### ISSUE TITLE
Py_func call slows down scipy

### ISSUE THREAD

**Issue by Bihaqo** [tensorflow/tensorflow#10005]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04.4 and MacOS 10.12.4 are affected
- **TensorFlow installed from (source or binary)**: tried both, reproduces on both
- **TensorFlow version (use command below)**: 1.0.1 and 1.1.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**: 
- **GPU model and memory**: both on Tesla K80 and on CPU version
- **Exact command to reproduce**: https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/z19wv70ogo15xg0/eigh%20speed%20bug.ipynb

Output of the enviromental script: https://pastebin.com/qdi8tJRV

### Describe the problem
Calling np.lianlg.svd via tf.py_fun forces scipy.linalg.eigh to become slower for some reason (4x slower on a server and 1.5x slower on my laptop). Here is the line that causes problems:
```
ret = tf.py_func(np.linalg.svd, [np.random.randn(2, 300)], [tf.float64, tf.float64, tf.float64])
%timeit sess.run(ret)
```
Before this line scipy.linalg.eigh used CPU for 2400% and worked in 13ms, after it it uses CPU for 600% and works in 43ms.

### Source code / logs
https://nbviewer.jupyter.org/urls/dl.dropbox.com/s/z19wv70ogo15xg0/eigh%20speed%20bug.ipynb

**Comment by yaroslavvb** [comment]
I couldn't reproduce it

I added the following to top of https://github.com/yaroslavvb/stuff/blob/master/svd_benchmark.py and ran it as `svd_benchmark.py eigh` and observed the same time.

```
import tensorflow as tf
sess = tf.Session()
ret = tf.py_func(np.linalg.svd, [np.random.randn(2, 300)], [tf.float64, tf.float64, tf.float64])
for i in range(10): sess.run(ret)
```

`py_func` runs the function provided in the main Python interpreter, so a simpler repro would be to run `np.linalg.svd` directly rather than through py_func. 

Also numpy backend may matter here, you can check with `python -c 'import numpy; numpy.__config__.show()'`

**Comment by yaroslavvb** [comment]
OK, I can reproduce it. It seems some weird interaction between TensorFlow and MKL.
Calling linalg.svd from inside py_func makes subsequent calls to eigh about 10% slower when you use MKL, but no effect in default BLAS

https://github.com/yaroslavvb/stuff/blob/master/github_pyfunc_slowness.py

Not sure why that would happen...perhaps the svd call in MKL ends up changing some defaults used by eigh? cc @vivek-rane since he seems to know about MKL
