### ISSUE TITLE
ResourceExhaustedError

### ISSUE THREAD

**Issue by lelayf** [tensorflow/tensorflow#10162]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Custom adaptation of tensorflow doc example
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.11.3 El Capitan
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: v1.1.0-rc0-61-g1ec6ed5 1.1.0 / python 3.5.2
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: N/A
- **GPU model and memory**: No CUDA-compliant GPU on Mac Book Pro
- **Exact command to reproduce**:  see full code below

### Describe the problem

The gist below fails reproducibly with the following error both from a jupyter notebook or the command line : 
```
ResourceExhaustedError (see above for traceback): ./models/m9-6/model.ckpt-826.data-00000-of-00001
	 [[Node: save/RestoreV2_6 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_6/tensor_names, save/RestoreV2_6/shape_and_slices)]]
```
I added some explict `del` and explicit garbage collection but that doesn't seem to change anything. I'm not sure if this is an OOM per se or if it is a different kind of resource exhaustion. In any case I wasn't expecting fitting a fresh model `m` repeatedly in a loop to be an issue so I'm reporting this in case it happens to be a TF issue.

### Source code / logs

https://gist.github.com/lelayf/f81b078a197b30490d6d52ba3f02f0a4

**Comment by michaelisard** [comment]
This is really more of a [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) question so please follow up with further questions there. I think the issue is that you are adding operations to the graph within your loop, so it's getting bigger and bigger and eventually running out of resources. You should probably create a new session for each experiment in order to properly garbage-collect the state in between experiments.
