### ISSUE TITLE
tf.resize_images return image full of noise but work on resize_image_with_crop_or_pad

### ISSUE THREAD

**Issue by wqj97** [tensorflow/tensorflow#10169]
- **OS OSX 10.12**:
- **TensorFlow installed from: source**:
- **TensorFlow version 1.2.0rc**:
- **Bazel version: 0.45**:
- **CUDA: CPU-only**:
- **GPU: CPU-only**:
```
img = tf.image.decode_jpeg(tf.read_file(path), channels=3)
img = tf.image.resize_images(img, [200, 200])
sess.run(img)
```
![damaged!](https://cloud.githubusercontent.com/assets/18662395/26419617/de547202-40f2-11e7-82c4-3640990d625c.png)

```
img = tf.image.decode_jpeg(tf.read_file(path), channels=3)
img = tf.image.resize_image_with_crop_or_pad(img, 200, 200)
sess.run(img)
```

![worked](https://cloud.githubusercontent.com/assets/18662395/26419629/ec09f1a6-40f2-11e7-9f44-0807633f60da.png)

**Comment by jart** [comment]
This sounds really bad, but I'm not able to reproduce it with 1.2.0rc0.

It would help if you could provide more information on how you got the above.

![image](https://cloud.githubusercontent.com/assets/49262/26479226/866525a2-4186-11e7-8154-407086ecc17f.png)

**Comment by wqj97** [comment]
please checkout this

[here](https://github.com/wqj97/tf_issue)

**Comment by asimshankar** [comment]
I believe this happens because:

- `tf.image.decode_jpeg` returns a `tf.uint8` tensor
- `tf.image.resize_image_with_crop_or_pad` doesn't do any numerical operations on the pixel values, it just crops or pads to change the shape of the input tensor but returns a tensor of the same type. In this case, it's a `tf.uint8` tensor.
- [`tf.image.resize_images`](https://www.tensorflow.org/api_docs/python/tf/image/resize_images) returns a `tf.float32` tensor
- `plt.imshow` expects either a uint8 array or a float array with values between 0 and 1.

Since the resized tensor is a float tensor but pixel values are not between 0 and 1, it's probably confusing `plt.imgshow`. Something like the following should fix things up:

```python
img = tf.image.decode_jpeg(tf.read_file(path), channels=3)
img = tf.cast(tf.image.resize_images(img, [200, 200]), tf.uint8)
sess.run(img)
```

Let us know if that works out.

**Comment by wqj97** [comment]
Yeah~ 
It works
Thx!

**Comment by ankit1997** [comment]
@asimshankar Thank you for the response.
But why does tf.image.convert_image_dtype not able to do the intended dtype conversion and tf.cast instead?

**Comment by paradisebee** [comment]
@ankit1997 
This might be a late response, but I'd like to help anyone who is searching for the solution.

The document for tf.image.convert_image_dtype says that:
"Images that are represented using floating point values are expected to have values in the range [0,1)"
However, after tf.image.resize_images, the value is float32 in range [0, 255). I am not sure how convert_image_dtype behaves in such case.

On the other hand, tf.cast directly casts the dtype without changing the value (well, with rounding of course) , so the output is a normal uint8 image.
