### ISSUE TITLE
tf.contrib.rnn.decoder does not require explicitly build encoder?

### ISSUE THREAD

**Issue by leesunfreshing** [tensorflow/tensorflow#10171]
As a beginner to tensorflow, I need to build a LSTM encoder decoder framework for images.
The tf.contrib.seq2seq.decoder does not require explicitly build encoder? Does it take the output from previous step as input? Thus the decoder_inputs are actually the input for encoder?

**Comment by danielwatson6** [comment]
+1. There is no full usage example available that I'm aware of. The closest thing to a complete example that I have found is in the unit tests; see [test for attention wrapper](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/seq2seq/python/kernel_tests/attention_wrapper_test.py) that builds the decoder.

The test makes the point that @leesunfreshing made valid. There's a difference between the encoder outputs and decoder inputs, but it's unclear what the decoder inputs even are (they're random numbers in the test).

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there.

@danielwatson6 We would be happy to welcome contributions for more example code, if it has tests.
