### ISSUE TITLE
tf.contrib.keras Conv2DTranspose output shape undefined

### ISSUE THREAD

**Issue by divamgupta** [tensorflow/tensorflow#10190]
The output shape for Conv2DTranspose is not fixed even when the input shape is fixed. The output shape for simple convolutioncomes to be correct.

```
import tensorflow as tf
L = tf.contrib.keras.layers.Conv2DTranspose( 512, (4,4), strides=(4, 4), padding='valid', data_format='channels_first' )
L2 = tf.contrib.keras.layers.Conv2D( 512, (4,4), strides=(4, 4), padding='valid', data_format='channels_first' )

img = tf.placeholder(tf.float32, shape=( 16 , 3 , 64 , 64 ))

x1 = L(img)
x2 = L2(img)

print x1.get_shape() # why ???
print x2.get_shape() # this is fine
```
Outputs : 
```
(?, 512, ?, ?)
(16, 512, 16, 16)
```

**Comment by michaelisard** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!
