### ISSUE TITLE
Definition of session -> run() in c++

### ISSUE THREAD

**Issue by ashokbugude** [tensorflow/tensorflow#10214]
Can I know the location of the code which contains the function definition of session-> run(const std::vector<std::pair<string, Tensor> >& inputs,
                     const std::vector<string>& output_tensor_names,
                     const std::vector<string>& target_node_names,
                     std::vector<Tensor>* outputs)

of session.h

After looking at docs , I found that its a part of TensorFlow C++ api whose code is present in tensorflow/code location, but I couldn't find exact location.
I could find only function declaration in session.h file in tensorflow/core/public but not its definition

I would like to modify the implementation of session -> run() and use it.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(That said, [`Session`](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/core/public/session.h#L119) is an abstract and there are multiple implementations of it, and hence multiple implementations of `Session::Run`, such as [`DirectSession::Run`](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/core/common_runtime/direct_session.cc#L364))

**Comment by ashokbugude** [comment]
Hi , I am trying to print log statements in 'DirectSession::Run' from https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/core/common_runtime/direct_session.cc#L364 

as described in https://stackoverflow.com/questions/24325463/how-to-get-console-output-of-log-lines-printf-cout-etc-of-c-library-use

and then built the libraries from source file.

I have then used the library in android ndk , but the logs are not getting printed in android studio.
Please help in debugging the .so file code from Android Studio using ndk
