### ISSUE TITLE
Android build error: tensorflow/core/framework/op_gen_lib.h:22:59: fatal error

### ISSUE THREAD

**Issue by atrah22** [tensorflow/tensorflow#10273]
Hello,

I previously built (some earlier releases of tensorflow) succesfully for android platform (aarch64). However, I get this  following error "./tensorflow/core/framework/op_gen_lib.h:22:59: fatal error: tensorflow/core/framework/op_gen_overrides.pb.h: No such file or directory
 #include "tensorflow/core/framework/op_gen_overrides.pb.h"
" incase of the latest release.

I did run "download_dependencies.sh", "compile_android_protobuf.sh" prior to the command "make -f ./tensorflow/contrib/makefile/Makefile TARGET=ANDROID"

There is no file called "op_gen_overrides.pb.h"!

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

In particular, things like what version of the code you're building (is it the release branch or some specific commit? etc.)

FYI @andrewharp
