### ISSUE TITLE
Tensorflow Windows Visual Studio Help

### ISSUE THREAD

**Issue by mrcauamst** [tensorflow/tensorflow#10285]
Hi all,
I'm VietNamese, my English is not good.
I'm programming mobile robot with Aria ,C++ ,OpenCv and Tensorflow
I'm using Windows and Visual Studio 2012. I can't setup Tensorflow C++.
how to setup Tensorflow C++ and connect to VS2012
I hope everyone will train and help me. 
Thank you.

**Comment by gunan** [comment]
TensorFlow on windows needs at least Visual Studio 2015, due to required C++11 support.
You will need to upgrade visual studio otherwise you wont be able to compile TF on your system.

You can find some more information here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/cmake/README.md
