### ISSUE TITLE
Problem exporting the weight matrix for each layer along with all the hyper parameters of each layer and their connectivity.

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/tensorflow#10329]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:

Yes, I have modified Tensorflow before but not w.r.t. this problem. (I used the binaries provided by conda and pip)

- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

macOS 10.12 Sierra for iMac

- **TensorFlow installed from (source or binary)**:

1.1.+

- **TensorFlow version (use command below)**:

pip and pip version

- **Bazel version (if compiling from source)**:

n/a

- **CUDA/cuDNN version**:
n/a
- **GPU model and memory**:
n/a
- **Exact command to reproduce**:

n/a

### Describe the problem

How do you extract the weights of each of the intermediate layers in tensorflow?  I use the /tmp/cifar-train but I couldn't find the exact location of the weight matrix along with the hyper parameters?  

![screen shot 2017-05-31 at 10 18 13 am](https://cloud.githubusercontent.com/assets/9545735/26639453/7ca8beb2-45ea-11e7-8ae6-d1fba7c190d5.png)

I see the following files above but there is no documentation that tells how to export the weight matrix along with the hyper parameters for the entire network and each layer for the exact configuration.

### Source code / logs

n/a

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(That said, in this case the files you're looking at are produced by [`tf.train.Saver`](https://www.tensorflow.org/api_docs/python/tf/train/Saver) - whose documentation will describe the process of exporting and importing tensor contents a bit).

Hope that helps.
