### ISSUE TITLE
How to add cwise_op_floor_mod to build libtensorflow-core.a for ANDROID

### ISSUE THREAD

**Issue by kzos** [tensorflow/tensorflow#10325]
OS: Ubuntu 16.04 64bits
Android Version: 7.1 (Nougat)
NDK Version: android-ndk-r12b
HEXAGON SDK: 3.1

When i am trying to build benchmark app, using make build, floor mod operation is not getting added by default, 

### By default:- 
when I issue below command, cwise_op_floor_mod.cc is not getting compiled against most of the files getting compiled in core/kernel/ folder
`make -f tensorflow/contrib/makefile/Makefile TARGET=ANDROID NDK_ROOT=~/android-ndk-r12b`

### Changes tried to add floor mod but failed:-
tensorflow/core/kernels/cwise_op_floor_mode.cc - changes in bold 

--- snip ---

```
#include "tensorflow/core/kernels/cwise_ops_common.h"
 
 namespace tensorflow {
 REGISTER2(BinaryOp, CPU, "FloorMod", functor::safe_floor_mod, int32, int64);
 REGISTER2(BinaryOp, CPU, "FloorMod", functor::floor_fmod, float, double);
 
 **REGISTER_KERNEL_BUILDER(Name("FloorMod")
                             .Device(DEVICE_CPU)
                             .HostMemory("x")
                             .HostMemory("y")
                             .HostMemory("z")
                             .TypeConstraint<int32>("T"),
                         BinaryOp<CPUDevice, functor::safe_floor_mod<int32>>);**
 #if GOOGLE_CUDA
 // A special GPU kernel for int32.
 // TODO(b/25387198): Also enable int32 in device memory. This kernel
 // registration requires all int32 inputs and outputs to be in host memory.
 REGISTER_KERNEL_BUILDER(Name("FloorMod")
                             .Device(DEVICE_GPU)
                             .HostMemory("x")
                             .HostMemory("y")
                             .HostMemory("z")
                             .TypeConstraint<int32>("T"),
                         BinaryOp<CPUDevice, functor::safe_floor_mod<int32>>);
 #endif

```
-- eo snip --

somebody help out adding floor mod in the build.
thanks

**Comment by asimshankar** [comment]
Not all operations are included for Android by default in order to reduce binary size.

To include `cwise_op_floor_mode.cc` in your build, you'll need to add that to [`tf_op_files.txt`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/tf_op_files.txt) (more details in the [README](https://github.com/tensorflow/tensorflow/blob/4be052a5fc9e6569fcf07da3e9615b463e008266/tensorflow/contrib/makefile/README.md#fixing-makefile-issues))

Or if you use bazel, then to the [`//tensorflow/core/kernels: android_extended_ops_group1`](https://github.com/tensorflow/tensorflow/blob/fe589d9/tensorflow/core/kernels/BUILD#L4126) target.

Let us know if that works.

FYI @andrewharp

**Comment by kzos** [comment]
it does works, thanks
