### ISSUE TITLE
What are the 'from' and 'to' dimensions of transition_params in tf.contrib.crf.crf_log_likelihood?

### ISSUE THREAD

**Issue by filipealeixo** [tensorflow/tensorflow#10378]
On TensorFlow, I want to pass a transition_params matrix as argument to tf.contrib.crf.crf_log_likelihood (https://www.tensorflow.org/api_docs/python/tf/contrib/crf/crf_log_likelihood) in order to initialize the transitions matrix of the CRF. Although, in the documentation, it doesn't state which dimension of this matrix corresponds to the first tag of the transition and which dimension corresponds to the second.

So, let T be the transitions matrix, does T[i,j] represent the score of the transition from tag i to tag j, or is it the other way around?

**Comment by jart** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is a larger community that reads questions there.

We also give amazing code reviews to anyone generous enough to send us pull requests that improve the documentation of contrib packages.
