### ISSUE TITLE
Limit the number of images in a summary [feature request]

### ISSUE THREAD

**Issue by fvisin** [tensorflow/tensorflow#10373]
When working on dense prediction tasks it is very convenient to show the predictions of the network in TensorBoard to evaluate them qualitatively during training. Even if TensorBoard shows only a subset of these images, all the summaries that have been saved since the beginning of times are kept on disk. The occupied space grows with the size of the dataset, the sampling frequency and the number of experiments, often resulting in a huge waste of space. When the disk space is limited, this can heavily limit the number of experiments logs one can run simultaneously and/or keep stored.

It would be great to have a way to either limit the number of images saved on disk or to remove some of them (e.g., for old experiments). Here is what I suggest:

- Add an argument to `tf.Summary.Image` to define how many images should be kept on disk (e.g., `buffer_size` or `steps_to_retain`). Also add an extra argument (e.g., `retain_strategy`) to select the strategy to define which images should be kept (e.g., keep latest, sample uniformly, ..).
- Add a function to remove some of the stored images programmatically.

This feature request is partially related to https://github.com/tensorflow/tensorflow/issues/5039
Also related to this SO thread: https://stackoverflow.com/questions/41543954/remove-image-outputs-from-tensorboard/41690170

**Comment by asimshankar** [comment]
I don't believe we have any immediate plans for working on this, so I'm going to mark this as Contributions Welcome, with the expectation that this might be updated as things towards #5039 happen.

If anyone does want to assist with this, it may make sense to discuss some design here before investing too much time in implementation.

Thanks!

**Comment by pbanavara** [comment]
Hey guys, I have been working on TF for about 3 months now and would like to make a contribution. I can spare about 30 minutes every day. Please let me know what is the qualifying criteria for contribution. 

Of the suggested approaches, I think the first approach works better, since there are future plans to display more than the current subset of images contained in the tensor, as per the SO thread.  
Instead of adding new API parameters - can the max_output parameter be used to determine the summary to be stored on the disk ? Going by the documentation, max_outputs defines the max number of batch elements to generate images for.

**Comment by dandelionmane** [comment]
@fvisin The summary doesn't really have any control or influence over how things are retained on disk. Basically, everything written to disk stays there forever until you manually remove it. 

There's some work on the TensorBoard side to switch TB over to using a sql database on the backend, at which point it would be feasible to just delete the old event files directly because a subset of their data will have already been ingested into TensorBoard.

If you want to write code for sweeping and downsampling old event files, you're welcome to, but I think it would be better to wait and see how things play out with converting the TensorBoard backend to sql. Pinging @jart so she can chime in on this; also closing as infeasible.

@pbanavara, that's awesome that you want to contribute. I don't think this one would be the best one to implement. There's another TensorBoard issue [here](https://github.com/tensorflow/tensorboard/issues/30) which a number of people thumbs-up'd and I think would be a good candidate for an external pull request.

**Comment by fvisin** [comment]
Thanks @dandelionmane , I look forward to an sql backend for Tensorboard. Is there a PR or an issue I can subscribe to, to follow the advancement? I couldn't find any.

**Comment by dandelionmane** [comment]
I would take a look here https://github.com/tensorflow/tensorboard/issues/92
