### ISSUE TITLE
Printing TensorFlow Library Logs in Android Studio

### ISSUE THREAD

**Issue by ashokbugude** [tensorflow/tensorflow#10416]
I have built Tensor Flow using Bazel  and am using the generated TensorFlow Libraries in Android Studio
for ndk.

But I do not find the logs of Tensor Flow being printed in Android Studio.
Can I know how do I acheive this .

I have tried using Android/log.h in TensorFlow code but of no use

**Comment by andrewharp** [comment]
There should be a "logcat" tab on the "Android Monitor" view that displays this. TensorFlow prints messages in the standard Android fashion so it's no different than any other app.

Any followup logging questions are better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since this is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by ashokbugude** [comment]
Thanks, but the logs of tensorflow are not being printed in Logcat of
Android ndk.
