### ISSUE TITLE
SavedModelBundle.java's load() method is not working with RandomForest Saved Model 

### ISSUE THREAD

**Issue by shashank734** [tensorflow/tensorflow#10454]
------------------------

### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OS 10.12
- **TensorFlow installed from (source or binary)**: Binary 
- **TensorFlow version (use command below)**: Tried with both 1.1.0 and 1.2.0-rc1
- **CUDA/cuDNN version**: Running on CPU

I have SavedModel using TensorForestEstimator (RandomForest) by using export_savedmodel() it was saved successfully and able to load from SavedModel-cli too. But when trying to load using 

```
val SAVED_MODEL_PATH =
      "/Users/Documents/tensordata/1496652787";
    val bundle = SavedModelBundle.load(SAVED_MODEL_PATH, "serve");
```
 It's giving following error -:

```
Exception in thread "main" org.tensorflow.TensorFlowException: Op type not registered 'TreePredictions'
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:38)
	at ai.tenten.ml.ClassifyITCase$.main(ClassifyITCase.scala:59)
```
I am able to load Other saved models like HalfPlusTwo Regression and mnist dense Predict model successfully. Only in RandomForest It's giving error I thing some op is missing from build or Java API is not updated.

**Comment by asimshankar** [comment]
@shashank734 : Alas, at this time, any ops defined in the Python `tf.contrib` namespace are not supported in the release binaries of other languages. This stems from the fact that these ops are implemented in their own binaries (in their own shared libraries) and we currently do not support loading custom ops.

That's something we're looking into (making custom operations in `tf.contrib` available to other binary distributions), but there is no timeline on that.

In the mean time, if you're willing to build from source, I can suggest a workaround, which would involve compiling from source. Something like:

1. Checkout the source and install bazel:

```sh
git checkout github.com/tensorflow/tensorflow
cd tensorflow
git checkout r1.2 # Just so that you're in the release branch

brew install bazel
```

2. Setup the build system to statically link the contrib ops into the JNI library by adding:

```
        "//tensorflow/contrib/tensor_forest:tensor_forest_ops_op_lib",
        "//tensorflow/contrib/tensor_forest:tensor_forest_kernels",
```

to the `deps` section of the [`libtensorflow_jni.so` build target](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/java/BUILD#L163)

3.  Build the JNI library:

```sh
yes "" | ./configure
bazel build -c opt //tensorflow/java:libtensorflow_jni.so
```

Now, you'd want to make this library instead of the one packaged in the release binary distributions. You can do that by adding `-Djava.library.path=bazel-bin/tensorflow/java` to the `java` command.

Do let us know if this works or not.

Hope that helps.

(FYI @allenlavoie @girving @martinwicke )

**Comment by shashank734** [comment]
I will try this. But still wait for changes before deploying to production.

**Comment by asimshankar** [comment]
This should now be doable with TensorFlow 1.4. See https://stackoverflow.com/questions/47276624/issue-while-loading-serving-tensorflow-model-in-java-using-estimators/47277367#47277367

You'll have to adjust the arguments to `TensorFlow.loadLibrary()` to correspond to the shared libraries included in the `tf.contrib.tensor_forest` module.

I'm closing this bug out since I believe the process described in the stackoverflow thread will work (albeit it could be made smoother). Please feel free to re-open if you run in to trouble or have comments.

Thanks!
