### ISSUE TITLE
TensorFlow logging configuration is non-standard

### ISSUE THREAD

**Issue by taion** [tensorflow/tensorflow#10498]
Ref https://github.com/tensorflow/tensorflow/issues/8023

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: Docker image
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: Per Docker image
- **GPU model and memory**: K80
- **Exact command to reproduce**: N/A

### Describe the problem
The logging configuration in `tf_logging` is odd and inconsistent with how things are generally done in Python.

In general, it's typical to attach handlers to the root logger in Python: https://docs.python.org/2/library/logging.html#logging.Logger.propagate

However, because `tf_logging` sets up its own stream handler, and does not disable the propagate flag, anybody who does follow the standard Python convention of attaching handlers to the root logger gets duplicated log output from TensorFlow.

Per https://github.com/tensorflow/tensorflow/issues/8023, while this isn't a bug per se, it's still wrong and undesirable.

The cleanest way forward is probably to just set `propagate=False` on the TF logger.

**Comment by tatatodd** [comment]
After browsing some of the code history, it looks like the current behavior was an explicit implementation choice made back in Nov 2015.

Here's the git commit that brought it in:
https://github.com/tensorflow/tensorflow/commit/d50565b35e886e7c3a201ea2f088790ed4b28de4

For reference, the internal tracking ID is cl/107710311 and the description is:
```
Scope tensorflow logging to prevent namespace pollution for
users who import tf and configure their own loggers.
```

@dave-andersen and @mrry were involved in the original change, and may have more details.  I'm re-assigning to @mrry since he knows Python much better than I do, and may have some opinions on the suggestion of setting `propagate=False`

**Comment by taion** [comment]
To clarify, I think it's absolutely correct that TensorFlow logging is scoped under `tensorflow`. If anything, a more common pattern in Python libraries is for loggers to be scoped to each individual module, as this exposes more control over customizing log level on a more granular basis.

What's suboptimal here is that the logger both has a handler _and_ propagates. This means that if I follow standard best practices, anything that TF tries to log hits both the handler on the `tensorflow` logger, and then my own handler on the root logger, so I end up getting two lines of log output.

**Comment by mrry** [comment]
I think we'd welcome contributions to fix this!
