### ISSUE TITLE
python3.5 support and @ operator with  __matmul__  method

### ISSUE THREAD

**Issue by DSLituiev** [tensorflow/tensorflow#1062]
Are there any plans to include Python3.5 support (incl. binaries) and [dedicated matmul `@` operator](https://www.python.org/dev/peps/pep-0465/)?

**Comment by martinwicke** [comment]
Our python3 binaries should work with python3.5 (although currently the wheels require renaming), and adding __matmul__ seems innocuous enough. However nobody is working on that now, it's likely a feature we'll accept if someone writes it.

**Comment by vrv** [comment]
I think we'd want to do this at the same time as supporting broadcasting for matmul in https://github.com/tensorflow/tensorflow/issues/216, otherwise the semantics might be confusing.

**Comment by girving** [comment]
Yes, we need to merge `matmul` and `batch_matmul` before doing this, and someone decided to give them different sets of attributes (I can't imagine why).

**Comment by ibab** [comment]
@girving: By merging, do you mean unifying the two ops, or providing a Python wrapper that switches between them intelligently?

Is the difference in attributes (transpose vs adjoint) something you would want to keep for backwards compatibility, or would you plan to adjust one of the ops to match the other one?

**Comment by girving** [comment]
@ibab: I mean unifying the two ops.  The Python wrapper is problematic since we don't necessarily know which to use at graph construction time, so `tf.cond` would be necessary.  The difference in attributes is pretty frustrating; @rmlarsen: did we have a nice conclusion as to which attributes we want?

**Comment by ibab** [comment]
In order to implement the semantics of `@` properly, we should use an op that exactly matches the behaviour of `numpy.matmul`: http://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.matmul.html#numpy.matmul
Otherwise things would get very confusing when users assume that the tensorflow `@` will work like the numpy one.

Here's a copy of the behaviour described in the docs:
 - If both arguments are 2-D they are multiplied like conventional matrices.
 - If either argument is N-D, N > 2, it is treated as a stack of matrices residing in the last two indexes and broadcast accordingly.
 - If the first argument is 1-D, it is promoted to a matrix by prepending a 1 to its dimensions. After matrix multiplication the prepended 1 is removed.
 - If the second argument is 1-D, it is promoted to a matrix by appending a 1 to its dimensions. After matrix multiplication the appended 1 is removed.
 - Multiplication by a scalar is not allowed, use * instead. Note that multiplying a stack of matrices with a vector will result in a stack of vectors, but matmul will not recognize it as such.

So there would need to be some extra work on top of unifying the two ops.

**Comment by girving** [comment]
@ibab I believe all of those semantics are backwards compatible with what we currently have, but @rmlarsen can correct me if I'm wrong.

**Comment by matteson** [comment]
+1 for this issue (general tensordot). I ran into wall on something I was implementing that would really benefit from this.

**Comment by girving** [comment]
@rmlarsen matmul and batch_matmul are merged, right?  That was the major issue blocking this in the past, so I think it would be straightforward to add.  I believe we would need to extend our matmul to handle 1-D tensors on either side, but this would be a welcome change at least to me.

Cc @aselle since this is related to numpy compatibility.

**Comment by ageron** [comment]
About 60 lines of tests, 4 lines of documentation, and 3 lines of "actual" code.  ;-)

**Comment by ageron** [comment]
A sneak preview:
```
>>> import tensorflow as tf
>>> import numpy as np
>>> a = [[1., 2.]]
>>> b = [[3., 4., 5.], [6., 7., 8.]]
>>> np_a = np.array(a)
>>> np_b = np.array(b)
>>> np_dot = np_a @ np_b
>>> tf_a = tf.constant(a)
>>> tf_b = tf.constant(b)
>>> tf_dot = tf_a @ tf_b
>>> tfpy_dot = tf_a @ b
>>> pytf_dot = a @ tf_b
>>> tfnp_dot = tf_a @ np_b
>>> nptf_dot = np_a @ tf_b
>>> with tf.Session():
...   print(tf_dot.eval())
...   print(tfpy_dot.eval())
...   print(pytf_dot.eval())
...   print(tfnp_dot.eval())
...   print(nptf_dot.eval())
...   print(np_dot)
... 
[[ 15.  18.  21.]]
[[ 15.  18.  21.]]
[[ 15.  18.  21.]]
[[ 15.  18.  21.]]
[[ 15.  18.  21.]]
[[ 15.  18.  21.]]
```

**Comment by ageron** [comment]
Note that although NumPy arrays support the @ operator, they play nice with unknown types: when the _rhs_ is not a NumPy array and it has an `__rmatmul__()` method, they return `NotImplemented` so that python calls that method instead.  This is why `np_a @ tf.b` works like a charm, thanks to NumPy.  I think I will open a feature request to make tensors behave the same way, returning `NotImplemented` rather than raising an exception when any magic function (e.g., `__add__()`) is called with an unsupported object type, and that object has an `__r*__` method.

**Comment by girving** [comment]
@ageron The problem with that is that "unsupported object" type means anything not convertible to a numpy array or `Tensor`.  It's hard to tell what those things are without trying to the conversion, and in Python the conversion can be a lossy operator (I hate this bit of Python).

**Comment by ageron** [comment]
@girving I opened #8051 to discuss this issue. I proposed a solution inspired from NumPy's `__array_priority__` scheme.
