### ISSUE TITLE
Implement architecture-independent fallback in tensorflow/workspace.bzl

### ISSUE THREAD

**Issue by brunoalr** [tensorflow/tensorflow#10649]
Archictecture-dependent binaries such as `nodejs` limits portability to different targets (namely, I'm interested in Tensorflow ppc64le builds). I tried replacing x64 binaries with ppc64 in the cached dirs and managed to compile Tensorflow (see https://github.com/tensorflow/tensorflow/issues/10306).

This issue is similar to https://github.com/bazelbuild/rules_closure/issues/207.

**Comment by aselle** [comment]
Thanks for experimenting. It would be great if you could contribute a pull-request of this!

**Comment by gut** [comment]
@aselle But what was the motivation for using a binary on bazel? I tried to get this [answer on StackOverflow](https://stackoverflow.com/questions/44413137/why-does-bazels-rules-closure-downloads-platform-specific-binaries-instead-of-s) but I'm still waiting.

For now, IMHO, the best solution is to ask bazel to compile these sources instead of downloading a binary.

**Comment by capone3691** [comment]
Thk

**Comment by gunan** [comment]
nodejs binary is used by tensorboard, I think.
In TF we should not be downloading and using any binaries, except if you enable MKL support.

Should this be filed against tensorboard repository?

**Comment by gunan** [comment]
Closing under TF as we should not have nodejs dependency anymore in TF.
