### ISSUE TITLE
Undocumented change in sharing variables from version 1.0 to 1.1

### ISSUE THREAD

**Issue by olyaromanyuk** [tensorflow/tensorflow#10652]
### System information
- **Custom code, a minimal reproducible example provided below**:
- **Linux Ubuntu 14.04**:
- **TensorFlow installed from binary using pip**:
- **TensorFlow version 1.0.1 and 1.1.0**:
- **CUDA 8.0/cuDNN 5.1**:
- **GeForce GTX 1080**:

### Problem
Variable scopes and sharing works different in versions 1.0.1 and 1.1.0. I try to enter a non-reusing variable scope after executing tf.get_variable_scope().reuse_variables(). This results in different values of tf.get_variable_scope().reuse inside this scope. When using version 1.0.1 it is False while when using 1.1.0 it is True. [The sharing variable guide](https://www.tensorflow.org/versions/r1.0/programmers_guide/variable_scope) states that setting reuse = False inside a reusing scope is not the desired behavior, but the guide is completely the same for both versions. Moreover, no changes in handling variable scopes are mentioned in release notes for version 1.1. 

### Source code / logs
```
import tensorflow as tf
print tf.__version__

with tf.variable_scope('foo'):
    assert tf.get_variable_scope().reuse == False, tf.get_variable_scope().reuse
    tf.get_variable_scope().reuse_variables()
    assert tf.get_variable_scope().reuse == True, tf.get_variable_scope().reuse
    with tf.variable_scope(tf.get_variable_scope(), reuse=False):
       print tf.get_variable_scope().reuse
```
Output:

- Version 1.0.1
```
1.0.1
False
```
- Version 1.1.0
```
1.1.0
True
```

**Comment by lukaszkaiser** [comment]
You are absolutely right: in 1.0.1 there was a bug that allowed "False" to override inheritance in a variable scope. We consider this a bug because variable scopes are meant to be nested inside functions and libraries. Imagine you're calling a sub-model defined in a library and you want to reuse all of it. If that model ever called "False" like in 1.0.1, you'd get a very wrong behavior that'd be potentially impossible to correct without changing the library. In 1.0.1, to get the correct behavior, you had to use "None" instead of "False" -- in fact we documented that you should always use only those two, but "False" worked like above. In 1.1.0 we changed this to avoid problems like the one above. But if you have a clear use-case for this, let us know!
