### ISSUE TITLE
how can combining cnn with convlutional lstm

### ISSUE THREAD

**Issue by jeansely** [tensorflow/tensorflow#10697]
Hi,

i want to process a image in cnn+convolutinal_lstm , in the connection point  between to network , shape(None,100,100,64) for cnn the should insert to convolution_lstm network ,
but not  match output cnn with input convlutinal_lstm.
is any example for this combination?

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

If you think after doing that, it is a bug, submit your reproducible test case. Thanks!
