### ISSUE TITLE
in the test dataset the use of different batch_size will get different results. ,why?

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#10726]
When I used kears and tensorflow training after the checkpoint, after stopping the process, when I was found in the test, the use of different batch_size will get different results. The When batch_size = 1 when the error rate is high, but when the batch_size = 128, the error rate is not so high. The The The Why is this? The So what about my online service?

**Comment by aselle** [comment]
I'm sorry, but I am closing thi, since it is not a TensorFlow question, this is a machine learning algorithm question. Please read references on what batch size means, e.g. here is one of the first google results. 
https://stats.stackexchange.com/questions/153531/what-is-batch-size-in-neural-network
