### ISSUE TITLE
The current makefile is incomplete

### ISSUE THREAD

**Issue by beinanwang** [tensorflow/tensorflow#10754]
Can someone provide a makefile that is equivalent to //tensorflow:libtensorflow_cc.so? This current makefile is missing many C++ API's. Is there a way to find all the files needed to build //tensorflow:libtensorflow_cc.so (recursively)?

**Comment by aselle** [comment]
Is there anyway but manually adding things, @petewarden? I know it uses many globs to avoid trivial new files but new directories I imagine are an issue.

**Comment by petewarden** [comment]
The tricky part with libtensorflow_cc is that it needs to compile a host-side tool first to generate the .cc and .h interfaces from the op definitions. That extra complexity means that neither the Bazel Android build process nor the Makefile build the lib. For the Makefile we try to mirror its globs and file list from the equivalents in the Bazel build process for Android, but since the CC interface isn't there, we can't do that in this case.

**Comment by kyo744** [comment]
I have tried the following steps to add the C and C++ APIs:
1. Add all .cc files in the /c and /cc directories to the Makefile.
2. Add all .pb.cc .pb_text.cc generated by Bazel to the Makefile.
3. Include the dependencies (gtest, .pb.h and pb_text.h).
4. Use the Makefile to create libtensoflow-core.a and .so.

The compilation terminates without error and the .a and the .so files are produced. However, when I try to use them to compile programs that use Tensorflow C or C++ APIs, I get undefined reference errors.

**Comment by petewarden** [comment]
From your description, it sounds like they're not being linked in, so you should look at what the command line that links all the .o files in the makefile logs looks like, and ensure it has the ones generated from the .cc's you want.

As a note, this sort of manual compilation will be a bit fragile, since you'll have to do the same steps #1 and #2 whenever ops are added or changed.
