### ISSUE TITLE
How to update the variable list for which the optimizer need to train in tensorflow?

### ISSUE THREAD

**Issue by issa-s-ayoub** [tensorflow/tensorflow#10795]
How to update the list of variables for the optimizer to train in tensorflow? In other words, if we have the following optimizer:

`optimizer = tf.train.AdamOptimizer(learning_rate).minimize(cost_scalar, var_list=my_var_list)`

I need to update my_var_list for example while fine tuning the network. That is, I am going to remove the variable which I no longer need to train and keep the others. Example, fine tuning the dense layer in a convolutional neural network.

Any help is much appreciated!!

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

However, one thing you could do is just make a new optimizer op that contains a changed set of var_list.
