### ISSUE TITLE
conv1d not in tf.contrib.layers

### ISSUE THREAD

**Issue by erickrf** [tensorflow/tensorflow#10790]
As of tensorflow 1.2, conv1d can be found under `tf.layers`, and not `tf.contrib.layers`, where you find conv2d. Shouldn't it be available under the contrib namespace? By the way, what's the conceptual difference between both submodules?

**Comment by martinwicke** [comment]
tf.contrib.* should be considered temporary. We make no guarantees about the stability of the modules and symbols in there. They may change behavior (even in not backwards-compatible ways) at any time. 

The symbols in core (anything in the tensorflow module that is not in contrib) are subject to semver guarantees, meaning they will not change behavior in backwards-incompatible ways between minor releases. Backwards incompatible changes are only allowed between major releases.

We use contrib as a staging ground where we try out and test ideas. When those ideas mature and stabilize, we move them out of contrib, and in the process remove deprecated parts or fix problems that we may have identified while working with them for a while.

Once we have a core module we don't really want to maintain the contrib versions. The only reason to not delete them is in order to avoid unnecessarily breaking users of the contrib versions. For layers, the contrib versions (of layers already in core) should be considered deprecated and subject to eventual removal. If we make improvements to the core version (such as adding conv1d) we may not also backport these improvements to the contrib modules.
