### ISSUE TITLE
Original error was: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by hkyq** [tensorflow/tensorflow#10808]
Hello. I've been getting 'Original error was: DLL load failed: The specified procedure could not be found' error when attempting to import tensorflow. I'm on Windows 10 with python 3.6.00. I've checked some issues like mine but I already have visual studio c++ 2017. I attempted to download 2015 however I was told I already have it.  I installed tensorflow with:

    Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?:
    No
    TensorFlow installed from (source or binary)?:
    binary
    TensorFlow version:
    Can't do version because I the error when importing
    Bazel version (if compiling from source):
    NA
    CUDA/cuDNN version:
    8.0 I think
    GPU Model and Memory:
    Nvidia 1080 4gb
    Exact command to reproduce:
    pip3 install --upgrade tensorflow-gpu

Here is the full error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\__init__.py", line 47, in <module>
    import numpy as np
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\__init__.py", line 142, in <module>
    from . import add_newdocs
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\__init__.py", line 8, in <module>
    from .type_check import *
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\lib\type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "C:\Users\David\AppData\Local\Programs\Python\Python36\lib\site-packages\numpy\core\__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError:
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.
Original error was: DLL load failed: The specified procedure could not be found.

I tried reinstalling numpy too, same error.

**Comment by timo92** [comment]
I just ran into a similar issue.

I installed python 3.5.3 (["Tensorflow only supports python 3.5.x on Windows"](https://www.tensorflow.org/install/install_windows#installing_with_native_pip) ) and followed solutions provided in [this](https://stackoverflow.com/a/43566341) stackoverflow answer.

For me this turned out to be an issue with my PATH variable for the cuDNN dll.

**Comment by hkyq** [comment]
Works @timo92 , thanks.

**Comment by VadVor** [comment]
I installed python 3.6 and Windows 8.1 x64.
I have similar issue with numpy:

ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: DLL load failed: The specified procedure could not be found.

**Comment by knightcube** [comment]
I got the same problem and i am still looking for a solution

**Comment by DeepthiKarnam** [comment]
Same here.

**Comment by smogharehabed** [comment]
same here

**Comment by smogharehabed** [comment]
I had the same error with numpy. I tried using Anaconda prompt instead of cmd. I installed numpy with typing "conda install numpy" and then the problem was gone.
