### ISSUE TITLE
load_csv_with_header

### ISSUE THREAD

**Issue by LuoJiaji** [tensorflow/tensorflow#10814]
When I run iris_monitors.py file, It has an error :
File "C:\software\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 47, in load_csv_with_header
header = next(data_file)
StopIteration

**Comment by LuoJiaji** [comment]
When I  run iris_monitors.py file, It has an error : 
  File "C:\software\Python\Python35\lib\site-packages\tensorflow\contrib\learn\python\learn\datasets\base.py", line 47, in load_csv_with_header
    header = next(data_file)
StopIteration

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, what platform you are using, and what versions it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

I did try it on my Linux machine, and it worked fine.

**Comment by LuoJiaji** [comment]
thanks for your attention. I am a beginner of TensorFlow. 
I use Win 10 ,and the version of TensorFlow is 1.0.1 , TensorFlow is installed from binary.

**Comment by lxy6** [comment]
I got the same problem, have you solved it?
