### ISSUE TITLE
py_func returning string leaks memory

### ISSUE THREAD

**Issue by gaohuazuo** [tensorflow/tensorflow#10822]
TF version: 1.2.0

```python
import tensorflow as tf

tf.InteractiveSession()
s = b' '*1000000
x = tf.py_func(lambda: s[1:], [], tf.string) # leaks
# x = tf.py_func(lambda: s, [], tf.string) # does not leak
# x = tf.py_func(lambda: len(s[1:]), [], tf.int64) # does not leak
while True:
    x.op.run()
```

**Comment by caisq** [comment]
cc @alextp 

This is fixed in the master branch by 

https://github.com/tensorflow/tensorflow/commit/27f1b80c22115f134fd959a7c0fe013a21784795#diff-6fed5e0cf86f9cf983a6c73438b0f7e1

But the fix is not in 1.2. So please either use the nightly builds (see home README.md for download addresses) or wait for 1.3.
