### ISSUE TITLE
GPU option allow_growth and CUDA_ERROR_OUT_OF_MEMORY

### ISSUE THREAD

**Issue by CY-dev** [tensorflow/tensorflow#10869]
Hi,

I tried to build a LSTM model on 30G data with a aws machine p2.xlarge with 60G memory and a gpu with 12G memory. The performance is inconsistent. Sometimes we get it to work but sometimes we encounter CUDA_ERROR_OUT_OF_MEMORY. The answer at https://stackoverflow.com/questions/39465503/cuda-error-out-of-memory-in-tensorflow suggests setting a gpu option allow_growth to False. It refers to the source code where the change could be made:
https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/core/protobuf/config.proto

But in the code I notice the only line containing "allow_growth" is this:
  bool allow_growth = 4;
It looks strange to me. Could you explain why allow_growth is assigned a integer value 4?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

For reference, config.proto is written in the Protocol Buffers language.  The '4' is the field id, not a value that's being assigned.  Details here: 
https://developers.google.com/protocol-buffers/docs/overview
