### ISSUE TITLE
word2vec error sequence index must be integer, not 'slice'

### ISSUE THREAD

**Issue by shanalikhan** [tensorflow/tensorflow#10866]
Im tring to run the code :
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/word2vec/word2vec_basic.py#L117

But get the exception on the Line 117 
as 
sequence index must be integer, not 'slice'

I want to ask if this really a problem in the tensorflow file or its just me facing this error.

**Comment by printdhruv** [comment]
I guess it's an issue on your end. I have no issue executing it with `Python 2` and `Python 3.` on `Ubuntu 17.04` distribution  

I would suggest doing the following for `Python 2` or you may use pip3 for `Python 3.`

-  `pip install --upgrade tensorflow` 

-   Update all dependencies which you are required for `word2vec_basic.py`

-   Try running it again. If you don't get success than share your OS, Tensor flow and Python log.

**Comment by rohan100jain** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by endymecy** [comment]
I also have this error. 

platform: mac os 10.12.5
tensorflow version: r1.0.1
python version: 2.7.13

**Comment by printdhruv** [comment]
@endymecy Did you tried executing `pip install --upgrade tensorflow` as stated in my above post?

**Comment by endymecy** [comment]
After I upgrade tensorflow to 1.2.0 and I don't get success

**Comment by shanalikhan** [comment]
I changed code in that line to make it work

**Comment by shanalikhan** [comment]
I'm in office cant access that code
instead of 
> buffer[:] = data[:span]

I used something like

> for word in data[:span]
>   buffer.append(data)

**Comment by cy89** [comment]
@shanalikhan When you have a moment with access, it'd be lovely to have the precise answer, and then we could close this issue. Thanks for your help!

**Comment by odhinnsrunes** [comment]
The actual code that worked for me was to replace:
`      buffer[:] = data[:span]`

With:

`      for word in data[:span]:
        buffer.append(word)`

**Comment by shanalikhan** [comment]
@cy89 its the same one i wrote :)
As this issue was opened by me, I should close this issue as its solved
