### ISSUE TITLE
Adding summaries changes random number generation

### ISSUE THREAD

**Issue by ilblackdragon** [tensorflow/tensorflow#1091]
Here is a simple example:
````
import tensorflow as tf

with tf.Session('') as sess:
    tf.set_random_seed(42)
#    tf.scalar_summary('d', 1.)
    y = tf.get_variable('y', [1, 5])
    sess.run(tf.initialize_all_variables())
    print sess.run(y)
```

Commenting / uncommenting scalar_summary changes results:
```[[ 1.58872545  0.94011414 -1.35924089  1.19359171  1.48940694]]``` to ```[[ 0.47769845 -1.17613626 -1.06156325 -0.85632306 -0.62591958]]```.

Related to https://github.com/tensorflow/skflow/issues/101

**Comment by vrv** [comment]
I believe this is 'working as intended': tf.set_random_seed only sets the graph level randomization seed, not the op level randomization seed.  You have to set both if you want deterministic results.

(I believe tf.set_random_seed documentation explains the details).

**Comment by vrv** [comment]
To clarify, you need to set both if you want deterministic results when the *graphs* are different.  If the graphs were the same and you set the graph level seed, you wouldn't need to set the op level seed, but here your graphs are different, so you would need to set both.

We could probably add this to our documentation, since this example is a useful one to show.
