### ISSUE TITLE
tensorboard display nothing after update to v1.2.0

### ISSUE THREAD

**Issue by cxwx** [tensorflow/tensorflow#11035]
I update to tensorflow 1.2.0 by building from source. 
after that, tensorboard show nothing.
Is the tensorboard changed?
I use command:
    tensorboard --logdir=log

**Comment by cxwx** [comment]
It seems tensor board disappeared in v1.2.0 ? 
how should I install tensor board in v1.2.0

**Comment by zasdfgbnm** [comment]
https://github.com/tensorflow/tensorboard

**Comment by cxwx** [comment]
When I install tensorflow compiled from source v1.2.0, it automaticly do bellow:
     pip install tensorflow-tensorboard, 
This tensorboard seems to display nothing!
However using (https://github.com/tensorflow/tensorboard) this one is OK.
Is it a bug?

**Comment by skye** [comment]
@dandelionmane @jart

**Comment by dandelionmane** [comment]
@cxwx Can you open an issue at github.com/tensorflow/tensorboard with the following information:
- What was the output that TensorBoard printed to console?
- What was the output that TensorBoard printed to web console? (in chrome, right click on the page + click "inspect")
- What browser are you using?
- What OS are you using?
- What exactly is TensorBoard displaying?

I'm closing this issue since this is the wrong place for TensorBoard issues.
