### ISSUE TITLE
Only use weakref.finalize from backports in Python < 3.4

### ISSUE THREAD

**Issue by mdeff** [tensorflow/tensorflow#11082]
### System information
- Arch Linux (up-to-date)
- TensorFlow installed from binary (with pacman, Arch package manager)
- TensorFlow version: 1.2.0
- No GPU or CUDA

### Describe the problem
[tensorflow/python/util/tf_should_use.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/tf_should_use.py) is doing `from backports import weakref` (introduced by    cf238e1f2f68309822e1adb3f86dd439c0b87441), though I guess this is only useful for Python 2. In Python 3, we could simply `import weakref`. This bug has been observed by other people and reported on the [Arch Linux bug tracker](https://bugs.archlinux.org/task/54606).

### Traceback
```
python -c "import tensorflow"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/usr/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 63, in <module>
    from tensorflow.python.framework.framework_lib import *
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/framework_lib.py", line 100, in <module>
    from tensorflow.python.framework.subscribe import subscribe
  File "/usr/lib/python3.6/site-packages/tensorflow/python/framework/subscribe.py", line 26, in <module>
    from tensorflow.python.ops import variables
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/variables.py", line 26, in <module>
    from tensorflow.python.ops import control_flow_ops
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 70, in <module>
    from tensorflow.python.ops import tensor_array_ops
  File "/usr/lib/python3.6/site-packages/tensorflow/python/ops/tensor_array_ops.py", line 33, in <module>
    from tensorflow.python.util import tf_should_use
  File "/usr/lib/python3.6/site-packages/tensorflow/python/util/tf_should_use.py", line 28, in <module>
    from backports import weakref  # pylint: disable=g-bad-import-order
ModuleNotFoundError: No module named 'backports'
```

**Comment by spinnau** [comment]
In [tensorflow/blob/master/tensorflow/python/util/tf_should_use.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/tf_should_use.py) the function `weakref.finalize` is used. This is [new since Python 3.4](https://docs.python.org/3/library/weakref.html#weakref.finalize). Thus, it is not a distinction between Python 2 and Python 3 here.

Possible solution is to check if the `finalize` function exists in `weakref` module and import `backports.weakref` otherwise. Importing `weakref` should be safe, as it [exists since Python 2.1](https://docs.python.org/2/library/weakref.html):

```python
import weakref
if not hasattr(weakref, 'finalize'):    
    from backports import weakref
```
Or alternatively

```python
try:
    from weakref import finalize
except ImportError:
    from backports.weakref import finalize
```
as `finalize` is (currently) the only used member from `weakref` module in tf_should_use.

@mdeff Maybe you want to change the title of the issue to something like *"Only use weakref.finalize from backports in Python < 3.4"*

**Comment by spinnau** [comment]
@ebrevdo What do you think? I could also add a PR for this.

**Comment by mdeff** [comment]
I just opened PR #11174 and preferred @spinnau's second option because it's "easier to ask for forgiveness than permission".
