### ISSUE TITLE
How can i use saved_model api to save chatbot model? 

### ISSUE THREAD

**Issue by StephenLee2016** [tensorflow/tensorflow#11109]
Rencently i train a chatbot model based on seq2seq model , but i failed to save the model use saved_model api! So i wonder to know where i can get some demo about this task?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(When you do ask there, you should probably include more detail on what exactly you tried and what failed)
