### ISSUE TITLE
tf.contrib.keras modules can't Open HDFS file

### ISSUE THREAD

**Issue by tonyw** [tensorflow/tensorflow#11127]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:CentOS 7
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: 1.1.0
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:5.1.10

I use keras.preprocessing.image.ImageDataGenerator class,I invoke flow_from_directory function,when train_data_dir is a HDFS directory. the script throw exception. I refer the source code.I found the  ImageDataGenerator class not use GFile class to open path.
So,it's possible to use GFile to open file in tf.contrib.keras modules?

**Comment by skye** [comment]
@fchollet can you comment or redirect? Thanks!

**Comment by DanielTizon** [comment]
@fchollet can you give any feedback about it? plz, I have the same problem.

**Comment by fchollet** [comment]
Keras can open HDF5 files accessible on local filesystem / network. It cannot open HDF5 files on GFS, because GFS does not support HDF5. We have been talking to the HDF group about possibly making that happen in the future.

To open HDFS files that aren't on a locally-accessible filesystem, first copy them locally.
