### ISSUE TITLE
No error reported when a wrong argument name is inputted to tf.app.flags

### ISSUE THREAD

**Issue by wenwei202** [tensorflow/tensorflow#11195]
The default behavior of `tf.app.flags` is: when the user inputs a wrong/undefined argument name, the program just keeps running without throwing out any error about it. For example, 
```
flags.DEFINE_string("weight_path", None, "the path of saved model to restore from")
```
But when the user inputs 
```
python your_prog.py --weights_path ${MODEL_PATH}
```
The program just keeps running with `weight_path=None` and does not report the wrong argument of `weights_path` which has a **s** appended.
Should we change this kind of default behavior? In this case, users may think they input the correct arguments to finetune the model but unfortunately it just trains from scratch.

**Comment by kheuton** [comment]
What should the behavior be here? I see a couple of options:

1. Raise an error if there's an unknown argument. This would be as simple as switching from `parse_known_args` to `parse_args`
2. Display a warning if there's an unknown argument. I imagine `parse_known_args` was chosen for a reason, so this might be the option more in-line with the intention behind that decision

**Comment by wenwei202** [comment]
I prefer the first one, with lots of logs printing out, the warning info can also be easily missed.

**Comment by nolanliou** [comment]
@wenwei202 @kheuton 
The first choice maybe not so good, which is not compatible for previous versions. I think a warning is good enough. The arguments has been set default values, terminating the app maybe not good choice. 

My solution:

- add **required**  argument to the [DEFINE_\*](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/flags.py#L65) APIs. which can solve the problem of lacking some required args or typo.

- add warning information for unparsed arguments.

I opened a PR, Feel free to share your thoughts.

**Comment by vrv** [comment]
Reposting what I said on another PR, so it's centralized in one place.  This is a good feature request for a flags library.

Some background is probably warranted though: TF's flags library is an API port of an internal flags library at Google that I believe predated argparse. The flags library's existence is solely to make it easier to opensource internal code, since flags.py's API is used throughout Google internally. But argparse is more than sufficient for most opensource use cases, so I would like to avoid changing the existing flags API, even to enhance it.

Furthermore, I believe there are efforts to opensource the internal flags library, which already has this feature of marking flags as required via an explicit call to mark flags as required, and rather than introduce a new API that is incompatible with the internal one, I think it would be a good idea to wait for that library to be released. If it's the case that several months go by and that library is not released, let's revisit this PR and perhaps plan to make it API compatible with that library.

I'm following up with the authors internally to see whether we should go ahead and add the API to the tf version in the short term.

**Comment by vrv** [comment]
Okay, it sounds like it will take some time to opensource the internal flags library, so let's endeavor to make it API compatible if we're going to do this.

If the implementation can be something like:

```
def mark_flag_as_required(flag_name):
  # impl here
```

and its use looks like:

```
if __name__ == '__main__':
      flags.mark_flag_as_required('your_flag_name')
      tf.app.run()
```

then I think we could accept a PR.

This means that the declaration of it being 'required' cannot be in the FLAGS definition, and so this will require some extra validation code to be run rather than using the 'requires' field of argparse.  

My suggestion would be to add code to the _FlagValues class that keeps track of required flags registered via "mark_flag_as_required", and prior to calling parse_known_args(), the code would check to see that 'args' contains all of the required flags, and raises an exception if not true.

The reason for doing it this way is that the this flags library is for better or worse (I think worse) built in such a way that it allows flags to be defined far from where they are parsed, and that means a flag may be defined in a file that you don't own, but you want to make required.  So decoupling the 'requirement' from the flag definition allows the binary to own the set of required flags.

**Comment by nolanliou** [comment]
Ok, this way is reasonable to me. I'll work on it.

**Comment by yilei** [comment]
The internal flags library will be released in three months, it's very like https://github.com/google/python-gflags, with some changes and many improvements.

The `mark_flag_as_required` API should be the same as https://github.com/google/python-gflags/blob/9f00edd8bb0c8c0019f98541655263d5923cec0a/gflags/__init__.py#L255

To be fully compatible, it should raise [`flags.ValidationError`](https://github.com/google/python-gflags/blob/9f00edd8bb0c8c0019f98541655263d5923cec0a/gflags/__init__.py#L88) if *flag value is not `None` after flags are parsed*.

NOTE: in case the flag is defined with a non-None default value, e.g.

```
flags.DEFINE_string("weight_path", '/tmp/module.out', "the path of saved model to restore from")
flags.mark_flag_as_required("weight_path")
```

but the flag is not specified in the command line, no exception should be raised. (It's ok to display a warning though.)

**Comment by vrv** [comment]
Thanks @yilei.  Though I don't think we can raise the same exception type, I think it's fine in the short term to raise a ValueError for now that will then change to ValidationError when we switch.   Please document that the exception raised will change in the future so it's documented as not being part of the official API.  Thanks!

**Comment by nolanliou** [comment]
@vrv I have finished the code. I added the check at _parse_flags and __setattr__, which reference python-gflags. Feel free to share thoughts, Thanks.

**Comment by vrv** [comment]
Regardless of the current feature set, I think we're just going to move to the now opensourced https://github.com/abseil/abseil-py/tree/master/absl/flags at some point, so I'd rather avoid any further development of our homegrown version that would make it functionally different than that one.

**Comment by vrv** [comment]
(I'd encourage those to avoid using tf.app.flags if you are bothered by issues with it, and use the abseil library or just argparse).
