### ISSUE TITLE
building gexagon_graph_execution for hexagon_DSP failed

### ISSUE THREAD

**Issue by amirjamez** [tensorflow/tensorflow#11257]
I have followed the build and run script for HVX here, after installing the protobuf and downloading the pre-built libraries the code has failed at :

`error: undefined reference to 'soc_interface_AllocateInOutNodeBuffers'
`here is the related file:

```
/home/amir/Documents/tensorflow/tensorflow/contrib/makefile/gen/lib/libtensorflow-core.a(hexagon_control_wrapper.o):hexagon_control_wrapper.cc:function tensorflow::HexagonControlWrapper::Init(tensorflow::RemoteFusedGraphExecuteInfo const&): error: undefined reference to 'soc_interface_AllocateInOutNodeBuffers'
collect2: error: ld returned 1 exit status
/home/amir/Documents/tensorflow/tensorflow/contrib/makefile/sub_makefiles/hexagon_graph_execution/Makefile.in:64: recipe for target '/home/amir/Documents/tensorflow/tensorflow/contrib/makefile/gen/bin/hexagon_graph_execution' failed
make: *** [/home/amir/Documents/tensorflow/tensorflow/contrib/makefile/gen/bin/hexagon_graph_execution] Error 1
```
@satok16 could you help me out here about the linking problem? Running on Ubuntu 16.04.02

**Comment by amirjamez** [comment]
The issue resolved when I rebuild al from source-code (without -p prebuilt library option).

**Comment by satok16** [comment]
Sure, thank you for the update.

**Comment by kanshuzhi** [comment]
@amirjamez @satok16 
I try to build from source-code then run on Snapdragon820 Board. But it failed and reports the following error.
```
Prepare failed! returned 0xffffffff

NN Id = -904838944
Execute graph!
Execution failed!
execute got err: -1

NN Id = -904838944
Execution failed
NN Id = -904838944
Failed to read data.
```
And dmesg information is as the following, looks like that ION cannot allocate memory.
```
[  110.941082] platform soc:qcom,ion:qcom,ion-heap@22: Fail to allocate buffer
[  111.581037] platform soc:qcom,ion:qcom,ion-heap@22: Fail to allocate buffer
[  308.621162] platform soc:qcom,ion:qcom,ion-heap@22: Fail to allocate buffer
[  309.221876] platform soc:qcom,ion:qcom,ion-heap@22: Fail to allocate buffer
```

And if I build with prebuilt library(-p), the issue is gone and I can run the hexagon_execute_graph successfully.

My Enviroment:
1. Openq 820 Board.
2. NDK13 and NDK14b (I try both NDK)
3. Hexagon SDK 3.1 and 3.2(I try both Hexagon SDK)
4. tensorflow commit id ca9899fb1da37c8644c447b401663a0b10483c91

any suggestion is appreciated.
Thanks.

**Comment by amirjamez** [comment]
@kanshuzhi I guess my SDK was 3.0 (7.2.12). You might wanna try that version as well.

**Comment by kanshuzhi** [comment]
Thanks.
I see. my sdk version is Hexagon v3.2 and Hexagon v3.0 SDK seems out of date cannot be fully downloaded.
