### ISSUE TITLE
Image Retrain Inception only check the own specific category not tensor dataset

### ISSUE THREAD

**Issue by ManojPabani** [tensorflow/tensorflow#11263]
I have retrained the inception model from my data set of traffic sign.Its working fine but when I am trying to check other image e.g panda it's resulting with the name of traffic sign with some probabilities.I don't understand why its doing it.I need both tensor-flow data-set and my own category too. My steps:

-I have installed the python 3.5.2 in windows 7

-I installed tensor-flow with pip --install tensorflow

-I download these two files retrain.py to train my data and label_image.py to check image.

files downloaded from: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/image_retraining

**Comment by jubjamie** [comment]
_Warning: As this doesn't appear to be a bug with Tensorflow, the devs may ask for this to be moved to Stack Overflow._

This is because when you have trained with your dataset you are retraining the final output layers with new classes (traffic signs). This will not retain the imagenet results. This is a question for S/O.

If you decide to move this issue to Stack Overflow, please post the link here so that myself (or others that stumble upon this issue) can find the S/O thread.

**Comment by ManojPabani** [comment]
I have posted it in stackover flow please guide i am using windows to do this.
https://stackoverflow.com/questions/44897648/image-retrain-inception-only-check-the-own-specific-category-not-tensor-dataset

**Comment by jubjamie** [comment]
Thanks @ManojPabani I will come over and continue the discussion there. Please close this issue to clear the issue tracker for the devs!
