### ISSUE TITLE
ImportError: No module named google.protobuf 

### ISSUE THREAD

**Issue by TyrionChou** [tensorflow/tensorflow#11268]
hello ,there! when i use C++ to call python program that use tensorflow，report this error

Traceback (most recent call last):
  
File "<string>", line 1, in <module>
 
File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>

    from tensorflow.python import *
  
File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 54, in <module>

    from tensorflow.core.framework.graph_pb2 import *
File "/root/anaconda2/lib/python2.7/site-packages/tensorflow/core/framework/graph_pb2.py", line 6, in <module>

    from google.protobuf import descriptor as _descriptor

ImportError: No module named google.protobuf

code is here ：
PyRun_SimpleString("sys.path.append('/root/anaconda2/lib/python2.7/site-packages')");
PyRun_SimpleString("sys.path.append('/root/pythoncode/vgg')");
PyRun_SimpleString("import tensorflow as tf");
PyRun_SimpleString("print sys.path");

have anyone meet this question？please，help! thank you very much!

**Comment by jubjamie** [comment]
_Please make sure you fill in the issue template to ensure that your issue can be troubleshooted correctly. Key information includes System Specs and Tensorflow/CUDA/cuDNN versions. Without this it's harder to help!_

What happens when you run it in a normal python environment? Does tensorflow work as expected?

**Comment by TyrionChou** [comment]
system is centos 7.tensorflow is 1.1.0. when I run it in a normal python environment it can run correctly

**Comment by jubjamie** [comment]
I'm not familiar enough with C++ or PyRun and don't want to lead you in the wrong direction. Are your tensorflow, protobuf installations in the site-packages area or are they in an environment somewhere? I notice you're using Anaconda so perhaps you are using anaconda incorrectly with this system? You may some package conflicts.

I presume you're otherwise unable to use the C++ version of Tensorflow for this?

**Comment by drpngx** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!
