### ISSUE TITLE
No OpKernel was registered to support Op 'LesseEqual' with these attrs on Android

### ISSUE THREAD

**Issue by 0rchard** [tensorflow/tensorflow#11296]
On Android I am trying to load a tensorflow graph which I have frozen by using convert_variables_to_constants however I am getting:

com.example.trio.tensordemo E/TensorflowDebug: 
java.lang.IllegalArgumentException: No OpKernel was registered to support Op 'LessEqual' with these attrs.  Registered devices: [CPU], 
Registered kernels:
<no registered kernels>
[[Node: bidirectional_rnn/fw/fw/LessEqual = LessEqual[T=DT_INT32, _device="/device:GPU:0"](bidirectional_rnn/fw/fw/Max, bidirectional_rnn/fw/fw/LessEqual/y)]]
This is what the node looks like:

name: "bidirectional_rnn/fw/fw/LessEqual_1"
op: "LessEqual"
input: "bidirectional_rnn/fw/fw/Max"
input: "bidirectional_rnn/fw/fw/LessEqual_1/y"
device: "/device:CPU:0"
attr {
  key: "T"
  value {
    type: DT_INT32
  }
}
The tensorflow version I trained and loaded in Android are both r1.2.

**Comment by cy89** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

As an aside, is there any chance that you've registered the kernel on GPU, but the node is trying to find the CPU variant, so that's why you're not finding the correctly registered kernel?
