### ISSUE TITLE
can't find some header files when i'm using c/c++ API, eg: tensorflow/core/example/example.pb.h

### ISSUE THREAD

**Issue by nyyznyyz1991** [tensorflow/tensorflow#11344]
TF version 1.1.0      ubuntu 14.04 ,    install by pip 
In many examples about c or c++ API in tensorflow, i can find some codes like:

#include "tensorflow/core/example/example.pb.h"
#include "tensorflow/core/example/feature.pb.h"
#include "tensorflow/core/framework/graph.pb_text.h"

but in the folder where tensorflow is intalled, i can't find these file, someone knows why?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said, note that the `pip` installation is for Python (`pip` is a python package manager). For now, to use the C++ API you need to build from source. See for example [related StackOverflow questions](https://stackoverflow.com/questions/33620794/how-to-build-and-use-google-tensorflow-c-api/43920376#43920376) or the C++ [label_image example README](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/label_image).

Installation for some other language bindings like C, Java, Go and community supported C#, Rust, Haskell etc. might be easier if those work for you. See https://www.tensorflow.org/install/ and https://www.tensorflow.org/api_docs/

**Comment by nyyznyyz1991** [comment]
am i must install tensorflow from source, using **.proto to generate **.pb.h and **.cc ?
