### ISSUE TITLE
Cannot run example in tensorflow docker due to missing dependency

### ISSUE THREAD

**Issue by yhenon** [tensorflow/tensorflow#11356]
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 14.04
- **TensorFlow installed from (source or binary)**: running in official docker container
- **TensorFlow version (use command below)**: 1.1.0
- **Python version**: 2.7
- **CUDA/cuDNN version**: CUDA 8.0
- **GPU model and memory**: Titan X
- **Exact command to reproduce**:
`docker run -it -p 8888:8888 gcr.io/tensorflow/tensorflow`

### Describe the problem
The official tensorflow docker container does not include h5py. This might be intentional?

However, this breaks an example:
- tensorflow/tensorflow/examples/learn/hdf5_classification.py

This also causes a number of contrib methods to raise exceptions:
- tensorflow/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py
- a numbert of keras.contrib files

**Comment by cy89** [comment]
@caisq can you please comment on whether leaving h5py might be intentional?

**Comment by caisq** [comment]
@cy89, @yhenon No, leaving h5py out from the dockerfiles is not intentional. Nobody has requested it so far. I'm fine with adding it. Feel free to send a pull request to add h5py to the following Dockerfiles:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/Dockerfile.gpu
