### ISSUE TITLE
Feature : Tensorflow works on ubuntu12.04

### ISSUE THREAD

**Issue by thor008** [tensorflow/tensorflow#11368]
Hi,all:
I have a computing cluster,with a master and some slaves. 
I want to tran the AI model on master, and then send to slaves for calculation。
But，for some reason, part of slaves works on ubuntu12.04, and i can not update them to 14.04. 
so, how can i get a lite tensorflow or a saved model lib, than can be restored on ubuntu12.04 slaves.
Many thanks!

**Comment by gunan** [comment]
How about using docker?
Can you get docker running on these machines?

Since ubuntu 12.04 is quite old, and even canonical does not support the OS, and do not push the latest compiler/glibc updates on the machines it would be difficult for us to support this version of the operating system.
So I will have to decline this feature request.

However, you can try building TF from sources on a machine or a docker container that has ubuntu 12.04, and if there are issues, we are happy to accept fixes into our repository.
