### ISSUE TITLE
Error while slicing with int64

### ISSUE THREAD

**Issue by minhlab** [tensorflow/tensorflow#11380]
This is similar to #11318 but with a slice instead of an individual index. I upgraded to the latest version using `pip3 install --user --upgrade tensorflow-gpu`.

```
>>> import tensorflow as tf
>>> tf.__version__
'1.2.1'
>>> i = tf.constant(1, dtype=tf.int64)
>>> a[i:i+1]
<long stack trace>
TypeError: Input 'strides' of 'StridedSlice' Op has type int32 that does not match type int64 of argument 'begin'.
```

**Comment by aselle** [comment]
It is known that int 64 index support is not well supported in many of our ops. the workaround is to cast to tf.int32 (with tf.cast) or in this case since it is a constant use  tf.int32. If you are using over 2 billion entry tensors, then you might need to work on adding the support. @vrv, has some ideas on how to handle this more elegantly.

**Comment by vrv** [comment]
Pretty sure this is another bug in SliceHelper. Probably in the first if
condition when iterating over the slice objects. I'll try to take a look
later.

**Comment by vrv** [comment]
Yup, bug in SliceHelper -- I'm submitting a fix with tests, and it'll be in probably early this week.
