### ISSUE TITLE
Apache License header does not include HTTPS link

### ISSUE THREAD

**Issue by alanyee** [tensorflow/tensorflow#11417]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS 10.12.15
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.2
- **Python version**: 2.7.13

### Describe the problem
Various code files have `http://www.apache.org/licenses/LICENSE-2.0` instead of `https://www.apache.org/licenses/LICENSE-2.0`. Not sure if this is the result of bazel or simply that needs to be explicitly written.

### Source code / logs
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/learn/wide_n_deep_tutorial.py

**Comment by jart** [comment]
I'm not sure if it makes a difference. I did a search and the http version of the link seems to be used 400x more, because it's what the Apache 2.0 license recommends. Although in all fairness, it was written in 2004. It would be a big change to refactor these headers and I'm not sure if it's worth doing.

**Comment by alanyee** [comment]
From a security perspective, there is a difference, though to be fair, it is something that maybe should be updated on Apache's side. If anything, I will change if I see in TensorFlow code when I make a pull request unrelated to HTTPS of the license.
