### ISSUE TITLE
No clue to inform what 'dimension' arg of argmin or argmax means in API docs

### ISSUE THREAD

**Issue by mikigom** [tensorflow/tensorflow#11422]
In documentation of TF API 1.2, `tf.argmin` and `tf.argmax` have `dimension` argument.

* [tf.argmin](https://www.tensorflow.org/api_docs/python/tf/argmin)
* [tf.argmax](https://www.tensorflow.org/api_docs/python/tf/argmax)

However, there is no any explanation for what it means.

**Comment by mrry** [comment]
The `dimension` argument is a deprecated synonym for `axis`. You should use `axis` in new code.

(The appearance of `dimension` in the generated docs suggests that this is something we should avoid in the doc generator. I'll assign this to @MarkDaoust, since he's most familiar with the recent advances in our doc generation technology!)
