### ISSUE TITLE
tf.matrix_inverse doesn't support complex tensor

### ISSUE THREAD

**Issue by uirye** [tensorflow/tensorflow#11430]
I'm trying to run the next code:

Code:

    x=tf.placeholder(tf.float64,[2,2])
    y=tf.matrix_inverse(x)

Result OK :

    <tf.Tensor 'MatrixInverse_2:0' shape=(2, 2) dtype=float64>

Code:

    x=tf.placeholder(tf.complex64,[2,2])
    y=tf.matrix_inverse(x)

Result (Error):

    Traceback (most recent call last):

    File "<ipython-input-163-f259114be54a>", line 2, in <module>
    y=tf.matrix_inverse(x)

    File "c:\python\python35\lib\site-packages\tensorflow\python\ops\gen_linalg_ops.py", line 330, in 
    matrix_inverse
    name=name)

    File "c:\python\python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 585, 
    in apply_op
    param_name=input_name)

    File "c:\python\python35\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 61, 
    in _SatisfiesTypeConstraint
    ", ".join(dtypes.as_dtype(x).name for x in allowed_list)))

    TypeError: Value passed to parameter 'input' has DataType complex64 not in list of allowed values: 
    float64, float32

It seems that complex matrix inverse is not supported, Any idea for workaround ?

**Comment by shreyneil** [comment]
In the matrix_inverse function source the inverse is computed only if adjoint is set to true. 
Check here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/linalg_grad.py

For real numbers we have to calculate the adjoint of the matrix in order to get the inverse but for the case of complex numbers in a matrix the inverse is calculated using conjugate transpose or hermitian transpose.

More here:
https://en.wikipedia.org/wiki/Conjugate_transpose

So for the time being it works only fot real numbers.
Hope this helps.

**Comment by uirye** [comment]
I currently have the next workaround for this problem:
I'm using py_func to import np.inalg.inv function

    x=tf.placeholder(tf.complex64,[2,2])
    #y=tf.matrix_inverse(x)
    y = tf.py_func(np.linalg.inv, [x], x.dtype)
    y = tf.reshape(y, [2,2])

**Comment by shreyneil** [comment]
So is the above code working for or are you  facing any problems?

**Comment by uirye** [comment]
Seems to work fine, but I haven't checked it with training yet
