### ISSUE TITLE
20 minutes for compiling a single file(conv_grad_ops_3d.cc)? 

### ISSUE THREAD

**Issue by snnn** [tensorflow/tensorflow#11452]
-----------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
2533ada7dd45b84d60677b8735e013d21044651a

- **Python version**: 
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

### Describe the problem

It took about 20 minutes to compile "conv_grad_ops_3d.cc"
The whole build took:
INFO: Elapsed time: 2241.764s, Critical Path: 1509.12s

Therefore this file took about 50% compile time. Why? 

### Source code / logs
http://ci.tensorflow.org/job/tf-master-win-bzl/1239/consoleFull

**Comment by martinwicke** [comment]
I don't know, but individual files' build times are not necessarily all that meaningful. The build for that file may be blocked on I/O by other build processes. Since we build several files in parallel, 20 min is much less than half the build time. 

I see this was a Windows build -- @meteorcloudy may have some insight on what may be happening. 

At this point I don't think this is a bug, so I will close this issue.

**Comment by meteorcloudy** [comment]
Yes, I noticed this before. See https://github.com/tensorflow/tensorflow/issues/10521
