### ISSUE TITLE
Sorry to Reply you.My problem is tensor-flow un-incompatible with windows IIS?

### ISSUE THREAD

**Issue by jxua** [tensorflow/tensorflow#11472]
Sorry, i just have time to reply you. Thanks for replying me.
I means I use Flask to call tensor-flow py. And mount Flask to windows IIS. Local run ok. But in IIS will show FastCgi error. Check local run is ok,no error. But when in IIS, when i import keras, it will show fastcgi error. but when don't import keras, it will ok. If tensor-flow isun-incompatible with IIS?
![image](https://user-images.githubusercontent.com/22673941/28158872-b733b454-67ed-11e7-914e-303340bdc081.png)
![image](https://user-images.githubusercontent.com/22673941/28158879-bc5bc0c0-67ed-11e7-90f2-e7f72fd69e02.png)
![image](https://user-images.githubusercontent.com/22673941/28158885-c147b828-67ed-11e7-96da-6bd9324bdba0.png)
![image](https://user-images.githubusercontent.com/22673941/28158983-0ff8cca0-67ee-11e7-8fc7-8a063950b19d.png)

**Comment by jubjamie** [comment]
Looks like you are meant to be replying to #11310 instead of creating a new issue.

See @gunan response here: https://github.com/tensorflow/tensorflow/issues/11310#issuecomment-315064408

FastCGI error is not a Tensorflow error but one from IIS I think. As @gunan has said, it is not supported on those platforms. Continue the conversation on #11310. Good luck!
