### ISSUE TITLE
Not able to install tensflow on Windows 7

### ISSUE THREAD

**Issue by YugankNarula** [tensorflow/tensorflow#11479]
Hi,

I am not able to tensor flow on Windows7 machine. I searched it and found it seems to b a proxy server problem which is trying to connect to pypi.python.org. I configured it also & tried to install tensorflow, it's still not working. Can anyone tell me how can I install it without compromising the security?

Thanks, 
Yugank Narula

**Comment by jubjamie** [comment]
_Warning: As this doesn't appear to be a bug with Tensorflow, the devs may ask for this to be moved to Stack Overflow._

Sounds like this is happening during the `pip install tensorflow` phase and you're unable to access the file. This is better off on Stack Overflow. In the meantime, please try one of the following:
(Assuming CPU)

**Python 3.5**
`pip install https://ci.tensorflow.org/view/Release/job/release-win/lastStableBuild/M=windows,PY=35/artifact/cmake_build/tf_python/dist/tensorflow-1.2.1-cp35-cp35m-win_amd64.whl`

**Python 3.6**
`pip install https://ci.tensorflow.org/view/Release/job/release-win/lastStableBuild/M=windows,PY=36/artifact/cmake_build/tf_python/dist/tensorflow-1.2.1-cp36-cp36m-win_amd64.whl`

If you decide to move this issue to Stack Overflow, please post the link here so that myself (or others that stumble upon this issue) can find the S/O thread.

**Comment by Bala1718** [comment]
Create a separate environment in your Local Machine and then download and install Tensor Flow.

**Comment by h313** [comment]
Try installing tensorflow under Anaconda?

**Comment by jart** [comment]
Thank you community members for supporting our friend. Please use [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) in the future, since this issue tracker is for bugs and feature requests. There is also a larger community that reads questions there.
