### ISSUE TITLE
allocate_output can result in OOM error

### ISSUE THREAD

**Issue by PatWie** [tensorflow/tensorflow#11500]
TF-commit: 7f008453ca1c7b

### Describe the problem
When implementing custom operations, allocating output twice (as a bug) should give at least a warning. The following code

```c++
    Tensor* tensor = nullptr;
    OP_REQUIRES_OK(ctx, ctx->allocate_output(0, output_shape, &tensor));
    OP_REQUIRES_OK(ctx, ctx->allocate_output(0, output_shape, &tensor));
```

gives a nearly un-debuggable OOM error after many iterations during runtime. Is it possible to prevent  `allocate_output(i,...)` being called with the same `i` twice?

**Comment by michaelisard** [comment]
It looks as if this [is checked](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/op_kernel.cc#L644) but only in debug builds. I'm sorry that this was hard for you to track down, but it's probably appropriate to have that checking turned off for performance. It is worth running a debug build when investigating mysterious issues.

I'll close this for now but please reopen if you still think there's a bug.

**Comment by michaelisard** [comment]
Looking again, I think you're right that it would be good if this were flagged up. However this function is a very hot code path that has been worked over carefully in the past for optimization so I'm not completely comfortable just suggesting you send a PR to fix this (e.g., make the call return an error rather than CHECK). @asimshankar would you take a look and see if you're happy with the performance implications of this check?

**Comment by PatWie** [comment]
The debug mode works as expected. Then this isn't an issue anymore. But most people probably only compile TF in release and then see the same behavior.

Maybe a
```c++
ctx->allocate_and_append_output(output_shape, &tensor));
```
would solve these issues. Don't know a single operation, where the output shape isn't known in the very beginning of the function.

I close this for now (knowing such an issue exists).
