### ISSUE TITLE
[Feature Request] Feed tensors to feed_dict

### ISSUE THREAD

**Issue by AndreiCostinescu** [tensorflow/tensorflow#11536]
I think that a nice step towards "dynamic computation graphs" is the possibility to feed tensors to placeholders.

I am building an application which creates a network.
I create my training and testing batches with tf.train.batch. 
However, the training batches are unlimited (so no epoch limit to the tf.train.slice_input_producer) but I would like to also test during training so to only test one epoch on the testing data.
For both the training and testing images, I have a preprocessing pipeline which also uses a computation graph, but is different for testing and for training.

Now the problem is that I have to create the testing batch every time I want to test (because I want to test for 1 epoch, and I cannot otherwise limit the input producing...).
So it would definitely help, to be able to feed the training and testing batch respectively to the network input.
My current solution is to create the network every time I make the switch from training to testing with the new network inputs. But this takes quite an (unnecessary) long amount of time...

Is there perhaps another way to "link" two graphs in tensorflow?

**Comment by yaroslavvb** [comment]
It doesn't really make sense to feed a `Tensor` object. Each tensor represents output of a an op and can correspond to different values, whereas numpy array is a specific value. Instead of `feed_dict` you can use standard Python API to indicate that you want tensor to be an input to another node.  A common scenario is to only use one graph, and have different parts of the graph correspond to training vs testing parts of the network.
