### ISSUE TITLE
Cannot build TensorFLow with GPU support when using TensorFlow as an external dependency

### ISSUE THREAD

**Issue by beinanwang** [tensorflow/tensorflow#11578]
Currently my project uses TensorFlow as an external dependency (local repository). When I build my project with CPU only, the build is successful. However if I add --config=-cuda the build will succeed but without the GPU part (yes, I have run ./configure). The warning I get is: WARNING: Config values are not defined in any .rc file: cuda. This does not happen if I build my project inside TensorFlow's source tree.

**Comment by shreyneil** [comment]
Try this:
https://github.com/tensorflow/models/issues/467

**Comment by beinanwang** [comment]
I forgot to say I'm building the C++ version.  The above issues don't apply to my case.

**Comment by shreyneil** [comment]
The second link also serves the issue for gcc compiler it should work for your case.

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. 

Specifically, what steps do I need to take to reproduce your problem.

Thank you.
