### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'shape'

### ISSUE THREAD

**Issue by zeshaoaaa** [tensorflow/tensorflow#11614]
I read these codes from a book, but it can't work, and after I searched for a couple of days haven't  similar 'shape' problem how can I fix it? Is anybody have ideas? plz, thanks!
----------------------------------------------------------------

\# -*- coding:utf-8 -*-
import tensorflow as tf
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v",initializer=tf.zeros_initializer(shape=[1]))

**Comment by PatWie** [comment]
```python
# -- coding:utf-8 --
import tensorflow as tf
g1 = tf.Graph()
with g1.as_default():
    v = tf.get_variable("v", shape=[1], initializer=tf.zeros_initializer())
```
see [documentation](http://devdocs.io/tensorflow~python/tf/get_variable) and **read:**


> Please go to Stack Overflow for help and support:
> 
> http://stackoverflow.com/questions/tagged/tensorflow
> 
> If you open a GitHub issue, here is our policy:
> 
> 1. It must be a bug or a feature request.
> 2. The form below must be filled out.
> 3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said, you probably want:

```
v = tf.get_variable("v", initializer=tf.zeroes_initializer(), shape=[1])
```

As per the [documentation of `tf.zeroes_initializer`](https://www.tensorflow.org/api_docs/python/tf/zeros_initializer), it only accepts a `dtype` as an argument to creating the initializer, while [`tf.get_variable`](https://www.tensorflow.org/api_docs/python/tf/get_variable) does accept a `shape` argument.

**Comment by zeshaoaaa** [comment]
@asimshankar I am sorry about that, I thought it is a bug, sorry!

**Comment by zeshaoaaa** [comment]
@PatWie I am sorry about that, I thought it is a bug, sorry! Thank you!
