### ISSUE TITLE
Missing file

### ISSUE THREAD

**Issue by talal579** [tensorflow/tensorflow#11624]
The file named node_def_pb2 is missing from tensorflow/core/framework. The file is required when I try to load the MNIST data as part of the tensorflow tutorial.

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . **Please provide all the information it asks**, in particular, steps to reproduce the problem. Thank you.

(In this case, if you're building from sources, the file is generated. If you're using the installed TensorFlow pip packages, the file will be there in the installed location). Since I'm not sure about the environment in which you're building / looking for the file, I'm not quite sure what the problem is)

**Comment by talal579** [comment]
My apologies -- I reinstalled the tensorflow package, and everything is working fine now. Thanks for your response!
