### ISSUE TITLE
Why are tensorboard removed after r1.2?

### ISSUE THREAD

**Issue by BinhangYuan** [tensorflow/tensorflow#11635]
Previously it was located in tensorflow/tensorboard. Is it removed or moved to somewhere else? What if I want to add new features in tensorboard?

Any suggestion is appreciated!

**Comment by BinhangYuan** [comment]
@jubjamie Cool, thanks for pointing that out! I am wondering if there was a huge change, seems like the new repository does not use nodejs anymore, is there any documentation about how to run the system? Or what kind of tool should I use? Thanks a lot!

**Comment by jubjamie** [comment]
afaik not much has changed from the user's pov as of yet. You can still call it in the usual way `tensorboard --logdir=[..]`. I think it's more for ease of development and open-sourcing etc. It means it's its own package now although I believe that it's installed as a dependency of tensorflow so for the user there isn't a huge change. You can point your TB issues and suggestions to the team at tensorflow/tensorboard :)

**Comment by dandelionmane** [comment]
Hi @BinhangYuan,

You're right that we changed the TensorBoard build system a lot. We no longer use node and associated tooling, we found it was really hard to keep multiple build systems synchronized, since we were using bazel internally and node externally. The result was a really painful build process in open source.

Now, as you can see at [DEVELOPMENT.md](https://github.com/tensorflow/tensorboard/blob/master/DEVELOPMENT.md), we simply use bazel for everything :)
