### ISSUE TITLE
Windows 64-bit GPU Build Failing

### ISSUE THREAD

**Issue by crohkohl** [tensorflow/tensorflow#11639]
The nightly windows 64-bit GPU build has been failing for over 3 days.
I could reproduce the error on different machines:

https://ci.tensorflow.org/view/Nightly/job/nightly-win/M=windows-gpu,PY=36/245/consoleText

Maybe the health monitor on the main site could include this build as well? Otherwise breaking errors might not be noticed for some longer time.

**Comment by jubjamie** [comment]
+1 Keen to get 1.3rc0 rolling but still on python3.5 which seems to be the one failing.

**Comment by drpngx** [comment]
@zheng-xq @gunan some libcupti issue? I thought we had this dependency for a while.

```
    47>gpu_tracer.obj : error LNK2019: unresolved external symbol "public: void __cdecl tensorflow::StepStatsCollector::Save(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class tensorflow::NodeExecStats *)" (?Save@StepStatsCollector@tensorflow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVNodeExecStats@2@@Z) referenced in function "public: virtual class tensorflow::Status __cdecl tensorflow::gputracer::GPUTracerImpl::Collect(class tensorflow::StepStatsCollector *)" (?Collect@GPUTracerImpl@gputracer@tensorflow@@UEAA?AVStatus@3@PEAVStepStatsCollector@3@@Z) [C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\cmake_build\proto_text.vcxproj]
```

**Comment by gunan** [comment]
The release branch is building OK, for 1.3, please use the branch.
In master branch, there are some new files added, but cmakefile updates
were missing. @mrry @guschmue for more information.

On Jul 20, 2017 8:00 PM, "drpngx" <notifications@github.com> wrote:

@zheng-xq <https://github.com/zheng-xq> @gunan <https://github.com/gunan>
some libcupti issue? I thought we had this dependency for a while.

    47>gpu_tracer.obj : error LNK2019: unresolved external symbol
"public: void __cdecl tensorflow::StepStatsCollector::Save(class
std::basic_string<char,struct std::char_traits<char>,class
std::allocator<char> > const &,class tensorflow::NodeExecStats *)"
(?Save@StepStatsCollector@tensorflow@@QEAAXAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAVNodeExecStats@2@@Z)
referenced in function "public: virtual class tensorflow::Status
__cdecl tensorflow::gputracer::GPUTracerImpl::Collect(class
tensorflow::StepStatsCollector *)"
(?Collect@GPUTracerImpl@gputracer@tensorflow@@UEAA?AVStatus@3@PEAVStepStatsCollector@3@@Z)
[C:\tf_jenkins\home\workspace\nightly-win\M\windows-gpu\PY\36\cmake_build\proto_text.vcxproj]

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/11639#issuecomment-316766650>,
or mute the thread

**Comment by guschmue** [comment]
for the master - just sent a PR for it.

**Comment by drpngx** [comment]
#11647 for reference

**Comment by gunan** [comment]
Build is now green in our CI. Please sync to master and try again.

**Comment by drpngx** [comment]
Yay, thanks!
