### ISSUE TITLE
how to load my pretrain model in ckpt file v2 format？

### ISSUE THREAD

**Issue by YgRen** [tensorflow/tensorflow#11642]
Hi,when I use ckpt v1 format,the command line as follows,
`python ./faster_rcnn/test_net.py --gpu 0 --weights ./models/VGGnet_fast_rcnn_iter_150000.ckpt  --imdb voc_2007_test --cfg ./experiments/cfgs/faster_rcnn_end2end.yml  --network VGGnet_test`
it works.
but I train my model in voc 2007 dataset ,the output like this.
![2017-07-20 21-27-37](https://user-images.githubusercontent.com/10908813/28419655-48ddb6d0-6d92-11e7-8e8f-8a5b0a2b14ee.png)

the test_net.py code as follows,
```
'# start a session
    saver = tf.train.Saver()
    sess = tf.Session(config=tf.ConfigProto(allow_soft_placement=True))
    saver.restore(sess, args.model)
    print ('Loading model weights from {:s}').format(args.model)
    test_net(sess, network, imdb, weights_filename)'
```
the output is:
`Waiting for ./output/faster_rcnn_end2end_pva_voc/voc_2007_trainval/PVAnet_iter_10000.ckpt to exist...`
I  have read some issues. but can't solve it . 
I need some help about this question.
how to load my pretrain model in ckpt file v2 format ?  modify my test_net.py?
thanks!

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

(In particular, I'm not quite sure what `faster_rcnn/test_net.py` is. This file doesn't seem to be part of the TensorFlow distribution, so perhaps this is some third-party code? And where is the checkpoint that you're using come from?)

**Comment by YgRen** [comment]
my problem like this issue[https://github.com/smallcorgi/Faster-RCNN_TF/issues/79](url), it provide one solution ，but I want to know how to use ckpt v2 format.What's the difference between ckpt v2 format and ckpt v1 format.
