### ISSUE TITLE
can't import data_utils from tensorflow.models.rnn.translate(No module name tensorflow.models)

### ISSUE THREAD

**Issue by GREEKYnikhilsharma** [tensorflow/tensorflow#11652]
i encountered this while trying to import data_utils from tensorflow.models.rnn.translate.(in the end - NO module named tensorfow.models was my output)

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks, particularly detailed steps to reproduce the problem. Thank you.
