### ISSUE TITLE
 tf.import_graph_def  load quantized graph error

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#11700]
[root@A01-R04-I221-14 export_dir]# python predict.py 
Traceback (most recent call last):
  File "predict.py", line 70, in <module>
    load_graph('quantized_graph.pb')
  File "predict.py", line 33, in load_graph
    tf.import_graph_def(graph_def)
  File "/usr/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 365, in import_graph_def
    % (input_name,)))
ValueError: graph_def is invalid at node u'while/add_6/y': More inputs specified ('while/Switch:1') than the op expects..

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks, in particular detailed instructions on reproducing the problem. Thank you.

**Comment by zhengge** [comment]
Hi @guoying1030 
I have the same error, Did you solve it?

**Comment by venuswu** [comment]
I have the same problem, Have you solve it ?

**Comment by venuswu** [comment]
I hope @petewarden can answer this question.

**Comment by turboLIU** [comment]
I have the same problem ,  have you solved?
