### ISSUE TITLE
run silent /.configure

### ISSUE THREAD

**Issue by merl-dev** [tensorflow/tensorflow#11714]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04

- **TensorFlow installed from (source or binary)**:
source

- **TensorFlow version (use command below)**:
1.3

- **Python version**: 
intel python

- **Bazel version (if compiling from source)**:
0.5

- **CUDA/cuDNN version**:
none
- **GPU model and memory**:
none
- **Exact command to reproduce**:

### Describe the problem
I am building a docker container, compiling tensorflow from source, would like to use MKL, and need to run ```configure``` script silently in order to set up the build correctly. Cannot figure out where, when and how the MKL libraries are being installed.

### Source code / logs
none

Is there a way to run the ```configure``` script silently? alternatively,
Does someone have a Docker script that will compile tensorflow USING the MKL?

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

(That said, there are two options, if you want to use all the defaults, you can run `yes "" | ./configure"`. Alternatively, if you need to set individual options, you can use the environment variables. For example, the scripts that run the builds for continuous integration such as [`libtenorflow_cpu.sh`](https://github.com/tensorflow/tensorflow/blob/r1.2/tensorflow/tools/ci_build/osx/libtensorflow_cpu.sh#L26) set various variables. Unfortunately, the full list is not documented in one place, so you'll have to look at the source of the [`configure` script](https://github.com/tensorflow/tensorflow/blob/master/configure))
