### ISSUE TITLE
tf.train.ExponentialMovingAverage.variables_to_restore

### ISSUE THREAD

**Issue by gauss-clb** [tensorflow/tensorflow#11839]
When I view the API doc, [tf.train.ExponentialMovingAverage.variables_to_restore](https://www.tensorflow.org/versions/master/api_docs/python/tf/train/ExponentialMovingAverage#variables_to_restore). It said `If a variable has a moving average, use the moving average variable name as the restore name; otherwise, use the variable name.`, but I test it is wrong.
Look the code:

```
import tensorflow as tf

a = tf.Variable(tf.constant(1.0),name='a')
b = tf.Variable(tf.constant(3.0),name='b')
c = tf.Variable(tf.constant(5.0),name='c')
ema = tf.train.ExponentialMovingAverage(decay=0.9999)
ema.apply([a,b])

print(tf.get_default_graph().get_all_collection_keys())
print(tf.get_collection('moving_average_variables'))
print(tf.global_variables())
variables_to_restore = ema.variables_to_restore()
print(variables_to_restore)
```
And the output is:
```
['trainable_variables', 'moving_average_variables', 'cond_context', 'variables']
[<tf.Variable 'a:0' shape=() dtype=float32_ref>, <tf.Variable 'b:0' shape=() dtype=float32_ref>]
[<tf.Variable 'a:0' shape=() dtype=float32_ref>, <tf.Variable 'b:0' shape=() dtype=float32_ref>, <tf.Variable 'c:0' shape=() dtype=float32_ref>, <tf.Variable 'a/ExponentialMovingAverage:0' shape=() dtype=float32_ref>, <tf.Variable 'b/ExponentialMovingAverage:0' shape=() dtype=float32_ref>]
{'a/ExponentialMovingAverage': <tf.Variable 'a:0' shape=() dtype=float32_ref>, 'c/ExponentialMovingAverage': <tf.Variable 'c:0' shape=() dtype=float32_ref>, 'b/ExponentialMovingAverage': <tf.Variable 'b:0' shape=() dtype=float32_ref>}

```
Variable c don't has a moving average, but in `variables_to_restore`, it use key=shadow_name either.
Who can tell me what's wrong?

**Comment by reedwm** [comment]
This behavior is confusing but it is not a bug. When calling `variables_to_restore`, you are supposed to indicate what variables have moving averages through its `moving_avg_variables` parameter. `ExponentialMovingAverage` doesn't actually use its own stored averages to determine what variables have moving averages, but instead relies on `moving_avg_variables`.  `moving_avg_variables` defaults to `variables.moving_average_variables() + variables.trainable_variables()`, which is why Variable `c` is included.

I believe the reason `variables_to_restore` acts this way is that it is typically called during evaluation, while the moving averages were set during training. During evaluation, no moving averages are set, so `variables_to_restore` cannot rely on the  `ExponentialMovingAverage`'s stored moving averages, which is why it uses `moving_avg_variables` instead.

@sguada, I think we should change the description to something like "If a variable is in `moving_avg_variables`, use its moving average variable name as the restore name; otherwise, use the variable name." What do you think?

**Comment by gauss-clb** [comment]
I think it maybe a bug.
Look at the code:

```
x = tf.Variable(12.,name='x')
y = tf.Variable(34.,name='y')
z = tf.Variable(0, trainable=False)
ema = tf.train.ExponentialMovingAverage(.0)
ema.apply([x])
print(ema.variables_to_restore())

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    saver = tf.train.Saver()
    saver.save(sess, './model.ckpt')

```
First, I save the variables to check point.

```
x = tf.Variable(12.,name='x')
y = tf.Variable(34.,name='y')
z = tf.Variable(0, trainable=False)
ema = tf.train.ExponentialMovingAverage(.0)
ema.apply([x])
print(ema.variables_to_restore())

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    saver = tf.train.Saver(ema.variables_to_restore())
    saver.restore(sess, './model.ckpt')
```

Then, I want to restore variables from the check point. I want to load x with x_shadow, load y with y, and load z with z. But it will raise a error. Because `ema.variables_to_restore()` will map `y_shadow_name` to y, but there is no key of `y_shadow_name`, and z is untrainable variable, so it can load correct.

So I think the purpose of  `variables_to_restore()` is to load moving average variables with shadow, such as x, but don't want to load non-moving average variables with shadow, such as y.

@reedwm

**Comment by sguada** [comment]
As the docs and @reedwm  mentioned by default `ema.variables_to_restore()` uses `tf.moving_average_variables() + tf.trainable_variables()`.

But you can get the behavior that want by doing

```
x = tf.Variable(12.,name='x')
y = tf.Variable(34.,name='y')
z = tf.Variable(0, trainable=False)
ema = tf.train.ExponentialMovingAverage(.0)
ema.apply([x])
variables_to_restore = ema.variables_to_restore(tf.moving_average_variables())
print(variables_to_restore)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    init.run()
    saver = tf.train.Saver(variables_to_restore)
    saver.restore(sess, './model.ckpt')
```

**Comment by gauss-clb** [comment]
It is wrong if you use `saver = tf.train.Saver(variables_to_restore)`, because the shadow variables aren't saved in check point. And the `variables_to_restore` map shadow name to moving average variable(just mean in check point, key=shadow_name, value=moving average variable), so when you restore(variables_to_restore), the moving average variables will be load by themselves, not their shadows. But our purpose is to load moving average variables  with their shadows.

@sguada

**Comment by sguada** [comment]
I'm sorry but I don't understand you comment. 

The code I suggested is for the restoring phase, for saving one would use `tf.train.Saver()` which would save `x`, `y`, `z` and `x/ExponentialMovingAverage`

If you print `variables_to_restore` I would expect that you get the following:
```
{'x/ExponentialMovingAverage': <tf.Variable 'x:0' shape=() dtype=float32_ref>, 
'y': <tf.Variable 'y:0' shape=() dtype=float32_ref>,
'z': <tf.Variable 'z:0' shape=() dtype=float32_ref>}
```

What means that the variable `x` would restore its value from `x/EMA` instead of from `x` itself, while `y` and `z` would restore their values from themselves.

**Comment by gauss-clb** [comment]
If I can get `'y': <tf.Variable 'y:0' shape=() dtype=float32_ref>`, I won't ask this question.
Look at  my first commit, you will also get `'y/ExponentialMovingAverage': <tf.Variable 'y:0' shape=() dtype=float32_ref>`

**Comment by sguada** [comment]
If you do what I mentioned then you would get it, because now we are telling ema that we only want to use `x.ema` but not the others by passing `(tf.moving_average_variables()`

```
x = tf.Variable(12.,name='x')
y = tf.Variable(34.,name='y')
z = tf.Variable(0, trainable=False)
ema = tf.train.ExponentialMovingAverage(.0)
ema.apply([x])
variables_to_restore = ema.variables_to_restore(tf.moving_average_variables())
print(variables_to_restore)
```
```
{u'y': <tf.Variable 'y:0' shape=() dtype=float32_ref>, u'Variable': <tf.Variable 'Variable:0' shape=() dtype=int32_ref>, u'x/ExponentialMovingAverage': <tf.Variable 'x:0' shape=() dtype=float32_ref>}
```
