### ISSUE TITLE
Using a `tf.Tensor` as a Python `bool` is not allowed

### ISSUE THREAD

**Issue by jiqiujia** [tensorflow/tensorflow#11840]
```
import tensorflow as tf

a = tf.constant([1,2,3])
b = tf.equal(a, 0)

with tf.Session() as ss:
    print(ss.run(a,b))
```
When I run the code above, I encounter the following errors:

> TypeError: Using a `tf.Tensor` as a Python `bool` is not allowed. Use `if t is not None:` instead of `if t:` to test if a tensor is defined, and use TensorFlow ops such as tf.cond to execute subgraphs conditioned on the value of a tensor.

But when I change to the following code, it doesn't raise a exception
```
import tensorflow as tf

a = tf.constant([1,2,3])
b = tf.equal(a, 0)

with tf.Session() as ss:
    print(ss.run(a))
    print(ss.run(b))
```
with the output of 

> [1 2 3]
[False False False]

It seems to be a bug, or it's designed to be so?

**Comment by yaroslavvb** [comment]
Not a bug, `b` is treated as the `feed_dict` argument, you probably meant to do `ss.run([a,b])`

**Comment by jiqiujia** [comment]
Oh, yes, what a careless mistake! Thank you very much.

**Comment by mkw18** [comment]
def iou(y_pred, y_true):
        y_pred = tf.cast((y_pred > 0), dtype=tf.float32)
        i = tf.reduce_sum(y_true * y_pred)
        u = tf.reduce_sum(y_true + y_pred)
        return (i / u).item()if u != 0 else u.item()
    
    model.compile(optimizer = Adam(lr = 1e-4), loss = 'binary_crossentropy', metrics = ['accuracy',iou])

I encounter similar error when I run this code. The error messages are as follow.
---------------------------------------------------------------------------
OperatorNotAllowedInGraphError            Traceback (most recent call last)
<ipython-input-197-a5eb92cb206c> in <module>
----> 1 model = unet()

<ipython-input-191-57144cd2aad3> in unet(pretrained_weights, input_size)
     51         return (i / u).item()if u != 0 else u.item()
     52 
---> 53     model.compile(optimizer = Adam(lr = 1e-4), loss = 'binary_crossentropy', metrics = ['accuracy',iou])
     54 
     55     model.summary()

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training.py in compile(self, optimizer, loss, metrics, loss_weights, sample_weight_mode, weighted_metrics, target_tensors, distribute, **kwargs)
    437           targets=self._targets,
    438           skip_target_masks=self._prepare_skip_target_masks(),
--> 439           masks=self._prepare_output_masks())
    440 
    441       # Prepare sample weight modes. List with the same length as model outputs.

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training.py in _handle_metrics(self, outputs, targets, skip_target_masks, sample_weights, masks, return_weighted_metrics, return_weighted_and_unweighted_metrics)
   2002           metric_results.extend(
   2003               self._handle_per_output_metrics(self._per_output_metrics[i],
-> 2004                                               target, output, output_mask))
   2005         if return_weighted_and_unweighted_metrics or return_weighted_metrics:
   2006           metric_results.extend(

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training.py in _handle_per_output_metrics(self, metrics_dict, y_true, y_pred, mask, weights)
   1953       with K.name_scope(metric_name):
   1954         metric_result = training_utils.call_metric_function(
-> 1955             metric_fn, y_true, y_pred, weights=weights, mask=mask)
   1956         metric_results.append(metric_result)
   1957     return metric_results

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\engine\training_utils.py in call_metric_function(metric_fn, y_true, y_pred, weights, mask)
   1153 
   1154   if y_pred is not None:
-> 1155     return metric_fn(y_true, y_pred, sample_weight=weights)
   1156   # `Mean` metric only takes a single value.
   1157   return metric_fn(y_true, sample_weight=weights)

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\metrics.py in __call__(self, *args, **kwargs)
    194     from tensorflow.python.keras.distribute import distributed_training_utils  # pylint:disable=g-import-not-at-top
    195     return distributed_training_utils.call_replica_local_fn(
--> 196         replica_local_fn, *args, **kwargs)
    197 
    198   @property

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\distribute\distributed_training_utils.py in call_replica_local_fn(fn, *args, **kwargs)
   1133     with strategy.scope():
   1134       return strategy.extended.call_for_each_replica(fn, args, kwargs)
-> 1135   return fn(*args, **kwargs)
   1136 
   1137 

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\metrics.py in replica_local_fn(*args, **kwargs)
    177     def replica_local_fn(*args, **kwargs):
    178       """Updates the state of the metric in a replica-local context."""
--> 179       update_op = self.update_state(*args, **kwargs)  # pylint: disable=not-callable
    180       with ops.control_dependencies([update_op]):
    181         result_t = self.result()  # pylint: disable=not-callable

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\utils\metrics_utils.py in decorated(metric_obj, *args, **kwargs)
     74 
     75     with tf_utils.graph_context_for_symbolic_tensors(*args, **kwargs):
---> 76       update_op = update_state_fn(*args, **kwargs)
     77     if update_op is not None:  # update_op will be None in eager execution.
     78       metric_obj.add_update(update_op)

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\keras\metrics.py in update_state(self, y_true, y_pred, sample_weight)
    585         y_pred, y_true)
    586 
--> 587     matches = self._fn(y_true, y_pred, **self._fn_kwargs)
    588     return super(MeanMetricWrapper, self).update_state(
    589         matches, sample_weight=sample_weight)

<ipython-input-191-57144cd2aad3> in iou(y_pred, y_true)
     49         i = tf.reduce_sum(y_true * y_pred)
     50         u = tf.reduce_sum(y_true + y_pred)
---> 51         return (i / u).item()if u != 0 else u.item()
     52 
     53     model.compile(optimizer = Adam(lr = 1e-4), loss = 'binary_crossentropy', metrics = ['accuracy',iou])

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py in __bool__(self)
    755       `TypeError`.
    756     """
--> 757     self._disallow_bool_casting()
    758 
    759   def __nonzero__(self):

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py in _disallow_bool_casting(self)
    524     else:
    525       # Default: V1-style Graph execution.
--> 526       self._disallow_in_graph_mode("using a `tf.Tensor` as a Python `bool`")
    527 
    528   def _disallow_iteration(self):

~\Anaconda3\envs\tf2\lib\site-packages\tensorflow_core\python\framework\ops.py in _disallow_in_graph_mode(self, task)
    513     raise errors.OperatorNotAllowedInGraphError(
    514         "{} is not allowed in Graph execution. Use Eager execution or decorate"
--> 515         " this function with @tf.function.".format(task))
    516 
    517   def _disallow_bool_casting(self):

OperatorNotAllowedInGraphError: using a `tf.Tensor` as a Python `bool` is not allowed in Graph execution. Use Eager execution or decorate this function with @tf.function.

### How can I correct my code so that I can run it successfully?
