### ISSUE TITLE
Command 'graph_transforms/transform_graph' not found.

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#11885]
i ran the following script since i want to optimise the graph for using in android.

```
bazel graph_transforms/transform_graph \
--in_graph=stripped.pb \
--out_graph=optimized_stripped.pb \
--inputs='Mul' \
--outputs='final_result' \
--transforms='
  strip_unused_nodes(type=float, shape="1,160,160,3")
  fold_constants(ignore_errors=true)
  fold_batch_norms
  fold_old_batch_norms
  round_weights(num_steps=256)
```
Im getting the following error..

`Command 'graph_transforms/transform_graph' not found. Try 'bazel help'.
`

**Comment by poxvoculi** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by Cpruce** [comment]
@Zumbalamambo 
1. Clone tensorflow
2. bazel build tensorflow from source
3. bazel build transform_graph
4. profit
