### ISSUE TITLE
Where can I find c++ head file "tensorflow/cc/ops/sparse_ops.h"

### ISSUE THREAD

**Issue by sttomato** [tensorflow/tensorflow#11899]
I want to use the sparse tensor in C++ API(https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/add-sparse-to-tensors-map). 
But when I search in "https://github.com/tensorflow/tensorflow", there is no "tensorflow/cc/ops/sparse_ops.h"
Does anyone know how to use the sparse tensor in C++?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(That file is generated by the build system and located in `bazel-genfiles/tensorflow/cc/ops/sparse_ops.h` when you build from source)

**Comment by AbduElrahmanRezk** [comment]
@asimshankar please can specify where bazel-genfiles/ is ? in ubuntu
