### ISSUE TITLE
Warning when running rnn_commons.select_last_activations (TensorFlow 1.2.1)

### ISSUE THREAD

**Issue by mari-linhares** [tensorflow/tensorflow#12005]
I see the following warning:
/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gradients_impl.py:93: UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.

**Comment by poxvoculi** [comment]
If you look at the source code where the warning originates, you'll see it triggers when the implied dense tensor has more than 10M elements.  For performance reasons you may want to avoid triggering this conversion if possible.


This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
