### ISSUE TITLE
foldr is too restrictive:  dimension 0 in both shapes must be equal

### ISSUE THREAD

**Issue by edgimar** [tensorflow/tensorflow#12019]
Using TF 1.2.0-rc1 on Ubuntu 16.04.

There are cases where `tf.foldr` should work, but is unable to because of a restriction that the first shape dimensions be identical for all list elements.  Below is a self-contained example that demonstrates the problem:

```
import tensorflow as tf
sess = tf.InteractiveSession()

def concat2(A, B):
    return tf.concat([A, B], axis=0)

A = tf.constant([[10,10]])             # A.shape => (1,2)
B = tf.constant([[20, 20], [30, 30]])  # B.shape => (2,2)

print(concat2(A, B).eval())              # => [[10, 10], [20, 20], [30, 30]]
print(tf.foldr(concat2, [A, B]).eval())  # => ERROR!
```

**Comment by poxvoculi** [comment]
I suppose it might be possible for foldr to work on binary functions whose two inputs need not have the same dimensions, but this might have unfortunate consequences for shape inference.  @mrry would we welcome a contribution of that kind?

**Comment by yongtang** [comment]
Currently `tf.foldl` and `tf.foldr` converts input elems into a `Tensor`, and then the converted `Tensor` is converted into a `TensorArray`:
https://github.com/tensorflow/tensorflow/blob/1e1b3d90295f9396a25b9cfd4c571f7949716182/tensorflow/python/ops/functional_ops.py#L100-L106

It is possible to bypass the step of `ops.convert_to_tensor()` and convert the input elems directly to a `TensorArray`. In this way, the restriction mentioned in this issue would be gone and the input elems could be any type as long as it is `Iterable`.

However, this might be a change in behavior so I am not sure. Nevertheless I created a PR #13282 so that further discussion could be done there.

**Comment by sushreebarsa** [comment]
@edgimar It is raising this [error](https://colab.research.google.com/gist/sushreebarsa/3f787d1c833de9a1732b281564601535/12019.ipynb). Please have a look at the [migration](https://www.tensorflow.org/guide/migrate) document and try to upgrade to the latest stable version. 
If you still face the issue then Kindly create a new ticket as you are using an older version of TF which is not actively supported. Thank you!
