### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by Zumbalamambo** [tensorflow/tensorflow#12082]
Im getting the following error while training mobile net model as

```
 python retrain.py \
    --image_dir ~/dataset --architecture mobilenet_1.0_224
```

Following is the error..

```
 _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "retrain.py", line 989, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by Mazecreator** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  mazecreator@gmail.com
    Domain mazecreator.com has exceeded the max emails per hour (28/25 (112%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from o7.sgmail.github.com ([167.89.101.198]:19977)
	by server2.lowesthostingrates.com with esmtps (TLSv1.2:ECDHE-RSA-AES128-GCM-SHA256:128)
	(Exim 4.89)
	(envelope-from <bounces+848413-e6d9-mazecreator=mazecreator.com@sgmail.github.com>)
	id 1dem78-000137-6n
	for mazecreator@mazecreator.com; Mon, 07 Aug 2017 12:47:20 -0500
DKIM-Signature: v=1; a=rsa-sha1; c=relaxed/relaxed; d=github.com; 
	h=from:reply-to:to:cc:subject:mime-version:content-type:content-transfer-encoding:list-id:list-archive:list-post:list-unsubscribe; 
	s=s20150108; bh=sxb50LBJRvieO1wieg58SOe0iLs=; b=p3IntJbwfhhPGeJ0
	JTR26vfjtl+1ACjgAwIiuBTFZXFZE/p6uv3UMWRhXV42PXMTFOw3u5soQaQgeG+5
	ogGFUmkSKk/ztxHYQDqnIB4FUsYXq/V5DiFxCviU1q7+1/qKe8sfIQUGS2PX4VeS
	YA1nkyAe9zTmzzATzTAsLPUP7Jc=
Received: by filter0944p1mdw1.sendgrid.net with SMTP id filter0944p1mdw1-28386-5988AA08-31
        2017-08-07 17:57:28.3777779 +0000 UTC
Received: from github-smtp2b-ext-cp1-prd.iad.github.net (github-smtp2b-ext-cp1-prd.iad.github.net [192.30.253.17])
	by ismtpd0027p1mdw1.sendgrid.net (SG) with ESMTP id If3CCDphSxaBaCCZQ3rS2Q
	for <mazecreator@mazecreator.com>; Mon, 07 Aug 2017 17:57:28.334 +0000 (UTC)
Date: Mon, 07 Aug 2017 17:57:28 +0000 (UTC)

**Comment by rohan100jain** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

Also in this particular case, would be helpful to know which retrain.py were you using.
