### ISSUE TITLE
WARNING:tensorflow:The default stddev value of initializer will change from “1/sqrt(vocab_size)” to “1/sqrt(dimension)” after 2017/02/25

### ISSUE THREAD

**Issue by datomnurdin** [tensorflow/tensorflow#12095]
I got this warning message when set Deep Model.

Warning message

```
WARNING:tensorflow:The default stddev value of initializer will change from "1/sqrt(vocab_size)" to "1/sqrt(dimension)" after 2017/02/25.
```

My code

```
    deep_columns = [
      tf.contrib.layers.embedding_column(workclass, dimension=8),
      tf.contrib.layers.embedding_column(education, dimension=8),
      tf.contrib.layers.embedding_column(gender, dimension=8),
      tf.contrib.layers.embedding_column(relationship, dimension=8),
      tf.contrib.layers.embedding_column(native_country, dimension=8),
      tf.contrib.layers.embedding_column(occupation, dimension=8),
      age, education_num, capital_gain, capital_loss, hours_per_week
    ]
```

Please advice. Thank you.

**Comment by printdhruv** [comment]
The `tf.contrib.layers.embedding_column` has no `initializer` value set. If you don't set it then defaults to `tf.truncated_normal_initializer` with mean 0.0 and `standard deviation 1/sqrt(sparse_id_column.length).`

So,the warning states that A new changed implementation for default of standard deviation  will be `1/sqrt(dimension)` after 2017/02/25 instead of `1/sqrt(vocab_size)`

**Comment by tatatodd** [comment]
@printdhruv Thanks for the explanation!

@datomnurdin For future reference, note that this question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
