### ISSUE TITLE
EigenAllocator for GPU ran out of memory when allocating 0 

### ISSUE THREAD

**Issue by Sharathnasa** [tensorflow/tensorflow#12147]
Environment info

Operating System: Ubuntu 16.04
Installed version of CUDA and cuDNN: CUDA-8.0, CUDNN 5.1.10
Tensorflow version r1.1

Hello, does anyone encountered this error ?

After some random number of iterations, i'm getting the below exception. Can anyone help me where its going wrong?

: E tensorflow/core/common_runtime/bfc_allocator.cc:244] tried to allocate 0 bytes
: W tensorflow/core/common_runtime/allocator_retry.cc:32] Request to allocate 0 bytes
: F tensorflow/core/common_runtime/gpu/gpu_device.cc:103] EigenAllocator for GPU ran out of memory when allocating 0. See error logs for more detailed info.
Aborted (core dumped)

Regards,
Sharath

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

Also note #492 has some extra info that may be interesting to you.  I found that via the following search:
https://github.com/issues?utf8=%E2%9C%93&q=repo%3Atensorflow%2Ftensorflow+%22EigenAllocator+for+GPU+ran+out+of+memory%22
