### ISSUE TITLE
Feature request: document which inputs have gradients

### ISSUE THREAD

**Issue by nrhinehart** [tensorflow/tensorflow#12154]
For most operations, the documentation does not make clear what gradients are implemented. Including this information for the inputs (e.g. annotating the inputs that do not have gradients implemented) would help the user better understand the resulting graph. 

It appears a related issue was closed, as it was not a feature request. https://github.com/tensorflow/tensorflow/issues/6025

**Comment by rohan100jain** [comment]
Seems like a reasonable thing to ask for but I'm not sure whether this is something we're thinking of working on actively in the near future. We do welcome contributions though!

**Comment by Dapid** [comment]
Since the gradients are registered in the code, shouldn't it be possible to build the list programatically?

Parse each "ops" file in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/ops, and match the names with the corresponding "grad".

**Comment by yaroslavvb** [comment]
As a heuristic, you could search for all instances of `ops.RegisterGradient`, that gives you which op has a gradient associated. You can then get source, and parse out `None`s out of `return` line, which gives you the inputs without gradients.

Note that this works only for atomic ops. Something like `tf.norm` will support gradients, but there are no gradients for this op in particular because it's defined in terms of sqrt/reduce_sum/etc

**Comment by sushreebarsa** [comment]
@nrhinehart Could you check this [doc](https://www.tensorflow.org/api_docs/python/tf/norm) of tf.norm.  This function can compute several different vector norms. 
If you still have any concerns, please raise a new request. Thank you!
