### ISSUE TITLE
Lack of documentation in tf.decode_raw

### ISSUE THREAD

**Issue by iurilarosa** [tensorflow/tensorflow#12234]
Hi, 
i need to load arrays stored in tfrecords files, so i need to convert the raw string/byte data to number, but i don't understand the output i get using `tf.decode_raw`. Unfortunately function documentation doesn't help me.

Here an example of the strange (for me) behavior of this function

```
import numpy
import tensorflow as tf
sess = tf.Session()


array = numpy.array([0.1, 0.2, 0.4, 0.8, 0.9, 1.1])
print(array.tobytes())
print(numpy.fromstring(array.tobytes()))

tensoraw = tf.constant(array.tobytes())

print(sess.run(tensoraw))
print(sess.run(tf.decode_raw(tensoraw, tf.float32)))

rawArray = sess.run(tensoraw)
decodedArray = sess.run(tf.decode_raw(tensoraw, tf.float32))
print(numpy.fromstring(rawArray))
print(numpy.fromstring(decodedArray))
```
with this output
```
b'\x9a\x99\x99\x99\x99\x99\xb9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xd9?\x9a\x99\x99\x99\x99\x99\xe9?\xcd\xcc\xcc\xcc\xcc\xcc\xec?\x9a\x99\x99\x99\x99\x99\xf1?'

[ 0.1  0.2  0.4  0.8  0.9  1.1]

b'\x9a\x99\x99\x99\x99\x99\xb9?\x9a\x99\x99\x99\x99\x99\xc9?\x9a\x99\x99\x99\x99\x99\xd9?\x9a\x99\x99\x99\x99\x99\xe9?\xcd\xcc\xcc\xcc\xcc\xcc\xec?\x9a\x99\x99\x99\x99\x99\xf1?'

[ -1.58818684e-23   1.44999993e+00  -1.58818684e-23   1.57499993e+00
  -1.58818684e-23   1.69999993e+00  -1.58818684e-23   1.82499993e+00
  -1.07374184e+08   1.84999990e+00  -1.58818684e-23   1.88749993e+00]

[ 0.1  0.2  0.4  0.8  0.9  1.1]

[ 0.1  0.2  0.4  0.8  0.9  1.1]
```

The strangest thing for me is that numpy.fromstring applied both to the raw tensor and the decoded tensor (evaluated) gives the same output.
Thank you.

**Comment by quaeler** [comment]
`decode_raw` in converting a string to an array of numbers, in a datatype specified.

numpy's `tobytes` is producing a string of bytes, 8 bytes per value to represent the default numpy float value (64 bit) - so you end up with 48 bytes in your string.

At that point, calling `decode_raw` with float32 as the desired data type is producing 12 values instead of the original 6 (since you've halved the bytes per value). If you called the operation with `tf.uint8` you'd see 48 values - each byte as an int value - and if you called it with `tf.float64` you'd get your original array values back (because you're just converting back to the original datatype.)

Hope this helps.

**Comment by iurilarosa** [comment]
Oh ok! This is because numpy arrays have float64 data type as default!
With `array = numpy.array([0.1, 0.2, 0.4, 0.8, 0.9, 1.1]).astype(numpy.float32)` i have back the original values with `tf.decode_raw(tensoraw, tf.float32)` (you don't say? :) )

Thank you so much. I don't know if the issue can be closed, or if the `decode_raw` documentation still needs a better description of the "Returns:" section.

**Comment by reedwm** [comment]
Closing since it seems the issue was not with the documentation, but with confusion over the fact the default numpy type is float64, not float32. Feel free to reopen if you still think the documentation is unclear.
