### ISSUE TITLE
Feature: add safe mode for tf.cast

### ISSUE THREAD

**Issue by facaiy** [tensorflow/tensorflow#12235]
tf.cast allows to cast float value to int without any warnning. It seems quite unsafe and data will be truncated.

```python
In [34]: tf.__version__
Out[34]: '1.2.1'

In [35]: sess.run(tf.cast(tf.constant(100000, tf.float32), tf.int16
))
Out[35]: -31072
```

Perhaps  it will be better, like [astype](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.astype.html) in numpy, to add a `casting` to support both safe and unsafe casting mode.

I can work on it if possible.

**Comment by facaiy** [comment]
Same problem for `tf.to_xxx` methods:

```python
In [37]: sess.run(tf.to_int32(tf.constant(10000000000, tf.float64)))
Out[37]: -2147483648
```

**Comment by Edwin222** [comment]
If I understand correctly, you can use tf.saturate_cast() instead of cast().

**Result by cast()**
![pre11](https://user-images.githubusercontent.com/28051014/29648843-56756302-88cb-11e7-9717-5bfd745a58ed.png)
![pre12](https://user-images.githubusercontent.com/28051014/29648845-57bfd90e-88cb-11e7-8123-50aacf6a4d21.png)

**Result by saturate_cast()**
![pre13](https://user-images.githubusercontent.com/28051014/29648849-5958d02c-88cb-11e7-854a-c6ada219d995.png)
![pre14](https://user-images.githubusercontent.com/28051014/29648850-5a77ff32-88cb-11e7-87f8-62472dca5254.png)

**Comment by facaiy** [comment]
Thanks for your suggestion, @Edwin222 . `saturate_cast` is a good alternative.
