### ISSUE TITLE
not installing 

### ISSUE THREAD

**Issue by RahulDos** [tensorflow/tensorflow#12253]
Collecting tensorflow
  Could not find a version that satisfies the requirement tensorflow (from versions: )
No matching distribution found for tensorflow

**Comment by jubjamie** [comment]
_Please make sure you fill in the issue template to ensure that your issue can be troubleshooted correctly. Key information includes System Specs and Tensorflow/CUDA/cuDNN versions. Without this it's harder to help!_

Absolutely not enough information here to help. This is usually caused by an incompatible system/python version. Please fill in the Issue Template and it will be possible to give you an answer.

**Comment by zouhair0** [comment]
Hi
i have the same problem... so i wonder if tensorflow doesn' t work with linux 32 bit ????

**Comment by gunan** [comment]
No, tensorflow is not supported and does not work out of the box on 32-bit desktop operating systems.
You can probably make it work by building from sources, but you need to reach out to the community in stackoverflow for support with issues on that.

**Comment by zouhair0** [comment]
Thanks gunan
i just tried to do it from sources.But unfortunately, Bazel doesn't work in 32-bits:
N: Skipping acquire of configured file 'jdk1.8/binary-i386/Packages' as repository 'http://storage.googleapis.com/bazel-apt stable InRelease' doesn't support architecture 'i386'
Thanks anyway
