### ISSUE TITLE
BUILD:1227:1

### ISSUE THREAD

**Issue by dilli007** [tensorflow/tensorflow#12360]
bazel build //tensorflow:libtensorflow.so
ERROR: /Users/dile/tensorflow/tensorflow/core/BUILD:1227:1: no such target '//tensorflow/tools/git:gen/spec.json': target 'gen/spec.json' not declared in package 'tensorflow/tools/git' defined by /Users/dile/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/dile/tensorflow/tensorflow/core/BUILD:1227:1: no such target '//tensorflow/tools/git:gen/head': target 'gen/head' not declared in package 'tensorflow/tools/git' defined by /Users/dile/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: /Users/dile/tensorflow/tensorflow/core/BUILD:1227:1: no such target '//tensorflow/tools/git:gen/branch_ref': target 'gen/branch_ref' not declared in package 'tensorflow/tools/git' defined by /Users/dile/tensorflow/tensorflow/tools/git/BUILD and referenced by '//tensorflow/core:version_info_gen'.
ERROR: Analysis of target '//tensorflow:libtensorflow.so' failed; build aborted.

**Comment by reedwm** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by gunan** [comment]
Your error messages indicate that you forgot to run configure script. Please make sure to follow the installing from sources documentation when trying to build tensorflow from sources:
https://www.tensorflow.org/install/install_sources
