### ISSUE TITLE
[Feature] InputStream variant for ReadBinaryProto and ReadTextProto

### ISSUE THREAD

**Issue by resec** [tensorflow/tensorflow#12379]
### System information

N/A

### Describe the problem
Currently in master branch both ReadBinaryProto and ReadTextProto accepts only file path to load model proto, while in some cases we may want to load from a network stream or any other input stream of model proto file that input stream is our best option.

So I think adding two variants accepts stream input instead of file path should be good. As both these ReadBinaryProto and ReadTextProto are in C++ public API, may I know is it feasible to add? Or any other security or implementation difficulty that is blocking it? Or design conflict? 

If it is just lacking of people, sure I can help.

### Source code / logs

N/A

**Comment by reedwm** [comment]
@tatatodd what do you think?

**Comment by tatatodd** [comment]
@resec What is the signature of your proposed API?  I.e. what exactly do you mean by 'input stream'?

Note that Read{Binary,Text}Proto are pretty short helper functions, and only exist because there are multiple uses in tests and command-line tools, when reading from files.  The proto library already has APIs to perform streaming input, which could be used directly without any TensorFlow-side wrapper.

**Comment by resec** [comment]
@tatatodd actually yesterday I tried to implement this feature, and than I found that I do agree with you that TensorFlow-side wrapper for this feature would be kind of redundant.

We can always load the model proto with protobuf lib only nicely. So just feel free to close this, thanks.

**Comment by tatatodd** [comment]
@resec Cool, closing this out.
