### ISSUE TITLE
Limit GPU memory usage not working in distributed training of inception

### ISSUE THREAD

**Issue by qinglintian** [tensorflow/tensorflow#12381]
I'm using the example provided for distributed trainig of [inception](https://github.com/tensorflow/models/blob/master/inception/inception/inception_distributed_train.py). I have three hosts, with one for parameter server and two for workers. All hosts have TensorFlow 1.2 installed with CUDA 8.0, cuDNN 5.1 and Titan X Pascal GPU running Ubuntu 14.04.

I followed the instruction for distributed training as provided in the [readme](https://github.com/tensorflow/models/blob/master/inception/README.md) and it runs successfully. But when I try to limit the GPU usage by making the following changes.

Change

sess_config = tf.ConfigProto(
          allow_soft_placement=True,
          log_device_placement=FLAGS.log_device_placement)

to

sess_config = tf.ConfigProto(
          allow_soft_placement=True,
          log_device_placement=FLAGS.log_device_placement,
          gpu_options=tf.GPUOptions(per_process_gpu_memory_fraction=0.6))

in [inception_distributed_train.py](https://github.com/tensorflow/models/blob/master/inception/inception/inception_distributed_train.py#L255)

I recompiled the example using 'bazel build //inception:imagenet_distributed_train' and run the example. But the process still occupies all GPU memory available observed using nvidia-smi.

**Comment by mrry** [comment]
The device options are interpreted somewhat differently in the distributed version of TensorFlow, because they are properties of the [`tf.train.Server`](https://www.tensorflow.org/api_docs/python/tf/train/Server), rather than an individual `tf.Session`. If you pass the same `sess_config` object as the optional `config` arg to the `tf.train.Server` constructor, you should get the desired behavior.

I'll close this issue for now, but feel free to reopen if it doesn't solve the problem.

**Comment by qinglintian** [comment]
Thank you @mrry ，that solves the problem.

**Comment by mrry** [comment]
Thanks for confirming!
