### ISSUE TITLE
Anaconda installation example doesn't match the description on web site

### ISSUE THREAD

**Issue by pulzar** [tensorflow/tensorflow#12393]
On this page:

https://www.tensorflow.org/install/install_linux#installing_with_anaconda

Step 4 says: 

> where tfBinaryURL is the URL of the TensorFlow Python package. For example, the following command installs the CPU-only version of TensorFlow for Python 2.7:

However, the example command below it actually installs TensorFlow for Python 3.4, not 2.7:

> pip install --ignore-installed --upgrade \
>  https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.3.0-cp34-cp34m-linux_x86_64.whl

**Comment by asimshankar** [comment]
This was fixed in https://github.com/tensorflow/tensorflow/commit/17f9320b33069ecda689bc71a917f5df5911666f at head (see #11708), however it seems that that change didn't make it to the r1.3. branch and the website content is now from the r1.3 branch.

@av8ramit : Could you take a look - should that change be merged into the r1.3 branch and the website re-pushed?

**Comment by av8ramit** [comment]
I'll CP this and push the docs, thanks @asimshankar and @pulzar

**Comment by av8ramit** [comment]
This is live.
