### ISSUE TITLE
nsync is broken on Windows in Bazel build

### ISSUE THREAD

**Issue by meteorcloudy** [tensorflow/tensorflow#12524]
http://ci.tensorflow.org/job/tf-master-win-bzl/1459/console
```
11:36:56 ERROR: C:/tmp/_bazel_system/424zmya1/external/nsync/BUILD:357:13: Configurable attribute "copts" doesn't match this configuration (would a default condition help?).
11:36:56 Conditions checked:
11:36:56  @nsync//:android_arm
11:36:56  @nsync//:android_arm64
11:36:56  @nsync//:android_armeabi
11:36:56  @nsync//:android_x86_32
11:36:56  @nsync//:android_x86_64
11:36:56  @nsync//:clang_macos_x86_64
11:36:56  @nsync//:gcc_linux_aarch64
11:36:56  @nsync//:gcc_linux_ppc64
11:36:56  @nsync//:gcc_linux_x86_64_1
11:36:56  @nsync//:gcc_linux_x86_64_2
11:36:56  @nsync//:ios_x86_64
11:36:56 ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted
```
 nsync is introduced in b48cfaea2aea3707a33e60c10385a87e37101b95

Fortunately, nsync already builds on Windows with CMake, I've sent a PR to add Bazel support.
https://github.com/google/nsync/pull/1

/cc @m3bm3b Could you please merge the PR, or is there any other way you prefer me to contribute to this repo?

**Comment by meteorcloudy** [comment]
Merged at d3bc53d38bee13bf66354ca61694956c92ffe879

**Comment by FKNoble** [comment]
Replicated this with Bazel 0.5.3 on Windows 10. Couldn't get 0.5.4 to work, otherwise I'd try with that too.

**Comment by ali01** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by meteorcloudy** [comment]
@FKNoble This issue has been fixed from nsync repo by d3bc53d38bee13bf66354ca61694956c92ffe879

We also have a [PR](https://github.com/tensorflow/tensorflow/pull/12603#issuecomment-325004977) to update nsync in TensorFlow.

**Comment by michaelisard** [comment]
Adding contributions welcome tag while PR is in flight.

**Comment by meteorcloudy** [comment]
Fixed by https://github.com/tensorflow/tensorflow/pull/12603
