### ISSUE TITLE
Java load python trained mode by SavedModelBundle predict wrong result

### ISSUE THREAD

**Issue by fancyerii** [tensorflow/tensorflow#12673]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
14.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.3/1.2.1
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

 

### Describe the problem
I trained a simple model using python and save it with SavedModelBuilder. Then I loaded it using java. it's loaded successfully but predict wrong result.

### Source code / logs
My python code is in
https://gist.github.com/fancyerii/af10e8cc35ffda4c983c6e9cf074b317
and java code https://gist.github.com/fancyerii/c1096f9f8c9bd9705da1b1c7d6ca2138

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(Though, from the gist of your Python code, I can see one problem - you're invoking `tf.global_variables_initializer().run()` inside the `save_model` function, which means that you're changing the weights to their initial (as opposed to trained) value before saving the model. As a result, the saved model doesn't have the trained weights so your predictions will be wrong)

**Comment by joyspark** [comment]
I have the same issue.
fancyerii, did you solved this problem?
My python code is in
https://github.com/joyspark/TensorFlow/blob/master/simpleRegression.py
and java code
https://github.com/joyspark/TensorFlow/blob/master/loadPythonModel.java

**Comment by gypleon** [comment]
@joyspark @fancyerii hi, have you resolved the problem? the SavedModelBundle document is so blurred... I  even cannot load the saved model successfully using SavedModelBundle.load() in java.

**Comment by asimshankar** [comment]
@gypleon : Feel free to file a new issue if you're having trouble loading the saved model - though do include a short example to reproduce the problem.

Haven't heard back from @fancyerii , but there was certainly a problem wherein the model was being exported with random weights, not the trained weights. Not sure about @joyspark 's issue
