### ISSUE TITLE
User ops documentation not sufficient

### ISSUE THREAD

**Issue by mhejrati** [tensorflow/tensorflow#1270]
I followed the documentation for building a user ops (https://www.tensorflow.org/versions/master/how_tos/adding_an_op/index.html), 
trying the zero_out op, there are a couple of places where the doc is not clear and also after hacking my way around it the op failed to work.

I am following the instructions for adding an op with Tensorflow source installation. 
Here are the questions:
1- Where should the bazel build rule be placed? 
2- How to exactly use bazel to build the op?

I appreciate if you can clarify the documentation, it will help a lot.

**Comment by vrv** [comment]
@keveman, @josh11b

**Comment by kbrems** [comment]
The documentation is actually not correct. You have to add the line
#include "tensorflow/core/framework/op_kernel.h"
to your zero_op.cc in order for it to build (this line was in the original 0.6 release user operator tutorial). 
However including this line will not work as stated if you try to use the binary installation, as this file includes "third_party/eigen3/unsupported/Eigen/CXX11/Tensor" which is not in the /usr/local/lib/python2.7/dist-packages/tensorflow/include directory. 

g++ -std=c++11 -shared zero_out.cc -o zero_out.so \
 -I $TF_INC -l tensorflow_framework -L $TF_LIB \
 -fPIC -Wl,-rpath $TF_LIB
In file included from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/type_traits.h:22:0,
                 from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/allocator.h:25,
                 from /usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/op_kernel.h:22,
                 from zero_out.cc:10:
/usr/local/lib/python2.7/dist-packages/tensorflow/include/tensorflow/core/framework/types.h:23:61: fatal error: third_party/eigen3/unsupported/Eigen/CXX11/Tensor: No such file or directory
 #include "third_party/eigen3/unsupported/Eigen/CXX11/Tensor"

It is not enough to just install eigen externally because the tensorflow include files hard-code the "third_party" path. Those files then include the "real" eigen files. I had to first download eigen-eigen-ed4c9730b545 and then download the full tensorflow source and copy the third_party directory and then put both eigen-eigen-ed4c9730b545 path and the path to my third_party directory in my build command as -I flags. This kind of defeats the goal of being able to create user operators with only the binary installation. 

With all the include paths set up, I was able to run the zero_out op from python, but it generates a segfault after the op is run. Exit code is 139, which is an invalid memory access. Note, I am running the gpu version of the pip package, but the zero_out op is running on my cpu as it has no gpu operator registered.

$ cat zero_out_test.py 
import tensorflow as tf
zero_out_module = tf.load_op_library('/home/kbrems/zeroout/libzero_out.so')
with tf.Session(''):
  result = zero_out_module.zero_out([[1, 2], [3, 4]]).eval()
  print result

$ python zero_out_test.py 
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties: 
name: GeForce GTX TITAN
major: 3 minor: 5 memoryClockRate (GHz) 0.928
pciBusID 0000:05:00.0
Total memory: 6.00GiB
Free memory: 5.51GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:717] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN, pci bus id: 0000:05:00.0)
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 1.0KiB
...
I tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:51] Creating bin of max chunk size 8.00GiB
[[1 0]
 [0 0]]
Segmentation fault (core dumped)

Being able to create new operators without having to fork tensorflow and bury them in the user_ops directory and build all of tensorflow is a very useful feature. It seems though that it is not yet completely implemented. If I put this same zero_out.cc file into the tensorflow/core/user_ops directory and build all of tensorflow and run the test using the bazel test framework, putting the test in tensorflow/python/kernel_tests/zero_out_op_test.py, it does work.

**Comment by lfwin** [comment]
mark.
Also have the same question!

**Comment by cuiguoxin** [comment]
There is only one 'tensorflow' folder in the 'include' folder. When I add a user op in it, it fails. Hope this bug will soon be fixed. At least the docs should be edited in order to not mislead more people.

**Comment by keveman** [comment]
Sorry everyone about the breakage. Some changes got inadvertently pulled in that removed Eigen and third_party header files from the pip package. I added them back, and also clarified the documentation a bit. The 0.7.1 pip package still has the problem, but if you create the pip package from HEAD and install it, that should work.

**Comment by kbrems** [comment]
I built the pip package from master HEAD today and installed it. It now seems that the tensorflow_framework library is not being installed (or is not being installed or named the way the instructions say it is). Following the instructions on the tensorflow "Adding a New Op" -> "Building the Op library" -> "With TensorFlow binary installation"

$ set | grep TF_
TF_INC=/usr/local/lib/python2.7/dist-packages/tensorflow/include
TF_LIB=/usr/local/lib/python2.7/dist-packages/tensorflow/core

$ g++ -std=c++11 -shared zero_out.cc -o zero_out.so \
> -I $TF_INC -l tensorflow_framework -L $TF_LIB \
> -fPIC -Wl,-rpath $TF_LIB
/usr/bin/ld: cannot find -ltensorflow_framework
collect2: error: ld returned 1 exit status

$ ls -l /usr/local/lib/python2.7/dist-packages/tensorflow/core
total 24
drwxr-sr-x 2 root staff 4096 Mar 17 14:41 example
drwxr-sr-x 2 root staff 4096 Mar 17 14:41 framework
-rw-r--r-- 1 root staff    0 Mar 17 14:41 __init__.py
-rw-r--r-- 1 root staff  147 Mar 17 14:41 __init__.pyc
drwxr-sr-x 3 root staff 4096 Mar 17 14:41 lib
drwxr-sr-x 2 root staff 4096 Mar 17 14:41 protobuf
drwxr-sr-x 2 root staff 4096 Mar 17 14:41 util

$ ls -l /usr/local/lib/python2.7/dist-packages/tensorflow/core/lib
total 8
drwxr-sr-x 2 root staff 4096 Mar 17 14:41 core
-rw-r--r-- 1 root staff    0 Mar 17 14:41 __init__.py
-rw-r--r-- 1 root staff  151 Mar 17 14:41 __init__.pyc

$ ls -l /usr/local/lib/python2.7/dist-packages/tensorflow/core/lib/core
total 16
-rw-r--r-- 1 root staff 4848 Mar 17 14:41 error_codes_pb2.py
-rw-r--r-- 1 root staff 3960 Mar 17 14:41 error_codes_pb2.pyc
-rw-r--r-- 1 root staff    0 Mar 17 14:41 __init__.py
-rw-r--r-- 1 root staff  156 Mar 17 14:41 __init__.pyc

**Comment by keveman** [comment]
The website is lagging behind the documentation from HEAD. Can you please follow the instructions here : https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/how_tos/adding_an_op/index.md
