### ISSUE TITLE
from tensorflow.python.ops.gen_audio_ops import *

### ISSUE THREAD

**Issue by krishnadn** [tensorflow/tensorflow#12722]
I am trying to follow the steps as per the readme file.
I get an import error.
After i inspected the repo i found that "gen_audio_ops" is missing under tensorflow/python/ops package.

Following is an image which shows the import 
![image](https://user-images.githubusercontent.com/17523473/29909246-9f1e1b0e-8e42-11e7-8f89-d601281d38c0.png)

Can you please help to get me the said package.

**Comment by ydzhang12345** [comment]
I ran into similar issue. But if you built from source you will see that. Look like it will be generated during building.

**Comment by quaeler** [comment]
Ya - all files prefaced by `gen_` are files that are **gen**erated during the build process (for example ops in Python because they are built by a processor that examines the actual C code containing the operations.)

**Comment by sarah-zaheer** [comment]
I faced the same issue. I built tensorflow from source,but still getting the same issue. What else do I have to build from source to get this file? very confused :/

**Comment by quaeler** [comment]
@sarah-zaheer It would be most straight forward if you built the pip builder:
```
bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
```

After that completes, you could either build a wheel archive to install with pip by doing
```
bazel-bin/tensorflow/tools/pip_package/build_pip_package /some/directory/to/put/the/whl/in
```
or if your interested in this specific generated file, it should be at
```
bazel-genfiles/tensorflow/python/ops/gen_audio_ops.py
```

**Comment by sarah-zaheer** [comment]
@quaeler  Thank you very much :) Do I move this file to 'tensorflow/python/ops/' now?
OR would it be better if I changed the path and pointed it to 'bazel-genfiles/tensorflow/python/ops/'?

**Comment by quaeler** [comment]
@sarah-zaheer Were it me, i'd build the wheel and pip install into a virtualenv or a conda env. If you don't want to go that route, you could change the path, but try pointing it at
```
bazel-out/darwin_x86_64-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow
```
to pick up everything (adjusting that path for the name of your build architecture as necessary.)

**Comment by sarah-zaheer** [comment]
***My command:**
sudo python tensorflow/examples/speech_commands/train.py > --data_url= > --data_dir= /home/sarah/Downloads/final/ > --wanted_words= shout,glass > --how_many_training_steps= 1000,200 > --learning_rate= 0.001,0.0001 

***The output:**
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 79, in <module>
    import input_data
  File "/home/sarah/tensorflow/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ImportError: cannot import name audio_ops

***In /tensorflow/contrib/framework/python/ops/audio_ops.py :** 
   _from tensorflow.python.ops.gen_audio_ops import *_ 
(same as krishnadn reported)

***Then I found 'gen_audio_ops' at /bazel-genfiles/tensorflow/python/ops (just like you suggested) and moved this file to /tensorflow/python/ops**

***Now in gen_audio_ops,this line seems to be the problem :** 
    _from tensorflow.core.framework import op_def_pb2 as_op_def_pb2_ 

because 'op_def_pb2' is not at /tensorflow/core/framework

***Now as you suggested changing the path, I have this,**
_/bazel-out/local-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow_
where do I use it?

(Im sorry if my question is not in proper github format, Im very new here)

**Comment by quaeler** [comment]
Not gonna use pip, eh? :- )  Ok.. 

First, running this via sudo makes me feel unwell - usual caveats about not running things as sudo go here, and i'm done being a nanny.

Second, if you moved the `gen_audio_ops.py` file to `/tensorflow/python/ops`, move it back (or at least delete it from `/tensorflow/python/ops`) - i only meant to point out where it gets generated to, not to suggest you should modify the contents of the tensorflow local code directories.

WRT the path, if you append your PYTHONPATH environment variable to include the full path to your
```
bazel-out/local-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow
```
then it should also find `op_def_pb2` because it should be sitting in
```
bazel-out/local-opt/bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/tensorflow/core/framework/op_def_pb2.py
```
Don't forget that if you redefine the environment variable, but still continue to use sudo, you'll need to use `sudo -E ...` to pass along the environment variables.

**Comment by sarah-zaheer** [comment]
Alright, no sudo from now on. :-)
I'm very sorry if I forgot to mention that I did the pip part already. (followed all the instructions at [https://www.tensorflow.org/install/install_sources](url) including pip installing the .whl file.)

**Comment by quaeler** [comment]
Ah ok - if you pip installed the whl created by the methods described on that page, then switch to the virtualenv or conda environment into which you installed it, unless you installed it into the system using `sudo pip ...`.

Then, make sure you change directories out of the tensorflow source root, as this has been reported by some people to end up with Python trying to import from the source tree; at that point, the Python script should be able to find all imports without problem.

That still isn't finding the imports, lemme know what commit of master or branch you pulled your source from.

**Comment by sarah-zaheer** [comment]
**After appending my PYTHONPATH environment variable like you suggested, (and no sudo)**

Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 77, in <module>
    import tensorflow as tf
  File "/home/sarah/tensorflow/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/sarah/tensorflow/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/sarah/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/sarah/tensorflow/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
ImportError: No module named pywrap_tensorflow_internal


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Found this on Stack Overflow:** 
[https://stackoverflow.com/questions/44768751/import-tensorflow-error-for-ubuntu-16-04-importerror-no-module-named-pywrap-te](url)

the suggestion there is to uninstall tensorflow, which I dont think so! because it took 6+ hours to build tensorflow from source.

**Comment by quaeler** [comment]
The PYTHONPATH suggestion was a "if you don't install via pip, then you can have Python reference the built contents which would otherwise go in to the pip install by setting your PYTHONPATH to look at the bazel output directories."

Since you installed from pip, don't alter the PYTHONPATH, and make sure your current working directory is not your local tensorflow repository directory when you run python.

**Comment by sarah-zaheer** [comment]
Yes I did install using sudo pip..
(which commit? I dont understand)

I cloned tensorflow into my home directory so now running 
_python tensorflow/tensorflow/examples/speech_commands/train.py_
from my home directory and still getting this error message
(Previously I was running from within the tensorflow root directory)

ImportError: cannot import name audio_ops

**Comment by quaeler** [comment]
You don't want to invoke Python on tensorflow-dependent code from **any** directory that is at the head of the tensorflow repository code - whether that be where you git-cloned to, or whether you made a duplicate elsewhere.

Maybe the best way is for you to repeat my attempt at this; i've done the following after last pulling my local repository from master around 100 minutes ago:
```
autogenic:tensorflow loki$ bazel clean
autogenic:tensorflow loki$ ./configure 
autogenic:tensorflow loki$ bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package
autogenic:tensorflow loki$ bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
autogenic:tensorflow loki$ cd ~/arbeit/virtualenvs
autogenic:virtualenvs loki$ virtualenv --system-site-packages tensorflow_20170902
autogenic:virtualenvs loki$ source tensorflow_20170902/bin/activate
(tensorflow_20170902) autogenic:virtualenvs loki$ cd tensorflow_20170902/
(tensorflow_20170902) autogenic:tensorflow_20170902 loki$ mkdir sarah-zaheer
(tensorflow_20170902) autogenic:tensorflow_20170902 loki$ cd sarah-zaheer
(tensorflow_20170902) autogenic:sarah-zaheer loki$ python ~/arbeit/worg/projects/tensorflow/tensorflow/examples/speech_commands/train.py 
>> Downloading speech_commands_v0.01.tar.gz 100.0%
INFO:tensorflow:Successfully downloaded speech_commands_v0.01.tar.gz (1488293908 bytes)
WARNING:tensorflow:From /Users/loki/arbeit/worg/projects/tensorflow/tensorflow/examples/speech_commands/train.py:161: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Training from step: 1 
INFO:tensorflow:Step #1: rate 0.001000, accuracy 6.0%, cross entropy 2.673610
INFO:tensorflow:Step #2: rate 0.001000, accuracy 7.0%, cross entropy 2.632296
INFO:tensorflow:Step #3: rate 0.001000, accuracy 11.0%, cross entropy 2.587655
INFO:tensorflow:Step #4: rate 0.001000, accuracy 10.0%, cross entropy 2.540978
INFO:tensorflow:Step #5: rate 0.001000, accuracy 14.0%, cross entropy 2.560040
INFO:tensorflow:Step #6: rate 0.001000, accuracy 11.0%, cross entropy 2.539041
INFO:tensorflow:Step #7: rate 0.001000, accuracy 4.0%, cross entropy 2.655353
INFO:tensorflow:Step #8: rate 0.001000, accuracy 9.0%, cross entropy 2.609798
...
```

The take-away point i'd make in a super-preachy sort of way would be:
* never, ever, (like Chris Rock "never-ever") pip install this stuff into your system Python install (unless you're running throw away docker-and-its-ilk-like images); once done, you've got some transient version of tensorflow stuck in your system and you pray that pip uninstall manages to wipe it all away correctly

and its corollary:
* use a virtualenv for this sort of stuff; if i end up installing the worst buggiest snapshot of tensorflow, i just delete that environment directory (`tensorflow_20170902` in the above example) from my filesystem and i'm back to pure-as-the-driven-snow.

Lemme know how the above works.

PS. Do try to do a `sudo pip uninstall ...` of tensorflow before doing anything else. If you don't, the above virtualenv creation command will copy the system's tensorflow install into your virtualenv and many continued problems and hilarities will ensure.

**Comment by sarah-zaheer** [comment]
Thank you very much for helping me out so much. I'm working on it like you have suggested. Let's see what happens :)

**Comment by serendipity24** [comment]
I have had similar issue as seen below:

"(tensorflow)*usrname*@*usrname*:~/tensorflow/tensorflow-0$ python tensorflow/examples/speech_commands/train.py
Traceback (most recent call last):
  File "tensorflow/examples/speech_commands/train.py", line 79, in <module>
    import input_data
  File "/home/cogknit/tensorflow/tensorflow-0/tensorflow/examples/speech_commands/input_data.py", line 35, in <module>
    from tensorflow.contrib.framework.python.ops import audio_ops as contrib_audio
ImportError: cannot import name audio_ops_"

But I am sorry I am not able to follow your suggestions due to my own lack of understanding of the software based lingo.To begin with, how to go into the autogenic:tensorflow mode as you suggested above in your most recent reply.
Is that the solution that I should implement when I have installed tensorflow through virtualenv and it uses python 2.7 ?
Thanks ahead.

**Comment by quaeler** [comment]
Yes, create a virutalenv, then switch to that virtualenv ("activate" that virtualenv) and [pip-install tensorflow into that virtualenv.](https://www.tensorflow.org/install/install_linux#installing_with_virtualenv)

From a directory **that is not in the tensorflow source tree** and while still in the virtualenv, run the example Python script.

**Comment by serendipity24** [comment]
As suggested by you I pip installed the tensorflow within a virtualenv (on Ubuntu 14.04 ,followed the steps in the following link :https://github.com/ravivalluri/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#import-error)
I am attaching the trailing end of the installation : 
".
 .
    x86_64-linux-gnu-gcc: numpy/random/mtrand/distributions.c
    x86_64-linux-gnu-gcc: numpy/random/mtrand/mtrand.c
    x86_64-linux-gnu-gcc: numpy/random/mtrand/initarray.c
    x86_64-linux-gnu-gcc: numpy/random/mtrand/randomkit.c
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/numpy/random/mtrand/mtrand.o build/temp.linux-x86_64-2.7/numpy/random/mtrand/randomkit.o build/temp.linux-x86_64-2.7/numpy/random/mtrand/initarray.o build/temp.linux-x86_64-2.7/numpy/random/mtrand/distributions.o -Lbuild/temp.linux-x86_64-2.7 -o build/lib.linux-x86_64-2.7/numpy/random/mtrand.so
    Creating build/scripts.linux-x86_64-2.7/f2py
      adding 'build/scripts.linux-x86_64-2.7/f2py' to scripts
    changing mode of build/scripts.linux-x86_64-2.7/f2py from 664 to 775
    
    warning: no previously-included files matching '*.pyo' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    changing mode of /home/cogknit/tensorflow/bin/f2py to 775
  Found existing installation: setuptools 2.2
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed tensorflow protobuf wheel mock numpy setuptools funcsigs pbr
Cleaning up...
"

I then run the python script as follows : 
(tensorflow)cogknit@cogknit:~$ python /home/cogknit/tensorflow/tensorflow/examples/speech_commands/train.py 

I am sorry but I am still getting the same error.Can you please tell me what am I doing wrong here?Also can you please elaborate on what you mean by "a directory that is not in the tensorflow source tree" if that's where the error is?

Thank You

**Comment by quaeler** [comment]
I'm not familiar with the instructions in the link you provided, and see nothing in the section of installation that you chose to include that is alarming. So from those things, i can't tell why it's not working for you.

Since this issue is closed, no other users are likely to chime in their help; you might have more luck using Stack Overflow for this sort of issue since it's not really a bug in TF.

**Comment by serendipity24** [comment]
Okay...Your suggestions gave me the necessary clarity nonetheless.Thank you very much :)
