### ISSUE TITLE
Run Retrained inception model

### ISSUE THREAD

**Issue by ashishagni5** [tensorflow/tensorflow#12728]
I have trained tensorflow inception v3 model with new data sets. (on ubuntu)
I got output_graph.pb and output_labels.txt files in tmp folder.
When I tried to run as below 

python label_image.py --image /home/ubuntu/140924_HDR3DSC_0092_ISO00050_SS1250.JPG --graph /tmp/output_graph.pb --labels /tmp/output_labels.txt

I got below errors

  File "label_image.py", line 121, in <module>
    input_operation = graph.get_operation_by_name(input_name);
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2836, in get_operation_by_name
    return self.as_graph_element(name, allow_tensor=False, allow_operation=True)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2708, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2768, in _as_graph_element_locked
    "graph." % repr(name))
KeyError: "The name 'import/input' refers to an Operation not in the graph."

Please suggest me what to do to resolve this.
Please suggest me if anything wrong from my end.

**Comment by CaffGeek** [comment]
I'm getting the same thing

**Comment by astewartau** [comment]
I am having this issue as well.

**Comment by michaelisard** [comment]
This looks like the same as #12736 which has a workaround in the comments.

**Comment by ashishagni5** [comment]
Thank you all for your quick responce
I could able to resolve the problem by changing the script path and run.

/tensorflow/bin/examples/image_retraining$ python label_image.py --image /home/ubuntu/index.jpeg --graph /tmp/output_graph.pb --labels /tmp/output_labels.txt --output_layer=final_result:0

Earlier script path was "/home/ubuntu/tensorflow/bin/examples/label_image" where I was getting mentioned error

**Comment by nitish11** [comment]
@ashishagni5 : Is this issue got resolved, if yes, why is this still open?

**Comment by ashishagni5** [comment]
@nitish11 forgot to close. done now

**Comment by aureosun** [comment]
@ashishagni5 
 Have you ever run the code label_image.py in tensorflow/tensorflow/examples/label_image/label_image.py
I have modify it to run on a dataset and read and calssify image one by one,and as the number of images goes,the speed is slower and slower,at first,that's about ten images per second,and when the number of image goes to 1000,the time is about 7s,Incredibly!and I find the problem is in the function read_tensor_from_image_file in label_image.py and this part is read and preprocess images, so what's the matter?and I want to know how to speed up?and how to modify the code so as to making it run for batches ?
