### ISSUE TITLE
GPU support on Mac OS X? compile by oneself?

### ISSUE THREAD

**Issue by cxwx** [tensorflow/tensorflow#12770]
I'm 纠结 to select ubuntu or Hackintosh as my PC.

Note: As of version 1.2, TensorFlow no longer provides GPU support on Mac OS X.

Could anyone tell the reason?

Could I compile tensorflow with gpu[cuda] support by myself? Why or Why not?

**Comment by gunan** [comment]
The reason is Apple has not released a Mac with an NVIDIA GPU since 2014. We tested with external boxes, but there were too many issues around the drivers and software TF depended on.
Therefore, we decided to drop support for GPUs on MacOS.

You may still be able to compile on MacOS with GPU support. But we do not know if it works, what needs to fix the issues you may face. You wont have the official support from TensorFlow development team when trying to use GPUs on MacOS.

**Comment by mrTsjolder** [comment]
@gunan Would [this](https://developer.apple.com/development-kit/external-graphics/) be a reason to pick up support again?

**Comment by gunan** [comment]
It is offered with an AMD GPU, so no.

**Comment by zsfarkas** [comment]
😢
