### ISSUE TITLE
Halted-partial dataset download for speech_commands example renders example ~broken

### ISSUE THREAD

**Issue by quaeler** [tensorflow/tensorflow#12773]
If a user attempts to run `tensorflow/examples/speech_commands/train.py` for the first time against a new `data_dir` location and then halts the execution of Python before the download can finish, subsequent attempts to run the script using the same data_dir specification (or lack of specification) will result in Python exiting in error with the gzip libraries complaining about incorrect CRC value.

This is because `AudioProcessor.maybe_download_and_extract_dataset(...)` in `tensorflow/examples/speech_commands/input_data.py` only downloads if the file doesn't already exist (sensibly) and assumes that `tarfile.open(...).extractall(...)` will complete error-free (less sensibly) - which it won't on the partially downloaded gzipped-tar asset. 

This probably merits a documentation inclusion as opposed to a code re-write since it's example code, but that decision is above my pay-grade.

**Comment by facaiy** [comment]
In my opinion, the exception about incorrect CRC value is sufficient clear for user.

**Comment by jart** [comment]
@facaiy I agree. It seems the except clause of maybe_download_and_extract_dataset does print the URL and the directory, in case the user wants to manually run wget or simply rm the file and try again. Although it might not be super noticeable since it appears to be a log and throw.

This might be worth worrying about if it was production code. For example, I worked on Bazel's downloader. We went to indescribable lengths to make it download files in the most reliable, secure, redundant, and high performance manner possible. But I think a little bit of imprecision makes sense here, to keep the example code simple, and make it easier for some of our users who have to do the download in a more manual way.

Thank you for the report.
