### ISSUE TITLE
allocate output tensor for every operation before the first inference

### ISSUE THREAD

**Issue by jiazhe0909** [tensorflow/tensorflow#12898]
### Describe the problem
I was wondering if it's possible to allocate memory in advance, for internal output tensors of every operation in my inference workload. 
I notice TF will automatically allocate (and de-allocate) memory for every internal result in a graph. If my inference workload repeats many times, all these allocations/deallocations will also repeat. Why don't we allocate these internal output tensors just once before the first inference run, and delete them after the last?

For example, I have the following workload (which will run thousands of times):
```
    M = tf.MatMul(A, B)
    D = tf.MatMul(M, C)
````
Is it possible to allocate M before the first run and use the memory for all inference? To avoid allocation of M in every single inference?

**Comment by yaroslavvb** [comment]
Similar thing is already being done with TensorFlow's caching allocator already. You may see __LOG_MEMORY__ messages suggesting memory allocations, but those allocations are near instantaneous when they reuse memory that tensorflow allocated earlier

**Comment by jiazhe0909** [comment]
Thanks for your reply, yaroslavvb.

If I understand correctly, (GPU)BFCAllocator does the caching stuff as you mentioned. And I do notice the same internal output tensors from different inference runs share the same "true ptr" addresses. 

However, when I changed code in "framework/op_kernel.cc" file, and timed the processes of "allocate output", I found these processes still cost 18-20 usec, which seems too long for me because the calculating time of my ops is only 30~50 usec on average.

```
2017-09-11 04:19:11.107759: I tensorflow/core/framework/op_kernel.cc:592] My log :: Start allocate output tensor
2017-09-11 04:19:11.107772: I tensorflow/core/framework/log_memory.cc:35] __LOG_MEMORY__ MemoryLogTensorAllocation { step_id: 10 kernel_name: "MatMul" tensor { dtype: DT_FLOAT shape {} allocation_description {allocator_name: "GPU_0_bfc" } }
2017-09-11 04:19:11.107778: I tensorflow/core/framework/op_kernel.cc:608] My log :: complete allocate output tensor
```

I was wondering if it's possible to keep the internal output tensors explicitly, thus I can walk around the process of output allocating.

**Comment by yaroslavvb** [comment]
Hm 20 usec on cached allocation on GPU would be quite terrible. You can have 10's of thousands of temporary allocations during running of a large network, so that could mean half a second of overhead in session.run purely due to tensor allocation calls. 

I do wonder if this 20 usec delay between your print messages is an actual bottleneck that can be eliminated, or if its a side effect of things running asynchronously. cc @zheng-xq cc @reedwm

**Comment by reedwm** [comment]
Since GPU allocations are run on the CPU during the OpKernel::Compute() call, they run in parallel with actual GPU computations, so reducing this allocation probably won't improve performance by much.

Still, reducing allocation times always helps, especially when a GPU is not available. @zheng-xq, any thoughts?

**Comment by yaroslavvb** [comment]
As a general comment -- it's preferable to to optimize existing allocators to be as fast as "manual preallocation" rather than give users a way to preallocate output tensor. This should be feasible in situation like yours where you run the same op thousands of times.
 
As an example of what "preallocating" does to code, here's an example of l-BFGS in [Torch](https://github.com/torch/optim/blob/master/lbfgs.lua), search for lines with "table" -- all that logic just complicates the code

**Comment by jiazhe0909** [comment]
Thanks for your replies, yaroslavvb and reedwm.
If the allocator really takes 10s of usec, I guess the output-allocation process could still be a bottleneck even in GPU inference workload. 
For example, we can consider a case that CPU side allocating process doesn't overlap with the previous launched GPU calculation.
![20170912_120218](https://user-images.githubusercontent.com/8175586/30308136-ba738734-9772-11e7-95f7-909b113cb66d.jpg)
I guess this could happen in inference (or training with small batch size) scenarios.

**Comment by yaroslavvb** [comment]
So I've talked to @zheng-xq who leads performance group and he said that they have ran experiments on real world networks and found that this delay was not a bottleneck. It was still not a delay when they artificially made this part 50% slower by adding sleep.

**Comment by reedwm** [comment]
@jiazhe0909 I am going to close this issue because as @yaroslavvb stated, the delay is currently not a bottleneck. As your diagram indicates, as GPUs get faster and the "Compute for Op1" box gets smaller, this could become a bottleneck in the future, but the solution will probably be to improve the allocator. Static allocation uses significantly more memory.

As you stated, for inference (or training) with small batches sizes, it is more likely the GPU compute time will be small relative to the CPU time, and the  increased memory usage from static allocation would not be a significant problem due to the small batch size. But as @yaroslavvb, this would complicate the code and take a lot of work. If this becomes a serious problem in the future, we can revisit this issue.
