### ISSUE TITLE
T-SNE Suddenly Not Working in Projector

### ISSUE THREAD

**Issue by HarryBaker** [tensorflow/tensorflow#12912]
Hello,

I'm sorry this isn't a technical question, but just this week I've noticed that T-SNE in the tensorboard projector is no longer clustering data properly. I am running the same vectors I did a few weeks ago, with the same perplexity. While before I saw distinct clusters, now the points are all forming an indistinct ball. Has anyone else noticed this?

**Comment by dandelionmane** [comment]
Hi HarryBaker,

Without a reproduction, this will be very hard to dig into. I recommend installing an older version of TensorFlow, and seeing if you can demonstrate that this is actually a bug in the TensorBoard projector. Since T-SNE is stochastic, you may have just gotten lucky the first time, or something else in the environment may have changed. 

Also, this issue should be filed against http://github.com/tensorflow/tensorboard rather than TensorFlow, since TensorBoard is its own project now. Please file there once you have a repro :)

**Comment by HarryBaker** [comment]
Ok, thanks for the link. You should redo the link on the projector page, since it goes to this repo.
