### ISSUE TITLE
Messy graph edges

### ISSUE THREAD

**Issue by MikalaiDrabovich** [tensorflow/tensorflow#1291]
### Steps to reproduce
1. python tensorflow/examples/tutorials/mnist/mnist_with_summaries.py
2. python tensorflow/tensorboard/tensorboard.py --logdir=/tmp/mnist_logs
3. Expand 'xent' node: edge from 'y-input' to 'mul' ops has an S-like shape instead of a more appropriate  C-like.
   See the image below:

![screen shot 2016-02-25 at 2 37 18 pm](https://cloud.githubusercontent.com/assets/953399/13337087/731d612c-dbce-11e5-919a-f07ca9da6a2a.png)

**Comment by danmane** [comment]
@chihuahua PTAL

**Comment by chihuahua** [comment]
I lack a solution ATM since the graph visualizer basically defers to dagre-d3 for graph layout. dagre-d3 treats graph layout as an optimization problem that trades off speed vs a quality layout. See https://github.com/cpettitt/dagre/wiki#recommended-reading for specifics.

In this case, it is odd how the arrow from y-input to the overall scope node is curved (and not a beeline for the node). Maybe we're somehow compelling the arrow's head to land on the left side.

**Comment by drpngx** [comment]
The code has changed substantially since the issue has opened. Feel free to open a new github issue if the problem still persists in recent versions.
