### ISSUE TITLE
No proper documentation to use transfer learning using pretrained model in .ckpt format

### ISSUE THREAD

**Issue by vishalghor** [tensorflow/tensorflow#12944]
Hi all,

Tensorflow had provided a retrain sample  code for inception v3 pretrained model to apply transfer learning usinng .pb file of the model.

But there is  no documentation on how  to use a .ckpt file for pretrained  models on Imagenet such as  Resnet,inception_resnet, etc.

Not much information of  how  to get a .pb file  for these pretrained model in .ckpt format.

Has anyone tried transfer learning on these models?
If yes, did they use .ckpt  or .pb  version oof the model?
How to get a .pb and how to perform transfer learning usinng .ckpt version ?

Please help me on the same.

thank and regards

**Comment by cy89** [comment]
It looks to me like @Bruczzz faced the same issue in #504, which you found and also commented on. It seems worth seeing if he can help you out.

**Comment by vishalghor** [comment]
Hi @cy89,

I think the issue is different from #504 as that refers to on tutorial to retrain inceptionv3 using .pb files. But as many models in tensorflow such as Resnet50 have only pretrained .ckpt instead of.pb. so it's a bit unclear on how to retrain such models the same way as suggested in #504

**Comment by aselle** [comment]
Can you use one of the slim based retrainings?
https://github.com/tensorflow/models/blob/master/slim/scripts/finetune_resnet_v1_50_on_flowers.sh

It appears to do resnet from resnet checkpoints. Slim provides all the python scripts that build the graph structure, so you can do retraining with just a .ckpt.

# As some background information: saved models come in several flavors

1. GraphDef (.pb) + ckpt  -- the graph structure is stored in the graph def, the ckpt contains the trained variable values separately. this is usually what you are producing when you are training new models

2. Frozen GraphDef (.pb) -- no ckpt is needed since all variables. This is what mobile TensorFlow and some serving applications used. This can be produced using freeze_graph.py.

3. Saved Model - this contains both checkpoints and graphdefs encapsulated in one unit.

4. ckpt - this is only the values of the variables. If this is all you have, you need to have the python code that generated the model graph, and then you could load this (which would replace the variable values in the python code iniialization with the trained values). 

This is explained in more detail here: https://www.tensorflow.org/extend/tool_developers/

**Comment by vishalghor** [comment]
hi @aselle ,

Thank you for the suggestion. hi reported some issue with models in slim in https://github.com/tensorflow/models/issues/2356

As I was not able to execute the finetune_resnet_v1_50.sh ,I reported for more clear documentation for transfer learning using .ckpt
The document for transfer learning using .ckpt will help a lot for using converted models from caffe or other framework where a .ckpt is generated.

Thanks and Regards

**Comment by aselle** [comment]
Closing this issue in favor of the models issue you created.
