### ISSUE TITLE
Ability to read multi-channel image format

### ISSUE THREAD

**Issue by edgimar** [tensorflow/tensorflow#12997]
Though the `tf.decode_image()` function can handle a few different image encodings, all of these encodings can only support a maximum of 4 channels in an image (RGBA).   One format which can support a larger number of channels is TIFF (which is currently not supported in TF, perhaps due to its complex specification?).  It would be convenient if TF could support decoding TIFF or some other format that is able to represent an arbitrary number of channels, `N` (which could be decoded into an `[H, W, N]` shaped tensor).

**Comment by reedwm** [comment]
Marking as contributions welcome if someone wants to implement this.

**Comment by facaiy** [comment]
Perhaps it is easier to use `mogrify -format jpg *.tif`

**Comment by edgimar** [comment]
@facaiy the whole point is to be able to have an image format that could, for example, represent 15 channels.  A single JPEG cannot do this.

**Comment by facaiy** [comment]
Hi, @edgimar .
I am not clear which one you need:
1. an solution to handle other image format,
2. or, a new parse ops `tf.decode_tiff` (`tf.decode_image` is just a wrapper outside) .

For the first one: In fact, `Tensor` supports arbitrary dimensions. So if TIFF or any format desired can be converted to array by Python, we are free to feed them into TensorFlow.

For the second one, perhaps the work will be difficult. And moreover, since most operators of `tf.image` seems designed for 3d / 4d nowadays, I don't know whether they are compatible if done.

Anyway, it is cool if someone wants to implement this.

**Comment by edgimar** [comment]
I'm looking for a parse op -- something that can be included as part of a TF graph.

**Comment by yongtang** [comment]
@edgimar TIFF has been added in [tensorflow/io](https://github.com/tensorflow/io). I will close this issue for now. Please take a look in [tensorflow/io](https://github.com/tensorflow/io) and let us know if there are any questions, and feel free to open issue there.
