### ISSUE TITLE
Add data dynamically to pre-exisiting contrib.data.dataset

### ISSUE THREAD

**Issue by alexgkendall** [tensorflow/tensorflow#13148]
(As far as I'm aware this isn't possible, so I think this is a feature request)

It would be great to be able to add data to a pre-exisiting dataset object, which already has an iterator attached. For example, in reinforcement learning, one often collects data while exploring, and needs to add this data to the training dataset. I can't see how using the `concatenate()` function is sufficient, as this returns a new dataset object and would require a new iterator etc.
@mrry 

Thanks!

**Comment by aselle** [comment]
@mrry, could you please evaluate this feature request. If it is a question of  it being possible already then perhaps it should belong on StackOverflow. I don't suppose you can use has-A inheritance to implement layered datasets?

**Comment by mrry** [comment]
What interface and semantics would you expect for a feature like this? To guide the discussion, I doubt it would make sense to make *all* datasets mutable, because this would inhibit optimization and lead us down a path similar to the queues. However, it could make sense to have some kind of mutable data *source*, and allow using datasets to transform and iterators to iterate over these. 

For example, today you can write code that creates a dataset from a queue, using this (slightly unintuitive) construction:

```python
q = tf.FIFOQueue(...)

# Create an infinite dummy dataset
dummy = Dataset.from_tensors(0).repeat(None)

# Create a dataset by dequeuing successive elements from `q`.
dataset = dummy.map(lambda _: q.dequeue())
```

You could also achieve something similar using the (new in 1.4) `Dataset.from_generator()` and a Python `queue` object.

If you used this functionality, would it satisfy your use case, or are there other things you'd like to see?

**Comment by alexgkendall** [comment]
Thanks - this would work. I guess for a cleaner API, I was imagining something like this:
```python
data = Dataset.from_tensor_slices((initial_features, initial_labels))

# get some new data and append this to the dataset
data.add_from_tensor_slices((new_features, new_labels))
```

**Comment by aselle** [comment]
@mrry, could you respond to the cleaner API improvement suggestion?

**Comment by mrry** [comment]
Since `data` in that example is a `tf.data.Dataset` object, an API like that would require some form of mutability in the `Dataset` class, which we are not going to support.

It might be possible to define some new type that supports (i) maintaining a dynamic set of elements, and (ii) creating a `Dataset` over that dynamic set of elements that has well-defined semantics (e.g. it could randomly sample from the current set of elements, or cycle through the elements in FIFO order).

**Comment by coderbhupendra** [comment]
@alexgkendall Did you get any better solution to above problem. I am working on Reinforcement learning. and try to apply RL on Gym atari game, where dataset keeps changing as I play. Basically, I store last 50000 game frames and then I select 32 frames randomly for training. But in the case of "tf.data.from_tensor_slices(myimagedataset)", myimagedataset keeps updating/changing on each step. so what could be a better approach to use dataset api.

**Comment by yongtang** [comment]
@coderbhupendra Are you looking for have a video input with frames coming in with FIFO buffering of 50000 frames (sliding window), and randomly select 32 out of the 50000 frames window?

**Comment by coderbhupendra** [comment]
@yongtang Yes you can think it in that way.

**Comment by yongtang** [comment]
In `tensorflow/io` you could read video files (needs FFmpeg library install) as a dataset. Then I think you could do some additional operations to achieve the effort you want. Maybe you could take a look and give it a try? 
Repo: https://github.com/tensorflow/io
Google Group: https://groups.google.com/a/tensorflow.org/forum/#!forum/io

**Comment by coderbhupendra** [comment]
@yongtang Thanks for helping me. But my dataset is not video. Its a game environment. My agent plays game and stores the frame (so its basically a 84*84 image). And I keep adding frames as I play and delete older frames from the buffer. So at each step I play I add a new frame and delete one old frame and randomly select 32 frames for training.  I hope I am not confusing you.

**Comment by yongtang** [comment]
@coderbhupendra Implementation wise that should be possible. Essentially it is a streaming data as input (with frames in). Internally, the class will keep a circular buffer (FIFO) to keep only 50000 frames and drops old frames as new frames in. Each batch will randomly select 32 frames from the circular buffer (of 50000) as the output.

As @mrry mentioned this is unlikely to be supported in `tf.data.Dataset` as it mutates.

But if the use case is generic enough I think we could consider adding it in `tensorflow/io`. Would you like to open an issue in https://github.com/tensorflow/io with more details? (Especially the input format you plan to take.)

**Comment by jperl** [comment]
I am collecting data during the training process and using `Dataset.from_tensor_slices` with placeholders and an initializable iterators to update the placeholders periodically with numpy arrays.

Initializable iterators are deprecated now, so what is the recommended pattern for dynamic numpy arrays. Should we switch to using a generator?
