### ISSUE TITLE
tf.contrib.data.Dataset outputs have only partial shape

### ISSUE THREAD

**Issue by qbilius** [tensorflow/tensorflow#13161]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04.2
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.6
- **Bazel version (if compiling from source)**: N/A
- **CUDA/cuDNN version**: 8.0 / 6
- **GPU model and memory**: Titan X 12GB
- **Exact command to reproduce**: see below

### Describe the problem

Dataset outputs should have the first shape dimension specified when dataset.batch is specified. Instead, "?" is given.

### Source code / logs

```python
import tensorflow as tf

dataset = tf.contrib.data.Dataset.range(100).map(lambda x: [x,x])
dataset = dataset.batch(32)
iterator = dataset.make_initializable_iterator()
inputs = iterator.get_next()
print(inputs.shape)
```

Output: ```(?, 2)```

Expected: ```(32, 2)```

**Comment by mrry** [comment]
This is intended behavior: if you evaluate `inputs` 4 times, you will notice that the shapes of the returned tensors are `(32, 2)`, `(32, 2)`, `(32, 2)`, and `(4, 2)`.

**Comment by Noahyt** [comment]
@mrry is there a way to prevent the dataset from producing the final batch which has incomplete batch size (in your example, the (4,2))?

**Comment by mrry** [comment]
Yes! In TF 1.4 (just RC'd yesterday) you can replace:

```python
dataset = dataset.batch(batch_size)
```

```python
dataset = dataset.apply(tf.contrib.data.batch_and_drop_remainder(batch_size))
```

**Comment by tomwesolowski** [comment]
I've been struggling with this problem.
I've put
`dataset = dataset.repeat()`
before
`dataset = dataset.batch(batch_size)`
and expected to see fully defined TensorShape.

**Comment by mrry** [comment]
@tomwesolowski Did you try the workaround I suggested in [my previous comment](https://github.com/tensorflow/tensorflow/issues/13161#issuecomment-336316164)?

**Comment by tomwesolowski** [comment]
@mrry Yes and it worked. But my question is if it's a intended behaviour?

**Comment by klydream** [comment]
@mrry I have struggle with this problem
first, when i deal with `dim = reshape.get_shape()[1].value
    weights = _variable_with_weight_decay('weights', shape=[dim, 384],
                                          stddev=0.04, wd=0.004)`

**Comment by cgarciae** [comment]
This is definitely confusing and was a headache to solve since I was getting an `Incompatible Shape` error consistently near step 1000 of training. Its worst since there is few documentation. 

I would suggest adding a kwarg like `drop_remainder = False` to the `batch` method that implements the solution suggested by @mrry.

**Comment by luketaverne** [comment]
Thank you to @mrry for the workaround! 

I would like to point out that this also affects the more dynamic model definitions (not just the last batches of training), for example when modifying the example `models/research/resnet/resnet_model.py` to use a `Dataset` instead of the queues, building the model will choke on the fully connected layer at [resnet_model.py#L290](https://github.com/tensorflow/models/blob/95385809e79369337e5431f3e778700a77dc93a9/research/resnet/resnet_model.py#L290).

**Comment by shantianyang** [comment]
Hi, "InvalidArgumentError: ConcatOp : Dimensions of inputs should match" , I meet the same problem, Did you have some solutions? thanks!!!

**Comment by chandanjc** [comment]
Thanks @mrry , I used the `drop_remainder=true` flag and it fixed this issue.
