### ISSUE TITLE
tf.get_variable() behavior somewhat inconsistent across reuse=True, reuse=None

### ISSUE THREAD

**Issue by ericjang** [tensorflow/tensorflow#1317]
By default, calling `tf.get_variable()` for a variable that does not exist yet creates that variable in the current scope, if the scope has `reuse=Nne`. However, if the scope has reuse=True, then  a Under-sharing error is raised.

```python
import tensorflow as tf
with tf.variable_scope("scope1",reuse=None):
  x=tf.get_variable("x", [1,1]) # this works
with tf.variable_scope("rnnscope",reuse=True):
  w=tf.get_variable("w",[1,1]) # this fails
ValueError: Under-sharing: Variable rnnscope/w does not exist, disallowed. Did you mean to set reuse=None in VarScope?
```

I think I understand the motivation behind this behavior - variables retrieved in a reuse=True scope should be in "reuse-mode", so an error should be raised if it hasn't been created yet.

The way I get around this is a global variable DO_SHARE=None that is permanently set to True for all t > 0. 

An example implementation of building an RNN this way is here: https://github.com/ericjang/draw/blob/master/draw.py#L163

However, this seems a bit inelegant - wouldn't it be easier to just have `get_variable()` create nonexistent variables, regardless of the value of `reuse`? Perhaps there is a better way to build RNNs that I'm not aware of?

### Environment info
Operating System: **Debian**

If installed from binary pip package, provide:

1. Which pip package you installed.
**GPU-enabled wheel for Linux**
2. The output from python -c "import tensorflow; print(tensorflow.__version__)".
**0.6.0**

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).

**Comment by lukaszkaiser** [comment]
In some sense the reuse checks in tf.get_variable are indeed superfluous -- one could, as you say, just always create non-existent variables regardless of the reuse-check setting (and get rid of reuse).

When designing variable_scope we discussed this issue at length. The decision to enforce reuse-checks was motivated by a history of research model development. It happened a few times that people trained models that had more variables than they thought, exactly because these parameters were silently created in the way you suggest. The models still gave reasonable results, so the problem was hard to debug -- but the results with proper reuse were much better. Taking this into account we decided to enforce reuse checks quite strictly. But it's python -- it's easy to disable the checks if you want to, e.g., like this.

```
def unsafe_get_variable(name, ...):
  try tf.get_variable(name, ...)
  except _:
    with tf.variable_scope(tf.get_variable_scope(), reuse=True):
      tf.get_variable(name, ...)
```

But it's a dangerous road, the checks can save you some debugging later, so consider not disabling them.

**Comment by ericjang** [comment]
Thanks! I also just discovered that `make_template` [https://www.tensorflow.org/versions/r0.7/api_docs/python/state_ops.html#make_template](https://www.tensorflow.org/versions/r0.7/api_docs/python/state_ops.html#make_template) does the trick as well.
