### ISSUE TITLE
Cannot put a Tensor into a StagingArea

### ISSUE THREAD

**Issue by EFanZh** [tensorflow/tensorflow#13288]
TensorFlow version: 1.3.0

According to the document, I should be able to put a tensor to a StagingArea<sup>[[1]](https://www.tensorflow.org/api_docs/python/tf/contrib/staging/StagingArea#put)</sup>. But the following code does not work:

```python
import tensorflow as tf
from tensorflow.contrib import staging

staging.StagingArea(dtypes=[tf.int32]).put(tf.constant(1))
```

The output says:

```
Traceback (most recent call last):
  File "/███████/dataset.py", line 4, in <module>
    staging.StagingArea(dtypes=[tf.int32]).put(tf.constant(1))
  File "/███████/site-packages/tensorflow/python/ops/data_flow_ops.py", line 1671, in put
    vals, _ = self._check_put_dtypes(values, indices)
  File "/███████/site-packages/tensorflow/python/ops/data_flow_ops.py", line 1480, in _check_put_dtypes
    raise ValueError("Indices must be supplied when inserting a list "
ValueError: Indices must be supplied when inserting a list of tensors
```

**Comment by calledbymountains** [comment]
This question seems suitable for StackOverFlow.

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by EFanZh** [comment]
@asimshankar Maybe my description is not clear, but I was not asking a question. I am fairly sure this is a bug, because the code’s behavior is different than the documented behavior. I think either the implementation is wrong, or the documentation is wrong.

Consider the following two pieces of codes:

```python
import tensorflow as tf
from tensorflow.contrib import staging

staging.StagingArea(dtypes=[tf.int32]).put(tf.constant(1))
```

```python
import tensorflow as tf
from tensorflow.contrib import staging

staging.StagingArea(dtypes=[tf.int32]).put((tf.constant(1),))
```

The first one won’t work as I described, the second one works. If the documentation is correct, both ones should work.

**Comment by asimshankar** [comment]
I see. Indeed it seems the documentation is incorrect.

Possible fixes include:

- Updating the documentation in [this line](https://github.com/tensorflow/tensorflow/blob/3dbe216/tensorflow/python/ops/data_flow_ops.py#L1676) to something like `A tuple or list of Tensors. The number of elements must match the length of the list provided to the dtypes argument when creating the StagingArea`.
- Updating the code to allow for a single Tensor by changing [this line](https://github.com/tensorflow/tensorflow/blob/3dbe216/tensorflow/python/ops/data_flow_ops.py#L1690) so that `indices` ends up as `[0]` instead of `None` when the argument is an instance of `Tensor`

PRs to fix these are welcome!

FYI @ekelsen

**Comment by JackDanger** [comment]
Thank you for outlining how to address this, @asimshankar, and for making it accessible for my first contribution. I've created a PR here: #13502 and tested it locally.
