### ISSUE TITLE
Concatenate in alternate fashion two tensors

### ISSUE THREAD

**Issue by Matrix92** [tensorflow/tensorflow#13316]
Good Afternoon.
I'd like to concatenate two tensors of shape (None,16) in alternate fashion.
For example, with simple arrays, if the inputs are:
a=[[1,2,3],[1,2,3],...]
b=[[4,5,6],[4,5,6],...]
I want this output:
c=[[1,4,2,5,3,6],[1,4,2,5,3,6],...]
How can I do it? 
I can't loop on tensors because of unknown shape[0], zip function isn't supported for tensors (tensor object is not iterable).
Thank u all in advance

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

Hint: Some combination of `tf.stack, tf.reshape, and tf.transpose` should be able to do this.
