### ISSUE TITLE
gru_ops.py trying to load a .so file on windows

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/tensorflow#13311]
gru_ops.py is attempting to load an .so library on windows when using CPU version (vs GPU), is this the correct behavior? It fails in my case. 

LINE 33
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/rnn/python/ops/gru_ops.py

**Comment by poxvoculi** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by apiszcz** [comment]
The error was my setup, fixed, no issue.
Platform Windows 10/64. Install was from a .whl.
This item can be closed.
Thank you.
