### ISSUE TITLE
Dataset API does not pass dimensionality information when constructing graph.  [using official ResNet]

### ISSUE THREAD

**Issue by Noahyt** [tensorflow/tensorflow#13348]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: YES 
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Mac OSX 10.12.6
- **TensorFlow installed from (source or binary)**: 
- **TensorFlow version (use command below)**: 1.3.0
- **Python version**: 3.6.1 

### Describe the problem
When I try to combine the dataset API with the resnet architecture provided at tensorflow/models/official/resnet the graph cannot be constructed because the dimension of the input data is not passed to the model constructing function.  

### Source code / logs

Skeleton code:

```
with tf.Session() as sess:
    print("initialized")

    features_placeholder = tf.placeholder(prepared_x.dtype, prepared_x.shape)
    labels_placeholder = tf.placeholder(dtype=tf.float32, shape=prepared_t.shape)

    dataset = tf.contrib.data.Dataset.from_tensor_slices((features_placeholder, labels_placeholder))
    dataset = dataset.shuffle(buffer_size=10000)
    dataset = dataset.batch(batch_size)
    dataset = dataset.repeat(num_epoch)

    iterator = dataset.make_initializable_iterator()

    (next_x_test, next_t_test) = iterator.get_next()
    next_x_test = tf.to_float(next_x_test, name='ToFloat')


    sess.run(iterator.initializer, feed_dict={features_placeholder: prepared_x,
                                              labels_placeholder: prepared_t})


    print(next_x_test)
    print(next_t_test)

    model = resnet_v2(resnet_size=50, num_classes=num_bins)

    output = model(next_x_test,is_training=True)
```

The last line throws an error on compiling:
> ValueError: The last dimension of the inputs to Dense should be defined. Found None.

this makes reference back to the resent_v2 definition where the final layer is a dense layer.

It appears that the dataset API is not passing dimension information hence the final dense layer does not know how to construct itself.

**Comment by Noahyt** [comment]
Actually this feels like a more general problem ... I just ran into this again when trying to reshape a tensor fed by a dataset iterator.  In this case the code is roughly: 

```
train_dataset = Dataset.from_tensor_slices({"image": features_placeholder_train, "label": labels_placeholder_train})
  iterator = train_dataset.make_initializable_iterator()
  (next_x_test, next_y_test) = iterator.get_next()
y_mod = tf.reshape(next_x_test,[-1,x_dim,y_dim,depth])

```
 When running this, tensorflow throws
 
> ValueError: Dimension size must be evenly divisible by ___  but is 1 for 'reshape/Reshape' with input shapes: [], [4] and with input tensors computed as partial shapes: input[1] = [?,28,28,1].

**Comment by drpngx** [comment]
Sorry this fell through the cracks. @mrry WDYT?

**Comment by mrry** [comment]
@Noahyt What is the output of these `print()` statements?

```python
    print(next_x_test)
    print(next_t_test)
```

**Comment by rishabh135** [comment]
@mrry  I am also facing a similar issue when applying a dense layer just after using tf.layer.Flatten() , is there any workaround where we can use dense with some layer that is of the shape [batch_size , None] (None as the dimensions of the second shape argument keeps changing ) . I did go through your answer on stack overflow regarding the same question https://stackoverflow.com/questions/39947793/dimentions-of-layers-in-conv-net-tensorflow-valueerror-shape-of-a-new-variable but that does not seems to work in tf r1.4

**Comment by mrry** [comment]
@rishabh135 Can you provide enough information to reproduce the problem?

**Comment by rishabh135** [comment]
@mrry  yeah , I have a network of following kind : 
```
        h3 = conv1d(h2, s2, size=3, rate=2, scope="d_h3_conv")
        h3 = tf.layers.batch_normalization(h3)
        h3 = tf.nn.leaky_relu(h3)
        
        h4 = tf.contrib.layers.flatten(h3)
   
        #h5 = tf.layers.dense(h4,1, activation=None, name="d_h5_lin")
        h5 = tf.layers.dense(h4,1)
```

and it throws up the above error (ValueError: The last dimension of the inputs to Dense should be defined. Found None.) But as I am working on audio dataset , hence I have a variable amount of dimension depending upon the number of timesteps , instead of using flatten I even tried using  tf.reshape along with tf.get_shape to make it work but to no avail.

**Comment by mrry** [comment]
This is not an issue with the `tf.data` API: the `h4` tensor inherently has an unknown shape, because it depends on flattening a variable-size tensor. 

The problem here is that `tf.layers.dense()` infers the number of input units in the layer from the shape of the input (`h4` in this case), and therefore it requires the input to have a static number of columns. However, in your program the number of columns depends on the sequence length, which is variable. You can't use `tf.layers.dense()` in this case; you must instead use a layer type that accepts variable-sized input, such as an RNN or a convolution.

**Comment by rishabh135** [comment]
@mrry  thanks for that information , but I am wondering if I can't use the dynamic shape of the h4 tensor above using your answer from https://stackoverflow.com/questions/37096225/how-to-understand-static-shape-and-dynamic-shape-in-tensorflow  to run the tf.layers.dense() , isn't that possible ?

**Comment by mrry** [comment]
No, because you cannot use a dynamic shape to define a variable. The dense layer is a wrapper [around two variables](https://github.com/tensorflow/tensorflow/blob/e210cb140a60a74d5e9ce3bf9ebedb21b4910f1c/tensorflow/python/layers/core.py#L131), whose shape depends on the number of columns in the input. Intuitively, the runtime has to allocate some memory for the variable that is shared across multiple steps, and so we require the shape of that memory to be the same across multiple steps. This requirement is enforced by requiring a static shape.

**Comment by tilarids** [comment]
I have experienced the same problem when using one_hot_column. I will try to extract a trivial working example out of my code but here is an excerpt:

```python
# columns are defined like this:
vector = tf.contrib.layers.sparse_column_with_vocabulary_file(
      column_name="vector",
      vocabulary_file=vocab,
      vocab_size=vocab_size)
vector_weighted = tf.contrib.layers.weighted_sparse_column(
      sparse_id_column=vector,
      weight_column_name="vector_weights")
vector_one_hot = tf.contrib.layers.one_hot_column(vector_weighted)

# estimator is defined like this:
estimator = tf.contrib.learn.DNNRegressor(
    feature_columns=[vector_one_hot],
    hidden_units=[1024],
    optimizer=tf.train.AdagradOptimizer(learning_rate))
```

This fails with 
```
The last dimension of the inputs to `Dense` should be defined. Found `None`.
```

**Comment by mrry** [comment]
@tilarids That sounds like it might have a different cause, since it looks like there's enough static information there to infer the appropriate shape. Please open a new issue with a complete set of details, and somebody who works on `tf.layers` will take a look.

**Comment by Migdalin** [comment]
Was a new issue opened for this?  I'm receiving the same error following a call to Flatten().  If I run just the flatten through a session, I get a "result.shape" of (2, 4656).  No "none" is present.  But when I try to feed that same result into a Dense layer, I get the error ("the last dimension of the inputs to `Dense` should be defined. Found `None`).
