### ISSUE TITLE
Dynamic loading / freeing GPU devices

### ISSUE THREAD

**Issue by chhwang** [tensorflow/tensorflow#13354]
I wonder whether there are any on-going works or plans on dynamic loading / freeing GPUs.

What I mean by dynamic loading is a client-side feature <code>sess.load_device()</code> like below:

```python
# start with /gpu:0 only
os.environ['CUDA_VISIBLE_DEVICES'] = '0'
sess = tf.Session()
with tf.device('/gpu:0'):
  a = tf.constant(0.5)
sess.run(a)

# add new device /gpu:1
os.environ['CUDA_VISIBLE_DEVICES'] = '0,1'
sess.load_device('/gpu:1')
with tf.device('/gpu:1'):
  b = tf.constant(0.3)
sess.run(a + b)

# free device /gpu:0
sess.free_device('/gpu:0')
```

I'm trying to test whether I can run <code>BaseGPUDeviceFactory::CreateDevices()</code> after the session is created, but if there are any better ways, would you please give me some hints?

**Comment by yaroslavvb** [comment]
Freeing GPUs inside process seems tricky since memory allocator is global. You could have several sessions storing things on various gpus, you'd need to check that you aren't destroying some precious memory state when releasing the GPU.

You could move GPU management a level up -- launch TensorFlow worker processes that reserve  GPUs and then destroy those processes to release.

**Comment by asimshankar** [comment]
There are currently no plans for enabling dynamic unloading/loading of devices in a session.
