### ISSUE TITLE
[XLA] Failure in the OS/X xla/service tests: duplicate symbol

### ISSUE THREAD

**Issue by DavidNorman** [tensorflow/tensorflow#13357]
I am getting the following error when running the XLA service unit tests:

```
duplicate symbol __ZN3xla7PrintToEPKNS_14HloInstructionEPNSt3__113basic_ostreamIcNS3_11char_traitsIcEEEE in:
    bazel-out/local-opt/bin/tensorflow/compiler/xla/service/_objs/user_computation_test/tensorflow/compiler/xla/service/user_computation_test.o
    bazel-out/local-opt/bin/tensorflow/compiler/xla/service/libhlo_matchers.a(hlo_matchers.o)
```

Command line for running the tests is:

```
bazel test --test_env TF_CPP_MIN_VLOG_LEVEL=2 --test_size_filters=small,medium,large --config opt --verbose_failures --test_output=all --nocache_test_results tensorflow/compiler/xla/service/...
```

This is OS/X, head of the master branch, using bazel `0.5.4-homebrew`.

Is this a known issue at the moment?

**Comment by hawkinsp** [comment]
No, I think this a new bug. The fix is to move those two functions in hlo_matchers.h out of line --- currently they are defined in the header which causes a duplicate definition. I'll fix it but it will take a day or two to make it to Github.

(Apologies for the breakage. Sadly our Mac continuous build doesn't build XLA yet because of limited resources, and this linking problem doesn't show up on Linux.)
