### ISSUE TITLE
Remove frame_length restrictions in tf.contrib.signal.stft/inverse_stft.

### ISSUE THREAD

**Issue by edumotya** [tensorflow/tensorflow#13363]
So far tf.contrib.signal.stft() does not allow a larger fft_length than frame_length.
```
 raise ValueError('frame_length (%d) may not be larger than '
                       'fft_length (%d)' % (frame_length_static,
                                            fft_length_static))
```
 I think it is worth to allow this option by zero-padding the input frames, matching fft_length, since it is the usual proceeding that provides a smooth time-freq representation.

**Comment by rryan** [comment]
The error you're pointing at prevents frame_lengths that are larger than fft_length -- I think fft_length larger than frame_length works already (there are unit tests for that case).

In either case, I think we can remove that check now -- ever since https://github.com/tensorflow/tensorflow/commit/7b4c01794fbc2e6dc46e93a42416dd80929ce1e5, the FFT ops have supported padding/slicing to fft_length if their input isn't of the right size.

**Comment by rryan** [comment]
I have a patch out for review that removes this -- I should be able to get it in before the TF 1.4 cut on Tuesday. Thanks for the suggestion (keep em coming!).

**Comment by rryan** [comment]
My fix is checked in internally and will go live as soon as the internal<->github sync is done.
