### ISSUE TITLE
ERROR: Failed to import the TensorFlow module.

### ISSUE THREAD

**Issue by andrewjsiu** [tensorflow/tensorflow#13387]
I was trying to install tensorflow-gpu. Using the tensorflow self check, it says all the required DLLs are present, but I still have an import error. I get the same error if I try to import numpy. There seems to be an issue with my conda command as well. Any help is greatly appreciated to resolve this issue. Thanks!

PS C:\Users\andrew\Documents> python tensorflow_self_check.py
ERROR: Failed to import the TensorFlow module.

- Python version is 3.6.

- TensorFlow is installed at: C:\Users\andre\Anaconda3\lib\site-packages\tensorflow

- All required DLLs appear to be present. Please open an issue on the
  TensorFlow GitHub page: https://github.com/tensorflow/tensorflow/issues

PS C:\Users\andrew\Documents> conda create -n tensorflow_gpu python=3.6
usage: conda [-h]
             {keygen,sign,unsign,verify,unpack,install,install-scripts,convert,version,help}
             ...
conda: error: invalid choice: 'create' (choose from 'keygen', 'sign', 'unsign', 'verify', 'unpack', 'install', 'install-
scripts', 'convert', 'version', 'help')

**Comment by cy89** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by gunan** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.
