### ISSUE TITLE
Error Raised contradicting to the documentation

### ISSUE THREAD

**Issue by Sentient07** [tensorflow/tensorflow#13452]
Hi,

This [Line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/inspect_checkpoint.py#L35-L36) says the variable can be left empty, but when done raises this error, `TypeError: print_tensors_in_checkpoint_file() takes exactly 3 arguments (2 given)`

**Comment by asimshankar** [comment]
This seems more like a question on how to use Python than on TensorFlow. Since none of the arguments are optional, they all must be provided.

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

In particular, it will be helpful if you can provide details on what exactly you tried and what the full error trace is. From the little error text provided, it seems this is the Python interpreter saying that you did not provide all 3 arguments to the function. If you do not want to provide the `tensors` argument, indicate so by provided `None`, for example: `print_tensors_in_checkpoint_file(filename, None, False)`.

Hope that helps.
