### ISSUE TITLE
cannot create an object of the class tf.layers.Dense()

### ISSUE THREAD

**Issue by yifannie** [tensorflow/tensorflow#13467]
I want to create an object of the class tf.layers.Dense(), but don't want to do the feedforward step immediately (i.e. not tf.layers.dense(input, units)). Because I want to first declare these modules/layers in a class, and then to have several member functions apply1(x, y), apply2(x,y) to use these layers. But when I did in tensorflow tf.layers.Dense(units), it returned:

layer = tf.layers.Dense(100)
 AttributeError: 'module' object has no attribute 'Dense'

How can I fix that?
Thanks

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

(In particular, `tf.layers.Dense` is not an exported symbol in TensorFlow releases 1.3 and prior. The next release will have them or you need to build from source. Hope that helps)
