### ISSUE TITLE
Issues in training the model on macOS Sierra

### ISSUE THREAD

**Issue by EmanSaad11** [tensorflow/tensorflow#13468]
hello, 

i want to create a AI-chatbot using the tensorflow seq2seq model. So, when i try to train the model there are two issues that i want to ask about:

1- why i'm getting this WARNING 
`WARNING:tensorflow:From /Users/emansaad/Desktop/AI-chtabot/Victor/eng-victor/seq2seq_model.py:129 in __init__.: all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.`

2-the temperature of my MAC book pro (macOS Sierra) is getting very high and the fans are running to cool the device , is that normal?

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said:
- The warning comes from the fact that `seq2seq_model.py` is using a deprecated API call
- It is possible that the training process is exercising your CPU enough to make it hot and cause the fans to run
