### ISSUE TITLE
Feature request: segment_argmax

### ISSUE THREAD

**Issue by RanBenIzhak** [tensorflow/tensorflow#13460]
Currently trying to return argmax from a tensor for selected slices (segments)
slices do not have the same length, so reshaping can't be used.
was looking for a function similar to tf.segment_max, only with indices as the return value.

for e.g
a = [1, 2, 3, 4, 5, 6]
seg = [0, 0, 0, 1, 1, 2]
tf.segment_argmax  return value will be
[2, 4, 5]

**Comment by tatatodd** [comment]
Contributions are welcome!

**Comment by shramesh** [comment]
I can try to implement this. 

Per the example by OP,  the segments are `[1,2,3], [4,5], [6]` and the segment_argmax function returns the indices of max element in each segment, but with a reference to the unsegmented list. 

Is my understanding correct ?

**Comment by RanBenIzhak** [comment]
yes, 
indices will be with reference to the unsegmented list.

my intention was to use these indices to slice the original tensor for all the max tensors

**Comment by GeorgyZhou** [comment]
I will go to work on this.

**Comment by damro** [comment]
Any update on this? I would also extend the feature request to support unsorted_segment_argmax, segment_argmax, unsorted_segment_argmin, and segment_argmin.

**Comment by patnaa2** [comment]
Would also like to throw my vote on this as a feature ; this would be super useful.

**Comment by damro** [comment]
How is this progressing?

**Comment by sushreebarsa** [comment]
Hi,
tf.segment_max returns the maximum values along segments, but you might need the corresponding indices using tf.where and tf.reduce_max.

Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow version with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the release notes to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
