### ISSUE TITLE
Float variable in loop not incremented properly

### ISSUE THREAD

**Issue by bernhardlutz** [tensorflow/tensorflow#13523]
Hi,

I am running the following code in tensorflow:

import tensorflow as tf

count = tf.get_variable("count", shape=(), dtype=tf.float32, trainable=False)
tf.assign(count, 0)
i = tf.get_variable("i", shape=(), dtype=tf.int32, trainable=False)
tf.assign(i, 0)

cond = lambda i, count: tf.less(i, 5)
body = lambda i, count: (tf.add(i,1), tf.add(count, 1))
i, count = tf.while_loop(cond, body, [i, count], shape_invariants=[tf.TensorShape(None), tf.TensorShape(None)])

init = tf.global_variables_initializer()

with tf.Session() as session:
    session.run(init)
    print("i", session.run(i), "count", session.run(count))

The expected result is that both, count and i have value 5. However, for count I get always different strange results like 6.18427 5.47266 5.81323

However, when I change the datatype of count to tf.int32, it works as expected.

Ubuntu 16.04 64 Bit
TF Version: v1.2.0-5-g435cdfc 1.2.1
Python 3.5.2

**Comment by mrry** [comment]
I think I see the source of confusion: those `tf.assign()` calls don't actually perform the assignment, but rather create an operation that you have to run in order to perform the assignment. See [this Stack Overflow answer](https://stackoverflow.com/a/34220750/3574081).

(The "different strange results" are due to the fact that the default initializer for [`tf.get_variable()`](https://www.tensorflow.org/api_docs/python/tf/get_variable) uses random values.)
