### ISSUE TITLE
tf.contrib.data.Dataset generated by slicing and dicing very large images

### ISSUE THREAD

**Issue by martin-gorner** [tensorflow/tensorflow#13532]
Hi
(writing here as requested by @mrry for further tf.contrib.data feature requests)

I would like to create a Dataset by cutting up and preprocessing very large images. I did this:

```
dataset = tf.contrib.data.Dataset.from_tensor_slices(tf.constant(img_filelist))
dataset = dataset.flat_map(load_cut_up_and_process)
```

This goes out of memory because my function load_cut_up_and_process creates too many pieces from one image, all in memory. If I try to make a function that returns fewer pieces for an image and then want to call it repeatedly on the same image to get more, how can I achieve that with Dataset, without replicating the huge image in memory? The only thing I can think of is:

```
dataset = tf.contrib.data.Dataset.from_tensor_slices(tf.constant(img_filelist))
dataset = dataset.flat_map(load_and_replicate_each_image) # Dataset is [im1, im1, im1, im2, im2, im2, im3, im3, im3, ...]
dataset = dataset.flat_map(cut_up_and_process_gently)
```

Now the second step goes out of memory because the implementation of load_and_replicate_each_image necessarily involves a tensor like [im, im, im] and multiple copies of the image will not fit. I also thought of this:

```
dataset = tf.contrib.data.Dataset.from_tensor_slices(tf.constant(img_filelist))
dataset = dataset.flat_map(replicate_each_filename) # Dataset is [imfname1, imfname1, imfname1, imfname2, imfname2, imfname2, imfname3, imfname3, imfname3, ...]
dataset = dataset.flat_map(load_cut_up_and_process_gently)
```

Which works, does not go out of memory, but now I am loading the same huge image multiple times in a row which is slow.

Any ideas ?

**Comment by mrry** [comment]
I don't think this is a bug or feature request... please post on Stack Overflow instead, providing more details of what's in the functions.

**Comment by martin-gorner** [comment]
Ok, the general question is: how do you generate a dataset from a list of very large images by cutting them up in pieces in a case when 1) you cannot load multiple very large images in memory at once and 2) the collection of pieces resulting from one image will not fit in memory either.

If the answer is "you cannot", then this is a feature request :-)

**Comment by yongtang** [comment]
@martin-gorner Not quite sure what you want to achieve but are you looking for a "partial read" of a file, so that only a chunk of the data records (off, len) is read into the memory?

In that case, I think it will very much depends on the underlying file format of the `img_filelist` and the implementation of the `load_cut_up_and_process_gently`.

It should always be possible with your own implementation. I do think you may get more help from StackOverflow.

**Comment by tatatodd** [comment]
Sorry @martin-gorner but I'm going to close this out.  We have limited resources in fielding github issues, so we really need to be strict wrt our "bugs+features in github, questions on StackOverflow" policy.

Here's the standard boilerplate:

This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
