### ISSUE TITLE
No OpKernel was registered to support Op 'Assign' running nightlypi stable build on raspberry pi 3

### ISSUE THREAD

**Issue by swb-tohear** [tensorflow/tensorflow#13652]
I am running the tensorflow backend to keras on a raspberry pi 3 with the lastest Stretch
The tensorflow 1.3 build is http://ci.tensorflow.org/view/Nightly/job/nightly-pi/lastStableBuild/

When running the Adam optimizer I'm seeing the following error:

tensorflow.python.framework.errors_impl.InvalidArgumentError: No OpKernel was registered to support Op 'Assign' with these attrs.  Registered devices: [CPU], Registered kernels:
  device='CPU'; T in [DT_FLOAT]
  device='CPU'; T in [DT_INT32]

         [[Node: Adam_2/iterations/Assign = Assign[T=DT_INT64, _class=["loc:@Adam_2/iterations"], use_locking=true, validate_shape=true](Adam_2/iterations, Adam_2/iterations/initial_value)]]

What can I do to solve this?

**Comment by tatatodd** [comment]
The error is trying to tell you that no kernel for int64 Assign is registered; only int32 and float are registered.

Digging into this a bit, I see that this is controlled by this block of macros for our Pi builds:
https://github.com/tensorflow/tensorflow/blob/3bafe0a86f67dd54197c6d60bdb5053f510de7d8/tensorflow/core/framework/register_types.h#L117

So you have two options:
1) Build tensorflow from sources yourself, including support for DT_INT64:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/pi/build_raspberry_pi.sh
2) Otherwise, you can find the code that's using int64, and change it to use int32 instead.

Hope that helps!

Note that technically this isn't a bug or feature request; in the future please ask these kinds of questions on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since there is a larger community that reads questions there. Thanks!
