### ISSUE TITLE
Failed to run TensorFlow inference with inputs:[image_tensor], outputs:[detection_boxes, detection_scores, detection_classes, num_detections]

### ISSUE THREAD

**Issue by vamshikhoslalabs** [tensorflow/tensorflow#13663]
Facing this issue when running TFDetect app. Even the app is crashing.
This issue i'm facing is when i'm running the example tensorflow android app.

**Comment by reedwm** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by vamshikhoslalabs** [comment]
@reedwm Hi Reed, I'm on Android 5.1.1 (OS : Mac, Architecture : None). The TensorFlow version i'm using is the 1.4.0-rc0. I have complied it form source.

**Comment by zubairbaqai** [comment]
I am also getting same error

**Comment by reedwm** [comment]
/CC @petewarden @andrewharp can you take a look?

**Comment by andrewharp** [comment]
@vamshikhoslalabs @zubairbaqai: can you please post a complete logcat from starting the app up until you see the error message? Do any of the other samples work?

I just tried the [official 1.4.0-rc0 APK](https://ci.tensorflow.org/view/Release/job/release-matrix-android/lastBuild/TF_BUILD_CONTAINER_TYPE=ANDROID_FULL,TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=NO_PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=cpu-slave/artifact/out/tensorflow_demo.apk) build, and it works fine for me.

**Comment by andrewharp** [comment]
Closing this as I'm assuming it had something to do with the temporary jcenter  issue we had where the wrong version of the TF AAR was downloaded. If it's still occurring please open a new issue with more details.
