### ISSUE TITLE
s390x support for google/nsync

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#13777]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: building from source
- **TensorFlow version (use command below)**: master 
- **Python version**:  Python 2.7.12
- **Bazel version (if compiling from source)**: 0.6.1
- **Exact command to reproduce**:  bazel build -c opt //tensorflow/tools/pip_package:build_pip_package

Tensorflow master build is failing on s390x platform with an error below: 
```
$ bazel build -c opt //tensorflow/tools/pip_package:build_pip_package
.................................................
ERROR: /home/test/.cache/bazel/_bazel_test/dece280ae0e9dc772a9ff752f1374540/external/nsync/BUILD:401:13: Configurable attribute "copts" doesn't match this configuration (would a default condition help?).
Conditions checked:
@nsync//:android_arm
@nsync//:android_arm64
@nsync//:android_armeabi
@nsync//:android_x86_32
@nsync//:android_x86_64
@nsync//:clang_macos_x86_64
@nsync//:gcc_linux_aarch64
@nsync//:gcc_linux_ppc64
@nsync//:gcc_linux_x86_64_1
@nsync//:gcc_linux_x86_64_2
@nsync//:ios_x86_64
@nsync//:msvc_windows_x86_64.
ERROR: Analysis of target '//tensorflow/tools/pip_package:build_pip_package' failed; build aborted.
```

Recently,  [google/nsync](https://github.com/google/nsync) is added to Tensorflow master as an [external dependency](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl).  
So, s390x support needs to be added to nsync module which includes code changes in BUILD file as well as adding source code in nsync package for s390x.   

We could create platform specific subdirectory inside [nysnc/builds](https://github.com/google/nsync) for s390x by executing  tools/mkmakefile.sh script. Also, could build nsync separately on s390x by executing command make depend test.
However, Tensorflow also uses code from platform-specific sub directories available inside  [nsync/platform/ ](https://github.com/google/nsync/tree/master/platform)  which has source code containing assembly instructions. 

Need information on how to generate similar code structure for s390x (we could see ppc, windows , arm etc platforms are supported).  
@gunan As we are not able to create an issue on nsync repository, could you please let me know whom to contact for this? 

Note: In Tensorflow, nsync dependency is added through [this ](https://github.com/tensorflow/tensorflow/commit/b48cfaea2aea3707a33e60c10385a87e37101b95)commit.

**Comment by gunan** [comment]
Hello @Nayana-ibm 
It looks like we just need to add a config option here for s390x:
https://github.com/google/nsync/blob/master/BUILD#L29
And add the necessary copts options for the architecture.
I confirmed with @m3bm3b that nsync, unlike boringssl is meant to be compatible and should work on s390x.

One detail is, We only accept changes to nsync internally.
If you can create a patch to support s390x, we can apply it internally and push the changes outside.

**Comment by Nayana-ibm** [comment]
Thanks @gunan for information. 
I have added support for s390x in nsync code : BUILD as well as bazel/BUILD.bazel files. PFA code patch. 

Apart from above changes, I guess we also need to create platform specific sub-directory inside `nysnc/builds` for s390x by executing `tools/mkmakefile.sh` script. 

With above changes, I could resolve an error :  `Configurable attribute "copts" doesn't match this configuration`  However Tensorflow build again failed at:

```
ERROR: missing input file '@nsync//:platform/s390x/cputype.h'.
ERROR: /home/test/tensorflow/tensorflow/tools/pip_package/BUILD:139:1: //tensorflow/tools/pip_package:build_pip_package: missing input file '@nsync//:platform/s390x/cputype.h'.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/test/tensorflow/tensorflow/tools/pip_package/BUILD:139:1 1 input file(s) do not exist.
```
Tensorflow uses nsync's platform-specific sub directories available inside `nsync/platform/` which has source code containing assembly instructions ( [cputype.h](https://github.com/google/nsync/blob/master/platform/x86_64/cputype.h) and [nsync_atm_<platform>.s](https://github.com/google/nsync/blob/master/platform/x86_64/src/nsync_atm_x86_64.s) ) 

The file `cputype.h` declares a flag` ATM_LD_IS_ACQ_ST_IS_REL_` . I'm not sure what should be the value (0 or 1) of this flag for s390x.  For now, I have set this flag value to 1 and with this change Tensorflow build succeeds. However, need to confirm on this. 

Also, need information on what assembly instructions are required for s390x from file `nsync_atm_<platform>.s` 
@gunan @m3bm3b Can you please check and let me know.

**Comment by m3bm3b** [comment]
My plan is to introduce a change to the bazel BUILD file that should make
nsync build with bazel
on linux s390x.

I believe ATM_LD_IS_ACQ_ST_IS_REL_ should be 1 for s390x.
When 1, this setting means
  "on this machine, all loads act as acquire loads, and all stores act as
release stores".
I believe that s390x is a sequentially consistent machine, and thus the
value should be 1.
If you believe that's not right please let me know.   (Incidentally,
it is _always_ safe to use the value 0 for this parameter on any machine.
To use 0 when the value could be 1 will merely cause extra memory
barriers to be inserted that will cause no harm, except to be slightly
slower
than necessary.   If you don't create this file, in a posix environment
nsync will automatically pick up platform/posix/cputype.h, which has the
value 0.)
I plan to create this file for s390x with the value 1 in an upcoming change.


It is usually not essential to create nsync_atm_<platform>.s for each new
machine type.
The library needs to get atomic operations from somewhere, but there are
several possibilities.
As well as assembly language, nsync may get atomic operations
from language-dependent libraries (it can from C++11 or C11),
compiler intrinsics (it can from gcc and clang),  or from
operating system dependent libraries (such as on MacOS, NetBSD, Win32).
When compiling TensorFlow, it's normal to use the C++11 atomic ops because
it's all in C++11.
Thus, assuming you have a complete C++11 implementation,
the compiler and its runtime will already provide the operations in a
TensorFlow build,
and handwritten assembly language is not needed in that case.
The assembly language is
needed typically when compiling with unusual or proprietary compilers in
C90,
often on uncommon operating systems (embedded systems, for example).

Mike

**Comment by Nayana-ibm** [comment]
Thanks @m3bm3b for detailed explanation. 
So, now to add support for s390x in nsync, the provident code patch and cputype.h file with the value 1 would be sufficient?

**Comment by m3bm3b** [comment]
I've just uploaded the change to github as branch v1.11,
change e14acb6027eca0d7eb5044d70bc9879acbedb727.
I'd be grateful if you could try it.   It updates the BUILD file (assuming
you're building with bazel),
and adds that header file.    I haven't added a makefile directory for it
because I was unable to test. (I tried repeatedly to get Debian up using
the Hercules emulator,
but every time I installed, the resulting system failed to boot, even
though the Debian install
had claimed the installation had succeeded.)

Beware that TensorFlow has not been updated to fetch the new version
of nsync automatically---it will still fetch the old one.  I will do that
update
to TensorFlow assuming all is well with the change to nsync.

**Comment by Nayana-ibm** [comment]
Yes...Will verify the nsync code on s390x with the commit id you have mentioned.
I guess I need to create a makefile directory also.   Earlier, I had used command make depend test. Is that sufficient?
Is there any specific command  to build nsync using basel build?
I'll also try building Tensorflow using above commit id (just by making change in workspace.bzl file of Tensorflow) on s390x using basel build command.

**Comment by m3bm3b** [comment]
Assuming you wish to build nsync as C++11
(which is what TensorFlow requires), at the root of the nsync tree do:
  cp -r builds/x86_64.linux.c++11 builds/s390x.linux.c++11
  cd builds/s390x.linux.c++11
  make depend test
This doesn't actually use the new header file because it's using C++11
atomics.

To try the new header file, do a C build, like this:
    mkdir builds/s390x.linux.old_gcc
    sed 's,x86_64,s390x,g' builds/x86_64.linux.old_gcc/Makefile >
builds/s390x.linux.old_gcc/Makefile
    touch builds/s390x.linux.old_gcc/dependfile
    cd builds/s390x.linux.old_gcc
    make depend test
This will build nsync as C (not C++11)
using "old-style" gcc atomics; that will use the header file.
(Old-style gcc atomics have compare and swap, but
don't include loads and stores, so those are
implemented with ordinary loads and stores, with extra memory barriers
as indicated by the flag in the new header.   The assumption here is
that the platform will perform loads and stores atomically if
they are 32-bits and naturally aligned.
New-style gcc atomics do include loads and stores, and so again wouldn't
really need
the header file.)

As you can tell, there are a distressingly large number of
options for getting atomic operations, because some platforms
implement some techniques, while others implement different ones.

**Comment by m3bm3b** [comment]
I forgot to say, there's nothing special needed to build nsync with bazel.
   bazel test :all
should work to build and test both with a C and a C++11 build.

**Comment by Nayana-ibm** [comment]
@m3bm3b I could build and verify nsync code on s390x platform as C++11 as well as C. 
(Using steps that you have mentioned in your previous comment)

As C++11:
```
cp -r builds/x86_64.linux.c++11 builds/s390x.linux.c++11 
cd builds/s390x.linux.c++11
make depend test 
```
As C:
```
mkdir builds/s390x.linux.old_gcc 
sed 's,x86_64,s390x,g' builds/x86_64.linux.old_gcc/Makefile > builds/s390x.linux.old_gcc/Makefile 
touch builds/s390x.linux.old_gcc/dependfile 
cd builds/s390x.linux.old_gcc 
make depend test 
```

Also, could verify using `bazel test :all` as well.

@gunan I could build Tensorflow master on s390x by updating Tensorflow workspace.bzl with nsync commit id as : e14acb6027eca0d7eb5044d70bc9879acbedb727. Should I go ahead and raise a PR for the same?

**Comment by m3bm3b** [comment]
I've made the equivalent change to TensorFlow's workspace.bzl
so it should now pick up the version of nsync that will work for you.
(The sha256 is different (839fcc53ff9be58218ed55397deb3f8376a1444e),
because I made another change to
nsync, unrelated to s390x support, but it includes the change you need.)

**Comment by Nayana-ibm** [comment]
@m3bm3b I couldn't see the changes done in TensorFlow's workspace.bzl file in TensorFlow master. 
The build is failing with same error on s390x. Am I missing anything here?

**Comment by m3bm3b** [comment]
Sorry.  I made the changes to an internal version that gets pushed to
github periodically.
I had forgotten that that process takes a while.

The diff is below.  It should appear on github within a day or so.
Sorry for the confusion.

==== //depot/google3/third_party/tensorflow/workspace.bzl#252 -
/google/src/files/173208878/depot/google3/third_party/tensorflow/workspace.bzl
====
432,433c432,433
<           "https://mirror.bazel.build/github.com/google/nsync/archive/ad722c76c6e6653f66be2e1f69521b7f7517da55.tar.gz",
<           # "https://github.com/google/nsync/archive/ad722c76c6e6653f66be2e1f69521b7f7517da55.tar.gz",
---
>           "https://mirror.bazel.build/github.com/google/nsync/archive/839fcc53ff9be58218ed55397deb3f8376a1444e.tar.gz",
>           # "https://github.com/google/nsync/archive/839fcc53ff9be58218ed55397deb3f8376a1444e.tar.gz",
435,436c435,436
<       sha256 =
"7dd8ca49319f77e8226cd020a9210a525f88ac26e7041c59c95418223a1cdf55",
<       strip_prefix = "nsync-ad722c76c6e6653f66be2e1f69521b7f7517da55",
---
>       sha256 = "124d105edb0313ef2d7f5bb86ec94d9f8de95479e55641c4254ffa8f795e9b37",
>       strip_prefix = "nsync-839fcc53ff9be58218ed55397deb3f8376a1444e",

**Comment by Nayana-ibm** [comment]
Thanks @m3bm3b

**Comment by m3bm3b** [comment]
I believe the change has now reached github.  You might check again.

**Comment by Nayana-ibm** [comment]
@m3bm3b Yes. Changes are now available in Tensorflow master.  I could build Tensorflow master successfully. Thank you for your help and fast response.
