### ISSUE TITLE
Channel number of convolution output is unspecified when atrous rate > 1 

### ISSUE THREAD

**Issue by vs-zhehangd** [tensorflow/tensorflow#13861]
Python 2.7
Tensorflow v1.2.0-rc2-21-g12f033d and v1.3.0-rc1-2361-gd1286ab

Easily reproduced by the following code:
``` Python
x = tf.placeholder(tf.float32, [1, 10, None, None])
w = tf.zeros([3, 3, 10, 20])
y = tf.nn.convolution(x, w, 'VALID', [1]*2, [2]*2, data_format='NCHW')
print(y)
```
The input has known channel number but unknown width and height, in NCHW format. The convolution has rate >= 2. The channel number of the output `y` is obviously known, `(1, 20, None, None)` in this example, depending on the shape of `w`. However the execution result gives 
```
Tensor("convolution/BatchToSpaceND:0", shape=(1, ?, ?, ?), dtype=float32)
```
I believe this is related to the reshaping operation in the atrous convolution. The issue happens only when the spatial shape is unknown and with NCHW format. Not sure if this happens to the latest version.

**Comment by facaiy** [comment]
It is reproduced on nightly version.

```python
In [1]: import tensorflow as tf

In [2]: tf.__version__
Out[2]: '1.5.0-dev20171019'

In [3]: %paste
x = tf.placeholder(tf.float32, [1, 10, None, None])
w = tf.zeros([3, 3, 10, 20])
y = tf.nn.convolution(x, w, 'VALID', [1]*2, [2]*2, data_format='NCHW')
print(y)

## -- End pasted text --
Tensor("convolution/BatchToSpaceND:0", shape=(1, ?, ?, ?), dtype=float32)
```

**Comment by facaiy** [comment]
The bug seems from here, since `[batch_to_space_nd](https://www.tensorflow.org/versions/master/api_docs/python/tf/batch_to_space_nd)` cannot handle the case correctly:

https://github.com/tensorflow/tensorflow/blob/d7409d32bba5ffa89141ec5427780f68a3b6942d/tensorflow/python/ops/nn_ops.py#L487-L495

**Comment by facaiy** [comment]
Since [`space_to_batch_nd`](https://www.tensorflow.org/versions/master/api_docs/python/tf/space_to_batch_nd) assumes that `input_shape = [batch] + spatial_shape + remaining_shape`, hence `paddings` is hacked as the tensor `[zeros, paddings]` to handle NC format. Since the value of tensor is hidden by itself, that's why we lost `num_input_channels` information in `space_to_batch_nd`.

https://github.com/tensorflow/tensorflow/blob/d7409d32bba5ffa89141ec5427780f68a3b6942d/tensorflow/python/ops/nn_ops.py#L485-L492

There are two solutions for the bug in my opinion:
1. use `reshape` to rewrite the correct `num_input_channels` at the last when `data_format is not None and data_format.startswith("NC") and not result_converted.shape[1].value`. Pretty easy. I can work on it if agreed.
2. modified `space_to_batch_nd` to handle `channle_at_the_first` case. Perhaps difficult.

Which one is better? Or other alternative solution? Thanks.

**Comment by vs-zhehangd** [comment]
For me, at application level I simply do
```
nout = ...
format = 'NCHW'
y = tf.nn.convolution(x, ..., data_format=format)
if format == 'NCHW':
    y.set_shape([None, nout, None, None])
```

**Comment by drpngx** [comment]
@ebrevdo WDYT? Should we encourage a contribution?

**Comment by ebrevdo** [comment]
The convolution function can call an appropriate set_shape in this special case.  Contributions welcome.

**Comment by facaiy** [comment]
Hi, @vs-zhehangd . I get a cold, would you like to take over the issue? The fix is pretty easy as you suggested, however, we'd better create a `nn_ops_test.py` and write more unit tests. It's not difficult, but perhaps a little cumbersome for new contributor. Thanks.

**Comment by vs-zhehangd** [comment]
Ok, let me take a look and see how to do it.

**Comment by ebrevdo** [comment]
There are conv unit tests in kernel_tests.

**Comment by facaiy** [comment]
@vs-zhehangd Hi, how's it going? Do you need help, or let me take it back?

**Comment by vs-zhehangd** [comment]
@facaiy  I found that I couldn't find a good time to deal with this problem. Probably it is better to return this to you. Sorry for the inconvenience.

**Comment by facaiy** [comment]
OK. Don't worry :-)
