### ISSUE TITLE
CNN gives core dumpped but for the same data LSTM is running successfully

### ISSUE THREAD

**Issue by vinayakumarr** [tensorflow/tensorflow#14057]
![screenshot from 2017-10-28 19-55-09](https://user-images.githubusercontent.com/18217467/32135309-517eaf52-bc1a-11e7-8f0a-cab3b3a03619.png)
![screenshot from 2017-10-28 19-54-17](https://user-images.githubusercontent.com/18217467/32135312-553fcfc2-bc1a-11e7-9e4f-4d4dedf992b9.png)

cuda 7.5 and cudann 5.0
tensorflow 0.10.0 and keras 1.2.0

LSTM program runs successfully. For CNN program, it is showing the below error. hHow to correct this?

**Comment by asimshankar** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

In particular, detailed instructions on reproducing the problem will be helpful.
