### ISSUE TITLE
Feature request: add tensor.<xyz> methods that redirect to tf.<xyz>(tensor,...)

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#14060]
Any TensorFlow API function func that takes `tensor` as a first argument could be implemented as `tensor.func(...)`. This is implemented in PyTorch/numpy and can make formulas more concise. Transpose is a frequent special case that deserves a shortcut like `T`.

cc @shoyer for numpy API wisdom

Compare:

Numpy:
```
b = a @ a.T
b.trace()
```

PyTorch:
```
b =  a @ a.t()
b.trace()
```

TensorFlow:
```
b = a @ tf.transpose(a)
tf.trace(b)
```

**Comment by shoyer** [comment]
This certainly convenient, but I'm not sure it was actually a good design choice for NumPy or would be for TensorFlow.

`numpy.ndarray` has 71 non-private attributes*:
T, all, any, argmax, argmin, argpartition, argsort, astype, base, byteswap, choose, clip, compress, conj, conjugate, copy, ctypes, cumprod, cumsum, data, diagonal, dot, dtype, dump, dumps, fill, flags, flat, flatten, getfield, imag, item, itemset, itemsize, max, mean, min, nbytes, ndim, newbyteorder, nonzero, partition, prod, ptp, put, ravel, real, repeat, reshape, resize, round, searchsorted, setfield, setflags, shape, size, sort, squeeze, std, strides, sum, swapaxes, take, tobytes, tofile, tolist, tostring, trace, transpose, var, view

There's no clear rule for what is a method vs. a function (most methods are also functions, but the converse is not always true). Only a fraction of these are actually widely used. Many of them are attractive nuisances with better alternatives elsewhere, but since we care about backwards compatibility the old methods are never removed. In practice, we no longer add new methods, for fear of making this list longer.

Purely from an organization point of view, having all these methods makes the internal dependency graph a complete mess. Basically everything ends up depending on everything else in a completely circular way.

In practice, I think more numeric type promotion (https://github.com/tensorflow/tensorflow/issues/8224) would make a bigger difference for readability of TensorFlow code. I see lots of codes littered with calls to `tf.constant` and `tf.cast` that should be totally unnecessary.

* Generated with `', '.join(entry for entry in dir(np.array(0)) if not entry.startswith('__'))`.

**Comment by yaroslavvb** [comment]
Fair enough, my main readability issue was with `tf.transpose` being too long, but one could also `def t(x): return tf.transpose(x)`
