### ISSUE TITLE
build with tensorflow_cc with cmake.

### ISSUE THREAD

**Issue by cxwx** [tensorflow/tensorflow#14157]
I found https://github.com/FloopCZ/tensorflow_cc/ 
as a good solution.
should somebody add it to official repository

**Comment by asimshankar** [comment]
That sounds wonderful and I hope the community finds it useful.

From what I understand, [`bazel` is used](https://github.com/FloopCZ/tensorflow_cc/blob/master/tensorflow_cc/cmake/build_tensorflow.sh#L41) to build `libtensorflow_cc.so`, and what's there packages that up with a set of header files.

Eventually, we would like to distribute the shared library and header files in a tarball that can be used by any build system, instead of having to maintain support for different build systems. We'd also like to tighten the API a bit, to reduce the number of internal header files that need to be exposed.

If anyone is interested in contributing to that, I'd suggest following along on #2412.
Thanks!

(FYI @skye)

**Comment by FloopCZ** [comment]
@asimshankar Yes, that is exactly what is done in there. However, it should be noted that if https://github.com/FloopCZ/tensorflow_cc/issues/8 is resolved (add support for CPack), you will be able to easily build a tarball, installers and even deb/rpm packages independent of the build system (FYI @skye).

**Comment by sathyamoorthyrr** [comment]
@FloopCZ Where should I place the **example** folder or its contents. From which location should I run those last commands(**3rd point under Usage**) in your [repository](https://github.com/FloopCZ/tensorflow_cc/) ?

**Comment by FloopCZ** [comment]
Lets continue at https://github.com/FloopCZ/tensorflow_cc/issues/112#issuecomment-461413277.
