### ISSUE TITLE
tfe.Network created inside variable_scopes

### ISSUE THREAD

**Issue by botev** [tensorflow/tensorflow#14164]
This is a feature request. 
Currently `tfe.Network` cannot be created under variable scopes. This is particularly useful to still have when composing very complicated models.

**Comment by jart** [comment]
@asimshankar Our friend is… eagerly awaiting your response to his feedback on tfe.Network + variable scopes.

**Comment by asimshankar** [comment]
FYI @alextp @allenlavoie @josh11b @agarwal-ashish 

Could you elaborate a bit on what you're trying and why :)? An example would help.
(I'm guessing you're filing this feature request because of [this exception](https://github.com/tensorflow/tensorflow/blob/d7cffe9/tensorflow/contrib/eager/python/network.py#L301))

We'd really like to understand your use case better before thinking about removing this restriction. Perhaps there is a more idiomatic alternative to structuring your examples that could be leveraged instead?

**Comment by botev** [comment]
So, I wanted to use a `tfe.Network` which defines, for instance, the Normalizing Flow of an Autoencoder. I have another network for the inference network. Now at this point, you can technically just have another net on top where these are part of, which I don't. Nevertheless, since I use the VAE inside an RL algorithm, that last bit is scoped, as so far in most code people and me included have used more of the functional interface. I understand that you can pretty much change any place where you used a scope to having a class, however, I was hoping that we can start the transition from using our old models to using `tfe.Network` without having to refactor 100% of our code. However, for that to happen we do need scopes to work otherwise the only option for changing is refactor everything is it just crashes. 

And yes that is the exception. I think this is useful for people trying to move into the suggested framework, but still have old code using scopes, which we don't want to recode all. Hope that gives some motive for removing the restriction. Could you maybe as well elaborate a bit more on why the restriction is there so we can try to understand what could be the issues of removing it?

**Comment by allenlavoie** [comment]
So it sounds like you'd be fine with variable scopes having no effect on Network variable naming, as long as they don't crash? (not a proposal, just a clarifying question)

The error is there because we'd like variables in a Network to have a name which matches the names of the Networks/Layers it belongs to, and it wasn't clear that adding special naming for when the Network is in a variable scope was worth it.

The likely approach is to keep the parent scope as part of the Network name. Anonymous networks (named/numbered based on their class name) would be numbered so that they're unique within the parent scope (rather than at the graph level). We'd strip off the parent scope prefix as part of the Network name when writing checkpoints, but shared layers would have their full scope prefix in the checkpoint (which might be a bit fragile).

**Comment by botev** [comment]
I think yes as long as they don't crash I if variable scopes have no affect at least at what I have in mind atm that would work. 

I can't say I'm a 100% sure which is the best solution, but I do think what you are saying - prefixing the name of the network by the parent scope - pretty much like the others to be a sound solution. This probably is fine even for anonymous networks to have it and is numbered.  For the checkpoints, I don't think many users would care either way as long as it provides consistent saving and loading of models.
