### ISSUE TITLE
Suggestion: Add Image Captioning Model Example for Android

### ISSUE THREAD

**Issue by pranay360** [tensorflow/tensorflow#14212]
This is a suggestion to add Android example for our deep-learning based tensorflow-android app which captions live camera frames in real-time.
https://github.com/neural-nuts/Cam2Caption

This app uses pre-trained model generated using 
https://github.com/neural-nuts/image-caption-generator

**Comment by jart** [comment]
If I understand correctly, you're asking us to merge your project into the TensorFlow codebase? Looking at the screenshots, what you built seems really cool. However merging it here might require a fair bit of build work, since .so and .jar files appear to be checked-in to that repo. While we appreciate contributions, we also love seeing TensorFlow benefiting the developers of other projects. I'm sure anyone searching will find, and benefit from, the work that you've shared.
