### ISSUE TITLE
what's is forget_bias? 

### ISSUE THREAD

**Issue by 404517981** [tensorflow/tensorflow#14223]
what's is forget_bias? I checked the basicllstmcell variable. but I found the biases are 0 althought I changed forget_bias to 0 or 1. I heard the func of it is that don't forget input of  first time .  please feedback

**Comment by asimshankar** [comment]
Please see the [documentation](https://www.tensorflow.org/api_docs/python/tf/contrib/rnn/BasicLSTMCell). It's a bias added to the forget gate described in the paper at http://arxiv.org/abs/1409.2329 

Hope that helps! Such questions are better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
