### ISSUE TITLE
Compilation progress indicator is useless

### ISSUE THREAD

**Issue by Timmmm** [tensorflow/tensorflow#14294]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS 10.12.6
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: `master` from around now
- **Python version**:  -
- **Bazel version (if compiling from source)**: 0.6.1
- **GCC/Compiler version (if compiling from source)**: Apple LLVM 9.0.0
- **CUDA/cuDNN version**: -
- **GPU model and memory**: -
- **Exact command to reproduce**: Any compilation, e.g. `bazel build //tensorflow/tools/pip_package:build_pip_package`

Whenever I compile Tensorflow, Bazel shows a nice progress indicator, for example:

    [1,428 / 1,437] Compiling tensorflow/core/kernels/cast_op_impl_int64.cc

However that progress proceeds something like this:

    [4 / 15]
    [20 / 26]
    ...
    [264 / 275]
    ...
    [1,821 / 1,832]
    ...
    [3,456 / 3,470]

Pretty useless. Compiling Tensorflow takes about 45 minutes on my system and it seems to want to do a complete recompile at the drop of a hat so it would be useful at least if I know whether I should wait for it or go and cook dinner. Is there anything that could be done to improve this?

**Comment by jart** [comment]
I agree it could be better. You can try filing a bug with the [Bazel project](https://github.com/bazelbuild/bazel), but this would be a tough nut to crack and I'm not sure how much help they would be able to provide.

The reason why that number grows over time is because Bazel starts building as it's traversing the build graph. It sort of discovers as it keeps going how much other stuff it needs to build. Each individual item could build quickly, like a .c file, or take a long time, like a complicated genrule. Whether or not they add time to build depends on whether or not they're in a critical path. So it would probably be very hard to predict the time it'll take.

However we know from experience that TensorFlow takes a long time to build. The main reason why that's the case is because we pass a lot of `-msystem` flags to the compiler which adds a `stat()` call for each `#include`, and C/C++ includes are quadratic. Those stat calls are at least half the compiler wall time IIRC. I've done some work in the past to remove `cc_library.includes` attributes wherever possible. In order to go further, I would probably need to do either:

1. Enhance Bazel's downloader to be able to regex transform C++ sources so includes can be relative to the repository root.
2. Break apart the `tensorflow/core/BUILD` targets, e.g. `lib_internal` into more fine-grained targets that depend on fewer third party libraries.

Both of which would require a big time investment.

Ideally, the C++ compiler would allow us to pass a file mapping includes to a specific location on disk, so we wouldn't need all these stat() calls. But compiler authors have never made this functionality available and I'm not sure why. Maybe it's because everyone is waiting for modules in C++20.

Either way, we appreciate the feedback and wish we could do more.

**Comment by pauldraper** [comment]
I don't think this particular issue was about a long build time so much as a lousy build indicator.

But yes, this is a Bazel problem.
