### ISSUE TITLE
sess.run hangs forever despite operation_timeout_in_ms being set

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#14489]
`sess.run` waits indefinitely on worker when one of the parameter server machines in the cluster fails despite `operation_timeout_in_ms` being set.

Because waiting happens inside TensorFlow runtime, there's no way for client to regain control to provide a helpful error message/fix the situation.

```
sess=tf.Session(config=...operation_timeout_in_ms=1000)  # succeeds even though TF cluster is partially dead
sess.run(remote_op)       # hangs forever
```
You see this during worker's `session.run`
```
2017-11-11 16:06:12.524442: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2017-11-11 16:06:22.525582: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
2017-11-11 16:06:32.525718: I tensorflow/core/distributed_runtime/master.cc:221] CreateSession still waiting for response from worker: /job:ps/replica:0/task:0
```

Suggestion: since `CreateSession` happens during `session.run`, make it subject to `.operation_timeout_in_ms` deadline

cc @mrry

**Comment by cy89** [comment]
@mrry would you please comment?

**Comment by mrry** [comment]
Indeed, it looks like the cancellation isn't propagated to the `WorkerService.ListDevices()` RPCs, which will attempt to reconnect forever if the host is unavailable. It seems reasonable to add that, and hopefully someone will volunteer to do it.

Just to check though, @sherrym: was there any reason you didn't add a timeout to this operation in fa07bfda6896748b747334e750763f6feea91129? (My recollection is that that change was to add a timeout that would mitigate run-time hangs, rather than startup hangs, for `SyncReplicasOptimizer`.)

/cc @saeta @suharshs as the two people who've been in there most recently, and might enjoy implementing the feature :). I'll mark as contributions welcome in case anybody else fancies a go.
