### ISSUE TITLE
[Fetaure Request] Bicubic interpolation using map coordinates

### ISSUE THREAD

**Issue by Sudhakar17** [tensorflow/tensorflow#14482]
I would like to train a two CNN in single graph. The architecture of model is 
![capture](https://user-images.githubusercontent.com/18436807/32688705-3ea9e54c-c6d6-11e7-84ba-fb01a3be2755.PNG)

This one is not like end to end training. In the warping of images(refer attachment), I use scipy for mapping coordinates from the disparity map to an input image and I am unable to build a model(graph) in tensorflow using scipy. Tensorflow supports only resize of images using bicubic/bilinear interpolation. [https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.ndimage.interpolation.map_coordinates.html](url)

For reference, original paper is implemented using matconvnet in [matlab.](http://cseweb.ucsd.edu/~viscomp/projects/LF/papers/SIGASIA16/)

**Comment by bignamehyp** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by Sudhakar17** [comment]
Thanks for your time. I have one question.

I will train a CNN1 using extracted depth features and freeze a graph. Then I will do an bicubic interpolation with disparity map in images using SciPy. Later, I use that warped images to train a CNN2 with tensorflow. Will auto-differentiation work in this case ? 

I read that tensorflow follows static graph construction. So probably it works only in an end to end training. (Not sure ! )

**Comment by Conchylicultor** [comment]
+1, for parity with `numpy` (`scipy.ndimage.map_coordinates`) and `jax` (`jax.scipy.ndimage.map_coordinates`). It would be great to have

**Comment by Venkat6871** [comment]
Hi **@Sudhakar17** ,
- Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

- The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow version with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

- Please follow the release notes to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
