### ISSUE TITLE
gfile random access file seek implementation inappropriate

### ISSUE THREAD

**Issue by fesun** [tensorflow/tensorflow#14512]
the call stack for tensorflow.python.platform.gfile.GFile.seek function is as follows:
https://github.com/tensorflow/tensorflow/blob/294442996b2aeff00b1bfdc7e7169f7cb35bbf3d/tensorflow/python/lib/io/file_io.py#L118
https://github.com/tensorflow/tensorflow/blob/18f36927160d05b941c056f10dc7f9aecaa05e23/tensorflow/core/lib/io/buffered_inputstream.cc#L153
https://github.com/tensorflow/tensorflow/blob/18f36927160d05b941c056f10dc7f9aecaa05e23/tensorflow/core/lib/io/buffered_inputstream.cc#L126
https://github.com/tensorflow/tensorflow/blob/d44d271c9da4d244ce4b2ffaf808adbe4cff759d/tensorflow/core/lib/io/random_inputstream.h#L27
https://github.com/tensorflow/tensorflow/blob/d44d271c9da4d244ce4b2ffaf808adbe4cff759d/tensorflow/core/lib/io/inputstream_interface.cc#L27

The implementation of SkipNBytes for random access file is read out N bytes. It's not efficient if we seek through one huge file. I think we should override the implementation for random access file.

I tried seek API for one large hdfs file, it took more than one hour to finish.

**Comment by bignamehyp** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by yongtang** [comment]
@fesun Are you looking for not reading through the data for RandomInputStream? It looks like RandomInputStream relies on RandomAccessFile which does not expose `SizeOfFile` so moving through the position marker will not be enough. We will need to know when EOF is hit.

On the other hand, I think it is possible to try reading 1 bytes to `expected_pos -1`, and if it complete, then we know EOF is not hit yet and we could (safely) move the position marker. Added #14557 for that.

**Comment by fesun** [comment]
@yongtang Thanks for your fix! This is exactly what I want.
