### ISSUE TITLE
How can I have an Online Data Augmentation like Keras in Tensorflow (tf-slim)?

### ISSUE THREAD

**Issue by Ellie68** [tensorflow/tensorflow#14511]
Hi all,

I use tf-slim [(this network)][1] for my classification problem. I want to do online data augmentation like [Keras ImageDataGenerator][2] for my images. I know [these functions][3] in Tensorflow, but I need a tutorial or an example in Tensorflow or tf-slim that does this online data augmentation. Would you please, help me to find a way to do this?

  [1]: https://github.com/pudae/tensorflow-densenet
  [2]: https://keras.io/preprocessing/image/
  [3]: https://www.tensorflow.org/api_guides/python/image

**Comment by cy89** [comment]
@sguada are there pointers we can pass along, or might this be something we would add in future documentation? 

@Ellie68 have you also asked on Stack Overflow?

**Comment by Ellie68** [comment]
Hi @cy89 

Yes, I have already asked on [Stack Overflow](https://stackoverflow.com/q/47258519/8872136). But I didn't get any good answers.

**Comment by sguada** [comment]
Take a look at https://github.com/tensorflow/models/blob/master/research/slim/preprocessing/inception_preprocessing.py

**Comment by tatatodd** [comment]
Closing this out, since the `inception_preprocessing.py` example seems pretty good.

For future reference, note that this type of question is better asked (and kept) on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

The "New issue" template has more information on this:

-----

Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug or a feature request.
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.
