### ISSUE TITLE
Python multiple inequalities do not work as expected

### ISSUE THREAD

**Issue by bernardopires** [tensorflow/tensorflow#1454]
```
import tensorflow as tf

with tf.device("/cpu:0"):
    lower_bound = tf.constant(
        [[ 0.,   0.,   0. ],
         [ 0.,   0.,   0. ],
         [ 0.5,  0.5,  0.5],
         [ 0.5,  0.5,  0.5],])
    upper_bound = tf.constant(
        [[ 0.5,  0.5,  0.5],
         [ 0.5,  0.5,  0.5],
         [ 1.,   1.,   1. ],
         [ 1.,   1.,   1. ],])
    test = tf.constant(
        [[ 0.30000001,  0.2,  0.82],
         [ 0.30000001,  0.2,  0.82],
         [ 0.30000001,  0.2,  0.82],
         [ 0.30000001,  0.2,  0.82],])
    multiple_inequality = lower_bound <= test < upper_bound
    lower_bound_filter = lower_bound <= test
    upper_bound_filter = test < upper_bound
    expected_filter = tf.logical_and(lower_bound_filter, upper_bound_filter)

with tf.Session() as sess:
    sess.run(tf.initialize_all_variables())
    print('Multiple inequality:', multiple_inequality.eval())
    print('Upper bound inequality:', upper_bound_filter.eval())
    print('Lower bound inequality:', lower_bound_filter.eval())
    print('Expected:', expected_filter.eval())
```
Output:

> ('Multiple inequality:', array([[ True,  True, False],
>        [ True,  True, False],
>        [ True,  True,  True],
>        [ True,  True,  True]], dtype=bool))
> ('Upper bound inequality:', array([[ True,  True, False],
>        [ True,  True, False],
>        [ True,  True,  True],
>        [ True,  True,  True]], dtype=bool))
> ('Lower bound inequality:', array([[ True,  True,  True],
>        [ True,  True,  True],
>        [False, False,  True],
>        [False, False,  True]], dtype=bool))
> ('Expected:', array([[ True,  True, False],
>        [ True,  True, False],
>        [False, False,  True],
>        [False, False,  True]], dtype=bool))

It seems like `multiple_inequality = lower_bound <= test < upper_bound` becomes `multiple_inequality = test < upper_bound`

**Comment by girving** [comment]
Unfortunately numpy as the same issue and for the same reason: our comparison operators return tensors of comparisons rather than single comparisons, and such tensors can't be combined with Python's `and` routine.

**Comment by mrry** [comment]
Is there a particular library or language on which you're basing your expectation (other than mathematics, where obviously the expression is well defined :)...)?

Generally speaking, we've been trying to maintain consistency between the TensorFlow Python API and NumPy. If I try to compute `multiple_inequality` using NumPy, I get the following:

```python
>>> import numpy as np
>>> lower_bound = np.array(
...         [[ 0.,   0.,   0. ],
...          [ 0.,   0.,   0. ],
...          [ 0.5,  0.5,  0.5],
...          [ 0.5,  0.5,  0.5],])
>>> upper_bound = np.array(
...         [[ 0.5,  0.5,  0.5],
...          [ 0.5,  0.5,  0.5],
...          [ 1.,   1.,   1. ],
...          [ 1.,   1.,   1. ],])
>>> test = np.array(
...         [[ 0.30000001,  0.2,  0.82],
...          [ 0.30000001,  0.2,  0.82],
...          [ 0.30000001,  0.2,  0.82],
...          [ 0.30000001,  0.2,  0.82],])
>>> lower_bound <= test < upper_bound
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

My intuition would be that this expression would be evaluated as one of the following (depending on the associativity of Python's comparison operators... I think it's the first of the two):

```python
x = lower_bound <= test  # a bool array
multiple_inequality = x < upper_bound  # bool vs. float
# or
x = test < upper_bound  # a bool array
multiple_inequality = lower_bound <= x  # bool vs. float
```

...however, either of these examples seems to work in NumPy (albeit with potentially wacky results, since NumPy converts `False` to `0.0` and `True` to `1.0`), so I'm not quite sure of the types.

---

**EDIT:** TIL that Python has [special syntax for chained comparisons](https://docs.python.org/2/reference/expressions.html#not-in)! However, its functionality seems to be predicated on interpreting the result of a comparison as a boolean. Unfortunately, the result of TensorFlow comparisons&mdash;like NumPy comparisons&mdash;is *not* a simple `bool` but rather a `tf.Tensor` object. We don't currently override `Tensor.__nonzero__()` (Python 2) or `Tensor.__bool__()` (Python 3), so a `tf.Tensor` is always considered to be "`True`" in comparisons etc.

Since this is a common error, I'm going to submit a quick fix that prevents this comparison. Unfortunately it isn't feasible to make the chained comparison syntax work, because Python's [bytecode translation for such comparisons](http://stackoverflow.com/a/12675160/3574081) relies on the value of the `Tensor` which isn't available when you construct the graph. However, we can at least provide a better error message.

**Comment by girving** [comment]
@mrry: Thank you for the more detailed explanation of my admittedly terse reply. :)  Good idea to produce a reasonable error!

**Comment by bernardopires** [comment]
Thanks for the fast reply guys. I'm not familiar with numpy so I didn't know they also had this limitation. I do think throwing an error preventing this comparison is a good idea, as I was surprised with the results.

**Comment by mrry** [comment]
Hmm, it looks like I may have spoken too soon... raising an error in `__nonzero__()`/`__bool__()` breaks a lot of previously legitimate code where we have:

```python
if tensor:
  # ...
```

...where really it should be:

```python
if tensor is not None:
  # ...
```

We can fix all of the instances in the TensorFlow library, but it might take longer to fix up all of the existing code that relies on the first version working as expected. Let's keep this issue open though, because the improved error messages are probably worth the pain.
