### ISSUE TITLE
tensorflow lite: how to set  --input_shapes param with batchsize when gen the pb lite file

### ISSUE THREAD

**Issue by charleys** [tensorflow/tensorflow#14650]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: lastest master
- **Python version**: 2.7

### Describe the problem

my python train script input tensor define as below :
tf.placeholder(dtype=tf.float32, shape=[None, 440], name=conf.input_features_tensor)

when i execute "bazel run --config=opt tensorflow/contrib/lite/toco:toco
 --others --input_shapes={None, 440} "

an error show as below :

2017-11-17 17:00:10.285456: F tensorflow/contrib/lite/toco/model_cmdline_flags.cc:269] Check failed: absl::SimpleAtoi(dim_str, &size) Failed to parse input_shape: None,440.

how i can set input batch size?

@andrehentz thx

**Comment by andrehentz** [comment]
If you know the batch size ahead of time, pass it in instead of None. For example --input_shape=3,440

If the batch size will change during inference, you can pass anything in and resize the input tensors during inference, when you know the size of the batch. Take a look at the apis.md file.

**Comment by charleys** [comment]
@andrehentz thx

**Comment by shivaniag** [comment]
Feel free to re-open if your issue hasn't been fully resolved.

**Comment by hamlatzis** [comment]
@andrehentz 

https://github.com/tensorflow/tensorflow/issues/14650#issuecomment-345325832

it doesn't work for me. I did exactly this, and I resize input tensors and call for allocation and at some point I get the reshape op called and when it calculates the shape of the output tensor it reports back that it's different to the input shape

reshape.cc line 58
TF_LITE_ENSURE_EQ(context, num_input_elements, num_output_elements);

As far as I understand some op (custom or built in) has the shape as constant and doesn't allow modification and I cannot find out which one. Probably it's a built-in op because I went and modified all my custom ops to use dynamic tensors and still have the same error.

I Googled this and many people have the same problem
