### ISSUE TITLE
where is mobile  ssd model?

### ISSUE THREAD

**Issue by sunjunlishi** [tensorflow/tensorflow#14715]
where is mobile  ssd model? where is it.where  is  mobile net model??

**Comment by tatatodd** [comment]
Perhaps you're looking for:

https://research.googleblog.com/2017/06/mobilenets-open-source-models-for.html
https://github.com/tensorflow/models/blob/master/research/slim/nets/mobilenet_v1.md
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android

For future reference, this type of question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
