### ISSUE TITLE
tf.TensorShape concatenation converts shape information to values

### ISSUE THREAD

**Issue by sleighsoft** [tensorflow/tensorflow#14762]
Tensorflow: 1.4.0

Example code:
```python
import tensorflow as tf
tf.InteractiveSession()
>>> tf.concat([tf.TensorShape([4,1]), tf.constant([1,1,1,1])], 0).eval()
array([4, 1, 1, 1, 1, 1])
```

Is it intended that this works and produces the output where the shape information gets converted into actual values?

**Comment by mrry** [comment]
Yes, this is intentional. `tf.concat()` expects a list of `tf.Tensor` objects as its argument, and it will implicitly convert a `tf.TensorShape` to a 1-D `tf.Tensor` if possible.

If you want to concatenate shapes and retain their shape-ness, use `tf.TensorShape([4, 1]).concatenate([1, 1, 1, 1])`.

**Comment by sleighsoft** [comment]
Actually I would have like a the following bevavior:
`array([1,1,1,1])` where `tf.TensorShape` denotes an "empty" shape that can be concatenated to a `tf.Tensor` to receive that Tensor again if shapes match. This would allow me to `tf.concat` in e.g. a `tf.while_loop` while having nothing to concatenate with in the first loop iteration.

**Comment by mrry** [comment]
Yes, shapes get converted to values because there are several APIs (e.g. `tf.reshape()`, `tf.fill()`, `tf.ones()`, `tf.zeros()`) that expect a `tf.Tensor` representing a shape, and it is convenient to be able to pass a `tf.TensorShape` directly to these APIs without an explicit conversion to `tf.Tensor`.

I'm not sure what `tf.TensorShape([4, 1])` would denote an empty shape, but it does not sound like the API you're describing matches the specification of `tf.concat()`. You can create empty tensors using `tf.constant()` and use these as the initial value for loop variables.

**Comment by sleighsoft** [comment]
I see, then I misunderstood the meaning of a `tf.TensorShape`. How do I get an empty `tf.constant`? It seems to require a `value`.

**Comment by mrry** [comment]
The easiest way is to pass an empty list as the value, and an explicit `shape` argument with at least one dimension set to 0.
