### ISSUE TITLE
Very different CPU usage/allocation behavior when using slightly different CPUs

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#14915]
I am running the same exact model on two largely similar systems, let's call them system A and B. However, TF's behavior is very different. On system A, CPU utilization is around 60% (on a 12-core system), while on system B CPU utilization is only around 8%. Moreover, on system A the same model runs about 10x slower than system B, even though it's using far fewer CPU resources.

The systems are similar in that they're both running:

Ubuntu 14.04
TensorFlow 1.4.0 (compiled from source)
Python 2.7
gcc 4.8.4

What's different:

System A:
Bazel 0.6.0
2x E5-2643 v3

System B:
Bazel 0.7.0
2x E5-2643 v4

Why would they behave so differently?

**Comment by viktro78** [comment]
The E5-2643 v4 uses the broadwell architecture, whereas the v3 uses haswell architecture. Broadwell architecture uses a 14nm process, whereas the haswell architecture uses 22nm, resulting in broadwell having a much higher ipc.

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by alquraishi** [comment]
You can close this if you want, but I'm reporting this as a bug, not a request for help. Same model with 10X performance decrease and 8X CPU utilization increase on nearly identical CPUs is not exactly expected behavior.

**Comment by yaroslavvb** [comment]
@alquraishi I guess the issue is that this bug is not actionable. Performance optimization is tricky, and there are many ways of ending up with slow performance. Without more details it's not clear if this is a fixable bug in TensorFlow, an unfixable bug in TensorFlow (or at least hard to fix), some kind of interaction between TensorFlow and underlying system, some inefficient implementation of the network where the inefficiency only comes out on some hardware implementation, etc

**Comment by tatatodd** [comment]
@alquraishi I don't deny that the behavior you're experiencing is unexpected.

The reason I'm suggesting you turn to StackOverflow for help is exactly what @yaroslavvb mentioned - without more information or a means for us to reproduce the issue, it's not clear what the issue is, and whether it is a bug in TensorFlow or not.  As a matter of policy, that sort of support is handled on StackOverflow.  Note we regularly monitor StackOverflow issues, just like we do for github issues.

If you do discover a more concrete problem, definitely do file an issue here.
