### ISSUE TITLE
Tensor as index to other tensor not supported?

### ISSUE THREAD

**Issue by rotem90** [tensorflow/tensorflow#14973]
I have 2 tensors (one is constant and one is placeholder), lets say:
A = [0.1,0.2,0.3,0.4,0.5,0.6,0.7]
B = [[1,2,4],[5,0],[3]]
I want to build a tensor C like this:
C= [[0.2,0.3,0.5],[0.6,0.1],[0.4]] which is a tensor in the same size of B and every element in C is equal to element in A indexed by B elements.

is there any way to do that?

Thanks!

**Comment by tatatodd** [comment]
I think you're looking for one of these:
https://www.tensorflow.org/versions/master/api_docs/python/tf/gather
https://www.tensorflow.org/versions/master/api_docs/python/tf/gather_nd

For future reference, this question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
