### ISSUE TITLE
Is there 3D ConvNets support ? 

### ISSUE THREAD

**Issue by sasadep** [tensorflow/tensorflow#150]
(Is there) **or** (will there be) a **3D ConvNets** support in **tensorflow** ?  
Which helps for spatiotemporal features.

**Comment by vrv** [comment]
We don't have a conv3d op yet, but there will eventually be!   We'll use this issue to track this feature request.

**Comment by sasadep** [comment]
:+1:

**Comment by PatrickChrist** [comment]
Theano offers serveral 3D Convolutional Implementations on CUDA. https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/GpuConv3D.py
https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/GpuConvGrad3D.py
https://github.com/Theano/Theano/blob/master/theano/sandbox/cuda/fftconv.py 
I would really appreciate, if you guys can port this stuff to tensorflow.

**Comment by edward339** [comment]
Any word on this? Would be very useful capability.

**Comment by bhack** [comment]
:+1:

**Comment by daeyun** [comment]
What is a good way to support 3D convolution in an existing code base that already uses tensorflow? I'm expecting to have to just port to a different library, but wanted to ask in case there's an easier way. I would want GPU support, but less optimized is fine.

**Comment by omarcr** [comment]
+1 on this request.

**Comment by noureldien** [comment]
Please, support 3D convnets. Thanks for help.

**Comment by bhack** [comment]
Ops are arriving with https://github.com/tensorflow/tensorflow/pull/1571/commits/784778e76d3f5fd75b9ec99138770795907f1616

**Comment by jerabaul29** [comment]
Great!

I guess a problem with 3 (or higher) D convnets will be the cost of computations. Do you think it would be possible / useful (or maybe it is already possible in your ops?) to implement a tetrahedral instead of square grid convnet as suggested in this article? Interesting also for later generalization to higher dimension: if I understand well, this approach (generalized if necessary to higher dimension) will make the number of nodes in the kernel linear instead of exponential in the dimension of the initial tensor.

http://arxiv.org/pdf/1505.02890v2.pdf

**Comment by jerabaul29** [comment]
Can the people at the origin of the present enhancement look at the following one:

https://github.com/tensorflow/tensorflow/issues/1661

The generalization asked may (?) be easier to implement by the same people who have already done it in 3D...

**Comment by akors** [comment]
Is it just the missing conv3d operation? Or do *all* operations for ConvNets need to be modified? Because when looking through the API documentation, the input tensor almost always seems to be fixed at 4D with [batch, height, width, channels].
What I can spot now but is probably incomplete:
- avg_pool
- max_pool
- moments

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/commit/6a187ccddaebb741ea77fc3201c6e36625f0aadb added 3d convolution support, including the pooling ops.

**Comment by rogertrullo** [comment]
is there also a 3d "Deconvolution" (conv3d_transpose) available?
Thanks!

**Comment by daeyun** [comment]
@rogertrullo `conv3d_backprop_input` is available e.g. #2467

**Comment by el3ment** [comment]
@rogertrullo if you manage to get conv3d_backprop_input to work as a deconvolution, would you publish some example code?

**Comment by rogertrullo** [comment]
@el3ment sure!, I am wondering though, if I define the operation like in #2467 , if I use the function as a layer, will the backward pass do something? (since we are actually using the backward pass of the convolution as forwards pass for the "deconvolution" )

**Comment by daeyun** [comment]
@rogertrullo I think so. conv2d_transpose is actually `conv2d_backprop_input`.

https://github.com/tensorflow/tensorflow/blob/9e8a4938c06301cc3afa4cd3a3c6c2279e81c98f/tensorflow/python/ops/nn_ops.py#L292

**Comment by spalaciob** [comment]
According to the doc (r0.9 and master), `max_pool3d` doesn't support pooling along the depth axis (`ksize[1] = 1`). Is there a way around this? Is this a missing feature?
