### ISSUE TITLE
msvcp140.dll missing on win 7

### ISSUE THREAD

**Issue by simonhuber95** [tensorflow/tensorflow#15003]
Hi everyone :)

I installed Tensorflow on Windows 7 ultimate with Python 3.5.4, via the `pip3 install --upgrade tensorflow` command. It even stated it successfully installed version 1.4

But if I try to invoke `import tensorflow as tf` in the shell I get the following error:
![grafik](https://user-images.githubusercontent.com/33151777/33433308-5b8fee18-d5db-11e7-8ddf-7037bae45e11.png)
 
Of course I installed the recommended Visual C++ 2015 Redistributablle 64bit Update 3, but there is neither the .dll file in my system folder, nor does tensorflow work. I get the same error as before.

Any help is appreciated, Thank you :)

**Comment by tatatodd** [comment]
@simonhuber95 This sounds like a problem that's specific to your machine or installation, rather than a problem with TensorFlow.  I'd suggest investigating online for `msvcp140.dll` problems.

E.g. this StackOverflow issue suggests downloading `Visual C++ Redistributable for Visual Studio 2015`:
https://stackoverflow.com/questions/32998902/msvcp140-dll-missing

Closing this out, since there isn't much we can do on the TensorFlow side to fix this.
