### ISSUE TITLE
no such package 'tensorflow/examples/image_retraining': BUILD file not found on package path. for Virtual Environment on mac. 

### ISSUE THREAD

**Issue by max1456** [tensorflow/tensorflow#15016]
**Template ignored**

**Comment by max1456** [comment]
no such package 'tensorflow/examples/image_retraining': BUILD file not found on package path. I followed the tensorflow tutorial for retraining inception but when typed retrain this occured. I am running it on a virtual env on a macbook pro.  How do i get the build file on a virtual env.


bazel build tensorflow/examples/image_retraining:retrain
ERROR: no such package 'tensorflow/examples/image_retraining': BUILD file not found on package path.
INFO: Elapsed time: 1.469s

**Comment by aselle** [comment]
I apologize but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new) . Please provide all the information it asks. Thank you.

i.e. What version of tensorflow? What tutorial URL? Where are you running this command from?
However, my guess is you are not running this from within the downloaded source tree of tensorflow.
