### ISSUE TITLE
Feature request: Use placeholders to specify the inputs of TFGAN model.

### ISSUE THREAD

**Issue by betterenvi** [tensorflow/tensorflow#15383]

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by betterenvi** [comment]
@tensorflowbutler 
Thanks, but this is a feature request, not a  bug. Do I still need to fill out these fields?

**Comment by petertulala** [comment]
Are plans to implement this? It would simplify the model, because currently it is very difficult to manipulate with a saved a graph without placeholders for inputs.

For example, currently there are two different discriminators created - one for real and one for fake data.

When I want to save the model and use the trained discriminator later with custom data, I have to create a third discriminator before saving with a placeholder as follows:

```
disc_in = tf.placeholder(tf.float32, name='disc_in', shape=(None, 28, 28, 1))
with tf.variable_scope(gan_model.discriminator_scope, reuse=True):
    gan_model.discriminator_and_aux_fn(disc_in, None)
```

So I end up with 3 different discriminators in the model. If TFGAN would use placeholders, we would need only one discriminator in the model.

**Comment by pribadihcr** [comment]
@petertulala 

Do you have the example how to use input from placeholder?
