### ISSUE TITLE
Loading tensorflow before scipy.misc seems to cause imread to fail

### ISSUE THREAD

**Issue by ritsu1228** [tensorflow/tensorflow#1541]
If I load `tensorflow` before loading `scipy.mics`, `scipy.misc.imread` seems to return `PIL.JpegImagePlugin.JpegImageFile`.

E.g. if I write

```
import tensorflow as tf
import scipy.misc

im = scipy.misc.imread('1.jpg')
```

`im` will be something like `array(<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=178x218 at 0x7F85ED8AA050>, dtype=object)`.

However, if I write

```
import scipy.misc
import tensorflow as tf

im = scipy.misc.imread('1.jpg')
```

`im` will be a normal `array` with `dtype=uint8`.

Why loading `tensorflow` first causes `scipy.misc.imread` to fail? I suppose this loading order should not matter.

I was building from source with commit `945a4b4cd12df0fdf3f0cc24b128bb4ce66ebf88`. I don't think I had this problem with older versions.

**Comment by mrry** [comment]
This sounds like an issue with your `pillow` (or possible `PIL`) installation. See the answer to [this Stack Overflow question](http://stackoverflow.com/questions/16612293/scipy-misc-imread-creates-an-image-with-no-size-or-shape) for a suggestion on how to fix it.

My guess is that a different version of some common library like `numpy` is being loaded when you load the modules in the two different orders, which leads to the confusion. This would seem especially likely if you had installed TensorFlow in a virtualenv, since TensorFlow installs its own copies of some libraries (including `numpy`), which might not be compatible with the system-installed version of, e.g., `scipy`.

**Comment by ritsu1228** [comment]
Thank you @mrry ! Actually I saw that post and tried the suggestion there but it didn't help. I am installing tensorflow on top of anaconda. I guess your thought is correct. I will try to figure this out. Before than I will just load `tensorflow` after `scipy`.

**Comment by snakecharmer1024** [comment]
This is also an issue with opencv. 

import cv2
import tensorflow
img = cv2.imread(...)

results in a numpy array with image contents.

import tensorflow
import cv2
img = cv2.imread(...)

this results in a None object for img.

**Comment by dzhyeon** [comment]
I'm also having same issue and it looks like this is happening only when loading jpg image.

**Comment by mrry** [comment]
Which version of TensorFlow are you running? The 0.9 release candidate should have the fix.
