### ISSUE TITLE
Decode_raw_op_test failure on s390x

### ISSUE THREAD

**Issue by namrata-ibm** [tensorflow/tensorflow#15767]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: s390x Ubuntu 16.04 
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: v1.4.1
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 0.7.0
- **GCC/Compiler version (if compiling from source)**: gcc 5.4.0
- **CUDA/cuDNN version**: NA
- **GPU model and memory**: NA
- **Exact command to reproduce**: bazel test -c opt //tensorflow/python/kernel_tests:decode_raw_op_test

### Describe the problem
Observing a failure in [testToFloat16](https://github.com/tensorflow/tensorflow/blob/v1.4.1/tensorflow/python/kernel_tests/decode_raw_op_test.py#L77) sub test, while running `decode_raw_op_test`. It seems that the [byte-reversal logic](https://github.com/tensorflow/tensorflow/blob/v1.4.1/tensorflow/core/kernels/decode_raw_op.cc#L80) for big endian is not needed for **float16 input**(and float16 output). While the other sub tests like int16/uint16 which have byte array input need byte-swapping for consistent results. What would be the best way to correct this?
@rmlarsen, @jiefangxuanyan , Could you please share your thoughts on this?
 
### Source code / logs
```
FAIL: testToFloat16 (__main__.DecodeRawOpTest)
----------------------------------------------------------------------
.
AssertionError:
Arrays are not equal
(mismatch 100.0%)
 x: [repr failed for <matrix>: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()]
 y: array([[  3.576279e-06,   1.144409e-05,   1.156330e-05,   4.053116e-06]], dtype=float16)
----------------------------------------------------------------------
Ran 7 tests in 0.089s

FAILED (failures=1)
not equal where =  (array([0, 0, 0, 0]), array([0, 1, 2, 3]))
not equal lhs =  [[ 1. -2. -3.  4.]]
not equal rhs =  [  3.57627869e-06   1.14440918e-05   1.15633011e-05   4.05311584e-06]
```

**Comment by jiefangxuanyan** [comment]
I think this problem is caused by `np.ndarray.tostring` [here](https://github.com/tensorflow/tensorflow/blob/438604fc885208ee05f9eef2d0f2c630e1360a83/tensorflow/python/kernel_tests/decode_raw_op_test.py#L84). This method ["constructs Python bytes showing a copy of the raw contents of data memory"](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tostring.html). So we get bytes in the native byte order, and the test will always fail on big-endian machines as long as `decode_raw` used little-endian as default. Maybe we should re-write the tests for float numbers.

**Comment by jiefangxuanyan** [comment]
I think this problem is caused by `np.ndarray.tostring` [here](https://github.com/tensorflow/tensorflow/blob/438604fc885208ee05f9eef2d0f2c630e1360a83/tensorflow/python/kernel_tests/decode_raw_op_test.py#L84). This method ["constructs Python bytes showing a copy of the raw contents of data memory"](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.tostring.html). So we get bytes in the native byte order, and the test will always fail on big-endian machines as long as `decode_raw` used little-endian as default. Maybe we should re-write the tests for float numbers.

**Comment by namrata-ibm** [comment]
@jiefangxuanyan, thank you for your inputs.

As you pointed out, output of `tostring` on x86 and s390x as seen is: 
```
x86:
 expected_result.tostring() --  ['0x0', '0x3c', '0x0', '0xc0', '0x0', '0xc2', '0x0', '0x44']
s390x:
 expected_result.tostring() --  ['0x3c', '0x0', '0xc0', '0x0', '0xc2', '0x0', '0x44', '0x0']
```
I tried below change in that test case:
```
if sys.byteorder == "big":
  result = decode.eval(feed_dict={in_bytes: [expected_result.byteswap().tostring()]})
else:
   result = decode.eval(feed_dict={in_bytes: [expected_result.tostring()]})
```
With this change, test passes on both platforms.

But I wonder if the functionality of decode_raw is correct for float? What will happen in actual scenario during decode_raw operation for float? Will `decode_raw_op.cc` need changes when input is not a byte array?

**Comment by jiefangxuanyan** [comment]
A simple solution could be just specify endianness in numpy dtype:
```
expected_result = np.matrix([[1, -2, -3, 4]], dtype="<f2")
```
