### ISSUE TITLE
Unable to find source java class: '/Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/java/src/main/java/org/tensorflow/op/core/Constant.java'

### ISSUE THREAD

**Issue by Maheshsmartdata** [tensorflow/tensorflow#15785]
I follow the instructions on the tensorflow official website on how to import android samples. I did exactly as they said but when I try to run the app it shows the following error.

Error:Execution failed for task ':compileDebugJavaWithJavac'.
> Unable to find source java class: '/Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/java/src/main/java/org/tensorflow/op/core/Constant.java' because it does not belong to any of the source dirs: '[/Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/examples/android/src/main/java, /Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/examples/android/src, /Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/examples/android/build-types/debug/java, /Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/examples/android/gradleBuild/generated/source/r/debug, /Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/examples/android/gradleBuild/generated/source/buildConfig/debug, /Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/examples/android/gradleBuild/generated/source/aidl/debug, /Users/vinay.garg/AndroidStudioProjects/tensorflow/tensorflow/examples/android/gradleBuild/generated/source/rs/debug]'

The problem is, Constants.java file is in the parent directory and not in the sample project directory. I tried to find the usage of the Constants.java file but can't find its use anywhere in the sample project. What am I missing here?

**Comment by hgasimov** [comment]
I had the same issue some minutes ago. I solved it by running "Build -> Rebuild Project" from Android Studio menu.

**Comment by Maheshsmartdata** [comment]
Thanks man. It worked.
I feel so dumb that I did not try this before posting it as an issue.

**Comment by sunnylovejordan** [comment]
I had Rebuild Project,but didn't work.

**Comment by japer21** [comment]
I am working on windows 10 and I want to make it work with my own model, how can I achieve it?

**Comment by llrraa** [comment]
> I am working on windows 10 and I want to make it work with my own model, how can I achieve it?

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android#install-model-files-optional
Optional: If you wish to place the models in your assets manually, remove all of the model_files entries from the assets list in tensorflow_demo found in the BUILD file. Then download and extract the archives yourself to the assets directory in the source tree:

BASE_URL=https://storage.googleapis.com/download.tensorflow.org/models
for MODEL_ZIP in inception5h.zip ssd_mobilenet_v1_android_export.zip stylize_v1.zip
do
  curl -L ${BASE_URL}/${MODEL_ZIP} -o /tmp/${MODEL_ZIP}
  unzip /tmp/${MODEL_ZIP} -d tensorflow/examples/android/assets/
done
This will extract the models and their associated metadata files to the local assets/ directory.

If you are using Gradle, make sure to remove download-models.gradle reference from build.gradle after your manually download models; otherwise gradle might download models again and overwrite your models.

Build
