### ISSUE TITLE
Code documentation for `confusion_matrix.py` misleading

### ISSUE THREAD

**Issue by timmolter** [tensorflow/tensorflow#16041]
### Describe the problem

The documentation for `confusion_matrix.py` says:

```
  Args:
    labels: 1-D `Tensor` of real labels for the classification task.
    predictions: 1-D `Tensor` of predictions for a given classification.
```

, however I found that those two arguments are simply python arrays and not Tensors. The following trial test code demonstrates this. As a TF/Python newbie, I'm wondering if this is actually a real issue, and if so I'll create a PR to correct it to prevent confusion to future programmers.

### Source code / logs

```
import tensorflow as tf

y_ = [0, 2, 2, 2]
y = [2, 1, 2, 2]

with tf.Session() as sess:
    confusion_matrix = tf.confusion_matrix(labels=y_, predictions=y, num_classes=4)
    confusion_matrix_to_Print = sess.run(confusion_matrix)
    print(confusion_matrix_to_Print)

```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by shivaniag** [comment]
IIUC, labels and predictions can accept `Tensor` objects, numpy arrays, Python lists, and Python scalars. @mrry do you know if there is any reason behind this or this is something which we need to fix.

**Comment by mrry** [comment]
This is covered in the documentation [here](https://www.tensorflow.org/programmers_guide/graphs#tensor-like_objects). @shivaniag is correct to say that other "tensor-like" types are accepted (including in this case Python lists and 1-D NumPy arrays) because they are implicitly convertible to `tf.Tensor` objects. I'd only consider this misleading if `tf.confusion_matrix()` **didn't** accept `tf.Tensor` objects, but as far as I can tell from the code it does.
