### ISSUE TITLE
when will we have multi gpu support under eager mode? Pytorch has it.

### ISSUE THREAD

**Issue by xiaoyunwu** [tensorflow/tensorflow#16093]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1. It must be a bug or a feature request.
2. The form below must be filled out.
3. It shouldn't be a TensorBoard issue. Those go [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
- **TensorFlow installed from (source or binary)**:
- **TensorFlow version (use command below)**:
- **Python version**: 
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by asimshankar** [comment]
Multiple GPUs are supported with eager execution in that you can use `with tf.device('/gpu:<N>')` blocks to place operations and tensors on different GPUs. For example, the following will execute one matmul on GPU0 and one on GPU1:

```python
with tf.device('/gpu:0'):
  tf.matmul([[1.]], [[2.]])
with tf.device('/gpu:1'):
  tf.matmul([[1.]], [[2.]])
```
However, it will schedule them serially - so your bottleneck will likely be the Python interpreter's single thread feeding the GPUs.

We're working on APIs for more efficient use of multiple GPUs and overall cutting down the cost of initiating operations from the Python interpreter.

I'm tempted to close out this issue since it is a bit open ended. Any significant APIs addressing this will be part of the release notes over the next few releases.

Thanks!

**Comment by asimshankar** [comment]
(FYI @josh11b )

**Comment by xiaoyunwu** [comment]
@asimshankar When will we have a better version of multi-gpu support like pytorch? Where we can do pytorch nn.DataParallel kind of operation?

**Comment by asimshankar** [comment]
@xiaoyunwu : Smoother multi-GPU support for eager is actively being worked on. However, I don't have a timeline to commit to at this point. We will surely make this clear in the release notes of the release where we feel it's in a position to use.

**Comment by xiaoyunwu** [comment]
@asimshankar any update?

**Comment by xiaoyunwu** [comment]
@asimshankar any update? It has been a long while now.

**Comment by asimshankar** [comment]
@xiaoyunwu - Unfortunately, no concrete update yet. However, the intent is to keep this in line with graph execution via the [distribution strategy APIs](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/distribute) and integrate that with the `tf.keras` classes so that the same code works for both graph and eager execution.

**Comment by xiaoyunwu** [comment]
but pytorch is ahead of us for so long, we need to have some solution.

Xiaoyun

**Comment by xiaoyunwu** [comment]
https://github.com/kashif/tf-keras-tutorial/blob/master/7-estimators-multi-gpus.ipynb

Is this the sign of what we are heading?

Xiaoyun

**Comment by asimshankar** [comment]
That tutorial you referred to is nice - it does demonstrate the general idea that the exact same code (`tf.keras.Model` object) used with eager execution can be used to create an `Estimator` for distributed (multi-GPU or multi-node) training.

We are working on making that process much smoother, where say the `DistributionStrategy` to use can be provided directly to the `tf.keras.Model` object. Till that happens, the notebook you referred to is one possibility. Sound reasonable?

**Comment by xiaoyunwu** [comment]
Asim,
any update on using multi gpu with eager mode?
Thanks.

Xiaoyun
