### ISSUE TITLE
Is it possible to train CNN model by using tensorflow JAVA API?

### ISSUE THREAD

**Issue by rayjang** [tensorflow/tensorflow#16144]
Hello, TF.
I have plane to train my CNN model by using tensorflow JAVA API.
I got success on simple model( with a simple matmul operation between weights and bias)
BUT I failed to train CNN model.
I got these error when I train the model.
![image](https://user-images.githubusercontent.com/9244296/34974396-0bfaaeb4-fad0-11e7-86c9-46ee3c154d3f.png)
Is there any way to solve this problem????

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said:
- Yes, it is possible to train from the Java API
- However, it seems what you're asking about (based on the error message) is training from Android. For binary size reasons, we strip the number of operations in the pre-built Android packages. To include additional operations, you may need to use selective registration. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/selective_registration.h (unfortunately, selective registration is not yet well documented (#10299)

**Comment by rayjang** [comment]
@asimshankar 
according to this article([](https://stackoverflow.com/questions/46030577/how-to-train-a-model-in-tensorflow-using-java)),
Train function of JAVA api is not sufficient.
Is it right?
TF Slim or other convolution layers are not supported I guess.
