### ISSUE TITLE
ContentTooShortError: <urlopen error retrieval incomplete: got only 246506328 out of 247336696 bytes>

### ISSUE THREAD

**Issue by KISHANKG** [tensorflow/tensorflow#16269]
I have started UDACITY deep learning course.
I was copying the assignment 1 codes then I got the this error during downloading the notMNIST_large.tar.gz
Here are some screenshots of the code.
I am doing this on jupyter python3 notebook in ubuntu.

![1](https://user-images.githubusercontent.com/25321783/35194207-ca56cdc6-fed5-11e7-9fe7-3232c3741689.png)
![2](https://user-images.githubusercontent.com/25321783/35194208-cacbbc6c-fed5-11e7-9ff0-600527e4990a.png)
![error](https://user-images.githubusercontent.com/25321783/35194209-cb3fbd6a-fed5-11e7-8162-9b999b6240bb.png)

**Comment by aselle** [comment]
Since this is custom code written by the professors teaching the udacity course, this is not the right forum. Please use the course forum, unless it is clear that it is a bug in TensorFlow. If you believe it to be a problem with the core TensorFlow library, please attach a text file of a reproducible test case.
