### ISSUE TITLE
Windows Installation tutorial has wrong cuda version requirement, 9.0 required for latest version.

### ISSUE THREAD

**Issue by cherrerajobs** [tensorflow/tensorflow#16477]
I just ran the installation validation and it's telling me I need 9.0, the tutorial says we must use 8.0. I don't have cheap access to Internet, now I have to find 1GB+ plus of data without paying $15 to use my phone's data. Please update the page to recommend 9.0.

Thank you.

**Comment by jackyko1991** [comment]
A pull request has been submitted. Pending for review and merge

**Comment by kuri-leo** [comment]
I meet the same issue. and I've reported it to Tensorflow team.

As @mtngle commented in #16513 , there are three solutions:

> The prebuilt tensorflow binaries support CUDA 9.0 - https://github.com/tensorflow/tensorflow/releases/tag/v1.5.0
> 
> You have 3 options:
> 
> Compile from source and link against CUDA 8.0.
> Upgrade your CUDA to 9.0
> Continue to user TF 1.4.

waiting for response.

**Comment by reedwm** [comment]
Marking as contributions since there's a pull request. (@jackyko1991 can you link the pull request?)

**Comment by tylerlekang** [comment]
I see a couple pull requests to update the release notes file from "CUDA 9" to "CUDA 9.0", but the Windows gpu installation instructions on the TF website (https://www.tensorflow.org/install/install_windows) still show 8.0 and 6.0.

**Comment by kuri-leo** [comment]
Hi @reedwm  ,
PR #16486 added the Cuda requirement to README.md.

and Hi @tylerlekang ,
I've reported it to Tensorflow team via our Google Developer Group on 28st and waiting for their updating.

**Comment by jackyko1991** [comment]
I have added c++ interface support with updated readme in PR https://github.com/tensorflow/tensorflow/pull/16480

protobuf has been updated to 3.5.0 in this version, however it will require NASM and golang to get it build pass.

**Comment by reedwm** [comment]
@jackyko1991 that PR does not update the documentation [here](https://github.com/tensorflow/tensorflow/blob/835a466c487c3a62852223eac6475ff4a4cc9836/tensorflow/docs_src/install/install_windows.md) and [here](https://github.com/tensorflow/tensorflow/blob/835a466c487c3a62852223eac6475ff4a4cc9836/tensorflow/docs_src/install/install_linux.md), which I believe is what this issue is about.

@gunan, can you update the documentation?

**Comment by tylerlekang** [comment]
As mentioned in the other thread (which is now closed):

It might be nice to have CUDA/cuDNN version support information in one location, and have everything else point to that webpage. Then you don't have to remember to update the version numbers in multiple places (and potentially forget a few).

In that case, it might also be nice to mention a few more specifics of the version numbers that a particular tf-gpu release was tested with.

Because there are a lot of different versions of CUDA and cuDNN, beyond simply saying 8.0 or 9.0. CUDA has 8.0GA1, 8.0GA2, and 9.0, the latter two of which also have an option for a separately installed update. cuDNN has 6.0 for CUDA 8.0, but also 7.0.4 and 7.0.5 for CUDA 9.0

Furthermore, it could be mentioned what version of the nVidia driver was used ... but only if that might actually make a difference (not sure).

**Comment by gunan** [comment]
Only thing we can point to is the cuda and cudnn versions we built against.
From user perspective, 8.0GA1 and 8.0GA2 should be the same, there should be only bugfixes between the two. So we will keep just announcing 8.0, or 9.0 (or 9.) version we build against.
Similarly, when we build against cuDNN 7.0.5, you should still be able to run it with cuDNN 7.0.4.

The drivers you will need to use for each CUDA version can be different, but only nvidia can help you with that. So you should reach out to them for which driver version should be used with which cuda version.

We usually include CUDA and cuDNN versions, but this time we forgot to update it.
It is currently updated in the source, but we need to update the website @av8ramit @MarkDaoust FYI the website still says CUDA8
We also include/announce CUDA updates in our release notes, but those are not followed as close as the website.

One thing I would like to do is improve our error reporting. When someone tries to import tensorflow rather than saying ".....so not found" I want to have an error message that says "You need cuda XX to run this version tensorflow, however you have XX installed". I am open to contributions for this if anyone would like to take this on.

**Comment by av8ramit** [comment]
https://github.com/tensorflow/tensorflow/pull/16702
Assigning to @MarkDaoust to update the website.

**Comment by MarkDaoust** [comment]
r1.5, r1.6 and master all include that change now and the website has been updated.

**Comment by tylerlekang** [comment]
@MarkDaoust the windows install webpage now shows CUDA 9.0, but shows cuDNN 6.0, and requires minimum compute capability of 3.0

The ubuntu install webpage, on the other hand, shows CUDA 9.0, cuDNN 7.0, and requires minimum compute capability of 3.5.

Just want to confirm these are correct. If so it means we can't use cuDNN 7.0(.x) on windows??

**Comment by gunan** [comment]
Windows also requires cuDNN 7,  looks like we missed that.

**Comment by tylerlekang** [comment]
Does Ubuntu actually require a GPU with higher computer capability than for Windows? It would wipe out a large swath of previous gen GPU cards if 3.5 is the true minimum.
