### ISSUE TITLE
Tensorflow 1.5.0 import error under CUDA 8.0

### ISSUE THREAD

**Issue by ha-ha-ha-han** [tensorflow/tensorflow#16670]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Windows 10
- **TensorFlow installed from (source or binary)**:
pip install tensorflow-gpu
- **TensorFlow version (use command below)**:
1.5.0
- **Python version**: 
3.5.4
- **CUDA/cuDNN version**:
8.0/6.0
- **GPU model and memory**:
GTX1080ti
- **Exact command to reproduce**:
pip install tensorflow-gpu
python
import tensorflow as tf

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with

python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

### Describe the problem
Tensorflow 1.4 works fine with the same setup as described above. However, after upgrade tensorflow to 1.5 using pip install tensorflow-gpu, it fails to import tensorflow package in python.

### Source code / logs
(tensorflow_1_5) C:\WINDOWS\system32>python
Python 3.5.4 |Continuum Analytics, Inc.| (default, Aug 14 2017, 13:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "C:\Program Files\Anaconda3\envs\tensorflow_1_5\lib\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Program Files\Anaconda3\envs\tensorflow_1_5\lib\ctypes\__init__.py", line 351, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\Anaconda3\envs\tensorflow_1_5\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "C:\Program Files\Anaconda3\envs\tensorflow_1_5\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Program Files\Anaconda3\envs\tensorflow_1_5\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 30, in <module>
    self_check.preload_check()
  File "C:\Program Files\Anaconda3\envs\tensorflow_1_5\lib\site-packages\tensorflow\python\platform\self_check.py", line 82, in preload_check
    % (build_info.cudart_dll_name, build_info.cuda_version_number))
ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit

**Comment by mrry** [comment]
Did you try following these instructions?

> ImportError: Could not find 'cudart64_90.dll'. TensorFlow requires that this DLL be installed in a directory that is named in your %PATH% environment variable. Download and install CUDA 9.0 from this URL: https://developer.nvidia.com/cuda-toolkit

**Comment by dkhusial** [comment]
I have the same error following the instructions at https://www.tensorflow.org/install/install_windows. After reverting back to: 
pip install --upgrade https://storage.googleapis.com/tensorflow/windows/gpu/tensorflow_gpu-1.0.0-cp35-cp35m-win_amd64.whl the issue is resolved.

**Comment by mrry** [comment]
@dkhusial Did you try upgrading to CUDA 9.0, as suggested in the error message?

**Comment by dkhusial** [comment]
Just tried tf 1.4 and works with my cuda 8 also. I am doing some testing on some tf from an old Windows machine to a new machine once I get through that I can try upgrading to cuda 9 and see if that will work with the latest tf 1.5. But that is likely tomorrow.

**Comment by dkhusial** [comment]
@mrry Just found another machine todo the Cuda 9.0 upgrade with the matching cudnn. After upgrade, the tensorflow hello world validation instructions works on a GTX 960M. Can you update the install_windows instructions at tensorflow.org?

**Comment by gunan** [comment]
@av8ramit looks like we may have forgotten tf install instructions with cuda version information?

**Comment by tylerlekang** [comment]
Yes, as of this moment the install instruction webpages (https://www.tensorflow.org/install/install_linux  and  https://www.tensorflow.org/install/install_windows) still show CUDA 8.0 and cuDNN 6.0, as noted in https://github.com/tensorflow/tensorflow/issues/16477

**Comment by ha-ha-ha-han** [comment]
>Yes, as of this moment the install instruction webpages (https://www.tensorflow.org/install/install_linux and https://www.tensorflow.org/install/install_windows) still show CUDA 8.0 and cuDNN 6.0, as noted in #16477

Yes I followed the instruction and didn't update the CUDA when the exception happened.
 
I upgraded CUDA and cudnn in my laptop (GTX 1050ti) and it worked. 
After updating to CUDA 9.0, cudnn 7 and Tensorflow 1.5, some model that I am now working with trains 25% faster than before in my laptop.

Interestingly, The old tensorflow 1.4 still works under CUDA 9.0.

It seems to be safe to upgrade tensorflow 1.5 for my legacy code. So I will do the same thing for the desktop.

Thanks a lot!

**Comment by QianYuK** [comment]
I tried tensorflow1.5 with cuda9.1 and cuda8.0, I got the same question. I see the install instruction say cuda8.0 is enough?

**Comment by scordata** [comment]
Having just been through this myself, I found that if you are using TF 1.5 you need Cuda 9.0. The nightly tensorflow ought to support 9.1, but I don't think that update has been pushed to the pip3 repo.

**Comment by tylerlekang** [comment]
It might be nice to have CUDA/cuDNN version support information in one location, and have everything else point to that webpage. Then you don't have to remember to update the version numbers in multiple places (and potentially forget a few).

In that case, it might also be nice to mention a few more specifics of the version numbers that a particular tf-gpu release was tested with.

Because there are a lot of different versions of CUDA and cuDNN, beyond simply saying 8.0 or 9.0. CUDA has 8.0GA1, 8.0GA2, and 9.0, the latter two of which also have an option for a separately installed update. cuDNN has 6.0 for CUDA 8.0, but also 7.0.4 and 7.0.5 for CUDA 9.0

Furthermore, it could be mentioned what version of the nVidia driver was used ... but only if that might actually make a difference (not sure).


@ha-ha-ha-han I think that when you install CUDA 9.0, it automatically installs side-by-side with CUDA 8.0 (not replaced it). Therefore, if you revert back to tf-gpu 1.4.0, it will still recognize the install of CUDA 8.0 that remains in your system.

**Comment by patruff** [comment]
@dkhusial I was debugging this problem for HOURS! Thanks so much. Reverting solved my issue!!

**Comment by gunan** [comment]
1.5, 1.6 and nightlies are all built for CUDA 9.0
We discussed with NVIDIA, and after their recommendation we decided to stay with cuda 9.0 rather than 9.1, as 9.1 requires drivers that are not available in all distros.

**Comment by vicproon** [comment]
@ha-ha-ha-han I have similar problem with upgrading to tf-1.5. However, I was unable to use @mrry advice and upgrade to cuda-9.0 due to the fact that U am using Ubuntu-14.04, for which NVIDIA does not provide an installer. 
The call to `pip3 install --upgrade tensorflow-gpu` does provide installation for ubuntu 14.04.
Maybe the configuration of ubuntu-14.04 and tf-1.5 can be achieved when building from source, however it was a real struggle in older tf versions so it would be highly appreciated if TF developers could provide prebuilt package of tf-1.5 for cuda-8.0. Or at least exclude ubuntu-14.04 out of supported OS for gpu versions.

**Comment by gunan** [comment]
The runfile installer for CUDA 9.0 should work for ubuntu 14, too.
Otherwise, you could also try using docker.

**Comment by ziruizhuang** [comment]
problem exists on Windows with CUDA 9.0 and CUDNN 7.0.5 for CUDA 9

**Comment by gunan** [comment]
Please file a new issue with all the debugging information requested by the template.
That way we can reproduce and pinpoint the exact problem.

**Comment by robhawkins** [comment]
@gunan it seems like part of the issue is documentation.  It's currently impossible to install tensorflow successfully by following [the instructions](http://archive.is/S1P6z)

**Comment by gunan** [comment]
I see. I think the documentation is fixed in the source, but we still need to push them to the website.
@MarkDaoust can we update the documentation in 1.5 and 1.6 branches?

**Comment by joelandplus** [comment]
Following instructions to install Cuda 9.0 on Ubuntu (apt-get) doesn't work, it will still install 9.1.

**Comment by Ericargus** [comment]
You don't  install cuda correctly

**Comment by facundoq** [comment]
@mrry The problem is not that people can't figure out what the error means. If the docs (https://www.tensorflow.org/versions/r1.5/install/install_linux) specify that TF 1.5 supports CUDA 8, then either the docs are wrong or the code is, not people's expectations. 

@gunan this hasn't been pushed to the website for 1.5 (its fixed for 1.6). I just ran into the same error for 1.5 with Ubuntu 16.04/cuda 8/cudnn 6 .

**Comment by mrry** [comment]
@MarkDaoust Can you push a fix to the 1.5 and 1.6 docs, please?
