### ISSUE TITLE
error in code 

### ISSUE THREAD

**Issue by 2017develper** [tensorflow/tensorflow#16740]
W_0 = utils.weight_variable([FLAGS.z_dim, 64 * GEN_DIMENSION / 2 * IMAGE_SIZE / 16 * IMAGE_SIZE / 16],
NameError: name 'utils' is not defined
can you help me please

**Comment by mrry** [comment]
I believe the source of that function is here: https://github.com/shekkizh/TensorflowProjects/blob/7bc5267da1bf4cf4a05cb1bac8bfd8f284728067/TensorflowUtils.py#L63

Since this does not appear to be a bug in or feature request for TensorFlow, I'm going to close this issue. If you continue to have difficulties, I'd recommend asking on Stack Overflow or opening an issue on the repository that contains that problematic line of code.
