### ISSUE TITLE
tf.QueueBase.dequeue_many returns list instead of tuple

### ISSUE THREAD

**Issue by seaotterman** [tensorflow/tensorflow#16948]
The dequeue_many operation returns a **list** of Tensors, while the documentation states that it should be a **tuple** (which is more sensible).

> Returns:
> The tuple of concatenated tensors that was dequeued.
(https://www.tensorflow.org/api_docs/python/tf/QueueBase)

Version: 1.5.0 from PIP, Python3, on OS/X

**Comment by cy89** [comment]
@mrry, I think that _dequeue_return_value was originally Matthieu's routine, but it looks like that routine is built to return a list not a tuple. Could you please comment on whether we should fix the documentation or fix the implementation, and perhaps assign someone to implement? 

Marking "docs" for now.

**Comment by mrry** [comment]
I don't think we can fix the implementation: although I agree it would make more sense to return a tuple here, there might be code that depends on it being a list. 

In a future major version of TensorFlow, it might make sense to use the `nest` library to allow nested structures (including lists, tuples, dictionaries, and recursive nests of those) to be stored in a queue.

For now, we'd welcome a fix to the documentation. I'm marking it as contributions welcome, since there is nobody specific working on that API right now.

**Comment by seaotterman** [comment]
I see, that's unfortunate but understandable. I submitted a pull request. #296540931
