### ISSUE TITLE
tf.fake_quant_with_min_max_vars returns wrong answer

### ISSUE THREAD

**Issue by com9009** [tensorflow/tensorflow#16995]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: pip install tensorflow-gpu
- **TensorFlow version (use command below)**: 1.5.0
- **Python version**: 2.7.12
- **Bazel version (if compiling from source)**: 
- **GCC/Compiler version (if compiling from source)**: 
- **CUDA/cuDNN version**: CUDA-8.0 CuDNN 6.0
- **GPU model and memory**: GTX 1080 8GB
- **Exact command to reproduce**: 

### Describe the problem
tf.fake_quant_with_min_max_vars returns wrong answer.

### Source code / logs
```python
import tensorflow as tf

a =tf.Variable([ 0.09504107, 0.0748544, 0.09333218, 0.106306, 0.09921047, 0.0930253, 0.09277194, 0.08704954, 0.12734564, 0.11479893], dtype=tf.float32)


sess = tf.InteractiveSession()
sess.run(tf.initialize_variables([a]))

print a.eval()
print tf.fake_quant_with_min_max_vars(inputs=a, min=tf.reduce_min(a), max=tf.reduce_max(a), num_bits=8).eval()
print tf.reduce_min(a).eval()
print tf.reduce_max(a).eval()
```

it prints like below
```
[ 0.09504107  0.0748544   0.09333218  0.106306    0.09921047  0.0930253
  0.09277194  0.08704954  0.12734564  0.11479893]
[ 0.05249124  0.05249124  0.05249124  0.05249124  0.05249124  0.05249124
  0.05249124  0.05249124  0.05249124  0.05249124]
0.0748544
0.127346
```

**Comment by aselle** [comment]
PTAL @suharshs. Thanks!

**Comment by navsuda** [comment]
Came across a similar error. The main reason is that fake_quant_with_min_max_vars Op is trying to "nudge" the quantized min, max values such that zero maps to an integer: [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/fake_quant_ops_functor.h#L139). Since both min,max values are positive and are _relatively_ far from zero, it happened that the (nudged min,max) values are (~0, 0.05249124), which are out of range of the values in variable "a". Hence all values are saturated to the upper bound of 0.05249124. 
Simple solution to your case is to not nudge, but the higher-level question is: will we encounter models  where min>0 and (max-min)<min?

**Comment by suharshs** [comment]
@navsuda  Yes this is indeed due to the nudging that happens. Nudging is very important because the float zero has to be represented exactly as a fixed point value when converted for hardware.

That being said, the particular implementation of nudging in FakeQuant may not be ideal because of saturation cases similar to what you describe. In practice it seems that as long as the nudging technique that the model is trained with is the same as what happens during inference on hardware, things seem to work out, but we are exploring different ways of nudging to avoid these cases.

I will close this since this isn't really a true 'error' and is how to op is expected to work. We may be introduce new techniques in the future though.

Thanks!
