### ISSUE TITLE
Not a gzipped file

### ISSUE THREAD

**Issue by lydhr** [tensorflow/tensorflow#170]
When I get started with 'Train your first TensorFlow neural net model':
`$ python tensorflow/models/image/mnist/convolutional.py`

There is an error:
```
File "tensorflow/models/image/mnist/convolutional.py", line 59, in extract_data
    bytestream.read(16)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 268, in read
    self._read(readsize)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 303, in _read
    self._read_gzip_header()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/gzip.py", line 197, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
```

**Comment by vincentvanhoucke** [comment]
The code attempts to download the data files from the MNIST web site, and assumes it's properly downloaded if the file is present locally on your system. You might have a corrupted file, in which case deleting it and retrying might help. Otherwise, try to get the data via your browser directly from:
http://yann.lecun.com/exdb/mnist/train-images-idx3-ubyte.gz
http://yann.lecun.com/exdb/mnist/train-labels-idx1-ubyte.gz
http://yann.lecun.com/exdb/mnist/t10k-images-idx3-ubyte.gz
http://yann.lecun.com/exdb/mnist/t10k-labels-idx1-ubyte.gz

**Comment by SunsetWan** [comment]
I downloaded these four data files from the link.But I don't know where these data file should be put.Is there anyone who can help me?

**Comment by wogong** [comment]
@SunsetWan 
/tmp/tensorflow/mnist/input_data/, in my setup, macOS Sierra 10.12.6.

**Comment by SunsetWan** [comment]
@wogong thank you very much!

**Comment by Ahmeedtraabelsi** [comment]
File "C:\Users\Ahmed\Anaconda3\lib\gzip.py", line 409, in _read_gzip_header
    raise OSError('Not a gzipped file (%r)' % magic)

OSError: Not a gzipped file (b'<h')

**Comment by galmalca** [comment]
The data exists locally on your machine, by default this data set located at `/tmp/cifar10_data`.
remove this dir and run the training step again.

**Comment by dretta** [comment]
For windows I found the corrupted files in  `C:\Users\username\.keras\datasets\fashion-mnist`

**Comment by YangGao1** [comment]
I tried your method and it succeed @vincentvanhoucke
