### ISSUE TITLE
How to run a trained model of TensorFlow object detection in Java application with GPU support with boxes output (x, y, w, h)?

### ISSUE THREAD

**Issue by Bahramudin** [tensorflow/tensorflow#17223]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Linux Ubuntu 16.04/Windows 10
- **TensorFlow installed from (source or binary)**: No
- **TensorFlow version (use command below)**: 1.5
- **Python version**:  3.5
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**: 4.8
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: NVIDIA GTX 1080 8GB
- **Exact command to reproduce**:

### Describe the problem
Here I want to ask and sure that: Is this possible to run a trained model (using python to train) in a Java application with GPU support and detect the object and get the result of matches and the x, y point and the width and height? 
I am going to use python to train my own dataset by using one of the model e.g: `ssd_mobilenet_v1_coco  `OR `faster_rcnn_resnet101_coco` and then use the trained model in the Java application with GPU support with boxes output. So I want to sure that does the TensorFlow support this task or not? If yes, is there any good tutorial to show the usage? If not, why, and when it can be supported?

Thanks in advance!!

**Comment by CarltonSemple** [comment]
See the the object detection API section for details on detection with boxes
https://github.com/tensorflow/models/blob/master/research/object_detection/README.md

**Comment by Bahramudin** [comment]
@CarltonSemple I know the link you mentioned, but you did not get the question that I asked. 
I say that: 
Is there possible to run the trained object detection API model within Java application with **GPU** support in both **Windows** and **Linux** operating systems?

I don't want a toy OR `helloword `program, I want to sure the stability and reliability in a real project.

**Comment by szaza** [comment]
Hi,
I've tried to run my demo application (https://github.com/szaza/tensorflow-java-yolo) with GPU on Linux Mint 18 with Nvidia Geforce 940MX, CUDA/CUDNN version 9.0, TensorFlow version 1.6, however I could run only on CPU until now. Theoretically, it is enough to include the `libtensorflow_jni_gpu` as dependency instead of `libtensorflow`. 
I'm still trying to get it work.
Best regards,
   Zoltan

**Comment by aselle** [comment]
It seems like if TF Java was built with CUDA support it should allow running on GPU. @asimshankar  for  verification. Also, you may find that for inference, just running on CPU is fast, especially if you are doing small batches, the latency for pipeline synch in gpu may not be worth it.

**Comment by asimshankar** [comment]
@Bahramudin : GPU on Windows isn't packaged yet (see #16660), but as @aselle said, we do support it it for Linux.

@szaza : To use GPU on Linux, your dependencies should look [like this](https://docs.google.com/presentation/d/e/2PACX-1vQ6DzxNTBrJo7K5P8t5_rBRGnyJoPUPBVOJR4ooHCwi4TlBFnIriFmI719rDNpcQzojqsV58aUqmBBx/pub?start=false&loop=false&delayms=3000&slide=id.g306175dd89_0_41). From a cursory look at [your `build.gradle`](https://github.com/szaza/tensorflow-example-java/blob/9c69b58/build.gradle), it would be a two line change:
- Change line 15 to `name: 'libtensorflow'`
- Change line 16 to `name: 'libtensorflow_jni_gpu'`

(Note the `org.tensorflow:tensorflow` artifact is a convenience one that pulls in `libtensorflow` and `libtensorflow_jni`)

Hope that helps.
Closing this since I believe the question is answered, but let me know if I'm mistaken.

**Comment by Bahramudin** [comment]
@asimshankar OK, the question almost has been answered, we hope the TensorFlow support GPU for Java on windows platform. And also I think the API for using the trained model in Java a much complex to use, I think it can be better to divide the usage into steps, like 1. load 2. calling the API for recognition 3. release resources. But now when loading we must do a lot of work, and also when doing recognition also do a lot of works, so then there is some job can incapsulate inside the API no need the user do the duplicate job. So it will be the API be handy and friendly. Thanks!

**Comment by szaza** [comment]
Thanks @asimshankar for your response, however I tried those dependencies before. As you can see the 'libtensorflow_jni_gpu' is also present in line 19, just it is commented out right now.
Unfortunately, the GPU support on Linux didn't work for me, however it can happen that my configuration is wrong.

**Comment by asimshankar** [comment]
@szaza : Note that you want to depend on *exactly one* of `libtensorflow_jni` and `libtensorflow_jni_gpu`.  Hence, I suggested replacing lines 15 and 16 (and not just uncommenting line 19).
