### ISSUE TITLE
OutOfRangeError (see above for traceback): box_index has values outside [0, batch_size)

### ISSUE THREAD

**Issue by Lancerchiang** [tensorflow/tensorflow#17288]
```
SYSTEM INFO:
OS: Ubuntu 16.04 LTS
Tensorflow version: 1.4.0
Python version: 2.7.12
```
My issue is very similar to this one here: [issue #10618](https://github.com/tensorflow/tensorflow/issues/10618)
I have been doing a multi-GPU session and I get some weird behavior from Tensorflow. 
My script only can finish its run in 1 out of 6 attempts, and in each finished execution, the result is slightly different from the single-GPU execution mode (unrepeatable error). If the execution cannot finish, most of the time it reports `OutOfRangeError (see above for traceback): box_index has values outside [0, batch_size)`
, which is not supposed to appear for tensorflow 1.4 and above, according to the issue above. 
Moreover, sometimes it would report `InternalError (see above for traceback): Blas SGEMM launch failed : m=14700, n=2048, k=1024`

Any advice would be greatly appreciated, thanks!

**Comment by angersson** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case. If you are unclear what to include  see the issue template displayed in  [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

 We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by Lancerchiang** [comment]
@angersson, I did add my platform information. In case of mistake I state here again:

SYSTEM INFO:
OS: Ubuntu 16.04 LTS
Tensorflow version: 1.4.0
Python version: 2.7.12

My code is a multi GPU session for testing in an open-sourced project [tf-faster-rcnn](https://github.com/endernewton/tf-faster-rcnn), and here is my `multi_gpu_demo.py` script.

[multi_gpu_demo.zip](https://github.com/tensorflow/tensorflow/files/1766511/multi_gpu_demo.zip)

**Comment by angersson** [comment]
Please provide all of the information listed in the [Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).
