### ISSUE TITLE
Save activation map for a specific convnet in the process of tf.train.MonitoredTrainingSession()

### ISSUE THREAD

**Issue by anbai106** [tensorflow/tensorflow#17323]
ADDING FEATURES

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 16.04
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: ('v1.4.0-19-ga52c8d9', '1.4.1')
- **Python version**:  2.7 anaconda
- **Bazel version (if compiling from source)**:
- **GCC/Compiler version (if compiling from source)**:
- **CUDA/cuDNN version**: 
- **GPU model and memory**: Quadro K400
- **Exact command to reproduce**:

### Describe the problem
I followed this tutorial from the source code of TF: **model/tutorials/image/cifar10/**, in the tutorial, you used tf.train.MonitoredTrainingSession() to log the checkpoint or tensor for future usage with TensorBoard, my question is to display the activation maps of my convnet during training process. But inside the:
`while not mon_sess.should_stop():
             mon_sess.run(train_op)`

I can not add new tensor because the Graph is finalized. So I want to ask you how to add something like **tf.summary.image**: Pass one example image to a specific convnet  after relu, and save it as png for all the filters???

I think I can easily implement this in a normal **tf.Session()**, but I am still interested if we can do it in **tf.train.MonitoredTrainingSession()**.

I think that would be great for the newbie to understand what happened for our CNN.

Thanks in advance

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(That said, to give you some hints -  you can insert summary operations in the definition of your model, for example, in the [`inference()`](https://github.com/tensorflow/models/blob/r1.6.0/tutorials/image/cifar10/cifar10.py#L188) function in the tutorial code, that builds the graph for the forward pass).

Hope that helps.
