### ISSUE TITLE
Examples and tutorial missing from pip tensorflow package

### ISSUE THREAD

**Issue by spiiph** [tensorflow/tensorflow#17351]
After searching for and eventually posting a question on StackOverflow (https://stackoverflow.com/questions/49007742/tensorflow-examples-and-tutorials-missing-from-the-pip-package) I was recommended to report this as a bug:

When installing Tensorflow (e.g. tensorflow-1.5.0-cp36-cp36m-manylinux1_x86_64.whl from https://pypi.python.org/pypi/tensorflow/1.5.0) from pip, there is only the tutorials/mnist example in tensorflow/examples. It would be nice to have the examples available without having to get them separately from GitHub. Is there a reason why the rest of the examples are not included? Can they be included in future releases?

**Comment by shivaniag** [comment]
@yifeif any comments on this?

**Comment by yifeif** [comment]
We want to keep our distribution as small as possible. As tutorials are not part of the APIs, we don't plan to include them in the standard package. `git clone` the repo would be the recommended way to get them. Hope this answer your question @spiiph.

**Comment by spiiph** [comment]
Thanks for the response.

**Comment by Bruno-Mascarenhas** [comment]
I have had a similar issue with that. To overcome this issue without downloading the whole repository, since I already installed the newest version through pip, I used SVN to download the specific part related to the examples,

For example https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples is the path to the examples folder on the github repository.

To use it with SVN, one simply replace the `tree/master` with `trunk` in the repo URL, resulting in the following command:

`svn checkout https://github.com/tensorflow/tensorflow/trunk/tensorflow/examples`
