### ISSUE TITLE
android:tensorflow_demo issue..

### ISSUE THREAD

**Issue by vusdo** [tensorflow/tensorflow#1737]
`poporo@poporo-All-Series://tensorflow/tensorflow/examples/android$ bazel build //tensorflow/examples/android:tensorflow_demo

WARNING: /tensorflow/tensorflow/core/BUILD:638:9: in srcs attribute of cc_library rule //tensorflow/core:android_tensorflow_lib_lite: please do not import '//tensorflow/core/kernels:avgpooling_op.h' directly. You should either move the file to this package or depend on an appropriate rule there.
.
.
.
INFO: Found 1 target...
WARNING: failed to create one or more convenience symlinks for prefix 'bazel-':
  cannot create symbolic link bazel-out -> /home/poporo/.cache/bazel/_bazel_poporo/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out:  /tensorflow/bazel-out (Permission denied)
  cannot create symbolic link bazel-tensorflow -> /home/poporo/.cache/bazel/_bazel_poporo/68a62076e91007a7908bc42a32e4cff9/tensorflow:  /tensorflow/bazel-tensorflow (Permission denied)
  cannot create symbolic link bazel-bin -> /home/poporo/.cache/bazel/_bazel_poporo/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-opt/bin:  /tensorflow/bazel-bin (Permission denied)
  cannot create symbolic link bazel-testlogs -> /home/poporo/.cache/bazel/_bazel_poporo/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-opt/testlogs:  /tensorflow/bazel-testlogs (Permission denied)
  cannot create symbolic link bazel-genfiles -> /home/poporo/.cache/bazel/_bazel_poporo/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/local_linux-opt/genfiles:  /tensorflow/bazel-genfiles (Permission denied).
ERROR: /tensorflow/tensorflow/examples/android/BUILD:63:1: Processing resources failed: resources_processor failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --buildToolsVersion 23.0.1 --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar ... (remaining 13 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
Error: bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /home/poporo/.cache/bazel/_bazel_poporo/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
.
.
.
.
Apr 01, 2016 10:48:05 AM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during merging resources
Error: Failed to run command:
	bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp1623410823562764165/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp1623410823562764165/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
	1
Output:
	bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /home/poporo/.cache/bazel/_bazel_poporo/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

	at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
	at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:113)
	at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
	at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
	at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:390)
	at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:321)
Caused by: com.android.ide.common.internal.LoggedErrorException: Failed to run command:
	bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/android_resources_tmp1623410823562764165/tmp-deduplicated/tensorflow/examples/android/res/drawable-hdpi/ic_launcher.png -o /tmp/android_resources_tmp1623410823562764165/merged_resources/drawable-hdpi-v4/ic_launcher.png
Error Code:
	1
Output:
	bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /home/poporo/.cache/bazel/_bazel_poporo/68a62076e91007a7908bc42a32e4cff9/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

	at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:123)
	at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:96)
	at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:58)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
	at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:139)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.359s, Critical Path: 4.34s
`

help me..

**Comment by andrewharp** [comment]
You may need to run sdk_path/tools/android and ensure that you have the 23.0.1 Android build tools installed. Alternatively, if you already have a version >= 21, you can try changing the setting in WORKSPACE and point to that.

**Comment by vusdo** [comment]
popo@popo-All-Series:~/android-sdk-linux/build-tools/23.0.1$ ls
NOTICE.txt  aidl                      bcc_compat  dx                     jack.jar  lib         mainDexClasses        mipsel-linux-android-ld  runtime.properties  split-select
aapt        arm-linux-androideabi-ld  dexdump     i686-linux-android-ld  jill.jar  llvm-rs-cc  mainDexClasses.rules  renderscript             source.properties   zipalign

----------------------------------------------------------------------------------------------------
WORKSPACE

android_sdk_repository(
    name = "androidsdk",
    api_level = 23,
    build_tools_version = "23.0.1",
    # Replace with path to Android SDK on your system
    path = "/home/poporo/android-sdk-linux",
)

android_ndk_repository(
    name="androidndk",
    path="/home/poporo/android-ndk-r10e",
    api_level=21)

help..

**Comment by andrewharp** [comment]
Have you verified that you have the 23.0.1 Android build tools installed in your SDK? You may have 23.0.2 or another version instead. You can run /home/poporo/android-sdk-linux/tools/android to double check.

**Comment by sriharrsha** [comment]
@andrewharp
 I'm also having the same issue. but I'm retraining in Google compute engine on Ubuntu 14.04

 ```
 cannot create symbolic link bazel-genfiles -> /home/developersriharsha/.cache/bazel/_bazel_developersriharsha/622942cbf
9b89fb76bd82d9602a4d614/tensorflow/bazel-out/local_linux-opt/genfiles:  /home/developersriharsha/tensorflow/tensorflow/ba
zel-genfiles (Permission denied).
```

**Comment by andrewharp** [comment]
If you can't create a bazel-genfiles link I'd suspect it's a basic Bazel installation problem. You could try doublechecking the permissions on the relevant directories and the users you installed Bazel as/are building as.
 
@damienmg Does this seem familiar to you? thanks

**Comment by damienmg** [comment]
it says it cannot write the convenience symlink. What does `ls -l /home/developersriharsha/tensorflow/tensorflow` says?

**Comment by qemb01** [comment]
I'm also having the same issue.So I try to put "ulimit -SHn 65535" into /etc/profile and run by root.But:

INFO: Found 1 target...
INFO: From Executing genrule @androidsdk//:zipalign_runner [for host]:
src/main/tools/namespace-sandbox.c:460: mount(opt->sandbox_root, opt->sandbox_root, NULL, MS_BIND | MS_NOSUID, NULL): Permission denied
ERROR: /home/eli/.cache/bazel/_bazel_root/e86f6fce5559de9e3e13fb6adb66b858/external/androidsdk/BUILD:144:2: Executing genrule @androidsdk//:zipalign_runner failed: bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped).
Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 3.985s, Critical Path: 1.41s

**Comment by damienmg** [comment]
This is a different issue which should not happens in tensorflow. Did you run ./configure?

**Comment by sriharrsha** [comment]
@damienmg 
These are the files
```
developersriharsha@instancenew:~/tensorflow/tensorflow$ ls
ACKNOWLEDGMENTS  configure        google             LICENSE    README.md   tensorflow   util
AUTHORS          CONTRIBUTING.md  ISSUE_TEMPLATE.md  navbar.md  RELEASE.md  third_party  WORKSPACE
bower.BUILD      eigen.BUILD      jpeg.BUILD         png.BUILD  six.BUILD   tools
```
developersriharsha@instancenew:~/tensorflow/tensorflow$

**Comment by damienmg** [comment]
I would like to get the output of `ls -l /home/developersriharsha/tensorflow/tensorflow` precisely (with -l) to see the permisssions

**Comment by sriharrsha** [comment]
```
developersriharsha@instancenew:~/tensorflow/tensorflow$ ls -l
total 120
-rw-r--r--  1 root root  2219 Apr  1 07:29 ACKNOWLEDGMENTS
-rw-r--r--  1 root root   313 Apr  1 07:29 AUTHORS
-rw-r--r--  1 root root 11318 Apr  1 07:29 bower.BUILD
-rwxr-xr-x  1 root root  9040 Apr  1 07:29 configure
-rw-r--r--  1 root root  1749 Apr  1 07:29 CONTRIBUTING.md
-rw-r--r--  1 root root   313 Apr  1 07:29 eigen.BUILD
drwxr-xr-x  3 root root  4096 Apr  1 07:29 google
-rw-r--r--  1 root root   940 Apr  1 07:29 ISSUE_TEMPLATE.md
-rw-r--r--  1 root root  1646 Apr  1 07:29 jpeg.BUILD
-rw-r--r--  1 root root 11416 Apr  1 07:29 LICENSE
-rw-r--r--  1 root root   396 Apr  1 07:29 navbar.md
-rw-r--r--  1 root root   999 Apr  1 07:29 png.BUILD
-rw-r--r--  1 root root  6322 Apr  1 07:29 README.md
-rw-r--r--  1 root root  6960 Apr  1 07:29 RELEASE.md
-rw-r--r--  1 root root   243 Apr  1 07:29 six.BUILD
drwxr-xr-x 13 root root  4096 Apr  1 07:29 tensorflow
drwxr-xr-x  5 root root  4096 Apr  1 07:29 third_party
drwxr-xr-x  2 root root  4096 Apr  1 07:34 tools
drwxr-xr-x  3 root root  4096 Apr  1 07:29 util
-rw-r--r--  1 root root  9631 Apr  1 07:29 WORKSPACE
```

**Comment by damienmg** [comment]
Here you are, only root can write here. "sudo chown -R developersriharsha /home/developersriharsha/tensorflow/tensorflow" should fix your issue

**Comment by sriharrsha** [comment]
Thanks ,It resolved

**Comment by qemb01** [comment]
I have run ./configure and "sudo chown -R eli /home/eli/tensorflow", but nothing is changed.

**Comment by andrewharp** [comment]
@qemb1 What target are you trying to build, and what version of Bazel are you using? Can you rerun with --verbose_failures, and then check that there are no ownership/permission/existence issues with the Android SDK binary in question?

**Comment by qemb01** [comment]
version of Bazel :bazel-0.1.4

eli@eli-VirtualBox:~/tensorflow$ bazel build //tensorflow/examples/android:tensorflow_demo

INFO: Found 1 target...

INFO: Building...


[0 / 1] BazelWorkspaceStatusAction stable-status.txt


[1 / 100] Linking google/protobuf/protoc [for host]


INFO: From Processing resources:

Error: /home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Error: /home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory
Apr 07, 2016 10:47:53 AM com.google.devtools.build.android.AndroidResourceProcessingAction main
SEVERE: Error during merging resources
Error: Failed to run command:
/home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/tmp-deduplicated941045509851047210/tensorflow/examples/android/res/drawable-mdpi/ic_launcher.png -o /home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/merged_resources/drawable-mdpi-v4/ic_launcher.png
Error Code:
1
Output:
/home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

at com.android.ide.common.res2.MergeWriter.end(MergeWriter.java:54)
at com.android.ide.common.res2.MergedResourceWriter.end(MergedResourceWriter.java:113)
at com.android.ide.common.res2.DataMerger.mergeData(DataMerger.java:291)
at com.android.ide.common.res2.ResourceMerger.mergeData(ResourceMerger.java:48)
at com.google.devtools.build.android.AndroidResourceProcessor.mergeData(AndroidResourceProcessor.java:239)
at com.google.devtools.build.android.AndroidResourceProcessingAction.main(AndroidResourceProcessingAction.java:322)
Caused by: com.android.ide.common.internal.LoggedErrorException: Failed to run command:
/home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary s -i /tmp/tmp-deduplicated941045509851047210/tensorflow/examples/android/res/drawable-mdpi/ic_launcher.png -o /home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/merged_resources/drawable-mdpi-v4/ic_launcher.png
Error Code:
1
Output:
/home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary: line 3: /home/eli/.cache/bazel/_bazel_eli/9d5da1ed772a83016cc571955005289d/tensorflow/bazel-out/host/bin/external/androidsdk/aapt_binary.runfiles/external/androidsdk/build-tools/23.0.1/aapt: No such file or directory

at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:123)
at com.android.ide.common.internal.CommandLineRunner.runCmdLine(CommandLineRunner.java:96)
at com.android.ide.common.internal.AaptCruncher.crunchPng(AaptCruncher.java:58)
at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:188)
at com.android.ide.common.res2.MergedResourceWriter$1.call(MergedResourceWriter.java:139)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)

ERROR: /home/eli/tensorflow/tensorflow/examples/android/BUILD:65:1: Processing resources failed: resources_processor failed: error executing command bazel-out/host/bin/external/bazel_tools/tools/android/resources_processor --aapt bazel-out/host/bin/external/androidsdk/aapt_binary --annotationJar external/androidsdk/tools/support/annotations.jar ... (remaining 13 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.

INFO: Building complete.


Target //tensorflow/examples/android:tensorflow_demo failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 10.953s, Critical Path: 6.29s

**Comment by andrewharp** [comment]
@qemb01 Do you have the sdk build tools 23.0.1 installed? If not, you'll need to update your WORKSPACE file to point to a version you do have. If it is already installed, check your SDK directory for ownership conflicts.

**Comment by qemb01** [comment]
@andrewharp It is useful.Thank you for the help!

**Comment by brucelau-github** [comment]
I have the same problem with bazel build either.

**Comment by andrewharp** [comment]
@brucelau-github What is the exact error you're seeing? Host OS/bazel version? Have you tried the suggestions from this thread without success?
