### ISSUE TITLE
run from script only instead of compiling with bazel?

### ISSUE THREAD

**Issue by evanthebouncy** [tensorflow/tensorflow#174]
I posted in the google discussion group but I think the turn-over rate is faster here. Hopefully I get a faster response.

In the RNN example tutorial, we're compiling the python script with bazel before executing it, instead of executing the script directory as in the simple MNIST example. Is it possible to do the RNN example purely in python script instead of using bazel? I used a binary installation instead of cloning the repo, so many of the file structures are different. I tried to hack it so I can run it from script instead of compiling with bazel, but I'm getting this error:

    $ python ptb_word_lm.py --data_path=simple-examples/data --model small
       File "ptb_word_lm.py", line 128, in __init__
       self._cost = cost = tf.reduce_sum(loss) / batch_size
       TypeError: unsupported operand type(s) for /: 'Tensor' and 'int'

Or is learning bazel the only way (which I don't mind but would like to avoid)?

**Comment by vrv** [comment]
I think some of those models aren't in our pip package yet -- building from source works for those.  We'll try to get around to fixing this soon, but for now building from source should work.

**Comment by evanthebouncy** [comment]
By that you mean I'd be using bazel to build but I can still run my experiment with a script alone right? I.e. bazel is not used for launching experiments

**Comment by ebrevdo** [comment]
The reason this won't using just the binary installed version of pip is because it relies on some additional includes not in the pip package (like reader.py in the same directory).  We didn't include the tutorials in the pip package because the package is mainly meant for modeling code.

As a hack, you could try setting your PYTHONPATH to the tensorflow/python/ subdirectory but that will probably break other things.

You can also move the python files in the ptb/ directory somewhere else, keep only the 'import tensorflow as tf' import and change the import of reader.py to 'import reader'.  That'll get you part of the way there.

**Comment by evanthebouncy** [comment]
that last bit of your suggestion is exactly what I did to get the error I'm reporting. I copied the /ptb directory and adjusted the reader.py location in the import

But I guess that's not important now. I could run and past the test scripts:
rnn_cell_test.py 
tf_rnn_test.py

does that mean at least the rnn and rnn_cell module is included in the pip package and is functional?
also, is there a tutorial to install tensorflow from source w/o GPU support?

**Comment by ebrevdo** [comment]
Yes, rnn and rnn_cell *are* included in the pip package.

To build tensorflow from source, use:
  bazel build -c opt
without the --config=cuda flag.

You can use this to build and run the build_pip_package target.  The build_pip_package will then create a binary wheel without the cuda.

This is in the tutorials.

**Comment by evanthebouncy** [comment]
I'm still having some trouble:

    tensorflow$ bazel build -c opt
    INFO: Found 0 targets...
    INFO: Elapsed time: 0.189s, Critical Path: 0.00s

sorry I don't code much at all, this is fairly challenging.

**Comment by ebrevdo** [comment]
Follow the instructions [here](http://www.tensorflow.org/get_started/os_setup.md) under the section "Create the pip package and install".  However, also pass in the flag "--config=cuda" as well as the current "-c opt" in order to build with CUDA.  Remember to run the configure script before running the bazel build.

**Comment by ebrevdo** [comment]
Ah sorry - you were not interested in having a cuda build.  Ignore my suggestion of adding "--config=cuda" and just follow the directions as they are.

**Comment by evanthebouncy** [comment]
thanks! 
It had not occured to me to look under installation direction under MacOS as I'm running ubuntu.
I think we're good for now. Thanks for being patient with me.
