### ISSUE TITLE
can we compute sparse matrix gradient in TF?

### ISSUE THREAD

**Issue by warisha** [tensorflow/tensorflow#17550]
In tensor flow (TF) , to compute gradients we have to pass some variable. Sparse tensors cannot be used as variables. Can you please tell me is there any solution for sparse matrix gradient ?
N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

(And if posting the question, I'd encourage you to add more detail - for example, a code snippet that you expect to work but doesn't. Or some more detail about what you're trying to achieve. Thanks!)
