### ISSUE TITLE
anaconda environment: install of protobuf library does not work 

### ISSUE THREAD

**Issue by roestigraben** [tensorflow/tensorflow#1755]
Hello,
I tried to install the special package of protobuf as proposed in [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#protobuf-library-related-issues). I get errors 

### Environment info
Operating System: MAC OSX Yosemite 10.10.5 (14F1713)

If installed from binary pip package, provide:

1. I use anaconda environment
2. created environment like "conda create -n tf python=2.7"
3. activated environment with "source activate tf"
4. installed easy_setup with "sudo -H curl https://bootstrap.pypa.io/ez_setup.py -o - | python"
5. installed tensorflow with "sudo -H pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.7.1-cp27-none-any.whl"
6. tested if I can import tensorflow from python. OK, no problem
7. installed protobuf by "pip install --upgrade https://storage.googleapis.com/tensorflow/mac/protobuf-3.0.0b2.post2-cp27-none-any.whl"
8. tested again if I can import tensorflow in python. NOK

terminal showed
File "/Users/peterhirt/anaconda/envs/tf1/lib/python2.7/site-packages/google/protobuf/descriptor.py", line 46, in <module>
    from google.protobuf.pyext import _message
ImportError: dlopen(/Users/peterhirt/anaconda/envs/tf1/lib/python2.7/site-packages/google/protobuf/pyext/_message.so, 2): Library not loaded: /usr/local/lib/libprotobuf.10.dylib
  Referenced from: /Users/peterhirt/anaconda/envs/tf1/lib/python2.7/site-packages/google/protobuf/pyext/_message.so
  Reason: image not found

Error importing tensorflow.  Unless you are using bazel,
you should not try to import tensorflow from its source directory;
please exit the tensorflow source tree, and relaunch your python interpreter
from there.

Repeated above flow twice in newly created envs to see if problem repeatable, yes ;-(

thanks for the help

**Comment by michaelnhw** [comment]
I encounter the same issue on OS X 10.10

**Comment by ekurutepe** [comment]
I have the same problem using `virtualenv` on El Cap as well.

**Comment by ekurutepe** [comment]
I was able to resolve this issue by getting the [C++ release](https://github.com/google/protobuf/releases/download/v3.0.0-beta-2/protobuf-cpp-3.0.0-beta-2.zip) of protobuf 3.0.0 from the release [page](https://github.com/google/protobuf/releases/tag/v3.0.0-beta-2) and building it locally by: 
```
./configure
make 
make install
```
on my machine with El Cap and Xcode 7.3 installed, this went without a hitch and produced `libprotobuf.10.dylib` under `/usr/local/lib` resolving the error when importing tensorflow in Python. 

I don't know if this problem is widespread but it's probably a good idea to update the instructions [here](https://www.tensorflow.org/versions/r0.8/get_started/os_setup.html#common-problems)

**Comment by keveman** [comment]
Sorry for the late response. But yes, you need libprotobuf installed on your machine for the C++ extension in the python package to work. I will update the instructions to reflect that.

**Comment by keveman** [comment]
Closed due to inactivity.
