### ISSUE TITLE
Leak when creating many tf.layers.Conv2D with tf.eager

### ISSUE THREAD

**Issue by matpalm** [tensorflow/tensorflow#17590]
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: 16.04.3 LTS
- **TensorFlow installed from (source or binary)**:  binary
- **TensorFlow version (use command below)**: ('v1.5.0-0-g37aa430d84', '1.5.0')
- **Python version**: Python 3.5.2
- **CUDA/cuDNN version**:  cuda-9.0 
- **GPU model and memory**: TITAN X (Pascal)

- **Exact command to reproduce**:

see gist https://gist.github.com/matpalm/93680534c5c53d6e7836d3aea1a3bbb3
for minimal reproduction. run this script and watch loop times increase.

### Describe the problem

each creation of a tf.layers.Conv2D is slower than the one before. have a project based on evolutionary algorithm that creates many instances of tf.layers.Conv2D for fitness evaluation and over time entire process slows down. it's not expected this loop should slow down.

### Source code / logs
see gist above

**Comment by matpalm** [comment]
just upgraded to `v1.6.0-0-gd2e24b6039 1.6.0` & same behaviour

**Comment by allenlavoie** [comment]
Will finish investigating on Monday. Looks like it's due to some overzealous caching.

Thank you for the excellent bug report.

**Comment by allenlavoie** [comment]
The more worrying/unexpected issues here were PyObject leaks due to missing Py_DECREFs in our C code. Those are now fixed, although some of the changes haven't synced to github yet (give them a day or so).

The main issue is that there's a bit of `variable_scope` code run by `Layer`s which means creating new `Layer`s in a loop will take quadratic time (closing a `variable_scope` is linear in the number of existing `variable_scope`s). We'll fix that eventually (potentially by removing `variable_scope` in TF2.x), but there's a relatively easy workaround in the meantime. You can either wrap your `Layer` creation in a `with tfe.EagerVariableStore().as_default():` block or reset the default graph on each iteration. This will ensure that `variable_scope` names don't build up in this dictionary.

**Comment by matpalm** [comment]
Awesome! Thanks for the work around, I'll give that a go ASAP. Do you want
me to close?

**Comment by allenlavoie** [comment]
You may want to use a build after https://github.com/tensorflow/tensorflow/commit/e2020e64360a4f9beeb48f388fb74ab1c4b1f847#diff-62c686d1c3d926dc05023a1ccd4d603c to avoid the PyObject leaks. Let me know if you run into any issues.
