### ISSUE TITLE
Error: C++ compilation of rule '@protobuf_archive//:protobuf_lite' failed

### ISSUE THREAD

**Issue by farhanhubble** [tensorflow/tensorflow#17709]
I am trying to build tensorflow inference library using the instructions [here](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/android).

------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Ubuntu 16.04.4 LTS
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**:  Master (10be1f2377bf7aad1a4cfa306277c53e44493a57)
- **Python version**: Python 3.6.3 :: Anaconda custom (64-bit)
- **Bazel version (if compiling from source)**: 0.11.1
- **GCC/Compiler version (if compiling from source)**: 5.4.0
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: Tesla K80 12GB
- **Exact command to reproduce**: ```bazel build -c opt //tensorflow/contrib/android:libtensorflow_inference.so    --crosstool_top=//external:android/crosstool    --host_crosstool_top=@bazel_tools//tools/cpp:toolchain    --cpu=armeabi-v7a --verbose_failures```

### Describe the problem
Bazel build is failing with the error `C++ compilation of rule '@protobuf_archive//:protobuf_lite' failed`.
The full error is pasted below. I have tried `bazel clean`.

### Source code / logs
```
ERROR: /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/external/protobuf_archive/BUILD:66:1: C++ compilation of rule '@protobuf_archive//:protobuf_lite' failed (Exit 1): false failed: error executing command 
  (cd /home/ubuntu/.cache/bazel/_bazel_ubuntu/ad1e09741bb4109fbc70ef8216b59ee2/execroot/org_tensorflow && \
  exec env - \
    PWD=/proc/self/cwd \
  /bin/false -MD -MF bazel-out/armeabi-v7a-opt/bin/external/protobuf_archive/_objs/protobuf_lite/external/protobuf_archive/src/google/protobuf/arena.pic.d '-frandom-seed=bazel-out/armeabi-v7a-opt/bin/external/protobuf_archive/_objs/protobuf_lite/external/protobuf_archive/src/google/protobuf/arena.pic.o' -fPIC -iquote external/protobuf_archive -iquote bazel-out/armeabi-v7a-opt/genfiles/external/protobuf_archive -iquote external/bazel_tools -iquote bazel-out/armeabi-v7a-opt/genfiles/external/bazel_tools -isystem external/protobuf_archive/src -isystem bazel-out/armeabi-v7a-opt/genfiles/external/protobuf_archive/src -isystem external/bazel_tools/tools/cpp/gcc3 -DHAVE_PTHREAD -Wall -Wwrite-strings -Woverloaded-virtual -Wno-sign-compare -Wno-unused-function -Wno-writable-strings -c external/protobuf_archive/src/google/protobuf/arena.cc -o bazel-out/armeabi-v7a-opt/bin/external/protobuf_archive/_objs/protobuf_lite/external/protobuf_archive/src/google/protobuf/arena.pic.o)
Target //tensorflow/contrib/android:libtensorflow_inference.so failed to build
INFO: Elapsed time: 3.864s, Critical Path: 0.01s
FAILED: Build did NOT complete successfully
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution

**Comment by farhanhubble** [comment]
It turns out that the issue is being caused by ndk path not being set in the WORKSPACE file (see [here](https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE)). Strangely Bazel doesn't give any hint of what's going wrong!

**Comment by farhanhubble** [comment]
It turns out that the issue is being caused by ndk path not being set in the WORKSPACE file (see [here](https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE)). Strangely Bazel doesn't give any hint of what's going wrong!

**Comment by Tvde1** [comment]
I'm getting the same error, how can I fix this? I am on master hash `b4ae85234b4f626e4aaee1d2c531a6b534712dbb`

**Comment by devimonica** [comment]
> 
> 
> It turns out that the issue is being caused by ndk path not being set in the WORKSPACE file (see [here](https://github.com/tensorflow/tensorflow/blob/master/WORKSPACE)). Strangely Bazel doesn't give any hint of what's going wrong!

**Comment by devimonica** [comment]
@farhanhubble Where exactly should we add android sdk and ndk repository information in the workspace file ?

**Comment by syw2014** [comment]
Same Error!

Platform: CentOS
GCC: 7.3.1
bazel: 3.3.1
tensorflow: master branch


WARNING: /home/projects/2-framework/tensorflow/tensorflow/core/BUILD:1750:11: in linkstatic attribute of cc_library rule //tensorflow/core:lib_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
WARNING: /home/projects/2-framework/tensorflow/tensorflow/core/BUILD:2162:16: in linkstatic attribute of cc_library rule //tensorflow/core:framework_internal: setting 'linkstatic=1' is recommended if there are no object files. Since this rule was created by the macro 'tf_cuda_library', the error might have been caused by the macro implementation
INFO: Analyzed 5 targets (0 packages loaded, 19455 targets configured).
INFO: Found 5 targets...
ERROR: /root/.cache/bazel/_bazel_root/e46112f22ffa5fec40c0ac30c24ecbbd/external/com_google_protobuf/BUILD:301:11: C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1)
gcc: error: unrecognized command line option '-std=c++14'
ERROR: /home/projects/2-framework/tensorflow/tensorflow/core/protobuf/BUILD:103:20 C++ compilation of rule '@com_google_protobuf//:protoc_lib' failed (Exit 1)
INFO: Elapsed time: 3.168s, Critical Path: 0.49s
INFO: 20 processes: 20 local.
FAILED: Build did NOT complete successfully
