### ISSUE TITLE
Does Tensorflow Lite supports LSTM?

### ISSUE THREAD

**Issue by op21beyond** [tensorflow/tensorflow#17923]
Hi, 

Tensorflow Lite does not supports tf.tanh according to [compatibility guide].(https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/tf_ops_compatibility.md). 
However tf.tanh is usually part of LSTM. 
Then, Does TF-Lite support LSTM or not? 
Does TF-Lite have compatible operator of BasicLSTMCell?

Thanks.

**Comment by Ala-Me-Da** [comment]
Turns out the 'tanh' function and the sigmoid function are related by tanh(a) = 2*sigmoid(2*a) - 1. tf.sigmoid is supported by Tensorflow Lite, so if there is no LSTM implementation we could replace tf.tanh with tf.sigmoid as needed and have one created. (Newbie to ML here, correct me if I'm wrong.)

**Comment by RoboEvangelist** [comment]
How do I replace this in my code? Is there an official release of TFLite that supports RNNs already?

**Comment by varunj** [comment]
@op21beyond @Ala-Me-Da @RoboEvangelist were any of you able to successfully port an LSTM model to TF Lite? 
If yes, could you please share the source code?
