### ISSUE TITLE
One hot embedding?

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#1799]
I'd like to embed integer labels into a fixed dimension space via the classic one-hot embedding. Here is an example:

```
onehot(inputs=[0, 2], num_labels=4) -> [[1, 0, 0, 0], [0, 0, 1, 0]]
```

It seems that sparse_to_dense does something similar, but not quite what I want. I've found some solutions online but they are rather convoluted. Is there a straightforward way to do this in tensorflow?

**Comment by drgriffis** [comment]
`sparse_to_dense` will do what you want, you just have to index your data first.  For your example, you would want
```python
inputs, num_labels = [0,2], 4
indexedInputs = [[i, inputs[i]] for i in range(len(inputs))]
tf.sparse_to_dense(indexedInputs, [len(inputs),num_labels], 1)  # produces [[1,0,0,0], [0,0,1,0]]
```

**Comment by vladfi1** [comment]
Is there any way to do this with variable-length inputs (shape=[None])?

**Comment by drgriffis** [comment]
Sure, the `tf.range` function will give you an integer range in the length of your input node, then you can reshape them both as matrices and `tf.concat` them together to get the right data matrix that you can run through `tf.sparse_to_dense`.  The documentation for those functions can help you get things set up properly.

In future, [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) is a much better place for a question like this.

**Comment by vladfi1** [comment]
I did check StackOverflow but found only convoluted answers, and I wanted to ask if there wasn't a more idiomatic way to perform this fairly ubiquitous operation. Since that doesn't appear to exist, perhaps this could be a feature request for it?

I've also tried tf.range but have encountered some errors when trying to reshape it #1801. Even so, I don't see how this would allow for variable length inputs, since tf.range needs to take a concrete limit.

**Comment by samjabrahams** [comment]
As a quick note, the [`tf.one_hot()`](https://www.tensorflow.org/versions/master/api_docs/python/array_ops.html#one_hot) method appears to be arriving in the next release of TensorFlow. I haven't checked, but it may also be available already in the nightly build- see the instructions to install it [here](https://github.com/tensorflow/tensorflow#installation)

**Comment by vladfi1** [comment]
@samjabrahams That's great, thanks for the tip!

**Comment by vladfi1** [comment]
Not a huge deal, but for some reason tf.one_hot insists on taking int64 as input - it should probably also work with the other int types. I'll just add in the cast myself for now.

**Comment by samjabrahams** [comment]
I've been taking a look at the code since this came up, and I think there's room for improvement. In addition to it needing to be more flexible, I think it makes sense for the `on_value` and `off_value` parameters to have default values of 1 and 0 (instead of forcing the user to define it by hand for these most common values).

I was thinking about modifying it myself to get some more practice with the inner workings of the software, but I'll ping @ebrevdo to see what he thinks, as he wrote the method.

**Comment by ebrevdo** [comment]
You should clarify what you mean by the improvements you'd like to make.  Regarding on/off value:

on_value and off_value must be provided to the kernel (because they're inputs, not attributes, and as such can be tensors).  It *is* reasonable to add defaults of 1 and 0 for the python wrapper.  You'll have to hide the auto-generated one_hot function in the BUILD rule for array_ops and then write your own python wrapper that calls gen_array_ops._one_hot().  to make sure that the default type is float32, you should use np.float32(0) for the off_value and np.float32(1) for the on value.

PRs welcome; happy to review.

**Comment by samjabrahams** [comment]
Thanks for getting back. I'll try to describe the improvements more precisely:

1. `on_value` / `off_value`: Like you said- create a Python wrapper that has a default value for these inputs. Thank you for the "to-do list" style overview- should make this process much smoother to go through!

2. Handling different int types for `indices` and `depth`: `indices` is required to be a Tensor of `int64`, and `depth` is required to be a Tensor of `int32`. It would be nice if the user was able to pass in any integer Tensor (or at least either `int64` or `int32`) and have the method handle it. Do you think this could be handled in the Python wrapper? The idea would be to check for an integer-type Tensor and cast it to the proper format before passing it on to the kernel. It's somewhat inefficient, but very simple.

**Comment by samjabrahams** [comment]
Also- with this changes, should I make tweaks to the OneHot definition in [ops.pbtxt](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/ops.pbtxt)?

**Comment by ebrevdo** [comment]
It's fine to use math_ops.to_int??()  as a stop gap.  ops.pbtxt is auto
updated and only depends on the c++ side, you don't have to update it.

**Comment by samjabrahams** [comment]
@vladfi1 : The one_hot() updates were recently merged into master. Would you like to test it out and see if it works well enough to close this issue?

**Comment by vladfi1** [comment]
@samjabrahams I've been using `one_hot` for a few weeks without problems. I recently reinstalled the master branch of tensorflow with `sudo pip3 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.8.0rc0-cp34-cp34m-linux_x86_64.whl` but there doesn't seem to be any update to the signature of `one_hot` - it still takes only int64 tensors and required manual on_value and off_value.

**Comment by ebrevdo** [comment]
You need to use a nightly build to see the change.

**Comment by vladfi1** [comment]
Ok, I installed the nightly build, which provides default on_value and off_value. However `one_hot` still demands `int64` for the input. If I pass in `int32` I get an error:

```
>>> tf.one_hot(tf.constant(1, dtype=tf.int32), 10)
Tensor conversion requested dtype int64 for Tensor with dtype int32: 'Tensor("Const:0", shape=(), dtype=int32)'
```

**Comment by samjabrahams** [comment]
I did some looking into this, and it looks like the error is due to using `tf.convert_to_tensor` as the way to handle different-typed tensors on [these lines](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py#L1860-L1861). This works when passing in Numpy arrays, but not with TensorFlow constants.

@ebrevdo @girving, would it be possible to import `tf.cast` in `tensorflow/python/ops/array_ops.py`? I think using that instead of `convert_to_tensor` would fix this.

**Comment by samjabrahams** [comment]
@vladfi1 `one_hot` should be compatible with indices of type `int32` and `int64`, now.

**Comment by girving** [comment]
Fixed, so closing.

**Comment by bionicles** [comment]
what do you do if the classes are strings, not ints?

**Comment by ebrevdo** [comment]
You first convert the strings to ints via one of the helper classes/functions in `tf.lookup`.  You will need to have a vocabulary in mind that maps strings to integers.
