### ISSUE TITLE
Feature Request: No U-Turn Sampler (NUTS) in tf.contrib.bayesflow

### ISSUE THREAD

**Issue by alichtl** [tensorflow/tensorflow#18003]
The NUTS sampler (http://www.jmlr.org/papers/volume15/hoffman14a/hoffman14a.pdf) would be a great addition to the HMC code already in tf.contrib.bayesflow.

A reference implementation is at: https://github.com/stan-dev/stan/blob/develop/src/stan/mcmc/hmc/nuts/base_nuts.hpp, and this has already been mentioned by @jvdillon and @dustinvtran in https://github.com/tensorflow/tensorflow/issues/4965. The HMC code has been brought over, but I don't see NUTS in there.

Is someone already working on this? Is there any way I could help?

---

Have I written custom code: No
OS Platform and Distribution: N/A
TensorFlow installed from: N/A
TensorFlow version: N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by srvasude** [comment]
Hi,
  Great question! We have some work progressing on this (and I hope we can give an update in the near future on this).

Might I ask you to close this issue, and file it again in https://github.com/tensorflow/probability? We've been focusing / moving our code and efforts in to this repo (as you might notice the HMC code has moved there), and it would be good to keep the issue tracking there (and also since this is an important feature request). 

Thanks!
  Srinivas

**Comment by alichtl** [comment]
Awesome- thanks Srinivas! I opened the issue over at https://github.com/tensorflow/probability/issues/8, and will close this one out.
