### ISSUE TITLE
Max Pooling Across Batch Dimension

### ISSUE THREAD

**Issue by johnrowlay** [tensorflow/tensorflow#1802]
I would like to use Tensor Flow to do max pooling over images. For example, with 10 images of size 500x500, this would yield a single image of size 500x500, where each pixel is the max of that pixel coordinate across the 10 images.

To do this, I tried:

    `image_pool = tf.nn.max_pool(input, ksize=[10, 1, 1, 1], strides=[10, 1, 1, 1], padding='VALID')`

Here, the ideas is that for each batch of images, every sub-batch of 10 images is pooled into a single image. However, this gives me the error message:

    `ValueError: Current implementation does not support pooling in the batch dimension.`

Therefore it appears that right now, this function is not yet supported in this way. So, firstly, it would be great if a later version would support this. And secondly, I'm wondering if there is another way to achieve what I want by using existing tools in Tensor Flow, or otherwise?

**Comment by vrv** [comment]
Easiest thing to do is to tf.split() your tensor into batches of 10, call tf.reduce_max() across each of those tensors along the batch dimension, and then concat them back together.  It sounds like you're not really looking to slide a window over the batch dimension since your kernel size is equal to your stride.
