### ISSUE TITLE
static graph vs dynamic graph

### ISSUE THREAD

**Issue by zsp1197** [tensorflow/tensorflow#18038]
since dynamic graph has so many advantages, why not tf use dynamic graph from the bey beginning? Is static graph has any advantages over the dynamic?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by nutti** [comment]
static graph can be optimized, so it has the advantage of the memory consumption and enables fast calculation.
you can also find the discussion about this in the other framework MXNet.

https://mxnet.incubator.apache.org/architecture/note_memory.html

I hope this answer gives the solution about your question

**Comment by asimshankar** [comment]
In order to keep GitHub issues focused on bugs and feature requests, I'm going to close this out.

In general though, there are many advantages of static graphs - like memory optimizations that can be applied, parallel execution of independent operations etc. Currently TensorFlow uses static by default (`tf.enable_eager_execution()` must be called explicitly or `tf.contrib.eager.py_func` must be used explicitly for dynamic graphs) and this will have to remain so for at least all 1.x versions of TensorFlow to keep with our semantic versioning guarantees.

Hope that helps. Thanks.
