### ISSUE TITLE
module 'tensorflow' has no attribute 'Variable'

### ISSUE THREAD

**Issue by SaiyaYe** [tensorflow/tensorflow#18043]
I used to install tensorflow.  But after I found that it was cpu version, I installed tensorflow-gpu and uninstalled the original tensorflow,which is the cpu version.  But when I used this module, there was something wrong, which said module 'tensorflow' had no attribute 'Variable'.  I don't know how to fix it.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by poxvoculi** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
