### ISSUE TITLE
The icon is assymetric

### ISSUE THREAD

**Issue by pH-** [tensorflow/tensorflow#182]
The icon for Tensor Flow should be fixed. The horizontal bar of T is longer on one side of the structure but the shadow shows a perfect T. The part of the bar on the right side of the structure should be one more unit long.

**Comment by vincentvanhoucke** [comment]
Exercise for the reader: finding a configuration of light sources that actually produce that shadow :)
TL;DR: we know, and you can't unsee it once you notice. I myself like to think that we're disciples of the [Wrong Theory](http://www.wired.com/2014/09/wrong-theory/) of design, but the reality is that it is this way because the asymmetric shadow just doesn't look as good.

**Comment by its2mc** [comment]
This is exactly what I thought.. :D
