### ISSUE TITLE
Saver optimistic restore

### ISSUE THREAD

**Issue by kshmelkov** [tensorflow/tensorflow#1823]
Hello,

I have a feature request about `Saver`. Is it possible to add an option to stop it from complaining about absent variables in a checkpoint? Quite often when I experiment with different architectures, I change layers between runs, but want to reuse pretrained earlier checkpoints. An option "just restore whatever you can from this checkpoint without complaining" would be very useful. Now I play with `var_list`, but find it tiring and error-prone. Another idea is to retrieve variable names from a given checkpoint, but I couldn't find API for that.

**Comment by mrry** [comment]
The `tf.train.NewCheckpointReader()` API lets you inspect a checkpoint to find out what variables it contains (it's in the nightlies at the moment, will be in 0.8).

**Comment by mrry** [comment]
I'm closing this because the `tf.train.NewCheckpointReader()` API is now in the latest version, and enables users to build this functionality in code that uses the existing Saver API.

**Comment by stepelu** [comment]
It does not seem to be documented in v0.9, where can I check this API?

**Comment by mrry** [comment]
It looks like there's no documentation for this API (indeed, it's in generated code, so there's no source code for it either). Here's a quick guide (though note that this is subject to change between versions):

* `tf.train.NewCheckpointReader(filename)`: returns a checkpoint reader for the given file. (I believe this has an auto-generated type, though it implements the same interface as [`tensorflow::checkpoint::CheckpointReader`](https://github.com/tensorflow/tensorflow/blob/b0166b8b07a0f134cea3bfbe9a55a7c9f887ba3a/tensorflow/core/util/checkpoint_reader.h), so we'll call it `CheckpointReader`.
* `CheckpointReader.has_tensor(tensor_name)`: returns `True` if a tensor with the given name is in the checkpoint, otherwise `False`.
* `CheckpointReader.get_tensor(tensor_name)`: returns a NumPy array containing the containing the value of the tensor with the given name from the checkpoint.
* `CheckpointReader.get_variable_to_shape_map()`: returns a dict mapping tensor names to lists of ints, representing the shape of the corresponding tensor in the checkpoint.

**Comment by danielgordon10** [comment]
I think it's way more user-friendly to allow new names, new shapes, and removed variables (Caffe style). This code seems to get that job done. I call it after running the global init operation.

```python
def optimistic_restore(session, save_file):
    reader = tf.train.NewCheckpointReader(save_file)
    saved_shapes = reader.get_variable_to_shape_map()
    var_names = sorted([(var.name, var.name.split(':')[0]) for var in tf.global_variables()
            if var.name.split(':')[0] in saved_shapes])
    restore_vars = []
    with tf.variable_scope('', reuse=True):
        for var_name, saved_var_name in var_names:
            curr_var = tf.get_variable(saved_var_name)
            var_shape = curr_var.get_shape().as_list()
            if var_shape == saved_shapes[saved_var_name]:
                restore_vars.append(curr_var)
    saver = tf.train.Saver(restore_vars)
    saver.restore(session, save_file)
```

**Comment by ugtony** [comment]
Thanks for @danielgordon10 's Caffe-style restore implementation. It is very useful when loading a pretrained model with network change. 

I tried the function but it doesn't work correctly for this code line

   ```curr_var = tf.get_variable(saved_var_name)```

I guess it's because the variable_scope of my networks are nested, and makes my variable names prepended (something like scope1_scope2_scope3_op:0). In this case using an empty variable_scope might be inappropriate.

```with tf.variable_scope('', reuse=True):```

Therefore, I modified the function to get the variables by their names:
```
def optimistic_restore(session, save_file, graph=tf.get_default_graph()):
    reader = tf.train.NewCheckpointReader(save_file)
    saved_shapes = reader.get_variable_to_shape_map()
    var_names = sorted([(var.name, var.name.split(':')[0]) for var in tf.global_variables()
            if var.name.split(':')[0] in saved_shapes])    
    restore_vars = []    
    for var_name, saved_var_name in var_names:            
        curr_var = graph.get_tensor_by_name(var_name)
        var_shape = curr_var.get_shape().as_list()
        if var_shape == saved_shapes[saved_var_name]:
            restore_vars.append(curr_var)
    opt_saver = tf.train.Saver(restore_vars)
    opt_saver.restore(session, save_file)
```
It seems work correctly. But I'm not very confident of the implementation. 
Maybe you can check if the logic is correct, thanks.
