### ISSUE TITLE
cannot be overwritten again on class - tensorflow

### ISSUE THREAD

**Issue by deepankar27** [tensorflow/tensorflow#18236]
Tensorflow: 1.6.0
OS: Red Hat Enterprise Linux 7

I created weights & json model using keras but when I try to load it from my code I am getting the error from tensorflow.

ValueError(operator getitem cannot be overwritten again on class <class 'tensorflow.python.framework.ops.Tensor'>.)

Initially I was loading the model from other lib & then referring it, to test I clubbed all in one place, still gets the same exception. Any idea when & why this exception occurs? Please let me know if you need any more

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
