### ISSUE TITLE
use lib static tensorflow-core.a error when build

### ISSUE THREAD

**Issue by trangtv57** [tensorflow/tensorflow#18256]
undefined reference to 'google::protobuf::internal::fixed_address_empty_string' ....
i think my program can't find lib protobuf to used. Even I have already lib protbuf.a and protobuf.so. Before i use lib tensorflow-core.a I have used lib dynamic: tensorflow_cc.so and lib tensorflow_framework.so i build with bazel, and lib protbuf.so include. I don't know ho to fix this error. Can anyone help me?
#issue using static lib tensorflow

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by trangtv57** [comment]
the  Issue about TensorFlow installed from source lib static for my program have problem.

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
