### ISSUE TITLE
How to set the truncation time series length parameter for RNN training in this example: tensorflow/tensorflow/contrib/timeseries/examples/lstm.py

### ISSUE THREAD

**Issue by MrBigmonster** [tensorflow/tensorflow#18261]
In the function of tf.contrib.timeseries.ARRegressor, we can set the input_window_size and output_window_size for building a time series forecasting model.
But in this example, we can only set the parameter of num_units of cell and num_features of input data for _LSTMModel，but we can not set the parameter of the truncation time series length in this model of TFTS.

**Comment by allenlavoie** [comment]
Please ask questions on StackOverflow instead of opening bugs. For timeseries stuff feel free to send the SO link to allenl@google.com.

But the LSTM example model does not operate on a fixed window; the same model can take any window size, like `dynamic_rnn`. You can set the truncated backprop length by setting a different window size in the input function. For `ARRegressor` the model and input function window sizes have to match for training.
