### ISSUE TITLE
SIGILL, Illegal instruction, when importing tensorflow

### ISSUE THREAD

**Issue by tgy** [tensorflow/tensorflow#18275]
I'm getting a `terminated by signal SIGILL (Illegal instruction)` when importing tensorflow.

`less /proc/cpuinfo` yields

```
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 26
model name      : Intel(R) Core(TM) i7 CPU         920  @ 2.67GHz
stepping        : 5
microcode       : 0x11
cpu MHz         : 1598.913
cache size      : 8192 KB
physical id     : 0
siblings        : 8
core id         : 0
cpu cores       : 4
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 11
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni dtes64 monitor ds_cpl vmx est tm2 ssse3 cx16 xtpr pdcm sse4_1 sse4_2 popcnt lahf_lm pti retpoline tpr_shadow vnmi flexpriority ept vpid dtherm ida
bugs            : cpu_meltdown spectre_v1 spectre_v2
bogomips        : 5331.70
clflush size    : 64
cache_alignment : 64
address sizes   : 36 bits physical, 48 bits virtual
power management:
```

Is my CPU too old to use tensorflow?

**Comment by yaroslavvb** [comment]
I don't see "avx" under "flags", so yes, that's probably that's the reason. You need tensorflow 1.5 binary, or build one yourself

**Comment by saluto** [comment]
That's not good. IMO it is a bug / faulty build and should be changed urgently in a next patch. CPU extensions that are not functionally necessary shouldn't be required for minimal installation. Could be frustrating for beginners following the simple installation instructions.

**Comment by rohan100jain** [comment]
As @yaroslavvb mentioned, from TF 1.6 onwards the pip install requires CPU's with AVX capability (https://www.tensorflow.org/install/install_sources). You can always do

pip install tensorflow==1.5
or 
pip install tensorflow-gpu==1.5

**Comment by tgy** [comment]
@rohan100jain Why does tensorflow require AVX capability from version 1.6? Why drop the support of CPUs that don't have AVX capabilities?

**Comment by saluto** [comment]
I don't get it either...
So users with older CPU are forced to use an outdated tensorflow API, probably leading to incompatible code in the future, just because AVX is required - unnecessarily! (Because building it without AVX shows that it is not really needed.) I understand that it improves performance. But in my opinion the most basic pip-installed build should target as many systems as possible. Performance aware users should use an advanced/custom build anyway. So what's the point of requiring AVX for everyone?

**Comment by ppwwyyxx** [comment]
@saluto  @tgy TensorFlow 1.6 supports CPUs without AVX capabilities. TensorFlow 1.6 did not drop support of older CPUs. The __prebuilt official binary__ of TensorFlow 1.6 does not support older CPUs. You can always build yourself on older GPUs or look for non-official binary others have built.

There are lots of options building a binary and there could be only one binary called "tensorflow==1.6.0" on pypi. So a choice has to be made. And requiring AVX is just one choice to balance speed and availability.

**Comment by saluto** [comment]
@ppwwyyxx "You can always build from source" - You should say this to people wanting a more not less advanced build. Especially because Tensorflow is also widely used among beginners.
I stay with it: For the most basic pip-build it's the wrong choice. Maybe a better compromise would be to activate AVX only for the prebuilt **GPU**-version, since this already is a performance optimized one. I think that would be a better balance of speed and availability. (I really understand and appreciate your effort for performance.)

**Comment by yaroslavvb** [comment]
The real issue is that TensorFlow binary is pre-baked with a specific architecture instruction set. This makes sense for Google internal deployments -- there's a small number of supported configurations, so it makes sense to maintain a different binary for each configuration. But it makes less sense for python ecosystem where there's a large number of hardware configurations, and pypi doesn't even support architecture specific binaries.

Other libraries like MKL and PyTorch provide a multi-instruction binary, which use dynamic dispatch to select the most efficient instructions for the architecture. cc @tatianashp

**Comment by dbl001** [comment]
I just built Tensorflow 1.8 from source on OS X 10.11.6, and it's core dumping.  
The build parameter to 'bazel' was: -march=native.
Doesn't that select options my CPU supports?  What build option(s) should I specify for an older CPU?
