### ISSUE TITLE
Using tensorflow lite invoke inference with multiple input tensors and specifying input node?

### ISSUE THREAD

**Issue by nickwhsu** [tensorflow/tensorflow#18375]
**System information**
Have I written custom code: Yes
OS Platform and Distribution: Ubuntu  16.04
TensorFlow installed from: source:Yes
TensorFlow version: 1.7.0
Python version: 3.6
Bazel version: 0.11.1
GCC/Compiler version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A

**Describe the problem**

I converted my tflite model foo.tflite with multiple input arrays flag , I got two inputs (decoded_sample_data: FLOAT32[],decoded_sample_data:1 FLOAT32[])

When invoke inference , I refer to 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/lite/g3doc/apis.md
float* input = interpreter->typed_input_tensor<float>(0)

**My question:**
Can  I assign the data to specific input node  like tensorflow mobile method
ex: 

private static final String INPUT_DATA_NAME = "decoded_sample_data:0";
private static final String SAMPLE_RATE_NAME = "decoded_sample_data:1"; inferenceInterface.feed(SAMPLE_RATE_NAME, sampleRateList);
inferenceInterface.feed(INPUT_DATA_NAME, floatInputBuffer, RECORDING_LENGTH, 1)
inferenceInterface.run(outputScoresNames);

Thank you!

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Exact command to reproduce

**Comment by bignamehyp** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by nickwhsu** [comment]
Thanks!
