### ISSUE TITLE
Could change Eigen to other blas for matrix  operation

### ISSUE THREAD

**Issue by xzy256** [tensorflow/tensorflow#18457]
As for CPU Tensorflow, matrix operation use `eigen`. Could replace it with other blases, such as openBlas, atlas,  gotoBlas et al.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xzy256** [comment]
OS :ubuntu
TensorFlow installed from TF github
TensorFlow version:1.2.0-rc1
Bazel version:0.5.0
CUDA/cuDNN version: NO
GPU model and memory: NO
I just install CPU Tensorflow. Now, i want to test the performance of using other blases  for matrix operation instead of eigen.  I don't how to do. Could you please give me some ideas?

**Comment by asimshankar** [comment]
For experimentation you may just want to change the kernel implementation to use another library. For example, change the [`MatMul` kernel](https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/core/kernels/matmul_op.cc) implementation to use another library.

The ["Adding an op"](https://www.tensorflow.org/extend/adding_an_op) guide would be a useful read to provide background on ops and kernels.

If you get more sophisticated, you could try things like what is done for Intel MKL where [a graph rewrite pass](https://github.com/tensorflow/tensorflow/blob/r1.7/tensorflow/core/graph/mkl_layout_pass.cc#L49) updates the nodes in the graph so that MKL-enabled kernels are used.

I don't believe that we (TensorFlow team) has any in-progress efforts for writing kernel implementations using the libraries you mentioned, but @tatianashp would have a more authoritative answer.

Hope that helps.

**Comment by xzy256** [comment]
`Adding an op` and `MKL-enable`  may be great. I will try.  Thanks for your attention. @asimshankar

**Comment by tatianashp** [comment]
We don't have  efforts adding support for BLAS libraries other than Eigen and MKL. [CPU performance guide](https://www.tensorflow.org/performance/performance_guide#optimizing_for_cpu)  gives instructions on how to build TensorFlow with MKL. It might be better to use the most recent released version of TensorFlow. 1.2 is quite old.

**Comment by xzy256** [comment]
ok. Thanks.

**Comment by ruthmd** [comment]
We are trying to replace Eigen with our own modified BLAS on TensorFlow for CPU to use it for the matrix multiplication. Any ideas to solve this will be helpful. Thanks in advance.

**Comment by Danliran** [comment]
is there any progress about using BLAS on Tensorflow? @ruthmd
