### ISSUE TITLE
Segfault on bad input to tf.constant.

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#18474]
One can get a segfault providing some wrong data into a `tf.constant`:

```python
>> tf.constant(tf.string, "[,]")
Segmentation fault (core dumped)
```

While `tf.constant(tf.string, "[]")` and `tf.constant(tf.string, ",")` both give the proper error (`dtype not understood`).

**Comment by yongtang** [comment]
The issue seems to be caused in:
https://github.com/tensorflow/tensorflow/blob/049dfd5e070cfa84c82eea71c6c746a70cba4a3f/tensorflow/python/framework/dtypes.py#L701

with crash happens in numpy. For example, the following will trigger a crash:
```
>>> import numpy as np
>>> np.dtype([("qint8", np.int8, 1)]) == "[,]"
Segmentation fault: 11
```

Added a PR #18481 to check the type of the `type_value` so that things like `"[,]"` is not compared.

**Comment by TimZaman** [comment]
thanks
