### ISSUE TITLE
Can not download tensorflow C libray of macOS GPU version.

### ISSUE THREAD

**Issue by Skycctw** [tensorflow/tensorflow#18485]
### Describe the problem
Can not download tensorflow c libray of macOS GPU version.

### Source code / logs
I can't download that form the link :
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-darwin-x86_64-1.7.0.tar.gz

According to https://www.tensorflow.org/install/install_c
`TF_TYPE="cpu" # Change to "gpu" for GPU support`
 `OS="linux" # Change to "darwin" for macOS`
` curl -L "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-${OS}-x86_64-1.7.0.tar.gz" |`

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
We should make this clearer on the "Install C" page, but since version 1.2 TensorFlow has not been providing GPU support on macOS.

See [release notes for 1.1.0](https://github.com/tensorflow/tensorflow/releases/tag/v1.1.0) and some [discussion on reddit](https://news.ycombinator.com/item?id=14577538).

Hope that helps.
