### ISSUE TITLE
Surprising behaviour with distributed Tensorflow

### ISSUE THREAD

**Issue by VDalibard** [tensorflow/tensorflow#1850]
Hello, I'm observing some surprising behaviour with distributed Tensorflow, in terms of performance. In short, for the exact same Graph, I get a very different performance based on the machine I connect my tf.Session to.

In my experiments, I have two machines A and B in a cluster. Machine A has a GPU with cuDNN. I declare a graph that executes the cifar10 gpu example exclusively on machine A. No operators (including the variables) are declared on machine B. I log the device placement and Tensorboard does not see any operators associated with anything other device than machine A. 

When I execute the graph, starting my session using `tf.Session("grpc://machineA:2222", ...` results in significantly better performance than using `tf.Session("grpc://machineB:2222", ...`. It is also not just a constant overhead, as I increase the batch size, the difference seems to scale linearly:

| Batch Size | Connect to machine A | Connect to machine B |
| --- | --- | --- |
| 128 | 0.19s | 0.50s |
| 256 | 0.38s | 1.00s |
| 512 | 0.74s |  1.78s |
| 1024 | 1.42s |  3.38s |

(Averaged over 10 iterations not including the first two)

When looking at the output of `top` on machine B, it does seem like python is doing some work when I connect to machine B as it averages around 30% CPU vs ~0% otherwise, but I cannot tell what that is/how to prevent it.

I am working with Tensorflow installed from source with commit ed1a947d5b306d74af24821110dc2eb2f36c038a.

**Comment by mrry** [comment]
Hi Valentin :).

So it sounds like you have three processes: a client (on machine A or B? or a third machine?), and two TensorFlow servers (one on machine A and one on machine B). If you connect to machine A and all of the ops are on machine A then all of the master<->worker traffic will be local; whereas if you connect to machine B and all of the ops are on machine A then all of the master<->worker traffic will cross the network. (I'm not sure about the client<->master traffic, because you didn't mention where the client is running. You might want to try putting the client in the same process as the machine A master, as I would expect that to give the best performance. That's the configuration we typically use for distributed TF.)

In the latter case, it's possible that 30% of machine B is being consumed by proxying RPCs between the client and machine A. You might be seeing latency because the "queue runners" that prefetch input data run sequentially and now have two network round trips per record, and you're now "I/O bound" (not actually bound by the disk, but by the steps that have to run to populate the input queues). You could try adding prefetching threads to the input pipeline to see if that improves things. (I'm assuming you're using a version of [`cifar10_multi_gpu_train.py`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/image/cifar10/cifar10_multi_gpu_train.py), so no data is being fed or fetched in each training step.)

The input pipeline "protocol" is very chatty on the network, and we've been relying on most of the interactions happening in-process. Thanks for digging into this: it might give us good motivation to improve the batching etc.!

**Comment by VDalibard** [comment]
Hi Derek! 

Thanks! That makes a lot of sense. Regarding the client location, I had tried either on machine A or B with little or no change in performance. So I had always left it on machine B so that the instructions were given from 1-hop away from the computes, although the batching may be different between client<->master and master<->worker?

I am still a little puzzled though because I just re-ran some experiments with a larger network (the second layer 64->2048 neurons) but I still get the same 2.5X ish drop in performance, even though the number of RPCs should be constant? 

Here were the results:

| Batch Size | Connect to machine A | Connect to machine B |
| --- | --- | --- |
| 128 | 2.06s | 5.26s |
| 256 | 3.76s | 10.17s |

The client was always on machine B again. It seemed like python was doing less work on `top`. I tried to change `num_preprocess_threads` in cifar10_input.py to 32 and 64 with no real change in performance.

**Comment by mrry** [comment]
That's surprising. Are you fetching anything in the call to `sess.run()` that you're measuring?

**Comment by VDalibard** [comment]
It's the train_op for the multi_gpu example. (The whole program is a slightly modified version of cifar10_multi_gpu_train.py)

**Comment by VDalibard** [comment]
Hello, just to say that I still get the same behaviour after updating to 0.8. I also had a look at the network traffic with `tcpdump` but it seemed similar in both settings. Any ideas on what could be going on?

**Comment by VDalibard** [comment]
I think what is going on is that when I connect the client to machine B, the operations of machine A don't get scheduled on the GPU. At least, I get the exact same behaviour when scheduling operations on the CPU. I wish I could make sure nothing is running on the GPU but `nvidia-smi` does not support my graphics card (GTX 780). But the behaviours do really match for multiple workloads.

I am not sure how to see why that would happen. Again, tensorboard tells me the operations are on the GPU.

**Comment by mrry** [comment]
Hmm, how are you determining that the operations are actually running on the GPU? The `cifar10_multi_gpu_train.py` example has `allow_soft_placement=True`, so there's a possibility that the code is being silently placed on the CPU instead of the GPU (not sure if that would account for the slowdown, as I'm not 100% familiar with the performance of that model, but it seems plausible). If you pass the flag `--log_device_placement=True`, what device does it show for the ops?

**Comment by VDalibard** [comment]
Indeed passing `--log_device_placement=True` shows the operations are not scheduled on the gpu. I've attached the two logs depending on which machine I use as master. ran(Machine A) has a gpu but trothy(Machine B) doesn't. Operations that should get scheduled on the gpu are under name scope `ran_gpu`.

Any idea on how I could use the gpu remotely without risking to break things with `allow_soft_placement=False`?

[from_ran.txt](https://github.com/tensorflow/tensorflow/files/223680/from_ran.txt)
[from_trothy.txt](https://github.com/tensorflow/tensorflow/files/223681/from_trothy.txt)

**Comment by mrry** [comment]
Have you installed the GPU version on both machines? I think the placer uses information about the locally registered kernels to make placement decisions, so if you connect your session to a process that only has the CPU kernels, it won't use a GPU anywhere. (This is a bit embarrassing, and we should fix it....)

**Comment by VDalibard** [comment]
Ah that makes sense! No it was only the CPU version. Will it work for me to install the GPU version without cuda on the machine?

**Comment by mrry** [comment]
I believe it should... if not, let me know and we'll have to build a workaround!

**Comment by VDalibard** [comment]
Didn't work :-( 

> bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
WARNING: Output base '/auto/homes/vd241/.cache/bazel/_bazel_vd241/bd4752ce1a8928ERROR: /local/scratch/vd241/tensorflow/third_party/gpus/cuda/BUILD:187:1: declared output 'third_party/gpus/cuda/cuda.config' is a dangling symbolic link.
ERROR: /local/scratch/vd241/tensorflow/third_party/gpus/cuda/BUILD:187:1: not all outputs were created.
ERROR: /local/scratch/vd241/tensorflow/third_party/gpus/cuda/BUILD:187:1: declared output 'third_party/gpus/cuda/cuda.config' is a dangling symbolic link.
ERROR: /local/scratch/vd241/tensorflow/third_party/gpus/cuda/BUILD:187:1: not all outputs were created.
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 37.604s, Critical Path: 6.99s

**Comment by VDalibard** [comment]
But actually, this means it shouldn't really be a problem as long as, whenever I have GPUs, my client connects to a machine with a GPU.

Thank you so much for all your help!

**Comment by wumengfei** [comment]
Hi, VDalibard：
I'm a freshman on tensorflow. Now I'm trying to establish a distributed tensorflow on two Ubuntu servers. I've used the code on tersorflow.org and ran the following codes  
`CUDA_VISIBLE_DEVICES='' python distribute.py --ps_hosts=10.105.36.225:2223 --worker_hosts=10.105.36.225:2224,10.105.32.251:2224 --job_name=ps --task_index=0` 
to setup the parameter server. And 
`CUDA_VISIBLE_DEVICES=0 python distribute.py --ps_hosts=10.105.36.225:2223 --worker_hosts=10.105.36.225:2224,10.105.32.251:2224 --job_name=worker --task_index=0` 
to create a worker node and
 `--task_index=1`
 for the other node. Whereas when I ran the last two commands, the terminal told me that 
`wmfs-MacBook-Pro-2:TensorFlow Murphy$ CUDA_VISIBLE_DEVICES=0 python distribute.py --ps_hosts=10.105.36.225:2223 --worker_hosts=10.105.36.225:2223,10.105.32.251:2224 --job_name=worker --task_index=0
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job ps -> {10.105.36.225:2223}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:206] Initialize HostPortsGrpcChannelCache for job worker -> {localhost:2223, 10.105.32.251:2224}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:202] Started server with target: grpc://localhost:2223
E0112 00:40:14.185396000 123145561804800 tcp_client_posix.c:191] failed to connect to 'ipv4:10.105.36.225:2223': timeout occurred
E0112 00:40:14.185566000 140736234132416 tcp_client_posix.c:191] failed to connect to 'ipv4:10.105.32.251:2224': timeout occurred`

So I wanna know if I need to start some kind of service on machine B?
