### ISSUE TITLE
Distributed Tensorflow:tensorflow prediction 

### ISSUE THREAD

**Issue by xiaoluojun** [tensorflow/tensorflow#18590]
I want to use many arm as tensorflow cluster to prediction.but I can't find some helpful demo or instructions about it.
In tensorflow distributed demo training we can see
Cluster = tf.train.ClusterSpec({"ps": ps_hosts, "worker": worker_hosts})
Cluster from the parameter server and worker hosts, I would like to know that the computing cluster created by the code here is only for training? What should I do if I want to create a cluster for prediction?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by xiaoluojun** [comment]
thanks for your ask,I runing tensorflow mobile_net on Raspberry Pi3 Raspbian OS according to the tutorial.I download tensorflow-1.5.0-cp35-none-linux_armv7l.whl and install tensorflow by pip.
I have a model that was trained in PC.And now I want to implement real-time prediction.but model  prediction is very slow.
So I want to use the tensorflow distributed computing approach to speed up my model prediction.
But the problem is that I can't get relevant information about tensorflow distributed prediction.
If you can give me relevant information or demo I will be very grateful. Thanks

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
