### ISSUE TITLE
Does anyone know how to make network output int instead of float?

### ISSUE THREAD

**Issue by adaxidedakaonang** [tensorflow/tensorflow#18636]
I try to use tf.round to make elements in tensor convert to int, but then I meet this error:

ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ['Tensor("conv_w_0/read:0", shape=(9, 9, 1, 64), dtype=float32)', 'Tensor("conv_b_0/read:0", shape=(64,), dtype=float32)', 'Tensor("conv_w_1/read:0", shape=(1, 1, 64, 32), dtype=float32)', 'Tensor("conv_b_1/read:0", shape=(32,), dtype=float32)', 'Tensor("conv_w_2/read:0", shape=(5, 5, 32, 1), dtype=float32)', 'Tensor("conv_b_2/read:0", shape=(1,), dtype=float32)'] and loss Tensor("Mean:0", shape=(), dtype=float32).

And this is my  code:
Loss = tf.reduce_mean(tf.nn.l2_loss(tf.round(Train_output) * Train_tao / 2 + Train_img_LR[:,6:27,6:27,:] - Train_img_HR))

I just want to transfer the elements in Train_output from float to int, Train_output is my network's output.
I have an idea is that I can add a binary_step activation to the end of my model, but I don't know how to write it, because tensor is not iterable, can anyone help me?

**Comment by adaxidedakaonang** [comment]
I try to change type to int but tensorflow says input must float.

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
