### ISSUE TITLE
TensorBoard not running correctly with TF 1.8.0-rc0

### ISSUE THREAD

**Issue by dalgu90** [tensorflow/tensorflow#18644]
Hi, I upgraded TF to 1.8.0-rc0 to use the new `tf.data.prefetch_to_device()` feature. But with this version tensorboard won't run well. Here is output when I run tensorboard.
![image](https://user-images.githubusercontent.com/13655756/38924425-e7eb7f16-4337-11e8-81a9-5b07dfcf39a1.png)
(The command was valid when I entered with TF 1.7.)
Also when I entered to the tensorboard on the browser, tensorboard page opened but no event was displayed.
![image](https://user-images.githubusercontent.com/13655756/38924904-1ec3ab3e-4339-11e8-94e3-233242a0f14b.png)

Environment info
TF version: ('v1.7.0-1569-g3970b47da5', '1.8.0-rc0')
Operating System: Ubuntu 16.04.3
Installed version of CUDA and cuDNN: CUDA 9.0 and cuDNN 7 but I guess it's not CUDA related.

The latest version of TensorBoard is still 1.7.0, so there might be a reason for the problem.

Thank you for your hard working :^)

**Comment by WenguoLi** [comment]
I also encountered the same problem!

**Comment by wookayin** [comment]
This is probably because you are using a Tensorboard of version 1.7.0, which should be fixed in its corresponding release. See tensorboard#1086 for a dispatching solution that handles both version of `_reader.GetNext()`, which might already have fixed the issue in TB 1.8.

But why TF core has changed its API? As a result, it seems that there are some kind of requirements that minor versions of TF and TB should match.

**Comment by rohan100jain** [comment]
Apologies for the backwards incompatible change that was made but following the discussion on the PR pointed out by @wookayin, this should work now. Can you confirm?

**Comment by dalgu90** [comment]
I found new version of tensorboard(tensorboard-1.8.0) is installed when I install tensorflow-gpu-1.8.0, and I works well! I think this issue can be closed!

Thanks for your hard working!
