### ISSUE TITLE
static libtensorflow.a crashed on TF_NewGraph()

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#18762]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
Master
- **Python version**: 
2.7
- **Bazel version (if compiling from source)**:
1.10
- **GCC/Compiler version (if compiling from source)**:
GCC
- **CUDA/cuDNN version**:
- **GPU model and memory**:
- **Exact command to reproduce**:

```
BUILD_ALL_ANDROID_PATH="${TF_ROOT_DIR}/tensorflow/contrib/makefile/build_all_android.sh"

CC_PREFIX=${CC_PREFIX} NDK_ROOT=${NDK_ROOT} "${BUILD_ALL_ANDROID_PATH}" \
-x "${GEN_LIBS_DIR}" \
-s "${TF_ROOT_DIR}/tensorflow/contrib/makefile/sub_makefiles/hexagon_graph_execution/Makefile.in" \
-t hexagon_graph_execution
```
I am working to create tensorflow using DSP hexagon .
I integrated into my  android application after success compilation libtensorflow-core.a library.
But on TF_NewGraph() I have crash:

output logcat:
`**graph.cc:283 Non-OK-status: status status: Not found: Op type not registered 'NoOp' in binary running on localhost. Make sure the Op and Kernel are registered in the binary running in this process**.`

Please advise how to resolve it

**Comment by karmel** [comment]
@satok16 -- taking a guess that this is something you would be able to help with?

**Comment by karmel** [comment]
It sounds like this may be a general build file question, rather than something directly related to Hexagon. This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear statement of the issue, rather than a problem that will need some debugging first.
