### ISSUE TITLE
Changing output/reaction at the moment of detection

### ISSUE THREAD

**Issue by SJRogue** [tensorflow/tensorflow#18798]
**Have I written custom code (as opposed to using a stock example script provided in TensorFlow):** No, I've followed a tutorial and haven't touched the base setup of it. https://github.com/EdjeElectronics/TensorFlow-Object-Detection-API-Tutorial-Train-Multiple-Objects-Windows-10
    **OS Platform and Distribution (e.g., Linux Ubuntu 16.04):** Windows 10
    **TensorFlow installed from (source or binary):** Source
    **TensorFlow version (use command below):** 1.5.0
    **Python version:** 3.6
    **Bazel version (if compiling from source):** Couldn't get the capture script to return this
    **GCC/Compiler version (if compiling from source):** b'unknown'
    **CUDA/cuDNN version:** 9.0 / 7.05
    **GPU model and memory:** Nvidia GeForce GTX 960M / 2Gb?
    **Exact command to reproduce:** No idea

------------------------

### Describe the problem

Hello TensorFlow and everyone else,

I was wondering where in the code we can change the output or rather, the reaction the framework has on a detected item. Quick notice: I have no prior Python experience so it's a bit difficult to go around and deduce code.

For simplicity, let's say, at the moment Tensor detects an object, i'd like to create a file. I've been looking around but can not find a structure or UML-diagram saying which code leads to which, so I have no solid idea where to begin. I'd be very greatful if any directions could be given.

Thanks in advance

### Source code / logs

N/A for this question

**Comment by jart** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
