### ISSUE TITLE
the files of events.out.tfevnts.***.net while running deep learning model

### ISSUE THREAD

**Issue by wenouyang** [tensorflow/tensorflow#18878]
Hi

During running a tensorflow model, I found that it automatically generates the file as the follows

```
events.out.tfevents.1524681518.xhl.net
events.out.tfevents.1524681541.xhl.net


```

What do these files stand for? Are there any ways to stop generating them. The files are saved along with model checkpoint file.

![capture](https://user-images.githubusercontent.com/5430158/39276576-42440a56-48af-11e8-9bed-715db940125e.JPG)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by jart** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
