### ISSUE TITLE
Tensorflow model training working slow

### ISSUE THREAD

**Issue by yash486gadhavi** [tensorflow/tensorflow#18897]
I have arond 1500 images  with 7 classes i know its less but i am rookie in machine learning and object detection. Due to technical limitation i am currently training the model  using tensorflow cpu version. the machine is taking 20 second/step. and it took 3 days to reach 11000 steps. i want to reach atleast 40000 steps.  My question is it always take that long time for training the model in tensorflow-cpu or is there some problem? please answer my question as soon as possible

I am using tensorflow-cpu version 1.5 the reason of using this version is that in tensorflow-1.7 i am getting the depracation warning and  was not able to train the model on my laptop

If i am doing something wrong please guide me 
thanking you in anticipation

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by yash486gadhavi** [comment]
Sorry there is a mistake on my end which is I am using tensorflow 1.6 I am really sorry to misguide you earlier, The tensorflow is installed from pypi tensorflow-1.6.0rc1-cp36-cp36m-win_amd64.whl package. windows 8.1  x86 64 bit. CPU model

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
