### ISSUE TITLE
Does tensorflow have 2D short time Fourier transform? 

### ISSUE THREAD

**Issue by Suakuw** [tensorflow/tensorflow#18916]
Tensorflow have tf.contrib.signal.stft which i think implements 1D stft. Can this be used fpr the 2D case?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Suakuw** [comment]
Have I written custom code: No
OS Platform and Distribution: Ubuntu 16.04
TensorFlow installed from:  NA
TensorFlow version: 1.7
Bazel version: NA
CUDA/cuDNN version: 9.0
GPU model and memory: Nvidia Titan Xp 12 Gb
Exact command to reproduce: NA

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you discover that TF is lacking such a feature, please create another issue formatted as a feature request. Thanks!
