### ISSUE TITLE
Dose Titan Xp work in Windows10?

### ISSUE THREAD

**Issue by ksho1204** [tensorflow/tensorflow#18914]
Hi i bought new GPU - Titan Xp for learning, so i set the system like below:
CPU-AMD Ryzen 51600 Six-Core Processor
GPU-Titan Xp
Tensorflow-1.5.0 GPU
CUDA-9.0
cuDNN-7.0

But i found that when the calculation begins, the data looks not stacked on GPU, so that it occurs error message.

does Titan XP work in Windows 10 to use tensorflow gpu?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by karmel** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
