### ISSUE TITLE
Broken links in C++ API documentation

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#1892]
It looks like all of the links from https://www.tensorflow.org/versions/r0.7/api_docs/cc/index.html are broken. For example, https://www.tensorflow.org/versions/r0.7/api_docs/cc/classTensor.html.

**Comment by vladfi1** [comment]
It appears that they just need to be capitalized: https://www.tensorflow.org/versions/r0.7/api_docs/cc/ClassTensor.html.

**Comment by Styrke** [comment]
I reported this in #1303, and it was fixed with #1314.

It seems like the fix would need to be backported in order to update the documentation for TF 0.7 on the website. The [documentation for TF 0.8](https://www.tensorflow.org/versions/r0.8/api_docs/cc/index.html) apparently works as it's supposed to.

**Comment by gunan** [comment]
TF 0.7 documentation has been removed, so this issue is now obsolete.
Closing.
