### ISSUE TITLE
why ldd  libtensorflow_cc.so can not find library related to tensorrt ?

### ISSUE THREAD

**Issue by sgzqc** [tensorflow/tensorflow#19076]
I have build tensorflow c++ library from source code of tensorflow1.7-release vision, but when i ldd this so, i can not find any information about tenosrrt, why? And when i configure, i have designated the TRT library's path, and i use bazel to build ,the command is like this:
bazel build --config=cuda --config=monolithic //tensorflow:libtensorflow_cc.so

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by samikama** [comment]
Hi @sgzqc, 

Right now tensorrt module behaves like a plugin and will become available to the system when you import the python module. In order to not to put it as a requirement on to the users who want to do pip install tensorflow-gpu. If you want to use TF-TRT in c++ you need to link your application to libraries produced by tensorrt package.

Sami

**Comment by samikama** [comment]
@sgzqc,

As I mentioned above, tensorflow-trt integration is designed as plugin and not linked to tensorflow library, even if you do monolithic builds.

Sami

**Comment by sgzqc** [comment]
@samikama  Thanks! If i want to use TF-TRT to do c++ inference, i should link both  two librarys as you say above?

**Comment by samikama** [comment]
Yes, you need to link against the libraries in the contrib/tensorrt as well. converters for the conversion and kernels for the ops.

**Comment by angersson** [comment]
I am closing this issue, since it's not a bug or feature request -- if you have additional installation or build issues, please ask a question on [Stack Overflow](http://stackoverflow.com/questions/tagged/tensorflow), which has more features to help everyone share problems and solutions. Thanks!

@samikama, thanks for helping out!
