### ISSUE TITLE
Run time error raised from image.random_contrast

### ISSUE THREAD

**Issue by tengerye** [tensorflow/tensorflow#1917]
### Environment info
Operating System: SUSE 64bit
Tensorflow version: 0.6.0

### Steps to reproduce
I am following the [CNN tutorial](https://www.tensorflow.org/versions/0.6.0/tutorials/deep_cnn/index.html#convolutional-neural-networks), and encounter the problem:
`E tensorflow/core/common_runtime/executor.cc:264] Executor failed to create kernel. Unimplemented: Op AdjustContrast is not available in GraphDef version 5. It has been removed in version 2. Use AdjustContrastv2 instead.`

`[[Node: adjust_contrast = AdjustContrast[T=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"](RandomCrop, random_uniform, adjust_contrast/min_value, adjust_contrast/max_value)]]`

And something like this:
`UnimplementedError: Op AdjustContrast is not available in GraphDef version 5. It has been removed in version 2. Use AdjustContrastv2 instead.`

Thank you in advance.

**Comment by martinwicke** [comment]
This error is a sign that the code used to run the graph is (much) newer than the code that generated the graph.

It seems to me you must have an older TensorFlow somewhere on the system, could you check that it's clean?

**Comment by tengerye** [comment]
Actually, I am using a server which bases on a lot of computers. And the administrators installed several versions of tensorflow as 'module', including: tensorflow/python2/gcc/0.5.0, tensorflow/python2/gcc/0.6.0, tensorflow_gpu/python2/intel/0.7.1, etc.

The module I loaded is tensorflow/python2/gcc/0.6.0 and I used the examples of tensorflow at the version 0.6.0.

**Comment by martinwicke** [comment]
I'm not sure I'll be a lot of help in this kind of situation. 

I suggest you stud your code with assertions about the tensorflow version to make sure you're on 0.7.1 when you create the graph, and then do the same when you actually run it. If you write out a graph, you can check its supported graphdef versions too, it's the versions field in `core/framework/graph.proto`, filled by `core/public/version.h`.

You should probably also consider running one of our docker containers instead of using the installed binaries (if that is possible), or at least install into a virtualenv to get at least some isolation from the rest of the versions.

I'll close this bug, I don't believe there's an indication of a bug, but please feel free to continue commenting, I will try to help out if I can.

**Comment by tengerye** [comment]
In the end, the administrator of my server helped to install newest version (0.8) of tensorflow. I tried to install on a virtualenv, but failed. I guess my problem was raised from conflict of versions of tensorflow. Thanks anyway.
