### ISSUE TITLE
Reproducibility Problem In tensorflow

### ISSUE THREAD

**Issue by sbmaruf** [tensorflow/tensorflow#19238]
If you open a GitHub issue, here is our policy:
------------------------

### System information
- **Have I written custom code - yes**:
- **google colab**:
- **google colab default notebook**:
- **'1.7.0'**:
- **Python version: '1.7.0'**: 
- **Bazel version : not applicable**:
- **GCC/Compiler version : not applicable**:
- **CUDA/cuDNN version : google colab default version**:
- **GPU model and memory : google colab's k80 gpu**:
- **Exact command to reproduce : code given**:

https://colab.research.google.com/drive/1KXAa4OVXht0ZhfN73u5AqqfYKM2uqvN8#scrollTo=gtSwh3KykmxG

I see some problem regarding Reproducibility of result. Here I have given a notebook. Each of the cell  contains same code with same seed of tensorflow except that in the middle cell contains only single placeholder extra that has nothing to do with the graph input. But I don't know why random number generation is different for just declaring a single placeholder extra. Is that an expected behavior?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
OS Platform and Distribution
TensorFlow installed from
TensorFlow version

**Comment by jart** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
