### ISSUE TITLE
Can't import interpreter from tensorflow.contrib.lite.python 

### ISSUE THREAD

**Issue by chenlh14** [tensorflow/tensorflow#19319]
![image](https://user-images.githubusercontent.com/22855898/40106717-0ef62cda-5929-11e8-806e-8e0ed2b14254.png)
tensorflow 1.8.0
tensorflow.contrib.lite has no attribute 'python', thus it's impossible to import interpreter from tensorflow.contrib.lite.python, which is in your tensorflow/tensorflow/contrib/lite/python/interpreter_test.py

**Comment by BerteADA** [comment]
I also have an issue importing the interpreter
Have I written custom code: No
OS Platform and Distribution: Android
TensorFlow installed from: Android Studio
TensorFlow version: Latest as of today
Bazel version: N/A
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
![image](https://user-images.githubusercontent.com/13137905/40168204-cbbd3912-59ba-11e8-88de-77c21bbace43.png)

**Comment by robieta** [comment]
This is intentional. Basically only what you see in `dir(tf.contrib.lite)` is supported. The reason that you can't import from the python subdirectory is that it has been intentionally sealed off from direct imports to prevent users from getting themselves into trouble by directly importing low level functions. (This is a very common pattern in TensorFlow.)

Why are you trying to import interpreter in the first place?

**Comment by chenlh14** [comment]
I want to load my .tflite model and run the inference.
How can I do?

**Comment by robieta** [comment]
I would start here. https://github.com/tensorflow/tensorflow/tree/master/tensorflow/docs_src/mobile/tflite

**Comment by lcxywfe** [comment]
model = tf.contrib.lite.Interpreter(model_path="test.tflite")
It works now.
