### ISSUE TITLE
Idea: support dictionary fetches with tf.Session.run()

### ISSUE THREAD

**Issue by Styrke** [tensorflow/tensorflow#1941]
# The Idea

The [`tf.Session.run()` method](https://www.tensorflow.org/versions/r0.8/api_docs/python/client.html#Session.run), currently supports taking either a _single graph element_, or _a list of graph elements_ as input for the `fetches` argument, and will return either a single value or a list of values correspondingly.

**I propose adding support for using a dictionary as input for the fetch argument**, and receiving a corresponding dictionary as the return value.

Using dictionaries has at least two advantages compared to lists:
1. It will make the code **more readable**, and keys are easier to remember than indices. In the following example the return value of the loss can be accessed as `result['loss']` instead of `result[2]`.
   
   ``` python
   fetches = {
   'train_op': train_op,
   'accuracy': accuracy,
   'loss': loss
   }
   
   result = sess.run(fetches, feed_dict)
   
   print(result['loss'], result['accuracy'])
   ```
2. It will be much **easier to only fetch certain elements on flexible schedules**.
   
   For example i might want to fetch summaries for TensorBoard every 20 iterations while only fetching the loss printing to the console every 50 iterations.
   
   That means that the return value would be a list that sometimes have none of the extra elements, sometimes one of them, and sometimes both. As a consequence the index in the returned list that contains the loss might vary from one run to the next, and I would have to build extra logic to handle this.
   
   With dictionaries the key doesn't change depending on other elements in the dict, so it would be possible to do something like saving summaries without even knowing the schedule:
   
   ``` python
   if 'summaries' in result:
       writer.add_summary(result['summaries'], i)
   ```
# Implementation

I have recently been emulating the proposed behavior in a project using using the following wrapper function to translate from dictionary to list and back.

I suspect that it wouldn't be hard to do something similar in [tensorflow/python/client/session.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/session.py) perhaps as part of [_process_fetches()](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/session.py#L455), but I didn't want to spend a lot of time on it before asking.

``` python
def run(session, fetches, feed_dict):
    """Wrapper for making Session.run() more user friendly.

    With this function, fetches can be either a list or a dictionary.

    If fetches is a list, this function will behave like
    tf.session.run() and return a list in the same order as well. If
    fetches is a dict then this function will also return a dict where
    the returned values are associated with the corresponding keys from
    the fetches dict.

    Keyword arguments:
    session -- An open TensorFlow session.
    fetches -- A list or dict of ops to fetch.
    feed_dict -- The dict of values to feed to the computation graph.
    """
    if isinstance(fetches, dict):
        keys, values = fetches.keys(), list(fetches.values())
        res = session.run(values, feed_dict)
        return {key: value for key, value in zip(keys, res)}
    else:
        return session.run(fetches, feed_dict)
```
# Questions
- Is this a bad idea for some reason I don't realize? Or maybe I just overlooked some disadvantages that are worth considering?
- Why stop at dictionaries? What about tuples, nested dictionaries, or dictionaries containing lists of elements?
- General comments and thoughts?

**Comment by yaroslavvb** [comment]
A similar syntactic sugar with current implementation is to do this:
`loss, accuracy = sess.run(fetches, feed_dict)`

Current approach is more familiar for people coming to TensorFlow from Theano since Theano object also returns a list rather than dictionary.

The biggest problem though is that this change is going to break code of thousands of people who are using "session.run" and treating the result as a list.

It might be better to create a different interface on top of TensorFlow, like Keras, PrettyTensor, tf.train

**Comment by Styrke** [comment]
@yaroslavvb If you look at my wrapper function you'll see that it can be fully backwards compatible.
If `fetches` is a list then the return value should of course still be a list.
If `fetches` is a dictionary then the return value should be a dictionary instead.

**Comment by yaroslavvb** [comment]
OK, good point, it does seem mostly backward compatible. Could this be done as an object on top of TF? As you mention, one may want to extend it to tuples, nested dictionaries, or dictionaries containing lists of elements, so that's additional changes to the core TF. Also, maybe asking for "isinstance(dict)" is too restrictive, instead you might want to follow the spirit of duck-typing and accept any object that is dictionary-like

Maybe a way to go is to have a thin wrapper like "EasySession" or something like this on top, and if it gets traction, then people can switch over to using it rather than the old run interface. In general, changes to core interface may break tests in unexpected ways an require some work to get integrated. For instance, there may be some code which feeds in a `dict` into session.run already and expects it to fail (it may seem like a stretch, but I have seen similar scenarios)

**Comment by Styrke** [comment]
> Could this be done as an object on top of TF?
> [...]
> Maybe a way to go is to have a thin wrapper like "EasySession" or something like this on top, and if it gets traction, then people can switch over to using it rather than the old run interface.

I assume that you are talking about (at least initially) implementing it as a subclass that can be used as e.g. `tf.EasySession` or `tf.contrib.Session` instead of `tf.Session`?

> As you mention, one may want to extend it to tuples, nested dictionaries, or dictionaries containing lists of elements, so that's additional changes to the core TF. Also, maybe asking for "isinstance(dict)" is too restrictive, instead you might want to follow the spirit of duck-typing and accept any object that is dictionary-like.

Yes, you're right. The `run()` function I shared above was only made to cover my own basic needs and serve as an example.

For something like this to be more general I am currently thinking that it could maybe accept any python object that is an iterable container, and its return value should have the same structure. I don't know yet if that's possible, or necessary, or even worth it at all. I think my own needs would be covered if it just works with both lists and dictionaries.

> In general, changes to core interface may break tests in unexpected ways and require some work to get integrated. For instance, there may be some code which feeds in a dict into session.run already and expects it to fail (it may seem like a stretch, but I have seen similar scenarios)

Sure, even the most (seemingly) trivial assumptions can turn out to be wrong, and especially for essential functionality that is used all the time like `tf.Session` it is a good policy to be extra cautious.

Ideally the implementation should of course be fully backwards compatible so it can be included in the main `tf.Session` class.

**Comment by girving** [comment]
The dictionary thing sounds like a good plan.  I don't think we need to add support for all possible types.  Dict support would have prevented a crazy workaround in my current code.

@Styrke: I'd welcome a PR if you're still interested (I'll mark this as contributions welcome).

**Comment by Styrke** [comment]
Cool! I will try to code up a proper implementation.

**Comment by yaroslavvb** [comment]
BTW, you can do something like this using a wrapper around `session.run`, here's an example -- https://gist.github.com/yaroslavvb/973862f62f35f174a4e8942bd7bd022e

**Comment by vladfi1** [comment]
I think this has been supported for quite some time now.

**Comment by girving** [comment]
Yep, it was added by 1ac30d53e512ee40413a210d57fd1d56e510f4cb.

**Comment by psxpa3** [comment]
Howdy!!

Can anyone please help me out in resolving this error. Have been trying resolving it for such a long time.
Seems, Keras is literally made for a good reason since tensor flow kills time. Any help would be highly appreaciated.

Here I am trying to convert x4 (tf.tensor object -- intermediate layer from Keras model) into numpy array so I can perform some operation on it as highlighted in the section "A" below. I tried almost everything that is mentioned on the internet, but to avail.

**The code snippet is as below:**

print("x4: ", x4) <<--- here x4 is the output of any intermediate layer from model built using keras.
    with tf.Session() as sess:
      print("sess: ", sess)
      arr = x4.eval(sess)
      #arr = sess.run(x4)
      
      print("arr: ", arr)
      print("len(arr): ", len(arr))
      
==== A =====
      for x_axis in range(len(arr)):
        if arr[x_axis] < 0.35:
          rg_train[x_axis]=a1*np.exp(-b1*np.exp(-c1*(11*(arr[x_axis]+0.6-0.13)-5)))
        else:
          rg_train[x_axis]=a*np.exp(-b*np.exp(-c*(11*(arr[x_axis]-0.13)-5)))+0.5  
      return rg_train
==== A ====

**The error log is:**
/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/nest.pyc in flatten_dict_items(dictionary)
    214   """
    215   if not isinstance(dictionary, dict):
--> 216     raise TypeError("input must be a dictionary")
    217   flat_dictionary = {}
    218   for i, v in _six.iteritems(dictionary):

TypeError: input must be a dictionary

** When I feed a dictionary into it then it says placeholder shoudl be fed, when I do that then it gives me some another error. really fed up with this issue **

Regards,
Priya Arora
