### ISSUE TITLE
libpng compiled without VSX option (for IBM Power8)

### ISSUE THREAD

**Issue by cristianomalossi** [tensorflow/tensorflow#19466]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: RHEL75
- **TensorFlow installed from (source or binary)**: Source
- **TensorFlow version (use command below)**: 1.7.1
- **Python version**:  Python 3.5.4+ (default, Jan  9 2018, 16:01:00)
- **Bazel version (if compiling from source)**: 0.13.0
- **GCC/Compiler version (if compiling from source)**: GCC 6.4.1
- **CUDA/cuDNN version**: 9.2/7.1.3
- **GPU model and memory**: P100 Nvidia
- **Exact command to reproduce**: import tensorflow

### Describe the problem
Compiling from source TF on IBM Power8 (ppc64le) leads to a problem with libpng. 
By default, TF download and get it's own libpng. This however lacks VSX symbols inside. To add those symbols libpng should be compiled with the following flags:

```
./configure --enable-powerpc-vsx --enable-hardware-optimizations
```

otherwise it leads to the following error when importing tensorflow:

```ImportError: /hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: png_init_filter_functions_vsx```

I think the `third_party/png.BUILD` file needs to be updated accordingly, but I do not have experience with bazel to do that myself.

Could you please solve this?

### Source code / logs
```> python3
Python 3.5.4+ (default, Jan  9 2018, 16:01:00)
[GCC 6.4.1 20170720 (Advance-Toolchain-at10.0) IBM AT 10 branch, based on subve on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/at10.0/lib64/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/at10.0/lib64/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: png_init_filter_functions_vsx

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *  # pylint: disable=redefined-builtin
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/opt/at10.0/lib64/python3.5/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/opt/at10.0/lib64/python3.5/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: /hpc_modules/at10.0-based/deeplearning/tensorflow/tensorflow-v1.7.1_openmpi-3.0.1/lib64/python3.5/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so: undefined symbol: png_init_filter_functions_vsx


Failed to load the native TensorFlow runtime.```

**Comment by maxwellc-dal** [comment]
My preliminary comment is that we need to ask for https://github.com/glennrp/libpng/blob/libpng16/scripts/pnglibconf.h.prebuilt to be updated with
+ #define PNG_POWERPC_VSX_OPT 2
or
< /*#undef PNG_POWERPC_VSX_CHECK_SUPPORTED*/
> #define PNG_POWERPC_VSX_CHECK_SUPPORTED

But I am not sure about the propagation of that git repo into https://mirror.bazel.build/github.com/glennrp/libpng/archive/v1.6.34.tar.gz

In the mean time, I am trying out updating tensorflow/workspace.bzl to swap out the mirror.bazel... link to a local one with updated scripts/pnglibconf.h.prebuilt to see if that resolves it.   I will get back to you with the results.   (Just to be clear, I am as much a tourist to the TF and Bazel projects as you, but have almost the same environment.  So if there any TF project/Bazel natives that want to chime in, you will be much more competent at commenting on the unintended consequences of this proposed change on the x64 world or style points on the modifications to the Bazel workspace.)   Anyway I will get back to you with the results of my experiment, but in the mean time if I ultimately fail, this might give you another guidepost to follow on your setup.

By the way, I am getting stalled during the compilation rather than at the python import, but it is on the same symbol so I think we are on the same road and any solutions one of us has is likely to the helpful to the other.

**Comment by cristianomalossi** [comment]
Thank you for the help! I really look forward for the results of your experiments.

With respect to my tests one clarification. I also had the issue during compilation, and I solved it with a trick: I implemented a short script that runs in the background during the installation, and swap the libpng.a file generated by tensorflow with mine. 

```
# TRY TO FIX LIBPNG
MONITORDIR=$install_path/tensorflow-git/bazel-out/ppc-py3-opt/bin/external/png_archive/

rm -rf $MONITORDIR/libpng.a
while [ ! -f $MONITORDIR/libpng.a ]
do
    sleep 1
done
``` 

This helps during compilation, however during execution I end up with similar issue as with 1.7.1. So I believe that somewhere else the wrong libpng is still linked...

**Comment by maxwellc-dal** [comment]
Ok, so here are two quick-and-dirty patches that should make it go.   (It appeared to get TF 1.8 going, but I am still not sure because we wanted it for Magenta, and we do not yet have that going, so can't be sure the stuff underneath is not messed.) 

Version 1 replaces the glennrp git repo with my git repo having applied the minor patching.   However, after all my fiddling, I applied that patch via the existing patch anyway, so version 2 ("gentler") just pulls the libpng from glennrp and does the patch on the fly.   Version 1 is the current state of my build repo, but Version 2 should be sufficient, I have just not wiped my repo and built again.


[tf-ppc64le.patch.txt](https://github.com/tensorflow/tensorflow/files/2037085/tf-ppc64le.patch.txt)
[tf-ppc64le-gentler.patch.txt](https://github.com/tensorflow/tensorflow/files/2037088/tf-ppc64le-gentler.patch.txt)

I am still trying to figure out if there is a way of getting Bazel to do what configure and CMake can do where they decided what defines and files to include into the project depending on what platform we are on.   Until I can get that, I suspect we can not apply this to the main tree without breaking x64 compiles.

**Comment by martinwicke** [comment]
Can we check whether #19291 has fixed this? 

@maxwellc-dal, once libpng is updated upstream and a new release is available, we can mirror a new version.

**Comment by maxwellc-dal** [comment]
Confirming #19291 resolves the problem in my build environment also.

**Comment by martinwicke** [comment]
Ok, I will close this then. Thank you!
