### ISSUE TITLE
How to link tensorflow contrib module in C API

### ISSUE THREAD

**Issue by thefiddler** [tensorflow/tensorflow#19536]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 x64
- **TensorFlow installed from (source or binary)**: Binary wheel (tensorflow-gpu)
- **TensorFlow version (use command below)**: 1.8.0
- **Python version**: Python 3.6
- **Bazel version (if compiling from source)**: -
- **GCC/Compiler version (if compiling from source)**: -
- **CUDA/cuDNN version**: 9.0/7.0
- **GPU model and memory**: 1080 GTX / 8GB
- **Exact command to reproduce**: -

----------------

Using python, I have built a graph that relies on tensorflow.contrib.resampler and exported it to a .pb file. I am able to correctly import and execute that graph in python, by adding the following lines to my script:
    import tensorflow as tf
    tf.contrib.resampler

However, when I try to import and execute that graph in plain C (c_api.h), I get the following error:
    Failed to process frame with No OpKernel was registered to support Op 'Resampler' with these attrs.
    Registered devices: [CPU,GPU], Registered kernels: <no registered kernels>

What is the correct way to register this op and use it in the C API? I have not been able to find any relevant documentation on the matter.

**Comment by asimshankar** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

That said, see [this particular StackOverflow answer](https://stackoverflow.com/a/47277367). The equivalent to `TensorFlow.loadLibrary()` in Java mentioned there is [`TF_LoadLibrary`](https://github.com/tensorflow/tensorflow/blob/3b85959a57ef2656cdcf2cfac62d68713948ba54/tensorflow/c/c_api.h#L1526) in the C API.

Hope that helps.
