### ISSUE TITLE
No module named 'sparse_dot_topn

### ISSUE THREAD

**Issue by mas24** [tensorflow/tensorflow#19669]
Hello all, trying to install the "sparse_dot_topn" package in python using pip install sparse_dot_topn in my mac terminal but failing.How else can i go about this?

**Comment by Culeshovi** [comment]
Try building it. https://github.com/ing-bank/sparse_dot_topn

**Comment by reedwm** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by gtarasconi** [comment]
Within Mac anvironment you can download the wheel for:
https://pypi.org/project/sparse-dot-topn/
