### ISSUE TITLE
how to train models on different GPUs in parallel?

### ISSUE THREAD

**Issue by githubgsq** [tensorflow/tensorflow#19672]
hi, all:
    How to train different models on different GPUs in parallel? For example, gpu_0 is responsible for model_0 and gpu_1 is for model_1
    I tried this way:
    with tf.device('/gpu:0'):
         op_0
    with tf.device('/gpu:1'):
         op_1
    but it seems that the models are trained in sequential order, because each time only one GPU-Util info is printed.
    Any advice please?
    Thanks :)

**Comment by achalshah20** [comment]
Yeah. but if op_1 is dependent upon op_0 then it's gonna run in sequential. Make sure your model is not dependent upon each to achieve your goal.

**Comment by githubgsq** [comment]
thanks @achalshah20 I would check the dependencies again

**Comment by bignamehyp** [comment]
You can create a staging area. See https://www.tensorflow.org/performance/performance_models#software_pipelining for example

This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
