### ISSUE TITLE
Android Picture improves image clarity and cannot be used

### ISSUE THREAD

**Issue by zhongmengfeng** [tensorflow/tensorflow#19738]
![image](https://user-images.githubusercontent.com/19525589/40902335-464f0a12-6806-11e8-933c-bb668e56affa.png)

I got a picture of the current TF input and saw that the resolution is not high. I tried to change to an HD picture, but

![image](https://user-images.githubusercontent.com/19525589/40902543-e17d1b28-6806-11e8-8d3c-4b84a09d0f7d.png)
After the modification, I could not identify it. I would like to ask about the definition of the image at the time of design. Can't modify and use the high-resolution graphics?

**Comment by zhongmengfeng** [comment]
![image](https://user-images.githubusercontent.com/19525589/40902890-1e69e9f2-6808-11e8-91f1-2e0c76ac8a61.png)
after edited bitmap code

**Comment by angersson** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
