### ISSUE TITLE
Unclear what parallel_iterations does in While/scan (docs issue, possible functional_ops issue)

### ISSUE THREAD

**Issue by lahwran** [tensorflow/tensorflow#1984]
It's unclear from both the code and documentation why scan() defaults to 10 parallel iterations. doesn't that cause it to sometimes run the function before the accumulated value is available? I also poked around and read the documentation for While, and that didn't clear things up. Things it looks like it might do:
- Run steps in parallel if and only if there are no graph dependencies on the last step
- Run steps in parallel but provide nonsense values for graph dependencies on the last step
- Ignore it because the parameter doesn't do anything yet?
- Do magic beyond my ken to skip ahead in serial computations? if so, can I tell it to only run the last one, thereby creating a halting oracle?
### Steps to reproduce
1. read the docs in master for scan() and while()
2. read the code for functional_ops.scan()
3. compare to the code for functional_ops.map_fn()
4. be confused that scan() appears to get the right answer when you use it

**Comment by yuanbyu** [comment]
scan is defined in terms of while_loop.  So I will try to answer your question using while_loop. 

while_loop implements non-strict semantics.  An iteration can start as soon as one of the ops for this iteration is ready (i.e., all its inputs are available.) for execution.  So a while_loop can easily have multiple iterations running in parallel.  For example, for scan, even if the accumulated value is not available in a step, the step can still start and execute any ops that don't depend on the accumulated value. One problem to allow multiple iterations to run in parallel is resource management. parallel_iterations is introduced to give users some control of memory consumption and execution order. 

For *correct* programs, a while_loop should compute the same value for any value of parallel_iterations >= 1.

**Comment by vrv** [comment]
@yuanbyu: can you document this somewhere in control_flow_ops.py ?

**Comment by yuanbyu** [comment]
I will. But let us first see if it clears up the question(s) by lahwran@.

**Comment by lahwran** [comment]
It does, and that's an impressively more fine-grained parallelism implementation than I expected. Cool!

**Comment by yuanbyu** [comment]
Thanks. Added some more documentations.

**Comment by mholzel** [comment]
@yuanbyu I believe your comment should be directly put into the documentation. Specifically, 

> while_loop implements non-strict semantics. An iteration can start as soon as one of the ops for this iteration is ready (i.e., all its inputs are available.) for execution. So a while_loop can easily have multiple iterations running in parallel.  

However, I think you meant to say "(i.e., NOT all its inputs are available.)". 

Also, it would be useful to know if these semantics depend on the order of the inputs or not.  For instance, suppose we want to run some function `f(x)` 10 times. If the argument order is important for  non-strict semantics, then the first example cannot run in parallel because the iteration counter is holding everything up, while the second version should indeed run in parallel:

```
i = tf.constant(0) 
x = ... 
cond1 = lambda i, x: tf.less(i, 10) 
def body1(i, x):
       y = f(x)
       return i+1, y  
tf.while_loop(cond1, body1, [i, x])

cond2 = lambda x,i: tf.less(i, 10) 
def body2(x,i):
       y = f(x)
       return y, i+1
tf.while_loop(cond2, body2, [x,i])

```
r = tf.while_loop(c, b, [i])

**Comment by michaelisard** [comment]
Right, "all its inputs" means "all the Op's inputs" not "all the loop's inputs". Would you like to submit a PR to incorporate the comment in the doc in a way that you think is going to comprehensible? Sometimes it's hard to tell from inside the codebase :/

**Comment by mholzel** [comment]
I could do the PR, but I still do not understand this completely myself....

I think the docs should be updated with a MWE to illustrate exactly what is going on. If you have a good example which demonstrates good vs bad practice, I would appreciate it. Particularly, I think the docs need to have an example that illustrates the "gotchas" here, that is, the innocuous things that might be slowing down the ability to parallelize the loop. 

For instance, a "while loop" written to emulate the behavior of a "for loop" will have an internal counter. Will that counter limit tensorflow's ability to parallelize the loop? 
Example:

```
i = tf.constant(0) 
x = ... 
cond_ix = lambda i, x: tf.less(i, 10) 

def body1(i, x):
       y = f(x)
       return i+1, y  
tf.while_loop(cond_ix, body1, [i, x])
```

A fundamental question that I cannot tease out of your statements is whether more than one call to `body1(x)` can run in parallel?

**Comment by michaelisard** [comment]
Let's take the limiting case where parallel_iterations is infinity. Now, if you imagine unrolling the whole loop as a dataflow graph, then the graph will just execute according to its data dependencies.

So in your example, there can't be two instances of `y` running in parallel, because `y`'s input in step `i+1` is the output of `y` in step `i`. Likewise, there can't be two instances of `i+1` running in parallel for the same reason.

However, if `f(.)` is slow, all the `i+1` ops will run ahead to completion without waiting for even the `f(.)` in the first iteration to complete, because there's no dependency of `f` that's needed to compute the next `i`.

If you had said
```
i = tf.constant(0) 
x = ... 
cond_ix = lambda i, x: tf.less(i, 10) 

def body1(i, x):
       y = g(i)
       return i+1, y  
tf.while_loop(cond_ix, body1, [i, x])
```
then if `g` were slow you could easily end up with `g(0)`, `g(1)`, ..., `g(9)` all running in parallel because there's no dependency on the output of `g(0)` that is needed to start `g(1)`.

**Comment by mholzel** [comment]
Excellent example and discussion. Precisely along the lines of what should be in the docs.

**Comment by tatianashp** [comment]
@mholzel Would you be interested in doing PR based on the information in the above reply from @michaelisard? If you do it'd be very helpful!

**Comment by mholzel** [comment]
Yes. But this week is very busy. I will try to get to it next week.

**Comment by tatianashp** [comment]
Thank you! We are looking forward to your PR.

**Comment by Hoeze** [comment]
Is there a way to tell while_loop: "Use as much parallelism as you want"?
I tried `parallel_iterations=np.iinfo(np.int).max` which worked until TF 1.9, but now breaks.

**Comment by michaelisard** [comment]
@ebrevdo any idea? (Reopening since this is being worked on: we can close when the PR is donw.)

**Comment by tensorflowbutler** [comment]
Please remove the assignee, as this issue is inviting external contributions. Otherwise, remove the `contributions welcome` label. Thank you.

**Comment by ebrevdo** [comment]
100 is a safe number

**Comment by harshini-gadige** [comment]
@mholzel Hi, any update on the PR you are working on ? Could you please reference the PR# if you've created.

**Comment by lamberta** [comment]
I think this is obsolete?

**Comment by alexeytochin** [comment]
> michaelisard

Does it works on CPU only or also on GPU?
