### ISSUE TITLE
using tf.contrib.model_pruning. but how to save pruning model??

### ISSUE THREAD

**Issue by Cbird-coder** [tensorflow/tensorflow#19861]
I run the demo of model_pruning module. I got the following:
```
-rw-r--r--  1 Jeff  staff    81B  6  8 21:47 checkpoint
-rw-r--r--  1 Jeff   staff   1.3M  6  8 21:48 events.out.tfevents.1528465664.MacBook-Pro.local
-rw-r--r--  1 Jeff   staff   790K  6  8 21:47 graph.pbtxt
-rw-r--r--  1 Jeff   staff   4.1M  6  8 21:47 model.ckpt-100000.data-00000-of-00002
-rw-r--r--  1 Jeff   staff   8.2M  6  8 21:47 model.ckpt-100000.data-00001-of-00002
-rw-r--r--  1 Jeff   staff   1.6K  6  8 21:47 model.ckpt-100000.index
-rw-r--r--  1 Jeff   staff   365K  6  8 21:47 model.ckpt-100000.meta
```
but I did not get the pruning model?? Dose the model_pruning module work??

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by drpngx** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by jiarenyf** [comment]
Asking here is useless, no one will answer you question, very angry ...

**Comment by jiarenyf** [comment]
Asking here is useless, no one will answer you question , very angry ...
