### ISSUE TITLE
saving tensorflow models in hdf5

### ISSUE THREAD

**Issue by raghavgurbaxani** [tensorflow/tensorflow#19886]
Hi Everyone

While using tensorflow, how to save the model in hdf5 file format (like keras does using model.save) .  

Most of the documentation I found online is for saving models in tensorflow with a checkpoint using saver.save

While trying 
tf.keras.models.save_model('model.h5',filepath='Desktop/')
in my mnist code in tensorflow, I get the following error

OSError: Unable to create file (unable to open file: name = 'Desktop/', errno = 22, error message = 'Invalid argument', flags = 13, o_flags = 302)

**Comment by anj-s** [comment]
raghavgurbaxani@ the first argument to save_model is the model instance itself and the second argument (i.e "filepath" parameter) is the path where you want to save the file, e.g: "Desktop/model.h5".  [Here](https://github.com/keras-team/keras/blob/master/keras/engine/saving.py#L26) is a link to where the call is defined.
Can you try this change and see if you still get an error?

**Comment by raghavgurbaxani** [comment]
Hi @anj-s , thanks that worked.

Also wanted to ask if there is a way to store weights in hdf5 without using tf.keras as I am trying to use float 16 ,uint 8  and uint16 operations for my research that keras doesn't support.


I want to try the data types mentioned here https://www.tensorflow.org/versions/r1.2/programmers_guide/dims_types and save tensorflow model as hdf5. 
 
Thanks

**Comment by reedwm** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
