### ISSUE TITLE
 return getattr(obj, method)(*args, **kwds) numpy.core._internal.AxisError: axis 1 is out of bounds for array of dimension 1

### ISSUE THREAD

**Issue by Munaze** [tensorflow/tensorflow#19927]
Having error in the code:

def accuracy(predictions,labels):
    return(100.0*np.sum(np.argmax(predictions) == np.argmax(labels,1))/predictions.shape[0])

with tf.Session(graph=graph) as session:
    tf.global_variables_initializer().run()
    print('Initialized')
    for step in range(num_steps):
        _, l, predictions = session.run([optimizer, loss, train_prediction])
        if (step % 100 == 0):
         
            
            print('loss at step %d: %f'%(step,1))
            print('Training accurecy:%.1f%%'% accuracy(
                predictions,train_labels[:train_subset,:]))
            print('Validation accuracy : %.1f%%' %accuracy(
                valid_prediction.eval(),valid_labels))
    print('Test accuracy: %.1f%%' % accuracy(test_prediction.eval(),test_labels))

**Comment by usr1234** [comment]
Hi,
I think this belongs in SO. Anyway, "axis 1 is out of bounds for array of dimension 1" means when you are trying to do:
> np.argmax(labels,1)

The axis 1 is "out of bounds", meaning it does not exist. Meaning your 'labels' is a 1D array. Try reshaping it or some other stuff by labels.reshape(

Also, you could do: 

> def accuracy(): np.average(np.argmax(predictions, axis)==np.argmax(labels, axis))

**Comment by poxvoculi** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
