### ISSUE TITLE
How to get activation values of fully connected layers?

### ISSUE THREAD

**Issue by surajitsaikia27** [tensorflow/tensorflow#20024]
I want to extract the neural activation from the Fully connected layers. In caffe i was doing like this net.blobs[layer_name].data

How can i do the same in tensorflow?

**Comment by marshalhayes** [comment]
Perhaps [@google/prettytensor#6](https://github.com/google/prettytensor/issues/6) could be helpful even though it's not from this repository.

**Comment by tatianashp** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
