### ISSUE TITLE
No ImageNet folder

### ISSUE THREAD

**Issue by JohnAllen** [tensorflow/tensorflow#2005]
No ImageNet folder found at `/usr/local/lib/python2.7/dist-packages/tensorflow/models/image`.  Only `mnist` and `cifar10`.

Am I missing something?

Installed with `sudo pip install --upgrade https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.8.0rc0-cp27-none-linux_x86_64.whl` on Ubuntu 15.1

**Comment by vrv** [comment]
You can get the sources from github (check out the code at the r0.8 branch if you're using the r0.8 wheel).  The models code aren't really core libraries, just examples.  I'd like to remove mnist/cifar10 from the pip wheel too.  Unless someone can convince me otherwise, it's weird to me to have models be part of the pip installed package.

**Comment by mrry** [comment]
+1 to @vrv. I think part of the reason it was "convenient" to have this is to paper over import issues for the various `input_data` modules. We could consider moving these to `tf.contrib` (or shoehorn them into skflow's dataset support).

**Comment by JohnAllen** [comment]
:+1:
