### ISSUE TITLE
Tensorflow failed when build with CMake

### ISSUE THREAD

**Issue by gulingfengze** [tensorflow/tensorflow#20071]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:Windows 7
- **TensorFlow installed from (source or binary)**:Source
- **TensorFlow version (use command below)**:1.8
- **Python version**: Anaconda 5.1.0 (Python 3.6 64-bit)
- **Bazel version (if compiling from source)**:N/A
- **GCC/Compiler version (if compiling from source)**:VS2015
- **CUDA/cuDNN version**:9.0
- **GPU model and memory**:GeFore GTX 1080
- **Exact command to reproduce**:N/A

### Describe the problem
 I compile according to the document and report an error when "MSBuild /p:Configuration=Release tf_tutorials_example_trainer.vcxproj"is executed: 

CUSTOMBUILD : error : RPC failed;curl 18 transfer closed with outstanding read data remaining [E:\Tensorflow\tensorflow\tensorflow
contrib\cmake\build\grpc.vcxproj]

[screenshot](https://note.youdao.com/yws/public/resource/103710ae2f5c53643adf49949dd427b2/xmlnote/B89834353E21430BBB709FD8777C0414/3698)
could you please help take a look at this?Thanks!

**Comment by poxvoculi** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
