### ISSUE TITLE
Promote usage of docker above all other installation methods

### ISSUE THREAD

**Issue by cauerego** [tensorflow/tensorflow#203]
Shouldn't we just focus on docker? At least on the main page, and then link to other methods elsewhere.

Would just need a good docker development workflow (I personally got none yet).

**Comment by timshephard** [comment]
Docker has tricky GPU support as well as CPU resource allocation that can lead to poor outcomes.

**Comment by cauerego** [comment]
Ouch. That's really good to know. But are you sure those are issues for TF?

**Comment by timshephard** [comment]
Well, I should caveat that my experiences has been on windows 10.  Perhaps it's better on linux/mac.  I'm having a hard time get a simple matrix_inverse to peg one of my cores to --cpu-shares=0  The GPU issues are tricky though, they don't come by default.   Have you got it working with docker yet?

**Comment by cauerego** [comment]
Nope. I'm currently at https://codenewbie.slack.com/archives/general trying to work out a dev workflow first. Never done any with docker before. Here are a few trails I'm following:

- http://stackoverflow.com/questions/30090007/whats-the-right-way-to-setup-a-development-environment-on-os-x-with-docker
- http://discourse.codenewbie.org/t/docker-boot2docker-exposing-app-on-localhost/1148/3
- https://www.airpair.com/node.js/posts/getting-started-with-docker-for-the-nodejs-dev

**Comment by timshephard** [comment]
Ah, ok, well fwiw, for docker I just installed it from http://docs.docker.com/v1.8/installation/ and ran the command they give on the tensorflow website docker run -it b.gcr.io/tensorflow/tensorflow.  It all worked perfectly fine.   Well, I had to open my computer's firewall to accept loopback connections, but I don't that's related to either docker or TF.

**Comment by cauerego** [comment]
It's related to boot2docker's vm. I'm at nearly that point as well, but not happy while I can't git everything up properly.

**Comment by ebrevdo** [comment]
Thank you for the suggestion.  In general, docker is the best approach for building a hermetic installation of TensorFlow and I encourage most heavy TensorFlow users to follow this approach.  In general, however, pip installs are easier for users who just want to play with TF.  And while I would encourage most such users to install in virtualenv, in practice it's always less friction to just gamble that there won't be any conflicts with system installed packages in a regular pip install.

All that to say is, [there's more than one way to skin a cat](http://www.phrases.org.uk/meanings/there-is-more-than-one-way-to-skin-a-cat.html).  Closing this for now since #149 is tracking building proper Docker images.

@timshephard and @cauerego PTAL at [this script](https://github.com/tensorflow/tensorflow/blob/41930f0b81b52a34fb56d921c9bad65c36168323/tensorflow/tools/docker/docker_run_gpu.sh) for details on how to forward GPU support into the docker container.  This has worked for us.

**Comment by cauerego** [comment]
[To me](http://talk.cregox.com/t/my-social-unfair-undervaluation-and-why-the-financial-system-is-broken/7751?u=cregox), you're just saying you will probably look at this back again in the future, but can't predict when! ;P

If you can confirm this, I will try and make docker installation simpler than pip. Would this work for you? If it is possible, I can probably and will eventually do it! :)

(Just not with GPU support, of course, but that's beyond the point)
