### ISSUE TITLE
Feature request: verify py_func tensor's shape when evaluating

### ISSUE THREAD

**Issue by kolmodin** [tensorflow/tensorflow#20567]
`tf.py_func(my_py_func, args, dype)` returns a tensor of known type but unknown shape.
When my_py_func runs, py_func will check that the type is what's expected and fail otherwise.

But, if you set an incorrect shape with .set_shape there's no warning. Having a loud warning would have saved me a few hours yesterday.

Minimal example;

```python
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import tensorflow as tf
import numpy as np

def my_py_func(x):
  return x

def main(argv):
  del argv

  print(tf.GIT_VERSION, tf.VERSION)

  t = tf.constant(0, dtype=tf.int64)
  print('tf.constant(0):', t)
  t = tf.py_func(my_py_func, [t], tf.int64)
  print('tf.py_func:', t)
  t.set_shape([100,100])
  print('t.set_shape:', t)

  with tf.Session() as sess:
    t = sess.run(t)
    print('sess.run(t)', t)

if __name__ == '__main__':
  tf.app.run()
```

Output;
```
$ python using_py_func.py
v1.8.0-0-g93bc2e2072 1.8.0
tf.constant(0): Tensor("Const:0", shape=(), dtype=int64)
tf.py_func: Tensor("PyFunc:0", dtype=int64)
t.set_shape: Tensor("PyFunc:0", shape=(100, 100), dtype=int64)
sess.run(t) 0
```

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by kolmodin** [comment]
Have I written custom code: yes
OS Platform and Distribution: all
TensorFlow installed from pip
TensorFlow version 1.8
Bazel version N/A
CUDA/cuDNN version N/A
GPU model and memory N/A
Exact command to reproduce: python using_py_func.py

**Comment by asimshankar** [comment]
Thanks for the suggestion and the report.

As you probably guessed, `tf.py_func` can't return a known shape since the shape of the returned tensor depends on Python code evaluated during graph execution. [`set_shape`](https://www.tensorflow.org/api_docs/python/tf/Tensor#set_shape) is meant to fill in gaps in shape inference at graph construction time.

Perhaps you're suggesting that an error be thrown at graph execution time (`sess.run()`)?
FWIW, this isn't specific to `py_func`. For example, the following demonstrates similar behavior with `placeholder`:

```python
x = tf.placeholder(tf.float32)  # Unknown shape
y = tf.identity(x)
y.set_shape([100, 100])
print(x)
print(y)
with tf.Session() as sess:
  print(sess.run(y, feed_dict={x:10}))
```

Or with other functions where the shape can only be known at graph construction time, like `tf.unique`

```python
x = tf.constant([1, 1, 2])
y, idx = tf.unique(x)
y.set_shape([100])
print(x)
print(y)
with tf.Session() as sess:
  print(sess.run(y))
```

Off the top of my head I'm not sure how to spec out the feature request here.

**Comment by kolmodin** [comment]
Yes, I'm aware why py_func cannot know the shape.
Indeed the idea was to print a warning during `sess.run(...)` since it should be able to spot the inconsistency between what was said and then actually was.

I didn't consider that py_func isn't at all special here. As you demonstrate, the same can be true for any tensor.

In your last example;

```python
x = tf.constant([1, 1, 2])
y, idx = tf.unique(x)
y.set_shape([100])
print(x)
print(y)
with tf.Session() as sess:
  print(sess.run(y))
```

a warning would be issued for y not having the shape it was said to have.

Tensors either have a know, partially unknown or unknown shape. If it's unknown, fine, there are no guarantees.
But if the shape has been provided, when evaluated it should be what's expected, no?
Spec: tensors of known or partially known shapes should actually have that shape when evaluated.
Does that sound reasonable?

**Comment by asimshankar** [comment]
An interesting suggestion. If I may, an alternative way to phrase you proposal is that `y.set_shape([100])` should have the same effect as:

```python
with tf.control_dependencies([tf.assert_equal(tf.shape(y), [100])]):
  y = tf.identity(y)
```

(a little more sophistication for handling partially known shapes as well, but the general idea being to use [assertion operations](https://www.tensorflow.org/api_guides/python/check_ops) to validate shapes at graph execution time).

So far, the shape of the symbolic `Tensor` object has only been used as a hint to help catch errors during graph construction. For most operations this is enough since shapes can be statically determined then. However, there are handful of operations where this is not possible and I can see how validation at runtime can be useful. That said, I don't think the costs (both additional overhead in graph execution and the time to implement it) outweigh the benefits enough for us to prioritize this at this moment.

For now, I'm going to mark this as "Contributions Welcome" with the understanding that if someone has the inclination to take this on, we'd be happy to discuss the details. Sound reasonable?

**Comment by kolmodin** [comment]
Sounds good.

**Comment by sahilbadyal** [comment]
@asimshankar  Interested in working on this issue. Need a little direction

**Comment by mohantym** [comment]
Hi @kolmodin !

It is throwing an exception now in 2.8.2 version.  Attached [gist](https://colab.sandbox.google.com/gist/mohantym/11bd09fc06593e43ba6364da6e4a70b6/git_20567.ipynb#scrollTo=RoOj0tKNAw7p) for reference.

Thank you!
