### ISSUE TITLE
Features parameters for retrain.py used model

### ISSUE THREAD

**Issue by Shazuka** [tensorflow/tensorflow#20573]
------------------------

### System information
- **Using retrain.py to train my own data**:
- **Windows**:
- **install tensorflow using cmd**:
- ** tensorflow version 2.0**:
- ** python version 3.6.6rc1**: 
- **No bazel**:

### Describe the problem
Need help regarding setting parameters for the model in ClassifierActivity.java .I have trained by custom dataset using retrain.py gave on the tensorflow.But when I run the app on the android by deploying my own model. The app runs successfully but not labeling the detecting images. I think there is some issue with parameters 
private static final int INPUT_SIZE = 299;
  private static final int IMAGE_MEAN = 128;
  private static final float IMAGE_STD = 128;
  private static final String INPUT_NAME = "Mul";
  private static final String OUTPUT_NAME = "final_result";
Or there is another issue you need to tell me.Please help as I have to submit my work as soon as possible.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
