### ISSUE TITLE
tf.cond not working with depedencies

### ISSUE THREAD

**Issue by alex04309** [tensorflow/tensorflow#2062]
tf.cond seems to have a bug if one of the condition have a dependency. (Dependencies are run, whatever tf.cond arg is True or False).

To illustrate:
```
import tensorflow as tf

a = tf.Variable(0)
incr = a.count_up_to(1)

def todo_if_true():
  with tf.control_dependencies([incr]):
    return tf.identity(a)
def todo_if_false():
  return tf.identity(a)

g = tf.cond(tf.constant(False), todo_if_true, todo_if_false)
init = tf.initialize_all_variables()

with tf.Session() as sess:
  sess.run(init)
  print(sess.run(g))
```

Output:
```
1 #But should be 0
```

**Comment by prb12** [comment]
@yuanbyu - any ideas?

**Comment by yuanbyu** [comment]
You need to move the count_up_to op inside the conditional branch you want it to be executed.

```
a = tf.Variable(0)

def todo_if_true():
  incr = a.count_up_to(1)
  with tf.control_dependencies([incr]):
    return tf.identity(a)
def todo_if_false():
  return tf.identity(a)

g = tf.cond(tf.constant(False), todo_if_true, todo_if_false)
```

I have added the following paragraph to the doc:

 Note that the conditional execution applies only to the operations defined in
  fn1 and fn2. Consider the following simple program:

  ```python
  z = tf.mul(a, b)
  result = tf.cond(x < y, lambda: tf.add(x, z), lambda: tf.square(y))
  ```

  If x < y, the tf.add operation will be executed and tf.square
  operation will not be executed. Since z is needed for at least one
  branch of the cond, the tf.mul operation is always executed, unconditionally.
  Although this behavior is consistent with the dataflow model of TensorFlow,
  it has occasionally surprised some users who expected a lazier semantics.

**Comment by mrn333** [comment]
Thanks!
