### ISSUE TITLE
Increasing memory use of Estimator with Dataset

### ISSUE THREAD

**Issue by The-Fonz** [tensorflow/tensorflow#20699]
------------------------

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 18.04
- **TensorFlow installed from (source or binary)**: Binary (pip install)
- **TensorFlow version (use command below)**: Tested on 1.8.0 and 1.10.0-dev20180620
- **Python version**: 3.6
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: GTX1050
- **Exact command to reproduce**: See below for minimal test case

### Describe the problem
I'm experiencing a memory leak that leaves some allocated memory behind after each Estimator training/evaluation run. I noticed this when my ML Engine jobs started failing after 1.5 hours of training with an OOM error on big CSV files, using the standard Dataset input pipeline with some preprocessing, batching, prefetching etc. The memory graph shows slow but steady increase of memory use until total RAM is filled. I observe the same behavior on my local machine.

I've distilled it down to a minimal test case with use of Estimator and Dataset input and tested on my local machine, where I also get slowly increasing memory use over time. It seems most pronounced when using a big shuffle buffer, but after all this time staring at it I'm not so sure of anything any more.

Test script (first `pip install -U memory_usage`):
```
import tempfile, time, argparse, os

# Install with pip install -U memory_usage
from memory_profiler import memory_usage
import tensorflow as tf
from tensorflow.python.client import device_lib

parser = argparse.ArgumentParser()
parser.add_argument('--apply-shuffle-repeat', action='store_true')
parser.add_argument('--shuffle', action='store_true')
parser.add_argument('--gpu', action='store_true')
args = parser.parse_args()

# Turn on/off gpu
if not args.gpu:
    print("Turning off GPU")
    os.environ["CUDA_VISIBLE_DEVICES"]=""

print(f"Tensorflow version: {tf.GIT_VERSION} {tf.VERSION}")

print(f"Devices: {device_lib.list_local_devices()}")

tmpdir = tempfile.mkdtemp()

_input = [1] * 5000000
_target = [1] * 5000000

def input_fn(batch_size=4096):
    data = tf.data.Dataset.from_tensor_slices(
        ({'input': _input}, _target))
    if args.shuffle:
        data = data.shuffle(1000000)
    elif args.apply_shuffle_repeat:
        data = data.apply(tf.contrib.data.shuffle_and_repeat(buffer_size=1000000, count=1))
    data = data.batch(batch_size)
    return data

estimator = tf.estimator.DNNRegressor(
    [64],
    [tf.feature_column.numeric_column(key='input')],
    model_dir=tmpdir)

train_spec = tf.estimator.TrainSpec(input_fn=input_fn)

eval_spec = tf.estimator.EvalSpec(input_fn=input_fn)

# Train and evaluate forever
tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)
```

Output of `mprof run tf_estimator_memoryleak_minimal.py --apply-shuffle-repeat
` (so it runs on CPU, for GPU use `--gpu` option) and plotting with `mprof plot` shows memory usage slowly but surely creeping upward:
![tf-memoryuse](https://user-images.githubusercontent.com/5527529/42563920-b7986b62-84ff-11e8-9fa4-304f319927a0.png)

I would expect memory usage after every train/evaluate loop to return to the initial level.

Am I using the Dataset in the wrong way? Should I convert to an Iterator first? Is slightly increasing memory use normal and should I restart my train script every once in a while?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Bazel version

**Comment by robieta** [comment]
Interesting. This looks like memory increases as more of the dataset is read (in order to repeat the dataset has to hang onto all points), and then it levels off which presumably is when it is repeating. Based on my reading of .train_and_evaluate(), it doesn't seem to be equivalent to:
```
while True:
  my_estimator.train(...)
  my_estimator.evaluate(...)
```

One simple thing you can try is to put a `print` statement in the input_fn to see if it is called once or repeatedly. If it is just called once for training and once for eval, then this behavior makes sense. (I would expect a memory leak to be linearly increasing, not asymptotic.)

**Comment by guillaumekln** [comment]
Thanks @The-Fonz for opening this issue.

I'm have similar observations with `train_and_evaluate`. It is mostly visible when using buffered Dataset operators like `shuffle` but it seems to level off after some steps:

![image](https://user-images.githubusercontent.com/4805513/42679991-0392b902-8684-11e8-9235-ec7c75720223.png)

(Each increase corresponds to a new training phase.)

After more investigation, this appears to be fixed by https://github.com/tensorflow/tensorflow/commit/3edb609926f2521c726737fc1efeae1572dc6581. However, I'm not sure about the availability of this change: GitHub says it's part of the `1.9.0rc2` tag but the commit is not on the `r1.9` branch?

Anyway, I can confirm this is no more an issue in the current nightly package.

**Comment by The-Fonz** [comment]
Thanks @guillaumekln for pointing that out, with the latest tf-nightly I can confirm that this problem is gone! I can happily train and evaluate forever now.

@robieta the input_fn was indeed called repeatedly for every train and evaluate cycle. With the new behavior, the input_fn is only called once for all train cycles, and repeatedly for the evaluate cycles.

Closing as this seems to be solved by 3edb609.

**Comment by guidj** [comment]
I'm seeing a similar issue, and it seems to be [documented as expected behavior](https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate):
`Note that in current implementation estimator.evaluate will be called multiple times. This means that evaluation graph (including eval_input_fn) will be re-created for each evaluate call. estimator.train will be called only once.`

The question is whether the graph and `eval_input_fn` are release/de-allocated after each call

Ps: I'm happy to move this discussion to a different place it helps

**Comment by chychen** [comment]
Dear @The-Fonz ,
I got few questions need your help.
Do you mean that the problem could be solve by train_and_evaluate()? as you said, input_fn() will be called repeatedly while evaluate(), won't it be a leaking situation?
I meet the same issues by iterating train() and evaluate() separately, does anyone have idea how to solve the problem? 
(train_and_evaluate() seems not work with horovod multi gpu training so I iterate train() and evaluate() instead)

**Comment by The-Fonz** [comment]
Hi @chychen, has been some time since I worked on this but I recall that it was fixed and that you need to use `train_and_evaluate()` as it only runs `input_fn()` once, see comments above.
