### ISSUE TITLE
go api speed up array of frames

### ISSUE THREAD

**Issue by deepch** [tensorflow/tensorflow#20717]
I have raw decoded video frame format *image.YCbCr

but for work I need to encode it to jpeg or png

op.DecodeJpeg
op.DecodePng

this operation takes about 20 ms

can I somehow convey a raw image so as not to waste this time?

or maybe I can convert to rgb and send pix() to  tensorflow op

It's really not convenient to code to decode and slow down the work with an array of frames; (

**Comment by asimshankar** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
