### ISSUE TITLE
Person Detection issue in Android App Using tenserflow Lite

### ISSUE THREAD

**Issue by Shanoobmk** [tensorflow/tensorflow#20729]
Hi i am Using Android Detection Example App , here  i want to monitor a person in or out activity.
but my problem is it take more time to detect when a person walk ,some time cnt detect person.
 another problem is that after detecting cant track properly ..
 is this is the issue of camera video quality..? 
how can i change the quality and  brightness of  camera in this app..?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by Shanoobmk** [comment]
yes i have written custom code on Multiboxtracker.java class.
N/A
N/A
N/A
Sir i am using tenserflow Lite on android mobile phone , i am using tenserflow Lite demo app downloaded from  github (tensorflow/tensorflow/examples/android/). my issue is in this app.

**Comment by reedwm** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by Shanoobmk** [comment]
thanks sir ,
