### ISSUE TITLE
Including timestamp with tf.Print?

### ISSUE THREAD

**Issue by eriophora** [tensorflow/tensorflow#2076]
I'm trying to implement a batched version of the Inception example for TensorFlow Serving, and I'd like to benchmark the performance. 

Is it possible to have `tf.Print` emit a timestamp along with the logging information? Particularly if the op is bundled via `tensorflow_serving.session_bundle.exporter`?

I think it's possible to do with:

`x = tf.Print(x, [x], "(%s) Obtained: " % asctime())`

although I'm not sure if this will work appropriately when exported.

**Comment by mrry** [comment]
That won't work, I'm afraid: `asctime()` will be evaluated once when you build the graph in Python, and all log entries will include the same timestamp. The `tf.Print()` op uses the [standard logging implementation in TensorFlow](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/default/logging.h), which does not have a particularly rich feature set.

It might be useful to add a timestamp to all log entries, but that would be a fairly invasive change. Alternatively, one could add some ops (perhaps in `tf.contrib`) that returned/formatted the current time, so that you could build whatever log you wanted.

I'll mark this one contributions welcome.

**Comment by suiyuan2009** [comment]
@eriophora you can use a placeholder
`x=tf.placeholder(tf.string,shape=(1,1))                                          
 z=tf.constant(10)                                                                
 y=tf.Print(z,[x,z])                                                              
 with tf.Session() as sess:                                                       
         for i in range(10):                                                          
         time.sleep(1)                                                            
         ti=time.asctime()                                                        
         xx=np.array([ti],ndmin=2)                                                
         y.eval(feed_dict={x:xx}) `

**Comment by b0noI** [comment]
blocked by #5682

**Comment by drpngx** [comment]
Are we ready to proceed on this?

**Comment by b0noI** [comment]
drpngx@ should be merged soon.

**Comment by yaroslavvb** [comment]
One second granularity is a bit too coarse for benchmarking, it would be nice to get microsecond granularity like LOG statements , ie, using `NowMicros` instead of `NowSeconds`. Maybe something like this in `GenerateLogMessage`?

```
char time_buffer[time_buffer_size];
uint64 micros = env_time->NowMicros()
time_t now = static_cast<time_t>(micros/1000000);
strftime(time_buffer, time_buffer_size, "%Y-%m-%d %H:%M:%S:%d", localtime(&now));
fprintf(stderr, "%s:%ld: %c %s:%d] %s\n", time_buffer, micros%1000000, "IWEF"[severity_], fname_, line_, str().c_str());
```
