### ISSUE TITLE
Configure Tensorflow on GPU using Java API

### ISSUE THREAD

**Issue by AdrianXIA** [tensorflow/tensorflow#20769]
Hello,

How to set following config "gpu_options.allow_growth = True" for Tensorflow, using Java API?
I tried using this code but it doesn't work:

```
        ConfigProto config = ConfigProto.newBuilder()
                  .setGpuOptions(GPUOptions.newBuilder()
                                         .setAllowGrowth(true)
                                         .setPerProcessGpuMemoryFraction(0.04)
                                         .build()
                                        ).build();
           model.session().runner()
                    .setOptions(config.toByteArray())
                    .feed("image_tensor", input).fetch("detection_scores")
                    .fetch("detection_classes").fetch("detection_boxes").fetch("num_detections").run();
```

I know the method setOption is an experimental method. 
Is there another away to achieve it?

Thanks

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce

**Comment by asimshankar** [comment]
Could you elaborate on what you mean by "it does not work". Can you provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) to reproduce the problem?

Thanks

**Comment by AdrianXIA** [comment]
1) Used this code [code](https://github.com/tensorflow/models/tree/master/samples/languages/java/object_detection),
2) Coco [Models ](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) for Inference: faster_rcnn_nas
2) I ran in AWS using AWS EC2, type p2.xlarge, with Tesla K80,
3) I chose a Linux instance for Deep Learning,
4) Tensorflow GPU version: 1.8.0 and 1.9 rc
5) Java 8

 The process reserve the whole memory but the actual utilization is under 40% - 50%. I used [nvidia-smi queries](http://nvidia.custhelp.com/app/answers/detail/a_id/3751/~/useful-nvidia-smi-queries) for monitoring the GPU.

**Comment by asimshankar** [comment]
Oh, I see.

`Session.runner().setOptions()` is supposed to be provided with a [`RunOptions`](http://static.javadoc.io/org.tensorflow/proto/1.9.0-rc2/org/tensorflow/framework/RunOptions.html) protocol buffer (see [javadoc](https://www.tensorflow.org/api_docs/java/reference/org/tensorflow/Session.Runner.html#setOptions(byte[]))), not a `ConfigProto` message.

The `ConfigProto` message needs to be provided when creating the `Session` object and currently `SavedModelBundle.load()` doesn't make this possible.  PR #18716 was supposed to make this possible, but it seems like the PR author didn't get around to updating the PR to fit into the master branch. I can try to fix that up.

Ideally, this error would have been caught by the compiler if the API accepted Java objects for the protocol buffer messages instead of a `byte[]` of serialized data. However, in an effort to ensure that
this lowest layer of the Java API has no dependencies, we avoid a dependency on the Java protocol buffer libraries, which comes at the cost of this confusion (since the serialized `ConfigProto` message provided can be parsed into a `RunOptions` message without error).

I'll make a PR to allow a serialized `ConfigProto` to be provided when loading a `SavedModelBundle` which would then address your use case.

**Comment by AdrianXIA** [comment]
Thank you!

**Comment by AdrianXIA** [comment]
Hello,
How can I test it?Can I use this version 1.9.0-rc2?
Thank youAdrian    On Saturday, July 14, 2018, 12:28:05 AM GMT+3, Asim Shankar <notifications@github.com> wrote:  
 
 
Oh, I see.

Session.runner().setOptions() is supposed to be provided with a RunOptions protocol buffer (see javadoc), not a ConfigProto message.

The ConfigProto message needs to be provided when creating the Session object and currently SavedModelBundle.load() doesn't make this possible. PR #18716 was supposed to make this possible, but it seems like the PR author didn't get around to updating the PR to fit into the master branch. I can try to fix that up.

Ideally, this error would have been caught by the compiler if the API accepted Java objects for the protocol buffer messages instead of a byte[] of serialized data. However, in an effort to ensure that
this lowest layer of the Java API has no dependencies, we avoid a dependency on the Java protocol buffer libraries, which comes at the cost of this confusion (since the serialized ConfigProto message provided can be parsed into a RunOptions message without error).

I'll make a PR to allow a serialized ConfigProto to be provided when loading a SavedModelBundle which would then address your use case.

**Comment by asimshankar** [comment]
@AdrianXIA : You'll have to build from source. This change isn't included in 1.9 or 1.10 (whose branch was cut just before the change was merged).

Instructions for building from source: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java#building-from-source

**Comment by DutAlex** [comment]
Hello,

I actually built from source the version with the Loader in SavedModelBundle.
However it seems that using SavedModelBundle.withConfigProto(config) doesn't impact anything compared to the "default" configuration.
Code is below :

`        ConfigProto configProto = ConfigProto.newBuilder()
                .setAllowSoftPlacement(true) // allow less GPUs than configured
                .setGpuOptions(GPUOptions.newBuilder().setPerProcessGpuMemoryFraction(0.01))
                .build();

SavedModelBundle  bundle = SavedModelBundle.loader(modelDir).withTags("serve").withConfigProto(configProto.toByteArray()).load();`

Am I missing something ?

**Comment by asimshankar** [comment]
@DutAlex : Just to confirm: When you say there is "no impact" you mean that you see all of the GPU memory being allocated by the JVM process (as reported by `nvidia-smi`)? Could you post some more detail on how you're running the program and observing the change?

**Comment by DutAlex** [comment]
@asimshankar Yes, all the GPU memory is allocated to the JMV process (using `nvidia-smi` ). To run the program, I am building the .jar file using `mvn package` and running it with using `java -cp jar-file-with-dependencies.jar`.

In the main file, I am loading a model and open a file where I make prediction on 10000 inputs (1-by-1). I am using `System.nanoTime()` to profile how long did the prediction of those 10000 examples take.
I see no difference in execution time whether I am setting the GPUOptions (`GPUOptions.newBuilder().setPerProcessGpuMemoryFraction(0.01).build()`) or using the historical version of the SavedModelBundle (`SavedModelBundle.load(modelDir, "serve")`).
In addition to that, I am also profiling my GPU activity every second while the model is making predictions (using `gpustat`) and see that its activity during the predictions is around ~65% whether I am setting the GPUOptions or not.

**Comment by asimshankar** [comment]
@DutAlex : There seem to be two things in your comment

1. Even after setting `per_process_gpu_memory_fraction`, all GPU memory is being allocated.
2. Setting that option doesn't change the time it takes to run predictions.

I don't quite see why setting the memory fraction option should change the latency of predictions. The 65% utilization of GPU cores is not something this option would address. Most likely there is some other limitation (in the model) that precludes better GPU utilization.

So, of 1. and 2., I think only 1. is concerning here :)
Could you create a [minimal, verifiable, complete](https://stackoverflow.com/help/mcve) example to help reproduce the problem?

For example, I tried the following  - https://gist.github.com/asimshankar/2d65be7ef53f1888cf7dc93758a565c9 - which suggests to me that the change is working (in that it is respecting options provided to the `ConfigProto` message).

In particular, note that without the `setPerProcessGpuMemoryFraction()` line, `nvidia-smi` shows that the JVM process has allocated all ~12GB of GPU memory:

```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    241863      C   /usr/lib/jvm/java-8-openjdk-amd64/bin/java 11615MiB |

```

but with that line, it allocates ~370MB:
```
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0    241613      C   /usr/lib/jvm/java-8-openjdk-amd64/bin/java   371MiB |

```

A way to reproduce the problem will be helpful, otherwise it may be hard to figure out what's going on in your particular setup. Thanks!

**Comment by DutAlex** [comment]
@asimshankar I managed to reproduced the results of your gist. I found out that I was using a wrong version of the tensorflow-jni library... . It actually works well now.

Thank you for your help.
Looking forward to see the version in a stable release !
