### ISSUE TITLE
mpi build failed, wrong filename

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#21117]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Ubuntu 16.04 x64
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
no
- **TensorFlow installed from (source or binary)**:
source
- **TensorFlow version (use command below)**:
1.10.0rc0
- **Python version**:
3.6.6 x64
- **Bazel version (if compiling from source)**:
0.15.0
- **GCC/Compiler version (if compiling from source)**:
5.4.0
- **CUDA/cuDNN version**: 
9.2/7.1.5
- **GPU model and memory**:
GTX1080Ti GDDR5X 11GB  X  6
- **Exact command to reproduce**:
build with mpi support

### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

![image](https://user-images.githubusercontent.com/4515120/43182126-1e4d20e8-901b-11e8-9414-2bc216fbd49f.png)

there is no such file actually

![image](https://user-images.githubusercontent.com/4515120/43182165-4789549a-901b-11e8-8086-f2da98551316.png)

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
