### ISSUE TITLE
KNN classifier.setClassifierDataset

### ISSUE THREAD

**Issue by lenny76** [tensorflow/tensorflow#21137]
hi

can you help me to save and retrieve the model I've created based on KNN Classifier?
I've seen that I need to use classifier.setClassifierDataset and classifier.getClassifierDataset, but I cannot make it workj

thanks

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by lenny76** [comment]
i'm trying to load a classifierdataset in this way

after train with addExample I save the model with this`
localStorage.setItem('classifier', JSON.stringify(classifier.getClassifierDataset()));`

and recover with
`classifier.setClassifierDataset(JSON.parse(localStorage.getItem('classifier')));`

knn-classifier:2 Uncaught (in promise) TypeError: r.clone is not a function
    at knn-classifier:2

thanks
