### ISSUE TITLE
cuda 9.0 on windows 10 goes extremely unstable, prebuilt should be migrated to cuda 9.2

### ISSUE THREAD

**Issue by alanpurple** [tensorflow/tensorflow#21217]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: no
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:  Windows 10 x64
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: 
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.10.0rc0
- **Python version**: 3.6.6 x64
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**: MSVC15
- **CUDA/cuDNN version**: 9.2/7.1.5
- **GPU model and memory**: GTX1050Ti GDDR5 4GB
- **Exact command to reproduce**:
CUDA 9.0 no longer supported

This is not a direct tensorflow issue. This is a suggestion for all windows 10 tensorflow-gpu user

These days NVIDIA geforce driver starts to reject CUDA 9.0 since this version is too old and deprecated

There is no reason tensorflow-gpu prebuilt binary is provided with cuda 9.0 and cudnn 7.0

Prebuild binary sholud be built with latest cuda and cudnn version

**Comment by tfboyd** [comment]
I am not aware of CUDA 9.0 being deprecated.  You can run the latest cuDNN with the prebuilt binary, e.g. 7.1.5, the docker container (linux) has tensorflow compiled with cuDNN 7.0 and ships with 7.1 binary.

Can you indicate what is not stable about CUDA 9.0 and what you mean by "starts to reject"? I have been running CUDA 9.0 on the NVIDIA DGX-1 with the 396.x driver and if anything it is much faster that with earlier drivers if you have updated cuDNN.  Of course that is not windows. I do not run on windows myself but I am curious of the use case and have you tried to compile with 9.2 and the problem went away?  If moving to CUDA 9.2 makes the windows experience better it may be something we can consider but I do not plan to push for CUDA 9.2 on Linux as currently there is very little to gain and 9.0 has been stable for linux.

Thank you for the information.

**Comment by alanpurple** [comment]
@tfboyd  latest geforce driver doesn't support CUDA for some VGA anymore

in my case, mx150 and GTX1080Ti is fine, but GTX1050Ti only able to install cuda 9.2 with geforce driver 398.36

**Comment by tfboyd** [comment]
Can you link the install and the statement from NVIDIA that it is not supported?  I will ask them what is up if I can get specific details.  You do not have to install the driver and CUDA at the same time (at least on linux), you can install any version of CUDA that you want.  NVIDIA is big into backwards compatibility, I am pretty sure you can still run CUDA 8.0 with the latest drivers if you really wanted.  If you are getting an error can you take a screenshot, as I am not sure why the 1080ti and my 1080 work but not the 1050ti.

CUDA 9.0 is not deprecated.  NVIDIA recommends CUDA 9.0 for its DGX-1.  In my meetings with them we agreed it would be better to stick with CUDA 9.0 until 10.0 comes out due to having to force people to update to the latest drivers, which is difficult for many users especially schools and corporations.  CUDA 10.x will be nice as it will not require constant driver updates.

If CUDA 9.0 is broken on Windows, I can escalate to NVIDIA and we can consider changing the windows install to use CUDA 9.2.  I just need details.   I did some light research and I do not see any indicators that CUDA 9.0 doesn't work with the 1050ti, but there is likely a lot of info out there that I have not seen.

**Comment by tfboyd** [comment]
As a side note, there is a very fast moving effort for more community builds that I believe will offer more bleeding edge support.  I understand CUDA 9.2 looks like the standard to you, but if you look at CUDA 9.0 it had at least 4 patches.  It is actually the more stable version as people slowly flush out issues with CUDA 9.2.  CUDA 9.2 was actually delayed due to some last minute bugs.  CUDA 9.0 plus patches have  had almost a year to slowly develop and become stable.  

This does not mean we cannot try to move Windows to CUDA 9.2 if that would greatly benefit the community.

**Comment by alanpurple** [comment]
@tfboyd 

yes I can build it myself( but you know, with windows10, build is not handy and not support officially as docs said )

this issue is just a suggestion, always thanks to you guys

**Comment by tfboyd** [comment]
@alanpurple   I just saw some early CUDA 10 stuff, and as crazy as this sounds CUDA 10 is going to be backwards compatible more than CUDA 9.1 and 9.2.  My goal is to get on CUDA 10 as soon as it is live and it is passing all of the tests.  

If you provide more details I can pass them on to NVIDIA.

**Comment by alanpurple** [comment]
@tfboyd 

today geforce driver 398.82 has been released, and cuda 9.0 works fine with that

FYI

**Comment by tfboyd** [comment]
That is great.  This is a bit insider information but the 384.x device driver will be supported for CUDA 10 until likely atleast Q2 next year although it is not supported by CUDA 9.1 and 9.2.  There will be a 400 "series" driver released with CUDA 10 as well.  

I understand your situation is different.  For an enterprise staying on a set of drivers as long a possible is desired.  If I was gaming and doing ML (as I do at home) and on Windows (I duel boot linux) I would be on the latest driver like yourself.  This does not help you and I understand this is painful at times.
