### ISSUE TITLE
tf.image.extract_glimpse does not work as expected

### ISSUE THREAD

**Issue by beopst** [tensorflow/tensorflow#2134]
tf.image.extract_glimpse function does not work as expected. In some cases, the extracted glimpses are the same regardless of offset parameters. Please see the below code to reproduce.
### Environment info

Operating System: Ubuntu 14.04 

Installed version of CUDA and cuDNN: CUDA 7.5, cuDNN R4

If installed from sources, provide the commit hash: cf1659d
### Steps to reproduce

Try to run the code

```
import tensorflow as tf
import numpy as np

input_img = np.arange(25).reshape((1,5,5,1))

first_glimpse = tf.image.extract_glimpse(input_img, [3,3], [[1,1]],
                                    centered=False, normalized=False)
second_glimpse = tf.image.extract_glimpse(input_img, [3,3], [[2,1]],
                                    centered=False, normalized=False)

sess = tf.Session()

print first_glimpse.eval(session=sess)[0,:,:,0]
print second_glimpse.eval(session=sess)[0,:,:,0]
```

Results are

```
first_glimpse = [[  0.   1.   2.]
                 [  5.   6.   7.]
                 [ 10.  11.  12.]]
second_glimpse = [[  0.   1.   2.]
                  [  5.   6.   7.]
                  [ 10.  11.  12.]]
```

Is this a bug? Or am I missing something?

**Comment by beopst** [comment]
One more observation: 
tf.image.extract_glimpse generates some noises (based on argument uniform_noise=True or False) on pixels outside of glimpse window. To my knowledge these noises should be random values, however it is not changed over calls.

**Comment by girving** [comment]
@benoitsteiner: Eigen's ExtractGlimpse code does seem broken: it builds its own internal RNG without any seed input from outside.

**Comment by tatatodd** [comment]
@benoitsteiner Friendly ping to update this bug when you have a chance, thanks!

**Comment by CNugteren** [comment]
@benoitsteiner Another friendly request to look at this. To be clear, the bug we are talking about is that the offsets of `extract_glimpse` are not working as expected. This is for example used in the U-Net type of networks (e.g. in the [tf_unet repo](https://github.com/jakeret/tf_unet/blob/a292baea867d2e8a74779155b61ae8abc3ba3cc3/tf_unet/layers.py#L51)).

I reproduced the bug using this [slightly larger example](https://gist.github.com/CNugteren/5313ebbd497ddba9016cc2ea09745894) and I got [this output](https://gist.github.com/CNugteren/4d4a236dc1e98784fca8301c098daa51). I cannot make sense of it, and it becomes less clear when trying other input sizes (e.g. 4x4). Also I believe that the bug is also present when the indices are floating point and `normalized=True`.

Note that there is also a an issue open on [StackOverflow](http://stackoverflow.com/questions/36039429/tensorflow-extract-glimpse-offset).

**Comment by CNugteren** [comment]
There is a work-around in case `centered=True` and `normalized=False`. In that case the offsets range from minus the size to plus the size of the tensor. I therefore wrote a wrapper that is more intuitive to numpy users, using pixel coordinates starting at (0,0):
```

import tensorflow as tf
import numpy as np

def extract_glimpse_numpy_like(input, glimpse_size, glimpse_offsets, name=None, uniform_noise=None):
    """
    Works like in numpy with pixel coordinates starting at (0, 0), returns:
       input[:, glimpse_offset[0] : glimpse_offset[0] + glimpse_size[0],
                glimpse_offset[1] : glimpse_offset[1] + glimpse_size[1], :]
    """
    assert(len(glimpse_size) == 2)
    assert(len(glimpse_offsets) == 2)
    input_size = tuple(input.get_shape().as_list())  # includes batch and number of channels
    corrected_offsets = [2 * glimpse_offsets[0] - input_size[1] + glimpse_size[0],
                         2 * glimpse_offsets[1] - input_size[2] + glimpse_size[1]]
    corrected_offsets = np.tile(corrected_offsets, input_size[3])  # repeat it for each batch
    corrected_offsets_t = tf.reshape(tf.constant(corrected_offsets, dtype=tf.float32), shape=(input_size[3], 2))
    return tf.image.extract_glimpse(input, glimpse_size, corrected_offsets_t, centered=True, normalized=False,
                                    uniform_noise=uniform_noise, name=name)
```
Note that this function assumes that the size of the tensor is known and that the offset is the same for each batch.

The original example would then return two subsequent glimpses when changed to use the above function:
```
input_img = np.arange(25).reshape((1,5,5,1))
input_tensor = tf.constant(input_img, dtype=tf.float32)
first_glimpse = extract_glimpse_numpy_like(input_tensor, [3,3], [0,0])
second_glimpse = extract_glimpse_numpy_like(input_tensor, [3,3], [1,0])

sess = tf.Session()
print first_glimpse.eval(session=sess)[0,:,:,0]
print second_glimpse.eval(session=sess)[0,:,:,0]
```

**Comment by cancan101** [comment]
This demonstrates the problem for me with `normalized=False` and`centered=False` (notice the off by 1):
```python
arr = np.zeros((1,11,11, 1), dtype=np.float32)
arr[0, 5,5] = 1
arr = tf.constant(arr)
glim = tf.image.extract_glimpse(arr, (1,1), offsets=[(6,6)], normalized=False, centered=False)
sess.run(glim)
```
```
> array([[[[ 1.]]]], dtype=float32)
```

**Comment by girving** [comment]
Looks like @benoitsteiner won't get to this himself.  Let me know if anyone wants to tackle it.  I'm happy to answer questions about how to mirror the seed semantics of the rest of the random ops.

**Comment by cancan101** [comment]
Perhaps this is another issue, or I am misunderstanding this, but it seems like there is an off by one issues as well?

**Comment by LucasMahieu** [comment]
Does this issue is always unsolved ?

**Comment by AroMorin** [comment]
Is this bug fixed yet? Also, is there a way to have pad with ZEROS instead of random noise??

**Comment by yongtang** [comment]
I think the issue about offset is located:
https://github.com/tensorflow/tensorflow/blob/ca3bc0f1c2f917cf6e7c49d58f5ec604a9af9367/tensorflow/core/kernels/eigen_attention.h#L84-L98

Created a PR #12829 to fix it with the following changes:
```
      if (normalized_) {
        // Un-normalize coordinates back to pixel space if normalized.
        x *= input_width;
        y *= input_height;
        if (centered_) {
          // Un-center if coordinates are centered on the image center.
          x /= 2.0f;
          y /= 2.0f;
          x += input_width / 2.0f;
          y += input_height / 2.0f;
          // Remove half of the glimpse window.
          x -= width_ / 2.0f;
          y -= height_ / 2.0f;
        }
      } else {
        if (centered_) {
          x += input_width / 2.0f;
          y += input_height / 2.0f;
        }
      }
```

**Comment by yongtang** [comment]
@AroMorin Currently the  `tf.image.extract_glimpse` allows you to specify a boolean (`True/False`) to indicate if uniform or gaussian noise is to be used. We could not extend the boolean to indicate the zero background.

It might be possible to add an additional flag (e.g, `noise_type: string` etc) so that other noise types could be specified. But that will require API changes.

I can work on adding zero padding if tensorflow team is OK with api changes for `tf.image.extract_glimpse`.

**Comment by vribic** [comment]
It is possible to use extract_glimpse with zero padding by playing around with resize_image_with_crop_or_pad first. 

If the img_batch variable is a tensor of shape [batch_size,img_width,img_height,channels] you could do first something like this:

```python
 # unstack images in batch
img_batch_unstacked = tf.unstack(img_batch , axis= 0)

 # stack images on channels
concat_on_channel_batch = tf.concat(img_batch_unstacked, axis= 2)

 # pad the image with max glimpse width/height
resized_img_batch = tf.image.resize_image_with_crop_or_pad(
    image= concat_on_channel_batch,
    target_width= conf.get_padded_img_width(), 
    target_height= conf.get_padded_img_height() 
)

 # undo the opeartions to get the original batch
 # first split images on channels 
splited_on_channel_batch = tf.split( 
    resized_img_batch, 
    num_or_size_splits=conf.batch_size, 
    axis=2
)

 # combine the images back to the original shape
img_batch_padded = tf.stack(
    splited_on_channel_batch,
    axis=0
)
```

Now you need to modify the offsets variable so that it goes from -x to x where x is a new boundary depending on the original image dimensions and the padding dimensions. You can calculate it like: 

```python
offset = offset * original_image_dimension / padded_image_dimension
```

Finally for the extract_glimpse use : 

```python
glimpses = tf.image.extract_glimpse(
    input=img_batch_padded,
    size = glimpse_dim,
    offsets=offset,
    centered=True,
    normalized=True
)
```

I'm not sure if this is the best solution but it keeps all calculations in Tensorflow what was my goal. Hope this helps until the fix for zero padding get implemented.

**Comment by 3nomis** [comment]
If I extract multiple glimpses from an IMG how can I make sure they are non overlapping? thanks
