### ISSUE TITLE
Diagnostic / assessment tools for network

### ISSUE THREAD

**Issue by jerabaul29** [tensorflow/tensorflow#2135]
It would be convenient to have some tools out of the box for assessing networks complexity, computational cost, resources use etc without need for the user to do it 'by hand'. Do you think the following would be possible to implement in a general way?

- getting a command to know how many parameters will be optimized by a tf.train node, and how many floating operations are required

- more generally, getting a command to know how many operations are required to execute a node with sess.run

- getting a set of commands to evaluate memory, cuda cores and bandwith use (both absolute value and proportion of the device) by a node on gpu, and cpu use. A little bit as mentioned here: http://stackoverflow.com/questions/34629613/how-to-profile-tensorflow-networks

**Comment by poxvoculi** [comment]
Yes, it would be very useful to have better tools to analyze and predict TensorFlow program costs, in terms of time, memory and other resource needs.

TensorFlow programs can be analyzed both statically and dynamically.  Your questions seem to me to suggest that maybe the properties in which you're interested can be discovered through static analysis.  

By and large, through static analysis one can determine the Tensor shapes and hence sizes of Variables.  Whether or not a given Variable functions as a model parameter is another question.    

The maximum memory required to execute a program is harder to get through static analysis because it depends on the extent to which memory intensive operations not otherwise constrained may overlap in time.  This may be non-deterministic, or determined by the runtime by rules that go beyond the denotational semantics of TensorFlow.  For example, there is the possibility of leaving values in memory for a long time, or recomputing them on demand, when the cost of doing so is less than the cost of leaving the memory occupied.  A version of this strategy is swapping values between CPU and GPU memory to free GPU memory for a period.

Determining the number of operations required to execute a node is also difficult for static analysis, so long as the Op implementing the node is opaque to the analysis, i.e. if you're not able to examine the actual machine instructions generated by the compiler.  In this case it seems more practical to dynamically measure the time or cycles consumed by an Op and use that to estimate its cost.

Better runtime profiling tools would be a welcome addition.
