### ISSUE TITLE
N_class from DNN estimator Problem

### ISSUE THREAD

**Issue by Zark02** [tensorflow/tensorflow#21471]
`assertion failed: [Label IDs must >= 0]`
I am getting this class again and again and i can not understand why.
Please tell me what is label and n_class?
i have 3 labels and they are asking me to make n_class greater than labels. When i do it, it does not do anything.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by Zark02** [comment]
Is it possible to put a range numbers of values under one label?
How to do that? I have research on internet but i could not find it. Any hint?
lets suppose i want to put 10,000 data under "+" operator. Now there are two ways, either i put 10,000 labels to 10,000 values which is a stupid approach or i can put all values under "+" operator. How to do that? And these values are totally different. They have no link with each other.

**Comment by reedwm** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
