### ISSUE TITLE
python XML content control

### ISSUE THREAD

**Issue by zerok01** [tensorflow/tensorflow#21583]
Below is a code snippet from the XML content that annotates the object tag and annotates it. Some XML files do not have an object tag. In this case it gives a keyError error. How can I pass such xml files without giving keyError

        annotation = read_xml(annotation_path)
        image = read_image(image_path)

        gt_boxes = []

        for b in annotation['object']:
            try:
                label_id = self.classes.index(b['name'])
            except ValueError:
                continue

            gt_boxes.append({
                'label': label_id,
                'xmin': b['bndbox']['xmin'],
                'ymin': b['bndbox']['ymin'],
                'xmax': b['bndbox']['xmax'],
                'ymax': b['bndbox']['ymax'],
            })
I want to put a control code above "for b in annotation['object']:" command. Help me please

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by michaelisard** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
