### ISSUE TITLE
how to remove nodes from restored graph?

### ISSUE THREAD

**Issue by githubgsq** [tensorflow/tensorflow#21599]
hi, all:
   I restored a graph from a meta file.
```python
    saver = tf.train.import_meta_graph(LOCAL_TRAINED_MODEL_DIR+'/saved_model-0.meta')
    saver.restore(sess, tf.train.latest_checkpoint(LOCAL_TRAINED_MODEL_DIR))
    graph = tf.get_default_graph()
```

how could I delete some nodes from the default graph? The nodes can be accessed by get_tensor_by_name(). and could I reuse the trained weights please? 
    Thanks!

**Comment by asimshankar** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
