### ISSUE TITLE
TF lite can build & run on Linux?

### ISSUE THREAD

**Issue by david456314** [tensorflow/tensorflow#21592]
As the title says, is tf lite can be built and ran on non-mobile environment, such as Linux or others:

**Comment by gargn** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
