### ISSUE TITLE
MatMul Broadcasting / tensordot

### ISSUE THREAD

**Issue by allentran** [tensorflow/tensorflow#216]
It would really help if `matmul()` and element-wise `mul()` were broadcastable, like in Numpy.  Otherwise you're writing a bunch of boilerplate reshaping code.

For example, suppose I have a `T x n x k` and want to multiply it by a `k x k2`, and then to a max pool over `T` and then a mean pool over `n`.  To do this now, I think you need to reshape, do the `matmul()` and then undo the reshape and then do the pooling.

**Comment by vrv** [comment]
element-wise mul should do broadcasting already, but feature requested noted for matmul.  Thanks!

**Comment by vladfi1** [comment]
I was going to open my own issue on this, but it seems that this one is being used for everything related to batch matrix-vector ops, `numpy.dot`, etc. For those looking for a workaround, I have two implementations of batch vector x matrix multiplication:

```python
def batch_vm(v, m):
  shape = tf.shape(v)
  rank = shape.get_shape()[0].value
  v = tf.expand_dims(v, rank)
  
  vm = tf.mul(v, m)
  
  return tf.reduce_sum(vm, rank-1)

def batch_vm2(x, m):
  [input_size, output_size] = m.get_shape().as_list()
  
  input_shape = tf.shape(x)
  batch_rank = input_shape.get_shape()[0].value - 1
  batch_shape = input_shape[:batch_rank]
  output_shape = tf.concat(0, [batch_shape, [output_size]])
  
  x = tf.reshape(x, [-1, input_size])
  y = tf.matmul(x, m)
  
  y = tf.reshape(y, output_shape)
  
  return y
```

The first is based on the broadcasting behavior of `tf.mul`, while the second relies on reshaping all but the last dimension of the input to reduce the operation down to matrix-matrix multiplication. I suspect the second method is more efficient, but it might rely on the tensors being in the right memory order (although I think tf, unlike numpy, only uses C order).

**Comment by girving** [comment]
This issue appears to be covered by the more specific #1062.  @vladfi1: Does #1062 do what you want, or does `tf.batch_matmul` work now?  We can reopen if not, but we should try to make the issue more specific if so.

**Comment by alessiob** [comment]
Hi, I have a similar problem with which I've been struggling.

I need to encode my input data as a 4D tensor:
`X = tf.placeholder(tf.float32, shape=(None, None, None, 100))`
The first dimension is the size of a batch, the second the number of entries in the batch.
You can imagine each entry as a composition of a number of objects (third dimension). Finally, each object is described by a vector of 100 float values.

Note that I used None for the second and third dimensions because the actual sizes may change in each batch. However, for simplicity, let's shape the tensor with actual numbers:
`X = tf.placeholder(tf.float32, shape=(5, 10, 4, 100))`

These are the steps of my computation:

1. compute a function of each vector of 100 float values (e.g., linear function)
`W = tf.Variable(tf.truncated_normal([100, 50], stddev=0.1))`
`Y = tf.matmul(X, W)`
**problem**: no broadcasting for `tf.matmul()` and no success using `tf.batch_matmul()`
expected shape of Y: (5, 10, 4, 50)

2. applying average pooling for each entry of the batch (over the objects of each entry):
`Y_avg = tf.reduce_mean(Y, 2)`
expected shape of Y_avg: (5, 10, 50)

I expected that `tf.matmul()` would have supported broadcasting. Then I found `tf.batch_matmul()`, but still it looks like doesn't apply to my case (e.g., W needs to have 3 dimensions at least, not clear why).

BTW, above I used a simple linear function (the weights of which are stored in W). But in my model I have a deep network instead. So, the more general problem I have is automatically computing a function for each slice of a tensor. This is why I expected that `tf.matmul()` would have had a broadcasting behavior (if so, maybe `tf.batch_matmul()` wouldn't even be necessary).

Look forward to learning from you!
Alessio

**Comment by PistaSaki** [comment]
I don't think this should be closed -- the matmul does not broadcast in tensorflow 1.3.0. Here is a minimal example: 
```
import numpy as np
import tensorflow as tf
import numpy.random as rnd

A = rnd.randint(10, size = (5, 2, 2)).astype(np.float)
B = rnd.randint(10, size = (1, 2, 2)).astype(np.float)

print("Numpy broadcasts the first index as expected:")
print( np.matmul(A, B))

print("Tensorflow throws an exception:")
print( tf.matmul(A, B))
```

**Comment by PeterMitrano** [comment]
I am surprised that the example above fails. I would like to contribute a fix to support this. Would a PR for supporting this be considered? Or is there some ambiguity/complexity I'm not seeing?

**Comment by rhaps0dy** [comment]
I am surprised that so few people have this problem. I suppose it doesn't crop up often if you only do neural networks.

As a temporary workaround, I'm using this:
```
def broadcast_matmul(A, B):
    "Compute A @ B, broadcasting over the first `N-2` ranks"
    with tf.variable_scope("broadcast_matmul"):
        return tf.reduce_sum(A[..., tf.newaxis] * B[..., tf.newaxis, :, :],
                             axis=-2)
```

which is probably not very efficient but it works. Are you implementing it in the proper `matmul` operation, @PeterMitrano ?

**Comment by talhasaruhan** [comment]
I found tensordot() useful when broadcasting is needed.

`
# a : tensor of shape [2, 3, 3]
a = tf.constant([[[1, 2, 3], [2, 3, 4], [1, 4, 5]], [[5, 6, 7], [6, 3, 4], [9, 0, 1]]])
# b : tensor of shape [3, 4]
b = tf.constant([[2, 3, 4, 5], [8, 9, 1, 5], [0, 9, 0, 2]])
# c : tensor of shape [2, 3, 4] where c[i, ...] = dot(a[i, ...], b)
c = tf.tensordot(a, b, axes=1)
`

**Comment by rhaps0dy** [comment]
`tensordot` only does batch matrix multiplication when one of the two is a rank-2 tensor, though.

**Comment by vdutor** [comment]
I am also quite bothered by this. The same problem arises in the `tf.matrix_triangular_solve` as well. Currently, I am using `tf.einsum` as a workaround.

**Comment by TheButlah** [comment]
I would also like tf.matmul to broadcast properly. It becomes a problem when trying to add a fully connected or softmax layer in an RNN:
`outputs = tf.stack(outputs, axis=1, name='Outputs')  # Shape is [batch, sequence, embedding]
    with tf.name_scope('Softmax'):
        w = tf.get_variable(
            name='Weight',
            initializer=tf.truncated_normal([rnn_cell.output_size, embedding_size], stddev=0.01))
        b = tf.get_variable(name='Bias', initializer=tf.zeros(embedding_size))

        scores = tf.matmul(outputs, w) + b  # Fails with ValueError: Shape must be rank 2 but is rank 3 for 'Softmax/MatMul' (op: 'MatMul') with input shapes: [?,50,256], [256,2569].

        softmax = tf.nn.softmax(scores, name='Softmax')`

**Comment by shoyer** [comment]
I think proper broadcasting support for `tf.matmul()` would pretty clearly be a welcome addition to TensorFlow. There is certainly plenty of interest in it, and it is backwards compatible with how `tf.matmul()` currently works.

I suspect full support for the semantics of `@` as described in https://github.com/tensorflow/tensorflow/issues/1062#issuecomment-225882004 would also be welcome, but supporting matrix-vector, vector-matrix and vector-vector multiplication with `tf.matmul()` would warrant more discussion given the potential for confusion.

**Comment by guidocalvano** [comment]
I would also welcome broadcasting for matmul, because without broadcasting it is necessary to use tiling instead. Profiling shows this tiling is what I (and probably anyone else in need of broadcasting) lose the largest part of my (/our) processing power on. It seems plausible that a clever matmul broadcasting implementation can prevent any actual copying and thus speed up all our code by potentially eliminating the rate limiting step.

Note that capsule and matrix capsule networks (two new networks released by Hinton) could potentially benefit a lot from a broadcasting matmul; see https://github.com/ageron/handson-ml/blob/master/extra_capsnets.ipynb (specifically section Compute the Predicted Output Vectors)

**Comment by ModarTensai** [comment]
I am using this until an official implementation comes around (inspired by @talhasaruhan):
```python
import numpy as np
import tensorflow as tf

def batch_matmul(A, B):
    '''Batch support for matrix matrix product.

    Args:
        A: General matrix of size (A_Batch, M, X).
        B: General matrix of size (B_Batch, X, N).

    Returns:
        The result of multiplying A with B (A_Batch, B_Batch, M, N).
    '''
    if A.ndim == B.ndim:
        return tf.matmul(A, B)  # faster than tensordot
    with tf.name_scope('matmul'):
        AB = tf.tensordot(A, B, axes=[A.ndim - 1, B.ndim - 2])
        if B.ndim > 2:  # only if B is batched, rearrange the axes
            A_Batch = np.arange(A.ndim - 2)
            M = len(A_Batch)
            B_Batch = (M + 1) + np.arange(B.ndim - 2)
            N = (M + 1) + len(B_Batch)
            perm = np.concatenate((A_Batch, B_Batch, [M, N]))
            AB = tf.transpose(AB, perm)
    return AB
```
This code would still work even if both A_batch and B_batch had multiple axes or none at all. The only caveat here is when B_Batch is not empty; the shape of the output tensor would be `(A_Batch, M, B_Batch, N)`, which requires calling `tf.transpose()` that [copies the full tensor](https://www.tensorflow.org/versions/r1.9/api_docs/python/tf/transpose) instead of creating an efficient view (on TensorFlow version 1.9 and older). I believe an efficient impelmentation of reshaping the inner-most axes of a tensor as a view would solve this issue but I am not aware of such function.

**Comment by GSPP** [comment]
I understand that any fully connected NN layer requires matmul. Also, if you want performance then you *need* batching. So does this not mean that pretty much *any* neural network implementation has a need for batched matmul? What's the recommended way to do this? Many solutions are proposed here or on the web but they all seem to rely on copying lots of data causing loss of performance.

**Comment by rhaps0dy** [comment]
Hi @GSPP , 

>I understand that any fully connected NN layer requires matmul

Yep!

>So does this not mean that pretty much any neural network implementation has a need for batched matmul?

Actually, no. If you had a single example, x which is a vector, and you wanted to apply the weights and compute Wx, you need a matrix-vector multiplication. If you have a minibatch of inputs, then X is a matrix, and you compute X@W which is a matrix-matrix multiplication. At no point you need a batched matrix multiplication.

Batched matmul would be needed if, for example, you need to do a matrix-matrix multiplication for every training example and then you need to minibatch them.

Additionally, batched matmul _is_ currently supported. What isn't supported is _broadcasted_ batch matmul, that is, when you want to do W@X and then W is of shape [1, a, b] and X is of shape [c, b, d].

**Comment by GSPP** [comment]
@rhaps0dy you are right and this explains, why my implementation is so complicated :grin:. Thanks for clarifying.

**Comment by rueberger** [comment]
Has there been any progress with this? I too find this to be a highly desirable feature. 

Couldn't it easily be implemented with tensordot and a transposition?   Like this:

```python
def broadcasted_matmul(A, B):
    """ Matmul with fast broadcasting

    Args:
      A - [n, m]
      B - [batch_size, m, k]

    Returns:
      AB - [batch_size, n, k]
    """
    # [n, batch_size, k]
    AB = tf.tensordot(A, B, axes=[[1], [1]])
    # [batch_size, n, k]
    return tf.tranpose(AB, [1, 0, 2])
```

**Comment by edvinsson** [comment]
You could also do this using a conv1d layer with a kernel size of 1. For instance in @TheButlah examples above one could use (dims etc from above): 

```
outputs = tf.stack(outputs, axis=1, name='Outputs')
scores = tf.layer.conv1d(inputs=outputs, kernel_size=1, filters=2569,  kernel_initializer=layers.xavier_initializer())
softmax = tf.nn.softmax(scores, name='Softmax')
```
This is an equivalent operation and produces the desired output of [?,50,2569]. This is obviously only practical if one of the matrices is a parameter of the model and not calculated from the data.

**Comment by brianwa84** [comment]
Dreams coming true:
https://github.com/tensorflow/tensorflow/commit/47ab68d265a96b6e7be06afd1b4b47e0114c0ee9

**Comment by srvasude** [comment]
Going to close this issue since matmul now broadcasts, and the forward compatibility window has passed. This means if you are on tf-nightly, tf.linalg.matmul will broadcast (and users of LinearOperator will also feel the performance improvements of this).
