### ISSUE TITLE
AttributeError: module 'tensorflow.contrib.lite.python.convert_saved_model' has no attribute 'convert'

### ISSUE THREAD

**Issue by jimenisimo** [tensorflow/tensorflow#21618]
### System information
- **OS Platform and Distribution: Linux Ubuntu 16.04**:
- **TensorFlow installed from source**:
- **TensorFlow version 1.10**:
- **Python version 3.6**:
- **Bazel version Build label: 0.16.0**:
- **Exact command to reproduce: convert_saved_model.convert(saved_model_dir=saved_model, output_tflite="/TF_Lite_Model")**:

I am trying to convert my premade DNN Model to tflite file, using the function:

from tensorflow.contrib.lite.python import convert_saved_model
**convert_saved_model.convert**(saved_model_dir=saved_model, output_tflite="/TF_Lite_Model")

I have the last verison of tensorflow installed 1.10
I am using UBUNTU 16.04

the error is the following:

AttributeError: module 'tensorflow.contrib.lite.python.convert_saved_model' has no attribute 'convert'

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by poxvoculi** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by gargn** [comment]
This issue has been reported on [Stack Overflow](https://stackoverflow.com/questions/51863312/attributeerror-module-tensorflow-contrib-lite-python-convert-saved-model-has).
