### ISSUE TITLE
What is the python mechanism to "Bring in all of the public TensorFlow interface into this # module." in tensorflow/__init__.py

### ISSUE THREAD

**Issue by 1070933148** [tensorflow/tensorflow#21651]
What is the python mechanism to "Bring in all of the public TensorFlow interface into this module." in tensorflow/__init__.py.

I don't see an explicit command to import any functions like tf.reduce_sum.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by reedwm** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
