### ISSUE TITLE
Can't connect to docker as remote interpreter when running on a remote machine

### ISSUE THREAD

**Issue by thebeancounter** [tensorflow/tensorflow#21792]
I am using the container on a remote machine

When I run regular python on it, I use pycharm to run ssh interpreter, it syncs the needed directories and runs the wanted scripts and works great, 

I need the docker to somehow expose it's filesystem and interpreter on a host's port and connect to it via pycharm remote interpreter (from another machine)

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by asimshankar** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
