### ISSUE TITLE
How can I solve the problem ?

### ISSUE THREAD

**Issue by Jiangnan-Bridge** [tensorflow/tensorflow#21882]
jiangnanqiao@jiangnanqiao-Lenovo-B40-80:~$ which pip
/home/jiangnanqiao/.local/bin/pip
jiangnanqiao@jiangnanqiao-Lenovo-B40-80:~$ export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.3.0-cp27-none-linux_x86_64.whl
jiangnanqiao@jiangnanqiao-Lenovo-B40-80:~$ sudo pip install $TF_BINARY_URL[sudo] password for jiangnanqiao: 
The directory '/home/jiangnanqiao/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/jiangnanqiao/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
tensorflow-1.3.0-cp27-none-linux_x86_64.whl is not a supported wheel on this platform.

My os is 64 bits,windows&ubuntu16.04.I know little about this and I want to solve the problem.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
