### ISSUE TITLE
how to convert std::vector<float> to tensor in c++

### ISSUE THREAD

**Issue by anteagle** [tensorflow/tensorflow#2194]

**Comment by mrry** [comment]
Hi there!

> GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

I'm going to close this issue because it's a question rather than a bug, but if you'd like to ask it on Stack Overflow then one of the team will respond with an answer (and it will be easier for other people to find if they hit the same problem).
