### ISSUE TITLE
TensorFlow Speech Recognition for Android

### ISSUE THREAD

**Issue by sravanshty** [tensorflow/tensorflow#22055]
Hello,

I am new to this exicted feature TensorFlow. I could import the Sample project and able to run it successfully. Now i just need help to how to build the Speech Recognition from TensorFlow what are the files required to add. Can someone give the steps, which would help me in my sample application

Thanks
Sravan Kumar Shetty

**Comment by sravanshty** [comment]
Thanks for your quick response.


OS Platform and Distribution : Android
TensorFlow installed from : N/A
TensorFlow version : N/A
Bazel version: N/A
CUDA/cuDNN version: N/A
GPU model and memory: N/A
Exact command to reproduce: N/A
Mobile device : Android Lollipop version

Here actually i am beginner to this. So i just wanted to know what are the installation, libraries required for Speech Recognition in order to integrate to Android Mobile application. using Desktop : Window-10 

Thanks

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
