### ISSUE TITLE
The latest process of building tensorflow serving

### ISSUE THREAD

**Issue by HowieChang7** [tensorflow/tensorflow#22211]
Hi, friends, can someone tell me the latest process of building tensorflow serving? I have tried the methods provided by the official documentation, but it failed, I need your help.

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment]
@HowieChang7 Please refer [here](https://stackoverflow.com/questions/51554543/build-tensorflow-serving-for-python3-failed) for issues related to building tf serving.

Also, this question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the issue template. Thanks!
