### ISSUE TITLE
bazel build branch r1.10 on windows ERROR _api_implementation.so

### ISSUE THREAD

**Issue by whb0219** [tensorflow/tensorflow#22243]
ERROR: C:/users/thinkpad/_bazel_thinkpad/26orbg4z/external/protobuf_archive/BUILD:645:1: C++ compilation of rule '@protobuf_archive//:python/google/protobuf/internal/_api_implementation.so' failed (Exit 1): cl.exe failed: error executing command

C:\users\thinkpad\_bazel_thinkpad\26orbg4z\execroot\org_tensorflow\external\protobuf_archive\python\google\protobuf\internal\api_implementation.cc : fatal error C1083: 无法打开编译器生成的文件: “”: Invalid argument
Target //tensorflow/tools/pip_package:build_pip_package failed to build
INFO: Elapsed time: 22363.015s, Critical Path: 4574.16s
INFO: 6185 processes: 6185 local.
FAILED: Build did NOT complete successfully

How to solve compilation errors?
Thank you

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by whb0219** [comment]
Versions:Windows 10 64bit
VS2017 with VS2015 workload 
Python 3.6.6
Bazel 0.15.2
TensorFlow r1.10 CPU version

**Comment by skye** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
