### ISSUE TITLE
Calculating custom metrics with tf.estimator.DNNRegressor in TensorFlow 1.10

### ISSUE THREAD

**Issue by imanirajian** [tensorflow/tensorflow#22248]
How to configure a `tf.estimator.DNNRegressor` to report different metrics like **RMSE** and **MAE** while evaluating?

(One can ask the same question for `tf.estimator.DNNClassifier` and **AUC** metric)

> **Note:** I know that it must be done in `tf.estimator.EstimatorSpec` of `model_fn()` for a custom `tf.estimator.Estimator`, but I don't know how to apply it for a `tf.estimator.DNNRegressor`.

[https://stackoverflow.com/q/52300519/2737801](https://stackoverflow.com/q/52300519/2737801)

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
