### ISSUE TITLE
Impossible to initialize Variable, restored from a model, in Java API?

### ISSUE THREAD

**Issue by okdzhimiev** [tensorflow/tensorflow#22362]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
Yes
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
Linux Ubuntu 16.04
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**:
N/A
- **TensorFlow installed from (source or binary)**:
binary via pom.xml:
```
<dependency>
     <groupId>org.tensorflow</groupId>
     <artifactId>libtensorflow</artifactId>
     <version>1.10.0</version>
 </dependency>
 <dependency>
     <groupId>org.tensorflow</groupId>
     <artifactId>libtensorflow_jni_gpu</artifactId>
     <version>1.10.0</version>
 </dependency>
```

- **TensorFlow version (use command below)**:
1.10.0
- **Python version**:
Using Java
- **Bazel version (if compiling from source)**:
N/A
- **GCC/Compiler version (if compiling from source)**:
N/A
- **CUDA/cuDNN version**:
9.0/7.0.5
- **GPU model and memory**:
GeForce GTX 750 Ti
- **Exact command to reproduce**:
N/A

### Describe the problem

Trying to run inference in Java from a restored model, getting:

```java.lang.IllegalStateException: Attempting to use uninitialized value```

Same thing works in Python.

The  model is not trivial - 2 stages with intermediate data stored in that uninitialized variable in GPU.

To workaround would like to initialize it. Looked through Operation and OperationBuilder classes - nothing.

Able to get the variable using:
```
Operation ooyoo = bundle.graph().operation("rv_stage1_out");
System.out.println(ooyoo.toString());
System.out.println(ooyoo.type());
```
getting:
```
<VariableV2 'rv_stage1_out'>
VariableV2
```

How to assign?

### Source code / logs
[Code](https://git.elphel.com/Elphel/imagej-elphel/blob/gpu/src/main/java/TensorflowExamplePlugin.java)

More information as well as code and logs are posted on [Stackoverflow](https://stackoverflow.com/questions/52394799/tensorflow-1-10-0-java-api-java-lang-illegalstateexception-attempting-to-use-u).

**Comment by okdzhimiev** [comment]
Silence is golden =)

**Comment by okdzhimiev** [comment]
Alright, I think I have found the solution. 
That variable belonged to LOCAL_VARIABLES - adding to GLOBAL collection (in Python) and storing then restoring seems to have fixed the error. Meaning, in Java there might be only some kind of equivalent of a global initializer if applicable. Need to double test.

**Comment by asimshankar** [comment]
I didn't get a chance to dig into the code linked to (there is a lot of it), but yeah, I'd also guess that there is some additional operation you're running to initialize variables in the Python side that isn't being run on the Java side.

If it is the local variables initializer, one option would be to provide `tf.local_variables_initializer()` as [the `main_op` or `legacy_init_op` to `SavedModelBuilder.add_meta_graph()`](https://www.tensorflow.org/api_docs/python/tf/saved_model/builder/SavedModelBuilder#add_meta_graph), so that the variables are initialized just when you load the program.

If you could provide a more compact reproduction, I'm happy to take a look. If not, I'll try to dig into the Python and Java code provided when I get a chance. Or if things have worked out, let me know and I'll close the issue (and feel free to add details here). Thanks.

**Comment by okdzhimiev** [comment]
Yes, that extra operation is:
`sess.run(tf.local_variables_initializer())`

Just tested - your suggestion works - Java will read the saved-in-python-model w/o errors:
```python
builder = tf.saved_model.builder.SavedModelBuilder('somedir')
builder.add_meta_graph_and_variables(sess,[tf.saved_model.tag_constants.SERVING],main_op=tf.local_variables_initializer())
# builder.add_meta_graph_and_variables(sess,[tf.saved_model.tag_constants.SERVING])
# builder.save(True)
builder.save(False) # True = *.pbtxt, False = *.pb
```
log output:
```
2018-09-20 13:48:40.812262: I tensorflow/cc/saved_model/loader.cc:90] Running MainOp on SavedModel bundle.
```
Thanks.
