### ISSUE TITLE
Tensorflow Object Detection - Car is wrongly detected as N/A

### ISSUE THREAD

**Issue by MalathiKaliyappan** [tensorflow/tensorflow#22375]
In Google-colab I am trying to detect car using Tensorflow Object-Detection API with SSD_mobilenet_v1_pets.config, it detect humans as car and car as N/A. The following are the  size config and image dimensions: 

anchor_generator {
      ssd_anchor_generator {
        num_layers: 6
        min_scale: 0.2
        max_scale: 0.95
        aspect_ratios: 1.0
        aspect_ratios: 2.0
        aspect_ratios: 0.5
        aspect_ratios: 3.0
        aspect_ratios: 0.3333
      }
    }
    image_resizer {
      fixed_shape_resizer {
        height: 300
        width: 300
      }

I have 1160 images with various dimensions (ex: 73 x 63, 118 x 62, 62 x 56, 71 x 56, 276 x 183, 259 x 184, 318 x 159, 700 x 420, 647 x 407, 897 x 554) 

This is the output I got:[enter image description here][1][enter image description here][2]

Please clarify, Is the problem of the wrong detection of car is because of the image dimensions or anything else?

  [1]: https://i.stack.imgur.com/eeau4.png
  [2]: https://i.stack.imgur.com/flkbA.png
![download](https://user-images.githubusercontent.com/39641762/45741779-186e8a00-bc16-11e8-92bf-462d46c20acb.png)
![download 1](https://user-images.githubusercontent.com/39641762/45741856-3dfb9380-bc16-11e8-9845-ec459818ebea.png)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
