### ISSUE TITLE
TensorFlow for Jetson TK1 (ARM + Cuda)

### ISSUE THREAD

**Issue by maxcuda** [tensorflow/tensorflow#224]
I have a gpu-enabled build for Jetson TK1 using CUDA 6.5 runtime and CUDNN 6.5.
This is a link to download the binary for the pip install if someone wants to try it:
https://drive.google.com/file/d/0B1uGKNpQ7xNqeTB4RFE2MXdNWUU/view?usp=sharing

Jetson  TK1 has a limited amount of memory ( CPU+GPU <2GB) so most of the examples will not run without modifications but aside from  Out Of Memory errors, TensorFlow runs just fine.

**Comment by ebrevdo** [comment]
Thank you for your contribution!  In general we encourage users with nonstandard setup to build their own pip packages from source.  And we are specifically encouraging the CUDA 7 runtime with CUDNN 6.5 because it's one less variable to consider when debugging (and this is the version we use and test with).  Since it doesn't seem like there's any issue, I'm closing / archiving this for now.
