### ISSUE TITLE
The scope of application for  Post-training quantization

### ISSUE THREAD

**Issue by mingrenbuke** [tensorflow/tensorflow#22625]
If I want to optimize tensorflow model running on linux,  can I use Post-training quantization? or can a tensorflow lite model run on linux?

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment]
@mingrenbuke Yes. For more information about Post training quantization, please refer [this.](https://www.tensorflow.org/performance/post_training_quantization)

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
