### ISSUE TITLE
How to resize one tensor to (e.g., 1.5 * its original shape)?

### ISSUE THREAD

**Issue by shampool** [tensorflow/tensorflow#2269]
The tensor shape is not fixed, and can change with different input.

**Comment by mrry** [comment]
Hi there. I'm going to close this issue because, as it says in the issue template:

> GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

You might find the [`tf.tile()`](https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#tile) and [`tf.pad()`](https://www.tensorflow.org/versions/r0.8/api_docs/python/array_ops.html#pad) ops useful, however. If you have further questions, please ask the question on Stack Overflow instead.
