### ISSUE TITLE
Will it cause performance loss, when the grads are IndexedSlices?

### ISSUE THREAD

**Issue by fortianyou** [tensorflow/tensorflow#22722]
https://github.com/tensorflow/tensorflow/blob/6f5d7a97cd2c0741ddfa756853ce5321377b5d53/tensorflow/contrib/distribute/python/cross_tower_ops.py#L313

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
