### ISSUE TITLE
The usage of CUDA_VISIBLE_DEVICES.

### ISSUE THREAD

**Issue by Fridgi** [tensorflow/tensorflow#22816]
I cannot figure out an ambigious definition of the env variable "CUDA_VISIBLE_DEVICES". As we know, the command `export CUDA_VISIBLE_DEVICES = 0`  means that we can only find the GPU:0. However, what's the defination of the command `export CUDA_VISIBLE_DEVICES = '' `? It means that we can either find all gpus or mask all gpus in our system?

And another odd thing is that I am running a BiLSTM-CRF model to do some NER tasks with a 8-gpu server. Without using the command `export CUDA_VISIBLE_DEVICES = '' `, the model runs a bit slower than expected, and we can see the program running with all 8 gpus through the command `nvidia-smi`. However, the model runs extremely faster than before when I use the command `export CUDA_VISIBLE_DEVICES = '' `, in addition, I cannot find any program information with `nvidia-smi`. 

Did I run the model with CPU? But the CPU usage changed only a little. And there seems no posibility that the CPU runs extremely faster than GPU under BiLSTM-CRF model. What's the matter?  If any information is needed, I'll update later cuz I don't know what information to display now.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
