### ISSUE TITLE
tfrecords-only size-1 arrays can be converted to Python scalars error

### ISSUE THREAD

**Issue by balajibalasubramanian** [tensorflow/tensorflow#22821]
![tfrecords_error](https://user-images.githubusercontent.com/26739210/46628024-f358a180-cb59-11e8-82e0-37f7eb7e8289.png)

**Comment by ymodak** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by balajibalasubramanian** [comment]
### System information
- I have not written any custom code
- OS Platform and Distribution :Debian GNU/Linux 9.5(GCP instance)
- Tensorflow installed using pip
- TensorFlow version:1.10.1
- Python version: 2.7.13
- CUDA Version: 9.2.148
- GPU model and memory: none
- Exact command to reproduce:
Dataset- DeepFashion-https://drive.google.com/drive/folders/0B7EVK8r0v71pWGplNFhjc01NbzQ
val_attr.npy file - https://drive.google.com/open?id=16Mya14JIojI8qOUnDtiR2etpKggkh7nn

import numpy as np
import tensorflow as tf

val_attr=np.load('/home/balajib26/new_exp/DeepFashion-Tensorflow/test_attr.npy')

def _int64_feature(value):
    return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

def _bytes_feature(value):
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

feature = { 'val_attr': _int64_feature(val_attr)}

error:
TypeError                                 Traceback (most recent call last)
<ipython-input-27-d64c9fcc250b> in <module>()
----> 1 feature = { 'val_attr': _int64_feature(val_attr)}

<ipython-input-19-c554b2e04247> in _int64_feature(value)
      1 def _int64_feature(value):
----> 2     return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))
      3 
      4 # _bytes is used for string/char values
      5 

TypeError: only size-1 arrays can be converted to Python scalars

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
