### ISSUE TITLE
[TF1.10][TRT5.0] TFTRT is still using libnvinfer.so.4 not 5, importing tensorflow.contrib.tensorrt failed

### ISSUE THREAD

**Issue by oscarriddle** [tensorflow/tensorflow#22855]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: NO
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7.0
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NO
- **TensorFlow installed from (source or binary)**: pip
- **TensorFlow version (use command below)**: 1.10
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: NO
- **GCC/Compiler version (if compiling from source)**: NO
- **CUDA/cuDNN version**: CUDA9.0 cuDNN 7.0.5
- **GPU model and memory**: TitanXP
- **Exact command to reproduce**: 'import tensorflow.contrib.tensorrt as trt'

### Describe the problem
New TensorRT version 5.0 is released from Nvidia official site. I downloaded it and try to import it inside tensorflow, which is called "TFTRT".
But below error popped out:
```
/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
**** Failed to initialize TensorRT. This is either because the TensorRT installation path is not in LD_LIBRARY_PATH, or because you do not have it installed. If not installed, please go to https://developer.nvidia.com/tensorrt to download and install TensorRT ****
Traceback (most recent call last):
  File "run_uff.py", line 4, in <module>
    from tensorflow.contrib.tensorrt import tensorrt as trt
  File "/home/web_server/dlpy72/dlpy/lib/python2.7/site-packages/tensorflow/contrib/tensorrt/__init__.py", line 34, in <module>
    raise e
tensorflow.python.framework.errors_impl.NotFoundError: libnvinfer.so.4: cannot open shared object file: No such file or directory

```
Seems the tensorflow is not updated for new TensorRT. Hope @samikama can take a look into this issue.

Thanks,

**Comment by samikama** [comment]
@oscarriddle, 

TF 1.10 is released long before TRT5.0 is released so it is not possible to have a prebuild pip TF package linking TRT5.0.  If you want, you can rebuild TF and use TRT5.0.

**Comment by yjiangling** [comment]
But the version TensorFlow-1.12.0 still gives the same error, what's wrong? The offical documents shows that the TensorRT-5.1.5 is compatible for the TensorFlow 1.12.0. It's weird.

Compatibility
‣ TensorRT 5.1.5 has been tested with the following:
‣ cuDNN 7.5.0
‣ TensorFlow 1.12.0
‣ PyTorch 1.0
‣ ONNX 1.4.1


>>> import tensorflow.contrib.tensorrt as trt
**** Failed to initialize TensorRT. This is either because the TensorRT installation path is not in LD_LIBRARY_PATH, or because you do not have it installed. If not installed, please go to https://developer.nvidia.com/tensorrt to download and install TensorRT ****
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/__init__.py", line 34, in <module>
    raise e
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/__init__.py", line 25, in <module>
    from tensorflow.contrib.tensorrt.python import *
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/__init__.py", line 22, in <module>
    from tensorflow.contrib.tensorrt.python.ops import trt_engine_op
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/tensorrt/python/ops/trt_engine_op.py", line 32, in <module>
    resource_loader.get_path_to_datafile("_trt_engine_op.so"))
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/contrib/util/loader.py", line 56, in load_op_library
    ret = load_library.load_op_library(path)
  File "/media/huaxin/tcl1/asr/yujiangling/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 60, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libnvinfer.so.4: cannot open shared object file: No such file or directory
