### ISSUE TITLE
Transfer Learning help

### ISSUE THREAD

**Issue by ArkaJU** [tensorflow/tensorflow#22870]
I am working on a sketch based image retrieval problem using Siamese network and have written the code in TensorFlow. Some people suggested to train the network on pretrained weights rather than training from scratch, but I am not sure how to implement it in TensorFlow. Online resources couldn't clear up my doubts completely. The repo link is given below:

https://github.com/ArkaJU/Sketch-Retrieval---Siamese/blob/master/SketchRetrieval.ipynb

I want to change the architecture to GoogLeNet and start with pretrained weights.
Any help is appreciated, thank you.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
