### ISSUE TITLE
TensorFlow Lite installation on Raspberry Pi

### ISSUE THREAD

**Issue by CycleMark** [tensorflow/tensorflow#23010]
Hi,

I've tried stackoverflow but thus far I've not had a reply - so feel free to close off is you feel this is unnecessary.

[https://stackoverflow.com/questions/52804669/tensor-flow-lite-raspberry-pi-installation](url)

I'm just looking from some clarity. I've build TF Lite on my RPi3 and the static lib's been created without issue.

At the moment python is returning the error:

> Traceback (most recent call last): 
>    File "label_image.py", line 23, in
>       <module> import tensorflow as tf

What I'm uncertain of is if it pip install TF then how can I know/be certain that I will get/be using TF Lite as apposed to the full version?

Also are there any stats re: TF Lite on the Pi vs full version for image classification?

Thanks & Regards

Mark

**Comment by tensorflowbutler** [comment]
Thank you for your post. We noticed you have not filled out the following field in the issue template. Could you update them if they are relevant in your case, or leave them as N/A? Thanks.
Have I written custom code
OS Platform and Distribution
TensorFlow installed from
TensorFlow version
Bazel version
CUDA/cuDNN version
GPU model and memory
Exact command to reproduce
Mobile device

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
