### ISSUE TITLE
[Bug or Not?] Variable and VarHandleOp has different initial value in creating slots in ExponentialMovingAverage 

### ISSUE THREAD

**Issue by wangsiyu** [tensorflow/tensorflow#23043]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: CentOS 7
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: None
- **TensorFlow installed from (source or binary)**: source 
- **TensorFlow version (use command below)**:  master
- **Python version**: 2.7
- **Bazel version (if compiling from source)**: 0.15.0
- **GCC/Compiler version (if compiling from source)**:  None
- **CUDA/cuDNN version**: 7.0
- **GPU model and memory**: None
- **Exact command to reproduce**: None

### Describe the problem
Variable and ResourceVariable has different initial value here. Is it a bug or expect action?
```
        # For variables: to lower communication bandwidth across devices we keep
        # the moving averages on the same device as the variables. For other
        # tensors, we rely on the existing device allocation mechanism.
        with ops.init_scope():
          if isinstance(var, variables.Variable):
            avg = slot_creator.create_slot(var,
                                           var.initialized_value(),
                                           self.name,
                                           colocate_with_primary=True)
            # NOTE(mrry): We only add `tf.Variable` objects to the
            # `MOVING_AVERAGE_VARIABLES` collection.
            ops.add_to_collection(ops.GraphKeys.MOVING_AVERAGE_VARIABLES, var)
          else:
            avg = slot_creator.create_zeros_slot(
                var,
                self.name,
                colocate_with_primary=(var.op.type in ["Variable",
                                                       "VariableV2",
                                                       "VarHandleOp"]))
            if self._zero_debias:
              zero_debias_true.add(avg)
        self._averages[var] = avg
```

**Comment by wangsiyu** [comment]
Hi, @alextp
  Sorry to bother you. This code seems have different initial value here. Is there any other consideration？
Thanks.

**Comment by alextp** [comment]
They will have different initial values if they are randomly initialized. TF requires you to specify an op seed when creating a random initializer if you want determinism; otherwise any change in the graph structure can change the internal seed used for the initializer leading to different values.

**Comment by wangsiyu** [comment]
Sorry，let me clarify this question. I mean why using create_slot in Variable branch but using create_zero_slot in VarHandleOp branch？

**Comment by yangjunpro** [comment]
@alextp I am afraid that you mis-understand our questions. What siyu tried to point out here is that for the same Variable stuff(in the if branch it is a normal Variable op, while in the else branch it is a ResourceVariableOp), in our understanding, either Variable op or ResourceVariable op should  have the same initialization value, otherwise ,that is a inconsistency. Could please kindly take a further look at our questions before closing it?

Thanks

**Comment by alextp** [comment]
Both ResourceVariable and RefVariable inherit from variables.Variable so they should both go through the initialized value mechanism.

Only a non-variable Tensor will trigger the zeros case.

**Comment by wangsiyu** [comment]
Thank you.

**Comment by fanshiqing** [comment]
@alextp Actually `DistributedValues` such as `MirroredVariable` will trigger the zeros case, is that as expected?

**Comment by wangsiyu** [comment]
Why treats Variables and Non-Variables different? Are they equivalent in mathematical ?

**Comment by alextp** [comment]
Variables are not a mathematical concept, so there's no mathematical justification for the difference. I don't know why this was implemented this way. I don't expect it to ever matter since it's an exponential moving average which is very independent of the initial value if you update it more than a few times.

We should probably make MirroredVariable and friends inherit from ResourceVariable not just for this, though. Please file an issue.

**Comment by wangsiyu** [comment]
I see. Thanks for your answer
