### ISSUE TITLE
QueueRunner going towards deprecation, but tf.data does not replace all usecases?

### ISSUE THREAD

**Issue by bjg2** [tensorflow/tensorflow#23067]
In my code I get QueueRunner deprecation warning:

```
QueueRunner.__init__ (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
```

Did a bit of investigation [here](https://www.tensorflow.org/guide/datasets) and it seems that tf.data is a new thing that is faster and better than the old queue stuff. But, as I understand, it it not replacing queues because data is expected to be static, (as far as I understood and of all the examples I saw), modification / appending new training data to the dataset is not supported, so I don't know how this change applies to the reinforcement learning, which learns on new data environment returns all the time. So, as far as I see, deprecation of queue runner is coming and I don't see tf.data replacing it for this usecase?

Any kind of explanation and example is welcome! Thanks!

PS. Started out this question [on stack overflow](https://stackoverflow.com/questions/52855870/queuerunner-going-towards-deprecation-but-tf-data-does-not-replace-all-usecases) first, but didn't get any solutions.

**Comment by dulex123** [comment]
Would love to hear a response for this one, having the same problem

**Comment by wt-huang** [comment]
For reinforcement learning, `tf.data` may have limited ability here. It is much more convenient to use Gym from Open AI. You can leverage a suite of methods and libraries and integrate them into training.

**Comment by wt-huang** [comment]
Closing as this is resolved, free to reopen if problem persists.

**Comment by wookayin** [comment]
@wt-huang @mrry I would like to revisit this issue it's getting closer towards TF 2.0, where all Queue APIs are going to be removed.

I agree that when it comes to reinforcement learning, queue APIs could be more powerful as I don't find any way to implement the similar behavior using `tf.data`. For example, replay buffers (used in IMPALA, Ape-X, or even in DQN, etc.) cannot be implemented easily using `tf.data`.

One particular scenario I ran into recently concerns an **"reentrancy"** issue. For example, let's consider a case where we need to **generate batches on-line** through running an environment simulator (Atari, DeepMind Lab, etc.) --- perhaps primarily because it's too expensive to store all image observations as dataset. To deal with this using `tf.data` API, we may use `Dataset.from_generator` which allows us to execute arbitrary python code as a TF operation, but the problem here is that non-reentrant generators will be broken. One example: some RL environments that use OpenGL, EGL hardware render, etc. should be used in the **same thread**, not on thread pools.

Perhaps the most straightforward and classic way (queue-based) is to have a **writer-reader** or **pub-sub** structure, say

* K parallel actors generates trajectory and put into the buffer/queue
* one or parallel reader thread reads from the queue and construct the batch as usual (prefetch, interleave, map, batch, etc.)

which would be quite a common pattern in RL. As @wt-huang mentioned one can use custom (parallel) utilities that generates batches, but it is desirable that they should run **in parallel** (like prefetch, etc.). 

I am still trying to figure out a good way of this particular use-cases (though I believe it's quite *general* in RL and online learning settings) to generate data on-line. However if we are doubtful `tf.data` fully supports this use cases, it might be a good idea to keep queue stuffs as V1-compat APIs, or implement a new `tf.data` API that can implement such a pub-sub pattern as well.

**Comment by mrry** [comment]
Hi @wookayin! We aren't removing *all* queue APIs in TF 2.0. In particular `FIFOQueue` and `RandomShuffleQueue` will remain in the 2.0 API (as `tf.queue.FIFOQueue` and `tf.queue.RandomShuffleQueue`), so you can continue to build arbitrarily sophisticated queuing networks in your code.

We have removed `tf.train.QueueRunner` from the 2.0 API (although it will continue to be available in `tf.compat.v1`), because it was only needed to support "transparent" thread creation in simple queue-based pipelines, and this is now more robustly handled inside `tf.data`. However, there is no magic inside `QueueRunner`, and you are free to create your own Python threads to move data between queues if that suits your workflow. Indeed, with eager execution in TF 2.0, it might be easier to build more of the simulation pipeline in pure Python code, rather than in graph-based data structures like `FIFOQueue`.

If you do have suggestions for a better future API for RL workloads, please do suggest it, either via the [TensorFlow RFC](https://github.com/tensorflow/community/tree/master/rfcs) repository, or the [SIG IO](https://github.com/tensorflow/io/) repository.

**Comment by passerbyd** [comment]
Queues are not only used for buffering input datas. And if queues are reserved, why queuerunners need to be removed. which makes users create their own runners? 
For tf.data, how to make it work like "shared queue"? (queue with shared_name) @mrry

**Comment by passerbyd** [comment]
> The existing QueueRunner API is tied to several TensorFlow 1.x concepts, like having a single global graph, collections, and the `tf.Session` interface. All of these are deprecated, and have been removed from the TensorFlow 2.0 API, except via the `tf.compat.v1` compatibility interface. As a result, QueueRunners don't make sense in TensorFlow 2.0, but you can still access them via `tf.compat.v1.train.QueueRunner` etc. if you're using the compatibility interface for other code.
> 
> Likewise, `shared_name` relies on TensorFlow 1.x `tf.Session` semantics, and there is no current equivalent in the 2.0 API. Using the compatibility interface, `tf.compat.v1.data.make_initializable_iterator(dataset, shared_name=...)` will create an iterator that will be shared between sessions on the same server.

how to initialize this shared iterator on two separated sessions? not found any reference. could you please show me an example. @mrry
