### ISSUE TITLE
Train the Model in android app

### ISSUE THREAD

**Issue by hoangduchuu** [tensorflow/tensorflow#23062]
I just finished three courses in CodeLab about Tensorflow.
I'm finding the way ***how can I train the Model on Android device instead of training from the computer and use that Model on Android***

**Comment by hoangduchuu** [comment]
that means, I want to build, train, and update the *.lite model and *label.txt in android

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
