### ISSUE TITLE
Cannot build tensorflow from source, Ubuntu 16.04

### ISSUE THREAD

**Issue by radiantone** [tensorflow/tensorflow#23178]
uname
Linux olympus 4.15.0-36-generic #39~16.04.1-Ubuntu SMP Tue Sep 25 08:59:23 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

CUDA 10

Trying to run ./configure to build tensorflow for cuda 10 but it doesn't work. bazel is complaining about many things..

The function 'set' has been removed in favor of 'depset', please use the latter. You can temporarily refer to the old 'set' constructor from unexecuted code by using --incompatible_disallow_uncalled_set_constructor=false

ERROR: error loading package '': Extension 'closure/filegroup_external.bzl' has errors

What are the exact steps to build successfully from source for linux?

**Comment by ymodak** [comment]
I apologize, but I am having a hard time understanding what the problem is, where the problem is, and what version it affects. Please resubmit and pay attention to the [issue template] (https://github.com/tensorflow/tensorflow/issues/new/choose). Please provide all the information it asks. Thank you.
