### ISSUE TITLE
text8.zip

### ISSUE THREAD

**Issue by Payam-Ebadi** [tensorflow/tensorflow#23189]
Hello Guys
previously the code was working on my MacBook, now it doesn't work and I don't understand why. I have the error below:

Traceback (most recent call last):
  File "/Users/payam/Desktop/tensorflow/tensorflow/examples/tutorials/word2vec/word2vec_basic.py", line 73, in <module>
    filename = maybe_download('text8.zip', 31344016)
  File "/Users/payam/Desktop/tensorflow/tensorflow/examples/tutorials/word2vec/word2vec_basic.py", line 69, in maybe_download
    raise Exception('Failed to verify {0}. Can you get to it with a browser?'.format(local_filename))
Exception: Failed to verify /var/folders/bp/cd99npls7q7g9y8f34lhwnq80000gn/T/text8.zip. Can you get to it with a browser?
9207808

Process finished with exit code 1

**Comment by ymodak** [comment]
It looks like you haven't provided the information requested by the template. We ask this because it will help us to narrow down our focus on your specific issue since system configurations can vary broadly Please resubmit and pay attention to the issue template (https://github.com/tensorflow/tensorflow/issues/new/issue). Please provide all the information it asks. Thank you.

**Comment by zhanchey** [comment]
have the same problem, have you solved this?
