### ISSUE TITLE
NameError: name 'init' is not defined

### ISSUE THREAD

**Issue by shikhar1sharma** [tensorflow/tensorflow#232]
I am getting the following error while trying MNIST tutorial

sessi.run(init,init)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'init' is not defined

**Comment by vrv** [comment]
That looks like a typo on your end (I can't find that snippet of code anywhere) -- please re-open with a way for us to reproduce the problem if there's a bug in our tutorial.  Thanks!

**Comment by vedhas** [comment]
I see typo in the post above, 'sessi' instead of 'sess'. 

I have run into same issue though, And here's my code:

num_neurons = 200
num_layers = 3
dropout = tf.placeholder(tf.float32)

cell = rnn_cell.GRUCell(num_neurons)  # Or LSTMCell(num_neurons)
cell = rnn_cell.DropoutWrapper(cell, output_keep_prob=dropout)
cell = rnn_cell.MultiRNNCell([cell] * num_layers)

#Simulating Time Steps
max_length = Sz_Max_GST #Sz_Max_LLD
# Batch size x time steps x features.
data = tf.placeholder(tf.float32, [None, max_length, Num_F_L])
target = tf.placeholder(tf.float32, [None, max_length, Num_G_L])
output, state = tf.nn.dynamic_rnn(cell, data, dtype=tf.float32,sequence_length=mylength(data))
yLogits=tf.contrib.layers.linear(output,1)

prediction=yLogits
cross_entropy = -tf.reduce_sum(target * tf.log(prediction))

train_step=tf.train.AdamOptimizer(1e-3).minimize(cross_entropy)
sess=tf.Session()
sess.run(init)

**Comment by vedhas** [comment]
No worries, I figured it out. :)

One should declare init as 
init=tf.global_variables_initializer()
