### ISSUE TITLE
Unnecessary gpu allocations when reusing resource variables that are initialized from checkpoint

### ISSUE THREAD

**Issue by WuTheFWasThat** [tensorflow/tensorflow#23236]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
**Yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
**Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
**binary**
- TensorFlow version (use command below):
**b'v1.11.0-rc1-0-ge4c4b20' 1.11.0-rc1**

- Python version:
**3.6.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
**9.2**
- GPU model and memory:
**Tesla K80**

**Describe the current behavior**
GPU memory is very high when using init_from_checkpoint and reuse=True with resource variables, in certain cases.

**Describe the expected behavior**
GPU memory should be at most parameters+activations

**Code to reproduce the issue**

```
#!/usr/bin/env python3

"""
# first:
python repro_bug.py --write_ckpt

# then, compare:
python repro_bug.py # good
python repro_bug.py --use_ckpt # bad
"""

import tensorflow as tf
from tensorflow.contrib.training import HParams
import fire

def model(*, X, hparams):
    with tf.variable_scope('model'):
        wte = tf.get_variable('wte', [hparams.n_vocab, hparams.n_embd],
                             initializer=tf.random_normal_initializer(stddev=0.02))
        h = tf.gather(wte, X)
        return tf.matmul(h, wte, transpose_b=True)

def main(
        batch_size=20, 
        length=100, # increase this to leak more memory!
        write_ckpt=False, use_ckpt=False, ckpt_path='/tmp/reprobug.ckpt',
        # hparams
        n_vocab=400, n_embd=300,
):
    hparams = HParams(n_vocab=n_vocab, n_embd=n_embd)

    if write_ckpt:
        with tf.Graph().as_default() as g:
            X = tf.placeholder(shape=[batch_size], dtype=tf.int32)
            results = model(X=X, hparams=hparams)
            saver = tf.train.Saver()
            with tf.Session() as sess:
                sess.run(tf.global_variables_initializer())
                saver.save(sess, ckpt_path)
        return

    X = tf.fill([batch_size], 0) # initial value
    for _ in range(length):
        # NOTE: doing something like reuse=(i > 0) doesn't help
        with tf.variable_scope('step', reuse=tf.AUTO_REUSE, use_resource=True):
            logits_flat = model(X=X, hparams=hparams)
        X = tf.squeeze(tf.multinomial(logits_flat, num_samples=1, output_dtype=tf.int32), axis=[1])

    if use_ckpt:
        print('setting initializers')
        tf.train.init_from_checkpoint(ckpt_path, {'/': 'step/'})

    config = tf.ConfigProto()
    config.gpu_options.visible_device_list = '0'
    with tf.Session(config=config) as sess:
        sess.run(tf.global_variables_initializer())

        run_metadata = tf.RunMetadata()
        sess.run(X, feed_dict={}, options=tf.RunOptions(trace_level=tf.RunOptions.HARDWARE_TRACE), run_metadata=run_metadata)
        mbs_in_use = []
        for dev_stat in run_metadata.step_stats.dev_stats[:]:
            for node_stat in dev_stat.node_stats[:]:
                for mem in node_stat.memory:
                    if mem.allocator_bytes_in_use and mem.allocator_name.startswith("GPU"):
                        mbs_in_use.append(mem.allocator_bytes_in_use // 1000000)
        print("mbs in use: " , " -> ".join(map(str, mbs_in_use)))

if __name__ == '__main__':
    fire.Fire(main)
```

**Other info / logs**

Output looks like this:
```
setting initializers
mbs in use:  0 -> 1 -> 1 -> 8 -> 10 -> 18 -> 27 -> 27 -> 35 -> [etc...]
```
without calling initialize_from_checkpoint, it looks like:
```
mbs in use:  0 -> 0 -> 0 -> 0 -> 0 -> 0 -> 0 -> 0 -> 0 -> 0 -> [etc...]
```

**Comment by WuTheFWasThat** [comment]
@girving

**Comment by WuTheFWasThat** [comment]
Also, I should mention that I was unable to reproduce the same error with a simple matrix multiply instead of this gather/multinomial business

**Comment by WuTheFWasThat** [comment]
Also reproducible with nightly, as of today, (version 1.13.0-dev20181025)

**Comment by alextp** [comment]
I'm a little confused; by reading your code it seems like the mbs in use grows not with time but with the number of ops being executed? As in, you're always running a single step, but in the case where you restore from checkpoint the memory grows as ops execute while in the case where you don't they do not, right?

Moreover, this growth happens not on the call to run global_variables_initializer but on the call to run the forward pass of the model.

This is very weird since you're not writing to any of the variables and running the forward pass shouldn't trigger more allocations. Can you print the partition graphs on the run metadata with and without checkpoint initialization so I can see what's different?

**Comment by WuTheFWasThat** [comment]
@alextp  Yes, your reading of the code is correct; it is quite weird!  `print(run_metadata.partition_graphs)` gives empty list in both cases.

**Comment by alextp** [comment]
Sorry, I should have been clearer; to output the partition graphs you need RunOptions(..., output_partition_graphs=True) in there as well.

**Comment by WuTheFWasThat** [comment]
The diff is quite large, so I'm uploading the results as files!
`good` = full output without checkpoints
`bad` = full output with checkpoints
`diff` = output of `diff good bad`
`2columncoloreddiff` = colored/2 column version

[Archive.zip](https://github.com/tensorflow/tensorflow/files/2550662/Archive.zip)

**Comment by alextp** [comment]
Ah, I see what is going on. It seems like the bad version is moving a lot of computation to the CPU because of int32 dtypes and colocation constraints. These copies are triggering more memory allocation, which is what you're seeing.

For example, look at the "step/model/gather" node, which runs on the CPU in the bad version and on the GPU on the good version, mostly because the variable is being placed on the CPU in the bad version.

Essentially, I think a fix is to stop force-placing the init op in the CPU (that is, deindenting the block which starts in https://github.com/tensorflow/tensorflow/blob/5fb8c844512f50ec58fe3b856c8718816d7a504a/tensorflow/python/training/checkpoint_utils.py#L321 ).

Can you do this and see if the issue goes away?

@jpienaar for FYI since this smells a lot like a colocation-group bug (which Jacques is working on removing from TF entirely) but is only indirectly so.

**Comment by WuTheFWasThat** [comment]
deindenting that line (and the 3 after) fixes it!  memory usage is fine and the partition_graphs are the same (modulo names)
