### ISSUE TITLE
a question about ,node naming rules of model network

### ISSUE THREAD

**Issue by zkl99999** [tensorflow/tensorflow#23240]
```
from keras import backend as K
In [40]: input = K.placeholder(ndim=3,name='x')

In [41]: input
Out[41]: <tf.Tensor 'x:0' shape=(?, ?, ?) dtype=float32>

In [42]: input2 = K.placeholder(ndim=3,name='x')

In [43]: input2
Out[43]: <tf.Tensor 'x_1:0' shape=(?, ?, ?) dtype=float32>
```
the name 'x:0' and 'x_1:0', the ':0' what mean, how to change it?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
