### ISSUE TITLE
Some problems in compile tensorflow in c++ (debug mode).

### ISSUE THREAD

**Issue by sevensix6** [tensorflow/tensorflow#23241]
Using tensorflow 1.8 and vs2015, evertime I compile the src file in debug mode, there is a problem like this:
![image](https://user-images.githubusercontent.com/33054583/47475426-d7d5e200-d84d-11e8-934b-8e493eb52ae3.png)
Even if I use a 32G computer. Any suggestions?

**Comment by ymodak** [comment]
Please try to use the latest version of TensorFlow and build again.
In addition, It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
