### ISSUE TITLE
I want to use the beamsearch in my seq2seq architecture. But I FAILED after working for a WHOLE afternoon!!!

### ISSUE THREAD

**Issue by MengofGaussianFitting** [tensorflow/tensorflow#23251]
[beam_search_prediction.py.zip](https://github.com/tensorflow/tensorflow/files/2514356/beam_search_prediction.py.zip)

error is about the attention wrapper i guess

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
