### ISSUE TITLE
 bazel-bin/$examples_dir/cifar10/cifar10_train --   in model_pruning  for No such file or directory

### ISSUE THREAD

**Issue by molyswu** [tensorflow/tensorflow#23284]
Hi,
bazel-bin/$examples_dir/cifar10/cifar10_train --pruning_hparams=name=cifar10_pruning,begin_pruning_step=10000,end_pruning_step=100000,target_sparsity=0.9,sparsity_function_begin_step=10000,sparsity_function_end_step=100000
bash: bazel-bin/contrib/model_pruning/examples/cifar10/cifar10_train: No such file or directory

Thank you for your help!

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
