### ISSUE TITLE
version ？

### ISSUE THREAD

**Issue by zkl99999** [tensorflow/tensorflow#23347]
ubuntu16.04  cuda9.2 cudnn7.1   tensorflow1.11  ，，
import tensorflow   error

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
