### ISSUE TITLE
Any detailed explain about timeline?

### ISSUE THREAD

**Issue by leoyang233** [tensorflow/tensorflow#23360]
I can not find a official and detailed timeline document telling me how to explain the timeline graph.
For example, what are the meaning and difference  of /device:GPU:0/stream:all and /job:localhost/replica:0/task:0/device:GPU:0, /job:localhost/replica:0/task:0/device:GPU:0? In a multi-gpu environment, why there is only /device:GPU:0/stream:all, where is the /device:GPU:1/stream:all?

**Comment by harshini-gadige** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
