### ISSUE TITLE
Tensorflow GPU setup issue on Ryzen 5 + 2080 RTX GPU + Ubuntu 18.04

### ISSUE THREAD

**Issue by ankitaggarwal-trantor** [tensorflow/tensorflow#23371]
Hi Team,

I am trying to setup tensorflow-gpu on my new machine with configuration AMD Ryzen 5 2600 + 2080 RTX GPU + Ubuntu 18.04. I have tried tensorflow-gpu docker, tensorflow build from source.

In docker image, it was exiting after first epoch without any error. 

And in other approach we are getting following errors:

ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory.

InvalidArgumentError (see above for traceback): Cannot assign a device for operation MatMul: Operation was explicitly assigned to /device:GPU:0 but available devices are [ /job:localhost/replica:0/task:0/device:CPU:0, /job:localhost/replica:0/task:0/device:XLA_CPU:0, /job:localhost/replica:0/task:0/device:XLA_GPU:0 ]. Make sure the device specification refers to a valid device.
	 [[node MatMul (defined at test.py:6)  = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/device:GPU:0"](a, b)]]

Please assist with right steps to setup tensorflow gpu on Ryzen 5 + 2080 RTX GPU + Ubuntu 18.04 machine. Quick response will be really appreciated.

Regards,
Ankit Aggarwal

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
