### ISSUE TITLE
car Detection 

### ISSUE THREAD

**Issue by Shruti-Mahajan** [tensorflow/tensorflow#23373]
Hi 
I only want to detect car objects. Can anybody tell me which tflite class used? So that I am able to detect only car object in Android.
Thanks!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
