### ISSUE TITLE
Build  model_pruning for bug

### ISSUE THREAD

**Issue by molyswu** [tensorflow/tensorflow#23392]
Hi,
bazel build -c opt examples/cifar10:cifar10_{train,val}
EERROR: Skipping 'examples/cifar10:cifar10_train': no such package 'tensorflow/contrib/examples/cifar10': BUILD file not found on package path
ERROR: no such package 'tensorflow/contrib/examples/cifar10': BUILD file not found on package path
Thank you for your help!

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
