### ISSUE TITLE
how to get the timestamp of the specified operation?

### ISSUE THREAD

**Issue by wangshuaizs** [tensorflow/tensorflow#23429]
Hi,

  I want to get the timestamp of some operations in each iterations when training DNN. I know timeline can do this, but after some experiments I found timeline caused performance loss. And I only need to get information about a few operations, so I wonder whether it possible to get the timestamp of the specified operation?

Thanks

**Comment by harshini-gadige** [comment]
@wangshuaizs  - Hi, please note that this question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. 

Please refer below links for your question. 
1) [Timestamp for TF](https://www.tensorflow.org/api_docs/python/tf/timestamp)
2) [More info](https://github.com/tensorflow/tensorflow/issues/5682)
