### ISSUE TITLE
Not getting position of detected objects

### ISSUE THREAD

**Issue by Shruti-Mahajan** [tensorflow/tensorflow#23448]
Hi 
Not able to get the position of detected objects.
Thanks

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
