### ISSUE TITLE
Does keras saved Model can output tensor?

### ISSUE THREAD

**Issue by beyondli** [tensorflow/tensorflow#23509]
I found H5 file saved by save API, the output is ONLY layer info supported which is not so convinced when deployed.
Is there exist method that can saved tensor info of Model ??
Thanks in andvance!

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
