### ISSUE TITLE
'Model' object has no attribute '_is_graph_network'

### ISSUE THREAD

**Issue by lingyuhaunti** [tensorflow/tensorflow#23510]
I create the model use Model(intput, output) function, but the model cannot use tf.keras.estimator.model_to_estimator(), why? The error is "'Model' object has no attribute '_is_graph_network'", I can't understand.

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
