### ISSUE TITLE
How to save tensorflow model and the model size is small?

### ISSUE THREAD

**Issue by Ariel-JUAN** [tensorflow/tensorflow#23521]
I met a weird thing. I try to reproduce a project, the author provides network architecture without training codes. So I write the training code to train using Tensorflow. The author also provides the model he trained.
![image](https://user-images.githubusercontent.com/30546375/47996051-35154180-e132-11e8-9129-153c32bed604.png)
Here is my model I saved: 
![image](https://user-images.githubusercontent.com/30546375/47996065-3fcfd680-e132-11e8-8fc9-8c6ae6439315.png)
I don't understand, if we use the same architecture, don't we get nearly the same model size? Why I save the model is so different with author provided..... Maybe I also save other parameters except weights.... Can anyone help me?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
