### ISSUE TITLE
tf.nn.embedding_lookup_sparse Converting sparse IndexedSlices Warning

### ISSUE THREAD

**Issue by davidenunes** [tensorflow/tensorflow#23558]
Using embedding_lookup_sparse raises the following warning:

`UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory. "Converting sparse IndexedSlices to a dense Tensor of unknown shape."`

Looking at embedding_lookup_sparse implementation, I suspect the issue comes from the `gather` after embedding lookup. 

```
ids = sp_ids.values
ids, idx = array_ops.unique(ids)

embeddings = embedding_lookup(...)
...
embeddings = array_ops.gather(embeddings, idx)
```
Is there a reason this op does not call `embedding_lookup` on `sp_ids.values` directly? As opposed to 
looking up the unique ids and calling gather on those rows ?

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
