### ISSUE TITLE
 The  compile error is to buid tensorflow1.4 source code in vs15

### ISSUE THREAD

**Issue by Yangjayhui** [tensorflow/tensorflow#23575]
Cmake tensorflow1.4 source code,but the error is unable to open file  to tensorflow.def  in vs15 windows

**Comment by harshini-gadige** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
