### ISSUE TITLE
remove reduce_ from established functions, make it closer to numpy

### ISSUE THREAD

**Issue by kirk86** [tensorflow/tensorflow#23688]
**System information**
- TensorFlow version (you are using): >>> tf.__version__
'1.11.0
- Are you willing to contribute it (Yes/No): I would like to but have no idea how.

**Describe the feature and the current behavior/state.**
Hi everyone. Thanks for your efforts in making tensorflow.
I've been using tensorflow for some time now and no matter my usecase I always find myself in the position of having forgotten how to call the max, sum, ..., etc. functions. I find that the current naming is utterly confusing and doesn't help ppl to easily learn and integrate with the api. It would have been much better if all possible functions were as close as possible to numpy naming conventions. Trying to translate code from some other framework that follows a numpy naming conventions I find myself typing `tf.max` only then to realize that it doesn't exist. Then I have to spend time re-learning that is not `tf.max` but `tf.reduce_max`. Now it could be only me but I suspect that this kind of notation doesn't stick in to ppls long term memory.

**Will this change the current api? How?**
Yes. Most common functions will have the same naming convention to numpy.

**Who will benefit with this feature?**
All existing and new users.

**Any Other info.**
Please keep unnecessary complexity out of tensorflow.

**Comment by karmel** [comment]
This has come up before, but the answer has generally been that we will not alias these given that the expectation of matching Numpy would be met nominally, but not in full. It would be valuable to implement a more full numpy correspondence, but that is beyond the scope of the issue here. @asimshankar to correct the above if I have misstated it, but I will close this issue for now.
