### ISSUE TITLE
Error when running code from seq2seq translate model

### ISSUE THREAD

**Issue by mikeconnors909** [tensorflow/tensorflow#237]
Hi all,

I have trained my model on an english to french database, as specified in the tutorial. And yet, when I run this command 
```
./bazel-bin/tensorflow/models/rnn/translate/translate  --decode DECODE --train_dir /Users/User/train/
```
I get a pageful of errors like this:
```
tensorflow.python.framework.errors.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [1024] rhs shape= [256]
	 [[Node: save/Assign_3 = Assign[T=DT_FLOAT, use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](embedding_attention_seq2seq/RNN/MultiRNNCell/Cell0/GRUCell/Candidate/Linear/Bias, save/restore_slice_3)]]
```

What do I do?

**Comment by vrv** [comment]
My best guess: did you train with --size=256 ?  If so, you need to decode with the same set of command line flags as the one you trained with.

The error is basically saying that there is a size mismatch: the variable being assigned to is of size [256] but it expected [1024].  I don't see any sizes of '256' in the translate.py example, so that's why I suspect it was overridden via flags.

**Comment by mikeconnors909** [comment]
This worked, thanks!
