### ISSUE TITLE
Riccati solver suggest

### ISSUE THREAD

**Issue by zgbkdlm** [tensorflow/tensorflow#23735]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.7.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The Discrete/Continuous Algebraic Riccati Equation is very important to linear quadratic regulator system. A solution of solving this need to be implemented in Tensorflow if one wants to combine machine learning with control theory. 

The solver has been implemented in [Matlab](https://se.mathworks.com/help/control/ref/dare.html)/Scipy etc. But there are also possibilities to implement in Tensorflow CPU/GPU.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Those who wants to combine control theory with machine learning and deep leanring

**Any Other info.**

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by rmlarsen** [comment]
I believe that a Ricatti solver can be written using the existing linear algebra primitives in tf.linalg. I'm not sure such a solver belongs in TensorFlow itself. If there are lower-level algorithms missing from tf.linalg that make this difficult, please let us know.
