### ISSUE TITLE
warning "using ptxas 10.0.145, which is older than 9.2.88"

### ISSUE THREAD

**Issue by MikalaiDrabovich** [tensorflow/tensorflow#23874]
"*** WARNING *** You are using ptxas 10.0.145, which is older than 9.2.88"
https://storage.googleapis.com/tf-performance/tf_binary/tensorflow-1.12.0.a6d8ffa.AVX2.CUDA10-cp27-cp27mu-linux_x86_64.whl

https://github.com/tensorflow/tensorflow/blob/f827bad24efc949e657e141464ea1010c18d812c/tensorflow/compiler/xla/service/gpu/nvptx_compiler.cc#L427

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by ppwwyyxx** [comment]
This is a bug and has been fixed in https://github.com/tensorflow/tensorflow/commit/83ff640fa5026b8bd3cb9c2ceff9e99e8e03823a#diff-888940c777f83519bd1e27349427d51e .

**Comment by ymodak** [comment]
Closing since it has been resolved. Feel free to reopen the issue if the problem still persists. Thanks!

> This is a bug and has been fixed in [83ff640#diff-888940c777f83519bd1e27349427d51e](https://github.com/tensorflow/tensorflow/commit/83ff640fa5026b8bd3cb9c2ceff9e99e8e03823a#diff-888940c777f83519bd1e27349427d51e) .
