### ISSUE TITLE
StructuralEnsembleRegressor gives warning: Converting sparse IndexedSlices to a dense Tensor of unknown shape

### ISSUE THREAD

**Issue by wliangaz** [tensorflow/tensorflow#23893]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
I break down the stock example and run it on debug mode. I used my own sample data which has 1000 rows x 15 cols.  here's the code:
#----
    reader = tf.contrib.timeseries.CSVReader(csv_file_name,column_names=((tf.contrib.timeseries.TrainEvalFeatures.TIMES,)+ (tf.contrib.timeseries.TrainEvalFeatures.VALUES,) * N_COLS))
    train_input_fn = tf.contrib.timeseries.RandomWindowInputFn(reader, batch_size=N_COLS, window_size = 15)
    training_steps=150
    structural = tf.contrib.timeseries.StructuralEnsembleRegressor(periodicities=[7,100], num_features=N_COLS, cycle_num_latent_values=3)
    ff = structural.train(input_fn=train_input_fn, steps=training_steps)
#----
- OS Platform and Distribution: Windows 10, Anaconda, Python3.6
- TensorFlow installed from (source or binary): 1.12.0
- GPU model and memory: Quadro K2200

Checked related SO posts and tf source code (gradients_impl.py), looks to me this was due to that TensorFlow automatically densifies the tf.IndexedSlices for unknown shape.  This also makes it throw OOM error for slightly larger dataset (1000rows x 25cols). I also saw a note from gradient_impl.py that reads:
  # TODO(mrry): Consider adding static shape information to
  # IndexedSlices, to avoid using numpy here.

**Comment by rmothukuru** [comment]
@wliangaz,
Sorry for the delayed response. In the **`Tensorflow Version 2.x`**, since we use [TF Keras](https://www.tensorflow.org/api_docs/python/tf/keras/) and [tf.data](https://www.tensorflow.org/guide/data) predominantly and don't use [Estimators](https://www.tensorflow.org/guide/estimator) much, can you please let us know if this Feature is still relevant? 

Also, please refer [this Tutorial](https://www.tensorflow.org/tutorials/structured_data/time_series) which demonstrates the usage of [TF Keras](https://www.tensorflow.org/api_docs/python/tf/keras/) for **`Time Series Data`**.

Thanks!
