### ISSUE TITLE
error raised when convert srgan model to .tflite

### ISSUE THREAD

**Issue by zzqiuzz** [tensorflow/tensorflow#23917]
Hi! Recently, I've tried a lot to convert a SRGan model(.ckpt) to .tflite version.However,things dont go that smoothly.When i called the converted model(.tflite) in android studio, it ran just collapsed. Finally , i find it is two modules contained in the code which is pixelShuffler() that  account for the raised error. Because when i set input of that module as output node in the frozen graph,it works.But  i dived into the problematic module and found no operator not supported by tensorflow lite.And the code is @https://github.com/brade31919/SRGAN-tensorflow. So Has anyone converted GAN to .tflite successfully?

**Comment by ymodak** [comment]
Please provide details about what platform you are using (operating system, architecture). 
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:


You can collect some of this information using our environment capture [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with
python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jdduke** [comment]
Closing due to stale history, feel free to re-open if this is still an issue.
