### ISSUE TITLE
 Commonization of return value's type ​​of  tf.image.resize_image_with_crop_or_pad and tf.image.resize_images

### ISSUE THREAD

**Issue by elect000** [tensorflow/tensorflow#23959]
# system 
tensorflow ver.  tensorflow-gpu == 1.12.0

# rough source code
    
    from PIL import Image
    import tensorflow as tf 

    im = Image.open("hogehoge.jpeg")
    w, h = im.size

    raw_image = tf.read_file("hogehoge.jpeg")
    image = tf.image.decode_jpeg(raw_image, channels = 3) # rgb color image
    print(image.dtype) # => dtype : uint8
    image = tf.image.resize_image_with_crop_or_pad(image, w, w)
    print(image.dtype) # => dtype : unit8
    image = tf.image.resize_images(image, [128, 128])
    print(image.dtype) # => dtype : float32    ??????????????????????????????????????????

So, I want to commonization of return value's type of them. (I want  tf.image.resize_images will return value of dtype : uint8)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by elect000** [comment]
Oh, thanks. But I wandering that your [document](https://www.tensorflow.org/api_docs/python/tf/image/resize_image_with_crop_or_pad) says that these function (resize_images_with_crop_or_pad and resize_images) return a float tensor? (
In fact it is found that resize_images_with_crop_or_pad  is returning different values.)I think this problem cannot be resolved in StackOverflow and other cite.

(I'm sorry that I cannot descrive more information because this is not program or system problem.)

**Comment by tenggyut** [comment]
Agree!

Recently I have encounter this issue two...changing the dtype of the returned tensor is so confusing!
