### ISSUE TITLE
Tensors should have an "ndim" property

### ISSUE THREAD

**Issue by shoyer** [tensorflow/tensorflow#2395]
This is a useful shortcut property on NumPy arrays, and would nice to have in TensorFlow for the sake of cross-compatibility. `tensor.ndim` would be equivalent to `tf.rank(tensor)`.

**Comment by mrry** [comment]
You can call `Tensor.get_shape().ndims` to get the (inferred) rank of a tensor, but it is allowed to be `None` if the rank is unknown. Or you can call `tf.rank(tensor)` and the result is a `tf.Tensor` that you have to evaluate (e.g. using `Session.run()`) in order to get an integer.

Neither of these is quite the same as the NumPy property, so I don't see the advantages of having an identical interface here.

**Comment by shoyer** [comment]
This is fair enough. I didn't realize it was possible to have tensors with unknown rank.

**Comment by mrry** [comment]
It's possible but rare :) (at least in reasonable-quality code...). For example you can create one with `tf.placeholder(tf.float32)`, but you're encouraged to use `tf.placeholder(tf.float32, shape=[...])`. Unfortunately, we have some highly dynamic custom and legacy op code that requires this behavior....
