### ISSUE TITLE
inactive tensor board at safari

### ISSUE THREAD

**Issue by Ella77** [tensorflow/tensorflow#23969]
when I want to access my tensor board summary with commands ... 
and listening on localhost:6060
The same address would be inactive on safari , but ok on chrome browser.
I wonder if it's general problem... 
![2018-11-26 12 57 10](https://user-images.githubusercontent.com/42016485/48994110-c81b2780-f184-11e8-8801-702fd48fc351.png)

I uploaded screenshots ( the left one is chrome, and the active one is on safari

This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in 

TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).`
If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by nfelt** [comment]
Closing since TensorBoard issues should be filed at http://github.com/tensorflow/tensorboard/issues/new with the corresponding template details.

However, I'm not sure that the behavior you've described is a bug in TensorBoard - it sounds like this could also be an issue with your Safari configuration or local network.  Please confirm that you can reproduce the issue on more than once machine, with the latest version of TensorBoard, before re-filing the issue.
