### ISSUE TITLE
ERROR: undeclared inclusion(s) in rule '//tensorflow/python/eager:pywrap_tfe_lib'

### ISSUE THREAD

**Issue by panovr** [tensorflow/tensorflow#23972]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.12.0
- Python version: 3.7.0
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 0.18
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: 10.0
- GPU model and memory: GTX 1080 and 8GB

**Describe the problem**

ERROR: /home/ylzhao/project/tensorflow/tensorflow/python/eager/BUILD:10:1: undeclared inclusion(s) in rule '//tensorflow/python/eager:pywrap_tfe_lib':
this rule is missing dependency declarations for the following files included by 'tensorflow/python/eager/pywrap_tensor.cc':
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/ndarrayobject.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/ndarraytypes.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/numpyconfig.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/_numpyconfig.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_endian.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_cpu.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/utils.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/_neighborhood_iterator_imp.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/__multiarray_api.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_interrupt.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/ufuncobject.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_math.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/k8-opt/genfiles/external/local_config_python/python_include/numpy/__ufunc_api.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by harshini-gadige** [comment]
@panovr  Hi, please use the following combination to resolve this. 

Python - 3.6
Bazel - 0.15
CUDA/cuDNN - 9/7

**Comment by lorenzesz** [comment]
Is this still not fixed with 1.13?

**System information**

* OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
* Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
* TensorFlow installed from (source or binary): source
* TensorFlow version: 1.13.0rc2
* Python version: 3.7.2
* Installed using virtualenv? pip? conda?: pip
* Bazel version (if compiling from source): 0.22
* GCC/Compiler version (if compiling from source): 6.5.0
* CUDA/cuDNN version: 10.0
* GPU model and memory: RTX 2070 and 8GB

**Describe the problem**

ERROR: /home/max/tensorflow/tensorflow/python/eager/BUILD:10:1: undeclared inclusion(s) in rule '//tensorflow/python/eager:pywrap_tfe_lib':
this rule is missing dependency declarations for the following files included by 'tensorflow/python/eager/pywrap_tensor.cc':
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ndarrayobject.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ndarraytypes.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/numpyconfig.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/_numpyconfig.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_endian.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_cpu.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/utils.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/_neighborhood_iterator_imp.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/__multiarray_api.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_interrupt.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/ufuncobject.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_math.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/npy_common.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/arrayobject.h'
  'bazel-out/host/genfiles/external/local_config_python/python_include/numpy/__ufunc_api.h'
Target //tensorflow/tools/pip_package:build_pip_package failed to build

**Comment by abhajaswal** [comment]
Same issue in 1.13

**Comment by abhajaswal** [comment]
@lorenzesz  any solution found?

**Comment by racinmat** [comment]
any solutions? I tried to compile for python 3.6, and 3.7, but it did not work for neither of them.

**Comment by weinman** [comment]
Still the same problem for r1.14 (c407b045b8802f9eded430ef48be18cd85e4788c) with Python 3.6.8, (Ubuntu 18.04, CUDA 10.1)

**Comment by jannispriesnitz** [comment]
Same here

**Comment by weinman** [comment]
@jannispriesnitz I got this fixed by sorting out my numpy install (it's possible to have in three places: system-wide via apt, system-wide via pip, and in your user account). Try uninstalling from as many of these as possible and uninstall just the one you need (user is certainly easiest) to manipulate.

Once I was down to a single, consistent version of NumPy, I had no problem.

**Comment by t-kalinowski** [comment]
I also encountered this error after switching the python version I was building against without doing a `bazel clean` in between
