### ISSUE TITLE
Improve SEO score on index page

### ISSUE THREAD

**Issue by TashaPenwellHC** [tensorflow/tensorflow#23991]
I'd like to update the home page on suggestion SEO improvements.  I'm having difficulty finding the index file.  

The first issues I'd to correct is related to links not having a descriptive text.

**Comment by ymodak** [comment]
Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
