### ISSUE TITLE
how to take out the output of a layer

### ISSUE THREAD

**Issue by xun6000** [tensorflow/tensorflow#24035]
I am using the code from here:
https://www.tensorflow.org/tutorials/estimators/cnn
how to take out the output of pool2_flat?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
