### ISSUE TITLE
Secondary algorithm not provided error when not using cuDNN autotune

### ISSUE THREAD

**Issue by mavrov** [tensorflow/tensorflow#24044]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 1.12
- Python version: 3.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 9.0 / 7.1.4
- GPU model and memory: Nvidia Tesla K80, Quadro M1200

**Describe the current behavior**
I get the following error message when I set TF_CUDNN_USE_AUTOTUNE=0:
 2018-11-22 10:10:01.227780: E tensorflow/stream_executor/cuda/cuda_dnn.cc:82] The primary convolution algorithm failed memory allocation, while a secondary algorithm is not provided.

**Describe the expected behavior**
I would expect a secondary algorithm that does not require any workspace to kick in should the scratch allocation for the primary algorithm fail even when I am not using autotune.

**Other info / logs**
I traced back the error message to when it was [first introduced](https://github.com/tensorflow/tensorflow/blob/466eb299f0ce20cf929b9e06d3d3c16959360c59/tensorflow/stream_executor/cuda/cuda_dnn.cc#L706) in the code base to revise the logic.

It seems to me that years of refactoring have disabled the [fallback mechanism](https://github.com/tensorflow/tensorflow/blob/466eb299f0ce20cf929b9e06d3d3c16959360c59/tensorflow/stream_executor/cuda/cuda_dnn.cc#L792) when both the primary and secondary algorithms are the default ones.

**Comment by ymodak** [comment]
@zheng-xq  Can you please take a look? Thanks!

**Comment by ymodak** [comment]
@zheng-xq Gentle ping. Can you please take a look/point me at another resource? Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
