### ISSUE TITLE
ModelCheckpoint TypeError: get_config() missing 1 required positional argument: 'self'

### ISSUE THREAD

**Issue by wangnet** [tensorflow/tensorflow#24042]
[comment]
Epoch 00001: loss improved from inf to 103.67410, saving model to /tmp/weights.hdf5
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-12-a8915ea6c3f5> in <module>()
     27 
     28 #validation_data=(X_test,y_test),
---> 29 model.fit(X_train,y_train,epochs=2000,batch_size=128,callbacks=[checkpointer])
     30 
     31 return_eval = model.evaluate(X_test,y_test,batch_size=128)

- [error ] as  error show:

/usr/local/lib/python3.5/dist-packages/tensorflow/python/keras/utils/generic_utils.py in serialize_keras_object(instance)
    134     return {
    135         'class_name': instance.__class__.__name__,
--> 136         'config': instance.get_config()
    137     }
    138   if hasattr(instance, '__name__'):

TypeError: get_config() missing 1 required positional argument: 'self'

- [ code]  as I use code below:

checkpointer = ModelCheckpoint(filepath="/tmp/weights.hdf5", verbose=1, monitor='loss',save_best_only=True)

model.compile(#metrics=[mean_pred],
    loss=keras.losses.mean_squared_error,    
    optimizer=keras.optimizers.Adam(lr=0.001))

#validation_data=(X_test,y_test),
model.fit(X_train,y_train,epochs=2000,batch_size=128,callbacks=[checkpointer])

also with validation_data & val_loss has issue, plz help to check it. thanks~

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
