### ISSUE TITLE
Investigate precomputing reciprocals for division operations in XLA

### ISSUE THREAD

**Issue by sanjoy** [tensorflow/tensorflow#24061]
Today we optimize this elementwise division by a scalar:

```
HloModule DivReciprocal

ENTRY main {
  x = f32[2000,200]{1,0} parameter(0)
  y = f32[] parameter(1)
  y.broadcast = f32[2000,200]{1,0} broadcast(y), dimensions={}
  ROOT div = f32[2000,200]{1,0} divide(x, y.broadcast)
}
```

into the following:

```
HloModule DivReciprocal

fused_computation {
  param_0 = f32[2000,200]{1,0} parameter(0)
  param_1.1 = f32[] parameter(1)
  y.broadcast.1 = f32[2000,200]{1,0} broadcast(param_1.1), dimensions={}
  ROOT div.1 = f32[2000,200]{1,0} divide(param_0, y.broadcast.1)
}

ENTRY main {
  x = f32[2000,200]{1,0} parameter(0)
  y = f32[] parameter(1)
  ROOT fusion = f32[2000,200]{1,0} fusion(x, y), kind=kLoop, calls=fused_computation
}
```

`fusion` is ultimately lowered into the following PTX (via LLVM):

```
//
// Generated by LLVM NVPTX Back-End
//

.version 6.0
.target sm_60
.address_size 64

        // .globl       fusion

.visible .entry fusion(
        .param .u64 fusion_param_0,
        .param .u64 fusion_param_1,
        .param .u64 fusion_param_2
)
.reqntid 1024, 1, 1
{
        .reg .pred      %p<2>;
        .reg .f32       %f<11>;
        .reg .b32       %r<6>;
        .reg .b64       %rd<10>;

        mov.u32         %r2, %ctaid.x;
        mov.u32         %r3, %tid.x;
        shl.b32         %r4, %r2, 10;
        or.b32          %r5, %r4, %r3;
        setp.lt.u32     %p1, %r5, 100000;
        @%p1 bra        LBB0_2;
        bra.uni         LBB0_1;
LBB0_2:
        ld.param.u64    %rd4, [fusion_param_0];
        ld.param.u64    %rd5, [fusion_param_2];
        cvta.to.global.u64      %rd1, %rd5;
        ld.param.u64    %rd6, [fusion_param_1];
        cvta.to.global.u64      %rd2, %rd6;
        cvta.to.global.u64      %rd3, %rd4;
        shl.b32         %r1, %r5, 2;
        mul.wide.u32    %rd7, %r1, 4;
        add.s64         %rd8, %rd2, %rd7;
        ld.global.nc.v4.f32     {%f1, %f2, %f3, %f4}, [%rd8];
        ld.global.nc.f32        %f5, [%rd1];
        rcp.approx.f32  %f6, %f5;
        mul.f32         %f7, %f1, %f6;
        add.s64         %rd9, %rd3, %rd7;
        mul.f32         %f8, %f2, %f6;
        mul.f32         %f9, %f3, %f6;
        mul.f32         %f10, %f4, %f6;
        st.global.v4.f32        [%rd9], {%f7, %f8, %f9, %f10};
LBB0_1:
        ret;

}
```

It is conceivable that in some cases computing the reciprocal for `x` once, before we launch the kernel for `fusion`, can be profitable.  We should investigate if (and when) precomputing the reciprocal helps, and if it does, implement it as an optimization in XLA.

**Comment by jlebar** [comment]
Hi, as per the other bug report, would you be willing not to assign issues to me that I am not working on?

**Comment by xykong1958** [comment]
It should be always profitable to hoist the reciprocal showing in the example, the problem is if the 
floating point precision differences are acceptable. Many compilers do the transformation under options which allow such differences.

**Comment by jlebar** [comment]
> the problem is if the floating point precision differences are acceptable

Indeed.

We already pass `-nvptx-prec-divf32=0` to LLVM, which lets it use PTX `div.approx`.  This is a large win on some benchmarks.

But even this optimization is observable.  For example, if `x == y`, then `x/y == 1` should be true.  But it's not with div.approx.  You can make this error arbitrarily large by e.g. doing `floor(x/y)` -- now this is 1 or 0, depending on whether or not there was an error.

We don't have a good framework for making decisions about whether or not these kinds of optimizations are allowable in XLA.  What we want for an ML compiler is different from traditional compiler "fastmath" assumptions.  We usually want to preserve infs and nans, maybe even signed zeroes.  We also *in general* don't want to arbitrarily decrease precision by reassociation (although we do this in some places today).

Instead (I think) we want the freedom that comes from the assumption that the floating-point inputs to a program are effectively random numbers.  It should be OK for XLA to transform a program `f(x)` into a program `g(x) = f(x+epsilon)`, because that perturbation is "within the noise" anyway.  Under a model like that many approximations (not just approximate div, but say approximate tanh) may become acceptable.

I dunno if that's a sound model, but it's my working idea.

Anyway my hunch is that since we're already doing `div.approx`, precomputing reciprocals is probably ok.

**Comment by xykong1958** [comment]
I am not sure if the original issue is about transforming the original code into the following 
(compute the reciprocal of parameter(1), and passed as a parameter to the fusion, and inside the
fusion, the divide is replaced by multiply),

HloModule DivReciprocal

fused_computation {
  param_0 = f32[2000,200]{1,0} parameter(0)
  param_1.1 = f32[] parameter(1)
  y.broadcast.1 = f32[2000,200]{1,0} broadcast(param_1.1), dimensions={}
  ROOT div.1 = f32[2000,200]{1,0} multiply(param_0, y.broadcast.1)
}

ENTRY main {
  x = f32[2000,200]{1,0} parameter(0)
  y = f32[] divide(1.0f/parameter(1))        
  ROOT fusion = f32[2000,200]{1,0} fusion(x, y), kind=kLoop, calls=fused_computation
}

**Comment by jlebar** [comment]
> I am not sure if the original issue is about transforming the original code into the following

Yes, exactly like you have it.  This is useful on the assumption -- now questioned! -- that computing recip.approx is significantly less expensive than computing div.approx.

**Comment by YuanLinNV** [comment]
Regarding the single-precision floating point .approx PTX instructions (namely div.approx, rcp.approx, ex2.approx, lg2.approx, sqrt.approx, rsqrt.approx, sin.approx, and cos.approx),

1.           All of them are implemented with a few straight-line hardware instructions (some of which are predicated).
2.           The non-ftz versions have a few more instructions to handle denorms, thus are slower than the ftz versions.
3.           div.approx is implemented as rcp.approx and mul.

You can verify the above using the `nvdisasm` tool shipped with the CUDA toolkit.

The throughput of these instructions is lower than that of mul, but in the same magnitude as mul compared with memory access. They generally should be considered ‘cheap’ in the cost function for fusion decisions, even if they are used in a broadcast.

Since you’re consistently lowering single precision HLO division to PTX’s div.approx, we do not recommend pursuing the optimization suggested in this issue per the above analysis.
