### ISSUE TITLE
Possible typo in doc of constant_initializer

### ISSUE THREAD

**Issue by lifuhuang** [tensorflow/tensorflow#2410]
In the [doc](https://www.tensorflow.org/versions/master/api_docs/python/state_ops.html#constant_initializer) of `constant_initializer`, it says that the argument `value` should be:

> value: A Python scalar. All elements of the initialized variable will be set to this value.

But in fact, it can take array-like argument and initialize variables properly with it. So I guess it's a mistake in the doc? It's kind of misleading for beginners.

Thanks!

**Comment by mrry** [comment]
The documentation is intentionally vague on this point. Currently, you can pass any array-like argument that is supported by `tf.constant()`, but this is an implementation detail, and it is unreliable since `constant_initializer()` can be used to create variables of different shapes. Only a scalar argument has a well-defined meaning (fill a tensor of the given shape with that scalar value) for all possible shapes.

**Comment by lifuhuang** [comment]
Got it, thanks.

Best Regards,
Lifu Huang

2016-05-18 14:37 GMT+08:00 Derek Murray <notifications@github.com>:
