### ISSUE TITLE
optimizing for mac users to use AVX2 FMA

### ISSUE THREAD

**Issue by foobar8675** [tensorflow/tensorflow#24134]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac 10.13.6
- TensorFlow installed from (source or binary): 1.12.0 binary

**Describe the problem**

according to the docs, `Note: We already provide well-tested, pre-built TensorFlow packages for Linux and macOS systems.` , however, when running that version, I still see `our CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA`

I wanted to know if there were plans to optimize the mac build to take full advantage of the CPU?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl`

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by pldelisle** [comment]
Hi,

You have to compile it with source in order to specify the compile flags you want. 

I normally compile it with the following flags (on a GPU-enabled Linux workstation): 

`bazel build -c opt --copt=-march=native --copt=-mfpmath=both --config=cuda --config=mkl -k //tensorflow/tools/pip_package:build_pip_package`

And I use the Intel Software distribution for Python with Anaconda (https://software.intel.com/en-us/articles/using-intel-distribution-for-python-with-anaconda)

Or you can use this link and download the binary If it matches your software configuration (you should upgrade to macOS Mojave) : https://github.com/lakshayg/tensorflow-build

**Comment by foobar8675** [comment]
thanks @pldelisle . I tried all the mojave versions in the tensorflow-build  [https://github.com/lakshayg/tensorflow-build]() but always got the error `tensorflow-1.12.0-cp37-cp37m-macosx_10_13_x86_64.whl is not a supported wheel on this platform.` with the respective whl file. I also tried compiling from source, but aborted after googling and trying and not succeeded. 

Thanks for replying. I think I'll stick with the whl file provided by google.

**Comment by pldelisle** [comment]
Make sure you have Python 3.7 installed on macOS. But I recommend you to compile it from source.

**Comment by foobar8675** [comment]
got it working. thank you! (performance is faster but still slow, I'm considering getting an egpu nvidia card for mac)

**Comment by pldelisle** [comment]
Useless. Tensorflow does not support GPU usage on macOS due to limited configuration access to nvidia GPUs. I think that compiling Tensorflow 1.12 with GPUs on macOS is not possible without modifications to code. Nvidia driver is also a pain on macOS, accusing a delay in versions of macOs supported (currently not supporting 10.14). Plus, Apple has not came out with a computer on Nvidia since 2013 and will probably never do it again. Moreover, eGPU on macOS is only supported with AMD GPUs, so basically not compatible with TensorFlow (there are kernel ports to openCL but implementation is still incomplete). 
I personally have my own Red hat server in which I have my GPUs (2x RTX 2080) to which I connected my Pycharm environment with remote Python interpreter. This is the best setup when you have a mac. You can still compile your graph on macOS to see if it works on CPU and then run it on a server with GPUs.

**Comment by foobar8675** [comment]
you potentially saved me a ton of time. Thank you.

**Comment by andreaghezzi** [comment]
Hi everyone!!
I followed the guide on the tensorflow site for installing from source. <br>
I have performed almost all the steps and they have been successful, I miss the last one or the installation of the package, using the following instruction:
`pip install /tmp/tensorflow_pkg/tensorflow-2.8.0-cp39-cp39-macosx_11_0_x86_64.whl` but it returns the following error
**`ERROR: tensorflow-2.8.0-cp39-cp39-macosx_11_0_x86_64.whl is not a supported wheel on this platform.`**  <br>
My version of Python is 3.9.9. Do you know how I can solve?
