### ISSUE TITLE
TextLineDataset supporting start/end file positions

### ISSUE THREAD

**Issue by chenjiasheng** [tensorflow/tensorflow#24198]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.11.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
When constructing a text dataset pipeline, we often want to extract text lines from part of a large text file, instead of from the whole file. For example, 

- using 99% lines at the head of a large file as train set and the remaining 1% as valid set.

- when training a model in parallel on multiple GPUs or nodes, we want to split large text files into equal-lengthed parts for each GPU to train one part of them.

Traditionally, to achieve this goal we have to do file operations such as splitting, copying and renaming. These operations are tedious, error-pruning and cost more disk space and time. It also messes up directory/file structures. More over, it is hard to share between different environments with different count of GPUs/nodes, or with different text file set.
Here I have created a `TextLineBlockDataset` op kernel as well as a python `dataset_ops.Dataset` by mimicking `TextLineDataset`. `TextLineBlockDataset` uses a [begin_offset, end_offset) range to mark a block of a text file, freeing one from tedious file splitting preparations.

This is the registration of the dataset op:
```
REGISTER_OP("TextLineBlockDataset")
    .Input("filenames: string")
    .Input("begin_offsets: int64")
    .Input("end_offsets: int64")
    .Input("buffer_size: int64")
    .Output("handle: variant")
    .SetIsStateful()  // TODO(b/65524810): Source dataset ops must be marked
        // stateful to inhibit constant folding.
    .SetShapeFn([](shape_inference::InferenceContext* c) {
      shape_inference::ShapeHandle unused;
      TF_RETURN_IF_ERROR(c->WithRankAtMost(c->input(0), 1, &unused));
      TF_RETURN_IF_ERROR(c->WithRankAtMost(c->input(1), 1, &unused));
      TF_RETURN_IF_ERROR(c->WithRankAtMost(c->input(2), 1, &unused));
      TF_RETURN_IF_ERROR(c->WithRank(c->input(3), 0, &unused));
      return shape_inference::ScalarShape(c);
    });
```
and the python API interface to it:
```
@tf_export("data.TextLineBlockDataset")
class TextLineBlockDataset(dataset_ops.Dataset):
    """A `Dataset` comprising lines from one or more text file blocks."""

    def __init__(self, filenames, begin_offsets, end_offsets, buffer_size=None):
        """Creates a `TextLineBlockDataset`.
        An element in zip(filenames, begin_offsets, end_offsets) denotes a text
        file block in file filename, beginning at begin_offset and ends at
        end_offset, in byte.
        `begin_offsets` and `end_offsets` will be smoothed to match text line
        boundaries under the hood.

        Args:
          filenames: A `tf.string` tensor containing one or more filenames.
          begin_offsets: A `tf.int64` 1-d tensor denoting begin offsets.
          end_offsets: A `tf.int64` 1-d tensor denoting end offsets.
          buffer_size: (Optional.) A `tf.int64` scalar denoting the number of bytes
            to buffer for each block, for each block. A value of 0 results in the 
            default values chosen on the compression type.
        """
```

This is how I use it:
Suppose I have 3 large text files, I want to extract text lines ranging from ratio 2/4 to 3/4 of each text file. Each text file block will be split into 8 smaller blocks for better shuffle effect.
```
if __name__ == '__main__':
    filenames = ["data/train.txt", "data/dev.txt", "data/test.txt"]
    n_files = len(filenames)
    # this is the 2nd of the 4 towers which consumes range 2/4 ~ 3/4 text lines of each file
    n_towers, tower_id = 4, 2
    n_splits = 8    # each range will be further split into 8 parts for better shuffle
    buffer_size = 256 * 1024

    block_params = []
    for file_id in range(n_files):
        file_size = os.path.getsize(filenames[file_id])
        split_size = file_size / (n_towers * n_splits)
        for split_id in range(n_splits):
            begin_offset = int(split_size * (tower_id * n_splits + split_id))
            end_offset = int(split_size * (tower_id * n_splits + split_id + 1))
            block_params.append((filenames[file_id], begin_offset, end_offset))
    dataset = TextLineBlockDataset(*zip(*block_params), buffer_size)
    dataset = dataset.shuffle(32000)  # shuffle in the same manner as `TextLineDataset`
    get_next = dataset.make_one_shot_iterator().get_next()

    sess = tf.Session()
    while True:
        try:
            print(sess.run(get_next).decode("utf-8"))
        except tf.errors.OutOfRangeError:
            break
```

**Will this change the current api? How?**
Yes.
A new dataset op kernal will be registered in the C++ side, and a corresponding python 
class tf.data.TextLineBlockDataset will be added.

**Who will benefit with this feature?**
Tensorflow users who deal with large text files.

**Any Other info.**
@mrry @eaplatanios @rachellim

**Comment by chenjiasheng** [comment]
@mrry @aselle
If you think this is worthy I will fire a PR and do performance tests on really large files, and also some visualization test to show line number generated at each step when batching or shuffling is using.
I can add a param so the user can decide whether to do interleaving or concatenating on the input file blocks. And I strongly suggest that `TextLineDataset` also supporting interleaving.

**Comment by aselle** [comment]
@martinwicke, Do you know who might have insight into this. I don't handle the data pipeline that much. Certainly @mrry would possibly know as well.

**Comment by jsimsa** [comment]
@chenjiasheng Can you clarify whether a) you are asking us to implement this API or b) you have an implementation of this API and you are looking for feedback on it.

If it is a), the request should clarify what should happen when the underlying file is compressed (`TextLineDataset` supports GZIP and ZLIB compression). Or are compressed files not supported by `TextLineBlockDataset`?

On a related note, how large are the text files in question? Instead of splitting the input file manually, you could make use of `tf.data.Dataset.shard()` or `tf.data.Dataset.filter()` in your input pipeline to "partition" the input across different GPUs. I say "partition" because a solution based on `shard()` and `filter()` read all the bytes and then discard the bytes that do not belong into this partition. If the time needed to read the all bytes is negligible compared to the time needed spend on training, then I recommend using existing transformations, instead of proposing a custom one.

If it is b), then I would be open to accepting this as a contribution to `tf.data.experimental` and reviewing the PR, provided the solution supports compressed files.

**Comment by chenjiasheng** [comment]
@jsimsa 

> Can you clarify whether a) you are asking us to implement this API or b) you have an implementation of this API and you are looking for feedback on it.

Yes, I do have an implementation and I'd like to contribute it to `tf.data.experimental`. I wrote it by mimicking `TextLineDataset`. Compression supports were removed just for personal simplicity, and of cause it can be added back.

> On a related note, how large are the text files in question?

700M ~ 40G, each file has a different source, including wikipedia, weibo/douban (something similar to twitter), news, film subtitle, etc.


> ... If the time needed to read the all bytes is negligible compared to the time needed spend on training, then I recommend using existing transformations, instead of proposing a custom one.

Yes, it is negligible compared to training. But it is not negligible when you are anxiously waiting for the training process start up normally . 
The large memory consumed is not acceptable as well. 
More over,  as I know `tf.data.Dataset.shard` generate lines in a concatenate order instead of interleaving, as a result almost all Wikipedia corpus lines come out before all the subtitle lines.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
