### ISSUE TITLE
Hard arbitrary limit on Saved model size

### ISSUE THREAD

**Issue by blair0011** [tensorflow/tensorflow#24205]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Both
- TensorFlow version (use command below): 1.10+
- Python version: N/A
- Bazel version (if compiling from source): 17.2
- GCC/Compiler version (if compiling from source): 7.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I am trying to load a 1.4GiB binary saved model and am getting an error saying that the protobuf message is too big i.e. over 1GiB

**Describe the expected behavior**
Current default limits for protobuf messages loaded by a CodedInputStream are 2GiB so my model should load without error.

**Code to reproduce the issue**

Comment out line 503 in env.cc:
//coded_stream.SetTotalBytesLimit(1024LL << 20, 512LL << 20);
rebuild and everything works as expected. 

**Other info / logs**

Also the second parameter to SetTotalBytesLimit has been deprecated and is no longer enforced.

**Comment by tilakrayal** [comment]
@blair0011 ,

Protobuf has a hard limit of 2GB, because many implementations use 32-bit signed arithmetic. For security reasons, many implementations impose a size limit of 64MB by default, although you can increase this limit manually.

Also could you take a look at this SO [link](https://stackoverflow.com/questions/13849434/how-to-change-the-buffer-limit-in-googles-protobuf) which delivers the required information. Thank you!
