### ISSUE TITLE
3D * 2D matrix multiplication without changing batch dimension

### ISSUE THREAD

**Issue by paduck86** [tensorflow/tensorflow#24252]
I'm trying to implement tensordot in other ways because of some tensorrt issues.

In tf.tensordot op, there is a batch-size modification in the process of 3d * 2d matmul.

```
M = tf.random_normal((batch_size, n, m))  # (3,6,9)
N = tf.random_normal((m, p)) # (9,9)

MT = tf.reshape(M, [batch_size*n, m]) # (18,9)
MTN = tf.matmul(M_T, N) # (18,9)

MN = tf.reshape(MTN, [batch_size, n, p]) # (3,6,9)
```

But I want 3d*2d matmul without changing batch-size dimension.
Is there a way?

**Comment by pooyadavoodi** [comment]
It's not clear to me what you are trying to achieve (I guess depends on `axis` used in your tensordot op). But you may need to replicate `N` along the batch dimension (e.g. using `tf.tile`) first.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by Rogersjk** [comment]
There is not direct function, but it can be implemented in a simple way as follows:
```
    MN = tf.matmul(M, tf.tile(N[None], [batch_size, 1, 1]))
```
