### ISSUE TITLE
Install Go TensorFlow error

### ISSUE THREAD

**Issue by Xib1uvXi** [tensorflow/tensorflow#24281]
**System information**
- OS Platform and Distribution (Linux Ubuntu 18.10 x64)
- Go Version: go version go1.11.2 linux/amd64

I refer to this [guide](https://www.tensorflow.org/install/lang_go) to install Go TensorFlow, I have encountered some problems

**Describe the problem**

install TensorFlow-C

run shell in command line:

```shell

 TF_TYPE="cpu" # Change to "gpu" for GPU support
 TARGET_DIRECTORY='/usr/local'
 curl -L \
   "https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-$(go env GOOS)-x86_64-1.8.0.tar.gz" |
 sudo tar -C $TARGET_DIRECTORY -xz

```

```shell
cd /usr/local/lib

ls |grep *tensorflow*
 
libtensorflow.so
```

```shell

sudo ldconfig

```

```shell

go get github.com/tensorflow/tensorflow/tensorflow/go

```

error info

```text
# github.com/tensorflow/tensorflow/tensorflow/go
/usr/bin/ld: $WORK/b001/_x003.o: in function `_cgo_8f42b3a84d7b_Cfunc_TF_AddGradientsWithPrefix':
/tmp/go-build/cgo-gcc-prolog:63: undefined reference to `TF_AddGradientsWithPrefix'
collect2: error: ld returned 1 exit status
```

how can i fix this problem

**Comment by Xib1uvXi** [comment]
i also try ```go get -d github.com/tensorflow/tensorflow/tensorflow/go```, but run ```go test github.com/tensorflow/tensorflow/tensorflow/go```  has the same error

error info

``` text
# github.com/tensorflow/tensorflow/tensorflow/go
/usr/bin/ld: $WORK/b048/_x003.o: in function `_cgo_8f42b3a84d7b_Cfunc_TF_AddGradientsWithPrefix':
/tmp/go-build/cgo-gcc-prolog:63: undefined reference to `TF_AddGradientsWithPrefix'
collect2: error: ld returned 1 exit status
FAIL	github.com/tensorflow/tensorflow/tensorflow/go [build failed]
```

**Comment by asimshankar** [comment]
@Xib1uvXi : It seems you're installing an old version of the TensorFlow C library, too old for the Go code in the `master` branch. Perhaps you're somehow seeing a very old version of the website?

To move forward, I see two options:

1. Use a newer version of the C library (as listed in the [installation page](https://www.tensorflow.org/install/lang_c)). Which should basically mean downloading `   https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-$(go env GOOS)-x86_64-1.12.0.tar.gz` instead of `   https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-${TF_TYPE}-$(go env GOOS)-x86_64-1.8.0.tar.gz` (notice the `1.12.0` instead of the `1.8.0` in the URL),

OR

2. Use an older snapshot of the Go code (compatible with the C library you have):

```sh
go get -d github.com/tensorflow/tensorflow/tensorflow/go
cd github.com/tensorflow/tensorflow/tensorflow/g
git checkout r1.8
```

Hope that helps.
I'm going to close this issue since the issue here seems to be because of following a stale version of the website. Feel free to re-open if I've misunderstood or if the problem persists. Thanks.
