### ISSUE TITLE
 Malformed TF_STRING tensor; too short to hold number of elements

### ISSUE THREAD

**Issue by zionwu** [tensorflow/tensorflow#24331]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  CentOS 7.3
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): Java API 1.12
- Python version: 
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
I am using Java API for prediction and 
I tried to create a tensor of String type using the following Java API:
```java
                    String[] strs = {"element1", "thisissecondelement"};  
                    ByteArrayOutputStream outputStream = new ByteArrayOutputStream( );   
                    for (String s : strs) {  
                        outputStream.write(s.getBytes());  
                    }  
                    long [] shape = new long[1];
                    shape[0] = strs.length;
                    Tensor<String> t = Tensor.create(String.class, shape,  ByteBuffer.wrap(outputStream.toByteArray());
```

However, when calling "runner.fetch("predict/Sigmoid:0").run().get(0)" I got the following excetion:
```
Exception in thread "main" java.lang.IllegalArgumentException: Malformed TF_STRING tensor; too short to hold number of elements.
```

I looked into the code:
![g1m018793wkgcqlwrvg-abv9paaa0cknmbeo475](https://user-images.githubusercontent.com/1213386/49913535-d5e0e480-fec8-11e8-8d94-4260800120a6.PNG)

It uses sizeof(tensorflow::uint64) as the size of the element in the byte array. However, the  size of the string element is not fixed. 

**Describe the expected behavior**
The API  `runner.fetch("predict/Sigmoid:0").run().get(0)`  should run without error.

**Code to reproduce the issue**
Create a String Tensor using `public static <T> Tensor<T> create(Class<T> type, long[] shape, ByteBuffer data) ` in org.tensorflow.Tensor.

**Comment by alextp** [comment]
@asimshankar this seems related to the C API code you wrote. Do you know who should handle this?

**Comment by asimshankar** [comment]
I think the following will get what you want:

```java
String[] strs = {"element1", "thisissecondelement"};
byte[][] data = new byte[strs.length][];
for (int i = 0; i < data.length; ++i) {
  data[i] = strs[i].getBytes();
}
Tensor<String> t = Tensors.create(data);
// Alternatively: Tensor<String> t = Tensor.create(data, String.class);
```

Some explanation:

- The sample code provided was using [`Tensor.create(Class<T> type, long[] shape, ByteBuffer data)`](http://static.javadoc.io/org.tensorflow/libtensorflow/1.12.0/org/tensorflow/Tensor.html#create-java.lang.Class-long:A-java.nio.ByteBuffer-) which (though easy to miss) requires that the `ByteBuffer` contain the bytes encoded as required by the TensorFlow C API. (The Javadoc links to the [format described in `c_api.h`](https://github.com/tensorflow/tensorflow/blob/98c0deb828c2f98f0d6d77a12d32f3b33ed92887/tensorflow/c/c_api.h#L206)). So, the string tensors needed to be encoded with `uint64` offset information in addition to the raw bytes, which is why you were getting the error.

- The snippet I provided above would probably be what you want instead - using [`Tensors.create(byte[][][])`](http://static.javadoc.io/org.tensorflow/libtensorflow/1.12.0/org/tensorflow/Tensors.html#create-byte:A:A-) which is a convenience wrapper over [`Tensor.create(Object, Class<T>)`](http://static.javadoc.io/org.tensorflow/libtensorflow/1.12.0/org/tensorflow/Tensor.html#create-java.lang.Object-java.lang.Class-), whose documentation provides some more examples.

I'm tempted to close this since this doesn't appear to be a bug, just a slight misunderstanding in how to use the API. If I'm mistaken, or if you have suggestions on what would have helped (or how the documentation could be improved) so that you didn't run into this - feel free to re-open.
