### ISSUE TITLE
Loaded cudnn library: 4007 but source was compiled against 4004

### ISSUE THREAD

**Issue by zzqiang04053080** [tensorflow/tensorflow#2437]
when I install the tensorflow from souces in my ubuntu14.04 system, a cudnn version does not match  problem happened.
Omit some fine steps, the following is my installation steps:

### 1.Configure the cuda installation,  CUDA 7.5 and cudnn v4.0.7  have been chosen:

root@node4:/home/zhouzhiqiang/tensor_5_9/tensorflow# ./configure 
Please specify the location of python. [Default is /usr/bin/python]: 
Do you wish to build TensorFlow with GPU support? [y/N] y
GPU support will be enabled for TensorFlow
Please specify which gcc nvcc should use as the host compiler. [Default is /usr/bin/gcc]: 
Please specify the Cuda SDK version you want to use, e.g. 7.0. [Leave empty to use system default]: 7.5
Please specify the location where CUDA 7.5 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify the Cudnn version you want to use. [Leave empty to use system default]: 4.0.7
Please specify the location where cuDNN 4.0.7 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 
Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size.
[Default is: "3.5,5.2"]: 
Setting up Cuda include
Setting up Cuda lib64
Setting up Cuda bin
Setting up Cuda nvvm
Setting up CUPTI include
Setting up CUPTI lib64
Configuration finished

### 2. Create the pip package and install

bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package

bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

sudo pip install /tmp/tensorflow_pkg/tensorflow-0.8.0-py2-none-any.whl

### After the installation, The following example was carried out:

python tensor_5_9/tensorflow/tensorflow/models/image/alexnet/alexnet_benchmark.py

### Log for printing:
E tensorflow/stream_executor/cuda/cuda_dnn.cc:286] Loaded cudnn library: 4007 but source was compiled against 4004.  If using a binary install, upgrade your cudnn library to match.  If building from sources, make sure the library loaded matches the version you specified during compile configuration.
W tensorflow/stream_executor/stream.cc:301] attempting to perform DNN operation using StreamExecutor without DNN support
Traceback (most recent call last):
  File "tensor_5_9/tensorflow/tensorflow/models/image/alexnet/alexnet_benchmark.py", line 236, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "tensor_5_9/tensorflow/tensorflow/models/image/alexnet/alexnet_benchmark.py", line 232, in main
    run_benchmark()
  File "tensor_5_9/tensorflow/tensorflow/models/image/alexnet/alexnet_benchmark.py", line 221, in run_benchmark
    time_tensorflow_run(sess, pool5, "Forward")
  File "tensor_5_9/tensorflow/tensorflow/models/image/alexnet/alexnet_benchmark.py", line 177, in time_tensorflow_run
    _ = session.run(target)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 332, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 572, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 652, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 672, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InternalError: cuDNN launch failure : input shape([128,3,225,225]) filter shape([11,11,3,64])
         [[Node: conv1/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 4, 4, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Variable/read, conv1/weights/read)]]

**Comment by zzqiang04053080** [comment]
No one has ever met??

**Comment by zheng-xq** [comment]
If you grep for "CUDNN_PATCHLEVEL" in your "/usr/local/cuda/include/cudnn.h", what does it say?

**Comment by zzqiang04053080** [comment]
@zheng-xq 

### CUDNN_PATCHLEVEL in cudnn.h described as follows:


#if !defined(CUDNN_H_)
#define CUDNN_H_

#define CUDNN_MAJOR      4
#define CUDNN_MINOR      0
#define CUDNN_PATCHLEVEL 7

#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

**Comment by zzqiang04053080** [comment]
@zheng-xq 
when I run the following example:
bazel build -c opt  --config=cuda  //tensorflow/cc:tutorials_example_trainer
bazel-bin/tensorflow/cc/tutorials_example_trainer --use_gpu

it can be executed correctly, print as shown below:

I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so.4.0.7 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so.7.5 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so.7.5 locally
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with properties:

**Comment by zheng-xq** [comment]
If you grep third_party/gpus/cuda/include/cudnn.h, do you see the same thing? You could also try to set LD_LIBRARY_PATH to point to the right library.

**Comment by zheng-xq** [comment]
Another possibility is that you are using an older TensorFlow binary. Please check around and make sure you didn't have those. Also look under /tmp/tensorflow_pkg as well.

**Comment by zzqiang04053080** [comment]
@zheng-xq 

yeah, seems I don't  have the right to replace the install file,  it is ok after recompiled. thank you !

**Comment by jojotata** [comment]
Hi. I have a similar issue when I run MNIST on TensorFlow.
There may be some problem in cudnn.
How did you fix the problem?

`E tensorflow/stream_executor/cuda/cuda_driver.cc:932] failed to allocate 163.74M (171696128 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY
E tensorflow/stream_executor/cuda/cuda_dnn.cc:289] could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
E tensorflow/stream_executor/cuda/cuda_dnn.cc:278] could not destroy cudnn handle: CUDNN_STATUS_BAD_PARAM
W tensorflow/stream_executor/stream.cc:301] attempting to perform DNN operation using StreamExecutor without DNN support
Traceback (most recent call last):
  File "mainE.py", line 125, in <module>
    x:batch[0], y_:batch[1], keep_prob:1.0})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 502, in eval
    return _eval_using_default_session(self, feed_dict, self.graph, session)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3334, in _eval_using_default_session
    return session.run(tensors, feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 340, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 564, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 637, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InternalError: cuDNN launch failure : input shape([50,1,28,28]) filter shape([5,5,1,32])
	 [[Node: Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/gpu:0"](Reshape, Variable/read)]]
	 [[Node: Mean_1/_9 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_704_Mean_1", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]
Caused by op u'Conv2D', defined at:
  File "mainE.py", line 57, in <module>
    h_conv1 = tf.nn.relu(conv2d(x_image, W_conv1) + b_conv1)
  File "mainE.py", line 43, in conv2d
    return tf.nn.conv2d(x, W, strides=[1, 1, 1, 1], padding='SAME')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_nn_ops.py", line 295, in conv2d
    data_format=data_format, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1154, in __init__
    self._traceback = _extract_stack()
`

**Comment by oakkas** [comment]
I am having same issue: I am having same issue and tried everything.
E tensorflow/stream_executor/cuda/cuda_dnn.cc:347] Loaded runtime CuDNN library: 5004 (compatibility version 5000) but source was compiled with 5103 (compatibility version 5100).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
F tensorflow/core/kernels/conv_ops.cc:457] Check failed: stream->parent()->GetConvolveAlgorithms(&algorithms) 
Aborted (core dumped)

I tried uninstall and install several times with cuda 7.5 and 8. I tried cudann 4, 5, 5.1. NOthing worked. 
What else I can do?

**Comment by zheng-xq** [comment]
@oakkas, the issue was that your code was compiled with Cudnn 5.1, but the loaded Cudnn library was 5.0. They might not be completely binary compatible. That is why stream-executor complains. 

Do you have multiple Cudnn library installed on your machine? Please make sure the one you pointed out to with "configure" is the one that is actually loaded. You can set LD_LIBRARY_PATH to manually make sure.
