### ISSUE TITLE
initial_sparsity should be float but instead its integer in hparams

### ISSUE THREAD

**Issue by dorlivne** [tensorflow/tensorflow#24535]
Hi,
im trying to determine an initial sparsity level so i can continue pruning a model of which i already pruned and has a known initial sparsity level,
but it seems i cannot use the initial sparsity level because it is determine as an integer in  Hparams.
i dont want to build a new directory and i would like to use the get_hparams function you kindly provided.
if this issue could be resolved it will be great!
thank you.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
