### ISSUE TITLE
Suggestion: adding Tags or descriptions to the run log

### ISSUE THREAD

**Issue by akors** [tensorflow/tensorflow#2454]
Hi!

So far, I I have to say that TensorBoard is a really great tool to analyze the training procedure.
However, I often find myself comparing various runs and wondering "wait, which version of my code was that and which parameters did I use?".
Currently, the only way to "document" a Run is the name of the log directory - so I find myself encoding all kinds of cryptic acronyms into the directory name.

What would be really awesome is some sort of feature that allows the training scripts to pass Data to the TensorBoard logs. This could be in any form, maybe as sort of "tags" or as key-value pairs, or simply as a plain old string called "description" or something.

Is this something that sounds useful to others as well? Is this feasible?

**Comment by girving** [comment]
@danmane: Can you comment on this?  It seems like a reasonable thing to mark "contributions welcome", but we should get your input first on how best to express it if so.

**Comment by danmane** [comment]
This is on my roadmap, actually. I want to make a new field in the event.proto that will let you record arbitrary info about the run, including key value pairs like "code version", "vx.x.x", hyperparameters, etc.
I'd like to get this in in-time for the next release, no promises.

It's probably not a great candidate for contributions welcome because I already have a plan to do it, and it requires some API changes.

**Comment by akors** [comment]
@danmane Thanks, that's great to hear.

By the way, #2510 seems like a duplicate of this one.

**Comment by danmane** [comment]
Hyperparameter & run description for tensorboard is now under active development.
I'm closing this issue to make for easier issue tracking.

**Comment by akors** [comment]
Hi, this is great news! Is there a tracking bug or anything to get notified, when you have implemented this feature?
