### ISSUE TITLE
How to create an tensor as vector C++ ?

### ISSUE THREAD

**Issue by ricardobnjunior** [tensorflow/tensorflow#24604]
Hey, there.

I am trying to create an tensor as vector with 16 positions. However i cannot. Can you help me please?
My code:

```
Tensor targetsValues(DT_FLOAT, TensorShape({16}));
targetsValues.scalar<float>()() = { 62, 62, 62, 62, 43, 55,  3, 78, 27, 78,  4, 78,  9, 78, 13, 78 };
```

The error:

![image](https://user-images.githubusercontent.com/18532570/50494950-08302d00-0a05-11e9-8eb3-1170f1c0c720.png)

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
