### ISSUE TITLE
Using `tf.nn.rnn_cell.LSTMCell` with `tf.nn.rnn` breaks when `state_is_tuple` is True

### ISSUE THREAD

**Issue by mouradmourafiq** [tensorflow/tensorflow#2463]
### Environment info
Operating System: mac

If installed from sources, provide the commit hash: 7d9ab3eb485e6eb1778bad4ef01a1cd95b2d22d9

### Steps to reproduce
Creating an rnn based on a list of cell specified by `MultiRNNCell` breaks at the `zero_state` function:

```python
num_units = 3
input_size = 5
num_proj = 4
max_length = 8
sequence_length = [4, 6]
initializer = tf.random_uniform_initializer(-0.01, 0.01)
inputs = max_length * [tf.placeholder(tf.float32, shape=(None, input_size))]
inputs_c = tf.pack(inputs)
cell = tf.nn.rnn_cell.LSTMCell(num_units, input_size, use_peepholes=True,
                               num_proj=num_proj, initializer=initializer, 
                               state_is_tuple=True)
cells = tf.nn.rnn_cell.MultiRNNCell([cell] * 2, state_is_tuple=True)
outputs_static, state_static = tf.nn.rnn(cells, inputs, dtype=tf.float32, 
                                         sequence_length=sequence_length)
```

The same model definition would work if `state_is_tuple=False`, the code break at this [line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/rnn_cell.py#L107)

The same code would work if we pass the cell directly to `tf.nn.rnn` i.e. without using `tf.nn.rnn_cell.MultiRNNCell`, the reason is that `tf.nn.rnn_cell.MultiRNNCell` would have a `state_size` value as tuple of tuples, in my example the value of the `state_size` is `<type 'tuple'>: ((3, 4), (3, 4))`

### What have you tried?
.1. Tried the same model definition without `state_is_tuple=False`, which works but shows a deprication warning.

```python
num_units = 3
input_size = 5
num_proj = 4
max_length = 8
sequence_length = [4, 6]
initializer = tf.random_uniform_initializer(-0.01, 0.01)
inputs = max_length * [tf.placeholder(tf.float32, shape=(None, input_size))]
inputs_c = tf.pack(inputs)
cell = tf.nn.rnn_cell.LSTMCell(num_units, input_size, use_peepholes=True,
                               num_proj=num_proj, initializer=initializer)
cells = tf.nn.rnn_cell.MultiRNNCell([cell])
outputs_static, state_static = tf.nn.rnn(cells, inputs, dtype=tf.float32, 
                                         sequence_length=sequence_length)
```

.2. Tried the same model definition with `state_is_tuple=True` and without `tf.nn.rnn_cell.MultiRNNCell`, which works.

```python
num_units = 3
input_size = 5
num_proj = 4
max_length = 8
sequence_length = [4, 6]
initializer = tf.random_uniform_initializer(-0.01, 0.01)
inputs = max_length * [tf.placeholder(tf.float32, shape=(None, input_size))]
inputs_c = tf.pack(inputs)
cell = tf.nn.rnn_cell.LSTMCell(num_units, input_size, use_peepholes=True,
                               num_proj=num_proj, initializer=initializer, 
                               state_is_tuple=True)
outputs_static, state_static = tf.nn.rnn(cell, inputs, dtype=tf.float32, 
                                         sequence_length=sequence_length)
```
### Logs or other output that would be helpful
```
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/ops/rnn.py", line 123, in rnn
    state = cell.zero_state(batch_size, dtype)
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.py", line 109, in zero_state
    for s in state_size)
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/ops/rnn_cell.py", line 109, in <genexpr>
    for s in state_size)
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 249, in pack
    return gen_array_ops._pack(values, name=name)
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1126, in _pack
    result = _op_def_lib.apply_op("Pack", values=values, name=name)
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2242, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1696, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 439, in _PackShape
    input_shape = input_shape.merge_with(inp.get_shape())
  File "/Users/mourad/.virtualenvs/ca/lib/python2.7/site-packages/tensorflow/python/framework/tensor_shape.py", line 554, in merge_with
    (self, other))
ValueError: Shapes () and (2,) are not compatible
```

**Comment by jihunchoi** [comment]
I am experiencing the same issue.
As far as I explored, it occurs because of the current implementation of `zero_state`.
When `state_is_tuple` flag is set to false, the cell state and the hidden state of a recurrent layer is concatenated, and the shape is `(2 * num_layers,)`.
However, when the flag is on, the cell state and the hidden state is passed separately, and the shape is `(num_layers, num_layers)` (one for the cell state, another for the hidden state).

1. Without `MultiRNNCell`
In this case, `state_size` would be `(num_layers, num_layers)`.
So line 107-109 of the current implementation would make a length-2 tuple of `(batch_size, num_layers)`-shape zero tensors.
2. With `MultiRNNCell`
In this case, `staet_size` would be `((num_layers, num_layers), ..., (num_layers, num_layers))` (whose length is `num_layers`).
So, line 107-109 of the current implementation causes error, because `s` in line 109 is a tuple `(num_layers, num_layers)`, where a single number is expected.

If you configure that setting the flag of a single `LSTMCell` to `False` and that of a `MultiRNNCell` to `True`, it would work well, although warnings would occur. (`num_layer + 1` warnings if you set both flags to `False`, and (`num_layer` warnings if you turn on only `MultiRNNCell`'s flag.)

I think it can be fixed by fixing as follows: if the type of `state_size` is tuple of tuple, initialize for all single numbers in the tuple of tuple and return with the same form.

**Comment by jihunchoi** [comment]
After a bit more exploration, I found that it works in case that both flags are on, if I apply `zero_state` for each layer manually and then make a tuple of the results.
However, I think `zero_state` should be modified, since it is specified in the abstract class `RNNCell` and `MultipleRNNCell` is a subclass of that abstract class.
I made a PR modifying this issue. Since I started studying TensorFlow yesterday, my codes might be awkward!

**Comment by ebrevdo** [comment]
This has been fixed internally and the next public push should have the fix.

**Comment by girving** [comment]
@ebrevdo: Is this fixed?

**Comment by ebrevdo** [comment]
Seems this is fixed.  @jihunchoi feel free to reopen if you're still having issues.

**Comment by rishabh135** [comment]
@ebrevdo  I am facing a similar issue , how do I migrate my code to v1.1 from 0.9 , 
```
        #cell = tf.nn.rnn_cell.LSTMCell(self.num_input, self.num_input)
        cell = tf.contrib.rnn.BasicLSTMCell(self.num_input, self.num_input)
        #print(_X.shape)
        state = _istate
        for step in range(self.num_steps):
            outputs, state = tf.nn.rnn(cell, [_X[step]], state)
            #outputs, state = tf.contrib.rnn.BasicRNNCell(cell, _X[step], state)
            tf.get_variable_scope().reuse_variables()
        return outputs
```
but I am getting the following error : 
```
    outputs, state = tf.nn.rnn(cell, [_X[step]], state)
AttributeError: 'module' object has no attribute 'rnn'
*** Error in `python': free(): invalid pointer: 0x0000000000e032f0 ***
Aborted (core dumped)
```
