### ISSUE TITLE
why is there different latency for post-training quantization and quantization-aware trained models? 

### ISSUE THREAD

**Issue by grobman** [tensorflow/tensorflow#24744]
**System information**
- TensorFlow version: TFlite 
- Doc Link:https://www.tensorflow.org/lite/performance/model_optimization

in the model optimization documentation page:
https://www.tensorflow.org/lite/performance/model_optimization
Table 1 gives a latency of 145ms for post-training quantization and 80.2 for quantization-aware training. 

it is unclear to me why there should be a difference in latency as both methods results in models that use 8-bit operation. The documentation implies that the benefit of using quantization aware training is to increase model accuracy when using int8, but from the table it seems that latency is also improved. why is that?

**Comment by freedomtan** [comment]
The reason is well explained in another doc, the [post_training_quantization](https://www.tensorflow.org/lite/performance/post_training_quantization) page. In short, models quantized by post-training quantization compute using floating point kernels; models quantized by quantization aware training use fixed-point kernels.

**Comment by grobman** [comment]
Thanks for the reply!

However, I still find it confusing as the move from floating kerenl to fixed point kernels is done via graph_freezing as explained in the [quantization-aware training](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/quantize/README.md) doc.

Is there no way to freeze the eval graph created by post training quantization to get the full speed up offered by using fixed point kernels? After all these graphs are conceptually the same. It would seem to be a shame to force a user to go through the train process if she only wishes to gain the latency speed-up.

A slightly unrelated issue that I cannot find any documentation on - does the TFlite quantization use channel-wise quantization as explained in [1] or layer-wise quantization?

[1] [Quantizing deep convolutional networks for efficient inference: A whitepaper](https://arxiv.org/abs/1806.08342)

**Comment by msymp** [comment]
Hello @grobman , we would like to thank @freedomtan for addressing your post-training quantization vs. quantization-aware training query in TFLite.
Please kindly submit a follow up issue for your query:
A slightly unrelated issue that I cannot find any documentation on - does the TFlite quantization use channel-wise quantization as explained in [1] or layer-wise quantization? https://arxiv.org/abs/1806.08342
Thanks. This issue is closed.
