### ISSUE TITLE
regarding tensor flow detect code 

### ISSUE THREAD

**Issue by chiragmak1** [tensorflow/tensorflow#24809]
hello guys 
how can we get TFdetect code only and 
how is it installing 4 apps  at a time 

thank in advance for your generous help

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
