### ISSUE TITLE
Problem in header file

### ISSUE THREAD

**Issue by Arafatk** [tensorflow/tensorflow#2486]
On this [line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/core/status.h#L22). 
The file `error_codes.pb.h` is not present.

**Comment by mrry** [comment]
This file is automatically generated (using `protoc`) from [`error_codes.proto`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/core/error_codes.proto). If you build TensorFlow using Bazel, the file will be generated for you. Otherwise, you will need to run `protoc` on that file to generate the C++ implementation of
