### ISSUE TITLE
Eager mode / AutoGraph control dependencies

### ISSUE THREAD

**Issue by botev** [tensorflow/tensorflow#24874]
In the current main examples of `autograph` which uses eager mode when calling `opt.minimize` there is this comment:
```
  # Autograph automatically adds the necessary `tf.control_dependencies` here.
  # (Without them nothing depends on `opt.minimize`, so it doesn't run.)
  # This makes it much more like eager-code.
```
So my question is could you clarify how this magic is happening behind the scenes (e.g. what are the conditions for which autograph creates these dependencies and if one wants to somehow force in eager mode some form of dependencies, how to achieve it. For instance consider the following "python" code:
```
def some_fn(x, m, t):
   if t % 100 == 0:
       m = m * 0.9 + x ** 2 * 0.1
   return x / tf.sqrt(m)
```
Here we want the final value of` to always be either the input or the updated value dependable on `t`. How can we force this control dependency?

**Comment by mdanatg** [comment]
Note that TF 2.0 includes an automatic control dependencies mechanism that is better than autograph's explicit `tf.control_dependencies`. So if at all possible we recommend using `tf.function` (`tf.function` also uses autograph) which ensures the stateful ops in the graph are sequenced in the order in which they were created (that is, program order). We'll update autograph to use this new system soon as well.

I'll describe the old mechanism below, for completeness. Then at the end I'll describe what happens in the case of the `if` statement, which doesn't need control dependencies at all.

**The old mechanism for control dependencies:**

In the case of `opt.minimize`, we used `tf.control_dependencies`. There are a few heuristics, the most important being that a function whose value is not used will be sequenced before all the statement that follow it. For example:

```
opt.minimize(...)
... other computations ...
```

is transformed into:

```
with tf.control_dependencies([opt.minimize(...)]):
  ... other computations ...
```

**Data dependencies due to if statements**

In the case of the example you listed:
```
   if t % 100 == 0:
       m = m * 0.9 + x ** 2 * 0.1
   return x / tf.sqrt(m)
```

the code is transformed into:

```
  m = tf.cond(
    t % 100 == 0,
    lambda: m * 0.9 + x ** 2 * 0.1,
    lambda: m)
  return x / tf.sqrt(m)
```

The functional form of TensorFlow's conditionals hopefully makes it more obvious that the modified variable has an explicit data dependency to the conditional that precedes it. So `m` will always have the correct value.

Let me know if anything else is unclear.

**Comment by facaiy** [comment]
Perhaps the document is also useful for understanding:
https://github.com/tensorflow/community/pull/20/files#diff-d5334516fd698a57cc5641aed4068e7fR166
