### ISSUE TITLE
seq2seq decoding after training in the same script

### ISSUE THREAD

**Issue by gorinars** [tensorflow/tensorflow#2492]
According to [FAQ](https://www.tensorflow.org/versions/r0.8/resources/faq.html), when session is closed, the model should be removed. 

However, when trying to test the seq2seq model in TensorFlow 0.7.1 right after training (in a different session, but within the same python script), an error appears.

Specifically, [rnn/translate/translate.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/models/rnn/translate/translate.py)

I add `decode()` function after training in order to not re-run the script for decoding:
```
def main(_):
   train()
   decode()
```

After training I get the following error message:
>  ValueError: Over-sharing: Variable embedding_attention_seq2seq/RNN/EmbeddingWrapper/embedding already exists, disallowed. Did you mean to set reuse=True in VarScope?
 
[Log file with error](https://github.com/tensorflow/tensorflow/files/280063/error_translate.txt)

When running decoding separately, this code works fine. So, I am just confused why closing training session and opening a new one for decoding makes the program stuck...does it mean some model variables are not removed when session closes?

**Comment by vrv** [comment]
@lukaszkaiser any ideas when or why this could happen?  This seems like a python-level issue, not a runtime one...

**Comment by lukaszkaiser** [comment]
Variables are stored with the graph, not session. So it looks like we're changing the session but the graph remains. I'm not 100% sure what's the intention, will try to construct a much smaller example tomorrow (it doesn't look like anything specific to seq2seq, but an interaction between session and variables).

**Comment by lukaszkaiser** [comment]
Indeed, I can confirm that variables are stored in the graph which is not reset with session. So this is behaving as intended. If you want to create a graph twice, separately, do it like this:

  with tf.Graph().as_default():
    train()  # or anything else...
  with tf.Graph().as_default():
    decode()  # or anything else...

**Comment by gorinars** [comment]
Thanks. This fixed the problem

**Comment by fighting41love** [comment]
@gorinars Hi, I'm new to tensorflow. 
I have the same error.
Could you please give me some details about how to modify the codes?
Thanks!

**Comment by gorinars** [comment]
@fighting41love not sure which code you are working on, but what helped was what @lukaszkaiser suggested above.

You can check [this example](https://github.com/cmusphinx/g2p-seq2seq/blob/master/g2p_seq2seq/app.py)

**Comment by fighting41love** [comment]
Thanks! @gorinars  
I'm working on this script: [translate.py (code-to-comment)](https://github.com/thaije/code-to-comment/blob/master/seq2seq/translate.py)
In function train() (line 224), we just remove the "#" from lines 277 and 278.
In this case, the code can train a model for every 5000 steps, then save the model, and then evaluate the performance.

An error appears as follows:

Traceback (most recent call last):
  File "translate.py", line 443, in <module>
    tf.app.run()
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "translate.py", line 440, in main
    train()
  File "translate.py", line 291, in train
    translate_file(source_path=dev_code_file,target_path=translated_dev_code)
  File "translate.py", line 149, in translate_file
    model = create_model(sess, True)
  File "translate.py", line 225, in create_model
    forward_only=forward_only)
  File "/Users/yy/PycharmProjects/test_code2comment/seq2seq/seq2seq_model.py", line 89, in __init__
    w = tf.get_variable("proj_w", [size, self.target_vocab_size])
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 339, in get_variable
    collections=collections)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 262, in get_variable
    collections=collections, caching_device=caching_device)
  File "/anaconda/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 118, in get_variable
    name, "".join(traceback.format_list(tb))))
**ValueError: Variable proj_w already exists, disallowed. Did you mean to set reuse=True in VarScope? Originally defined at:**

  File "/Users/yy/PycharmProjects/test_code2comment/seq2seq/seq2seq_model.py", line 89, in __init__
    w = tf.get_variable("proj_w", [size, self.target_vocab_size])
  File "translate.py", line 225, in create_model
    forward_only=forward_only)
  File "translate.py", line 248, in train
    model = create_model(sess, False)

The translate.py of code-to-comment is a little different from this [example](https://github.com/cmusphinx/g2p-seq2seq/blob/master/g2p_seq2seq/app.py).

I think the problem is the same. But I don't know how to fix the error in my code...

Thanks!
