### ISSUE TITLE
embedding_lookup return a SparseTensor

### ISSUE THREAD

**Issue by 1049451037** [tensorflow/tensorflow#24951]
Neither embedding_lookup nor embedding_lookup_sparse can return a sparse tensor. Could you add a feature to support SparseTensor returned?

I don't mean just convert the dense to sparse. It's **sparse lookup**.

**Comment by jvishnuvardhan** [comment]
@1049451037 Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by 1049451037** [comment]
Hi @jvishnuvardhan , it's a recent work about graph convolutional networks. https://arxiv.org/abs/1811.04441

The idea is that we need a sparse matrix that represent the ajacency matrix of the graph. However, each non-zero element of the matrix is not a constant, but a variable, which we want to lookup from a tensor.

**Comment by skye** [comment]
@ebrevdo @martinwicke who owns embedding ops?

**Comment by ebrevdo** [comment]
I'm trying to understand the use case.  the whole point of embedding_lookup is to take a sparse tensor, and get a dense tensor back.  embedding_lookup_sparse refers to the sparsity of the input arguments, not the outputs (those are still embeddings...dense tensors...)

**Comment by 1049451037** [comment]
Yes, the feature I request here is taking dense in and giving sparse back, which is different from both embedding_lookup and embedding_lookup_sparse.
