### ISSUE TITLE
error while loading shared libraries: libprotobuf.so.17: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Avin-Techv** [tensorflow/tensorflow#25018]
techv@techversant-pc:~/Desktop/django-deepspeech-server/tensorflow$ tensorflow/contrib/makefile/gen/bin/benchmark  --graph=$HOME/graphs/inception/tensorflow_inception_graph.pb
tensorflow/contrib/makefile/gen/bin/benchmark: error while loading shared libraries: libprotobuf.so.17: cannot open shared object file: No such file or directory

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by sathyamoorthyrr** [comment]
Hi, same error. Have filed an [issue](https://github.com/tensorflow/tensorflow/issues/25576)
