### ISSUE TITLE
The scale parameter in the slim.batch_norm

### ISSUE THREAD

**Issue by UpCoder** [tensorflow/tensorflow#25041]
**System information**
- TensorFlow version: tensorflow-gpu 1.4.0
- Doc Link: [link](https://github.com/tensorflow/tensorflow/blob/467c1c2e215c5481372ba4e685869ae504b9e74f/tensorflow/contrib/layers/python/layers/layers.py#L226)

I try to know the details of slim.batch_norm's parameters. We know the formula of the BN is like y = gamma * x + beta. And when the BN layer before the non-linear layer (like the relu), why the gamma need to set 1.0? Does it will harm the performance? In addition, in the doc, the relu is linear? why is the scaling done by the relu?
```
 scale: If True, multiply by `gamma`. If False, `gamma` is
            not used. When the next layer is linear (also e.g. `nn.relu`), this can be
            disabled since the scaling can be done by the next layer.
```

**Comment by msymp** [comment]
@UpCoder ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
[New Issue Template](https://github.com/tensorflow/tensorflow/issues/new)

**Comment by jvishnuvardhan** [comment]
Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. Github is mainly for addressing bugs in installation and performance. Thanks!
