### ISSUE TITLE
No code example which allows to use tensorflow lite immediately in iOS

### ISSUE THREAD

**Issue by Gargo** [tensorflow/tensorflow#25045]
**System information**
- TensorFlow version: 1.12.0
- Doc Link:
https://www.tensorflow.org/lite/tfmobile/ios_build

Most iOS developers use Swift and Objective C. But tensorflow is written in C++ and "examples" require strong C++ knowledge too. In the same time that code contains a lot of hardcoded data and it is very hard to understand how to use it in general!

A lot of time passed. Why not to write a class-wrapper over tensorflow to hide C++ code from developers? For example, code should convert `UIImage` to `NSString` or array of strings

**Comment by msymp** [comment]
@Gargo , can you please clearly describe your issue that you are facing? Also
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
[New Issue Template](https://github.com/tensorflow/tensorflow/issues/new)

**Comment by User2004** [comment]
https://webappcodes.com/category/ios

Here, above link you find all ios example codes

**Comment by miaout17** [comment]
We recently improved the [iOS demo document](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/demo_ios.md) and added more explanation. 
We're also working on adding more language binding support. Stay tuned.

**Comment by jvishnuvardhan** [comment]
Thanks @miaout17. I am closing this as I don't see a reason to keep this open. Thanks!
