### ISSUE TITLE
Error: No gradient defined for operation (op type: CropAndResizeGradImage)

### ISSUE THREAD

**Issue by john81923** [tensorflow/tensorflow#25050]
I'm running FasterRCNN model with second ordered differentiation. 
but an error occur: 
`No gradient defined for operation 'tower0/gradients/tower0/roi_align/crop_and_resize/CropAndResize_grad/CropAndResizeGradImage' (op type: CropAndResizeGradImage)` 

I have been looking on the internet and haven't found a solution 
please help
thank you

**Comment by msymp** [comment]
@john81923 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
[New Issue Template](https://github.com/tensorflow/tensorflow/issues/new)

**Comment by jvishnuvardhan** [comment]
Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. When you post this issue in Stackoverflow, please provide more details on the issue so that community will support you faster. Thanks!

**Comment by ppwwyyxx** [comment]
This is a feature request for the second order gradients of `tf.image.crop_and_resize`

**Comment by jvishnuvardhan** [comment]
@ppwwyyxx Could you provide more details on the context and issue. Please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?template=30-feature-request.md). More details help us to faster solution. Thanks!

**Comment by ppwwyyxx** [comment]
I was only pointing out the nature of this issue and do not actually intend to request this feature myself as it is not useful to me. In fact I think this feature may be only useful to a few people in the world trying out very new ideas (who may just implement it by themselves with a new op).

**Comment by rmothukuru** [comment]
@john81923,
Can you please confirm if the issue is still relevant? You can refer the [Tensorflow Documentation for Second Order Differentiation ](https://www.tensorflow.org/guide/advanced_autodiff). Thanks!
