### ISSUE TITLE
No code examples for rewriting existing graph using tf.quantization.fake_quant_with_min_max_vars for quantization-aware training

### ISSUE THREAD

**Issue by ayulek** [tensorflow/tensorflow#25077]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 1.12.0
- Doc Link:

**Describe the documentation issue**
It would be great if code examples or a tutorial can be written up to help with manually inserting fake quant nodes into an existing TensorFlow graph. The current rewriter provided in contrib/quantize doesn't seem to be able to handle complex graphs well.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by tilakrayal** [comment]
@ayulek,
Have you got the chance to have a look at this official document where the required details were updated for the **tf.quantization.fake_quant_with_min_max_vars** where it uses Fake-quantize the 'inputs' tensor of type float via global float scalars.
https://www.tensorflow.org/api_docs/python/tf/quantization/fake_quant_with_min_max_vars

**tf.quantization.fake_quant_with_min_max_vars** is commonly used for training-time Int8 fake-quantisation in TF, and when used correctly will cause the TFLite converter to output int8 (rather than float) ops.

`tf.quantization.fake_quant_with_min_max_vars` requires a min/max quantisation scale to be passed in as TF variables. This means that the scales can be updated during training. However, one could conceivably instead use tf.quantization.**fake_quant_with_min_max_args**, which is the same op with the exception that the min/max scales are passed in as constants rather than variables.

Also please find the example for the same api below.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/security/advisory/tfsa-2022-093.md#L16

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
