### ISSUE TITLE
Two roundings in MultiplyByQuantizedMultiplier(TFLite) leads to inconsistent result with tensorflow

### ISSUE THREAD

**Issue by Rasterer** [tensorflow/tensorflow#25087]
https://github.com/tensorflow/tensorflow/blob/ff91cd691027076e6128afbd902d3d38e3672787/tensorflow/lite/kernels/internal/common.h#L105
Per my understanding, `MultiplyByQuantizedMultiplier` is used to simulate floating point multiplication.
But in some cases, the two roundings in it will cause different result from floating point arithmetic, which will further lead to unpredictable tflite accuracy compared with tensorflow training pipeline.

`inline int32 MultiplyByQuantizedMultiplier(int32 x, int32 quantized_multiplier, int shift)`
Assume x = 7984, quantized_multiplier = 1583594044, shift = -9 (the simulated floating point arithmetic is `std::round(7984 * 0.0014402703931141053)`). The multiplication of x and quantized_multiplier will be 12643414847296(0xB7FC6402F40), it will undergo two rounding shift(one in `SaturatingRoundingDoublingHighMul` and the other one in `RoundingDivideByPOT`), and results in number 12. But the floating point result is 11. We can find that if we combine these two rounding shifts into one, i.e. do only one rounding shift, the results will be 12, which matches with floating point result.

**Comment by suharshs** [comment]
Hi, could you describe more what you mean by "do only one rounding shift"?

Since we are doing integer math to approximate a float scale, it is inevitable that for some values we will have an error. We can plan with the logic to move that error around, but we cannot represent all values exactly without using an actual float value.

**Comment by Rasterer** [comment]
Well, in the case I described above, `SaturatingRoundingDoublingHighMul` will perform **31** bits right shift, and `RoundingDivideByPOT` will perform **9** bits right shift, I mean if we only do one **(31+9)** bits right shift instead, then this issue can be avoided.

I understand that being bit-match might be very difficult, but this issue will result in quite large relative error(sometimes >20%), and more than 5% elements of a feature map will hit this issue in one convolution layer from my observation. So I think it has significant impact to the final accuray.

**Comment by jianlijianli** [comment]
Hey, thanks for raising the question and explaining your logic in the example.

I think the problem is not with splitting the 31 bit shift and 9 bit shift: (a >> 31) >> 9 is the same as a >> 40, assuming there is no overflow. The subtle difference in from the "nudge" in gemmlowp (https://github.com/google/gemmlowp/blob/master/fixedpoint/fixedpoint.h#L320), that instead of (a >> 31) >> 9, it becomes ((a + delta) >> 31) >> 9. The nudge logic is added to simulate "VQRDMULH".
- if one merges the >> 9 to .../(1ll<<31) to make it .../(1ll<<40), the result is still 12.
- If one forces "nudge" to be zero, the result is 11.

BTW, the value just happen to be close to one of the 0.5. Without nudge, SaturatingRoundingDoublingHighMul gives 5887 and 5887/2^9 = 11.49, which rounds to 11; with nudge, SaturatingRoundingDoublingHighMul gives 5888 and 5888/2^9 = 11.5, which rounds to 12.

Do you have a measurement of the overall accuracy impact because of this rounding? Thanks.

**Comment by kaigeplus** [comment]
Hi, what is this "The nudge logic is added to simulate "VQRDMULH". Why is it necessary?

**Comment by windhw** [comment]
> Hey, thanks for raising the question and explaining your logic in the example.
> 
> I think the problem is not with splitting the 31 bit shift and 9 bit shift: (a >> 31) >> 9 is the same as a >> 40, assuming there is no overflow. The subtle difference in from the "nudge" in gemmlowp (https://github.com/google/gemmlowp/blob/master/fixedpoint/fixedpoint.h#L320), that instead of (a >> 31) >> 9, it becomes ((a + delta) >> 31) >> 9. The nudge logic is added to simulate "VQRDMULH".
> 
> * if one merges the >> 9 to .../(1ll<<31) to make it .../(1ll<<40), the result is still 12.
> * If one forces "nudge" to be zero, the result is 11.
> 
> BTW, the value just happen to be close to one of the 0.5. Without nudge, SaturatingRoundingDoublingHighMul gives 5887 and 5887/2^9 = 11.49, which rounds to 11; with nudge, SaturatingRoundingDoublingHighMul gives 5888 and 5888/2^9 = 11.5, which rounds to 12.
> 
> Do you have a measurement of the overall accuracy impact because of this rounding? Thanks.

--> The nudge logic is added to simulate "VQRDMULH".
I think using VQRDMULH is wrong here,  because the result is not final number and you need to perform rounding-shift again.  Rounding after 31-bit shifting will cause the error on numbers such as x.499. 
I think VQDMULH without rounding is the correct instruction to use.

**Comment by Tombana** [comment]
> instead of (a >> 31) >> 9, it becomes ((a + delta) >> 31) >> 9.
>     * if one merges the >> 9 to .../(1ll<<31) to make it .../(1ll<<40), the result is still 12.

I'm also a bit puzzled by the gemmlowp mechanism.
If I understand correctly, in `RoundingDivideByPOT`, effectively another nudge is added, making it `(((a+delta_1) >> 31) + delta_2) >> 9`. (This is not implemented by adding a constant `delta_2` but by checking if the 'shifted-away-bits' are larger than a threshold, and then adding 1 to the result.).
I think that's the reason why the two separate shifts are not the same as a single shift of 40, and that might be the cause of these rounding mismatches ?

**Comment by Tombana** [comment]
@petewarden  Would it be a good idea to use this rounding on tflite-micro ?

**Comment by bjacob** [comment]
Bit-exactness is not part of the contract here. Do whatever is friendly to your target hardware as long as it's a reasonable round-to-nearest scheme without significant bias.

It is expected that different hardware targets will run different, non-bit-exact flavors of MultiplyByQuantizedMultiplier and RoundingRightShift.

Regarding MultiplyByQuantizedMultiplier:
For example, we have seen people use 16-bit fixedpoint instead of 32-bit fixedpoint multipliers on Qualcomm HVX, and we have seen people use float32 instead of 32-bit fixedpoint multipliers on Google EdgeTPU.

Regarding RoundingRightShift:
Even on ARM NEON, our thinking has evolved a bit. We used to think that it would be important for the rounding right shift to break ties away from zero, out of a concern that breaking ties upward would be "biased". However, in practice, away-from-zero is only unbiased if the data is centered around zero, which it not always is, so there was no practical unbiasing benefit from that, so we now happily use ARM NEON's own "rounding right shift", breaking ties upward.

In the newer matrix multiplication library used by TFLite in the quantized case on ARM, we are using SQRDMULH followed by RSHL i.e. native NEON rounding shift per the previous paragraph, by default. We've retained the ability to compile to the old break-ties-away-from-zero way but might drop it soon.
Search for NATIVE_ROUNDING in this file,
https://github.com/google/ruy/blob/a0ca5e6d3d1b1771197368c5cf38de1f9fe7f1e0/ruy/kernel_arm64.cc

We hadn't bothered to update these TFLite functions because not much time was being spent there.

Do you care about the efficiency of these functions because they're significant on your CPU profiles or do you care about the clarification that bit-exactness is not required for your own ports?  In the former case, we'll happily take a patch optimizing these functions by relaxing them as in the above-linked ruy code. In the latter case, this might be more of a documentation issue? Do you still see a need for SaturatingRoundingDoublingHighMulWithShift given the non-requirement of bit-exactness ?

**Comment by Tombana** [comment]
Thanks for the clarification, that helps a lot!
I will investigate the latency impact of this on the systems I'm interested in, and if its significant I'll submit a patch.

> Do whatever is friendly to your target hardware as long as it's a reasonable round-to-nearest scheme without significant bias.

I have one more question about this: from what I understood, the scheme should always round-to-nearest, and the freedom is in how perfect ties are rounded. But in the example above, the numbers `0.25`, `1.25`, `2.25` etc all get rounded upwards to `1`, `2`, `3` respectively, which is not round-to-nearest anymore. So is there more freedom than just the ties?

**Comment by bjacob** [comment]
Ah, I understand what you were saying now, sorry that I didn't read closely enough the first time.

It's not very well defined what exactly are the boundaries of what's allowed. As I alluded to above, some hardware targets have needed to perform these computations at lower bit depths, such as 16-bit fixedpoint multipliers on Qualcomm HVX or 23-bit-mantissa float32 on Google EdgeTPU. That in itself is more freedom than merely freedom in breaking ties. So when I said "Do whatever is friendly to your target hardware as long as it's a reasonable round-to-nearest scheme without significant bias." it had by necessity to include allowing for such deeper arithmetic differences, such as using lower precision data types, and then it seems unavoidable that we can't require off-by-one errors to be limited to ties only.  So yes, there is more freedom than just the ties.

How much freedom exactly, is not formalized at the moment.

Separate from "how much freedom do hardware ports have" is the other question "what code should TFLite carry as 'reference code'". TFlite's reference code needs to be accurate, portable, and give a reasonable starting point for porting to hardware. The current code is shown by the present issue to have a quite serious accuracy flaw, but on the other hand it's easy to port to hardware thanks to being a sequence of two distinct steps, MultiplyByQuantizedMultiplier and RoundingRightShift, each of which tends to be fairly well understood how to map to hardware. by contrast, SaturatingRoundingDoublingHighMulWithShift is better accuracy-wise but it is apparently difficult to port to most hardware, because it seems to require going through twice-wider integer (e.g. 32bit -> 64bit) to apply the nudge there, unless the architecture natively has an instruction for doing exactly that computation (it's not inherently harder to implement in hardware, it just does not fit common fixed-point-multiplication instructions). So at this point I don't know what we can usefully do about this.  Maybe at least add a summary of this discussion / a link to this issue in a comment ?

**Comment by Tombana** [comment]
> TFlite's reference code needs to be accurate, portable, and give a reasonable starting point for porting to hardware. 

Thanks for the clarification, that makes a lot of sense, and the 'fix' I suggested does not satisfy those criteria.

> it seems to require going through twice-wider integer (e.g. 32bit -> 64bit) to apply the nudge there

I'm not sure if that is a big problem, since the nudge was already being added to the 64-bit multiplication result, before it was right-shifted back into a 32-bit value. I do agree that the function as a whole would no longer translate to a common hardware instruction.

> Maybe at least add a summary of this discussion / a link to this issue in a comment ?

That sounds good to me.


I have been running TF Micro on Cortex-M cores using CMSIS-NN, and it seems that in their effort to become [TF Micro compliant](https://github.com/ARM-software/CMSIS_5/blob/develop/CMSIS/NN/README.md), they have copied this reference rounding code, see [here](https://github.com/ARM-software/CMSIS_5/blob/5b694867a8c8dce47b860cf4a17403cc4754bafb/CMSIS/NN/Include/arm_nnsupportfunctions.h#L739-L743) .
As far as I know, on the Cortex-M series these two functions do not directly translate to instructions, in which case `SaturatingRoundingDoublingHighMulWithShift` would actually make things faster (and more accurate).
So based on what you're saying (and if its indeed faster), it makes sense to ping the devs of CMSIS-NN and tell them that the bit-exact match is not needed, and they can use `SaturatingRoundingDoublingHighMulWithShift`, potentially guarded by a preprocessor flag like `RUY_OPT_NATIVE_ROUNDING` from the example you linked to.

(The tflite implementation of `MultiplyByQuantizedMultiplier` could also do this based on such a preprocessor flag, but that would only affect reference code so it should not matter so much.)

**Comment by bjacob** [comment]
> I do agree that the function as a whole would no longer translate to a common hardware instruction.

Right, that's the concern that I was highlighting here.

I agree with everything you say. I hadn't been following these developments around TFLite for microcontrollers. It does sound like some documentation or at least comments to make the conclusions of the present discussion more discoverable, would be useful.

Point taken that, SaturatingRoundingDoublingHighMulWithShift, while less friendly to NEON hardware, is more friendly to Cortex-M, so it arguably makes a better reference function to have here in TFLite code. I'd like to let others take it from here, as I haven't been very closely involved in this code for the past 2 years and I shouldn't end up owning this again. @suharshs ?

**Comment by suharshs** [comment]
Thanks @bjacob for the detailed responses.

We cannot change the default rounding mode in TFLite due to backwards compat issues, that being said since you are targetting a microcontroller, TFLite Micro may be able to accomodate this need in their infra. Will assign to them to get their thoughts.

Thanks!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
