### ISSUE TITLE
could you teach me how to config the openssl and icu lib？？？？？？

### ISSUE THREAD

**Issue by SuMacal2019** [tensorflow/tensorflow#25149]
tensorflow 1.12
win10
python 3.5
vs 2015 update3
compile tensorflow for tensorflow.dll and tensorflow.lib
could you teach me how to config the openssl and icu lib？？？？？？
how to package openssl and icu lib to tensorflow.dll and tensorflow.lib

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
