### ISSUE TITLE
Go Binding: Use runtime.KeepAlive

### ISSUE THREAD

**Issue by r0l1** [tensorflow/tensorflow#25246]
Please ensure to call runtime.KeepAlive, because the go bindings use finalizers which they shouldn't...
Reference: https://github.com/golang/go/issues/13347

Also ensure to call runtime.KeepAlive on every:

```go
var buf []byte
//...
unsafe.Pointer(&buf[0])
// C call here
runtime.KeepAlive(buf)
```

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
