### ISSUE TITLE
Library Conversion: Tensor2Tensor

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25352]
**Tensor2Tensor**, or [T2T](https://github.com/tensorflow/tensor2tensor) for short, is a library of deep learning models and datasets designed to make deep learning more accessible and [accelerate ML research](https://research.googleblog.com/2017/06/accelerating-deep-learning-research.html). T2T is actively used and maintained by researchers and engineers within the [Google Brain team](https://research.google.com/teams/brain/) and a community of users. You can chat with the T2T team on [Gitter](https://gitter.im/tensor2tensor/Lobby) and join the [T2T Google Group](https://groups.google.com/forum/#!forum/tensor2tensor).

The purpose of this ticket will be to migrate Tensor2Tensor to the TF 2.0 API.

- Convert all existing Tensor2Tensor code.
- Run unit tests.
- Ensure processes are well understood.

**Comment by Harsh188** [comment]
Hey @dynamicwebpaige @alextp! I would love to help out, I just need some guidance on where and how to start.

**Comment by manish-p-gupta** [comment]
Hey @alextp, is this Issue still up for contributions? I'm interested in helping out.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
