### ISSUE TITLE
Add integer data types to IsTrainable for use with custom gradients

### ISSUE THREAD

**Issue by jvmncs** [tensorflow/tensorflow#25386]
**System information**
- TensorFlow version (you are using): 1.12.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, there are a limited number of DTypes usable with autograd (see `IsTrainable` and `_IsBackpropagatable` below) https://github.com/tensorflow/tensorflow/blob/6631cd5e0e43e672d2de3cf1f0e29da17b57824e/tensorflow/python/ops/gradients_impl.py#L300

In particular, nodes with integer tensors automatically generate gradients of None, which breaks any call to `tf.gradients`.  This is a reasonable assumption for usual practices in machine learning, however this prevents one from creating their own autograd system using `tf.custom_gradient`.  I'd contend that, as a general purpose automatic differentiation library, TF should enable experimenting with such uses of its autograd system.  This would be particularly useful when intending to perform automatic differentiation over rings or finite fields, which are often represented in computers as sets of consecutive integers (i.e. `Z_p`).

**Will this change the current api? How?**
This change shouldn't affect any standard usage of TensorFlow -- all autograd on floats will be unchanged.  The only change will occur when calling autograd on graphs that compute integer arithmetic and similar.

Currently, performing `tf.gradients` on graphs with integer tensors will raise an unhandled error:
```python
import numpy as np
import tensorflow as tf

x_back = np.ones([2, 2])
y_back = np.ones([2, 2])
x = tf.Variable(x_back, dtype=tf.int32)
y = tf.Variable(y_back, dtype=tf.int32)
z = x + y
vg = tf.gradients([z], [x, y])
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    out = sess.run(vg)
    print(out)
```
Returns:
```
Traceback (most recent call last):
  File "/Users/jasonmancuso/dropout/research/customgrad/issue_min.py", line 16, in <module>
    out = sess.run(vg)
  File "/Users/jasonmancuso/anaconda/envs/tf-encrypted/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/Users/jasonmancuso/anaconda/envs/tf-encrypted/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    self._graph, fetches, feed_dict_tensor, feed_handles=feed_handles)
  File "/Users/jasonmancuso/anaconda/envs/tf-encrypted/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 471, in __init__
    self._fetch_mapper = _FetchMapper.for_fetch(fetches)
  File "/Users/jasonmancuso/anaconda/envs/tf-encrypted/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 261, in for_fetch
    return _ListFetchMapper(fetch)
  File "/Users/jasonmancuso/anaconda/envs/tf-encrypted/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 370, in __init__
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/Users/jasonmancuso/anaconda/envs/tf-encrypted/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 370, in <listcomp>
    self._mappers = [_FetchMapper.for_fetch(fetch) for fetch in fetches]
  File "/Users/jasonmancuso/anaconda/envs/tf-encrypted/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 258, in for_fetch
    type(fetch)))
TypeError: Fetch argument None has invalid type <class 'NoneType'>
```
See https://github.com/tensorflow/tensorflow/issues/783#issuecomment-175824168 for other cases in which Ops can generate a `None` gradient.

After implementing this feature, we'd return the following:
```
[array([[1, 1], [1, 1]], dtype=int32),
 array([[1, 1], [1, 1]], dtype=int32)]
```

**Who will benefit with this feature?**
Anyone who wants to perform automatic differentiation on integer data types, as would be the case when operating in integer rings or finite fields.

**Any Other info.**
This request is motivated by the [`tf-encrypted`](https://github.com/mortendahl/tf-encrypted) project.

**Comment by skye** [comment]
This is a cool use case, but unfortunately I think is too large a project to take on at this time. I think this would be a difficult feature to fully implement, because we'd have to make sure that every integer operation has a proper gradient function defined. Gradient functions are currently written with the assumption that we don't need to handle integers (e.g. we always return None for the indices param of a gather op). The result of this is, without careful auditing and/or testing, many gradients() calls over integers would silently return None or even the wrong answer. This is a big enough feature that we'd probably want close collaboration with someone on the TF team.

If there's enough demand in the future it might be worth the effort, but for now I don't think we can properly deliver on this.

cc @alextp @ebrevdo @martinwicke -- maybe I'm missing something that makes this more tractable?

**Comment by alextp** [comment]
I agree with @skye . It might be easier for you to bypass TF's gradient code entirely if you want to go this route, since our ops have gradients which don't behave well at all with integers.

**Comment by mortendahl** [comment]
@skye to understand the problem better and out of curiosity, would you mind pointing to a place where the assumption on returning None is used?

**Comment by skye** [comment]
Here's one I happen to run into recently: http://google3/third_party/tensorflow/python/ops/array_grad.py?l=410
Note that we always return None for the indices grad of [gather](https://www.tensorflow.org/api_docs/python/tf/gather). This is a niche case, but if you were attempting to take the gradient w.r.t. a variable that determines the indices, this grad function would silently return the wrong answer (None corresponds to zero gradient more or less). There are likely more, part of the difficulty is combing through all the gradient functions and finding them :)

**Comment by shaunster0** [comment]
I have this need for integer tensor and their gradients too ... it’s disappointing nothing seems to be happening with this, I think this will restrict future innovation in some interesting areas

**Comment by mohantym** [comment]
Hi @jvmncs !

It is not throwing any error in 2.8 version. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/d8e4788df634b069399c983e6fb70580/git_25836.ipynb) for reference.

Thank you!

**Comment by jvmncs** [comment]
Hi @mohantym, thanks for the response. It's nice to see that the error is no longer being thrown, but unfortunately I don't think that suffices to consider this issue solved. In particular, the check that forces a jump out of the backprop logic seems to be the same, just moved to a new location [here](https://github.com/tensorflow/tensorflow/blob/87462bfac761435a46641ff2f10ad0b6e5414a4b/tensorflow/python/eager/backprop_util.py#L48). Thus it's still not possible for integer-typed tensors to have non-None gradients, even when defined explicitly with a `tf.custom_gradient`.

FWIW, I think my understanding of TF's goals & aims has evolved. I would not be surprised if this feature were considered a non-goal for the project. It's a relatively niche request. Anyway, I think Jax might be a bit better fit for something so experimental.

**Comment by mohantym** [comment]
@jvmncs !
Thanks for the update.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
