### ISSUE TITLE
How can I do some process like segment_sum to a batch data in parrelel

### ISSUE THREAD

**Issue by kelvict** [tensorflow/tensorflow#25413]
For example..
I got an embedding matrix as follow:
embed_matrix = [
[0,0,0,0],
[1,1,1,1],
[2,2,2,2],
]

I have another input which decides which embedding should I use for summation to get a new embedding. 
ids = [
[0,1,],
[1,2,],
[0,1,2]
]

And I want a function f as folow.
f(embed_matrix, ids) 
= [
 [0, 0, 0] + [1, 1, 1],
 [1, 1, 1] + [2, 2, 2],
 [0, 0, 0] + [1, 1, 1] + [2, 2, 2],
]
= [
[1,1,1],
[3,3,3],
[3,3,3],
]

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
