### ISSUE TITLE
2.0 Reference Models: NMT Model (TPU with dist strat and Keras)

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#25432]
**Sequence-to-sequence** (seq2seq) models ([Sutskever et al., 2014](https://papers.nips.cc/paper/5346-sequence-to-sequence-learning-with-neural-networks.pdf), [Cho et al., 2014](http://emnlp2014.org/papers/pdf/EMNLP2014179.pdf)) have enjoyed great success in a variety of tasks such as machine translation, speech recognition, and text summarization. 

This model will give TF 2.0 end users a full understanding of seq2seq models and show them how to build a competitive seq2seq model from scratch. We focus on the task of **Neural Machine Translation** (NMT), which was the very first [testbed for seq2seq models](https://research.googleblog.com/2016/09/a-neural-network-for-machine.html).

For the TensorFlow 1.x equivalent, please refer [here](https://github.com/tensorflow/nmt).

The purpose of this issue is to migrate models into the TF 2.0 Keras API. Each migrated model must be eager and distribution compatible, with tests, and all associated engineering artifacts.

**Comment by JACKHAHA363** [comment]
Any updates? I find that the keras high level API is not flexible enough compared to the old `contrib.seq2seq`.

**Comment by npuichigo** [comment]
Any updates? +1

**Comment by rachellj218** [comment]
We are revamping the official model garden: more details can be viewed in this RFC https://github.com/tensorflow/community/pull/130. We focus on supporting BERT and its variants for NLP tasks this quarter. We'd like to have NMT but don't have cycles now. Will try it include it in Q4.

**Comment by gadagashwini** [comment]
Tensorflow v2.x supports Sequence-to-Sequence NMT with Attention Mechanism, for more information refer these links [ref1](https://www.tensorflow.org/addons/tutorials/networks_seq2seq_nmt) and [ref2](https://www.tensorflow.org/text/tutorials/nmt_with_attention). Thank you!

**Comment by mohantym** [comment]
Hi @dynamicwebpaige !
We are checking to see whether you still need help in this issue . 

 I think above  [add on documentation](https://colab.sandbox.google.com/gist/mohantym/998c0b39e0b215104b5d25601c44645a/networks_seq2seq_nmt.ipynb#scrollTo=mU3Ce8M6I3rz) are still not compatible with tpu /dist-strat/eager mode.


Tested with [ nmt_with_attention](https://www.tensorflow.org/text/tutorials/nmt_with_attention)  from Tensorflow/text. 
Results are not convincing in 2.9 too. 

Attached[ gist ](https://colab.sandbox.google.com/gist/mohantym/ee1e72393bbf291dfa792a45d4648ddb/nmt_with_attention.ipynb#scrollTo=5DWLI3pssjnx) for reference.

Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
