### ISSUE TITLE
np.array(x), where x is a tuple or list of tensor(s), is unusable (eager execution)

### ISSUE THREAD

**Issue by jpatts** [tensorflow/tensorflow#25439]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
No
- TensorFlow installed from (source or binary):
Source
- TensorFlow version (use command below):
b'v1.12.0-5845-g764109a352' 1.12.0
- Python version:
3.6.7
- Bazel version (if compiling from source):
Invocation ID: 42251854-036f-415c-8a52-76aac8520ea0
Build label: 0.21.0
Build time: Wed Dec 19 12:58:44 2018 (1545224324)
- GCC/Compiler version (if compiling from source):
gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version:
Cuda compilation tools, release 10.0, V10.0.130
- GPU model and memory:
GTX 1060 Max Q, 6gb VRAM

**Describe the current behavior**
If x is a list of any size, or a tuple of size >= 2, which contains tensors, np.array(x) is unusable as it runs exponentially longer than the tensor.numpy() function.

**Describe the expected behavior**
np.array(x) should run in a reasonable amount of time. Doing a simple list comprehension with tensor.numpy() shouldn't be faster.

**Code to reproduce the issue**

This shows the exponential time difference when x is a list containing a single tensor.
```
import numpy as np
import tensorflow as tf
import time

tf.enable_eager_execution()

x = [tf.zeros((32, 32, 12))]

start = time.time()
print("temp")
temp = np.array(x[0:1])
end = time.time()
print(end - start)

start = time.time()
print("temp1")
temp1 = np.array([x[0]])
end = time.time()
print(end - start)

start = time.time()
print("temp2")
temp2 = np.array([x[0].numpy()])
end = time.time()
print(end - start)

start = time.time()
print("temp3")
list = []
[list.append(t.numpy()) for t in x]
temp3 = np.array(list)
end = time.time()
print(end - start)

```
**Other info / logs**
Output:
temp
1.7468986511230469
temp1
1.7278409004211426
temp2
0.00018978118896484375
temp3
0.00024890899658203125

However, strangely enough, the problem only occurs with tuples when the length of the tuple is 2 or more. Changing x to the line below and running the same code generates similar results.
`x = (tf.zeros((32, 32, 12)), tf.zeros((32, 32, 12)))`

Why is it faster for me to use a list comprehension with t.numpy(), appending it to a list, and then run np.array(list), than it is to run np.array(x)?

**Comment by jpatts** [comment]
FYI my numpy version is 1.16.0

**Comment by alextp** [comment]
@akshaym this is weird, do you have time to take a look?

**Comment by akshaym** [comment]
Thanks for the report!

Based on reading some code, numpy special cases objects that are already np.arrays when converting sequences to python (code reference: https://github.com/numpy/numpy/blob/dea85807c258ded3f75528cce2a444468de93bc1/numpy/core/src/multiarray/ctors.c#L453) and there doesn't seem much we can do on the TF side to get around this.

Numpy does provide an API to allow this to be slightly faster (the tensor is iterated twice, one of which is to discover the shape - and that can be easily fixed by EagerTensor implementing numpy's array interface).

This is still not really ideal though, since when iterating through a tensor item by item, we create a bunch of temporary tensors. Your best bet is to continue to convert the individual tensors to numpy in the list, or to use something like ```tf.stack(x).numpy()``` instead.

**Comment by jpatts** [comment]
Thanks for looking into this! I guess I will avoid this function in the future for this use case.
