### ISSUE TITLE
[tf.data] non-used attributes in some tf.data operation definitions

### ISSUE THREAD

**Issue by feihugis** [tensorflow/tensorflow#25509]
Some attributes in [tf.data operation definition](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/dataset_ops.cc) (e.g. `RangeDataset`, `TensorDataset`, `TensorSliceDataset`) do not seem to be used in other places. 

Taken [RangeDataset](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/dataset_ops.cc#L339-L340) as an example, the `output_types` and `output_shapes` are required, but these attributes are not used in [range_dataset_op.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/data/range_dataset_op.cc).

**Comment by feihugis** [comment]
@allenlavoie Thanks for your explanation. It makes sense if these attributes were used in shape inference. 

@rachellim If you confirm it, I will close this issue.

**Comment by rachellim** [comment]
These attrs are not used for shape inference. It is possible that these attrs were used before, but the internal implementation of datasets has since changed such that the attrs aren't used in the kernels. Because of TF compatibility guarantees, the OpDefs can't be changed to remove them, and we have no plans to remove the unused attrs. Furthermore, these attrs are actually referenced in some optimizations, such as [map_vectorization](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/data/map_vectorization.cc#L135).

**Comment by feihugis** [comment]
Got it. Thanks, @rachellim.
