### ISSUE TITLE
Add support for circle_ci or travis upon pull request. 

### ISSUE THREAD

**Issue by Mistobaan** [tensorflow/tensorflow#2553]
It would be good to have an automatic and simple first continuous integration rule that will run when a pull request is submitted/updated. We could leverage some of the free services out there to handle this task. I presume both the compilation and the testing will be quite slow but it will provide a first line of filtering. The commands would be the same as in the ci_build so no active maintenance should be required.

**Comment by aselle** [comment]
We haven't prioritized this since we always needed to run all of our internal tests anyways, but it definitely seems like it would be handy for contributors to get an earlier feedback.

**Comment by jendap** [comment]
Any of the "CI as a service" would not work...

They can't run tests because compile alone takes more cpu and memory than limits on any of those services for open source projects - our jenkins nodes have far more cpu and memory and the builds take 15-30 minutes because they are cached. Does any of the free services persist workspace between builds? Even with cache it would not fit free tier limits (with some it would not fit even within paid limits).

Even our sanity job which takes 30 seconds to run in our current setup would take far longer. For example validation of BUILD files using "bazel --nobuild" would have to install bazel, fetch external dependencies - more than 1GB of source code from many git repositories and zip files...

There are a lot more more problems I know of. And we have not even tried it...

Given that said we might be able to enable some light build to be automatically trigger on ci.tensorflow.org. Not the full suite as it is for the time being too expensive.

@Mistobaan is there something in particular you would think should be triggered automatically?

**Comment by girving** [comment]
Closing as infeasible as @jendap discussed.  @Mistobaan: Please let us know if there are particular things we should fire off automatically.
