### ISSUE TITLE
About model size in ckpt format or numpy format

### ISSUE THREAD

**Issue by apple14755** [tensorflow/tensorflow#25805]
Hello, I got a strange question when I tried to convert model from ckpt format to numpy format.
I have two files for the source model in ckpt format
model.ckpt.index - 53.7KB
model.ckpt.data-00000-of-0001 - 330MB

But when I tried to use get_variable_to_shape_map() to get all variables from the src model and save them into a file with numpy format, I got a npy file with 494MB !!!

I wonder if I used the wrong way to convert ckpt to npy? Or if the ckpt model has been saved in some code formats so it looks small. 

Thank you !

**Comment by jvishnuvardhan** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
