### ISSUE TITLE
how to specify session target when using Estimator API

### ISSUE THREAD

**Issue by ustcyue** [tensorflow/tensorflow#25829]
Hi, I am trying to run my training graph in a remote server with remote session. I am able to do it by starting two tasks and specify the target of tf.Session as the first server. But seems there is noway to specify the target for tf.Session. Is there any workaround for this?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
