### ISSUE TITLE
Bug: ImportError: DLL load failed

### ISSUE THREAD

**Issue by quarterpastsix** [tensorflow/tensorflow#25824]
ImportError: DLL load failed
doesnt show the name of the DLL which failed

**Comment by jvishnuvardhan** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. Closing due to lack of recent activity. Please open new ticket if you see similar issue. Thanks!
