### ISSUE TITLE
Passing variable length sentences to Tensorflow LSTM

### ISSUE THREAD

**Issue by chinnusujitha** [tensorflow/tensorflow#25874]
I have a tensorflow LSTM model for predicting the sentiment. I build the model with the maximum sequence length 150. (Maximum number of words) While making predictions, i have written the code as below:

    batchSize = 32
    maxSeqLength = 150

    def getSentenceMatrix(sentence):
        arr = np.zeros([batchSize, maxSeqLength])
        sentenceMatrix = np.zeros([batchSize,maxSeqLength], dtype='int32')
        cleanedSentence = cleanSentences(sentence)
        cleanedSentence = ' '.join(cleanedSentence.split()[:150])
        split = cleanedSentence.split()
        for indexCounter,word in enumerate(split):
            try:
                sentenceMatrix[0,indexCounter] = wordsList.index(word)
            except ValueError:
                sentenceMatrix[0,indexCounter] = 399999 #Vector for unkown words
        return sentenceMatrix

    input_text = "example data"
    inputMatrix = getSentenceMatrix(input_text)\

In the code i'm truncating my input text to 150 words and ignoring remaining data.Due to this my predictions are wrong.

    cleanedSentence = ' '.join(cleanedSentence.split()[:150])
I know that if we have lesser length than sequence length we can pad with zero's. What we need to do if we have more length.
Can anyone suggest me the best way to do this. Thanks in advance.

**Comment by ymodak** [comment]
Please take a look at similar questions answered on [SO](https://stackoverflow.com/questions/34670112/how-to-deal-with-batches-with-variable-length-sequences-in-tensorflow).
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!

**Comment by chinnusujitha** [comment]
I know it's not a bug or feature request, but i couldn't found anywhere how to solve this problem, So i posted in stack overflow also,but i didn't get any response.
[](https://stackoverflow.com/questions/54421451/issue-with-maximum-sequence-length-while-making-predictions-using-lstm-model)
