### ISSUE TITLE
Ability to hook Iterator initialisation while using estimators

### ISSUE THREAD

**Issue by keotic** [tensorflow/tensorflow#25885]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I find it hard to track the epochs number while training with Estimators.
One possibility would be to hook the Dataset Iterator initialisation between epoch
combining the use of dataset.repeat(num_epochs) - (Assuming the Estimator is initialising the iterator between epochs) 
 
**Will this change the current api? How?**
No - just add another training hook.

**Who will benefit with this feature?**
Every developer / researcher that would like to track the number of training epochs in addition to
the training steps

**Any Other info.**
Other ways to track the epoch number should be fine as well

**Comment by rmothukuru** [comment]
@keotic, 
Sorry for the delayed response. In the **`Tensorflow Version 2.x`**, since we use [TF Keras](https://www.tensorflow.org/api_docs/python/tf/keras) predominantly and don't use [Estimators](https://www.tensorflow.org/guide/estimator) much, can you please let us know if this Feature is still relevant? Thanks!
