### ISSUE TITLE
tensorflow r1.6 use Eigen or intel mkl for matrix operation?

### ISSUE THREAD

**Issue by lebron374** [tensorflow/tensorflow#25889]
tensorflow r1.6 use Eigen or intel mkl for matrix operation?
and we user java api of tensorFlow 1.6 and try to optimize the time cost

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
