### ISSUE TITLE
can't split error

### ISSUE THREAD

**Issue by MADONOKOUKI** [tensorflow/tensorflow#25881]
Traceback (most recent call last):
  File "train.py", line 82, in <module>
    tf.app.run(main)
  File "/home/madono/.local/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "train.py", line 52, in main
    datasets = mnist.load_data()[:10000]
TypeError: 'ConditionalDataset' object is not subscriptable

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
