### ISSUE TITLE
TensorFlow "Development" Build Issue

### ISSUE THREAD

**Issue by zplizzi** [tensorflow/tensorflow#2591]
I just built Tensorflow from the most recent source (81db154), and attempted to set it up for a "development" install - using `python setup.py develop` after following the instructions in the [documentation](https://www.tensorflow.org/versions/master/get_started/os_setup.html#setting-up-tensorflow-for-development). After doing this, running `import tensorflow` in Python results in a "package not found" error. 

I have found that changing the line in the documentation 
```
ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow* .
````
to
```
ln -s ../bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/org_tensorflow/* .
```
solves the problem (the difference is an extra backtick near the end of the line). Perhaps this was a typo?

**Comment by cg31** [comment]
Yes, it should be a typo.

**Comment by rdadolf** [comment]
Just also pointing out that this documentation is also incorrect for bazel version 2.1 and earlier. The `org_tensorflow/` subdirectory doesn't exist, and these instructions will fail even if the typo is fixed (because of these two changesets: [one](https://github.com/tensorflow/tensorflow/pull/2336/files#diff-1cf444a338533a8469b274d1cd1b7229), [two](https://github.com/tensorflow/tensorflow/commit/14ac2235699509f512b44b71160239c153ab413d)).

The page mentions that users should "download the latest stable bazel version", but no supported (or minimum) version is mentioned. It looks like the project believes that [bazel 2.0+](https://github.com/tensorflow/tensorflow/blob/14ac2235699509f512b44b71160239c153ab413d/WORKSPACE) is sufficient.

**Comment by yaroslavvb** [comment]
From: https://github.com/tensorflow/tensorflow/issues/2497#issuecomment-221631692
Bazel 0.2.1 and lower, any TF: the path will be build_pip_package.runfiles/*
Bazel 0.2.2 with TensorFlow before 32fa42a: build_pip_package.runfiles/*
Bazel 0.2.2, TF after 32fa42a: build_pip_package.runfiles/org_tensorflow/*.
Bazel 0.2.3, TF before 32fa42a: build_pip_package.runfiles/__main__/*
Bazel 0.2.3, TF after 32fa42a: build_pip_package.runfiles/org_tensorflow/*

**Comment by rdadolf** [comment]
Yep, I was just re-discovering this because of ongoing problems over in #1704 (but thank you for the pointer&mdash;it's good to confirm this is real behavior). These changes broke the workarounds that I was using to get around the broken protobuf behavior. I went your route, too: just blow everything away and pull new copies of everything. I'll update #1704 when the dust settles, since [14ac223](https://github.com/tensorflow/tensorflow/commit/14ac2235699509f512b44b71160239c153ab413d) is supposed to fix this.
