### ISSUE TITLE
Adding labels to images while training

### ISSUE THREAD

**Issue by a4ankit** [tensorflow/tensorflow#25936]
Hi @nsthorat @tensorflower-gardener,  we were about to implement image recognization

I'm able to convert the image to tensor, now I want to add the label and give training to that image. If this gets succeeded then I want to do the same for multiple images with their respective labels. Any suggestions would be helpful.

Thanks

**Comment by Sri-vatsa** [comment]
Could you please tell me more about the model you are using and clarify more about the problem you are facing with labelling and training?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
