### ISSUE TITLE
Is tensorflow-mkl version same as tensorflow?

### ISSUE THREAD

**Issue by LittleFatHero** [tensorflow/tensorflow#25944]
OS: windows 10
Intel said that if I want to install the mkl version of tensorflow on windows 10, I have to use the command as following:
_conda install tensorflow-mkl_

However, Anaconda said that if I want to install the mkl version of tensorflow, I just need to execute the following command no matter my OS is windows or linux:
_conda install tensorflow_

I just want to know if tensorflow is the same as tensorflow-mkl when I install tensorflow using the _conda install_ command ?

**Comment by preethivenkatesh** [comment]
No, they are not the same on windows yet. Ideally, tensorflow from Anaconda must install mkl optimizations by default. However, due to old run time dependencies on windows, eigen version of tensorflow takes precedence over mkl version. This discrepancy has already been reported to Anaconda, and they are working on fixing their SAT solver to prefer mkl by default. In the meantime, please do ```conda install tensorflow-mkl``` to install mkl version. We'll notify once Anaconda makes the neccessary changes.

**Comment by TensorFlow-MKL** [comment]
addressed the original question.  Please reopen if you have further comments/questions
