### ISSUE TITLE
summary v2 create_file_writer() bug "SummaryWriterInterface does not exist"

### ISSUE THREAD

**Issue by ataiya** [tensorflow/tensorflow#25976]
Keeping the description brief as already discussed with @nfelt 

I am getting these errors when logging to tensorboard:
```
NotFoundError: Resource [....] N10tensorflow22SummaryWriterInterfaceE does not exist. [Op:WriteScalarSummary] name: loss/
```
This is a similar outcome to #25707, but it has a completely different cause (see below).

When using this "set_as_default" style:
```
# ... setup code
tf.contrib.summary.create_file_writer("/logdir/path/", flush_millis=2500).set_as_default()
# ... more setup code
for ibatch in range(iterations):
   # ... training code
   with tf.contrib.summary.record_summaries_every_n_global_steps(FLAGS.tb_every):
      tf.contrib.summary.scalar('loss', loss)
```

The problem does not take place when using this style:
```
# ... setup code
writer = tf.contrib.summary.create_file_writer("/logdir/path/", flush_millis=2500)
writer.set_as_default()
# ... more setup code
for ibatch in range(iterations):
   # ... training code
   with tf.contrib.summary.record_summaries_every_n_global_steps(FLAGS.tb_every):
      tf.contrib.summary.scalar('loss', loss)
```

This is very counter-intuitive as the writer was never used after, and therefore collapsing the two lines as I did should have not caused any problem!

**Comment by nfelt** [comment]
Just for context, this happens because the underlying resource is deleted when the SummaryWriter python object (returned by `create_file_writer()`) is no longer referenced.  Chaining the `.set_as_default()` method directly means there is no local variable reference to the writer.

I think the bug here is arguably that `.set_as_default()` only holds onto the underlying resource handle, not the SummaryWriter object itself, which breaks the abstraction that SummaryWriter should map 1:1 to the resource (which is also what #25707 is fixing, though a separate aspect of it).
