### ISSUE TITLE
tf.keras.layers.conv3Dtranspose error when input size is None

### ISSUE THREAD

**Issue by vikashranjan26** [tensorflow/tensorflow#25978]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04 / Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 1.12.0 / 1.10.0  /  1.9.0
- Python version: Python 3.6.7 
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 8.0
- GPU model and memory: Tesla M40 24GB

**Describe the current behavior**

Conv3DTranspose layer is producing an error message when the input layer dimension size is given None.

**Describe the expected behavior**

Like other layers, Conv3DTranspose layer should automatically infer the dimension size as well.

**Code to reproduce the issue**

Colab link to produce an error.
[https://colab.research.google.com/drive/1ee0LncVZIr8U4mQvmTW9R14Fpv31syO4](https://colab.research.google.com/drive/1ee0LncVZIr8U4mQvmTW9R14Fpv31syO4)

```

import tensorflow as tf

# Won't produce an error if we give explicitly the dimension size instead of None.
x2 = tf.keras.layers.Input(shape=(None,None,None,3), name='image_input')

x=tf.keras.layers.Conv3D(filters=64,kernel_size=(3,3,3),padding="same",activation='relu',name='Conv1')(x2)
x=tf.keras.layers.Conv3D(filters=64,kernel_size=(3,3,3),padding="same",activation='relu',name='Conv2')(x)

x=tf.keras.layers.Conv3DTranspose(filters=128,kernel_size=(3,3,3),padding="same",activation='relu',name='Conv6')(x)
x=tf.keras.layers.Conv3DTranspose(filters=64,kernel_size=(3,3,3),padding="same",activation='relu',name='Conv8')(x)

mod=tf.keras.models.Model(inputs=x2,outputs=x)
mod.summary()

```
**Output**
```

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3ec84051b623> in <module>()
      6 x=tf.keras.layers.Conv3D(filters=4,kernel_size=(3,3,3),padding="same",activation='relu',name='Conv2')(x)
      7 
----> 8 x=tf.keras.layers.Conv3DTranspose(filters=4,kernel_size=(3,3,3),padding="same",activation='relu',name='Conv6')(x)
      9 x=tf.keras.layers.Conv3DTranspose(filters=4,kernel_size=(3,3,3),padding="same",activation='relu',name='Conv8')(x)
     10 

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    701 
    702       if not in_deferred_mode:
--> 703         outputs = self.call(inputs, *args, **kwargs)
    704         if outputs is None:
    705           raise ValueError('A layer\'s `call` method should return a Tensor '

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/layers/convolutional.py in call(self, inputs)
   1060       else:
   1061         outputs_4d = array_ops.reshape(outputs, [
-> 1062             outputs_shape[0], outputs_shape[1] * outputs_shape[2],
   1063             outputs_shape[3], outputs_shape[4]
   1064         ])

TypeError: unsupported operand type(s) for *: 'NoneType' and 'NoneType'


```

**Comment by yongtang** [comment]
I could reproduce with 1.13.0rc2 but not with tf-nightly. I think the issue has been fixed in the master branch.

**Comment by facaiy** [comment]
Yes, it has been fixed in #23004.

**Comment by facaiy** [comment]
@myron gets stuck in the same problem.

**Comment by vikashranjan26** [comment]
Thank you @facaiy it is working as expected in tf-nightly.

**Comment by facaiy** [comment]
Closing as it's fixed

**Comment by Meiyd** [comment]
No it is still not fixed until today!

**Comment by Meiyd** [comment]
Hi, here's my code:

input_img = keras.layers.Input( shape=( None, len(params2), len(params2), 1 ) ) # adapt this if using `channels_first` image data format

conv1 = keras.layers.Conv3D(filters=32, kernel_size=(1, 3, 3), strides=(1, 1, 1), activation='selu', padding='same', data_format='channels_last', name='conv1')(input_img)
conv2 = keras.layers.Conv3D(filters=64, kernel_size=(1, 3, 3), strides=(1, 2, 2), activation='selu', padding='same', data_format='channels_last', name='conv2')(conv1)
conv3 = keras.layers.Conv3D(filters=128,kernel_size=(1, 3, 3), strides=(1, 2, 2), activation='selu', padding='same', data_format='channels_last', name='conv3')(conv2)
conv4 = keras.layers.Conv3D(filters=256,kernel_size=(1, 3, 3), strides=(1, 2, 2), activation='selu', padding='same', data_format='channels_last', name='conv4')(conv3)

convlstm1 = keras.layers.ConvLSTM2D(filters=32, return_sequences=True, kernel_size=(3, 3), strides=(1, 1), activation='selu', padding='same', data_format='channels_last', name='convlstm1')(conv1)
convlstm2 = keras.layers.ConvLSTM2D(filters=64, return_sequences=True, kernel_size=(3, 3), strides=(1, 1), activation='selu', padding='same', data_format='channels_last', name='convlstm2')(conv2)
convlstm3 = keras.layers.ConvLSTM2D(filters=128,return_sequences=True, kernel_size=(3, 3), strides=(1, 1), activation='selu', padding='same', data_format='channels_last', name='convlstm3')(conv3)
convlstm4 = keras.layers.ConvLSTM2D(filters=256,return_sequences=True, kernel_size=(3, 3), strides=(1, 1), activation='selu', padding='same', data_format='channels_last', name='convlstm4')(conv4)

deconv4 = keras.layers.Conv3DTranspose(filters=128, kernel_size=(1, 2, 2), strides=(1, 2, 2), activation='selu', padding='valid', output_padding=(0, -1, -1), data_format='channels_last', name='deconv4')(convlstm4)
concat4 = keras.layers.Concatenate(axis=4, name='concat4')([convlstm3, deconv4])
deconv3 = keras.layers.Conv3DTranspose(filters=64 , kernel_size=(1, 2, 2), strides=(1, 2, 2), activation='selu', padding='valid', output_padding=(0, -1, -1), data_format='channels_last', name='deconv3')(concat4)
concat3 = keras.layers.Concatenate(axis=4, name='concat3')([convlstm2, deconv3])
deconv2 = keras.layers.Conv3DTranspose(filters=32 , kernel_size=(1, 3, 3), strides=(1, 2, 2), activation='selu', padding='same' , data_format='channels_last', name='deconv2')(concat3)
concat2 = keras.layers.Concatenate(axis=4, name='concat2')([convlstm1, deconv2])
deconv1 = keras.layers.Conv3DTranspose(filters=1  , kernel_size=(1, 3, 3), strides=(1, 1, 1), activation='selu', padding='same' , data_format='channels_last', name='deconv1')(concat2)

autoencoder = keras.models.Model(input_img, deconv1)
autoencoder.compile(optimizer='adadelta', loss='binary_crossentropy')
autoencoder.summary()

and here's the error message:

TypeError                                 Traceback (most recent call last)
<ipython-input-150-83622ca7a77b> in <module>
     28     return autoencoder
     29 
---> 30 autoencoder1(1700)

<ipython-input-150-83622ca7a77b> in autoencoder1(file_length)
     14     convlstm4 = keras.layers.ConvLSTM2D(filters=256,return_sequences=True, kernel_size=(3, 3), strides=(1, 1), activation='selu', padding='same', data_format='channels_last', name='convlstm4')(conv4)
     15 
---> 16     deconv4 = keras.layers.Conv3DTranspose(filters=128, kernel_size=(1, 2, 2), strides=(1, 2, 2), activation='selu', padding='valid', output_padding=(0, -1, -1), data_format='channels_last', name='deconv4')(convlstm4)
     17     concat4 = keras.layers.Concatenate(axis=4, name='concat4')([convlstm3, deconv4])
     18     deconv3 = keras.layers.Conv3DTranspose(filters=64 , kernel_size=(1, 2, 2), strides=(1, 2, 2), activation='selu', padding='valid', output_padding=(0, -1, -1), data_format='channels_last', name='deconv3')(concat4)

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py in __call__(self, inputs, *args, **kwargs)
    552             # In graph mode, failure to build the layer's graph
    553             # implies a user-side bug. We don't catch exceptions.
--> 554             outputs = self.call(inputs, *args, **kwargs)
    555           else:
    556             try:

~/anaconda3/lib/python3.7/site-packages/tensorflow/python/keras/layers/convolutional.py in call(self, inputs)
   1138       else:
   1139         outputs_4d = array_ops.reshape(outputs, [
-> 1140             outputs_shape[0], outputs_shape[1] * outputs_shape[2],
   1141             outputs_shape[3], outputs_shape[4]
   1142         ])

TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'

You just said that this problem was solved. But I'm really not sure why I still have this problem today on April 2019.

**Comment by davidparkerhl** [comment]
With tf-nightly 1.15.0-dev20190706, this problem is resolved

**Comment by facaiy** [comment]
> With tf-nightly 1.15.0-dev20190706, this problem is resolved

Thanks for telling us, @davidparkerhl :-)
