### ISSUE TITLE
 Model transfer Tensorflow to Keras

### ISSUE THREAD

**Issue by sonfiree** [tensorflow/tensorflow#26005]
I want to transfer the model from Tensorflow to Keras. But I do not see this function

**Comment by ymodak** [comment]
Please take a look at similar [discussion](https://stackoverflow.com/questions/44466066/how-can-i-convert-a-trained-tensorflow-model-to-keras).
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
