### ISSUE TITLE
[TF Java] Support for AddControlInput in generated factory methods for building operations 

### ISSUE THREAD

**Issue by irenedea** [tensorflow/tensorflow#26024]
**System information**
- TensorFlow version (you are using): 1.12
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
There are automatically generated wrapper classes for Graph Operations that provide a neat interface and consistency in practice. We can easily create graph operations with the `create` method. 

However, there is no option to add control inputs to a newly built operation using these wrapper classes. 

For example, in the generated `Add.java` file:
```
    public static <T> Add<T> create(Scope scope, Operand<T> x, Operand<T> y) {
        OperationBuilder opBuilder = scope.graph().opBuilder("Add", scope.makeOpName("Add"));
        opBuilder.addInput(x.asOutput());
        opBuilder.addInput(y.asOutput());
        return new Add(opBuilder.build());
    }
```

**Will this change the current api? How?**

One possibility is to overload the `create` method, such that the new overloaded method would have an additional parameter that is a list of control inputs. This way, current usages of the original `create` method would not break. The proposed generated `create` method would look like:
```
    public static <T> Add<T> create(Scope scope, Operand<T> x, Operand<T> y, Iterable<Operand<T>> controlInputs) {
        OperationBuilder opBuilder = scope.graph().opBuilder("Add", scope.makeOpName("Add"));
        opBuilder.addInput(x.asOutput());
        opBuilder.addInput(y.asOutput());
       for (Operand<T> ctrl : controlInputs) { opBuilder = operBuilder.addControlInput(ctrl.asOutput().op()) }
        return new Add(opBuilder.build());
    }
```
This would require modifying `tensorflow/tensorflow/java/src/gen/cc/op_generator.cc` to add this to the code gen. 

**Who will benefit with this feature?**

Anyone who wants to add control inputs to their graph. 

**Any Other info.**
It is possible to add control inputs to operations by directly using OperationBuilder like so:
```
  public <T> Operation addOp(String name, Output<T> x, Output<T> y, Operation z) {
    return graph.opBuilder("Add", name)
        .addInput(x).addInput(y).addControlInput(z).build();
  }
```
But definitely would be best to have addControlInput as an option to use with the neat generated classes :) 
 
cc: @samdow @melissagrueter

**Comment by irenedea** [comment]
@sjamesr @karllessard 

Any thoughts regarding this? Thank you!

**Comment by sjamesr** [comment]
Looks good to me, are you going to send a patch? Otherwise I can take care of it.

**Comment by irenedea** [comment]
@sjamesr yup, I'll open a PR soon. Thanks!

**Comment by karllessard** [comment]
Hi @irenedea, sorry in advance for the novel but I think it might worth it to get more into details here,

I think your concern on not having control inputs available in the Ops API is justified. I would be careful though before adding a new `create` factory method inside the wrappers.

The thing is that by design, operation wrapper factories were not meant to be accessed directly by the users. The `org.tensorflow.op.*Ops` classes, which carries the scope along the graph building process, should be used instead. In other words, instead of calling `Add<T> add = Add.create(scope, x, y)`, you should call `Add<T> add = tf.add(x, y)`, where `tf` is an instance of `Ops`.

The `*Ops` classes are also generated at compile time, not by the C++ generator like the wrappers but by an annotation processor, which is triggered by the annotation `@Operator` added to the generated wrappers.  For each factory method found in the wrapper, an endpoint with the name of the operation is added to the `Ops` class. 

Right now, there is in general only one factory per wrapper (and in a few cases, two), so we end up having a single endpoint call `tf.add()` (or `tf.math.add()` depending on the version you are looking to). Adding a new factory into all wrappers will create a second endpoint for all the ops, which leads to double the size of the Ops API namespace. I think we should try to avoid that. 

What should we do, then? A trivial but not aesthetic solution would be to name your new factory with a different name (e.g. `createAfter`) so it is not picked by the annotation processor to generate an endpoint in the API. 

Another solution, better IMHO but more complex to implement, is to chain the control input before the creation of the operation. For example, we can already rename an operation added to a graph by invoking `tf.withName("addThis").add(x.y)`. Why not following the same semantic and having something like `tf.controlledBy(assertOp).add(x,y)`?

If you also find this option interesting, we can work altogether to find out what would be the best way to implement it. What do you think?

**Comment by karllessard** [comment]
In case you were not aware of the existence of the `Ops` classes, here [some examples](https://github.com/karllessard/models/tree/master/samples/languages/java/mnist/src/main/java/org/tensorflow/model/sample/mnist) to show there usage.

**Comment by irenedea** [comment]
Hi @karllessard, thank you for your response; the details are great! I actually had no idea of the existence of the `Ops` classes, so thank you for pointing that out or I would've missed that completely. (Is there documentation on this somewhere?)

I do like the idea of the chain solution. It is definitely much neater than doubling the Ops API :) 

What do you think about this:
- Add `controlInputs` as a member of `scope` that defaults to an empty list.
- Add `withControlDependencies(Iterable<Operand<?>> controls)` method to scope that returns a new scope with new control inputs. 
- Add `controlledBy` method to `Ops`:
```
  public Ops controlledBy(Iterable<Operand<?>> controls) {
    return new Ops(scope.withControlInputs(controls));
  }
```
- Modify factory method to be something like:
```
    public static <T> Add<T> create(Scope scope, Operand<T> x, Operand<T> y) {
        OperationBuilder opBuilder = scope.graph().opBuilder("Add", scope.makeOpName("Add"));
        opBuilder.addInput(x.asOutput());
        opBuilder.addInput(y.asOutput());
       for (Operand<T> ctrl : scope.getControlDependencies()) { opBuilder = operBuilder.addControlInput(ctrl.asOutput().op()) }
        return new Add(opBuilder.build());
    }
```

**Comment by karllessard** [comment]
> Is there documentation on this somewhere?

There is a glitch in current Java documentation on the TF website that prevents to generated classes to appear. I pinged the documentation team about this a few days ago and they said they will take a look at it but it's not on their top-priority list.

To palliate the pain, I wanted to merge my examples (the previous link I provided) to master but there's been another issue in the build system that will prevent the latest TF release (1.13.0) to include changes those examples rely upon.

So right now, the best documentation we have is [this javadoc.](http://javadoc.io/doc/org.tensorflow/libtensorflow/1.13.0-rc2)

> What do you think about this:
> * Add `controlInputs` as a member of `scope` that defaults to an empty list.
> * Add `withControlDependencies(Iterable<Operand<?>> controls)` method to scope that returns a new scope with new control inputs.
> * Add `controlledBy` method to `Ops`:

That sounds perfect. Maybe we should keep the name of the methods consistent between the `Scope` and the `Ops` but any those should fit.

> * Modify factory method to be something like (no more overloaded method):
> 
> ```
>    public static <T> Add<T> create(Scope scope, Operand<T> x, Operand<T> y) {
>        OperationBuilder opBuilder = scope.graph().opBuilder("Add", scope.makeOpName("Add"));
>        opBuilder.addInput(x.asOutput());
>        opBuilder.addInput(y.asOutput());
>       for (Operand<T> ctrl : scope.getControlDependencies()) { opBuilder = operBuilder.addControlInput(ctrl.asOutput().op()) }
>        return new Add(opBuilder.build());
>    }
> ```

Sounds also good! Just an idea like this, maybe the `Scope` instance should be allowed to visit the operation being built so the logic of that `for` loop (or any special need we might face in the future) would be moved to this class instead (which is easier to maintain than changing the C++ op generator).

Something like this?
```
   public static <T> Add<T> create(Scope scope, Operand<T> x, Operand<T> y) {
       OperationBuilder opBuilder = scope.graph().opBuilder("Add", scope.makeOpName("Add"));        
       opBuilder.addInput(x.asOutput());
       opBuilder.addInput(y.asOutput());
       scope.apply(opBuilder);       
       return new Add(opBuilder.build());
   }
```

**Comment by irenedea** [comment]
Thanks for your work on the documentation side of things as well! Hope it gets resolved soon as it would be great to have more documentation and examples with TF Java. (I haven't had much luck finding good usage examples myself.)

> Maybe we should keep the name of the methods consistent between the `Scope` and the `Ops` but any those should fit

Good catch!

> Just an idea like this, maybe the `Scope` instance should be allowed to visit the operation being built so the logic of that `for` loop (or any special need we might face in the future) would be moved to this class instead (which is easier to maintain than changing the C++ op generator).

Agreed, that sounds great.

**Comment by irenedea** [comment]
closed: https://github.com/tensorflow/tensorflow/pull/26181
