### ISSUE TITLE
Feature request: Tensorboard streaming

### ISSUE THREAD

**Issue by SpencerC** [tensorflow/tensorflow#2603]
The new Tensorboard refresh button looks great, and will certainly be a bit more civilized than rapidly swapping the horizontal axis view to update the data. :)

But what if Tensorboard could be optionally updated in real time, whenever a summary writer was flushed? I've written systems before where past data is loaded along with the page, and new data is added continuously via a web socket. Would this work in Tensorboard's current architecture?

If my understanding is correct, Tensorboard currently updates itself every 120 seconds by reading the event files in the log directory. Could Tensorboard also open a local socket and bounce summary updates from a connected Tensorflow process to websocket clients?

I was thinking of hacking a streaming system together on my branch, but I figured I should reach out first to see if this is already in the roadmap. If it isn't, is this feature something you might like to merge if I can get it to work robustly?

**Comment by danmane** [comment]
Hi SpencerC,

I'm currently working on a re-architecutre of the TensorBoard backend that will shift the underlying data pipe to be based on streams of data rather than async loading, with the option to connect TensorBoard directly to the TensorFlow process. Once this is setup, it will be feasible to have realtime updating in TensorBoard. However, it's a very involved change that involves changes to TensorFlow, the TensorBoard backend, and the TensorBoard frontend. So don't expect it to be released in the near future. 

You're welcome to hack a streaming system together, but unless we coordinate closely there's a pretty good chance that our changes will clobber each other.

As a workaround, you can change the frequency with which TensorBoard loads events from the backend by setting `reload_interval` to something much shorter, e.g. tensorboard --reload_interval=2. Then you can click the refresh button and get data much faster (note you should increase the flush frequency on your summary writer too). 

Right now the reload frequency on the frontend is hardcoded to 120secs, I would like to setup a route so that it reads from TensorBoard and reloads as quickly as TensorBoard is reloading. If you feel like contributing that, it's a good candidate for a pull request.

**Comment by SpencerC** [comment]
Sure, I can work on that. I assume it's fine to add a route to handler.py, and the modify the js behaviors in the tf-tensorboard and tf-backend folders?

**Comment by danmane** [comment]
Sorry I disappeared. You're right that adding a route to handler.py and modifying the js behaviors is a good way to go. 

There's no ETA on the broader TensorBoard changes that will switch to streaming.

**Comment by vonclites** [comment]
@SpencerC, anything I can do to help?

**Comment by dominikandreas** [comment]
Any update on this? It seems like a great and obvious improvement to tensorboard

**Comment by dandelionmane** [comment]
Supporting streaming isn't currently on the agenda, so no ETA.
Pinging @jart to take a look.

**Comment by dandelionmane** [comment]
Migrated to tensorflow/tensorboard.
