### ISSUE TITLE
Warn or throw error when calling tf.train.TFRecordDataset([])

### ISSUE THREAD

**Issue by silentsnooc** [tensorflow/tensorflow#26038]
### Issue

I am just here because it took me way to long to get behind this issue as somebody who tried to write `.tfrecord` files and use them in a `TFRecordDataset` for the first time.

I am not sure if this is intended behavior but it turns out that `dataset = tf.data.TFRecordDataset([])` won't bother you until you run the graph in a session but will only give you 

```
OutOfRangeError (see above for traceback): End of sequence
```
As an error. I was thinking about everything else like wrong data types, not enough samples inside the files etc. until I turned out to be a typo in `file_paths` and I realized I was just passing in an empty array.

### Reproduce

```python
import tensorflow as tf


def main():

    dataset = tf.data.TFRecordDataset([])
    iterator = dataset.make_one_shot_iterator()
    get_next = iterator.get_next()

    with tf.Session() as session:
        session.run(tf.global_variables_initializer())
        batch = session.run(get_next)
        print(batch)


if __name__ == '__main__':
    main()
```

### Environment

```
$ pip freeze | grep tensor
tensorboard==1.12.0
tensorflow-gpu==1.12.0

$ uname -svomp
Linux #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 x86_64 GNU/Linux
```

**Comment by mrry** [comment]
Although this is an unlikely path to take at the top level of an input pipeline with a literal empty list, I don't think we can make it an error, because it is a legitimate definition for an empty dataset. For example, the list might be created by a library function that shards up a list of files, and in some cases the individual list assigned to a particular worker might be empty.
