### ISSUE TITLE
winsock2.h

### ISSUE THREAD

**Issue by kerwinxu** [tensorflow/tensorflow#26037]
tensorflow\core\platform\cloud\gcs_dns_cache.cc 文件，i think it should like below 。
#include <winsock2.h>
#include <Windows.h>

**Comment by jvishnuvardhan** [comment]
@kerwinxu Thank you for your post. We noticed you have not filled out the fields in the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. Are you getting the error during installation or during running some code. It would be great if you can provide a small code to reproduce the error. Thanks!
