### ISSUE TITLE
Why is op:BatchMatMul listed in file(.pbtxt), when there is no call to such op?

### ISSUE THREAD

**Issue by vinayonchip** [tensorflow/tensorflow#26076]
There is no usage of op named ***BatchMatMul*** in my code. If the op is not used then why is it listed in the file (.pbtxt)?

Can anyone please help me with this...!

Thanks in advance.

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by vinayonchip** [comment]
Ok @ymodak.
Actually I was guessing it as a miscellaneous issue and used the related template.
I have created a new issue using the Bug template.
https://github.com/tensorflow/tensorflow/issues/26239
