### ISSUE TITLE
bazel-bin transform_graph err, loading graph ..pb failed with can't parse pb file 

### ISSUE THREAD

**Issue by Micy1919** [tensorflow/tensorflow#26139]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by Micy1919** [comment]
![image](https://user-images.githubusercontent.com/16379388/53418747-77c99500-3a13-11e9-968c-8a04a06e15fd.png)

**Comment by jvishnuvardhan** [comment]
@Micy1919 Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket when new information is available. Thanks!
