### ISSUE TITLE
[TF 2.0 API Docs] tf.keras.activations.relu 

### ISSUE THREAD

**Issue by BlackHoundNate** [tensorflow/tensorflow#26211]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version: 2.0
- Doc Link: https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/activations/relu

**Describe the documentation issue**

* The description is minimal, not written with complete sentences, and lacks recommendations of when and when not to use the symbol.

* There is no usage example.

* The parameters are described only briefly and with inconsistent capitalization.

* The returned object description could be more useful.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

Yes.

**Comment by BlackHoundNate** [comment]
I'm terribly sorry, but I can't find the relevant file to work on in the docs repository. I see in CONTRIBUTING.md that "[s]ome projects have their repositories under github.com/tensorflow [and] are navigable from the tensorflow/docs site/en directory," but I can't manage to actually navigate there from the site/en directory. I've tried searching on GitHub, but I can't find it there either.

It is likely that I'm missing something obvious, but I'd be very grateful to be pointed to the repository that contains the activations.relu doc; I'm eager to help with this.

**Comment by dynamicwebpaige** [comment]
@BlackHoundNate - No worries! Files for the docs are often hard to track down. :slightly_smiling_face: 

The part of `activations.py` you'll want to modify for `tf.keras.actions.relu` is located [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/activations.py#L143). Let me know if you run into any snags or confusions when making changes to the docstring! And thanks so much for contributing - we appreciate it. :tada:

**Comment by BlackHoundNate** [comment]
Thanks so much, @dynamicwebpaige!

**Comment by yagyajoshi15** [comment]
Suppose you want to start from your home and drive around your neighborhood and get
back to exactly where you started (your home) and you want this ride to exactly take 10
minutes. Assume that all roads are laid out in a perfect grid. Suppose there is an app that
gives users random paths to drive throughout the city. Every time you press the button, it
gives you a random set of one-letter strings representing the directions to take. For
example, [‘N’, ‘W’, ‘W’, ‘S’, ‘E’] means that go one block to north, two blocks to west,
one block to south and one block to east.
Knowing that it takes you one minute to traverse one city block, create a function that
given a path from the app, will return true if the path will take you exactly ten minutes to
drive and will return you where you started from (home). Return false otherwise.
Note: you will always receive a valid array containing a random assortment of direction
letters ('N', 'S', 'E', or 'W' only). It will never give you an empty array. Some one help me to write program for this in python

**Comment by DeepManuPy** [comment]
please review.
@dynamicwebpaige

**Comment by shegokarm** [comment]
Can I take this issue?

**Comment by pifon2a** [comment]
@yagyajoshi15 we need more of those.

**Comment by Williscool13** [comment]
Will try my hand at this issue

**Comment by rohanreddych** [comment]
I want to take this issue.

**Comment by rohanreddych** [comment]
I made a pull request please review and give feedback

**Comment by nikochiko** [comment]
@Williscool13 's PR has already been merged. This issue should be closed already. 
@BlackHoundNate @dynamicwebpaige

**Comment by dubesar** [comment]
@dynamicwebpaige  Please close this issue as this seems to be already solved.

**Comment by yashk2810** [comment]
Thank you so much. Fixed in nightly: https://www.tensorflow.org/api_docs/python/tf/keras/activations/relu?version=nightly
