### ISSUE TITLE
[TF 2.0] Conversion script fails to parse IPython functions.

### ISSUE THREAD

**Issue by dynamicwebpaige** [tensorflow/tensorflow#26294]
The [`tf_upgrade_v2`](https://github.com/tensorflow/docs/blob/master/site/en/r2/guide/upgrade.md) tool fails to parse commands with common IPython functions (for example, `!pip install tf-nightly` and `%matplotlib inline`).

```
ERROR: Failed to parse.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/tools/compatibility/ast_edits.py", line 510, in update_string_pasta
    t = pasta.parse(text)
  File "/usr/local/lib/python3.6/dist-packages/pasta/__init__.py", line 23, in parse
    t = ast_utils.parse(src)
  File "/usr/local/lib/python3.6/dist-packages/pasta/base/ast_utils.py", line 56, in parse
    tree = ast.parse(sanitize_source(src))
  File "/usr/lib/python3.6/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)
  File "<unknown>", line 37
    !pip install tf-nightly
    ^
SyntaxError: invalid syntax
```

**Comment by kyscg** [comment]
Hi, I would like to work on this issue. Any starting pointers?

**Comment by NikolaMandic** [comment]
would this work https://github.com/tensorflow/tensorflow/pull/26332/files

**Comment by shreyashub** [comment]
Is anyone currently working on this Issue?

**Comment by SunflowerPKU** [comment]
Hi @dynamicwebpaige @kyscg @NikolaMandic @shreyashub  , I am doing a research about "how the labels such as <good first issue> help newcomers to contribute" , but I found many PR were rejected because of duplication or newcomers feel puzzled whether this issue are under processing, especially for popular projects. How do you think of this problem? I wonder whether mechanisms to avoid this problem are needed, for example, in addition to <open> and <closed>, add a new status of issue: <ongoing>.

**Comment by NikolaMandic** [comment]
you like read what people wrote then think
what was last written that is the status
here for example one puts a pull request then people look at that one

**Comment by Amorn-Kingthong** [comment]
let's go

**Comment by lc0** [comment]
@dynamicwebpaige this one should be been fixed for quite a while. Would you mind to close the issue or point us out if you still have any open issues with current nightly.

Thanks!

**Comment by dynamicwebpaige** [comment]
Closing, and thanks to @lc0 for the contribution!
