### ISSUE TITLE
How to retrain with custom object and get frozen_inference.pb model file with Tensorflow.

### ISSUE THREAD

**Issue by NiranjanAntany** [tensorflow/tensorflow#26344]
Hi,

I am working in a project for eye-lid detection. My eye-lid detection is based on landmark points in face. it uses tensor-flow library. i was stuck in a procedure how to retrain the algorithm with new data-set and generate frozen_inference.pb file. I have tried with procedure given in tensor-flow page but i cannot able to get frozen_inference.pb file. Please help me in the procedure how to retrain and get the frozen_inference,pb file.

Kindly do the needful..

Regards,
Niranjan B

**Comment by kunakl07** [comment]
1)In order to train the TensorFlow model, we will need to two files — custom object Model files (.pb) and object names file (.pbtxt)
2)Inorder to train our model, we need to provide it with some training data. In our case, since we want it to detect eye-lid, we need to collect images of various tools. Make sure you collect a ton of images and you can also datasets online for this.
3)Once images are ready, we need to annotate them to describe the object in the image. To do this we can use a powerful graphical annotation tool called labellmg which generates an XML file for you.
4)TensorFlow expects training data as TFRecord file. Inorder to convert the XML file we obtained from labelimg, we first need to convert it to CSV using xml_to_csv.py [link](https://github.com/datitran/raccoon_dataset/blob/master/xml_to_csv.py)
nd then use generate_tfrecord.py [link](https://github.com/datitran/raccoon_dataset/blob/master/generate_tfrecord.py)
to get the TFRecord file.
While using the xml_to_csv.py script, make sure you change path to your images folder and the output csv folder.
Command
image_path = os.path.join(os.getcwd(),’your image path’.format(directory))
xml_df.to_csv(‘your csv folder ’.format(directory), index=None)

Here’s how you use generate_tfrecord.py to convert your CSV to TFRecord.

python generate_tfrecord.py --csv_input=screwdriver_data/train_labels.csv --output_path=screwdriver_data/train.record

To set the object name in TFRecord you can change the generate_tfrecord.py file in this place —

# TO-DO replace this with label map
def class_text_to_int(row_label):
 print(row_label)
 if row_label == ‘Your object name’:
 return 1
 else:
 None

5)Clone the Tensorflow model repository and navigate to the research/object_detection folder and then execute the below commands in this path.

python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/ssd_mobilenet_v1_pets.config
6)All files will create in training folder. You can visualise the training progress by using TensorBoard by executing the below command in object_detection folder—

$ tensorbord --logdir='training'

6)Finally, execute the below command in same path which will generate the model file(.bp) in the specified output folder. You should also use the latest “Trained Checkpoint Prefix” filename which is of the format — model.ckpt-XX in the below command.

python export_inference_graph.py \
 — input_type image_tensor \
 — pipeline_config_path training/ssd_mobilenet_v1_pets.config \
 — trained_checkpoint_prefix training/model.ckpt-XX\
 — output_directory “graphfoldername”

Now your frozen_inference graph is generated and you are ready to rock

**Comment by anujeet98** [comment]
hello Niranjan B,
are you working on tensorflow object detection api?
if so, add the new dataset with the old data, generate csv ,convert it to tfrecord
this command should begin the training process  Eg: python train.py --logtostderr --train_dir=training/ --pipeline_config_path=training/faster_rcnn_resnet101_coco.config

To generate inference graph Eg: python export_inference_graph.py --input_type image_tensor --pipeline_config_path training/faster_rcnn_resnet101_coco.config --trained_checkpoint_prefix training/model.ckpt-10575 --output_directory inference_graph2019

**Comment by NiranjanAntany** [comment]
Hello, 

Thanks for your reply.

i have tried your method with racoon data-set and can successfully able to freeze my variables into frozen_inference_graph.pb.

but after getting the model file i have loaded it into my eye-detection algorithm and tested it..but its showing me the below error
----------------------------------------------------------------------------------------------------------
python Face_estimate_head_pose.py 
Linux is fine! Python multiprocessing works.
2019-03-05 17:59:41.237918: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "Face_estimate_head_pose.py", line 184, in <module>
    main()
  File "Face_estimate_head_pose.py", line 78, in main
    marks = mark_detector.detect_marks(face_img)
  File "/home/user/Desktop/head-pose-estimation-master/mark_detector.py", line 165, in detect_marks
    logits_tensor = self.graph.get_tensor_by_name('logits/BiasAdd:0')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3666, in get_tensor_by_name
    return self.as_graph_element(name, allow_tensor=True, allow_operation=False)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3490, in as_graph_element
    return self._as_graph_element_locked(obj, allow_tensor, allow_operation)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 3532, in _as_graph_element_locked
    "graph." % (repr(name), repr(op_name)))
KeyError: "The name 'logits/BiasAdd:0' refers to a Tensor which does not exist. The operation, 'logits/BiasAdd', does not exist in the graph."
----------------------------------------------------------------------------------------------------------------

Pls find the code it is eyelid detection based on detected land marks in face. it uses landmark annotation method.
 ---------------------------------------------------------------------------------------------------------------
class MarkDetector:
    """Facial landmark detector by Convolutional Neural Network"""

    def __init__(self, mark_model='/home/user/Desktop/eye/raccoon_dataset-master/training/output_inference_graph.pb'):
        """Initialization"""
        # A face detector is required for mark detection.
        self.face_detector = FaceDetector()

        self.cnn_input_size = 128
        self.marks = None

        # Get a TensorFlow session ready to do landmark detection
        # Load a (frozen) Tensorflow model into memory.
        detection_graph = tf.Graph()
        with detection_graph.as_default():
            od_graph_def = tf.GraphDef()
            with tf.gfile.GFile(mark_model, 'rb') as fid:
                serialized_graph = fid.read()
                od_graph_def.ParseFromString(serialized_graph)
                tf.import_graph_def(od_graph_def, name='')
        self.graph = detection_graph
        self.sess = tf.Session(graph=detection_graph)

    @staticmethod
    def draw_box(image, boxes, box_color=(255, 255, 255)):
        """Draw square boxes on image"""
        for box in boxes:
            cv2.rectangle(image,
                          (box[0], box[1]),
                          (box[2], box[3]), box_color)

    @staticmethod
    def move_box(box, offset):
        """Move the box to direction specified by vector offset"""
        left_x = box[0] + offset[0]
        top_y = box[1] + offset[1]
        right_x = box[2] + offset[0]
        bottom_y = box[3] + offset[1]
        return [left_x, top_y, right_x, bottom_y]

    @staticmethod
    def get_square_box(box):
        """Get a square box out of the given box, by expanding it."""
        left_x = box[0]
        top_y = box[1]
        right_x = box[2]
        bottom_y = box[3]

        box_width = right_x - left_x  
        box_height = bottom_y - top_y 

        # Check if box is already a square. If not, make it a square.
        diff = box_height - box_width
        delta = int(abs(diff) / 2)

        if diff == 0:                   # Already a square.
            return box
        elif diff > 0:                  # Height > width, a slim box.
            left_x -= delta
            right_x += delta
            if diff % 2== 1:
                right_x += 1
        else:                           # Width > height, a short box.
            top_y -= delta
            bottom_y += delta
            if diff % 2 == 1:
                bottom_y += 1

        # Make sure box is always square.
        assert ((right_x - left_x) == (bottom_y - top_y)), 'Box is not square.'

        return [left_x, top_y, right_x, bottom_y]

    @staticmethod
    def box_in_image(box, image):
        """Check if the box is in image"""
        rows = image.shape[0]
        cols = image.shape[1]
        return box[0] >= 0 and box[1] >= 0 and box[2] <= cols and box[3] <= rows

    def extract_cnn_facebox(self, image):
        """Extract face area from image."""
        _, raw_boxes = self.face_detector.get_faceboxes(
            image=image, threshold=0.9)

        for box in raw_boxes:
            # Move box down.
            diff_height_width = (box[3] - box[1]) - (box[2] - box[0])
            offset_y = int(abs(diff_height_width / 2))
            box_moved = self.move_box(box, [0, offset_y])

            # Make box square.
            facebox = self.get_square_box(box_moved)

            if self.box_in_image(facebox, image):
                return facebox

        return None

    def detect_marks(self, image_np):
        """Detect marks from image"""
        # Get result tensor by its name.
        logits_tensor = self.graph.get_tensor_by_name('logits/BiasAdd:0')

        # Actual detection.
        predictions = self.sess.run(
            logits_tensor,
            feed_dict={'input_image_tensor:0': image_np})

        # Convert predictions to landmarks.
        marks = np.array(predictions).flatten()
        marks = np.reshape(marks, (-1, 2))

        return marks

    @staticmethod
    def draw_marks(image, marks, color=(255, 255, 255)):
        """Draw mark points on image"""
        for mark in marks:
            cv2.circle(image, (int(mark[0]), int(
mark[1])), 1, color, -1, cv2.LINE_AA)
-----------------------------------------------------------------------------------------------------------------
Am stuck with this issue for past one month..Please help with the procedure how to retrain and get the frozen_inference.pb file for eyelid detection.

Thanks & Regards,
Niranjan B

**Comment by kunakl07** [comment]
@NiranjanAntany Did you feed your annotated images to the model,along with seperate annotation file

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
