### ISSUE TITLE
RAM memory issue in Xavier 

### ISSUE THREAD

**Issue by Niran89** [tensorflow/tensorflow#26359]
Hi,
I am currently working on an application which runs ssd mobilenet based Object detector in Nvidia AGX Xavier Developer kit, which is flashed with Jetpack 4.1. 

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): LINUX UBUNTU 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NO
- TensorFlow installed from (source or binary): pip install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v411 tensorflow-gpu
- TensorFlow version (use command below): 1.13.0
- Python version: 2.7
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: CUDA 10.0/cuDNN 7.3.1.20
- GPU model and memory:Xavier developer kit

The sofware specifications are as follows, 
Ubuntu 18.04
tf = 1.13.0 from pip install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v411 tensorflow-gpu
CUDA 10.0
CUDNN 7.3.1.20

I have noticed that the algorithm is taking around 12GB out of 15.5GB RAM memory available in Xavier.

I have made use of "config = tf.ConfigProto(allow_soft_placement=True, log_device_placement=log_device)" and "config.gpu_options.allow_growth=allow_memory_growth" in the code to control the memory growth. But still I could not see any improvement in the memory allocation.

I have uninstalled tensorflow and installed it again too. But there is no much change.

The same algorithm allocates only about 2-3GB is GPU based Laptop.

Could you help me to make a conclusion on this issue. Are there any more changes to be done specific to xavier for using the split model algorithm you have created ? Also can the split model code be used for mutilple cameras ? 

Thanks in Advance !!!

Regards,
Niran

**Comment by sanjoy** [comment]
@nluehr Can you please help triage this?

**Comment by ark626** [comment]
Yeah the issue might be, that you used (like i did ) Tensorflow and Pytorch together.
If it uses to much RAM you have to limit it manually, to do this, just add those following lines

gpus = tf.config.experimental.list_physical_devices('GPU') tf.config.experimental.set_virtual_device_configuration(gpus[0], [tf.config.experimental.VirtualDeviceConfiguration(memory_limit=CUDARAMINMB)])

CUDARAMINMB Is the CUDA RAM Limit in MB. The two lines above can be placed after the import of Tensorflow.

Also if you use Pytorch and Tensorflow together, tensorflow MUST be imported after Pytorch, otherwise it will fail with some cryptical block error.

**Comment by sanatmpa1** [comment]
@Niran89,

Can you take a look at the above comment and let us know if it helps in resolving your issue.Thanks!
