### ISSUE TITLE
train with MirroredStrategy with multiple gpus has no speed up

### ISSUE THREAD

**Issue by Alex-zhai** [tensorflow/tensorflow#26392]
**System information**
OS Platform and Distribution: CentOS Linux release 7.3.1611
TensorFlow installed from: (pip install tensorflow-gpu)
TensorFlow version: Tensorflow 1.12
Bazel version: N/A
GPU model and memory: Tesla P40 24G
Exact command to reproduce: N/A
Mobile device: N/A
CUDA/cuDNN version: cuda 9.0 with cudnn7.1.4

**Describe the current behavior**
I trained with tensorflow for multi-gpu with MirroredStrategy and estimator. My model is a simple dnn. The layer number is 256->128->64.  when I set bigger batch_size (such as 1024), the training speed using multiple gpus  has no improvement compared with single gpu. As following picture shows:

![image](https://user-images.githubusercontent.com/11607954/53925412-da2d3000-40ba-11e9-994f-1130348d7b67.png)

What I want to ask is that the acceleration performance of MirroredStrategy has associated with the type of model? Is that the complex model like cnn just can have obvious acceleration performance when using multiple gpus?

**Comment by isaprykin** [comment]
You should see <performance of 1 GPU> * <number of GPUs> * 90%-ish percent scaling.  Please check your measurement logic, because it's common to only count the single GPU number.  Please re-open if you think it's still an issue, and if so, please provide more details about your setup.  One other thing you could do is to look at `$ nvidia-smi` during your training to observe the utilization of your GPUs.
