### ISSUE TITLE
tensorflow 1.13.1: module 'tensorflow._api.v1.keras.applications' has no attribute 'resnet'

### ISSUE THREAD

**Issue by keyyuki** [tensorflow/tensorflow#26446]
Hi every one

I have used Google Colab and when use keras resnet, it raise this error: module 'tensorflow._api.v1.keras.applications' has no attribute 'resnet'

my code 

```
import tensorflow as tf
from tensorflow import keras

model = keras.applications.resnet.ResNet50(weights=None,classes=4, input_shape=(150,150,3))
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), 
                loss='binary_crossentropy',
                metrics=['accuracy'])
```

my tensorflow is 1.13.1, as default of google colab

Other keras application like Mobinet, VGG16 still work fine

Thank for you help

**Comment by Ayush517** [comment]
@keyyuki Can you please add this line and try again :
from keras.applications.resnet import ResNet50

Let us know how it proceeds. Thanks :)

**Comment by keyyuki** [comment]
@Ayush517 
```
import tensorflow as tf
from keras.applications.resnet import ResNet50
```
and it said

```
ModuleNotFoundError: No module named 'keras.applications.resnet'
```

**Comment by Ayush517** [comment]
Please try this before import:
!pip install keras --upgrade
!pip install Keras-Applications

**Comment by keyyuki** [comment]
@Ayush517 
I think it keras, not tensorflow.keras
so after install, i run

```
import keras
print(keras.__version__)
```
print
```
2.2.4
```
and continue

```
import keras
from keras.applications.resnet import ResNet50
```

it still error
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-5-d327cd2bb017> in <module>()
      1 import keras
----> 2 from keras.applications.resnet import ResNet50

ModuleNotFoundError: No module named 'keras.applications.resnet'

---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------
```
note that, I run on google colab, GPU, python 3

**Comment by Ayush517** [comment]
import tensorflow as tf
from keras.applications import ResNet50 as ResNet50
from keras.optimizers import Adam as Adam
model = ResNet50(weights=None,classes=4, input_shape=(150,150,3))
model.compile(optimizer=Adam(0.01), loss='binary_crossentropy', metrics=['accuracy'])

This works for me. I am not sure if it's the correct way of doing it or just a hack. Can you please see if your issue is resolved by this.

**Comment by keyyuki** [comment]
ok I see
my code
keras.applications.resnet.ResNet50

and your code
keras.applications.ResNet50

You dont have resnet.ResNet50, and it run. But as document at https://www.tensorflow.org/api_docs/python/tf/keras/applications

they said read at https://github.com/keras-team/keras-applications and read at https://keras.io/applications/

in https://keras.io/applications/#resnet

keras.applications.resnet.ResNet50(include_top=True, weights='imagenet', input_tensor=None, input_shape=None, pooling=None, classes=1000)

so, document of tensorflow.keras is different with keras 

It still issue, but for document, not lib

**Comment by Ayush517** [comment]
Yeah, it's different than the document on their official website. Did the code resolved your issue? Is it working the way you were expecting it to?

**Comment by keyyuki** [comment]
ok, it run now, thank you so much

**Comment by Ayush517** [comment]
Your welcome 😄 
Let us know if face any other issues. You can close this issue now.

**Comment by jvishnuvardhan** [comment]
@keyyuki using tf.keras works as you expected. Just for your information, if you upgrade to TF2.0, try to use tf.keras instead of keras as most of the functionality is still work-in-progress in Keras.

import tensorflow as tf
#from tensorflow import keras

model = tf.keras.applications.resnet50.ResNet50(weights=None,classes=4, input_shape=(150,150,3))
model.compile(optimizer=tf.keras.optimizers.Adam(0.01), 
                loss='binary_crossentropy',
                metrics=['accuracy'])

Regarding document, i don't see any error. Please point out the "document error" if you see any. Website in currently upgrading, and most of the modifications will be available in couple of days. If you see any document error after two weeks, please do PR with the modifications. Thanks!
