### ISSUE TITLE
Allow py_function to support functions that return RaggedTensor

### ISSUE THREAD

**Issue by woodshop** [tensorflow/tensorflow#26453]
**System information**
- TensorFlow version (you are using): 1.13.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
`py_function` only supports functions that return `Tensor`s. However the wrapped function is executed in eager mode and therefore ideally should support other return types consistent with eager mode. As of tf-1.13.1, `py_function` attempts to convert the returned objects to `Tensor`s, but a `RaggedTensor` cannot be converted directly to a `Tensor`. Any attempt to return a `RaggedTensor` raises an exception during the attempted conversion. E.g.,

```python
with tf.Graph().as_default():
    elements = [[1., 2., 3.], [4., 5.]]
    ragged1 = tf.ragged.constant(elements)
    def py_func():
        return tf.ragged.constant(elements)
    
    ragged2 = tf.py_function(
        py_func, [], tf.dtypes.float32
    )
    with tf.Session() as sess:
        print(sess.run(ragged1))
        print(sess.run(ragged2))

>>> <tf.RaggedTensorValue [[1.0, 2.0, 3.0], [4.0, 5.0]]>
>>> ...
>>> ValueError: TypeError: object of type 'RaggedTensor' has no len()
```

I propose that `py_function` detect which output arguments, if any, are `RaggedTensor`s and returns them without attempting to convert to `Tensor`s. If the proposal is rejected, I suggest that the documentation is updated to make clearer (either in the API or guides) that a `RaggedTensor` is not a suitable return type for functions wrapped by `py_function`. 

**Will this change the current api? How?** No.

**Who will benefit with this feature?** Anyone who uses `RaggedTensor` in conjunction with `py_function`.

**Any Other info.**
As a workaround, one can construct a `RaggedTensor` from the output of `py_function`. E.g.,

```python
with tf.Graph().as_default():
    elements = [[1., 2., 3.], [4., 5.]]
    ragged1 = tf.ragged.constant(elements)
    def py_func():
        lengths = [len(element) for element in elements]
        return sum(elements, []), lengths
    
    concatenated, lengths = tf.py_function(
        py_func, [], [tf.dtypes.float32, tf.dtypes.int64]
    )
    ragged2 = tf.RaggedTensor.from_row_lengths(concatenated, lengths)
    with tf.Session() as sess:
        print(sess.run(ragged1))
        print(sess.run(ragged2))

>>> <tf.RaggedTensorValue [[1.0, 2.0, 3.0], [4.0, 5.0]]>
>>> <tf.RaggedTensorValue [[1.0, 2.0, 3.0], [4.0, 5.0]]>
```

**Comment by edloper** [comment]
In https://github.com/tensorflow/tensorflow/issues/27679#issuecomment-522578000, I showed how py_function could be extended to handle composite tensor inputs and outputs (and other nested structures, like dicts, tuples, lists, etc).  If you have bandwidth to work on a PR that adds that to TensorFlow (with tests etc.), then it would be very welcome; otherwise, you could just use the `new_py_function` that I defined there, which wraps `tf.py_function`.

**Comment by JXRiver** [comment]
The issue should have been fixed by @edloper. The following example should work.
```
import tensorflow

# TF1
tf = tensorflow.compat.v1
with tf.Graph().as_default():
    elements = [[1., 2., 3.], [4., 5.]]
    ragged1 = tf.ragged.constant(elements)
    def py_func():
        return tf.ragged.constant(elements)
    
    ragged2 = tf.py_function(
        py_func, [], Tout=tf.RaggedTensorSpec([2, None], tf.float32)
    )
    with tf.Session() as sess:
        print(sess.run(ragged1))  # <tf.RaggedTensorValue [[1.0, 2.0, 3.0], [4.0, 5.0]]>
        print(sess.run(ragged2))  # <tf.RaggedTensorValue [[1.0, 2.0, 3.0], [4.0, 5.0]]>

# TF2
tf = tensorflow.compat.v2
def py_func():
  return tf.ragged.constant([[1., 2., 3.], [4., 5.]])

print(tf.py_function(py_func, [], Tout=tf.RaggedTensorSpec([2, None], tf.float32)))  # <tf.RaggedTensor [[1.0, 2.0, 3.0], [4.0, 5.0]]>
```

Note the main difference of this example with the example in the original issue is the `Tout` argument of `tf.py_function`. When `tf.py_function` returns a `CompositeTensor`, the `Tout` argument should be a subclass of `tf.TypeSpec`, i.e., `tf.RaggedTensorSpec` for a `RaggedTensor`.

See https://www.tensorflow.org/api_docs/python/tf/py_function for more information on `tf.py_function` and https://www.tensorflow.org/api_docs/python/tf/TypeSpec on `tf.TypeSpec`.

**Comment by HuangChiEn** [comment]
> The issue should have been fixed by @edloper. The following example should work.
> 
> ```python
> import tensorflow
> 
> # TF1
> tf = tensorflow.compat.v1
> with tf.Graph().as_default():
>     elements = [[1., 2., 3.], [4., 5.]]
>     ragged1 = tf.ragged.constant(elements)
>     def py_func():
>         return tf.ragged.constant(elements)
>     
>     ragged2 = tf.py_function(
>         py_func, [], Tout=tf.RaggedTensorSpec([2, None], tf.float32)
>     )
>     with tf.Session() as sess:
>         print(sess.run(ragged1))  # <tf.RaggedTensorValue [[1.0, 2.0, 3.0], [4.0, 5.0]]>
>         print(sess.run(ragged2))  # <tf.RaggedTensorValue [[1.0, 2.0, 3.0], [4.0, 5.0]]>
> 
> # TF2
> tf = tensorflow.compat.v2
> def py_func():
>   return tf.ragged.constant([[1., 2., 3.], [4., 5.]])
> 
> print(tf.py_function(py_func, [], Tout=tf.RaggedTensorSpec([2, None], tf.float32)))  # <tf.RaggedTensor [[1.0, 2.0, 3.0], [4.0, 5.0]]>
> ```
> 
> Note the main difference of this example with the example in the original issue is the `Tout` argument of `tf.py_function`. When `tf.py_function` returns a `CompositeTensor`, the `Tout` argument should be a subclass of `tf.TypeSpec`, i.e., `tf.RaggedTensorSpec` for a `RaggedTensor`.
> 
> See https://www.tensorflow.org/api_docs/python/tf/py_function for more information on `tf.py_function` and https://www.tensorflow.org/api_docs/python/tf/TypeSpec on `tf.TypeSpec`.

Thanks for your brief tutorial, but the given code will not work, if I convert it into the lambda function.
![image](https://user-images.githubusercontent.com/52521165/144815600-6c2b84e2-fb2d-4e4d-9a9d-85751a3d59c3.png)

![image](https://user-images.githubusercontent.com/52521165/144815642-0054a429-fa1a-4f3f-9ad4-2bab8e8fc7cc.png)

![image](https://user-images.githubusercontent.com/52521165/144815573-c24bda40-1f4d-4f30-b521-5e1f18741804.png)

look forward to see the further improvement of tf..

**Comment by edloper** [comment]
@HuangChiEn Are you using TensorFlow 2.7?  Support for using composite tensors (such as `RaggedTensor`) with `py_function` was added with 2.7, so if you're using an earlier version of TensorFlow, then it won't work.  I tried executing your code as written:

```python
tmp = lambda _: tf.ragged.constant([[1., 2., 3.], [4., 5.]])
tf.py_function(tmp, [], Tout=tf.RaggedTensorSpec([2, None], tf.float32))
```

And it failed with "`<lambda>() missing 1 required positional argument: '_'`" (which is expected, since your lambda takes one argument, but you didn't supply any arguments when you called `tf.py_function`).  If I change it the `lambda` to not expect any argument:

```python
tmp = lambda: tf.ragged.constant([[1., 2., 3.], [4., 5.]])
tf.py_function(tmp, [], Tout=tf.RaggedTensorSpec([2, None], tf.float32))
```

Then it succeeds for me (in TF 2.7).
