### ISSUE TITLE
where are the conflow flow ops like abort used?

### ISSUE THREAD

**Issue by yongwww** [tensorflow/tensorflow#26455]
Previous, TF control flow primitives are Switch, Merge, Enter, NextIteration, and Exit, we can see them in a simple while_loop graph. Currently, in your r1.13 and r2.0 [docs](https://www.tensorflow.org/versions/r2.0/api_docs/cc/group/control-flow-ops), seems the control flow ops changed a lot, how could I see this ops in a graphdef? are they still in while_loop and cond?

**Comment by yongwww** [comment]
Tried to use while_loop and tf 2.0, the graphdef is still the same as previous tf versions, haven't seen abort, RefNextIteration, RefSelect, RefSwitch. Please help share a simple model example which uses these ops in your new docs.

**Comment by skye** [comment]
FYI, in general, questions like these are best asked on [Stack Overflow](http://stackoverflow.com/questions/tagged/tensorflow), since we GitHub issues to track bugs and features.

The docs you linked to are to the C++ API, which contains many lower-level (and sometimes outdated ops) than the Python API. For example, in TF 2.0, the Python API no longer produces Ref ops. So you won't see all the control flow ops still included in the C++ API when using the Python API.

These resources should help you learn more about control flow in the TF Python API:
New tf.cond doc: https://github.com/tensorflow/community/blob/master/rfcs/20180507-cond-v2.md
New tf.while doc: https://github.com/tensorflow/community/blob/master/rfcs/20180821-differentiable-functional-while.md
Old-style control flow doc (using switch, merge, etc.): http://download.tensorflow.org/paper/white_paper_tf_control_flow_implementation_2017_11_1.pdf

**Comment by yongwww** [comment]
@skye  thanks!
