### ISSUE TITLE
Segfaults due to protobuf -std=c++11 mismatch

### ISSUE THREAD

**Issue by llchan** [tensorflow/tensorflow#2646]
I was seeing segfaults in `std::unordered_map`, and the symptoms looked like potential memory corruption.  Took a fair amount of digging in gdb to figure out that it wasn't that, but was just a build/library version issue:

- tensorflow's embedded protobuf is built with `-std=c++11`
- a default protobuf build is built without `-std=c++11`

I'm not super familar with the details of dlopen and symbol resolution, but the `RTLD_GLOBAL` when it loads `_pywrap_tensorflow.so` might be causing it to shadow the symbols in `libprotobuf.so` (for the cpp-enabled protobuf python package).  The C++11 vs non-C++11 libraries use different headers for `std::unordered_map` (in bits vs tr1), and things blow up when they start using the wrong library's version of the code.  (Correct me if my understanding of RTLD_GLOBAL is wrong and that's irrelevant).

In any case, building protobuf with C++11 fixed the segfaults I was seeing.

Now as for solutions, here are some ideas:
- Allow tensorflow to link to an external libprotobuf.so.  This is probably the best solution, since then only one protobuf library is loaded at runtime, and a version check is probably simple to add.
- If RTLD_GLOBAL is a relevant factor, maybe _pywrap_tensorflow.so can be split up and only the parts that actually need to be global can be global.  Or maybe some gcc attributes to control visibility can do the trick.
- Maybe we can shove the embedded protobuf into a namespace so the symbols don't collide

Possibly useful info to reproduce:
- gcc-4.8.x
- libstdc++.so.6.0.19
- r0.8 branch

I've seen some other people post about similar segfault issues and I suspect many of them might be related to this.

Also now that I've found the issue, it seems obvious in retrospect, and a related issue on the protobuf issues is https://github.com/google/protobuf/issues/839.

**Comment by llchan** [comment]
I should add that I know nothing about bazel so I will need someone involved in the project to help.

**Comment by llchan** [comment]
Seems like #2034 had similar issues with symbol visibility related to `RTLD_GLOBAL`, maybe that can be revisited and tightened up a bit?  We really only want it to make certain things global, and we should be careful what's exposed.

**Comment by aselle** [comment]
Yeah I believe sizeof(std::unordered_map) is different between the c++0x (tr1 version of std library) and --std=c++11. If protobuf and tensorflow are not communicating unordered_maps amongst each other and protobuf functions are not inlined into tensorflow translation units it can be perfectly safe. However, if some of the inlined functions are not inlined and instead turned into exported symbols implicitly, the dso loader will attempt to share one symbol with both libraries which will not work (it will assume the wrong structure layout).  You could attempt to work around this by adding 
-fvisibility-inlines-hidden to tensorflow which will force tensorflow to use its own copies of all inlines that are spilled to function calls. OTOH, if this is due to inlines using a std::unordered_map in a tensorflow translation unit that was allocated in a protobuf translation unit, this will not solve the problem.







-fvisibility-inlines-hidden

**Comment by girving** [comment]
@aselle: To pull an offline comment into the thread, is there a way we could detect the size mismatch (possibly at runtime) and bail with an explanatory error?

**Comment by llchan** [comment]
Hiding inlines might solve one class of problems, but non-inlined functions could also be clobbered.  We really need to either make the two libraries hidden from each other (i.e. remove/restrict RTLD_GLOBAL-ness), or share the same libprotobuf.so.

By far the best solution would be to dynamically link to an existing protobuf library and sprinkle in one or two version checks to make sure the right one is loaded.  Is there any reason not to do this other than the work involved to put it in the bazel build configs?

**Comment by llchan** [comment]
@girving a size check would be a good first line of defense, and would certainly be a good addition until this is ironed out, but the struct could also have different members/layout with the same size so it should only be a temporary solution.

**Comment by llchan** [comment]
I think this may impact the other libraries that are embedded in tensorflow.  Suppose I do this:

1. Import tensorflow, it loads _pywrap_tensorflow.so with RTLD_GLOBAL, libpng symbols are loaded with global visibility
2. Import matplotlib.pyplot, it loads _png.so, which depends on libpng15.so, but when it's linked some of the symbols it needs are globally visible via _pywrap_tensorflow.so so it uses those instead
3. Potential problems?  On my box, I have libpng-1.5.x, but tensorflow embeds libpng-1.2.x.  I don't know the details of the implementation but there could very well be struct changes between those versions.

In an ideal world we'd link to existing libraries whenever possible.  If I had to guess, we are embedding these libraries so we don't need to support the entire universe of different versions people might have installed.  That's fine while TF is still young, but if we're going to do that we really can't have those embedded libraries loaded with global visibility or they will cause problems with libraries loaded the normal way.

**Comment by keveman** [comment]
@llchan With respect to libpng and other libraries embedded in `_pywrap_tensorflow.so`, look [here](https://github.com/tensorflow/tensorflow/blob/9078909131d5e91e8bd1878eac54136885656043/tensorflow/tensorflow.bzl#L651). The linker scripts strictly control the symbols exported by `_pywrap_tensorflow.so`. Even though the library is loaded with `RTLD_GLOBAL`, only tensorflow related symbols are available in the global address space.

**Comment by llchan** [comment]
Ah my bad, I was building TF 0.8 so I had the r0.8 branch checked out.  Should have checked out master, looks like the exported symbols list was added after r0.8.  I'll try a r0.9 build.

**Comment by aselle** [comment]
Sorry for the late reply. It's difficult to do this in general, because you'd need to put something in a translation unit for every project that might have possibly been compiled differently that you can query later. I.e. something already has to be compiled that remembers the size or that it is c++11. I don't really know enough about the toolchain to know if the compiler dumps something we could reliably use to determine if a c++11 or c++0x standard library was used. We could roll our own, but it seems difficult to control. It is best to avoid std::unordered_map being part of a systems API to avoid most times you would hit this, at least until c++0x tr stuff is put to bed.

**Comment by llchan** [comment]
@keveman 0.9 is much, much better about symbol visibility, the libpng symbols I saw before in 0.8 are no longer global, and poking around in gdb, I now see symbols coming from the right place.  Thanks, for pointing me to the right place to look!

@aselle Yeah, youre right, it sounds like it'd be a pain to check c++11 vs c++0x for every dependency, and it's unclear if theres enough information as-is to determine that at runtime.  I think the stuff about restricting global symbols should address my concerns though.

For anyone else reading, try r0.9 released a day or two ago, the issues related to shared libraries may not exist anymore.

**Comment by keveman** [comment]
@llchan Thanks for your comments. I am closing this issue as there seems to be no outstanding action items. Feel free to open the issue if you feel that it has not been sufficiently addressed.
