### ISSUE TITLE
Android TFLite benchmark performance issue with deeplab segmentation model (DepthwiseConv2d)

### ISSUE THREAD

**Issue by anilsathyan7** [tensorflow/tensorflow#26474]
**System information**
The benchmark tests were carried out using the following tools and devices:-
Bazel version:Build label: 0.23.1
Tensorflow Version: 1.13.0
Android Device: OnePlus 3

**Describe the current behavior**
We trained a segmentation model using deeplab with mobilenet with TF 1.13.0 to replicate the
segmentation model by tensorflow i.e 'deeplabv3_257_mv_gpu.tflite'(Using sample code  in repo for pascal voc).
However there was significant time difference for average running time for 'DepthwiseConv2d', when we benchmarked the two tflite models with 'tflite android benchmark tool'.
In the official model avg time was around 28 ms; whereas in our own model it was around 103 ms.
The only difference between the two float models being the quantization levels i.e Ours was 0-255
and official model has -1 to 0.99.Also, there is a difference in model size(Official:2.7Mb vs. Ours:3.3Mb).

It seems the official model is using a newer kernel for depthwiseconv2d and hence runs significantly faster compared to our trained model.Was the official model trained or optimised using TF2.0 tools?What could be done to achieve similar speed (DepthwiseConv2d) using TF 1.13.0 or do we have to migrate and retrain our model using TF 2.0?

**Describe the expected behavior**
The depthwise conv2d performance should be same in the official model and the replicated model.

**Code to reproduce the issue**
Benchmark commands:-

```
# bazel build -c opt   --config=android_arm64   --cxxopt='--std=c++11' --copt=-DTFLITE_PROFILING_ENABLED tensorflow/lite/tools/benchmark:benchmark_model

# adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/deeplabv3_257_mv_gpu.tflite --num_threads=1
```

Benchmark results:-

_Official model:-_

```
Number of nodes executed: 70
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	                 CONV_2D	       38	   137.792	    76.447%	    76.447%	     0.000	       38
	       DEPTHWISE_CONV_2D	       17	    27.808	    15.428%	    91.875%	     0.000	       17
	         RESIZE_BILINEAR	        3	    13.577	     7.533%	    99.408%	     0.000	        3
	           CONCATENATION	        1	     0.528	     0.293%	    99.701%	     0.000	        1
	                     ADD	       10	     0.410	     0.227%	    99.928%	     0.000	       10
	         AVERAGE_POOL_2D	        1	     0.129	     0.072%	   100.000%	     0.000	        1

Timings (microseconds): count=50 first=180683 curr=179967 min=177601 max=186179 avg=180284 std=1486
Memory (bytes): count=0
70 nodes observe
```

_Replicated model:-_

```
Number of nodes executed: 70
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	                 CONV_2D	       38	   141.189	    54.356%	    54.356%	     0.000	       38
	       DEPTHWISE_CONV_2D	       17	   103.263	    39.755%	    94.110%	     0.000	       17
	         RESIZE_BILINEAR	        3	    14.178	     5.458%	    99.568%	     0.000	        3
	           CONCATENATION	        1	     0.554	     0.213%	    99.782%	     0.000	        1
	                     ADD	       10	     0.437	     0.168%	    99.950%	     0.000	       10
	         AVERAGE_POOL_2D	        1	     0.130	     0.050%	   100.000%	     0.000	        1

Timings (microseconds): count=50 first=258703 curr=259361 min=255581 max=269627 avg=259789 std=3844
Memory (bytes): count=0
70 nodes observed
```

**Other info / logs**

However using TF-12.0 with Bazel 0.16.0, the 'benchmark_model' built failed for 'official model'; but worked with replicated model.

Bazel build:-

```
# bazel build -c opt   --config=android_arm64   --cxxopt='--std=c++11' --linkopt='-llog' --copt=-DTFLITE_PROFILING_ENABLED tensorflow/contrib/lite/tools/benchmark:benchmark_model

# adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/deeplabv3_257_mv_gpu.tflite --num_threads=1
```

TF-Lite benchmark:-

adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/deeplabv3_257_mv_gpu.tflite --num_threads=1
adb: /opt/intel/intelpython27/lib/libcrypto.so.1.0.0: no version information available (required by adb)
STARTING!
Num runs: [50]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Warmup runs: [1]
Graph: [/data/local/tmp/deeplabv3_257_mv_gpu.tflite]
Input layers: []
Input shapes: []
Use nnapi : [0]
nnapi error: unable to open library libneuralnetworks.so
Loaded model /data/local/tmp/deeplabv3_257_mv_gpu.tflite
resolved reporter
Didn't find op for builtin opcode 'DEPTHWISE_CONV_2D' version '2'

Registration failed.

Failed to construct interpreter
Aborted

Can you provide the corresponding optimised pb file before tflite conversion, for the same model ?

**Comment by shashishekhar** [comment]
@anilsathyan7 : 
Version 2 of [Depthwiseconv2d](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/toco/tflite/operator.cc#L177) :
is used when dilation width and height factors are equal to 1.
This doesn't have to do anything with TF 2.0. Adding @jianlijianli  who can give a definitive answer.

**Comment by anilsathyan7** [comment]
It looks like the dilation_w_factor and dilation_h_factor in the official model for depthwiseconv2d  are not equal to 1 everywhere.Initially it is 1 for couple of depthwiseconv2d layers, then it becomes 2 and finally it is 4 for last few depthwiseconv2d layers. This seems to be the difference between both models (replicated model has dilation width and height factors equal to one in all the nodes in network).This also seems to make the avg execution time for deothwiseonv2d in official model smaller.How can we configure the dilation width and height factors separately for each nodes  during deeplabv3+ training?

**Comment by Roger8** [comment]
mine failed too, have no idea,  need help. 
```
File "/usr/local/python3/lib/python3.5/site-packages/tensorflow/contrib/lite/python/interpreter.py", line 53, in __init__
    model_path))
ValueError: Didn't find op for builtin opcode 'CONV_2D' version '2'
Registration failed.
```

**Comment by SanthoshRajendiran** [comment]
We tried benchmarking the tflite obtained from official deeplab repository, with depthwise conv2d Version 2. The dilation_w_factor and dilation_h_factor for deeplab is set as 1, by default. The tflite from the output of the graph transform model, seemed to provide no speed difference as we believe graph transformation (Flatten_atrous_conv), has affected the speed improvement by DepthwiseConv2d Version 2. The direct output from the optimize for inference, was giving speedup in the Depthwise Conv2d V2, but when trying to run it on the mobile GPU, it increased the time of execution, since it had operators like SpacetoBatchND and BatchtoSpaceND, which are not optimized for GPU processing. Is there any way, we can remove the spacetobatch and batchtospace nodes from the optimized graph, so as to obtain the speed gain by Depthwise Conv2d Version2 on android GPU... Tried doing the remove_nodes graph transform on the optimized graph, but it did not remove the nodes..

Attached with here, are the commands, benchmarks and tflite files..

**Benchmark Results: (Oneplus 3)**

**1.Without Batch2Space**

Command & Result:-

`adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/withoutbatchtospace.tflite --num_threads=1`
adb: /opt/intel/intelpython27/lib/libcrypto.so.1.0.0: no version information available (required by adb)
STARTING!
Num runs: [50]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Warmup runs: [1]
Graph: [/data/local/tmp/withoutbatchtospace.tflite]
Input layers: []
Input shapes: []
Use nnapi : [0]
nnapi error: unable to open library libneuralnetworks.so
Loaded model /data/local/tmp/withoutbatchtospace.tflite
resolved reporter
Initialized session in 7.374ms
Running benchmark for 1 iterations 
count=1 curr=248072

Running benchmark for 50 iterations 
count=50 first=243147 curr=234508 min=234107 max=245867 avg=237050 std=3526


Number of nodes executed: 70
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	                 CONV_2D	       38	   128.807	    54.361%	    54.361%	     0.000	       38
	       DEPTHWISE_CONV_2D	       17	    90.016	    37.990%	    92.351%	     0.000	       17
	         RESIZE_BILINEAR	        3	    17.095	     7.215%	    99.566%	     0.000	        3
	           CONCATENATION	        1	     0.505	     0.213%	    99.779%	     0.000	        1
	                     ADD	       10	     0.401	     0.169%	    99.949%	     0.000	       10
	         AVERAGE_POOL_2D	        1	     0.122	     0.051%	   100.000%	     0.000	        1

Timings (microseconds): count=50 first=243080 curr=234449 min=234036 max=245808 avg=236985 std=3526
Memory (bytes): count=0
70 nodes observed

Average inference timings in us: Warmup: 248072, Init: 7374, no stats: 237050


**2.With Batch2Space**

Command & Result:-

`adb shell /data/local/tmp/benchmark_model --graph=/data/local/tmp/withbatchtospace.tflite --num_threads=1`
adb: /opt/intel/intelpython27/lib/libcrypto.so.1.0.0: no version information available (required by adb)
STARTING!
Num runs: [50]
Inter-run delay (seconds): [-1]
Num threads: [1]
Benchmark name: []
Output prefix: []
Warmup runs: [1]
Graph: [/data/local/tmp/withbatchtospace.tflite]
Input layers: []
Input shapes: []
Use nnapi : [0]
nnapi error: unable to open library libneuralnetworks.so
Loaded model /data/local/tmp/withbatchtospace.tflite
resolved reporter
Initialized session in 6.757ms
Running benchmark for 1 iterations 
count=1 curr=207830

Running benchmark for 50 iterations 
count=50 first=197780 curr=196627 min=195049 max=200776 avg=196418 std=1165


Number of nodes executed: 110
============================== Summary by node type ==============================
	             [Node type]	  [count]	  [avg ms]	    [avg %]	    [cdf %]	  [mem KB]	[times called]
	                 CONV_2D	       38	   129.772	    66.131%	    66.131%	     0.000	       38
	       DEPTHWISE_CONV_2D	       17	    30.027	    15.302%	    81.432%	     0.000	       17
	         RESIZE_BILINEAR	        3	    17.773	     9.057%	    90.489%	     0.000	        3
	                     MUL	       10	     8.193	     4.175%	    94.665%	     0.000	       10
	       SPACE_TO_BATCH_ND	       10	     3.707	     1.889%	    96.554%	     0.000	       10
	                     ADD	       20	     3.707	     1.889%	    98.443%	     0.000	       20
	       BATCH_TO_SPACE_ND	       10	     2.446	     1.246%	    99.689%	     0.000	       10
	           CONCATENATION	        1	     0.492	     0.251%	    99.940%	     0.000	        1
	         AVERAGE_POOL_2D	        1	     0.118	     0.060%	   100.000%	     0.000	        1

Timings (microseconds): count=50 first=197577 curr=196500 min=194929 max=200638 avg=196286 std=1161
Memory (bytes): count=0
110 nodes observed


Average inference timings in us: Warmup: 207830, Init: 6757, no stats: 196418

**Optimize for inference** 
`bazel-bin/tensorflow/python/tools/optimize_for_inference --input=frozen.pb --output=stripped.pb --frozen_graph=True --input_names="sub_2" --output_names="ResizeBilinear_2"`

**Graph Transforms**
`bazel-bin/tensorflow/tools/graph_transforms/transform_graph --in_graph="stripped.pb" --out_graph="flatten.pb"  --inputs='sub_2' --outputs='ResizeBilinear_2' --transforms='flatten_atrous_conv'`

**TFLite Conversion** 

`CUDA_VISIBLE_DEVICES="0" tflite_convert --graph_def_file="flatten.pb" --output_file="withoutbatchtospace.tflite" --output_format=TFLITE --input_format=TENSORFLOW_GRAPHDEF --input_arrays="sub_2" --output_arrays="ResizeBilinear_2" --input_shapes=1,257,257,3
`

`
CUDA_VISIBLE_DEVICES="0" tflite_convert --graph_def_file="stripped.pb" --output_file="withbatchtospace.tflite" --output_format=TFLITE --input_format=TENSORFLOW_GRAPHDEF --input_arrays="sub_2" --output_arrays="ResizeBilinear_2" --input_shapes=1,257,257,3
`
[tf_depthwise_conv2d_v2.zip](https://github.com/tensorflow/tensorflow/files/2990941/tf_depthwise_conv2d_v2.zip)

**Comment by ilous12** [comment]
Hi @shashishekhar, I'm deeplearning new and I have questions.
Are you change the input type from "uint8" to "float32"?

**export_model.py**
```
input_image = tf.placeholder(tf.uint8, [1, None, None, 3], name=_INPUT_NAME)
input_image = tf.placeholder(tf.float32, [1, None, None, 3], name=_INPUT_NAME)
```

I saw your tflite files. What do you do weights & bias from '32' to '16'?

<img width="246" alt="Screen Shot 2019-03-21 at 8 58 51 PM" src="https://user-images.githubusercontent.com/3174693/54750847-6d6a7780-4c1c-11e9-82ad-478320161663.png">

**Comment by anilsathyan7** [comment]
Hi @ilous12, those frozen graph and tflite files will have depth multiplier 0.5 in this case...

**Comment by SanthoshRajendiran** [comment]
> @anilsathyan7 :
> Version 2 of [Depthwiseconv2d](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/toco/tflite/operator.cc#L177) :
> is used when dilation width and height factors are equal to 1.
> This doesn't have to do anything with TF 2.0. Adding @jianlijianli who can give a definitive answer.

@jianlijianli @shashishekhar  The code snippet referred, states that version2 of depthwiseconv2d will be used, when either of dilation_width_factor or dilation_height_factor is not equal to 1. This is exactly opposite what was written above. 

@jianlijianli How to set dilation height and width when using Mobilenet-v2 architecture to take advantage of Depthwiseconv2d version 2?

**Comment by ilous12** [comment]
@anilsathyan7 thanks your help. I succeeded by following you. 

One more question.
I don't why my NHWC is "1x17x17x96" and "deeplabv3_257_mv_gpu.tflite"'s NHWC is "1x17x17x96" on MobilenetV2/expanded_conv_6. You will see an image below.

<img width="1546" alt="스크린샷 2019-03-22 오후 8 01 33" src="https://user-images.githubusercontent.com/3174693/54818973-e1b91f80-4cdd-11e9-9992-cf4f277e3d9d.png">

**Comment by anilsathyan7** [comment]
The following seems to be the major differences between the official model and our replicated model:-
Deptwiseconv2d dilation factors, its corresponding weight dimensions and the input bias id (i.e no batc2spaceND_bias):-

![compare](https://user-images.githubusercontent.com/1130185/55138564-c9bc2280-5159-11e9-9d3a-2c21571caf05.png)

How can we fix it? Should we use some different training settings or can we fix it while tflite conversion?
@ilous12  are you having similar issues?If so, did you manage to resolve the same?

**Comment by lwu025** [comment]
Similar issue here. Does anyone replicated model without BATCH_TO_SPACE?

**Comment by bhavints** [comment]
Any updates on this?

**Comment by jsolves** [comment]
Any luck getting ride of those pesty BATCH_TO_SPACE?

**Comment by zhuyan288** [comment]
I have the same issue,  can anyone help us and give a definite answer?thanks.

**Comment by lwu025** [comment]
@zhuyan288  @jsolves 
I think tflite_convert in 1.15 can do the conversion directly.

**Comment by anilsathyan7** [comment]
Latest tf-nightly and tf1.15 seems to solve this problem ; but tf-nightly sometimes creates new nodes that may not be supported by gpu-delegate.Other option is to use transform graph tool (with corresponding tf version & bazel) with flatten atrous conv option. This seems to work for spacetobatch/batchtospace issue for depthwise or diated convolutions in general.
