### ISSUE TITLE
FailedPreconditionError 

### ISSUE THREAD

**Issue by chayan18** [tensorflow/tensorflow#26511]
Please help me out 

FailedPreconditionError                   Traceback (most recent call last)
<ipython-input-27-72245a7797cb> in <module>()
      6     #session.run(adapt_policy_mean, feed_dict=rl.feed_dict)
      7     sess = tf.Session()
----> 8     sess.run(adapt_policy_mean, feed_dict=rl.feed_dict)

/home/ayan/slearn/venv/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
