### ISSUE TITLE
refuse﻿ find example 

### ISSUE THREAD

**Issue by fix27** [tensorflow/tensorflow#26548]
add example learning TensorFlow 2.0 to comment type of warning ecology place. Sample https://photos.google.com/search/battery https://photos.google.com/search/refuse﻿

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
