### ISSUE TITLE
Max Pooling NCHW

### ISSUE THREAD

**Issue by zplizzi** [tensorflow/tensorflow#2660]
In the documentation for the tf.nn.max_pool() op, it is written: 

`data_format: A string. 'NHWC' and 'NCHW' are supported.`

However, when I specify 'NCHW' as the data format, I receive the error "Default MaxPoolingOp only supports NHWC" (generated [here](https://github.com/tensorflow/tensorflow/blob/3488ac22f156cbcfd27c242ccbdac58679385ddc/tensorflow/core/kernels/pooling_ops_common.h#L83) in master when this was written). 

It was my understanding that most ops have been ported to NCHW to support CuDNN natively - so I was surprised to see this wasn't implemented.

**Comment by girving** [comment]
@vrv: Can you take a look?  At best, the error message isn't very explanatory.

**Comment by vrv** [comment]
I talked to @zheng-xq: NCHW is supported only for GPU (because we call cudnn), we do not have an implementation for CPU.

I'm not sure how to correct the documentation though -- the data_format strings indicate the potentially supported formats, not the actually supported ones :(.

To reiterate:

MaxPool on GPU supports NCHW and NHWC
MaxPool on CPU only supports NHWC.

If you have a concrete suggestion for how I should change the documentation, please let me know and I'll be happy to make the improvement!

**Comment by girving** [comment]
@vrv: Maybe just add "(on device %s)" to the error message so that we know which device it isn't supported on?

**Comment by zplizzi** [comment]
Yep I think that would help a lot - the error message seemed to imply that NCHW wasn't supported at all, vs only not being supported on CPU.

**Comment by botev** [comment]
So, this is quite inconsistent with the suggestions of using NCHW for the gpu, due to cudnn. Can we just have MaxPooling actually work with NCHW on the CPU as well? At the moment we literally can not test our code on a CPU for dev because of this issue...

**Comment by wj1066** [comment]
This Documentation [TensorFlow* Optimizations on Modern Intel® Architecture](https://software.intel.com/en-us/articles/tensorflow-optimizations-on-modern-intel-architecture), says "Data format: we suggest that users can specify the NCHW format for their specific neural network model to get maximum performance. TensorFlow default NHWC format is not the most efficient data layout for CPU and it results in some additional conversion overhead."
Due to the MKL in version 1.2, is this necessary to fix this issues?
@lakshayg

**Comment by suiyuan2009** [comment]
I received this error message that didn't say device info, still `Default MaxPoolingOp only supports NHWC`. The error doesn't always occur when I run [tensorflow benchmark code](https://github.com/tensorflow/benchmarks/blob/master/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py). The placer put this op on `cpu:0`, maybe because I set `allow_soft_placement` as true.

**Comment by suiyuan2009** [comment]
I find one worker got `failed call to cuInit: CUDA_ERROR_NOT_INITIALIZED` error so it's not tensorflow code problem.
