### ISSUE TITLE
Dependency on absl_py needs to be updated for compatibility with Bazel version >= 0.25

### ISSUE THREAD

**Issue by brandjon** [tensorflow/tensorflow#26616]
In Bazel 0.23,

```
bazel build --nobuild //tensorflow/tools/pip_package:build_pip_package --incompatible_remove_old_python_version_api
```

has a breakage in `@absl_py`. I submitted an upstream fix that should appear on github today, with a release occurring tomorrow. When that lands, [workspace.bzl](https://github.com/tensorflow/tensorflow/blob/a4c589d5c754493c86f10cc71022fe38d184001a/tensorflow/workspace.bzl#L323-L336) will need to be updated to reference the new abseil-py release.

The fix relies on a feature introduced in Bazel 0.22. The incompatible change flag should be flipped in Bazel 0.25, at which point versions of TF without this fix will break by default.

For more info see bazelbuild/bazel#7308.

**Comment by gunan** [comment]
I do not have cycles to get to this quickly, but I am happy to review a PR.

@meteorcloudy recently bumped our max bazel version requirement to 0.23.2, I thought we had TF tested with that bazel version. Looks like without this change TF wont build with bazel 0.23.2. Yun, should we revert the max bazel version in TF?

**Comment by meteorcloudy** [comment]
@gunan, TensorFlow does build with Bazel 0.23.2, this is tested on Bazel CI.
https://buildkite.com/bazel/tensorflow/builds/2384

@brandjon is reporting a breaking change in future Bazel version. This breaking change can be enabled in 0.23.2 with `--incompatible_remove_old_python_version_api` so that you can test.

As the incompatibility comes from a dependency, TF can just upgrade `@absl_py` when a new release comes out. We don't have to revert the max bazel version in TF.

**Comment by brandjon** [comment]
Right, this change is to ensure TensorFlow works with 0.25 onward. But because the fix to the dependency uses a feature introduced in 0.22, this probably means that the minimum version needs to be bumped to 0.22.

The release of the dependency just went through, so I'll make a PR updating TF's use of it and the min bazel version.
