### ISSUE TITLE
DetectNet alternative

### ISSUE THREAD

**Issue by up-to-you** [tensorflow/tensorflow#26623]
Are there any common alternatives (in tensorflow ecosystem) to Nvidia DetectNet network (object detection), 
which use bbox layer?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
