### ISSUE TITLE
Nasnet models don't support custom image sizes even if include_top is set to False

### ISSUE THREAD

**Issue by dipanjanS** [tensorflow/tensorflow#26639]
The general idea for fine-tuning pre-trained models with a custom image size is to set the `include_top` parameter to `False` when loading the models. However it doesn't seem to be working with the Nasnet models in `tf.keras` so far. All other models including Inception are working fine.

__Note:__ I was using tensorflow 2.0 alpha so I'm not sure if that is the problem.

I believe maybe some issue somewhere in checking dimension size along with the `include_top` flag but I might be wrong.

Following is the stack trace.

```

Code executed:
nasnet = tf.keras.applications.nasnet.NASNetLarge(include_top=False, weights='imagenet', 
                                                                                  input_shape=(100, 100, 3))

Error Message:
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-100-64f6d45dc54d> in <module>
      1 nasnet = tf.keras.applications.nasnet.NASNetLarge(include_top=False, weights='imagenet', 
----> 2                                                                                 input_shape=(100, 100, 3))
      3 nasnet.summary()

/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/applications/__init__.py in wrapper(*args, **kwargs)
     68       kwargs['models'] = models
     69       kwargs['utils'] = utils
---> 70     return base_fun(*args, **kwargs)
     71   return wrapper
     72 

/opt/anaconda3/lib/python3.6/site-packages/tensorflow/python/keras/applications/nasnet.py in NASNetLarge(*args, **kwargs)
     37 @keras_modules_injection
     38 def NASNetLarge(*args, **kwargs):
---> 39   return nasnet.NASNetLarge(*args, **kwargs)
     40 
     41 

/opt/anaconda3/lib/python3.6/site-packages/keras_applications/nasnet.py in NASNetLarge(input_shape, include_top, weights, input_tensor, pooling, classes, **kwargs)
    364                   classes=classes,
    365                   default_size=331,
--> 366                   **kwargs)
    367 
    368 

/opt/anaconda3/lib/python3.6/site-packages/keras_applications/nasnet.py in NASNet(input_shape, penultimate_filters, num_blocks, stem_block_filters, skip_reduction, filter_multiplier, include_top, weights, input_tensor, pooling, classes, default_size, **kwargs)
    166                                       data_format=backend.image_data_format(),
    167                                       require_flatten=True,
--> 168                                       weights=weights)
    169 
    170     if backend.image_data_format() != 'channels_last':

/opt/anaconda3/lib/python3.6/site-packages/keras_applications/imagenet_utils.py in _obtain_input_shape(input_shape, default_size, min_size, data_format, require_flatten, weights)
    290                                  'and loading `imagenet` weights, '
    291                                  '`input_shape` should be ' +
--> 292                                  str(default_shape) + '.')
    293         return default_shape
    294     if input_shape:

ValueError: When setting `include_top=True` and loading `imagenet` weights, `input_shape` should be (331, 331, 3).
```

**Comment by jvishnuvardhan** [comment]
@dipanjanS Could you provide a code to reproduce the bug? Thanks!

**Comment by dipanjanS** [comment]
Hi, it's mentioned in the previous comment, reposting here again separately.

```
nasnet = tf.keras.applications.nasnet.NASNetLarge(include_top=False, weights='imagenet', 
                                                  input_shape=(100, 100, 3))
```

**Comment by qlzh727** [comment]
Adding Francois who is the owner Keras overall.

**Comment by akiroselin** [comment]
Same question

**Comment by dipanjanS** [comment]
@fchollet any idea on this aspect?

**Comment by akiroselin** [comment]
I need to wrote weights=None, then the training runs successfully.

**Comment by dipanjanS** [comment]
That is just random initialization of weights, the whole point of using this is to do transfer learning with pre-trained weights obtained from imagenet. Using `weights=None` defeats the purpose of doing that. That's the same like building your own CNN and copying the layers from Nasnet.

**Comment by akiroselin** [comment]
I understand.but then you see in practice, nasnet was requiring fixed image size after loading imagenet.whats the solution to that besides dumping imagenet?-------- Original Message --------Subject: Re: [tensorflow/tensorflow] Nasnet models don't support custom image sizes even if include_top is set to False (#26639)From: Dipanjan Sarkar To: tensorflow/tensorflow CC: Kirosealin ,Manual That is just random initialization of weights, the whole point of using this is to do transfer learning with pre-trained weights obtained from imagenet. Using weights=None defeats the purpose of doing that. That's the same like building your own CNN and copying the layers from Nasnet.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/tensorflow/tensorflow/issues/26639?email_source=notifications\u0026email_token=AFSLRD4TMTZWQ2OWYGGW2V3PWKC4RA5CNFSM4G5RM342YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVYP2CY#issuecomment-493944075",
"url": "https://github.com/tensorflow/tensorflow/issues/26639?email_source=notifications\u0026email_token=AFSLRD4TMTZWQ2OWYGGW2V3PWKC4RA5CNFSM4G5RM342YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVYP2CY#issuecomment-493944075",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by dipanjanS** [comment]
fixing the API so it is consistent with the other pre-trained models I guess?

**Comment by vvsotnikov** [comment]
The problem is not with the TensorFlow itself, but with the `keras_applications` module. The reason for such behavior of NASNet is described [here](https://github.com/keras-team/keras-applications/pull/62). So it's more likely a bug than a feature, however, I think that documentation should be updated.

**Comment by rilott** [comment]
I just ran into this, agree the documentation should be updated - both the tensorflow and keras documentation say that you should be able to set input_shape to something other than (331,331,3).

**Comment by ymodak** [comment]
The documentation for loading weights with correct input_shape has been updated. Thanks!
