### ISSUE TITLE
 Filter out empty strings as post processing

### ISSUE THREAD

**Issue by lhendre** [tensorflow/tensorflow#26638]
Let users filter out empty strings as post-processing if they do want to.
Re indices and shapes, the right answer is to have proper ragged and sparse tensor support to tf.boolean_mask.

This is a follow up to issue #26368 . and PR #26475 .

**Comment by lhendre** [comment]
@alextp

**Comment by alextp** [comment]
@edloper do you have any pointers as to how to implement boolean_mask support for RaggedTensor?

**Comment by lhendre** [comment]
Has there been any movement?

**Comment by edloper** [comment]
Sorry I’ve been out sick for the past few days.

It’s already implemented. See:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/ragged/ragged_array_ops.py

But it’s not exported yet (via delegation) because the API doesn’t exactly
match the existing boolean_mask op.  In particular it has a new keepdims
argument.

I would like to modify the existing boolean_mask op to add a keepdims arg
(defaulting to false) and to delegate to this if keepdims is true.

-Edward

**Comment by lhendre** [comment]
Is this something that you would want help on?

**Comment by alextp** [comment]
@lhendre I'd happily review a pull request with this change. Do you think you have enough information to open one?

**Comment by lhendre** [comment]
Let me do a little digging and work over the day and Ill get back here with questions

**Comment by lhendre** [comment]
I had some personal things come up over the last two weeks, but this week is looking better to dig into this

**Comment by lhendre** [comment]
I have started working on this and have some stuff down but I want to clarify and make sure I am on the right path.
The existing boolean mask I am modifying to add a keepdims arg(defaulting to false) and to delegate to the ragged ops is here right?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/array_ops.py
I am a little less familiar with this portion of the code and wanted to check first?  Additionally the ragged function does make a callback to this so I am unsure of it or is their a higher level location?  @alextp and @edloper

**Comment by lhendre** [comment]
Checking in real quick @edloper, I want to make sure this is the correct approach.

**Comment by edloper** [comment]
Yes, you'll need to make changes to the boolean_mask function in array_ops.py.  However, looking at this a little closer, we might have some issues with circular dependencies that make this more of a pain to do than it would otherwise be.  If you can figure out a good way around the circular dependencies, I'm happy to look at a PR; otherwise, I'll try to look at this sometime in the next couple weeks to see what I can do.

**Comment by edloper** [comment]
I think we will refactor the code a little to make this circular dependency go away.  So it's probably easiest to hold off on this until we do that.

**Comment by lhendre** [comment]
Its been a while and thought I'd circle back and see if there have been any updates?

**Comment by edloper** [comment]
Sorry for not updating this thread.  In PR 1366762 I added a "tf.ragged.boolean_mask" op, which preserves the masked dimensions.  (We decided that it was better to add this as a separate op, rather than adding an option to the existing tf.boolean_mask op.)

**Comment by lhendre** [comment]
No Problem, thanks for the update!
