### ISSUE TITLE
what does USE_EIGEN_TENSOR used?

### ISSUE THREAD

**Issue by deepllz** [tensorflow/tensorflow#26661]
There are some  USE_EIGEN_TENSOR macros, What does it used for?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
