### ISSUE TITLE
Multipose outputs

### ISSUE THREAD

**Issue by death14stroke** [tensorflow/tensorflow#26667]
**System information**
- TensorFlow version: tf-lite
- Doc Link: https://www.tensorflow.org/lite/models/pose_estimation/overview
https://medium.com/tensorflow/real-time-human-pose-estimation-in-the-browser-with-tensorflow-js-7dd0bc881cd5

**By using the getOutputTensors function in tflite interpreter, I can get that there are 4 output arrays with dimension of  1*23*17*17, 1*23*17*34, 1*23*17*64 and 1*23*17*1. However in the tflite medium article or website, the usage of full output is not explained. How can I get the pose coordinates in the image? In the heatmap array, I am getting very low confidence scores close to 0.00 for every pixel. Here is what I have tried : https://stackoverflow.com/questions/55136861/how-to-use-outputs-of-posenet-model-in-tflite**

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue? - No**

**Comment by tafsiri** [comment]
@jvishnuvardhan You may have been thinking of someone else. I don't work on tflite.

**Comment by Death14Stroke** [comment]
Any progress?

**Comment by tgpsantos** [comment]
Hey! I have the same problem (Model used was multi_person_mobilenet_v1_075_float.tflite). Additionally tried to run it in python using the interpreter without success

**Comment by shaqian** [comment]
I wrote a post about PoseNet on iOS and Android. Hope it helps. 
https://medium.com/flutter-community/posenet-for-ios-android-and-flutter-using-tensorflow-lite-836788a110c7

**Comment by nerdaliciousCH** [comment]
Same issue here. Downloaded the starter model from the [tflite page](https://www.tensorflow.org/lite/models/pose_estimation/overview) as referenced as well in [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/models/pose_estimation/overview.md) markdown file and its output formats and names don't match anything mentioned in any docs.

If you load the tflite model into [Netron](https://lutzroeder.github.io/netron/), you will see that the outputs are also named differently (heatmaps, short offset, mid offset, segment) instead of (heatmaps, offsets, displacement forward, displacement backwards).

Could it be that this was a prematurely uploaded version of PoseNet v2?

Cheers

**Comment by Saduf2019** [comment]
@death14stroke 
Could you please confirm if this is still an issue.
