### ISSUE TITLE
Error: unexpected EOF from Bazel server

### ISSUE THREAD

**Issue by MaeThird** [tensorflow/tensorflow#2668]
==> tensorflow : r0.9   bazel : 0.2.3  gcc:6.1.1  python: 3.5
When i try to compile tensorflow from source on my archlinux(kernel : 4.5.4-1) ,errror occured. Something like " Linking tensorflow/cc/ops/data_flow_ops_gen_cc [for host]
Error: nexpected EOF from Bazel server."

**Comment by MaeThird** [comment]
And when i tried again ,i got the same error but in compile file "tensorflow/core/common_runtime/simple_graph_execution_state.cc" . Maybe there is a bug in GCC-6.1.1 ?? How can I change the default compiler ? Thanks

**Comment by girving** [comment]
This seems like a bazel issue, unfortunately.  @damienmg: Do you have any ideas?

**Comment by damienmg** [comment]
Copy-paste of my answer on bazel-discuss to another similar issue:
"This means that something has killed Bazel during its run. I saw this behavior on some system where the memory of the OS was reaching the limit and the OOM killer was always choosing Bazel because it was the most memory consuming process."

**Comment by girving** [comment]
Thanks @damienmg!  Closing since it is not a TensorFlow issue.
