### ISSUE TITLE
Collision with built in python "logging" module

### ISSUE THREAD

**Issue by skku-dhkim** [tensorflow/tensorflow#26691]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): mac OS Mojave
- TensorFlow installed from (source or binary): pip 
- TensorFlow version (use command below): 2.0.0 alpha-0
- Python version: 3.7.2

**Describe the current behavior**
When using Python internal "logging" module with Tensorflow, a logging module emits below warning message.

> WARNING: Logging before flag parsing goes to stderr.

Also, it prints out duplicate logging message with my own formatter and something internally defined format(I guess) as below.

> $ python3 test.py 
[INFO|test.py:29] 2019-03-14 17:30:14,402 >> Hello World.
WARNING: Logging before flag parsing goes to stderr.
I0314 17:30:14.402168 4528047552 test.py:29] Hello World.
[INFO|test.py:30] 2019-03-14 17:30:14,402 >> This is message 1
I0314 17:30:14.402369 4528047552 test.py:30] This is message 1

When I try without importing Tensorflow, then it works properly.

> $ python3 test.py 
[INFO|test.py:29] 2019-03-14 17:37:40,172 >> Hello World.
[INFO|test.py:30] 2019-03-14 17:37:40,172 >> This is message 1

**Describe the expected behavior**
Maybe stream handler is colliding each other.

**Code to reproduce the issue**
```
import logging
import tensorflow as tf

formatter = logging.Formatter('[%(levelname)s|%(filename)s:%(lineno)s] %(asctime)s >> %(message)s')

stream_logger = logging.getLogger('logger_stream')
stream_logger.setLevel(logging.INFO)

# Set handler
streamHandler = logging.StreamHandler()
streamHandler.setFormatter(formatter)
stream_logger.addHandler(streamHandler)

stream_logger.info("Hello World")
stream_logger.info("This is message 1")
```

**Comment by vrv** [comment]
Adding @caisq who I think might have more familiarity with this code (I haven't really touched the logger code myself).

**Comment by pesser** [comment]
I ran into the same issue with 1.14rc1. I think this is caused by abseil instead of tensorflow: abseil/abseil-py#99

Workaround: https://github.com/dhalperi/pybatfish/blob/f8ddd3938148f9a5d9c14c371a099802c564fac3/pybatfish/client/capirca.py#L33-L50

**Comment by revan** [comment]
@pesser is right, this is due to absl logging upstream.

If possible, I'd recommend using the absl logger instead: https://github.com/abseil/abseil-py/blob/master/absl/logging/__init__.py
The absl logger installs itself in place of the default logger, so for the most part you can continue to use the regular logger.info(), etc. functions. Some configuration can be done directly in the module.

Example of setting a custom format using absl logger for @skku-dhkim 's case:
```
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> import tensorflow as tf
>>> import absl.logging
>>> formatter = logging.Formatter('[%(levelname)s|%(filename)s:%(lineno)s] %(asctime)s >> %(message)s')
>>> absl.logging.get_absl_handler().setFormatter(formatter)
>>> stream_logger = logging.getLogger('logger_stream')
>>> stream_logger.setLevel(logging.INFO)
>>> stream_logger.info("Hello World")
WARNING: Logging before flag parsing goes to stderr.
[INFO|<stdin>:1] 2019-07-01 13:37:51,808 >> Hello World
```

If you're really set on using the default logger, you can use the mentioned workaround to disable absl logging.

Example (@eldar 's case from #29842):
```
Python 2.7.16 (default, Apr  6 2019, 01:42:57) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import logging
>>> import tensorflow as tf
>>> import absl.logging
>>> logging.root.removeHandler(absl.logging._absl_handler)
>>> absl.logging._warn_preinit_stderr = False
>>> logging.basicConfig(filename='log.txt', filemode='w', datefmt='%Y-%m-%d %H:%M:%S', level=logging.INFO, format='%(asctime)-15s %(message)s')
>>> logging.info('logs to file, as expected')
```

```
$  cat log.txt
2019-07-01 13:24:40 logs to file, as expected
```

Closing this issue as it's a (mostly intentional) change in behavior -- please follow up on the abseil-py repo if you have concerns about upstream.

**Comment by KristianHolsheimer** [comment]
Breaking native logging was intended? Let me see if I understand this correctly. If I want my codebase to be compatible with tensorflow, my choice to either change all my loggers or to change all my loggers?

I'm a bit surprised by this outcome, to be honest. Are you sure this is the direction you want to go?

I was under the impression that Tensorflow was more than an experimentation tool, it's supposed to be robust enough to embed into production code. To have to do a refactor (like changing all my loggers) each time I update doesn't exactly fit into that picture.

**Comment by revan** [comment]
Hi Kristian,
Perhaps I misspoke: the intentional change here was the decision to adopt absl, in place of the forked versions of several core libraries that TensorFlow had been maintaining. The move to absl.app pulled in absl.logging, which seems to have some unfortunately complicated interactions with existing user logging.
Ideally, this behavior would be fixed upstream in the abseil-py repo (as you can see by abseil/abseil-py#99, we're not the only ones bothered).
I suppose we could give a shot at bundling the removeHandler() workaround directly into TensorFlow, though -- reopening while I play with this.

**Comment by KristianHolsheimer** [comment]
Ah great thanks so much @revan

**Comment by harahu** [comment]
@revan I really appreciate your understanding in this matter. The default logging library is in common use in the python eco system, and certain best practices are associated with it. One of them is that libraries shouldn't make decisions on how how to handle log items on behalf of developers. Quoting [Logging HOWTO](https://docs.python.org/3/howto/logging.html#configuring-logging-for-a-library):

> **Note:** It is strongly advised that you _do not add any handlers other than `NullHandler` to your library’s loggers_. This is because the configuration of handlers is the prerogative of the application developer who uses your library. The application developer knows their target audience and what handlers are most appropriate for their application: if you add handlers ‘under the hood’, you might well interfere with their ability to carry out unit tests and deliver logs which suit their requirements.

I also use the logging library and was surprised and confused upon upgrading to TF 1.14.

**Comment by revan** [comment]
Update: I've got *some* sort of patch that appears to fix this, but it involves risky looking logic running in the `__init__.py` so I'm really hoping we can fix this upstream instead.
My concern with including the removeHandler workaround in our own import is that now we break anyone who intends to use absl.logging: since absl.logging installs itself at import time, subsequent imports won't reenable it. We can hack around this by deleting absl.logging from `sys.modules` to force a reimport, but this brings us solidly into Python's "don't do this" territory.

Anyway, if we fix it here it wouldn't be out until the next TensorFlow release, so I'm afraid the workarounds noted earlier are the way to go for now.

**Comment by KristianHolsheimer** [comment]
Thanks for looking into it @revan. Yeah, it's the tampering of global state by absl combined with the fact that things will start to rely on this tampering that makes it so tricky.

I really hope that https://github.com/abseil/abseil-py/issues/99 will be properly addressed.

**Comment by KristianHolsheimer** [comment]
Thanks for the follow-up @revan

**Comment by skku-dhkim** [comment]
It works properly now. Thanks 👍

**Comment by drevicko** [comment]
One possible workaround, so long as you don't need your logger to propogate, is to set `propogate` on your logger to `False`:

`my_logger.propogate = False`
