### ISSUE TITLE
tflite GPU only support  one batch input?if not,how can I set my mult-dim inputs like [16,256,256,3]

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#26730]
here is my log in java:
java.lang.IllegalArgumentException: Internal error: Failed to apply delegate: GpuDelegate Prepare: First dimension is supposed to be BATCH and always equal to 1.Node number 19 (GpuDelegate) failed to prepare.

**Comment by impjdi** [comment]
@sunzhe09 

Thanks for trying out the GPU delegate.  Unfortunately, batching was not fully supported at the time of building the dev preview.  Since the release of the dev preview, we made some progress in that direction and you will most likely be able to use the batch dimension in our open source release.

**Comment by impjdi** [comment]
@sunzhe09 

You might be able to use batch > 1 if you set `dynamic_batching_enabled` to `1`.  That applies to C++ interface though.  I don't think we did the plumbing for Java API side yet...

**Comment by sunzhe09** [comment]
Thx！
