### ISSUE TITLE
The contents of Transfer learning tutorial and its github source are not the same.

### ISSUE THREAD

**Issue by wongongv** [tensorflow/tensorflow#26824]
https://www.tensorflow.org/alpha/tutorials/images/transfer_learning
This is the tutorial for transfer learning for tensorflow 2.0
but if you click on run on colab or view source on github buttons,
then the contents are not the same 
(colab link : https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning.ipynb
github link :
https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning.ipynb
)

which one is the latest one and which one I should follow?

Thank you in advance!

**Comment by Ayush517** [comment]
@wongongv Isn't the tutorial same on both the links?

**Comment by shaolinkhoa** [comment]
@wongongv  is correct.
Both colab link and github link are wrong. The current link is not for tensorflow 2.0
They should direct to this link: https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/images/transfer_learning.ipynb

**Comment by lamberta** [comment]
Thanks.
These links have been fixed upstream: https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/images/transfer_learning.ipynb
And will be reflected on the website when the next site publish happens.

If you're learning, I'd go with the alpha/r2 docs (though some of them are still in alpha condition)

**Comment by shaolinkhoa** [comment]
Hi, @lamberta  
I would like to know if the website team have a plan to check all the link on TF2 tutorial or not?
Because I just found another case in ["Load images with tf.data"](https://www.tensorflow.org/alpha/tutorials/load_data/images) and ["Using TFRecords and tf.Example"](https://www.tensorflow.org/alpha/tutorials/load_data/tf_records). 
They should link to https://github.com/tensorflow/docs/tree/master/site/en/r2/tutorials/load_data 
I know that TF team are all busy so I just want to remind.
Regards.
