### ISSUE TITLE
Saving and Restoring SingularMoniteredSession in tensorflow 1.4.1

### ISSUE THREAD

**Issue by prabhant** [tensorflow/tensorflow#26829]
I want to save and restore a SingularMoniteredSession in my code 

```
with g.as_default():
    .......
    with tf.train.SingularMoniteredSession() as sess:
        child_ops = .......
        sess.run(child_ops)
        controller_ops=..........
        sess.run(controller_ops)
```
I want to save and restore the controller ops session here(second session). but i wasn't able to find any documentation regarding it.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
