### ISSUE TITLE
Tensorflow 2.0: please do not deprecate important functions!!!

### ISSUE THREAD

**Issue by chwang85** [tensorflow/tensorflow#26844]
According to Tensorflow 2.0, many important functions are deprecated, such as:
tf.layers.dense()
tf.layers.dropout()
tf.layers.flatten()
tf.layers.batch_normalization()
...
Since these functions are very widely used, and also very helpful for building complicted models, would you please keep them in the future versions?

**Comment by galeone** [comment]
You have to use `tf.keras.layers` instead of `tf.layers` to build the models.

**Comment by chwang85** [comment]
there is no dense(), dropout(), etc. to use, no matter keras or layers

**Comment by galeone** [comment]
You have to use the functional version of the layers in Keras. There are no `dropout`, `dense` and so on layers, because there are the keras layers that you can instantiate and then call:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/layers

For example:

`tf.layers.dropout` becomes `tf.keras.layers.Dropout(rate)(input)`

**Comment by mandroid6** [comment]
Yup, @galeone is right.. TensorFlow is trying to standardize on tf.keras as the direction of general model building.

@chwang85 Also checkout https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/nn/dropout

**Comment by chwang85** [comment]
Sorry, I am not asking for "how to write a TF program".
I believe it is ridiculous to deprecate these functional layers. 
Keeping them in TF 2.0 is not a burden, and compatible with TF 1.x, why do you insist in deprecating them?

**Comment by mihaimaruseac** [comment]
"Deprecated" means they are still there but will go away on a subsequent release (that is, in 2.0).

So, you can still use them in TF 1.x, but they won't be available in TF 2.x and later. The deprecated message is just to notify you and give you time to update.

Closing this and the duplicated #26151 and #26144

**Comment by chwang85** [comment]
Why not deprecate tf.Session()?

**Comment by mihaimaruseac** [comment]
It goes away too

**Comment by chwang85** [comment]
In TF 1.13, when tf.layers.dense() is used, there is a "deprecate" warning, but tf.Session() is OK.
By the way, I think it would be better if the difference between TF 1.x and TF 2.x is like that between Python 2.x and Python 3.x

**Comment by mihaimaruseac** [comment]
`tf.session` will be deprecated later, after the community switches to using TF2.x. Until then, it will still be available for some scenarios, since TF2.x has a very abrupt change in the way TF code is executed (from graph mode to eager mode; `tf.session` is needed for graph mode even in TF2.x).

`tf.layers.dense` has a 100% functional equivalent. It has been there for a long time and the decision to deprecate it and favor the object oriented approach has been taken a long time ago. There is no reason to keep both available, so that's why you get this warning. Please understand that APIs change and the design choice has been taken a very long time ago and now it is too late to go back. That ship has sailed for too long.

**Comment by chwang85** [comment]
This decision is not reasonable at all, because the new components, tf.keras.layers, still has a lot of problems in combining with other tf components...
tf.keras.layers even does not support variable scope, see #27016 for example

**Comment by galeone** [comment]
To share variables using Keras layers you have to build a Keras Model - is a different way of organizing the code and to think.

Once you built the model you have to reuse the **object**. Hence don't share variables using scopes, but share variables using the `model.trainable_variables` attribute.

While I was migrating my codebase to TF2 I faced your same issues and I wrote a blog post about this: https://pgaleone.eu/tensorflow/keras/2019/01/19/keras-not-yet-interface-to-tensorflow/

I also wrote a second article about how to migrate the models from tf1 to tf2, while still using tf1: https://pgaleone.eu/tensorflow/gan/2018/11/04/tensorflow-2-models-migration-and-new-design/
(therefore there are still sessions that in tf2 are going to be removed)

In practice, TF2 requires to re-learn how to use the framework if you're used to working with the static graph + session execution.

**Comment by chwang85** [comment]
thanks
i have noticed that the change between TF 1.x and TF 2.x is too big to simply modify tf.layers to tf.keras.lyaers
instead, it requiress a totally different way of thinking and designing...
i will stick on the graph + session ways

**Comment by chwang85** [comment]
By the way, before deprecating old components, would you please complete the current functionality? See #27042. It seems that TF is very good at deprecating widely used functions, but poor at improving its weak points

**Comment by OgnjenTanovic** [comment]
Can someone explain me. If I need to use  tf.keras.layers instead of tf.layers to build the models, and tf.keras.model.compile to build graph, and tf.keras.model.fit to train instead tf.graph and tf.Session.
Then why I need Tensorflow at all? Maybe I should simply use Keras?

@mihaimaruseac @galeone @mandroid6 @ry

**Comment by mandroid6** [comment]
Keras is a high level API for TensorFlow, which will be able to solve most
of the model building and training needs. Still it isn't an exhaustive API
which has all basic ops available in TensorFlow.

Most importantly Keras uses TensorFlow for building the acyclic graphs or
now the eager execution context.

All tf.keras.layers or tf.keras.model uses TensorFlow in the backend. You
can very well still directly use the low level TF ops, but why to when you
have a more simple abstraction available.

**Comment by chwang85** [comment]
When will you deprecate keras?
When will you deprecate Tensorflow?
When will you deprecate Google?

**Comment by leimao** [comment]
TensorFlow is giving up a lot of its unique features. As a TensorFlow user since 2015, I feel very sorry about that. Keras should never take the place of TensorFlow.

**Comment by czgdp1807** [comment]
I was just working on https://github.com/sympy/sympy/pull/17103 and was curious to find why deprecation has been done. I googled and reached this issue.
So, well many of my doubts are clear, but using, `tf.compat.v1.Session` instead of `tf.Session` is not clear(Is this related to namespace?), I will investigate more on this, though if any one can provide an answer on this, then it will be really helpful.

PS - BTW, if the end result for `tf.layers` and `tf.keras.layers` is same, then I think its a one line change,
Create an alias for use, `tf = tf.keras` and most of the effort for changes can be avoided. This trick can be included somewhere in the README or warnings, probably you might have done that. Well that's just a suggestion, it can be immature, and many of you might have thought it. 

Thanks for reading.

**Comment by czgdp1807** [comment]
I was just working on adapting to some deprecation warnings and was curious to find why deprecation has been done. I googled and reached this issue.
So, well many of my doubts are clear, but using, `tf.compat.v1.Session` instead of `tf.Session` is not clear(Is this related to namespace?), I will investigate more on this, though if any one can provide an answer on this, then it will be really helpful.

PS - BTW, if the end result for `tf.layers` and `tf.keras.layers` is same, then I think its a one line change,
Create an alias for use, `tf = tf.keras` and most of the effort for changes can be avoided. This trick can be included somewhere in the README or warnings, probably you might have done that. Well that's just a suggestion, it can be immature, and many of you might have thought it. 

Edit - Found https://www.tensorflow.org/beta/guide/migration_guide, nice guide. Though tf.Session -> tf.compat.v1.Session is not clear.
Thanks for reading.

**Comment by mihaimaruseac** [comment]
Regarding `tf.Session`: TF 2.0 is eager by default, in that world `Session` is useless. It is being moved to `compat.v1` to have some backward compatibility: instead of requiring you to rewrite your entire script immediately you can just change an import (or use a script to rename `tf.Session` into `tf.compat.v1.Session`) and then rewrite at your convenience (though, at one point you should rewrite).

Regarding `tf.layers`: `tf` top level namespace was too huge, making autocomplete and human understanding very hard. We decided to split it into components.

Note that doing `tf = tf.keras` will result into issues `tf.math.sin` will be `tf.keras.math.sin` which will result in `AttributeError: Module 'keras' has no attribute 'math'`.

**Comment by czgdp1807** [comment]
@mihaimaruseac Thank you for the clarification. In fact, I read [this proposal](https://github.com/tensorflow/community/blob/b1d83bf2ee3fc72650140b89656e29932db36226/rfcs/20180918-functions-not-sessions-20.md), many of my doubts are clear. I would say, it's a very good idea to migrate from `Sessions` -> `Functions`. Though I am not familiar with the terminology but examples in the proposal made the issue very clear.

> It is being moved to `compat.v1` to have some backward compatibility: instead of requiring you to rewrite your entire script immediately you can just change an import (or use a script to rename `tf.Session` into `tf.compat.v1.Session`) and then rewrite at your convenience (though, at one point you should rewrite).

Ah! I was thinking of that. So, are there any plans to remove `compat` somewhere in future? 



> Note that doing `tf = tf.keras` will result into issues `tf.math.sin` will be `tf.keras.math.sin` which will result in `AttributeError: Module 'keras' has no attribute 'math'`.

I see, doing, `tf = tf.keras` is really very immature, well I came across an automation script to make the code compatible with tensorflow 2.0 in   https://www.tensorflow.org/beta/guide/migration_guide.

**Comment by leimao** [comment]
What is the future of frozen graph? Currently there is no way to freeze a graph in TF2.0. Will it be supported in the near future?

**Comment by mihaimaruseac** [comment]
@czgdp1807 Yes, at one point (probably nearing TF 3.0 but don't quote me on that as I might be wrong w.r.t timeline) `compat.v1` will be removed

The migration guide is really useful and recommended

@leimao I suggest opening a new issue to discuss that, I have no idea to be honest and if there's a new issue an owner of that part of the code can respond. Thanks

**Comment by czgdp1807** [comment]
@mihaimaruseac I expect that release of tf 3.0 is not very near, right? I expect it at least after 1 year and I hope that no concrete alternative is in the pipeline for `compat.v1`, if there is, then please let me know, so that I can make updates to my sympy PR to keep that part of the code base stable for a longterm.

**Comment by mihaimaruseac** [comment]
Yes, TF 3.0 is going to be far in the future. There are no plans for it at the moment (we still have to actually make a release for TF 2.0, we are currently in beta)

**Comment by DollarAkshay** [comment]
I think the problem here is that people have no clue how to use `tf.keras.layers.Dense` without building a Keras model.

Even the official document for [tf.keras.layers.Dense](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense) has only examples using the Keras model. So naturally, people see this and wonder "_How do I add the inputs?_" They come to the conclusion that `tf.keras.layers.Dense` cannot be used with pure TensorFlow and then start using `tf.layers.dense`

If we could add examples of how to use `tf.keras.layers.Dense` with pure TensorFlow this would solve the issue. I am guessing the general expression is :

```
output = tf.keras.layers.<LAYER_TYPE>(size, activation, ...)(inputs)
```

**Comment by PiotrDabkowski** [comment]
The solution to this problem:
Switch to PyTorch, you will not regret it.
`torch.nn.Linear` has been there since the v0 and continues to work ever since.
With TF there have been tf.nn, tf.slim, tf.contrib, tf.layers, tf.keras, I wonder what next... Every year they announce a new, final API...

Unless your company forces you to use TF there is no real reason to stay. Really.

**Comment by sbrl** [comment]
How does this affect Tensorflow.js?
