### ISSUE TITLE
Process finished with exit code -1073741819 (0xC0000005)

### ISSUE THREAD

**Issue by bglee85** [tensorflow/tensorflow#26853]
This is my simple coding:-

<em>import tensorflow as tf
print("Hi");</em>

**output**
Process finished with exit code -1073741819 (0xC0000005)

The "Hi" is not printed. I searched online for this issue, but seems like none of the people has this, so it has been bugging me for few days.

No GPU involved, just the CPU version of tensorflow.

I tried v1.13, v1.12, v1.11, and v.1.10, all gave the me the same issue.
I tried with python 3.5.*, 3.6.*, and 3.7.*, also same result.
Tried with LiClipse, PyCharm, Atom, all gave the same result as well.

Windows 10 x64.

It works before, but suddenly one day it didn't work anymore, so I have no idea what happen.
Tried to uninstall any apps that installed within few weeks, but didn't solve the issue.

I really wish someone can help me to solve this issue.

**Comment by ziruizhuang** [comment]
The same thing goes here. I have tried to install tensorflow through pip and tensorflow_mkl with conda. Another installation on a different machine which uses a GPU version tensorflow works just fine. Tried to remove and reinstall python environment to avoid any possible dependency issue, not working.

Since 0xC0000005 often comes from DLL importing issue on Windows, I checked the event log of Windows, the error comes from python.exe obviously, and the error module is unknown(which should be the dll name if any). The error report info goes as follows,
```
Fault bucket 1638171688499684297, type 5
Event Name: BEX64
Response: Not available
Cab Id: 0

Problem signature:
P1: python.exe
P2: 3.7.2150.1013
P3: 5c6f3612
P4: StackHash_ac46
P5: 0.0.0.0
P6: 00000000
P7: PCH_F0_FROM_ntdll+0x00000000000A01C4
P8: c0000005
P9: 0000000000000008
P10: 
```

I checked that the CPU is Core i7-4790 which has AVX2 capability, so that it shouldn'd be a problem about AVX right?

**Comment by ziruizhuang** [comment]
Also it worth mentioning that a custom py37-win-x64 build on branch r1.13 with cherry-pick https://github.com/tensorflow/tensorflow/commit/ec727016282383aacf9d26386b01f6bdbd65b14b by VS2017 also facing the same problem. I haven't had time to build a cpu version on the other computer, so it is unclear whether the issue is related to code or the environment (either system or python).

**Comment by jvishnuvardhan** [comment]
@bglee85 Could you uninstall python and tensorflow, restart system and install python and tensorflow following these [instructions](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12). This procedure is for installing TF1.12 but you can follow similar procedure to install higher version of TF. Please let me know how it progresses. Thanks!

**Comment by bglee85** [comment]
I was quite urgent to use the tensorflow-gpu, so I reset my windows and reinstall everything. It works with the following conditions:-

CUDA 10.0, cudnn 7.5, python-3.6.8, tensorflow & tensorflow-gpu 1.13.1
Windows 10, i9, GTX 1050 Ti

I wish there is a better way to solve the issue without resetting the windows, but I didn't have time to try other options one by one.

** On side note, I did try with CUDA 9.0 (installation failed), CUDA 9.2 (works fine with tensorflow 1.12 but didn't work with tensorflow-gpu 1.12, I think is the graphic driver is higher version) and CUDA 10.1 (fine with CUDA 9.2, but works with tensorflow-1.13.1, not 1.12). All associated with the respective cudnn-7.5.

** Also, I ran the deviceQuery.exe, and the result came back with CUDA Driver Version = 10.1, CUDA Runtime = 10.0, so I tried to install the CUDA 10.1 Runtime instead, but it didn't work on python-3.6.8, I haven't try with python 3.7.2 yet.

Hope this help.

**Comment by jvishnuvardhan** [comment]
@bglee85 when you have time, please write simple step by step instructions that could help the community who have similar problems like you had earlier. Thanks!

**Comment by bglee85** [comment]
@jvishnuvardhan, technically I didn't solve the problem, I just reset my windows and reinstall everything. Anyway here is the step after factory reset the windows.

1) Install CUDA 10.0
2) Copy cudnn into CUDA/v10.0 folder
- you can check out whether your GPU is working with CUDA running at Anaconda prompt deviceQuery.exe at "UDA/v10.0/extras/demo_suite/deviceQuery.exe"
- you also can test out the bandwidth by running bandwidthTest.exe in the same folder.
3) Install tensorflow at Anaconda prompt: pip install tensorflow (use tensorflow==xxx if you want specific version, e.g., tensorflow==1.12)
4) Install tensorflow-gpu at Anaconda prompt: pip install tensorflow-gpu (similar to tensorflow if you want specific version, e.g., tensorflow-gpu==1.12)

Technically, this doesn't solve the issue of 0xC0000005 as I just factory reset my windows.

**Comment by 1RandoPerson** [comment]
Have you moved your files around in any way, like separate the application from the rest of the files. I moved the files back and the problem was solved.
