### ISSUE TITLE
"tensorflow/core/framework/attr_value.pb.h"

### ISSUE THREAD

**Issue by laiqb** [tensorflow/tensorflow#26925]
<em>Please make sure that this is a documentation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:doc_template</em>

**System information**
- TensorFlow version:
- Doc Link:

**Describe the documentation issue**
in "tensorflow/core/framework/function.h" file inclued "tensorflow/core/framework/attr_value.pb.h" file, but i can not find the file. please tell me where is the dir("tensorflow/core/framework/attr_value.pb.h"). thanks

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**

**Comment by mihaimaruseac** [comment]
It is autogenerated from the protocol buffers

**Comment by jvishnuvardhan** [comment]
@laiqb I had it in one of my virtual environment /usr/local/google/home/vishnuvardhanj/venv/lib/python3.6/site-packages/tensorflow/include/tensorflow/core/framework.

If there is any issue, please fill issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=00-bug-performance-issue.md) so that we can resolve it as soon as possible. If this is not related to bug or build installation issue, then close here and post it in stackoverflow. Thanks!

**Comment by laiqb** [comment]
@mihaimaruseac how to autogenerate the file. thanks
