### ISSUE TITLE
OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by essalahsouad** [tensorflow/tensorflow#26952]
**I know that my question isn't nothing to do with tensorflow but i'll appreciate any help**
when i was trying to prepare voc dataset for training pre trained model i got this error

> OSError: libcudart.so.9.0: cannot open shared object file: No such file or directory

`from gluoncv.data import VOCDetection
class VOCLike(VOCDetection):
    CLASSES = ['iris']
    def __init__(self, root, splits, transform=None, index_map=None, preload_label=True):
        super(VOCLike, self).__init__(root, splits, transform, index_map, preload_label)
dataset = VOCLike(root='/home/dell/Bureau/myDataset', splits=((2019, 'train'),))
print(dataset[0])`
**Knowing that I can't use cuda or gpu because i haven't a graphic card nvidia**

**Comment by jvishnuvardhan** [comment]
@essalahsouad I think some function in your code is forcing to use GPU. which is why it was searching for CUDA9.0 related files and throws error as there is no GPU and no CUDA files. Could you run a simple cpu based model and check whether there is any bug. Please check there are lots of community support on stackoverflow. Thanks!

**Comment by essalahsouad** [comment]
@jvishnuvardhan 
thank you for your reply

**Comment by jvishnuvardhan** [comment]
I think it was resolved. I am closing the issue. Please open a new ticket if you see similar issue again. Thanks!
