### ISSUE TITLE
Dynamic ksize and strides with AvgPool

### ISSUE THREAD

**Issue by davideh29-portfolio** [tensorflow/tensorflow#26961]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
1.11.0

- Are you willing to contribute it (Yes/No):
Yes - but unfamiliar with contribution process and I think it would be very similar to MaxPoolV2

**Describe the feature and the current behavior/state.**
Adding an AvgPoolV2 with dynamic ksize, much like MaxPoolV2. This is very related to issue #11875

**Will this change the current api? How?**
It would add a new function gen_nn_ops.avg_pool_v2

**Who will benefit with this feature?**
Anybody looking to use an average pooling layer with dynamic ksize. For example, when running a graph with an input of an unspecified size when the ksize is dependent on the size of the input

**Any Other info.**

**Comment by tamaranorman** [comment]
Sorry I don't have enough experience here, you need someone who has worked on the ops, I have only touched the python layer on top.

**Comment by tanzhenyu** [comment]
I can work on this, but re-defining op kernels sounds a very cool thing to do, @davideh29-portfolio do you want to contribute?

**Comment by Siddhant7** [comment]
Any update on this?

**Comment by vvmatorin** [comment]
Could you raise the priority for this, please?
I mean, it's been 2 years already, and over 3 since [#11875](https://github.com/tensorflow/tensorflow/pull/11875) was implemented. I need dynamic average pooling to implement StripPooling in my CNN, but neither torch.nn.pool, nor gen_nn_ops.avg_pool support dynamic shapes.

**Comment by edwardyehuang** [comment]
We need dynamic stride support for avgpool

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
