### ISSUE TITLE
Restoring model doesn't see variables

### ISSUE THREAD

**Issue by PawelFaron** [tensorflow/tensorflow#26964]
I saved model using:
```
def serving_input_receiver_fn():
    features = {'comment': tf.placeholder(dtype=tf.int64, shape=[None, 3])}
    return tf.estimator.export.ServingInputReceiver(features, features)

classifier.export_saved_model('saved_model', serving_input_receiver_fn)
```
When I'm trying to restore and use it:
```
predict_fn = predictor.from_saved_model(model_path)
pred = predict_fn({'comment': [1, 2, 3]})['output']
```
I'm getting the following error:

> ValueError: Got unexpected keys in input_dict: {'comment'}
> expected: set()

But when I use cli everything looks ok:
```
saved_model_cli show --dir saved_model/1553134286/ --all

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['predict']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['comment'] tensor_info:
        dtype: DT_INT64
        shape: (-1, 3)
        name: Placeholder:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['class_ids'] tensor_info:
        dtype: DT_INT64
        shape: (-1, 1)
        name: head/predictions/ExpandDims:0
```

**Comment by jvishnuvardhan** [comment]
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will open a new issue. Thanks!
