### ISSUE TITLE
How horovod integrate itself into tf distribute strategy?

### ISSUE THREAD

**Issue by zhouhaiy** [tensorflow/tensorflow#27009]
Hi,
I read from tensorflow TFC that horovod team is collobrating with tf team upon the HorovodDistributionStrategy.
RFC: https://github.com/tensorflow/community/blob/master/rfcs/20181016-replicator.md#use-case-4-users-who-will-create-new-distributionstrategy-implementations

Can anyone share with us more details about how to integrate horovod into d.s.? Because there's a lot of difference between them: e.g. launcher mode

Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
