### ISSUE TITLE
Make documentation link to C++ code

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#27029]
**System information**
- TensorFlow version: All
- Doc Link: All the Python API documentation, for example: https://www.tensorflow.org/api_docs/python/tf/nn/conv2d_transpose

**Describe the documentation issue**
The Python API documentation often points to the Python code (on github) where the operation is defined. For the example, for `tf.nn.conv2d_transpose()`, it links to [this code](https://www.tensorflow.org/code/stable/tensorflow/python/ops/nn_ops.py).

Unfortunately, most operations are fairly thin wrappers around C++ operations, and since the link from Python to C++ is automatically generated (in this example, it's `gen_nn_ops.conv2d_backprop_input()`), it is not trivial to find the corresponding C++ code (the mapping is in Bazel code, really hard to find). Many people have been bothered by this problem, as you can see by searching for gen_nn_ops on StackOverflow, for example this question: https://stackoverflow.com/questions/41147734/looking-for-source-code-of-from-gen-nn-ops-in-tensorflow

It would be great if the documentation could point to both the Python function and the C++ operation. In this case, it would be https://www.tensorflow.org/versions/r2.0/api_docs/cc/class/tensorflow/ops/conv2-d-backprop-input and the source code is in [tensorflow/core/kernels/conv_grad_input_ops.cc](https://github.com/tensorflow/tensorflow/blob/94be8f012aa59730570bf71e6ba7cd2aa432a589/tensorflow/core/kernels/conv_grad_input_ops.cc#L265).

To find it, I had to search locally on my computer to find the `gen_nn_ops.py` file, and I found that `gen_nn_ops.conv2d_backprop_input()` just called the `Conv2DBackpropInput` operation. But then I had to go back to github to search for its C++ source code (since the TensorFlow binary does not include it), and it was tricky to find, since the C++ operation is also dynamically registered, so the actual name of the function is `Conv2DCustomBackpropInputOp`. Searching for `"REGISTER_KERNEL_BUILDER  Conv2DBackpropInput"` helps.

**We welcome contributions by users. Will you be able to update submit a PR (use the [doc style guide](https://www.tensorflow.org/community/documentation)) to fix the doc Issue?**
I'm not sure where I could contribute this fix.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!

**Comment by MarkDaoust** [comment]
This feature is a good idea, but I' never going to have tie to come back and fix this.
