### ISSUE TITLE
tensorflow-gpu 2.0.0-alpha0 on win10 ImportError: DLL load failed:

### ISSUE THREAD

**Issue by YAOYI626** [tensorflow/tensorflow#27020]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  win10 Pro x64
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 
- TensorFlow version: 2.0.0
- Python version: 3.6.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: CUDA: v9.0, cuDnn: v7.5
- GPU model and memory: 1060 6GB

**Describe the problem**
errors occur when `import tensorflow as tf`
 
I have read some similar issues and [this](https://github.com/jvishnuvardhan/Installing-TensorFlow-GPU-on-Windows-10-TF1.12) but those do not work on my case.

And I reinstall tensorflow 1.13.1, it works well.

**Any other info / logs**

I'm sure you've seen many similar logs like below:

>Traceback (most recent call last):
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\JoTang507\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\JoTang507\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified module could not be found

>During handling of the above exception, another exception occurred:

>Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 27, in <module>
    from tensorflow._api.v2 import audio
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\_api\v2\audio\__init__.py", line 8, in <module>
    from tensorflow.python.ops.gen_audio_ops import decode_wav
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\JoTang507\Anaconda3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "C:\Users\JoTang507\Anaconda3\lib\imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\JoTang507\Anaconda3\lib\imp.py", line 343, in load_dynamic
    return _load(spec)
>ImportError: DLL load failed: The specified module could not be found

**Comment by shaolinkhoa** [comment]
You should install CUDA toolkit v10 just like this [guide](https://www.tensorflow.org/install/gpu#software_requirements)said.
Or you can install on conda follow this [guide](https://medium.com/@shaolinkhoa/install-tensorflow-gpu-2-0-alpha-on-anaconda-for-windows-10-ubuntu-ced099010b21?fbclid=IwAR17F1Z7Xd6yk0UYnnLhYYuHcAr6mBn61xdxbg1fLy-swd10vprfrbc__GM)

**Comment by ymodak** [comment]
I suspect you must have installed TF 1.13.1 CPU version earlier since it supports cuda 10.0 too. In addition to cuda 10.0 installation also take a look at [windows setup guide](https://www.tensorflow.org/install/gpu#windows_setup) to add cuda path. Thanks!

**Comment by shaolinkhoa** [comment]
@YAOYI626 Where do you want to install Tensorflow-gpu 2.0? local or on anaconda?
**If you want to install on local:**
I had been this error before while I install tensorflow-gpu 2.0 on local (without Anaconda). The reason are:
+ Wrong Nvidia GPU version => Solution: Install Nvidia GPU latest ( >=410.x)
+ Wrong CUDA toolkit version =>  Solution: Install CUDA toolkit 10.0
+ Wrong cuDNN version  =>  Solution: Download cuDNN 7.5 and follow this [guide](https://docs.nvidia.com/deeplearning/sdk/cudnn-install/index.html#installwindows)

**If you want to install on anaconda:**
Follow this [guide](https://medium.com/@shaolinkhoa/install-tensorflow-gpu-2-0-alpha-on-anaconda-for-windows-10-ubuntu-ced099010b21?fbclid=IwAR17F1Z7Xd6yk0UYnnLhYYuHcAr6mBn61xdxbg1fLy-swd10vprfrbc__GM):
The reason is Tensorflow 2.0 require cuDNN version >= 7.4.1 but Anaconda hasn’t supported cuDNN version >= 7.4.1 yet. So we have to download cuDNN 7.5 and manually copy cuDNN 7.5 to Anaconda environment.

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by jmp75** [comment]
The [gpu TF requirements guide](https://www.tensorflow.org/install/gpu#software_requirements) should link straight to the [cuda-10.0-download-archive](https://developer.nvidia.com/cuda-10.0-download-archive) rather than [cuda-zone](https://developer.nvidia.com/cuda-zone). It is all too easy for newbies to then install 10.1 and loose at least an hour figuring out this ImportError issue. Not a good first impression of TF2.

**Comment by hwdong-net** [comment]
I installed  "cuda_10.1.168_425.25_win10" and "cudnn-10.1-windows10-x64-v7.6.2.24".But I have the same problem
