### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.contrib'

### ISSUE THREAD

**Issue by ChaoYue0307** [tensorflow/tensorflow#27084]
Just cannot import from tensorflow.contrib in 1.13.xx, where do the packages be moved to? Thanks

**Comment by shashvatshahi1998** [comment]
Try to reinstall your tensorflow (prefer higher versions while installing it again).

**Comment by jvishnuvardhan** [comment]
Please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new?template=10-build-installation-issue.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!

**Comment by jvishnuvardhan** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by feistar** [comment]
I have the same problem...tried reinstall but not working
