### ISSUE TITLE
Unable to infer shape of placeholder

### ISSUE THREAD

**Issue by RafaelCosman** [tensorflow/tensorflow#2709]
```
myPlaceholder = tf.placeholder(dtype=tf.float32, shape=[4, 5])
tf.shape(myPlaceholder).eval()
```
```
InvalidArgumentError: You must feed a value for placeholder tensor 'Placeholder_1' with dtype float and shape [4,5]
```

One shouldn't have to feed a value for the placeholder because the shape is already determined.

**Comment by girving** [comment]
@mrry has an optimization that decouples this dependency, but maybe it has to be turned on manually?

**Comment by mrry** [comment]
Why not just use the static shape, `myPlaceholder.get_shape()`?

There is a prototype optimization (@cwhipkey is working on it now) that uses inferred shapes in constant folding, but I'm not sure that it will make your use case work. I'm inclined to say that you must _always_ feed a placeholder if you want to fetch a tensor whose value is a function of that placeholder, because making the semantics depend on optimization level seems confusing....

**Comment by girving** [comment]
@RafaelCosman: I think the conclusion is that we don't want to support the independence you want to rely on, but we also don't want to guarantee that the exception will be thrown.  Thus, what you want to do might happen to start working at some point in the future.
