### ISSUE TITLE
tf.feature_column.sequence_categorical

### ISSUE THREAD

**Issue by Jie-Yuan** [tensorflow/tensorflow#27099]
What is the difference between tf.feature_column.sequence_categorical... and tf.feature_column.categorical...？

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
