### ISSUE TITLE
Inference vs training in tensorflow 

### ISSUE THREAD

**Issue by RadjaHachilif** [tensorflow/tensorflow#27118]
Hello,
Could you please tell me how does Tensoflow differentiate the training step from the inference? ( in most examples I found, they use the same call for both steps )

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
