### ISSUE TITLE
CPU version of Tensorflow training is very slow with PlotLossesCallback

### ISSUE THREAD

**Issue by Kuselokusi** [tensorflow/tensorflow#27111]
I have the CPU version of tensorflow and have been training a 3 layered Simple Recurrent keras model. However, the model takes takes too long to complete the an epoch (in excess of 30 minutes). 
This started when I added the `plot_losses = PlotLossesCallback()` so that I can get live progress plots of the progress on the losses and accuracies for each epoch. I'm not sure how to remediate the issue. Would installing cuDNN be helpful to fixing the issue or does it not work with the CPU version of tensorflow?
Or is there another when this can be fixed?

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
