### ISSUE TITLE
how to generate batch pictures of myselt dataset

### ISSUE THREAD

**Issue by Lipingking** [tensorflow/tensorflow#27149]
Based on MNIST recognition project,I want to train myself dataset,I want to generate more pictures on the basis of the existing captured pictures. thank you for your reply as soon as possible.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by Lipingking** [comment]
thanks for your advises
