### ISSUE TITLE
Error when compiling a keras model with top_k_categorical_accuracy metrics

### ISSUE THREAD

**Issue by ruslanagit** [tensorflow/tensorflow#27165]
I am trying to compile a KERAS model for multi-class segmentation of 2D images with top_k_categorical_accuracy metrics, i.e.
`model.compile(optimizer='adadelta', 
              loss='categorical_crossentropy', 
              metrics=['accuracy', 'top_k_categorical_accuracy'])`
The error I get is:

> ValueError: Shape must be rank 2 but is rank 4 for 'metrics_2/top_k_categorical_accuracy/in_top_k/InTopKV2' (op: 'InTopKV2') with input shapes: [?,?,?,10], [?,?,?], [].

I am using one-hot encoding for the labels (10 is number of classes).
Interestingly, trying to use sparse_top_k_categorical_accuracy (which I am not supposed to use given my labels are not flattened) gives exactly the same error... 

I am using tensorflow 1.10.0

Does top_k_categorical_accuracy has any assumptions I am not aware of?  How can I make top_k_categorical_accuracy work for my model?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
