### ISSUE TITLE
Feedback limitation in a documentation web page 

### ISSUE THREAD

**Issue by simsim314** [tensorflow/tensorflow#27247]
Hello tf developers team. 

I'm coming to this page: https://www.tensorflow.org/api_docs/python/tf/bitwise, and I see no indication whether this is implemented on GPU or CPU only. Will tf help me for my project or not? I find this information page extremely unhelpful for my purpose. As the overview should state clearly when to use the library and when not (I need only bitwise operations). 

I left a feedback on your page giving two stars - but I can't write a string for you. How would you know what to fix if everyone are just saying the document is bad, and can't explain why and what they're missing?

**Comment by lamberta** [comment]
Thanks for the feedback ... it seems you found the place to enter it :)

I would suggest starting with the [guides and tutorials](https://www.tensorflow.org/overview) to get started. Perhaps check out the beginner eager tutorial notebooks to look at GPU placement. Colab provides a option to toggle the between CPU and GPU (and TPU!). The API reference is a mixed bag since there are about ~5000 pages of them. But the docstrings are open source so contributions welcome.

Stars are used more for a signal. There are no plans to add a more featureful feedback widget.
