### ISSUE TITLE
How to transfer a ckpt file to the code?

### ISSUE THREAD

**Issue by Nankaiming** [tensorflow/tensorflow#27248]
I have a demand that need to transfer the ckpt.meta file to the code. Don't use the "import_meta_graph". I means that if we know the input_tensor name and logit name, how we get the subgraph of this and transfer the graph to "inference" code.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
