### ISSUE TITLE
How to get Gather instead of GatherV2 in GraphDef?

### ISSUE THREAD

**Issue by yongwww** [tensorflow/tensorflow#27262]
Tried to use "tf.gather", each time when I export GraphDef, just saw op GatherV2, so how could I get Gather in graphdef?

**Comment by yongwww** [comment]
code snippet:

```
import tensorflow as tf

indices = tf.constant([0, 1, 1])
x = tf.constant([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])

result = tf.gather(x, indices, axis=1)

with tf.Session() as sess:
    out = sess.run(result)
    print(out)
    print(sess.graph_def)
```

**Comment by yongwww** [comment]
Got it, seems if using old tf version like 1.5, Gather will be used instead for same graph definition. Does that mean Gather is never used in TF new versons like 1.9+?

**Comment by jvishnuvardhan** [comment]
This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!

**Comment by yongwww** [comment]
posted it is stackoverflow - https://stackoverflow.com/questions/55484373/how-to-get-gather-in-graphdef

**Comment by jvishnuvardhan** [comment]
@yongwww Thank you very much.

**Comment by yongwww** [comment]
reopen it since nobody responds to the question on stackoverflow.

**Comment by yongwww** [comment]
if we can not find the Gather anymore, it should be removed

**Comment by yongwww** [comment]
Same questions for Zeros, Ones, ZerosLike, OnesLike

**Comment by alextp** [comment]
TensorFlow at one point changed to emit GatherV2 in GraphDef instead of Gather, because GatherV2 has correct shape inference, and changing the shape inference behavior of Gather could have broken existing graphs.

In general the set of ops emitted by TensorFlow for a given set of python API calls is not fixed, and can change from version to version.

If you rely on downstream processing of TensorFlow ops I recommend you use our [compat module](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/compat/compat.py) to run nightly tests against future versions of TensorFlow's graph emitting code.
