### ISSUE TITLE
tensorflow op ExtractImagePatches is not supported

### ISSUE THREAD

**Issue by ayermolo** [tensorflow/tensorflow#27400]
Hello

I am trying to convert yolov2-voc converted from darknet to TF using dark flow.
I am getting an error: "ValueError: tensorflow op ExtractImagePatches is not supported"
Currently I am using pre-build 1.9.0. Looking around seems like I need to build it from scratch, but it's not clear what I need to do on windows to get it to work.
It was mentioned to add it to tensorflow/core/kernels/BUILD, but it's not clear where exactly in it, and if I need to modify any other files.

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ayermolo** [comment]
Never mind. Miss understood some things.
