### ISSUE TITLE
High RAM usage after loading inference model into GPU

### ISSUE THREAD

**Issue by shivSD** [tensorflow/tensorflow#27512]
OS - Ubuntu 16.04
CUDA Version 10.0.130
Tensorflow version 1.13.1
YoloV2 - https://pjreddie.com/darknet/yolov2/

Trained a YOLOv2 architecture on the custom images and after freezing the graph, Model weight (.pb) file size is 268MB, Once we load this into gpu for inference it is consuming 7.93GB. I know tensorflow allocates the buffers for the output data at each stage at the beginning. Please, can somebody explain why there is so much memory usage by tensorflow.

Btw, if we run the same model with darknet framework it is taking 2.9GB of RAM.

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by shivSD** [comment]
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by shivSD** [comment]
Please, can somebody share or throw some insight into Tensorflow memory allocations while inference.

**Comment by achandraa** [comment]
Apologies for the delay in response. Have a look on this [link](https://www.tensorflow.org/guide/using_gpu) and let us know if that helps. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
