### ISSUE TITLE
tf.add_n is inaccurate for float16

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#27544]
**System information**
- TensorFlow version (you are using): master
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

`tf.add_n` is insufficiently accurate with `float16` precision for large scale training, for two reasons:

1. It sums the numbers serially, rather than in tree order.  As a result, we get stuff like this:

```
>>> f = lambda x: tf.constant(x, dtype=tf.float16)
>>> tf.add_n([f(1)]+[f(2**-11)]*7).numpy()
1.0
>>> tf.add_n([f(2**-11)]*7+[f(1)]).numpy()
1.004
```

2. It uses intermediate `float16` values, even though it would be cheap to use intermediate `float32` values.

I'd like to fix this by (1) using tree order in the Eigen kernels and (2) making the op cast up to `float32`, do the sum in `float32`, then downcast back to `float16`.

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

People using `float16` training (primarily GPU users).

**Any Other info.**

`tf.add_n` is memory bandwidth limited, so there should be negligible slowdown.

**Comment by girving** [comment]
Would want some confirmation that such a PR would be accepted before writing it.

**Comment by shashvatshahi1998** [comment]
for x in inputs:
    if x.dtype == dtypes.float16:
      x = cast(x,  dtypes.float32, name=name)
I have added these lines in tensorflow/python/ops/math_ops.py/add_n function. I guess these lines will solve your problem no 2, if yes I will make a pr.

**Comment by girving** [comment]
@shashvatshahi1998 Unfortunately that the wrong place to fix it: it has to be in C++ and CUDA.  Users of `float16` typically want to avoid `float32` temporaries where possible, and doing the cast inside the loop in the kernel means no extra memory usage.

**Comment by mohantym** [comment]
Hi @girving .Was able to replicate the issue with TF v2.5 , please find the[ gist ](https://colab.research.google.com/gist/mohantym/80904339db2688ddfe85e7f889da7460/27544.ipynb)here .Thanks!

**Comment by sanatmpa1** [comment]
Issue still persist in `2.7.0` and also in `tf-nightly`. Please find the [gist here](https://colab.sandbox.google.com/gist/sanatmpa1/504fb0e5088b67ed27d4f16157e394ed/27544.ipynb). Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!

**Comment by girving** [comment]
If you’re looking for me to respond: fine to close. I haven’t used TF in years, and in any case this issue is mostly obsolete now that we have XLA and programmable operator fusion.

**Comment by tilakrayal** [comment]
As per above comment, closing this issue as it is obsolete. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate
