### ISSUE TITLE
Wheel and libtensorflow archives contain duplicated .so files instead of symlinks

### ISSUE THREAD

**Issue by angerson** [tensorflow/tensorflow#27556]
Although https://github.com/tensorflow/tensorflow/pull/27493 resolves our CI failures, there's still a critical issue to address that **must be fixed before April 15**: we couldn't figure out how to get symlinks working properly in Bazel-generated archives, so the extra `tensorflow_framework.so.*.*` files are all duplicates. The pip wheel is now ~120MB:

```
... ... 120M Apr  5 16:05 tensorflow-1.13.1-cp27-cp27mu-linux_x86_64.whl
```
https://github.com/pypa/packaging-problems/issues/101 seems to be the most recent documentation explaining TF's maximum wheel size limit, which is currently 100MB. We won't be able to upload the 1.14 release until this is addressed. TF is [just scraping the limit at 92MB](https://pypi.org/project/tensorflow/#files), so all extra files will have to be symlinks to fix this properly.

The libtensorflow archives are affected by this as well.

FYI @gunan, assigning to myself and @perfinion.

**Comment by angersson** [comment]
For some more context, even if Bazel is configured to generate symlinks, the `pkg_tar` rule (and whatever `build_pip_package` does) will dereference them when packaging the files. We'd like our binary files to include e.g. `libtensorflow.so` and `libtensorflow.so.1` which both symlink to `libtensorflow.so.1.13.0` (I think). I can put together a demonstration of this if we need it.

**Comment by perfinion** [comment]
Also somewhat related: https://github.com/tensorflow/tensorflow/issues/27430

So the only one that is strictly required in the pip wheel is `libtensorflow_framework.so.1` since that is the one that matches the soname. The fuller length `libtensorflow_framework.so.1.13.1` is used in distros a lot (with the symlinks) but for the pip wheel i have no issues dropping it.
`ldd $(find . -iname "*\.so*") | grep '^\s' | sed 's/(0x[0-9a-fA-F]*)$//' | sort -u ` in the `site-packages/tensorflow` dir shows what things depend on (ie only the .so.1 file)

The unversioned `libtensorflow_framework.so` one is only required for compiling. It makes `gcc foo.c -ltensorflow_framework` work nicely but compiling with the full name directly does also work, you just have to do `gcc foo.c -l:libtensorflow_framework.so.1`, so we could drop the unversioned one too to save space. I'd rather have a symlink obviously but there are other ways to do it need be.

**Comment by angerson** [comment]
I think this is fixed, or at least no longer an issue.
