### ISSUE TITLE
Multidimensional Keras recurrent layers

### ISSUE THREAD

**Issue by ARozental** [tensorflow/tensorflow#27608]
Tensorflow 2.0.0-alpha

currently Keras recurrent layer expect their input to have exactly 3 dimensions: (batch, sequence_length, element_size)

Input of higher dimensions will result in the following error:
> ValueError: Input 0 of layer unified_lstm is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [2, 3, 5, 4]

The wanted behavior is as follows:
let's say that I have in input of shape (2, 3, 5, 4) where every element in my batch have 3 documents: (batch, document_number, sequence_length, element_size).
I would like for the LSTM to consume only the last 2 dimensions (2*3 time)  in the same manner that tf.keras.layers.Dense consumes only the last dimension.

**This will not change the current api**
**I an willing to help (though it will be my first time committing to FT)**
**Anyone that wants to run several RNNs in parallel will benefit from this feature**

**Comment by qlzh727** [comment]
I think for LSTM itself, the specification is quite clear that the input has to be 3D, but this is not enforce for RNN layer.

If you want to have a RNN cell accept high dimension input, you can certainly create a custom cell for that. In fact we have a similar example in the unit test.

https://github.com/tensorflow/tensorflow/blob/5581b91ada226f1ec20f55cd6423853072b2813c/tensorflow/python/keras/layers/recurrent_test.py#L1340.

Furthermore, I think LSTM has clear math definition, which is not like Dense layer. Updating default LSTM is probably not something we can intake.

**Comment by qlzh727** [comment]
The other alternative I can think of is that you reshape your data before feeding it to LSTM, eg [2, 3, 5, 4] -> [6, 5 ,4]. Since document_number is not something that you want LSTM to aware, the math result for the data after conversion should be same as before. You can also reshape the output from LSTM to bring back your document_number dim. 

If you want LSTM to aware your document_number, then you will need a customized cell to do that.

**Comment by qlzh727** [comment]
The other alternative I can think of is that you reshape your data before feeding it to LSTM, eg [2, 3, 5, 4] -> [6, 5 ,4]. Since document_number is not something that you want LSTM to aware, the math result for the data after conversion should be same as before. You can also reshape the output from LSTM to bring back your document_number dim. 

If you want LSTM to aware your document_number, then you will need a customized cell to do that.

**Comment by qlzh727** [comment]
The example could be like:

```
batch, document_number, sequence_length, element_size = 2, 3, 5, 4
inputs = tf.ones([batch, document_number, sequence_length, element_size])
lstm_inputs = tf.reshape(inputs, [None, sequence_length, element_size])
lstm = tf.keras.layers.LSTM(10, return_sequence=True)
lstm_outputs = lstm(lstm_inputs)
outputs = tf.reshape(lstm_outputs, [batch, document_number, sequence_length, 10])
```

**Comment by qlzh727** [comment]
The example could be like:

```
batch, document_number, sequence_length, element_size = 2, 3, 5, 4
inputs = tf.ones([batch, document_number, sequence_length, element_size])
lstm_inputs = tf.reshape(inputs, [None, sequence_length, element_size])
lstm = tf.keras.layers.LSTM(10, return_sequence=True)
lstm_outputs = lstm(lstm_inputs)
outputs = tf.reshape(lstm_outputs, [batch, document_number, sequence_length, 10])
```

**Comment by qlzh727** [comment]
The example could be like:

```
batch, document_number, sequence_length, element_size = 2, 3, 5, 4
inputs = tf.ones([batch, document_number, sequence_length, element_size])
lstm_inputs = tf.reshape(inputs, [None, sequence_length, element_size])
lstm = tf.keras.layers.LSTM(10, return_sequence=True)
lstm_outputs = lstm(lstm_inputs)
outputs = tf.reshape(lstm_outputs, [batch, document_number, sequence_length, 10])
```

**Comment by qlzh727** [comment]
I am closing this FR since there isn't anything i can address here. Feel free to reopen this if you feel otherwise. Thanks.

**Comment by ARozental** [comment]
@qlzh727 Thanks. Reshaping to 3D and back is exactly the behavior I would expect so Keras layers will be interchangeable with other TF layers. I can implement it myself for my code but I really believe other people could also enjoy it and the implementation is not hard.
