### ISSUE TITLE
Starting a TF session (and nothing else) uses over 350MB of GPU memory

### ISSUE THREAD

**Issue by farzaa** [tensorflow/tensorflow#27651]
On TF `1.13.1`, the code below:
```
with tf.Session(config=config) as sess:
    while True:
        print("Session is open!")
        time.sleep(1)
Uses 363MiB / 16280MiB according to nvidia-smi.
```

Am I missing something or is this normal? Shouldn't GPU usage be 0MiB at this point? If not, why?

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
