### ISSUE TITLE
unrecognized arguments: --output_node_names

### ISSUE THREAD

**Issue by pramodKarande** [tensorflow/tensorflow#27674]
i am following steps mentioned in [this](https://medium.com/testdotai/training-data-for-app-classifier-f217dc005523) article.
at "tensorflowjs_converter --input_format=tf_frozen_model --output_node_names=final_result  output/saved_model.pb web_model" this step i am getting below issue;

usage: TensorFlow.js model converters. [-h]
                                       [--input_format {tf_hub,keras,tf_session_bundle,keras_saved_model,tensorflowjs,tfjs_layers_model,tf_saved_model,tf_frozen_model}]
                                       [--output_format {tfjs_layers_model,tensorflowjs,keras,tfjs_graph_model}]
                                       [--signature_name SIGNATURE_NAME]
                                       [--saved_model_tags SAVED_MODEL_TAGS]
                                       [--quantization_bytes {1,2}]
                                       [--split_weights_by_layer] [--version]
                                       [--skip_op_check SKIP_OP_CHECK]
                                       [--strip_debug_ops STRIP_DEBUG_OPS]
                                       [input_path] [output_path]
TensorFlow.js model converters.: error: unrecognized arguments: --output_node_names=final_result

- **OS Platform and Distribution : MacOS 10.14 (MacBook Pro)
- **TensorFlow installed from pip
- **TensorFlow version : 1.13.1
- **Python version : 3.6.5

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by rosman21** [comment]
Did you ever figure this out?

**Comment by pramodKarande** [comment]
degrading python version and tensorflow version worked for me.
