### ISSUE TITLE
Checkpoint Restore blocked by changed default bias variable name

### ISSUE THREAD

**Issue by mschonwe** [tensorflow/tensorflow#2768]
### Environment info
Operating System: Ubuntu 14.04
Built from source (016da8c9b9f171235a528e3361b8068c693c5529)

Has there been a recent change that modified the default name of the bias variable from "bias" to "biases" (in the nn_ops.conv2d)?

When loading from a checkpoint there is an error:
tensorflow.python.framework.errors.NotFoundError: Tensor name "model/attention_decoder/Attention_0/fully_connected/biases" not found in checkpoint files .../model.ckpt

Looking the variables stored in a checkpoint file the closest match is:
model/attention_decoder/Attention_0/fully_connected/bias (DT_FLOAT) [512]

Loading this checkpoint file had been working fine for weeks, so it seems like a TF update that has caused the issue.

Can the model.ckpt[.meta] be edited to work around the change?  If so, is there a guide or any pointers for how to do it.

**Comment by mrry** [comment]
The easiest way to work around this is to specify a list of explicit variable names when creating your `tf.train.Saver()`. Creating a `tf.train.Saver` with no arguments is equivalent to doing:

```python
saver = tf.train.Saver({v.op.name: v for v in tf.all_variables()})
```

The dictionary keys correspond to the names in the checkpoint file that will be read/written by the saver. You can customize the dictionary so that it matches your old checkpoint. For example:

```python
names_to_vars = {v.op.name: v for v in tf.all_variables()}
bias_var = names_to_vars["model/attention_decoder/Attention_0/fully_connected/biases"]
names_to_vars["model/attention_decoder/Attention_0/fully_connected/bias"] = bias_var
del names_to_vars["model/attention_decoder/Attention_0/fully_connected/biases"]
saver = tf.train.Saver(var_list=names_to_vars)
```

PS. This is probably more appropriate as a Stack Overflow question, rather than a GitHub issue.

**Comment by gawinghe** [comment]
You need to call inception_v3() within the arg_scope() returned by inception_v3_arg_scope()

**Comment by gb96** [comment]
Seven years on, I encountered this kind of problem trying to restore and inference using an old pretrained TF1.x model.

Seems that older versions of TF (circa 1.0.0) tended to default names like "weights" and "biases" but then these defaults changed to "kernel" and "bias".

Because my model had too many layers to sensibly modify the names_to_vars dict as suggested above, I used this lazier method to achieve the same result.   Hope someone else finds it helpful:

    names_to_vars = {v.op.name.replace("biases", "bias").replace("weights", "kernel"): v for v in tf.all_variables()}

    # or to apply the naming patch the opposite direction:

    names_to_vars = {v.op.name.replace("bias", "biases").replace("kernel", "weights"): v for v in tf.all_variables()}

    saver = tf.train.Saver(var_list=names_to_vars)
