### ISSUE TITLE
axis parameter in tf.random_shuffle

### ISSUE THREAD

**Issue by GeorgeKaspar** [tensorflow/tensorflow#27686]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.13
- Are you willing to contribute it (Yes/No): Yes, if you help me to do

**Describe the feature and the current behavior/state.**
No, current behavior will not change

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
now code is 
x = tf.transpose(x, [3, 0, 1, 2])
x = tf.random_shuffle(x)
x = tf.transpose(x, [1, 2, 3, 0]

code will be
x = tf.random_shuffle(x, axis=-1)
**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@GeorgeKaspar Could you provide more details about the feature and its use cases? What is the current gap that you wish to fill this feature? Thank you!

**Comment by GeorgeKaspar** [comment]
I work on https://arxiv.org/pdf/1901.03447.pdf
And with code need shuffling across different axes
I think, that tensorflow has limited support for permutations of data
In that article, we have specific randomized permutations and standard implementation without C++ extensions on tensorflow very slow...
It is one reason add permutation across different axes

**Comment by episodeyang** [comment]
This is definitely needed. In RL, my batch data from replicator looks like 
```
unroll_batch = Shape[H, B, C]
```

and I have two sets of decoys, need to shuffle one by the time dimension, and another by the batch. 

So i want to do 
```
decoy_1 = tf.random_shuffle(unroll, axis=0)
decoy_2 = tf.random_shuffle(unroll, axis=1)
```

**Comment by SuryanarayanaY** [comment]
Same status.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
