### ISSUE TITLE
Unable to do transpose on a  yolo model 

### ISSUE THREAD

**Issue by Rathna21** [tensorflow/tensorflow#27691]
Hello,

I am trying to add a transpose layer at the end of Yolo model.

I am using the following script, 

model = load_model(filepath="yolov2-tiny-voc.h5")
output = model.output
output_shape = model.output.shape
transpose = Lambda(lambda x: tf.transpose(output, prem=(0,3,1,2),name='transpose'))(output)
final_model = Model(inputs= model.input, outputs= transpose )
save_model(model=final_model, filepath= "trial_attempt.h5")

But I am getting the following error:
AttributeError: 'Conv2D' object has no attribute 'outbound_nodes'

Could someone help on this issue?

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Rathna21** [comment]
@gadagashwini ,

The platform is macOS High Sierra.
The tensorflow version is 1.13.1.
I have installed using pip.

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: macOS High Sierra
- **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device**: NA
- **TensorFlow installed from (source or binary)**: Binary
- **TensorFlow version (use command below)**: tensorflow 1.13.1
- **Python version**:  python 3.6.6
- **Bazel version (if compiling from source)**: NA
- **GCC/Compiler version (if compiling from source)**: NA
- **CUDA/cuDNN version**:
- **GPU model and memory**: 
- **Exact command to reproduce**:

model = load_model(filepath="yolov2-tiny-voc.h5")
output = model.output
output_shape = model.output.shape
transpose = Lambda(lambda x: tf.transpose(output, prem=(0,3,1,2),name='transpose'))(output)
final_model = Model(inputs= model.input, outputs= transpose )
save_model(model=final_model, filepath= "trial_attempt.h5")


### Describe the problem
Describe the problem clearly here. Be sure to convey here why it's a bug in TensorFlow or a feature request.

### Source code / logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

model = load_model(filepath="yolov2-tiny-voc.h5")
output = model.output
output_shape = model.output.shape
transpose = Lambda(lambda x: tf.transpose(output, prem=(0,3,1,2),name='transpose'))(output)
final_model = Model(inputs= model.input, outputs= transpose )
save_model(model=final_model, filepath= "trial_attempt.h5")

Let me know if you need any further information.

**Comment by gadagashwini** [comment]
@Rathna21 Thanks for providing the details.

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
