### ISSUE TITLE
Support synchronous training with parameter servers using Distribution Strategies

### ISSUE THREAD

**Issue by yuefengz** [tensorflow/tensorflow#27725]
**System information**
- TensorFlow version (you are using): TF 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Right now we have `MirroredStrategy` and `MultiWorkerMirroredStrategy` for synchronous training where variables and ops are all replicated and all-reduce is used for gradient aggregation. We also have `ParameterServerStrategy` where gradient updates from workers are purely asynchronous since `SyncReplicasOptimizer` is buggy and has been deprecated.
 
We would like to first collect use cases where synchronous training with `MirroredStrategy` and `MultiWorkerMirroredStrategy` is not ideal and synchronous training with parameter servers is necessary.

If this feature is necessary and important enough, we will then use this issue to track the progress of the development of this feature.

We have a separate feature request to support large embeddings with `MirroredStrategy` and `MultiWorkerMirroredStrategy`: https://github.com/tensorflow/tensorflow/issues/27726

**Will this change the current api? How?**
Yes.

**Who will benefit with this feature?** 
Those who use distributed training.

**Any Other info.**
N/A

**Comment by shendiaomo** [comment]
What's the progress of this issue?

**Comment by liyi193328** [comment]
What's the progress of this issue?

**Comment by neuzxy** [comment]
This feature is promising. What's the progress of this issue? @yuefengz

**Comment by yuefengz** [comment]
We will send out a RFC for PSStrategy soon.

**Comment by liyi193328** [comment]
There is any plan? Thanks @yuefengz

**Comment by sahiltyagi4** [comment]
@yuefengz any developments on this ?

**Comment by Mesilenceki** [comment]
hi , Is there some progress with this issue?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
