### ISSUE TITLE
Support model parallelism in tf.distribute.Strategy

### ISSUE THREAD

**Issue by guptapriya** [tensorflow/tensorflow#27724]
Current tf.distribute.Strategy only supports data parallelism. We would like to support the following form of model parallelism: user specifies a number of "logical devices" per replica upfront, and then explicitly places ops on a specific logical device.

**Comment by cweill** [comment]
We can benefit from this in https://github.com/tensorflow/adanet: we have heterogeneous subgraphs within a tf.Graph that we would like to distribute across logical devices.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
