### ISSUE TITLE
How can I warm up the cache by calling the predict method with an all zero inputs in browsers?

### ISSUE THREAD

**Issue by XdyGoGo** [tensorflow/tensorflow#27746]
You can warm up the cache by calling the predict method with an all zero inputs

**Comment by XdyGoGo** [comment]
Sorry, I do not know what you mean is?

**Comment by gadagashwini** [comment]
@XdyGoGo This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.  If you think it is a bug/feature request, please fill the respective template inorder to start triaging. Thanks !

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
