### ISSUE TITLE
C++ compilation of rule '//tensorflow/core/grappler/optimizers:memory_optimizer' failed (Exit 2)

### ISSUE THREAD

**Issue by Clamps251** [tensorflow/tensorflow#27826]
Hi,

When i run: bazel build tensorflow/tools/graph_transforms:transform_graph i get the following issue:
tensorflow/core/grappler/optimizers/BUILD:428:1: C++ compilation of rule '//tensorflow/core/grappler/optimizers:memory_optimizer' failed (Exit 2)

I am running this on Windows 10, has anyone come accross this isse?

Thanks in advance.

**Comment by LiuPangYao** [comment]
win10, bazel0.24.1
run: bazel build tensorflow/tools/graph_transforms:transform_graph get
ERROR: C:/users/user/tensorflow_test2/tensorflow/tensorflow/core/kernels/data/BUILD:78:1: C++ compilation of rule '//tensorflow/core/kernels/data:captured_function' failed (Exit 2)

**Comment by ymodak** [comment]
@Clamps251 Is this still an issue? Can you please provide following information? Thanks!
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by LiuPangYao** [comment]
> 
> 
> @Clamps251 Is this still an issue? Can you please provide following information? Thanks!
> **System information**
> 
>     * Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
> 
>     * OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
> 
>     * Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
> 
>     * TensorFlow installed from (source or binary):
> 
>     * TensorFlow version (use command below):
> 
>     * Python version:
> 
>     * Bazel version (if compiling from source):
> 
>     * GCC/Compiler version (if compiling from source):
> 
>     * CUDA/cuDNN version:
> 
>     * GPU model and memory:
> 
> 
> You can collect some of this information using our environment capture
> [script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
> You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
> 
> **Describe the current behavior**
> 
> **Describe the expected behavior**
> 
> **Code to reproduce the issue**
> Provide a reproducible test case that is the bare minimum necessary to generate the problem.
> 
> **Other info / logs**
> Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

question fix, environment not install error C++ visual studio install fail

**Comment by ymodak** [comment]
@LiuPangYao Please post a [new issue](https://github.com/tensorflow/tensorflow/issues/new/choose) and provide all the information asked by the template.  We ask this because it's more efficient to have one thread dedicated to one issue. Thanks!
