### ISSUE TITLE
Building TensorFlow on RaspberryPi

### ISSUE THREAD

**Issue by MrSlayer02** [tensorflow/tensorflow#2783]
I'm trying to build `TensorFlow` on a Raspberry Pi (OS : Raspbian Jessie), but I get this error :  

http://pastebin.com/zUfP4xsP

I use this command to build TensorFlow : 
`sudo bazel build -c opt --local_resources 1024,1.0,1.0 --verbose_failures --ignore_unsupported_sandboxing --copt="-mfpu=neon" tensorflow/tools/pip_package:build_pip_package
`

Any help ?

**Comment by prb12** [comment]
@petewarden  - do you know what the current status is of TF on RaspberryPi?

**Comment by petewarden** [comment]
It's a bit tricky to build using Bazel, since you need a USB drive plugged in so that in can swap beyond the 1GB of RAM on the Pi. @samjabrahams has a great rundown here:
https://github.com/samjabrahams/tensorflow-on-raspberry-pi

If you only need to run models, not train them, we're have makefile support for the core inference part of TensorFlow here:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/pi_examples

**Comment by prb12** [comment]
Closing since this isn't a specific bug, and RaspberryPi is not an offically supported platform (afaik).  
It makes sense to redirect discussion to https://github.com/samjabrahams/tensorflow-on-raspberry-pi

**Comment by samjabrahams** [comment]
Awesome- I hadn't seen the makefile folders in contrib yet- I'll add in that information to the Raspberry Pi repo after I give it a look-over.
