### ISSUE TITLE
Add built-in helper functions for _bytes_feature, _float_feature and _int64_feature from "Using TFRecords and tf.Example" page

### ISSUE THREAD

**Issue by terryspitz** [tensorflow/tensorflow#27831]
The TF documentation page "Using TFRecords and tf.Example" https://www.tensorflow.org/tutorials/load_data/tf_records lists these helper functions:

```
# The following functions can be used to convert a value to a type compatible
# with tf.Example.

def _bytes_feature(value):
  """Returns a bytes_list from a string / byte."""
  return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))

def _float_feature(value):
  """Returns a float_list from a float / double."""
  return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def _int64_feature(value):
  """Returns an int64_list from a bool / enum / int / uint."""
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))
```

Searching github code shows these have been cut and pasted 3453 times into other projects:
https://github.com/search?q=_bytes_feature+_float_feature&type=Code
and presumably many more times besides.

Could TF include helper functions for these and other common tf.train.Features/Examples helpers?

**System information**
- TensorFlow version: 1.13.1
- Are you willing to contribute it: Yes (at some point)

**Describe the feature and the current behavior/state.**
Examples and Features are recommended as the canonical way to store TF datasets.  However understanding the protobufs is non-trivial: they are multiple layers deep and have a verbose API.

**Will this change the current api? How?**
This will make the API simpler and more pythonic for building usual Features and Examples.

**Who will benefit with this feature?**
All users building datasets.

**Any Other info.**

**Comment by bionicles** [comment]
agreed, this is boilerplate, tf could easily have this. tfrecords are cool but could be simplified dramatically and be better for it

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
