### ISSUE TITLE
[feature request]check whether a data iterator is initialized

### ISSUE THREAD

**Issue by passerbyd** [tensorflow/tensorflow#27915]
**System information**
- TensorFlow version (you are using): r1.13
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**
When a dataset iterator is shared among sessions by "shared_name", non-chief sessions need to wait for its initialization on the chief session. And what is the proper way to check the state of iterators currently？
Ideally, iterators should be initialized by init_ops of monitoredsession, and checked in model_ready function.

**Will this change the current api? How?**
No changes on current api. add one new api like "is_initialized".

**Who will benefit with this feature?**
all who use "shared_name" feature.

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by passerbyd** [comment]
> Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

sorry，added informations.

**Comment by passerbyd** [comment]
awaiting tensorflower

**Comment by jsimsa** [comment]
TF 1.X style iterators are deprecated in TF 2.0 and the tf.data team will not prioritize this request. I will mark this issue as contributions welcome.

**Comment by rthadur** [comment]
as the style iterators are deprecated , this is no longer a valid feature request, closing this issue. Thank you
