### ISSUE TITLE
Autodiff creates stack for loop-invariant data

### ISSUE THREAD

**Issue by nunoplopes** [tensorflow/tensorflow#27926]
In file `control_flow_ops.py`, `GetRealValue()` implements the functionality to get the value of an operation from each forward loop iteration to be used in the backward loop.
This function checks if the operation is a constant and skips creating a stack for these. Otherwise it creates a stack and pushes the value at each loop iteration.
The issue is that `GetRealValue()` doesn't check if the operation is loop invariant, or simply, if it's computed outside the loop, and still creates the stack. I see significant memory consumption because of this.

I tried to find a way of checking if an operation is loop invariant or if it's computed outside the loop, but failed to find such a function (I'm new in TF source-code). If you could point me out to such a function, I would be happy to try to produce a patch.
Thanks!

**Comment by sanjoy** [comment]
@saxenasaurabh Any ideas about this?

**Comment by saxenasaurabh** [comment]
Could you provide a code snippet? v1 control flow [should not](https://github.com/tensorflow/tensorflow/blob/fd28b784b2e82ddb2c72196668374e244cfdf205/tensorflow/python/ops/control_flow_ops.py#L1006) be capturing loop invariants. Are you maybe passing the tensor in the list of loop_vars?

**Comment by nunoplopes** [comment]
I've uploaded a simple example here: https://gist.github.com/nunoplopes/5d98b7f8301ca3b74f6a32bd974fbae5

See the XLA output below, where green shows 'a', which is loop invariant. And in yellow you've the stack push to store 'a' on each iteration:
![tf-loop](https://user-images.githubusercontent.com/2998477/56738201-05033e80-6764-11e9-8c8f-f66d16eaff44.jpg)

**Comment by saxenasaurabh** [comment]
Thanks for the repro. Even though variables are marked as loop invariants, they could get updated in the loop body. Arguing for constness of a variable used in the While body may be hard because they are updated in-place. Could you try reading the variable's value outside the loop using [`a.read_value()`](https://www.tensorflow.org/api_docs/python/tf/Variable#read_value) and use that in the loop body? That should fix your memory issue I think.

**Comment by nunoplopes** [comment]
That gets rid of the stack for `a` indeed, thank you.
In theory, just iterating over all the instructions in the loop and checking which variables they can potentially write to doesn't sound too hard. But I don't know enough of TF's internals to judge that. I couldn't even find a way to iterate over such instructions.

@saxenasaurabh Do you think v2 loops will solve the issue (or at least make it easier to solve)?  Is there hope of fixing this?
Thanks!

**Comment by saxenasaurabh** [comment]
I don't think v2 loops will fix this (at least for now). I think there are some other issues with while loop accumulating _too much_. Maybe we can handle all those cases as an optimization pass. Let me know if you have other thoughts on this or if you would like to contribute :) I will close this for now since I might not be able to look into this immediately but this is definitely on my radar of potential performance improvements for tf.while_loop.
