### ISSUE TITLE
Why "Don't build XLA with -ffast-math"?

### ISSUE THREAD

**Issue by zhangyafeikimi** [tensorflow/tensorflow#27942]
The most problem is not as title.

It is ridiculous that the error is thrown out after thousands of files were compiled.

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
