### ISSUE TITLE
`GetCudaLaunchConfig` configuration of number of blocks

### ISSUE THREAD

**Issue by ThisIsIsaac** [tensorflow/tensorflow#27943]
the definition is:
```
inline CudaLaunchConfig GetCudaLaunchConfig(int work_element_count,
                                            const Eigen::GpuDevice& d) {
  CHECK_GT(work_element_count, 0);
  CudaLaunchConfig config;
  const int virtual_thread_count = work_element_count;
  const int physical_thread_count = std::min(
      d.getNumGpuMultiProcessors() * d.maxGpuThreadsPerMultiProcessor(),
      virtual_thread_count);
  const int thread_per_block = std::min(1024, d.maxGpuThreadsPerBlock());
  const int block_count =
      std::min(DivUp(physical_thread_count, thread_per_block),
               d.getNumGpuMultiProcessors());

  config.virtual_thread_count = virtual_thread_count;
  config.thread_per_block = thread_per_block;
  config.block_count = block_count;
  return config;
}
```

why is the number of blocks is capped at `getNumGpuMultiProcessors`?

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ThisIsIsaac** [comment]
sorry for the lack of clarity. I am asking the design decision behind only launching as many blocks as `d.getNumGpuMultiProcessors` in this [file](https://github.com/tensorflow/tensorflow/blob/5d34d064d3163c451c90b318a501792dcafee600/tensorflow/core/util/gpu_launch_config.h#L125).

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
