### ISSUE TITLE
Tensorflow 2.0 has missing features related to checkpointing Dataset

### ISSUE THREAD

**Issue by KichangKim** [tensorflow/tensorflow#27954]
**System information**
- TensorFlow version: 2.0-alpha.0
- Doc Link:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/make_saveable_from_iterator

**Describe the documentation issue**
With 2.0-alpha.0, tf.data.Dataset does not have any make_xx_iterator() methods, so I can't save/restore iterate state while training by using tf.data.experimental.make_saveable_from_iterator().

How to save/restore internal state of Dataset?

**Comment by KichangKim** [comment]
It seems that iterator from Dataset.__iter__() can be serialized with tf.train.Checkpoint(). Even though it is not described in document.

**Comment by jsimsa** [comment]
Checkpointing of stateful functions is not supported.

As far as I can tell from looking at the [implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/script_ops.py) of `py_function` and `numpy_function`. `tf.py_function` is unconditionally stateless while `tf.numpy_function` is unconditionally stateful. So the error you are describing does not match the expected behavior of the code.

If you would like further help, please provide a reproducible example.

**Comment by KichangKim** [comment]
Here is reproducible sample.

```
import tensorflow as tf

image_paths = ['test.png']


def my_map_py(x):
    return x


dataset = tf.data.Dataset.from_tensor_slices(image_paths)
dataset = dataset.map(lambda x: tf.py_function(my_map_py, [x], [tf.string]))

iterator = dataset.__iter__()

checkpoint = tf.train.Checkpoint(iterator=iterator)
checkpoint.save('checkpoint.tf')
```

**Comment by jsimsa** [comment]
Thank you for the reproducible example.

I took a closer look at the [implementation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/script_ops.py) of `py_function` and it turns out it is implemented using the `EagerPyFunc` op, which is also stateful. In other words, you will not be able to checkpoint an input pipeline that contains `numpy_function` or py_function`.

**Comment by KichangKim** [comment]
Thanks for invedtigation. I divided my dataset into multiple datasets and manually save checkpoint via its offset.
