### ISSUE TITLE
Tensorflow 2.0's eager_execution for keras is not real.

### ISSUE THREAD

**Issue by TianLin0509** [tensorflow/tensorflow#27972]
For normal tensorflow codes, it works well.
However, for tf.keras, it actually performs as a static graph, which is terrible.

An good example is tensorflow 1.12.0, which enables users easily debug keras models.
I just wonder why not inherit the 1.12.0's mode in tf2.0? the former is much better.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
