### ISSUE TITLE
tflite interpreter getting stuck at runForMultipleInputsOutputs function

### ISSUE THREAD

**Issue by spaul13** [tensorflow/tensorflow#28217]
I am initializing tflite interpreter to run the object detection inference with GPU delegate option for Yolov3 (adding a GPU delegate) for enabling GPU support on Android Platform (on Pixel 2). But when I run **tflite.runForMultipleInputsOutputs**(inputArray, outputMap);

Its getting stuck there not returning anything while without the GPU delegate that functions working well. Can anyone please tell me why it's getting stuck for indefinitely?

[e.g., If few ops are not performed by GPU that must be performed by CPU this might increase the time of inference but it should provide the output]

**Comment by muddham** [comment]
@spaul13 It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
