### ISSUE TITLE
Detecting Bounding Boxes along with class labels realtime

### ISSUE THREAD

**Issue by spaul13** [tensorflow/tensorflow#28218]
I am using TF Lite Android Image Classifier App provided with this project with GPU support for Mobilenetv1. I want to know how I can detect the bounding boxes of inferred/detected objects along with the class labels?

Can anyone please tell me what modifications I have to make?

**Comment by freedomtan** [comment]
You may want to start from the object detection example first https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android

**Comment by spaul13** [comment]
@freedomtan Thanks a lot for the reply. It (https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android) is working for the input size 224 when I am changing the resized bitmap size from 224 to 416 or 608 I am getting the following error 

**_04-30 22:00:51.810 26345-26363/org.tensorflow.lite.examples.detection E/AndroidRuntime: FATAL EXCEPTION: inference
    Process: org.tensorflow.lite.examples.detection, PID: 26345
    java.lang.ArrayIndexOutOfBoundsException
        at android.graphics.Bitmap.checkPixelsAccess(Bitmap.java:1718)
        at android.graphics.Bitmap.getPixels(Bitmap.java:1659)
        at org.tensorflow.lite.examples.detection.tflite.TFLiteObjectDetectionAPIModel.recognizeImage(TFLiteObjectDetectionAPIModel.java:156)
        at org.tensorflow.lite.examples.detection.DetectorActivity$2.run(DetectorActivity.java:215)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)_**
can anyone please tell me how to resolve this issue?

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
