### ISSUE TITLE
tflite_interpreter.run() showing error with GPU delegate

### ISSUE THREAD

**Issue by spaul13** [tensorflow/tensorflow#28220]
I am trying to implement the GPU support on Android for Yolov3 model.  Without the GPU support its working fine but whenever I am creating a GPU delegate and adding as the interpreter option and finally creating a tflite interpreter that can run to GPU. But tflite interpreter got stuck in runForMultipleInputsOutputs() call (Never returning from this)

While using tflite_interpreter.run() I am getting the following error, can anyone Please tell me how to resolve this issue?

**_Error:_**
_04-28 01:28:54.862 21858-21916/com.amitshekhar.tflite E/AndroidRuntime: FATAL EXCEPTION: Thread-4
    Process: com.amitshekhar.tflite, PID: 21858
    java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 13, 13, 3, 12] and a Java object with shape [1, 7].
        at org.tensorflow.lite.Tensor.throwExceptionIfTypeIsIncompatible(Tensor.java:270)
        at org.tensorflow.lite.Tensor.copyTo(Tensor.java:141)
        at org.tensorflow.lite.NativeInterpreterWrapper.run(NativeInterpreterWrapper.java:161)
        at org.tensorflow.lite.Interpreter.runForMultipleInputsOutputs(Interpreter.java:275)
        at org.tensorflow.lite.Interpreter.run(Interpreter.java:249)_

**Comment by muddham** [comment]
@spaul13 It looks like you haven't used a template to create this issue(mention the versions used). Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by muddham** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
