### ISSUE TITLE
tf.Module name scope nesting does not work as expected

### ISSUE THREAD

**Issue by ethereon** [tensorflow/tensorflow#28249]
Consider the following example:

```Python
import tensorflow as tf

with_name_scope = tf.Module.with_name_scope


class Alpha(tf.Module):
    def __init__(self):
        super().__init__()
        self.var = None

    @with_name_scope
    def __call__(self, x):
        if self.var is None:
            self.var = tf.Variable(42., name='leaf')
        return x + self.var


class Beta(tf.Module):
    def __init__(self):
        super().__init__()
        self.alpha = Alpha()

    @with_name_scope
    def __call__(self, x):
        return self.alpha(x)


class Gamma(tf.Module):
    def __init__(self):
        super().__init__()
        self.beta = Beta()

    @with_name_scope
    def __call__(self, x):
        return self.beta(x)


gamma = Gamma()
gamma(1)
print(gamma.trainable_variables[0].name)
```

While the expected output is `gamma/beta/alpha/leaf:0`, the actual output is `alpha/leaf:0`. This appears to be because `_scope_name` in `tf.Module` has a trailing slash with breaks out of enclosing name scopes. 

In contrast, substituting the following for `with_name_scope` works correctly:

```python
def with_fixed_name_scope(method):
    def wrapped(self, *args, **kwargs):
        with tf.name_scope(self.name):
            method(self, *args, **kwargs)
    return wrapped


with_name_scope = with_fixed_name_scope
```

Tested with TensorFlow 2.0 built from source (`5473bb187efacc3ce26a7203801aebac68045ee0`)

**Comment by tomhennigan** [comment]
Hey ethereon@, thanks for the report. Module name scopes are fixed at construction time, and re entered whenever you use `@with_name_scope` or `with self.name_scope`. They are intentionally "fully qualified" (not sure if that's the right term) such that they don't inherit the scope from the caller. We've been using that pattern for variable naming in Sonnet for a few years now and it seems to be a sensible idea (reasoning about where you construct modules [and thus what name they will have] is often simpler than reasoning about where they will be used for the first time).

In this case what you'll want to do is manually enter the name scope in the constructor when creating the inner modules:

```python
class Beta(tf.Module):
    def __init__(self):
        super(Beta, self).__init__()
        with self.name_scope:
          self.alpha = Alpha()

    @with_name_scope
    def __call__(self, x):
        return self.alpha(x)


class Gamma(tf.Module):
    def __init__(self):
        super(Gamma, self).__init__()
        with self.name_scope:
          self.beta = Beta()

    @with_name_scope
    def __call__(self, x):
        return self.beta(x)
```

With that I get `gamma/beta/alpha/leaf:0`.

In the RFC we had designed `tf.Module` such that it would automatically enter the name scope for you in all methods (removing the need for the boilerplate). Sadly we found that in practice this makes it ~impossible for existing libraries (e.g. `tf.keras`) to adopt `tf.Module` (since this was backwards incompatible for existing checkpoints) so in e866995aff7d I made the scoping opt-in rather than opt-out (which in turn meant Keras Layer/Model could adopt `tf.Module` in 23c8fd4ca3).

If you'd prefer the automatic name scoping (I do) then I'd suggest keeping an eye out for the open source release of Sonnet 2 (c.f. deepmind/sonnet#117). The only real difference between `tf.Module` and `snt.Module` is that in Sonnet name scoping is opt out. We've taken a bit more time than we thought to actually open source the code, but we're working on that right now and I hope to have something public quite soon.
