### ISSUE TITLE
saving tensorflow models using hdf5 (without using a keras interface)

### ISSUE THREAD

**Issue by elham1992** [tensorflow/tensorflow#28301]
how to saving tensorflow models using hdf5 (without using a keras interface) ?

**Comment by captain-pool** [comment]
You can try this out 
https://geekyisawesome.blogspot.com/2018/06/savingloading-tensorflow-model-using.html?m=1

Hope this helps.

**Comment by muddham** [comment]
@elham1992  This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by muddham** [comment]
@elham1992 Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
