### ISSUE TITLE
[C API] cond op

### ISSUE THREAD

**Issue by melissagrueter** [tensorflow/tensorflow#28385]
**System information**
- TensorFlow version (you are using): master
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.** 
Feature: a cond operator for the C API, similar to [tf.cond](https://www.tensorflow.org/api_docs/python/tf/cond).

Current state: The C API currently includes the control flow primitives needed to implement cond, but it does not include the cond op itself. 

**Will this change the current api? How?**
The C API would include the cond op

**Who will benefit with this feature?**
All language bindings built on top of the C API could use its cond op, rather than having to individually implement their own from control flow primitives.

**Comment by melissagrueter** [comment]
Two questions:

-  I'd eventually like to use the cond op through the Java bindings. Since while loops are implemented at the C API level (rather than in the higher level language bindings using primitives), I assume we'd want to implement cond at the C API level too. Is this accurate? 

- given that control flow in TF is moving towards a functional representation, is it valuable to contribute the non-functional cond op to the C API? To me, it seems simplest to start by implementing the non-functional cond, and later move towards functional cond. Do you agree?

For reference, C API support for functional cond is discussed as future work in the cond_v2 design doc [here](https://github.com/tensorflow/community/blob/master/rfcs/20180507-cond-v2.md): "C API support. Ideally other language bindings support conditional execution as well. The C API already includes the primitives for other bindings to implement something similar to tf.cond that produces an If op, but the C API TF_AddGradients method would need to support If ops in order for other bindings to (easily) allow autodiff of conditionals."

**Comment by melissagrueter** [comment]
cc: @saxenasaurabh

**Comment by saxenasaurabh** [comment]
Thanks melissagrueter@, comments inlined. 

> I'd eventually like to use the cond op through the Java bindings. Since while loops are implemented at the C API level (rather than in the higher level language bindings using primitives), I assume we'd want to implement cond at the C API level too. Is this accurate?

Yes, implementing cond in the C API would make sense.

> given that control flow in TF is moving towards a functional representation, is it valuable to contribute the non-functional cond op to the C API? To me, it seems simplest to start by implementing the non-functional cond, and later move towards functional cond. Do you agree?

If `TF_AddGradients` supports taking gradients of low level control flow ops `Switch`, `Merge` etc. (I will need to look into this but maybe @skye already knows), then yeah we could go this route just to avoid dealing with functional op gradients for now. If not, we can look into the functional cond. I think the forward pass for functional cond would be much easier to implement than the non-functional one, and less prone to bugs, which tempts to try this in the first place but I am fine with either since it will still be strictly better than having no cond in the C API :)

**Comment by skye** [comment]
I'm pretty sure TF_AddGradients does not handle Switch and Merge. It's not as bad as while_loop, but the legacy cond gradient implementation is pretty complicated (e.g. see CondContext). It would be much better long-term to implement functional cond instead, although might take some short-term extra work because the C API only has very low-level support for functions. But I think it shouldn't be too crazy to do something similar to the TF_NewWhile API, and turn the branch TF_Graphs into functions instead of adding switch/merge nodes.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
