### ISSUE TITLE
Threadpool created by SingleThreadedCpuDevice 

### ISSUE THREAD

**Issue by snowpeakz** [tensorflow/tensorflow#28412]
Here we have a question about the threadpool created by SingleThreadedCpuDevice which could make sense on performance.
Each time the constructor of SingleThreadedCpuDevice is called, a threadpool with only one thread will be created.
 
  (single_threaded_cpu_device.cc:44)
```
  explicit SingleThreadedCpuDevice(Env* env)
      : Device(env, Device::BuildDeviceAttributes("/device:CPU:0", DEVICE_CPU,
                                                  Bytes(256 << 20),
                                                  DeviceLocality())) {
    eigen_worker_threads_.num_threads = kNumThreads;
    eigen_worker_threads_.workers = GraphRunnerThreadPool();
    eigen_device_.reset(new Eigen::ThreadPoolDevice(
        eigen_worker_threads_.workers->AsEigenThreadPool(),
        eigen_worker_threads_.num_threads));
    set_tensorflow_cpu_worker_threads(&eigen_worker_threads_);
    set_eigen_cpu_device(eigen_device_.get());
  }
```
 
As far as we know, a threadpool cost more than a thread, so why a SingleThreadedCpuDevice create a threadpoll instead of a thread?

**Comment by muddham** [comment]
@snowpeakz It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by muddham** [comment]
@snowpeakz Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
