### ISSUE TITLE
libcudart.so.7.5: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by 007fred50** [tensorflow/tensorflow#28436]
Hello,

I try to install tensorflow-gpu on my ubuntu machine.

i got this error here:
ImportError: libcudart.so.7.5: cannot open shared object file: No such file or directory

some one can help me ?

inside my ~/.bashrc
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64"
export CUDA_HOME=/usr/local/cuda

Installed:
Cuda 10.0
cuDNN 7.5.0

**Comment by muddham** [comment]
@007fred50  It looks like you haven't used a template to create this issue(tensorflow gpu  version used). Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.

**Comment by muddham** [comment]
@007fred50 Request you to please follow the [link1](https://github.com/tensorflow/models/issues/143), [link2](https://github.com/tensorflow/tensorflow/issues/1501).
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
