### ISSUE TITLE
TypeError: unhashable type: 'memmap'

### ISSUE THREAD

**Issue by ning3m** [tensorflow/tensorflow#28435]
When I want to use `tf.as_dtype` to convert a `numpy.memmap` data , the error was given. Is tensorflow not support this dtype? Or I shoulde use other function to convert my data to a type that tensorflow can recognize?

**Comment by ymodak** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
