### ISSUE TITLE
Tensor flow 2.0 and OpenCV usage

### ISSUE THREAD

**Issue by syedalamabbas** [tensorflow/tensorflow#28457]
Hi,
       I have already opened this issue in [Stack Overflow ](https://stackoverflow.com/questions/55986982/what-is-the-way-to-use-tensor-flow-2-0-object-in-open-cv2-python-and-why-is-it-s)but without much notice, I decided to add it here too. My question is related to usage of OpenCv operations like for instance in a train_step lets say I want to use an opencv function of remap - say undistort the output from a training model, then how do I do this in tensorflow ? Is this impossible as tensor flow object resides on GPU and calling an open cv operation requires a CPU copy and then a GPU push ? Is there already exists a provision through py_function  (I tried it) or something fancier ? Please advice.

**Comment by muddham** [comment]
@syedalamabbas This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by syedalamabbas** [comment]
@muddham  If you feel there is nothing you can add to the discussion about the issue since its already on Stack Overflow as my first post described, you may close it.

**Comment by muddham** [comment]
@syedalamabbas Since it is not a bug or feature request, this issue will be closed. Thanks!
