### ISSUE TITLE
Seek help 

### ISSUE THREAD

**Issue by Polaris-SDU** [tensorflow/tensorflow#28474]
I use tensorflow to train a end-to-end scene text recognition system. The training stage seems good. total_loss gradually declined until convergence. But when I load pretrained weight and use the same network to predict a picture. it reminds me:
###
FailedPreconditionError (see above for traceback): Attempting to use uninitialized value recognition_lstm/stack_bidirectional_rnn/cell_0/bidirectional_rnn/bw/lstm_cell/bias
###
Meanwhile  I run my demo.py and print(tf.global_variables()).
I found that some variables related to recognition part are not in tf.global_variables()
Why? Any help will be appreciated.

Here is my demo.py
#####################################################################
![2019-05-07 20-39-22屏幕截图](https://user-images.githubusercontent.com/34428575/57300316-2ae7f600-7109-11e9-87de-89123c56a123.png)
![2019-05-07 20-39-35屏幕截图](https://user-images.githubusercontent.com/34428575/57300329-320f0400-7109-11e9-912c-a434dcb658b0.png)
![2019-05-07 20-39-44屏幕截图](https://user-images.githubusercontent.com/34428575/57300338-363b2180-7109-11e9-93c6-57a2fbb196c6.png)

**Comment by muddham** [comment]
@Polaris-SDU It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
