### ISSUE TITLE
Low GPU utilization 

### ISSUE THREAD

**Issue by hn2** [tensorflow/tensorflow#28472]
I am running windows 10, core i7-8700 cpu, gtx geforce 1660 ti GPU.
When training models, gpu utilization is very low (5-10% at max, sometimes lower).
Even is network is five layers. CPU utilization on the other hand is 30% and above.

**Comment by muddham** [comment]
@hn2 This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
