### ISSUE TITLE
when I run my model in gpudelegate in android , it build crash

### ISSUE THREAD

**Issue by sunzhe09** [tensorflow/tensorflow#28507]
here is my bug message:

TfLiteGpuDelegate Prepare: Suitable node shader is not found: Output size is less than input size.Node number 129 (TfLiteGpuDelegate) failed to prepare.

my aar is tensorflow-lite-0.0.0-gpu-experimental.aar

**Comment by muddham** [comment]
@sunzhe09 This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by jvishnuvardhan** [comment]
@sunzhe09 
Please fill the issue [template](https://github.com/keras-team/keras/issues/new?template=a--tensorflow-backend-users.md). Could you update them if they are relevant in your case, or leave them as N/A? Along with the template, please provide as many details as possible to find the root cause of the issue. It would be great if you can provide a small code to reproduce the error. Thanks!
