### ISSUE TITLE
set_visible_device_list("") in c++ not work 

### ISSUE THREAD

**Issue by anhtu812** [tensorflow/tensorflow#28503]
I use tensorflow 1.12 cuda 9.0 build from source.
My code have follow lines, but session still use gpu. I not use CUDA_VISIBLE_DEVICES='' because my program have two session.
```
auto options = SessionOptions();
options.config.mutable_gpu_options()->set_visible_device_list("");
```

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by idealboy** [comment]
> I use tensorflow 1.12 cuda 9.0 build from source.
> My code have follow lines, but session still use gpu. I not use CUDA_VISIBLE_DEVICES='' because my program have two session.
> 
> ```
> auto options = SessionOptions();
> options.config.mutable_gpu_options()->set_visible_device_list("");
> ```

Have you solved this problem?I meet the same problem, and when I use this function, I still see all the gpu cards were occupied by tensorflow.

Thank you
