### ISSUE TITLE
Tutorials next_step page is giving 404

### ISSUE THREAD

**Issue by beingsagir** [tensorflow/tensorflow#28539]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/next_steps

## Description of the issue (what needs changing):
This page is not opening

### Clear description

Link is getting 404

### Request visuals, if applicable

![404     Page Not Found     TensorFlow](https://user-images.githubusercontent.com/1620769/57435595-65fa3e80-725b-11e9-81da-8394e7147ca7.png)

**Comment by jvishnuvardhan** [comment]
@beingsagir Where did you find the link to `next_steps`? Could you share that link? Thanks!

**Comment by beingsagir** [comment]
@jvishnuvardhan 
Please visit this link: [(https://www.tensorflow.org/tutorials/keras)]

**search for:** next steps.

**Comment by jvishnuvardhan** [comment]
@beingsagir Thanks for finding this missing link. In the coming weeks, TF website will be updated. There are lots of changes we are making that's why there are some missing links.
 
This missing link was updated in master [here](https://github.com/tensorflow/docs/blob/master/site/en/r2/tutorials/keras/index.md). When the TF website is updated, you don't see the last line 
`Additional TensorFlow and machine learning resources are listed in next steps.`

Thanks

**Comment by jvishnuvardhan** [comment]
Closing this issue. Thanks!
