### ISSUE TITLE
IDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.

### ISSUE THREAD

**Issue by hmchaitra** [tensorflow/tensorflow#28538]
**System information**
- OS Platform and Distribution Linux Ubuntu 16.04

- TensorFlow installed from pip:
- TensorFlow version 1.13:
- Python version 3.5:
- Installed using created virtualenvironment and then used ubuntu command to install :

- GPU model and memory   NVIDIA Corporation GT218 [GeForce 210] (rev a2)
 

# Install NVIDIA driver
apt-get install --no-install-recommends nvidia-410 .

to check this nvidia installation i used  
nvidia-smi 
command it ended up with above error message

https://www.tensorflow.org/install/gpu followedsame link

Is this issue is because the GPU version is not supported??
If so please to share the GPU compatible version and memory size

**Comment by muddham** [comment]
@hmchaitra This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
