### ISSUE TITLE
About slim.nets.inception_v3

### ISSUE THREAD

**Issue by menghuanlater** [tensorflow/tensorflow#28592]
I have read the function Inception_v3_base, I have questions about the code of Mixed_5b, 5c, 5d. The paper replaces the 5x5 convolution with 1x1 3x3 3x3, but why replace the original 1x1 3x3 combination with 1x1 5x5 in the code.

**Comment by menghuanlater** [comment]
not only this question, in line 242~251, the code named the scope as "conv2d_1a_1x1", but actually the code use 3x3 size

**Comment by muddham** [comment]
@menghuanlater This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
