### ISSUE TITLE
TypeError: '<' not supported between instances of 'list' and 'tuple'.

### ISSUE THREAD

**Issue by jiapei100** [tensorflow/tensorflow#28624]
I **git pull http directly** and **not git fork any more**...
So, I do **NOT** provide **pull request** for now.

A bug:
```
TypeError: '<' not supported between instances of 'list' and 'tuple'.
```

File **third_party/gpus/find_cuda_config.py**

Line 447:
```
    if cuda_version.split(".") < (10, 1):
```
to
```
    ver = cuda_version.split(".")
    ver1 = int(ver[0])
    ver2 = int(ver[1])
    if (ver1, ver2) < (10, 1):
```

BTW, I'm using **CUDA 10.1** 

Cheers
Pei

**Comment by gadagashwini** [comment]
@jiapei100 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
@jiapei100 
File **third_party/gpus/find_cuda_config.py**
### if cuda_version.split(".") < (10, 1):
modified to
###  if tuple(int(v) for v in cuda_version.split(".")) < (10, 1):

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
