### ISSUE TITLE
train.py

### ISSUE THREAD

**Issue by yangjinghit** [tensorflow/tensorflow#28655]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): git clone
- TensorFlow version: newest
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

./train.py
./train.py: line 68: --wanted_words: command not found
./train.py: line 68: rSimple speech recognition to spot a limited number of keywords.
why is that?how to solve it?

**Comment by muddham** [comment]
@yangjinghit Please provide the link for the mentioned train.py, to further investigate on this.Also please mention the tensorflow version( 1.13.1 or 2.0.0alpha) currently being used .

**Comment by muddham** [comment]
@yangjinghit It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
