### ISSUE TITLE
Can't Run code on ubuntu 18.04 

### ISSUE THREAD

**Issue by hariteja97** [tensorflow/tensorflow#28667]
I tried to run the code in my ubuntu system but couldn't run the code
can u suggest a way to run the code without gpu support and it would be great if u say with few proper steps

**Comment by muddham** [comment]
@hariteja97  It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
