### ISSUE TITLE
Why is the model file named as *00000-of-00001

### ISSUE THREAD

**Issue by zqp2009happy** [tensorflow/tensorflow#28688]
My variables model files is named as *00000-of-00002 or *00001-of-00002. My questions are:
1. What's the difference between them?
2. Why is the model file named as this pattern?
Thanks!

**Comment by muddham** [comment]
@zqp2009happy  It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. We will close this issue in lieu of the new one you will create from the template. Thank you for your cooperation.
