### ISSUE TITLE
tf.lite.TFLiteConverter.from_frozen_graph error

### ISSUE THREAD

**Issue by harsh020goyal** [tensorflow/tensorflow#28690]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- TensorFlow installed from (source or binary):source
- TensorFlow version (or github SHA if from source):1.13.1

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: CONCATENATION, CONV_2D, DEPTHWISE_CONV_2D, LOGISTIC, RESHAPE. Here is a list of operators for which you will need custom implementations: TFLite_Detection_PostProcess.

```

**Comment by SanthoshRajendiran** [comment]
Could you provide your pb file and the conversion command you used. Will be helpful for finding out the issue. Because, all the operators that you have mentioned are supported operators by TFLite.

**Comment by harsh020goyal** [comment]
I have download the model from the link as i mentioned below :+1: 
[http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_coco_2018_01_28.tar.gz](url)

the conversion program written in python which is shown below:


import tensorflow as tf

graph_def_file="./frozen_inference_graph.pb"
input_arrays=["image_tensor"]
output_arrays=["detection_boxes","detection_scores","num_detections","detection_classes"]
input_tensor={"image_tensor":[1,300,300,3]}

converter = tf.lite.TFLiteConverter.from_frozen_graph(graph_def_file, input_arrays, output_arrays,input_tensor)
converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,tf.lite.OpsSet.SELECT_TF_OPS]
tflite_model = converter.convert()
open("detect.tflite", "wb").write(tflite_model)

**Comment by SanthoshRajendiran** [comment]
Follow the steps in this repository
[https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md](
https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md)

**Comment by harsh020goyal** [comment]
If i am using that model whose link given below:
[http://download.tensorflow.org/models/object_detection/ssd_mobilenet_v1_quantized_300x300_coco14_sync_2018_07_18.tar.gz](url)
which is also a SSD mobilenetV1 model , It get successfully converted into tflite.So what is issue with the above first mentioned model which is also a SSD mobilenet model.

**Comment by Dayananda-V** [comment]
@harsh020goyal 

hi ,

as of now object detection model just supports **ssd mobilenet** versions using
 script [running_on_mobile_tensorflowlite][https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md] to tflite version. This script allows "add_postprocessing_op" parameter which resolve your problem which mentioned in issue.

`Here is a list of operators for which you will need custom implementations: TFLite_Detection_PostProcess.
`

Hope this resolve your issue.

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by chenyuZha** [comment]
@Dayananda-V @harsh020goyal 
 ``TFLite_Detection_PostProcess`` appears because when you frozen your graph, you use ``export_tflite_ssd_graph.py.py`` instead of ``export_inference_graph.py``, so that your input arrays become **normalized_input_image_tensor**, and your output arrays become **'TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'**.

Then to convert to tflite format, you can use either **bazel** or **tf.lite.TFLiteConverter**.
For the last method, the code snippet is like this:
``converter = tf.lite.TFLiteConverter.from_frozen_graph('your_graph.pb',input_shapes = {'normalized_input_image_tensor':(1,300,300, input_arrays = ['normalized_input_image_tensor'],output_arrays = ['TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'])
converter.allow_custom_ops=True tflite_model = converter.convert() tf_model_files = 'new.tflite' open(tf_model_files,"wb").write(tflite_model)``

**Comment by chauhansaurabhb** [comment]
@chenyuZha : Thanks for the solution. If anyone is looking for how to get the value of `input_shapes`, `input_arrays` and `output_arrays` then kindly upload your tflite graph to the [this](https://lutzroeder.github.io/netron/) link and you will find all parameters value.
