### ISSUE TITLE
Persistent colors on detected objects when using TFLite demo app

### ISSUE THREAD

**Issue by Symphonized** [tensorflow/tensorflow#28734]
<em>I would like persisent colors on detected objects when using the TFLite demo app on Android</em>

**System information**
- TensorFlow version (you are using): 1.13.1

- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Detected objects in the TFLite demo app show rectangles around them with a confidence number. These rectangles change color and make a certain use case I have rather difficult. I'd like the colors to be persisent, let's say I have 3 labels:
Label A - GREEN
Label B - RED
Label C - BLUE
and so on.

**Will this change the current api? How?**
I don't want to change the current API but I would appreciate a suggestion on how to change this.

**Who will benefit with this feature?**
I will.

**Any Other info.**
No.

**Comment by Dayananda-V** [comment]
@Symphonized 

Warning: As this doesn't appear to be a bug with Tensorflow, the better to may ask on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there.

This can be achieved on following code changes,
1. [Classifier.java](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/Classifier.java)
```
    public Recognition(
        final String id, final String title, final Float confidence, final RectF location, final int lablePos) {
      this.id = id;
      this.labelPos = lablePos;
      this.title = title;
      this.confidence = confidence;
      this.location = location;
    }

    private final int labelPos;
    public int getLablePosition() {
      return labelPos;
    }
```

2. [TFLiteObjectDetectionAPIModel.java](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tflite/TFLiteObjectDetectionAPIModel.java) 

```
      recognitions.add(
          new Recognition(
              "" + i,
              labels.get((int) outputClasses[0][i] + labelOffset),
              outputScores[0][i],
              detection,
                  (int) outputClasses[0][i] + labelOffset));
``` 
3. [MultiBoxTracker.java](https://github.com/tensorflow/examples/blob/master/lite/examples/object_detection/android/app/src/main/java/org/tensorflow/lite/examples/detection/tracking/MultiBoxTracker.java)

```
      if (potential.second.getLablePosition()  == 87) {//scissors [0 base index]
        trackedRecognition.color = Color.parseColor("#0D0068"); // CYAN for scissors 
      } else if (potential.second.getLablePosition()  == 33) {//suitcase
        trackedRecognition.color = Color.parseColor("#AA33AA"); // MAGENTA for suitcase 
      } else {
        trackedRecognition.color = COLORS[trackedObjects.size()];
      }
```

 Thanks!

**Comment by achandraa** [comment]
@Symphonized : Will it be possible to put some light on the feature you are proposing as in APIs that would get affected and the users who will be benefited with this change. Meanwhile you can also have a look on @Dayananda-V's suggestion. Thanks!

**Comment by Symphonized** [comment]
Thank you @Dayananda-V. Yes I realized this question might not suit the intended goal here. Thanks anyway for helping me find a solution even though it might have seemed trivial to you.

All the good.

Thanks.

**Comment by Symphonized** [comment]
> @Symphonized : Will it be possible to put some light on the feature you are proposing as in APIs that would get affected and the users who will be benefited with this change. Meanwhile you can also have a look on @Dayananda-V's suggestion. Thanks!
