### ISSUE TITLE
voice activity detection implementation

### ISSUE THREAD

**Issue by delowarcse** [tensorflow/tensorflow#28757]
I found that voice activity detection is implemented in the paper "Small-Footprint Keyword Spotting Using Deep Neural Networks". But I did not find anything related to voice activity detection in the paper "Convolutional Neural Networks for Small-footprint Keyword Spotting".
My question is that is voice activity detection implemented in this code or not?

**Comment by muddham** [comment]
@delowarcse Please provide the link for the paper mentioned here. Is this related to tensorflow.org website?

**Comment by delowarcse** [comment]
The paper title is "Convolutional Neural Networks for Small-footprint Keyword Spotting" and link is https://static.googleusercontent.com/media/research.google.com/en//pubs/archive/43969.pdf. This paper is implemented in Speech Commands Example and Link is https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/speech_commands. 

My question is that is voice activity detection implemented in this code or not?

**Comment by mustansarsaeed** [comment]
@delowarcse Were you able to detect voice activity using tensorflow lite?

**Comment by MeghnaNatraj** [comment]
Yes, it has been implemented in this code. The instructions are [here](https://github.com/tensorflow/docs/blob/master/site/en/r1/tutorials/sequences/audio_recognition.md).

You can also use this with TFLite micro. ([example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech), [training](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech/train))

The only issue is that it uses TensorFlow 1 (and not the latest TensorFlow 2 version), otherwise the code should work as per the instructions provided.
