### ISSUE TITLE
No gradients provided for any variable, check your graph for ops that do not support gradients while optimization

### ISSUE THREAD

**Issue by alphamuth** [tensorflow/tensorflow#28792]
ValueError: No gradients provided for any variable, check your graph for ops that do not support gradients, between variables ["<tf.Variable 'Variable:0' shape=(784, 500) dtype=float32_ref>"

this is coming up on using -  

optimizer = tf.train.AdamOptimizer(learning_rate=0.01).minimize(cost)

**Comment by muddham** [comment]
@alphamuth 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by muddham** [comment]
@alphamuth Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
