### ISSUE TITLE
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.

### ISSUE THREAD

**Issue by Anjnesh** [tensorflow/tensorflow#28827]
I'm working on a text analytics project and encountered this issue. I don't have much experience with this. Please assist. 

![image](https://user-images.githubusercontent.com/17949213/57971131-863aa380-79a7-11e9-90b8-ef8f2969aa1a.png)

**Comment by achandraa** [comment]
Deprecation messages means a particular service/component will not be there in future version as for example contrib is not there in TensorFlow version 2.0. For more information and better support for such issues, you can go to [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and can provide help faster for such issues. Thanks!
