### ISSUE TITLE
Add Tensorflow Lite GPU Delegates for the desktop

### ISSUE THREAD

**Issue by fire** [tensorflow/tensorflow#28830]
**System information**
- TensorFlow version (you are using): Tensorflow2.0alpha
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Tensorflow lite only has GPU delegates for iOS and Android devices.

In theory, Tensorflow lite should be able to use desktop Opengles apis through GLAD.

**Will this change the current api? How?**

This will use the existing interfaces for gpu delegates.

**Who will benefit with this feature?**

1. Tensorflow lite will be able to be gpu accelerated on desktops
1. Users of Tensorflow lite can have the same acceleration on the desktop and the mobile devices for ease of development.
1. Nvidia Tegra kits are a desktop-like platform that isn't an Android or iOS device but is able to run compute shaders.
1. Inference on the GPU may now run fast enough and now become suitable for real-time applications compared to the CPU.

**Comment by impjdi** [comment]
@fire 

Oh my apologies.  This issue somehow dropped from my radar, and I haven't responded for very long.

Yes, we have had successful running of the TFLite GPU on desktop with mesa.  It wasn't robust, e.g. I couldn't make it to run, but some of my colleagues were able to.

Our team is pretty short staffed, and have all our forces on supporting mobile devices.  And even so, we have trouble fixing Mali performance (which is going on for over a month now).  I'm sure we can somehow make it work for desktop, but that goes with supporting the community, and we just don't have the resources to do so.

For now, I will close this issue as infeasible.

**Comment by kingofthebongo2008** [comment]
I have here fixed gpu delegate to run on windows with angle library.

**Comment by fire** [comment]
Is it testable? Can you link to a git branch? I am interested.

**Comment by wolterlw** [comment]
Can anyone give a short summary of how tflite runs on GPU using mesa as used in Mediapipe project?

**Comment by fire** [comment]
![image](https://user-images.githubusercontent.com/32321/80245575-cf678e80-861f-11ea-83a8-80da530f77ad.png)

**Comment by impjdi** [comment]
Haha good one.  MediaPipe uses

`--copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11`

to bypass the X11 Status issue.

**Comment by magnusg-sa** [comment]
> I have here fixed gpu delegate to run on windows with angle library.

@kingofthebongo2008 is there any information on how to get this to work?

It feels like I am close to the solution but I must be missing something fundamental. I am quite new to most of the tools and concepts involved, but I managed to stitch together the following procedure:

1. Installed ANGLE according to https://chromium.googlesource.com/angle/angle/+/main/doc/DevSetup.md (COMMIT=596c2acfa5071eb643eaffe855a5ccb51c345427)

2. Built ANGLE libraries with following args (args.gn):
```
is_component_build = false
target_cpu = "x64"
is_debug = false
angle_assert_always_on = false
```

3. Added ANGLE build output directory (containing libEGL.dll, libEGL.dll.lib, libGLESv2.dll, libGLESv2.dll.lib, d3dcompiler_47.dll) to PATH environment variable.

4. Added ANGLE library dependency in bazel:

    1. In WORKSPACE file:
        ```
        new_local_repository(
            name = "angle",
            path = "../../../angle/angle/include",
            build_file_content = """
        package(default_visibility = ["//visibility:public"])
        cc_library(
            name = "headers",
            srcs = glob(["**/*.h"])
        )
        """
        )
        ```

    2. Added necessary dependencies (`copts = ["-Iexternal/angle"]` and `"@angle//:headers"`) to targets in bazel BUILD files (all targets that failed compilation due to missing OpenGL headers):
        
        Example:
        ```
        cc_library(
            name = "gl_errors",
            srcs = ["gl_errors.cc"],
            hdrs = ["gl_errors.h"],
            copts = ["-Iexternal/angle"],             <--- ADDED THIS
            deps = [
                "@angle//:headers",                   <--- ADDED THIS
                ":portable",
                "//tensorflow/lite/delegates/gpu/common:status",
                "@com_google_absl//absl/strings",
            ],
        )
        ```

    3. Updated .bazel to use '/std:c++latest'        
        ```
        ---build:windows --cxxopt=/std:c++17
        ---build:windows --host_cxxopt=/std:c++17
        +++build:windows --cxxopt=/std:c++latest
        +++build:windows --host_cxxopt=/std:c++latest
        ```

5. Build TensorFlow Lite GPU delegate (v2.10.0) //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
```
bazel2 build --local_cpu_resources=3 --features=windows_export_all_symbols -s -c opt --copt="-DMESA_EGL_NO_X11_HEADERS" --copt="-DEGL_NO_X11" //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so
```

But I get errors that I do not know how to mitigate.

```
ERROR: C:/users/magnusg/src/tensorflow_lite/tflite_2.10.0_gpu_delegate_build_bazel/tensorflow_src/tensorflow/lite/delegates/gpu/cl/kernels/BUILD:129:11: Compiling tensorflow/lite/delegates/gpu/cl/kernels/converter.cc failed: (Exit 2): cl.exe failed: error executing command
  cd /d C:/users/magnusg/_bazel_magnusg/4du655w4/execroot/org_tensorflow
  SET INCLUDE=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\include;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.8\include\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\ucrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\shared;C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\um;C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\winrt;C:\Program Files (x86)\Windows Kits\10\include\10.0.20348.0\cppwinrt
    SET PATH=C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\VC\VCPackages;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TestWindow;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\TeamFoundation\Team Explorer;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\bin\Roslyn;C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\devinit;C:\Program Files (x86)\Windows Kits\10\bin\10.0.20348.0\x64;C:\Program Files (x86)\Windows Kits\10\bin\x64;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\\MSBuild\Current\Bin;c:\Windows\Microsoft.NET\Framework64\v4.0.30319;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\Tools\;;C:\Windows\system32;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\Common7\IDE\CommonExtensions\Microsoft\CMake\Ninja
    SET PWD=/proc/self/cwd
    SET PYTHON_BIN_PATH=C:/Users/magnusg/anaconda3/envs/sa/python.exe
    SET PYTHON_LIB_PATH=C:/Users/magnusg/anaconda3/envs/sa/lib/site-packages
    SET RUNFILES_MANIFEST_ONLY=1
    SET TEMP=C:\Users\magnusg\AppData\Local\Temp
    SET TF2_BEHAVIOR=1
    SET TMP=C:\Users\magnusg\AppData\Local\Temp
    SET avariable=3
  C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\cl.exe @bazel-out/x64_windows-opt/bin/tensorflow/lite/delegates/gpu/cl/kernels/_objs/converter/converter.obj.params
# Configuration: 4692499b740a707abb55d09dbd7c915fbefe7b433a9f783356c086c94c980334
# Execution platform: @local_execution_config_platform//:platform
cl : Command line warning D9035 : option 'experimental:preprocessor' has been deprecated and will be removed in a future release
cl : Command line warning D9036 : use 'Zc:preprocessor' instead of 'experimental:preprocessor'
cl_version.h: CL_TARGET_OPENCL_VERSION is not defined. Defaulting to 300 (OpenCL 3.0)
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(526): error C2059: syntax error: '__cdecl'
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(532): error C2065: 'cl_command_buffer_khr': undeclared identifier
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(532): error C2165: 'left-side modifier': cannot modify pointers to data
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(532): error C2513: 'cl_int *': no variable declared before '='
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(535): error C2065: 'cl_command_buffer_khr': undeclared identifier
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(535): error C2165: 'left-side modifier': cannot modify pointers to data
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(535): error C2513: 'cl_int *': no variable declared before '='
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(538): error C2065: 'cl_command_buffer_khr': undeclared identifier
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(538): error C2165: 'left-side modifier': cannot modify pointers to data
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(538): error C2513: 'cl_int *': no variable declared before '='
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(542): error C2061: syntax error: identifier 'cl_command_buffer_khr'
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(547): error C2065: 'cl_command_buffer_khr': undeclared identifier
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(548): error C2275: 'cl_command_queue': illegal use of this type as an expression
external/angle\CL/cl.h(32): note: see declaration of 'cl_command_queue'
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(549): error C2059: syntax error: 'const'
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(559): error C2065: 'cl_command_buffer_khr': undeclared identifier
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(560): error C2065: 'cl_command_buffer_info_khr': undeclared identifier
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(560): error C2275: 'size_t': illegal use of this type as an expression
tensorflow/lite/delegates/gpu/cl/kernels/converter.cc: note: see declaration of 'size_t'
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(561): error C2062: type 'void' unexpected
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(682): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(682): error C2146: syntax error: missing ';' before identifier 'clCreateCommandBufferKHR'
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(687): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(687): error C2146: syntax error: missing ';' before identifier 'clCommandNDRangeKernelKHR'
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(688): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h(688): error C2146: syntax error: missing ';' before identifier 'clGetCommandBufferInfoKHR'
Target //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so failed to build
INFO: Elapsed time: 375.856s, Critical Path: 62.04s
INFO: 686 processes: 15 internal, 671 local.
FAILED: Build did NOT complete successfully
```

I do not know if I am on the right track and simply missing a minor detail or if I am missing the target completely. Any feedback would be helpful.

**Comment by kingofthebongo2008** [comment]
Run build from this command, cl.exe will be in the path

ERROR: C:/users/magnusg/src/tensorflow_lite/tflite_2.10.0_gpu_delegate_build_bazel/tensorflow_src/tensorflow/lite/delegates/gpu/cl/kernels/BUILD:129:11:
Compiling tensorflow/lite/delegates/gpu/cl/kernels/converter.cc
failed: (Exit 2): cl.exe failed: error executing command


[image: image.png]

**Comment by kingofthebongo2008** [comment]
Here command line option is wrong, i think, that you must change it somehow

cl : Command line warning D9035 : option 'experimental:preprocessor'
has been deprecated and will be removed in a future release
cl : Command line warning D9036 : use 'Zc:preprocessor' instead of
'experimental:preprocessor'

**Comment by magnusg-sa** [comment]
> Run build from this command, cl.exe will be in the path ERROR: C:/users/magnusg/src/tensorflow_lite/tflite_2.10.0_gpu_delegate_build_bazel/tensorflow_src/tensorflow/lite/delegates/gpu/cl/kernels/BUILD:129:11: Compiling tensorflow/lite/delegates/gpu/cl/kernels/converter.cc failed: (Exit 2): cl.exe failed: error executing command [image: image.png]

@kingofthebongo2008 I am not sure what you mean by _"Run build from this command"_? And did you provide some image `image.png` that is not displayed in your post?

I have tried re-running the build multiple times from the tensorflow source root directory. It compiles most of the ~1,111 files properly but it always fails on this `cl.exe` error for the file `.\tensorflow/lite/delegates/gpu/cl/opencl_wrapper.h` when it is ~30 files left to compile. It seems like it finds `cl.exe` at the path `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.28.29910\bin\HostX64\x64\cl.exe` but that `cl.exe` has trouble compiling `opencl_wrapper.h`.

Even though the error specifically says `syntax error: '__cdecl'` I cannot find any instances of `__cdecl` in the code.

I have seen that others get `cl.exe` errors when compiling tensorflow for Windows (e.g., [failed: (Exit 2): cl.exe failed: error executing command，Bazel=5.0.0, tf=2.8.0,MSVC2019](https://github.com/tensorflow/tensorflow/issues/54578)) but since I could compile TensorFlow Lite on Windows without a problem I thought my environment was set up correctly.

I have fixed the `experimental:preprocessor` warning but the problem remains.

Could it have something to do with `CL_TARGET_OPENCL_VERSION` defaulting to `300` (OpenCL 3.0)?

**Comment by ethening** [comment]
Thanks to the comments above, I have figured out how to make GPU delegates run on Windows with ANGLE.

We are at tensorflow commit e92261f, and we updated Bazel version to 6.3.0 in .bazelversion to support Visual Studio 2022.

First, I just checked out ANGLE library (commit 2ef85c2 for those interested) and built it according to https://github.com/google/angle/blob/main/doc/DevSetup.md.
When running `gn args out/Release`, config like below:
```
is_component_build = false
target_cpu = "x64"
is_debug = false
```
Then you could build with the `autoninja -C out/Release` command.
An error that I have encountered when building ANGLE, is due to CDB not being found. Somehow, downloading Windows SDK through Visual Studio Installer does not download every component you need. You could fix it by going to Windows > Apps & Features > Windows SDK > Change > Change. Check “Debugging Tools for Windows” and install.

Afterwards, you should be able to get the libs in `angle\out\Release\`. We would like to put the build results to the tensorflow repo to link against the TFLite GPU delegate library. I put these inside a directory in `tensorflow\third_party\angle\'

Copy these from `angle\out\Release\` to `tensorflow\third_party\angle\lib\windows_64\`:
    - `libEGL.dll`
    - `libEGL.dll.lib`
    - `libGLESv2.dll`
    - `libGLESv2.dll.lib`
- Copy whole `angle\include\` as `tensorflow\third_party\angle\include`.

Make a Bazel BUILD file (`tensorflow\third_party\angle\BUILD\`) in the  ANGLE directory. Content as follows:

```
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "headers",
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
)

cc_import(
    name = "libEGL",
    shared_library = "lib/windows_x64/libEGL.dll",
    interface_library = "lib/windows_x64/libEGL.dll.lib",
)

cc_import(
    name = "libGLESv2",
    shared_library = "lib/windows_x64/libGLESv2.dll",
    interface_library = "lib/windows_x64/libGLESv2.dll.lib",
)

cc_library(
    name = "libs",
    deps = [
        ":libEGL",
        ":libGLESv2",
    ],
)

cc_library(
    name = "angle",
    deps = [
        ":headers",
        ":libs",
    ],
)
```

Afterwards, we can start modifying the tensorflow repo BUILD files to correctly link the ANGLE together.

First, you want to tell the linker where to find the ANGLE library, which you add in the `deps` of the GPU delegate build target.

`tensorflow/lite/delegates/gpu/BUILD`:
```
:libtensorflowlite_gpu_delegate.so
cc_binary(
    name = "libtensorflowlite_gpu_delegate.so",
    linkopts = [
        "-Wl,-soname=libtensorflowlite_gpu_delegate.so",
    ] + gpu_delegate_linkopts() + select({
        "//tensorflow:windows": [],
        "//conditions:default": [
            "-fvisibility=hidden",
        ],
    }),
    linkshared = 1,
    linkstatic = 1,
    tags = [
        "nobuilder",
        "notap",
    ],
    deps = [":delegate"] + select({
        "//tensorflow:windows": [
            "//third_party/angle:libs"
        ],
        "//conditions:default": [],
    }),
)
```

The build command is always this: `bazelisk build -c opt --config=windows --copt -Os --copt -DTFLITE_GPU_BINARY_RELEASE --strip always //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so --verbose_failures --subcommands`
- `verbose_failures` and `subcommands` are used to debug
- You will run into multiple problems during the build, you could fix them one by one with the following.

`fatal error C1083: Cannot open include file: 'EGL/egl.h': No such file or directory`
- Adds dependency to "//third_party/angle:headers" whenever the EGL/egl.h error happens (e.g. api, egl_sync, egl_context, …)
- Should look something like this:
```
cc_library(
    name = "api",
    srcs = ["api.cc"],
    hdrs = ["api.h"],
    deps = [
        "//tensorflow/lite/delegates/gpu/common:data_type",
        "//tensorflow/lite/delegates/gpu/common:status",
        "//tensorflow/lite/delegates/gpu/common:util",
        "//tensorflow/lite/delegates/gpu/gl:portable",
        "@com_google_absl//absl/types:span",
        "@com_google_absl//absl/types:variant",
        "@opencl_headers",
        "@vulkan_headers//:vulkan_headers_no_prototypes",
    ] + select({
        "//tensorflow:windows": [
            "//third_party/angle:headers"
        ],
        "//conditions:default": [],
    }),
)
```

`tensorflow/lite/delegates/utils/sync_fence.cc(17): fatal error C1083: Cannot open include file: 'poll.h': No such file or directory`
- Could disable building `sync_fence` completely, it is not actually used if you are not building for Android.
```
cc_library_with_tflite(
    name = "sync_fence",
    srcs = select({
        "//tensorflow:windows": [], # <--- add this
        "//conditions:default": ["sync_fence.cc"],
    }),
    hdrs = ["sync_fence.h"],
    tflite_deps = [
        ":ret_macros",
    ],
    deps = [
        "//tensorflow/lite:minimal_logging",
        "@com_google_absl//absl/types:span",
    ],
)
```

`use of designated initializers requires C++20`
- Change `.bazelrc` from
```
build:windows --cxxopt=/std:c++17
build:windows --host_cxxopt=/std:c++17
```
to 
```
build:windows --cxxopt=/std:c++latest
build:windows --host_cxxopt=/std:c++latest
```

`.\tensorflow/lite/core/interpreter.h(1002): note: 'std::atomic_flag::atomic_flag(const std::atomic_flag &)': cannot convert argument 1 from 'bool' to 'const std::atomic_flag &'`
- Change `tensorflow/lite/core/interpreter.h` line from `std::atomic_flag continue_invocation_{false};` to `std::atomic_flag continue_invocation_{};`.

After doing all these patches, you should be able build successfully and get the build result in `bazel-bin/tensorflow/lite/delegates/gpu/libtensorflowlite_gpu_delegate.so`. If you still have build errors, unfortunately, you are on your own.

To use the GPU delegate, you would want to put the `libEGL.dll` and `libGLESv2.dll` in the same dir as the GPU delegate.
