### ISSUE TITLE
Support Stateful LSTM on TPU

### ISSUE THREAD

**Issue by maxima120** [tensorflow/tensorflow#28837]
<em>Cannot use LSTM model with tf.keras if Stateful = True on TPU</em>

**System information**
- TensorFlow version (you are using): 1.13

**Describe the feature and the current behavior/state.**
if I build tf.keras model and then try to convert to TPU model it gives: 

`WARNING:tensorflow:Model replication does not currently support stateful models.  Degrading to a single core.`

**Will this change the current api? How?**
unlikely

**Who will benefit with this feature?**
anyone to research time-series prediction

**Any Other info.**

**Comment by qlzh727** [comment]
I think RNN model will be supported on TPU after 2.0, TPU team is working it. Adding @xiejw from TPU team for status update.

**Comment by xiejw** [comment]
Sorry for the confusion. 

@qlzh727  This PR is about stateful RNN not just RNN.

I would like to provide some context here. 

The warning is accurate. It is supported but the code is using single TPU core for that, instead of 8 TPU cores. The code is working but it will not fully utilize the TPU power. 

The reason for that is: Keras uses TF variable to store the states for RNN.  However, the current TPU software stack does not have the infrastructure to have different variables for different TPU cores. This is mainly due to software limitation not hardware. The expected change to make that happen is quite large and we do not have near-term plan to work on that. 

With that, I will close this. And in future, if we have the bandwidth to solve this, will reopen.

**Comment by maxima120** [comment]
Is it so difficult to hardcode 8 sets of those variables (sorry I don't know how your TPU software stack looks like)? If so - *can Keras team help* by making it work differently when on TPUs?

And I am just curious - who is defining your priorities? Is it a popular vote or something? Like they voted for Trump and Brexit? You voted to cut TPUs out for anyone who doing ML on sequences and time-series? Fine.
