### ISSUE TITLE
Build Tensorflow Lite from source on Yocto Linux

### ISSUE THREAD

**Issue by nguyenhuy3588** [tensorflow/tensorflow#28863]
I have built a custom 32 bit Linux with [Yocto project](https://www.yoctoproject.org/), now i have a gcc toolchain that full support on c and c++ standard library, can i build Tensorflow Lite from source? Which dependencies will i have to install for a succesful build?

**Comment by geert56** [comment]
I did the same using tensorflow/lite/tools/make/Makefile on x86, ppc64le, and s390.
Use the dependencies as listed in download_dependencies.sh.
A few full tensorflow files are needed:
tensorflow/workspace.bzl is only needed for
tensorflow/lite/tools/make/download_dependencies.sh
(to pick up some download URLs)

tensorflow/core/util/ seems only needed to build benchmark_model
benchmark_model.h:
#include "tensorflow/core/util/stats_calculator.h"

Here is a listing of the files needed in tensorflow (apart from lite):
$ ls -la
       total 60
       drwxrwxr-x  4 geert geert  4096 May 15 15:26 .
       drwxrwxr-x  4 geert geert  4096 May 16 09:48 ..
       drwxrwxr-x  5 geert geert  4096 Apr 19 09:41 core
       drwxrwxr-x 22 geert geert  4096 May 13 13:52 lite
       -rwxrwxr-x  1 geert geert 44212 Apr 19 09:36 workspace.bzl

$ ls -laR core
       core:
       total 20
       drwxrwxr-x 5 geert geert 4096 Apr 19 09:41 .
       drwxrwxr-x 4 geert geert 4096 May 15 15:26 ..
       drwxrwxr-x 2 geert geert 4096 Apr 18 17:19 kernels
       drwxrwxr-x 2 geert geert 4096 Apr 18 17:15 public
       drwxrwxr-x 2 geert geert 4096 May 13 13:54 util

       core/kernels:
       total 72
       drwxrwxr-x 2 geert geert  4096 Apr 18 17:19 .
       drwxrwxr-x 5 geert geert  4096 Apr 19 09:41 ..
       -rw-rw-r-- 1 geert geert 62142 Mar 15 17:26 eigen_spatial_convolutions-inl.h

       core/public:
       total 16
       drwxrwxr-x 2 geert geert 4096 Apr 18 17:15 .
       drwxrwxr-x 5 geert geert 4096 Apr 19 09:41 ..
       -rw-rw-r-- 1 geert geert 6088 Mar 15 17:27 version.h

       core/util:
       total 32
       drwxrwxr-x 2 geert geert 4096 May 13 13:54 .
       drwxrwxr-x 5 geert geert 4096 Apr 19 09:41 ..
       -rw-rw-r-- 1 geert geert 9732 Mar 15 17:27 stats_calculator.cc
       -rw-rw-r-- 1 geert geert 5724 Mar 15 17:27 stats_calculator.h
       -rw-rw-r-- 1 geert geert 1397 Mar 15 17:27 stat_summarizer_options.h

**Comment by nguyenhuy3588** [comment]
it's amazing, thanks @geert56 , i will try with my toolchain now.

**Comment by achandraa** [comment]
@geert56 : Thanks you for providing the support
@nguyenhuy3588 : Let us know if you are able to resolve it. Thanks!

**Comment by nguyenhuy3588** [comment]
Hi @achandraa will i need to separately compile library dependencies downloaded by ownload_dependencies.sh?

I successfully compile object file for the source in tensorflow/lite but got some undefined reference error when creating libtensorflow-lite.a, like so:

> /home/xxxx/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include/flatbuffers/base.h:356: undefined reference to `flatbuffers::ClassicLocale::instance_' 
/home/xxxx/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a(if.o): In function `flexbuffers::Indirect(unsigned char const*, unsigned char)':

**Comment by nguyenhuy3588** [comment]
I face this problem when compile with ubuntu default environtment too.

Forgot to mention, i change the CXX_FLAGS from:

> CXXFLAGS := -O3 -DNDEBUG -fPIC
CXXFLAGS += $(EXTRA_CXXFLAGS)

to only this:

> CXXFLAGS := -O3 -DNDEBUG -fPIC -pipe -g -feliminate-unused-debug-types

for not typing so many each time but i think this's not a problem.

**Comment by XiaYuanxiang** [comment]
> Hi @achandraa will i need to separately compile library dependencies downloaded by ownload_dependencies.sh?
> 
> I successfully compile object file for the source in tensorflow/lite but got some undefined reference error when creating libtensorflow-lite.a, like so:
> 
> > /home/xxxx/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include/flatbuffers/base.h:356: undefined reference to `flatbuffers::ClassicLocale::instance_'  /home/xxxx/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a(if.o): In function `flexbuffers::Indirect(unsigned char const*, unsigned char)':

Hello，Did you solved this problem？

**Comment by ggardet** [comment]
> > Hi @achandraa will i need to separately compile library dependencies downloaded by ownload_dependencies.sh?
> > I successfully compile object file for the source in tensorflow/lite but got some undefined reference error when creating libtensorflow-lite.a, like so:
> > > /home/xxxx/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include/flatbuffers/base.h:356: undefined reference to `flatbuffers::ClassicLocale::instance_'  /home/xxxx/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a(if.o): In function `flexbuffers::Indirect(unsigned char const*, unsigned char)':
> 
> Hello，Did you solved this problem？

Same problem for me. If someone has a patch, I can test it.

**Comment by nguyenhuy3588** [comment]
> > > Hi @achandraa will i need to separately compile library dependencies downloaded by ownload_dependencies.sh?
> > > I successfully compile object file for the source in tensorflow/lite but got some undefined reference error when creating libtensorflow-lite.a, like so:
> > > > /home/xxxx/tensorflow/tensorflow/lite/tools/make/downloads/flatbuffers/include/flatbuffers/base.h:356: undefined reference to `flatbuffers::ClassicLocale::instance_'  /home/xxxx/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a(if.o): In function `flexbuffers::Indirect(unsigned char const*, unsigned char)':
> > 
> > 
> > Hello，Did you solved this problem？
> 
> Same problem for me. If someone has a patch, I can test it.

I still can't solve it, waiting for Tensorflow for help.

**Comment by thotaram** [comment]
Hi,
Building tensorflow lite for ARM64 with the below link
https://www.tensorflow.org/lite/guide/build_arm64
Dependencies are resolved.
Changed the Makefile to build for arm(./tensorflow/lite/tools/make/build_aarch64_lib.sh)
Makefile Changes:
TARGET := aarch64
TARGET_ARCH := armv8-a
when i run this file ./tensorflow/lite/tools/make/build_aarch64_lib.sh getting the below error.

/home/xxxxx/ARMNN/tensorflow_lite_build/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/benchmark-lib.a(test_main.o): In function `main':
test_main.cc:(.text.startup+0x48): undefined reference to `testing::InitGoogleTest(int*, char**)'
test_main.cc:(.text.startup+0x250): undefined reference to `tflite::SingleOpModel::SetForceUseNnapi(bool)'
test_main.cc:(.text.startup+0x25c): undefined reference to `testing::UnitTest::GetInstance()'
test_main.cc:(.text.startup+0x260): undefined reference to `testing::UnitTest::Run()'
collect2: error: ld returned 1 exit status
tensorflow/lite/tools/make/Makefile:284: recipe for target '/home/xxxxx/ARMNN/tensorflow_lite_build/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/benchmark_model' failed
make: *** [/home/xxxxx/ARMNN/tensorflow_lite_build/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/benchmark_model] Error 1
make: *** Waiting for unfinished jobs....
/home/xxxxx/ARMNN/tensorflow_lite_build/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(while.o): In function `tflite::ops::custom::while_kernel::Init(TfLiteContext*, char const*, unsigned long)':
while.cc:(.text+0x1d04): undefined reference to `flatbuffers::ClassicLocale::instance_'
while.cc:(.text+0x1d18): undefined reference to `flatbuffers::ClassicLocale::instance_'
while.cc:(.text+0x1d6c): undefined reference to `flatbuffers::ClassicLocale::instance_'
while.cc:(.text+0x1d78): undefined reference to `flatbuffers::ClassicLocale::instance_'
/home/xxxxxx/ARMNN/tensorflow_lite_build/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(audio_spectrogram.o): In function `tflite::ops::custom::audio_spectrogram::Init(TfLiteContext*, char const*, unsigned long)':
audio_spectrogram.cc:(.text+0xf00): undefined reference to `flatbuffers::ClassicLocale::instance_'
/home/xxxxxx/ARMNN/tensorflow_lite_build/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/lib/libtensorflow-lite.a(audio_spectrogram.o):audio_spectrogram.cc:(.text+0xf0c): more undefined references to `flatbuffers::ClassicLocale::instance_' follow
collect2: error: ld returned 1 exit status
tensorflow/lite/tools/make/Makefile:270: recipe for target '/home/aiiec/ARMNN/tensorflow_lite_build/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal' failed
make: *** [/home/xxxxx/ARMNN/tensorflow_lite_build/tensorflow/tensorflow/lite/tools/make/gen/aarch64_armv8-a/bin/minimal] Error 1

Please give your inputs how to resolve it.
By going in deep analysis the issue is with google test library. Please find the below link to build it.
https://stackoverflow.com/questions/13513905/how-to-setup-googletest-as-a-shared-library-on-linux
Changed the Makefile by including "-lgtest" at line 60
CXXFLAGS := -O3 -DNDEBUG -fPIC -flax-vector-conversions -fomit-frame-pointer -lgtest

Error:
/usr/lib/gcc-cross/aarch64-linux-gnu/5/../../../../aarch64-linux-gnu/bin/ld: cannot find -lgtest
collect2: error: ld returned 1 exit status

Please give some information to overcome this issue.

Thanks in advance.

**Comment by yaysummeriscoming** [comment]
I'm also getting this flatbuffers::ClassicLocale::instance_ error.  This error comes up on both my Raspberry Pi & my ODroid N2 ARM64 boards.  I use the same build instructions as @thotaram

**Comment by thotaram** [comment]
Hi @achandraa 
Did you resolve the below issue
while.cc:(.text+0x1d04): undefined reference to flatbuffers::ClassicLocale::instance_' while.cc:(.text+0x1d18): undefined reference to flatbuffers::ClassicLocale::instance_'
while.cc:(.text+0x1d6c): undefined reference to flatbuffers::ClassicLocale::instance_' while.cc:(.text+0x1d78): undefined reference to flatbuffers::ClassicLocale::instance_'

Can you please help me how to resolve it.

Thanks.

**Comment by kn0t3k** [comment]
I had the same problem, solved it by adding
/tensorflow/lite/tools/make/downloads/flatbuffers/src/idl_gen_cpp.cpp
/tensorflow/lite/tools/make/downloads/flatbuffers/src/code_generators.cpp
/tensorflow/lite/tools/make/downloads/flatbuffers/src/idl_gen_general.cpp
/tensorflow/lite/tools/make/downloads/flatbuffers/src/idl_parser.cpp
/tensorflow/lite/tools/make/downloads/flatbuffers/src/reflection.cpp
/tensorflow/lite/tools/make/downloads/flatbuffers/src/util.cpp
to my app sources

**Comment by thotaram** [comment]
@kn0t3k 
Hi,
Thank you for your feedback.
Can you please send the tensorflow source code path where to add these .cpp files.

**Comment by kn0t3k** [comment]
> 
> 
> @kn0t3k
> Hi,
> Thank you for your feedback.
> Can you please send the tensorflow source code path where to add these .cpp files.

Its not about tensorflow build, you have to add those file to your app CMakeLists.txt or whatever your using, they contain the neccesary symbols

the path is relative to tensorflow root dir

**Comment by ggardet** [comment]
@thotaram, my workaround is to install `libflatbuffers` on the system and apply this patch to tensorflow-lite to use the system `libflatbuffers`:
```
--- tensorflow-1.13.1/tensorflow/lite/tools/make/Makefile.orig  2019-06-04 13:13:08.329080620 +0200
+++ tensorflow-1.13.1/tensorflow/lite/tools/make/Makefile       2019-06-04 16:05:13.325963284 +0200
@@ -38,11 +38,12 @@ INCLUDES := \
 -I$(OBJDIR)
 # This is at the end so any globally-installed frameworks like protobuf don't
 # override local versions in the source tree.
-INCLUDES += -I/usr/local/include
+INCLUDES += -I/usr/include
 
 # These are the default libraries needed, but they can be added to or
 # overridden by the platform-specific settings in target makefiles.
 LIBS := \
+-lflatbuffers \
 -lstdc++ \
 -lpthread \
 -lm \
```

**Comment by thotaram** [comment]
@ggardet 
Thank you for your prompt response.

I have build the flatbuffers source code and copied the library files to /usr/lib.
and included 
 LIBS := \
+-lflatbuffers \

Still am getting the error: undefined reference to `flatbuffers::ClassicLocale::instance_'

I think if you cross build(ARM64) the tensorflow lite source code, Can you please help me or any document you have followed to build it.

**Comment by TrungLM13** [comment]
> Hi @achandraa
> Did you resolve the below issue
> while.cc:(.text+0x1d04): undefined reference to flatbuffers::ClassicLocale::instance_' while.cc:(.text+0x1d18): undefined reference to flatbuffers::ClassicLocale::instance_'
> while.cc:(.text+0x1d6c): undefined reference to flatbuffers::ClassicLocale::instance_' while.cc:(.text+0x1d78): undefined reference to flatbuffers::ClassicLocale::instance_'
> 
> Can you please help me how to resolve it.
> 
> Thanks.

I have the same problem, please help

**Comment by vizero1** [comment]
@kn0t3k @ggardet 
Have the same issue. Could you please explain your workaround a bit more in detail? From your answer its not very clear how to resolve that issue.
Thanks in advance

**Comment by TrungLM13** [comment]
Hello @vizero1 
Please look for more detail of #29626. I think it can help you to resolve some problem.

**Comment by vizero1** [comment]
@TrungLM13 so you could only compile tf lite with version v1.12.2(with the workaround of disabling NNAPI)?

**Comment by TrungLM13** [comment]
> @TrungLM13 so you could only compile tf lite with version v1.12.2(with the workaround of disabling NNAPI)?

yes.

**Comment by thotaram** [comment]
Hello All,
Has any one tried building the entire tensorflow source code instead of tensorflow lite?
Could you please provide any web link or steps to cross compile entire tensorflow source code for ARM64.
Thanks in advance.

**Comment by arnaldog12** [comment]
I have instructions for building tensorflow v1.4 (not lite) for android, @thotaram:
https://github.com/arnaldog12/Tensorflow-Build-MT/tree/master/v1.4/android

I hope it helps.

**Comment by thotaram** [comment]
Hi All,
TF lite is build successfully.
While importing the tensorflow on board, am getting the below error.
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'tensorflow'

I would like to know how to import interpreter function?
tf.lite.interpreter instead is there any way to use tflite interpreter directly? because "import tensorflow" is not working.

Any one tried running label_image.py files on target board?
Thanks inadvance.

**Comment by jaden-young** [comment]
@thotaram See https://www.tensorflow.org/lite/guide/python#run_an_inference_using_tflite_runtime

**Comment by Saduf2019** [comment]
@ nguyenhuy3588
Could you please verify on the latest tf version and let us know if this is still an issue as many bugs have been fixed since this has been reported.
