### ISSUE TITLE
ValueError: Attempt to convert a value (<6x6 sparse matrix of type '<class 'numpy.float64'>' 	with 1 stored elements in COOrdinate format>) with an unsupported type (<class 'scipy.sparse.coo.coo_matrix'>) to a Tensor.

### ISSUE THREAD

**Issue by AmandaCSantos** [tensorflow/tensorflow#28925]
I am building a recommendation model using the WALS algorithm and implementing it in Tersorflow. I have processed the data and when I try to initialize the object I get the error below. 

ValueError: Attempt to convert a value (<6x6 sparse matrix of type '<class 'numpy.float64'>'
	with 1 stored elements in COOrdinate format>) with an unsupported type (<class 'scipy.sparse.coo.coo_matrix'>) to a Tensor.

`input_tensor = tf.SparseTensor(indices=list(zip(tr_sparse.row, tr_sparse.col)),
                                values=(tr_sparse).astype(np.float64),
                                dense_shape=tr_sparse.shape)`

**Comment by gadagashwini** [comment]
@AmandaCSantos Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
