### ISSUE TITLE
mfcc

### ISSUE THREAD

**Issue by yangjinghit** [tensorflow/tensorflow#28954]
preprocess: Spectrogram processing mode. Can be "mfcc" or "average".

what is average?

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Closing this issue since the associated PR has been merged. Feel free to reopen if the problem still persists. Thanks!
