### ISSUE TITLE
fatal error LNK1000: Internal error during CImplib::EmitThunk

### ISSUE THREAD

**Issue by fmmohammadi** [tensorflow/tensorflow#28955]
**System information**
- Windows 10
- TensorFlow installed from (source or binary): source
- C++ Visual Studio 2015 Update 3
- GPU model and memory: NO USE

**Describe the problem**

Hi,
I have a Static library project, containing some codes that are using Tensorflow as Additional Dependencies.
I want to make a static libray (name "`myLib.lib`") from these codes to use in another Win32 App.
In my static library project, I used `/WHOLEARCHIVE` flag to include all tensorflow's lib files to the my final static library, `myLib.lib` file.
I build it and make `myLib.lib` file.
In another Win32 App I link this `myLib.lib` to use it and also use `/WHOLEARCHIVE:myLib.lib` as a Additional options in Linker->Command Line.
But when I run this win32app, I got the error:

`fatal error LNK1000: Internal error during CImplib::EmitThunk`

I searched many topics but I didn't find any appropriate solution. I totaly confused. What should I do?

I have to say that I added `/WHOLEARCHIVE` flag in order to prevent error `No session factory registered for the given session options` when using Tensorflow.

**Comment by ZLeopard** [comment]
i encounter this too, do you have some metheds to solve it. i build tensorflowr1.13.0 with bazel.

**Comment by ZLeopard** [comment]
@fmmohammadi

**Comment by fmmohammadi** [comment]
No idea ??

**Comment by muddham** [comment]
@fmmohammadi Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by fmmohammadi** [comment]
@muddham @ZLeopard 
After tons of searching I found that the problem is because of Visual Studio 2015. As mentioned [here](https://support.microsoft.com/en-us/help/4020481/fix-link-exe-crashes-with-a-fatal-lnk1000-error-when-you-use-wholearch) the cause of problem is:

> This problem occurs in rare cases because Link.exe might not handle import objects and incremental linking correctly if it uses the /WHOLEARCHIVE switch.

And the solution is to download and install a hotfix (vc14-kb4020481.exe) from [here](https://download.microsoft.com/download/8/1/d/81dbe6bb-ed92-411a-bef5-3a75ff972c6a/vc14-kb4020481.exe).

**Comment by muddham** [comment]
@fmmohammadi Glad to hear that your issue was resolved.Hence this issue will be closed.
