### ISSUE TITLE
faild to retrain the Inception v3 model.

### ISSUE THREAD

**Issue by berylyellow** [tensorflow/tensorflow#29038]
![2019-05-26 18-12-22 的屏幕截图](https://user-images.githubusercontent.com/36025537/58380553-033bcd80-7fe5-11e9-88d5-1d6486a4ef6b.png)

**Comment by berylyellow** [comment]
@ry @jmhodges @eggie5 @bmabey  Hi~My network is okay, why I occur this? Thanks.

**Comment by gadagashwini** [comment]
@berylyellow  Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
