### ISSUE TITLE
TFLite model almost the same size as frozen graph

### ISSUE THREAD

**Issue by hoonkai** [tensorflow/tensorflow#29089]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): v1.13.1
- Python version: 3.6
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: n/a
- GPU model and memory: n/a

**Describe the current behavior**

Freeze [xception65_coco_voc_trainaug](http://download.tensorflow.org/models/deeplabv3_pascal_train_aug_2018_01_04.tar.gz) from this [model zoo](https://github.com/tensorflow/models/blob/master/research/deeplab/g3doc/model_zoo.md) using:
```
python tensorflow/models/deeplab/export_model.py ...
```

Resulting `.pb` is 157mb.

Convert `.pb` to `.tflite` using `tflite_convert`. Resulting `.tflite` is 156mb. Just 1mb smaller than the `.pb`.

**Describe the expected behavior**

The TFLite model should perhaps be considerably smaller. If not, why not?

[The frozen graph I'm using](https://drive.google.com/file/d/14usyseWBL36SGNdYPm17D07OQ1P_5Hjx/view?usp=sharing)

**Comment by gargn** [comment]
This is expected behavior because the model contains the same number of weights and ops. If you are interested in reducing the model size then please reference our [FAQ](https://www.tensorflow.org/lite/guide/faq#how_do_i_reduce_the_size_of_my_converted_tensorflow_lite_model). We also have the [model optimization toolkit](https://www.tensorflow.org/model_optimization) which was recently launched.
