### ISSUE TITLE
Hard-coding "1" for CUDA version breaks existing MacOS GPU build with CUDA 7.5

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#2910]
Commit https://github.com/tensorflow/tensorflow/commit/f45874b4a969a60fa9ced86e6769012e4912b5ca broke existing GPU builds on MacOS with CUDA 7.5

It nows fails
`I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:1078] failed to find libcuda.so on this system: Failed precondition: could not dlopen DSO: libcuda.1.dylib; dlerror: dlopen(libcuda.1.dylib, 5): image not found
`
A work-around is to create a symlink
```
cd /usr/local/cuda/lib/
ln -s libcuda.dylib libcuda.1.dylib

```

**Comment by vrv** [comment]
cc @3XX0 and @rdadolf 

life is hard

**Comment by flx42** [comment]
It was `libcuda.so.1` previously too:
https://github.com/tensorflow/tensorflow/commit/d0a822fbcb04d95a643d8efe65699a8d1cdce98b
But then the `.1` suddenly disappeared here:
https://github.com/tensorflow/tensorflow/commit/8bf6ef1337359993a8be057c0dc90da8f5a6e4fa

**Comment by vrv** [comment]
I think the .1 makes more sense, so I'd rather someone figure out a way to special-case this for OS X rather than change it back.

**Comment by rdadolf** [comment]
@vrv What fun would life be without incompatible versioning?

So it seems like this is coming from mutual incompatibility in nvidia's tools.

On the OS X cuda 7.5 default install, most of the libraries exist in `/Developer/NVIDIA/CUDA-7.5/lib`, and these are symlinked into `/usr/local/cuda/lib`. There is actually only one non-symlinked file, which is `/usr/local/cuda/lib/libcuda.dylib`. There are no version numbers on it (as @yaroslavvb pointed out).

In the `nvidia/cuda:7.5-cudnn4-devel` docker image (which TensorFlow's docker image is built from), the cuda libraries are in `/usr/local/nvidia/lib64`, and there are two files: `libcuda.so.1` and `libcuda.so.352.63`.

So it looks like any solution will not be confined to `dso_loader.cc`.

I see two solutions:

1. Decide the canonical name of libcuda is "libcuda.<extension>". Revert f45874b. Add a line to the tensorflow dockerfile which creates a symlink from `.1.so` to `.so`.

2. Decide the canonical name of libcuda is "libcuda.<extension>.1". Make users symlink on install or convince nvidia to add another symlink to their installer. The former seems unwieldy, and the latter seems unlikely to happen.

3. Add a TF_LIBCUDA_VERSION configuration variable. Users wouldn't actually have to configure this, if @3XX0 is correct in that it won't change. There's already system-dependent checks in [configure](https://github.com/tensorflow/tensorflow/blob/05df7e3cea808f26931370f099b0c4352375afce/configure#L181), so we could add another that simply generates a ".1" for linux and a "" for OS X. Then we add a third function along with [GetCudaVersion](https://github.com/tensorflow/tensorflow/blob/d0a822fbcb04d95a643d8efe65699a8d1cdce98b/tensorflow/stream_executor/dso_loader.cc#L40) and GetCudnnVersion, which will end up getting text-substituted [just like the other two](https://github.com/tensorflow/tensorflow/blob/14ac2235699509f512b44b71160239c153ab413d/configure#L238). This doesn't actually make it any more safe (because we're just moving the hardcoded number into the configure script instead of the `dso_loader.cc`), but it does give tensorflow more control over where to look for things instead of trying to rely solely on nvidia's tools.


I think 3 sounds more reasonable than the other two. I can probably work up the pull request if this seems like a viable plan for everyone.

**Comment by 3XX0** [comment]
Why am I not surprised...

We decided to hardcode the `libcuda.so` symlink inside `nvidia-docker` because too many things are broken without it, so reverting is one solution. Fixing cuDNN is a must have though.

Otherwise, as @rdadolf pointed out you could have two functions `GetCudaDriverVersion` and `GetCudaVersion` which would return the cuda version (e.g. "7.5) and "1" (**"" for OSX**) respectively.

**Comment by vrv** [comment]
@3XX0: Can you clarify what things TensorFlow should do and what needs to be fixed elsewhere?  I've seen your comments in other github threads but I've had trouble understanding what your full set of recommendations is (for cuda, cudnn, etc).

Also @zheng-xq for TF opinions

**Comment by zheng-xq** [comment]
I agree add ".1" for OSX is a good idea. 

Adding the stream-executor owner, @henline here.

**Comment by rdadolf** [comment]
So adding ".1" isn't really a solution inside TensorFlow, it's a solution that nvidia or the user would have to do alongside TF. It basically means adding @yaroslavvb's symlink workaround as part of the official install instructions. I.E., whenever a user installs a version of cuda on a Mac (including upgrading versions), they'd have to also add the symlink manually. I'm not sure this should really be part of the TF install scripts, since it's modifying previously-installed libraries. Adding it into `configure` is probably not a good idea, and it would probably require sudo-invoking the configure script (since the cuda libraries could be in system locations).

The third solution I pitched is sort of a compromise. The dso loader now wouldn't care about the particulars of the system-dependent behavior of libcuda, and it's no less portable than before (because libcudnn and libcudart already require it). I wrote up a [patch](https://github.com/rdadolf/tensorflow/commit/9255c1e75f7c3f9185293c31d8ca655664055afb) which implements this. I can certainly submit it as a pull request if you like. (But until #2865 is resolved, we'll have to check the CI tests manually to see if it works.)

@3XX0 I guess my other question is why the nvidia cuda installer *doesn't* create a libcuda.1.dylib and symlink it. Every other file is done this way, and you believe that [libcuda.dylib is not the correct name](https://github.com/NVIDIA/nvidia-docker/blob/master/tools/src/nvidia/volumes.go#L263). Is this a bug in the installer?

**Comment by 3XX0** [comment]
@rdadolf  Yes this is totally our fault. I will try to escalate this issue internally to our OSX packaging team but in the meantime your patch is the only (clean) way to solve it.

@vrv I guess this answers your question for libcuda.
For libcudnn, I talked about it [here](https://github.com/tensorflow/tensorflow/issues/2525#issuecomment-223523008). In short, it would be nice to detect the libcudnn soname and set it by default in the configure script.
Otherwise, if users try to run a precompiled version of Tensorflow where cudnn hasn't been configured with the script (e.g. the Tensorflow Docker runtime image), it will fail when it tries to look for `libcudnn.so`. Precompiled Tensorflow should be looking for `libcudnn.so.<soname it has been compiled with>`

**Comment by vrv** [comment]
(I think I fixed all I could safely do in a bunch of other commits.  Just waiting for the cuda mac install to do the right thing).

**Comment by jucor** [comment]
Hi guys. Fresh Xoogler here, I think we talked when my ldap was jucor@. Quick update on this: I've just installed TF r0.11 on OSX 10.11.3 in a virtualenv with Cuda 8.0.47 and cuDNN 8.0-5.1, and I had the same error as @yaroslavvb. Bad news: manually symlinking `libcuda.so` to `libcuda.1.so` was still necessary. Good news: it was also sufficient.
