### ISSUE TITLE
TFL GPU gpu::gl::reshape Is attr redundant?

### ISSUE THREAD

**Issue by mun3** [tensorflow/tensorflow#29207]
I'm trying to write a few test cases for `gl::reshape` and noticed that `attr` appears to be of not much use. The only use I can find is [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/gl/kernels/reshape.cc#L49-L52):

```
    if (attr.new_shape != output->tensor.shape) {
      return InvalidArgumentError(
          "Dimensions for output does not match new_shape attribute");
    }
```

But `attr.new_shape` always take the tensor shape of the output ([here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/model_builder.cc#L811)). Under what circumstances, if any, would the matching `attr.new_shape` against `output->tensor.shape` fail?

**Comment by muddham** [comment]
@mun3 This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!
