### ISSUE TITLE
[XLA]support of async xlaop kernel  

### ISSUE THREAD

**Issue by LogX2** [tensorflow/tensorflow#29240]
**System information**
- TensorFlow version (you are using):
r1.14
- Are you willing to contribute it (Yes/No):
YES

**Describe the feature and the current behavior/state.**
in the current tf version, there are two types of ops: OpKernel and AsyncOpKernel, but in the xla module, the only xlaop type is XlaOpKernel, which is a sync interface. For most of xlaops, this method works fine, but when it comes to some async op like horovod all reduce op, which derived from AsyncOpKernel in the tfop, this sync interface  will not work. I gonna to learn if it is possible to add a async xla op kernel type? if these idea is contradicted to the original design of XLA module, thanks for letting me know.    
**Will this change the current api? How?**
no
**Who will benefit with this feature?**
anyone who want to add a async op in xla
**Any Other info.**

**Comment by jlebar** [comment]
cc @sanjoy.  (I also want to cc Tres, but I can't find his github handle...)

I don't quite understand what you're trying to accomplish by way of this feature request.

Are you hoping to implement Horovod all-reduce *inside of XLA*?  (Note that XLA recently grew NCCL all-reduce support, which I understand is not the same thing.)

**Comment by sanjoy** [comment]
Apart from what Justin said, `XlaOpKernel` is a "symbolic execution" kernel whose only job is to generate HLO instructions for TF nodes.  So it does not make sense for the `XlaOpKernel` class itself to allow async execution since it is only ever called by the TF->XLA compiler.  Now we may have to make a change to XLA itself to represent Horovod all-reduce and associated asynchronicity depending on the details, but that does not have anything to do with `XlaOpKernel`.

**Comment by LogX2** [comment]
Thanks for your update, i'm implementing this and looking forward to a good result. 
And  with your explanation, i think this issue should be closed.
