### ISSUE TITLE
[TF 2.0] - freeze_graph not working with converted keras to tensorflow serving model using tf.keras.experimental.export_savedmodel

### ISSUE THREAD

**Issue by vsriram23** [tensorflow/tensorflow#29253]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution : Linux Ubuntu 16.04
- TensorFlow installed from: binary
- TensorFlow version (use command below): 2.0
- Python version: 3.6
- CUDA/cuDNN version: 10.0
- GPU model and memory:

**Describe the current behavior**
Model saved as tf.keras .hdf5 converted to tensorflow model using  tf.keras.experimental.export_savedmodel and when using freeze_graph to get a single .pb file running into error 

**Describe the expected behavior**

**Code to reproduce the issue**
```python
import tensorflow as tf
model_path = '/home/vsrira10/Desktop/model.hdf5'
model = tf.keras.models.load_model(model_path)
tf.keras.experimental.export_savedmodel(model,newdir)
```
After this a variables folder with files [checkpoint,variables.data-00000-of-00001,variables.index], saved_model.pb and assests folder created in newdir.

I am trying to use saved_model.pb and variables.data-00000-of-00001 files to get single .pb frozen_graph
**Other info / logs**
python /home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py --input_graph=/home/vsrira10/Desktop/tf_models/saved_model.pb --input_checkpoint=/home/vsrira10/Desktop/tf_models/variables/variables.data-00000-of-00001 --output_graph=/home/vsrira10/Desktop/tf_models/frozen_graph.pb --output_node_names=classes,corners --input_binary=true
Traceback (most recent call last):
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 492, in <module>
    run_main()
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 489, in run_main
    app.run(main=my_main, argv=[sys.argv[0]] + unparsed)
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 488, in <lambda>
    my_main = lambda unused_args: main(unused_args, flags)
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 382, in main
    flags.saved_model_tags, checkpoint_version)
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 341, in freeze_graph
    input_graph_def = _parse_input_graph_proto(input_graph, input_binary)
  File "/home/vsrira10/anaconda2/envs/tf2/lib/python3.6/site-packages/tensorflow/python/tools/freeze_graph.py", line 252, in _parse_input_graph_proto
    input_graph_def.ParseFromString(f.read())
google.protobuf.message.DecodeError: Error parsing message

**Comment by gargn** [comment]
This is expected behavior. `freeze_graph` is not supported in 2.0. It will be removed from the pip in the near future.

**Comment by vsriram23** [comment]
If freeze_graph is not supported what should I use instead?

**Comment by vsriram23** [comment]
> This is expected behavior. `freeze_graph` is not supported in 2.0. It will be removed from the pip in the near future.
If freeze_graph is not supported what should I use instead?

**Comment by gargn** [comment]
In 2.0, the primary export format is [SavedModels](https://www.tensorflow.org/alpha/guide/saved_model) so APIs are built to directly support SavedModels. Inference on existing frozen graphs can be run using the `v1.compat` path.

If there is a tool that is currently not supporting SavedModels in 2.0, please report that as a separate issue.

**Comment by iLeW** [comment]
I'll try to comment here about this post:

> This is expected behavior. `freeze_graph` is not supported in 2.0. It will be removed from the pip in the near future.

Well, I need to use freeze_graph to have a saved model compatible with opencv cv::dnn::readNetFromTensorflow in C++. Have you have ever considered this situation? What are your plans to continue supporting this?

Thank you.

**Comment by Oktai15** [comment]
Also, coreml doesn't work with TF 2.0 now, only with frozen graph. But I need to convert my model to it.

**Comment by vade** [comment]
Seriously, this is kind of crazy.

An entire ecosystem was built around using protocol buffers - none of those tools work with TF 2.0 since TF 2.0 can't export PB's as far as I can tell, especially if TF 2.0 has bug fixes for models that won't export properly from TF 1.14 - 

So right now I

* can build a  model in TF 1.14 or 2.0
* Cant export said model Keras h5 since it used TF.Layers rather than Keras layers
* Cant export a PB since said model has  some weird bug thats yet to be fixed in TF 1.1.4
* Cant export a PB in 2.0 runtime, using 1.x combat runtime in TF 2.0 triggers the TF 1.x bug.
* Cant export SavedModel format to any other format
* SavedModel PB defaults to some very weird SERVING PB which, I never asked for.
* Tensorflow project doesn't provide a method of back porting a SavedModel to a PB in an external tool.

I guess I can't use TF?

**Comment by CharlieBickerton** [comment]
@efournie I've been wresting with this issue for a while and I've been able to convert a freeze_session.py from 1.X to 2.0. If you are still changing environments this technique back help you. Tensorflow 2.0 allows you access to the 1.X functions but you just have to call them differently, rather than saving the weights and then converting you should be able to directly convert the model after training. Scroll down to see the freeze function and then how I can it post training.

Here is my freeze session function:

`def freeze_session(session, keep_var_names=None, output_names=None, clear_devices=True):
    """
    Freezes the state of a session into a pruned computation graph.

    Creates a new computation graph where variable nodes are replaced by
    constants taking their current value in the session. The new graph will be
    pruned so subgraphs that are not necessary to compute the requested
    outputs are removed.
    @param session The TensorFlow session to be frozen.
    @param keep_var_names A list of variable names that should not be frozen,
                          or None to freeze all the variables in the graph.
    @param output_names Names of the relevant graph outputs.
    @param clear_devices Remove the device directives from the graph for better portability.
    @return The frozen graph definition.
    """
    graph = session.graph
    with graph.as_default():
        freeze_var_names = list(set(v.op.name for v in tf.compat.v1.global_variables()).difference(keep_var_names or []))
        output_names = output_names or []
        output_names += [v.op.name for v in tf.compat.v1.global_variables()]
        input_graph_def = graph.as_graph_def()
        if clear_devices:
            for node in input_graph_def.node:
                node.device = ""
        frozen_graph = tf.compat.v1.graph_util.convert_variables_to_constants(
            session, input_graph_def, output_names, freeze_var_names)
        return frozen_graph`

Which I call using:
`import tensorflow.python.keras.backend as K
frozen_graph = freeze_session(K.get_session())
tf.compat.v1.train.write_graph(frozen_graph, save_model_dir, "frozen_model.pb", as_text=False)
`

**Comment by hahadashi** [comment]
> g them to an untrained m

i try to convert ckpt model to pb model under tf2.0
.   when i run them, but their result is different
