### ISSUE TITLE
[TF 2.0 API Docs] tf.data.experimental.Optional

### ISSUE THREAD

**Issue by skalagarla** [tensorflow/tensorflow#29289]
## URL(s) with the issue:

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/Optional

### Usage example

No usage example provided

**Comment by ymodak** [comment]
This is fixed with TF 2.3 API update https://www.tensorflow.org/api_docs/python/tf/experimental/Optional
`tf.data.experimental.Optional` is deprecated and `tf.experimental.Optional` is exposed in the API. Thanks!
https://github.com/tensorflow/tensorflow/blob/9edbe5075f79a4a95ed14a2be831f9b59e61f49d/tensorflow/python/data/ops/optional_ops.py#L36
