### ISSUE TITLE
Please provide the list of supported hardware architectures (and/or build options) for the pre-built library

### ISSUE THREAD

**Issue by KocsisV** [tensorflow/tensorflow#29357]
## URL(s) with the issue:
https://www.tensorflow.org/install/lang_c
## Description of issue (what needs changing):
There is no mention on this page what options were used to build the library files.
For example the lib ("Linux GPU support") requires cuda 6.0 compute architecture (or above) which is not mentioned. While the pip package runs fine on 3.0 or above.
Or which CPU instructions sets/extensions are supported and which are required (minimum).
It would be good if all of these were mentioned alongside the download link.

I just run into this issue using a GPU with compute architecture 3.7, and TF says it ignores the device because it was not built to support that architecture. It also gives me an info message about the lib not built with SSE4.1 SSE4.2 AVX AVX2 FMA in mind.

**Comment by gadagashwini** [comment]
Hi @KocsisV, 
You can get the minimum Hardware requirements to install Tensorflow from [here](https://www.tensorflow.org/install/pip#hardware_requirements). 
<img width="934" alt="Screen Shot 2022-06-28 at 12 54 06 PM" src="https://user-images.githubusercontent.com/99852755/176118768-2794a9fc-1740-43fe-b42a-c99ddd4e1e4a.png">

Thank you!

**Comment by KocsisV** [comment]
Documentation is still incomplete.. Check [https://www.tensorflow.org/install/lang_c](https://www.tensorflow.org/install/lang_c),  you linked the PIP package's page, which is a completely different release type.
Last time (3 years ago) the this library supported a different set of compute architectures than what the pip package does (what you just linked). Don't know if this is still the case or not. And the lang_c page does not mention any GPU requirements / list of supported compute levels.
I don't have a ready to use environment anymore to test the c_lang package's ([libtensorflow-gpu-linux-x86_64-2.8.0.tar.gz](https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-linux-x86_64-2.8.0.tar.gz) GPU support anymore.
And neither the PIP package, nor the c_lang library lists the supported CPU instruction sets.

I hope the next response won't take 3 more years.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by KocsisV** [comment]
I moved away from using TF a long time ago, I won't provide any more information regarding this issue.
