### ISSUE TITLE
get sequence length when use tf.dataset

### ISSUE THREAD

**Issue by policeme** [tensorflow/tensorflow#29378]
@ry @jmhodges @eggie5 @bmabey @djones 
I want to get sequence length, when use tf.dataset, but when I got next batch, the length still [?, ?],
I want to know the second element, but as I saw, tf.dataset don't support, Is I wrong or tf.dataset still not support this? Could anyone tell me the reason.

**Comment by policeme** [comment]
![image](https://user-images.githubusercontent.com/30991932/58847564-ffc7d680-86b5-11e9-8dff-6e7aafd73532.png)
this is my code

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact code snippet required to replicate the issue included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by policeme** [comment]
Thx,i found way to slove this


from Alimail iPhone
 ------------------Original Mail ------------------

**Comment by achandraa** [comment]
Great..Will close the issue since it is resolved. Thanks!
