### ISSUE TITLE
tf.gather_nd replacement

### ISSUE THREAD

**Issue by gbc8181** [tensorflow/tensorflow#29419]
Hi,

I am doing a project but their tensorflow, but the hardware does not support tf.gather_nd. I am asking if possible that use tf.gather, tf.slice or tf.strided_slice to rewrite a function of tf.gather_nd?

Thanks,
Peter

**Comment by gadagashwini** [comment]
@gbc8181 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gbc8181** [comment]
> @gbc8181 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
> 
> Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
> 
> We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

Hi,

I checked with the administer. The Tensor-flow is 1.08. Since they have very special hardware thus they cannot support tf.gather_nd. Now the method is can we use tf.gather to realize the function of tf.gather_nd. 

Thanks

**Comment by gadagashwini** [comment]
This is not Bug/Performance issue or Build/Installation. Please post this kind of support questions at [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
