### ISSUE TITLE
[TF 2.0 API Docs]tf.data.experimental.shuffle_and_repeat

### ISSUE THREAD

**Issue by pronapro** [tensorflow/tensorflow#29441]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/data/experimental/shuffle_and_repeat

### Clear description

No.
it has warning and it is kinda abstract on when to use the function

### Raises listed and defined
No.
yet while comparing  dataset.shuffle(buffer_size, reshuffle_each_iteration=True).repeat(count).the difference is in the actions performed on the datasets. 

### Usage example
No.
there is need of an example to clearly explain the difference between the two shuffles

**Comment by ymodak** [comment]
The docs are updated in TF 2.4.1 https://www.tensorflow.org/api_docs/python/tf/data/experimental/shuffle_and_repeat
Since `tf.data.experimental.shuffle_and_repeat` function is deprecated we may want to refer [`tf.data.Dataset.shuffle(buffer_size, seed)`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#shuffle) and [`tf.data.Dataset.repeat(count)`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#repeat) to know more about the usage.
Thanks!
