### ISSUE TITLE
How to run  keras model using tensor flow JNI interface in java

### ISSUE THREAD

**Issue by Arpit-Mittal** [tensorflow/tensorflow#29475]
This is python model which is working good in python:

https://github.com/keras-team/keras/tree/master/examples

lstm_seq2seq.py Trains a basic character-level sequence-to-sequence model.
lstm_seq2seq_restore.py Restores a character-level sequence to sequence model from disk (saved by lstm_seq2seq.py) and uses it to generate predictions.

Do you know if there is way to convert to java?

I used below code to import python model -
 
SavedModelBundle model = SavedModelBundle.load(
                "DIR",
                "serve");
 
i got below exceptions:
org.tensorflow.TensorFlowException: Could not find SavedModel .pb or .pbtxt at supplied export directory path.

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and can provide better support for such issues. Meanwhile you can have a look on this [link](https://towardsdatascience.com/deploying-keras-deep-learning-models-with-java-62d80464f34a). This might help. Thanks!

**Comment by Arpit-Mittal** [comment]
DeepLearning4j is not working for me. If you know any way to convert below models to java Let me know.

Below are 2 models:
https://github.com/keras-team/keras/tree/master/examples

lstm_seq2seq.py Trains a basic character-level sequence-to-sequence model.
lstm_seq2seq_restore.py Restores a character-level sequence to sequence model from disk (saved by lstm_seq2seq.py) and uses it to generate predictions.

**Comment by achandraa** [comment]
Since the issue at hand is not related to bug/build/feature request, we need to direct the same to[ StackOverflow](https://stackoverflow.com/questions/tagged//tensorflow) for better and faster resolution. However, you can have a look on this [link](https://stackoverflow.com/questions/35712182/running-a-python-program-in-java-using-jython) also which might be of some help to you. Thanks!
