### ISSUE TITLE
how can fix the problem "Memory cannot be recycled" in  my web service  build by tensorflow + flask 

### ISSUE THREAD

**Issue by johnsonyep** [tensorflow/tensorflow#29483]
**### This is my code:**

```
import numpy as np
from flask import Flask, request
import tensorflow as tf

from tensorflow.python.platform import gfile
from app.utils.log_util import LogUtils
log = LogUtils.get_stream_logger(__name__)

app = Flask(__name__)

with gfile.FastGFile('../20190517-152605.pb', 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    
graph = tf.Graph()
with graph.as_default():
    tf.import_graph_def(graph_def, input_map=None, name='')
    # print(tf.get_default_graph().as_graph_def().node)
    images_placeholder = tf.get_default_graph().get_tensor_by_name("input:0")
    embeddings = tf.get_default_graph().get_tensor_by_name("embeddings:0")
    phase_train_placeholder = tf.get_default_graph().get_tensor_by_name("phase_train:0")
    model = {
        'images_placeholder': images_placeholder,
        'embeddings': embeddings,
        'phase_train_placeholder': phase_train_placeholder
    }

sess = tf.Session(graph=graph)

@app.route('/', methods=['POST'])
def classify():
    log.info('ss')
    # data = request.files.get('data').read()
    face = np.load("test.npy")
    images_placeholder = model['images_placeholder']
    embeddings = model['embeddings']
    phase_train_placeholder = model['phase_train_placeholder']
    result = sess.run(embeddings, feed_dict={images_placeholder: face, phase_train_placeholder: False})
    print(result)
    return str(200)
app.run(host='127.0.0.1',port=12480)
```
memory grow situation :
request times: |1 | 2 |4 ... |100 ... n
memory: |400+MB |600+MB | 700MB ... |2GB ... 2GB

- OS Platform :  ubuntu 18.04
- TensorFlow installed from (source or binary): pipenv pypi
- TensorFlow version (use command below):  1.13.1
- Python version: 3.6.4
- run at cpu

**Comment by gadagashwini** [comment]
@johnsonyep Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
@johnsonyep Could you provide more details about the issue and context?

**Comment by gadagashwini** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
