### ISSUE TITLE
How to convert a tensorlfow SpaceToBatchND-Conv2D-BatchToSpaceND to a single Conv2D in tflite

### ISSUE THREAD

**Issue by lwu025** [tensorflow/tensorflow#29509]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):NO
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:NA
- TensorFlow installed from (source or binary):source
- TensorFlow version (use command below):1.13.1
- Python version: 2.7
- Bazel version (if compiling from source): 0.22.0
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
I'm trying to train my own deeplab model using this [code](https://github.com/tensorflow/models/tree/master/research/deeplab) and convert it to tflite.
My target is to get a model similar to [this](https://storage.googleapis.com/download.tensorflow.org/models/tflite/gpu/deeplabv3_257_mv_gpu.tflite)

However, the model is obtained contains operations like:
![image](https://user-images.githubusercontent.com/43549654/59057361-135a7500-884f-11e9-9546-e2bd20e69c95.png)
SpaceToBatchND and BatchToSpaceND operations are not supported by tflite + opengles backend, they reduced the model's performance on my device.

In your hosted deeplab model, those three ops are replaced by DEPTHWISE_CONV_2D v2, which has options to set dilation factor. This would be the best solution for me but I'm not sure how to convert SpaceToBatchND-Conv2D-BatchToSpaceND into a singe DEPTHWISE_CONV_2D v2(dilation=2).

FYI, I have tried the graph_transforms tool under tensorflow/tools/graph_transforms to flatten the atrous conv. It upsampled the kernels instead of Space_To_Batch + Batch_To_Space. But this transform leads to much more computations that I cannot afford.

**Describe the expected behavior**

convert SpaceToBatchND-Conv2D-BatchToSpaceND into a singe DEPTHWISE_CONV_2D v2(dilation=2)

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

You can try any model under deeplab model zoo for example [http://download.tensorflow.org/models/deeplabv3_mnv2_ade20k_train_2018_12_03.tar.gz](url)

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by normandra** [comment]
Hey, I am currently facing the same problem. One thing that I noticed is when working with quantized model this conversion is being done. Problem is then I end up with a uint8 model.

**Comment by depthwise** [comment]
I'm seeing the same issue in TF 2.0.0 and TF2.1.0. This makes e.g. Deeplab V3 effectively not runnable on GPU as it relies extensively on atrous convolutions.

**Comment by haozha111** [comment]
> I'm seeing the same issue in TF 2.0.0 and TF2.1.0. This makes e.g. Deeplab V3 effectively not runnable on GPU as it relies extensively on atrous convolutions.

Are you using the old converter or the new MLIR-based converter?

**Comment by depthwise** [comment]
Seems to happen regardless of which converter is chosen. I can ask my client to provide an untrained SavedModel as a repro, if that helps.

**Comment by depthwise** [comment]
I'm pretty sure it would repro with segmentation specific variant of MobileNet V3, i.e. this one: https://github.com/1e100/mobilenet_v3/blob/master/mobilenet_v3_keras.py, using "large_segmentation" config: https://github.com/1e100/mobilenet_v3/blob/master/mobilenet_v3_configs.py#L69.

**Comment by depthwise** [comment]
This is where it bails in my case (in `identify_dilated_conv.cc`):
```
120   Operator* bias_add_op = !has_bias_before_bts ? final_op : next_op;
121   if (bias_add_op->type != OperatorType::kAdd) {
122     // Bias op is required before or after BatchToSpace
123     return false;
124   }
```

**Comment by depthwise** [comment]
Upon export, a _dilated_ MobileNet V3 block turns into this:
![dilated_bug](https://user-images.githubusercontent.com/46361887/72696297-7eac3b00-3af0-11ea-8cf6-d45bfc7e40be.png)
In its original form, the block is defined as follows: https://github.com/1e100/mobilenet_v3/blob/master/mobilenet_v3_keras.py#L155

**Comment by depthwise** [comment]
It expects that there will be bias add either before or after BatchToSpaceNd, but it looks like the bias is folded into DepthwiseConv2D. What that Mul is doing there, I don't know.

**Comment by depthwise** [comment]
Minimal repro:
```python3
#!/usr/bin/env python3

import pathlib

import tensorflow as tf
from tensorflow import keras

input = keras.Input([128, 128, 3])
x = keras.layers.Conv2D(8, 5, dilation_rate=2, padding="same", use_bias=False)(input)
x = keras.layers.BatchNormalization()(x)
output = keras.layers.ReLU()(x)

m = keras.Model(inputs=input, outputs=output)
out_dir = pathlib.Path("/tmp/minimal_bug_repro")
m.save(str(out_dir), save_format="tf")

converter = tf.lite.TFLiteConverter.from_saved_model(str(out_dir))
tflite_model = converter.convert()
output_file = out_dir / "model.tflite"
output_file.write_bytes(tflite_model)

print(f"Converted model was written to {output_file}")
```
You get the following on the other end:
![minimal_repro_bug](https://user-images.githubusercontent.com/46361887/72698007-1b71d700-3af7-11ea-9176-bf05f210c17d.png)
Which is not runnable on the GPU.

**Comment by haozha111** [comment]
Thanks @depthwise for the repro example.

I'm working on adding support of dilated conv into the MLIR-based converter. I will update this thread when I'm finished.

**Comment by depthwise** [comment]
FYI, @haozha111, this PR improved the issue, but did not fully fix it. Here's an updated repro which demonstrates the remaining issue:
```
#!/usr/bin/env python3

import pathlib

import tensorflow as tf
from tensorflow import keras

input = keras.Input([128, 128, 3])
x1 = keras.layers.Conv2D(8, 5, dilation_rate=6, padding="same", use_bias=False)(input)
x1 = keras.layers.BatchNormalization()(x1)
output1 = keras.layers.ReLU()(x1)

x2 = keras.layers.Conv2D(8, 5, dilation_rate=12, padding="same", use_bias=False)(input)
x2 = keras.layers.BatchNormalization()(x2)
output1 = keras.layers.ReLU()(x2)

output = tf.concat([x1, x2], axis=3)

m = keras.Model(inputs=input, outputs=output)
out_dir = pathlib.Path("/tmp/minimal_bug_repro")
m.save(str(out_dir), save_format="tf")

converter = tf.lite.TFLiteConverter.from_saved_model(str(out_dir))
tflite_model = converter.convert()
output_file = out_dir / "model.tflite"
output_file.write_bytes(tflite_model)

print(f"Converted model was written to {output_file}")
```

This produces the following:

![minimal_repro2](https://user-images.githubusercontent.com/46361887/73354717-3bb63a00-424b-11ea-9767-5762e6863f05.png)

Each of the convs in isolation is fixed, but if I concatenate them we're back to the status quo ante.

**Comment by depthwise** [comment]
Such dilations are commonly used in the ASPP module of segmentation models.

**Comment by haozha111** [comment]
That's a bit interesting. I haven't tested for this case.

So do you mean if you have only one conv2d in your graph, then it can be correctly folded?

**Comment by depthwise** [comment]
Looks like conv2d's by themselves work fine. The simpler repro I posted before looks "correct", although I have not tested this in a full blown, trained model yet.

**Comment by haozha111** [comment]
I tested with your new code, and convert it. Then I'm getting the tflite graph looks like the following:
![mum9U9Ewi6y](https://user-images.githubusercontent.com/6316921/73408979-bbc3ba80-42b2-11ea-91ab-46f8a05219f5.png)

I also have the corresponding tflite file, but not sure how to attach it here.

This suggests that the graph is converted as expected. I'm wondering if my previous change has been pushed into the nightly already. Maybe you can download tomorrow's nightly and give a try.

**Comment by depthwise** [comment]
OK, I'll try again. My example was converted using a build directly from master as of last night. Maybe something else got submitted in the interim.

**Comment by haozha111** [comment]
did you set converter.experimental_new_converter = True between those two lines?

`converter = tf.lite.TFLiteConverter.from_saved_model(str(out_dir))
tflite_model = converter.convert()`

**Comment by depthwise** [comment]
I'm actually converting as follows, using the master branch as of this afternoon:
```bash
bazel run --copt="-Wno-unused-result" :tflite_convert -- --saved_model_dir=/tmp/minimal_bug_repro --experimental_new_converter=True --output_file=/tmp/minimal_bug_repro/model.tflite
```
The original savedmodel is created with TF 2.1.0 release version, the conversion is done with `master` `tflite_convert`.

Here's the original model and its conversion, in case it's useful in debugging: https://storage.googleapis.com/depthwise-temp/minimal_bug_repro.zip

**Comment by depthwise** [comment]
For me the graph looks like the image I posted previously, incorrect.

**Comment by haozha111** [comment]
I could reproduce the issue with your saved model, but the graph I posted before is from the keras testing code. I'm not sure why there is a difference here.

Digging it further, I found that there is a difference in the MLIR representation of the two models. For saved model, the IR looks like:
...
  %10 = "tf.Identity"(%arg0) {T = f32, device = ""} : (tensor<1x128x128x3xf32>) -> tensor<1x128x128x3xf32>
  %11 = "tf.Identity"(%10) {T = f32, device = ""} : (tensor<1x128x128x3xf32>) -> tensor<1x128x128x3xf32>
  %12 = "tf.SpaceToBatchND"(%11, %0, %1) {T = f32, Tblock_shape = i32, Tpaddings = i32, device = ""} : (tensor<1x128x128x3xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<36x26x26x3xf32>
  %13 = "tf.SpaceToBatchND"(%11, %3, %4) {T = f32, Tblock_shape = i32, Tpaddings = i32, device = ""} : (tensor<1x128x128x3xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<144x15x15x3xf32>
  %14 = "tf.Conv2D"(%12, %8) {T = f32, data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true} : (tensor<36x26x26x3xf32>, tensor<5x5x3x8xf32>) -> tensor<36x22x22x8xf32>
  %15 = "tf.BatchToSpaceND"(%14, %0, %2) {T = f32, Tblock_shape = i32, Tcrops = i32, device = ""} : (tensor<36x22x22x8xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<1x128x128x8xf32>
  %y, %batch_mean, %batch_variance, %reserve_space_1, %reserve_space_2, %reserve_space_3 = "tf.FusedBatchNormV3"(%15, %6, %7, %7, %6) {T = f32, U = f32, data_format = "NHWC", device = "", epsilon = 1.000000e-03 : f32, is_training = false} : (tensor<1x128x128x8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<8xf32>) -> (tensor<1x128x128x8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<*xf32>)
  %16 = "tf.Conv2D"(%13, %9) {T = f32, data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true} : (tensor<144x15x15x3xf32>, tensor<5x5x3x8xf32>) -> tensor<144x11x11x8xf32>
  %17 = "tf.BatchToSpaceND"(%16, %3, %2) {T = f32, Tblock_shape = i32, Tcrops = i32, device = ""} : (tensor<144x11x11x8xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<1x128x128x8xf32>
  %18 = "tf.Mul"(%17, %cst) : (tensor<1x128x128x8xf32>, tensor<8xf32>) -> tensor<1x128x128x8xf32>
  %19 = "tf.Add"(%18, %cst_0) : (tensor<1x128x128x8xf32>, tensor<8xf32>) -> tensor<1x128x128x8xf32>
  %20 = "tf.ConcatV2"(%y, %19, %5) {N = 2 : i64, T = f32, Tidx = i32, _cloned = true, device = ""} : (tensor<1x128x128x8xf32>, tensor<1x128x128x8xf32>, tensor<i32>) -> tensor<1x128x128x16xf32>
  return %20 : tensor<1x128x128x16xf32>
}<144x11x11x8xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<1x128x128x8xf32>
  %18 = "tf.Mul"(%17, %cst) : (tensor<1x128x128x8xf32>, tensor<8xf32>) -> tensor<1x128x128x8xf32>
  %19 = "tf.Add"(%18, %cst_0) : (tensor<1x128x128x8xf32>, tensor<8xf32>) -> tensor<1x128x128x8xf32>
  %20 = "tf.ConcatV2"(%y, %19, %5) {N = 2 : i64, T = f32, Tidx = i32, _cloned = true, device = ""} : (tensor<1x128x128x8xf32>, tensor<1x128x128x8xf32>, tensor<i32>) -> tensor<1x128x128x16xf32>
  return %20 : tensor<1x128x128x16xf32>
}

For the keras test model, the IR is:
  %7 = "tf.Const"() {value = dense<12> : tensor<2xi32>} : () -> tensor<2xi32>
  %8 = "tf.Const"() {value = dense<[[24, 28], [24, 28]]> : tensor<2x2xi32>} : () -> tensor<2x2xi32>
  %9 = "tf.Const"() {value = dense<3> : tensor<i32>} : () -> tensor<i32>
  %10 = "tf.Identity"(%arg0) {T = f32, device = ""} : (tensor<1x128x128x3xf32>) -> tensor<1x128x128x3xf32>
  %11 = "tf.SpaceToBatchND"(%10, %3, %4) {T = f32, Tblock_shape = i32, Tpaddings = i32, device = ""} : (tensor<1x128x128x3xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<36x26x26x3xf32>
  %12 = "tf.Conv2D"(%11, %2) {T = f32, data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true} : (tensor<36x26x26x3xf32>, tensor<5x5x3x8xf32>) -> tensor<36x22x22x8xf32>
  %13 = "tf.BatchToSpaceND"(%12, %3, %5) {T = f32, Tblock_shape = i32, Tcrops = i32, device = ""} : (tensor<36x22x22x8xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<1x128x128x8xf32>
  %y, %batch_mean, %batch_variance, %reserve_space_1, %reserve_space_2, %reserve_space_3 = "tf.FusedBatchNormV3"(%13, %0, %1, %1, %0) {T = f32, U = f32, data_format = "NHWC", device = "", epsilon = 1.000000e-03 : f32, is_training = false} : (tensor<1x128x128x8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<8xf32>) -> (tensor<1x128x128x8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<8xf32>, tensor<*xf32>)
  %14 = "tf.SpaceToBatchND"(%10, %7, %8) {T = f32, Tblock_shape = i32, Tpaddings = i32, device = ""} : (tensor<1x128x128x3xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<144x15x15x3xf32>
  %15 = "tf.Conv2D"(%14, %6) {T = f32, data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true} : (tensor<144x15x15x3xf32>, tensor<5x5x3x8xf32>) -> tensor<144x11x11x8xf32>
  %16 = "tf.BatchToSpaceND"(%15, %7, %5) {T = f32, Tblock_shape = i32, Tcrops = i32, device = ""} : (tensor<144x11x11x8xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<1x128x128x8xf32>
  %17 = "tf.Mul"(%16, %cst) : (tensor<1x128x128x8xf32>, tensor<8xf32>) -> tensor<1x128x128x8xf32>
  %18 = "tf.Add"(%17, %cst_0) : (tensor<1x128x128x8xf32>, tensor<8xf32>) -> tensor<1x128x128x8xf32>
  %19 = "tf.ConcatV2"(%y, %18, %9) {N = 2 : i64, T = f32, Tidx = i32, _cloned = true, device = ""} : (tensor<1x128x128x8xf32>, tensor<1x128x128x8xf32>, tensor<i32>) -> tensor<1x128x128x16xf32>
  return %19 : tensor<1x128x128x16xf32>

I think the issue is that the IR for saved model is a bit strange, notice those lines:
%13 = "tf.SpaceToBatchND"(%11, %3, %4) {T = f32, Tblock_shape = i32, Tpaddings = i32, device = ""} : (tensor<1x128x128x3xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<144x15x15x3xf32>
  %14 = "tf.Conv2D"(%12, %8) {T = f32, data_format = "NHWC", device = "", dilations = [1, 1, 1, 1], explicit_paddings = [], padding = "VALID", strides = [1, 1, 1, 1], use_cudnn_on_gpu = true} : (tensor<36x26x26x3xf32>, tensor<5x5x3x8xf32>) -> tensor<36x22x22x8xf32>
  %15 = "tf.BatchToSpaceND"(%14, %0, %2) {T = f32, Tblock_shape = i32, Tcrops = i32, device = ""} : (tensor<36x22x22x8xf32>, tensor<2xi32>, tensor<2x2xi32>) -> tensor<1x128x128x8xf32>

The `block_shape` parameter before/after the Conv2D op is different, which causes the pattern to not match successfully. Will investigate why the IR is different.

**Comment by haozha111** [comment]
I think you can produce the correct result by calling the tflite converter python API:
def run_sm():
  out_dir = pathlib.Path("/tmp/minimal_bug_repro")
  converter = tf.compat.v2.lite.TFLiteConverter.from_saved_model(str(out_dir))
  converter.experimental_new_converter = True
  tflite_model = converter.convert()
  output_file = out_dir / "model.tflite"
  output_file.write_bytes(tflite_model)

I think there is some unexpected bug when you use the command line tool `tflite_converter`. Still investigating...

**Comment by haozha111** [comment]
Hi, Nupur, do you know what might be the cause for the difference between calling the python API and the command line tool?

**Comment by haozha111** [comment]
I also tried to convert the model via command line 'tflite_convert' directly (no bazel) in tf-nightly, and the model could be converted correctly. I think the issue is probably with bazel, it might be calling the TF 1 saved model loader which doesn't produce the expected result.

Can you please try using `tf-nightly` and then run 'tflite_conveter' tool directly (please avoid using bazel)?

Thanks.

**Comment by depthwise** [comment]
Just to be clear, once again, the SavedModel I posted was saved using TF 2.1.0, not the new "master" build. Let me try to replicate this with a wheel of TF build off master to see if the model is being saved incorrectly in the first place. Build times being what they are, this will take a bit of time.

**Comment by haozha111** [comment]
I think the saved model is generated correctly, it doesn't matter if you generate it from TF 2.1.0 or the master build.

The issue is with the converter. When you build from master, and then run `bazel`, even if it's pulling the latest code, I think there is some mis-configuration in bazel that causes the model loading to incorrectly use the old TF 1.x codepath. So what I'm suggesting maybe the easiest approach is to download the tf-nightly, and then call 'tflite_convert' tool directly (in a virtualenv).

**Comment by depthwise** [comment]
Nightly as of last night LGTM, in both my full deeplab model and the minimal example. Thanks for the quick fix, much appreciated. This was blocking things in unpleasant ways.

**Comment by haozha111** [comment]
Great to hear that!

**Comment by bayesian-mind** [comment]
@haozha111 any updates on this?

**Comment by bayesian-mind** [comment]
> > > @haozha111 I have not tested on TF nightly, however, tested on latest stable TF 2.6 release. Also, TFMOT 0.7.0 and tf-nightly-gpu = '2.7.0-dev20210806' seem to be giving build issues. Is there a 1:1 match for both that works well?
> > 
> > 
> > I would suggest that we test it on tf-nightly, since this is the most updated code.
> 
> @haozha111 Please find below the code that will help you reproduce the issue.
> 
> ```
> import numpy as np
> import tensorflow as tf
> from tensorflow_model_optimization.python.core.quantization.keras import quantize
> from tensorflow.python import keras
> 
> l = tf.keras.layers
> 
> tf.config.run_functions_eagerly(True)
> 
> def functional_model():
>     """Builds an MNIST functional model."""
>     inp = tf.keras.Input(shape=image_input_shape())
>     x = l.Conv2D(filters=32, kernel_size=5, padding='same', activation='relu',
>                  kernel_regularizer=tf.keras.regularizers.l2(l=0.0001))(inp)
>     x = l.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='same')(x)
>     # TODO(pulkitb): Add BatchNorm when transformations are ready.
>     # x = l.BatchNormalization()(x)
>     x = l.Conv2D(filters=64, kernel_size=5, padding='same', activation='relu',
>                  kernel_regularizer=tf.keras.regularizers.l2(l=0.0001))(x)
>     x = l.Conv2D(filters=64, kernel_size=3, dilation_rate=(3, 3), padding='same', activation='relu',
>                  kernel_regularizer=tf.keras.regularizers.l2(l=0.0001))(x)
>     x = l.MaxPooling2D(pool_size=(2, 2), strides=(2, 2), padding='same')(x)
>     x = l.Flatten()(x)
>     x = l.Dense(1024, activation='relu')(x)
>     x = l.Dropout(0.4)(x)
>     out = l.Dense(10, activation='softmax')(x)
> 
>     return tf.keras.Model(inp, [out])
> 
> 
> def image_input_shape(img_rows=28, img_cols=28):
>     if tf.keras.backend.image_data_format() == 'channels_first':
>         return 1, img_rows, img_cols
>     else:
>         return img_rows, img_cols, 1
> 
> 
> def preprocessed_data(img_rows=28,
>                       img_cols=28,
>                       num_classes=10):
>     """Get data for mnist training and evaluation."""
>     (x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
> 
>     if tf.keras.backend.image_data_format() == 'channels_first':
>         x_train = x_train.reshape(x_train.shape[0], 1, img_rows, img_cols)
>         x_test = x_test.reshape(x_test.shape[0], 1, img_rows, img_cols)
>     else:
>         x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
>         x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
> 
>     x_train = x_train.astype('float32')
>     x_test = x_test.astype('float32')
>     x_train /= 255
>     x_test /= 255
> 
>     # convert class vectors to binary class matrices
>     y_train = tf.keras.utils.to_categorical(y_train, num_classes)
>     y_test = tf.keras.utils.to_categorical(y_test, num_classes)
> 
>     return x_train, y_train, x_test, y_test
> 
> 
> model = functional_model()
> model.summary()
> x_train, y_train, x_test, y_test = preprocessed_data()
> 
> model.compile(
>     loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
> model.fit(x_train, y_train, batch_size=500)
> _, model_accuracy = model.evaluate(x_test, y_test, verbose=0)
> 
> print("Quantizing model")
> 
> quantized_model = quantize.quantize_model(model)
> quantized_model.compile(
>     loss='categorical_crossentropy', optimizer='sgd', metrics=['accuracy'])
> 
> quantized_model.fit(x_train, y_train, batch_size=500)
> _, quantized_model_accuracy = quantized_model.evaluate(
>     x_test, y_test, verbose=0)
> model.save("/home/anurag/git/train_data/testOrig.h5")
> quantized_model.save("/home/anurag/git/train_data/test.h5")
> converter = tf.lite.TFLiteConverter.from_keras_model(quantized_model)
> converter.optimizations = [tf.lite.Optimize.DEFAULT]
> converter.inference_input_type = tf.int8
> converter.inference_output_type = tf.int8
> converter.change_concat_input_ranges = True
> converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]
> tfliteModel = converter.convert()
> with open("/home/anurag/git/train_data/test.tflite", 'wb') as outfile:
>     outfile.write(tfliteModel)
> ```

@haozha111 any updates on this?

**Comment by haozha111** [comment]
sorry for the delay. will take a deeper look today.

**Comment by bayesian-mind** [comment]
Hello @haozha111 thank you for looking into this, @jvishnuvardhan recommended me to create a new issue for the same and I did that yesterday. The issue number is #53025 .
