### ISSUE TITLE
Custom Op Placement on TPUs

### ISSUE THREAD

**Issue by aidangomez** [tensorflow/tensorflow#29592]
Hello,

I'd like to place one portion of my model on a single core of a TPU and another portion on another core (as opposed to the usual full-model replica method).

What is the correct way to do this? I understand that I'll need to do away with TPUEstimator and use a tpu.rewrite() along with tf.Sessions, but I'm not sure the correct way to specify placement for a TPU core.

Is it as simple as `with tf.device("TPU:<core_id>"):`?

**Comment by aidangomez** [comment]
Presumably people working on MTF have already solved how to do this, so maybe Noam, Ryan, or another would be the best people to have answer.

**Comment by achandraa** [comment]
Can you please help us with some more information as in platform ( operating system, architecture ), TensorFlow version you are using. This will help us to proceed faster. Thanks!

**Comment by aidangomez** [comment]
TF 1.13.1
TPU-v2

I suppose this easiest thing to provide would be to show a colab that's confusing me: https://colab.research.google.com/drive/1Y9PgINAT_zhjz4xXbpC5tTMRzg7aSH1e

I had imagined that running on all 8 cores would have been many times faster than running on a single core, but I'm not seeing that here.

**Comment by frankchn** [comment]
@aidangomez I think the issue here is that the computation in your Colab is so small that the TPU compilation overhead (etc...) dominates. I changed `for _ in range(5)` to `for _ in range(000)`, then I get:

```
Running ops
One core: 44.88167405128479
Eight cores: 25.88580870628357
```
It would also be helpful to [take a profile](https://stackoverflow.com/questions/53254056/running-cloud-tpu-profiler-in-google-colab-environment?rq=1) and see what the utilization is like on each core.

**Comment by frankchn** [comment]
Going to close this for now, but feel free to re-open if this persists with larger computations and it would be helpful to take a profile as well.
