### ISSUE TITLE
[TF 2.0] tf.linalg.inv

### ISSUE THREAD

**Issue by mukeshmithrakumar** [tensorflow/tensorflow#29700]
**System information**
- TensorFlow version: '2.0.0-dev20190612'
- Python version: 3.6.7

**Describe the current behavior**
I am taking the inverse of a matrix with a large condition number, see the code for the matrix example, when I try tf.linalg.inv(A) I get the error: InvalidArgumentError: Input is not invertible. [Op:MatrixInverse]

**Describe the expected behavior**
I don't think that is the correct error, because the Matrix can be inverted because the determinant is not exactly zero and TF gets it as zero due to the way tf.linalg.det is implemented. But if you try the same in numpy or Matlab, we can get the inv, in numpy you get the inv and in Matlab, you get the inv with a warning. Again, the determinant is very small (2.1934511e-08), for all purposes it can be assumed to be zero, so in the least, the error can be more of a warning rather than a not invertible error.

Also, I am curious to know how precise TF calculations are or after how many significant figure something is rounded to be zero. If you have any resources or links so I can check it out, would really appreciate it.

**Code to reproduce the issue**
```
A = tf.constant([[4.1, 2.8], [9.676, 6.608]], dtype=tf.float32)
Ainvnp = np.linalg.inv(A)
print(A2inv)

Ainvtf = tf.linalg.inv(A)
print(Ainvtf)
```

**Comment by achandraa** [comment]
I have tried on Colab with TensorFlow version 2.0.0-dev20190612 and was able to get inverse of matrix when trying with numpy but got the mentioned error when trying with "tf.linalg.inv"

**Comment by mshlis** [comment]
any update?

**Comment by rmlarsen** [comment]
If the condition number of your matrix approaches 1/std::numeric_limits<T> then it is "numerically singular", or "numerically indistinguishable" from a singular matrix. 

As you mention, Matlab warns you that you are in this regime, which also means that the results returned by np.inv or inv in Matlab are essentially completely random numbers.

In TensorFlow we chose to fail with an error in this case, instead of returning garbage. The TF error only occurs when zeros appear in the diagonal of the underlying LU decomposition, which is not as reliable as the condition number estimation approach used by, Matlab. I contributed a condition estimator to the Eigen library used by TF on CPU, and we should probably consider using it.

My advice would be: 

1. Don't compute the inverse of a matrix unless you absolutely have to. If you are really solving a linear system of equations, consider using tf.linalg.solve. Use tf.linalg.solve_ls, if you are solving a least-squares problem or an under-determined linear system.
2. If you think you need the inverse for an ill-conditioned matrix, you most likely want the pseudo-inverse provided by tf.linalg.pinv.
3. If you really want to work with an ill-conditioned matrix, use tf.linalg.svd.

I would recommend picking up a textbook on numerical linear algebra and read about (backwards) to better understand what the limitations of these algorithms are. Personally I really like Jim Demmel's book: https://epubs.siam.org/doi/book/10.1137/1.9781611971446?mobileUi=0

**Comment by umairbinmansoor** [comment]
Hello guys,
My simple question is that why the Matlab running on my laptop (Intel, core i5, 8G ram) computes the inverse faster as compared to the Google TPU. Code attached...
Matlab code:
A = rand(3000,3000);
tic
inv(A);
t = toc;
disp(t)
Output:
1.1297

Python code:
import numpy as np
import scipy as sp
import timeit
import tensorflow as tf

dim = 3000
mat = tf.random.uniform(shape=(dim,dim))

st = timeit.default_timer()
tf.linalg.inv(mat)
print("time elapsed tensorflow:", timeit.default_timer() - st)

x = np.random.rand(dim,dim)
st = timeit.default_timer()
np.linalg.inv(x)
print("time elapsed scipy: ", timeit.default_timer() - st)

Output:
time elapsed tensorflow: 1.3009283419999065
time elapsed scipy: 2.618305011000075

**Comment by jvishnuvardhan** [comment]
@umairbinmansoor Please open a new issue with a simple standalone code to reproduce the issue. Your code uses only cpu as you didn't enable any TPU. Thanks!

**Comment by umairbinmansoor** [comment]
> @umairbinmansoor Please open a new issue with a simple standalone code to reproduce the issue. Your code uses only cpu as you didn't enable any TPU. Thanks!

@jvishnuvardhan, I have the earlier output with the TPU selected but the funny thing is, with GPU, I am getting 0.1153 s
