### ISSUE TITLE
ok

### ISSUE THREAD

**Issue by cSingleboy** [tensorflow/tensorflow#29724]
bazel build --config=opt --config=mkl //tensorflow:libtensorflow_cc.so
successfully!
but, have no absl and eigen3

**Comment by Leslie-Fang** [comment]
@cSingleboy Sorry, What did you mean of no absl and eigen3?

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
