### ISSUE TITLE
tf.keras.Model can't initialize variables given input shape in tf2.0 beta

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [tensorflow/tensorflow#29729]
When given `input_shape` of the input, the model built on `Sequential` will initialize all the variables at once. 
```python  
model = Sequential()
model.add(layers.Dense(32, input_shape=(500,)))
model.add(layers.Dense(32))
print(len(model.weights)) #output 4
```

--------------------------------------
When given `input_shape` of the input, the model built on `Model` will not initialize all the variables at once and only initializes them after doing some predictions.
I can understand when no `input_shape` is given, the model cannot initialize all the variables, but why it doesn't when given `input_shape`?

```python
class MyModel(tf.keras.Model):
  def __init__(self, state_dim, action_dim):
    super(MyModel, self).__init__()
    self.state_dim = state_dim
    self.action_dim = action_dim

    self.fc1 = tf.keras.layers.Dense(100, input_shape=(2,))
    self.fc2 = tf.keras.layers.Dense(1)

  def call(self, inputs):
    out = self.fc1(inputs)
    out = self.fc2(out)
    return out

Q = MyModel(2, 2)
print(len(Q.weights)) # output 0
states = np.random.random((10, 2))
Q(states)
print(len(Q.weights)) # output 4
```

**Comment by gadagashwini** [comment]
I am able to reproduce the issue on colab with Tf-2.0.0.brta0.

**Comment by TomorrowIsAnOtherDay** [comment]
any progress here?

**Comment by TomorrowIsAnOtherDay** [comment]
any progress here? 
Again.

**Comment by Geogre19** [comment]
Same issue. Any response from tensorflow developer ?

**Comment by tomerk** [comment]
Subclass models in Keras are not guaranteed to have made all of their variables until the first time they have been called on inputs. This is because the model has no way to know how your layers are connected until you actually enter the `call` method, so it is insufficient to specify an input layer shape on one of your layers.

If your subclass model doesn't implement a custom `build` method, you should be able to call `model.build()` to force the variables to instantiate.

We are currently exploring ways of allowing subclass models that do implement custom `build` methods to still initialize all variables when their `build` method is called. (Models implement custom `build` methods when the layers can't all be constructed in the `__init__` method because the number of layers may depend on the input dimensions)

Alternatively, you can also use the Keras functional API, because the variables will be created right away without needing to call `.build()`. https://www.tensorflow.org/beta/guide/keras/functional

**Comment by TomorrowIsAnOtherDay** [comment]
Thanks for replying. 
I do want to use limited number of  keras functional API to build my network, as these APIs are not as flexible as origin tf.xx APIs. So I will try using model.build() to initialize the variables.
