### ISSUE TITLE
Sess.run() leads to unexpected memory leaky in CPU version

### ISSUE THREAD

**Issue by CloudFlyCN** [tensorflow/tensorflow#29816]
Hi~

A simplest example is shown as below:
```
graph = tf.Graph()

sess = tf.InteractiveSession(graph=graph)

with graph.as_default_graph():
       # Here is my code build the model
       model  = Model(inputs=,outputs=)

# frozen graph to avoid any other ops adding to the graph
graph.finalize()

# prepare test data
img = np.ones(model.input_shape)

# run session in loop
while True:
      sess.run(model.output,feed_dict={model.input:img}
     # Here is my code for watching memory state:
      print(psutil.Process(os.getpid()).memory_info().rss)
``` 

And the result of `psutil` shows the process memory usage increases after each iteration and could not collected by gc in python. I eagerly wonder why this phenomena appears and how to solve it.

Thanks a lot!

**Comment by gadagashwini** [comment]
@CloudFlyCN Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

 If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
