### ISSUE TITLE
Limited tf.compat.v2.summary API due to missing TensorBoard installation.

### ISSUE THREAD

**Issue by JCMiles** [tensorflow/tensorflow#29866]
I came across this warning after updating to the las nightly release.
Any idea on how to fix it?

**Comment by timekarma** [comment]
I too received the same error
Ubuntu 16.4 
installed tf 2.0.0 beta1
using tensorflow models object_detection
python object_detection/builders/model_builder_test.py
Error seen
WARNING: Logging before flag parsing goes to stderr.
W0621 07:26:07.547648 139914507269888 __init__.py:308] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W0621 07:26:07.557060 139914507269888 __init__.py:335] Limited tf.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "object_detection/builders/model_builder_test.py", line 23, in <module>
    from object_detection.builders import model_builder
  File "/home/ai/tensorflow/models/research/object_detection/builders/model_builder.py", line 20, in <module>
    from object_detection.builders import anchor_generator_builder
  File "/home/ai/tensorflow/models/research/object_detection/builders/anchor_generator_builder.py", line 22, in <module>
    from object_detection.protos import anchor_generator_pb2
ImportError: cannot import name anchor_generator_pb2

**Comment by nfsrules** [comment]
Hi @JCMiles Did you solve this issue?
Thanks

**Comment by sahilpasricja** [comment]
Hey,
Did we manage to find a solution to this?

**Comment by JCMiles** [comment]
Hi everyone, I fixed this problem by checking my local project files.
I my case I had a file named tensorborad_run.py that was interfering with the correct import of the regular tensorboard files. By changing the file name to run_tensorboard solved the problem.

**Comment by baxterai** [comment]
See https://github.com/tensorflow/tensorboard/issues/2352 for solution

**Comment by m-nasiri** [comment]
My script name was tensorboard.py, i changed the name of file to tb.py solved my problem.
