### ISSUE TITLE
 No OpKernel was registered to support Op 'TensorArrayWriteV3'

### ISSUE THREAD

**Issue by veeeencedamico2** [tensorflow/tensorflow#29914]
I'm trying to perform the inference on a pre-trained model that I imported into the assets folder.

When I make inference I get the following error:

`java.lang.IllegalArgumentException: No OpKernel was registered to support Op TensorArrayWriteV3' used by {{node map_4/while/TensorArrayWrite/TensorArrayWriteV3}}with these attrs: [T=DT_UINT8, _class=["loc:@map_4/while/convert_image"]]
`

**Comment by gadagashwini** [comment]
@veeeencedamico2 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
