### ISSUE TITLE
How to make remote worker load custom op?

### ISSUE THREAD

**Issue by wudixiaotie** [tensorflow/tensorflow#29946]
I write a custom op and compile it to .so file. When I use it in to train model locally, it works fine. But when I use it to run in standalone mode, worker server alway tells me OP not registered, because the worker server started before, it have not load my custom op.

So is there anyway I can do to tell remote worker to load lib dynamic like tf.load_op_library in local mode?

**Comment by wudixiaotie** [comment]
@tensorflower-gardener

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and provide better help to such issues. Meanwhile you can also have a look on this [documentation.](https://www.tensorflow.org/guide/extend/op). Hope that helps. Thanks!

**Comment by wudixiaotie** [comment]
@achandraa Thanks for your reply. But I think it is a bug. Because there is not way to rpc remote worker to load_op_library. Only way to do that is to stop remote worker, and restart it with load_op_library before join().
