### ISSUE TITLE
build for Windows always fail

### ISSUE THREAD

**Issue by kekxv** [tensorflow/tensorflow#29945]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Windows 10 (try cmake and bazel,not work)
- TensorFlow installed from (source or binary):
- TensorFlow version:2.0.0 or 1.14
- Python version:3.7.3
- Installed using virtualenv? pip? conda?:pip
- Bazel version (if compiling from source):0.25
- GCC/Compiler version (if compiling from source):vs 2019
- CUDA/cuDNN version:no
- GPU model and memory:no use

build all fail,I followed the official documentation.However, it cannot be executed successfully.Some files cannot be downloaded or otherwise.
Please help me:
* Tell me how to build c api
* Give me the file for tensorflow.lib and tensorflow.dll.

thank you very much!

**Comment by meteorcloudy** [comment]
Can you provide the error message you got when building TensorFlow on Windows?

**Comment by kekxv** [comment]
@meteorcloudy 
Thanks for your reply, using cmake has been unsuccessful. I compiled it successfully after using bazel. Now I have a new problem. I need x86_32 dll. I don't know how to make it.
（感谢你的回复，使用 cmake 一直不成功，我使用bazel之后编译成功，现在有个新的问题，我需要x86_32 的dll，我不知道如何制作。）

**Comment by jvishnuvardhan** [comment]
@kekxv This is an old issue. The  documentation has improved a lot since the issue opened. There is a Special Interest Group (SIG) for especially [build related issues](https://github.com/tensorflow/build). You can learn and contribute towards build related issues. Users can also attend months meetings or follow the progress [here](https://docs.google.com/document/d/10_3IQ5aF-88ADJNLF0WOpb09bZ15x-sBnRSnDHNCNr8/edit#heading=h.u7w1oawlfu32). 

As this is an old issue, I am closing this issue. Please feel free to open a new issue if there is any build related issues with recent TF versions. Thanks!
