### ISSUE TITLE
TensorFlow/examples The gesture_classification Install Dependencies FAIL

### ISSUE THREAD

**Issue by LiYaun** [tensorflow/tensorflow#30005]
As the picture shows
<img width="1102" alt="螢幕快照 2019-06-20 下午8 20 45" src="https://user-images.githubusercontent.com/28727682/59848978-11d59480-9399-11e9-8dc0-3025be7e51c3.png">

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by LiYaun** [comment]
I run the TensorFlow Lite example from [HERE](https://github.com/tensorflow/examples).
I choice the gesture_classification.
When I finish to train my model by web  and download it.
Then I use Colabs to open the [tensorflowjs_to_tflite_colab_notebook.ipynb](https://github.com/tensorflow/examples/blob/master/lite/examples/gesture_classification/ml/tensorflowjs_to_tflite_colab_notebook.ipynb).
In the Install Dependencies part, I saw Error msg like the image.
Is that correct?

**Comment by achandraa** [comment]
Looks like this is  TensorflowJS issue. You can post this issue on [TensorFlowJS](https://github.com/tensorflow/tfjs/issues) repository for better and faster help. Let us know if you have any clarification. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
