### ISSUE TITLE
clock_gettime undefined , build on centos6.6, gcc 4.9 （build static lib）

### ISSUE THREAD

**Issue by cSingleboy** [tensorflow/tensorflow#30000]
centos 6.6
gcc 4.9
build  static lib of tensorflow
use:  ./tensorflow/contrib/makefile/build_all_linux.sh

**Comment by achandraa** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by achandraa** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
