### ISSUE TITLE
google.protobuf.message.DecodeError: Truncated message

### ISSUE THREAD

**Issue by zxzhijia** [tensorflow/tensorflow#3002]
I retrained a Inception model using my data and saved the label txt and pd file. I tried to run @wolffg 
code lab file to load my trained network on my Raspberry Pi and test on another image. But I got this error below:
pi@raspberrypi:~/robotimages $ python retrain_test.py /home/pi/robotimages/Robot1/w/1.jpg
Traceback (most recent call last):
  File "retrain_test.py", line 15, in <module>
    graph_def.ParseFromString(f.read())
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/message.py", line 185, in ParseFromString
    self.MergeFromString(serialized)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1091, in MergeFromString
    if self._InternalParse(serialized, 0, length) != length:
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/python_message.py", line 1127, in InternalParse
    pos = field_decoder(buffer, new_pos, end, self, field_dict)
  File "/usr/local/lib/python2.7/dist-packages/google/protobuf/internal/decoder.py", line 610, in DecodeRepeatedField
    raise _DecodeError('Truncated message.')
google.protobuf.message.DecodeError: Truncated message.
pi@raspberrypi:~/robotimages $

**Comment by petewarden** [comment]
That appears to be an issue with the model file loading. It's the sort of problem I'd expect to see if the model file was truncated or corrupt in some way. Can you check that you can load the model file on another machine?

**Comment by zxzhijia** [comment]
Thank you for your answer. Yes, it can somehow be loaded on my Desktop but
has another different error:

(tensorflow)xu@xu-ThinkCentre-M72e:~/Robotimages $ retrain_test.py
/home/xu/Robotimages/Robot1/w/1.jpg
retrain_test.py: command not found
(tensorflow)xu@xu-ThinkCentre-M72e:~/Robotimages $ python retrain_test.py
/home/xu/Robotimages/Robot1/w/1.jpg
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA
library libcurand.so locally
I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:900] successful NUMA
node read from SysFS had negative value (-1), but there must be at least
one NUMA node, so returning NUMA node zero
I tensorflow/core/common_runtime/gpu/gpu_init.cc:102] Found device 0 with
properties:
name: GeForce GTX 750 Ti
major: 5 minor: 0 memoryClockRate (GHz) 1.2545
pciBusID 0000:01:00.0
Total memory: 2.00GiB
Free memory: 1.80GiB
I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y
I tensorflow/core/common_runtime/gpu/gpu_device.cc:755] Creating TensorFlow
device (/gpu:0) -> (device: 0, name: GeForce GTX 750 Ti, pci bus id:
0000:01:00.0)
W tensorflow/core/kernels/batch_norm_op.cc:36] Op is deprecated. It will
cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
W tensorflow/core/kernels/batch_norm_op.cc:36] Op is deprecated. It will
cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
W tensorflow/core/kernels/batch_norm_op.cc:36] Op is deprecated. It will
cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
E tensorflow/core/common_runtime/executor.cc:332] Executor failed to create
kernel. Invalid argument: NodeDef mentions attr 'T' not in Op<name=MaxPool;
signature=input:float -> output:float; attr=ksize:list(int),min=4;
attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME",
"VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>;
NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1],
padding="VALID", strides=[1, 2, 2, 1],
_device="/job:localhost/replica:0/task:0/gpu:0"](pool/control_dependency)
     [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3,
1], padding="VALID", strides=[1, 2, 2, 1],
_device="/job:localhost/replica:0/task:0/gpu:0"](pool/control_dependency)]]
Traceback (most recent call last):
  File "retrain_test.py", line 86, in <module>
    run_inference_on_image()
  File "retrain_test.py", line 69, in run_inference_on_image
    {'DecodeJpeg/contents:0': image_data})
  File
"/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py",
line 340, in run
    run_metadata_ptr)
  File
"/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py",
line 564, in _run
    feed_dict_string, options, run_metadata)
  File
"/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py",
line 637, in _do_run
    target_list, options, run_metadata)
  File
"/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/client/session.py",
line 659, in _do_call
    e.code)
tensorflow.python.framework.errors.InvalidArgumentError: NodeDef mentions
attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float;
attr=ksize:list(int),min=4; attr=strides:list(int),min=4;
attr=padding:string,allowed=["SAME", "VALID"];
attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef:
pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1],
padding="VALID", strides=[1, 2, 2, 1],
_device="/job:localhost/replica:0/task:0/gpu:0"](pool/control_dependency)
     [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3,
1], padding="VALID", strides=[1, 2, 2, 1],
_device="/job:localhost/replica:0/task:0/gpu:0"](pool/control_dependency)]]
Caused by op u'pool', defined at:
  File "retrain_test.py", line 86, in <module>
    run_inference_on_image()
  File "retrain_test.py", line 63, in run_inference_on_image
    create_graph()
  File "retrain_test.py", line 50, in create_graph
    _ = tf.import_graph_def(graph_def, name='')
  File
"/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/importer.py",
line 240, in import_graph_def
    op_def=op_def)
  File
"/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py",
line 2154, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File
"/home/xu/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py",
line 1154, in __init__
    self._traceback = _extract_stack()

**Comment by zxzhijia** [comment]
By the way, if I use Bazel to load the same pb and txt file, it works well
on my desktop.

**Comment by ank286** [comment]
For me, the retrained inception-v3 model loads properly as I am able to see all the different types of tensors including "final_result" and "DecodeJpeg/contents." The model file doesn't seem corrupted. But I do get the exact same DecodeJpeg error as zxzhijia

**Comment by zxzhijia** [comment]
@ank286 It works for me now after I use tensorflow 0.9.0 rc0.

**Comment by zxzhijia** [comment]
@ank286 So please have a try and see if it works.

**Comment by ank286** [comment]
I did a "pip show tensorflow" and I have 0.9.0rc0 running.

I still get an error when trying to call import_graph_def(graph_def, name='') with a retrained Inception-v3 model for the flowers data.

`W tensorflow/core/framework/op_def_util.cc:332] Op BatchNormWithGlobalNormalization is deprecated. It will cease to work in GraphDef version 9. Use tf.nn.batch_normalization().
E tensorflow/core/common_runtime/executor.cc:334] Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float; attr=ksize:list(int),min=4; attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)
         [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)]]
Traceback (most recent call last):
  File "retrain_inference.py", line 78, in <module>
    run_inference_on_image()
  File "retrain_inference.py", line 62, in run_inference_on_image
    {'DecodeJpeg/contents:0': image_data})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 636, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 708, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 728, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.InvalidArgumentError: NodeDef mentions attr 'T' not in Op<name=MaxPool; signature=input:float -> output:float; attr=ksize:list(int),min=4; attr=strides:list(int),min=4; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)
         [[Node: pool = MaxPool[T=DT_FLOAT, data_format="NHWC", ksize=[1, 3, 3, 1], padding="VALID", strides=[1, 2, 2, 1], _device="/job:localhost/replica:0/task:0/cpu:0"](pool/control_dependency)]]
Caused by op u'pool', defined at:
  File "retrain_inference.py", line 78, in <module>
    run_inference_on_image()
  File "retrain_inference.py", line 50, in run_inference_on_image
    create_inception_graph()
  File "retrain_inference.py", line 30, in create_inception_graph
    tf.import_graph_def(graph_def, name='')
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 274, in import_graph_def
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()

`

**Comment by zxzhijia** [comment]
@ank286 , is the version which you downloaded from github also 0.9.0 rc0?
What I did is installing using pip, and also downloaded the tensorflow
source code from github *with version 0.9.0 rc0*.

**Comment by ank286** [comment]
So you installed TensorFlow 0.9.0rc0 using `sudo pip2 install https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.9.0rc0-cp27-none-linux_x86_64.whl`

and you also compiled from source? Or you downloaded the source code for 0.9.0rc0 and put it in some folder, which folder? 

Thank you

**Comment by zxzhijia** [comment]
Download it to any folder you wants and run

       cd /tensorflow/

bazel build -c opt --copt=-mavx tensorflow/examples/image_retraining:retrain

**Comment by zxzhijia** [comment]
Then run below in the same folder to retrain. For more detail, you can see
Tensorflow for poets.

bazel-bin/tensorflow/examples/image_retraining/retrain \
--bottleneck_dir=/tf_files/bottlenecks \
--model_dir=/tf_files/inception \
--output_graph=/tf_files/retrained_graph.pb \
--output_labels=/tf_files/retrained_labels.txt \
--image_dir /tf_files/flower_photos

**Comment by ank286** [comment]
Okay, I am retraining now with 0.9.0rc0 and re-generating the .pb model file. I will report back if I can import this model successfully. 
Thank you for all your help!

**Comment by zxzhijia** [comment]
No problem. Let us know if it works.
