### ISSUE TITLE
Can TensorFlow's "predict" be used in C++?

### ISSUE THREAD

**Issue by Toby237** [tensorflow/tensorflow#30036]
I am very new to TensorFlow and this may be a silly question, and I hope this is the right place to ask it. I have been searching for a rnn-library that I can use with C++ and was hoping TensorFlow could work for me. What I am wondering about is:

**Can I train and save a keras model in python, and then load the model by using C++, and then use the loaded model to do predictions (in C++)?**

I just wanted to make sure, or figure out, if this is possible before I started working on, and learn more about TensorFlow, or if I should keep looking for other C++ libraries.

**Comment by achandraa** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there and provide solution to such issues better and faster. meanwhile you can also have a look on this [link](http://bitbionic.com/2017/08/18/run-your-keras-models-in-c-tensorflow/) for reference. This might help you. Thanks!

**Comment by Toby237** [comment]
Thanks for the reply. I understand, I will ask this question (and similar ones in the future) at StackOverflow instead, since it's not a bug or feature request. Thanks again!

**Comment by achandraa** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=30036)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=30036)
