### ISSUE TITLE
Unsupported cumsum, cumprod and scatter_nd ops

### ISSUE THREAD

**Issue by samsucik** [tensorflow/tensorflow#30131]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): from binary
- TensorFlow version (or github SHA if from source): 1.13.1

**Provide the text output from tflite_convert**

```
Some of the operators in the model are not supported by the standard TensorFlow Lite runtime and are not recognized by TensorFlow. If you have a custom implementation for them you can disable this error with --allow_custom_ops, or by setting allow_custom_ops=True when calling tf.lite.TFLiteConverter(). Here is a list of builtin operators you are using: ABS, ADD, CAST, CONCATENATION, EQUAL, EXPAND_DIMS, FULLY_CONNECTED, GATHER, LESS, MEAN, MUL, PACK, PAD, RANGE, REDUCE_MAX, RELU, RESHAPE, RSQRT, SHAPE, SIN, SOFTMAX, SQUARED_DIFFERENCE, SQUEEZE, STRIDED_SLICE, SUB, SUM, TILE, TRANSPOSE. Here is a list of operators for which you will need custom implementations: Cumprod, Cumsum, ScatterNd.
```

**Any other info / logs**

I am trying to convert a transformer model built using [tensor2tensor](https://github.com/tensorflow/tensor2tensor), but the implementation in that repo uses `cumsum`, `cumprod` and `scatter_nd`, which makes it unusable with the TF Lite converter...

**Comment by haozha111** [comment]
Sorry that it doesn't work out for you. We are continuously adding new ops into tflite, in the mean time you could also try implement those ops yourself as custom ops [1]. I believe you won't need implement `scatter_nd` since it's a supported tf select op. Just pass --target_ops=TFLITE_BUILTINS,SELECT_TF_OPS during conversion, thanks!

[1]https://www.tensorflow.org/lite/guide/ops_custom
