### ISSUE TITLE
make tf.image ops support tf.float16 in tensorflow 2.0

### ISSUE THREAD

**Issue by mttbx** [tensorflow/tensorflow#30195]
make tf.image ops like tf.image.extract_patches/tf.image.resize to support tf.float16, or at least make them to do implicit cast.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thanks!

**Comment by x10000year** [comment]
This is a feature request. I also need this feature (tf.image.resize for float16)

**Comment by annarev** [comment]
Reassigning to @hyeygit since she has been working on image APIs recently.

**Comment by rmothukuru** [comment]
@mttbx,
Sorry for the delayed response. Can you please go through the documentation of [Mixed Precision](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/Policy) and [the Guide](https://www.tensorflow.org/guide/mixed_precision) and let us know if it helps? Thanks!
