### ISSUE TITLE
Multiple output files for tf.data.experimental.TFRecordWriter

### ISSUE THREAD

**Issue by harahu** [tensorflow/tensorflow#30203]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I have a `tf.data.Dataset` that I want to write to tfrecord files. to do this, I currently use `tf.python_io.TFRecordWriter` to do this, but would like to use `tf.data.experimental.TFRecordWriter`, as it would be more efficient to also do the writing as part of the dataset graph execution. The latter has one limitation, however, which stops me from using it. I need to split my dataset between a number of different shards (files). I could achieve this effect by using the shard method to split the dataset into a number of datasets before writing, but since I want to shuffle the dataset before writing it, this is too expensive.

Hence, I would like `tf.data.experimental.TFRecordWriter` to write a single dataset to multiple files.

**Will this change the current api? How?**
One could for instance change the signature to:
```python
tf.data.experimental.TFRecordWriter(
    file_pattern,  # string with format brackets for index, like 'train-shard-{}.tfrecord'
    num_shards=1,
    compression_type=None
)

```

**Who will benefit with this feature?**
Those of us who use tfrecord files as a storage format for our datasets and need options for writing such files efficiently and with flexibility.

**Any Other info.**

**Comment by jsimsa** [comment]
@harahu it is possible to achieve what you want using existing transformations:

```
  tf.enable_v2_behavior()

  dataset = tf.data.Dataset.from_tensor_slices(["a", "b", "c", "d"])

  def reduce_func(key, dataset):
    filename = tf.strings.join(["/tmp/test.", tf.strings.as_string(key)])
    writer = tf.data.experimental.TFRecordWriter(filename)
    writer.write(dataset.map(lambda _, x: x))
    return tf.data.Dataset.from_tensors(filename)

  dataset = dataset.enumerate()
  dataset = dataset.apply(tf.data.experimental.group_by_window(
    lambda i, _: i % NUM_SHARDS, reduce_func, tf.int64.max
  ))

  for elem in dataset:
    print(elem.numpy())
```

The above will create two files `/tmp/test.0` and `/tmp.test.1` which contain "a", "c" and "b", "d" respectively, printing the names of the files.

**Comment by harahu** [comment]
@jsimsa This seems to work, thank you! Quite complex logic for a relatively simple task, though. Might be work documenting somewhere should/ this move out of `experimental`.

**Comment by jsimsa** [comment]
https://github.com/tensorflow/tensorflow/commit/1d1acc507b281e69dfedafdc4706cc12e55a9933

**Comment by harahu** [comment]
You are amazing.

**Comment by optiluca** [comment]
This example doesn't seem to work in TF 2.0?  On my machine it returns very fast (implausibly fast relative to the size of the dataset I'm trying it on), and no files are written.

**Comment by jsimsa** [comment]
We have a test for this behavior in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/data/experimental/kernel_tests/tf_record_writer_test.py and the test is passing. Please create a separate issue with a minimal reproducible example for your problem.

**Comment by veonua** [comment]
@jsimsa 
does it load whole dataset into memory? Because I tried to run this script on the 10GB dataset with 20 shards... and it does not create any files just eating my memory

**Comment by jsimsa** [comment]
Yes, the `group_by_window` with "infinite" group size will have that effect.

The challenge with the existing API is that `tf.data.experimental.TFRecordWriter.write()` takes a dataset and in order to create a dataset for a shard, you need to iterate through the entire original dataset. An alternative to materializing all shards in memory would be to iterate through the original dataset multiple time.

I can imagine extending the API of `TFRecordWriter` to support `num_shards` argument which would avoid the above problems if that's something that you are interested in, please create a feature request for it and I will mark it as contributions welcome to see if anyone in the external community has interest in implementing it. Thanks.

**Comment by datend3nker** [comment]
I posted a solution to this Problem on [StackOverflow](https://stackoverflow.com/a/64540388/11643158).

`tf.data.experimental.group_by_window` Has to load the whole dataset into memory in order to do some sort of in memory sorting.
Therefore the wired behaviour with not writing any file and just eating memory.
 A solution to this Problem is, using a Generator, iterating over the dataset. I assume you already batched   
your dataset `dataset = dataset.batch(items_per_file)`

`def write_generator():
    i = 0
    iterator = iter(dataset)
    while True:
        optional = iterator.get_next_as_optional()
        ds = optional.get_value()
        batch_ds = tf.data.Dataset.from_tensor_slices(ds)
        writer = tf.data.experimental.TFRecordWriter(save_to + "\\" + name + "-" + str(i) + ".tfrecord", compression_type='GZIP')#compression_type='GZIP'
        i += 1
        yield batch_ds, writer, i
        if optional.has_value().numpy() == False:
            break  
`
And write the file with a for-loop using the generator:
`or data, wri, i in write_generator():
    start_time = time.time()
    wri.write(data)
    print("Time needed: ", time.time() - start_time, "s", "\t", NAME_OF_FILES + "-" + str(i) + ".tfrecord")` 

(sorry I am to dump to get the formatting right, so pleas see on [StackOverflow](https://stackoverflow.com/a/64540388/11643158))
As long one single file fits raw in memory, this should just work fine.
