### ISSUE TITLE
Why not support LeakyRelu op for C++ Api?

### ISSUE THREAD

**Issue by shoutOutYangJie** [tensorflow/tensorflow#30201]
I try to import my pb file which use LeakyRelu as activation function in VS2015. I find I can't use "sess->Create(&gdef)" to import my pb. Error shows :
> Not found: Op type not registered 'LeakyRelu' in binary running on 9BFHO3E5CP3B44C. Make sure the Op and Kernel are registered in the binary running in this process.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
