### ISSUE TITLE
Need better documentation for BestExporter

### ISSUE THREAD

**Issue by jenishah** [tensorflow/tensorflow#30276]
In the documentation for [BestExporter](https://www.tensorflow.org/api_docs/python/tf/estimator/BestExporter), the example mentioned does not specify how to write a _compare_fn_ .
By default, it takes the _loss_.
How to use it if we were to use custom metrics, that are evaluated in the _model_fn_ .

**Comment by gowthamkpr** [comment]
@jenishah Since Estimators are not recommended for new code. Estimators run [v1.Session](https://www.tensorflow.org/api_docs/python/tf/compat/v1/Session)-style code which is more difficult to write correctly, and can behave unexpectedly, especially when combined with TF 2 code. Estimators do fall under our [compatibility guarantees](https://tensorflow.org/guide/versions), but will receive no fixes other than security vulnerabilities. See the [migration guide](https://tensorflow.org/guide/migrate) for details.

This will not be fixed. Closing this issue as it is no longer valid. Thanks!!
