### ISSUE TITLE
 convolution VS correlation convolution 

### ISSUE THREAD

**Issue by lannisite110** [tensorflow/tensorflow#30343]
I think the 

> tensorflow.nn.conv2d 

use the correlation convolution, but i need convolution in my layer. So do you have any advice?

**Comment by gadagashwini** [comment]
@lannisite110 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
