### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError

### ISSUE THREAD

**Issue by govindbanura** [tensorflow/tensorflow#30352]
I have built an LSTM model and try to run that with python flask.

tensorflow.python.framework.errors_impl.NotFoundError: Container localhost does not exist. (Could not find resource: localhost/embedding/embeddings)
	 [[{{node embedding/embedding_lookup}}]]
here is the image of error.

![screencapture-127-0-0-1-5002-predict-2019-07-03-18_18_18](https://user-images.githubusercontent.com/26489408/60592830-0cc40c80-9dbf-11e9-82a5-48ec7c835205.png)

**Comment by govindbanura** [comment]
can anyone help me out with this issue?

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by govindbanura** [comment]
operation system: Windows 10
anaconda 
tensorflow: 1.14.0

Code: 
[first.zip](https://github.com/tensorflow/tensorflow/files/3366777/first.zip)

**Comment by govindbanura** [comment]
Thank you, 
My code is now running and I solved the issue.
Please see the new code to solve the issue.

[first.zip](https://github.com/tensorflow/tensorflow/files/3368295/first.zip)
