### ISSUE TITLE
get_variable style tf.Variable initialization

### ISSUE THREAD

**Issue by jbuckman** [tensorflow/tensorflow#30366]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.x
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently, tf.Variable requires passing in an initial value for the variable. It's often much more useful to pass in a shape and initializer. It'd be great if there was a convenience function that made this easy to do. tf.get_variable did this, but it requires a namescope to be specified, which is no longer desirable.
**Will this change the current api? How?**
Barely - it will simply add an additional way to initialize variables.
**Who will benefit with this feature?**
Almost everyone using TF.
**Any Other info.**

**Comment by alextp** [comment]
@tomhennigan I think you wanted this for sonnet as well, right?

**Comment by tomhennigan** [comment]
Hey @jbuckman, if you're using Keras you can do this inside `Layer`s via [`add_weight`](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Layer#add_weight) which has almost the same signature as `tf.get_variable`.

You can approximate the TF1 API in two lines with the following:

```python
>>> def get_variable(name, shape, dtype=tf.float32, initializer=tf.initializers.GlorotNormal()):
...   return tf.Variable(initializer(shape, dtype), name=name)

>>> w = get_variable("w", [])
<tf.Variable 'w:0' shape=() dtype=float32, numpy=-0.15932713>
```

We did discuss this for [Sonnet 2](https://github.com/deepmind/sonnet/tree/v2), but we found that there was a source of confusion since `get_variable` had both creation and re-use (and we only wanted creation). We've also found that for most layers using the `tf.Variable` API directly leads to pretty simple code (example: https://github.com/deepmind/sonnet/blob/v2/sonnet/src/linear.py#L73-L80).

I think currently we're happy enough without `get_variable` in TF2.

**Comment by rmothukuru** [comment]
@jbuckman,
As per my understanding, [tf.Variable](https://www.tensorflow.org/api_docs/python/tf/Variable) now offers the functionality that you are looking for. Can you please confirm if it is so, so that we can close this issue? Thanks!
