### ISSUE TITLE
ERROR: Invalid command prefix "invoke_stepper"

### ISSUE THREAD

**Issue by chanchann** [tensorflow/tensorflow#30395]
When I use tfdbg and I input the command line: invoke_stepper. It appears ERROR: Invalid command prefix "invoke_stepper"

**Comment by chanchann** [comment]
I just use the example:python -m tensorflow.python.debug.examples.debug_mnist --debug

**Comment by chanchann** [comment]
Thanks very much if you can help me

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by hitbuyi** [comment]
I also found this problem in tensorflow 1.50.0 ,both on WIN10 and Ubuntu20.04,
