### ISSUE TITLE
Inconsistent naming of the getter functions in the C API

### ISSUE THREAD

**Issue by IvanUkhov** [tensorflow/tensorflow#3042]
The naming scheme of the getter functions in the [C API](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/public/tensor_c_api.h) seems to be a bit inconsistent. For instance, there are the following declarations:

```c
// With “Get” and without the type name.
extern TF_Code TF_GetCode(const TF_Status*);

// Without “Get” and without the type name.
extern const char* TF_Message(const TF_Status*);

// Without “Get” and with the type name (“Tensor”).
extern TF_DataType TF_TensorType(const TF_Tensor*);
```

The first two are even concerned with the same type, `TF_Status`. I’m curious if there’s any particular reason behind this naming. Thanks!

Regards,
Ivan

**Comment by vrv** [comment]
I'm sure there was some reasoning, for example since all of these functions are in the global namespace, TF_Type wouldn't be very descriptive, and might end up overloading another TF_Type in the future, etc.  In any case, we'll try to be thoughtful about these interface names in the future.  Thanks!
