### ISSUE TITLE
How to use CMake to add tf which builded by bazel into project?

### ISSUE THREAD

**Issue by Junhuan-Peng** [tensorflow/tensorflow#30426]
Hello, I am confused by importing the tf into my project with CMake,  I compiled the tensorflow with bazel,without GPU support.
I dont know how to write the CMakeLists. I am not so clear about the compiling result of the bazel, there are severl folders, how should I do to use these folders in my CMakeLists ?
Hope your reply, Thx :)

**Comment by Junhuan-Peng** [comment]
tensorflow : 1.14.0, I download it from release, and I use the Windows10.

**Comment by Scott-Thomas-Dev** [comment]
I would recommend starting with CMakeLists found in the tensorflow/contrib/Cmake folder.
The bazel system might take a while to recreate in CMake if you were to start from scratch... :D

**Comment by Junhuan-Peng** [comment]
Thx! I would try this way. 
Maybe I should use some preview versions  _(:з)∠)_ ,  not the lastest 😭

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Junhuan-Peng** [comment]
So sorry about that, I will notice the problem next time.
we solve this problem of tensorflow with another solution. It looks like that my partner compile it with only c api. Our project is a Qt project, so we use the .pro file, instead of  cmake.

**The Details**:
OS: **Windows 10 profession edition(x64)**.
TensorFlow verison: **1.14.0**, compiled from source.

I compiled it successfully(with the commond ``` bazel.exe build  //tensorflow:libtensorflow_cc.so ```), I just cant use it with cmake. So sorry about  that I cant provide you the error output information because I had delete the CMakeLists that I used.

if it's possible, could you please provide a CMakeLists template of the project which would use the cpp and tf. 

And thanks for your reply! \(￣︶￣*\))

**Comment by rmothukuru** [comment]
@Junhuan-Peng ,
Thank you for the information. Building Tensorflow using CMake is not supported from TF Version, 1.11. Please refer this [link](https://www.tensorflow.org/install/source_windows#tested_build_configurations), for details.

**Comment by rmothukuru** [comment]
Closing the issue as Tensorflow could be installed successfully using Bazel.
