### ISSUE TITLE
Batched tf.linalg.eigh is much slower on GPU than on CPU for many small matrices

### ISSUE THREAD

**Issue by calincru** [tensorflow/tensorflow#30466]
**Describe the current behavior**
See title.

**Describe the expected behavior**
There shouldn't be such a big discrepancy between the two (see below).

**Code to reproduce the issue**
```python
import tensorflow as tf
sym = lambda a: 0.5 * (a + tf.matrix_transpose(a))
with tf.device('cpu:0'):
    _ = tf.linalg.eigh(sym(tf.random.uniform((100000, 2, 2))))  # fast (~0.02s)
with tf.device('gpu:0'):
    _ = tf.linalg.eigh(sym(tf.random.uniform((100000, 2, 2))))  # slow (~7.3s)
```

**System information**
- os platform: Linux-4.4.0-154-generic-x86_64-with-debian-stretch-sid
- gpu: GeForce GTX TITAN X
- python version: 3.7.3
- tf.version.VERSION = 1.13.1
- tf.version.COMPILER_VERSION = 5.4.0
- CUDA 10, cuDNN 7

**Comment by gadagashwini** [comment]
@calincru I tried executing the code on Colab with Tensorflow-gpu 1.13.1 but it executed with same duration (~0.01s) for GPU and CPU. Can you try once let us know is this still an issue. Thanks!

**Comment by calincru** [comment]
@gadagashwini The code that I included just builds the graph.  You should either enable eager execution or run it in a session.  Here's a more complete reproducing code that you can run on Colab: https://gist.github.com/calincru/890fbf8ad4b547381adcd2cc632c35e3

**Comment by gadagashwini** [comment]
I could see the GPU performance is much slower than the CPU. I ran the code on Colab with tensorflow-gpu 1.13.1.

**Comment by aaroey** [comment]
@reedwm would you help to take a look? Thanks.

**Comment by calincru** [comment]
Can we expedite this a little bit, please?

FWIW, there's a similar issue in PyTorch (see https://github.com/pytorch/pytorch/issues/22573). But AFAIU cuSolver should be fast for small matrices.  Is it expected to be slower than CPU, though?

**Comment by gkanwar** [comment]
I'm experiencing the same issue running in tensorflow-gpu 1.12.0. Profiling trace attached if this is at all helpful. There are many, many small copies back and forth between CPU/GPU.
[timeline_eigh_gpu.json.tar.gz](https://github.com/tensorflow/tensorflow/files/3468312/timeline_eigh_gpu.json.tar.gz)

**Comment by Kiritsugu17** [comment]
Hi, 
I have experienced the problem already at the beginning of 2019 (https://stackoverflow.com/questions/55655235/tf-linalg-eigh-extremely-slow-on-gpu-normal). I believe the problem is simply how the GPU tries to solve this problem. Without any prove I believe, that the GPU solves one matrix at a time and hence does this with 100.000 matrices of size 2x2 in your case. The problem is, that you try to solve the eigenvalue problem of each matrix of size 2x2 on hundreds if not thousands of cores, which is basically making things worse rather than better. Hence a few (or even one!) fast CPU core is much faster than trying to split a very easy calculation on many slow cores. You should also experience a similar thing if you have a CPU with many cores (lets say 16 cores and 32 threads) - at least that was what I experienced when I calculated small matrices with scipy.linalg.eighs on 32 threads vs 1 thread.

Overall I have not found any way yet to calculate efficiently many small matrices on the GPU and I am not sure, whether this is actually possible. It would of course be nice, if one could specify that one wants to parallelise things in the batch dimension instead of the matrix dimensions

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
