### ISSUE TITLE
How to reuse conv layers with keras

### ISSUE THREAD

**Issue by Student-HXJ** [tensorflow/tensorflow#30487]
my data shape is [91,109,91,27] and I unstack the one data to 27 data which shape is [91,109,91,1],

I want to use the convnet to extract the feature. But here is loop my Net 27 times. So how could I reuse the Network for just one time?

Description of the problem in the code comment
```python
x_in = Input(shape=shape) # my data shape is [91,109,91,27]

x = Lambda(self.unstack)(x_in) # there I unstack the data to 27 datas shape is [91,109,91]

t_list = []
for i in range(len(x)): # loop 27 times
   x_expand = Lambda(self.expand)(x[i])  # change the data shape to [91,109,91,1]

   feature = self.cnn_block(x_expand)# here is my Net with 3 convs --->
# I build a convnet here, and I want to reuse the network, but here it is looping 27 times. so is there a way to reuse the cnn_block in keras?

   x_out = Lambda(self.expand)(feture)
   t_list.append(x_out)

x = Concatenate(axis=-1)(t_list)

```

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
