### ISSUE TITLE
ScatterSub on GPU

### ISSUE THREAD

**Issue by dennybritz** [tensorflow/tensorflow#305]
I tried running a CNN with embedding layer on a GPU (AWS), but ran into the same problem as described here: http://stackoverflow.com/questions/33624048/fail-to-run-word-embedding-example-in-tensorflow-tutorial-with-gpus

`ScatterSub` doesn't seem to be supported on GPUs and the device placement fails. It would be great if was :) 

It would be great if the examples worked on GPUs.

**Comment by girving** [comment]
Agreed, scatter on GPUs would be useful.  Also gather.

**Comment by avostryakov** [comment]
I will be great for NLP tasks like machine translation to work and re-train embeddings matrix on GPU. So, gather and scatterSub should work on GPU.

**Comment by schmiflo** [comment]
I agree, this functionality would be great to have. Any news on the progress?

**Comment by girving** [comment]
Progress here: https://github.com/tensorflow/tensorflow/pull/782

**Comment by fpmchu** [comment]
Note that while this is progress, and you can theoretically remove the ```with tf.device('/cpu:0')``` line, it wouldn't work completely, because many underlying ops are still not GPU enabled (you can see this if you use ```with tf.device('/gpu:0')``` in ```word2vec_basic.py```).  My guess is that because ```scatter_sub``` is an inline operation, if there's no GPU op, TF just fails; whereas for non-inline operations, TF just knows to copy data back and forth dynamically.  So for something like word2vec_basic.py where a lot of the underlying expensive ops don't have a GPU kernel, you end up using GPU for some and CPU for others, which doesn't speed things up AFAICT.

**Comment by caisq** [comment]
There are unit tests that are failing on the GPU configuration due to this issue: 
//tensorflow/models/embedding:word2vec_test
//tensorflow/models/embedding:word2vec_optimized_test

When is the fix for ScatterSub support on GPU coming?

**Comment by vrv** [comment]
I believe ScatterSub on GPU now is implemented thanks to @fpmchu
