### ISSUE TITLE
Choosing device on NNAPI

### ISSUE THREAD

**Issue by abrarmatin** [tensorflow/tensorflow#30579]
I would like to call specifically into the NPU of a device. Is there a way to call into NNAPI from the application level that will allow such behavior?

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
