### ISSUE TITLE
TensorflowLiteSwift fails pod validation

### ISSUE THREAD

**Issue by robseward** [tensorflow/tensorflow#30577]
**System information**
- OS Platform and Distribution: MacOS 10.14.5
- TensorflowLiteSwift Pod version: 0.2.0
- Commit: 477447155b
- Cocoapods version: 1.7.3
- Xcode version: 10.2.1

**Describe the problem**

When running the command `pod spec lint`, tests fail because `i386` architecture cannot be found. This happens not only on my machine, but also on our private pod system. Failing validation means we cannot use the pod for our apps without turning off the tests. 

**Provide the exact sequence of commands / steps that you executed before running into the problem**

1. cd to TensorflowLiteSwift directory
2. run `pod spec lint --verbose` 

**Any other info / logs**

[here's the output](https://github.com/tensorflow/tensorflow/files/3378927/log.txt)

I was able to resolve this issue by upping the the iOS deployment target in the podspec from 9.0 to 11.0. I believe `pod spec lint` wants to compile a 32 bit version of TensorFlowLiteC for iOS 9 and 10, but the TensorFlowLiteC binary only contains `x86_64` and no `i386`. A more robust solution might be to compile for `i386`. Or it may be possible to configure the podspec to only execute tests on arm and `x86_64`.

**Comment by yyoon** [comment]
Is this still a problem for you? When I run `pod spec lint --verbose --allow-warnings TensorFlowLiteSwift.podspec` in the `tensorflow/lite/experimental/swift` directory, it succeeds on my side.

A few more things to note.
* The i386 target is now included in the `TensorFlowLiteC` nightly binaries (as of 29e6eafad33725f3c1b8f0dae54c702df804e03d).
* The `--allow-warnings` flag will be needed due to a swift version related warning.
* If the missing `i386` still causing you a problem, you could also use `--skip-import-validation` to pass the lint, although it's not ideal.

Please let me know.

**Comment by robseward** [comment]
We turned off the tests for this pod as a short-term workaround. Also, since we only support the last 2 versions of iOS, since iOS 13 is out we'll drop support for iOS 10 which should also fix the problem.

**Comment by yyoon** [comment]
Sounds good. Let me close this bug for now.
