### ISSUE TITLE
compile_nsync.sh does not exist

### ISSUE THREAD

**Issue by phil123456** [tensorflow/tensorflow#30623]
compile_nsync.sh does not exist
yet again I give it up
FUCK GOOGLE
FUCK TENSORFLOW

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github](https://github.com/tensorflow/tensorflow/issues/new/choose) new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
