### ISSUE TITLE
RPI3 - g++-4.8 does'nt exist on debian buster (june 2019)

### ISSUE THREAD

**Issue by phil123456** [tensorflow/tensorflow#30621]
no way I am gonna fill this
guys, update your doc please ;-)

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rmothukuru** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
