### ISSUE TITLE
Best practice of using tensor-core on TensorFlow r1.12

### ISSUE THREAD

**Issue by jw447** [tensorflow/tensorflow#30729]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): CentOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): r1.12
- Python version: 3.6
- Bazel version (if compiling from source): 0.19
- GCC/Compiler version (if compiling from source): 4.8.5
- CUDA/cuDNN version: cuda 9.2
- GPU model and memory: Volta 100

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

I'm wondering what is the best practice of leveraging V100 GPU on TensorFlow r1.12. I understand that Nvidia support it nicely with their TensorFlow container and TF-nightly build may have good support as well. For older version of TensorFlow, (r1.12 or r1.13), is "--use_fp16=True" and "--xla_compile=True" the best practice of leveraging tensor-cores?

Right now my benchmark results indicates that fp16/xla can give 844 images/sec (resnet50, batch size = 128) while fp32/no xla gives 412.5. It is no where near the reported 3x improvement. 

Thank you,

**Comment by tlkh** [comment]
@jw447 can you share which exact script you are using to run the benchmark?

The 3x speed-up reported on [this page](https://devblogs.nvidia.com/nvidia-automatic-mixed-precision-tensorflow/) includes **doubling the batch size to 256**. This could explain the bulk of the difference.

In addition, I noticed that you are using CUDA 9.2 (and most probably a older version of cuDNN as well). Simply upgrading to CUDA 10.0 and the latest cuDNN (7.6 at time or writing) along with TF1.14 will increase performance due to performance enhancements in TF/cuDNN etc. 

The `--use_fp16=True` option should be enabling mixed precision, which will enable the use of Tensor Cores, while the `--xla_compile=True` enables the XLA compiler which allows TF to fuse GPU kernels to increase performance by reducing the overall overhead of kernel launches, unnecessary transposes etc.

Going forward, the suggested way of tapping into Tensor Cores is to use the new **Automatic Mixed Precision (AMP)** API available in TF 1.14 and newer. You can find out more about AMP on this [page](https://developer.nvidia.com/automatic-mixed-precision) or on some improved documentation currently stuck at PR #29249 .

**Comment by jw447** [comment]
Hi @tlkh,

Thanks for getting back to me. The script I'm using is as follows:

args='--data_format=NCHW --batch_size=512 --num_batches=100 --model=resnet50 --optimizer=sgd --variable_update=replicated --all_reduce_spec=nccl --use_fp16=True --xla_compile=False --nodistortions --gradient_repacking=2 --datasets_use_prefetch=True --per_gpu_thread_count=2 --loss_type_to_report=base_loss --compute_lr_on_cpu=True --single_l2_loss_op=True --local_parameter_device=gpu --num_gpus=6 --display_every=10'

script='~/benchmarks/scripts/tf_cnn_benchmarks/tf_cnn_benchmarks.py'

jsrun --nrs 1 --tasks_per_rs 1 --rs_per_host 1 --gpu_per_rs 6  python $script $args

I will try TensorFlow 1.14 with CUDA 10.0 and cudnn 7.6. Is the env variable TF_ENABLE_AUTO_MIXED_PRECISION available in TensorFlow 1.14 already?

Many thanks!

**Comment by tlkh** [comment]
In TensorFlow 1.14, automatic mixed precision is available via the `tf.train.experimental.enable_mixed_precision_graph_rewrite` function call. 
Here's a simple example how to use it with tf.keras. The usage in TensorFlow is very similar, just wrap a `tf.train.Optimizer` instead. 

```python

model = tf.keras.models.Sequential([
    ...
])

opt = tf.keras.optimizers.SGD()
opt = tf.train.experimental.enable_mixed_precision_graph_rewrite(opt)

model.compile(loss="categorical_crossentropy",
              optimizer=opt,
              metrics=["accuracy"])

model.fit(x_train, y_train,
          batch_size=batch_size,
          epochs=epochs)
```

**Comment by ymodak** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
