### ISSUE TITLE
How do you export this model into a tensorflow model

### ISSUE THREAD

**Issue by thekingrenz23** [tensorflow/tensorflow#30732]
Im following this code to train a CNN image classifier to classify Philippines currency. How would you export this model? to get the file to be interpreted by tensorflow

**Comment by anush-o** [comment]
@thekingrenz23 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by anush-o** [comment]
Closing due to lack of recent activity.Thanks!
