### ISSUE TITLE
fit_generator with use_multiprocessing=True causes memory usage grow (leakage) on TF 1.13+

### ISSUE THREAD

**Issue by jsnowacki** [tensorflow/tensorflow#30801]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 9 (GCP AI Platform Jobs and notebooks), Ubuntu 18.04 (custom) 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): preinstalled via official GCP deep learning VM image, also via pip and conda
- TensorFlow version (use command below): 1.13 and 1.14
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10
- GPU model and memory: NVIDIA Tesla K80 and GFX 1080

**Describe the current behavior**
We use `fit_generator` with a custom build on `tensorflow.keras.utils.Sequence`, but we also have seen similar behavior with `tensorflow.keras.preprocessing.image.ImageDataGenerator`. Namely, when we have the default `use_multiprocessing=False`, the training process is slow but the memory usage saturates at some point and everything works fine. When we use `use_multiprocessing=True`, despite the number of workers or `max_queue_size` the memory keeps growing linearly up to the point when the process gets killed by the system. See the enclosed memory graph from GCP AI Platform Job monitoring: 
![ai_job_mem](https://user-images.githubusercontent.com/1014323/61370638-2bcc9f00-a893-11e9-829e-7ed1ee16039d.png)
The same code worked fine on TF 1.12, i.e. the memory saturated at some point, but broke from 1.13, and we see the same effect with 1.14. 
**Describe the expected behavior**
The memory shouldn't grow indefinitely as it did in TF 1.12. See the memory timeseries for TF 1.12 below:
![ai_job_mem_ok](https://user-images.githubusercontent.com/1014323/61373323-ca5bfe80-a899-11e9-857d-47c85f985a78.png)

**Code to reproduce the issue**
Our Data Generator looks as follows:
```python
class DataGenerator(tf.keras.utils.Sequence):
    def __init__(self, affect_net_dir, data_file, batch_size, aug=True):
        self.affect_net_dir = affect_net_dir
        with FileIO(os.path.join(self.affect_net_dir, data_file), 'r') as fr:
            self.data = pd.read_csv(fr)
        self.batch_size = batch_size
        self.aug = aug
        self.indexes = np.arange(self.data.shape[0])
        np.random.shuffle(self.indexes)

    @property
    def steps(self):
        return int(np.floor(self.data.shape[0] / self.batch_size))

    def __getitem__(self, index):
        batch_indexes = self.indexes[index * self.batch_size: (index + 1) * self.batch_size]

        x = np.zeros(shape=(self.batch_size, 224, 224, 3))
        y = np.zeros(shape=(self.batch_size, 11))

        for i, b_index in enumerate(batch_indexes):
            file_path = self.data.iloc[b_index]['subDirectory_filePath']
            with FileIO(os.path.join(self.affect_net_dir, file_path), 'rb') as fr:
                face_img = Image.open(BytesIO(fr.read()))
            face_x = self.data.iloc[b_index]['face_x']
            face_y = self.data.iloc[b_index]['face_y']
            face_width = self.data.iloc[b_index]['face_width']
            face_height = self.data.iloc[b_index]['face_height']
            expression = self.data.iloc[b_index]['expression']
            # crop face from image
            face_img = face_img.crop([face_x, face_y, face_x + face_width, face_y + face_height])
            face_img = face_img.resize(size=(224, 224), resample=Image.LANCZOS)
            face_img = tf.keras.preprocessing.image.img_to_array(face_img)

            # face augmentation if needed
            if self.aug:
                if np.random.rand() >= 0.5:
                    face_img = face_aug.random_brightness(face_img)
                if np.random.rand() >= 0.5:
                    face_img = face_aug.random_hue(face_img)
                if np.random.rand() >= 0.5:
                    face_img = face_aug.random_saturation(face_img)
                if np.random.rand() >= 0.5:
                    face_img = face_aug.random_contrast(face_img)
                if np.random.rand() >= 0.5:
                    face_img = face_aug.horizontal_mirror(face_img)

            x[i] = face_img
            y[i] = tf.keras.utils.to_categorical(expression, num_classes=11)

        return tf.keras.applications.resnet50.preprocess_input(x), y

    def __len__(self):
        return int(np.floor(self.data.shape[0] / self.batch_size))
```
But it is quite problem specific and we use it with a large data set O(100k) samples. 

You can reproduce a similar memory growing behaviour with the Flower example https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l05c04_exercise_flowers_with_data_augmentation_solution.ipynb. When I run it on GCP AI Platform notebook with TF 1.14 and NVIDIA Tesla K80, with multiprocessing on, i.e. (train the model section):
```python
epochs = 80

history = model.fit_generator(
    train_data_gen,
    steps_per_epoch=int(np.ceil(train_data_gen.n / float(batch_size))),
    epochs=epochs,
    validation_data=val_data_gen,
    validation_steps=int(np.ceil(val_data_gen.n / float(batch_size))),
    use_multiprocessing=True,
    workers=3,
)
```
I get the below memory plot in Stackdriver:
![ai_job_mem_sample](https://user-images.githubusercontent.com/1014323/61373689-bf559e00-a89a-11e9-95e5-397ce8c1113f.png)
It is not as profound but the same trace remains quite flat when train with `use_multiprocessing=False`. I guess in our case the number of iteration within one epoch, combined with the linear memory growth kills the machine.

**Comment by theGOTOguy** [comment]
I'm having this same issue, and wanted to confirm that from my experience it's still happening in Tensorflow 2.2.0.  I'm running a method similar to [NIMA](https://arxiv.org/abs/1709.05424).  I'm using `tf.keras`' `ImageDataGenerator` to pre-process the images, and then a second generator wrapping that one to perform a random crop of the image in order to get a patch that can be trained on.  It's not possible to keep the GPU saturated as the method bottlenecks on the CPU-based pre-processing, so multiprocessing is essential.  Further, according to [this bug](https://github.com/keras-team/keras-preprocessing/issues/145), the Keras team seems to believe that the warnings about bad interactions in multiprocessing can be safely ignored and that `ImageDataGenerator` is thread-safe.  I hope that what follows will help diagnose and fix the issue:

I've noticed that the system never crashes with a single thread, but on multiple threads fails increasingly quickly.  I profiled the memory with `guppy` after each epoch, as such:

```
from guppy import hpy

# Profile memory, if desired.
class MemoryProfilerCallback(keras.callbacks.Callback):
  def __init__(self, session):
    self.session = session

  def on_epoch_end(self, epoch, logs=None):
    print(self.session.heap())

if args.memory_profile:
  profile_session = hpy()
  cp_callbacks.append(MemoryProfilerCallback(profile_session))

model.fit(..., callbacks=cp_callbacks, ...)
```

The memory leak consists of a lot of `np.ndarray` objects corresponding to the image patches, and the garbage collector won't pick them up. I did try a custom `GarbageCollectorCallback` that simply calls `gc.collect()` which did not alleviate the issue.  This means that something, somewhere, is still holding onto a reference to these `np.ndarray` objects.

The raw number of `np.ndarray` objects at the end of each epoch gives us a hint as to what's going on:
```
Epoch		1-CPU		3-CPU		Ratio
1		247		759		3.07
2		255		1308		5.13
3		257		1785		6.94
4		259		2260		8.72
5				2759
6				3262
7				3763
```

It makes sense that the number of arrays might be triple initially for 3 CPUs, and if it stayed this way then memory wouldn't be an issue for me.  However, it appears that after each epoch, 2 of the 3 worker threads never cleaned up their `ndarray`s, and they were left sitting around!  Then, epoch after epoch, the memory growth increases by the requirement of (num_threads - 1) threads, eventually causing an out-of-memory error.

This is all to say that if I were debugging the issue, I'd be looking at where the worker threads are being shut down and their memory freed, and in particular for an error where an operation is being applied to one thread where it should be applied to all.

**Comment by atotev** [comment]
https://fantashit.com/linearly-increasing-memory-with-use-multiprocessing-and-keras-sequence/#comment-254237

**Comment by rmothukuru** [comment]
@jsnowacki,
Sorry for the delayed response. Can you please go through [this comment](https://fantashit.com/linearly-increasing-memory-with-use-multiprocessing-and-keras-sequence/#comment-254237) and let us know if it helps? Thanks!

**Comment by jsnowacki** [comment]
@rmothukuru well, it's almost 2 years since I posted this, so in my case I cannot even confirm it anymore, as I'm not on the project and we somehow used different approach which works (not workaround really just bigger machine as I recall). So as for me, if TF 2.3.0 solves it, the issue can be closed.

**Comment by rmothukuru** [comment]
@jsnowacki,
Thank you for the confirmation.
