### ISSUE TITLE
error: static assertion failed: Specified Data Type not supported

### ISSUE THREAD

**Issue by maohuui** [tensorflow/tensorflow#30828]
`auto gt_pts_trans = tensorflow::ops::Transpose(root, gt_pts, NULL);`
I used 'tensorflow::ops::Transpose()' and occurred error despite gt_pts is DT_FLOAT

> error: static assertion failed: Specified Data Type not supported
> static_assert(IsValidDataType::value, "Specified Data Type not supported");
> error: ‘v’ is not a member of ‘tensorflow::DataTypeToEnum’
> Tensor t(DataTypeToEnum::v(), TensorShape());

**Comment by anush-o** [comment]
@maohuui ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by anush-o** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by SwuduSusuwu** [comment]
[_Anthropic's Assistant_ says to use `tensorflow::DataTypeTrait`](https://poe.com/s/XaEsG8S8uPtVMl0em2si), which is not found.
[_GitHub_'s _Copilot_ suggests that `tensorflow:DataTypeToEnum` exists but is not always available for public use](https://github.com/copilot/share/c837139e-01e0-80a0-a102-e24920e96817).
This issue is the first search result for [searches of `DataTypeToEnum`](https://duckduckgo.com/?q=%22DataTypeToEnum%22).
Want to know if _TensorFlow_ plans to give `DataTypeToEnum` to users, or if should implement on own. Is [simple to implement this](https://github.com/SwuduSusuwu/SusuLib/blob/f1fb12967d433514a59851a742ce667838f072b7/cxx/ClassTensorFlowCns.hxx#L85-L101), but verbose if want all `tensorflow::DataType`s included, plus will require to remember to add future new `tensorflow::DataType`s to this.
Related search results for `DataTypeToEnum`:
- https://deepmodeling.github.io/abacus-develop/structcontainer_1_1DataTypeToEnum.html
- https://stackoverflow.com/questions/45910776/tensorflow-cpp-with-eigen-element-wise-multiply
- https://blog.csdn.net/HaoBBNuanMM/article/details/114638077
- https://github.com/tensorflow/tensorflow/issues/20586
- https://github.com/tensorflow/tensorflow/pull/21042
