### ISSUE TITLE
How to get the detail type of auto eigen variable in op

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#30831]
The auto variable is annoying in eigen as the interpreter cannot decide how to interpret it. See the detail [here](https://stackoverflow.com/questions/57057123/how-to-get-the-scalar-value-returned-by-eigen-tensors-sqrt-function/57075471#57075471)

**Comment by anush-o** [comment]
@sjtusmartboy ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by sjtusmartboy** [comment]
Ubuntu 18.10 Tf 14 compiled from source

I modify the code [here](https://github.com/tensorflow/tensorflow/blob/c174697c09737e543e1919ca5cd5cfc373a96012/tensorflow/core/kernels/training_ops.cc#L2310) in line 2310 and 2311 to be the code as follows

auto linear_square = linear * linear;                                        
auto linear_square_sum = linear_square.sum();                         
Eigen::Tensor<T,0> _linear_l21_norm = linear_square_sum.rsqrt();
auto x =  linear.constant(_linear_l21_norm()) * linear.constant(l1_scalar) * linear.constant(static_cast<T>(sqrt(inner_dim)))  * linear - linear; 

which gives me the error at the third code line, maybe the error is about the type mismatch of Eigen::Tensor<T,0>. I can cout the value of _linear_l21_norm if I modify the code to be 

auto _linear_l21_norm = linear_square_sum.rsqrt();

but since I want to construct an array same size with that of the 'linear' and the parameter of constant must be of type scalar, I give the variable _linear_l21_norm the type of Eigen::Tensor<T,0>. Unfortunately, it gives the static assert error when compiling and it tells me I made a programming mistake. So my question is how I can construct the array linear.constant(_linear_l21_norm()) and why the type of Eigen::Tensor<T,0> cannot be assigned to _linear_l21_norm.

**Comment by alextp** [comment]
Can you ask this question in the eigen repository? I don't think it's TF-specific.
