### ISSUE TITLE
TensorFlow r0.9 warning warns about Deprecation and recommends itself.

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#3085]
TensorFlow r0.9:

```
In [3]: tf.logging.warning('asdf')
/home/hholst/anaconda3/envs/tf-r0.9/bin/ipython:1: DeprecationWarning: The 'warn' method is deprecated, use 'warning' instead
  #!/home/hholst/anaconda3/envs/tf-r0.9/bin/python
WARNING:tensorflow:asdf
```

**Comment by danmane** [comment]
That is pretty funny :)

It is really easy to fix if you want to fix it.
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/platform/tf_logging.py#L56
Change it to use logger._warning (and verify that everything still works)

**Comment by claguna** [comment]
Sorry if this is a naive question:

What is the standard way to verify that "everything still works"?
Is there a test suite to validate changes?

**Comment by danmane** [comment]
You can run bazel test //tensorflow/... to run every test, although that will be unnecessary since it will test a lot of code you haven't touched at all. bazel test //tensorflow/python/... is plenty.

When you submit a PR, we will have Jenkins test it, and this will test and build the code in several different environments.

**Comment by tcfuji** [comment]
@danmane I verified that there was no change in the amount of errors both before and after the change.
