### ISSUE TITLE
tensorbaord graph broken for multi-gpu (cifar10 example)

### ISSUE THREAD

**Issue by JianbangZ** [tensorflow/tensorflow#3087]
![graph-run 1](https://cloud.githubusercontent.com/assets/15835199/16431922/c084e280-3d50-11e6-9b9d-5169d84ae865.png)
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.
### Environment info

CentOS 6 (64 bit) + NVidia K80

Installed version of CUDA and cuDNN: 
CUDA 7.5, cuDNN v4

If installed from binary pip package, provide:
1. Which pip package you installed.
   The lateset (0.9 with GPU)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
   0.9.0
### Steps to reproduce
1. Locate the cifar10 example https://github.com/tensorflow/tensorflow/tree/master/tensorflow/models/image/cifar10
2. run "python cifar10_multi_gpu_train.py --num_gpus=2"
3. Check the tensorboard results from events. The "GRAPHS" doesn't look right
### What have you tried?
1. I tried to run the single GPU version of cifar10 example "python cifar10_train.py", Tensorboard graph looks normal
2. I tried "python cifar10_multi_gpu_train.py --num_gpus=1", Tensorboard graph broken
3. I didn't try a early version of tensorflow this time, but I remember the Tensorboard used to work with the cifar10 multi-gpu example
### Logs or other output that would be helpful

(If logs are large, please upload as attachment).

**Comment by heibaidaolx123** [comment]
Same problem for imagenet multi-GPU training.

**Comment by dsmilkov** [comment]
Hi @JianbangZ ! Thanks for reporting.

The reason why the multi-GPU graph looks like that is because the namescoping in the multi-GPU version creates tower_N namespaces that have incoming edges (tensors) above a certain threshold, at which point we extract those nodes on the side since usually they end up being auxiliary and not part of the main net architecture.

If we don't extract nodes on the side, many graphs will be highly intertwined and un-readable. The current threshold for incoming edges was decided empirically, but as this example suggest, it is not ideal. We will try out different thresholds and heuristics and get back to you!

**Comment by JianbangZ** [comment]
Hi @dsmilkov  is this issue fixed in 0.10.0?

**Comment by drpngx** [comment]
Assuming this was fixed in later versions. Feel free to open a new issue if the problem persists with new code.

**Comment by monjoybme** [comment]
Getting almost similar unconnected series. Is it fine for CIFAR10 multi GPU code? Please suggest. 

<img width="1390" alt="screen shot 2019-01-16 at 11 25 47 am" src="https://user-images.githubusercontent.com/17875749/51267948-e6372400-198c-11e9-91db-12becf7097a0.png">
