### ISSUE TITLE
Problems with running keras models in colab TPU

### ISSUE THREAD

**Issue by kushalj001** [tensorflow/tensorflow#30916]
```
filepath = "./xlnet_models/batch-128/saved-model-128-{epoch:02d}-{acc:.2f}--{loss:.5f}.hdf5"
save_callback = tf.keras.callbacks.ModelCheckpoint(filepath)
model.fit_generator(train_generator_128,epochs=20,callbacks=[save_callback])

```
`fit_generator` is not supported for models compiled with tf.distribute.Strategy.

Is there any way to solve this?

**Comment by gadagashwini** [comment]
@kushalj001 Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

In order to expedite the trouble-shooting process, please provide a complete code to reproduce the issue reported here. Thanks!
