### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'keys'

### ISSUE THREAD

**Issue by dee98** [tensorflow/tensorflow#30976]
I am trying to make classification using tensorflow 

I am using anaconda version 1.7.2 on Ubuntu 18.04.2 LTS and python 3.7.3

i downloaded retrain.py code from [ https://github.com/tensorflow/hub/blob/master/examples/image_retraining/retrain.py](url)

 when i run this file i got error 

`File "retrain.py", line 1349, in <module>
    tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
  File "/home/deepak/anaconda3/lib/python3.7/site-packages/tensorflow/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/deepak/anaconda3/lib/python3.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/deepak/anaconda3/lib/python3.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "retrain.py", line 1006, in main
    class_count = len(image_lists.keys())
AttributeError: 'NoneType' object has no attribute 'keys'`

i was running this command to run that file 

`python retrain.py --image_dir ~/home/deepak/new_data_EHL/Augmented --learning_rate=0.0001 --testing_percentage=20 --validation_percentage=20 --training_batch_size=32 --validation_batch_size=-1 --eval_step_interval=100 --how_many_training_steps=10 --random_scale=30 --random_brightness=30 --architecture mobilenet_1.0_224 --output_graph=output_graph.pb --output_labels=output_labels.txt`

i am a beginner in tensorflow and deep learning i searched about the solution but i couldn't get the solution that work.

**Comment by pandrey-fr** [comment]
Hi,
This is actually not a tensorflow issue, the exception is apparently raised because the `create_image_lists` function returns a `None` value instead of the expected `OrderedDict`. I would advise you to run Python in a terminal, copy/paste the `retrain.py` file's content save for the `if __name__ == '__main__'` final block (or run `from retrain import `create_image_lists` if the file is in your working directory) and try to call it withe the proper arguments - so, in your case, `create_image_lists('~/home/deepak/new_data_EHL/Augmented', 20, 20)`. See what this returns, whether you get warnings, etc. If you do not get a dict with information on your images, maybe try running the function's code line by line to see where it goes wrong...
Good luck!

**Comment by gadagashwini** [comment]
@dee98 Please provide the correct link for retrain.py. 
And also, let us know @pandrey-fr's comment resolve your issue. Thanks!

**Comment by dee98** [comment]
@gadagashwini link of retrain.py  `https://github.com/tensorflow/hub/tree/master/examples/image_retraining`
yes @pandrey-fr  comment resolve my issue
this error occured because i was using "~" this sign in my image path

Thanks for help me

**Comment by pandrey-fr** [comment]
@dee98 You are welcome :)
