### ISSUE TITLE
CUDA optimization: using read-only cache

### ISSUE THREAD

**Issue by ThisIsIsaac** [tensorflow/tensorflow#31052]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**

@chsigg 

I wanted to propose adding `__restrict__` or `const __restrict__` tags on `input` and `output` arrays of ALL tensorflow kernels. But before I go on, I wanted to check a couple things:

1. can I assume that input and output arrays given to a CUDA kernel do not overlap?
2. Can I assume that input arrays are not modified, or would I have to check this per-kernel bases?

**Will this change the current api? How?**

**Who will benefit with this feature?**

Since pytorch arrays are stored in NHWC data layout, many kernels waste global memory read bandwidth. By adding `__restrict__` or `const __restrict__` tags, we can let the compiler cache the reads to read-only cache which displays about 50 ~ 100x faster clockspeed on memory reads.

**Any Other info.**

**Comment by rmothukuru** [comment]
@ThisIsIsaac ,
In order to answer your questions, 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ThisIsIsaac** [comment]
@rmothukuru 

Operating system: all operating systems

architecture: any Nvidia GPU with compute capability over 3.0

Tensorflow version: NA

I got response from @chsigg via email. Seems like I can assume the two ( any exceptions should be caught by pre-built unit tests ). I will go a head with a pull request with in a couple days.

**Comment by rmothukuru** [comment]
@ThisIsIsaac ,
Thank you for the details. Once you raise the pull request, can you please give reference of that Pull Request in this issue so that we can track it accordingly.

**Comment by ThisIsIsaac** [comment]
Made a pull request [here](https://github.com/tensorflow/tensorflow/pull/31223)

**Comment by bhack** [comment]
Can we close this?

**Comment by ymodak** [comment]
Closing this issue since the associated PR has been merged. Thanks!
