### ISSUE TITLE
Instructions for updating: Use standard file APIs to delete files with this prefix. While training chicken pose estimation algorithm

### ISSUE THREAD

**Issue by SumairSaeed** [tensorflow/tensorflow#31069]
![11](https://user-images.githubusercontent.com/53338377/61946734-c710f300-afbc-11e9-8f08-b2eab9a06445.PNG)

While training chicken pose estimation data on google colab using this pose estimation algorithm, this is the point where it stucks.  This is the command i am using;
"import os
os.chdir("/content/gdrive/My Drive/pose-tensorflow-master/models/coco/train")
!ls ../../
!TF_CUDNN_USE_AUTOTUNE=0 CUDA_VISIBLE_DEVICES=0 python3 ../../../train.py"
what should i do for that?

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by omega-accelr** [comment]
Adding following line solved this issue for me.

tf.compat.v1.disable_v2_behavior()
