### ISSUE TITLE
Tensorflow-lite gpu ios memory leak

### ISSUE THREAD

**Issue by zuoshaobo** [tensorflow/tensorflow#31092]
I use TensorFlowLiteGpuExperimental  for inference ,I have 60 models, if i only use one model to inference ,it works well, but if i switch different models in running , than memory leak occurs, I just use code :
            interpreter = nullptr;
            DeleteGpuDelegate(delegate);
to free resources
so if i loss other free function ?
if TensorFlowLiteGpuExperimental a bug?
TensorFlowLiteGpuExperimental the newer version number is what?

**Comment by aselle** [comment]
I assume you are storing interpreter in a std::unique_ptr so that interpreter=nullptr doesn't leak.
Could you give a complete repro example. Reassigning @impjdi who has more insight.

**Comment by NALanhnt2** [comment]
sorry about my english. I use tensorflow and i leak memory on ip. Does anyone have the same problem and how can i fix it

**Comment by impjdi** [comment]
@zuoshaobo Sorry, I missed this re-assignment... and this is already over a year old.  My apologies.

We don't have experience with multiple gpu delegates, but usually, deleting the GPU delegate and the interpreter (maybe the other way around... I forgot.  there is a particular order) should be clean without memory leaks.  Given that this bug is quite old without updates, I assume the OP solved the issue by him/herself and will close the bug.  Feel free to reopen.

@NALanhnt2 I think it's better to create a new issue for this with additional information.  If you say "it doesn't work on ip", it doesn't tell us much.
