### ISSUE TITLE
How to create a tensorflow lite plugin for Unity

### ISSUE THREAD

**Issue by Deepak-HpyAda** [tensorflow/tensorflow#31119]
I'm trying to use tensorflow lite in unity.
I need plugins to run my project.
Especially a **plugin for IOS** [tensorflowlite_c]

Thank you!

**Comment by anush-o** [comment]
@Deepak-HpyAda ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information.

**Comment by anush-o** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by joaocc** [comment]
Hi. Any updates on this? Thx

**Comment by jwaychee** [comment]
Hi. Is it possible to build the tensorflowlite_c.a static library for use in iOS? The readme only listed the bazel command for Android and linux but not for iOS.

**Comment by asus4** [comment]
Hi, a simple way is importing pre-build `TensorFlowLiteC.framework` from CocoaPods

Just make the blank Xcode project with Podfile and copy it.
```
pod 'TensorFlowLiteObjC', '0.0.1-nightly'
```

and need to modify `[DllImport (TensorFlowLibrary)]` to  `[DllImport (__Internal)]`
of use my PR #34450
