### ISSUE TITLE
Tensor flow not found - spyder

### ISSUE THREAD

**Issue by AlbiBone** [tensorflow/tensorflow#31142]
Hello,
I am new of python environment.
I want to use spyder and tensor flow in windows PC, but I get the error: 

`no module named 'tensorflow' spyder`

I simply downloaded anaconda from https://www.anaconda.com/distribution/#download-section.
What's wrong? I already tried to look for similar problems on internet but I am quite confused to the procedure. Can you provide me a step-by-step guide on how to install the module?

Thank you so much,
A

**Comment by akshika47** [comment]
Could you post your code snippet here?

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by AlbiBone** [comment]
I am using a Windows 7 i7 pc, and the Anaconda version is "Anaconda 2019.07 for Windows Installer" that you can see in the link: https://www.anaconda.com/distribution/#download-section
and then I installed the anaconda with "Python 3.7 version" (at left).

But good news: now I write in the anaconda prompt:
'pip install tensorflow' and now the code works without problem of 'no module named 'tensorflow' spyder'.
Therefore thank you so much for your help but I think that it is already solved (I don't know how exacly).
Kindly regards!

**Comment by rmothukuru** [comment]
@AlbiBone ,
Good to know that your issue is resolved. If I understand it correctly, you were trying to 
`import tensorflow` without running `pip install tensorflow`. Now that you have run `pip install tensorflow`, you could `import` it without any error.

**Comment by rmothukuru** [comment]
Are you satisfied with the resolution of your issue?<br> [Yes](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=Yes&entry.2137816233=31142)<br> [No](https://docs.google.com/forms/d/e/1FAIpQLSfaP12TRhd9xSxjXZjcZFNXPGk4kc1-qMdv3gc6bEP90vY1ew/viewform?entry.85265664=No&entry.2137816233=31142)
