### ISSUE TITLE
same one line code but get different type.

### ISSUE THREAD

**Issue by gschen** [tensorflow/tensorflow#31160]
```python
import tensorflow as tf
import numpy as np

# 2.0.0-beta1
print(tf.__version__)

# [P1]Out result is: tensorflow.python.framework.ops.EagerTensor
print(type(tf.random.uniform([], maxval=1.0)))

def preprocess(n):
    # [P2]Out result is: <class 'tensorflow.python.framework.ops.Tensor'>
    print(type(tf.random.uniform([], maxval=1.0)))
    return n

ds = tf.data.Dataset.from_tensor_slices(tf.cast([1], tf.float32))\
.map(preprocess, num_parallel_calls=tf.data.experimental.AUTOTUNE)\
.repeat()

```
There is one line same code '**type(tf.random.uniform([], maxval=1.0))**' in two positions [P1],[P2], but we got two different type, one is EagerTensor and the other is Tensor. 

Some people know why? Thanks for your reading.

**Comment by pandrey-fr** [comment]
Hi,

I have an imprecise answer to your question, which should hopefully clarify things for you but might not be entirely accurate from a technical standpoint.

In version 2.0, Eager execution is enabled by default, hence any Tensor you create will be wrapped as an EagerTensor. This is what shows up at position [P1] in your code.

That being said, TensorFlow relies on building computation graphs, and when possible (basically, every time you use a "behind-the-scenes", possibly lower-level, mechanism) a single graph is being built which does not work in Eager mode and is maintained in the background to be reused on different Tensors (with similar specs). In your case, calling `tf.data.Dataset.map` on a function will trigger the conversion of this function (using Autograph and such) so as to define such a re-usable graph. Hence, in the body of the converted function (which is the one being actually called), processed Tensors are no longer Eager. This is also why you sometimes need to wrap some operations that cannot be converted with `tf.py_function`, so that they will be preserved "as-is" in spite of this behaviour (see an example in [this tutorial](https://www.tensorflow.org/beta/tutorials/text/transformer)).

**Comment by pandrey-fr** [comment]
By the way, no offence and I am happy to try to help you, but this is not an issue _per se_ and would be better asked on a questions-answering website such as StackOverflow rather than here ;-)
