### ISSUE TITLE
[TF 2.0 API Docs] tf.tuple

### ISSUE THREAD

**Issue by johnkegz** [tensorflow/tensorflow#31279]
## Documentation contributor guide: 
https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/tuple

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/MyMethod

### Correct links
The GitHub link to `tf.tuple` leads to `tf.tuple_v2`.
### Usage example
There is no usage example.

**Comment by Ir1d** [comment]
Hi @jvishnuvardhan this is not a bug, the link is correct because `tuple_v2` has different param order than `tuple``

**Comment by rmothukuru** [comment]
@johnkegz,
Sorry for the delayed response. This is expected because the implementation of [tf.tuple](https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/tuple) correspond to the **`Tensorflow Version 2.x`** and hence it is pointing to [tuple_v2](https://github.com/tensorflow/tensorflow/blob/v2.0.0/tensorflow/python/ops/control_flow_ops.py#L2911-L2944).

If we observe the [Tensorflow 1.x version of tf.Tuple](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/tuple), it points to [tuple in Github](https://github.com/tensorflow/tensorflow/blob/v1.15.0/tensorflow/python/ops/control_flow_ops.py#L2947-L3014).
Thanks!
