### ISSUE TITLE
[TF2.0] Use Adam and GradientTape() to optimize own function wrt to input (no keras model)

### ISSUE THREAD

**Issue by de-core** [tensorflow/tensorflow#31273]
**Optimization**
I want to optimize my own loss function with adam optimizer of keras, with respect to the input. Unfortunately this doesn't work with GradientTape(). 

**Executed Code with TF2.0**
```
@tf.function
def train(opt, input):
   with tf.GradientTape() as tape:
        tape.watch(input)
        loss = tf.reduce_mean(input)
    gradients = tape.gradient(loss, input)
    opt.apply_gradients(zip(gradients, input))

opt = tf.keras.optimizers.Adam(learning_rate=1)
input = tf.random.normal((1, 1))

train(opt, input)
```

**Current behavior**
Code gives error if `opt.apply_gradients(zip(gradients, input))` is called.
TypeError: Tensor objects are only iterable when eager execution is enabled. To iterate over this tensor use tf.map_fn.

**Comment by WindQAQ** [comment]
@de-core Hi, I think the example has some errors within it:

1. `apply_gradient` takes **list of (gradient, variable) pairs** as input (that's why you use **zip**). However, since `input` is a **tensor** (not a list of tensors), `tape.gradient(loss, input)` thus returns a gradient tensor w.r.t. input. You can find that both `gradients` and `input` are a tensor instead of a list of tensors, implying they are just not iterable while calling `zip`. To fix this, simply modify this line
```python
opt.apply_gradients(zip(gradients, input))
```
with
```python
opt.apply_gradients(zip([gradients], [input]))
```
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/keras/optimizers/Adam#apply_gradients

2. Again, because apply_gradient takes **list of (gradient, variable) pairs**, `input` must be a instance of `tf.Variable` rather than `tf.Tensor`. However, the line `input = tf.random.normal((1, 1))` creating a **tensor** with normal distribution. To make it a `tf.Variable`, wrap it with `tf.Variable` like
```python
input = tf.Variable(tf.random.normal((1, 1)))
```
which means you create a `tf.Variable` with initial value `tf.random.normal(1, 1)`

https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/Variable
https://www.tensorflow.org/versions/r2.0/api_docs/python/tf/random/normal#returns

Thanks!

**Comment by de-core** [comment]
Thank you very much, solved it.

**Comment by gadagashwini** [comment]
Closing the issue since its resolved. Feel free to reopen if the problem still persists. Thanks!
