### ISSUE TITLE
Performance decline after updating from 1.13.1 to 1.14.0

### ISSUE THREAD

**Issue by erikchwang** [tensorflow/tensorflow#31307]
I have observed an obvious performance decline after I update TF from 1.13.1 to 1.14.0, even if the code has never changed. 
I am using CUDA 10.0 and tf.contrib.opt.AdamWOptimizer

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture).  Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
