### ISSUE TITLE
Can't install a version of TF with filter_for_shard

### ISSUE THREAD

**Issue by Griffbo99** [tensorflow/tensorflow#31334]
Hey, 

I'm using a program which calls for filter_for_shard (tf.data.experimetnal.filter_for_shard). The API claims it should exist in TF 1.13, but I have not been able to get this to work (or find the file) with any installation of TF 1.13. Any ideas on what to install to get this working?

Thanks in advance!

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Griffbo99** [comment]
Hey! I solved this problem actually. My program was just looking at a different version which was 1.4 even though I had 1.3 installed elsewhere, so I just pointed it in the right direction. Thanks!
