### ISSUE TITLE
Using another model despite of provided in android sample

### ISSUE THREAD

**Issue by VirRajpurohit** [tensorflow/tensorflow#31406]
@ry @jmhodges 

I have replaced the tensorflow lite (Detect.tflite) model in the android sample.

I ended up with several errors on building the project.

One of them is 

` java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 1080000 bytes and a ByteBuffer with 270000 bytes.`

After some try and error I ended up with another error mentioned below

 `java.lang.IllegalArgumentException: Cannot copy between a TensorFlowLite tensor with shape [1, 1917, 4] and a Java object with shape [1, 3].`

Please look it into asap so can move forward with the sample.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by VirRajpurohit** [comment]
@ravikyram 

I have tried running the Demo on my samsung A50.

Simply I have replaced the detect.tfite with my .tflite file and label file with my file, and ended up with above errors.

Please assist.

**Comment by jdduke** [comment]
> Simply I have replaced the detect.tfite with my .tflite file and label file with my file

You can't simply drop in an arbitrary model and expect the sample to function without any modifications. In particular, depending on your model, the input/output tensors will differ, and you'll need to adjust your usage of the TFLite Interpreter accordingly. Without knowing any additional details about your model, it's impossible to say what is going wrong here, but it's pretty clear that your new model has fundamentally different input shapes and output types than what are used in the sample. 

Have a look at [this guide](https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file) for how to inspect your graph to determine the format of inputs/outputs you should provide.
