### ISSUE TITLE
TensorFlow 1.14 eager execution not working with tf.function

### ISSUE THREAD

**Issue by blaisewang** [tensorflow/tensorflow#31439]
**System information**
- OS Platform and Distribution: macOS Mojave
- TensorFlow installed from: binary
- TensorFlow version: v1.14.0-rc1-22-gaf24dc91b5 1.14.0
- Python version: Python 3.7.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**

I use `tf.math.argmax(predictions).numpy()` to get the prediction in a function. But with the `tf.function` declared before the function, there will raise an AttributeError: 'Tensor' object has no attribute 'numpy'.

**Code to reproduce the issue**
Similar to [this tutorial](https://www.tensorflow.org/beta/tutorials/text/nmt_with_attention), but with `tf.math.argmax(predictions).numpy()` inside the `train_step()` to print the prediction.

**Comment by pandrey-fr** [comment]
Hi,

The whole point of `tf.function` is to disable Eager execution on a portion of your code in favour of building a re-usable computational graph (rather than building and discarding graphs as data comes by) ; it is therefore not a bug, but a feature, that you can no longer use the `numpy` method, which is exclusive to `EagerTensor` (a subclass of the more general `Tensor` type).

If you want to print something, you should use `tf.print` on your `Tensor` (this is also true in contexts when you are handling `EagerTensor` instances, since this is more general and less error-prone than using a combination of the built-in `print` and Eager functionalities). So, in your example, use `tf.print(tf.math.argmax(predictions))`, which will create a print-out node in the built computation graph.
