### ISSUE TITLE
java.lang.RuntimeException: Failed to find input Node 'image_tensor'

### ISSUE THREAD

**Issue by VirRajpurohit** [tensorflow/tensorflow#31470]
Hi,

I have downloaded the sample and tried run the **Android** Example.
It is working fine.

Now I have my own .tflite model and .txt label file I have put them in assets and replaced
**TF_OD_API_LABELS_FILE** ,**TF_OD_API_MODEL_FILE** to my file path 

I have ended up with the error
`java.lang.RuntimeException: Failed to find input Node 'image_tensor'`

I am running this sample on my **samsung A50.**

I am not much aware about any detail but the simple steps as above and the error. Can you guys please take deep dive into this and get me out of it?

**Comment by ymodak** [comment]
Please provide following information:
****System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
**

**Comment by VirRajpurohit** [comment]
@ymodak 

As I have mentioned I am running the sample on my samsung A50.

Only two changes I have made in the sample code that is that changing label file and added my own tflite model, I have ended up with this error


java.lang.RuntimeException: Failed to find input Node 'image_tensor'

**Comment by jdduke** [comment]
Hi @VirRajpurohit, for TFLite please follow [this detection example](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android), not the one in tensorflow/examples/android. The latter is for TensorFlow Mobile, and will soon be removed.
