### ISSUE TITLE
Cocoapods cannot install TensorFlowLiteC

### ISSUE THREAD

**Issue by berkerbilgi** [tensorflow/tensorflow#31538]
I am getting [!] Error installing TensorFlowLiteC when trying to install pods. I am using 
pod 'TensorFlowLiteSwift' in my podfile. 

Error:
[!] Error installing TensorFlowLiteC
[!] /usr/bin/curl -f -L -o /var/folders/8h/w7cb5w9x4m9dg8l9rr3h1qwas0000gn/T/d20208412-2822-n13n01/file.tgz https://dl.google.com/dl/cpdc/9d0ec5e53f4ff34a/TensorFlowLiteC-0.2.0.tar.gz --create-dirs --netrc-optional --retry 2

**Comment by ravikyram** [comment]
@berkerbilgi 

I am not able to open the link you have provided.Please, share the correct link.

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the Github new issue template.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by berkerbilgi** [comment]
@ravikyram 

When i am trying to install "TensorFlowLiteSwift" library with Cocoapods, getting an error. The link is not working and i think this is the problem. Link is provided by google for downloading the TensorFlowLiteC library.
So i cannot share the correct link because it is google link.

**Comment by jdduke** [comment]
@miaout17 can you advise?

**Comment by berkerbilgi** [comment]
@miaout17 is there any update? Still cannot install the library. It gives 404 not found error

**Comment by jdduke** [comment]
Are you using the 1.14 TensorFlowLiteSwift CocoaPod? If not, can you try updating to that version?

**Comment by miaout17** [comment]
The `0.2.0` was an experimental release and it no longer worked. Sorry for your inconvenience. 

To solve this problem: 
If you specified version in Podfile, update it to `1.14.0`. 
Run `pod update`. 

Let us know if it works.

**Comment by berkerbilgi** [comment]
@miaout17 @jdduke thanks for your reply. After pod update and specify version to 1.14.0, I installed successfully.

**Comment by jdduke** [comment]
Thanks again @berkerbilgi for flagging the issue, we've gone ahead and restored the experimental `0.2.0` release to avoid further confusion.
