### ISSUE TITLE
Interrelations of collections and scope counts are not clear from documentation

### ISSUE THREAD

**Issue by Uiuran** [tensorflow/tensorflow#31543]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/GraphKeys

## Description of issue (what needs changing):

The GraphKeys doc is lacking explanation of ('__variable_store',) and ('__varscope',) keys relation to the others collections e to the variable creation in in a variable scope context.
In my modelling, since iam building a dnn from scratch, its cond sine-qua-non to estimate memory usage like given in this  for VGGNet 
http://cs231n.github.io/convolutional-networks/#case

However to me its not clear which tensors summup the computation memory allocations (even if it initializes in the runtime, you should be able to pre-calculate the estimative from the graph builted, before running).

So iam able to realize the relations of scopes counting, variable creation and using, will be hard to do such kind of memory estimation function.

Today iam using ._collections['variables'], i think it subsums the variables used in any session of training.

### Clear description

Collections are created in the modelling process with the intent of variable management for some functional reason. The developer must have a clear image of which is the intent of each collection and the inter-relation of them (this is somewhat done in GraphKeys, but the mentioned keys are lacking).

### Submit a pull request?

Are you planning to also submit a pull request to fix the issue? See the docs
contributor guide: https://www.tensorflow.org/community/contribute/docs and the
docs style guide: https://www.tensorflow.org/community/contribute/docs_style

### More Info

I have seem the RFC and know that the 2.0beta Variable became abs class and the management and implementation is more flexible, but now i dont have time to migrate the code, so i think this is stuff is good to keep-up updated (if it is possible and desirable by TFlow team), more people may be in the same condition .

**Comment by rmothukuru** [comment]
@Uiuran ,
If I understand your description, you want the explanation about `('__variable_store',)` and `('__varscope',)`  in the documentation corresponding to `GraphKeys`. 

If it is so, the documentation about `GraphKeys` is present in this [TF Link](https://www.tensorflow.org/api_docs/python/tf/GraphKeys) and the Code corresponding to `GraphKeys` is present in this [Github Link](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/framework/ops.py#L6144-L6286).

In both the places, I couldn't see the terms mentioned by you `('__variable_store',)` and `('__varscope',)`. 

Can you please be more specific and if possible, can you please provide the exact link of the documentation which you are referring to, so that it would be easy for us to understand and make necessary changes. Thanks!

**Comment by Uiuran** [comment]
('__varscope',) and ('__variable_store',) probably appears in graphs  _collections dictionary, probably  because of the class:
class _VariableStore(object)
in
https://github.com/tensorflow/tensorflow/blob/d61d32a0486953064d172945fa7fb68de8008083/tensorflow/python/ops/variable_scope.py

So it appears as a collection in the graph, to the intent of tracking similar variable scopes, but it's not clear why they appear and how they are count from the documentation.

**Comment by Saduf2019** [comment]
@Uiuran 
Is this still an issue.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
