### ISSUE TITLE
tf.shape() for RaggedTensor is raising an exception

### ISSUE THREAD

**Issue by DEKHTIARJonathan** [tensorflow/tensorflow#31545]
Let suppose the following context:

```python
ragged_tensor = tf.ragged.constant(
    [['All', 'the', 'world', 'is', 'a', 'stage'],
    ['And', 'all', 'the', 'men', 'and', 'women', 'merely', 'players'],
    ['They', 'have', 'their', 'exits', 'and', 'their', 'entrances']]
)

print(isinstance(ragged_tensor, tf.RaggedTensor))   # True

tf.shape(ragged_tensor)[0]   # Should return "3"

>>> TypeError: Failed to convert object of type 
<class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor. 
Contents: tf.RaggedTensor(
    values=Tensor("RaggedConstant/values:0", shape=(21,), dtype=string), 
    row_splits=Tensor("RaggedConstant/Const:0", shape=(4,), dtype=int64)
). 
Consider casting elements to a supported type.

# To obtain the information, one shall call the following:
ragged_tensor.bounding_shape()[0]
```

We should merge the two functionalities into TF.Shape and raise a warning/exception in case someone tries to evaluate a ragged dimension.

**Comment by alextp** [comment]
@edloper do you think we should add dispatch support to tf.shape as well, or do you think that'd be more confusing?

**Comment by DEKHTIARJonathan** [comment]
Any news ? @alextp

**Comment by edloper** [comment]
Which of these is the problem that you're trying to address?

1. You'd like to get the size of some dimension of a ragged tensor.
2. You'd like to do get the size of some dimension of an *optionally* ragged tensor, in a way that works for both tensors and ragged tensors.

For problem 1:

* You can get the size of the outermost dimension with `rt.nrows()`
* You can get the size of inner uniform dimensions with `tf.shape(rt.flat_values)[-n]`.
* You can get the bounding size of any single dimension with: `rt.bounding_shape(axis)`.  For non-ragged dimensions, this will be identical to the actual size.  E.g., `rt.bounding_shape(0) == rt.nrows()`.

For problem 2:

`tf.shape` returns a vector of integers.  There's no backwards-compatibility possibility for changing it to return some other object that will "raise a warning/exception in case someone tries to evaluate a ragged dimension."  And given that we're forced to return a vector of integers, we would have to decide which integer to use for ragged dimensions.  We could use `-1`, but that would lead to some unexpected/unintuitive behavior -- e.g., `tf.reshape(a, tf.shape(b))` would give a surprising result, since `tf.reshape` has a special meaning for `-1`.  So the best solution I can think of would be to introduce some helper function that handles both ragged & dense tensors.  E.g.:

```
def nrows(t):
  if isinstance(t, tf.RaggedTensor):
    return t.nrows()
  else:
    return tf.shape(t)[0]
```

Or:

```
def bounding_shape(t):
  if isinstance(t, tf.RaggedTensor):
    return t.bounding_shape()
  else:
    return tf.shape(t)
```

(These would probably need to be helpers in your own code, since they're probably not worth adding as endpoints to TensorFlow.)

**Comment by nectario** [comment]
I am having a similar issue:
    "supported type." % (type(values), values))
TypeError: Failed to convert object of type <class 'tensorflow.python.ops.ragged.ragged_tensor.RaggedTensor'> to Tensor. Contents: tf.RaggedTensor(values=Tensor("Input1/flat_values:0", shape=(None,), dtype=int64), row_splits=Tensor("Input1/row_splits_0:0", shape=(None,), dtype=int64)). Consider casting elements to a supported type.

**Comment by rmothukuru** [comment]
@DEKHTIARJonathan,
Sorry for the delayed response. We can get the shape of **`Ragged Tensor`** not using **`tf.shape`** but using **`get_shape`** . Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/11f74723513e432440d486709945d95e/gh_31545.ipynb) of the working  code. Thanks!

**Comment by edloper** [comment]
@DEKHTIARJonathan, @rmothukuru `ragged_tensor.shape` and `ragged_tensor.get_shape()` are equivalent, and both return the **static shape** of a RaggedTensor.  This shape will contain `None` for any dimensions that are ragged or that have unknown dimension size (because it may depend on the inputs to the graph).  This differs from the `tf.shape()` operation, which returns a `Tensor`, and will never have `None` dimensions.

For some use cases, `ragged_tensor.shape` (aka `ragged_tensor.get_shape()` will be sufficient.  If it's not, I listed several alternatives in my comment above from Aug 22, 2019.

**Comment by DEKHTIARJonathan** [comment]
> @DEKHTIARJonathan,
> Sorry for the delayed response. We can get the shape of **`Ragged Tensor`** not using **`tf.shape`** but using **`get_shape`** . Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/11f74723513e432440d486709945d95e/gh_31545.ipynb) of the working code. Thanks!

The thing is some network requires to be able to get a ShapeTensor, that wouldn't work here

**Comment by chunduriv** [comment]
@DEKHTIARJonathan,

This feature is implemented in `TF2.9.1`. Please refer to the code snippet
```
import tensorflow as tf
print(tf.__version__)

ragged_tensor = tf.ragged.constant(
    [['All', 'the', 'world', 'is', 'a', 'stage'],
    ['And', 'all', 'the', 'men', 'and', 'women', 'merely', 'players'],
    ['They', 'have', 'their', 'exits', 'and', 'their', 'entrances']]
)

tf.shape(ragged_tensor)

tf.shape(ragged_tensor)[0] 
```
Output:

```
2.9.1
<DynamicRaggedShape lengths=[3, (6, 8, 7)] num_row_partitions=1>

<tf.Tensor: shape=(), dtype=int32, numpy=3>
```
Thank you.
