### ISSUE TITLE
From object detection using Tensorflow

### ISSUE THREAD

**Issue by Mohamedebouguerra** [tensorflow/tensorflow#31583]
from utils import label_map_util

from utils import visualization_utils as vis_util 

ImportError                               Traceback (most recent call last)
<ipython-input-4-956de605e8fe> in <module>()
----> 1 from utils import label_map_util
      2 
      3 from utils import visualization_utils as vis_util

C:\Users\hp\Downloads\models\research\object_detection\utils\label_map_util.py in <module>()
     24 import tensorflow as tf
     25 from google.protobuf import text_format
---> 26 from object_detection.protos import string_int_label_map_pb2
     27 
     28 

ImportError: cannot import name 'string_int_label_map_pb2'

**Comment by gowthamkpr** [comment]
Please refer to the following [solution](https://github.com/tensorflow/models/issues/1595#issuecomment-309234210) which will help you in resolving this problem. Also please make sure to post questions like these on [Tensorflow/Models](https://github.com/tensorflow/models/issues) as this issue is related to Models. Thanks!

**Comment by gowthamkpr** [comment]
Closing this issue as this has been inactive for more than 14 days. Please add additional comments and we can open the issue again. Thanks!
