### ISSUE TITLE
In 1.14  does using  TF-TRT still show TensorRT nodes in Tensorboard graph ?

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#31598]
I am not seeing any TensorRT related nodes in  Tensorflow 1.14  in Tensorboard graph.   Is that supposed to be that way ?  In that case how do I make sure TF-TRT is in fact used ?

**Comment by aaroey** [comment]
In 1.14 TF-TRT was disable by default accidentally due to some release problem, and we're fixing the it in 1.15. In fact [1.15rc1](https://pypi.org/project/tensorflow-gpu/1.15.0rc1/) and [2.0rc1](https://pypi.org/project/tensorflow-gpu/2.0.0rc1/) were out and TF-TRT was enabled in both, please try with that and let me know.

Thanks.
