### ISSUE TITLE
Call NNAPI cpu implementation on linux machine

### ISSUE THREAD

**Issue by haoyan01** [tensorflow/tensorflow#31666]
I am trying to implement the example in the following link on my linux machine:
https://developer.android.com/ndk/guides/neuralnetworks
I know if there is no no delegation for nnapi, it will fall back to cpu implementation. So I tried to link the shared library libneuralnetworks.so which is from NDK prebuilt library to my example code. But it does not work. It seems that this .so file is not dynamic link library. Is there anyone know how to run NNAPI cpu implementation on linux machine? 

Thanks very much.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
