### ISSUE TITLE
Can't import  tokenizer_from_json

### ISSUE THREAD

**Issue by Bingqiang1001** [tensorflow/tensorflow#31676]
When I  use 'keras.preprocessing.text.tokenizer_from_json', can't find.
I check keras/preprocessing/text.py, find there is no tokenizer_from_json;
Then add "tokenizer_from_json = text.tokenizer_from_json", is ok;
![image](https://user-images.githubusercontent.com/54168679/63150263-ec7fa280-c038-11e9-9ac5-63018957ad79.png)
and add "from tensorflow.python.keras.preprocessing.text import tokenizer_from_json"  in 
"site-packages/tensorflow/_api/v1/keras/preprocessing/text/__init__.py"
![image](https://user-images.githubusercontent.com/54168679/63257680-ebef4200-c2ac-11e9-8c3b-e0e69146e343.png)

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by Bingqiang1001** [comment]
cool!
