### ISSUE TITLE
 The arguments and returns of tf.keras.layers.GRUCell.call() make no sense at all

### ISSUE THREAD

**Issue by jpatts** [tensorflow/tensorflow#31705]
## URL(s) with the issue: https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/layers/recurrent.py#L1615 https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/layers/recurrent.py#L1718

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRUCell

## Description of issue (what needs changing):
The `states` argument to tf.keras.layers.GRUCell.call() is indexed with `h_tm1 = states[0]  # previous memory`, and the function returns `h` and `[h]`, which is the same value?

### Clear description
Why does this occur? Its inconsistent with the pytorch torch.nn.GRUCell implementation (https://pytorch.org/docs/stable/nn.html#grucell). 

I noticed the `states` issue when I was converting a project from pytorch to tf.keras and the same code, with just the GRUCell swapped from pytorch to tf.keras, did not work. The error message was `tensorflow.python.framework.errors_impl.InvalidArgumentError: In[0] is not a matrix. Instead it has shape [200] [Op:MatMul] name: transition/gru_cell/MatMul/`, and the solution was to replace my `hidden` with `[hidden]` for the states parameter. 

Furthermore, when I got my return types, they were a tuple rather than the output. Upon further inspection, the tuple CONTAINED THE SAME VALUE TWICE.

Is there any reason it does this? In the doc this is not explained AT ALL.

### Correct links
https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/layers/recurrent.py#L1615
https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/layers/recurrent.py#L1718

### Parameters defined
`states` parameter is the confusing one in question.

### Returns defined
`return h, [h]` makes no sense

### Raises listed and defined
Irrelevant

### Usage example
self.rnn = tf.keras.layers.GRUCell(num_units)
self.rnn(input, hidden)

where input, hidden = shape(N, num_units) doesn't work. Needs to be changed to:
self.rnn(input, [hidden]) to execute.

Furthermore, on the LHS of self.rnn, rather than just an x = self.rnn(...), I need to do x, _ = self.rnn(...)
Why?

### Submit a pull request?
I would gladly change this if someone would confirm this is an issue.

**Comment by MarkDaoust** [comment]
Hi @jpatts, 

Thanks for reporting this, but I believe this code is correct.

The keras rnn api is: You write a layer that returns an output, and a list of internal states. 
The list of internal states is what the layer passes to the next timestep as `states`. 

Compare to [LSTM](https://github.com/tensorflow/tensorflow/blob/r1.14/tensorflow/python/keras/layers/recurrent.py#L2196)

GRUCell returns `h,[h]`: the first `h` is the output. `[h]` is the list of internal states to pass to the next timestep. This makes sense because a GRU has one recurrent connection. That connection is its output from the last timestep.

See the [Keras RNN API](https://www.tensorflow.org/beta/guide/keras/rnn) for more detail.

**Comment by kevindoran** [comment]
Currently, this issue is the best documentation on GRUCell usage. GRUCell could really do with some improved documentation.

**Comment by tymefighter** [comment]
@kevindoran Yes you're right, also it took me a while to find this page and understand the outputs of GRUCell
