### ISSUE TITLE
Is wide_n_deep compatible with python3.5?

### ISSUE THREAD

**Issue by gnujimmik** [tensorflow/tensorflow#3177]
GitHub issues are for bugs / installation problems / feature requests.  
For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System: Ubuntu 14/04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from sources, provide the commit hash:

### Steps to reproduce
1. run wide_n_deep.py on python 3.5
2.
3.

### What have you tried?
1.

### Logs or other output that would be helpful
(If logs are large, please upload as attachment).
TypeError: unsupported operand type(s) for +: 'dict_items' and 'dict_items'

This is because python3.5 does not support + between dict_items. I worked around using dict.copy(), but still get error and could proceed. Do you have plan to release python 3.5 version in near future?

**Comment by eyewy** [comment]
in wide_n_deep_tutorial.py, change the following line:
feature_cols = dict(continuous_cols.items() + categorical_cols.items())
to
feature_cols = {**continuous_cols , **categorical_cols}
this change makes wide_n_deep_tutorial.py compatible with Python 3.x.
Now simply run it like:
python3.5 wide_n_deep_tutorial.py --model_type=wide

note that the wide_n_deep option (--model_type=wide_n_deep) still has an error due to a compatibility issue in dnn_linear_combined.py

**Comment by aselle** [comment]
@hengtze could you fix this?
