### ISSUE TITLE
How to check/enlarge computer memory in Mac OS when running .py code? 

### ISSUE THREAD

**Issue by QLQLQL** [tensorflow/tensorflow#3178]
Hi everyone,

I'm new to python, and learning tensorflow recently on my mac OS X Yosemite system with 8g memory. I'm using anaconda with tensorflow installed within it. When trying some demo codes, I found they run very slowly.

 I've saw somewhere previously that python only use 2g (or 1g? sorry I cannot remember clearly) memory in Mac OS since it was installed in virtual environment, so one can enlarge the memory to 8g to speed up the programme by using just several command lines. 

Unfortunately I  cannot find out that webpage now. Does anyone have idea how to do this? Thanks a lot!

**Comment by QLQLQL** [comment]
@takluyver @carreau

**Comment by takluyver** [comment]
> I've saw somewhere previously that python only use 2g (or 1g? sorry I cannot remember clearly) memory in Mac OS since it was installed in virtual environment

If you are really using a virtual *environment*, it cannot, as far as I know, limit the memory a process can use. If you're using a virtual *machine*, or a container system such as Docker, it can.

**Comment by Carreau** [comment]
Yeah, that's one of the issues with tensor flow we heard about. I've heard the you can configure tensor flow not to do that but that. IIUC you need to do that when you create a session:

http://stackoverflow.com/questions/34199233/how-to-prevent-tensorflow-from-allocating-the-totality-of-a-gpu-memory

**Comment by QLQLQL** [comment]
"If you are really using a virtual environment, it cannot, as far as I know, limit the memory a process can use. If you're using a virtual machine, or a container system such as Docker, it can." -- Thanks for the reply. Actually I'm not 100% sure whether I'm using a virtual environment or virtual machine or Docker (sorry I'm not major in computer and not very familiar with computer systems). If I'm using VM or Docker, how can I do it? @takluyver

**Comment by QLQLQL** [comment]
Yeah it cannot solve my problem... But still thanks for your kind help! @Carreau

**Comment by Carreau** [comment]
> Actually I'm not 100% sure whether I'm using a virtual environment or virtual machine or Docker

If you are not sure, then there is 99% chance that you are not using either Docker or a VM. If you are you would explicitly start these and you would thus be able to pass an option at startup to limit the RAM, in te case of Docker `--memory="<memory>" `. In case of OS X it's worse as you run Docker in a VM. 

Os it's unlikely that your python is memory limited already:

```
In [15]: import numpy as np
In [18]: z = np.random.rand(*((1000,)*3)
In [17]: %whos
Variable   Type       Data/Info
-------------------------------
np         module     <module 'numpy' from '/Us<...>kages/numpy/__init__.py'>
z          ndarray    1000x1000x1000: 1000000000 elems, type `float64`, 8000000000 bytes (7629.39453125 Mb)
```

(note we might want to update `whos`, sic) but I'm actually using 7.5Gb Ram.

<img width="540" alt="screen shot 2016-07-04 at 19 59 36" src="https://cloud.githubusercontent.com/assets/335567/16572830/e1681c26-4221-11e6-800b-057a03f7640b.png">


The "limited to 2 Gb" would make sens on 32bits OS, especialy windows, which you are extremely unlikely to get, you had to boot with `/LARGEADDRESSAWARE` flag, or upgrade your windows version (of vista) which was limited *on purpose*.


My guess is that tensorflow is ment to be used on much more powerful machines (eg the machines I have seen it use have 100 of GB of memory of 10s of GB of GPUs). It is slow because your machine is just not up to the task.

**Comment by QLQLQL** [comment]
Get it. Currently I’m just in a learning phase. Though the macbook is slow, I think I can live with it for the moment. Thanks again! @Carreau

**Comment by aselle** [comment]
@QLQLQL, If your question has  been answered sufficiently, I will close.

**Comment by QLQLQL** [comment]
Yeah, please close the issue. Thanks.

    On Thursday, July 7, 2016 8:21 AM, Andrew Selle <notifications@github.com> wrote:
 

 @QLQLQL, If your question has been answered sufficiently, I will close.—
