### ISSUE TITLE
Data Augmentation from PREPROCESSING_FUNCTION_MAP?

### ISSUE THREAD

**Issue by AeroWRX** [tensorflow/tensorflow#31911]
How do we utilize Data Augmentation features in the Tensorflow API as indicated from the PREPROCESSING_FUNCTION_MAP in preprocessor_builder.py? Is there a file we have to modify in the /object_detection folder or is there additional command lines we need to be aware of?

**Comment by oanush** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
