### ISSUE TITLE
Running MobileNet SSD Float Detector

### ISSUE THREAD

**Issue by thias15** [tensorflow/tensorflow#31922]
Hello. 

I'm trying to run the model "mobile_ssd_v2_float_coco.tflite" in the [object detection app](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/android). I have gotten the model to run on the GPU following the [tutorial](https://www.tensorflow.org/lite/performance/gpu) and adjusting image resolution and output accordingly. The output seems to follow the [old format](https://github.com/tensorflow/tensorflow/commit/f3785197b4de9466b48462f4f93b455c88dd622b#diff-c748d758eb53ac58d70a13e07e02c6db), where only outputLocations and outputClasses are produced. In the previous code it was also necessary to rescale the bounding boxes and there was a file "box_priors". I found the old file, it has 1917 entries, since this was the number of results produced. The new model on the other hand produces 2034 results. Is there a compatible "box_priors" file? Is this file even necessary?

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by thias15** [comment]
Hello. 

Thanks for your response. The problem is not related to a specific platform, but here it is:
The App is running on Android, Android Studio running on a MacBook. 

I'm using tflite, 1.14 binaries:
org.tensorflow:tensorflow-lite-gpu:1.14.0

**Comment by srjoglekar246** [comment]
Hey @thias15 , are you interested in the raw box encodings and scores (before Non-Max-Suppression) or the final results (much less in number, but post-processed with NMS)? 

So the network you have consists only of the 'Feature Extractor' & 'Box Predictor' components, which produce the raw set of candidate objects. These would need to be post-processed with NMS.

If all you need is the final results, please follow the instructions on [this page](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) on any of the models from our [model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md). This should yield a model which follows the Inputs/Outputs mentioned [here](https://www.tensorflow.org/lite/models/object_detection/overview#starter_model).

**Comment by hi10n** [comment]
Hi:

I have a follow up question. I am using the same setup using tflite-gpu 1.14 and get the raw data of 'Feature Extractor' & 'Box Predictor'. Can you please let me know how to go about post-processing that data using NMS and I believe we would need the anchors to use with NMS?

Thanks.

**Comment by srjoglekar246** [comment]
One way would be to [use TFLite's post-processing op](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md). 
If you want to do things yourself, look at our [detection_postprocess](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/detection_postprocess.cc) op.

I am closing this issue now, since it has been stale for a while.
