### ISSUE TITLE
[install error] install failed on RedHat 

### ISSUE THREAD

**Issue by dzhwinter** [tensorflow/tensorflow#3194]
In large scale cluster,  Entherprise RedHat system is mainstream distribution branch, and its always encounter a low version of kernel and libc problem.  There  several similar issue in this project.  I'm wondering that
1  is there any method to build tensorflow offline? 
2  how can I build tensorflow cc part as static library instead of shared library. 
3  is there any way to pay a cheap price to replace the bazel build tool?  Here we encounter a build tool bug.
https://github.com/bazelbuild/bazel/issues/1474, which had been labeled as a bug in bazel, is there any alternative method?

Thanks
System info:

```
(gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) )
ldd --version
ldd  2.18
```

**Comment by aselle** [comment]
You did not specify what version of RedHat you are using (Please paste cat /etc/issue or cat /etc/redhat-release). But judging from the gcc version 4.4.4, I am guessing it is RHEL6.x. Bazel itself is not supported on less than RHEL/CentOS 7. Others have managed to get it to work by changing Bazel's source significantly, but this is not supported).

1. I don't understand what this means? You could install the same operating system in a VM on your local machine and build tensorflow there.
2. probably not easily. you'd need to build a python binary replacement, because otherwise all modules are typically brought in as dso's
3. we are unlikely to support other build systems other than bazel in the long-term or near-term.

**Comment by dzhwinter** [comment]
release version of system as you guessed, RHEL6.3, actually .

1. this is an problem in fact since our cluster is offline, which means the cluster physical isolation with internet. And bazel clone a lot of dependency files from elsewhere.
I use tensorflow smoothly on my workstation, but when it comes to company level cluster envrionment, Since the building tool system do not support linux version lower RHEL/CentOS 7,  we really need to port tensorflow to other buiding tools.

It seems the best solving method is build tensorflow in VM env, then pack it and distribute.

 




Because i will going to test tensorflow in cluster,

**Comment by aselle** [comment]
The simplest easiest way to deploy tensorflow is probably through docker or virtual machine. People do get it to work on older clusters, and if you search around issues you might find the solution to your problem. But it will not be easy. Good luck!

**Comment by gunan** [comment]
We now have cmake support under contrib. So you may be able to use that.
As for offline build support, I am not sure but I guess you can build a pip package on a machine with internet access and deploy that on other machines.

**Comment by gunan** [comment]
https://github.com/tensorflow/tensorflow/issues/7118

We were able to get TensorFlow build on RHEL6. Looks like you need to make some local changes, but things seem to build fine. I will close this issue to merge the discussion on the other thread, which currently has a solution.
