### ISSUE TITLE
[TF 2.0.0rc0] dependency on functools32 prevents python3.7 installation

### ISSUE THREAD

**Issue by PgLoLo** [tensorflow/tensorflow#31983]
Somewhy poetry thinks, that `tensorflow-gpu = "2.0.0-rc0"` depends on functools32 on python3.7 environment, because of what `poetry install / update` fails.

Found [this](https://github.com/tensorflow/tensorflow/issues/31767) issue, but it did not help because `tensorflow-gpu = "2.0.0-beta1"` works greate with poetry.

**Comment by oanush** [comment]
@PgLoLo ,
Can you please provide details about what platform you are using (operating system, architecture).Thanks!

**Comment by fgervais** [comment]
I did more digging and I verified that 
`tensorflow==2.0.0-b1` is `manylinux1`
`tensorflow==2.0.0-rc0` is `manylinux2010`

So I think the issue @PgLoLo [linked to](https://github.com/tensorflow/tensorflow/issues/31767#issuecomment-522786795) is the issue here.

@PgLoLo I'm on pipenv and updating to master did bring `manylinux2010` support and made the installation of rc0 possible. I would suggest that you verify if poetry have support for `manylinux2010` on the version you are running.

**Comment by oanush** [comment]
@PgLoLo ,
can you please refer @fgervais response to the issue ?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by synap5e** [comment]
Still having this issue, with `2.0.0-rc0` using `poetry` to install on a clean (no other deps) test project

```
(venv) PS C:\tmp\tftest> poetry add tensorflow-gpu="2.0.0-rc0"

Updating dependencies
Resolving dependencies... (3.1s)

Writing lock file


Package operations: 8 installs, 12 updates, 0 removals

 -> 1.17.2)g numpy (1.16.3
 -> 0.8.0)ng absl-py (0.7.1
 -> 1.23.0)g grpcio (1.20.1
 -> 2.10.0)g h5py (2.9.0
 -> 3.1.1)ng markdown (3.1
 -> 3.9.1)ng protobuf (3.7.1
 -> 0.15.6)g werkzeug (0.15.2
  - Installing wheel (0.33.6)
 -> 0.8.0)ng astor (0.7.1
  - Installing functools32 (3.2.3-2)

[EnvCommandError]
Command ['C:\\tmp\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '--no-deps', 'functools32==3.2.3-2'] errored with the following output:
Collecting functools32==3.2.3-2
  Using cached https://files.pythonhosted.org/packages/c5/60/6ac26ad05857c601308d8fb9e87fa36d0ebf889423f47c3502ef034365db/functools32-3.2.3-2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\tmp\venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\simon\\AppData\\Local\\Temp\\pip-install-80qdzk9j\\functools32\\setup.py'"'"'; __file__='"'"'C:\\Users\\simon\\AppData\\Local\\Temp\\pip-install-80qdzk9j\\
functools32\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: C:\Users\simon\AppData\Local\Temp\pip-install-80qdzk9j\functools32\
    Complete output (1 lines):
    This backport is for Python 2.7 only.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

add [-D|--dev] [--git GIT] [--path PATH] [-E|--extras EXTRAS] [--optional] [--python PYTHON] [--platform PLATFORM] [--allow-prereleases] [--dry-run] [--] <name> (<name>)...
```

**Comment by PgLoLo** [comment]
The problem is still presented in tensorflow2.0.0-rc1.

**Comment by PgLoLo** [comment]
@oanush  can you please reopen this issue?

**Comment by av8ramit** [comment]
Unfortunately we only support pip installation as of right now, which is why we made the move to manylinux2010. I'm not sure what I can do to help fix this issue, but I think once [this issue](https://github.com/sdispater/poetry/issues/1373) is resolved on poetry's side it will work.

We cannot provide manylinux1 whls as pypi will reject them and they are not even technically compliant with the packaging standard. Sorry for the inconvenience.

**Comment by aflc** [comment]
I commented on https://github.com/sdispater/poetry/issues/1330#issuecomment-533043208.

What about a restriction for Python version like below?
https://github.com/tensorflow/tensorflow/blob/c75bb66a99ad45e5a3c9fc4625c8abeb705520b5/tensorflow/tools/pip_package/setup.py#L56

I don't tested yet, but I will.
