### ISSUE TITLE
Calculate a vector l1 norm of a tensor creates unnecessary copy of tensor

### ISSUE THREAD

**Issue by zhengwy888** [tensorflow/tensorflow#3201]
I am using tensorflow 0.9.
when I am trying to calculate a simple l1-norm of vector, like 
```python
    matrix = vs.get_variable("Matrix", [total_arg_size, output_size])                      
    l1norm = tf.reduce_mean(tf.abs(matrix))                                                 
```

Tensorflow allocates memory for the results of tf.abs(matrix). when matrix size are large, this could cause out of memory issue.
Is there a way I can avoid this additional allocation?

**Comment by Kontrakt** [comment]
I have encountered the same problem. Tensorflow also allocates memory for gradients of intermediate operations and it makes working with large models impossible. It would be great to hear reasons for such memory model and how unnecessary allocations can be avoided.

**Comment by aselle** [comment]
It is always possible to create monolithic custom ops on your side when you find bottlenecks that are show stoppers. However, we are always working to improve performance. Perhaps  @michaelisard @vrv can provide context and point of view.

**Comment by michaelisard** [comment]
We realize that unnecessary copies are undesirable: they can make you run out of GPU memory as you observe, and even when they don't they consume unnecessary memory bandwidth.

There are two strategies being investigated that could help here, but both are non-trivial and will take some time to be done in a comprehensive fashion.

The first is to allow general-purpose Ops to do in-place updates, i.e. re-use the input memory buffer instead of allocating a new buffer for the output. This is non-trivial because buffers in TensorFlow can be aliased, and obviously we can't update a buffer that another consumer believes is immutable. It isn't as simple as just reference counting because aliased variables add more complexity. I am working on a formal memory model for TensorFlow which is a step towards doing the analysis that would allow in-place updates to be done with confidence.

The second is to do some kind of operator fusion as in #164 which again is being worked on but will take some time.

In the meantime as @aselle indicates the workaround is do write a custom fused Op. It's not an ideal situation but should allow you to make progress if you are really blocked on memory.
