### ISSUE TITLE
[lite] only armv8.so carsh

### ISSUE THREAD

**Issue by laohur** [tensorflow/tensorflow#32048]
[lite] resloved, unity problem

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Can you please elaborate about the issue & the context.Will it be possible to provide related code. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
