### ISSUE TITLE
micro: riscv32_mcu build failed with undefined references

### ISSUE THREAD

**Issue by ehirdoy** [tensorflow/tensorflow#32041]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: source
- TensorFlow version: 298534b745db43b2ad18256ed781bd2f142e5bc7
- Python version: 2.7.15+/3.6.8
- Installed using virtualenv? pip? conda?: pip3

**Describe the problem**
TF Lite for micro, riscv32 build fails with undefined references.

make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=riscv32_mcu TARGET_ARCH=riscv32 hello_world_bin

/home/ehirdoy/src/tensorflow/tensorflow/lite/experimental/micro/riscv32_mcu/debug_log.cc:18: undefined reference to `__wrap_puts'
exit.c:(.text.exit+0x2e): undefined reference to `__wrap__exit'
sbrkr.c:(.text._sbrk_r+0x12): undefined reference to `__wrap__sbrk'
writer.c:(.text._write_r+0x16): undefined reference to `__wrap__write'
closer.c:(.text._close_r+0x12): undefined reference to `__wrap__close'
lseekr.c:(.text._lseek_r+0x16): undefined reference to `__wrap__lseek'
readr.c:(.text._read_r+0x16): undefined reference to `__wrap__read'
fstatr.c:(.text._fstat_r+0x14): undefined reference to `__wrap__fstat'
isattyr.c:(.text._isatty_r+0x12): undefined reference to `__wrap__isatty'

**Provide the exact sequence of commands / steps that you executed before running into the problem**

export PATH="$PATH:./tensorflow/lite/experimental/micro/tools/make/downloads/riscv_toolchain/bin"
make -f tensorflow/lite/experimental/micro/tools/make/Makefile clean
make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=riscv32_mcu TARGET_ARCH=riscv32 hello_world_bin

**Any other info / logs**
[make.log](https://github.com/tensorflow/tensorflow/files/3550454/make.log)

**Comment by zhoupeng** [comment]
I write patches which fix this bug.
This pull request to fix is  https://github.com/tensorflow/tensorflow/pull/33972
Hi @ehirdoy @Zielasko 
Could you have a try of these patches pls? If it works, pls have a support click.

Best,

**Comment by Zielasko** [comment]
Thank you for writing a fix @zhoupeng .
I tried to write a workaround in an older version of this repository that let me compile the hello world example and a few examples i have written myself, but they didn't behave correctly. 
Using your version lets me compile and successfully run the hello world example on a risc-v simulator with the expected output. 
(Using `make -f tensorflow/lite/experimental/micro/tools/make/Makefile TARGET=riscv32_mcu hello_world` to build the executable) 

Unfortunately I still can't build the micro_speech, magic_wand or person_detection examples for 
riscv32_mcu. 
For the magic_wand example it cant find `__wrap_malloc` and `__wrap_free` .

person_detection fails with the error 
``` 
person_detection section `.bss' will not fit in region `ram' 
[...]
section .stack VMA [0000000080003800,0000000080003fff] overlaps section .bss VMA [00000000800002b8,0000000080012d87]
[...]
region `ram' overflowed by 0 bytes
```

I have yet to test my own models. 

Also, trying to build a linux version of the hello world example with the __dso fix gives me this error: 
`multiple definition of `__dso_handle'`

**Comment by zhoupeng** [comment]
Hi @Zielasko , Thanks for your response. Sorry for late reply, I am not convenient to handle mail in time, because on a travel of RISC-V tech forum.
1)For the `.bss' will not fit in region `ram error:
Set the MEMORY.ram option with a larger value in the link script can fix.
The ram option is in the link script `tensorflow.git/tensorflow/lite/experimental/micro/tools/make/downloads/sifive_fe310_lib/bsp/env/freedom-e300-hifive1/flash.lds`.
In my case, I only try to set `ram (wxa!ri) : ORIGIN = 0x80000000, LENGTH = 128K` (Maybe `64K` or `32K` is enough for some examples bug I didn't try)

2)__dso_handle missing problem. Thanks for response, very helpful.
This problem may only exists on non-Linux target (riscv32_mcu,Windows ...), I will submit a new version patch adding target OS check.
Before the new patch, If you try to build a linux version, you can try to comment `__dso_handle`  by replacing `void* __dso_handle;`
with `// void* __dso_handle;`, in `tensorflow.git/tensorflow/lite/experimental/micro/arduino/abi.cc`,

Hi @nkreeger @gbaned @rockyrhodes, sorry for  late, thanks @nkreeger for your detail review I will submit a new version patch, catching up on this Fridays after my RISC-V tech forum journey.

**Comment by ymodak** [comment]
Closing since the associated PR has been merged. Feel free to reopen if necessary. Thanks!
