### ISSUE TITLE
Export Inference TensorFlow model Option(DEFAULT/API_MODEL)

### ISSUE THREAD

**Issue by czy2014hust** [tensorflow/tensorflow#32069]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (1.8/2.0):
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**

When exporting(freeze graph) tensorflow model(graph) only for inferencing on mobile/Embedded/IoT using [Tflite](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite)/[MNN](https://github.com/alibaba/MNN) etc lite inference framework, it is difficult to convert/implement the freezed graph efficiently sometimes. For example, when using RNN/GRU/LSTM(static or dynamic) or control flow api(operations), tensorflow will unroll the api to lower operations that make converting/implementing/optimizing on other inference framework difficult, and need much efforts for optimizing the unrolled graph.
I wonder whether the following recommendation is acceptable:
> Tensorflow provide two options when exporting(freeze graph), one is the *DEFAULT* which like the original process, the other is *API_MODEL* which do not lower the api, keep the api-operations in the freezed graph(pb). 
 This method like [convert-RNN-tflite](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/g3doc/convert/rnn.md), but I think the above method is better.

**Will this change the current api? How?**
Yes, add one option(DEFAULT/API_MODEL)
**Who will benefit with this feature?**
Those who using tensorflow framework to train model, then deploying the model on mobile/Embedded/IoT using Tflite/MNN etc lite inference framework.
**Any Other info.**

**Comment by gargn** [comment]
The freeze graph 1.X API ([`convert_variables_to_constants`](https://www.tensorflow.org/api_docs/python/tf/graph_util/convert_variables_to_constants)) does not lower control flow. The API takes in a GraphDef and does not have sufficient information in order to prevent lowering.

Control flow lowering happens in the TFLite code. If you want to prevent lowering from happening, please reference the [`OpHint`](https://www.tensorflow.org/api_docs/python/tf/lite/OpHint) API. We are also actively working on better supporting control flow in TensorFlow 2.0.
