### ISSUE TITLE
Bug in tf.math.lbeta?

### ISSUE THREAD

**Issue by KristianHolsheimer** [tensorflow/tensorflow#32135]
Hi there,

I noticed that there's a discrepancy between the implementations of the log-beta function in tensorflow and scipy.

Here's a simple test (pytest) to reproduce this:

```python
import numpy as np
import tensorflow as tf


def test_lbeta():
    import scipy.special

    ab = [10, 20]
    x = scipy.special.betaln(*ab).astype('float32')

    # compare
    ab = tf.constant(ab, dtype='float32')
    with tf.Session() as sess:
        y = sess.run(tf.math.lbeta(ab))

    np.testing.assert_almost_equal(x, y)  # error: -19.115328 != -19.115334

```
The relative error is about 3e-7, which is not negligible. It gets worse with larger `a` and `b`.

This can be problematic in situations that rely on cancellation of large numbers, e.g. in computations involving the log-pdf of a Beta distribution.

Is this expected or is it a bug?

**Comment by ravikyram** [comment]
Please, let us know the TensorFlow version you are using. 
Looks like the code is incomplete.Can you please provide full code snippet to reproduce it on our environment.Thanks!

**Comment by KristianHolsheimer** [comment]
```
$ python3 -c 'import tensorflow as tf; print(tf.__version__)'
```
> 1.14.0

In order to reproduce the error just run `pytest` on the code above or call the `test_lbeta()` function yourself, e.g.

```
$ python3 -c "
> import numpy as np
> import tensorflow as tf
> 
> 
> def test_lbeta():
>     import scipy.special
> 
>     ab = [10, 20]
>     x = scipy.special.betaln(*ab).astype('float32')
> 
>     # compare
>     ab = tf.constant(ab, dtype='float32')
>     with tf.Session() as sess:
>         y = sess.run(tf.math.lbeta(ab))
> 
>     np.testing.assert_almost_equal(x, y)
> 
> test_lbeta()
> "
```
> AssertionError: 
> Arrays are not almost equal to 7 decimals
>  ACTUAL: -19.115328
>  DESIRED: -19.115334

**Comment by WindQAQ** [comment]
Hi @KristianHolsheimer, I think it it due to precision. If you take a deeper look at the scipy's implementation, you can find out the two arguments passed into `betaln` (python API) or `lbeta` (c API) are `double` a.k.a. `float64`.

So the computation for `lbeta` in scipy is all done with `double`, meaning the numbers are more precise. While in TensorFlow, if you pass `float` into it, the computation will be done in `float`, which results in less precision for intermediate/output values. So to do a fair test against scipy, we should make sure the numbers passed into TF is `float64`.

https://colab.research.google.com/drive/1WcQV9wSKZkkqVc0zKiBlk-nC9Pmv9QzS
https://github.com/scipy/scipy/blob/master/scipy/special/functions.json#L216-L220
https://github.com/scipy/scipy/blob/master/scipy/special/_cephes.pxd#L7
https://github.com/scipy/scipy/blob/master/scipy/special/cephes/beta.c#L138

**Comment by ravikyram** [comment]
@KristianHolsheimer 

Have a look on @WindQAQ's suggestion and let us know if that helps to resolve the issue. Thanks!

**Comment by KristianHolsheimer** [comment]
@WindQAQ You're absolutely right. That was it. Phew.. cheers!!
