### ISSUE TITLE
Commit 2f38d92fa854bb173bc866a89f5123e501cf35bd breaking unit test builds.

### ISSUE THREAD

**Issue by claynerobison** [tensorflow/tensorflow#32283]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: https://github.com/tensorflow/tensorflow/commit/2f38d92fa854bb173bc866a89f5123e501cf35bd problem occurs on master branch with and without --config=v2
- Python version: py2.7
- Installed using virtualenv? pip? conda?: docker tensorflow/tensorflow:devel
- Bazel version (if compiling from source): 0.26.1 from docker tensorflow/tensorflow:devel
- GCC/Compiler version (if compiling from source): tensorflow/tensorflow:devel (7.4.0)
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
> SUBCOMMAND: # //tensorflow/core/platform:windows_env_time_impl [action 'Compiling tensorflow/core/platform/windows/env_time.cc']
> (cd /jenkins/workspace/Nightly-Private-Tensorflow-Eigen/eigen_build/a638235ef1b5f50137189224e7b73e40/execroot/org_tensorflow && \
>   exec env - \
>     PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin \
>     PWD=/proc/self/cwd \
>     PYTHON_BIN_PATH=/usr/local/bin/python \
>     PYTHON_LIB_PATH=/usr/local/lib/python2.7/dist-packages \
>     TF_CONFIGURE_IOS=0 \
>   /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG -ffunction-sections -fdata-sections '-std=c++0x' -MD -MF bazel-out/k8-opt/bin/tensorflow/core/platform/_objs/windows_env_time_impl/env_time.pic.d '-frandom-seed=bazel-out/k8-opt/bin/tensorflow/core/platform/_objs/windows_env_time_impl/env_time.pic.o' -fPIC -iquote . -iquote bazel-out/k8-opt/bin '-march=haswell' '-mtune=broadwell' -O3 -Wformat -Wformat-security -fstack-protector -fPIC -fpic '-std=c++14' '-D_GLIBCXX_USE_CXX11_ABI=0' -fno-canonical-system-headers -Wno-builtin-macro-redefined '-D__DATE__="redacted"' '-D__TIMESTAMP__="redacted"' '-D__TIME__="redacted"' -c tensorflow/core/platform/windows/env_time.cc -o bazel-out/k8-opt/bin/tensorflow/core/platform/_objs/windows_env_time_impl/env_time.pic.o)
> ERROR: /jenkins/workspace/Nightly-Private-Tensorflow-Eigen/tensorflow/tensorflow/core/platform/BUILD:51:1: C++ compilation of rule '//tensorflow/core/platform:windows_env_time_impl' failed (Exit 1)
> tensorflow/core/platform/windows/env_time.cc:19:10: fatal error: windows.h: No such file or directory
>  #include <windows.h>
>           ^~~~~~~~~~~

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
$ docker run tensorflow/tensorflow:devel
# cd /tensorflow_src
# git pull
# yes "" | python configure.py
# bazel --nosystem_rc --nohome_rc --output_user_root=/root/eigen_build test --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=0 --copt=-march=haswell --copt=-mtune=broadwell --copt=-O3 --copt=-Wformat --copt=-Wformat-security --copt=-fstack-protector --copt=-fPIC --copt=-fpic --linkopt=-znoexecstack --linkopt=-zrelro --linkopt=-znow --linkopt=-fstack-protector --test_timeout 300,450,1200,3600 --test_env=KMP_BLOCKTIME=0 -s --cache_test_results=no --test_size_filters=small,medium,large,enormous -c opt -- //tensorflow/... -//tensorflow/compiler/... -//tensorflow/lite/... -//tensorflow/core:test_lite_main -//tensorflow/contrib/tensorrt/... -//tensorflow/stream_executor/cuda/... -//tensorflow/python/autograph/pyct/... -//tensorflow/core/kernels:eigen_mkldnn_contraction_kernel_test -//tensorflow/python/debug:dist_session_debug_grpc_test

```
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by angersson** [comment]
Quick link to commit: 2f38d92fa854bb173bc866a89f5123e501cf35bd

@bmzhao, can you take a look at this? Was there a change on top of the original that didn't get rolled back as well?

**Comment by bmzhao** [comment]
Pasting my reply from the commit (https://github.com/tensorflow/tensorflow/commit/2f38d92fa854bb173bc866a89f5123e501cf35bd#commitcomment-34983793):

Hi Clayne! Could you tell us the bazel command you executed that ran into this issue?

For context, we are refactoring build targets under tensorflow/core/platform/BUILD, such that platform-specific library implementations have their own build targets (eg: window's implementation of the env_time interface is now split into its own build target `windows_env_time_impl`). Our intention is that the implementation meant for your platform is the one that selected at build time.

In other words

1. we now have both `windows_env_time_impl` and default `env_time_impl` build targets
2. if you build on posix, only the default `env_time_impl` should ever be in the transitive closure of any build target's dependencies. (This is enforced through the select statement here: https://github.com/tensorflow/tensorflow/commit/2f38d92fa854bb173bc866a89f5123e501cf35bd#diff-c0864b5ac6e1b46699c5e0453e53c696R67-R70)

However, one potential issue you might run into is if you attempt to execute the command `bazel test ...` or `bazel build ...`

The `...` syntax will recursively expand to all subpackages & targets (from wherever you invoked the command). See https://docs.bazel.build/versions/master/query.html#target-patterns

If this is the case, you can add the flag `--build_tag_filters=-no_oss` to your bazel flag, which will exclude any targets that have the `no_oss` tag, see: https://docs.bazel.build/versions/master/command-line-reference.html#flag--build_tag_filters

Note that simply supplying `test_tag_filters=-no_oss` does not work, due to this bazel issue: https://github.com/bazelbuild/bazel/issues/8439

Also, note that supplying the `build_tag_filters=-no_oss` will still allow targets to be built if they are in the transitive closure of some other target you are building: https://github.com/bazelbuild/rules_docker/issues/269#issuecomment-354764562

**Comment by bmzhao** [comment]
Ah I missed the docker run commands at the bottom of your comment; I see what's happening. Our ci_build scripts weren't also updated with the --build_tag_filters (my mistake)! I asked gunan@ and he confirmed that using "manual" as a tag would also suffice, without having to set the build_tag_filters flag. I will have a fix shortly.

**Comment by bmzhao** [comment]
I've just added the new tags here, which should fix this issue:
https://github.com/tensorflow/tensorflow/commit/5ee8685df5aac173729e76b51144bba73a536fa4

Can you sync to head and confirm if the problem is fixed @claynerobison?

**Comment by claynerobison** [comment]
Fixed. Thanks!
