### ISSUE TITLE
Plain English explanation of CLA?

### ISSUE THREAD

**Issue by csbrown** [tensorflow/tensorflow#32502]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md#contributor-license-agreements

## Description of issue (what needs changing):

I have no idea what any of this legal mumbo-jumbo actually entails.  "Grant of Patent License", "Grant of Copyright License".  Do I own my contributions?  Does Google own my contributions?  What does all of this mess mean?  If I create something and "give it away", I want to make it free as in gratis and as in libre widely, and not just to Google.  Is that happening here?  Does Google charge/restrict people (e.g. corporations) using tensorflow?  *Can* Google charge/restrict people using tensorflow and/or my contributions? 

### Submit a pull request?
No.

**Comment by martinwicke** [comment]
> I have no idea what any of this legal mumbo-jumbo actually entails. "Grant of Patent License", "Grant of Copyright License". Do I own my contributions?

Yes, you own your contributions. The preamble of the agreement addresses this.

> Does Google own my contributions? 

No, Google only receives a license to your contribution, as detailed in Sections 2 and 3 of the agreement, which enables Google to incorporate the contribution into the project.

> What does all of this mess mean? If I create something and "give it away", I want to make it free as in gratis and as in libre widely, and not just to Google. Is that happening here?

You are entirely welcome to make your contributions as free as possible. The Contributor License Agreement grants Google broad permission to use the contribution, which Google then uses to release your contribution as part of TensorFlow under the Apache 2 license. However, since you retain ownership of your contributions, you are also free to publish those contributions (and/or anything else that you personally hold the rights to) under the most liberal terms possible by publishing it on GitHub (or elsewhere) under a license such as the CC0.

> Does Google charge/restrict people (e.g. corporations) using tensorflow? Can Google charge/restrict people using tensorflow and/or my contributions?

TensorFlow is released under the Apache 2 license which is a perpetual open source license. This means that Google cannot prevent people, corporations, you, or anyone from ever using TensorFlow under the terms of the Apache 2 license. 

Let me know if you have more questions.
