### ISSUE TITLE
bazel should be optional when building from source

### ISSUE THREAD

**Issue by hartsantler** [tensorflow/tensorflow#326]
nobody likes a complicated compile and installation process.  its great that to get started users can easily pip install tensorflow, but its not great that to do a full recompile they need to install bazel.

Jim F. has a great tutorial here for using tensorflow directly from c++, https://medium.com/jim-fleming/loading-a-tensorflow-graph-with-the-c-api-4caaff88463f#.ruuyvd9ae

but for users like me on Fedora, installing bazel is unsupported, so its a major disappointment not being able to try Jim's tutorial.

cmake is probably a better choice for alternate build system, because that is easy to use on any type of linux.  The cmake build script could be super stripped down and not include building the python wrappers, because most people building from source are embedding into their own apps, and only use python to create and train their graphs.

**Comment by chenghuige** [comment]
I can not install bazel from source code. But you may try just install bazel using below
https://github.com/bazelbuild/bazel/releases/download/0.1.0/bazel-0.1.0-installer-linux-x86_64.sh
which works for me.

**Comment by davidzchen** [comment]
@hartsantler You do not need to build Bazel from source. You can just use the latest Bazel binary installer instead: http://bazel.io/docs/install.html

I had thought the [TensorFlow docs](http://tensorflow.org/get_started/os_setup.md#installing_from_sources) were updated to instruct to use the Bazel 0.1.1 installer since #130 was closed, but it looks like the docs haven't been updated yet.

**Comment by vrv** [comment]
website is now updated to refer to the latest install

**Comment by vrv** [comment]
Deduping with https://github.com/tensorflow/tensorflow/issues/380
