### ISSUE TITLE
Missing output shape for inverse stft

### ISSUE THREAD

**Issue by risajef** [tensorflow/tensorflow#32619]
## Link
https://www.tensorflow.org/api_docs/python/tf/signal/inverse_stft

## Description of issue:
I am missing what the output dimensions are.

### Clear description

I do not know what the output dimensions of inverse_stft are. And I do not know how they come to be.

### Example Code

```
audioNp = np.random.random((1,120800)).astype(np.float32)
frame_length = 2048
frame_step = 2048//4
stft = tf.contrib.signal.stft(
    audioNp[0], 
    frame_length, 
    frame_step)
invstft = tf.contrib.signal.inverse_stft(
    stft, 
    frame_length, 
    frame_step, 
    window_fn = tf.contrib.signal.inverse_stft_window_fn(frame_step))
sess = tf.Session()
stft, invstft = sess.run((stft, invstft))
print(invstft.shape)
```
The output shape of invstft is then (120320,). And I don't know how it got there. In my opinion it should be again (120800).

**Comment by ravikyram** [comment]
I have tried on colab with TF version1.14 , 1.15.0-rc0 and see output shape of invstft is (120320,).Thanks!

**Comment by risajef** [comment]
With trial and error I found out that the ouput shape seems to be: ```audioNp[0].shape//frame_step*frame_step```
So rounded down to a multiple of frame_step. But can anyone confirm this?

**Comment by rryan** [comment]
Thanks for the report! This is actually intended behavior. The padding behavior of `tf.signal.stft` can be set via the `pad_end` keyword argument. If you set `pad_end=True`, you'll get a `(1, 120832)` Tensor out, while the default (`pad_end=False`), will truncate the signal to only compute the STFT over full frames and give you `(1, 120320)`. There's no way we can give you the exact size of your input back because the input to `tf.signal.inverse_stft` is an integer number of frames. Hope that helps :).
