### ISSUE TITLE
Cannot import tensorflow.image since 2019-09-06

### ISSUE THREAD

**Issue by vmarkovtsev** [tensorflow/tensorflow#32630]
I am running Linux. 

Executing the following works:
```
pip3 install tf-nightly-gpu-2.0-preview==2.0.0.dev20190903
python3 -c "import tensorflow.image"
```

There were no nightly builds on 4th and 5th. The following does not work:
```
pip3 install tf-nightly-gpu-2.0-preview==2.0.0.dev20190906
python3 -c "import tensorflow.image"
```

I get

```
ModuleNotFoundError: No module named 'tensorflow.image'
```

This still reproduces on the most recent nightly 2.0.0.dev20190918.

**Comment by vmarkovtsev** [comment]
The following fixes the import problem: add

```python
from tensorflow.python.util import module_wrapper as _module_wrapper

if not isinstance(_sys.modules[__name__], _module_wrapper.TFModuleWrapper):
  _sys.modules[__name__] = _module_wrapper.TFModuleWrapper(
      _sys.modules[__name__], "", public_apis=None, deprecation=False,
      has_lite=False)
```

before `# WRAPPER_PLACEHOLDER` in `tensorflow_core/__init__.py`.

**Comment by vmarkovtsev** [comment]
I believe that this is a "featured" bug, but I will happily PR the fix if needed.

**Comment by mihaimaruseac** [comment]
Just to check, does the following work?

```python
import tensorflow as tf
print(tf.image)
```

**Comment by vmarkovtsev** [comment]
That works:
```
<module 'tensorflow_core._api.v2.image' from '/usr/local/lib/python3.7/dist-packages/tensorflow_core/_api/v2/image/__init__.py'>
```

**Comment by mihaimaruseac** [comment]
Perfect. That is the only supported way to use TF API, all the other ways can break as we progress our API. Unfortunately, Python allows you to do all kinds of imports, accessing private stuff, etc but this is also brittle.

Please use the `import tensorflow as tf; tf.image` approach

**Comment by gadagashwini** [comment]
Closing this issue since its resolved. 
Feel free to reopen if the issue still persists. Thanks!

**Comment by kmamine** [comment]
Issue still persists 

` ---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-12-4c38243be73f> in <module>()
      3 import numpy as np
      4 
----> 5 import tensorflow.image.encode_jpeg
      6 import tensorflow.image.decode_jpeg
      7 import tensorflow.image.adjust_jpeg_quality

ModuleNotFoundError: No module named 'tensorflow.image'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
`---------------------------------------------------------------------------`

**Comment by kmamine** [comment]
Issue persists 

> 
---------------------------------------------------------------------------

ModuleNotFoundError                       Traceback (most recent call last)

<ipython-input-12-4c38243be73f> in <module>()
      3 import numpy as np
      4 
----> 5 import tensorflow.image.encode_jpeg
      6 import tensorflow.image.decode_jpeg
      7 import tensorflow.image.adjust_jpeg_quality

ModuleNotFoundError: No module named 'tensorflow.image'


---------------------------------------------------------------------------
NOTE: If your import is failing due to a missing package, you can
manually install dependencies using either !pip or !apt.

To view examples of installing some common dependencies, click the
"Open Examples" button below.
---------------------------------------------------------------------------

**Comment by gadagashwini** [comment]
@vmarkovtsev,
Please use the imports as follows:
```
import tensorflow as tf
encode = tf.image.encode_jpeg
decode = tf.image.decode_jpeg
adjust_quality = tf.image.adjust_jpeg_quality
```
Thanks!
