### ISSUE TITLE
Why doesn't tf.matmul work with transposed tensor?

### ISSUE THREAD

**Issue by qo4on** [tensorflow/tensorflow#32658]
Why doesn't `tf.matmul` work with transposed tensor?

`transpose_b=True` is ok, but not `tf.transpose(inp)`.

This screenshot was made in Colab with `tensorflow-gpu==2.0.0-rc1`:

![image](https://user-images.githubusercontent.com/35609308/65253964-f2bfdd80-db14-11e9-859f-ca6a38498d20.png)

**Comment by WindQAQ** [comment]
Hi @qo4on, it's because you are trying to transpose 3D tensor with `tf.transpose`. The `perm` argument defaults to `None` and will transpose the first and last axis only. You have to let `perm=[0, 2, 1]` so that the shape is compatible with batch matrix multiplication.

The workable example is here:
https://colab.research.google.com/drive/1JMEpncNz23mQ4EHOj1QUak27sH1Iw-lg

**Comment by qo4on** [comment]
Hi, WindQAQ. Thank you.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
