### ISSUE TITLE
tensorflow 2.0.0b0 ImportError: cannot import name 'Layer'

### ISSUE THREAD

**Issue by xichuanhit** [tensorflow/tensorflow#32678]
When I import the tensorflow, it has show the following errors :
(tensorflow 2.0.0b0)
> import tensorflow as tf
> Traceback (most recent call last):
> 
>   File "<ipython-input-12-64156d691fe5>", line 1, in <module>
>     import tensorflow as tf
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
>     from tensorflow.python.tools import module_util as _module_util
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 83, in <module>
>     from tensorflow.python import keras
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
>     from tensorflow.python.keras import applications
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\applications\__init__.py", line 25, in <module>
>     from tensorflow.python.keras import engine
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\__init__.py", line 23, in <module>
>     from tensorflow.python.keras.engine.base_layer import Layer
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 50, in <module>
>     from tensorflow.python.keras.saving import saved_model
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\__init__.py", line 20, in <module>
>     from tensorflow.python.keras.saving.hdf5_format import load_attributes_from_hdf5_group
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 32, in <module>
>     from tensorflow.python.keras.utils import conv_utils
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\__init__.py", line 38, in <module>
>     from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\multi_gpu_utils.py", line 22, in <module>
>     from tensorflow.python.keras.engine.training import Model
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 39, in <module>
>     from tensorflow.python.keras import metrics as metrics_module
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\metrics.py", line 33, in <module>
>     from tensorflow.python.keras.engine.base_layer import Layer
> 
> ImportError: cannot import name 'Layer'
> 
> 
> 
> 
> import tensorflow as tf
> Traceback (most recent call last):
> 
>   File "<ipython-input-13-64156d691fe5>", line 1, in <module>
>     import tensorflow as tf
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\__init__.py", line 40, in <module>
>     from tensorflow.python.tools import module_util as _module_util
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\__init__.py", line 83, in <module>
>     from tensorflow.python import keras
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\__init__.py", line 27, in <module>
>     from tensorflow.python.keras import applications
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\applications\__init__.py", line 25, in <module>
>     from tensorflow.python.keras import engine
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\__init__.py", line 23, in <module>
>     from tensorflow.python.keras.engine.base_layer import Layer
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 50, in <module>
>     from tensorflow.python.keras.saving import saved_model
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\__init__.py", line 20, in <module>
>     from tensorflow.python.keras.saving.hdf5_format import load_attributes_from_hdf5_group
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py", line 32, in <module>
>     from tensorflow.python.keras.utils import conv_utils
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\__init__.py", line 38, in <module>
>     from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\utils\multi_gpu_utils.py", line 22, in <module>
>     from tensorflow.python.keras.engine.training import Model
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\engine\training.py", line 39, in <module>
>     from tensorflow.python.keras import metrics as metrics_module
> 
>   File "D:\Users\1\Anaconda3\lib\site-packages\tensorflow\python\keras\metrics.py", line 33, in <module>
>     from tensorflow.python.keras.engine.base_layer import Layer
> 
> ImportError: cannot import name 'Layer'
How to deal with it ? Should I pip the tensorflow 2.0 agnain ?

**Comment by gadagashwini** [comment]
@xichuanhit,
Please uninstall available tensorflow and python and install both again. Please try installing latest Tf version 2.0.0.rc1.  Thanks!

**Comment by gadagashwini** [comment]
@xichuanhit, 
Any update!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by prpeixoto** [comment]
I'm having the same issue, I've tried uninstalling and installing again both python and TensorFlow and it didn't work

**Comment by gadagashwini** [comment]
@prpeixoto, Which Tensorflow and python version are you trying to install?

**Comment by prpeixoto** [comment]
@gadagashwini thank you for the reply. I'm using tensorflow 2.0 and Python 3.7 on windows. I was previously using tensorflow 2.1, but downgraded since other issues were occurring that were resolved when downgrading.
The current issue is as follows:
ImportError("cannot import name 'Layer' from 'tensorflow.python.keras.engine.base_layer'
 Any ideas or suggestions on what could be causing this and how to resolve this? Thank you

**Comment by gadagashwini** [comment]
@prpeixoto, Could you open the new issue by providing information asked in [Template](https://github.com/tensorflow/tensorflow/issues/new/choose). Issue could be configuration specific.

**Comment by prpeixoto** [comment]
Of course, just did it, https://github.com/tensorflow/tensorflow/issues/36162
Thank you

**Comment by Githubpython96** [comment]
I have solved this problem by using anaconda.Use "conda install -c conda-forge tensorflow" in cmd on Windows.I have used pip and pycharm tools but failed.I uninstalled it and run "conda install -c conda-forge tensorflow".This works.

**Comment by aliqwecdsc** [comment]
I'm having the same issue, I've tried uninstalling and installing again both python and TensorFlow and it didn't work

**Comment by aliqwecdsc** [comment]
C:\Users\LENOVO\PycharmProjects\pythonProject1\venv\Scripts\python.exe C:\Users\LENOVO\PycharmProjects\pythonProject1\venv\Lib\site-packages\keras_vggface\vggface.py 
2024-02-22 20:50:57.382238: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
WARNING:tensorflow:From C:\Users\LENOVO\PycharmProjects\pythonProject1\venv\lib\site-packages\keras\src\losses.py:2976: The name tf.losses.sparse_softmax_cross_entropy is deprecated. Please use tf.compat.v1.losses.sparse_softmax_cross_entropy instead.

Traceback (most recent call last):
  File "C:\Users\LENOVO\PycharmProjects\pythonProject1\venv\Lib\site-packages\keras_vggface\vggface.py", line 9, in <module>
    from keras_vggface.models import RESNET50, VGG16, SENET50
  File "C:\Users\LENOVO\PycharmProjects\pythonProject1\venv\lib\site-packages\keras_vggface\__init__.py", line 1, in <module>
    from keras_vggface.vggface import VGGFace
  File "C:\Users\LENOVO\PycharmProjects\pythonProject1\venv\lib\site-packages\keras_vggface\vggface.py", line 9, in <module>
    from keras_vggface.models import RESNET50, VGG16, SENET50
  File "C:\Users\LENOVO\PycharmProjects\pythonProject1\venv\lib\site-packages\keras_vggface\models.py", line 16, in <module>
    from keras.utils import layer_utils
ImportError: cannot import name 'layer_utils' from 'keras.utils' (C:\Users\LENOVO\PycharmProjects\pythonProject1\venv\lib\site-packages\keras\utils\__init__.py)

Process finished with exit code 1
