### ISSUE TITLE
Android Examples

### ISSUE THREAD

**Issue by ferdinan97** [tensorflow/tensorflow#32710]
i already install and run tensorflow examples but it consist of tf_classify,tf_detect,tf_speech and tf_style. so can anyone tell me how to install only tf_detect ?

**Comment by oanush** [comment]
@ferdinan97 ,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
Make sure you also include the exact command if possible to produce the output included in your test case. 
If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ferdinan97** [comment]
**System information**
- OS Platform :Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Asus Zenfone 4 max
- TensorFlow installed from (source or binary):pip install tensorflow gpu==1.13.1
- TensorFlow version:1.13.1
- Python version:3.6.9
- Installed using :miniconda
- Bazel version (if compiling from source): no bazel
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.0
- GPU model and memory:Nvdia Geforce 970MX



**Describe the problem**
How can i only install TF_Detect from tensorflow (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android) that consist of tf_style,tf_detect,tf_classify and tf_speech ? cause i only need tf_detect

**Comment by jdduke** [comment]
Please look at the TensorFlow Lite examples [here](https://github.com/tensorflow/examples/tree/master/lite). They are each packaged separately.

**Comment by ferdinan97** [comment]
Actually i know about that, but the model i work didnt support the tensorflow lite thats why i ask this question. Can you reopen the issue or give me solution ?

**Comment by jdduke** [comment]
We won't be updating the TF Mobile example any further, so there's no way to decouple the tf_detect portion from the other examples. You'd have to manually pull out just the necessary code.

**Comment by ferdinan97** [comment]
Ok then , thank you
