### ISSUE TITLE
Tensorflow Lite for Android on x86_64

### ISSUE THREAD

**Issue by dimitryn** [tensorflow/tensorflow#32724]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
ubuntu 16.0
- TensorFlow installed from (source or binary):
Yes
- TensorFlow version (or github SHA if from source):
master

Hi  , I like to build Tensorflow Lite to run on x86_64 with Android.
I see there is package downloaded  NEON_2_SSE and there is a scripts in tools/make build_XXX for Android/Ios/RPI
Can anyone suggest how to combine both SSE and Android .
Thanks.

**Comment by jdduke** [comment]
We publish .aar's that have x86_64 binaries. If you look at [our examples](https://www.tensorflow.org/lite/examples), each of them should run on x86_64 when built with Android Studio and/or gradle.

Otherwise, if you want to build manually, you can follow the instructions @ https://www.tensorflow.org/lite/guide/android. The x86 build should automatically use NEON_2_SSE for our CPU kernels.
