### ISSUE TITLE
A question about tensorflow lite

### ISSUE THREAD

**Issue by GGGWB** [tensorflow/tensorflow#32765]
I am a machine learning beginner. And I want to know the scale of neural networks and and the number of parameters that tensorflow lite can support  so far, because I have not found a similar answer elsewhere. I look forward to your answer.

**Comment by ravikyram** [comment]
@GGGWB 

Please, go through [TensorFlow Lite guide](https://www.tensorflow.org/lite/guide) and see if it helps you.Thanks!

**Comment by GGGWB** [comment]
Thank you very much for your answer, but I have read the TensorFlow Lite guide carefully and still have not found the relevant answer. In your experience, taking the perceptron as an example, how many layers and how many nodes per layer can be executed on the mobile phone. Additionally, I would like to know, when will the training be implemented on mobile devices? Thank you once again for your answer.

**Comment by jvishnuvardhan** [comment]
@GGGWB This is a stale issue.

Since the issue opened, there were lot of improvements in TFlite and micro. Difficult to say how many neurons, hidden layers without knowing the target device. But, Some of the big models were converted to TFLite format and used for `object_detection`, `pose_estimation`, `speech recognition`, `segmentation` and many more applications. Please feel free to check those pre-trained models and examples https://www.tensorflow.org/lite/examples

I am closing this issue. Please feel free to reopen if there are any more questions. Thanks!
