### ISSUE TITLE
ValueError when passing tensors to keras subclass model calls

### ISSUE THREAD

**Issue by sghoshjr** [tensorflow/tensorflow#32764]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 / Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Not tested
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.0.0-rc0 / rc1 / rc2
- Python version: 3.7.4
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 10.0 / 7.6.3
- GPU model and memory: Quadro K620

**Describe the current behavior**
Using conditional statements on tensors passed to keras subclassed models without `@tf.function` decorator leads to ValueError Exception
` ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: Identity.  Input index: 0. Original input shape: (64, 1024).  Calculated input gradient shape: (32, 1024)`
Neither `tf.cond` or python's if statement work without decorator.

The Model works fine if the call function is decorated with `@tf.function` decorator.
Passing Python Boolean values instead of `tf.constant(True)` works fine, with and without `@tf.function` decorator.
  
**EDIT**: Eager mode works fine. (without any `@tf.function`)

**Describe the expected behavior**
The model should work without mandating `@tf.function` decorator. See the code for details.

**Code to reproduce the issue**
Code that reproduces the problem. [Colab Link](https://colab.research.google.com/drive/1zNGK5sc3JVVveg-5Fe3JE0MVqxgd6h6d)

**Other info / logs**

    ValueError: in converted code:

    <ipython-input-26-76bba83ea439>:12 train_step  *
        gradients_mdan = tape.gradient(model_loss, model.trainable_variables)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/backprop.py:1014 gradient
        unconnected_gradients=unconnected_gradients)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/imperative_grad.py:76 imperative_grad
        compat.as_str(unconnected_gradients.value))
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/eager/backprop.py:138 _gradient_function
        return grad_fn(mock_op, *out_grads)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:120 _IfGrad
        true_graph, grads, util.unique_grad_fn_name(true_graph.name))
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:395 _create_grad_func
        func_graph=_CondGradFuncGraph(name, func_graph))
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/func_graph.py:915 func_graph_from_py_func
        func_outputs = python_func(*func_args, **func_kwargs)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:394 <lambda>
        lambda: _grad_fn(func_graph, grads), [], {},
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/cond_v2.py:373 _grad_fn
        src_graph=func_graph)
    /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gradients_util.py:714 _GradientsHelper
        (op.name, i, t_in.shape, in_grad.shape))

    ValueError: Incompatible shapes between op input and calculated input gradient.  Forward operation: Identity.  Input index: 0. Original input shape: (64, 1024).  Calculated input gradient shape: (32, 1024)

**Comment by qlzh727** [comment]
Adding @mdanatg since this might related to auto graph.

**Comment by qlzh727** [comment]
@sghoshjr, since you have some confusion about tf.function, let me provide some more details.

1. TF function will turn a python into a tf graph, which will speed up the training performance. This also means for any value created in the body of a tf function, they will be traced and lift out from the graph. In your case, the python boolean will be convert to tensor automatically if they are created within tf.function.

2. Checking against the boolean value in call(). Most likely, your model call() method is executed in the graph context, which mean the if check of the boolean tensor will probably not work as expected (eg it will just do a None check), unless the auto graph is enabled(default behavior). In the call body of your example, the "if tf.reduce_all(....)" is likely to be the issue here. The correct way to do it is using tf.cond(), and make sure the result from True and False branch should have the same shape (in your case they don't).

I think its highly likely that auto graph converted your code, created a wrong shape gradient by relying on the True branch shape, while the execution path actually goes to False branch. The error message maybe complaining the wrong place, and we probably should update it (eg, the True/False branch should have the same shape), which should point you to fix your model.

After I fix the shape of True/False branch, the model trains correctly.

More general comments for your code:
1. For any static value that don't change, probably create them as python types in the __init__ method in model, rather than passing them around in the call().
2. Annotation the outmost training function with tf.function is enough. The keras model call() method already have some handling of graph context, and it doesn't need any tf.function usually.

**Comment by mdanatg** [comment]
I think in this case autograph is used in both cases, so the `if` statement is fine - I checked that it's converted to `tf.cond` in all cases. BTW, I get the shape error even when `source_train` is a Python boolean - can you double-check?

The gradient calculation should work even if the `tf.cond` returns different shapes, and indeed it does when `tf.function` is added. So the fact that it works with `tf.function` but not without definitely looks like a bug.

@saxenasaurabh @alextp any idea where the error might be coming from?

**Comment by sghoshjr** [comment]
Code generated by Autograph is the same whenever `@tf.function` is used. As I understand, it recursively converts the child function calls as well.

When using Python Boolean along with `if source_train is True:` py cond, it works as expected. [[this works](https://colab.research.google.com/drive/1Pte92bg40-cqdypvDhzlCfmwZTR8FSyR)]

But using tf tensors, along with `tf.equal` check does not work. It works only in eager mode, not in graph mode.

Also, in the autograph converted code, all tensors past the conditional statement had a batch size of `None`. To get the batch size, the tensors need to be returned from the function decorated with `@tf.function`.

So in my case, `l_logits` had a shape of `[None, 10]`. It should be `[32, 10]` (with source_train to False).
Changing the loss function to `loss_func(l_logits[0:32], labels)` also works, even when passing tf tensors. [[this also works](https://colab.research.google.com/drive/1AY_0RcaL_ob6eiJ5ma6WNBegr19R__eg)]

**Comment by sghoshjr** [comment]
Just to be clear, the original code does work in eager mode. i.e. removing both the `@tf.function` decorator.

**Comment by saxenasaurabh** [comment]
The shape of `feature_slice` is different in both branches of `if`. It seems that only one branch is expected to be used during training, however the graph building code does not know this and tries to build gradient functions for both branches and it sees an inconsistency in the shape of the output gradient.

I didn't dig too deep but the reason this works with adding `tf.function` is that somehow the input gradient wrt `feature_slice` has an undefined size for the batch dim in that case. So now the output gradients wrt `feature` from both branches has undefined size for the batch dim which are compatible. The incomplete shape here is probably a bug.

I think you should be using a python bool here.

One thing I am unclear about is why we allow building a `tf.cond` with incompatible output shapes in the first place. I will look into that.

**Comment by mdanatg** [comment]
@kkimdev FYI

I concur with @saxenasaurabh, although there are a few separate issues. I ran multiple combinations to try to see what happens. It looks like the `else` branch of the `if` statement is incorrect, and the error that you get when that's actually executed is a bit more helpful: "logits and labels must be broadcastable: logits_size=[64,10] labels_size=[32,10]".

By the way, you can safely write `if source_train == False:` and it will work correctly with tensors too (you no longer need to write tf.equal). I'll use that below.

Here is what I observed:
  * both `tf.function` decorators off + `output = model(images, True)`:
    * raises "logits and labels must be broadcastable: logits_size=[64,10] labels_size=[32,10]"
  * both `tf.function` decorators off + `output = model(images, False)`: works
  * both `tf.function` decorators off + `output = model(images, tf.constant(True))`:
    * raises "logits and labels must be broadcastable: logits_size=[64,10] labels_size=[32,10]"
  * both `tf.function` decorators off + `output = model(images, tf.constant(False))`: works
  * `train_step` decorator on, `call` decorator off  + `output = model(images, True)`:
    * raises "Dimensions must be equal, but are 64 and 32 for 'softmax_cross_entropy_with_logits"
  * `train_step` decorator on, `call` decorator off  + `output = model(images, False)`: works
  * `train_step` decorator on, `call` decorator off  + `output = model(images, tf.constant(True))`:
    * raises "Incompatible shapes between op input and calculated input gradient"
  * `train_step` decorator on, `call` decorator off  + `output = model(images, tf.constant(False))`:
    * raises "Incompatible shapes between op input and calculated input gradient"
  * both `tf.function` decorators on + `output = model(images, True)`:
    * raises "Dimensions must be equal, but are 64 and 32 for 'softmax_cross_entropy_with_logits"
  * both `tf.function` decorators on + `output = model(images, False)`: works
  * both `tf.function` decorators on + `output = model(images, tf.constant(True))`:
    * raises "logits and labels must be broadcastable: logits_size=[64,10] labels_size=[32,10]"
  * both `tf.function` decorators on + `output = model(images, tf.constant(False))`: works

So, the conclusion is that based on whether `tf.function` is added, you get a different error message, and in one case there is an error even when the good branch would otherwise be executed. This is something that we'll need to remedy.

**Comment by sghoshjr** [comment]
The `source_train` was supposed to be used to be used to with a dataset of batch size of 64. (so, in the snippet, it should not be True). Likewise, 

> "logits and labels must be broadcastable: logits_size=[64,10] labels_size=[32,10]"

its supposed to use a different dataset which has 64 batch sized labels.
See the use case here: [DANN Implementation](https://github.com/sghoshjr/Domain-Adversarial-Neural-Network/blob/master/DANN.py)

Also, slicing along the batch axis should be supported. `tf.cond` does allow partial shapes.

1. Why does python boolean or `==` work, but not `tf.equal` check.
2. Why does decorating both calls remove the error? Both functions are converted by autograph in each case.
3. Python conditionals allows to build even models with different no. of outputs. But why does `tf.cond` require same shape of outputs.

**Comment by mdanatg** [comment]
A few answers:
 1. Ultimately it's all about the type of the expression in the `if` condition. If the condition evaluates to a Python boolean, then the `if` statement remains a Python `if`. If it evaluates to a `Tensor`, then the statement is a `tf.cond`. Check out the [autograph reference](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/g3doc/reference/control_flow.md#if-statements) for more info. When you use `tf.equal`, its result is always a Tensor, but when you use `==`, the result is the type of `source_train`. To convince yourself, of that, add this print: `print(type(source_train == True))` and see how the type of `source_train` matches the result (and how the buggy case happens when it prints Tensor).

 2. By the looks of it, that is a bug.

 3. tf.cond is fine with different output shapes. But as you can see from the above, in one of the cases the gradient calculation doesn't like it - that's probably the same bug as (2).

Having `source_train` be connected to the dataset size explains things. In that case, it's probably easiest to use a Python boolean because you don't need to support both batch sizes in the same run and it avoids the bug.

BTW, you can actually write that `if` statement as simply `if source_train:`. It will work in just the same way as `if source == True:`.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2 and TF-nightly i.e. v2.4.0-dev20200722. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/02a7b325e8148baa5e3e4b2e461abe04/32764.ipynb). Thanks!

**Comment by mdanatg** [comment]
Unfortunately I didn't have time to work on this, un-asigning myself. For reference, the issue amounts to inconsistent error messages.

**Comment by saikumarchalla** [comment]
I can able to reproduce the issue using TF version 2.5 and 2.6 nightly as well. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/8de352e91567f8fe9fd8ef459743ef73/32764.ipynb).Thanks!

**Comment by sushreebarsa** [comment]
@sghoshjr Was able to reproduce the issue in TF v2.7.0,Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/a174d38fd3ac0e53288b5f8e77052f19/32764.ipynb#scrollTo=mRConvYwwvCd).Thanks!

**Comment by tensorflowbutler** [comment]
Hi There,

 This is a stale issue. As you are using an older version of tensorflow, we are checking to see if you still need help on this issue. Please test the issue with the latest TensorFlow (TF2.7 and tf-nightly). If the issue still persists with the newer versions of TF, please feel free to open it in [keras-team/keras](https://github.com/keras-team/keras/issues) repository by providing details about the issue and a standalone code to reproduce the issue. Thanks! 

 Please note that Keras development has moved to a separate Keras-team/keras repository to focus entirely on only Keras. Thanks!
