### ISSUE TITLE
XLA bug w/ Keras: "Node name contains invalid characters"

### ISSUE THREAD

**Issue by nikitos9000** [tensorflow/tensorflow#32873]
**System information**
- Have I written custom code: yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): tensorflow-gpu==1.14.0+nv
- Python version: 3.6.8
- CUDA/cuDNN version: 10.1
- GPU model and memory: RTX 2080 Ti, NVIDIA Driver 418.43

**Describe the current behavior**

Shows the warning at the predict time:
```2019-09-27 11:02:42.377419: W tensorflow/core/common_runtime/process_function_library_runtime.cc:667] Ignoring multi-device function optimization failure: Invalid argument: Node '_arg_segments_ids_input_0_1_0_arg': Node name contains invalid characters```

And doesn't enable XLA optimizations as I can see (performance doesn't improve)

**Describe the expected behavior**

There should be no problem at all.

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

Occured in a real-case keras-bert based code, but reproduces in the following code:

```
import numpy as np
import tensorflow as tf
from tensorflow.keras.backend import set_session
from tensorflow.keras.layers import Input, Embedding, Add
from tensorflow.keras.models import Model

config = tf.ConfigProto()
config.graph_options.optimizer_options.global_jit_level = tf.OptimizerOptions.ON_1
set_session(tf.Session(config=config))

seq_len = 80
batch_size=5000

tokens_ids_input = Input(shape=(seq_len, ), dtype='int32', name='tokens_ids_input')
segments_ids_input = Input(shape=(seq_len, ), dtype='int32', name='segments_ids_input')

output = Add()([Embedding(input_dim=5000, output_dim=16)(tokens_ids_input), Embedding(input_dim=2, output_dim=16)(segments_ids_input)])

model = Model(inputs=[tokens_ids_input, segments_ids_input], outputs=[output])

model.predict([np.zeros((batch_size, seq_len)), np.zeros((batch_size, seq_len))])
```

**Comment by gadagashwini** [comment]
@nsmetanin, I executed on Colab with Tf 1.14.0. But it didn't throw any error. Please take a look at [colab gist](https://colab.sandbox.google.com/gist/gadagashwini/57dd2eae878e43da89dbc146409c59a5/untitled169.ipynb) and confirm the expected behavior. Thanks!

**Comment by nsmetanin** [comment]
I'm able to reproduce the bug in the "tensorflow/tensorflow:1.14.0-gpu-py3" docker container. Google Colab has K80 GPU while I have RTX 2080 Ti, so I think this bug could be related to the 2080 GPUs and/or CUDA 10.1 only.

**Comment by gadagashwini** [comment]
@nsmetanin, Can you try with with CUDA 10.0. And,  Let us know if issue still persists. Thanks!

**Comment by nsmetanin** [comment]
That reproduces both with CUDA 10.1 and 10.0 (as in tensorflow/tensorflow:1.14.0-gpu-py3 image)

**Comment by jvishnuvardhan** [comment]
@nsmetanin Can you try recently released `TF1.15.0rc2` and let us know whether the issuer persists there? Thanks!

**Comment by nsmetanin** [comment]
The (mostly) same error in tensorflow/tensorflow:1.15.0rc2-gpu-py3:

`2019-10-04 10:25:57.285825: W tensorflow/core/common_runtime/process_function_library_runtime.cc:688] Ignoring multi-device function optimization failure: Invalid argument: Node '_arg_tokens_ids_input_0_0_0_arg': Node name contains invalid characters`

The difference is that previously the problem was with "_arg_segments_ids_input_0_1_0_arg" node name and now with the "_arg_tokens_ids_input_0_0_0_arg". This error occurs as the node names can't start with underscore, but for some reason in these cases they do.

**Comment by sanjoy** [comment]
I don't think the log you're seeing signifies a hard error since it is a `LOG(WARNING)`.  But CC @iganichev who added the warning line.

As for why XLA does not provide a speedup, have you confirmed that XLA is kicking in?  You should see a `Compiled cluster using XLA!` log if it is kicking in.

Note that speedups using XLA is expected but not guaranteed.

**Comment by iganichev** [comment]
That error is indeed non-fatal. It is warning that some optimizations could not be performed.

@sanjoy maybe some Keras folks can take a look at who produces these badly named nodes.

**Comment by nsmetanin** [comment]
Yes, you're right, I can't really tell if it disables all optimizations made or only a part of them due to this error.

**Comment by dmaniry** [comment]
I can confirm that there is a considerable speed difference between networks where this warning shows up and networks where it doesn't. I can also see from profiling that the former case splits the network into multiple XLA clusters and the latter turns it into a single cluster. I'm still trying to find which difference causes the ghost underscore node to show up. It is not in the graph_def!

**Comment by Saduf2019** [comment]
@nsmetanin 
Is this still an issue

**Comment by jeisinge** [comment]
I am seeing this issue on one of my models:
> 2020-05-12 18:32:58.336604: W tensorflow/core/common_runtime/process_function_library_runtime.cc:688] Ignoring multi-device function optimization failure: Invalid argument: Node '_arg_foo_input_bar_0_4_0_arg': Node name contains invalid characters

This is with Nvidia's Triton with XLA enabled.

**Comment by YanDavKMS** [comment]
I am seeing the same issue with my model, Did someone find a solution or can we please reopen this issue?

**Comment by jeisinge** [comment]
I'm still seeing the issue as well. I'm not sure if it is causing any
performance issues, though.

**Comment by YanDavKMS** [comment]
I'm not sure as well. From what @dmaniry said there is.
Also there is the initial delay on the first inference this error appears. for me it was of about 40 seconds

**Comment by dishengbin** [comment]
I have got the same issue, both on GTX 2080ti and V100s. Does anyone have a solution?

**Comment by deekshant-w** [comment]
Did anyone find a solution to this? I have the same issue on GTX 1660 Ti.

**Comment by jinluyang** [comment]
I have the same problem on T4. I found it was because my Node name has an underscore "_" at the beggining, in function:
bool IsValidNodeName(StringPiece s, bool allow_internal_ops)
when allow_internal_ops is false, it throws this error.
In my case, the allow_internal_ops depends on tensorflow::GraphConstructorOptions which is not set when calling ConvertGraphDefToGraph.
I changed the opts to allow internal ops and then the warning disappeared.
