### ISSUE TITLE
Slicing of rank>=6 tensor?

### ISSUE THREAD

**Issue by metap** [tensorflow/tensorflow#3293]
Currently it throws a not implemented error "inputs rank not in [0,5]".

**Comment by jmchen-g** [comment]
It is not supported as we don't see a good use case yet. What is yours here?

**Comment by metap** [comment]
Some new convolutional layers invented in the last few months for superresolution etc. require further division of the H and W dimension like [N, C, H, H_sub, W, W_sub]. Although the slicing can be simulated via reshaping and slicing in a lower rank tensor, it's just doesn't feel right when T.transpose() and T.reshape() are both supported for rank 6 tensor and T.slice() isn't.

**Comment by infnorm** [comment]
Interesting, could you give a citation of papers that do this. It is difficult to extend past 5 in the current framework because it requires more Eigen template instantiation which would bloat the binary. One way to get around this would be to implement a catchall non templatized version of slice. Most ops don't really support more than 5 so you probably will hit this on many other ops as well.

**Comment by aselle** [comment]
Interesting, could you give a citation of papers that do this. It is difficult to extend past 5 in the current framework because it requires more Eigen template instantiation which would bloat the binary. One way to get around this would be to implement a catchall non templatized version of slice. Most ops don't really support more than 5 so you probably will hit this on many other ops as well.

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when further information becomes available.
