### ISSUE TITLE
Is it possible to convert a FP16 checkpoints to be compatible with FP32 runs ?

### ISSUE THREAD

**Issue by sgambient** [tensorflow/tensorflow#32937]
Hi, looks like AMP ( or FP16) trained  checkpoints are not compatible with non AMP  session runs in Tensorflow.   Is it possible to convert a check point to be compatible with both AMP and non-AMP runs ?

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by sgambient** [comment]
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary): binary
TensorFlow version (use command below): 1.14
Python version: 2.7
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:10.1
GPU model and memory: T4

**Comment by ravikyram** [comment]
@sgambient 

Will it be possible to share simple standalone code to reproduce the issue.Please provide as many details as possible to find the root cause of the issue.

**Comment by sgambient** [comment]
What code do you want ?  I am puzzled.  You can just take any  ResNet code from slim/official  area , train with FP16 ( e.g. AMP for Nvidia) and generate a checkpoint.  Then try to load that checkpoint without enabling FP16.

**Comment by jvishnuvardhan** [comment]
@sgambient This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks!
