### ISSUE TITLE
TensorFlow 2.x Java/Maven release

### ISSUE THREAD

**Issue by maziyarpanahi** [tensorflow/tensorflow#32943]
Hello,

Our library really depends on `libtensorflow` and `libtensorflow_jni_gpu` releases on Maven, is there any ETA for releasing TensorFlow 2.0 on Maven? The latest release is `1.14.0` now.

Many thanks

**Comment by maziyarpanahi** [comment]
@sjamesr Any update or ETA on TensorFlow release on Maven? The last version of TF that works in Java was `1.13.1` since the `1.14.0` has a bug and we are blocked updating to TF 2.0.

Many thanks

**Comment by andrewsmartin** [comment]
+1, any updates on this? My organization is also blocked upgrading because of the bug in 1.14.

**Comment by mattnworb** [comment]
Specifically we are eager to upgrade to 1.15 due to https://github.com/tensorflow/tensorflow/issues/30635

**Comment by maziyarpanahi** [comment]
@mattnworb FTI, the `1.15.0` is finally available on Maven. Looking forward to see `2.0.0` there as well.

**Comment by maziyarpanahi** [comment]
I have renamed the title to TensorFlow `2.x` as I can see there is still no news from Java in the upcoming `2.1.0` RC.

**Comment by jakemannix** [comment]
Is there any progress / roadmap / plan on this?  TF2 has been out for a while, and not even a plan on java support... is pretty unsatisfying.

**Comment by xiaoyunwu** [comment]
Any plan on support tensorflow 2.0 for java?

**Comment by zhedongzheng** [comment]
Please support TF2 in Java

**Comment by tastyminerals** [comment]
We have been using java API to implement our first prototype back ago when TF was 1.10 and then kept slowly moving ahead until 1.14.0 version. Now, we'd like to upgrade the old code to 2.0 but having no official support or response for 2.0 is quite discouraging. Having no roadmap is even worse because we cannot plan anything. We also cannot wait until the nobody knows when.

We started switching to PyTorch with newer models and at this point I am eager to push the team to do the same for the older Tensorflow models still running on prod.

**Comment by maziyarpanahi** [comment]
Hi @tastyminerals 
How are you using PyTorch in Java? Is this a native support for Java by PyTorch that is cross-platform like TensorFlow in Java?

**Comment by tastyminerals** [comment]
> Hi @tastyminerals
> How are you using PyTorch in Java? Is this a native support for Java by PyTorch that is cross-platform like TensorFlow in Java?

There is none.
We just spawn new Python services for every model. This works for us because we also have Python based system API that talks to these services. It is just more work of course. With older model it's a bit tricky since it depends on custom Java packages which we didn't port. This is the only thing that stops us from the switch tbo.

**Comment by tastyminerals** [comment]
There is[ this repo ](https://github.com/tensorflow/java)which I suspect has something to do with TF2.0 support.

**Comment by maziyarpanahi** [comment]
Yes, I've been following that repo and it is a new Java for TF (or TF 2.x) with support for training and lots of other stuff. It is in an early stage and as fast as the Python side is going forward with new releases, I expected to have at least one Java release for 2.0 before moving entirely to the new APIs. 
I guess it's easier to create a new Java project from scratch for TF 2.x than trying to fix and change the old Java APIs.

As for me, are project is stuck in Scala/Java so there are no alternatives at the moment.

**Comment by zhedongzheng** [comment]
Hi,

It seems Java for TF 2 is coming up

References:
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-2.3.0.jar
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow_jni-cpu-linux-x86_64-2.3.0.tar.gz
https://www.tensorflow.org/install/lang_java

**Comment by sjamesr** [comment]
@karllessard hey Karl, I haven't been keeping up on the latest with TF 2 in Java. Is there anything you can add here?

**Comment by karllessard** [comment]
Yes, all development for TF Java is actually occurring to this new repo: [github.com/tensorflow/java](https://github.com/tensorflow/java). It is build on top of TensorFlow 2.3 and support some of the new feature. We are actually targeting a first alpha release by the end of this month (September '20).
