### ISSUE TITLE
tf.train.Server.create_local_server  has two problems :1)performance drop 2 times compare to without it,2) gpu memory fraction limitations fails. 

### ISSUE THREAD

**Issue by u4lr451** [tensorflow/tensorflow#3295]
tf.train.Server.create_local_server has two problems :1)performance drop 2 times compare to without it,2) gpu memory fraction limitations fails

my model is a dnn network with 12 layers, same as the alphago policy network!

## code1: whitout server = tf.train.Server.create_local_server(start = True)
```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)

sess =  tf.Session(config=tf.ConfigProto(log_device_placement=True,allow_soft_placement=True,gpu_options=gpu_options))
```

## - code2:  using server = tf.train.Server.create_local_server(start = True)
```
gpu_options = tf.GPUOptions(per_process_gpu_memory_fraction=0.333)

    server = tf.train.Server.create_local_server(start = True)

    sess= tf.Session(target=server.target,config=tf.ConfigProto(log_device_placement=True,allow_soft_placement=True,gpu_options=gpu_options))
```

# Questions:
**1. code2 performance drop 3 times compare to code1( 3 steps/seconds vs 11 steps/seconds), why?**
**2. code2 will broke the  limitations of gpu memory. while code1 is ok**

ps: Is this relevant to this issue than the training data is read from queue?

**Comment by jmchen-g** [comment]
@mrry Could you take a look at this when you are back?

**Comment by mrry** [comment]
1. Without seeing the code, it's difficult to say why you're getting a slowdown, but the most likely problem is that you're feeding and/or fetching a large amount of data, and the increased cost of copying through the RPC interface is increasing the cost of each step. We have a medium term plan to reduce this overhead, but in the meantime you might want to revise your code to avoid feeding/fetching so much data in each step.

2. The GPU memory configuration is slightly confusing for the `tf.train.Server`. Instead of passing it in the `config` argument to the `tf.Session`, you pass the `per_process_gpu_memory_fraction` setting in the `config` argument to the `tf.train.Server` (and it affects *all* sessions against that server).

**Comment by millisecond** [comment]
I'm not the original author, but I'm having the same performance degradation when using the server.  

Here's my training loop, which I believe is straight from one of the examples: 

`for step in xrange(num_epochs * train_size // self.batch_size):
    offset = (step * self.batch_size) % train_size
    batch_data = train_data[offset:(offset + self.batch_size), :]
    batch_labels = train_labels[offset:(offset + self.batch_size)]
    train_step.run(feed_dict={x: batch_data, y_: batch_labels})`

Tried several variations on batch_size (50, 100, 1000) to saturate both processing power on the server and network usage to no avail.  Any tips / suggestions on making it more performant in the client-server scenario?

**Comment by mrry** [comment]
The server-based version uses an RPC (actually, two RPCs) to communicate the `feed_dict` to the TensorFlow runtime. There's a medium-term effort underway to improve the performance of this codepath when the data stays in the same process, but for now, for distributed training, we recommend using [input pipelines](https://www.tensorflow.org/versions/r0.10/how_tos/reading_data/index.html) so that the data do not need to be copied across the session boundary.

**Comment by girving** [comment]
It sounds like @millisecond's question is answered, and there's been no response from the OP for a while, so I'm going to close this issue for now.

**Comment by millisecond** [comment]
Hmm, I rewrote everything for the CSV input pipeline and switched all training code over to that.  Network usage dropped off to a few KB/s (vs 2MB/s before), but it performs almost identically to the previous train.  Training directly on the worker takes 11s, using client-server it takes ~40s.

This is a CPU worker, might those be single-threaded?  Wondering if only GPU workers are expected.  On the 11s train above done locally on the worker, CPU goes to many hundred % (box with 12 cores) during the train but rarely breaks 100% on the remote train.

**Comment by helinwang** [comment]
@millisecond Maybe try feed data into a TF buffered queue, and the training OPs will read the data from that queue. It still cost more CPU cycles for RPC (protobuf is really slow), but hopefully it will not have visible impact to the training time.
