### ISSUE TITLE
Freezing a graph using the C API

### ISSUE THREAD

**Issue by adaber** [tensorflow/tensorflow#32965]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

Hi everyone,

Is it possible to freeze a graph and save the frozen version using the C API after loading the graph's definition file (.pb) and restoring its variables created in Python ?

A code snippet of the "freezing" step would be greatly appreciated!

Thanks :)

**Comment by rmothukuru** [comment]
@adaber,
Can you please check [this link](https://towardsdatascience.com/creating-a-tensorflow-cnn-in-c-part-3-freezing-the-model-and-augmenting-it-59a07c7c4ec6) and let us know if it helps. If that link doesn't help, can you please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by adaber** [comment]
Hi, rmothukuru

Firstly, thank you for the response. It is very appreciated :)

My environment:

-Operating system: Windows 10
-TensorFlow version: 1.13.1 (C library: libtensorflow-gpu-windows-x86_64-1.13.1)
-Visual Studio version: 2017

I had checked out that link before and while it has a ton of useful information it is the C++ API, not the C API. For example, the author uses the "FreezeSavedModel" method that doesn't exist in the C API.

I've built C++ code (using the TF **C** API!) for loading and running a model created in Python but I would like to be able to train a model in C++ (using the TF **C** API!) and freeze it before saving it to the harddrive. I know how to train a model but don't know how to freeze it using the TF C API.

I have tried to find any information regarding this online but couldn't find any. So, my question is about freezing a model but using the C API not the C++ API. Any pointers or pseudo code would help.

Thanks again for your time, rmothukuru!

**Comment by alextp** [comment]
There's no way to freeze it using only the C API. Also freezing is unsupported going forward. @gargn to confirm.

**Comment by adaber** [comment]
Hi, alextp

Thank you for your response. I have tried to Google keywords such as "tensorflow model freezing being unsupported in the future" and didn't get any hits. Will the model file format be different in the future ? Will the network architecture and tensor values be saved to a single file by default ?

It'd be great if you could provide a bit more information if you have any at this point.

Thanks!

**Comment by gargn** [comment]
The primary supported file format in 2.0 is [SavedModel](https://www.tensorflow.org/guide/saved_model). While GraphDef is a part of the SavedModel, it is no longer an independently supported format.
