### ISSUE TITLE
Accessing validation data within a custom callback ??

### ISSUE THREAD

**Issue by hagianga21** [tensorflow/tensorflow#32981]
**Describe the current behavior**
Hi, how can I access validation data within a custom callback ?

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

```
from __future__ import absolute_import, division, print_function, unicode_literals

import os
import matplotlib.pyplot as plt
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass
import tensorflow as tf
import datetime



print("TensorFlow version: {}".format(tf.__version__))
print("Eager execution: {}".format(tf.executing_eagerly()))

from tensorflow.keras.layers import Dense, Flatten, Conv2D
from tensorflow.keras import Model

mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10, activation='softmax')
])

class MyCustomCallback(tf.keras.callbacks.Callback):
    def on_epoch_end(self, epoch, logs=None):
        print('Hello')
        print(self.validation_data[0].shape)
  
def customLoss3(y_true, y_pred):
    return tf.reduce_mean(tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred))
  
#model.compile(optimizer='adam', loss=customLoss3, metrics=['accuracy'])

model.compile(optimizer='adam', loss=customLoss3, metrics=[tf.keras.metrics.SparseCategoricalAccuracy()])

model.fit(x_train, y_train, epochs=5, validation_split=0.2, callbacks=[MyCustomCallback()])

model.evaluate(x_test, y_test)

```
**Other info / logs**
TypeError: 'NoneType' object is not subscriptable

**Comment by gowthamkpr** [comment]
Can you please try the solution mentioned in this[ issue](https://stackoverflow.com/questions/47079111/create-keras-callback-to-save-model-predictions-and-targets-for-each-batch-durin) and let me know if it helps. thanks!

**Comment by doiko** [comment]
How can we access the self.model._targets[0] and self.model.outputs[0] inside a Custom Callback at on_batch_end?

**Comment by jayaBalaR** [comment]
Hi
I am also facing this issue while defining my own custom callback. I raised it in a wrong prf earlier this morning . Quoting the reference here [(https://github.com/keras-team/keras/issues/10472.)]

Here is the test case description to reproduce the issue:
`I am executing the code on google colab and tf version is 2.2.0-rc2 , i have built a custom callback for calculating the F1 score and AUC score.
I am getting the same error with fit. I am not using fit_generators as data augmentation in not necessary in my code.

`from tensorflow.python.util.tf_export import keras_export
@keras_export('keras.callbacks.Callback')
class MyCustomCallback(tf.keras.callbacks.Callback):
def on_train_begin(self, logs={}):
self._data = []

def on_epoch_end(self, epoch, logs={}):
print(type(self.validation_data[0]))
print(type(self.validation_data[1]))
X_val, y_val = self.validation_data[0], self.validation_data[1]
y_predict = np.asarray(model.predict(X_val))

y_val = np.argmax(y_val, axis=1)
y_predict = np.argmax(y_predict, axis=1)

self._data.append({
  'val_microF1Score': f1_score(y_val, y_pred, average='micro'),
  'val_rocauc': roc_auc_score(y_val, y_predict),
  })

print('The f1 score {:7.2f} and auc {:7.2f}  for epoch {} .'.format( logs['val_microF1Score'], logs['val_rocauc'],epoch))
return
def get_data(self):
return self._data

mycallback = MyCustomCallback()`
I am invoking fit with these arguments 

 `history = model.fit(X_train, y_train, epochs=nb_epoch,batch_size=batch_size,validation_split=0.2,validation_data = (X_cv,y_cv),callbacks=[mycallback])`


Could you please suggest any workaround temporary for this as my work is held up due to this

Thank you
