### ISSUE TITLE
Converting Tensor to numpy array

### ISSUE THREAD

**Issue by mnozary** [tensorflow/tensorflow#33046]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.14.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
I already trained a model and I need to load the model in another script (model1) and use it for prediction (df: new data).

I load the model to use it for prediction as follow:
model1 = tf.keras.models.load_model(model_path, custom_objects=None, compile=False)
result = model1(df)

Then how can I extract the numpy array from result Tensor?

if I use "result.numpy()" I will get "AttributeError: 'Normal' object has no attribute 'numpy'"

I need to return numbers to the frontend application.

**Will this change the current api? How?**
I don't know

**Who will benefit with this feature?**
Anyone using TensorFlow for production applications.

**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@mnozary You need to run a session in `TF1.x` in order to access the graph tensor. However, in TF2.0, everything runs eagerly and you can access a numpy array from a tensor as you mentioned above (`result.numpy()`)

So in TF1.x, you need to add the following lines to access `result` numpy array.
```
with tf.Session() as sess:
  sess.run(tf.global_variables_initializer())
  result_output=sess.run(result)
```

Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/2d0e36917906fec79ee4643ae29ee3ba/tf33046_1x.ipynb) with TF1.x. You can also check [gist](https://colab.sandbox.google.com/gist/jvishnuvardhan/2b0ef0d3842bb9e2cfaf064673f95bea/tf33046_keras_loadmodel.ipynb) with TF2.0. Thanks!

I am closing this issue as it was resolved. Please feel free to open the issue if it persists again. Thanks!
