### ISSUE TITLE
Input pipeline guide refactoring

### ISSUE THREAD

**Issue by AlexisBRENON** [tensorflow/tensorflow#33049]
## URL(s) with the issue:

Better performance with tf.data: https://www.tensorflow.org/guide/data_performance

## Description of issue (what needs changing):

Currently, this guide seems to be the main documentation source for `tf.data` usage.
However, the differents steps shown do not seems to be optimal. For example:
* TFRecordDataset usage do not match the actual API (see #33048)
* Usage of `interleave` with TFRecordDataset is redoundant (see [SO post](https://stackoverflow.com/questions/58014123/how-to-improve-data-input-pipeline-performance)).

### Submit a pull request?

No PR intented for the moment as I think this requires some discussion if I missed something or whatever.

**Comment by MarkDaoust** [comment]
Hi @AlexisBRENON,

We don't have anyone currently working on that doc, so if you want to make some updates, you're unlikely to run into any conflicts. It sounds like you're identified some areas for improvement. I would welcome a PR to tensorflow_docs with any fixes.

Ideally the first step would be to convert the markdown file to a notebook:

- I can setup testing for to avoid errors like #33048.
- A notebook can demonstrate concrete improvements.


+ @rohan100jain, @jsimsa FYI.

**Comment by AlexisBRENON** [comment]
Ok, no problem, I'm on it!

I am sorry, I do not understand your first point. What do you mean by "I can setup testing for to avoid errors like #33048"?

I will convert the current file to a notebook, just some questions:

* Is there some guidelines on coding style? As it is a guide/tutorial notebook I would write many comments, but maybe it infringes some coding style rules
* Is there some public repo of TFRecords that I can use for the example (letting the notebook run seemlessly) ?

**Comment by MarkDaoust** [comment]
Thanks Alexis,

> What do you mean by "I can setup testing for to avoid errors like #33048"?

I just mean that since notebooks are executable we run them as tests, and get warnings when they break. That's something I will take care of, If this file gets converted to a notebook. 

> Is there some guidelines on coding style? As it is a guide/tutorial notebook I would write many comments, but maybe it infringes some coding style rules

> Is there some common cells to add at the top/bottom of the notebook (copyright, links to GH, Colab, etc.)

There's some advice in our notebook template:

https://github.com/tensorflow/docs/blob/master/tools/templates/notebook.ipynb
https://colab.sandbox.google.com/github/tensorflow/docs/blob/master/tools/templates/notebook.ipynb

> I would write many comments

Typically if it's more than a line or two of __code comments__ I encourage people to pull the text out into a markdown cell.

>Is there some public repo of TFRecords that I can use for the example (letting the notebook run seemlessly) ?

One simple option here might be to download a few files from the "French Street Name Signs" dataset:

https://storage.googleapis.com/download.tensorflow.org/data/fsns-20160927/train/train-00001-of-00512
https://storage.googleapis.com/download.tensorflow.org/data/fsns-20160927/validation/validation-00000-of-00064
https://storage.googleapis.com/download.tensorflow.org/data/fsns-20160927/test/test-00000-of-00064

I give an example of loading this data in [this section of the tf.data guide](https://www.tensorflow.org/guide/data#consuming_tfrecord_data)

**Comment by AlexisBRENON** [comment]
Thanks for all the advices.

For the moment I mainly copied the base document to a notebook, just updating the code blocks to make them run.

While presenting an example with TFRecord is interesting to showcase a real use case it is hard to use it to effectively show improvements with `prefetch`, `interleave`, `cache` and co. So I tried to build some artificial example which can be crafted to exhibits the performance gains. Take a look at it at the end of [the notebook](https://colab.research.google.com/github/tensorflow/docs/blob/89563f70f1a7306f2d06f8f4e905c2265459a759/site/en/guide/data_performance.ipynb#scrollTo=-XhmoSv9yTiZ), in the `Some ideas` section. It needs some more polish but allow to plot nice charts to show the improvement brang by each operation. What do you think of this kind of artificial example show cases?

**Comment by MarkDaoust** [comment]
It looks like you making good progress on that notebook, please send it as a PR and "@MarkDaoust" me on the thread if I'm not auto assigned as a reviewer. Let's continue the conversation there.

> So I tried to build some artificial example which can be crafted to exhibits the performance gains.

The one caution with artificial examples is that they may not reflect use cases that matter. So we should be sure to make sure that if we use artificial data for this we set it up to reflect real world usage.

> Maybe the data_performance one can reffer the the former as a pre-requisite, and I can concentrate on performance improvements showcases.

Yes.

> plot nice charts

Cool.
