### ISSUE TITLE
Tensorflow Lite  fully integer quantization error :Got tensor of type STRING but expected type FLOAT32

### ISSUE THREAD

**Issue by Eagle223** [tensorflow/tensorflow#33144]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18.04
- TensorFlow installed from (source or binary):binary(pip)
- TensorFlow version (or github SHA if from source):1.14.0

**Provide the text output from tflite_convert**

```
2019-10-08 20:47:37.470691: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-10-08 20:47:37.491949: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2194920000 Hz
2019-10-08 20:47:37.492291: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5600095b3a90 executing computations on platform Host. Devices:
2019-10-08 20:47:37.492321: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
2019-10-08 20:47:39.487818: I tensorflow/core/grappler/devices.cc:60] Number of eligible GPUs (core count >= 8, compute capability >= 0.0): 0 (Note: TensorFlow was not compiled with CUDA support)
2019-10-08 20:47:39.487989: I tensorflow/core/grappler/clusters/single_machine.cc:359] Starting new session
2019-10-08 20:47:41.530815: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:716] Optimization results for grappler item: graph_to_optimize
2019-10-08 20:47:41.576395: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 941 nodes (-544), 973 edges (-544), time = 1222.25598ms.
2019-10-08 20:47:41.576429: I tensorflow/core/grappler/optimizers/meta_optimizer.cc:718]   constant folding: Graph size after: 941 nodes (0), 973 edges (0), time = 214.279ms.
INFO: Initialized TensorFlow Lite runtime.
Traceback (most recent call last):
  File "/home/eagle/PycharmProjects/TFLite/main.py", line 30, in <module>
    quantized_model = converter.convert()
  File "/home/eagle/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 908, in convert
    inference_output_type)
  File "/home/eagle/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/lite.py", line 200, in _calibrate_quantize_model
    inference_output_type, allow_float)
  File "/home/eagle/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/optimize/calibrator.py", line 75, in calibrate_and_quantize
    self._calibrator.FeedTensor(calibration_sample)
  File "/home/eagle/anaconda3/lib/python3.7/site-packages/tensorflow/lite/python/optimize/tensorflow_lite_wrap_calibration_wrapper.py", line 112, in FeedTensor
    return _tensorflow_lite_wrap_calibration_wrapper.CalibrationWrapper_FeedTensor(self, input_value)
ValueError: Cannot set tensor: Got tensor of type STRING but expected type FLOAT32 for input 0, name: input 
```

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
Source Code:

import tensorflow as tf
import os

os.environ["CUDA_VISIBLE_DEVICES"]="-2"

saved_model_dir = "./tmp/resnet/resnet_v2_101_299_frozen.pb"

if __name__ == "__main__":
    input_arrays = ["input"]
    output_arrays = ["output"]

    converter = tf.lite.TFLiteConverter.from_frozen_graph(
        str(saved_model_dir), input_arrays, output_arrays, input_shapes={"input": [1, 299, 299, 3]})

    (resnet_train, _), (_, _) = tf.keras.datasets.cifar10.load_data()
    images = tf.cast(resnet_train[0], tf.float32)/255.0
    resnet_ds = tf.data.Dataset.from_tensor_slices(images).batch(1)

    def representative_data_gen():
        for input_value in resnet_ds.take(100):
            yield [input_value]

    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = representative_data_gen
    converter.target_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.qint8
    converter.inference_output_type = tf.qint8
    quantized_model = converter.convert()
    open("./tmp/resnet/resnet_v2_101_299_frozen_weight_quantized.tflite", "wb").write(quantized_model)

**Comment by suharshs** [comment]
Its seems that your representative dataset is feeding string tensors can you double check the type of input_value and make sure it is the correct type (FLOAT)

**Comment by Ailsorxd** [comment]
I have the same problem - the Tensor sent with input_value is float32.

**Comment by ausk** [comment]
Same issue, solved by feeding `numpy.ndarray` instead.

**Comment by Deadsec69** [comment]
Pass Numpy array instead it will solve the problem in tensorflow versions<2.0
I mean don't use this 
`images = tf.cast(resnet_train[0], tf.float32)/255.0`
use this instead
`images=resnet_train[0]..astype('float32')/255`
It worked for me in a similar case

**Comment by ChiHangChen** [comment]
Same issue but still have no solutions.

**Comment by Deadsec69** [comment]
Can you provide the model I mean ThreeOutputModel_Final.pb

**Comment by ChiHangChen** [comment]
> Can you provide the model I mean ThreeOutputModel_Final.pb

Could it be model's problem? 
[shorturl.at/AFGN3](shorturl.at/AFGN3)

**Comment by hyunsungkim** [comment]
I got the same problem and my problem was that the dtype of the dataset was 'float64', not the 'float32'.
So the problem was solved by casing dtype using .astype.
`
train_images = np.load(dir_data/'train_images.npy')
train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_dataset = train_dataset.shuffle(buffer_size=10000).batch(128)

representative_dataset = tf.data.Dataset.from_tensor_slices(train_images.astype('float32'))
representative_dataset = representative_dataset.shuffle(buffer_size=10000).batch(1)

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
def representative_dataset_gen():
    for i, samples in enumerate(test_dataset.take(1)):
        yield [samples]
        
converter.representative_dataset = representative_dataset_gen
tflite_model_int = converter.convert()
open('./models/model_quant_8b.tflite', 'wb').write(tflite_model_int)
with tf.io.gfile.GFile('./models/model_quant_8b.tflite', 'wb') as f:
    size = f.write(tflite_model_int)


`

**Comment by kodon0** [comment]
# Need to add astype('float32'), otherwise the below wont work!
def representative_dataset():
  for i in range(500):
    yield([x_train[i].reshape(1, 1).astype('float32')])
# Set the optimization flag.
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# Enforce integer only quantization
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
# Provide a representative dataset to ensure we quantize correctly.
converter.representative_dataset = representative_dataset
model_tflite = converter.convert()

# Save the model to disk
open(MODEL_TFLITE, "wb").write(model_tflite)

**Comment by kodon0** [comment]
Needed to add astype('float32') to input, otherwise the below wont work!

`def representative_dataset():
  for i in range(500):
    yield([x_train[i].reshape(1, 1).astype('float32')])
# Set the optimization flag.
converter.optimizations = [tf.lite.Optimize.DEFAULT]
# Enforce integer only quantization
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
# Provide a representative dataset to ensure we quantize correctly.
converter.representative_dataset = representative_dataset
model_tflite = converter.convert()`

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
