### ISSUE TITLE
Link to TensorBoard: Graph Visualization is broken

### ISSUE THREAD

**Issue by abhilashshakti** [tensorflow/tensorflow#33185]
I am reading about tensorboard here: https://www.tensorflow.org/tensorboard/r1/summaries

On this page the link to *TensorBoard: Graph Visualization* is broken. This is the link: https://www.tensorflow.org/tensorboard/guide/graph_viz

**Comment by jvishnuvardhan** [comment]
@abhilashshakti I agree the link is not working. We will update soon. In the mean time you can take a look at the [`TensorBoard: Graph Visualization`](https://www.tensorflow.org/tensorboard). Thanks!

**Comment by MarkDaoust** [comment]
Thanks for the report @abhilashshakti

I've sent a PR with a fix, but remember that you can too. The github edit button makes thios sort of thing easy to fix without ever leaving your browser.

**Comment by abhilashshakti** [comment]
Thanks for looking into the request.

**Comment by abhilashshakti** [comment]
The link https://www.tensorflow.org/tensorboard/guide/graph_viz is still broken

**Comment by wchargin** [comment]
Thanks for the ping! The docs for TensorFlow 1.x, including the one that
you mention (<https://www.tensorflow.org/tensorboard/r1/summaries>), are
now hosted on GitHub rather than tensorflow.org. The tensorflow.org link
now redirects to the new source of truth, where the “TensorBoard: Graph
Visualization” link works:
<https://github.com/tensorflow/tensorboard/blob/master/docs/r1/summaries.md>

**Comment by abhilashshakti** [comment]
Awesome, thanks!
