### ISSUE TITLE
Variable name misspelt in example

### ISSUE THREAD

**Issue by jaicie** [tensorflow/tensorflow#33252]
Loading is spelled loadimg in one example(pose2seg)  And set to False. But loading is expected.  A text search will get you there. Although its in cluster_pose.py.  not a biggy, i know, still, one of those things that may create a problem if someone assumes its set

**Comment by jaicie** [comment]
Its in Pose2Seg's cluster_pose.py      and its     loadimg=False

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
@jaicie 
Please, let us know if any update on this issue. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
