### ISSUE TITLE
tf.feature_column.indicator_column OOM

### ISSUE THREAD

**Issue by former7** [tensorflow/tensorflow#33304]
**Describe the current behavior**
i'm building a CTR model， use tf.feature_column.indicator_column  and tf.feature_column.categorical_column_with_hash_bucket  to make my  categorical feature turn into a multi-hot feature  .  But OOM happens , the error show that API indicator_column generate many one-hot feature , this cause the OOM.   
it seems produce many one-hot [batch_size ,categorical list len, bucket_size] then reduce_sum to multi-hot ,this will cost many memory ,how can i solve this problem?

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
