### ISSUE TITLE
tf.sparse.sparse_dense_matmul can't broadcast as tf.linalg.matmul does.

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#33336]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

tf.sparse.sparse_dense_matmul can't broadcast on the leading dimensions. the following code is an example.

```python
#!/usr/bin/python3

import numpy as np;
import tensorflow as tf;

def main():

    a = tf.sparse.SparseTensor(
        indices = [[0, 0, 1], [0, 0, 2], [0, 1, 2], [0, 1, 3], [0, 2, 1], [0, 2, 3]],
        values = [1., 1., 1., 1., 1., 1.],
        dense_shape = [1, 3, 4]
    ); # a.shape = (1,3,4)
    b = tf.constant(np.random.normal(size = (4, 4, 5)), dtype = tf.float32);
    c = tf.linalg.matmul(tf.sparse.to_dense(a),b); # will be succeed
    c = tf.sparse.sparse_dense_matmul(a,b); # will be fail

if __name__ == "__main__":

    main();
```

**Will this change the current api? How?**

no api need to be changed.

**Who will benefit with this feature?**

user handling sparse matrices will be benefit from the change.

**Any Other info.**

**Comment by familyguy12** [comment]
Hi, I would like to handle this and add the feature. Please let me know if no one is working on it.

**Comment by jvishnuvardhan** [comment]
@familyguy12 Thanks for coming forward to support the development. Please feel free to contribute through PR. Thanks!

**Comment by familyguy12** [comment]
@jvishnuvardhan It seems that this method is working as mentioned in the [documentation](https://www.tensorflow.org/api_docs/python/tf/sparse/sparse_dense_matmul). If I understand correctly, I am supposed to modify the way sparse matrix multiplication works so that it handles the case when the first arg is of rank != 2. Is that right?

**Comment by breadbread1984** [comment]
the tensorflow's traditional matmul does matrix production on the last two dimensions of the two inputs. if the leading dimensions of the two inputs are not equal, matmul may broadcast the small one to the large one if plausible.

**Comment by familyguy12** [comment]
In the code mentioned, `tf.rank(a).eval()` is 3. The documentation says that the sparse multiplication works only for rank-2 tensors. Even in the traditional matmul function, it says that

> If one or both of the matrices contain a lot of zeros, a more efficient multiplication algorithm can be used by setting the corresponding a_is_sparse or b_is_sparse flag to True. These are False by default. This optimization is only available for plain matrices (rank-2 tensors) with datatypes bfloat16 or float32.

So, basically it is not supposed to work for matrices that are sparse, with rank > 2. IMO, it could work as the multiplication is performed on the last two dimensions only. So, I should handle the case where rank != 2 in `sparse_matmul` and perform multiplication only on the last two dimensions, instead of giving a `ValueError`, right?
This is my first contribution to the repository and I apologise for too many questions.

**Comment by breadbread1984** [comment]
the tf.sparse.sparse_dense_matmul can only handle dot product of two 2-rank tensors. the function is too constrained. I would appreciate if dot product between higher rank tensors are supported. besides, I would like to have auto broadcast of sparse_dense_matmul supported. Thx.

**Comment by breadbread1984** [comment]
if sparse_dense_matmul can't support dot product between matrices over rank 2. please add a tf.sparse.map_fn which support tensor slice over sparse tensor. Or some operations are impossible.

**Comment by breadbread1984** [comment]
please support matmul for sparse tensor. pytorch has deepspeed which can handle sparse tensor matmul having rank over 2. implementing sparse attention with tensorflow 2 is impossible without such feature.

**Comment by breadbread1984** [comment]
@familyguy12 any progress?

**Comment by sjtusmartboy** [comment]
@familyguy12 any progress?

**Comment by MPKenning** [comment]
I believe this is an important feature to enable. If I hadn't already programmed so much of my project in Tensorflow, I would have switched to PyTorch.

**Comment by chunduriv** [comment]
I was able to replicate the issue in tf-nightly 2.10.0-dev20220726. Please find the [gist](https://colab.sandbox.google.com/gist/chunduriv/73c6a29c366dc3777924db0781cc7cfc/33336.ipynb) for reference. Thank you.

**Comment by dmitrybaltin** [comment]
I also vote for the feature.
I was unpleasantly surprised when I realized that I couldn’t multiply sparse matrices with a rank > 3 (
By the way, thanks for the info about pytorch. Didn't plan to switch to it, but might have to

**Comment by MPKenning** [comment]
Hello everyone,

There is no native satisfactory solution to performing a matrix multiplication between a SparseTensor and a Tensor and between two SparseTensors. So I made a solution. I think it runs well enough. Everyone is free to use it. I don't demand any but acknowledgement in return.

[I have posted the code on Colab.](https://colab.research.google.com/drive/1BvNLVQFrNv9fGJ2lUogtJHji1D1Y2djB?usp=sharing)

Let me know if you have any bugs or feedback. Perhaps I should set up a GitHub repository for the code.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
