### ISSUE TITLE
Allow to specify the type of the tf.data.Dataset.range function

### ISSUE THREAD

**Issue by AlexisBRENON** [tensorflow/tensorflow#33414]
**System information**
- TensorFlow version (you are using): *v2.0.0*
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

[`tf.data.Dataset.range`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#range) return a dataset of `tf.dtypes.int64` tensors.

It could be nice if the `range` method accept a `dtype` argument (as many other TF methods) to choose the type of the dataset elements.

**Will this change the current api? How?**

This will change the API, adding an accepted `dtype` parameter to the `range` method.

**Who will benefit with this feature?**

Any person that uses the `Dataset.range` method to generate some index to use with `TensorArray.write` which only accept a `tf.dtypes.int32` tensor as its first argument.

**Any Other info.**

It could be possible to update `TensorArray.write` to let it accept `int32` or `int64` (or even `int8`) as its `index` argument.

**Comment by jsimsa** [comment]
This sounds like a useful functionality and I would be happy to review a PR that implements it.

**Comment by ksslng** [comment]
I think this is a good issue for my first PR for TensorFlow. I'll add dtype as an argument and set `tf.dtypes.int64` as the default value.

**Comment by jsimsa** [comment]
Thank you @ksslng . Please add me as a reviewer when you PR is ready.

**Comment by mitsuan** [comment]
Can I contribute to this project?

**Comment by ilhamfp** [comment]
Hi @jsimsa, 

Since this issue has gone silent in a couple of days, I tried to solve it. I have tried adding optional output_types argument and later assigning `self._structure` variable with the corresponding dtypes in [RangeDataset class](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/data/ops/dataset_ops.py#L2891). It worked well with the default `dtypes.int64` but when I tried to change it into `dtypes.int32` it shows:

`
InvalidArgumentError: Data type mismatch at component 0: expected int32 but got int64. [Op:MakeIterator]
`

Did I miss something? Looking into  [_create_iterator](https://github.com/tensorflow/tensorflow/blob/1cf0898dd4331baf93fe77205550f2c2e6c90ee5/tensorflow/python/data/ops/iterator_ops.py#L597), it should be fine since `self._element_spec = dataset.element_spec` right?

[Here's a colab notebook showing the updated code and the problem.](https://colab.research.google.com/drive/1gWdPla-YnER6Z8k4qf2kpca8T096egNW)

**Comment by AlexisBRENON** [comment]
From what I can see, in the `_build_tensor` method, you still pass `dtypes.int64` to the `dtypes` argument (whatever the required `output_type`).
I tried to update using `self.element_spec.dtype` but stumble upon another error:
```
AttributeError: 'RangeDataset' object has no attribute '_structure'
```
Which seems strange as `self._structure` is defined in the `__init__` method...
Maybe you have to investigate a little bit deeper, in the `DatasetSource` class.

**Comment by lsgrep** [comment]
Hi @jsimsa,  this issue has gone silent for a while  .  If it is open, I would like to take on this issue.

**Comment by jsimsa** [comment]
Sounds good. Once you have a working PR, please add me as a reviewer.

**Comment by lsgrep** [comment]
OK, I am on it.

**Comment by lsgrep** [comment]
Hi @jsimsa , I dug a little bit and found that the underlying `RangeDatasetOp` operation does not support `int32`. In fact, it does not parse `output_types` at all, yet.  If I extend `RangeDatasetOp`, then the problem can be solved?  Am I right? Thanks
