### ISSUE TITLE
Simple Audio Recognition validation seems error

### ISSUE THREAD

**Issue by ArtemisZGL** [tensorflow/tensorflow#33495]
my tf version is 1.14.0. I download the code from the newest git for the example Simple Audio Recognition, and run the train.py, but after running several steps, the validation  acc seems not change at all, alse the confusion matrix, all the predict result is the first class. but the training acc is normal, after 8000 steps, about 80%.
![image](https://user-images.githubusercontent.com/31615877/67067057-7f5acb80-f1a7-11e9-852a-ca218bebd8a3.png)
![image](https://user-images.githubusercontent.com/31615877/67067081-939ec880-f1a7-11e9-85d2-f027f4a8749d.png)

**Comment by gadagashwini** [comment]
@ArtemisZGL, Please provide the information asked in template.
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

**Describe the expected behavior**

**Code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by ArtemisZGL** [comment]
i change to tf2.0 and everything is ok
