### ISSUE TITLE
Problem trying to install iOS example

### ISSUE THREAD

**Issue by KevinAyuque** [tensorflow/tensorflow#3354]
I get this problem when running `compile_ios_tensorflow.sh`
 
I tried cloning TensorFlow again, download dependencies and `compile_ios_protobuf.sh ` but the problem persists.

```
Undefined symbols for architecture armv7:
  "tensorflow::OptimizationPassRegistry::Global()", referenced from:
      tensorflow::SimpleGraphExecutionState::InitBaseGraph(tensorflow::BuildGraphOptions const&) in libtensorflow-core-armv7.a(simple_graph_execution_state.o)
      tensorflow::SimpleGraphExecutionState::BuildGraph(tensorflow::BuildGraphOptions const&, std::__1::unique_ptr<tensorflow::SimpleClientGraph, std::__1::default_delete<tensorflow::SimpleClientGraph> >*) in libtensorflow-core-armv7.a(simple_graph_execution_state.o)
  "tensorflow::OptimizationPassRegistry::RunGrouping(tensorflow::OptimizationPassRegistry::Grouping, tensorflow::GraphOptimizationPassOptions const&)", referenced from:
      tensorflow::SimpleGraphExecutionState::InitBaseGraph(tensorflow::BuildGraphOptions const&) in libtensorflow-core-armv7.a(simple_graph_execution_state.o)
      tensorflow::SimpleGraphExecutionState::BuildGraph(tensorflow::BuildGraphOptions const&, std::__1::unique_ptr<tensorflow::SimpleClientGraph, std::__1::default_delete<tensorflow::SimpleClientGraph> >*) in libtensorflow-core-armv7.a(simple_graph_execution_state.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/Users/Kevin/Developer/tensorflow/tensorflow/contrib/makefile/gen/bin/benchmark] Error 1
+ '[' 2 -ne 0 ']'
+ echo 'armv7 compilation failed.'
armv7 compilation failed.
+ exit 1

```

**Comment by jmchen-g** [comment]
@petewarden Could you take a look at this please?

**Comment by andreesteva** [comment]
I'm getting the same error

**Comment by sahil912** [comment]
I am getting the same error too..

**Comment by michaellee1** [comment]
Same error found here

**Comment by KevinAyuque** [comment]
Could this be due to the Xcode 8 beta? I have it installed and I'm not sure if it affects the command line tools.

**Comment by JulianBlin** [comment]
No, it's not linked to Xcode 8 beta. I faced the same xith Xcode 7.3
If you want to build the library, I'd advise you to checkout an older commit (e.g. 7520953ac6ee65f7cca8ab3f124fb2cb1629918e ) and then run build_all_ios.sh , it worked for me. But this issue is still open because the compilation fails with the current master tensorflow.

**Comment by petewarden** [comment]
I just checked in PR #3382 which fixes the immediate problem, and also makes it less likely that it will happen in the future. The summary is that we used to have an explicit list of files that were needed for the core library, and this was fragile because individual .cc files are often added, breaking the build. To make things more robust, I've switched over to a wildcard-based approach together with a blacklist of excluded files, which mirrors the Bazel build rule more closely and so should break less often.

Please give this a try if you get a chance and let me know how it goes.

**Comment by sahil912** [comment]
It works great now. 
![img_5043](https://cloud.githubusercontent.com/assets/7187949/16957491/26dc3e48-4dfa-11e6-881a-5b623c6227bd.jpg)

**Comment by KevinAyuque** [comment]
It works for me now as well! thanks!

**Comment by chrisrn** [comment]
I have installed everything correctly and I also ran the provided inception graph from image-net. I created my own graph which gives great predictions using label_image.py but all predictions are wrong using xcode simulator or camera...
