### ISSUE TITLE
model.losses return null ?

### ISSUE THREAD

**Issue by Jessespace** [tensorflow/tensorflow#33556]
I want to use regularization loss to improve model accuracy, so I follow the official tutorial, but model.losses return **[]**, and got "**ValueError: inputs must be a list of at least one Tensor/IndexedSlices with the same dtype and shape**", Is there something wrong and how to fix it?
```
def train_step(images, labels):
    with tf.GradientTape() as tape:
        predictions = model(images, training=True)
        pred_loss = loss_object(labels, predictions)
        print("model.losses:", model.losses)  
        regularization_loss = tf.math.add_n(model.losses)
        total_loss = pred_loss + regularization_loss
    gradients = tape.gradient(total_loss, model.trainable_variables)
    optimizer.apply_gradients(zip(gradients, model.trainable_variables))
```

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by srihari-humbarwadi** [comment]
Did you set the `kernel_regularizer` arg in the respective layers while building the model?

**Comment by Jessespace** [comment]
> activation

I used your method and can really solve the problem above.But still have 2 questions:
1) When I use **tf.keras.applications.MobileNetV2**, how to add regularization loss?
```python
base_model = tf.keras.applications.MobileNetV2(
    input_shape=IMG_SHAPE,
    include_top=False,
    weights='imagenet'
)
base_model.trainable = False
maxpool_layer = tf.keras.layers.GlobalMaxPooling2D()
prediction_layer = tf.keras.layers.Dense(3, activation='sigmoid')
model = tf.keras.Sequential([
    base_model,
    maxpool_layer,
    prediction_layer
])```
2) Why is it defined in this form? I only need to add a regular term to the loss function. Why can't I call it as simple as pytorch or mxnet? It's so complicated and confusing.

**Comment by rmothukuru** [comment]
Closing the issue as it has been resolved by @srihari-humbarwadi's comment. You can raise new issue for other queries. Thanks!
