### ISSUE TITLE
tf-lite 2.0 python

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#33626]
I'd like to have TensorFlow-lite python module. So is it and how to build from source?

**Comment by oanush** [comment]
@peter197321 ,
Can you please refer this [link](https://www.tensorflow.org/lite/guide/python) and let us know if it was helpful ?Thanks!

**Comment by peter197321** [comment]
I would like to know how to prepare (build from source) such a lean wheel
*tflite_runtime*.whl*
A page you shared is more on user experience-oriented information - am I
right?

**Comment by jdduke** [comment]
@gargn should be able to advise.

**Comment by gargn** [comment]
This [link](https://www.tensorflow.org/install/source) has information on how to build the TensorFlow pip from source.

**Comment by peter197321** [comment]
Ok. How about tf-lite only for inference but not full fledged tf?

Dne pá 25. 10. 2019 22:52 uživatel Nupur Garg <notifications@github.com>
napsal:

**Comment by fdasilva59** [comment]
Hi,

I agree with @peter197321 : having more detailed instructions on how to build Tensorflow Lite Runtimes would be helpfull (Adding official Tensorflow support to Jetson Nano in addition to the Raspberry Pi would also be great, but that's another topic)

I have recently built with success TF2.0 for Nvidia Jetson Nano (aarch64 with python 3.6) . This allows to use tf.lite API but having to load the whole tensorflow library is rather heavy on the memory.

Thus I would also like to have the TF 2.0 Lite Runtime for Python 3.6 . As there is [no wheel package provided for python 3.6 on aarch64](https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter), I tried to built (natively or via cross compilation) TF 2.0 Lite by myself but without success so far. In order to do so I am using the scripts from this directory: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package), but unfortunately apart from the README, there is no specific Tensorflow documentation describing how to build tensorflow lite runtimes

When building natively, there seems to be a first issue with "subprocess.check_call(["make" ...]) ,at first sight this looks like some kind of incompatibility with a  Python 3.6 module

I tried to replace in setup.py the "subprocess.check_call(["make" ...]) calls by "os.system('make ...')], which allows to bypass the 1st issue : the compilation apparently starts well but it then fails with in the distutils lib with a "TypeError: must be str, not int" (More details on https://devtalk.nvidia.com/default/topic/1065109/jetson-nano/building-tensorflow-2-0-and-tensorflow-lite-python-runtime/post/5396093/#5396093 )

**Comment by gargn** [comment]
@dmitriykovalev might be able to provide additional help

**Comment by terryheo** [comment]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/pip_package
This page has the way to build Python wheel of *tflite_runtime*.whl*

**Comment by ymodak** [comment]
You can also see https://pypi.org/project/tflite/#files
