### ISSUE TITLE
Some errors when running keras-yolo3 as a child process 

### ISSUE THREAD

**Issue by 050214221** [tensorflow/tensorflow#33664]
Hello! I am confronted with some errors and don't know how to solve them When running keras-yolo3 module as a child process. By setting breakpoints, I found erors appearing at the statement in yolo.py "sout_boxes, out_scores, out_classes = self.sess()". Concrete errors are shown as follows:
1 [tensorflow/core/grappler/clusters/utils.cc:82] Failed to get device properties, error code: 3
2 Python failed to enqueue async from host to device: cuda _error_not_initialized;
GPU dst: …… ; host src: …… ;size: ……

I am looking forward to getting replys from warm-hearted you, thanks!

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
@050214221 

Any update please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
