### ISSUE TITLE
How to replace contrib.rnn.stack_bidirectional_dynamic_rnn in tf2.0

### ISSUE THREAD

**Issue by LJXLJXLJX** [tensorflow/tensorflow#33683]
I use contrib.rnn.stack_bidirectional_dynamic_rnn in my code, but I upgrade my tf to 2.0 now, how to replace it?

**Comment by qlzh727** [comment]
So there are two ways to build bidirectional RNN in tf 2.0 with keras layers, and the existing stack_bidirectional_dynamic_rnn() is using the second approach. There isn't any right/wrong between those 2 approaches, the major difference is that whether the cell state will be feed to next layer as initial states.

1. Does not feed cell states to next layer as initial states, note that forward and backward cellls are just simpleRNN cells and you can replace them with LSTM or GRU cells.
```python
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers

batch = 32
timestep = 10
input_shape = 8

cell_size = 4
num_layers = 6
cells = [layers.SimpleRNNCell(cell_size) for _ in range(num_layers)]

model = tf.keras.Sequential()

model.add(tf.keras.Input(shape=(None, input_shape)))
model.add(layers.Bidirectional(
    layers.RNN(cells)
))

result = model.predict(np.ones(shape=(batch, timestep, input_shape), dtype=np.float32))
print(result)

```

2. Using the previous layers end state as the initial state for the next layer. Since now we need to probably pass the states between layers, we will need to use functional API, rather than just the Sequential model as the example above.

```python
import tensorflow as tf
import numpy as np
from tensorflow.keras import layers

batch = 32
timestep = 10
input_shape = 8

cell_size = 4
num_layers = 6
# cells = [layers.SimpleRNNCell(cell_size) for _ in range(num_layers)]

inputs = tf.keras.Input(shape=(None, input_shape))
output = inputs
states = None
for _ in range(num_layers):
  result = layers.Bidirectional(
      layers.RNN(layers.SimpleRNNCell(cell_size),
                 return_state=True, return_sequences=True))(output, states)
  output, states = result[0], result[1:]
# If you only care about the output for the last time step, you can just slide it here.
output = output[:, -1, :]

model = tf.keras.Model(inputs, output)

result = model.predict(np.ones(shape=(batch, timestep, input_shape), dtype=np.float32))
print(result)
```

Hope this resolve your question.
