### ISSUE TITLE
Infinite loop with generators wrapping a dataset in tf.function

### ISSUE THREAD

**Issue by omoindrot** [tensorflow/tensorflow#33724]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): `v2.0.0-rc2-26-g64c3d38 2.0.0`
- Python version: 3.7.4
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0 / 7.6.3
- GPU model and memory: TITAN Xp, 12196MiB

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with: 1. TF 1.0: `python -c "import
tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"` 2. TF 2.0: `python -c
"import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**

My use case was to use `tqdm` to track progress on a training loop over a `tf.data.Dataset`:

```python
@tf.function
def train_one_epoch(model, dataset):
    for x in tqdm(dataset):
        train_step(model, x)
```

However, when the function `train_one_epoch` is wrapped in a `tf.function`, the AutoGraph is stuck in an infinite loop. 

**Describe the expected behavior**

The expected behavior would be that using `tf.function` results in the same behavior than the eager mode.

The current issue is that AutoGraph doesn't recognize `tqdm(dataset)` as a `tf.data.Dataset` (which is normal). However, iterating infinitely over the dataset in AutoGraph is weird and shouldn't happen. Maybe it should give an exception.

Maybe the easiest fix would be to prevent `dataset.__iter__` being called inside `tf.function` if it is not in a loop.  
So `for x in dataset` would be fine, but `for x in tqdm(dataset)` wouldn't.

**Code to reproduce the issue**

```python
import tensorflow as tf


class Iterable():
    def __init__(self, iterable):
        self.iterable = iterable

    def __iter__(self):
        for obj in self.iterable:
            yield obj

@tf.function
def f(dataset):
    for x in Iterable(dataset):
        print(x)

dataset = tf.data.Dataset.range(5)
f(dataset)
```

The minimal `Iterable` class can be replaced by `tqdm` (`from tqdm import tqdm`), and this should yield the same results.

**Other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

Without the `@tf.function`, the wrapped dataset `Iterable(dataset)` is iterated over in eager mode:
```
tf.Tensor(0, shape=(), dtype=int64)
tf.Tensor(1, shape=(), dtype=int64)
tf.Tensor(2, shape=(), dtype=int64)
tf.Tensor(3, shape=(), dtype=int64)
tf.Tensor(4, shape=(), dtype=int64)
```

With the `@tf.function`, the AutoGraph mode doesn't recognize the wrapped `Iterable(dataset)` as a `tf.data.Dataset`, so it tries to iterate over it in python to trace the graph. However, it looks like the `Iterable(dataset).__iter__` infinitely yields a next element named `IteratorGetNext`.

This results in an infinite iteration over the dataset:
```
Tensor("IteratorGetNext:0", shape=(), dtype=int64)
Tensor("IteratorGetNext_1:0", shape=(), dtype=int64)
Tensor("IteratorGetNext_2:0", shape=(), dtype=int64)
Tensor("IteratorGetNext_3:0", shape=(), dtype=int64)
Tensor("IteratorGetNext_4:0", shape=(), dtype=int64)
Tensor("IteratorGetNext_5:0", shape=(), dtype=int64)
Tensor("IteratorGetNext_6:0", shape=(), dtype=int64)
Tensor("IteratorGetNext_7:0", shape=(), dtype=int64)
...
```

**Comment by mdanatg** [comment]
Indeed, AutoGraph does not recognize `Iterator` or the generators executed by `tqdm`. I'll explain in more detail below, but in general the objects are not recognized because they are not subclasses of a dataset or a dataset iterator.

AutoGraph only transforms objects of types it recognizes - everything else is executed in Python, at function tracing time. For this reason, when running the code above, it's as if you ran it without AutoGraph (try executing `@tf.function(autograph=False)`, it should behave identically). To better understand this, have a look at the [dispatch logic for `for` loops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/operators/control_flow.py#L331
). Since `Iterator` is not an instance of any of the classes listed there, AutoGraph reverts to running the for loop in Python. In Python, it will cycle infinitely because the `Tensor` objects that the hidden `Dataset` iterator returns evaluate to True. `next(iter(Dataset))` never returns `StopIteration` in graph mode - it can't, because it doesn't know how much data there is at graph construction.

You might wonder why AutoGraph doesn't detect that the for loop inside `Iterator` which does use a Dataset. The answer is because AutoGraph doesn't touch generators, however [the warning it generates is silenced by default](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/autograph/core/unsupported_features_checker.py#L40). I think we'll need to make that warning more obvious.

Now, AutoGraph could detect that a `for` loop is trying to iterate over a generator and disallow it in graph mode. However, that could break legitimate uses of generators (e.g. such as those used by Keras), but again, it looks like a warning would be useful.

Separately from all that, `tqdm` itself contains console output logic and other operations that are highly dependent on the Python runtime and which are not very compatible with TF graphs. So it would be tricky to run in graph mode regardless (though it could be possible to create a more graph-friendly version). When running training loops inside `tf.function`, you can currently only use summaries and `tf.print` and tensorboard to monitor the training progress.

I think adding a graph-compatible `tqdm` (one that uses TF Iterators and `tf.print`) would be a useful API to build as well.

**Comment by mdanatg** [comment]
There is now a verification in autograph that outputs a warning in situations such as this. We could add a verification that looks specifically for tqdm, but that won't work work the custom generator in the OP so it would be of limited help.

Here is an alternative that might be useful for adding a progress bar to a dataset - it modifies a dataset to print tqdm messages whenever it is being iterated, using tf.py_function:

```
def tf_tqdm(ds):

  # Suppress printing the initial status message - it creates extra newlines, for some reason.
  bar = tqdm.tqdm(file=io.StringIO())

  def advance_tqdm(e):
    def fn():
      bar.update(1)
      # Print the status update manually.
      print('\r', end='')
      print(repr(bar), end='')
    tf.py_function(fn, [], [])
    return e

  return ds.map(advance_tqdm)


@tf.function
def f(ds):
  for x in tf_tqdm(ds):
    pass

ds = tf.data.Dataset.from_tensor_slices(tf.range(3))
f(ds)
```

Another similar alternative is to use `Dataset.from_generator` and supply it with a custom generator that itself includes tqdm. This will work whenever you are constructing the dataset from a Python object (it will not work when using built-in datasets like TFRecordDataset, though):

```
data = tf.range(3)

def f():
  bar = tqdm.tqdm(file=io.StringIO())
  for i in data:
    bar.update(1)
    # Print the status update manually.
    print('\r', end='')
    print(repr(bar), end='')
    yield i

ds = tf.data.Dataset.from_generator(f, tf.int32)


@tf.function
def f():
  for x in ds:
    pass

f()
```
