### ISSUE TITLE
AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_images'

### ISSUE THREAD

**Issue by amd-lthakur** [tensorflow/tensorflow#33736]
I am trying to load pspnet pretrained model and encountered the said error.
AttributeError: module 'tensorflow_core._api.v2.image' has no attribute 'resize_images'
Could please guide me how resolve this?
Config: Windows10
using Juyter notebook
tensorflow version: 2.0.0
code source : https://github.com/divamgupta/image-segmentation-keras
The code used to reproduce the issue is:
import keras_segmentation
model = keras_segmentation.pretrained.pspnet_101_voc12()

**Comment by ymodak** [comment]
This issue is not on TF side but more on ```keras-segmentation``` module as mentioned in the template.
As mentioned in the prerequisites you have to install keras 2.0 version to make it work.
See https://github.com/divamgupta/image-segmentation-keras#prerequisites
Installing newer keras version (above 2.0) fails to load the model.
For further question https://github.com/divamgupta/image-segmentation-keras/issues github repo can be a good platform.
