### ISSUE TITLE
LSTMCell name is ignored in trainable_variables when wrapped in keras.layers.RNN

### ISSUE THREAD

**Issue by EgorLakomkin** [tensorflow/tensorflow#33776]
I created a model with several LSTMCell cells, wrapped in keras.layers.RNN.
When I print trainable_variables, cell names are ignored, which results into duplicate variable names (several same recurrent_kernel/etc), which confuses Tensorboard for example.

Collab notebook to reproduce: https://colab.research.google.com/drive/11W6ntLFGj4gqh5sS09CeVgb0LMNb_Fiu
Environment: tensorflow 2 release

**Comment by oanush** [comment]
Issue replicating for the given code - TF-2.0.

**Comment by bono1567** [comment]
I would like to work on this one.

**Comment by qlzh727** [comment]
Thanks for reporting this issue. I think this is a historical issue since the we directly invoke cell.call() method rather than cell.__call__(). This cause the name scope in the __call__ to be ignored, which result into the variable name doesn't have the prefix. 

The fix might need some special care since it affects the existing saved model (since the variable name changed, as well as the ops under the cell, they will now have a prefix of the cell's name). For anyone who want to try a fix, I would suggest to make sure the save model and checkpoint is explicitly verified.

**Comment by EgorLakomkin** [comment]
@qlzh727 thank you! Maybe you have an idea of a simple workaround (not sure if calling __call__ explicitly for each cell would help) until the proper fix is done?

**Comment by qlzh727** [comment]
The weights of the layer is initialized in build(), so you have to build the layer first with proper input_shape, so that it can init the weights with proper shape. then set_weights() should work fine.

**Comment by EgorLakomkin** [comment]
I tried to build each cell, but the names are still duplicated
