### ISSUE TITLE
Which ssd model to use to generate the smallest tflite for a lite>experimental>micro project?

### ISSUE THREAD

**Issue by riccardobrue** [tensorflow/tensorflow#33797]
Hi, I have asked [this](https://stackoverflow.com/questions/58595004/how-to-obtain-a-small-tflite-file) question on stack overflow and I am going to ask the same thing here; Furthermore I would like to know if the lite>experimental>micro project is still under developing; In particular:

- I cannot execute the MUL operation, will it be ever available for the micro sub-project?
- If not, can I rely on previous ssd mobilenets (v1 or v2)  in order to execute an object-detection?
- Which ssd model do you suggest to generate the smallest object detection model?
- And more important, I would ask you if there is something that I have missed on the documentation/process that I have done (more details on the posted question) in order to generate the .cc file to be run on the microcontroller.

Thank you for your attention.

**Comment by rockyrhodes** [comment]
The micro project is still under development and ops are still being added.  The MUL op hasn't been added yet, but it is on the todo list.  Maybe @MeghnaNatraj can offer some advice with respect to SSD models.

**Comment by riccardobrue** [comment]
> The micro project is still under development and ops are still being added. The MUL op hasn't been added yet, but it is on the todo list. Maybe @MeghnaNatraj can offer some advice with respect to SSD models.

Thank you for your reply.

**Comment by MeghnaNatraj** [comment]
The [TensorFlow Object detection model zoo](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/detection_model_zoo.md) has many pre-trained models and is the best resource to get started with SSD models. Most users pick a pre-trained model and use transfer learning to customize it (similar to your use-case). Unfortunately, even the smallest ones (mobilenet V1/V2/V3 models) target mobile devices (few MBs) and not embedded. So currently, there are 3 options:

1. Experimenting with the smallest pre-trained mobilenet models - (eg: ssd_mobilenet_v1_0.75_depth_quantized_coco, ssd_mobilenet_v1_ppn_coco, ssd_mobilenet_v2_quantized_coco, ssdlite_mobilenet_v2_coco, ssd_mobilenet_v3_small_coco)
Have you tried using the v1 and v2 models and do any of them fit your memory constraints? (Will discuss v3 in the next section)
2. [Training your own model ](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/defining_your_own_model.md) or using [embedded mobilenet config](https://github.com/tensorflow/models/blob/master/research/object_detection/models/embedded_ssd_mobilenet_v1_feature_extractor.py). Unfortunately, this would require a lot of effort.

For ssd_mobilenet_v3_small_coco, I [visualized the model.tflite file ](https://www.tensorflow.org/lite/guide/faq#how_do_i_inspect_a_tflite_file) to check all the ops which are required. They are listed below:
```
index	builtin_code	  custom_code	version
0	ADD	          None	        1
1	AVERAGE_POOL_2D	  None	        1
2	CONCATENATION     None	        1
3	CONV_2D	          None	        1
4	DEPTHWISE_CONV_2D None	        1
5	DEQUANTIZE	  None	        1
6	MUL	          None	        1
7	RESHAPE	          None	        1
8	HARD_SWISH	  None	        1
```
When we [compare this to the list of currently supported ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/micro/kernels/all_ops_resolver.cc), we can see that the unsupported ops are: CONCATENATION (work in progress), MUL (work in progress) and HARD_SWISH (will be prioritized).

Now back to your questions:
1. I cannot execute the MUL operation, will it be ever available for the micro sub-project? 
> It's a work in progress, we'll update this thread once it's complete. #TODO
2. If not, can I rely on previous ssd mobilenets (v1 or v2) in order to execute an object-detection? 
> Yes!
3. Which ssd model do you suggest to generate the smallest object detection model? 
> Answered above in 1) Experimenting with the smallest .....
4. And more important, I would ask you if there is something that I have missed on the documentation/process that I have done (more details on the posted question) in order to generate the .cc file to be run on the micro controller. 
> There are no issues in your process, however, you can try visualizing/inspecting the tflite model to check what ops are required and ensure they are all supported before converting them. This can save your time as you can ensure all ops are supported at once vs trying to convert it to a cc file and finding a new unsupported op error every time. eg: Here, the conversion failed for one op (eg: MUL), and you would've missed that the model also requires 2 additional unsupported ops.

**Comment by MeghnaNatraj** [comment]
CONCATENATION and MUL have been implemented. Could you confirm if you're still blocked on this issue and require the HARD_SWISH op. It's a high priority, but currently we cannot provide an estimated completion date. If you could use another activation function until this is implemented, it could solve the issue temporarily.

**Comment by MeghnaNatraj** [comment]
Received no response; Marking issue as closed.

**Comment by alisonwh** [comment]
Hi, MeghnaNatraj, I have a question related to this issue. I am working on object detection using TFLite micro + SSD model. For ssd_mobilenet_v3_small_coco, the last operator is TFLite_Detection_PostProcess. I couldn't find the support for this operator in TFLite micro. Could you give me some guide?

**Comment by petewarden** [comment]
Hi @alisonwh! We do have support for this operation in TFLite Micro:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/detection_postprocess.cc

We haven't yet created an example, documentation, or end to end test cases for it yet though, but hopefully you should be able to use it by just exporting your model and loading it into the interpreter. Drop us an email at micro@tensorflow.org if you do hit problems.

**Comment by alisonwh** [comment]
@petewarden Thank you very much for your reply. I will try to use this operator and send you an email if I meet problems.

**Comment by alisonwh** [comment]
@petewarden I tried to send an email to micro@tensorflow.org, but it failed with the information that "We're writing to let you know that the group you tried to contact (micro) may not exist, or you may not have permission to post messages to the group. "

**Comment by alisonwh** [comment]
@petewarden My question is as below:

I am working on object detection based on Arm Cortex-M7 + TFLite Micro. The model I used is SSD mobilenet v1 quantized.

Using https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/detection_postprocess.cc, the previous issue about operator DETECTION_POSTPROCESS is not registered has been fixed. Thanks for your help.

Now the application runs to interpreter invoke function. It fails at operator LOGISTIC invoke function. The reason is the input tensor type is UINT8. It is not supported yet as below.

// TODO(b/141211002): Also support other data types once we have supported
    // temporary tensors in TFLM.
    TF_LITE_KERNEL_LOG(context, "Input %s, output %s not supported.",
                       TfLiteTypeGetName(input->type),
                       TfLiteTypeGetName(output->type));

May I ask when will you add this support? Or do you have some suggestions for this problem?

**Comment by furknclk** [comment]
> @petewarden My question is as below:
> 
> I am working on object detection based on Arm Cortex-M7 + TFLite Micro. The model I used is SSD mobilenet v1 quantized.
> 
> Using https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/kernels/detection_postprocess.cc, the previous issue about operator DETECTION_POSTPROCESS is not registered has been fixed. Thanks for your help.
> 
> Now the application runs to interpreter invoke function. It fails at operator LOGISTIC invoke function. The reason is the input tensor type is UINT8. It is not supported yet as below.
> 
> // TODO(b/141211002): Also support other data types once we have supported
> // temporary tensors in TFLM.
> TF_LITE_KERNEL_LOG(context, "Input %s, output %s not supported.",
> TfLiteTypeGetName(input->type),
> TfLiteTypeGetName(output->type));
> 
> May I ask when will you add this support? Or do you have some suggestions for this problem?

Hello. I am also working on ssd with stm32. Have you solve the problem ?
