### ISSUE TITLE
DenseFeatures always returns float32

### ISSUE THREAD

**Issue by piyueh** [tensorflow/tensorflow#33793]
(https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently, a call to `tf.keras.layers.DenseFeatures` returns `float32` no matter what.
It doesn't respect its own `dtype` (e.g., `DenseFeatures(..., dtype=tf.float64)`
is not working). Using `tf.keras.backend.set_floatx('float64')` does not change
the behavior, either. It will be nice if a user can choose to return `float64`.
Or at least respect the setting of `tf.keras.backend.set_floatx(...)`.

This behavior is not mentioned in the API documentation:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/DenseFeatures

But it is mentioned in the docstring of `DenseFeatures.call`:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/feature_column/dense_features.py#L119-L122

Here's a simple sample code:
```
import numpy
import tensorflow as tf

numpy.set_printoptions(15)

columns = [
    tf.feature_column.numeric_column("a", dtype=tf.float64),
    tf.feature_column.numeric_column("b", dtype=tf.float64)
]

layer = tf.keras.layers.DenseFeatures(columns, dtype=tf.float64)

data = {
    "a": tf.constant([1./3.], dtype=tf.float64),
    "b": tf.constant([numpy.pi], dtype=tf.float64)
}

print("\n"+"-"*80)
print("data[\"a\"]:", data["a"])
print("data[\"b\"]:", data["b"])
print("layer(data):", layer(data))
print("-"*80)
```

And the output:
```
--------------------------------------------------------------------------------
data["a"]: tf.Tensor([0.333333333333333], shape=(1,), dtype=float64)
data["b"]: tf.Tensor([3.141592653589793], shape=(1,), dtype=float64)
layer(data): tf.Tensor([[0.33333334 3.1415927 ]], shape=(1, 2), dtype=float32)
--------------------------------------------------------------------------------
```

**Will this change the current api? How?**

No.

**Who will benefit with this feature?**

Not sure. But who ever uses `tf.keras.backend.set_floatx('float64')` will
probably be happy.

**Any Other info.**

N/A

**Comment by gowthamkpr** [comment]
@piyueh Can you be clear about how setting float32 to float64 helps the community. Thanks!

**Comment by pandrey-fr** [comment]
@gowthamkpr To back up this issue: depending on the application context, a user may want to use float64 to enable handling larger or more precise values than with float32. Alternatively, one may want to use float16 to limit the memory cost of their model.

At any rate, the keras API is built to support the specification of an alternative dtype for float layers. The fact that the `DenseFeatures` layer exposes this API trait but does not actually implement it is indeed an issue, since it is basically a violation of the `tf.keras.layers.Layer` common specification (thus notably enfringing the Liskov substitution principle).

**Comment by pandrey-fr** [comment]
To fix this, one needs to alter source code in [this folder](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/python/feature_column) to ensure proper dtypes are passed to variable constructors (whose methods seem to be doted with the necessary parameters; so the API probably does not need to change, some arguments just need to be explicitly passed instead of assuming that the layer's dtype is always float32).

If nobody else does in the upcoming days, I will try to submit a PR this week-end.

**Comment by gowthamkpr** [comment]
Makes sense @pandrey-fr. Thanks for detailed explanation.

**Comment by pandrey-fr** [comment]
My pleasure :)
I have not had time to start working on a fix yet but hopefully I will submit something this week (unless somebody else does it first!).

**Comment by pavithrasv** [comment]
Assigning to @tanzhenyu who owns this area.

**Comment by tanzhenyu** [comment]
I think the bottleneck here is that EmbeddingColumn is always with float32, which seems to be a legacy feature column issue, and we don't want feature column rely on keras backend. Moving forward, we're deprecating DenseFeatures or any other feature column related things and it's better to use [preprocessing layers](https://github.com/tensorflow/community/pull/188)
Closing this issue for now. If PR is desired, please open one and I can help review it.
