### ISSUE TITLE
Compressed input?

### ISSUE THREAD

**Issue by skearnes** [tensorflow/tensorflow#338]
Is there any support for reading/writing compressed input files, e.g. with gzip? I would like to use the "standard" file format, but the uncompressed TFRecords files I am generating are huge for my datasets.

**Comment by vincentvanhoucke** [comment]
None yet. gzipping will unlikely result in significant compression due to the high entropy of the weights, but we're very interested in enabling compressed model representations at rest in general, especially for models that have to fit on mobile devices. I'll leave this bug open to track the feature request.

**Comment by delip** [comment]
OP: have you tried using L1 regularization? How big are your model files
after that?

**Comment by skearnes** [comment]
@vincentvanhoucke I've got a TFRecords file with ~9k Example protos that went from 115M to 1.7M after gzip. My input Features are (pretty sparse) float arrays, so I'm not surprised that compression helps a lot.

@delip I'm focusing here on the input data, not the model checkpoints. The checkpoints do compress somewhat, but limiting the number and frequency of checkpoints is fine for now.

**Comment by delip** [comment]
@skearnes sorry, not sure why I talked about model files :8ball: 

+1 for this request. I would suggest using lzo for compression as opposed to gzip, as the former allows compressed files to be splittable. There's a reference use of lzo with protobufs in Twitter's [elephantbird](https://github.com/twitter/elephant-bird) library.

**Comment by vincentvanhoucke** [comment]
I completely misunderstood your point, for some reason I assumed you meant checkpoints. FR stands, I agree that it might make a lot of sense to support something like that.

**Comment by llhe** [comment]
@vincentvanhoucke I guess @skearnes meaning compressing the training data instead of the checkpoints. In some cases, the input feature vectors are extremely sparse and compression will reduce the IO dramatically. So I'm also wondering whether the compression of TFRecord file will be supported in the future?

**Comment by llhe** [comment]
@delip Snappy is another choice: https://github.com/google/snappy

**Comment by NathanHowell** [comment]
Looks like support for zlib compressed TFRecords was added in 90bad51f97cc32dc9bc8e2ffb3e81b65cec37dfb

**Comment by tatatodd** [comment]
Indeed 90bad51f97cc32dc9bc8e2ffb3e81b65cec37dfb added support for zlib compressed TFRecords.  Closing this issue out.

**Comment by Remi-Coulom** [comment]
Is it possible to read compressed raw files?
