### ISSUE TITLE
Pull Requests: Status information should be available

### ISSUE THREAD

**Issue by petewarden** [tensorflow/tensorflow#33801]
There is currently no way to tell who needs to take the next action on a pull request, or what state a PR is in. This delays external contributions and frustrates developers. Here is the sort of information that is needed to enable efficient contributions:

 - Who needs to take action? Is it the contributor, a member of the gtech team, or a Google TensorFlow engineer? This should be clearly and publicly visible on the request, so that stakeholders can communicate with the responsible individual.

 - Where is the request in the approval workflow? We'll need a map of the stages involved, and a way to map the current state to each node in the graph.

There are other pieces of information that would be nice to have, but these are essential to shepherding contributions through our process.

/cc @jenselofsson @freddan80

**Comment by SuryanarayanaY** [comment]
Hi @petewarden ,
Your request regarding PRs: 

- `Who needs to take action? Is it the contributor, a member of the gtech team, or a Google TensorFlow engineer? This should be clearly and publicly visible on the request, so that stakeholders can communicate with the responsible individual.`

It has already taken care and reflecting in the PRs [link](https://github.com/tensorflow/tensorflow/pulls).Could you please check and confirm?

Regarding your second point on PR workflow and Map of stages:

- `Where is the request in the approval workflow? We'll need a map of the stages involved, and a way to map the current state to each node in the graph.`

The workflow process also reflecting for each PR.For the map of the stages involved in PR process, a PR #[57564](https://github.com/tensorflow/tensorflow/pull/57564) already raised against your Issue #[33802](https://github.com/tensorflow/tensorflow/issues/33802) . Could you please go through the both issues and confirm all the requirements you put forward has been taken care of?

If anything else missing as per the request raised by you please let us know.

Thankyou!
