### ISSUE TITLE
the relationship among optimize_for_inference.py quantize_graph.py graph_transforms

### ISSUE THREAD

**Issue by yyf1986** [tensorflow/tensorflow#33813]
Is graph_transforms  tool the newest tool to optimize and quantize for pb.
when I find tf < 1.11,has quantize_graph.py.

**Comment by gadagashwini** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
