### ISSUE TITLE
tf.image.ssim_multiscale does not work in tf-2.0.0

### ISSUE THREAD

**Issue by AravindGanesh** [tensorflow/tensorflow#33840]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution: Linux Ubuntu 16.04
- TensorFlow installed from: binary (pip)
- TensorFlow version: `2.0.0`
- Python version: `3.5.2`
- CUDA version: `10.1`
- GPU model and memory: GTX 1060, 6GB

``` python
# example image batches
video1 = tf.random.uniform(shape=[8, 64, 64, 1], minval=0, maxval=1)
video2 = tf.random.uniform(shape=[8, 64, 64, 1], minval=0, maxval=1)
```
ssim works fine but when I use the multiscale ssim, I am getting the following error message. What am I doing wrong? How do I fix this? 

**SSIM**
``` python
ssim_score = tf.image.ssim(img1=video1, img2=video1, max_val=1.0)
print(ssim_score) # tf.Tensor([1. 1. 1. 1. 1. 1. 1. 1.], shape=(8,), dtype=float32)
```

**MS-SSIM**
``` python
ms_ssim_score = tf.image.ssim_multiscale(img1=video1, img2=video2, max_val=1.0)
```
``` python
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-9-cc68ceec0921> in <module>
----> 1 ms_ssim_score = tf.image.ssim_multiscale(img1=video1, img2=video2, max_val=1.0)

~/.local/lib/python3.5/site-packages/tensorflow_core/python/ops/image_ops_impl.py in ssim_multiscale(img1, img2, max_val, power_factors, filter_size, filter_sigma, k1, k2)
   3405             filter_sigma=filter_sigma,
   3406             k1=k1,
-> 3407             k2=k2)
   3408         mcs.append(nn_ops.relu(cs))
   3409 

~/.local/lib/python3.5/site-packages/tensorflow_core/python/ops/image_ops_impl.py in _ssim_per_channel(img1, img2, max_val, filter_size, filter_sigma, k1, k2)
   3174               math_ops.greater_equal(shape1[-3:-1], filter_size)),
   3175           [shape1, filter_size],
-> 3176           summarize=8),
   3177       control_flow_ops.Assert(
   3178           math_ops.reduce_all(

~/.local/lib/python3.5/site-packages/tensorflow_core/python/util/tf_should_use.py in wrapped(*args, **kwargs)
    196   """
    197   def wrapped(*args, **kwargs):
--> 198     return _add_should_use_warning(fn(*args, **kwargs))
    199   return tf_decorator.make_decorator(
    200       fn, wrapped, 'should_use_result',

~/.local/lib/python3.5/site-packages/tensorflow_core/python/ops/control_flow_ops.py in Assert(condition, data, summarize, name)
    154           op=None,
    155           message="Expected '%s' to be true. Summarized data: %s" %
--> 156           (condition, "\n".join(data_str)))
    157     return
    158 

InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: 8, 8, 8, 1
11

```

**Comment by gadagashwini** [comment]
Issue is replicating on colab with TF 2.0. Please see the [gist](https://colab.sandbox.google.com/gist/gadagashwini/45c4eb25cbba648f1a48a0bade7587b8/untitled229.ipynb). Thanks!

**Comment by dhruv13J** [comment]
+1
The following code reproduces the error:

```
a = np.random.randn(1, 10, 10, 1)
max_val = np.max(np.reshape(a, [-1]))

l = tf.image.ssim_multiscale(a, a, max_val, filter_size=11)
```

**Comment by isaacgerg** [comment]
Any update on this.  Have the same issue with 2.1.0-rc2

**Comment by gadagashwini** [comment]
Could replicate the issue with Tf-nightly == 2.2.0.dev20200316.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/6bff2733702ece74d63d3de197bab46a/untitled458.ipynb). Thanks!

**Comment by isaacgerg** [comment]
I was also able to verify with your gist that psnr() has the same issue and is also broke.

**Comment by szerintedmi** [comment]
same here with tensorflow  `2.2.0-rc3`
interestingly it works for me on `(255,255,1)` shape tensors but got the same error with two `(128,128,1)` tensors

**Comment by ravikyram** [comment]
Could replicate the issue with TF 2.2.0-rc4.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/78e436329f8216cc39153b804181d402/untitled856.ipynb).Thanks!

**Comment by aakash30jan** [comment]
The issue appears to be with assertion after spatial-dimension reduction. In  `_ssim_per_channel `, the `H` and `W` of images is [asserted](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/image_ops_impl.py#L3524) against `filter_size` . Whereas in `ssim_multiscale`, [downsampling ](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/image_ops_impl.py#L3741)is performed `len(power_factors)-1` times. 

Here are two workarounds:
1. Make sure that `filter_size` is small enough to calculate ssim values for all the four spatial-scales(excluding first scale) after downsampling within `ssim_multiscale`. Contrarily, ensure both `H` and `W ` of your image are big enough such that **`H/(2**4) and W/(2**4) >= filter_size`** .  

2. Since downsampling is performed `len(power_factors)-1` times, you can also use lesser number of `_MSSSIM_WEIGHTS` or power_factors than default, which means `H/(2**(len(power_factors)-1)) and W/(2**(len(power_factors)-1)) >= filter_size` .

```python3
field1 = tf.random.uniform(shape=[8, 64, 64, 1], minval=0, maxval=1)
field2 = tf.random.uniform(shape=[8, 64, 64, 1], minval=0, maxval=1) 
#Use smaller filter_size
ms_ssim_score = tf.image.ssim_multiscale(img1=field1, img2=field2, max_val=1.0,
                                         filter_size=4)
#Or use lesser number of power_factors
ms_ssim_score = tf.image.ssim_multiscale(img1=field1, img2=field2, max_val=1.0,
                                         power_factors=(0.0448, 0.2856, 0.3001),
                                         filter_size=11)
```
Hope this helps :-)

**Comment by rmothukuru** [comment]
@AravindGanesh,
Sorry for the delayed response. Can you please let us know if [this workaround](https://github.com/tensorflow/tensorflow/issues/33840#issuecomment-633715778) helped you so that we can work towards closure of this issue? Thanks!

**Comment by sachinprasadhs** [comment]
@AravindGanesh , The issue has been fixed in Tensorflow 2.5 version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/586e5ad2732c96c6ee5b547f906b4213/224.ipynb).

**Comment by aakash30jan** [comment]
> @AravindGanesh , The issue has been fixed in Tensorflow 2.5 version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/586e5ad2732c96c6ee5b547f906b4213/224.ipynb).

@sachinprasadhs the issue is not fixed even with tf2.5,  you have pasted my workaround in your gist. The issue still persists, please check by pasting what OP @AravindGanesh has mentioned or check the proper gist [here](https://colab.research.google.com/gist/aakash30jan/7add0e61ea973844360cf569bf8dcffc/issue_33840.ipynb).

**Comment by sachinprasadhs** [comment]
@aakash30jan, There was some mistake, reopened the issue.

**Comment by mohantym** [comment]
Hi! @AravindGanesh  and Thanks @aakash30jan . Was able to replicate the issue with TF v2.5  with different numbers of power factors starting with default  values as mentioned in official  tensorflow document .The program ran successfully only when power_factor was 2 or 3 , Please find the [gist](https://colab.research.google.com/gist/mohantym/917ff98e449aeb85c98d2f58a5e065b4/33840.ipynb#scrollTo=08xZvKrGCfLn) here ..Thanks!

**Comment by aakash30jan** [comment]
dum dum

**Comment by dmvieira** [comment]
The error persists here using python 3.7 and tensorflow 2.9.1

> The issue appears to be with assertion after spatial-dimension reduction. In `_ssim_per_channel `, the `H` and `W` of images is [asserted](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/image_ops_impl.py#L3524) against `filter_size` . Whereas in `ssim_multiscale`, [downsampling ](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/ops/image_ops_impl.py#L3741)is performed `len(power_factors)-1` times.
> 
> Here are two workarounds:
> 
>     1. Make sure that `filter_size` is small enough to calculate ssim values for all the four spatial-scales(excluding first scale) after downsampling within `ssim_multiscale`. Contrarily, ensure both `H` and `W ` of your image are big enough such that **`H/(2**4) and W/(2**4) >= filter_size`** .
> 
>     2. Since downsampling is performed `len(power_factors)-1` times, you can also use lesser number of `_MSSSIM_WEIGHTS` or power_factors than default, which means `H/(2**(len(power_factors)-1)) and W/(2**(len(power_factors)-1)) >= filter_size` .
> 
> 
> ```python
> field1 = tf.random.uniform(shape=[8, 64, 64, 1], minval=0, maxval=1)
> field2 = tf.random.uniform(shape=[8, 64, 64, 1], minval=0, maxval=1) 
> #Use smaller filter_size
> ms_ssim_score = tf.image.ssim_multiscale(img1=field1, img2=field2, max_val=1.0,
>                                          filter_size=4)
> #Or use lesser number of power_factors
> ms_ssim_score = tf.image.ssim_multiscale(img1=field1, img2=field2, max_val=1.0,
>                                          power_factors=(0.0448, 0.2856, 0.3001),
>                                          filter_size=11)
> ```
> 
> Hope this helps :-)

this workaround works great, but I think it's not the fix. I don't know if define the max filter_size and alert with an warning is an option, but is possible with this code and I can contribute with something like these if you agree:
`filter_size = max(1, min(img1.shape[1]//(2**(len(power_factors)-1)), img1.shape[2]//(2**(len(power_factors)-1)), img2.shape[2]//(2**(len(power_factors)-1)), img2.shape[1]//(2**(len(power_factors)-1))))`

For filter_size 11 do you need an image at least 176X176

**Comment by mohantym** [comment]
Ok @dmvieira ! 
Thanks for the update. Re-opening as requested. Could you raise a PR from your end .
Thank you!

**Comment by aakash30jan** [comment]
@dmvieira perhaps this is well suited 

```
def suggest_filter_size(image1_batch,image2_batch,power_factors,filter_size):
      shape1= image1_batch.shape[1:-1]  
      shape2= image2_batch.shape[1:-1] 
      if not(shape1[-3:-1][0]/(2**(len(power_factors)-1)) and shape2[-3:-1][0]/(2**(len(power_factors)-1)) >= filter_size):
            H = tf.math.reduce_min((shape1,shape2))
            suggested_filter_size = int(H/(2**(len(power_factors)-1)))
      else:
            suggested_filter_size = filter_size
      return suggested_filter_size
```
For example: 
`
suggest_filter_size(field1, field2,power_factors = (0.0448, 0.2856, 0.3001, 0.2363, 0.1333), filter_size = 11)
`
A good fix would be on the user side, something like:

```
H,W = 128,128  
field1 = tf.random.uniform(shape=[8, H, W, 1], minval=0, maxval=1) 
field2 = tf.random.uniform(shape=[8, H, W, 1], minval=0, maxval=1) 
filter_size = 11 #default from tf.image.ssim_multiscale
power_factors = (0.0448, 0.2856, 0.3001, 0.2363, 0.1333)  #default from tf.image.ssim_multiscale
#get a new filter_size from default values
new_filter_size = suggest_filter_size(field1, field2,power_factors,filter_size) 
#tf.image.ssim_multiscale would now work with new_filter_size
ms_ssim_score = tf.image.ssim_multiscale(img1=field1, img2=field1, max_val=1.0,filter_size=new_filter_size)
```

**Comment by dmvieira** [comment]
It's a good code example @aakash30jan ! And a great new feature, but my point was about how is the best Interface for the user. I don't know if build a new function to suggest filter_size is the best way, but perhaps just show a better error with the description explaining that the maximum filter_size should be the value returned by a code similar to `suggest_filter_size`, instead of a generic error. 

Another option is create another param like `auto_change_filter` that uses `suggest_filter_size` or another one is `filter_size` accepts `None` and uses `suggest_filter_size` to determine one, but this last one should be very well documented.

My vote to close this issue is in the first one option that just show a better error and how to use. What do you think?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
