### ISSUE TITLE
Eager context device issue (Segmentation Fault) after context (re-)setting ServerDef 

### ISSUE THREAD

**Issue by pw2393** [tensorflow/tensorflow#33894]
**System information**
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from (source or binary): binary whl
- TensorFlow version (use command below): `tensorflow-gpu==2.0.0`
- Python version: 3.6.8
- CUDA/cuDNN version: 10.0 / 7.6.4
- GPU model and memory: GeForce GTX 1080 Ti

**Describe the current behavior**
```python
import tensorflow as tf
from tensorflow.core.protobuf.tensorflow_server_pb2 import ServerDef
from tensorflow.python.eager import context
from tensorflow.python.training.server_lib import ClusterSpec


cluster_def = ClusterSpec({'worker': ['127.0.0.1:15293']}).as_cluster_def()
# 15293 is just some random available port

server_def = ServerDef(
    cluster=cluster_def,
    job_name='worker',
    task_index=0,
    protocol='grpc'
)

v = tf.Variable(3)

print(v.device)
# > /job:localhost/replica:0/task:0/device:CPU:0

context.set_server_def(server_def)

####################################
print(v.device)
# > Segmentation fault (core dumped)
####################################
```

**Describe the expected behavior**

* Should API users expect the Variable re-placed and re-initialized on the new Server?

**Code to reproduce the issue**
See above

**Comment by oanush** [comment]
@pw2393 ,
When tried running the given code, session crashed all the time. Is the same error faced ? Find the [gist](https://colab.sandbox.google.com/gist/oanush/9a232909b3ae54c70913a3df6491cab3/33894.ipynb) of colab.Thanks!

**Comment by pw2393** [comment]
> @pw2393 ,
> When tried running the given code, session crashed all the time. Is the same error faced ? Find the [gist](https://colab.sandbox.google.com/gist/oanush/9a232909b3ae54c70913a3df6491cab3/33894.ipynb) of colab.Thanks!

@oanush Yes. It crashes. If running it in simply Python Interpreter, one may see `Segmentation fault (core dumped)`. (In colab case, that error sends a sys signal which leads to a session crash.)

**Comment by haoyuz** [comment]
Hello @pw2393 , this happens because `v.variable` refers to a device which is recreated before cluster initialization. `set_server_def` essentially recreates the devices and device managers (and also destroy existing ones) so `v.device` points to invalid memory and accessing it would cause segfault. This for now is intended behavior.

In the current codebase (you can install the latest nightly release by `pip install tf-nightly`), we provide an experimental `update_server_def` API that users can call to add/remove workers in a cluster, while still able to access ops/tensors on unchanged devices. Note that the variable devices must still be valid after the update for them to be accessed successfully. For example,

```python
import tensorflow as tf
from tensorflow.core.protobuf.tensorflow_server_pb2 import ServerDef
from tensorflow.python.eager import context
from tensorflow.python.training import server_lib
from tensorflow.python.training.server_lib import ClusterSpec

cluster_def = ClusterSpec({'localhost': ['localhost:15293']}).as_cluster_def()
server_def = ServerDef(cluster=cluster_def, job_name='localhost', task_index=0, protocol='grpc')

context.set_server_def(server_def)
v = tf.Variable(3)
print(v.device)

context.update_server_def(server_def)
print(v.device)
```

**Comment by pw2393** [comment]
@haoyuz Thanks a lot! BTW, any chance you might know how to deal with #34242 ?
