### ISSUE TITLE
Insert Windows command line in the tutorials

### ISSUE THREAD

**Issue by raffaem** [tensorflow/tensorflow#33923]
## URL(s) with the issue:

Example: https://www.tensorflow.org/tutorials/keras/save_and_load

## Description of issue (what needs changing):
 
The tutorial uses POSIX commands like:

`!ls {checkpoint_dir}`

Unfortunately I am on Windows so those commands does not work. Is there no way to condition the command on the OS?

`!dir {checkpoint_dir}`

The alternative way would be to use Python straightaway:

```
onlyfiles = [f for f in os.listdir(mypath) if os.path.isfile(os.path.join(mypath, f))]
print(onlyfiles)
```

**Comment by MarkDaoust** [comment]
The ! system commands are just used because they're convienient, and work in colab which we see as the primary execution platform for these. there's no good way to switch these based on the OS. 

As you say probably the most platform independent way is to just do it in python. 

I'd probably go with:
```
mypath = pathlib.Path(...)
list(mypath.glob('*'))
```

I'm unable to prioritize this right now. 

@raffaem I would welcome any PR you can send to tensorflow/docs making this sort of change.

**Comment by samaritanhu** [comment]
Hi, this is my first time contributing to the TensorFlow community. Since no one is taking this task, can I volunteer to take this task? 

One more question - since the doc you mentioned is in here: https://github.com/tensorflow/docs-l10n/blob/master/site/zh-cn/tutorials/keras/save_and_load.ipynb. To update this doc on the website, I just need to change the `ipynb` file, right?

Thank you! I am happy to contribute to this issue :)
