### ISSUE TITLE
Exif Orientation support tf.image.decode_jpeg()

### ISSUE THREAD

**Issue by wikiwen** [tensorflow/tensorflow#33932]
Hi.
I have large amounts of JPEG files uploaded by users on our service .
They use mainly smartphone camera, so most files contain **EXIF orientation metadata.**

It would seem that the **tf.image.decode_jpeg() ignores this information.** How about adding support for these meta informations, especially orientation ?

This issue is from 
> https://github.com/tensorflow/tensorflow/issues/8430#issue-214362114

**But I found this problem is still existing. Anybody knows how to solve this probelm? I found opencv take the EXIF information into count, but it's hard to use opencv to replace tensorflow image processor.**
```python
        image_bgr = cv2.imread(file_name)
        image_rgb = cv2.cvtColor(image_bgr, cv2.COLOR_BGR2RGB)
        image = np.asarray(image_rgb)
        # image_buffer = tf.read_file(file_name)
        # image_rgb = tf.image.decode_jpeg(image_buffer)
        # image = tf.cond(tf.equal(tf.shape(image_rgb)[2], 1), lambda: tf.image.grayscale_to_rgb(image_rgb), lambda: tf.identity(image_rgb))
```

**Comment by yongtang** [comment]
@wikiwen I added a `decode_jepg_exif` in [tensorflow/io](https://github.com/tensorflow/io) with PR  tensorflow/io#604 . This will allows you to obtain the orientation from JPEG, so that it is possible to do post-processing.

If there is enough further interest, I could add additional enhancement for
1) Extract additional fields in EXIF than orientation
2) Add another function (or a new kernel) to automatically adjust decoded JPEG with orientation.

Please take a look at the PR tensorflow/io#604

**Comment by wikiwen** [comment]
@yongtang Nice work! Thanks~

**Comment by yongtang** [comment]
@wikiwen As PR  tensorflow/io#604 has been merged, you can give it a try and see if it fits you needs. I will close this issue for now.

If you want additional features such as automatically transformint the picture's orientation based on the EXIF's orientation value, can you open a new issue in [tensorflow/io](https://github.com/tensorflow/io) repo? We can continue the discussion there.
