### ISSUE TITLE
model summary, input_layer, output_layer not working properly in sub-classing method of tf.keras

### ISSUE THREAD

**Issue by fightthepower** [tensorflow/tensorflow#33946]
**EDIT:** _After further research I found that in subclassing many of the models methods and attributes are not working examples are input_names, output_names etc.._

I am using TF2 I am trying to build a model via sub-classing method. In sequantial model; methods and attributes such as summary, input_layer, output_layer works

```
import tensorflow as tf
import tensorflow.keras as keras

model = keras.Sequential([
    keras.layers.Dense(4,input_shape=(None,3)),
    keras.layers.Dense(3, activation='relu'),
    keras.layers.Dense(2, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

print(model.summary())
print(model.input_shape)
print(model.output_shape)
```

But in sub classing those methods and attributes are not working properly.

```
class MLP(tf.keras.Model):
    def __init__(self):
        super().__init__()
        self.fc1 = tf.keras.layers.Dense(4,input_shape=(None,3))
        self.fc2 = tf.keras.layers.Dense(3,activation = 'relu')
        self.fc3 = tf.keras.layers.Dense(2,activation ='softmax')
    def call(self,x):
        x = self.fc1(x)
        x = self.fc2(x)
        x = self.fc3(x)
        return x


model = MLP()
model.build((1,3))
print(model.summary())

print(model.input_shape)
print(model.output_shape)
```

The summary output in sub class model doesn't show the output shapes
```
Layer (type)                 Output Shape              Param #   
=================================================================
dense_11 (Dense)             multiple                  16        
_________________________________________________________________
dense_12 (Dense)             multiple                  15        
_________________________________________________________________
dense_13 (Dense)             multiple                  8         
=================================================================
Total params: 39
Trainable params: 39
Non-trainable params: 0
```
and model.input_shape and model.output_shape returns this error,
>raise AttributeError('The layer has never been called '
AttributeError: The layer has never been called and thus has no defined output shape.

**Comment by oanush** [comment]
Issue replicating for given code TF-2.0, please find the [gist](https://colab.sandbox.google.com/gist/oanush/10d4f67e126e105e8972f47b023f98f1/33946.ipynb) of colab.Thanks!

**Comment by jvishnuvardhan** [comment]
@fightthepower There are some differences between subclass model and other models (Sequential and Functional). 

Functional and Sequential models are static graphs of layers, so you can infer the shapes while building the model. Whereas Subclass model is a piece of Python code (a call method), there is no static graph of layers. So it is difficult to know how layers are connected to each other  (because that's defined in the body of call, not as an explicit data structure), so we cannot infer input / output shapes. Only when we train or test with real data, then only we know the shape. I think there are some workaround suggested by some of the users [here](https://github.com/tensorflow/tensorflow/issues/29132).

I think this is resolved. I am closing this issue. Feel free to open a new issue if you encounter any other issue. Thanks!
