### ISSUE TITLE
List index out of range for FashionMNIST tutorial.

### ISSUE THREAD

**Issue by fsiraj** [tensorflow/tensorflow#34022]
I've just started learning a bit about Tensorflow, and I tried out the Fashion MNIST tutorial. However, I keep getting a list index out of range error. I've copied the code from the official tutorial and also tried using tf.reset_default_graph() as suggested in some other posts, but neither have worked.

Here is the notebook with the error:
https://github.com/fsiraj/Tensorflow-Tutorials/blob/master/Fashion%20MNIST.ipynb

**Comment by oanush** [comment]
@fsiraj ,
Hi, in the section 
```
# Training loop
model.fit(train_images, epochs=10)
```
model.fit is expecting `train_labels` 
please use `model.fit(train_images,train_labels, epochs=10)` you will be able to execute the tutorial without any issues.
Thanks!

**Comment by fsiraj** [comment]
@oanush 
Thanks for the quick reply, silly mistake on my behalf. Fixing the issue I ran into another error which I've gotten with another tutorial as well. It says "InternalError:  Blas GEMM launch failed". 

Having just started I'm not sure what to make of this. I've updated the notebook so you can get a look at the new error.

**Comment by oanush** [comment]
@fsiraj ,
Try doing a fresh run from the beginning always by restarting the kernal when any changes are made in the code, no error will be faced, please find the [gist](https://colab.sandbox.google.com/gist/oanush/3c3415a29ca3c051fe924b891a579701/34022.ipynb) of colab for your reference . Thanks!

**Comment by fsiraj** [comment]
@oanush 
I've tried that but I always run into this error. I'm running the notebook in a conda environment with only tensorflow and other required modules and dependencies. Is this an issue with my system?

**Comment by oanush** [comment]
@fsiraj ,
Issue might be due to opening too many Jupyter Notebooks. Please check this [comment](https://github.com/tensorflow/tensorflow/issues/34069#issuecomment-551573104) of similar issue.
Also find links of these similar issue's and solutions present in them and see if it solves the issue [1](https://github.com/tensorflow/tensorflow/issues/11812),[2](https://stackoverflow.com/questions/37337728/tensorflow-internalerror-blas-sgemm-launch-failed) and [3](https://stackoverflow.com/questions/43990046/tensorflow-blas-gemm-launch-failed?rq=1).Thanks!

**Comment by fsiraj** [comment]
I tested this and it seems if I have more than one notebook open it always fails. This solves the issue so thank you!

I was still wondering why this happens it's not very convenient at all.
