### ISSUE TITLE
Error in the document of tf.keras.layers.Dense

### ISSUE THREAD

**Issue by changy12** [tensorflow/tensorflow#34207]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense 

## Description of issue (what needs changing):
The tf.keras.layers.Dense can actually take input_shape as function input, but it is not shown in this document.
In addition, the example of this document has the function "Dense", but I tried on my Googlecolab and it is not defined in tensorflow2.

**Comment by pandrey-fr** [comment]
Hi,

Thank you for your submission; I believe however that this is more of an issue with the understanding of how the docs are formatted rather than an actual issue with their content.

> The tf.keras.layers.Dense can actually take input_shape as function input, but it is not shown in this document.

`input_shape` is one of the default keyword arguments inherited from the parent `Layer` class (just as `dtype` for example), which is why it is not explicitly documented for `Dense` class.

> In addition, the example of this document has the function "Dense", but I tried on my Googlecolab and it is not defined in tensorflow2.

As in most documentation examples, imports are not explicitly displayed. To reproduce, you must run `from tensorflow.keras.layers import Dense` (same thing with the `Sequential` class).

**Comment by dubesar** [comment]
> In addition, the example of this document has the function "Dense", but I tried on my Googlecolab and it is not defined in tensorflow2.

```python3
from tensorflow.python.keras.layers import Input, Dense
from tensorflow.python.keras.models import Sequential
model = Sequential()
model.add(Dense(32, input_shape=(16,)))
model.add(Dense(32))
```

**Comment by changy12** [comment]
I C. 
Thank U very much.

**Comment by gowthamkpr** [comment]
@changy12 As @pandrey-fr mentioned, it is clear that this is not a docs issue, its more of the way it has been formatted. I am gonna close this issue as it has been resolved. Please add additional comments and we can open this issue again. Thanks!
