### ISSUE TITLE
use tensorflow inference on CPU and get error "undefined symbol: _ZN10tensorflow10DEVICE_CPUE"

### ISSUE THREAD

**Issue by psnbbgy** [tensorflow/tensorflow#34232]
I use tensorflow to inference lstm crf model on CPU, and I compile a lib use tensorflow C++ API, depend on tensorflow source code.
my compile environment is GCC 4.8.5, tensorflow 1.12.0, bazel 0.15.0

when I load the so lib, it report an error: undefined symbol: _ZN10tensorflow10DEVICE_CPUE, anybody knows why? or if I must provide more information?

**Comment by gadagashwini** [comment]
@psnbbgy, Please provide more information about the issue.
Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by gadagashwini** [comment]
@psnbbgy, Please provide the information asked in the template. Thanks!

**Comment by gadagashwini** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by tslater** [comment]
@psnbbgy did you ever solve this? I'm facing it now.
