### ISSUE TITLE
tf.function hangs on ragged tensor input

### ISSUE THREAD

**Issue by MikeOfZen** [tensorflow/tensorflow#34297]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):No
- TensorFlow installed from (source or binary):Colab
- TensorFlow version (use command below):2.0.0
- Python version:3.6
- GPU model and memory:None

**Describe the current behavior**
When using tf.function with a number of for loops on a RaggedTensor, the function call hangs (I stopped waiting after half hour).
-when running the function directly (no tf.function decorator), the function executes immediately
-when converting the ragged tensor to dense tensor, the function executes immediately.

I couldn't pinpoint the exact combination of operations that causes this Autograph behavior, but I tried to reduce my code to the simplest combination that still causes this behavior.
I struggled for hours with my own code, trying to get tf.function to work, until I figured it was due to the ragged tensor + for loops + tf.function hanging the kernel

I observed similar behavior on my machine and a colab machine as well.

**Describe the expected behavior**
Should execute in a comparable time to a dense tensor.

**Code to reproduce the issue**
```
%tensorflow_version 2.x
import tensorflow as tf
import numpy as np

inp=tf.ragged.constant(np.arange(1000,dtype=np.float32).reshape(10,10,10))

@tf.function    #if not using tf.function it runs well
def ragged_example(r_tensor):
  s=tf.constant(0.0)
  for i in tf.range(10):
    inner=r_tensor[i]
    for x in inner:
      b=tf.reduce_sum(x)
      s=s+b
  return s

#inp=inp.to_tensor() #if this is uncommented, it runs well

ragged_example(inp) #this hangs
```
**Other observations**
Also noted very large memory footprint as a result (9gb and growing)

**Comment by rmothukuru** [comment]
Could reproduce the issue with TF Version 2.0. Here is the [Gist](https://colab.sandbox.google.com/gist/rmothukuru/3a286f4b25e62d041d0030e80a4e1cb2/34297.ipynb). Thanks!

**Comment by mdanatg** [comment]
This bug is a combination of several problems that we'll need to resolve, fopefully in 2.2. In the mean time, a workaround is to avoid writing for loops over ragged tensors (e.g. `for x in ragged_tensor`). This means rewriting your code like so:

```
def ragged_example(r_tensor):
  s = tf.constant(0.0)
  for i in tf.range(10):
    inner = r_tensor[i]
    for j in tf.range(inner.row_lengths()[0]):  #  `for x in inner` doesn't work yet.
      x = inner[i]
      b = tf.reduce_sum(x)
      s = s + b
  return s
```

A few more details on the cause of the bug --

Autograph doesn't currently support iterating over `RaggedTensor`, and it thinks they are normal Python objects. We'll fix that in autograph, hopefully by TF 2.2.
Now, this should have normally generated an error (something in the lines of "cannot directly iterate over RaggedTensor in graph mode"). But it seems that the `RaggedTensor` class is iterable and the iterator it returns hangs when consumed in graph mode. @edloper I think this iterator should error out in `tf.function` instead?

**Comment by MikeOfZen** [comment]
Thank you for the update and the details.

**Comment by mdanatg** [comment]
The PR that just got merged should fix the issue in tf.function.

As a side note, we should still disallow RaggedTensor.__iter__ in graph code (or make it return a proper graph-based iterator).
