### ISSUE TITLE
How to use Per-channel quantize in TFLite？

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#34299]
Hello
from the tflite conv.cc , I can see that now tflite supports Per-channel quantize , is there any guide or doc how to use per-channel quantize when convert tf model to tflite?

**Comment by developer22-university** [comment]
hi,

https://github.com/KhronosGroup/NNEF-Tools/issues/40

https://www.tensorflow.org/lite/performance/post_training_quantization

CHECK THESE LINKS UPDATE ME

**Comment by liyunlu0618** [comment]
When you use post-training integer quantization, per-channel quantization is enabled by default. Please follow instructions here:
https://medium.com/tensorflow/tensorflow-model-optimization-toolkit-post-training-integer-quantization-b4964a1ea9ba

**Comment by jakc4103** [comment]
@liyunlu0618 Do you know how to specify for using per-layer instead in tflite?  I searched in many tutorials and documents, no luck however.

**Comment by liyunlu0618** [comment]
Currently if you use post-training integer quantization it's per-channel by default. There's no way to configure that to use per-layer quant. The legacy quantization-aware training (QAT) used per-layer quantization but we're deprecating that. The upcoming QAT will also use per-channel.

**Comment by LLNLanLeN** [comment]
Hey @liyunlu0618  , sorry to bring up this issue again (since been closed for a while), but I"m just looking for some answer and hopefully you can provide me some. To my understanding, right now TF QAT for Conv2D is still supporting per-axis quantization, I'm wondering if we can pass in some custom configuration for quantizing to make it per-tensor quantization instead? If it's possible, I'm wondering if you can provide me some examples/ resources to do so.

**Comment by peter197321** [comment]
Hello guys,

I'm facing a similar issue of not-having per-layer quantization available - is it somehow enforce this feature (per-layer-quantization)?
As @liyunlu0618 mentioned this feature ((per-layer-quantization)) will be removed but is it somehow possible to have this feature - if so, how?

Thank you.

Peter

**Comment by fPecc** [comment]
Hi,

Any plans on enabling per layer quantization, instead of per channel?
