### ISSUE TITLE
Batch pre-padding with Tensorflow datasets

### ISSUE THREAD

**Issue by shahriar49** [tensorflow/tensorflow#34311]
I have a dataset of variable-length sequences to feed an LSTM network and I want to do pre-padding in the batches, but current padded_batch function only pads at the sequences end. How can I do it?
I asked this question on stackoverflow but nobody answered me.

**Comment by developer22-university** [comment]
i know it is little tricky but what helped me is this article check it out. and please update me.
https://machinelearningmastery.com/data-preparation-variable-length-input-sequences-sequence-prediction

**Comment by developer22-university** [comment]
happy to help

**Comment by shahriar49** [comment]
@developer22-university 
Thanks for reply. What it says in the article is about padding a sequence by itself, but what I want is an integrated batch&pad capability for a tensorflow dataset. This article has nothing to do with datasets.

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by shahriar49** [comment]
@rmothukuru 
I am referring to the padded_batch function as described in https://www.tensorflow.org/api_docs/python/tf/data/Dataset#padded_batch
I just want to know how to do this thing (padded_batch) in pre-padding format. The current function only implements post-padding.
I am using Tenorflow 1.12 on Python 3.6/Windows platform, but my question is general.

**Comment by jsimsa** [comment]
You can implement your custom batching logic using existing tf.data transformation thanks to the following API: https://github.com/tensorflow/community/blob/master/rfcs/20180726-tf-data-windowing-reducers.md

**Comment by shahriar49** [comment]
@jsimsa 
Thanks for link!

**Comment by ravikyram** [comment]
@shahriar49 

Please close this thread if it solves your question. Thanks!
