### ISSUE TITLE
TensorRT not working due to eager execution

### ISSUE THREAD

**Issue by anshkumar** [tensorflow/tensorflow#34339]
I'm trying to convert my saved model to tensorRT but I'm failing due to following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/compiler/tensorrt/trt_convert.py", line 911, in __init__
    assert context.executing_eagerly()
AssertionError
```

Here, is my code
```
from tensorflow.python.compiler.tensorrt import trt_convert

conversion_params = trt_convert.DEFAULT_TRT_CONVERSION_PARAMS._replace(precision_mode=trt_convert.TrtPrecisionMode.FP16, max_batch_size=1, max_workspace_size_bytes=8000000000)

trt_converter = trt_convert.TrtGraphConverterV2(input_saved_model_dir='/home/xavier2/apple_trt_l1/nonRT',  conversion_params=conversion_params)
```

Here are my specs:
Tensorflow version: 1.14.0
Platform: NVIDIA Jetson AGX Xavier developer kit
Python: 3.6.8

**Comment by oanush** [comment]
@anshkumar ,
Hi, looks like the issue is fixed in TF version-2.0. Can you try running the code in 2.0? kindly find the gist of [colab](https://colab.sandbox.google.com/gist/oanush/76966638dba18670472226ba0dac6607/34339.ipynb) for your reference. Thanks!

**Comment by anshkumar** [comment]
My platform is NVIDIA Jetson AGX Xavier; tensorflow is provided by nvidia. The list of version provided by them is here. NVIDIA does not provide Tensorflow-2.0 for Jetson.

**Comment by gowthamkpr** [comment]
TrtGraphConverterV2 only converts TF 2.0 SavedModels as shown [here](https://github.com/tensorflow/tensorflow/blob/00fad90125b18b80fe054de1055770cfb8fe4ba3/tensorflow/python/compiler/tensorrt/trt_convert.py#L851)

Are you using Tensorflow 2.0 Saved model or Tensorflow 1.14 saved model? If you are using a saved model that is other than 2.0 then this throws an error.

**Comment by anshkumar** [comment]
Yes I was using Tensorflow lower than 2.0. Using following command I'm able to convert properly,

`trt_converter = trt_convert.TrtGraphConverter(input_saved_model_dir='/home/xavier3/single_model', precision_mode="FP16", is_dynamic_op=True)`

**Comment by saurabbhsp** [comment]
Hi,
I am facing the same issue with tensorflow==2.1.0+nv20.4

**Comment by CyclingGeek** [comment]
Ran into same issue after fresh install of Jetpack 4.4 on Jetson Nano  which contains tensorflow==2.1.0+nv20.4. Loaded and built pycuda and got the same error. After looking into code, found the exception was due to tf.executing_eagerly() == False. 
-- Work around --
import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt
    ....
    ....
    tf.compat.v1.enable_eager_execution()
    print('Using Tensorflow version: {0}'.format(tf.version.VERSION))   
    print(tf.executing_eagerly()) 
   ### Was able to execute trt.TrtGraphConverterV2 on keras models ##

I was under the impression that all TF 2.x versions ran with executing_eagerly == TRUE as default. When I import tensorflow 2.1.0+nv20.4 it seems that execute_eagerly is initialized as false in JP 4.4

>>> import tensorflow as tf
2020-05-08 22:22:59.965357: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2
2020-05-08 22:23:07.427738: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libnvinfer.so.7
2020-05-08 22:23:07.474677: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libnvinfer_plugin.so.7
>>> print(tf.executing_eagerly())
False

When I do the same thing on JP 4.3 with tensorflow 2.1.0+nv20.3.tf2

Python 3.6.9 (default, Apr 18 2020, 01:56:04)
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
2020-05-08 22:47:32.666516: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcudart.so.10.0
2020-05-08 22:47:37.064950: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer.so.6
2020-05-08 22:47:37.067243: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libnvinfer_plugin.so.6
>>> print(tf.executing_eagerly())
True
>>>

Anyone have any thoughts ? Or is this a bug
