### ISSUE TITLE
module 'keras.applications' has no attribute 'resnet'

### ISSUE THREAD

**Issue by mimimichelle** [tensorflow/tensorflow#34361]
I tried to google the whole day and nothing worked for me.

So in the beginning I got this:
module 'keras.applications' has no attribute 'resnet'

Then I tried a few ways that I got from googling, I got this:
module 'tensorflow' has no attribute 'get_default_graph'

seems like related but I can't understand what's wrong here. My keras version is 2.2.4.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by mimimichelle** [comment]
Thanks for your reply ravikyram.

OS: Windows 10
Python 3.6 with Anaconda
TensorFlow version: 2.0.0
keras version: 2.2.4

I installed tensorflow in Anaconda with conda install xxxxx. And then I got into the tensorflow environment in Anaconda and installed keras. I was provided these codes but they didn't seem to work. The purpose here is to download the ResNet50 model.

import numpy as np
import keras
from keras.preprocessing.image import ImageDataGenerator
from keras.applications.resnet50 import ResNet50, decode_predictions
from keras import layers
from keras.models import Model, Sequential
from keras.callbacks.callbacks import ModelCheckpoint, EarlyStopping
resnet = keras.applications.resnet.ResNet50(include_top=False, weights='imagenet', input_shape=(224,224,3))

I tried keras_application. I tried tensorflow.keras.xxxx. Nothing worked for me. I'm totally lost... Thanks!

**Comment by ravikyram** [comment]
@mimimichelle 
I tried with tf.keras and it was working fine. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/b7bc35d73f7a8238119f0340103ea120/untitled381.ipynb).Thanks!

**Comment by ravikyram** [comment]
@mimimichelle 
Please, let us know if this issue still persists?.Thanks!

**Comment by konschat** [comment]
> Thanks for trying to help. I figured out it's a version/Windows-Anaconda default setting problem.

Hello @mimimichelle , can you specify what was that exactly?
