### ISSUE TITLE
Mixed precision training with tf.keras 2.0

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#34406]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below): 2.0.0
- Python version: 3.5
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: V100

**Describe the current behavior**

I am trying to incorporate mixed-precision training in my `tf.keras` models. After going through [the instructions on the NVIDIA docs](https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html), I used the following code snippet (full code is provided in the end):

```python
opt = tf.keras.optimizers.Adam()
opt = tf.train.experimental.enable_mixed_precision_graph_rewrite(opt)
model.compile(loss=loss, optimizer=opt)
model.fit(...)
```
I do not see any speed up after mixed precision is enabled. I tried out `tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt, "dynamic")`. Still there is no significant improvement to note. On the other hand, I tried to experiment with `tf.keras.mixed_precision.experimental.set_policy('mixed_float16')` but I am kind of confused about how to appropriately use it. I am trying to train the following model on the FashionMNIST dataset:

```python
tf.keras.mixed_precision.experimental.set_policy('mixed_float16')
model = Sequential([
            Input((28,28,1)),
            Conv2D(32, (3, 3), activation='relu'),
            MaxPooling2D((2,2)),
            Conv2D(64, (3, 3), activation='relu'),
            MaxPooling2D((2,2)),
            Conv2D(64, (3, 3), activation='relu'),
            GlobalAveragePooling2D(),
            Dense(64, activation='relu'),
            Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
```

But when I call `model.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=10, batch_size=128)`, I get the following:

```
/usr/local/lib/python3.5/dist-packages/tensorflow_core/python/framework/op_def_library.py in _apply_op_helper(self, op_type_name, name, **keywords)
    561                   "%s type %s of argument '%s'." %
    562                   (prefix, dtypes.as_dtype(attrs[input_arg.type_attr]).name,
--> 563                    inferred_from[input_arg.type_attr]))
    564 
    565           types = [values.dtype]

TypeError: Input 'y' of 'Mul' Op has type float32 that does not match type float16 of argument 'x'.
```

The entire error trace is there in the attached notebook. The second experiment in this line I did was with `policy = tf.keras.mixed_precision.experimental.Policy('mixed_float16')`. In that, I just set the `dtype` of the penultimate dense layer (of the above-mentioned model) to `policy`. The works fine but throws this warning:

```
WARNING:tensorflow:Layer dense_1 is casting an input tensor from dtype float16 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float16 by default, call `tf.keras.backend.set_floatx('float16')`. To change just this layer, pass dtype='float16' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.
```

Any recommended way of using these policies along with simple and more complex models? 

**Describe the expected behavior**

**Code to reproduce the issue**
[Mixed Precision Training in tf.keras 2.0.zip](https://github.com/tensorflow/tensorflow/files/3862764/Mixed.Precision.Training.in.tf.keras.2.0.zip)

**Comment by verrannt** [comment]
I had the same problem with float16 training. Please refer to [this issue](https://github.com/tensorflow/tensorflow/issues/33484) for an explanation on why the TypeError is thrown. Apparently, it will be fixed in TF2.1 and is already fixed in the current `tf-nightly-gpu`.
#33484

**Comment by sayakpaul** [comment]
@verrannt thank you very much :)

**Comment by oanush** [comment]
@sayakpaul ,
Looks like the issue is fixed in `tf-nightly-gpu`, can you confirm the same and close the issue ?Thanks!

**Comment by sayakpaul** [comment]
@oanush I can definitely check that out but there were some other issues I mentioned which I believe need some more attention. For example, the speedup not happening when using `tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt, "dynamic")`. So, I would wait for a few days to get some pointers on that.

**Comment by tlkh** [comment]
When using `tf.keras.mixed_precision.experimental.set_policy('mixed_float16')`, the last layer (softmax layer) must currently be set to have `dtype=tf.float32` and it will work:

```python
Dense(10, activation='softmax', dtype=tf.float32)
```

However, you are not seeing speed-up because of a few reasons:

- The model is too small (only 60554 params), so other overheads (casting, padding) have greater impact that speeding up the layers
- Many shapes in the model are not fully efficient on Tensor Cores. Conv filters/channels are multiples of 8, so that's good. But the input/output sizes are not in multiples of 8 (I see 26, 13 etc), and this requires padding in the software. This is much less significant on larger models.

For some "non-official" examples demonstrating speed-up on some real-world models, check out:
https://github.com/NVAITC/pycon-sg19-tensorflow-tutorial

P.S. I am using TensorFlow 2.0 stable

**Comment by sayakpaul** [comment]
@tlkh thanks much for your pointers. I experimented today with ResNet50V2 as well but could not observe any significant improvements. You can find the notebook [here](https://gist.github.com/sayakpaul/e595b12b09dbb40e452db0289a6aa76c). 

Also, did you check out experiments with `tf.train.experimental.enable_mixed_precision_graph_rewrite(opt)` and `tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt, "dynamic")` (notebooks `1 - MP in tf.keras 2.0.ipynb` and `2 - MP in tf.keras 2.0.ipynb` respectively)? They include a larger model.

**Comment by tlkh** [comment]
**2 - MP in tf.keras 2.0.ipynb**

- **Your training is CPU bottlenecked due to the data augmentation**.  Just adding `use_multiprocessing=True` and `workers=8` to the fit function cuts each epoch from 30+s to 20+s on my workstation (20 core Xeon processor). Using tf.data (in particular the `prefetch` function) would likely yield much better results. 
- In any case, I don't think you're using the mixed precision API correctly. `tf.keras.mixed_precision.experimental.LossScaleOptimizer` does not activate mixed precision on its own. You need to call `tf.config.optimizer.set_experimental_options({"auto_mixed_precision": True})`. Note that this is set on a per-session basis, so you need to call `tf.keras.backend.clear_session` to remove that setting. The same goes for when using `enable_mixed_precision_graph_rewrite`, it is a per-session config. You can't enable it half-way in a notebook for the **same** model (like in your first notebook!). 
- GPU utilisation is oddly low (<20%) and I'm actually not quite sure why actually.
- The model is still "too small". The model's convolution layers only have 32 filters each. As a rule of thumb, Conv layers under 256 filters are likely to be memory, not compute bottlenecked. 

Here are my results for mixed precision vs FP32 (V100) after some modifications:

* Modifications: 256 filters per conv layer; 40 workers; batch_size 320; enabled XLA compiler
* FP32: 74.54s for first 3 epochs
* mixed precision: 59.97s for first 3 epochs

For what it's worth, smaller models aren't currently a good showcase for mixed precision. I typically work with larger transformer models, and mixed precision is really a godsend for those!

**Comment by sayakpaul** [comment]
@tlkh thank you for providing the information. I could not find this on the documentations I had studied. Moving forward, I will consider these and will report back accordingly.

**Comment by reedwm** [comment]
Thank you @sayakpaul for filing this issue, and @tlkh for the responses! As mentioned, TF2.1 will fix the TypeError, but you can pass `dtype=tf.float32` to make it work in 2.0.

However, even in 2.1, it is recommended to do softmax in float32 for numeric stability. @tlkh fix of passing `dtype=tf.float32` will cause the softmax to be done in float32, solving the issue. For slightly better performance, you can also just do the softmax in float32 while keeping the Dense layer in mixed_float16, by splitting the Dense layer from the activation as follows:

```
model = Sequential([
            ... # All the previous layers
            Dense(10),
            Activation('softmax', dtype='float32')
])
```

I am trying to find a way to automatically do Softmax in float32, but as of 2.1, you still must explicitly pass `dtype='float32'`.

Also, you can safely ignore the warning you received:

```
WARNING:tensorflow:Layer dense_1 is casting an input tensor from dtype float16 to the layer's dtype of float32, which is new behavior in TensorFlow 2.  The layer has dtype float32 because it's dtype defaults to floatx.

If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float16 by default, call `tf.keras.backend.set_floatx('float16')`. To change just this layer, pass dtype='float16' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.
```

In this particular case, the warning is a bug and should not appear. This has been fixed in the nightlies and TF 2.1, and does not appear with `tf-nightly-gpu`.

I will have a better tutorial for using mixed precision in the future. For now, I recommend using the following: https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/experimental/Policy

**Comment by sayakpaul** [comment]
Thank you very much for passing this along @reedwm. I think the notebooks @tlkh shared are quite nice and definitely provide good insights. I am also working on more experiments to make it easier for the community to try mixed-precision training in `tf.keras` 2.0.

**Comment by sayakpaul** [comment]
@tlkh I experimented with your codes today but on a [different dataset](https://datahack.analyticsvidhya.com/teams/game-of-thrones). Mixed Precision indeed showed it's magic and that too big time. I have pushed the files [here](https://github.com/sayakpaul/Mixed-Precision-Training-in-tf.keras-2.0/tree/master/With_Policy). The GPU utility has significantly increased as I am now using utilities from `tf.data`. I did not see any stark difference in the memory footprint though (you can check those information [here](https://app.wandb.ai/sayakpaul/mixed-precision-tf-keras/runs)). 

I am going to experiment with the other methods now and will share the results here. On a side note, if you see the performance of ResNet got worse on the dataset I used, it can be for a number of reasons, though. 

**Note** that the repository is not complete yet. I am going to add all the acknowledgments, README a bit later.

**Comment by tlkh** [comment]
When using the Policy method, the loss is also scaled. I'm not sure why the tf.config + LossScaleOptimizer would not be working when the Policy method does.
I'm currently a bit tied up with work, but I'll take a close look at this when I have some time.

**Comment by sayakpaul** [comment]
Sure. Thanks, @tlkh :)

**Comment by reedwm** [comment]
@sayakpaul, in [the Jupyter notebook where you have the LossScaleOptimizer](https://github.com/sayakpaul/Mixed-Precision-Training-in-tf.keras-2.0/blob/master/With_Loss_Scale_Optimizer/Mixed_Precision.ipynb), you have the line

```
tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt,  
                                                       "dynamic")
```

The issue is LossScaleOptimizer does not modify the passed in optimizer, but instead returns a new optimizer that performs loss scaling. Try setting `opt` to the LossScaleOptimizer instead:

```
opt = tf.keras.mixed_precision.experimental.LossScaleOptimizer(opt,  
                                                               "dynamic")
```
I think fixing this will cause tf.config + LossScaleOptimizer to work just as well as the Policy. In the future, I'll try to raise an error or warning if this issue occurs.

Also note currently I cannot run the Jupyter notebooks as I do not have the `X_train.npy` and `y_train.npy` datasets.

**Comment by sayakpaul** [comment]
@reedwm extremely sorry about that silly mistake. I have updated the notebooks accordingly but still, the loss increases along with the accuracy. 

Note that I intentionally did not pass the `.npy` files. You would need to run the `Data_gathering_and_prep.ipynb` notebook to generate them.

**Comment by reedwm** [comment]
Also, for the LossScaleOptimizer notebook, try passing `learning_rate=1e-4` to the Adam optimizer:

```
opt = Adam(learning_rate=1e-4)
```

This is already done in the Policy notebook. After doing this, the loss decreased for me instead of increasing.

**Comment by sayakpaul** [comment]
Sure, thanks much @reedwm
