### ISSUE TITLE
Have the count mode passed to the callbacks

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#34417]
**System information**
- TensorFlow version: 2.0.0
- Are you willing to contribute it: Yes

**Describe the feature and the current behavior/state.**
Right now when training on a generator (I don't know about the other cases), when the callbacks are configured, the number of samples passed in might actually be the number of steps (i.e. divided by batch size). To cope with that for the progress bar, a `count_mode` variable is used to know how to update it.

I would like the `count_mode` variable to also be passed to the callbacks in order for them to also adapt their behaviour based on it.

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
The [`keras-tqdm`](https://github.com/bstriner/keras-tqdm) library is currently [not working properly because of that lack](https://github.com/bstriner/keras-tqdm/issues/37). It could implement a new way to deal with the count, once this variable is provided in the callbacks parameters.

**Comment by shun-lin** [comment]
Hi @zaccharieramzi,

I am the maintainer for [tqdm progress bar](https://github.com/tensorflow/addons/blob/master/docs/tutorials/tqdm_progress_bar.ipynb) in tensorflow addons, does this problem persists with `tfa`'s implementation of tqdm progress bar? Thanks!

**Comment by zaccharieramzi** [comment]
Hi @shun-lin ,

Thanks for the pointer. I have installed `tensorflow-addons` using `pip install tensorflow-addons`. However, when testing with the following code:
```python
import tensorflow_addons as tfa
print(tfa.__version__)
tfa.callbacks.TQDMProgressBar
```

I get the following output:
```
AttributeError                            Traceback (most recent call last)
<ipython-input-1-0c7c9299f697> in <module>
      1 import tensorflow_addons as tfa
      2 print(tfa.__version__)
----> 3 tfa.callbacks.TQDMProgressBar

AttributeError: module 'tensorflow_addons.callbacks' has no attribute 'TQDMProgressBar'
```

Have you had this problem before?

Also, I noticed in the source code that you d[idn't allow a custom metrics formatting](https://github.com/tensorflow/addons/blob/master/tensorflow_addons/callbacks/tqdm_progress_bar.py#L199). [This is available in `keras-tqdm`](https://github.com/bstriner/keras-tqdm/blob/master/keras_tqdm/tqdm_callback.py#L13) and was quite handy for me, I can open an issue and a PR for it if you want.

**Comment by shun-lin** [comment]
Hi!

Can you pip install using this following command?

`!pip install -q --no-deps tensorflow-addons~=0.6`

(without the `!` if in terminal or with `!` if in notebook)
Since I just added the tqdm progress bar callback recently, it will be available with regular `pip install tensorflow addons` in the next release, so now we need to add a bit more flag to as above to install. 
I did not include a custom metrics formatting because I first want to get a minimum working product out to tensorflow addons as their code style is more strict, but if it is useful for you and feel like it will be for others. Feel free to opens an issue in TF Addons and a pull request, thanks for the contribution.

If you still have problem using the pip install command line above, please let me know!

**Comment by rmothukuru** [comment]
@zaccharieramzi,
The code:

```python
import tensorflow_addons as tfa
print(tfa.__version__)
tfa.callbacks.TQDMProgressBar
``` 
works fine now. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/283bbb9237dd959f18922a956f26751e/gh_34417.ipynb) of the working code. Thanks!

**Comment by zaccharieramzi** [comment]
@rmothukuru yes sorry I should have closed the issue a long time ago.
I am using it on a regular basis now without problems.
I think we can close this.
