### ISSUE TITLE
Is it possible to import the project int android Studio and compile using NDK?

### ISSUE THREAD

**Issue by vishnudevk** [tensorflow/tensorflow#3444]
I was trying to import the project into android studio and work on it.
Getting lot of compilation issues on jni compilation.
Is it possible to do that?
Any constraints we have ?

**Comment by andrewharp** [comment]
Hi, I've just given this a whirl and managed to successfully open the Android Tensorflow Demo under Android Studio and build it from there. You'll still need Bazel for building the native libs, but you'll be able to get full Java support through Android Studio.

Some of these steps are shared with
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/README.md, so feel free to skip if you've already done them.

**Instructions:**
Download and install bazel 0.3.0 for your system: https://github.com/bazelbuild/bazel/releases

Download Android NDK r11c and unzip it somewhere:
osx: https://dl.google.com/android/repository/android-ndk-r11c-darwin-x86_64.zip
linux: http://dl.google.com/android/repository/android-ndk-r11c-linux-x86_64.zip

**Clone repo:**
```
git clone --recursive https://github.com/tensorflow/tensorflow/
cd tensorflow
```
now edit tensorflow/WORKSPACE to point to your NDK (SDK should be unnecessary).

**Install Assets for Demo:**
```
wget https://storage.googleapis.com/download.tensorflow.org/models/inception5h.zip -O /tmp/inception5h.zip
unzip /tmp/inception5h.zip -d tensorflow/examples/android/assets/
```

**Build native libs:**
```
CPU=armeabi-v7a
bazel build //tensorflow/examples/android:tensorflow_native_libs --crosstool_top=//external:android/crosstool --cpu=$CPU --host_crosstool_top=@bazel_tools//tools/cpp:toolchain

NATIVE_FOLDER=tensorflow/examples/android/libs/$CPU
andrewharp-macbookpro2:tensorflow andrewharp$ mkdir -p $NATIVE_FOLDER
andrewharp-macbookpro2:tensorflow andrewharp$ cp bazel-bin/tensorflow/examples/android/libtensorflow_demo.so $NATIVE_FOLDER 
```

**Set up the Android Studio project:**
- Open tensorflow/examples/android as "Existing Gradle project" (it's not, but don't worry about that)
- It will detect the AndroidManifest.xml, and ask you to configure. Do so.
- Open "File/Project Structure"
- click "Modules"
- select the Android module
- On the "sources" tab, make sure that res is a resource directory, and src is a source directory.
- On the "Paths" tab, make sure that the paths are set to a directory you want to output to.

**Build the APK**
Under Build, click "Generate Signed APK"

With any luck, this should create a working APK! **You'll need to re-run the "Build Native Libs" instructions any time you modify .cc or .h files**, but you should be able to edit the Java code as you normally would for any other Android project.

In the future we may better support Android Studio with cmake support, so that some of these steps would be unnecessary.

**Comment by andrewharp** [comment]
Just to followup on this, there is now a build.gradle for the Android demo that will automate most of this if you just add the tensorflow/examples/android dir as an existing AS project. You'll still need to have Bazel installed, though.

**Comment by riless** [comment]
Error on Sync build.gradle

`Error:(72, 0) Could not get unknown property 'assembleDebug' for root project 'android' of type org.gradle.api.Project.`

Works fine when I comment the line `assembleDebug.dependsOn copyNativeLibs`

**Comment by andrewharp** [comment]
@riless Seems to be a change/bug in Gradle 2.2: https://code.google.com/p/android/issues/detail?id=219732

A workaround may be to rewrite it as:
```
tasks.whenTaskAdded { task ->
    if (task.name == 'assembleDebug') {
        task.dependsOn 'copyNativelibs'
    }
}
```

**Comment by riless** [comment]
`copyNativeLibs` (with Capital L)

**Comment by codeloverr** [comment]
Can anyone guide me? I want to take the scoreView result as recog.getTitle() in a texview.

**Comment by andrewharp** [comment]
@codeloverr It sounds like you just want to call view.setText(recog.getTitle()). But please direct general Android programming questions to StackOverflow, you'll find better support for that there.
