### ISSUE TITLE
TensorFlow Lite schema updater loses floating-point precision

### ISSUE THREAD

**Issue by vmarkovtsev** [tensorflow/tensorflow#34523]
I am concerned about [tensorflow/lite/schema/upgrade_schema.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/schema/upgrade_schema.py). I see that the schema upgrade is performed by converting flatbuffers binary to JSON and then backward.
However, there is a problem with flatbuffers binary -> JSON step described in https://github.com/google/flatbuffers/issues/5371 which leads to float32 precision loss. `float`-s are serialized as `"0.6f"` and `double`-s as `"0.12d"` (equivalent to C++'s stringstream API). Thus, for example, float32 values that are very small, e.g. `0.123e-6`, will be written as `0.0`.

**Comment by jianlijianli** [comment]
Hi gargn@, could you please help answer this question, it's about conversion between different versions of the schema. Thanks.

**Comment by gargn** [comment]
Reassigning to @aselle who has more context.

**Comment by threebrooks** [comment]
Has there been any movement on this? I ran into this exact problem where the upgrade script actually produced an invalid output tflite file. I use quantized models, and some of the quantization scales were below 10^-6, which got mapped to 0. Apart from the possible loss of accuracy of the model, a quantization scale of 0 can't even be loaded for some platforms because they check for it.

**Comment by aselle** [comment]
@miaout17  could you ptal?
This doesn't seem to be resolved. If flatbuffers doesn't change, I suppose the best thing to do would be to generate python bindings for every version of the schema so that you could programatically move data w/o using json. Of course this is somewhat painful because there has to be more data marshaling (which is why I used the json approach in the first place).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
