### ISSUE TITLE
Batch size reset to 1 after conversion

### ISSUE THREAD

**Issue by antofara** [tensorflow/tensorflow#34620]
**System information**
- OS Platform and Distribution Windows 10 and Ubuntu 64 bit
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): 2.0.0

**Command used to run the converter or code if you’re using the Python API**
```python
x=tf.keras.Input(shape=(256,1), batch_size=50)
y=tf.keras.layers.Convolution1D(kernel_size=5,filters=8,input_shape=(50,256,1))(x)
model=tf.keras.Model(x,y)
# compile and train
# ... 
converter=tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.OPTIMIZE_FOR_SIZE]
converter.inference_input_type = tf.int8
converter.inference_output_type = tf.int8
converter.representative_dataset = setgen
modelq=converter.convert()

conv_interpreter=tf.lite.Interpreter(model_content=modelq)
input_details = conv_interpreter.get_input_details()
```

**The output from the converter invocation**

```
{'name': 'input_5',
 'index': 8,
 'shape': array([   1, 256,    1]),
 'dtype': numpy.float32,
 'quantization': (0.0, 0)}
```

**Failure details**
Despite before conversion the batch size is explicitly set to 50, after conversion the batch size is always 1.
The reason why I am trying to have batch size >1 is because the model has to be executed in the edge TPU and I want to exploit as best the parallelism offered by the chip, thus performing the convolution on as many inputs as possible in parallel.
If not supported by TF Lite, any suggestion to achieve the same result is welcome and appreciated

**Comment by jvishnuvardhan** [comment]
@antofara I ran your code in `tf-nightly` and I see batch_size set as 50. There were lots of improvements recently and team is continuously improving the converter. 

I have also added new experimental new converter as `converter.experimental_new_converter = True`. Please check the gist [here](https://colab.sandbox.google.com/gist/jvishnuvardhan/c7f8adcc2be802258e522540b0c61472/untitled686.ipynb).

Please close the issue if it was resolved for you. Otherwise, please share a colab gist with a standalone code to reproduce the issue. Thanks!

**Comment by antofara** [comment]
Thanks @jvishnuvardhan 
Solved with the following fixes:
TF version: '2.1.0-dev20191204'
converter.experimental_new_converter = True
