### ISSUE TITLE
TFRecordsWriter default write mode?

### ISSUE THREAD

**Issue by qbeer** [tensorflow/tensorflow#34650]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/io/TFRecordWriter

## Description of issue:

So I've been using TFRecordWriter for a while now and I would be interested in the method it writes to files. If I create two TFRecord files with the exact same name what is the default wrtiing option? `append` or `(re)write`? It would be crucial to know this in my use case. Thanks in advance.

**Comment by qbeer** [comment]
All right, just to make sure I iterated over the datafile and I know from statistics what should be the number of records in the TFRecord file:

```python3
sum(1 for _ in dataset)
```

It seems that the default behaviour is `(re)write` so not appending. Can anyone point me to the code where this is actually defined?

**Comment by jsimsa** [comment]
The fact that TFRecordWriter (re)writes (as opposed to appends) is not specified in the documentation of `TFRecordWriter`. 

The Python code that creates the [writer](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/lib/io/tf_record.py#L217) ends up calling into C++ using a generated wrapper, which ends up creating an instance of the following [class](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/python/lib/io/py_record_writer.cc#L30), which ends up using `NewWritableFile` and its [documentation](https://github.com/tensorflow/tensorflow/blob/r2.0/tensorflow/core/platform/file_system.h#L76) specifies the behavior.

Append is not supported out-of-the-box because appending to a compressed file would in general not be possible without first decompressing the file.

**Comment by qbeer** [comment]
Thanks!
