### ISSUE TITLE
Euclidean distance transform add on to support 3D images?

### ISSUE THREAD

**Issue by helwilliams** [tensorflow/tensorflow#34651]
Hello as the euclidean distance transform has been implemented with specific input shapes, I was wondering if this would be expanded to more general shapes. I am currently trying to generate a distance matrix based on 3D ground truth data (i.e. W X H X D) which could easily be 4D  (Batch size x W x H x D). Is this something that would be possible?

**Comment by jaingaurav** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
