### ISSUE TITLE
Docker Image with Python 3?

### ISSUE THREAD

**Issue by drcrook1** [tensorflow/tensorflow#3467]
This is more a feature request.  Any chance we can get support for this?

**Comment by caisq** [comment]
Just to gather more info, are you using the images from docker hub or gcr.io?

**Comment by drcrook1** [comment]
gcr.io I'm also not a docker guru; I'm just trying to get tensor flow operational on my windows machine and have to deal with all sorts of crazy data that comes in; so python 3.5 is nice.  I am trying to use this not only for tensorflow but get a data set in, do my munging with it, then feed it into tensor flow.

**Comment by jonrei** [comment]
+1, would love if it included ipython3 too.
Currently using gcr.io, but could use any source really.

**Comment by lhlmgr** [comment]
Is there an update on this issue? (using the gcr.io - image)

**Comment by javidcf** [comment]
For those willing to look out of gcr.io, there is a Docker image in Docker Hub packing Python 3 Tensorflow (0.10.0rc0 at the time of writing) with IPython notebook installed, pretty much like the supported ones:
https://hub.docker.com/r/erroneousboat/tensorflow-python3-jupyter/

**Comment by tobegit3hub** [comment]
It would be great to sync docker images from gcr.io to docker hub because gcr.io is always blocked in China.

[erroneousboat/tensorflow-python3-jupyter](https://hub.docker.com/r/erroneousboat/tensorflow-python3-jupyter/) is good enough for someone who want to run TensorFlow and Python 3. BTW, installing TensorFlow and building another docker image are not that hard. Just modify the Dockerfile if you want another operation system or dependencies.

**Comment by caisq** [comment]
@tobegit3hub The latest releases are indeed synced to docker hub. So are the nightly builds:
https://hub.docker.com/r/tensorflow/tensorflow/tags/
Are those working for you?

**Comment by tobegit3hub** [comment]
Thanks @caisq and I have test the python3 docker image. It works like a charm with Python 3.4.3 and latest TensorFlow. You can run by `docker run -i -t  tensorflow/tensorflow:nightly-py3 bash`.

![screen shot 2016-12-02 at 09 17 53](https://cloud.githubusercontent.com/assets/2715000/20819590/49d6ed22-b870-11e6-9b20-4c30572a1224.png)

But the binary `python` doesn't exist. It would be better to link `python3` to `python`.

**Comment by caisq** [comment]
@tobegit3hub Good point. I'll incorporate your feedback. I'm working on a pull request to finalize the python3 docker builds: https://github.com/tensorflow/tensorflow/pull/6030

Once the PR is submitted, py3 images will be pushed to docker hub nightly. Release py3 images will be pushed starting from the next release.

**Comment by caisq** [comment]
Fixed by https://github.com/tensorflow/tensorflow/pull/6030
Python-3 docker images are now available in nightly builds.
See: https://hub.docker.com/r/tensorflow/tensorflow/tags/

py3 tags include:
nightly-py3
nightly-devel-py3
nightly-gpu-py3
nightly-devel-gpu-py3

py3 images will also be made available in the next release.

**Comment by dkaberna** [comment]
Can I please ask two questions?
1.) If we built our own custom image, where do we go find it?  Documentation says: "${USER}/tensorflow:latest", but I can't find mine.

2.) When I run parameterized_docker_build.sh, it says 
FAIL: wget http://127.0.0.1:8888/notebooks/*.ipynb

Any ideas how I can troubleshoot this?  Thanks so much.

**Comment by 372046933** [comment]
By the way,  what does devel mean in nightly-devel-gpu-py3? Does it mean development release or this release is for tensorflow development?
