### ISSUE TITLE
tf.map_fn does not execute in parallel

### ISSUE THREAD

**Issue by haideraltahan** [tensorflow/tensorflow#34716]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.0.0
- Python version:
3.7.4
- CUDA/cuDNN version:
10.1/7.6.5
- GPU model and memory:
GTX 1070

**Describe the current behavior**
The [documentation ](https://www.tensorflow.org/api_docs/python/tf/map_fn) for `map_fn` specifies that 

> When executing eagerly, map_fn does not execute in parallel even if parallel_iterations is set to a value > 1. You can still get the performance benefits of running a function in parallel by using the tf.contrib.eager.defun decorator,

However, `tf.contrib.eager.defun` no longer is available in TensorFlow 2.0. Hence, `map_fn` would only run on a single thread. 

How can I parallelize `map_fn ` in TensorFlow 2.0?

**Comment by ravikyram** [comment]
@haideraltahan 

Can you please go through the [link ](https://stackoverflow.com/questions/52774351/how-to-run-parallel-map-fn-when-eager-execution-enabled)and see if it helps you.Thanks!

**Comment by haideraltahan** [comment]
```python
import tensorflow as tf
import time

x = tf.ones(shape=(100,))

def op(i):
    for _ in range(1000):
        i ** 2
    return i
a = time.time()
_ = tf.map_fn(op, x, parallel_iterations=100)
print(f"Sequential : {time.time() - a}s")
# Now wrap tf.map_fn inside tf.function
@tf.function
def my_map(*args, **kwargs):
    return tf.map_fn(*args, **kwargs)

a = time.time()
_ = my_map(op, x, parallel_iterations=100)
print(f"Parallel : {time.time() - a}s")
```

This works for Tensorflow 2.0.
I will update the doc in a PR.

**Comment by jorgeecardona** [comment]
Hi @haideraltahan, testing your code I don't see any big difference when I change the number of iterations from 100 to just 1, I guess then that the difference of execution is because of the call to tf.function and not due to parallelism.  
I added a input_signature to tf.function and increased the size of x and the results don't depend on the parameter parallel_iterations.

How then can I confirm that multiple threads are being used?

In [2]: import tensorflow as tf
   ...: import time
   ...: 
   ...: x = tf.ones(shape=(100,))
   ...: def op1(i):
   ...:     for _ in range(1000):
   ...:         i ** 2
   ...:     return i
   ...: 
   ...: @tf.function
   ...: def op(i):
   ...:     for _ in range(1000):
   ...:         i ** 2
   ...:     return i
   ...: a = time.time()
   ...: _ = tf.map_fn(op1, x, parallel_iterations=100) # this takes ~15 seconds to compute
   ...: print(f"Sequential : {time.time() - a}s")
   ...: 
   ...: a = time.time()
   ...: _ = tf.map_fn(op, x, parallel_iterations=100) # this takes ~1 second to compute
   ...: print(f"Parallel : {time.time() - a}s")

Sequential : 3.5768771171569824s
Parallel : 1.2645704746246338s

In [3]: 

In [3]: import tensorflow as tf
   ...: import time
   ...: 
   ...: x = tf.ones(shape=(100,))
   ...: def op1(i):
   ...:     for _ in range(1000):
   ...:         i ** 2
   ...:     return i
   ...: 
   ...: @tf.function
   ...: def op(i):
   ...:     for _ in range(1000):
   ...:         i ** 2
   ...:     return i
   ...: a = time.time()
   ...: _ = tf.map_fn(op1, x, parallel_iterations=10) # this takes ~15 seconds to compute
   ...: print(f"Sequential : {time.time() - a}s")
   ...: 
   ...: a = time.time()
   ...: _ = tf.map_fn(op, x, parallel_iterations=10) # this takes ~1 second to compute
   ...: print(f"Parallel : {time.time() - a}s")

Sequential : 3.592731237411499s
Parallel : 1.1762580871582031s

In [4]: 

In [4]: import tensorflow as tf
   ...: import time
   ...: 
   ...: x = tf.ones(shape=(100,))
   ...: def op1(i):
   ...:     for _ in range(1000):
   ...:         i ** 2
   ...:     return i
   ...: 
   ...: @tf.function
   ...: def op(i):
   ...:     for _ in range(1000):
   ...:         i ** 2
   ...:     return i
   ...: a = time.time()
   ...: _ = tf.map_fn(op1, x, parallel_iterations=1) # this takes ~15 seconds to compute
   ...: print(f"Sequential : {time.time() - a}s")
   ...: 
   ...: a = time.time()
   ...: _ = tf.map_fn(op, x, parallel_iterations=1) # this takes ~1 second to compute
   ...: print(f"Parallel : {time.time() - a}s")
Sequential : 3.608123302459717s
Parallel : 1.2272813320159912s
