### ISSUE TITLE
Missing information: embedding_lookup automatically returns 0 for an out-of-vocab index

### ISSUE THREAD

**Issue by hoangcuong2011** [tensorflow/tensorflow#34721]
Greetings,

I expected embedding layer gives an error when a word id is beyond the fixed pre-determined vocab size. Nonetheless, it is not the case as tf.nn.embedding_lookup automatically return 0 for an out-of-vocab index. While this is nice, it is risky because there is no information or anything like that from the website https://www.tensorflow.org/api_docs/python/tf/keras/layers/Embedding. I personally did not know that until digging to the code carefully.

So I think more information at the website should be updated.

Example code to see how embedding_lookup returns output:

>>> sess = tf.compat.v1.InteractiveSession()
>>> params = tf.constant([10,20,30,40])
>>> ids = tf.constant([0,1,2,3,4,5])
>>> tf.nn.embedding_lookup(params,ids).eval()
array([10, 20, 30, 40,  0,  0], dtype=int32)

**Comment by lamberta** [comment]
Thanks @hoangcuong2011 . Since you recently investigated, would you be able to make a pull request to update the docstring or add a snippet? That file should be here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/layers/embeddings.py#L35
To add a testable docstring, please see this guide: https://www.tensorflow.org/community/contribute/docs_ref

**Comment by nikitamaia** [comment]
Hi @hoangcuong2011, is this request still relevant? If so are you interested in submitting a PR?
