### ISSUE TITLE
TFLITE C++ 

### ISSUE THREAD

**Issue by thotaram** [tensorflow/tensorflow#34897]
Hi,

We are able to run TFLITE CPP application(label_image) on ARM processor which uses CPU.
Can we run same TFLITE CPP application on any GPU like NVIDIA, POWERVR.

Thanks,
Ram.

**Comment by ravikyram** [comment]
Can you please go through the [link](https://www.tensorflow.org/lite/performance/gpu) and see if it helps you.
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ravikyram** [comment]
@thotaram 

Any update on this issue please. Thanks!

**Comment by thotaram** [comment]
TFLITE C++ application, to run it on GPU(PowerVR) need to use GPU delegate.
When i refer web links regarding GPU delegate it supports Android & IOS.
I would like to know GPU delegate supports for ARM64 platforms or not?
Please suggest any links or inputs to use GPU delegate for ARM.

Thanks,
Ram.

**Comment by impjdi** [comment]
TFLite GPU team officially only supports Android & iOS.  However, Android & iOS are both arm64 architectures.  So if you can get it to compile, it's possible that it runs out of the box.  Of course, your GPU needs to be support OpenGL ES 3.1
