### ISSUE TITLE
Timeline only produced for the last invocation on Session.run

### ISSUE THREAD

**Issue by akors** [tensorflow/tensorflow#3489]
Hi!

First of all, thanks for the great profiling/timeline feature! I think it can be really amazing to debug model performance.

I do have a question though: is it possible to create a timeline for *multiple* invocations of `Session.run`?

In all the examples that I saw, timeline creation looks something along the lines of this:

```
run_options = tf.RunOptions(trace_level=tf.RunOptions.FULL_TRACE)
run_metadata = tf.RunMetadata()

sess.run(result, options=run_options, run_metadata=run_metadata)

tl = timeline.Timeline(run_metadata.step_stats)
ctf = tl.generate_chrome_trace_format()
```

This is all good and well, but this generates the trace only for *one* invocation of Session.run. If it is invoked multiple times (for example in batch training), the `step_stats` in the run_metadata are always overwritten by the last run.

Is there a way to aggregate the timing data to create a timeline that spans over multiple invocations?

I would need this to debug performance decay over long periods.

**Comment by rdadolf** [comment]
Perhaps this is more appropriate for over on stackoverflow, since I'm not sure there's a bug here. But let's discuss anyways. I'm working on performance analysis tools for TF, so I'm interested in your view.

One question is what do you want the behavior to be? If you literally just want a concatenation, one way of doing this is to record both traces and generate a new protobuf with both of their elements. The structure of the RunMetadata protobuf isn't that bad:
[top level](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/config.proto#L224) 
[most everything else](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/step_stats.proto#L29)

It sounds like you want something more intelligent, though. If you're trying to do something like a moving average, you'll need to muck with actual data, and that raises more questions. For instance, how would heterogeneous tensor shapes get handled? (i.e., what if a tensor has different dimensions between two run steps?)

**Comment by akors** [comment]
I started out with the assumption that running the same operation on data of the same shape should take approximately the same amount of time. I have found this to not be true, if you are interested you can take a look at my [StackExchange Thread](http://superuser.com/questions/1086626/machine-performance-drops-over-time-until-reboot). There have also been other [reports](https://github.com/tensorflow/models/issues/170) of slowdowns that might, or might not be related.

My primary goal is to get rid of those slowdowns. If that happens by some magic commit and the problem goes away, that would be very dandy. I'm not very hopeful this will happen though, so I am ready and willing to dig down and debug the issue.

I was hoping that the Timeline thing would be able to help me. I created this issue because I was not sure (and it's not documented anywhere) of what the purpose of the TimeLine object is, and whether it's supposed to be used in only one invocation of Session.run() or multiple ones. Judging from your comment, it's supposed to cover only one invocaton?


> If you literally just want a concatenation, one way of doing this is to record both traces and generate a new protobuf with both of their elements

Is there a somewhat sane python snippet that can do that? If not, I'd prefer not to dig into Protobuf affairs.

> It sounds like you want something more intelligent, though

Not really. The only thing that interests me is why some batches take significantly longer to compute than other batches, and I was hoping that a simple concatenation of the timeline could yield some insight.

**Comment by akors** [comment]
My requirement for an accumulated timeline has dropped (libtcmalloc magic has fixed my slowdown problem), and people seem rather uninterested in the feature, so I would suggest to close the issue.
