### ISSUE TITLE
Saving custom tensor fails

### ISSUE THREAD

**Issue by awav** [tensorflow/tensorflow#34908]
Hello everyone,

There is a bug with saving and loading of custom tensors (variables) in TF. It was discovered at https://github.com/GPflow/GPflow/issues/1127. I have created the MWE in colab [here](https://colab.research.google.com/drive/1REEmDStqGGvl9EmYRa6KB44YXT7EVZkt). There are two errors when `tf.save_model` applies to custom tensors:

* The loading for custom tensor (variable) restores broken tf.Variable object
* Saving of tf.Module with custom tensors (variables) fails

Details in [colab notebook](https://colab.research.google.com/drive/1REEmDStqGGvl9EmYRa6KB44YXT7EVZkt)

PS: referencing @alextp and @dynamicwebpaige, because they know what I mean by custom tensor.

Thanks,
Artem

**Comment by alextp** [comment]
@k-w-w as far as I can tell those module-visible variables should be correctly handled by savedmodel. Do you know what is going on here?

**Comment by awav** [comment]
@k-w-w, @alextp ping ^^^

**Comment by k-w-w** [comment]
This is an interesting use case. SavedModel should be correctly handling this, but we hadn't considered this case yet. I'll see what changes are required to resolve the issue.

**Comment by awav** [comment]
@k-w-w, @alextp any progress on the issue?

**Comment by awav** [comment]
@k-w-w, @alextp ping

**Comment by awav** [comment]
@k-w-w, @alextp Hello! Because of this issue, in [GPflow](https://github.com/GPflow/GPflow) we can't save models. My suspicion that it also affects TensorFlow Probability project. Can you make an update about it? Can you propose any workaround? Can you advise on how we can contribute to TensorFlow to make this work? 
Thanks!

**Comment by awav** [comment]
hello @k-w-w, @alextp! any updates?

**Comment by marcoadurno** [comment]
Hello @k-w-w @alextp , any updates on this?

**Comment by alextp** [comment]
Pinging @rohan100jain for FYI on something that might need a priority bump

**Comment by awav** [comment]
@alextp thanks!

**Comment by nathanhack** [comment]
@alextp any idea when this might be fixed?

**Comment by alextp** [comment]
@ccrusius FYI

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
