### ISSUE TITLE
TF2.0: No way to create local variables in tensorflow 2.0

### ISSUE THREAD

**Issue by x10000year** [tensorflow/tensorflow#35043]
In tensorflow 1.x, user can create local variables, whose lifetime spans over multiple session runs, but will not be saved to checkpoints. Those local variables can be used as internal states of session (e.g., the hidden states of an online rnn). In tensorflow 2.x, session is gone in python side, but when deploy the model in a c++ program we still need to use session, and the local variables can be used to store session states of the model. However, in tensorflow 2.x, there is no standard way to create local variables in python, because all variables created in a Module/Layer are automatically tracked and stored into checkpoints.

**Comment by ravikyram** [comment]
@x10000year 

Can you please help us with the minimal standalone code to reproduce the issue in our environment. It helps us in localizing the issue faster. Thanks!

**Comment by x10000year** [comment]
@ravikyram 

Consider the following TF1.x example code:

# in actual application, we may have many different variables to represent rnn hidden states
state = tf.Variable(
    name='state',
    initial_value = tf.zeros([]),
    trainable=False,
    collections=[tf.GraphKeys.LOCAL_VARIABLES])

# reset the rnn state
init_op = state.assign(0.0, name='init_state')

# update the rnn state. in actual application, it can be one step of a complex rnn model
update_op = state.assign_add(1.0, name='update_state')

After exporting the model, a c++ program can load the model and use init_state and update_state operations to manipulate the hidden state of the model in a session. The state variable is, however, not saved, because it is not the parameter of the model.

In TF2.x, if we implement the model with tf.Module:

class MyModel(tf.Module):
    def __init__():
        self.state = tf.Variable(name='state',
            initial_value = tf.zeros([]),
            trainable=False)
    @tf.function(input_signature=[])
    def init_state():
        self.state.assign(0.0)
    @tf.function(input_signature=[])
    def update_state():
        self.state.assign_add(1.0)

Then self.state will be tracked automatically, and will be saved to SavedModel, which is undesired. The state tensor can be very big in actual application.

**Comment by tianran** [comment]
I just thought about the same thing and found this class attribute from the source code: tf.Module._TF_MODULE_IGNORED_PROPERTIES
Maybe it can solve the problem?

**Comment by rmothukuru** [comment]
@x10000year,
Sorry for the delayed response. Can you please let us know if the [above comment](https://github.com/tensorflow/tensorflow/issues/35043#issuecomment-704214576) has resolved the problem so that we can work towards the closure of this issue? Thanks!

**Comment by mdanatg** [comment]
This issue is being worked on internally, but for now remains unresolved.

For the time being, the best workaround in TF 2 is to avoid the use of `tf.Variable`. That might prove challenging with tf.Module, but applying the tf.function at as high a level as possible might help. For example:

```
class MyModel(tf.Module):
    def __init__():
        self.state = tf.zeros([])

    def init_state():
        self.state = tf.zeros([])

    def update_state():
        self.state += 1

@tf.function
def main():
  m = MyModel
  # all code working on m should be called here
```

Even better, if at all practical for you, pure functional programming patterns are much better supported, where you use plain data structures and plain functions, and all inputs are function arguments and all outputs are return values. So for example:

```
MyData = collections.namedtuple('MyData', ['state'])

def init():
  return MyData(tf.zeros([]))

def update(old_data):
  return MyData(old_data.state + 1)
```

**Comment by tilakrayal** [comment]
@x10000year,
Variable creation is hoisted out of **tf.function** automatically because the common case for variable use is that its state is shared between different traces of the function. The fact that `tf.Variables` do this automatically (as opposed to requiring users to express their intent explicitly via init_scope). AFAIK hoisting the state of **tf.function** makes the lifetime of any such state **global** and I would in general discourage it for `tf.data` objects.

I would recommend that it would be to decouple the problem of returning an iterator out of `tf.function` (without leaking the underlying C++ iterator resource) from the problem of saving a **tf.Module** that contains an iterator.

Also tried to execute the example with the sample code. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/972e2a6a21b9d16c7ef3310059ec6538/untitled1278.ipynb). Thank you!

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request. Thank you!
