### ISSUE TITLE
`tf.vectorized_map` works incorrectly for functions with `tf.stack`

### ISSUE THREAD

**Issue by rrkarim** [tensorflow/tensorflow#35073]
Description of the bug is pretty much in the title, here is the little snippet:

```python
import tensorflow as tf
import tensorflow_probability as tfp

def log_prob(x):
    x = 0 # we don't care about the input tensor
    final_log_probs = [tf.ones(1)]
    concat_log_probs = tf.stack(final_log_probs, 0)
    return concat_log_probs

print(log_prob(tf.ones(1)).shape) # (1,1)

# vectorized function
log_prob = tf.vectorized_map(log_prob, tf.ones(1))
print(log_prob.shape) # (1,1,1)
```
The returning shapes are different for two types of calls. Maybe the behaviour is documented (limit on `tf.stack`) but it seems to be odd for me.

```
tf: 2.0.0
tfp: 0.8.0
```

**Comment by rrkarim** [comment]
I guess the problem is with `is_stacked` flag and the appropriate logic in `*/pfor.py`?

**Comment by agarwal-ashish** [comment]
This looks like the expected behavior. FWIW, replacing vectorized_map with map_fn also gives the same shape.

**Comment by rrkarim** [comment]
Still it is not documented so it makes it unexpected.

**Comment by agarwal-ashish** [comment]
As per documentation, the function returns " A tensor or (possibly nested) sequence of tensors. Each tensor packs the
    results of applying fn to tensors unpacked from elems along the first
    dimension, from first to last."

The idea is that log_prob is applied to each row of your input and the results are stacked together. Since log_prob returns a tensor of rank 2, stacking these results should give rank 3. This has nothing to do with the usage of tf.stack inside your log_prob function or the fact that log_prob's output is independent of the inputs.

Does that help ?

**Comment by rrkarim** [comment]
@agarwal-ashish thanks, yeah, it is much more clear now.
