### ISSUE TITLE
how to convert NonMaxSuppressionV4 to older versions

### ISSUE THREAD

**Issue by shnamin** [tensorflow/tensorflow#35076]
Hi, 
I am training a tensorflow object detection model and am converting it to tensorflow js. Although there is no NonMaxSuppressionV4 in the config.proto file (but has batch_non_max_suppression), I am getting the error 
ValueError: Unsupported Ops in the model before optimization
NonMaxSuppressionV4

when trying to use tensorflowjs_converter to convert the trained model into tensorflow js. Is there a way I can convert my checkpoints into saved_model that doesn't convert nonmaxsuppression to v4 (I think v3 is supported in tensorflowjs)? I am using tensorflow 1.15.0, but back tracking to tensorflow 1.13.0 has not helped either. 

I would appreciate it if someone explains what is happening, or how I can convert the model into supported tensorflow js operators (after creating tensorflowjs with --skip_op_check or before it at the time of model training or exporting it into saved or frozen model)?

Thank you in advance

**Comment by oanush** [comment]
@shnamin ,
This issue is related to Tensorflow.js repo, can you please open issue using this [link](https://github.com/tensorflow/tfjs/issues/new)? Also there are already issue's [2540](
https://github.com/tensorflow/tfjs/issues/2540), [2450](https://github.com/tensorflow/tfjs/issues/2450) being reported for the same refer the same.Thanks!
