### ISSUE TITLE
Why list, dictionary and tuple are taken value vice versa when declare it in one-line?

### ISSUE THREAD

**Issue by Mayurjotaniya3** [tensorflow/tensorflow#35259]
I am feeling very strange when I am working on list, dictionary and tuple in python.

When we declare multiple variables in one line like a = b = c = 0 it behaves like separate variables.

If we are update value any of the above variables then it will not affect another variable like below.

a = 10
b = 11
c = 13
But, this thing is not applying with list, tuple and dictionary. If we declare blank list like below.

a = b = c = []

Now, I am appending the value of only a list.

a.append('Testing')
Now, b and c is automatically assigned that value.

This thing also happens with dictionary and tuple also.

Can anyone please help to solve this issue. Please don't suggest to declare it in a different line.

**Comment by gadagashwini** [comment]
@Mayurjotaniya3, When we declare multiple variables as a list, tuple and dictionary, all the variables shows unique number representing the identity of an object. Unique identity number can be identified using `id` function . 
a=b=c=[]   # a,b,c will have same `id` number.

For more read https://stackoverflow.com/questions/16348815/python-assigning-multiple-variables-to-same-value-list-behavior.

Closing this issue since its not related to Tensorflow. Please feel free to reopen if its Tensorflow issue by providing all the information asked in Template. Thanks!
