### ISSUE TITLE
parallelize OneVsRestClassifier

### ISSUE THREAD

**Issue by rubenstern** [tensorflow/tensorflow#3539]
Hi,

I have implemented a CNN model in a TensorFlowEstimator and I use it with a OneVsRestClassifier.
It works good.
When I am trying to parallelize it by putting n_jobs=2 in the OneVsRestClassifier, I got a strange error that I don't understand : 

MaybeEncodingError: Error sending result: '[TensorFlowEstimator(batch_size=32, class_weight=None, clip_gradients=5.0,
          config=None, continue_training=True, learning_rate=0.001,
          model_fn=<function cnn_model at 0x11f22d500>, n_classes=16,
          optimizer='Adam', steps=200, verbose=1)]'. Reason: 'PicklingError("Can't pickle <type 'module'>: it's not found as **builtin**.module",)'

Do you have an idea of what does it mean ?

Thanks

**Comment by michaelisard** [comment]
@poxvoculi would you take a look?

**Comment by poxvoculi** [comment]
In short, no I don't know just what's going on, but here's what I can deduce, not having much experience with python or the python layer of tensorflow.

This is a python error trickling up, evidently from the python pickle operation which serializes an in-memory object for storage or i/o with another process.  It appears something is unsuccessfully trying to serialize TensorFlowEstimator, which is in contrib.learn.TensorFlowEstimator.  (Maybe this is a result of parallelizing, so now the entire program is being pickled before being transferred to some child processes.)  The python pickling rules described [here](https://docs.python.org/2/library/pickle.html#what-can-be-pickled-and-unpickled) suggest that TensorFlowEstimator should be pickleable, since it's a class at the top level of a module.  Could it be that somehow the way you're running the program, access to that full definition has been lost by the compilation/execution unit that is trying to do the pickle at runtime?

**Comment by michaelisard** [comment]
Sorry I misdirected but thanks @poxvoculi. @ilblackdragon could you have a quick look?

**Comment by rubenstern** [comment]
I'm only running it in the command shell by writing : 
python program.py

So I don't know how to handle the access

**Comment by rubenstern** [comment]
?

**Comment by ilblackdragon** [comment]
The error means that some component inside the object can't be picklable (serializable).
Probably this means the `model_fn` didn't serialize. (I'm not sure because your error doesn't have info about object like this `Can't pickle <function _model_fn at 0x108802140>:`).

Two things:
1) Try using `Estimator`, because `TensorFlowEstimator` is deprecated.
2) You can try to move whatever you passing to `model_fn` into separate module and import it. This may allow to serialize the pointer to function.

If pickling of the `model_fn` function doesn't work, you can always make a wrapper that will do the work of constructing new estimator and returning.

**Comment by rubenstern** [comment]
Thanks
In which library can I find : Estimator ?

**Comment by terrytangyuan** [comment]
@rubenstern `tf.contrib.learn`

**Comment by rubenstern** [comment]
1) and 2) doesn't work : I got the same error.

How can I make a wrapper that will do the work of constructing new estimator and returning ?

**Comment by ilblackdragon** [comment]
You can serialize params / arguments you pass to `Estimator` and then just re-create object by passing arguments again.

**Comment by drpngx** [comment]
Marking as fixed. Thanks @ilblackdragon !
