### ISSUE TITLE
tensorflowlib for 2.0

### ISSUE THREAD

**Issue by Dave-Stein** [tensorflow/tensorflow#35405]
I can see many users over the last 2 weeks struggling with getting the build to work with Windows 10. I also see a few **recent commits** to improve the build in response to the above feedback.

As [stated here](https://www.tensorflow.org/install/source_windows) that the Windows tensorflow 2.0 builds with following configurations are successful.

![image](https://user-images.githubusercontent.com/59223977/71443261-34f74d00-270a-11ea-8cc5-ee2902f336b8.png)
![image](https://user-images.githubusercontent.com/59223977/71443269-44769600-270a-11ea-8857-750f7f3598ee.png)

Please **update** [the links](https://www.tensorflow.org/install/lang_c) here with the successful windows tensorflow 2.0 builds provided above 

For example: we need
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-cpu-windows-x86_64-2.0.0.zip
https://storage.googleapis.com/tensorflow/libtensorflow/libtensorflow-gpu-windows-x86_64-2.0.0.zip

_Although these tentative builds are old_, but it will provide a starting point **to start TESTING the Tensorflow 2.0 features through bindings.**

**Comment by Dave-Stein** [comment]
[Community effort](https://github.com/guikarist/tensorflow-windows-build-script/issues/38#issue-513074418)

**Comment by ravikyram** [comment]
@Dave-Stein 

Please, have a look at the note mentioned in the [link ](https://www.tensorflow.org/install/lang_c).As stated it can be included in the future releases.Thanks!

**Comment by GeorgeS2019** [comment]
@ravikyram I read with excitement of the latest features of tensorflow 2.0. With all the problems users here feedback regarding building tensorflow 2.0, we would like to see a commitment to Windows platform. We need soon the compiled version of tensorflowlib 2.0.0. We understand that perhaps we may need to wait for tensorflow 2.1, we are curious to compare tensorflowlib 1.15 and 2.0.0. 

==> please try your best to make tensorflowlib 2.0.0 available!

**Comment by GeorgeS2019** [comment]
Tracking challenges in compiling for windows
[Case1](https://github.com/tensorflow/tensorflow/issues/35977#issue-551290058)

**Comment by GeorgeS2019** [comment]
@ravikyram @gunan  any update to [this](https://www.tensorflow.org/install/lang_c) for 2.0?

**Comment by Dave-Stein** [comment]
Update after 3 months
Tensorflow2.2 for windows
[Case 1](https://github.com/tensorflow/tensorflow/issues/39905)

**Comment by Dave-Stein** [comment]
https://joe-antognini.github.io/machine-learning/build-windows-tf

**Comment by heyufei2008** [comment]
Are we going to have an official fix for the windows linking symbols issue ? Adding TF_EXPORT does not seem to be a solid solution, you have a big chance to miss some functions.
I'm struggling on how to fix the tensorflow::op::Cast class.

//////////////////////////////////////////
auto uint8Caster = Cast(root.WithOpName("uint8_Cast"), outTensor, tensorflow::DT_UINT8);

But Cast class is defined in math_ops.h, which is "// This file is MACHINE GENERATED! Do not edit."

How to add TF_EXPORT to class Cast ?
///////////////////////////////////////////

**Comment by gunan** [comment]
@av8ramit @bmzhao is working to fix libtensorflow releases.
As mentioned in other issues, owners of our C++ APIs have left, and now we are ramping up on the releases, moving them to 2.0, and cleaning up stale build scripts all at the same time. This is taking some time, thus the delay. Moreover, we have lost multiple people with windows expertise, so that has been quite difficult for us to ramp up as well.

**Comment by Dave-Stein** [comment]
We need to invite more discussion on the future of WINDOW support for tensorflow.  6 months with no progress but challenges. **Google needs to hire those WHO CLIAM HERE are able to address these challenges IMMEDIATELY.**

**Comment by heyufei2008** [comment]
@gunan 
Hi Gunan

If you need more people to work on windows, maybe I can help, I've been working on windows more than 10 years.

**Comment by gunan** [comment]
@heyufei2008 Thank you for your offer to help.
We are working through the backlog, however we welcome any contributions, if you like to help!

**Comment by heyufei2008** [comment]
@gunan  Great. how can I start work on some issues? I need some basic introductions or document  to get my hands in. Thanks.

**Comment by gunan** [comment]
To get started, you can go over our guide to build TF from sources here:
https://www.tensorflow.org/install/source_windows
While I know that the guide is for python, the C++ library builds the same code with a different build target (tensorflow:tensorflow, I think)

Also, this is a great community effort, I recommend reading this as well:
https://github.com/sitting-duck/stuff/tree/master/ai/tensorflow/build_tensorflow_1.14_source_for_Windows 

And finally, @av8ramit can help with the mechanisms we use for exporting c++ symbols from our shared objects

**Comment by heyufei2008** [comment]
@gunan 
Thanks.

**Comment by av8ramit** [comment]
We are also building nightly libtensorflow packages. Please pardon the difficult browser navigation, but they can be found in the `libtensorflow-nightly` GCS bucket [here](https://storage.googleapis.com/libtensorflow-nightly). They are listed by operating system. The directories correspond to the date they were built. We will also be publishing official binaries along with additional instructions on tensorflow.org as a part of the 2.3 release.

**Comment by av8ramit** [comment]
As for how we export shared object symbols on Windows, that depends. For exporting a symbol from a dependency in [pywrap_tensorflow](https://github.com/tensorflow/tensorflow/blob/492bb4d4a3fd5aafae620d2b4db1535b2d4f4a7b/tensorflow/python/BUILD#L5985), we would request that you add them to [this file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/def_file_filter/symbols_pybind.txt) and add the target [here](https://github.com/tensorflow/tensorflow/blob/492bb4d4a3fd5aafae620d2b4db1535b2d4f4a7b/tensorflow/python/BUILD#L6049) as we have a script that exposes the mangled symbol from the larger shared object. For smaller standalone shared objects, using pybind11 and creating a standalone `pybind_extension` invocation should be enough.

**Comment by heyufei2008** [comment]
@av8ramit 
Thanks.

Can you give me an example showing how to change  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/def_file_filter/symbols_pybind.txt

and how to change https://github.com/tensorflow/tensorflow/blob/492bb4d4a3fd5aafae620d2b4db1535b2d4f4a7b/tensorflow/python/BUILD#L6049

I need to export symbol for this:

//////////////////////////////////////////
auto uint8Caster = Cast(root.WithOpName("uint8_Cast"), outTensor, tensorflow::DT_UINT8);

But Cast class is defined in math_ops.h, which is "// This file is MACHINE GENERATED! Do not edit."

How to add TF_EXPORT to class Cast ?
///////////////////////////////////////////

**Comment by av8ramit** [comment]
Ah my apologies, I missed your previous message. Unfortunately since that is autogenerated, the suggestion I provided will not apply. That suggestion is for explicitly defined functions. [Here](https://github.com/tensorflow/tensorflow/commit/9d41ea557a79e33c5c766b075d307501acd2265b#diff-145ec99c6d4762e904542472583a3fb1) is an example.


Let me dig into this a bit more and get back to you tomorrow.

**Comment by GeorgeS2019** [comment]
> the `libtensorflow-nightly` GCS bucket [here](https://storage.googleapis.com/libtensorflow-nightly).

@av8ramit  Finally, something that we all have been looking for.

**Comment by gunan** [comment]
I would like to remind everyone that TensorFlow is an open source project.
While we do our best to provide many features, the community is more than welcome to contribute and fill those gaps.
We have been lacking windows expertise for a long time. This is no secret. So we depend on everyone here to work with us, and fill the gaps where we fall short.

**Comment by GeorgeS2019** [comment]
@gunan @av8ramit   I have followed discussions between SciSharp and tensorflow team.
The team is currently offering tensorflow.dll (CPU), Now we have the GPU version.
From the ongoing work. it is increasing clear that we need MORE than this binary eventually. We need to contribute to the source code that create the tensorflow.dll so that SciSharp team has more control on what are being exposed for the .NET community.

TODAY is a NEW beginning!

**Comment by heyufei2008** [comment]
@av8ramit Thanks for your information.
def_file_filter is very complicated, I don't know how it works.
Can you tell me how to change it so that I can do this ? 
//////////////////////////////////////////
auto uint8Caster = Cast(root.WithOpName("uint8_Cast"), outTensor, tensorflow::DT_UINT8);
//////////////////////////////////////////

Another way: Can I build a static library instead of a dll ? Static tensorflow library is ok for me, then we can bypass the issue of limited export symbol in windows.

Thanks.
John

**Comment by av8ramit** [comment]
Unfortunately I'm not too familiar with Windows def files either. I think you need to copy the def file target we have currently given to libtensorflow_cc and then create a new one with the cc_library target that contains the `uint8Caster`. 

I'm not sure about the static library, but if that bypasses the limited export issue, it could work.

**Comment by heyufei2008** [comment]
@av8ramit I did some test following your message, but failed to make it work.
I'm doing object detection, "auto uint8Caster = Cast(root.WithOpName("uint8_Cast"), outTensor, tensorflow::DT_UINT8);" is a must to me.

Please give me more help on this.

Thanks.

**Comment by av8ramit** [comment]
So you created a new def file target applied it to the libtensorflow_cc and tried building a new shared object? What was the issue you saw?

**Comment by heyufei2008** [comment]
@av8ramit Hi Amit
First, according to this in build file:
tf_cc_shared_object(
    name = "tensorflow_cc",
    linkopts = select({
        "//tensorflow:macos": [
            "-Wl,-exported_symbols_list,$(location //tensorflow:tf_exported_symbols.lds)", 
I added one line in tf_exported_symbols_lds.
{
*tensorflow*
*toco*
*perftools*gputools*
*tf_*
*TF_*
*TFE_*
*nsync_*
*stream_executor*
*Cast*     // I added.
}

Nothing changed.

then I add these lines to def_file_filter.py.tpl:

@@ -214,6 +215,9 @@ def main():
      def_fp.write("LIBRARY " + args.target + "\n")
    def_fp.write("EXPORTS\n")
    def_fp.write("\t ??1OpDef@tensorflow@@UEAA@XZ\n")
    def_fp.write("\t ??0Cast@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@W4DataType@2@@z\n")
    def_fp.write("\t ??0Div@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@1@Z\n")
    def_fp.write("\t ??0Subtract@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@1@Z\n")	

Then it says: can not find Cast()...

**Comment by heyufei2008** [comment]
libtensorflow_cc.dll.exp : error LNK2001: unresolved external symbol "??0Cast@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@W4DataType@2@@z" (??0Cast@ops@tensorflow@@QEAA@AEBVScope@2@VInput@2@W4DataType@2@@z)
bazel-out\x64_windows-opt\bin\tensorflow\tensorflow_cc.dll : fatal error LNK1120: 1 unresolved externals
Target //tensorflow:tensorflow_cc.lib failed to build
INFO: Elapsed time: 97.091s, Critical Path: 47.80s
INFO: 0 processes.
FAILED: Build did NOT complete successfully

**Comment by av8ramit** [comment]
@Hey @heyufei2008 

So `tf_exported_symbols.lds` is only applied for MacOS builds as seen in [this line](https://github.com/tensorflow/tensorflow/blob/c41f4652b45bf70f20686e612b41574b4b8139d7/tensorflow/BUILD#L758).  `def_file_filter.py.tpl` has filters to expose symbols, but those symbols need to come from somewhere. And that filter is applied to what comes from the `        "//tensorflow:windows": ":tensorflow_filtered_def_file",` target. So you need to create similar logic.

As you go down the path reverse engineering that target you'll create a dependency similar to [this one](https://github.com/tensorflow/tensorflow/blob/de0a617f4ef321ebf579a4539cec85690f55fb4c/tensorflow/tensorflow.bzl#L1804-L1813). In that target you'll need to add the cc_library where the symbol you want to expose will be defined.

**Comment by jeffhwang02** [comment]
Until tf1.10 version with cmake tool, there is no such issue. Please let me know how to export all cc_api in tensorflow.dll by bazel too?

**Comment by GeorgeS2019** [comment]
@av8ramit @gunan 

> I would like to remind everyone that TensorFlow is an open source project.
> While we do our best to provide many features, the community is more than welcome to contribute and fill those gaps.

Your opinions on setting up this repo for C# API to tensorflow.dll
[https://github.com/tensorflow/csharp](https://github.com/tensorflow/tensorflow/pull/38027#issuecomment-606736249)

With this, we can mobilize .NET C# tensorflow api developers to contribute on regular basis

**Comment by gunan** [comment]
@GeorgeS2019 Please avoid adding unnecessary and unrelated comments on different issues. This will not bring extra attention to any issues. Moreover, it further causes extra delays for us, trying to check if these are connected, and wastes our time.

About csharp, You may want to start a thread in developers@tensorflow.org.
If there is enough interest, it may happen.

**Comment by heyufei2008** [comment]
@gunan  My issue is still not solved.

**Comment by gunan** [comment]
@heyufei2008 I am aware. Have you tried the suggestion in https://github.com/tensorflow/tensorflow/issues/35405#issuecomment-646306403 ?

**Comment by GeorgeS2019** [comment]
> About csharp, You may want to start a thread in developers@tensorflow.org.
If there is enough interest, it may happen.

@gunan  thx for suggestion.  Not trying to create confusion, BUT to bring developers interested on .NET into ONE common thread.  As u suggested, the new focus => For anyone interested to contribute to **Tensorflow.NET**<= will be **developers@tensorflow.org.**

**Comment by omatai** [comment]
> 
> 
> I would like to remind everyone that TensorFlow is an open source project.
> While we do our best to provide many features, the community is more than welcome to contribute and fill those gaps.
> We have been lacking windows expertise for a long time. This is no secret. So we depend on everyone here to work with us, and fill the gaps where we fall short.

I think it would help to start with the documentation, and make a quick note of the status of (1) building from source on Windows and (2) the intended way to use the C++ API (and other APIs?) (i.e. does it require building from source? Static libraries? Dynamic libraries? Direct integration of source?). I have been struggling for days to understand the status of building on Windows because the documentation is sparse to say the least. I'm extremely reluctant to edit the documentation myself (extremely unfamiliar with git; extremely lost with regard to building on windows...) so have tried to raise the issue [here](https://github.com/tensorflow/tensorflow/issues/43519)

Meanwhile, my current aim as an exercise in understanding the process is to create a "hello ML world" program in C++ for Windows desktop (console application). The intent is to invoke "helloML image.jpg" where "image.jpg" contains an image of a hand-written digit. The output should say something like "hello ML world! The image contained the digit 7" or whatever.

I will document that process as I go, and aim to make the result available as a tutorial.

**Comment by GeorgeS2019** [comment]
@gunan @av8ramit   @omatai 

I would argue that the support we get from tensorflowlib 2.x has improved a great deal.

The [sharing](https://github.com/tensorflow/tensorflow/issues/35405#issuecomment-641619156) of the [nightly built link](https://storage.googleapis.com/libtensorflow-nightly) has made a GREAT impact to the Tensorflow.NET and tensorflowSharp communities. 

Tensorflow.NET and Csharp wrapper support are now more recognized than before. 

I do not denied there is still room for improvement, especially on the documentation and consistent build scripts for Windows.

Suggestions

1. We need to setup a consensus format no the Tensorflow C Api Unit tests so that e.g. the Tensorflow.NET community can parse the C Api unit tests to automatically generate the C# version of the binding codes to the C API. 

Right now, the tensorflow team is dong such an incredible GOOD JOB that it is getting more and more challenging to keep up by e.g. C# Tensorflow.NET community.  We are severely behind with code coverage of the C Api unit tests with C# wrappers. 

I need suggestion from the Tensorflow team how we could collaborate to sort out a more Parser friendly format of the tensorflow C API so that the Tensorflow.NET community has a better chance of automatically generate the code skeleton framework to be UP-TO-DATE with each release of the tensorflow C API. 

2. We also hope the tensorlfow team can keep up with the documentation of the C API within the code to make it easy to port those documentation to the C# equivalent. 

Porting the C unit test code will still need to be done manually. However, to get **MORE WINDOW SUPPORT** (see below) to keep up with the speed that tensorlfow team is progressing, we need a C# overview of tensorflow C API code coverage to coordinate among the C# tensorflow.NET community to coordinate the porting of the C API. 

> I would like to remind everyone that TensorFlow is an open source project.
While we do our best to provide many features, the community is more than welcome to contribute and fill those gaps.
We have been lacking windows expertise for a long time. This is no secret. So we depend on everyone here to work with us, and fill the gaps where we fall short.

3. The more the Tensorflow.NET community is able to keep up to date with those tensorflow C API, the more engagement we can expect from the Windows Community. 

Please advice how best to proceed with an Agreeable C API unit test format that will be a WIN WIN for other community like Tensorflow.NET and the fast moving tensorflow team.

**Comment by GeorgeS2019** [comment]
@gunan @av8ramit I would like to feedback that the level of effort the Tensorflow.NET team invested into the tensorflow C API unit tests is probably more comprehensive than that of the tensorflow Java wrapper project. 

In other words, the Tensorflow.NET initiative is getting serious and on par, more and more in my view, catching up to e.g. Tensorflow Java wrapper project.

**Comment by av8ramit** [comment]
I think the [SIG Build](https://groups.google.com/a/tensorflow.org/forum/#!forum/build) would be a better forum to discuss these gaps, reach out for community feedback, and see how we can proceed going forward.

**Comment by omatai** [comment]
Here's my real experience: I started with Tensorflow 2+ years ago on version 1.5. I could not understand it, but it worked. But since I could not understand it, I could not modify it. So I was forced to mothball it. I returned to Tensorflow about 6 months ago. This time with Keras, I could understand it, but I could not make it work. Most of the inability to make it work rested with the documentation.

Finally, after relegating TF to something that only justified 2-3 hours per week attention because the investment in it promised so little payback, we got it to work, and wanted to integrate the network we had trained in C++ on Windows in a desktop application. That was mid last week.

I have subsequently spent 3 solid days trying to work out how to progress past that point. My assessment: the documentation needs priority, because the signal-to-noise in the alternatives to the documentation (github issues, stackoverflow) is so low as to reinforce our original assessment that TF should be set aside completely.

And yet it would have only taken 1 paragraph of documentation to change that 3 solid days of angst and confusion to an acceptable rate of progress. The paragraph:

To use the Tensorflow API in a <x> application, typically you will need to build a Tensorflow library for <x> from the source. In certain cases, there may be pre-compiled libraries available. Please see the Tensorflow install instructions for your platform. Those instructions are directed towards building a pip installation package. You should instead direct the bazel build process to produce the library you require. For example, to build a library for a Windows C++ application, you should invoke: bazel build --config=opt //tensorflow:tensorflow.dll

That paragraph would have saved me 2.5 days. That is typical of our experience with tensorflow - it is a slow death by a thousand paper cuts.

The build process is actually fine - once I knew what to do (2.5 days late) it ran smoothly without issue. But understanding what to build is a nightmare that could be dramatically simplified with some simple documentation changes.

I'm about to try to integrate the library/DLL I have produced into a hello world program. Normally I would expect to complete that within an hour. Based on some months of experience with Tensorflow, I would expect it to take several days. I'll let you know how long it actually takes.

**Comment by GeorgeS2019** [comment]
> I think the SIG Build would be a better forum to discuss these gaps, reach out for community feedback, and see how we can proceed going forward.

@av8ramit   => thanks for the right next step to proceed. 👍

**Comment by GeorgeS2019** [comment]
@av8ramit 

Here to update [the formation of the Tensorflow.NET SIG](https://github.com/tensorflow/community/pull/337) to serve the TensorFlow .NET community that there will be commitment to work with tensorflow SIG Build to ensure up-to-date to what have been and what have not been implemented (both API and Unit Tests) with respect to the latest changes/commits of tesnsorflow  c API and c API tests

**Comment by omatai** [comment]
In case anyone was waiting to know how long it took me to integrate TensorFlow into a Windows C++ application... the answer is an infinite amount of time - we gave up :-(

For anyone else wanting to proceed down the same path, I suggest that you are better off at present converting your TF model into an ONNX model, and then using Windows ML (potentially slow, despite using Onnx Runtime ) or Onnx Runtime itself, or DirectML if every millisecond matters.

**Comment by mohantym** [comment]
Hi @Dave-Stein! Could you please check on latest stable version of TF 2.6 and the instructions at this[ link ](https://www.tensorflow.org/install/lang_c)for installing Tensorflow in windows from Source. let us know if this is still an issue.Thanks!

**Comment by GeorgeS2019** [comment]
@mohantym   if you check the feedback here, most have given up. With LibTorch, we have a reliable VS2019 project solutions to iteratively integrate LibTorch for .NET community.  I went through the link. It seems to focus on Python and not c++ Tensorflowlib build. Please engage further improvement.
