### ISSUE TITLE
import frozen graph with error "Input 0 of node X was passed float from Y:0 incompatible with expected float_ref

### ISSUE THREAD

**Issue by MachineJeff** [tensorflow/tensorflow#35406]
It's the same problem with [this early issue](https://github.com/onnx/tensorflow-onnx/issues/77)

However I can not solve this problem like it.

Bacause there is no "Ref" node and "AssignSub" node and "AssignAdd" node in my pb file.

```bash
Input 0 of node MelGAN/Generator/Generator_1thconv1d/weight_norm/Assign was passed float from MelGAN/Generator/Generator_1thconv1d/group__conv1d/g:0  incompatible with expected float_ref
```

My pb file is in [my repository](https://github.com/MachineJeff/BUG)

And the "print node" code is also in there.

Who can help me ?

**Comment by gadagashwini** [comment]
@MachineJeff, The my repository link is not working. Please provide the correct link. 
Please provide the information asked in  issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by MachineJeff** [comment]
I have solved it by myself, thanks! @gadagashwini

**Comment by chunchunya** [comment]
> 
> 
> I have solved it by myself, thanks! @gadagashwini

How do you solve it? I have the similar question with you,could you please tell me some solution? Thanks!
