### ISSUE TITLE
no such package '@com_google_protobuf error while running bazel build

### ISSUE THREAD

**Issue by 4dcity** [tensorflow/tensorflow#35414]
**System information**
- OS Platform and Distribution: Windows10 x64
- TensorFlow installed from: binary
- TensorFlow version: 1.15.0
- Python version: 3.7
- Installed using: conda
- Bazel version (if compiling from source): 1.1/2.0
- CUDA/cuDNN version: 10.0

I was trying to inspect a model following the guide [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/graph_transforms/README.md#inspecting-graphs)
When running the command
```bash
bazel build tensorflow/tools/graph_transforms:summarize_graph
```
it failed with these logs
```
INFO: Writing tracer profile to 'C:/users/yy/_bazel_yy/zxtlmlwl/command.profile.gz'
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=120
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/YY/Anaconda3/python.exe
INFO: Reading rc options for 'build' from e:\tensorflow\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --enable_platform_specific_config --config=v2
INFO: Found applicable config definition build:v2 in file e:\tensorflow\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file e:\tensorflow\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --incompatible_windows_native_test_wrapper --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file e:\tensorflow\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at E:/tensorflow/tensorflow/third_party/repo.bzl:121:19):
 - E:/tensorflow/tensorflow/tensorflow/workspace.bzl:457:5
 - E:/tensorflow/tensorflow/WORKSPACE:19:1
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash 'b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "E:/tensorflow/tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(2) when executing 'C:\Windows\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/yy/_bazel_yy/zxtlmlwl/external/com_google_protobuf" "-i" "E:/tensorflow/tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: patch: **** Can't change to directory C:/users/yy/_bazel_yy/zxtlmlwl/external/com_google_protobuf : No such file or directory
ERROR: Analysis of target '//tensorflow/tools/graph_transforms:summarize_graph' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "E:/tensorflow/tensorflow/third_party/repo.bzl", line 101
                _apply_patch(ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "E:/tensorflow/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(2) when executing 'C:\Windows\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/yy/_bazel_yy/zxtlmlwl/external/com_google_protobuf" "-i" "E:/tensorflow/tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: patch: **** Can't change to directory C:/users/yy/_bazel_yy/zxtlmlwl/external/com_google_protobuf : No such file or directory
INFO: Elapsed time: 3.975s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)
    currently loading: tensorflow
```

I've tried diferent versions of bazel, 0.20, 1.1.0, and 2.0.0，and ```bazel clean```, the error is still there.
What makes me confused is that the " Can't change to directory C:/users/yy/_bazel_yy/zxtlmlwl/external/com_google_protobuf : No such file or directory", which in fact I can find the dir at that path

I've checked other similar issue, but none can fix this error

**Comment by kelvinxuande** [comment]
Same issue: tf version 2, Bazel version 0.29.1

`INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=135
INFO: Reading rc options for 'build' from c:\users\user\desktop\tensorflow\.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Options provided by the client:
  'build' options: --python_path=C:/Users/user/AppData/Local/Programs/Python/Python37-32/python.exe
INFO: Reading rc options for 'build' from c:\users\user\desktop\tensorflow\.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --action_env=TF_ENABLE_XLA=1 --define=with_xla_support=true --enable_platform_specific_config --config=v2
INFO: Found applicable config definition build:v2 in file c:\users\user\desktop\tensorflow\.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:windows in file c:\users\user\desktop\tensorflow\.bazelrc: --copt=/w --copt=/D_USE_MATH_DEFINES --cxxopt=/std:c++14 --host_cxxopt=/std:c++14 --config=monolithic --copt=-DWIN32_LEAN_AND_MEAN --host_copt=-DWIN32_LEAN_AND_MEAN --copt=-DNOGDI --host_copt=-DNOGDI --linkopt=/DEBUG --host_linkopt=/DEBUG --linkopt=/OPT:REF --host_linkopt=/OPT:REF --linkopt=/OPT:ICF --host_linkopt=/OPT:ICF --experimental_strict_action_env=true --verbose_failures --distinct_host_configuration=false
INFO: Found applicable config definition build:monolithic in file c:\users\user\desktop\tensorflow\.bazelrc: --define framework_shared_object=false
INFO: Build option --cxxopt has changed, discarding analysis cache.
INFO: Call stack for the definition of repository 'com_google_protobuf' which is a tf_http_archive (rule definition at C:/users/user/desktop/tensorflow/third_party/repo.bzl:134:19):
 - C:/users/user/desktop/tensorflow/tensorflow/workspace.bzl:480:5
 - C:/users/user/desktop/tensorflow/tensorflow/workspace.bzl:480:5
 - C:/users/user/desktop/tensorflow/WORKSPACE:26:1
INFO: Repository 'com_google_protobuf' used the following cache hits instead of downloading the corresponding file.
 * Hash 'b9e92f9af8819bbbc514e2902aec860415b70209f31dfc8c4fa72515a5df9d59' for https://storage.googleapis.com/mirror.tensorflow.org/github.com/protocolbuffers/protobuf/archive/310ba5ee72661c081129eb878c1bbcec936b20f0.tar.gz
If the definition of 'com_google_protobuf' was updated, verify that the hashes were also updated.
ERROR: An error occurred during the fetch of repository 'com_google_protobuf':
   Traceback (most recent call last):
        File "C:/users/user/desktop/tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/user/desktop/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "C:/users/user/desktop/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(2) when executing 'C:\WINDOWS\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/user/_bazel_user/e7jbxsyy/external/com_google_protobuf" "-i" "C:/users/user/desktop/tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: patch: **** Can't change to directory C:/users/user/_bazel_user/e7jbxsyy/external/com_google_protobuf : No such file or directory
ERROR: Analysis of target '//tensorflow/lite/tools/benchmark:benchmark_model' failed; build aborted: no such package '@com_google_protobuf//': Traceback (most recent call last):
        File "C:/users/user/desktop/tensorflow/third_party/repo.bzl", line 110
                _apply_patch(ctx, <1 more arguments>)
        File "C:/users/user/desktop/tensorflow/third_party/repo.bzl", line 68, in _apply_patch
                _execute_and_check_ret_code(ctx, <1 more arguments>)
        File "C:/users/user/desktop/tensorflow/third_party/repo.bzl", line 52, in _execute_and_check_ret_code
                fail(<1 more arguments>)
Non-zero return code(2) when executing 'C:\WINDOWS\system32\bash.exe -l -c "patch" "-p1" "-d" "C:/users/user/_bazel_user/e7jbxsyy/external/com_google_protobuf" "-i" "C:/users/user/desktop/tensorflow/third_party/protobuf/protobuf.patch"':
Stdout:
Stderr: patch: **** Can't change to directory C:/users/user/_bazel_user/e7jbxsyy/external/com_google_protobuf : No such file or directory
INFO: Elapsed time: 65.300s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (1 packages loaded, 0 targets configured)
    currently loading: tensorflow`

**Comment by Hyvok** [comment]
I have this exact same issue with Tensorflow 2.0 and bazel 2.0.0. The directory in question seems to exist.

**Comment by ruddyscent** [comment]
I have the same issue with TensorFlow on the master branch and bazel 2.0.0 on Windows 10 Pro 1909.

**Comment by ruddyscent** [comment]
It seems that we should use a directory path scheme in bash. For example, '/mnt/c/Users/...' instead of 'C:/users/...' Then, I got the following output:
```
patching file BUILD
Hunk #2 succeeded at 208 (offset -1 lines).
Hunk #3 succeeded at 219 (offset -1 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file protobuf.bzl
```

**Comment by ruddyscent** [comment]
> I have the same issue with TensorFlow on the master branch and bazel 2.0.0 on Windows 10 Pro 1909.

It seems that we should use a path scheme in bash. For example, '/mnt/c/Users/...' instead of 'C:/users/...' Then, I got the following output:
```
patching file BUILD
Hunk #2 succeeded at 208 (offset -1 lines).
Hunk #3 succeeded at 219 (offset -1 lines).
(Stripping trailing CRs from patch; use --binary to disable.)
patching file protobuf.bzl
```

**Comment by ruddyscent** [comment]
> > I have the same issue with TensorFlow on the master branch and bazel 2.0.0 on Windows 10 Pro 1909.
> 
> It seems that we should use a path scheme in bash. For example, '/mnt/c/Users/...' instead of 'C:/users/...' Then, I got the following output:
> 
> ```
> patching file BUILD
> Hunk #2 succeeded at 208 (offset -1 lines).
> Hunk #3 succeeded at 219 (offset -1 lines).
> (Stripping trailing CRs from patch; use --binary to disable.)
> patching file protobuf.bzl
> ```

The following is my ad-hoc patches to this problem. 
```
diff --git a/third_party/py/python_configure.bzl b/third_party/py/python_configure.bzl
index 6e9a22f806..481e42c93d 100644
--- a/third_party/py/python_configure.bzl
+++ b/third_party/py/python_configure.bzl
@@ -133,6 +133,7 @@ def _get_python_lib(repository_ctx, python_bin):
 def _check_python_lib(repository_ctx, python_lib):
     """Checks the python lib path."""
     cmd = 'test -d "%s" -a -x "%s"' % (python_lib, python_lib)
+    cmd = cmd.replace("C:/Users", "/mnt/c/Users")
     result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
     if result.return_code == 1:
         auto_config_fail("Invalid python library path: %s" % python_lib)
@@ -140,6 +141,7 @@ def _check_python_lib(repository_ctx, python_lib):
 def _check_python_bin(repository_ctx, python_bin):
     """Checks the python bin path."""
     cmd = '[[ -x "%s" ]] && [[ ! -d "%s" ]]' % (python_bin, python_bin)
+    cmd = cmd.replace("C:/Users", "/mnt/c/Users")
     result = raw_exec(repository_ctx, [get_bash_bin(repository_ctx), "-c", cmd])
     if result.return_code == 1:
         auto_config_fail("--define %s='%s' is not executable. Is it the python binary?" % (
diff --git a/third_party/repo.bzl b/third_party/repo.bzl
index a4d2b899f8..aaba57e37a 100644
--- a/third_party/repo.bzl
+++ b/third_party/repo.bzl
@@ -26,7 +26,7 @@ def _wrap_bash_cmd(ctx, cmd):
         bazel_sh = _get_env_var(ctx, "BAZEL_SH")
         if not bazel_sh:
             fail("BAZEL_SH environment variable is not set")
-        cmd = [bazel_sh, "-l", "-c", " ".join(["\"%s\"" % s for s in cmd])]
+        cmd = [bazel_sh, "-l", "-c", " ".join(["\"%s\"" % s for s in cmd]).replace("C:/users", "/mnt/c/Users")]
     return cmd

 def _get_env_var(ctx, name):
```
And I faced another kind of problem. Not sure that it is related to the original problem or above patches:
```
INFO: Analyzed target //tensorflow/tools/graph_transforms:transform_graph (142 packages loaded, 8410 targets configured).
INFO: Found 1 target...
INFO: Deleting stale sandbox base C:/users/ruddy/_bazel_ruddy/tkn72bxt/sandbox
ERROR: C:/users/ruddy/_bazel_ruddy/tkn72bxt/external/snappy/BUILD.bazel:89:1: Executing genrule @snappy//:snappy_stubs_public_h failed (Exit 1)
/bin/bash: source external/bazel_tools/tools/genrule/genrule-setup.sh; sed -e 's/${\(.*\)_01}/\1/g' -e 's/${SNAPPY_MAJOR}/1/g' -e 's/${SNAPPY_MINOR}/1/g' -e 's/${SNAPPY_PATCHLEVEL}/4/g' external/snappy/snappy-stubs-public.h.in >bazel-out/x64_windows-opt/bin/external/snappy/snappy-stubs-public.h: bad substitution
Target //tensorflow/tools/graph_transforms:transform_graph failed to build
ERROR: C:/users/ruddy/source/repos/ruddyscent/tensorflow/tensorflow/core/framework/BUILD:1098:1 Executing genrule @snappy//:snappy_stubs_public_h failed (Exit 1)
INFO: Elapsed time: 15.628s, Critical Path: 0.74s
INFO: 0 processes.
FAILED: Build did NOT complete successfully
```

**Comment by ruddyscent** [comment]
> I have the same issue with TensorFlow on the master branch and bazel 2.0.0 on Windows 10 Pro 1909.

I eventually have been succeeded in compiling TensorFlow. The problem was the incompatibility of Bazel to bash on Windows as stated at https://docs.bazel.build/versions/master/windows.html.

I removed the 'Windows Subsystem for Linux' to remove bash from Windows, and then the official build procedure works as stated.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
