### ISSUE TITLE
some problem about pb model

### ISSUE THREAD

**Issue by MrCrazyCrab** [tensorflow/tensorflow#35412]
when i want to load my pb modekl, i met a probelm that "raise ValueError("callback %s is not found" % token) ValueError: callback pyfunc_31 is not found"

what is the pyfunc_31, why i can't load it, and how can i to slove it?

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Please, provide simple standalone code to reproduce the issue in our environment.It helps in localizing the issue faster. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
@MrCrazyCrab 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
