### ISSUE TITLE
linux aarch64 nested, exception is java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by TuringZhai** [tensorflow/tensorflow#35473]
Handler dispatch failed; nested exception is java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: linux, architecture: aarch64.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
@TuringZhai 

Any update on the issue please. Thanks!
