### ISSUE TITLE
Why Tf Warns 'Model's Complie Policy is not the same as the dtype policy's loss scale'

### ISSUE THREAD

**Issue by yourtheron** [tensorflow/tensorflow#35528]
I built up a custom model, then tried to adopt mixed precision as instructed by [here](https://www.tensorflow.org/guide/keras/mixed_precision#training_the_model_with_a_custom_training_loop)

```
from tensorflow.keras.mixed_precision import experimental as mixed_precision
curOpt = tf.keras.optimizers.Adam(learning_rate=1e-4)
curOpt = mixed_precision.LossScaleOptimizer(curOpt, loss_scale='dynamic')
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)
# query if it has been well set
print('Compute dtype: %s' % policy.compute_dtype)
print('Variable dtype: %s' % policy.variable_dtype)
modelInDim = (4, 64, 64, 64)
classNum = 2
mbSize = 2
TUNet = SimpleUNet(modelInDim, classNum)
TUNet.build_model(input_shape=(mbSize,)+modelInDim)
TUNet.summary()
```
Note that I set all Then as I call
```
TUNet.compile(loss=softDiceLoss, optimizer=curOpt)
```
The following warning pops out
```
TUNet.compile(loss=softDiceLoss, optimizer=curOpt)
WARNING:tensorflow:LossScale of LossScaleOptimizer passed to compile (DynamicLossScale(current_loss_scale=32768.0, num_good_steps=0, initial_loss_scale=32768.0, increment_period=2000, multiplier=2.0)) is not the same as the dtype policy's loss scale (DynamicLossScale(current_loss_scale=32768.0, num_good_steps=0, initial_loss_scale=32768.0, increment_period=2000, multiplier=2.0)). Because the dtype policy has a loss scale, you should pass an optimizer that is not wrapped with a LossScaleOptimizer,
```
What does it mean? The guide requires the optimizer to be wrapped in the way above. I am quite confused... 
FYI, the following is the model I built up.
```
class C3BR(tf.keras.Model):
    ''' 3D Convolution + Batch Normalisation + Relu '''
    def __init__(self, filterNum, kSize, strSize, padMode):
        super(C3BR, self).__init__()
        self.conv = layers.Conv3D(filters=filterNum, kernel_size=kSize, strides=strSize, padding=padMode, data_format='channels_first')
        self.BN = layers.BatchNormalization(axis=1)
    
    def call(self, inputs, ifTrain=False):
        x = self.conv(inputs)
        if ifTrain == True:
            x = self.BN(x)
        return activations.relu(x)

    def build_model(self, input_shape):
        ''' A work-around to define dimensions of signals through the NN'''
        self.build(input_shape)
        inputs = tf.keras.Input(shape=input_shape[1:])
        _ = self.call(inputs) 


class SimpleUNet(tf.keras.Model):
    """
    Input:
        inDim: (for initialisation) [modaility/channel, tensor dimensions]
        classNum: background included
        name: name for the net
        inputs: 5D tf tensor of [mbSize, modaility/channel, tensor dimensions]. Inputs must be organised into channel first order
        input_shape: a 1X5 tuple (mbSize, modaility/channel, tensor dimensions)
        ifTrain: True for training, and False for validation and testing
    Returns:
        outputs: 5D tf tensor of [mbSize, classNum, tensor dimensions]
    """
    def __init__(self, inDim, classNum):
        super(SimpleUNet, self).__init__()
        self.inDim = inDim
        self.classNum = classNum
        dimEnSt1End = np.array(inDim)[1:]-2-2
        dimEnSt2Ed = dimEnSt1End/2-2-2
        dimBridgeEnd = (dimEnSt2Ed/2-2-2)*2
        dimDEStd1End = (dimBridgeEnd-2-2)*2
        self.outDim = dimDEStd1End-2-2-2
        temp = ((dimEnSt2Ed - dimBridgeEnd)/2).astype('int32')
        crop3d1 = tuple(np.tile(temp, (2, 1)).T)
        temp = ((dimEnSt1End - dimDEStd1End)/2).astype('int32')
        crop3d2 = tuple(np.tile(temp, (2, 1)).T)

        self.en_st1_cbr1 = C3BR(32, 3, 1, 'valid')
        self.en_st1_cbr2 = C3BR(64, 3, 1, 'valid')
        self.en_st2_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
        self.en_st2_cbr1 = C3BR(128, 3, 1, 'valid')
        self.en_st2_cbr2 = C3BR(128, 3, 1, 'valid')
        self.bridge_mp = layers.MaxPooling3D(pool_size=(2, 2, 2), strides=(2, 2, 2), padding='valid', data_format='channels_first')
        self.bridge_cbr1 = C3BR(256, 3, 1, 'valid')
        self.bridge_cbr2 = C3BR(256, 3, 1, 'valid')    
        self.bridge_tconv1 = layers.Conv3DTranspose(512, 2, strides=2, padding='valid', data_format='channels_first')
        self.de_3dcrop1 = layers.Cropping3D(crop3d1, data_format='channels_first')
        self.de_st1_concat = layers.Concatenate(axis=1)
        self.de_st1_cbr1 = C3BR(256, 3, 1, 'valid')
        self.de_st1_cbr2 = C3BR(128, 3, 1, 'valid')    
        self.de_st1_tconv1 = layers.Conv3DTranspose(128, 2, strides=2, padding='valid', data_format='channels_first')
        self.de_3dcrop2 = layers.Cropping3D(crop3d2, data_format='channels_first')
        self.de_st2_concat = layers.Concatenate(axis=1)
        self.de_st2_cbr1 = C3BR(64, 3, 1, 'valid')
        self.de_st2_cbr2 = C3BR(64, 3, 1, 'valid') 
        self.final_conv3D = layers.Conv3D(filters=self.classNum, kernel_size=3, strides=1, padding='valid', data_format='channels_first')                
        self.output_layer = layers.Activation('softmax', dtype='float32')
    
    #@tf.function
    # In fact, decorating it does not bring much benefit as it primarily contains large ops. that have been optimised by tf.
    def call(self, inputs, ifTrain=False):
        x0 = self.en_st1_cbr1(inputs, ifTrain)
        xEnSt1End = self.en_st1_cbr2(x0, ifTrain)
        x1 = self.en_st2_mp(xEnSt1End)
        x2 = self.en_st2_cbr1(x1, ifTrain)
        xEnSt2Ed = self.en_st2_cbr2(x2, ifTrain)
        x3 = self.bridge_mp(xEnSt2Ed)  
        x4 = self.bridge_cbr1(x3, ifTrain)
        x5 = self.bridge_cbr2(x4, ifTrain)    
        xBridgeEnd = self.bridge_tconv1(x5)
        xCrop1 = self.de_3dcrop1(xEnSt2Ed)
        x6 = self.de_st1_concat([xBridgeEnd, xCrop1])
        x7 = self.de_st1_cbr1(x6, ifTrain)
        x8 = self.de_st1_cbr2(x7, ifTrain)
        xDeSt1End = self.de_st1_tconv1(x8)
        xCrop2 = self.de_3dcrop2(xEnSt1End)
        x9 = self.de_st2_concat([xDeSt1End, xCrop2])
        x10 = self.de_st2_cbr1(x9, ifTrain)
        x11 = self.de_st2_cbr2(x10, ifTrain)
        x12 = self.final_conv3D(x11)
        outputs = self.output_layer(x12)
        
        return outputs
        
    def build_model(self, input_shape):
        ''' A work-around to permit one to see dimensions of signals through the NN. An imperative API does not support it
            by its own right
        '''
        self.build(input_shape)
        inputs = tf.keras.Input(shape=input_shape[1:])
        _ = self.call(inputs)
        
    def compute_output_shape(self):
        ''''Override this function if one expects to use the subclassed model in Kera's fit() method; Otherwise, it is optional.
        '''
        return tf.TensorShape(np.append(self.classNum, self.outDim))    

```

**Comment by ravikyram** [comment]
@yourtheron 

Which version of Tensorflow you are using?.Please provide details about what platform you are using (operating system, architecture). Looks like code is incomplete. Request you to provide simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster.I tried reproducing the issue with TF 2.0.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/15d4f2270e8f1638b1b57decb277d08e/untitled528.ipynb).Thanks!

**Comment by yourtheron** [comment]
@ravikyram 
OS: Windows 7
TF: 2.0.0
Python: 3.7.5
IDE: Spyder
GPU: QuadroK620M
To call TUNet, just use a dummy signal
`x = tf.random.uniform((mbSize,)+modelInDim, dtype=tf.float32)`
```
from __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
from tensorflow.keras.mixed_precision import experimental as mixed_precision
import numpy as np
from tensorflow.keras import layers, activations

@tf.function(input_signature=[tf.TensorSpec(shape=None, dtype=tf.float32), tf.TensorSpec(shape=None, dtype=tf.uint8)])
def softDiceLoss(yPred, yTrue):
    '''
    SoftDiceLoss calculates multi-class soft dice loss
    loss = avg_batch(1-(sum(W_k*sum(yPred.*yTrue)))/(sum(W_ksum(yPred^2+yTrue^2))))
    where W_k = 1/(number of voxels in class k)^2
    Class number of segmented regions includes background
    Input:
        yPred/yTrue: prediced and desired outputs shaped as [mbSize, classNum, tensor dimensions]. Also, both must be float-point
    Return:
        loss: a scalar tensor
    '''
    epsilon = 1e-16 
    yTrue =tf.dtypes.cast(yTrue, dtype=yPred.dtype)
    # Dot product yPred and yTrue and sum them up for each datum and class
    crossProd=tf.multiply(yPred, yTrue)
    # As a symbolic tensor, dimensions and shapes etc. cannot be extracted from data, nor can it be used in subroutines.
    crossProdSum=tf.math.reduce_sum(crossProd, axis=np.arange(2, 5)) #tf.rank(yTrue)))
    # Calculate weight for each datum and class 
    weight = tf.math.reduce_sum(yTrue, axis=np.arange(2, 5))#tf.rank(yTrue)))
    weight = tf.math.divide(1, tf.math.square(weight)+epsilon)
    # Weighted sum over classes
    numerator = 2*tf.math.reduce_sum(tf.multiply(crossProdSum, weight), axis=1)
    # Saquared summation 
    yySum = tf.math.reduce_sum(tf.math.square(yPred) + tf.math.square(yTrue), axis=np.arange(2, 5))#tf.rank(yTrue)))
    # Weighted sum over classes
    denominator = tf.math.reduce_sum(tf.multiply(weight, yySum), axis=1)
    # Get individual loss and average over minibatch
    loss = tf.math.reduce_mean(1 - tf.math.divide(numerator, denominator+epsilon))
    
    return loss

```
I also have two pertinent questions. 
1) If I use mixed preicision. Suppose my original input is of float32, do I have to manually cast it into float16?
2) The doc instructs setting the output layer to be float32. layers.Activation(...) does not support setting axis=1 (my data is channel first), and if I use activations.softmax(...), it does not support manually setting dtype=float32, as I mentioned in another [issue](https://github.com/tensorflow/tensorflow/issues/35537)
Any solution or work-around? 
3. Is the way I set the input signature of softDiceLoss(...) correct? or shall I write it like
`@tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.float32), tf.TensorSpec(shape=[None], dtype=tf.uint8),))` The online doc is a bit confusing
Thanks.

**Comment by yourtheron** [comment]
Further more, as per the doc [here](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/experimental/LossScaleOptimizer?version=stable#minimize) , beside using CurOpt.get_scaled_loss(...) and CurOpt.get_unscaled_gradients(...), for example
```
curOpt = mixed_precision.LossScaleOptimizer(curOpt, loss_scale='dynamic')
epoch = 1
for ep in range(epoch):
    print('Start of epoch %d' % (ep,))
    # Each step crosses one minibatch
    for step, data in enumerate(dsTrain):    
		with tf.GradientTape() as tape:
			yPred = model(data[0], ifTrain=True)
			loss = lossFunc(yPred, data[1])
			scaledLoss = optimizer.get_scaled_loss(curLoss)
		scaledGradients = tape.gradient(scaledLoss, model.trainable_variables)
		gradients = optimizer.get_unscaled_gradients(scaledGradients)
		optimizer.apply_gradients(zip(gradients, model.trainable_variables))
```
Can the two code snippets below be performed instead without using tf.GradientTape()? Are they equivalent, with/without mixed precision? I want to know that because it seems the following two provide a unified API for cases of using mixed precision or not.
```
# Code Snippet 1
curOpt = mixed_precision.LossScaleOptimizer(curOpt, loss_scale='dynamic')
epoch = 1
for ep in range(epoch):
    print('Start of epoch %d' % (ep,))
    # Each step crosses one minibatch
    for step, data in enumerate(dsTrain):        
        yPred = TUNet(data[0])
        loss = softDiceLoss(yPred, data[1])
        gradients = curOpt.get_gradients(loss, TUNet.trainable_variables)
        curOpt.apply_gradients(zip(gradients, TUNet.trainable_variables))  


# Code Snippet 2
curOpt = mixed_precision.LossScaleOptimizer(curOpt, loss_scale='dynamic')
epoch = 1
for ep in range(epoch):
    print('Start of epoch %d' % (ep,))
    # Each step crosses one minibatch
    for step, data in enumerate(dsTrain):        
        yPred = TUNet(data[0])
        loss = softDiceLoss(yPred, data[1])
        CurOpt.minimize(loss, TUNet.trainable_variables)
```
Sorry for so many basic questions, I am trying my best to climb the mountain of tf2.0 now. Thanks again, indeed!

**Comment by yourtheron** [comment]
@gowthamkpr As per [NVIDIA's guide](https://docs.nvidia.com/deeplearning/sdk/mixed-precision-training/index.html) probably I should not have called model.compile(...) method after wrapping my optimizer by mixed_precision.LossScaleOptimizer(optimizer), but directly start training, because I use a graph-based code not Keras. Do you think so?
![捕获](https://user-images.githubusercontent.com/51472988/71806031-c97c7c00-3035-11ea-9337-4b0f86c39267.JPG)
Another point is that NVIDIA sugests about using tf.train.experimental.enable_mixed_precision_graph_rewrite() to wrap the optimizer in lieu of mixed_precision.LossScaleOptimizer(). What is the difference between the two? I am aware that my GPU is too old to use the first one, but tf' doc says using the second one may at least enable me to double my batch size.

**Comment by yourtheron** [comment]
@gowthamkpr A further question, when I tried to use adaptive learning rate like this
```
lr = 5e-4
decayR = 0.99
epStep = (epoch/mbSize)
# Decay lr after 10% epoch
decayS = np.floor(epStep*epoch*0.1)
lrSchedule = tf.keras.optimizers.schedules.InverseTimeDecay(initial_learning_rate=lr, decay_steps=epStep, decay_rate=decayR, staircase=True)
curOpt = tf.keras.optimizers.Adam(learning_rate=lrSchedule)

```
together with mixed precision, tf raised an error 
```
AttributeError: 'Adam' object has no attribute 'get_scaled_loss'
```
So I am wondering if that is because mixed precision does not support adaptive learning rate? Thanks.

**Comment by reedwm** [comment]
Sorry for the late response. I answered your questions below. Let me know if you have any more questions.

> The following warning pops out
> 
> ```
> TUNet.compile(loss=softDiceLoss, optimizer=curOpt)
> WARNING:tensorflow:LossScale of LossScaleOptimizer passed to compile (DynamicLossScale(current_loss_scale=32768.0, num_good_steps=0, initial_loss_scale=32768.0, increment_period=2000, multiplier=2.0)) is not the same as the dtype policy's loss scale (DynamicLossScale(current_loss_scale=32768.0, num_good_steps=0, initial_loss_scale=32768.0, increment_period=2000, multiplier=2.0)). Because the dtype policy has a loss scale, you should pass an optimizer that is not wrapped with a LossScaleOptimizer,
> ```
> 
> What does it mean? The guide requires the optimizer to be wrapped in the way above. I am quite confused...

This warning is poorly worded, and you can safely ignore it. If you want to know the technical details, what is happening is as follows. You set the policy to `mixed_float16` and use a `LossScaleOptimizer`. The `LossScaleOptimizer` automatically creates a `DynamicLossScale` object since you passed the string `dynamic`. However, when you call `TUNet.compile`, it automatically tries to convert the optimizer to a `LossScaleOptimizer` with a different `DynamicLossScale` object, since the policy is `mixed_float16` which has `DynamicLossScale`. Since you already passed a `LossScaleOptimizer`, it gives a warning.

I will try to see how I can rework this error message, as it's too confusing. If you call `Model.fit`, you can fix by not wrapping the optimizer with a `LossScaleOptimizer`. If you do not call fit, you do need to wrap with a `LossScaleOptimizer` but you (probably) do not need to call `compile`.

> If I use mixed preicision. Suppose my original input is of float32, do I have to manually cast it into float16?

Typically no. The following lines will cause every Keras layer to cast their inputs to float16, so you do not have to do any casting.
```
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)
```
> The doc instructs setting the output layer to be float32. layers.Activation(...) does not support setting axis=1 (my data is channel first), and if I use activations.softmax(...), it does not support manually setting dtype=float32, as I mentioned in another issue

I responded to that issue directly.

> Is the way I set the input signature of softDiceLoss(...) correct? or shall I write it like
@tf.function(input_signature=(tf.TensorSpec(shape=[None], dtype=tf.float32), tf.TensorSpec(shape=[None], dtype=tf.uint8),)) The online doc is a bit confusing
Thanks.

Passing `shape=None` means the shape can be anything, such as `[2]` or `[3, 4]`. Passing `shape=[None]` means the shape must only have at least one component, or in other words, in the form of `[???]` where `???` can be any number. This means `[2]` would be acceptable but not `[3, 4]`. Assuming you always pass tensors with one component in their shape, I think the two forms have no practical difference, although `shape=[None]` may have a performance benefit. I'm not an expert on this.

> Can the two code snippets below be performed instead without using tf.GradientTape()? Are they equivalent, with/without mixed precision? I want to know that because it seems the following two provide a unified API for cases of using mixed precision or not.

Yes, all three of those examples are correct. `curOpt.get_gradients` and `curOpt.minimize` automatically apply loss scaling when called on a LossScaleOptimizer, so you do not have to do extra work. However, when you use a `tf.GradientTape`, you must call `get_scaled_loss and `get_unscaled_gradients` (as you correctly did in the first example), since the GradientTape does not know about loss scaling. In general, if you compute gradients through the LossScaleOptimizer, you don't have to manually scale the loss and unscale gradients. If you compute gradient tapes through a GradientTape, you do have to manually scale the loss and unscale gradients.

> Another point is that NVIDIA sugests about using tf.train.experimental.enable_mixed_precision_graph_rewrite() to wrap the optimizer in lieu of mixed_precision.LossScaleOptimizer(). What is the difference between the two? I am aware that my GPU is too old to use the first one, but tf' doc says using the second one may at least enable me to double my batch size.

This is complicated, and I will definitely clarify this in a doc in the future. The `enable_mixed_precision_graph_rewrite` function recommends is **completely separate** from the `mixed_precision.set_policy` API. You can use one API or the other, but not both because they both do the same thing. I recommend not using `enable_mixed_precision_graph_rewrite`, and we will deprecate and remove it in the future (although it will be accessible under the `tf.compat.v1` namespace for a long time). Instead use `mixed_precision.set_policy`. 

`enable_mixed_precision_graph_rewrite` causes the graph to be rewritten under the hood by the TensorFlow C++ backend to use mixed precision. `mixed_precision.set_policy('mixed_float16')` causes Keras layers to use mixed precision through `tf.cast` ops. The one shared component between the APIs is the LossScaleOptimizer. `enable_mixed_precision_graph_rewrite`  returns a LossScaleOptimizer, and you have to use it just as you do in the `mixed_precision.set_policy` API.

As `enable_mixed_precision_graph_rewrite` rewrites the graph, it does not work in Eager mode as there is no graph. Additionally, as it operates on the C++ backend, querrying `tensor.dtype` will always return float32 since the float16 happens on the C++ layer. Finally, you cannot override a dtype of a layer to float32 easily with the graph rewrite. On the other hand, `enable_mixed_precision_graph_rewrite` will never result in a TypeError, works outside of Keras as well as inside, and can more effectively determine the optimal dtypes of ops since it can look at the whole graph at once. The Keras `mixed_precision.set_policy` is recommended over the `enable_mixed_precision_graph_rewrite`.

**Comment by yourtheron** [comment]
@reedwm, thank you so much for your detailed explanation! Everything is clear to me now!
