### ISSUE TITLE
Correction in the course material

### ISSUE THREAD

**Issue by ManishAradwad** [tensorflow/tensorflow#35525]
## Description of issue (what needs changing):

Do we still need the `steps_per_epochs` parameter while fitting the model to training set?
In the tensorflow tutorial(which is very similar to the MNIST tutorial of Intro to Deep Learning course ), there is no such parameter...

## URL(s) with the issue:

Udacity Course Notebook : https://colab.research.google.com/github/tensorflow/examples/blob/master/courses/udacity_intro_to_tensorflow_for_deep_learning/l03c01_classifying_images_of_clothing.ipynb#scrollTo=S5Uhzt6vVIB2

-----------------------------------------------------------------
![Screenshot from 2020-01-01 23-27-10](https://user-images.githubusercontent.com/29497701/71644446-78dfe880-2cee-11ea-9da7-5c033d8a0592.png)
-----------------------------------------------------------------

Tensorflow Tutorial : 
https://www.tensorflow.org/tutorials/keras/classification/

-----------------------------------------------------------------
![Screenshot from 2020-01-01 23-26-50](https://user-images.githubusercontent.com/29497701/71644452-93b25d00-2cee-11ea-97af-70d0ece074d9.png)
-----------------------------------------------------------------

### Parameters defined

`steps_per_epoch` parameter in `model.fit` should be removed??

### Submit a pull request?

I'll submit a PR right away if this issue is relevant...

**Comment by Lasers67** [comment]
While training over large datasets, It is not possible to load the entire dataset onto the memory at once, one approach used is to perform step wise training where we only show a fixed number of datapoints to the model at every epoch, here steps_per_epoch is used.

**Comment by wangyexiang** [comment]
> Total points per epoch is equal to steps_per_epoch*batch_size.

Dear sir, If I understand correctly from the manual, "`step_per_epoch = n_samples / batch_size`" will not do augmentation, because it will simply iterate all the data once. If you want to augment the data, should you set `step_per_epoch = n*(n_samples / batch_size)` (where n = 2, 3, 4, ...)?

**Comment by jvishnuvardhan** [comment]
@ManishAradwad As of now, we still need `steps_per_epoch` flag otherwise it will throw an error as follows
`ValueError: When passing an infinitely repeating dataset, you must specify the steps_per_epoch argument.` May be in the later versions, it will be removed. Even in the course material you mentioned, `steps_per_epoch` flag is present  in the `model.fit` as shown below.

`model.fit(train_dataset, epochs=5, steps_per_epoch=math.ceil(num_train_examples/BATCH_SIZE))`

I am closing this issue. Please feel free to reopen the issue if there is any related issue. thanks!
