### ISSUE TITLE
The report a mistake link does not work

### ISSUE THREAD

**Issue by GantMan** [tensorflow/tensorflow#35593]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://codelabs.developers.google.com/codelabs/sparkfun-tensorflow/#3

### Clear description

The "Report a Mistake" link at the bottom left does not work, and goes to a GitHub 404 instead.
![image](https://user-images.githubusercontent.com/997157/71787589-711a8f80-2fdf-11ea-8c54-03f8fc68b8d0.png)

Currently it links to: https://github.com/tensorflow/tensorflow/issues/new/title=[sparkfun-tensorflow-codelab]:

**Comment by jvishnuvardhan** [comment]
@GantMan It was moved out of `tensorflow` GitHub repository to a new repository on GitHub. Link to the new repository is [here](https://github.com/googlecodelabs/tools/issues). Please file an issue there so that it will be resolved faster. You could also raise a PR to update the docs in that repository. Thanks!

I am closing this issue as it was not related to Bug/Performance related to `Tensorflow` repository. Thanks!
