### ISSUE TITLE
OOM error when running ops on large tensors in TF2.0

### ISSUE THREAD

**Issue by evancasey** [tensorflow/tensorflow#35681]
<em>Please make sure that this is a bug. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.0.0
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 10.0.130 / 7.6.0
- GPU model and memory: Nvidia GeForce GTX 1060

**Describe the current behavior**

I want to allocate a large tensor (in the 100Ms of elements) and perform an operation on it such as `tf.exp`. However, when I apply an operation to my tensor it appears that TF is reallocating the entire thing, causing an OOM. This behavior is not limited to `tf.exp`, I believe it is common across all ops. Is there any way to force TF not to do such a massive reallocation?

**Describe the expected behavior**

TF should return the result of `tf.exp` without error.

**Code to reproduce the issue**

Running:
```python
x = tf.ones([1, 25088, 25088])
tf.exp(x)
```
Gives me the following error:
```
2020-01-08 15:06:32.805387: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at cwise_ops_common.h:259 : Resource exhausted: OOM when allocating tensor with shape[1,25088,25088] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/evan/opt/miniconda3/envs/tf-gpu-2.0.0/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_math_ops.py", line 3970, in exp
    _six.raise_from(_core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[1,25088,25088] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Exp]
```

In PyTorch, I could run the following identical code without error:
```python
x = torch.ones((1,25088,25088))
torch.exp(x)
```

**Comment by pandrey-fr** [comment]
Hi,

You are computing the exponential (or any value-wise transformation) of N values, without re-assigning the results to their initial container, so obviously N new values have to be created and allocated space for. In your case, N is very large; the created array should take around 2.5 GB of memory space (with default float32 dtype). Note that if you reassign to the inital tensor (`x = tf.exp(x)`), values will be overwritten, but there can still be some extra memory used during the operation (as transformed values have to be computed somewhere before being moved back to their initial location), but it will be minor as compared to assigning results to a distinct tensor.

Now, the fact that the OOM occurs in TensorFlow and not in PyTorch could be due to the fact that in TF the computation occurs on the GPU, which in most cases has a more limited dedicated memory than when using system RAM for CPU computations. My knowledge of PyTorch is limited, but my guess is that the computation is happening on CPU there, hence the fact that it fits. Note that depending on the material you are using, actual memory limits will vary.

To force a computation to occur on CPU in TF, you can use a `tf.device` context manager:
```python
with tf.device('cpu:0'):
    x = tf.ones([1, 25088, 25088])
    tf.exp(x)
```

I hope this helps.

**Comment by oanush** [comment]
@evancasey ,
When tried executing the code for TF-2.0, worked fine. Also the solution provided by @pandrey-fr  works well too. Kindly find the [gist](https://colab.sandbox.google.com/gist/oanush/f47c3278a1b478b3f5e78f0ba278ea64/35681.ipynb) of colab for your reference. Kindly close the issue if its resolved.Thanks!

**Comment by oanush** [comment]
@evancasey ,
Any update on the issue?Thanks!

**Comment by oanush** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
