### ISSUE TITLE
Failed to load model from file:///android_asset/frozen_inference_graph.pb'

### ISSUE THREAD

**Issue by SirPhemmiey** [tensorflow/tensorflow#35707]
Hi guys, 

I am trying to run the trained model on my android device, but it's crashing on opening. 

When i checked my logcat, i have the following screenshot:
<img width="1364" alt="Screen Shot 2020-01-09 at 5 47 51 PM" src="https://user-images.githubusercontent.com/22390818/72073182-d7b5eb00-3308-11ea-996d-b508710f75c4.png">
Process: org.tensorflow.demo, PID: 3797 java.lang.RuntimeException: Failed to load model from 'file:///android_asset/frozen_inference_graph.pb'.

I have tried so many things like changing my TF version to match the tensorflow android build version but all to no avail. 

And also, sometimes the logcat will log an error message relating to something like `Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary`. 

I would have matched my android build.gradle dependencies with my current TF version but the latest tensorflow-android is 1.13.1.

My model was trained on TF 1.15.0
macOS Mojave 10.14
TF Version: 1.15.0
Model used: ssd_mobilenet_v2_quantized_300*300_coco and ssd_inception_v2_coco

Please help, I have used more than 24 hours in looking for the solution.

**Comment by jdduke** [comment]
TF Mobile is deprecated, so if you need updated support you would have to build the libraries manually from source.

Alternatively, TensorFlow Lite supports both ssd_mobilenet_v2 and ssd_inception, and should offer much better performance and a much smaller binary size. Is there a reason you cannot use TensorFlow Lite?

**Comment by SirPhemmiey** [comment]
Aha, Okay.

No reason, actually. I just followed a tutorial. 

I'll definitely try out TensorFlow Lite and see how it goes. 

Thank you!

**Comment by jdduke** [comment]
Sounds good, let us know if you run into any issues!

**Comment by SirPhemmiey** [comment]
Hi @jdduke, I am trying to run the command to convert .pb to tflite format using this code
 `toco --graph_def_file=trained-inference-graphs/output_tflite/tflite_graph.pb  --output_format=TFLITE --output_file=trained-inference-graphs/output_tflite/detect.tflite --inference_type=QUANTIZED_UINT8 --inference_input_type=QUANTIZED_UINT8 --input_arrays=input --output_arrays=TFLite_Detection_PostProcess --input_shapes=1,60,80,3 --mean_values=128 --std_dev_values=128 --default_ranges_min=0 --default_ranges_max=6
` 

but it's returning the error `F tensorflow/lite/toco/graph_transformations/quantize.cc:614] Check failed: is_rnn_state_array`. When i change the output_arrays, it returns `Specified output array is not produced by any op in this graph`. I have tried different input_arrays values as well as output_arrays values and input_shapes values ut all to no avail. How can i know the correct appropriate values for my case, please?

**Comment by jdduke** [comment]
@srjoglekar246 can help in offering guidance for detection model conversion.

**Comment by srjoglekar246** [comment]
@SirPhemmiey Please follow the instructions on [this page](https://github.com/tensorflow/models/blob/master/research/object_detection/g3doc/running_on_mobile_tensorflowlite.md) for conversion. You will probably need to follow instructions for float models, since the models mentioned above aren't quantized. The command to convert, in particular, is this:

```
bazel run --config=opt tensorflow/lite/toco:toco -- \
--input_file=$OUTPUT_DIR/tflite_graph.pb \
--output_file=$OUTPUT_DIR/detect.tflite \
--input_shapes=1,300,300,3 \
--input_arrays=normalized_input_image_tensor \
--output_arrays='TFLite_Detection_PostProcess','TFLite_Detection_PostProcess:1','TFLite_Detection_PostProcess:2','TFLite_Detection_PostProcess:3'  \
--inference_type=FLOAT \
--allow_custom_ops
```

**Comment by Adeesh2411** [comment]
I'm getting the same error when deploying frozenModel.pb to android 
My tensorflow model contains LSTM layers. Is it because of this?
Thanks in advance

**Comment by Adeesh2411** [comment]
> @Adeesh2411 you can't run a .pb on Android with TFLite. What API are you using?

**This is my tensor flow model information:** 
![image](https://user-images.githubusercontent.com/35789683/110511461-428bcd80-812a-11eb-985a-ca901dc3c37e.png)



I'm not using tflite file . I Converted above model to  .pb file and I want to run this .pb file in android 
**API used in android :** 
Module used :  import org.tensorflow.contrib.android.TensorFlowInferenceInterface;
inferenceInterface = new TensorFlowInferenceInterface(getAssets(), MODEL_FILE); // here MODEL_FILE is path to .pb file

My issue is it fails to load the module itself .It provides Java Runtime exception

The reason I'm using this approach is because I need to deploy LSTM Model into android 
**To put this in another way is it possible to run LSTM model in android by any means?**

**Comment by srjoglekar246** [comment]
You need to convert it to tflite.

**Comment by Adeesh2411** [comment]
Currently we cannot convert LSTM model to tflite file . so then we cannot deploy LSTM model to android?
