### ISSUE TITLE
Failed to allocate memory for tensor_info, 1320 bytes required

### ISSUE THREAD

**Issue by pramodjayram** [tensorflow/tensorflow#35794]
@tensorflow/micro

Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
NAME="Ubuntu"
VERSION="18.04.3 LTS"
ID=ubuntu
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
Python versionL 2.7.15+
Target platform : K64F

**Describe the problem**
I have build a GRU model in python and converted to a bin format for ARM K64F board. When I flash the binary I get the following error message in the serial console.  How can I fix it? Any help is appreciated.

`Failed to allocate memory for tensor_info, 1320 bytes required
AllocateTensors() failed

++ MbedOS Fault Handler ++

FaultType: HardFault

Context:
R0   : 00000000
R1   : 00000000
R2   : 00000000
R3   : 20013FE8
R4   : 00000000
R5   : 00000000
R6   : 00000000
R7   : 20002368
R8   : 20002364
R9   : 00000000
R10  : 00000000
R11  : 00000000
R12  : 000000B0
SP   : 20013F10
LR   : 00008E89
PC   : 000010E4
xPSR : 61070000
PSP  : 20013EA8
MSP  : 2002FFC0
CPUID: 410FC241
HFSR : 40000000
MMFSR: 00000000
BFSR : 00000004
UFSR : 00000000
DFSR : 00000008
AFSR : 00000000
Mode : Thread
Priv : Privileged
Stack: PSP

-- MbedOS Fault Handler --

++ MbedOS Error Info ++
Error Status: 0x80FF013D Code: 317 Module: 255
Error Message: Fault exception
Location: 0x10E4
Error Value: 0x1FFF0400
Current Thread: main Id: 0x200013E8 Entry: 0x3F07 StackSize: 0x10000 StackMem: 0x20004010 SP: 0x20013F10
For more info, visit: https://mbed.com/s/error?error=0x80FF013D&tgt=K64F
-- MbedOS Error Info --

= System will be rebooted due to a fatal error =
= Reboot count(=7) reached maximum, system will halt after rebooting
`

**Comment by njeffrie** [comment]
This is the expected error if you are trying to load a model and your tensor arena is too small.  If you have extra memory, you can increase the tensor arena size.  If not, you will either need to compress your model and required tensors via quantization, or select a more compact model.

**Comment by pramodjayram** [comment]
I did try to increase the Tensor arena size but that resulted with another error **`Logic error in memory planner, tensor 17 has an invalid lifetime`**.  I dont understand this error. Secondly what kind of quantization should I use for data type of float. Any help regarding this appreciated.

**Comment by njeffrie** [comment]
Apologies for the delay.  It's strange that you're seeing that error - as far as I know that's a sanity check to ensure that the memory planner has found valid lifetimes for each tensor in the graph - i.e. for each tensor it has a valid start and end.  I'm guessing you may be running into this error as a side-effect of something else going wrong.  Perhaps try further increasing arena size (we have seen some issues with marginal arena sizes) and make sure you allocate the arena in a valid way. Avoid allocating large arenas on the stack to avoid stack overflow issues.  Also make sure you aren't overrunning any structures in your application, since that could also cause memory corruption.

When it comes to quantizing float tensors, we mainly support int8 quantization on TFLite Micro.  You should be able to quantize your model using the TFLite converter with OPTIMIZE_FOR_SIZE along with providing a representative dataset.  Note that we do not support running hybrid quantized models on TFLite Micro, hence needing a representative dataset at conversion time.

**Comment by njeffrie** [comment]
I'm going to close this, since it's been a while since any update. Please reopen if this issue persists, or if new information is available.
