### ISSUE TITLE
The result of NNAPI hardswish quantization implementation is different with tensorflow hardswish

### ISSUE THREAD

**Issue by jianlongf** [tensorflow/tensorflow#35847]
Recently,  I ran AI benchmark v4 model(Mobilenet-v3-quant.tflite) by label_image. But I got the different result by tflite and NNAPI implementation quantization. The detailed difference is just 1 per quant HardSwish layer. And HardSwish is splited by NNAPI delegate as below: 

> // Lower hardswish according to the following equation:
> // hard_swish[x] = x (ReLU6(x + 3)) / 6 == x * (Relu_N1_to_1(x/3) * 3 + 3) / 6
> // = 0.5x * Relu_N1_to_1(x/3) + 0.5x

in nnpai_delegate.cc at the line around 510.
BTW, NNAPI uses int32 quantization but tflite uses int16.

**Comment by miaowang14** [comment]
A couple of questions:
1. Which device are you using?
2. Could you provide the test input & output so that we can reproduce it? Or you can try using "nnapi-reference" to see if you still see the same off be 1 error.
3. Is this causing significant accuracy problem for the whole model? 

background:
NNAPI does allow off by 1 error for hardware accelerators, to allow different implementation / optimization.
And I believe NNAPI is using 8 bit quantization, the int32 scalars were just for passing certain parameters.

**Comment by jianlongf** [comment]
Sorry for lately responding,  Actually, NNAPI use 8 bit quantization , but I mean the implementation of operator is  32bit int32, and I checked the implementation of tflite that was int16 implementation.

**Comment by miaowang14** [comment]
I guess you meant the intermediate tensors are int16 for TFLite CPU implementation. And since NNAPI delegate uses lower level operations to compute hard_swish, the intermediate output are 8bit. Please correct me if that's incorrect.

Back to my original question, is this off-by-1 error causing significant difference in the accuracy for the model?

(also, FYI, for Android R, NNAPI will be adding a fused hard_swish which hopefully would be faster and more accurate: https://android.googlesource.com/platform/frameworks/ml/+/refs/heads/master/nn/runtime/include/NeuralNetworks.h#5388)
