### ISSUE TITLE
variable_ops.h missing from pip install

### ISSUE THREAD

**Issue by dirktheeng** [tensorflow/tensorflow#35993]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Centos 7
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 1.14.0
- Python version:3.6
- Installed using virtualenv? pip? conda?: Pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.0
- GPU model and memory: p100

**Describe the problem**
When building custom ops, we want to link against pip installation for end user simplicity.  We were testing expanding the registered dtypes for variableson GPUs through subclassing.  We found that the header for the variable op is missing from the pip installation.  We had to copy the file locally from source and reference it in our cuatom op code which is undesirable from a maintenance perspective.  Can the file be added to the proper place in the includes?

**Comment by yifeif** [comment]
@gunan, do you think headers for classes like VariableOp under core/kernels/ should be included?

**Comment by gunan** [comment]
I definitely do not want any headers under `core/kernels` in the pip package.
If there are libraries there we would like to use for custom kernels, they should be turned into libraries and moves outside core/kernels.

**Comment by dirktheeng** [comment]
May I ask why the headers should not be included?  I'm not trying to argue, I am just curious and somewhat ignorant.  Is there a way that we can make the core kernels accessible from custom ops with a standard install?  For our purposes it is best to subclass and expand capability but it is difficult to make the workflow easy if the headers are not there.

**Comment by gunan** [comment]
`core/kernels` by design are just our implementations of kernels. Most libraries there have not been designed to be reused. So in our code structure, they are meant to be hidden symbols not used by others.

Moreover, on windows, we have to limit the number of symbols we export. This is because windows puts a limit on number of exported symbols from shared objects. So that folder is completely excluded.

Again, if you like to use any libraries under core/kernels, you may refactor the code out of that directory.
