### ISSUE TITLE
Compatibility issue with cudnn 7.0.5 and cuda 9.0

### ISSUE THREAD

**Issue by Vishal2188** [tensorflow/tensorflow#36148]
My source code required tensorflow 1.7.0 with cuda 9.0 and cudnn 7.0.5 version. However when i install cudnn 7.0.5 then my cuda 9.0 version downgraded to 8.0 that arise error during training. While when i install cuda 9.0 and cudnn 7.1.2 then i got following error:

**E tensorflow/stream_executor/cuda/cuda_dnn.cc:396] Loaded runtime CuDNN library: 7102 (compatibility version 7100) but source was compiled with 7005 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.**

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture).

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by ravikyram** [comment]
@Vishal2188 

Can you please try with cudnn 7.0.Can you please see tested build configuration from [here](https://www.tensorflow.org/install/source#gpu).Thanks!

**Comment by ravikyram** [comment]
@Vishal2188 

Any update on this issue please. Thanks!

**Comment by ravikyram** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
