### ISSUE TITLE
Build using nvcc + clang?

### ISSUE THREAD

**Issue by djwenren** [tensorflow/tensorflow#36213]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit c044803bcd710a040d6baa6f39588581ae1c5c01 (with the problem in https://github.com/tensorflow/tensorflow/issues/36170 fixed locally)
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: conda
- Bazel version (if compiling from source): 1.2.1
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.4.0-1ubuntu1~18.04.1) 7.4.0
- CUDA/cuDNN version: V10.1.243/7.6.5
- GPU model and memory: GeForce GTX 1080, 8116 MiB 

**Describe the problem**

I was able to build Tensorflow with (`bazel build tensorflow/tools/pip_package:build_pip_package`) using nvcc + gcc. But if I tried to manully override gcc using clang (8.0.1), the build will fail with
```
clang: error: unknown argument: '-fno-canonical-system-headers'
``` 
It seems the CC toolchain auto config still generates flags for nvcc + gcc, even though I choose to use clang. I confirmed that my gcc has this flag while my clang does not.

If I choose to use clang as CUDA compiler, it would fail with
```
 error: cannot find libdevice for sm_61.
``` 
which seems to mean that Clang cannot compile for this cuda compute capabilities (6.1). So I am wondering if there is any way of using nvcc + clang to build since I use clang as default (for all other builds). Shouldn't this be possible since clang is used by default on Macs? Thanks!

**Comment by djwenren** [comment]
The original error when using clang as cuda compiler (cannot find libdevice) seems to go away after upgrading clang to a new version (10.0.0-++20200126090219+73a91477f70-1~exp1~20200126201656.19). Is the build supposed to be done either by gcc+nvcc or purely by clang? Or is Clang supported?

Using the new clang version still fails due to errors like the following. To isolate the problem, the target I built is
```
bazel build @nccl_archive//:device_lib
```
The errors look like this
```
In file included from <built-in>:1:
In file included from /usr/lib/llvm-10/lib/clang/10.0.0/include/__clang_cuda_runtime_wrapper.h:202:
In file included from /usr/include/string.h:494:
/usr/include/x86_64-linux-gnu/bits/string_fortified.h:95:8: error: exception specification in declaration does not match previous declaration
__NTH (stpcpy (char *__restrict __dest, const char *__restrict __src))
       ^
/usr/include/string.h:451:14: note: previous declaration is here
extern char *stpcpy (char *__restrict __dest, const char *__restrict __src)
             ^
```
There is one such error for each function in `/usr/include/string.h`. It seems to be caused by the difference in their declaration and definition. gcc doesn't take it as an error while clang-10 does. For example, the declaration of `strcpy` in `string.h` is
```c
/* Copy SRC to DEST.  */
extern char *strcpy (char *__restrict __dest, const char *__restrict __src)
     __THROW __nonnull ((1, 2));
```
while in `/usr/include/x86_64-linux-gnu/bits/string_fortified.h` it is
```c
__fortify_function char *
__NTH (stpcpy (char *__restrict __dest, const char *__restrict __src))
{
  return __builtin___stpcpy_chk (__dest, __src, __bos (__dest));
}
```
The latter does not throw while the former does? I am not sure if this should be a Tensorflow issue or Clang issue or there is something wrong with my set up.

**Comment by djwenren** [comment]
I also saw the same error came up in this issue: https://github.com/tensorflow/tensorflow/issues/34098

**Comment by gunan** [comment]
@Artem-B may have some details.
At one point, I remember CUDA headers had a check to block building with Clang, when we first tried this. I do not know if this still applies.

Another option is to just use clang when building TF. Clang can already compile cuda code.

**Comment by Artem-B** [comment]
NVCC + custom crosstool w/ a wrapper script was very gcc-centric when I looked at it last time (mind, it was a while back). I would not expect that to work out of the box.

As for using clang for CUDA compilation, it's expected to work in general, but I don't have enough details to tell what went wrong in this case. 

> error: cannot find libdevice for sm_61.

This could happen if you install CUDA from packages (as opposed to installing it manually from a .run file). Packages tend to scatter CUDA files all over the place which confuses clang. I think there were recent changes to attempt dealing with some of this, but in general clang assumes a monolithic CUDA installation (I.e. all CUDA files are under a single directory).

As for mismatching declarations for stpcpy, here's how I'd debug it:

* run blaze with --verbose_failures and extract exact compiler command line
* reproduce the failure manually
* If the failure was during compilation of a CUDA file run compiler with -v and extract command line of sub-compilation that fails.
* run the failing sub-compilation with `-dD -E` and check what preprocessed declarations/definitions look like for the functions we're failing on.
* track down the differences to a macro which leads to them (`__USE_XOPEN2K8` ? `__THROW` ?) and then figure out why the declarations are inconsistent.

One thing that could be the culprit is that CUDA does not support exceptions on the GPU side. If something/somewhere assumes that exceptions are available, things may not work as expected. Another possible source of trouble is that clang's `__clang_cuda_runtime_wrapper.h` which implements the magic massaging CUDA headers into something clang can pasre may need to be updated to deal with more recent headers on your machine. 

@djwenren If you can send me exact command line that fails, I'll try reproducing it locally and check what's going on. The headers on my machine appear to match the ones quoted above.

**Comment by djwenren** [comment]
Thanks for the detailed information, @Artem-B ! I reinstalled my Cuda toolkit (10.1) using runfiles from Nvidia. The problems seem to have gone away. I was able to build using purely Clang. Could have been some misconfiguration I had earlier.

**Comment by Vadim-Maklakov** [comment]
Hi all!
1. For correct nvcc and TF compilation  with MLIR support required  preinstalled clang  - see required clang version version in the  '/usr/local/cuda-11-2/include/crt/host_config.h`
2.  If you remain only sm_61 in the setup.py  - you get error in the time compilation. Enter next values separated by comma when you run setup.py after defining correct path to clang: sm_35, sm_50, sm_60, sm_70, sm_75, compute_80 - more accuracy required in the you version TF values you can get run these code for TF package installed from pypy

```
from tensorflow.python.platform import build_info
build_info.build_info  
```
in my case for TF 2.5.1

```
OrderedDict([('cpu_compiler', '/usr/bin/gcc-5'),
             ('cuda_compute_capabilities',
              ['sm_35', 'sm_50', 'sm_60', 'sm_70', 'sm_75', 'compute_80']),
             ('cuda_version', '11.2'),
             ('cudnn_version', '8'),
             ('is_cuda_build', True),
             ('is_rocm_build', False),
             ('is_tensorrt_build', True)])
```
