### ISSUE TITLE
XLA Warning and could not interpret set environment

### ISSUE THREAD

**Issue by himanshisyadav** [tensorflow/tensorflow#36247]
**System information**
- OS Platform and Distribution:18.04
- TensorFlow version: 1.14.0
- Python version: 2.7.17

`Couldn't interpret value =/home/hyadav/deephyp/lib/python2.7/site-packages/tensorflow/compiler/xla:--tf_xla_cpu_global_jit=/home/hyadav/deephyp/lib/python2.7/site-packages/tensorflow/compiler/xla:=--tf_xla_cpu_global_jit=--tf_xla_cpu_global_jit for flag tf_xla_cpu_global_jit.`

I tried using the following export TF_XLA_FLAGS=--tf_xla_cpu_global_jit=/mytensorflowpath/tensorflow/compiler/xla:$TF_XLA_FLAGS=--tf_xla_cpu_global_jit from issue #30308 and get the above.

**Comment by gadagashwini** [comment]
@himanshisyadav, Could you provide the standalone code to reproduce the reported issue. Thanks!

**Comment by himanshisyadav** [comment]
I am using the autoencoder example codes from [this](https://github.com/lloydwindrim/hyperspectral-autoencoders) github repo. Specifically running autoencoder_test_MLP_basic.py. 

I actually unset tf_xla_cpu_jit variable and the above error was solved. However, I was trying so many things simultaneously that I do not remember what did the trick.

**Comment by tpopp** [comment]
Hi @himanshisyadav,

The person in the previous issue was using this flag wrong. It should be only `TF_XLA_FLAGS=--tf_xla_cpu_global_jit` This is not a key-value pair. It is just a flag.

Regarding the XLA warning you mention, if you were seeing the same warning mentioned in the previous issue, it is fixed in newer versions of Tensorflow and will not be backported. If you don't want to use XLA in your code, just ignore the warning.

**Comment by Saduf2019** [comment]
@himanshisyadav Please let us know if the above comment helps resolve the issue.
