### ISSUE TITLE
How is the support for tensorflow 2.0 and keras in this?

### ISSUE THREAD

**Issue by Akpadhy** [tensorflow/tensorflow#36253]
Need to understand if this support tensorflow 2.0 and tfx serving directly?

**Comment by amahendrakar** [comment]
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. Thanks!

**Comment by amahendrakar** [comment]
@Akpadhy,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
