### ISSUE TITLE
Support nested structure as return value in tf.py_function.

### ISSUE THREAD

**Issue by VitaliKaiser** [tensorflow/tensorflow#36276]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow==2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Support for return values in nested structures as in `tf.data.Dataset.from_generator`.
I cant return any nested structure as, e.g., a dict or namedtuple.

See example:
 
````python
arg1_const = tf.constant([0, 1], dtype=tf.int32)
def eager_py_dict(arg1):
    return {0: arg1}

tf.py_function(eager_py_dict, [arg1_const], {0: tf.int32})
# Returns:
# tensorflow.python.eager.core._FallbackException: Expecting a DType.dtype for attr Tout, got dict
````

**Will this change the current api? How?**
Supporting nesting structures.

**Who will benefit with this feature?**
People building their `tf.data` pipeline with `tf.pyfunction`.

**Any Other info.**
I will create more `tf.py_function` related stories. Since this are distinct features from my POV, there multiple feature requests. I hope this is ok.

**Comment by chunduriv** [comment]
I was able to replicate issue using TF 2.10.0-dev20220728. Please find the [gist](https://colab.sandbox.google.com/gist/chunduriv/0d855829c55785e4d45d8b45ee33a67a/untitled49.ipynb) for reference. Thank you.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
