### ISSUE TITLE
Support setting shapes directly in tf.py_function

### ISSUE THREAD

**Issue by VitaliKaiser** [tensorflow/tensorflow#36274]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow==2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
In comparison to `tf.data.Dataset.from_generator`, `tf.py_function` does not take an (optional) shape argument. Therefore all returned tensors have unknown shape. Looking up the docu I realized you can solve this by setting `tf.Tensor.set_shape`. It would be more convienent if  `tf.py_function` would support this directly.
Therefore I wrote a wrapper for myself:

```
def py_function2(
    func: Callable,
    inp: tf.Tensor,
    tOut: Iterable[tf.dtypes.DType],
    shapes: Iterable[Optional[Shape]] = None,
    name: str = None,
) -> Union[tf.Tensor, Iterable[tf.Tensor]]:
    result = tf.py_function(func, inp, tOut, name=None)

    if shapes is not None:
        # Set shape of the output tensors.
        for tensor, shape in zip(result, shapes):
            if shape is not None:
                tensor.set_shape(tf.TensorShape(shape))

    return result
````

Note: This is not working for nested structures, which are on the other hand currently not supported by  `tf.py_function` anyway. But I will create another FR for this.

**Will this change the current api? How?**
Yes, `tf.py_function` would get another optional argument.

**Who will benefit with this feature?**
People building their `tf.data` pipeline with `tf.pyfunction`.
**Any Other info.**
I will create more `tf.py_function` related stories. Since this are distinct features from my POV, there multiple feature requests. I hope this is ok.

**Comment by jsimsa** [comment]
Re-assigning to @rohan100jain for triage.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
