### ISSUE TITLE
````ruby def hello_world  puts 'Hello World!' end ````

### ISSUE THREAD

**Issue by janonoly** [tensorflow/tensorflow#36295]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by janonoly** [comment]
````ruby
def hello_world
 puts 'Hello World!'
end
````
![吾爱淘装修论坛 _MAP-DESK-1080 (2)](https://user-images.githubusercontent.com/46779919/73330080-ad69a480-429a-11ea-9c35-f044b774e526.jpg)

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by mihaimaruseac** [comment]
spam issue
