### ISSUE TITLE
Tensorflow 2.1 Tracing Error with LSTM layer

### ISSUE THREAD

**Issue by michal-bouska** [tensorflow/tensorflow#36302]
I am implementing a tensorflow model using the keras LSTM layer.

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu
- TensorFlow version (use command below): 2.1.0
- Python version: 3.7
- GPU model and memory: CPU

**Describe the current behavior**
Method Model.predict raise warning about Tracing
```WARNING:tensorflow:5 out of the last 5 calls to <function _make_execution_function.<locals>.distributed_function at 0x7eff0c74def0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings is likely due to passing python objects instead of tensors. Also, tf.function has experimental_relax_shapes=True option that relaxes argument shapes that can avoid unnecessary retracing. Please refer to https://www.tensorflow.org/tutorials/customization/performance#python_or_tensor_args and https://www.tensorflow.org/api_docs/python/tf/function for more details.```

**Describe the expected behavior**
Same as Model.predict_on_batch

**Code to reproduce the issue**
```python
import tensorflow as tf
import numpy as np
import time

feature_dimension=2
lstm_size=256
learning_rate=0.0001

model = tf.keras.Sequential([
    tf.keras.Input([None, feature_dimension]),
    tf.keras.layers.LSTM(lstm_size),
    tf.keras.layers.Dense(1, activation='linear')
])

model.compile(loss='mean_squared_error',
              optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate),
              metrics=['mse', 'mae'])

print('Model.predict')
st = time.time()
for i in range(5,100):
    model.predict(np.array([[(0.1,0.1)]*i]*10))
print(f'Model.predict in {time.time() - st}')

print('Model.predict_on_batch')
st = time.time()
for i in range(5,100):
    np.array(model.predict_on_batch(np.array([[(0.1,0.1)]*i]*10)))

print(f'Model.predict_on_batch in {time.time() - st}')
```

**Other info / logs**
For me help use predict_on_batch method.

**Comment by gadagashwini** [comment]
Was able to replicate the issue on colab with Tf 2.1 and Tf -nightly version.
Please find the gist [here](https://colab.research.google.com/gist/gadagashwini/2799dacc09fdf988c7c40d4b72bf5d9d/36302.ipynb). Thanks!

**Comment by qlzh727** [comment]
I don't think this is the issue with LSTM. The warning also shows up when LSTM layer is removed.

The real issue is that the usage between predict() and predict_on_batch(). Since the predict() is designed to handle large data and process them one batch by one batch, under the hood, we build TF functions. Whereas for predict_on_batch, since there is only one batch, we use more light weighted approach. 

For this warning, it is expected since your input shape changes everytime, and model as to retrace the function based on that change.

See https://www.tensorflow.org/api_docs/python/tf/keras/Model?version=nightly#predict for more details and performance implication of small and large data input.
