### ISSUE TITLE
Problem with build_rpi_lib.sh

### ISSUE THREAD

**Issue by apostrophesoftware** [tensorflow/tensorflow#36336]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
PRETTY_NAME="Raspbian GNU/Linux 9 (stretch)"
NAME="Raspbian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Device - Raspberry Pi 3B
- TensorFlow clonned from git hub:
- GCC/Compiler version (if compiling from source): 6.3.0 20170519

**Describe the problem**

I am following the example to build the raspberry pi version of the Tensorflow Lite C++ library and the build script fails and the pi locks up and requires a hard reset.  There are numerous warnings displayed when the build script runs.  The last warning shown is: .tensorflow/lite/kernels/cpu_backend_gemm_customer_gemv.h:500:13 warning: attributes at the beginning of statement are ignored [-Wattribute] [[clang::fallthrough]];

Any help appreciated

**Comment by ravikyram** [comment]
@apostrophesoftware 
Can you please go through the [link](https://www.tensorflow.org/lite/guide/build_rpi) and see if it helps you. Thanks!

**Comment by apostrophesoftware** [comment]
Hello @ravikyram the link you specified is to the same page that I was using so this will not help
Thanks

**Comment by terryheo** [comment]
"build script fails and the pi locks up and requires a hard reset" doesn't look like S/W issue. Considering that compiling takes more power, I'm wondering if you're using official power supply which gives at least 2.5A current.
I had a similar experience with 1.0A power supply.

**Comment by apostrophesoftware** [comment]
Sorry I disagree, there are numerous warnings displayed.  Meaning there are clearly things the compiler does not like!

I am also using an official raspberry pi power supply and have never seen a problem like this before

**Comment by terryheo** [comment]
Compiler warning doesn't make system look up. Compiler just generates object files by reading source files with CPU computation. So there is nothing harm to system.

Fortunately, I could reproduce this problem. It works well with RPI4 but RPI3 has the problem.
The reason is RPI3 only has 1GB memory while RPI4 has 4GB memory.
So the system frozen happens by out of system memory.

There are several solutions you can choose.
1. Just build it on your workstation and copy binary.
You don't need to use RPI device to build TFLite. You can cross build RPI binary on your powerful workstation.
2. Configure Swap on your RPI device.
The virtual memory can workaround your issue but it'll super slow due to [thrashing](https://en.wikipedia.org/wiki/Thrashing_(computer_science)).
3. Build with single job
The script tensorflow/lite/tools/make/build_rpi_lib.sh has the following line.
`
make -j 4 TARGET=rpi -C "${TENSORFLOW_DIR}" -f tensorflow/lite/tools/make/Makefile
`
Using "-j 4" consumes 4 times more memory and it's not efficient when you don't have enough memory. You should remove the option.
`
make TARGET=rpi -C "${TENSORFLOW_DIR}" -f tensorflow/lite/tools/make/Makefile
`

**Comment by terryheo** [comment]
I'd better update the script. Let me handle it.
