### ISSUE TITLE
Official release of tensorflow==1.15.2 does not include GPU support

### ISSUE THREAD

**Issue by pavanky** [tensorflow/tensorflow#36347]
**System information**
- OS Platform and Distribution: Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): [binary](https://pypi.org/project/tensorflow/1.15.2/#files)
- TensorFlow version: 1.15.2
- Python version: python2, python3.6
- Installed using virtualenv? pip? conda?: pip

**Describe the problem**

As [announced](https://groups.google.com/a/tensorflow.org/forum/#!topic/developers/iRCt5m4qUz0) Tensorflow 1.15 contained GPU support by default. Tensorflow 1.15.2 no longer has GPU support.

**Comment by pavanky** [comment]
Related there is no 1.15.2 version of tensorflow_cpu: https://pypi.org/project/tensorflow-cpu/#history

**Comment by mihaimaruseac** [comment]
There has been an unfortunate change in our build scripts and 1.15.2 uses `tensorflow_gpu` for GPU and `tensorflow` for CPU.

**Comment by pavanky** [comment]
@mihaimaruseac This isnt a blocker, but it would nice if you can make an announcement about this at least.

**Comment by amahendrakar** [comment]
@pavanky,
Is this still an issue? Please please free to close it if if answers your query.

**Comment by pavanky** [comment]
@amahendrakar I can build the combined wheel if I build from source, but this is about the official release. 

I dont see the download page updated yet.

**Comment by mihaimaruseac** [comment]
For 1.15 what our scripts did was:

1. produce `tensorflow_gpu` and `tensorflow` pip package
2. upload `tensorflow_gpu` pip package as it is
3. rename `tensorflow` pip package to `tensorflow_cpu` and upload it under `tensorflow_cpu`
4. rename `tensorflow_gpu` as `tensorflow` and upload it under `tensorflow`

Both of these renames are more than just a `cp source.whl target.whl`, they also required changing the metadata in the wheel. But this process caused issues with integrity checks as filenames changed.

After 1.15.0 was released (actually, just before 2.1.0 was released) we fixed all of those issues but the fix was not backported into `r1.15`.

Currently, one could think we could attempt to manually do the steps above. Except we cannot. Pypi doesn't allow us to reuse package names (for good reasons) so once we have uploaded `tensorflow_gpu==1.15.2` and `tensorflow==1.15.2` we cannot change them around.

Actually, it is better to not do this since the move above caused `tensorflow_estimator` to depend on `tensorflow_cpu_estimator` for example (due to a bug). So if we wanted to manually do the steps above then we would need to create 3 more patch releases with no actual changes (2 for tensorflow, 1 for estimator).

We will update documentation on download page though

**Comment by pavanky** [comment]
@mihaimaruseac updating the documentation sounds good. this can be closed at that point.

**Comment by mihaimaruseac** [comment]
Documentation updated. Please let me know if there's something else to change.

Apologies again for not having a single pip anymore on 1.15

**Comment by wookayin** [comment]
But does it make sense? It is obviously unintended and bug, so with all due respect I think **we should release a hotfix (say 1.15.3) ASAP&& to provide GPU support.

Due to the promise of v1.15, some people (definitely in certain cases) the dependency specification would be just `tensorflow>=1.15` rather than `tensorflow-gpu>=1.15` hoping that it is GPU enabled. But, in such cases we might end up installing a package **without GPU**.

**Comment by wookayin** [comment]
I carefully went through the documentation and a history, and now I think it also makes a sense to revert the package consolidation behavior for 1.15.x series (which also makes a sense as this is kinda breaking change around v2.0). Given that [the documentation](https://www.tensorflow.org/install/pip) has been already updated, we should keep this one. Only remaining issues would be legacy package specification in some cases, or outdated [announcements](https://groups.google.com/a/tensorflow.org/g/developers/c/iRCt5m4qUz0). Thanks!

**Comment by metaxmx** [comment]
Hi, I also got confused and used the wrong package (tensorflow==1.15.2 without GPU support), because I read this section in the install documentation:
https://www.tensorflow.org/install/gpu#older_versions_of_tensorflow

> For the 1.15 release, CPU and GPU support are included in a single package:
> `pip install --pre "tensorflow==1.15.*"`

Please add a remark to this section, that it does not apply to the version 1.15.2 (and upwards). It's quite confusing if you explicitly state that the 1.15.x versions do NOT use a separate "-gpu" package, when in fact some of them do.

**Comment by mihaimaruseac** [comment]
Should be handled soon (with a 24hours delay due to the upgrade process). Apologies for missing that page

**Comment by jingweimo** [comment]
@mihaimaruseac  Which cuda version is compatible with tensorflow-gpu==1.15.2?

**Comment by mihaimaruseac** [comment]
It should be the same CUDA version as 2.0.

**Comment by jingweimo** [comment]
@mihaimaruseac I have tested that it works with cuda 10.0
