### ISSUE TITLE
tf.gather produces zeros for invalid indices on GPU

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#3638]
### Environment info

Operating System: Ubuntu 16.04 LTS (64 bit)

```
$ dpkg -l | grep cuda | grep ^ii
ii  libcuda1-361                                361.42-0ubuntu2                                             amd64        NVIDIA CUDA runtime library
ii  libcudart7.5:amd64                          7.5.18-0ubuntu1                                             amd64        NVIDIA CUDA Runtime Library
ii  libcudnn5                                   5.0.5-1+cuda7.5                                             amd64        cuDNN runtime libraries
ii  libcudnn5-dev                               5.0.5-1+cuda7.5                                             amd64        cuDNN development libraries and headers
ii  libcudnn5-doc                               5.0.5-1+cuda7.5                                             amd64        cuDNN documents and samples
ii  nvidia-cuda-dev                             7.5.18-0ubuntu1                                             amd64        NVIDIA CUDA development files
ii  nvidia-cuda-doc                             7.5.18-0ubuntu1                                             all          NVIDIA CUDA and OpenCL documentation
ii  nvidia-cuda-gdb                             7.5.18-0ubuntu1                                             amd64        NVIDIA CUDA Debugger (GDB)
ii  nvidia-cuda-toolkit                         7.5.18-0ubuntu1                                             amd64        NVIDIA CUDA development toolkit
```

```
$ find /usr/lib -name libcud\*
/usr/lib/i386-linux-gnu/libcuda.so.1
/usr/lib/i386-linux-gnu/libcuda.so.361.42
/usr/lib/i386-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libcudnn_static.a
/usr/lib/x86_64-linux-gnu/libcudnn_static_v5.a
/usr/lib/x86_64-linux-gnu/libcuda.so.1
/usr/lib/x86_64-linux-gnu/libcudart.so.7.5.18
/usr/lib/x86_64-linux-gnu/libcudnn.so
/usr/lib/x86_64-linux-gnu/libcuda.so.361.42
/usr/lib/x86_64-linux-gnu/libcudnn.so.5.0.5
/usr/lib/x86_64-linux-gnu/libcudart.so
/usr/lib/x86_64-linux-gnu/libcudart.so.7.5
/usr/lib/x86_64-linux-gnu/libcudadevrt.a
/usr/lib/x86_64-linux-gnu/libcudnn.so.5
/usr/lib/x86_64-linux-gnu/stubs/libcuda.so
/usr/lib/x86_64-linux-gnu/libcuda.so
/usr/lib/x86_64-linux-gnu/libcudart_static.a
```

```
$ python -c "import tensorflow; print(tensorflow.__version__)"
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:108] successfully opened CUDA library libcurand.so locally
0.10.0rc0
```
### Steps to reproduce

```
In [23]: x = tf.constant([1.1,2.2,3.3])

In [24]: a = tf.constant(123,dtype=tf.int32)

In [25]: tf.gather(x,a,validate_indices=True).eval()
Gather_8: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:818] Gather_8: /job:localhost/replica:0/task:0/gpu:0
Const_8: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:818] Const_8: /job:localhost/replica:0/task:0/gpu:0
Const_7: /job:localhost/replica:0/task:0/gpu:0
I tensorflow/core/common_runtime/simple_placer.cc:818] Const_7: /job:localhost/replica:0/task:0/gpu:0
Out[25]: 0.0

In [26]: 
```

**Comment by poxvoculi** [comment]
You are correct.  The validation is always performed, since overhead was negligible.

**Comment by girving** [comment]
To clarify: it works on CPU but not on GPU, right?  Unfortunately, while we always perform the checks on GPU, we never report those errors back to the user:

https://github.com/tensorflow/tensorflow/blob/c5f94b10bbb30e525fa3ca313e7ccb173040c90a/tensorflow/core/kernels/gather_op_gpu.cu.cc#L40

It would be great to fix this, but we didn't know how to do it in a performant fashion.

**Comment by hholst80** [comment]
So what does the CPU version do? https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/gather_op.cc

I was not expecting a zero as return when I sent in a out of bounds index. NaN maybe but not zero.

**Comment by girving** [comment]
@hholst80 The CPU gives you an exception independent of what you're using (True or False).  This is to avoid crashing.  NaN would be reasonable, but the real fix would be to get an actual exception to bubble back up to the CPU from the GPU.

**Comment by josh11b** [comment]
I neither have the context for this bug, nor am I going to be able to get to this in a reasonable time frame.

**Comment by girving** [comment]
I don't know enough about GPUs to solve this one.  @zheng-xq Can you triage?

**Comment by zheng-xq** [comment]
This is an area that is contribution welcome. We cannot have GPU synchronize with CPU. There are a few ways: 

1. Trigger a "trap" instruction on GPU, which triggers an interrupt on the host CPU. 
2. Allocated a pinned memory on CPU, and write the error status from GPU in the kernel. During the launch, also schedule an asynchrous functor to check the status through "ThenExecute".

**Comment by hholst80** [comment]
I'd love to see GPU doing the same thing as the CPU code is doing, but as I said, the flag is unnecessary since it does not do anything on neither GPU nor CPU (and this behavior is undocumented as well).

If the exception thingy from GPU is too hard to do right now just put a NaN here instead of T(0)?
https://github.com/tensorflow/tensorflow/blob/c5f94b10bbb30e525fa3ca313e7ccb173040c90a/tensorflow/core/kernels/gather_op_gpu.cu.cc#L41

Silent and undetectable failure is dangerous...

**Comment by ibab** [comment]
Here's an older issue that can be closed once this one is fixed: https://github.com/tensorflow/tensorflow/issues/3067

**Comment by ibab** [comment]
@hholst80: You can only put `NaN` into the output if `T` is a floating point type, so I'm afraid that the idea can't work for all types :(

@zheng-xq: Do you know whether it's possible to somehow signal an error in TensorFlow after `OpKernel::Compute()` has already finished? It seems that this might not be possible through the `OpKernelContext`, as it's only guaranteed to live roughly until the end of `OpKernel::Compute()`.
From reading the `Executor` code at https://github.com/tensorflow/tensorflow/blob/00700f00fdf71baec1342d1afd7849e16fbd2a33/tensorflow/core/common_runtime/executor.cc#L1210 it doesn't seem like there's an opportunity to pass a `Status` from our asynchronous functor to the `Executor`, but I might be wrong here.

**Comment by zheng-xq** [comment]
If someone really wants to have this kernel report errors, here are some more details:

1. Add non-default attribute so the kernel can optional synchronize with GPU and check errors. 
2. A more TensorFlow way is to change the kernel AsyncOpKernel, and check the errors and call "done" through ThenExecute. That way, the current thread is released to do other work. But ops following gather still cannot issue. 
3. Still use the sync OpKernel, schedule ThenExecute to check for the error. The down-side is the context is long gone at that point. So you can print out enough error message and crash the process with LOG(FATAL). 

I will leave it up to the contributor/developer to choose from those. But it is important that by default, we don't synchronize and hold off other kernel launches unnecessarily.

**Comment by ibab** [comment]
Thanks!
I think the checking shouldn't be optional, otherwise users will keep running into problems, so that would rule out option 1.
Option 2 still blocks ops that depend on gather. I think we should try to avoid this if we can.
Option 3 sounds good, but a `LOG(FATAL)` would crash the interpreter that the user might be running TensorFlow in, which isn't very nice. (But maybe this is easy to fix?)

I've also thought of writing a `CheckGather` op, which performs the index checking separately from `Gather`. It could be launched alongside `Gather` from a Python wrapper.
This could either always run on the CPU, or synchronize with the GPU, possibly as an AsyncOpKernel as you've explained.

Maybe the cleanest option would be to modify `Executor` slightly to add support for asynchronous error reporting.
For example, we could add a `Status` protected by a mutex to `Executor` that's specifically designed for asynchronous error reporting. The op's `Compute` method could then pass the `Status` into a callback that's executed as part of the CUDA stream. The `Executor` would then check the `Status` after it synchronized the computation.
I'm not sure how useful this change would be for ops other than `Gather`, though.

**Comment by zheng-xq** [comment]
I've talked to my colleagues about modifying executor. It is trickier than we would like. 

At this point, I think option 3 with LOG(FATAL) is the path with the least potential problems. I agree that it is not clean. But there are plenty of CHECK in TensorFlow, which does essentially the same thing. So if we put debugging information in that error message, perhaps it is more useful to people than it is today.

**Comment by girving** [comment]
@zheng-xq Actually we've done quite a bit of work to remove `LOG(FATAL)` uses that can be triggered by the user.  The policy is that they should all be unreachable.  It would be a shame if `gather` did this.

**Comment by zheng-xq** [comment]
In that case, maybe we could explore the async error reporting as @ibab mentioned. The tricky part is that we need to hold executor to wait for all the error checks to finish at the end. Otherwise, the run could finish  successfully before the async error checking. And we need to be very careful that we don't cause a deadlock.

**Comment by Fenugreek** [comment]
I ran into this issue today (on v1.0). 

If no fix is on the horizon, I suggest either removing the `validate_indices` option or mentioning in the API docs that it works only on CPU for now, as that helps with debugging (otherwise people will think their problem lies elsewhere, trusting that the indices must be valid).

**Comment by girving** [comment]
@Fenugreek Interested in contributing a doc fix?

**Comment by Fenugreek** [comment]
@girving Yes. A bit busy today but will get back by early next week.

**Comment by Fenugreek** [comment]
@girving I feel a little stupid but after 15+ minutes of looking I can't find where the docs for `tf.gather` live. They're not in `python/ops/array_ops.py`. Any tips?

**Comment by josh11b** [comment]
tensorflow/core/ops/array_ops.cc

**Comment by Fenugreek** [comment]
Cool, thanks for the pointer @josh11b . I am hoping to submit a pull request for the doc fix in a day or so, looking to be consistent with docs elsewhere Re: GPU vs CPU differences/limitations.

**Comment by Fenugreek** [comment]
This is my proposed addition to the `tf.gather` doc in array_ops.cc:

---

`validate_indices`: DEPRECATED. If this operation is assigned to CPU, values in 
`indices` are always validated to be within range. If assigned to GPU,
out-of-bound values in `indices` currently result in output values of `0`.

---
Given @hholst80 's comment on Aug 5, 2016 above, and confirming by looking at the CPU and GPU .cc source, the above seems the most complete doc. We may prefer to avoid saying that current fallback value on GPU is `0`, in case people start depending on it.

The above fix is in my fork at `github.com/Fenugreek/tensorflow`. I expect there will be comments resulting in changes, so I am holding off making a pull request.

**Comment by girving** [comment]
Looks good.  Maybe change the GPU sentence to

> If assigned to GPU, out-of-bound indices result in unspecified behavior (currently the result is 0, but this may become an error in future).

**Comment by Fenugreek** [comment]
Ok, changed it as so and put in the associated pull request #8646 .

**Comment by girving** [comment]
Related bug with the same "how to signal errors on GPU" problem: https://github.com/tensorflow/tensorflow/issues/3638.

**Comment by MattShannon** [comment]
What about unifying the GPU and CPU implementations of gather by always returning 0 for out-of-bound indices, then having a separate op which checks indices with a CPU-only implementation. That way you get consistent behavior, error propagation if desired and a clean interface.

That would also allow "conditional gather"-type operations relatively easily, where a default value is used for indices that are out of range, such as:

tf.gather(xs, indices) + (indices >= tf.shape(xs)[0]) * 2.0

At the moment conditional gather operations like this is tricky on the CPU, since error checking is always done.

**Comment by Androbin** [comment]
@MattShannon Well, your idea seems legit, but I don't get how you would differentiate between a "real" zero value and a "fake" zero value. Although this would be a reasonable fallback behavior for out-of-range indices, it should always be a conscious decision, else we end up with silent errors.

Ideally, we would have a "special value" other than zero:
* one available for all dtypes OR one for each dtype
* presumably unused by any "non-special behavior" code

Then we could wrap it with handlers like the ones you brought up.

**Comment by MattShannon** [comment]
My idea was that there are two ops. The gather op is changed to be forgiving, i.e.g both GPU and CPU it returns zero whenever an index is out-of-bounds. A separate op (say "check_indices") with only a CPU implementation determines whether the gather is "valid" (i.e. no out-of-bounds lookups, in the same way that the current CPU implementation does (iiuc).

For some applications, forgiving gather is exactly what you want. It is simple to turn this into something which uses a user-specified default value instead of 0, using something like the code snippet above. Afaict, forgiving gather is currently quite hard to effect in tensorflow.

tf.gather can be implemented in terms of forgiving gather and check_indices. This preserves the current CPU behavior, and extends that to the GPU case, fixing this bug.

**Comment by Androbin** [comment]
> A separate op (say "check_indices") with only a CPU implementation ...

If this op is forced to be run on CPU, it could slow down the computation due to additional data transfers between CPU and GPU. I can't assess the impact this might have, but this effect should be considered.

**Comment by MattShannon** [comment]
Yeah, I agree that's something to bear in mind. The motivation for my suggestion was just that: (a) I think it's uniformly better than the current situation where the GPU implementation is nominally "incorrect" (doesn't check indices); and (b) I think the current GPU behavior ("forgiving gather") is actually a great op to have.

The procedure to check indices could consist of an op which outputs a boolean (whether the indices were valid) and has a GPU implementation, and a CPU-only op which takes that and actually raises the error. This avoids any large GPU to CPU transfer.

**Comment by alextrevithick** [comment]
I am currently using this quirk of the gather op because I want to have identically 0 tensors if the index is out of bounds. Is this bad from a performance perspective?

**Comment by mohantym** [comment]
Hi @hholst80! 
We are checking to see whether you still need help in this issue . It will raise error in CPU and render zero in GPU .Attaching [Gist ](https://colab.research.google.com/gist/mohantym/6676d460c5572bdce10857982b99a856/github_3638.ipynb)and [Reference ](https://www.tensorflow.org/api_docs/python/tf/gather#args).Thanks!
