### ISSUE TITLE
Integer random_uniform

### ISSUE THREAD

**Issue by lespeholt** [tensorflow/tensorflow#364]
Feature request:

Support for dtype=tf.int32/int64 in tf.random_uniform.

**Comment by girving** [comment]
Yep, we want this internally too.

**Comment by michaelguia** [comment]
Would the upper bound be configurable? What sort of range would be a good default?

**Comment by girving** [comment]
This is done, and should be out in git soon.  `tf.random_uniform` now works for `int32` and `int64`.  Like the floating point case, it takes a half open range as `[minval, maxval)`.  In the integer case, `maxval` must be specified (it does not default to 1, since random zeros are not particularly useful).

**Comment by girving** [comment]
@michaelguia: That is, I don't know a good default range for the integer case (at least on the top), so I made it required.
