### ISSUE TITLE
Build tensorflow error with keras api

### ISSUE THREAD

**Issue by phamkhactu** [tensorflow/tensorflow#36438]
### I build tensorflow follow [link](https://www.tensorflow.org/install/source)
1. use r2.0
1. bazel 0.25.0
1. CUDA Version: 10.0 
1. ubuntu 18.04
Here my error
```
ERROR: /root/tensorflow/tensorflow/python/keras/api/BUILD:13:1: Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed (Exit 1)
Traceback (most recent call last):
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/tools/api/generator/create_python_api.py", line 27, in <module>
    from tensorflow.python.tools.api.generator import doc_srcs
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/__init__.py", line 83, in <module>
    from tensorflow.python import keras
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/__init__.py", line 32, in <module>
    from tensorflow.python.keras import datasets
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/datasets/__init__.py", line 25, in <module>
    from tensorflow.python.keras.datasets import imdb
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/datasets/imdb.py", line 25, in <module>
    from tensorflow.python.keras.preprocessing.sequence import _remove_long_seq
  File "/root/.cache/bazel/_bazel_root/efb88f6336d9c4a18216fb94287b8d97/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/keras/preprocessing/__init__.py", line 21, in <module>
    import keras_preprocessing
ModuleNotFoundError: No module named 'keras_preprocessing'
Target //tensorflow/tools/pip_package:build_pip_package failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 11062.314s, Critical Path: 746.52s
INFO: 17931 processes: 17931 local.
FAILED: Build did NOT complete successfully

```

**Comment by wdirons** [comment]
Are you sure you ran `pip install -U --user keras_preprocessing --no-deps`?  That is included in the instructions you linked.

**Comment by phamkhactu** [comment]
Yes
```
Installing collected packages: keras-preprocessing
Successfully installed keras-preprocessing-1.1.0

```

**Comment by wdirons** [comment]
Can you run `pip show keras-preprocessing` and does the value in `Location`  match the value in `.tf_configure.bazelrc` for `build --action_env PYTHON_LIB_PATH` ?

**Comment by phamkhactu** [comment]
### here is it
```
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: Keras-Preprocessing
Version: 1.1.0
Summary: Easy data preprocessing and data augmentation for deep learning models
Home-page: https://github.com/keras-team/keras-preprocessing
Author: Keras Team
Author-email: None
License: MIT
Location: /root/.local/lib/python3.6/site-packages
Requires: numpy, six
Required-by: 
```

**Comment by wdirons** [comment]
And `cat .tf_configure.bazelrc` show what?

When you ran `./configure`

For `Please input the desired Python library path to use.` the answer should have been `/root/.local/lib/python3.6/site-packages` as that is the location where the python package are installed.

**Comment by skrishnauccsedu** [comment]
Running into the same error
 Executing genrule //tensorflow/python/keras/api:keras_python_api_gen failed 
 
Aditionally there is an import error, might be the same issue
ImportError: cannot import name 'gen_checkpoint_ops' from 'tensorflow.python.ops' (/private/var/tmp/_bazel_nikhilchitlurnavakiran/ed132e8d3b760bae902e7d17da8676dc/execroot/org_tensorflow/bazel-out/host/bin/tensorflow/python/keras/api/create_tensorflow.python_api_1_keras_python_api_gen.runfiles/org_tensorflow/tensorflow/python/ops/__init__.py)

going through the above discussion have listed the commands to verify

**pip3 install -U --user keras_preprocessing --no-deps** 
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Requirement already up-to-date: keras_preprocessing in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (1.1.0)

**pip3 show keras-preprocessing**                        
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Name: Keras-Preprocessing
Version: 1.1.0
Summary: Easy data preprocessing and data augmentation for deep learning models
Home-page: https://github.com/keras-team/keras-preprocessing
Author: Keras Team
Author-email: None
License: MIT
Location: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages
Requires: six, numpy
Required-by: tensorflow

**cat .tf_configure.bazelrc**
build --action_env PYTHON_BIN_PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
build --action_env PYTHON_LIB_PATH="/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages"
build --python_path="/Library/Frameworks/Python.framework/Versions/3.7/bin/python3"
build:xla --define with_xla_support=true
build --config=xla
build:opt --copt=-march=native
build:opt --copt=-Wno-sign-compare
build:opt --host_copt=-march=native
build:opt --define with_default_optimizations=true
test --flaky_test_attempts=3
test --test_size_filters=small,medium
test --test_tag_filters=-benchmark-test,-no_oss,-oss_serial
test --build_tag_filters=-benchmark-test,-no_oss
test --test_tag_filters=-gpu,-nomac,-no_mac
test --build_tag_filters=-gpu,-nomac,-no_mac
build --action_env TF_CONFIGURE_IOS="0"

**Comment by amahendrakar** [comment]
@phamkhactu,
Any updates regarding this issue? Thanks!

**Comment by amahendrakar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by evdcush** [comment]
What is it with this bizarre coupling of keras to tensorflow (especially in TF 2.0)? TensorFlow should just be TensorFlow... 2.0 didn't make me use keras anymore than I did before. It just made me start using pytorch.
