### ISSUE TITLE
Cannot install tensorflow go

### ISSUE THREAD

**Issue by glarchev** [tensorflow/tensorflow#36495]
This is a continuation of a similar issue (#35133 ) but the missing package is now different. It appears that the fix has involved substituting one go dependency for another -- however, the new package also cannot be found:

`go get github.com/tensorflow/tensorflow/tensorflow/go
package github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto: cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto" in any of:
	/usr/local/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOROOT)
       /Users/admin/go/src/github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto (from $GOPATH)`

**Comment by jhseu** [comment]
Please follow the Go README:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/go/README.md

You need to generate the proto files. That means you must use `go get -d` to download only and then use `go generate` to BUILD the proto .go files.

**Comment by gadagashwini** [comment]
@glarchev, Did you get a chance to check @jhseu's comment. Thanks

**Comment by glarchev** [comment]
@gadagashwini I did not. I may come back to it, but this solution is not ideal for me (see latest comments in #35133 for more detail).

**Comment by glarchev** [comment]
@gadagashwini I tried to go through the install process just to see if it works, and it failed on the `./configure` step because it expects bazel version 2.0.0, and I have 2.1.0. So it wants me to downgrade my bazel version, which I shouldn't have to do.

**Comment by groud** [comment]
Hi, I have the same problem when I go through the installation process. I first had this error message: `cannot find package "github.com/tensorflow/tensorflow/tensorflow/go/core/core_protos_go_proto"`.

So I followed the steps to builds things from source instead and had the error about the bazel version (I had bazel 2.2.0 instead of the request 2.0.0), but removing the .bazelversion files solved the problem.

Following the remaining allowed tensorflow for go to be installed correctly, though it was annoying to have to build everything from source.

**Comment by malanb5** [comment]
@groud @glarchev fyi you can use https://github.com/bazelbuild/bazelisk bazelisk instead of install a specific installation of bazel.  This is a wrapper around bazel which will automatically install and use the correct version of bazel for your project.  Just put a .bazelversion with the desired version in your project root folder.  Still figuring this one out.  Let me know if you get anywhere with this please.

**Comment by longkeyy** [comment]
cd $GOPATH/src/github.com/tensorflow/tensorflow

git checkout v2.1.0

**Comment by boratanrikulu** [comment]
@longkeyy thanks a lot! that works.

**Comment by Saduf2019** [comment]
@glarchev 
Please move this issue to closed status if resolved.
