### ISSUE TITLE
Tensorflow 1.15 doesn't do incremental memory growth

### ISSUE THREAD

**Issue by CMCDragonkai** [tensorflow/tensorflow#36501]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): NixOS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): unknown 1.15.0
- Python version: 3.7.6
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2.89
- GPU model and memory: RTX 2070 - 440.44

**Describe the current behavior**

I'm trying to activate incremental memory growth. However in all the ways I've done it, it always ends up allocating almost the entire GPU.

```python
import tensorflow as tf
import tensorflow.keras as keras
import tensorflow.keras.applications as applications
import tensorflow.keras.utils as utils
import numpy as np

num_samples = 1000
height = 224
width = 224
num_classes = 1000

config = tf.compat.v1.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.compat.v1.Session(config=config)
keras.backend.set_session(sess)

# gpus = tf.config.experimental.list_physical_devices('GPU')
# for gpu in gpus:
#     tf.config.experimental.set_memory_growth(gpu, True)
# logical_gpus = tf.config.experimental.list_logical_devices('GPU')

model = applications.ResNet50(weights=None, input_shape=(height, width, 3), classes=num_classes)

parallel_model = utils.multi_gpu_model(model, gpus=2, cpu_relocation=True)
parallel_model.compile(loss='categorical_crossentropy', optimizer='rmsprop')

x = np.random.random((num_samples, height, width, 3))
y = np.random.random((num_samples, num_classes))

parallel_model.fit(x, y, epochs=20, batch_size=2)

print('all done')
```

As I watch `nvidia-smi`, I always see almost the entire GPUs allocated.

This is true for the compat v1 and for the new tf.config.experimental commands and also for the environment variable `TF_FORCE_GPU_ALLOW_GROWTH`.

The only one that has any effect is `config.gpu_options.per_process_gpu_memory_fraction = 0.5`.

In all other cases I see the the GPU memories get used up entirely and I get these messages:

```
2020-02-06 15:48:35.517899: I tensorflow/stream_executor/cuda/cuda_driver.cc:831] failed to allocate 3.18G (3411184640 bytes) from device: CUDA_ERROR_OUT_OF_MEMORY: out of memory
```

**Comment by sanjoy** [comment]
> As I watch `nvidia-smi`, I always see almost the entire GPUs allocated.

`allow_growth` only means that TF will *start off* with allocating only part of the GPU memory, but there is no limit to how much of the GPU memory it can use over the execution of the program (i.e. over time, the GPU memory usage can grow).  Is this what you are observing?  If so, I think this is WAI.

To keep TF from allocation more than half the GPU for the lifetime of the process, you need to use `per_process_gpu_memory_fraction`, as you said you are doing.

> In all other cases I see the the GPU memories get used up entirely and I get these messages:

Are these fatal errors or does the program continue to work?  TF often tries to allocate memory speculatively to use as workspace for cuDNN convolutions, but if the allocation fails it just falls back to a slower algorithm that uses less memory.  So if the OOM warnings are non-fatal then this is WAI too, although it does indicate the logging output could be made more helpful.

**Comment by CMCDragonkai** [comment]
This behaviour is different from before. When allow memory growth was enabled I saw a progressive incremental gpu memory growth. But now its instantly all the gpu memory. So the errors are non fatal. But previously I didn't need to enable this for tf to work on rtx 2070.

On 13 February 2020 18:29:22 GMT+11:00, Sanjoy Das <notifications@github.com> wrote:
>> As I watch `nvidia-smi`, I always see almost the entire GPUs
>allocated.
>
>`allow_growth` only means that TF will *start off* with allocating only
>part of the GPU memory, but there is no limit to how much of the GPU
>memory it can use over the execution of the program (i.e. over time,
>the GPU memory usage can grow).  Is this what you are observing?  If
>so, I think this is WAI.
>
>To keep TF from allocation more than half the GPU for the lifetime of
>the process, you need to use `per_process_gpu_memory_fraction`, as you
>said you are doing.
>
>> In all other cases I see the the GPU memories get used up entirely
>and I get these messages:
>
>Are these fatal errors or does the program continue to work?  TF often
>tries to allocate memory speculatively to use as workspace for cuDNN
>convolutions, but if the allocation fails it just falls back to a
>slower algorithm that uses less memory.  So if the OOM warnings are
>non-fatal then this is WAI too, although it does indicate the logging
>output could be made more helpful.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tensorflow/tensorflow/issues/36501#issuecomment-585589881

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sanjoy** [comment]
> This behaviour is different from before. When allow memory growth was enabled I saw a progressive incremental gpu memory growth.

It would be nice to have some more information here (what TF versions are you comparing?) but ultimately I'm not sure if there is much for us to do here.  The could just be a matter of the executor executing the graph in a different order.

**Comment by CMCDragonkai** [comment]
Are you implying that memory growth is not happening any more on 1.15 and RTX2070. Cause that's what the option says. But it immediately allocates all memory.

On 15 February 2020 17:46:21 GMT+11:00, Sanjoy Das <notifications@github.com> wrote:
>> This behaviour is different from before. When allow memory growth was
>enabled I saw a progressive incremental gpu memory growth.
>
>It would be nice to have some more information here (what TF versions
>are you comparing?) but ultimately I'm not sure if there is much for us
>to do here.  The could just be a matter of the executor executing the
>graph in a different order.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/tensorflow/tensorflow/issues/36501#issuecomment-586560852

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by sanjoy** [comment]
> Are you implying that memory growth is not happening any more on 1.15 and RTX2070.

allow_growth is a core TF level setting.  When it is set to false (default) TensorFlow itself allocates almost all of the GPU memory into its memory pool and uses this memory pool to satisfy memory allocation requests from the various GPU kernels.  When it is set to true then TF starts of allocating only a small amount of memory into the pool, and expands the pool as needed (e.g. if the pool has 1G of memory free and a GPU kernel wants 2G of memory then TF will allocate 1G more from the GPU runtime).

However, allow_growth has no bearing on how much memory will actually be demanded by GPU kernels.  As an extreme example, if you have a GPU kernel that by itself needs all the memory the GPU has available, then irrespective of whether allow_growth is true or false, the program will immediately consume all of the GPU's memory when this kernel runs.

I suspect that this is what is happening here.  We have not stopped respecting allow_growth, but the newer cuDNN probably has some algorithms that ask for more scratch memory in order to run faster.

Specifically, if I disable autotuning by setting the environment variable `TF_CUDNN_USE_AUTOTUNE` to `false` then the memory use stabilizes to 1857MiB (on my Titan-V).  If you are okay with the performance hit of disabling autotuning then this could be a good workaround for you.

**Comment by alankongfq** [comment]
@CMCDragonkai -- I also faced the same issue as you. 
I had ported code from tf 1.15 to tf 2.1 and tried running the same code that work on my other machine. Following the tensorflow guide at https://www.tensorflow.org/guide/gpu, i had tried these 2 block of codes:

code 1
```
gpu_options = tf.compat.v1.GPUOptions(per_process_gpu_memory_fraction=gpu_max_mem, allow_growth=True)
sess = tf.compat.v1.Session(config=tf.compat.v1.ConfigProto(gpu_options=gpu_options))
```
code 2
```
gpus = tf.config.experimental.list_physical_devices('GPU')
if gpus:
     # Restrict TensorFlow to only use the first GPU
     try:
         # Currently, memory growth needs to be the same across GPUs
         for gpu in gpus:
             tf.config.experimental.set_memory_growth(gpu, True)
         tf.config.experimental.set_visible_devices(gpus[0], 'GPU')
         logical_gpus = tf.config.experimental.list_logical_devices('GPU')
         print(len(gpus), "Physical GPUs,", len(logical_gpus), "Logical GPU")
     except RuntimeError as e:
         # Visible devices must be set before GPUs have been initialized
         print(e)
```
Both code blocks allocated all GPU memory instead of my previously observed behavior of incremental increase in the GPU memory before inference. (During inference, the model do take up most of the memory space.)

At the moment, what work for me was setting the environment variable ```TF_FORCE_GPU_ALLOW_GROWTH = "true"```

I noticed this changes when there was some update to my nvidia driver, cuda and cudnn.
MACHINE 1
nvidia_driver ver = 440.64.00
cuda = 10.1.243
cudnn =7.6.5
tf 2.1.1
python = 3.7.3


when I tried it on another machine with specs below, the behaviour was expected without any setting of the environment variable ```TF_FORCE_GPU_ALLOW_GROWTH = "true"```
MACHINE 2
nvidia_driver ver = 440.64.00
cuda = 10.0.130
cudnn =7.6.5
tf 1.15
python = 3.7.3

**Comment by srwiley** [comment]
I found I needed to add  the following to the classification.ipynb notebook in the docs in order to get it to work. Otherwise the model would throw a CUDA_ERROR_OUT_OF_MEMORY error during initialization, even though there should have been plenty of memory.

> import os
> 
> os.environ['TF_FORCE_GPU_ALLOW_GROWTH'] = 'true'

My system information:
 == nvidia-smi ===================================================
Sun Nov  8 11:58:14 2020       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.80.02    Driver Version: 450.80.02    CUDA Version: 11.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 780     Off  | 00000000:01:00.0 N/A |                  N/A |
| 34%   33C    P8    N/A /  N/A |   2767MiB /  3018MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 780     Off  | 00000000:02:00.0 N/A |                  N/A |
| 34%   30C    P8    N/A /  N/A |     67MiB /  3022MiB |     N/A      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================
/usr/local/cuda-10.0/doc/man/man7/libcudart.so.7
/usr/local/cuda-10.0/doc/man/man7/libcudart.7
/usr/local/cuda-10.0/lib64/libcudart.so.10.0.130
/usr/local/cuda-10.0/lib64/libcudart_static.a

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.2.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: /home/swiley/.conda/envs/tf-gpu/lib/python3.8/site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 8, 5, 'final', 0)

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
