### ISSUE TITLE
[CI] Ubuntu CPU is still "Expected — Waiting for status to be reported" after 14 days.

### ISSUE THREAD

**Issue by leemgs** [tensorflow/tensorflow#36527]
It is strange. Please look at the execution status (**See the red rectangle below)** of the Tensorflow CI on  PR #36186.  The work status of **Ubuntu CPU** and **Ubuntu Sanity** checker are still running. The current status of two checkers is "**Expected — Waiting for status to be reported**" even though 14 days is passed after the contributor submitted PR #36186. Why do not these checkers report the execution result either PASS or FAILURE? As we all know the 14 days are not reasonable to us. And, it will be helpful to the reviewers?

![image](https://user-images.githubusercontent.com/82404/74004185-65443380-49b8-11ea-986c-58791e241d50.png)

Above all, many PRs do not have been getting the test result from the CI checkers in time.  It seems that the TensorFlow community does not have Cloud instances enough to run CI checkers whenever PRs are submitted by the contributors. Or because of the unstable CI system.

**Comment by ravikyram** [comment]
@leemgs 
First PR has to be approved by the reviewer. Then CI checks will run automatically and PR process will take it forward accordingly.Thanks!

**Comment by leemgs** [comment]
@ravikyram, I wonder why the CI checks start the execution after the reviewers approve PRs. Let's assume that a PR of contributor has a build error. Is it meaningful the execution sequence of the existing CI checks to help reviewers?  I thnik that the most of the automatic CI checks have to be run before reviewers start reviewing PRs.

**Comment by leemgs** [comment]
Here is another case on (1) the merging time of the PR and (2) the execution time of the CI checks. 

- (1) PR https://github.com/tensorflow/tensorflow/pull/36523: About the merging time
   - When the reviewer **frankchn** of two reviewers approved the PR, The CI checks work. Then, all checks are passed. It seems that the PR is still not merged due to the 1 pending reviewer (**gunan**). In this case, what are the criteria to merge this PR as a final step?
   - Screenshot:
      ![image](https://user-images.githubusercontent.com/82404/74029403-f7b3f980-49ef-11ea-81cc-c57e2673b4e2.png)

- (2) PR https://github.com/tensorflow/tensorflow/pull/33524 : About the execution cost of CI checks
   - It's weird. When **omalleyt12** approved the PR 33524, the three checks are still keeping the "Waiting for status ...." after 2hour. Why do not CI checks start a task? Does the CI system require 2hour+ to check the PR status?
      - Ubuntu CPU Expected — Waiting for status to be reported  Required
      - Ubuntu Sanity Expected — Waiting for status to be reported Required
      - import/copybara Expected — Waiting for status to be reported
   - Screenshot: 
      ![image](https://user-images.githubusercontent.com/82404/74030714-1071de80-49f3-11ea-9861-415988076e32.png)

**Comment by rthadur** [comment]
@leemgs thank for your concern , please post questions regarding tensorflow library. It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). Thank you for your cooperation.
cc @mihaimaruseac @chanshah

**Comment by mihaimaruseac** [comment]
@leemgs There is a long process around accepting PRs. There are costs associated with it, but the costs of not following the process are more harmful to Google.

First, you must keep in mind that CI runs on Google infrastructure and can impact Google in multiple ways. As such, it must not be triggered unless a Googler vouches that the PR is not malicious. This is why no CI except sanity check runs before the first green review.

Second, you must keep in mind that there are hundreds of PRs in flight daily and they use CI infrastructure that is also shared by people developing TensorFlow inside Google. So we are looking at high hundreds of CI process running in a day. Add to this the fact that CI needs to take a very long time. This is way CI only runs by default once PR is approved or once the `kokoro:force run` label is applied.

Finally, even after PR is approved and all CI passes, there are 2 more steps to do: first is to import the change inside Google and integrate it with the Google internal version of TensorFlow (that's what Copybara does). Then this needs another approval and another round of CI run (because sometimes the integration cannot be automated and there is an engineer that does it manually). The import only happens if `ready to pull` tag is automatically applied and that tag is only applied when all reviewers on the PR have approved it.

This process is in place for security reasons and also because there are many concerns related to a PR. There are multiple areas that should be analyzed (for example API changes are discussed in API steering meetings, C++ code is analyzed for style guide by one person and for suitability with the rest of the code by another, etc.).

If this seems too long, note that we are exporting the [scripts used for these CI checks](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/ci_build/presubmit) and you could attempt to run them manually.

Hope this clarifies the entire process.

**Comment by leemgs** [comment]
>  Please resubmit your issue using a template from here. Thank you for your cooperation.

@rthadur, Got it. Since @mihaimarusea already explained Google infrastructure status for CI, The shared scripts for the manual run test in case of long CI checks, and the security reasons for the issue 36527 that is posted by me. So, I will follow up the template that you commented on from the next issue. 

> There are costs associated with it, but the costs of not following the process are more harmful to Google.

@mihaimaruseac,  Before posting this issue, I thought that Google Tensorflow community already has been used many GCP (Google Cloud Platform) instances enough for massive/popular Tensorflow deep-learning framework because Google has lots of GCP instances as global cloud infrastructure.

> Finally, even after PR is approved and all CI passes, there are 2 more steps to do: 

@mihaimaruseac, Although this issue is closed by @rthadur 10 hours ago, I want to post my comment on your reply. 
We all know that the reviewers must consume their valuable time to approve the malicious/pre-mature/bad/unstable PRs if the reviewers verify and approve the PRs first without the assistance of automated CI facilities.
