### ISSUE TITLE
Error when installing: ERROR: tensorflow-2.1.0-cp27-cp27m-macosx_10_15_intel.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by namedtoaster** [tensorflow/tensorflow#36607]
Running Mojave 10.14.6
Tensorflow installed from source (via https://www.tensorflow.org/install/source from cloning the repo)
Python 2.7.15
Installed using pip
Bazel version 1.2.1
Clang version 11.0.0
Intel Iris 1536 MB

When trying to build tensorflow from this [link](https://www.tensorflow.org/install/source) I was able to get through all steps until actually installing using pip. Everything went relatively smoothly although it took a while (although it did take about 5 hours).

I was excited to finally get to the end but was disappointed because pip couldn't install the package giving me the following error:

`ERROR: tensorflow-2.1.0-cp27-cp27m-macosx_10_15_intel.whl is not a supported wheel on this platform.`

I googled the error and searched through the list of other similar issues but most of the issues were either old or didn't apply to the same os.

How do I fix this?

**Comment by Saduf2019** [comment]
@namedtoaster Could you please provide the exact sequence of commands / steps that you executed before running into the problem [the pip command where you faced the issue]

**Comment by namedtoaster** [comment]
The command I ran was `pip install /tmp/tensorflow_pkg/tensorflow-2.1.0-cp27-cp27m-macosx_10_15_intel.whl
`
The commands I ran up to that were:
`./configure` - I selected the default options for the first few steps then selected "N" for the follow on Y/N questions
`bazel build //tensorflow/tools/pip_package:build_pip_package`
`./bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg`

And then the pip command.

**Comment by freedomtan** [comment]
@namedtoaster According to your message, you are running macOS 10.14 and trying to install a 10.15 pip wheel. Either upgrade your OS (`Mojave 10.14.6` --> `10.15`) or use a `macosx_10_15` pip wheel.

**Comment by Saduf2019** [comment]
@namedtoaster  Please let us know if the above comment helps resolve the issue.

**Comment by namedtoaster** [comment]
@freedomtan @Saduf2019 thanks I just got the update on my Mac book working on installing it now. Once I can test again I’ll let you know

**Comment by namedtoaster** [comment]
Updating to macos 10.5 Catalina fixed my problem. Thanks for the help

**Comment by mesmerli** [comment]
For your reference, I change the file name to tensorflow-2.1.0-cp37-cp37m-macosx_10_14_x86_64.whl from tensorflow-2.1.0-cp37-cp37m-macosx_10_15_x86_64.whl, and the whl can be installed in OSX 10.14 without any issues.

The whl file is built in the same machine with OSX 10.14.
It is weird to generate such whl file with macos_10_15 in its file name.
I believe that could be a bug of TensorFlow, especially when the whl file can work in OSX 10.14 actually.

It could not recommended to upgrade the OSX to 10.15 for this issue of TensorFlow, because the Eigen library in the TensorFlow package could get problems due to a Clang bug about AVX instructions in OSX 10.15.
[http://manao.inria.fr/eigen_tmp/pullrequests/748/(http://manao.inria.fr/eigen_tmp/pullrequests/748/)

Per the bug report, the Eigen library works fine in OSX 10.14.
