### ISSUE TITLE
How to create new cuda stream in custom op

### ISSUE THREAD

**Issue by chaaland** [tensorflow/tensorflow#36634]
I've written a custom op for the GPU that takes X with shape ```(n,p)``` and Y with shape ```(m,p)``` and returns Z with shape ```(n,m)```. 

In the backward pass, dX and dY are independent computations so I'd like to have launch two separate CUDA kernels and have them run in separate streams. I know the cuDNN RNN is capable of doing kernels in parallel but I cannot find the source code for how to do this. It seems the only usable stream is provided by the OpKernelContext. 

Matrix multiplication must have a similar parallelism when doing the backward pass but I have not found anywhere in the source making use of multiple streams. This is essentially a reopening of [this issue](https://github.com/tensorflow/tensorflow/issues/6675) as there doesn't appear to a public answer

**Comment by gadagashwini** [comment]
@chaaland, Please take a look at [this doc](https://www.tensorflow.org/guide/create_op#gpu_kernels). Thanks!

**Comment by chaaland** [comment]
Thanks for the link. I've referenced this doc many times while developing the op but I don't see where it specifies how to generate two CUDA streams. The call to ```d.stream()``` just returns a stream that has already been created rather than creating a new stream (which is what I think I'd need).

I'm open to any other way to get the dX and dY computations running in parallel as well. Currently I have something like the below which appears to be running in serial

```c++
const cudaStream_t& cu_stream = GetCudaStream(ctx);
dx_bprop<<<griddim, blockdim, 0, cu_stream>>>(...);
dy_bprop<<<gridim, blockdim, 0, cu_stream>>>(...);
```

**Comment by chaaland** [comment]
Any updates on this?

**Comment by chaaland** [comment]
@gowthamkpr yes I'm familiar with the custom op repo. My issue is not with being able to compile a GPU operation as I've managed to get that working already. I'd like to know how (or if it's even possible at all) to launch two CUDA kernels in 2 different streams. 

In CUDA this can be done with a simple malloc of a new stream and passing the string as the 4th argument to the kernel itself. TensorFlow seems to have its own management of memory and streams which I didn't want to interfere with by calling a CUDA malloc directly. The example given in the `time_two_kernels.cu.cc` shows just using a single stream `d.stream()` which is the case I have working currently. I notice there are other streams created for copying host to device, device to device and so on but I don't see the ability to have multiple streams for compute.

Is this just a fundamental limitation of TensorFlow? I can't find any examples of using multiple compute streams yet I can't think of a reason this shouldn't be possible given CUDA permits it

**Comment by chaaland** [comment]
@gowthamkpr bump on this issue

**Comment by yifeif** [comment]
@chaaland  afaik, currently TensorFlow runtime only creates a single compute stream per GPU device. Thought this might change in the future runtime, but I don't think anytime soon. cc: @iganichev

**Comment by iganichev** [comment]
@yifeif is right. TensorFlow design today is fairly tied to the "there is a single compute stream" assumption. This is usually not a problem because CUDA kernels tend to operate on large enough pieces of data and utilize the whole GPU. Your use case will benefit from parallelism only if your data is too small. In this case, if this op is not a major part of the computation (e.g. done in a tight loop), you might end up saving just a few microseconds.

If you still believe that running in parallel will be beneficial enough, there are a couple of things you can try doing:

- You can try putting both computations into the same kernel. A possible approach is to split your CUDA threads into two logical groups and make threads in group 1 do computation for dX and threads in group 2 do computation for dY.
- A much more involved and likely slower approach is to create another stream in your kernel (you probably want to cache it somewhere), launch your work on both streams, synchronize the new stream to the one used by TensorFlow to make sure that the TensorFlow's stream will not proceed until all work on your stream is done.

**Comment by chaaland** [comment]
@iganichev  Sounds like fusing the Op's backprop functor is the most straightforward approach. I was under the impression this would provide a perf benefit since as the thread blocks computing dX finish, threadblocks for dY could be scheduled. In my current implementation, _all_ of the thread blocks for dX must finish before any work on dY can be done. Will just have to test and see if it makes any difference. Thanks for your help!
