### ISSUE TITLE
undefined reference to `tflite::DefaultErrorReporter()'

### ISSUE THREAD

**Issue by ashishmagar600** [tensorflow/tensorflow#36661]
System information:  
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): v1.4.0-19-ga52c8d9 1.4.1
Python version: 2.7.12
Bazel version (if compiling from source): 0.8.1
GCC/Compiler version (if compiling from source): g++ 5.4.0
CUDA/cuDNN version: none
GPU model and memory: none
Exact command to reproduce:

g++ -I../tensorflow  -Llib -ltensorflow_cc -Llib -ltensorflowlite  test.cpp -o exec

Describe the problem
I used this tutorial to build tensorflow [link](https://tuatini.me/building-tensorflow-as-a-standalone-project/).  Also this [link](https://github.com/FloopCZ/tensorflow_cc)

Additionally, I built tensorflow-lite with:

bazel build //tensorflow/lite:libtensorflowlite.so

I am using this code for testing tflite:

  #include < cstdio >
  #include "tensorflow/lite/interpreter.h"
  #include "tensorflow/lite/kernels/register.h"
  #include "tensorflow/lite/model.h"
  #include "tensorflow/lite/tools/gen_op_registration.h"

  using namespace tflite;

  int main(int argc, char* argv[]) {
  if (argc != 2) {
  fprintf(stderr, "minimal \n");
  return 1;
  }
  const char* filename = argv[1];

  std::unique_ptr<tflite::FlatBufferModel> model =
  tflite::FlatBufferModel::BuildFromFile(filename);
  return 0;
  }

Here is the error:

/tmp/ccPKK7am.o: In function `main':
test.cpp:(.text+0x57): undefined reference to `tflite::DefaultErrorReporter()'
test.cpp:(.text+0x6d): undefined reference to `tflite::FlatBufferModel::BuildFromFile(char const*, tflite::ErrorReporter*)'
/tmp/ccPKK7am.o: In function `std::default_delete<tflite::FlatBufferModel>::operator()(tflite::FlatBufferModel*) const':
test.cpp:(.text._ZNKSt14default_deleteIN6tflite15FlatBufferModelEEclEPS1_[_ZNKSt14default_deleteIN6tflite15FlatBufferModelEEclEPS1_]+0x1e): undefined reference to `tflite::FlatBufferModel::~FlatBufferModel()'
collect2: error: ld returned 1 exit status

**Comment by terryheo** [comment]
Could you try to separate build and link stage?
For example)
$ g++ -I../tensorflow -ltensorflow_cc -c test.cpp
$ g++ -Llib -ltensorflow_cc -Llib -o exec test.o -ltensorflowlite 
Please make sure to provide your object file first than "-ltensorflowlite "

**Comment by ashishmagar600** [comment]
I am getting this :
./exec: error while loading shared libraries: libtensorflowlite.so: cannot open shared object file: No such file or directory

My lib/ 
libtensorflow_cc.so                 libtensorflow_framework.so.2               libtensorflowlite.so-2.params           lite
libtensorflow_cc.so.2               libtensorflow_framework.so.2.1.0           libtensorflowlite.so.runfiles
libtensorflow_cc.so.2.1.0           libtensorflow_framework.so.2.1.0-2.params  libtensorflowlite.so.runfiles_manifest
libtensorflow_cc.so.2.1.0-2.params  libtensorflowlite.so                       libtensorflow.so.2.1.0-2.params

**Comment by terryheo** [comment]
You need to update LD_LIBRARY_PATH to make linker can find libtensorflowlite.so

**Comment by ashishmagar600** [comment]
Thanks a lot...
So I have to:
1. Include my library after object file
2. Add path to LD_LIBRARY_PATH

I wasted so many days on this. 
Thank you once again

**Comment by rajveershringi** [comment]
System information:
Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Tiny modification to existing minimal.cc file
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
TensorFlow installed from (source or binary): source
TensorFlow version (use command below): not sure how to get this via c++, I cloned the latest tensorflow repository from here https://github.com/tensorflow/tensorflow
Python version: 3.7.7
Bazel version (if compiling from source): not installed
GCC/Compiler version (if compiling from source): g++  7.5.0
CUDA/cuDNN version: none
GPU model and memory: none

Exact command to reproduce:
`g++ -o minimal minimal.o -Itensorflow/lite/tools/make/gen/linux_x86_64/lib/libtensorflow-lite.a`

I have build tensorflowlite for x86 following the instructions here : [link](https://www.tensorflow.org/lite/guide/build_arm64)
But instead of running `./build_aarch64_lib.sh`, I ran `./build_lib.sh` for x86
I can see the generated `.a` files under : `tensorflow/lite/tools/make/gen/linux_x86_64/lib/` which are `benchmark-lib.a` and `libtensorflow-lite.a`

I can see an executable already made for minimal.cc under  `tensorflow/lite/tools/make/gen/linux_x86_64/bin`, which I am able to run with a `.tflite` model and get the expected outputs.

However I need to write a tweaked version of minimal.cc file for my model interpretation. How do I build this file ? Currently I see linker errors :
`minimal.cc:(.text+0x6e): undefined reference to tflite::DefaultErrorReporter()
minimal.cc:(.text+0x8a): undefined reference to tflite::FlatBufferModel::BuildFromFile(char const*, tflite::ErrorReporter*)
minimal.cc:(.text+0xe5): undefined reference to tflite::ops::builtin::BuiltinOpResolver::BuiltinOpResolver()
minimal.cc:(.text+0x110): undefined reference to tflite::impl::InterpreterBuilder::InterpreterBuilder(tflite::FlatBufferModel const&, tflite::OpResolver const&)`

I have compiled the file via :
`g++ -I. -Itensorflow/lite/tools/make/downloads/googletest/googletest/include/ -Itensorflow/lite/tools/make/downloads/absl/ -Itensorflow/lite/tools/make/downloads/flatbuffers/include/ -c tensorflow/lite/examples/minimal/minimal.cc` 

Things already done : 
`echo $LD_LIBRARY_PATH
/home/rajveer/Downloads/tensorflow/tensorflow/lite/tools/make/gen/linux_x86_64/lib/`

**Comment by rajveershringi** [comment]
Resolved above via compiling in the `tensorflow/` root directory :
`$ g++ tensorflow/lite/examples/minimal/minimal.cc -o minimal -std=c++11 -I. -Itensorflow/lite/tools/make/downloads/googletest/googletest/include/ -Itensorflow/lite/tools/make/downloads/absl/ -Itensorflow/lite/tools/make/downloads/flatbuffers/include/ -L/tf-lite/ -ltensorflow-lite -lrt -ldl -pthread`

Where linker path `/tf-lite` is the source directory containing `libtensorflow-lite.a` 

Hope it helps others.

However if I use the similar approach, I am not able to compile `label_image.cc` example under `tensorflow/lite/examples/label_image/label_image.cc` and  get undefined references for :
`label_image.cc:(.text+0x55): undefined reference to "tflite::evaluation::CreateGPUDelegate()"`

**Comment by pranv12** [comment]
I'm getting following error.

`/usr/bin/ld: cannot find -ltensorflow-lite`

**Comment by pranv12** [comment]
> I am getting this :
> ./exec: error while loading shared libraries: libtensorflowlite.so: cannot open shared object file: No such file or directory
> 
> My lib/
> libtensorflow_cc.so libtensorflow_framework.so.2 libtensorflowlite.so-2.params lite
> libtensorflow_cc.so.2 libtensorflow_framework.so.2.1.0 libtensorflowlite.so.runfiles
> libtensorflow_cc.so.2.1.0 libtensorflow_framework.so.2.1.0-2.params libtensorflowlite.so.runfiles_manifest
> libtensorflow_cc.so.2.1.0-2.params libtensorflowlite.so libtensorflow.so.2.1.0-2.params

@ashishmagar600 

How did you get `lib` folder and it's files?

I've wrote a code in C++  TFLite but unable to compile it. 
I'm also getting same error  `undefined reference to `tflite::DefaultErrorReporter()'` . I tried above things but It wasn't a success. 


It'd be very helpful if you provide complete steps.

**Comment by pranv12** [comment]
Hello,

@rajveershringi @ashishmagar600 @jdduke @terryheo 

I'm trying to run a custom code written in C++ using TFLite. 
I.m trying to compile and run the code. But it's giving some errors.

I also had undefined reference to `tflite::DefaultErrorReporter()' this error but managed to remove it.

Somehow I've managed to install TensorflowLite from the source. 
I've put `tensorflow/tensorflow` directory in `/usr/local/include`. Other dependencies (absl,flatbuffers, etc) are also inside same directory. Using this command `bazel build //tensorflow/lite:libtensorflowlite.so` whcichever files (*.so, *.params, *.runfiles.manifest) are generated and put in `/usr/local/lib/` directory. 

As said in this [comment](https://github.com/tensorflow/tensorflow/issues/36661#issuecomment-585034121) I tried to execute two commands
```
g++ -ltensorflow -c main.cc
g++ -Llib -ltensorflow -o ./main.o -ltensorflowlite
```

And error was:
```
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 1603 (>= sh_info of 1)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2710 (>= sh_info of 1)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2711 (>= sh_info of 1)
/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function _start':
(.text+0x24): undefined reference to main'
collect2: error: ld returned 1 exit status
```

second time I did something like this:
`g++ -ltensorflow -Llib main.cc -ltensorflowlite`
And now error is :
```
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 1603 (>= sh_info of 1)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2710 (>= sh_info of 1)
/usr/bin/ld: /usr/local/lib/libtensorflow.so: .dynsym local symbol at index 2711 (>= sh_info of 1)
/usr/bin/ld: /tmp/ccR2jeyn.o: in function `main':
main.cc:(.text+0x314): undefined reference to `infer_float(tflite::impl::Interpreter*)'
/usr/bin/ld: main.cc:(.text+0x32a): undefined reference to `infer_uint8(tflite::impl::Interpreter*)'
collect2: error: ld returned 1 exit status
```

Please help to correct me if I've done something wrong with the installation process or coding error.

infer_float and infer_uint8 are two functions declared in a header file. Then two separate .cc files contain the definition of each function. main.cc file has included header file and rest of code. 

Here's [link](https://github.com/pranv12/tflite_example_cc) to my repo.

**Comment by amahendrakar** [comment]
@pranv12,
Could you please create a new issue from [this link](https://github.com/tensorflow/tensorflow/issues/new/choose) and fill in the issue template, so that we can track it there. Thanks!

**Comment by pranv12** [comment]
@amahendrakar 
Thank you for your response. (And also sorry for late response.)

I found the problem. The problem wasn't with TFLite but my .cc file compiling.

I didn't compile all .cc files. 
I replaced command with `g++ -ltensorflow -Llib *.cc -ltensorflowlite` and it worked.
