### ISSUE TITLE
Tensorflow installation document Korean translated page outdated

### ISSUE THREAD

**Issue by jungmin-lim** [tensorflow/tensorflow#36678]
## URL(s) with the issue 

https://www.tensorflow.org/install?hl=ko

## Description of issue (what needs changing)

On installation document/windows build from source page, it tells that "TensorFlow를 컴파일하는 데 사용되는 빌드 도구인 Bazel 0.23.0을 설치합니다. C++를 빌드하도록 Bazel을 설정합니다." which means install Bazel 0.23.0 to compile Tensorflow. However, most recent version of Tensorflow which is r2.1, doesn't support Bazel 0.23.0. Instead, it uses 0.27.0~0.29.0. I checked English document and it tells me the version of Bazel that is needed. So, I think the Korean page should be renewed.

**Comment by MarkDaoust** [comment]
Hi @jungmin-lim, 

Thanks for reporting this. The docs translations in the 
https://github.com/tensorflow/docs-l10n repository.  

Can you copy this issue to that repository, and close this one? Thanks.

Also note that these translations are community owned. Since you seem to know how to correct this, I'm sure they'd love it if you can send a PR too.

Thanks.
