### ISSUE TITLE
How to build libhexagon_nn_skel.so ?

### ISSUE THREAD

**Issue by huanyingjun** [tensorflow/tensorflow#36681]
Hi
TFLite hexagon delegate is based on hexagon nnlib, I can get nnlib source code from https://source.codeaurora.org/quic/hexagon_nn/nnlib, and I can build ibhexagon_nn_skel.so according to "README.HOW_TO_BUILD" in nnlib, but my build libhexagon_nn_skel.so can not be used for tflite, report some error.
Does  tflite modify the nnlib code ? how to build libhexagon_nn_skel.so using the nnlib source code ?

**Comment by gowthamkpr** [comment]
@huanyingjun Github is only meant for bug/performance, build/install, feature request or docs related issues. 
Please post it in stack overflow as there is a wider community to respond. Thanks!

**Comment by aima9115** [comment]
Hello everyone, I post this here because I tried the same and I think it might be good to have another precedent.

I have implemented tflite natively with c (no java) on an android service. The target platform is a Snapdragon 625 (Qualcomm Technologies, Inc MSM8953). Using the Hexagon delegate as mentioned in [https://www.tensorflow.org/lite/performance/hexagon_delegate](https://www.tensorflow.org/lite/performance/hexagon_delegate) I got the following warning:

>WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
INFO: Hexagon Delegate is not supported.

I reach a point where I cannot build libhexagon_nn_skel.so for SD625 using the Hexagon SDK and the [nnlib](https://source.codeaurora.org/quic/hexagon_nn/nnlib) project. 

Do you have the libraries for this platform available? and if not supported at this moment, will it be supported in the future? or... what should I do to have the libraries I need?
