### ISSUE TITLE
Dataset padded_batch fails with InvalidArgumentError

### ISSUE THREAD

**Issue by stathva** [tensorflow/tensorflow#36686]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6

**Describe the current behavior**
```
rt = tf.ragged.constant([[1,2,3], [2], [1,2,3,4], [1,1]])
ds = tf.data.Dataset.from_tensor_slices(rt)
ds.padded_batch(2, padded_shapes=[None])
```
Fails with the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/vas/anaconda3/envs/text-ai/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 1481, in padded_batch
    drop_remainder)
  File "/home/vas/anaconda3/envs/text-ai/lib/python3.6/site-packages/tensorflow_core/python/data/ops/dataset_ops.py", line 3858, in __init__
    output_shapes=structure.get_flat_tensor_shapes(self._structure))
  File "/home/vas/anaconda3/envs/text-ai/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_dataset_ops.py", line 4091, in padded_batch_dataset_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/home/vas/anaconda3/envs/text-ai/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 6606, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: Mismatched type between padding value 0 and input dataset's component 0: int32 vs. variant [Op:PaddedBatchDatasetV2]
```
However:
```
ds.map(lambda x: x).padded_batch(2, padded_shapes=[None])
```
works as expected

**Comment by gadagashwini** [comment]
I could replicate the issue with Tf 2.1 and Latest tf-nightly.
Please find the gist [here](https://colab.sandbox.google.com/gist/gadagashwini/72fc06af220d44e2f7a1bd9208528b7a/untitled391.ipynb). Thanks!

**Comment by jsimsa** [comment]
@edloper could you please take a look? As far as I can tell, this is related to boxing ragged tensors in a variant so that they can be batched/unbatched. Thanks.

**Comment by edloper** [comment]
I'll look into what the problem is.  But in the meantime, note that if you don't actually want/need padding added, you can use [tf.data.experimental.dense_to_ragged_batch](https://www.tensorflow.org/api_docs/python/tf/data/experimental/dense_to_ragged_batch) to batch items into ragged tensors:

rt = tf.ragged.constant([[1,2,3], [2], [1,2,3,4], [1,1]])
ds = tf.data.Dataset.from_tensor_slices(rt)
ds2 = ds.apply(tf.data.experimental.dense_to_ragged_batch(2))
for element in ds2:
  print(element)

**Comment by edloper** [comment]
Ok, here's a bit more information:

* A DataSet's elements can be encoded as Tensors or RaggedTensors.  If they're encoded as RaggedTensors, then they have a ragged_rank indicating how many ragged dimensions they have.  You can check how elements are encoded by printing `my_dataset.element_spec`.

* When you use `ds = tf.data.Dataset.from_tensor_slices(rt)`, you construct a DataSet whose elements are encoded RaggedTensors with `ragged_rank = rt.ragged_rank-1`.  In your example, `rt` has one ragged dimension, so the elements in the dataset `ds` are RaggedTensors with `ragged_rank=0`.

* If a DataSet's elements are RaggedTensors, then you can batch them, even if they don't have the same size.  The result will be a RaggedTensor with one more ragged dimension.  So you can e.g. do:

  ```
  >>> ds = tf.data.Dataset.from_tensor_slices(rt)
  >>> # (elements of ds are stored as RaggedTensors w/ ragged_rank=0)
  >>> ds2 = ds.batch(2) # elements are RaggedTensors 
  >>> # (elements of ds2 are stored as RaggedTensors w/ ragged_rank=1, and 2 rows)
  ```

  I.e., you don't need to use `tf.data.experimental.dense_to_ragged_batch` in this context -- you can just use `ds.batch()`.

* When you use `ds2 = ds.map(lambda: lambda)`, it converts RaggedTensors w/ `ragged_rank=0` (i.e., with no ragged dimensions) into plain Tensors:

  ```
  >>> ds = tf.data.Dataset.from_tensor_slices(rt)
  >>> print(ds.element_spec)
  RaggedTensorSpec(TensorShape([Dimension(None)]), tf.int32, 0, tf.int64)

  >>> ds2 = ds.map(lambda x: x)
  >>> print(ds2.element_spec)
  TensorSpec(shape=(?,), dtype=tf.int32, name=None)
  ```

* `tf.data.experimental.dense_to_ragged_batch` is mostly useful if you have a dataset whose elements are encoded as Tensors, and you want to batch them into RaggedTensors.  If your elements are already encoded as RaggedTensors, you can just use batch().
 
* `padded_batch` does not currently support RaggedTensors (or SparseTensors).  It requires that the dataset's elements be Tensors.

* The reason that `ds.map(lambda x: x).padded_batch(2, padded_shapes=[None])` works is that the `map` converts the RaggedTensor elements into Tensor elements, and padded_batch is happy since its inputs have Tensor elements.

For now, we should probably add a check to `PaddedBatchDataset` that checks if any inputs are ragged, and if so, raises an exception.  (It looks like there's already an exception raised if any inputs are sparse).  In the future, we might want to update PaddedBatchDataset to support ragged tensors -- not sure from a brief look at the code how hard that would be.

But work-arounds are possible:

1. If your original dataset's elements are encoded using RaggedTensors w/ ragged_rank=0, then you can use `ds.map(lambda x: x).padded_batch(...)`.

2. If your original dataset's elements are encoded using RaggedTensors w/ any ragged_rank, then you can use: `ds.batch(...).map(lambda x: x.to_tensor())`

**Comment by grofte** [comment]
I just want to point out that Keras expects a `tf.data.Dataset.zip((x, y))` object where the inputs match the named tensors in x and the outputs match the names tensors in y. The only way I can get this to work with the majority of tf.Dataset methods (but not all) is by having both inputs and outputs in the same Dataset and then zip it twice before feeding to Keras. It feels like nonsense.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/bce5af439667785862d19ef3535dcade/35650.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
Since padded batch with ragged tensors is unsupported, you can convert the ragged tensor to uniform tensor and then perform padded batch like below.

```
import tensorflow as tf

rt = tf.ragged.constant([[1,2,3], [2], [1,2,3,4], [1,1]])
rt = rt.to_tensor(default_value=0)
ds = tf.data.Dataset.from_tensor_slices(rt)
A = ds.padded_batch(2, padded_shapes=[None])
for element in A.as_numpy_iterator():
  print(element)
```
Output:

```
[[1 2 3 0]
 [2 0 0 0]]
[[1 2 3 4]
 [1 1 0 0]]
```
