### ISSUE TITLE
TF 2.0: Spyder auto complete and go to definition not working. Please fix it!

### ISSUE THREAD

**Issue by colt18** [tensorflow/tensorflow#36798]
Due to the nature of the "lazy import" spyder IDE is not able to resolve the package tree and fails both "auto complete" and "go to function definition". 

Spyder guys told me TF should implemeny .pyi files to overcome this.

https://github.com/spyder-ide/spyder/issues/11553

**Comment by mihaimaruseac** [comment]
Which version of TF are you using? Can you please fill in the issue template?

.pyi files already exist on master as @annarev is working on exactly this.

**Comment by annarev** [comment]
Interesting. I added a __init__.pyi file under keras/ in https://github.com/tensorflow/tensorflow/commit/69f6601034942b018081715b31f6dd40111250af but looks like that doesn't help in Spyder. It still doesn't autocomplete for `from tensorflow.keras import metrics`

**Comment by annarev** [comment]
Retested with correct environment now. Now autocomplete works for `from tensorflow.keras import metrics`, but jump to definition doesn't work for `from tensorflow.keras.layers import Conv2D`

**Comment by colt18** [comment]
> 
> 
> Retested with correct environment now. Now autocomplete works for `from tensorflow.keras import metrics`, but jump to definition doesn't work for `from tensorflow.keras.layers import Conv2D`

Exactly, I also tested with Kite engine installed. I dunno if this is the beauty of the Kite engine but Autocomplete now works smooth though go to definition still fails.

**Comment by sachinprasadhs** [comment]
Could you please refer to the new import mechanism of keras here Related changes: https://github.com/keras-team/keras/blob/master/pip_build.py  and the [Related post](https://twitter.com/fchollet/status/1639776922019454976?s=20) which should solve the auto complete issue.
For more details and discussion on this issue, please refer the issue here https://github.com/tensorflow/tensorflow/issues/56231
