### ISSUE TITLE
sue: Build/Installation Issue

### ISSUE THREAD

**Issue by RAHUL9545416** [tensorflow/tensorflow#36884]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@RAHUL9545416 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Saduf2019** [comment]
@RAHUL9545416
please update on the above comment

**Comment by RAHUL9545416** [comment]
window10 64.8gb ram  grapic card 2bg pyton3.8

**Comment by Saduf2019** [comment]
@RAHUL9545416 
Could you please downgrade your python version and let us know of it helps, please refer to this [link](https://www.tensorflow.org/install/pip) as Tensorflow is only supported till python 3.7 as of now.
Also as request please share the steps before you faced an error and error logs for us to help you resolve the issue.

**Comment by Saduf2019** [comment]
@RAHUL9545416 
please confirm if the above comment helps

**Comment by Saduf2019** [comment]
@RAHUL9545416,
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
