### ISSUE TITLE
Java.lang.ArrayIndexOutOfBoundsException: length=66049; index=66049

### ISSUE THREAD

**Issue by Ehtasha** [tensorflow/tensorflow#36956]
I'm facing this error while integrating my custom Nails Segmentation Model with the app.

Other models are working find but whenever I use custom model app crashes and give above mentioned error.

Error in bellow while loop
`while (segmentedImage.hasRemaining()){
             outFrame[i++] = segmentedImage.int
        }`

**Android App Code to Reproduce this error:**
I have upload the stand alone code on [this ](https://drive.google.com/open?id=1WQ9LmAqJpxMwZIHtzMxRP2j6nq1Ga2lD)link which produce this error.

**System Information**
OS Platform and Distribution: Windows 10
Mobile device: Samsung Galaxy
TensorFlow version: Tensorflow Version installed on system is 1.15.0
Tensorflow Dependency using in android gradle file is: `implementation('org.tensorflow:tensorflow-lite:0.0.0-nightly') { changing = true }` 
TFlite Nails Detection Model file source: [Nail Detection Model](https://github.com/makeml-app/MakeML-Nails/tree/master/Segmentation%20Nails/Resources)

**Expected Behavior:**
Expected Behavior is showing in this [link](https://github.com/makeml-app/MakeML-Nails). 

**Current Behavior**
Currently when the camera view is open App crashes when the model start nails detection.
Exception throw in above while loop.
If I hide this above while loop then app is not crashing but not detecting nails and place colors on that.

What I need to change to get rid from this error ?

Thanks.

**Comment by ymodak** [comment]
Please provide following applicable information, Thanks!
**System information** 
- Have I written custom code (as opposed to using a stock
example script provided in TensorFlow): 
- OS Platform and Distribution (e.g.,
Linux Ubuntu 16.04): 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if
the issue happens on mobile device: 
- TensorFlow installed from (source or
binary): - TensorFlow version (use command below): 
- Python version: - Bazel
version (if compiling from source):
- GCC/Compiler version (if compiling from
source): 
- CUDA/cuDNN version: - GPU model and memory:

**Describe the current behavior**

**Describe the expected behavior**

**Comment by Ehtasha** [comment]
@ymodak  Glad to see your response Thanks.
My project deadline is already past.

I have update the information above.
Please give your precious time on urgent basis on this issue.
Thanks.
