### ISSUE TITLE
Custom object detection API for tensorflow 2.0 not working

### ISSUE THREAD

**Issue by sreeni5493** [tensorflow/tensorflow#37072]
The current Object detection API still has graphs and many code structures which are working only until version 1.15

Everywhere including colab it says support will only be for 2.0

Is there a timeline for the object detection API to be useful for tensorflow 2.0 for us to do custom object detection on our own datasets?

**Comment by gowthamkpr** [comment]
@sreeni5493 You can follow the following [tutorial1](https://tensorflow-object-detection-api-tutorial.readthedocs.io/en/latest/training.html) and [tutorial2](https://towardsdatascience.com/how-to-train-a-tensorflow-2-object-detection-model-25d4da64b817) to train your custom model using object detection API. If you have more questions, please post it in tensorflow/models repo as this issue is more apt there. Thanks!
