### ISSUE TITLE
function.Defun can't be applied to tf.Variable

### ISSUE THREAD

**Issue by zeis** [tensorflow/tensorflow#3710]
I need to specify a custom gradient for my custom_op() function. I've written the following example.

```
import numpy as np
import tensorflow as tf
from tensorflow.python.framework import function

def custom_op_grad(op, grad):
    return grad

@function.Defun(x=tf.float32, python_grad_func=custom_op_grad)
def custom_op(x):
    exp = tf.exp(x)
    constant = tf.constant(1., dtype=tf.float32)
    add1 = tf.add(constant, exp)
    log = tf.log(add1)
    return log

x = tf.Variable(np.array(np.arange(6)).reshape(3, 2), dtype=tf.float32)

sess = tf.Session()
sess.run(tf.initialize_all_variables())

x = tf.identity(x)

grad = tf.gradients(custom_op(x), [x])[0]

res = sess.run(grad)

print(res)

sess.close()
```

If I run the above example as it is I get the following result:

```
[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]
```

If I comment out the @function.Defun(...) decorator (with I use to specify a custom gradient function) I get a different result:

```
[[ 0.5         0.7310586 ]
 [ 0.88079709  0.95257413]
 [ 0.98201376  0.99330717]]
``` 

That is strange because custom_op_grad(op, grad) just returns grad, which I guess should be the same as the gradient calculated in the second case.

Moreover, if I keep the decorator I also need to do this: x = tf.identity(x). If I comment out this line, I get the following error and I don't understand why:

```
Traceback (most recent call last):
  File "custom_op3.py", line 42, in <module>
    grad = tf.gradients(custom_op(x), [x])[0]
  File "/Users/zeis/tfm/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 528, in __call__
    return call_function(self._definition, *args, **kwargs)
  File "/Users/zeis/tfm/lib/python3.5/site-packages/tensorflow/python/framework/function.py", line 267, in call_function
    compute_shapes=False)
  File "/Users/zeis/tfm/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2285, in create_op
    raise TypeError("Input #%d is not a tensor: %s" % (idx, a))
TypeError: Input #0 is not a tensor: <tensorflow.python.ops.variables.Variable object at 0x10eb7d710>
```

I'm using the GitHub version of TensofFlow.

**Comment by girving** [comment]
If you comment out the `Defun`, it's computing the gradient of softplus correctly.  Your gradient function is wrong, since softplus isn't the identity function and doesn't have derivative 1, but computes what I'd expect given its implementation.

The fact that you can't apply a Defun to a variable is a bug.  @andydavis1: Could you take a look?

**Comment by andydavis1** [comment]
Sorry that you are having this issue. We are working on a fix, after which you will be able to pass a Variable as a function argument (without using the Identify).

**Comment by zffchen78** [comment]
Your custom_op(x) is effectively computing element-wise y = log(1+e^x) for x in the inputs. By definition, tf.gradients(y, x) computes, since grad_ys=None by default, dy_i/dx_i = e^x / (1 + e^x)  = sigmoid(x). Since your test is giving x = [0, 1, 2, 3, 4, 5]. So, 
[[ 0.5         0.7310586 ]
 [ 0.88079709  0.95257413]
 [ 0.98201376  0.99330717]]
is correct.

When you specify custom_op_grad(x, grad) = grad, effectively, you are telling the backprop algorithm to pass through the error. Since grad_ys=None, effectively, these are 1.0.

**Comment by albertz** [comment]
If I run that sample code, I get

    ValueError: Unknown keyword arguments: ['x']

When I remove `x=` in the `Defun` call, this exception is gone.

But then I get:

    tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'custom_op_d6da5a2c'

Is there something broken again?
