### ISSUE TITLE
Can you guys work on making Tensorflow easier to install?

### ISSUE THREAD

**Issue by Tylersuard** [tensorflow/tensorflow#37189]
Hi.  I spent 2 weeks trying to get Tensorflow up and running on my GPU.  It worked... for that one particular repo.  Now I'm trying another project, and apparently that particular version of Tensorflow gives me the error "Tensorflow has no attribute 'dimension'".  

So I tried to open a new environment, re-install tensorflow-gpu, and I'm getting a "core-dump" error.

With other packages, I can just type "pip install" and it works.  With tensorflow, every single time I have to use or install it I have to spend multiple hours debugging it.  Please, instead of adding new features, work on making Tensorflow able to be installed and used, without errors, by someone without a doctorate in computer science.

**Comment by av8ramit** [comment]
Hi @Tylersuard can you please fill out the form that goes along with the issues so that we may better assist you? What OS and version of TF are you trying to install?

**Comment by Tylersuard** [comment]
https://www.reddit.com/r/tensorflow/comments/czo5x7/why_is_tensorflow_so_hard_to_install/
https://www.quora.com/Why-is-TensorFlow-so-hard-to-install

It's not the OS or the version of my particular machine.  It's that Tensorflow is incompatible with EVERYTHING, unless I do a huge amount of error solving to get it to work.  The first link above is from a person who says that in their 6 years of experience he has never run into a library that's as difficult to install as Tensorflow.  And I have to agree.

It's particularly frustrating to try to install tensorflow-GPU: when last I tried, it was not compatible with the latest NVIDIA drivers, so I had to uninstall them as well as CUDNN in order to get tensorflow-gpu to work on my machine.

Though I've often been told not to use Conda to install tensorflow, recently I'm finding that is the only way to actually get Tensorflow to work.

Every other package I've ever used that is not Tensorflow, I just do pip install and it works and it's fine.  With Tensorflow, I have to solve around 10+ errors after every install, and often in between uses.

Tensorflow was made by Google.  Google is well-known for its simple software and great interfaces.  Tensorflow has nothing to do with either of those qualities.

I am from now on going to try to use Pytorch, not because of its quality, but because I can actually install it.

**Comment by SivamPillai** [comment]
In my experience, the ease of installation of TensorFlow has gotten better with every new release. The current versions are just as easy as pip install TensorFlow (Which defaults to GPU enabled option). I believe the challenge you face is the interdependency between the platform, graphics drivers, CUDA, CuDNN, and Tensorflow. In that case, I also agree the overall pipeline of TF installation has never been smooth for me. 

Below is my experience on Ubuntu OS (16.04, 18.04) with Cuda 8.x, 9.x, 10.x, CuDNN 5.x onwards and TF 0.9 till 2.0. The main problems:
1) Corruption of Graphics drivers causing UI to not work on restart.
2) Causing login loops
3) GPU used for UI and ML
4) Version mismatches between cuda, drivers, and TF
5) Getting CUDA and CuDNN to communicate with each other
6) Difference between installing using DEB packages vs Nvidia run files.
 
and a few more. 

I think, for this to be smoother Nvidia and TF team have to work together. As I said before once the right version of drivers and CUDA are in place, I have never faced any issue with installing any version of TensorFlow including nightly packages, or local package building.

**Comment by amahendrakar** [comment]
@Tylersuard,
Could you please share the exact sequence of commands you executed before running into the problem. If possible share the error logs too, so that we can look into this issue and fix it.

You can check out [this](https://www.tensorflow.org/install/pip) guide to install TensorFlow through pip packages. Or, if you want to build TensorFlow from source you can follow [the official guide](https://www.tensorflow.org/install/source) depending on the OS you are using. Thanks!

**Comment by Tylersuard** [comment]
@amahendrakar I'm sorry, I can't give you any exact sequence of commands.  This post is just me venting my frustration at using Tensorflow for over a year, and it being by far the most difficult package to install each and every time.  

Tensorflow doesn't work with the most recent version of Python.  Tensorflow doesn't work with the most recent version of CUDNN.  Tensorflow doesn't work with the most recent version of CUDA.

I've resorted to using Colab for everything because I don't have to wade through hours of error-solving just to open a program.

This isn't asking you to solve a specific error.  This is me asking your team to solve ALL the errors, and please, please, for the love of god, PLEASE make Tensorflow easy to install so that I and others don't have to keep tearing our hair out.

**Comment by mihaimaruseac** [comment]
Unfortunately this is a huge project with too many dependencies, so making sure everything works as soon as new dependencies versions are released is a Sisyphean task with little recognition. It is what it is.

Fortunately, this is a community project, anyone from the open source can provide PRs to upgrade build tools/code so that TF would work with the newer versions.

There is the alternative of splitting TF into many smaller packages each one being much easier to install. But this has several people upset because then they can no longer just do a `pip install tensorflow` and `import tensorflow as tf` and have everything working.

**Comment by SivamPillai** [comment]
While the OP mentioned having TF support the latest versions of CuDNN, CUDA, etc; I do not think that alone is the problem. Assuming you have specific versions of these dependencies that are supported, **is there a foolproof way of installing packages that will work reliably?** Yes, I have gone through the steps mentioned in the TF installation page and yes the latest version **mostly** works. However, I still face difficulties, where the exact same method with the same setup will not work in two different ubuntu machines. The most troublesome part is when a certain step leads to issues like login loop or Cuda not being detected. During my attempts, I have used the Nvidia website, various blog posts, TF installation guides, askubuntu answers, FastAI advice (and some combination therein) to make things work. It would be much easier if we can have a more robust installation procedure so we can worry about building DL algorithms with TF rather than setting up TF.

Don't get me wrong! TF is an amazing package without which things would have been far gloomier. It is just that "why" feeling when you end up spending hours or days setting up TF rather than training your models already!

**Comment by mihaimaruseac** [comment]
We try to ensure that the official builds are working in as many cases as possible. If you encounter a problem with official install guides, please open a PR and we will fix issues.

Unfortunately, the build system has grown fast and in a haphazard way. We need to clean it up and make it better but this needs head count and time. Will happen eventually.

**Comment by Tylersuard** [comment]
@SivamPillai Thank you for backing me up on this.  I feel exactly the same way.

@mihaimaruseac At this point I would settle for a Windows-type installation wizard, anything to just get the software to work.  It could even include matching Nvidia drivers and Python versions with Tensorflow or something like that.  It's just frustrating to me that everything else by Google is amazing and easy to use, except Tensorflow, which is the worst program I have ever had to work with.  I wish more repos used other tech so I didn't have to keep downloading and installing it.  Where there are options to use Pytorch or Theano, I use them.

**Comment by SivamPillai** [comment]
@mihaimaruseac I am not setting up TF at the moment in any machine. But will share specific issues when I come across those. @Tylersuard sure, it was just resonating so chipped in. I don't think making things so rigid like a windows software package will help either. As you know most of us want to make use of the latest improvements or algorithms implemented in TF. Windows like rigid packaging will most likely lack the ability to update on-the-go. 

I think  the way to go is modularizing and minimizing dependencies. I am sure TF folks are working on this but would love to see if a separate project on the usability is setup as mentioned by @Tylersuard so as to have a roadmap. We can chip in where possible for this project.

**Comment by ymodak** [comment]
Closing this issue for now. Thanks!

**Comment by turu-tensor** [comment]
> https://www.reddit.com/r/tensorflow/comments/czo5x7/why_is_tensorflow_so_hard_to_install/
> https://www.quora.com/Why-is-TensorFlow-so-hard-to-install
> 
> It's not the OS or the version of my particular machine. It's that Tensorflow is incompatible with EVERYTHING, unless I do a huge amount of error solving to get it to work. The first link above is from a person who says that in their 6 years of experience he has never run into a library that's as difficult to install as Tensorflow. And I have to agree.
> 
> It's particularly frustrating to try to install tensorflow-GPU: when last I tried, it was not compatible with the latest NVIDIA drivers, so I had to uninstall them as well as CUDNN in order to get tensorflow-gpu to work on my machine.
> 
> Though I've often been told not to use Conda to install tensorflow, recently I'm finding that is the only way to actually get Tensorflow to work.
> 
> Every other package I've ever used that is not Tensorflow, I just do pip install and it works and it's fine. With Tensorflow, I have to solve around 10+ errors after every install, and often in between uses.
> 
> Tensorflow was made by Google. Google is well-known for its simple software and great interfaces. Tensorflow has nothing to do with either of those qualities.
> 
>



> Hi. I spent 2 weeks trying to get Tensorflow up and running on my GPU. It worked... for that one particular repo. Now I'm trying another project, and apparently that particular version of Tensorflow gives me the error "Tensorflow has no attribute 'dimension'".
> 
> So I tried to open a new environment, re-install tensorflow-gpu, and I'm getting a "core-dump" error.
> 
> With other packages, I can just type "pip install" and it works. With tensorflow, every single time I have to use or install it I have to spend multiple hours debugging it. Please, instead of adding new features, work on making Tensorflow able to be installed and used, without errors, by someone without a doctorate in computer science.

Just use pytorch, i never have issues with that.
