### ISSUE TITLE
Warning/Error not present when not using the result of write in a TensorArray

### ISSUE THREAD

**Issue by zaccharieramzi** [tensorflow/tensorflow#37245]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1.0
- Python version: 3.6.8

**Describe the current behavior**
When not using the result of a `write` method from a `TensorArray`, I am not getting any warning or error.

**Describe the expected behavior**
According to [the docs of `write`](https://www.tensorflow.org/api_docs/python/tf/TensorArray#write), I should receive a warning or error.
I think it's also important to receive one given I spent quite some time realizing it was not inplace.

**Standalone code to reproduce the issue** 
```python
import tensorflow as tf
@tf.function
def use_tensor_array(x):
    y = tf.TensorArray(x.dtype, tf.shape(x)[0])
    for i in tf.range(tf.shape(x)[0]):
        y.write(i, x[i])
    y = y.stack()
    return y

use_tensor_array(tf.constant([1, 3, 4, 6]))
```

**Comment by Saduf2019** [comment]
I have replicated the mentioned issue and it persist,please find the [gist](https://colab.sandbox.google.com/gist/Saduf2019/a47bad1134ac9ec7bee368439fcdbdea/untitled71.ipynb) here

**Comment by ravikyram** [comment]
I have tried in colab with TF versions 2.2,2.3-rc1,nightly versions(`2.4.0-dev20200712`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/4a898fa9440cb0d6faeaae72748b9761/untitled115.ipynb).Thanks!

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/ff2301e043c5a133e9d64aa9443f152e/35650.ipynb). Thanks!

**Comment by Saduf2019** [comment]
This issue is still reproducible on tf 2.7-[nightly](https://colab.research.google.com/gist/Saduf2019/726eb43542712e0a4320a2a3cb9ae557/untitled638.ipynb) version.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
