### ISSUE TITLE
tf.estimator.SummarySaverHook should support native V2 symbols.

### ISSUE THREAD

**Issue by ujjwal-ai** [tensorflow/tensorflow#37272]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
At present when specifying `tf.estimator.SummarySaverHook` in `tf.estimator.EstimatorSpec` when writing a custom `model_fn`, one is bound to use symbols from `tf.compat.v1`. 

This is because, `tf.estimator.SummarySaverHook` needs  `summary_op` as an argument which should be a  tensor or list of tensors.

On the other hand the native V2 api in the form of `tf.summary...` symbols  return a boolean value. 

Therefore it is not possible to use `tf.summary` functions when using `tf.estimator.SummarySaverHook`.

**Will this change the current api? How?**

It will change the API as it will require either a basic change in `tf.summary` or `tf.estimator`

**Who will benefit with this feature?**
It will help people in migrating their codes to native V2 symbols.

**Comment by ujjwal-ai** [comment]
#36516 is also a related issue I think.

**Comment by MihailMihaylov97** [comment]
I have also stumbled upon this issue. Is somebody working on a resolution?

**Comment by rmothukuru** [comment]
@ujjwal-ai ,
Sorry for the delayed response. In the **`Tensorflow Version 2.x`**, since we use [TF Keras](https://www.tensorflow.org/api_docs/python/tf/keras/) and [tf.data](https://www.tensorflow.org/guide/data) predominantly and don't use [Estimators](https://www.tensorflow.org/guide/estimator) much, can you please let us know if this Feature is still relevant? 

Thanks!
