### ISSUE TITLE
General discussion of tf.image

### ISSUE THREAD

**Issue by czabo** [tensorflow/tensorflow#37274]
Hi,

I was thinking about applying for the GSoC for the topic of expandin tf.image (Adding and standardizing image processing operations in tf.image). It is said that it involves adding operations present in other image processing libraries. I am thinking operations that for example OpenCV has. 

I was looking for example at rotating an image, which is right now just limited to rotate by multiples of 90 degrees (tf.image.rot90). More generally one would like to for example get a rotation matrix and do an affine transform there to get any rotation angle. It seems though that tf.keras.precprocessing.image also has some image processing operations like tf.keras.precprocessing.image.apply_affine_transform that would do that. It seems to me redundant though for having tf.keras.preprocessing.image and tf.image in the end.

Any thoughts on that? 

Anyway if I need a mentor for that from the TF community for the GSoC project, who should I contact you think?

**Comment by swghosh** [comment]
Hello @czabo!

I am also looking forward to applying at GSoC 2020. Replacing tf.keras.preprocessing.image.ImageDataGenerator for data augmentation op(s) using vanilla tf.image instead of SciPy based affine transformations have been extensively discussed. (https://docs.google.com/document/d/1yz2kwWsZ3wx-cObodb84a-LgHuxbTbxo53VI5yFqms8/edit) Also, there were discussions regarding complete rewrite of tf.keras.preprocessing submodule using tf.data.Dataset pipelines exclusively. The meeting notes indeed mention that some of these changes are to brought up in TF2.2 (this March). Any leads?

Any information from the community in this regard would be greatly appreciated as that'd help in supporting information for GSoC proposals.

Thank you.

**Comment by czabo** [comment]
Thank you for your update @swghosh :) Yes it would be indeed helpful if there would be any further information regarding all this.

**Comment by ymodak** [comment]
Closing this issue since we have an active thread tagged above covering this topic. 
Feel free to reopen if necessary. Thanks!

**Comment by ghosalsattam** [comment]
@swghosh I applied for the same problem statement but unfortunately could not get through it. Can you please tell me from where you got the above link(is there any site or place where the outcomes of such meetings are published). I am asking it just for information so that it can be helpful for me if I apply to tensorflow in future.

**Comment by swghosh** [comment]
Hi @ghosalsattam, probably you gone go through the following to get information about community meetings and discussion about API changes.

A good point to start would be to refer:
- https://www.tensorflow.org/community/contribute
- https://github.com/tensorflow/community/ (new RFCs for TensorFlow ecosystem goes here)
- https://github.com/keras-team/governance (new RFCs that subclass Keras APIs or changes to actual keras itself)
