### ISSUE TITLE
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed. (Running Adel Wheat))

### ISSUE THREAD

**Issue by sujithgunturu** [tensorflow/tensorflow#37333]
`from alinea.adel.astk_interface import AdelWheat
from alinea.astk.Weather import sample_weather

seq, weather = sample_weather()
wdata = weather.get_weather(seq)

adel = AdelWheat(nsect=2)

g = adel.setup_canopy(100)
adel.grow(g, wdata)`

Getting the error:

(adel) C:\Users\Personal\Desktop\OpenAlea research\adel\example>python test_AdelWheat.py
Traceback (most recent call last):
  File "test_AdelWheat.py", line 1, in <module>
    from alinea.adel.astk_interface import AdelWheat
  File "C:\Users\Personal\Desktop\OpenAlea research\adel\src\alinea\adel\astk_interface.py", line 6, in <module>
    from alinea.adel.AdelR import setAdel, RunAdel, genGeoAxe, checkAxeDyn, getAxeT, \
  File "C:\Users\Personal\Desktop\OpenAlea research\adel\src\alinea\adel\AdelR.py", line 23, in <module>
    import rpy2.robjects as robj
  File "C:\Users\Personal\.conda\envs\adel\lib\site-packages\rpy2\robjects\__init__.py", line 16, in <module>
    import rpy2.rinterface as rinterface
  File "C:\Users\Personal\.conda\envs\adel\lib\site-packages\rpy2\rinterface\__init__.py", line 92, in <module>
    from rpy2.rinterface._rinterface import (baseenv,
ImportError: DLL load failed: A dynamic link library (DLL) initialization routine failed.

**Comment by sujithgunturu** [comment]
Installing this package  https://github.com/openalea-incubator/adel
and trying to run the above code

**Comment by ravikyram** [comment]
@sujithgunturu 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by sujithgunturu** [comment]
I am not working with tensor flow. The issue is with adel wheat which is an other paclage.

**Comment by mihaimaruseac** [comment]
Then this should not be posted in tensorflow repository. Locking conversation as offtopic
