### ISSUE TITLE
Precision at top_k does not compute the precision *on average* as stated in the API

### ISSUE THREAD

**Issue by LeechMuse** [tensorflow/tensorflow#37416]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:

https://www.tensorflow.org/api_docs/python/tf/keras/metrics/Precision

## Description of issue (what needs changing):
This method does not compute the precision *on average* when top_k is set. This could lead to bad evaluations, especially when the sample_weight is set and used as counts.

### Clear description

To see the issue, it's enough to run 
```
m = tf.keras.metrics.Precision(top_k=2)
m.update_state([0, 0, 1, 1], [1, 1, 1., 1.])

print('Final result: ', m.result().numpy()) # Returns 0 but should return 0.5
```
It always computes the precision according to the given order and returns 0. However it should return 0.5 if it's on average.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF 2.1 and TF-nightly. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/835c0ddf7b10b0c134967080939efffe/37416.ipynb). Thanks!

**Comment by ravikyram** [comment]
@LeechMuse 
In the code provided by you `y_true` = [0, 0, 1, 1], `y_pred` = [1, 1, 1., 1.] , top_k = top-k classes to be considered to calculate precision. 

If top_k = none it consider all the classes.

Precision is calculated by TP/TP+FP. So in the case top_k =1 it considers the first value only to calculate precision (ie y_true = [0]  and y_pred = [1]) so precision is zero. 

Similarly top_k=2 considers first 2 values y_true` = [0, 0] and y_pred` = [1, 1] so precision is zero. 
If top_k=3 then y_true` = [0, 0,1] and y_pred` = [1,1,1.] so precision is 0.33.

In this example top_k =4 or None is same because it uses all the values. In that case `y_true` = [0, 0, 1, 1], `y_pred` = [1, 1, 1., 1.]  so precision will be 0.5. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/af71a7be1c9cc0e945f79536d540fbb3/untitled710.ipynb). Thanks!

**Comment by LeechMuse** [comment]
Sure, this is true, but in that case it's not on average, and instead you should say precision at top_k (ties are broken by the order in which the values are provided).

If it was on average, it should be expected to break ties according to expectation. So in the case of top_k=1, it should still be 0.5, because under random assignment of order (given that all y_hat are equal), 0.5 of the permutations will have 1 in the first element in the array.

**Comment by LeechMuse** [comment]
Or, if the average is referring to average across the batches, it should still say how you handle ties in y_hat. While this might seem trivial, I have failed in the past reproducing results of papers because of that.

**Comment by ashutosh1919** [comment]
> @LeechMuse
> In the code provided by you `y_true` = [0, 0, 1, 1], `y_pred` = [1, 1, 1., 1.] , top_k = top-k classes to be considered to calculate precision.
> 
> If top_k = none it consider all the classes.
> 
> Precision is calculated by TP/TP+FP. So in the case top_k =1 it considers the first value only to calculate precision (ie y_true = [0] and y_pred = [1]) so precision is zero.
> 
> Similarly top_k=2 considers first 2 values y_true` = [0, 0] and y_pred` = [1, 1] so precision is zero.
> If top_k=3 then y_true` = [0, 0,1] and y_pred` = [1,1,1.] so precision is 0.33.
> 
> In this example top_k =4 or None is same because it uses all the values. In that case `y_true` = [0, 0, 1, 1], `y_pred` = [1, 1, 1., 1.] so precision will be 0.5. Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/af71a7be1c9cc0e945f79536d540fbb3/untitled710.ipynb). Thanks!

@ravikyram , I think this example should also be added in the doc, so here it is. PR #37528 adds this example to doc.
