### ISSUE TITLE
Roadmap link is broken.

### ISSUE THREAD

**Issue by ryujaehun** [tensorflow/tensorflow#37509]
## URL(s) with the issue:
README.md  Resources's roadmap link is broken.
https://www.tensorflow.org/community/roadmap

## Description of issue (what needs changing):
It is occurred Page not found errer.

**Comment by ManishAradwad** [comment]
I'd like to fix this, but I can't find the proper link. Can anyone plz help??

**Comment by ashutosh1919** [comment]
@ryujaehun , Please refer to [this commit](https://github.com/tensorflow/docs/commit/297a36784c1f665a21e076301d7fd3603797be33) in the doc repo. It specifies that they have removed the roadmap page on Jan-10, 2020. The reason may be because they may be updating the readme and will upload new readme as soon as they complete gathering the newly added features.

**Comment by ymodak** [comment]
Closing this issue since its resolved. Thanks!
