### ISSUE TITLE
Incorrect number of Total Parameters when Loading a Saved Model with Trainable = False

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#37531]
[Resume_Classification_Model.zip](https://github.com/tensorflow/tensorflow/files/4324479/Resume_Classification_Model.zip)
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): N/A, as it can be reproduced in Google Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:  N/A
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.1
- Python version: Colab
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):  N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

This issue is similar to [29535](https://github.com/tensorflow/tensorflow/issues/29535) but now occurring in `Tensorflow Version 2.x`.

**Describe the current behavior**: Value of Total Parameters, when we Load the Saved Model with `Trainable = False` is Double compared to the Actual Total Parameters.

**Describe the expected behavior**: Value of Total Parameters should be same even we use `Trainable = True` or `Trainable = False`

**Standalone code to reproduce the issue** :  Please find the [attached Gist](https://colab.sandbox.google.com/gist/rmothukuru/a454904863d7a0e42b4497d6366a70e0/load_with_freeze_error.ipynb).

Please find the Model, "Resume_Classification_Model.zip", attached.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue. Please find the Gist [here](https://colab.sandbox.google.com/gist/amahendrakar/73a3b70d4f50f8a5e460e212be8c6793/tf2-1.ipynb). Thanks!

**Comment by jaketae** [comment]
I would just like to add to the discussion the fact that calling `compile()` after setting `trainable = False` resolves the issue, *i.e.* the correct number of parameters are displayed.

**Comment by ashutosh1919** [comment]
@rakeshmothukuru1 , @amahendrakar and @jaketae , I think I have figured out the issue. 
`trainable_count` is calculated for summary by [this code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/utils/layer_utils.py#L261).

Note that the code on the above link
```python
if hasattr(model, '_collected_trainable_weights'):
    trainable_count = count_params(model._collected_trainable_weights)
else:
    trainable_count = count_params(model.trainable_weights)
```
first checks if there is any attribute as `_collected_trainable_weights`, if it is then it will count params based on `_collected_trainable_weights`, otherwise it will count based on `trainable_weights`.

Now, since you are loading the model which was trained already so by default the layers of the model were trainable. I checked it by calling layers API and checking the weights as follows:
You can check layers with
```python
>>> New_Model._layers
[<tensorflow.python.keras.engine.input_layer.InputLayer at 0x7f694dcadcc0>,
 <tensorflow.python.keras.saving.saved_model.load.Embedding at 0x7f694dd3e0f0>,
 <tensorflow.python.keras.saving.saved_model.load.Bidirectional at 0x7f694dd3e780>,
 <tensorflow.python.keras.saving.saved_model.load.Bidirectional at 0x7f694dd3ecc0>,
 <tensorflow.python.keras.saving.saved_model.load.Dense at 0x7f694dd73128>,
 <tensorflow.python.keras.saving.saved_model.load.Dense at 0x7f694dd73550>]
```
You can also check the trainable and non-trainable weights for each model with
```python
>>> New_Model._layers[5]._trainable_weights
[<tf.Variable 'dense_1/kernel:0' shape=(64, 7) dtype=float32, numpy=
 array([[-5.22130467e-02, -1.93556882e-02,  6.19841479e-02,
         -2.20982015e-01, -2.58759469e-01,  1.56931624e-01,
         -1.02677837e-01],
        [-2.78469831e-01, -3.55885886e-02, -3.39667916e-01,
         -2.11565107e-01,  2.90678382e-01,  3.44290137e-02,
         -1.20272964e-01],
         ...
        [-1.06683329e-01, -2.90703289e-02,  5.69653399e-02,
         -1.45962730e-01,  1.51988491e-02, -4.15223390e-01,
         -3.09695005e-01]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(7,) dtype=float32, numpy=
 array([-0.04054414,  0.05413923,  0.0347003 , -0.0140862 , -0.02740904,
         0.01077772, -0.01707667], dtype=float32)>]
```

So, you can see here that weights of the layers are trainable by default since we have loaded the trained model. Now, the fact to know here is `_collected_trainable_weights` in `tf.keras.Model` is assigned at the time of `compile`. 

So, if you compile the model before setting `trainable=False`, then it will assign `_collected_trainable_weights` non-empty list (Because layers trainable weights are non-empty). So, in this case, `trainable_weights` will be empty but `_collected_trainable_weights` will not be empty. Hence, the first [this code](https://github.com/tensorflow/tensorflow/blob/c9c38bcd20e206674e72d187c1f95046218342d1/tensorflow/python/keras/utils/layer_utils.py#L261) to count trainable parameter will consider `_collected_trainable_weights` to count trainable param.
```python
New_Model = tf.keras.models.load_model("Resume_Classification_Model/Resume_Classification_Model/1")
New_Model.compile()
New_Model.trainable= False
```
It will generate o/p as 
```
Total params: 863,758
Trainable params: 431,879
Non-trainable params: 431,879
```

In reverse case,
f you compile the model after setting `trainable=False`, then it will assign `_collected_trainable_weights` empty list (Because compile will get `kwargs` as `trainable=False`). So, in this case, `trainable_weights` will be empty but `_collected_trainable_weights` will also be empty. Hence, the first [this code](https://github.com/tensorflow/tensorflow/blob/c9c38bcd20e206674e72d187c1f95046218342d1/tensorflow/python/keras/utils/layer_utils.py#L261) to count trainable parameter will consider `_collected_trainable_weights` (which is empty) to count trainable param.
```python
New_Model = tf.keras.models.load_model("Resume_Classification_Model/Resume_Classification_Model/1")
New_Model.trainable= False
New_Model.compile()
```
It will generate o/p as 
```
Total params: 431,879
Trainable params: 0
Non-trainable params: 431,879
```

**Comment by ashutosh1919** [comment]
So, I think no need to change the code. We need to use `trainable` considering above thing in mind.

**Comment by k-w-w** [comment]
Can you clarify what the workflow is?

What do you mean by loading the SavedModel with trainable=False?

**Comment by rakeshmothukuru1** [comment]
@k-w-w,
If the question is to me, Please find this [Github Gist](https://colab.sandbox.google.com/gist/rmothukuru/a454904863d7a0e42b4497d6366a70e0/load_with_freeze_error.ipynb) for the Workflow. The Model is attached.

[Resume_Classification_Model.zip](https://github.com/tensorflow/tensorflow/files/4342619/Resume_Classification_Model.zip)

**Comment by k-w-w** [comment]
I think this is working as intended. `compile` locks down the trainable weights, I believe because the train ops are generated during compile. Therefore, you should recompile to get the correct number of parameters. (also, the summary notes that you should call `compile` after changing the `trainable` value)
