### ISSUE TITLE
large model parallelism on gpu causing oom

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#37563]
We are using v100 with gpu memory of 32 gb to train wide and deep model of size 12gb, facing the problem of gpu out of memory. 

So we are thinking of the model parallelism to distribute the large model on different gpu, however, all of the current available strategies for model parallelism could not meet our demand.

1. MirroredStrategy 
2. MultiWorkerMirroredStrategy
3. CentralStorageStrategy
4. ParameterServerStrategy
5. TPUStrategy

For MirroredStrategy  and MultiWorkerMirroredStrategy, each variable in the model is mirrored across all the replicas, which means that gpu memory of each card is still in shortage. CentralStorageStrategy and ParameterServerStrategy have great communication cost among cpus and gpus. So my question is for our large ctr model is there any solutions to realize model parallelism

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Please provide colab link or simple standalone code with supporting files to reproduce the issue in our environment. It helps us in localizing the issue faster.Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).Thanks!

**Comment by sjtusmartboy** [comment]
ubuntu 18.04 and tf 1.14 @ravikyram

**Comment by sjtusmartboy** [comment]
It's noticed that the wide-and-deep model involves the usage of the DNNLinearCombinedClassifier, so the detail of the model is invisible for the user to specify which variable should be placed on the specified gpu,  i.e. with tf.device('/gpu:0'). @ymodak

**Comment by ymodak** [comment]
May be you can consider [limiting gpu memory growth ](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) in this case?
Also see https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/ConfigProto
For TF 1.X  you can try,
```python
import tensorflow as tf
config = tf.ConfigProto()
config.gpu_options.allow_growth = True
sess = tf.Session(config=config)
```

**Comment by sjtusmartboy** [comment]
@ymodak I've tried limiting memory growth as mentioned above, without any help. Because the model involves adagrad op, the internal variables of which require three times the model size, which is 3*12gb = 36gb > 32gb of the gpu memory. So it's useless to set `config.gpu_options.allow_growth = True`. Any other suggestions?

**Comment by sjtusmartboy** [comment]
What I desired is the parallel model training that could split large model on one machine with eight gpus. Each part of the model is trained on the single gpu, and then the results are combined, just the philosophy of map-reduce, for the reason that each gpu memory is not large enough to hold the entire model, not the MirroredStrategy that simply makes the replica of model on different gpus.

**Comment by crccw** [comment]
This is not supported natively in TF yet. We're certainly interested in it. Could you describe your use case more if possible? Are you using a deep and wide model?

You can look into Mesh Tensorflow.

**Comment by sjtusmartboy** [comment]
@crccw The model is exactly the wide-and-deep model. Mesh Tensorflow seems to be one of the solutions that implement model parallelism, however, mesh tensorflow involves so much revise of the original model code. Maybe some other distribution strategies like MirroredStrategy are welcomed. Or whether you can any materials describing the detail implementation and architecture of MirroredStrategy so that user can develop the strategies by themselves?

**Comment by crccw** [comment]
MirroredStrategy use a custom variable_creator[1] to replica each variable on all devices. It launches computation on all devices by using multiple threads. In each thread, it's essentially:

with tf.device("xxx"):
   do_the_work()

(The actual code is much more complicated in order to make things work with other parts of TF).

After getting the gradient, it AllReduce them and each replica applies the gradient by itself. 

Developing your own strategy is not trivial. Optionally you can look into ZeRO (https://arxiv.org/abs/1910.02054). One of its optimization is to distribute the optimizer states. This is possible to implement by wrapping optimizers. It's still non trivial, but you don't need to touch your model code.

[1] https://www.tensorflow.org/api_docs/python/tf/variable_creator_scope
[2] https://arxiv.org/abs/1910.02054

**Comment by sjtusmartboy** [comment]
@crccw Thanks a lot for your helpful advice. ZeRO seems to be amazing, and [here](https://github.com/microsoft/DeepSpeed) is the micorsoft's implementation of the optimizer on Pytorch. Any plan to support it on tensorflow?

**Comment by crccw** [comment]
We don't have concrete plans at this moment. Please understand that we need to prioritize this among other things that are also important. I'll keep this ticket updated.

**Comment by myunuro** [comment]
Hello, is there any update of this thread? We are planning to train a model that may even not fit into a100 which has 40GB GPU memory. And we are seeking for model parallelism solutions. Or something similar to Pipeline parallelism[1] in Pytorch should help.

[1] https://pytorch.org/docs/stable/pipeline.html

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
