### ISSUE TITLE
Dose TensorFlow has tf.sparse.segment_max? how to code it by customer?

### ISSUE THREAD

**Issue by wangshang19911011** [tensorflow/tensorflow#37564]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by Saduf2019** [comment]
@wangshang19911011 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?
please share simple stand alone code for us to replicate the issue.

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Saduf2019** [comment]
@wangshang19911011 
i looked up for "tf.sparse.segment_max" in tensorflow website and do not find anything related to this, there is no such module in case you are looking to use it. [tf.math.segment_max ](https://www.tensorflow.org/api_docs/python/tf/math/segment_max)is present.

**Comment by Saduf2019** [comment]
@wangshang19911011
please update on the above comment

**Comment by wangshang19911011** [comment]
@Saduf2019 Thanks for reply. I'm working with sparse input, tf.math.segment_max is not so good with sparse input. I tried code  tf.math.segment_max by myself, but it is too hard. Hope tensorflow will has this module.

**Comment by EdwardCuiPeacock** [comment]
Is this feature going to be supported?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
