### ISSUE TITLE
Cumulative decaying sum

### ISSUE THREAD

**Issue by Dominik1123** [tensorflow/tensorflow#37567]
**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): Yes (with some guidance)

**Describe the feature and the current behavior/state.**

Add a new function `cumsum_decay` which computes the cumulative sum along an axis while multiplying the previous element with a scalar decay factor `p`:

    c_i = x_i + p*c_{i-1}    for i >= 1
    c_i = x_i                for i == 0

Example interface:

    def cumsum_decay(x, p, axis=0, exclusive=False, reverse=False, name=None):

where

* `x, axis, exclusive, reverse, name` are similar to [`tf.math.cumsum`](https://www.tensorflow.org/api_docs/python/tf/math/cumsum),
* `p` is a scalar tensor.

**Will this change the current api? How?**

It will add one function `tf.math.cumsum_decay`.

**Who will benefit with this feature?**

Doing this sort of computation comes up repeatedly, for example see these StackExchange questions:

* [Increasing each element of a tensor by the predecessor in Tensorflow 2.0](https://stackoverflow.com/q/60590333/3767239)
* [Can the cumsum function in NumPy decay while adding?](https://stackoverflow.com/q/28915088/3767239)
* [Parallel or efficient computation of value with momentum](https://cs.stackexchange.com/q/73746/23162)

**Any Other info.**

Since I'm not familiar with the tensorflow core, I cannot judge whether this feature is easy to implement based on the implementation of `cumsum`.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
