### ISSUE TITLE
Can I use TensorFlow Multi-worker training with two machines, which one has GPUs, the other only has CPU?

### ISSUE THREAD

**Issue by maqy1995** [tensorflow/tensorflow#37690]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

- TensorFlow version : 2.1.0

I have two machines, machine1 has GPUs and machine2 only has CPUs. I want to know if they can use Multi-worker training in Tensorflow, that is, during the distributed training, machine1 uses GPUs and machine2 uses CPUs.

I followed this tutorial to experiment:
https://tensorflow.google.cn/tutorials/distribute/multi_worker_with_keras?hl=en

But there are some error:
> tensorflow.python.framework.errors_impl.InternalError: Collective Op CollectiveBcastSend: Broadcast(1) is assigned to device /job:worker/replica:0/task:0/device:GPU:0 with type GPU and group_key 1 but that group has type CPU [Op:CollectiveBcastSend]

when I set machine1(has GPUs) not to use GPUs:
```
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
```
my code run successfully.

I want to know: Can I use machine1's GPUs and machine2's CPUs to do distributed learning?

**Comment by ckkuang** [comment]
As you can see from the error, such heterogeneous distributed training is currently not supported in TensorFlow. I would recommend you to use the machine with GPU using MirroredStrategy (single-machine training), and in fact, the training speed is most likely to surpass the distributed setting as you described because:
1. The GPU machine needs to wait for the non-GPU machine for every training step to aggregate the gradients, so training speed is bounded to the slower machine.
2. The network cost of gradient aggregation is usually non-negligible in distributed training. BTW TensorFlow do offer some optimizations like overlapping gradient aggregation with back propagation, if you are interested, check out [this video](https://www.youtube.com/watch?v=6ovfZW8pepo&list=PLQY2H8rRoyvzuJw20FG82Lgm2SZjTdIXU&index=11&t=0s) from the recent TensorFlow dev submit.
