### ISSUE TITLE
How to install/run/use TensorFlow on windows machines?

### ISSUE THREAD

**Issue by as1ndu** [tensorflow/tensorflow#377]

**Comment by mrry** [comment]
The current Windows solution is to run TensorFlow in a Docker container. This StackOverflow thread has discussion of how to do this: http://stackoverflow.com/questions/33616094/tensorflow-is-it-or-will-it-sometime-soon-be-compatible-with-a-windows-work . If you have questions about how to get this running, S

Otherwise, adding more Windows support is an open issue (#17), so I'll close this for now.
