### ISSUE TITLE
Backport #31378 to 1.15

### ISSUE THREAD

**Issue by LukeNotable** [tensorflow/tensorflow#37701]
Since a `pipenv check` when using TF 1.15.2 now yields:
```
37524: tensorflow <2.0 resolved (1.15.2 installed)!
Tensorflow 2.0 fixes a potential security vulnerability where decoding variant tensors from proto could result in heap out of bounds memory access.
```
Can a 1.15.3 be made with #31378 incorporated?

**Comment by mihaimaruseac** [comment]
The patch is already included in `r1.15` and later 

https://github.com/tensorflow/tensorflow/blob/bab74a15d9ad6bb9066b3e31d601d6a45b1cb221/tensorflow/core/framework/tensor.cc#L518-L522

**Comment by mihaimaruseac** [comment]
All of these tags have the patch from the original commit: v2.2.0-rc1 v2.2.0-rc0 v2.1.0 v2.1.0-rc2 v2.1.0-rc1 v2.1.0-rc0 v1.15.2 v1.15.0 v1.15.0-rc3 v1.15.0-rc2 v1.15.0-rc1 v1.15.0-rc0 

The #31378 PR was an attempt at fixing 1.14 with a patch release. Unfortunately, 1.14 was released in a bad state and we cannot patch it. Anyway, this is not an issue since 1.14 is outside the support window anyway

**Comment by ymodak** [comment]
Closing this issue since it's answered. Feel free to reopen if necessary. Thanks!
