### ISSUE TITLE
TFDS tests fail with tf-nightly

### ISSUE THREAD

**Issue by vijayphoenix** [tensorflow/tensorflow#37705]
**System information** 
- TensorFlow version: - `tf-nightly` 
- Python version: - 3.6

**Describe the current behavior**
Tensorflow-dataset tests fail with tf-nightly while it works fine with TF 1.15 and TF 2.1

**Describe the expected behavior**
Tests should pass.

**Standalone code to reproduce the issue** 
[Colab Link](https://colab.research.google.com/drive/1kdqmjjp-Omg3GfKO4FthubegCnJUrNqf#scrollTo=xB6MPLOCrtQ7)

More Info: https://github.com/tensorflow/datasets/issues/1670

**Comment by Saduf2019** [comment]
i have replicated mentioned issue it [persist](https://colab.sandbox.google.com/gist/Saduf2019/9ab988049e5bda1ed0f2046abeeca426/37705.ipynb) in nightly

**Comment by gowthamkpr** [comment]
@vijayphoenix This issue is already been discussed [here](https://github.com/tensorflow/datasets/issues/1670). This issue is primarily due to tfds api itself itself and has already been posted there. Closing this issue as it belongs to [tensrflow/datasets repo](https://github.com/tensorflow/datasets/issues).

**Comment by Conchylicultor** [comment]
Our tests are back to green. Thank you: https://source.cloud.google.com/results/invocations/1f44cdab-ab19-4b5d-8cc7-1793fb51864a/targets/tensorflow_datasets%2Fgh_testing%2Fcontinuous/log
