### ISSUE TITLE
corrupted tfrecord error should also have the info of file name

### ISSUE THREAD

**Issue by cheyang** [tensorflow/tensorflow#37751]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

Could TensorFlow 2.0 add the name of tfrecord file  when the file is corrupted in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/record_reader.cc#L105 ? It  is very helpful for investigating  tfrecord file issue or storage issue.

we tried to add  like https://github.com/cheyang/tensorflow/commit/54015629282b35d848d3c64550d15c3804e05c8d

But it has segment fault issue. 

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
