### ISSUE TITLE
tf.Module does not update state when a trackable attribute is reassigned a nontrackable

### ISSUE THREAD

**Issue by ilia-kats** [tensorflow/tensorflow#37806]
**System information** 
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian Sid and Linux Arch
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: 
- TensorFlow installed from (source or binary): PyPi binary
- TensorFlow version (use command below): v2.1.0-rc2-17-ge5bf8de 2.1.0
- Python version: - Bazel version (if compiling from source): 3.7.6
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When subclassing tf.Module and assigning a tf.Variable to an attribute, then later replacing it with a constant, tensorflow does not delete the Variable from its internal list of tracked objects. This leads to e.g. the Variable being saved and loaded with tf.saved_model, even though it's no longer referenced by any user-visible attribute.

**Describe the expected behavior**
Tensorflow correctly deletes the tf.Variable from its internal state.

**Standalone code to reproduce the issue** 
```python
class test(tf.Module):
    pass

a = test()
a.var = tf.Variable(1)
a.const = tf.constant(2)
a.var = tf.constant(a.var.numpy())

tf.saved_model.save(a, "a")
al = tf.saved_model.load("a")
```
Trying to access `al.const` throws an exception:
```python
al.const
```
```python
AttributeError: '_UserObject' object has no attribute 'const'
```
However, `al.var` still contains the tf.Variable:
```python
al.var
```
```python
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=1>
```

**Other info / logs**

As far as I can tell, the problem is that `AutoTrackable.__setattr__` does not delete its internal tracking state if a Trackable is replaced by something non-trackable, it only handles cases where a non-trackable is replaced by a Trackable or a Trackable is replaced by another Trackable.

**Comment by Saduf2019** [comment]
i have replicated the code shared and issue persist, please find [gist here](https://colab.sandbox.google.com/gist/Saduf2019/50b876d78a699e5ac4feaef73b2dfd84/37806.ipynb)

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210524, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/aed14a440460e3cbf025d7932734bf8b/untitled7.ipynb). Thanks!

**Comment by kumariko** [comment]
I could reproduce the issue with TF 2.7 . Please, find the gist [here](https://colab.research.google.com/gist/kumariko/8a66abfc6f34386539a6e68d03b5b7f9/untitled7.ipynb#scrollTo=fPzJ0Pz_8T8A). Thanks!

**Comment by SuryanarayanaY** [comment]
@ilia-kats ,
As per Documentation:

> A module is a named container for [tf.Variable](https://www.tensorflow.org/api_docs/python/tf/Variable)s, other [tf.Module](https://www.tensorflow.org/api_docs/python/tf/Module)s and functions which apply to user input.

Since all the assignments you have done are outside the Module it only tracks Variables(trackables) by default and wont accept constants that are no trackable and the assignment `a.var = tf.constant(a.var.numpy())` is not going to override the previous assignment `a.var = tf.Variable(1) `.

However if you can do the same inside a class that subclasses `tf.Module` then it update the state even if you assign trackable to non-trackable. Hence in the below code the assignment `self.b = tf.constant(self.b.numpy())` overrides
`self.b = tf.Variable(tf.zeros([output_size]), name='b') `

```
class Test(tf.Module):
  def __init__(self, input_dim, output_size, name=None):
    super().__init__(name=name)
    self.w = tf.Variable(
      tf.random.normal([input_dim, output_size]), name='w')
    self.b = tf.Variable(tf.zeros([output_size]), name='b')
    self.b = tf.constant(self.b.numpy())
```

Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/ba6a151432d69e117cb9040b98b17243/37806.ipynb) for the demo where i replicated all the behaviour mentioned above.Hope this clarifies your query.

Thankyou!
