### ISSUE TITLE
Allow different prefixes for TF_SYSTEM_LIBS libraries

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#37835]
**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Using TF_SYSTEM_LIBS to compile TensorFlow requires to have the libraries installed into a common prefix. It is however not uncommon to have different prefixes for different software (think: /opt/foo-1.x.y, /opt/bar-w.e.r...)

However TF currently only supports a single prefix via `PREFIX, INCLUDEDIR and LIBDIR`.

So what would be great is having one environment variable per dependency, e.g. `TF_PROTOBUF_PREFIX` to set this to the folder containing the `include`, `bin` etc folders.

Alternatively: As all the stuff (headers, binaries) must already be able to be found: Why not use the environment variables PATH, CPATH, (LD_)LIBRARY_PATH? Or a similar (maybe new) variable supporting multiple paths?

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

Package maintainers

**Comment by npanpaliya** [comment]
Even I'm facing the same error while using TF_SYSTEM_LIBS=org_sqlite. I have correctly set PREFIX, INCLUDEDIR and LIBDIR to point to the installed location of sqlite with proper suffixes `include` and `lib` to PREFIX. In third_party/systemlibs/sqlite.BUILD, I've also created a genrule to create the symlinks of sqlite's headers which works correctly but somehow my TF's build still fails for not able to find libsqlite.so. For this I've also explicitly set LD_LIBRARY_PATH to point to the location of libsqlite.so. Still no luck. Kindly provide some thoughts on this.

Also, I believe setting PREFIX, INCLUDEDIR and LIBDIR variables should suffice for TF to locate the headers and libraries for any external dependency, instead of creating symlinks to them or setting any additional variables like LD_LIBRARY_PATH.

**Comment by npanpaliya** [comment]
@Flamefire - I didn't understand the reason behind thumbs down emoji on above comment.
Do you mean what I'm trying is incorrect or what I believe about variables is wrong? Or may be I added a comment in wrong issue?

**Comment by Flamefire** [comment]
This is a feature request for introducing/supporting a different install prefix for each dependency or alternatively using a list of paths to allow installing dependencies into different prefixes. I don't see how your bug report using the existing variables relates to a feature request and can be "the same error".    
So yes, wrong issue. Updating the initial description to make it clearer

**Comment by gunan** [comment]
Ping! @perfinion @angerson

**Comment by Flamefire** [comment]
*Ping*

This currently seems to apply to protobuf and jsoncpp
