### ISSUE TITLE
How to solve this problem?(download_dependencies.sh)(c++ tensorflow)

### ISSUE THREAD

**Issue by heartraeh** [tensorflow/tensorflow#37846]
downloading https://github.com/google/googletest/archive/release-1.8.0.tar.gz
downloading https://mirror.bazel.build/github.com/google/nsync/archive/0559ce013feac8db639ee1bf776aca0325d28777.tar.gz

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

**Comment by Saduf2019** [comment]
@heartraeh 
It looks like you haven't used a template to create this issue. Please resubmit your issue using a template from [here](https://github.com/tensorflow/tensorflow/issues/new/choose). We ask users to use the template because it reduces overall time to resolve a new issue by avoiding extra communication to get to the root of the issue. 

As per the error please refer to #31799 #35747, we will need the tensor flow version and steps performed before you encountered the error to help you resolve the issue

**Comment by Saduf2019** [comment]
@heartraeh
please update on the above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
