### ISSUE TITLE
Train time multi crop augmentation

### ISSUE THREAD

**Issue by colt18** [tensorflow/tensorflow#37868]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by Saduf2019** [comment]
@colt18
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.

please share the error log,code for which this feature implementation is required
We ask for this, because it is really difficult to help without that information. Thanks!

**Comment by Saduf2019** [comment]
@colt18
Please update on the above comment

**Comment by Saduf2019** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
