### ISSUE TITLE
**debug feature** for debugging numeric instability, like nan or infinity

### ISSUE THREAD

**Issue by bela127** [tensorflow/tensorflow#37904]
**System information**
- TensorFlow version (you are using): nightly
- Are you willing to contribute it (Yes/No): cant do it alone, but willing to help

**Describe the feature and the current behaviour/state.**
I propose a **debug feature** for debugging numeric instability. The functionality should be similar to `tf.debugging.enable_check_numerics()` but more granular, but still more high level then `tf.debugging.check_numerics`.

Implementation Idea:
A `tf.debugging.check_func_numerics` annotation is added. It can be applied to ops warped in a python eager function and to tf.functons.
It will add numerics checks to all ops used in this function and, this is IMPORTANT, to all corresponding gradient ops.

The part of a model which courses numeric instability can be identified with this.

**Will this change the current api? How?**
it will add another debugging function/annotation, so the standard api is not changed.

**Who will benefit with this feature?**
Everyone with problems with nan and infinity in there models.
Especially for big models where `tf.debugging.check_func_numerics` can not be applied to the hole model.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
