### ISSUE TITLE
Anconda Tensorflow-GPU 2.1.0 cudart64_101.dll not found

### ISSUE THREAD

**Issue by leocd91** [tensorflow/tensorflow#37938]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 64bit 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Conda
- TensorFlow version: 2.1.0
- Python version: 3.7.6
- Installed using virtualenv? pip? conda?: Conda
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: NVIDIA GTX 1060 6GB

**Describe the problem**
Can't use tensorflow with GPU.
This warning always show up : 
2020-03-26 14:16:44.969758: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'cudart64_101.dll'; dlerror: cudart64_101.dll not found
2020-03-26 14:16:44.975297: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
1. Installed CUDA on Windows
2. Setting the Path as the tutorial said
3. Installed tensorflow with "conda install -c anaconda tensorflow-gpu"

**Any other info / logs**
Cupy works (need cuda also) on my current environment. So I wonder what's wrong.
I found multiple cudart64_101.dll in these directories : 
1. On Cuda installation : C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.1\bin
2. On Anaconda environment directory : C:\Users\user\Anaconda3\Library\bin

**Comment by Saduf2019** [comment]
@leocd91 

please refer to these issues with similar error:#36111 #33319 #31018 
and these [comments](https://github.com/tensorflow/tensorflow/issues/35872#issuecomment-581681377) [for reference](https://github.com/tensorflow/tensorflow/issues/29831#issuecomment-504496546)

**Comment by theadityasam** [comment]
Hey @leocd91 
I believe you have installed cuDNN after CUDA? 
The typical flow for installing tf-gpu would be something like this-
- Download and install CUDA toolkit.
- Download cuDNN, extract contents to CUDA toolkit path(replace if asked).
- Check if CUDA_HOME is present. 
- Create an environment in python and do "pip install tensorflow-gpu" 
If you've followed the above steps and are still getting error then it might be due to different versioning(refer [this link](https://www.tensorflow.org/install/source_windows#gpu)) 
What I would recommend you is to uninstall CUDA and then simply run 
```
conda create --name tf_gpu
conda activate tf_gpu
conda install tensorflow-gpu
```
Conda will take care of all CUDA dependencies.

**Comment by leocd91** [comment]
Hi, I already all those steps too, and any other suggestion #36111 #33319 #31018 with no results.
okay, thanks @theadityasam for the suggestion, I'll try to uninstall the cuda then just use the one from anaconda.
I'll inform you guys quickly.

**Comment by leocd91** [comment]
all suggestions done, .dll still not found.
now trying to remove all type of 10.1 cuda in windows and conda, and reinstall anaconda and then the tensorflow-gpu.

**Comment by leocd91** [comment]
still not found.

I tried to downgrade to 1.15, still not found.

**Comment by thomasjungblut** [comment]
wrestled the same problem for the whole evening, here's what fixed it for me (TF 2.1):
* install the "Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017, and 2019" 
* enable long paths: https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing
* install CUDA 10.2 (instead of 10.1) and the corresponding cudnn package
* define CUDAPATH and PATH to point to the CUDA 10.2 installation directory
* copy the cudart64_101.dll from the 10.1 directory into the 10.2 installation
* install a vanilla python3.7.7 (https://www.python.org/downloads/) 
* run a plain `pip3 install tensorflow`
* test with a plain `python3 -c "import tensorflow as tf; print(tf.reduce_sum(tf.random.normal([1000, 1000])))"`

And everything works. I'm not sure where that disparity between CUDA 10.2 and 10.1 comes from, especially since the documentation ultimately requires CUDA 10.1, but it is fine to load all the other dlls. 

It definitely did not work for me to just use CUDA 10.1 and use it as part of the PATH.

**Comment by tovaroe** [comment]
I have the a similar setup as leocd91 (with a Titan Xp) and having the same Problem. Regardless of what I try, cudart64_101.dll isn't found. Tried with anaconda/miniconda and installing with conda or pip (and manual installation of CUDA/CUDNN). 
Two more things that might have to do with this problem:
1. I had to set the CONDA_DLL_SEARCH_MODIFICATION_ENABLE to be able to import other packages (such as numpy)
2. conda install tensorflow=1.14 works perfectly fine (1.15 doesn't work though - dll not found)

**Comment by gunan** [comment]
Conda packages are built and maintained by the community, and anaconda. I will redirect the issue to @jjhelmus

**Comment by jjhelmus** [comment]
leocd91 If you are using the Tensorflow package from Anaconda you can open an issue in https://github.com/ContinuumIO/anaconda-issues/issues. I can try to help with the additional information request in that template.

**Comment by yakovkeselman** [comment]
The following command really helped. My conda version is 4.8.3 and my TF version is 2.1.0, installed prior to the below command (probably via pip). Thanks @theadityasam!

`conda install tensorflow-gpu`

**Comment by leocd91** [comment]
ok, will try it again, but that tutorial is one of the tutorial that I have tried.

**Comment by ymodak** [comment]
> lIf you are using the Tensorflow package from Anaconda you can open an issue in https://github.com/ContinuumIO/anaconda-issues/issues.

Closing this issue since TF Anaconda build issues are tracked separately in the above tracker. Thanks!
