### ISSUE TITLE
More easier setup for building and using Tensorflow from source for mods and adds

### ISSUE THREAD

**Issue by shyamalschandra** [tensorflow/tensorflow#3798]
Why does tensorflow use bazel instead of ./configure; make; make install?

Could you please make the building from source much more streamlined?

Thanks!

**Comment by aselle** [comment]
We use bazel because it is an open source version similar to our internal build tool. As such, we can have one set of build files for our internal and external version. Generally speaking, it is the simplest way to keep our build working between open source and internal and supporting many build files would divert development time from actual core improvements. We do, however, provide many binary methods including docker. There is some limited support for Makefiles and CMake, but I think you will find that even less streamlined.

It is worth noting ./configure is only streamlined for projects with very few dependencies. Many ./configure scripts require --with-xxx= to provide paths to libraries, etc. 

If there are any particular problems that are making bazel difficult to use, could you enumerate them?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please reopen when additional information becomes available.

**Comment by shyamalschandra** [comment]
Reasons why I don't like Bazel?
1. I haven't gotten tensorflow to compile and run from source.
