### ISSUE TITLE
Unable to cross compile TFLite for Raspberry Pi Zero  using Docker image nightly-develop

### ISSUE THREAD

**Issue by garethjscoleman** [tensorflow/tensorflow#38037]
**System information**
- OS Platform and Distribution:  Linux Mint 19:03 (based on Ubuntu 18:04)
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A ?  Attempting to crosscompile tensorflowlite for Raspbery Pi Zero (Armv6) 
- TensorFlow installed from (source or binary): nightly-develop  docker image
- TensorFlow version: 2.2
- Python version: 2.7 
- Installed using virtualenv? pip? conda?: docker file from latest nightly build
- Bazel version (if compiling from source): bazel 0:15:0
- GCC/Compiler version (if compiling from source): gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0
- CUDA/cuDNN version: n/a
- GPU model and memory: none

When cross compiling for raspberry pi zero (ARMv6), as per instructions on following page [https://www.tensorflow.org/lite/guide/build_rpi](https://www.tensorflow.org/lite/guide/build_rpi)
and running the command indicated to build for the ARMv6 architecture, 
`./tensorflow/lite/tools/make/build_rpi_lib.sh TARGET_ARCH=armv6`

  there are errors indicating that the compiler options set are incorrect

/usr/arm-linux-gnueabihf/include/bits/stdio.h: In function 'int getchar()':
/usr/arm-linux-gnueabihf/include/bits/stdio.h:44:14: sorry, unimplemented: Thumb-1 hard-float VFP ABI
 getchar (void)

**Any other info / logs**

if I examine the file 

`./tensorflow/lite/tools/make/build_rpi_lib.sh
`
I found that the TARGET_ARCH parameter was hard coded for armv7 in the final line of the file

If I edit the file so that this reads

`CC_PREFIX=arm-linux-gnueabihf- make -j 3 -f tensorflow/lite/tools/make/Makefile TARGET=rpi TARGET_ARCH=armv6
`
(the hardcoding is not ideal for obvious reasons )
 and then change the armv6 compiler options in

`tensorflow/lite/tools/make/targets/rpi_makefile.inc
`
to the following

```
ifeq ($(TARGET_ARCH), armv6)
CXXFLAGS +=
-marm
-mfpu=vfp
-mlong-calls
-mthumb-interwork
-mfloat-abi=hard

CCFLAGS += \
  -marm \
  -mfpu=vfp \
  -mlong-calls \
  -mthumb-interwork \
  -mfloat-abi=hard

LDFLAGS := \
  -Wl,--no-export-dynamic \
  -Wl,--exclude-libs,ALL \
  -Wl,--gc-sections \
  -Wl,--as-needed \
  -mfpu=vfp \
  -mlong-calls \
  -mfloat-abi=hard \
  -mthumb-interwork 
endif

```
I can compile without errors (and just a couple of warnings).

Given that it seems to be difficult (or just very slow) to compile bazel directly on a raspberry pi zero due to the lack of memory and that increasing the memory available (even via machine virtualisation such as QEMU appears impossible), I think that for deployment on a PI Zero, cross compiling is the only way forward. At the moment I can inference, but only by using a full tensorflow implementation, which is really too slow for my needs) 

Additionally it would be nice to have a way to generate a python wheel as well. The main ci_build process does this for the full fat tensorflow package, (and i can run one of those on the pi zero), but I'd like to just use tensorflow-lite for my inferencing, as i think any performance improvements that I can get would be beneficial. I'm using a Pi Zero for it's low power consumption for energy efficiency reasons, so swapping out to a PI 3 or Pi 4 would not really be viable for my project. 

thanks for your help

**Comment by mikhailkin** [comment]
Failed to run on Pi Zero W with the recipe. "Illegal instruction" in the end

**Comment by askemottelson** [comment]
I'm facing the same issue, tried with different flags, but still "Illegal instruction" when importing the library.

```
      -march=armv6zk \
      -marm \
      -mfpu=vfp \
      -mlong-calls \
      -mthumb-interwork \
      -mfloat-abi=hard
```

I also tried compiling with [this](https://github.com/rvagg/rpi-newer-crosstools/tree/master/x64-gcc-6.5.0/arm-rpi-linux-gnueabihf) gcc made for rpi, but it lacks the c++ python3.7m headers and won't compile.

**Comment by mikhailkin** [comment]
I've left to compile on Raspberry. At the end got:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/tflite_runtime/interpreter_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /usr/local/lib/python3.7/dist-packages/tflite_runtime/_interpreter_wrapper.so: undefined symbol: __atomic_compare_exchange_8
```
I've added -latomic in make files. But since bazel was in use, interpreter_wrapper.so was linked without it:

> arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv6l-3.7/interpreter_wrapper/interpreter_wrapper_wrap.o build/temp.linux-armv6l-3.7/interpreter_wrapper/interpreter_wrapper.o build/temp.linux-armv6l-3.7/interpreter_wrapper/numpy.o build/temp.linux-armv6l-3.7/interpreter_wrapper/python_error_reporter.o build/temp.linux-armv6l-3.7/interpreter_wrapper/python_utils.o -L/home/pi/Soft/tensorflow/tensorflow/lite/tools/make/gen/rpi_armv6/lib/ -ltensorflow-lite -o build/lib.linux-armv6l-3.7/tflite_runtime/_interpreter_wrapper.so

**Comment by askemottelson** [comment]
@mikhailkin Could you try:
```
LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0 python3
>>> from tflite_runtime.interpreter import Interpreter
```

**Comment by mikhailkin** [comment]
> ```
> LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0 python3
> ```
Worked for me! Thank you a lot!

**Comment by askemottelson** [comment]
> > ```
> > LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0 python3
> > ```
> 
> Worked for me! Thank you a lot!

@mikhailkin would you mind sharing your .whl? I've been trying to cross compile for days!

**Comment by mikhailkin** [comment]
> 
> @mikhailkin would you mind sharing your .whl? I've been trying to cross compile for days!

@askemottelson it was the first thing I intended to do... but I've called "make clean" in order to try other options.
Anyway, I copied binaries from /usr/local/lib/python3.7/dist-packages
https://drive.google.com/drive/folders/1hm4ShvPCqXYDuh7ijA6tepycFuP-II4K
I'll put wheel as soon as it is rebuilt.
Command to launch
`LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0 python3 <your_args>`

**Comment by askemottelson** [comment]
> Anyway, I copied binaries from /usr/local/lib/python3.7/dist-packages
> https://drive.google.com/drive/folders/1hm4ShvPCqXYDuh7ijA6tepycFuP-II4K

Thanks, but when i use your binaries I get the following
```
>>> import tflite_runtime.interpreter
Traceback (most recent call last):
  File "/home/pi/ada-alarm/ML/lite/dist/tflite_runtime/interpreter_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tflite_runtime._interpreter_wrapper'
```

**Comment by rajurimu** [comment]
Mikhail - new to pi world. How do I run your wheel file from rpi directly?

**Comment by rajurimu** [comment]
Mikhail - this works compared to the official TF Lite instructions. With the official, I am still getting ModuleNotFoundError: No module named 'tflite_runtime' even after a very long installation on rpi zero.

However when I run your compiled whl, I am getting ModuleNotFoundError: No module named '_interpreter_wrapper'.

I am on RPI Zero and trying to install TF Lite Standalone. Above error comes when I use the following;
import tflite_runtime.interpreter as tflite

**Comment by rajurimu** [comment]
Can anyone help with this? Trying to install TFlite on Rpi zero (without TF). Any pointers / guidance will help. Thanks

**Comment by rajurimu** [comment]
> > Anyway, I copied binaries from /usr/local/lib/python3.7/dist-packages
> > https://drive.google.com/drive/folders/1hm4ShvPCqXYDuh7ijA6tepycFuP-II4K
> 
> Thanks. Works here!

When I run your compiled whl, I am getting ModuleNotFoundError: No module named '_interpreter_wrapper'.

I am on RPI Zero and trying to install TF Lite Standalone. Above error comes when I use the following;
import tflite_runtime.interpreter as tflite

I am using pip3 install for your wheel.

**Comment by askemottelson** [comment]
@rajurimu could you try the below?

```
wget https://github.com/askemottelson/ada-alarm/blob/master/ML/lite/dist/tflite_runtime-2.2.0rc3-cp37-cp37m-linux_armv6l.whl?raw=true
pip3 install tflite_runtime-2.2.0rc3-cp37-cp37m-linux_armv6l.whl
LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0 python3
...
from tflite_runtime.interpreter import Interpreter
```

**Comment by rajurimu** [comment]
> @rajurimu could you try the below?
> 
> ```
> wget https://github.com/askemottelson/ada-alarm/blob/master/ML/lite/dist/tflite_runtime-2.2.0rc3-cp37-cp37m-linux_armv6l.whl?raw=true
> pip3 install tflite_runtime-2.2.0rc3-cp37-cp37m-linux_armv6l.whl
> LD_PRELOAD=/usr/lib/arm-linux-gnueabihf/libatomic.so.1.2.0 python3
> ```
> 
> ```
> >>> from tflite_runtime.interpreter import Interpreter
> ```

askemottelson, this worked and i can load tflite runtime as you suggested. Many many many thanks for that. However when I run in Thonny, it gives me the following errors,

***
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: /home/pi/.local/lib/python3.7/site-packages/tflite_runtime/_interpreter_wrapper.cpython-37m-arm-linux-gnueabihf.so: undefined symbol: __atomic_compare_exchange_8

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pi/Desktop/Fruit_PiZero/fruit_testing_tflite.py", line 10, in <module>
    import tflite_runtime.interpreter as tflite
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter.py", line 46, in <module>
    from tflite_runtime import interpreter_wrapper as _interpreter_wrapper
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 17, in <module>
    _interpreter_wrapper = swig_import_helper()
  File "/home/pi/.local/lib/python3.7/site-packages/tflite_runtime/interpreter_wrapper.py", line 16, in swig_import_helper
    return importlib.import_module('_interpreter_wrapper')
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_interpreter_wrapper'
***
However these are resolved once I LD_PRELOAD Thonny with libatomic.so.

Many many many thanks to you. I have been trying to find solution for quite some time and was not successful. Thanks a lot.

A few followup questions though
1. Is there a way to build my own whl? Instruction from earlier thread did not work. If you have something which i can follow and learn will be very useful. I am at an entry level and trying to learn
2. Is there a way to 'avoid' LD_PRELOAD and have this always included instead of running LD_PRELOAD? Seems libatomic is referenced in many places as 'missing library' making it a part of PRELOAD

Thanks

**Comment by askemottelson** [comment]
hi @rajurimu 

As you can see from the thread I myself struggled with creating my own wheel for armv6 using the cross compilation scripts provided by tensorflow. It's definitely possible, it's about setting the right compiler flags (the missing atomic lib is related), and using the correct cross compiler. 

check https://www.tensorflow.org/lite/guide/build_rpi, but prepare to change the build scripts and CC/CX flags

**Comment by Bleyddyn** [comment]
https://github.com/tensorflow/tensorflow.git, commit 5c1c1085fe331de3dde07e6b3f40f69de4cb5a19.
Raspberry Pi Zero W (model name	: ARMv6-compatible processor rev 7 (v6l), any other relevant info?)

So far I haven't been able to get tflite to compile on the RPi itself.
First I had to increase swap to 1024MB to get very far at all.
Now it's failing on a link step, -o .../tensorflow/lite/tools/make/gen/linux_armv6l/bin/minimal, with errors about missing symbol __atomic_load_8 and others. I copied that particular call to g++, added -latomic and it linked.

However I'm not sure where to add that extra link. I'll keep poking around, but any suggestions would be great.

**Comment by freeedom67** [comment]
FYI i found a good working solution for running tensorflow(lite as well) on the ARM6 based raspberry pi (like the zero or the Pi1):

-get a pre compilied python wheel from https://github.com/lhelontra/tensorflow-on-arm/releases or compile it on your own. 
- Install it on the device using pip3

in python
import tensorflow as  tf

interpreter = tf.lite.Interpreter(model_path)

After a long time looking for a good solution I found this working pretty well!

**Comment by albertoisorna** [comment]
> FYI
> 
> I was able to find a working solution for running tensorflow(lite as well) on the ARM6 based raspberry pi (like the zero or the Pi1):
> 
> * get a pre compilied python wheel from https://github.com/lhelontra/tensorflow-on-arm/releases or compile it on your own.
> * Install it on the device using pip3.
> 
> in python:
> 
> ```
> import tensorflow as  tf
> 
> interpreter = tf.lite.Interpreter(model_path)
> ```
> 
> After a long time looking for a good solution I found this working pretty well and easy!

It worked for me, happily running TF 2.3 and TFlite in my Pi Zero :)

**Comment by askemottelson** [comment]
Sure, but I'd prefer not to have the entire TensorFlow installed, and just use the tflite_runtime lib for performance reasons

**Comment by mohantym** [comment]
Hi @garethjscoleman !
We are checking to see whether you still need help in this issue .Could you try with Python 3.6-3.8 with other tested configurations from [here](https://www.tensorflow.org/install/source#tested_build_configurations). Attaching relevant threads for reference. [link1](https://qengineering.eu/install-tensorflow-2-lite-on-raspberry-pi-4.html),[link2](https://www.tensorflow.org/lite/guide/build_cmake_arm),[link3](https://www.tensorflow.org/lite/guide/build_cmake_pip).Thanks!

**Comment by vivaaprimavera** [comment]
Applies to debian:bookworm,

Cross-compiling to rpi0 with

 make BASE_IMAGE=debian:bookworm PYTHON_VERSION=3.11 TENSORFLOW_TARGET=rpi0 docker-build 

Since bookworm already ships with python 3.11, adding the deadsnakes repo is no longer needed for compiling for python3.11, however since python3.11 changes the beaviour of pip, the following changes are needed to tensorflow/tensorflow/lite/tools/pip_package/Dockerfile.py3

#RUN yes | add-apt-repository ppa:deadsnakes/ppa
RUN echo "[global]" >> /etc/pip.conf
RUN echo " break-system-packages = true" >> /etc/pip.conf


The failure to link against libatomic it's still present.

The solution from @mikhailkin (using LD_PRELOAD) works.
