### ISSUE TITLE
Use only tensorflow-lite-gpu aar file

### ISSUE THREAD

**Issue by t-niroc** [tensorflow/tensorflow#38099]
I am trying to build an image recognition app and have a ML model ready which I have converted to .tflite type for using. I have used tflite and tflite-gpu aar files in my project for performing inference with the model and deployed it on my devices and it works fine. But I am concerned about the apk size after including these two aar. Is it possible to use just tflite-gpu aar file for my app? Or any other work around ?

**Comment by Saduf2019** [comment]
@t-niroc 
could you please share the tensorflow version on which this error is faced.

please refer to this [comment](
https://github.com/tensorflow/tensorflow/issues/25278#issuecomment-459609002), and let us know if its helps.

**Comment by t-niroc** [comment]
@Saduf2019 I am on the latest master branch. 
> 
> please refer to this [comment](https://github.com/tensorflow/tensorflow/issues/25278#issuecomment-459609002), and let us know if its helps.
This comment specifies to use only necessary ops to decrease size.  My question is a little different from that.

If I use all the ops and also want to use GPU acceleration, is it possible to use just the tensorflowlite-gpu.aar and avoid tensorflowlite.aar as an alternate way of reducing size?

**Comment by impjdi** [comment]
You probably cannot only use the GPU AAR as there is a fallback-to-CPU mechanism.  However, there are a couple of places where you can trim for binary size:

* Instead of using the builtin op resolver, you can create a custom op resolver with only the used ops and used that when initializing the Interpreter object.  I learned that the bare bone TFLite is 3-500kB, but when using the bulitin op resolver, binary size will increase to 1.5MB.
* You can employ a similar trick to GPU as well.  You can trim bunch of code in `delegates/gpu/common/model_builder` to only accept the ops that you care about and limit dependencies in `delegates/gpu/gl/kernels` and/or `delegates/gpu/cl/kernels`.

**Comment by t-niroc** [comment]
@impjdi Okay. Thanks a lot for the clarification.

**Comment by dhruv-arcot** [comment]
@impjdi How can you build these custom aar's/ op resolver? Is there any documentation of sorts?

**Comment by impjdi** [comment]
I'm not familiar with any TF documentation; maybe there is, maybe there isn't.  As an engineer, I look at existing code and try to mimic the closest example in the code base...

**Comment by mohantym** [comment]
Hi @t-niroc ! Does this [document](https://www.tensorflow.org/lite/guide/reduce_binary_size#build_with_custom_ops) answer your[ question](https://github.com/tensorflow/tensorflow/issues/38099#issuecomment-673240701)? Thanks!
