### ISSUE TITLE
Add a Mutable Hash Table of Ragged Tensors 

### ISSUE THREAD

**Issue by kieranricardo** [tensorflow/tensorflow#38263]
**System information**
- TensorFlow version 2.1:
- Are you willing to contribute it Yes:

**Describe the feature and the current behavior/state.**

`tf-nightly` has `MutableHashTableOfTensors` for fast lookups of key/tensor pairs. This feature request is to add similar functionality for `RaggedTensor`s, either by adding `RaggedTensor` support to `MutableHashTableOfTensors` or creating new ops for e.g. a `MutableHashTableOfRaggedTensors`. 

**Will this change the current api? How?** I don't think so. If extra `RaggedTensor` functionality is added `MutableHashTableOfTensors` I think the current `MutableHashTableOfTensors` API won't need to change. 

**Who will benefit with this feature?** Users who need to perform fast lookups on irregular data will benefit from this feature.

Personally I'd like to store a graph adjacency list as a `MutableHashTableOfRaggedTensors`, and then create a `tf.data.Dataset` pipeline to pre-process the graph data for machine learning. I'll implement this in [StellarGraph](https://github.com/stellargraph/stellargraph) to make our graph backend natively tensorflow!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
