### ISSUE TITLE
RuntimeError: Encountered unresolved custom op: Dilation2D.Node number 2 (Dilation2D) failed to prepare

### ISSUE THREAD

**Issue by sibadakesi** [tensorflow/tensorflow#38341]
What can i do when i must use Dilation2D op on the tensorflowlite? Thinks.
```
RuntimeError: Encountered unresolved custom op: Dilation2D.Node number 2 (Dilation2D) failed to prepare. 
```

**Comment by Saduf2019** [comment]
@sibadakesi 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 
please share a simple standalone code to replicate the issue faced.

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by sibadakesi** [comment]
Thinks a lot,i chose another  operators to soloved this problem!

**Comment by theotheo** [comment]
@sibadakesi Could you, please, tell what operators do you use to replace Dilation2D?

**Comment by aitikgupta** [comment]
> Thinks a lot,i chose another operators to soloved this problem!

Which operators are you talking about?
If you're talking about adding `allow_custom_ops=True`, could you explain the workflow in the interpreter?
