### ISSUE TITLE
Extract Model Variable from Serialize Graph File

### ISSUE THREAD

**Issue by RinascimentoMan** [tensorflow/tensorflow#38376]
**System information**
- TensorFlow version (you are using): 1.14.0
- Are you willing to contribute it (Yes/No): Yes.

**Describe the feature and the current behavior/state.**
![image](https://user-images.githubusercontent.com/16629752/78857533-2edc7080-7a5c-11ea-80a7-a69ccd51fc63.png)
When I save a graph in to keras.pb. Then I wan to acquire <b>model</b> variable. However, I cannot find a way to achieve.

**Will this change the current api? How?**
I am not sure.

**Who will benefit with this feature?**
This feature can help people transfer released model parameters into other format, such as ML flow, Keras etc.

**Any Other info.**

**Comment by k-w-w** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
