### ISSUE TITLE
Better documentation for the Embeddings Projector, especially graphs/edges?

### ISSUE THREAD

**Issue by johann-petrak** [tensorflow/tensorflow#38422]
Apparently it is possible to render edges between data points in the embeddings projector but I cannot find the documentation for this anywhere. It is also not clear what other things might be possible which are not obvious or documented.
A column called `__next__` may have special meaning, judging from one of the examples, but it is not clear what exactly it can be used for, what the requirements on the input are or what other special meaning column names there may exist.
Or am I missing some obvious documentation here?

**Comment by 17patelumang** [comment]
@ravikyram  can i work on this issue ? Could you please point me where to start ?

**Comment by 17patelumang** [comment]
@gowthamkpr  can i work on this issue ? Could you please point me where to start ?

**Comment by johann-petrak** [comment]
Does anyone have some initial pointers to start figuring this out? Is the original source code of the JavaScript available? The code used in the tensorboard page is uglified and not very readable.

**Comment by borhan-kazimipour** [comment]
I'm also interested to know the answers to the questions that @johann-petrak asked originally.

I did some reverse engineering and found `__next__` can be used to add links between nodes in the graph. There are some limitations though: 
- You can use line number (as in the embedding TSV file) to point to a node
- It should be a 1-1 relationship so you cannot have duplicates in your `__next__` column
- You cannot have a loop like 1 -> 2 -> 3 -> 1

Keen to know if there is any other special column!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
