### ISSUE TITLE
Broadcasting sparse indices

### ISSUE THREAD

**Issue by ngc92** [tensorflow/tensorflow#38429]
**System information**
- TensorFlow version (you are using): 2.1
- Are you willing to contribute it (Yes/No): Yes (partially, what can be done on the python side, and maybe CPU kernels)

**Will this change the current api? How?**
Add an operation to `tf.sparse.broadcast_indices` (feel free to suggest a beter name), doing the following:
```
tf.sparse.broadcast_indices(a, b, default_value): Given two sparse tensors of same dense shape, inserts `default_value` at positions such that a.indices == b.indices.
```
This would provide a basic building block for arbitrary pointwise-binary operations on SparseTensors. Therefore I would also suggest adding a function like
```
tf.sparse.map_binary_op(a, b, op, def_value=0):
   a, b = broadcast_indices(a, b, def_value)
   return SparseTensor(a.indices, op(a.values, b.values), a.shape) 
```

This would then allow for more efficient implementations e.g. of binary metrics when both labels and predictions are sparse, e.g. when calculating P@k statistics.

I think I can provide an initial, sub-optimal implementation that builds this on top of `tf.sparse.add` for default values of zero. Would you be interested in a PR like that (maybe putting it into experimental namespace at first)?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
