### ISSUE TITLE
real gradients of complex-valued functions

### ISSUE THREAD

**Issue by corcra** [tensorflow/tensorflow#3850]
I am experiencing _unexpected_ behaviour when taking gradients of a complex-valued function parametrised with real variables. It looks like the gradient with respect to the complex part of the function is (erroneously) zero.

Example:
```
> x = tf.constant(0.0)    # real-valued parameters of a complex-valued function
> y = tf.constant(0.0)
> z = tf.complex(x, y)    # the complex-valued function

> session.run(tf.gradients(z, x), {x:1.0, y:2.0})    # value of x and y don't matter
[1.0]    # good, expected
> session.run(tf.gradients(z, y), {x:1.0, y:2.0})
[0.0]    # bad, expecting 1j
```

Is the result being silently cast to real before being returned, or am I misusing `tf.gradients` somehow?

Using tensorflow version 0.9.0 with GPU on RedHat 4.8.6-4.

**Comment by girving** [comment]
This is expected behavior.  TensorFlow gradients are always mathematically of the form `dL/dx`, where `L` is a scalar *real* loss tensor.  If you ask for the gradient of something (`z` in this case) that isn't already scalar real, it assumes the gradients `dL/dz` are 1.  Since the imaginary part of 1 is zero, the chain rule gives zero in your second case.

Note that scalar and real here are essentially the same restriction.

**Comment by ibab** [comment]
I've opened an issue on this some time ago here: https://github.com/tensorflow/tensorflow/issues/2818.
Maybe it would be a good idea to not allow taking the derivative of a complex expression, to avoid confusion?
