### ISSUE TITLE
tf.function decorated functions fail in graph mode if any of the branches of conditionals would be invalid at runtime

### ISSUE THREAD

**Issue by csachs** [tensorflow/tensorflow#38539]
**System information** 
- Have I written custom code: yes
- OS Platform and Distribution: Ubuntu 18.04
- TensorFlow installed from: binary
- TensorFlow version: 2.1.0 
- Python version: 3.7.6

**Describe the current behavior**
As far as I followed the development of TF's @tf.function-decoration/autotracing, the aim is to mostly write ideomatic Python and have TF take care of building a corresponding TF op graph, with this feature being a highlight of TF2.

The simple function below, where one branch can only be properly executed when the conditional is met, albeit ideomatic Python, fails in graph mode, albeit it works in eager mode.

(I am aware that I can work around the situation; but I guess it not working as-is is a bug?)

**Describe the expected behavior**

The function working identically in both eager or graph mode.

**Standalone code to reproduce the issue** 
```python
import tensorflow as tf


@tf.function
def test_function(tensor):
    if tf.size(tensor) == 2:
        return tensor[1]
    else:
        return tensor[0]


tf.config.experimental_run_functions_eagerly(True)

print(test_function(tf.constant([1])))
print(test_function(tf.constant([1, 2])))
print(test_function(tf.constant([1, 2, 3])))

tf.config.experimental_run_functions_eagerly(False)

print(test_function(tf.constant([1])))
print(test_function(tf.constant([1, 2])))
print(test_function(tf.constant([1, 2, 3])))
```
```
> TF_CPP_MIN_LOG_LEVEL=2 python test.py
tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)
Traceback (most recent call last):
  File "test.py", line 20, in <module>
    print(test_function(tf.constant([1])))
  File "…/tensorflow_core/python/eager/def_function.py", line 568, in __call__
    result = self._call(*args, **kwds)
  File "…/tensorflow_core/python/eager/def_function.py", line 615, in _call
    self._initialize(args, kwds, add_initializers_to=initializers)
  File "…/tensorflow_core/python/eager/def_function.py", line 497, in _initialize
    *args, **kwds))
  File "…/tensorflow_core/python/eager/function.py", line 2389, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "…/tensorflow_core/python/eager/function.py", line 2703, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "…/tensorflow_core/python/eager/function.py", line 2593, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "…/tensorflow_core/python/framework/func_graph.py", line 978, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "…/tensorflow_core/python/eager/def_function.py", line 439, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "…/tensorflow_core/python/framework/func_graph.py", line 968, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in converted code:

    test.py:7 test_function  *
        return tensor[1]
    …/tensorflow_core/python/ops/array_ops.py:898 _slice_helper
        name=name)
    …/tensorflow_core/python/ops/array_ops.py:1064 strided_slice
        shrink_axis_mask=shrink_axis_mask)
    …/tensorflow_core/python/ops/gen_array_ops.py:9535 strided_slice
        shrink_axis_mask=shrink_axis_mask, name=name)
    …/tensorflow_core/python/framework/op_def_library.py:742 _apply_op_helper
        attrs=attr_protos, op_def=op_def)
    …/tensorflow_core/python/framework/func_graph.py:595 _create_op_internal
        compute_device)
    …/tensorflow_core/python/framework/ops.py:3322 _create_op_internal
        op_def=op_def)
    …/tensorflow_core/python/framework/ops.py:1786 __init__
        control_input_ops)
    …/tensorflow_core/python/framework/ops.py:1622 _create_c_op
        raise ValueError(str(e))

    ValueError: slice index 1 of dimension 0 out of bounds. for 'strided_slice' (op: 'StridedSlice') with input shapes: [1], [1], [1], [1] and with computed input tensors: input[1] = <1>, input[2] = <2>, input[3] = <1>.
```

**Comment by gadagashwini** [comment]
Could able to replicate the issue with Tf2.1.
Please find the [gist here](https://colab.sandbox.google.com/gist/gadagashwini/f0af4a0d27a4f1ebe8e9b37f20a13d51/untitled508.ipynb). Thanks

**Comment by mdanatg** [comment]
This is a known inconsistency that we hope to remedy, so I'll leave the issue open to track.

The main issue is that functions like `tf.size`, `tf.shape` and `tf.rank` always return a Tensor, forcing AutoGraph to create a tf.cond which triggers shape checks in both tensor[1] and tensor[0]. If the shape of tensor is unknown, the code once more works correctly.

Including a few workarounds below.

If the tensor is a vector, `len` will work consistently:

```
    if len(tensor) == 2:
        return tensor[1]
    else:
        return tensor[0]
```

If the tensor is higher-dimensional and you indeed need the entire size (rather than just the size of dimension zero), please use `.shape.num_elements()` instead of `tf.size` until this is resolved:

```
    if tensor.shape.num_elements() == 2:
        return tensor[1]
    else:
        return tensor[0]
```

In case `tensor.shape` may be unknown, the following code is more complete:

```
def proper_size(tensor):
  if tensor.shape.is_fully_defined():
    return tensor.shape.num_elements()
  return tf.shape(tensor)

...

if proper_size(tensor):
  return tensor[1]
else:
  return tensor[0]
```

**Comment by csachs** [comment]
@mdanatg thank you for the in-depth response, good to hear it's being addressed already.

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210525, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/ea14b161312f8dc20de763ac491bedee/38539.ipynb). Thanks!

**Comment by tilakrayal** [comment]
Was able to reproduce your issue in tf v2.7, please find the gist [here](https://colab.sandbox.google.com/gist/tilakrayal/849a93f687cf8c98d9e624b345f5bfb1/untitled156.ipynb). Thanks!

**Comment by mohantym** [comment]
@csachs !
I was able to replicate this issue in [2.11 ](https://colab.sandbox.google.com/gist/mohantym/b7afe87ba1f2024260fd458b132fe4ef/git_38539.ipynb#scrollTo=2VsOvFBu2gYw)and [nightly ](https://colab.sandbox.google.com/gist/mohantym/69795fc22ab374f89b9901fee2d7fbe4/git_38539.ipynb#scrollTo=ktIyHcDI6UQt)version. 
Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
