### ISSUE TITLE
Roadmap for publishing TFLite runtime on PyPi?

### ISSUE THREAD

**Issue by ivelin** [tensorflow/tensorflow#38642]
First off, congrats to the team for all the great progress made towards publishing tflite runtime 2.x binaries for a matrix of architectures and python versions.

I know the topic of publishing tflite-runtime on pypi has been discussed, but I cannot find an issue or thread to follow. Could you please point me to it if there is one?

Thank you!

**Comment by TBAALi-ros** [comment]
I'm not TBAALi 邮箱：jiaxx903@tom.com 签名由 网易邮箱大师 定制 On 04/18/2020 00:06, Ivelin Ivanov wrote: First off, congrats to the team for all the great progress made towards publishing tflite runtime 2.x binaries for a matrix of architectures and python versions. I know the topic of publishing tflite-runtime on pypi has been discussed, but I cannot find an issue or thread to follow. Could you please point me to it if there is one? Thank you! — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by jdduke** [comment]
Just to be clear, this would be to avoid pulling in the full TF module (which includes the TFLite runtime)?

**Comment by ivelin** [comment]
> Just to be clear, this would be to avoid pulling in the full TF module (which includes the TFLite runtime)?

Yes, exactly. Operating Edge / IoT applications focused on inference could benefit from a light ~10MB TFLite binary as opposed to a full 1GB+ TF download.

**Comment by terryheo** [comment]
@ivelin Is this what you're looking for?
https://www.tensorflow.org/lite/guide/python#install_just_the_tensorflow_lite_interpreter

**Comment by ivelin** [comment]
@terryheo I am aware of the page you shared and admit that it gets us pretty close to the end goal. Lots of great progress in the past year. We no longer need to build tflite from source.

I am hoping to eventually see something a bit more streamlined like the full tensorflow distribution: https://pypi.org/project/tensorflow/

**Comment by tschnoelzer** [comment]
I am looking for a version of pip3 install https://dl.google.com/coral/python/tflite_runtime-2.1.0.post1-cp37-cp37m-linux_armv7l.whl for the Raspberry Zero containing the ARM 6 processor. I can not find an example to build and install just the runtime. Any help appreciate!

**Comment by mhsmith** [comment]
I think the main advantage of releasing tflite-runtime on PyPI is that it would allow third-party Python libraries to declare it as a requirement. That isn't currently possible, as there's no way of declaring a requirement on a set of URLs.  So those libraries have to require the full tensorflow package instead, which, on Linux, increases the size from 2 MB to 420 MB.

**Comment by gilescoope** [comment]
Also why is the interpreter on https://www.tensorflow.org/lite/guide/python still Tensorflow 2.1. 
2.2 has been out for months now, Python 3.8 even longer and there is still no support.

**Comment by mhsmith** [comment]
@gilescoope: https://www.tensorflow.org/lite/guide/python now has Python 3.8 packages for Linux, but not for Windows or Mac. The TensorFlow version is still 2.1.0.

**Comment by andreselizondo-adestech** [comment]
Some TensorFlow 2.3.0 models are not compatible with the TFLite binary provided by: https://www.tensorflow.org/lite/guide/python
This is because new operations from 2.3.0 are not available in the 2.1.0 version.
Can we get an updated TFLite interpreter in the short term?

**Comment by michaelzxu** [comment]
+1

Building from source is a huge inconvenience

**Comment by mhsmith** [comment]
https://www.tensorflow.org/lite/guide/python has now been updated to version 2.5.0.

**Comment by mhsmith** [comment]
Which is strange, because the main TensorFlow project hasn't even released version 2.4.0 yet.

**Comment by ivelin** [comment]
Awesome!

Is there an update on a plan to publish the wheels on pypi so that 
`pip3 install tflite` 
just works and there is no need to write conditional logic in install scripts that map OS and architecture to the correct tflite wheel URL?

**Comment by mihaimaruseac** [comment]
@mhsmith we update the version on master as soon as the branch is cut.

**Comment by abdenour759** [comment]
i can't find the whl version from armv6l https://github.com/google-coral/pycoral/releases/download/release-frogfish/tflite_runtime-2.5.0-cp37-cp37m-linux_armv6l.whl ..???

**Comment by terryheo** [comment]
FYI, this effort is under experimental.
As the result, tflite_runtime 2.7 is published at Pypi.
https://pypi.org/project/tflite-runtime
So you can use `pip install tflite-runtime` on some platform.

We can't host armv6l on Pypi since it only allows manylinux compatible wheels and `armv6l` isn't compatible with  manylinux2014. https://www.python.org/dev/peps/pep-0599/#the-manylinux2014-policy
But you can download it separately.

- https://storage.googleapis.com/tensorflow-release-public/prod/tensorflow/lite/release/rpi/release/5/20211118-210013/tflite_runtime-2.7.0/tflite_runtime-2.7.0-cp37-cp37m-linux_armv6l.whl
- https://storage.googleapis.com/tensorflow-release-public/prod/tensorflow/lite/release/rpi/release/5/20211118-210013/tflite_runtime-2.7.0/tflite_runtime-2.7.0-cp38-cp38-linux_armv6l.whl
- https://storage.googleapis.com/tensorflow-release-public/prod/tensorflow/lite/release/rpi/release/5/20211118-210013/tflite_runtime-2.7.0/tflite_runtime-2.7.0-cp39-cp39-linux_armv6l.whl

**Comment by ivelin** [comment]
> FYI, this effort is under experimental. As the result, tflite_runtime 2.7 is published at Pypi. https://pypi.org/project/tflite-runtime So you can use `pip install tflite-runtime` on some platform.
> 
> We can't host armv6l on Pypi since it only allows manylinux compatible wheels and `armv6l` isn't compatible with manylinux2014. https://www.python.org/dev/peps/pep-0599/#the-manylinux2014-policy But you can download it separately.
> 
> * https://storage.googleapis.com/tensorflow-release-public/prod/tensorflow/lite/release/rpi/release/5/20211118-210013/tflite_runtime-2.7.0/tflite_runtime-2.7.0-cp37-cp37m-linux_armv6l.whl
> * https://storage.googleapis.com/tensorflow-release-public/prod/tensorflow/lite/release/rpi/release/5/20211118-210013/tflite_runtime-2.7.0/tflite_runtime-2.7.0-cp38-cp38-linux_armv6l.whl
> * https://storage.googleapis.com/tensorflow-release-public/prod/tensorflow/lite/release/rpi/release/5/20211118-210013/tflite_runtime-2.7.0/tflite_runtime-2.7.0-cp39-cp39-linux_armv6l.whl

Very nice. Thank you for the update. Will give it a try.

**Comment by beasteers** [comment]
great to hear that tflite-runtime is on pypi! Is there a reason that builds are only provided for linux and not mac/windows? I'm still hoping for a simple cross-platform install process for tflite-runtime where you don't have to do platform detection to install requirements

**Comment by chunduriv** [comment]
@ivelin,

[`tflite_runtime 2.9.1`](https://pypi.org/project/tflite-runtime/) is published at Pypi. To know more about this package refer [`Tensorflow Lite runtime`](https://www.tensorflow.org/lite/guide/python).

Please feel free to move this issue to close status. Thank you.
