### ISSUE TITLE
Can I use other Microcontrollers other than which are specified by tensorflow?

### ISSUE THREAD

**Issue by ms-ims** [tensorflow/tensorflow#38681]
Can other Microcontrollers can be used other than these mentioned below for tensorflow modules-
Arduino Nano 33 BLE Sense
SparkFun Edge
STM32F746 Discovery kit
Adafruit EdgeBadge
Adafruit TensorFlow Lite for Microcontrollers Kit 
Adafruit Circuit Playground Bluefruit
Espressif ESP32-DevKitC 
Espressif ESP-EYE 
If yes can. Is there any documentation to follow?

**Comment by ravikyram** [comment]
@ms-ims 

Can you please refer the [link](https://www.tensorflow.org/lite/microcontrollers) and see if it helps you.As per Tensorflow official documentation the TF modules supports the microcontrollers  as mentioned in the link. Thanks!

**Comment by ravikyram** [comment]
@ms-ims 
Any update on this issue please. Thanks!

**Comment by ms-ims** [comment]
I looked the link but tensorflow library is very supportive to Arm microcontroller I suppose.
I trying to run hello world program of tensorflow on my RX series board of renesas. I'm finding it difficult to build on that.

**Comment by mohantym** [comment]
Hi @ms-ims ! Have you checked these threads from Renseas? Link[ 1](https://www.renesas.com/us/en/document/apn/ra6t1-motor-failure-detection-example-tensorflow-lite-microcontroller-application-notes?language=en),[ 2](https://www.renesas.com/eu/en/blogs/embedded-artificial-intelligence-inference-renesas-rzg2) .Thanks!

**Comment by ms-ims** [comment]
Hi,

No I'm working on tensor flow now days.

**Comment by mohantym** [comment]
@ms-ims ! Above threads suggested usage of Tensorflow Lite on Renesas RA6T1 Motor Starter Kit.  Is this issue good to close then?

**Comment by ms-ims** [comment]
Yeah it can be closed

**Comment by mohantym** [comment]
Thank you confirming the same! Closing this issue as it seems to be resolved from above [comment](https://github.com/tensorflow/tensorflow/issues/38681#issuecomment-1004524327).

**Comment by ballsystemlord** [comment]
I subscribed to this thinking that we might get a link to some instructions for a pair of general boards with ESP32 and ARM MCUs.
But the issue was closed because we got instructions for a particular board, the RA6T1 motor controller board. This doesn't really say how to make tensorflow work on anything other than their board. It doesn't even list the step they took to get tensorflow working on their board -- other than that they used yocto (and they didn't even explain why they did that either).

Should I open a new issue to learn more?
