### ISSUE TITLE
gather nd op does not support string input

### ISSUE THREAD

**Issue by lizhen2017** [tensorflow/tensorflow#38780]
As the title.
Thanks for your help.

**Comment by Saduf2019** [comment]
@lizhen2017 
 please provide a code snippet to reproduce the issue reported here,Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

Make sure you also include the exact details if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by thaink** [comment]
@abattery,
Can you confirm this?

**Comment by abattery** [comment]
Hi lizhen2017,

Could you try the nightly build? In the nightly build, GatherNdOp supports string input tensors.

Best regards,
Jaesung

**Comment by Saduf2019** [comment]
@lizhen2017
please update as per above commenets
