### ISSUE TITLE
control_dependencies() maybe fails to mfence when an assign() with different shape occurs

### ISSUE THREAD

**Issue by smacke** [tensorflow/tensorflow#3886]
### Environment info
Operating System: OS X El Capitan

Installed CPU version (OSX pip package)
tensorflow version: 0.10.0rc0

### Steps to reproduce

Consider the following code snippet:

```python
x = tf.Variable(0.)
x_op = tf.assign(x, [1.], validate_shape=False)

with tf.control_dependencies([x_op]):
    plus_op = x+2

tf.initialize_variables([x]).run()
print plus_op.eval()
```

The expected output is `[3]`, but instead I get `2`

### What have you tried?

If we don't assign an inconsistent shape (e.g. assign `1` instead of `[1]`), then things work the way one would expect (output is `3`)

If we replace

`plus_op = x+2`

with

`plus_op=x.ref() + 2`

then we get the expected output of `[3]` instead of `2`.

I suspect this is because calling `ref()` may somehow trigger a memory fence which fixes the broken behavior.

Also, it is possible that this is the intended behavior and that I misunderstood control_dependencies(), in which case I apologize.

**Comment by yaroslavvb** [comment]
I can reproduce. That's kind of unexpected, `x+2` and `x.ref()+2` should work the same.

**Comment by prb12** [comment]
I believe this code is actually non-deterministic.  (at least I see **both** values if I run repeatedly)

If you look at the GraphDef using this code:
```
tf.train.write_graph(sess.graph.as_graph_def(),  '.',  'issue3886.pbtxt')
```
The Variable read of x is cached using an Identity op called `Variable/read`.  There is no control dependency between the cached read and the assign.  There **is** a control dependency on the Const input to the Add op. (@yuanbyu is the expert on why this is the case)

Here is the full GraphDef for reference:
```
node {
  name: "Variable/initial_value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "Variable"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "Variable/initial_value"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: true
    }
  }
}
node {
  name: "Variable/read"
  op: "Identity"
  input: "Variable"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  }
}
node {
  name: "Assign/value"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 1
          }
        }
        float_val: 1.0
      }
    }
  }
}
node {
  name: "Assign"
  op: "Assign"
  input: "Variable"
  input: "Assign/value"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }
  }
  attr {
    key: "use_locking"
    value {
      b: true
    }
  }
  attr {
    key: "validate_shape"
    value {
      b: false
    }
  }
}
node {
  name: "add/y"
  op: "Const"
  input: "^Assign"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 2.0
      }
    }
  }
}
node {
  name: "add"
  op: "Add"
  input: "Variable/read"
  input: "add/y"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
}
versions {
  producer: 9
}
```

**Comment by mrry** [comment]
This is intended behavior: variable reads are cached by default, and the implicitly created caching operator (a `tf.identity()`) is not ordered (by any control or data dependency) with the assignment operator. As a result, the caching operator can cache the value `0.` or `1.` depending on whether it runs before or after the `tf.assign()` operator.

There are several ways to avoid this:

1. As you noticed, you can use the `Variable.ref()` method to perform a non-caching read of the variable. This will ensure that it's read after the assignment, and you will always get the result `3`.
2. You can read the *result* of the assignment, which is itself a ref-tensor (l-value) representing the value of the tensor after the assignment. The following program always prints `3`:
 ```python
 x = tf.Variable(0.)
 x_op = tf.assign(x, [1.], validate_shape=False) 
 plus_op = x_op + 2

 tf.initialize_variables([x]).run()
 print plus_op.eval()
 ```
3. (Perhaps least intuitively.) You would always get the result `3` if you didn't change the shape of the variable in the assignment. The following program also always prints `3`:
 ```python
 x = tf.Variable(0.)
 x_op = tf.assign(x, 1.) 
 with tf.control_dependencies([x_op]) 
 plus_op = x + 2

 tf.initialize_variables([x]).run()
 print plus_op.eval()
 ```
 ...however this is an implementation detail (because the same buffer is used for `x` before and after the assignment, whereas when you change the shape a new buffer is allocated).

This is, admittedly, not the most intuitive semantics, but the caching tends to give the most efficient execution plan when running in a distributed setting with variables on a shared parameter server.
