### ISSUE TITLE
PR #34911 not being included in releases

### ISSUE THREAD

**Issue by ShaneSmiskol** [tensorflow/tensorflow#38883]
**System information**
- Have I written custom code (as opposed to using example directory):  Nope
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Windows 10 x64
- TensorFlow backend (yes / no):  Yes
- TensorFlow version:  2.1.0
- Keras version:  2.2.4-tf (using tf.keras)
- Python version:  3.7.5
- CUDA/cuDNN version:  11
- GPU model and memory:  1070 with 8GB

**Describe the current behavior**
In `site-packages/tensorflow_core/python/keras/utils/generic_utils.py`, the PR I made [here](https://github.com/tensorflow/tensorflow/pull/34911) on December 6, 2019 isn't being applied to PyPi releases of TensorFLow, specifically TF 2.1.0 in my case. The code in that file when cleanly installing TensorFlow is as follows:
```python
self._dynamic_display = ((hasattr(sys.stdout, 'isatty') and
                          sys.stdout.isatty()) or
                         'ipykernel' in sys.modules or
                         'posix' in sys.modules)
```

**Describe the expected behavior**
When it should be:
```python
self._dynamic_display = ((hasattr(sys.stdout, 'isatty') and
                          sys.stdout.isatty()) or
                         'ipykernel' in sys.modules or
                         'posix' in sys.modules or
                         'PYCHARM_HOSTED' in os.environ)
```
as changed in the PR. Is there some other place I need to create a PR for this change to take effect in the releases?

**Code to reproduce the issue**  
Install TensorFlow 2.1.0 on Windows 10, Python 3.7.5

**Comment by mihaimaruseac** [comment]
Hi.

Your PR (#34911) was merged into `master` on December 13th. However, the release branch for the 2.1 release (`r2.1`) has been cut on November 11th. Since there was no cherrypick of the commit, the change was not included in the 2.1 release. [Here](https://github.com/tensorflow/tensorflow/compare/r2.1) is a list of all commits included in the 2.1 release.

However, it will be surely included in the 2.2 release as it is already included in the release candidates. In fact, once it landed on master it will be included in all releases for all branches cut __after__ that date (unless it is being rolled back).

For the other releases, we can do a cherry-pick to `r1.15`, `r2.0` and `r2.1` (or a subset of them). I will merge the existing cherry-picks when we do a patch release to any of these versions, as long are they are still in the support window.

Do you want to make the cherry-picks, please?

**Comment by ymodak** [comment]
Thanks for the issue. Apologies for the inconvenience, the 2.1 branch cut had happened before merging this PR.  We can expect this change in TF 2.2 release.

**Comment by ShaneSmiskol** [comment]
Thanks for the response. Ah, I didn't know the 2.1 branch was created before the merge, but that makes sense now. Let me look into cherry picking with Git and I'll get back to you, never tried that before.

**Comment by ymodak** [comment]
Closing this now since TF 2.2 official has been released. Thanks!
