### ISSUE TITLE
tf.nn.depthwise_conv2d with rank=1 kernels (separable filters)

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#39050]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
nigthly
- Are you willing to contribute it (Yes/No):
no

**Describe the feature and the current behavior/state.**
There is a thread about twice calling DepWhiseConv2d TF ops when we have rank=1 kernels (separable filters) VS a single call to DepWhiseConv2d with 2d kernel.
I suppose that is would be hard to fuse on trace two DepWhiseConv2d on the separable filter.
So I was asking why with the current DepWhiseConv2d in TF doesn't handle the kernel rank=1 case with an parameter for down the stack compiler/transformations (kernel size, input size, device type, etc.).

**Will this change the current api? How?**
Yes
**Who will benefit with this feature?**
Separable filters (gaussian blur, etc)
**Any Other info.**
See https://github.com/tensorflow/addons/pull/1450#issuecomment-621351753 with follow-up @alextp and @rmlarsen comments.

**Comment by ghosalsattam** [comment]
@bhack @alextp  @rmlarsen  According to me this should be implemented in all other conv ops where this situation may arise like along wiith depthwise conv operation- Conv2D, Conv3D,...
(If at all implementation is needed)

**Comment by jpienaar** [comment]
Is the proposal here that DepthwiseConv2dNative (for different dimensions) has an additional attribute to say that is separable and in which case it gets a rank 1 kernel. And allows backends to decide whether they want to implement that as a single call with 2D kernel or 2 calls of DepthwiseConv2dNative with said rank 1 kernel? The rationale being that matching these two calls would be too difficult/fragile?

So it isn't a case where one would have

%5 = tf.SomeKernelGeneration()
%10 = DepthwiseConv2dNative(..., %5)
%20 = DepthwiseConv2dNative(%10 ..., %5)

and need to find cases where you have 1 dephtwise conv feeding into a next and they both share the same kernel, and if so one can convert to the other call form?

**Comment by bhack** [comment]
I think that the framework can analyze if the  kernel Is rank==1. 
Then down to the stack It can see if it wants to separate the kernel reasoning on different parameters (input size, kernel size, hardware factors etc..).

**Comment by bhack** [comment]
Any news on thi? We are adding a Gaussian filter again in Keras-cv:

https://github.com/keras-team/keras-cv/pull/143

**Comment by gadagashwini** [comment]
Hi @bhack, Are you looking similar feature [tfa.image.gaussian_filter2d](https://www.tensorflow.org/addons/api_docs/python/tfa/image/gaussian_filter2d) and [tfio.experimental.filter.gaussian](https://www.tensorflow.org/io/api_docs/python/tfio/experimental/filter/gaussian). Thank you!

**Comment by bhack** [comment]
No, I meant these kind of optimizations could be handled by XLA/MLIR

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
