### ISSUE TITLE
Ability to exclude columns from tf.data.experimental.CsvDataset

### ISSUE THREAD

**Issue by omatai** [tensorflow/tensorflow#39069]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):2.0
- Are you willing to contribute it (Yes/No): No (beginner level python skills)

**Describe the feature and the current behavior/state.**
There is an existing "select_cols" parameter; it would be useful to provide an "exclude_cols" parameter (possibly mutually exclusive) so that when you have 200+ columns in a CSV, but a small number of them are useful only to a human reader, you can exclude them from the dataset.

**Will this change the current api? How?**
It would only add an additional optional parameter

**Who will benefit with this feature?**
People wanting to train neural nets on CSVs full of multi-column data, e.g. to identify musical instruments from frequency spectrum

**Any Other info.**

**Comment by jsimsa** [comment]
This sounds useful. Marking as "contributions welcome".

**Comment by rachellim** [comment]
Hey @omatai - thanks for filing this issue. @stjohnso98 has started working on it in #39799 and we wanted to clarify what the expectations for this feature are.

On a CSV file with many columns, even if we had an `exclude_cols` parameter, a user would still have to know and specify the types of the included columns. For example, suppose we had a CSV file with 200 int32 columns and we knew we wanted to exclude columns 3 and 5, we could call this API as follows:

```
record_defaults = [tf.int32] * 198
dataset = tf.data.experimental.CsvDataset(files, record_default=record_defaults, exclude_cols=[3,5])
```

but this to me doesn't seem that useful on top of what already exists (`select_cols`), since a user still has to specify all the included columns in `record_defaults`, and one can easily derive `select_cols` as the complement of `exclude_cols` as follows:

```
exclude_cols_set = set(exclude_cols)
total_cols = len(record_defaults) + len(exclude_cols)
select_cols = [i for i in range(total_cols) if i not in exclude_cols_set]
```

My take is that this would make more sense in a context where the user doesn't have to specify the columns included at all (for example, `tf.data.experimental.make_csv_dataset` tries to infer the types and number of columns if it's not provided).

Just wanted to clarify what you think this feature should look like -- can you give some code examples of how you expect to call `exclude_cols`? Thanks!

**Comment by omatai** [comment]
Hi Rachel,

I am comparatively new to Tensorflow, and not a native speaker of python. But I have 30+ years experience in programming, mostly in C++.

What you have written – two lines to specify directly what I would have wanted – is perfect. It makes Tensorflow more accessible to those strong on data science, but weak on python skills.

If you had asked me how to produce a list of included columns from a list of excluded columns in python, I would have wasted at least 15-30 mins. In my experience, this happens far too regularly with Tensorflow – I have taken 8 weeks on and off trying to get a specific adaptation of a VGG network translated from TF1.4 to TF2.1, but what used to work fine in TF1.4 still fails to converge as a ground-up rewrite in TF2.1. Both have fewer than 150 lines of code in them. The TF2.1 code is simpler and clearer, but it just doesn’t work. In TF1.4 it works, but it’s completely unintelligible. It’s exasperating. The hard work of getting network training to converge should not be held back by interfaces that make it hard to fit the pieces together. IMHO, Tensorflow could be and should be no harder than Lego.

So please consider providing this feature EXACTLY as you have imagined it so that Tensorflow does not become the equivalent of an “English speakers only” exclusive club. Accessibility matters.

Thanks,
Paul.

**Comment by rachellim** [comment]
Thanks for the feedback - we'll go ahead and implement that.
