### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError: Cannot find TensorFlow native library for OS: windows, architecture: x86_64.

### ISSUE THREAD

**Issue by swzaaaaaaa** [tensorflow/tensorflow#39067]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):windows10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:1.14
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:9.2/7.6
- GPU model and memory:4G

**Describe the problem**
On windows10 systems, the call to the tensorflow-cpu version using Java runs successfully, but replacing libtensorflow_jni with libtensorflow_jni_gpu will report an error in Can't find dependent libraries?
cpu:successful
     maven:dependency
		libtensorflow and libtensorflow_jni
gpu:error
     maven:dependency
		libtensorflow and libtensorflow_jni-gpu
     Cannot find TensorFlow native library for OS: windows, architecture: x86_64. See https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java/README.md for possible solutions (such as building the library from source). Additional information on attempts to find the native library can be obtained by adding org.tensorflow.NativeLibrary.DEBUG=1 to the system properties of the JVM.         at org.tensorflow.NativeLibrary.load(NativeLibrary.java:77)         at org.tensorflow.TensorFlow.init(TensorFlow.java:66)         at org.tensorflow.TensorFlow.<clinit>(TensorFlow.java:70)         at org.tensorflow.Graph.<clinit>(Graph.java:479)         at HelloTensorFlow.main(HelloTensorFlow.java:8)
**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@swzaaaaaaa Looking at your system specification, I notice there is an incompatibility issue. `pip` binary that you used to install `TF1.14` was built using `CUDA 10` but you have `CUDA10.2`. When you run TF-cpu, it doesn't look for CUDA but when you run `TF-gpu` then it will looks for some CUDA libraries under `CUDA10.0` path but you have all the libraries under `cuda10.2` which is why it is throwing error.

Solution: Uninstall TF-->uninstall CUDA -->RESTART --> install CUDA 10 --> Install TF

Please check the [`Tested build configurations`](https://www.tensorflow.org/install/source_windows#gpu)


Version | Python version | Compiler | Build tools | cuDNN | CUDA
-- | -- | -- | -- | -- | --
tensorflow_gpu-1.14.0 | 3.5-3.7 | MSVC 2017 | Bazel 0.24.1-0.25.2 | 7.4 | 10


Please feel free to close this issue if this was resolved for you. Thanks!
