### ISSUE TITLE
Problem in importing Tensorflow: "ImportError: DLL load failed while importing"

### ISSUE THREAD

**Issue by samiravafa** [tensorflow/tensorflow#39096]
I have a problem in importing TensorFlow. My system is protected in ProgramData. So, I used the virtual environment and installed TensorFlow in my user environment. The TensorFlow is installed, but can not be imported. I checked other websites and related issues, but non of them solved my issue.

The versions of the python: Python 3.8.2
The version of TensorFlow:  1.13.1
The versions of the pip: pip 20.1
CPU: has avx instruction
Environment: virtual environment installed from "https://uoa-eresearch.github.io/eresearch-cookbook/recipe/2014/11/20/conda/"
Error: ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.
Failed to load the native TensorFlow runtime.
See https://www.tensorflow.org/install/errors
for some common reasons and solutions. Include the entire stack trace
above this error message when asking for help.

Thanks.

**Comment by oke-aditya** [comment]
This error occurs to many Users

This occurs because you may not have Visual C++ Redistributable for Windows. Please download it.
Also tensorflow has no support for Python 3.8 as of now.

Refer [here](https://www.tensorflow.org/install/pip#windows) to check if you have installed properly

Also, refer similar issues.
#36167 #36151 #36138 #36054 #36045 #36020 #36003 #35988 #35903 #35880 #35865 #35805 #35789 #35773 #35772 #35767 #35766 #35749 #35721 #35618 #35204
Thanks!

Please, check Your CPU/Python is on 32 bits?

Please, refer #36167 #38615 and see if it helps you.

Thanks!

**Comment by ravikyram** [comment]
@samiravafa 

Solution should be downloading and installing visual studio 2015-2019 x86 and x64 from here:https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads.Thanks!
