### ISSUE TITLE
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot serialize protocol buffer of type tensorflow.GraphDef as the serialized size (2643020353bytes) would be larger than the limit (2147483647 bytes)

### ISSUE THREAD

**Issue by dupeng2014** [tensorflow/tensorflow#39108]
tensorflow.python.framework.errors_impl.InvalidArgumentError: Cannot serialize protocol buffer of type tensorflow.GraphDef as the serialized size (2643020353bytes) would be larger than the limit (2147483647 bytes)

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
In order to expedite the trouble-shooting process, please provide a minimal standalone code to reproduce the issue reported here
Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thanks!

**Comment by mihaimaruseac** [comment]
Please fill in issue template and provide a minimal reproducer

Although, this error probably makes sense. To prevent DOS, we include some upper limits on the serialization. Without having a minimal reproducer, there's hardly a way to provide guidance around this
