### ISSUE TITLE
Adding Tab press for showing available methods and autocompletion for objects

### ISSUE THREAD

**Issue by pdubz-sudo** [tensorflow/tensorflow#39142]
**Describe the feature and the current behavior/state.**
Pressing the `tab` button does not show methods or autocomplete already defined objects when using Jupyter notebooks.

I tried this solution [https://stackoverflow.com/questions/54281719/how-to-get-code-completion-in-a-jupyter-notebook-running-in-docker](url). It didn't do anything when I tried it though.

`%config IPCompleter.greedy=True`

Example of how it works in Jupyter notebook when installed with conda.
```
import pandas as pd
pd.<tab_here>   # should show all availabe methods e.g. pd.read_csv(), pd.read_excel(), etc.
```

**System information**
I used the following below and the feature was missing. I don't know if it has been addressed or fixed in the new versions.
- TensorFlow Docker Image:  tensorflow/tensorflow:2.1.0-gpu-py3-jupyter
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- GPU model and memory: 1080Ti
- Are you willing to contribute it (Yes/No): No because I don't know how to implement it.

**Will this change the current api? How?**
I don't think so. It's just an add-on I think.

**Who will benefit with this feature?**
The showing of methods is a behavior that works when installing jupyter from conda and I would say is a standard feature in Jupyter notebooks. I've never seen anybody that couldn't hit tab and pull up methods or had autocomplete. It helps the user so they can see what options they have to call. This can save a massive amount of time and help the user be much more efficient.

**Comment by mohantym** [comment]
Hi @pdubz-sudo ! 
We see that you are using old version of Tensorflow which is officially considered as end of life, We recommend that you upgrade to 2.6 version and let us know if the issue still persists in newer versions .Please open a new issue in case you face any errors, we will get you the right help .Thanks!

**Comment by pdubz-sudo** [comment]
@mohantym Hey there! I tried the nightly build but the jupyter notebook didn't have the method list and autocomplete.

For example, doing `tf.__` and then hitting `tab` will have a drop down list of all the available methods which one can then choose from.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
