### ISSUE TITLE
Full screen camera needed for tensor flow pose estimation android

### ISSUE THREAD

**Issue by kittusster** [tensorflow/tensorflow#39211]
Provide full screen camera for pose estimation android

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by kittusster** [comment]
Android ,tensor flow latest version .need full screen camera for pose
estimation is issue

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!
