### ISSUE TITLE
Unnecessary tracing in tf.functions loaded from a saved model

### ISSUE THREAD

**Issue by saswatac** [tensorflow/tensorflow#39369]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Darwin-18.7.0-x86_64-i386-64bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.1.0
- Python version: Python 3.6.10
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

A custom keras model is saved using tf.saved_model.save and provided with a signature with None in the first dimension to allow for variable batch size. When the model is loaded back and used, it does tracing for each different batch size.

**Describe the expected behavior**

Since the model is saved with a signature, the expectation is that it should not perform tracing for different batch sizes.

The issue can be avoided by specifying the signature in the tf function instead of specifying it while saving the model, as shown in the linked gist.

**Standalone code to reproduce the issue**

The issue and the workaround can be seen in -

https://gist.github.com/saswatac/40aea67d71bbac021f7280e3a0cca419

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@saswatac 
I ran the code shared by you and face a different error, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/dbe66f9401e01f4109fb6e9c50841bb7/untitled172.ipynb), if possible please share a colab gist for us to analyse the error

**Comment by saswatac** [comment]
@Saduf2019 I was able to reproduce the my issue in the gist you shared. The issue you faced is probably due to installing tf 2.1.0 , i think you need to restart the kernel after installing 2.1.0 version. Alternatively you can also reproduce the issue with version 2.2.0-rc4, the default installed in colab.

**Comment by Saduf2019** [comment]
@saswatac 
I ran the shared code again and do not face any error, it replicated the issue reported by you, please confirm the same as per the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/dfa6d64d7848cf8edc904a72639dd344/untitled176.ipynb)

**Comment by saswatac** [comment]
@Saduf2019 yes looks good.

**Comment by dellis23** [comment]
Thanks for reporting.  After looking into this, I don't believe there's a bug, though I do believe we could improve the documentation around signatures.  I have a PR out for clarifying this.

The function returned from `get_concrete_function` that you're passing to the `signatures` argument of `save` isn't doing anything special to the function itself; it's simply exposing that concrete function in the signatures dictionary at load time.

For example, after loading your model, since you didn't pick a specific name for the signature, it could be called via:

```
loaded.signatures['serving_default'](inputs=tf.ones((2, 2)))
```

This isn't all that useful in TensorFlow 2 in Python, but it does allow you to access these functions in the graph-based v1 and C++.  There isn't any additional magic that modifies your original function when you set things up this way.  From the point of view of the original function, you've simply created another concrete function and can do whatever you wish with it.

To further illustrate the problem / interaction, consider this: when defining a function, we support a single optional signature.  Attempts to request a function that don't fit this signature will throw an error. Example:

```
@tf.function(input_signature=[tf.TensorSpec(shape=[None, 2], dtype=tf.float32])
def foo(arg1):
  return tf.multiply(0.5, arg1)

foo.get_concrete_function(tf.ones((3, 3, 3)))
```

This will throw an exception, since the concrete function you're requesting isn't valid with the input signature you provided.  If we were to attempt to retroactively enforce a signature at export time, we may find concrete functions whose inputs are incompatible with the signature.  Trying to work around this would probably only make an already-confusing interface even more so.

More broadly, it might be possible to add support for multiple input signatures, but this is not something we have on the roadmap for supporting at this time, and regardless, the behavior of automatically adding additional ones when a concrete function is requested would seemingly violate the purpose of creating a specific input signature in the first place.

Hope this makes sense.
