### ISSUE TITLE
tf.add_check_numerics_ops() causes numeric errors for gradients of tf.pow

### ISSUE THREAD

**Issue by thjashin** [tensorflow/tensorflow#3937]
### Environment info
Operating System: Ubuntu 16.04

Installed version of CUDA and cuDNN: None
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. Which pip package you installed.
[`https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl`](https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp27-none-linux_x86_64.whl)
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.
`0.10.0rc0`

### Steps to reproduce
```python
import tensorflow as tf
x = tf.Variable(0.)
x_grad = tf.gradients(x**2, x)
init = tf.initialize_all_variables()
check_op = tf.add_check_numerics_ops()
sess = tf.InteractiveSession()
sess.run(init)
sess.run(x_grad + [check_op])
# => InvalidArgumentError: gradients/pow_grad/Log:0 : Tensor had Inf values
sess.run(x_grad)
# => [0.0]
```

My guess is that the check_op forces the two factors in `grad(x**2) = (e**(2log x)) * (1./x)` to separately evaluate. Then 1./x causes an `Inf`.

**Comment by yaroslavvb** [comment]
That's normal functionality of check_gradient -- you run it on a code which
shouldn't have any NaN or inf values, and it fails with
IllegalArgumentError on the first inf/nan it finds.

However, having NaN or Inf in your computation isn't necessarily a problem.
You can divide by inf to get 0, or you can add extra logic to replace it
with regular value.

Below is implementation of Pow grad
(tensorflow/python/ops/math_grad.py#L544). You can see it'll computes Log
of 0, but there's a "where" clause which replaces negative infinities with
0's so they don't break the result

  # Avoid false singularity at x = 0
  log_x = math_ops.select(x > 0, math_ops.log(x), array_ops.zeros_like(x))

**Comment by thjashin** [comment]
Thanks for explanation. Yep. But this makes it hard for someone who uses tf.pow in their code but still want to find out other NaNs, right? And it also feels a little uncomfortable to have different behaviors between tf.pow (y=2) and tf.square when using check_op.

**Comment by prb12** [comment]
It's always possible to manually insert individual check_numerics ops - and probably more sensible to insert them in strategic places when debugging rather than everywhere.  I think it is unlikely that this behavior is going to be changed.

**Comment by rasmusbergpalm** [comment]
I strongly disagree with the sentiment here. 

This is how I've spent ~6 hours before I found this issue

* Run big hairy model for a couple of hours, everything is fine. 
* Suddenly, NaNs everywhere.
* Google tensorflow debug nan. Tells me to insert `add_check_numerics_ops`. Great! Then I can at least know which tensor first get's the NaNs.
* Run model again. Immediately get NaN warning `gradients/pow_grad/Log:0`. Spend hours debugging where that tensor comes from.
* Track it down to a MSE calculation. 
* Check all inputs for NaNs.
* Find this issue :/

`add_check_numerics_ops` is basically useless due to this issue, which brings me right back to my original issue: how do i debug NaNs in the code?

Do i have to add individual check_numeric_ops to every single operation (except pow because it's broken). That cannot seriously be the answer.

**Comment by yaroslavvb** [comment]
btw there's also dedicated `tf.square(x)` op. Another problem with `add_check_numerics` is that ops created by optimizers are not checked https://github.com/tensorflow/tensorflow/issues/2288

**Comment by yaroslavvb** [comment]
@rasmusbergpalm the reason you are seeing this error is because gradient is because of how gradient of `pow` is implemented in [math_grad.py](https://github.com/tensorflow/tensorflow/blob/64edd34ce69b4a8033af5d217cb8894105297d8a/tensorflow/python/ops/math_grad.py#L686)

There's this line

`log_x = array_ops.where(x > 0, math_ops.log(x), array_ops.zeros_like(x))`

So what happens is that `check_numerics` adds a a numeric check to both branches, so there's an infinity produced during evaluation of your graph, but presumably you don't care about it because it doesn't affect your result.

Not sure there's an easy general solution here -- both branches of select are evaluated here, so if there are side-effects, then then this infinity may make its way into final result. IE, you could have control dependencies or something like this.

`log_x = array_ops.where(x > 0, y.assign(math_ops.log(x)), z.assign(array_ops.zeros_like(x)))`

In this case the one branch's value is assigned to `log_x`, but the second branch is still evaluated, so z is updated and infinity there could make its way into final result.

Perhaps the way to fix it would be to have a fused implementation of gradient of power operation

**Comment by rasmusbergpalm** [comment]
Thanks for the explanation @yaroslavvb 

I think I understand why this is happening. I still think it's pretty bad, regardless of why it is so.

Unfortunately, I don't have any opinion on how to fix it, as I'm not familiar with the TF source code.

**Comment by prb12** [comment]
It's pretty hard to come up with a generic 'magically debug my big hairy numeric algorithm' solution when internally code is written to produce and mask numeric errors.  It's even harder to do this without destroying performance on GPU.

At one point in distant history, I remember reading the code of an inception model which only added explicit CheckNumerics ops just before writing gradients back to the model variables (hence preventing state corruption).   

If somebody has spare time on their hands, here is what I would do:
a) Change the `ApplyGradients` method of the `Optimizer` class to add `CheckNumerics` ops.
b) Wrap training steps in an exception handler which catches any NaN exceptions, and uses the model checkpoint code to write the equivalent of a 'core dump'. 
c) Use the TF debugger code, partial evaluation or just explicit feed/fetch to reload the checkpoint and then repeatedly execute the step to examine the values of (all) intermediate tensors in the graph.

This technique relies on deterministic execution, so wouldn't work if there were Queues or any other stateful ops in the graph, and would rely on feeding the same training data.

**Comment by mjlm** [comment]
I also just spent hours on this. I solved it by replacing x**2.0 by tf.square(x).

**Comment by burnpanck** [comment]
Just a +me-too here. The great thing with `tf.add_check_numerics` is that it allows one to relatively quickly identify where NaNs and Infs appear first, which is usually the place one is most interested in. However, this assumption fails for graphs, where NaN's and Infs a are expected and later explicitly handled, such as in the implementation of `tf.pow`. The problem is, as soon as I have one such case in my graph, I cannot use the great `tf.add_check_numerics` anymore, even when it would be perfectly fine for the 99 % remainder of the graph.
The "perfect" generic "magicaly debug my big hairy numeric algorithm" solution would probably require something like a "non-signalling" assert, i.e. an exception that propagates through the graph and only is reported if it makes it to the end; exactly like fp non-signalling NaNs and Infs, but with the additional traceback/debugging information being pulled along, in order to still be able to identify the source. Unfortunately, that would be very difficult to implement.
One workaround that would at least allow me to continue to use `tf.add_check_numerics` would be a way to explicitly silence/remove those checks from operations that I have explicitly identified as being unproblematic. Is there a way to accomplish this?
In any case, a warning in the documentation of `tf.add_check_numerics` (ideally with a list of well known operations with this problem) would probably save many people hours of debugging such issues. Of course, a fused implementation of the gradient of pow would avoid this particular case, as would an optimiser identifying and replacing the very common case of  `x**2`.

**Comment by burnpanck** [comment]
One year later and none the wiser... I again spent hours debugging a big hairy numeric algorithm with NaNs, this time apparently with `tf.metrics.accuracy` (I did verify/assert that all dimensions are positive)? Any news on how to more effectively debug NaNs? `add_check_numerics` is just useless this way, but would be very useful if there was a way for selectively silencing certain sub-trees. Unfortunately, most other debugging help one finds on google is either outdated or doesn't work for my case: Training an `Estimator` from an IPython Notebook. `tfdbg` doesn't help here either...
