### ISSUE TITLE
Problematic image loading with `image_dataset_from_directory`

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#39373]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.2.0-dev20200508
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
When using `image_dataset_from_directory` to load images it drops the color of the images significantly as can be seen below:

![image](https://user-images.githubusercontent.com/22957388/81499518-d4982f00-92e9-11ea-9f0c-7a188bdf1fe1.png)

**Describe the expected behavior**

The color drop should not be there.

**Standalone code to reproduce the issue**
Colab Gist: https://colab.research.google.com/gist/sayakpaul/f4c686a65ec88fa9bb0e62f4bc32004d/scratchpad.ipynb.

**Comment by Saduf2019** [comment]
@sayakpaul 
i am able to replicate this issue, please find the [gist here for nightly](https://colab.sandbox.google.com/gist/Saduf2019/cda059b126a6a616e0d38b06ffc767a0/untitled172.ipynb)
i ran the code on tf 2.1 and the results are better, please find the [gist here](https://colab.sandbox.google.com/gist/Saduf2019/bb44ff0c0a8f26cefb8208e30552f04b/untitled172.ipynb) and let us know if that helps.

**Comment by sayakpaul** [comment]
The results are not better I think as the image quality should not be degraded to this level. @fchollet could you confirm?

**Comment by sayakpaul** [comment]
@fchollet have you experienced anything like this?

**Comment by jvishnuvardhan** [comment]
@sayakpaul The warning clearly points to the root-cause of the issue.

```
show_batch(image_batch.numpy(), label_batch.numpy(), image_data_gen=False) 

# the above line throws a warning as shown below
Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers
```
As the `image_batch` is of `float32`, we need to pass values between 0 and 1. However, the values are between 0 and 255. As mentioned in the warning, it clips values between 0 and 1 and pass the data, which is why the images are not good.

So, if you divide the `image_batch` array by 255. then the images are good. Please take a look at the gist [here](https://colab.research.google.com/gist/jvishnuvardhan/f7281d40804697ef0aa56b0e31798a26/scratchpad.ipynb) for your reference.

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by sayakpaul** [comment]
Fair enough. Thank you :)
