### ISSUE TITLE
Very slow compared to my PC

### ISSUE THREAD

**Issue by rajkr476** [tensorflow/tensorflow#39385]
![Screenshot (3)](https://user-images.githubusercontent.com/39881819/81509318-5490ba00-9327-11ea-990f-d35c11b67c3d.png)

Google Colaboratory notebook training speed(On GPU) is very slow compare to my PC.
Specs:- Windows 10
            GPU - Nvidia Geforce GTX 950M
            CUDA - v10.1
            CUDNN - v7.6
Per Epoch Training time on my PC(GPU) - 5-6 minutes
Per Epoch Training time on Google Colaboratory(GPU)- More than 3 hr
I am using mounted drive for providing the dataset.

please provide me a solution so i can train my model faster.

**Comment by Saduf2019** [comment]
@rajkr476  
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here.
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. 

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by rajkr476** [comment]
![Screenshot (4)](https://user-images.githubusercontent.com/39881819/81647316-733ba180-944a-11ea-8c93-3eecd18fcf6a.png)
OS - Windows 10
Anaconda Navigator
Tensorflow Version - 2.1.0

**Comment by rajkr476** [comment]
![Screenshot (5)](https://user-images.githubusercontent.com/39881819/81706173-7c019700-948d-11ea-8767-9078915e0711.png)
![Screenshot (6)](https://user-images.githubusercontent.com/39881819/81706204-80c64b00-948d-11ea-8250-c41d40d9f390.png)

I have also getting these UserWarning.

**Comment by ymodak** [comment]
Please provide a github gist or use proper markdown formatting. Screenshot attachments paint the picture but does very little to repro the issue at our end. Thank you.
