### ISSUE TITLE
Why tf.contrib.distribute.OneDeviceStrategy is used, the Variable is defined as ResourceVariable?

### ISSUE THREAD

**Issue by venuswu** [tensorflow/tensorflow#39445]
I used tf 1.14. Here is the code.

```
distribution = tf.contrib.distribute.OneDeviceStrategy("device:CPU:0")
run_config = tf.estimator.RunConfig(
      session_config = config,
      model_dir=FLAGS.output_dir,
      train_distribute=distribution,
      save_checkpoints_steps=FLAGS.save_checkpoints_steps,
     )
```

I found that when the OneDeviceStrategy is used, the variable was defined as ResourceVariable. But when this strategy is deleted, the variable was defined as VariableV2. Why chould this happend, it is said in the official document, that when use_resource or eager mode is enabled, the variable is defined as resource variable.

**Comment by ravikyram** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the code snippet to reproduce the issue. If you are unclear what to include see the issue template displayed in the [Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
