### ISSUE TITLE
Lite benchmark reports inconsistent runtime on raspberry pi 4

### ISSUE THREAD

**Issue by luyuan2015** [tensorflow/tensorflow#39488]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Raspbian 10
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 2.1.0
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Raspberry Pi 4

**Describe the problem**

We compiled lite/tools/benchmark/benchmark_model using bazel build on Pi4. And use it to profile a tflite network (attached: 0.tflite). The reported runtime is **~2.3sec** (0.log). However, when we run the same tflite network using an explicit call (tflite_test.py), it only reports **~270ms** runtime. Why?

For the same model, we have tried it on an Ubuntu 18.04 workstation. Both reports consistent runtime.

Note that you need to rename the file suffix in order to run them.

**Please provide the exact sequence of commands/steps when you ran into the problem**
% bazel --version
bazel 2.1.0- (@non-git)
% bazel build --linkopt=-latomic -c opt tensorflow/lite/tools/benchmark:benchmark_model
% ~/NAS/tensorflow/bazel-bin/tensorflow/lite/tools/benchmark/benchmark_model --graph=./0.tflite --enable_op_profiling=true --num_runs=10 > 0.log
% python tflite_test.py -m 0.tflite -n 10
Iteration 10 Time: 0:00:02.724248                          # 2.7s/10 = 270ms

[0.log](https://github.com/tensorflow/tensorflow/files/4620249/0.log)
[tflite_test.py.txt](https://github.com/tensorflow/tensorflow/files/4620251/tflite_test.py.txt)
[0.tflite.txt](https://github.com/tensorflow/tensorflow/files/4620253/0.tflite.txt)

**Comment by daverim** [comment]
Hi luyuan2015, these should be relatively close.

It sounds like you have a mismatch between the benchmark and interpreter used in Python. How did you install Tensorflow in Python? What version are you using?

Please try building tflite benchmark using the following guide:
https://www.tensorflow.org/lite/guide/build_rpi

Use build_aarch64_lib.sh instead of build_rpi_lib.sh for raspberry pi 4 if you are using a 64-bit os.
The guide will result in the benchmark binary being built along with the tflite library.

**Comment by luyuan2015** [comment]
Hi Daverim,

Thank you very much for your help. Cross compilation works for me. I was able to compile benchmark_model with your suggestion and get correct result. Many thanks for your help.
