### ISSUE TITLE
Can tfdbg support dumping tensor inside the function？

### ISSUE THREAD

**Issue by september-boy1** [tensorflow/tensorflow#39491]
I am using tf 1.15. 
I write a script containing if operator and function.
I use tfdbg to dump the tensor.
when I user "lt" command to list all tensors, I can't see the tensors inside the function.
Is it possible to dump tensors inside the function?

**Comment by amahendrakar** [comment]
@september-boy1,
If this issue is related to a TensorFlow bug, could you please provide the complete code to reproduce the issue.

If not, I'd suggest you to post this query on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow). There is also a larger community that reads questions there. Thanks!
