### ISSUE TITLE
Is tf.distribute.Strategy API use multi-processing？

### ISSUE THREAD

**Issue by COthello** [tensorflow/tensorflow#39512]
As python has GIL when use multi threading, so  tf.distribute.Strategy is using multi-processing or multi-threading?

**Comment by ckkuang** [comment]
Good question. Since you mention multi threading, I would assume you are probably talking about MirroredStrategy which can run on multiple GPUs? If that's the case, the answer is two folded:
1. If you are using purely eager execution, currently the implementation is not optimized and effectively there is no parallelism. I believe you will get a warning about the performance. This mode is only recommended for debugging / developing purpose.
2. More often you should use Keras compile/fit ([example](https://www.tensorflow.org/tutorials/distribute/keras)) or custom training loops with tf.function ([example](https://www.tensorflow.org/tutorials/distribute/custom_training)), in this mode your python code is just constructing the computation graph and the real heavy lifting is done in TensorFlow runtime (C++), which uses C++ multi-threading so python GIL doesn't come into play.

**Comment by Jianbing-D** [comment]
Hi @ckkuang, I tried with `python pdb` to find out where multiple-threading is used to execute the wrapped python functions undef `tf.distribute.MirroredStrategy`, but got lost in `tensors = pywrap_tfe.TFE_Py_Execute(...)`. And I don't see any python multi-threading is used.

```python
@tf.function
def _train_step(inputs):
    return tf.identity(inputs)

strategy = tf.distribute.MirroredStrategy()
print(strategy.run(_train_step, args=(tf.constant(1.0))))
```

Could you please point out how TF launched the python functions for multiple GPU devices with multiple CPU threads?

**Comment by ckkuang** [comment]
It doesn't use python multi-threading. The wrapped function is compiled into a TensorFlow graph, which will be eventually executed by TF graph [executor](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/executor.h#L51). The graph executor uses two bounded thread pools: one for running multiple ops concurrently (called intra-op threadpool), and the other for parallelizing individual ops (called inter-op threadpool).

In the example you posted, the graph contains N (N equals to #GPUs) identity nodes and each node is assigned to one GPU. At runtime the N nodes run concurrently using threads in the intra-op threadpool. By default the number of threads in that pool equals to the your CPU cores.

For GPU devices there are three [modes](https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/common_runtime/gpu/gpu_device.cc#L485-L496):
  * global: GPU uses threads shared with CPU in the intra-op thread-pool. This is currently the default.
  * gpu_private: GPU uses threads dedicated to this device. This usually saves setting up thread context for enqueuing GPU kernels, and can sometimes improve performance (see [link](https://www.tensorflow.org/guide/gpu_performance_analysis)).
  * gpu_shared: All GPUs share a dedicated thread pool.

Note that CPU thread launching GPU computations is not blocking - it just enqueues the GPU kernel to a compute stream.
