### ISSUE TITLE
[feature request] - please consider adding in gpumlib features to tensorflow

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#39537]
**[feature request] - please consider adding in gpumlib features to tensorflow**

# Greetings

**I would like to point out to:**
- *incorporalting gpumlib features in tensorflow.*

**motivations for the assessment:**
- *gpumlib contains some interesting algorithms, that could perfectly enhance some features of tensorflow.*

**the source code for the framework can be found at:**
- *http://gpumlib.sourceforge.net/*

**Comment by sanjoy** [comment]
Hi @jakob82 ,

> gpumlib contains some interesting algorithms, that could perfectly enhance some features of tensorflow.

Can you please be more specific?

The TensorFlow team does not have cycles to look into this at the moment.  However, please feel free to post [an RFC](https://github.com/tensorflow/community/blob/master/governance/TF-RFCs.md) with more details if you want to take this on.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
