### ISSUE TITLE
TensorFlow Hub hosted Mv1/Mv2 fails execution in tflite runtime

### ISSUE THREAD

**Issue by vinodganesan** [tensorflow/tensorflow#39552]
The mv1 and mv2 quantized models hosted here 
(mv1-224 0.25,0.5,0.75,1.0 and mv2-224)
(https://www.tensorflow.org/lite/guide/hosted_models) fails execution on the tflite runtime on my custom app modified from TensorFlow's demo app, running on a Google Pixel 3a mobile. 

The error was,
java.lang.IllegalArgumentException: Cannot convert between a TensorFlowLite buffer with 150528 bytes and a Java Buffer with 602112 bytes.

It seems like there's an int8 vs float32 mismatch somewhere. However, if I manually take an mv2 and use the TFLite Converter (with quantization flag) to convert to a quantized model, it runs perfectly (both the models have the same size (hosted vs converted) hence ruling any issues of Converter not quantizing the model).

Can you please let me know why the hosted model could be erring out?

**Comment by vinodganesan** [comment]
Also, I am unable to generate/convert models for Mv3-224 (small and large) and the existing model fails similarly. 

However, the hosted Mnas models work perfectly well

**Comment by jvishnuvardhan** [comment]
@vinodganesan Can you please explain what you meant by the following? Give us more details on what you have done taking the hosted models.
> The mv1 and mv2 quantized models hosted here
(mv1-224 0.25,0.5,0.75,1.0 and mv2-224)
(https://www.tensorflow.org/lite/guide/hosted_models) fails execution on the tflite runtime on my custom app modified from TensorFlow's demo app, running on a Google Pixel 3a mobile.

My questions are
1. from the hosted models, did you download saved model or tflite quantized model?
2. which model you ported into mobile? What are the steps you followed?
3. what do you mean by "Also, I am unable to generate/convert (to tflite) models for Mv3-224 (small and large) and the existing model fails similarly."

Let's take one at a time and understand the issue so that we can resolve faster. Thanks!

**Comment by vinodganesan** [comment]
Hi, 

Please find my answer to your queries below

1. I downloaded the tflite quantized model, 
2. I ported Mobilenet_V1_1.0_224_quant and Mobilenet_V2_1.0_224_quant, using an app modified from the existing tensorflow demo app.. It more or less uses the steps mentioned in this link (https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/)

3. For Mv3, I took the tflite quantized model provided in https://github.com/tensorflow/models/tree/master/research/slim/nets/mobilenet and tried running it, it failed too. 

However, if I take the float models provided and use TFLiteConverter with OPTIMIZE_FOR_SIZE flag, I get a quantized model with similar size as of that of hosted. However, I was successfully able to run these quantized models that I converted on the app. 

Let me know if that clarifies. 

Thanks,
Vinod

**Comment by jvishnuvardhan** [comment]
@vinodganesan Can you please create a standalone code to reproduce the issue? what are the sizes of your model (that you converted) and the hosted model? Are they both full integer quantization or float quantization models? Thanks!
