### ISSUE TITLE
Suggest to the user to define a cache volume for bazel

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#39560]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/install/source#docker_linux_builds

## Description of issue (what needs changing):
We the current info about Docker build from source we will lost the cache when we destroy the container
### Clear description
The bazel cache will be stored in `/root/.cache/bazel/` that it is ephemeral and so it will lost if the container it is removed. So you are going to lost hours of builds just if you will restart the image with a new container. You need to suggest to mount an host volume for the bazel cache.

For example, why should someone use this method? How is it useful?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
