### ISSUE TITLE
Pixel range issue with `image_dataset_from_directory` after applying `convert_image_dtype`

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#39595]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes. 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.3.0-dev20200514
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

After creating a dataset with `image_dataset_from_directory` I am mapping it to `tf.image.convert_image_dtype` for scaling the pixel values to the range of [0, 1] and also to convert them to `tf.float32` data-type. Looks like the value range is not getting changed. 

Here's the self-contained code:

```python
import matplotlib.pyplot as plt
import tensorflow as tf

# Get the flowers dataset
flowers = tf.keras.utils.get_file(
    'flower_photos',
    'https://storage.googleapis.com/download.tensorflow.org/example_images/flower_photos.tgz',
    untar=True)

def scale(image, label):
    return tf.image.convert_image_dtype(image, tf.float32), label

batch = tf.keras.preprocessing.image_dataset_from_directory(flowers)
batch = batch.map(scale)

image_batch, label_batch = next(iter(batch))

print(tf.reduce_max(image_batch[1,:])) # outputs: tf.Tensor(248.96571, shape=(), dtype=float32)
print(image_batch.dtype) # outputs: <dtype: 'float32'>
```

**Describe the expected behavior**

If my understanding is correct, then `batch = batch.map(scale)` should already take care of the scaling step. 

**Standalone code to reproduce the issue**

[Colab Gist](https://colab.research.google.com/gist/sayakpaul/831f2a584f92cdcc97f81bf0eb344ad1/scratchpad.ipynb)

**Comment by sayakpaul** [comment]
@jvishnuvardhan

**Comment by ravikyram** [comment]
I have tried in colab with TF nIghtly version (`2.3.0-dev20200516`) and was able to reproduce the issue.Please, find the gist [here](https://colab.sandbox.google.com/gist/ravikyram/9d665bc0d9e4cfaea247e310eed3a8e8/untitled897.ipynb).Thanks!

**Comment by AkshayRoyal** [comment]
`tf.image.convert_image_dtype` expects the image to be between 0,1 if the type is float which is your case. 
I am attaching the excerpt from the [link](https://www.tensorflow.org/api_docs/python/tf/image/convert_image_dtype)
**Images that are represented using floating point values are expected to have values in the range [0,1). Image data stored in integer data types are expected to have values in the range [0,MAX], where MAX is the largest positive representable number for the data type.**

Now coming back to your issue. Since `image_dataset_from_directory` does not provide rescaling option either you can use `ImageDataGenerator` which provides rescaling option and then convert it to `tf.data.Dataset` object using `tf.data.Dataset.from_generator` or process the output from `image_dataset_from_directory` as follows:
```
from tensorflow.keras.layers.experimental.preprocessing import Rescaling
dataset = image_dataset_from_directory(directory)
rescale = Rescaling(scale=1.0/255)
rescaled_dataset = dataset.map(lambda image,label:(rescale(image),label))
```
In your case map your `batch` with this `rescale` layer. Also check the documentation for Rescaling [here](https://www.tensorflow.org/api_docs/python/tf/keras/layers/experimental/preprocessing/Rescaling)

**Comment by sayakpaul** [comment]
Makes sense, thank you. I am aware of the other options you suggested. I am gonna close this issue.
