### ISSUE TITLE
Faulty error message: "InternalError: Failed copying input tensor from" on tf.concat

### ISSUE THREAD

**Issue by rani-pinchuk** [tensorflow/tensorflow#39668]
The following code:
```python
import tensorflow as tf
print(tf.version.GIT_VERSION, tf.version.VERSION)
 
t1 = tf.constant([])
print(t1)
t2 = tf.constant(["hello", "world"])
print(t2)
t3 = tf.concat([t1, t2], axis=0)
print(t3)
``` 
Gives the following on my installation:
```
v2.2.0-rc4-8-g2b96f3662b 2.2.0
tf.Tensor([], shape=(0,), dtype=float32)
tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)
---------------------------------------------------------------------------
InternalError                             Traceback (most recent call last)
~/omp/m5/plots_server.py in <module>
      6 t2 = tf.constant(["hello", "world"])
      7 print(t2)
----> 8 t3 = tf.concat([t1, t2], axis=0)
      9 print(t3)

/usr/local/lib/python3.6/dist-packages/tensorflow/python/util/dispatch.py in wrapper(*args, **kwargs)
    178     """Call target, and fall back on dispatchers if there is a TypeError."""
    179     try:
--> 180       return target(*args, **kwargs)
    181     except (TypeError, ValueError):
    182       # Note: convert_to_eager_tensor currently raises a ValueError, not a

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/array_ops.py in concat(values, axis, name)
   1604           dtype=dtypes.int32).get_shape().assert_has_rank(0)
   1605       return identity(values[0], name=name)
-> 1606   return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
   1607 
   1608 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/gen_array_ops.py in concat_v2(values, axis, name)
   1179         pass  # Add nodes to the TensorFlow graph.
   1180     except _core._NotOkStatusException as e:
-> 1181       _ops.raise_from_not_ok_status(e, name)
   1182   # Add nodes to the TensorFlow graph.
   1183   if not isinstance(values, (list, tuple)):

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/ops.py in raise_from_not_ok_status(e, name)
   6651   message = e.message + (" name: " + name if name is not None else "")
   6652   # pylint: disable=protected-access
-> 6653   six.raise_from(core._status_to_exception(e.code, message), None)
   6654   # pylint: enable=protected-access
   6655 

/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run ConcatV2: Can't copy Tensor with type string to device /job:localhost/replica:0/task:0/device:GPU:0. [Op:ConcatV2] name: concat
```
On collab I get the correct output:
```
v2.2.0-0-g2b96f3662b 2.2.0
tf.Tensor([], shape=(0,), dtype=float32)
tf.Tensor([b'hello' b'world'], shape=(2,), dtype=string)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-17-fcff1beaaddc> in <module>()
      6 t2 = tf.constant(["hello", "world"])
      7 print(t2)
----> 8 t3 = tf.concat([t1, t2], axis=0)
      9 print(t3)

4 frames
/usr/local/lib/python3.6/dist-packages/six.py in raise_from(value, from_value)

InvalidArgumentError: cannot compute ConcatV2 as input #1(zero-based) was expected to be a float tensor but is a string tensor [Op:ConcatV2] name: concat
```

**System information**
 ```
lsb_release -a 
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```
Tensorflow installed - a docker container:
```
FROM tensorflow/tensorflow:2.2.0-gpu-jupyter
...
```
CPU: Intel(R) Xeon(R) CPU D-1518 @ 2.20GHz
GPU:  NVIDIA Corporation GP104 [GeForce GTX 1070 Ti] (rev a1)

The code is obviously incorrect, but the seem-to-be faulty error message makes it very difficult to spot the problem.

**Comment by amahendrakar** [comment]
@rani-pinchuk,
The difference in the error log is due to the TensorFlow version. 

On running the code with [TensorFlow CPU](https://colab.research.google.com/gist/amahendrakar/500f35afe24c6e913761de3b6713cff5/39668-2-2.ipynb) the error is `InvalidArgumentError: cannot compute ConcatV2 as input #1(zero-based) was expected to be a float tensor but is a string tensor [Op:ConcatV2] name: concat`

Whereas on running the code with [TensorFlow GPU](https://colab.research.google.com/gist/amahendrakar/693da38e1d229c34154514f4769dc216/39668-2-2-gpu.ipynb#scrollTo=B0kwwUbXwzDU) the error is `InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:GPU:0 in order to run ConcatV2: Can't copy Tensor with type string to device /job:localhost/replica:0/task:0/device:GPU:0. [Op:ConcatV2] name: concat`.

Please check the linked Colab gist for the complete code. Thanks!

**Comment by rani-pinchuk** [comment]
Thanks @amahendrakar. I see that if I run this with CPU I get a different error from the one I get when running it with GPU (on the same version v2.2.0-0-g2b96f3662b 2.2.0). So it seems that the difference in versions in my original entry is irrelevant. 
I wonder if this difference in the error messages between CPU and GPU is documented somewhere.

**Comment by yongtang** [comment]
@rani-pinchuk While the error messages seem to be different, looks like it does makes sense:
1. On CPU, the error happens when Concat op happens where you cannot concat two different dtype tensors.
2. On GPU, before Concat happens, data has to be transferred to GPU first. And the error happens here because string data is not supported on GPU.

**Comment by rani-pinchuk** [comment]
@yongtang Thanks for the explanation. This is clear now.
