### ISSUE TITLE
TF 2.2.0 ptxas issue

### ISSUE THREAD

**Issue by FMalerba** [tensorflow/tensorflow#39716]
Running in linux some code I get the following warning:

`You are using ptxas 8.x, but TF requires ptxas 9.x (and strongly prefers >= 9.2.88).  Compilation of XLA kernels below will likely fail.`

However when I run with the flag `TF_CPP_VMODULE=asm_compiler=2` I get this output:

`2020-05-20 14:57:36.735438: I tensorflow/stream_executor/gpu/asm_compiler.cc:169] Looking for ptxas at /usr/local/cuda-10.1/bin/bin/ptxas`
`2020-05-20 14:57:36.735500: I tensorflow/stream_executor/gpu/asm_compiler.cc:169] Looking for ptxas at /usr/local/cuda/bin/ptxas`
`2020-05-20 14:57:36.735521: I tensorflow/stream_executor/gpu/asm_compiler.cc:178] Using ptxas at /usr/local/cuda/bin/ptxas`

So it seems that when it's looking in cuda-10.1 it's going in the wrong dir (there is no cuda-10.1/bin/bin, the ptxas binary is in cuda-10.1/bin). Does anyone know how to fix this?

The situation is somewhat similar to #33375

**Comment by Saduf2019** [comment]
@FMalerba Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by FMalerba** [comment]
Managed to find a workaround with
`export XLA_FLAGS=--xla_gpu_cuda_data_dir=path_to_cuda`

**Comment by Saduf2019** [comment]
@FMalerba 
please let us know if we can move this issue to closed status.

**Comment by FMalerba** [comment]
sure

**Comment by Saduf2019** [comment]
Moving to closed status with confirmation
