### ISSUE TITLE
Is there any good detailed  description of GraphDef and Saved Model ?

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#39729]
## URL(s) with the issue:

N/A

## Description of issue (what needs changing):

Need clear documentation with details  on what makes all these different formats different. 

### Clear description

Looking for  a clear description  (pun not intended)  of  GraphDef and Saved Model - their diffrences etc., needs for  them ( and others such as ckpt ) .

### Correct links

N/A

### Parameters defined

N/A

### Returns defined

N/A

### Raises listed and defined

N/A

### Usage example

N/A

### Request visuals, if applicable

N/A

### Submit a pull request?

N/A

**Comment by amahendrakar** [comment]
@whatdhack,
Please check [this description](https://www.tensorflow.org/guide/saved_model#the_savedmodel_format_on_disk) for the SavedModel format and let us know if it helps Thanks!

**Comment by whatdhack** [comment]
That looks good for SavedModel for TF 2.0 .  How about a similar page for TF 1.15 ?  How about the other model types (GraphDef/Forzen/ckpt)  ?

**Comment by amahendrakar** [comment]
@whatdhack,
tf.saved_model is common for both TF 1.x and 2.x. You can read more about training checkpoints from [this link](https://www.tensorflow.org/guide/checkpoint). 

Also, this question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is  a larger community that reads questions there.

**Comment by whatdhack** [comment]
I do not think I can agree with that statement. Availability of basic clear documentation are part of the product  (open source or not). Saves users/developers time and energy.  How difficult is it to add a page to the already existing documentation ? I would have done that myself,if I knew exactly what the differences are, given the amount of time I have spent trying  to understand the differences.

**Comment by lamberta** [comment]
You saw the SavedModel guide: https://www.tensorflow.org/guide/saved_model ?

Graph optimization guide also useful: https://www.tensorflow.org/guide/graph_optimization

**Comment by whatdhack** [comment]
Yes, have seen  that. Does not really explain  how contnts of Saved Model, GraphDef, Frozen model etc differs and which one is suitable for what.

**Comment by randyzhao** [comment]
@lamberta Is there any update on this issue. I agree with @whatdhack . We do need good doc about these formats. Some basic concepts are not clear now, e.g. what's diff of saved model vs graph def, when to use which format.

**Comment by jfbrennan** [comment]
A comparison table would be very helpful for folks new to TF

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
