### ISSUE TITLE
choosing bitrate when encoding audio

### ISSUE THREAD

**Issue by avnx** [tensorflow/tensorflow#39761]
**In tf1.15 there was the support of  choosing bitrate when encoding audio**
https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/contrib/ffmpeg/ffmpeg_ops.py#L101

**Now the possibility is cut out**

It is very important feature in speech recognition tasks. So It will be great when you return back this option.

**Comment by ymodak** [comment]
`contrib` module is deprecated and no longer part of TensorFlow.
Have you tried using [`tf.audio.encode_wav`](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/audio/encode_wav) ?

**Comment by avnx** [comment]
> `contrib` module is deprecated and no longer part of TensorFlow.
> Have you tried using [`tf.audio.encode_wav`](https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/audio/encode_wav) ?

Hi.
I talk about bitrate, not sample rate.

Neither of any encoders support the option now.

As I mentioned earlier it is very important feature in speech recognition tasks.
As a proof of my words you could look at paper from Google https://arxiv.org/pdf/1808.05312.pdf  p3.3

**Comment by rryan** [comment]
Thanks for the feature request @avnx, but I'm confused. Setting a bitrate doesn't seem to have been part of the tf.contrib.ffmpeg public API? Do you mean you edited the source code?

It would be nice if encode/decode audio had this support. I think we could mark this contributions welcome, because I doubt the core team has bandwidth to look at it.

**Comment by avnx** [comment]
> Thanks for the feature request @avnx, but I'm confused. Setting a bitrate doesn't seem to have been part of the tf.contrib.ffmpeg public API? Do you mean you edited the source code?
> 
> It would be nice if encode/decode audio had this support. I think we could mark this contributions welcome, because I doubt the core team has bandwidth to look at it.

Hi,

Yes, I edited source code. It was not hard as you can see https://github.com/tensorflow/tensorflow/blob/r1.15/tensorflow/contrib/ffmpeg/ffmpeg_ops.py#L101

Just change one option and that's it.

I tried to go deeper in current code tf2.2 and I can't imagine how I could "turn on" the option to encode with different bitrate.

**Comment by yongtang** [comment]
@avnx ffmpeg and all tf.contrib has been removed from tensorflow code tree and is not part of the distribution since TF 2.0.

They are being distributed to separate repos and pip. tensorflow-io are mostly for I/O, audio/video, tensorflow-addons are mostly for additional tf.keras related modules. You can open feature request issues to [tensorflow/io](https://github.com/tensorflow/io) if it is audio related.

**Comment by avnx** [comment]
> @avnx ffmpeg and all tf.contrib has been removed from tensorflow code tree and is not part of the distribution since TF 2.0.
> 
> They are being distributed to separate repos and pip. tensorflow-io are mostly for I/O, audio/video, tensorflow-addons are mostly for additional tf.keras related modules. You can open feature request issues to [tensorflow/io](https://github.com/tensorflow/io) if it is audio related.

so what do you want to say? I didn't get you.

I opened feature request and attached info where you (Google) use bitrate manipulation during solving speech recognition tasks. I say that it is very important feature in speech recognition tasks and it is good to have it. Especially considering the fact that there was the opportunity to do that in older versions of tf.

I would be happy to do that by myself but tf code became very complicated in processing an audio (since tf2) and I don't think that I am capable of adding this feature by myself.

**Comment by yongtang** [comment]
@avnx I was suggesting you to open a feature request issue in  [tensorflow/io](https://github.com/tensorflow/io), so that we can track the progress there. We will add support for your feature request if there is enough interests from overall community.

Since  [tensorflow/io](https://github.com/tensorflow/io) and  [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) are two different repos, feature requests cross the repo might not have been noticed.

**Comment by yongtang** [comment]
@avnx I have opened a feature request in https://github.com/tensorflow/io/issues/994 .

Let's continue the conversion there to track the progress.

**Comment by avnx** [comment]
> @avnx I was suggesting you to open a feature request issue in [tensorflow/io](https://github.com/tensorflow/io), so that we can track the progress there. We will add support for your feature request if there is enough interests from overall community.
> 
> Since [tensorflow/io](https://github.com/tensorflow/io) and [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) are two different repos, feature requests cross the repo might not have been noticed.

I am sorry. Didn't get your idea first time.
Thank you!
