### ISSUE TITLE
Keras: list index is out of range!

### ISSUE THREAD

**Issue by neel04** [tensorflow/tensorflow#39787]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by amahendrakar** [comment]
@neel04,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the TensorFlow version you are using.

Also, if this question is not a TensorFlow bug or feature request, it is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged//tensorflow) as there is a larger community that reads questions there. Thanks!

**Comment by jaketae** [comment]
Hi @neel04, I think it would be best to close either this or #39789, as they are duplicate threads referring to the same issue. Just a quick suggestion on logistics in passing, thanks!
