### ISSUE TITLE
tf.queue.FIFOQueue throws NotFoundError on enqueue / dequeue if created in graph mode

### ISSUE THREAD

**Issue by alexrobomind** [tensorflow/tensorflow#39820]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Windows 7 and Ubuntu 18.04.3 LTS (colab)
- TensorFlow installed from (source or binary): pip install tf-nightly-gpu
- TensorFlow version (use command below):    v1.12.1-32502-g2544e4e277 2.3.0-dev20200523 (Windows and colab)
- Python version: 3.6.6 (Windows), 3.6.9 (colab)
- CUDA/cuDNN version: 10.1/7.6.3.30 (Windows), unknown (colab)
- GPU model and memory: NVidia 1080Ti ~11GB (Windows), unknown (colab)

**Describe the current behavior**

When creating a tf.FIFOQueue inside a tf.function decorated function, enqueueing / dequeueing tensors from the queue fails with a NotFoundError mentioning a non-existing resource of name "localhost/{Some number}/{C++ mangled name of class tensorflow::QueueInterface}"

All operations work fine if the queue is created in eager mode.

**Describe the expected behavior**

Either the graph mode execution should succeed just like in eager mode, or the unsuitability of queue creation for graph mode should be documented as API.

**Standalone code to reproduce the issue**

Linux case:

https://colab.research.google.com/drive/1OQ68ibI-9u-6f4nslwIzDuMzdztxVGwX?usp=sharing

Windows case:

```
import tensorflow as tf

@tf.function
def foo():	
	queue = tf.queue.FIFOQueue(-1, [tf.string], tf.TensorShape([]))
	queue.enqueue('Hello')
	s = queue.dequeue()
	tf.print(s)

foo()
```

Log is attached

[log.txt](https://github.com/tensorflow/tensorflow/files/4672215/log.txt)

**Comment by ravikyram** [comment]
I have tried in colab with TF - GPU nightly version and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/a2e6523f42fee5297dfb2a1ed03457f7/untitled33.ipynb).Thanks!

**Comment by allenlavoie** [comment]
Currently you need to hold on to the Python object that owns the queue resource outside of the function, like this: https://github.com/tensorflow/tensorflow/blob/b1a712d40d67a7a9f88d6e2f5f5fe28fa10c7f1e/tensorflow/python/kernel_tests/fifo_queue_test.py#L145-L157

It'd be good if we threw an error message, or alternatively let the function create and destroy a transient queue resource every time it's run, so I'm leaving the bug open,

**Comment by saikumarchalla** [comment]
I tried to reproduce the issue in latest TF version 2.5 and the issue still exists.Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
