### ISSUE TITLE
array slice on tf.function is about 23 times slower than non tf function

### ISSUE THREAD

**Issue by w19787** [tensorflow/tensorflow#39850]
tf version: 2.1.0
HW: one gpu

```python code
import time
import tensorflow as tf

@tf.function
def test_tf_fun(inputs):
    for i in range(16):
        for j in range(128):
            t = inputs[i, j, :]

inputs = tf.random.uniform((16, 128, 4))

t1 = time.time()
test_tf_fun(inputs)
print("duration for tf.fun: ", time.time() - t1)
```
![image](https://user-images.githubusercontent.com/731496/82810012-03a0ca00-9ec0-11ea-8ed5-778b3ed4ab66.png)

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with [TF v2.1](https://colab.research.google.com/gist/amahendrakar/e52732cb63db90f1e641d2f6805766a4/39850-2-1.ipynb), [TF v2.2](https://colab.research.google.com/gist/amahendrakar/d52e2ebe334d840d95661cf1184b5560/39850.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/6ffd39d98243e58c00fc7f561d55c993/39850-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by dathudeptrai** [comment]
@ymodak any update ?

**Comment by w19787** [comment]
@ymodak any update for this issue?

**Comment by zhuzilin** [comment]
@w19787 
The reason for this is the first invocation will do lots of graph optimization and will add overhead. If you run the function multiple times, you could see the performance is actually better. For example ,if you execute the function 5 times:
```python
# the function definition is the same as above
# ...

for _ in range(5):
    t1 = time.time()
    test_tf_fun(inputs)
    print("duration for tf.fun: ", time.time() - t1)
```
with `tf.function` will have:
```
duration for tf.fun:  5.076590061187744
duration for tf.fun:  0.00021696090698242188
duration for tf.fun:  0.0001277923583984375
duration for tf.fun:  0.00012183189392089844
duration for tf.fun:  0.00015115737915039062
```
without will be:
```
duration for tf.fun:  0.12435412406921387
duration for tf.fun:  0.12618684768676758
duration for tf.fun:  0.1261131763458252
duration for tf.fun:  0.1262199878692627
duration for tf.fun:  0.1267070770263672
```
My test environment is a macbook pro 2019.

**Comment by zhuzilin** [comment]
@mdanatg 
Is it possible for `tf.function` to add config like `RewriterConfig` to control the grappler?

**Comment by w19787** [comment]
> @w19787
> The reason for this is the first invocation will do lots of graph optimization and will add overhead. If you run the function multiple times, you could see the performance is actually better. For example, if you execute the function 5 times:
> 
> ```python
> # the function definition is the same as above
> # ...
> 
> for _ in range(5):
>     t1 = time.time()
>     test_tf_fun(inputs)
>     print("duration for tf.fun: ", time.time() - t1)
> ```
> 
> with `tf.function` will have:
> 
> ```
> duration for tf.fun:  5.076590061187744
> duration for tf.fun:  0.00021696090698242188
> duration for tf.fun:  0.0001277923583984375
> duration for tf.fun:  0.00012183189392089844
> duration for tf.fun:  0.00015115737915039062
> ```
> 
> without will be:
> 
> ```
> duration for tf.fun:  0.12435412406921387
> duration for tf.fun:  0.12618684768676758
> duration for tf.fun:  0.1261131763458252
> duration for tf.fun:  0.1262199878692627
> duration for tf.fun:  0.1267070770263672
> ```
> 
> My test environment is a macbook pro 2019.

thanks. it is very reasonable explanation.

**Comment by mdanatg** [comment]
Yes, it's possible with `tf.config.optimizer.set_experimental_options`, but it's tricky to tweak these settings to get an apples-to-apples comparison.

Note that if you only want to benchmark the performance of slice operations, you should simplify the code as much as possible. There are a few caveats:

 * in eager mode, you should add a `.numpy()` call at the end of the computation, to make sure you measure the total time from starting it to getting the results, otherwise you may only be benchmarking asynchronous launch costs
 * within tf.function, `for i in range` will multiply the ops in the graph, so the two nested loops will measure the performance of 16 * 128 slice ops executed with maximum parallelism; `for i in tf.range` does create a graph loop, but even that will be aggressively parallelized
 * the cost of calling tf.function alone is significant, higher than calling a single slice op; you should account for that when benchmarking
 * there are many caches involved - for example, tf.function compilations are cached, tf.constant is cached; you should always do dry-runs to get accurate results

So to make an apples-to-apples comparison, here's what I'd run:

```
def test_no_tf_fun(inputs, i, j):
    return inputs[i, j, :]


@tf.function
def test_tf_fun(inputs, i, j):
    return inputs[i, j, :]


@tf.function
def test_tf_fun_empty(inputs, i, j):
    return i


inputs = tf.random.uniform((16, 128, 4))

# Warm-up caches
test_tf_fun(inputs, tf.constant(0), tf.constant(0)).numpy()
test_tf_fun_empty(inputs, tf.constant(0), tf.constant(0)).numpy()
for c in range(128):
  tf.constant(c).numpy()

# Measure cost of calling tf.function
t1 = time.time()
for i in range(16):
    for j in range(128):
      test_tf_fun_empty(inputs, tf.constant(i), tf.constant(j)).numpy()
t_empty = time.time() - t1
print("duration for empty tf.fun: ", t_empty)

# Measure cost of slice inside tf.function
t1 = time.time()
for i in range(16):
    for j in range(128):
      test_tf_fun(inputs, tf.constant(i), tf.constant(j)).numpy()
print("duration for tf.fun: ", time.time() - t1 - t_empty)

# Measure cost of slice outside tf.function
t1 = time.time()
for i in range(16):
    for j in range(128):
      inputs[i, j, :].numpy()
print("duration without tf.function: ", time.time() - t1)
```

On my machine, that printed:
```
duration for empty tf.fun:  0.4628314971923828
duration for tf.fun:  0.02042388916015625
duration without tf.function:  0.2617456912994385
```
