### ISSUE TITLE
Issue with fetching of Output Tensor sizes in Model

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#39870]
Output Size in tfLite Model for few networks are obtained only after the allocation of Tensorflow lite tensors. Could you please explain why it is special with the models like above . When I fetch the output dimensions of each output in the Model before allocation of tensors , I was getting the dimensions as zero.

Example : - http://storage.googleapis.com/download.tensorflow.org/models/tflite/coco_ssd_mobilenet_v1_1.0_quant_2018_06_29.zip

Output Size in tfLite Model for few other networks are obtained only independent of the allocation of Tensorflow lite tensors.  When I fetch the output dimensions of each output in the Model before allocation of tensors , I was getting the proper dimensions. 

Example : -
https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_1.0_224.tgz

Please explain the reason of this behaviour based on model

**Comment by amahendrakar** [comment]
@pranathibl,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the TensorFlow version you are using. Thanks!

**Comment by pranathibl** [comment]
Hi,

I have tensor flow interpreter c++ API to fetch the number of dimensions of each Output.

It was returning zero before allocation for few models. after allocation, No. of dimensions were proper.

Reproduction API is added
![Picture15](https://user-images.githubusercontent.com/47776253/84111159-f77e4600-aa43-11ea-8274-c0252621ed43.png)
 as attachment.

**Comment by srjoglekar246** [comment]
This is intended behavior. Some models, like the SSD one mentioned in the description, have ops that 'decide' the output tensor dimensions when they go through the `Prepare` phase (this is the phase where op kernels will typically initialize any temporary tensors they need, or programmatically determine their output tensor sizes based on params etc).

If a model doesn't contain any such ops, the output tensor is available before `AllocateTensors()` (which runs the `Prepare` phase of applicable ops). Otherwise, you have to do this after `AllocateTensors()`.
