### ISSUE TITLE
autograph for bool logic control incorrect

### ISSUE THREAD

**Issue by w19787** [tensorflow/tensorflow#39875]
tf version: 2.1.0
HW: one gpu

```python
import tensorflow as tf

@tf.function
def check_zero(data):
    tf.print(data)
    if data == 0:
        tf.print("check zero yes")
        return True
    else:
        tf.print("check zero no")
        return False

@tf.function
def test_arg(a):
    is_zero = check_zero(a)
    
    if is_zero is True:
        tf.print("zero")
    else:
        tf.print("not zero")

for i in range(3):
    test_arg(i)
```
![image](https://user-images.githubusercontent.com/731496/82915054-d711ae80-9fa2-11ea-9f0b-3187d95b7ce8.png)

**Comment by w19787** [comment]
if replace
``` python
    if is_zero is True:
```
to
```python
if tf.equal(is_zero, True):
```
the result will be fine. but the first one seems more friendly for engineer.

**Comment by yongtang** [comment]
I think this is because `is` keywords is not implemented in autograph yet? But if I understand correctly, `is` is testing for identity, not equality. So `if is_zero is True:` probably makes sense as `True` is unique. But the other usages of `is` may not be feasible? /cc @mdanatg as this might be related.

**Comment by Saduf2019** [comment]
@w19787 
Please update as per above comment

**Comment by mdanatg** [comment]
+1 to @yongtang 's note

I recommend using the value directly: `if is_zero:`. You can also use an equality check like `if is_zero == True:`, but there's no obvious advantage to it.

Indeed, autograph doesn't implement `is` and strictly speaking I'm not sure that it can, judging from the [SO answer](https://stackoverflow.com/questions/27276610/boolean-identity-true-vs-is-true), because the semantics of `a is True` mean "a is exactly the singleton object True", in other words `id(a) == id(True)`. Take for example another True-like object:

```
np_true = np.array(True)

bool(np_true)
# True

np_true == True
# True

np_true is True
# False
```

**Comment by w19787** [comment]
the comments are acceptable. thanks. this issue will be closed.
