### ISSUE TITLE
Use of unresolved identifier 'CoreMLDelegate'

### ISSUE THREAD

**Issue by hanishsairohit** [tensorflow/tensorflow#39965]
![Screenshot 2020-05-29 at 12 50 56 AM](https://user-images.githubusercontent.com/44207274/83184096-918de680-a146-11ea-836f-1cf6c895c7fb.png)

pod version TensorFlowLiteSwift 0.0.1-nightly.20200527

Facing this issue even after running 

> pod cache clean TensorFlowLiteSwift

**Comment by Saduf2019** [comment]
@hanishsairohit 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by grin** [comment]
I'm also running into this issue after upgrading from `'0.0.1-nightly.20200513'` to `0.0.1-nightly.20200519` or `0.0.1-nightly.20200527`. My pod spec:

```rb
use_frameworks!

target 'XXX' do
  pod 'TensorFlowLiteSwift', '0.0.1-nightly.20200527'
end
```

**Comment by grin** [comment]
This has fixed it for me:
```rb
use_frameworks!

target 'XXX' do
  pod 'TensorFlowLiteSwift', '0.0.1-nightly.20200527'
  pod 'TensorFlowLiteSwift/CoreML', '0.0.1-nightly.20200527'
  pod 'TensorFlowLiteSwift/Metal', '0.0.1-nightly.20200527'
end
```
They split the TensorFlowLiteSwift pod into subspecs (CoreML, Metal, ...) so you have to install them manually as needed.

**Comment by hanishsairohit** [comment]
Thank you so much! @grin
