### ISSUE TITLE
[MLIR/XLA] Invalid IR passes verification

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/tensorflow#40045]
With TensorFlow HEAD at 3ffb4ad2d43311f41155b6e00fd105e50df685da (May 31), the following snippet should fail verification with `tf-opt` but it doesn't:

```
  func @main(%arg0: memref<4x64x128x3xf32>) -> tuple<tensor<4x64x128x3xf32>> {
    "xla_lhlo.copy"(%arg0, %arg0) : (memref<4x64x128x3xf32>, memref<4x64x128x3xf32>) -> ()
    "xla_lhlo.terminator"() : () -> ()
  }
```

To reproduce: `$ bazel-bin/tensorflow/compiler/mlir/tf-opt  verify.mlir`.

@joker-eph @pifon2a @sherhut

**Comment by pifon2a** [comment]
@bondhugula Why exactly should it fail? Is that because `xla_lhlo.copy` source and destination buffers are the same? 

Currently, there are no custom verifiers for lhlo ops. Also I am a bit surprised to see `tuple` here.

**Comment by bondhugula** [comment]
> @bondhugula Why exactly should it fail? Is that because `xla_lhlo.copy` source and destination buffers are the same?

Not really - this part is fine. (The src/dest of the copy given that this has memory semantics can be the same.)

> 
> Currently, there are no custom verifiers for lhlo ops. Also I am a bit surprised to see `tuple` here.

It was the return type signature that I felt was out of line with the terminator -- as to where the function was getting its return value (tuple tensor) from.

**Comment by joker-eph** [comment]
So the issue is with the custom terminator which isn't strict about the possible parent operations?
Then the minimal example is something like:

```
func @main() -> f32 {
  "xla_lhlo.terminator"() : () -> ()
}
```

**Comment by bondhugula** [comment]
> So the issue is with the custom terminator which isn't strict about the possible parent operations?
> Then the minimal example is something like:
> 
> ```
> func @main() -> f32 {
>   "xla_lhlo.terminator"() : () -> ()
> }
> ```

That's right - that would be the minimal form - the copy has nothing to do with this issue. Not a high priority issue, but would be good to fail verification in such cases.

**Comment by joker-eph** [comment]
https://reviews.llvm.org/D81045 should help here.

**Comment by bhack** [comment]
What is the status of this?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
