### ISSUE TITLE
Unclear shape dependency of `value` in  `tf.keras.backend.moving_average_update` documentation

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#40050]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/backend/moving_average_update

### Clear description

Unclear shape dependency of input `value`. According to the document, `value` should have the same shape as `variable`, but it is unclear what is `variable`.

### Parameters defined

Yes

### Returns defined

Yes

### Raises listed and defined

No

**Comment by Saduf2019** [comment]
@DNXie 
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by DNXie** [comment]
@Saduf2019 

### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.2.0-rc3
- **Python version**: 3.8.2
