### ISSUE TITLE
Design a generic type Python API for the hparams plugin

### ISSUE THREAD

**Issue by neilteng** [tensorflow/tensorflow#40100]
**System information**
- TensorFlow version (you are using): tf2.20
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
While I follow the following tutorial to do the hyperparameter tuning. I cannot choose from list type object.
https://www.tensorflow.org/tensorboard/hyperparameter_tuning_with_hparams

```
HP_NUM_UNITS = hp.HParam('num_units', hp.Discrete([[256, 512, 256, 128,64],[256, 512, 1024, 512, 256, 128],[256, 512, 1024, 512, 256, 128, 64, 32]]))

ValueError: Unknown dtype: <class 'list'>

```

I am playing with the canned estimator and tune the 'dnn_hidden_units' hyperparameter with 'from tensorboard.plugins.hparams import api as hp'. But it seems that I cannot tune 'dnn_hidden_units' with this library. 

```
    estimator = tf.estimator.DNNLinearCombinedClassifier(
        # wide settings
        linear_feature_columns=feature_columns,
        linear_optimizer=FtrlwithParams,
        # deep settings
        dnn_feature_columns=feature_columns,
        dnn_hidden_units=[256, 512, 256, 128, 64],
#         dnn_hidden_units=[1000, 500,100],
        dnn_optimizer=AdamWithParams,
        batch_norm=True,
        dnn_dropout=0.5,
        n_classes=NUM_LABEL,
        config=RUN_CONFIG,
        # warm-start settings
        warm_start_from=MODEL_DIR
    )
```

**Will this change the current api? How?**
No. Maybe we can add a new API or a generic API.

**Who will benefit with this feature?**
Anyone need to do hyperparameter tuning.

I expect that people build models with list-like parameter. So I think this is a common feature.

**Comment by sachinprasadhs** [comment]
Hi, Estimator will be deprecated from Tensorflow 2.12 since it uses Tensorflow V1 behavior.
Could you please migrate from Estimator to Keras API which will enable you to perform the aforementioned tasks, such as [model building](https://www.tensorflow.org/guide/keras/custom_layers_and_models), gradient application, [training](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit), evaluation, and prediction.
Refer Migration guide here https://www.tensorflow.org/guide/migrate/migrating_estimator for more details. Thanks!
