### ISSUE TITLE
tf.random.uniform unexpected behaviour for unknown shape

### ISSUE THREAD

**Issue by chrism0dwk** [tensorflow/tensorflow#40125]
Hi,

Using `tf.random.uniform` with a tensor of equal `minval` and `maxval` values and unknown shape does not generate the expected independent variates:
```
tf.random.uniform((), minval=[0, 0, 0], maxval=[4,4,4])
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([2.1699166, 2.1699166, 2.1699166], dtype=float32)>
```
If the shape is specified, however, independent random variates are returned:
```
tf.random.uniform([3], minval=[0, 0, 0], maxval=[4,4,4])
<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.3341255 , 0.45406246, 3.4779797 ], dtype=float32)>
```
Is this a bug or a known feature?  If the latter, should it be documented?

Thanks.

TF version 2.3.0-dev20200528 (tf-nightly)

**Comment by yongtang** [comment]
@chrism0dwk the issue was that `tf.random.uniform` had the usage of `math_ops.add` which implicitly broadcast the result from the random and causes the seemingly definitely result. The fix for this issue is the same as some other issues such as #34363 

There were several attempts to fix this issue in #34399 / #38585. However, due to internal tests failures they were not merged yet (merged/reverted).

Once the internal test failures could be fixed, the fix could be merged and the issue could be resolved then.

**Comment by ravikyram** [comment]
I could reproduce the issue in colab with TF nightly version.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/433b2432284a5833c916c86fb1cde531/untitled48.ipynb).
As suggested by @yongtang we will verify the issue once PRs get merged and close the issue.Thanks!

**Comment by mihaimaruseac** [comment]
It seems the fix in #38585 fails with

```
third_party.tensorflow.python.framework.errors_impl.InvalidArgumentError: Rank of input (1) must be no greater than rank of output shape (0). [Op:BroadcastTo]
```

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5 and Nightly versions. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/b5cf845e4ff02c1a484ba6ab88647334/untitled82.ipynb).Thanks!

**Comment by flippy1313** [comment]
I would like to take this issue and try to fix it.

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF 2.11 and TF Nightly. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/c5f31f707dd0f5a23ffb9c3349194eb0/40125.ipynb). Thank you.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
