### ISSUE TITLE
Difference of 0.5 factor compared to Research Paper in Soft NMS implementation

### ISSUE THREAD

**Issue by swapniel99** [tensorflow/tensorflow#40253]
Hi,

I believe the below lines are for Gaussian implementation of Soft-NMS, since the variable 'scale' is used in:
https://github.com/tensorflow/tensorflow/blob/7474d3c8345d663cea3f9132c47cd1bd342b0cec/tensorflow/core/kernels/non_max_suppression_op.cc#L189
https://github.com/tensorflow/tensorflow/blob/7474d3c8345d663cea3f9132c47cd1bd342b0cec/tensorflow/core/kernels/non_max_suppression_op.cc#L194

But in the research paper, no multiplier of 0.5 is mentioned. Please refer page number 4 of [https://arxiv.org/pdf/1704.04503.pdf](https://arxiv.org/pdf/1704.04503.pdf).

So if paper suggests ideal sigma value of 0.5, should I configure value of 0.25 instead?

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.
Thanks!

**Comment by swapniel99** [comment]
Never mind I used 0.25 as sigma and got correct results. Just wondering why only tensorflow implementation has 0.5 in source code. There are various other implementations which work as is.

**Comment by fsx950223** [comment]
Same question.

**Comment by mingxingtan** [comment]
Hi @jch1 @ymodak  this looks more like a bug. 

Jonathan, I saw you implemented this code (thanks for the great implementation). I wonder is there any specific reason to use 0.5 instead of 1 (as the paper)?
Should we either change it to 1 or update the document (https://www.tensorflow.org/api_docs/python/tf/image/non_max_suppression_with_scores) to mention this?

Thanks!

**Comment by swapniel99** [comment]
@mingxingtan To me it looked like following a convention since in Gaussian Exponent, denominator is always 2*sigma. But still it is better to follow what the paper suggests.

**Comment by fsx950223** [comment]
Any update?
Could I submit a pull request?

**Comment by swapniel99** [comment]
can I do it? :)

**Comment by mingxingtan** [comment]
@swapniel99 @fsx950223 I guess it is not easy to change the value because many existing code already has dependence on it, but you should definitely update the doc to reflect this point.

**Comment by fsx950223** [comment]
> @swapniel99 @fsx950223 I guess it is not easy to change the value because many existing code already has dependence on it, but you should definitely update the doc to reflect this point.

Maybe they set wrong soft_nms_sigma too.
https://github.com/tensorflow/models/blob/451906e4e82f19712455066c1b27e2a6ba71b1dd/research/object_detection/core/multiclass_nms_test.py#L566

**Comment by swapniel99** [comment]
> > @swapniel99 @fsx950223 I guess it is not easy to change the value because many existing code already has dependence on it, but you should definitely update the doc to reflect this point.
> 
> Maybe they set wrong soft_nms_sigma too.
> https://github.com/tensorflow/models/blob/451906e4e82f19712455066c1b27e2a6ba71b1dd/research/object_detection/core/multiclass_nms_test.py#L566

We can test it but I don't think so. I came across this issue while using object detection api itself.

**Comment by sachinprasadhs** [comment]
@swapniel99 , Thanks for pointing the difference.

Does changing as per below suggestion works as you expected?
https://github.com/tensorflow/tensorflow/blob/e59fc0739e9228a01e0ad452f5143e4e40430015/tensorflow/core/kernels/image/non_max_suppression_op.cc#L229-L237


```
  T scale = static_cast<T>(0.0);
  bool is_soft_nms = soft_nms_sigma > static_cast<T>(0.0);
  if (is_soft_nms) {
    scale = soft_nms_sigma;
  }

  auto suppress_weight = [similarity_threshold, scale,
                          is_soft_nms](const T sim) {
    const T weight = Eigen::numext::exp<T>(scale * sim * sim);
```

**Comment by swapniel99** [comment]
Hi,

I don't remember the context much here since this was some time back.
But looking at the code, I think it should be 
`static_cast<T>(-1.0) / soft_nms_sigma;`
However like I said it has been a long time since I have worked on this.
Please check paper.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
