### ISSUE TITLE
Support for .next() on tf.data.Dataset

### ISSUE THREAD

**Issue by fostiropoulos** [tensorflow/tensorflow#40285]
**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): **Yes** (If approved)

**Describe the feature and the current behavior/state.**
Currently when working with https://www.tensorflow.org/api_docs/python/tf/data/Dataset
You can iterate a Dataset with a loop e.g. 
```python
for x,y in train:
   tf.print(x,y)
```

However if you want to get a single batch, the only option would be:

```python
train.__iter__().next()
```

Currently there is only support for creating a numpy iterator, Example
```python
train.as_numpy_iterator().next()
```
**and the output is not a tf object.** 

The closest to the expected behavior of `.next()` would be `train.take(1)` which still needs to be converted to an iterator. 

The current methods of getting a single batch are tedious and create bug prone code, multiple lines, and/or functions called. 

**Will this change the current api? How?**

It will create a .next() function for tf.data.Dataset e.g. 

https://www.tensorflow.org/api_docs/python/tf/data/Dataset#next

**Who will benefit with this feature?**
Hopefully the entire community 

**Any Other info.**

The feature could be implemented by using an existing iterator for the dataset object and when calling .next() simply picking an element from that iterator rather than creating an iterator every time for performance benefits.

**Comment by lgeiger** [comment]
> However if you want to get a single batch, the only option would be `train.__iter__().next()`

I think you should be able to call `next(iter(train))` similar to normal Python 3 `next(iter(range(3)))`.

**Comment by fostiropoulos** [comment]
@lgeiger Thanks! I was not aware of that, however maybe it is tedious? in the use case of custom iteration over the data, wouldn't it make more sense for the iterator to be part of the dataset class/object. Such that the state of the iteration is saved and compatible with other methods such as take, rather than creating a new iterator every time?

**Comment by jsimsa** [comment]
@lgeiger suggestion is idiomatic use of `tf.data` APIs.

`tf.data.Dataset.next()` is problematic. What should happen when you call `next()` multiple times? I assume you would like different elements to be produced. But in that case `tf.data` would need to maintain internal iterator object to provide this functionality. If that's the case, how is the lifetime of this iterator object managed? When you create iterator explicitly via `iter`, the lifetime is tied to the lifetime of Python object which makes it possible to decide when the iterator object is no longer needed and can be destroyed. In contrast, if the iterator object was hidden inside of tf.data internals, then you would need an API for explicitly destroying it (since the iterator objects may be allocating a large amount of memory). There is tens of bugs opened against Keras leaking memory because of exactly this -- Keras backend session allocating memory that needs to be explicitly clear -- and we will not repeat that mistake for tf.data.
