### ISSUE TITLE
SupervisedSession cannot run dict fetchs.

### ISSUE THREAD

**Issue by coderXiangLi** [tensorflow/tensorflow#4031]
### `supervised_session.SupervisedSession`  under  `contrib.learn` cannot run dict fetchs:

 1.Document says that it's same as `tf.Session.run()` and confused.  
    
    	def run(self, fetches, feed_dict=None, options=None, run_metadata=None):
        """Run ops in the supervised session.
        	This method is completely compatible with the `tf.Session.run()` method.

        	Args:
          	fetches: Same as `tf.Session.run()`.
          	feed_dict: Same as `tf.Session.run()`.
          	options: Same as `tf.Session.run()`.
          	run_metadata: Same as `tf.Session.run()`.

        	Returns:
          	Same as `tf.Session.run()`.
        	"""
        	return self._sess.run(fetches, feed_dict=feed_dict, options=options,
                              run_metadata=run_metadata)

2.it is constructed with MonitoredSession, so it can only run `one` or a `list`.
	
		actual_fetches = {
    		caller': fetches,
    		self._global_step_tensor: self._global_step_tensor,
    		'monitors': [_as_graph_element(f, self.graph) for f in monitor_fetches]
  		}

Could you support for running a dict as tf.Session.run()? Or modify the document more clearly?

**Comment by martinwicke** [comment]
@ispirmustafa this does look like a bug in the docstring (or a bug in MonitordSession), or are we misunderstanding this?

**Comment by ispirmustafa** [comment]
supervised_session.SupervisedSession had that restriction. SuperviseSession was removed and replaced with a MonitoredSession. MonitoredSession don't have this restriction.

FYI, we don't export Supervised or Monitored session via __init__ since we're still working on it's interface/implementation. It will be exported via __init__ when we think it's ready for a global use.
