### ISSUE TITLE
How to use BlockLSTM and BlockLSTMGrad to build a LSTM network in C++?

### ISSUE THREAD

**Issue by cj741** [tensorflow/tensorflow#40311]
Anyone have idea on how to use BlockLSTM and BlockLSTMGrad to build a LSTM network in C++? It take me quit a long on this problem, please give me a simple example, many thanks!

**Comment by Saduf2019** [comment]
@cj741 

Please refer to this [link](https://tensorflow.google.cn/api_docs/python/tf/raw_ops/BlockLSTM?authuser=0&hl=Es) , [link1](http://maggus.com.co/TestLeo/Django/test34/lib/python3.4/site-packages/tensorflow/contrib/rnn/ops/gen_lstm_ops.py) 


This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged//tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

**Comment by gowthamkpr** [comment]
Closing this issue as it has been inactive for more than 3 weeks. Please add additional comments for us to open the issue again. Thanks!
