### ISSUE TITLE
Neural Structured Learning

### ISSUE THREAD

**Issue by maxkaustav** [tensorflow/tensorflow#40321]
Is neural structured learning is same as using graph neural network?

**Comment by ravikyram** [comment]
@maxkaustav 

Can you go through the [link](https://www.tensorflow.org/neural_structured_learning) and see if it helps you.
This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
