### ISSUE TITLE
ValueError: You are trying to load a weight file containing 16 layers into a model with 0 layers.

### ISSUE THREAD

**Issue by vijay2001** [tensorflow/tensorflow#40378]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
# Copy and paste here the exact command
```

**The output from the converter invocation**

```
# Copy and paste the output here.
```

**Also, please include a link to the saved model or GraphDef**

```
# Put link here or attach to the issue.
```

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:
- Producing wrong results and/or decrease in accuracy
- Producing correct results, but the model is slower than expected (model generated from old converter)

**RNN conversion support**
If converting TF RNN to TFLite fused RNN ops, please prefix [RNN] in the title.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@vijay2001 
Please share a simple stand alone code for us to replicate the issue faced and You may want to double check your weight file since it is saying the weight file contains 0 layers. 

with respect to the error reported, please refer to these links:
[link](https://github.com/keras-team/keras/issues/10417) [link1](https://github.com/tensorflow/tensorflow/issues/34016) [link2](https://stackoverflow.com/questions/51544666/keras-try-save-and-load-model-error-you-are-trying-to-load-a-weight-file-contain) [link3](https://www.google.com/search?rlz=1CANPDX_enIN885&biw=1410&bih=789&ei=O9ngXuzoMaHB3LUP19afsAk&q=You+are+trying+to+load+a+weight+file+containing+16+layers+into+a+model+with+0+layers&oq=You+are+trying+to+load+a+weight+file+containing+16+layers+into+a+model+with+0+layers&gs_lcp=CgZwc3ktYWIQAzICCABQir7ZJViKvtklYMLE2SVoAXAAeACAAbsBiAG7AZIBAzAuMZgBAKABAaABAqoBB2d3cy13aXqwAQA&sclient=psy-ab&ved=0ahUKEwis8uPVpvfpAhWhILcAHVfrB5YQ4dUDCAw&uact=5)
