### ISSUE TITLE
Tensorflow Java API reliability/stability guaranties

### ISSUE THREAD

**Issue by hbeybutyan** [tensorflow/tensorflow#40465]
Hello everyone

I want to use the TensorFlow Java API ( https://www.tensorflow.org/install/lang_java )

On the official page provided above it is stated that "Caution: The TensorFlow Java API is not covered by the TensorFlow API stability guarantees."

I have read the "TensorFlow API stability guarantees", googled little and still have the following questions:

1. If I will load the trained model with "TensorFlow Java API"  and it will not complain, can I be sure that the inferred output is correct, meaning that I would get the same output if I would load the model in python?
2. When the 2.3 release expected to happen so TensorFlow Java API will support tensorflow 2?

Thanks
Harut

**Comment by gaikwadrahul8** [comment]
@hbeybutyan 

Apologies for the delay and I found similar issue [#43335](https://github.com/tensorflow/tensorflow/issues/43335) where user has noticed slight difference in the result of model with TF version 1.15.2 in Python and libtensorflow-1.15.0.jar. but user tried Tensorflow version 1.x which is not actively supported.

TensorFlow Java has its own release cycle, independent from the [TensorFlow runtime](https://github.com/tensorflow/tensorflow). Consequently, its version does not match the version of TensorFlow runtime it runs on. Consult the TensorFlow Java [versioning table](https://github.com/tensorflow/java/#tensorflow-version-support) to list all versions available and their mapping with the TensorFlow runtime.

Could you please try TensorFlow/Java Version as per the versioning table and check your model is giving the same result with Tensorflow Java API and TF version in python ?

If issue still persists, in order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using ?

Thank you!

**Comment by hbeybutyan** [comment]
Hello @gaikwadrahul8 

Thanks for your response.
Unfortunately I can not provide any details to you because I am not working on the project any more.

But I believe the question is clear by itself. Seems I just did not found the answer in documentation and wanted to make sure everything will work as expected.

I just requested a clarification on documentation.

Regards

**Comment by gaikwadrahul8** [comment]
Hi, @hbeybutyan 

Thank you for the clarification and Apologies for the delayed response w.r.t your questions related with TensorFlow Java API is not covered by the TensorFlow [API stability guarantees](https://www.tensorflow.org/guide/versions) documentation so Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? 

If you need any further assistance please let us know ?

Thank you!

**Comment by hbeybutyan** [comment]
Hello @gaikwadrahul8 

Can you please try to answer the mentioned 2 questions?

1. If I will load the trained model with "TensorFlow Java API" and it will not complain, can I be sure that the inferred output is correct, meaning that I would get the same output if I would load the model in python?
2. When the 2.3 release expected to happen so TensorFlow Java API will support tensorflow 2?

Regards
Harut

**Comment by gaikwadrahul8** [comment]
Hi, @hbeybutyan 

To be honest with you it's hard to say but some users experienced the difference in the output of TensorFlow Java API model and python model you can refer this one of our user [comment](https://github.com/tensorflow/tensorflow/issues/43560#issuecomment-700396376), you can refer this [version support table](https://github.com/tensorflow/java/#tensorflowjava-version-support) as per that table latest  TensorFlow Java Version(0.5.0-SNAPSHOT) supports TensorFlow Version :2.9.1 with Minimum Java Version :11

We recommend that you upgrade to the latest 2.x version and please let us know if the issue still persists in newer versions ?

Thank you!

**Comment by hbeybutyan** [comment]
Thanks @gaikwadrahul8
