### ISSUE TITLE
Support for use of tensorflow_probability.distributions.Distribution instances in model.fit(...)

### ISSUE THREAD

**Issue by wbeardall** [tensorflow/tensorflow#40482]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): No (have yet to work out the best way to implement)

**Describe the feature and the current behavior/state.**

I have a model that I would like to train using the KL divergence between the model output and a tfp.distributions.Distribution instance. (Note: this model is using tensorflow_probability's probabilistic layers). As of right now, Distributions cannot be plumbed through the model.fit(...) pipeline due to incompatibilities with the DataAdapter classes, as:

1) They are not recognised by TensorLikeDataAdapter as a Tensor-like object (i.e. they fail the _is_tensor() check).

2) tf.keras.utils.Sequence instances that return distributions fail in convert_for_inspection (calling np.array(distribution,dtype='float64') fails as np sees distributions as sequences).

**Will this change the current api? How?**
Change to support this should have no effect on the API, but would expand functionality to users of tf and tfp.

**Who will benefit with this feature?**
Users who use both tf and tfp, and need to use distributions to train models.

**Any Other info.**

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
