### ISSUE TITLE
tfcompile AOT with quantization

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#40486]
Does the `tfcompile` have capability of quantization?
Is `tfcompile` able to process on input the quantized models?

**Comment by ravikyram** [comment]
@peter197321 

Can you please refer this[ link ](https://www.tensorflow.org/xla/tfcompile )and see if it helps you.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by peter197321** [comment]
I think it does not help since AOT compilation works for for x86-64 CPU only as indicated in [AOT (Ahead-of-time) compilation for CPU with tfcompile](https://www.tensorflow.org/xla#aot_ahead-of-time_compilation_for_cpu_with_tfcompile)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
