### ISSUE TITLE
Want to contribute but build takes time

### ISSUE THREAD

**Issue by ratansingh98** [tensorflow/tensorflow#40505]
I am new to TensorFlow's contribution community. I want to add some features and write test some scripts for it, but as it is taking so much time to build. I want to import TensorFlow from the source without re-building every time. 
Please let me know if it's possible or if there is another way of doing that.

**Comment by mihaimaruseac** [comment]
After the first compile the others should be cached and don't take that much of time. Unless you sync to master again, an action which would likely invalidate the cache again.

Unfortunately, we don't have too much engineering time dedicated to streamlining the build. There is some effort in this line but we can benefit from open source community contributions too.

**Comment by amahendrakar** [comment]
@ratansingh98,
If you want to install TensorFlow from pre-built packages, please check this [guide](https://www.tensorflow.org/install/pip).

Or if you have built TensorFlow from source, the `whl` file is stored in the `/tmp/tensorflow_pkg/` directory. You can use this `whl` file to install TensorFlow every time instead of re-building from source.

Please check [this](https://www.tensorflow.org/install/source#build_the_package) installation guide for more information. Thanks!

**Comment by ratansingh98** [comment]
> After the first compile the others should be cached and don't take that much of time. Unless you sync to master again, an action which would likely invalidate the cache again.
> 
> Unfortunately, we don't have too much engineering time dedicated to streamlining the build. There is some effort in this line but we can benefit from open source community contributions too.

Thanks for the info. As for now, the cache can be very useful for me. If possible, I will look into streamlining the build.

**Comment by ratansingh98** [comment]
> @ratansingh98,
> If you want to install TensorFlow from pre-built packages, please check this [guide](https://www.tensorflow.org/install/pip).
> 
> Or if you have built TensorFlow from source, the `whl` file is stored in the `/tmp/tensorflow_pkg/` directory. You can use this `whl` file to install TensorFlow every time instead of re-building from source.
> 
> Please check [this](https://www.tensorflow.org/install/source#build_the_package) installation guide for more information. Thanks!

Thanks @amahendrakar , but that's not exactly was my question. I wanted to reduce that build time or a handy way to import TensorFlow. In my case, I wanted to generate a new **whl** file every time I build TensorFlow from my modified source.
As @mihaimaruseac told, the building is not streamlined enough. I have to rely on the cache.
Thanks for your guidance though.

**Comment by NikhilBartwal** [comment]
@mihaimaruseac Hey, i was actually having the same doubt i built tf from source the day before yesterday and today after pulling the new changes from tf repo i ran bazel build again, it is still taking a lot of time. How much time do you think is reasonable after the initial build? And how are other contributors updating the build everytime new commits are merged? Thanks

**Comment by mihaimaruseac** [comment]
It depends on your operating system and hardware. You should watch memory consumption during build to make sure you are not using swap, since that would definitely slow down builds. There are bazel flags to limit how much RAM should be used by the compilation process and how many processes to run in parallel. These should help with contention issues.

Then, you should make sure you use the bazel cache between builds so that you don't always rebuild from scratch.

Finally, you don't need to always build everything. The way I do it is first I build a pip package from scratch, identify the issue, identify a smaller test showcasing the issue or writing one if it does not exist. Then, as I work on fixing the issue, I only run that test and only when done do I build the entire package again

**Comment by NikhilBartwal** [comment]
@mihaimaruseac Thanks for the reply.

> Then, you should make sure you use the bazel cache between builds so that you don't always rebuild from scratch.

I didn't quite understand what you meant by using the bazel cache as I'm fairly new to bazel and open source, this being my first project.

> The way I do it is first I build a pip package from scratch, identify the issue, identify a smaller test showcasing the issue or writing one if it does not exist. Then, as I work on fixing the issue, I only run that test and only when done do I build the entire package again

It would be great if you could provide a little insight.

**Comment by mihaimaruseac** [comment]
https://docs.bazel.build/versions/master/remote-caching.html

**Comment by bhack** [comment]
You can follow our effort to optimize and continuously monitoring the contributor experience with our official docker developer image at https://github.com/tensorflow/tensorflow/pull/48421 /cc @theadactyl
