### ISSUE TITLE
LSTM example for GPU delegate 

### ISSUE THREAD

**Issue by adonisues** [tensorflow/tensorflow#40574]
Hello, 
I am trying to run my model in android GPU using TF lite and gpu delegate.
But I faced this "UNIDIRECTIONAL SEQUENCE LSTM: Operation is not supported".
From the document "https://www.tensorflow.org/lite/performance/gpu_advanced", LSTM v2 is supported now. 
All examples in tensorflow git are not using this LSTM.
Is there any example for "LSTM v2 (Basic LSTM only)" ?

**Comment by adonisues** [comment]
My model is using following
`tf_enc_model` = tf.keras.models.Sequential([
    tf.keras.layers.Input(shape=(1, input_dim), name='input'),
    tf.keras.layers.LSTM(hidden_size, time_major=False, return_sequences=True)

**Comment by adonisues** [comment]
@ymodak  Hello, Can you show me any document or example for LSTM gpu delegate ?

**Comment by impjdi** [comment]
TFLite GPU doesn't have a good story for RNNs.

First of all, only the basic LSTM is supported.  Unidirectional, bidirectional, full LSTMs are not implemented and we don't have immediate priorities to add the missing ops.

Then comes the problem around invoking the LSTM network with a for loop.  What we've seen in the past is the following pattern:
```
for (int i = 0; i < n; ++i) {
  // copy output state from i - 1 to input state to i
  interpreter->Invoke();
}
```
Unfortunately, this will take up a LOT of time in GPU/CPU synchronization, and at that point, you might as well just stay in the CPU land.

Now a terrible workaround that I have done in one of the LSTM projects is the manual unrolling.  Instead doing the for loop programmatically 28 times at Invoke, I've replicated the graph structure 28 times in the TFLite model, so that it is a single Invoke call.
