### ISSUE TITLE
Unable to create SavedModel from keras model

### ISSUE THREAD

**Issue by MyJumperBroke23** [tensorflow/tensorflow#40572]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 10.15.4
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.2.0rc3
- Python version: 3.7

**Describe the current behavior**

Running model.save("model") creates a standalone file named "model"

**Describe the expected behavior**

Running model.save("model") creates a directory named model that contains assets, saved_model.pb, and variables

**Standalone code to reproduce the issue**
Link to model: https://www.dropbox.com/s/6ginejkhna1sic8/unet_70.h5?dl=0

```
import segmentation_models as sm
from keras.models import load_model
from tensorflow import keras
import tensorflow as tf


path_to_model = "models/unet_70.h5"
loss = sm.losses.binary_focal_dice_loss
model = load_model(path_to_model, custom_objects={'binary_focal_loss_plus_dice_loss': loss})

model.save('model')

```

**Comment by ravikyram** [comment]
@MyJumperBroke23 

I have tried in colab with TF version 2.2 and i am seeing the below error message.(`OSError: Unable to open file (truncated file: eof = 7340032, sblock->base_addr = 0, stored_eof = 122058928`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/15a8e1bfe466b7c38ec35b25e1db8c87/untitled46.ipynb).Thanks!

**Comment by MyJumperBroke23** [comment]
@ravikyram Edited it so that the model loads

https://colab.research.google.com/gist/ravikyram/15a8e1bfe466b7c38ec35b25e1db8c87/untitled46.ipynb#scrollTo=5-zR-zsAWHRU

**Comment by nikitamaia** [comment]
Hi @MyJumperBroke23, model.save only creates a directory with assets, saved_model.pb, and variables when you are saving to **TF SavedModel format**. As you are saving to the **H5 format**, all you will see is the standalone model file. See [this section of the doc](https://www.tensorflow.org/guide/keras/save_and_serialize#whole-model_saving_loading) for more detail.

Since the TF SavedModel format is the default when using model.save(), you can try saving the model to a filename that does not end in .h5.

Additionally it looks like you are using a combination of keras and tf.keras? You probably want to change your second import so that everything is consistent:
` from tensorflow.keras.models import load_model `

**Comment by MyJumperBroke23** [comment]
@nikitamaia Hi, my model.save call doesn't end in .h5, the file I'm loading the model from is a h5 file. I'm using 

`model.save('model')`

I use keras.models instead of tensorflow.keras.models, because when I use tensorflow.keras.models I get an error importing my model due to a custom layer

**Comment by nikitamaia** [comment]
Ahh I see, okay in that case I wonder if the custom layer is causing the problem and that would be the first thing to try and fix so you can import with tf.keras. Similar issue here [#26835](https://github.com/tensorflow/tensorflow/issues/26835)

**Comment by MyJumperBroke23** [comment]
@nikitamaia that fixed it. Thanks.

**Comment by nikitamaia** [comment]
Glad to hear it! Closing now since a fix was found.
