### ISSUE TITLE
Use header include directories auto-detected from host compiler

### ISSUE THREAD

**Issue by davidzchen** [tensorflow/tensorflow#4058]
As mentioned by @akors in #2109 and #3980, we should generate `cxx_builtin_include_directory` entries for the header include directories used by the user's host compiler of choice rather than hard-coding them as we are currently doing.

**Comment by akors** [comment]
@davidzchen @martinwicke 
I'm not quite sure why this issue (and all other issues) has been closed, because the problem still clearly persists, even in the latest HEAD.

In case you have trouble reproducing, here's a reminder:

1) Install Ubuntu 16.04.1 LTS
2) Install the CUDA Toolkit version 8.0
3) Prepare compiler:
```
sudo apt-get install build-essential
sudo apt install libgmp-dev libmpfr-dev libmpc-dev
wget https://ftp.gnu.org/pub/gnu/gcc/gcc-5.3.0/gcc-5.3.0.tar.bz2
tar -xjf gcc-5.3.0.tar.bz2
cd gcc-5.3.0
./configure --prefix=/opt/gcc-5.3 --disable-nls --enable-languages=c,c++ --with-ld=/bin/ld --with-nm=/bin/nm --with-as=/usr/bin/as
make -j 8
sudo make install
```

4) Install bazel

5)
```
git clone https://github.com/tensorflow/tensorflow
cd tensorflow
./configure
bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
```


Should I create yet another GitHub Issue that describes the same problem? Or do I have to accept that smooth building is not a priority and using a custom compiler is "unsupported" and requires hacking template files?


It's not that I want to make your life difficult (please, you're very welcome to direct me to a way to build TensorFlow from source without all the hassle).

It's just most people using TensorFlow don't have Google build server magic available.
Everyone using a Linux Operating system (which should be quite a few, shouldn't it?) and wanting to use GPU acceleration needs:
 - The CUDA toolkit, which
 - needs a **specific** GCC version (4.9 or 5.3 for CUDA 7.5 or 8.0, respectively), which is usually 
 - **not** available from the distribution sources, which 
 - **requires** you to build it from source, which causes
 - TensorFlow to not work out of the box which is 
 - very hard to understand for me

Is using Ubuntu (which is the most popular linux distribution) or Fedora or CentOS really such a crazy/exotic configuration that it's not worth smoothing out the build from source?
Do really none of the devs use this setup? Is it really all just Macbooks and build servers over there?

Please guys, whoever is working on the build system, just try to perform this seemingly simple task:

Build TensorFlow from source and run it with GPU acceleration on Ubuntu 16.0.4.1 LTS.

**Comment by martinwicke** [comment]
No worries. I was traveling and was just going through the notification emails now. Your updated comment was a nice surprise! :)
