### ISSUE TITLE
random in tf.data.Dataset.map is not random if not coming from tensorflow

### ISSUE THREAD

**Issue by Wirg** [tensorflow/tensorflow#40620]
**System information**
== check os platform ===============================================
os: Linux
os kernel version: #53~18.04.1-Ubuntu SMP Thu Jun 4 14:58:26 UTC 2020
os release version: 5.3.0-59-generic
os platform: Linux-5.3.0-59-generic-x86_64-with-Ubuntu-18.04-bionic
linux distribution: ('Ubuntu', '18.04', 'bionic')
linux os distribution: ('Ubuntu', '18.04', 'bionic')
mac version: ('', ('', '', ''), '')

== check python ===================================================
python version: 3.6.9
python branch: 
python build version: ('default', 'Apr 18 2020 01:56:04')
python compiler version: GCC 8.4.0
python implementation: CPython

== compiler =====================================================
c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Copyright (C) 2017 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

== check pips ===================================================
numpy                   1.18.4
protobuf                3.12.2
tensorflow              2.1.1
tensorflow-addons       0.10.0
tensorflow-estimator    2.1.0

== tensorflow import ============================================
tf.version.VERSION = 2.1.1
tf.version.GIT_VERSION = v2.1.0-33-g3ffdb91
tf.version.COMPILER_VERSION = 7.3.1 20180303

**Standalone code to reproduce the issue**

```python
import tensorflow as tf
import numpy as np
import random as rd

dataset = (
    tf.data.Dataset.from_tensor_slices((np.arange(5)))
    .map(lambda annotation: (rd.random(), np.random.rand(), tf.random.uniform([])))
)

for el in dataset:
    print(el)
```

**Describe the current behavior**
The value for every element of the dataset is the same for python or numpy based random, but not for tensorflow based random.

**Describe the expected behavior**
The value for tf, np, python (...)-based randomness is a new random value for every dataset element.
Or a warning / error to avoid falling into this trap and debugging.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.1, [TF v.2.2](https://colab.research.google.com/gist/amahendrakar/7a8ad34fd0bceb98fdd35669f7f24e94/40620-2-2.ipynb) and [TF-nightly](https://colab.research.google.com/gist/amahendrakar/3216528f7a297d5b932263356b452898/40620-tf-nightly.ipynb). Please find the attached gist. Thanks!

**Comment by aaudiber** [comment]
This happens because functions passed to tf.data transformations are traced and converted to tensorflow graphs for execution in C++. During tracing, `rd.random()` and `np.random.rand()` get evaluated into constants (since tensorflow doesn't have hooks to detect these methods being called, like it does for tensorflow ops). The easiest way to work around this is to stick with tensorflow ops. Another option is to wrap non-tensorflow code in [tf.py_function](https://www.tensorflow.org/api_docs/python/tf/py_function), which executes arbitrary python code as a tensorflow op (with the caveat that this requires grabbing the GIL and generally results in worse performance compared to the equivalent tensorflow ops).

I agree that it's too easy to get an unpleasant surprise from using non-tensorflow ops in tf.data functions. @Wirg, do you think there is anywhere that we could improve the documentation that would have helped you here? Some places that we could add discussion of tracing:
- Top-level `tf.data.Dataset` doc: https://www.tensorflow.org/api_docs/python/tf/data/Dataset
- Individual `tf.data.Dataset` transformations that take a function argument, e.g. https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map. The `map` doc does currently say that the function will be traced, but it is buried in the detailed section of the doc, and not mentioned in the short description of the function argument.
- In the tf.data guide: https://www.tensorflow.org/guide/data

**Comment by Wirg** [comment]
Hi @aaudiber,

I understand the inerant complexity. Thanks for the explanation.

I think a warning the tf.data guide and in the map function dcos should be enough.

Sorry for the long time without answer.

**Comment by winthropharvey** [comment]
> 
@aaudiber
If I want to convert a numpy random op to a tensorflow op, but still need to use the result as a regular number or numpy int, how can I do this?  For example, I want to use the following random cropping code to crop an image and calculate the center shift.  It works with numpy, but of course if used in or as a map function it always generates the same shift which is unwanted behavior.  Trying to use the tensorflow equivalent op produces the desired different random number each time, but I can not get it to run without an error due to its use later when cropping the image using numpy slicing.  I can not simply use .numpy() as a method either as it will not run unless the code is executing eagerly.  

Note: I already have the code running correctly using tf.py_function, but I am wondering if there is a way to use tensorflow random ops and therefore get the code to run without py_function and get some performance gains.  

`def random_crop_single(img, random_crop_size, img_real_size, is_valid = False):
    # Note: image_data_format is 'channel_last'
    #print("IMAGE SHAPE" , img.shape)
    assert img.shape[2] == 3
    height, width = img.shape[0], img.shape[1]

    dy, dx = random_crop_size
    #Choose a random point in the valid area to be the new location, then crop
    if not is_valid:
        x = np.random.randint(0, width - dx + 1)
        #y = tf.experimental.numpy.random.randint(0 , height - dy + 1, dtype=np.int)
        #tf.print("y", int(y), output_stream=sys.stderr)
        y = np.random.randint(0, height - dy + 1)
        #y = int(y)

    else:
        x = 0
        y = 0
    #Second and third return values are the x and y adjustments for labels (unscaled)
    return img[ y:(y+dy), x:(x+dx), :], (float(x) / img.shape[1]) * img_real_size, (float(y) / img.shape[0]) * img_real_size`
