### ISSUE TITLE
ValueError: return statements are not supported within a TensorFlow loop.

### ISSUE THREAD

**Issue by sayakpaul** [tensorflow/tensorflow#40714]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.2.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**

When using return statements within for loops TensorFlow raises the error aforementioned in the issue title. 

**Describe the expected behavior**

A workaround. As this behavior is unknown to me. 

**Standalone code to reproduce the issue**

[Colab Notebook](https://colab.research.google.com/gist/sayakpaul/a069acdb369b25f48dd3844b4f701855/scratchpad.ipynb)

**Other info / logs** 

**Update**
When retrieving the dataset just register here: http://www.fki.inf.unibe.ch/databases/iam-handwriting-database. It won't take more than 40 seconds. Once registered, one can update username and the password in the `wget` fields.

**Comment by jpodivin** [comment]
As per the [docs]( https://www.tensorflow.org/api_docs/python/tf/data/Dataset#map) the map function doesn't support arbitrary python code because it converts everything into graph. In order to run something more complex you need to use [tf.py_function](https://www.tensorflow.org/api_docs/python/tf/py_function).

However, I think that this kind of task is better suited for different approach entirely. It would be much simple to process labels before you create the Dataset. You could, for example, use numpy or pandas.

Same goes for IO operations, unless you are limited by memory.

**Comment by sayakpaul** [comment]
> As per the docs the map function doesn't support arbitrary python code

This section (https://www.tensorflow.org/tutorials/load_data/images#load_using_tfdata) showcases otherwise, though. Sorry if my understanding is wrong. 


> However, I think that this kind of task is better suited for different approach entirely. It would be much simple to process labels before you create the Dataset. You could, for example, use numpy or pandas.

Any supporting minimal code snippet?

**Comment by jpodivin** [comment]
In some cases Tensorflow can handle the code yes, but only if it can find appropriate graph representation for it. The problem stems from question of what can you define as computational graph. Think about it as if you were compiling a code for a virtual machine.

Your code, in this case label processing, is taken by AutoGraph, which acts as a compiler, and it tries it's best to figure out how to make it work. But it's not perfect and sometimes has just no idea how to do it. So it fails. That being said, it can work and does work most of the time. But you still should consider alternatives. Speaking of alternatives...

Both numpy and pandas have a map (and map like) functions, and both libraries have lots of examples. The great thing is that they use same data structures as tensorflow, multidimensional arrays (Pandas builds on numpy). The only question is, which one is more to your liking. 

Pandas works better with more complex data. It can read JSON or csv, and work with it straight away. Data processing and even basic plotting included. 

Numpy is for low level stuff, obviously the numerical data, but you can work with other things too. Although instead of map function it has vectorize which works in similar way, while offering better performance. 

In general you want the right tool for the right job. Tensorflow offers lot of functionality but it isn't always consistent in quality. 

[Pandas map](https://pandas.pydata.org/docs/reference/api/pandas.Series.map.html?highlight=map)

[Numpy vectorize](https://numpy.org/doc/stable/reference/generated/numpy.vectorize.html)

[There's also a handy article about their performance, again with examples.](https://stackoverflow.com/questions/35215161/most-efficient-way-to-map-function-over-numpy-array)

**Comment by sayakpaul** [comment]
Fair points. 

Here's a bit more context as to why I would like to stick to `tf.data`. With a `tf.data.Dataset`abstraction I can avail some performance specific utilities such as [`prefetch`](https://www.tensorflow.org/api_docs/python/tf/data/Dataset#prefetch).

**Comment by Saduf2019** [comment]
@sayakpaul 
Please share all dependencies for us to rpelicate the issue faced, please find [the gist](https://colab.research.google.com/gist/Saduf2019/bc75fa9f584a62f522d67f6f3eecde4d/untitled243.ipynb) of the code shared.

**Comment by sayakpaul** [comment]
@Saduf2019 please take a look at the updated description. You did not pass the right username and password. I mentioned it in the updated issue, could you check it once and retry?

**Comment by bhack** [comment]
The third party dataset changed. 
Also I think that we need to find a small test gist to reproduce this. Having a registration dependency and a quite large datasets as input, it doesn't help to monitor this.
