### ISSUE TITLE
relatively slower performance on FCN

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#4072]
according to the paper http://arxiv.org/abs/1608.07249,
TensorFlow is good at CNN and RNN, however relatively slower on FCN, is this because of using python loop to feed data each mini-batch? Can we solve this since FCN is always important in general use of Deep Learning like competitions in kaggle.

![image](https://cloud.githubusercontent.com/assets/11470826/18024624/9230e594-6c41-11e6-989e-f5a7ba9e927f.png)

![image](https://cloud.githubusercontent.com/assets/11470826/18024628/9e3ad430-6c41-11e6-91b9-89347dabc1ce.png)

![image](https://cloud.githubusercontent.com/assets/11470826/18024630/b0d5abd8-6c41-11e6-8584-877b5fa45d88.png)

**Comment by poxvoculi** [comment]
We are very interested in improving TF performance on the kinds of models users care about. 

For the models in this paper it seems unlikely that python overhead for initiating each minibatch is a major factor.  It's more likely that the performance differences are primarily due to the efficiency of the kernels in use for the expensive operations (matmul, for FCN), and the degree to which operator fusion is applied to compile away the overhead of launching individual ops, and save on memory bandwidth.   I notice that in the chart you posted, TF's relative performance is best for CPUs with lots of cores, which corresponds to the kind of CPU platform used at Google.  I'm a little surprised at the cited relatively poor performance for FCNs on GPUs, given that the paper claims all systems are using cuDNN.  

In the future we intend to apply operator fusion more widely and continue to improve the kernel libraries used.

**Comment by drpngx** [comment]
@fayeshine you could try `tf.while_loop` and the latest XLA compiler. Closing for now since it's been a while and it's not clear how the new code still behaves. Feel free to reopen.
