### ISSUE TITLE
Import .tflite model into Tensorflow graph

### ISSUE THREAD

**Issue by krafczyk** [tensorflow/tensorflow#40721]
**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): No (Don't have expertise to do it..)

**Describe the feature and the current behavior/state.**
I'd like to be able to import a .tflite model as a 'node' within a tensorflow graph. This would allow people to download published .tflite models, add pre/post processing nodes to the graph, then re-export the graph to .tflite again. This should allow the user to adapt published models to their use case, moving certain common pre/post processing actions on-GPU or other compute device.

To my knowledge, it is not currently possible to 're-import' a .tflite model into a tensorflow graph.

**Will this change the current api? How?**
Yes, a function will need to be added to tf.Graph to support importation of .tflite files. I could also see a function taking a tf.lite.Interpreter object which has the .tflite model in question loaded.

Concrete suggestions:
* `tf.graph_util.import_tflite(model_path=None)`
* `tf.graph_util.import_tflite(interpreter=None)`

**Who will benefit with this feature?**
All tensorflow-lite users will likely benefit. Folks publishing models will find their models will be easier to use and so more folks will download them. Folks trying to use published models will find they can add additional pre/post processing on-GPU or other compute device, making the published models more easily accessible. In some cases, this can skip re-training complex networks when versions which already work well have been published, but with perhaps not the right expected input dimensions, or not the right output format.

**Any Other info.**
None at this time.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
