### ISSUE TITLE
kronecker product

### ISSUE THREAD

**Issue by ZhiwenZong** [tensorflow/tensorflow#40747]
Doesn't it have a function of kronecker product like np.kron in numpy?

**Comment by ravikyram** [comment]
@ZhiwenZong 

Can you please go through this [link](https://www.tensorflow.org/api_docs/python/tf/linalg/LinearOperatorKronecker) and see if it helps you.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
