### ISSUE TITLE
how to convert frozen graph (.pb and .pbtxt) model into quantized edge.tflite model 

### ISSUE THREAD

**Issue by MevadaRavikumar** [tensorflow/tensorflow#40764]
I have created one object detection model (.pb and .pbtxt) using 'faster_rcnn_inception_v2_coco_2018_01_28' model I found from TensorFlow zoo. It works fine on windows but I want to use this model on google coral edge TPU. How can I convert my frozen model into edgetpu.tflite quantized model?

**Comment by amahendrakar** [comment]
@MevadaRavikumar,
Please take a look at [this](https://coral.ai/docs/edgetpu/compiler/#download) Edge TPU Compiler guide to convert your tflite model  to Edge TPU compatible format. 

Also, this question is better asked on [StackOverflow](https://stackoverflow.com/questions/ask) since it is not a TensorFlow bug or feature request. There is a larger community that reads questions there. Thanks!
