### ISSUE TITLE
How can I enable aws during running configure?

### ISSUE THREAD

**Issue by ibrahimLearning** [tensorflow/tensorflow#40820]
@tensorflower-gardener @gunan 
Environment:
Ubuntu 16.04
python 3.6
bazel 0.26.0

I built tensorflow 1.14 from source. I want to enable aws, but I did not find anyway.
How can I enable it?

**Comment by amahendrakar** [comment]
> I built tensorflow 1.14 from source. I want to enable aws, but I did not find anyway.
> How can I enable it?

@ibrahimLearning,
Could you please elaborate the issue you are facing or the use case you're trying to implement. Thanks!

**Comment by mihaimaruseac** [comment]
Unfortunately 1.14 was not properly released. Can you attempt 1.15 instead?

Also, what do you mean by enabling AWS? S3 filesystem?

**Comment by ibrahimLearning** [comment]
> what do you mean by enabling AWS? S3 filesystem?

I just want this:
Do you wish to build TensorFlow with Amazon AWS Platform support? [Y/n]: Y
Amazon AWS Platform support will be enabled for TensorFlow.

but I did not find this, during TF1.14 installation.

**Comment by mihaimaruseac** [comment]
The exact question as specified in that snippet has been introduced in `tensorlfow==1.10`:

https://github.com/tensorflow/tensorflow/blob/4dcfddc5d12018a5a0fdca652b9221ed95e9eb23/configure.py#L1468-L1469

And got removed by the time `tensorflow==1.12` got released.

They got removed in https://github.com/tensorflow/tensorflow/commit/d56c298f1ef14b5a738e1e0b7bbc66fcd736be3e#diff-ade1d3e4b7c35655f854151d899df62b and since then these filesystems are enabled by default if supported by the operating system.

**Comment by gunan** [comment]
Closing issue, as AWS is now default enabled, except on windows.
On windows, I don't think our AWS or GCP support ever worked.
