### ISSUE TITLE
Incorrect TF nightly version

### ISSUE THREAD

**Issue by AjayReyo** [tensorflow/tensorflow#40827]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): pip
- TensorFlow version: 2.3
- Python version: 3.6
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source): 
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
`pip install tf-nightly` installs TF v2.5. Shouldn't it be TF v2.3???

PyPI link - https://pypi.org/project/tf-nightly-gpu/2.5.0.dev20200626/

**Provide the exact sequence of commands / steps that you executed before running into the problem**
```
import tensorflow as tf
print(tf.__version__)
```
**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by jvishnuvardhan** [comment]
@AjayReyo Due to some simple mistake in the TF build code, `TF2.5` version ( https://pypi.org/project/tf-nightly-gpu/2.5.0.dev20200626/) was created. Correct version is adjusted back to `TF2.4dev` (https://pypi.org/project/tf-nightly/2.4.0.dev20200630/ ).

As next stable version is `TF2.3`, the `tf-nightly` is `TF2.4dev2020MMDD` (MM, DD- two digits for month and day respectively)


So if you run

```
import tensorflow as tf
print(tf.__version__)
```

The output will show correctly as `2.4.0-dev20200630`. Sorry for the confusion. Thanks!

Please close the issue if this was resolved for you. Thanks!

**Comment by mihaimaruseac** [comment]
This has been resolved.
