### ISSUE TITLE
using tf.GPUOptions in tf 2.x

### ISSUE THREAD

**Issue by glennford49** [tensorflow/tensorflow#40867]
what is the proper call for this in version of tensorflow 2.x ?
tf.GPUOptions(per_process_gpu_memory_fraction=0.3) # i used this with tf.compat.v1 , GPUOptions is not available in 2.x , can someone help me use my gpu cores without using gpuoptions ,coz i dont want to use compat v1

**Comment by ravikyram** [comment]
@glennford49 

Can you please go through the [link](https://www.tensorflow.org/guide/gpu#) and see if it helps you.This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
