### ISSUE TITLE
directory structure has changed

### ISSUE THREAD

**Issue by NotUserX** [tensorflow/tensorflow#40894]
This is a Codelabs doc bug

## URL(s) with the issue:
https://codelabs.developers.google.com/codelabs/recognize-flowers-with-tensorflow-on-android/#3

## Description of issue (what needs changing):
Change directory structure from
examples/lite/codelabs/flower_classification/start
to
examples/lite/codelabs/flower_classification/android/start

{Admittedly, a minor issue, but am I doing this right?}

**Comment by ravikyram** [comment]
@NotUserX 

It was moved out of tensorflow GitHub repository to a new repository on GitHub. Link to the new repository is [here](https://github.com/googlecodelabs/tools/issues). Please file an issue there so that it will be resolved faster. You could also raise a PR to update the docs in that repository. Thanks!
