### ISSUE TITLE
Process killed on tf.dynamic_partition

### ISSUE THREAD

**Issue by mijungk** [tensorflow/tensorflow#40905]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.2.0-rc4-8-g2b96f3662b 2.2.0
- Python version: 3.7.6
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
tf.dynamic_partition with a large `num_partitions` hangs while consuming lots of memory  and the process is killed after a while. 

**Describe the expected behavior**
I would expect a memory allocation warning message rather than a hang followed by the killed process.  

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```python
import tensorflow as tf

partitions = [0, 0, 1, 1, 0]
num_partitions = 100000000 
data = [10, 20, 30, 40, 50]

output = tf.dynamic_partition(data, partitions, num_partitions)
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.
```
Killed
```

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, cloab crashes after we run the code shared.

**Comment by rmothukuru** [comment]
Could reproduce the **crash** of **`Google Colab`** with **`Tensorflow Version 2.5`** and **`TF Nightly`**. Thanks!

**Comment by tilakrayal** [comment]
@mijungk,
I tried to execute the mentioned with the alternative range of values for 
`num_partitions = 100, 1000, 10000, 100000, 1000000, 10000000` 

and it was executed without any issue/error. But we observed that to execute the 
**num_partitions = 10000000** took longer than the other values. 

Whereas when I tried to execute with **num_partitions = 100000000**, the colab was crashed due to a memory issue which was intended for the large number of input values.  Kindly find the gist of it [here](https://colab.sandbox.google.com/gist/tilakrayal/e894bd11afa3aa5085a2bb8f5ecef3ad/untitled1017.ipynb). Thank you!

![Screenshot 2023-03-06 10 00 44 PM](https://user-images.githubusercontent.com/81610181/223171959-389eb157-4c18-4b32-8d16-e5c2916cacda.png)
