### ISSUE TITLE
Where is imgae_recognition_model.cc in image_recognition_experimental?

### ISSUE THREAD

**Issue by uf19414** [tensorflow/tensorflow#40900]
Sorry to bother. I would like to run the image recognition model by Keil but I could not find "image recognition model data".

Could you tell me where the document is?

Or could you tell me where I can find the tutorial about how to train this model?

**Comment by amahendrakar** [comment]
@uf19414,
Could you please provide more information about 'image recognition model by Keil' or provide any link about its description. Thanks!

**Comment by uf19414** [comment]
> @uf19414,
> Could you please provide more information about 'image recognition model by Keil' or provide any link about its description. Thanks!
![image](https://user-images.githubusercontent.com/61425756/86044895-ad84f080-ba42-11ea-9cf3-5263d3c414f5.png)

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/image_recognition_experimental

There is only "image_recognition_model.h" in this link.

I think there should be "image_recognition_model.cc" which is the data of image recogntion model in this link too.

Like “model.cc" and "model.h" in this link 

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech/micro_features

**Comment by jenselofsson** [comment]
The model is downloaded from [here](https://storage.googleapis.com/download.tensorflow.org/models/tflite/cifar_image_recognition_model_2020_05_27.zip) when running the make-command, due to it being too large to store in the git repository.

If you take a look in the [Makefile.inc ](https://github.com/tensorflow/tensorflow/blob/fe968502a9835afec951a669d64224e411746605/tensorflow/lite/micro/examples/image_recognition_experimental/Makefile.inc#L1) file in the example it downloads the IMAGE_RECOGNITION_MODEL_URL as specified [here](https://github.com/tensorflow/tensorflow/blob/fe968502a9835afec951a669d64224e411746605/tensorflow/lite/micro/tools/make/third_party_downloads.inc#L70). It then moves the downloaded .cc-file into the generated directory.
