### ISSUE TITLE
tf.keras.layers.Permute documentation is misleading, error messages even more so

### ISSUE THREAD

**Issue by alexpyattaev** [tensorflow/tensorflow#41123]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/layers/Permute

### Clear description

Permute layer is quite picky about its dims argument despite docs clearly saying 

`dims: Tuple of integers. Permutation pattern, does not include the samples dimension. Indexing starts at 1. For instance, (2, 1) permutes the first and second dimensions of the input. `

 It does not actually follow from this documentation that the dims input MUST have all the dimensions clearly listed without misses -  as per check actually present in the code:
``` python
   if sorted(dims) != list(range(1, len(dims) + 1)):
      raise ValueError(
          'Invalid permutation `dims` for Permute Layer: %s. '
          'The set of indices in `dims` must be consecutive and start from 1.' %
          (dims,))
```
The next hurdle is that the error message thrown by runtime is kind of inconsistent:

``` python
keras.layers.Permute((3, 2), input_shape=[30, 6, 8], name=f"Permute_layer")
>>> Invalid permutation `dims` for Permute Layer: (3, 2). The set of indices in `dims` must be consecutive and start from 1.
```
It does not say in the doc that the dims must start with 1, it just says indexing starts with 1! Ok now the user knows it must start with 1, but how does one actually get dimensions 2 and 3 swapped? At that point it's just a mess from there on.

### Suggest following changes:
to the docs: please make example use 3D tensor, rather than 2D. Then it would be clear that all dims must be listed, even if they are not to be permuted, e.g.
``` python
tmp = keras.layers.Permute((1, 3, 2), name=f"Permute_input")(tmp)
```

Another note that docs do not make is that the len(ndim) must match the  input_shape dimensions, which is however checked by the __init__, again possibly conflicting with the doc that says that input_shape can be whatever (clearly not whatever, it is coupled with ndim argument.

**Comment by Bhavay192** [comment]
Hey @MarkDaoust , is the issue stil open or have you resolved it?? Can you assign the issue to me please.

**Comment by MarkDaoust** [comment]
This page hasn't changes. You can give it a shot. The source for this page is here:

https://github.com/keras-team/keras/blob/master/keras/layers/core/permute.py

It might be sufficient to say that `dims` expects a **permutation** of the dimensions.

**Comment by Bhavay192** [comment]
Hey @MarkDaoust , thanks for assigning me this issue. Soo as stated in the issue, I just need to use a 3-D tensor example instead of a 2-D one right?? And also state that len(ndim) must match the input_shape dimensions right?? I'm just clarifying on this cause I'm new to this, soo need your help. Thanks

**Comment by MarkDaoust** [comment]
Yes, that sounds right.

**Comment by Bhavay192** [comment]
Okay I shall make a pull-request on it. Thanks

**Comment by Bhavay192** [comment]
Hey @MarkDaoust , I have understood the issue but the problem comes out here that what should I write in documentation?? How to change the documentation such that points are covered in that?? Please advice me some context and I shall definitely resolve this. Thanks

**Comment by Bhavay192** [comment]
Hey @MarkDaoust , are you there to help ??

**Comment by MarkDaoust** [comment]
Just putting a 3D example on the api-page would be a good start.

> Invalid permutation `dims` for Permute Layer: %s. The set of indices in `dims` must be consecutive and start from 1.

For the error message maybe something like this would help:

```
Invalid permutation `dims` for Permute Layer: %s. `dims` must be a permutation (reordering) of the input's axis ids, excluding the batch-dimension. To transpose a batch of tensors with shape `[batch, n, m]` pass `Permute([2,1])`.
```

And copy that to the description of the 'dims' argument.

**Comment by mohantym** [comment]
Hi @alexpyattaev @MarkDaoust !

Could you share your pointers on PR [#17390 ](https://github.com/keras-team/keras/pull/17390) . Updated documentation as per above [comment](https://github.com/tensorflow/tensorflow/issues/41123#issuecomment-991229661). 

Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by alexpyattaev** [comment]
I think the proposed change to docs does make it better. Sorry for not replying earlier I must have missed the notification. Though as I see the original PR can not move forward anyway...

**Comment by MarkDaoust** [comment]
This code has moved into the keras repo.
