### ISSUE TITLE
Support strings as a first-class input/output data type in Swift

### ISSUE THREAD

**Issue by martinx9** [tensorflow/tensorflow#41131]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2.0
- Are you willing to contribute it (Yes/No): Maybe if time/company policy permits.

**Describe the feature and the current behavior/state.**
Support strings as a first-class input/output data type in Swift. Currently only the several bool/int/float types are supported, per https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/experimental/swift/Sources/Tensor.swift

**Will this change the current api? How?**
Yes on the Swift language bindings

**Who will benefit with this feature?**
iOS/Swift developers

**Any Other info.**
Asked on the community group, and was redirected here to file this feature request. CC: @jdduke

**Comment by jdduke** [comment]
Thanks for the request, this feature is on our roadmap and we hope to make progress on it this quarter.

**Comment by pkgoogle** [comment]
Hi @yyoon, did we ever get around to this? Thanks.

**Comment by yyoon** [comment]
Not entirely sure, but it probably hasn't been addressed yet.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
