### ISSUE TITLE
Quantization instruction problem after training

### ISSUE THREAD

**Issue by LINYOUWEI0804** [tensorflow/tensorflow#41228]
I have a problem with the instruction [integer quantization after training] in the official website.
this code:

mnist_train, _ = tf.keras.datasets.mnist.load_data()
images = tf.cast(mnist_train[0], tf.float32) / 255.0
mnist_ds = tf.data.Dataset.from_tensor_slices((images)).batch(1)
def representative_data_gen():
  for input_value in mnist_ds.take(100):
    # Model has only one input so each data point has one element.
    yield [input_value]
converter.representative_dataset = representative_data_gen

My question is the fifth itinerary [for input_value in mnist_ds.take(100): ], if I use my own data set, do I need to change this part of mnist_ds.take? There is also a question 100 what does it mean?

**Comment by jvishnuvardhan** [comment]
@LINYOUWEI0804 Ye, if you use your own data, then you need to update that part of the code. We need representative dataset to accurately estimate dynamic range of activations. Please check [this page](https://www.tensorflow.org/lite/performance/post_training_integer_quant).

> Now, in order to create quantized values with an accurate dynamic range of activations, you need to provide a representative dataset. To support multiple inputs, each representative data point is a list and elements in the list are fed to the model according to their indices.

`100` in the code is to take 100 sets of training data and estimate statistics of the data to decide dynamic range of activations. 


Please close the issue if this was resolved for you. Please post any support related questions in Stackoverflow so that there is a big community to get help. Thanks!

**Comment by miaout17** [comment]
Thanks @jvishnuvardhan . 
It seems to me this is a usage question but not an issue, and it was fully answered. I'm closing this ticket.
