### ISSUE TITLE
The `**kwargs` in `tf.keras.Model` does not accept any argument

### ISSUE THREAD

**Issue by YingzhouLi** [tensorflow/tensorflow#41251]
The `**kwargs` in `tf.keras.Model` does not accept any argument.

I am writing derivative class of `tf.keras.Model`, namely `Foo` class, which would like to create an instance of another class `Boo`. Hence I would like to pass arguments of `Boo`, say `booarg`, together to the derived class constructor. However, since `**kwargs` in `tf.keras.Model` does not accept any argument, I have to filter out arguments by myself, which is complicated, especially when the argument list of `Boo` is long. A toy code is attached.

```python
import tensorflow as tf

class Boo():
    def __init__(self, booarg1, booarg2):
        print("Boo Class: ", booarg1)
        print("Boo Class: ", booarg2)

class FooModel(tf.keras.Model):
    def __init__(self, fooarg, **kwargs):
        super(FooModel, self).__init__(**kwargs)
        print("Foo Class: ", fooarg)
        boo = Boo(**kwargs)

foo = FooModel(fooarg=1, booarg1=2, booarg2=3)
```

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.2.0
- Python version: 3.8.2
- GCC/Compiler version (if compiling from source): 9.3.0

**Comment by Saduf2019** [comment]
@YingzhouLi 
Please refer to this issue with similar error and let us know of it helps.
[link](https://stackoverflow.com/questions/50830736/typeerror-keyword-argument-not-understood-data-format) [link1](url)

**Comment by YingzhouLi** [comment]
@Saduf2019 Upgrading Keras does not solve the issue.

**Comment by Saduf2019** [comment]
@YingzhouLi,
Changing the line `super(FooModel, self).__init__(**kwargs)` to `super().__init__()` seems to work.
Please check this [gist](https://colab.research.google.com/gist/amahendrakar/f8552954f37fb95561134076baeded24/41251.ipynb
) for reference.

Also, take a look at this relevant StackOverflow [comment](https://stackoverflow.com/a/7629620). Thanks!

**Comment by YingzhouLi** [comment]
@Saduf2019, that indeed works but not in the way I prefer.
I would like to wrap another layer around `tf.Model` and some parameters in `**kwargs` would be passed to `tf.Model` class, like, optimizer, etc.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/6d580bee8537ba3fce97691e0514fd82/untitled131.ipynb)..Thanks !

**Comment by hemantnyadav** [comment]
This real issue. I am also trying to extent the layer but it is not accepting anything in **kwargs with error TypeError: ('Keyword argument not understood:',

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF 2.11, Please find the gist [here](https://colab.research.google.com/gist/pjpratik/4d6b2d8cdb7ad06ff8ace27122a1d1cb/41251.ipynb). Thank you.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
