### ISSUE TITLE
User defined color in tf.image.resize_with_crop_or_pad

### ISSUE THREAD

**Issue by ClementWalter** [tensorflow/tensorflow#41272]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tf 2.2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently, the `tf.image.resize_with_crop_or_pad` ops pads with 0. It would be helpful to be able to give another value because in some application black is not the right color for padding (it messes with real data).

**Will this change the current api? How?**

Adding a kwarg padding_color Union[int, iterable] with:
 - int, a value to be used on all channels (currently 0)
 - iterable: with len(iterable) == number of channel to describe any rgb color

Example of how to achieve the expected result currently:

```
        output_tensor = tf.image.resize_with_crop_or_pad(input_tensor, 450, 450)
        padding = (1 - tf.image.resize_with_crop_or_pad(tf.ones_like(input_tensor), 450, 450)) * tf.constant(
            [255, 0, 255], dtype=tf.uint8
        )
        output_tensor += padding
```

**Who will benefit with this feature?**

Users who need to pad images with another color because black is not suitable for their dataset

**Any Other info.**

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
