### ISSUE TITLE
python program spitting out a tensorflow error of "ImportError: DLL Load failed while importing" 

### ISSUE THREAD

**Issue by SugoiShades** [tensorflow/tensorflow#41314]
**System information**
- Windows 10 pro 64bit ver 2004
- TensorFlow version: 2.2.0
- Python version: 3.8.3
- Installed using PIP
- CUDA ver: 10.0
- GPU model and memory: NVIDIA GTX 1070 8GB
-My CPU does not support the AVX Instruction set

when attempting to use a python program, I am greeted with this error (Copied Verbatim below)
     (side note, I'm not great with python or most of the dev tools I've attempted to use to download all of the required libraries, so forgive me if this has a relatively simple solution.)

This occurs when I use the CMD prompt to execute the main.py file for this program. to do this, I typed this command
Python main.py
after a few moments the error is triggered. the prompt remains blank until the error traceback appears.
(I can give more specifics to the best of my ability, but this is all of the information that I am aware that I have to help diagnose)

(this is the entire error verbatim)

Error when importing libraries:  Traceback (most recent call last):
  File "G:\APPLICATIONS\Python\3.8.3\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "G:\APPLICATIONS\Python\3.8.3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "G:\APPLICATIONS\Python\3.8.3\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "G:\APPLICATIONS\Python\3.8.3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "G:\APPLICATIONS\Python\3.8.3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
Some Python libraries are missing. You can install all required libraries by running in the command line 'pip install -r requirements.txt'

**Comment by SugoiShades** [comment]
is there a way around using the 2.2.0 version of TF without the AVX instruction set? right now I just want to see this work, processing time and efficiency do not matter at the moment.

**Comment by ravikyram** [comment]
@SugoiShades 

What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the [latest microsoft visual c++ redistributable from here](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

**TensorFlow release binaries version 1.6 and higher are prebuilt with AVX instruction sets.**
Therefore on any CPU that does not have these instruction sets, either CPU or GPU version of TF will fail to load.

If your CPU model does not support AVX instruction sets. You can still use TensorFlow with the alternatives given below:

Try Google Colab to use TensorFlow.
The easiest way to use TF will be to switch to google colab. You get pre-installed latest stable TF version. Also you can use pip install to install any other preferred TF version.
It has an added advantage since you can you easily switch to different hardware accelerators
(cpu, gpu, tpu) as per the task.
All you need is a good internet connection and you are all set.
Try to build TF from sources by changing CPU optimization flags.
Thanks!

**Comment by SugoiShades** [comment]
@ravikyram My CPU Definitely doesn't support AVX (its a Core i7 980) I but you answered my question, thank you.

**Comment by ravikyram** [comment]
@SugoiShades 

Please, close this thread if your query has been answered.Thanks!

**Comment by ravikyram** [comment]
I am closing this issue  since the query has been answered. Thanks!
