### ISSUE TITLE
Differencing Time Series Data - How to Invert Differencing 

### ISSUE THREAD

**Issue by Tyson-Stur** [tensorflow/tensorflow#41326]
I am working with time series data (non-stationary), I have applied .diff(periods=n) for differencing the data to eliminate trends and seasonality factors from data. 

By using .diff(periods=n), the observation from the previous time step (t-1) is subtracted from the current observation (t).

Now I want to invert back the differenced data to its original scale, but I am having issues with that.

Original DataSet before differencing:

[![original dataset][1]][1]

My code for differencing and output:

    data_diff = df.diff(periods=1)     
    
    data_diff.head(5) 

[![output differenced data][2]][2]

Code for inverting data to original scale and output:

    cols = df.columns
    x = []
    for col in cols:
        diff_results = df[col] + data_diff[col].shift(-1)
        x.append(diff_results)
    diff_df_inverted = pd.concat(x, axis=1)
    
    diff_df_inverted

[![data inverted][3]][3]

As you can see from last output, I have successfully inverted my data back to its original scale. However, I do not get the inverted data for row 1. It inverts and shifts the values up a row. My question is, why? What am I missing?

Appreciate your help, thank you!

  [1]: https://i.stack.imgur.com/qMwCZ.png
  [2]: https://i.stack.imgur.com/Z5T6B.png
  [3]: https://i.stack.imgur.com/oCXj2.png

**Comment by ravikyram** [comment]
@Tyson-Stur 
This question is better asked on StackOverflow since it is not a bug or feature request related to Tensorflow. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by tc18fwd** [comment]
Here's a quick function that I defined to take in the differenced series and the first value of the original series that will return the original series. Copy and run the function below and run it. To have the function defined, then copy the codes near bottom to test and see.

def diff_inv(series_diff, first_value):
    series_inverted = np.r_[first_value, df_diff].cumsum().astype('float64)
    return series_inverted 

For a quick example to see how this works, let's make some a dataframe with random numbers and column A
Get its diff() as another dataframe
Then we can use the function to take the diferenced series, which is why it's df_diff.A, we're selecting that column, then input the first value of the original dataframe of that column. The function then returns the restored values in an array format.

df = pd.DataFrame({'A': np.random.randint(0, 10, 10)})
df_diff = df.diff().dropna()
df_restored = diff_inv(df_diff.A , df.A[0])
display(df)
df_restored
