### ISSUE TITLE
build problems found at runtime for CUDA related issue on laptop with no GPU

### ISSUE THREAD

**Issue by greencane** [tensorflow/tensorflow#41322]
**System information**
- Linux Ubuntu 20.04LTS
- HP Elitebook 820 G3, Intel® Core™ i7-6600U CPU @ 2.60GHz × 4.  8GB RAM installed
- TF installed in virtualenv with command "pip3 install tensorflow" and keras with "pip3 install keras"
- TensorFlow version: 2.2.0.  Keras version 2.4.2
- Python version: 3.8.2
- Installed using virtualenv? pip? conda?:  installed in virtualenv and used pip
- GPU model and memory:  No GPU, installed on laptop.  using Mesa Intel® HD Graphics 520 (SKL GT2)

**Describe the problem**
Build does not produce an error but fails at runtime, see attached log.  Suspect it is related to the building of tensorflow for this laptop without GPU card.

**Provide the exact sequence of commands / steps that you executed before running into the problem**
trying to train a CNN causes this error

**Any other info / logs**
see attached log file
[error_log.txt](https://github.com/tensorflow/tensorflow/files/4908576/error_log.txt)

**Comment by amahendrakar** [comment]
@greencane,
In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using.

Also, please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/32563#issuecomment-531977227) from a similar issue and let us know if it helps. Thanks!
