### ISSUE TITLE
Using HIP instead of CUDA (work on all graphics card)

### ISSUE THREAD

**Issue by labidus** [tensorflow/tensorflow#41360]
Since half of the developers can use an AMD card or an old NVIDIA card, if that append, you cannot use the GPU with CUDA.

**System information**
- TensorFlow version: ALL
- Are you willing to contribute it (Yes/No): YES

**Describe the feature and the current behavior/state.**

HIP is a C++ Runtime API and Kernel Language that allows developers to create portable applications for AMD and NVIDIA GPUs from single source code.

Key features include:

HIP is very thin and has little or no performance impact over coding directly in CUDA or hcc "HC" mode.
HIP allows coding in a single-source C++ programming language including features such as templates, C++11 lambdas, classes, namespaces, and more.
HIP allows developers to use the "best" development environment and tools on each target platform.

The HIPIFY tools automatically convert source from CUDA to HIP.
Developers can specialize for the platform (CUDA or hcc) to tune for performance or handle tricky cases
New projects can be developed directly in the portable HIP C++ language and can run on either NVIDIA or AMD platforms. 

Additionally, HIP provides porting tools which make it easy to port existing CUDA codes to the HIP layer, with no loss of performance as compared to the original CUDA application. HIP is not intended to be a drop-in replacement for CUDA, and developers should expect to do some manual coding and performance tuning work to complete the port.

[https://github.com/ROCm-Developer-Tools/HIP]

**Will this change the current api? How?** NO

**Who will benefit with this feature?** ALL

**Comment by David-Gan** [comment]
This is great!

**Comment by acxz** [comment]
You can already compile with HIP, see https://github.com/rocm-arch/tensorflow-rocm/blob/master/PKGBUILD as a reference installation guide.

I believe this issue can be closed,

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
