### ISSUE TITLE
Suggestions For Tensorflow v3

### ISSUE THREAD

**Issue by Tylersuard** [tensorflow/tensorflow#41525]
1.  Rebuild from scratch.  At this point there are too many errors, warnings, and old code to do anything about.  It might be an idea to streamline Tensorflow, by creating a new version with only the most important features, and then adding new ones.

2.  Make updates compatible with previous versions.  Do not change syntax used in previous versions.  For instance, any repository written for Tensorflow 3.2 should be completely compatible with Tensorflow 3.8 .  Currently, if a repository is written in Tensorflow and the version is not specifically mentioned by the repo's author, it is anyone's guess as to which specific version of Tensorflow 1 or 2 will work.  A repo written in Tensorflow 1.4 is completely incompatible with Tensorflow 1.5.  Can you imagine if Microsoft Word worked like this?  For every new version update, all your documents are now incompatible and have to be re-written?

3.  Fewer warnings.  When starting up Tensorflow, a full page of warnings appear.  I would be nice to not have these.

4.  Install correct version of Protoc automatically.  This will avoid the common error "ImportError: DLL load failed".

5.  If possible, automatically install the correct versions of Cuda and CUDNN.  The process can be long and fairly difficult.  Even better if this can be done inside a virtual environment so it does not affect the host system's settings.

6.  If tensorflow version is incorrect for the repository, give a hint as to which tensorflow version to install instead, and which commands to enter for that purpose.

7.  No more guessing games: more helpful error messages.  Take the most common stackoverflow errors with tensorflow, and add the solutions to the error messages received from Tensorflow.

8.  Coordinate more closely with Python.org, Nvidia, and other dependencies to ensure compatbility with new versions of Tensorflow.

9.  Make installation process on computers easier and more automatic.  "pip install tensorflow" should not install most recent version of Tensorflow, but should install the specific version of Tensorflow compatible with that particular distribution of Python, and compatible with that repository.  This could be accomplished through point #2, making all subsequent versions of Tensorflow compatible with previous versions.  To illustrate, a repository coded in Python 3.7 using Tensorflow 1.4, will not be able to run on Tensorflow 1.5.  It would be wonderful if any repository made in Tensorflow 3 could run on any version of Tensorflow 3: this could be possible by keeping the syntax and commands the same across all versions of Tensorflow 3, and adding features if necessary as the versions go on.

10.  I know you all are geniuses.  But the rest of us need a little help.  It might be an idea to simplify things as much as possible, and make running and installing Tensorflow so easy a child could do it.  Pytorch has been gaining traction over Tensorflow because it is just easier to use.  One helpful reddit thread: https://www.reddit.com/r/MachineLearning/comments/bo0nxh/d_what_are_you_using_tensorflow_vs_pytorch/

**Comment by mihaimaruseac** [comment]
Thank you for the suggestions. Note though that some are impossible to achieve due to technical reasons (depend on multiple CUDA versions), legal reasons (automatically bundle some dependencies) or process reasons (rewriting from scratch). Furthermore, some of the suggestions don't directly apply to TF (e.g., `pip` recommendation in 9. is likely something that needs to happen at the level of PyPI, assuming it would be possible).

We don't have any plans for v3 at the moment but we can extract some of these suggestions and take them into account for that time.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
