### ISSUE TITLE
tf.ragged.stack issue

### ISSUE THREAD

**Issue by ARozental** [tensorflow/tensorflow#41531]
tf.ragged.stack(input) return tf.Tensor if the first dim of the input is of length 1 and tf.RaggedTensor if not.
This is a problem as those types don't share the same interface and if the length of the input is not know in advance (as is often the case when using ragged tensors) one must have in "if" condition inside the graph to check the output type.

```
tf.ragged.stack([[1,2,3]]) => tf.Tensor([[1 2 3]], shape=(1, 3), dtype=int32)
tf.ragged.stack([[1,2,3],[1,2,3]]) =>  <tf.RaggedTensor [[1, 2, 3], [1, 2, 3]]>

```

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, 2.3-rc1, nightly version(`2.4.0-dev20200719`) and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/ca64601372cfa6fe3938590894ae5d51/untitled149.ipynb).Thanks!

**Comment by edloper** [comment]
`tf.ragged.stack`'s first argument is a list of tensors, not a single tensor.  And the length of that list is always known in advance (i.e., at graph-construction time).  So you don't need any conditional **inside** the graph here.  

In general, `RaggedTensor` operations return a `tf.Tensor` if it can statically determine that the result has no ragged dimensions.  This has some advantages in terms of efficiency (`Tensor` operations are sometimes more efficient than `RaggedTensor` ops) and flexibility (`tf.Tensor` supports more operations than `RaggedTensor`).  So this is working as intended.

That said, I agree that it's annoying to have an API that may return either a `Tensor` or a `RaggedTensor` since, as you point out, they have somewhat different interfaces.  This is a side-effect of the current `RaggedTensor` design, where ragged tensors are defined recursively, and you can't create a `RaggedTensor` with `rank<2`.  We have some thoughts about how `RaggedTensor` could be refactored to avoid this (so ragged ops and ops that take ragged inputs would always return a `RaggedTensor` object, even if the result has no ragged dimensions); but it's somewhat difficult to change in a backwards-compatible way.

For now, I think the best solution for your case may be to write something like the following:

```
x = tf.ragged.stack([[1,2,3]])
if isinstance(x, tf.Tensor):
  x = tf.RaggedTensor.from_tensor(x)
```

(Note that this will fail with a shape error if `x.shape.rank<2`, since `RaggedTensor` can currently only be used if `rank>=2`.  Also, depending on what you're doing downstream of this operation, you may want to explicitly specify `ragged_rank` when calling `from_tensor`.)
