### ISSUE TITLE
When dose Tensorflow add elasticity function in worker？

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#41589]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):1.15
- Are you willing to contribute it (Yes/No): with pleasure, but I'm a rookie.

**Describe the feature and the current behavior/state.**
We has lots of jobs and a set number of resource. We hope:
When resource is enough, jobs can add some workers to increase training speed.
When resource is lacking, jobs will delete some workers to release resource.

**Any Other info.**
Does Tensorflow have any plan on elasticity function, and when does TF support elasticity function in workers?

**Comment by nikitamaia** [comment]
Hi @zhaozheng09, for multiworker training this is not an out of the box feature we currently have in TF. And I don't know that it's a common use case for distributed training with ML training because of the consistent nature of the workload and because you might not always see a direct speedup simply by increasing the number of machines. But if possible my thought is it would probably work best with an asynchronous training strategy (eg [ParameterServer](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/ParameterServerStrategy)) and not a synchronous strategy where the GPUs are in sync at the end of each batch.

**Comment by zhaozheng09** [comment]
@nikitamaia, We use async training now.
We has a test that multi worker will speedup training(like y = log2x    x:worker nums, y:training speed), and our uesrs only use less worker, so dynamic add worker will has a good effect.
We hope TF auto add worker to speedup training when resource is enough.

**Comment by yuefengz** [comment]
If you will be using our TF 2 parameter server training (in the next release) and willing to contribute, I would be happy to help.

**Comment by zhaozheng09** [comment]
> If you will be using our TF 2 parameter server training (in the next release) and willing to contribute, I would be happy to help.

thx

**Comment by wojciechp6** [comment]
Hi @zhaozheng09. I have developed adding and removing workers "while in training". If you (or somebody else) are still interested in this feature you can contact me.

**Comment by wojciechp6** [comment]
Hi, for dynamic worker removing one change in Worker class is necessary. 
The change is here:
```python
class Worker:
  [...]
  def _process_queue(self):
    """Function running in a worker thread to process closure queues."""
    self._maybe_delay()
    while self._should_worker_thread_run:
      closure = self._cluster._closure_queue.get()  # pylint: disable=protected-access
      if not self._should_worker_thread_run or closure is None:
        if closure is not None:
          closure.mark_cancelled()
        return
      self._process_closure(closure)
      # To properly stop the worker and preemption threads, it is important that
      # `ClusterCoordinator` object is not held onto so its `__del__` can be
      # called. By removing the reference to the `closure` that has already been
      # processed, we ensure that the `closure` object is released, while
      # getting the next `closure` at above `self._cluster._closure_queue.get()`
      # call.
      del closure
  [...]
```

Could someone commit it? Thanks in advance.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
