### ISSUE TITLE
Unable to load graph from protobuf file on s390x arch (Big Endian)

### ISSUE THREAD

**Issue by Masquerade0097** [tensorflow/tensorflow#41652]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): IBM Z (s390x arch), Ubuntu 18.04.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Installed Tensorflow C lib from source
- TensorFlow version (use command below): 1.15.3
- Python version:
- Bazel version (if compiling from source): 0.26.1
- GCC/Compiler version (if compiling from source): 
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
I installed the TensorFlow C library on an s390x machine. Then tried to do inferencing using a pre-trained model, when I encountered the following error. I'm loading the model graph from a protobuf file.

```
INFO[0000]/root/gopros/src/github.com/rai-project/tensorflow/vendor/github.com/rai-project/dlframework/framework/register.go:76 github.com/rai-project/tensorflow/vendor/github.com/rai-project/dlframework/framework.Register() skipping regitration of hidden model          pkg=dlframework/framework name=SSD_MobileNet_v2_Quantized_300x300_COCO
INFO[0000] running predict urls                          model=MobileNet_v1_1.0_224 pkg=dlframework/framework/cmd/server
Error: unable to create tensorflow model graph: Invalid value in tensor used for shape: -385679360
```

**Describe the expected behavior**
Tensorflow should support the loading of model graphs in protobuf format on a big-endian machine.

**Standalone code to reproduce the issue**
I suspected the error is because the protobuf file for the model graph was originally created on little endian machine and I'm trying to load it on a big-endian machine. In order to confirm that the error is due to the loading of protobuf graph in Tensorflow, I tried out **[this](https://gist.github.com/asimshankar/7c9f8a9b04323e93bb217109da8c7ad2)** tutorial. Using this tutorial, I created a tensorflow model and saved it in protobuf format on an x86 system. When I loaded the graph file on an x86 system, it works but when I tried loading the graph on s390x system, I got the following error -

```
Loading graph
Read GraphDef of 27083 bytes
ERROR: Dimension 0 in both shapes must be equal, but are 1 and 16777216. Shapes are [1,1] and [16777216,16777216]. for 'dense/kernel/Assign' (op: 'Assign') with input shapes: [1,1], [16777216,16777216].
```

**Other info / logs**

The following tests are passing -
```
//tensorflow/c:c_api_test
//tensorflow/c:c_api_function_test
//tensorflow/c:c_test
//tensorflow/c:ops_test
//tensorflow/c:env_test
//tensorflow/c:c_test_util
//tensorflow/cc/saved_model:reader_test
//tensorflow/cc/saved_model:loader_test
```

**Comment by frreiss** [comment]
This problem stems from a design flaw in TensorFlow's internal data structures.

In `tensorflow/core/framework/tensor.cc`, the method `Tensor::FromProto(Allocator*, const TensorProto&)`  reads the `tensor_content` field out of the generated C++ class corresponding to a `TensorProto` message and copies the contents of that field directly into the target `Tensor` object's backing buffer:

```c++
929    if (!proto.tensor_content().empty()) {
930      const auto& content = proto.tensor_content();
931      CASES_WITH_DEFAULT(proto.dtype(), p = Helper<T>::Decode(a, content, N),
932                         dtype_error = true, dtype_error = true);
933    }
```
([direct link to file in git](https://github.com/tensorflow/tensorflow/blob/66b1247f10bf37a33e5c495eb1523e0895a04ae9/tensorflow/core/framework/tensor.cc#L929))

**The byte order of the `tensor_content` field is not defined.** The field was never intended to be used for on-disk serialization; see the comment [here](https://github.com/tensorflow/tensorflow/blob/f5fb417ebc18485b7e2493e766d658da539f007c/tensorflow/core/framework/tensor.proto#L35).  However, many different parts of TensorFlow currently store raw binary data in the `tensor_content` field, mostly for reasons of convenience.

The `Tensor` class also contains a method `Tensor::AsProtoTensorContent()` that writes the contents of the tensor's buffer directly into the `tensor_content` field of a `TensorProto` message.  One of these places that calls this method is `Input::AsTensorProto()` (see `tensorflow/cc/framework/ops.h`, line 182):

```c++
182    TensorProto AsTensorProto() {
183      TensorProto tensor_proto;
184      if (tensor.NumElements() > 1) {
185        tensor.AsProtoTensorContent(&tensor_proto);
186      } [...]
```
([direct link to file in git](https://github.com/tensorflow/tensorflow/blob/50caa9d728973399d8b5860dfb5c3a1748bfaf2f/tensorflow/cc/framework/ops.h#L182))

As a result of this code and others like it, `TensorProto` protocol buffer messages embedded inside `AttrValue` messages embedded inside `NodeDef` messages embedded inside `FunctionDef` messages embedded inside `FunctionDefLibrary` messages embedded inside `GraphDef` messages embedded inside `MetaGraphDef` messages embedded inside `SavedModel` messages embedded inside the `saved_model.pb` file inside of the root directory of a SavedModel sometimes contain raw binary data in the byte order of the host that produced the SavedModel.

Fixing this problem will be complicated.

I don't think that tracking down all the places that abuse the `tensor_content` field is an option.  Modifying `Tensor::FromProto()` is likewise not an option, as there is no way to tell what is the byte order of a `TensorProto`'s `tensor_content` field at that point in the code.

The best fix I can think of would be to modify the Python code `tf.saved_model.load()` so that, when run on big-endian machines, that code will byte-swap the `tensor_content` fields of any `TensorProto` messages reachable from a traversal of the contents of the SaveModel's `saved_model.pb` file.

This change would also require adding similar byte-swapping functionality to `tf.saved_model.save()`. Otherwise, big-endian machines would not be able to import SavedModels that they themselves wrote.

**Comment by Masquerade0097** [comment]
@frreiss Thank you for looking into the issue.

@jvishnuvardhan Is the TensorFlow team planning to work on it?

**Comment by rposts** [comment]
@frreiss I am running into similar issue on s390x with `TF serving` when it tries to serve models saved on x86 containing `TensorProto` serialized data.  I modified `tf.saved_model.save()` code on s390x as you indicated and it was able to store date in LE format.  Predictably, it failed to load the model on s390x as the bytes were now swapped.

I am currently investigating if `tensor_content` can be modified right after `ReadMetaGraphDefFromSavedModel` is loaded by [loader.cc](https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/cc/saved_model/loader.cc#L316).  Since `TF Serving` does not appear to call Python `tf.saved_model.load()` directly, any changes made there may not be picked up during model load.

Another issue I see here is that any models that were generated on s390x prior to  `tf.saved_model.save()` modifications will now fail as there is no way of determining endiness of the model.  I wonder if endiness information can be stored somewhere in  the `MetaGraph`?  The changes made by this [PR](https://github.com/tensorflow/tensorflow/pull/28490) appear to address `tensor bundles` only.

I am still figuring out aspects of save/load so may be missing few key steps.

Let me know your thoughts.

Thanks.

**Comment by frreiss** [comment]
Thanks for sharing that pointer to `loader.cc`, @rposts . It looks like there's a second, C++-only code path for loading SavedModels from non-Python applications, and that this second code path isn't currently reachable from the Python API but is TF Serving's primary way of loading models. I suspect that other languages beyond Python (Java in particular) are probably also exercising that C++-only loading code.

This C++ code path will also need to be updated to byte-swap tensors on loading. The change will be similar in nature to what I described above for the Python code. There is most like a parallel C++-only code path for writing SavedModels that will need some byte-swapping inserted.

The good news here is that byte-swapping routines are already present on the C++ code base, at `tensorflow/core/util/tensor_bundle/byte_swap.cc`. The functions in that file would need to be moved to a different directory to be callable from `loader.cc`, but I don't think they would need to change at all.

If you need a short-term workaround, my colleagues at IBM have built a utility that byte-swaps the tensors in a SavedModel's serialized protocol buffers file.

**Comment by tensorflowbutler** [comment]
Hi There,

 We are checking to see if you still need help on this, as you are using an older version of tensorflow which is officially considered end of life . We recommend that you upgrade to the latest 2.x version and let us know if the issue still persists in newer versions. Please open a new issue for any help you need against 2.x, and we will get you the right help. 

 This issue will be closed automatically 7 days from now. If you still need help with this issue, please provide us with more information.
