### ISSUE TITLE
ImportError: cannot import name py_checkpoint_reader

### ISSUE THREAD

**Issue by yuyuyuyuyu1234** [tensorflow/tensorflow#41691]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by amahendrakar** [comment]
@yuyuyuyuyu1234,
In order to expedite the trouble-shooting process, please provide the exact sequence of commands / steps that you executed before running into the problem.

Also, please take a look at [this comment](https://github.com/tensorflow/tensorflow/issues/36609#issuecomment-590000208) from a similar issue and let us know if it helps. Thanks!
