### ISSUE TITLE
Question mark (?) in the model image using plot_model instead of None

### ISSUE THREAD

**Issue by V2dha** [tensorflow/tensorflow#41744]
I am using the tf.keras.utils.plot_model function to plot the model. The code is given below. Now instead of getting None for the batch sizes I am getting question mark (?). So can you please address why this is happening and how I can replace None inplace of ? question mark.

tf.keras.utils.plot_model(
    model,
    to_file='model2.png',
    show_shapes=True,
    show_layer_names=True
)

![model image](https://user-images.githubusercontent.com/50369708/88482269-d9ca5900-cf7d-11ea-8a0b-7150d4b056e1.png)

**Comment by jpodivin** [comment]
What you see there is caused by this line in keras utils:
https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/utils/vis_utils.py#L183

It's actually the desired behavior. 
My understanding is that the None sized dimensions are effectively variable sized, or unknown '?' when the graph is compiled. 
Therefore tensor with other dimensions matching can fit. Notice how output shape of a layer and the input shape of the following layer always matches. 

Now you could replace the '?' string with 'None' string, but what would it be good for? It wouldn't make it any more readable.

**Comment by V2dha** [comment]
> What you see there is caused by this line in keras utils:
> https://github.com/tensorflow/tensorflow/blob/2b96f3662bd776e277f86997659e61046b56c315/tensorflow/python/keras/utils/vis_utils.py#L183
> 
> It's actually the desired behavior.
> My understanding is that the None sized dimensions are effectively variable sized, or unknown '?' when the graph is compiled.
> Therefore tensor with other dimensions matching can fit. Notice how output shape of a layer and the input shape of the following layer always matches.
> 
> Now you could replace the '?' string with 'None' string, but what would it be good for? It wouldn't make it any more readable.

Actually I am working on a research paper in which I need the image of the model architecture although it wouldn't make it any more readable from a programmer's point of view but from a layman's understanding it would atleast come out to be a tad bit readable as the '?' mark signifies as if there's an error or something is missing where as None kind of explains that I voluntary didn't add the batch sizes.

**Comment by jpodivin** [comment]
Worst case scenario you can add an explanatory footnote.

**Comment by ravikyram** [comment]
@V2dha 

It is expected behavior.Please, see this [tutorial](https://www.tensorflow.org/tutorials/images/segmentation), [link](https://www.tensorflow.org/api_docs/python/tf/keras/utils/plot_model) for your reference.Thanks!

**Comment by V2dha** [comment]
Okay thanks!
