### ISSUE TITLE
can we convert back tflite model to keras h5 format?

### ISSUE THREAD

**Issue by feiwofeifeixiaowo** [tensorflow/tensorflow#41771]
hi there, thanks for this powerful tool.
can we convert back tflite model to keras h5 format?
i find a solution [here](https://stackoverflow.com/questions/59559289/is-there-any-way-to-convert-the-tflite-file-back-to-keash5), but the weight in bn layer in tflite is null, how can we convert back this?

**Comment by ravikyram** [comment]
@feiwofeifeixiaowo 

I think there is no way to convert tflite model to keras h5 format as some information will be lost after conversion.

Can you refer the [link](https://stackoverflow.com/questions/53664279/converting-tflite-to-pb) and see if it helps you.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by feiwofeifeixiaowo** [comment]
ok, thanks.
