### ISSUE TITLE
TensorFlow 2.2 using tf.float16 executes only on CPU

### ISSUE THREAD

**Issue by aleksandarPlu** [tensorflow/tensorflow#41783]
I'm using [this code](https://github.com/vcadillog/PPO-Mario-Bros-Tensorflow-2) as a starting point for one of my projects. The only modification I did so far is switching to OpenAI Gym Atari because I'm running it on Windows.

The problem I'm having is when I use tf.keras.backend.set_floatx(tf.float16) the code gets stuck executing on CPU. I also changed all the explicit casts throughout the code. The idea is to utilize the tensor cores on my GPU. This only happens with this code. All my other projects work fine.

I'm running it on TF 2.2. I tried removing tf.function annotations. I tried messing around with casts. For example, leaving all the data in fp32 and using fp16 weights in the model. Nothing helped. Honestly, I haven't tried much because I can't find any information on the problem and have no idea where to start debugging. There are no errors and everything works fine, except it runs on CPU instead of GPU. The only difference is in the mess that TF spews out when initializing I get this message:

`W tensorflow/compiler/jit/xla_device.cc:398] XLA_GPU and XLA_CPU devices are deprecated and will be removed in subsequent releases. Instead, use either @tf.function(experimental_compile=True) for must-compile semantics, or run with TF_XLA_FLAGS=--tf_xla_auto_jit=2 for auto-clustering best-effort compilation.`

I tried both options proposed in the message and nothing happened.

Also, I have tried [tf.device](https://www.tensorflow.org/api_docs/python/tf/device) but nothing changed

I really need this to work. Not just for the memory and performance optimizations but part of my project is benchmarking the difference between the two.

Any help would be appreciated or at least if someone could point me in the direction where to look for the information.

Thank you.

**Comment by ravikyram** [comment]
@aleksandarPlu 

Request you to fill [issue template.](https://github.com/tensorflow/tensorflow/issues/new/choose).
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version.
Request you to share simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster.Thanks!

**Comment by aleksandarPlu** [comment]
@ravikyram 

Thanks for you reply. All other project are working fine, except this one. Unable to create any simpler version to reproduce this issue.
Platform details are:  TF 2.2, Win 10 (1909), nVidia driver 451.67, CUDA 10.1, Python 3.7, i7-4770k, RTX 2060 Super

**Comment by gowthamkpr** [comment]
@aleksandarPlu Can you try using `tf.keras.mixed_precision.experimental.set_policy('mixed_float16')` This might help you to speed up training by 3 times on a modern GPU as mentioned [here](https://www.tensorflow.org/guide/mixed_precision#overview)

**Comment by aleksandarPlu** [comment]
@gowthamkpr thank you for your suggestion. Now at least was able to run the code on tf16 with your proposed solution. But we did not get any improvement in speed or memory. It is the same as when I used tf32

**Comment by gowthamkpr** [comment]
@aleksandarPlu Glad you were able to run the code with proposed solution. As mentioned in the comment, it might help you speed up training but I didn't promise it would. 

As mentioned [here](https://www.tensorflow.org/guide/mixed_precision#overview), NVIDIA GPUs can run operations in float16 faster than in float32. Therefore, these lower-precision dtypes should be used whenever possible on those devices. However, variables and a few computations should still be in float32 for numeric reasons so that the model trains to the same quality. The Keras mixed precision API allows you to use a mix of either float16 or bfloat16 with float32, to get the performance benefits from float16/bfloat16 and the numeric stability benefits from float32.

Some ops are performed on CPU but not on GPU, this might be the reason for not seeing any change in speed.

Moreover, As this issue is not a bug pr feature request can you please post this in stack overflow where community can help you. Thanks!
