### ISSUE TITLE
S3 ParseURI supporting query parameters

### ISSUE THREAD

**Issue by mjnovice** [tensorflow/tensorflow#41798]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Currently, when I pass query parameters as a part of my request to `TFRecordDataset`  the query becomes a part of the object name. For example:
```
filenames = ["s3://bucketname/path/to/file1.tfrecord?uuid=<UUID>",
             "s3://bucketname/path/to/file2.tfrecord?uuid=<UUID>"]
dataset = tf.data.TFRecordDataset(filenames)
```
On the server-side, we then see `path/to/file1.tfrecord?uuid=<UUID>` as the path with the `query params` as empty which should not be the case, as `?` is a query param delimiter and should be treated as such.

**Will this change the current api? How?**

No. But it will eliminate the need for a hack on the storage side to parse/strip URL query from object names. Thus, it will enhance TensorFlow <=> Cloud storage integration - which is a good thing.

**Who will benefit with this feature?**

People who run TensorFlow against datasets hosted by Object/Cloud storages. In our case, we are a team at NVIDIA, working on the open-source https://github.com/NVIDIA/aistore where TensorFlow is one of the critical client apps that we want to support.

It will be of great help, as the feature would be free of hacks.

**Any Other info.**

**Comment by aaudiber** [comment]
I think this support would be implemented by modifying [s3_file_system.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/s3/s3_file_system.cc), as opposed to making a change within `TFRecordDataset`. Reassigning to Mihai, who is more familiar with the filesystem level.

**Comment by mihaimaruseac** [comment]
I agree with Andrew, this is an issue in the current implementation. I'll take a look at this in ~1 week or so, unfortunately I cannot before. However, PRs are welcome, if you can get a fix earlier.

**Comment by mjnovice** [comment]
Adding additional information. I think tensorflow is dependent on the [aws-sdk-cpp](https://github.com/aws/aws-sdk-cpp) and the sdk doesn't support sending custom query parameters. https://sdk.amazonaws.com/cpp/api/LATEST/class_aws_1_1_transfer_1_1_transfer_manager.html#a4c1aec774f4338acee2fd8d90ed052eb Think it makes more sense to raise an issue there ?

**Comment by mjnovice** [comment]
@mihaimaruseac any comments you would have ?

**Comment by mihaimaruseac** [comment]
Let's raise the issue to aws-sdk-cpp repo. TF could add a layer to strip the query parameters in the AWS filesystem too, if you want to send a PR. But I think it's better to raose the issue to the sdk first.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
