### ISSUE TITLE
TFLu r2.3: Broken memory allocation for micro interpreter object with TF_LITE_STATIC_MEMORY enabled

### ISSUE THREAD

**Issue by ml-0** [tensorflow/tensorflow#41900]
Compiling TFLu r2.3 with TF_LITE_STATIC_MEMORY gives an incorrect memory allocation for the micro interpreter object. 

**System information**
- TFLu r2.3
- OS Platform: Linux Ubuntu 16.04 or Windows 10 64 bit
- Target: Cortex M4F

**Current behavior**
In my case the size of the network input data is
interpreter->input(0)->bytes = 1920

After calling for memory allocation
TfLiteStatus allocate_status = interpreter->AllocateTensors();

the memory address of the input data is
interpreter->input(0)->data = 0x8012174
and memory address of the input tensor structure is
interpreter->input(0) = 0x8012570

This gives only 1020 bytes memory space for the data which is 1920 btes. As a consequence, the input tensor structure is overwritten when copying the input data.

**Expected behavior**
After removing TF_LITE_STATIC_MEMORY from the CCFLAGS/CXXFLAGS the memory allocation leaves enough space between the data and the input tensor structure:
interpreter->input(0) = 0x80124d0
interpreter->input(0)->data = 0x80103c0

**Other info**
Using TFLu r2.2 with TF_LITE_STATIC_MEMORY does not show the problem. It gives correct memory layout. Starting with commit fbf407383c93774d10bd7c45cd66788a070b0e07 (mid of June '20) the memory layout is broken.

I'm not sure if this is a bug or if it is intended behavior and I better compile without TF_LITE_STATIC_MEMORY.

**Comment by njeffrie** [comment]
It looks like this may be related to some of our memory optimization efforts. I have filed an internal bug to track this and will update when we have a resolution.

**Comment by ml-0** [comment]
Thx for looking into this. As indicated in my bug description, temporary workarounds are
- using r2.2
- using r2.3 without TF_LITE_STATIC_MEMORY in the CCFLAGS/CXXFLAGS

**Comment by advaitjain** [comment]
This is a case of our making changes that are not backwards compatible coupled with the fact that Tensorflow Lite Micro doesn't currently conform to the release cadence of the broader Tensorflow project.

My recommendation here is to use TFLM from source. Since we no longer support using TFLM without TF_LITE_STATIC_MEMORY (and have thus made it the default in our Makefile).

I'm going to close the current issue but please open a new one if you are seeing issues when building from source.

**Comment by ml-0** [comment]
What do you mean by "use TFLM from source"? I did not modify any source code or Makefile except for adding a make target for Cortex-M4F. I observe the problem when TF_LITE_STATIC_MEMORY is specified (which is the default). I observe it with r2.3 and with HEAD of master (Sept. 2020).

**Comment by ml-0** [comment]
I just found the reason for the observation on my side: the application project includes header files from TFLM to instantiate the interpreter. I missed to define TF_LITE_STATIC_MEMORY when including such header files.

Is not a bug in TFLM.

**Comment by COTASPAR** [comment]
@ml-0 Hi, I'm experiencing a similar issue. Could you clarify which header files you are referring to? thanks in advanced.

**Comment by advaitjain** [comment]
I think what @ml-0 is referring to is that any external code that includes TFLM headers should be built with `-DTF_LITE_STATIC_MEMORY`, or have a `#define TF_LITE_STATIC_MEMORY` before the headers are included.

Apologies for not being very clear with my previous reply - what I was emphasizing is that using TFLM without TF_LITE_STATIC_MEMORY defined isn't really supported anymore, even on x86.

**Comment by ml-0** [comment]
Hi @COTASPAR, my application project comes with its own Makefile (not part of TFLM) and links against the libtensorflow_microlite .a. To instantiate the TFLM interpreter I have to include
```
#include "tensorflow/lite/micro/kernels/micro_ops.h"
#include "tensorflow/lite/micro/all_ops_resolver.h"
#include "tensorflow/lite/micro/micro_error_reporter.h"
#include "tensorflow/lite/micro/micro_interpreter.h"
#include "tensorflow/lite/version.h" 
#include "tensorflow/lite/c/common.h"
```
As the last include (common.h) heavily uses TF_LITE_STATIC_MEMORY this macro has to be defined in the application project as well. If not, the application uses a different definition for TfLiteTensor as the library does.

This problem does not appear in all the examples that come with TFLM because they compile TFLM + the example code with the same settings (single Makefile).

@advaitjain Do you see the chance to avoid such problems by inverting the definition of TF_LITE_STATIC_MEMORY? The code we should use does not require it has to be defined only for special purposes?

**Comment by advaitjain** [comment]
Unfortunate as it is, its best to use TFLM with  TF_LITE_STATIC_MEMORY. It has basically become a way to separate the TFLM build graph from the TfLite build graph.

Without this define, the performance is degraded due to allocations of TfLiteTensors from the temp space at each Eval. More importantly, its not a path that we test or support anymore so there can definitely be bugs.

We would like to get to a point where TFLM does not need this additional define at all, but the code sharing with TfLite (via common.h as you pointed out and more) makes it something that will take some time to disentangle.
