### ISSUE TITLE
CNN convolution neural network problem

### ISSUE THREAD

**Issue by lvjinqiao** [tensorflow/tensorflow#41992]
Why do we define the weights of CNN convolutions neural networks with normal distribution，is it because of the central limit theorem？

**Comment by ravikyram** [comment]
@lvjinqiao 

Can you please go through the [link](https://www.deeplearning.ai/ai-notes/initialization/) , [link2](https://towardsdatascience.com/weight-initialization-in-neural-networks-a-journey-from-the-basics-to-kaiming-954fb9b47c79) and see if it helps you.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
