### ISSUE TITLE
Unable to create a pip whl. 

### ISSUE THREAD

**Issue by tCubed** [tensorflow/tensorflow#4199]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

https://github.com/tensorflow/tensorflow/issues/2040

### Environment info
Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

-rw-r--r-- 1 root root  189170 Dec 23  2015 /usr/local/cuda/lib/libcudadevrt.a
lrwxrwxrwx 1 root root      16 Dec 23  2015 /usr/local/cuda/lib/libcudart.so -> libcudart.so.7.5
lrwxrwxrwx 1 root root      19 Dec 23  2015 /usr/local/cuda/lib/libcudart.so.7.5 -> libcudart.so.7.5.18
-rwxr-xr-x 1 root root  311596 Dec 23  2015 /usr/local/cuda/lib/libcudart.so.7.5.18
-rw-r--r-- 1 root root  558020 Dec 23  2015 /usr/local/cuda/lib/libcudart_static.a
lrwxrwxrwx 1 root root      17 Dec 23  2015 /usr/local/cuda/lib/libcuinj32.so -> libcuinj32.so.7.5
lrwxrwxrwx 1 root root      20 Dec 23  2015 /usr/local/cuda/lib/libcuinj32.so.7.5 -> libcuinj32.so.7.5.18
-rwxr-xr-x 1 root root 5396088 Dec 23  2015 /usr/local/cuda/lib/libcuinj32.so.7.5.18

If installed from source, provide 
1. The commit hash (`git rev-parse HEAD`)

9b69ec3960cf9225df557fdc1ab673bd36bde4fb

2. The output of `bazel version`

Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jan 01 00:00:00 1970 (0)
Build timestamp: Thu Jan 01 00:00:00 1970 (0)
Build timestamp as int: 0

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)

Quite simply, I am going through the instructions here(https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#create-the-pip-package-and-install), and get the following error:

tc:/deeplearning/tensorflow$ bazel-bin/tensorflow/tools/pip_package/build_pip_package.sh /tmp/tensorflow_pkg
bash: bazel-bin/tensorflow/tools/pip_package/build_pip_package.sh: No such file or directory

### What other attempted solutions have you tried?
The fix from here (https://github.com/tensorflow/tensorflow/issues/2040), which was to do: cp -r bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/__main__/* bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles/

seemed to run properly, but this did not work in the end.

**Comment by tatatodd** [comment]
I tried to reproduce and ended up with a different error with 9b69ec3960cf9225df557fdc1ab673bd36bde4fb checked out, but don't see errors on the latest 0.10 release.

In general I would recommend using an official release, rather than an arbitrary commit.  FYI the 9b69ec3 commit was on June 6.

Here are instructions on downloading a binary distribution:
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#download-and-setup

For source installs, you can use the `git clone -b` flag to pick a branch.  E.g. the following will clone the latest 0.10 release:
```
$ git clone -b v0.10.0rc0 https://github.com/tensorflow/tensorflow
```

Hope this helps!  Please re-open if you still encounter issues on an official release.
