### ISSUE TITLE
Dataset sharding in MultiWorker Mirrored Strategy

### ISSUE THREAD

**Issue by iamhassaan** [tensorflow/tensorflow#42146]
Hi, I am relatively new to distributed TensorFlow. I am running a custom CIFAR10 training code from tensorflow website on 2 Azure VMs. I have made key-less ssh connections between them and have set up TF_CONFIG. My training completes successfully. I just want to know, how CIFAR10 data is getting sharded in my code. First it mentions that it is switching to DATA and then it says it cannot find a shardable source but still it proceeds to train my code. A surprising thing is that with all these errors with sharding in my cluster, my training completes more swiftly as compared to getting trained in a single VM. The logs tell that it cannot shard my code, if this is so, why am I getting a speed increase in training, despite dataset not getting sharded? Please help.

**ERROR:**

. Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.
 You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via.

And then :

2020-08-01 16:29:05.556918: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:521] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_39847"
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
. 

### **System information**

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version: 3.5.2
- Bazel version (if compiling from source):
- 2 CPU only machines : Azure D2s V3 (2 cores, 8gb ram)
-Tensorflow 2.2

**Standalone code to reproduce the issue**

```
`from` __future__ import absolute_import, division, print_function, unicode_literals
import tensorflow as tf
import os	
import json 	

from tensorflow.keras import datasets, layers, models
import matplotlib.pyplot as plt

strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()

(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()


train_images, test_images = train_images / 255.0, test_images / 255.0

class_names = ['airplane', 'automobile', 'bird', 'cat', 'deer',
               'dog', 'frog', 'horse', 'ship', 'truck']

plt.figure(figsize=(10,10))
for i in range(25):
    plt.subplot(5,5,i+1)
    plt.xticks([])
    plt.yticks([])
    plt.grid(False)
    plt.imshow(train_images[i], cmap=plt.cm.binary)
    # The CIFAR labels happen to be arrays, 
    # which is why you need the extra index
    plt.xlabel(class_names[train_labels[i][0]])
plt.show()

with strategy.scope():

	model = models.Sequential()
	model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(32, 32, 3)))
	model.add(layers.MaxPooling2D((2, 2)))
	model.add(layers.Conv2D(64, (3, 3), activation='relu'))
	model.add(layers.MaxPooling2D((2, 2)))
	model.add(layers.Conv2D(64, (3, 3), activation='relu'))


#model.summary()


	model.add(layers.Flatten())
	model.add(layers.Dense(64, activation='relu'))
	model.add(layers.Dense(10))

	model.compile(optimizer='adam',
	              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
	              metrics=['accuracy'])

history = model.fit(train_images, train_labels, epochs=10, 
                    validation_data=(test_images, test_labels))

plt.plot(history.history['accuracy'], label='accuracy')
plt.plot(history.history['val_accuracy'], label = 'val_accuracy')
plt.xlabel('Epoch')
plt.ylabel('Accuracy')
plt.ylim([0.5, 1])
plt.legend(loc='lower right')

test_loss, test_acc = model.evaluate(test_images,  test_labels, verbose=2)




`print(test_acc)`
```

****### ** FULL LOGS******

2020-08-01 16:22:46.425007: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-08-01 16:22:46.425047: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
2020-08-01 16:22:47.497587: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory
2020-08-01 16:22:47.497633: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-08-01 16:22:47.497673: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (instance1): /proc/driver/nvidia/version does not exist
2020-08-01 16:22:47.497969: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-08-01 16:22:47.505592: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2593905000 Hz
2020-08-01 16:22:47.505762: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5a13560 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-01 16:22:47.505844: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-01 16:22:47.513007: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.0.0.4:12345, 1 -> 10.0.0.5:12345}
2020-08-01 16:22:47.513233: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:405] Started server with target: grpc://10.0.0.4:12345
WARNING:tensorflow:`eval_fn` is not passed in. The `worker_fn` will be used if an "evaluator" task exists in the cluster.
WARNING:tensorflow:`eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
2020-08-01 16:22:49.618955: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 614400000 exceeds 10% of free system memory.
2020-08-01 16:22:49.916264: W tensorflow/core/framework/cpu_allocator_impl.cc:81] Allocation of 614400000 exceeds 10% of free system memory.
2020-08-01 16:22:50.285604: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:521] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_244"
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
. Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.
Epoch 1/10
WARNING:tensorflow:From /home/iamhassaan/venv/lib/python3.7/site-packages/tensorflow/python/data/ops/multi_device_iterator_ops.py:601: get_next_as_optional (from tensorflow.python.data.ops.iterator_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.data.Iterator.get_next_as_optional()` instead.
1561/1563 [============================>.] - ETA: 0s - loss: 1.5020 - accuracy: 0.45262020-08-01 16:23:27.691909: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:521] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_4289"
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
. Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `1563/1563 [==============================] - 38s 25ms/step - loss: 1.5017 - accuracy: 0.4527 - val_loss: 1.2870 - val_accuracy: 0.5304
Epoch 2/10
1563/1563 [==============================] - 37s 24ms/step - loss: 1.1390 - accuracy: 0.5970 - val_loss: 1.0820 - val_accuracy: 0.6155
Epoch 3/10
1563/1563 [==============================] - 37s 24ms/step - loss: 0.9962 - accuracy: 0.6510 - val_loss: 0.9849 - val_accuracy: 0.6546
Epoch 4/10
1563/1563 [==============================] - 37s 24ms/step - loss: 0.8935 - accuracy: 0.6890 - val_loss: 0.9642 - val_accuracy: 0.6618
Epoch 5/10
1563/1563 [==============================] - 37s 24ms/step - loss: 0.8244 - accuracy: 0.7117 - val_loss: 0.9134 - val_accuracy: 0.6870
Epoch 6/10
1563/1563 [==============================] - 37s 24ms/step - loss: 0.7653 - accuracy: 0.7351 - val_loss: 0.8816 - val_accuracy: 0.6953
Epoch 7/10
1563/1563 [==============================] - 37s 24ms/step - loss: 0.7151 - accuracy: 0.7497 - val_loss: 0.8829 - val_accuracy: 0.6986
Epoch 8/10
1563/1563 [==============================] - 37s 24ms/step - loss: 0.6721 - accuracy: 0.7656 - val_loss: 0.9168 - val_accuracy: 0.6910
Epoch 9/10
1563/1563 [==============================] - 37s 24ms/step - loss: 0.6250 - accuracy: 0.7830 - val_loss: 0.9076 - val_accuracy: 0.7012
Epoch 10/10
1563/1563 [==============================] - 37s 24ms/step - loss: 0.5895 - accuracy: 0.7968 - val_loss: 0.9148 - val_accuracy: 0.7039
WARNING:tensorflow:`eval_fn` is not passed in. The `worker_fn` will be used if an "evaluator" task exists in the cluster.
WARNING:tensorflow:`eval_strategy` is not passed in. No distribution strategy will be used for evaluation.
2020-08-01 16:29:05.556918: W tensorflow/core/grappler/optimizers/data/auto_shard.cc:521] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Did not find a shardable source, walked to a node which is not a dataset: name: "FlatMapDataset/_9"
op: "FlatMapDataset"
input: "PrefetchDataset/_8"
attr {
  key: "Targuments"
  value {
    list {
    }
  }
}
attr {
  key: "f"
  value {
    func {
      name: "__inference_Dataset_flat_map_slice_batch_indices_39847"
    }
  }
}
attr {
  key: "output_shapes"
  value {
    list {
      shape {
        dim {
          size: -1
        }
      }
    }
  }
}
attr {
  key: "output_types"
  value {
    list {
      type: DT_INT64
    }
  }
}
. Consider either turning off auto-sharding or switching the auto_shard_policy to DATA to shard this dataset. You can do this by creating a new `tf.data.Options()` object then setting `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` before applying the options object to the dataset via `dataset.with_options(options)`.
313/313 - 3s - loss: 0.9148 - accuracy: 0.7039
0.7038999795913696

**Comment by nikitamaia** [comment]
Hi @iamhassaan, I agree the logs here are a bit confusing. tf.distribute autoshards the input dataset in multi worker training in one of three ways: `AUTO`, `FILE`, `DATA`. By default the `tf.data.experimental.AutoShardPolicy` is set to `AUTO`, which will  first attempt to shard by `FILE` (the assumption here is that if you're doing multi worker training, you probably have a large dataset spread across a number of files, and not something you can easily load into memory). The attempt to shard by FILE fails if a file-based dataset is not detected. tf.distribute will then fall back to sharding by `DATA`. If you scroll to the Sharding section and look for the `DATA` section of the [distributed input guide here](https://www.tensorflow.org/tutorials/distribute/input#tfdistributestrategyexperimental_distribute_dataset), you'll find a little more detail on how the sharding happens in the `DATA` case. 

So to summarize, for your case that warning you're seeing is just that `AUTO` does not detect files and is switching to `DATA`. But each worker is still processing different data on each step and that's why your training completes successfully (and faster) despite the messages you've reported. If you follow the suggestion in the message to set `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA` [(docs here) ](https://www.tensorflow.org/api_docs/python/tf/data/experimental/DistributeOptions) then I don't think you'll see this warning anymore. In general, working with a tf.data.Dataset is suggested when doing multi worker training. The datasets in Keras load data into numpy arrays, which I suspect is why you're seeing the message `walked to a node which is not a dataset`

Hope this helps clear up any confusion!

**Comment by iamhassaan** [comment]
Thank you so much for the detailed response. While running the experiment I was aware regarding usage of tf.distribute api.

 I have tried setting ```
options.experimental_distribute.auto_shard_policy = AutoShardPolicy.AUTO to 
options.experimental_distribute.auto_shard_policy = AutoShardPolicy.DATA
```, I have even tried changing it to `options.experimental_distribute.auto_shard_policy = AutoShardPolicy.OFF`.  But I get the same logs. Even the performance doesnot change at all after changing it from `.DATA to .OFF` (I experimented this with Mnist dataset). I was getting a speed increase as compared to running jobs in one machine only but changing auto shard policy from .Data to .OFF did not seem to make a difference at all on the cluster I was working on. I got the same training time and both methods produced this error `walked to a node which is not a dataset`. 

As you mentioned in the above answer Keras loads data into numpy arrays, are you sure that splitting NumPy arrays (datasets) is supported in tf.distribute?

By doing several experiments on the API, I think toy datasets are not sharded by tf.distribute regardless of auto_shard_policy.  But computation efficiency is increased since there are 2 machines working to process each batch rather than just 1 machine ? Especially in the cases of toy datasets (numpy, cifar10) ? I will really appreciate your response. Thanks.

**Comment by nikitamaia** [comment]
To clarify, you have to use use a `tf.data.Dataset` in order to set the policy. If you haven't converted your numpy data into a tf.data.Dataset, you can't set the policy so you'll still see the messages. When I converted your numpy arrays to a tf.data.Dataset, and set the DATA policy, the message goes away. 

```
strategy = tf.distribute.experimental.MultiWorkerMirroredStrategy()
options = tf.data.Options()
options.experimental_distribute.auto_shard_policy = tf.data.experimental.AutoShardPolicy.DATA
(train_images, train_labels), (test_images, test_labels) = datasets.cifar10.load_data()
train_images, test_images = train_images / 255.0, test_images / 255.0
train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_dataset = train_dataset.with_options(options)
train_dataset = train_dataset.batch(32)
```

The `walked to a node which is not a dataset` you're seeing is also because you're passing in a numpy array and not a tf.data.Dataset.

As for the behavior of numpy arrays, I believe they get sharded but not really a common use case. Generally with multi worker training you use tf.data so you can efficiently pipeline the data. Let me do some investigation on the behavior with numpy arrays.

**Comment by iamhassaan** [comment]
Thank you so much Nikita, I tried your snippet of code. I am really happy that it managed to clear the verbose logs. Please let me know if you are sure whether numpy arrays get sharded or not?  I replicated your code with Numpy dataset. I got rid of messages. But I cannot see any speedup in training? It is almost the same. I used a global batch size of 32000. I utilized two workers. In my first experiment I turned of data sharding to `.OFF` . In the second experiment I turned data sharding to `.DATA` . The training time stays the same. Will really appreciate any final clarifications.

Also please let me know how I can set an eval_strategy. As there is one last warning:  `tensorflow:`eval_strategy` is not passed in. No distribution strategy will be used for evaluation. You can then close this :). Thank you for your time
`

**Comment by nikitamaia** [comment]
Under the hood, keras `model.fit` converts numpy arrays to a `tf.data.dataset`. This happens regardless of whether you're using a distribution strategy or not. So the behavior should be same if you pass numpy data or a `tf.data.dataset`. The benefit of converting your data to a `tf.data.dataset` first before passing to `model.fit` is that you can add additional transformations to make your input pipeline more efficient, which would help speed your training up if your program is input bound ([more details here](https://www.tensorflow.org/guide/data_performance)). If your batch size stays the same then I would expect the time for a step on each machine to be equivalent for the`.DATA` and `.OFF` sharding because both machines are still processing `GLOBAL_BATCH_SIZE//2` amount of data in each step for both cases. However, in the `.DATA` case the data is different on each machine. So I don't think you should expect a speed up in the time per step, but `.DATA` should converge faster since different data is being seen on both machines. The difference might not be too noticible because your model and dataset are not too large.

As for the eval_strategy, that warning is a little confusing unfortunately. It's a legacy warning that has to do with the eval_strategy when using an estimator. A change has just been submitted so that warning should not exist in future versions. You can ignore the warning for now. if you are using `model.fit` then the same distribution strategy will be used for evaluation when you pass in a validation dataset. `MultiWorkerMirroredStrategy` is still in experimental, so as we move it out of experimental some of these confusing warnings will also be removed.

**Comment by nikitamaia** [comment]
Hi @aginpatrick, seems to be related to #45157. That thread is about `train_on_batch` but I think the same applies for `predict_on_batch`.

**Comment by aginpatrick** [comment]
Oh I see @nikitamaia, thank you so much for your support. I understand that there is nothing to do except ignore this warning right? It's very annoying because in my case I'm training with Google AI Platform and the logs are literally overwhelmed by the multiple outputs of this warning and it's then very difficult to see my "real" logs. Anyway, thanks again for your excellent explanations.

**Comment by nikitamaia** [comment]
Happy to help! 
You'll have to ignore the warning for now. I think longterm it would make sense to set the autopolicy to DATA for train and predict on batch, which would get rid of the warning, but I suspect that won't be prioritized any time soon. If anything changes, I'll keep these threads updated.

**Comment by sandeepsinghsengar** [comment]
Hi @nikitamaia thanks for your valuable comments. I am also getting the same error/warning: tensorflow/core/grappler/optimizers/data/auto_shard.cc:656] In AUTO-mode, and switching to DATA-based sharding, instead of FILE-based sharding as we cannot find appropriate reader dataset op(s) to shard. Error: Found an unsharable source dataset: name: "TensorDataset/_1"

You told to ignore this warning right? but due to this warning computation speed is very slow. I am working on 3D MRI dataset. Please suggest to improve computational speed. Thanks

**Comment by artiumd** [comment]
Hi @nikitamaia

I am getting the same warning, however, I am using instances of ``tf.keras.utils.Sequence`` subclasses to train and validate my model using ``model.fit()``.

What would be the recommended solution? I could in principle wrap my sequences in ``tf.data.Dataset`` objects, but the problem is that the ``on_epoch_end()`` method of my ``tf.keras.utils.Sequence`` subclass will not be called.

Should I infer from this that ``tf.keras.utils.Sequence`` will be deprecated in the future? or at least deprecated in the case of distributed training?

Thanks.

**Comment by nikitamaia** [comment]
With MultiWorkerMirroredStrategy, there are two ways to shard data. Either by FILE, or by DATA. As the name suggests, the FILE policy only works when your data is in files (eg TF Records). If your data is not file based, then you must shard by the DATA policy. This is explained in the [Sharding section of the Distributed Input guide.](https://www.tensorflow.org/tutorials/distribute/input#tfdistributestrategyexperimental_distribute_dataset) There are pros and cons of each policy, and you can see that explained more in detail in the guide.

If you are seeing this warning it means that you have not set an autoshardpolicy. That is okay! The default AUTO policy is smart enough to pick the correct policy for you (either FILE or DATA).[ You can see here in the code](https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/core/grappler/optimizers/data/auto_shard.cc#L652), that if the defult AUTO Policy is on, it will first try to `ShardByFile`. if your data is not file based, it will issue this warning you are seeing and then `ShardByData`. 
```
    case AutoShardPolicy::AUTO:
    default:
      Status s = ShardByFile(*sink_node, num_workers, index, &flib, &graph);
      if (errors::IsNotFound(s)) {
        LOG(WARNING) << "In AUTO-mode, and switching to DATA-based sharding, "
                        "instead of FILE-based sharding as we cannot find "
                        "appropriate reader dataset op(s) to shard. Error: "
                     << s.error_message();
        return ShardByData(*sink_node, num_workers, index, num_replicas,
                           &graph);
```

The end result is equivalent as to if you had explicitly set the policy to DATA, which is also easily seen a [few lines earlier in the code](https://github.com/tensorflow/tensorflow/blob/r2.4/tensorflow/core/grappler/optimizers/data/auto_shard.cc#L649). Whether you set the policy yourself or use the default AUTO policy, if you do not have file based data then the policy will `ShardByData`
```
    case AutoShardPolicy::DATA:
      return ShardByData(*sink_node, num_workers, index, num_replicas, &graph);
```

If you're having performance issues, it is not directly because of this warning. If your data is not file based, the only way to shard is to `ShardByData`, and as shown in the code snippets above, that is precisely what is happening when you see this warning. Feel free to open a new issue if you'd like to pursue any performance debugging, but again this warning is not directly causing slow performance. 

Please note also that I have modified the wording on this warning in 92bd8e1 and removed the word "Error".

**Comment by JivanRoquet** [comment]
This warning doesn't seem to serve any apparent purpose and appears to be substantially annoying to anyone who encounters it.

**Comment by CloudyOverhead** [comment]
I have sucessfully removed this warning on TensorFlow 2.5.2 by dynamically replacing the default autosharding policy, in case anyone is interested.

```[python]
from tensorflow.python.data.util import options as options_lib
from tensorflow.data.experimental import DistributeOptions, AutoShardPolicy

DistributeOptions.auto_shard_policy = options_lib.create_option(
    name="auto_shard_policy",
    ty=AutoShardPolicy,
    docstring="The type of sharding to use. See "
    "`tf.data.experimental.AutoShardPolicy` for additional information.",
    default_factory=lambda: AutoShardPolicy.DATA,
)
```
