### ISSUE TITLE
some question about grpc+verbs and grpc+gdr

### ISSUE THREAD

**Issue by DeruiLiu** [tensorflow/tensorflow#42174]
when i use gdr, but the server_protocol can be use grpc+gdr or grpc+verbs.
i followed this script, and nv_peer_mem is loaded.
[gdr](https://github.com/tensorflow/tensorflow/tree/v1.8.0/tensorflow/contrib/gdr)
but the performance of grpc+gdr is worse, why?

**Comment by jvishnuvardhan** [comment]
@DeruiLiu 
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
