### ISSUE TITLE
Fused conv implementation does not support grouped convolutions for now

### ISSUE THREAD

**Issue by yangshengdong** [tensorflow/tensorflow#42177]
![image](https://user-images.githubusercontent.com/12997948/89756964-837d1e80-db16-11ea-98a9-262719e3bc72.png)

`Fused conv implementation does not support grouped convolutions for now`

What should i do ？

**Comment by Saduf2019** [comment]
@yangshengdong 
please update the template, we cannot find the tensorflow version, steps followed before you faced the error and error logs for us to analyze the issue.
Also please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.

**Comment by yangshengdong** [comment]
thanks，This problem solved

The problem was due to the difference in the number of channels in the image and the model
