### ISSUE TITLE
Installation issue with Tensorflow

### ISSUE THREAD

**Issue by Elona-marti** [tensorflow/tensorflow#42265]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): windows 10
- TensorFlow version: 2.2
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
I have freezed a Tkinter-using GUI Python 3.7 app with cx_Freeze.On my laptop, the app works perfectly. But when I try on a laptop that doesn't have python, I have this error:

![error](https://user-images.githubusercontent.com/69578257/90025950-00df9500-dcb7-11ea-8e40-604f7ad3964a.PNG)

Is it possible to automatically install Microscoft C 2015 when the application is installed?

**Comment by ravikyram** [comment]
@Elona-marti 

Can you please see [link1](https://stackoverflow.com/questions/51067599/cx-freeze-python-error-in-main-script-importerror-dll-load-failed) and [link2](https://stackoverflow.com/questions/2553886/how-can-i-bundle-other-files-when-using-cx-freeze) and see if it helps you.

This issue is more related to windows and cx_freeze .

This question is better asked on StackOverflow since it is not a bug or feature request related to Tensorflow. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by Elona-marti** [comment]
@ravikyram 
If you don't have the answer to a question, don't answer in a vacuum. My application works without tensorflow, it is the only library that poses a problem.

**Comment by ymodak** [comment]
Did you install [MSVC 2019](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)?
Also see https://www.tensorflow.org/install/pip#system-requirements
