### ISSUE TITLE
AttributeError: No svd operator in 0.10.0rc0

### ISSUE THREAD

**Issue by tomMoral** [tensorflow/tensorflow#4228]
Issue #2207 and [documentation](https://www.tensorflow.org/versions/r0.10/api_docs/python/math_ops.html#svd) both indicate that tensorflow has a svd operator.
However, I can't find it in fresh install of tensorflow0.10 with pip for python3.5 (both cpu and gpu )

### Environment info
Operating System: Linux (arch, kernel 4.7.2)
Pip installed (in two different virtualenv):
* https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl  
* https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0rc0-cp35-cp35m-linux_x86_64.whl

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
```python3
import tensorflow as tf
tf.svd

AttributeError: module 'tensorflow' has no attribute 'svd'
```

**Comment by tatatodd** [comment]
Thanks for the note @tomMoral!

Note that the in "0.10.0rc0" the "rc" stands for "release candidate", which is a preliminary version cut before the actual 0.10 release, to shake out issues.  Support for tf.svd was added after 0.10.0rc0 was cut, which is why it doesn't show up in your installs.

Try one of the following instead for either cpu or gpu installs: 
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl
https://storage.googleapis.com/tensorflow/linux/gpu/tensorflow-0.10.0-cp35-cp35m-linux_x86_64.whl

Note that these are listed in the pip installation instructions for version 0.10.  The instructions for master haven't been flipped over yet, since 0.10 hasn't been officially released yet.
https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#pip-installation

This should fix your problem; if not feel free to re-open.
