### ISSUE TITLE
In TF2.3 Reshape is not converted correctly

### ISSUE THREAD

**Issue by dansitu** [tensorflow/tensorflow#42286]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): OSX
- TensorFlow installed from (source or binary): pip
- TensorFlow version (or github SHA if from source): 2.3.0

**Command used to run the converter or code if you’re using the Python API**
If possible, please share a link to Colab/Jupyter/any notebook.

```
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
```

**Also, please include a link to the saved model or GraphDef**

Attached to issue 
[saved_model.zip](https://github.com/tensorflow/tensorflow/files/5065959/saved_model.zip)

**Failure details**
If the conversion is successful, but the generated model is wrong,
state what is wrong:

When converting a reshape, the resulting model has extra ops. Here's the expected output, as produced with `converter.experimental_new_converter = False`:

![image](https://user-images.githubusercontent.com/379235/90071187-f8349200-dca9-11ea-882f-1ed354fbe36a.png)

And here's the output with the new converter, note the extra ops before the reshape:

![image](https://user-images.githubusercontent.com/379235/90071275-1f8b5f00-dcaa-11ea-90e6-0ee502e148c6.png)

**Comment by Saduf2019** [comment]
@dansitu 
I am unable to open the file shared, can you please share a colab gist with the error faced.

**Comment by dansitu** [comment]
I've checked the attached file and it works. It's extremely simple to reproduce; just extract the .zip file and do this:

```
import tensorflow as tf
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
tflite_model = converter.convert()
```

Then save and inspect the `tflite_model`.

**Comment by Saduf2019** [comment]
@dansitu 
I ran your code as mentioned above on tf-nightly and did not face any error, please find [gist here](https://colab.research.google.com/gist/Saduf2019/2a93aacc1403d6561356aca9fe072f1f/untitled377.ipynb)

**Comment by dansitu** [comment]
@Saduf2019 The code executes, but it produces an incorrect output.

I've created a gist that demonstrates the issue:

https://colab.research.google.com/gist/dansitu/fdf90b82ed194d592716f777cf92e7dc/untitled377.ipynb

Note how when `converter.experimental_new_converter=True`, the output contains spurious ops and is missing another op.

I also noticed that `tf-nightly` crashes when `converter.experimental_new_converter=True` is set, but it does not crash with TF2.3.

**Comment by idenc** [comment]
I am also facing this issue

**Comment by karimnosseir** [comment]
@dansitu @idenc 
This is not an issue with the converter, actually it looks working as expected.
Let me explain why the extra nodes/discrepancy,

* Why using old converter looks as working ?
The old converter didn't support dynamic shapes (tensors with unknown dimension like (None, 637). Incorrectly it used to set 1 for the dynamic dimension if it is batch dimension (first dimension).
This is incorrect, because 
   Assuming static shape allows the converter to do extra optimizations, that will be incorrect if you tried doing resize_input_tensor on the interpreter. (You can find many issues already created with old converter about failures during resizing).

* Why the model using current converter has extra ops ?
The new converter now supports dynamic shapes, and if the graph has dynamic shape it will honor this, and passes this information to the runtime, so users can resize the input tensors correctly.

* My use case doesn't need dynamic shape, what can i do ?
Then in your model set the shape to a static shape and things should work as expected.

I modified the conversion lines to set a static shape using something like below (I suggest you modify your original model instead)
model = tf.saved_model.load('/tmp/saved_model')
concrete_func = model.signatures['serving_default']
concrete_func.inputs[0].set_shape([1, 637])
converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_func])
model_new_converter = converter.convert()
open('/tmp/model_new_converter_static_input_shape.tflite', 'wb').write(model_new_converter)

Thanks

**Comment by karimnosseir** [comment]
Closing the issue. Please reopen or file new one.

Thanks

**Comment by dansitu** [comment]
This makes sense, thanks for the clarification @karimnosseir!  Hope you are doing well :)

**Comment by dansitu** [comment]
FYI it's worth updating the converter docs with this info, since by default Keras models have a batch dimension of None.

**Comment by karimnosseir** [comment]
@dansitu Thanks, hope you are doing well too :) 
Will update the docs.

Thanks
