### ISSUE TITLE
Error installing from source.

### ISSUE THREAD

**Issue by vladfi1** [tensorflow/tensorflow#4234]
I'm installing tensorflow from source (git hash 891f8f73cc1967a5c2da89057884bc3dc1f9091a, bazel version 0.3.1).

    ./configure
    bazel build -c opt --config=cuda //tensorflow/tools/pip_package:build_pip_package
    bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg

The first two steps work, but the last one gives an error:

    error: can't copy 'tensorflow/models/embedding/gen_word2vec.py': doesn't exist or not a regular file

That file indeed does not exist.

**Comment by tatatodd** [comment]
I recommend that you pick a release branch, rather than something so close to HEAD, which may exhibit arbitrary failures.  We try to keep HEAD working at all times, but inevitably issues creep in.

To clone at the latest official release (0.10.0rc0) run the following.  Note that 0.10 hasn't been officially released yet; the "rc" means that this is a release candidate:
```
git clone -b v0.10.0rc0 https://github.com/tensorflow/tensorflow
```

Feel free to re-open if that doesn't fix your problem.

**Comment by shetshield** [comment]
I have same error stated above.
(Tensorflow is installed from source.)
In tensorflow/models/embedding/ directory, there is word2vec.py not gen_word2vec.py.
Command "bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg" requires gen_word2vec.py not word2vec.py.
I installed latest version of tensorflow by using "git clone https://github.com/tensorflow/tensorflow"
Error message is like this "error: can't copy 'tensorflow/models/embedding/gen_word2vec.py': doesn't exist or not a regular file".
How can I solve it?

**Comment by tatatodd** [comment]
As above, I recommend that you pick a release branch.  Note that 0.10 has been released.
```
git clone -b r0.10 https://github.com/tensorflow/tensorflow
```
