### ISSUE TITLE
How to add TFLite_Detection_PostProcess ops for my own detection model?

### ISSUE THREAD

**Issue by zzzzzzrc** [tensorflow/tensorflow#42352]
I have built the efficientdet-lite model using tf.keras, and it can predict the boxes, scores, classes, but it need postprocess,such as NMS. Now I have the frozen pb file, what should i do to add TFLite_Detection_PostProcess, what's the input for TFLite_Detection_PostProcess ops

**Comment by ymodak** [comment]
This question is better asked on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there.

If you think we've misinterpreted a bug, please comment again with a clear explanation, as well as all of the information requested in the [issue template](https://github.com/tensorflow/tensorflow/issues/new). Thanks!
