### ISSUE TITLE
SimpleRNN possibly not using GPU

### ISSUE THREAD

**Issue by joaogui1** [tensorflow/tensorflow#42363]
**System information**
Colab with K80 GPU

TensorFlow git version: v2.3.0-0-gb36436b087 2.3.0

**Describe the current behavior**
The SimpleRNN cell is taking close to 15 longer to run compared to the GRU, and so it appears that the simpleRNN is not using the GPU

**Describe the expected behavior**
It should be faster, or at least as fast as the GRU layer. 
**Standalone code to reproduce the issue**
Here's the [Colab](https://colab.research.google.com/drive/1SiLNLSweAMVf5O8i5UUDShv5Jf5AWtEA?usp=sharing) to reproduce the issue.

**Comment by Saduf2019** [comment]
@joaogui1 
I ran the code shared and face a different issue, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/37a5c98528b19792fa606d7077630d3a/untitled373.ipynb).

**Comment by joaogui1** [comment]
@Saduf2019 
The line `test_dataset = test_dataset.padded_batch(BATCH_SIZE)` is missing after doing the same for the train_dataset on the sixth cell

**Comment by Saduf2019** [comment]
@joaogui1 
I ran the code shared, please refer to the [gist](https://colab.research.google.com/gist/Saduf2019/c072980edf074309a9cda6acd63232f0/untitled373.ipynb) if it confirms your issue.

**Comment by joaogui1** [comment]
@Saduf2019 it confirms my issue (SimpleRNN takes 15 times longer than GRU)

**Comment by qlzh727** [comment]
Hi @joaogui1, thanks for reporting the issue.

I think the performance of GRU is because of fused cudnn kernel used, which is way faster than standard kernel. Unfortunately, we don't have a fused cudnn kernel for simpleRNN (cudnn kernel is provide by Nvidia), which is way simpleRNN is slower than GRU. It doesn't necessary mean the simpleRNN doesn't run on GPU.

I think there isn't any action item I need to address here. Closing this bug for now, and feel free to reopen if you feel there are other issue need to be addressed.
