### ISSUE TITLE
Adding Conv3DLSTM and depth-wise separable Conv3D layers to tensorflow.keras API

### ISSUE THREAD

**Issue by omarallouz** [tensorflow/tensorflow#42399]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Yes (but may not have the technical coding skills)

**Describe the feature and the current behavior/state.**
Thank you for creating this wonderful tool for researchers. It would be extremely helpful to have implementations of Conv3DLSTM and depth-wise separable Conv3D layers to the API for 3D medical image analysis.

**Will this change the current api? How?**
Yes, these layers would extend the features currently available in 2D within the current API making it more useful to researchers working with 3D data

**Who will benefit with this feature?**
Researchers working with 3D imaging data, particularly in the medical field

**Any Other info.**
I would appreciate any available tips or advice on how I could go by extending these features myself or how I could contribute to adding those features to the API

**Comment by mattlyon93** [comment]
The Conv3DLSTM feature would be very useful for my work also.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
