### ISSUE TITLE
ValueError: `tape` is required when a `Tensor` loss is passed.

### ISSUE THREAD

**Issue by zendevil** [tensorflow/tensorflow#42447]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (macOS Catalina):
- TensorFlow installed from pip:
- TensorFlow version 2.3.0:
- Python version 2.8:

**Describe the current behavior**

Getting the following error:
```
Traceback (most recent call last):
  File "train.py", line 277, in <module>
    k3
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 385, in minimize
    loss, var_list=var_list, grad_loss=grad_loss, tape=tape)
  File "/usr/local/lib/python3.7/site-packages/tensorflow/python/keras/optimizer_v2/optimizer_v2.py", line 440, in _compute_gradients
    raise ValueError("`tape` is required when a `Tensor` loss is passed.")
ValueError: `tape` is required when a `Tensor` loss is passed.
```
whereas `loss` is a number.

**Describe the expected behavior**
Since `loss` is a number, we expect tensorflow to not say that `Tensor` loss has been passed.
**Standalone code to reproduce the issue**

```
def loss(ground_truth, output):
    return np.sum(np.positive(ground_truth - output))

def kernel(*args):
  return tf.Variable(np.random.rand(*args), dtype=tf.float32) # kernel 1
color_channels = 3
feature_size = 32
k1 = kernel(5, 5, color_channels, feature_size)
k2 = kernel(3, 3, feature_size, feature_size) # kernel 2
k3 = kernel(3, 3, feature_size, feature_size) # kernel 3
width = 100
height = 200
y_train_left_nod = np.random.rand(width, height, 3)

y_train_left_noc = tf.keras.preprocessing.image.load_img("/img/path")
y_train_left_noc = tf.keras.preprocessing.image.img_to_array(y_train_left_noc)
soft_argmin = np.random.rand(y_train_left_noc.shape[0], y_train_left_noc.shape[1])  
loss = loss(y_train_left_noc[:,:,0], soft_argmin).tolist() # y

train = tf.keras.optimizers.Adam().minimize(loss, [
    k1,
    k2,
    k3])
```

**Comment by amahendrakar** [comment]
@zendevil,
On running the given code snippet, I am facing an error stating `NameError: name 'color_channels' is not defined`. 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here. Thanks!

**Comment by zendevil** [comment]
@amahendrakar I have updated the original code. The only change you need to make is have a valid image path.

**Comment by nikitamaia** [comment]
Hi @zendevil, the loss argument for `Optimizer.minimize` should be a callable, [as noted here in the docs](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer#minimize).

The error message you're seeing [is here in the source code:](https://github.com/tensorflow/tensorflow/blob/43cfb92ac5e2348718155905245194723f674697/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L499)
```
if not callable(loss) and tape is None:
    raise ValueError("`tape` is required when a `Tensor` loss is passed.")
```
This error message seems only to be in tf-nightly, and if you run the code in TF 2.3 you'll notice a slightly different error message `TypeError: 'float' object is not callable` which is perhaps a more clear message. Either way, since you're passing a scalar loss value, and not a callable, an error is expected. If you want to use a scalar loss value and not pass the callable, then you should use `GradientTape`, as noted in the error message. Happy to share some examples on how to do that is helpful.
