### ISSUE TITLE
non-zero `bias` of `Conv2D` in tflite file

### ISSUE THREAD

**Issue by KangGrandesty** [tensorflow/tensorflow#42484]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 1.15.0

All information is in [Colab](https://colab.research.google.com/drive/1yWwmAXHyBjNIivJKwmMMJT5V-37TEgph?usp=sharing)

Question:

Why the `Conv2D` op has non-zero `bias` input while they were setup `use_bias=False`.

**Comment by ravikyram** [comment]
@KangGrandesty 

Please, grant me access for the colab link.Thanks!

**Comment by KangGrandesty** [comment]
@ravikyram ,you can try again. [Colab](https://colab.research.google.com/drive/1yWwmAXHyBjNIivJKwmMMJT5V-37TEgph?usp=sharing)

**Comment by KangGrandesty** [comment]
My ssd lite model has bias like above, too.

And then the ssd model throws:

```
Internal error: Failed to apply delegate: tensorflow/lite/kernels/kernel_util.cc:129 std::abs(input_product_scale - bias_scale) <= 1e-6 * std::min(input_product_scale, bias_scale) was not true.
    Node number 35 (CONV_2D) failed to prepare.
```

Node number 35 is first `conv` of the 3rd squeeze-and-excite module in mobilenet v3 small. All of bias'value in this `conv` are -2147483648

**Comment by ymodak** [comment]
@KangGrandesty Can you try expand the `bias` values in the Netron app and inspect?
You should be seeing a bunch of zero values.
I made a toy example to work with TF 2.X way since all new updates are available for TF 2.
Please see the [gist](https://colab.research.google.com/gist/ymodak/178876aac1e5d019244b436479cf3b99/post_training_integer_quant.ipynb)

In the netron viewer on expanding the biases you will see all `zeros` when `use_bias=False`.
Please see attached screenshot.
<img width="687" alt="Screen Shot 2020-08-19 at 11 44 06 AM" src="https://user-images.githubusercontent.com/42785357/90676792-5a911380-e211-11ea-9fa3-d0f9c861e4cd.png">



For the same example when `use_bias=True`
<img width="665" alt="Screen Shot 2020-08-19 at 11 46 27 AM" src="https://user-images.githubusercontent.com/42785357/90677014-a17f0900-e211-11ea-9f1f-2716200083f8.png">

**Comment by KangGrandesty** [comment]
I run my example in tf2, but the bias is still non-zero. 

[mnist tf2 Colab](https://colab.research.google.com/drive/19avZS7BdPdwAEAEqyVmYoxB_uICijULw?usp=sharing)

![20200820101651](https://user-images.githubusercontent.com/19343603/90709235-4fe88400-e2ce-11ea-850f-a57780f91ed6.png)

If I remove  the `bn` layer:

[mnist no bn tf2 Colab](https://colab.research.google.com/drive/1aoOacX7BeSS3SomFpIii9VqCwpgp8JdP?usp=sharing)

![20200820102504](https://user-images.githubusercontent.com/19343603/90709735-722ed180-e2cf-11ea-84d5-925ebf6f453c.png)

The key is `bn` layer. Maybe?
