### ISSUE TITLE
Discrepancy between available operation semantics documentation and documentation of `tf2xla.python.xla.conv`

### ISSUE THREAD

**Issue by bchetioui** [tensorflow/tensorflow#42513]
## URL(s) with the issue:

https://www.tensorflow.org/xla/operation_semantics#conv_convolution

https://github.com/tensorflow/tensorflow/blob/5f2e159a58d1ef3414b2c34339266449574d8f94/tensorflow/compiler/tf2xla/python/xla.py#L239:L269

### Clear description

 [tf2xla.python.xla.conv](https://github.com/tensorflow/tensorflow/blob/5f2e159a58d1ef3414b2c34339266449574d8f94/tensorflow/compiler/tf2xla/python/xla.py#L239:L269) points to the operation semantics for `ConvWithGeneralPadding` but actually wraps the more general `ConvGeneralDilated`. It would make sense to actually have documentation about the operation semantics of this more general operation.

**Comment by Harsh188** [comment]
Hi @bchetioui,

Looks like the [docstrings for conv](https://github.com/tensorflow/tensorflow/blob/5f2e159a58d1ef3414b2c34339266449574d8f94/tensorflow/compiler/tf2xla/python/xla.py#L239:L269) in `xla.py` are incorrect. The method that is wrapped seems to be the [`XLA Conv`](https://github.com/tensorflow/tensorflow/blob/1dd24b74c291218f097f0e2a086a0fbd847bbea2/tensorflow/compiler/xla/client/xla_builder.h#L529) operator, not the `XLA ConvGeneralDilated` operator.

**Comment by bchetioui** [comment]
Hi @Harsh188,

It doesn't seem like this is the case to me; [Xla::Conv](https://github.com/tensorflow/tensorflow/blob/5f2e159a58d1ef3414b2c34339266449574d8f94/tensorflow/compiler/tf2xla/python/xla.py#L239:L269) has a different prototype than the function that is called in `xla.py` (which indeed corresponds to the one of [ConvGeneralDilated](https://github.com/tensorflow/tensorflow/blob/1dd24b74c291218f097f0e2a086a0fbd847bbea2/tensorflow/compiler/xla/client/xla_builder.h#L553).

**Comment by Harsh188** [comment]
@bchetioui you seem to be right. It also looks like it's just named [`XLAConv`](https://github.com/tensorflow/tensorflow/blob/5f2e159a58d1ef3414b2c34339266449574d8f94/tensorflow/compiler/tf2xla/kernels/xla_conv_op.cc#L91), but it seems to use `xla::ConvGeneralDilated`.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
