### ISSUE TITLE
Pipenv EagerExecution

### ISSUE THREAD

**Issue by Jakedismo** [tensorflow/tensorflow#42618]
I've written an object detection framework with Tensorflow 2 Keras and now I'm implementing some new functionalities. I noticed that eager_execution is not enabled if I run my code via `pipenv run python3 .../folder/main.py` ( tf tf.executing_eagerly() returns False) where as in `pipenv run python3 .... import tensorflow as tf tf.executing_eagerly()` returns True also in jupyter notebooks  tf tf.executing_eagerly() returns true.
Why does this behavior happen? I can't wrap my head around this.

**Comment by rmothukuru** [comment]
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
