### ISSUE TITLE
`OOM when allocating tensor with shape[320000,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc`

### ISSUE THREAD

**Issue by yangyoungyang** [tensorflow/tensorflow#42617]
`OOM when allocating tensor with shape[320000,512] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc`
I got this message while training CNN
Specifying batch_size 16, 32, 64, 128 did not help

_Originally posted by @Ritaprava95 in https://github.com/tensorflow/tensorflow/issues/16768#issuecomment-448324351_

**Comment by amahendrakar** [comment]
@yangyoungyang,
In order to expedite the trouble-shooting process, could you please provide the TensorFlow version, the complete code to reproduce the issue and the dataset you are using. 

Also, try limiting GPU memory growth as per [this guide](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) and let us know if it helps. 

Thanks!
