### ISSUE TITLE
How do I use a local LLVM installation?

### ISSUE THREAD

**Issue by daravi** [tensorflow/tensorflow#42639]
Hi,

I've been trying to build TensorFlow with my local LLVM installation. I figured I have to choose `N` when I run `./configure`:
```
Do you wish to download a fresh release of clang? (Experimental) [y/N]: n
```
I also tried setting the environment variable manually for the build:
```
TF_DOWNLOAD_CLANG="0" bazel build ...
```
However the build is still pulling llvm-project as an external dependency. Is using a local LLVM installation not supported? What do I need to do? Could you please give me the steps I need to take as I am new to Bazel or refer me to a resource?

**Comment by rmothukuru** [comment]
@daravi,
Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in [the Github new issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!
