### ISSUE TITLE
from_dlpack unable to process arrays with column-major strides

### ISSUE THREAD

**Issue by alecgunny** [tensorflow/tensorflow#42660]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Ubuntu 18.04
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (use command below):
2.3.0
- Python version:
3.6.9/3.7
- CUDA/cuDNN version:
10.1/7
- GPU model and memory:
K80/V100-32GB

**Describe the current behavior**
Trying to pass dlpack capsules to TensorFlow that come from arrays with column-major strides, like those leveraged by CuDF, raises an `InvalidArgumentError`. It's possible to work around this by transposing the array first, passing it to TensorFlow via dlpack, then transposing back, but obviously this is less than ideal.

**Describe the expected behavior**
These arrays should be read properly without needing to transpose first.

**Standalone code to reproduce the issue**
```
import tensorflow as tf, cupy as cp

# initialize tf
x = tf.random.uniform((1,))

tf.experimental.dlpack.from_dlpack(cp.asfortranarray(cp.ones((5, 2))).toDlpack())
```

Output should be
```
InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-4-cb770ae77ab3> in <module>()
      1 import tensorflow as tf, cupy as cp
      2 x = tf.random.uniform((5,))
----> 3 tf.experimental.dlpack.from_dlpack(cp.asfortranarray(cp.ones((5, 2))).toDlpack())

/usr/local/lib/python3.6/dist-packages/tensorflow/python/dlpack/dlpack.py in from_dlpack(dlcapsule)
     64     A Tensorflow eager tensor
     65   """
---> 66   return pywrap_tfe.TFE_FromDlpackCapsule(dlcapsule, context.context()._handle)

InvalidArgumentError: Invalid strides array from DLPack
```
See notebook [here](https://colab.research.google.com/drive/1ALUBTckq2ycXwQDIBNUzifYWJl9UJLN1?usp=sharing)

---------------------------
@miguelusque for viz

**Comment by sanjoy** [comment]
I don't think this can be fixed easily -- `tensorflow::Tensor` does not have an independent layout that can be set.  We can, however, do an in-memory transpose, but it won't be free.

**Comment by alecgunny** [comment]
If that can simplify the API to avoid having to do checks on the shape and layout of the incoming array, that seems like it might be worth it even if the performance is less than optimal

**Comment by sanjoy** [comment]
CC @VoVAllen 

I'm slightly worried that this might break the (implicit) promise that transferring tensors via dlpack is "free", but I'm happy to be corrected.

**Comment by alecgunny** [comment]
Hmm that's an interesting and valid point. Would a warning be a potential middle ground?

**Comment by sanjoy** [comment]
> Would a warning be a potential middle ground?

WDYT about adding a `allow_noncanonical_layouts` boolean argument to `tf.experimental.dlpack.from_dlpack`?  If this arg is set then we do a transpose, otherwise we don't.  That way it is obvious at the call site if a transpose may happen.

**Comment by VoVAllen** [comment]
I don't think it's a good idea to make it happen in the `from_dlpack` function. I would prefer it to be an option in the `to_dlpack` in cupy or other library, such as `force_canonical_layouts`. Since transpose seems always needed, I would prefer it happening at the source framework side. 

Project DGL also met similar problem, that the tensor might be non-alignment on cpu, which would cause error in tensorflow. Our solution is add an argument to force the alignment at DGL side. I think the case here is similar.

**Comment by kkraus14** [comment]
Hey, cuDF maintainer here and we produce a column major dlpack object since it makes the most sense given a columnar DataFrame.

> I'm slightly worried that this might break the (implicit) promise that transferring tensors via dlpack is "free", but I'm happy to be corrected.

Regardless of whether the transpose happens at the source or destination this promise is broken. I guess you could argue that doing it at the source is the user opting in to breaking that promise more explicitly, but all other DLPack adopters (CuPy, PyTorch, MXNet, cuDF, etc.) all either support a column major memory layout or implicitly handle the transpose.

> I don't think it's a good idea to make it happen in the `from_dlpack` function. I would prefer it to be an option in the `to_dlpack` in cupy or other library, such as `force_canonical_layouts`. Since transpose seems always needed, I would prefer it happening at the source framework side.

I'm against this, because not every producer has a transpose implementation or wants to add a transpose implementation. I.E. cuDF will produce a column major DLPack object via copy since our columns are individual allocations normally, and we don't want to transpose the dataframe since that's extremely expensive and implementing an array transpose is out of scope for a dataframe library. This will then force users to hop through something like CuPy to do the array transpose, which is non-obvious for non-power users.

**Comment by VoVAllen** [comment]
Hi,

Is transpose could be avoid? I'm wondering what's your downstream usage. What would be the API exposed to user in cuDF? Could user/downstream task accept a transposed tensor as a starting point? (i.e. `to_tf_tensor(transpose=True)` by default).

**Comment by VoVAllen** [comment]
Also there's possibility to avoid another transpose with copy if it's handling at the source framework, but there's no way to avoid this at tensorflow side. Source framework may have the cache of transposed tensor/make it a transposed tensor when creating, which improves the efficiency

**Comment by kkraus14** [comment]
> Could transpose be avoided? I'm wondering what's your downstream usage. What would be the API exposed to user in cuDF? Could user/downstream task accept a transposed tensor as a starting point? (i.e. `to_tf_tensor(transpose=True)` by default).

cuDF exposes an api of `df.to_dlpack()` which returns a `PyCapsule` wrapping a `DLTensor`. It similarly exposes an api of `cudf.from_dlpack(...)` which takes in a `PyCapsule` wrapping a `DLTensor` and returns either a Column or a DataFrame depending on if the tensor is 1d or 2d.

cuDF is a column major dataframe with separate allocations for each columns. To produce a DLPack object we copy each column into a new dense column major array. Given we're a DataFrame library, our stance has been that we produce the dense column major array in the most efficient way possible for us and then allow the downstream array/tensor framework (CuPy, PyTorch, MXNet, Tensorflow, etc.) handle the transpose if needed as they're more well equipped to do so than we are in cuDF.

**Comment by miguelusque** [comment]
Hi!

I was wondering if there is any progress on this issue.

Thanks!

Regards,
Miguel

**Comment by sushreebarsa** [comment]
Hi @alecgunny  Could you please try on latest stable version of tf 2.5 or 2.4.1 and let us know if this is still an issue.Thanks!

**Comment by alecgunny** [comment]
@sushreebarsa I'm actually no longer a part of the team on whose behalf I filed this issue. @miguelusque it looks like the [corresponding workaround](https://github.com/NVIDIA/NVTabular/blob/a04cbeed73a4ec7ad840471f2cd8db1ea6110ff1/nvtabular/loader/tensorflow.py#L334) is still being used in NVTabular, so I would recommend getting in touch with @EvenOldridge about whether someone from that team is still interested in taking a look at this.

**Comment by sushreebarsa** [comment]
@EvenOldridge, can you please respond to the above comment?

**Comment by karlhigley** [comment]
@sushreebarsa Chiming in from @EvenOldridge's team: I'm able to reproduce this issue with Tensorflow 2.5.0 and CuPy 9.2.0, so I believe this is still an issue.

**Comment by miguelusque** [comment]
I think this issue is still valid

**Comment by SuryanarayanaY** [comment]
Able to replicate the issue in TF2.11V. Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/dcef3db3dc5589a02125ce8f82234ab9/42660_2-11.ipynb). Thanks!

**Comment by EvenOldridge** [comment]
@VoVAllen @sushreebarsa is there any traction here to fix this on the TF side?  We've had a workaround in place in Merlin for a while but we're overhauling that system and it's a pain to maintain.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
