### ISSUE TITLE
“default Round and Robin”, “tf.fixed_ size_ Partitioner” and “tf.min_max_variable_partitioner” 

### ISSUE THREAD

**Issue by AI-Friend** [tensorflow/tensorflow#42675]
Suppose there are three PS servers and three tf.Variable (shape=[100000,256])。
Round and Robin policy: each PS server puts a tensor;
tf.fixed_ size_ Partitioner (3,0): assign 1 / 3 of each tensor to each PS server.

**Is the computing efficiency of the two strategies the same?**

**If the shape of tensor is quite different, is the latter better?**
**Would it be better to have some small tensors on the same PS?**
**tf.min_max_variable_partitioner：min_ slice_ size can't be used up. Will it be recycled?**

Thanks!

**Comment by nikitamaia** [comment]
Hi @AI-Friend, Sounds like you are using TF 1.x, since the methods you've mentioned do not exist in TF2. Are you trying to implement your own strategy, or utilize the tf.distribute.Strategy `ParameterServerStrategy`? 
I'm having a hard time understanding the benefit of breaking up each tensor and putting 1/3 on each PS as it seems like this will make the gradient updates more complicated. If you're using the out of the box strategy, then each variable of the model is placed on one PS, and it is not split up. Let me know if I have misunderstood your question.

**Comment by AI-Friend** [comment]
Hi, @nikitamaia,  I use TF1. X, because several embedding variables are relatively large. If we use "default Round and Robin" strategy, the load of PS will be unbalanced. Therefore, from the perspective of load balancing, I would like to ask whether the efficiency of placing one embedding variable in multiple PS and one PS is the same?

In addition, I would like to ask if I use "tf.estimator.Estimator", Is the code of distributed and stand-alone identical? 
Distributed information is configured in "tf.estimator.RunConfig", Is that ok?

Thanks!

**Comment by nikitamaia** [comment]
Closing this issue because Github is mainly for filing bugs. For support, Stack Overflow is a better place to go since there is a larger community of people answering questions. 
But to answer your question about using the estimator yes, the code should remain the same in the distributed and non-distributed case other than what you configure in the `RunConfig`. You might also need to adjust the batch size and input data function to ensure convergence. You can check out [this example here](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_estimator) from the docs.
