### ISSUE TITLE
individual neuron pruning (similar to tfkerassurgeon)

### ISSUE THREAD

**Issue by joh10891** [tensorflow/tensorflow#42688]
Just wanted to bring up that existing pruning packages (tfkerassurgeon and keras-surgeon https://github.com/Raukk/tf-keras-surgeon) are no longer supported or compatible with Tensorflow, so it'd be great if Tensorflow could implement their own simple individual neuron pruning capability. I'm aware of the existing Tensorflow APIs that focus on automated low-magnitude pruning(https://www.tensorflow.org/model_optimization/guide/pruning/comprehensive_guide), but being able to simply delete specific neurons/channels from layers or delete specific layers would be useful, and aid in the study of neural networks. For example, something like:
```
# delete layer_1 from a model
model = delete_layer(model, layer_1)
# delete channels 0, 4 and 67 from layer_2 in model
model = delete_channels(model, layer_2, [0,4,67])
```
This allows researchers and scientists much more flexibility in deciding how exactly they want to prune their model, and foster development of new pruning techniques

**Comment by ilyanelken** [comment]
Any update on this?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
