### ISSUE TITLE
tf.debugging.set_log_device_placement(True) does not seem to be working correctly.

### ISSUE THREAD

**Issue by marwan116** [tensorflow/tensorflow#42708]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow version (use command below): ('v2.3.0-0-gb36436b087', '2.3.0')
- Python version: 3.6.9 (default, Jul 17 2020, 12:50:27) 
- GPU model and memory: Tesla K80, 11441 MiB

**Describe the current behavior**
1. I open the documentation at https://www.tensorflow.org/guide/gpu in a colab
2. I change the runtime to GPU
3. I run all the cells
4. Looking at the Manual device placement section - I see the following output:
<img width="1094" alt="Screen Shot 2020-08-27 at 11 16 29 AM" src="https://user-images.githubusercontent.com/6924410/91461401-f1d01980-e856-11ea-986a-2a0539def458.png">

**Describe the expected behavior**
I would have expected the computation to be done on the CPU instead - am I missing something here that is colab specific?

**Standalone code to reproduce the issue**
The colab link is the one generated from visiting `https://www.tensorflow.org/guide/gpu`

**Comment by ravikyram** [comment]
@marwan116 

Since `c = tf.matmul(a, b)` is outside the scope of ` with tf.device('/CPU:0'):` it is being placed on GPU. But if we include `c = tf.matmul(a, b)` inside ` with tf.device('/CPU:0'):` then it will be placed on CPU as mentioned in the document [here](https://www.tensorflow.org/guide/gpu).Please, find the [gist](https://colab.research.google.com/gist/ravikyram/ddbeac0143d637e2c71d009faf755d93/untitled277.ipynb) for your reference. Thanks!

**Comment by marwan116** [comment]
@ravikyram - thanks for confirming this - I had just discovered the issue with c being outside of the context manager scope :) I guess the docs need to be updated - and then this issue can be closed.
