### ISSUE TITLE
Clarify that tf.image.adjust_brightness accepts negative values

### ISSUE THREAD

**Issue by hwaxxer** [tensorflow/tensorflow#42704]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/image/adjust_brightness

## Description of issue (what needs changing):

The documentation states that delta should be in the range [0, 1). However, the delta is added to the image so negative values in the range (-1, 0] are also valid, and useful if the image should be made darker.

### Clear description

It is useful to be able to darken images, and the documentation should make it clear how to do so.

**Comment by chrisrapson** [comment]
I wondered this myself. Since `random_adjust_brightness` provides a value in the interval `[-max_delta, max_delta)` it seems that negative values should be accepted.

I wondered whether this could be an issue with underflow for unsigned integer representations? The calculation is done as a float, but scaling and casting negative results (e.g. -0.1) to uint could give some weird behaviour. You can't just set a hard limit of 0 either, because some projects scale pixel values between -1 and 1. (https://www.tensorflow.org/api_docs/python/tf/keras/applications/xception/preprocess_input)
