### ISSUE TITLE
I have no idea how to initialize the tf.feature_column.embedding_column from txt or numpy? 

### ISSUE THREAD

**Issue by ChaosCY** [tensorflow/tensorflow#42720]
I have no idea how to initialize the tf.feature_column.embedding_column from txt or numpy? thanks

**Comment by ravikyram** [comment]
@ChaosCY 

Please, take a look at this usage example from [here](https://www.tensorflow.org/tutorials/structured_data/feature_columns) for tf.feature_column.embedding_column from text.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by ChaosCY** [comment]
I cannot find the example loading from a text, sorry.

**Comment by ChaosCY** [comment]
> @ChaosCY
> 
> Please, take a look at this usage example from [here](https://www.tensorflow.org/tutorials/structured_data/feature_columns) for tf.feature_column.embedding_column from text.
> 
> This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

I cannot find the example loading from a text, sorry.
