### ISSUE TITLE
Autograph unable to process lambda statements @TF 2.3.0

### ISSUE THREAD

**Issue by tornikeo** [tensorflow/tensorflow#42729]
- `TF 2.0: python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"` : `v2.3.0-rc2-23-gb36436b087 2.3.0`

## Problem description  
```python
import tensorflow as tf
assert tf.__version__ == '2.3.0'
dataset = tf.data.Dataset.from_tensor_slices(
   [1,2,3.]
).map(lambda x:x)
```
Throws unexpected warning:
```
WARNING:tensorflow:AutoGraph could not transform <function <lambda> at 0x7f4ac022e710> and will run it as-is.
Cause: could not parse the source code:

).map(lambda x:x)

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
WARNING: AutoGraph could not transform <function <lambda> at 0x7f4ac022e710> and will run it as-is.
Cause: could not parse the source code:

).map(lambda x:x)

This error may be avoided by creating the lambda in a standalone statement.

To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
```

## Expected behaviour  
The autograph converting the lambda statement as usual.

## Additional info  
This bug does not seem to occur in earlier version '2.2.0'. 
as per:
```python
import tensorflow as tf
assert tf.__version__ == '2.2.0'
dt = tf.data.Dataset.from_tensor_slices(
    tf.ones((10,))
).map(lambda x:x)
```
running without any erroneous output.
* all installations were made using pip package manager

**Comment by tornikeo** [comment]
This is my very first issue on git and I more than willing to help however I can. :smile:

**Comment by ravikyram** [comment]
@tornikeo 

I tried in colab with TF versions 2.2,2.3 and was able to reproduce the issue.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/d670398149064d89ca7a94158455e6cb/untitled279.ipynb).You are also seeing the same behavior. Thanks!

**Comment by tornikeo** [comment]
@ravikyram 

Yes, in colab see the same behaviour in both, versions 2.2 and 2.3.

**Comment by tornikeo** [comment]
@ravikyram 

How do I contribute? Specifically I want to help with updating writing and translating documentation. Can you provide any pointers?

**Comment by nikitamaia** [comment]
Hi @tornikeo,

The warning here is because your lambda statement is on a separate line. 
`tf.data.Dataset.from_tensor_slices([1,2,3.]).map(lambda x:x)` should work fine.

The reason you are not seeing the warning in earlier versions is not because the problem wasn't there, but it wasn't discovered until later and the warning was added. Please see issue #39832 for more context on why the multi line lambda statements can cause problems for autograph (it had to do with an underlying issue in Python).

We have added more robust coverage for lambdas and you should not see the problem in tf-nightly. Hope this helps!

**Comment by tornikeo** [comment]
Thanks @nikitamaia 
This means you can safely close this issue now, if you wish.

P.S: Sorry for bothering you but, about my question above, how do I contribute? Are there any easy to understand guides for contributing to tensorflow? This is the first time i am contributing to FOSS. Any pointers would be greatly appreciated. :smile:
 Thank you.

**Comment by nikitamaia** [comment]
That's great! The Tensorflow community is always looking for more contributors! You can learn more about getting started in the [Contributors Guide](https://www.tensorflow.org/community/contribute). Also linking to the specific sections on [docs and translations](https://www.tensorflow.org/community/contribute/docs#community_translations) since you mentioned you were interested.

**Comment by tornikeo** [comment]
Thnaks @nikitamaia ! I'll look into that. Closing this issue now.
