### ISSUE TITLE
bazel build error, //tensorflow:libtensorflow_cc.so is misplaced here (expected cc_library, objc_library, cc_proto_library or cc_import)

### ISSUE THREAD

**Issue by yuye2133** [tensorflow/tensorflow#42769]
I have used a proto(lower version) in my project , so I want to build a dynamic link library that not rely proto
my BUILD：
![image](https://user-images.githubusercontent.com/20791462/91634620-3bba2a80-ea24-11ea-80ac-b3cff8384221.png)

**build error:**
in deps attribute of cc_binary rule //tensorflow/extern/crflstmmodel-api:libcrflstmmodel.so: cc_binary rule '**//tensorflow:libtensorflow_cc.so**' is misplaced here (expected cc_library, objc_library, cc_proto_library or cc_import) and '**//tensorflow:libtensorflow_cc.so**' does not have mandatory providers: 'CcSkylarkInfo'

**Comment by amahendrakar** [comment]
@yuye2133,
In order to expedite the trouble-shooting process, could you please fill in the below details

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

And also provide the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by mihaimaruseac** [comment]
You should not use a file in `deps`, but a Bazel target.

**Comment by amahendrakar** [comment]
> You should not use a file in `deps`, but a Bazel target.

@yuye2133,
Any updates regarding this? Please feel free to close the issue if resolved. Thanks!
