### ISSUE TITLE
[ko][zh-cn] How to get chinese/korean fonts to work in matplotlib + Colab?

### ISSUE THREAD

**Issue by MarkDaoust** [tensorflow/tensorflow#42780]
The default Matplotlib setup in Colab doesn't include Chinese or Korean fonts, so these characters don't render.

I believe this is one of the reasons we have not been translating figure text.

I can get the browser to render this text by outputting svg-text:

```
from IPython.display import set_matplotlib_formats
set_matplotlib_formats('svg')
matplotlib.rcParams['svg.fonttype'] = 'none'
```

But that messes up a lot of the formatting.

Some searching shows that it might just be a matter of installing the right fonts and adding them to the `matplotlib.rc` configuration, but I haven't found a end-to-end setup that works yet. 

Does anyone have experience setting this up?

**Comment by MarkDaoust** [comment]
Status: still broken.
 
The reference from TFHub is that they have one multi-lingual tutorial that breaks if they push it to the site because the fonts are not available.

If this is high enough priority, we could upstream Haesun's font setup (+fonts for Chinese) into Colab and the site generator. Worth it? or should we just close this?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
