### ISSUE TITLE
Can't download Tenserflow

### ISSUE THREAD

**Issue by rinabatt** [tensorflow/tensorflow#42809]
Traceback (most recent call last):
  File "C:\Users\Oyuntuul\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\Oyuntuul\venv\lib\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\Oyuntuul\venv\lib\site-packages\tensorflow\python\__init__.py", line 40, in <module>
    from tensorflow.python.eager import context
  File "C:\Users\Oyuntuul\venv\lib\site-packages\tensorflow\python\eager\context.py", line 35, in <module>
    from tensorflow.python import pywrap_tfe
  File "C:\Users\Oyuntuul\venv\lib\site-packages\tensorflow\python\pywrap_tfe.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\Oyuntuul\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\Oyuntuul\venv\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.

Failed to load the native TensorFlow runtime.

**Comment by NikhilBartwal** [comment]
Hey @rinabatt, Could you provide us some more information about the python version you are using and the TF version you want to install along with the Microsoft Visual C++ version and whether you are using CUDA/cDNN.
Are you trying to install Tensorflow using the Anaconda distribution or using the official _pip_. You can have a look [here](#39007 ) and [here](https://stackoverflow.com/questions/44503603/tensorflow-on-windows-importerror-dll-load-failed-the-specified-module-could)

**Comment by rinabatt** [comment]
Hi Nikhil,

I'm using Python 3.8.3. I am trying to download TF 2. Microsoft Visual
C ++  2015 version. I am using CUDA/cDNN.
I tried doing both, and it's not working.



<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by amahendrakar** [comment]
@rinabatt,
In order to expedite the trouble-shooting process, could you please provide the following information

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Also, please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) for installing TensorFlow and check if you have the correct dependencies installed. Thanks!
