### ISSUE TITLE
tf.compat.v1.data.get_output_shapes(datasets) gives Errors

### ISSUE THREAD

**Issue by iamsrilakshmi** [tensorflow/tensorflow#42824]
## Iam getting different types of errors in different projects whenever I use tf.compat.v1.data.get_output_shapes(datasets)
I have tried all the Codes in Colab only.
</em>

**System information**
### COLAB

1. Tensorflow Version :  Latest on Colab : 2.3.0
2. Python 3
3. COLAB GPU

**Current behavior :**
While using **tf.compat.v1.data.get_output_shapes(datasets), I got 2 types of errors in 2 projects:**
1. ValueError: logits and labels must have the same shape ((None, 1) vs ())
2. ValueError: Input 0 of layer global_average_pooling1d is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [None, None, None, 128]

**As a temporary solution, I used datasets.output_shape** & I got the desired output.

*But whenever I use datasets.output_shape , I get a warning as below:*
WARNING:tensorflow:From <ipython-input-3-3cfb74cd1ccb>:3: DatasetV1.output_shapes (from tensorflow.python.data.ops.dataset_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.compat.v1.data.get_output_shapes(dataset)`.

**Request to the Tensorflow Team:**
I kindly request the Tensorflow team to look into this issue and help me solve it.

**Thank you Tensorflow Team in Advance...!!!**

[Colab file Link](https://colab.research.google.com/drive/1m9yF3cXQGTc1xNLCgBVx0BdcHVnOctbz?usp=sharing)

**Comment by ravikyram** [comment]
I tried in colab with TF version 2.3, nightly(`2.4.0-dev20200831`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/460758e724e1b69840f66d3f1b037fbe/untitled290.ipynb). Thanks!

**Comment by nikitamaia** [comment]
Hi @iamsrilakshmi, I think your issue here is that you first define

```
tr = tr.shuffle(10000)
tr = tr.padded_batch(64, tr.output_shapes)
```

And then when defining `tr2`, you are again padding `tr`, which is already padded, and that results in an extra dimension, hence the error message `expected ndim=3, found ndim=4. Full shape received: [None, None, None, 128]`

If you just remove the following lines from your colab notebook, it runs without error:
```
tr = tr.shuffle(10000)
tr = tr.padded_batch(64, tr.output_shapes)
val = val.padded_batch(64, val.output_shapes)
```

**Comment by iamsrilakshmi** [comment]
Hi @nikitamaia ,

Can you please check in this Colab code file... [Link to colab file](https://colab.research.google.com/drive/12V0MXjBVxZ7gEDYlKwW_QXZ2wb3UUbDa?usp=sharing)

I am facing the same error with tf.compat.v1.data.get_output_shapes. This error is displayed only when training the model

The error I am talking about is as follows:

**ValueError: logits and labels must have the same shape ((None, 1) vs ())**

Please look into the issues concerning this particular error

**Comment by nikitamaia** [comment]
The error you see is because you are passing in the wrong datasets to your `model.fit`

You are calling  `model.fit(train_data, epochs=num_epochs, validation_data=test_data)`
but `train_data` and `test_data` are the raw datasets from tfds, and not the ones you have applied  `tf.compat.v1.data.get_output_shapes` to.

You should be passing in `train_dataset` and `test_dataset` like so:
`model.fit(train_dataset, epochs=num_epochs, validation_data=test_dataset)`

For future reference, Github is a place for filing bugs. These kinds of support requests are better for Stack Overflow where there is a wider community to troubleshoot.

**Comment by nikitamaia** [comment]
Closing issue since a solution was found and there is no bug here.
