### ISSUE TITLE
Breaking API change without deprecation warning

### ISSUE THREAD

**Issue by mkolod** [tensorflow/tensorflow#4283]
### Problem

The name_scope API has changed between last week and last night's latest changes in the 0.10 branch. The previous API was:
   
    name_scope(*args, **kwds)

The current API is:

    name_scope(name)

The API was changed in a breaking way, rather than the new API being added and the use of the old API triggering a warning.

I was wondering what the TensorFlow gatekeepers' policy is on breaking API changes. Is there an official policy? Is the breaking change without a deprecation warning and phase-out intentional?

**Comment by martinwicke** [comment]
This is a deliberate change. Before 1.0, we have very few guarantees for the API itself. In fact, we're trying to make breaking changes before 1.0, so their frequency may increase in the coming months. 

Please take a look at [our policy](https://www.tensorflow.org/versions/r0.10/resources/versions.html) regarding code. 

For stored graphs, the guarantees are [stronger](https://www.tensorflow.org/versions/r0.10/resources/data_versions.html). 

After 1.0, there should not be breaking changes in minor releases, only for major ones (i.e., the next ones at 2.0).

Note that regardless of version, development at head (or branch head) is inherently dangerous when it comes to stability due to bugs.

**Comment by thatguymike** [comment]
So TF shouldn't be used in production until 1.0?  Is there documented rough schedule/timeline for 1.0?

**Comment by martinwicke** [comment]
There's no problem with using TF in production (we use it plenty). But I *would* advise against using TF *at head using continuous updates* in a production environment.

To use TF in production, I would use a release (or, if you must, a specific hash), and update TF only in a controlled manner. In other words, treat it the same as other libraries you use in production: when you update the library to a new version, verify that everything works afterwards. 

Even updating more mature libraries like numpy to a new version is not something you can safely do in production. 

TF is no different in principle, although because of various factors (cuda, rapid development) people are much more likely to use TF at head, and so the pressure up update is much higher.

**Comment by malcolmgreaves** [comment]
```update TF only in a controlled manner.```
Seems like the problem here is that there's no warnings or release notes when breaking changes occur. How should someone like me (external to Google, using TF) know which versions are safe and which ones are unsafe to depend upon? What strategy do you recommend, @martinwicke ?

**Comment by vrv** [comment]
There are release notes when breaking changes occur: https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md, though it's clear it isn't always filled in with all changes :(.
