### ISSUE TITLE
Try running

### ISSUE THREAD

**Issue by kosohae** [tensorflow/tensorflow#42854]
==> I try pip install tensorflow==1.5.0 
it was not working, and then I tried pip install tensorflow-gpu==1.5.0 
it was working. Thanks.
Try running
pip uninstall tensorflow
And then
pip install tensorflow==1.5

EDIT
just to give credit, solution is from here:
https://stackoverflow.com/questions/49094597/illegal-instruction-core-dumped-after-running-import-tensorflow

_Originally posted by @konnerthg in https://github.com/tensorflow/tensorflow/issues/17411#issuecomment-370393493_

**Comment by ravikyram** [comment]
@kosohae 

This may be due to conflicts in dependencies.Always it would be better to create an virtual environment and install tensorflow .
Tensorflow 1.5 version is too old. It will be advisable to use latest TF versions like 2.3. There were lots of performance improvements in the latest versions. Please, close this issue as i do not see any issue now.Thanks!
