### ISSUE TITLE
control flow support issue in TensorFlow XLA

### ISSUE THREAD

**Issue by yongwww** [tensorflow/tensorflow#42876]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary (pip install tensorflow)
- TensorFlow version (use command below): 2.3 (issue exists in 1.5 as well)
- Python version: 3.7.6
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Seems control flow is supported in xla, but I ran into issues with some test cases

**Describe the expected behavior**
the graph should be supported by xla

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
```
import numpy as np
import tensorflow as tf
from tensorflow.python.ops import control_flow_ops
tf.compat.v1.enable_eager_execution()
@tf.function(experimental_compile=True)
def test_switch():
    data_np = np.random.uniform(0, 5, size=(2, 4, 5, 1)).astype('float32')
    data = tf.constant(data_np)
    split = tf.split(data, 2, axis=0)
    flag = False
    output_false, output_true = control_flow_ops.switch(split[1], flag)
    return output_false

test_switch()
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

The following is the error message I got when tried to run with xla.
```
Switch: unsupported op: No registered 'Switch' OpKernel for XLA_CPU_JIT devices compatible with node {{node Switch}}
	Stacktrace:
		Node: __inference_test_switch_12, function: 
		Node: Switch, function: __inference_test_switch_12
 [Op:__inference_test_switch_12]
```

**Comment by Saduf2019** [comment]
I am able to replicate the issue faced, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7042a073fd9ca20e10c881938a7c587e/untitled403.ipynb)

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tf Nightly 2.6.0-dev20210603, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/da738e8701d9febde7ec5671c1369796/42876.ipynb). Thanks!

**Comment by SuryanarayanaY** [comment]
Hi @yongwww ,

XLA not supports all the Ops on Tensorflow. Please find the list of supported Ops for CPU at [CPU_XLA_Ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/g3doc/cpu_supported_ops.md) and GPU at [GPU_XLA_Ops](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/tf2xla/g3doc/gpu_supported_ops.md) .

ControlTrigger Is the only Operation from Controlflow Ops that supported on XLA. The tested Op `control_flow_ops.switch` not supported on XLA and hence the error which is clear and explicit.

InvalidArgumentError: Detected unsupported operations when trying to compile graph __inference_test_switch_24[_XlaMustCompile=true,config_proto=3175580994766145631,executor_type=11160318154034397263] on XLA_CPU_JIT: Switch (No registered 'Switch' OpKernel for XLA_CPU_JIT devices compatible with node {{node Switch}}){{node Switch}}.

Since XLA is still under process of covering all the Ops implementations possible may be in Future version we may expect the implementation of the Ops.But for time now tested Op is not implemented on XLA. Shall we close the issue now ??
