### ISSUE TITLE
Tensorflow model dump in c++ during inference

### ISSUE THREAD

**Issue by sw2921** [tensorflow/tensorflow#42875]
Tensorflow 1.15/2.x

For debugging process, we hit nan score issue during c++ inference (saved model). i would like to know which intermediate node having issue.  I try to search the official documentation and google, there is no way to dump all tensors in the graph in c++ side during inference.

**Will this change the current api? How?**
No, I imagine we can provide an option in the run options, to serialize all tensors after inference into string and put it into RunMetadata.

**Who will benefit with this feature?**
Everyone?  :)

**Any Other info.**
If we already have some ways to dump the all graph tensors in c++ side during inference, please let me know. Very appreciate it!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
