### ISSUE TITLE
Does TensorFlow1.x support CUDA11? And how can i compile tensorflow 1.x with cuda11?

### ISSUE THREAD

**Issue by Crisescode** [tensorflow/tensorflow#42895]
This template is for miscellaneous issues not covered by the other issue categories.

For questions on how to work with TensorFlow, or support for problems that are not verified bugs in TensorFlow, please go to [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).

If you are reporting a vulnerability, please use the [dedicated reporting process](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md).

For high-level discussions about TensorFlow, please post to discuss@tensorflow.org, for questions about the development or internal workings of TensorFlow, or if you would like to know how to contribute to TensorFlow, please post to developers@tensorflow.org.

**Comment by bhack** [comment]
I don't think it will be officially supported for TF 1.x. Please ask at https://github.com/tensorflow/tensorflow/issues/42047

**Comment by mihaimaruseac** [comment]
No. Each CUDA support is tied with a version of TF and is impossible to backport to older releases.

I would say community can create builds with newer CUDA and older TF, but it is likely that the compile process will fail, since we also change TF code to be in sync with CUDA specs. Hence, even backporting some patches to the release branches is impossible.
