### ISSUE TITLE
Bazel error on six_archive when compiling from source

### ISSUE THREAD

**Issue by severun** [tensorflow/tensorflow#429]
Hello,

I am having issues building tensorflow from source. I have a local checkout and the required packages installed, following the manual from the tensorflow.org getting-started pages. However, when trying to use bazel to compile the pip-package I get the following error. Can anyone help me to solve this problem? Thanks in advance!

**Command:** bazel build -c opt //tensorflow/tools/pip_package:build_pip_package -s --verbose_failures

**ERROR:**  ~/development/alexander/.cache/bazel/_bazel_alexande/44250d582377ce08fbe503824f986778/external/six_archive/BUILD:1:1: Executing genrule @six_archive//:copy_six failed: bash failed: error executing command 
  (cd ~/development/alexander/.cache/bazel/_bazel_alexande/44250d582377ce08fbe503824f986778/tensorflow && \
  exec env - \
    PATH=/usr/local/bin:/usr/bin:/bin:/usr/X11R6/bin::/usr/lib64/java/bin:/usr/lib64/java/jre/bin:/usr/lib64/java/bin:/usr/lib64/kde4/libexec:/usr/lib64/qt/bin:.:/usr/local/tmake/bin:/home/alexander/bin:/home/alexander/development/alexander/bazel/ \
    TMPDIR=/home/alexander/development/alexander/.tmp \
  /bin/bash -c 'source tools/genrule/genrule-setup.sh; cp external/six_archive/six-1.10.0/six.py bazel-out/local_linux-opt/genfiles/external/six_archive/six.py'): bash failed: error executing command

**Comment by girving** [comment]
@craigcitro: Do you know what's happening me?  My knowledge of pip is scant.

**Comment by craigcitro** [comment]
I'd guess that the download failed for some reason, and we're just getting a bad error from it.

@severun  -- Can you run again with `bazel build -s` to see the full command-line and output?

**Comment by severun** [comment]
@craigcitro -- I've run the build again using the following command: "bazel build -s  --verbose_failures //tensorflow/tools/pip_package:build_pip_package"

And this is a part of the output that I get, containing the error. I hope this is enough output?
http://pastebin.com/ihL6gm2S

**Comment by craigcitro** [comment]
@severun well, it confirms that the failing step is indeed something about copying the file out of the downloaded six archive.

i'll admit that i'm shooting in the dark a bit here; two things to try:
* could you try running again with `-j 1` and see if that fixes things? (it'll be *much* slower, since it forces bazel to do things serially, but we've seen lots of nondeterminism issues.)
* similarly, can you run `blaze build -s @six_archive//:copy_six` to confirm it works by itself?

**Comment by severun** [comment]
Interesting, when I build without the <code>-j 1</code> I get a random error, either from <code>six_archive</code> or from <code>//google/protobuf:python_srcs_genrule</code>.

I've run the build again using <code>-j 1</code> and this now consistently shows the following error:
<code>ERROR: /local.mnt/vol1/development/alexander/tensorflow/google/protobuf/BUILD:497:1: Executing genrule //google/protobuf:python_srcs_genrule failed: bash failed: error executing command </code>

When I try to build only this package by itself, using: 
<code>bazel build -s -j 1 --verbose_failures //google/protobuf:python_srcs_genrule</code>
I get the following output:

http://pastebin.com/GSZNpiRW

**Comment by craigcitro** [comment]
So this one is also an error just trying to copy files; two questions:

* any chance you're doing this on a partition that's nearly full?
* when you cloned the github repo, did you do `--recursive` (which also clones protobuf, the one git submodule we have)?

**Comment by severun** [comment]
The command that I used to clone the github repo:
<code>git clone --recurse-submodules https://github.com/tensorflow/tensorflow</code>

Only our /tmp folder is almost full, so I have a <code>export TMPDIR=....</code> to an alternative directory to use as temporary folder. Could this be the problem? I noticed a couple of 'source' commands in the bazel output, so maybe this tmpdir variable is overwritten?

**Comment by craigcitro** [comment]
`--recursive` and `--recurse-submodules` are the same, so no worries there.

It looks like bazel is using `TMPDIR=/home/alexander/development/alexander/.tmp`; can you do `df -h /home/alexander/development/alexander/.tmp` and see if it's short on space?

**Comment by severun** [comment]
df shows there is 270G still available, so I doubt that to be the problem.

**Comment by craigcitro** [comment]
OK, so all my easy hypotheses are no good.

Summoning @lberki, knower of all things bazel -- Lukas, how should we diagnose what's happening here? `bazel build` is failing at a copy step, even with `-j 1`.

**Comment by severun** [comment]
@craigcitro Thanks for the effort :)

**Comment by lberki** [comment]
What happens if you try to run this command:

`cp external/six_archive/six-1.10.0/six.py bazel-out/local_linux-fastbuild/genfiles/external/six_archive/six.py` 

in `<root>/bazel-tensorflow`, or, equivalently, in `/local.mnt/vol1/development/alexander/.cache/bazel/_bazel_alexande/44250d582377ce08fbe503824f986778/tensorflow`? My suspicion is that `cp` silently fails for some reason. If that works, try

`/bin/bash -c 'source tools/genrule/genrule-setup.sh; cp external/six_archive/six-1.10.0/six.py bazel-out/local_linux-fastbuild/genfiles/external/six_archive/six.py'` in the same directory.

**Comment by severun** [comment]
Both commands work fine, <code>six.py</code> is successfully copied.

**Comment by lberki** [comment]
@craigcitro : Tensorflow users Bazel 0.1.1, right? 
@severun : Does this work if you add the `--spawn_strategy=standalone --genrule_strategy=standalone` command line options to the Bazel command line?

**Comment by lberki** [comment]
@severun : do you also have ample disk space under `/local.mnt/vol1/development/alexander/.cache/bazel/_bazel_alexande/44250d582377ce08fbe503824f986778/tensorflow`?

**Comment by craigcitro** [comment]
@lberki for the docker containers, we use 0.1.1. @severun -- what version of bazel are you using locally?

**Comment by craigcitro** [comment]
(and install instructions suggest 0.1.1.)

**Comment by severun** [comment]
When I run <code>bazel help</code> it outputs: [bazel release 0.1.1], which seems to be the correct version required for tensorflow.

When running <code>bazel build -s -j 1 --verbose_failures --spawn_strategy=standalone --genrule_strategy=standalone //tensorflow/tools/pip_package:build_pip_package</code> it outputs the following error: http://pastebin.com/AKC7UADW

**Comment by lberki** [comment]
How about just with `--genrule_strategy=standalone` then? Also, do you have ample disk space under `/local.mnt/vol1/development/alexander/.cache/bazel/_bazel_alexande/44250d582377ce08fbe503824f986778/tensorflow`?

**Comment by severun** [comment]
Yes I have enough disk-space, still 270gb free space left. Also running the bazel command with only <code>--genrule_strategy=standalone</code> does not help, same error.

However, I noticed that the generated commands include <code>/usr/bin/gcc</code> to compile the code, and manually running this command failes. However, if I use <code>/usr/bin/g++</code> the code does compile, without any errors w.r.t. the symbols.

**Comment by lberki** [comment]
Okay, I'm shooting in the dark now. Since the `cp` genrule works when run in the execroot manually, my next guess is something sandbox-related. Could you try to run the build with the `--sandbox_debug` command line option? For best results, do a build without the option, then a build with it so that the only rule that's run with debugging is the offending genrule. Otherwise you'd get quite a lot of log spam on the console.

**Comment by severun** [comment]
Ok I reran the build using the <code>--sanbox_debug</code> parameter, which results in the following output: http://pastebin.com/TSCrrHWF

**Comment by severun** [comment]
I think I found the Issue. When i run the command <code>exec env -</code> I am disconnected from the server. This might be some security feature installed on the server I guess?
When I manully repeat the commands from the debug output, without the <code>exec</code> command it works fine...

**Comment by lberki** [comment]
The `exec env -` part is not actually executed by Blaze, it's just (IIRC) so that it's easy to achieve similar behavior when you copy-paste the command into your terminal.

It's getting late here, so I'll continue tomorrow. Adding @philwo and @ulfjack in case they have a clever idea.

**Comment by lberki** [comment]
What's "disconnected from the server"? You mean as in, logged out from your shell? It's expected, since `exec` replaces your shell with `env`, which then promptly exits)

**Comment by severun** [comment]
I connect to the server via ssh, and after running <code>exec env -</code> I am disconnected from the ssh session. I am no linux guru so I am not much of a help. Just close this 'issue' if its taking too much time. I'm sure you guys have more interesting things to work on :)

**Comment by philwo** [comment]
Hehe :) The reason why your SSH connection closes is simple, but also rather surprising (now I wonder why Bazel even prints "exec env" - this is never something you'd want to paste into your shell):

Let's assume you simply type "env" into your shell and press Enter. The shell then spawns a new process in which it executes the binary "env". It prints some stuff to your terminal, exits and now you're back in your shell.

However, when you run "exec env", the shell actually *replaces* itself with the newly spawned process "env". Now when that process exits, your SSH connection gets closed, because the process your terminal was connected to has exited.

You can try it yourself on your local machine (just tried it on my Macbook): Open a Terminal, enter "exec env" and your terminal closes or will print something like "[Process completed]" and no longer responds to input. You can simply leave the "exec" away and it should work fine.

**Comment by philwo** [comment]
This error message in your log looks very strange:
"/lib64/libm.so.6: could not read symbols: Invalid operation"

This suggests that Bazel is not linking in libm when building protoc, see http://stackoverflow.com/questions/9934549/very-strange-linker-behavior for some discussion about a similar error (unrelated to Bazel).

This error message: "bash failed: error executing command" actually says that bash could not be executed. It means that the sandbox might be missing a shared library.

Something is very different with your Linux machine that with the ones we test Bazel on :) Which Linux distribution are you using? Is there anything "special" about your machine or Linux setup?

**Comment by severun** [comment]
<code>uname -o</code> "outputs GNU/Linux". I also found that <code>cat /etc/slackware-version</code> outputs "Slackware 14.0"

I also noted above that when manually running the Bazel commands, and replacing gcc with g++ it does seem to properly work. Is it possible to change the compiler that Bazel uses?

**Comment by severun** [comment]
An update for those interested
I've managed to get past the compiling problems of </code>protoc</code>. I managed to get past the linker error by adding <code>-lm</code> in 'google/protobuf/BUILD'.

However, now I managed to get an actual compiling error, similar to the one mentioned here: #439 
I'll monitor the other issue and see if a solution for that ticket can be applied to my problem as well.

My error log:
......
In file included from /usr/lib64/gcc/x86_64-slackware-linux/4.7.1/../../../../include/c++/4.7.1/x86_64-slackware-linux/bits/os_defines.h:40:0,
                 from /usr/lib64/gcc/x86_64-slackware-linux/4.7.1/../../../../include/c++/4.7.1/x86_64-slackware-linux/bits/c++config.h:414,
                 from /usr/lib64/gcc/x86_64-slackware-linux/4.7.1/../../../../include/c++/4.7.1/string:40,
                 from ./tensorflow/core/platform/port.h:19,
                 from ./tensorflow/core/lib/core/command_line_flags.h:19,
                 from tensorflow/core/lib/core/command_line_flags.cc:16:
/usr/include/features.h:328:4: warning: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Wcpp]
In file included from ./tensorflow/core/lib/gtl/array_slice.h:101:0,
                 from ./tensorflow/core/lib/strings/str_util.h:21,
                 from tensorflow/core/lib/core/command_line_flags.cc:18:
./tensorflow/core/lib/gtl/array_slice_internal.h:231:38: error: 'tensorflow::gtl::array_slice_internal::ArraySliceImplBase<const T>::ArraySliceImplBase' names constructor
./tensorflow/core/lib/gtl/array_slice_internal.h:251:32: error: 'tensorflow::gtl::array_slice_internal::ArraySliceImplBase<T>::ArraySliceImplBase' names constructor
...

**Comment by philwo** [comment]
I think your gcc is too old - Slackware 14.0 ships gcc 4.7.1, but the error messages suggests that a C++11 feature called "Inheriting Constructors" are being used by tensorflow, which requires at least gcc 4.8.

Can you upgrade to Slackware 14.1? That has gcc 4.8.2, which should be fine.

**Comment by lberki** [comment]
@philwo kindly too a look and at least we now know why the genrule failed: the error message `error executing command` is raised not because the command fails, but because bash cannot be executed. It's probably because some libraries needed by bash are not mounted into the sandbox. An `ldd bash` and a good hard look and the sandbox debugging output would provide a clue, but you probably simply want to disable the sandbox with the `--*_strategy=standalone` options.

**Comment by severun** [comment]
@philwo I've asked the system admin to upgrade the gcc version and I now have access to gcc5.2, However, I'm getting some compiler errors like <code>Error: expecting string instruction after `rep'</code> which is probably due to an old version of the binutils. So I'll give an update once this has been fixed.

**Comment by severun** [comment]
Ok guys, I got it working! Thanks for all the support and sticking with me on this :) :+1: 
If you are interested in any additional information about this case, please let me know!
