### ISSUE TITLE
More details on the reduce_codesize tag used for arc

### ISSUE THREAD

**Issue by advaitjain** [tensorflow/tensorflow#42932]
@tensorflow/micro

This came up during the review for PR #42020 in [this comment](https://github.com/tensorflow/tensorflow/pull/42020#discussion_r483160984)

The TFLM team would like to understand better what this `reduce_codesize` tag is doing in `micro/examples/micro_speech/arc_emsdp/Makefile`

Topics of discussion:

 * In the current design, TAGS was mostly meant as a way to allow for multiple optimized kernel implementations. While not enforced, the expectation is that each tag has a corresponding directory in micro/kernels/

 * We are planning on making some changes in the interest of being able to register different kernel variants that might be useful for this instead of what appears to be a find and replace.

**Comment by advaitjain** [comment]
Tagging @JaccovG and @dzakhar since this issue is requesting more info.

**Comment by dzakhar** [comment]
Hi,
As described, in the makefile, this tag does sources modifications to use a specific version of kernel in the exact “find and replace” way.  It gives a notable reductione in total size of application by removing not-used versions of optimized kernels, which is important for us. Same mechanism is used in `micro/examples/person_detection_experimental/arc_emsdp/Makefile` 

We considered several options to deal with it including an application specific version of the library, or moving part of library available for application build. However, since we are planning some related changes to our library in the future, we concluded that this current solution would be acceptable in the interim as something which could be done quickly

We are looking forward to migrating to your proposed kernels registration methodology when it will be available. Can you give more information/reference about it so we can assess how it can fits to our needs?

**Comment by advaitjain** [comment]
#43682 is a first implementation of the changes that allow kernels to support registration of a subset of functionality from the application code via the MicroMutableOpResolver.

Let me know if this is something that you guys can leverage.
