### ISSUE TITLE
tf.nn.ctc_greedy_decoder: self define the output node's name

### ISSUE THREAD

**Issue by bittergourd1224** [tensorflow/tensorflow#42946]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 1.15
- Are you willing to contribute it (Yes/No): Maybe

**Describe the feature and the current behavior/state.**
There's no "name" argument in the current "tf.nn.ctc_greedy_decoder", in both tensorflow 1.15 and tensorflow 2. 
But it does has one in "tensorflow.python.ops.gen_ctc_ops.ctc_greedy_decoder", which the "tf.nn.ctc_greedy_decoder" inherits from.  
So why not add a "name" argument, so users can define the name of output node's name of  "tf.nn.ctc_greedy_decoder" by themselves, and locate it easily? 

**Will this change the current api? How?**
Only need to make a little change to "tf.nn.ctc_greedy_decoder"

**Who will benefit with this feature?**
Everyone who uses this function. 

**Any Other info.**
Actually, I also wonder what's the default output node's name of tf.nn.ctc_greedy_decoder?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
