### ISSUE TITLE
tf.nn.max_pool2d: No support for tf.Tensor input for ksize

### ISSUE THREAD

**Issue by luuzk** [tensorflow/tensorflow#42973]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10.0.19041
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: -
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.0
- Python version: 3.7.6
- Bazel version (if compiling from source): -
- GCC/Compiler version (if compiling from source): -
- CUDA/cuDNN version: 11.0/7.6.5
- GPU model and memory: RTX 2070 8GB

**Describe the current behavior**
The ksize arguement of tf.nn.max_pool2d supports only native Python int but not tf.Tensor. This is not a problem when using eager mode, but very disadvantageous when calculating the ksize as a Tensor in TF Graph mode.

`TypeError: Expected int for argument 'ksize' not <tf.Tensor 'random_uniform:0' shape=() dtype=int32>.`

**Describe the expected behavior**
Tensor support for tf.nn.max_pool2d function parameters, espacially ksize.

**Standalone code to reproduce the issue**
```
@tf.function
def issue():
    inp = tf.convert_to_tensor(np.arange(75).reshape((1, 5, 5, 3)))
    ksize = tf.random.uniform([], 1, 3, dtype=tf.int32)
    return tf.nn.max_pool2d(inp, [ksize], 1, "SAME")

if __name__ == "__main__":
    issue()
```

**Other info / logs**
[traceback.txt](https://github.com/tensorflow/tensorflow/files/5177269/traceback.txt)

Thank you in advance!

**Comment by bhack** [comment]
Check https://stackoverflow.com/questions/43574076/tensorflow-maxpool-with-dynamic-ksize
And https://github.com/tensorflow/tensorflow/issues/4746

**Comment by Shreerama9** [comment]
Specifying shape in ksize may help u,

a = 1        # a can be '1','2' or '4' 
ksize = tf.random.uniform([a], 1, 3, dtype=tf.int32)

or 

ksize = tf.random.uniform(shape = [],minval = 1,maxval = 3, dtype=tf.int32)

**Comment by lutzzz** [comment]
Thank you @bhack! There seems to be a solution for this issue provided by PR #11875. Use `gen_nn_ops.max_pool_v2` instead of `gen_nn_ops.max_pool`, which is used by default when calling `tf.nn.max_pool2d`. Change the code above to:
```
from tensorflow.python.ops import gen_nn_ops
return gen_nn_ops.max_pool_v2(inp, [1, ksize, ksize, 1], [1, 1, 1, 1], "SAME")
```
PR #14983 tries to integrate the utilization of `gen_nn_ops.max_pool_v2` as standard behavior but was reverted. @yongtang @rmlarsen, are you interested to push PR #14983 into `tensorflow:master` to completely solve this issue, #1967 and, #4746?

**Comment by sachinprasadhs** [comment]
Was able to reproduce your issue in Tensorflow 2.5 version, please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/f267af22e1879854802a153e7d5123ba/42973.ipynb). Thanks!

**Comment by cl886699** [comment]
> ```
> from tensorflow.python.ops import gen_nn_ops
> return gen_nn_ops.max_pool_v2(inp, [1, ksize, ksize, 1], [1, 1, 1, 1], "SAME")
> ```
this is not worked for me

**Comment by chunduriv** [comment]
Was able to reproduce your issue in Tensorflow 2.8 version, please find the gist [here](https://colab.research.google.com/gist/chunduriv/7c118d3199933746d64d8ec9b03f08f6/42973.ipynb). Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
