### ISSUE TITLE
AttributeError: module 'tensorflow_addons.layers' has no attribute 'SpectralNormalization'

### ISSUE THREAD

**Issue by kanishk-awadhiya** [tensorflow/tensorflow#42982]

**Comment by bhack** [comment]
Please, compile the ISSUE template. Thanks

**Comment by amahendrakar** [comment]
@kanishk-awadhiya,
In order to expedite the trouble-shooting process, please provide the complete code to reproduce the issue and also the TensorFlow version you are using. 

Also, make sure you have updated the tensorflow_addons package to the latest version i.e. v0.11.2.

I was able to import the `SpectralNormalization` without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c819ef3de49e6d809e305dec47a67eee/42982.ipynb). Thanks!
