### ISSUE TITLE
Support INT16 quantisation for RESIZE_NEAREST_NEIGHBOR

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#43080]
Per issue #43064 I'm requesting the RESIZE_NEAREST_NEIGHBOR of int16 implementation.

`RuntimeError: Quantization to 16x8-bit not yet supported for op: 'RESIZE_NEAREST_NEIGHBOR'.` 

Thanks.

**Comment by Saduf2019** [comment]
@peter197321 
please share the code anf tf version or colab gist for us to analyse.

**Comment by macenpav** [comment]
Hi @Saduf2019 
this is the code we have been experimenting with https://gist.github.com/macenpav/404e65a23affc193a428d96a7260a2f4

There is a workaround using tf.lite.OpsSet.TFLITE_BUILTINS, but that creates quantize/dequantize nodes, i.e. f32 layer because RESIZE_NEAREST_NEIGHBOR is not supported (in the UpSampling layer).

On tensorflow==2.3.0 it prints just:
RuntimeError: Quantization to 16x8-bit not yet supported for op: 

On tf-nightly (tf_nightly-2.4.0.dev20200910-cp37-cp37m-win_amd64.whl) it shows which op is not supported:
RuntimeError: Quantization to 16x8-bit not yet supported for op: 
RESIZE_NEAREST_NEIGHBOR

**Comment by mohantym** [comment]
Hi @peter197321 ! Above Runtime error is not replicating in the [2.8](https://colab.sandbox.google.com/gist/mohantym/6e25e54f77088017a30e6bb9a5d1f4f0/untitled51.ipynb#scrollTo=ih4AjcuXPSNQ) version now. Can we move this issue to closed status now?
