### ISSUE TITLE
Input_c/Input_h shape in Cudnn LSTMP

### ISSUE THREAD

**Issue by YoPatapon** [tensorflow/tensorflow#43095]
Hi, I'm using Cudnn LSTMP as implemented here: [https://github.com/tensorflow/tensorflow/blob/v1.15.0/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py#L1848](url).

I have a question about the shapes of **input_h** and **input_c** in the `__call__` method. Why the shape is `[n_layers, batch_size, n_proj]` for both shapes. In LSTM cell, `h` is of shape `[n_layers, batch_size, n_proj]` while **c** is of shape `[n_layers, batch_size, n_units]`. I would really be appreciated if you could explain.

**Comment by jvishnuvardhan** [comment]
@YoPatapon Sorry for the late response. I cannot access the link you mentioned above. Can you please use recent TF version and let me know if you see any issue. 

Please note that GitHub is mainly for Bug/performance related issue. If your issue is not related to bug/performance, please file an issue in Stackoverflow where there is larger community to support general questions. Thanks!
