### ISSUE TITLE
tensorflow.python.framework.errors_impl.UnknownError: 

### ISSUE THREAD

**Issue by Shobana1230** [tensorflow/tensorflow#43133]
I tried  to test the face filter model which i had in my system. when i run the test script i am getting the following error. In cpu it is running without any issue but in gpu its causing the issue.

tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.
	 [[{{node conv2d_1/Conv2D}} = Conv2D[T=DT_FLOAT, data_format="NCHW", dilations=[1, 1, 1, 1], padding="SAME", strides=[1, 1, 1, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/device:GPU:0"](conv2d_1/Conv2D-0-TransposeNHWCToNCHW-LayoutOptimizer, conv2d_1/Conv2D/ReadVariableOp)]]

**Comment by ravikyram** [comment]
@Shobana1230 

Request you to fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).

This error might arise due to incompatibility between the cuda  and cuDNN version.

Please, see build tested configurations for [Linux/mac OS](https://www.tensorflow.org/install/source#tested_build_configurations), [windows
](https://www.tensorflow.org/install/source_windows#tested_build_configurations).

Refer similar issues #24828, [SO link](https://stackoverflow.com/questions/53698035/failed-to-get-convolution-algorithm-this-is-probably-because-cudnn-failed-to-in) and see if it helps you. Thanks!

**Comment by Shobana1230** [comment]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below):1.12.0
- Python version:3.6.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):gcc 7.5
- CUDA/cuDNN version:cuda 9.0
- GPU model and memory: GTX 1660

**Comment by ravikyram** [comment]
@Shobana1230 

TF 1.x is not actively supported. Can you please upgrade to TF 2.3 and see if the issue still persists. Thanks!
