### ISSUE TITLE
[EfficientNet] Understanding architectural implementation decision for the Squeeze and Excitation phase

### ISSUE THREAD

**Issue by AlexandruPurdila** [tensorflow/tensorflow#43146]
The following question refers to "Squeeze and Excitation" block from the EfficientNet implementation (https://github.com/tensorflow/tensorflow/blob/v2.3.0/tensorflow/python/keras/applications/efficientnet.py#L517-L540), lines 478 - 498.

Concretely, "Squeeze and Excite" current implementation makes use of two Conv2D blocks: one for filters reduction at line 483 and the other one for filters expanding at line 491.

Giving the fact that the input in this two Conv2D layers is just an array of features reshaped into a 3D tensor (of shape (1, 1, nr_features) according to line 482), the operations that this layers are doing is just a standard one-shot matrix multiplication followed by and activation (as in exactly what a Dense layer does by default).

Therefore, my question is why the implementation uses a Conv2D instead of a regular Dense layer? Is it because of easier code understanding/maintenance? I guess the reason could not be speed execution since both Dense and Conv2D make use of optimized matrix multiplication.

_Thanks, would really appreciate if this question can be answered as I can't find any docs that address this question._

**Comment by gowthamkpr** [comment]
@AlexandruPurdila Squeeze and Excitation phase is a method to give weightage to each channel instead of treating them all equally. You can get indepth understanding [here](https://datamonje.medium.com/image-classification-with-efficientnet-better-performance-with-computational-efficiency-f480fdb00ac6#:~:text=Squeeze%20and%20excitation%20(SE)%20block,by%20itself%20like%20other%20parameters.).
