### ISSUE TITLE
TextVectorization not working on TPU with tf-nightly.

### ISSUE THREAD

**Issue by Ankur3107** [tensorflow/tensorflow#43254]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow version (use command below):tf-nightly:2.4.0-dev20200915
- Using TPU: Yes

I am trying to run TextVectorization on TPU

```
def get_vectorize_layer(texts, vocab_size, max_seq, special_tokens=['[MASK]']):

  vectorize_layer = preprocessing.TextVectorization(
    max_tokens=vocab_size,
    output_mode='int',
    standardize = None,
    output_sequence_length=max_seq)
  
  vectorize_layer.adapt(texts)

  vocab = vectorize_layer.get_vocabulary()
  vocab = vocab[2:vocab_size-len(special_tokens)] + ['[MASK]']
  vectorize_layer.set_vocabulary(vocab)
  return vectorize_layer


vectorize_layer = get_vectorize_layer(data.text.values.tolist(), 20000, 196, special_tokens=['[MASK]'])
```
 Error:

> NotFoundError: 'OptimizeDatasetV2' is neither a type of a primitive operation nor a name of a function registered in binary running on n-86c78cbc-w-0. Make sure the operation or function is registered in the binary running in this process.

Tensorflow: 2.4.0-dev20200915
Reference Notebook: https://colab.research.google.com/drive/1QiQmA2M2WkwsjiHHxBhPM0Jw3_LBJnGV?usp=sharing

**Comment by ravikyram** [comment]
@Ankur3107 

I have tried in colab with TF version 2.3 and i am not seeing any issue. Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/94a3caa305a8d3476f03cfd2afbdc332/untitled358.ipynb).
However i am able to reproduce the issue in TF nightly version (`2.4.0-dev20200915`).Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/8ad11414ca33973fcbf402b68cc74bf6/untitled357.ipynb).Thanks!

**Comment by Ankur3107** [comment]
@ravikyram True, it's working with TF version 2.3. I need to use MultiHeadAttention that why i need tf-nightly. Thanks

**Comment by mkuchnik** [comment]
This seems to be due to a mismatch between TPU and host code. TPU doesn't have the same Graphdef API as the host.

Nightly build exposes OptimizeV2 as the [default op in Python code](https://github.com/tensorflow/tensorflow/blob/5c42efeedaa92b82fd9c6fe831a307c9fa5d4b6d/tensorflow/python/data/ops/dataset_ops.py#L4497), and the C++ interface on TPU is still expecting OptimizeV1 (OptimizeV2 is not a valid op in the GraphDef). 2.3 [still uses OptimizeV1](https://github.com/tensorflow/tensorflow/blob/ee598066c4cb31ec5ed3106e61ba99ef004a4bae/tensorflow/python/data/ops/dataset_ops.py#L386), which exists and can be deserialized just fine.

**Comment by mkuchnik** [comment]
@jsimsa

**Comment by jsimsa** [comment]
TensorFlow provide backwards compatibility (i.e. older client works with newer server) between minor versions but not forward compatibility (i.e. newer client works with older server). For more details see https://www.tensorflow.org/guide/versions.

The issue you have encountered is because you are using a newer client with older server, which is not guaranteed to work. In other words, there is nothing to fix here.

**Comment by Ankur3107** [comment]
thanks, @jsimsa @mkuchnik  @jvishnuvardhan @ravikyram. I got my answer,  there is nothing to fix here.!
