### ISSUE TITLE
Output of TensorFlow Java API differs from the one in TensorFlow Python

### ISSUE THREAD

**Issue by esgomezm** [tensorflow/tensorflow#43335]
Hi there, 

I'm processing an image with a TF trained model using the TensorFlow Java API but I get slightly different results from what the model outputs in python. 

The model was trained with TF version 1.15.2 in Python and libtensorflow-1.15.0.jar. 
Is there any well-known difference between the last two?

Thank you!

**Comment by amahendrakar** [comment]
@esgomezm,
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to v2.3 and check if you are facing the same issue?

Also, in order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the dataset you are using. Thanks!
