### ISSUE TITLE
XLA future

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#43374]
As declared the XLA shows promising results for certain use cases, its specialization for executable size reduction, and TensorFlow could use `tfcompile` tool that leverages XLA for ahead-of-time compilation (AOT). I would wonder if there is the implementation supporting other alternative backends and devices (e.g. ARM64)?
What is the interconnection between XLA and  TensorFlow Lite?

**Comment by bhack** [comment]
I don't know If @asaadaldien can comment here expecially on AArch64 experiments.

**Comment by bhack** [comment]
@peter197321 In the meantime I suggest you to take a look at:
https://github.com/tensorflow/mlir-hlo#overview
https://llvm.discourse.group/t/case-study-docs-on-vector-dialect-cpu-codegen/1674/15

**Comment by asaadaldien** [comment]
I am not familiar with `tf_compile`, but quickly looking at the AOT library build rules seems like `arm64`is already supported : 
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/aot/tfcompile.bzl#L430

**Comment by bhack** [comment]
@asaadaldien As the title Is also about the "XLA future" I think that you are involved in some  interesting codegen experimental activities on this arch right?

**Comment by sachinprasadhs** [comment]
`XLA` and `TFLite` does not have any connection between each other. 
`TFLite` does not make use of `XLA` because TensorFlow uses GraphDef (in ProtoBuf/PB format). 
TensorFlow Lite uses TensorFlow Lite model format (in FlatBuffer serialization format). These 2 execution runtimes are very disjoint. You won't be able to use TFLite with GraphDef (PB) model.
XLA is a compiler based operation, whereas TFLite does the model conversion and uses Interpreter and there is no involvement of compiler to use in TFLite environment.
