### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow'

### ISSUE THREAD

**Issue by PrivetMerhaba** [tensorflow/tensorflow#43459]
-using anaconda python v3.8
-working with jupyter notebook 
-try to add on cmd system --- conda install tensorflow but loading old version tensorflow and than give to me this error code:

```
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-62c45ef75a16> in <module>
----> 1 from tensorflow.keras.models import Sequential
      2 #modelleri oluşturmak için
      3 from tensorflow.keras.layers import Dense
      4 #katmanları da böyle oluştururuz

ModuleNotFoundError: No module named 'tensorflow'

**Comment by bhack** [comment]
We don't directly support Anaconda here.
Please use our official install guide https://www.tensorflow.org/install/pip

Anaconda has a third party support:
https://docs.anaconda.com/anaconda/user-guide/tasks/tensorflow/

**Comment by Saduf2019** [comment]
@PrivetMerhaba 
This could ocuur due to different reasons, as the error log has not been shared, please refer to [below issues](https://stackoverflow.com/questions/46568913/tensorflow-import-error-no-module-named-tensorflow):
#42761 - verify gast related issue.
#42233 - verify if python/cpu is not 32 bit it should be 64 bits.
#42367 - as you have python 3.8 ensure your tf version is 2.2 or above. [#27935 please verify your tf version]
[jupyter](https://www.heatonresearch.com/2019/09/03/tf-no-module-jupyter.html) related

**Comment by elijahmccoy** [comment]
You could be using a different installation of Python. Make sure you installed tensor flow to the correct spot and that you don't have multiple installations of Python.

You could consider using a venv to install Python and run your code using said venv.
