### ISSUE TITLE
Feature Request: Support for ragged argmin/argmax

### ISSUE THREAD

**Issue by atyshka** [tensorflow/tensorflow#43460]
**System information**
- TensorFlow version: 2.3.0
- Are you willing to contribute it: Possibly

**Describe the feature and the current behavior/state.**
tf.math.argmax/argmin does not support ragged tensors.
**Will this change the current api? How?**
No breaking changes, simply additive in nature.
**Who will benefit with this feature?**
In my opinion this is particularly important, as it can condense a ragged dimension down to a 1-dimension. In my use case, I have predictions that can be of variable length. I want to take the minimum, which would effectively eliminate the ragged dimension.
**Any Other info.**
For anyone else looking for a workaround, currently my approach is to convert the ragged tensor to a regular tensor. The default value should be max positive number if you are performing min or max negative number if you are performing max.

**Comment by aavishkarmishra** [comment]
Interested !!

**Comment by raghakot** [comment]
Here is a simple workaround.
```
indices = tf.map_fn(tf.math.argmax, ragged_tensor, fn_output_signature=tf.int64)
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
