### ISSUE TITLE
Add support for dataset to pandas dataframe

### ISSUE THREAD

**Issue by rd16395p** [tensorflow/tensorflow#43487]
**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

There is a feature for numpy conversion, but none for a conversion to a pandas dataframe. 

**Will this change the current api? How?**

It will add a function to do this, could be called as_dataframe()

**Who will benefit with this feature?**

Anyone who uses pandas over numpy or prefers pandas dataframes over numpy arrays. 

**Any Other info.**

Inspired by the feature in the datasets package:
https://www.tensorflow.org/datasets/api_docs/python/tfds/as_dataframe

**Comment by aaudiber** [comment]
Does this need to be in core tf.data? It seems simple enough to call `tfds.as_dataframe(dataset)` instead of `dataset.as_dataframe()`.

**Comment by rd16395p** [comment]
@aaudiber Wouldn't it make it more accessible as the numpy function is if a user is unaware of the tfds package?

**Comment by aaudiber** [comment]
Fair enough, it will be much easier to find if it's in the Dataset API. I think we could add it, but we need to be very clear that it won't work for large datasets, and that it needs to wait to load the entire dataset, which could take some time. I see the tfds implementation relies on their `dataset_utils.as_numpy(tf.data.Datasaet)` implementation. We would probably want a similar `tf.data.Dataset.as_numpy()`. @jsimsa what are your thoughts?

**Comment by jsimsa** [comment]
I would be open to adding support for `tf.data.experimental.as_numpy(dataset)` and `tf.data.experimental.as_dataframe(dataset)`.

**Comment by rd16395p** [comment]
Can I help with coding this new feature?

**Comment by nelsonlin2708968** [comment]
Is this open to being coded still?

**Comment by aaudiber** [comment]
Yes, contributions are still welcome here

**Comment by rd16395p** [comment]
@nelsonlin2708968 I was hoping to work on this soon, if you want to tackle it together. 👍

**Comment by hfahrudin** [comment]
Can i join on working on this feature? I just starting to get my feet wet on tensorflow dev stuff.

**Comment by rd16395p** [comment]
@habernal Sure! Just message me for details. 👍

**Comment by AdityaKane2001** [comment]
Is this issue still open? Would like to work on this one.

**Comment by rd16395p** [comment]
@AdityaKane2001 Sure, you can join! Feel free to send me a message.

**Comment by hfahrudin** [comment]
It seems like the PR already closed. Do you have any plan to reopen it? @rd16395p

**Comment by rd16395p** [comment]
@hfahrudin Yes I do, commented on the pr.

**Comment by SigireddyBalasai** [comment]
is this still on

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
