### ISSUE TITLE
Feature Request: Support sparse to dense with max_length input

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#43490]
Using tensorflow 2.3, some times I found I need tfrecords with tf.io.VarlenFeature, but when using tpu or for some other reasons you might need to pad it to fixed max_length like 50, 200(fixed) not just using padded_batch or tf.sparse.to_dense to padd it to the max length in the batch(dynamic).

It is ok if you pre padding to max_length when generating tfrecords but that is wasting space and also reduce flexbilty.

I'd like padded_batch(x, max_length), tf.sparse.to_dense(x, max_length) or just set tf.io.VarlenFeature(max_length).

Will this feature be possible ? Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
