### ISSUE TITLE
Official Tensorflow build for s390x CPU

### ISSUE THREAD

**Issue by jperezpbos** [tensorflow/tensorflow#43500]
There is currently a Tensorflow on Linux s390x CPU Stable Release as well as a Tensorflow on Linux s390x Nightly build. Both under the category of community builds. 

User story:
As a developer Tensorflow user, I want to be able to work with an official Tensorflow build for s390x so I can have certainty on the lifecycle and I can communicate to my end users (enterprises) that I work with an official Tensorflow version.

There is a growing demand for ML applications in the s390x arch platform, recent feedback from large enterprise customers like banks are working on ML models in the same platforms where their mission-critical apps are, s390x.

**Comment by mihaimaruseac** [comment]
i don't understand the ask in the issue? What should we do?

**Comment by jperezpbos** [comment]
@mihaimaruseac thanks for getting back to me.   The ask is to have an official Tensorflow build for s390x architecture. Today is only a community build.
If there's a process to upgrade a build from "community build" to "official build" I'm requesting to go through that process.

**Comment by mihaimaruseac** [comment]
Unfortunately we don't have enough CI infrastructure and developers to maintain this build internally.

**Comment by jperezpbos** [comment]
@mihaimaruseac if you guys are open to get help, I can talk to my IBM colleagues. We can certainly help with infrastructure and we have engineers already contributing upstream.

**Comment by mihaimaruseac** [comment]
But then that's equivalent to the other community builds.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
