### ISSUE TITLE
RuntimeError: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.Failed to apply the default TensorFlow Lite delegate indexed at 0.

### ISSUE THREAD

**Issue by le8888e** [tensorflow/tensorflow#43569]
Hi,

I tried to use build XNNPack with respect of accelerating tflite inference on CPU. I built tensorflow2.4 from source code with flag "--define tflite_with_xnnpack=true".When I run inference with my .tflite model with BiLSTM layer, ther is an error:
RuntimeError: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.Failed to apply the default TensorFlow Lite delegate indexed at 0.

But when I run a ResNet50 tflite model downloaded on TensorFlow Hub, no error occurs. What's more, I tried to run my tflite model with tf-nightly 2.4.0-dev20200917 and no error occurs.

What's probably going wrong? Thank you.

**Comment by Saduf2019** [comment]
@le8888e 
Please provide with simple stand alone code to replicate issue faced along with error logs or if possible share a colab gist with issue reported.

**Comment by mattiadg** [comment]
I have the same problem. I converted an encoder-decoder model for machine translation using two separate tflite models respectively for the encoder and the decoder.

The encoder uses BiLSTM and generates the error in the title. The same error doesn't occur if I use `unroll=True`, but this is unfeasible for me as I need input sequences of length 100. In this case, I don't get the error but then the usage of RAM explodes.

The decoder, on the other hand, uses input of length 1 and LSTMCell instead of LSTM, and it doesn't produce the error.

Is there a way to make the operation static-length without using unroll?

**Comment by kassianl26** [comment]
> I have the same problem. I converted an encoder-decoder model for machine translation using two separate tflite models respectively for the encoder and the decoder.
> 
> The encoder uses BiLSTM and generates the error in the title. The same error doesn't occur if I use `unroll=True`, but this is unfeasible for me as I need input sequences of length 100. In this case, I don't get the error but then the usage of RAM explodes.
> 
> The decoder, on the other hand, uses input of length 1 and LSTMCell instead of LSTM, and it doesn't produce the error.
> 
> Is there a way to make the operation static-length without using unroll?

up

**Comment by mohantym** [comment]
Hi @le8888e @ mattiadg @kassianl26 !

Have you checked this issue in [Fusion Code lab ](https://colab.sandbox.google.com/github/tensorflow/tensorflow/blob/master/tensorflow/lite/examples/experimental_new_converter/Keras_LSTM_fusion_Codelab.ipynb )instruction with Nightly(2.12dev) version. 
Could you create a new issue with stand alone code to reproduce this issue.

Thank you!
