### ISSUE TITLE
Wrong example script in the docs for preprocessing data

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#4358]
I was reading the [docs for preprocessing][1], which is a small paragraph linking to the [CIFAR-10 network][2] as an example. However, that script does not perform any preprocessing. Do we have a better example illustrating preprocessing steps like data normalization, distorting images, etc?

[1]: https://www.tensorflow.org/versions/r0.10/how_tos/reading_data/index.html#preprocessing
[2]: https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/models/image/cifar10/cifar10.py

**Comment by andydavis1** [comment]
This is a question better suited for StackOverflow. Please ask it there and tag it with the `tensorflow` tag."

**Comment by danijar** [comment]
@andydavis1 Are you sure? I'm mainly pointing at a "bug" in the docs. I'm not asking for anything, my question was just to suggest a way of improving the docs.

**Comment by andydavis1** [comment]
Ah ok. I took that last sentence you wrote " Do we have a better example illustrating preprocessing steps like data normalization, distorting images, etc?". As a general question.

**Comment by wilesdaliglass** [comment]
The folder holding the file referenced in the docs has, e.g. https://github.com/tensorflow/tensorflow/blob/r0.10/tensorflow/models/image/cifar10/cifar10_input.py, which does contain a `distorted_inputs` routine, is this what you're looking for? If so, then the easiest fix is just to change the link in the docs to point to the cifar10_input.py file instead of the cifar10.py file that imports it (line 47)

**Comment by danijar** [comment]
Thanks. Yes, I think that would be suitable. Do you want to create a pull request? Otherwise, I can do that.

**Comment by wilesdaliglass** [comment]
You can go ahead.
