### ISSUE TITLE
Failed to build on Cuda-11.1

### ISSUE THREAD

**Issue by sephiroce** [tensorflow/tensorflow#43588]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: related to servers
- TensorFlow installed from (source or binary): source
- TensorFlow version: commit: a0b68d1ecc46f9bbc8fad4f18c68f25c6bd5ae48
- Python version: 3.6
- Installed using virtualenv? pip? conda?: none
- Bazel version (if compiling from source): 3.1.0
- GCC/Compiler version (if compiling from source): 7.5.0-3ubuntu1
- CUDA/cuDNN version: CUDA-11.1, CuDNN 8.0.3 for CUDA-11.0
- GPU model and memory: RTX 3090, 24GB, RTX Titan, 24GB, RTX 2080Ti, 11GB (total three GPUs)

**Describe the problem**
Hello,
failed to compile Tensorflow.
Please check the log messages then give me an advice.
Thanks!

**Provide the exact sequence of commands / steps that you executed before running into the problem**
(Including logging messages)
bazel build --config=mkl //tensorflow/tools/pip_package:build_pip_package

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.
```
tensorflow$ deactivate
sephiroce@bike:~/open_source/tensorflow$ bazel build --config=mkl //tensorflow/tools/pip_package:build_pip_package
WARNING: Ignoring JAVA_HOME, because it must point to a JDK, not a JRE.
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=228
INFO: Reading rc options for 'build' from /home/sephiroce/open_source/tensorflow/.bazelrc:
  Inherited 'common' options: --experimental_repo_remote_exec
INFO: Reading rc options for 'build' from /home/sephiroce/open_source/tensorflow/.bazelrc:
  'build' options: --apple_platform_type=macos --define framework_shared_object=true --define open_source_build=true --java_toolchain=//third_party/toolchains/java:tf_java_toolchain --host_java_toolchain=//third_party/toolchains/java:tf_java_toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=0 --define=use_fast_cpp_protos=true --define=allow_oversize_protos=true --spawn_strategy=standalone -c opt --announce_rc --define=grpc_no_ares=true --noincompatible_remove_legacy_whole_archive --noincompatible_prohibit_aapt1 --enable_platform_specific_config --config=short_logs --config=v2
INFO: Reading rc options for 'build' from /home/sephiroce/open_source/tensorflow/.tf_configure.bazelrc:
  'build' options: --action_env PYTHON_BIN_PATH=/home/sephiroce/virtualenv/py3-tf2-gpu/bin/python3 --action_env PYTHON_LIB_PATH=/home/sephiroce/virtualenv/py3-tf2-gpu/lib/python3.6/site-packages --python_path=/home/sephiroce/virtualenv/py3-tf2-gpu/bin/python3 --config=xla --action_env CUDA_TOOLKIT_PATH=/usr/local/cuda-11.1 --action_env TF_CUDA_COMPUTE_CAPABILITIES=8.6 --action_env LD_LIBRARY_PATH=/home/sephiroce/open_source/rdkit/build/lib:/usr/local/cuda/lib64:/usr/local/lib:/usr/local/lib/openmpi:/home/sephiroce/local/lib:/usr/lib/x86_64-linux-gnu:/usr/lib: --action_env GCC_HOST_COMPILER_PATH=/usr/bin/x86_64-linux-gnu-gcc-7 --config=cuda --action_env TF_CONFIGURE_IOS=0
INFO: Found applicable config definition build:short_logs in file /home/sephiroce/open_source/tensorflow/.bazelrc: --output_filter=DONT_MATCH_ANYTHING
INFO: Found applicable config definition build:v2 in file /home/sephiroce/open_source/tensorflow/.bazelrc: --define=tf_api_version=2 --action_env=TF2_BEHAVIOR=1
INFO: Found applicable config definition build:xla in file /home/sephiroce/open_source/tensorflow/.bazelrc: --define=with_xla_support=true
INFO: Found applicable config definition build:cuda in file /home/sephiroce/open_source/tensorflow/.bazelrc: --config=using_cuda --define=using_cuda_nvcc=true
INFO: Found applicable config definition build:using_cuda in file /home/sephiroce/open_source/tensorflow/.bazelrc: --define=using_cuda=true --action_env TF_NEED_CUDA=1 --crosstool_top=@local_config_cuda//crosstool:toolchain --define=tensorflow_enable_mlir_generated_gpu_kernels=1
INFO: Found applicable config definition build:mkl in file /home/sephiroce/open_source/tensorflow/.bazelrc: --define=build_with_mkl=true --define=enable_mkl=true --define=tensorflow_mkldnn_contraction_kernel=0 -c opt
INFO: Found applicable config definition build:linux in file /home/sephiroce/open_source/tensorflow/.bazelrc: --copt=-w --host_copt=-w --define=PREFIX=/usr --define=LIBDIR=$(PREFIX)/lib --define=INCLUDEDIR=$(PREFIX)/include --cxxopt=-std=c++14 --host_cxxopt=-std=c++14 --config=dynamic_kernels
INFO: Found applicable config definition build:dynamic_kernels in file /home/sephiroce/open_source/tensorflow/.bazelrc: --define=dynamic_loaded_kernels=true --copt=-DAUTOLOAD_DYNAMIC_KERNELS
INFO: Repository local_config_cuda instantiated at:
  no stack (--record_rule_instantiation_callstack not enabled)
Repository rule cuda_configure defined at:
  /home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl:1407:18: in <toplevel>
ERROR: An error occurred during the fetch of repository 'local_config_cuda':
   Traceback (most recent call last):
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1054, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 599, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1054, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 599, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1377
                _create_local_cuda_repository(<1 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 1054, in _create_local_cuda_repository
                _find_libs(repository_ctx, <2 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 599, in _find_libs
                _check_cuda_libs(repository_ctx, <2 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/gpus/cuda_configure.bzl", line 501, in _check_cuda_libs
                execute(repository_ctx, <1 more arguments>)
        File "/home/sephiroce/open_source/tensorflow/third_party/remote_config/common.bzl", line 208, in execute
                fail(<1 more arguments>)
Repository command failed
No library found under: /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1
INFO: Elapsed time: 1.183s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: tensorflow/tools/pip_package
```

**Comment by jaentrouble** [comment]
My graphics card: 3080
Cuda 11.1, ubuntu 20.04, cudnn 8.0.3 (the very recent one), python 3.8

I installed cuda 11.1 using the .deb file (to create all the symlinks automatically)
I think the problem is that CUDA11.1 installs symlink libcudart 11.0 but it does not create symlink for libcudart11.1. 
However, tensorflow tries to find libcudart 11.1, because cuda version is 11.1
I tried to make a symlink libcudart11.1 -> libcudart11.1.74 as suggested in here : https://github.com/tensorflow/tensorflow/issues/26150#issuecomment-469058265
However, then the error showed that SONAME did not match.
Next, I tried this method : https://github.com/tensorflow/tensorflow/issues/26289#issuecomment-477848947
I opened third_party/gpus/cuda_configure.bzl and searched for 'cudart'
Changed  cuda_config.cuda_version to "11.0"
For me, changing cuda_config.cuda_version of only cudart and cudart_static worked and I am currently building tensorflow.
My CPU is too slow (never expected to build tensorflow myself), so it will take a long time to see if it successfully builds, but until now, it is building without any errors.
I will update if anything happens.

**Comment by sephiroce** [comment]
Thanks!
It worked 👍  (I'm not sure the RTX 3090 is fully utilized or not though.)

**Comment by AeroScripts** [comment]
> It worked 👍 (I'm not sure the RTX 3090 is fully utilized or not though.)

sm_86 doesnt seem to be implemented in nvcc yet, at least not in the copy i have (same cuda/cudnn configuration) so there's probably still room for performance improvement

**Comment by jaentrouble** [comment]
> > It worked 👍 (I'm not sure the RTX 3090 is fully utilized or not though.)
> 
> sm_86 doesnt seem to be implemented in nvcc yet, at least not in the copy i have (same cuda/cudnn configuration) so there's probably still room for performance improvement

I ran a simple test training, and Conv2D operation was about 2~3 times faster than 2070super. The tensorboard profiling showed that 3080 did not use tensorcores, and the speed was actually a bit faster with fp32 than mixed precision. Considering some issues saying that using tensorcores does not speed up much, I think the performance is within the range of expectation. 
Oh, and by the way, profiling fails in CUDA11.1. It worked with CUDA11.0, but after I upgraded to CUDA11.1, segmentation fault happens.

**Comment by seledkapod** [comment]
> I ran a simple test training, and Conv2D operation was about 2~3 times faster than 2070super. The tensorboard profiling showed that 3080 did not use tensorcores, and the speed was actually a bit faster with fp32 than mixed precision. Considering some issues saying that using tensorcores does not speed up much, I think the performance is within the range of expectation.
> Oh, and by the way, profiling fails in CUDA11.1. It worked with CUDA11.0, but after I upgraded to CUDA11.1, segmentation fault happens with profile_batch turned on.

Please tell me what versions of CUDA and cuDNN did you use? And also a listing of a test training, if not difficult.

**Comment by jaentrouble** [comment]
> 
> Please tell me what versions of CUDA and cuDNN did you use, and the parameters at which the build was successful? And also a listing of a test training, if not difficult.
> 
> My platform:
> `OS: Windows 10 x64, Graphics Card: Palit RTX 3080`
> 
> My REQUIRED_PACKAGES were working for me:
> `python 3.6 absl-py==0.7.0 astunparse==1.6.3 gast==0.3.3 google_pasta==0.1.8 h5py==2.10.0 keras_preprocessing==1.1.1 opt_einsum==2.3.2 protobuf==3.9.2 tensorboard==2.3.0 tensorflow_estimator==2.3.0 termcolor==1.1.0 wrapt==1.11.1 wheel==0.26 six==1.12.0 numpy==1.18.5`
> 
> My build options that where working:
> `bazel build --config=opt --config=avx2_win --config=short_logs --define=no_tensorflow_py_deps=true --copt=-DTHRUST_IGNORE_CUB_VERSION_CHECK --copt=-nvcc_options=disable-warnings //tensorflow/tools/pip_package:build_pip_package`
> 
> I used cuDNN v8.0.3 (August 26th, 2020), for CUDA 11.0 and Latest Release CUDA Toolkit 11.1 (Sept 2020), but this required renaming cudart64_110.dll to cudart64_111.dll and cufftw64_10.dll to cufftw64_11.dll for the test vgg16 model to work
> 
> With CUDA Toolkit 11.0 Update1 (Aug 2020) and cuDNN v8.0.3 (August 26th, 2020), for CUDA 11.0 i got:
> `nvcc fatal : Unsupported gpu architecture 'compute_86'`

OK, here's all I have tried since installing 3080
`Ubuntu 20.04`
`cuDNN v8.0.3`

1. `CUDA 11.0 Update1 `

As you mentioned, building from the source with compute compatibility 8.6 failed.
I think it's because CUDA 11.0 does not support 30 series geforce graphics card.
They added 30 series in CUDA 11.1
However, installing with `pip tf-nightly` works.
The problem with pypi installation is that it does not recognize sm_86, and spits out
`ptxas fatal : Value 'sm_86' is not defined for option 'gpu-name'` and compiles ptxas every single time it launches.
Tensorboard profiling worked in this case.

2. `CUDA 11.1`

  - `pip tf-nightly`
It still works.
Tensorflow does fail to find libcudart.so.11.1 (as CUDA 11.1 does not make libcudart.so.11.1 nor libcudart.so.11 symlink), but because Tensorflow then searches for libcudart.so file, it managed to load libcudart.so anyway.
However, it still does not recognize sm_86 and compiles ptxas everytime it starts.
Moreover, Tensorboard profiling does not work. (segmentation fault)

  - Build from source
This is the case I mentioned above.
In my case, making symlink for libcudart.so.11.1 did not work. 
I had to edit third_party/gpus/cuda_configure.bzl file.
With this build, it now recognizes sm_86 and does not compile ptxas anymore.
However, tensorboard profiling error consists.

3. In both `CUDA 11.0 Update1` and `CUDA 11.1`

They both have to set `set_memory_growth=True`, or they spit out errors when predict and/or fit a model with Conv layers.
This problem does not care how big the model is. Even with a single Conv layer, it just fails.

About testing, I used customized HRNet. It has batchnorm, Conv2D, Conv2D Transpose, Global pooling average and Dense layers.
It is the only log I have left with profiling turned on using 2070super, so I only compared with this model.
I think I can get my profiling function back if I downgrade to CUDA 11.0, but I really do not want to change anything anymore, until new versions come out.

**Comment by summa-code** [comment]
Why is this closed ?

**Comment by jaentrouble** [comment]
> Why is this closed ?

Because the chief complaint of this issue is failing to build on CUDA-11.1, and at least building tensorflow is successful.

**Comment by minsky-1** [comment]
How to change the value of cuda_config.cuda_version to 11.0
cudart": _check_cuda_lib_params(
            "cudart",
            cpu_value,
            cuda_config.config["cuda_library_dir"],
            cuda_config.cuda_version,    <-------------------- here
            static = False,
        ),
        "cudart_static": _check_cuda_lib_params(
            "cudart_static",
            cpu_value,
            cuda_config.config["cuda_library_dir"],
            cuda_config.cuda_version,               <--------------------------- and here
            static = True,
        ),
Please, I am not too good at python...

**Comment by jaentrouble** [comment]
> How to change the value of cuda_config.cuda_version to 11.0
> cudart": _check_cuda_lib_params(
> "cudart",
> cpu_value,
> cuda_config.config["cuda_library_dir"],
> cuda_config.cuda_version, <-------------------- here
> static = False,
> ),
> "cudart_static": _check_cuda_lib_params(
> "cudart_static",
> cpu_value,
> cuda_config.config["cuda_library_dir"],
> cuda_config.cuda_version, <--------------------------- and here
> static = True,
> ),
> Please, I am not too good at python...

I meant literally changing it to "11.0"

- Before :
cuda_config.config["cuda_library_dir"],
cuda_config.cuda_version,
static = False,

- After:
cuda_config.config["cuda_library_dir"],
"11.0",
static = False,

**Comment by minsky-1** [comment]
Thank you very much for the so swift help. I am not being able to build tensorflow with bazel. Somebody wrote that the soultion is to change the version to  11.0, since I use cuda11.1 and cudnn8... I changed the version as you kindly suggested, but I still can not build it. After changing I still get these errors:
ERROR: An error occurred during the fetch of repository 'local_config_cuda':ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
WARNING: Target pattern parsing failed.
ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):


I feel so sorry but some help would be very much appreciated.

**Comment by jaentrouble** [comment]
> Thank you very much for the so swift help. I am not being able to build tensorflow with bazel. Somebody wrote that the soultion is to change the version to 11.0, since I use cuda11.1 and cudnn8... I changed the version as you kindly suggested, but I still can not build it. After changing I still get these errors:
> ERROR: An error occurred during the fetch of repository 'local_config_cuda':ERROR: Skipping '//tensorflow/tools/pip_package:build_pip_package': no such package '@local_config_cuda//cuda': Traceback (most recent call last):
> WARNING: Target pattern parsing failed.
> ERROR: no such package '@local_config_cuda//cuda': Traceback (most recent call last):
> 
> I feel so sorry but some help would be very much appreciated.

What specific CUDA version/CUDNN version/ OS are you using?

**Comment by minsky-1** [comment]
Thank you very much for your answer.
I am using  cuda-11.1 and libcudnn8-8.0.0.180-1, and I my system is linux_suse_x86-64.

**Comment by jaentrouble** [comment]
Ok. things to try:

1. Install cudnn 8.0.4 or 8.0.3
8.0.4 is the cudnn which supports cuda 11.1.
I had no problem building with cudnn 8.0.3, and am currently building with cudnn 8.0.4 without any errors right now.
(My cpu is not so good. It takes ages to complete building)
Honestly, I do not think this is the problem, but give it a try.

2. Check your cuda path.
When executing configure file before building with bazel, does that properly recognize your cuda and cudnn?
If not so, check LD_LIBRARY_PATH and PATH.

**Comment by minsky-1** [comment]
Thousand thanks for your reply. I will try. Yeah, something strange happened. Actually, I have installed cuda10.2 in my system, and when running the .configure of tensor flow, it asks for the cuda version and so on, and the program would go to limbo, it would ask for the cudnn version, and also for the RT support and so on. Then I thought that the problem would be not having "cupy" installed, because I want to use GPU's, and the card I got is a GeForce GTX 1060 6GB.  It was also kind of cumbersome to install cupy, but finally I did. Suddenly .configure would ask all these questions again, but now the default cuda, was the cuda11.1, and the defalut cudnn would be cudnn7.1. But the cudnn installed was the cudnn8.0.0. So I input that, and then .configure finished, indicating the options to run bazel. I thought I succeeded, but now I am facing this problem for more than a week. My LD_LIBRARY_PATH and PATH are pointing to my cuda-10.2 installation, and it seems that .configure doesn't care. It automatically goes to thecuda11.1 installation.

**Comment by jaentrouble** [comment]
If you are using gtx 1060, I really suggest using cuda 10.1 or  10.2, not 11.x.
For me, I have 3080 which does not work with cuda 10 so I have to use cuda 11.
However, right now, there is absolutely no benefit for using cuda 11.

Whether or not you still want to use cuda 11, I recommend uninstalling CUDA completely and reinstalling CUDA. 
Something seems to be messed up.

**Comment by minsky-1** [comment]
I have no words to thank you for your time. You got almost the best GPU card in the market. Does it maintain a low temperature? Well, comparatively I mean. Let me then re-install cuda-10.2 and the libcuddnn corresponding is 
Then I will have to uninstall cuda11.1 that suddenly appeared when I installed "cupy", and then re-install cuda. In fact I got cuda and cuda10.2 which are the same. My CUDA_HOME points to /usr/local/cuda. And I will proceed with cudnn-8.0.4

**Comment by minsky-1** [comment]
Now, in Linux SUSE-15.1  cuda 10.2 and libcudnn8.0.0.0.180.1 come pre installed.

**Comment by jaentrouble** [comment]
I looked up cupy installation document briefly. It seems like it does not require CUDA 11.1.
If you do not need 11.1 for any other reason, I recommand you to go for cuda 10.1 and cudnn 7.6.5
(Compatibility matrix : https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html)
I haven't used SUSE, so I am not sure whether installing cuda 10.1 will be successful, but if possible, it is the most stable configure for tensorflow.
As you said, remove all cuda related things first, and then install cuda 10.1 with corresponding cudnn (recommend 7.6.5).
If CUDA11.1 was installed when installing cupy, try installing cupy-cuda101 (or cupy-cuda102 if you want to use 10.2)

**Comment by minsky-1** [comment]
OK, I will follow your advice. Thank you very much. Hope this time around I can install tensorflow with the GPU's. Because I installed one, indeed, but pycharm keeps warning that even though it detects the GPU, it can't use it... So I need this bazel installation.

**Comment by minsky-1** [comment]
Hello, how are you? I am still fighting with the installation of TF, and when I thought I did, the monitor suddenly went off, and after 10 or 12 minutes it came back and this is the state. Do you think the installation is going well? Because for some time it doesn´t continue.
  Thank you for your comments.
________________________________
差出人: jaentrouble <notifications@github.com>
送信日時: 2020年10月7日 5:24
宛先: tensorflow/tensorflow <tensorflow@noreply.github.com>
CC: minsky-1 <delcmca@hotmail.com>; Comment <comment@noreply.github.com>
件名: Re: [tensorflow/tensorflow] Failed to build on Cuda-11.1 (#43588)


I looked up cupy installation document briefly. It seems like it does not require CUDA 11.1.
If you do not need 11.1 for any other reason, I recommand you to go for cuda 10.1 and cudnn 7.6.5
(Compatibility matrix : https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html)
I haven't used SUSE, so I am not sure whether installing cuda 10.1 will be successful, but if possible, it is the most stable configure for tensorflow.
As you said, remove all cuda related things first, and then install cuda 10.1 with corresponding cudnn (recommend 7.6.5).
If CUDA11.1 was installed when installing cupy, try installing cupy-cuda101 (or cupy-cuda102 if you want to use 10.2)

**Comment by minsky-1** [comment]
Hello,
  I am still struggling with the TF installation, and thought everything was going OK, when suddenly the computer has stopped. This happened last time, after I changed as you advised me. But the computer was back after 3 hours or so. But this time, its more than 12 hours and it doesn´t come back.
Do you think I should force shutdown and retry? It has stopped as I show in the photo. How far am I from installing it?  Thank you for your time.


________________________________
差出人: jaentrouble <notifications@github.com>
送信日時: 2020年10月6日 8:02
宛先: tensorflow/tensorflow <tensorflow@noreply.github.com>
CC: minsky-1 <delcmca@hotmail.com>; Comment <comment@noreply.github.com>
件名: Re: [tensorflow/tensorflow] Failed to build on Cuda-11.1 (#43588)


Ok. things to try:

  1.  Install cudnn 8.0.4 or 8.0.3
8.0.4 is the cudnn which supports cuda 11.1.
I had no problem building with cudnn 8.0.3, and am currently building with cudnn 8.0.4 without any errors right now.
(My cpu is not so good. It takes ages to complete building)
Honestly, I do not think this is the problem, but give it a try.

  2.  Check your cuda path.
When executing configure file before building with bazel, does that properly recognize your cuda and cudnn?
If not so, check LD_LIBRARY_PATH and PATH.

**Comment by ElhamSol** [comment]
Hi,

I'm having issues with building TF 2.3.

OS: Ubuntu 18.04
GPU: RTX2080
CUDA: 11.1
cudNN: 8.0.4
TensorRT: 7.2

I already tried :
changing it to "11.0"

Before :
cuda_config.config["cuda_library_dir"],
cuda_config.cuda_version,
static = False,

After:
cuda_config.config["cuda_library_dir"],
"11.0",
static = False,

Please see the following to see what happened and let me know what else I should do.

root:~/tensorflow# ./configure
You have bazel 3.1.0 installed.
Please specify the location of python. [Default is /usr/bin/python3]: /usr/bin/python3


Found possible Python library paths:
  /usr/lib/python3/dist-packages
  /usr/local/lib/python3.7/dist-packages
Please input the desired Python library path to use.  Default is [/usr/lib/python3/dist-packages]
/usr/lib/python3/dist-packages
Do you wish to build TensorFlow with OpenCL SYCL support? [y/N]: n
No OpenCL SYCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with ROCm support? [y/N]: y
ROCm support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Do you wish to build TensorFlow with TensorRT support? [y/N]: y
TensorRT support will be enabled for TensorFlow.

Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 649, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 641, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 579, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 255, in _find_cuda_config
    get_header_version)
  File "third_party/gpus/find_cuda_config.py", line 241, in _find_header
    required_version, get_version)
  File "third_party/gpus/find_cuda_config.py", line 230, in _find_versioned_file
    actual_version = get_version(file)
  File "third_party/gpus/find_cuda_config.py", line 247, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''
Asking for detailed CUDA configuration...

Please specify the CUDA SDK version you want to use. [Leave empty to default to CUDA 10]: 11.1


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 7]: 8.0.4


Please specify the TensorRT version you want to use. [Leave empty to default to TensorRT 6]: 7.2


Please specify the locally installed NCCL version you want to use. [Leave empty to use http://github.com/nvidia/nccl]:


Please specify the comma-separated list of base paths to look for CUDA libraries and headers. [Leave empty to use the default]: /lib,/lib/x86_64-linux-gnu,/usr,/usr/lib/x86_64-linux gnu/libfakeroot,/usr/local/cuda,/usr/local/cuda-11.1,/usr/local/cuda-11.1/targets/x86_64-linux/lib,/TensorRT-7.2.0.14


Traceback (most recent call last):
  File "third_party/gpus/find_cuda_config.py", line 649, in <module>
    main()
  File "third_party/gpus/find_cuda_config.py", line 641, in main
    for key, value in sorted(find_cuda_config().items()):
  File "third_party/gpus/find_cuda_config.py", line 579, in find_cuda_config
    result.update(_find_cuda_config(cuda_paths, cuda_version))
  File "third_party/gpus/find_cuda_config.py", line 255, in _find_cuda_config
    get_header_version)
  File "third_party/gpus/find_cuda_config.py", line 241, in _find_header
    required_version, get_version)
  File "third_party/gpus/find_cuda_config.py", line 230, in _find_versioned_file
    actual_version = get_version(file)
  File "third_party/gpus/find_cuda_config.py", line 247, in get_header_version
    version = int(_get_header_version(path, "CUDA_VERSION"))
ValueError: invalid literal for int() with base 10: ''
Asking for detailed CUDA configuration...

**Comment by minsky-1** [comment]
Hello my friend.
I succeeded with the installation, it recognizes the card, and all the cublas libraries...!!!
And it is working in tandem with pycharm...
 Thank you very much for your replies. It took me half the month to do so.
I installed python3.7, then I had to reinstall python3.6, because cuda was running with python3.6.
I have neve had a problem like this. But it is done. Thank you for your help...

________________________________
差出人: jaentrouble <notifications@github.com>
送信日時: 2020年10月7日 5:24
宛先: tensorflow/tensorflow <tensorflow@noreply.github.com>
CC: minsky-1 <delcmca@hotmail.com>; Comment <comment@noreply.github.com>
件名: Re: [tensorflow/tensorflow] Failed to build on Cuda-11.1 (#43588)


I looked up cupy installation document briefly. It seems like it does not require CUDA 11.1.
If you do not need 11.1 for any other reason, I recommand you to go for cuda 10.1 and cudnn 7.6.5
(Compatibility matrix : https://docs.nvidia.com/deeplearning/cudnn/support-matrix/index.html)
I haven't used SUSE, so I am not sure whether installing cuda 10.1 will be successful, but if possible, it is the most stable configure for tensorflow.
As you said, remove all cuda related things first, and then install cuda 10.1 with corresponding cudnn (recommend 7.6.5).
If CUDA11.1 was installed when installing cupy, try installing cupy-cuda101 (or cupy-cuda102 if you want to use 10.2)

**Comment by S3Stellar** [comment]
Another RTX 3080 user here, trying to make CUDA 11.1 with cuDNN and tensorflow works (using conda to make my environment) but fail to do so, I get that I have to use latest cuda as it supports my card, but there seems to be so many conflicts upon trying to make the environment, if someone got a solution would really help~

**Comment by jcastagneri** [comment]
Can verify that I was able to start compiling from [this](https://github.com/tensorflow/tensorflow/issues/43588#issuecomment-699592351) answer above!

**Comment by bheu** [comment]
Another resolution is to modify soname in libcudart.so.
sudo patchelf --set-soname libcudart.so.11.1 /usr/local/cuda-11.1/targets/x86_64-linux/lib/libcudart.so.11.1.74
But the system will show the file was truncated.
