### ISSUE TITLE
some questions for coreml_executor.mm 

### ISSUE THREAD

**Issue by ToBigboss** [tensorflow/tensorflow#43589]
I have a few questions for tensorflow/lite/experimental/delegates/coreml/coreml_executor.mm:
1.  line 143: id<MLFeatureProvider> outputFeature = [_model predictionFromFeatures:inputFeature options:options error:&error];
How does Coreml recognize custom constructs TensorData?

2.line 80: if ([featureName cStringUsingEncoding:NSUTF8StringEncoding] == input.name) {}
featureName  is output name of network and input.name is input name of network, the network output node name must not be equal to the input node name, this code doesn't make sense?

**Comment by teijeong** [comment]
Hi @ToBigboss, thanks for asking!

1. The `inputFeature` has type of `MultiArrayFeatureProvider`, inherited from [`MLFeatureProvider`](https://developer.apple.com/documentation/coreml/mlfeatureprovider) class. It's initializer handles `TensorData` struct, and the interface `FeatureValueForName` is actually called from Core ML side. That being said, `MultiArrayFeatureProvider` parses `TensorData` struct and returns appropriate `MLFeatureValue` for a name provided. (The logic that you mentioned in question 2.)

2. The `MultiArrayFeatureProvider` is only used for inputs, so that the internal vector of `TensorData` struct is also named `_inputs`. Outputs are handled from line 150, and note that the output's `MLFeatureProvider` is the base class one, not the `MultiArrayFeatureProvider`, thus nothing to do with the code inside `MultiArrayFeatureProvider` :) 

Please let me know if I missed something, or you need further clarifications. Thanks!

**Comment by ToBigboss** [comment]
> Hi @ToBigboss, thanks for asking!
> 
> 1. The `inputFeature` has type of `MultiArrayFeatureProvider`, inherited from [`MLFeatureProvider`](https://developer.apple.com/documentation/coreml/mlfeatureprovider) class. It's initializer handles `TensorData` struct, and the interface `FeatureValueForName` is actually called from Core ML side. That being said, `MultiArrayFeatureProvider` parses `TensorData` struct and returns appropriate `MLFeatureValue` for a name provided. (The logic that you mentioned in question 2.)
> 2. The `MultiArrayFeatureProvider` is only used for inputs, so that the internal vector of `TensorData` struct is also named `_inputs`. Outputs are handled from line 150, and note that the output's `MLFeatureProvider` is the base class one, not the `MultiArrayFeatureProvider`, thus nothing to do with the code inside `MultiArrayFeatureProvider` :)
> 
> Please let me know if I missed something, or you need further clarifications. Thanks!

get it，Thanks very much
