### ISSUE TITLE
Single threaded TensorFlow

### ISSUE THREAD

**Issue by fisakhan** [tensorflow/tensorflow#43671]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
TensorFlow should generate the specified number of threads, irrespective of the available number of CPUs or CPU cores. 
config.set_inter_op_parallelism_threads(1);
config.set_intra_op_parallelism_threads(1); is not enough to restrict the total number of generated threads.
Some related issues.
https://github.com/tensorflow/tensorflow/issues/33627
https://github.com/tensorflow/tensorflow/issues/42510

**Will this change the current api? How?**

**Who will benefit with this feature?**
People who discuss it at the following issues:
https://github.com/tensorflow/tensorflow/issues/33627
https://github.com/tensorflow/tensorflow/issues/42510

**Any Other info.**

**Comment by NeoZhangJianyu** [comment]
@fisakhan 
`config.set_inter_op_parallelism_threads(1);
config.set_intra_op_parallelism_threads(1);` can't work well because there would be many python libs to be executed in a AI script. It's possible other libs will enable multiple threads.

Above two parameters only limit the tensroflow train/infer.

There is simple method to limit one thread, like:
`numactl -C 1 python train.py`

It sets the python running on the No.1 CPU core only.
If you use 'htop', you will see only No.1 CPU core is busy.

**Comment by fisakhan** [comment]
@NeoZhangJianyu both of your suggestions are not working and have been properly discussed on https://github.com/tensorflow/tensorflow/issues/33627#issuecomment-675661637
numactl doesn't work because another C++ program (from another party) is calling my code and I have to control the number of thread from within my code.

**Comment by fisakhan** [comment]
If I build TensorFlow from source then what code should I change to disable threading by TensorFlow?

**Comment by bhack** [comment]
@fisakhan Have you tried to control also `OMP_THREAD_NUM`?

**Comment by fisakhan** [comment]
@bhack I use system(export OMP_NUM_THREADS=1)" in my C++ code but it looks like TensorFlow overwrites this setting. Can you please suggest how and where to use OMP_NUM_THREADS to force TensorFlow not to generate threads?
.

**Comment by bhack** [comment]
On master you can try to make a look at

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/threadpool_device.cc#L45:L69

**Comment by NeoZhangJianyu** [comment]
@fisakhan OK, I understand your case.

Currently, the method to control thread number by external is only for process, instead of library (your case).
The current env variables/parameters are only impact the AI operation part. Like OMP_NUM_THREADS and inter_op_parallelism_threads, intra_op_parallelism_threads.

I think they are working for AI operation of Tensorflow. But they won't impact the other part of tensorflow to use single thread or multiple threads. For example, load dataset.

Your case need whole tensorflow use single thread.
It's a little hard: even if the source code of tensorflow is changed to use single thread, but it's hard to make sure the 3rd party libs used by tensorflow to use single thread.

I have two alternatives:
1. Modify the source code of tensorflow to set the thread number variables to 1 by hard code.
It's  big work, and would be fault, because it can't control the 3rd party lib.

2. Refactor your software structure:
Sperate the software into two processes. The function call is changed to IPC.
Your code is running as child process and receive the parameters/return result by IPC.
So the thread number can be controlled by 'numactrl'.

**Comment by NeoZhangJianyu** [comment]
@fisakhan 
Is there any feedback?

**Comment by fisakhan** [comment]
I'm still struggling with that.

**Comment by NeoZhangJianyu** [comment]
@fisakhan 

Good lucky!

Do you still need any support from Tensorflow with MKL view?

**Comment by NeoZhangJianyu** [comment]
@fisakhan 

If you don't know the support, could you close this issue?

**Comment by fisakhan** [comment]
This is not possible with tensorflow. I wonder how did some people control the tensorflow threads [here](https://github.com/usnistgov/frvt/issues/12).

**Comment by suraj-maniyar** [comment]
@fisakhan Were you able to disable multi-threading in Tensorflow C API?
I am also working on the same problem.

**Comment by fisakhan** [comment]
@suraj-maniyar No I couldn't. I still don't know how to do that.

**Comment by preethivenkatesh** [comment]
@fisakhan @suraj-maniyar can you try building tensorflow 2.4 with --config=mkl_threadpool instead of --config=mkl to use Eigen threadpool. this way you don't have to use omp threadpool and control through just setting  config.set_inter_op_parallelism_threads(1)
config.set_intra_op_parallelism_threads(1) and see if that solves the problem

**Comment by fisakhan** [comment]
@preethivenkatesh try it and then be confident in providing answer. Try...if..., try...if... doesn't work.

**Comment by suraj-maniyar** [comment]
@preethivenkatesh I got build errors when using --config=mkl_threadpool.
Could you please elaborate what all steps you followed to build Tensorflow 2.4?

**Comment by preethivenkatesh** [comment]
@suraj-maniyar 
bazel:3.1.0, 
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Here is the build command I used for c api
`bazel build --config=mkl_threadpool  //tensorflow/tools/lib_package:libtensorflow`

 For sanity check purpose, I tested the installer on Python for the  single-threaded behavior and was able to do it by setting the threads for all sessions in the script [here](https://github.com/IntelAI/models/blob/271256623b6dca4663cad409081af79c5d374b10/models/image_recognition/tensorflow/resnet50/inference/eval_image_classifier_inference.py). you can try to use this as a ref point to compare if your setting the sessions and configuring it to use 1 thread. 

   infer_config = tf.compat.v1.ConfigProto()
   infer_config.intra_op_parallelism_threads = 1
   infer_config.inter_op_parallelism_threads = 1
   infer_config.use_per_session_threads = 1

**Comment by NeoZhangJianyu** [comment]
@fisakhan @suraj-maniyar
As my understanding of your issue, you want to a program which call TF to work only use one thread.
The program's work include AI inference and other functions (like pre/post handle dataset).

The parameters above will only impact the TF inference behavior: use 1 thread to infer.
But the parameters can't control the program do other jobs with 1 thread.

Please check and find the code/function to use multiple threads in your case.
If TF AI inference code use multiple threads, we could continue check.
Else, it's another topic. Like load images by multiple workers, which are multiple threads. They need to be refactored to use single thread.
