### ISSUE TITLE
ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build

### ISSUE THREAD

**Issue by Dhananjay201** [tensorflow/tensorflow#43709]
model = tf.keras.Sequential([
layers.DenseFeatures(feature_columns),
layers.Dense(128,activation='relu'),
layers.Dropout(0.2),
layers.Dense(512,activation='relu'),
layers.Dropout(0.2),
layers.Dense(512, activation='relu'),
layers.Dense(31,activation='softmax')
])

This is my model.How do i solve this issue or add input shape to the first layer? Please help
When i try to save and load it with this piece of code 
model.save("my_model_tf",save_format="tf")
model_temp = keras.models.load_model('my_model_tf')
it works fine but when i write model.summary() it gives the above the title error.I have to deploy it on aws so it would be an issue there  so please help

**Comment by ritika-singh2000** [comment]
@Dhananjay201 , I am new to open source and DL .I think I can work on this .

**Comment by Dhananjay201** [comment]
@ritika-singh2000 Sure.Any help is appreciated.I think it is a bug with this whenever we use feature_columns to build a model.

**Comment by amahendrakar** [comment]
@Dhananjay201,
On running the given code snippet I am facing an error stating `NameError: name 'feature_columns' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/57260361ee70c003574113eba986021e/43709.ipynb).

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and the TensorFlow version you are using.

Also, please go through [this guide](https://www.tensorflow.org/tutorials/quickstart/beginner) for building a basic neural network using Keras and let us know if it helps. Thanks!
