### ISSUE TITLE
ParseTensor (tf.io.parse_tensor) is not vectorized - Vectorizing via tf.vectorized_map uses while_loop

### ISSUE THREAD

**Issue by mhorlacher** [tensorflow/tensorflow#43706]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution: Ubuntu 16.04
- TensorFlow installed from: Binary
- TensorFlow version: v2.3.0-rc2-23-gb36436b087 **2.3.0**
- Python version: 3.8
- CUDA/cuDNN version: 10.1
- GPU model and memory: TITAN V, 12G VRAM

**Describe the current behavior**
See the code below. I'm serializing a list of tensors and then attempt to parse them using (1) naive, single-record parsing and (2) batch-parsing using vectorized_map, which I expect to yield a significant performance increase. 

But: `tf.io.parse_tensor` appear to be not implemented for vectorized parsing, as I'm getting a `WARNING:tensorflow:Using a while_loop for converting ParseTensor` message and see little to no performance increase!

I find it very surprising that such an essential operation is not vectorized.. how else would I parse no-scalar features from e.g. a TFRecord file? Meanwhile, `tf.io.parse_example` is vectorized. 

**Describe the expected behavior**
I would expect that using a vectorized version of `tf.io.parse_tensor` to yield significant performance increase. 

**Standalone code to reproduce the issue**

```
import numpy as np
import tensorflow as tf

import time

# This would normaly come from some data stream, e.g. stream of TFRecords
some_tensor_list = [np.zeros(shape=(5,5), dtype=np.int32)]*100000
some_tensor_list_serialized = [tf.io.serialize_tensor(x) for x in some_tensor_list]

# Feed to tf.data
dataset = tf.data.Dataset.from_tensor_slices(some_tensor_list_serialized)

# Parsing whole batch back to tensors
def parse_batch(b):
    return tf.vectorized_map(lambda x: tf.io.parse_tensor(x, out_type = tf.int32), b)

# Parsing single record back to tensors
def parse_single(x):
    return tf.io.parse_tensor(x, out_type = tf.int32)

# Compare speed
def exaust_iterable(it):
    t = time.time()
    for _ in it:
        pass
    print(f'{time.time() - t}s')

# naive
dataset_naive = dataset.map(parse_single)

exaust_iterable(dataset_naive)

# vectorized over batch
dataset_vec = dataset.batch(32)
dataset_vec = dataset_vec.map(parse_batch)

exaust_iterable(dataset_vec)
```

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/5ebb056a8b89acfeaa0ed82ffa1593c2/43706-tf-nightly.ipynb). Thanks!

**Comment by Jephthia** [comment]
Just came across the same issue, I'm trying to do the following

1. Load my tfrecord dataset
2. Apply `batch`
3. Parse the batch of `tf.train.Example`s
4. Parse the batch of tensors

I'm unable to do `4.` since `tf.io.parse_tensor` only accepts a single tensor and not a batch of tensors.

Here's my code

```python
import tensorflow as tf

ds = tf.data.TFRecordDataset('ds.tfrecords')
ds = ds.batch(24) # Without this the code works fine

description = {
    'c_encoded': tf.io.FixedLenFeature([], tf.string)
}

for examples in ds:
    # Parse examples in batch
    parsed_example = tf.io.parse_example(examples, description)
    # Fails here since it can only parse one tensor at a time
    c_encoded = tf.io.parse_tensor(parsed_example['c_encoded'], out_type=tf.float32)
```

Maybe I'm missing something but what's the point of being able to parse a batch of `Example`s if you can't deserialize that batch of tensors? My options are to either loop through the batch and parse each tensor individually but that's less efficient or to batch my data prior to building my  tfrecords but that's less flexible if I want to quickly change the batch size.

Would be great to have a version of ` tf.io.parse_tensor` that accepts a batch.

**Comment by rmothukuru** [comment]
@mhorlacher,
Using [**`tf.function`**](https://www.tensorflow.org/guide/function) has resulted in significant performance increase. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/7157864b1c7e2ba77a848ee339027f04/43706-tf-nightly.ipynb). Thanks!

**Comment by zhangenzhi** [comment]
@Jephthia 

You can use a for-loop to deal with the batch problem of tf.io.parse_tensor, like this(using your code):

```python
import tensorflow as tf

ds = tf.data.TFRecordDataset('ds.tfrecords')
ds = ds.batch(24) # Without this the code works fine

description = {
    'c_encoded': tf.io.FixedLenFeature([], tf.string)
}

for examples in ds:
    # Parse examples in batch
    parsed_example = tf.io.parse_example(examples, description)
    # Fails here since it can only parse one tensor at a time
    # c_encoded = tf.io.parse_tensor(parsed_example['c_encoded'], out_type=tf.float32)

    # A for-loop
    c_encoded = []
    for i in range(24): 
        c_encoded.append(tf.io.parse_tensor(parsed_example['c_encoded'][i], out_type=tf.float32))
```

**Comment by Jephthia** [comment]
I am aware that I could loop over the batch and parse each tensor individually. I was hoping that I wouldn't need to do that and could simply call `tf.io.parse_tensor` on a batch of tensors. It seems weird to me that you can parse a batch of examples with `tf.io.parse_example` but when it comes to parsing these tensors you need to loop over each tensor because it can't handle a batch.

Is there a good reason why `tf.io.parse_example` is vectorized but not `tf.io.parse_tensor` ?

**Comment by mhorlacher** [comment]
@Jephthia I agree, that was exactly why I opened the issue - seems like a missed opportunity here. Currently, my models are not IO bottlenecked because the individual samples are quite big, but I would be really happy to see this resolved in future versions at some point.

**Comment by sjang92** [comment]
@mhorlacher , could you re-open this issue? This deserves proper attention. This issue prevents users from decoding tensors in batched tf.data pipelines

**Comment by sjang92** [comment]
To summarize the request, please include a vectorized version of tf.io.parse_tensor

**Comment by mhorlacher** [comment]
I agree with @sjang92 - this is still very much needed, specially for shallow models where IO is more of a bottleneck.

**Comment by zndr27** [comment]
I am also interested in a vectorized version of tf.io.parse_tensor

**Comment by wdy06** [comment]
I have same issue. I also hope verctorzied version of tf.io.parse_tensor.

**Comment by bmc2-stripe** [comment]
+1 on the need for this

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
