### ISSUE TITLE
regression in layer names for tf-operation layers in current tf-nightly (2.4) 

### ISSUE THREAD

**Issue by scd75** [tensorflow/tensorflow#43840]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0-dev20201006
- Python version: 3.7

**Describe the current behavior**
In the last tf-nightly release, when attributing a name to a layer created by a tf operation, this naming does not seem anymore to be effective anymore. 

**Describe the expected behavior**
the naming of the layer shall work as expected, as for tf 2.3

**Standalone code to reproduce the issue**
```
import tensorflow as tf
print(tf.__version__)

test = tf.keras.Input((1,), name='input1')
test2 = tf.identity(test, name='abcd')
print(test.name)
print(test2.name)
```

**Other info / logs** 
```
2.4.0-dev20201005
input1
tf.identity/Identity:0
```

**Comment by bhack** [comment]
I've tried to create https://github.com/tensorflow/tensorflow/pull/43844 that names `abcd/Identity:0`.

**Comment by scd75** [comment]
Thanks, is there a reason why you don't want to keep the current behavior from tf 2.3?

**Comment by bhack** [comment]
It is just that I don't know if there was any specific motivation for what we have After `/`. 
So.. just waiting for feedbacks.

**Comment by tomerk** [comment]
Hi @scd75 , we actually don't consider this a regression because we never made API guarantees about the exact ops or op names that would be generated for keras models. (and that applies to tf-op layers as well). I would be surprised if any TF code in 2.4/the nightlies relies on these in a load-bearing way, and I would be interested to know what use case you have that treats these names as load-bearing.

The release notes actually mention this change:
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md

```
* A major refactoring of the internals of the Keras Functional API may affect code that is relying on certain internal details:
...
  * Code that relies on the exact number and names of the op layers that TensorFlow operations were converted into. These may have changed.
```

```
Major Features and Improvements
---------------
....
* A major refactoring of the internals of the Keras Functional API has been completed, that should improve the reliability, stability, and performance of constructing Functional models.
```

```
* Improvements from the functional API refactoring:
  *Functional model construction does not need to maintain a global workspace graph, removing memory leaks especially when building many models or very large models.
  * Functional model construction should be ~8-10% faster on average.
  * Functional models can now contain non-symbolic values in their call inputs inside of the first positional argument.
  * Several classes of TF ops that were not reliably converted to Keras layers during functional API construction should now work, e.g. tf.image.ssim_multiscale
  * Error messages when Functional API construction goes wrong (and when ops cannot be converted to Keras layers automatically) should be clearer and easier to understand.
```

We could not complete this refactoring while guaranteeing that the op names produced by layers generated from TF API calls would stay the same (otherwise we would have done so).

I also see you reported a separate issue #43824. Although I can't repro it in the colabs I would actually expect this to be a non-issue in the nightlies, because the Keras tfoplambda layers after the refactoring don't set the generated op name as their own layer name.
