### ISSUE TITLE
Wrong linker flags in Makefile for ARM Compiler

### ISSUE THREAD

**Issue by jenselofsson** [tensorflow/tensorflow#43865]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): source
- Tensorflow version (commit SHA if source): 917882bfa2
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
Recently, --fatal-warnings and --gc-sections was added as linker flags to the Makefile. These flags is not available for ARM Compiler (armclang), the corresponding flags are instead --diag_error=warning and --remove.

I propose changing the makefile to something like this, in order to use the correct flags when the ARM Compiler is used.
https://github.com/jenselofsson/tensorflow/commit/dba2406f6c3396b1d936c53f4dcd6f763b0dafbf

If I'm not mistaken, the --remove flag is the default, but could be added in order to be consistent with the gcc-flags for readability.

**Comment by advaitjain** [comment]
Somewhat related to #43726 so tagging @mansnils as well.

I'd like to keep the `TAGS` list reserved the optimized kernel implementations. I recognize that its a catch-all name and I would like to change that too.

My suggestion here would be to add a new command line option called `TOOLCHAIN`, that can help select between armclang, gcc etc. rather than adding armclang to the TAGS.

Then we would change
https://github.com/tensorflow/tensorflow/blob/84202f860fa45b0508a9a23aae4698fc044e0bb0/tensorflow/lite/micro/tools/make/Makefile#L39-L42

to something like:

```make
ifeq ($(TOOLCHAIN), armclang))
  CXX_TOOL := armclang++?
  CC_TOOL := ?
  AR_TOOL :=?
else
  # default to gcc
  CXX_TOOL := g++
  CC_TOOL := gcc
  AR_TOOL := ar
endif
```

And for the `LDFLAGS`:

```make
ifeq ($(TOOLCHAIN), armclang))
  LDFLAGS += \
    -Wl,--diag_error=warning \
    -Wl,--remove
else
  # default to gcc
  LDFLAGS += \
    -Wl,--fatal-warnings \
    -Wl,--gc-sections
endif
```

Will this work for you?

**Comment by jenselofsson** [comment]
Yes, that should work just fine.

**Comment by nkreeger** [comment]
https://github.com/tensorflow/tensorflow/issues/43887#event-3856301945

Is related for macos - MacOS uses clang for g++:
```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 11.0.0 (clang-1100.0.33.8)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by jenselofsson** [comment]
@nkreeger that does look related
