### ISSUE TITLE
No way to initialize Interpreter with Model reference in TensorFlowLiteSwift

### ISSUE THREAD

**Issue by ahmetaa** [tensorflow/tensorflow#43891]
**System information**
- TensorFlow version (you are using):

TensorFlowLiteSwift 2.3.0

- Are you willing to contribute it (Yes/No):

Maybe

**Describe the feature and the current behavior/state.**

For inference you need to use Interpreter class. But all initializers uses model file parameters. This prevents sharing of the model in different threads.  

**Will this change the current api? How?**

Yes, Model class needs to be public and Interpreter class will need new initializer functions.

**Who will benefit with this feature?**

Who wants to use inference in separate threads.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
