### ISSUE TITLE
please expose uniform_full_int on tf.random

### ISSUE THREAD

**Issue by amitport** [tensorflow/tensorflow#43937]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.2
- Are you willing to contribute it (Yes/No): no

**Describe the feature and the current behavior/state.**
This request is about adding `tf.random.uniform_full_int` similarly to how `tf.random.uniform` exists

it's currently not trivial to get the full range of ints using `tf.random.uniform` (specifically because maxval is expected to be of the int type but is exluded from the range)

**Will this change the current api? How?**
Yes, adding `tf.random.uniform_full_int` similarly to how `tf.random.uniform` exists

(note that there is `tf.random.Generator.uniform_full_int`, but this request applies to `tf.random`)

**Comment by wangpengmit** [comment]
I'll add this.

**Comment by amitport** [comment]
Any news on this?
I think it is reasonable to just say Generators are the only way to go in tf, but please also deprecate the old `tf.random.uniform` and the like, otherwise the differences in these APIs make things harder to reason about and test.

**Comment by wangpengmit** [comment]
I got preempted and haven't got to it. Fancy contributing a PR?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
