### ISSUE TITLE
How to use custom tensorflow op for CUDA?

### ISSUE THREAD

**Issue by WzwzzZ** [tensorflow/tensorflow#43994]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Window 10 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version: 2.3
- Python version: 3.7
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:10.1 7.6.5
- GPU model and memory: GTX 1060 6G

**Describe the problem**
Recently I am researching deformable convolution, because i can't find a tf2.3 version to use, i use a tensorflow python api build, it is too slow. I want to learn how to use a cuda version to get better performance.
thanks for advice.

**Comment by ravikyram** [comment]
@WzwzzZ 

Please, refer this [tutorial](https://www.tensorflow.org/guide/create_op) and see if it helps you.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!

**Comment by WzwzzZ** [comment]
Thanks, I'll try it.
