### ISSUE TITLE
 model = GDO.minimize(totalLoss) TypeError: minimize() missing 1 required positional argument: 'var_list'

### ISSUE THREAD

**Issue by mariamalbarghouti** [tensorflow/tensorflow#44151]
*i am trying to use Gradient Descent Optimizer in this function "wx+b".*

**the code is:**

    import os
    
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
    
    import tensorflow as tf
    
    w = tf.Variable([5.0], tf.float32)
    b = tf.Variable([7.0], tf.float32)
    
    def linearRegressionModel(x):
        return w * x + b
    
    def totalLoss(x, y):
        return tf.reduce_sum(tf.square(linearRegressionModel(x) - y))
    
    GDO = tf.keras.optimizers.SGD(0.01)
    model = GDO.minimize(totalLoss)
    for i in range(10000):
        model(x=[0, 1, 2, 3, 4, 5], y=[9, 7, 5, 3, 1, -1])
    print(w, b)

the result is:

**line 20, in <module>
    model = GDO.minimize(totalLoss)
TypeError: minimize() missing 1 required positional argument: 'var_list'
Process finished with exit code 1**

**Comment by sehoffmann** [comment]
The signature of `minimize()` is 

```
minimize(
    loss, var_list, grad_loss=None, name=None
)
```

As the error tells you, you're missing the second **required** parameter `var_list`, e.g `model.trainable_weights`

**Comment by amahendrakar** [comment]
@mariamalbarghouti,
As mentioned by @sehoffmann, the `minimize()` method requires two arguments. For more information, please take a look at the documentation [here](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/SGD#minimize). 

Also, this question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a TensorFlow bug or feature request. There is also a larger community that reads questions there. Thanks!
