### ISSUE TITLE
installation issue keras-preprocessing

### ISSUE THREAD

**Issue by mgood2** [tensorflow/tensorflow#44163]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

ERROR: Could not find a version that satisfies the requirement keras-preprocessing<1.2,>=1.1.1 (from tensorflow==2.3.1) (from versions: none)
ERROR: No matching distribution found for keras-preprocessing<1.2,>=1.1.1 (from tensorflow==2.3.1)

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@mgood2,
In order to expedite the trouble-shooting process, could you please provide the following details

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

and the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by amahendrakar** [comment]
Also, I was able to install the keras-preprocessing package without any issues, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/08af1a7cdfc4c1d33c9a37cd4c5502fd/44163.ipynb). 

Please update pip to the latest version using the below command and check if you are still facing the same issue.

`pip install --upgrade pip`

Thanks!
