### ISSUE TITLE
GPU Nightly links broken

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#4416]
The links to .whl files on https://github.com/tensorflow/tensorflow are broken for Linux GPU and Mac GPU

https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-linux/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.10.0-cp27-none-linux_x86_64.whl

https://ci.tensorflow.org/view/Nightly/job/nightly-matrix-mac-gpu/TF_BUILD_IS_OPT=OPT,TF_BUILD_IS_PIP=PIP,TF_BUILD_PYTHON_VERSION=PYTHON2,label=gpu-mac/lastSuccessfulBuild/artifact/pip_test/whl/tensorflow-0.10.0-py2-none-any.whl

**Comment by caisq** [comment]
This is because since the version string was updated from 0.10.0rc0 to 0.10.0, there hasn't been a passing build in the Linux GPU nightly configuration yet. See history: http://ci.tensorflow.org/view/Nightly/job/nightly-matrix-linux-gpu/

To work around this temporarily, use URLs in which 0.10.0 is replaced with 0.10.0rc0. It should resolve itself when they pass.
Sorry about the inconvenience.

**Comment by caisq** [comment]
The Linux GPU whl links should be working now.
