### ISSUE TITLE
mixed_float16 + example code = horrible performance on a GeForce GTX 1660 Ti

### ISSUE THREAD

**Issue by motrek** [tensorflow/tensorflow#44191]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.1 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): docker image (binary)
- TensorFlow version (use command below): 2.3.0 (v2.3.0-rc2-23-gb36436b087)
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.0
- GPU model and memory: Nvidia GeForce GTX 1660 Ti (mobile)

**Describe the current behavior**
I went to the TensorFlow guide on mixed precision, here:

https://www.tensorflow.org/guide/mixed_precision

... and copied the code/model as best I could. (I will attach my code.)

Inference performance decreases by a factor of ~4 when mixed_float16 is turned on. (GeForce GTX 1660 Ti)

I have tried several different input dimensions and model designs (including the model that I'm actually trying to optimize) and I can't find a combination where mixed_float16 doesn't decrease performance by a factor of 2-4x.

**Describe the expected behavior**
I understand that the 1660 Ti (chip name: TU116 SM) does not have Tensor Cores but it does have support for float16 and Nvidia advertises that its float16 throughput is twice that of float32, so I would expect some speedup from switching to mixed_float16. Instead I'm seeing enormous slowdowns.

**Standalone code to reproduce the issue**
I will attach my minimal-repro code to this issue.

[test.py.txt](https://github.com/tensorflow/tensorflow/files/5413328/test.py.txt)

**Comment by Saduf2019** [comment]
@motrek 
Please share a simple stand alone code to replicate the issue faced or is possible share a colab gist with issue reported.

**Comment by motrek** [comment]
> @motrek
> Please share a simple stand alone code to replicate the issue faced or is possible share a colab gist with issue reported.

Please note that I attached a file called "test.py.txt" to this issue. This is a small Python script that demonstrates the issue. I had to add the ".txt" extension to the file because the system would not allow me to upload a file with the extension ".py".

If you rename the file and run it on any system that has TensorFlow installed, it will create a model (the model from TensorFlow's page on mixed precision), then create some fake input data, and then measure how fast the model can do inference on that data.

Then uncomment the line that enables mixed_float16 and re-run the script. Note that the performance of inference decreases dramatically. (At least it does on a TU116 chip.)

On my 1660 Ti, the script does ~42,000 inferences per second when it's float32 and ~15,000 inferences when it's mixed_float16.

**Comment by motrek** [comment]
In addition to the script with the model from the TensorFlow mixed precision page that I already posted, here's a similar file containing the model that I'm really trying to optimize. It's a pretty straightforward sequential model with some convolutional filters and residual blocks.

Switching to mixed_float16 (see the lines that are commented out) causes this script to run exactly 4x slower on my computer.

[mymodel.py.txt](https://github.com/tensorflow/tensorflow/files/5417465/mymodel.py.txt)

**Comment by gowthamkpr** [comment]
@motrek Pls give us a minimal example to reproduce this issue. Also did you try reproducing this issue on colab using gpu.. if not please try it and share the gist. Thanks!

**Comment by motrek** [comment]
> @motrek Pls give us a minimal example to reproduce this issue. Also did you try reproducing this issue on colab using gpu.. if not please try it and share the gist. Thanks!

I'm not sure what's going wrong here but you're the second person to ask me for a minimal repro.

Are you guys not seeing that I attached a python script to the first post, called "test.py.txt"?

Just rename the file (remove the .txt extension) and run it. That's the minimal repro. The problem should be immediately obvious.

**Comment by reedwm** [comment]
I cannot reproduce on a Titan V or a P100, the latter which does not have tensor cores. My guess is that this issue is exclusive to the Geforce 16 series. Unfortunately I do not have such a card to debug.

@nluehr any ideas what the issue is? The compute capability of the GTX 1660 Ti is not listed on the [CUDA website](https://developer.nvidia.com/cuda-gpus) but according to [this review](https://www.anandtech.com/show/13973/nvidia-gtx-1660-ti-review-feat-evga-xc-gaming/2), the compute capability is 7.5. This card lacks tensor cores, so perhaps some code is getting confused and taking a slow path because it assumes tensor cores are present? The [mixed precision guide](https://www.tensorflow.org/guide/mixed_precision#supported_hardware) claims that all cards with compute capability of at least 7.0 greatly benefit from mixed precision; is this true of the GTX 1660 Ti?

**Comment by motrek** [comment]
> I cannot reproduce on a Titan V or a P100, the latter which does not have tensor cores. My guess is that this issue is exclusive to the Geforce 16 series. Unfortunately I do not have such a card to debug.

Thank you so much for even trying to reproduce this. If I could get this problem fixed, it would save me literally weeks of compute time for a project I'm working on.

**Comment by motrek** [comment]
Sorry, I don't know how labels work on these issues/threads but it seems like this issue is still "awaiting tensorflower." Was the label removed in error?

**Comment by rutgerkra** [comment]
Having the same issue here with a GTX 1660 (non Ti). Mixed precision performance is roughly 5 times slower than normal 32 bit.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
