### ISSUE TITLE
Heteregnous inference

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#44287]
I'm wondering if there is a procedure for inference calculation within a heterogeneous environment. The goal is to run graf inference as multiple its subgraph on the various processing unit (CPU, GPU). basically to split the inference workload across multiple CPUs, GPUs ... Is there any example or guide on how to do it?

**Comment by bhack** [comment]
Check https://www.tensorflow.org/tutorials/distribute/save_and_load?hl=en#the_tfsaved_model_api
And the glossary at https://www.tensorflow.org/api_docs/python/tf/distribute

**Comment by ravikyram** [comment]
@peter197321 

Please, see the [link](https://www.tensorflow.org/tutorials/distribute/save_and_load)  and see if it helps you.

This question is better asked on StackOverflow since it is not a bug or feature request. There is also a larger community that reads questions there and provide better and faster support for such issues. Thanks!
