### ISSUE TITLE
[TFLite] [GPU delegate] DataLayout::DHWC4 and ObjectType::OPENGL_SSBO input does not work

### ISSUE THREAD

**Issue by natario1** [tensorflow/tensorflow#44336]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Nexus 5X
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2.0 / 2.3.1
- Python version: 2.7.16
- Bazel version (if compiling from source): 2.0.0

**Describe the current behavior**

The GPU delegate readme explains how tensors are always converted to the DHWC4 format, which I understand, and by providing the input in the correct format we can avoid a useless copy.

I'm using a slightly modified build of tensorflow (See [v2.2.0](https://github.com/deepmedia/tensorflow/commit/7401fbb4fa0c94004865c089d8c89bdd566ad747) and [v2.3.1](https://github.com/deepmedia/tensorflow/commit/ac8aad5c55838566a26ed6725c966d399319c831)) in order to inject `OPENGL_SSBO` inputs into the delegate.

**In v2.2.0**, adding a SSBO with `DataLayout::DHWC4` would fail with a "Not supported" error.
The error was thrown in [these lines](https://github.com/tensorflow/tensorflow/blob/v2.2.0/tensorflow/lite/delegates/gpu/gl/api2.cc#L138-L141):

```c++
    // TODO(akulik): external object should propagate to internal.
    if (IsSameDef()) {
      return UnimplementedError("Not supported");
    }
```

**In v2.3.1**, a commit was added, named "Fix propagation of objects with same defs.", which removes this error:

https://github.com/tensorflow/tensorflow/commit/3e414c752be1a259c64b1f85a24e095d02dd5e2f

But it just removes the exception, without actually implementing the propagation. I could not find any other commit that includes the actual implementation. The result is that if I try to pass a DHWC4 SSBO, I get no error, but the input is all zeros. 
Am I missing something? If so, can you point me to the code/commit that actually reuses the input SSBO id? 

**Describe the expected behavior**

We should be able to send a SSBO buffer with DataLayout::DHWC4 and avoid a useless copy. If it's not implemented, we should get an error.

**Comment by impjdi** [comment]
Acknowledged.  I have forwarded the message to the person who modified that code but is on vacation.  Ping me again in a week or so if you don't hear back.

**Comment by natario1** [comment]
@impjdi pinging you as you requested. 

I also want to take this opportunity to ask about the CL delegate - is this feature currently broken for the CL delegate as well? Can we pass DHWC4 there? And does it even help, or maybe it makes it worse (original image is grayscale)? I guess the SSBO will have to be converted to some OpenCL primitive buffer.

**Comment by impjdi** [comment]
Thanks for the reminder.  Here's the response I'm forwarding.

Indeed the v2.2.0 included the issue which you just faced. The check was removed because objects with the same definitions are supported by DefaultTensorTie (see DefaultTensorTie::Init method). The cl you spotted is not enough to solve this issue, there must be 2 more changes in. If we open tensorflow/lite/delegates/gpu/gl/api2.cc history for the 2.3.1 version of TF:
https://github.com/deepmedia/tensorflow/commits/v2.3.1%2B/tensorflow/lite/delegates/gpu/gl/api2.cc
We see these two cls are also in:
1) https://github.com/deepmedia/tensorflow/commit/4000a5c75cdbe49d77bcac93a7f21070a31c4cce#diff-b767dbfafb3ad2d4475896f019215adc48c9318bc3414c0d2b94f7df18cfc1c2
2) https://github.com/deepmedia/tensorflow/commit/dffe6a0e810f4c3d9968ddb56fd58c8f405eb846#diff-b767dbfafb3ad2d4475896f019215adc48c9318bc3414c0d2b94f7df18cfc1c2
They help to make sure that in case of same defs the link is constructed correctly and handled by DefaultTensorTie. So, basing on the expected behaviour, I'd expect your code should reach this line when initializing the DefaultTie:
https://github.com/deepmedia/tensorflow/blob/ac8aad5c55838566a26ed6725c966d399319c831/tensorflow/lite/delegates/gpu/gl/api2.cc#L175
The fact that you get the empty values in the input tensor means that you likely reach this line instead
https://github.com/deepmedia/tensorflow/blob/ac8aad5c55838566a26ed6725c966d399319c831/tensorflow/lite/delegates/gpu/gl/api2.cc#L179
Can you debug a bit around why the conditions are not met there? If is_same_def == false, maybe you requested the internal object of the other data type than the external one and it really needs to be converted and created separately? More details on what inference options you used will help. Also, please share what data type did you use?

Answering your question regarding the OpenCL side support. The CL delegate behavior is similar: if DHWC4 ssbo is met the external gl-object will be just copied to internal cl-object with no internal data conversions. 

Hope this explanation will help debugging. Feel free to send a pull request if you'll manage to locate and fix the bug.

**Comment by natario1** [comment]
@impjdi that's not the case unfortunately, I correctly hit [L175](https://github.com/deepmedia/tensorflow/blob/ac8aad5c55838566a26ed6725c966d399319c831/tensorflow/lite/delegates/gpu/gl/api2.cc#L175), which means that `user_provided` and `is_same_def` are both true. I setup the object def as follows:

```cpp
tflite::gpu::ObjectDef get_gpu_object_def(bool is_dhwc4) {
    tflite::gpu::ObjectDef object_def;
    object_def.data_type = tflite::gpu::DataType::FLOAT32;
    object_def.data_layout = is_dhwc4 ? tflite::gpu::DataLayout::DHWC4 : tflite::gpu::DataLayout::BHWC;
    object_def.object_type = tflite::gpu::ObjectType::OPENGL_SSBO;
    object_def.user_provided = true;
    return object_def;
}
```

So that if I pass is_dhwc4=false, inference works, if not, I get blank results.

Given that L175 is hit I think the ObjectDef is not the culprit here. What's more suspicious is the SSBO usage/binding, I fail to see where my external SSBO (not the object def, but the concrete SSBO id passed to `InferenceRunner.SetInputObject`) is retrieved to be bound. Maybe it should be registered into the ObjectManager. Anyway this brings the investigation to much lower level components that I'm not confident with. I can easily add log calls though.

About inference options,

```
 auto options = TfLiteGpuDelegateOptionsV2Default();
 options.inference_preference = TfLiteGpuInferenceUsage::TFLITE_GPU_INFERENCE_PREFERENCE_SUSTAINED_SPEED;
 options.inference_priority1 = TfLiteGpuInferencePriority::TFLITE_GPU_INFERENCE_PRIORITY_MIN_LATENCY;
 options.inference_priority2 = TfLiteGpuInferencePriority::TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
 options.inference_priority3 = TfLiteGpuInferencePriority::TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
```

**Comment by natario1** [comment]
@impjdi could you please reach back to the author with my answer above? He seemed willing to help :-) in short, all that happens in the DefaultTensorTie is totally fine in my opinion:

- `user_provided && is_same_def == true` ✅
- `MaybeAllocateInternalObject` never called ✅
- `MaybeAllocateExternalObject` never called ✅
- `external_obj_` contains the SSBO id that I passed to `InferenceRunner.SetInputObject` ✅
- `CopyFromExternalObject` does nothing because no conversion should take place ✅

But then, I can't see who should bind this SSBO (contained in external_obj_) for the first op. The components that do the actual job (run shaders) seem to take buffers from the ObjectManager, but my external SSBO is never registered there (because it's not allocated by TF in MaybeAllocate*). Is this the issue? 

My concern with registering it is that maybe it would transfer ownership of the buffer to TF? Which would be bad, app should be responsible to release the SSBO.

**Comment by ekaterinaignasheva** [comment]
That is correct, to make the external SSBO available for the InferenceRunner, you need to register it prior to calling the InferenceRunner->Initialize() method. Could you please describe in more details the logic, or better share a piece of code, which is responsible fore the initialization of the InferenceRunner? The steps you described before sound reasonable and match the expected way of using delegate's API and its internal behaviour.

**Comment by natario1** [comment]
@ekaterinaignasheva thanks a lot for jumping in and for your hints. My logic is much simpler than you might think at this point, I'm using the regular TFLite flow (using Interpreter and TfLiteGpuDelegateV2Create). The only difference is that I have added setters for tensor definition and tensor object to the gpu delegate:

```cpp
void SetExternalObjectDef(int index, ObjectDef object_def); // called before ModifyGraphWithDelegate
void SetExternalTensorObject(int index, TensorObject tensor_object); // called before Invoke
```

See [here](https://github.com/deepmedia/tensorflow/commit/ac8aad5c55838566a26ed6725c966d399319c831) for the actual implementation. So the whole flow becomes: create interpreter; create the delegate; configure the delegate by passing a DHWC4 definition (using my `SetExternalObjectDef`. see [here](https://github.com/tensorflow/tensorflow/issues/44336#issuecomment-724700457) for actual def); apply the delegate (`ModifyGraphWithDelegate(delegate)`); allocate tensors; when available, pass the SSBO object to the delegate (using my `SetExternalTensorObject`); run the interpreter (`interpreter->Invoke()`).

Note that passing the `TensorObject` after modifying the interpreter graph with the delegate is legitimate, because the objects are passed to the inner components (InferenceRunner & TensorTie) at every Invoke call ([reference](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/lite/delegates/gpu/delegate.cc#L217)). The delegate is already aware of the ObjectDef and it doesn't need the actual SSBO id.

### DHWC4 Issues

The **first problem** is that the `DefaultTensorTie` is not registering the SSBO id to the ObjectManager. The tie has all the informations needed to do this, so I think it should be its responsibility to do so, especially because the object manager is a pretty low-level internal component. One possible solution is to add a few lines [here](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/lite/delegates/gpu/gl/api2.cc#L139-L140), like:

```cpp
...
external_obj_ = obj;
if (IsSameDef()) { 
  // This is a no-copy tie! Make the object manager aware of the actual ssbo ID.
  if (def().external_def.object_def.object_type == gpu::ObjectType::OPENGL_SSBO) {
      auto ssbo = absl::get_if<OpenGlBuffer>(&obj);
      GlBuffer buffer;
      RETURN_IF_ERROR(WrapSSBO(*ssbo, &buffer));
      RETURN_IF_ERROR(objects_->RegisterBuffer(def().id, std::move(buffer)));
  }
}
return absl::OkStatus();
```

But then the **second problem** is timing, because such updates to the object manager are not picked up by the `Runtime`. The runtime will create binding functions only once during [InferenceBuilder.Build](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/lite/delegates/gpu/gl/api2.cc#L573-L576), so by the time that the tensor tie receives the SSBO id through the InferenceRunner, the runtime is already initialized and won't pick up the new buffer.

So... The runner has setters to update the external TensorObject, yet the runtime expects the internal TensorObjects to be ready during InferenceBuilder.Build, so basically **before the runner is even returned**. This goes unnoticed with normal flow but it is a big design issue for no-copy DHWC4.

### Thoughts

Overall, no-copy DHWC4 i/o is pretty impossible at the moment? Or you have to hack very deep into the low level components. So I wouldn't say that this is implemented 😄 now I'm not an expert, not even a c++ developer, but one possible solution I see is to modify the runtime [MakeBindingFunc](https://github.com/tensorflow/tensorflow/blob/v2.3.1/tensorflow/lite/delegates/gpu/gl/runtime.cc#L147):

- When the object manager is that of internal nodes, keep everything as is
- When the object manager is that of edge nodes (`Runtime::external_objects_`, the one shared with the runner), the manager should be inspected **as part of the binding function**, not outside. An elegant implementation could use a new function called `MakeDeferredBindingFunc` which creates a lambda that calls `MakeBindingFunc` when invoked.

This would have a negligible impact on performance because it will only be done for i/o buffers, not internal nodes, and this object manager is typically extremely small. And it would fix the design issue where SSBO ids (or whatever other tensor type) are not picked after the tie setter is called.

What do you think?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
