### ISSUE TITLE
TF Lite GPU delegate - Selection of GPU device

### ISSUE THREAD

**Issue by svobora** [tensorflow/tensorflow#44332]
-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Platform independent
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: X
-   **TensorFlow installed from (source or binary)**: Source
-   **TensorFlow version (use command below)**: 2.3.0
-   **Python version**: 3.8
-   **Bazel version (if compiling from source)**: Doesn't matter
-   **GCC/Compiler version (if compiling from source)**: Doesn't matter
-   **CUDA/cuDNN version**: Doesn't matter
-   **GPU model and memory**: Nvidia Titan, Jetson, etc
-   **Exact command to reproduce**: Nope

### Describe the problem
I believe there is currently no way to select which GPU device is used by TF Lite. Even though it is supposed to be used on mobile devices, we already have builds for Windows, Linux (server and embedded), Android, and platforms i686, x86_64, armv7 etc. So basically we use it as our main inference library everywhere, as it is much smaller compared to full TF (which we also integrated). 

I believe GPU selection is a feature desired by many. We are willing to put our resources into coding this feature and creating a push request. Could you point us to a proper place in code where the GPU selection should be integrated? Both for opengl and opencl. Please also suggest how to expose GPU selection in the public API, which structure to modify. We are mainly using the C API.

If we are just stupid and the feature is already present, please point us to it.

Thanks, r

**Comment by jdduke** [comment]
Hi @svobora, can you talk a bit more about your use-case and need for desktop GPU acceleration?

While TFLite supports many different platforms, including desktop platforms, our primary focus continues to be mobile/edge devices. Technically the GPU delegate can run using OpenCL, but we test and optimize primarily for mobile devices. If you can say more about what kind of workloads, models or use-cases you have in mind, we can try to find a better way to support you. Thanks.

**Comment by svobora** [comment]
Hi, thanks for the reply.

The use case is to be able to select which GPU device will be used on systems with more than 1 GPU. This should not interfere with the primary goal of TF Lite. From public API perspective, this could mean a new member variable in TfLiteGpuDelegateOptionsV2, like int32 gpu_id, with default gpu_id = 0 (this is how it works now).

Specifically, I am not discussing builds for other platforms to be included, just the option to select GPU based on OpenCL/OpenGL.

In TfLiteGpuDelegateV2Create, code could be added to call opengl/opencl gpu selection routines.

**Comment by svobora** [comment]
For the OpenCL part, the GPU can be selected in 
 
delegates/gpu/cl/cl_device.cc 

where line 

<code>*result = CLDevice(devices[0], platform_id);</code>

should be modified to accept gpu_id instead of selecting device with index 0.

The access to this functions can be made via 4 layers,

delegate.cc:  absl::Status InitializeOpenClApi(*)

api.cc absl::Status NewInferenceEnvironment(*)

api.cc   absl::Status Init(*)

cl_device.cc absl::Status CreateDefaultGPUDevice(*)

where in the top layer the delegate options are available. In the delegate options, I suggest to add gpu_id variable.

**Comment by jdduke** [comment]
@impjdi @srjoglekar246 any thoughts on the proposal?

**Comment by pkgoogle** [comment]
Hi @svobora, please feel free to create a PR, we will review it. Thanks.

**Comment by impjdi** [comment]
While I've seen this (or a similar request) in the past, it dropped off my radar and didn't respond to jdduke's question.  My apologies.

As jdduke mentioned above, TFLite is targeting mobile use cases.  We're well aware that it can also run on desktop, but due to limited resources, we can't officially support the use cases.  As the OP said, it's not difficult to add that in, but we can't support it afterwards, so I'd kindly ask that the OP does local modifications to use a different GPU for his/her use case, rather than making it an official API that needs to be supported by us.

**Comment by misterBart** [comment]
I faced the same issue as OP: the integrated GPU of the laptop was selected rather than the discrete GPU. I delved into the TfLite code and noticed in tensorflow/lite/delegates/gpu/cl/cl_device.cc that simply the first GPU of the first CL platform is selected. This is contrary to the code comment in lite/delegates/gpu/delegate.h, which states that the 'fastest available GPU' is selected. In any case, I created a PR that selects the fastest available GPU of all available CL platforms. Although my PR differs from the OP's request of manual GPU selection, I hope it also resolves his issue.

**Comment by svobora** [comment]
> I faced the same issue as OP: the integrated GPU of the laptop was selected rather than the discrete GPU. I delved into the TfLite code and noticed in tensorflow/lite/delegates/gpu/cl/cl_device.cc that simply the first GPU of the first CL platform is selected. This is contrary to the code comment in lite/delegates/gpu/delegate.h, which states that the 'fastest available GPU' is selected. In any case, I created a PR that selects the fastest available GPU (based on querying GPU capabilities) of all available CL platforms. Although my PR differs from the OP's request of manual GPU selection, I hope it also resolves his issue.

I already implemented proper GPU switching, but will not share it because maintainer is not interested.
