### ISSUE TITLE
Model not deterministic, even though os.environ['TF_DETERMINISTIC_OPS'] = '1' is set

### ISSUE THREAD

**Issue by stevenwong951028** [tensorflow/tensorflow#44414]
in reference of this [kaggle notebook](https://www.kaggle.com/devang/transfer-learning-with-keras-and-efficientnets) i've written this [notebook](https://drive.google.com/file/d/1VyaUGXgaCDIbWbt0-F0iHTIdokxWesJH/view?usp=sharing) to try transfer learning through multiple datasets.

With multiple soft runs on the notebook, I came to found out that I can't get deterministic/reproducible model out of it. 

Weird thing is, with the same virtual-environment, I can get deterministic/reproducible from a plain [CNN-MNIST](https://drive.google.com/file/d/1GpTupofffdaEufpMSvDkqnTpjiqP3mwC/view?usp=sharing) code. 

Spent a week on researching and can't find the solution. Any guidance or suggestions are much appreciated. 

[my environment](https://drive.google.com/file/d/1lfM5y2vylh9HkuduargAon9arNQKB9kQ/view?usp=sharing)

**Comment by amahendrakar** [comment]
@stevenwong951028,
On running the code, I am facing an error stating `FileNotFoundError: [Errno 2] No such file or directory: 'D:/img_db/stanford-dogs-dataset/images/Images/'`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/8e0360e4664bb42465019d639a85e82d/44414.ipynb#scrollTo=SDALvhOKhj1m).

In order to expedite the trouble-shooting process, could you please provide the dataset you are using in the code.

Also, the example is fairly complex and would be difficult for us to pinpoint the issue. Can you remove the dependencies + get the example down to the simplest possible repro? That will allow us to debug the issue easily. Thanks!

**Comment by stevenwong951028** [comment]
updated [colab code](https://colab.research.google.com/drive/1cqqdmrsQrlA7DDehnoEOXxqIt9WiwIMr?usp=sharing) for reproducing the error

might take a while for downloading the dataset and extracting the images

**Comment by amahendrakar** [comment]
@stevenwong951028,
On running the code I did not face any errors. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/80bab1577ed23f14476266acf011c537/44414.ipynb).

> With multiple soft runs on the notebook, I came to found out that I can't get deterministic/reproducible model out of it.

Could you please elaborate the issue you are facing and also the behavior you are expecting? Thanks!

**Comment by stevenwong951028** [comment]
@amahendrakar 
The error is that the code won't get reproducible results. 

To elaborate on that, in gpu environment, I get different results on the accuracy and the loss on every runs. With seeding and tf_deterministic_ops all set.  

The weird part is, I can get reproducible results on a plain cnn-mnist (in gpu environment)

**Comment by rmothukuru** [comment]
@stevenwong951028,
Sorry for the delayed response. Please refer this [Stack Overflow Answer](https://stackoverflow.com/questions/50744565/how-to-handle-non-determinism-when-training-on-a-gpu) which shows how to handle non-determinism with `Tensorflow-GPU`. Thanks!
