### ISSUE TITLE
Code snippet in the TensorFlow for Poets codelab is confusing

### ISSUE THREAD

**Issue by mrry** [tensorflow/tensorflow#4444]
Based on [this](http://stackoverflow.com/q/39562938/3574081) Stack Overflow question.

In [section 5](https://codelabs.developers.google.com/codelabs/tensorflow-for-poets/index.html?index=..%2F..%2Findex#4), the first `python` command has a leading `#`:

``` bash
# python tensorflow/examples/image_retraining/retrain.py \
--bottleneck_dir=/tf_files/bottlenecks \
--how_many_training_steps 500 \
--model_dir=/tf_files/inception \
--output_graph=/tf_files/retrained_graph.pb \
--output_labels=/tf_files/retrained_labels.txt \
--image_dir /tf_files/flower_photos
```

The second one doesn't:

``` bash
python tensorflow/examples/image_retraining/retrain.py \
--bottleneck_dir=/tf_files/bottlenecks \
--model_dir=/tf_files/inception \
--output_graph=/tf_files/retrained_graph.pb \
--output_labels=/tf_files/retrained_labels.txt \
--image_dir /tf_files/flower_photos
```

If you copy and paste the first command, you'll get an unintuitive error like `"--bottleneck_dir=/tf_files/bottlenecks: No such file or directory"`. We should remove the leading `#` or somehow make it clearer (and consistent across both snippets) that this is a shell prompt.

**Comment by michaeljancen** [comment]
Since `/tf_files/..` is an absolute path you probably have to make sure where this tensorflow folder is located and change the code to the following after chaning the directory with `cd` :

`python tf_files/tensorflow/examples/image_retraining/retrain.py --bottleneck_dir=tf_files/bottlenecks --how_many_training_steps 500 --model_dir=tf_files/inception --output_graph=tf_files/retrained_graph.pb --output_labels=tf_files/retrained_labels.txt --image_dir tf_files/images
`

**Comment by tatatodd** [comment]
FYI I'm looking into how to update the codelab, and will update this bug once it's resolved.

**Comment by tatatodd** [comment]
It looks like Wolff added the codelab - assigning to him to get it fixed up.

**Comment by wolffg** [comment]
I removed all the leading % and # (which I was using to indicated whether you were in or not in Docker).
