### ISSUE TITLE
Add WinRT (UWP) as a supported platform

### ISSUE THREAD

**Issue by ianier** [tensorflow/tensorflow#44463]
Feature request: Add WinRT as a supported target platform for the native library. This would allow using TF on Microsoft Store apps and would benefit projects like https://github.com/SciSharp/TensorFlow.NET.

I've performed a fair amount of analysis work in the scope of the vcpkg project (see https://github.com/microsoft/vcpkg/issues/14252 and https://github.com/microsoft/vcpkg/pull/13028), so this looks realistically feasible.

I realize that this feature has been requested already in #16514 long ago, but unfortunately it was closed without further explanation.

**Comment by ianier** [comment]
@amahendrakar : You may refer to https://github.com/microsoft/vcpkg/issues/14252#issuecomment-720606994 for a list of patches that result in a valid DLL.

**Comment by mihaimaruseac** [comment]
We won't be able to officially support this, but you could create it as a community build and maintain the build.

**Comment by ianier** [comment]
That's a pity, because it doesn't seem too complicated. I can live with the patching we've done at https://github.com/microsoft/vcpkg/issues/14252#issuecomment-720606994, which is relatively straightforward and produces a working binary.

@mihaimaruseac : however, would you be able to tackle at least #45151?

**Comment by mihaimaruseac** [comment]
The main issue is that our support matrix is too large whereas the team got severely reduced and rescoped. So we can only offer full support for x86_64 builds that are mentioned on the official site and anything that diverges is on best effort basis and left to community.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
