### ISSUE TITLE
Distributed TF managed session: inter_op_parallelism_threads and intra_op_parallelism_threads has no effect

### ISSUE THREAD

**Issue by hholst80** [tensorflow/tensorflow#4455]
We are using:
``` .python
with sv.managed_session(
  server.target,
  config=tf.ConfigProto(log_device_placement=True,
                        inter_op_parallelism_threads=1,
                        intra_op_parallelism_threads=1),
) as sess:
```
but TensorFlow still launches a number of threads proportional to the number of cores on each process. I counted +50 threads used by each process on my 24 vcore machine.

What can we do to limit the number of threads in a managed session.

EDIT: @yaroslavvb identified the problem. See the end of the thread about Session vs Server options.

**Comment by jmchen-g** [comment]
Do you have it set by some previous sessions in the same process?
  // Note that the first Session created in the process sets the
  // number of threads for all future sessions unless use_per_session_threads is
  // true or session_inter_op_thread_pool is configured.

**Comment by yaroslavvb** [comment]
There are two places to configure remote session with tf.ConfigProto
1. when you create a session with remote master: tf.Session("grpc://",
config=...)
2. when you launch remote master: tf.train.Server(config=...)

Docs says that tf.train.Server(config=...) specifies "specifies default
options for all sessions that run on this server."
Does this mean that tf.Session("grpc://", config=config) settings are
ignored?

**Comment by hholst80** [comment]
@jmchen-g this is the only session in my program.

**Comment by hholst80** [comment]
Anything new on this? We're completely trashing our AWS instances right now with load averages in the 3 digit range for TF distributed running on 16 docker processes on the same machine. Being able to limit the number of computational threads seems to be essential for us.

**Comment by yaroslavvb** [comment]
Have you tried using config option in Server?

**Comment by hholst80** [comment]
@yaroslavvb This is why they pay you the big bucks (hopefully) ;-) Thank you for solving the problem- now we're down to 6 threads per worker which should be manageable for a modern CPU.

**Comment by yaroslavvb** [comment]
@hholst80 no problem. It's a bit confusing to me too, you can pass it in either tf.Session(config=) or tf.train.Server(config=), and some options (inter_op_parallelism_threads) seem to be silently ignored in the first method, while others (log_device_placement) are respected. We had a similar problem of too much CPU usage because of this

@mrry any advice as to whether we should ever use tf.Session(config=) option when session connects to distributed master?

**Comment by mrry** [comment]
There are several options that are relevant to individual sessions, and should be passed in the session constructor if you want to set them.

From a quick look at [`master_session.cc`](https://github.com/tensorflow/tensorflow/blob/0db279f16ce21568c414694ea55e2dec07ad6972/tensorflow/core/distributed_runtime/master_session.cc) it appears that the only `ConfigProto` options respected in the distributed master are those under `ConfigProto.graph_options`. The `SimplerPlacer` uses `log_device_placement` and `allow_soft_placement` as well. `device_filters` is also used when constructing the session, and determines what servers the session can contact.

Since the `tf.train.Server` owns its set of devices and shares them between sessions on that server, any options relevant to creating devices (or configuring e.g. their thread pools) should be passed when constructing the server instead.

**Comment by aselle** [comment]
Closing as this  appears to be resolved. Thanks @yaroslavvb and @mrry.
