### ISSUE TITLE
Convert TensorFlow to TensorFlow Lite - very small model after conversion

### ISSUE THREAD

**Issue by Rariusz** [tensorflow/tensorflow#44561]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab
- TensorFlow installed from (source or binary): source 
- TensorFlow version (or github SHA if from source): 2.3.0

Following my previous issues https://github.com/tensorflow/tensorflow/issues/44091 https://github.com/tensorflow/tensorflow/issues/44435 of converting the Tensorflow model to Tensorflow Lite I prepared a notebook inspired by the notebook from the link [Object_Detection_in_TFLite](https://github.com/sayakpaul/E2E-Object-Detection-in-TFLite/blob/master/Object_Detection_in_TFLite.ipynb). From notebook  we can see that after converting model ```ssd_mobilenet_v2_320x320_coco17_tpu-8``` [Training a pets detector model within minutes with TFOD API](https://colab.research.google.com/github/sayakpaul/TF-2.0-Hacks/blob/master/Training_a_pets_detector_model_within_minutes_with_TFOD_API.ipynb) to TFLite the model size is 5711632 Bytes. In my cases the size of model is 516 bytes [mobilenet_v2_to_tflite](https://colab.research.google.com/drive/1GYKWFR7A6WknexnFa312eCa3ZST58i_3?usp=sharing)

Where Is the problem? I try to convert the model up to a month and the results are always the same. Model size is around 500 bytes. I thought it was a bug due to the fact that there is something wrong with training the model but I can see that even for the standard model with the repository the error is the same.

**Comment by amahendrakar** [comment]
@Rariusz,
I was able to reproduce the issue with [TF v2.3](https://colab.research.google.com/gist/amahendrakar/a060a9cf582e283a38ba647000f2ee02/44561.ipynb). 

However, the issue seems to be fixed with the latest [TF-nightly](https://colab.research.google.com/gist/amahendrakar/5e8c0f4835547183cb6629a2facde125/44561-tf-nightly.ipynb#scrollTo=cohE9r5hfI1C). On converting the model, the size of the `.tflite` file is around 11 MB. Please check the linked gist for reference. Thanks!

**Comment by Rariusz** [comment]
@amahendrakar Thank you for your help !!! So far the results are the same. For model graph and tflite frozen graph. Now I will want to run the model on google coral. But first I need to quantization. We'll see if there will be any more problems
