### ISSUE TITLE
from_tensor_slices not compatible with sparse data

### ISSUE THREAD

**Issue by amirhmk** [tensorflow/tensorflow#44565]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Google Colab / TF 2.3.0

**Describe the current behavior**
It's stated in the documentation that `Dataset` is able to handle `SpareTensors` on top of `Ragged` tensors and the other standard data types. 

Issue is `from_tensor_slices` is not able to handle a list of `SparseTensors`, but `from_tensors` which accepts a single datapoint is able to instantiate it. Currently `Dataset.from_generator` is not able to handle `Sparse` datatype either (in the current release at least) https://github.com/tensorflow/tensorflow/pull/41981 so I'm not sure how one is supposed to handle datasets that are compromised of both Sparse and dense data. 

**Describe the expected behavior**
`from_tensor_slices` should accept a list of `SparseTensors` given that there is exactly the same number of items in the list as the other features passed into `from_tensor_slices` 

**Standalone code to reproduce the issue**
[Colab Link](https://colab.research.google.com/drive/1952M7pHEgpl0KSFPkHz7gu9BpxGejdfu?usp=sharing
)
**Other info / logs** 

I'm not sure if it's just me, but when I read this [part of the documentation](https://www.tensorflow.org/guide/data#dataset_structure) I was under the impression that this feature would be supported. Thus you may identify this as a `feature_request` rather than a bug if I've misunderstood the documentarian.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c36fffc4912e041dd75b2d011bdb6c84/44565.ipynb). Thanks!

**Comment by amirhmk** [comment]
@amahendrakar No worries! I can potentially look into creating a fix for this in the next couple of days and submit a PR. Though do you know of any workarounds to deal with such a dataset using the `Dataset` API? (Sparse + Dense)?

**Comment by aaudiber** [comment]
@amirhmk Each component of the argument passed to `Dataset.from_tensors` or `Dataset.from_tensor_slices` must be convertible to a single object representable by a `tf.TypeSpec`. `list(SparseTensor)` doesn't satisfy this. There are a couple ways to make it work:

1. Define a single sparse tensor and take slices out of it:
```python
sparse = tf.SparseTensor(indices=[[0, 0, 0], [0, 1, 2], [1, 0, 0], [1, 1, 1]], 
    values=[1, 2, 3, 4], dense_shape=[2, 3, 4])
dataset = tf.data.Dataset.from_tensor_slices(sparse)
```

2. Produce sparse tensors using Dataset.from_generator:
```python
sparse_1 = tf.SparseTensor(indices=[[0, 0], [1, 2]], values=[1, 2], dense_shape=[3, 4])
sparse_2 = tf.SparseTensor(indices=[[0, 0], [1, 1]], values=[3, 4], dense_shape=[2, 2])
def gen():
  yield sparse_1
  yield sparse_2

dataset = tf.data.Dataset.from_generator(gen, output_signature=tf.SparseTensorSpec(dtype=tf.int32))
```

**Comment by amirhmk** [comment]
@aaudiber Thank you for your comment, that makes sense. I like the first approach, I just have to keep track of the indices that represent each data point after merging them into a single `SparseTensor` which shouldn't be too bad. 

As for the second approach, I think `from_generator` accepts `SparseTensorSpec` in the `pre-release` version. Do you know when this will become a `stable` version?

**Comment by aaudiber** [comment]
@amirhmk It will be available in TF 2.4.0, which should be released in the next week or two.

**Comment by amirhmk** [comment]
Sounds good. I still think this feature would be nice to have, as in each data point has some sort of a `sparse` tensor attached to it. Feel free to close if there is a strong reason not to do that. Thanks!

**Comment by ktsitsi** [comment]
I was trying to ingest sparse data into `tf.data.Dataset` by using the `from_generator` API. Trying that with on-prem design for Sparse Arrays which follows the COO representation I was not able to pass the 
```
return tf.data.Dataset.from_generator(
            generator=cls._generator,
            output_signature=(
                tf.SparseTensorSpec(dtype=tf.int32)
            )
            ,args=(a,),
        )
```
I was getting the following error: 

```
TypeError("Failed to convert object of type %s to Tensor. "
TypeError: Failed to convert object of type <class 'SparseArray'> to Tensor. Contents: ....
```
Thinking that the culprit may be the on-prem implementation of sparse data I tried the same with `scipy.coo_matrix`

I get the same error:

```
Attempt to convert a value (<4x4 sparse matrix of type '<class 'numpy.int64'>' with 4 stored elements in COOrdinate format>) with an unsupported type (<class 'scipy.sparse.coo.coo_matrix'>) to a Tensor.

```
After some debugging I saw that the error comes from the evaluation of the arguments of generator function,  Which makes sense since in the docs here clearly states that the args should be tf.Tensors.

https://www.tensorflow.org/api_docs/python/tf/data/Dataset#from_generator

```
args | (Optional.) A tuple of tf.Tensor objects that will be evaluated and passed to generator as NumPy-array arguments.
```
However after the introduction of `SparseTensors` and `SparseTensorSpec` I'm not sure if it's just me, but when I read this part of the documentation I was under the impression that these `scipy.coo_matrix` would be translated into `SparseTensors` or at least to `index`,`value` Numpy-arrays by exploiting the `data`,`row`,`col` attr of the COO sparse format (e.g. `scipy.coo_matrix`). Is there any walk-around on how someone can ingest sparse data using `from_generator`? Or is there any formal way that I am not aware?

**Comment by sat2000pts** [comment]
I am doing something very similar to @ktsitsi but instead inside the function that I pass to from_generator() I am converting the coo matrix to SparseTensor and specifying like @ktsitsi the SparseTensorSpec into the output_signature -> the error message I get is the following:

`TypeError: Cannot convert value SparseTensor Spec to a TensorFlow DType.`

**Comment by aaudiber** [comment]
@sat2000pts Can you open a new issue, and include code to reproduce the error you're seeing?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
