### ISSUE TITLE
tflite Converting unsupported operation: MatrixInverse

### ISSUE THREAD

**Issue by usename6** [tensorflow/tensorflow#44575]

**Comment by amahendrakar** [comment]
@usename6,
In order to expedite the trouble-shooting process, could you please provide the following information

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version (use command below):
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

And also the complete code to reproduce the issue reported here. Thanks!
