### ISSUE TITLE
Why is the memory(no gpu) used so different between windows and Ubuntu？

### ISSUE THREAD

**Issue by nistarlwc** [tensorflow/tensorflow#44601]
PS: memory is not GPU-memory, is PC-memory
There are 6 small models, inference with 6 multiprocessing in python3.7 and tensorflow1.13.1.  
In windows, use 4G memory, but in Ubuntu use 12G memory, don't know why.  
How to reduce memory in ubuntu?

**Comment by amahendrakar** [comment]
@nistarlwc,
TensorFlow 1.x is not actively supported. Could you please upgrade TensorFlow to v2.3 and check if you are facing the same issue? Thanks!

**Comment by nistarlwc** [comment]
update tensorflow2.3, but it use keras
`model=tf.keras.models.load_model("xx.h5)  
output = model.predict(image)`
use 12G memory in ubuntu

**Comment by amahendrakar** [comment]
@nistarlwc,
In order to expedite the trouble-shooting process, could you please provide the complete code and the dataset you are using.

Also, please take a look at the [memory profile tool](https://www.tensorflow.org/guide/profiler#memory_profile_summary) and compare the usage on both the operating systems. Thanks!
