### ISSUE TITLE
[TF 2.4] KerasTensor breaks typing compatibility

### ISSUE THREAD

**Issue by lgeiger** [tensorflow/tensorflow#44613]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc0 and tf-nightly
- Python version: 3.8

## The Problem
Since version 2.4 functional Keras models use `KerasTensor` instead of `tf.Tensor` as layer output types. Unfortunately `KerasTensor` doesn't subclass `tf.Tensor` which breaks `isinstance(x, tf.Tensor)` checks:
https://github.com/tensorflow/tensorflow/blob/6d9e0887f6bce8fbeeb430364e520d05350d96d5/tensorflow/python/keras/engine/keras_tensor.py#L63

The release notes recommend to use `tf.is_tensor` instead.
In my opinion this is not really Pythonic and breaks compatibility with the [TF Types RFC](https://github.com/tensorflow/community/blob/master/rfcs/20200211-tf-types.md) (/cc @mdanatg) wich even mentiones that `tf.is_tensor` is expected to be deprecated eventually.

Concretely, switching from `isinstance(x, tf.Tensor)` to `tf.is_tensor` is also not possible in all cases. E.g. this breaks usage of static typecheckers like `pytype` or `typeguard`:

A common pattern which can also be found in TensorFlow Addons (/cc @seanpmorgan) is the following:

```python
from typeguard import typechecked
import tensorflow as tf

@typechecked
def foo(x: tf.Tensor):
    print(x.dtype)

foo(tf.keras.Input(shape=(32, 32, 3)))  # Throws in TF 2.4 since `isintance` is used for typechecking
```

## Possible solutions

1. Make `KerasTensor` a subclass of `tf.Tensor`. @mihaimaruseac @fchollet is there a reason why this isn't currently the case?

2. Make `KerasTensor` a subclass of [`types.Tensor`](https://github.com/tensorflow/tensorflow/blob/6d9e0887f6bce8fbeeb430364e520d05350d96d5/tensorflow/python/types/core.py#L40-L54). I don't see any disadvantage of doing this in general, but it wouldn't really fix this issue since `types.Tensor` is not exposed as part of the public API yet so users would need to rely on private TensorFlow APIs

3. In usercode this could be fixed by directly relying on `KerasTensor` to replace the usage of `tf.Tensor` with:
   ```python
   from typing import Union
   from tensorflow.python.keras.engine.keras_tensor import KerasTensor

   TensorType = Union[tf.Tensor, KerasTensor]
   ```
   I do not think this is a proper solution since it requires users to rely on internal APIs and implementation details that might change in the future.

I am currious to hear back from you on what the bestpractices for type checking of Tensors are, or whether I am just missing somthing obvious here.

**Comment by mihaimaruseac** [comment]
@tomerk can you take a look please?

**Comment by seanpmorgan** [comment]
cc @mdanatg per discussion in SIG Addons meeting

**Comment by mdanatg** [comment]
Indeed, `is_tensor` intentionally diverges from `isinstance(*, tf.Tensor)`, and we ultimately hope to deprecate it. For now, you may use it and we'll support backward compatibility, but we encourage using isinstance whenever possible, so it makes sense to resolve this particular issue.

Option 1 is unfortunately not feasible because the TensorFlow infra does not support subclassing `tf.Tensor`.

That leaves either option 2 or 3, depending whether or not we want `KerasTensor` to be considered a "TensorFlow Tensor" - we're currently discussing this and should have a resolution soon. Either alternative would indeed require exposing an appropriate public symbol, because we definitely don't want to create a dependency on internal symbols.

**Comment by lgeiger** [comment]
@mdanatg Thanks a lot for taking a look.

**Comment by Saduf2019** [comment]
@lgeiger 
Is this still an issue

**Comment by lgeiger** [comment]
> Is this still an issue

@Saduf2019 Yes

**Comment by seanpmorgan** [comment]
@mdanatg Any idea if a public KerasTensor or tf.Tensor subclass will land in TF2.4?

**Comment by mdanatg** [comment]
Unfortunately the branch cut for 2.4 already happened a couple of weeks ago, so this will definitely not be fixed by then.

We're still discussing the final solution with @tomerk. For 2.4, I believe the only solution is to use option 3 above, with a large note around it calling that it's a temporary measure.

**Comment by lgeiger** [comment]
@mdanatg Thanks for the info. It's a bit cumbersome for library authors who want to support multiple versions of TensorFlow, but the workaround works fine.

> Unfortunately the branch cut for 2.4 already happened a couple of weeks ago, so this will definitely not be fixed by then.

I probably missed the RFC for the `KerasTensor` changes, otherwise I would've opened the issue earlier.
In projects I maintain we don't usually test against `tf-nightly` as broken builds are mostly false positives that get resolved shortly afterwards, but maybe I'll reevaluate to catch issues like this before the release branch gets cut.

**Comment by Saduf2019** [comment]
@lgeiger 
Is this still an issue.

**Comment by lgeiger** [comment]
@Saduf2019 yes this is still an issue. The current temporary workaround relies on private TensorFlow function which isn't a longterm solution. See https://github.com/tensorflow/tensorflow/issues/44613#issuecomment-732215759

**Comment by lgeiger** [comment]
Is there already a decision made on whether a fix for this will make it into the 2.5 release?

**Comment by kleinicke** [comment]
I'm getting the error: ImportError: cannot import name 'keras_tensor' from 'tensorflow.python.keras.engine' (/Users/florian/anaconda/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/__init__.py)

In https://github.com/tensorflow/tensorflow/issues/33786 they say, that tensorflow.python.keras.engine does not exist.

**Comment by mdanatg** [comment]
We discussed creating a TF interface that KerasTensor can use, but unfortunately it not be available in 2.5.

**Comment by lgeiger** [comment]
With TF 2.6.0 this issue is now is even more subtle since `tensorflow/python/keras` was replaced with `keras`, however the old import still work. Which leads to the following weirdness in TF 2.6.0:
```python
from keras.engine.keras_tensor import KerasTensor  # imported from keras-team/keras

from tensorflow.python.keras.engine.keras_tensor import KerasTensor as KerasTensorFromTF # This import should not exist anymore

assert KerasTensorFromTF == KerasTensor   # This breaks!!!
```

```python
import tensorflow as tf

from tensorflow.keras.backend import is_keras_tensor
from tensorflow.python.keras.backend import is_keras_tensor as is_keras_tensor_tf  # this import should not exist anymore

assert is_keras_tensor(tf.keras.Input([10]))
assert is_keras_tensor_tf(tf.keras.Input([10])) # This breaks!!!
```
Checkout [this notebook](https://colab.research.google.com/drive/1-TcroLTdI4fx4dk5P3Cq_vk5AfiYuVOo?usp=sharing).

I opened #50613 as a separate issue to discuss removal of `tensorflow/python/keras` from the PIP package to remove this confusion.

**Comment by jinensetpal** [comment]
This is still an issue! Has a solution for this made it to any of the upstream branches yet?

**Comment by pjpratik** [comment]
I was able to reproduce this issue on TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/7ac78d9cb83ca8031d30fe84fc607658/44613.ipynb). Thank you.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
