### ISSUE TITLE
How to implement custom delegate that supports dynamic-sized tensor

### ISSUE THREAD

**Issue by junhyk** [tensorflow/tensorflow#44681]
Hi,

I'm implementing custom TFLite delegation for my accelerator.
My implemented the delegation largely referring [dummy delegate example](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/utils/dummy_delegate)
But when I modify the graph using my delegate, I got following error.
```
ERROR: Attempting to use a delegate that only supports static-sized tensors with a graph that has dynamic-sized tensors.
```
So I want to enable dynamic-sized tensor support in my delegate.
But I couldn't find any guidelines for that.

**What should I do to support dynamic-sized tensors in my custom delegate?**
Do tensorflow have such an example?

Thanks in advance!

**Comment by ymodak** [comment]
Apologies for the delay in response. I think this question is better asked on [Stack Overflow](http://stackoverflow.com/questions/tagged/tensorflow) since the use cases can be different for each user. You may find this [thread](https://github.com/tensorflow/tensorflow/issues/41194) useful to build a custom delegate. Thanks!
