### ISSUE TITLE
Discussion of Apollo3 TFLu PRs

### ISSUE THREAD

**Issue by oclyke** [tensorflow/tensorflow#44737]
@tensorflow/micro

Hi @advaitjain, or whoever it may concern.

Thank you for the [explanation closing my last PR](https://github.com/tensorflow/tensorflow/pull/43831). I'd like to restructure and improve those features so that they can be accepted into the project. From what I understand there are two main concerns:

* keeping PRs focused to one issue/feature each
* trying to deduplicate code for examples

These should be fairly easy to do. I propose three PRs:

1. Fix existing issues with Apollo3 EVB performance
2. Update underlying AmbiqSuite SDK version to 2.5.1
3. Add targets for additional SFE Apollo3 based boards 

In the last PR I initiated deduplication efforts for the additional boards. Generally it went well but I did have issues with one target in particular. I may reach out for some guidance on that when the time comes. 

Please, let me know if this approach is acceptable.

Thank you,
oclyke

**Comment by advaitjain** [comment]
Thanks @oclyke for making this issue.

Breaking up the PRs into smaller chunks is much appreciated. In addition, let me share the desired end state and some additional PRs that I think we will need here.

### Desired End State
We want to consolidate all the Apollo3 based boards into a single `TARGET` with an additional specifier for the specific `BOARD`.

What this means is that the invocations should be:
```
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=apollo3 BOARD=sparkfun_edge
make -f tensorflow/lite/micro/tools/make/Makefile TARGET=apollo3 BOARD=apollo3evb
```

This is in contrast to the current approach of having a separate `TARGET` for `sparkfun_edge`, `apollo3evb` and more.

What this also means is that there will be many more common files, including:
 * micro/apollo3/micro_time.cc (instead of `sparkfun_edge/micro_time.cc` and `apollo3evb/micro_time.cc` etc.)
 * micro/apollo3/debug_log.cc
 * micro/examples/micro_speech/apollo3/audio_provider.cc
 * etc.

Any places where there are differences between the boards (for example the audio_provider) will be handled via ifdefs and helper functions, as needed. 

### Next steps

 * Let's continue the conversation on this issue until we are aligned on where we want to end up.
 * As a first step, even before #44740, let's consolidate sparkfun_edge and apollo3evb along the lines of what I describe above with the following PRs (so that we can avoid breaking things):
   1. make a directory tensorflow/lite/micro/apollo3 add a README with some context and you listed as a maintainer (along the lines of [this readme](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/kernels/arc_mli#embarc-mli-library-based-optimizations-of-tensorflow-lite-micro-kernels-for-arc-platforms)).
    1. make a new apollo3 makefile target with debug_log, micro_time etc.
    1. Add that target to [test_all.sh](https://github.com/tensorflow/tensorflow/blob/07b9eccccfc13e687a1de4ad08cd49c8954236a5/tensorflow/lite/micro/tools/ci_build/test_all.sh) similar to [test_sparkfun.sh](https://github.com/tensorflow/tensorflow/blob/07b9eccccfc13e687a1de4ad08cd49c8954236a5/tensorflow/lite/micro/tools/ci_build/test_sparkfun.sh)
    1. Individual PRs that make the examples work for sprakfun_edge with `TARGET=apollo3 BOARD=sparkfun_edge`
    1. Individual PRs that make the examples work for apollo3evb with `TARGET=apollo3 BOARD=apollo3vb` -- this step will mean adding in #ifdefs and some refactoring of the code from the previous step (and might encompass some of the changes from #44740).
    1. Delete the existing makefiles and code in the sparkfun_edge and apollo3evb directories.

 * Then start sending PRs to support the new boards ...

Let me know what you think. Since this is a fairly significant refactor that I am requesting, I'm happy to get on a video call to discuss this further.

Tagging @petewarden and @njeffrie in case they have any additional comments.

**Comment by oclyke** [comment]
@advaitjain thanks for working with me on this. i've completed steps i-iii and vi in #44930. due to the current structure of the examples they are still working, though still using redundant code. that can be fixed in steps iv-v.

to distinguish between boards i added ```-DTFLU_APOLLO3_BOARD_$(BOARD)``` to the PLATFORM_FLAGS. when ```BOARD``` is changed on the command line it is necessary to use files that have been compiled with that option, therefore the GENDIR is specialized in the main [Makefile](https://github.com/tensorflow/tensorflow/pull/44930/files#diff-84c8d7e242143d674d6e26ab56443970ed8e1f3db0fcb1d0e8e127eaebbe1a1a).

**Comment by pkgoogle** [comment]
Hi @oclyke, it seems these PRs have stalled, let us know if you would like to continue this.
