### ISSUE TITLE
Optimize Tensorflow for Cortex-R MCUs

### ISSUE THREAD

**Issue by ramkumarkoppu** [tensorflow/tensorflow#44833]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
Most of the Automative sensors uses Cortex-R MCU. To run Tensorflow on Cortex-R MCU, can you please optimize Tensorflow for Cortex-R MCUs as well similar to what you have done for Cortex-M?

**Will this change the current api? How?**

**Who will benefit with this feature?**
Building Intelligent sensors for automotive applications as well.

**Any Other info.**

**Comment by freddan80** [comment]
Sorry for the late reply. You're asking a good question.

The Arm Cortex-R architecture is similar to Cortex-A. Both use [Neon technology](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon). A good starting point for optimizations would be the TFL opt kernels for Cortex-A. For example: [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/internal/optimized/integer_ops/depthwise_conv.h). But that would require you do build TFL, not TFL for Microcontrollers. Do you have a preference? What are the typical memory sizes (SRAM/flash/DRAM) of the systems you're referring to? Do you have a link to a typical system?

Cheers!

**Comment by freddan80** [comment]
I should be more clear - Neon technology is _optional_ in some of the Arm Cortex-R, see [link](https://developer.arm.com/-/media/Arm%20Developer%20Community/PDF/Cortex-A%20R%20M%20datasheets/Arm%20Cortex-R%20Comparison%20Table_v2.pdf?revision=74d60ed8-f68b-48c4-a888-9a8b128a2cbe)

**Comment by pkgoogle** [comment]
Hi @grantjensen, can you please take a look at this? Thanks.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.

**Comment by handiener** [comment]
Hey, has anyone performed a basic port for Cortex-R5 with just the TFLM reference implementations? I don't need optimizations I just need it for testing purposes.
