### ISSUE TITLE
The TFLite test reported an error

### ISSUE THREAD

**Issue by huafeihuayu** [tensorflow/tensorflow#44830]
The Tflite model failed to test Android on the development board
Compiled tflite library:
![15b3b25151b93f1da414d6f36260ac7](https://user-images.githubusercontent.com/54087172/99056074-bb43a880-25d4-11eb-8226-44a1fb8d058d.jpg)
error:
![a2e375014e28b2d18f295e065cd6e3d](https://user-images.githubusercontent.com/54087172/99056182-e3cba280-25d4-11eb-9fda-727686fa1f51.jpg)

why not librk_codec.so? what is  librk_codec.so ?

**Comment by Saduf2019** [comment]
@huafeihuayu 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Please paste the error message (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.
