### ISSUE TITLE
tf.io.gfile can read but can't write file 

### ISSUE THREAD

**Issue by zvikarp** [tensorflow/tensorflow#44884]
**System information**

Running on Ai Platform using Tensorflow Cloud.
- Docker container: tensorflow/tensorflow:2.3.1
- Python version: 3.8

**Describe the current behavior**
Using tf.io to read/write files to Google Cloud Storage. I can listdir, read files but not write.

**Standalone code to reproduce the issue**

Assuming "gs://bucket/folder" existes, and "gs://bucket/folder/folder1" doesn't exist.

```
import tensorflow as tf

print(tf.io.gfile.exists("gs://bucket/folder/folder1"))  # prints false
tf.io.gfile.makedirs("gs://bucket/folder/folder1")
print(tf.io.gfile.exists("gs://bucket/folder/folder1"))  # prints true
```

So it seems like the code worked, but when I have a look at the bucket, I can't find the file. and when I run the script again, it has the same output, meaning it didn't find the file.

I did not touch the permissions as Ai Platform has required permissions. Also, the Ai Platform job and the bucket are in the same region.

I'll be happy to provide more information or any logs if relevant. I also did a small test on Compute Engine and had the same issue.

**Comment by vnvo2409** [comment]
Because `GCS` [stores](https://cloud.google.com/storage/docs/gsutil/addlhelp/HowSubdirectoriesWork) data differently from usual filesystem like `posix`, we are forcing the behavior of `posix` upon `GCS` and sometime, the filesystem does not work as intented, especially with directory ( since `GCS` does not have the concept of directory ). 

The directory you just created is an empty file and it might not show on `GCS` server. I think you could try `tf.io.gfile.Gfile.write` to see if you could actual write to the server or not.

**Comment by zvikarp** [comment]
Thank you @vnvo2409 for the explanation, I guess tf.io is not stable for Google Cloud Storage and I shouldn't really on it.

Although this is strange, on [Tensorflow's API docs](https://www.tensorflow.org/api_docs/python/tf/io/gfile/GFile) it says that this is exactly what Gfile is here for - to support GCS:

" The C++ FileSystem API supports multiple file system implementations, including local files, Google Cloud Storage (using a gs:// prefix, and HDFS (using an hdfs:// prefix). "

There is documentation and examples using tf.io for GCS, [here is one example](https://www.tensorflow.org/official_models/fine_tuning_bert#resources). Gfile is also one of the [suggested ways to use GCS in Google AI Platform](https://cloud.google.com/ai-platform/training/docs/working-with-cloud-storage#read-during-training).


I have done some tests with the following and no success:

```
tf.io.write_file(file_name, data)
```

```
with tf.io.gfile.GFile(file_name, mode="w+") as f:
    f.write(data)
```

No errors from Tensorflow, but the files are not saved in GCS.

**Comment by mihaimaruseac** [comment]
There are some bugs in GCS. Internally Google uses different filesystem implementations, so GCS, Hadoop, etc. don't get as tested as Posix/Windows/internal ones. That's why we're modularizing them now so that community can take control over the cloud filesystems.

Now, regarding your code in the last comment, is `file_name` starting with `gs://` in the GCS example? There might also be a need for a wait before the file gets written. If that still does not work, this is a serious bug (please also paste full version of `file_name`, modulo hiding bucket name and path prefix, if you want to hide them)

**Comment by vnvo2409** [comment]
@zvikarp 

> I guess tf.io is not stable for Google Cloud Storage and I shouldn't really on it.

This isn't what I mean. `tf.io` is stable enough for Google Cloud Storage. I mean It will have some weird [problems](https://github.com/tensorflow/tensorflow/pull/41282#issuecomment-657236354) ( however, they are very rare cases and require an unusual process to reproduce ) with directory operation ( especially `isdir` ) but with reading/writing file, there should be no problem.

Indeed, I just tested `tf.io.write_file` and I did not have any problem.
```
>>> import tensorflow as tf
>>> tf.__version__
'2.4.0-rc0'
>>> tf.io.write_file("gs://tfvnvo/tf.txt", "tensorflow")
2020-11-19 12:51:47.994065: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  SSE4.2 AVX AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
>>>
```
<img width="903" alt="image" src="https://user-images.githubusercontent.com/17511625/99627099-3b02c480-2a66-11eb-82ee-3184cb935255.png">

---

Regarding your problem, I think it is related to your bucket configurations (  [`IAM`, `ACL`](https://cloud.google.com/storage/docs/access-control) or your credentials ). In order to confirm that your bucket doesn't have any problems, I think you could try and see if you could write to your bucket with GCS Python Client:
``` python
# pip install google-cloud-storage
>>> from google.cloud import storage
>>> client = storage.Client()
>>> bucket = client.get_bucket('tfvnvo')
>>> blob = bucket.blob('python-gcs')
>>> blob.upload_from_string('python-gcs')
```
---

> No errors from Tensorflow, but the files are not saved in GCS.

Handling error in TensorFlow GCS is a little bit outdated ( It was writtern 4 years ago ) so it might be the reason why TensorFlow does not catch any error. However, I am working on a modular filesystem plugin which will replace the current filesystem and it will have a much better handling error mechanic for sure.

**Comment by zvikarp** [comment]
Sorry for the delay.

In the last few days, I re-tried and all the commands worked for me with GAE and GCS. I suspect it might have been an issue with Google AI Platform (that I tried using earlier), the permissions it had, or the way I implemented the modal.

Anyway, sorry for the destruction, I indeed learned a lot form this conversion.

**Comment by eddie-scio** [comment]
I believe this is a real problem with `make_dirs` (perhaps not `write_file`) interaction with GCS -- note the T2T issue [here](https://github.com/tensorflow/tensor2tensor/issues/879), I figured this is an existing issue and better to bump it in core TF.

My workflow is simply to call `tf.gfile.MakeDirs(FLAGS.data_dir)` on my output directory (which is on GCS), which is quite a common workflow.  However, this will fail for any non-top/bucket-level output, with the error in the attached issue):
```
tensorflow.python.framework.errors_impl.InvalidArgumentError: 'object' must be a non-empty string. (File: gs://my_bucket/)
```

**Comment by eddie-scio** [comment]
For folks who run into this and can't use the linked workaround of top-level bucket input, I'm just tracking down all usages of `MakeDirs/makedirs` and using a temporary local input there instead, doing a GCS copy later with the GCS python lib instead of tf.

**Comment by Geoyi** [comment]
as @vnghia mentioned above, you have to verify if you have (read and write) access to the GCS. 
Once you can access the basket, writing file back to gcs buck can be like:

```python
import numpy as np
from tensorflow.python.lib.io import file_io
a = np.random.rand(100, 100, 4)
b = np.random.rand(100, 100, 1)
BUCKET_NAME = f"{your-bucket-name}"
fout = f"gs://{BUCKET_NAME}/data/train/test.npz"
np.savez(file_io.FileIO(fout, 'w+'), x=a, y=b)
```
Read more on [StackOverflow](https://stackoverflow.com/questions/41633748/load-numpy-array-in-google-cloud-ml-job)
