### ISSUE TITLE
Enable TensorFloat32 with XLA

### ISSUE THREAD

**Issue by n2cholas** [tensorflow/tensorflow#44887]
**System information**
- TensorFlow version (you are using): `2.5.0-dev20201115`
- Are you willing to contribute it (Yes/No): No (don't know how to)

**Describe the feature and the current behavior/state.**
Currently, TF32 works in the normal run time but not with XLA.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Anyone using Ampere GPUs and XLA compilation.

**Any Other info.**
I checked the TF32 was not being used with XLA using the following script:
```python
import tensorflow as tf
tf.debugging.set_log_device_placement(True)
tf.config.experimental.enable_tensor_float_32_execution(True)

@tf.function(experimental_compile=True)
def f(x):
    return x @ x
with tf.device("/GPU:0"):
    x = tf.cast(tf.random.uniform(shape=(16,16)), tf.float32)
f(x)
```

I ran this on an A100 with dlprof. With `experimental_compile=False`, the following kernel ran:
![image](https://user-images.githubusercontent.com/12474257/99198812-fb3b9480-2768-11eb-9a39-a417e072a064.png)

With `experimental_compile=False` and `tf.config.experimental.enable_tensor_float_32_execution(False)`, the following kernel ran:
![image](https://user-images.githubusercontent.com/12474257/99198825-0c84a100-2769-11eb-8785-599f0527526e.png)

With  `experimental_compile=True` and `tf.config.experimental.enable_tensor_float_32_execution(True)`, the same kernel ran:
![image](https://user-images.githubusercontent.com/12474257/99198832-1b6b5380-2769-11eb-93fc-dce2e695d5d3.png)

This indicates to me that the TF32 is not enabled with XLA. Please let me know if I'm doing something wrong. Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
