### ISSUE TITLE
Cuda verision not documents

### ISSUE THREAD

**Issue by birolkuyumcu** [tensorflow/tensorflow#44897]
There is no information about which cuda version required for pip packages
i think must be document as an table for old relases and 
for recent release mustbe selection gui something like pytorch 
![resim](https://user-images.githubusercontent.com/8981828/99224100-b8280280-27f6-11eb-9511-44237b0a45a0.png)

**Comment by ymodak** [comment]
We have listed the build configurations here https://www.tensorflow.org/install/source#gpu

**Comment by ymodak** [comment]
I understand your confusion however its important to note that dependencies such as cuda are updated very quickly and it is a challenge to keep various TF versions compatible with different cuda versions.
Hence we provide newest TF prebuilt binaries for latest/most recent cuda version and we do not backport new cuda versions to older TF versions due to limited resources unfortunately.
Also now that we are in TF 2.X new cuda versions will be made available for later TF 2.X versions.
