### ISSUE TITLE
tflite: why using mali gpu will cause memory leak?

### ISSUE THREAD

**Issue by Sunnyday2016** [tensorflow/tensorflow#44903]
**System information**

- OS Android 10.0
- Mobile device: mate 30 pro:
- tflite build from source:
- gpu：mali g76:

I noticed there are some comments about reducing memory leak for mali gpu in tflite opencl and opengl context. And I also observed memory leak on my mate30 pro when using opencl, which does not happens with my previous adreno phone.
mate30 pro
![image](https://user-images.githubusercontent.com/21992233/99243764-162b0900-283c-11eb-98f0-ace9fa61def5.png)

mi8
![image](https://user-images.githubusercontent.com/21992233/99243935-5a1e0e00-283c-11eb-961a-65c041c473e8.png)

So can anyone explain why there may be memory leak for mali gpu? 

Thanks!

**Comment by impjdi** [comment]
Hi @Sunnyday2016 ,

We are aware of the existence of this issue, but we don't have a Mali device due to COVID-19 and office accessibility, and it doesn't look like the situation will change any time soon (Santa Clara county went from orange to purple yesterday).

Unfortunately for GPUs, we can't easily pinpoint the problem location for you to take a look.  It could be a vendor driver bug, a bug in the extensions, or a bug in our code.  The last one is probably most likely, and I would start looking at the code locations where Adreno vs Mali diverge.

**Comment by FdyCN** [comment]
@impjdi is there any update for this issue?

**Comment by impjdi** [comment]
Can you share the code snippet and the network?

**Comment by mohantym** [comment]
Hi @Sunnyday2016 !

We are checking to see whether you still need help in this issue . 
Could you confirm whether issue still exists in 2.9 or higher versions or not.

Would it be possible share a sample model/lite model or profiling results from [benchmarking ](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark)with 2.11  to replicate this issue.

Thank you!
