### ISSUE TITLE
How to run TFLite on specific CPUs?

### ISSUE THREAD

**Issue by tlzhao-casia** [tensorflow/tensorflow#44965]
@tensorflow/micro

Dear Authors:
     I'm running TFLite on RK3399 with BIG.LITTLE architecture, which contains 2 ARM Cortex A72 cores (BIG cores) and 4 ARM Cortex-A53 cores (LITTLE cores),  and the tflite is installed through source.  I use the example code of [benchmark](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark) and the tflite model is converted from keras model. 
     When I run tflite with 2 threads (through the interpreter.SetNumThreads interface), it is expected that it should run on the 2 BIG cores. However, it seems that in some cases it runs on 2 of the LITTLE cores, which will largely degrade performance. So is there any way to run tflite on specific CPUs?

**Comment by talumbau** [comment]
Hi,

This issue (pinning a user process to a desired core in BIG.LITTLE architecture) is not particular to TF Lite. In general, the operating system will decide whether to run on the lower energy LITTLE cores, or the higher performance BIG cores. There is no general API for a process to move itself (or fork another process) to a particular core that the OS will respect for the life of the process. This is because the OS must be able to assert control for thermal management, battery management, etc. For benchmarking purposes or other testing activities, one call always use the `taskset` Linux utility to run a given program on a particular core. In the context of the RK3399 board, from what I understand, it appears that your application is not the standard use case for TF Lite, that being "run ML inference inside a Android/iOS application on a mobile SoC." For your case, maybe it is good enough to start some kind of "server" process with `taskset` and then have user applications talk to that process in order to make sure inference happens on a BIG core.

**Comment by HungYangChang** [comment]
Answer from one of my group members:
 you can assign specific CPUs. You do so by either taskset or CPU shielding. My preference is CPU shielding. Here's how:

1- install cpuset if not there
2- shield the CPUs that you want to assign (I'm assuming CPUs number 0,1,2,3 (LITTLE cluster)
3- run the tflite model using the benchmark model in the CPUset you have created, with setting num_threads option. Here I set it to 4

`sudo apt install cpuset
sudo cset shield --cpu 0,1,2,3 --kthread on --threads
cset proc -s user --exec ./benchmark_model -- --graph=/home/mohamed/Downloads/Export/H-128_L-1_A-2_I-512.tflite  --max_profiling_buffer_entries=8092 --num_threads=4 --num_runs=100  --profiling_output_csv_file=output.csv --enable_op_profiling=true --input_layer=input_mask:0,input_ids:0,segment_ids:0 --input_layer_shape=1,64:1,64:1,64 --warmup_runs=1 --min_secs=0.001 --warmup_min_secs=0.001`
    
Another example if you want to run on only 2 LITTLE cores, say number 0,1( num_threads is set to 2)
`cpu shield --reset
sudo cset shield --cpu 0,1 --kthread on --threads
cset proc -s user --exec ./benchmark_model -- --graph=/home/mohamed/Downloads/Export/H-128_L-1_A-2_I-512.tflite  --max_profiling_buffer_entries=8092 --num_threads=2 --num_runs=100  --profiling_output_csv_file=output.csv --enable_op_profiling=true --input_layer=input_mask:0,input_ids:0,segment_ids:0 --input_layer_shape=1,64:1,64:1,64 --warmup_runs=1 --min_secs=0.001 --warmup_min_secs=0.001`

**Comment by HungYangChang** [comment]
Another example: form [https://github.com/adityagupta1089/ComputeLibrary](url)

![image](https://user-images.githubusercontent.com/70759685/128282036-bc63999b-c6e5-4efd-a028-d4f2de9d3238.png)
