### ISSUE TITLE
Flexbuffers patching causing -Wnull-dereference

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tensorflow#44971]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source): 41dc09029c39777b3be83e6cc00853be7c5f0674
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**
tensorflow/lite/micro/tools/make/flatbuffers_download.sh is patching Flexbuffers. The original code is replaced with:
// Introduce a segfault for an unsupported code path for TFLM.
return *(static_cast<double*>(nullptr));
This is causing a compile issue for us, i.e. it triggers:
error: indirection of non-volatile null pointer will be deleted, not trap [-Werror,-Wnull-dereference]

Perhaps we could generate a segfault in another way or maybe just log an error and return 0.

**Please provide the exact sequence of commands/steps when you ran into the problem**

**Comment by mansnils** [comment]
Tagging @advaitjain

**Comment by advaitjain** [comment]
Sorry about that.

Logging an error is hard because we're in the external flatbuffers library. Do you have a suggestion for a different way to generate a segfault?

Alternately, I'd be fine with an ifdef for the arm compiler (as part of the flatbuffer patching) so that you don't run into this issue.

**Comment by advaitjain** [comment]
Documenting for the future when we might wonder why we did what we did.

#45040 made null-dereference an error for any code that includes flexbuffers.h which resulted in [odd build errors](https://github.com/tensorflow/tensorflow/pull/43566#issuecomment-733250524) because the version of patched flatbuffers that I had locally was changing my build.

TFLM never really turned on `-Wnull-dereference` and as a test when I did explicitly enable `-Wnull-dereference`, I got a bunch of  (the same) errors in the flatbuffers code and at least one in the TFLM code as well:
```bash
tensorflow/lite/micro/tools/make/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:252:48: error: potential null pointer dereference [-Werror=null-dereference]
  252 |   uoffset_t size() const { return EndianScalar(length_); }
In file included from tensorflow/lite/micro/tools/make/downloads/flatbuffers/include/flatbuffers/flatbuffers.h:20,
                 from ./tensorflow/lite/micro/micro_allocator.h:21,
                 from tensorflow/lite/micro/micro_allocator.cc:16:
tensorflow/lite/micro/tools/make/downloads/flatbuffers/include/flatbuffers/base.h:392:22: error: null pointer dereference [-Werror=null-dereference]
  392 |   return EndianScalar(*reinterpret_cast<const T *>(p));
      |          ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./tensorflow/lite/micro/simple_memory_allocator.h:31:7: error: potential null pointer dereference [-Werror=null-dereference]
   31 | class SimpleMemoryAllocator {
      |       ^~~~~~~~~~~~~~~~~~~~~
./tensorflow/lite/micro/simple_memory_allocator.h:31:7: error: potential null pointer dereference [-Werror=null-dereference]
```

Realistically, these errors are only a sampling of what we might see, which is a somewhat long-winded way of saying that setting `-Wno-null-dereference` is ok for the TFLM code.

**Comment by advaitjain** [comment]
Ignore commit 059ef7f. The change from that commit was overwritten with 87b03ee
