### ISSUE TITLE
Attempting to use uninitialized value lstm/LSTMCell/W_0 on Distributed TensorFlow

### ISSUE THREAD

**Issue by qingzew** [tensorflow/tensorflow#4500]
On a cluster of Tensorflow, which has one ps server, and one worker:

``` python
def inference(self, inds, early_stops):

            ...

            with tf.variable_scope('lstm_encoder') as scope:
                initializer = tf.random_uniform_initializer(-0.08, 0.08)
                lstm_cell = tf.nn.rnn_cell.LSTMCell(self.hidden_units, initializer = initializer, state_is_tuple = True)
                if self.is_training and self.keep_prob < 1:
                    lstm_cell = tf.nn.rnn_cell.DropoutWrapper(lstm_cell, output_keep_prob = self.keep_prob)

       ...
```

``` python
 with tf.device(tf.train.replica_device_setter(worker_device =
                                                          '/job:worker/task:%d' % int(os.environ['task_index']), cluster = cluster)):
                train_op, loss = inference()
```

it turns out that:

```
tensorflow.python.framework.errors.FailedPreconditionError: Attempting to use uninitialized value sentiment/lstm_encoder/RNN/LSTMCell/W_0
     [[Node: sentiment/lstm_encoder/RNN/LSTMCell/W_0_S8 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:worker/replica:0/task:0/gpu:0", send_device="/job:ps/replica:0/task:0/gpu:0", send_device_incarnation=-5768356229269645157, tensor_name="edge_226_sentiment/lstm_encoder/RNN/LSTMCell/W_0", _device="/job:ps/replica:0/task:0/gpu:0"](sentiment/lstm_encoder/RNN/LSTMCell/W_0)]]
     [[Node: sentiment/lstm_encoder/RNN/LSTMCell/B/Assign_S4 = _Recv[client_terminated=false, recv_device="/job:worker/replica:0/task:0/gpu:0", send_device="/job:ps/replica:0/task:0/gpu:0", send_device_incarnation=-5768356229269645157, tensor_name="edge_214_sentiment/lstm_encoder/RNN/LSTMCell/B/Assign", tensor_type=DT_FLOAT, _device="/job:worker/replica:0/task:0/gpu:0"]()]]
```

I try to place variables on cpu or gpu, both of them did not work.

**Comment by mrry** [comment]
Can you share the code that you use to initialize the variables?

**Comment by qingzew** [comment]
I push it to github, you can reference [this](https://github.com/qingzew/tfcluster/blob/master/examples/sentiment/trainer.py#L57)

**Comment by mrry** [comment]
Thanks for sending over that code. There's nothing obvious in that file that would lead to variables being uninitialized, but I haven't read all of the files.

Could you try adding an explicit call to `sess.run(init_op)` in your session, to see if the initialization is being missed for some reason?

If that doesn't fix things, the next step would be to package up your code as a single file with no external code or data dependencies, and we can take a look at why the initialization isn't working as expected.

**Comment by qingzew** [comment]
@mrry Thank you for your help. I have tried `sess.run(init_op)`, it doesn't work. Before that, I wrote it on singal machine, putting all variables  and ops on gpu, it was fine. Then I modify it on distributed version, it does not work any more.

In fact, I write a cluster base on mesos,  I run this example on it. I am not sure if the cluster has bugs, although a mnist example can run on it

so I will update this issue

**Comment by mrry** [comment]
@qingzew Do you have any updates on this issue?

**Comment by qingzew** [comment]
not yet, I rewritted my distributed code, and want to use sync_trainer instead async_trainer, but the gpu is busy,
so you will close this issue?

**Comment by mrry** [comment]
I'll close it for now, but please feel free to re-open if you can reproduce it with a smaller example!

**Comment by spitis** [comment]
Think I am running into something related to this issue on v1.0. Will see if I find time to get a small reproducible example going, but I encountered it doing the following:

Took cifar10 tutorial and instead of a convnet, built an RNN (using the contrib RNN cells, tested with both basic rnn / gru cells, and also with both dynamic rnn and the static rnn). 

AFAIK there is no easy way to get the RNN variables on the CPU, so I wrapped the entire graph in the following hack:

    from tensorflow.python.framework.graph_util_impl import must_run_on_cpu
    
    def all_gpu_but_pin_vars_to_cpu(node):
      if must_run_on_cpu(node, FLAGS.pin_vars_to_cpu):
        return "/cpu:0"
      return "/gpu:0"

    with tf.device(all_gpu_but_pin_vars_to_cpu):
       // build graph

(as an aside, I have two suggestions:
- it would be nice if `tf.get_variable` got a new `device` parameter, so we could use `arg_scope` to accomplish the above in a clean way (see tf.slim which supports this, and also `variable` from contrib/framework/python/ops/variables.py)
- alternatively, or additionally, it would be nice if the function passed to `tf.device` were allowed to return `None`, which would result in the default placement)

Then, if we initialize a session with `allow_soft_placement`, the error is thrown _during_ the init op: 

    sess.run(tf.global_variables_initializer())

I was able to work around this with another hack that forces a 2-step initialization:

    try:
      sess.run(tf.global_variables_initializer())
    except:
      sess.run(tf.global_variables_initializer())

This catches the error, variables initialize correctly, and training proceeds ok.
