### ISSUE TITLE
Chinese docs on .org site should not link to .cn site

### ISSUE THREAD

**Issue by gqqnbig** [tensorflow/tensorflow#45008]
https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/tools/nblint/style/tensorflow_docs_l10n.py sets up a rule that in Chinese docs, replace links from .org to .cn. (the change is from https://github.com/tensorflow/docs/commit/07608d0e273157c104920286ebd596f1b766909f)

I always browse Chinese docs on https://www.tensorflow.org , there are so many traps in the docs that extradites me to the .cn site.

Though I'm a Chinese reader, I may or may not have associations with China. Remember Malaysian, Singapore people use Simplified Chinese, as well as American (or wherever) born Chinese. I hope to use the international site.

I think the establishment of the .cn site is a call from the company strategies, but this should be mainly for readers who are in China. For those who are visiting the international site, they can keep visiting the international site, you don't need to take them back to China.

If Google wants to keep letting people in China visiting the .cn site, can you use relative URL?

**Comment by lamberta** [comment]
Thanks, @gqqnbig. This is WAI but will consider for future planning.

> can you use relative URL?

We use relative URLS but this is not always possible because of the way the site is assembled from multiple GitHub repos. And we've heard from contributors that they prefer links that also work in GitHub, as well as Colab. It depends if the link is "crossing the subsite boundary." But the site navigation is relative links so you can always use that to move around on the same domain.

It's more of a useability issue: the `tensorflow.google.cn` proxy works everywhere but `www.tensorflow.org` doesn't work in China. Since most site requests for Chinese language pages come from China, we've decided to make sure those users aren't hitting 404s. You may prefer not to use the `tensorflow.google.cn` proxy, but at least the page works.

If you are able to locally replace `tensorflow.google.cn` => `www.tensorflow.org`, that would work, too.

**Comment by gqqnbig** [comment]
I'm sorry. While I did find bugs in Tensorflow Chinese docs, due to the current rule, I won't contribute to it.
