### ISSUE TITLE
Custom loss function always throws: TypeError: __init__() takes 1 positional argument but 3 were given

### ISSUE THREAD

**Issue by kareemamrr** [tensorflow/tensorflow#45079]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution : Linux Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8.5
- CUDA/cuDNN version: 10.1 / 7.6.5
- GPU model and memory: GTX 1060 (6gb)

**Describe the current behavior**
I've created a custom loss function by subclassing from `tf.keras.losses.Loss` and a model using the functional API and specified its outputs to be that of two layers, I need one of them to passed to the loss function and another is the actual output that should print out to the user. Since there are two outputs I pass a list of the same loss when compiling the model and specify the loss weights as `[1.0, 0.0]` because I only care about the loss of one output. When I try the model using on of the basic losses like `categorical_crossentropy` it runs fine. But when I use the loss function I wrote it throws me `TypeError: __init__() takes 1 positional argument but 3 were given`. Furthermore, when building the model, I tried specifying the output to be only one value instead of two, and the same issue arises.

**Describe the expected behavior**
The loss function should work normally since I wrote it according to the docs.

**Standalone code to reproduce the issue**
[Colab link](https://colab.research.google.com/drive/1nB2kVk_e_Mj3dy8mJ0kka2gHHLUSwiHn?usp=sharing)

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.2, 2.3, nightly versions(`2.5.0-dev20201122`) and was able to reproduce the issue.Please, find the gist [here.](https://colab.research.google.com/gist/ravikyram/271dca3a80c757bd335ae20b05f633b6/untitled529.ipynb) Thanks!

**Comment by kareemamrr** [comment]
Someone suggested passing `EndToEndLoss()` to the `compile` method instead of `EndToEndLoss`, this resulted in the error `    OperatorNotAllowedInGraphError: iterating over `tf.Tensor` is not allowed: AutoGraph did convert this function. This might indicate you are trying to use an unsupported feature.`

**Comment by kareemamrr** [comment]
@rmothukuru will someone provide insight into this?

**Comment by steve3nto** [comment]
that loss function indeed should get only one input, cause it's a simple logistic regression over the cosine similarity, which is a scalar in the range [-1,1]
Did you forget maybe to do the average of the enrollment utterances and then take the cosine similarity with the evaluation utterance before adding the logistic loss layer?

cosine_distance should return a scalar... It's the scalar product of the average enrollment embedding and the evaluation embedding..
I think the error is in `cosine_distance`
`return -K.mean(x * y, axis=-1, keepdims=True)`
while it shall be
`return K.dot(x,y)`

**Comment by steve3nto** [comment]
there is also a mistake in the EndToEndLoss, you should do the 1- switch before applying the -log( )
To avoid using if conditions in the loss, use this trick that usually is learned from implementing logistic regression.
Assuming y_true is 0 or 1 (reject or accept) and score is the cosine similarity in the range [-1,1]
`-( y_true*log(sigmoid(w*score-b)) + (1-y_true)*log(1-sigmoid(w*score-b)) ) `

you can use this directly to get the sigmoid
https://www.tensorflow.org/api_docs/python/tf/keras/activations/sigmoid
instead of using backend.exp and computing it yourself

**Comment by nikitamaia** [comment]
Hi @kareemamrr, I made a couple of changes to your colab and was able to get the training working. Please [see the gist here.](https://colab.research.google.com/gist/nikitamaia/ae3cb10a3b8944031d4ea00c036b7ff3/untitled12.ipynb)

In `model.compile`, you have `loss=EndToEndLoss`, I changed that to `loss=EndToEndLoss()`
I also replaced the np.log with `tf.math.log` in` EndToEndLoss` because using TF ops is preferred over using numpy ops.

**Comment by kareemamrr** [comment]
Thank you both @steve3nto @nikitamaia ! Closing this issue.
