### ISSUE TITLE
AttributeError: 'TensorArray' object has no attribute 'mark_used' with tf.function

### ISSUE THREAD

**Issue by stokhos** [tensorflow/tensorflow#45093]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): colab
- TensorFlow version (use command below):  v2.3.0-54-gfcc4b966f1 2.3.1

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:

**Describe the current behavior**

```python
import tensorflow as tf
import tensorflow_probability as tfp
tfd = tfp.distributions 

class Test(tf.Module):
  def __init__(self):
    self.log_likes_list = None
    self.i = tf.constant(0)

  @tf.function
  def __call__(self, samples):

    @tf.function
    def rnd():
        return tfd.Normal(0,1).sample()+ tfd.Normal(3,1).sample()
      
    if self.log_likes_list is None:
        self.log_likes_list = tf.TensorArray(tf.float32, size=samples) 

    def cond(x,i):
        return tf.less(i, samples) 

    def body(x,i):
        #x=x.write(i,tfm.reduce_sum(tfd.Normal(rnd(), 1).log_prob(0.4)))
        # AttributeError: 'TensorArray' object has no attribute 'mark_used'
        x.write(i,tfm.reduce_sum(tfd.Normal(rnd(), 1).log_prob(0.4))).mark_used()
        return x, i+1 

    self.log_likes_list, i = tf.while_loop(cond, body, [self.log_likes_list, self.i])

    self.log_likes = self.log_likes_list.stack()

    self.log_like = tfm.reduce_mean(self.log_likes)

    loss = self.log_like

    return loss


T= Test()
t= T(5)

T.log_likes, T.log_like, 
# the code in below is not running 
T.log_likes_list.stack()
```

**Describe the expected behavior**
How can get values in t.log_likes, and t.log_like, and t.log_likes_list?

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/1ddlIXUBOHd5umTaCW-xghWk3bTOIKhVf#scrollTo=-yj19j0eC_cj

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@stokhos 
I ran the code shared and face a different error, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/08c39b7061660280481784ce0790615a/untitled468.ipynb).
ALso grant access tot the drive shared.

**Comment by stokhos** [comment]
https://colab.research.google.com/drive/1ddlIXUBOHd5umTaCW-xghWk3bTOIKhVf?usp=sharing

**Comment by Saduf2019** [comment]
I am able to replicate the issue please find the [gist here](https://colab.research.google.com/gist/Saduf2019/56d83db34bc7d3dda33dc00a31ee21b8/untitled474.ipynb).

**Comment by mdanatg** [comment]
@cheshire FYI

Sorry for the delay. I think the warning about `mark_used` is quite misleading, we'll need to fix it. You almost never want to use it. The warning itself was meant to caution that you should always assign the result of `x.write` back to `x`. It's similar to Pandas, if you're familiar with it.

There is another limitation of tf.function here: when you want to pass values outside the `tf.function`, you must either return them, or use `tf.Variable`. Assigning to `self.property` won't work properly. This is something we intend to fix, and should have a warning message, but in the mean time, a workaround is to use Variables.

I rewrote your code to get it to run without error, see below.
A few more notes:
 * Since `tf.Variable` cannot change shape, I used padding for `self.log_likes`
 * I also took the liberty to write the `tf.while_loop` in a shorter form since the function is autographed
 * I recommend calling the function with a Tensor (that is, `tf.constant(5)` instead of `5`) to avoid unwanted retracing
 * I turned `jit_compile` to False since it seems to reveal a bug; I think that will be fixed soon, and I do recommend turning it on when possible because it helps performance
 * `rnd` doesn't need a separate tf.function - as long as it's called inside one it will be compiled

```
class Test(tf.Module):
  def __init__(self, max_samples=100):
    # Variables to store things across tf.function boundaries (that are not returns/args)
    self.i = tf.Variable(0)
    self.max_samples = max_samples
    self.log_likes = tf.Variable(tf.zeros([max_samples]))
    self.log_like = tf.Variable(0.0)

  @tf.function  # Should be able to use jit_compile=True soon, once a shape bug is fixed
  def __call__(self, samples):

    def rnd():
        return tfd.Normal(0,1).sample()+ tfd.Normal(3,1).sample()

    # Read things from outside tf.function
    x = tf.TensorArray(tf.float32, size=samples)
    i = self.i.read_value()

    x = x.unstack(self.log_likes.read_value())
    while i < samples:
      # Always assign back to `x` after `x.write`
      x = x.write(i, tfm.reduce_sum(tfd.Normal(rnd(), 1).log_prob(0.4)))
      i += 1

    log_likes = x.stack()
    log_like = tfm.reduce_mean(log_likes)
    loss = tfm.reduce_mean(log_like)

    # Put things back
    self.i.assign(i)
    self.log_likes.assign(tf.pad(log_likes, [[0, self.max_samples - samples]]))
    self.log_like.assign(log_like)

    return loss

T= Test()
# Use a Tensor for samples, otherwise you might get many retraces.
t= T(tf.constant(5))
```

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue  using TF Nightly(2.6).Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/20de0ac979407371e4365456fe8ff1a1/untitled474.ipynb).Thanks!

**Comment by cheshire** [comment]
> I turned jit_compile to False since it seems to reveal a bug; I think that will be fixed soon, and I do recommend turning it on when possible because it helps performance

@mdanatg could you clarify which bug, what error message, and how to repro?

**Comment by mdanatg** [comment]
@cheshire I can't remember if I filed a bug, and if I did, it was internal. The repro is straightforward however: copy the snippet above, and add `jit_compile=True` in the line with the comment: `@tf.function  # Should be able to use jit_compile=True soon, once a shape bug is fixed`. At a quick test, it appears the bug is still there.

**Comment by cheshire** [comment]
@mdanatg There's no XLA bug, it correctly prints that `self.i` is on CPU, and it can't use it from GPU. The problem there is that using an int32 tensor force-places it on CPU, so I had to use int64 as a workaround and to have it correctly running on GPU.

Furthermore, the conversion pass seems to have issues with `samples` being different from `max_samples`, but I haven't looked too closely, as the following works:

```python
import tensorflow as tf
import tensorflow_probability as tfp

tfd = tfp.distributions
tfm = tf.math

class Test(tf.Module):
  def __init__(self, max_samples=100):
    # Variables to store things across tf.function boundaries (that are not returns/args)
    self.i = tf.Variable(0, dtype=tf.int64)
    self.max_samples = max_samples
    self.log_likes = tf.Variable(tf.zeros([max_samples]))
    self.log_like = tf.Variable(0.0)

  @tf.function(jit_compile=True) 
  def __call__(self, samples):

    def rnd():
        return tfd.Normal(0,1).sample()+ tfd.Normal(3,1).sample()

    # Read things from outside tf.function
    x = tf.TensorArray(tf.float32, size=tf.cast(samples, tf.int32))
    i = self.i.read_value()

    x = x.unstack(self.log_likes.read_value())
    while i < samples:
      # Always assign back to `x` after `x.write`
      x = x.write(tf.cast(i, tf.int32),
                  tfm.reduce_sum(tfd.Normal(rnd(), 1).log_prob(0.4)))
      i += 1

    log_likes = x.stack()
    log_like = tfm.reduce_mean(log_likes)
    loss = tfm.reduce_mean(log_like)

    # Put things back
    self.i.assign(i)
    padded = tf.pad(log_likes, [[0, self.max_samples - samples]])
    self.log_likes.assign(padded)
    self.log_like.assign(log_like)

    return loss


T= Test()
t = T(tf.constant(100, dtype=tf.int64))
```

**Comment by mdanatg** [comment]
@cheshire are you sure we're seeing the same error? This is what I'm getting (tried on tf-nightly too, same error):

```
UnimplementedError: Shape of resource _AnonymousVar7 cannot be changed after initialization: old shape was [100], new shape is [195]
	 [[{{node AssignVariableOp_1}}]] [Op:__inference___call___292]
```

**Comment by cheshire** [comment]
@mdanatg I'm looking into that one. The int32 error appears when running on a GPU.

On CPU, the error you mention is gone if you run with samples=max_samples.

Shape-wise, I'm trying to see what is exactly going on. If we run in pure eager, with no `tf.function` annotation, how is `x = x.unstack(self.log_likes.read_value())` supposed to work?

`x` is of size `samples`, and `self.log_likes` is of size `self.max_samples`, so I don't see how that could work? Eager execution complaints about the same thing. I would guess that is what confusing the compilation.

**Comment by mdanatg** [comment]
Yes, that sounds like the reason. I wouldn't test this one in eager mode - TensorArray has different implementations in eager and graph and they seem to have diverged (cleaning them up is a longstanding todo...).

The `size` passed to TensorArray is just its initial size - unstack is supposed to resize it if necessary, but the documentation doesn't seem to clarify that. Would that explain the error?

**Comment by cheshire** [comment]
> The size passed to TensorArray is just its initial size - unstack is supposed to resize it if necessary

I don't think that's the case - at least that's not what eager runtime is doing.

**Comment by mdanatg** [comment]
I would definitely use the graph implementation for reference - I don't think the eager implementation is even used much.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
