### ISSUE TITLE
C and Java perfomance differences under Android

### ISSUE THREAD

**Issue by MrSherish** [tensorflow/tensorflow#45100]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.7
- Mobile device: Android with MT8512 processor
- TensorFlow installed from (source or binary): Source (C code) and binary (Java)
- TensorFlow version (use command below): v1.12.1-45356-g73272ab087 2.5.0-dev20201107
- Python version: 3.7
- Bazel version: 3.1
- Android NDK version: r21d with API level 22
- Target architecture: armv7

**Describe the current behavior**

I have 2 different models running under TFLite and implementations in Java and C for benchmarking. First model runs about 10% slower using TFLite in C code than Java equivalent. Second model runs about 4-5% faster in C than in Java. Copying to and from input/output buffers is neglible in terms of execution time. Going multithreaded causes both models to run slower in C with bigger gaps.

**Describe the expected behavior**

Inference in plain C should've been at least as fast as in Java in every case.

TFLite in C is built with bazel command:
`bazel build -c opt --config=android_arm --verbose_failures //tensorflow/lite/c:tensorflowlite_c`
Binaries needed for Java are pulled from Tensorflow's provided repositories.

Are there any compile options different for C and Java binaries that may cause performance differences? What else can cause it?

Thanks in advance

**Comment by multiverse-tf** [comment]
> **System information**
> 
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Catalina 10.15.7
> * Mobile device: Android with MT8512 processor

This is a dual-core processor with Amazon's AI Neural processor according to https://www.mediatek.com/blog/amazon-az1-neural-edge-processor-powered-by-mediatek. From this perspective, multithreading (i.e. running with >= 2 CPU threads) might create resource contention on CPU. Speaking of performance, have you tried TFLite NNAPI delegate that might be able to utilize the neural processor?

> * TensorFlow installed from (source or binary): Source (C code) and binary (Java)
> * TensorFlow version (use command below): v1.12.1-45356-g73272ab087 2.5.0-dev20201107

I'm a bit of confused here. What's the exact version of this TF? v1.12.1 or the one pulled from GitHub on 2020/11/07?

> * Python version: 3.7
> * Bazel version: 3.1
> * Android NDK version: r21d with API level 22
> * Target architecture: armv7
> 
> **Describe the current behavior**
> 
> I have 2 different models running under TFLite and implementations in Java and C for benchmarking. First model runs about 10% slower using TFLite in C code than Java equivalent. Second model runs about 4-5% faster in C than in Java. Copying to and from input/output buffers is neglible in terms of execution time. Going multithreaded causes both models to run slower in C with bigger gaps.

Are those performance differences repeatedly reproducible? What're the absolute latency difference? Just wondering whether it might be caused by OS jitters, automatic CPU throttling, OS scheduling etc.

Could you try TFLite's benchmark model tool on your two models and report the performance here? Thx! There're two options here: 
First, we offer pre-built binaries as shown on https://www.tensorflow.org/lite/performance/measurement#native_benchmark_binary.

Secondly, if you prefer to build your own benchmark model tool, you could refer to https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark to build the tool in the type of a C++ native binary, and https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark/android to build the tool in the type of a Java APK. The latter one offers perhaps a more faithful view of runtime performance.

In particular, when benchmarking NNAPI delegate performance, you could refer to https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/README.md#nnapi-delegate (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/delegates/README.md#nnapi-delegate-provider gives more details) for various parameters we support.

> 
> **Describe the expected behavior**
> 
> Inference in plain C should've been at least as fast as in Java in every case.
> 
> TFLite in C is built with bazel command:
> `bazel build -c opt --config=android_arm --verbose_failures //tensorflow/lite/c:tensorflowlite_c`
> Binaries needed for Java are pulled from Tensorflow's provided repositories.
> 
> Are there any compile options different for C and Java binaries that may cause performance differences? What else can cause it?
> 
> Thanks in advance

**Comment by MrSherish** [comment]
> From this perspective, multithreading (i.e. running with >= 2 CPU threads) might create resource contention on CPU. 
I have also tried it on different CPU with 4 cores, and the results diverge a lot more when using 2 out of 4 cores in C vs Java.

> Speaking of performance, have you tried TFLite NNAPI delegate that might be able to utilize the neural processor?
Currently I cannot do that.

> I'm a bit of confused here. What's the exact version of this TF? v1.12.1 or the one pulled from GitHub on 2020/11/07?
2.5.0-dev20201107, the command output turned to be weird

> Are those performance differences repeatedly reproducible? What're the absolute latency difference? Just wondering whether it might be caused by OS jitters, automatic CPU throttling, OS scheduling etc.
Yeah, these are reproducible and similar every time. For one model (10% slower in C) the absolute difference would be about 0.5 seconds, 5.4 secs (C) vs 5.9 (Java).
> Could you try TFLite's benchmark model tool on your two models and report the performance here?
I am working on that, does the APK benchmark accept exactly same parameters as the C++ one? It doesn't seem to respect `input_layer_value_range` `input_layer` and `input_layer_shape` parameters, resulting in errors - model needs some constraints on the input.

**Comment by multiverse-tf** [comment]
> > From this perspective, multithreading (i.e. running with >= 2 CPU threads) might create resource contention on CPU.
> 
> I have also tried it on different CPU with 4 cores, and the results diverge a lot more when using 2 out of 4 cores in C vs Java.
> 
> > Speaking of performance, have you tried TFLite NNAPI delegate that might be able to utilize the neural processor?
> 
> Currently I cannot do that.
> 
> > I'm a bit of confused here. What's the exact version of this TF? v1.12.1 or the one pulled from GitHub on 2020/11/07?
> 
> 2.5.0-dev20201107, the command output turned to be weird
> 
> > Are those performance differences repeatedly reproducible? What're the absolute latency difference? Just wondering whether it might be caused by OS jitters, automatic CPU throttling, OS scheduling etc.
> 
> Yeah, these are reproducible and similar every time. For one model (10% slower in C) the absolute difference would be about 0.5 seconds, 5.4 secs (C) vs 5.9 (Java).
Typo? Is C a bit of faster here?
> 
> > Could you try TFLite's benchmark model tool on your two models and report the performance here?
> 
> I am working on that, does the APK benchmark accept exactly same parameters as the C++ one? It doesn't seem to respect `input_layer_value_range` `input_layer` and `input_layer_shape` parameters, resulting in errors - model needs some constraints on the input.

Yes, the APK one should accept the exact same set of parameters that the C++ one accepts. @hajuho Could you help to take a look at this?

**Comment by MrSherish** [comment]
> Typo? Is C a bit faster here?

Yeah, sorry that was a typo. Java was meant to be faster.

**Comment by mohantym** [comment]
Hi @MrSherish !
1.x has been depreciated and not supported any more. 

For 2.11 version,  Java runtime instructions has been updated recently.

Could you test the bazel built wheels  with [C](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/lib_package/README.md) and [Java](https://www.tensorflow.org/jvm/install) from 2.10/2.11 version and post the benchmarking results here.



Thank you!

**Comment by MrSherish** [comment]
I've never used 1.x version

**Comment by mohantym** [comment]
Ok @MrSherish !
Thanks for the update.
Thank you!

**Comment by sachinprasadhs** [comment]
Could you please test it against our latest Tensorflow version 2.12 which can result in improvement in performance. 
Let us know the outcome. Thanks!
