### ISSUE TITLE
Save model to json on TF 2.3 and TF 2.2

### ISSUE THREAD

**Issue by jjerry-k** [tensorflow/tensorflow#45135]
Hi, I'm Jerry Kim in Korea of Republic.

I faced difference between TF 2.3 and TF 2.2.

After training model using tf 2.3, I saved model using `.to_json()`.

At loading model time, I got error about `Value error:unknown layer : functional`.

If you want to correct this, Edit 

`{"class_name": "Functional", "config": {"name": "functional_1", "layers": [{"class_name": "InputLayer" ...`

to 

`{"class_name": "Model", "config": {"name": "model_1", "layers": [{"class_name": "InputLayer" ...`

After If you get error like `('Keyword argument not understood:', 'groups')`, 

![image](https://user-images.githubusercontent.com/25097024/100039069-e38a9d00-2e47-11eb-8c8a-ed76840b7072.png)

Erase all `"groups":1, `

After then, loading model will work.

Thank you.

**Comment by Saduf2019** [comment]
@jjerry-k 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

Please paste the error message/or any info (using makrdown formatting around it) instead of screenshotting. Screenshots are not searchable so they don't help in looking for the issue and also don't help other people having the same error from finding about the issue.
