### ISSUE TITLE
Allow --cpu=x64_arm64_windows as a compilation target on Windows

### ISSUE THREAD

**Issue by ianier** [tensorflow/tensorflow#45151]
Compilation of TensorFlow on Windows currently assumes x64 as a target CPU architecture. Searching .bzl files for "x64_windows" shows the many places in TF where this assumption is made. 

In principle, though, nothing should prevent compiling TensorFlow to target ARM64 on Windows (--cpu=x64_arm64_windows, see the [bazel doc](https://github.com/bazelbuild/bazel/blob/master/site/docs/windows.md)).

This feature request is about adding support for '--cpu=x64_arm64_windows' to produce ARM64 binaries. The goal is to be able to use TF on Windows on ARM 64 bits.

**Comment by mihaimaruseac** [comment]
Will happily review and approve a PR

**Comment by ianier** [comment]
I would happily work on a PR, but unfortunately my knowledge of Bazel and TF build system is nearly zero. Passing --cpu=x64_arm64_windows causes the TF build system to download LLVM instead of using MSVC. 
@mihaimaruseac : Can you hint where to start fixing/patching? The initial goal is to get the MSVC toolchain invoked, then I should be able to work on the required code changes.

**Comment by mihaimaruseac** [comment]
TF needs to download LLVM to build as it contains a lot of code that uses LLV libraries directly (MLIR)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
