### ISSUE TITLE
module 'gast' has no attribute 'Ellipsis'

### ISSUE THREAD

**Issue by bruceh191** [tensorflow/tensorflow#45295]
``` python
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tqdm.autonotebook import tqdm
%matplotlib inline
from IPython import display
import pandas as pd
import tensorflow_probability as tfp
ds = tfp.distribution
```

![image](https://user-images.githubusercontent.com/46621519/100713763-c0379300-33ef-11eb-81ea-3938e2204309.png)

**Comment by amahendrakar** [comment]
@bruceh191,
I was able to import the modules without any issues. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/e18e9ecad4fb482867f70ce49ed513c3/45295.ipynb#scrollTo=ZzZGjfOAeN5s).

Please provide the following information, so that we can look into this 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Thanks!

**Comment by mihaimaruseac** [comment]
Also, what version of `gast` are you using.
