### ISSUE TITLE
Op to convert numeric tensor to string type faster 

### ISSUE THREAD

**Issue by firejq** [tensorflow/tensorflow#45406]
**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

When we want to convert a tensor with numeric value to string type, there is `tf.as_string` available for us. However, its performance will become very poor along with the input tensor swelling, which is caused due to its implement by `vsnprintf` in my opinion. `vsnprintf` indeed provides a quite rich formatting features but in my case I only want to convert number to string..

According to this [benchmark](http://www.zverovich.net/2020/06/13/fast-int-to-string-revisited.html), `fmt::to_string` is 4x faster than `sprintf`. Therefore, I want to inroduce it into third_patry of tensorflow and create a new function (e.g. `tf.number_to_string`) which can simplely and fast convert numeric tensor to string type based on [`fmtlib`](https://github.com/fmtlib/fmt).

In fact, I have implemented a basic version for `tf.number_to_string`, whose performance in my case has been significantly improved than `tf.as_string`. Considering the versatility and the overall design of the framework, I am looking forward to your suggestions.

**Comment by vnvo2409** [comment]
I think if we write a specific function for conversion between number and string, we should use a different library which is dedicated for that conversion, since `fmt` is still a formatting library. I found a [benchmark](https://github.com/miloyip/dtoa-benchmark) here and I think [double-conversion](https://github.com/google/double-conversion) is a good choice ( it is fast and it supports bazel out-of-the-box ). WDYT ?

**Comment by firejq** [comment]
@vnvo2409 Thanks for your reply!

> `fmt` is still a formatting library.

Although `fmt` is definitely a formatting library, `fmt::to_string` is a function only for conversion between number and string in fact.

> I think double-conversion is a good choice ( it is fast and it supports bazel out-of-the-box ).

`double-conversion` is also a good choice of implementation library worth considering. However, it seems to focus only on the conversion between floating-point numbers and strings, and as for integer numbers, I am currently not sure whether the library also supports it? 

If my concern doesn't actually constitute a issue, then I am going to get more familiar with this library and try to transform my implementation based it. But before that, since the reasons now seem to be incomplete, we might be able to further discuss why we should use `double-conversion` instead of `fmt`...

**Comment by vnvo2409** [comment]
>  `fmt::to_string` is a function only for conversion between number and string in fact.

In that case, `fmt::to_string` is good to me. `double-conversion` does not support integer indeed.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
