### ISSUE TITLE
Incorrect instructions for Tensor RT

### ISSUE THREAD

**Issue by joehoeller** [tensorflow/tensorflow#45410]
The install instruction: https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101

Have this code here: 

```
# Install TensorRT
RUN apt-get install -y --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1 \
    libnvinfer-dev=6.0.1-1+cuda10.1 \
    libnvinfer-plugin6=6.0.1-1+cuda10.1
```

Which returns:

```
E: Unable to locate package libnvinfer6
E: Unable to locate package libnvinfer-dev
E: Unable to locate package libnvinfer-plugin6
```

**Comment by amahendrakar** [comment]
@joehoeller,
I did not face any errors while running the command on Ubuntu 18.04, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/3015fd93b2f31caf1265fd8785bbfe2d/45410.ipynb). 

Could you please restart your machine, run all the commands listed in the [guide](https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101) and check if it works. Thanks!

**Comment by amahendrakar** [comment]
Also in order to expedite the trouble-shooting process, could you please provide the following details

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

and the exact sequence of commands that you executed before running into the error. Thanks!

**Comment by joehoeller** [comment]
It fails in Dockerfile.

**Comment by amahendrakar** [comment]
@joehoeller,
> The install instruction: https://www.tensorflow.org/install/gpu#ubuntu_1804_cuda_101

The guide you have linked is for installing TensorFlow pip packages.

If you're using Docker containers, please follow the instructions as per [this guide](https://www.tensorflow.org/install/docker). Thanks!

**Comment by joehoeller** [comment]
Does TF2 work with CUDA 11?

**Comment by amahendrakar** [comment]
@joehoeller,
Every TensorFlow release is compatible with a certain CUDA and cuDNN version. TF v2.4 and TF-nightly versions are compatible with CUDA 11.

For more information, please take a look at the [tested build configurations](https://www.tensorflow.org/install/source#gpu). Thanks!

**Comment by joehoeller** [comment]
It still doesn’t find GPU on Kubernetes, your suggestions do not solve any
problems. I’ve tested this by deploying torch and rapids in same image and
they can find the GPU.

**Comment by amahendrakar** [comment]
@joehoeller,
Could you please provide the below information so that we can escalate the issue accordingly

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

Thanks!
