### ISSUE TITLE
tf.keras.model.Model-subclassed models do not serialise tf.function-ed methods

### ISSUE THREAD

**Issue by jscant** [tensorflow/tensorflow#45432]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Have not tested
- TensorFlow installed from (source or binary): pip
- TensorFlow version (use command below): 2.5.0-dev20201206
- Python version: 3.7.7
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: 11.0, 8.0.4
- GPU model and memory: NVidia Quatro 5000

**Describe the current behavior**
I have a model which implements a custom training step (tf.keras.models.Model.train_step), which all works fine until serialisation. I understand that because the `train_step` is python code, it needs to be saved as a `tf.function` (graph), and for that it should be decorated including an `input_signature`. However, saving and then reloading models decorated in this way does not seem to recover the custom `train_step`.

**Describe the expected behavior**

Methods decorated by `tf.function` including an `input_signature` should be seralised and loaded along with the weights, optimisers and losses.

**Standalone code to reproduce this issue** 

[Gist](https://colab.research.google.com/drive/1hGqE_s1YFKEFjovEO9Kb-US-5nLsCx6H?usp=sharing)

Thanks you in advance.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/7b0f4b070dd2eda6e0d68e9035e7b703/untitled478.ipynb)

**Comment by saikumarchalla** [comment]
Still an issue in TF 2.5 and TF-Nightly(2.6). Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/a6d5d9f229848715dcb417ae8cd443ae/untitled478.ipynb#scrollTo=XbCGn9Rs2J_l).Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
