### ISSUE TITLE
Mapping LSTM over arbitrary tensor shapes

### ISSUE THREAD

**Issue by jonas-eschmann** [tensorflow/tensorflow#45634]
**System information**
- TensorFlow version 2.3.1:

Dense layers map over tensors of up to rank 5, by just being applied to the last dimension:

```
import tensorflow as tf
m = tf.keras.Sequential([tf.keras.layers.Dense(1)])
print(m(tf.ones((10, 9, 8, 6, 5))).shape)
```
So they consume 1 dimension and allow for a freedom of 4 dimensions of additional structure (where the first one usually represents a batch)

Why is this different for LSTM layers, which only support inputs of rank 3:

This works:
 ```
import tensorflow as tf
m = tf.keras.Sequential([tf.keras.layers.LSTM(1)])
print(m(tf.ones((8, 6, 5))).shape)
```

This doesn't work:
 ```
import tensorflow as tf
m = tf.keras.Sequential([tf.keras.layers.LSTM(1)])
print(m(tf.ones((9, 8, 6, 5))).shape)
```
leading to following error: 

```
ValueError: Input 0 of layer sequential_7 is incompatible with the layer: expected ndim=3, found ndim=4. Full shape received: [9, 8, 6, 5]
```

Also LSTM layers consume 2 dimensions, so there is only 1 additional dimension, which is usually required to be the batch.

I am wondering why there are these limitations and if the LSTM layers could at least made equal to the dense layers in that regard. I am aware that through reshaping one can emulate that behaviour but this raises the question if it introduces an unnecessary computational overhead. In addition to that it is convenient to work with `None` dimensions which makes the reshaping problematic in graph mode.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.2, TF v2.3 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/a09e5d391ccd3dc178a4dbcd035af475/45634.ipynb). Thanks!

**Comment by rmothukuru** [comment]
@jonas-eschmann,
Yes, it is different and it is expected. It is because, **`Dense`** Layer is just a **`Dot Product`** between `Weights` and `Inputs`, added by `Biases`. 

[Documentation of Dense](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dense) states:

> Note: If the input to the layer has a rank greater than 2, then Dense computes the dot product between the inputs and the kernel along the last axis of the inputs and axis 1 of the kernel (using tf.tensordot). For example, if input has dimensions (batch_size, d0, d1), then we create a kernel with shape (d1, units), and the kernel operates along axis 2 of the input, on every sub-tensor of shape (1, 1, d1) (there are batch_size * d0 such sub-tensors). The output in this case will have shape (batch_size, d0, units).


However, [LSTM and GRU](https://towardsdatascience.com/animated-rnn-lstm-and-gru-ef124d06cf45) has different Architecture  and different Operations taking place inside them, which mandates the `Input Tensor` to be **`3-Dimensional`**.

Hence, the documentation of [LSTM](https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU#call_arguments_2) and [GRU](https://www.tensorflow.org/api_docs/python/tf/keras/layers/GRU#call_arguments_2) states:

> inputs: A 3D tensor, with shape [batch, timesteps, feature].

**Comment by rmothukuru** [comment]
@jonas-eschmann,
Can you please respond to the above comment. Thanks!

**Comment by jonas-eschmann** [comment]
Hi, thanks for the response and sorry for the late reply. 
I don't see why recurrent layers should behave differently. The just consume the last two dimensions of the input instead of only the last one. So it operates along axes 1 and 2 of the input (on every sub-tensor of shape (1, d0, d1)). There is no reason why it couldn't operate on subtensors of shape (1, 1, d0, d1), as this would be the same as reshaping the first two dimensions into one batch dimension, applying the recurrent layer (with its current restrictions) and then reshaping again to recover the first two dimensions.

**Comment by rmothukuru** [comment]
@jonas-eschmann,
In case of a Dense Layer, the computation that happen is just, **`Activation(W.X + b)`** but in case of **`LSTM`**, 
because of its `Multi Gate Architecture`, the computations that take place are

```python
it = σ(Wixt + Riht-1 + bWi + bRi)
ft = σ(Wfxt + Rfht-1 + bWf + bRf)
ot = σ(Woxt + Roht-1 + bWo + bRo)
c't = tanh(Wcxt + Rcht-1 + bWc + bRc)
ct = ft ◦ ct-1 + it ◦ c't
ht = ot ◦ tanh(ct)
```

Please find [this link](https://docs.nvidia.com/deeplearning/cudnn/api/index.html#cudnnRNNMode_t) for more details.

Since many calculations are involved in **`LSTM Layer`**, it mandates the Input Shape to be a **`3D Tensor`**. Similarly, a **`Conv2D Layer`** mandates its Input to be a `4D Tensor`, `(N,H,W,C) `.

**Comment by rmothukuru** [comment]
@jonas-eschmann,
Can you please respond to the above comment? Thanks!
