### ISSUE TITLE
  W/native: op_kernel.cc:1401 OP_REQUIRES failed at save_restore_tenProplem restoring the checkpoint in my android app: sor.cc:175 : Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for [B@66ce18

### ISSUE THREAD

**Issue by alejandroaguileraalcalde-ing** [tensorflow/tensorflow#45650]
I have created a simple tensorflow model and trained it on device using tensorflow java api. I send the weights to a server that I created and there I average them with other phones weights and created a upgrated model so I can do Federated Learning. 

When I download the checkpoint_name.ckpt.meta file so I can restore the checkpoint in the app I got one error that I dont understand. I run this code 

Graph graph = new Graph();
graph.importGraphDef(graphdef);
...
checkpoinPrefix = org.tensorflow.Tensors.create("checkpoint_name.ckpt.meta"); 
...
...
sess.runner().feed("save/Const", checkpointPrefix).addTarget("save/restore_all").run();

**error:**
W/native: op_kernel.cc:1401 OP_REQUIRES failed at save_restore_tensor.cc:175 : Not found: Unsuccessful TensorSliceReader constructor: Failed to find any matching files for [B@66ce18

**Comment by amahendrakar** [comment]
@alejandroaguileraalcalde-ing,
In order to expedite the trouble-shooting process, could you please provide the following information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

also also the the exact sequence of commands / steps that you executed before running into the error. Thanks!
