### ISSUE TITLE
Different fill value for different channel with ImageProjectiveTransformV3

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/tensorflow#45717]
**System information**
- TensorFlow version (you are using): 2.4
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently, `tf.raw_ops.ImageProjectiveTransformV3` accepts a scalar `fill_value` that fill out of bound pixel with `fill_value` when `fill_mode` is "constant". However, in some tensorflow repos like tensorflow-addons and tensorflow-models have some additional functionality to suppport different fill value for different channel. It's doable and less burden to do such thing in the C++ ops by checking if fill_value is either a scalar or a vector of #channels. With pure C++ implementation, we do not need compositions of python ops, which is suppposed to be slow.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/image/image_ops.cc#L88-L96
https://github.com/tensorflow/models/blob/master/research/object_detection/utils/autoaugment_utils.py#L1189-L1224
https://github.com/tensorflow/addons/blob/master/tensorflow_addons/image/utils.py#L112-L151

**Will this change the current api? How?**

No. Only change underlying implementation.

**Who will benefit with this feature?**

Users of Tensorflow KPL layers, addons and models.

**Any Other info.**

**Comment by WindQAQ** [comment]
Hi @tanzhenyu, is any suggestion to this? Thannk you!

**Comment by tanzhenyu** [comment]
> Hi @tanzhenyu, is there any suggestion to this? Thannk you!

scalar/vector checking at OpKernel level sounds good to me. Please file a PR

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
