### ISSUE TITLE
tfLite armv7 build Issue

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#45740]
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/make

Is there any option to build for generic armv7 targets other than raspberry pi.
Is this restricted for just raspberry pi targets ? Will the same makefile work for other armv7 targets other than raspi targets.

**Comment by terryheo** [comment]
I don't know what the generic armv7 targets means.
To me, armv7 is very fragmented unlike aarch64 target.
I'm seeing lots of armv7 compatibility issue since their armv7 capability are different each other.

RPI is target for Armv7 which is Cortex-A hard-float little-endian neon-enabled which is compatibility with armhf of Debian.
https://wiki.debian.org/ArmHardFloatPort
It's runnable on any ARMv7 target of Cortext-A hard-float little-endian neon-enabled machines.

You might be able to build other ARMv7 variant but it's your own responsibility.

FYI, this is ABI of the generated ARM binary.
```
$ readelf -A benchmark_model
Attribute Section: aeabi
File Attributes
  Tag_CPU_name: "7-A"
  Tag_CPU_arch: v7
  Tag_CPU_arch_profile: Application
  Tag_ARM_ISA_use: Yes
  Tag_THUMB_ISA_use: Thumb-2
  Tag_FP_arch: VFPv3
  Tag_Advanced_SIMD_arch: NEONv1
  Tag_ABI_PCS_wchar_t: 4
  Tag_ABI_FP_rounding: Needed
  Tag_ABI_FP_denormal: Needed
  Tag_ABI_FP_exceptions: Needed
  Tag_ABI_FP_number_model: IEEE 754
  Tag_ABI_align_needed: 8-byte
  Tag_ABI_enum_size: int
  Tag_ABI_VFP_args: VFP registers
  Tag_CPU_unaligned_access: v6
```
