### ISSUE TITLE
[Documentation bug] Format issue in document of `tf.raw_ops.For`

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#45777]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/raw_ops/For

## Description of issue (what needs changing):
The signature of the function has format issue
![image](https://user-images.githubusercontent.com/24580222/102424794-f1ac8300-3fd9-11eb-81d1-72dec90f96f1.png)

## System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: MacOS Mojave 10.14
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 2.3.0
- **Python version**: 3.7.6

**Comment by Abhishek01039** [comment]
hello @yashk2810 and @lamberta 
can anyone please review this PR?
Thanks

**Comment by chunduriv** [comment]
@DNXie,

This issue is fixed now in `TF2.9`, Please refer to the screenshot below 

![image](https://user-images.githubusercontent.com/74177924/174435301-7bf7571d-da4c-4c30-a00d-3d7641333306.png)

For more details please refer [tf.raw_ops.For](https://www.tensorflow.org/versions/r2.9/api_docs/python/tf/raw_ops/For). Thank you.

**Comment by chunduriv** [comment]
Are you satisfied with the resolution of your issue?
[Yes](https://goo.gl/forms/Oe0tEvODFRoI2gJF3)
[No](https://goo.gl/forms/fUjzOfrtkFbrOT8d2)
