### ISSUE TITLE
Visualizing scalar summaries on the graph

### ISSUE THREAD

**Issue by pronobis** [tensorflow/tensorflow#458]
Would it be possible to visualize the values of scalar summaries (e.g. from a chosen or simply last event) directly on the graph? If not, what is the best way to easily inspect the values of the tensors after the most recent run?

**Comment by danmane** [comment]
We're planning to build closer integration between the graph visualizer and the other event types so that it would be possible to visualize data charts directly on the graph; we haven't started work on it yet, though. 
For now, if you want to inspect values of the tensors you probably want to add a histogram summary, and you can then view the distribution of values from the tensor on the histogram page. (Ideally you would put each run in a separate directory so it's easy to filter between them using the run selector.)
I'll post back with more info when we start building tighter graph vis/event integration. 
Does this answer your question for now?

**Comment by pronobis** [comment]
It does, thanks. Is there an automatic way to generate the runs in separate folders?

**Comment by mlajtos** [comment]
Maybe (TDB)(https://github.com/ericjang/tdb) might help.

**Comment by pronobis** [comment]
That looks promising. Will have to check it out.

**Comment by danmane** [comment]
Closing this since we aren't likely to work on it soon, and it's probably too large and involved a change for external contributors.
