### ISSUE TITLE
Changing kBufferAlignment to 8 from 16 for SIMD extensions fixes TfLite micro_allocator_test

### ISSUE THREAD

**Issue by skribm9** [tensorflow/tensorflow#45857]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.3.1
- Python version: 3.6.9
- Bazel version (if compiling from source): 3.4.1
- GCC/Compiler version (if compiling from source): Ubuntu 7.5.0-3ubuntu1~18.04
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
While testing ```//tensorflow/lite/micro:micro_allocator_test``` on s390x, a segmentation fault was observed.
On debugging, I found an issue with SSE alignment. There were multiple warnings in the logs: ```8 bytes lost due to alignment. To avoid this loss, please make sure the tensor_arena is 16 bytes aligned.``` The TC was failing further when assigning the buffers but it seemed that on working on the warnings and changing `kBufferAlignment` from `16` to `8` fixed the issue.

To debug, I compared the results of this TC on Intel and s390x.
In ```MicroAllocator::Create```, with `kBufferAlignment = 16` ,  and everything else same on Intel and s390x ```uint8_t* aligned_result = reinterpret_cast<uint8_t*>(((data_as_uintptr_t + (alignment - 1)) / alignment) * alignment);``` returns `aligned_result` as ```(uint8_t *) 0x3ffffffe1e0``` where tensor_arena was ```(uint8_t *) 0x3ffffffe1d8```  while on Intel, same returns ```(uint8_t *) 0x7fffffffd2b0``` which is equal to address of tensor_arena or data_as_uintptr_t . If the value of ```kBufferAlignment``` is 8 , then aligned_arena is same as tensor_arena.
Although, I could not find if for s390x tensor buffers should be aligned to 8 bytes or 16 bytes for SIMD extensions, but changing the value to 8 helped in passing the TCs. This value effects a multiple TfLite Micro related test cases.

To our understanding,  s390x can handle any byte alignment. It would be great if we can identify the real cause of this issue and someone can look into this issue from SIMD perspective. 

**Describe the expected behavior**
The tensor arena should not lose any bytes of data due to alignment.

**Standalone code to reproduce the issue**
To reproduce this issue, you can simply run the test case using:
```bazel --host_jvm_args="-Xms1024m" --host_jvm_args="-Xmx2048m" test --host_javabase="@local_jdk//:jdk" --test_tag_filters=-gpu,-benchmark-test,-v1only,-no_oss,-oss_serial  -k --test_timeout 300,450,1200,3600 --build_tests_only --test_output=errors -- //tensorflow/lite/micro:micro_allocator_test```

**Other info / logs** 
A PR was raised with this change and other arena size related fixes. That PR is rejected and closed and I was asked to raise a github issue to discuss this further. PR reference: #45790 . It would be great if we can find out the real cause behind this problem. @advaitjain Can you please help tag someone who would be able to help here. Thanks!

**Comment by freddan80** [comment]
Hi! Some thoughts from my side. 

HW architectures vary a lot and may rely on larger bus bandwidths (e.g. 128bits) to communicate efficiently with the memory. On a related note, Ethos-U55 would require the tensor arena start address (obs: the arena itself, not individual tensors) to be 16 byte aligned. Today that is handled by the micro allocator. The tensor arena and individual tensor alignment depends on the same parameter (kBufferAlignment), so they'd need to split up. A small change, but it may add to the complexity. In the case of SIMD instructions for Arm Cortex-M, the 16 byte tensor alignment does not affect on the SIMD operations, word alignment is fine. 

On the topic of memory savings. If I understand the issue correctly, we may loose up to a worst case of 15 bytes per runtime tensor (and on average 7.5 bytes per runtime tensor) due to alignment. The default greedy memory planner re-uses runtime tensors. Hence, _the size of the arena is dimensioned by the largest combined size of any simultaneously used tensors_, plus "house keeping" dynamic memory allocations. Therefore, the worst case loss due to alignment would be 15 bytes per runtime tensor for this specific simultaneously used tensor combination.

It's quite complex to describe this in words, so I'll add a usecase:

If we use the person detection demo as an example, the a) input and b) output tensor of layer 3 represent that largest combination. The worst case alignment loss would be 30 bytes, 15 bytes for a) + 15bytes for b). That results in only about 0.02% (30/136000) memory increase of the total 136kB arena. Therefore, I think the gain of changing this alignment would be very small. Let me know what you think.

Regarding the issue you ran into, I unfortunately don't have any input.

**Comment by skribm9** [comment]
Thanks @freddan80 for making this easier to understand. I completely agree with you that in this case gain of changing this alignment would be very small. In the case of s390x, to my understanding, the architecture can handle any byte alignment. Although with the TC failure, I started to doubt the effect of changing kBufferAlignment. 
Maybe, as you mentioned, splitting up kBufferAlignment for Tensor arena and individual tensor alignment is what we need here. I noticed that to populate the output arena tensor, allocation was done from tail but because flatbuffer vectors are in LE format, the tensor was first read in BE format(from tail) and then populated. This process seemed very complicated and seemed like adding into the problem of byte-alignment. Is there maybe an underlying problem here for Big Endian systems? 
Just an additional info, To get a successful result, I did have to increase arena_size as well for the Test case.

**Comment by freddan80** [comment]
@skribm9 Interesting observation regarding BE system. @advaitjain, do you know if the tests have been ran on a BE system previously?

**Comment by skribm9** [comment]
Hi @advaitjain do you have some time to look at this issue?

**Comment by advaitjain** [comment]
Apologies for the long delay @skribm9. Yes, I would guess that there is something specific to BE systems here. Unfortunately, we currently do not have the cycles to look into BE support which has been ad-hoc and untested.

In a departure from the way the code is currently implemented, my preference here would be:
 * The TFLM inference code should only support flatbuffers and runtime have the same endianness (without any endian transformations in the code itself).
 * There should be external tooling to convert a LE flatbuffer into a BE flatbuffer (which can then be used with the TFLM interpreter on a BE processor). I'd be ok with having a micro/tools/big_endian folder for such tooling.

@skribm9, let me know if this direction sounds reasonable to you and if this something that you would be interested in contributing.

**Comment by skribm9** [comment]
Thank you for your response @advaitjain. I agree with you, flatbuffers only support Little-endian and has been causing issues in several other test cases as well. We had a discussion for Tensorflow serving code where the community kindly agreed to make changes in flatbuffer related code to make sure that it supports all potential permutations of little/big endian conversion and deployment. This is being tracked under [45009](https://github.com/tensorflow/tensorflow/issues/45009)

If you feel that the flatbuffer related changes can help with this TFLM issue as well, we can certainly wait for that issue to be closed.

**Comment by kun-lu20** [comment]
This issue could be closed since test case `//tensorflow/lite/micro:micro_allocator_test` has been moved out of [tensorflow/tensorflow](https://github.com/tensorflow/tensorflow) repository.

**Comment by kun-lu20** [comment]
Hi @mohantym ,

Thanks! I'm @skribm9 's colleague. Yes, this issue could be closed now.

**Comment by mohantym** [comment]
Ok @kun-lu20 !
Thanks for  the confirmation. Marking this as resolved then.
Thank you!
