### ISSUE TITLE
Need to install tensorflow 1.12.0 for gpt-2, not working

### ISSUE THREAD

**Issue by artiblaster** [tensorflow/tensorflow#45890]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Mint 20 Ulyana
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 12
- Python version: 3.8.3

**Describe the current behavior**

I am trying `pip3 install tensorflow==1.12.0`

Which returns:
`ERROR: Could not find a version that satisfies the requirement tensorflow==1.12.0 (from versions: 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.2.1, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0, 2.3.1, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4)
ERROR: No matching distribution found for tensorflow==1.12.0`

**Describe the expected behavior**

1.12.0 installing

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by amahendrakar** [comment]
@artiblaster,
As per the [tested build configurations](https://www.tensorflow.org/install/source#cpu), TensorFlow 1.12 requires Python 3.3 - 3.6.


Version | Python version | Compiler | Build tools
-- | -- | -- | --
tensorflow-1.15.0 | 2.7, 3.3-3.7 | GCC 7.3.1 | Bazel 0.26.1
tensorflow-1.14.0 | 2.7, 3.3-3.7 | GCC 4.8 | Bazel 0.24.1
tensorflow-1.13.1 | 2.7, 3.3-3.7 | GCC 4.8 | Bazel 0.19.2
tensorflow-1.12.0 | 2.7, 3.3-3.6 | GCC 4.8 | Bazel 0.15.0


Also, I'd suggest you to update TensorFlow to the latest stable version v2.4 since TensorFlow 1.x is not actively supported. Thanks!

**Comment by artiblaster** [comment]
> @artiblaster,
> As per the [tested build configurations](https://www.tensorflow.org/install/source#cpu), TensorFlow 1.12 requires Python 3.3 - 3.6.
> Version 	Python version 	Compiler 	Build tools
> tensorflow-1.15.0 	2.7, 3.3-3.7 	GCC 7.3.1 	Bazel 0.26.1
> tensorflow-1.14.0 	2.7, 3.3-3.7 	GCC 4.8 	Bazel 0.24.1
> tensorflow-1.13.1 	2.7, 3.3-3.7 	GCC 4.8 	Bazel 0.19.2
> tensorflow-1.12.0 	2.7, 3.3-3.6 	GCC 4.8 	Bazel 0.15.0
> 
> Also, I'd suggest you to update TensorFlow to the latest stable version v2.4 since TensorFlow 1.x is not actively supported. Thanks!

Gpt-2 requires tensorflow 1.12. I will try a different python, thanks you!
