### ISSUE TITLE
SavedModelBundle.java do not has serialize，so in spark do not broadcast the load model, only run local or one executor 

### ISSUE THREAD

**Issue by chlyzzo** [tensorflow/tensorflow#45917]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/java/src/main/java/org/tensorflow/SavedModelBundle.java

**Comment by amahendrakar** [comment]
@chlyzzo,
In order to expedite the trouble-shooting process, could you please provide the following information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

and also the exact sequence of commands / steps that you executed before running into the problem. Thanks!
