### ISSUE TITLE
TanhExp activation function

### ISSUE THREAD

**Issue by CSRONOML** [tensorflow/tensorflow#45929]
Please add the new TanhExp activation function, it’s faster to compute and converge better than Mish and Swish.

Link for the paper: https://arxiv.org/pdf/2003.09855.pdf

**Comment by anilkumarKanasani** [comment]
@left-brain , We will work on the new feature addition and submit the code soon

**Comment by sangireddysiva** [comment]
@left-brain, me and @anilkumarKanasani  have added the TanhExp activation functionality and pull request #47472 has been created for the same.

**Comment by jdduke** [comment]
Over to @miaout17 for follow-up.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
