### ISSUE TITLE
Modular filesystem inconsistent rename_file behaviour

### ISSUE THREAD

**Issue by peteboothroyd** [tensorflow/tensorflow#45936]
This is not a contribution.

The new modular filesystem includes a [rename_file](https://github.com/tensorflow/tensorflow/blob/67b4154b7dff78b1a2f1d0cd1ae6bbf6cea90673/tensorflow/c/experimental/filesystem/filesystem_interface.h#L485) operation. The docstring states that the implementation must throw a TF_FAILED_PRECONDITION error if either of the src or dst paths are directories. This is also part of the [test suite](https://github.com/tensorflow/tensorflow/blob/67b4154b7dff78b1a2f1d0cd1ae6bbf6cea90673/tensorflow/c/experimental/filesystem/modular_filesystem_test.cc#L859-L882). However the [gfile rename api description](https://github.com/tensorflow/tensorflow/blob/2800f688ffcce464054e41dbb09a83815dc3810d/tensorflow/python/lib/io/file_io.py#L537) says 'Rename or move a file / __directory__.'. Current implementations of the filesystem interface follow the latter description and will happily rename a directory, eg. [s3](https://github.com/tensorflow/tensorflow/blob/67b4154b7dff78b1a2f1d0cd1ae6bbf6cea90673/tensorflow/c/experimental/filesystem/plugins/s3/s3_filesystem.cc#L1109-L1151), [gcs](https://github.com/tensorflow/tensorflow/blob/67b4154b7dff78b1a2f1d0cd1ae6bbf6cea90673/tensorflow/c/experimental/filesystem/plugins/gcs/gcs_filesystem.cc#L1011-L1024).

Should we follow the existing implementations or the interface documentation?

**Comment by vnvo2409** [comment]
Thank you for pointing this out !

In fact, I am fully aware of this inconsistent. However, given that "directory" isn't supported by [s3](https://docs.aws.amazon.com/AmazonS3/latest/user-guide/using-folders.html), I decided to follow the existing implementations: [s3](https://github.com/tensorflow/tensorflow/blob/9489702e35b16a40a1accf3b8b5ed557efae10c7/tensorflow/core/platform/s3/s3_file_system.cc#L1133) because it saves a lot of resources ( and less flakiness ).

I am working on documentations for the new modular filesystem plugins and it will be done around TF 2.5. Please let me know if you have any question left !

/cc @yongtang @mihaimaruseac

**Comment by mihaimaruseac** [comment]
Wondering if we should change to `rename_path` and support the newer API

**Comment by vnvo2409** [comment]
I think it is a good idea. But it won't solve all the misunderstandings we are having. In my opinion, we just need a better document ( which I am working on ).

**Comment by chunduriv** [comment]
@vnghia,

As per https://github.com/tensorflow/tensorflow/issues/45936#issuecomment-754577776, could you please share any update on the working document? Thank you.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
