### ISSUE TITLE
Rename TF_Attr_Type and TF_Attr_Metadata

### ISSUE THREAD

**Issue by IvanUkhov** [tensorflow/tensorflow#4595]
The names of the `TF_Attr_Type` enum and `TF_Attr_Metadata` struct seem to be unlike any other names in the C API. Contrast them with `TF_OperationDescription`, `TF_SessionOptions`, `TF_SessionWithGraph`, and `TF_DataType`, which are also composed of multiple words. Since 0.11 hasn’t been released yet, perhaps it’s not too late to unify the naming scheme.

Regards,
Ivan

**Comment by yaroslavvb** [comment]
@josh11b

**Comment by asimshankar** [comment]
Thanks for pointing this out @IvanUkhov - this was a silly oversight on my part.
I will have this fixed in HEAD shortly, however we're unlikely to merge that into the release branch for 0.11. 

Once a release branch is cut, we try to avoid merging changes that don't fix a breaking bug in order to prevent release delays. Since this is a naming change of functions barely used yet, it probably isn't worth holding up the release for it.
