### ISSUE TITLE
Tensorflow Lite speed -> mobile vs desktop

### ISSUE THREAD

**Issue by jrash33** [tensorflow/tensorflow#45953]
As I am currently building a mobile application with pretty heavy duty object detection, I switched to tensorflow lite as a way to speed up computing. Everything is lightning fast as expected, but I am seeing 99% of the computation time being overpowered by the interpretation.invoke() function which is obviously critical for inference as described in https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter. 

With over 1400 images to loop my model through, I am seeing the invoke() function take roughly 1 sec for each image extending the total inference time to over 20 min. One extremely important detail to note is that this is run through xcode on my desktop computer and not a mobile device. After extensive research, I have discovered to expect better performance on a mobile device with tensorflow lite.

My question is - are the performance gains from tensorflow lite on a mobile device exponentially faster than desktop? If my run time on desktop is over 20 min, is it even possible for this to decrease to a few minutes on mobile? Tons of forums out there are concluding tflite is obviously faster on mobile than desktop, but I am looking for logistics here. Generally HOW MUCH FASTER? Please help! Thanks!!

**Comment by sayakpaul** [comment]
Great questions here @jrash33. As you rightly pointed out you should expect pretty good speedups with an optimized TensorFlow Lite model even on a commodity mobile phone. 

Now, coming to how much that all really depends on the phone you are running inference on and also the type of model you are using.

Type of model because if you are using the TFLite GPU Delegate then you need to ensure your model does not have dynamic-shaped inputs and also, you would need to minimize the number of ops not supported by the GPU delegate. TFLite GPU delegate works the best when your model is generally in float16 but they have recently added support for integer models. Phones come with different GPU chipsets sometimes and that can vary the extent of speed-up. 

[Here's](https://github.com/sayakpaul/Adventures-in-TensorFlow-Lite/blob/master/DeepLabV3/DeepLab_TFLite_COCO.ipynb)an example that shows how to carefully design the inputs and outputs in your TFLite model if you would run it on GPU delegate.

That said, if you want to get an idea of how faster your model would run on a mobile device I would suggest checking out the [Benchmarking tool](https://www.tensorflow.org/lite/performance/measurement). It gives you a fair idea of different inference statistics such as memory usage, average inference latency, and many more. 

Now, from my personal experience, I have noticed at least 10x speedups on style transfer models (with a MobileNet backend) and 5x speedups on MobileDets all on my humble Realme Pro 2. 

I hope that helps.

**Comment by jrash33** [comment]
this helps a ton! Thank you - I will checkout the benchmarking tool and try to dig deeper into different types of models. I am not too familiar with tflite and am actually just using the tflite file provided to me in autoML from google cloud. I found some scripts online to help me execute inference in swift but was disappointed in the performance as explained earlier. It sounds to me from your response like running this on mobile should fix the issue to the extent that I had hoped. I will definitely be optimizing the model and using the benchmarking tool you recommended, but for now, I think I am good to proceed. Thanks!

**Comment by sayakpaul** [comment]
Sure thing! Please feel free to continue posting your questions here. I will try my best to answer them from my experience.

**Comment by abattery** [comment]
The open-gl based GPU delegate can be runnable on the desktop. That might help accelerating the speed on the desktop. @terryheo

**Comment by sayakpaul** [comment]
Could you point to some relevant resources that talk about this? @abattery

**Comment by terryheo** [comment]
Actually it's OpenCL not OpenGL. You can build x86_64 binary with OpenCL supports.
https://www.tensorflow.org/lite/guide/build_cmake#opencl_gpu_delegate

FYI, it's still experimental and only verified with NVidia CUDA OpenCL 1.2.

**Comment by sayakpaul** [comment]
Interesting. Any information on the amount of speedup one might expect? I understand this is highly model specific. Also, what would be the recommendation for accelerating inference with commodity CPUs?

**Comment by terryheo** [comment]
Regarding GPU performance, check this article.
https://blog.tensorflow.org/2019/01/tensorflow-lite-now-faster-with-mobile.html

Also you can apply quantization which usually gets at least 2x improvement.
https://www.tensorflow.org/lite/performance/model_optimization

Also it's worth to read.
https://www.tensorflow.org/lite/performance/best_practices

**Comment by sayakpaul** [comment]
@terryheo I am aware of the above-mentioned stuff. If I am not wrong all of them are highly mobile-specific. Since that is not under question (I am quite aware of TensorFlow Lite's capability of accelerating mobile-specific models as I already mentioned [here](https://github.com/tensorflow/tensorflow/issues/45953#issuecomment-750821307)) I wanted to understand the practices one should follow when the inference runtime is based on common NVIDIA GPUs or Intel CPUs and so on. 

For GPUs, you mentioned OpenCL related building [here](https://github.com/tensorflow/tensorflow/issues/45953#issuecomment-751565725). But what if I am using an Intel CPU during inference? Are there any recommendations for that? Also, in these cases what is the typical speed-up one might expect? 

Let me know if anything is unclear.

**Comment by sayakpaul** [comment]
@terryheo any further inputs based on my comments above?
