### ISSUE TITLE
tf.data.Data.as_numpy_iterator() creates unnecessary copies

### ISSUE THREAD

**Issue by n2cholas** [tensorflow/tensorflow#45964]
Does `tf.data.Data.as_numpy_iterator()` need to copy the data ([here](https://github.com/tensorflow/tensorflow/blob/v2.4.0/tensorflow/python/data/ops/dataset_ops.py#L3942)), or can the tensor buffer be used directly? This copy can be avoided by using `x._numpy()` instead, like in this Flax ImageNet example [here](https://github.com/google/flax/blob/master/linen_examples/imagenet/train.py#L169-L170). Or, by using the numpy buffer interface, as shown [here](https://github.com/tensorflow/tensorflow/issues/33254#issuecomment-542379165).

**Comment by aaudiber** [comment]
Hi @n2cholas,

`as_numpy_iterator` calls `numpy` instead of `_numpy` as a defensive measure to prevent Tensors from being mutated, causing undefined behavior (short demonstration in https://colab.research.google.com/drive/1WLNyazBbY8ZxGsBHKP3TXASjEAUr7VBI). We can't transparently change the behavior to zero-copy because current users may be relying on the copying mechanism already. Perhaps we could add a `copy=True` parameter, and when `copy=False` we could use `_numpy()` and then set the resulting array's [writeable](https://numpy.org/doc/stable/reference/generated/numpy.ndarray.flags.html) flag to `False`? What are your thoughts on this approach?

As a workaround in the short term, you can define a zero-copy as_numpy_iterator as follows:

```python
def zero_copy_as_numpy_iterator(dataset):
  return map(lambda elem: tf.nest.map_structure(lambda c: c._numpy(), elem), dataset)
```

**Comment by n2cholas** [comment]
Hi @aaudiber, thanks for the response! That makes sense, and I like the idea of adding a `copy=True` parameter. There seems to already be an API to create a zero-copy immutable numpy array from a tensor, that could be used, described [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L1051-L1057).

**Comment by chunduriv** [comment]
@n2cholas,

Please feel free to move this issue to close status if it is resolved for you? Thank you.

**Comment by n2cholas** [comment]
Thanks for the ping @chunduriv, my issue is resolved. Here is the commit for future reference: https://github.com/tensorflow/tensorflow/commit/3e98cbc83e73c834d14137b98da0a26d1d8b7034.
