### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/tensorflow/lite/support/image/ColorSpaceType

### ISSUE THREAD

**Issue by claycontrast** [tensorflow/tensorflow#45997]
Error when using ImageSegmentation in Android

Maybe my ability is not enough and I am prone to make some low-level mistakes, but this problem has really troubled me for a long time, and there is no problem with using other types of models. Thank you.

**Comment by lu-wang-g** [comment]
Sorry to hear that the issue has been bothered you for a while. This is due to a recent breakage of our bintray to Jcenter pipeline. The Java package on the Jcenter is not updated properly. And we are actively looking into this issue, and trying to fix it.

At the mean time, please try the package from [Bintray](https://jcenter.bintray.com/org/tensorflow/tensorflow-lite-support/0.0.0-nightly/). It should be up-to-date.

**Comment by gowthamkpr** [comment]
@hotsx Did you try the solution provided [above](https://github.com/tensorflow/tensorflow/issues/45997#issuecomment-751835941). Please let me know if it has worked for you. Thanks!
