### ISSUE TITLE
 When I use AndroidStudio to import Image Segementation TensorsorflowLite model, there is a problem...

### ISSUE THREAD

**Issue by claycontrast** [tensorflow/tensorflow#45998]
@tensorflow/micro

**System information**
-Pixel 2xl  Android 11

**Describe the problem**
Model:
[ImageSegmentation](https://tfhub.dev/tensorflow/lite-model/deeplabv3/1/metadata/2)

Dependencies：
```
implementation("org.tensorflow:tensorflow-lite-gpu:0.0.0-nightly")
implementation("org.tensorflow:tensorflow-lite-support:0.0.0-nightly")
implementation("org.tensorflow:tensorflow-lite-metadata:0.0.0-nightly")
```

Code:
```
 val options = Model.Options.Builder()
            .setDevice(Model.Device.GPU)
            .setNumThreads(4)
            .build()
val inputImage = TensorImage.fromBitmap(originBitmap)
val model = ImageSegmentationModel.newInstance(context, options)
val result = model.process(inputImage)
result.segmentationMasksAsCategoryList
model.close()
```
Error: `java.lang.IllegalArgumentException: Label number 21 mismatch the shape on axis 1`

**Comment by Saduf2019** [comment]
@hotsx 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by hotsx** [comment]
thanks for reminding

**Comment by lu-wang-g** [comment]
This error is caused by the code of `TensorLabel` [here](https://github.com/tensorflow/tflite-support/blob/93616b1d1397b7d910e4890979185daf53dc81e8/tensorflow_lite_support/java/src/java/org/tensorflow/lite/support/label/TensorLabel.java#L89). I guess you are trying to use TensorLabel to parse the label strings. the output tensor is in the size of `[1,257,257,21]` where the label axis is the fourth one. So you should create the TensorLabel by using this [factory creation method](https://github.com/tensorflow/tflite-support/blob/93616b1d1397b7d910e4890979185daf53dc81e8/tensorflow_lite_support/java/src/java/org/tensorflow/lite/support/label/TensorLabel.java#L75-L76), where the first parameter is a map of axis id (3 in this case) and labels.

However, TensorLabel actually won't help you in this case, because there's no method to allow you to get a map of label string and the sliced TensorBuffer value. The [getMapWithTensorBuffer](https://github.com/tensorflow/tflite-support/blob/93616b1d1397b7d910e4890979185daf53dc81e8/tensorflow_lite_support/java/src/java/org/tensorflow/lite/support/label/TensorLabel.java#L108-L113) method only "allow the mapping on the first axis with size greater than 1". For example it works with the [image classification model](https://www.tensorflow.org/lite/models/image_classification/overview), where the output is in the size of `[1, n]`. If the output tensor size of the image segmentation model is `[1, 21, 257, 257]`, `getMapWithTensorBuffer` can be used.

To parse the labels, you can use [FileUtil.loadLabels](https://github.com/tensorflow/tflite-support/blob/93616b1d1397b7d910e4890979185daf53dc81e8/tensorflow_lite_support/java/src/java/org/tensorflow/lite/support/common/FileUtil.java#L86), such as:
```
labels = FileUtil.loadLabels(metadataExtractor.getAssociatedFile(classesLabelsFileName));
```

Hope it helps.

**Comment by mohantym** [comment]
Hi @claycontrast !
We are checking whether you are still looking for any assistance. Beside checking with above [suggestion](https://stackoverflow.com/a/62603736/11530462), Have you checked for any extra empty lines or extra labels in label.txt file.
Thank you!
