### ISSUE TITLE
Ability to parse non-Example protos without Eager Execution

### ISSUE THREAD

**Issue by atyshka** [tensorflow/tensorflow#46052]
**System information**
- TensorFlow version 2.4.0:
- Are you willing to contribute it (No):

**Describe the feature and the current behavior/state.**
I am trying to use the Waymo open dataset in tensorflow, without using eager execution. The data is not formatted as tf.data.examples, but instead as a custom proto that is serialized. The eager-compatible approach is something like this: `example.ParseFromString(raw_record.numpy())`, which relies on the numpy compatibility of eager tensors. I thought this issue could be solved by the introduction of tf.experimental.numpy, but it does not seem to support iterating like normal numpy arrays. Are there any plans to add iteration support to tensorflow numpy, or support for deserializing protos other than tf.Examples?
 
**Will this change the current api? How?**
If the iteration approach is taken, it will not change the api as iteration methods currently exist but throw errors when called. Other approaches may involve additions to the API for proto desierialization.

**Who will benefit with this feature?**
Users of the Waymo Open Dataset will benefit, as well as anyone else who would like to format their data as custom protos. Tf.example format can be difficult for structured or hierarchical data.

**Comment by cooperlab** [comment]
I ran into this problem too and it's really annoying. TensorFlow's own dataset format can't be parsed in graph mode. We need a function analogous to exmple.ParseFromString that accepts non-eager tensors.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
