### ISSUE TITLE
Resource exhausted:  OOM when allocating tensor with TF 2.4.0

### ISSUE THREAD

**Issue by lmocsi** [tensorflow/tensorflow#46111]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: The code is from PyImageSearch.com, it runs fine on TF 2.3.1
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Windows 10 Pro, version 20H2, OS build: 19042.685
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: -
-   **TensorFlow installed from (source or binary)**: binary
-   **TensorFlow version (use command below)**: 2.4.0 (sorry, 2.4 is uninstalled now, I cannot run that command)
-   **Python version**: 3.7.5
-   **Bazel version (if compiling from source)**: -
-   **GCC/Compiler version (if compiling from source)**: -
-   **CUDA/cuDNN version**: 11.0.2_451.48 / 11.0
-   **GPU model and memory**: NVIDIA GeForce RTX 2060, 6 GB RAM
-   **Exact command to reproduce**: run my python script with my data, after around 940-960 epochs it runs out of memory

### Describe the problem
There is a bug around TensorFlow 2.4.0: the exact same code runs fine with the following components in python:
tensorflow==2.3.1
tensorflow-gpu==2.3.1
cuda_10.1.105_418.96_win10.exe
cudnn-10.1-windows10-x64-v7.6.5.32.zip

But give a "Resource exhausted:  OOM when allocating tensor" error after 900 and some epochs with TF 2.4.0:
tensorflow==2.4.0
tensorflow-gpu==2.4.0
cuda_11.0.2_451.48_win10.exe
cudnn-11.0-windows-x64-v8.0.5.39.zip

In the logs, I found this:
/job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu

Can it be, that TF is switching to cpu instead of gpu at one point?

### Source code / logs
Logs of two runs:
[bug.txt](https://github.com/tensorflow/tensorflow/files/5760806/bug.txt)
[bug2.txt](https://github.com/tensorflow/tensorflow/files/5760807/bug2.txt)

**Comment by Saduf2019** [comment]
@lmocsi 

Please share stand alone indented code and dependencies to replicate or if possible share a colab gist with error reported.

**Comment by lmocsi** [comment]
1. What do you mean by "stand alone indented code and dependencies"? All the code and the 8000 images?
2. What is a "colab gist with error reported"?

**Comment by Saduf2019** [comment]
@lmocsi 
Code simple enough to replicate the issue faced, for us to replicate the issue reported.

**Comment by lmocsi** [comment]
I'm not sure if I can simplify the code for you to be able to reproduce the problem, since it is running on 8000 images, and the problem arises only above 900 iterations.
Could you instead compare the codes of TF 2.3.1 and 2.4.0 with respect to the errors described in the bug txt files?
Python37\lib\site-packages\tensorflow\python\eager\execute.py, line 60 seems to be the starting point.

**Comment by ymodak** [comment]
Have you tried using smaller batch sizes for your training?

**Comment by lmocsi** [comment]
No. The exact same batch size works perfectly on TF 2.3.1.

**Comment by mihaimaruseac** [comment]
Please try to provide a simple minimal reproducer code so that people can use it to bisect the issue and then create a regression test to prevent the issue from appearing in the future.

**Comment by lmocsi** [comment]
As I've said, creating a "simple minimal reproducer code" is extremely difficult in this case, almost at the level of solving the problem.

**Comment by normanheckscher** [comment]
Hello.
Tagging myself into this issue and keeping it alive.

I believe that I might be facing this issue too.
I have upgraded from tf1.14 to 2.4 recently and I think my code is good, although I need to generate some small generic standalone code in the process of debugging my code. 
It will take me a few weeks to get some code in a Colab to see if I can replicate it there.
Will let you know the outcome.
Please advise if anyone resolves this.

**Comment by geoffroy-noel-ddh** [comment]
Similar issue here. OOM exception during a call to model.fit() while it is trying to allocate a tensor.

(0) Resource exhausted:  OOM when allocating tensor with shape[3072,768] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc

The recommendation I have seen everywhere on github and stackoverflow is to reduce the minibatch size. I don't think the batch size is the issue in my case since:
1. error occurs only in the 13th trials. Each trial uses a new instance of the same model architecture. batch size = 8. Previous instance is discarded each time. Why would first 12 trials fit comfortably into GPU memory and not the 13th?
2. I can run 12 trials with batch size = 16. Also crashes at 13th.
3. nvidia-smi logs shows the GPU RAM utilisation doesn't exceeds 58% (batch size = 8) and returns to 0% before each trial (indicating that there is no GPU memory leak).

Reproduced with tensorflow 2.3.1, 2.4.0, 2.4.1; 1080 ti; ubuntu 20.04.

**Comment by normanheckscher** [comment]
@geoffroy-noel-ddh are you using python generators with a tf.keras.Model() and fit()

**Comment by geoffroy-noel-ddh** [comment]
@normanheckscher Thanks for asking. No, the model is instantiated and trained in a method which is called by a loop. I managed to fix the issue, which was due to my training callback (to implement early stopping) being a class instance. By instantiating the callback within the loop, the memory error disappeared. I assume that singleton instance was somehow holding resources from being freed.

**Comment by ymodak** [comment]
Have you considered limiting gpu memory growth?
Make sure you close all python sessions and exit python interpreter to free up memory and try running script as:
```python
#On top of your script
import tensorflow as tf
gpu = tf.config.list_physical_devices('GPU')
tf.config.experimental.set_memory_growth(gpu[0], True) #limits gpu memory
# Rest of your code
```

**Comment by DavidWiesner** [comment]
I have the same issue. @ymodak memory growth does not help. I still get an OOM with keras and tensorflow 2.4 while it was working with 2.3 and 2.2. The memory growth option should not help here. Correct me if I am wrong, but it's only enable / disable that tensorflow reserves all memory in front up vs. when needed.

**Comment by shivamguys** [comment]
any updates?

**Comment by normanheckscher** [comment]
> any updates?

I'm short on time to commit to this, so I'll probably never get to the bottom of it. My conclusion is that the source of this problem is within the tensorflow/cuda code or its a python incompatibility.

Ultimately, I'm just going to revert my codebase back to tensorflow 1.1x, an older version of cuda and import keras as a separate python library. This worked for me in the past and it should work again.
