### ISSUE TITLE
new feature in cuda8.0 release

### ISSUE THREAD

**Issue by fayeshine** [tensorflow/tensorflow#4620]
```
New in CUDA 8
Pascal Architecture Support
Enhance performance out-of-the-box on Pascal GPUs
Simplify programming using Unified Memory including support for large datasets, concurrent data access and atomics
Optimize Unified Memory performance using new data migration APIs
Increase throughput at ultra-fast speeds using NVLINK, new high-speed interconnect
Developer Tools
Identify latent system-level bottlenecks using critical path analysis
Improve productivity up to 2x with NVCC
Tune OpenACC applications and overall host code using new profiling extensions
Libraries
Accelerate graph analytics algorithms with nvGRAPH
Speed-up Deep Learning applications using native support for FP16 and INT8, support for batch operation in cuBLAS
```

Do we have anything to improve in these places
1.Simplify programming using Unified Memory including support for large datasets, concurrent data access and atomics
2.Optimize Unified Memory performance using new data migration APIs
3.Increase throughput at ultra-fast speeds using NVLINK, new high-speed interconnect
4.Speed-up Deep Learning applications using native support for FP16 and INT8, support for batch operation in cuBLAS

**Comment by tatatodd** [comment]
@fayeshine Do you have a specific problem that you're working on, or is this just for general information?

@zheng-xq might have some info on specifics.

**Comment by zheng-xq** [comment]
United memory is great for minimizing effort to port existing CPU application to GPU. This could change in the future, but it doesn't seem to offer much performance benefit for frameworks like TensorFlow that are optimized for GPU. Since all the buffers are in forms of explicitly managed tensors, we can already reap most of the sharing between CPU and GPU through pinned memory, if necessary.

Native support for FP16 had been targeted extensively. More support for INT8 is going to be added as well. 

There are also a lot of interest for high-bandwidth inter-GPU communication primitives. They are likely be to be targeted as well.

**Comment by byronyi** [comment]
Possibly unrelated, but does send/recv between multiple GPUs curently go through main memory? I've been searching in the source, and it would be very helpful if you could give a hint on this.

**Comment by yaroslavvb** [comment]
It can use P2P transfers which don't use CPU. For instance if you have 8
GPUs which can all transfer memory directly to each other, you'll see
something like this in logs

I tensorflow/core/common_runtime/gpu/gpu_init.cc:126] DMA: 0 1 2 3 4 5 6 7
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 0:   Y Y Y Y Y Y Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 1:   Y Y Y Y Y Y Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 2:   Y Y Y Y Y Y Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 3:   Y Y Y Y Y Y Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 4:   Y Y Y Y Y Y Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 5:   Y Y Y Y Y Y Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 6:   Y Y Y Y Y Y Y Y
I tensorflow/core/common_runtime/gpu/gpu_init.cc:136] 7:   Y Y Y Y Y Y Y Y

**Comment by pswpswpsw** [comment]
@yaroslavvb How did tensorflow choose to transfer information() across GPU directly, rather than goes to CPU as an intermediate state? 

Second question, more important, internally, how does tensorflow off-load job to GPU? Does it off-load all training data + weights all together into GPU memory then computing until the end of training, then bring the final weight back to CPU? Or, does it only off-load current batch of training data + weights to GPU memory?

Thanks,
Shawn

**Comment by yaroslavvb** [comment]
The user specifies where to locate weights and training data and TensorFlow adds transfers are necessary. If you place your training data and weights on GPU, and all ops have GPU implementation, then all the data will stay on GPU. You can use timeline profiling to see where ops are executes and when CPU/GPU transfers are taking place -- https://github.com/tensorflow/tensorflow/issues/1824#issuecomment-225754659

**Comment by aselle** [comment]
Since there is no specific bug or feature request settled on, I am closing this for now. Our other performance initiatives will encompass using Cuda 8.0 features. Thank you!
