### ISSUE TITLE
Many errors in the Example of tf.feature_column.categorical_column_with_vocabulary_file

### ISSUE THREAD

**Issue by rakeshmothukuru1** [tensorflow/tensorflow#46211]
## URL(s) with the issue:

Please provide a link to the documentation entry, for example:
https://www.tensorflow.org/api_docs/python/tf/feature_column/categorical_column_with_vocabulary_file

## Description of issue (what needs changing):
In the sentence, 

> Use either (but not both) of num_oov_buckets and default_value to specify how to include out-of-vocabulary values.

since **either** is used, **or** should be used instead of **and**.

When running the **`Example Code`**, it is resulting in the errors mentioned below:

1. 

> NameError: name 'categorical_column_with_vocabulary_file' is not defined

2. 

> NameError: name 'linear_model' is not defined

3. 

> ValueError: All feature_columns must be FeatureColumn instances. Given: Ellipsis

4. 

> NameError: name 'input_layer' is not defined

The code in the documentation should be modified to fix all the above errors. 

Please find the [Github Gist](https://colab.research.google.com/gist/rmothukuru/74b353ebc7046dee6220cb158f25e5bc/categorical_column_with_vocabulary_file_error.ipynb) demonstrating the errors.

**Comment by PratsBhatt** [comment]
I would like to contribute. Could somebody give me some pointers to begin. It will be of immense help. Thank you.

Below is my understanding of the issue:

0. The sentence needs to be updated. This is quiet straight forward.
1. This could be due to the fact that the code has a missing import for `categorical_column_with_vocabulary_file`
2, 3 and 4: I think in this particular example, the writer, tried to provide a pseudo code.

So if I understand correctly, the issue, would like to have a running code in place of pseudo code.

Any pointers will be of immense help.
