### ISSUE TITLE
Input y of 'Greater' op has type float32 that does not match type int64 of x

### ISSUE THREAD

**Issue by hiyamgh** [tensorflow/tensorflow#46291]
I have this code below:
```
tf.contrib.metrics.precision_at_recall(tf.cast(tf.argmax(tf.nn.softmax(query_preds[i], dim=1), axis=1), tf.float32), tf.argmax(query_y, axis=1), target_recall=0.3)
```

It keeps giving me this error. I tried casting as you can see but still not working.

**Comment by hiyamgh** [comment]
Important to note I tried the same function with ```tf.contrib.metrics.accuracy``` but it is working fine:

```
query_accs.append(tf.contrib.metrics.accuracy(tf.argmax(tf.nn.softmax(query_preds[i], dim=1), axis=1),
					                                            tf.argmax(query_y, axis=1)))
```

**Comment by ravikyram** [comment]
@hiyamgh 
Please, fill [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose).
From the information you provided it looks like you are using TF 1.x.
TensorFlow 1.x is not actively supported. Could you please update TensorFlow to the latest stable version v2.4 and check if you are facing the same issue.
In TF 2.4 you can use `tf.keras.metrics.Accuracy` instead of `tf.contrib.metrics.accuracy` as contrib functionality removed in TF 2.x
If you are still facing issue please share colab link or simple standalone code to reproduce the issue in our environment.It helps us in localizing the issue faster. Thanks!
`

`

**Comment by hiyamgh** [comment]
Hello @ravikyram 

Thank you for your fast response. I have upgraded to ``tf 2.4`` but now I am using this now:
```
tf.metrics.Accuracy(tf.argmax(tf.nn.softmax(support_pred), axis=1), tf.argmax(support_y, axis=1))
```

and getting now another error:
```
    ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by hiyamgh** [comment]
I have dumped my sample code here on this colab notebook: [https://colab.research.google.com/drive/1brMeujSY4aSJT_CG5THEL0rfsNeXspi2?usp=sharing](https://colab.research.google.com/drive/1brMeujSY4aSJT_CG5THEL0rfsNeXspi2?usp=sharing)

Thank you in advance.

**Comment by ravikyram** [comment]
@hiyamgh 

Can you please refer similar SO issues [link1](https://stackoverflow.com/questions/22175489/numpy-valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambi/22175725) , [link2](https://stackoverflow.com/questions/10062954/valueerror-the-truth-value-of-an-array-with-more-than-one-element-is-ambiguous) and see if it helps you. Thanks!
