### ISSUE TITLE
Performance and memory usage improvements

### ISSUE THREAD

**Issue by abidmalik1967** [tensorflow/tensorflow#4635]
Is the tensorflow computational graph a good working unit for scaling the performance? Do we need an another layer of Data Flow that can help do the resource management efficiently?

**Comment by abidmalik1967** [comment]
I am doing a deep analysis of tensorflow under different ML algorithms and computing frameworks. The goal is to understand the performance bottlenecks under different environments.  I asked the previous question in this context.

**Comment by concretevitamin** [comment]
I don't understand what it is you're asking -- could you narrow down the scope, and rephrase, please?

**Comment by abidmalik1967** [comment]
I can rephrase the question. Do you think the tensorflow computational graphs are good enough to manage  resource efficiently? My current understanding is that it is not. I put this question to get second opinion from the tensorflow community. May be someone has strong argument/proof of work to negate my understanding.

**Comment by concretevitamin** [comment]
I don't know what "resource" specifically refers to in this context.  Feel free to email me if you have a writeup / report to share, and I can discuss it with the team.  For discussions of this nature, I'd suggest to use the [mailing list](https://groups.google.com/a/tensorflow.org/forum/#!forum/discuss) instead of Github, which is for issues and bugs.

Thanks!

**Comment by abidmalik1967** [comment]
By "resource", I mean memory and core management etc.
