### ISSUE TITLE
tflite custom Bazel build for wasm target 

### ISSUE THREAD

**Issue by dhirajnitk** [tensorflow/tensorflow#46359]
I am using tflite in  c++ cross platform library. I plan to build  them with emscripten for wasm. I wish to use the shared libraries (emscripten).  I am new to bazel but i didnt find any custom build for emscripten target in  the repository. 
I can see that xnnpack helps us with building  optimized kernels for  all targets(including wasm). 
Media pipe also claims to use wasm and it supports both tensorflow and tflite but i dont find any emscripten build in their repository as well.

I need flatbuffer &  inference portion of tflite in wasm

**Comment by dhirajnitk** [comment]
@dsmilkov
I was  going through your old  old ported repo on https://github.com/dsmilkov/tflite-wasm.
I was curious to know if its possible to use emscripten with bazel for current tflite/tensorflow c++ source code to a emscripten static library(.a).

**Comment by terryheo** [comment]
@jdduke might have some idea on this. Could you take a look?

**Comment by dhirajnitk** [comment]
The CmakeLists  for tflite doesn't  support emscripten. I am building the tflite with emscripten. I am able to build all the static needed libraries of libtensorflowlite. I need a delegate to launch the interpreter. But emscripten build also have source code dependencies on xnnpack_delegates.h/cc .
So can you please guide me on how to build xnnpack and xnnpack_delegate.cc so that i could register the xnnpack as delegate using low level delegate api(or any other means) listed in https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/delegates/xnnpack

**Comment by jdduke** [comment]
@annxingyuan may be able to offer some guidance.

**Comment by dhirajnitk** [comment]
I m forcing the xnnpack_delegate.cc  commenting on find_package(xnnpack)
its failing on "fp16.h' file not found"I see that this is half float library. Is this supported  like numpy(not at cpu/compiler level)  
If I am able to build xnnpack_delegate.o then I can use emcc to link it  with libxnnpack.a(from bazel) ??

**Comment by davlhd** [comment]
Is there any news on building tensorflow lite with xnnpack for webassembly?

**Comment by multiverse-tf** [comment]
I think @Maratyszcza could shed more light on this. Thx!

**Comment by Maratyszcza** [comment]
AFAIK, the recent Emscripten SDK releases feature Bazel support, and everything should build out of the box. Look at the scripts in [https://github.com/tensorflow/tfjs/tree/master/tfjs-tflite](tfjs-tflite) for examples.

**Comment by aa333** [comment]
@Maratyszcza If I understand correctly, those scripts only download pre-built wasm binaries of TFlite from Google cloud. Can you please point me to actual build configs from which those modules are built? It doesn't look like they are part of this repo.

**Comment by L1onKing** [comment]
Hello @dhirajnitk ! Could you please tell me if you succeed building TFLite for WASM? I am struggling with the same issue, and I also do not understand how to fetch TFLite libraries from tensorflow.js either.

**Comment by Yongle-Fu** [comment]
i try this works in nodejs runtime
https://github.com/seanchas116/node-tflite

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
