### ISSUE TITLE
Support for LSTM and GRU 

### ISSUE THREAD

**Issue by peter197321** [tensorflow/tensorflow#46390]
Hello,

I wonder if there is support for LSTM and GRU within TensorFlow Lite for Microcontrollers (audio NN models) or any plan to have these operations? 

Thank you.

Best regards,
Peter

**Comment by rmothukuru** [comment]
@peter197321,
Can you please refer [this link](https://www.tensorflow.org/lite/convert/rnn#:~:text=Known%20issues%2Flimitations-,Overview,TensorFlow%20Lite's%20fused%20LSTM%20operations.&text=Provide%20native%20support%20for%20standard,This%20is%20the%20recommended%20option.) which explains LSTM support for TF Lite? Thanks!

**Comment by advaitjain** [comment]
We don't have a good answer at this time. https://github.com/tensorflow/tensorflow/issues/43380 is a related issue and I am going to close the current issue in favor of the earlier one so that any progress can be discussed in a consolidated location.

**Comment by StuartIanNaylor** [comment]
Hi apols to ask again but wondering if 'GRU within TensorFlow Lite for Microcontrollers (audio NN models)' has had any development?

**Comment by advaitjain** [comment]
This is not currently on the list of planned work.

Having said that,the person who created a different github issue on this topic (https://github.com/tensorflow/tensorflow/issues/43380) is an active contributor to TFLM, so if your use-case is aligned with what @yair-ehrenwald is doing, that may be the path forward.

Any additional details on your use case would be useful.

**Comment by StuartIanNaylor** [comment]
It was just a thought to the upcoming esp32-s3 that has vector support and maybe be capable and trying to think of an edge KWS that would work for both microcontroller & embedded linux with tensorflow-lite and reuse of converted models.
The tensorflow4micro has options for kws and if you where to try and keep a common model then higher frameworks will need to use what works on tf4m which just made me wonder with rnn / gru being common rather than the tail wagging the dog is it possible to have tf4m support?

The low cost microcontrollers are of interest for distributed array kws where voice = near / noise = fair by distribution and position and a kws would just be a simple low cost networked sensor that may co-exist with standard standard TensorFlow Lite devices and models.

**Comment by yair-ehrenwald** [comment]
@peter197321 @StuartIanNaylor 

Hi, sorry for reopening this so late, been out of the office for a while.

I've successfully used and deployed models using Keras.GRUCell with TFLM. 
Using Keras.GRU directly results in the TFLite convertor creating a WHILE op so is problematic, but GRUCell works just fine and is implemented with fully connected layers. 
You will probably need to do some rewriting to your model and make it work "frame by frame" but you probably need to do that anyway to get it to run on an actual device.

If you have any specific issues feel free to tag me in an issue with more details and I'll have a look.

**Comment by StuartIanNaylor** [comment]
I never really got to specifics would the examples @

https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_paper_12_labels.md#crnn
https://github.com/google-research/google-research/blob/master/kws_streaming/experiments/kws_experiments_paper_12_labels.md#crnn_state

Make a good base as relatively low ops and have non=stream & stream examples.

**Comment by PenguinsAreLate** [comment]
Commenting to know if there's been any update to adding support for LSTM or GRU layers in TFLM, and if so, could somebody point out some resources to understand how to do it?

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
