### ISSUE TITLE
How the trim existed model for a given tflite model?

### ISSUE THREAD

**Issue by WeiChungChang** [tensorflow/tensorflow#46413]
Given a tflite model, is there any way to trim the model?

It is, for example, for squeezent, 
```
1. Placeholder
2. maxpool
3. fire 1
4. fire 2
5. fire 3
.....
41. average pooling
42. flattern
43. softmax
```
I need a way to trim and keep 
```
3. fire 1
4. fire 2
5. fire 3
```
for this case, the input is replaced to fire1 and output is as fire 3.

I wonder if tensorflow provides such functionaliry?

Thanks~

**Comment by abattery** [comment]
You can modify your TensorFlow Lite model file by using the flatbuffer library manually, which is not the recommended way but it is possible since TensorFlow Lite model itself is based on the flatbuffer format. TFLite serialization library can do that.  https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/serialization

However, I would recommend modifying the original TensorFlow model and converting again, which is much a clean way to achieve the same goal.
