### ISSUE TITLE
Tensorflow Lite OpenCL delegate outputs NaN's when CPU works fine

### ISSUE THREAD

**Issue by DwayneDuane** [tensorflow/tensorflow#46462]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Android 11
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Samsung Galaxy S20 w/ Qualcomm chipset
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): Nightly
- Python version: 3.6
- Bazel version (if compiling from source): 3.7.2
- GCC/Compiler version (if compiling from source): 8.4
- CUDA/cuDNN version: N/A
- GPU model and memory: Adreno 650

**Describe the current behavior**
For my model, the CPU (with or without XNNPACK delegate) produces the correct outputs on Snapdragon 865. However, some of the outputs from the OpenCL GPU delegate are completely wrong. I see NaN's and numbers like 5.83379e+29 in some of the output tensors in the network. The model has more than 1 output, other output tensors of the same model , however, show entirely correct results.

As far as I am aware, I have turned off FP16 optimizations so that model runs at full 32 bit floating point precision:

        TfLiteGpuDelegateOptionsV2 options;
        options.is_precision_loss_allowed = 0;
        options.inference_preference = TFLITE_GPU_INFERENCE_PREFERENCE_FAST_SINGLE_ANSWER;
        options.inference_priority1 = TFLITE_GPU_INFERENCE_PRIORITY_MAX_PRECISION;
        options.inference_priority2 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
        options.inference_priority3 = TFLITE_GPU_INFERENCE_PRIORITY_AUTO;
 
**Describe the expected behavior**
CPU outputs and GPU delegate outputs should match.

**Standalone code to reproduce the issue**
You can find the C++ sample code (along with the .tflite model, the original Keras model, Keras->TFLite conversion script, complete sample output from CPU and OpenCL GPU) that reproduces this error at https://github.com/DwayneDuane/tensorflow_lite_opencl_bug

**Comment by rose-jinyang** [comment]
Hi
Could u provide the commands to build OpenCL backend TFLite GPU delegate?
Thanks

**Comment by DwayneDuane** [comment]
@rose-jinyang 
Here is my build command:

`bazel build -c opt --config=android_arm64 --cxxopt=-std=c++14 --config=mkl --config=mkl_aarch64 --copt -DMESA_EGL_NO_X11_HEADERS --copt -DEGL_NO_X11 //tensorflow/lite:libtensorflowlite.so //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so`

**Comment by rose-jinyang** [comment]
Hi @DwayneDuane 
Could u check the following issue?
https://github.com/tensorflow/tensorflow/issues/46498
Thanks

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
