### ISSUE TITLE
Addition of Pull request template

### ISSUE THREAD

**Issue by vat0599** [tensorflow/tensorflow#46482]
I noticed that this repository has a issue related template, but is missing PR related template. Adding this will have high value to the community as it will help for first time contributers to navigate through their issue effectively.

**Comment by rthadur** [comment]
@vat0599 thanks for the suggestion. We will discuss with team internally.

cc @mihaimaruseac

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
