### ISSUE TITLE
Efficient and simple encoding for large tensors (such as `encode_raw`) for the use with tensorflow serving needed

### ISSUE THREAD

**Issue by burnpanck** [tensorflow/tensorflow#46493]
**System information**
- TensorFlow version (you are using): 2.4.0
- Are you willing to contribute it (Yes/No): Yes - tough I have no experience with developing tf ops

**Describe the feature and the current behavior/state.**
The stock gRPC/protobuf encoding for requests used in tensorflow serving carries large per-value processing overhead,
even though that encoding is the recommended encoding for optimal performance.
This might not matter much on the server side, where the encoding time is usually dwarved by the model processing time.
However, on the client side, decoding of the repeated values within the tensor proto may cause significant processing load.
(In my particular reinforcement learning case, the majority of time is spent decoding protobuf).

On the request side, this can be avoided by dumping binary data into a string and then using `tf.io.decode_raw` in the model.
However, for the response, a corresponding `tf.io.encode_raw` is missing.
Furthermore, there seems to be no graph mode compatible way to "view"/"bitcast" data into a `tf.string`
(even the workaround presented in https://stackoverflow.com/questions/43403147/how-to-create-a-encode-raw-tensorflow-function ported to TF 2.4.0 is not usable, because apparently `tf.strings.join` is not supported in graph mode). 

Of course, one could work around by implementing a custom API using the C++ API of tensorflow serving,
but that is a large effort with a much more limited application than a general `tf.io.encode_raw`.

**Will this change the current api? How?**
No.

**Who will benefit with this feature?**
Users of tensorflow serving requiring large prediction outputs. As a basic IO operation, many more use cases may be around.

**Comment by zhuzilin** [comment]
I have interest in this feature and will start investigaate this soon :).

**Comment by zhuzilin** [comment]
@burnpanck Hi. I have implemented the `encode_raw` op in the above PR. I wonder if you could provide a realistic use case of it in terms of code that we could add to the doc? Thank you.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
