### ISSUE TITLE
Add option to write tensor to raw byte string

### ISSUE THREAD

**Issue by lminer** [tensorflow/tensorflow#46497]
`tf.io.serialize_tensor` appears to serialize to protobuf. It would be nice to have the option to serialize to a raw byte string as this allows for a lot more flexibility when dealing with data in unsupported formats (e.g. > 16 int bit depth audio data).

I know that this is possible with the `.numpy()` option. However, `.numpy()` is not available in graph mode, meaning there is no way to serialize to byte string in `tensorflow-serving`.

Ideally, `tensorflow-io` would solve this problem. However, as yet there does [not appear](https://github.com/tensorflow/io/issues/414) to be an easy way to get `tensorflow-serving` to support `tensorflow-io` ops.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
