### ISSUE TITLE
help me to solve this i am running a windows machine 8 gb ram python 3.8 cudnn 6.5 cuda 11 geforce 210

### ISSUE THREAD

**Issue by seviksindia** [tensorflow/tensorflow#46490]
(base) C:\Users\ADMIN>python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\tensorflow\__init__.py", line 41, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\__init__.py", line 39, in <module>
    from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 83, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\pywrap_tensorflow.py", line 64, in <module>
    from tensorflow.python._pywrap_tensorflow_internal import *
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: A dynamic link library (DLL) initialization routine failed.

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
>>>

**Comment by chazuttu** [comment]
Your CPU model might be not supporting  AVX instruction sets.

Try Google Colab to use TensorFlow

**Comment by amahendrakar** [comment]
@seviksindia,
You might be facing this issue because of the following reasons

- You are running 32-bit Python or 32-bit OS
- You have not installed the [Microsoft Visual C++ Redistributable](https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads) package
- Your CPU does not support AVX instructions. 

Please take a look at the [system requirements](https://www.tensorflow.org/install/pip#system-requirements) and check if you have the correct dependencies installed.

Also, check similar duplicate issue #36167 for reference. Thanks!

**Comment by ymodak** [comment]
You may want to try using TensorFlow CPU version since the cuda compute capability of your [graphics card](https://www.geeks3d.com/20100606/gpu-computing-nvidia-cuda-compute-capability-comparative-table/) is 1.2 which is less than required minimum cuda compute capability of 3.5
See https://www.tensorflow.org/install/gpu#hardware_requirements
Thanks!
