### ISSUE TITLE
Docker image tensorflow:latest-gpu-jupyter - Setting a password doesn't work

### ISSUE THREAD

**Issue by Atralb** [tensorflow/tensorflow#46502]
Using image from here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dockerfiles/dockerfiles/devel-gpu-jupyter.Dockerfile

Downloaded from dockerhub with `docker pull tensorflow/tensorflow:latest-gpu-jupyter`

When running the jupyter server, we can normally set up a password in the login page.

However, with this image I get an error 500 after configuring the password.

The password is effectively written to `/root/.jupyter/jupyter_notebook_config.json` but it isn't taken into account by the jupyter server. I.e. you can't connect just as if you had put a wrong password.

On the other hand, this works perfectly when using images from [jupyter/docker-stacks](https://github.com/jupyter/docker-stacks/).

**Comment by Saduf2019** [comment]
@Atralb 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

**Comment by Atralb** [comment]
@Saduf2019 

I'm talking about running the docker container provided by yourselves. I have linked to the dockerfile and every single package version is in there, I couldn't give you a more exhaustive list than that.

The single additional step I can give you is: `docker run -p 8888:8888 tensorflow/tensorflow:latest-gpu-jupyter`, and then it's the steps performed in the GUI as explained in my original post.

**Comment by Daphneitec** [comment]
Hello,
  Any updates about this issue? Please don't close it, -p PASSWORD:password does not help. Thank you.

**Comment by ymodak** [comment]
Is this still an issue?

**Comment by DirtySoc** [comment]
This is still an issue. I'm trying to set a password by using:
```
docker run -e PASSWORD=password tensorflow/tensorflow:1.15.5-gpu-py3-jupyter
```
 and it is not working.  See: https://github.com/tensorflow/tensorflow/issues/6351#issuecomment-637476227

**Comment by mohantym** [comment]
@Atralb !
I could replicate this issue in 2.10 version  and was able to run the container without password even after changing the password in root directory .
Thank you!

**Comment by Atralb** [comment]
@mohantym What do you mean "run the container" ? I'm talking about logging in on the Jupyter UI on the browser.

So what is the current state on fixing this issue @angerson @ymodak ? It' been 2 years with no updates.

Thanks in advance.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
