### ISSUE TITLE
Extracting item from a list with tf.function() :  TypeError: list indices must be integers or slices, not Tensor

### ISSUE THREAD

**Issue by AiaHaruv** [tensorflow/tensorflow#46533]
**System information**
- Have I written custom code (see below):
OS Platform and Distribution: Linux Ubuntu 18.04.5
Python version: 3.7.4
Tensorflow : 2.4.0

**Describe the current behavior**
I have a list of objects (custom type), I want to extract an object in a specific index from a list. However, when running using tf.function() I'm getting an error that the index is a tensor and it should be an integer or slices : 

    TypeError: list indices must be integers or slices, not Tensor

I know I can use tf.gather but the list can't be converted to a tensor since it includes unsupported types (specifically in my case these are loaded estimators). 

    TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [<__main__.my_class object at 0x7f36d11b9c88>, 
    <__main__.my_class object at 0x7f36d11b9828>]. Consider casting elements to a supported type.

In addition, I can't find a way to evaluate the index to convert it to a number with the tf.function.. 

**Standalone code to reproduce the issue**

          import tensorflow as tf
          
          class my_class():
              def __init__(self,name):
                  self.name = name #
          x = [my_class('ron'),my_class('john')]
          
          def extract(idx):
              y = x[idx]
              return y
          y = extract(1)
          print(y)
          
          
          @tf.function(input_signature=[tf.TensorSpec(shape=[1], dtype=tf.int32)])
          def extract(idx):
              y = x[idx]
              return y
          
          y = extract(1)
          print(y)

Output: 

    <__main__.my_class object at 0x7f36d1841978>
    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    <ipython-input-9-1b61ba209201> in <module>()
         18     return y
         19 
    ---> 20 y = extract(1)
         21 print(y)
    
    8 frames
    /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
        983           except Exception as e:  # pylint:disable=broad-except
        984             if hasattr(e, "ag_error_metadata"):
    --> 985               raise e.ag_error_metadata.to_exception(e)
        986             else:
        987               raise
    
    TypeError: in user code:
    
        <ipython-input-9-1b61ba209201>:17 extract  *
            y = x[idx]
    
        TypeError: list indices must be integers or slices, not Tensor.

Is there a way to evaluate the index with tf.function()? or some other function to extract the object from the list (it is a list wrapper)?
Thanks you

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/005e051feacc3282885642e9e51f0016/46533.ipynb). Thanks!

**Comment by jvishnuvardhan** [comment]
@AiaHaruv Based on the error description (`TypeError: list indices must be integers or slices, not Tensor.`), i changed two lines in your code as shown below.

```

# x = [my_class('ron'),my_class('john')] # changed this line
x = [my_class('ron').name,my_class('john').name]

@tf.function#(input_signature=[tf.TensorSpec(shape=[1], dtype=tf.int32)]) # changed this line 
```

After those two modifications, everything worked as expected. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/a3cf9175313c2695b0dd8293ab25bc20/46533.ipynb). 

Please feel free to check the [guide](https://www.tensorflow.org/guide/function) on `tf.funciton`.

Please verify once and close the issue if this was resolved for you. Thanks!

**Comment by AiaHaruv** [comment]
@jvishnuvardhan - thank you for your response. 
This actually doesn't solve my issue since my problem is to extract from a list which contain a custom class (and not a supported type as str, float, etc). I created this class just for an example to easily reproduce. My actual list includes estimators and I want to extract from the list an estimator from a specific position.
Also, in my case the idx is initially a tensor and not a number (there are other processes before the extraction from the list). I see that if the idx is just a number and not a tensor, it succeed to extract the class from the list. Is there a way to convert it to a number somehow within the run of tf.function?

**Comment by mdanatg** [comment]
There are a few ways to index a static list based on a Tensor value, but there are caveats you should know first, especially if the list may contain different custom objects.

The 100% proof solution is to use a [tf.py_function](https://www.tensorflow.org/api_docs/python/tf/py_function) - pass the index as argument, and close over the list, and then return any tensors you need to extract from the objects.

To see whether methods that don't rely on py_function, can you tell us more about the use case:
 * is the list expected to change much in between calls to `extract`?
 * is the type of objects at each index expected to change across calls?
The reason why those questions are important is because reading from a Python list, and working with custom object counts as Python side effect - [this guide](https://www.tensorflow.org/guide/function#executing_python_side_effects) explains a bit about their caveats.

**Comment by AiaHaruv** [comment]
@mdanatg - thank you for your answer. 
I read about the tf.py_function and I saw this caveat:

  "The body of the function (i.e. func) will not be serialized in a GraphDef. Therefore, you should not use this function if you need to serialize your model and restore it in a different environment."

My use case is that I need to save my model and then convert it to a tflite model (to run inside an android app). 
So if I understand correctly, I can't use tf.py_function for that, right? 

Specifically, my list is a list of loaded estimators (https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator), and I want to be able to get as an input to the function the indices to use the right models for a user (instead of loading them on runtime). 

Not 100% related, but I encountered a similar problem also when trying to predict using the loaded estimator. 
(I detailed this error in this issue : https://github.com/tensorflow/tensorflow/issues/46340 ).
When generating an example to input to the estimator, I followed the examples here: https://www.tensorflow.org/api_docs/python/tf/train/Example 
However, to create the example using the recommended function :
```
    def _float_feature(value):
         """Returns a float_list from a float / double."""
          return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))
```
I also get an error if the value is a tensor (and it is by default if I'm using tf.function) . And to create the proto message I must have the values themselves.
(It is related for me since in both of these issues I need to get the tensor evaluation and if I understand correctly, currently there is no way of doing so when using the tf.function). 

Thank you in advance,

**Comment by mdanatg** [comment]
That's correct, if you need to save or export the model, then py_function is not an option.

If the list of loaded estimators is static (i.e. you load it once, and doesn't ever change without re-saving the model), then this can be done using [tf.switch_case](https://www.tensorflow.org/api_docs/python/tf/switch_case). The restriction is that you need to write things as tensor-in, tensor-out functions.

Meaning, that instead of this:

```
do_domething(estimator):
  ...  code ...
do_something(estimators[0])
do_something(estimators[1])
```

we write
```
do_something_with_ron():
  ... code using estimators[0] ...
do_something_with_john():
  ... code using estimators[1] ...
do_something_with_ron()
do_something_with_john()
```

Then you can use tf.switch_case in a way like this:

```
def use_item_0():
  obj = x[0]
  y = # do calculations with obj
  return y  # y must be a tensor or structure of tensors

def extract(idx):
  y = tf.switch_case(
    idx,
    [use_item_0, use_item_1, ...]
  )
```

This dance is necessary because TF graphs are static and fairly limited, and can't represent things like objects in a dynamic manner. So instead of writing the code with the traditional OOP, we instead think about it as building a separate graph for each estimator in the list, then using switch_case to choose which graph to run.

Now, does this mean you'll have to write duplicate code? Not necessarily, because inside a single tf.function you can still write arbitrary code, like for instance a factory. So you should be able to write this:

```
def make_use_item_function(i):
  obj = x[i]
  def use_item():
    y = # do_calculations with obj
    return y
  return use_item

def extract(idx):
  y = tf.switch_case(
    idx,
    [make_use_item_function(0), make_use_item_function(1), ...]
  )
```

**Comment by AiaHaruv** [comment]
@mdanatg - got it, thank you!
