### ISSUE TITLE
mkl_layout_pass_test fails due to optional BFLOAT16 support in MKL/oneDNN

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#46532]
Using TF 2.4 on a haswell system

**Describe the current behavior**

Running the test //tensorflow/core/common_runtime:mkl_layout_pass_test or //tensorflow/core/kernels:mkl fails at the BFloat16 types with e.g. 
```
tensorflow/core/common_runtime/mkl_layout_pass_test.cc:270: Failure
Expected equality of these values:
  DoMklLayoutOptimizationPass()
    Which is: "A(BFloat16Input);B(BFloat16Input);C(Conv2D)|A->C;B->C:1"
  "A(" "BFloat16Input" ");B(" "BFloat16Input" ");C(_MklConv2D);DMT/_0(Const);" "DMT/_1(Const)|A->C;A:control->DMT/_0:control;A:control->" "DMT/_1:control;B->C:1;DMT/_0->C:2;DMT/_1->C:3"
    Which is: "A(BFloat16Input);B(BFloat16Input);C(_MklConv2D);DMT/_0(Const);DMT/_1(Const)|A->C;A:control->DMT/_0:control;A:control->DMT/_1:control;B->C:1;DMT/_0->C:2;DMT/_1->C:3"
[  FAILED  ] MklLayoutPassTest.NodeMerge_Conv2DWithBias_Negative_NoAddBias_DT_BFLOAT16 (1 ms)
```
This is expected on non AVX512 systems as https://github.com/tensorflow/tensorflow/blob/e211aab91939c2666987cc7ccaee29ee0dd2ba41/tensorflow/core/graph/mkl_graph_util.h#L212 checks for runtime support and exits if not found causing the operation to not be changed and failing the test.

**Describe the expected behavior**

Tests pass on any valid system.

**Standalone code to reproduce the issue**

Compile TF with Bazel and `//tensorflow/core/common_runtime:mkl_layout_pass_test` as the target or run that binary manually on a non-AVX-512 system.

**Comment by NeoZhangJianyu** [comment]
@Flamefire 
We are checking it and feedback as soon.

Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by Flamefire** [comment]
The test is no longer present at the previous location. If it has been moved, the issue likely persists.
