### ISSUE TITLE
Regarding tensorflow error in ubuntu 18.04

### ISSUE THREAD

**Issue by Ashitha97** [tensorflow/tensorflow#46564]
F tensorflow/core/platform/cpu_feature_guard.cc:38] The TensorFlow library was compiled to use FMA instructions, but these aren't available on your machine.
Aborted (core dumped)

can anyone please help me with this error.

**Comment by amahendrakar** [comment]
@Ashitha97,
In order to expedite the trouble-shooting process, could you please provide the following details

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

and also the exact sequence of commands / steps that you executed before running into the error. Thanks!
