### ISSUE TITLE
How to avoid downloading when using many times of the tff.simulation.datasets.stackoverflow.load_data()

### ISSUE THREAD

**Issue by DiegoCao** [tensorflow/tensorflow#46574]
As I see in this function, there is a parameter called cache_dir, which can be used to define the ```__pycache__```. However when I set this each time, every time when I run the code, it still tries to download the data. Is there any way that can avoid this? Or should I change the type of HDF5ClientData file to other format then I can save the data?

Thanks a lot for your help!

**Comment by ymodak** [comment]
I see there is another [thread](https://github.com/tensorflow/federated/issues/896) pointing the same problem in TF Federated repository.
TF Federated repository is the right place to surface this issue. I have a tagged the owner as per the `blame` in the above thread. Thus I will close the issue here. Thanks!
