### ISSUE TITLE
Misleading warning when loading weights from hdf5 format weights

### ISSUE THREAD

**Issue by srihari-humbarwadi** [tensorflow/tensorflow#46591]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows, Ubuntu 18.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.0, nightly
- Python version: 3.7
- CUDA/cuDNN version: 11.0, 8.0.4
- GPU model and memory: 1060, 6GB

**Describe the current behavior**
When loading weights with `skip_mismatch=True`, and if the stored weights don't match with the current layer weights, 
the warning seems to show misleading shapes for the stored weights.

**Describe the expected behavior**
I have attached a minimal code to produce the warning. The warning seems confusing. The expected shapes of weights shown in 
the warning should be `((3, 4, 7, 32) vs (3, 4, 7, 16))` rather than `((3, 4, 7, 32) vs (16, 7, 3, 4))`. I suspect the transpose here is causing the change of shape. 
https://github.com/tensorflow/tensorflow/blob/3c84fc9a4def10a80dcf5901c57210d3562f13cd/tensorflow/python/keras/saving/hdf5_format.py#L407-L411

**Standalone code to reproduce the issue**
```python
import tensorflow as tf

model = tf.keras.Sequential(
    tf.keras.layers.Conv2D(16, [3, 4], use_bias=False, input_shape=[10, 10, 7]))
model.save_weights('test.h5')

tf.keras.backend.clear_session()

new_model = tf.keras.Sequential(
    tf.keras.layers.Conv2D(32, [3, 4], use_bias=False, input_shape=[10, 10, 7]))
new_model.load_weights('test.h5', skip_mismatch=True, by_name=True)

WARNING:tensorflow:Skipping loading of weights for layer conv2d due to mismatch in shape ((3, 4, 7, 32) vs (16, 7, 3, 4)).

```

**Comment by Saduf2019** [comment]
@srihari-humbarwadi 
I ran the stand alone code shared and do not see any warning, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/ca32d1fa7556ee0e2eab62fb07325f5c/untitled505.ipynb)

**Comment by srihari-humbarwadi** [comment]
It may require you to restart your kernel before you try to load the weights into the new model. I have modified your gist and we can now see the warning.
![image](https://user-images.githubusercontent.com/24864163/105493807-df5fec00-5cdf-11eb-939b-baeef919adee.png)
Here is the modified [gist](https://colab.research.google.com/gist/srihari-humbarwadi/ea0bb0e4f1473c2bb52cd7e82be9d85a/untitled505.ipynb)

**Comment by Saduf2019** [comment]
I am able to replicate the issue on [tf 2.4 ](https://colab.research.google.com/gist/Saduf2019/70e44138bd31227b37e9d4db4ecb5c12/untitled510.ipynb)and [nightly](https://colab.research.google.com/gist/Saduf2019/756a53cc6d2fd80a9d56d1bcc98b1c3f/untitled509.ipynb)

**Comment by k-w-w** [comment]
Hello! This transpose occurs because, in the past (years ago), the weights of Conv layers could be saved with channel-first or channel-last format. This code tries both formats, and when it fails it raises a warning with the transposed shapes. I'll make the warning a bit clearer so that in the future users won't get tripped out about this. Thanks for the report!

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/c70843fb8cc13024a7b6547eda000445/untitled91.ipynb).Thanks!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
