### ISSUE TITLE
_pywrap_tensorflow_internal.pyd is to big after PyInstaller pack

### ISSUE THREAD

**Issue by roeyilan** [tensorflow/tensorflow#46598]
Hi,

I'm working on packing our Algo pipe Micro-services built from 4 services that are wrapping Algo API's using TensorFlow 2.3.1.
I'm using PyInstaller with a unified spec file to pack all 4 services into one folder so all services executables will use shared resources.

One of the resources is "_pywrap_tensorflow_internal.pyd" file.

The issue is that after the latest version this file size has increased from about 140 MB to 694 MB.
I did not found any related issue yet, I'm thinking that the PyInstaller has increased this file size due to our version progress.

What could be the reason?
Is there an option to decrease this file size?

**System information**
- OS Platform: Win:
- TensorFlow installed: from source
- TensorFlow version: 2.3.1
- Python version: 3.7.6 x64
- Installed using virtualenv? pip? conda?: pip
- PyInstaler version: 4.2

**Comment by Saduf2019** [comment]
@roeyilan 
Please share the error log for us to analyse.

**Comment by roeyilan** [comment]
It's an error, I'm having issue with the file size.
I'm trying to understand why it increased in about 500 MB

**Comment by Christilut** [comment]
I recently ran into the same thing. The `_pywrap_tensorflow_internal.pyd` adds 766MB. Anything that can be done to reduce this? Or split this file up and include only what is used?

**Comment by Honghe** [comment]
In TensorFlow 2.5.0, it it bigger, 838MB.

**Comment by 20080303** [comment]
In TensorFlow 2.6.0, it is 613MB，how to decrease this file size？

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
