### ISSUE TITLE
Error MTCNN with tensorflow ROCM 

### ISSUE THREAD

**Issue by taitang96** [tensorflow/tensorflow#46619]
Traceback (most recent call last):
  File "webcam.py", line 51, in <module>
    main()
  File "webcam.py", line 32, in main
    boxes, _ = detect_face.detect_face(img, minsize, pnet, rnet, onet, threshold, factor)
  File "/home/taitang/tracking/mtcnn-face-detect/src/detect_face.py", line 361, in detect_face
    tmp[dy[k]-1:edy[k],dx[k]-1:edx[k],:] = img[y[k]-1:ey[k],x[k]-1:ex[k],:]
ValueError: could not broadcast input array from shape (457,628,3) into shape (0,628,3)

i tried to run pretrain model MTCNN with Tensorflow ROCM and I received error message as above. Any one help me? Thanks

**Comment by amahendrakar** [comment]
@taitang96,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using.

Also, please take a look at [this comment](https://stackoverflow.com/a/43977626) from a similar StackOverflow query and check if it helps. Thanks!
