### ISSUE TITLE
[Tensorflow Lite] Build static framework for iOS

### ISSUE THREAD

**Issue by DwayneDuane** [tensorflow/tensorflow#46674]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Mac OS Catalina
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): source
- TensorFlow version: 2.5 (nightly)
- Python version: N/A
- Installed using virtualenv? pip? conda?: N/A
- Bazel version (if compiling from source): 3.7
- GCC/Compiler version (if compiling from source): Xcode 12.3
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the problem**
I am trying to cross compile Tensorflow Lite for iOS. I would like to build a **static** framework. Here is the build command I used:

`bazel build --config=ios_arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteC_framework`

The `TensorFlowLiteC_framework` target is defined in `tensorflow/tensorflow/lite/ios/BUILD.apple` as 

```
tflite_ios_static_framework(
    name = "TensorFlowLiteC_framework",
    hdrs = [
        ":c_api.h",
        ":common.h",
        ":xnnpack_delegate.h",
        "//tensorflow/lite/c:c_api_types.h",
    ],
    allowlist_symbols_file = ":allowlist_TensorFlowLiteC.txt",
    bundle_name = "TensorFlowLiteC",
    minimum_os_version = TFL_MINIMUM_OS_VERSION,
    deps = [
        ":tensorflow_lite_c",
    ],
)
```

I had expected the resulting framework (please see the file attached below) to be a static framework, but it appears to be a dynamic framework instead. Inside the `TensorFlowLiteC.framework` folder, there is a binary file `TensorFlowLiteC`. If I do `file TensorFlowLiteC`, I get:

```
TensorFlowLiteC: Mach-O universal binary with 1 architecture: [arm64:Mach-O 64-bit object arm64]
TensorFlowLiteC (for architecture arm64):	Mach-O 64-bit object arm64
```
This appears to be a dynamic lib file to me. As far as I know, if this was a static archive, I should have gotten: `current ar archive`.

[TensorFlowLiteC.framework.zip](https://github.com/tensorflow/tensorflow/files/5870061/TensorFlowLiteC.framework.zip)

Is there a way to actually build Tensorflow Lite into an actual static framework for iOS?

**Provide the exact sequence of commands / steps that you executed before running into the problem**

`bazel build --config=ios_arm64 -c opt //tensorflow/lite/ios:TensorFlowLiteC_framework`

**Comment by yyoon** [comment]
Interesting. We've started to hide unnecessary symbols starting `v2.3.0`, in order to avoid potential symbol collision issues with other frameworks. Looking at it more carefully now, it seems to imply that the resulting framework would have an exported symbol table, and become a dynamic framework.

Can you try building the same target with changing `tflite_ios_static_framework` to just `ios_static_framework` and removing the `allowlist_symbols_file` parameter? Does that produce you an actual static framework?

**Comment by DwayneDuane** [comment]
@yyoon I followed your advice and it worked. I was able to generate a static framework. It feels like it was always the intention for `TensorFlowLiteC_framework` to be static, but it is now building dynamic by mistake. Should I make a merge request based on your suggestions?

**Comment by yyoon** [comment]
No, that's probably not the right thing to do for now.
We started doing the symbol hiding work because there were real users affected by name collisions between TFLite framework and other dependencies. Simply reverting this back to static framework without symbol hiding would reintroduce the issue.

Maybe we should instead add an additional build target for the static framework, which could be built by people who need one.

**Comment by DwayneDuane** [comment]
@yyoon I understand your position. I think having an additional static framework build target would be a very good thing to have. I am trying to build a library of my own (I use TFLite inside my library) and I would like to avoid introducing external dependencies. This is why linking against a static TFLite framework is attractive to me and people with similar use case. 

As for the existing framework build target, I would suggest stop using `tflite_ios_static_framework` build rule. Instead, use a different rule to make it clear that the resulting framework is dynamic.

**Comment by yyoon** [comment]
Thanks for the suggestions!
