### ISSUE TITLE
Integer quantization converts bias of 32-bit float type in conv2d to 8-bit int type on TFLite 

### ISSUE THREAD

**Issue by da2so** [tensorflow/tensorflow#46679]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  **Ubuntu 16.04**
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: **RPI 3b+**
- TensorFlow installed from (source or binary): **source**
- TensorFlow version (use command below): **2.3.1**
- Python version: **3.6**
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):  **5.4.0**
- CUDA/cuDNN version: 
- GPU model and memory: 

**Describe the current behavior**
![error](https://user-images.githubusercontent.com/47438617/105789041-06127100-5fc5-11eb-8430-249c2baf5b08.png)

Used network is a kind of resnet18 and this network is applied int8 quantization by using TFLite. But bias of one of the conv2d has int8 type. The other bias have int32 type. 

Then, inference with this model is not worked, like as below.
![image](https://user-images.githubusercontent.com/47438617/105789822-740b6800-5fc6-11eb-8819-95f04868bc92.png)
**Describe the expected behavior**

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

I share you kears and tflite versions of resnet18.
[benchmark model.zip](https://github.com/tensorflow/tensorflow/files/5870712/benchmark.model.zip)

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by teijeong** [comment]
This seems to be resolved with nightly version of tensorflow. Can you try again?

**Comment by simonmaurer** [comment]
any news on this? still seems a problem with the latest TF2.5(RC) release

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
