### ISSUE TITLE
enable tf.shape on ragged keras input tensor

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#46715]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

current behavior:
currently. tf.shape can't be called on ragged keras input tensor. for example, 
```shell
#!/usr/bin/python3
import tensorflow as tf;

inputs = tf.keras.Input((None, 1), ragged = True);
batch = tf.keras.layers.Lambda(lambda x: tf.shape(x)[0])(inputs);
```
can't get a variable to be infered. tf.shape is necessary because the input tensor shape is not decided before a specific tensor is feed into the keras model.

feature:
support tf.shape on ragged keras input tensor.

**Will this change the current api? How?**

No change to current api

**Who will benefit with this feature?**

developer who use functional or sequential tf.keras.Model to handle NLP related application.

**Any Other info.**

**Comment by pedro-r-marques** [comment]
Workaround:
Use ```type_spec_from_value``` instead of ```tf.shape```. This works for both dense and ragged tensors.
as in:
```
batch = tf.keras.layers.Lambda(lambda x: tf.type_spec_from_value(x).shape[0])(inputs)
```

Full example:
https://colab.research.google.com/drive/1mu8r2iuJsw2vjnqxNE3AAoC3LuRpgiw3?usp=sharing

It does seem odd that tf.shape doesn't return the underlying shape. I guess that with ragged tensors there is ambiguity between the shape specification and the bounding_shape(); perhaps the TF team decided not to support the ```tf.shape``` operation; imho it would make the API more consistent if tf.shape was defined and returned the inferred type_spec shape.

**Comment by fchollet** [comment]
@edloper should be able to call `tf.shape()` on a ragged tensor?

**Comment by edloper** [comment]
@fchollet No, `tf.shape` is not defined for ragged tensors -- the shape of a ragged tensor can't be described by a single list of integers.  Internally, we have the RaggedTensorDynamicShape type, which can encode the full shape of a ragged tensor; and we may eventually update it to be a composite tensor, and update `tf.shape(x: RaggedTensor)` to return a `RaggedTensorShape` object, but we haven't done that yet.  (There are good reasons why we do *not* have `tf.shape(x: RaggedTensor)` return `x.bounding_shape()` -- if you're interested, we can talk about them sometime.)

@pedro-r-marques A simpler workaround is `batch = tf.keras.layers.Lambda(lambda x: x.shape[0])(inputs)`.  `Tensor.shape` (and `RaggedTensor.shape`) returns a `TensorShape` object, which describes what's known about a shape at compile time (and may include unknown dimensions).  `tf.shape(x: Tensor)` returns a `Tensor` object that gives the runtime shape of `x` (and will never include unknown dimensions).  So as long as the dimension size is known statically, you can just use `x.shape[0]` instead of `tf.shape(x)[0]`, and it will work for both tensors and ragged tensors.  (Note that `tf.type_spec_from_value(x).shape` is just a more verbose way of saying `x.shape` -- i.e., the result is a `TensorShape`, not a `Tensor`.)  If you *don't* know the batch shape statically, then neither `x.shape[0]` nor `tf.type_spec_from_value(x).shape[0]` will work (both will return `None`).  In that case, you'd currently need to do something like `batch = x.nrows() if isinstance(x, tf.RaggedTensor) else tf.shape(x)[0]`.

**Comment by foxik** [comment]
BTW, if you know that the batch dimension is not ragged, it should be fine to use `bounding_shape`, i.e.,
```python
batch_size = tf.keras.layers.Lambda(lambda x: x.bounding_shape(0))(inputs)
```
or more naturally as
```python
batch_size = inputs.bounding_shape(0)
```

Cheers.

**Comment by jvishnuvardhan** [comment]
@breadbread1984 Can you please check whether @edloper suggestion helped in resolving the issue. Thanks
