### ISSUE TITLE
Difference between regular and fast nms in TFLite 

### ISSUE THREAD

**Issue by AhmedTElthakeb** [tensorflow/tensorflow#46739]
What is the difference between regular and fast Non-Max-Suppression (NMS) in TFLite ? is there any documentation on that?
I mean it terms of accuracy/performance. I understand there is a difference in the time complexity, but why do they yield different results? 

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/kernels/detection_postprocess.cc

**Comment by srjoglekar246** [comment]
(I am not a detection expert, so feel free to verify what I say based on code link mentioned in the answer)

'fast' NMS is equivalent to `class_agnostic_non_max_suppression` from the object detection codebase (see [here](https://github.com/tensorflow/models/blob/master/research/object_detection/core/post_processing.py#L626)).

The high-level overview is that 'regular' NMS performs [Non-Max-Suppression](https://www.coursera.org/lecture/convolutional-neural-networks/non-max-suppression-dvrjH) for *each class separately*, keeping the best scored boxes & pruning away overlapping candidates per-class. These per-class results are then combined into the final output.


Fast NMS, on the other hand, doesn't consider classes at all, and just performs NMS *once* over the whole set of bounding boxes - for each selected candidate at the end, its 'most likely' class is chosen. The time complexity win comes from the fact that NMS is done only once instead of number-of-classes times.

The latter method is less accurate, since it is likely to prune away outputs where 

1) same bounding boxes can be scored highly for very similar classes (TV vs Monitor): In fast NMS, you will likely only see 1 class in the output
2) boxes that have very high overlap but two different classes: fast NMS might just look at the higher-probability class
