### ISSUE TITLE
Implementation of Ordinary Differential Equations

### ISSUE THREAD

**Issue by summa-code** [tensorflow/tensorflow#46750]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): The nightly build
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.** 
We don't have a solution in Tensorflow for UNEVEN time series data. There are implementations using Torch for ODE (Ordinary Differential Equations) RNN.

**Will this change the current api? How?**
Not sure

**Who will benefit with this feature?**
I will be.... but this is a huge gap in Tensorflow right now. There are lots of data that are generated with uneven gap between them. Tensorflow does not have a viable solution right now.

**Any Other info.**
https://www.sciencedirect.com/science/article/abs/pii/S095219762030292X
https://towardsdatascience.com/paper-summary-neural-ordinary-differential-equations-37c4e52df128

I don't know, there are many papers on them.

**Comment by rchao** [comment]
Hello summa-code@: thanks for reporting the issue - would you be interested in making a contribution?

**Comment by fchollet** [comment]
+1 to @rchao: we're open to contributions for such a feature. No plans on our side.

**Comment by summa-code** [comment]
And also, i heard that Tensorflow has PhasedLSTM implemented somewhere online. But i could not find it. Anyone know if it is the case ?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
