### ISSUE TITLE
Add placement API for C interface - control subset of devices to make visible for model

### ISSUE THREAD

**Issue by deadeyegoodwin** [tensorflow/tensorflow#46764]
**System information**
- TensorFlow version: 2.3
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
During inference it may be necessary to control how a model is loaded onto the available devices (e.g. GPUs). Two cases that illustrate this are:
- The model is created with explicit device assignments that use more/different devices then are available at inference time. The inference application should be able to query which devices are required by the model and somehow map those devices onto the set of devices that are currently available.
- The model is created without explicit device assignments but the inference application wants to control which device the model should load onto (instead of loading onto the default, "0" device).

The existing GPU options has a visible_device_list setting that seems like it could provide at least part of a solution. Unfortunately, it seems all/most of the GPU options are actually global and not per-session / per-model and so visible_device_list is not actually a solution. This is discussed in #311 and #8136 (the second issue is closed but the underlying issue is not resolved).

**Will this change the current api? How?**
It seems likely.

**Who will benefit with this feature?**
Any application that wants to control how a model is loaded, such as inference applications and servers.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
