### ISSUE TITLE
C API to efficiently share weights and access tensor data during inferencing

### ISSUE THREAD

**Issue by deadeyegoodwin** [tensorflow/tensorflow#46766]
**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
I believe the existing Session API is thread safe so that multiple inferences can be run simultaneously for the same model. It is not clear if doing so also shares the model weights (which are constants during inferencing) so that only a single copy of the weights is required.

The tensor input and output C APIs should have options to use input tensors in-place, from binary blobs, from either CPU/system memory or device (e.g. GPU) memory. This "zero-copy" API would remove any copy overhead and any overhead related to protobuf creation.

**Will this change the current api? How?**
Yes, likely need new C API.

**Who will benefit with this feature?**
Inference applications that need to integrate with TF library and get maximum performance.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
