### ISSUE TITLE
TFLite Converter Version  InCompatibility Issue

### ISSUE THREAD

**Issue by tulasiram58827** [tensorflow/tensorflow#46780]
### 2. Code

Please find this [notebook](https://colab.research.google.com/drive/1slj7OwIZ8M567BDUyNLUI7w-Eag7b55R?usp=sharing)

### 3. Failure after conversion

Model conversion working with `tensorflow-2.3.0` and `tf-nightly` versions and not working with `tensorflow=2.4`(default colab version). Similary model inference is working only with `tensorflow-2.3.0` and not working with both `tensorflow-2.4` and `tf-nightly`

CC: @abattery @khanhlvg

**Comment by ravikyram** [comment]
I have tried in colab with TF 2.4 version and I am seeing converter error.Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/01fbf9eed0166e6af71f59f0ec46ef10/untitled643.ipynb).Thanks!

**Comment by tulasiram58827** [comment]
@ravikyram That is my point. Conversion is successful with `tensorflow-2.3` but erroring out with `tensorflow-2.4`

**Comment by abattery** [comment]
You need to enable select TF op for this case in the conversion. We added more concise logics to fallback to TF ops. This is an intended behavior.

**Comment by abattery** [comment]
TFLite's MaxPool op kernel does not support all inputs like the model's inputs in the gist. However, the older versions converted them without checking its capability to TFLite MaxPool operator. That was a wrong behavior. To reflect the capability of the TFLite MaxPool, the select TF option is needed since the TFLite MaxPool can not handle those inputs and it makes fallback to the select TF option.

**Comment by tulasiram58827** [comment]
Thanks, @abattery for a detailed explanation. It's working as expected.
