### ISSUE TITLE
Expose TString related C API

### ISSUE THREAD

**Issue by Oceania2018** [tensorflow/tensorflow#46803]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow v2.4.1:
- Are you willing to contribute it (Yes):

**Describe the feature and the current behavior/state.**
Since v2.4.0 removed string related APIs like `TF_StringEncode`, we can't operate string in other language binding. What we need are exposing thoses APIs: 
* TF_CAPI_EXPORT extern TF_TString* TF_StringInit();
* TF_CAPI_EXPORT extern void TF_StringCopy(TF_TString *dst, const char *src, size_t size);
* TF_CAPI_EXPORT extern const char* TF_StringGetDataPointer(TF_TString* tstr);
* TF_CAPI_EXPORT extern size_t TF_StringGetSize(TF_TString* tstr);
* TF_CAPI_EXPORT extern void TF_StringDealloc(TF_TString* tstr);

**Will this change the current api? How?**
No changing current api.

**Who will benefit with this feature?**
All other language bindings.

**Any Other info.**
I'm willing to PR these changes.

**Comment by adamcrume** [comment]
I maintain github.com/tensorflow/rust, and upgrading to TensorFlow 2.4 is turning into a major headache.

Removing TF_StringEncode and friends breaks TensorFlow's compatibility guarantees.  https://www.tensorflow.org/guide/versions#what_is_covered states that the C API is covered, so a breaking change in a minor release like this should not have been allowed.  Not only does this create headaches for bindings maintainers, but it also creates headaches for their users, because the TensorFlow version is suddenly tightly coupled with the bindings library version, which was not previously the case.

Using inline functions in the C API is also hostile for other languages, because those other languages can no longer link to the symbols in the shared library, because there are no symbols to link to.  Requiring authors of other language bindings to write C is not trivial, because some of these projects (such as mine) have no C code, and suddenly needing to include it simply to wrap inline functions means manually changing the build to rely on a C compiler and all of the cross-platform headaches that come with that.

**Comment by Oceania2018** [comment]
My PR will make TFString works but in different API, still waiting for merging into master.
