### ISSUE TITLE
tf.quantization.fake_quant_with_min_max_vars(_gradient) crash(abort)

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#46910]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.quantization.fake_quant_with_min_max_vars` and `tf.quantization.fake_quant_with_min_max_vars_gradient` crash(abort)

**Describe the expected behavior**
expect an exception message if the input unexpected instead of crash. 

**Standalone code to reproduce the issue**
~~~python
tf.quantization.fake_quant_with_min_max_vars_gradient(gradients=1, inputs=1, max=[1,1], min=[1,1])
tf.quantization.fake_quant_with_min_max_vars_gradient(gradients=[], inputs=[], max=[1,1], min=[1,1])
tf.quantization.fake_quant_with_min_max_vars(inputs=np.ones((1,1)), max=[1,1], min=[1,1])
~~~

Output
~~~python
2021-02-04 04:05:44.055418: F tensorflow/core/framework/tensor.cc:669] Check failed: 1 == NumElements() (1 vs. 2)Must have a one element tensor
Aborted (core dumped)
~~~

**Comment by Saduf2019** [comment]
@ymodak 
I ran the code shared on tf 2.4 and nightly, colab crashes. please find the [gist here](https://colab.research.google.com/gist/Saduf2019/b6ce7dad554d4bc34a08de023d23ffcd/untitled520.ipynb)

**Comment by DNXie** [comment]
I just found `tf.quantization.fake_quant_with_min_max_vars_per_channel` also aborts
~~~python
tf.quantization.fake_quant_with_min_max_vars_per_channel(inputs=[], max=[], min=np.ones((0,1)))
~~~

**Comment by sushreebarsa** [comment]
I ran the code shared on tf-nightly, colab crashes. please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/bf4216da6dc1467fbf5227bb63ac5878/untitled520.ipynb#scrollTo=gBvtr8o68x53)

**Comment by tilakrayal** [comment]
I ran the code shared on tf 2.7 and nightly(2.8.0-dev20211222), colab crashes. please find the gist [here](https://colab.research.google.com/gist/tilakrayal/6cfc9f05bf1302fb9993301693e79e90/untitled150.ipynb)

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
