### ISSUE TITLE
MeanIoU not ignoring background

### ISSUE THREAD

**Issue by petoor** [tensorflow/tensorflow#46921]
According to https://en.wikipedia.org/wiki/Jaccard_index and the MeanIoU documentation : https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/python/keras/metrics.py#L2722-L2850
The IoU score is TP / (TP+FP+FN)

However the MeanIoU seems to calculate this per class not ignoring the background class.
Minimum working example.

```
import tensorflow as tf

m = tf.keras.metrics.MeanIoU(num_classes=2)
m.update_state([0, 0, 1, 1, 1], [0, 1, 0, 1, 1])

tp = m.total_cm[1,1]
tn = m.total_cm[0,0]
fn = m.total_cm[1,0]
fp = m.total_cm[0,1]

print(m.total_cm)
print(m.result())
print(tp/(tp+fp+fn))
```
Where tensorflow calculates the IoU to be (0.5 + 0.3333) / 2, however to my understanding the correct answer should be 0.5.

Is there a way to get the IoU scores mean for Classes that are not background? (Ignoring cm[0,0] in true positives)

Best regards

**Comment by ravikyram** [comment]
I have tried in colab with TF version 2.4, nightly version (`2.5.0-dev20210204`) and was able to reproduce the issue. Please, find the gist [here](https://colab.research.google.com/gist/ravikyram/e0a078b207fc59e59f83e073dd488435/untitled659.ipynb). Thanks!

**Comment by sachinprasadhs** [comment]
Note that `tf.keras.metrics.MeanIoU` computes IoUs for all individual classes and then returns the mean of these values, which is why you are seeing the difference in result from manual computation vs `tf.keras.metrics.MeanIoU`.
Refer this [gist](https://colab.research.google.com/gist/sachinprasadhs/cd107230793b43c349646b5f7c47f03d/46921.ipynb) which calculates the individual IoU and then does the average.
