### ISSUE TITLE
tf.data function mapping slower when using tf.GradientTape

### ISSUE THREAD

**Issue by PythonFZ** [tensorflow/tensorflow#46961]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): conda binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.7.7
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: - 
- GPU model and memory: -

**Describe the current behavior**

Mapping a function to a `tf.data.Dataset` is slower, than computing the function directly with the tensor.

The example below is exaggerated, but it represents the issue I have, with less gradients but a more complex function.
Further more, the tf.data mapping uses more memory, which is my main concern.

**Describe the expected behavior**

I would expect both function are compiled and should result in similiar performance and memory usage.

**Standalone code to reproduce the issue**

```py
import tensorflow as tf

@tf.function
def func(r):
    with tf.GradientTape(persistent=True, watch_accessed_variables=False) as tape:
        tape.watch(r)
        out = []
        for idx in range(2000):
            out.append(r**idx)
    grad = []
    for layer in out:
        grad.append(tape.gradient(layer, r))
    return tf.stack(grad)

data = tf.random.normal((100000, 1000))
dataset = tf.data.Dataset.from_tensor_slices(data)
dataset = dataset.batch(2).map(func)

# Compile
iterator = iter(dataset)
_ = next(iterator)
_ = func(data[:2])

%timeit next(iterator)  # 57.5 ms ± 265 µs per loop
%timeit func(data[:2])  # 30 ms ± 34.9 µs per loop
```

Link to [Google Colab](https://colab.research.google.com/drive/1-4TrBifOZDEkdeXWwPAkfp7Q6KIRYHfV?usp=sharing)

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/58b3ac239e4bcd9a31024774fcc98b60/untitled524.ipynb)

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
