### ISSUE TITLE
Tensorflow implementation in Julia

### ISSUE THREAD

**Issue by atreyamaj** [tensorflow/tensorflow#46971]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.x
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
Currently, there is no Tensorflow implementation in Julia. Since Julia is the next major upcoming scientific computation language and it is much faster than Python while maintaining similar intuitiveness, I believe that we should have a Julia-version of TF.

**Will this change the current api? How?**
This will not change existing features but will port them over to Julia as well.

**Who will benefit with this feature?**
The entire scientific community will be benefitted as more and more people will start shifting to Julia in the near future, as more and more packages are being developed for it.
**Any Other info.**

**Comment by jvishnuvardhan** [comment]
@atreyamaj Thanks for opening the issue. Features like these are managed by the special interest groups (SIGs). So, Please feel free to open this issue [here](https://github.com/tensorflow/community/issues). 

This repository is only for Bug and performance related to TF (python). So, I am closing this issue here. Thanks!
