### ISSUE TITLE
Construct sparse tensor using keras inputs (keras symbolic tensor)

### ISSUE THREAD

**Issue by stephenzwj** [tensorflow/tensorflow#47010]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): r2.4
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
We want to construct sparse tensors using keras inputs (dens inputs, not sparse inputs). We pass dense_shape, values, and indices as dense inputs and will be using these three to construct a sparse tensor. Particularly, we dont want to use keras inputs with sparse flag on as keras models with sparse input can not be export for serving directly (see this [issue](https://github.com/tensorflow/tensorflow/issues/42018) ).

**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Users need to build and serve models with sparse tensors
**Any Other info.**
#42018

**Comment by tomerk** [comment]
Hi @stephenzwj ,

To treat TF APIs as if they are Keras layers during model construction, we rely on the existing internal tf dispatching mechanism for CompositeTensors (e.g. raggedtensors, sparsetensors) to allow for custom behaviors when built-in tf apis see unknown CompositeTensor types.

Because `__new__` doesn't call `__init__` but the failure triggers in `__init__`, we can't trigger the current fallback-based dispatching approach on SparseTensor instance construction. And, the fact that tf.SparseTensor is a class means we can't change the api to just be a method for backwards compatibility reasons.

So, this isn't fixable (without bad hacks) until the proactive type-checking dispatching described in the extensiontypes rfc is implemented: https://github.com/tensorflow/community/pull/269/files#diff-d7a12dc407449b1bdf3121f46aebaaf1


You should be able to work around this for now by:
1. putting the tf.SparseTensor creation inside of a keras lambda layer
2. Putting the tf.SparseTensor creation inside of a custom layer
3. If you're okay with using the nightlies, you can pass a type_spec that matches your needs directly to tf.keras.Input creation. This should be available in TF 2.5

**Comment by ymodak** [comment]
Closing this issue since its addressed above. Feel free to reopen if necessary. Thanks!
