### ISSUE TITLE
Upload sdists to PyPI

### ISSUE THREAD

**Issue by sub-mod** [tensorflow/tensorflow#47044]
I wanted to check if sdists can be uploaded on PyPi and also understand if there are any issues?
  
   
2017 : https://github.com/tensorflow/tensorflow/issues/7286 (not possible)
```
bazel build //tensorflow/tools/pip_package:build_pip_package     
bazel-bin/tensorflow/tools/pip_package/build_pip_package --src "${srcdir}"    
cd "${srcdir}" && python3 ./setup.py sdist    
```
@perfinion  also mentioned that the above commands cannot create a true sdist since sdist has the compiled *.so files from bazel.
And we need to translate the bazel rules into python build rules so it can compile the libs.

**Comment by mihaimaruseac** [comment]
I think the status of #7286 is still current. Unless we get a serious investment in converting bazel rules for building the pip package into python commands we won't be able to do this.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
