### ISSUE TITLE
tf.keras.initializers.zeros causes model.save to fail, while tf.keras.initializers.Zeros() works great

### ISSUE THREAD

**Issue by fawazahmed0** [tensorflow/tensorflow#47054]
[Here](https://www.tensorflow.org/api_docs/python/tf/keras/initializers/Zeros) it's written that `tf.keras.initializers.zeros` is a shortcut for `tf.keras.initializers.Zeros()`.
If it is a shortcut, then both should work same

While saving the model, if I use `tf.keras.initializers.zeros` , model save failes, but using `tf.keras.initializers.Zeros()` works great.

Same issue raised by someone at [Stackoverflow](https://stackoverflow.com/questions/57154799/keras-model-saving-erroring-typeerror-get-config-missing-1-required-position) 

[Colab](https://colab.research.google.com/drive/1E0P-aBU9B7RO_QUtDrlRDPcOWqd6UfkD?usp=sharing#scrollTo=weBjeZAFJOP4)

**Comment by MaanasArora** [comment]
I'm new to open source, but to clarify, are you calling or referencing the function directly? If you reference the function object rather than initialize a new one (i.e. `tf.keras.initializers.zeros` instead of `tf.keras.initializers.zeros()`) without calling it, it will not work.

**Comment by Saduf2019** [comment]
@fawazahmed0 
Please provide with minimal stand alone indented code to replicate the issue reported or if possible share a colab gist with the error.

**Comment by fawazahmed0** [comment]
Well, I was going through, [timeseries forecasting tutorial](https://www.tensorflow.org/tutorials/structured_data/time_series) and when I tried to save the model it failed, I just had to change `tf.initializers.zeros` to `tf.initializers.zeros()` to make it working.

Here is the [colab](https://colab.research.google.com/drive/1E0P-aBU9B7RO_QUtDrlRDPcOWqd6UfkD?usp=sharing#scrollTo=weBjeZAFJOP4)

**Comment by mishc9** [comment]
Minimal code sample which reproduces the error ([colab](https://colab.research.google.com/drive/1ehWxx6PaDKP6nFMaI2Nf84O3-Xyv3-Sm?usp=sharing) link):

```python
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Reshape((-1, 784)),
    tf.keras.layers.Lambda(lambda x: tf.divide(tf.cast(x, tf.float32), 255.)),
    tf.keras.layers.Dense(256, activation='relu', bias_initializer=tf.initializers.zeros),
    tf.keras.layers.Dense(10, activation='softmax',)
])

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
model.compile('adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(x_train, y_train, validation_data=(x_test, y_test))
model.save('test')
```

exception:
```
TypeError                                 Traceback (most recent call last)
<...>

TypeError: get_config() missing 1 required positional argument: 'self'
```

The same code with tf.initializers.Zeros() would work fine `tf.initializers.Zeros()`, as @fawazahmed0 mentioned:

```python
import tensorflow as tf

model = tf.keras.Sequential([
    tf.keras.layers.Reshape((-1, 784)),
    tf.keras.layers.Lambda(lambda x: tf.divide(tf.cast(x, tf.float32), 255.)),
    tf.keras.layers.Dense(256, activation='relu', bias_initializer=tf.initializers.Zeros()),
    tf.keras.layers.Dense(10, activation='softmax',)
])

(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()
model.compile('adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history = model.fit(x_train, y_train, validation_data=(x_test, y_test))
model.save('test')
```

**Comment by mishc9** [comment]
I guess it could be simplified to the following gist ([colab](https://colab.research.google.com/drive/1jqONjLpZe1V6DYt9XulC9YFVifetUnFm?usp=sharing)):

```python
import tensorflow as tf

layer = tf.keras.layers.Dense(256, bias_initializer=tf.initializers.zeros)
layer.get_config()

Out: 
...
TypeError: get_config() missing 1 required positional argument: 'self'
```

But the following snippet works just fine:
```python
import tensorflow as tf

layer = tf.keras.layers.Dense(256, bias_initializer=tf.initializers.Zeros())
layer.get_config()
Out: 
{'activation': 'linear',
 'activity_regularizer': None,
 'bias_constraint': None,
 'bias_initializer': {'class_name': 'Zeros', 'config': {}},,
 ...
 'units': 256,
 'use_bias': True}
```

The same logic holds for other initializers. For example, `tf.initializers.he_uniform` will fail with the same error if `get_config` is called, but  `tf.initializers.HeUniform` will not.

I'm not sure if it is a problem or it's by design. But it's at least confusing because models trained with "`tf.initializers.zeros` - like" initializers use them properly except for the model serialization.

**Comment by MaanasArora** [comment]
@mishc9 To me, it appears that the `tf.initializers.zeros` shortcut function was intended to be _called_ rather than referenced as-is, i.e. it generates an object of the `tf.keras.initializers.Zeros` class. The class and the shortcut function are exported with the same `@keras_export` decorator in the source code. 

If you run the colab with `tf.initializers.zeros()` in place of `tf.initializers.zeros`, it works just fine.

**Comment by mishc9** [comment]
@MaanasArora you're right, it should be called provided to the layer constructor as `tf.initializers.zeros()`, not  `tf.initializers.zeros`. But the strange thing is that it still would work even in the later case ([colab](https://colab.research.google.com/drive/1R1K3olMovqhX7z7qW1AwbmhbK12WeEjq#scrollTo=In65cIrYpBst)).

I think this behaviour should be treated as an issue if the way to provide an initializer in the form of `tf.initializers.zeros` is allowed and it initializers weights the right way (because it's the main purpose of initializers). 

On the other hand, if this way to use initializers is not a 'regular' way to use them and trained model could fail, there should be a warning (at least, may be exception) during the model build/compile stage in my opinion. Not sure about backward compatibility - raise an exception could break some old code. It is 'correct' way to initialize weights & biases in the [standalone](https://github.com/keras-team/keras) `keras` API.

**Comment by MaanasArora** [comment]
@mishc9 Yes, it oddly works in both cases and it's inconsistent because `tf.initializers.zeros` only creates issues during serialization.

Further, I noticed that when I passed `tf.initializers.Zeros` instead of `tf.initializers.Zeros`, it _also_ worked, and it also had the same error as `tf.initializers.zeros` when serializing the model. So I think that the issue is not with the shortcut function but that the class itself can be used directly without initializing an instance but breaks when serializing the model.

Looking at the source, I suspect that the class was not intended to be passed to the layer constructor. I will review the source further to be sure.

**Comment by mishc9** [comment]
@MaanasArora that is interesting. I looked here and there in the source code too and still do not understand what's the reason of this issue :( 
[Function](https://github.com/tensorflow/tensorflow/blob/132437408620c947aaa43db31ce442a2b30dec12/tensorflow/python/keras/initializers/__init__.py#L150) `initializers.get` dispatches initializers:

```python 
@keras_export('keras.initializers.get')
def get(identifier):
  if identifier is None:
    return None
  if isinstance(identifier, dict):
    return deserialize(identifier)
  elif isinstance(identifier, six.string_types):
    identifier = str(identifier)
    return deserialize(identifier)
  elif callable(identifier):
    return identifier
  else:
    raise ValueError('Could not interpret initializer identifier: ' +
                     str(identifier))
```

It is invoked [here](https://github.com/tensorflow/tensorflow/blob/132437408620c947aaa43db31ce442a2b30dec12/tensorflow/python/keras/layers/core.py#L1164) in `__init__` of the layer and later, during 'build' stage, in `add_weight` [method](https://github.com/tensorflow/tensorflow/blob/132437408620c947aaa43db31ce442a2b30dec12/tensorflow/python/keras/engine/base_layer.py#L591). But it should return the identity of the provided object, because the `tf.initializers.zeros`/`tf.initializers.Zeros` is callable. And we couldn't use this object to initialize weights - it is just initializer class. So perhaps I missed something, probably would use debugger to localise the error.

**Comment by MaanasArora** [comment]
@mishc9 Note that the variable is instantiated in the `add_weight` method, so when `get_config` is called, the initializer attribute of the layer object is still a class. So, the problem is that the `get_config` method is not accessing the object that is created in `add_weight`, but rather the (class type) attribute itself.

I'm not sure if it fits the design or function very well, but a possible solution would be to check if an attribute is a class during serialization and instantiate it if it is. Should I create a pull request with these changes?

**Comment by mishc9** [comment]
@MaanasArora yes, exactly. In a layer object initializer is still a class, because getter called inside `add_weight` does not change the layer itself. I've tested locally following changes to the function `initialisers.get`: 

```python
@keras_export('keras.initializers.get')
def get(identifier):
  if identifier is None:
    return None
  if isinstance(identifier, dict):
    return deserialize(identifier)
  elif isinstance(identifier, six.string_types):
    identifier = str(identifier)
    return deserialize(identifier)
  elif callable(identifier):
    if inspect.isclass(identifier):
        identifier = identifier()
    return identifier
  else:
    raise ValueError('Could not interpret initializer identifier: ' +
                     str(identifier))
```
and it worked. This function transforms type object initializer to the object initializer, as the `getter` in `add_weight` method does. 

I thought of changes in the serialisation function too. But it seems this solution could affect other serialised objects: activations, layers, regularizers etc. It's hards to handle all this cases carefully.  But `get` function is only for initializers. There's a cons to the `initializers.get` change too: type of provided argument will be changed implicitly. But it is true for `string` and `dict` initializers now.

I would make a PR with this change, but have had a problem with tensorflow local unit testing 🤷‍♂️. Would send it without any additional unit tests covering this issue though. By the way, have you seen any additional intstructions how to dev & tests tensorflow on the local machine, except the contributing guidelines? Than would be great :)
