### ISSUE TITLE
ConverterError: <unknown>:0: error: loc(callsite(callsite("map/TensorArrayV2_1@__inference_call_func_18494" at "StatefulPartitionedCall@__inference_signature_wrapper_22648") at "StatefulPartitionedCall")): failed to legalize operation 'tf.TensorListReserve' that was explicitly marked illegal <unknown>:0: note: loc("StatefulPartitionedCall"): called from

### ISSUE THREAD

**Issue by karanjakhar** [tensorflow/tensorflow#47107]
[saved_model.zip](https://github.com/tensorflow/tensorflow/files/5970743/saved_model.zip)
I am trying to convert this model to tflite. But getting above error.

**Comment by karanjakhar** [comment]
Please help me. I have tried various things but nothing is worked.

**Comment by amahendrakar** [comment]
@karanjakhar,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code to build and convert the model and the dataset you are using. 

Also, please take a look at issue [#43495](https://github.com/tensorflow/tensorflow/issues/43495) with a similar error log and check if you are facing the same error. Thanks!

**Comment by karimnosseir** [comment]
@karanjakhar 
Please see the suggestion here
https://github.com/tensorflow/tensorflow/issues/43495#issuecomment-698049054


Also, please share complete snippet on how you're loading/converting the model

Thanks

**Comment by karanjakhar** [comment]
https://colab.research.google.com/drive/1X-ShZMLAGMLtPuEHI3YAOhWEyz-j_hyC?usp=sharing

This colab notebook has everything. Please have a look and please guide me.

**Comment by karanjakhar** [comment]
Any updates @amahendrakar @karimnosseir? Please help.

**Comment by karimnosseir** [comment]
@karanjakhar did you try fixing the shape for your model so it has 1D tensorList ? currently we only support 1D tensorlist

**Comment by karanjakhar** [comment]
Yes, I tried it. But it didn't worked. I have shared the colab notebook
above. Please check it, and please give it a try.

**Comment by karimnosseir** [comment]
The colab you shared doesn't fix the shape. The input 
```
input_tensor: uint8 Tensor, shape=(1, None, None, 3)
```

**Comment by amahendrakar** [comment]
@karanjakhar,
Any updates regarding this? Is this still an issue?

Could you please take a look at the above comment and let us know if you are facing the same error. Thanks!

**Comment by karanjakhar** [comment]
I have tried it but no luck. https://colab.research.google.com/drive/1X-ShZMLAGMLtPuEHI3YAOhWEyz-j_hyC?usp=sharing
you can check that in this colab.

**Comment by abattery** [comment]
@karanjakhar could you try conversion with the tf-nightly version? I have resolved the conversion issues related to TensorList recently by implementing Flex fallback.

**Comment by karanjakhar** [comment]
Okay, I try that, Thanks.

**Comment by amahendrakar** [comment]
@karanjakhar,
As mentioned by @abattery, I was able to run the code without any errors using the latest TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/c2ea23a0ac5cdf619d705f5a03961c68/copy-of-object_detection.ipynb). Thanks!

**Comment by karanjakhar** [comment]
It worked !! Thankyou so much @abattery @amahendrakar @karimnosseir

**Comment by nlm-yuh5** [comment]
@abattery @amahendrakar @karimnosseir I follow the gist above and converted the model `mask_rcnn_inception_resnet_v2_1024x1024_coco17_gpu-8` from TF2 model zoo with the following code:

`import tensorflow as tf
from tflite_support import metadata as _metadata

model_dir = r'C:\Users\yuh5\PycharmProjects\ConvertToTFLite\saved_model'
saved_model_dir = 'updated/saved_model'
model = tf.saved_model.load(model_dir)
concrete_func = model.signatures['serving_default']
concrete_func.inputs[0].set_shape([1, 1024, 1024, 3])
tf.saved_model.save(model, saved_model_dir)

converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir, signature_keys=['serving_default'])
converter.experimental_new_converter = True
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS, tf.lite.OpsSet.SELECT_TF_OPS]

tflite_model = converter.convert()

with tf.io.gfile.GFile('model.tflite', 'wb') as f:
    f.write(tflite_model)

# Used for adding metadata
populator = _metadata.MetadataPopulator.with_model_file("model.tflite")
populator.load_associated_files(["labels.txt"])
populator.populate()`

The code run though successfully, however, the input tensor of the .tflite model has the shape shown in the image below:
![Capture](https://user-images.githubusercontent.com/63370208/110393112-ffe9c880-8037-11eb-8397-b75c6710026f.PNG)

Is this correct? When I use this model to run inference on Android with the demo code for object detection I got the follow error:

`Caused by: java.lang.IllegalArgumentException: Cannot copy to a TensorFlowLite tensor (serving_default_input_tensor:0) with 3 bytes from a Java Buffer with 12582912 bytes.`

How should I modify the code to use maskRCNN model?

**Comment by abattery** [comment]
@nlm-yuh5 could you file a separate issue to make this thread simple? And could you share your converted model file as well?

**Comment by abattery** [comment]
@nlm-yuh5 could you file a separate issue to make this thread simple? And could you share your converted model file as well?

**Comment by nlm-yuh5** [comment]
sure

**Comment by VirVisha** [comment]
I have followed the exact steps mentioned in  issue #43495, except that i am using tensorflow 2.5 instead of tensorflow-nightly to build the classification problem
The entire set up has been done on Google Colab, I am able to do correctly identify the results. Subsequent to this i have built the model.tflite file as well

But when i do inference using Interpreter in Python on Colab, i get the error as 
ValueError                                Traceback (most recent call last)
<ipython-input-112-7ce8b910841d> in <module>()
----> 1 interpreter.set_tensor(input_index, resized_image)

/usr/local/lib/python3.7/dist-packages/tensorflow/lite/python/interpreter.py in set_tensor(self, tensor_index, value)
    570       ValueError: If the interpreter could not set the tensor.
    571     """
--> 572     self._interpreter.SetTensor(tensor_index, value)
    573 
    574   def resize_tensor_input(self, input_index, tensor_size, strict=False):

ValueError: Cannot set tensor: Dimension mismatch. Got 250 but expected 1 for dimension 1 of input 0.

**Comment by VirVisha** [comment]
This is where i have maintained the entire set up
https://colab.research.google.com/drive/1dpJ05nLl-stqu8lC9P4mwoIEbBmyxFBU#scrollTo=SiPTPXIbk-8L

**Comment by UcefMountacer** [comment]
Hello

I have a question.

How come the model downloaded from tf2 model zoo can be converted to int8, while using the same code on this model but trained on custom dataset fails.

I am really interested in knowing this. Thanks
