### ISSUE TITLE
Data cardinality is ambiguous:   x sizes: 60000   y sizes: 10000 Please provide data which shares the same first dimension.

### ISSUE THREAD

**Issue by saikrishna14343** [tensorflow/tensorflow#47105]
complete code here  [http://localhost:8888/notebooks/Desktop/minor%20proj/Untitled-Copy1.ipynb](url) 

working on mnist data set for handwriten recognition

**Comment by saikrishna14343** [comment]
please someone help me out .. 
waiting eagerly

**Comment by saikrishna14343** [comment]
its actually the bug which i am getting

**Comment by amahendrakar** [comment]
@saikrishna14343,
In order to reproduce the issue reported here, could you please provide the TensorFlow version, the complete code and the dataset you are using. 

Also, please take a look at [this comment](https://stackoverflow.com/a/62606245) from a similar StackOverflow query and check if helps.

Thanks!
