### ISSUE TITLE
Add 3.7 to list of default compute capabilities

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#4712]
The Tesla K80 has a compute capabilities of 3.7. These are the cards in [AWS' new `p2` GPU offering](https://aws.amazon.com/blogs/aws/new-p2-instance-type-for-amazon-ec2-up-to-16-gpus/) and in [Azure's GPU offering](https://azure.microsoft.com/en-us/blog/azure-n-series-preview-availability/) which means that usage of these cards will be quite widespread.

Given that there are some difference between CC 3.5 and 3.7, it would be ideal to have builds that are able to use the newer features / settings in 3.7.

**Comment by concretevitamin** [comment]
@zheng-xq: WDYT?

**Comment by zheng-xq** [comment]
Adding a default GPU config has significant impact on build time. Since 3.5 and 3.7 are largely compatible, it is better to keep the default config number low. Unless we see a non-trivial change in performance, we'd prefer to leave the current setting unchanged. Power users can still use configure to choose their favorite compute capabilities.

**Comment by cancan101** [comment]
How hard would it be to generate wheels for different CCs?

**Comment by gunan** [comment]
Without going into specifics, I can say that each new configuration to maintain is an added burden across the board, in terms of build, release and maintenance.
Therefore, in terms of released packages we would rather create packages that work for most.
If a user needs a specific build that would perform best on their setup, they likely also need to add other compiler flags based on which CPU they are using, such as "-mavx". 
Rather than supporting a cross product of different CPU and GPU configurations, we prefer asking users to build their images, and provide support for build issues.
