### ISSUE TITLE
How to close parameter server with python?

### ISSUE THREAD

**Issue by LiamHe** [tensorflow/tensorflow#4713]
In the TensorFlow documentation, the tf.train.Server.join() will block forever, but I would like to close it after training. Are there any possible solutions for it?

Thanks.

**Comment by hholst80** [comment]
Maybe you can create a Supervisor which you then monitor from a separate thread? If you get a should_stop you exit the entire process. I have not tried it myself but could be worth trying.

**Comment by jart** [comment]
This should be an easy question for @mrry to answer.

**Comment by mrry** [comment]
There's no built-in API for shutting down a TensorFlow server remotely; the assumption is that whatever mechanism (e.g. a cluster manager) you used to start the processes would also kill them after the job completes.

If you're feeling adventurous, you could try using TensorFlow coordination mechanisms, like a `tf.FIFOQueue` to signal when training is complete. The basic idea would be to (1) create a *shared* queue on one of the PS tasks; (2) on each of the PS tasks, run a dequeue op on that queue instead of calling `server.join(); (3) at the end of training enqueue_many N elements into the queue (where N is the number of parameter servers). If you did that, the PS tasks would all unblock when training was done, and exit.

**Comment by jart** [comment]
This looks like a satisfactory answer to me, so I'm going to close this out. Let me know if you want me to reopen this @LiamHe.

**Comment by coolsurf** [comment]
Would you reopen this issue, please?  In our cluster setup (LSF+MPI shared by many different groups), it requires extra efforts to monitor a TF job in order to stop it after training.  A simple wait-then-close method for parameter server would be much appreciated because it increases ease-of-use a lot, especially in a shared cluster where parameter servers should be closed after every single job.  Thank you.

For your reference, this issue is brought up again here: https://github.com/tensorflow/ecosystem/issues/19.

**Comment by yaroslavvb** [comment]
There's a work-around -- instead of `server.join()` have your parameter servers do `sess.run(queue.dequeue)` `k` times if there are `k` workers. Then each worker does an `enqueue` at the end of it's work. Here's a full example, search for `create_done_queues` [here]( https://gist.github.com/yaroslavvb/ea1b1bae0a75c4aae593df7eca72d9ca). An alternative solution was started in this pr -- https://github.com/tensorflow/tensorflow/pull/6185

**Comment by jhseu** [comment]
Hmm, that's a nice option. @martinwicke FYI, possibly worthwhile doing in tf.learn by default?

**Comment by alextp** [comment]
@jhseu this is not a reasonable default since workers can in some settings restart unpredictably during training

**Comment by coolsurf** [comment]
@alextp @jhseu How about adding it as an option, disabled by default?  The user may turn it on if desired.

**Comment by hustcat** [comment]
Stop ps server gracefully is a requirement when run distributed training with [kubernetes batch job](https://kubernetes.io/docs/user-guide/jobs/). Anyone can write a detail demo base on [mnist_replica](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/dist_test/python/mnist_replica.py)? @mrry @jart

**Comment by yaroslavvb** [comment]
@hustcat http://stackoverflow.com/questions/39810356/shut-down-server-in-tensorflow/40186129#40186129

**Comment by hustcat** [comment]
I write a demo for MNIST_data, and it seems run OK. See [dist_fifo](https://github.com/hustcat/tensorflow_examples/blob/master/mnist_distributed/dist_fifo.py).
