### ISSUE TITLE
TF repo preprocessing for EfficientNet differs from that contained in Keras repo.

### ISSUE THREAD

**Issue by albertotonon** [tensorflow/tensorflow#47182]
Hi all,

I've noticed that the code for EfficientNet image preprocessing contained [here](https://github.com/keras-team/keras-applications/blob/master/keras_applications/efficientnet.py#L530) is different from the one contained [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/efficientnet.py#L740).
In the first link (from keras-team) standard ImageNet preprocessing is performed, while in the second link (from tensorflow) nothing is done.

Which version of the code should I trust for reusing the EfficientNet checkpoints publicly released by Google?

Thanks for your time!

**Comment by rmothukuru** [comment]
@albertotonon,
We can't say that nothing is done in the [TF Keras (second) link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/efficientnet.py#L740) because it is wrapped with `@keras_export('keras.applications.efficientnet.preprocess_input')`.

It is recommended to use PreProcess function of [TF Keras](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/efficientnet.py#L740) over [Keras-Teams Applications](https://github.com/keras-team/keras-applications/blob/master/keras_applications/efficientnet.py#L530) because [TF Keras Applications Code](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/applications/efficientnet.py#L740) is actively/recently updated.

**Comment by albertotonon** [comment]
Thanks a lot, @rmothukuru ! This completely clarifies my doubt, so, i'll close the ticket.
Keep up the good work, people :)
