### ISSUE TITLE
Bidirection Masked LSTM breaks in graph mode.

### ISSUE THREAD

**Issue by cfrancesco** [tensorflow/tensorflow#47192]
tf version: 2.4.1
python: 3.6

Using the Bidirectional layer is returning the following error in graph mode
```
ValueError: Shape must be rank 1 but is rank 2 for '{{node cond/ReverseSequence}} = ReverseSequence[T=DT_FLOAT, Tlen=DT_INT32, batch_dim=0, seq_dim=1](cond/ReverseSequence/inputs, cond/Sum)' with input shapes: [?,?,1], [?,1].
```
To reproduce:
```
import tensorflow as tf


class Bad(tf.keras.models.Model):
    def __init__(self):
        super(Bad, self).__init__()
        # self.rec_net = tf.keras.layers.LSTM(10)
        self.rec_net = tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(10))
    
    @tf.function(input_signature=
                 [tf.TensorSpec(shape=(None, None, 1), dtype=tf.float32),
                  tf.TensorSpec(shape=(None, None, 1), dtype=tf.int32), ])
    def call(self, x, mask):
        return self.rec_net(x, mask=tf.cast(mask, tf.bool), training=False)
        # return self.rec_net(x, training=False)


if __name__ == '__main__':
    inp = tf.random.uniform((3, 4, 1))
    mask = tf.convert_to_tensor([[[1], [1], [1], [1]],
                                 [[1], [1], [1], [0]],
                                 [[1], [1], [0], [0]]])
    
    b = Bad()
    out = b(inp, mask)
```

It works if any of tf.function, bidirectional or mask is removed.
Also works if a GRU is used.

**Comment by amahendrakar** [comment]
Was able to reproduce the issue with TF v2.3, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/b54b47a85946b967a2c5dd5388ed2886/47192.ipynb). Thanks!

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue with TF v2.5 .Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/293a6df1b5e439ec710ec76370eae413/untitled124.ipynb?authuser=1) ..Thanks !

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tf-nightly 2.10.0-dev20220719. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/6ad9e07126fbccd5c1a53bb474ebaf5c/untitled439.ipynb). Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
