### ISSUE TITLE
RE: Some questions

### ISSUE THREAD

**Issue by Joe23232** [tensorflow/tensorflow#47201]
Hi I have some questions in regards to this project:

1. How does this differ to OpenCV?
2. Am I able to also code in C++?
3. Does it support AMD OpenCL?

**Comment by addy1997** [comment]
@Joe23232 

1. Tensorflow is a framework used (with Keras) to perform ML-related tasks. OpenCV is primarily used for Computer Vision and Image processing related tasks. 
2. This library is written in C++ and python both. 
3. Read this [Link](https://missinglink.ai/guides/tensorflow/tensorflow-support-opencl/)

**Comment by Joe23232** [comment]
Oh ok thanks mate

**Comment by Saduf2019** [comment]
@Joe23232 
1.OpenCv does not have automatic differentiation engine and many more differences, these are largely different in their own scope.
2.Both frameworks have programmable interface in c++
3.Please refer to this [link](https://community.amd.com/t5/hsa/tensorflow-with-amd-gpu/td-p/199925).

This question is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow) since it is not a bug or feature request. There is also a larger community that reads questions there, please move this to close status and open an issue on stackoverflow.

**Comment by mihaimaruseac** [comment]
Closing as this should be asked on Stack Overflow.
