### ISSUE TITLE
Training with MultiWorkerMirroredStrategy for machines with heterogeneous number of GPUs

### ISSUE THREAD

**Issue by unfazing** [tensorflow/tensorflow#47203]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): **yes**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): **Ubuntu 20.04**
- TensorFlow installed from (source or binary): **From docker image tensorflow:latest-gpu**
- TensorFlow version (use command below): **2.4.1**
- Python version: **3.6.9**
- CUDA/cuDNN version: **CUDA 11.2**
- GPU model and memory: **chief (2x Quadro P2000), worker (4x RTX 2080)** 

**Describe the current behavior**
With the [keras tutorial](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras), I made the relevant changes to my own model. 

I encounter the following error when the worker runs the main.py and starts the training:

> tensorflow.python.framework.errors_impl.InternalError: Collective Op has group_size 8 and group_key 1 but that group has size 4
> Encountered` when executing an operation using EagerExecutor. This error cancels all future operations and poisons their output tensors.

However, the code runs the training fine when I limit the number of CUDA visible GPUs for each machine to 2 (such that worker and chief have the same number of GPUs).

**Describe the expected behavior**
I want to be able to utilise all 6 GPUs for training.

**Standalone code to reproduce the issue**
docker command for chief and worker (change index to 1 for worker):
```
docker run --gpus all -it -p 12345:12345 -v /home:/home tensorflow/tensorflow:latest-gpu
export TF_CONFIG='{"cluster": {"worker": ["x.x.x.x:12345", "x.x.x.x:12345"]}, "task": {"index": 0, "type": "worker"}}'
python main.py
```

**Other info / logs**

**Comment by nikitamaia** [comment]
Hi @unfazing, just my thoughts on this: in `MultiWorkerMirroredStrategy` the forwards and backwards passes are computed on each replica and the gradients synchronized across all GPUs on a machine and all machines in the cluster.  So if you have a machine that has 4 GPUs, it's going to complete the forward/backwards passes on the data in a particular step faster than the machine with 2 GPUs (assuming your data is evenly distributed across the machines). Thus, the machine with 4 GPUs will be sitting around waiting for the 2 GPU machine before it can start the next step and you won't actually get a performance improvement.

There's probably a way to make this scenario work by sending more data to the machine with 4 GPUs, but I'm not entirely sure how that functionality would work. I'll mark this as a feature request for now.

**Comment by unfazing** [comment]
Okay, so the error is by design. In the situation that 4 weaker GPUs end up having the same computational power as 2 more powerful GPUs, is there a way to run the training without encountering the error?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
