### ISSUE TITLE
Make Image Summary in tensorboard more dynamic

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#4721]
The image summary in Tensorboard is very nice, it's the most static tab on Tensorboard.
For example, when I am doing a visual test of my auto-encoder, for example MNIST, I see this:
![image](https://cloud.githubusercontent.com/assets/7721540/19021497/5d761600-88c3-11e6-90c8-85f8049f0a14.png)

Then I wait a few minutes, and I refresh and it shows:
![image](https://cloud.githubusercontent.com/assets/7721540/19021501/7187f2d0-88c3-11e6-88f1-8374dbd48356.png)

So it works. But I would like to be able to somehow review the progress, other than my current F5-stategy.
I recon all image summaries are saved inside, but I cannot obtain them through Tensorboard.

**Comment by danmane** [comment]
TensorBoard does store many images per tag, but as you point out the UI only surfaces the most recent one.

This could be improved by adding some UI for loading older images in the sequence - maybe a slider on the left that changes which image gets loaded by each image-loader, e.g. if the slider is set to the far left it loads the earliest image, if it is set to far right it loads the latest image.

I don't think the TensorBoard team will prioritize this right now, but we would gladly advise on a pull request if you (or anyone else) wants to add this feature.

Also,  you can use the reload icon in the top-left rather than F5.

**Comment by TimZaman** [comment]
F5 and reload does not seem to be very smooth though - probably a caching
issue where flushed data appears (with reloading) only after some time.

Can you give some pointers where to start? i might look into this one over
the weekend.

**Comment by dandelionmane** [comment]
We just added a new feature to the image dashboard that lets you load older images by dragging a slider around. It should be in the next major release of TensorFlow after 1.0. Closing the issue since work is complete (although it will be a little while until the feature is available)

**Comment by ankitp94** [comment]
Has this been released yet?
Currently, I'm using '1.0.0'

**Comment by ankitp94** [comment]
Update: This feature has been released in TensorFlow 1.1.0-rc0 (released 5 days ago).

Thanks to all contributors.

**Comment by blake-varden** [comment]
I installed 1.1.0-rc1, yet don't see any slider in the image view.  Is there something specific needed to enable it?
