### ISSUE TITLE
ValueError: No gradients provided for any variable: ['conv1_conv/kernel:0', 'conv1_conv/bias:0', 'conv2_block1_preact_bn/gamma:0', 'conv2_block1_preact_bn/beta:0', 'conv2_block1_1_conv/kernel:0',

### ISSUE THREAD

**Issue by kitenko** [tensorflow/tensorflow#47214]
I cannot understand how I can solve this issue.  I would be very grateful for help!  

https://colab.research.google.com/drive/1ZFrfT7BPV7S75WD0082VTswNkdYqYSWf?usp=sharing

**Comment by amahendrakar** [comment]
@kitenko,
On running the code, the `class_names` variable prints an empty list. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f8164d9bf4e5f22fab27a90649c248ec/47214.ipynb).

Could you please provide the dataset and all the necessary files required to run the code, so that we can reproduce the issue on our end. Thanks!
