### ISSUE TITLE
ParameterServerStrategy supporting GPU workers

### ISSUE THREAD

**Issue by pawel-polyai** [tensorflow/tensorflow#47239]
**Describe the feature and the current behavior/state.**
Hi TF team,

we can train very efficiently our models thanks to the PS strategy using tf 1.15. 
We are moving our codebase to 2.3 but it looks like you don't support GPU workers in the PS strategy right now.
Do you have any (even tentative) dates for shipping that feature?

**Will this change the current api? How?**

**Who will benefit from this feature?**

**Any Other info.**

**Comment by amahendrakar** [comment]
@pawel-polyai,
Please take a look at the [documentation](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/ParameterServerStrategy) and [tutorial](https://www.tensorflow.org/tutorials/distribute/parameter_server_training) for `ParameterServerStrategy` using TensorFlow 2.x and check if it helps. Thanks!

**Comment by nikitamaia** [comment]
Hi @pawel-polyai, GPU support is actively being worked on right now. I unfortunately can't provide a date, but I'll keep this thread updated.

**Comment by tilakrayal** [comment]
@pawel-polyai,
[tf.distribute.experimental.ParameterServerStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/ParameterServerStrategy) and [tf.distribute.MultiWorkerMirroredStrategy](https://www.tensorflow.org/api_docs/python/tf/distribute/MultiWorkerMirroredStrategy), both are designed for CPU/GPU training with multiple workers.

In order to use GPUs for training, allocate GPUs visible to each worker. **ParameterServerStrategy** will use all the available GPUs on each worker, with the restriction that all workers should have the same number of GPUs available.

Also please take a look at the official doc [link](https://www.tensorflow.org/api_docs/python/tf/distribute/experimental/ParameterServerStrategy) and the Parameter [server](https://www.tensorflow.org/tutorials/distribute/parameter_server_training) training  for the reference.

https://www.tensorflow.org/guide/migrate/multi_worker_cpu_gpu_training

![image](https://user-images.githubusercontent.com/81610181/219328889-de139d13-0a19-43cc-aff0-fc74cda40aeb.png)

**Comment by tilakrayal** [comment]
Closing this as stale. Please reopen if this is still a valid request.
