### ISSUE TITLE
TensorFlow lite support for snapdragon 888/875 dsp

### ISSUE THREAD

**Issue by shuki-k** [tensorflow/tensorflow#47246]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- Mobile device Snapdragon 875/888
- TensorFlow version 2.4.0:

Problem description:

when running my tesorflow lite app that need to use the hexagon dsp delegate.
I get the following error:

"WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
INFO: Hexagon Delegate is not supported"

from https://www.tensorflow.org/lite/performance/hexagon_delegate I can't see that you support the snapdragon version I'm using 875/888 , is the Hexagon delegate doesn't support this new snapdragon device or am I'm missing something ?
When will it be supported ?

Thanks
Shuki

**Comment by karimnosseir** [comment]
Hi @shuki-k 
Sadly this is not possible.
These new chips uses a newer version of HVX that is different than what Hexagon delegate supports.

**Comment by shuki-k** [comment]
when will that be the new snapdragon 888 be supported by TFlite ? is it in the roadmap

**Comment by karimnosseir** [comment]
Hi @shuki-k,
Sadly no plans, as this is not totally in our hands.
The new hardware is completely new and Qualcomm is not planning to update the API which is used by the Hexagon Delegate. 
We are checking with Qualcomm for other options for this new hardware.

Thanks

**Comment by alexanderfrey** [comment]
Facing same issue here with Xiaomi MI11.

**Comment by karimnosseir** [comment]
Hi @alexanderfrey 
As mentioned earlier, QC new hardware is using new chip and API and it doesn't even use Hexagon NN, that's why the delegate doesn't work (Sorry, i wish i could do something to help here :( )

For NNAPI case, it's different than Hexagon delegate, and QC provides different drivers for android.

**Comment by anandravi24** [comment]
Hey @karimnosseir , is there any update on this issue. Could we expect support for SD 888 DSP anytime soon?

**Comment by karimnosseir** [comment]
Hey @anandravi24 Sorry same reply, the new chip doesn't leverage Hexagon NN API. I wish i could help

**Comment by yx-chan131** [comment]
@karimnosseir Hi, I am trying to benchmark int8 quant model on Snapdragon 7 Gen 1 DSP. 

This error occurs:
"WARNING: Failed to fetch Hexagon NN version. This might be because you're using incompatible versions of libhexagon_interface and libhexagon_nn_skel. You must use compatible versions. Refer to Tensorflow Lite Hexagon Delegate Guide.
INFO: Hexagon Delegate is not supported"

Is this chip not supported as well? Thanks.
