### ISSUE TITLE
tensorflow is shown on listing packages using pip list or conda list but you can't import in Python

### ISSUE THREAD

**Issue by nayrr25** [tensorflow/tensorflow#47253]
Same issue happened even with using pip install https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-2.3.0-cp38-cp38-macosx_10_14_x86_64.whl

as mentioned in https://www.tensorflow.org/install/pip#package-location

tensorflow is shown on listing packages using pip list or conda list but you can't import in Python

When I try to import TensorFlow the kernel restarting and then I have the message 

[SpyderKernelApp] WARNING | No such comm: 7843964a725e11eb900a1e29c0108246
[SpyderKernelApp] WARNING | No such comm: 81501ed4725e11eb900a1e29c0108246

**Comment by amahendrakar** [comment]
@nayrr25,
In order to expedite the trouble-shooting process, could you please provide the following details

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

and the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by amahendrakar** [comment]
Also, looking at the messages it seems like the issue is with Spyder IDE. To confirm if TensorFlow is successfully installed please run the below code snippet. 
```
import tensorflow as tf
print(tf.reduce_sum(tf.random.normal([1000, 1000])))
```
Thanks!

**Comment by nayrr25** [comment]
When I run that code:

import tensorflow as tf
print(tf.reduce_sum(tf.random.normal([1000, 1000])))

I receive that message:


Kernel died, restarting
Restarting kernel... 

[SpyderKernelApp] WARNING | No such comm: 7843964a725e11eb900a1e29c0108246
[SpyderKernelApp] WARNING | No such comm: 81501ed4725e11eb900a1e29c0108246
[SpyderKernelApp] WARNING | No such comm: e012dd08725e11eb900a1e29c0108246
[SpyderKernelApp] WARNING | No such comm: b8bfbb76726411eb900a1e29c0108246
[SpyderKernelApp] WARNING | No such comm: f1fb85aa726411eb900a1e29c0108246
[SpyderKernelApp] WARNING | No such comm: 24454e6e726b11eb900a1e29c0108246
[SpyderKernelApp] WARNING | No such comm: d8eaf940726b11eb900a1e29c0108246

**Comment by amahendrakar** [comment]
@nayrr25,
Please try importing TensorFlow in the macOS terminal i.e. outside the conda environment and check if you are facing the same issue. Thanks!
