### ISSUE TITLE
LinearOperatorKronecker for SparseTensors

### ISSUE THREAD

**Issue by stefanmeili** [tensorflow/tensorflow#47270]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tensorflow 2.2(gpu) & 2.3, linux64, anaconda
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently there is no kronecker product operator that works on sparse tensors. Calling tf.linalg.LinearOperatorKronecker on sparse tensors raises `AttributeError: 'SparseTensor' object has no attribute 'is_non_singular'`

**Will this change the current api? How?**
Possibly?

LinearOperatorKronecker checks attributes: `.is_non_singular`, `.is_self_adjoint`, and `.is_self_adjoint`, and then calls `.extend` during initialization, and looks for `.name`. SparseTensor doesn't have any of these. It's probably easier to build a kronecker product operator specifically for sparse tensors.

**Who will benefit with this feature?**
Kronecker products on sparse tensors can be useful in building coefficient matrices for finite difference simulations. I could see wide application building grey box models for use in physics, industrial engineering, aerospace, weather, and so on. Pretty much anyone looking to solve PDEs on a regular grid.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
