### ISSUE TITLE
tf.convert_to_tensor crashes(segfault) 

### ISSUE THREAD

**Issue by DNXie** [tensorflow/tensorflow#47274]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below):2.1.0
- Python version:3.7.6
- Bazel version (if compiling from source):N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version:N/A
- GPU model and memory:N/A

**Describe the current behavior**
`tf.convert_to_tensor` crashes(segfault) when integer `dtype` passed

**Describe the expected behavior**
Expect graceful exception messages instead of crash

**Standalone code to reproduce the issue**
~~~python
import tensorflow as tf
import numpy as np
tf.convert_to_tensor(value=np.array((10)), dtype=20)
~~~

Output:
~~~python
Segmentation fault (core dumped)
~~~

**Comment by ravikyram** [comment]
Was able to reproduce the issue with TF v2.1, TF v2.4 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/ravikyram/a7eed77cae1bf42f7395590f6020a2f2/untitled677.ipynb). Thanks!

**Comment by agrawalakshay68** [comment]
@DNXie
 ## Error  line : tf.convert_to_tensor(value=np.array((10)), dtype=20)
### The error is in the dtype argument of convert_to_tensor which expects specific codes instead of numeric integers, if you want to convert your array into integer tensor you shall pass dtype =tf.int32 for 32bit integers or dtype  = tf.int64 for 64 bit integers instead of 20. Also, if you want to convert it into float you may try dtype = tf.float32 or tf.float64 . You may look code snippet
![image](https://user-images.githubusercontent.com/58474875/108689057-a2755800-751e-11eb-98ac-496e10a85460.png)

**Comment by sushreebarsa** [comment]
Was able to reproduce the issue with TF 2.6.0-dev20210526.Please check the gist [here](https://colab.research.google.com/gist/sushreebarsa/58ff320751a93200f6a4e91b351e3ba6/untitled149.ipynb?authuser=1)..Thanks !

**Comment by ymodak** [comment]
With TF 2.5 and above the crash is avoided by raising error with appropriate message.
```python
ValueError: Failed to convert a NumPy array to a Tensor (Unexpected numpy data type).
```
