### ISSUE TITLE
tf.errors.UnknownError should include __cause__

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#47391]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

When a [`tf.errors.UnknownError`](https://www.tensorflow.org/api_docs/python/tf/errors/UnknownError) is raised, the `exception.__cause__` is not set (it is `None`), so if someone wants to find the underlying error, the best they can do is trying to infer it through the `exception.message` attribute, which is suboptimal at best.

`exception.__cause__` should be set to the chained exception when known. See https://docs.python.org/3/library/exceptions.html.

**Will this change the current api? How?**

It will change the `tf.errors.UnknownError` behaviour to include more information.

**Who will benefit with this feature?**

Everyone who wants more control over `UnknownError`. For example, it is currently not possible for me to detect that the `UnknownError` is caused due to a `PIL.UnidentifiedImageError` unless I find the string in the `message`.

**Any Other info.**

Code causing the `UnknownError` that prompted the request:

```python
def my_generator(img):
    img = Image.open(io.BytesIO(img))  # <- here's the `PIL.UnidentifiedImageError`
    img = tf.image.convert_image_dtype(img, tf.float32)
    yield img, tf.constant([[]], dtype=tf.float32), tf.constant([], dtype=tf.int32)

ds = tf.data.Dataset.from_generator(lambda: my_generator((image_bytes))
# ...trying to use ds...
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
