### ISSUE TITLE
Disable unroll batch matmul pass

### ISSUE THREAD

**Issue by WindQAQ** [tensorflow/tensorflow#47425]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Colab
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): nightly

### 2. Code

https://colab.research.google.com/drive/1VxiMyDs5B_Oxcg29EmPSu9qgvPejCWqx?usp=sharing

### 3. Failure after conversion

It's all successful. But with unrolling (large batch dim), the model will be significant larger, and probably decrease the performance. I suppose it's just a workaround when tflite does not have batch matmul kernel, but we have it now.

**Comment by abattery** [comment]
Thanks @WindQAQ  for filing a feature request.

**Comment by abattery** [comment]
@talumbau could you take a look at this?

**Comment by abattery** [comment]
Many delegates don't support the BatchMatMul op, so we default to unrolling. We are working on a more user friendly approach here, but for now, you could manually set the flag here for your individual case:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/lite/common/tfl_pass_config.h#L36

**Comment by WindQAQ** [comment]
Got it! Thanks for the response 😄

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
