### ISSUE TITLE
Cannot import name 'boosted_trees_test' from 'tensorflow_estimator.python.estimator.canned' 

### ISSUE THREAD

**Issue by samanemami** [tensorflow/tensorflow#47430]
When I am trying to import boosted_trees_test, I face the following error:

`cannot import name 'boosted_trees_test' from 'tensorflow_estimator.python.estimator.canned' (C:\Users\user\AppData\Local\Programs\Python\Python38\lib\site-packages\tensorflow_estimator\python\estimator\canned\__init__.py)
`

Also, I could not find the boosted_trees_test in the latest TF package (2.4)

**Comment by amahendrakar** [comment]
@samanemami,
Looks like you're trying to run code meant for TF 1.x on TF 2.4. The last TF version with a reference to [boosted_trees_test.py](https://github.com/tensorflow/tensorflow/blob/v1.12.3/tensorflow/python/estimator/canned/boosted_trees_test.py) was v1.12.3

Could you please provide the Python script/notebook you're running, so that we can look into this issue? Thanks!

**Comment by samanemami** [comment]
Thank you for the reply

The code is as follows, which I tried to import a model:

`from tensorflow_estimator.python.estimator.canned import boosted_trees_test
model = boosted_trees_test`

**Comment by samanemami** [comment]
`tensorflow.__version__
'2.4.1'`

**Comment by samanemami** [comment]
@amahendrakar Have you checked the issue?

**Comment by samanemami** [comment]
@ymodak
I have installed TF 1.15.0, but the problem has not solved. Got the same error.

Please note that I have downloaded **different versions of TF** and consequently installed **different versions of python** which is **costly**. 
Would you please indicate the correct version of TF which actually works, please?

**Comment by ymodak** [comment]
@samanemami  Importing `boosted_trees_test` test script fails since these files (*_test.py) are not exposed to your python session.
Simply importing boosted_trees module should work with TF 2.4 version.
`from tensorflow_estimator.python.estimator.canned import boosted_trees`
For running test files you need to try [Bazel command](from tensorflow_estimator.python.estimator.canned import boosted_trees).
