### ISSUE TITLE
custom op on gpu/dsp

### ISSUE THREAD

**Issue by xmy19029** [tensorflow/tensorflow#47448]
The official website just tell me how to custom ops on CPU, i wonder if there‘s something could teach me how to do this on GPU/DSP.
And we need  **_“libhexagon_nn_skel.*.so"_** to use DSP. If i custom ops on hexagon delegate, do i have to compile new  ”.so“ through hexagon SDK ,or just build AAR and use the old .so files?
Thanks a lot!!!😭😭😭

**Comment by abattery** [comment]
@karimnosseir could you take a look at this?

**Comment by karimnosseir** [comment]
Hi @1173710201 
There is a way to support user defined operation on hexagon DSP, but it is experimental and not supported by Qualcomm, so we didn't expose it.

If you can share details on your usage, we can look if we can plan adding this.

Thanks

**Comment by 1173710201** [comment]
@karimnosseir  Thanks for your help! Actually this is my graduation project, so there's no specific usage now. My teacher asked me to figure out whether the tflite supported custom ops on GPU/DSP.

**Comment by 1173710201** [comment]
@karimnosseir  Thanks for your help! Actually this is my graduation project, so there's no specific usage now. My teacher asked me to figure out whether the tflite supported custom ops on GPU/DSP.

**Comment by karimnosseir** [comment]
Hi @xmy19029 
For DSP no supported API for doing this as mentioned.

For GPU, added @impjdi to help answer this.

Thanks

**Comment by impjdi** [comment]
For GPU, it's possible to use custom ops, but you need a lot of plumbing.  There is no clean API that lets you do that currently.

1. You first need to create a model that has the custom op.  I unfortunately don't know how to do that.  https://www.tensorflow.org/lite/guide/ops_custom is probably the best place for entry and if you have questions,  @karimnosseir  is probably at a better position to answer that.
2. Once you have a model with custom ops, you need to update the op resolver to recognize the op.  See MutableOpResolver.
3. Then, you need to update GPU's model_builder.cc to recognize your new custom op.
4. Finally, you have to write GPU shader code (depending on whether you use OpenGL/OpenCL/Vulkan) that implements the kernel.

These are going to be quite a lot of work, if you're new to the codebase or GPU programming.

**Comment by xinjin95** [comment]
Have you @xmy19029 tried to add custom op for GPU?

@impjdi I have a followup question. I am running a model on Android with GPU delegate. The `tf.gather` op in my model is not supported. If I add custom op for it in Android GPU delegate, should I follow the same steps as you suggested above?

**Comment by tilakrayal** [comment]
@xmy19029,
Primarily please try to create the model that has the Custom Op. Using custom operators consists of four steps.

- [Create a TensorFlow Model.](https://www.tensorflow.org/lite/guide/ops_custom#create_a_tensorflow_model) Make sure the Saved Model (or Graph Def) refers to the correctly named TensorFlow Lite operator.

-  [Convert to a TensorFlow Lite Model.](https://www.tensorflow.org/lite/guide/ops_custom#convert_to_a_tensorflow_lite_model) Make sure you set the right TensorFlow Lite converter attribute in order to successfully convert the model.

-  [Create and register the operator.](https://www.tensorflow.org/lite/guide/ops_custom#create_and_register_the_operator) This is so that the TensorFlow Lite runtime knows how to map your operator and parameters in your graph to executable C/C++ code.

- [Test and profile your operator.](https://www.tensorflow.org/lite/guide/ops_custom#test_and_profile_your_operator) If you wish to test just your custom operator, it is best to create a model with just your custom operator and use the [benchmark_model](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/benchmark/benchmark_model.cc) program.

https://www.tensorflow.org/lite/guide/ops_custom

Also please take a look at this official doc [link](https://www.tensorflow.org/lite/performance/gpu) for the reference. Thank you!
