### ISSUE TITLE
Update TF with CUDA 11.2 and cuDNN 8.1

### ISSUE THREAD

**Issue by goldiegadde** [tensorflow/tensorflow#47568]
Update TF with CUDA 11.2 and cuDNN 8.1

**Comment by awaisbajwaml** [comment]
May I know if we have support for CUDA 11.2 and cuDnn 8.* - please see this [issue  ](https://github.com/tensorflow/tensorflow/issues/47669)

**Comment by pkanwar23** [comment]
Support for Ubuntu has landed in the nightlies (for CUDA 11.2 and cuDNN 8.1).

**Comment by ALIANS-PRODUCTIONS** [comment]
Would do you think it will be possible for Windows 10 as well?

**Comment by pkanwar23** [comment]
Windows support has landed too.

**Comment by ALIANS-PRODUCTIONS** [comment]
I tried installing on UBUNTU 20.04 : Cuda 11.2 and the latest Cudnn 8.1.1, python 3.7, Anaconda.
I installed tf-nightly-gpu 2.5.0.dev20210320, and tf-nightly 2.5.0.dev20210320

and got the following crash on import tensorflow as tf: Illegal instruction (core dumped)

My cpu has AVX but not AVX2 :  There was an issue back end of last year which was fixed by Jan regarding tf nightly binaries accidently starting to use AVX2 by mistake. It seemed this issue has now come back??

I will try Windows 10 later on. 

https://github.com/tensorflow/tensorflow/issues/45866
