### ISSUE TITLE
TFLite micro hard fault when using tf.reduce_sum

### ISSUE THREAD

**Issue by oholimoli** [tensorflow/tensorflow#47569]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): pip install tensorflow
- Tensorflow version (commit SHA if source): 2.4.1
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Arm M4 with Zephyr

**Describe the problem**

I'm trying to export my TF-model with one simple custom layer to TFLite micro and get hardware faults when running it.

I would like to implement a layer that performs this calculation:

```python
def call(self, inputs):
    x = (tf.reduce_sum(tf.math.squared_difference(inputs['vector'],inputs['vector_old'])))
    x = tf.reshape(x,(1,1))
    return x
```
`vector` and `vector_old` have both the shape (1,4) and are float tensors and my output should have the shape (1,1)

**Sequence of commands/steps when I ran into the problem**

Because I get a hard fault I tried the following things:

**A** This works:

```python
def call(self, inputs):
    x = tf.math.subtract( inputs['vector'],inputs['vector_old'], name=None)
    x = tf.math.multiply(x,x)
    #x = tf.reduce_sum(x)
    x = x[0][0]
    x = tf.reshape(x,(1,1))
    return x
```

**B** This doesn't:

```python
def call(self, inputs):
    x = tf.math.subtract( inputs['vector'],inputs['vector_old'], name=None)
    x = tf.math.multiply(x,x)
    x = tf.reduce_sum(x)
    #x = x[0][0]
    x = tf.reshape(x,(1,1))
    return x 
```

**C** This doesn't work also:

```python
def call(self, inputs):
    x = tf.constant(1, shape=(1,1), dtype='float32')
    #x = tf.math.subtract( inputs['vector'],inputs['vector_old'], name=None)
    #x = tf.math.multiply(x,x)
    #x = tf.reduce_sum(x)
    #x = x[0][0]
    #x = tf.reshape(x,(1,1))
    return x
```

**D** But this works without a hard fault:
```python
def call(self, inputs):
    x = tf.math.subtract( inputs['vector'],inputs['vector_old'], name=None)
    x = tf.math.multiply(x,x)
    x1 = tf.math.add(x[0][0], x[0][1], name=None)
    x2 = tf.math.add(x[0][2], x[0][3], name=None)
    x = tf.math.add(x1,x2, name=None)
    x = tf.reshape(x,(1,1))
    return x
```

Thank you for any advice :)

Oliver

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
