### ISSUE TITLE
Can't Quantize Inputs As Uint8 In TFLM

### ISSUE THREAD

**Issue by embeddetech** [tensorflow/tensorflow#47610]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution: Windows 10
- TensorFlow installed from Source
- Tensorflow version 2.4.1
- Target platform Visual Studio

**Describe the problem**
I have been troubleshooting problems trying to run inference on a model using Tensorflow Lite for MIcrocontrollers in Visual Studio. I found the issue to be that the lite/micro/kernells/quantize.cc kernel is unable to accept Uint8 inputs, but supports UInt8 outputs. From lite/micro/kernels/quantize.cc in the Prepare() function, UInt8 is not included in the input type check:

```
  TF_LITE_ENSURE(context, input->type == kTfLiteFloat32 ||
                              input->type == kTfLiteInt16 ||
                              input->type == kTfLiteInt8);
  TF_LITE_ENSURE(context, output->type == kTfLiteUInt8 ||
                              output->type == kTfLiteInt8 ||
                              output->type == kTfLiteInt16 ||
                              output->type == kTfLiteInt32);
```
I originally created my quantized model using the conversion code example provided here, which shows using UInt8 for the input:

https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization

Should the TFLM implementation of the quantize kernel support UInt8? Or  perhaps the example should be updated to show using Int8?

**Comment by abattery** [comment]
CCing @ethkim

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
