### ISSUE TITLE
Addition of  kernel variant directory with fast portable kernels

### ISSUE THREAD

**Issue by andrewstevens-infineon** [tensorflow/tensorflow#47644]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary): n/a
- Tensorflow version (commit SHA if source): 
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.):

**Describe the problem**

Currently tflite(u) only has reference kernel implementations (written for clarity / correctness) and target/platform-specific optimized kernels variants.    It lacks efficient portable kernel implementations needed to achieve more competitive performance on Microcontrollers without dedicated support.   This is especially true of smaller Microcontrollers without DSP/NN ISA extensions (e.g. small RISC-V devices) where good portable C++ implementations can achieve close-to-optimal results.

**Please provide the exact sequence of commands/steps when you ran into the problem**

n/a

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
