### ISSUE TITLE
More info on the deprecation of predict_x method for Sequential model?

### ISSUE THREAD

**Issue by gqqnbig** [tensorflow/tensorflow#47671]
I traced down to https://github.com/tensorflow/tensorflow/commit/9795964342fbb0b6104b5ae131600d62faddb8c9 which marked predict_x method as deprecated.

But are there more information on the deprecation? Who made the decision? Are there any discussion on the deprecation? Are there any whatsnew/breaking changes items?

**Comment by sachinprasadhs** [comment]
Many of the API are depreciated and moved to new mode mainly because it runs on v1.Session style code and may fall under compatibility guarantees and can behave unexpectedly when combined with TF 2 code also to make the user experience better with the improved performance these changes will be made.

**Comment by gqqnbig** [comment]
Fine. If you don't want to revise some docs, I will close the issue.

**Comment by sachinprasadhs** [comment]
Depreciation warning will be added initially as you see in the linked PR, in the subsequent Tensorflow versions it will be removed. You can go ahead and close the issue. Thanks!
