### ISSUE TITLE
Model.fit average gradients by batch_size

### ISSUE THREAD

**Issue by NEGU93** [tensorflow/tensorflow#47702]
So, it seems `Model.fit` is averaging the gradient over the batch size.

There is a simple [script](https://github.com/NEGU93/cvnn/blob/master/debug/mwe_testing_learning_algo.py) I did to check that assertion and it was discussed in [stackoverlow](https://stackoverflow.com/questions/66566905/debugging-tensorflow-fit-not-making-sense/)

It is highly possible this is by design and not a bug but I wanted to report it just in case it is indeed a bug.

**Comment by Saduf2019** [comment]
@NEGU93 
Please share simple stand alone code to replicate the issue reported.

**Comment by NEGU93** [comment]
I already did. Is the link to the script. Is a standalone .py file. The logic of how I test it and why it should work is detailed on the stackoverlow link.

**Comment by Saduf2019** [comment]
@NEGU93
i ran the script shared on tf 2.3,2.4 and nightly, please refer to [this gist](https://colab.research.google.com/gist/Saduf2019/4bb39d011175bd41ceccdfac44b93651/untitled564.ipynb) and confirm.

**Comment by NEGU93** [comment]
Yes, this is it. You can see that when I get at least some `True` (Not all of them but maybe due to rounding errors) is by comparing the gradient to:
`(i_w - f_w) * BATCH_SIZE / 0.01`. You can change `BATCH_SIZE` to verify this is not a case for a specific number.

**Comment by sushreebarsa** [comment]
Was able to replicate the issue in TF v2.5,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/58da3b5c5b4c125c1a47da8ecb4aecb8/untitled159.ipynb)..Thanks !

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
