### ISSUE TITLE
TF C-API GPU not found via TF_SessionListDevices

### ISSUE THREAD

**Issue by mlpva** [tensorflow/tensorflow#47721]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10
- TensorFlow installed from (source or binary): binary
- TensorFlow version: 2.4
- CUDA/cuDNN version: 11.0 / 8.0.4
- GPU model and memory: GeForce MX250 2048MB GDDR5

I'm currently working on a CNN deployment via the Tensorflow C-API. When checking for the available devices via **TF_SessionListDevices** only the CPU is listed. I already checked my CUDA installation and verified it on the python side which detects the GPU. Trying to set the device via hex string doesn't fix it.

**Provide the exact sequence of commands / steps that you executed before running into the problem**

    TF_Graph* Graph = TF_NewGraph();
    TF_Status* Status = TF_NewStatus();

    uint8_t config[13] = { 0xa, 0x7, 0xa, 0x3, 0x47, 0x50, 0x55, 0x10, 0x0, 0x10, 0x1, 0x28, 0x1};

    TF_SessionOptions* SessionOpts = TF_NewSessionOptions();
    TF_Buffer* RunOpts = NULL;

    TF_SetConfig(SessionOpts, (void*)config, 13, Status);

    if (TF_GetCode(Status) == TF_OK)
    {
        printf("TF_SetConfig OK\n");
    }
    else
    {
        printf("%s", TF_Message(Status));
    }

    const char* saved_model_dir = "\\model";
    const char* tags = "serve"; // default model serving tag; can change in future
    int ntags = 1;

    TF_Session* Session = TF_LoadSessionFromSavedModel(SessionOpts, RunOpts, saved_model_dir, &tags, ntags, Graph, NULL, Status);
    if (TF_GetCode(Status) == TF_OK)
    {
        printf("TF_LoadSessionFromSavedModel OK\n");
    }
    else
    {
        printf("%s", TF_Message(Status));
    }

    //Check devices
    TF_DeviceList* dl = TF_SessionListDevices(Session, Status);
    if (TF_GetCode(Status) == TF_OK)
    {
        printf("TF_SessionListDevices OK\n");
        int count = TF_DeviceListCount(dl);
        const char* list;
        const char* tpe;
        printf("DeviceList:\n");
        for (int i = 0; i < count; i++)
        {
            list = TF_DeviceListName(dl, i, Status);
            tpe = TF_DeviceListType(dl, i, Status);
            printf(list);
            printf("\n");
        }

        TF_DeleteDeviceList(dl);
    }
    else
    {
        printf("%s", TF_Message(Status));
    }

Expected output should be two list members with type CPU and GPU each, but only the CPU device is listed.

Any help on this issue would be appreciated.

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by sanjoy** [comment]
I'm not too familiar with the C API, @agarwal-ashish do you know what's going on here?

**Comment by mlpva** [comment]
Bump

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
