### ISSUE TITLE
weights_initializer in tf.contrib.layers.fully_connected

### ISSUE THREAD

**Issue by marcoadurno** [tensorflow/tensorflow#4774]
Hi, 

At present contrib.layers.fully_connected is unable to accept a Tensor as an initializer for the weights.

This because when calling variable_scope.get_variable (which accepts a Tensor as an initializer) it specifies both the initializer and the shape. Is this expected behavior or a bug? 

I have put together a small [gist ](https://gist.github.com/marcoadurno/60faf136193d8eccc83d14932d188d25) that illustrates the issue.

At present what's the recommended way to pass a Tensor as an initializer? Would a [dummy init_fn](https://gist.github.com/marcoadurno/60faf136193d8eccc83d14932d188d25#file-layers_weights_test-py-L34) be acceptable?

I'm currently running rev: 9c11fe2f1db1ccf5bcdb0724c18cc462ff5fbbd7.

Thanks,

Marco

**Comment by tatatodd** [comment]
@marcoadurno Thanks for filling the issue and the gist!  FYI your `dummy init_fn` link is broken.

@sguada probably has some advice here.

**Comment by marcoadurno** [comment]
@tatatodd link fixed, it was pointing to a copy of the gist in a private repo.

**Comment by sguada** [comment]
You can use a function to initialize a variable with a constant, the problem is that those constants become part of the graph and adding many of them could make it very big.

Instead the recommended way to initialize a variable with a value is using [assign_from_values_fn](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/framework/python/ops/variables.py#L447):
```
init_assign_fn = assign_from_values_fn({'scope/weights': value})
sess.run(init_assign_fn)
```

**Comment by aselle** [comment]
@marcoadurno, did you find a solution to this issue?

**Comment by prb12** [comment]
Closing due to lack of response.  Please reopen if necessary.
