### ISSUE TITLE
C API gradient tape support

### ISSUE THREAD

**Issue by rnett** [tensorflow/tensorflow#47748]
**System information**
- TensorFlow version: 2.4.1
- Are you willing to contribute it: Probably not

**Describe the feature and the current behavior/state.**

Gradients are being ported to C++, with the tape API in [c/eager/gradients.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/eager/gradients.h).

However, there is no equivalent C API, and as per https://github.com/tensorflow/community/pull/335 it does not seem there are current plans to add one.

I assume this is on the radar somewhere, but I don't see any tracking issues, so I'm making this as tracking (and a request).

**Will this change the current api? How?**

It will expose the existing gradient tape api to the C API.  Gradient registration should be exposed as well to allow for registering custom gradients (it seems to be tape specific?).

**Who will benefit with this feature?**

It will enable eager mode to support gradients for projects using the C API bindings, including the [official JVM bindings](https://github.com/tensorflow/java) (which is what prompted this issue) and those that depend on it.

**Comment by bhack** [comment]
For JVM, are they working directly with C++ interfaces https://github.com/tensorflow/java/pull/283?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
