### ISSUE TITLE
Any way to train a TF1 graph in TF2 without using tf.compat.v1.Session?

### ISSUE THREAD

**Issue by rachthree** [tensorflow/tensorflow#47751]
Hello, hope y’all are staying safe and healthy! Currently my group is migrating from TF 1.8 to TF 2.4.1. Some of our work is dependent on `tensorflow_gan` back when it used to be under `models/research`. We would take the initial graph generated and then train it with our own framework. The files are:

```
checkpoint
model.ckpt.data-00000-of-00001
model.ckpt.meta
model.ckpt.index
```

And below was our TF 1.8 code that would train the GAN. I apologize that due to policy, I cannot copy and paste, but this is just to have an idea:

```
tf.train.import_meta_graph(graph_path + ‘.meta’)
graph = tf.get_default_graph()
gen_input = graph.get_tensor_by_name(“inputs/gen_input:0”)
gen_loss = graph.get_tensor_by_name(“losses/truediv:0”)
gen_train_op =  graph.get_tensor_by_name(“train_ops/generator_train/train_op/control_dependency:0”)
gen_output = graph.get_tensor_by_name(“Generator/output/add:0”)
dis_input = graph.get_tensor_by_name(“inputs/x_placeholder:0”)

with tf.Session() as sess:
	with tf.variable_scope(tf.get_variable_scope(), reuse=False):
		assert tf.get_variable_scope().reuse == False
	tf.train.Saver().restore(sess, restore_path)

	for iteration in range(max_epochs):
		real_data, fake_data = dataset.get_next_batch()
		_, loss = sess.run([gen_train_op, gen_loss], feed_dict={gen_input:fake_data, dis_input:real_data})
```

We would like to be as close to TF2 and use Keras as much as possible. Is there any way to wrap the tensors from `graph.get_tensor_by_name` or the whole graph into a `tf.Keras.Model`, or must we use `tf.compat.v1.Session`? We’d ideally like to convert this into a `saved_model.pb` that can be imported and used like a `tf.Keras.Model` for additional training, not just inference.

If not, is it possible to combine a loaded graph with a `tf.Keras.Model` for training? For instance, having a model be a backbone to another, and then train on the whole model.

Thanks!

**Comment by tomerk** [comment]
`get_tensor_by_name` is not something that should be used in TF2. (You should not be relying on variable or tensor names directly).

variable_scope is also not currently supported in TF2-proper as-is (outside of sessions, which are realistically TF1 just included in the TF2 binaries).

You *may* be able to put your variable scopes inside of a `tf.compat.v1.make_template` and have it work (and then you can add the make_template's variables to a Keras layer if you'd like).


We are currently exploring alternatives that will allow variable_scope code to be used more effectively from w/in Keras (purely as a form of a migration tooling), so you may be able to repurpose this test prototype (that still has debugging logs/notes attached):

```
import tensorflow.python.ops.variable_scope as variable_scope
import contextlib
import re

# TODO: May need to avoid writing variables to graph collection even when
# Using the eager variable store. (right now it looks like they do get written)
# Otherwise the variables may become global/
# never get cleaned up.

# Also note: This will have higher python overheads in eager than purely-object-attr-based accesses.
# Should be fine in a python function though?

class _RegularizerCapturingEagerVariableStore(variable_scope._VariableStore):
  def __init__(self, *args, **kwargs):
    super().__init__(*args, **kwargs)
    self.regularizers = {}
    self._store_eager_variables = tf.compat.v1.executing_eagerly_outside_functions # Yay code archeology!
    self._observed_created_variables = []

  def get_variable(self, *args, **kwargs):
    # print("Created: ", args, kwargs)
    # Todo: this extraction is a bit sketchy & depends on exact api of internal _VariableStore
    if len(args) > 4:
      regularizer = args[4]
    else:
      regularizer = kwargs.get('regularizer')
    var = super().get_variable(*args, **kwargs)
    if regularizer is not None:
      # print("Caught reg!: ", var.name, regularizer)
      self.regularizers[var.name] = regularizer
    if not (id(var) in [id(x[0]) for x in self._observed_created_variables]):
      self._observed_created_variables.append((var, 'new'))
    else:
      self._observed_created_variables.append((var, 'reused'))

    return var


class VariableCapturer(tf.Module):
  def __init__(self):
    self._var_store = _RegularizerCapturingEagerVariableStore()
    self._variables = {}
    self._observed_created_variables = []

  def _variable_creator(self, next_creator, **kwargs):
    var = next_creator(**kwargs)
    self._variables[var.name] = var

    # Weirdness: may need this due to weird tracking not triggering on dict inserts for keras layers thing? TBD since this wasn't tested on nightly.
    # As of nightly modules are supposed to be tracked by layers.
    self._variables = self._variables

    if not (id(var) in [id(x[0]) for x in self._observed_created_variables]):
      self._observed_created_variables.append((var, 'new'))
    else:
      self._observed_created_variables.append((var, 'reused'))
    return var

  @contextlib.contextmanager
  def scope(self):
    with tf.variable_creator_scope(self._variable_creator), variable_scope.with_variable_store(self._var_store):
      yield

  def get_regularization_losses(self, scope=None):
    # scope regex matching taken directly from collections scope regex matching
    losses = {}
    if scope is None:
      for var_name, regularizer in self._var_store.regularizers.items():
        losses[var_name] = regularizer(self._variables[var_name])
    else:
      regex = re.compile(scope)
      for var_name, regularizer in self._var_store.regularizers.items():
        if regex.match(var_name):
          losses[var_name] = regularizer(self._variables[var_name])
    return losses
    ```

(We cannot currently provide advice or support around this prototype though since it is still very much a work-in-progress. It may also require the tf nightlies / tf 2.5 to be out if you want to track tf.Modules from inside keras layers/models).

 If as you say you'd like to be as close to TF2 and use Keras as much as possible and this is urgent, we'd suggest rewriting the core pieces of GAN functionality that you need with Keras. If you have a few months to wait then we may have a more official shim for variable_scope ready. Or you could always see if compat.v1.make_template works.
