### ISSUE TITLE
TFLM Magic Wand example perform late 

### ISSUE THREAD

**Issue by SunBeenMoon** [tensorflow/tensorflow#47806]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- Tensorflow version (commit SHA if source):
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Himax WE-1

Hi, 

I would like to ask for comments from developers who have implemented the magic wand example.

I ran the magic wand example with a Himax WE-1 board. However, there was a problem with slow reaction.
1. After executing the program, it is not recognized even if one of the wing ring slopes is executed continuously. For example, running the wing several times didn't bring up anything in the prompt window.

2. As it still did not recognize, I restarted by pressing the reset button. So, the previously entered action was continuously displayed. In other words, when the program was executed, it could not be launched and was pushed and operated. For example, after entering the wing multiple times in the previous operation, the prompt window did not appear, so as soon as the reset button was pressed, the wing was launched twice in succession.

When running other examples supported by the Himax board, it does not appear to be a problem in the prompt window as there was no problem.

I would like to hear from developers who are having the same problem as me or who have no problem when running magic wand.

Thanks

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
