### ISSUE TITLE
Tensorflow (Using TensorFlow backend.)

### ISSUE THREAD

**Issue by mahsajalali** [tensorflow/tensorflow#47800]
while running the INVASE code I got this error,

Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\Mahsa\AppData\Roaming\Python\Python37\site-packages\tensorflow\python\platform\self_check.py", line 75, in preload_check
    ctypes.WinDLL(build_info.cudart_dll_name)
  File "C:\Users\Mahsa\AppData\Local\Programs\Python\Python37\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found
 How could I fix it? 
I have installed many Tersorflow libraries and check if one works or not, but noone has works!

**Comment by amahendrakar** [comment]
@mahsajalali,
In order to expedite the trouble-shooting process, could you please provide the following information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

along with the complete code and the dataset you are using. Thanks!
