### ISSUE TITLE
Creating ragged tensors is incredibly slow

### ISSUE THREAD

**Issue by bjourne** [tensorflow/tensorflow#47853]
I'm running the following code on a Google Colab instance with GPU support enabled:
```
tf.ragged.constant(np.random.randint(10, size = 10_000_000))
```
The code takes 15 seconds to finish. In comparison, `tf.constant(np.random.randint(10, size = 10_000_000))` takes only 50 milliseconds to finish.

**Comment by Saduf2019** [comment]
I am able to replicate the issue reported on tf 2.3,2.4 and nightly, please find the [gist here](https://colab.research.google.com/gist/Saduf2019/51cc6e1d071d86111071a731fbf09d26/untitled564.ipynb).

**Comment by jvishnuvardhan** [comment]
@bjourne Recently Colab has some problems in accessing `gpu`. So, even when you select `gpu` it is still running in `cpu`. Please check the [gist here](https://colab.research.google.com/gist/jvishnuvardhan/6a958d7f505101b1ddac8aec2ca93e6e/untitled564.ipynb).

Adding the following code to check `gpu` usage throws error

```
device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))
```

Can you please run it on GPU and let us know if there is any issue there. Thanks!

**Comment by bjourne** [comment]
Yes, same thing with a GPU:
```import tensorflow as tf
import numpy as np
from time import time

device_name = tf.test.gpu_device_name()
if device_name != '/device:GPU:0':
  raise SystemError('GPU device not found')
print('Found GPU at: {}'.format(device_name))

st = time()
tf.ragged.constant(np.random.randint(10, size = 10_000_000))
print(time() - st)
```
The code takes 14.8 seconds to finish.

**Comment by edloper** [comment]
It looks like most of the time is being spent in `_find_scalar_and_max_depth`.  Two options to speed up that function:

1. short-circuit and return early once we find any scalar value.  (But this may prevent us from giving good error messages if the user supplies an input with scalar values at different nesting depths.)
2. change `np.ndim(pylist) != 0` to `(isinstance(pylist, np.ndarray) and np.ndim(pylist) != 0` -- calling `ndim` seems to take up a fair amount of time.  Not sure if this will break any existing use-cases.

But even with these fixes, `tf.ragged.constant` will probably still be significantly slower than `tf.constant` (especially if the input is a numpy array), since `tf.constant` is implemented in c and `tf.ragged.constant` is implemented in Python.

If you want to ingest ragged large tensors quickly, and it's possible to get them into a format other than nested python lists, then you might consider using one of the following:

* The `RaggedTensor` factory methods, such as `tf.ragged.from_row_splits` or `tf.ragged.from_row_lengths`.  (Use `validate=False` to prevent validation ops from being added to the graph, which can slow things down.)
* The `RaggedTensor.from_tensor` method, which has optional `padding` and `lengths` arguments you can use to specify which values are padding.
* If you have a list of numpy arrays (for each row), then you could use `tf.ragged.stack(list_of_numpy_arrays)`.

All of these options will be substantially faster than `tf.ragged.constant`.

What is the actual shape of ragged tensors you want to ingest?  This could impact what approach will be best for ingesting them.  Examples:

- a 2d tensor [dense, ragged] where `dense` and `ragged` are both very large.
- a 3d tensor [dense_1, ragged_1, ragged_2, dense_2], where `dense_1` and `ragged_1` are large, but `ragged_2` and `dense_2` are small.

(In the example you used for timing, you pass in a 1D list, which can't even be ragged -- RaggedTensors always have rank>1.)

**Comment by bjourne** [comment]
It's a 2d-tensor [n, size]. n is 10k and size varies between 100 to 1000.

**Comment by yonikremer** [comment]
I struggle with the same issue, have you managed to improve the efficiency?

**Comment by jvishnuvardhan** [comment]
@bjourne Is this still an issue for you? I think this is intended and @edloper provided couple of suggestions to improve. Thanks!

**Comment by bjourne** [comment]
Yeah it's still an issue! The code I pasted still runs dog slow.

**Comment by deepakagrawal** [comment]
I have a list of 2d numpy arrays `(m,n)` where `m` is variable (order of 1000) and `n` is fixed (say 1000). I have around 10000 such arrays. The final ragged tensor should be of shape `(10000, None, 1000)`. `RaggedTensor.stack` is fast however it results into a ragged tensor of `ragged_rank=2`, shape=`(10000, None, None)`. How can I convert this into a tensor which has a ragged rank of 1. `RaggedTensor.constant` gives correct results, however it is incredibly slow.

**Comment by thariq-nugrohotomo** [comment]
> I have a list of 2d numpy arrays `(m,n)` where `m` is variable (order of 1000) and `n` is fixed (say 1000). I have around 10000 such arrays. The final ragged tensor should be of shape `(10000, None, 1000)`. `RaggedTensor.stack` is fast however it results into a ragged tensor of `ragged_rank=2`, shape=`(10000, None, None)`. How can I convert this into a tensor which has a ragged rank of 1. `RaggedTensor.constant` gives correct results, however it is incredibly slow.

Hi @deepakagrawal,
Try using factory class-methods such as:

- [tf.RaggedTensor.from_value_rowids](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor#from_value_rowids), 
- [tf.RaggedTensor.from_row_lengths](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor#from_row_lengths), and 
- [tf.RaggedTensor.from_row_splits](https://www.tensorflow.org/api_docs/python/tf/RaggedTensor#from_row_splits).


Here's an example of using `tf.RaggedTensor.from_row_splits` to convert a `(100000, 1000)` numpy-array into a `(1000, None, 1000)` ragged-tensor. https://colab.research.google.com/drive/1WnyvzoB8oE5vGXq5iYHJAAv7RQDADVU8?usp=sharing

```
CPU times: user 16.5 ms, sys: 18.6 ms, total: 35.1 ms
Wall time: 39.7 ms
```

**Comment by edloper** [comment]
@deepakagrawal: +1 to using the `RaggedTensor` factory methods.  In your example, you could convert the numpy arrays into a RaggedTensor using `RaggedTensor.from_row_lengths` as follows:

```
import numpy as np
np_arrays = [np.zeros([i, 1000]) for i in range(1000)]  # example array.

ragged_tensor = tf.RaggedTensor.from_row_lengths(
    values=tf.concat(np_arrays, axis=0),
    row_lengths=[a.shape[0] for a in np_arrays])
```

**Comment by deepakagrawal** [comment]
Thanks, This worked perfectly

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
