### ISSUE TITLE
TensorFlow-Lite: need for ruy library

### ISSUE THREAD

**Issue by WannesBouwen** [tensorflow/tensorflow#47862]
Hello

For an embedded software project, we are trying to integrate TensorFlow-Lite via buildroot (via CMake). In the CMakeLists.txt we find following option:

option(TFLITE_ENABLE_RUY "Enable experimental RUY integration" OFF)

However, even with this option disabled, the ruy library is still needed in order to compile TensorFlow-Lite. My question is if this is really necessary, or that with the right adaptions to the code it should in principle work without this libary. We want to minimize the amount of libraries we are taking in, also because ruy in its turn depends for example on the pyTorch cpuinfo library.

We are compiling for an ARM64 architecture.

Kind regards,

Wannes

**Comment by terryheo** [comment]
Currently there is a code which always rely on RUY. So it's inevitable now. But I'll handle it later.

BTW, if you're using aarch64, RUY gives performance improvement. Could you share why do you want to minimize library dependencies?

**Comment by WannesBouwen** [comment]
Hello,

As we are running on an embedded system with a limited amount of memory, we want to avoid all libraries which we do not necessarily need. A performance hit is less of a problem for us.

Kind regards,

Wannes

**Comment by terryheo** [comment]
Acknowledged.

BTW, if you're quite limited on memory, we should use TFLite Micro.

**Comment by WannesBouwen** [comment]
Thanks for the suggestion. I'll have a look into TFLite Micro. We are however running on an ARM A53, for which I do not immediately see support in the micro framework.

**Comment by talumbau** [comment]
It is correct that Ruy is an unconditional dependency for ARMv8 builds, but the dependency set within Ruy is not very large. For example, one can build Ruy without the cpuinfo library (but in that I don't believe the library would be able to choose optimized kernels based on  the detected platform). I think a good way to describe the situation is as follows: Ruy contains the optimized GEMM kernels used on ARMv8 that are necessary for good performance on that platform. Ruy needs cpuinfo in order to choose the proper kernels, again for good performance. So a minimal set of dependencies on ARMv8 that make TF Lite useful would include Ruy and cpuinfo. Depending on your use case, you may wish to create a stripped down build, for example  only using gemmlowp or only using eigen, but we don't maintain builds like that because the goal is a fully usable (both float and quant) library that has good performance while minimizing binary size. One option for your case is to manually reduce the set of built-in ops that TF Lite ships with by default. If you are just interested in a certain type of model with just a few ops, you could potentially significantly reduce binary size. This would of course not be something you could upstream back to TF Lite, but it might solve your immediate issue.

**Comment by misterBart** [comment]
Same issue with me.
And also here: https://gitanswer.com/tensorflow-cmake-build-option-tflite-enable-ruy-off-does-not-work-cplusplus-871733814
Just wasted quite some time before I found this thread. Quite annoying that the documentation (https://www.tensorflow.org/lite/guide/build_cmake) mentions it as an option.
