### ISSUE TITLE
TFLite Documentation Request: How do per-axis quantizations work with subsequent layers?

### ISSUE THREAD

**Issue by atyshka** [tensorflow/tensorflow#47893]
## URL(s) with the issue:

https://www.tensorflow.org/lite/performance/quantization_spec

## Description of issue (what needs changing):
Documentation on how per-axis quantization works with subsequent layers

### Clear description

I am working on implementing the algorithms for TFLite layers in FPGA and I'm uncertain how the quantization spec expects subsequent layers to deal with per-axis quantizations. For example, following the tutorial [here](https://www.tensorflow.org/lite/performance/post_training_integer_quant) there is a 12-channel convolution which is pooled and flattened before being fed to a fully connected layer. The output of the convolution op has different quantization scales for each of the 12 channels. But then flattening the tensor it would seem this information is lost? The two options I can see are either rescaling the tensor so that the reshaped tensor has the same quantization uniformly. That would seemingly eliminate any benefits of per-axis quantization if it's just being undone in the next step. If the reshape does not re-scale them to the same scheme, wouldn't that then introduce a massive difference in the distribution of data going to the fully connected layer?

The logical explanation to me is that per-axis quantizations are only useful when feeding one convolutional layer to another convolutional layer. If the output of a convolution operation goes to anything other than a convolution, the output is re-scaled to match the same quantization scheme for all channels. But I'm unsure if that's what actually happens

### Correct links

N/A

### Parameters defined

N/A

### Returns defined

N/A

### Raises listed and defined

N/A

### Usage example

N/A

### Submit a pull request?

I do not know enough to submit a PR but if someone with knowledge can answer my question I can contribute it to the docs.

**Comment by abattery** [comment]
@daverim could you take a look?

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
