### ISSUE TITLE
Weights in tf.estimator.BoostedTreesClassifier()

### ISSUE THREAD

**Issue by mattiasthalen** [tensorflow/tensorflow#47912]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Win 10
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): PIP
- TensorFlow version (use command below): v2.4.0-49-g85c8b2a817f 2.4.1
- Python version: 3.8.5
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: 11.2
- GPU model and memory: NVIDIA Quadro T2000 with Max Q-design, 4GB. 64GB RAM

**Describe the current behavior**
Error when setting the weight_column in ```tf.estimator.BoostedTreesClassifier()```
Encoded as a feature using tf.feature_column.numeric_column() and appended to list feature_columns.

It works perftectly with ```tf.estimator.DNNClassifier()```

**Describe the expected behavior**
No error :)

**Standalone code to reproduce the issue**
```
tf.estimator.BoostedTreesClassifier(feature_columns,
                                    n_batches_per_layer = 1,
                                    weight_column = 'weeks_to_complete_weights',
                                    n_trees = 100)
```
**Other info / logs**
TypeError: Expected float32 passed to parameter 'y' of op 'Mul', got 'weeks_to_complete_weights' of type 'str' instead. Error: Expected float32, got 'weeks_to_complete_weights' of type 'str' instead.

**Comment by amahendrakar** [comment]
@mattiasthalen,
On running the code, I am facing an error stating `NameError: name 'feature_columns' is not defined`. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/dc2d218f7b1686832cda85f47bc9761f/47912.ipynb). 

In order to expedite the trouble-shooting process, could you please provide the complete code to reproduce the issue reported here and also the dataset you are using. Thanks!
