### ISSUE TITLE
Process finished with exit code -1073740791 (0xC0000409) when training on GPU

### ISSUE THREAD

**Issue by farazk86** [tensorflow/tensorflow#47934]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): [copied code from tensorflow transfer learning documentation](https://www.tensorflow.org/guide/keras/transfer_learning#an_end-to-end_example_fine-tuning_an_image_classification_model_on_a_cats_vs_dogs_dataset)
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10 - 64 bit
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: n/a
- TensorFlow installed from (source or binary): ``pip install tensorflow``
- TensorFlow version (use command below): ``v2.4.0-rc4-71-g582c8d236cb 2.4.0``
- Python version: 3.6.8
- Bazel version (if compiling from source): n/a
- GCC/Compiler version (if compiling from source): n/a
- CUDA/cuDNN version: cuda:  cuda_11.2.r11.2/ cuDNN: v8.1.1.33
- GPU model and memory: Nvidia 1080 8GB

tf_env script output:

```

== check python ===================================================

== check os platform ===============================================

== are we in docker =============================================
No

== compiler =====================================================
bash: c++: command not found

== check pips ===================================================
numpy                  1.19.5
protobuf               3.14.0
tensorflow             2.4.0
tensorflow-estimator   2.4.0

== check for virtualenv =========================================

== tensorflow import ============================================
bash: /c/Users/Faraz: No such file or directory

== env ==========================================================
LD_LIBRARY_PATH is unset
DYLD_LIBRARY_PATH is unset

== nvidia-smi ===================================================
Fri Mar 19 23:41:09 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.89       Driver Version: 460.89       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080   WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   36C    P8     9W /  N/A |    963MiB /  8192MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A       532    C+G   ...y\ShellExperienceHost.exe    N/A      |
|    0   N/A  N/A      1276    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      2784    C+G   ...lPanel\SystemSettings.exe    N/A      |
|    0   N/A  N/A      4564    C+G   ...t\Teams\current\Teams.exe    N/A      |
|    0   N/A  N/A      7408    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A      7928    C+G   C:\Windows\explorer.exe         N/A      |
|    0   N/A  N/A      8532    C+G   ...ekyb3d8bbwe\YourPhone.exe    N/A      |
|    0   N/A  N/A      8732    C+G   ...artMenuExperienceHost.exe    N/A      |
|    0   N/A  N/A      9116    C+G   ...w5n1h2txyewy\SearchUI.exe    N/A      |
|    0   N/A  N/A      9996    C+G   ...cw5n1h2txyewy\LockApp.exe    N/A      |
|    0   N/A  N/A     11768    C+G   Insufficient Permissions        N/A      |
|    0   N/A  N/A     11836    C+G   ...m Files (x86)\SCM\SCM.exe    N/A      |
|    0   N/A  N/A     11936    C+G   ...b3d8bbwe\WinStore.App.exe    N/A      |
|    0   N/A  N/A     12800    C+G   ...t\Teams\current\Teams.exe    N/A      |
|    0   N/A  N/A     13164    C+G   ...a\74.0.3911.160\opera.exe    N/A      |
|    0   N/A  N/A     14716    C+G   ...wekyb3d8bbwe\Video.UI.exe    N/A      |
|    0   N/A  N/A     15196    C+G   ...in7x64\steamwebhelper.exe    N/A      |
+-----------------------------------------------------------------------------+

== cuda libs  ===================================================

== tensorflow installed from info ==================
Name: tensorflow
Version: 2.4.0
Summary: TensorFlow is an open source machine learning framework for everyone.
Home-page: https://www.tensorflow.org/
Author-email: packages@tensorflow.org
License: Apache 2.0
Location: c:\users\faraz khan\appdata\local\programs\python\python36\lib\site-packages
Required-by: 

== python version  ==============================================
(major, minor, micro, releaselevel, serial)
(3, 6, 8, 'final', 0)

== bazel version  ===============================================

```

**Describe the current behavior**

When running model training on GPU, I get the following output:

```
2021-03-19 23:43:27.889416: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-19 23:43:31.028195: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
2021-03-19 23:43:31.029096: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library nvcuda.dll
2021-03-19 23:43:31.052703: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.771GHz coreCount: 20 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 298.32GiB/s
2021-03-19 23:43:31.053038: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-19 23:43:31.080499: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-19 23:43:31.080660: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-19 23:43:31.097601: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-19 23:43:31.101390: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-19 23:43:31.150363: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-19 23:43:31.165564: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-19 23:43:31.166410: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-19 23:43:31.166617: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-19 23:43:31.167034: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2021-03-19 23:43:31.167949: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
pciBusID: 0000:01:00.0 name: GeForce GTX 1080 computeCapability: 6.1
coreClock: 1.771GHz coreCount: 20 deviceMemorySize: 8.00GiB deviceMemoryBandwidth: 298.32GiB/s
2021-03-19 23:43:31.168488: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll
2021-03-19 23:43:31.168746: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-19 23:43:31.169257: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-19 23:43:31.169475: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cufft64_10.dll
2021-03-19 23:43:31.169697: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library curand64_10.dll
2021-03-19 23:43:31.169887: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusolver64_10.dll
2021-03-19 23:43:31.170027: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cusparse64_11.dll
2021-03-19 23:43:31.170168: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll
2021-03-19 23:43:31.170350: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1862] Adding visible gpu devices: 0
2021-03-19 23:43:31.796539: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
2021-03-19 23:43:31.796758: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      0 
2021-03-19 23:43:31.796853: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1280] 0:   N 
2021-03-19 23:43:31.797098: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1406] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6274 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
2021-03-19 23:43:31.798090: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
Number of training samples: 9305
Number of validation samples: 2326
Number of test samples: 2326
2021-03-19 23:43:32.077770: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:116] None of the MLIR optimization passes are enabled (registered 2)
2021-03-19 23:43:33.184162: W tensorflow/core/kernels/data/cache_dataset_ops.cc:757] The calling iterator did not fully read the dataset being cached. In order to avoid unexpected truncation of the dataset, the partially cached contents of the dataset will be discarded. This can happen if you have an input pipeline similar to `dataset.cache().take(k).repeat()`. You should use `dataset.take(k).cache().repeat()` instead.
Epoch 1/20
2021-03-19 23:43:37.097103: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublas64_11.dll
2021-03-19 23:43:37.446836: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cublasLt64_11.dll
2021-03-19 23:43:37.484678: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudnn64_8.dll

Process finished with exit code -1073740791 (0xC0000409)
```
The code I am using is mentioned from the official documentation for transfer learning as linked above. But every time I get this error. 

Also, no matter what batch size I use, the GPU memory always shoots up to almost maximum capacity as can be seen from screenshot below, but no training happens as it fails at ``epoch 1``.

![Capture221](https://user-images.githubusercontent.com/33456896/111851982-4202ec00-890d-11eb-9cf8-70a1540d6675.JPG)

When I re-run this code on cpu using the lines:

```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "-1"
```

The training runs fine without any problems but runs on the cpu. :(

**Describe the expected behavior**

It should be able to train on the GPU.

**Standalone code to reproduce the issue**

As mentioned above, I'm using the transfer learning tensorflow example code:

```python
import tensorflow as tf
import tensorflow_datasets as tfds
import matplotlib.pyplot as plt
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np

# tfds.disable_progress_bar()

train_ds, validation_ds, test_ds = tfds.load(
    "cats_vs_dogs",
    # Reserve 10% for validation and 10% for test
    split=["train[:40%]", "train[40%:50%]", "train[50%:60%]"],
    as_supervised=True,  # Include labels
)

print("Number of training samples: %d" % tf.data.experimental.cardinality(train_ds))
print(
    "Number of validation samples: %d" % tf.data.experimental.cardinality(validation_ds)
)
print("Number of test samples: %d" % tf.data.experimental.cardinality(test_ds))

plt.figure(figsize=(10, 10))
for i, (image, label) in enumerate(train_ds.take(9)):
    ax = plt.subplot(3, 3, i + 1)
    plt.imshow(image)
    plt.title(int(label))
    plt.axis("off")

size = (150, 150)

train_ds = train_ds.map(lambda x, y: (tf.image.resize(x, size), y))
validation_ds = validation_ds.map(lambda x, y: (tf.image.resize(x, size), y))
test_ds = test_ds.map(lambda x, y: (tf.image.resize(x, size), y))

batch_size = 32

train_ds = train_ds.cache().batch(batch_size).prefetch(buffer_size=10)
validation_ds = validation_ds.cache().batch(batch_size).prefetch(buffer_size=10)
test_ds = test_ds.cache().batch(batch_size).prefetch(buffer_size=10)

data_augmentation = keras.Sequential(
    [
        layers.experimental.preprocessing.RandomFlip("horizontal"),
        layers.experimental.preprocessing.RandomRotation(0.1),
    ]
)

for images, labels in train_ds.take(1):
    plt.figure(figsize=(10, 10))
    first_image = images[0]
    for i in range(9):
        ax = plt.subplot(3, 3, i + 1)
        augmented_image = data_augmentation(
            tf.expand_dims(first_image, 0), training=True
        )
        plt.imshow(augmented_image[0].numpy().astype("int32"))
        plt.title(int(labels[0]))
        plt.axis("off")


base_model = keras.applications.Xception(
    weights="imagenet",  # Load weights pre-trained on ImageNet.
    input_shape=(150, 150, 3),
    include_top=False,
)  # Do not include the ImageNet classifier at the top.

# Freeze the base_model
base_model.trainable = False

# Create new model on top
inputs = keras.Input(shape=(150, 150, 3))
x = data_augmentation(inputs)  # Apply random data augmentation

# Pre-trained Xception weights requires that input be normalized
# from (0, 255) to a range (-1., +1.), the normalization layer
# does the following, outputs = (inputs - mean) / sqrt(var)
norm_layer = keras.layers.experimental.preprocessing.Normalization()
mean = np.array([127.5] * 3)
var = mean ** 2
# Scale inputs to [-1, +1]
x = norm_layer(x)
norm_layer.set_weights([mean, var])

# The base model contains batchnorm layers. We want to keep them in inference mode
# when we unfreeze the base model for fine-tuning, so we make sure that the
# base_model is running in inference mode here.
x = base_model(x, training=False)
x = keras.layers.GlobalAveragePooling2D()(x)
x = keras.layers.Dropout(0.2)(x)  # Regularize with dropout
outputs = keras.layers.Dense(1)(x)
model = keras.Model(inputs, outputs)

# model.summary()

model.compile(
    optimizer=keras.optimizers.Adam(),
    loss=keras.losses.BinaryCrossentropy(from_logits=True),
    metrics=[keras.metrics.BinaryAccuracy()],
)

epochs = 20
model.fit(train_ds, epochs=epochs, validation_data=validation_ds)

```

**Comment by AbhisekOmkar** [comment]
This is actually an nvcc bug. we are also running into this and reported to nvidia.
Nvidia has fixed this issue in cuda 10.1, but reported that they will not patch 10.0 with the fix.
So uninstall your cuda and re-install with latest version of cuda

**Comment by farazk86** [comment]
> This is actually an nvcc bug. we are also running into this and reported to nvidia.
> Nvidia has fixed this issue in cuda 10.1, but reported that they will not patch 10.0 with the fix.
> So uninstall your cuda and re-install with latest version of cuda

Thanks but I'm already using 11.2 I'm not using 10.0

**Comment by Saduf2019** [comment]
@farazk86 
Can you please try with 11.0 and let us know, with tf 2.4.

**Comment by farazk86** [comment]
> @farazk86
> Can you please try with 11.0 and let us know, with tf 2.4.

OK, so, I tried it now with CUDA 11.0, 11.1, 11.2.2

Ive tried with all above versions and still get the same error :(

**Comment by farazk86** [comment]
Right, so an update, I was finally able to train on GPU.

But I had to downgrade to ``CUDA 10.1``, ``cuDNN 7.6`` and ``tensorflow 2.3``. 

I had to downgrade to make this work but I would really appreciate a solution to this for ``tensorflow 2.4`` and the newer CUDA and cuDNN as I have other frameworks that depend on the latest versions :(

**Comment by Saduf2019** [comment]
@farazk86 
I ran the code on 2.4 and it works fine,please refer to the [gist here](https://colab.research.google.com/gist/Saduf2019/10e31dc3cec9f27676126e56caf9003c/untitled569.ipynb).
As the issue is resolved for you can you please move this to closed status.

**Comment by luckyluke97** [comment]
Any possible solutions?

**Comment by Manouselis** [comment]
Problem was solved for me when I followed the instructions [in this link :](https://www.reddit.com/r/tensorflow/comments/jsalkw/rtx_3090_and_tensorflow_for_windows_10_step_by/)

**Comment by AbhisekOmkar** [comment]
RTX 3090 and Tensorflow for Windows 10 - step by step
I recently bought an RTX 3090 (upgrading from a GTX 1060) and needed my keras/tensorflow notebooks to work. There are some guides on this on the internet, but these were often skipping some steps or explanations, so I wanted to share a very simple, "for dummies" kind of step by step instruction with explanations on how I got it to work on my system. It is similar to this guide, but a bit different as I encountered some problems that was not mentioned in that guide. I am using a Ryzen 2700X and Windows 10 Home.

So, what you need to know beforehand: The NVIDIA 3000 Series GPUs (Ampere) require CUDA v11 and cuDNN v8 to work. The tensorflow versions on anaconda and pip on Windows (currently at max tensorflow 2.3) do not include a tensorflow built with CUDA v11. But you can use pip to install a nightly build of tensorflow (currently tensorflow 2.5) which built with CUDA v11. Apart from a tensorflow build with CUDA v11, you will also need the actual DLLs for CUDA v11 and cuDNN v8. Normally, you would just install these with anaconda with the packages cudatoolkit and cudnn, but while cudatoolkit is available with v11, for cudnn, at least for Windows, v8 is not available in anaconda. The workaround is to manually get these DLLs and set them in the system environment path (so that python/tensorflow can find and load them). So let's start:



First, install anaconda if you haven't already. Open the anaconda prompt with admin rights.

Type conda create -n tf2 python=3.8 and hit enter to create a new anaconda environment with python 3.8 (the tensorflow nightly build needs python 3.8 or higher, that's why we are using python 3.8)

Type activate tf2 or conda activate tf2 and hit enter to enter that new environment.

Install the nightly tensorflow build with pip3 install tf-nightly-gpu

Install other packages that you might need. For me, it's conda install jupyter scikit-learn matplotlib pandas

Now, download CUDA v11 from NVIDIA (https://developer.nvidia.com/cuda-downloads or https://developer.nvidia.com/cuda-toolkit-archive). Yeah, the file is pretty big with 3GB.

Additionally, apparently we also need a Microsoft Visual Studio version for C++ for the installer to run properly. Download the free Visual Studio Community Edition (https://visualstudio.microsoft.com/downloads/) and install the C++ components. For this, select "Desktop development with C++", select the first 6 options and install. This step is taken from the guide I mentioned earlier, so refer to it if you have trouble with this. For me, I already had Visual Studio with C++ in mind set up on my computer, so I could skip this step.

Now, let's first execute the CUDA v11 installer. Execute it. You can do the express installation, but if you already have GeForce Experience installed, you can also choose the Custom option and deselect everything that you already have installed with a higher version. For me, I only needed the very first checkbox with the CUDA options, so that might be enough.

What the CUDA v11 installer basically did was installing all the CUDA v11 DLLs, Headers, and stuff in the directory "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1" (the version may be different for you). What we will do next: Add the cuDNN DLLs, Headers, etc. in this directory as well and then add this directory to the system path. Ok, let's go.

Download cuDNN from NVIDIA (https://developer.nvidia.com/rdp/cudnn-download). This file is around 700MB. You need to register as a developer and answer some questions, but don't worry, it's free. When asked for an email, you can type in any email, since in the next page, you will get an option to login using google or facebook as an alternative (which you may or may not prefer). Once you downloaded the file, extract it. Going into the directory, you will see three folders "bin", "include", "lib". Comparing it with the CUDA v11 directory (C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1), you'll notice that these directories are present there as well! So just copy the folders from cuDNN to the CUDA v11 directory. Windows will add the files into the existing folders.

Now, let's add those directories to the system path. In windows, open start and search for "This PC". Rightclick and select "Properties" to open a Window called "System". On the left side at the bottom, select "Advanced system settings". Click "Environment Variables..." at the bottom. Here, in the lower half, in "System variables", find and open "Path". Here, click "New" to add a new directory to the system path. Do this every time for each of the following directories (as mentioned earlier, the version number may be different for you). Some of the directories may be already listed there, so feel free to skip them (there is no negative effect from double entries though, so don't worry too much):
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\bin
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\libnvvp
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\extras\CUPTI\lib64
C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1\include

Now, very important: Restart your system!

Now, run your code to see if everything works. For me, it was through a jupyter notebook. A simple thing to do first is to import tensorflow and check the physical devices:import tensorflow as tftf.config.list_physical_devices()

Your GPU may not show up. Take a close look at the output of the console (for me, it was the anaconda prompt with which I started up my jupyter notebook). There, you should see logs like tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library cudart64_110.dll or a similar log stating that a certain DLL could not be loaded! In my case, everything loaded except the DLL "cusolver64_10.dll". So, I went to the CUDA v11 directory (C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.1), opened the "bin" folder (the DLLs are in there) to check if that DLL was there. Nope, it was not. Instead, there was "cusolver64_11.dll". So what I did was just copy that DLL and renamed the copy to "cusolver64_10.dll". Yeah, sounds dumb, but after that, everything worked.

I hope this guide helps at least someone. Hopefully, we will get official versions of tensorflow 2.5 and the CUDA/cudnn packages soon so that these kind of workarounds will not be required anymore.



EDIT: Somewhat obvious thing I noticed today: Had a video call running and was using the background removal of NVIDIA Broadcast. Tried to do some inference during the call and it was failing with error messages like Could not create cudnn handle: CUDNN_STATUS_ALLOC_FAILED and tensorflow.python.framework.errors_impl.UnknownError: Failed to get convolution algorithm. This is probably because cuDNN failed to initialize, so try looking to see if a warning log message was printed above.. Well, yeah, that was because NVIDIA Broadcast was running, which itself uses the machine learning capabilities of the GPU. After closing it, things worked normally again. Kind of obvious, but somewhat easy to overlook/forget.

72 Comments

Share

Save

Hide

Report
