### ISSUE TITLE
Configure failed on NFS: Device or resource busy

### ISSUE THREAD

**Issue by shiyemin** [tensorflow/tensorflow#4794]
On Rocks OS (CentOS 6.5) cluster, filesystem is on NFS.

When run "./configure", it failed at "ERROR: /home/shiyemin/.cache/bazel/_bazel_shiyemin/df39eb3667102dfbd2ad9a81b93b57e9/server/.nfs0000000000cdec5400000995 (Device or resource busy).". Then the configuration stoped.

I've seen this error, but never like this. I think maybe "configure" did not kill all sub-processes in time.

And i found it failed at "bazel clean --expunge".

**Comment by tatatodd** [comment]
@shiyemin see the related issue #3652

You probably want to get your bazel output directory onto your local filesystem, rather than NFS.

**Comment by shiyemin** [comment]
@tatatodd This should work, and i will try it latter(some experiments is running).
However, i'm just curious that why everything works fine on "v0.11.0 RC0" but fails on current version.

Thanks very much!

**Comment by tatatodd** [comment]
@shiyemin If your bazel output directory is on NFS, rather than the local filesystem, the build might sometimes work, but very slowly.  So it's possible that things just happened to work previously.

I.e. it's best to ensure your bazel output directory is on the local filesystem, to avoid these problems to begin with, and to have reasonable build times.

I'm closing this out, but feel free to comment or file a new issue if you run into further problems.  Thanks!
