### ISSUE TITLE
Add additive/multiplicative angluar margin loss

### ISSUE THREAD

**Issue by singhularAdi** [tensorflow/tensorflow#47941]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Additive angular margin loss can create highly discriminative embedding appropriate for re-identification and cross-domain instance matching tasks. Such a layer is currently accessible only via third-party implementations.

**Will this change the current api? How?**
Will add a new layer that allows for angular penalties.

**Who will benefit with this feature?**
Anyone working in cross domain instance matching/ identification problems. Additionally, can be used as a stepping stone to implement certain SOTA instance matching architectures.
**Any Other info.**
N/A

**Comment by AbhisekOmkar** [comment]
It's sounds good

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
