### ISSUE TITLE
Huge code size after compile the TFLM hello world example for ARM

### ISSUE THREAD

**Issue by napoleonwar** [tensorflow/tensorflow#48156]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Debian 9
- TensorFlow installed from (source or binary): Source
- Tensorflow version (commit SHA if source): SHA
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): ARM Cortex M33 bare mental (SSE 200)

**Describe the problem**
##########
I want to implement the TFLM into my own ARM board, which has a flash not more than 512KB. And my compiler is arm compiler.  The first step I did is to try the hello world example. I expected a binary file less than 20KB as it says in the website, but my compilation result is 348KB. I don't know how to handle that.

**Please provide the exact sequence of commands/steps when you ran into the problem**
#############
First, I generated a static library by using `make -f tensorflow/lite/micro/tools/make/Makefile TOOLCHAIN=armclang TARGET_TOOLCHAIN_ROOT=/usr/pack/armmisc-201912-tonl/ARMCompiler6.13/bin/ TARGET=cortex_m_generic TARGET_ARCH=cortex-m33 microlite ARMLMD_LICENSE_FILE:=xxx`. Even the generated static library `libtensorflow-microlite.a` is 1.1MB, which is really large compared other issues posted here.
Then, I modified my makefile, adding the lib directory into the dependency,
```
$(OUTPUT_DIR)/$(BUILD_S_NS)/$(TEST_NAME).elf:	$(CPU_MCU_OBJ) $(MICROLITE_LIB_PATH)  
	@set -euo pipefail;\  
	echo "Making $@ ...";\  
	mkdir -p $(@D);\  
	export ARMLMD_LICENSE_FILE=$(ARMLMD_LICENSE_FILE);\
	$(LD) $(LDFLAGS) -o $@ $^ > $@.log`
```
I also changed the ops from `all_ops_resolver` to `micro_mutable_op_resolver.h`, and modified the code in `main_function.cc hello_world_test.cc` to 
```
// static tflite::AllOpsResolver resolver;
  
  static tflite::MicroMutableOpResolver<1> micro_op_resolver(error_reporter);
  if (micro_op_resolver.AddFullyConnected() != kTfLiteOk) {
    return;
  }

```
The `CPU_MCU_OBJ` includes the five source code which should be compiled, `main.cc main_functions.cc models.cc constants.cc output_handler.cc`.  It will generate `.elf .hex .disass .map`, I really care about the size of `.hex` file, which is 348KB, far more larger than it indicated less than 20KB in the website.

**Comment by napoleonwar** [comment]
@ymodak @saikumarchalla Is there anyone can give me some hint?

**Comment by NatakuG** [comment]
Hi, I have maybe the same issue. 

I am currently trying the example Hello World on **Zephyr OS**.

#################################################

The example code takes **157kB** of **FLASH** memory. 

- From original example code:

        Memory region         Used Size  Region Size  %age Used
           FLASH:      157376 B         1 MB     15.01%
            SRAM:       19112 B       448 KB      4.17%
           SRAM1:          0 GB        64 KB      0.00%
        IDT_LIST:          0 GB         2 KB      0.00%

I first thought it was the size of the model, so I take away the entire model on purpose, then I get the result of **140kB**, which indicates the TF Lite for Micro itself takes the most of the space rather than the model. 

- From the code without model (_model.cc/model.h_)

        Memory region         Used Size  Region Size  %age Used
           FLASH:      140376 B         1 MB     13.39%
            SRAM:       10792 B       448 KB      2.35%
           SRAM1:          0 GB        64 KB      0.00%
        IDT_LIST:          0 GB         2 KB      0.00%
#################################################

Plus: The `.hex` file also takes **442kB** in this case. On the contrary, `.hex` only takes around **52kB** when without TensorFlow in this case.

#################################################

Is there any solution for this?

**Comment by napoleonwar** [comment]
@NatakuG it looks like no answer until now, and I do not know how to handle it :)

**Comment by NatakuG** [comment]
Hi all,

I find the answer on my side.

On the TensorFlow guide website: https://www.tensorflow.org/lite/microcontrollers/library

- It says:
> all_ops_resolver.h or micro_mutable_op_resolver.h can be used to provide the operations used by the interpreter to run the model. Since all_ops_resolver.h pulls in every available operation, it uses a lot of memory. In production applications, you should use micro_mutable_op_resolver.h to pull in only the operations your model needs.

And in my code, I'm using:

	static tflite::MicroMutableOpResolver<4> resolver;

Instead of:

	XXX static tflite::AllOpsResolver resolver; XXX

And then add the operations that I need, for example:

	resolver.AddFullyConnected();

Here's the result, it drops to 5% of FLASH:

        Memory region    Used Size  Region Size  %age Used
           FLASH:       52432 B         1 MB      5.00%
            SRAM:       16976 B       448 KB      3.70%
           SRAM1:          0 GB        64 KB      0.00%
        IDT_LIST:          0 GB         2 KB      0.00%

@napoleonwar I hope this can help you on your side too

**Comment by sanatmpa1** [comment]
@napoleonwar,

Can you take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/48156#issuecomment-858452541) by @NatakuG, and let us know if it helps in resolving your issue? Thanks!
