### ISSUE TITLE
Neural Network Exchange Format (NNEF)

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#4815]
Do you want to support and contribute to the standardizzation of provisional [NNEF](https://www.khronos.org/nnef) effort by Kronos Group? Google is still in the [promoter member list](https://www.khronos.org/members/member_list)

**Comment by tatatodd** [comment]
Thanks for filing the issue @bhack 

Seeing as NNEF is the the proposal/design phase, there isn't a specific feature for us to implement at this time.  We may revisit this in the future.

**Comment by bhack** [comment]
I know that it is provisional but my issue was also about if you plan to take part to this process as Kronos member. Can you reply me to this point?

**Comment by yaroslavvb** [comment]
IMHO standard is hard to make useful at this point since the set of useful neural network primitives is changing so fast. Two years ago people wouldn't have thought about adding GRU unit, a year ago people would miss some neural attention primitives, and next year there may be categorically new ops or ops that unify existing ops redundant. Like with ReLU -> ReLU6 -> ReLUN, then ReLUN with trainable N which technically makes all other versions of ReLU redundant. So a standard would end up either missing someone's favorite primitive, or grow so large that it's not practical to be implemented by everyone

**Comment by bhack** [comment]
Yes in this field standards will be always behind state of the art. So a standard can evolve on research sediments. If we not start in some way will leave only margin for near metal de facto (closed) standard like cudnn the in some way it is dictacting low level interfaces.

**Comment by yaroslavvb** [comment]
@zstone

**Comment by bhack** [comment]
I see this as an opportunity to start a collective effort for finding a subset of what research is cooking in different burners and what it is "ready" for eating at inference and that impact near metal production (open or closed source). I think that a multi stakeholder effort for finding an agreement to update the standard one or two times at year could be feasible. /cc @fchollet

**Comment by biolee** [comment]
is there any update on this?
