### ISSUE TITLE
Dataset random state not saved in checkpoint when reshuffling each iteration

### ISSUE THREAD

**Issue by keyonvafa** [tensorflow/tensorflow#48178]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.4.1
- Python version: 3.9.2
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.2
- GPU model and memory: NVIDIA Titan V

**Describe the current behavior**
I am creating a dataset with
``` python
dataset = tf.data.Dataset.from_tensor_slices((np.arange(5)))
dataset.shuffle(5, reshuffle_each_iteration=True)
dataset = dataset.batch(5)
...
for epoch in range(1000):
  iterator = iter(dataset)
```
I am saving this dataset as part of a checkpoint after every epoch. When I stop training, load the checkpoint, and create an iterator for a new epoch from the dataset, the batch is not the same as if I had kept training. Instead, it uses the global random seed, so the iterator is identical to the iterator from the very first epoch.

**Describe the expected behavior**
The dataset random state should be held over. That is, when an iterator is created from this dataset, it should be identical to if I had never stopped training.

**Standalone code to reproduce the issue**
https://gist.github.com/keyonvafa/2120c836a71dd783f7da0e73116681b6

At the first iteration, this prints: tf.Tensor([1 3 2 4 0], shape=(5,), dtype=int64). When we stop training and restore a checkpoint, it will go back and print the same thing. Removing the global random seed would fix this but the code would no longer be reproducible between runs.

Thank you!

**Comment by rmothukuru** [comment]
@keyonvafa,
When trying to reproduce your code, I've encountered with the error:

```
FATAL Flags parsing error: Unknown command line flag 'f'
Pass --helpshort or --helpfull to see help on flags.
An exception has occurred, use %tb to see the full traceback.

SystemExit: 1
```
 Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/ab554b889210447eeca8dbbc075d41d4/gh_48178.ipynb). Can you please help us reproduce the error? Thanks!

**Comment by keyonvafa** [comment]
Thank you for looking into it. It looks like `absl` doesn't work well with Colab, so I have removed it and can reproduce the issue:

https://colab.research.google.com/gist/keyonvafa/cc3927fb7d9a0ea955e34219f605d4b8/gh_48178.ipynb

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210603,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/08f26bc2483ca5cdd6e7c98fbf1bfb3c/untitled210.ipynb#scrollTo=HMKx35b6dVIJ)..Thanks !

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
