### ISSUE TITLE
FP16 support for grouped convolutions

### ISSUE THREAD

**Issue by BearNinja123** [tensorflow/tensorflow#48176]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently, grouped convolutions (at least for Conv2D) doesn't see any speedup from FP16 training, although memory usage is still lowered training in FP16. When doing a mixed precision test, running tf.nn.conv2d and K.conv2d with grouped convolutions in FP16 has equal performance to FP32 and running the same operations without groups (same number of input/output channels) has about an 80% speedup in FP16.

**Will this change the current api? How?**

**Who will benefit with this feature?**

**Any Other info.**

**Comment by rmothukuru** [comment]
@BearNinja123,
Couple of points:
1. Documentation of `Mixed Precision` states: 

> While mixed precision will run on most hardware, it will only speed up models on recent NVIDIA GPUs and Cloud TPUs. NVIDIA GPUs support using a mix of float16 and float32, while TPUs support a mix of bfloat16 and float32.
> 
> Among NVIDIA GPUs, those with compute capability 7.0 or higher will see the greatest performance benefit from mixed precision because they have special hardware units, called Tensor Cores, to accelerate float16 matrix multiplications and convolutions.

Can you please confirm if you are using latest `GPU` with `Compute Capability` 7.0 or higher?

2.  Can you please try using [tf.keras.layers.Conv2D](https://www.tensorflow.org/api_docs/python/tf/keras/layers/Conv2D) and confirm if you are experiencing the same `performance` (because this API is more active compared to the ones you specified)?

Thanks!
