### ISSUE TITLE
[XLA PjRT] Ongoing progress and future plan of PjRT distributed runtime

### ISSUE THREAD

**Issue by ymjiang** [tensorflow/tensorflow#48210]
Hi TF developers, 

This issue intends to get more knowledge about the ongoing and future plan of XLA PjRT, especially on the distributed runtime of GPU.

Although there are some related commits (e.g., 44e771aa50ad8be454b7f4469ad04a815d03cca1 and 8a72c4466a0f44de9bd1cfbf47a701727731036c), existing PjRT code seems quite preliminary in supporting distributed training on multiple hosts -- As far as I could see, it now only provides basic control operations such as setting up the connections and sharing GPU topology, and it is not trivial to run a real distributed demo with communication.  Another issue https://github.com/google/jax/issues/2731 seems also aligns with this point. 

So I would like to confirm if TF team is also working on this and may probably release some new features soon. For now, our   interest is on using PjRT to run HLO with collective or P2P communication, possibly including all-reduce, all-gather, reduce-scatter, send/recv, etc.

Any response will be appreciated. Thanks.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
