### ISSUE TITLE
Loading multiple Models over different Processes

### ISSUE THREAD

**Issue by lvlanson** [tensorflow/tensorflow#48232]
I am creating a GUI for handling neural nets using Keras.

I run, save and load models in different processes (multiprocessing.Process). I assumed the global state of tensorflow is being cleaned up after the process is being terminated. This works so far well when running and saving the models in different processes.

Somehow when I load a net and the process terminates, somehow the global variables start blocking tensorflow again.

What is a good approach working with multiple models with tensorflow 2. I have found approaches for Tensorflow 1, but a good approach for tensorflow 2 I have not found yet.

It is quite hard to provide a code snippet, since I only need a good solution working with different models and my project is quite complex.

**Comment by ymodak** [comment]
Perhaps [tf.compat.v1.reset_default_graph](https://www.tensorflow.org/api_docs/python/tf/compat/v1/reset_default_graph) can work in your case.

**Comment by lvlanson** [comment]
Thanks for your response. This does not work.

I called tf.compat.v1.reset_default_graph() before exiting the process where the net has been loaded. Other processes are still being blocked.

**Comment by lvlanson** [comment]
What I am actually doing in the subprocess is the following:

`        with tf.keras.utils.custom_object_scope(custom_objects):

            with open(path_net_config, "r") as f:
                loaded_config_yaml = yaml.full_load(f)

            if name_base_class == "Sequential":
                model = tf.keras.Sequential().from_config(loaded_config_yaml)
            elif name_base_class == "Model":
                model = tf.keras.Model().from_config(loaded_config_yaml)
            else:
                return None
            model.load_weights(path_weights)

        weights = model.get_weights()`

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
