### ISSUE TITLE
Broken syntax highlighting on docs that render python notebooks.

### ISSUE THREAD

**Issue by dansuh17** [tensorflow/tensorflow#48234]
tensorflow/docs related.

## URL(s) with the issue:

Code example for `MultiHeadAttention` at:

https://www.tensorflow.org/tutorials/text/transformer?hl=en#multi-head_attention

and code example at:

https://www.tensorflow.org/tutorials/text/image_captioning?hl=en#create_a_tfdata_dataset_for_training

### Clear description

I actually wasted some amount of time for my own stupidity, but there seems to be a glitch in the syntax highlighting system for notebooks rendered on the docs.

It seems that the syntax highlighter parses `//` as comments in python code blocks, not [`floordiv`](https://docs.python.org/3/library/operator.html#operator.floordiv), which it actually means.

This actually may cause some amount of confusion, especially for people coming from c++ world like myself 
who tend to eye-parse away the `//` as comments and the broken syntax highlighter is encouraging this (+ it looks so natural!).

### Request visuals, if applicable

![image](https://user-images.githubusercontent.com/14329563/113301809-5f3ab000-933a-11eb-82e9-251e0f514af1.png)

![image](https://user-images.githubusercontent.com/14329563/113301852-6a8ddb80-933a-11eb-80a7-1edf624f5047.png)

Also in dark mode:

![image](https://user-images.githubusercontent.com/14329563/113302147-bc366600-933a-11eb-8569-f61efa84de73.png)

**Comment by mbalayil** [comment]
When the Jupyter notebooks are rendered as HTML, for python code, `lang-python` CSS class is used for the `<pre>` block instead of `lang-py`. The `prettify` library used at https://www.tensorflow.org/tutorials understands python code as `lang-py` (https://github.com/tensorflow/docs/blob/master/tools/tensorflow_docs/api_generator/parser.py#L503 - `lang-py` is used correctly when generating API documentation). When `prettify` doesn't recognize the language identifier, it falls back to `default-code` lexer which ends up being used when `lang-python` is specified (floor division operator is probably being interpreted as a _C style comment_).

When the underlying JavaScript function is invoked from the Google Chrome Developer Console with the correct language identifier, the generated output is correct as shown by the following snippet.
```
> window.prettyPrintOne('self.depth = d_model // self.num_heads', 'python')
"<span class="kwd">self</span><span class="pun">.</span><span class="pln">depth </span><span class="pun">=</span><span class="pln"> d_model </span><span class="com">// self.num_heads</span>"

> window.prettyPrintOne('self.depth = d_model // self.num_heads', 'py')
"<span class="pln">self</span><span class="pun">.</span><span class="pln">depth </span><span class="pun">=</span><span class="pln"> d_model </span><span class="pun">//</span><span class="pln"> self</span><span class="pun">.</span><span class="pln">num_heads</span>"
```

I could not find any information on how this repo is converted to the full fledged site at https://www.tensorflow.org/tutorials or how the Jupyter notebooks are converted to HTML. This change probably needs to happen in that converter.

**Comment by lamberta** [comment]
Unfortunately, tensorflow.org (and others) use a version of [code-prettify](https://github.com/googlearchive/code-prettify) and that project is now archived. There are no plans to upgrade, at this time. Sorry
