### ISSUE TITLE
PIP install OS X, requirement to install

### ISSUE THREAD

**Issue by Hnri** [tensorflow/tensorflow#4828]
Today I tried to install TensorFlow on my MacBook pro following the guidelines on [tensorflow.org](https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#installing-from-sources).

Operating System: OS X 10.11.6
Pip: 8.1.2 (python 3.5)
My MBP doesn't have an actual GPU so I tried using the CPU only version: [link](https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc0-py3-none-any.whl)

When trying to run `sudo -H pip3.5 install --upgrade $TG_BINARY_URL`
Pip logged `You must give at least one requirement to install (see "pip help install")`

I'm pretty new to pip, is there something obvious that I'm missing ?

**Comment by tatatodd** [comment]
@Hnri that error indicates that the TF_BINARY_URL bash variable is empty.  The pip-install instructions are here:
https://www.tensorflow.org/versions/r0.11/get_started/os_setup.html#pip-installation

Specifically, you're supposed to run these two lines:
```
export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.11.0rc0-py3-none-any.whl

sudo pip3 install --upgrade $TF_BINARY_URL
```

The first line exports the TF_BINARY_URL variable, while the second line does the pip install.

Closing this out, since I believe that should fix your problem.  If not just comment on this issue.  Thanks!

**Comment by Hnri** [comment]
That worked like magic, thank you!

**Comment by BeautifulTommorow** [comment]
tanx
