### ISSUE TITLE
Do TensorFlow probability (TFP) layers have a similar class like `tf.keras.layers.Layer` , if yes please share. 

### ISSUE THREAD

**Issue by rrklearn2020** [tensorflow/tensorflow#48295]
**System information**
- TensorFlow version (you are using): 2.4 (binary)

**Describe the feature and the current behavior/state.**
`tf.keras.layers.Layer` -> class from which all layers inherit.

Do TensorFlow probability (TFP) layers have a similar class, if yes please share. 

**Who will benefit from this feature?**
Users of TFP who would like to inherit the base class and add their own layers.

**Comment by jvishnuvardhan** [comment]
@rrklearn2020 [Here](https://github.com/tensorflow/probability/tree/master/tensorflow_probability/python/layers) are the layers in `tfp`. Thanks!

Please post `TFP` related issues in [`TFP` repository](https://github.com/tensorflow/probability/issues) so that `TFP` experts will respond and resolve issues. Thanks!
