### ISSUE TITLE
Training Operations Dependencies 

### ISSUE THREAD

**Issue by NoraAl** [tensorflow/tensorflow#48313]
**System information**
- TensorFlow version: 2.4.1
- Are you willing to contribute it (Yes/No): Yes when published 

**Description**
I am trying to add a feature that enhances the optimization performance and it can be done in two ways:
1. Creating custom optimizers: by inheriting  [optimizer_v2](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/optimizer_v2/optimizer_v2.py#L290-L302) 
2. Extending existing optimizers

I just implemented the first option and it works just find, now I need to add the feature to existing optimizers to measure the performance enhancement, e.g. SGD and Adam. I started with ([tensorflow/tensorflow/core/kernels/training_ops.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/training_ops.cc) &  [training_ops.h](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/training_ops.h)) but then I realized that there are many files that need to be changed. 
In particular, I need to add functions like [ApplyGradientDescent](https://github.com/tensorflow/tensorflow/blob/68e6c8da5a56b4895114ec47fc6aeccb8027de88/tensorflow/core/kernels/training_ops.h#L32).
Can I get a list of files (including build files and wrappers) that need to be changed to get such function working?

Thanks,

**Comment by NoraAl** [comment]
Any update?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
