### ISSUE TITLE
I am unable to install Tensorflow on my mac without Virtual Environment, how can I fix this

### ISSUE THREAD

**Issue by Prashant-Kesharwani** [tensorflow/tensorflow#48327]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**
>>> import tensorflow as tf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'tensorflow'

**Provide the exact sequence of commands / steps that you executed before running into the problem**

**Any other info / logs**
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached.

**Comment by Saduf2019** [comment]
@Prashant-Kesharwani 
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced]

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

You can check the following as well:
What is make/model of your cpu?
I suspect your cpu model does not support AVX instructions sets.See [hardware requirements](https://www.tensorflow.org/install/pip?lang=python3#hardware-requirements)
Make sure to download the latest microsoft [visual c++ redistributable from here](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0).
.Also, please follow the instructions from to install from [Tensorflow website](https://www.tensorflow.org/install/source_windows).

Please, check Your CPU/Python is on 32 bits?

Please, refer similar issue #39007
#41022, [link](https://github.com/tensorflow/tensorflow/issues/46362#issuecomment-759368982),#44291,#47140, #37525, #43459, #44130

**Comment by Prashant-Kesharwani** [comment]
Thank you so much for your response, earlier when even I updated Python and then tried installing it, it didn't work.
Now, after updating python it started working and finally I am able to install it,.

**Comment by Saduf2019** [comment]
@Prashant-Kesharwani 
Thank you for your response, glad your issue is resolved.
