### ISSUE TITLE
How can I train tensorflow model to take specific rows of historical training data in each training iteration that is related to current row?

### ISSUE THREAD

**Issue by khaled-alkilane** [tensorflow/tensorflow#48326]
I have a buses dataset between stations with the entering time for each stop. Each row has information about the bus current station including (time entering this station, long/lat, date, and also the target station with its arrival time and distance(I add a sample of data below). What I want to do is to estimate the bus arrival time to any of the following station in the route. Since the data is not recorded with time-stamp I can't use LSTM to train the model using the previous window time(for example two hours before). How can I train the model for each link between two stops with only historical records that are two hours before. Any idea to build a training function that takes the previous links with two hours before from the data as the batch size.
![Screenshot from 2021-04-06 16-19-14](https://user-images.githubusercontent.com/60028253/113696247-53693800-9704-11eb-9925-2b4d347cf453.png)

**Comment by tilakrayal** [comment]
@khaled-alkilane 

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:

and the the exact sequence of commands / steps that you executed before running into the problem

Thanks!
