### ISSUE TITLE
MultiWorkerMirroredStrategy:Training is slow with 50 workers

### ISSUE THREAD

**Issue by Mullich123** [tensorflow/tensorflow#48324]
I am trying to use 50 workers to train my model and made it.However,training is very slow.I'd like to know if there are some tips to 
improve the performance in terms of reducing training time.I would appreciate it if you could give me some advice.

**Comment by Saduf2019** [comment]
@Mullich123 

Please provide details about what platform you are using (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?

Make sure you also include the exact command if possible to produce the output included in your test case. If you are unclear what to include see the issue template displayed in the[ Github new issue template.](https://github.com/tensorflow/tensorflow/issues/new)

We ask for this in the issue submission template, because it is really difficult to help without that information. Thanks!

**Comment by Mullich123** [comment]
Thanks for you reply,I've got some tips on Tensorflow tutorial and it's sorry to trouble you for my carelessness.I will change next time.

**Comment by Saduf2019** [comment]
@Mullich123 
Its absolutely no issues, please let us know the issue faced and share details for us to help.

**Comment by Mullich123** [comment]
Sorry I am a newbie in Tensorflow2.Could you please delete this issue.

**Comment by Saduf2019** [comment]
@Mullich123 
Please confirm if your issue is resolved.

**Comment by Mullich123** [comment]
Good night

I'm so sorry.It's my default.I raised the issue in a wrong way.By debugging my code
and referencing tutorials,I found I knew too little.In term of the issue,I use 50 ports
of localhost to do experiment and make it ambiguous.So please delete it and I would&nbsp;
raise another questions carefully.


Yours Sincerely,
Mr. Mullich
