### ISSUE TITLE
What is the diference between NNAPI, GPU and Hexagon delegates

### ISSUE THREAD

**Issue by limdlh** [tensorflow/tensorflow#48349]
Could anyone describe the diference between NNAPI, NPU, GPU and Hexagon delegates?
Does it means NNAPI will use one delegate in NPU, GPU or Hexagon(DSP) according to device? If device only embedded GPU, NNAPI will use GPU; if device only embedded DSP, NNAPI will use DSP; and so on?
Or does NNAPI only use NPU delegate?

Thank you so much~

**Comment by abattery** [comment]
@srjoglekar246 @karimnosseir could you take a look at this question?

**Comment by karimnosseir** [comment]
These are different types of TFLite delegates.
I will try to explain below - and provide pointers. Please let me know if you have more questions.


* What is TFLite Delegate ?
TFLite delegates is a way to take part/all of the TFLite graph and execute it differently - in other words delegate the execution to something other than the default TFLite CPU kernels.

* Why use TFLite Delegates ?
Recently hardware vendors have specialized hardwares that can execute ML operations (or matrix operations) in an optimized way. Utilizing these specialized hardwares can benefit inference speed and power consumption.

* What types of delegates does TFLite offers currently ?
There are types that are maintained by the TFLite team and others available open source (or closed source) that leverage TFLite Delegate framework.
Note: You can search for types of delegates available online to use. Here below i will summarize the different delegates maintained by the TFLite team and you can find the code in the TF repo.


- NNAPI Delegate:
This delegate is available only on Android devices starting Android 8.1 (API level 27).
This delegate uses Android Neural Network API which can accelerate the execution on different hardwares including GPU, DSP or NPU.
Note that, although NNAPI can accelerate on GPU, or DSP it is not similar (exact) to the GPU delegate or Hexagon DSP delegate.
For more information and instructions on how to run it see the [guide](https://www.tensorflow.org/lite/performance/nnapi).

- GPU Delegate:
This delegate supports running on OpenCL and OpenGL. It can run on Android or iOS.
See [guide](https://www.tensorflow.org/lite/performance/gpu) for more information on using it.

- Hexagon Delegate:
This Delegate uses Hexagon NN framework which allows running ML operations on the Snapdragon Hexagon DSP.
It is available on Android and can be run also on non-android devices (e.g. Linux on Arm)
See the [guide](https://www.tensorflow.org/lite/performance/hexagon_delegate) for more information.

- CoreML Delegate:
This delegate runs only on iOS since it leverages apple CoreML to accelerate on Apple's Neural engine.
See the [guide](https://www.tensorflow.org/lite/performance/coreml_delegate) for more information.



Every delegate has their own requirements, for example Hexagon DSP delegate runs only quantized models while GPU delegate can run floating point models.
For details about what each delegate support, please see this [section](https://www.tensorflow.org/lite/performance/delegates#delegates_by_model_type)


Hope that helps.

Thanks

**Comment by limdlh** [comment]
Thank you for your answer, it help me much.
By the way, if I want to use NPU, now I could only use NNAPI?

**Comment by limdlh** [comment]
Hi karimnosseir, sorry to trouble you, that I have another question:
I want to use Hexagon libraries in 64bit, but I could only get 32bit lib from [TFLite org link](https://www.tensorflow.org/lite/performance/hexagon_delegate?hl=zh-cn).
I did download tflite_hexagon_nn_skel_v1.20.0.1.run, and use it to download Hexagon libraries.
Should I download from other link, or just use 32bit in 64bit device?

**Comment by limdlh** [comment]
@karimnosseir  Thank you for your answer, it help me much.
By the way, if I want to use NPU, now I could only use NNAPI?

**Comment by srjoglekar246** [comment]
@limdlh Yes, for newer Android devices that should be the case.

**Comment by limdlh** [comment]
@srjoglekar246 What about XNNPACK ? What does it represent?

**Comment by srjoglekar246** [comment]
@limdlh XNNPack is a delegate that implements some CPU optimizations, especially for sequences of heavy ops like MatMul, Conv etc. So its not exactly a hardware delegate, but runs on CPU. See [this blog post](https://blog.tensorflow.org/2020/07/accelerating-tensorflow-lite-xnnpack-integration.html) for an explanation of how to try it.

**Comment by suraj-maniyar** [comment]
Hello @srjoglekar246 
From this [link](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md), it says that: 
**XNNPACK engine used by TensorFlow Lite interpreter uses a single thread for inference by default**
Could you give some overview on how this is done? For example, if I want to run regular TensorFlowLite on single thread, will that be feasible? How is TFLite with xnnpack engine different from regular TFLite runtime that makes it easy to run on single thread?

Thanks.

**Comment by srjoglekar246** [comment]
We haven't enabled XNNPack by default yet. So you should be running TFLite w/ single-threaded CPU kernels by default as of now.

With XNNPack, some parts of the TFLite graph with CONV/FULLY_CONNECTED etc will get replaced by a single XNNPack kernel that performs the equivalent task but faster. XNNPack runs faster if you set num threads higher with TFLite.

**Comment by suraj-maniyar** [comment]
@srjoglekar246 I may be missing something here. Could you please clarify :
I am running inference on CentOS 8 linux x86_64 architecture. And based on this [part](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/xnnpack/README.md#enable-xnnpack-via-bazel-build-flags-recommended-on-desktop) 
```
When building TensorFlow Lite with Bazel, add --define tflite_with_xnnpack=true, and the TensorFlow Lite interpreter 
will use XNNPACK engine by default.
```

I did build TFlite with --define tflite_with_xnnpack=true. Will this not run on single thread?

**Comment by srjoglekar246** [comment]
This will run w/ XNNPack & a single thread, yes. I did not realize you were building with that `--define`

**Comment by suraj-maniyar** [comment]
That's good to know. Thanks.

But based on your previous comment : 
> We haven't enabled XNNPack by default yet. So you should be running TFLite w/ single-threaded CPU kernels by default as of now.

Does TFLite still run single threaded even if XNNPack is not enabled?

I am asking this in context of a program that I am currently trying to run. It uses forking to create multiple processes to do inference. Currently, when I used default TFlite, it gets stuck in mutex lock. That's why I want to confine TFLite runtime to a single thread.
Note it also uses flex delegate if that is relevant information to this problem.

**Comment by srjoglekar246** [comment]
> Does TFLite still run single threaded even if XNNPack is not enabled?

Yup, atleast for TFLite builtin ops. However, I am not sure if flex uses multiple threads. @abattery do you have an idea?

Also, are you using the same Interpreter from multiple threads? TFLite doesn't support that, you will need a new Interpreter for each concurrent thread. It might be a good sanity check to run some mobilenet model in your framework (since it has only TFlite builtin ops) and see if things work without issues.

**Comment by suraj-maniyar** [comment]
> Also, are you using the same Interpreter from multiple threads? TFLite doesn't support that, you will need a new Interpreter for each concurrent thread.

I am not sure I understand this completely. I specify only 1 thread when creating InterpreterBuilder, something like this : 
```
tflite::InterpreterBuilder(*flat_buffer_model, builtins)(&interpreter, 1);
```
Do you mean every child process that is forked should have its own new Interpreter instance?
My model is, in fact, mobilenetv2 which is getting stuck in lock condition.

**Comment by srjoglekar246** [comment]
The Interpreter's kernels will use only single threaded inference in your case. However, you mentioned that you use multiple processes for inference:

> I am asking this in context of a program that I am currently trying to run. It uses forking to create multiple processes to do inference.

Are all of these processes using the same Interpreter instance? or different ones?

**Comment by suraj-maniyar** [comment]
@srjoglekar246 
I am using a code written by someone else, but with some debugging I believe all the processes **are** using the same interpreter instance. And now I understand from your previous comment, that TFLite doesn't support that.
So I suppose you are suggesting me to create a new Interpreter instance for every process. That's very helpful to know.
