### ISSUE TITLE
retrain.py input PNG picture

### ISSUE THREAD

**Issue by shaolinkhoa** [tensorflow/tensorflow#4840]
Hi all, 

I try to change the retrain.py from jpeg to png so that I can input the png image. ( replace "jpeg" in the code to "png")

but I got the error **'Requested return_element %r not found in graph_def.' % name)
ValueError: Requested return_element 'DecodePng/contents:0' not found in graph_def.**

How to fix it ? 
I try **input_map={'DecodePng:0': decoded_png}** in **tf.import_graph_def** but **decoded_png** locate under the **create_inception_graph()** so I don't know where is the **decoded_png** to add with **"DecodePng:0"** 

thank you and regards,
Khoa

**Comment by shaolinkhoa** [comment]
Hi, I fixed it and it run
[retrain.txt](https://github.com/tensorflow/tensorflow/files/518028/retrain.txt)

would you mind checking it

thank you and regard,
Khoa

**Comment by jart** [comment]
This [StackOverflow answer](http://stackoverflow.com/a/34497833) should provide some help.

Basically, you don't need to use PIL. There's an op for decoding PNG files. https://www.tensorflow.org/versions/r0.11/api_docs/python/image.html

Another thing you can do is use ImageMagick on the command line to `convert foo.png foo.jpg`.

**Comment by Dagalaki** [comment]
Hi!

@shaolinkhoa Thanks for your code, it helped me as well.

Still, @jart I would like to understand how to fix it according to the Stackoverflow answer using the tf.image.decode_png

I changed the code on lines 615, 616 of add_input_distortions definition, so as to apply decode_png
Then according to Stackoverfow I have to edit the import_graph_definition to apply the input_map

The code to change should be the following in create_inception_graph (line 249):

bottleneck_tensor, jpeg_data_tensor, resized_input_tensor = (
          tf.import_graph_def(graph_def, name='', return_elements=[
              BOTTLENECK_TENSOR_NAME, JPEG_DATA_TENSOR_NAME,
              RESIZED_INPUT_TENSOR_NAME]))

So, in that case I cannot put the input map inside this definition because it will give an error that tensor is used before assignment. 

I guess my question might seem stupid, but as I am totally new, I would appreciate some help on how to make it work that second way.

Thanks in advance.. !

**Comment by jart** [comment]
@Dagalaki We hope you've been enjoying TensorFlow so far! I wish I could answer your question, but we try to keep this issue tracker limited to bugs and feature requests. We rely on the [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) community to provide support on using TensorFlow. I recommend redirecting your question there.

**Comment by Dagalaki** [comment]
Thanks @jart ! I will ask StackOverflow community

**Comment by yutao256258** [comment]
hallo @Dagalaki , have you fixed the problem mit using using the tf.image.decode_png, i have the same problem as yours, if you have the answer, could you please help me, thanks
