### ISSUE TITLE
Tensorflow error messages are verbose, frustrating and hard to understand

### ISSUE THREAD

**Issue by kaelzhang** [tensorflow/tensorflow#48462]
I run into weird and verbose errors that are hard to understand all the time, and it always takes me tons of time to debug into it, however actually, even debugging is also frustrating. 

I don't know if other people feel the same.

I'm not actually talking about some specific type of error messages and it is a common issue which might be blamed to the computation graph tensorflow builds and causes that `model.fit` could lead to tons of types of errors.

I hesitated for a long time, thinking about whether I should submit it here as an issue.

### Expectation

- The error stacks should not always from `model.fit`
- `ValueError: in user code:` should list real **user code** instead of verbose and detailed implementation of keras. There might be some mechanism to track the execution of graph flow and show users the root cause.

**Comment by tilakrayal** [comment]
@kaelzhang ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem.

Thanks!
