### ISSUE TITLE
Possible race condition in nccl_manager_test

### ISSUE THREAD

**Issue by kevint324** [tensorflow/tensorflow#48474]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/nccl/nccl_manager_test.cc#L157

``in_cpu`` is not referenced and goes out of scope (line 159) right after the ``stream->ThenMemcpy`` is called

The source cpu buffer may become invalid before the actual H2D memory transfer start.

This test failed in our in-house platform. I'm not sure why this test seems fine on tensorflow's CI.  That piece of code looks buggy to me though.

Thanks
Kevin

**Comment by UsharaniPagadala** [comment]
@kevint324 
Could you please fill the issue template

In order to expedite the trouble-shooting process, could you please provide the following details

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory

and the exact sequence of commands / steps that you executed before running into the problem. Thanks!

**Comment by UsharaniPagadala** [comment]
@kevint324 

Hi, Can you provide the above requested details.Thanks

**Comment by kevint324** [comment]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): UBUNTU18
TensorFlow installed from (source or binary): from source
TensorFlow version: 2.4.1
Python version: 3.6
Installed using virtualenv? pip? conda?: virtualenv
Bazel version (if compiling from source): 3.1
GCC/Compiler version (if compiling from source): 7.5
CUDA/cuDNN version:n/a
GPU model and memory: n/a

The test failed on our in house platform.
I'd be happy to submit a PR to fix it but maybe someone  could confirm whether it's a valid issue first.
It is pretty straight forward just by reviewing the code.

**Comment by sanjoy** [comment]
Hi @kevint324,

This is a valid issue, please send a PR.

This is passing on our internal CI likely because in this case the NVIDIA memcpy implementation is coping the CPU memory into a staging area at memcpy enqueue time, hiding this problem.

**Comment by tilakrayal** [comment]
@kevint324,
Could you please take a look at the **nccl_manager_test.cc** file where the changes has been changed.

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/nccl/nccl_manager_test.cc#L157

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

Thank you!
