### ISSUE TITLE
einsum with ellipsis is slow

### ISSUE THREAD

**Issue by reisertm** [tensorflow/tensorflow#48484]
Please go to Stack Overflow for help and support:

https://stackoverflow.com/questions/tagged/tensorflow

If you open a GitHub issue, here is our policy:

1.  It must be a bug, a feature request, or a significant problem with the
    documentation (for small docs fixes please send a PR instead).
2.  The form below must be filled out.
3.  It shouldn't be a TensorBoard issue. Those go
    [here](https://github.com/tensorflow/tensorboard/issues).

**Here's why we have that policy**: TensorFlow developers respond to issues. We want to focus on work that benefits the whole community, e.g., fixing bugs and adding features. Support only helps individuals. GitHub also notifies thousands of people when issues are filed. We want them to see you communicating an interesting problem, rather than being redirected to Stack Overflow.

------------------------

### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: No
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: ubuntu 16-20
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**:N/A
-   **TensorFlow installed from (source or binary)**: N/A
-   **TensorFlow version (use command below)**: 2.4.1
-   **Python version**: 3.5-3.8
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**:
-   **GPU model and memory**:
-   **Exact command to reproduce**: see https://colab.research.google.com/drive/14pGREWEo2zd4j5jDJIxEERfNcpLBGuvv?usp=sharing

### Describe the problem
Runtime of einsum heavily depends on the usage of an ellipsis (Both on GPU and CPU)
```python
a = tf.random.normal([100,32,32,32,3])
e = tf.random.normal([100,3,3])

x=timer()
R = tf.einsum('b...l,blr->b...r',a,e)
print(timer()-x)
# output: 0.28

x=timer()
R = tf.einsum('bijkl,blr->bijkr',a,e)
print(timer()-x)
# output: 0.0008
```

### Source code / logs
https://colab.research.google.com/drive/14pGREWEo2zd4j5jDJIxEERfNcpLBGuvv?usp=sharing

**Comment by kkimdev** [comment]
Thanks for filing this.  FYI here is the implementation `third_party/tensorflow/core/kernels/linalg/einsum_op_impl.h`.  Marking contribution welcome.

**Comment by ryanr08** [comment]
I can try to take a look at this. I'll investigate why the ellipsis is causing it to run so much slower. If anyone has any ideas as to what the problem is I would love to hear.

**Comment by nrwahl2** [comment]
All the time is spent in `Transpose::run()` in `tensorflow/core/kernels/transpose_functor_cpu.cc`. We don't have to do a transpose when ellipses aren't used.

The issue is that when ellipses are used, `EinsumHelper::ReduceOperand()`'s `absl::c_sort()` call rearranges `permutation`.
```
    // Check if we can avoid the transpose. We need to flip the adj_x (or adj_y)
    // flag during BatchMatMul. This is an extra optimization not necessary for
    // correctness.
    if (ShouldSwapFreeAndContract(*labels, label_types)) {
      *swap_free_and_contract = true;
    } else {
      absl::c_sort(permutation, [&](int i, int j) {
        int label_i = (*labels)[i];
        int label_j = (*labels)[j];
        return std::tie(label_types[label_i], label_i) <
               std::tie(label_types[label_j], label_j);
      });
```
```
label_i: 3, label_types[label_i]: 0, label_j: 0, label_types[label_j]: 1
label_i: 4, label_types[label_i]: 0, label_j: 3, label_types[label_j]: 0
label_i: 4, label_types[label_i]: 0, label_j: 0, label_types[label_j]: 1
label_i: 4, label_types[label_i]: 0, label_j: 3, label_types[label_j]: 0
label_i: 5, label_types[label_i]: 0, label_j: 3, label_types[label_j]: 0
label_i: 5, label_types[label_i]: 0, label_j: 0, label_types[label_j]: 1
label_i: 5, label_types[label_i]: 0, label_j: 4, label_types[label_j]: 0
label_i: 1, label_types[label_i]: 3, label_j: 3, label_types[label_j]: 0
label_i: 1, label_types[label_i]: 3, label_j: 0, label_types[label_j]: 1
permutation AFTER: 1 2 3 0 4
```

When ellipses aren't used, the sort keeps `permutation` in its original order.
```
label_i: 1, label_types[label_i]: 2, label_j: 0, label_types[label_j]: 1
label_i: 1, label_types[label_i]: 2, label_j: 0, label_types[label_j]: 1
label_i: 2, label_types[label_i]: 2, label_j: 0, label_types[label_j]: 1
label_i: 2, label_types[label_i]: 2, label_j: 1, label_types[label_j]: 2
label_i: 3, label_types[label_i]: 2, label_j: 0, label_types[label_j]: 1
label_i: 3, label_types[label_i]: 2, label_j: 2, label_types[label_j]: 2
label_i: 4, label_types[label_i]: 3, label_j: 0, label_types[label_j]: 1
label_i: 4, label_types[label_i]: 3, label_j: 3, label_types[label_j]: 2
ShouldSwapFreeAndContract check took 13759 nanoseconds
permutation AFTER: 0 1 2 3 4 
```

If the permutation has been rearranged, `EinsumHelper::ShouldTranspose()` returns true. So we have to do a transpose when we use ellipses. It returns false when ellipses aren't used and the permutation keeps its original sequential order.

I'm totally new to looking at TensorFlow internals, so this is as far as I've gotten. Not sure yet why there's this discrepancy or whether it's avoidable.

**Comment by zahed327** [comment]
I'd like to take a look at this issue and see why the ellipsis cause it to work slower

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
