### ISSUE TITLE
Lua Wrapper

### ISSUE THREAD

**Issue by darkSKULL-labs** [tensorflow/tensorflow#48480]
I wrapped it with Swig. But, I can not wrap TF_NewWhile because of the const pointer. I do not know why it says that it is read-only, because I tested it with another C program and it compiled. If anyone can explain why it says it is read-only I would like to learn the reason it refuses to compile it.

**Comment by tilakrayal** [comment]
@darkSKULL-labs ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

Thanks!

**Comment by darkSKULL-labs** [comment]
I don't think you can help I don't think it is a tensorflow problem.

**Comment by tilakrayal** [comment]
@darkSKULL-labs ,

Without the reproducible code, it would be difficult for us to debug the issue. In order to expedite the trouble-shooting process, could you please provide a minimal code snippet and the TensorFlow version you are using.

Also, if this is not a TensorFlow bug or feature request, it is better asked on [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a larger community that reads questions there. Thanks!

**Comment by darkSKULL-labs** [comment]
I am pretty sure it is a problem with GCC, the swig wrapper is so simple you could make it in five seconds if you want to test it.

**Comment by darkSKULL-labs** [comment]
This is the swig wrapper 

```haskell
%module lua_tensorflow
%{
#include <tensorflow/c/c_api.h>
%}

%ignore TF_NewWhile;
%include <tensorflow/c/c_api.h>
```

The problem is GCC will not assign the result from TF_NewWhile because ti believes it is read only but it doesn't make any sense to me why it thinks that.

**Comment by jvishnuvardhan** [comment]
@darkSKULL-labs If this is not a TF problem, then please post it in Stackoverflow where there is a huge community to help each other.

This is not Build/Installation or Bug/Performance issue. Please post this kind of support questions at [Stackoverflow](https://stackoverflow.com/questions/tagged/tensorflow). There is a big community to support and learn from your questions. GitHub is mainly for addressing bugs in installation and performance. Thanks

**Comment by darkSKULL-labs** [comment]
Ok thanks

**Comment by darkSKULL-labs** [comment]
Yes, I found out what the problem was and can fix it.

**Comment by darkSKULL-labs** [comment]
Yes, I just wanted to show why Google uses Swig for tensorflow. Thanks.

**Comment by darkSKULL-labs** [comment]
Butler, you are supposed to learn now and close the thread.
