### ISSUE TITLE
LookupError: No gradient defined for operation 'CudnnRNN' (op type: CudnnRNN)

### ISSUE THREAD

**Issue by rajsingh02** [tensorflow/tensorflow#48501]
model = Sequential()
model.add(LSTM(units=50, return_sequences=True, input_shape=(x_train.shape[1],1)))
model.add(LSTM(units=50))
model.add(Dense(1))

model.compile(loss='mean_squared_error', optimizer='adam')
model.fit(x_train, y_train, epochs=1, batch_size=1, verbose=2)

This is the code i am using

**Comment by UsharaniPagadala** [comment]
@rajsingh02 

Could you please fill the issue template
In order to expedite the trouble-shooting process, could you please provide the following details

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory
and the exact sequence of commands / steps that you executed before running  and also the error you are facing into the problem. Thanks!

**Comment by UsharaniPagadala** [comment]
@rajsingh02 
Hi  Can you please provide the above requested details. Thanks
--

**Comment by jvishnuvardhan** [comment]
@rajsingh02 Can you please share a simple standalone code to reproduce the issue? Thanks!
