### ISSUE TITLE
CMAKE_DL_LIBS refers to which libraries？I can't find the libs in CMakelists.txt

### ISSUE THREAD

**Issue by ToBigboss** [tensorflow/tensorflow#48512]

**Comment by UsharaniPagadala** [comment]
@ToBigboss 
Could you please fill the issue template

In order to expedite the trouble-shooting process, could you please provide the following details

OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory
and the exact sequence of commands / steps that you executed before running into the problem. Thanks!
