### ISSUE TITLE
Training a keras model on pretrained weights using load_weights()

### ISSUE THREAD

**Issue by irfanumar1994** [tensorflow/tensorflow#48534]
I am using a custom keras model in Databricks environment. For a custom keras model, `model.save(model.h5)` does not work, because custom model is not serializable. Instead it is recommended to use` model.save_weights(path)` as an alternate.

model.save_weights(pathDirectory) works. This yields 3 files c`heckpoint`,`.data-00000-of-00001,``.index` in the pathDirectory

For loading weights, Following mechanism is working fine.

```
model = Model()

model.load_weights(path)
```

But I want to train my model on pretrained weights I just saved. Like I saved model weights, and continue training on these saved weights afterwards. 

So, when I load model weights and apply training loop, I get this error, TypeError: 'CheckpointLoadStatus' object is not callable

Code is [here](https://gist.github.com/irfanumar1994/f38c3f80ac399717af5bce9904daa042)

**Comment by tilakrayal** [comment]
@irfanumar1994 ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem.

Also please, share colab link or simple standalone code to reproduce the issue in our environment.

Thanks!
