### ISSUE TITLE
Tf lite interpreter.allocate_tensors() Runtime error

### ISSUE THREAD

**Issue by farazBhatti** [tensorflow/tensorflow#48544]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 18.04):
- TensorFlow installed from (binary):
- TensorFlow version (2.4.1):
- Also tried tf-nightly

Ive used the following code to convert keras model to tflite. Conversion went successfull without any errors. Note that i used tf-nightly for the conversion as stable version of tf 2.4.1 was unable to convert
```
import tensorflow as tf
from tensorflow.keras.models import load_model

modelPath = "u2net_keras.h5"

tflite_model = load_model(modelPath)
converter = tf.lite.TFLiteConverter.from_keras_model(tflite_model)

# converter = tf.lite.TFLiteConverter.from_keras_model_file( 'u2netp_keras.h5')
tfmodel = converter.convert()
open ("model.tflite" , "wb") .write(tfmodel)
print("Sucess!")
```
Now I am using the following code to get inference from the converted model but code seems to get stuck on 
`'interpreter.allocate_tensors()'` line

```
import tensorflow as tf
import PIL.Image as Image
import numpy as np

import cv2


def preprocess(img_path, dim):
    img = Image.open(img_path)
    img = img.resize(dim, Image.BILINEAR)
    img_data = np.array(img)
    img_data = np.transpose(img_data, [2, 0, 1])
    img_data = np.expand_dims(img_data, 0)
    mean_vec = np.array([0.485, 0.456, 0.406])
    stddev_vec = np.array([0.229, 0.224, 0.225])
    norm_img_data = np.zeros(img_data.shape).astype('float32')
    for i in range(img_data.shape[1]):
        norm_img_data[:,i,:,:] = (img_data[:,i,:,:]/255 - mean_vec[i]) / stddev_vec[i]
    return norm_img_data


w = 320
h = 320
dim = (w,h)
model = "U2net-tflite-models/u2net.tflite"
img_path = 'boat.jpg'
img = preprocess(img_path, dim)


# Load TFLite model and allocate tensors.
interpreter = tf.lite.Interpreter(model)

interpreter.resize_tensor_input(0, [1,3, 320, 320], strict=False)

interpreter.allocate_tensors()



#get input and output tensors
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()


# Read the image and decode to a tensor

#Preprocess the image to required size and cast
input_shape = input_details[0]['shape']
print("input shape = ",np.expand_dims(img,0))
input_tensor= np.array(np.expand_dims(img,0))

#set the tensor to point to the input data to be inferred
input_index = interpreter.get_input_details()[0]["index"]
interpreter.set_tensor(input_index, input_tensor)
#Run the inference
interpreter.invoke()
output_details = interpreter.get_output_details()


output_data = interpreter.get_tensor(output_details[0]['index'])
results = np.squeeze(output_data)
top_k = results.argsort()
for label, idx in train_data_gen.class_indices.items():
    if top_k[idx]==1:
        print("Prediction: " ,label)
```

ERROR log

```
2021-04-15 18:34:01.240901: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-04-15 18:34:01.240937: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/home/faraz/Desktop/Esper_Solutions/upwrok/tfLite/U-2-Net-Keras/tflite_inference.py", line 34, in <module>
    interpreter.allocate_tensors()
  File "/home/faraz/.local/lib/python3.6/site-packages/tensorflow/lite/python/interpreter.py", line 420, in allocate_tensors
    return self._interpreter.AllocateTensors()
RuntimeError: tensorflow/lite/kernels/space_to_batch_nd.cc:67 op_context->block_shape->dims->data[0] != spatial_dims_num (3 != 2)Node number 49 (SPACE_TO_BATCH_ND) failed to prepare.


Process finished with exit code 1
```

**Comment by farazBhatti** [comment]
inorder to reproduce above error, here is the link of converted keras to tflite [model](https://drive.google.com/file/d/1y3LQSuxZcggilzMo82rPdGW9PMt-Lqam/view)

**Comment by amahendrakar** [comment]
@farazBhatti,
I am facing errors while convert the model to `.tflite`, please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/f0b201b5ba066efd0473be8f43dacd0d/48544.ipynb).

In order to expedite the trouble-shooting process, could you please provide a minimal reproducible code? Alternatively, you can run the code on [Google Colab](https://colab.research.google.com/) and share the notebook with us. Thanks!

**Comment by farazBhatti** [comment]
@amahendrakar , here is the link to keras model converted to .tflite [model](https://drive.google.com/drive/folders/1GR_CJ9JapoLwzzr7gkEwQZA4OewdWc60). please note I was only able to convert using tf-nightly and not stable version of tensorflow2.4.1. ill also share google colab with you in few minutes. thanks

**Comment by farazBhatti** [comment]
here is the google colab [notebook](https://colab.research.google.com/drive/12sAdJbiXS3w5vy8P75bfFbF6yTdUqK3c?usp=sharing)

**Comment by amahendrakar** [comment]
@farazBhatti,
Thank you for the gist.

@rmothukuru,
I was able to reproduce the issue with TF v2.4.1, TF v2.5.0rc1 and TF-nightly. Please find the gist of it [here](https://colab.research.google.com/gist/amahendrakar/dbe8dcf8ab125e42ae86d891f7cea103/48544.ipynb). Thanks!

**Comment by karimnosseir** [comment]
Hi 
Can you share the original model before conversion 

Thanks

**Comment by chunduriv** [comment]
@farazBhatti, Can you please share original model before conversion as per @karimnosseir [comment](https://github.com/tensorflow/tensorflow/issues/48544#issuecomment-868893248).Thanks!

**Comment by farazBhatti** [comment]
@karimnosseir  @chunduriv  You can find it [here](https://drive.google.com/file/d/1y3LQSuxZcggilzMo82rPdGW9PMt-Lqam/view)

**Comment by satpalsr** [comment]
Hey, I am facing a similar error while using tf2onnx for conversion. I am using [DeepLabv3+ model](https://keras.io/examples/vision/deeplabv3_plus/).

1. I convert TF model to TFlite using
```converter = tf.lite.TFLiteConverter.from_keras_model(model)

converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.target_spec.supported_types = [tf.float16]

converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

tflite_fp16_model = converter.convert()
```
This produces this warning message `WARNING:absl:Buffer deduplication procedure will be skipped when flatbuffer library is not properly loaded
8433276`

2. I converted  Tflite to onnx using tf2onnx. 
`
!python -m tf2onnx.convert --opset 13 --tflite model_f16_new.tflite --output model.onnx
`
```
WARNING - Error loading model into tflite interpreter: tensorflow/lite/kernels/space_to_batch_nd.cc:67 op_context->block_shape->dims->data[0] != spatial_dims_num (3 != 2)Node number 99 (SPACE_TO_BATCH_ND) failed to prepare.```

If someone resolves it please tag me.

**Comment by pjpratik** [comment]
I was able to reproduce this issue in TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/e69478d286ad187158d0ca30b75f9659/48544.ipynb). Thank you.

**Comment by pkgoogle** [comment]
I am able to reproduce locally,

Currently it seems that when the model converts, the block shape of the "space_to_batch_nd" op is 1 x 2 x 2 which is 3 dimensions instead of 2 dimensions which is what the input shape implies (batch, 1st spatial dim, 2nd spatial dim, channel), the input shape matches the original model's tensor dimensions, so this implies that the block shape is probably incorrect. It seems like the first dimension of the block shape (of size 1) should be squeezed but the conversion doesn't do that.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
