### ISSUE TITLE
How can I change dtype of TFLITE model Weights ?

### ISSUE THREAD

**Issue by Humza1996** [tensorflow/tensorflow#48540]
**System information**
- OS Platform and Distribution (Windows 10):
- TensorFlow installed from binary
- TensorFlow version 2.4.1

I have a TFLITE model which was made from KERAS Functional API. Unfortunately I have deleted the all files related to that model like weights.h5 and model structure file. Now All I have is my TFLITE model. Its weights are in float 32 but I have to run it on mobile. So I need to convert weights to int8 (Quantization mode) or float16. Is there anyway So I can cast my TFLITE model weights ?  
[Model.zip](https://github.com/tensorflow/tensorflow/files/6318011/Model.zip)

I have Attached the Model below

**Comment by ymodak** [comment]
I am afraid there is no way to do this without original model since all model optimization techniques ([integer-only quantization](https://www.tensorflow.org/lite/performance/post_training_integer_quant#convert_using_integer-only_quantization), [float16 quantization](https://www.tensorflow.org/lite/performance/post_training_float16_quant#convert_to_a_tensorflow_lite_model)) are declared before converting `SavedModel/Keras` model into `tflite` format.
