### ISSUE TITLE
Unexpected behavior of soft device placement

### ISSUE THREAD

**Issue by atom00** [tensorflow/tensorflow#48559]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.4.1
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the current behavior**
Soft device placement by default is set to True. Despite this running the code below causes it to fail with error:
tensorflow.python.framework.errors_impl.InvalidArgumentError: Could not satisfy device specification '/job:localhost/replica:0/task:0/device:dummy:0'. enable_soft_placement=0. Supported device types [CPU]. All available devices [/job:localhost/replica:0/task:0/device:CPU:0]. [Op:Fill]

Even though tf.config.get_soft_device_placement() returns True in the error we can see "enable_soft_placement=0"
WA for this issue is to explicitly call  tf.config.set_soft_device_placement(True)

**Describe the expected behavior**
Soft device placement should work as indicated by tf.config.get_soft_device_placement()
Also tf.device inside tf.function should not have such side effects

**Standalone code to reproduce the issue**
```
    # tf.config.set_soft_device_placement(True) # Uncomment this for WA
    @tf.function
    def func():
        with tf.device("/device:CPU:0"): # this tf.device within tf.function breaks soft placement in eager mode later
            return tf.constant([1])    
    func()

    print("tf.config.get_soft_device_placement() = ", tf.config.get_soft_device_placement()) # Always prints True

    # Commenting code above this line makes code below execute correctly
    with tf.device("/device:dummy:0"):
        tf.fill([1, 1], 1) # Error
```

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue with TF 2.4 and Nightly versions. Please find the gist [here](https://colab.research.google.com/drive/16G4mZM8bNTaCQyJ6-0WpQ-LiemIiU8D7#scrollTo=CluP63gevyi1&uniqifier=2). Thanks!

**Comment by chunduriv** [comment]
I was able to reproduce the issue on colab using `TF2.6` and `TF-nightly(2.8.0-dev20211003)`.Please find the gist [here](https://colab.research.google.com/gist/chunduriv/4aa228014b98f491e10e9eea12d846b7/48559.ipynb) for reference.Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
