### ISSUE TITLE
Connectionist Temporal Classification with Maximum Entropy Regularization (EnCTC)

### ISSUE THREAD

**Issue by Cerno-b** [tensorflow/tensorflow#48614]
**System information**
- TensorFlow version (you are using): 2.1.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

There is an extension to CTC (EnCTC) that introduces regularization in order to prevent "peaky" and overly confident distributions typical to CTC.

https://papers.nips.cc/paper/2018/file/e44fea3bec53bcea3b7513ccef5857ac-Paper.pdf
Connectionist Temporal Classification with Maximum Entropy Regularization
Hu Liu, Sheng Jin, Changshui Zhang

This approach has been shown to *"consistently improve over the CTC baseline without the need to adjust training settings"* on scene text recognition tasks.

**Will this change the current api? How?**

It would likely extend `tf.nn.ctc_loss` to have an optional regularization argument.

**Who will benefit with this feature?**

Anyone who uses CTC in Recurrent Neural Networks, e.g. in OCR, handwriting recognition or speech recognition

**Any Other info.**

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
