### ISSUE TITLE
load_model fails for certain keras.layers.Add configurations

### ISSUE THREAD

**Issue by elad-c** [tensorflow/tensorflow#48673]
**System information**
Python version: 3.7
TF 2.3 version: v2.3.0-54-gfcc4b966f1 2.3.1
TF 2.4 version: v2.4.0-49-g85c8b2a817f 2.4.1
TF-nightly version: v1.12.1-55314-g6a872f41130 2.6.0-dev20210421

**Describe the current behavior**
It's possible to create and infer model with Add layer (or OpLambdaLayer-Add) that adds the input to a constant, either with the constant as first input or the last. I can save it, but can't load it again

The following code works in TF 2.3, but fails both in TF 2.4 and the nightly versions

**Describe the expected behavior**
Seems like it should be able to load the saved model

**Standalone code to reproduce the issue**
`
import tensorflow as tf
import numpy as np

np_const = np.ones((1, 6))
outs = []
_in = tf.keras.layers.Input((6,))
outs.append(tf.keras.layers.Add()((_in, _in)))
outs.append(_in + np_const)
outs.append(tf.keras.layers.Add()((np_const, _in)))  # <=== problematic layer
outs.append(np_const + _in)  # <=== problematic layer

model = tf.keras.Model(inputs=_in, outputs=outs)

print('TF version:', tf.__version__)
print('model output:', model(np.arange(18).reshape(-1, 6)))

model_file = '/tmp/add_model.h5'
model.save(model_file)

loaded_model = tf.keras.models.load_model(model_file, compile=False)
print('loaded model output:', loaded_model(np.arange(18).reshape(-1, 6)))
`

**Comment by tilakrayal** [comment]
@jvishnuvardhan ,

I was able to replicate the issue on tf 2.4 and nightly but the issue is not reproducible on tf 2.3, please find the [gist](https://colab.research.google.com/gist/tilakrayal/017b8a7566093e4bb0d7644827bdb47d/48673.ipynb) here

**Comment by elad-c** [comment]
As I wrote in the issue description, the code works fine in TF 2.3
it only started failing after the move to 2.4

**Comment by chunduriv** [comment]
I was able to reproduce the issue on colab using `TF2.6` and `TF-nightly(2.8.0-dev20211003)`. Please find the gist [here](https://colab.research.google.com/gist/chunduriv/2b3a7c25f78f2a65a440638051a65eb0/48673.ipynb) for reference .Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
