### ISSUE TITLE
How to build a dynamic library for ios tflite by cmake with Cross-compilation?

### ISSUE THREAD

**Issue by Mrlyk423** [tensorflow/tensorflow#48693]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary):
- TensorFlow version:
- Python version:
- Installed using virtualenv? pip? conda?:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory:

**Describe the problem**

I have successfully built the ios static library with the comand "bash tensorflow/lite/tools/make/download_dependencies.sh". But I find the generated static lib is over 17Mb for each architecture. 

Meanwhile, I also try to use the command "bazel build --config=ios_x86_64 -c op //tensorflow/lite/ios:TensorFlowLiteC_framework" to genenrate a ios static lib (.framework), but it is bigger (>23Mb).

 In my opinion, the dynamic lib can be smaller than the static lib (17Mb). How can I obtain it?

**Comment by abattery** [comment]
@terryheo @yyoon  could you take a look?

**Comment by yyoon** [comment]
cc/ @thaink 

Generally speaking, the size of the iOS static library built with bazel is big due to bitcode embedding. When it's linked to your final app after the app thinning is applied, the actual size increase caused by TFLite will be much smaller (around 3~4MB last time we checked a few months ago).

A few additional notes:
* The [iOS build script using Makefile](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/tools/make/build_ios_universal_lib.sh) has not been maintained for quite a long time, and the resulting library wouldn't necessarily work correctly.
* You could try building a dynamic framework by adding a new `ios_framework` build target in the [iOS BUILD file](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/ios/BUILD.apple). It would be similar to the static framework target, but you would need to additionally provide a `plist.info` file. See https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/ios/BUILD.apple for documentation.
* When I tried building iOS lib with CMake, it didn't support cross compilation. It required me to use a Mac machine and the Xcode project generator. Even with these, I couldn't successfully build some dependencies such as XNNPack.

Let me know if you have further questions.

**Comment by thaink** [comment]
Right. I don't think you should care about .framework file size. Better to focus on the final app size increase.

**Comment by Mrlyk423** [comment]
I see. Thanks!

**Comment by Mrlyk423** [comment]
@yyoon I find the official site (https://www.tensorflow.org/lite/guide/build_ios) is still asking users to use the command "tensorflow/lite/tools/make/download_dependencies.sh". It is better to update it.

**Comment by yyoon** [comment]
@Mrlyk423 I don't see that instruction anywhere on the page you linked. Can you point to the exact location of it? Is it possible that you were somehow looking at an old version of that doc?

**Comment by Mrlyk423** [comment]
Ohh, I see. I am looking at the version of "Chinese" of this page, the "English" version has been updated.
