### ISSUE TITLE
model.fit() should tell you if batch is not big enough to train with

### ISSUE THREAD

**Issue by isaacgerg** [tensorflow/tensorflow#48708]
Suppose you train a model using model.fit() and your batch size is set to N.  If the input from a generator is < N, tf keras gives the following error which is difficult to interpret: **ValueError: Expect x to be a non-empty array or dataset.**

Reference second answer in : https://stackoverflow.com/questions/63231811/valueerror-expect-x-to-be-a-non-empty-array-or-dataset-tensor-flow-lite-model

Propose to have tf keras tell user that batch size is larger than data size in place of current error.  The current error implies that the x is empty which isnt this case for all x with size less than N.

**Comment by tilakrayal** [comment]
@isaacgerg ,

In order to expedite the trouble-shooting process, could you please provide the Tensorflow version,complete code and dataset to reproduce the issue reported here.

Thanks!

**Comment by isaacgerg** [comment]
Tensorflow 2.4.1

**Comment by tilakrayal** [comment]
@isaacgerg ,

Could you please provide the complete code and dataset or colab link to reproduce the issue reported here.

**Comment by isaacgerg** [comment]
@tilakrayal  See the stack overflow link in the original post.

**Comment by Saduf2019** [comment]
@isaacgerg 
You set a batch size and then enter input less than batch size it would be treated as empty, you cannot have that. 
We cannot have issues to fix user code as this repo is for performance issues and feature request or bugs only.

**Comment by isaacgerg** [comment]
@Saduf2019 Please read the original issue carefully and note my proposal.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by isaacgerg** [comment]
I decided to stop using TensorFlow due to the delayed responses on the GitHub issues I raised and some concerns I had about the implementation quality.
