### ISSUE TITLE
Question about Cannot Import

### ISSUE THREAD

**Issue by lms153** [tensorflow/tensorflow#48734]
This are parts of my code：
 
![image](https://user-images.githubusercontent.com/78319233/115960832-21e6ce00-a546-11eb-92c2-21a28665f3d8.png)
![image](https://user-images.githubusercontent.com/78319233/115960837-2b703600-a546-11eb-9027-ca04cc2e0a12.png)

from tensorflow.python.eager.context import get_config

ImportError: cannot import name 'get_config'
can someone tell me why?

**Comment by saikumarchalla** [comment]
I tried to  import all the packages and   not getting any errors that you have faced. Please check the gist [here](https://colab.research.google.com/gist/saikumarchalla/d1eb9c29d5e1b7dd91ceaa423d5900e4/untitled67.ipynb).

Please use tensorflow.keras instead of keras  and  make sure you use Tensorflow 2.x  and let us know still if that doesn't resolve the  error. Thanks!
