### ISSUE TITLE
microspeech pretrained model is uint8 quantized instead of int8 quantized and doesn't work properly

### ISSUE THREAD

**Issue by mocleiri** [tensorflow/tensorflow#48752]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/micro/examples/micro_speech/train#trained-models

## Description of issue (what needs changing):

There is a download link for the pre-trained microspeech model; speech_commands.zip.  When you download and unzip the files there are 3:
model.cc (encoded array is 18222 bytes long)
model.tflite (file is 18222 bytes long)
model.tb

The documentation says that this is a model that is int8 quantized at the inputs and outputs **but it is wrong**, the model in the zip file is actually uint8 quantified on the inputs and outputs.

The model used in the microspeech example is 18712 bytes long:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/micro_features/model.cc

I picked up the model.tflite from the zip file because I needed to load it as a bytestream instead of as an array.  

I just found out my code is not working because the quantization is wrong.  The spectrograms generate as int8 and because this model is uint8 I've been dropping out half my data when casting an int8 to an uint8.

I recreated the model using the https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/micro/examples/micro_speech/train/train_micro_speech_model.ipynb starting from the pretrained checkpoints and the output model is correctly quantized using int8's.

The zipfile needs to be updated with the correct model files and then the link in the page changed to point at the new zip file.

### Page
![image](https://user-images.githubusercontent.com/250942/116026221-3f886600-a620-11eb-9ded-f36fa633ef91.png)

### Contents of speech_commands.zip archive
![image](https://user-images.githubusercontent.com/250942/116026202-34cdd100-a620-11eb-93c4-efb54febc6aa.png)

### Neutron View of downloaded model
![image](https://user-images.githubusercontent.com/250942/116026326-79f20300-a620-11eb-8426-fc80d730b080.png)

### Neutron View of retrained model
![image](https://user-images.githubusercontent.com/250942/116026398-ab6ace80-a620-11eb-8033-2ab835c66060.png)

**Comment by jianlijianli** [comment]
Hi advaitjain, could you please help triage this issue on micro? Thanks.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by mocleiri** [comment]
It looks like there was an update of the models last year: https://github.com/tensorflow/tflite-micro/tree/main/tensorflow/lite/micro/examples/micro_speech/models

Probably fixes this issue so I will close.
