### ISSUE TITLE
Change the default for num_epochs to 1 from None in make_csv_dataset

### ISSUE THREAD

**Issue by dgoldenberg-audiomack** [tensorflow/tensorflow#48759]
The default for the num_epochs parameter in make_csv_dataset is None:

```
    num_epochs: An int specifying the number of times this dataset is repeated.
      If None, cycles through the dataset forever.
```

This is really confusing to the user (at least, it was very surprising and confusing to me). I could not tell why my training appeared to be 'hanging'. It turned out it was due to this default. I propose that this be changed to 1. Looping forever is highly unexpected and leads to many user time cycles left trying to debug and understand what's happening.

I'm filing this per the discussion in TFRS regarding this problem which took a long time to troubleshoot and fix. Per that discussion,

> [the]... default [...] goes against the compositional nature of tf.data APIs (where you'd normally stick a .repeat() at the end if you want an infinite dataset).

(Opening an issue here to replace https://github.com/tensorflow/io/issues/1377 per @yongtang 's suggestion).

**Comment by maciejkula** [comment]
:+1:

In the `tf.data` world the usual way to get an infinite dataset is to use `dataset.repeat()`. It is therefore surprising that this repeats infinitely by default. I suspect this is because this API predates the modern `tf.data` functions?

**Comment by dgoldenberg-audiomack** [comment]
Good point, I guess we'll find out once we hear from some folks @ tf core.

**Comment by aaudiber** [comment]
@dgoldenberg-audiomack I agree 100%, it shouldn't repeat by default. Switching the default on the `experimental.make_csv_dataset` symbol will likely break existing users though, so it is prudent to wait until we migrate `make_csv_dataset` out of "experimental". I'm adding a TODO reminder in the code.

**Comment by dgoldenberg-audiomack** [comment]
Thanks, @aaudiber, I think that sounds like the right time to do it. Maybe this ticket can be referenced from that epic when it comes around.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
