### ISSUE TITLE
Please support native acos/asin/atan/atan2 operations within TFLite library

### ISSUE THREAD

**Issue by barabanus** [tensorflow/tensorflow#48775]
**System information**
- `Linux 5.11.4-arch1-1 #1 SMP PREEMPT Sun, 07 Mar 2021 18:00:49 +0000 x86_64 GNU/Linux`
- `TensorFlow 2.4.1` from `tensorflow-opt-cuda` package (https://archlinux.org/packages/community/x86_64/tensorflow-opt-cuda)

**Provide the text output from tflite_convert**

```
ConverterError: /usr/lib/python3.9/site-packages/tensorflow/python/ops/math_ops.py:5037:0: error: 'tf.Acos' op is neither a custom op nor a flex op
/usr/lib/python3.9/site-packages/tensorflow/python/util/dispatch.py:201:0: note: called from
/home/barabanus/work/4a-games/pfnn-tools/test/tflite-acos-missing.py:6:0: note: called from
/usr/lib/python3.9/site-packages/IPython/utils/py3compat.py:168:0: note: called from
/usr/lib/python3.9/site-packages/IPython/core/interactiveshell.py:2740:0: note: called from
/usr/lib/python3.9/site-packages/IPython/core/shellapp.py:377:0: note: called from
/usr/lib/python3.9/site-packages/IPython/core/shellapp.py:452:0: note: called from
/usr/lib/python3.9/site-packages/IPython/core/shellapp.py:328:0: note: called from
/usr/lib/python3.9/site-packages/IPython/terminal/ipapp.py:323:0: note: called from
/usr/lib/python3.9/site-packages/traitlets/config/application.py:87:0: note: called from
<unknown>:0: error: failed while converting: 'main': Ops that need custom implementation (enabled via setting the -emit-custom-ops flag):
	tf.Acos {device = ""}
```

**Standalone code to reproduce the issue** 
```
# use tensorflow API v1
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

X = tf.placeholder(dtype=tf.float32, shape=[], name="X")
Y = tf.acos(X, name="Y")

with tf.Session() as session:
    acosZero = session.run(Y, feed_dict={ X: 0., })
    acosOne = session.run(Y, feed_dict={ X: 1., })
    print(f"TensorFlow: acos(0.)={acosZero}, acos(1.)={acosOne}")

    converter = tf.lite.TFLiteConverter.from_session(
        session,
        input_tensors=[X],
        output_tensors=[Y]
    )
    flatbuffer = converter.convert()
```

**Comment by abattery** [comment]
Thanks for filing a feature request. You can enable the Select TF option to utilize the existing TF kernels. See https://www.tensorflow.org/lite/guide/ops_select.

**Comment by barabanus** [comment]
@abattery Thank you for your suggestion to enable Select TF option, but in our environment TensorFlow is not supported. We can use only TFLite operations.

**Comment by abattery** [comment]
To understand the circumstances, If possible, could you share why your deployment environment can't have it?

**Comment by barabanus** [comment]
@abattery Our runtime hardware is game consoles (Microsoft XBox, Sony PS and Nintendo Switch) with realtime inference requirement. They don't support TF with all its uncontrolled memory allocations, signals and threads management, but we hope to be use TFLite.

**Comment by abattery** [comment]
Do you need to all acos/asin/atan/atan2 ops? If possible, it would be nice to share your detailed op requirements including tensor type and tensor shape requirements. For example, is supporting float32 inputs up to 4 four dimensions sufficient?

**Comment by barabanus** [comment]
@abattery Oh, I see! Well, actually we need `acos` with `float32` inputs of unrestricted size (`shape=[None]`)

**Comment by abattery** [comment]
@thaink could you take a look at this feature request?

**Comment by abattery** [comment]
If this is quite urgent in your side, please consider implementing a custom acos op for your case. Here is the guide document describing how to write down a TFLite custom sin op.

https://www.tensorflow.org/lite/guide/ops_custom#defining_the_kernel_in_the_tensorflow_lite_runtime

**Comment by thaink** [comment]
These under our list to add to builtin ops. I think I can handle them sometime later this week.

**Comment by PINTO0309** [comment]
**`tf.lite.OpsSet.SELECT_TF_OPS`** seems to cause an error, so I implemented an approximate calculation **`acos`**. I get an error even with v2.6.0. It is not recommended because it is very computationally expensive and redundant. However, it can be implemented without custom operations, using only standard OPs.

https://github.com/PINTO0309/openvino2tensorflow/blob/f91027ef98e9e30912505b9a8e9ab455a1c9f08f/openvino2tensorflow/openvino2tensorflow.py#L3557-L3578

![Screenshot 2021-09-21 11:49:16](https://user-images.githubusercontent.com/33194443/134512382-4fbfc136-48f4-40da-9a25-c052207ae7f7.png)
.

**Comment by barabanus** [comment]
@PINTO0309 Thank you for sharing your implementation of `acos`. I managed to do a similar approximation based on its similarity to `sqrt(1 - abs(x))` + polynome to reduce error, but it would be good to have this common operation implemented within TFLite by default
```
def acosTF(x, margin=1e-5):
    """ Approximate arccos() as it's not supported within TFLite
    """
    x = tf.clip_by_value(x, margin - 1., 1. - margin)

    # set initial approximation
    xp = tf.abs(x)
    t = tf.sqrt(1. - xp)

    # fix with polynomial
    c3 = -0.0200752
    c2 = xp * c3 + 0.0759031
    c1 = xp * c2 - 0.2126757
    c0 = xp * c1 + 1.5707963
    p = t * c0

    # correct for negative argument
    n = TAU / 2. - p
    y = tf.where(x >= 0., p, n)

    return y
```

**Comment by PINTO0309** [comment]
@barabanus 
A structurally simple model was generated, and the output results match perfectly. I would like to thank you as well.
```
TF
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Float32
<tf.Tensor: shape=(1,), dtype=float32, numpy=array([0.00447434], dtype=float32)>

TFLite
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Float32
array([[0.00447434]], dtype=float32)
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ INT8
array([[0.00447434]], dtype=float32)
```
![Screenshot 2021-11-09 21:29:24](https://user-images.githubusercontent.com/33194443/140924447-e9215953-4ae6-4723-baa1-164f7efa8726.png)

The method you suggested is clearly a better method for approximate calculations. However, I have created models that are compatible not only with TFLite, but also with all of TensorFlow, EdgeTPU, ONNX, OpenVINO, Myriad Blob, TensorRT, TensorFlow.js, and CoreML. In fact, I had consciously avoided using the last GreaterEqual and Select operations because they do not work well with other frameworks. Please ignore this fact, as it has nothing to do directly with this issue.

Thanks again.

**Comment by pjpratik** [comment]
FYI, `atan2` has been added as builtin op.

https://github.com/tensorflow/tensorflow/blob/674c3c86b1b0b97689f9cfa061285f43f571d70c/tensorflow/lite/builtin_ops.h#L186

**Comment by bawahakim** [comment]
@pjpratik 
Is this in 2.12.0, and does it work without enabling Select TF options? We need atan2 for our project, and it seems WebGL does not support TF options. Would be great to have a workaround if not :)

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
