### ISSUE TITLE
@YonitZall

### ISSUE THREAD

**Issue by apramanik62** [tensorflow/tensorflow#48861]
@YonitZall 
did you get any solutions? I am facing the same problem

_Originally posted by @apramanik62 in https://github.com/tensorflow/tensorflow/issues/29078#issuecomment-830577011_

**Comment by tilakrayal** [comment]
@apramanik62 ,

In order to expedite the trouble-shooting process, could you please provide the The tesnorflow version,complete code and dataset to reproduce the issue.

Thanks!

**Comment by apramanik62** [comment]
@tilakrayal 
Thanks for your kind response . can you share me your email address for sharing necessary files?

**Comment by tilakrayal** [comment]
@apramanik62 ,

Can you please provide the tensorflow version,complete code and dataset or colab to reproduce the issue here.

**Comment by apramanik62** [comment]
@tilakrayal 
below is the link 
https://1drv.ms/u/s!At88VZrdRtnbhHhyJor1fXyD_4Nc?e=rK2FJT
kindly give your comments for the same.
tensorflow version 1.15

**Comment by apramanik62** [comment]
@tilakrayal 
Thanks for your response. I will look at the given link.
Can you tell me how did figure out that? is there any wrong file in TensorFlow 1.15

**Comment by tilakrayal** [comment]
@apramanik62 ,

TensorFlow 1.x is not actively supported. Could you please update TensorFlow v2.x and also as mentioned please follow similar issue [here](https://github.com/tensorflow/models/issues/7636).

Issue is more related to tensorflow models,Could you please close here and submit a new issue from this [link](https://github.com/tensorflow/models/issues/new/choose) and fill in the template, so that we can track the issue there. Thanks!

**Comment by apramanik62** [comment]
ok I will check on TF 2.x
Thanks.
