### ISSUE TITLE
Optimizer that is wrapped with two different LossScaleOptimizer throws a error.

### ISSUE THREAD

**Issue by keisen** [tensorflow/tensorflow#48862]
**System information**
- OS: colab (Ubuntu 18.04.5)
- Where TensorFlow installed from : pre-installed in colab
- TensorFlow version: 2.4.1
- Python version: 3.7.10
- GPU model and memory: Tesla K80, 12GB

**The current behavior**

When using tf.keras.Optimizer that is wrapped with two different `tf.keras.mixed_precision.LossScaleOptimizer`, the optimizer raises a error below.

```
ValueError: Called Trackable._track_trackable() with name='loss_scale', but a Trackable with this name is already declared as a dependency. Names must be unique (or overwrite=True).
```

**The expected behavior**

I believe that the error should be NOT occurred.

**Standalone code to reproduce the issue**

• The code snippet to reproduce the error.

```python
import tensorflow as tf

optimizer = tf.optimizers.RMSprop()
wrapped_optimizer_1 = tf.keras.mixed_precision.LossScaleOptimizer(optimizer) # There is no error.
wrapped_optimizer_2 = tf.keras.mixed_precision.LossScaleOptimizer(optimizer) # The error occurred.
```

• The error

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-efa101fb525d> in <module>()
      3 optimizer = tf.optimizers.RMSprop()
      4 wrapped_optimizer_1 = tf.keras.mixed_precision.LossScaleOptimizer(optimizer)
----> 5 wrapped_optimizer_2 = tf.keras.mixed_precision.LossScaleOptimizer(optimizer)

2 frames
/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py in __init__(self, inner_optimizer, dynamic, initial_scale, dynamic_growth_steps)
    545       self._loss_scale = _DynamicLossScaleState(
    546           initial_scale, dynamic_growth_steps, multiplier=2)
--> 547       self._track_trackable(self._loss_scale, 'loss_scale')
    548     else:
    549       if initial_scale is None:

/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/mixed_precision/loss_scale_optimizer.py in _track_trackable(self, trackable, name, overwrite)
    154 
    155   def _track_trackable(self, trackable, name, overwrite=False):  # pylint: disable=redefined-outer-name
--> 156     return self._trackable._track_trackable(trackable, name, overwrite)
    157 
    158   def _handle_deferred_dependencies(self, name, trackable):  # pylint: disable=redefined-outer-name

/usr/local/lib/python3.7/dist-packages/tensorflow/python/training/tracking/base.py in _track_trackable(self, trackable, name, overwrite)
    897             ("Called Trackable._track_trackable() with name='%s', "
    898              "but a Trackable with this name is already declared as a "
--> 899              "dependency. Names must be unique (or overwrite=True).") % (name,))
    900       # This is a weird thing to do, but we're not going to stop people from
    901       # using __setattr__.

ValueError: Called Trackable._track_trackable() with name='loss_scale', but a Trackable with this name is already declared as a dependency. Names must be unique (or overwrite=True).
```

**Other info / logs**

N/A

Thanks!

**Comment by UsharaniPagadala** [comment]
@keisen 
As per the [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/LossScaleOptimizer?version=nightly#hyperparameters) Object (saved)name should be UNIQUE for more info please find the [LINK](https://colab.research.google.com/gist/UsharaniPagadala/ed3328ee33ac81c36048ace6593af3cd/-48862.ipynb) .Thanks

**Comment by keisen** [comment]
@UsharaniPagadala 

> As per the documentation

Where does it say that?
Would you be more specific about where it is?

> As per the documentation Object (saved)name should be UNIQUE for more info please find the LINK 

What is `Object` you said?
If you said `Object` is `tf.keras.optimizers.RMSprop` instance, why there are no error when we use multiple RMSprop instances (whose name are all default value 'RMSprop') in model training?

> ValueError: Called Trackable._track_trackable() with name='loss_scale', but a Trackable with this name is already declared as a dependency. Names must be unique (or overwrite=True).

What named it 'loss_scale'?
I opened this issue because I thought the naming logic in `LossScaleOptimizer` is wrong.


Thanks.

**Comment by rmothukuru** [comment]
@keisen,
Can you please let us know why do you want to wrap the **`an Optimizer`** with two **`tf.keras.mixed_precision.LossScaleOptimizer`** instances? Thanks!

**Comment by keisen** [comment]
> Can you please let us know why do you want to wrap the an Optimizer with two tf.keras.mixed_precision.LossScaleOptimizer instances?

@rmccorm4 , Thank you for your response.

I know it's only natural but, we do NOT want to meaninglessly wrap the one with multiple LossScaleOptimizers.
We want to resolve this issue for our library users.
We've been developing [a library](https://github.com/keisen/tf-keras-vis) that analyze the model, the code below is its I/F.

https://github.com/keisen/tf-keras-vis/blob/ddd951396f16e7f5b7a0e8619f43f99c599628fb/tf_keras_vis/activation_maximization.py#L12-L20

As above, our library's I/F accepts an optimizer instance as necessary, that's, when our user does NOT specify it, the `optimizer` will be default value (`tf.optimizers.RMSprop(1., 0.95)`).
So users will face the error in two situation as follow:

1. Call the API twice without specifying `optimizer`.

```
library_instance = ActivationMaximization(...)
results = library_instance(...)
# Do something
results = library_instance(...) # The error occurred!
```

2. Call the API twice with an optimizer instance which is created by user, such below:

```
optimizer = tf.optimizers.RMSprop()

library_instance = ActivationMaximization(...)
results = library_instance(..., optimizer=optimizer)
# Do something
results = library_instance(..., optimizer=optimizer) # The error occurred!
```

We want to avoid in which they face the error.
Let me get this straight.

1. Although we've used the I/F above ever since Tensorflow1.x, we've never faced an error about the uniqueness of optimizer .
1. This problem affect various users that deal with optimizer wrapped by LossScaleOptimizers, like above.

For the above reasons,  I suspect that this behavior is a specification bug of LossScaleOptimizer.
But even if it were officially specification ...

1. I could NOT find the explanation that makes us understand this phenomenon clearly in Tensorflow documentations.
1. It is too hard to identify the cause of it ,at least, from the error message below. Actually, I took a long time to find it.

```
ValueError: Called Trackable._track_trackable() with name='loss_scale', but a Trackable with this name is already declared as a dependency. Names must be unique (or overwrite=True).
```

So I'd like to request an appropriate error message and enough documentation.

Thanks!

**Comment by rmccorm4** [comment]
I believe @rmothukuru was supposed to be pinged above instead.

**Comment by keisen** [comment]
@rmothukuru , @rmccorm4 , I sincerely apologize for the mistake!

**Comment by reedwm** [comment]
The error message was improved in 57caac46d0f036754f8f093fd40099eaaf6c06c2 (which will be in TF 2.5) but the issue remains unfixed. 

Can you clarify what the use case is? I'm assuming "I/F" means "interface". Is the issue that `library_instance` wraps the optimizer with a `LossScaleOptimizer`, which causes this error when `library_instance` is called twice??

**Comment by keisen** [comment]
Hi, @reedwm .

> The error message was improved in 57caac4 (which will be in TF 2.6) but the issue remains unfixed.

Thank you so much for the improvement!


> Can you clarify what the use case is? I'm assuming "I/F" means "interface". Is the issue that library_instance wraps the optimizer with a LossScaleOptimizer, which causes this error when library_instance is called twice??

I have something to tell you first.
When I created this issue, I thought there are scenarios many more that has this problem.
However, now, I notice that almost of them can be avoided by redesigning our library's interface. That's, We should NOT define the interface that defalult value is a optimizer instance.

As a result, the scenario that needs to reuse the same optimizer instance is only on when our users use them on jupyter notebook or colab interactively , such below.

```python
import tensorflow as tf
from tf_keras_vis.activation_maximization import ActivationMaximization as OurLibrary

# Setting mixed-precisoin
tf.keras.mixed_precision.set_global_policy('mixed_float16')

# Create library_instance
model = tf.keras.applications.vgg16.VGG16(weights='imagenet', include_top=True)
library_instance = OurLibrary(model)

# Create optimizer instance
optimizer = tf.keras.optimizers.RMSprop()

# First call
activations = library_instance(score=lambda x: x[:, 20],
                               seed_input=None,
                               optimizer=optimizer)

# To do thing...
# Check results, but it was not calculated enough.
# So we decided to continue the calculation with the result of first call as seed_input value.

# But the error occurred!
activations = library_instance(score=lambda x: x[:, 20],
                               seed_input=activations,
                               optimizer=optimizer)
```


I'm sorry for the late reply.
Thanks!

**Comment by reedwm** [comment]
Unfortunately, supporting this is very difficult, so this will probably not get fixed. I will update the documentation.

I highly recommend having the user pass a `LossScaleOptimizer` to `library_instance` instead of a normal optimizer. In general, it's a good idea to wrap the optimizer with a `LossScaleOptimizer` shortly after creating it. Alternatively, if you want `library_instance` to wrap with a LossScaleOptimizer and allow it to be called multiple times, you can maintain a `dict` (or `WeakKeyDictionary`) from optimizer to LossScaleOptimizer, and reuse the LossScaleOptimizer if the same optimizer is passed multiple times.

Technical details ahead (no need to read this): The reason this is so difficult to implement is because LossScaleOptimizer emulates the checkpoint format of the inner optimizer. This means if a checkpoint is saved with a LossScaleOptimizer, the checkpoint format is exactly the same as if it were saved with the inner optimizer, except the optimizer has a dependency on the loss scale. However, if two LossScaleOptimizers wrap the same inner_optimizer, then each will try to create a trackable dependency from the inner_optimizer to the loss scale (with name "loss_scale"), giving an error since an object cannot two dependencies with the same name.

**Comment by keisen** [comment]
@reedwm , Thank you for your reply!


> Unfortunately, supporting this is very difficult, so this will probably not get fixed. I will update the documentation.

>if two LossScaleOptimizers wrap the same inner_optimizer, then each will try to create a trackable dependency from the inner_optimizer to the loss scale (with name "loss_scale"), giving an error since an object cannot two dependencies with the same name.

That's too bad but I understand.


> I highly recommend having the user pass a LossScaleOptimizer to library_instance instead of a normal optimizer. In general, it's a good idea to wrap the optimizer with a LossScaleOptimizer shortly after creating it.

You're right. However we don't want our users to have check whether the visualization target model has a low-precision variable or not. In the scenario below, UserB doesn't know that he needs to wrap a optimizer with LSO if UserA does NOT tell him that the model was saved in a mixed-precision environment or not.

1. UserA implemented and trained a model, and then saved it into xxx.h5 file.
2. UserA publishes it, and UserB finds and downloads it.
3. UserB loads the model and visualizes it with `library_instance`.

Because the `library_instance` uses the outputs of intermediate layer of the model, to know it, I believe that our users have to do like below:

```python
for layer in model.layers:
    if (layer.variable_dtype != layer.compute_dtype) and
        (layer.compute_dtype in [tf.float16, tf.bfloat16]):
        # TODO wrap a optimizer with LSO
        break
```

So if we're able to use LSO instance regardless if the model contains lower-precision variables or not, we're so happy to adopt the way you recommended. (That's, we will re-define the specification that our users need to pass the optimizer wrapped with LSO when they aren't confident whether the model is float32-precision.)
If not, I believe, it's too verbose to have our users implement it in every using `library_instance`.

So, I have two questions below:
1. Is there no problem when we apply LSO to calculation of gradients of the float32-precision model?
2. If not, is it possible to fix it ?


Thanks!

**Comment by reedwm** [comment]
> Is there no problem when we apply LSO to calculation of gradients of the float32-precision model?

This won't cause issues, although I still don't recommend it. LSO is typically only used for mixed precision models, and may cause confusion is used for float32 models. If an LSO is used, the dynamic loss scale will be raised to a very high value, which won't cause issues but will cause confusion if a user queries the loss scale.

Also, LSO is not needed for bfloat16, and there is no need to check if the variable dtype and compute dtype differ, as the variable dtype should always be float32 if the compute dtype is float16. Therefore, the check can be simplified to be `layer.compute_dtype == tf.float16` for each layer. Granted, I understand you still don't want users to have to write that check. Perhaps you could have a `model_uses_mixed_precision` or `maybe_wrap_with_lso` function that does the check for them. Or, in `library_instance`, you can cache the LSO in a `dict` mapping from inner_optimizer to LSO, as I suggested in my previous comment.

> If not, is it possible to fix it ?

I think this is theoretically possible but would add a lot of complexity, so I don't think it is worth implementing.

Technical details follow where I describe how this could theoretically be implemented (no need to read this): Currently, the inner_optimizer has a trackable dependency named "loss_scale" on the loss scale. Since the inner_optimizer cannot have multiple dependencies with the same name, we cannot have multiple LSOs wrap the inner optimizer. However, we could instead have the inner_optimizer have a dependency on a list of loss_scales, one per LSO that wraps it. Each LSO would have an index into this list (but this index would not be saved in the checkpoint).

This approach would be difficult to implement and add a lot of complexity. I'm also not sure if it's possible, as there might be something I didn't consider that prevents this from working. So I don't think it is worth implementing this.

**Comment by keisen** [comment]
@reedwm , Thank you for your reply and kind instruction!


> LSO is not needed for bfloat16, and there is no need to check if the variable dtype and compute dtype differ, as the variable dtype should always be float32 if the compute dtype is float16.

That's good news for us!
As you said, we will provide a function to check model's variables.

> This approach would be difficult to implement and add a lot of complexity. I'm also not sure if it's possible, as there might be something I didn't consider that prevents this from working. So I don't think it is worth implementing this.

I understood why the approach should NOT be implemented. I agree with your opinion.


Thank you so much!
Best regards.
