### ISSUE TITLE
Tensorflow is not detecting  GPU but Pytorch is

### ISSUE THREAD

**Issue by tbhaxor** [tensorflow/tensorflow#48882]
Hi,

I am on Manjaro _5.4.114-1-MANJARO_ kernel. Pytorch is detecting the GPU and using it while training the model but TensorFlow
 is not detecting it.

![image](https://user-images.githubusercontent.com/28386721/116854848-f8990280-ac15-11eb-829c-364d85a3ac5e.png)

**Comment by tilakrayal** [comment]
@tbhaxor ,

In order to expedite the trouble-shooting process, could you please provide the following information
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:

Thanks!

**Comment by tbhaxor** [comment]
I solved this already by using community packages with python3.9
