### ISSUE TITLE
_pywrap_tensorflow_internal.so is enormous

### ISSUE THREAD

**Issue by crfrolik** [tensorflow/tensorflow#48902]
<em>Please make sure that this is a build/installation issue. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:build_template</em>

**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow version: 2.3
- Python version:  3.8
- Installed using virtualenv? pip? conda?: virtualenv and pip3

**Describe the problem**

`_pywrap_tensorflow_internal.so` is 591MB. Based on #40492 it sounds like there was some expectation that it would get smaller, but instead it seems to be getting larger. That issue was unfortunately closed with no action taken.

**Comment by shah9678** [comment]
the size of _pywrap_tensorflow_internal.so reflects TensorFlow's comprehensive capabilities, there are ways to manage or reduce the overall footprint of TensorFlow for specific applications or environments with constrained resources.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
