### ISSUE TITLE
in customized async op, should gpu allocate_output call be synchronized?

### ISSUE THREAD

**Issue by woodlgz** [tensorflow/tensorflow#48931]
Hi, I am using tensorflow 1.15 with horovod in which cusomized asynchronous op kernel is involved.
horovod implements its collective op by enqueuing collective request to its own runtime message queue, and in nvidia gpu environment, horovod uses its own cuda stream other than tensorflow gpu stream.
generally, horovod gpu allgather operation calls allocate_output and synchronizes on it (blocking host code). 
my question is that, if allocate_output return valid memory pointer as soon as the call return, why calling BlockHostUntilDone on tensorflow stream is necessary?
I checked tensorflow allocator implementation but got no clues. it appears to me that gpu memory allocation is done synchronously and actually not related to any stream.
a related discussion can be found [here](https://github.com/horovod/horovod/discussions/2877).

**Comment by Saduf2019** [comment]
@woodlgz 
Thank you for reporting your issue, we will update you at the earliest on this.

**Comment by Saduf2019** [comment]
@woodlgz 
Could you please upgrade to later versions of tf and let us know as tf 1.x is not actively supported on 2.x is.
You may refer to [this discussion](https://github.com/horovod/horovod/discussions).

**Comment by woodlgz** [comment]
hi, Saduf2019, it 's not a bug. it's just a confusion.
tensorflow 2.x should make no difference.

**Comment by sanjoy** [comment]
BFC allocator is asynchronous; and this is best illustrated with an example.  Consider a program that does:

```
// All work is enqueued on the compute stream
a = bfc_allocate(size=100);
do_work(a)
bfc_deallocate(a);
b = bfc_allocate(size=100);
do_work(b)
bfc_deallocate(b);
```

The second allocation, `b`, can reuse the memory from `a` even though when we execute `b` `do_work(a)` is running on the GPU and using the memory.  The assumption is that any use of `b` will be ordered after `do_work(a)` so all is well.

This means you can think of the BFC allocate / deallocate operations as conceptually "enqueued" on the compute stream, and the pointers returned by allocate are legal to use only after the GPU execution has reached the point where the allocation was enqueued.

For this reason `BlockHostUntilDone` is necessary -- work enqueued on the Horovod stream will not be totally ordered after the BFC allocate operations otherwise.  However `BlockHostUntilDone` is a large hammer; it should be sufficient to create a CUDA event on the compute stream and wait on it on the Horovod stream.

**Comment by woodlgz** [comment]
got it. thanks @sanjoy.
