### ISSUE TITLE
Tflite Hexagon delegate performance drop when upgrading from TF 2.2 to 2.4

### ISSUE THREAD

**Issue by yakovdan** [tensorflow/tensorflow#48934]
**System information**
- Have I written custom code: Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Windows 10, Android.
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Snapdragon 855 dev platform
- TensorFlow installed from (source or binary): source
- TensorFlow version (use command below): 2.2 and 2.4
- Python version: 3.8
- Bazel version (if compiling from source): 3.7
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A 
- GPU model and memory: N/A

**Describe the current behavior**

* A Keras model is converted to TfLite with full integer quantization and is executed on device using hexagon delegate.
When converted using Tensorflow 2.2, 97 of 99 nodes are a executed on DSP and good performance is achieved - 12 ms per inference. When the same model is converted using Tensorflow 2.4, the output TfLite NN has 112 nodes of which only 81 are executed on DSP an runtime is 40 ms - nearly 4 times worse! 

* When converted using Tensorflow 2.2, a run time of 12 ms is observed in an offline test. When running online (in an android app), run time of inference degrades to 18 ms. 

**Describe the expected behavior**

* Runtime (in an offline test) is expected to remain nearly the same when upgrading from Tensorflow 2.2 to Tensorflow 2.4
* Runtime difference between online and offline execution is expected to be much less than 6ms (18 ms vs 12 ms) as most of the network is offloaded to DSP. 

**Standalone code to reproduce the issue**
See [attached](https://drive.google.com/file/d/1yoPakbmxyhKXaXydn3RXLGMnsLdFl2t5/view?usp=sharing) a zip file with:
1. The Keras model
2. Conversion script
3. representative dataset for conversion
3. output TfLite model for TF version 2.2
4. output Tflite model for TF version 2.4
5. logs from TfLite benchmark utility for both TfLite model versions.

_usage:_ python convertandquantize.py
Switch from TF 2.2 to TF 2.4 in your environment between runs

**Comment by abattery** [comment]
@karimnosseir could you take a look at this?

**Comment by karimnosseir** [comment]
Short answer:
Can you please fix the batch size on the keras model before conversion.

Longer answer:
It looks like your model has dynamic batch, older versions TFLite converter used to ignore the dynamic batch on the original model. This was fixed and now the model generated can properly supports dynamic dimensions.
If you didn't specify a static shape during conversion, you will be missing some optimizations which happens during conversion.
That means the model will be running extra ops and some might not be supported on DSP, which will make it even slower, since the model will switch between CPU and DSP.
Please fix the batch size to '1' on the original keras model before conversion and retry.

See 

https://github.com/tensorflow/tensorflow/issues/46725#issuecomment-768534832

and https://github.com/tensorflow/tensorflow/issues/43882#issuecomment-731636562

**Comment by karimnosseir** [comment]
Please let us know if you are having issues.

Thanks
