### ISSUE TITLE
Get HLO PROTO from TF (in python)

### ISSUE THREAD

**Issue by KatiaSN602** [tensorflow/tensorflow#48967]
Hi,

I'm using `experimental_get_compiler_ir` to extract the HLO-IR of functions written in TF2. 
However, hitting some issues and was wondering if there is an API from TF, that exposes the proto format, something similar to what `JAX` does like here:
[xla_computation](https://jax.readthedocs.io/en/latest/jax.html#jax.xla_computation
) with the `as_serialized_hlo_module_proto`. 

There is probably a better way to go from TF code (in python) to HLO PROTO, but even when I'm using `experimental_get_compiler_ir`, maybe you could just allow this function to not serialize the result:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/jit/get_compiler_ir.cc#L136

Thanks!

**Comment by cheshire** [comment]
hi @KatiaSN602 , selecting `optimized_hlo_proto_serialized ` (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/jit/get_compiler_ir.h#L35) should give you back the proto, is that your question?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
