### ISSUE TITLE
Random rotation, flip, translation, and zoom for 3D data? 

### ISSUE THREAD

**Issue by llodds** [tensorflow/tensorflow#49000]
Does TF have any plan to support 3D random transform layers? or why not? Or is there already an experimental version or some other contributions on github related to this? Thanks

**Comment by bhack** [comment]
You  can check our repos:
https://github.com/tensorflow/graphics
https://ai.googleblog.com/2021/02/3d-scene-understanding-with-tensorflow.html
https://github.com/google-research/google-research/tree/master/tf3d

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
