### ISSUE TITLE
MultiWorkerMirroredStrategy for multiple gpus on a worker

### ISSUE THREAD

**Issue by chenxinhua** [tensorflow/tensorflow#49014]
could tensorflow provide official examples for MultiWorkerMirroredStrategy for multiple gpus on a worker.

**Comment by UsharaniPagadala** [comment]
@chenxinhua 
Could you please find the [documentation](https://www.tensorflow.org/guide/distributed_training) with an [example](https://www.tensorflow.org/tutorials/distribute/multi_worker_with_keras) . Thanks

**Comment by UsharaniPagadala** [comment]
@chenxinhua 
Could you please confirm if the issue still persist.Thanks

**Comment by ranjeetkgupta** [comment]
@chenxinhua. Were you able to figure this out ?? I am trying to run a similar scenario . multiple nodes , each node with multiple gpus. In this case do we run multiple workers(==no of gpus on that node) on each node, or just one worker on each node? From the documentation and examples, its not clear what happens when 1 worker has multiple gpus, or should we run multiple process in that case.
