### ISSUE TITLE
Converted model ERROR: Unsupported data type 14 in tensor

### ISSUE THREAD

**Issue by MaxxTr** [tensorflow/tensorflow#49045]
### 1. System information
Converted on:
- Widows 10
- TensorFlow 2.5.0

Run on:

- iOS 11.1
- POD installation:
- TensorFlowLite 2.4.0:

### 2. Code
regular tensroflowlite ios app example

### 3. Failure after conversion

ERROR:
Unsupported data type 14 in tensor

------------------------------------
Details:
I converted tensorflow model to tensorflow lite and tried to use it with iOS app (firstly on simulator) and unfortunately it makes an error during the interpreter build

Model path:
https://drive.google.com/drive/folders/1rdbLyp9BJWhz9oyR0-PAdsLPjcAzno6Z
You can ask for access if you need it

@mariaHit FYI

**Comment by MaxxTr** [comment]
@abattery thank you for fast response !!! But TF-Lite version 2.5.0-rc2 is not available through PODs...

**Comment by abattery** [comment]
@yyoon could you take a look at this? When will the POD for TensorFlow 2.5 be released?

**Comment by MaxxTr** [comment]
@sachinprasadhs let me check that everything work fin once I'm taking the nightly version and I'll definitely close this ticket

**Comment by MaxxTr** [comment]
@sachinprasadhs there is a new error:

TensorFlow Lite Error: Regular TensorFlow ops are not supported by this interpreter. Make sure you apply/link the Flex delegate before inference.
TensorFlow Lite Error: Node number 183 (FlexTensorListReserve) failed to prepare.

Failed to invoke the interpreter with error: Must call allocateTensors().

Can you please explain the meaning and the solution for this issue ?

Thank you

**Comment by yyoon** [comment]
The second error (`Invalid tensor index 1, max index is 0`) is likely caused by some tensor accessing code in your Swift code side.
Can you double check if you are passing the tensor index value correctly in your code?

**Comment by MaxxTr** [comment]
@yyoon You are totally right. My bad - I assumed the same tensor shape is it was for mobile net.
Just one additional question if you maybe ca assist me:

the run time of my converted net is HUGE ~45sec.
That's really surprising. Can you please redirect me to some guide about optimization of the converted nets ?

Thank you & best regards
Max

**Comment by yyoon** [comment]
There are some official docs on model optimization, which you can find here:
https://www.tensorflow.org/lite/performance/model_optimization

That being said, a single inference taking 45 sec is indeed huge. A few additional points which might be helpful to you.
* Make sure that you were using a real device (rather than a simulator), and make sure you were using release mode.
* Try using the [iOS benchmark app](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/lite/tools/benchmark/ios) and see what the numbers look like there.
* If you still see the 45s inference time, you might need to consider using a simpler model architecture to begin with.

cc/ @abattery @ethkim for any additional guidance on additional model optimization / removing select tf ops dependency.

**Comment by abattery** [comment]
The model is using the variant type. Currently, variant opeators can be supported through only the Select TF option.

**Comment by MaxxTr** [comment]
@yyoon  & @abattery  Thank you for your answers I'm closing this issue
