### ISSUE TITLE
Mac OS X GPU Support Request

### ISSUE THREAD

**Issue by hardmaru** [tensorflow/tensorflow#491]
Hi Team

Currently I've been doing some work with TensorFlow (some of my work on http://blog.otoro.net/) and have been developing everything a Macbook Pro running the IPython stack.  My Mac is fairly fast for regular sized tasks, and even has an NVIDA chip (NVIDIA GeForce GT 750M 2048 MB).  Although the current build doesn't support GPU's for Macs, it seems to me from reading earlier threads that it is not possible to custom build for GPU support on the Mac, despite having CUDA libraries installed.

This would really help out my work flow, especially I can get other frameworks to utilize my GPU / CUDA on the Mac.  The Macbook Pro is a great machine to develop use and develop stuff on, and lots of people I know also use MBP's to develop ML algorithms, and then send jobs off to AWS for the heavy-lifting after it works locally.

I think having GPU support for Mac would really help in not just the performance front, but allows us to debug and check any GPU specific issues when running some script locally, and be able to fix them quickly, before sending them to a EC2 or some remote GPU server.  It would make the workflow a lot smoother for developers who use Macbook Pro's with the NVIDIA chip.

Thanks in advance!

**Comment by ville-k** [comment]
Hi hardmaru!

I'm in the same situation  as you and was able to build TensorFlow on my Mac with GPU support. I have an open pull request for the changes:

https://github.com/tensorflow/tensorflow/pull/475

**Comment by hardmaru** [comment]
Hey Ville!

Thanks- I missed that pull request when browsing the history of issues.  Hopefully they will merge your request!  If not I'll try to do it manually.

Cheers.

**Comment by elbamos** [comment]
Since the PR is closed (hopefully temporarily) I thought a little reminder that a lot of us want this, would be helpful.

**Comment by vrv** [comment]
(it is just temporary, we may re-open it soon).

**Comment by seantrue** [comment]
This would be _very_ useful.

**Comment by ueser** [comment]
Agreed all comments. 

Tensorflow is a great tool but I see two bottlenecks for it to be widely used:
1. Many clusters have the old CentOS on which TF doesn't work
2. Many developers use MacBook Pro, and TF doesn't support GPU integration. 

I hope the team considers these issues.

**Comment by elbamos** [comment]
Let me just add to @ueser's comments, that many of us are on CUDA 7.5.  There are a lot of reasons for this, not the least of which is that if you're setting up a new machine, its a lot easier to get a working 7.5 installation with a current distro than a working 7.0 installation.  So part of what's needed is permitting compilation with 7.5.

**Comment by ville-k** [comment]
@elbamos I have a new open PR for OSX Cuda support that uses Cuda 7.5: https://github.com/tensorflow/tensorflow/pull/664

The PR makes it easier to test with different versions of cuDNN and Cuda by making the version of each framework a variable in the configure script.

**Comment by hurshprasad** [comment]
would running it in docker make any difference

http://stackoverflow.com/questions/25185405/using-gpu-from-a-docker-container

**Comment by ageitgey** [comment]
@hurshprasad I think those solutions are meant for Linux Docker hosts running Linux Docker images.

But Docker doesn't run natively on OS X like it does on Linux. When you run Docker on OSX, it actually boots a tiny Linux VM inside either VirtualBox or VMWare Fusion. Then that Linux VM is then what actually runs Docker. It's Russian nesting dolls :)

So to share an OS X GPU with a running Docker image, there's actually two levels of indirection: VirtualBox has to allow the Linux VM to access the host GPU. Then the Linux VM has to allow the docker images running inside of it to access that GPU. 

I'm not an expert, but I'd guess that making that work would be way harder than just supporting OS X GPUs directly in Tensorflow.

**Comment by Erstwild** [comment]
+1 for this feature.  With a thunderbolt e-gpu, you can do some solid work on a top spec macbook pro.

**Comment by lettergram** [comment]
+1 for this. I have a 2014 model with an NVIDIA GPU, it shouldn't be a super hard port.

**Comment by jesseengel** [comment]
+1, for all the reasons mentioned above

**Comment by danielravina** [comment]
+1

**Comment by normanhh3** [comment]
+1

**Comment by royalstream** [comment]
+1
Yes, the latest MacBook Pro / Mac Pro models do not offer NVIDIA as an option, but, apparently there's a MacBook Pro in the works for 2016 that will come with NVIDIA graphics.

**Comment by chrisloy** [comment]
+1

**Comment by horacechan** [comment]
+1

**Comment by joshburkart** [comment]
In order to keep the thread compact and easy to read, please consider just hitting "subscribe" instead of +1ing. (Also consider deleting previous posts that only have a +1 etc.)

**Comment by naono-git** [comment]
I use a linux machine for running TensorFlow, but I'm developing on MacBookPro (Early 2013) which has NVIDIA GeForce GT 650M. Though I have installed CUDA on my mac, TensorFlow wouldn't use GPU. Any support will help me quite a lot.

**Comment by sashaostr** [comment]
+1

**Comment by AbDaniel** [comment]
+1

**Comment by tj2013** [comment]
+1

**Comment by iRandD** [comment]
+1

**Comment by damirv** [comment]
+1

**Comment by esd100** [comment]
+1

**Comment by yazabaza** [comment]
It seems that there has been a pull request pending on this for several months: https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/yF6g1pfesCM
Does anyone know the status of this?

**Comment by elbamos** [comment]
If you read through, Google felt there were issues with the PR, but this has really been in their hands for a long time. I gave in and installed Linux on my Mac Pro.

It turned out that running data science in Linux was 4x-6x faster than with OS X on the same hardware, for both gpu and non-gpu tasks. Because the Mac multithreading just isn't as efficient.

So, while I totally get the issue folks have, honestly getting tf to use laptop gpus on OS X I don't think is going to buy you what you want, and you're gonna be happier switching to Linux for your computations.

**Comment by royalstream** [comment]
Honestly talking about "data science" as if it was just one thing that supposedly runs "4x faster" sounds like a very broad generalization, especially when the GPU is doing most of the work.

**Comment by anatoliykmetyuk** [comment]
@elbamos can you please give a link with more info on the performance? Or any way to reproduce the behaviour. Does Mac manage also the GPU threads? Aren't they supposed to be managed by the GPU controls and the drivers?

**Comment by esd100** [comment]
Check out this thread...

https://github.com/tensorflow/tensorflow/pull/664

https://gist.github.com/ageitgey/819a51afa4613649bd18

Reportedly, it should work.  Unfortunately, I tried it and although I got really close to doing a complete Bazel PIP build, it failed when trying near the end when going through the cuDNN v5 library. I'm not sure if it would work for you, but you should give it a try.

**Comment by elbamos** [comment]
I don't have any links to provide or anything like that. It's just my personal experience. 

But I'm someone who was running tensorflow on OS X with gpu early on (look at the thread), and I switched to Linux specifically because I do a lot of net training with gpus, so take what I have to say fwiw. 

An example: a few weeks ago I was on a deadline to finish training a deep net with torch when, having done something stupid, Linux decided that booting was no longer necessary. So I rebooted the machine into OS X. Using exactly the same code on exactly the same hardware with exactly the same data, on a gpu-centric application, with a dedicated gpu that wasn't driving any monitors, each epoch took roughly twice as long on OS X. That was with torch and cuda 7.5 and cudnn v 4. 

Processing a single image for demonstration purposes, including all preprocessing and reconstruction steps, took 1 min 15 seconds on OS X, and 20 seconds when I was ultimately able to get back into Linux.

I should add, the threading point is partly my speculation based on what I observed in performance running xgboost and other applications that use a multithreaded blas through R. For some reason applications seem to have an easier time using more cores on Linux. 

I was very surprised that gpu performance differed. My guess is that maybe the libraries, cuda and torch and such, aren't as optimized for OS X.

**Comment by anatoliykmetyuk** [comment]
Very interesting, indeed, but it doesn’t proof that the problem is fundamental to OS X’s architecture. We should try to isolate the problem and study it once we get a reliable way to compile TF under Mac. Maybe it was specific only to your particular configuration. I’ll try the instructions above later.

**Comment by elbamos** [comment]
You may be right. I will say, I observed this with torch, R, and tensorflow, all of them.

My point is, the folks who are very eager for Mac-tf-gpu support so they can run tf on the gpus in apple laptops, which aren't remotely cuda-optimized anyway, I think they're going to find that the book isn't worth the candle, and there are easier ways to accomplish what they want.

**Comment by jramapuram** [comment]
@elbamos: this is most likely not true. Can you please run the CUDA benchmarks on OSX and Linux for something simple like repeated GEMM calls (to ensure proper burn in) and report back?  CUDA provides examples that can natively be built on OSX and Linux. If you are seeing more cpu cores being used you are most likely using CPU BLAS and might be experiencing performance gains due to lack of host <-> gpu transfers.

**Comment by elbamos** [comment]
I'm positive that I wasn't using cpu blas. Because I tried forcing it to use cpu and that was an order of magnitude slower. I also fully believe that the performance on unit benchmarks is identical.  

If I have the time this weekend I may try to take some video of it.  And if there are particular benchmarks you'd like me to run, lay it out for me exactly what you'd like me to do and I'll give it a try.

**Comment by esd100** [comment]
In reality, people using mac os x should be exploiting the tremendous development platform which Apple has created. Using the XCode IDE, Instrument Profiler, Swift Language and new Metal API, developers could easily program script level, super-optimized (Clang LLVM), super-fast CPU/GPU compute software.

If you are curious about the Metal API, you can watch some of the videos from WWDC (https://developer.apple.com/videos/play/wwdc2015/610/). Unfortunately, I think you might have to watch them on Safari, because for some reason the videos only stream on safari.

In fact, I highly recommend checking out this guys, Amund Tveit, https://github.com/atveit, work...
https://github.com/DeepLearningKit/DeepLearningKit
https://github.com/atveit/SwiftMetalGPUParallelProcessing

**Comment by royalstream** [comment]
Well, I wouldn't be surprised if the CUDA drivers (or the NVIDIA drivers) for Mac aren't all that optimized at this point in time, considering Apple is not offering any laptop or workstation with NVIDIA as an option anymore.
This could change in the near future though.
But in any event, using the Mac as a development environment (including GPU support) should be supported.

**Comment by elbamos** [comment]
I really did not intend to send things in this direction

**Comment by esd100** [comment]
From my understanding, there is not a very huge difference in GPU compute performance of an NVIDIA card accepting assembly language instructions compiled form OpenCL (now the Metal API) libraries and assembly language instructions compiled from CUDA libraries. 

My conclusion is based on doing a google search for openCL vs. CUDA. For example, this post in 2010 from Accelereyes (now ArrayFire) shows subtle, but not huge differences in performance for various mathematical operations.
http://blog.accelereyes.com/blog/2010/05/10/nvidia-fermi-cuda-and-opencl/

**Comment by anatoliykmetyuk** [comment]
With introduction of Thunderbolt 2 and 3 technology, external GPUs will likely be supported in the near future. Even now I was able to connect a GPU to my MacBook Pro externally via Thunderbolt 2 and Akitio Thunder 2. So even if Mac is not optimized enough right now, this is most likely to change in the nearest future.

**Comment by vrv** [comment]
In #664 @ville-k added support and a few have verified it works -- we'll try our best to keep it running but we don't have a test machine so please continue to contribute to keep it working!

**Comment by orodbhen** [comment]
This press release from NVIDIA may be relevant to the performance issues mentioned.

https://blogs.nvidia.com/blog/2015/08/31/mac-driver/

**Comment by flaviostutz** [comment]
+1 on this!

**Comment by virl** [comment]
+1 on this. This issue especially important in the light of spreading eGPU support, like on these videos:
https://www.youtube.com/watch?v=jFHjT50M7_Y
https://www.youtube.com/watch?v=vvAB3U5umug
https://www.youtube.com/watch?v=JpR8_cS-168
https://www.youtube.com/watch?v=LN7prQBjRNc
https://www.youtube.com/watch?v=pNd5_kxpPc4

**Comment by amagrabi** [comment]
+1

**Comment by liufsd** [comment]
+1

**Comment by virl** [comment]
For everyone interested in official eGPU support in macOS, I recommend creating a ticket in Apple's bug reporter: https://bugreport.apple.com/logon
And mentioning my ticket via "Also see rdar://29836015"

**Comment by bryant1410** [comment]
[Bender](https://github.com/xmartlabs/Bender) supports running TensorFlow models in Metal API. It was tested on iPhone, not on Mac. But maybe with little changes it works for Mac!

**Comment by virl** [comment]
@bryant1410 No, it uses MetalPerformanceShaders and thus allows to execute '''already trained''' networks, not training with Metal.

**Comment by bryant1410** [comment]
Oh, yeah. It only allows to do inference, not training.
