### ISSUE TITLE
Implement ragged `tf.gather_nd` with `batch_dims > 0`.

### ISSUE THREAD

**Issue by foxik** [tensorflow/tensorflow#49148]
**System information**
- TensorFlow version (you are using): TF 2.4, TF 2.5rc3, TF-nightly
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**

Currently, using ragged `tf.gather_nd` with `batch_dims > 0` does not work:
```python
tf.gather_nd(tf.ragged.constant([[1,2], [3,4]]), tf.ragged.constant([[[0]], [[1]]], ragged_rank=1), batch_dims=1)
```
fails with
```python
ValueError: batch_dims != 0 is not supported for ragged gather yet.
```
https://colab.research.google.com/drive/10BIgfMaeO_rL3ZBQqXCHuoW0CZxnhh5S?usp=sharing

I propose for the missing functionality to be implemented.

**Will this change the current api? How?**

The API will stay the same, but an unsupported combination will be implemented.

**Who will benefit with this feature?**

Users using ragged tensors.

**Any Other info.**

Using non-ragged `tf.gather_nd` works
```python
tf.gather_nd(tf.ragged.constant([[1,2], [3,4]]).to_tensor(), tf.ragged.constant([[0], [1]]).to_tensor(), batch_dims=1)
```
as does does ragged `tf.gather_nd` with `batch_dims==0`
```python
tf.gather_nd(tf.ragged.constant([[1,2], [3,4]]), tf.ragged.constant([[[0]], [[1]]], ragged_rank=1), batch_dims=0)
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
