### ISSUE TITLE
Request: Function (or example) for shuffling a large dataset on disk

### ISSUE THREAD

**Issue by atyshka** [tensorflow/tensorflow#49242]
**System information**
- TensorFlow version (you are using): 2.4.1
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
There is currently no supported way to shuffle a large tfrecord dataset that does not fit into memory. For example, I am working with the Waymo Open Dataset, which consists of roughly 800 TFRecord files each with 200 frames of data. With 1TB of data it cannot be shuffled even with a very large 128GB memory. Ideally shuffling it would consist of writing to shards small enough to fit in memory, completely shuffling the shards randomly, and then randomly interleaving the shuffled shards. This would be a nice addition to the new experimental tf.data save and load APIs.

**Will this change the current api? How?**
Possibly? Either dedicated functions could be added, or this could be possibly achieved as a composition of existing tf.data operations.

**Who will benefit with this feature?**
Anyone using large datasets with tf.data

**Comment by bhack** [comment]
I don't know if using [Waymo TFDS](https://www.tensorflow.org/datasets/catalog/waymo_open_dataset) it can work with TFDS  [`shuffle_files` param](https://www.tensorflow.org/datasets/api_docs/python/tfds/load)

**Comment by atyshka** [comment]
TFDS would be a great solution but unfortunately the TFDS version is simplified and does not contain the original data format

**Comment by bhack** [comment]
I think that this is still valid https://github.com/tensorflow/tensorflow/issues/14857#issuecomment-347261151

**Comment by atyshka** [comment]
I tried that method but noticed I wasn’t getting truly random data. This is because the data is an ordered time series within each re-record file. Even though all 800 files are shuffled randomly, the data read from them is still in order. The first elements of the files are read first and the last elements are read last. This may seem like an insignificant difference in a large dataset, but I am experiencing loss spikes when I restart the epoch because it isn’t truly random.

**Comment by bhack** [comment]
So do you have the inverted use case of https://github.com/tensorflow/datasets/issues/113 ?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
