### ISSUE TITLE
Superflous keras-nightly dependency?

### ISSUE THREAD

**Issue by Flamefire** [tensorflow/tensorflow#49298]
**Describe the problem**

TF 2.5.0 added a dependency on keras-nightly for some reason with https://github.com/tensorflow/tensorflow/commit/d171d94d899cc73e18bd8b2b11b5c320ea7aac2c

However at no place there is an actual `import keras` or similar in the TF code, hence that package is completely optional at least or superflous it seems.

What was the reasoning for including that in the *required* dependencies of TF? Can it be removed?

I'd guess usually people use tf.keras or install TF then keras (for some reason), i.e. keras depends on TF (more or less) but now there is a dependency cycle.

**Comment by bhack** [comment]
I don't know but probably it is part of the program to prepare and test the migration https://github.com/keras-team/keras#under-construction

**Comment by Flamefire** [comment]
Oh great! Now even more confusion what "Keras" actually is :D

Well in any case: In 2.5.0 there still is tf.keras, so what is the keras dependency for in TF 2.5.0?

**Comment by bhack** [comment]
I suppose it is only to prepare/test the release infra when the standalone migration will completed. If you see the commit log Keras is now a sort of mirror/auto-sync https://github.com/keras-team/keras/commits/master

**Comment by Flamefire** [comment]
Sure, but that still leaves the question: What is it good for in TF 2.5? Or should it be a dependency of TF at all because it creates a circular dependency, e.g. keras directly uses TF at https://github.com/keras-team/keras/commit/4a978914d2298db2c79baa4012af5ceff4a4e203#diff-b25a4ff4c4bcd43013e75cefce6cc1dbe27b94312054aa3e132bcf10973e1787R19

**Comment by bhack** [comment]
If you want to have more details I think that we could collect more info from @qlzh727

**Comment by qlzh727** [comment]
Thanks for asking the question. In tf 2.5, keras package is included as a deps, but not actively used. We are in the final stage for switch tf to use keras as a dependency package (and the keras code in tensorflow/python/keras will be removed afterwards).

As for the dependency circle, there isn't any since tf shouldn't rely on any keras code at python level. There is only one way deps from Keras to TF. The keras PIP deps is added to TF so that tf.keras API could properly be exported. This is same as the tf estimator API.

**Comment by Flamefire** [comment]
> There is only one way deps from Keras to TF.

So that means that the keras package should have a dependency on the tensorflow package, shouldn't it?

> The keras PIP deps is added to TF so that tf.keras API could properly be exported.

I don't understand this. What does it mean to be "properly exported"? And why does this require keras to be installed (which is what the pip dep means)?

**Comment by qlzh727** [comment]
> > There is only one way deps from Keras to TF.
> 
> So that means that the keras package should have a dependency on the tensorflow package, shouldn't it?
> 
> > The keras PIP deps is added to TF so that tf.keras API could properly be exported.
> 
> I don't understand this. What does it mean to be "properly exported"? And why does this require keras to be installed (which is what the pip dep means)?

I see why you get confused here.

If you thinking from API and layering perspective, for any python code, keras code can rely on TF for underlying ops and other lib, but not the other way around (tf low level ops, or high level API like tf.dataset or tf.distribute shouldn't aware of keras). In this sense, the dependency direction is from Keras to TF.

When we talk about PIP package, the dependency is the other way. tf.keras is a namespace that contain keras APIs. When the actual keras code lives in keras-nightly PIP package, tf will need keras as a PIP dependency, so that tf.keras namespace can be properly populated. This is why keras-nightly (in future, keras PIP) is a TF PIP dependency.

We break this circle by not including TF in the Keras PIP package requirement, and only expecting user to have the proper tf PIP installed on their local env. See https://github.com/keras-team/keras/blob/master/keras/tools/pip_package/setup.py#L35, the required dependency doesn't have tf or tf-nightly listed.

**Comment by Flamefire** [comment]
>  tf.keras is a namespace that contain keras APIs. When the actual keras code lives in keras-nightly PIP package, tf will need keras as a PIP dependency, so that tf.keras namespace can be properly populated. This is why keras-nightly (in future, keras PIP) is a TF PIP dependency.

Thanks for the explanation, please allow me to ask another question to be sure that I understood that correctly:
The goal is to move the current code under `tf.keras.*` into a separate (pip) package so that `tf.keras == keras`, i.e. `import tf.keras as keras` and `import keras` are essentially equivalent and the TF package does not contain the actual code of that namespace anymore. Is that correct?
From what I see this is currently not done, i.e. TF 2.5.0 does still contain all the code under `tf.keras` and doesn't actually need `keras-nightly`, so that dependency is only a preparation for a future change removing that code, isn't it? In that case one could remove the keras dependency from 2.5.0.

Just a thought here: If the goal is to have tf.keras basically be an alias to keras, then maybe it could be made optional: I.e. if a user tries to import tf.keras and keras is not installed an error is shown. Because from an engineering point of view the dependency is from keras to TF and that not being declared as such looks like a workaround to me. (see the comment in the keras setup.py, i.e. users could `pip install keras` and it won't work)

And maybe a general question to keras because we need to teach the users at our HPC cluster on using it:

Previously I understood the following, could you please check if this (still) holds true:
- "Keras" is an (abstract) API for machine learning (especially deep learning), i.e. it defines the interfaces
- tf.keras is an implementation of that API using TF to run the operations (i.e. TF is the "backend")
- "keras" (at least used to be) an implementation of the "Keras" API which can use different ML frameworks (e.g. TF or PyTorch, I think Theano was there too) as the backend

I.e. the goal of the Keras API to me seemed to be to allow users to switch the implementations (backend) without changing their code when they code against the Keras API.

What now confuses me is from the linked file this line: https://github.com/keras-team/keras/blob/4a978914d2298db2c79baa4012af5ceff4a4e203/keras/tools/pip_package/setup.py#L15

It says "TensorFlow Keras." Does this mean that the "keras" package can only use TF as the backend and nothing else? So the keras (pip) package does no longer allow switching the backends? Or was there another package which did allow this?

**Comment by qlzh727** [comment]
> > tf.keras is a namespace that contain keras APIs. When the actual keras code lives in keras-nightly PIP package, tf will need keras as a PIP dependency, so that tf.keras namespace can be properly populated. This is why keras-nightly (in future, keras PIP) is a TF PIP dependency.
> 
> Thanks for the explanation, please allow me to ask another question to be sure that I understood that correctly:
> The goal is to move the current code under `tf.keras.*` into a separate (pip) package so that `tf.keras == keras`, i.e. `import tf.keras as keras` and `import keras` are essentially equivalent and the TF package does not contain the actual code of that namespace anymore. Is that correct?

This is correct.

> From what I see this is currently not done, i.e. TF 2.5.0 does still contain all the code under `tf.keras` and doesn't actually need `keras-nightly`, so that dependency is only a preparation for a future change removing that code, isn't it? In that case one could remove the keras dependency from 2.5.0.

TF 2.5 is still using keras code under tensorflow/python/keras, and NOT using code from keras-nightly. You observation is correct. It is indeed a preparation. User could turn on the Keras pip package by config a env var (_PREFER_OSS_KERAS), see https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/api_template.__init__.py#L87
> 
> Just a thought here: If the goal is to have tf.keras basically be an alias to keras, then maybe it could be made optional: I.e. if a user tries to import tf.keras and keras is not installed an error is shown. Because from an engineering point of view the dependency is from keras to TF and that not being declared as such looks like a workaround to me. (see the comment in the keras setup.py, i.e. users could `pip install keras` and it won't work)

Keras couldn't be a optional deps package for tensorflow, since tf API namespace has a strong contract and we can't easily make tf.keras not available. When user "pip install tensorflow", we would expect keras pip to be installed as well.
> 
> And maybe a general question to keras because we need to teach the users at our HPC cluster on using it:
> 
> Previously I understood the following, could you please check if this (still) holds true:
> 
> * "Keras" is an (abstract) API for machine learning (especially deep learning), i.e. it defines the interfaces
> * tf.keras is an implementation of that API using TF to run the operations (i.e. TF is the "backend")
> * "keras" (at least used to be) an implementation of the "Keras" API which can use different ML frameworks (e.g. TF or PyTorch, I think Theano was there too) as the backend
> 

Currently there isn't a difference between tf.keras and Keras, since keras package is now single backend (TF only). @fchollet will have more details.

> I.e. the goal of the Keras API to me seemed to be to allow users to switch the implementations (backend) without changing their code when they code against the Keras API.
> 
> What now confuses me is from the linked file this line: https://github.com/keras-team/keras/blob/4a978914d2298db2c79baa4012af5ceff4a4e203/keras/tools/pip_package/setup.py#L15
> 
> It says "TensorFlow Keras." Does this mean that the "keras" package can only use TF as the backend and nothing else? So the keras (pip) package does no longer allow switching the backends? Or was there another package which did allow this?

Yes, the current road map for keras is have TF as the single backend only. @fchollet

**Comment by bhack** [comment]
Some of there are natural questions then soon or later we will need to put somewhere in a visibile FAQ/Readme
