### ISSUE TITLE
Need clarity on metrics reported in extras field on using run_op_benchmark

### ISSUE THREAD

**Issue by aditisaluja5** [tensorflow/tensorflow#49369]
## URL(s) with the issue:
https://www.tensorflow.org/api_docs/python/tf/test/Benchmark

## Description of issue (what needs changing):

I ran a simple tf.linalg.matvec operation using the benchmark framework and got different metrics in the extras field. I could not understand the difference between the keys in the extra field - allocator_max_num_bytes_GPU_0_bfc and allocator_max_num_bytes_gpu_host_bfc.

More  description of these metrics would help users understand what metrics are actually being  reported.

**Comment by tilakrayal** [comment]
@aditisaluja5 ,

We see that the [issue template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue.

Looks like the issue is with gpu memory allocation.Please try limiting [GPU memory growth](https://www.tensorflow.org/guide/gpu#limiting_gpu_memory_growth) using any of the methods listed here and check if it helps. Thanks!
