### ISSUE TITLE
Tensorflow and emscripten

### ISSUE THREAD

**Issue by loretoparisi** [tensorflow/tensorflow#4940]
Any plans to add the build chain for emscripten?
At this time there is this attempt https://github.com/tomasreimers/tensorflow-emscripten, but a official supported would be awesome!

**Comment by jart** [comment]
Do you have a design doc?

In order to merge a feature like this, it would ideally be configured using Bazel, possible using [cc_toolchain()](https://github.com/bazelbuild/bazel/blob/master/src/main/java/com/google/devtools/build/lib/rules/cpp/CcToolchain.java). Our Makefile build system is community supported and intended for platforms that aren't able to run Bazel.

**Comment by mhyttsten** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by loretoparisi** [comment]
@jart this issue was closed for inactivity, by the way any recent progress or contribute in that direction for the build chain (I guess it has changed a bit...)? Thanks.

**Comment by Yongle-Fu** [comment]
Any things update? i need build tensorflowlite_c code into emscripten static library(.a).
