### ISSUE TITLE
Random number generation with tf.function in tf 2.5.0

### ISSUE THREAD

**Issue by robertnoest** [tensorflow/tensorflow#49463]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux CentOS 7.6
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: No
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: None
- GPU model and memory: None

**Describe the current behavior**
Example provided on your website here: https://www.tensorflow.org/guide/random_numbers#passing_generators_as_arguments_to_tffunction leads to num_traces=2. This results in excessive retracing and thus slowdown in custom code. Noticed it after upgrading to 2.5.0 from 2.3.1.

**Describe the expected behavior**
As documentation describes num_traces=1 is expected, which it does produce in tf 2.3.1. 

**Standalone code to reproduce the issue**
```
import tensorflow as tf 

num_traces = 0
@tf.function
def foo(g):
  global num_traces
  num_traces += 1
  return g.normal([])
foo(tf.random.Generator.from_seed(1))
foo(tf.random.Generator.from_seed(2))
print(num_traces)
```

**Comment by tilakrayal** [comment]
I was able to reproduce the issue in TF v2.5.0,2.3.1 and nightly.Please find the [gist](https://colab.research.google.com/gist/tilakrayal/0a281490403fa60c744e9faccd5f4b81/49463.ipynb) here.

**Comment by wangpengmit** [comment]
Yeah, different `tf.random.Generator` objects used to not cause retracing, but the mechanism to achieve that (making `tf.random.Generator` a subclass of `CompositeTensor`) is broken in many cases. `tf.random.Generator` is basically a `tf.Variable`, and since we aren't able to make `tf.Variable` a `CompositeTensor`, neither can we for `tf.random.Generator`. Notice that if you do `foo(tf.Variable(1)); foo(tf.Variable(2))`, you'll also get 2 traces, so the current `tf.random.Generator` behavior is consistent with `tf.Variable`. I'll update the RNG guide.

**Comment by wangpengmit** [comment]
Guide updated.
