### ISSUE TITLE
all_ops_resolver and custom ops

### ISSUE THREAD

**Issue by Lucy20211** [tensorflow/tensorflow#49468]
In case I had to implement a generic op unsupported by TF Lite and specify layers of my model, for example like this:

`tflite::MicroMutableOpResolver<2> micro_op_resolver; `
`micro_op_resolver.AddConv2D(); `
`micro_op_resolver.AddX();`

where AddX() is the unsupported op which I have to create, what for its registration in all_ops_resolver.cc?

**Comment by ymodak** [comment]
https://www.tensorflow.org/lite/guide/ops_custom#example_custom_sin_operator shows implementation of custom ops which you may use as reference for your case. In case the guide is not covering your areas of interest perhaps you can mention what is it that you are looking for and what changes you wish to see in the guide so that it may help for use cases like yours.
Thank you.

**Comment by Lucy20211** [comment]
In my case I'm not sure: 
- which folder to put my implementation of a custom operator in;
- if I have to modify all_ops_resolver.cc or not: it is not mentioned in the tutorial, but I have to use Add ops (AddConv2D, AddFullyConnected for example) in all_ops_resolver.cc and to use a custom ops which is in this file;
- if I have to modify register.cc in tensorflow/tensorflow/lite/kernels.

**Comment by karimnosseir** [comment]
Added Nat as this is for tflite micro.
Nat can you please advice here.

Thanks

**Comment by njeffrie** [comment]
Apologies for the delay - 
all_ops_resolver.cc simply catches all possible ops in TFLM. If you are creating a custom op and your example uses a MicroMutableOpResolver, you do not need to add your op to all_ops_resolver.

We typically do add all TFLM supported ops to the all_ops_resolver so that users can use all_ops_resolver rather than creating a custom MicroMutableOpResolver.

If you have follow-up questions please file an issue against the [TFLM repo](https://github.com/tensorflow/tflite-micro/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).
