### ISSUE TITLE
 How to convert TFLite quantization model back to normal TFLite model?

### ISSUE THREAD

**Issue by jwj04ok** [tensorflow/tensorflow#49482]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 16.04
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.4.1

### 2. Question

How to convert TFLite quantization model back to normal TFLite model?

The models I compared are from https://www.tensorflow.org/lite/guide/hosted_models
1. https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_02_22/mobilenet_v1_0.75_224.tgz
2. https://storage.googleapis.com/download.tensorflow.org/models/mobilenet_v1_2018_08_02/mobilenet_v1_0.75_224_quant.tgz

I tried to converted the second quantized model back to float model based on the quantization info from interpreter.get_tensor_details(). 

Issue 1:
The weight/bias info after converted back to float is totally different from those info from the normal tflite model. This is explained in this question that quantized model and normal models are from different training. https://github.com/tensorflow/tensorflow/issues/49119

Issue 2:
If I just converted quantized model back to normal model, the model will lack the activation function after each CONV node (RELU6 in this model), which could result in unconstrained range for output after each layer. At the end, the layer result could be extremely big or small (negative).
Therefore I add a 0-6 clip node after each CONV layer to eliminate extreme number. However, the final inference result is still away from the result of normal TFLite model.

Is there anything I did wrong?
Any suggestion to converted back quantized model to normal TFLite model?

**Comment by abattery** [comment]
We don't have such feature yet. We consider this as a feature request. Thanks

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
