### ISSUE TITLE
negative sampling in Word2Vec tutorial

### ISSUE THREAD

**Issue by bizzyvinci** [tensorflow/tensorflow#49490]
## URL(s) with the issue:
[negative sampling](https://www.tensorflow.org/tutorials/text/word2vec#negative_sampling_for_one_skip-gram)
[generate training data](https://www.tensorflow.org/tutorials/text/word2vec#generate_training_data)

## Description of issue (what needs changing):
I was going through the tutorial on skipgram word2vec and I noticed that positive sample candidates are also negative sample candidates too.

### Clear description
For example, we have `sentence = "The wide road shimmered in the hot sun"` and `window_size = 2` for `tf.keras.preprocessing.sequence.skipgrams`. Therefore positive skip-grams for include `(road, the), (road, wide), (road, shimmered), & (road, in)`. 

**I guess `the, wide, shimmered, & in` should not be later labeled as negative skip-grams for `road`, right?**.

PS: I'm a newbie

**Comment by Saduf2019** [comment]
@bizzyvinci 
Thank you for the request, we will update you on the earliest on this.

**Comment by gqqnbig** [comment]
The incorrect negative samples are calculated from `tf.random.log_uniform_candidate_sampler`, which may have bugs. See #44758.

**Comment by 8bitmp3** [comment]
Thank you @bizzyvinci and @gqqnbig. We'll look into this cc @MarkDaoust

**Comment by wangpengmit** [comment]
Please see my comment https://github.com/tensorflow/tensorflow/issues/44758#issuecomment-916554100 . The phrase "negative samples" may have different meanings in different candidate-sampling algorithms. For some algorithms "negative samples" can overlap with true classes. 

We do need to mention this caveat in the tutorial though.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
