### ISSUE TITLE
Make a TensorFlow official conda channel

### ISSUE THREAD

**Issue by otavio-silva** [tensorflow/tensorflow#49555]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.3
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
The feature will be to release TensorFlow and related packages like TensorFlow-Hub, TensorFlow-Datasets, Tensorflow-Extended, etc. through an official conda channel, in a similar way to Pytorch does currently.

**Will this change the current api? How?**
I don't believe there will be any significant changes to the API in regards to this

**Who will benefit with this feature?**
All Anaconda, Miniconda and similar users will benefit from this, it does facilitate the installation process a lot and to have all TensorFlow related packages in a centralized environment (if I'm not mistaken, ass TensorFlow dependencies are on conda some way or another, including the CUDA Toolkit and cuDNN)

**Any Other info.**
as seen [here](https://github.com/tensorflow/tensorflow/issues/35754) a lot of people are currently interested in this and it would be beneficial to everyone.

**Comment by mihaimaruseac** [comment]
We don't have enough developers for this internally, so it has to come from the community, just like it is.

**Comment by h-vetinari** [comment]
Hey, I've been wanting to comment on this, but it's been languishing on my todo-list - sorry.

I'm one of the people who helps package tensorflow for conda-forge, _the_ main channel these days for pretty much everything, particularly in the scientific computing / data science space. There are some trade-offs for having everything in one channel, but a lot of upsides too (homogeneous infra guarantees binary-compatible builds across whole channel, supports various architectures, GPUs, and even different runtimes like PyPy, etc. etc.).

In fact, there's a lot of interest in packaging tensorflow for conda-forge, but by far the biggest bottleneck is the fact that TF builds time out in the standard Azure CI that MSFT provides for GH (6h). This leads to extremely painful debugging, because - contrary to the ususal PR+CI model - someone has to retrigger builds locally for every change. Almost exclusively due to this, there's been long delays in packaging TF releases in conda-forge.

Since I saw this issue, I've been mulling to propose a collaboration on this, in the sense that the conda-forge community would be able to provide high-quality packaging for this (and do all the conda packaging effort, essentially), but we'd really need support on the CI front, where building the various tensorflow releases & flavours could be done.

Would that be interesting to the tensorflow developers and their sponsors? (CI isn't free, unfortunately...)

CC @xhochy @beckermr @wolfv @isuruf @jakirkham

**Comment by mihaimaruseac** [comment]
That would be nice. What would be the differences between your environment and the env TF releases use to build? Can you join SIG Build meetings (unfortunately the most recent one just finished) and we can discuss this there?

**Comment by h-vetinari** [comment]
Cool, awesome to hear! 🙃 

I don't know the repo-structure here - I looked here and in the TF org, but couldn't find where the conda packages are built?

For conda-forge, everything is done in the so-called "feedstock" repo on GH: https://github.com/conda-forge/tensorflow-feedstock/

The [recipe](https://github.com/conda-forge/tensorflow-feedstock/blob/master/recipe/meta.yaml) there is fully self-contained (although, by that I mean the recipe [folder](https://github.com/conda-forge/tensorflow-feedstock/tree/master/recipe) and all its content). Note that we'd love to keep the recipe as stupidly simple as possible (i.e. requirements + `pip install` or something**) - everything else there has unfortunately "earned" its place as a necessity (at least currently). CUDA builds are not supported yet, but that's just due to the above-mentioned CI problem - conda-forge has the capability to build GPU packages, and does so extensively.

Regarding joining meetings, I'm willing to join (timezone-permitting), and I'm almost certain that there'd be other maintainers of the tensorflow-feedstock (or conda-forge/core itself) that would be interested in moving this forward.

** In the case of TF, it makes sense to provide several outputs (e.g. with python-bindings, as well as just a C++ lib), so that rule would apply to each of those outputs, which are allowed to depend on each other in the form of a DAG.

**Comment by beckermr** [comment]
Another opportunity here is to use conda-forge to provide CPU versions with more SIMD optimization than you get in other spots.

**Comment by h-vetinari** [comment]
> Can you join SIG Build meetings (unfortunately the most recent one just finished) and we can discuss this there?

@mihaimaruseac any plans for the next SIG Build meeting?

**Comment by mihaimaruseac** [comment]
Every first Tuesday of the month (with exception for June/July due to US holidays)

bit.ly/tf-sig-build-notes


There is also a link in the title there to Add the event to your Google Calendar

**Comment by sh-shahrokhi** [comment]
Any news on this?
