### ISSUE TITLE
 Due to the upgrade tensorflow2.5.0,I cannot load weights which tf2.4.0 canload,maybe the reson is  the h5py from 2.10.0 to 3.1.0,I want to use tf2.5.0 to load the  pretrain model,how can I do?

### ISSUE THREAD

**Issue by successAI** [tensorflow/tensorflow#49597]
ValueError: in user code:

    E:\git_projects\segmentation\deeplabv31\subpixel.py:91 call  *
        return self._phase_shift(super(Subpixel, self).call(inputs))
    D:\software\soft\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\keras\layers\convolutional.py:273 call  **
        outputs.set_shape(out_shape)
    D:\software\soft\Anaconda3\envs\tf2\lib\site-packages\tensorflow\python\framework\ops.py:777 set_shape
        raise ValueError(str(e))

    ValueError: Dimension 1 in both shapes must be equal, but are 150 and 1200. Shapes are [?,150,150,128] and [?,1200,1200,2].

**Comment by tilakrayal** [comment]
@successAI ,

In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

Also please take a look at the links with similar error.[link1](https://stackoverflow.com/questions/41835789/tensorflow-valueerror-dimension-0-in-both-shapes-must-be-equal),[link2](https://stackoverflow.com/questions/41800643/valueerror-dimensions-must-be-equal-but-are-1-and-3-for-conv2d-op-conv2d/41880215),[link3](https://github.com/matterport/Mask_RCNN/issues/604).It helps.

Thanks!
