### ISSUE TITLE
Android example giving wrong results on Samsung Galaxy A3

### ISSUE THREAD

**Issue by JosiahKane** [tensorflow/tensorflow#4966]
I've built the android demo and installed the same APK on 3 phones: Samsung S6, HTC one M9, and Samsung Galaxy A3. 
On the Galaxy A3 only the results are wrong; whereas the other phones give sensible results for various things in the office (photocopier, monitor, laptop etc) the A3 produces much lower scores and suggests things like oscillascope and nematode.

Additionally, the preview window is small and skewed. Suspecting an odd resolution might have confused things, I forced it to 640*480 but the problem persists. 

I do not know whether this is unique to the A3 .

**Comment by andrewharp** [comment]
Hi, would you mind posting a screenshot and the adb log please? Also you can grab the actual image being classified by turning on SAVE_BITMAP in TensorFlowImageListener.java, which could be helpful to see.

**Comment by andrewharp** [comment]
Also, what version of Android is your A3 running?

**Comment by JosiahKane** [comment]
I'm afraid the phones are at work; I'll provide the requested details on Monday. 
Sorry.

**Comment by JosiahKane** [comment]
I believe this is the requested information. 

Screenshot (For comparison, most other phones would say photocopier)
![screenshot_2016-10-17-09-45-59](https://cloud.githubusercontent.com/assets/6673752/19431097/ef44edd6-944e-11e6-8275-14e2d9991b08.png)

Preview image, which seems rather bad!
![preview](https://cloud.githubusercontent.com/assets/6673752/19431103/f3c0d3b6-944e-11e6-90ee-87ae7a0e20e5.png)

adb log
[TensorFlow_A3.txt](https://github.com/tensorflow/tensorflow/files/532792/TensorFlow_A3.txt)

I cannot promise that the preview image matches the same run through the network as the screenshot.

**Comment by riless** [comment]
Samsung Galaxy A3 comes by default with Android 4.4.4.

And it seems that the [ImageUtils.convertYUV420ToARGB8888](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/src/org/tensorflow/demo/TensorFlowImageListener.java#L164) function that makes the conversion from raw camera output to RGB format isn't compatible with versions of Android <= 5.1.1 due to a [bug on android](https://code.google.com/p/android/issues/detail?id=81984)

See issues [#4911](https://github.com/tensorflow/tensorflow/issues/4911) and [#306](https://github.com/tensorflow/tensorflow/issues/306)

So the solution is to update Android to +5.1.1, or adapt YUV2RGB function to this version of Android.

**Comment by JosiahKane** [comment]
Thank you for the information.
