### ISSUE TITLE
Performance of using dicts in tf.data.Dataset.from_generator

### ISSUE THREAD

**Issue by ChWick** [tensorflow/tensorflow#49727]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 21.04, Colab
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.4.1 and 2.5.0
- Python version: 3.7

Using dicts as input structure for a `tf.data.Dataset.from_generator` is significantly (>40%) slower than using tuples. Wrapping the nested dict structure in `tf.nest.flatten` and `tf.nest.pack_sequence_as` is only a bit (<10%) slower than using plain tuples.

Maybe consider to "speed-up" the use of nested structures such as dicts, e.g. by internally flatten and "unflatten" the input.

See the attached colab code. I included some additional benchmark results on my machines.

https://colab.research.google.com/drive/12pGU80HJXFSh7lqhdsWaTyeeHyWwovPe?usp=sharing

**Comment by tilakrayal** [comment]
@ymodak 
I was able to reproduce the issue in TF [v2.4](https://colab.research.google.com/gist/tilakrayal/47dea112f28a763f31fc6499c93904fd/49727-2-4.ipynb),[v2.5](https://colab.research.google.com/gist/tilakrayal/e65c7349ce7e2d034523f8e10067b37d/49727-2-5.ipynb) and [nightly](https://colab.research.google.com/gist/tilakrayal/39a161598b1e813450d47525896c7a24/49727-nightly.ipynb).Please find the gist.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
