### ISSUE TITLE
tensorflowlite quantized model get incorrect output in tensorflowlite C API

### ISSUE THREAD

**Issue by YaoChen5566** [tensorflow/tensorflow#49854]
@tensorflow/micro

**System information**
- Host OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 16.04
- TensorFlow installed from (source or binary): 
- Tensorflow version (commit SHA if source): r2.4
- Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Qualcomm Snapdragon XR2 

**Describe the problem**
I have two tflite model, one is quantized to float16 the other is quantized to full integer. Both model can get correct result on python for PC. But only model quantized to float16 get correct result on tensorflowlite C API. Model quantized to int8 with different input always get the same output. Both model run for CPU on Qualcomm Snapdragon XR2.

Model quantized to float 16: [link](https://drive.google.com/file/d/119wMGk2Z-Kx4o-Zxji4h-KOmDVuwG3Rq/view?usp=sharing)
Model quantized to full integer: [link](https://drive.google.com/file/d/1oEHtKag7AM_FFNkgyIGg2PsAGt3zERKm/view?usp=sharing)

Thanks

**Comment by oniigiirii** [comment]
I am currently facing the same problem on a different target platform, namely an Xtensa hifi3 digital signal processor. 
The int8 quantized model always returns the same incorrect value as output. Furthermore, the cehcking the input/output types through`tflite::MicroInterpreter` returns `kTFLiteFloat32` types for both input and output tensors, although the model was quantized using int8 inputs/outputs/weights.  

I opened an [issue](https://github.com/tensorflow/tflite-micro/issues/1975)  for it in the TFLiteMicro Repository where more details can be found.

Thanks in advance.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
