### ISSUE TITLE
TfLite C API safety requirements

### ISSUE THREAD

**Issue by Nugine** [tensorflow/tensorflow#49899]
## URL(s) with the issue:

https://github.com/tensorflow/tensorflow/blob/eaa6753876e6a5974258e7244f46bfe8b27f906d/tensorflow/lite/c/c_api.h#L142-L152

### Clear description

What would happen if the user does not follow the calling order?

Does the interpreter perform a runtime safety check?

Can I read the input tensors before I fill values into them?

**Comment by abattery** [comment]
When you try to access `TfLiteTensor` objects through the `TfLiteInterpreterGetInputTensor` method before the allocation, the `TfLiteTensor`'s `data` field won't have valid memory address since it hasn't allocated.

**Comment by Nugine** [comment]
> When you try to access `TfLiteTensor` objects through the `TfLiteInterpreterGetInputTensor` method before the allocation, the `TfLiteTensor`'s `data` field won't have valid memory address since it hasn't allocated.

What if I read the tensor immediately after allocation? Is it uninitialized or filled with zeros?

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
