### ISSUE TITLE
SafeH2DMemcpy removed in thunk

### ISSUE THREAD

**Issue by VertexC** [tensorflow/tensorflow#49914]
I am looking into some profiling issue of XLA. I noticed that in tf2.5 and newer **SafeH2DMemcpy** part is remove from convolution_thunk.cc/custom_call_thunk/convolution_thunk.

By looking into old code of convlution_thunk's memcpy part
```python

  // Write the output tuple.
  const int kNumOutputs = 2;
  auto ptrs = absl::make_unique<void*[]>(kNumOutputs);
  ptrs[0] = result_buffer.opaque();
  ptrs[1] = scratch.opaque();
  se::DeviceMemory<void*> tuple_addr(
      buffer_allocations.GetDeviceAddress(tuple_result_buffer_));
  SafeH2DMemcpy(tuple_addr, std::move(ptrs), kNumOutputs, params.stream,
                params.deferred_host_callbacks);
```
I am wondering
- What are result_buffer, scratch_buffer and tuple_result_buffer here? Are they cpu buffer or gpu buffer?
- Why it does a H2D copy instead of D2H copy? Why result is not from gpu to cpu? 
- Why this memcpy is now removed? What is the original purpose of this?

Would really appreciate any ideas on this.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
