### ISSUE TITLE
Model converted to TFlite performs slow during inference

### ISSUE THREAD

**Issue by rohanshingade** [tensorflow/tensorflow#49931]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.5.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version:
- GPU model and memory: No

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

**Describe the current behavior**
Tensorflow saved model converted to TFlite model gives poor performance during inference. The inference time is same as (or greater than in some cases) tensorflow model

**Describe the expected behavior**
Inference time should be low according to the documentation

**[Contributing](https://www.tensorflow.org/community/contribute)** - Do you
want to contribute a PR? (yes/no): - Briefly describe your candidate solution
(if contributing): Yes

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.
https://colab.research.google.com/drive/16IAyeNAIdfgRrS1CLhOqBrAc0bvFNt5A?usp=sharing

**Comment by tilakrayal** [comment]
@rohanshingade ,

I do not have access to the link you have provided. Could you please provide the required permissions to view the files.

**Comment by rohanshingade** [comment]
@tilakrayal updated.
https://colab.research.google.com/drive/16IAyeNAIdfgRrS1CLhOqBrAc0bvFNt5A?usp=sharing

**Comment by renjie-liu** [comment]
Hi, it seems you're benchmarking on workstations, TFLite is not well optimized for x86 comparing to Tensorflow.

**Comment by multiverse-tf** [comment]
> Hi, it seems you're benchmarking on workstations, TFLite is not well optimized for x86 comparing to Tensorflow.

We have done optimizations for x86, but they are not likely enabled (probably due to the OS+compiler used when building the tflite distribution). I guess this is why you see slow inference in the colab environment.

Could you build your own tflite distribution on your workstation and benchmark the model performance? You could use either bazel or cmake ([guide](https://www.tensorflow.org/lite/guide/build_cmake)) to achieve this.

* when using bazel, pls explicitly add "-c opt --define=tflite_with_ruy=true --define=tflite_with_xnnpack=true"
* when using cmake, pls turn on TFLITE_ENABLE_RUY option as described [here](https://www.tensorflow.org/lite/guide/build_cmake#available_options_to_build_tensorflow_lite)

**Comment by rohanshingade** [comment]
@multiverse-tf i tried what you suggested but there was no improvement in performance
Inference time for
Out of the box model: 59 seconds
TF model convert to Tflite model: 21 mins

**Comment by sushreebarsa** [comment]
Was able to replicate the issue with TF 2.6.0-dev20210606,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/12dd5455a7ed54d88f26dffac540d649/untitled233.ipynb) ..Thanks !

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
