### ISSUE TITLE
SparseTensor indices stored as tf.int32 instead of tf.int64

### ISSUE THREAD

**Issue by jocampo2** [tensorflow/tensorflow#49993]
`tf.SparseTensor ` currently only accepts indices as `tf.int64`. Which mean memory of indices > values (`tf.float32`) in general. Would it make sense to have an option to store indices as `tf.int32`? This would be useful for storing large sparse matrices where the index values are < 2^32 as it would free up some RAM

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
