### ISSUE TITLE
deserialize pb stream to feature is too slow.

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#50308]
We run tensorflow on A100 machine, and our model currently consumes TFRecord very fast, we find deserialize varint64 is hot spot, so I want to replace from varint64 to fixed64.
I find :
    1. TF don't support fixed64 in feature.proto.
    2. I have a test that fixed64 is faster(10x) than varint64.
Is there any way we can implement fixed64 without modifying the TF code?

**Comment by zhaozheng09** [comment]
Some of our confidential data needs to be converted into hash64, and parse varint64 is unfriendly to hash64.

**Comment by zhaozheng09** [comment]
Now TF not support Fixed64, Do we have a plan to add a fixed64 type to deserialize hash64?

**Comment by zhaozheng09** [comment]
If you think this part is meaningful and you have no plans to implement this part, I can contribute this part of the code.

**Comment by jvishnuvardhan** [comment]
@zhaozheng09 Contributions are always welcome. Please feel free to raise a PR. Thanks!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
