### ISSUE TITLE
Build fails with GCC-11

### ISSUE THREAD

**Issue by samcom12** [tensorflow/tensorflow#50303]
Installation of Py-TensorFlow fails for below targets with GCC-11.

1. `third_party/abseil-cpp/absl/synchronization/internal/graphcycles.cc
`
2. `external/com_google_absl/absl/synchronization/internal/graphcycles.cc`

3. `external/ruy/ruy/block_map.cc`

**Fix-**
In respective header file, add `#include <limits>` and `#include <stdexcept>`

**Comment by tilakrayal** [comment]
@samcom12 ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

**Comment by samcom12** [comment]
**@tilakrayal**   Thanks for an early update.
Please see the below details for your reference.

OS Platform and Distribution : `linux-centos7-skylake_avx512`
TensorFlow installed from (source or binary):` installed from Source`
TensorFlow version: `2.4.1`
Python version: Tried with `Python-3.8.5` and `Python-3.9.0`
Installed using virtualenv? pip? conda?: Using `Spack`, Link- https://github.com/spack/spack.git
Bazel version (if compiling from source):`3.7.2`
GCC/Compiler version (if compiling from source): `GCC-11.1.0`
CUDA/cuDNN version: Compiling without GPU support
GPU model and memory: Not applicable

Variant 1: `spack install  --dont-restage py-tensorflow %gcc@11.1.0 ~cuda~nccl+mpi+numa ^openblas  ^openjdk ^python@3.9.0 ^mpich`
Variant 2: `spack install  --dont-restage py-tensorflow %gcc@11.1.0 ~cuda~nccl+mpi+numa ^openblas  ^openjdk ^python@3.8.5 ^mpich` 

As stated earlier, we need to explicitly include `<limits>` in builds of Bazel, grpc, ruy packages.

**Comment by samcom12** [comment]
We need to use-
1. latest abesil-cpp from https://github.com/abseil/abseil-cpp.git
2. latest Bazel if supported or patching older Bazel for GCC-11.
3. Integrate latest ruy- https://github.com/google/ruy.git

**Comment by mihaimaruseac** [comment]
Can you send a PR please? You can tag me (`@mihaimaruseac`) so I'll get notified to quickly review and approve

**Comment by riaqn** [comment]
This problem still exist.
