### ISSUE TITLE
question about the roadmap of xla send/recv ops supporting.

### ISSUE THREAD

**Issue by NEWPLAN** [tensorflow/tensorflow#50376]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): TensorFlow master branch with commit id: 3ef6fbfd02716f774024afae711383fdb0d8a30c
- Are you willing to contribute it (Yes/No): Yes
 

**Describe the feature and the current behavior/state.**
I'm starting my project on top of tensorflow with cross-machine communication support. Currently, we want to use the send/recv ops for multicast/p2p communication in HLO graph. However, we find that the latest tensorflow has not fully supported such ops in xla. I would like to query the roadmap for the support.
The send/recv hlo file for test is as follows:

HloModule TwoSendRecvBothWayRecvFist_module

ENTRY %TwoSendRecvBothWayRecvFist.v3 () -> (f32[], token[]) {
  %token0 = token[] after-all()
  %recv = (f32[], u32[], token[]) recv(token[] %token0), channel_id=15, sharding={maximal device=1}
  ROOT %recv-done = (f32[], token[]) recv-done((f32[], u32[], token[]) %recv), channel_id=15, sharding={maximal device=1}
  %constant = f32[] constant(2.1), sharding={maximal device=0}
  %send = (f32[], u32[], token[]) send(f32[] %constant, token[] %token0), channel_id=16, sharding={maximal device=0}, control-predecessors={%recv}
  %send-done = token[] send-done((f32[], u32[], token[]) %send), channel_id=16, sharding={maximal device=0}
}

The current tensorflow  would end up with an error when compiling the hlo graph as follows:
Attempting to fetch value instead of handling error Internal: LHLO opcode recv is not supported.

We notice that the "xla all_to_all" communication primitive was added last month (https://github.com/tensorflow/tensorflow/blob/636833c8ff5f716dfa2eddd60a9eae905d8f715a/tensorflow/compiler/xla/service/gpu/nccl_all_to_all_thunk.cc#L65). So are the support of xla send/recv ops in scheduling?

Thanks a lot.

**Will this change the current api? How?**
Not sure.
**Who will benefit with this feature?**
This feature would enable us to develop more flexible parallelisms for large model training. such as pipeline parallelism support in xla level.

**Any Other info.**
None

**Comment by tilakrayal** [comment]
@NEWPLAN ,

Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also can you please elaborate about your Feature and please specify the Use Cases for this feature. Thanks!

**Comment by NEWPLAN** [comment]
> @NEWPLAN ,
> 
> Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).Also can you please elaborate about your Feature and please specify the Use Cases for this feature. Thanks!

Hi, 

Thanks for your help. We have updated the issue with given template as above.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
