### ISSUE TITLE
support CSR (data, indices, indptr), [shape=(M, N)] format in tf.sparse 

### ISSUE THREAD

**Issue by hadifar** [tensorflow/tensorflow#50381]
**System information**
- TensorFlow version (you are using): 2.5
- Are you willing to contribute it (Yes/No): YES

**Describe the feature and the current behavior/state.**

The current `tf.sparse` constructor only support COO format `((data, (row_ind, col_ind)), [shape=(M, N)])`. However, the standard sparse representation is CSR `(((data, indices, indptr), [shape=(M, N)]))`. It would nice to see both options in `tf.sparse`. [Scipy](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.sparse.csr_matrix.html) and [pytorch](https://pytorch.org/docs/stable/generated/torch._sparse_csr_tensor.html) already support both these cases. 
I investigate a bit more and find out there are some functionalities that already implemented at [repo](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/sparse/) but apparently, they are no longer maintain or accessible:

e.g., ```tf.compat.v1.raw_ops.DenseToCSRSparseMatrix``` is not working:

```
import tensorflow.compat.v1 as tf

tf.disable_v2_behavior()

tmp = tf.constant([[1, 2, 3, 4, 5], [0, 0, 0, 2, 1]], dtype=tf.float32)
indices = tf.where(tf.not_equal(tmp, 0))
b = tf.raw_ops.DenseToCSRSparseMatrix(dense_input=ss, indices=indices)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(b)) 
```

**Will this change the current api? How?** No, it can be handle with if-else condition based on args 

**Who will benefit with this feature?** tf.sparse

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
