### ISSUE TITLE
A name conflict bug caused by LoweringFunctionalOps pass

### ISSUE THREAD

**Issue by Niz13** [tensorflow/tensorflow#50393]
**System information**
- TensorFlow version: 2.5.0
- Python version: 3.6

**Describe the current behavior**

When running testSkipEagerCaseLoweringPreservesNameForFetch test from tensorflow/tensorflow/blob/master/tensorflow/python/kernel_tests/functional_ops_test.py on a device that isn’t CPU/GPU the test fails due to a naming conflict in TF:
“Invalid argument: Node 'Case/branch_index/_3' is not unique”

During LoweringFunctionalOps pass, the Case node is replaced with a graph that contains a _SwitchN nodes with the name 'Case/branch_index/_3' with an input that is named 'Case/branch_index/’.
Later, during graph partitioning, a _Send node is added between the Const input and the _SwitchN node which happens to get the name 'Case/branch_index/_3' thus causing a conflict.

Here is a schematic of the situation:
![case2](https://user-images.githubusercontent.com/17768507/122736642-eb4cdb80-d288-11eb-8c0c-75cfb949df51.png)

- Do you want to contribute a PR? (yes/no): no

**Other info / logs** 
The _SwitchN name given during the lowering phase happens at:
tensorflow/core/common_runtime/lower_case_op.cc:122
The _Send name given during partitioning happens at:
tensorflow/core/graph/graph_partition.cc:241

**Comment by jsmeredith** [comment]
Hi!  Can you clarify the reproduction conditions a little more?  Specifically, you said that it fails that test in `functional_ops_test.py` "on a device that isn’t CPU/GPU" -- is there a specific setup that we can try?  Thanks!

**Comment by Niz13** [comment]
Hello,
Unfortunately, it isn't possible to provide you with a specific setup that would reproduce this, however, I can provide you with the pre-partitioning and post-partitioning graphs where it is possible to see the problem unfolding.
(These are .pbtxt files, for some reason couldn't upload .pbtxt files here)

[before.txt](https://github.com/tensorflow/tensorflow/files/6767985/before.txt)
[after.txt](https://github.com/tensorflow/tensorflow/files/6767984/after.txt)

In the after.txt graph, if you look for 'Case/branch_index/_3' you would see two nodes with that name.: a _SwitchN and a _Recv.

One thing you can try is maybe placing the _SwitchN on CPU, the reason this doesn't reproduce on GPU is due to the fact that both the _SwitchN and the Const before it are placed on GPU so a _Recv isn't added.

Hope this gives you a lead, let me know if you need any extra information!

**Comment by puneeshkhanna** [comment]
Same issue is also seen in another test "testCaseLowering" in the same file if you execute the test on another device other than CPU or GPU.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
