### ISSUE TITLE
Tensorboard delete option for runs

### ISSUE THREAD

**Issue by timmeinhardt** [tensorflow/tensorflow#5039]
Since many of us train with Tensorflow on a remote server and use Tensorboard to monitor and evaluate the training I think it would be useful to add a delete option for specific runs on the Tensorboard dashboard.
When I debug a training process I monitor what the network is doing and sometimes restart the process very quickly. Like this my data directory easily gets filled with a lot of fail runs. Deleting them from command is a little tedious cause you always have to check in Tensorboard which ones you might want to keep. And usually you have to close Tensorboard to be able to delete them at all.

Maybe you guys have a suggestion for an improved workflow! Otherwise I think being able to delete runs directly from Tensorboard would be a nice addition. As part of this an 'active' flag for  whether a run is still running might be interesting as well. Obviously this flag would disable the deletion option.

I am looking forward to your feedback!

Edit: If this is really a feature worth integrating I would be happy to look into it and submit a PR.

**Comment by asimshankar** [comment]
@danmane : Any thoughts on this?

**Comment by jart** [comment]
Thank you for your suggestion @timmeinhardt. We have a feature in TensorBoard that hasn't been released yet where the state of the runs checkboxes is persisted to the URL. I think that might actually solve your problem.

We're really excited that you're volunteering to be a contributor. Although right now we're in the process of revamping our build system. It's our top priority right now, but it's going to take a bit more time. Feature work is currently on hold and we're not able to accept contributions just yet. We'll let you know as soon as that changes. Because the new build is going to be simple and make it much easier to get involved in TensorBoard development.

**Comment by timmeinhardt** [comment]
Thank you for your fast response @jart ! From what I understood the non-released TensorBoard feature would address the 'active' flag for currently running runs but not the pollution of the data directory. Or am I missing something?

I am looking forward to your new build system and maybe contributing something in the future!

**Comment by jart** [comment]
Having TensorBoard do file management is a line we're probably not yet ready to cross. If the concern is disk space, there are probably better angles we could take for tackling the problem. @danmane and I have had conversations about changing the way we write events to disk. One thing I was actually wondering about the other day was if we could do reservoir sampling as we write to disk, rather than when we read from disk. Things like that could really help. But at the end of the day, `tensorboard` is still a command line program, so it's assumed that the user will feel comfortable with the fact that little command-line-fu is required to use this fabulous GUI.

**Comment by wielandbrendel** [comment]
I'd be very much interested in this feature as well! My use case is similar: I am often iterating over a prototype network for ten or twenty iterations, tweaking hyperparameters and fixing bugs according to the learning curves. Of course I can - and will - delete the superfluous runs via command line from time to time, but it would be a very elegant feature if this could be done directly in the GUI.

**Comment by jart** [comment]
We've got a few things planned over the course of this year that dovetail with this feature request, so we'll be sure to take the feedback we've received here into consideration.

**Comment by wchargin** [comment]
I'm going to close this for now; feel free to open an issue in our new repository at https://github.com/tensorflow/tensorboard/issues if you feel that there's more to discuss. Thanks!
