### ISSUE TITLE
TFLite converts splits of int64 tensors, but fails to evaluate the conversion

### ISSUE THREAD

**Issue by dlyubimov** [tensorflow/tensorflow#50445]
**System information**
- OS Platform and Distribution MacOS 
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from  binary:
- TensorFlow version 2.5.0:
- Python version: 3.8

**Standalone code to reproduce the issue**

```
def test_split_export():
    @tf.function
    def test_fn(inp: tf.Tensor) -> tf.Tensor:
        return tf.concat(tf.split(inp, 3, axis=1), axis=1)

    concrete_f = test_fn.get_concrete_function(tf.TensorSpec((None, 3), tf.int64))
    converter = tf.lite.TFLiteConverter.from_concrete_functions([concrete_f])
    tflite_model = converter.convert()
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()

```
**Describe the current behavior**

The example converts fine, but attempt to instantiate evaluation breaks in allocate_tensors with the error:

E     RuntimeError: tensorflow/lite/kernels/split.cc:90 input_type == kTfLiteFloat32 || input_type == kTfLiteUInt8 || input_type == kTfLiteInt8 || input_type == kTfLiteInt16 || input_type == kTfLiteInt32 was not true.Node number 0 (SPLIT) failed to prepare.

**Describe the expected behavior**
TFLite1 did not produce this error. Ideally behavior should be identical to TFLite1 (I think it downconverted all int64s to int32. If TFLite does not do downconversion, then the split should be able to support int64 tensors.(

Thank you.

**Comment by abattery** [comment]
Thanks. I can reproduce this issue at my side.

**Comment by abattery** [comment]
Please consider using the Select TF ops for enabling int64 type inputs in the TF Split op.

**Comment by rodenkew** [comment]
We considered using SELECT_TF_OPS, but the increase in the size of the resulting binary makes this option very unattractive.

The fact that the converter produces an artifact that the interpreter cannot run definitely seems like an issue with one or both products. The fact that the TfLite 1.15 converter/interpreter pair did not have this problem seems like a regression.

Given that the concatenation kernel and the split_v kernel support kTfLiteInt64, it is surprising that the split kernel does not. After comparing the the split and split_v kernels, I think that the behavior described in this ticket seems almost trivial to address.

In fact, I made the obvious (but maybe incorrect) update to split.cc, built from source, and the issue was resolved.

**Comment by abattery** [comment]
Please consider uploading a separate issue for filing a feature request for int64 support in TFLite split kernels with your usage's context information.

For the binary size issue, you can reduce the selective build for Select TF enabled TFLite AAR. https://www.tensorflow.org/lite/guide/reduce_binary_size

**Comment by RuofanKong** [comment]
@abattery This looks a regression rather than a feature request, given int64 with TFLite split was supported on TFlite 1.x., and continuing to support it is more reasonable to me.

**Comment by abattery** [comment]
I dont think so. TOCO converter in the TF version one does not have enough type support checks..
