### ISSUE TITLE
tf.profiler.experimental.Trace only works with name is "TraceContext"

### ISSUE THREAD

**Issue by PeterMitrano** [tensorflow/tensorflow#50440]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.3.1
- Python version: 3.8
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 10.1
- GPU model and memory: 1080ti

**Describe the current behavior**
The name argument to `Trace` has to be exactly `"TraceContext"` otherwise the "overview" page doesn't give any info. Interesting the other pages still work and have all the right data. But the title page is broken, so most users wouldn't think to look at the other pages and just assume the whole thing was broken.

**Describe the expected behavior**
It works with any name

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
```
from datetime import datetime
import tensorflow as tf

b = tf.random.uniform([32,28,28,1])

model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28, 28, 1)),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(10, activation='softmax')
])

def test(trace_name):
    logs = f"logs/{trace_name}" + datetime.now().strftime("%Y%m%d-%H%M%S")

    epoch = 0
    tf.profiler.experimental.start(logs)
    for step in range(100):
        if 1 < step < 100:
            with tf.profiler.experimental.Trace(trace_name):
                model(b)
        else:
            model(b)
    tf.profiler.experimental.stop()

test("TraceContext") # works fine
test("Broken") # no step marker observed error
```

**Other info / logs**
![trace_context](https://user-images.githubusercontent.com/4010770/123279273-b4b7d080-d4d5-11eb-9e75-e91cff2982cc.png)
![broken](https://user-images.githubusercontent.com/4010770/123279286-b6819400-d4d5-11eb-8515-8b5998658a00.png)

**Comment by UsharaniPagadala** [comment]
@PeterMitrano 

In order to expedite the trouble-shooting process,Could you please share the colab gist with all the dependencies .Thanks

**Comment by PeterMitrano** [comment]
I have reproduce the issue in colab:

https://colab.research.google.com/drive/18bLYBL6hAX8tNgxJ21qGAu81Hvt2h8Sy?usp=sharing

**Comment by PeterMitrano** [comment]
what permissions does the notebook need? I just set it to "anyone with link can view"

**Comment by UsharaniPagadala** [comment]
@Saduf2019 

I was able to replicate the issue reported here.Please find the [gist](https://colab.research.google.com/drive/1O_9FDa584VYd-CcRjrKl86uc397VzglL?resourcekey=0-H6gHS07dZuDaa8wODjRASw).Thanks

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
