### ISSUE TITLE
Load in-cluster config in tf.distribute.cluster_resolver.KubernetesClusterResolver

### ISSUE THREAD

**Issue by yanp** [tensorflow/tensorflow#50449]
**System information**
- TensorFlow version (use command below): `2.5.0`

**Describe the current behavior**

  Currently the `KubernetesClusterResolver` class can only load configs from kube-config file:

https://github.com/tensorflow/tensorflow/blob/v2.5.0/tensorflow/python/distribute/cluster_resolver/kubernetes_cluster_resolver.py#L97

**Describe the expected behavior**

  When running in worker pods in cluster, we want to be able to load configs using `.load_incluster_config()` ([example](https://github.com/kubernetes-client/python/blob/v17.17.0/examples/in_cluster_config.py#L55))

We can't use the `override_client` arg with `kubernetes` package either, because once installed the `ImportError` does not happen 

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no):

  Yes

- Briefly describe your candidate solution(if contributing):

  Try to do `k8sconfig.load_incluster_config()` first, if failed then do `k8sconfig.load_kube_config()`

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
