### ISSUE TITLE
Multi-core not being utilized?

### ISSUE THREAD

**Issue by kaihuchen** [tensorflow/tensorflow#5046]
I have a 8 vCPUs 30GB Debian instance on the Google Cloud Platform, running the TensorFlow implementation of the WaveNet from https://github.com/ibab/tensorflow-wavenet  

I noticed that CPU usage stays around 13%, as if only one of the 8 vCPUs is being used. I have found this issue https://github.com/tensorflow/tensorflow/issues/583 which seems to indicate that such problem should have been fixed. 

Any advice on what I need to do in order for all of the vCPUs on my instance to be full utilized in such a case? Thanks!

**Comment by yaroslavvb** [comment]
Is this a TensorFlow problem or a Google Cloud problem? You can tell by
trying to run this model locally and seeing the CPU usage

**Comment by aselle** [comment]
You can try the timelines profiler e.g.
http://stackoverflow.com/questions/34293714/tensorflow-can-i-measure-the-execution-time-of-individual-operations/37774470#37774470

Closing for now since it is not clear that it is a bug. You might try asking on StackOverflow since this question is more "how to get good performance on TensorFlow" rather than "TensorFlow is broken." Please reopen if you find that a bug is causing performance to be worse than it should be.
