### ISSUE TITLE
ConvLSTM2D layer wrong computation

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#50599]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Describe the current behavior**

There seems to be something wrong with the computation of the ConvLSTM2D layer. I tried to do the computation manually for a simplified example and I come to a different result. I think there might be a bug in the last round of the layer.  The issue is illustrated in the example below. 

**Describe the expected behavior**
The output that I expected from the simple example model is `[[[[[   0.], [   8.]]], [[[ 0.],[1053.]]]]]`, but instead the actual output is `[[[[[   0.], [   8.]]], [[[ 512.],[1053.]]]]]`.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
tf.keras.backend.set_floatx('float64')
model = keras.Sequential([
keras.layers.ConvLSTM2D(1, (1, 2), return_sequences=True, padding='valid', strides=(1,1),recurrent_activation='linear', activation='linear',  input_shape=(2, 1, 3, 1))])
w = model.get_weights()
w[0] = np.array([[[[1, 1, 1, 1]],[[1, 1, 1, 1]]]])
w[1] = np.array([[[[1, 1, 1, 1]],[[1, 1, 1, 1]]]])
w[2] = np.array([0, 0, 0, 0])
model.set_weights(w)
x = tf.constant([[[[[0], [0], [2]]], [[[0], [0], [1]]]]])
print (np.array2string(model.predict(x,steps=1), separator=', '))
```

**Comment by saikumarchalla** [comment]
@rschumi0 It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. As ([previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999/)), all future development of Keras is expected to happen in the [github.com/keras-team/keras](github.com/keras-team/keras) repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!

**Comment by rschumi0** [comment]
@saikumarchalla it's now in the keras repo: https://github.com/keras-team/keras/issues/15224
