### ISSUE TITLE
How to use the TF_VARIANT with C APIs?

### ISSUE THREAD

**Issue by yanzhang-dev** [tensorflow/tensorflow#50607]
Hi,

Currently, we can create or get a `TF_Tensor` with `TF_FLOAT` data type, and then manipulate the raw data buffer by the pointer from `TF_TensorData`. For example,

```
TF_Tensor* output = TF_AllocateOutput(xxx, TF_FLOAT, xxx);
float* output_raw_buffer = reinterpret_cast<float*>(TF_TensorData(output));
// do some calculation on output_raw_buffer
```

But for the data type TF_VARIANT, we can't manipulate it directly like float type. Do we have any examples about how to use it ?

Thanks

**Comment by UsharaniPagadala** [comment]
@yanzhang-dev 

Could you please refer this [`c_api`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api_test.cc#L166),hope it helps.Thanks

**Comment by yanzhang-dev** [comment]
Hi @UsharaniPagadala 

The test case you provided is parsing the meta data like shape, dtype of Tensor.
Yes, we can create a TF_VARIANT Tensor and get these meta data, too.

But if we want to get the elements of Tensor, for example,

1. If the tensor's elements are `TF_FLOAT`, we can parse the raw buffer like [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api_test.cc#L1671)
2. But if the tensor's elements are `TF_Variant`, we can't parse the raw buffer by `TF_TensorData` like above. How should we do ?

Thanks

**Comment by Jianhui-Li** [comment]
@penpornk

**Comment by penpornk** [comment]
Hi @yanzhang-dev,

Sorry for the delay! 

[TF_VARIANT](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/c/tf_datatype.h;l=69;drc=9849fde5e7b4da4b630ffbc517fad68b2b811c0c) / [DT_VARIANT](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/framework/types.proto;l=40;drc=7c3f96bf324cebe443a7eb814ce771c66c073998) is a data type that is used to encapsulate C++ data structures. You can generally treat a DT_VARIANT tensor as a wrapper of a blob of bytes, whose value will be interpreted based on the kernel it is in. 

For example, 
* [CSRSparseMatrixToDense](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/ops/sparse_csr_matrix_ops.cc;l=151;drc=57395f70dbc24d3ac5f97626520194f6773303e8) takes [a variant input](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/ops/sparse_csr_matrix_ops.cc;l=152;drc=57395f70dbc24d3ac5f97626520194f6773303e8) and [interprets the binary data blob](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/kernels/sparse/csr_sparse_matrix_to_dense_op.cc;l=129-130;drc=8d72537c6abf5a44103b57b9c2e22c14f5f49698) as a [CSRSparseMatrix C++ object](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/kernels/sparse/sparse_matrix.h;l=35;drc=3381da37560d64c7cb62b53879a0a931ff9036c4).
* TensorList ops [interprets the data blob](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/kernels/list_kernels.cc;l=81;drc=8d72537c6abf5a44103b57b9c2e22c14f5f49698) in its variant tensor as a [TensorList C++ object](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/kernels/tensor_list.h;l=65;drc=3381da37560d64c7cb62b53879a0a931ff9036c4).

Since [Variant::get()](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/core/framework/variant.h;l=246;drc=a697dbc60433fc8378680716cef9ab363bf70568) is a templated function, we can't just expose it as-is for the C API. But I think we can make a C API that returns a type-erased pointer to the binary blob, e.g., add `TensorInterface::VariantData` under [TensorInterface::Data](https://cs.opensource.google/tensorflow/tensorflow/+/master:tensorflow/c/tf_tensor.cc;l=219;drc=dfd157595356cbf49303af75277df5b717caed7b). 

```c++
void* TensorInterface::VariantData() const {
  return tensor_.scalar<Variant>()().get<void>();
}
```

Then your kernel will take this void pointer and cast the blob to a C++ object. This requires plug-ins to have the exact same headers as core TensorFlow. C++ classes also don't have versioning guarantees. So I'm not sure if trying to support `DT_VARIANT` will be worth it.

**Comment by whatdhack** [comment]
@penpornk , is there a list  of  python level ops that ends up using variant data types ?  For example tensorflow.keras.layers.LSTM  uses TensorList.  Not sure if the TensorList  comes from the parent class tf.keras.layers.RNN  or not.  If it is the former, then all RNNs are unfriendly to plugins.   One way I  can think of getting around this issue  is replacing  the op implementation with one that does not use variant type ?  Is there any such alternative for LSTM or RNN ?

**Comment by felker** [comment]
@whatdhack could you point me to where the `tensorflow.keras.layers.LSTM`  --> `TensorList` --> `DT_VARIANT` usage occurs in the source code?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
