### ISSUE TITLE
error reporting model(x) vs model.predict(x)

### ISSUE THREAD

**Issue by rschumi0** [tensorflow/tensorflow#50618]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): v2.4.0-rc4-71-g582c8d236cb 2.4.0
- Python version: 3.8.5

**Describe the current behavior**

The error and warning messages seem to be different when `model(x)` is used instead of `model.predict(x)`  to make a prediction.
Is this intentional and documented somewhere? 
For example, in the following simple model there is a warning when `model.predict(x)` is used, but none for `model(x)`. 
Moreover, it would be generally good to know which warnings (or errors) might not occur when a specific prediction method is used and also which warnings will be the same.

**Standalone code to reproduce the issue**
```
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
import numpy as np
model = keras.Sequential([
keras.layers.ReLU(threshold=3,  input_shape=(2,))])
x = tf.constant([[[[1,2,3,4,5]]]])
print (np.array2string(model(x).numpy(), separator=', '))
#print (np.array2string(model.predict(x), separator=', '))
```

**Comment by i-seesharp** [comment]
Hi @saikumarchalla I'd like to contribute towards fixing this bug. Could you maybe point me in the right direction?

**Comment by saikumarchalla** [comment]
@i-seesharp  It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. As ([previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999/)), all future development of Keras is expected to happen in the [github.com/keras-team/keras](github.com/keras-team/keras) repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!

**Comment by jvishnuvardhan** [comment]
This Issue was moved to keras repo. So, closing the issue here. Thanks
