### ISSUE TITLE
tf.repeat for RaggedTensor

### ISSUE THREAD

**Issue by Azmisov** [tensorflow/tensorflow#50619]
Wondering if we can get `tf.repeat` for the `tf.ragged` module?

The `tf.stack` and `tf.tile` ops are implemented, so doesn't seem like there would be a technical limitation for `tf.repeat`. My particular case is doing the repeat on one of the non-ragged dims. But seems you could do a repeat on a ragged tensor, so long as the `repeats` arg is scalar or matches the maximum row length. I did see a related issue discussing the possibility of an nd_repeat operation, which would perhaps prove more useful for repeats on ragged dims.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
