### ISSUE TITLE
tf.shape can't infer sparse tensor shape in graph mode

### ISSUE THREAD

**Issue by breadbread1984** [tensorflow/tensorflow#50622]
<em>Please make sure that this is a bug. As per our
[GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md),
we only address code/doc bugs, performance issues, feature requests and
build/installation issues on GitHub. tag:bug_template</em>

**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.5.0
- Python version: 3.8.10
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source): N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

You can collect some of this information using our environment capture
[script](https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh)
You can also obtain the TensorFlow version with:
1. TF 1.0: `python -c "import tensorflow as tf; print(tf.GIT_VERSION, tf.VERSION)"`
2. TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`

v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0

**Describe the current behavior**

tf.shape can't infer shape of a sparse tensor in graph mode.

**Describe the expected behavior**

tf.shape should infer shape of a sparse tensor in graph mode.

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no
- Briefly describe your candidate solution(if contributing):

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

```python
#!/usr/bin/python3
import tensorflow as tf;

inputs = tf.keras.Input((2,3,4));
print(tf.shape(inputs)); # tf.shape can infer dense tensor

inputs = tf.keras.Input((2,3,4), sparse = True);
print(tf.shape(inputs)); # tf.shape cannot infer sparse tensor
```

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

**Comment by saikumarchalla** [comment]
Was able to reproduce the issue in TF 2.5. Please find the gist [here](https://colab.research.google.com/gist/saikumarchalla/c3d7a40bd1c3d5ebefd86ed560a1c8c9/untitled107.ipynb),Thanks!

**Comment by rmothukuru** [comment]
@breadbread1984,
Documentation of [tf.shape](https://www.tensorflow.org/api_docs/python/tf/shape#for_example) states 

> **`tf.shape`** and **`Tensor.shape`** should be identical in eager mode.

Using **`inputs.shape`** instead of **`tf.shape(inputs))`** resolves your problem. Please find [the Gist](https://colab.research.google.com/gist/rmothukuru/72adf7e88659f4178f69dcf42985a9c1/untitled107.ipynb) of the working code. Thanks!

**Comment by breadbread1984** [comment]
in graph mode the batch size is inferable, but it is not when using tensor.shape. that why i am using th.shape to infer shape of tensor when building graph model with functional model definition.

**Comment by cantonios** [comment]
My guess is this is a keras issue.  SparseTensor works just fine:
```
x = tf.sparse.SparseTensor(
    [[0, 0, 1]], [2], (2, 3, 4)
)
print(x)
print(tf.shape(x))
```

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
