### ISSUE TITLE
[Adaptation] Indices of SparseTensor should adapt with current indices if (explicitly/implicitly) specified

### ISSUE THREAD

**Issue by IchiruTake** [tensorflow/tensorflow#50643]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No):

I am using TensorFlow version 2.5.0 and try to adapt Sparse Tensor into Deep Learning model. However, interestingly that despite the indices has been specified by numpy, the indices always cast to uint64 despite our trial, even from numpy or tensorflow (tf.convert_to_tensor || tf.constant). As our matrix has its shape (10000, 7465), it is recommended to use uint16 as datatype indices rather than uint64. 

If indices was pass as Python List or Tuple, casting to uint64 is prefered, but if numpy array as input, it would be great to be modified with respective datatype with equivalent range rather than safely cast to uint64 as input

This implementation can help to reduce maximum of computing resources as storing indices may quite costly even if the matrix was not sparse enough. In my case, luckily, the data is uint8 with 2.24 % density so there are no problems about that. 

Example:
Current Version: Memory Cost: data (uint8), indices (uint64) -> Memory Cost: 38.08% compared to dense array
This implementation 1: data (uint8), indices (uint16) -> Memory Cost: 11.02% compared to dense array
This implementation 2: data (uint8), indices (uint32) -> Memory Cost: 20.16% compared to dense array

Moreover, it should be possible to make keras.Input(sparse=True) be compatible with Scipy.sparse rather than making warnings

**Comment by IchiruTake** [comment]
> **System information**
> 
> * TensorFlow version (you are using): 2.5.0
> * Are you willing to contribute it (Yes/No):
> 
> I am using TensorFlow version 2.5.0 and try to adapt Sparse Tensor into Deep Learning model. However, interestingly that despite the indices has been specified by numpy, the indices always cast to uint64 despite our trial, even from numpy or tensorflow (tf.convert_to_tensor || tf.constant). As our matrix has its shape (10000, 7465), it is recommended to use uint16 as datatype indices rather than uint64.
> 
> If indices was pass as Python List or Tuple, casting to uint64 is prefered, but if numpy array as input, it would be great to be modified with respective datatype with equivalent range rather than safely cast to uint64 as input
> 
> This implementation can help to reduce maximum of computing resources as storing indices may quite costly even if the matrix was not sparse enough. In my case, luckily, the data is uint8 with 2.24 % density so there are no problems about that.
> 
> Example:
> Current Version: Memory Cost: data (uint8), indices (uint64) -> Memory Cost: 38.08% compared to dense array
> This implementation 1: data (uint8), indices (uint16) -> Memory Cost: 11.02% compared to dense array
> This implementation 2: data (uint8), indices (uint32) -> Memory Cost: 20.16% compared to dense array

**Comment by cantonios** [comment]
Similar to #49993.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
