### ISSUE TITLE
transpose op code behavior mismatch with comments in xla

### ISSUE THREAD

**Issue by mingting** [tensorflow/tensorflow#50662]
tensorflow 1.15.5
https://github.com/tensorflow/tensorflow/blob/v1.15.5/tensorflow/compiler/xla/service/shape_inference.cc#L2740

```c++
  // Permute(dimensions,input) computes output[dimensions[i]]=input[i]. However,
  // we need output[i]=input[dimensions[i]] which is
  // Permute(Inverse(dimensions),input).
  return ShapeUtil::PermuteDimensions(InversePermutation(dimensions), operand);
```

https://github.com/tensorflow/tensorflow/blob/v1.15.5/tensorflow/compiler/xla/util.h#L340

```c++
// Applies `permutation` on `input` and returns the permuted array.
// For each i, output[permutation[i]] = input[i].
//
// Precondition:
// 1. `permutation` is a permutation of 0..permutation.size()-1.
// 2. permutation.size() == input.size().
template <typename Container>
std::vector<typename Container::value_type> Permute(
    absl::Span<const int64> permutation, const Container& input) {
  using T = typename Container::value_type;
  absl::Span<const T> data(input);
  CHECK(IsPermutation(permutation, data.size()));
  std::vector<T> output(data.size());
  for (size_t i = 0; i < permutation.size(); ++i) {
    output[permutation[i]] = data[i];
  }
  return output;
}
```

my question is 
accoding to the comments, **if using inverse permutation, we should use output[i]=input[dimensions[i]].**
**but, code still use  output[dimensions[i]]=input[i].**

seems like a bug or mismatch?
I checked latest code, this is still there, but inverse moved to other place.
so I used 1.15.5, as the inverse code is together with permute.

BR.
Mingting

**Comment by mingting** [comment]
@hawkinsp can you help to check this?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
