### ISSUE TITLE
Failed to convert mhlo dialect to Linalg dialect when the layout of Conv2d is NCHW

### ISSUE THREAD

**Issue by wwwwcu** [tensorflow/tensorflow#50687]
I want to convert the conv2d operator from mhlo to linalg dialect. It seems like that it can't process the situation when the  layout of conv2d is NCHW.
The mhlo dialect of conv2d.mlir is shown below:
```
module  {
  func @main(%arg0: tensor<64x3x7x7xf32>, %arg1: tensor<1x3x224x224xf32>) -> tuple<tensor<1x64x112x112xf32>> {
    %0 = "mhlo.convolution"(%arg1, %arg0) {batch_group_count = 1 : i64, dimension_numbers = {input_batch_dimension = 0 : i64, input_feature_dimension = 1 : i64, input_spatial_dimensions = dense<[2, 3]> : tensor<2xi64>, kernel_input_feature_dimension = 1 : i64, kernel_output_feature_dimension = 0 : i64, kernel_spatial_dimensions = dense<[2, 3]> : tensor<2xi64>, output_batch_dimension = 0 : i64, output_feature_dimension = 1 : i64, output_spatial_dimensions = dense<[2, 3]> : tensor<2xi64>}, feature_group_count = 1 : i64, lhs_dilation = dense<1> : tensor<2xi64>, padding = dense<3> : tensor<2x2xi64>, precision_config = ["DEFAULT", "DEFAULT"], rhs_dilation = dense<1> : tensor<2xi64>, window_strides = dense<2> : tensor<2xi64>} : (tensor<1x3x224x224xf32>, tensor<64x3x7x7xf32>) -> tensor<1x64x112x112xf32>
    %1 = "mhlo.tuple"(%0) : (tensor<1x64x112x112xf32>) -> tuple<tensor<1x64x112x112xf32>>
    return %1 : tuple<tensor<1x64x112x112xf32>>
  }
}
```
I use "./mlir-hlo-opt ./conv2d.mlir -hlo-legalize-to-linalg -o conv2d_linalg.mlir" to do the transformation.
I traced the workflow and found out when it checks "HasCanonicalDimensionNumbers()", it returns false.
[legalize_to_linalg.cc:1771](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/hlo/lib/Dialect/mhlo/transforms/legalize_to_linalg.cc#L1771)
```
  if (dimension_numbers.input_batch_dimension().getInt() != 0 ||
      dimension_numbers.input_feature_dimension().getInt() !=
          (input_spatial_rank + 1)) {
    return false;
  }
```

**Comment by wwwwcu** [comment]
The input with input size (NCHW), filter (FCHW), I've checked [Linalg Dialect - MLIR](https://mlir.llvm.org/docs/Dialects/Linalg/#linalg), [linalg.conv_2d_input_nchw_filter_hwcf](https://mlir.llvm.org/docs/Dialects/Linalg/#linalgconv_2d_input_nchw_filter_hwcf-mlirlinalgconvinputnchwfilterhwcfop) supports NCHW input, but the filter should be HWCF, also it doesn't support padding according to the description of Interface; and I saw these Interface: [linalg.conv_2d_nchw](https://mlir.llvm.org/docs/Dialects/Linalg/#linalgconv_2d_nchw-mlirlinalgconvnchwop) and [linalg.conv](https://mlir.llvm.org/docs/Dialects/Linalg/#linalgconv-mlirlinalgconvop). I'm not sure which one is better for supporting Conv2D with input (NCHW) and filter (FCHW).
Maybe we need to add some transpose OPs for supporting it. I'm not familiar with Linalg. This is just my thought, not sure if it is correct

**Comment by joker-eph** [comment]
@hanhanW : wanna chime in here?

**Comment by wwwwcu** [comment]
> @hanhanW : wanna chime in here?
Ok, if it is convenient for you.

**Comment by hanhanW** [comment]
Sure, I'm happy to! We've been experimenting conv op in IREE repo. In that time, we only see this form of convolution. So only it is supported when we upstream the pattern.
Please do not use linalg.conv op because

- It only works on memrefs.
- Padding attribute would stop many opportunities of Linalg transforms. E.g., we are not able to fuse operations if it has padding attributes.
- It should be deprecated at some point.
- ETC

There are couple options to support conv_2d_input_nchw_filter_hwcf op.

1) You can create a pass to legalize the conv op to such form, like inserting some transpose op before/after the conv op, and recreate the conv op. (Because the dim numbers would be different.)

2) Add a linalg.conv_2d_input_nchw_filter_hwcf to Linalg dialect, and add a pattern to lower the conv op to Linalg ops.
 - We added the operation to TC files while yaml gen was in progress. Now you can follow the [doc](https://mlir.llvm.org/docs/Dialects/Linalg/OpDSL/) to add the operation to yaml file.
 

For padding attribute, IREE has a pass to extract the padding attributes to a mhlo.pad op. You can either add a similar pass to your pipeline, or create a linalg.pad_tensor op when there are padding attributes. The latter approach make more sense to me.

**Comment by wwwwcu** [comment]
Thank you very much for your detailed suggestions! I'll try it.

**Comment by tilakrayal** [comment]
@wwwwcu,
Could you please take a look at this [comment](https://github.com/tensorflow/tensorflow/issues/50687#issuecomment-879277321) from the developer and let us know if you are facing the same issue in latest stable v2.9. Thank you!
