### ISSUE TITLE
Print a warning or error when an empty TFRecord file is used.

### ISSUE THREAD

**Issue by jt0dd** [tensorflow/tensorflow#50726]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

This is a feature request in the sense that it's asking for a new functionality to make a scenario not fail silently. Not a substantial feature for TF, just a quality of life change.

**Describe the feature and the current behavior/state.**

Many people use TFRecord generation scripts that fail silently if they can't find images and generate empty TFRecords. When Tensorflow encounters empty TFRecords, it fails silently, leaving users confused:

https://github.com/tensorflow/models/issues/9581

**Will this change the current api? How?**

No

**Who will benefit with this feature?**

All new users

**Any Other info.**

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
