### ISSUE TITLE
tf.keras.layers.TimeDistributed build method passes shapes as tuples instead of TensorShapes.

### ISSUE THREAD

**Issue by iiwii** [tensorflow/tensorflow#50752]
https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/layers/wrappers.py#L186

This causes inconsistencies in wrapped layer.

**Comment by saikumarchalla** [comment]
@iiwi It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. As ([previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999/)), all future development of Keras is expected to happen in the [github.com/keras-team/keras](github.com/keras-team/keras) repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!

**Comment by saikumarchalla** [comment]
Closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
