### ISSUE TITLE
Documented and more fine grained XLA auto-clustering flags in ConfigProto

### ISSUE THREAD

**Issue by rnett** [tensorflow/tensorflow#50797]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it: Probably not

**Describe the feature and the current behavior/state.**
Currently, to enable XLA auto-clustering, you have to either use global configuration flags (`TF_XLA_FLAGS`) or `config.proto` options.  However, several options from the global flags are missing from `config.proto`, most importantly to do it on CPU (`--tf_xla_cpu_global_jit`), but also including debug settings.

I would like the option to set all relevant XLA options (but especially to enable it on CPU) in `config.proto` in addition to the global settings.  It avoids forcing global (JVM-wide in this case) configuration and allows setting it from code.

**Will this change the current api? How?**
It will add properties to `config.proto`.

**Who will benefit with this feature?**
Anyone wanting to use XLA auto-clustering programmatically.  The motivating use case was for Graphs in tensorflow/java.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
