### ISSUE TITLE
Dark mode not working for `metric_names` attributes of `tf.keras.Model`

### ISSUE THREAD

**Issue by 01-vyom** [tensorflow/tensorflow#50823]
## URL(s) with the issue:

https://www.tensorflow.org/api_docs/python/tf/keras/Model#attributes_1

## Description of issue (what needs changing):

The `metrics_names` attribute section of `tf.keras.Model` doesn't work properly while turning on dark mode.

<img width="629" alt="Screenshot 2021-07-18 at 7 32 01 PM" src="https://user-images.githubusercontent.com/46242526/126070193-287588da-0504-4807-a63a-727b15426fb7.png">

### Correct links

Doc for `Model` : https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/engine/training.py#L135-L207

Doc for attribute `metric_names` : https://github.com/tensorflow/tensorflow/blob/a4dfb8d1a71385bd6d122e4f27f86dcebb96712d/tensorflow/python/keras/engine/training.py#L684-L717

### Parameters defined

The `layers` attribute of the `tf.keras.Model` is not defined
<img width="858" alt="Screenshot 2021-07-18 at 8 27 48 PM" src="https://user-images.githubusercontent.com/46242526/126071975-ac217cea-2e23-439b-ac78-35c588c275da.png">

### Submit a pull request?

Yes

**Comment by UsharaniPagadala** [comment]
@01-vyom 

It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](https://github.com/keras-team/keras/issues) repository instead. As previously [announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999) all future development of Keras is expected to happen in the keras-team/keras repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!

**Comment by 01-vyom** [comment]
@UsharaniPagadala 

Thank you for the info. In Keras, the code-copy and code-theme functionality has not been implemented yet so will hold out on the issue. Will raise an issue in Keras later. 

This issue can be closed.
