### ISSUE TITLE
implement reduce for the bitwise operations. 

### ISSUE THREAD

**Issue by yaoshiang-masterfulai** [tensorflow/tensorflow#50939]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.4, 2.5. 
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently, there is no tf.reduce_xor (or any reduction or any other bitwise op). There is the tf.bitwise package for bitwise ops, but they only operate on two inputs. 

**Will this change the current api? How?**

No, this would be an additional api. 

**Who will benefit with this feature?**

As more preprocessing operations are pushed into the graph-mode model rather than in tf.data.Dataset.map layers, we need to do more preprocessing work in the graph (though preprocessing does not need to be differentiable). For example, I am attempting to implement a message digest algorithm that is invariant to the ordering of the images in a batch. The basic algo would be to implement a message digest for each image in a mini batch, then xor them together with a tf.bitwise.reduce_xor() function. Without reduce, I'd have to rely on tf.scan and tf.bitwise.bitwise_xor. 

**Any Other info.**

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
