### ISSUE TITLE
tf.spars.sparsee_dense_matmul supports multiplication of batches of data in a sparse tensor with a dense tensor

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51074]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using):  tf 2.5
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?** No.

**Who will benefit with this feature?** The user who needs the sparse matrix multiplication of batches of data

As said in the manual script, `tf.spars.sparsee_dense_matmul`  only support `Multiply SparseTensor (or dense Matrix) (of rank 2)
`. Currently I have batches of data stored in a sparse tensor, then how should I do the multiplication? Any suggestions?

**Comment by Saduf2019** [comment]
@sjtusmartboy 
You could create a tf.data,Dataset and then map that function.

**Comment by sjtusmartboy** [comment]
It indeed can do that by splitting the data along the batch axis, but I think there's no necessity to limit the rank of sparseTensor to be 2. From the perspective of user's eye, the function should be as easy to use as possible. What's more, there's no need to change the current api, just make full implementation of the function is enough.

**Comment by sjtusmartboy** [comment]
It indeed can do that by splitting the data along the batch axis, but I think there's no necessity to limit the rank of sparseTensor to be 2. From the perspective of user's eye, the function should be as easy to use as possible. What's more, there's no need to change the current api, just make full implementation of the function is enough.

**Comment by Saduf2019** [comment]
@sjtusmartboy 
this is not a valid request, you may open this issue at tensorflow discussion forum as there si a larger community to answer it there and move this to closed status here.

**Comment by sjtusmartboy** [comment]
＠Saduf2019 Any reason why tensorflow set this rank limit?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
