### ISSUE TITLE
Sparse matmul and element-wise multiply

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51092]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): tf2.5
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

**Will this change the current api? How?** No

**Who will benefit with this feature?** Users who need sparse calculation, but with limited memory resources and so big the dimension of data.

**Any Other info.**

1. If `a` is a sparse column vector`(n*1)`, then how to get the result of `a matmul a.T`, which is also the sparse matrix with dense_shape `(n*n)` but unable to be stored in the memory? 
2. If A and B are both the sparse matrix with dense_shape of `(n*n)`,  then how to calculate the result of `A multiply B`(element-wise), and how to calculate `A matmul B`, the result of which are both sparse matrix with dense shape` (n*n)`?

**Comment by jvishnuvardhan** [comment]
@sjtusmartboy Is this duplicate of https://github.com/tensorflow/tensorflow/issues/51074? If yes, can you please close https://github.com/tensorflow/tensorflow/issues/51074 and follow the progress in this issue.

As you mentioned that you are interested in contributing, you could raise a PR and connect it to this issue. Thanks!

**Comment by sjtusmartboy** [comment]
I would like to contribute, but currently I do not have any idea how to realize this function. And where to raise the PR

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
