### ISSUE TITLE
No information in official doc regarding implementation of class_weight in customized model.fit() method

### ISSUE THREAD

**Issue by n33lkanth** [tensorflow/tensorflow#51127]
Hi,
I have customized the standard model.fit() method based on the help/steps described in the official [page](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit). Now, I would like to use the class_weight in this customized function but I do not see any help regarding class_weight implementation in official [page](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit#supporting_sample_weight_class_weight) under the heading [Supporting sample_weight & class_weight](https://www.tensorflow.org/guide/keras/customizing_what_happens_in_fit#supporting_sample_weight_class_weight). Kindly help me to understand how to implement class_weight in this case?

Best Regards

**Comment by n33lkanth** [comment]
Hi,
Any update on this issue?


Best Regards

**Comment by saikumarchalla** [comment]
@n33lkanth It looks like your Issue relates to the Keras component. Please submit it to the [github.com/keras-team/keras](github.com/keras-team/keras) repository instead. As ([previously announced](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999/)), all future development of Keras is expected to happen in the [github.com/keras-team/keras](github.com/keras-team/keras) repository. If your issue lies with the TF-Core area please comment back with your explanation and we can look into it further. Thanks!

**Comment by n33lkanth** [comment]
Hi @saikumarchalla ,
Thank you for your feedback. I raised this issue here as it is related to the TensorFlow official documentation. Do you mean that the doc I mentioned in previous post is not Tensorflow official doc?

**Comment by rthadur** [comment]
Yes this has been moved to Keras repo , please check the related github page here https://github.com/keras-team/keras-io/blob/master/guides/customizing_what_happens_in_fit.py , any updated information will be submitted in keras repo. Thank you

**Comment by n33lkanth** [comment]
Dear @rthadur,
Thank you for the response. However, the question still remains the same. The [link](https://github.com/keras-team/keras-io/blob/master/guides/customizing_what_happens_in_fit.py) shared by you discusses the usage of _sample_weight_ only. There is no information about the usage of _class_weight_ in the customized model.fit() method.


Best Regards
