### ISSUE TITLE
&TfLiteTensor->Data not 16-Byte Aligned

### ISSUE THREAD

**Issue by MisterBerg** [tensorflow/tensorflow#51178]
### 1. System information

- OS Platform and Di_pywrap_toco_apistribution (e.g., Linux Ubuntu 16.04): LINUX UBUNTU 20.04
- TensorFlow installation (pip package or built from source):  PIP PACKAGE
- TensorFlow library (version, if pip package or github SHA, if built from source): PIP PACKAGE

### 2. Code
I think the code will not help, as the conversion process is working but I have questions about the resulting model file.
I have attached a zip:
[model.zip](https://github.com/tensorflow/tensorflow/files/6934441/model.zip)

### 3. Failure after conversion
I am working on a proof of concept, and I am making changes to the TFLite codebase. 
Although the model file is 16-byte aligned, some of the tensor data is not. 
For example:
my input->data.f has an address of 0x..........0 (16 byte aligned)
my bias->data.f has an address of 0x...........8 (8 byte aligned)

While this can still work, the hardware optimization I am trying to implement works better if the data is 16-byte aligned. The only option I see is to specifically treat the first two floats (8 bytes), and then use full optimization for the rest of the data.

SO, my question is whether there is some option somewhere during conversion to align the the data within each tensor! I assume there would be some option to have it pad the data structures in the flatbuffer model with a few zeros before beginning the float data array.

The only posts I have seen regarding memory alignment are for TensorflowLite Micro, which isn't really an option for me.

### 5. (optional) Any other info / logs
If there is no option in the converter to achieve what I want, I suppose I can make the changes myself when the memory is allocated in TFlite, but I could use a nudge in the right direction. My assumption is that the model is parsed somewhere, and I would like to add some instruction to make sure the TfLiteTensor->data is properly aligned. Do you know where the easiest place to make that change would be?

Thanks!

**Comment by abattery** [comment]
For your specific cases, you might need to create your own data type in TensorFlow Lite and modify the converter and runtime to suppport it.

**Comment by abattery** [comment]
@srjoglekar246 could you take a look?

**Comment by MisterBerg** [comment]
Hello, Sachin.

If it helps, you can load the model I provided into a debug version of Tensorflow Lite, and set a breakpoint at optimized_ops.h line 420 or so.  The PoC I am demonstrating branches from here. Two of the data arrays should be 16-byte aligned, and two should be 8-byte aligned, in the FullyConnected( ) function somewhere..  Again, while I can work around it, it would be preferable if there was some way to build/load the model in a way that all the tensor data arrays were 16-byte aligned by default.

Thanks in advance!

**Comment by srjoglekar246** [comment]
@MisterBerg you are correct, AFAIK the constants in TFLite flatbuffers (and even the runtime TFLite tensors) are required to be aligned at 8 bytes. This is mainly because most of the underlying backends/kernels we use don't require any greater alignment. 
@miaout17 and I had discussed this a while back....YC, is there a way to make the converter align constants to a different multiple of 8 bytes? We cannot use an arbitrary alignment for obvious reasons, but any multiple of 64 bits should be okay I think.

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
