### ISSUE TITLE
tf.data.Iterator:  TypeError: object() takes no parameters

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51346]
tf 2.5
[tf.data.Iterator](https://tensorflow.google.cn/api_docs/python/tf/data/Iterator?hl=en)

```
dataset = tf.data.Dataset.range(10)
iterator = tf.data.Iterator(dataset)
print(iterator.get_next())
```

```
Traceback (most recent call last):
  File "test6.py", line 32, in <module>
    iterator = tf.data.Iterator(dataset)
TypeError: object() takes no parameters
```

**Comment by sjtusmartboy** [comment]
Also I'd like to ask whether there is any group that we can get access to the developer quickly. Because I've submit some issues for half a month, only to see the assignees changing times and times, but get no solutions, the efficiency of which is so low.

**Comment by sanatmpa1** [comment]
@sjtusmartboy,

Can you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) to expedite the troubleshooting process. Thanks!

**Comment by sjtusmartboy** [comment]
@sanatmpa1 try the code and you find it

**Comment by sanatmpa1** [comment]
I am able to reproduce the issue in colab, Please find the [gist here](https://colab.research.google.com/gist/sanatmpa1/9e778630d765279bed8c1a70b6ff289e/51346.ipynb).

**Comment by sanatmpa1** [comment]
@sjtusmartboy,

If you want to iterate through `dataset`, Can you try using the python iterator protocol `iter()` and it works fine as added in the above gist.

You need to replace the second line, 
`iterator = tf.data.Iterator(dataset)` with `iterator = iter(dataset)` and let us know if it helps. Thanks!

**Comment by sjtusmartboy** [comment]
@sanatmpa1 thanks, it seems tf.data.Iterator is of no use at all because you are using the python iter. If not, please teach me how to use tf.data.Iterator.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
