### ISSUE TITLE
How to add ARG_MAX operation in tensorflow lite android with GPU ?

### ISSUE THREAD

**Issue by yonatanbitton** [tensorflow/tensorflow#51433]
I am working with tensorflow 2.5.0. I take a 4d tensor and perform argmax in a lambda function:

```python
def activate_postprocess(tensor):
  res = []
  for i in range(k):
    res.append(tf.argmax(tensor[i]))
  return res

post_processe_layer = tf.keras.layers.Lambda(activate_postprocess)
post_processed_output = post_processed_layer(model.outputs)
```

then I convert, adding `TFLITE_BUILTINS` and `SELECT_TF_OPS`:

```python
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS,
                                             tf.lite.OpsSet.SELECT_TF_OPS
                                             ]
    tflite_model = converter.convert()
```

And then I run in the Android app, with GPU delegate

```
val options = Interpreter.Options()
val compatList = CompatibilityList()
val delegateOptions = compatList.bestOptionsForThisDevice
                gpuDelegate = GpuDelegate(delegateOptions)
                options.addDelegate(gpuDelegate)
```

After running the model, I receive the following error:
```
Failed for 'img.jpg' with error: Internal error: Failed to apply delegate: Following operations are not supported by GPU delegate:
    ARG_MAX: Operation is not supported.
```
I also tried `options.setUseNNAPI(true) `before creating the interpreter, but it doesn't help.
How can I solve it? 

I see this: https://www.tensorflow.org/lite/guide/ops_custom
But I don't understand how to register the operator (https://www.tensorflow.org/lite/guide/ops_custom#create_and_register_the_operator) 

Is there an example with argmax? 

Thanks

**Comment by impjdi** [comment]
Yeah, I don't recall our team implementing an `ARG_MAX` op.  The closest we have is probably `MAX_POOL` with indices.  The shader code should be in the repository.

Adding custom op to the delegates requires a LOT of plumbing.
* First, you need to make tflite convert understand that custom op of yours (I have never worked in this domain and don't know how easy it is).
* Then you need to create the op and register it, so that the op resolver understand the custom op.  You can skip the implementation of the op if you know you will fully work on the GPU side, but often it's beneficial to have a reference CPU implementation.
* After that, you need to change the GPU delegate's model builder to recognize the new op.  This involves parsing the op and representing this in `GraphFloat32` which is the internal data structure the GPU delegate uses.  Might involve definition of attributes.
* Last but not least, you need to implement the shader code.  If you're not proficient with compute shaders, this can be a major headache.

**Comment by freedomtan** [comment]
@yonatanbitton NNAPI does support ArgMax. However, default output data type of [tf.argmax](https://www.tensorflow.org/api_docs/python/tf/math/argmax) is `int64`, which is not supported by [NNAPI's argmax](https://developer.android.com/ndk/reference/group/neural-networks). If `int32` is enough for your use, please use `tf.argmax(tensor[i], output_type=tf.dtypes.int32)` instead.

**Comment by pjpratik** [comment]
Hi @yonatanbitton 

As @freedomtan suggests, will int32 works for your use case to use [NNAPI's argmax](https://developer.android.com/ndk/reference/group/neural-networks#group___neural_networks_1ggaabbe492c60331b13038e39d4207940e0a89be86ff36e83254e9b3d0954e7e0729)?

Thanks.
