### ISSUE TITLE
Normalizations based on TFLite input type

### ISSUE THREAD

**Issue by pranathibl** [tensorflow/tensorflow#51454]
Why there is a different kind of normalization technique used for each data type.

Could you explain the reasoning for using these.

Using Tensorflow version 2.4.1.
Reference - https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/lite/examples/label_image/bitmap_helpers_impl.h ,
https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/lite/examples/label_image/get_top_n_impl.h

For input normalizing .
![Capturefgregtrgtr](https://user-images.githubusercontent.com/47776253/129198641-5f186ab7-7429-4f76-b7fa-29a4ee98b745.JPG)
For output .
![Capturesssssss](https://user-images.githubusercontent.com/47776253/129198676-1b67f9a0-1375-425a-b612-29980532d631.JPG)

Are these valid all kinds of TFLite Models?

**Comment by pranathibl** [comment]
Does this valid for all TFLite Models including RNN models ?

Could you explain the reasoning for that ?

**Comment by pjpratik** [comment]
Hi @pranathibl 

The normalisation is done based on the data type since different data types have different ranges.  

For float32 data type, the mean normalization is done by subtracting with mean and dividing with standard deviation to normalize the input in the range [-1,1] with mean 0 and standard deviation 1.

Similarly. for int8, the input is normalised to be in range [-128,127] and for unit8 no normalization is required.

This is done to normalize the input, irrespective of using RNNs or CNNs.

Thanks.
