### ISSUE TITLE
Support freezing ResourceGather ops in subgraphs

### ISSUE THREAD

**Issue by TomWildenhain-Microsoft** [tensorflow/tensorflow#51488]
Support freezing ResourceGather ops in subgraphs.  Currently skipped.
https://github.com/tensorflow/tensorflow/blob/00a29e825c5f1cd86fb2031f0c78326284637f7f/tensorflow/python/framework/convert_to_constants.py#L407

**Describe the feature and the current behavior/state.**
Not implemented

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Anyone freezing a graph with resource gather ops in the subgraph

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
