### ISSUE TITLE
Error with running tensorflow/tensorflow/examples/tutorials/mnist/fully_connected_feed.py

### ISSUE THREAD

**Issue by aashish-kumar** [tensorflow/tensorflow#5151]
I am not able to run the example for mnist
$ python fully_connected_feed.py 
Extracting data/train-images-idx3-ubyte.gz
Extracting data/train-labels-idx1-ubyte.gz
Extracting data/t10k-images-idx3-ubyte.gz
Extracting data/t10k-labels-idx1-ubyte.gz
Error Log: Traceback (most recent call last):
  File "fully_connected_feed.py", line 268, in <module>
    tf.app.run()
  File "/home/aashishk/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "fully_connected_feed.py", line 219, in main
    run_training()
  File "fully_connected_feed.py", line 143, in run_training
    **summary = tf.summary.merge_all()
AttributeError: 'module' object has no attribute 'merge_all'**

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
http://stackoverflow.com/questions/33772833/error-while-merging-summaries-for-tensorboard

### Environment info
Operating System: Ubuntu

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`): none

**Tensorflow** **0.10.0** installed using **conda** **4.2.9**
I am only taking the examples folder from here to test with the above version

**Comment by asimshankar** [comment]
@aashish-kumar : It seems you're running `fully_connected_feed.py` from the HEAD of the git repository, which is incompatible with the release version (in particular because of change https://github.com/tensorflow/tensorflow/commit/8532897352ada1d8ecd3ca1dd17aaa869a42d4b8)

Many examples are installed with the release, so you would find some files in:
`/home/aashishk/anaconda2/envs/tensorflow/lib/python2.7/site-packages/tensorflow/examples/tutorials/mnist`

However, since `fully_connected_feed.py` is not used in the website tutorials, we don't include it with the release. That said, you can find the versions that work with the release in the release branches on git.

- [For 0.10](https://github.com/tensorflow/tensorflow/tree/r0.10/tensorflow/examples/tutorials/mnist)
- [For 0.11](https://github.com/tensorflow/tensorflow/tree/r0.11/tensorflow/examples/tutorials/mnist)

Hope that explains the situation and helps you get out of it :)
I'm going to close this issue since I believe it is resolved, but if not, feel free to reopen it.

Thanks!
