### ISSUE TITLE
Support compression type "SNAPPY" in Tensorflow Python API

### ISSUE THREAD

**Issue by xiu2049** [tensorflow/tensorflow#51536]
**System information**
- TensorFlow version (you are using): 2.5.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
From https://www.tensorflow.org/api_docs/python/tf/io/TFRecordOptions?hl=en, it does not appear that TensorFlow (up till v2.6.0) supports "SNAPPY" as a compression type in the Python API. However, in c++ source code https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/lib/io/record_writer.h#L44, this is already supported. For my use case, "SNAPPY" is preferred over "ZLIB" or "GZIP". Therefore, having "SNAPPY" as an option in Python TFRecord API is a desirable feature.

**Will this change the current api? How?**
Yes. The `compression_type` field of TFRecordOptions will have valid values of "GZIP", "ZLIB", "SNAPPY"(new) or "" (no compression).

**Who will benefit with this feature?**
Users who want to use snappy as their compression algorithm in order to take advantage of its speed.

**Any Other info.**

**Comment by mohantym** [comment]
Hi!@zxiu2049 !We  see that the issue template has not been filled, Could you please do so as it helps us analyse the issue .

**Comment by zxiu2049** [comment]
> Hi!@zxiu2049 !We see that the issue template has not been filled, Could you please do so as it helps us analyse the issue .

Hi @mohantym ! Thanks for the response. Modified the description based on the feature request template. Please let me know if that works.

**Comment by mohantym** [comment]
Hi @Saduf2019  ,Could you please look into this issue ?

**Comment by glinscott** [comment]
Something like this works in the meantime until it's officially added:
```
def enable_snappy_compression():
    """
    Workaround Snappy not being a public option yet.
    """
    tf.io.TFRecordOptions.compression_type_map[3] = "SNAPPY"
```
and then just:
```
tf.data.TFRecordDataset(file, compression_type="SNAPPY")
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
