### ISSUE TITLE
ios demo app version error

### ISSUE THREAD

**Issue by hyuDev** [tensorflow/tensorflow#51543]
hi, I want to build an object detection ios demo app using tflite model.
but your code support ios14.4, my ios is 14.6.
Apple doesn't assign ios to downgrade 14.6 to14.4.
so did you upgrade for ios 14.6?? 

thanks,

**Comment by tilakrayal** [comment]
@hyuDev ,

In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem

**Comment by hyuDev** [comment]
OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: the IOS device with ios14.6
TensorFlow installed from (source or binary): maybe binary(I install TF with pip3)
TensorFlow version: 1.15.0
Python version:3.6.5
Installed using virtualenv? pip? conda?: pip3 
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version: NO CUDA, only CPU
GPU model and memory: NO GPU, only CPU


the project error is"this device' os is not supported, we support ios 14.4"

**Comment by tilakrayal** [comment]
@hyuDev ,
We see that you are using tf version 1.15, 1.x is not actively supported, please update to stable version tf v2.5, v2.6 and let us know if you are facing same issue.Thanks!
