### ISSUE TITLE
An easy way to update tensors that complies with numpy syntax

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#51582]
**System information**
- TensorFlow version (you are using): 2.6
- Are you willing to contribute it (Yes/No): No (wouldn't know how)

**Describe the feature and the current behavior/state.**
I would love to be able to do something like the following:
```python
t1 = np.zeros((2, 4))
t2 = np.ones((2, 3))

t1[:, 1:4] += t2
t1[:, [3, 1, 1]] += t2
```
without having to use methods like `tensor_scatter_nd_update` over multiple lines of code...

**Will this change the current api? How?**
yes, it will be possible to use a syntax like in numpy, that everyone is familiar with.

**Who will benefit with this feature?**
everyone who needs to build tensors manually

**Comment by mihaimaruseac** [comment]
TF tensors are supposed to be immutable

**Comment by mohantym** [comment]
Hi @ziofil !  
We see that the issue template has not been filled, could you please do so as it helps us analyse the issue .Thanks

**Comment by ziofil** [comment]
> TF tensors are supposed to be immutable

I know, but then again there are methods like [`tf.tensor_scatter_nd_update`](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update), so effectively tensor are mutable if one uses the right methods. So why not allowing a clearer syntax?

**Comment by ziofil** [comment]
> Hi @ziofil !
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue .Thanks

Hi @mohantym I understand, but the issue is clear: I'd like a simple syntax for in-place tensor updates, given that there are methods for doing this already.

**Comment by ziofil** [comment]
> Hi @ziofil !
> We see that the issue template has not been filled, could you please do so as it helps us analyse the issue .Thanks

Done.

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,Could you please look into these issue!

**Comment by cantonios** [comment]
An RFC tp address this has been up for a bit.  Adding a link here in case anyone wants to provide input.

Comments are invited to the [pull request](https://github.com/tensorflow/community/pull/433). You can view the [design doc here](https://github.com/tensorflow/community/blob/77aa8fd5ea9c54bf1f08e9d25113aaa1ea90ba20/rfcs/20221020-tensor-indexed-updates.md), and also [leave comments inline](https://github.com/tensorflow/community/pull/433/files) on the document source.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
