### ISSUE TITLE
calback pyfunc_18 is not found

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51623]
**tensorflow 2.5, python3.7**

I'm using tf.py_function in the model, and after training, the model is saved with tf.saved_model.save().

Is this the compatible problem of these two functions that causes this error?

**Comment by tilakrayal** [comment]
@sjtusmartboy ,

 In order to expedite the trouble-shooting process, could you please provide a complete code and dataset  you are using.Also please take a look at this [comment](https://stackoverflow.com/questions/56227140/using-py-func-inside-tensorflow-valueerror-callback-pyfunc-0-is-not-found) with similar error.It helps.Thanks
