### ISSUE TITLE
ValueError: `tape` is required when a `Tensor` loss is passed.

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#51622]
**tensorflow 2.5 python 3.7**

As said in https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Optimizer?hl=en#minimize,  the first parameter of minmize should satisfy the requirement,

_Tensor or callable. If a callable, loss should take no arguments and return the value to minimize. If a Tensor, the tape argument must be passed._

The first piece of code takes tensor as the input of minimize(), and it requires the gradient tape, but I don't know how.
The second piece of code takes callable function as the input of minimize(), which is easy 

```
import numpy as np
import tensorflow as tf
from tensorflow import keras

x_train = [1, 2, 3]
y_train = [1, 2, 3]

W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
hypothesis = W * x_train + b


@tf.function
def cost():
    y_model = W * x_train + b
    error = tf.reduce_mean(tf.square(y_train - y_model))
    return error


optimizer = tf.optimizers.SGD(learning_rate=0.01)

cost_value = cost()
train = tf.keras.optimizers.Adam().minimize(cost_value, var_list=[W, b])

tf.print(W)
tf.print(b)
```
How to add the gradient tape, I know the following code certainly works.
```
import numpy as np
import tensorflow as tf
from tensorflow import keras

x_train = [1, 2, 3]
y_train = [1, 2, 3]

W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
hypothesis = W * x_train + b


@tf.function
def cost():
    y_model = W * x_train + b
    error = tf.reduce_mean(tf.square(y_train - y_model))
    return error


optimizer = tf.optimizers.SGD(learning_rate=0.01)

cost_value = cost()
train = tf.keras.optimizers.Adam().minimize(cost, var_list=[W, b])

tf.print(W)
tf.print(b)
```
Please help me revise the first piece of code and let it run, thanks!

**Comment by mohantym** [comment]
Hi @sjtusmartboy , was able to replicate and resolve in TF2.6 by replacing `cost = cost()`  with` cost = lambda: cost()` , providing [gist ](https://colab.research.google.com/gist/mohantym/6e008dd557ebee5d20bbd8e32c34d705/github_51622.ipynb)for reference.please look at this [documentation ](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam)for further details

**Comment by sjtusmartboy** [comment]
@mohantym Thanks for your code. If cost function has a 'step' parameter that I want to record, then how to pass that variable into the cost()?

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,could you please look into this issue.

**Comment by gowthamkpr** [comment]
This occurs because .minimize() expects a function. While cost_value&cost(), is a tf.Tensor object, cost is a tf.function. You should directly pass your loss function into the minimize as `tf.keras.optimizers.Adam().minimize(cost, var_list=[W, b])`. You can get the full detailed explanation [here](https://stackoverflow.com/questions/68879963/valueerror-tape-is-required-when-a-tensor-loss-is-passed). 
Here is the working [gist](https://colab.sandbox.google.com/gist/gowthamkpr/f98e892695882be6d8f555dbc3b12432/untitled385.ipynb). 

Also, if you still think this is an issue, please create a new issue in this [repo](https://github.com/keras-team/keras/issues/new/choose) as the development of keras has been moved to a different repo. Thanks!
