### ISSUE TITLE
AttributeError: 'module' object has no attribute 'histogram'

### ISSUE THREAD

**Issue by abhishekbanthia** [tensorflow/tensorflow#5163]
### Environment info
Operating System: MacOS 10.12

Running tensorflow (0.11.0rc1), I'm trying to retrain the Inception's final layer with my own set of images, and I'm running into this error:

<img width="749" alt="screen shot 2016-10-24 at 12 56 46 am" src="https://cloud.githubusercontent.com/assets/8280282/19637602/c7ea232e-9984-11e6-8d9d-5e0ba56a7b47.png">

**Comment by asimshankar** [comment]
@abhishekbanthia : It seems you're running example code from the HEAD of master branch of the tensorflow git repository, which is not compatible with the release (in this case, because of https://github.com/tensorflow/tensorflow/commit/8532897352ada1d8ecd3ca1dd17aaa869a42d4b8#diff-e27def9997dcd569e1f2412fd6f3ae76).

Perhaps you `git clone`ed the master branch, instead of the release branch, to get the example code? To clone the release branch, you can use:
```sh
git clone -b r0.11 https://github.com/tensorflow/tensorflow
```

Hope that helps.
(And in the future, please try to fill in the [New issue template](https://github.com/tensorflow/tensorflow/issues/new), in particular the section about providing a minimal example to reproduce the error as that is often the most useful in helping to diagnose a problem).

Feel free to re-open this issue with more details if using the release branch does not solve the problem. Thanks!

**Comment by mohamedsahadkp** [comment]
Thanks, This has worked for me

**Comment by hiteshvaidya** [comment]
![image](https://cloud.githubusercontent.com/assets/14166608/23104603/0c765a74-f6f7-11e6-9185-336663aa7a8d.png)
can you please help me with this error? I tried the solution given in earlier post of git clone...... in the folder of the code that I want to run. But it didn't work. Can you please help?

**Comment by asimshankar** [comment]
Which version of TensorFlow are you using? It seems you're using one from head. I'd suggest using the release version if possible ad things in head will always be in flux and it can be hard to support. That said, do browse through the [upgrade instructions](https://www.tensorflow.org/install/migration). In this particular case, you want to use `tf.summary.histogram`.

Going forward, with future 1.x releases, the API will be much more stable.

**Comment by sagrawal1993** [comment]
I have tenserflow with 0.11.0rc2 version, but still getting error.
