### ISSUE TITLE
files not found "graph.pb.h" and "image_ops.h"

### ISSUE THREAD

**Issue by civilmanxx** [tensorflow/tensorflow#5170]
The 2 files below are included in main.cc of label image example, but i can't find these 2 **.h** files in the relevant **ops** and **framework** folders. So we can remove them out directly?

#include "**tensorflow/cc/ops/image_ops.h**"
#include "**tensorflow/core/framework/graph.pb.h**"

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc#L38

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/label_image/main.cc#L40

**Comment by asimshankar** [comment]
These files are generated when you use `bazel build` to build the example.  The files are placed in `bazel-genfiles`. 

Hope that helps.

**Comment by ranka47** [comment]
Hi 

I am compiling a C++ file using the following command: 

`g++ -std=c++11 validation.cpp -L./ -ltensorflow_cc -o validation -I/home/hadoop/git/tensorflow-r1.8/  -I/home/hadoop/git/eigen3/ -I/home/hadoop/git/tensorflow-r1.8/bazel-genfiles/`

To come to this step: 

1. First I built the `libtensorflow_cc.so` using `bazel build //tensorflow:libtensorflow_cc.so`
2. Then I copied the .so file to the project directory: 
`cp bazel-bin/tensorflow/libtensorflow_cc.so ~/projects/tf-vad-validation/.` 
3. Included the cloned folder of branch `r1.8` and the `bazel-genfiles` for including some missing header files like `const_op.h`
4. Cloned and included the eigen3 folder because the compiler went into deep nested loop while importing `unsupported/Eigen/CXX11/Tensor`

After this I got the error: 
`bazel-genfiles/tensorflow/core/lib/core/error_codes.pb.h:9:42: fatal error: google/protobuf/stubs/common.h: No such file or directory`

How to deal with this error?
