### ISSUE TITLE
More freedom in Dtype of indices of sparse.SparseTensors

### ISSUE THREAD

**Issue by benoitdescamps** [tensorflow/tensorflow#51728]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): v2.6.0
- Are you willing to contribute it (Yes/No):
Yes

**Describe the feature and the current behavior/state.**
sparse.SparseTensors  'indices dtype are hardcoded as tf.int64. I would like to allow other integers types (tf.uint8, tf.uint16, tf.uint32, tf.uint64, tf.int8, tf.int16, tf.int32)
see https://github.com/tensorflow/tensorflow/blob/919f693420e35d00c8d0a42100837ae3718f7927/tensorflow/python/framework/sparse_tensor.py#L130

**Will this change the current api? How?**
need to be investigated. I am not sure why this is hard-coded.
**Who will benefit with this feature?**
Smaller memory useage of SparseTensors which is needed in a lot of application with limited RAM.
**Any Other info.**

**Comment by mohantym** [comment]
@benoitdescamps !
It still has not been addressed in[ 2.10 version](https://github.com/tensorflow/tensorflow/blob/r2.10/tensorflow/python/framework/sparse_tensor.py).

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Could you please take a look at this comment from the developer where it was mentioned that having a way for shape computations to remain on host/cpu is critical for managing data transfer to/from GPU. 
https://github.com/tensorflow/tensorflow/issues/59803#issuecomment-1462917015

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
