### ISSUE TITLE
tf.vectorized_map fails on ragged tensors

### ISSUE THREAD

**Issue by catskillsresearch** [tensorflow/tensorflow#51771]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 21.04
- TensorFlow installed from (source or binary): pip install tensorflow==2.6.0
- TensorFlow version (use command below): 2.6.0
- Python version: 3.9
- CUDA/cuDNN version: 11.4
- GPU model and memory: 2080ti

**Describe the current behavior**

tf.vectorized_map fails on RaggedTensor

**Describe the expected behavior**

tf.vectorized_map succeeds on RaggedTensor

**Standalone code to reproduce the issue**

```
import tensorflow as tf

tf.__version__ # 2.6.0

A1 = tf.constant([[1,3], [1,5]], dtype=tf.float32)

b1 = tf.constant([3,4], shape = (2,1), dtype=tf.float32)

tf.linalg.lstsq(A1,b1) # SUCCEEDS, single task

A2 = tf.constant([[1,3], [1,4], [1,5]], dtype=tf.float32)

b2 = tf.constant([2,3,4], shape = (3,1), dtype=tf.float32)

tf.linalg.lstsq(A2,b2) # SUCCEEDS, single task

A1A1 = tf.stack([A1,A1])

b1b1 = tf.stack([b1,b1])

tf.linalg.lstsq(A1A1, b1b1) # SUCCEEDS, parallel task

A1A1ragged = tf.ragged.stack([A1,A1])

tf.linalg.lstsq(A1A1ragged, b1b1) # FAILS TypeError: object of type 'RaggedTensor' has no len()

@tf.function
def least_squares(task):
    A, b = task
    return tf.linalg.lstsq(A.to_tensor(), b)

tf.stack([least_squares(task) for task in zip(A1A1ragged, b1b1)]) # SUCCEEDS, serial task

tf.map_fn(least_squares, (A1A1ragged, b1b1), dtype = tf.float32) # SUCCEEDS, possible but not guaranteed parallel task

tf.vectorized_map(least_squares, (A1A1ragged, b1b1))  # FAILED, ValueError: Received a shape scalar with unknown static value

A1A2ragged = tf.ragged.stack([A1,A2])

b1b2 = tf.ragged.stack([b1,b2])

@tf.function
def least_squares_ragged(task):
    A, b = task
    return tf.linalg.lstsq(A.to_tensor(), b.to_tensor())

tf.ragged.stack([least_squares_ragged(task) for task in zip(A1A2ragged, b1b2)])  # SUCCEED, but serial

tf.map_fn(least_squares_ragged, (A1A2ragged, b1b2), dtype = tf.float32) # SUCCEED,not guaranteed parallel

tf.vectorized_map(least_squares_ragged, (A1A2ragged, b1b2)) # FAIL  ValueError: Received a shape scalar with unknown static value

```

**Comment by mohantym** [comment]
Hi @sanatmpa1 ,Could you please look at this issue , providing [gist](https://colab.research.google.com/gist/mohantym/ad7afdd8f8f312b5c84b2c4d7d417696/github_51771.ipynb#scrollTo=Q-WhCzmqRkiw) for reference.

**Comment by ishark** [comment]
Acknowledged. Have added it to backlog of bugs to investigate for pfor support. There is a generic required support to be added for Composite Tensors.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
