### ISSUE TITLE
Is there any update on profiler's TensorCores eligible rules?

### ISSUE THREAD

**Issue by gaoteng-git** [tensorflow/tensorflow#51812]
@yisitu
I find the rules code to judge whether a kernel uses Tensor Cores is 1~2 years old. I'm not sure whether there should be new updates, along with latest hardward chips or library updates.
BTW, how these rules come from? Is there any doc that lists all kernels which uses Tensor Cores?

https://github.com/tensorflow/tensorflow/blob/5dcfc51118817f27fad5246812d83e5dccdc5f72/tensorflow/core/profiler/utils/kernel_stats_utils.cc#L95-L119

**Comment by yisitu** [comment]
@trisolaran  these rules need to be updated for Ampere and beyond.

**Comment by gaoteng-git** [comment]
@yisitu Thanks! But how do you get the rules? Maybe I could contribute if I know the way to get them.

**Comment by yisitu** [comment]
Hi Gao,

It is a heuristic and obtained mainly through observation, empirical data, and research. I agree that it would be great if NVIDIA documentation lists all kernels which uses Tensor Cores. Alternatively, you could read the cuDNN documentation to see the prereqs for using TensorCores and observe what kernels are launched - but this requires significant amount of effort.

Situ

**Comment by gaoteng-git** [comment]
Hi yisitu,
Thanks a lot for response! 
Do you mean trying to run a lot of classic models on different NVIDIA archtectures(such as Turing and Volta), and using [nvprof and tensor_precision_fu_utilization metric](https://developer.nvidia.com/blog/using-nsight-compute-nvprof-mixed-precision-deep-learning-models/) to check each kernel, recording every one with this metric valid? This way is also time consuming and can't cover full kernel set.
Yes, I don't find any list provided by NVIDIA. The document is not detail enough to kernel level.

**Comment by yisitu** [comment]
It is not so much about the models as it is about the resulting cuDNN kernels for each GPU architecture. You can simplify this a little more to cover just the cuDNN TensorCore use cases.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
