### ISSUE TITLE
TF-32 Tensor Cores not used

### ISSUE THREAD

**Issue by atyshka** [tensorflow/tensorflow#51826]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: 11.1
- GPU model and memory: RTX A6000, 48GB

**Describe the current behavior**
I'm training a fairly large convnet, and with long training times, one thing I've noticed is apparent lack of tensor core utilization. I have tried using float16, but my model greatly suffers from the reduced precision. However, since this is an Ampere GPU I expect to be able to use tensor cores in 32 bit as well. Using the tensorboard profiler, I see many of my kernels are tensor core eligible but none are actually using tensor cores. 
<img width="785" alt="Screen Shot 2021-09-03 at 11 50 49 AM" src="https://user-images.githubusercontent.com/19317207/132033324-c31d0d45-d1cc-4bee-80da-c747028f69b7.png">

All of my convolution layers have multiples of 8 for filters (32, 64, 128, etc.) so dimensions should not be affecting tensor cores. One other thing I though worth noting was lots of memory being taken up by NHWC->NCHW transpose layers. It's my understanding that tensor cores should operate entirely in NHWC, so my model should not be doing any computation in NCHW and yet it seems to be.

<img width="750" alt="Screen Shot 2021-09-03 at 11 54 19 AM" src="https://user-images.githubusercontent.com/19317207/132033733-18ce0744-ed68-467b-9f1f-b802198061dc.png">

**Describe the expected behavior**
I expect Tensor Cores to be used for most convolution and matmul operations provided the multiple-of-8 condition is met. One thing I'm wondering: is it possible that the bug is actually in reporting tensor core usage rather than not using tensor cores in the first place? I.e. is tensorboard only looking for float16 tensor cores and not reporting tf-32 operations as using tensor cores when they actually are? That still doesn't explain the NCHW behavior though.  

**Standalone code to reproduce the issue**
Working on producing an example. Colab is not an option due to lack of Ampere GPUs

**Other info / logs** Include any logs or source code that would be helpful to
diagnose the problem. If including tracebacks, please include the full
traceback. Large logs and files should be attached.

Here is my TensorBoard log file. This includes the profiler data as well as a model checkpoint for inspecting the architecture
[20210902-145514.zip](https://github.com/tensorflow/tensorflow/files/7107228/20210902-145514.zip)

**Comment by sushreebarsa** [comment]
@atyshka Could you please post this issue in [Tensorboard repo](https://github.com/tensorflow/tensorboard/issues) ,you will get the right help there ?Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
