### ISSUE TITLE
set_visible_device_list causing session create failure

### ISSUE THREAD

**Issue by Shadowman82** [tensorflow/tensorflow#51847]
**System information**
- Standard code (as shown in the "gpu_device_test.cc" provided with TF source code)
- Windows 10 64 bit
- Tensorflow built from source
- TF 2.5
- Python 3.8.7
- Bazel 3.7.2
- CUDA 11.2 cudnn 8
- GeForce GTX 1050

The session create function fails if I set a specific GPU with the function set_visible_device_list, even if I have a single GPU.
For instance if I set the GPU like this
```
SessionOptions options;
ConfigProto* config = &options.config;
(*config->mutable_device_count())["GPU"] = 1;
config->mutable_gpu_options()->set_visible_device_list("0");
```

The subsequent piece of code and in the specific the session create fails. If I don't set, it doesn't fail.

```
architecture->session.reset(NewSession(options));
graph_def.reset(new GraphDef());
ReadBinaryProto(Env::Default(), (string)architecture_path, graph_def.get());
architecture->session->Create(*graph_def.get());
```

The GPU is working and visbile by Tensorflow
```
auto gpu_factory = DeviceFactory::GetFactory("GPU");
gpu_factory->ListPhysicalDevices(&devs_gpu);
```

How can I set a specific GPU?

**Comment by Shadowman82** [comment]
In addition if I call the CreateDevices after setting the specific GPU, it also fails wit this error

`DeviceFactory::GetFactory("GPU")->CreateDevices(options, kDeviceNamePrefix, &devices) failed: "Internal: Failed to get memory allocator for TF GPU 0 with 2914163099 bytes of memory."`

```
std::vector<std::unique_ptr<Device>> devices;
const char* kDeviceNamePrefix = "/job:localhost/replica:0/task:0";
DeviceFactory::GetFactory("GPU")->CreateDevices(options, kDeviceNamePrefix, &devices);
```

**Comment by mohantym** [comment]
Hi @jvishnuvardhan ,could you please look into this issue?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
