### ISSUE TITLE
Tensorflow does not work with python -OO because of __doc__ usage

### ISSUE THREAD

**Issue by klamann** [tensorflow/tensorflow#51896]
**System information**

- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): any
- TensorFlow installed from (source or binary): pip wheel
- TensorFlow version (use command below): 2.6.0
- Python version: 3.9

**Describe the current behavior**

Tensorflow crashes when being executed in a context where python was started with the [`-OO`](https://docs.python.org/3/using/cmdline.html#cmdoption-oo) flag. This happens because tensorflow is dynamically changing [`__doc__`](https://github.com/tensorflow/tensorflow/search?q=__doc__) variables during runtime and all of these variables become `None` when `python -OO` is used. An exception will be raised whenever a source file is loaded which tries to modify a `__doc__` variable, usually something along the lines of

    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

which is raised by e.g. [/tensorflow/python/ops/array_ops.py#L452](https://github.com/tensorflow/tensorflow/blob/1f0c1d8ec778b029028a27a47a89acf6a93637ad/tensorflow/python/ops/array_ops.py#L452)

    listdiff.__doc__ = gen_array_ops.list_diff.__doc__ + "\n" + listdiff.__doc__

but there are lots of other places in the code where this can happen.

**Describe the expected behavior**

Tensorflow should play nicely with `python -OO`. All code that modifies [`__doc__`](https://github.com/tensorflow/tensorflow/search?q=__doc__) variables during runtime would require `None` checks.

**Standalone code to reproduce the issue**

`python -OO -c "from tensorflow.python.ops import array_ops"` fails with

    TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

But `python -O -c "from tensorflow.python.ops import array_ops"` works fine, because [`-O`](https://docs.python.org/3/using/cmdline.html#cmdoption-o) does not discard docstrings. I would expect tensorflow to work with both `-O` and `-OO`.

*edit*: updated code to reproduce

**Comment by tilakrayal** [comment]
@klamann ,
Can you please check this [SO](https://stackoverflow.com/questions/15036594/how-to-fix-typeerror-unsupported-operand-types-for-nonetype-and-str) link for the issue with similar error.It helps.Thanks!

**Comment by tilakrayal** [comment]
Also In order to expedite the trouble-shooting process, could you please provide the complete code and dataset to reproduce the issue reported here.

**Comment by klamann** [comment]
There is no dataset required and I provided a complete working example. You can try it in your terminal, it's just one call:

    python -OO -m tensorflow.python.ops.array_ops

It will fail with the mentioned `TypeError`.

The linked SO post has nothing to do with this issue.

**Comment by tilakrayal** [comment]
@klamann ,
Can you please share a colab gist with the issue reported, it helps to debug the issue from our side.Thanks

**Comment by klamann** [comment]
Hi @tilakrayal, I don't want to register a google account and I'm not sure that you can change the launch parameters in a google colab document anyways. The steps to reproduce are really easy:

1. open a terminal
2. run `python -OO -m tensorflow.python.ops.array_ops`
3. compare the output with `python -O -m tensorflow.python.ops.array_ops`

Step 2 will rause an exception, step 3 will not.
I'm not sure what else to say.

**Comment by sanatmpa1** [comment]
@klamann,

Step 2 produces the similar issue as you mentioned, but I am getting the below error for step 3. Please take a look at the [gist here](https://colab.research.google.com/gist/sanatmpa1/ed7db8bf974a570477ffe0281a8e2e0f/51896.ipynb).

**Comment by klamann** [comment]
you're right, I didn't notice this one. It seems to be unrelated, since `tensorflow.python.ops.array_ops` is not meant to be called as a module. We can work around this by just importing the module (without doing anything else).

This should work:

    python -c "from tensorflow.python.ops import array_ops"
    python -O -c "from tensorflow.python.ops import array_ops"

and this fails with the mentioned `TypeError`:

    python -OO -c "from tensorflow.python.ops import array_ops"

**Comment by rainwoodman** [comment]
Indeed it was surprising -- Tensorflow'ers probably shouldn't have assumed __doc__ is not None when the codebase was written years ago, but who would have known.. Be aware that  -OO can have other surprises too, like removing assertion statements. 

Another possible avenue is that -OO could have set __doc__ to "" instead of None to maximize the compatibility with runtime docstring generation; and an option to keep assertion's "side" effects in place would be nice.

I did some measurements on a typical self-contained training binary with -OO. The size went down by 30MB out of 1.4GB. We do tend to produce very large binaries in Google, so your ratios may be very different.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
