### ISSUE TITLE
tf.nn.max_pool_with_argmax to support multiple dimensions (ND) 

### ISSUE THREAD

**Issue by NEGU93** [tensorflow/tensorflow#51895]
**System information**
- TensorFlow version (you are using): 2.x
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Current Behavior:

Currently, there is a function called [tf.nn.max_pool_with_argmax](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool_with_argmax). 

Feature Request:

However, it would be great if the function supported several dimensions, not only 2D images.  [`tf.nn.max_pool`](https://www.tensorflow.org/api_docs/python/tf/nn/max_pool) for example supports any dimensionality. 

**Will this change the current api? How?**

I think the easiest will be to implement a new method like `tf.nn.max_pool_with_argmax_nd` not to have compatibility issues. 
Because it is a new method, this will also enable the fixing of the `tf.nn.max_pool_with_argmax` bug:

> This is a bug, but fixing it is difficult to do in a safe backwards compatible way, especially due to flattening.

**Who will benefit with this feature?**

This function is useful to, for example, implement ND [MaxUnpooling](https://www.oreilly.com/library/view/hands-on-convolutional-neural/9781789130331/6476c4d5-19f2-455f-8590-c6f99504b7a5.xhtml).

In particular, it will help me implement the [feature request](https://github.com/NEGU93/cvnn/issues/10) asked on my repository.

**Any Other info.**

Correct formatting of [this](https://github.com/tensorflow/tensorflow/issues/51787) feature request.

**Comment by mohantym** [comment]
Hi! @Saduf2019 ,Could you please look at this feature request?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
