### ISSUE TITLE
XLA HLO profiling not supported on GPU

### ISSUE THREAD

**Issue by donglinz** [tensorflow/tensorflow#51988]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): v2.5.0-rc3-213-ga4dfb8d1a71 2.5.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
when enable hlo profile via export XLA_FLAGS="--xla_hlo_profile", log says 
```
2021-09-14 17:15:45.256221: E tensorflow/compiler/xla/service/gpu/gpu_compiler.cc:893] --xla_hlo_profile for GPU is unsupported.
```

**Will this change the current api? How?**
No
**Who will benefit with this feature?**
Machine learning system researchers/engineers would benefit from this feature when profiling machine learning models.
**Any Other info.**

**Comment by mohantym** [comment]
Hi @jvishnuvardhan ,Could you please look at this issue .

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
