### ISSUE TITLE
Explanation about 'SAME' padding doesn't cover edge cases

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#5203]
In the [docs](https://www.tensorflow.org/versions/r0.11/api_docs/python/nn.html#convolution), it explains the padding as follows:
```
For the 'SAME' padding, the output height and width are computed as:

out_height = ceil(float(in_height) / float(strides[1]))
out_width  = ceil(float(in_width) / float(strides[2]))

and the padding on the top and left are computed as:

pad_along_height = ((out_height - 1) * strides[1] +
                    filter_height - in_height)
pad_along_width = ((out_width - 1) * strides[2] +
                   filter_width - in_width)
pad_top = pad_along_height / 2
pad_left = pad_along_width / 2
```
When `in_height=20, stride=2, filter_height=1`, we will end up with `pad_along_height=-1`. I think it's unclear what this means (is there padding or not?). Further explanation are needed to document the behavior in this case.

Also, when `in_height=19, stride=2, filter_height=1`, we will end up with `out_height=10, pad_along_height=0, pad_top=0`.  But with 19 inputs and stride=2 how can you have 10 output without padding? This doesn't seem right.

**Comment by drpngx** [comment]
It sounds reasonable to add documentation and a unit test to clarify, if you're willing to submit a PR.

@vrv perhaps to weigh in on the 2nd point.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/common_shape_fns.cc#L19 is the implementation the runtime uses.  For the first case, a negative padding is clipped to 0, though what it means is that the windows do not cover the entire input because you couldn't satisfy the 'output size' for SAME if you tried.

As for the second:  Let's say our 19 values are:

A B C D E F G H I J K L M N O P Q R S

We are selecting filter size of 1 and stride of 2, so we get:
A C E G I K M O Q S

which are 10 values.

Feel free to update our documentation if you think there's something better we can do, but I don't think there's a bug here?

**Comment by ppwwyyxx** [comment]
Oh yes. The second case is my misunderstanding. There isn't a bug here but the documentation can be improved a bit on the first case.

**Comment by drpngx** [comment]
Thanks @vrv for the clarification! @ppwwyyxx, please send a PR with doc changes if you want.
