### ISSUE TITLE
Profile TensorFlow Performance: Multiple occurences of single Conv2D op

### ISSUE THREAD

**Issue by shelkesagar29** [tensorflow/tensorflow#52048]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Custom
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: None
- TensorFlow installed from (source or binary): Binary
- TensorFlow version (use command below): 2.6
- Python version: 3.8
- Bazel version (if compiling from source): None
- GCC/Compiler version (if compiling from source): None
- CUDA/cuDNN version: 11.4/8.2
- GPU model and memory: RTX3090/24GB

**Describe the current behavior**
My goal is to profile NN layers runtime on GPU device (I am concerned only with inference). I am using
tf.profiler module.
Even though single convolution operation is used in the network, profile shows multiple Conv2D occurrences.

**Describe the expected behavior**
With one Conv2D used in the nwtrok, shouldn't profiler be showing only one Conv2D?

**Standalone code to reproduce the issue**
I have created a simple network as shown below.
dummy_net.py
```
import tensorflow as tf
import os

os.environ["CUDA_VISIBLE_DEVICES"] = "0"

class Net(tf.keras.Model):
    def __init__(self) -> None:
        super().__init__()
        self.conv = tf.keras.layers.Conv2D(6,3)
    
    def call(self, x):
        x = self.conv(x)
        return x
```
and profiling it on random input.
test_dummy_net.py

```
import tensorflow as tf
import dummy_net

inp = tf.random.uniform([1,300,300,3])
model = dummy_net.Net()
tf.profiler.experimental.start('./dummy_infer_logs')
y = model(inp)
tf.profiler.experimental.stop()
tf.debugging.set_log_device_placement(True)
```

**Other info / logs**
When I check profile logs in the TensorBoard, it shows that Conv2D op has occurred multiple times.
![image](https://user-images.githubusercontent.com/25697952/133830669-c238655e-13bd-4fc8-8bc7-b0932f7e056c.png)

When I add more Conv2D layers, occurrences go on increasing. For example, for 4 Conv2D layers more than 1900 occurrences are shown. This makes it difficult to get exact run times.

Also, why same operations are also run on the host?
![image](https://user-images.githubusercontent.com/25697952/133830755-44f70f07-8d18-41e7-9a90-6cf00e8dae1a.png)

**Comment by sushreebarsa** [comment]
@shelkesagar29 Could you please confirm if this issue is related tensorboard ? If so please post this issue in [tensorboard repo](https://github.com/tensorflow/tensorboard/issues).Thanks!

**Comment by shelkesagar29** [comment]
How can I confirm that?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
