### ISSUE TITLE
TF Lite `Conv1D` conversion bug

### ISSUE THREAD

**Issue by ebraraktas** [tensorflow/tensorflow#52064]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS Big Sur 11.4 and Ubuntu 18.04 LTS on Colab machine
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.3.0 and 2.6.0

### 2. Code

This notebook demonstrates the bug with the simplest example I came up with.

https://colab.research.google.com/gist/ebraraktas/69995d036a35a8d7f744c845a163863e

You can set `use_tf_2_3 = True` to see that it runs on tensorflow `2.3.0` with no error.

### 3. Failure after conversion

As you can see in the Colab gist, model can be converted to TF Lite model successfully, but different tensorflow versions creates different graphs (see [Netron](https://github.com/lutzroeder/netron) outputs below). And tensorflow lite versions >= 2.4.0 fail to reshape and allocate tensors. See runtime error below:

```
RuntimeError: tensorflow/lite/kernels/reshape.cc:69 num_input_elements != num_output_elements (25000 != 0)Node number 2 (RESHAPE) failed to prepare.
```

| TensorFlow 2.3.0 | TensorFlow 2.6.0 |
| --- | --- |
| ![model_2 3 0](https://user-images.githubusercontent.com/62459770/133984264-8e2149f3-df82-4b3b-9cfe-1a5b4b2dabf5.png) | ![model_2 6 0](https://user-images.githubusercontent.com/62459770/133984266-4aac1db5-99df-4d7c-b5cf-7bde923971a8.png) |

**Comment by sanatmpa1** [comment]
@ebraraktas,

Can you take a look at this [link](https://stackoverflow.com/questions/62386682/node-number-x-reshape-failed-to-prepare-tensor-resize-with-tflite-v2-2) which addresses similar issue? Thanks!

**Comment by ebraraktas** [comment]
@sanatmpa1 ,
I have found a workaround which allows me to convert model and run inference on `tensorflow>=2.4.0`. If you change this line:
```python
_ = model.predict(tf.random.normal((1, 100, 80)))
```
with this:
```python
model.build(input_shape=(None, None, 80))
```
you can convert and run without an error. 

I think this may give you an insight about fixing the bug.

**Comment by ebraraktas** [comment]
@sanatmpa1 ,

I don't consider this issue as fixed. My suggestion was just a workaround. And the bug still exists on latest stable version `2.6.0`. It would be better to close it when it is really fixed.

**Comment by MrSherish** [comment]
I've noticed very similar behaviour exists in TF 2.8 (moving from 2.5). In my case it was that one Conv2D was converted to Flex op for some reason. Using build() method instead of random inputs solved is as workaround. Still, this cannot be used for models with multiple inputs.

**Comment by pjpratik** [comment]
I was able to replicate this in TF 2.11. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/f298a769cbf052e25d6156e85cc62ce3/52064.ipynb). Thank you.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
