### ISSUE TITLE
Error using xla_sharding split on XLA_GPU

### ISSUE THREAD

**Issue by bhetherman-bbn** [tensorflow/tensorflow#52108]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: Unknown
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.0
- Python version: 3.6.9
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2/8.2
- GPU model and memory: 8x NVIDIA A100 (40 GB)

**Describe the current behavior**
I get an error when trying to use xla_sharding on an XLA_GPU device. The error is:

InvalidArgumentError: Trying to access resource _AnonymousVar584 (defined @ <ipython-input-27-90261c699d9c>:18) located in device /job:localhost/replica:0/task:0/device:XLA_GPU:0 from device /job:localhost/replica:0/task:0/device:GPU:0 [Op:__inference_test_xla_sharding_split_3074]

**Describe the expected behavior**
A tensor split into 8 parts across the 0 dimension.

**Standalone code to reproduce the issue**

```
import os
os.environ["XLA_FLAGS"] = "--xla_gpu_cuda_data_dir=/usr/local/cuda"
os.environ["TF_XLA_FLAGS"] = "--tf_xla_enable_xla_devices"

from tensorflow.compiler.xla.experimental.xla_sharding import xla_sharding
import numpy as np
import tensorflow as tf

tf.config.optimizer.set_jit(True)
print("Tensorflow version " + tf.__version__)

dim = 0
num_parts = 8

mirrored_strategy = tf.distribute.MirroredStrategy(
    devices=["device:XLA_GPU:0", "device:XLA_GPU:1", "device:XLA_GPU:2", "device:XLA_GPU:3", 
             "device:XLA_GPU:4", "device:XLA_GPU:5", "device:XLA_GPU:6", "device:XLA_GPU:7"
])

with mirrored_strategy.scope():
    var0 = tf.Variable([0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0])
    var0_split = tf.Variable([10.0, 11.0, 12.0, 13.0, 14.0, 15.0, 16.0, 17.0])

@tf.function(jit_compile=True)
def test_xla_sharding_split(x, y):
    with mirrored_strategy.scope():
        y.assign(xla_sharding.split(x, dim, num_parts, use_sharding_op=True))

test_xla_sharding_split(var0, var0_split)
```

**Other info / logs** Include any logs or source code that would be helpful to
attached tf_env.txt file

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The tensorflow.compiler.xla.experimental was moved to tensorflow.python.compiler.xla.experimental. Kindly refer to this [commit](https://github.com/tensorflow/tensorflow/commit/6ed611beb95124234d07053581205eb8f3a865a5).
**from tensorflow.python.compiler.xla.experimental import xla_sharding**

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
