### ISSUE TITLE
Add full parameter to SSIM

### ISSUE THREAD

**Issue by edumotya** [tensorflow/tensorflow#52150]
**System information**
- TensorFlow version (you are using): 2.6.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**

Currently, `tf.image.ssim` and also `tf.image.ssim_multiscale` return the mean ssim value of the images (across height and width dimensions), but returning the full ssim image would be highly useful for multiple applications (reconstruction autoencoders, etc).

**Will this change the current api? How?**

Yes, both functions (`tf.image.ssim` and `tf.image.ssim_multiscale`) will include a new parameter `full` and will return a tensor containing the full ssim image if `full` is True. In fact, this ressembles the api of [scikit-image structural_similarity](https://scikit-image.org/docs/dev/api/skimage.metrics.html?highlight=structural_similarity#skimage.metrics.structural_similarity).

**Any Other info.**

The implementation for `tf.image.ssim` is straightforward.  It consists of removing the `reduce_mean` operation if `full` is True, or conversely `reduce_mean` for no axes (`axes=[]`).

https://github.com/tensorflow/tensorflow/blob/bdc6a138403e8257841e8dff6d6b9322bb65053a/tensorflow/python/ops/image_ops_impl.py#L4227

I am not sure about the implementation for `tf.image.ssim_multiscale`, but it should be similar (or even the same).

**Comment by mohantym** [comment]
Hi @Saduf2019! 
Could you please look at this feature request!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
