### ISSUE TITLE
XLA dumps are not generated after setting XLA_FLAGS="--xla_dump_to=/some/path"

### ISSUE THREAD

**Issue by reza-amd** [tensorflow/tensorflow#52244]
I was running the unit test ```//tensorflow/compiler/tests:categorical_op_test_gpu``` and wanted to see the XLA dumps for this unit test. I set the --xla_dump_to to a correct path, but dump files were never generated (the setup is correct as for other tests, It can generate XLA dumps). 

I tried to investigate this issue  further and I found that [```detailed_logging```](https://github.com/tensorflow/tensorflow/blob/70ba657dcc0aed3593562931df16090218ab616b/tensorflow/compiler/jit/xla_compile_on_demand_op.cc#L138) has been hard coded to false in this location. This value is being used later on in [here](https://github.com/tensorflow/tensorflow/blob/70ba657dcc0aed3593562931df16090218ab616b/tensorflow/compiler/xla/service/dump.cc#L76) to reset the ```dump_to``` path. 

With this empty value for ```dump_to```, it will never generate the files even though ```xla_dump_to``` has been set. This behavior is contradictive to the XLA documentation described [here](https://www.tensorflow.org/xla)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
