### ISSUE TITLE
copy_to_device too slow

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#52310]
now the order of my dataset:
```TFRecordDataset->batch->map->copy_to_device```
map will output lots of small tensor, small tensor memcpyH2D is too slow. data by nsys:
![image](https://user-images.githubusercontent.com/33950866/136652365-9639e001-c0b2-4ce0-9d3f-e02e73139d2a.png)

```TFRecordDataset->batch->map->merge->copy_to_device->split``` maybe have a good performance.

I can contribute this part of the code if necessary

**Comment by zhaozheng09** [comment]
In same data H2D test:
small H2D:
![image](https://user-images.githubusercontent.com/33950866/136657774-d7cdece5-7771-47c1-b2c0-cde747cad8d4.png)
Big H2D:
![image](https://user-images.githubusercontent.com/33950866/136657794-c833ec8f-2695-48a1-abd3-b61fca1f250a.png)

H2D performance: BigH2D speed:18.8862 GB/s(13%) SmallH2D speed: 16.6752GB/s.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
