### ISSUE TITLE
TFlite model is too slow when Output Buffer is Direct().

### ISSUE THREAD

**Issue by filipeferreiradsr** [tensorflow/tensorflow#52323]
**System information**
- tensorflow-lite-gpu:2.7.0-rc0
- Are you willing to contribute it- Yes

**Describe the feature and the current behavior/state.**
I'm trying to use output buffer as```output =  ByteBuffer.allocateDirect(4 * LARGE_DIMENSIONS)
                .let {
                    it.order(ByteOrder.nativeOrder())
                    it.asFloatBuffer()
                }```
               with a buffer of large dimensions. The problem is that using direct allocation make the model run half of the velocity. I believe this because current tflite api is only able to use `copyTo`  instead of what happens with direct memory allocation in `setTo`.
Can you confirm that this is the expected behavior?

**Comment by tilakrayal** [comment]
@filipeferreiradsr ,
Can you please share a reproducible code that supports your statement so that the issue can be easily understood? Thanks!

**Comment by filipeferreiradsr** [comment]
```class InferencerTFLite internal constructor(
    private val modelConfig: ModelConfig,
    options: Interpreter.Options,
    modelBytes: ByteBuffer
) : Inferencer<Mat, FloatBuffer> {


    private val interpreter: Interpreter

    private val output: FloatBuffer

    private val input: FloatBuffer

    init {
        interpreter = Interpreter(modelBytes, options)

        input = ByteBuffer.allocateDirect(
            modelConfig.input.width * modelConfig.input.height * modelConfig.input.channels * modelConfig.input.channelSize
        )
            .let {
                it.order(ByteOrder.nativeOrder())
                it.asFloatBuffer()
            }

        output =
            ByteBuffer.allocateDirect(4 * modelConfig.output.height * modelConfig.output.width * modelConfig.output.channels)
                .let {
                    it.order(ByteOrder.nativeOrder())
                    it.asFloatBuffer()
                }

    }

    override fun inference(inputFrame: Mat): FloatBuffer {
        interpreter.run(
            createInput(inputFrame),
            createOutput()
        )
        return output
    }

    override fun close() {
        interpreter.close()
    }

    private fun createInput(inputFrame: Mat): FloatBuffer =
        input.apply {
            rewind()
            put(inputFrame.toFloatArray())
        }

    private fun createOutput(): FloatBuffer =
        output.apply {
            rewind()
        }

}```

If use 


```output = FloatBuffer.allocate(modelConfig.output.height * modelConfig.output.width * modelConfig.output.channels) ```

The model runs 2x the velocity

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
