### ISSUE TITLE
tensorflow/core/framework/op_kernel.cc:968 Invalid argument: Could not parse example input

### ISSUE THREAD

**Issue by anjiefang** [tensorflow/tensorflow#5234]
I'm trying to convert images (PNG) to `tf-records` files. When I read `tf-records` files. I saw lots of unreadable code on the screen. Please help to find the problem. I list my problems and code below:

I need to convert a sequence of images (10 PNGs) into a single `tf-records` file. I have several sequences of images and each sequence (10 PNGs) is in a folder. Here is the code I used to convert images to `tf-records`:

    import os, sys
    import tensorflow as tf
    import numpy as np
    from PIL import Image
    
    def _int64_feature(value):
        return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))
    
    def _bytes_feature(value):
        return tf.train.Feature(bytes_list=tf.train.BytesList(value=[value]))
    
    def read():
        # parent folder contains all sequence, each sequence (10 png) is in a sub-folder 
        parent_foler = sys.argv[1]
        for folder in os.listdir(parent_foler):
            images = read_images_from(parent_foler + '/' + folder)
            num_examples = len(images)
    
            print 'Number of images: ' + str(num_examples)
            outputFile = os.path.join(parent_foler, folder + '.tfrecords')
            writer = tf.python_io.TFRecordWriter(outputFile)
            fs = {}
            for index in range(num_examples):
                image_raw = images[index].tostring()
                image_name = 'move/' + str(index) + '/image/encoded'
                fs[image_name] = _bytes_feature(image_raw)
                print folder + ':' + image_name
            print 'Size of Features:' + str(len(fs))
            example = tf.train.Example(features=tf.train.Features(feature=fs))
            writer.write(example.SerializeToString())
            writer.close()
    
    def read_images_from(folder_name):
        images = []
        files_to_read = [folder_name + '/' + folder_name.split('/')[-1] + '_' + str(i + 1) + '.png' for i in range(10)]
        for filename in files_to_read:
            im = Image.open(filename)
            im = np.asarray(im, np.uint8)
            images.append(im)
        images = np.array(images)
        print'shape of images: ' + str(images.shape)
        return images
    
    if __name__ == "__main__":
        read()

Here is the code to read these `tf-records` files: (adapted from [this code][1])

    ORIGINAL_WIDTH = 2048
    ORIGINAL_HEIGHT = 1536
    COLOR_CHAN = 4
    
    def build_tfrecord_input(tf_folder):
    	filenames = [foldername + '/' + tf_file for tf_file in os.listdir(tf_folder)]
    	filename_queue = tf.train.string_input_producer(filenames, shuffle=True)
    	reader = tf.TFRecordReader()
    	_, serialized_example = reader.read(filename_queue)
    	image_seq = []
    
    	# FLAGS.sequence_length = 10
    	for i in range(FLAGS.sequence_length): 
    		image_name = 'move/' + str(i) + '/image/encoded'
    		features = {image_name: tf.FixedLenFeature([1], tf.string)}
    		features = tf.parse_single_example(serialized_example, features=features)
        	image = tf.decode_raw(features[image_name], tf.uint8)
        	image = tf.reshape(image, shape=[ORIGINAL_HEIGHT,ORIGINAL_WIDTH,COLOR_CHAN])
        	image.set_shape([ORIGINAL_HEIGHT, ORIGINAL_WIDTH, COLOR_CHAN])
        	
        	crop_size = min(ORIGINAL_HEIGHT, ORIGINAL_WIDTH)
        	image = tf.image.resize_image_with_crop_or_pad(image, crop_size, crop_size)
        	image = tf.reshape(image, [1, crop_size, crop_size, COLOR_CHAN])
        	image = tf.image.resize_bicubic(image, [IMG_HEIGHT, IMG_WIDTH])
        	image = tf.cast(image, tf.float32) / 255.0
        	image_seq.append(image)
    
        	image_seq = tf.concat(0, image_seq)
    
        return image_seq

  [1]: https://github.com/tensorflow/models/blob/master/video_prediction/prediction_input.py

When the training code runs to

    tf.train.start_queue_runners(sess)
    sess.run(tf.initialize_all_variables())

I saw unreadable code:

��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������~���~���|���|���~�������������������������������������������������������������������������������������������������������������������������������������������~���������������}�������������������������������������������������������������������������������������������������������������������������������������������������������~���}���}���~�������������������������������~���~���~���~���~���}��~|�~}{�~}{�~}{�~}{�~}{��~|���}���}���}���~���~���|���|���|���|���}���~���}���{�~}y�}|x�|{w�|{w�}|x�|{w�{zv�zyu�xws�wvr�vuq�utp�tso�tso�tso�utp�tso�utp�utp�utp�tso�tso�utp�utp�tso�utp�utp�vuq�wvr�xws�yxt�zyu�{zv�|{w�}|x�}|x�}|x�}|x�}|x�}|x�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}y�~}x��~y��~w��~w��~w��~w��~w��~w��~w��~w��~w��~W tensorflow/core/framework/op_kernel.cc:968] Invalid argument: Could not parse example input, value: '
���<
����
�move/7/image/encoded�����
����

Can anyone tell me which part of the code is wrong?

Thanks very much in advance,
Andy.

**Comment by drpngx** [comment]
Yes, it's a common error. See:
https://github.com/OliviaMG/xiaomeng/issues/1

**Comment by anjiefang** [comment]
@drpngx I didn't see a solution in OliviaMG/xiaomeng#1. Can you please specify it? Thanks a lot.

**Comment by drpngx** [comment]
See https://github.com/tensorflow/models/issues/579 and https://github.com/OliviaMG/xiaomeng/issues/1. The original code is posted in the link in the report, and febert posted the solution.

**Comment by greaber** [comment]
@drpngx, I'm not sure if this is the proper place to pursue this issue, but I am having the same problem, and after looking at the links you give, I am still confused.  Also, it does seem that there is a kind of bugginess here in that it does not give a sensible error message.  I am not even sure if the file being read is corrupt, but if so, TensorFlow should stop it being written in the first place.

**Comment by drpngx** [comment]
It's not a bug, it's just that the string is the raw image, being binary, is just printed as binary.

**Comment by anjiefang** [comment]
@drpngx Thanks. I understand that author offered the original code in  tensorflow/models#579.

But I saw some code examples very similar to the one I listed (e.g. [this](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/how_tos/reading_data/fully_connected_reader.py)). But It caused the parse problem.
So, in the code I listed above, Could you please point out which inappropriate code caused this parse problem? It helps me to avoid this problem in the future.

Btw, Tensorflow didn't raise a standard exception. It may need to be improved. 

Thanks a lot.

**Comment by drpngx** [comment]
OK, I can take a look later. Please include everything that is needed for a repro.

**Comment by anjiefang** [comment]
@drpngx  Thanks a lot! 

Here is the code: https://github.com/anjiefang/examplecodes_tensorflow.git

1. By running `./download_data.sh`, a sample data will be download and save in folder `data`
2. Convert images to `tf-records`:  `python convert_image.py ./data` (`tf-records` files will be store under `./data/`)
3. Train the model: `python prediction_train.py --data_dir ./data` (only the `tf-records` files will be read)

**Comment by greaber** [comment]
In my case, the writing code is:

```
assert cooked_data.shape == (60000,256,16)
flattened_data = cooked_data.flatten()
listized_data = flattened_data.tolist()
tf_example = tf.train.Example(
    features = tf.train.Features(
        feature = {
            'data': tf.train.Feature(float_list = tf.train.FloatList(value = listized_data)),
            'subject_id': tf.train.Feature(int64_list = tf.train.Int64List(value = [subject_id])),
            'example_id': tf.train.Feature(int64_list = tf.train.Int64List(value = [example_id])),
            'label': tf.train.Feature(float_list = tf.train.FloatList(value = [label]))
        }
    )
)
writer.write(tf_example.SerializeToString())
```

and the reading code is:

```
key, record_string = reader.read(queue)
features = tf.parse_single_example(
    record_string,
    features={
        'data': tf.FixedLenFeature([60000*256*16], tf.float32),
        'subject_id': tf.FixedLenFeature([1], tf.int64),
        'example_id': tf.FixedLenFeature([1], tf.int64),
        'label': tf.FixedLenFeature([1], tf.float32),
    }
)
```

Is the bug in this code?

Also, what is the rationale for using a non-self-describing format for tfrecords and also for using a non-standard format?  It seems to me hdf5 or a subset would be better.

**Comment by OliviaMG** [comment]
In my case, I have  problem same as anjiefang. Would you mind modify the code? @drpngx

**Comment by drpngx** [comment]
Will do.

**Comment by drpngx** [comment]
Wait... you're writing an `Example`, not `SequenceExample`?

**Comment by anjiefang** [comment]
@drpngx
One sequence contains 10 PNGs stored in a folder (e.g. ./data/backward_1). A single `tf example` records these 10 PNGs and is serializes as a `tf-records` file. Is it what you wanna know?
Thanks.

**Comment by drpngx** [comment]
OK, I'm not 100% sure exactly what you intended to do, use PIL or tensorflow. But you can't decode the image twice. I'm not familiar with image channels but I think the `COLOR_CHAN=3` is the proper index, numbered from zero. If you feed the raw png bytes (just `open(filename, 'r') as f; im = f.read()` in the `convert_image.py`, then you'll decode with tensorflow (`prediction_input.py` has decode_png). It should get you going.

We should be getting easier error messages on parse errors, stay tuned for that.

**Comment by drpngx** [comment]
BTW, you should not import modules directly. For instance, use `tf.app` instead of `from .. import app`.

**Comment by anjiefang** [comment]
@drpngx Either PIL or tensorflow is chosen in function `convert_to_image_per_folder` or `read_images_from` to decode PNGs string to `uint8` format. In function `read()`, `uint8` is converted to string again (`images[index].tostring()`) before serialization (`writer.write(example.SerializeToString())`). 

I used the way you suggested (`pen(filename, 'r') as f; im = f.read() `in `convert_image.py`). The parse problem is solved. Thanks a lot.
I think your given solution is equivalent as my previous code, i.e. images string is used for serialization (`writer.write(example.SerializeToString())` in `convert_image.py`). So I'm still not quite sure why my previous code had parse problem. :-(

> BTW, you should not import modules directly. For instance, use `tf.app` instead of `from .. import app.`

Thanks for your suggestion. We will improve our writing style in the future.


The updated code is committed to https://github.com/anjiefang/examplecodes_tensorflow.git @OliviaMG @greaber

**Comment by drpngx** [comment]
It might have been the `COLOR_CHAN`. Only indices `0` through `3` are allowed. It might have generated a parse error. Anyway, glad to see you figured it out!

**Comment by limian1761** [comment]
I have the same problem! It seems to come with numpy and tf.py_func!

`import tensorflow as tf
import numpy as np

myname = ".\mags\LJ001-0002.npy"   
print(np.load(myname))
    
def printsomthing(name):
    print(name)
    return np.load(name)

op = tf.py_func(printsomthing,[myname],[tf.float32])
session = tf.Session()
print(session.run(op))`





`018-03-10 20:03:24.722478: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\platform\cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2018-03-10 20:03:24.973617: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1212] Found device 0 with properties:
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.8095
pciBusID: 0000:01:00.0
totalMemory: 8.00GiB freeMemory: 6.59GiB
2018-03-10 20:03:24.977676: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-10 20:03:25.427432: I C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\common_runtime\gpu\gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6372 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
b'.\\mags\\LJ001-0002.npy'
2018-03-10 20:03:25.666649: W C:\tf_jenkins\workspace\rel-win\M\windows-gpu\PY\36\tensorflow\core\framework\op_kernel.cc:1190] Unknown: AttributeError: 'bytes' object has no attribute 'read'
Traceback (most recent call last):
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1361, in _do_call
    return fn(*args)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1340, in _run_fn
    target_list, status, run_metadata)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\framework\errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'bytes' object has no attribute 'read'
         [[Node: PyFunc = PyFunc[Tin=[DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](PyFunc/input_0)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/Dev2018/tacotron/tacotron/test.py", line 13, in <module>
    print(session.run(op))
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 905, in run
    run_metadata_ptr)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1355, in _do_run
    options, run_metadata)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\client\session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.UnknownError: AttributeError: 'bytes' object has no attribute 'read'
         [[Node: PyFunc = PyFunc[Tin=[DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](PyFunc/input_0)]]

Caused by op 'PyFunc', defined at:
  File "d:/Dev2018/tacotron/tacotron/test.py", line 11, in <module>
    op = tf.py_func(printsomthing,[myname],[tf.float32])
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 317, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 225, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\ops\gen_script_ops.py", line 95, in _py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 3271, in create_op
    op_def=op_def)
  File "C:\Users\lichao\Anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1650, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

UnknownError (see above for traceback): AttributeError: 'bytes' object has no attribute 'read'
         [[Node: PyFunc = PyFunc[Tin=[DT_STRING], Tout=[DT_FLOAT], token="pyfunc_0", _device="/job:localhost/replica:0/task:0/device:CPU:0"](PyFunc/input_0)]]`
