### ISSUE TITLE
logistic error in tf.split function

### ISSUE THREAD

**Issue by sjtusmartboy** [tensorflow/tensorflow#52526]
**tf nightly**

```
@tf.function
def test():
    nearest_color_neighbor = tf.constant([
     [0, 3],[0, 4],[0, 6],[0, 7],
     [1, 0],[1, 1],[1, 2],[1, 3],[1, 4],[1, 6],
     [2, 0],[2, 1],[2, 2],[2, 3],[2, 4],[2, 6],
     [3, 3],[3, 4]])

    unique, _, counts = tf.unique_with_counts(nearest_color_neighbor[:, 0])

    # ValueError: Cannot infer num from shape Tensor("UniqueWithCounts:2", shape=(None,), dtype=int32)
    splits = tf.split(nearest_color_neighbor[:, -1], counts)

    # TypeError: Expected int for argument 'num_split' not <tf.Tensor 'Shape:0' shape=(1,) dtype=int32>.
    splits = tf.split(nearest_color_neighbor[:, -1], counts, num=tf.shape(counts)) # error

    # output:
    # [<tf.Tensor: shape=(4,), dtype=int32, numpy=array([3, 4, 6, 7], dtype=int32)>,
    #  <tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 6], dtype=int32)>,
    #  <tf.Tensor: shape=(6,), dtype=int32, numpy=array([0, 1, 2, 3, 4, 6], dtype=int32)>,
    #  <tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4], dtype=int32)>]
    splits = tf.split(nearest_color_neighbor[:, -1], counts, num=4)
```

1. What's the type of `num` parameter for tf.split in https://tensorflow.google.cn/api_docs/python/tf/split?hl=en#args. Can it be of the type 'tensor' or just the 'int' type?
2. If the number of  split output can only be inferred from the context, I mean the **tf.shape(counts)** in the above example, then how to revise the code?

**Comment by sjtusmartboy** [comment]
Please do not tell me to remove the **@tf.function** because I have to use it in the dynamic **graph** . Why the **num** parameter for **tf.split**  could only be **int** instead of **tensor**?

**Comment by xuChenSJTU** [comment]
Hi, I have the same issue. Have you solved this? @sjtusmartboy

**Comment by sachinprasadhs** [comment]
Since you are running it in graph mode, try to provide the specific values or the values generated before graph mode.
You can try changing the below `tf.split` parameters to the allowed formats mentioned here.
`num_or_size_splits: Either an integer indicating the number of splits along axis or a 1-D integer Tensor or Python list containing the sizes of each output tensor along axis. If a scalar, then it must evenly divide value.shape[axis]; otherwise the sum of sizes along the split axis must match that of the value.`


`
num : Optional, used to specify the number of outputs when it cannot be inferred from the shape of size_splits.`

**Comment by victorconan** [comment]
Having the same issue. Can we reopen this issue?
