### ISSUE TITLE
[mlir-hlo]The following operations cannot be legalized: tf.VariableV2 

### ISSUE THREAD

**Issue by GipsonLeo** [tensorflow/tensorflow#52591]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.6.0
- Are you willing to contribute it (Yes/No): No, i want to but i don't know how to

**Describe the feature and the current behavior/state.**
feature: 
lower the op tf.VariableV2/tf.VarHandleOp/tf.ReadVariableOp/tf.AssignVariableOp of tf.dialect into mlir-hlo or other dialect. 

the current behavior: 
when i trying to do the translation as follow:
tf-opt --tf-to-hlo-pipeline target-func.mlir -o target-mhlo.mlir
i get the following error message:
target-func.mlir:2:3: error: The following operations cannot be legalized: tf.Assign (count: 1); tf.AssignAdd (count: 1); tf.VariableV2 (count: 1). These legalization failure(s) may be due to missing TF to HLO lowerings and/or unsupported attributes, etc.
  func @main() attributes {tf.entry_function = {control_outputs = "Variable/Assign,AssignAdd", inputs = "", outputs = ""}} {

**Will this change the current api? How?**
yes.
convertion should be add to the file [legalize_hlo_patterns.td](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/mlir/tensorflow/transforms/legalize_hlo_patterns.td) or else

**Who will benefit with this feature?**
MLIR users, all tensorflow IR users

**Any Other info.**
is there any feature similar completed ？

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
