### ISSUE TITLE
Golang support for tf.Variable

### ISSUE THREAD

**Issue by gonzojive** [tensorflow/tensorflow#52610]
**System information**
- TensorFlow version (you are using): unsure
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

I don't see any equivalent of "tf.Variable" in the Go API:
https://pkg.go.dev/github.com/tensorflow/tensorflow/tensorflow/go#section-readme
and
https://pkg.go.dev/github.com/tensorflow/tensorflow/tensorflow/go/op

**Will this change the current api? How?**
It will change the Go API.

**Who will benefit with this feature?**
Golang users who want to train models.

I have a model I am creating in Golang and then sending to Python to use the optimization API. I need tf.Variable objects to pass to the minimize function.

**Any Other info.**
I mistakenly filed this FR in an unofficial repo: https://github.com/galeone/tfgo/issues/62

**Comment by gowthamkpr** [comment]
@gonzojive Please take a look at this [explanation](https://github.com/galeone/tfgo/issues/62#issuecomment-949301702), where its clearly explained why there is no support to tf.variable in Golang.

**Comment by gonzojive** [comment]
> But it's not worth it IMO since the support for static-graph + session execution is enough for every application: just write the graph in Python (a function decorated with @tf.function) and export it as a SavedModel - the graph can contain any layer, with variables and so on. The exported graph can be loaded into tfgo and used, being the state (the value of the variables) managed by the TensorFlow runtime (the C library) and not by the bindings.

Thank you @galeone for the explanation. The feature request would allow building the graph with Go, not Python. Perhaps it is infeasible.

Is there an RPC API for graph building? Go could use that.

**Comment by cantonios** [comment]
> Is there an RPC API for graph building? Go could use that.

Not at the moment, but we may consider it - although it will be some time out.

**Comment by hdu-hh** [comment]
@gonzojive: You might be interested in my [experimental fork](https://github.com/hdu-hh/tensorflow), which focusses on reviving the golang binding also for training. It already supports [op.Variable](https://pkg.go.dev/github.com/hdu-hh/tensorflow/tensorflow/go/op#VariableV2), [tf.Func](https://pkg.go.dev/github.com/hdu-hh/tensorflow/tensorflow/go#Func), [op.While](https://pkg.go.dev/github.com/hdu-hh/tensorflow/tensorflow/go/op#While) and many more ops than upstream. See [some examples here](https://github.com/hdu-hh/tensorflow/blob/main/tensorflow/go/op/op_func_test.go).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
