### ISSUE TITLE
No SVDF ref kernel support with all 8 bit weights and state

### ISSUE THREAD

**Issue by mansnils** [tensorflow/tensorflow#52673]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source): 1180d389b41314e9715336b4b7b194140292d5c8

TFLM has support for this already:
https://github.com/tensorflow/tflite-micro/pull/506

If CMSIS-NN should add support for this it would be good to first have support in Tensorflow Lite, since CMSIS-NN has TFL as reference for its tests.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by mansnils** [comment]
This is not really needed anymore so closing it.
