### ISSUE TITLE
Addition of a new activation function: Mish in comps

### ISSUE THREAD

**Issue by MrinalTyagi** [tensorflow/tensorflow#52885]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.6.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.** Addition of a new activation function Mish.

**Will this change the current api? How?**Yes. Addition of a new activation function in the comps API. 

**Who will benefit with this feature?**As described in the following paper, Mish acts as a better activation function in comparison to LeakyReLU and outperforming it in some scenarios. Addition of this new activation functions for user to use in various models will be a huge advantage.
[Link to paper](https://arxiv.org/pdf/1908.08681.pdf)

**Any Other info.**

**Comment by sachinprasadhs** [comment]
As of now `Mish` is already available in [Tensorflow Addons](https://www.tensorflow.org/addons/api_docs/python/tfa/activations/mish), and you can still make use of the same for now.
Moving this to core could take some time and few factors like below.
`TensorFlow Addons is a repository of contributions that conform to well-established API patterns, but implement new functionality not available in core TensorFlow. TensorFlow natively supports a large number of operators, layers, metrics, losses, and optimizers. However, in a fast moving field like ML, there are many interesting new developments that cannot be integrated into core TensorFlow (because their broad applicability is not yet clear, or it is mostly used by a smaller subset of the community).`
