### ISSUE TITLE
Makefile downloads/ breaks ./configure

### ISSUE THREAD

**Issue by spiantino** [tensorflow/tensorflow#5310]
I'm rebuilding tf on Sierra and with CUDA 8.0 and Xcode 8.0 but ./configure fails with:

INFO: Starting clean (this may take a while). Consider using --expunge_async if the clean takes more than several minutes.
........
ERROR: /Users/serkan/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/BUILD:544:1: no such target '//external:gson': target 'gson' not declared in package 'external' defined by /Users/serkan/tensorflow/WORKSPACE and referenced by '//tensorflow/contrib/makefile/downloads/protobuf:protobuf_java_util'.
ERROR: /Users/serkan/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/BUILD:544:1: no such target '//external:gson': target 'gson' not declared in package 'external' defined by /Users/serkan/tensorflow/WORKSPACE and referenced by '//tensorflow/contrib/makefile/downloads/protobuf:protobuf_java_util'.
ERROR: /Users/serkan/tensorflow/tensorflow/contrib/makefile/downloads/protobuf/BUILD:544:1: no such target '//external:guava': target 'guava' not declared in package 'external' (did you mean 'java'?) defined by /Users/serkan/tensorflow/WORKSPACE and referenced by '//tensorflow/contrib/makefile/downloads/protobuf:protobuf_java_util'.
ERROR: Evaluation of query "deps((//tensorflow/... union @bazel_tools//tools/jdk:toolchain))" failed: errors were encountered while computing transitive closure.

perhaps bazel has changed something about how it handles dependencies?

**Comment by aselle** [comment]
Unfortunately we have not built or tested on Mac OS sierra yet. I will keep this open and let you know. We're not sure if it is a underlying Bazel not supporting MacOS sierra or if it is a tensorflow. @gunan, @jart any thoughts? Another issue is having Sierra issues too (#599).

**Comment by jart** [comment]
This is unrelated to Sierra. It's a flaw in the design of contrib/makefile. What most likely happened is you tried out the Makefile build system. Then you decided to go back to using Bazel. Because `bazel fetch //tensorflow/...` crawled the protobuf build files in the downloads directory left over by the makefile, and those BUILD files defined external dependencies we don't specify, things didn't work.

To work around this issue, `rm -rf tensorflow/contrib/makefile/downloads` before running `./configure`. The download_dependencies.sh script can always recreate that directory as needed.

I'm not sure if this is a bug we can fix, without a nontrivial redesigning contrib/makefile. I want to thank you for bringing this to our attention. But I'm leaning towards closing this issue for now. Although @martinwicke or @gunan may re-open it if they disagree.

**Comment by spiantino** [comment]
@jart removing the makefile downloads worked. Thank you!

**Comment by aselle** [comment]
Thanks @jart for the quick responsee

**Comment by jart** [comment]
Always happy to be of service. Enjoy TensorFlow.

**Comment by gunan** [comment]
@petewarden do you think we can easily fix this issue by modifying makefile?

**Comment by petewarden** [comment]
Thanks to some help from @jart I have a better understanding of what's happening here. It sounds like we could avoid this problem by removing the BUILD file as part of the download_dependencies script, and that would avoid this issue. I'll reopen this and take a look at it.

**Comment by aselle** [comment]
@petewarden, is this resolved?

**Comment by petewarden** [comment]
I think it is fixed now, @andrewharp put in a change recently to remove the BUILD files from the download folders. Closing.

**Comment by aselle** [comment]
Thanks!
