### ISSUE TITLE
SSIM index maps

### ISSUE THREAD

**Issue by MaggieLieu** [tensorflow/tensorflow#53115]
**System information**
- TensorFlow version (you are using): 2.7
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Currently tf.image.ssim() returns a global ssim value but it would be useful to have it return a non globally averaged value as per 
e.g. https://uk.mathworks.com/help/images/ref/ssim.html that would allow the making of ssim index maps

**Will this change the current api? How?**
-

**Who will benefit with this feature?**
anyone doing computer vision

**Any Other info.**

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you look into this feature request?

**Comment by sachinprasadhs** [comment]
Could you please elaborate your feature request and provide some code to show what is implemented and what changes in result you are expecting. Thanks!

**Comment by MaggieLieu** [comment]
Hi, 

Yes so the results I am expecting are like that shown here: https://uk.mathworks.com/help/images/ref/ssim.html for the local ssim map. So it's a SSIM value for each pixel rather than the mean. 

I believe that it comes in the function _ssim_per_channel() where the SSIM values are computed but then it returns the global mean rather than the pixel values. 
>  ssim_val = math_ops.reduce_mean(luminance * cs, axes)
>  cs = math_ops.reduce_mean(cs, axes)
>  return ssim_val, cs

And the ssim() function 
> ssim_per_channel, _ = _ssim_per_channel(img1, img2, max_val, filter_size,
                                            filter_sigma, k1, k2)
> return math_ops.reduce_mean(ssim_per_channel, [-1])

**Comment by rainwoodman** [comment]
Thanks MaggieLieu for tracking this down!

We can add a 'return_index_map=False/True' argument to ssim to maintain backward compatibility: when return_index_map is True, returns the index map; when return_idnex_map is False, return the reduced global value.

Since you have already identified where to change, would you mind contributing a PR?

PS: Here is a reference where it is explicitly described that the global ssim value is the mean of the local ssim value: https://medium.com/srm-mic/all-about-structural-similarity-index-ssim-theory-code-in-pytorch-6551b455541e .

**Comment by CohenAriel** [comment]
Hey, can I create a PR for this?

**Comment by rainwoodman** [comment]
That would be nice. Thanks!
