### ISSUE TITLE
GPU with OpenGL implementation for Android

### ISSUE THREAD

**Issue by LozariaVinok** [tensorflow/tensorflow#53209]
Hi! I am trying to implement processing from the camera using only GPU with OpenGL. I've built libtensorflowlite_gpu_gl.so

I've bound buffer like this:
`const void *model_data =
static_cast<void *>(env->GetDirectBufferAddress(model_buffer));
jlong model_size = env->GetDirectBufferCapacity(model_buffer);

TfLiteModel *model_ = TfLiteModelCreate(model_data, model_size);
TfLiteInterpreterOptions *options_ = TfLiteInterpreterOptionsCreate();
auto *options = new TfLiteGpuDelegateOptions ();
auto delegate_ = TfLiteGpuDelegateCreate(options);
TfLiteGpuDelegateBindBufferToTensor(delegate_, cam_ssbo_id, 0);
TfLiteInterpreterOptionsAddDelegate(options_, delegate_ );

interpreter_ = TfLiteInterpreterCreate(model_, options_);

TfLiteStatus status = TfLiteInterpreterAllocateTensors(interpreter_);`
and then on a new frame, I call
TfLiteStatus status = TfLiteInterpreterInvoke(interpreter_);
It is working. I am receiving the expected result. But it seems like the invoke is working on CPU instead of GPU. It also freezes the main thread (I am calling all of these methods in a separate thread), and the processing is too slow.
I have tried processing on GPU for my model using standard GPU Delegate it was working fine and two times faster. I was expecting that TfLiteInterpreterInvoke(interpreter_) whould work around the same time for both configurations. Can you help me to understand how I should implement processing on GPU correctly?

**Comment by sushreebarsa** [comment]
@LozariaVinok Could you please refer to the [TF Lite on GPU](https://www.tensorflow.org/lite/performance/gpu_advanced) and let us know if it helps?Thank you!

**Comment by LozariaVinok** [comment]
I've read these docs. There is no info about using ssbo in input or output.
I've also used samples from #26297 . It helped me to get current results. But maybe this issue is too old.  
It would be helpful if you can show me the way how to use the current library to process data on GPU from a camera without copying it. Or point me what I could do wrong in my sample

**Comment by impjdi** [comment]
@srjoglekar246 Do we have code pointers for zero copy?

**Comment by srjoglekar246** [comment]
broader support for Zero copy interop on the TFLite side is still being designed, and will likely land in Q1 next year.
@impjdi can they use the older GPU delegate surface for this feature? I suppose that one doesnt have a Java interface? :-/

**Comment by impjdi** [comment]
Yeah, no Java interface that I'm aware of.

**Comment by LozariaVinok** [comment]
I use tflite in NDK. So, I think I don't need a Java interface, right?

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
