### ISSUE TITLE
STFT --> inverse_STFT not reconstructing the original signal when using no window

### ISSUE THREAD

**Issue by giamic** [tensorflow/tensorflow#53205]
Tensorflow is not reconstructing the original signal when applying the STFT followed by the inverse STFT when using no window. The problems arise when the frames of the STFT overlap: It seems like every frame contributes with a weight of 1 regardless of the number of overlapping frames `N = frame_size / frame_step`. As a result, the central part of the signal is `N` times larger than the original. Here is a minimal code to reproduce the error:

```python
import matplotlib.pyplot as plt
import numpy as np
import tensorflow as tf

size = 2048
frame_length = 512
frame_step = 128
waveform = np.sin(np.arange(size) * 1 / 100)

stft = tf.signal.stft(waveform, frame_length, frame_step, window_fn=None)
inverse_stft = tf.signal.inverse_stft(stft, frame_length, frame_step, window_fn=None)

plt.plot(waveform)
plt.plot(inverse_stft)
plt.show()
plt.clf()
```
Broken stft --> istft applied to sinusoidal signal: 
![](https://i.stack.imgur.com/BMjqX.png)

Notice that I'm using no window. If I put the Hann window, the central part works well but the borders are smoothly going to zero, a related but surprisingly different bug that is already documented here: #36616. The implementation of scipy works well under all circumstances.

I'm using Tensorflow 2.6.0 installed with tensorflow-macos on an Apple M1 MacBookPro.

**Comment by mohantym** [comment]
Hi @sanatmpa1! Could you please look at this issue. It's replicating in Tf 2.5 ,2.6 and 2.7 . Attaching [Gist ](https://colab.research.google.com/gist/mohantym/7a700af1a33bc4800663adc80c71f5ae/github_53205.ipynb)for reference.

**Comment by mohantym** [comment]
Hi @giamic ! Work around for this problem is to reduce frame_step to 8. Attaching resolved [gist](https://colab.sandbox.google.com/gist/mohantym/e9c44b14c406d39607c538b26cefd8a2/github_53205.ipynb#scrollTo=0oCflt-dIKa4) for reference. Thanks!

**Comment by RosameliaCarioni** [comment]
I am currently having the same issue when trying to reconstruct an initial signal. Can someone tell me what can I do, please? I can provide the code or what I am doing if there's someone that can have a look at it (basically the same as giamic tho but with my own signal .wav signal). 
Thank you

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
