### ISSUE TITLE
How to remove NaN in tensor by specific values?

### ISSUE THREAD

**Issue by leelew** [tensorflow/tensorflow#53228]
Hi, I have two tensor, `a` and `b`, which have the same shape. I want to replace NaN value in `a` by corresponding value in `b`. I find `tf.tensor_scatter_nd_update` could replace value for tensor, but I don't know how to generate `indices` where to update. So how can I remove NaN in tensor?

Thanks!

**Comment by hxyue1** [comment]
Hi,

`tf.where(tf.math.is_nan(a), b, a)` will probably do the trick.

How does it work?

`tf.math.is_nan(a)` returns a boolean array with the same shape as `a` with each element being `True` if the corresponding element in `a` is NaN and `False` otherwise. 

This is then passed to `tf.where()` which replaces each `True` value in the `is_nan` result with the corresponding value in `b` and if not NaN, leaves it as the original value in `a`.

A simple demonstration:

```
import tensorflow as tf
import numpy as np

#Some dummy tensors
a = tf.convert_to_tensor([[1., 2.], [3., np.nan]])
b = tf.convert_to_tensor([[1., 2.], [3., 4.]])

#NaNs in a replaced with values in b
c = tf.where(tf.math.is_nan(a), b, a)
```

Hope this helps!

**Comment by leelew** [comment]
Thanks! Your suggestion works perfectly!

**Comment by tilakrayal** [comment]
@leelew ,
Also please take a look at this issues and link [1](https://www.tensorflow.org/api_docs/python/tf/tensor_scatter_nd_update) [2](https://stackoverflow.com/questions/55652981/tensorflow-2-0-how-to-update-tensors) and [3](https://stackoverflow.com/questions/67362672/tensorflow-2-how-to-directly-update-elements-in-tf-variable-x-at-indices) which helps to provide the more information.Thanks

**Comment by tilakrayal** [comment]
@leelew ,
Please feel free to move this issue to closed status as the issue has resolved.Thanks!
