### ISSUE TITLE
Memoization

### ISSUE THREAD

**Issue by egpbos** [tensorflow/tensorflow#5323]
I have a particle physics optimization problem where my graph contains a large subgraph that only needs to be calculated once every couple of iterations. The code I'm currently using for this uses memoization to create a significant increase in performance for these types of problems. I've been looking into porting the graph calculation part of my current code to TensorFlow, but it seems like the absence of memoization might become a show-stopper.

Are there plans to include support for memoization? If not, do you think this would be a good addition and do you have ideas on how to do this? I would be willing to contribute, if possible.

Ideally, one would be able to activate memoization per node/operation, so as to avoid performance hits due to overhead in nodes that need to be recalculated every time (i.e. that receive different arguments every time).

Perhaps this could be implemented using partial_run (#672), but I suspect a native c++ implementation would be vastly superior.

**Comment by aselle** [comment]
@vrv might have more insight, but I have a few things.

1. This is a great question to ask on StackOverflow, because you can ask "how do people deal with caching data and/or memoizing? do you use explicit memoization?"
2. A concrete example of what kind of data you are memoizing might make it clearer exactly what you want.
3. Dataflow and traditional memoization are pretty much at odds in the current architecture, since you really have no way to have a function that causes upstream dependencies to run. You need to be able to schedule a static computation. Perhaps you mean memoization in the sense of if you see the same input, you have an internal cache per node.

**Comment by vrv** [comment]
I think using partial_run, or perhaps saving your subgraph output state in a variable to be consumed downstream is probably the best ways to go about doing this for now.

Note that partial_run is also supported at the C++ interface, though I'd like to see proof that it would be 'superior'. :)

**Comment by egpbos** [comment]
@aselle 
> memoization in the sense of if you see the same input, you have an internal cache per node.

Yes, that's what I mean. It seems to me that implementing such functionality would be a lot more expensive when done at the Python level than at the C++ level.

> Note that partial_run is also supported at the C++ interface, though I'd like to see proof that it would be 'superior'. :)

See above, by "c++ implementation" I meant the implementation of memoization in C++ vs in Python, not the partial_run implementation :)

**Comment by vrv** [comment]
partial_run's C++/python interface does do most of its implementation in C++, fortunately.

**Comment by aselle** [comment]
I'm closing this for now, since there really isn't a concrete feature request here. If you want to formalize or suggest a particular design, we are happy to reopen and discuss.
