### ISSUE TITLE
MLIR backend for XLA

### ISSUE THREAD

**Issue by whatdhack** [tensorflow/tensorflow#53301]
Hello,  may I ask  a few simple questions on XLA .

1. Is there an open sourced XLA MLIR backend that  one can try "out of the box" ?
2. Is there a way to enable/disable various optimizations  that are used in XLA ?
3. What is the best way to figure out  what optimizations are available in XLA ?

**Comment by sushreebarsa** [comment]
@whatdhack Could you please have a look at the [XLA link ](https://www.tensorflow.org/xla) and let us know if it helps?Thanks!

**Comment by whatdhack** [comment]
@sushreebarsa ,  that link is very cursory and does not address any of the questions above.  Hence I opened the issue .

**Comment by sachinprasadhs** [comment]
You can refer the Tensorflow code for [XLA](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/compiler/xla) and implementation code for [MLIR-HLO](https://github.com/tensorflow/mlir-hlo).
For information regarding XLA MLIR optimization detail you can refer [this](https://www.tensorflow.org/mlir/xla_gpu_codegen) documentation. Let us know if this helps you. Thanks!

**Comment by whatdhack** [comment]
Thanks.   The link[ MLIR CodeGen for XLA ](https://www.tensorflow.org/mlir/xla_gpu_codegen)  looks like is sort of a roadmap which is yet to be implemented.   Would appreciate if you could clarify the current high level XLA  flow and the  future flow with MLIR.   AFAIK,  the current flow is as follows. Can you  please check and make any correction and enhancement ? 

Grappler (pbb  ?) -> XLA HLO (independent) - XLA HLO ( target dependent) -> LLVM IR ->  PTX -> thunk 

Along the same line,  what would the MLIR  based flow look like ?

Also, none of the documentation seems to mention any flag to  enable/disable category of optimizations. Is it possible to enable/disable certain category of optimizations ?

**Comment by whatdhack** [comment]
@sachinprasadhs , any update on this ?

**Comment by whatdhack** [comment]
Anyone here ?

**Comment by bhack** [comment]
> The link[ MLIR CodeGen for XLA ](https://www.tensorflow.org/mlir/xla_gpu_codegen)looks like is sort of a roadmap which is yet to be implemented.

It would be also nice to understand where we are now in implementing this roadmap.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
