### ISSUE TITLE
cannot get high precision arithmetic to work

### ISSUE THREAD

**Issue by ziofil** [tensorflow/tensorflow#53306]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): MacOS 12.0.1
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.6.2
- Python version: 3.9.7
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Describe the current behavior**
High precision when casting with numpy, but low precision when casting with tf:
```python
>>> import numpy as np; import tensorflow as tf
>>> tf.math.sin(np.array(np.pi, dtype=np.float64))
<tf.Tensor: shape=(), dtype=float64, numpy=1.2246467991473532e-16>

>>> tf.math.sin(tf.cast(np.pi, dtype=tf.float64))
<tf.Tensor: shape=(), dtype=float64, numpy=-8.742278000372475e-08>  # why low precision?

>>> tf.math.sin(tf.cast(3.141592653589793, dtype=tf.float64))
<tf.Tensor: shape=(), dtype=float64, numpy=-8.742278000372475e-08>  # how to get high precision??
```

**Describe the expected behavior**
I would expect `tf.cast(np.pi, dtype=tf.float64)` to behave like a float64 value when passed to functions.

- Do you want to contribute a PR? (yes/no): no

**Standalone code to reproduce the issue**
see above

**Comment by chunduriv** [comment]
@sachinprasadhs, I was able to reproduce the issue on colab using TF 2.7 and TF-nightly(2.8.0-dev20211207). Please find the [gist here](https://colab.research.google.com/gist/chunduriv/c5748c0e1934a18ec9aac38daf131d30/53306.ipynb) for reference.Thanks!

**Comment by sachinprasadhs** [comment]
The reason is while doing the `tf.cast` it does the approximation because you are converting `tf.float32` to `tf.float64` because of this it changes the value of `pi` from `3.141592653589793 `to `3.1415927410125732` and hence the change in precision.
To avoid that you can feed the` tf.float64` variable by providing `tf.constant` value as below.
`tf.math.sin(tf.cast(tf.constant(np.pi, dtype=tf.float64),dtype=tf.float64))`

Please find the gist [here](https://colab.research.google.com/gist/sachinprasadhs/e4acc8151448ba264f8fbff1804dcf24/53306.ipynb#scrollTo=-Y0xzKd9_AZi) for detailed reference, Thanks!
