### ISSUE TITLE
[TFLite] Conversion support for 3D operators with channels first data format

### ISSUE THREAD

**Issue by Tessil** [tensorflow/tensorflow#53315]
Hello,

TensorFlow Lite currently supports the conversion of 2D operators like `tf.keras.layers.Conv2D`, `tf.keras.layers.MaxPool2D`, ... with `data_format="channels_first"` through the insertion of `TRANSPOSE` operators as the TFLite kernels only support the channels last format.

Would it be possible to add something similar for 3D operators like  `tf.keras.layers.Conv3D`, `tf.keras.layers.MaxPool3D`, ... that use `data_format="channels_first"`?

Example script:
```python
import tensorflow as tf

input = tf.keras.Input(shape=[1, 3, 8, 8, 8])
output = tf.keras.layers.Conv3D(
    filters=12,
    kernel_size=(2, 2, 2),
    data_format="channels_first",
    use_bias=False,
)(input)
model = tf.keras.Model(input, output)


converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()
```

Conversion error with TF 2.7.0 (note that setting `data_format="channels_last"` works):
```
error: 'tf.Conv3D' op is neither a custom op nor a flex op
error: failed while converting: 'main':
Some ops are not supported by the native TFLite runtime, you can enable TF kernels fallback using TF Select. See instructions: https://www.tensorflow.org/lite/guide/ops_select
TF Select ops: Conv3D
Details:
        tf.Conv3D(tensor<?x3x8x8x8xf32>, tensor<2x2x2x3x12xf32>) -> (tensor<?x12x7x7x7xf32>) : {data_format = "NCDHW", device = "", dilations = [1, 1, 1, 1, 1], padding = "VALID", strides = [1, 1, 1, 1, 1]}
```

Thibaut

**Comment by chunduriv** [comment]
@sachinprasadhs, I was able to reproduce the issue on Colab using TF 2.7 and TF-nightly(2.8.0-dev20211208). Please find the [gist here](https://colab.research.google.com/gist/chunduriv/f3f4b6b4f958bf8034ce214062a786e6/untitled68.ipynb) for reference.Thanks!

**Comment by sachinprasadhs** [comment]
Did you try with the `channels_last` `data_format` in `tf.keras.layers.Conv3D`, let me know if you are facing any issues with this conversion.

**Comment by sachinprasadhs** [comment]
Right now Conv3D with data_format="channel_first" operations are not in a listed TFLite operations for conversion. As you have specified data_format = = "channel_last" is working and you can use the same.

**Comment by Tessil** [comment]
@sachinprasadhs Yes, using `channels_last` works fine for 3D operators. It's mainly a feature request to have feature-parity with 2D operators as supporting `channels_first` can be useful when converting models from one framework to another.

Would it be possible to re-open the issue as with the end of the year holidays I was late to respond and the issue has been closed as stale? Thanks!

**Comment by FrozenWolf-Cyber** [comment]
Any update regarding this issue?

**Comment by mohantym** [comment]
Hi @Tessil !
This issue got resolved after following Select Ops syntax.
Attached [gist](https://colab.sandbox.google.com/gist/mohantym/f304c48a7dcfb1de6fb534c86ebbcd9f/git_53315.ipynb) for reference.
Thank you!

**Comment by Tessil** [comment]
Thank you for your reply though we are looking to have models with TensorFlow Lite builtin operators in the graph without any TensorFlow ones.

**Comment by mohantym** [comment]
Ok @Tessil !
Thanks for the clarification.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.

**Comment by Tessil** [comment]
The issue is still present with the latest version of TensorFlow.

**Comment by pkgoogle** [comment]
Hi @Tessil ,

Thanks for raising this issue. Are you aware of [AI-Edge-Torch](https://developers.googleblog.com/en/ai-edge-torch-high-performance-inference-of-pytorch-models-on-mobile-devices/)? As we believe this issue is better supported by and more relevant to AI-Edge-Torch we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/ai-edge-torch/issues/392).

Let us know if you have any questions. Thanks.
