### ISSUE TITLE
Unable to find version specific documentation for building TFLite

### ISSUE THREAD

**Issue by bhpatray** [tensorflow/tensorflow#53312]
The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:

https://www.tensorflow.org/lite/guide/

## Description of issue (what needs changing):
Unable to find version-specific documentation to build TFLite building.

### Clear description
For version 2.4.1, There used to be documentation which is based on Makefile present in tensorflow/lite/tools/make
But this became redundant in the current release.
Bazel and cmake build process were introduced later.
Bazel build on host to generate TFLite shared library was initially kept and removed from the site.

For example, why should someone use this method? How is it useful?
Need version specific documentation to build TFLite library.
It will be helpful when users are using previous releases and help them in building TFLite library.

### Correct links
https://www.tensorflow.org/lite/guide/
https://github.com/tensorflow/tensorflow

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
