### ISSUE TITLE
failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error

### ISSUE THREAD

**Issue by NeilChangYanpeng** [tensorflow/tensorflow#53341]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): source
- TensorFlow version: 1.14.0
- Python version: 3.6.13
- Installed using virtualenv? pip? conda?: pip
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): 7.5.0
- CUDA/cuDNN version: 10.0.130/7.4.2
- GPU model and memory: GTX 2080Ti  12GB
 Output of nvidia-smi：
`ubuntu@init:~$ nvidia-smi
Tue Dec  7 10:01:07 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 470.86       Driver Version: 470.86       CUDA Version: 11.4     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  Off  | 00000000:02:00.0 Off |                  N/A |
| 30%   29C    P8    16W / 250W |     41MiB / 11016MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
`

**Describe the problem**

After I installed tensorflow-gpu using pip，I tested it in terminal，but it seems gpu is not available

`(tfgpu114) ubuntu@init:~$ python
Python 3.6.13 |Anaconda, Inc.| (default, Jun  4 2021, 14:25:59) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow
>>> tensorflow.test.is_gpu_available()
2021-12-07 09:01:22.849145: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2021-12-07 09:01:22.888771: I tensorflow/stream_executor/platform/default/dso_loader.cc:42] Successfully opened dynamic library libcuda.so.1
2021-12-07 09:01:22.949108: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error
2021-12-07 09:01:22.949204: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: init
2021-12-07 09:01:22.949225: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: init
2021-12-07 09:01:22.949349: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:200] libcuda reported version is: 470.86.0
2021-12-07 09:01:22.949407: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:204] kernel reported version is: 470.86.0
2021-12-07 09:01:22.949428: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:310] kernel version seems to match DSO: 470.86.0
2021-12-07 09:01:22.960938: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2500025000 Hz
2021-12-07 09:01:22.964071: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x55ed09dbc440 executing computations on platform Host. Devices:
2021-12-07 09:01:22.964121: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): <undefined>, <undefined>
False
>>> 
`

Does anyone meet this condition，please tell me a solution，thank you！

**Comment by mohantym** [comment]
Hi @NeilChangYanpeng ! 
It seems you are using older versions(1.x versions) of Tensorflow which is not supported any more. Could you try again in latest version 2.7? Attaching relevant[ thread](https://stackoverflow.com/questions/47068709/your-cpu-supports-instructions-that-this-tensorflow-binary-was-not-compiled-to-u) for reference. Thanks!

**Comment by NeilChangYanpeng** [comment]
> 

thank you，I will have a try on latest version

**Comment by NeilChangYanpeng** [comment]
I created a new conda env with python 3.7 and installed tensorflow-gpu 2.4.1 using conda method, but still same error:
![812e733f8b8369bc677f50e3072b5ee](https://user-images.githubusercontent.com/41663460/145041073-938f9302-841e-43ed-a767-db1cbe713f48.png)

**Comment by mohantym** [comment]
Ok @NeilChangYanpeng ! Are you using Cuda 11 and CuDNN 8.0  for TF  2.4 .Please following instructions from [here](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) properly setting CUDA installation.  Attaching relevant threads for reference . [link1](https://github.com/tensorflow/tensorflow/issues/32623),[link2](https://www.tensorflow.org/install/gpu#install_cuda_with_apt).Thanks!

**Comment by NeilChangYanpeng** [comment]
> Ok @NeilChangYanpeng ! Are you using Cuda 11 and CuDNN 8.0 for TF 2.4 .Please following instructions from [here](https://docs.nvidia.com/cuda/cuda-installation-guide-linux/index.html) properly setting CUDA installation. Attaching relevant threads for reference . [link1](https://github.com/tensorflow/tensorflow/issues/32623),[link2](https://www.tensorflow.org/install/gpu#install_cuda_with_apt).Thanks!

First of all, when using conda to install tensorflow-gpu instead of pip, the conda will install cuda and cudnn properly, so you dont have to install it yourself.
second,I was using the container created by lxc  at beginning, but  now I changed to the host ,there is no problem on host, (tensorflow-gpu 1.14.0 created using 'conda install tensorflow-gpu=1.14.0' )
Thank you so much!

**Comment by mohantym** [comment]
Ok @NeilChangYanpeng! Thanks for confirmation. Closing this issue at it seems to be resolved.

**Comment by rebmcr** [comment]
For anyone else finding this issue from a search engine:

When running CUDA inside an lxc container, you are likely passing various nvidia devices from the host's `/dev/` into the container's `/dev/`. These devices (particularly '/dev/nvidia-uvm`) must be initialised properly BEFORE starting the lxc container.

The way I do this is to have the full driver+cuda+cudnn+tensorflow stack installed on the host, and make sure I run these commands while the lxc container(s) are not running:
`$ python3`
`>>> import tensorflow as tf`
`>>> print("Num GPUs Available: ", len(tf.config.list_physical_devices('GPU')))`

This should print `1`, then after starting the lxc container(s) you will no longer encounter the `failed call to cuInit: CUDA_ERROR_UNKNOWN: unknown error` message!

**Comment by arunanshub** [comment]
For anyone facing this problem on Linux:

1. Enable the following services in `systemd`:

   - `nvidia-suspend.service`
   - `nvidia-resume.service`
   - `nvidia-hibernate.service`

   Enable via `sudo systemctl enable <service name>`.

2. Create a file named `/etc/modprobe.d/nvidia-suspend.conf`.

3. Add the following line to the file:

   ```modconf
   options nvidia NVreg_PreserveVideoMemoryAllocations=1
   ```

4. Reboot

5. **Optional:** If that does not help, execute these.

   ```bash
   sudo modprobe -r nvidia_uvm # or: sudo rmmod nvidia_uvm
   sudo modprobe nvidia_uvm
   ```

This shall prevent the `cuInit: CUDA_ERROR_UNKNOWN: unknown error`. [Read more about the problem here.][guide]

[guide]: https://download.nvidia.com/XFree86/Linux-x86_64/510.39.01/README/powermanagement.html

**Comment by aymenabid-lab** [comment]
If we have
`W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT`

WE should install **`pip install nvidia-tensorrt`**
And all we be right

`2024-07-05 11:05:09.855365: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-07-05 11:05:09.881372: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-07-05 11:05:09.881397: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-07-05 11:05:09.882065: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-07-05 11:05:09.886101: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-07-05 11:05:10.340700: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
`

**Comment by Tse-Lu** [comment]
> For anyone facing this problem on Linux:对于在 Linux 上遇到此问题的人：
> 
> 1. Enable the following services in `systemd`:在 `systemd` 中启用以下服务：
>    
>    * `nvidia-suspend.service`
>    * `nvidia-resume.service`
>    * `nvidia-hibernate.service`
>    
>    Enable via `sudo systemctl enable <service name>`.  通过 `sudo systemctl enable <service name>` 启用。
> 2. Create a file named `/etc/modprobe.d/nvidia-suspend.conf`.创建一个名为 `/etc/modprobe.d/nvidia-suspend.conf` 的文件。
> 3. Add the following line to the file:将以下行添加到文件中：
>    ```
>    options nvidia NVreg_PreserveVideoMemoryAllocations=1
>    ```
> 4. Reboot  重启
> 5. **Optional:** If that does not help, execute these.可选：如果这不起作用，请执行这些操作。
>    sudo modprobe -r nvidia_uvm # or: sudo rmmod nvidia_uvm
>    sudo modprobe nvidia_uvm
> 
> This shall prevent the `cuInit: CUDA_ERROR_UNKNOWN: unknown error`. [Read more about the problem here.](https://download.nvidia.com/XFree86/Linux-x86_64/510.39.01/README/powermanagement.html)这将防止 `cuInit: CUDA_ERROR_UNKNOWN: unknown error` 。有关此问题的更多信息，请在此处阅读。

It does work. My device has both Windows11 and Ubuntu20.02.
However, when I run this code on Ubuntu20.04, the choice of Windows is lost in the bios.
Is there anyone who can help me ?
