### ISSUE TITLE
Tutorial for autoencoder might be applying denoising to the wrong input data

### ISSUE THREAD

**Issue by dnlmlr** [tensorflow/tensorflow#53357]
## URL(s) with the issue:

https://www.tensorflow.org/tutorials/generative/autoencoder#second_example_image_denoising

## Description of issue (what needs changing):

The model was trained to remove noise using the `x_train_noisy` as input and `x_train` as target output.
Later when demonstrating the denoising capabilities `x_test` is used as input, which is the original (**not noisy**) test data. In the plot it is also presented as `original + noise` (noisy images) vs the reconstruction [*from the noisy images*]. 

If I am not missing something, right now the autoencoder is used to denoise the already **not noisy** images instead of denoising the **noisy** images which are also shown as a comparison besides the reconstructed images.

### Clear description

Use the autoencoder to denoise the actually noisy images, in the same way as it is presented below and the same way as the model is trained and validated before.

Change this
```python
encoded_imgs = autoencoder.encoder(x_test).numpy()
decoded_imgs = autoencoder.decoder(encoded_imgs).numpy()
```
to this
```python
encoded_imgs = autoencoder.encoder(x_test_noisy).numpy()
decoded_imgs = autoencoder.decoder(encoded_imgs).numpy()
```

**Comment by Aman2909** [comment]
Yes, you are correct.
The input to the encoder should be x_test_noisy instead of x_test.

**Comment by sushreebarsa** [comment]
@dnlmlr Sorry for the late response!
The description in the tutorial is correct since it is unsupervised learning so we require only input to learn patterns from it.Here we define two things one is **Encoder** which compresses the image that means conversion to a smaller dimension and second one is **Decoder** which takes the small image and reconstruct it back. In this case we call the  fit function to train the model and we use arguments (x_train as input and x_train as output ).The input and output will be the same as the entire role of the model is that it has to construct the same image as input . 

In the below code we are passing some test images(x_test) to see how it works.We are passing it to the encoder and saving it as encoded images (encoded_imgs) then we take these encoded images and pass it to the decoder (decoded_imgs) again.
`encoded_imgs = autoencoder.encoder(x_test).numpy()  
`
`decoded_imgs = autoencoder.decoder(encoded_imgs).numpy()`

I am able to run one example of autoencoder successfully  using TF v2.7.0 on colab using another data set,Please refer to this [gist](https://colab.research.google.com/gist/sushreebarsa/c99d303e689e72e8f00113776e668b95/autoencoder.ipynb) .
Thank you!

**Comment by dnlmlr** [comment]
I think there is a misunderstanding here. I was talking specifically about the **denoising** (second) example as you can see in the title and also the issue text. 
You seem to be talking about the first example instead, which just tries to reconstruct the input image.

Also I **never said** that any of the examples **didn't work**, I just said that I think the wrong input images were used in the demonstration. 
The second example was trained to remove noise from the given images, but the demonstration used the **not** noisy images as input. So the output of course seems to be correct if you run it, because it is just denoising images that are not noisy to begin with. 

But I already wrote all that in the initial issue, so I would ask you to please read it again, especially the **Clear description** part where you can see the current code and what I would assume to be the correct demonstration code. You can see that I replaced the `x_test` with `x_test_noisy` which are the noisy images.

**Comment by sushreebarsa** [comment]
@dnlmlr Thank you for the quick response!
Would you like to submit a PR to fix this issue else I can submit a PR on your behalf ?

**Comment by dnlmlr** [comment]
Feel free to submit the PR on my behalf. The change should literally be only 6 characters

**Comment by sushreebarsa** [comment]
@dnlmlr This issue will be closed once the [PR](https://github.com/tensorflow/docs/pull/1986) is merged.Thanks!

**Comment by 8bitmp3** [comment]
PR merged, thank you @dnlmlr @sushreebarsa !
