### ISSUE TITLE
 bazel-genfiles/ and *.pb.h  not been generated  with bazel-building tensorflow2.4.1 from source

### ISSUE THREAD

**Issue by no-define** [tensorflow/tensorflow#53381]
**System information**
- OS Platform and Distribution ( Linux Ubuntu 18.04):
- TensorFlow installed from (source)
- TensorFlow version:        Tags v2.4.1
- Python version:      Python 3.7.6
- Installed using virtualenv? pip? conda?:       conda
- Bazel version (if compiling from source):        have tried bazel 3.4.0 、 bazel 3.1.0
- GCC/Compiler version (if compiling from source):  gcc (GCC) 7.4.0
- CUDA/cuDNN version:        cuda_11.1 , cudnn 8.0.5
- GPU model and memory:   rtx3060
- nvidia-driver version:     460.91
- eigen  version :      eigen-3.3.90

I want to build  tensorflow c++ api with bazel, no errors were reported during  bazel-build process .
the command I used: `bazel build --config=opt --config=cuda //tensorflow:libtensorflow_cc.so`

however,while compiling a C++ program, I got the following error:
`fatal error: tensorflow/core/framework/device_attributes.pb.h: No such file or directory
  #include "tensorflow/core/framework/device_attributes.pb.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
`  

After that I  checked the  tensorflow/core/framework  folder and **found no *.pb.h  files in it ,only   some .proto files,**(etc. device_attributes.proto ) .  **Not even the bazel-genfiles folder.** 
The *.pb.h files should be generated by protobuf ,  what's wrong with my protobuf ?
the protobuf version and url refer to [workspace.bzl](https://github.com/tensorflow/tensorflow/blob/v2.4.1/tensorflow/workspace.bzl)

I don't  know how to solve it.  Thanks for your help.

**Comment by tilakrayal** [comment]
@no-define ,
Could you please update TensorFlow to the latest stable version v2.7 and let us know if you are facing the same error. Also please take a look at this issue [1](https://github.com/tensorflow/tensorflow/issues/47902) and [2](https://github.com/tensorflow/tensorflow/issues/46786) with the similar error.It helps.Thanks!

**Comment by no-define** [comment]
@tilakrayal  hi,I've tried  manually generating pb.h by command  `sudo protoc  <protofile>  --cpp_out=./ `
, now the original error has been fixed.  Thank you anyway!

**Comment by tangjie77wd** [comment]
> unsupported/Eigen/CXX11/Tensor

You could see the solution in https://blog.csdn.net/wd1603926823/article/details/92843830 because the author solved the similar problem like the following shows:
`./unsupported/Eigen/CXX11/Tensor:1:42: error: #include nested too deeply
tensorflow/core/lib/core/threadpool.cc:88:49: error: expected template-name before ‘<’ token
 struct ThreadPool::Impl : Eigen::ThreadPoolTempl<EigenEnvironment> {
                                                 ^
tensorflow/core/lib/core/threadpool.cc:88:49: error: expected ‘{’ before ‘<’ token
tensorflow/core/lib/core/threadpool.cc:88:49: error: expected unqualified-id before ‘<’ token
tensorflow/core/lib/core/threadpool.cc:217:1: error: expected ‘}’ at end of input
 }  // namespace tensorflow
 ^
tensorflow/core/lib/core/threadpool.cc:217:1: error: expected ‘}’ at end of input
`

**Comment by no-define** [comment]
> 

`tensorflow/third_party/eigen3/unsupported/Eigen/CXX11/Tensor:1:42: error: #include nested too deeply #include "unsupported/Eigen/CXX11/Tensor"`

way to solve this problem :   https://stackoverflow.com/questions/54779775/issues-including-eigen-for-simple-c-tensorflow-lite-test-program


`find . -name "eigen*" -type d `   

then edit your CMakeList.txt  :
` include_directories(
        ${CMAKE_CURRENT_SOURCE_DIR}/tf/eigen
)
`

try replace eigen path listed one by one.
