### ISSUE TITLE
Is it possible to report warning when plugin device cannot load instead of error?

### ISSUE THREAD

**Issue by guizili0** [tensorflow/tensorflow#53427]
Hi,
I found TF would crash when load plugin device fail, Is it possible to change it with warning instead of crash and do not enable plugin device? Just like the GPU device behavior.  
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/api_template.__init__.py#L150

**Comment by mohantym** [comment]
Hi @guizili0 ! 
Could you please update the other details in this [template ](https://github.com/tensorflow/tensorflow/issues/new/choose)too as it helps us analyse the issue .Thanks!

**Comment by guizili0** [comment]
@mohantym my issue is belong to others issue, in others issue, I found this 

> For high-level discussions about TensorFlow, please post to discuss@tensorflow.org

Do I need submit a topic here? https://discuss.tensorflow.org/

Basically I want to plugin device load fail with warning instead of error.
the python code for the plugin device is here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/api_template.__init__.py#L150
and the error raise is here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/client/tf_session_wrapper.cc#L714
I hope for plugin device load, here just show warning instead of raise error. Thanks!

**Comment by mohantym** [comment]
Hi @Saduf2019! Could you please look at this issue?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
