### ISSUE TITLE
Writing Tensor objects to Numpy arrays in Tensorflow 1.12

### ISSUE THREAD

**Issue by snehalstomar** [tensorflow/tensorflow#53456]
I am building a model which is supposed to be a composition of different models. I need the output of one model to be fed as input to another. To do so, I followed the standard approach of extending tf.keras.Model and modifying the call() function suitably. However, that didn’t work out since Model2 expects an input of the type np.ndarray whereas Model1 returns an output of the type tf.tensor hence their composition isn’t possible.

I have tried multiple ways of doing the above including converting the tensor to a tf.Variable and using the Variable.assign() method, writing out values to a list and then using np.stack() to get a np.tensor as output. Nothing has worked so far.

I request the community to kindly help me out in solving the above issue.

**Comment by sushreebarsa** [comment]
@snehalstomar We see that you are using `TF v1.12` which is not actively supported. Could you please try to upgrade to `TF` `v2.7.0` and please refer to the [migration guide](https://www.tensorflow.org/guide/migrate) for more information?Thank you!

**Comment by snehalstomar** [comment]
Hi!

I am actually trying to build upon a base model written in Tensorflow 1.12 for my research. I would highly appreciate it if you could kindly give me insights to make it work in TF v1.12

**Comment by sushreebarsa** [comment]
@snehalstomar You can only convert tensors to numpy arrays during Eager execution. Since you're using a version older than 2.0 this is not enabled by default.
In any case, you can call this after importing tensorflow;
`tf.compat.v1.enable_eager_execution()`

Depending on your framework and usecase, you might also have to run tf.config.run_functions_eagerly (if you have tf.function defined anywhere). For better support of the Eager mode, you should upgrade tensorflow to the newest version and use tf.keras as your code might not work properly with older standalone versions of Keras. In newer versions, you can specify your keras model to run eagerly  as follows:
`model.run_eagerly = True`

Please refer to similar [issue1](https://stackoverflow.com/questions/56205844/how-to-convert-a-tensorflow-tensor-to-a-numpy-array-within-tf-dataset-map-whil),[issue2](https://stackoverflow.com/questions/64004445/how-to-convert-tensor-into-numpy-array)

As TensorFlow version 1.x is out of support window so for any further queries  please post this issue in [TF Forum](https://discuss.tensorflow.org/) where there is a larger community to help .Thank you!
