### ISSUE TITLE
What need processing power?

### ISSUE THREAD

**Issue by metropt** [tensorflow/tensorflow#535]
Hi,

I maybe be wrong but from what I read about machine learing the learning process is what take a lot of time and need a lot of processing power, is it true? If yes, can I teach the neural network and then use the results on a small pc like rpi?

thank you

**Comment by mrry** [comment]
Typically we use a much larger amount of computation to train a model with TensorFlow (using one or more GPUs if it is a complex model), because the throughput of examples processed per second is what determines how long it takes to train the network.

For inference - depending on the model - it is often possible to scale horizontally by using lower power devices, and scaling out to many independent devices (unless the model is too big to fit on a single device). That's what makes it possible to run inference on a mobile device (like in the [Android tutorial](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/android)), and potentially it could also run inference on a Raspberry Pi.

**Comment by sriharrsha** [comment]
@mrry How much time and energy does an inference take on Android platform?

**Comment by mrry** [comment]
This depends a lot on the particular model that you are running. @petewarden would have better statistics than I do, but it's certainly plausible to run the Inception model for image recognition on an Android device.

**Comment by petewarden** [comment]
To give you a rough idea, a small Inception model like the one used in the Android example can run in under a second on a mid-range phone like a Nexus 5, and will take two or three Joules.

**Comment by sriharrsha** [comment]
@petewarden  Is it compulsory to include the graph in the apk itself / can we program to configure the graph after installing the apk and download the graph later on runtime.
