### ISSUE TITLE
Failed to load the native TensorFlow runtime.

### ISSUE THREAD

**Issue by SLP-phys8** [tensorflow/tensorflow#53548]
Hi,
I am having an issue when importing tensorflow into jupyter notebook. I installed tensorflow using pip install tensorflow using a command prompt opened via anaconda. I checked which versions of python and tensorflow are installed, the command line says I have python 3.8.5 and tensorflow 2.7.0. I believe they are compatible with eachother.
The error I get when importing it is attached below. 
![Issue](https://user-images.githubusercontent.com/96695861/147415587-9a175ade-f747-449b-b04e-01666ba43b08.PNG)

How can this be solved?
Many thanks

**Comment by Saduf2019** [comment]
@SLP-phys8 
Can you please share information in text which will help any user with similar/same error instead of sharing a screenshot.
Also you may refer to below similar issues and let us know if it helps. also please try in venv to see if you face the error.

#24419, [link](https://stackoverflow.com/questions/57214046/c-extension-not-working-in-python-3-7-says-importerror-dynamic-module-does-not?rq=1),[link2](https://github.com/pybind/pybind11/issues/2145)

**Comment by Nikhil-Mudgal** [comment]
hey @Saduf2019 , I want to start contributing to tensorflow. I checked some of the issues tagged contribution welcome and good first issue but they were too confusing for me at this earlier stage. Can you please suggest some issues I can start on. I will be highly obliged. Thanks

**Comment by Saduf2019** [comment]
@Nikhil-Mudgal 
can you open an issue on in discussion forum as there is a large community who can help and you can start addressing issues of your interest there, you can also filter labels here on github to issues of your choice and address them.
