### ISSUE TITLE
TensorFlow Lite C API TfLiteInterpreter misleading documentation

### ISSUE THREAD

**Issue by ebraraktas** [tensorflow/tensorflow#53628]
This is documentation bug in TFLite C API. I am not sure if I chose a proper issue tag.

### Clear description

See [the documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h#L146-L158) of `TfLiteInterpreterCreate`.

According to this documentation, the snippet below is valid:
```c++
std::vector<char> model_data;
{
    // Fill model data    
}
TfLiteModel *model = TfLiteModelCreate(model_data.data(), model_data.size());
// Create the interpreter.
TfLiteInterpreter *interpreter = TfLiteInterpreterCreate(model, options);
// According to documentation, I can delete the model.
// Hence, the lifetime of the model ends.
TfLiteModelDelete(model);
```

From now on, according to [the documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h#L98-L104) of `TfLiteModelCreate`, `model_data` 
can be modified. Like the snippet below:
```c++
for (char& e : model_data) {
  e = 0;
}
```
This is just a demo to show that current or another process may modify the memory region.

However, this is not valid, and corrupts the interpreter severely. Deleting a `TfLiteModel` object is ok, if one reads it from a file, because the interpreter relies on the file which is _assumed_ to stay unmodified during the lifetime of the interpreter. On the other hand, lifetime of an Interpreter must be bounded by the model which is bounded by the lifetime of the model data to avoid errors. Similar statement can be found in [the documentation](https://www.tensorflow.org/lite/api_docs/cc/class/tflite/interpreter#summary) of the C++ API (see the usage snippet).

I think @jdduke is the one who can fix the documentation properly, but my suggestion is to replace `... and can destroy it immediately after creating the interpreter; the interpreter will maintain its own reference to the underlying model data` part with ` and the model data must outlive the interpreter` to avoid confusion.

**Comment by tilakrayal** [comment]
@ebraraktas ,
Can you please feel free to submit a PR for the requested change or share the link where requested change is to be made?

**Comment by tilakrayal** [comment]
@ebraraktas ,
Can you please feel free to move this issue to closed status as related PR has been merged.Thanks!

**Comment by fergushenderson** [comment]
> See [the documentation](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/c/c_api.h#L146-L158)
> of TfLiteInterpreterCreate.

1. That link stopped working due to subsequent changes in that file.
Here's a corrected link to [the original documentation](
https://github.com/tensorflow/tensorflow/blob/8c8e16921656a6ed4238368e72281080d4d9b17f/tensorflow/lite/c/c_api.h#L146-L158) of TfLiteInterpreterCreate.

2. This fix in https://github.com/tensorflow/tensorflow/pull/53711/commits/c109cfb2921b4d8d1340de83987646e4b607cce7 wasn't quite right; it didn't properly distinguish the lifetime of the buffer from the lifetime of the TfLiteModel object. It's fine to destroy the TfLiteModel object before the lifetime of the TfLiteInterpreter has ended (since internally the TfLiteInterpreter has a shared_ptr to the underlying FlatBufferModel object), it's only the byte buffer whose lifetime needs to last beyond the lifetime of the TfLiteInterpreter. We will make a further fix to correct the docs.
