### ISSUE TITLE
py_function is slower in TF2.7 (and 2.6) compared to TF2.5

### ISSUE THREAD

**Issue by anth2o** [tensorflow/tensorflow#53620]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04
- TensorFlow installed from (source or binary): docker
- TensorFlow version (use command below): 2.7
- Python version: 3.8.10

**Describe the current behavior**

In my training code I'm using `tf.data.Dataset.map` with a `tf.py_function` within it. I know that using `tf.py_function` is slower than regular tensorflow, but there's a part of my dataset processing that requires the usage of plain Python code.   

However, when I tried to upgrade TF from 2.5 to 2.6, I noticed that my trainings were slower in 2.6 compared to 2.5. I postponed the upgrade at the moment. When 2.7 came out I tried again but the slower data processing was still present.

**Describe the expected behavior**

I would have expected this kind of code to be as efficient as it was in 2.5

**Standalone code to reproduce the issue**

You can find a reproducible example in [this colab](https://colab.research.google.com/drive/1AmOnuNosr7nq5p4m25jJwG-I2R9r7PTf?usp=sharing).

To reproduce my issue, I wrapped the opening of the image on disk within a `tf.py_function` and opened it using Pillow and numpy. I know that this can be done in a more efficient way as I explained directly in the colab.

Here are the results I got when executing the `%%timeit` cell with 2 different versions of TF:
- tf.__version__ = "2.7.0" -> 3 loops, best of 7: 1.81 s per loop (would have been the same in TF2.6)
- tf.__version__ = "2.5.2" -> 3 loops, best of 7: 1.44 s per loop

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue? Attaching Gist in[ 2.7](https://colab.sandbox.google.com/gist/mohantym/0a49116bc0c7ea34af5b6fa563df2ffb/slow_pyfunction_tf27.ipynb#scrollTo=oQ0SYAzqIOqS) and [2.6](https://colab.sandbox.google.com/gist/mohantym/e63c8daa9c9680caf97c6678553de514/slow_pyfunction_tf27.ipynb#scrollTo=LGz8iNzS6a4K) for reference .Thank you!

**Comment by bgdax** [comment]
Thanks for raising this issue. We are looking into it.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
