### ISSUE TITLE
Question on implicit transpose in HLO bitcast/copy/reshape instruction #2

### ISSUE THREAD

**Issue by donglinz** [tensorflow/tensorflow#53650]
In below dumped hlo instruction:
```
%bitcast.94 = f16[1,128,2,64]{3,1,2,0} bitcast(f16[1,2,128,64]{3,2,1,0} %bitcast.50)
```

both tensor shape and memory layout are permuted between dimension 1 and dimension 2.

However in this instruction
```
%copy.6 = f16[2,128,128]{2,1,0} copy(f16[2,128,128]{1,2,0} %bitcast.70)
```

Dimension 1 and dimension 2 have same size, I cannot infer from dumped IR about whether tensor share are permuted between dim 1 and dim 2.

May I ask how can I get complete information shape/layout permutation?

**Comment by mohantym** [comment]
Hi @Saduf2019 ! Could you please look at this issue?

**Comment by akuegel** [comment]
Copy always uses the same (logical) dimensions, but permutes the layout (physical) dimensions. So a copy actually moves dimensions around.
Bitcast however is a no-op, it does not copy any data. It can do that by changing the physical layout in the same way as the (logical) dimensions, so that it still is the same data as before. The bitcast you show here is in fact a Transpose op in disguise. For Transpose op, layout assignment always assigns a layout such that it becomes a bitcast.
Hope this makes it a bit clearer :)

**Comment by donglinz** [comment]
@akuegel Thanks a lot!!! That makes me much more clear on this.

I have two further questions on these instructions:

# Q1 
I am still a little bit confused about Reshape instruction, consider:
```
%reshape.103 = f16[4,128,2,64]{3,1,2,0} reshape(f16[512,128]{1,0} %slice.20)
```

Looks this reshape.103 instruction is combined of two steps:
1. [512,128]{1,0} -> [4,128,2,64]{3,2,1,0}
2. [4,128,2,64]{3,1,2,0}

So, is it functionally equivalent to a Bitcast (step 1) followed by a Copy (step 2) instruction?

# Q2:
In addition, I am also wondering about which instructions can incur underlying data change.
Consider Reshape/Transpose/Copy/Bitcast instructions. Underlying data change only happens on Copy and Reshape instructions as these two instructions both can permute layout (physical) dimensions in a way that is not aligned with logical dimension change. In contrast, Transpose and Bitcast do not change data, only change meta-data in HLO IR. Am  I understanding correctly in this regard?

**Comment by akuegel** [comment]
Regarding question 1) yes, for reshape, layout assignment also assigns a layout such that the reshape is a bitcast (i.e. no data has to be moved around). It can happen that this chosen layout can be propagated to other ops so that we don't need the copy. In this case, it seems we still need the copy.

Regarding question 2) In fact, after layout assignment we should only have Copy which moves data. Reshape and Transpose become bitcasts, however we don't replace Transpose ops inside fusion nodes with bitcasts because that allows to generate more efficient code (we may be able to reuse multi-dimensional iteration variables if we know the no-op is a transpose, so we only need to permute the multi-dimensional index instead of recalculating it; the Bitcast op loses this information).

**Comment by donglinz** [comment]
Thanks for the detailed explanation. Closing the issue now:)
