### ISSUE TITLE
Deterministic selection of deterministic cuDNN convolution algorithms removed in TF 2.5

### ISSUE THREAD

**Issue by duncanriach** [tensorflow/tensorflow#53771]
Summary: deterministic selection of deterministic cuDNN convolution algorithms (added in TensorFlow version 1.14) has been broken since version 2.5. This issue explains how it was broken, provides a work-around, and discusses next-steps.

Pull request [34951](https://github.com/tensorflow/tensorflow/pull/34951), opened by @duncanriach (merged on 2020-01-27 for TF 2.2), added multi-algorithm deterministic cuDNN convolutions, which included deterministically selecting (via the auto-tuning code), for each path through the convolution op, the first working algorithm in a list of deterministic algorithms.

This refactoring [commit](https://github.com/tensorflow/tensorflow/commit/c865c2d8822ecc663f95a01e08b2f465d478f4e9), part of pull request [46965](https://github.com/tensorflow/tensorflow/pull/46965) opened by @kaixih (merged on 2021-03-19 for TF 2.5), accidentally removed the code from `tensorflow/core/kernels/gpu_utils.cc` that caused the first working algorithm to be deterministically selected when op determinism is enabled. Instead, the auto-tuner code runs as normal on the list of deterministic algorithms. This lead to a functional regression in deterministic operation that still exists up to and including TF version 2.8.

Although I have heard @reedwm mention that he thought there might be a regression, this issue was confirmed by [this comment](https://github.com/tensorflow/tensorflow/pull/34951#issuecomment-974714116), from @leiwuzheng, in the original pull request 34951 (which added the functionality) for TF version 2.5. @leiwuzheng, please add some simple reproducer code here.

This regression was not prevented, and not discovered sooner, because there were and are no tests for this functionality. At the time I implemented it, it seemed very difficult or impossible to test.

Thankfully, the XLA-equivalent code (to deterministically select the first working algorithm from a list of deterministic algorithms) appears to have been retained in a similar refactoring by @cheshire in [this commit](https://github.com/tensorflow/tensorflow/commit/eed38bdd4d7bfa7d81efb99d8bd7d68e2288adc5) (committed on 2021-05-20).

The current work-around, as confirmed by @leiwuzheng, is to set the environment variable `TF_CUDNN_USE_FRONTEND` to `1` (from TF version 2.5 through at least 2.8, the default is `0`). This is an effective work-around because the code that uses the new cuDNN 8 frontend/backend API correctly selects the first algorithm from the list of deterministic algorithms, as the legacy code did prior to the regression.

When `TF_CUDNN_USE_FRONTEND` defaults to `1`, the severity and urgency of this issue will be reduced, but the issue will persist until `TF_CUDNN_USE_FRONTEND` is removed along with the associated legacy code.

The intention of this current issue is to drive the reinstatement of the functionality in the legacy code, and to ensure that the functionality is tested in both the legacy code and the new code (with `TF_CUDNN_USE_FRONTEND` set to both `0` and `1`). Testing may require the addition of a mechanism to allow auto-tuning to be reset dynamically (in the running python process). I believe that @reedwm may have further thoughts on how to test.

**Comment by duncanriach** [comment]
@reedwm, if this cannot be fixed (and the fix cherry-picked into the r2.8 branch) before the final version 2.8 release, then I think that the work-around should be added to the [documentation](https://www.tensorflow.org/api_docs/python/tf/config/experimental/enable_op_determinism) for `tf.config.experimental.enable_op_determinism`. What are your thoughts on that?

**Comment by reedwm** [comment]
Changing the documentation also requires a cherry-pick, unfortunately.

I'm still reading the code and the commits you referenced to fully understand what is going on. I mistakenly believed `TF_CUDNN_USE_FRONTEND` defaulted to `1`. Instead, it only defaults to `1` if TF is built with at least cuDNN 7.2. This is true in internal builds, which is what I've been testing with, but the pip package is built with cuDNN 7.1, so `TF_CUDNN_USE_FRONTEND` defaults to `0`.

Once I finish reading the code to understand this fully, I'll create and submit a fix and immediately try to cherry-pick it.

I'll try to think of how to test this after we cherry-pick the fix in, since that is less urgent.

**Comment by duncanriach** [comment]
Nice. Thanks, @reedwm.

**Comment by reedwm** [comment]
Stream executor will still filter out nondeterministic algorithms at least. So the only (known) source of nondeterminism is the fact which algorithm is chosen is nondeterministic. I will fix and try to cherry-pick.

I found an example to reproduce. On a Titan V, with CUDA 11.2.2, cudnn 8.1.1 and TensorFlow 2.8rc0, the following is nondeterministic:

```python
import tensorflow as tf

tf.keras.utils.set_random_seed(1)
tf.config.experimental.enable_op_determinism()

inp = tf.random.normal((64, 8, 8, 8))
f = tf.random.normal((3, 3, 8, 8))
out = tf.nn.conv2d(inp, f, [1, 1, 1, 1], padding='SAME')
print(tf.reduce_sum(out))
```

This convolution doesn't look very unusual, so it's clear this issue can happen in practice. Hopefully this is what was causing #53792 and also hopefully there are no other major determinism issues like this one. I will fix and try very very hard to cherry-pick.

**Comment by reedwm** [comment]
I plan on fixing this by choosing the first working algorithm in `gpu_utils.cc` when determinism is enabled. Unfortunately, this still has a very slightly possibility of nondeterminism: Because memory consumption is nondeterministic, an algorithm may non deterministically OOM, and so the "first working algorithm" is also nondeterministic. It's possible to fix this by selecting the first working or OOMing algorithm, but I worry that logic might be too complicated for a last minute cherrypick.

I'm pretty sure even before the [commit](https://github.com/tensorflow/tensorflow/commit/c865c2d8822ecc663f95a01e08b2f465d478f4e9) that caused this issue, this slightly possibility of nondeterminism could occur, so I think leaving this bug in TF 2.8 is OK. @duncanriach let me know if you disagree. This bug will be fixed for TF 2.9.

**Comment by edwardyehuang** [comment]
@reedwm  It is possible to give a small patch asap before TF2.9? Since I am preparing ECCV 2022, and I want to provide a fully reproducible code as appendix, and ack your hardworking for deterministic in my paper.

**Comment by duncanriach** [comment]
@reedwm, very nice analysis and thinking. I agree with you, the OOM issue has not been addressed before and leaving it in 2.8 is okay.

@edwardyehuang, my understanding is that @reedwm is intending to undo the regression that was introduced in TF2.5 in TF2.8, via a cherry-pick. He is also suggesting addressing a further (OOM) issue that has been raised in TF2.9. It's extremely unlikely the further issue would lead to nondeterminism for you.

**Comment by reedwm** [comment]
I created a cherry-pick request here https://github.com/tensorflow/tensorflow/pull/53826. It will likely get merged.

**Comment by duncanriach** [comment]
Yay! I see it was merged. Thanks, @reedwm. BTW, the most recent release was 2.8.0-rc0 (not rc1).

**Comment by edwardyehuang** [comment]
Note that, in TensorFlow 2.8.0, currently I have 5% chance to produce a non-determinsitc result (but closer), after I run again, it will produce the determinstic result.

I did not meet this issue in TensorFlow 2.8.0 RC0 (with TF_CUDNN_USE_FRONTEND set)

**Comment by duncanriach** [comment]
@edwardyehuang, are you saying that, with your particular model running on TensorFlow version 2.8.0, you get the same result on only 95% of the runs?

Does setting `TF_CUDNN_USE_FRONTEND=1` (when running on TensorFlow version 2.8.0) lead to the same result being produced on 100% of runs?

**Comment by edwardyehuang** [comment]
> @edwardyehuang, are you saying that, with your particular model running on TensorFlow version 2.8.0, you get the same result on only 95% of the runs?
> 
> Does setting `TF_CUDNN_USE_FRONTEND=1` (when running on TensorFlow version 2.8.0) lead to the same result being produced on 100% of runs

1: TensorFlow 2.8 rc0 + TF_CUDNN_USE_FRONTEND=1. My models always produce same results every runs.
2: TensorFlow 2.8 + TF_CUDNN_USE_FRONTEND=1. Some models, only happend once or twice, produce non-determinsitc results. However, after I ran again, result become the determinsitc one.

**Comment by duncanriach** [comment]
@edwardyehuang, as far as I know, when `TF_CUDNN_USE_FRONTEND=1`, there is no functional difference between version 2.8.0-rc0 and version 2.8.0 with respect to determinism. Therefore, I expect that whatever you noticed is unrelated to changes that were made between version 2.8.0-rc0 and version 2.8.0. Most likely, the version difference is a red herring and you just happened to observe the nondeterminism when using version 2.8.0 and not when using version 2.8.0-rc0.

It is possible that this nondeterminism you noticed was caused by the nondeterministic out-of-memory scenario that @reedwm [identified](https://github.com/tensorflow/tensorflow/issues/53771#issuecomment-1016028174) above. I believe that that functionality has existed going all the way back to TF 2.2 and is present whether `TF_CUDNN_USE_FRONTEND` is set to `0` (default) or `1`.

However, without isolating the source, as @leiwuzheng did [here](https://github.com/tensorflow/tensorflow/pull/34951#issuecomment-974714116), we cannot know for sure if the nondeterminism you saw was really caused by nondeterministic selection of deterministic cuDNN convolution algorithms (due to running out of memory), or by something else.

BTW, @leiwuzheng, (if possible) I would appreciate if you could confirm that with version 2.8.0 your model operates fully deterministically without setting `TF_CUDNN_USE_FRONTEND=1`. The nondeterministic selection of algorithms that you described [here](https://github.com/tensorflow/tensorflow/pull/34951#issuecomment-974714116), which is the primary focus of this current issue, should now be fixed.

General reminder to myself and others: before this issue can be closed, we're waiting for the OOM scenario to be addressed (whether `TF_CUDNN_USE_FRONTEND` is set to `0` or `1`), which @reedwm may complete before the version 2.9.0 branch is cut. @edwardyehuang, when those changes are in the master branch, you will be able to utilize them in the `tf-nightly` build.

**Comment by leiwuzheng** [comment]
@duncanriach, sorry for late respond. Currently, we do not have TF version 2.8 installed yet, will try once we have it ready. Another not so optimal way of fixing this non deterministic behavior is just turn off auto tune by setting TF_CUDNN_USE_AUTOTUNE = 0.

**Comment by duncanriach** [comment]
No problem, @leiwuzheng. The recommended work-around for TensorFlow 2.5, 2.6, and 2.7 is to set `TF_CUDNN_USE_FRONTEND=1`. Setting `TF_CUDNN_USE_AUTOTUNE=0` may result in an exception with the message "No algorithm worked!" in some cases, and is therefore not recommended.

**Comment by leiwuzheng** [comment]
@duncanriach , thanks for clarification. It's more clear now.

**Comment by leiwuzheng** [comment]
@duncanriach and @reedwm , after setting TF_CUDNN_USE_FRONTEND=1 and deterministic behavior, tensorflow will always use the first workable deterministic convolution algorithm for conv2d op. My question is this first workable deterministic convolution algorithm is already heuristically obtained convolution algorithm for the given layer specification (convolution filter size etc.)? For example, we may prefer WINOGRAD algo for conv2d op with 3*3*8*8 filter, and prefer FFT algo for conv2d op with 1*100*1*1 filter.
The reason I ask this question is recently we benchmarked runtime for the same job (minibatch size = 128) but with following 2 settings:

1. Set TF_DETERMINISTIC_OPS=1, TF_CUDNN_USE_AUTOTUNE=0, and TF_CUDNN_USE_FRONTEND=0, 

-  each training step takes about 0.6 seconds.

2. Set TF_DETERMINISTIC_OPS=1, TF_CUDNN_USE_AUTOTUNE =1 and TF_CUDNN_USE_FRONTEND=1,

- each training step takes about 1.5 seconds.
The runtime increased too much when using frontend api, I am not quite sure the runtime increase is expected or not.

**Comment by reedwm** [comment]
> My question is this first workable deterministic convolution algorithm is already heuristically obtained convolution algorithm for the given layer specification (convolution filter size etc.)

I am not sure. The cuDNN frontend API returns a list of algorithms generated by heuristics. On the TF side, without determinism, we choose the fastest, but with determinism, we choose the first algorithm in the list. I think the list takes into account the layer specification (input/filter shapes, padding etc), but I don't know if the order of the list takes this into account. The order is important, as with determinism, we always choose the first algorithm. @duncanriach, do you know if cuDNN tries to put the best algorithm at the front of the list or not?

@leiwuzheng, if possible, can you provide a short example to reproduce the convolution taking 0.6s without the cuDNN frontend API and 1.5s with the cuDNN frontend API? Unfortunately, I'm not sure if we have bandwidth to fix this. Performance could be improved with heuristics on the TF side to choose a better algorithm, but I'm not sure if we have time to implement this.

**Comment by duncanriach** [comment]
I suspect that the returned order of algorithms is arbitrary, but I'm not sure. @kaixih, do you know if the lists of deterministic algorithms returned by the cuDNN frontend API are pre-sorted (using a deterministic heuristic) based on expected performance given the particular layer configuration (e.g. highest to lowest expected performance) or is the list order currently arbitrary (just a list of algorithms that are deterministic and are also expected to work for the specified layer configuration)?

**Comment by kaixih** [comment]
Yes, the heuristics list is sorted based on the expected perf.

**Comment by duncanriach** [comment]
Thank you, @kaixih. In that case, deterministic performance should be roughly the same, if not better, using the cuDNN frontend API. @leiwuzheng, please will you open a new issue for this specific deterministic performance issue, and include in that a simple reproducer as requested by @reedwm.

**Comment by leiwuzheng** [comment]
@kaixih , @reedwm , @duncanriach , thanks a lot for the confirmation. After dumping out more tensorflow and cudnn log, I guess the performance regression issue is related with the cudnn bug https://forums.developer.nvidia.com/t/cudnn8-regression-in-algorithm-selection-heuristics/153667, and which is already fixed in cudnn8.2.1.

Following is test I did and the log dumped out:

###Testing environment

- cuda 11.2, cudnn 8.1.1 and 8.3.3, tensorflow 2.5
### Test cases

1.  cudnn 8.1.1, TF_DETERMINISTIC_OPS=1, TF_CUDNN_USE_FRONTEND=0, TF_CUDNN_USE_AUTOTUNE=0

-  Each training step takes about 0.6s
`I! CuDNN (v8101) function cudnnBackendExecuteInternal() called:
i!     enable_tf32: type=bool; val=false;
i!     operation: type=internalType; val=CONV_BWD_FILTER;
i!     xDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[512,8,21,21];
i!         strideA: type=int; val=[3528,441,21,1];
i!     wDesc: type=cudnnFilterDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         vect: type=int; val=0;
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[8,8,3,3];
i!         format: type=cudnnTensorFormat_t; val=CUDNN_TENSOR_NCHW (0);
i!     yDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[512,8,19,19];
i!         strideA: type=int; val=[2888,361,19,1];
i!     convDesc: type=cudnnConvolutionDescriptor_t:
i!         mode: type=cudnnConvolutionMode_t; val=CUDNN_CROSS_CORRELATION (1);
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         mathType: type=cudnnMathType_t; val=CUDNN_FMA_MATH (3);
i!         reorderType: type=int; val=0;
i!         arrayLength: type=int; val=2;
i!         padA: type=int; val=[0,0];
i!         strideA: type=int; val=[1,1];
i!         dilationA: type=int; val=[1,1];
i!         groupCount: type=int; val=1;
i!     alpha: type=CUDNN_DATA_FLOAT; val=1.000000;
i!     beta: type=CUDNN_DATA_FLOAT; val=0.000000;
i!     engine_id: type=int; val=**20**;
i!     knobDesc: type=cudnnBackendDescriptor_t:
i!         CUDNN_KNOB_TYPE_TILE_SIZE: type=int; val=6;
i!         CUDNN_KNOB_TYPE_USE_TEX: type=int; val=0;
i!     numericalNotes: type=cudnnBackendDescriptor_t:
i!         CUDNN_NUMERICAL_NOTE_REDUCED_PRECISION_REDUCTION: type=bool; val=true;
i!         CUDNN_NUMERICAL_NOTE_NONDETERMINISTIC: type=bool; val=true;`

2. cudnn 8.1.1, TF_DETERMINISTIC_OPS=1, TF_CUDNN_USE_FRONTEND=1, TF_CUDNN_USE_AUTOTUNE=1

- Each training step takes about 1.5s
`I! CuDNN (v8101) function cudnnBackendExecuteInternal() called:
i!     enable_tf32: type=bool; val=false;
i!     operation: type=internalType; val=CONV_BWD_FILTER;
i!     xDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[512,8,21,21];
i!         strideA: type=int; val=[3528,441,21,1];
i!     wDesc: type=cudnnFilterDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         vect: type=int; val=0;
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[8,8,3,3];
i!         format: type=cudnnTensorFormat_t; val=CUDNN_TENSOR_NCHW (0);
i!     yDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[512,8,19,19];
i!         strideA: type=int; val=[2888,361,19,1];
i!     convDesc: type=cudnnConvolutionDescriptor_t:
i!         mode: type=cudnnConvolutionMode_t; val=CUDNN_CROSS_CORRELATION (1);
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         mathType: type=cudnnMathType_t; val=CUDNN_DEFAULT_MATH (0);
i!         reorderType: type=int; val=1;
i!         arrayLength: type=int; val=2;
i!         padA: type=int; val=[0,0];
i!         strideA: type=int; val=[1,1];
i!         dilationA: type=int; val=[1,1];
i!         groupCount: type=int; val=1;
i!     alpha: type=CUDNN_DATA_FLOAT; val=1.000000;
i!     beta: type=CUDNN_DATA_FLOAT; val=0.000000;
i!     engine_id: type=int; val=**0**;
i!     knobDesc: type=cudnnBackendDescriptor_t; val=NULL_PTR;
i!     numericalNotes: type=cudnnBackendDescriptor_t; val=NULL_PTR;
i! Time: 2022-07-05T13:33:46.776747 (0d+0h+0m+5s since start)
i! Process=116059; Thread=116117; GPU=0; Handle=0x7efd55f09c70; StreamId=0x387f7790.`

3.  cudnn 8.3.3, TF_DETERMINISTIC_OPS=1, TF_CUDNN_USE_FRONTEND=1, TF_CUDNN_USE_AUTOTUNE=1
- Each training step takes about 0.8s
`I! CuDNN (v8303) function cudnnBackendExecuteInternal() called: 
i!     enable_tf32: type=bool; val=false;
i!     operation: type=internalType; val=CONV_BWD_FILTER;
i!     xDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[512,8,21,21];
i!         strideA: type=int; val=[3528,441,21,1];
i!     wDesc: type=cudnnFilterDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         vect: type=int; val=0;
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[8,8,3,3];
i!         format: type=cudnnTensorFormat_t; val=CUDNN_TENSOR_NCHW (0);
i!     yDesc: type=cudnnTensorDescriptor_t:
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         nbDims: type=int; val=4;
i!         dimA: type=int; val=[512,8,19,19];
i!         strideA: type=int; val=[2888,361,19,1];
i!     convDesc: type=cudnnConvolutionDescriptor_t:
i!         mode: type=cudnnConvolutionMode_t; val=CUDNN_CROSS_CORRELATION (1);
i!         dataType: type=cudnnDataType_t; val=CUDNN_DATA_FLOAT (0);
i!         mathType: type=cudnnMathType_t; val=CUDNN_DEFAULT_MATH (0);
i!         reorderType: type=int; val=1;
i!         arrayLength: type=int; val=2;
i!         padA: type=int; val=[0,0];
i!         strideA: type=int; val=[1,1];
i!         dilationA: type=int; val=[1,1];
i!         groupCount: type=int; val=1;
i!     alpha: type=CUDNN_DATA_FLOAT; val=1.000000;
i!     beta: type=CUDNN_DATA_FLOAT; val=0.000000;
i!     engine_id: type=int; val=**17**; 
i!     knobDesc: type=cudnnBackendDescriptor_t; val=NULL_PTR;
i!     numericalNotes: type=cudnnBackendDescriptor_t; val=NULL_PTR;
i!     behaviorNotes: type=cudnnBackendDescriptor_t; val=NULL_PTR;
i! Time: 2022-07-05T14:21:00.004114 (0d+0h+0m+4s since start)
i! Process=121704; Thread=121774; GPU=0; Handle=0x7f5886036a90; StreamId=0x3b6538d0.`

Unlike cudnn backend api, the frontend api doesn't clearly output the algorithm it used to do conv/conv backprop. From these log, I can see the engine_id's val is totally different from in these 3 cases. By the way, is there anyway to know which algo used in frontend api?

@duncanriach , since cudnn8.3.3 has already solved my issues, do you see we still need to file a new issue to track this specific performance regression case?

**Comment by duncanriach** [comment]
@leiwuzheng, if the regression has been fixed by using a newer version of cuDNN, then you don't need to (and should not) open a new issue.

**Comment by gadagashwini** [comment]
Hi @duncanriach, Can we move this issue to closed state, if it was resolved. Thank you!

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
