### ISSUE TITLE
[minor enhancement] Absolute vs. Relative import

### ISSUE THREAD

**Issue by zafartahirov** [tensorflow/tensorflow#5389]
I am raising a question if absolute imports should be changed to relative -- even if not in all the files, but at least in the files that have to be grouped together.
According to [PEP 328](https://www.python.org/dev/peps/pep-0328/#rationale-for-relative-imports):
> ... the most important [usage case ...] is being able to rearrange the structure of large packages without having to edit sub-packages. In addition, a module inside a package can't easily import itself without relative imports.

I understand that absolute imports help avoid "shadowing" of the modules/methods with the same names, but if the naming convention of the relative imports is enforced to be protected (`_name`), the problem could be mitigated.

**Comment by aselle** [comment]
We are unlikely to switch to relative imports because we need to adhere to our internal conventions which mandate absolute paths. @wicke or @vrv can probably give a better explanation. I believe bazel also does things this way. Thus I am closing it for now unless  @wicke and @vrv think we could do it. Thanks for bringing it up though.

**Comment by zafartahirov** [comment]
Thanks!
