### ISSUE TITLE
Copy-on-read Limits Usable GPU Memory

### ISSUE THREAD

**Issue by philipphack** [tensorflow/tensorflow#54105]
When sparsely accessed individual variables occupy a large portion of available memory, the necessary copy during dense reads, e.g. while saving a checkpoint, can substantially increase the total memory usage. In the limit of a single variable (such as an embedding table) occupying all allocated memory, this behavior causes the memory usage to double when the model is saved. Therefore, a single sparsely accessed variable can at most occupy half the available memory to avoid OOM while saving the model.

Possible solutions could include for instance allowing a conversion from copy-on-read to copy-on-write, or dense access without copy using an exclusive lock in some situations.
[](url)

**System information**
Reproducer: [copy_on_read_oom.zip](https://github.com/tensorflow/tensorflow/files/7946149/copy_on_read_oom.zip)

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N/A
- TensorFlow installed from (source or binary): Source
- TensorFlow version (use command below): 2.6
- Python version: 3.8
- Bazel version (if compiling from source): 4.2.2
- GCC/Compiler version (if compiling from source): 9.3.0
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you look at this feature request?

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
