### ISSUE TITLE
tf.image.adjust_brightness and random_brightness miss input check

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54116]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
x = [[[1.0, 2.0, 3.0],
      [4.0, 5.0, 6.0]],
    [[7.0, 8.0, 9.0],
      [10.0, 11.0, 12.0]]]
print(tf.image.adjust_brightness(x, delta=1.1))
print(tf.image.random_brightness(x, max_delta=1.1))

```

**Expected output**
According to the document [tf.image.adjust_brightness](https://www.tensorflow.org/api_docs/python/tf/image/adjust_brightness?hl=en), the delta should be in range `(-1, 1)`. And random_brightness is  quivalent to adjust_brightness() using a delta randomly picked in the interval [-max_delta, max_delta), so valid input check is also missing here.

**Comment by mohantym** [comment]
Hi @jvishnuvardhan ! Could you please look into this issue ? It is replicating in [2.6](https://colab.sandbox.google.com/gist/mohantym/aa7ca251a9388c45411aa67dcb9748ff/github_54116.ipynb#scrollTo=96aKifvB8EyQ), [2.7](https://colab.sandbox.google.com/gist/mohantym/b2e8fdb4207ad6fcc477c0d0a1e1ef03/github_54116.ipynb) and [2.8](https://colab.sandbox.google.com/gist/mohantym/d042a09b947b8c4e6ab437083059bd31/github_54116.ipynb#scrollTo=-GRf3hmP8AYE).

**Comment by Cheril311** [comment]
Can look into this

**Comment by Cheril311** [comment]
@ArrowIntoTheSky like the documentation says I believe delta should be in the range (-1,1) when your pixel ranges are in between 0 and 1 however if there are some exceptional irregular images, the delta value can exceed the range given, thus the validation is not implented

**Comment by Cheril311** [comment]
That being said I guess we can add a validation based on pixel ranges and then adjust the delta values, I am working on it and will submit a pr

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
