### ISSUE TITLE
TensorArray.stack should accept axis as argument

### ISSUE THREAD

**Issue by deluksic** [tensorflow/tensorflow#54171]
**Describe the feature and the current behavior/state.**

Currently there is:
```python
TensorArray.stack(name=None) -> tf.Tensor
```

If we want to have stacking along a different axis, we must manually transpose using:
```python
myTensorArray = tf.TensorArray(dtype=tf.float32, size=6, element_shape=(2, 3))
# [6, 2, 3]
res = myTensorArray.stack()
axis = 1
*perm, = range(len(res.shape))
perm[0], perm[axis] = perm[axis], perm[0]
# [2, 6, 3]
res_correct = tf.transpose(res, perm)
```

NOTE: I could have directly written out the `perm` parameter, but what if you're writing a library where you want to be able to stack along user-defined axis?

**Will this change the current api? How?**

New definition could directly do this:
```ptyhon
TensorArray.stack(axis=0, name=None) -> tf.Tensor
```

**Who will benefit with this feature?**

Anyone who uses `TensorArray.stack` and doesn't want to stack on 0th dimension.

**Any Other info.**

Performance implication of stacking along non-0 axis should be considered and clearly explained in docs if significant.

EDIT: Other APIs in TensorArray should also be considered to be consistent. For example
```python
TensorArray.concat(name=None) ->tf.Tensor
TensorArray.unstack(value, name=None) ->tf.Tensor
```

**Comment by ricvo** [comment]
Related to: https://github.com/tensorflow/tensorflow/issues/8369

**Comment by ricvo** [comment]
`def tf_array_stack(tf_array, axis=0):
    stacked = tf_array.stack()
    if axis!=0:
        num = stacked.shape[0]
        splits = [tf.squeeze(t) for t in tf.split(stacked, num)]
        stacked = tf.stack(splits, axis=axis)

    return stacked
`

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
