### ISSUE TITLE
Allow to change thread timeout in collective_ops with an ENV variable

### ISSUE THREAD

**Issue by alonfnt** [tensorflow/tensorflow#54221]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.6.2
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
This issue happens with XLA when using JAX in a multi-host system, where I get `This thread has been waiting for 5000ms for and may be stuck` when the pmap function is getting compiled and rapidly followed by `Thread is unstuck!  Warning above was a false-positive.`. This gets annoying when I know that it is not really stuck and I get it on most of the devices (so the log gets repeated `num_devices` times). 

**Will this change the current api? How?**
Looking at the code, the 5000ms are hardcoded. Because I understand the need to log these cases, I would propose adding an ENV var where you could change the 5000ms to be another value, and if the variable is not set, then keep the 5000ms which works on most cases. 

It would only require to modify this function at `tensorflow/tensorflow/compiler/xla/service/collective_ops_utils.h`
```
template <typename DescFn>
void WaitAndLogIfStuck(tensorflow::BlockingCounter* counter,
                       const DescFn& desc_fn) {
  VLOG(3) << "Begin: " << desc_fn();
  const std::chrono::milliseconds timeout(5000);
  bool ok = counter->WaitFor(timeout);
  if (ok) {
    VLOG(3) << "Finished: " << desc_fn();
    return;
  }
  LOG(ERROR) << "This thread has been waiting for " << timeout.count()
             << "ms for and may be stuck: " << desc_fn();
  counter->Wait();
  LOG(ERROR) << "Thread is unstuck!  Warning above was a false-positive.  "
                "Perhaps the timeout is too short: "
             << desc_fn();
}
```
**Who will benefit with this feature?**

Cleaner logs and avoid known false positive.

**Any Other info.**

Also, there's a `for` repeated on the log which could be fixed in the same PR :)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by alonfnt** [comment]
😆 win by attrition.

**Comment by dmarx** [comment]
@alonfnt so does that mean there was never a PR to add this env var?

**Comment by alonfnt** [comment]
> [@alonfnt](https://github.com/alonfnt) so does that mean there was never a PR to add this env var?

@dmarx 
No. Waited for a response of the tensorflow team before doing the PR.

But to be fair, at some point I did stop recieving the errors... so things may have changed in the ~3 years until I got the comment to close this.
