### ISSUE TITLE
CONV_ADD and CONV_ADDV2 Fusion

### ISSUE THREAD

**Issue by Alok-Ranjan23** [tensorflow/tensorflow#54246]
Why do we need to check the broadcast compatibility before CONV_ADD and CONV_ADDV2 Fusion?

Refer line 818 of [remapper.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/remapper.cc)

`if (!IsAddN(*node_def) && !IsAddWithNoBroadcast(ctx, *node_def)) return false;`

Why do we need _**IsAddWithNoBroadcast(ctx, *node_def)**_ check? 

Refer line 795 to  805 of [remapper.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/grappler/optimizers/remapper.cc) for the definition of  _**IsAddWithNoBroadcast**_

`bool IsAddWithNoBroadcast(const RemapperContext& ctx, const NodeDef& node) {`
`  if (!IsAdd(node)) return false;`

  `// Check if this is case of broadcasting - Add node supports broadcasting.`
  `const auto& props = ctx.graph_properties.GetInputProperties(node.name())`;
  `if (props.size() == 2 &&`
      `ShapesSymbolicallyEqual(props[0].shape(), props[1].shape())) {`
   ` return true;`
 ` }`
  `return false;`
`}`

If we have Add op defined in our network, then both of its inputs are either same or broadcast compatible otherwise we can not perform Add.

Consider the third ADD node of [resnet50_v1.pb](https://zenodo.org/record/2535873/files/resnet50_v1.pb) in the attached figure. 

<img width="421" alt="Resnet50_v1_Add3" src="https://user-images.githubusercontent.com/40749307/152197427-69dd56ca-16f9-4bc0-844a-0757ca2c62cd.PNG">

Please clarify why we need a Broadcast compatibility check. If inputs to Add are not the same or broadcast compatible, then How is it possible to have an Add op in the network?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
