### ISSUE TITLE
inference/prediction batch is non deterministic and overlap data

### ISSUE THREAD

**Issue by kabilan6** [tensorflow/tensorflow#54259]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7/2.2
- Python version: 3.10,3.8

**Describe the current behavior**
we create tensor dataset from parquet files using make_batch_reader() & make_petastorm_dataset().
Strategy - Multiworker mirror strategy
we use tf native functions like unbatch, batch, autosharding etc 
tf.data.experimental.AutoShardPolicy.DATA

ds = dataset.
        .unbatch()
        .batch(xcc_batch_size)
        .with_options(options)
         .prefetch(AUTO)

strategy.experimental_distribute_dataset(ds)

tensor data have overlap between batches and we expect the data shouldn't overlap between batches. 

**Describe the expected behavior**

data shouldn't overlap between batches. if we batch 100 records in 10 batch then i would expect all 10 batches should have unique data.

**Comment by duncanriach** [comment]
Adding clarification that @kabilan6 provided in #53846: This issue occurs on a single GPU, so multi-GPU strategy is not relevant.

@kabilan6, before we ask you for a simple reproducer script, are you able to first try running on TF 2.8? There were some potentially relevant determinism fixes between 2.7 and 2.8 related to `tf.data.Dataset` that might resolve at least the nondeterminism element of your issue.

**Comment by kabilan6** [comment]
@duncanriach we noticed issue with both single and multi gpu workers. i tried tf 2.8 version and still same issue. we create tensor dataset from parquet file. then we use tf unbatch and batch function, then distribute with experimental_distribute_dataset

**Comment by duncanriach** [comment]
@kabilan6,

# Single vs multi-GPU

When considering determinism, if there is not determinism with a single GPU then there will also not be determinism with multi-GPU. (The inverse is not necessarily true, however.) Once a single GPU is operating deterministically, multi-GPU will automatically operate deterministically, unless you are running into an independent issue with multi-GPU, which is unlikely.

*Therefore, this issue is, at least and for now, a single GPU issue.*

I think we can probably also rule out `experimental_distribute_dataset` since this is multi-device functionality, unless its use with a single device is somehow introducing a bug (which is unlikely). However, I think it should be easy to include in a reproducer script.

# TF Version

Thank you for confirming that the issue is occurring with TF2.8.

# Next Steps

In your original comment, you wrote, "we create tensor dataset from parquet files using make_batch_reader() & make_petastorm_dataset()." I assume that you are referring to `petastorm.reader.make_batch_reader` ([documentation](https://petastorm.readthedocs.io/en/latest/api.html#module-petastorm.reader)) and `petastorm.tf_utils.make_petastorm_dataset` ([use example](https://petastorm.readthedocs.io/en/latest/readme_include.html#tensorflow-api)).

*Have you confirmed that this software from Petastorm generates data both correctly and deterministically/reproducibly?*

In your original comment, also mention that you're using `tf.data.experimental.AutoShardPolicy.DATA`. Note that in the [documentation](https://www.tensorflow.org/api_docs/python/tf/data/experimental/AutoShardPolicy), it states "Note that for this mode to correctly partitions the dataset elements, the dataset needs to produce elements in a deterministic order."

*Have you experimented with disabling sharding, by setting it to `OFF`?*

**Comment by kabilan6** [comment]
Thanks for your timely response. If the auto sharding is set to OFF , how tf batch data will be distributed to different worker and multiple gpu with in a worker in multi worker strategy?

Another question, If i try mirror strategy ( with single worker and single GPU), we noticed data non determinstic  data(tf2.7), do you think this should be resolved in 2.8 ? 

 Have you confirmed that the Petastorm-provided dataset is generating data both correctly and deterministically/reproducibly? we set the worker_count = 1 and ran multiworker startegy, i hope this should produce data in determinstic order.

**Comment by duncanriach** [comment]
> If the auto sharding is set to OFF , how tf batch data will be distributed to different worker and multiple gpu with in a worker in multi worker strategy?

My intention for asking you about setting `AutoShardPolicy` to `OFF` was as an experiment to see if that led to the non-uniqueness problem being resolved. If it did, then it would support the hypothesis that the problem of nondeterminism and non-uniqueness in the dataset was related to the Petastorm-provided dataset being nondeterministic/non-reproducible.

This is just an experiment to help isolate the source of the problems you're seeing. I'm making hypotheses and asking you to run experiments to test those hypotheses.

> Another question, If i try mirror strategy ( with single worker and single GPU), we noticed data non determinstic data(tf2.7), do you think this should be resolved in 2.8 ?

It seems like you're changing too many variables. We just need to focus on isolating the source of the problems in the system as it stands. We're not even trying to find a solution yet. We're just trying to isolate the problem.

What I first want us to do is rule out this being a Petastorm-related issue. Everything I asked about in my previous comment is focused on that.

**Comment by duncanriach** [comment]
I think you should run one experiment at a time (on a single GPU); only run *one* of the following at a time, not necessarily in the order listed, and then we can use the results to infer what might be happening. You don't necessarily have to run all of these experiments. It sounds like you're starting with experiment two, although I'm concerned that you've changed the multi-GPU strategy, which could be confounding (and also suggests you're not running these experiments on a single GPU, as you should now be).

1. Look at the sequence of data coming out of the dataset produced by Petastorm to see if it's deterministic.
2. Set `petastorm.reader.make_batch_reader` `worker_count` to 1.
3. Set TF `AutoShardPolicy` to `OFF` to see if this makes be batch contents unique.

**Comment by duncanriach** [comment]
Also, to debug these kinds of problem, to run the above experiments, you shouldn't need to run for very long. You should be able to see the nondeterminism after only a few steps, maybe 10 steps. You can check for determinism by performing a running hash on the examples coming out of the dataset. At this point, you'll want to focus on confirming determinism of the dataset coming out of Petastorm, because it's upstream.

**Comment by duncanriach** [comment]
And remember, as with any change you make, if setting `worker_count` to 1 (on its own, in the absence of other changes) leads to the batches being deterministic and unique, then it will merely provide certainty that the nondeterminism is coming from the Petastorm section of your data pipeline. It will not necessarily be the ultimate solution you will want to use. There might be a best-practice for getting maximum deterministic performance from Petastorm.

**Comment by duncanriach** [comment]
For future reference, here is the summary of my current understanding of this issue.

Until it's ruled out, we should assume that the observed/reported nondeterminism is coming from the upstream [Petastorm](https://petastorm.readthedocs.io/en/latest/index.html) section of the input pipeline. Although I have not written code to reproduce it, the [documentation](https://petastorm.readthedocs.io/en/latest/api.html#module-petastorm.reader) for `petastorm.reader.make_batch_reader` (and `petastorm.reader.make_reader`) has pseudo-random functionality that must be initialized in order to obtain determinism.

Additionally, the observed "overlap data" is probably due to feeding TensorFlow's DATA-mode autosharding functionality with the nondeterministic data from Petastorm. See [this documentation](https://www.tensorflow.org/api_docs/python/tf/data/experimental/AutoShardPolicy).

@mohantym, please will you change the title of this issue to "Batch is nondeterministic and has overlapping data when using Petastorm make_batch_reader".
