### ISSUE TITLE
Dataset error when using with XLA device (No unary variant device copy function found)

### ISSUE THREAD

**Issue by mmaor123** [tensorflow/tensorflow#54254]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): yes
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.3 LTS
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: NA
- TensorFlow installed from (source or binary): binary 
- TensorFlow version (use command below):  v2.8.0-rc1-32-g3f878cff5b6 2.8.0
- tensorflow-2.8.0-cp38-cp38-manylinux2010_x86_64.whl
- Python version: 3.8
- Bazel version (if compiling from source): NA
- GCC/Compiler version (if compiling from source): NA
- CUDA/cuDNN version: NA
- GPU model and memory: NA

**Describe the current behavior**
error in script: 
tensorflow.python.framework.errors_impl.InternalError: Failed copying input tensor from /job:localhost/replica:0/task:0/device:CPU:0 to /job:localhost/replica:0/task:0/device:XLA_CPU:0 in order to run __inference_f_27: No unary variant device copy function found for direction: 1 and Variant type_index: tensorflow::data::(anonymous namespace)::DatasetVariantWrapper [Op:__inference_f_27]

**Describe the expected behavior**
script runs with no errors and produces values as expected 

**[Contributing](https://www.tensorflow.org/community/contribute)**

- Do you want to contribute a PR? (yes/no): no - internal error 
- Briefly describe your candidate solution(if contributing): no - internal error 

**Standalone code to reproduce the issue**
```
import os
os.environ['TF_XLA_FLAGS'] = '--tf_xla_enable_xla_devices' 

import tensorflow as tf

dataset = tf.data.Dataset.range(10)
    
@tf.function
def f():
    for x in dataset:
        tf.print(x)

with tf.device('/device:XLA_CPU:0'):
    f()
```

**Comment by tilakrayal** [comment]
@jvishnuvardhan ,
I was able to reproduce the issue in tf v2.8, v2.7 and  nightly.Please find the gist [here](https://colab.research.google.com/gist/tilakrayal/07573cb93790424e0b640394b574b142/untitled212.ipynb).

**Comment by mmaor123** [comment]
adding more context: 
it appears like this failure is related to the fact that XLA is (rightfully) not supporting dataset structs and operations. however, the failure is not clear and it would be better to try and generate a clear failure statement that explains that. 
the user is expected to explicitly place all dataset related work on the CPU and hand over only pure tensors to the function, when must-compile is used (in this case, the must-compile is implicitly triggered because of the explicit placement on an XLA device).

**Comment by Jianhui-Li** [comment]
@penpornk

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
