### ISSUE TITLE
TFTRT is not optimizing Resize Bilinear

### ISSUE THREAD

**Issue by rpytel1** [tensorflow/tensorflow#54310]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):Linux Ubuntu 18 (using docker image from nvidia: [nvcr.io/nvidia/tensorflow:21.12-tf2-py3](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/tensorflow)
- TensorFlow installed from (source or binary): 2.6.2, but the problem persists on older versions too (all versions in 2021). Newer versions are not yet stable for tensorrt. 
- TensorFlow version (use command below): via docker image. 
- Python version: Python 3.8.10
- CUDA/cuDNN version: CUDA 11.5.0
- GPU model and memory: Telsla T4 16 GB, but also on GTX 1080 TI. 

**Describe the current behaviour**
When training and optimizing the model, logs indicate that an operation called ResizeBilinear is not optimized. Initially, I thought that's because I am using dynamic_shapes = True (and this operation does not support dynamic shapes), but when I disabled that, the log persists. 

**My question is also, what kind of improvement should I expect if this operation is supported?**

**Describe the expected behaviour**
I think a lot of applications are using Resizing on the input, and from my research [ONNX](https://github.com/onnx/onnx/blob/main/docs/Operators.md#resize)  and [Tesnorrt](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/classnvinfer1_1_1_i_resize_layer.html) is supporting this operation. I also checked that ``tf.resize`` via nearest neighbour interpolation is supported which gives me no indication why it is not working. 

**Standalone code to reproduce the issue**
I was trying to create a collab, but it is a nightmare to set up TensorRT. Here are my tries and standalone code for script which trains a simple model, saves it and then optimizes it via TFTRT. 
- Google Colab: [link](https://colab.research.google.com/drive/1K-6Qoeo-3GxINUJw6Xi3N_6V0y0SHBON?usp=sharing)
- Python script:  [link](https://gist.github.com/rpytel1/de52d7e3116c6d3da5c7bd3f9e65a738)

**Other info / logs**:
Unsupported comment looks like this: 
<img width="1016" alt="Screenshot 2022-02-09 at 11 57 59" src="https://user-images.githubusercontent.com/12116282/153184823-51f0835b-7db1-4f70-a656-1309d723e879.png">

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
