### ISSUE TITLE
Batch processing for tflite_runtime

### ISSUE THREAD

**Issue by iaverypadberg** [tensorflow/tensorflow#54331]
**System information**
- TensorFlow version (you are using): 2.7.0
- Are you willing to contribute it (Yes/No): Yes

**Describe the feature and the current behavior/state.**
Batch processing of images in object detection models that are running in a tflite_runtime environment would be a great feature to add. Right now, it is possible to resize the input tensor to something like [x, h, w, c] where x is the number of images in a batch, and run it through the interpreter. However, the predictions come out looking like an image classification model, where there are probabilities but no bounding boxes.

**Will this change the current api? How?**
Yes. It will allow for developers to leverage the savings associated with batch processing.

**Who will benefit with this feature?**
Anyone who wants to break large images into x number of tiles and run inference on them all at once. This will greatly improve object detection capabilities on EdgeTPU devices.

**Any Other info.**
[Here](https://discuss.tensorflow.org/t/tflite-batch-inference-bug/7495) is a post I made on batch processing with an EfficientDet model.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
