### ISSUE TITLE
Specify what axes are independent in `batch_jacobian`, instead of it being always the first axis only. 

### ISSUE THREAD

**Issue by arifr1234** [tensorflow/tensorflow#54347]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.7.0
- Are you willing to contribute it (Yes/No): Yes

Hi everyone,

**Describe the feature and the current behavior/state.**

Currently, `GradientTape`'s `batch_jacobian` method assumes that `target[i,...]` is independent of `source[j,...]` for `j != i`.
See: https://www.tensorflow.org/api_docs/python/tf/GradientTape#batch_jacobian

Also from the docs: The function is logically equivalent to `tf.stack([self.jacobian(y[i], x[i]) for i in range(x.shape[0])])`.
The first dimension gets a special role, it "contains" the independent tensors whose Jacobian should be calculated.

However, the shape of independent tensors doesn't have to be of rank one, it may be multidimensional.
It may be nice to be able to specify where the line passes, between the independent tensors' shape and tensors whose jacobian we want to find.

This can be done today using `reshape` before and after the `batch_jacobian` call: merging the independent dimensions into the first dimension, applying `batch_jacobian`, and then reshaping back.
This is not so nice though :(

Here is an example of both a use case and the reshaping trick: https://colab.research.google.com/drive/1oXsmJl9GuQihJsxq0t3PusQ_-xBSiAyk

**Will this change the current api? How?**

Maybe the function can have an `axis` parameter to specify what dimensions to calculate the jacobian over, while the other dimensions will have the same "special" role the first dimension of `target` has now.

**Who will benefit with this feature?**

One use case may be calculating the batch_jacobian over the result of `meshgrid`, as I did to calculate the normals of a parametric surface (See colab notebook link above).

**Any Other info.**

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
