### ISSUE TITLE
Load tflite model meet The model allocation is null/empty

### ISSUE THREAD

**Issue by Ryuk17** [tensorflow/tensorflow#54385]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): no
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):  Linux Ubuntu 16.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: armv7
- TensorFlow installed from (source or binary): source 
- TensorFlow version (use command below): tensorflow-2.8.0
- Python version:
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source): arm-linux-gnueabihf-gcc
- CUDA/cuDNN version:
- GPU model and memory:

I built a libtensorflowlite_c.so with cmake
```
ARMCC_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations"
ARMCC_PREFIX=/tools/toolchain/gcc-x86_64_arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
cmake -DCMAKE_C_COMPILER=${ARMCC_PREFIX}gcc \
  -DCMAKE_CXX_COMPILER=${ARMCC_PREFIX}g++ \
  -DCMAKE_C_FLAGS="${ARMCC_FLAGS}" \
  -DCMAKE_CXX_FLAGS="${ARMCC_FLAGS}" \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -DCMAKE_SYSTEM_NAME=Linux \
  -DCMAKE_SYSTEM_PROCESSOR=armv7 \
  ../tensorflow/lite/c
  
cmake --build . -j  
```

however, when loading model by
```
TfLiteModel *model;
model = TfLiteModelCreateFromFile("model.tflite);
```

i meets the following problem
```
ERROR: Mmap of '5' at offset '0' failed with error '22'.  
ERROR: The model allocation is null/empty
```

here is my model:
[model.zip](https://github.com/tensorflow/tensorflow/files/8067674/model.zip)

**Comment by Ryuk17** [comment]
By the way, if i just use gcc to compile a lib for PC by
```
cmake ../tensorflow/lite/c ..
cmake --build . -j 
```
It's all fine.

**Comment by mohantym** [comment]
Hi @Ryuk17 ! Could  you check this [instructions](https://www.tensorflow.org/lite/guide/build_cmake_arm#build_for_armv7_neon_enabled) for ARMV7?

**Comment by Ryuk17** [comment]
Thanks for reply @mohantym. I have tried that instructions last month but I met problems as #54069. So I try current method to build the libtensorflowlite_c.so with the CMakeLists in /tensorflow/lite/c instead of  libtensorflow-lite.a with the CMakeLists in /tensorflow/lite.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
