### ISSUE TITLE
`tf.clip_by_norm` gives WRONG results when given negative `norm`

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54414]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf

x = tf.constant([[1, 2, 3, 4, 5]], dtype=tf.float32)
clip_norm = -6.0
x_clipped = tf.clip_by_norm(x, clip_norm, )
print(x)
print(x_clipped)

```
Outputs:
```
tf.Tensor([[1. 2. 3. 4. 5.]], shape=(1, 5), dtype=float32)
tf.Tensor([[-0.80903983 -1.6180797  -2.4271195  -3.2361593  -4.0451994 ]], shape=(1, 5), dtype=float32)
```

**Describe the current behavior**
`tf.clip_by_norm` has an argument `clip_norm` which should be a **positive** floating point. However, it does not perform any validity checking and can accept a negative value like `-6.0`.  When applied to a tensor, it produces wrong output silently.

**Describe the expected behavior**
`tf.clip_by_norm` should check the value of `clip_norm`.

**Comment by yongtang** [comment]
Added PR #54430 for the fix.

**Comment by gadagashwini** [comment]
Was able to reproduce the issue `tf-nightly-2.11.0-dev20220829`. Please find the gist [here](https://colab.research.google.com/drive/1gyQwlf1upuIl4SOEaRXmv0EoN3FfkpJ-?usp=sharing). Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
