### ISSUE TITLE
Improved MPI support for TensorFlow

### ISSUE THREAD

**Issue by rhc54** [tensorflow/tensorflow#54450]
**System information**
- TensorFlow version (you are using):  I am not a current TensorFlow user
- Are you willing to contribute it (Yes/No): I am willing to help develop it

**Describe the feature and the current behavior/state.**
I lead the PMIx initiative and have been the runtime lead on OpenMPI since its inception. We have been receiving a steady stream of problem complaints about MPI use from within TensorFlow, mostly due to problems with MPI wireup. We have developed methods for providing a more robust mechanism for MPI support of programming models that do not follow the traditional MPI "bulk synchronous" architecture. However, it has become apparent that TensorFlow is not using those methods.

I would like to initiate a collaboration to resolve these problems by helping TensorFlow developers utilize the dynamic programming model support for MPI. I have given many presentations on this subject, some of which are available as online videos, and am willing to give an in-person version to help kick things off. I can also help a bit with coding and am always available for advice and guidance. I acknowledge that we sometimes have to "tweak" our support to better fit a particular programming model, and I am willing to make such adjustments as they are uncovered.

**Will this change the current api? How?**
I don't believe there will be a need for such changes, but I defer that to the TensorFlow community once we identify what needs to be done.

**Who will benefit with this feature?**
All TensorFlow users should benefit as it will make MPI operations more robust

**Any Other info.**

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
