### ISSUE TITLE
Calling `tf.random.set_seed` with invalid seed breaks the Context!

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#54923]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.7.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
a = tf.random.uniform([1, 20]) # All good
print(a)
try:
  s = [[1,2]]
  tf.random.set_seed(s) # This will fail
except Exception as e:
  print("Error:"+str(e)) # Error:only size-1 arrays can be converted to Python scalars

print(tf.add(2,3)) # OK
b = tf.random.uniform([1, 20]) # AttributeError: 'Context' object has no attribute '_rng'

```

**Describe the current behavior**
[`tf.random.set_seed`](https://www.tensorflow.org/api_docs/python/tf/random/set_seed) should be called with an integer, however, although it has validity checking (which appeared to be working), calling `tf.random.set_seed([[1,2]])` will result in an error, but this would break some Context object and the random APIs are not working any more!
Error message is:
```
AttributeError: 'Context' object has no attribute '_rng'
```

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to reproduce this issue on colab using TF v2.8.0 and tf-nightly,please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/dc8a6e97ea66f06ffd041281e92b15ff/54923.ipynb).Thanks!

**Comment by wangpengmit** [comment]
Looks like if https://github.com/tensorflow/tensorflow/blob/3f878cff5b698b82eea85db2b60d65a2e320850e/tensorflow/python/eager/context.py#L497 fails, https://github.com/tensorflow/tensorflow/blob/3f878cff5b698b82eea85db2b60d65a2e320850e/tensorflow/python/eager/context.py#L489 should also be reverted.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
