### ISSUE TITLE
Custom operation on extracted volume patches

### ISSUE THREAD

**Issue by ShowStopperTheSecond** [tensorflow/tensorflow#55043]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are ): I'm using TensorFlow version 2.8
- Are you willing to contribute it (Yes/No):

**Describe the feature and the current behavior/state.**
Custom operation on sliding kernels on volumes of data would be really helpful. I know off the function _tf.extract_volume_patches_ but there are some drawbacks to this. It collects the patches but consumes lots of memory resource. I mean what I had in mind was performing some kind of custom operation on data collected through a sliding window and using this function would eventually lead to exhausting my available resource. And also it would be great to add a kernel mask to specify how the sampling would be performed. In short two I recommend more arguments to this function :
1) An argument to specify a function or a lambda to call upon every sampled window right after sampling and return and save the result instead of the sampled window itself
2) A sampling mask. Specifying which elements should be sampled ( I know it can be done using the this very function but again the constrain is the memory usage) 

**Will this change the current api? How?**
I think it wouldn't change anything 

**Who will benefit with this feature?**
This would be very helpful for image processing and feature extraction out of large volumes of data 

**Any Other info.**

**Comment by mohantym** [comment]
Hi @gadagashwini ! Could you please look at this feature request?

**Comment by gadagashwini** [comment]
@TheKiteFlier, Would you like to raise PR for proposed feature request?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
