### ISSUE TITLE
Build a static library

### ISSUE THREAD

**Issue by jefby** [tensorflow/tensorflow#5511]
Is there a way to ask the build system bazel to build a static library that one can link a program written using the C++ API against? My apologies for this simple question, but I am very unfamiliar with this build system. I try to add some code to tensorflow/tensorflow/BUILD

```
cc_binary(
    name = "libtensorflow_gpu.a",
    linkstatic = 1,
    linkshared = 0,
    deps = [
        "//tensorflow/c:c_api",
        "//tensorflow/core:tensorflow",
    ],
)
```

but it failed, it will show these log

>ERROR: /gruntdata/jefby/alicpp/external/tensorflowserving/tensorflowserving-50129ec0b407e5778282ee8d7610a9494cfcf6b2/tensorflow/tensorflow/BUILD:209:1: Linking of rule '//tensorflow:libtensorflow_gpu.a' failed: gcc failed: error executing command /usr/bin/gcc -o bazel-out/local-opt/bin/tensorflow/libtensorflow_gpu.a -pthread -Wl,-no-as-needed -B/usr/bin -B/usr/bin -pass-exit-codes '-Wl,--build-id=md5' '-Wl,--hash-style=gnu' -Wl,--gc-sections ... (remaining 1 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/usr/lib/gcc/x86_64-unknown-linux-gnu/4.9.2/../../../../lib64/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
collect2: error: ld returned 1 exit status
Target //tensorflow:libtensorflow_gpu.a failed to build

**Comment by drpngx** [comment]
It's looking for `main`. Try `cc_library`.

**Comment by jefby** [comment]
@drpngx compile no error, but i can't find  file libtensorflow_gpu.a

**Comment by aselle** [comment]
What's your exact build command?

**Comment by jefby** [comment]
@aselle bazel build -c opt //tensorflow:libtensorflow_gpu.a

**Comment by girving** [comment]
@jefby Where did you look?  It should be in `bazel-bin` (or one of the similar directories).

**Comment by girving** [comment]
@aselle Why did you remove awaiting response?

**Comment by asimshankar** [comment]
Alas, it is not currently possible to get bazel to build a single `.a` file that you can link against the C++ API. For details see https://github.com/bazelbuild/bazel/issues/1920 

Till that is resolved, the alternatives are either:
- Build the shared library (`bazel build -c opt //tensorflow:libtensorflow.so`) and link against and run with that available, OR
- Figure out a way to get the static library built using the Makefile (https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/makefile)

Our hope is that the bazel team will be able to figure out a solution and we can then add those targets.

Closing this issue since I believe the original query has been answered. Feel free to re-open or ping if you think closing it was a mistake. Thanks!

**Comment by jkuri** [comment]
I managed to build tensorflow statically.
- add `tensorflow/c/c_api.cc` above [that](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/contrib/makefile/Makefile#L534) line
- add `#define __ANDROID__ 1` in `tensorflow/c/c_api.cc` on the top to skip files that's missing header files
- run ./tensorflow/contrib/makefile/build_all_linux.sh

works for me on Ubuntu artful and MacOS High Sierra.

**Comment by dio** [comment]
@asimshankar WDYT of the provided sample in https://github.com/bazelbuild/bazel/issues/1920#issuecomment-509144086?
