### ISSUE TITLE
Simplify Android integration

### ISSUE THREAD

**Issue by errcw** [tensorflow/tensorflow#5513]
The current process of building an Android app that uses TensorFlow is unwieldy at best. The only available documentation is baked into the sole example app, which itself is embedded in the TensorFlow build system. Having prebuilt, drop-in Android libraries (or even the ability to build these libraries from source) would, I believe, significantly simplify the process.

I added my own BUILD definitions to build libraries I can easily drop into an Android Studio project (having experience with blaze made this much more tractable):
```
# Inside //tensorflow/contrib/android/BUILD

# Build the JAR.
# Ends up in //my-app/libs/libandroid_tensorflow_inference_java.jar
android_library(
    name = "android_tensorflow_inference_java",
    srcs = [":android_tensorflow_inference_java_srcs"],
)

# Build the SO.
# bazel build //tensorflow/contrib/android:libtensorflow.so \
#   --crosstool_top=//external:android/crosstool \
#   --host_crosstool_top=@bazel_tools//tools/cpp:toolchain \
#   --cpu=armeabi-v7a
# Ends up in //my-app/src/main/jniLibs/armeabi-v7a/libtensorflow.so
LINKER_SCRIPT = "//tensorflow/contrib/android:jni/version_script.lds"

cc_binary(
    name = "libtensorflow.so",
    srcs = [],
    copts = tf_copts(),
    linkopts = [
        "-landroid",
        "-ljnigraphics",
        "-llog",
        "-lm",
        "-z defs",
        "-s",
        "-Wl,--version-script",  # This line must be directly followed by LINKER_SCRIPT.
        LINKER_SCRIPT,
    ],
    linkshared = 1,
    linkstatic = 1,
    deps = [
        ":android_tensorflow_inference_jni",
        "//tensorflow/core:android_tensorflow_lib",
        LINKER_SCRIPT,
    ],
)
```

Moreover, if the Android example could rely on these libraries and therefore exist as a "standalone" project buildable by Android Studio I think the barrier to entry for TensorFlow on Android would be materially lower.

**Comment by andrewharp** [comment]
Thanks for the suggestion, implemented in 341da02072ee1c1093a5dca6ad45a1488306193d. 

Android apps may now either either add tensorflow/contrib/android:libtensorflow_inference.so to their native libs list or continue to just build the src filegroup into another .so (as the demo does). The loadLibrary call in TensorFlowInferenceInterface.java has a bit of smarts in it to automatically figure out if it needs to load libtensorflow_inference.so or not.

In either case tensorflow/contrib/android:android_tensorflow_inference_java should be used as a dep rather than including the src filegroup directly.
