### ISSUE TITLE
Tensor evaluating to None

### ISSUE THREAD

**Issue by hamzamerzic** [tensorflow/tensorflow#55184]
**System information**
- TensorFlow version (you are using): TF1 and TF2
- Are you willing to contribute it (Yes/No): Depends on the extent of the change necessary.

**Describe the feature and the current behavior/state.** 
I have TF datasets (both TF1 and TF2) that I would like to transform (dataset.map). Transforms package the datasets into a new structure and this structure might contain some None elements. If I try to make elements None, I get some "fetches errors" saying None is not supported. I'm wondering if there is a value that would evaluate to None? If not, could we add support for one?

Alternative would be to create an iterator and manually doing the map on fetched items, but that messes up external API (as we no longer work on tf.Datasets but Iterators instead).

**Will this change the current api? How?**
Not sure.

**Who will benefit with this feature?**
DeepMind internal.

**Any Other info.**

**Comment by mohantym** [comment]
Hi @hamzamerzic ! Could you please share a use case or a simple code snippet that explain the above feature request?

**Comment by hamzamerzic** [comment]
Thanks a lot for the quick reply! Here is an example:

```
from typing import NamedTuple, Optional

import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

import tensorflow_datasets as tfds


class DatasetOutputs(NamedTuple):
  image: np.array
  label: np.array
  metadata: Optional[np.array]


def _map_fn(data):
  return DatasetOutputs(
      image=tf.cast(data['image'], tf.float32) / 255.,
      label=data['label'],
      metadata=None)  # Problematic.


ds = tfds.load('mnist', split='train')
ds = ds.map(_map_fn)
data = next(iter(tfds.as_numpy(ds)))
```

This gives an error
`TypeError: Argument `fetch` = None has invalid type "NoneType". Cannot be None`

This simple reproducer seems to actually work well with TF2. But, in my particular use case the dataset that I'm trying to use seems to fail elsewhere when using TF2 though.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
