### ISSUE TITLE
You have two different versions of our example for tf.transpose(x) , only one of your tutorial examples  of the exact same thing is correct!

### ISSUE THREAD

**Issue by SynapticHorizons** [tensorflow/tensorflow#55182]
Thank you for submitting a TensorFlow documentation issue. Per our GitHub
policy, we only address code/doc bugs, performance issues, feature requests, and
build/installation issues on GitHub.

The TensorFlow docs are open source! To get involved, read the documentation
contributor guide: https://www.tensorflow.org/community/contribute/docs

## URL(s) with the issue:
Tutorial Links:
Correct example of x @ tf.transpose(x)
https://www.tensorflow.org/api_docs/python/tf/compat/v1/transpose?authuser=2

Incorrect example of x @ tf.transpose(x)
https://www.tensorflow.org/guide/basics?authuser=2

## Description of issue (what needs changing):
Need to decide which result it correct when performing the x @ tf.transpose(x)

### Clear description
You have two different outcomes for the same x @ tf.transpose(x) [command]
You can't have it both ways.

**Comment by chunduriv** [comment]
@SynapticHorizons,

Since `python >= 3.5` the `@` operator is supported (see [PEP 465](https://www.python.org/dev/peps/pep-0465/)). In TensorFlow, it simply calls the [tf.matmul()](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul)

>Incorrect example of x @ tf.transpose(x)
https://www.tensorflow.org/guide/basics?authuser=2

 No, here the example describes `matmul` operation between `x` and `tf.transpose(x)`. Please find the gist [here](https://colab.research.google.com/gist/chunduriv/23ce2ccf04a43aad61084fb25677d037/55182.ipynb) for reference. 

For more information please refer [here](https://www.tensorflow.org/api_docs/python/tf/linalg/matmul).Thanks!

**Comment by SynapticHorizons** [comment]
Chunduriv
Thanks for your response on the TensorFlow new syntax
doug

**Comment by chunduriv** [comment]
@SynapticHorizons,

If your issue resolved. Please feel free to close. Thanks!
