### ISSUE TITLE
`tf.gather_nd` and `tf.gather` have inconsistent type check for `batch_dims`

### ISSUE THREAD

**Issue by ArrowIntoTheSky** [tensorflow/tensorflow#55203]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow): Y
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device: N
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.8.0
- Python version: 3.8
- Bazel version (if compiling from source): N/A
- GCC/Compiler version (if compiling from source):N/A
- CUDA/cuDNN version: N/A
- GPU model and memory: N/A

**Standalone code to reproduce the issue**
```
import tensorflow as tf
params = tf.random.uniform([3, 1, 12, 64], dtype=tf.float32)
indices = tf.random.uniform([35, 2], minval=0, maxval=1, dtype=tf.int64)
batch_dims = False
tf.gather_nd(params, indices, batch_dims=batch_dims) # Pass
tf.gather(params, indices, batch_dims=batch_dims) # InvalidArgumentError
```
Detailed error message:
```
InvalidArgumentError: Value for attr 'Taxis' of bool is not in the list of allowed values: int32, int64
	; NodeDef: {{node GatherV2}}; Op<name=GatherV2; signature=params:Tparams, indices:Tindices, axis:Taxis -> output:Tparams; attr=batch_dims:int,default=0; attr=Tparams:type; attr=Tindices:type,allowed=[DT_INT32, DT_INT64]; attr=Taxis:type,allowed=[DT_INT32, DT_INT64]> [Op:GatherV2]
```

**Describe the current behavior**
In the above code, `batch_dims` is a `bool`, not a `int`. `tf.gather` complains about this type mismatch and throws `InvalidArgumentError`. However, `tf.gather_nd` would do implicit conversion and convert `False` to `0`. There is an inconsistency in the type checking.

**Describe the expected behavior**
Either allow implicit `bool`-`int` conversion in all cases, or throw an Error in all cases.

**Comment by yongtang** [comment]
Added a PR #55210 for the fix.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
