### ISSUE TITLE
Extracting Bazel installation

### ISSUE THREAD

**Issue by linrio** [tensorflow/tensorflow#5522]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
After I run `./configure`, why it stagnate in the step of `Extracting Bazel installation...` ? 

### Environment info
Operating System:
`Linux k20-1 2.6.32-358.el6.x86_64 #1 SMP Fri Feb 22 00:31:26 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux`

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
cuda 7.5
cuDNN 5

**Comment by sherrym** [comment]
@gunan, could you please comment? Thanks.

**Comment by gunan** [comment]
Doe it get stuck, or does it simply wait a while and then continue?
During configure, we run a bunch of bazel commands, and that is the first thing bazel prints if you run a bazel command.

**Comment by linrio** [comment]
@guman It remains staying at the step of **Extracting Bazel installation... ** now. Continuing about 11 hours. Does it get a stuck? How to confirm it?

**Comment by linrio** [comment]
@guman During configure, would the bazel download something from internet?

**Comment by drpngx** [comment]
`bazel` is the last thing which runs at the end of `configure`. Could you `strace bazel clean --expunge` and tell us what the last thing it's trying to do?

**Comment by gunan** [comment]
I think during configure there should not be a download.
Did you try killing the process and rerunning ./configure?

The command @drpngx provided might help us get some more information.
I think there are multiple steps where it can print "Extracting bazel installation".
Could you copy your full temrinal output to pastebin, or a similar site and share that with us?

**Comment by gunan** [comment]
Ping!
@linrio Could you try the suggestions above?

**Comment by gunan** [comment]
Closing the issue due to lack of debug information, and lack of activity.

**Comment by cournape** [comment]
FWIW, I have seen similar issues w/ a custom built bazel 0.5.1 on Rhel 6, and the issue was a dangling bazel process. If I make sure no bazel process is alive before I do configure, the issue goes away. Unfortunately, doing configure seems to always keep one dangling bazel process :(

Platforms details:

* rhel 6.5 on x86_64
* bazel 0.5.1 built against rhel 6's openjdk 1.8.0
* configure run as follows: `yes "" | ./configure`
* the operation hanging is always bazel clean.

It always appear when trying to configure a second time, and one can fixes the hang of bazel clean by either  `rm -rf ~/.cache/bazel` or killing the hanging bazel process.

Doing an strance on bazel clean shows that otherwise, bazel clean tries to connect to localhost, and hangs around there (I can get a full trace if that is deemed useful)

**Comment by ryanpeach** [comment]
Mine is stuck as well, any fix?

I'm on Ubuntu Subsystem for Windows if that effects anything.
