### ISSUE TITLE
Regression: TFLiteConverter changes output order again since 2.7

### ISSUE THREAD

**Issue by chao-camect** [tensorflow/tensorflow#55242]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
  No
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
   Ubuntu 20.04
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
   N/A
- TensorFlow installed from (source or binary):
   Binary
- TensorFlow version (use command below):
   2.7.1
- Python version:
   3.8.10
- Bazel version (if compiling from source):
   N/A
- GCC/Compiler version (if compiling from source):
   N/A
- CUDA/cuDNN version:
   11.2
- GPU model and memory:
   1080TI, 11G

**Describe the current behavior**
   tf.lite.TFLiteConverter.from_keras_model changes output order.

**Describe the expected behavior**
   Should keep the same order as the keras model.

- Do you want to contribute a PR? (yes/no):
  No

**Standalone code to reproduce the issue**
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

This is a regression bug. Please find an example here: https://github.com/tensorflow/tensorflow/issues/33303

**Comment by mohantym** [comment]
Hi @chunduriv ! Could you please look at this issue ? It is replicating in  [2.7 ](https://colab.sandbox.google.com/gist/mohantym/497e7ad863352c438687735dd0b4ea08/github_33303.ipynb#scrollTo=lV0UZ3IMXJie), [2.8 ](https://colab.sandbox.google.com/gist/mohantym/11f85642afdccf2e17053f71eb9dda41/github_33303.ipynb#scrollTo=9rUgGQnje2Dn)and [nightly](https://colab.sandbox.google.com/gist/mohantym/11f85642afdccf2e17053f71eb9dda41/github_33303.ipynb#scrollTo=9rUgGQnje2Dn) ( 2.9.0dev) .Thanks!

**Comment by karimnosseir** [comment]
Hi @chao-camect 

The issue is that TFLite converter uses saved model underneath, saved model doesn't guarantee order/names of tensors when loading the model, and that causes the issue.
Actually if you searched github you will even find other issues on older TF releases.

How to fix it ?
Because of this ordering / naming issue, TFLite now supports signature concept so you don't need to care about the tensors order or the tensor name.
Instead you deal with the defined signature on the model and the input / output names.
The mapping between the readable names and the actual tensors is done by TFLite and you don't need to care about them changing if the implementation underneath caused any order changes.

An example of using signatures

```
# Load the TFLite model in TFLite Interpreter
interpreter = tf.lite.Interpreter('/tmp/my_mode.tflite')

# If the model has only  1 signature defined
# then it will return it by default.
# If there are multiple signatures then we can pass the name as an argument.
my_signature = interpreter.get_signature_runner()

# my_signature is callable with input as arguments.
output = my_signature(x=tf.constant([1.0], shape=(1,10), dtype=tf.float32))
# 'output' is dictionary with all outputs from the inference.
# Assuming we named it in the original model as 'result' we can then pass it here.
print(output['result'])
```

See more details [here](https://www.tensorflow.org/lite/guide/inference#load_and_run_a_model_in_python) and API for other models.
Please let us know if you are having any issues.
