### ISSUE TITLE
tf.random.poisson hangs on nan input

### ISSUE THREAD

**Issue by jacksonloper** [tensorflow/tensorflow#55243]
Running on colab.research.google.com (`v2.8.0-0-g3f878cff5b6` at time of writing).

Looking at this code.

```
import tensorflow as tf
import math

print(tf.version.GIT_VERSION, tf.version.VERSION)

for lam in [3.2,-3.2,math.inf,-math.inf,math.nan]:
  print(lam,tf.random.poisson((1,),tf.convert_to_tensor(lam).numpy()))

```

**Describe the current behavior**

`tf.random.poisson` currently seems to handle nonsensical input as follows
- Negative values --> return 0
- +infinite values --> return infinity
- -infinite values --> return 0
- nan values --> freeze program completely (presumably running some rejection sampling algorithm forever??)

All of these seem okay except the last one.  

**Describe the expected behavior**

I have no strong opinions here.  I suppose my intuition would be 
- Negative values --> return nan
- +infinite values --> return infinity
- -infinite values --> return nan
- nan values --> return nan

But there may be good reasons for other behavior.  

At minimum, I suppose something should be added to the documentation indicating what expected behavior is (or that behavior is undefined in some cases).

**Comment by tilakrayal** [comment]
@chunduriv ,
I was able to reproduce the issue in tf v2.8, v2.7 and nightly.Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/aa2046d9316bb90d5a6356601133b843/untitled249.ipynb).

**Comment by dlibk** [comment]
This problem remains on tensorflow 2.15.0. Please check the code below.
```python
input = tf.constant(-1, dtype='int64')
p = tf.constant(np.nan, dtype='float64')

out = tf.random.poisson(shape=input.shape, lam=p, dtype=tf.float32)  # Program is frozen here.
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
