### ISSUE TITLE
AttributeError: 'module' object has no attribute 'dtypes'

### ISSUE THREAD

**Issue by sh1ng** [tensorflow/tensorflow#5525]
version r0.11

python 2

Mac OS

gender = tf.contrib.layers.sparse_column_with_integerized_feature(column_name="sex",
                                                                      bucket_size=2, dtype=tf.dtypes.int16)

  File "/Users/sh1ng/Projects/santander/nn/simple.py", line 220, in <module>
    tf.app.run()
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/Users/sh1ng/Projects/santander/nn/simple.py", line 216, in main
    train_and_eval()
  File "/Users/sh1ng/Projects/santander/nn/simple.py", line 208, in train_and_eval
    m = build_estimator(model_dir)
  File "/Users/sh1ng/Projects/santander/nn/simple.py", line 75, in build_estimator
    bucket_size=2, dtype=tf.dtypes.int16)
AttributeError: 'module' object has no attribute 'dtypes'

**Comment by finbarrtimbers** [comment]
You can leave out the dtypes`: 

```{python}
gender = tf.contrib.layers.sparse_column_with_integerized_feature(column_name="sex", bucket_size=2, dtype=tf.int16)
```

**Comment by sherrym** [comment]
@sh1ng please let me know if using tf.int16 fixes your problem.

**Comment by sh1ng** [comment]
it's fixed thanks

**Comment by Alinadi23** [comment]
I encountered with this error about lambda function.

AttributeError: 'Lambda' object has no attribute 'dtype'

what do i do to solve this problems?

**Comment by gzygmontson13** [comment]
I had this issue as well but the file causing the problem was called "signal.py" in my case. Rather than saying "make sure you don't have a file in the directory called numbers.py", you must say something like "check any recent .py file you've added and try changing its name". When I had the issue I read your answer several times but I didn't pay much attention to it because I didn't have any file called "numbers.py"...
Beside this,I figured this out. The answer is that the file I was running was named numbers.py. This screws the whole thing up. If you have this problem check to make sure you don't have a file in the directory called numbers.py
Easy way to check is move the file with the import statement to a different directory and try running [it](https://malletandplane.com/).
