### ISSUE TITLE
Build TensorFlow Lite for iOS on macOS Mojave

### ISSUE THREAD

**Issue by raziel2k** [tensorflow/tensorflow#55268]
Hello,
I'm trying to build TensorFlow Lite 2.8.0 for iOS on an Intel MacBook Pro with macOS Monterey. 

I'm following [this link](https://www.tensorflow.org/lite/guide/build_ios?hl=en)

but whan I execute the command:

`bazel build --config=ios_fat -c opt //tensorflow/lite/ios:TensorFlowLiteC_framework`

I get this error:

```
ERROR: .../tensorflow/tensorflow/lite/ios/BUILD:104:21: Bundling Preprocessed_TensorFlowLiteC_framework failed: (Exit 127): bundletool failed: error executing command 
  (cd /private/var/tmp/_bazel_gcutri/7cb05f4ce32b1b08677be1af22c0dd6b/execroot/org_tensorflow && \
  exec env - \
  bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool bazel-out/applebin_ios-ios_armv7-opt-ST-36ad1e8d6baf/bin/tensorflow/lite/ios/Preprocessed_TensorFlowLiteC_framework-intermediates/bundletool_control.json)
Execution platform: @local_execution_config_platform//:platform
env: python: No such file or directory
```

It seems that python is not found when executing the script bundletool. I installed both python 3.9 and 2.7.

Please help

**Comment by yishuangP** [comment]
Hi, looks like this is a python location issue. When you ran [configure.py](https://github.com/tensorflow/tensorflow/blob/master/configure.py), did you specify the location of python? You should specify it, otherwise the default one is used.

One possible scenario is that python 3 is used, but it is finding `/usr/bin/python` folder. Find your python3 path with `whereis python3` and maybe create a symlink to it: `sudo ln -s /usr/bin/python3 /usr/bin/python`. Hope this could help!

**Comment by raziel2k** [comment]
Hi yishuangP,
thank you for your response. I have already tried to specify the location of python (trying different paths) but I don't think that's the problem since many python scripts are correctly executed before that problem occurs.

I have also already tried to create the symbolic link but it didn't help.

I tried to run the command `exec env - bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool` from command line and still got the problem but if I write `python bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool`, the script is executed (but I get a different error at runtime), so python is not found only when I use `exec env -`.

How can I solve this?

**Comment by yishuangP** [comment]
This is weird. I wonder if this is because you have two versions of python installed. And I think this is a bazel build issue. How about `python3 bazel-out/host/bin/external/build_bazel_rules_apple/tools/bundletool/bundletool`? Does it execute? `exec env -` clears the environment variables before executing. Can you try removing the old version?

**Comment by raziel2k** [comment]
Yes, that command executes without `exec env -`.

Anyhow, the problem is not related to the fact that I have python 2 installed because there was also before I installed it (actually, I installed python 2 to try to solve it).

I think, maybe, the problem is related to the fact that I have a fresh installation of macOS Mojave (that does not come with python pre-installed anymore) and I installed python 3.9 from the official web site. Maybe this setup is different from an update to Mojave from a previous version.

**Comment by yishuangP** [comment]
Hi is your problem resolved? Maybe the following commands could help 
 ```
 # Setup Python
  PYTHON_BIN_PATH=$(which python3)
  export PYTHON_BIN_PATH
  # Update /usr/bin/python3 for Bazel's host tool execution.
  sudo rm -f /usr/bin/python3
  sudo ln -s "${PYTHON_BIN_PATH}" /usr/bin/python3
```

**Comment by softfactory0911** [comment]
I also have a similar problem.
Unable to create symblic link in /usr/bin path on macOS.

`
exec env - .....
`
Because of that part, the environment variable disappears.
And if the environment variable disappears, python cannot be used, only python3 can be used.

This is my guess, but because of this I can't run bundletool during build.

Is there a way to fix the build other than bypassing the OS?

**Comment by sanghun8741** [comment]
I also have a similar problem.
Unable to create symblic link in /usr/bin path on macOS.

`
exec env - .....
`
Because of that part, the environment variable disappears.
And if the environment variable disappears, python cannot be used, only python3 can be used.

This is my guess, but because of this I can't run bundletool during build.

Is there a way to fix the build other than bypassing the OS?

**Comment by e7fendy** [comment]
I also have the similar issue.
Is it the problem of bazel 4? Someone mentioned it on https://stackoverflow.com/questions/71778867/bazel-build-fails-with-msg-env-python-no-such-file-or-directory-macos-monte

**Comment by yishuangP** [comment]
Can you try updating to bazel 5?

**Comment by sachinprasadhs** [comment]
@raziel2k , As per the below comment, could you please try in Bazel 5 and let us know if you still face an issue. Thanks!

> Can you try updating to bazel 5?
