### ISSUE TITLE
Opening GUIs on host machine using the TensorFlow docker image

### ISSUE THREAD

**Issue by caliari-italo** [tensorflow/tensorflow#55346]
Hello everyone 

I'm using TensorFlow gpu docker image and it is working just fine on my python scripts. 
My issue is trying to open some GUI applications like spyder-ide.

The _Dockerfile_ used to build the image is:
```
FROM tensorflow/tensorflow:latest-gpu
RUN apt-get update
RUN apt-get install python3-opencv libasound2 -y
RUN pip install --upgrade pip
RUN pip install spyder
RUN pip install numpy
RUN pip install pandas
RUN pip install sklearn
RUN pip install matplotlib
WORKDIR /home
```

and the docker arguments used to start the image are
```
sudo docker run -it \
    --gpus all \
    --env="DISPLAY" \
    --net=host \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -v $PWD:/home imagename/imagename \
    spyder
```

But I'm getting the following error...

```
root@350X:/home# spyder
Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted (core dumped)
```

Any ideas how could I open GUIs on the host machine using the TensorFlow docker image ?
I tried reinstalling the application and getting these plugins but had no success in opening GUIs.

**Comment by tilakrayal** [comment]
@caliari-italo ,
Can you please take a look at this link [1](https://github.com/google/mediapipe/issues/1373), [2](https://github.com/google/mediapipe/issues/1373) and [3](https://github.com/tensorflow/tensorflow/issues/16658) with the similar error.It helps.Thanks!

**Comment by caliari-italo** [comment]
The problem was solved following https://github.com/spyder-ide/spyder/issues/17542#issuecomment-1077946055

**Comment by tilakrayal** [comment]
@caliari-italo ,
In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem
