### ISSUE TITLE
TensorFlow android throw java.lang.OutOfMemoryError when building project, but there's free 20GB memory.

### ISSUE THREAD

**Issue by shps951023** [tensorflow/tensorflow#55368]
![image](https://user-images.githubusercontent.com/12729184/160032113-66a91d3c-81cf-4ac0-a5e7-f4046f5da39c.png)

My process:
- Clone project from https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/android/test
- Click build button (My PC memory : 11.7/31.9 GB (37%))
- When building the memory only use 2GB, then it throwed error : 
```
:packageDebug' `
> A failure occurred while executing com.android.build.gradle.internal.tasks.Workers$ActionFacade
> java.lang.OutOfMemoryError (no error message)
```
- My PC has hyper-v

Did I miss some key steps?  Really appreciate Tensorflow team's efforts.

**Comment by tilakrayal** [comment]
@shps951023 ,
In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem
