### ISSUE TITLE
Feature request: Add left_side flag and functionality to tf.linalg.triangular_solve

### ISSUE THREAD

**Issue by jmmarschke** [tensorflow/tensorflow#55371]
**System information**
- TensorFlow version (you are using): 2.8.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
Add `left_side` flag and functionality to `tf.linalg.triangular_solve` as described in documentation for XLA TriangularSolve:
https://www.tensorflow.org/xla/operation_semantics?hl=sl&skip_cache=true#triangularsolve

**Will this change the current api? How?**
It will add an additional flag, which can be defaulted to maintain current behavior.

**Who will benefit with this feature?**
Those who want to solve triangular systems without a bulk of unnecessary transpose operations.

**Comment by tilakrayal** [comment]
@jmmarschke ,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thanks!

**Comment by jmmarschke** [comment]
**Current functionality**
`output = tf.linalg.triangular_solve(matrix, rhs, lower=True, adjoint=False, name=None)`

With `matrix` either upper or lower triangular, solves equations of the form:

`matrix*output = rhs`


**Proposed feature**
`output = tf.linalg.triangular_solve(matrix, rhs, lower=True, adjoint=False, name=None, left_side=True)`


With `matrix` either upper or lower triangular, 
solves:
` matrix * output = rhs` (if `left_side == True`, default, same as above) 

or solves:
` output * matrix = rhs` (if `left_side==False`, new functionality)

**Use Case**
Currently, one can arrive at the same result by permuting the inputs beforehand and then reverse-permuting the result. However, since the cleaner, more performant approach already appears to be implemented in XLA, it would make sense to expose this through `tf.linalg.triangular_solve`.

Old code:
```
SyyT    =   tf.transpose(Syy)
KSyy_T  =   tf.transpose(KSyy)

K_T     =   tf.linalg.triangular_solve(SyyT, KSyy_T, lower=False)

K       =   tf.transpose(K_T)
```

New code:
```
K       =   tf.linalg.triangular_solve(Syy, KSyy, lower=False, left_side=False)
```

Cleaner, and more performant, since (even under the hood) it circumvents three unnecessary transpose operations.

**Comment by Srikeshram** [comment]
I would like to work on this feature. Can you please assign it to me?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
