### ISSUE TITLE
Pylint phantom checks

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#55442]
Some check that we have enabled in `.pylintrc` are silently not executed anymore.

https://github.com/tensorflow/tensorflow/blob/fa6895a1564f14f488c5019039e3f0addef49f32/tensorflow/tools/ci_build/pylintrc#L48
`python -m pylint --list-msgs | egrep "indexing-exception|old-raise-syntax|W0311|W0312|C0330|C0301|C0326|W0611|W0622"`

We have only 4/9 explicitly enabled checks that are still valid: 
```
:line-too-long (C0301): *Line too long (%s/%s)*
:bad-indentation (W0311): *Bad indentation. Found %s %s, expected %s*
:unused-import (W0611): *Unused %s*
:redefined-builtin (W0622): *Redefining built-in %r*
```
It could require `black` to support some of these check again. 
Please check https://github.com/tensorflow/tensorflow/pull/55396#issuecomment-1083685885

/cc @mihaimaruseac @angerson @mdanatg

**Comment by bhack** [comment]
Now is going to fail also the CI:
https://source.cloud.google.com/results/invocations/4fc80853-f2a6-4670-b33f-eafd25542c43/targets/pkg%2Fcode_check_changed_files/tests

```
=============================
tensorflow/tools/ci_build/pylintrc:1:0: E0015: Unrecognized option found: profile, cache-size, files-output, comment, zope, required-attributes, bad-functions, disable-report, no-space-check, ignore-iface-methods, short-func-length, deprecated-members, ignore-exceptions, copyright (unrecognized-option)
```

**Comment by bhack** [comment]
Do we plan to switch to pyink:
https://github.com/google/flax/pull/2608

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Also the PR's which were raised for the similar issue have been reviewed and merged. 
https://github.com/tensorflow/tensorflow/pull/55453


The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.
