### ISSUE TITLE
TFLite performance difference between python and c++

### ISSUE THREAD

**Issue by BhaskarsarmaP** [tensorflow/tensorflow#55476]
**System information**
- Have I written custom code (as opposed to using a stock example script provided in TensorFlow):
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10 Linux buster
- Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
- TensorFlow installed from (source or binary): 2.8.0
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.3
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source): 8.3.0
- CUDA/cuDNN version: NA
- GPU model and memory: NA

 TF 2.0: `python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"`
v2.8.0-rc1-32-g3f878cff5b6 2.8.0

**Describe the current behavior**

Python performance of tflite is much better than C++.
When number of threads is set to -1, Not getting best performance in C++.
Manual setting the number of threads to max is giving improvement in C++ API performance and still its less than python.
As per this issue(https://github.com/tensorflow/tensorflow/issues/46272) It is mentioned, number of threads in c++ are automatically set to -1 and all threads will be used, But its not happening and there is performance difference.
Performance is not modified proportionately based on the threads. Suppose when threads are set to 2, we are not getting 2x performance than threads as 1

**Describe the expected behavior**
Match the performance of python with C++.
Give an API or directly automate the setting the threads without manual change.
What is the backend used for python and C++ ? Are they same ?
Can we expect the performance proportionately based on the threads. Suppose when threads are set to 2, can we expect 2x performance than 1 thread ?

**Standalone code to reproduce the issue**
Python TFlite--

`` python3 tfliteversionprofile_latest_singleiteration.py ``

2.8.0
Time elapsed during the process:%d ms 99.971158

`` python3 tfliteversionprofile_latest_singleiteration_multicores.py ``

.2.8.0
Time elapsed during the process:%d ms 85.076159
There is clear change in performance when number of threads are set to max. 
My cpu has 6 cores and 2 threads per core, so set to 12.

C++ TFlite-- 

But when c++ API is used there is huge impact in performance , Using example label image.

when -1 is set as number of threads.
`` bazel-4.2.1 build -c opt //tensorflow/lite/examples/label_image:label_image ``

when -1 (number of threads) is set in label_image.h present in tensorflow/lite/examples/label_image, 

`` bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model detect.tflite --labels labelmap.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp `` 

INFO: Loaded model detect.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: invoked
INFO: average time: 323.143 ms
INFO: 0.00389769: 3 car
INFO: 0.0038741: 2 bicycle

 
when 12 is set as number of threads.
`` bazel-4.2.1 build -c opt //tensorflow/lite/examples/label_image:label_image ``

when 12 (number of threads) is set in label_image.h present in tensorflow/lite/examples/label_image, 

`` bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model detect.tflite --labels labelmap.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp ``

INFO: Loaded model detect.tflite
INFO: resolved reporter
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: invoked
INFO: average time: 141.746 ms
INFO: 0.00389769: 3 car
INFO: 0.0038741: 2 bicycle

Attached the model, scripts and labels file.,
[labelmap.txt](
[New folder.zip](https://github.com/tensorflow/tensorflow/files/8405110/New.folder.zip)
https://github.com/tensorflow/tensorflow/files/8405102/labelmap.txt)
[labelmap.txt](https://github.com/tensorflow/tensorflow/files/8405103/labelmap.txt)

**Comment by multiverse-tf** [comment]
> **Describe the expected behavior** Match the performance of python with C++. Give an API or directly automate the setting
> the threads without manual change. What is the backend used for python and C++ ? Are they same ? Can we expect the 
> performance proportionately based on the threads. 
> Suppose when threads are set to 2, can we expect 2x performance than 1 thread ?

1. Python binding actually uses the C++ implementation of Tensorflow Lite. Considering the Python runtime overhead itself, I would expect, under the same running environment, the Python performance should be no better than that of the C++ one.
2. Linear scaling w/ threads isn't guaranteed at all in practice due to various factors. For example, if some TFLite op in the graph isn't parallelized, then running with multiple threads on the op doesn't help at all. In addition, the multithreading performance could suffer if there's resource contention on CPU cores.

Btw, you could use the [TFLite benchmark tool](https://www.tensorflow.org/lite/performance/measurement) to measure the performance of your model. In practice, the overall performance could be further impacted by other components of your inference binary, including the data pre-processing, data post-processing etc.

**Comment by BhaskarsarmaP** [comment]
But based on the attached files, Its clearly having difference between python and C++

**Comment by BhaskarsarmaP** [comment]
I have run the benchmark tool for tensorflow 2.8.0 and still got less performance than python.
![Capture2](https://user-images.githubusercontent.com/37923435/162717140-c805cdaf-ebd8-43cf-a16d-4aa1d4a7d902.PNG)
![Capture1](https://user-images.githubusercontent.com/37923435/162717148-881f69cd-4cfb-4cba-8562-5de0c6679e83.PNG)

**Comment by multiverse-tf** [comment]
> I have run the benchmark tool for tensorflow 2.8.0 and still got less performance than python. ![Capture2](https://user-images.githubusercontent.com/37923435/162717140-c805cdaf-ebd8-43cf-a16d-4aa1d4a7d902.PNG) ![Capture1](https://user-images.githubusercontent.com/37923435/162717148-881f69cd-4cfb-4cba-8562-5de0c6679e83.PNG)

Could you also paste the performance of the corresponding Python program here? In addition, what are the performances when num_threads is set to 1, 2, 4 respectively? Thx!

Btw, which hardware platform are you running the performance test?

**Comment by BhaskarsarmaP** [comment]
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10 Linux buster
- TensorFlow installed from (source or binary): 2.8.0
- TensorFlow version (use command below): 2.8.0
- Python version: 3.7.3
- Bazel version (if compiling from source): 4.2.1
- GCC/Compiler version (if compiling from source): 8.3.0

`cat /sys/devices/system/cpu/smt/active`
      1
      Hyper threading is enabled.

` sudo dmidecode -t processor | grep Count`
	Core Count: 6
	Thread Count: 12

For C++, I profiled using benchmark tool and also with label example, with loop count set to 100 and warm-up runs zero and threads ranging from -1 to 12 and  >12 .

`bazel-4.2.1 build -c opt //tensorflow/lite/examples/label_image:label_image`
`bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model detect.tflite --labels labelmap.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp`

### C++ (2.8.0)
-1 -- 306.917 ms  
0  -- 122.151 ms (Randomly getting cores )
1  -- 293.365 ms  
2  -- 155.565 ms 
3  -- 105.54 ms  
4  -- 82.3551 ms
5  -- 98.8991 ms
6  -- 64.5327 ms 
7  -- 103.385 ms 
8  -- 98.1083 ms  
9  --  87.2203 ms 
10 --  76.0722 ms 
11 --  63.1864 ms 
12 --  71.3735 ms
13 -- 131.074 ms  (Randomly getting cores when greater than threads given)
14 -- 133.658 ms 
15 -- 134.247 ms

### Python Performance for threads (2.8.0) (Ran for 100 runs)

TFLite 2.8.0 Python

-1 -- unable to set
0 -- unable to set
1 --  67.28704053 ms
2 --  37.27101533 ms
3 --  24.89689852 ms
4 --  19.27222278 ms 
5 --  16.82612416 ms
6 --  14.75332775 ms 
7 --  26.53925619 ms
8 --  22.71062904 ms
9 --  20.09229901 ms
10 -- 17.41771392 ms
11 -- 14.67389033 ms
12 -- 14.79799008 ms
13 --  81.4597831 ms (Randomly pick threads)
14 --   76.92194408 ms 
15 --  76.67167669 ms

These are the observations when all are closed in my pc except profiler.
I have the following queries


**1) As per this issue(https://github.com/tensorflow/tensorflow/issues/46272) It is mentioned when the number of threads in c++ is set to -1 all threads will be used, But it's not happening and there is a clear performance difference.

2) What is meant by threads set as zero, what is ideal behavior in c++? 

3) Why the performance in C++ is random, and in my case, there is a drop in performance after 6 threads (My pc has 6 cores) and an increase happened when it reaches almost 11 or 12 threads. Is this behavior expected? There is no proportional increase in performance w.r.t to threads set .

This is similar even in python until 6 there is an increase, But there is a drop in performance, and eventually, performance increases when it reaches the max number of threads which is 12. What is the reason behind it?**


lscpu info file and scripts for python benchmarking and model are attached in this thread.

**Comment by BhaskarsarmaP** [comment]
Any update

**Comment by multiverse-tf** [comment]
> * OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Debian 10 Linux buster
> * TensorFlow installed from (source or binary): 2.8.0
> * TensorFlow version (use command below): 2.8.0
> * Python version: 3.7.3
> * Bazel version (if compiling from source): 4.2.1
> * GCC/Compiler version (if compiling from source): 8.3.0
> 
> `cat /sys/devices/system/cpu/smt/active` 1 Hyper threading is enabled.
> 
> ` sudo dmidecode -t processor | grep Count` Core Count: 6 Thread Count: 12
> 
> For C++, I profiled using benchmark tool and also with label example, with loop count set to 100 and warm-up runs zero and threads ranging from -1 to 12 and >12 .
> 
> `bazel-4.2.1 build -c opt //tensorflow/lite/examples/label_image:label_image` `bazel-bin/tensorflow/lite/examples/label_image/label_image --tflite_model detect.tflite --labels labelmap.txt --image tensorflow/lite/examples/label_image/testdata/grace_hopper.bmp`
> 
> ### C++ (2.8.0)
> -1 -- 306.917 ms 0 -- 122.151 ms (Randomly getting cores ) 1 -- 293.365 ms 2 -- 155.565 ms 3 -- 105.54 ms 4 -- 82.3551 ms 5 -- 98.8991 ms 6 -- 64.5327 ms 7 -- 103.385 ms 8 -- 98.1083 ms 9 -- 87.2203 ms 10 -- 76.0722 ms 11 -- 63.1864 ms 12 -- 71.3735 ms 13 -- 131.074 ms (Randomly getting cores when greater than threads given) 14 -- 133.658 ms 15 -- 134.247 ms
> 
> ### Python Performance for threads (2.8.0) (Ran for 100 runs)
> TFLite 2.8.0 Python
> 
> -1 -- unable to set 0 -- unable to set 1 -- 67.28704053 ms 2 -- 37.27101533 ms 3 -- 24.89689852 ms 4 -- 19.27222278 ms 5 -- 16.82612416 ms 6 -- 14.75332775 ms 7 -- 26.53925619 ms 8 -- 22.71062904 ms 9 -- 20.09229901 ms 10 -- 17.41771392 ms 11 -- 14.67389033 ms 12 -- 14.79799008 ms 13 -- 81.4597831 ms (Randomly pick threads) 14 -- 76.92194408 ms 15 -- 76.67167669 ms
> 
> These are the observations when all are closed in my pc except profiler. I have the following queries
> 
> 1. **As per this issue([use of interpreter-->SetNumThreads. Do we need to invoke setNumThreads always to improve performance #46272](https://github.com/tensorflow/tensorflow/issues/46272)) It is mentioned when the number of threads in c++ is set to -1 all threads will be used, But it's not happening and there is a clear performance difference.**

When it's set to -1, in general, the actual number of threads used is 1 because it's the safest choice on mobile phones in practice so that we could avoid resource contention with other activities on the phone.

> 2. **What is meant by threads set as zero, what is ideal behavior in c++?**

When it's set to 0, it should mean to disable multithreading as noted [here](https://github.com/tensorflow/tensorflow/blob/7a99ce11636fb7e0c974d4d9b8b5dbff7f259c87/tensorflow/lite/interpreter.h#L541-L559).

> 3. **Why the performance in C++ is random, and in my case, there is a drop in performance after 6 threads (My pc has 6 cores) and an increase happened when it reaches almost 11 or 12 threads. Is this behavior expected? There is no proportional increase in performance w.r.t to threads set .**
> 
> **This is similar even in python until 6 there is an increase, But there is a drop in performance, and eventually, performance increases when it reaches the max number of threads which is 12. What is the reason behind it?**
> 

I think this is largely because of the over-subscription on the underlying cores (i.e. severe computing resource contention) by the computing inference threads. As a result, performance decrease is expected.

> 4. **Can we expect a proportional increase in performance based on the threads set?**

I hope my [earlier comment](https://github.com/tensorflow/tensorflow/issues/55476#issuecomment-1089729503) could clarify this.

> 
> lscpu info file and scripts for python benchmarking and model are attached in this thread.

Lastly, regarding the intriguing performance difference reported here, after looking at the additional details you've provided, I'm now thinking whether it could be caused by the compiler or not as there's a performance-difference issue before that's solved by upgrading the compiler to gcc 9.0+ (you used gcc 8.3 here in this case?).  

My guess is based on the assumption that you compiled the C++ lib/binary from source while using the Python library from the official TF 2.8.0 release.

To help validate the guess, could you try the following (from being easy to being complex):
* Download the [latest linux_x86-64 benchmark binary](https://storage.googleapis.com/tensorflow-nightly-public/prod/tensorflow/release/lite/tools/nightly/latest/linux_x86-64_benchmark_model) to benchmark the detect model? More options for the benchmark tool could be found [here](https://www.tensorflow.org/lite/performance/measurement#download_or_build_the_binary).
* As your model is a quantized model (uint8), could you try run with the corresponding non-quantized fp32 model? Just wondering the performance difference also occurs with the fp32 models.
* Also build the TFLite python library from source using the same building env? Or use the TF dev/nightly docker (which includes newer compilers) to build the lib/binary?

Again, many thanks for reporting the issue and the detailed description earlier!

**Comment by NobuoTsukamoto** [comment]
label_image (C ++) doesn't seem to have xnnpack delegate enabled.
You must specify the `xnnpack_delegate` option.
(`INFO: Applied XNNPACK delegate.` Is logged)
However, the xnnpack delegate does not take effect when the option is specified due to a label_image issue (#56367). Perhaps the python benchmark has xnnpack delegate enabled.

I think you need to make sure that the xnnpack delegate option is working properly.

**Comment by sachinprasadhs** [comment]
@BhaskarsarmaP , Could you please try the solution mentioned here and let us know if this works for you.

> label_image (C ++) doesn't seem to have xnnpack delegate enabled. You must specify the `xnnpack_delegate` option. (`INFO: Applied XNNPACK delegate.` Is logged) However, the xnnpack delegate does not take effect when the option is specified due to a label_image issue (#56367). Perhaps the python benchmark has xnnpack delegate enabled.
> 
> I think you need to make sure that the xnnpack delegate option is working properly.

**Comment by terryheo** [comment]
FYI, https://github.com/tensorflow/tensorflow/issues/56367 is fixed

**Comment by BhaskarsarmaP** [comment]
Will update this by testing with xnnpack_delegate

**Comment by zdarova** [comment]
was this resolved?

**Comment by Byte247** [comment]
Have the same error: https://github.com/tensorflow/tensorflow/issues/110160. 

Did anyone find a solution?
