### ISSUE TITLE
Serialize TF graph after XLA compilation 

### ISSUE THREAD

**Issue by pemoi1982jpm** [tensorflow/tensorflow#55520]
**System information**
- TensorFlow version (you are using): 2.8.0

**Describe the feature and the current behavior/state.**
Not available
**Will this change the current api? How?**
Potentially

Hi, I was wondering if there is a way to serialize a TF graph after compiling with XLA. Typically we can serialize a graph as a proto file and load it afterwards. However, the graph execution is slow the first time we run it after loading presumably due to JIT compilation. Is there a way to store the graph so that there is no performance overhead during the first run after loading it? 

Consider the following example: 
[https://gist.github.com/pemoi1982jpm/bf3e6afe90551a824d0f9e9baa42d041](https://gist.github.com/pemoi1982jpm/bf3e6afe90551a824d0f9e9baa42d041)

So the question:  Is there a way to serialize the TF graph in a way that the first run is also fast after restoring it?  

In principle the graph was already compiled using XLA, Can we store it in some format so that XLA doesn’t have to compile it again? 

Any help or guidance would be really helpful.

**Comment by pemoi1982jpm** [comment]
Is there any update on this issue?
Thank you

**Comment by pemoi1982jpm** [comment]
Please,
Any progress or update on this issue?

**Comment by amitvarshney00** [comment]
I am also interested in this question. Any update or guidance from the Tensorflow would be really helpful.

**Comment by wangpengmit** [comment]
There are 2 stages of compilation involving 3 languages: TF -> XLA -> binary. Do you want to serialize XLA or binary?

**Comment by pemoi1982jpm** [comment]
Thanks for the info @wangpengmit 
Ideally we would like to eliminate any overhead when running the graph after loading (even in the first iteration), so we would like to serialize the binary.
Is there a way to serialize/deserialize the binary?

In any case, what is the most optimal way to serialize/deserialize XLA? I am also interested about this.

**Comment by wangpengmit** [comment]
The current situation is that neither XLA nor the binary is a serializable language in TF's policy. TF's serialization (SavedModel) is designed to be a long lasting artifact that's guaranteed to work at least during TF2's lifetime. Neither XLA nor the binary is a stable language that meets the requirement. We are exploring having a stable (thus serializable) version of XLA, but that'll be a long-term project. We don't have any plan for a stable version of the binary currently.

Perhaps a "persistent compilation cache" (instead of a long-lasting serialization) is what you are asking for? It won't be guaranteed to work across TF or XLA versions but should work within the same version.

**Comment by amitvarshney00** [comment]
Thank you @wangpengmit. "Persistent compilation cache" sounds interesting. What would be the best way to create it?

**Comment by wangpengmit** [comment]
Unclear yet. It's still a big new feature and will take a long time to realize.

**Comment by amitvarshney00** [comment]
Thanks @wangpengmit. I understand that official support for XLA/binary serialization will take a long time. Do you think it would be possible for me to somehow achieve the persistent cache type functionality in an ad-hoc way? I am just looking for something that works, even if it is not the most elegant way.

**Comment by wangpengmit** [comment]
We don't normally recommend usage outside the public APIs, but I'll rely on @smit-hinsu from the TF2XLA team to answer whether there is a quick hack to achieve persistent compilation cache.

**Comment by smit-hinsu** [comment]
Could you describe the setup and motivation in more detail? Is this for training or serving? What devices are involved? What's the use-case? etc.

**Comment by amitvarshney00** [comment]
Hi @smit-hinsu - The following are the details of the use case:

We want to express a set of numerical algorithms as TensorFlow computational graphs. Once the graph is built and JIT-compiled, we will use it repeatedly with different inputs. In that context, this is a **serving** use case. We also want the flexibility to build the graph on one machine and share it with other users. We are currently using `tf.saved_model.save` to serialize the graph and
1. Load the graph back at a later time
2. Share with other machines/users

However, after we load the serialized graph, the first run is slow because the graph is compiled again. Our graphs is very large and JIT compilation takes a long time. This is why we are interested in exploring options to directly serialize the binary so that we do not have to incur the overhead of compilation every time we load the graph. Also we have a large number of graphs for various kinds of algorithms/models. Out target devices are CPU and GPU.

Let me know if that helps.

**Comment by smit-hinsu** [comment]
Please check out model warmup that could do eager initialization. You could use this or implement a similar solution.
https://www.tensorflow.org/tfx/serving/saved_model_warmup

**Comment by amitvarshney00** [comment]
Thanks @smit-hinsu. I looked up on `saved_model_warmup`, and it appears that it runs a few inferences at the time of loading the model. Unfortunately, this doesn't solve our use case because we will incur the JIT-compilation overhead during the model warmup. We are looking for ways to save the binary that is produced **after** the JIT compilation. This way we can completely avoid the JIT overhead every time the model is loaded.

Please note that we understand this is not officially supported, however we are open to any ad-hoc or "hacky" solution. Any pointers would be deeply helpful.

**Comment by wangpengmit** [comment]
CCing @hfan and @qqfish who are investigating a similar feature request.

**Comment by amitvarshney00** [comment]
Hi @hfan and @qqfish - Just curious if you have any insights to share. We would really appreciate any guidance that you can provide.

**Comment by qqfish** [comment]
There are two related issues we are working on:
1. Build a new API to allow converting a raw TF graph to a compiled graph (after optimization + XLA compilation). This is mainly driven by @maidoupp
2. Make the XLA GPU compilation result serializable. This is mainly driven by @ezhulenev

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
