### ISSUE TITLE
Allow different inputs choice to pad to bucket boundary in tf.data.Dataset.bucket_by_sequence_length

### ISSUE THREAD

**Issue by JeffreyWardman** [tensorflow/tensorflow#55601]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): 2.8.0
- Are you willing to contribute it (Yes/No): No

**Describe the feature and the current behavior/state.**
tf.data.Dataset().bucket_by_sequence_length() has boolean input variable `pad_to_bucket_boundary`. However, if one wants to pad multiple sequences (e.g. audio, length=1000) and labels (e.g. 10 categories) then there is no capability to pad one by bucket_boundary and the other by maximum length in batch.

In my instance, I'd like to pad the audio to the maximum length in the batch, but the label by buckets.

**Will this change the current api? How?**
Boolean pad_to_bucket_boundary can also receive a dictionary with string key and boolean value.

**Who will benefit with this feature?**
Users who want to avoid unnecessary sparsity conversions/padding

**Any Other info.**

**Comment by JeffreyWardman** [comment]
If there's a way to achieve the above via multiple operations that would be great to know.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
