### ISSUE TITLE
Handle called_computation in AbslHashValue

### ISSUE THREAD

**Issue by mavenlin** [tensorflow/tensorflow#55604]
<em>Please make sure that this is a feature request. As per our [GitHub Policy](https://github.com/tensorflow/tensorflow/blob/master/ISSUES.md), we only address code/doc bugs, performance issues, feature requests and build/installation issues on GitHub. tag:feature_template</em>

**System information**
- TensorFlow version (you are using): master
- Are you willing to contribute it (Yes/No): yes

**Describe the feature and the current behavior/state.**

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/xla/service/hlo_instruction.h#L1315
Only `kFusion` is considered in this code, modify to the following code to consider other instructions that has a called_computation.

```python
if (!hlo.called_computations().empty()) {
  for (auto* comp : hlo.called_computations()) {
    h = H::combine(std::move(h), *comp);
  }
}

if (hlo.opcode() == HloOpcode::kFusion) {
  h = H::combine(std::move(h), hlo.fusion_kind(), 
                 hlo.fused_instruction_count(),
                 hlo.fused_parameters().size());
}
```

**Will this change the current api? How?**
No

**Who will benefit with this feature?**
Everyone who is using the hash value to distinguish different computations.

**Any Other info.**

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
