### ISSUE TITLE
Some modification for tflite GPU delegate

### ISSUE THREAD

**Issue by njuhang** [tensorflow/tensorflow#55606]
I find some bug during programming. But I am not sure if these are right way to fix them, so I list them here first.

**System information**
- Mobile device  MTK mobile device.

**Details**
1. When a model has the structure that a Div followed by a Conv2D, and feature map has 3 channels. In this situation, I would get a all-nan output.
file [tensorflow/lite/delegates/gpu/common/tasks/conv_powervr.cc:](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/tasks/conv_powervr.cc)
in line 857, 
```
-        for (int ch = 0; ch < 4; ++ch){
+        for (int ch = 0; ch < (input_ch < 4 ? input_ch : 4); ++ch) {
```
in line 1043:
```
-        conv_core(0);
+        conv_core(0, input_ch);
```
in line 1046:
```
-         conv_core(i * block_size.w * 4);
+         input_ch -= 4;
+         conv_core(i * block_size.w * 4, input_ch);
```
Where input_ch represents the input channel number, which is 3 in this situation.
This modification will prevent zeros in channel 4, which is padded by GPU device for alignment, getting into calculation process.

2. When a conv2D op receive a dynamic weight as its second input, it will resullt in wrong padding.
file [tensorflow/lite/delegates/gpu/common/model_builder.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/model_builder.cc)
line 531, add this two lines after RETURN_IF_ERROR(reader->AddInput(node, 1)):
```
+          attr.weights.shape.h = graph->FindInputs(node->id)[1]->tensor.shape.h;
+          attr.weights.shape.w = graph->FindInputs(node->id)[1]->tensor.shape.w;
```
This modification will provide shape information for padding, which is in line 542:
UpdatePadding(tf_options->padding, graph->FindInputs(node->id)[0]->tensor.shape, &attr);

3. When a model has the structure that a Div followed by a Sub, and feature map has batch greater than 1, for example, feature map is in shape 64x1. This will cause a calculation error.
file [tensorflow/lite/delegates/gpu/common/tasks/elementwise.cc,](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/lite/delegates/gpu/common/tasks/elementwise.cc) function CreateElementwiseTwoInput:
```
-        const std::string x_coord = shape.w == 1 ? "0" : "X_COORD";
+        const std::string x_coord = (definition.IsBatchSupported() ? shape.w * shape.b : shape.w) == 1 ? "0" : "X_COORD";
```

**Comment by mohantym** [comment]
Hi @njuhang ! Could you also update the template with sample stand alone codes to help investigate the above bugs? Thanks!

**Comment by njuhang** [comment]
Sorry, I don't know what  template with sample stand alone codes mean. I have modified format of my question for reading easily.
Thanks

**Comment by mohantym** [comment]
Ok @njuhang ! Thanks for reporting those bugs. Reopening as requested. Thanks!

**Comment by njuhang** [comment]
Thanks, will there be anybody verify these problem, and modify source code?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
