### ISSUE TITLE
FusedBatchNormV3 split/fuse to/from Cheaper primitive ops with TF-1.15/TF-2.8

### ISSUE THREAD

**Issue by Alavandar08** [tensorflow/tensorflow#55650]
Hi, 

I am doing Inference with Bert Large & Bert Base models with TF-1.15 and TF-2.8. 

**Inference with Checkpoints:**
For TF-2.8, I observed set of primitive ops are Fused to single node FusedBatchNormV3 whereas in TF-1.15 fusion of primitive ops is not happening(The graph consists of Primitive ops).

**Inference with Frozen Graph:**
With frozen graph(.pb) the graph itself has FusedBatchNormV3 node. For TF-1.15 the FusedBatchNormV3 is split into set of primitive ops. whereas in TF-2.8 split of ops is not happening (The graph consists of Fused op).

I am trying to find where this fusion/split is happening when it differs TF versions. After going through fusions that happens at grappler phase(remapper.cc) I found the fusion is happening before it reaches grappler phase. 

Can someone help me to point out where the fusion/split of FusedBatchNormV3 is being taken place?

Thanks!!

**Comment by tilakrayal** [comment]
Hello @Alavandar08 ,
I request you, please specify the Use Cases/colab gist or share the link for the mentioned statement.It helps to debug the issue.Thanks!

**Comment by Alavandar08** [comment]
Hi @tilakrayal 
As mentioned above one of the use case is set of primitive ops are Fused into single op FusedBatchNormV3 in Bert Large with TF-2.8
Here I am adding the before and after fusion of FusedBatchNormV3 with checkpoints snapshots for the reference

![FusedBatchNormV3-primitve_ops](https://user-images.githubusercontent.com/86424477/163922325-e0b6cfec-2331-4458-b850-0c3acba1d30b.png)

<img width="253" alt="FusedBatchNormV3" src="https://user-images.githubusercontent.com/86424477/163922390-7f8571bd-b950-43c1-bbe5-a813ee68d5b2.png">

The file that I referred to in grappler -  [https://github.com/tensorflow/tensorflow/blob/r2.8/tensorflow/core/grappler/optimizers/remapper.cc](url)

**Comment by tilakrayal** [comment]
@Alavandar08 ,
The provided grappler file link is re-directing to github home-page.Can you please provide the correct link or code to reproduce the issue.It helps to debug the issue.Thanks!

**Comment by sachinprasadhs** [comment]
In Tensorflow 1.x with the graph mode as default it optimizes the graph computations and the same reason you see mainly primitive ops.
With Tensorflow 2.x with eager execution as default, in order to optimize the overall computation and to reduce the memory footprints fused operations are mainly used. 
Apart from the code link which you shared, you can refer this documentation for [FusedBatchNormV3](https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/fused-batch-norm-v3#summary).
For other options to optimize graphs you can refer [this](https://www.tensorflow.org/guide/graph_optimization) document.
[Here](https://github.com/tensorflow/tensorflow/blob/r2.8/tensorflow/core/ops/nn_ops.cc#L203) is an other code implementation of NN ops with `FusedNormV3`.
Hope this detail helps you. Thanks!
