### ISSUE TITLE
TFLite doesn't build OOB on VS2019, requires /std:c++20

### ISSUE THREAD

**Issue by chunky** [tensorflow/tensorflow#55702]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

github master 185c176

### Custom Code

No

### OS Platform and Distribution

Windows 10 x64

### Mobile device

N/A

### Python version

N/A

### Bazel version

N/A

### GCC/Compiler version

VS2019 16.11.12

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A (Intel UHD)

### Current Behaviour?

I followed the instructions here: https://www.tensorflow.org/lite/guide/build_cmake, making allowances for windows:
1) CMake 3.23.0-rc2, using cmake-gui
2) Chose tensorflow_src/tensorflow/lite as "where is the source code"
3) Chose new folder, tensorflow_src/tflite_build as "where to build the binaries"
4) Clicked "Configure", chose VS 2019 version in dropdown and left it with other options default.
5) Clicked "Generate", then "Open Project", which correctly opened in VS

In CMake's output, the only warning was in abseil-cpp/CMakeLists.txt:74, "A future Abseil release will default ABSL_PROPAGATE_CXX_STD to ON for CMake 3.8 and up. We recommend enabling this option to ensure your project still builds correctly"

Once the project opened in VS, I chose "Release" build type, and left everything else default, then clicked "Build Project"

The build failed. Code C7555, "use of designated initializers requires /srd:c++20", in project tensorflow-lite, in external_delegate.cc:158.

I'm unsure whether this is supposed to be a supported build configuration. If not, please close the issue.

### Standalone code to reproduce the issue

```shell
No code necessary; instructions above.
```

### Relevant log output

```shell
Severity   Code    Description    Project File    Line    Suppression State
Error    C7555    use of designated initializers requires at least '/std:c++20'    tensorflow-lite    C:\Users\gbriggs\src\tensorflow_src\tensorflow\lite\delegates\external\external_delegate.cc    158
```
</details>

**Comment by chunky** [comment]
I manually set the tensorflow_lite target to be built using stdc++20
I then subsequently got errors about __PRETTY_FUNCTION__ not defined, so I edited types.h, and inside the tflite namespace, I added:
```
#if !defined(__PRETTY_FUNCTION__) && !defined(__GNUC__)
#define __PRETTY_FUNCTION__ __FUNCSIG__
#endif
```
[Borrowed from here: https://stackoverflow.com/questions/48857887/pretty-function-in-visual-c ]

I haven't tested, but it did at least output Release/tensorflow-lite.lib without errors

**Comment by chunky** [comment]
EDIT: I stand corrected. After those two items, it's failing to link when I link to tensorflow-lite.lib , because it can't find a bunch of symbls with "ryu" in the name. And, I don't seem to be able to find a built lib anywhere that includes those symbols.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
