### ISSUE TITLE
Can tflite CoreML delegate add ELU activation support? (with fp16 as well)_

### ISSUE THREAD

**Issue by lucasjinreal** [tensorflow/tensorflow#55764]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf2.8

### Custom Code

No

### Current Behaviour?

```shell
A bug happened!
Can tflite CoreML delegate add ELU activation support? (with fp16 as well)_
```

### Standalone code to reproduce the issue

```shell
Can tflite CoreML delegate add ELU activation support? (with fp16 as well)_
```

### Relevant log output

```shell
Can tflite CoreML delegate add ELU activation support? (with fp16 as well)_
```
</details>

**Comment by hguihot** [comment]
If you're up for it, I'd suggest you add support for it yourself in the CoreML delegate since it's been a while. It should take about an hour.

1. Review the [TensorFlow contribution guidelines](https://github.com/tensorflow/tensorflow#contribution-guidelines).
2. Have a look at the [Apple documentation for the ELU activation](https://apple.github.io/coremltools/mlmodel/Format/NeuralNetwork.html#activationelu) (note the presence of `alpha`).
3. Also see the Apple documentation for [NeuralNetworkLayer](https://apple.github.io/coremltools/mlmodel/Format/NeuralNetwork.html#neuralnetworklayer) (see `activation` in there) and [ActivationParams](https://apple.github.io/coremltools/mlmodel/Format/NeuralNetwork.html#activationparams) (see `ELU` in there).
4. Modify `coreml_delegate.mm` and its `IsNodeSupportedByDelegate()` function so that it returns true for `kTfLiteBuiltinElu` (see how it's done for `kTfLiteBuiltinRelu` for inspiration). Pay attention to the "_For most ops, only version 1 is supported_" comment, you may have to modify that part too.
5. Add `OpBuilder* CreateEluOpBuilder(GraphBuilder* graph_builder);` declaration in `builders/op_factory.h`.
6. Add `case` statement in `builders/op_builder.cc` for `kTfLiteBuiltinElu` to add the new builder (again, see how it's done for ReLU).
7. Since you're adding support for an activation function you can then just modify `builders/activation_layer_builder.cc` accordingly instead of creating new files. Note that this file is using the `kTfLiteAct***` constants (`TfLiteFusedActivation` type) and `kTfLiteActElu` doesn't exist. You probably have to modify that part to use `kTfLiteBuiltinElu` instead (and change the use of the `TfLiteFusedActivation` type accordingly).

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
