### ISSUE TITLE
How to resize (downsample) 5D samples in tensorflow? 

### ISSUE THREAD

**Issue by innat** [tensorflow/tensorflow#55809]
Issue Type: Feature Request
Source: binary
Tensorflow Version: tf 2.8
Custom Code: Yes
OS Platform and Distribution: Windows 10
Python version: 3.9

---

## Note.

Reposting from [here](https://github.com/keras-team/keras/issues/16260). It's closed in keras and recommended to post it on the tensorflow side because this functionality is not precisely available in tensorflow. It may need to write low-level ops in tf for best performance.

# Current Behaviour?

Currently, for **5D** data, `(batch_size, h, w, depth, channel)`, the [`tf.keras.backend.resize_volumes`](https://github.com/keras-team/keras/pull/3274) or `UpSampling3D` can be used to **upsampling purpose**. 

For example, I can do 

```python
a  = tf.ones(shape=(1, 100, 100, 64, 1))

tf.keras.backend.resize_volumes(
       a, depth_factor=2, 
       height_factor=2, 
       width_factor=2, 
       data_format="channels_last"
).shape
TensorShape([1, 200, 200, 128, 1])
```

These `*_factor` values (above), should be an **integer**, and are coded here: https://github.com/keras-team/keras/blob/master/keras/backend.py#L3441-L3444. 

In that case, how can we **downsample** the input sample? For example:

```python
a  = tf.ones(shape=(1, 100, 100, 64, 1))

tf.keras.backend.resize_volumes(
       a, depth_factor=0.5, 
       height_factor=0.5, 
       width_factor=0.5 
       data_format="channels_last"
).shape

TypeError: 'float' object cannot be interpreted as an integer

# EXPECTED
TensorShape([1, 50, 50, 32, 1])
```

[ HERE https://stackoverflow.com/q/57341504/9215780, another scenario where the factor needed to be fractional. ]

# Candidate Solutions

- [scipy.ndimage.zoom](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.zoom.html)
- [in pytorch](https://discuss.pytorch.org/t/pytorch-resize-3d-numpy-array/70338/4) (didn't test)

## Others

- Such downsampling feature needs to be implemented in low-level. 
- In the `depth` part of volumetric data, it might be hard to decide the appropriate strategy to drop the slices depending on the domain. For example, in medical data, if we drop the slice blindly, we might lose information. FYI, in CT/MRI images, most of the information appears mainly in the **middle range**. 
- Currently a workaround for **medical data (CT/MRI)**, we're following:

```
# (input data: 1, 50, 50, 20, 4)
# (desired output: 1, 25, 25, 10, 4)
```
```python
a = tf.ones(shape=(1, 50, 50, 20, 4))
a.shape # TensorShape([1, 50, 50, 20, 4])

a2 = tf.reshape(a, [-1, 50, 50, 20*4])
a2.shape # TensorShape([1, 50, 50, 80])

a3 = tf.image.resize(a2, [25, 25])
a3.shape # TensorShape([1, 25, 25, 80])

a4 = tf.reshape(a3, [-1, 25, 25, 20, 4])
a4.shape # TensorShape([1, 25, 25, 20, 4])

# HERE, Picking some middle slices -
# - Assuming that by this we may get relevant slices. 
# How convenient is this? # May not general! 
a5 = a4[...,  5:15, :]
a5.shape
TensorShape([1, 25, 25, 10, 4])
```

**Comment by innat** [comment]
@sushreebarsa adding `keras` tag may not be proper. Please read this https://github.com/keras-team/keras/issues/16260#issuecomment-1070950476 and https://github.com/keras-team/keras/issues/16260#issuecomment-1071146844.

**Comment by cantonios** [comment]
@innat medical data often needs to be treated quite specially.  Our `tf.image` toolbox is designed for 2D images, and does an interpolation or convolution (depending on the supplied method).  A generalized 3D image resize primitive would mirror this, and apply the interpolation/convolution in all 3 dimensions.  Is this what you're looking for?

In MR images, the z-direction usually has a much lower resolution that the others, and correlation between slices is much lower (since slices have further separation and have larger "thickness").   You often don't want to interpolate between these.  More commonly, you resize the 2D image slices and then stack them together, as you have done (i.e. only resize in x-y).  To reduce the number of slices, you can either pick a region of interest (e.g. choose the middle 10 slices as in your workaround), or use `tf.strided_slice` to skip between them (e.g. `a5 = a4[...,  ::2, :]`).

If you're content with your work-around, I don't think we could squeeze much more efficiency out of it by introducing a new op.  In graph mode, the shape-resize-shape will be just as efficient as if we had done the same thing internally (the reshapes won't actually move any data around).

If you *do* want a 3d interpolation, there are tools like [tfg.math.interpolation.trilinear](https://www.tensorflow.org/graphics/api_docs/python/tfg/math/interpolation/trilinear/interpolate).  I don't think it's common enough that we would put it into core tensorflow.

**Comment by innat** [comment]
@cantonios Thanks for your details answer. I did a pause of a project that raised such above issue. I will revisit the problem soon. But below are some quick queries.

---

1. > A generalized 3D image resize primitive would mirror this, and apply the interpolation/convolution in all 3 dimensions. 

Is this https://www.tensorflow.org/graphics/api_docs/python/tfg/math/interpolation/trilinear/interpolate function doing a similar operation? 

2. > I don't think it's common enough that we would put it into core tensorflow.

Agree. But IMHO, general interpolation methods should be available from core tensorflow. 


3. > In MR images, the z-direction usually has a much lower resolution than the others, and the correlation between slices is much lower (since slices have further separation and have larger "thickness"). You often don't want to interpolate between these.

Could you please elaborate on this?

4. > Our `tf.image` toolbox is designed for 2D images and does an interpolation or convolution (depending on the supplied method). 

My main approach was not with `tf.image` though, I wanted to use [`tf.keras.backend.resize_volumes`](https://github.com/keras-team/keras/blob/master/keras/backend.py#L3563-L3591), which meant for the volumetric data. Now, unable to downsampling with it was a bit disappointing. To address this is the actual feature request.

---

In [`scipy`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.zoom.html#scipy.ndimage.zoom) and [`pytorch`](https://pytorch.org/docs/stable/generated/torch.nn.Upsample.html), I can do

```python
import torch

a = torch.rand(1, 3, 20, 128, 128)

up = torch.nn.Upsample(size=(40, 256, 256), mode='trilinear')
down = torch.nn.Upsample(scale_factor=(0.5, 0.5, 0.5), mode='trilinear')

print('orig = ', a.shape)
print('up   = ', up(a).shape)
print('down = ', down(a).shape)

orig =  torch.Size([1, 3, 20, 128, 128])
up   =  torch.Size([1, 3, 40, 256, 256])
down =  torch.Size([1, 3, 10, 64, 64])
```
```python
from scipy.image import zoom

a = np.zeros((20, 128, 128))
up = zoom(a, zoom=(2, 2, 2), mode='wrap')
down = zoom(a, zoom=(0.5, 0.5, 0.5), mode='wrap')

print('orig = ', a.shape)
print('up   = ', up.shape)
print('down = ', down.shape)

orig =  (20, 128, 128)
up   =  (40, 256, 256)
down =  (10, 64, 64)
```

Now, if I reform my query, like, how can I achieve this with core `tensorflow`. The [`layers.UpSampling3D`](https://keras.io/api/layers/reshaping_layers/up_sampling3d/) which uses `tf.keras.backend.resize_volumes` in [backed](https://github.com/keras-team/keras/blob/d8fcb9d4d4dad45080ecfdd575483653028f8eda/keras/layers/convolutional.py#L3043) lacks interpolation methods for 3D volumetric data.

**Comment by cantonios** [comment]
@innat 
1. I have no direct experience with tfg, but you can check out the source for `trilinear` [here](https://github.com/tensorflow/graphics/blob/master/tensorflow_graphics/math/interpolation/trilinear.py).  It looks like you give it a set of sampling points (e.g. your desired locations within the new interpolated grid), and it will use trilinear interpolation to extract values at those points.

2. Interpolation is usually viewed as an input preprocessing stage.  It's not *really* part of the ML model.  For 2D images, it is very common to have training images of different sizes (e.g. a collection of downloaded pictures of horses).  And in model serving, if you want a generic inference model that can work for multiple camera resolutions, it makes sense to have a built-in tool to allow these to be resampled to a fixed input size.  3D images, however, are a lot more rare - the most common being medical images.  It is more likely that these will already be of identical size, and if not, you can use whatever tool you need to re-interpolate them ahead of time; it's unlikely you will have a steady stream of 3D images coming directly from a camera, for example.  Similarly with general ND inputs - it's also not as common to need to interpolate on-the-fly.

3. Interpolation works well when nearby pixels/voxels are highly correlated, so that the new interpolated pixel/voxel is highly representative of those around it.  In MR slices, the slice direction is often separated by larger gaps, the signal is an estimated average over the slice thickness, and it is often captured at a slightly different time than other slices.  For CT it depends on how it's collected.  Many applications also use slices of 2D CT, so you will have similar issues.  Hence there is often a much lower image resolution in the slice direction, and more variation between slices.  In medical applications we often want to keep all slices (at least those in the region of interest).

4. It looks like `resize_volumes` just repeats values along each spatial axis.  The inverse of this is `tf.strided_slice`.

---

If you have an input of fixed known size, and you just want to decrease the resolution to make the model run faster, it's much more common to add convolution+pooling layers (e.g. `Conv3d` + `MaxPool3d`).  The convolution will try to pick out "features", and the pooling will keep only the "important" ones while cutting down the number of samples.  That way you're not throwing away any potentially important information.

If you just want to cut down the resolution of your fixed-size input images, you could try [`tf.nn.avg_pool3d`](https://www.tensorflow.org/api_docs/python/tf/nn/avg_pool3d), which will take the average of a collection of voxels.  This will be similar in nature to trilinear interpolation on a regular grid (and equivalent if you're cutting each dimension down by half), but is already built-in and will be much faster.

**Comment by cantonios** [comment]
@bhack not by Google, it's community-driven.  The interpolate function is python-only though, and they just use exising `tf` functions under-the-hood.

**Comment by bhack** [comment]
> The interpolate function is python-only though, and they just use exising tf functions under-the-hood.

Yes I saw. It was more related to clear-up the contribution route in the ecosystem and to know if there were full time resources allocated to sustain the core repo activities.
