### ISSUE TITLE
Crash when using TFLite on Window

### ISSUE THREAD

**Issue by HedgeHao** [tensorflow/tensorflow#56022]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Bazel version

4.2.1

### Current Behaviour?

```shell
When assign assign interpreter->outputs() to another variable, it crashed on Windows. Same code works fine on Linux.
```

### Standalone code to reproduce the issue

```c++
#include <tensorflow/lite/kernels/register.h>
using namespace tflite;

int main() {
	std::unique_ptr<tflite::Interpreter> interpreter;
	auto model = tflite::FlatBufferModel::BuildFromFile("D:/test.tflite");
	if (model == nullptr) {
		printf("Error1\n");
	}
	tflite::ops::builtin::BuiltinOpResolver resolver;
	if (InterpreterBuilder(*model, resolver)(&interpreter) != kTfLiteOk) {
		printf("Error2\n");
	}
	if (interpreter->AllocateTensors() != kTfLiteOk) {
		printf("Error3\n");
	}

	interpreter->outputs();   // This line will work
	 //auto outs = interpreter->outputs();  // This line will crash

	printf("Done\n");
	return 0;
}
```

### Relevant log output

_No response_</details>

**Comment by HedgeHao** [comment]
When using debbuger to trace the TFLiteModel. It seems the model is not load correctly. As you can see my code, I check errors for each steps related to TF. BuildFromFile(), InterpreterBuilder() and AllocateTensors() are success

![擷取_2022_05_09_15_32_07_189](https://user-images.githubusercontent.com/8536950/167362150-9a1d1551-c284-4623-be40-f0e71c52db48.png)

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
