### ISSUE TITLE
Support for tf.transpose for tensors of rank 12 or higher

### ISSUE THREAD

**Issue by LeavesBreathe** [tensorflow/tensorflow#5606]
Can support for `tf.transpose` please be added for tensors above rank 11? Can it be extended to tensors of rank size 40 or 50 on the gpu?

I know this seems large, but I'm trying to implement this tensorization paper where this is demanded. 

https://arxiv.org/pdf/1611.03214v1.pdf

**Comment by girving** [comment]
Unfortunately, the current code for transpose does template instantiation for each dimension.  We're already running into code size issues, so we won't be able to accept 40 or 50 (a rather large chunk of the tensorflow binary would become transposes).

However, we'd be happy to accept PRs that implement arbitrary rank transposes in a manner that doesn't require unbounded template instantiation.  There are a couple options for this:

1. Find a clever new algorithm that I've searched for but failed to find that efficiently does arbitrary rank transpose.  I would be thrilled.
2. Split high rank transposes into a sequence of reshapes and smaller rank transposes.  This requires a fair amount of index machinery, but is "straightforward".  It could be done either in C++ and Python, but is probably easier to do in C++ since then the index manipulation doesn't have to be TensorFlow ops.

In either case, it would be good to add the optimization that flattens dimensions that transpose together so as to use lower rank code if possible.

Note that [XLA](https://www.tensorflow.org/versions/master/resources/xla_prerelease.html) will likely have no trouble with high rank transposes, but that may take a while to land and wouldn't necessary be very efficient (for the same reasons I haven't found a fast high rank transpose algorithm).  Thus, I don't think the above work would be wasted.

**Comment by LeavesBreathe** [comment]
@girving Thanks for such a comprehensive response. 

Would it at all be possible to even raise the acceptable rank number to 15 or 20? This alone would open up alot of possibilities. Hopefully it wouldn't raise the binary size too much.

Idea 1 would be miraculous but I'm just as lost as you are on how to specifically implement this.

**Comment by girving** [comment]
@LeavesBreathe Actually, I'm confused.  It looks like someone already wrote the slow but arbitrary rank version: https://cs.corp.google.com/piper///depot/google3/third_party/tensorflow/core/kernels/transpose_functor_gpu.cu.cc?dr=CSs&l=27.  What error message you seeing?

**Comment by girving** [comment]
I asked about it on scicomp: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/transpose_functor_gpu.cu.cc#L27.  Curious if someone knows a faster version.

**Comment by LeavesBreathe** [comment]
I apologize but I don't have the error message in front of me right now. I'm going to close this thread as i'm not providing adequate documentation. From what I remember the message said "tf.transpose does not support tensor of rank 12"
