### ISSUE TITLE
Wrong prediction every time using the person detection model on ESP32-WROVER-IE board 

### ISSUE THREAD

**Issue by ASabovic** [tensorflow/tensorflow#56079]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

Microlite esp32 firmware 

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

Python 3.8

### Current Behaviour?

```shell
Hi guys,
I am using the ESP32-WROVER-IE board with the ov2640 camera connected to it. I am trying to run the person detection example and see if I can get some output results based on the captured image. Every time I get same result where the higher value is assigned to not_a_person prediction even if I am present on the picture. I also tried with the existing example but there as well the prediction is always negative (I mean it's always like there is nobody on the picture). Is there any possible solution for this issue? Any kind of help is welcome.

P.S. I am using MicroPython!
```

### Standalone code to reproduce the issue

```shell
https://github.com/mocleiri/tensorflow-micropython-examples/tree/main/examples/person_detection
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @ASabovic ! Thanks for reporting the bug. @sachinprasadhs ! Could you please look at this issue?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
