### ISSUE TITLE
Fonts do not load properly under Firefox

### ISSUE THREAD

**Issue by zurgeg** [tensorflow/tensorflow#56099]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

Firefox on Windows 11

### Current Behaviour?

```shell
Docs page can not load Google Fonts (503 service unavailable) under Firefox, even with all extensions disabled. It only succeeds to load properly under an Incognito Window.
```

### Standalone code to reproduce the issue

```shell
Open any page on tensorflow.org under Firefox 100 (problem was there before FF 100, but I didn't take note of when it started). The problem will appear. Clearing cookies or using incognito solves the issue.

Further note: the issue can be solved by blocking cookies for tensorflow.org, but a server-side solution would help a lot of people.
```

### Relevant log output

_No response_</details>

**Comment by chunduriv** [comment]
@zurgeg, 

Thank you for reporting the issue. Unfortunately I am unable to replicate the issue using `Firefox 96.0.3`. Please refer to the screenshot in below

![image](https://user-images.githubusercontent.com/74177924/168835495-0b7f0788-c88c-4335-9462-06bc55c89c9c.png)

Generally `503 service unavailable` caused by a high number of requests sent to the server, which exhausts available resources.

Please can you confirm if you are facing any issues using `Firefox 96.0.3`?  Thank you.

**Comment by zurgeg** [comment]
> @zurgeg,
> 
> Thank you for reporting the issue. Unfortunately I am unable to replicate the issue using `Firefox 96.0.3`. Please refer to the screenshot in below
> 
> ![image](https://user-images.githubusercontent.com/74177924/168835495-0b7f0788-c88c-4335-9462-06bc55c89c9c.png)
> 
> Generally `503 service unavailable` caused by a high number of requests sent to the server, which exhausts available resources.
> 
> Please can you confirm if you are facing any issues using `Firefox 96.0.3`? Thank you.

Sure, I'll try.

FYI: The problem seems to happen on and off. I'm seeing a similar issue displayed in #28173.
