### ISSUE TITLE
Tflite checkpoint restore 

### ISSUE THREAD

**Issue by Sanjay2802** [tensorflow/tensorflow#56117]
Checkpoints saved sucessfully, but can't load checkpoint after interruption 
![Screenshot_20220516-112630](https://user-images.githubusercontent.com/86015315/168553539-cd972228-29a9-471c-bf9a-941c1248dc4f.jpg)
 
Why detection variable is not defined , how to restore saved checkpoint

**Comment by Sanjay2802** [comment]
Hi @mohantym , https://colab.research.google.com/drive/1qdcEpYXlu-K5eYC9ARtyJaiQjlhT63kT?usp=sharing


You can see that i interrupted the training , but after that i need to continue from last checkpoint epoch , but error arises , please help me to solve this brother

**Comment by mohantym** [comment]
Hi @Sanjay2802 ! Can you check this [gist](https://colab.sandbox.google.com/gist/mohantym/8b45a5972205e5ed7d2b27809f3d2fa7/stack_69444878.ipynb#scrollTo=nBusnX_vcOUl) on restoring from checkpoints? Thank you!

**Comment by Sanjay2802** [comment]
https://colab.research.google.com/drive/1pCRD4fUTrI0jb9SDqjLAvKSey7pr_-Fu?usp=sharing 

Some errors....
can you explain me when and how checkpoint is made ,and how to restore when  interrupted .and why it continues from 11th epoch in your notebook

**Comment by mohantym** [comment]
@Sanjay2802 ! It was starting from 11th epoch as i set initial_epochs=10 in spec initially. Could you check the updated [gist](https://colab.sandbox.google.com/gist/mohantym/8b45a5972205e5ed7d2b27809f3d2fa7/stack_69444878.ipynb#scrollTo=5RLrPiZRBsEl) now. It is loading the weights from 50th epoch(completed epoch) after commenting    `do_train = False` from spec. Thank you!

**Comment by Sanjay2802** [comment]
https://colab.research.google.com/drive/1Eu6yamVbd8NGmm278RutiuafxEJIdopb?usp=sharing

when i stop training at 2nd epoch, and try to continue to restore, same error arises, check the above link

**Comment by mohantym** [comment]
@Sanjay2802 ! It should continue from last checkpoint after interruption as you mentioned. But things does not seem same  in case of TFlite model maker.

@sachinprasadhs ! Could you please look at this issue . Attached [gist](https://colab.sandbox.google.com/gist/mohantym/8b45a5972205e5ed7d2b27809f3d2fa7/stack_69444878.ipynb#scrollTo=5RLrPiZRBsEl) for reference. Thank you!

**Comment by Sanjay2802** [comment]
Solve asap

**Comment by Sanjay2802** [comment]
Found anything?

**Comment by pkgoogle** [comment]
currently blocked by https://github.com/tensorflow/tensorflow/issues/60431

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
