### ISSUE TITLE
DenseNet PB and TFLite models produce inaccurate results

### ISSUE THREAD

**Issue by luludak** [tensorflow/tensorflow#56183]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

TF 2.8.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04 4LTS

### Python version

3.8

### GPU model and memory

Intel UHD Graphics 620

### Current Behaviour?

```shell
I am using the slim DenseNet models provided [here](https://storage.googleapis.com/download.tensorflow.org/models/tflite/model_zoo/upload_20180427/densenet_2018_04_27.tgz), building and loading them using [Apache TVM](https://tvm.apache.org/).

Although I applied the [indicated preprocessing](https://github.com/tensorflow/models/tree/master/research/slim/preprocessing), it seems that the models produce results much different from the ground truths expected in a small validation dataset I use, and they are consistent to this across each other.

Also, they tend to predict similar ImageNet labels (e.g., IDs 1000, 340 and 341 are common part to almost all top-5 classification predictions they produce).

I suspect this is related to preprocessing somehow, but I have followed the process step by step and the results are the same.
```

### Standalone code to reproduce the issue

```shell
1) Build model in TVM modules (one for PB and one for TFLite)
2) Execute the modules, applying preprocessing.
3) Compare top-5 predictions with dataset ground truths.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @luludak ! Could you please share a minimal standalone code to replicate the issue.

**Comment by luludak** [comment]
Hi @mohantym . My code follows precisely the model compilation and execution procedure defined in TVM ([tutorials](https://tvm.apache.org/docs/tutorial/index.html)).

In addition, I prepared and setup preprocessing as set in the [VGG Preprocessing](https://github.com/tensorflow/models/blob/master/research/slim/preprocessing/vgg_preprocessing.py), unchanged.
In practice, I load the model, and for each image from its validation dataset, I convert it to a NumPy tensor and use VGG Preprocessing. Then I execute it using TVM and I extract the predictions.

I tend to believe there is 1. either a problem with the model version or 2. preprocessing causes problems to the models.
Can you please provide some insight on this?

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue?

**Comment by khanhlvg** [comment]
TVM isn't part of the TensorFlow ecosystem so unfortunately we don't have anyone familiar with it at Google. If you want to run inference with TF models, I'd suggest checking out:
1. TF Serving if you want to run inference on the server.
2. TFLite if you want to run inference on edge devices.

**Comment by luludak** [comment]
Hi @khanhlvg and thank you for your reply. My main concern in terms of TensorFlow is on the use of preprocessing.
Is the one I have found the correct one for these specific models?

**Comment by pkgoogle** [comment]
Hi @grantjensen, can you please take a look? Thanks.

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
