### ISSUE TITLE
BUG: Memory leak bugs due to returned new reference is not decreased on failure (static analyzer reports)

### ISSUE THREAD

**Issue by Snape3058** [tensorflow/tensorflow#56238]
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/python/client/tf_session_wrapper.cc#L285
Function returns without decreasing the refcnt.
https://github.com/tensorflow/tensorflow/blob/4c1572c8cd91ac2bf757189e0d533b1dbecdad01/tensorflow/python/client/tf_session_wrapper.cc#L296
Internal Report ID: cd62b9

---
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L1390
Function returns without decreasing the refcnt.
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/eager/pywrap_tfe_src.cc#L1397
Internal Report ID: 471b1c 

---
Returning a new reference here:
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/util/nest.cc#L93
Function returns without decreasing the refcnt.
https://github.com/tensorflow/tensorflow/blob/15c26be8f79834ae5a6123939b4885e4d6a112af/tensorflow/python/util/nest.cc#L136 
Internal Report ID: 86960d

**Comment by sushreebarsa** [comment]
@Snape3058 In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose). Thank you!

**Comment by Snape3058** [comment]
I think it is not necessary to provide the information you are collecting in the template, since the reports are from a static analyzer. But if you really want, here is the information I can provide.

* Issue Type: Bug
* Source: source
* Tensorflow Version: analyzer is executed on commit faad219fc46032a0ae9576ccc3076612cc1f5f72 and the bugs are confirmed to be exist in the latest commit 15c26be8f79834ae5a6123939b4885e4d6a112af when I report the bug 
* Custom Code: No
* Python version: 3.9
* Compiler version: static analyzer is developed on the top of Clang Static Analyzer 9.0.0.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
