### ISSUE TITLE
HtoD copy not fully overlapping with he execute

### ISSUE THREAD

**Issue by kushanam** [tensorflow/tensorflow#56259]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

Ubuntu 18.04

### Python version

3.8

### Bazel version

5.0.0

### CUDA/cuDNN version

11.5/8.3

### GPU model and memory

V100 32GB

### Current Behaviour?

```shell
Despite the recent work on moving the staging logic to TF from the driver (commits 9a8772d, ad60111, b4b294f, 2803dfc, 4111779 and ecc3db7), the blocking calls seem to still be existent and the execute could not be fully synchronized. This behavior is not consistent and seems to be more frequent in the elater steps.
```

### Standalone code to reproduce the issue

```shell
import os
import datetime
from tqdm import tqdm
import numpy as np
import tensorflow as tf

def main(argv):
  del argv
  @tf.function
  def do_stuff(wmat, tf_var):
    result = tf.matmul(wmat + 1, tf.transpose(wmat))
    error = tf.reduce_mean(tf_var)
    return error, result

  dataset = tf.data.Dataset.range(1000)
  dataset = dataset.map(
      lambda _: tf.random.uniform([10000,1024]),
      num_parallel_calls=tf.data.AUTOTUNE)
  dataset = dataset.apply(tf.data.experimental.prefetch_to_device('/gpu:0'))

  tf_var = tf.Variable(np.zeros(3))
  adam = tf.keras.optimizers.Adam(1e-4)

  for _, wmat in tqdm(enumerate(dataset)):
    with tf.GradientTape() as tape:
      result = do_stuff(wmat, tf_var)
      grads = tape.gradient(result[0], [tf_var])
      adam.apply_gradients(zip(grads, [tf_var]))

if __name__ == "__main__":
    main("")
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
While I was trying to reproduce the issue in google colab, the code was executing more than 3 hrs which was longer than expected. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/85a9bd43309f44ed92cd4611c13233f5/56259.ipynb).

**Comment by kushanam** [comment]
> @sachinprasadhs,
> While I was trying to reproduce the issue in google colab, the code was executing more than 3 hrs which was longer than expected. Please find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/85a9bd43309f44ed92cd4611c13233f5/56259.ipynb).

Made a smaller dataset. could you have another look please?

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
