### ISSUE TITLE
When we will  publish the  rnn_cell dynamic_rnn  lstm build method  in C api and Java api? eager to use

### ISSUE THREAD

**Issue by mullerhai** [tensorflow/tensorflow#56264]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

mac

### Python version

3.8

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
want to use  lstm in java ,but we not have example
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@mullerhai Could you elaborate about your feature and please specify the use cases for this feature. Thank you!

**Comment by gadagashwini** [comment]
Hi @mullerhai, Tensorflow Java has `BlockLSTM` API support. It computes the LSTM cell forward propagation for all the time steps. For more information refer this [link](https://www.tensorflow.org/api_docs/java/org/tensorflow/op/core/BlockLSTM). Thank you!

**Comment by mullerhai** [comment]
> link

Thanks ,I know BlockLSTM in java ，but also I think if convenient for our team to write the contain lstm train model example in java ? like  this https://github.com/tensorflow/java-models/blob/master/tensorflow-examples/src/main/java/org/tensorflow/model/examples/cnn/vgg/VGGModel.java
also I think  Embedding Layer in keras and  dynamic_rnn_cell  should contain in java tensorflow api.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
