### ISSUE TITLE
Create a rugged tensor in golang

### ISSUE THREAD

**Issue by juancresc** [tensorflow/tensorflow#56278]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

latest or any

### Custom Code

No

### OS Platform and Distribution

any

### Mobile device

any

### Python version

3.9

### Current Behaviour?

```shell
I'm currently not able to create a rugged tensor from golang. I wonder if there's a way to do it or if there's gonna be
```

### Standalone code to reproduce the issue

```shell
if you create a newTensor right now, all elements in the lists needs to be the same size
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @juancrescente,
Can you please elaborate about your Feature. Also, kindly specify the Use Cases for this feature. Thank you!

**Comment by juancrescente** [comment]
Yes, we have a model that accepts an array as an input feature. This array can be of different length like this in python:

`words = tf.ragged.constant([["So", "long"], ["thanks", "for", "all", "the", "fish"]])`

Right now there's no way to do that (that we are aware of) in golang and we'd love to be able to do it.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
