### ISSUE TITLE
Add gdb to development docker?

### ISSUE THREAD

**Issue by awf** [tensorflow/tensorflow#56309]
Following arguments similar to https://github.com/tensorflow/io/pull/460, and given splendid @mrry advice here, https://stackoverflow.com/questions/40889221/debugging-tensorflow-tests-pdb-or-gdb, it would be nice to have GDB in the devel image.  I am happy to create a PR given very brief pointers on what files to change.

<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

head

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.8.3

### Bazel version

5.0.0

### GCC/Compiler version

9.4.0

### Current Behaviour?

```shell
$ docker pull tensorflow/tensorflow:devel
$ docker run tensorflow/tensorflow:devel gdb
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "gdb": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled 


Ideally there would not be an error.

```

### Standalone code to reproduce the issue

```shell
$ docker pull tensorflow/tensorflow:devel
$ docker run tensorflow/tensorflow:devel gdb
docker: Error response from daemon: OCI runtime create failed: container_linux.go:367: starting container process caused: exec: "gdb": executable file not found in $PATH: unknown.
ERRO[0000] error waiting for container: context canceled
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi @awf,
Can you please elaborate about your Feature. Also, please specify the Use Cases for this feature. Thank you!

**Comment by awf** [comment]
This is a feature for tensorflow developers following the instructions at https://www.tensorflow.org/install/source#cpu-only

Currently, as a developer, I cannot debug tensorflow using gdb inside the developer docker container.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
