### ISSUE TITLE
Unable to use tflite java on macos

### ISSUE THREAD

**Issue by drubinstein** [tensorflow/tensorflow#56322]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

MacOS

### Current Behaviour?

```shell
Currently TFLite on Maven only distributes .so files for JNI which are not usable on macos (as it's not a mach-o file). I am trying to run some tests on a library I'm working on outside of the android emulator, but can't run the tests due to the lack of .dylib files. Is it possible to add a configuration for mac builds or possibly add a .jar artifact to maven with .dylib files for jni?
```

### Standalone code to reproduce the issue

```shell
Built it locally and tried to run tests with JUnit.
```

### Relevant log output

_No response_</details>

**Comment by drubinstein** [comment]
Any update?

**Comment by charaizlabs** [comment]
Hi there! I'm following up on this issue! We're looking for `.dylib` files for Android development unit testing

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
