### ISSUE TITLE
tf.data Service Dispatcher/ Worker - how to shutdown/stop?

### ISSUE THREAD

**Issue by gilinachum** [tensorflow/tensorflow#56386]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

binary

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.9

### Current Behaviour?

```shell
How can I shutdown/stop tf.data.service dispatcher and workerServer processes when training completes?  
I'm running tf.data.service on two nodes: data-node, GPU-node. 
On the data-node I'm starting: `tf.data.experimental.service.DispatchServer` and a `tf.data.experimental.service.WorkerServer`.
On the GPU-node I'm consuming a dataset which connects to the DispatcherServer
.apply(tf.data.experimental.service.distribute(
        processing_mode="parallel_epochs",
        service=f'grpc://{dispatcher_host}:6000',),
    )
All is well, but I found there's no built-in way to signal the dispatcher and workerserver to exit when training completes on the GPU-node. I need them to exit gracefully as I'm running in a job orchestrator that waits with terminating the overall job until all processes exit.  
I would expect to have a shutdown/close/stop method with tf.data.Dataset, or in data_service_ops.py.
```

### Standalone code to reproduce the issue

```shell
I just followed the built-in example for tf.data.service. Asking a what is the expected behavior question.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@gilinachum,
In order to reproduce the issue reported here, could you please provide the complete code and the dataset you are using. Thank you!

**Comment by gilinachum** [comment]
[Archive 2.zip](https://github.com/tensorflow/tensorflow/files/8918186/Archive.2.zip)
Attached an example for running a standard tf.data.service client and server.
The issue is that after training completes, the server's process doesn't exit, and there's no way to hint it should exit.

**Comment by EnricoMi** [comment]
You can call private method `_stop()` of `DispatchServer` and `WorkerServer`, which will stop the underlying servers.

The `__del__` method is calling that private method, so eventually, `_stop` gets called anyway.

There is no public / documented way to shut them down gracefully. And there is no explanation why.

**Comment by gilinachum** [comment]
Thanks, I noticed `_stop()`, I could use it locally, but my actual challenge is being able to stop the dispatcher and worker servers from the dataset consuming process that runs on a different box.  
For my use case, not being able to stop the dispatcher is a design hole, and I'll need to create my own socket signaling mechanism between client to dispatcher to workers, to workaround it.

**Comment by EnricoMi** [comment]
The latest release of Horovod (0.25.0) supports starting a TF Data Server and shutting it down from the training script.

**Comment by sachinprasadhs** [comment]
@gilinachum , If your issue is resolved, could you please close the issue. Thanks!

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
