### ISSUE TITLE
Adding additional image color and packing conversions for row images in order to save effort, space and improve performance 

### ISSUE THREAD

**Issue by zkadi21** [tensorflow/tensorflow#56443]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

No

### OS Platform and Distribution

any

### Mobile device

any

### Python version

n/a

### Bazel version

n/a

### GCC/Compiler version

n/a

### CUDA/cuDNN version

n/a

### GPU model and memory

any

### Current Behaviour?

```shell
Presently there are  only limited  amount of color and packing conversion for images . 
example : https://www.tensorflow.org/api_docs/python/tf/image/yuv_to_rgb   and  the packing  of the images is usually 1:1 type. 
Majority of test images from cameras are originally decoded as I420, or NV12 packing  (4:2:0) and  they need to get converted into RGB (or BGR) 4:4:4. 
It would be beneficial if https://www.tensorflow.org/api_docs/python/tf/image/ has a  NV12 (4:2:0) to RGB  layer more than YUV --> RGB (4:4:4 to 4:4:4). 
There are multiple reason for it:
   1 - Both Intel and nVidia (and many others) decode videos into NV12 
   2 - Majority of Images and Videos are stored in 4:2:0 packing  .
   3 - Reduce memory (or disk) footprint of using other tools to convert images  outside of TF (like FFMPEG, OpenCV...) 
   4 - Most importantly, it will allow for quick/significant bandwidth reduction by fussing first layer of many NN with the color-conversion+packing, considering that all of them use RGB (4:4:4) images as input . 
   5 - Finally, the user will be  using TF
```

### Standalone code to reproduce the issue

```shell
There are many color/packing converter examples  of Images  available in many other places. 
Find one wo  royalties.
```

### Relevant log output

```shell
n/a
```
</details>

**Comment by cantonios** [comment]
We may accept an external contribution for this.  We generally want to avoid TF from becoming an all-purpose image processing library though.  If there is a light-weight external library to do this conversion, that would be preferred.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
