### ISSUE TITLE
Tensorflow precompiled AOT XLA compiler.

### ISSUE THREAD

**Issue by weisrc** [tensorflow/tensorflow#56474]
I am trying to compile a Saved Model to a linkable library. But compiling the compiler takes forever on my computer. Is it possible to provide the compiler binaries and possibly have it in the releases. Perhaps also make it freeze the model automatically for simplicity.

Thank you!

**Comment by mohantym** [comment]
Hi @weisrc ! Could you you share the steps along a minimal stand alone code to replicate the issue. Thank you!

**Comment by weisrc** [comment]
Thank you for the swift response!

I am trying to compile this model https://tfhub.dev/vasudevgupta7/wav2vec2/1 into binary using `tf_library()`, but doing so requires to compile most of TensorFlow. I am following this tutorial online: https://gist.github.com/carlthome/6ae8a570e21069c60708017e3f96c9fd but for a different saved model.
Are there precompiled https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/aot/tfcompile_main.cc that I am not aware of? If not, having one will be a great addition to make XLA AOT more accessible!

The reason I am falling back to this is because I am experiencing issues using the regular TF. There is a feature which is not implemented for CPU (Group Conv2D if I recall correctly).

**Comment by weisrc** [comment]
Furthermore, I am trying to use it with Rust, this explains why I prefer having it as a linkable library.

**Comment by weisrc** [comment]
Sorry, I will try to get the template filled when I have access to my computer.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this feature request. Thank you!

**Comment by rivershah** [comment]
Any updates on this issue please? We need working recent examples of AOT compilation from a saved model. Having `tfcompile` available with tensorflow distribution will be a great help.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
