### ISSUE TITLE
Dataset loses cardinality/length after prefetch to gpu 

### ISSUE THREAD

**Issue by tgpsantos** [tensorflow/tensorflow#56508]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8.2

### Custom Code

Yes

### Current Behaviour?

```shell
Hi Guys,

I've noticed that I lose dataset cardinality when prefetching data to gpu. 

This forces me to call assert_cardinality, which is a problem because:
- operation runs on CPU, so instead of buffering data for training in GPU, I'll be buffering data that is sent to CPU for assert_cardinality and then being send on demand to GPU
- if I don't call assert_cardinality, model.fit runs endlessly since it can't determine the number of steps per epoch
```

### Standalone code to reproduce the issue

```shell
I've created this colab that reproduces the issue I'm telling
https://colab.research.google.com/drive/1I7Z4BwTuVe4qc_TrtfzdcdUNrBw9vWnB?usp=sharing

There's also an unexpected problem regarding the length without GPU (it's returning 24 when 100 was the expected). 

Thanks for the help in advance!
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/892ff1a38e77857c37e5810c6b76f369/56508.ipynb).

**Comment by tgpsantos** [comment]
Hey @aaudiber , did you have a look at this?

**Comment by aaudiber** [comment]
The colab prints `24` because the string `"len ds_without_gpu = 100"` is 24 characters long. 

Switching the `len` to `print` gives the expected value of 100.

You're right that cardinality metadata is lost when prefetching to GPU. I don't see a good workaround for setting the cardinality since as you mentioned assert_cardinality runs on CPU. 

That being said, it isn't clear if you actually need the cardinality to be set. `model.fit` should not run endlessly just because it can't determine the cardinality of the dataset. Most datasets have unknown cardinality because they read examples from files, and it is initially unknown how many examples each file contains. The `model.fit` docs suggest that it will train on the entire dataset unless `steps_per_epoch` is specified, in which case it will only train for the requested number of steps. Either way, it shouldn't require a known cardinality.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
