### ISSUE TITLE
Gradients across graphs

### ISSUE THREAD

**Issue by xlnwel** [tensorflow/tensorflow#56530]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### Current Behaviour?

```shell
How can I compute gradients across two `@tf.function`?
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/10V4V5Hr25NZehWE2TjFPD0-jtGpCFDMa?usp=sharing
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@xlnwel Could you please share the drive access to this colab link as it will help us to analyse the issue?
Thank you!

**Comment by sushreebarsa** [comment]
@xlnwel Sorry, I am not able to access this gist. Thank you!

**Comment by xlnwel** [comment]
Hi @sushreebarsa. I'm sorry for that. I believe it's accessible now

https://colab.research.google.com/drive/10V4V5Hr25NZehWE2TjFPD0-jtGpCFDMa?usp=sharing

**Comment by xlnwel** [comment]
Hello, @sushreebarsa. Could you access the above link now? Please let me know if you're still not able to.

**Comment by sushreebarsa** [comment]
@xlnwel Thank you for your response. I could access the link.
@chunduriv I was able to replicate this issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/7416eb9a4595bceb9b8ac43570d6ce55/meta-gradient-rl.ipynb#scrollTo=usYHHPujhNSN) here. Thank you!

**Comment by xlnwel** [comment]
Any updates? @sushreebarsa and @chunduriv

**Comment by sachinprasadhs** [comment]
Since, `tf.function` creates a new graph each time it is used and `Gradient tape` does not record the operations done outside its graph.
Ideal way in your case is to wrap all the expensive computations within the single `tf.function` and compute the Gradient in the same graph.

**Comment by xlnwel** [comment]
Hi @sachinprasadhs. I remember that TF constructs the graph only at the first call and keeps it thereafter, while torch destroys the graph after every call. But you told me that `@tf.function` creates a new graph each time. Does it mean that `@tf.function` now behaves similarly to torch? 

> Ideal way in your case is to wrap all the expensive computations within the single `tf.function` and compute the Gradient in the same graph.

I acknowledge that, but that'll be very expensive if I do multi-step meta-gradients. Isn't there a cheaper way to achieve my objective?

**Comment by sachinprasadhs** [comment]
Could you please refer this answer which explains about the above point.
https://stackoverflow.com/questions/69133906/

**Comment by xlnwel** [comment]
Hi @sachinprasadhs. I've read the link and understand your point. But I'm wondering if there is some way to avoid recomputing `inner` inside `outer` in the following link since `inner` may be performed multiple times before calling `outer` and repeating `inner` inside `outer` may be quite computationally expensive. Maybe with some lower-level techniques than `tf.function` in TF?

https://colab.research.google.com/drive/10V4V5Hr25NZehWE2TjFPD0-jtGpCFDMa?usp=sharing#scrollTo=O9G5leXLeexD

**Comment by xlnwel** [comment]
Hello, are there any updates, @sachinprasadhs, @sushreebarsa?

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
