### ISSUE TITLE
C API Tensor data type doesn't have flat() to convert into a Eigen::Tensor

### ISSUE THREAD

**Issue by YogaVicky** [tensorflow/tensorflow#56531]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Feature Request

### Source

binary

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux 

### Mobile device

07010841551

### Current Behaviour?

```shell
Hi there!
I am trying to convert my TF_Tensor datatype object into a eigen tensor(I am using the tensorflow C API).When I am using the C++ tensorflow API,I use the flat() method but there's no such thing available in the C API TF_Tensor.
Could someone please check and tell me??

Thanks,
Yoga
```

### Standalone code to reproduce the issue

```shell
// In C++:
auto input = input_tensor.flat<int32>();

// In C:
No method available
```

### Relevant log output

_No response_</details>

**Comment by jblespiau** [comment]
I am not sue I understand the highlight. I haven't opened this bug, and I am not a developer of tensorflow. How is that related to me?

**Comment by cantonios** [comment]
@YogaVicky unfortunately I don't think we currently have a method of converting directly from a c `TF_Tensor` to a c++ `tensorflow::Tensor`, which would get you what you want. 

You can use the c api to extract the datatype, element count, and data pointer, then use this to manually construct your own `Eigen::TensorMap`.  That would look something like:
```
TF_DataType dtype = TF_TensorType(tensor);
int64_t element_count = TF_TensorElementCount(tensor);
void* data = TF_TensorData(tensor);

switch (dtype) {
  case TF_FLOAT:
   auto flat = Eigen::TensorMap<Eigen::Tensor<float, 1, Eigen::RowMajor, Eigen::DenseIndex>, Eigen::Aligned>(data, element_count);
   // ...
   break;
}
```

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
