### ISSUE TITLE
Masking tensor with boolean vector raises an error, while tf.boolean_mask works

### ISSUE THREAD

**Issue by lucasdavid** [tensorflow/tensorflow#56539]
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8.10

### Current Behaviour?

We can mask tensors to extract their elements (in the first `k` axes) using a boolean tensor of rank `k`:

```py
maps = tf.reshape(tf.range(4*4*5), (4, 4, 5))
rows = tf.constant([False, True, False, True])
maps[rows].shape            # TensorShape([2, 4, 5])
tf.boolean_mask(maps, rows).shape  # TensorShape([2, 4, 5])
```

However, it's impossible to do so if I want to mask other axis than the first:
```py
maps = tf.reshape(tf.range(4*4*5), (4, 4, 5))
labels = tf.constant([False, True, False, True, False])
tf.boolean_mask(maps, labels, axis=2).shape  # TensorShape([4, 4, 2])
maps[:, :, labels].shape            # TypeError: Only integers, slices (`:`), [...] are valid indices, got <tf.Tensor: shape=(5,), dtype=bool, ...)>
maps[..., labels].shape            # TypeError: Only integers, slices (`:`), [...] are valid indices, got <tf.Tensor: shape=(5,), dtype=bool, ...)>
```

I expected that `maps[:, :, labels]` had the exact same behavior of `tf.boolean_mask(maps, labels, axis=2)`;
and `maps[..., labels] == tf.boolean_mask(maps, labels, axis=-1)`.

### Standalone code to reproduce the issue

```py
import tensorflow as tf

maps = tf.reshape(tf.range(4*4*5), (4, 4, 5))
labels = tf.constant([False, True, False, True, False])
print(tf.boolean_mask(maps, labels, axis=2).shape)  # TensorShape([2, 4, 5])
print(maps[:, :, labels].shape)
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/mnt/files/Workspace/envs/tf/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/mnt/files/Workspace/envs/tf/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 907, in _check_index
    raise TypeError(_SLICE_TYPE_ERROR + ", got {!r}".format(idx))
TypeError: Only integers, slices (`:`), ellipsis (`...`), tf.newaxis (`None`) and scalar tf.int32/tf.int64 tensors are valid indices, got <tf.Tensor: shape=(5,), dtype=bool, numpy=array([False,  True, False,  True, False])>
>>>
```

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v3.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/663be65a16804a68f7d8ac63387c2595/56539.ipynb).

**Comment by cantonios** [comment]
Correct, our tensor indexing API currently doesn't support mixed slicing + boolean indexing.  If you want to mask a single axis, you need to use `boolean_mask`.

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
