### ISSUE TITLE
Reproducible sparse-dense matrix multiplication

### ISSUE THREAD

**Issue by renatobellotti** [tensorflow/tensorflow#56547]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

v2.9.0-18-gd8ce9f9c301 2.9.1

### Custom Code

No

### Current Behaviour?

```shell
There is currently no deterministic sparse-dense matrix multiplication implementation on the GPU. I would like to have one.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
tf.keras.utils.set_random_seed(3948)
tf.config.experimental.enable_op_determinism()

m = tf.SparseTensor(
    indices=[[0, 0], [0, 1]],
    values=np.array([1, 2], dtype=np.float32),
    dense_shape=(3, 2),
)
v = tf.constant([[1], [1]], dtype=tf.float32)

tf.sparse.sparse_dense_matmul(m, v)
```

### Relevant log output

```shell
UnimplementedError: A deterministic GPU implementation of SparseTensorDenseMatmulOp is not currently available. [Op:SparseTensorDenseMatMul]
```
</details>

**Comment by sushreebarsa** [comment]
@renatobellotti Could you please refer this [thread](https://stackoverflow.com/questions/50744565/how-to-handle-non-determinism-when-training-on-a-gpu) and let us know if it helps? Thank you!

**Comment by renatobellotti** [comment]
@sushreebarsa This is what I tried (see example code). The problem is that the sparse dense matrix multiplication implementation does not have a reproducible version.

**Comment by renatobellotti** [comment]
Has somebody had the time to look into this?

**Comment by mohantym** [comment]
Yes @renatobellotti ! 
I can confirm that workarounds are not working for sparse-dense multiplication in GPU mode. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/94eef9660238c07f2b0b600d9a2fe5df/git_56547.ipynb#scrollTo=ou1eAMNWxFjp), [2.9](https://colab.sandbox.google.com/gist/mohantym/06ccb760628d6af6b21d835a50fc9165/git_56547.ipynb#scrollTo=WB-45fTlxRyn) and [nightly](https://colab.sandbox.google.com/gist/mohantym/31be331038a45eea092b531ffd59380e/git_56547.ipynb#scrollTo=WB-45fTlxRyn) for reference.
Thank you!

**Comment by renatobellotti** [comment]
@mohantym Thanks for your answer! Is there a chance that this will be fixed soon? I don't want to be rude and I understand that priorities of the project might not align with my own. I'm working on a project where reproducibility is crucial, so this issue is a deal-breaker to use TensorFlow. I would like to know what I can expect. :)

**Comment by ngc92** [comment]
Note that while tf does not offer a *GPU* implementation, but it appears that you can get determinism if you force things to run on CPU, e.g. the following code works
```
import numpy as np
import tensorflow as tf
tf.keras.utils.set_random_seed(3948)
tf.config.experimental.enable_op_determinism()

m = tf.SparseTensor(
    indices=[[0, 0], [0, 1]],
    values=np.array([1, 2], dtype=np.float32),
    dense_shape=(3, 2),
)
v = tf.constant([[1], [1]], dtype=tf.float32)

with tf.device("cpu:0"):
    tf.sparse.sparse_dense_matmul(m, v)
```

**Comment by cantonios** [comment]
The issue has to do with order of operations.  The GPU matmul is split across many GPU threads and accumulated in the order those threads complete.  Since accumulation (or floating-point math in general) is order-dependent, we cannot guarantee _exact_ bitwise reproducibility.

CPU determinism essentially does a single-threaded matmul, so you're killing performance.

> I'm working on a project where reproducibility is crucial, so this issue is a deal-breaker to use TensorFlow.

Results should already be reproducible within expected floating-point accumulation errors.  If you need exact bit reproducibility, you essentially need to disable any multithreading, and most GPU kernels.

Note that even on CPU, "determinism" is only guarnateed with the exact same TF build, and on the exact same hardware.  Change either the hardware or the build, and you'll potentially get different results, again because of order of operations, or because of availability of different instructions (e.g. FMA).

Nobody is currently working on this - it would need to be an an external contribution.

**Comment by renatobellotti** [comment]
Thanks for the detailed answer.

**Comment by sushreebarsa** [comment]
@renatobellotti I was able to run the code successfully using the latest TF v2.13, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/92c2a76a74eab37e380f926fed88f349/56547.ipynb#scrollTo=BZlN8NJzcmPM) here for reference. Thank you!
