### ISSUE TITLE
iOS uses 100%+ CPU to run tflite

### ISSUE THREAD

**Issue by jingjing0327** [tensorflow/tensorflow#56548]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
MAC OS 12.2
- TensorFlow installed from (source or binary):
binary
- TensorFlow version (or github SHA if from source):
2.9.1

**Provide the text output from tflite_convert**

```
tflite_convert --output_file exported_tflite_0000004/2222od_model.tflite --saved_model_dir exported_tflite_0000004/saved_model
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

![截屏2022-06-23 21 02 43](https://user-images.githubusercontent.com/7891692/175305025-92f0bbbb-dce1-40a2-96e3-540519192665.png)
is this normal?

**Comment by jingjing0327** [comment]
Yeah,during the inference part ,thank you for your response.
![2022-06-24 09 43 04](https://user-images.githubusercontent.com/7891692/175446448-18388b28-a6ba-4e21-9f8f-dd29dbcb2586.png)

**Comment by jingjing0327** [comment]
1) use MobileNetV2 640x640 train 
2) export tfite file
3) import tflite file in the [tensorflow/examples/lite/](https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/ios)
4) fixed some params
5) run object_detection product 
6) tflite return result is very good.
7) but my all devices(iphone x\iphone12\iphone 8p\ipad5) uses CPU 100%+

The strange thing is use demo tflite file,uses cpu 20%.

Can you show me where I have gone off the rails?

**Comment by mohantym** [comment]
@jingjing0327 ! Could you share your params too. Thank you!

**Comment by jingjing0327** [comment]
Yeah, use CoreMLDelegate 
![截屏2022-06-24 15 58 02](https://user-images.githubusercontent.com/7891692/175490763-7719c29a-2154-4999-814f-9d1cd5189c05.png)
![截屏2022-06-24 15 58 26](https://user-images.githubusercontent.com/7891692/175490819-1c762cbb-846b-4a0f-8917-89c9ff80cb4d.png)
I don't know what else to offer, because I use [https://github.com/tensorflow/examples/tree/master/lite/examples/object_detection/ios](url) code.
Thank you!

**Comment by jingjing0327** [comment]
I'll share the tflite file and label.txt with you.
[tflite.zip](https://github.com/tensorflow/tensorflow/files/8974343/tflite.zip)
Thank you!

**Comment by jingjing0327** [comment]
[tflite_cpu_100_source.zip](https://github.com/tensorflow/tensorflow/files/8974378/tflite_cpu_100_source.zip)
Hi,I share the source code with you,this is the project with this issue.

**Comment by mohantym** [comment]
Hi @sachinprasadhs ! Could you please look at this issue. Thank you!

**Comment by roserg** [comment]
> [tflite_cpu_100_source.zip](https://github.com/tensorflow/tensorflow/files/8974378/tflite_cpu_100_source.zip) Hi,I share the source code with you,this is the project with this issue.

Hi, I tried to run this project and with CoreML delegate it works. But when I try to run Metal delegate I can see this errors:
TensorFlow Lite Error: Following operations are not supported by GPU delegate:

CUSTOM TFLite_Detection_PostProcess: TFLite_Detection_PostProcess

DEQUANTIZE: 

PACK: OP is supported, but tensor type/shape isn't compatible.

RESHAPE: OP is supported, but tensor type/shape isn't compatible.

111 operations will run on the GPU, and the remaining 218 operations will run on the CPU.

TensorFlow Lite Error: TfLiteMetalDelegate Prepare: Currently external can be used only for graph inputs/outputs

TensorFlow Lite Error: Node number 329 (TfLiteMetalDelegate) failed to prepare.

TensorFlow Lite Error: Restored original execution plan after delegate application failure.

Failed to create the interpreter with error: Failed to create the interpreter.

[2022-07-21 10](tel:2022-07-21 10):29:40.275466+0200 ObjectDetection[592:18798] [UIFocus] UITableView implements focusItemsInRect: - caching for linear focus movement is limited as long as this view is on screen.

ObjectDetection/ViewController.swift:56: Fatal error: Failed to load model

[2022-07-21 10](tel:2022-07-21 10):29:40.314699+0200 ObjectDetection[592:18798] ObjectDetection/ViewController.swift:56: Fatal error: Failed to load model


And I can not run it. 
But from errors and from look at the card4detect model probably clear why cpu load is so high. Because this model in the best case executed only partially on GPU. It has a lot of unsupported ops/cases. I can see 5d tensors in the model, but gpu supports max 4d.

**Comment by jingjing0327** [comment]
oh my god, I modified the model.  now the CPU load is 30%，thank you very much!
