### ISSUE TITLE
CSV generated by the code in the "Human Pose Classification with MoveNet and TensorFlow Lite" example inconsistent

### ISSUE THREAD

**Issue by rjfc** [tensorflow/tensorflow#56553]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows

### Python version

3.8.0

### Current Behaviour?

Running [part 1](https://www.tensorflow.org/lite/tutorials/pose_classification#part_1_preprocess_the_input_images) here (after running the preparation code) generates CSVs different from the CSVs in the section [here](https://www.tensorflow.org/lite/tutorials/pose_classification#optional_download_the_preprocessed_dataset_if_you_didnt_run_part_1). 

The CSVs should be the same, but the CSVs generated by running the code has discrete keypoint coordinates while the CSVs linked in the above section have decimal keypoint coordinates. I believe that the code in the example is missing some scaling code. In the `def process(self, per_pose_class_limit=None, detection_threshold=0.1):` function, under the `# Get landmarks and scale it to the same size as the input image` comment, I don't think the landmarks are actually scaled:
``` 
pose_landmarks = np.array(
    [[keypoint.coordinate.x, keypoint.coordinate.y, keypoint.score]
        for keypoint in person.keypoints],
    type=np.float32)
```

Yoga CSVs generated by running the code: 
[yoga_train_data.csv](https://github.com/tensorflow/tensorflow/files/8969168/train_data.csv)
[yoga_test_data.csv](https://github.com/tensorflow/tensorflow/files/8969170/test_data.csv)

Yoga CSVs linked in the code for skipping part 1 which claims to be identical:
[yoga_train_data.csv](https://github.com/tensorflow/tensorflow/files/8969172/yoga_train_data.csv)
[yoga_test_data.csv](https://github.com/tensorflow/tensorflow/files/8969171/yoga_test_data.csv)

### Standalone code to reproduce the issue

[https://www.tensorflow.org/lite/tutorials/pose_classification](https://www.tensorflow.org/lite/tutorials/pose_classification)

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
Hi @rjfc 

The issue seems to be resolved with TF 2.12. I have observed with the `test_data.csv` which has the  has discrete keypoint coordinates.

 Please find the gist [here](https://colab.research.google.com/gist/pjpratik/c1213207cda63c7257b2647df3cfc952/56553.ipynb) and the head data below:

|index|file\_name|NOSE\_x|NOSE\_y|NOSE\_score|LEFT\_EYE\_x|LEFT\_EYE\_y|LEFT\_EYE\_score|RIGHT\_EYE\_x|RIGHT\_EYE\_y|RIGHT\_EYE\_score|LEFT\_EAR\_x|LEFT\_EAR\_y|LEFT\_EAR\_score|RIGHT\_EAR\_x|RIGHT\_EAR\_y|RIGHT\_EAR\_score|LEFT\_SHOULDER\_x|LEFT\_SHOULDER\_y|LEFT\_SHOULDER\_score|RIGHT\_SHOULDER\_x|
|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|---|
|0|chair/guy3\_chair070\.jpg|150\.0|101\.0|0\.69633734|155\.0|96\.0|0\.81174135|145\.0|96\.0|0\.7756405|163\.0|97\.0|0\.7792505|140\.0|97\.0|0\.5823091|172\.0|112\.0|0\.80950165|133\.0|
|1|chair/guy3\_chair071\.jpg|151\.0|103\.0|0\.7204095|155\.0|99\.0|0\.86422026|146\.0|98\.0|0\.80267566|163\.0|99\.0|0\.7085024|141\.0|99\.0|0\.54238826|173\.0|113\.0|0\.79421246|132\.0|
|2|chair/guy3\_chair072\.jpg|150\.0|105\.0|0\.724821|155\.0|100\.0|0\.84365886|146\.0|100\.0|0\.79857314|164\.0|101\.0|0\.74888885|142\.0|101\.0|0\.6859938|174\.0|114\.0|0\.75105125|134\.0|
|3|chair/guy3\_chair073\.jpg|150\.0|107\.0|0\.7161201|155\.0|102\.0|0\.63974524|146\.0|101\.0|0\.5465567|163\.0|103\.0|0\.7929039|142\.0|102\.0|0\.725726|174\.0|116\.0|0\.85323805|134\.0|
|4|chair/guy3\_chair074\.jpg|149\.0|109\.0|0\.49887785|154\.0|104\.0|0\.7880822|145\.0|103\.0|0\.65956235|163\.0|104\.0|0\.57862025|142\.0|105\.0|0\.62644887|174\.0|117\.0|0\.7471118|134\.0|

Thanks.
