### ISSUE TITLE
Issue with Tensorflow Binary and oneAPI while flask deployment

### ISSUE THREAD

**Issue by Siddharth1India** [tensorflow/tensorflow#56561]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

tensorflow-cpu

### Custom Code

No

### Python version

3.7

### CUDA/cuDNN version

NA

### GPU model and memory

NA

### Current Behaviour?

```shell
I created Flask App with tensorflow model and it is working fine in local machine. However while deploying, it is giving me following warning because of which build is successful but deployment failed. Error shows up with tensorflow and tensorflow-cpu both. I am not sure how to solve the same.
Please help.
```

### Standalone code to reproduce the issue

```shell
Issue happens not due to code but something else.
```

### Relevant log output

```shell
Jun 24 03:47:17 PM  ==> Starting service with 'gunicorn app:app'
Jun 24 03:47:54 PM  2022-06-24 10:17:54.733536: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
Jun 24 03:47:54 PM  To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
```
</details>

**Comment by tilakrayal** [comment]
@Siddharth1India,
In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem and the error log. Thank you!

**Comment by Siddharth1India** [comment]
@tilakrayal Issue turned out to be RAM of machine. 
Changing machine to higher end solved issue, Thanks.
