### ISSUE TITLE
Gradient computation through tf.linalg.eigh does not work with complex-valued input in XLA

### ISSUE THREAD

**Issue by faycalaa** [tensorflow/tensorflow#56619]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

Yes

### Current Behaviour?

```shell
Computing the gradient through tf.linalg.eigh() fails in XLA when the input of the function is complex-valued (tf.complex64).
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

h_real = tf.Variable([[1., 1.], [1., 1.]], dtype=tf.float32, trainable=True)
h_imag = tf.Variable([[0.0, 1.], [-1., 0.0]], dtype=tf.float32, trainable=True)

@tf.function(jit_compile=True)
def test():
    with tf.GradientTape() as tape:
        # Build Hernitian matrix
        h = tf.complex(h_real, h_imag)
        # Compute singular values
        s,_ = tf.linalg.eigh(h)
        loss = tf.math.real(s[0])
    grad = tape.gradient(loss,[h_real,h_imag])
    return grad

g = test()
```

### Relevant log output

```shell
InvalidArgumentError: Binary op add with different element types: f32[2,2] and c64[].
	 [[{{node gradient_tape/add}}]] [Op:__inference_test_245]
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0bc8bfa540cc90beaedf0e25fca7aaf0/56619.ipynb).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
