### ISSUE TITLE
Get Input/Output shapes of node (ex: Conv, Add) during the inferencce

### ISSUE THREAD

**Issue by Alavandar08** [tensorflow/tensorflow#56622]
Hi,

I would like to know how can we access input and output shapes of a node (ex: Convolution, Add) from the reampper file. 

I am trying to access input shapes in function [IsAddWithNoBroadcast] (https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/core/grappler/optimizers/remapper.cc#L843) but I am not successful in retrieving the input shapes of node.

Can someone help me to get the input shapes of node with in a remapper file?

Thanks!!

**Comment by tilakrayal** [comment]
Hi @Alavandar08,
We see that the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) has not been filled, could you please do so as it helps us analyse the issue [tf version, steps followed before you ran into this error or stand alone code to reproduce the issue faced] or if possible share a colab gist with the issue reported. Thank you!

**Comment by Alavandar08** [comment]
Hi @tilakrayal 
This issue (i.e getting shapes is not specific to particular version. It is across all versions). For easier reference we can consider    
(TF-2.9).
From my experiments I am trying to dump the shapes into a log file and verify if the logs been printed or not.

I tried to get node input shapes from couple of places
some of them are - 
1. [IsAddwithNoBroadcast](https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/core/grappler/optimizers/remapper.cc#L843) 
We have access to node of type 'NodeDef'

2. [SymbolicshapesEqual](https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/core/grappler/utils/symbolic_shapes.cc#L76)
We have access to input properties of a node that are obtained from context of type 'TensorShapeProto'

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
