### ISSUE TITLE
gradient computation throws InvalidArgumentError in `tf.gather_nd` 

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#56628]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9

### Current Behaviour?

```shell
A bug happened during gradient computation of `tf.gather_nd` with `indices = [1,1]`. The code below is a minimized snippet. The forward pass of `tf.gather_nd` succeeds and the output `res` is correct. However, if I take the gradient,  it throws `InvalidArgumentError`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
params = tf.random.uniform([3, 2], dtype=tf.float32)
indices = [1,1]
res = tf.gather_nd(params, indices)
res = tf.reduce_sum(res)
print(res) # success

with tf.GradientTape(persistent=True,) as g:
  g.watch(params)
  res = tf.gather_nd(params, indices)
  res = tf.reduce_sum(res)
grad = g.gradient(res, params)
print(grad) # InvalidArgumentError
```

### Relevant log output

```shell
InvalidArgumentError: Updates shape must have rank at least one. Found:[] [Op:ScatterNd]
```
</details>

**Comment by sushreebarsa** [comment]
@chunduriv I was able to replicate the issue, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/75ced825f65ef05971aac44ca5aec78b/56628.ipynb#scrollTo=SeiNbQ8nns1C) here. Thank you!

**Comment by cantonios** [comment]
I believe the index dimensions should be
```
indices = [[1,1]]
```
which allows this to work.

**Comment by sachinprasadhs** [comment]
@VictoriaGriffith , As per the above comment, please find the working [Gist](https://colab.sandbox.google.com/gist/sachinprasadhs/213513c68d4786382a9a90280e94d37d/56628.ipynb) with modified indices input.

**Comment by VictoriaGriffith** [comment]
Thanks @cantonios @sachinprasadhs ! Indeed changing the indices to be rank-`2` would make the gradient work. 

However, I believe there is still a bug here. When `indices = [1,1]`, the direct invocation of `tf.gather_nd` will succeed, is this an expected behaviour? The [documentation](https://www.tensorflow.org/api_docs/python/tf/gather_nd) does not make it clear whether indices should have rank `>=2`. If that is the case, the forward pass of `tf.gather_nd` should raise an exception too. If `indices = [1,1]` can be broadcasted in the forward pass, then the backward pass of `tf.gather_nd` should also allow this.

**Comment by cantonios** [comment]
@VictoriaGriffith yes, we're trying to decide what to do about that.  Thanks for bringing this up.  We have the same "issue" across all back-ends: that `gather_nd` supports a single index tuple, but `scatter_nd` does not.  However, it's not currently a high priority for us, since there is a work-around.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
