### ISSUE TITLE
TF test failure: //tensorflow/lite/kernels/shim:shape_test

### ISSUE THREAD

**Issue by psunn** [tensorflow/tensorflow#56623]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

latest master branch

### Custom Code

No

</details>
### Current Behaviour?

```shell
TEST //tensorflow/lite/kernels/shim:shape_test failing on TF upstream/master:

tensorflow/lite/kernels/shim/shape_test.cc:74: Failure
Expected equality of these values:
  "[]"
  Shape({}).ToString()
    Which is: "?"

tensorflow/lite/kernels/shim/shape_test.cc:81: Failure
Value of: Shape({}).FullyDefined()
  Actual: false
Expected: true
```

### Standalone code to reproduce the issue

```shell
bazel test //tensorflow/lite/kernels/shim:shape_test --test_output=all
```

**Comment by mohantym** [comment]
@psunn! 
Thanks for reporting this bug .The issue is not replicating in the [2.8](https://colab.sandbox.google.com/gist/mohantym/25c109bbd4ca675f0294084707902c34/tensorflow-ranking.ipynb#scrollTo=vDXp-0XmqYkc)/[2.9](https://colab.sandbox.google.com/gist/mohantym/f9ede3f986518cf929732b3fb79badb6/tensorflow-ranking.ipynb#scrollTo=vDXp-0XmqYkc) version though. 
Can we stick to stable branches for a while. 
Thank you!

**Comment by mohantym** [comment]
@psunn! Could we stick to the stable versions for a while (2.8/2.9). Thank you!

**Comment by psunn** [comment]
TESTs would pass when compiling with gcc>=8.1
code snippet to stand out the issue: https://godbolt.org/z/6o76cTM3W

**Comment by psunn** [comment]
Closed as we think it's a compiler issue.
