### ISSUE TITLE
Tensorflow lite for microcontroller not support the model with float32 input/output and int8 weights.

### ISSUE THREAD

**Issue by FragrantRookie** [tensorflow/tensorflow#56626]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

No

### OS Platform and Distribution

ubuntu20

### Python version

3.9

### Current Behaviour?

```shell
Tensorflow lite for microcontroller not support the model with float32 input/output and int8 weights.
```

### Standalone code to reproduce the issue

```shell
Tensorflow lite for microcontroller not support the model with float32 input/output and int8 weights.
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @FragrantRookie ! 
Could you post a standalone code to understand the feature request too. 
Thank you!

**Comment by FragrantRookie** [comment]
> Hi @FragrantRookie ! Could you also post a minimal standalone code to understand the feature request . Thank you!

Sorry, I didn't give enough information.I am doing some tests so that I can better describe my problem.I am deploying the model to DSP or MCU. This model was mentioned in the previous question. This is the link: [https://github.com/breizhn/DTLN](url) or [https://github.com/tensorflow/tensorflow/issues/56505](url)
Because some layers in TF Lite for micro do not support int16, and the main object of computing power consumption in the target model is the full connection layer, I am going to use float type input and output and int8 type weight.
However, the problem is that the full connection layer(micro) currently does not support the mixed model of float and int8, so I modified the code myself. At present, the mixed model has been able to get the correct inference result.
Because the way I make the hybrid model work is to transform int8 back to float32, the new problem is that the computational power consumption is huge.
I consider quantifying the input to int16 only in the full connection layer. The problem with this is that when the model contains multiple fully connected layers, I cannot accurately know the input range of each fully connected layer, so I cannot accurately quantify the input of each layer.

**Comment by mohantym** [comment]
Ok @FragrantRookie !
Thanks for the update. @sachinprasadhs ! Could you please look at this issue.
Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
