### ISSUE TITLE
TensorFlow doesn't use all available memory on NVIDIA GPU

### ISSUE THREAD

**Issue by otavio-silva** [tensorflow/tensorflow#56661]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.6

### Custom Code

No

### OS Platform and Distribution

Windows 11 Pro 21H2

### Python version

3.7.13

### CUDA/cuDNN version

11.3.1/8.2.1

### GPU model and memory

NVIDIA GeForce RTX 3070 Laptop GPU 8GB

### Current Behaviour?

```shell
When using GPU VRAM, TensorFlow only uses 5.6GB of the 8.0GB available
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
v = tf.Variable(tf.linspace(-10., 10, 10000))
```

### Relevant log output

```shell
2022-07-02 17:25:40.770168: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-02 17:25:41.122377: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1510] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5482 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6

Sat Jul  2 17:26:11 2022
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 516.59       Driver Version: 516.59       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   52C    P8    12W /  N/A |   5740MiB /  8192MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A     27356      C   ...onda3\envs\tf2\python.exe    N/A      |
+-----------------------------------------------------------------------------+
```
</details>

**Comment by gowthamkpr** [comment]
It might be due to the WDDM 3.x driver of Windows 11 that might be causing this issue. Please take a look at this [solution](https://github.com/tensorflow/tensorflow/issues/22623#issuecomment-430482857). Thanks!

**Comment by otavio-silva** [comment]
@gowthamkpr this is not a realistic solution, considering that I use my machine for personal stuff, college and work, just downgrading back to Windows 7 is not a possibility. But thanks for explaining me what exactly is happening, I hope a solution comes eventually.

**Comment by gowthamkpr** [comment]
@otavio-silva Can you please try it withthe latest version of tensorflow i.e. 2.9 and let me know if the issue still persists. Thanks!

**Comment by otavio-silva** [comment]
```
2022-07-18 18:06:15.578161: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX AVX2
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-07-18 18:06:16.021970: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1532] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5484 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 3070 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.6
```
```
>>> tf.version.VERSION
'2.9.1'
```
Same thing, issue still persists.

**Comment by hahouari** [comment]
Try setting memory_limit when initializing a logical device.
In my case I have an RTX 3060 6GB and I had the same problem with `tensorflow==2.9.1`, so this worked: 

```python
gpus = tf.config.list_physical_devices('GPU')
if gpus: 
    tf.config.set_logical_device_configuration(
        gpus[0],
        [tf.config.LogicalDeviceConfiguration(memory_limit=5292)]
    )

logical_gpus = tf.config.list_logical_devices('GPU')
print(len(gpus), "Physical GPU,", len(logical_gpus), "Logical GPUs")
```

Here is before setting memory_limit:

![Screenshot from 2022-08-12 16-26-25](https://user-images.githubusercontent.com/39862612/184389061-343b0f5c-6e51-4e36-a9e1-299bc5734e5d.png)

> `nvidia-smi` output
>
> ![Screenshot from 2022-08-12 16-36-28](https://user-images.githubusercontent.com/39862612/184391109-d700c438-fbdc-460e-8d78-8d3230bc5d73.png)

and after setting memry_limit to `5292MiB`:

![Screenshot from 2022-08-12 16-25-38](https://user-images.githubusercontent.com/39862612/184389094-3ab2ae9b-38a5-4ef2-8396-32eefc6dffb3.png)

> `nvidia-smi` output
>
> ![Screenshot from 2022-08-12 16-37-25](https://user-images.githubusercontent.com/39862612/184391170-94335aa1-3ef8-4b25-9121-b264c662444a.png)


The difference of memory between Tensorflow report and nvidia-smi probably has to do with other initialization that tensorflow has to do.

If you try to set memory limit to a value close to your VRAM size (in my case is `6144MiB`) you will get an `InternalError: Graph execution error` when you run `model.fit()` later, for me I could set memory_limit to `5844` leaving only 300~MiB for other processes and my model trains with no error.

**Comment by amzon-ex** [comment]
@hahouari This seems to work for me. Is there a way to automate this/set a global configuration?

**Comment by otavio-silva** [comment]
Just tested with TensorFlow 2.9.1, this exact behavior persists. The workaround proposed by @hahouari seems  to work nicely though. The problem is, shouldn't TensorFlow dead with this automatically?

**Comment by gaikwadrahul8** [comment]
Hi, @otavio-silva 

Apologies for the delay and workaround provided by @hahouari should work and even we have official documentation w.r.t `LogicalDeviceConfiguration` [here](https://www.tensorflow.org/api_docs/python/tf/config/LogicalDeviceConfiguration) through which you can set GPU `memory_limit`, you can also enable memory growth using [tf.config.experimental.set_memory_growth](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth) and please refer our [Use a GPU](https://www.tensorflow.org/guide/gpu) documentation. if your model consume all your allocated GPU memory then you will get memory runs out error and to avoid that you can send your large dataset into batches with the help of `tf.data.Dataset` to know more about `tf.data.Dataset` you can refer this official documentation [here](https://www.tensorflow.org/api_docs/python/tf/data/Dataset) and also same [discussion](https://discuss.tensorflow.org/t/getting-memory-error-when-training-a-larger-dataset-on-the-gpu/13270) going on our Tensorflow Forum, I hope it will help you to resolve your issue 

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? 

If issue still persists, please let us know ?

Thank you!

**Comment by otavio-silva** [comment]
@gaikwadrahul8 I understand the proposed solutions, but why does TensorFlow does not allocate more memory?

**Comment by gaikwadrahul8** [comment]
Hi, @otavio-silva 

Apologize for the delayed response and In some cases it is desirable for the process to only allocate a subset of the available memory, or to only grow the memory usage as is needed by the process. TensorFlow provides two methods to control this.

The first option is to turn on memory growth by calling [tf.config.experimental.set_memory_growth](https://www.tensorflow.org/api_docs/python/tf/config/experimental/set_memory_growth), which attempts to allocate only as much GPU memory as needed for the runtime allocations: it starts out allocating very little memory, and as the program gets run and more GPU memory is needed, the GPU memory region is extended for the TensorFlow process.

The second method is to configure a virtual GPU device with [tf.config.set_logical_device_configuration](https://www.tensorflow.org/api_docs/python/tf/config/set_logical_device_configuration) and set a hard limit on the total memory to allocate on the GPU.

This is useful if you want to truly bound the amount of GPU memory available to the TensorFlow process. This is common practice for local development when the GPU is shared with other applications such as a workstation GUI.

Tensorflow provides GPU memory allocation configuration controls to users because different use-cases have different requirements with GPU memory allocation 

I hope it make sense, Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ?

If you need any further assistance or if you have any further questions please let us know ?

Thank you!

**Comment by otavio-silva** [comment]
@gowthamkpr I understand, but TensorFlow should deal with memory in a more efficient manner.
Memory growth should be enabled by default and it should recognize at least 80% of the device memory.

**Comment by gaikwadrahul8** [comment]
Hi, @otavio-silva 

As I checked your `nvidia-smi `output and you're using `cudatoolkit==11.7` with `Tensorflow version==2.6` and as per our official documentation you should install `cudatoolkit==11.2` and `cudnn==8.1.0` for Tensorflow-GPU and I believe you followed our [official documentation](https://www.tensorflow.org/install/pip#windows-wsl2) to install Tensorflow with gpu support 

If you would like a particular operation to run on a device of your choice instead of what's automatically selected for you, you can use `with tf.device` to create a device context, and all the operations within that context will run on the same designated device. you can refer this [section](https://www.tensorflow.org/guide/gpu#overview)

Could you please try to install Tensorlfow-GPU with latest version of `Tensorflow==2.11` by following above instructions and please run this sample Google Colab [notebook](https://colab.research.google.com/gist/gaikwadrahul8/43b8f78bbbdb9317f57936c405c683a1/gpu-performance-test.ipynb) to check whether complete GPU utilisation happening or not through task manager ?

If issue still persists please let us know with `nvidia-smi `output and screenshot of windows task manager? Thank you!
