### ISSUE TITLE
Add support for kwargs for tf.recompute_grad API for graph mode

### ISSUE THREAD

**Issue by pranavladkat** [tensorflow/tensorflow#56692]
### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.9

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

3.9

### Current Behaviour?

Currently `tf.recompute_grad()` API do not support keyword arguments  when run in graph mode. It throws ValueError from here: 

https://github.com/tensorflow/tensorflow/blob/d8ce9f9c301d021a69953134185ab728c1c248d3/tensorflow/python/ops/custom_gradient.py#L404-L408 

This will be a useful addition for ease of use.

### Standalone code to reproduce the issue

```shell
This can be reproduced with any example. Even simply passing `training=True` during forward pass will raise this issue when run in graph mode
```

**Comment by pranavladkat** [comment]
Hi, any update on this issue?

**Comment by nyngwang** [comment]
Hi, I'm not the staff of the Repo. but if got the error because you put the `tf.recompute_grad` around the `__call__` or `call`(if you use `tf.keras`) method, then you might try to create a nested function inside `__call__` (or `call`)  and wrap it with `tf.recompute_grad`:

```python
def call(self, x):
  @tf.recompute_grad
  def foo(x):
     # original content
  return foo(x)
```

**Comment by pranavladkat** [comment]
The issue with above suggestion is that it does not work with nested modules. If one of the layer is deep inside other layers which uses kwarg, this approach does not work.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
