### ISSUE TITLE
InactiveRpcError of RPC that terminated with: status = StatusCode.FAILED_PRECONDITION, details = "Attempting to use uninitialized value dense_2/bias

### ISSUE THREAD

**Issue by ViktorKhLoopMe** [tensorflow/tensorflow#56698]
-----------------------
### [InactiveRpcError of RPC that terminated with: status = StatusCode.FAILED_PRECONDITION, details = "Attempting to use uninitialized value dense_2/bias]

Getting following error from my python grpc client when trying predicting wuth the tf-serving server:
```
_InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
    status = StatusCode.FAILED_PRECONDITION
    details = "Attempting to use uninitialized value dense_2/bias
     [[{{node dense_2/bias/read}}]]"
    debug_error_string = "{"created":"@1654790154.977771219","description":"Error received from peer ipv4:10.1.25.14:9002","file":"src/core/lib/surface/call.cc","file_line":903,"grpc_message":"Attempting to use uninitialized value dense_2/bias\n\t [[{{node dense_2/bias/read}}]]","grpc_status":9}"
>
```

I found description of problem but it is not informative for me
Operation was rejected because the system is not in a state required for the operation’s execution. (https://grpc.github.io/grpc/python/grpc.html#grpc-status-code)

### System information
python 3.9 
tensorflow-serving-api==2.8.0
tensorflow==2.8.0

What can be the reason for this error and how it could be fix?

**Comment by mohantym** [comment]
Hi @ViktorKhLoopMe !
Sorry for the late response. Could you share the link to gist to your model file. 
Thank you!

**Comment by ViktorKhLoopMe** [comment]
Hi @mohantym

Where should exactly I need use `tf.global_variables_initializer().run() `?

running this line I got error :
`AttributeError: module 'tensorflow' has no attribute 'global_variables_initializer'`

Analysing relevant [thread](https://github.com/tensorflow/serving/issues/594) I decided update versions to 2.9.0
And After updating I got error:
`status = StatusCode.UNAVAILABLE`

**Comment by mohantym** [comment]
Hi @ViktorKhLoopMe !
Could you please provide a Colab gist or re-produceable code again.
Thank you!

**Comment by ViktorKhLoopMe** [comment]
@mohantym @gowthamkpr Here is code how I set up serving and how I predict
https://gist.github.com/ViktorKhLoopMe/bd4a7ef6f605f96253cb7537ccd15ae5

**Comment by gowthamkpr** [comment]
@gowthamkpr This is a user error. In order to debug, Can you please attach the code used build the model and  save it and also the plat form details. Also can you please attach the full stack trace. Thanks!!

**Comment by gowthamkpr** [comment]
@ViktorKhLoopMe Since this looks like a user error I need the entire code in colab to see where the issue is. I can't help with just the stack trace. Thanks!

**Comment by ViktorKhLoopMe** [comment]
@gowthamkpr Hello!
Here is code with model training and save
https://gist.github.com/ViktorKhLoopMe/54f5584f77c5c030c835f9678c02da8d

**Comment by gowthamkpr** [comment]
@ViktorKhLoopMe The issue here is that you are using `saved_model.Builder` which is from tensorflow 1.x.  Please try using `tf.saved_model.save()` or `tf.keras.saved_model.save()` for keras which is preferred way of saving model in tensorflow 2.x. For more details you can look at the following [migration guide](https://www.tensorflow.org/guide/migrate/saved_model). Thanks!

**Comment by ViktorKhLoopMe** [comment]
@gowthamkpr  Can you produce how I suppose save model with signatures in V2?

like I used to saved in V1

`builder = tf.saved_model.builder.SavedModelBuilder(export_path)

    model_input = tf.saved_model.utils.build_tensor_info(model.input)
    model_output = tf.saved_model.utils.build_tensor_info(model.output)

    prediction_signature = (
        tf.saved_model.signature_def_utils.build_signature_def(
            inputs={'inputs': model_input},
            outputs={'output': model_output},
            method_name=tf.saved_model.signature_constants.PREDICT_METHOD_NAME))

    with K.get_session() as sess:
        builder.add_meta_graph_and_variables(
            sess=sess, tags=[tf.saved_model.tag_constants.SERVING],
            signature_def_map={
                'predict':
                    prediction_signature,
            })

        builder.save()
`

**Comment by ViktorKhLoopMe** [comment]
@gowthamkpr any comments?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
