### ISSUE TITLE
Bug in tf.test.compute_gradient for tf.keras.losses.categorical_hinge

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#56693]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Mobile device

n/a

### Python version

3.9

### Current Behaviour?

```shell
The numerical gradient and theoretical gradient for `tf.keras.losses.categorical_hinge` is different, one is `0.5`, the other is `0.333`. I think the numerical gradient is wrong.
```

### Standalone code to reproduce the issue

```shell
x = tf.zeros(shape=[2,3], dtype=tf.float64)
y = tf.zeros(shape=[2,3], dtype=tf.float64)
r = tf.keras.losses.categorical_hinge(x,y)
theoretical, numerical = tf.test.compute_gradient(tf.keras.losses.categorical_hinge, [x,y])
print(theoretical[1])
print(numerical[1])
```

### Relevant log output

```shell
[[0.33333333 0.33333333 0.33333333 0.         0.         0.        ]
 [0.         0.         0.         0.33333333 0.33333333 0.33333333]]
[[0.5 0.5 0.5 0.  0.  0. ]
 [0.  0.  0.  0.5 0.5 0.5]]
```
</details>

**Comment by mohantym** [comment]
Hi @chunduriv !
Could you look at this issue. Attached gist in[ 2.8](https://colab.sandbox.google.com/gist/mohantym/ef18fb3597f27f8c098417775d0e68af/git_56693_2-8.ipynb#scrollTo=szukxf4gZpoK), [2.9 ](https://colab.sandbox.google.com/gist/mohantym/64ef4463326281ac0bbe98463e444da3/git_56693_2-8.ipynb#scrollTo=szukxf4gZpoK)and [nightly](https://colab.sandbox.google.com/gist/mohantym/3b4f28ba39ddb566a22ccc155ce9fefc/git_56693_2-8.ipynb#scrollTo=9uMJp_c4PyWF) for reference.
Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
