### ISSUE TITLE
[XLA] Bincount dynamic output size in a loop

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#56769]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

master

### Custom Code

Yes

### Current Behaviour?

```shell
TF XLA fail with bincount with dynamic output shape in a loop
```

### Standalone code to reproduce the issue

```shell
!pip install tf-nightly-cpu
```

```python

import tensorflow as tf
@tf.function(jit_compile=True)
def bincount_test():
  for length in tf.range(2):
    values = tf.constant([1,1,2,3,2,4,4,5])
    output = tf.math.bincount(values, minlength=length) #[0 2 2 1 2 1]
  return output

 
print(bincount_test())
```

### Relevant log output

```shell
InvalidArgumentError: Input 1 to node `while/bincount/Bincount` with op Bincount must be a compile-time constant.

XLA compilation requires that operator arguments that represent shapes or dimensions be evaluated to concrete values at compile time. This error means that a shape or dimension argument could not be evaluated at compile time, usually because the value of the argument depends on a parameter to the computation, on a variable, or on a stateful operation such as a random number generator.
```
</details>

**Comment by bhack** [comment]
We had a similar case already for TPU https://github.com/tensorflow/tensorflow/issues/53051

**Comment by LukeWood** [comment]
Yep!  We'd benefit from this absolutely.

**Comment by bhack** [comment]
@LukeWood It seems that the bridge cannot automatically unroll the loop with `tf.range` so you need to use python `range`  in your Keras-cv implementaiton so it is unrolled in transformations.

The one at https://github.com/keras-team/keras/issues/15655#issuecomment-1029571189 instead could be a little bit different or probably related to another not automatically unrolled loop in `map_fn`.

**Comment by bhack** [comment]
@cheshire Is there a margin to do something more here? 

If not can we at least improve the error message in the code? As I think that the PR to `known_issues.md` is a little bit too marginal for the avg developer with the current error string in the code.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
