### ISSUE TITLE
[tflite/hexagon] The test output shape is not as expected

### ISSUE THREAD

**Issue by xbwee1024** [tensorflow/tensorflow#56784]
https://github.com/tensorflow/tensorflow/blob/6a2e3dcd5f215a641050877d7c302107adafe217/tensorflow/lite/delegates/hexagon/builders/tests/concat_test.cc#L177

As 4 inputs and shape is 1x2x1x2(nhwc) and axis=2, so the output shape should be 1x2x4x2(nhwc), but the test out is 1x2x1x8(nhwc)

debug log as following:
```bash
hexagon_nn_execute_new(gid=6 ic=4 oc=1)
input: 
	nhwc: 1x2x1x2 [139 91 80 44]
	nhwc: 1x2x1x2 [22 62 82 141]
	nhwc: 1x2x1x2 [136 87 76 204]
	nhwc: 1x2x1x2 [45 114 148 252]
	
output: 
	nhwc: 1x2x1x8 [255 0 255 255 255 0 255 255 0 0 255 255 0 255 255 255]
	
[       OK ] QuantizedConcatenationOpModel.FourInputsAxis2_UInt8 (10 ms)
```
BTW: 
the others tests of concat output as expected.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
