### ISSUE TITLE
Forward AD threw error in `tf.autodiff.ForwardAccumulator` for `tf.keras.layers.MaxPooling3D`, but backward AD succeeded with same input

### ISSUE THREAD

**Issue by eeDigitalSeal** [tensorflow/tensorflow#56833]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
Forward AD threw error, but backward AD succeeded with same input. They should throw error both as expected. This behaviour can be reproduced in some similar APIs like `tf.keras.layers.AveragePooling2D` and `tf.keras.layers.AveragePooling3D`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

pool_size = [2,1,1]
strides = [2,2,2]
padding = "valid"
data_format = "channels_last"
input = tf.constant(0.895205,shape=[1,1,1,1,1], dtype=tf.float32)
layer = tf.keras.layers.MaxPooling3D(pool_size=pool_size, strides=strides, padding=padding, data_format=data_format, )

with tf.GradientTape(persistent=True, ) as g:
    g.watch(input)
    res_backward = layer(input)
grad_backward = g.jacobian(res_backward,res_backward)
print("res_backward:",res_backward)
print("grad_backward:",grad_backward)

tangents = tf.constant(1.,dtype=tf.float32,shape=[1,1,1,1,1])
with tf.autodiff.ForwardAccumulator(input, tangents) as acc:
    res_forward = layer(input)
    grad_jvp = acc.jvp(res_forward)
    print("res_forward:", res_forward)
    print("grad_forward", grad_jvp)
```

### Relevant log output

```shell
res_backward: tf.Tensor([], shape=(1, 0, 1, 1, 1), dtype=float32)
grad_backward: tf.Tensor([], shape=(1, 0, 1, 1, 1, 1, 0, 1, 1, 1), dtype=float32)
ValueError: Negative dimension size caused by subtracting 2 from 1 for '{{node gradient_tape/gradient_tape/MaxPool3DGradGrad}} = MaxPool3DGradGrad[T=DT_FLOAT, data_format="NDHWC", ksize=[1, 2, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 2, 1]](inputs, outputs, tangents)' with input shapes: [1,1,1,1,1], [1,0,1,1,1], [1,1,1,1,1].
```
</details>

**Comment by tilakrayal** [comment]
@eeDigitalSeal,
I tried to execute the code in an alternative approach and was able to execute without any errors. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/27047cbc96352ceaf5674149123f7623/untitled443.ipynb). Also please take a look at this [issue](https://github.com/keras-team/keras/issues/3945) and [comment](https://github.com/tensorflow/tensorflow/issues/48589) for the similar error. Thank you!

**Comment by eeDigitalSeal** [comment]
@tilakrayal Please kindly note that this bug only happened when the  `padding="valid"`, not `padding="same"`. In this case,  the `pool_size = [2,1,1]` is invalid, so `MaxPooling3D` should throw `ValueError`. However now it excuted successfully when caculating gradient in reverse mode.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/bf87b68fb8b97fd13c14b23b4bc259ea/56833.ipynb).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
