### ISSUE TITLE
Rsqrt doesn't support for tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8

### ISSUE THREAD

**Issue by Jwy-Leo** [tensorflow/tensorflow#56898]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
- TensorFlow installed from (source or binary):
- TensorFlow version (or github SHA if from source):

**Provide the text output from tflite_convert**

```
# Copy and paste here
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by mohantym** [comment]
Hi @Jwy-Leo !
Could you provide a minimal stand alone code to replicate the issue.
Thank you!

**Comment by Jwy-Leo** [comment]
Hi @mohantym 
Here is the code 
`
_input = x = tf.keras.Input((640, 480, 3), dtype=tf.float32)
    # output = tf.keras.layers.LayerNormalization()(_input)
    # x = tf.keras.layers.Conv2D(kernel_size=3)(x)
    # x = tfa.layers.GELU(False)(x)
    output = tf.keras.layers.LayerNormalization()(x)    
    model = tf.keras.Model(inputs=[_input], outputs=[output], name='rsqrt_operation_demo')
    converter = tf.lite.TFLiteConverter.from_keras_model(model)

    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.target_spec.supported_ops = [tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8]
    def representative_data_gen():
        for i in range(10):
            yield [tf.random.normal((1, 640, 480, 3), dtype=tf.float32)]
    converter.representative_dataset = representative_data_gen
    tflite_model = converter.convert()
    with open('model.tflite', 'wb') as F:
        F.write(tflite_model)    

    test_in = tf.random.normal((1, 640, 480, 3), dtype=tf.float32)
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()
    input_index = interpreter.get_input_details()[0]["index"]
    output_index = interpreter.get_output_details()[0]["index"]

    interpreter.set_tensor(input_index, test_in)
    interpreter.invoke()
    predictions = interpreter.get_tensor(output_index)
`

**Comment by mohantym** [comment]
Hi @Jwy-Leo !
Sorry for the inconvenience . 
@sachinprasadhs ! Could you please look at this issue. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/e0001e195b8a8fa9fd2aef3494ca12ec/untitled398.ipynb#scrollTo=zmTcTKkED5P-), [2.9](https://colab.sandbox.google.com/gist/mohantym/c080160e3b7e458829338110b8d03370/untitled398.ipynb#scrollTo=zmTcTKkED5P-) and [nightly ](https://colab.sandbox.google.com/gist/mohantym/286f3b8c6b6bc867249d5072a2e3c43b/untitled398.ipynb#scrollTo=zmTcTKkED5P-)for reference. 
Thank you!

**Comment by sachinprasadhs** [comment]
Hi, Could you please try the below select TF options which will allow the failed ops to fallback to TF Ops and let us know if that works, since the Rsqrt is not supported in the mentioned select ops in your code. 
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]

**Comment by Jwy-Leo** [comment]
Hi @sachinprasadhs ,
Directly using your recommendation command - tf.lite.OpsSet.TFLITE_BUILTINS is run on tf.int8.
But in my case, I want to run the inference_type=tf.int16.
So I try to cascade the flag, but it cannot work as I want.

`converter.target_spec.supported_ops = [
  tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8,
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]`

**Comment by Jwy-Leo** [comment]
If the rsqrt is supported, it's a helpful solution for application that has a large output range s do the PTQ on the device I think.

Also, in this solution, the tensorflow_addons.layers.GELU(False), tf.math.exp, tf.math.log, and Hardswish are waiting to support.

**Comment by sachinprasadhs** [comment]
Right now, I can see RSQRT implementation for tflite-micro for INT8 & INT16 here https://github.com/tensorflow/tflite-micro/pull/1072/files.
Let me know if this helps. Thanks!

**Comment by Jwy-Leo** [comment]
Hi @sachinprasadhs ,

It's helpful for me. But I hope it can become the new feature in the next round official release.

Thanks

**Comment by sachinprasadhs** [comment]
Thanks for the update. I'm changing this to a feature request.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
