### ISSUE TITLE
NaN values in tf.reduce_mean + float16 + CPU

### ISSUE THREAD

**Issue by shkarupa-alex** [tensorflow/tensorflow#56890]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.2

### Custom Code

No

### Python version

3.7.13

### Current Behaviour?

```shell
When using CPU + fp16, tf.reduce_mean produces NaN-s.
When reduce_mean placed on GPU everything works.
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1sEUNVv0knkg65JNrsHMcbdlCJGs8U8j9?usp=sharing
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
@shkarupa-alex , It can be due to the large input given, could you please confirm if you face the same issue when the small input is given.

**Comment by shkarupa-alex** [comment]
> @shkarupa-alex , It can be due to the large input given, could you please confirm if you face the same issue when the small input is given.

Even if so, i suppose there should be no difference between CPU and GPU ops behavior.
I wasted about 2 hours to determine why my model produces NaN-s in CPU inference mode after it was trained without errors on GPU

**Comment by sachinprasadhs** [comment]
When I tried to debug, it is returning NaN for the output given the input y. We will look into the issue in detail.

**Comment by cantonios** [comment]
@shkarupa-alex both the sum of elements in that array, and the number of elements (232*304) overflow a `float16`, so you end up with `-inf/inf`, which is a `NaN`.

The GPU kernel internally does a cast to float and computes the means in `float32` before casting back [here](https://github.com/tensorflow/tensorflow/blob/5134091134e62a175bc6d491069c8278e7bc4ccf/tensorflow/core/kernels/reduction_gpu_kernels.cu.h#L1219).  Your input does not overflow a `float32`, so you get a valid answer back.

There are many cases where the CPU version and GPU version will give different results.  Sometimes this is because of different hardware capabilities, other times because of different efficiencies.  I don't think we want to force all `reduce_mean` calls for `float16` to cast to `float32`.  If you need the extra precision, you can do that yourself.
