### ISSUE TITLE
Wrong gradient in TensorScatterUpdate with duplicated indices

### ISSUE THREAD

**Issue by ghost** [tensorflow/tensorflow#56961]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.8.2

### Custom Code

No

### Current Behaviour?

`tf.tensor_scatter_nd_update()` generates wrong gradients (summation) with duplicated indices. According to the doc, on CPU, only the gradient of last update should be used.

### Standalone code to reproduce the issue

https://colab.research.google.com/drive/11esloyqJ4ysEqobGfPuKvvW1IpZirTvC

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@chunduriv,
I was able to reproduce the issue on tensorflow [v2.8](https://colab.research.google.com/gist/tilakrayal/81bf41c61ed52e9f696e51d364fffdab/test_scatter_update_grad.ipynb), [v2.9](https://colab.research.google.com/gist/tilakrayal/7e603aee6daa10bea38ac53c66a9bdb2/2-9test_scatter_update_grad.ipynb) and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/889e760abc5a593e1dede282ad307d0e/nightly-test_scatter_update_grad.ipynb).

**Comment by cantonios** [comment]
Nice find.  The conclusion seems to be that we require input indices to be unique.  Otherwise, not only is the output non-deterministic on GPU, but gradients are broken on any device.

To fix gradients, we would need to pre-process and dedup the indices ourselves.  If we need to do this for gradients, we may as well do this for the forward pass as well and make the GPU behavior deterministic.  However, doing so will require sorting the input indices, so we'd take a performance hit (particularly on GPU).

The alternative is just to claim that the output is undefined (i.e. garbage) if you have duplicate indices (which was the case for GPU).
