### ISSUE TITLE
tape.gradient is returning none

### ISSUE THREAD

**Issue by nomadeCodeur** [tensorflow/tensorflow#56968]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.7.0

### Custom Code

Yes

### Current Behaviour?

```shell
I don't understand why the code below output grads to be None.
Could you please give me some explanations ?
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
ones = tf.ones([ 1, 128, 128, 1], tf.float32)
with tf.GradientTape() as tape:

    
    class_channel = tf.constant([4.4328732],  dtype=tf.float32)
    grads = tape.gradient(class_channel, ones)

    print("grads: ",grads)
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
Hi @nomadeCodeur, In this case gradient is `None` why because, you trying to find gradient for the non differential equation . If you finding gradient `y` w.r.t `x`, dy/dx should be differntiable. 

For example, consider the function y = x * x. The gradient at x = 3.0 can be computed as:
```
x = tf.constant(3.0)
with tf.GradientTape() as g:
  g.watch(x)
  y = x * x
dy_dx = g.gradient(y, x)
print(dy_dx)
```
Make your class_channel as differentiable input. Thank you!

**Comment by nomadeCodeur** [comment]
Hi @gadagashwini , thank you for your clear explanation. You solved my problem.
