### ISSUE TITLE
[Question]: Where does these recommended block size come from in Mali GPU delegates?

### ISSUE THREAD

**Issue by FdyCN** [tensorflow/tensorflow#56964]
i found codes in GPU delegates below: https://github.com/tensorflow/tensorflow/blob/03e6e2af40f53f69e5fab1151235b0880252c21c/tensorflow/lite/delegates/gpu/common/task/util.cc#L150 

and i'm really confused how these thresholds come from，is there any doc or paper that i can learn about? seemed they are related to CU compute capacity, but i don;t know why, could any one help me? thank your so much.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
