### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by tianxiangsong** [tensorflow/tensorflow#56966]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.8.2

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 16.04

### Mobile device

Linux Ubuntu 16.04

### Python version

3.8.2

### Bazel version

5.0.0

### GCC/Compiler version

9.6.0

### CUDA/cuDNN version

11.4

### GPU model and memory

3080 11g

### Current Behaviour?

```shell
When adapting a binary operator for calculation, such as mul, if two input tensors are one-dimensional, one of them will be converted into a scalar,
so that the memory of the tensor is not released, causing memory leaks (Especially when programming with opencl).
```

### Standalone code to reproduce the issue

```shell
'''
import tensorflow  as tf
a = tf.random.normal(shape=[1], dtype=tf.float32)
'''
through tensorflow/python/ops/random_ops.py:43(random_normal)
mean and stddev will be changed tensor. Next, in tensorflow/core/kernels/cwise_ops_common.h:120(Compute) tensor is seen as scalar so that it will be not released.
```

### Relevant log output

_No response_</details>

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
