### ISSUE TITLE
xla && dynamic graph

### ISSUE THREAD

**Issue by never-to-never** [tensorflow/tensorflow#57040]
what is the relationship of xla and dynamic graph？

**Comment by tilakrayal** [comment]
@never-to-never,

The `Dynamic Shape Mode` requires changes in many aspects regarding current XLA design & implementation. And MLIR provides an opportunity to make things easier. 

In order to support "Dynamic Shape Mode" we also need some other features/works to be supported which in our understanding should be in the roadmap of MLIR but may not be directly related with "Dynamic Shape" at all.

"Dynamic Shape Mode" will lose some of the optimization potentials, while it at least keep the profit of op fusion codegen (including kLoop/kInput in XLA), i.e. the reduction of kernel launch /memory access /operation launch overhead. 

Also the "Dynamic Shape Mode" is only a supplement of the current static shape mode as a last resort rather than a replacement.

The Ops that face the "dynamic shape issue" can be seperated into two categories:

- The output shape can be easily infered from the value of input tensors, and the calculation of the output shape is light enough. There are lots of such examples, like Reshape, Slice, Transpose. 
- The output shape can only be known after the "real" calculation. One of the most common seen examples is the "Unique" Op. And just for this reason, XLA has not supported Unique like Ops yet.

**Comment by never-to-never** [comment]
> @never-to-never,
> 
> The `Dynamic Shape Mode` requires changes in many aspects regarding current XLA design & implementation. And MLIR provides an opportunity to make things easier.
> 
> In order to support "Dynamic Shape Mode" we also need some other features/works to be supported which in our understanding should be in the roadmap of MLIR but may not be directly related with "Dynamic Shape" at all.
> 
> "Dynamic Shape Mode" will lose some of the optimization potentials, while it at least keep the profit of op fusion codegen (including kLoop/kInput in XLA), i.e. the reduction of kernel launch /memory access /operation launch overhead.
> 
> Also the "Dynamic Shape Mode" is only a supplement of the current static shape mode as a last resort rather than a replacement.
> 
> The Ops that face the "dynamic shape issue" can be seperated into two categories:
> 
> * The output shape can be easily infered from the value of input tensors, and the calculation of the output shape is light enough. There are lots of such examples, like Reshape, Slice, Transpose.
> * The output shape can only be known after the "real" calculation. One of the most common seen examples is the "Unique" Op. And just for this reason, XLA has not supported Unique like Ops yet.

@tilakrayal Thank you for your answer, but I still have a little question. Before tensorflow 2.0, tensorflow was a static graph mode, and it was necessary to build a graph and get an HLO IR. XLA accepts computational graphs defined in HLO for goal-independent optimization. Then, the xla backend performs further HLO-level optimizations. After that, xla backend converts the HLO IR to LLVM IR, which performs low-level optimizations and generates machine code. After tensorflow 2.0, tensorflow has become a dynamic graph mode similar to pytorch, without first building a static graph. Can you answer, what is the logic from the top to the bottom under the dynamic graph concept? Thank you very much

**Comment by tilakrayal** [comment]
@never-to-never,

The compilation realtion of TensorFlow graphs using XLA is as below. 

We can use `XLA` to compile and run parts of a `TensorFlow graph` at runtime.

By compiling models with `XLA`, we can generate high-performance code that can outperform Tensorflow's hand-written compute kernels, by applying optimizations such as automatic operator fusion.

There are three phases to JIT compilation:

1. Choosing TensorFlow operators that are candidates for compilation
2. Group operators into clusters to be compiled by `XLA`, and replace each cluster with a pair of `_XlaCompile` and `_XlaRun` operators
3. `_XlaCompile` compiles the cluster using `XLA` and `_XlaRun` executes the compiled cluster
