### ISSUE TITLE
TensorFlow Lite in Play Services issue

### ISSUE THREAD

**Issue by sandeep5193** [tensorflow/tensorflow#57099]
**System information**
- Android Device information (use `adb shell getprop ro.build.fingerprint`
  if possible): Lenovo/A6020a46/A6020a46:5.1.1/LMY47V/A6020a46_S105_161124_ROW:user/release-keys
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`): play-services-tflite-java:16.0.0-beta03
- Google Play Services version
  (`Settings` > `Apps` > `Google Play Services` > `App details`): 22.26.15 (020408-461192076)

**Standalone code to reproduce the issue**
TfLite.initialize(this, TfLiteInitializationOptions.builder().setEnableGpuDelegateSupport(true).build());

**Any other info / logs**
Any reliable way to find if GPU Delegate is supported in given device? Currently I am relying on addOnFailureListener() callback with "Error loading TFLite GPU delegate module" message.

Should I go back to CompatibilityList class of org.tensorflow.lite.gpu package for this one particular requirement?

**Comment by mohantym** [comment]
Hi @sandeep5193 !
You can check instructions in this [document](https://www.tensorflow.org/lite/performance/gpu#tensorflow_lite_interpreter) to check available GPU delegate. You can also build your GPU delegate through below Bazel commands.

I am doubtful about NNAPI implementation with Android 5.1 (Android 8.1 minimum requirment). You can check with other available delegate ( I see Snapdragon 616 in Lenovo/A6020a46 , Hexagon delegate might work , not sure though)

```
bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:delegate                           # for static library
bazel build -c opt --config android_arm64 tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so  # for dynamic library
```

**Comment by sandeep5193** [comment]
Hi @mohantym,

The document you have linked talks about using the delegate through org.tensorflow:tensorflow-lite-gpu module, while I am inclined with using them through [Play Services](https://www.tensorflow.org/lite/android/play_services). TensorFlow Lite available in the Google Play services API doesn't have any way to check if the device is compatible for GPU delegate.

**Comment by sheepmaster** [comment]
We're not recommending to use the `CompatibilityList` class with TensorFlow Lite in Google Play services, because the list is a static copy built into the SDK, whereas the GPU delegate can get updated over time, so compatibility might actually change. (Also, currently the `CompatibilityList` class is bundled into the static GPU delegate SDK, so depending on it would include a full copy of the GPU delegate implementation, which adds unnecessary binary size).

We hear your feedback about lack of an explicit API to query compatibility though. Stay tuned :)

**Comment by sandeep5193** [comment]
Thanks for clarifying.

**Comment by acq** [comment]
FYI, we had a new release (16.0.0, first stable release) that adds a new API to check if the GPU delegate is available on a device ahead of time: [TfLiteGpu.isGpuDelegateAvailable](https://developers.google.com/android/reference/com/google/android/gms/tflite/gpu/support/TfLiteGpu#isGpuDelegateAvailable(android.content.Context))

Instead of having to try-with-delegate/catch/try-without-delegate, you can now write something [like](https://github.com/tensorflow/examples/blob/5d3579cb1057d31c260be4289a32ebc0a91782e0/lite/examples/object_detection/android_play_services/app/src/main/java/org/tensorflow/lite/examples/objectdetection/ObjectDetectorHelper.kt#L51):
```
TfLiteGpu.isGpuDelegateAvailable(context).onSuccessTask { gpuAvailable: Boolean ->
    val optionsBuilder = TfLiteInitializationOptions.builder()
    if (gpuAvailable) {
        optionsBuilder.setEnableGpuDelegateSupport(true)
    }
    TfLiteVision.initialize(context, optionsBuilder.build())
}
```

Hope this helps!

**Comment by sandeep5193** [comment]
While this worked on our devices in development, recently we pushed an update, and we're seeing below error in Crashlytics:

```
com.google.android.gms.tasks.DuplicateTaskCompletionException: Complete with: result false
	at com.google.android.gms.tasks.zzw.zzh(Unknown Source:5)
	at com.google.android.gms.tasks.zzw.zzb(SourceFile:1)
	at com.google.android.gms.tasks.TaskCompletionSource.setResult(Unknown Source:2)
	at com.google.android.gms.internal.tflite_gpu.zzb.onInstallStatusUpdated(SourceFile:3)
	at com.google.android.gms.common.moduleinstall.internal.zaaa.notifyListener(SourceFile:2)
	at com.google.android.gms.common.api.internal.ListenerHolder.zaa(SourceFile:2)
	at com.google.android.gms.common.api.internal.zacb.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:873)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:201)
	at android.app.ActivityThread.main(ActivityThread.java:6826)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

any decent way to handle this?

**Comment by sheepmaster** [comment]
Thanks! I've filed an internal bug (http://b/248231641), and we'll investigate this.

**Comment by sandeep5193** [comment]
Now I'm not sure if this error is coming for TfLiteGpu.isGpuDelegateAvailable(context) method, will update when I have more info.

**Comment by acq** [comment]
We haven't been able to reproduce the issue, so we'll welcome any new info you may have.
On the other hand, we think we may have a solution to safeguard the code against this issue in the future, but it would require us to publish an SDK update, which may take a bit.

**Comment by sandeep5193** [comment]
@acq Any hint on how we can catch for the time being?

We already tried to catch it for TfLiteGpu.isGpuDelegateAvailable(Context) method, still it's throwing exceptions in prod.

TfLite.initialize(Context, TfLiteInitializationOptions) is next suspect.

**Comment by sheepmaster** [comment]
Yeah, the problem is that the exception is being thrown on the UI thread in a callback, not in the immediate call to `isGpuDelegateAvailable()` or `initialize()`, so catching exceptions there won't help.

**Comment by sandeep5193** [comment]
Got it, thanks for clarification.

**Comment by acq** [comment]
Since we haven't been able to reproduce it: do you have any data on how widespread the problem is for your app? Is it impacting all users or a fraction of them? If it is a fraction, any metric that would differentiate crashing vs non-crashing populations? Is there a way for me to access the app and see it crash in person so I can collect more data?

**Comment by sandeep5193** [comment]
Don't have exact figures, but definitely below 5 per cent, and real count can be way less than it. Currently we have disabled this feature through Firebase Remote Config because of this issue, will share app once we enable it again.

**Comment by acq** [comment]
Thanks for the data! <5% does explain why we didn't run into it earlier and why we have found it challenging to reproduce.
We are still investigating for the root cause and will keep you updated on an eventual resolution

**Comment by sandeep5193** [comment]
FYI, we thought we can skip using `isGpuDelegateAvailable()` and use `initialize()` without GPU delegate support for now. But now we are getting similar error here as well:

```
com.google.android.gms.tasks.DuplicateTaskCompletionException: Complete with: result false
	at com.google.android.gms.tasks.zzw.zzh(Unknown Source:5)
	at com.google.android.gms.tasks.zzw.zzb(SourceFile:4)
	at com.google.android.gms.tasks.TaskCompletionSource.setResult(Unknown Source:2)
	at com.google.android.gms.internal.tflite.zzt.onInstallStatusUpdated(SourceFile:19)
	at com.google.android.gms.common.moduleinstall.internal.zaaa.notifyListener(SourceFile:5)
	at com.google.android.gms.common.api.internal.ListenerHolder.zaa(SourceFile:9)
	at com.google.android.gms.common.api.internal.zacb.run(Unknown Source:4)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:233)
	at android.os.Looper.loop(Looper.java:334)
	at android.app.ActivityThread.main(ActivityThread.java:8399)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
```

Do you think ensuring API availability with ModuleInstallClient before using it will solve this?

**Comment by acq** [comment]
I don't think it would hurt.

FYI: internal usage of ModuleInstallClient is what seems to be causing the issue.
It seems that for the users experiencing issues, the progress listener we set up on our instance ModuleInstallClient receives multiple terminal state updates (CANCELED, FAILED, COMPLETED) which was not expected and gives us our DuplicateTaskCompletionException.
If your code handles this gracefully (for example by unregistering the listener after receiving the first terminal state update), you could know ahead of time which scenario you are in:
- if it's successful, the code from the stacktrace above would be skipped (since the modules would already be available)
- if it's unsuccessful, you can avoid running the offending code altogether (which if run would trigger the issue above)

Meanwhile, we are still working towards a more stable fix, that would not require this extra code, but the solution above may unblock you faster

**Comment by sandeep5193** [comment]
Thanks for the tip.

**Comment by sandeep5193** [comment]
To my surprise, there are no errors in past 14 hours. Last error was at Sep 23, 2022, 14:56:58 UTC.

Any idea what could have changed? Can dynamically loading modules solve it?

**Comment by sandeep5193** [comment]
We have enabled it again, but this time, not using GPU delegate. See below comment, it was enabled again but wasn't calling `isGpuDelegateAvailable()`. We were then getting another error for TfLite module but then it stopped.



> FYI, we thought we can skip using `isGpuDelegateAvailable()` and use `initialize()` without GPU delegate support for now. But now we are getting similar error here as well:
> 
> ```
> com.google.android.gms.tasks.DuplicateTaskCompletionException: Complete with: result false
> 	at com.google.android.gms.tasks.zzw.zzh(Unknown Source:5)
> 	at com.google.android.gms.tasks.zzw.zzb(SourceFile:4)
> 	at com.google.android.gms.tasks.TaskCompletionSource.setResult(Unknown Source:2)
> 	at com.google.android.gms.internal.tflite.zzt.onInstallStatusUpdated(SourceFile:19)
> 	at com.google.android.gms.common.moduleinstall.internal.zaaa.notifyListener(SourceFile:5)
> 	at com.google.android.gms.common.api.internal.ListenerHolder.zaa(SourceFile:9)
> 	at com.google.android.gms.common.api.internal.zacb.run(Unknown Source:4)
> 	at android.os.Handler.handleCallback(Handler.java:938)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:233)
> 	at android.os.Looper.loop(Looper.java:334)
> 	at android.app.ActivityThread.main(ActivityThread.java:8399)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:582)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1068)
> ```
> 
> Again, I am not sure where exactly it is failing, `initialize()` or `InterpreterApi.create()` or `runForMultipleInputsOutputs()`.
> 
> Do you think ensuring API availability with ModuleInstallClient before using it will solve this?

**Comment by acq** [comment]
Ah I see, thanks for explaining.

Because TFLite for Play Services overall relies on downloadable APIs/modules, it is possible that just giving it more time may have helped by giving more opportunity for all devices to be up-to-date.
While the error number going down could be explained by that, I'm still surprised it would go to 0.

Either way, we'll probably want to go ahead with an SDK update that handles this situation more gracefully.

Couple of thoughts:
- is it possible that your app is used on devices that don't have the Play Services? (for example, distributed outside of the Play Store)?
- is it possible that some of your users may try to use your app in countries where they would not be able to get Play Services updates/downloads?

**Comment by sandeep5193** [comment]
We have not distributed this anywhere other than Play Store. But we can see it listed in various unofficial stores when we search by name on Google, and many of them do not redirect it Play Store.

So yes, it's possible to install it on devices where Play Services is not supported.

**Comment by sandeep5193** [comment]
> I don't think it would hurt.
> 
> FYI: internal usage of ModuleInstallClient is what seems to be causing the issue. It seems that for the users experiencing issues, the progress listener we set up on our instance ModuleInstallClient receives multiple terminal state updates (CANCELED, FAILED, COMPLETED) which was not expected and gives us our DuplicateTaskCompletionException. If your code handles this gracefully (for example by unregistering the listener after receiving the first terminal state update), you could know ahead of time which scenario you are in:
> 
> * if it's successful, the code from the stacktrace above would be skipped (since the modules would already be available)
> * if it's unsuccessful, you can avoid running the offending code altogether (which if run would trigger the issue above)
> 
> Meanwhile, we are still working towards a more stable fix, that would not require this extra code, but the solution above may unblock you faster

TFLite module's availability can be checked with `TfLiteClient`, but I do not see a class extending `OptionalModuleApi` for GPU delegate. `isGpuDelegateAvailable()` is using an internal class for the same.

**Comment by sheepmaster** [comment]
> TFLite module's availability can be checked with `TfLiteClient`, but I do not see a class extending `OptionalModuleApi` for GPU delegate module. `isGpuDelegateAvailable()` is using an internal class for the same.

That's a good point! We should expose an `OptionalModuleApi` implementation for the GPU delegate module.

**Comment by acq** [comment]
We just released an update for the GPU SDK: https://maven.google.com/web/index.html#com.google.android.gms:play-services-tflite-gpu:16.1.0
This should resolve the crash your users were experiencing and also exposes an `OptionalModuleApi` for the GPU delegate module (via `TfLiteGpu.getClient(context)`).

Note that since we haven't been able to reproduce the initial, we can't guarantee that this specific issue no longer happens, but it should be a step in the right direction either way.

**Comment by sandeep5193** [comment]
Recently we updated the app with the latest version of this lib, and now we are seeing this exception:

```
com.google.android.gms.tasks.DuplicateTaskCompletionException: Complete with: result false
       at com.google.android.gms.tasks.zzw.zzh(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at com.google.android.gms.tasks.zzw.zzb(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at com.google.android.gms.tasks.TaskCompletionSource.setResult(com.google.android.gms:play-services-tasks@@18.0.2:1)
       at com.google.android.gms.internal.tflite.zzt.onInstallStatusUpdated(com.google.android.gms:play-services-tflite-impl@@16.0.0:3)
       at com.google.android.gms.common.moduleinstall.internal.zaaa.notifyListener(com.google.android.gms:play-services-base@@18.1.0:2)
       at com.google.android.gms.common.api.internal.ListenerHolder.zaa(com.google.android.gms:play-services-base@@18.1.0:2)
       at com.google.android.gms.common.api.internal.zacb.run(com.google.android.gms:play-services-base@@18.1.0:4)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8669)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
```

I assume this is for TFLite module and not GPU Delegate.

**Comment by acq** [comment]
Ah, that's frustrating...
Thanks for letting us know.

I was hoping the issue was only impacting the GPU delegate optional module, but your error points to the problem also impacting the main TFLite optional module.
So we'll have to publish SDK updates of play-services-tflite-java, play-services-tflite-support, ...

I'll let you know when those are available

**Comment by sandeep5193** [comment]
Well, we already mentioned this issue for TFLite module as well, [here](https://github.com/tensorflow/tensorflow/issues/57099#issuecomment-1256375155). But after that we stopped receiving it, and we thought dynamically loading modules through Play Services might have solved it.

**Comment by acq** [comment]
Apologies for the release taking longer than I would have liked, but we have published a 16.0.1 release of the TFLite for Play Services SDKs (expect for the GPU delegate SDK which was previously updated to 16.1.0).
cf https://maven.google.com/web/index.html#com.google.android.gms:play-services-tflite-java:16.0.1

Hope this solves the issue!

**Comment by sandeep5193** [comment]
Thanks for the update @acq , we updated the app yesterday. No error reported till now.

**Comment by sachinprasadhs** [comment]
@sandeep5193 , Thanks for confirming, could you please move this issue to closed.

**Comment by hakobast** [comment]
@acq so how should SDK setup be done in order to avoid crashes until gpu delegate SDK update will  be published?

**Comment by acq** [comment]
The GPU delegate SDK (and its counterparts like the Java SDK) were updated in October 2022.
Which should have resolved the issues mentioned in this thread.

Those updates included a new API: `TfLiteGpu.isGpuDelegateAvailable(context)`. You should invoke this asynchronous method if you're interested in using the GPU, and use the return value to decide whether you want to `TFLite.initialize(...)` with GPU or not

Please let me know if you're having issues with this
In which case, a code sample of your initialization would help me help you

**Comment by mohamedma872** [comment]
TfLiteGpu.isGpuDelegateAvailable(context) always returns false and my phone is google pixel 6 so I don't know what that ? is anyone has the same problem

**Comment by tpatterson** [comment]
> TfLiteGpu.isGpuDelegateAvailable(context) always returns false and my phone is google pixel 6 so I don't know what that ? is anyone has the same problem
I'm having the same issue. Any suggestions?
