### ISSUE TITLE
Cannot assign variable in Tensorflow-Lite: "incompatible with expected resource"

### ISSUE THREAD

**Issue by petered** [tensorflow/tensorflow#57111]
### Summary

I cannot get variable assignment to work in TFLite. 

I've made a minimal-possible graph for just doing a cumulative sum.  

 When I try to save the graph as a TFLite model, I get 

```
Cannot assign variable in Tensorflow-Lite: "incompatible with expected resource"
```

### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): macOS Monterey, 12.2.1
- TensorFlow installation (pip package or built from source): Conda, from `conda install -c apple tensorflow==2.8.1`
- TensorFlow library (version, if pip package or github SHA, if built from source): `2.8.1`

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option A: Reference colab notebooks

This colab notebook reproduces the issue: 
https://colab.research.google.com/drive/1KPjHhlCMVs2oFxodrFAO7YcPrfBADC2k?usp=sharing 

See also: Stackoverflow Question
https://stackoverflow.com/questions/73327824/cannot-assign-variable-in-tensorflow-lite-incompatible-with-expected-resource

**Comment by mohantym** [comment]
Hi @rthadur !
Could you look at this issue. Attached gist in [2.8](https://colab.sandbox.google.com/gist/mohantym/cf370a7953cf2d44ab72f9d005467383/test_tflite_fails_with_stateful_op.ipynb), [2.9](https://colab.sandbox.google.com/gist/mohantym/a6e3c3384c3f4ef8aefbd035d3d853a0/test_tflite_fails_with_stateful_op.ipynb#scrollTo=6-RNc-Bu_HC-) and[ nightly](https://colab.sandbox.google.com/gist/mohantym/3ecb17d122013788414759192845e8ee/test_tflite_fails_with_stateful_op.ipynb#scrollTo=tdS3Oe11NczW) for reference.
Thank you!

**Comment by petered** [comment]
Ok, I found a workaround for this.  [See answer to stackoverflow question](https://stackoverflow.com/a/73337087/851699).

Basically, variable-assignment only works when loading the converter from: 

```
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_dir)
```

Colab notebook with solution: https://colab.research.google.com/drive/1Ud3lcyweOIeHRUgsoqr7-kBxndZSSBcH 

Up to you guys whether you want to close this ticket - two possible improvements that could come out of this: 

1) A more obvious error message that points to the solution.
2) Enable variable assignment when creating the converter with `TFLiteConverter.from_concrete_functions`

**Comment by mohantym** [comment]
Hi @petered !
Could you suggest a PR for review.
Thank you!

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue.
Ideally `TFLiteConverter.from_concrete_functions` should track the variable name scope same way as `TFLiteConverter. from_saved_model`.
We will investigate further and update you. Thanks!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
