### ISSUE TITLE
Error:Could not compute output KerasTensor... when saving a model

### ISSUE THREAD

**Issue by osayes** [tensorflow/tensorflow#57124]
when saving model, identical layer instance in different level leads to an error

**code to reproduce**:
```
from tensorflow.keras import *
import tensorflow as tf

act = layers.ReLU()

model = Sequential([
  act, 
  Sequential([
    act
  ]),
  Sequential([
    act
  ])
])
model(tf.random.normal([1]))
model.save("./model-test")
```

**the code below works correctly**:
```
from tensorflow.keras import *
import tensorflow as tf
from copy import deepcopy

act = layers.ReLU()

model = Sequential([
  deepcopy(act),
  Sequential([
    act
  ]),
  Sequential([
    act
  ])
])
model(tf.random.normal([1]))
model.save("./model-test")
```

there is no error as long as not saving, I wonder if it is a bug, or some mechanism causes that

platform: win10
tf version: 2.7.0
python version: 3.9

**Comment by tilakrayal** [comment]
@osayes, 

Thank you for opening the issue! This is an issue with `Sequential` models, where they will essentially assume that any layer can be traced with a an input matching the layer's dtype. This is an issue hitting quite a few `preprocessing` layers (though due to some refactoring it looks like StringLookup is newly affected in 2.8). 

For now, the fix suggested above, use a `keras.Input(..., dtype='string')` as the first layer in your sequential is a good workaround. Functional models will also not be affected, as they always have a clear dtype.

Re performance, I don't think that would be related? The only change  `StringLookup` performance would be stricter error checking with `num_oov_tokens=0`, which could lead to slower performance in that case.

Anyway, the end goal here should be to fix tracing inside the `Sequential` model so it does not make invalid assumptions about input types.

Thank you!

**Comment by osayes** [comment]
@tilakrayal,
Thank you for your response!
Adding the input layer into the first layer of sequential model solved the problem, although I'm still confused about the tracing procedure
In my mind, all inputs and outputs of the relu instance in previous code are the same if you feed any value with any dtype to the model, they should not conflict with each other

**Comment by tilakrayal** [comment]
@osayes,
Glad the suggestion worked for you. Could you please feel free to move this issue to closed status and submit a new issue from [this link](https://github.com/keras-team/keras/issues) in Keras repo. Thank you!
