### ISSUE TITLE
CHECK failed: file != nullptr

### ISSUE THREAD

**Issue by sabrinakall-imtf** [tensorflow/tensorflow#57121]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.6.0

### Custom Code

No

### OS Platform and Distribution

MacOS Monterey Version 12.0.1 (21A559)

### Python version

3.8.9

### Current Behaviour?

```shell
Building and running a docker container (file provided below) on several machines with the same dockerfile and python version. Works on various Ubuntu installations, a MacOS Monterey Version 12.5 installation, but not the MacOS Monterey Version 12.0.1 (21A559) installation on a machine with an Apple M1 Pro chip. On that one, the log output below happens.
```

### Standalone code to reproduce the issue

```shell
FROM tensorflow/serving:2.6.0
#RUN mkdir /models
#WORKDIR /models
#COPY ./ /models
EXPOSE 8080
ENTRYPOINT tensorflow_model_server --rest_api_port=8080 --model_name=MyModel #--model_base_path=/models/
```

### Relevant log output

```shell
[libprotobuf FATAL external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2345] CHECK failed: file != nullptr:
terminate called after throwing an instance of 'google::protobuf::FatalException'
  what():  CHECK failed: file != nullptr:
qemu: uncaught target signal 6 (Aborted) - core dumped
Aborted
```
</details>

**Comment by tilakrayal** [comment]
@sabrinakall-imtf,
Could you please confirm if you are using X86 wheel without AVX. In that case we have already an open ticket, so it is better to add a comment there instead of having a new ticket:
#19584

If instead you want to have AVX TCG support in QEMU e.g. on M1 there is already an open ticket at:
https://gitlab.com/qemu-project/qemu/-/issues/164.

Also please take a look at this [issue1](https://github.com/tensorflow/tensorflow/issues/52972#issuecomment-963079971) and [issue2](https://github.com/tensorflow/tensorflow/issues/52845) with the similar error. Thank you!
