### ISSUE TITLE
tf.math.ceil supported dtypes

### ISSUE THREAD

**Issue by RickSanchezStoic** [tensorflow/tensorflow#57123]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### Current Behaviour?

```shell
https://www.tensorflow.org/api_docs/python/tf/math/ceil

The dtype section in the documentation above says `int32` which I believe is a mistake.
```

### Standalone code to reproduce the issue

```shell
import tensorflow
print(tensorflow.math.ceil(tensorflow.constant([1,2,3])))
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.InvalidArgumentError: Value for attr 'T' of int32 is not in the list of allowed values: bfloat16, half, float, double
	; NodeDef: {{node Ceil}}; Op<name=Ceil; signature=x:T -> y:T; attr=T:type,allowed=[DT_BFLOAT16, DT_HALF, DT_FLOAT, DT_DOUBLE]> [Op:Ceil]
```
</details>

**Comment by Deepchavan1** [comment]
Hey there, can I contribute to this issue?

**Comment by tilakrayal** [comment]
@RickSanchezStoic,
The PR has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
