### ISSUE TITLE
tf.sparse.reduce_max should update the static shape

### ISSUE THREAD

**Issue by yoeldr** [tensorflow/tensorflow#57148]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### Current Behaviour?

```shell
tf.sparse.reduce_max(..., output_is_sparse=True) does not fill the result's static shape, although it can easily be done (like in the output_is_sparse=False case).
```

### Standalone code to reproduce the issue

```shell
@tf.function
def f(n):
  t = tf.sparse.eye(n)
  tf.print(t.shape)
  result = tf.sparse.reduce_max(t, axis=1, keepdims=True, output_is_sparse=True)
  tf.print(result.shape)


f(3)
```

### Relevant log output

```shell
TensorShape([3, 3])
TensorShape(None)
```
</details>

**Comment by HarisBalaji** [comment]
Hi, @sushreebarsa if I want to be assigned an open issue, what can I do or how to do show my willingness?

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/b2ff803a62aabc03c8f8603b3215f87a/57148.ipynb) here. Thank you!

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
