### ISSUE TITLE
tf.clip_by_value allows clip_value_min greater than clip_value_max

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#57151]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF2.4

### Custom Code

Yes

### OS Platform and Distribution

win11

### Current Behaviour?

```shell
When clip_value_min is greater than clip_value_max, the snippet code works but behaves abnormally. I think it should throw exception or add an example in documentation to illustrate what will happen when clip_value_min > clip_value_max.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  arg_0 = tf.random.uniform([2, 3], maxval=10, dtype=tf.float32)
  print(arg_0)
  '''
  arg_0 = tf.Tensor(
[[4.7769785  0.57591677 4.4995    ]
 [0.93842626 4.697542   2.146771  ]], shape=(2, 3), dtype=float32)
  '''
  clip_value_min = 1
  clip_value_max = -1
  results["res"] = tf.clip_by_value(arg_0,clip_value_min=clip_value_min,clip_value_max=clip_value_max,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
'''
  results = {'res': <tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>}
'''
```

### Relevant log output

_No response_</details>

**Comment by aniruthraj** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
