### ISSUE TITLE
filters can be set to float in tf.keras.layers.Conv1D

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#57164]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF2.4

### Custom Code

Yes

### Current Behaviour?

```shell
filters should be an integer, because it's relevant to the dimensionality of the output space. Also it must be an integer written on the document. However, I find that when the type of filters is float, code works.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
results={}
try:
  padding = "same"
  filters = 2.5
  kernel_size = 3
  arg_class = tf.keras.layers.Conv1D(padding=padding,filters=filters,kernel_size=kernel_size,)
  arg_input = tf.random.uniform([1, 2, 2], dtype=tf.float32)
  results["res"] = arg_class(arg_input)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
'''
results = {'res': <tf.Tensor: shape=(1, 2, 2), dtype=float32, numpy=
array([[[-0.49259394,  0.5246876 ],
        [-0.00979106,  0.42434496]]], dtype=float32)>}
'''
```

### Relevant log output

_No response_</details>

**Comment by cheyennee** [comment]
Same problem is found in similar APIs:
tf.keras.layers.Conv1DTranspose
tf.keras.layers.Conv2D
tf.keras.layers.Conv2DTranspose
tf.keras.layers.Conv3D
tf.keras.layers.Conv3DTranspose

**Comment by cheyennee** [comment]
size can be set to float in tf.keras.layers.UpSampling1D. But size should be an integer written in documentation.
```
import tensorflow as tf
results={}
try:
  size = 2.5
  arg_class = tf.keras.layers.UpSampling1D(size=size,)
  arg_input = tf.saturate_cast(tf.random.uniform([2, 2, 3], minval=-256, maxval=257, dtype=tf.int64), dtype=tf.int64)
  results["res"] = arg_class(arg_input)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
```
Above code works.

**Comment by sushreebarsa** [comment]
@cheyennee I was able to replicate the issue, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/ea0d92d441898baa946b45aff508506f/57164.ipynb) here. 
This issue seems to be Keras issue.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by cheyennee** [comment]
@sushreebarsa Thanks for reminding. I post this issue on keras repo, and the system asigns that issue to you automatically.

**Comment by sushreebarsa** [comment]
@cheyennee Thank you for the update!
Could you please move this issue to closed status as we will track the other ticket in keras-team/keras repo.
Thank you!
