### ISSUE TITLE
ERROR: Current implementation only supports equal length strides in the r.w and column dimensions!is there any plan to support this?

### ISSUE THREAD

**Issue by alexmil2019** [tensorflow/tensorflow#57250]
is there any plan to support this?

```
In [1]: import tensorflow as tf

In [2]: input_shape = (4, 256, 256, 3)

In [3]:  x = tf.random.normal(input_shape)

In [4]: y=tf.keras.layers.SeparableConv2D(2, 3, strides=(1,2),activation='relu', input_shape=input_shape[1:])(x)
---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
Input In [4], in <cell line: 1>()
----> 1 y=tf.keras.layers.SeparableConv2D(2, 3, strides=(1,2),activation='relu', input_shape=input_shape[1:])(x)

File ~/miniforge3/envs/tfn/lib/python3.10/site-packages/keras/utils/traceback_utils.py:67, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     65 except Exception as e:  # pylint: disable=broad-except
     66   filtered_tb = _process_traceback_frames(e.__traceback__)
---> 67   raise e.with_traceback(filtered_tb) from None
     68 finally:
     69   del filtered_tb

File ~/miniforge3/envs/tfn/lib/python3.10/site-packages/tensorflow/python/framework/ops.py:7164, in raise_from_not_ok_status(e, name)
   7162 def raise_from_not_ok_status(e, name):
   7163   e.message += (" name: " + name if name is not None else "")
-> 7164   raise core._status_to_exception(e) from None

InvalidArgumentError: Exception encountered when calling layer "separable_conv2d" (type SeparableConv2D).

Current implementation only supports equal length strides in the row and column dimensions. [Op:DepthwiseConv2dNative] name: depthwise

Call arguments received by layer "separable_conv2d" (type SeparableConv2D):
  • inputs=tf.Tensor(shape=(4, 256, 256, 3), dtype=float32)

In [6]: tf.__version__
Out[6]: '2.9.2'
```

_Originally posted by @alexmil2019 in https://github.com/tensorflow/tensorflow/issues/33005#issuecomment-1176697401_

**Comment by sushreebarsa** [comment]
@alexmil2019 
In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose),
Thank you!

**Comment by alexmil2019** [comment]
Issue Type:bug

v2.9.0-18-gd8ce9f9c301 2.9.1

source: binary

Tensorflow Version: 2.9.1

Custom Code: No

OS Platform and Distribution
linux: ubuntu 18.04.6 LTS (Bionic Beaver)

cuda version:
cuda_11.0_bu.TC445_37.28845127_0

**Comment by sushreebarsa** [comment]
@alexmil2019 
I was able to replicate the issue [here](https://colab.research.google.com/gist/sushreebarsa/cb65bda76727d634bf6940943be58e20/57250.ipynb).
This issue seems to be Keras issue.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
