### ISSUE TITLE
`tf.linalg.sqrtm` crashes when computing gradient for empty input

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#57486]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
floating point exception (core dumped) when compute gradient.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = tf.random.uniform([3, 0, 0, 0], minval=0.2782671520237796, maxval=1.0, dtype=tf.float32)
print(tf.linalg.sqrtm(x))

with tf.GradientTape() as g:
    g.watch(x)
    res_backward = tf.linalg.sqrtm(x)
print(res_backward)
grad = g.jacobian(res_backward, [x])
print(grad)
```

### Relevant log output

```shell
tf.Tensor([], shape=(3, 0, 0, 0), dtype=float32)
tf.Tensor([], shape=(3, 0, 0, 0), dtype=float32)
floating point exception (core dumped)
```
</details>

**Comment by VictoriaGriffith** [comment]
I think the bug comes from this low-level api `tf.raw_ops.MatrixSquareRoot`, which also crashes on the same input:
```
import tensorflow as tf
x = tf.random.uniform([3, 0, 0, 0])
y = tf.raw_ops.MatrixSquareRoot(input=x)
print(y)
with tf.GradientTape() as g:
    g.watch(x)
    y_2 = tf.raw_ops.MatrixSquareRoot(input=x)
print("y_2: ", y_2)
# y_2:  tf.Tensor([], shape=(3, 0, 0, 0), dtype=float32)
grad = g.jacobian(y_2, [x]) 
# floating point exception (core dumped)
```

**Comment by tilakrayal** [comment]
@gowthamkpr,
I was able to reproduce the issue on tensorflow v2.9, v2.8 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/f5b5349871127659779c9fe7e9ec69e5/untitled534.ipynb).

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

I tried with the alternative approach and code was executed with the expected result. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/67d71287a1ee4a9caaec9acb477a34d7/untitled2227.ipynb).

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
