### ISSUE TITLE
`tf.raw_ops.UnicodeDecodeWithOffsets` crashes

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#57488]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
Session crashes.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
input = "text"
input_encoding = "utf-8"
errors = "replace"
replacement_char = 65533
replace_control_characters = False
Tsplits = 3.0
result =  tf.raw_ops.UnicodeDecodeWithOffsets(input=input, input_encoding=input_encoding, errors=errors, replacement_char=replacement_char, replace_control_characters=replace_control_characters, Tsplits=Tsplits, )
```

### Relevant log output

```shell
F tensorflow/core/framework/tensor.cc:725] Check failed: dtype() == expected_dtype (9 vs. 3) int32 expected, got int64
abort (core dumped)
```
</details>

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/efd51855e1aebafe8196ada57d9459ca/57488.ipynb) here. 
Thank you!

**Comment by sachinprasadhs** [comment]
Tsplits has to be one of the dtype from `tf.dtypes`.

> Tsplits | An optional tf.DType from: tf.int32, tf.int64. Defaults to tf.int64.

Below is the working code and the output.

```
import tensorflow as tf
input = "text"
input_encoding = "utf-8"
errors = "replace"
replacement_char = 65533
replace_control_characters = False
Tsplits = tf.dtypes.int64
result =  tf.raw_ops.UnicodeDecodeWithOffsets(input=input, input_encoding=input_encoding, errors=errors, replacement_char=replacement_char, replace_control_characters=replace_control_characters, Tsplits=Tsplits, )

UnicodeDecodeWithOffsets(row_splits=<tf.Tensor: shape=(2,), dtype=int64, numpy=array([0, 4])>, char_values=<tf.Tensor: shape=(4,), dtype=int32, numpy=array([116, 101, 120, 116], dtype=int32)>, char_to_byte_starts=<tf.Tensor: shape=(4,), dtype=int64, numpy=array([0, 1, 2, 3])>)
```

**Comment by VictoriaGriffith** [comment]
Thanks @sachinprasadhs , indeed the Tsplits has to be one of the dtype from tf.dtypes, however, as a public API, it should handle invalid inputs properly instead of throwing Check Fail and crash.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
