### ISSUE TITLE
When input is a tensor, the 'axis' is not type checked in tf.concat

### ISSUE THREAD

**Issue by cheyennee** [tensorflow/tensorflow#57526]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

TF2.8

### Custom Code

Yes

### Current Behaviour?

```shell
Axis must be in the range [-rank(values), rank(values)) written on documentation [https://tensorflow.google.cn/versions/r2.4/api_docs/python/tf/concat#args]. When input is a list of tensor, axis will validate the range. However, when input is a single tensor, axis won't check the range.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
t1 = [[[1, 2], [2, 3]], [[4, 4], [5, 3]]]
t2 = [[[7, 4], [8, 4]], [[2, 10], [15, 11]]]
res = tf.concat([t1, t2], -100)
print(res)
'''
tensorflow.python.framework.errors_impl.InvalidArgumentError: ConcatOp : Expected concatenating dimensions in the range [-3, 3), but got -100 [Op:ConcatV2]
'''

Above code will check the validity of axis, but the following code wont.

import tensorflow as tf
results={}
try:
  arg_0 = tf.saturate_cast(tf.random.uniform([2, 4], minval=-256, maxval=257, dtype=tf.int64), dtype=tf.int64)
  axis = -200
  results["res"] = tf.concat(arg_0,axis=axis,)
except Exception as e:
  results["err"] = "Error:"+str(e)
print(results)
'''
{'res': <tf.Tensor: shape=(2, 4), dtype=int64, numpy=
array([[ 140,  236, -151,   66],
       [ 154,   28,  -82,   23]])>}
'''
```

### Relevant log output

_No response_</details>

**Comment by gadagashwini** [comment]
I was able to reproduce the issue with Tensorflow 2.8.2 and 2.9.2. Please find the gist [here](https://colab.research.google.com/drive/1lH3U9dergmhVYzdTtR6jAcdzt97eeJOm?usp=sharing). Thank you!

**Comment by cantonios** [comment]
Our concat ["op"](https://github.com/tensorflow/tensorflow/blob/c086ec2e3b75c7c0ea0a0345939b7b5023436f9c/tensorflow/core/ops/array_ops.cc#L528) requires there be 2+ tensors, and that is where the error checking happens.  If there is only one tensor input, we simply return it and the operation becomes a noop.  It would probably be wasteful to force an additional check/assertion here.

**Comment by cheyennee** [comment]
@cantonios So should the documentation separately state the value of axis in the case of only one input tensor? Or add an example to illustate what will happen when input is one tensor.

**Comment by cantonios** [comment]
Why?  I don't think we want it officially part of the API that the axis is ignored when inputing a single tensor.  It is still a user error.  It just is not worth us checking for it since doing so only adds overhead, and we return the correct result if the specified axis was _any_ valid value.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
