### ISSUE TITLE
Forward gradient does not support `axis=[0]` for `tf.concat`

### ISSUE THREAD

**Issue by VictoriaGriffith** [tensorflow/tensorflow#57535]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
Inconsistent `axis` shape check for `tf.concat`: when `axis=[0]`, direct execution and reverse gradient computation both will succeed, but forward gradient does not support it and throws error.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = tf.random.uniform([12, 1, 1, 1], minval=0, maxval=2.0, dtype=tf.float32)
y = tf.random.uniform([12, 1, 1, 1], minval=0, maxval=2.0, dtype=tf.float32)
axis = [0]
result = tf.concat([x, y], axis)
print(result.shape) # Pass

with tf.GradientTape() as tape:
    tape.watch(x)
    result = tf.concat([x, y], axis)
print(result.shape)
print(tape.gradient(result, x).shape) # Reverse mode AD pass

tangent = tf.reshape(tf.one_hot(1, tf.size(x), dtype=x.dtype), shape=x.shape)
with tf.autodiff.ForwardAccumulator(x, tangent) as acc:
    result = tf.concat([x, y], axis) # Forward mode AD fail
```

### Relevant log output

```shell
(24, 1, 1, 1) 
(24, 1, 1, 1) 
(12, 1, 1, 1) 
Node: 'gradient_tape/ConcatOffset' 
Concat dim tensor should be a scalar integer, but got shape [1] 
 [[{{node gradient_tape/ConcatOffset}}]] [Op:__inference__jvp_helper_wrapper_78]
```
</details>

**Comment by sushreebarsa** [comment]
@sachinprasadhs I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/209e242b4f7d8e8eb938b553f84b953f/57535.ipynb) here. Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
