### ISSUE TITLE
[Question] Does Distributed TensorFlow can be run in  independent filesystem

### ISSUE THREAD

**Issue by ilixiaocui** [tensorflow/tensorflow#57605]
I used tensorflow version 1.14 to run distributed training and failed using the **local file system.**

I saw the exchange [post in 2018 on the Internet](https://groups.google.com/a/tensorflow.org/g/discuss/c/-NdsSrWmp8w), saying that the distributed training must use the shared file system at that time, but the local file system will be supported later
![image](https://user-images.githubusercontent.com/15689619/188060748-9bff0805-1799-4009-9cb3-248f7ec8960f.png)

Is there a version that supports running distributed training tasks on the local file system?

**Comment by sushreebarsa** [comment]
@ilixiaocui 
In order to expedite the trouble-shooting process here, could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose).
Older version of TF (1.x) is not actively supported, could you please upgrade to latest TF version and let us know if the issue still persists in latest TF version? 
Thank you!

**Comment by ilixiaocui** [comment]
@sushreebarsa 
Okay. New related issue: https://github.com/tensorflow/tensorflow/issues/57618

**Comment by sushreebarsa** [comment]
@ilixiaocui Could you please move this issue to closed status as it is a duplicate ticket. Thank you!
