### ISSUE TITLE
Documentation for tf.strided_slice is nearly useless

### ISSUE THREAD

**Issue by yaccman** [tensorflow/tensorflow#5761]
The documentation for this op could almost be used as a teaching moment for how to not document something.  In order to understand what it does, it is necessary to not only understand in detail how the related numpy op works, but also understand the mapping between the inputs of that op and the inputs of theTensorFlow op, that are totally different -- something that is far from obvious.

Just to ice the cake, the examples given in the document are for slice, not strided_slice...

Searches didn't turn up anything.  TF version is .11.  The machine and OS are not applicable.

**Comment by aselle** [comment]
I apologize for the confusion and frustration. A few notes that might be of help.

1. The examples actually are for strided_slice, and there has been a correction to the documentation just made to correct that.
2. If operating in Python you almost always should use the tensor slice operator (i.e. getitem)
https://www.tensorflow.org/versions/master/api_docs/python/framework.html#Tensor (and search for __getitem__)
3. I will add a link referring to the the Tensor.__getitem__ documentation from here, because that is almost always what you want to be using.
4. If you have a suggestion on how to restructure the documentation to be more intuitive, I would be happy to integrate it. Perhaps a section that gives some examples of what it can do first. I do believe that what is there is useful for those that do know what the NumPy slice does, which is probably many people.

**Comment by krstovski** [comment]
The example code has a typo:
tf.slice -> tf.strided_slice
Also, the third example doesn't produce the given result:
tf.slice(input, [1, 1, 0], [2, -1, 3], [1, -1, 1]) **!=**> [[[4, 4, 4], [3, 3, 3]]]

**Comment by danielwatson6** [comment]
As of version .12, `tf.strided_slice` has `[misleading documentation](https://www.tensorflow.org/versions/master/api_docs/python/array_ops/slicing_and_joining#strided_slice)`.  A fourth argument is mandatory, not a keyword argument, and it cannot be `None`.
