### ISSUE TITLE
BroadcastGradientArgs is used in protocol buffers but undocumented

### ISSUE THREAD

**Issue by yaccman** [tensorflow/tensorflow#5762]
Not too much to say about this.  The op, having two outputs, is far from trivial to figure out from its usage.  It is used in a number of the early TensorFlow tutorials.

TensorFlow .11

**Comment by prb12** [comment]
This is an internal op used in autogenerated gradient code to support gradient computation for ops which support broadcasting.  You should not be using it directly.

**Comment by yaccman** [comment]
This is a very unsatisfying answer for those of us who are trying to persuade TensorFlow to run on new hardware.  It is not an internal op if it appears in the protocol buffer.  Please rethink this...

**Comment by prb12** [comment]
@yaccman  Believe me, I came across the exact same problem about 9 months ago when working on compiling TF graphs for new hardware platforms. ;-)

Working directly from the GraphDef you are going to find an increasing number of problems like this, not least due to the ever increasing use of custom ops.  In the ideal case, constant folding removes much of this sort of code when you provide adequate shape information, but it is fragile to rely on this.

For this reason that we are encouraging people (internally and externally) to standardize on XLA as a portable intermediate representation for those targeting new hardware and accelerator platforms.   The aim is to have a small and complete set of primitives with well-defined semantics that compiler writers can implement, and TF will provide the translation to XLA for connected subgraphs which are suitable for compilation/acceleration. 

If you are working on something like this then please contact @wolffg or Zak Stone.

**Comment by jedld** [comment]
Based on usage it looks like it returns the axis of reduction given two tensor shapes. Notice that the return values of this is always used for reduce_sum. ops that support broadcasting (an op involving a tensor of lesser rank or shape) needed to have a reduction function so that the resulting gradient has the same original size. It has the effect of summing individual gradients into one value.
