### ISSUE TITLE
Partial GPU Logical Device configurations fail on TF 2.10 

### ISSUE THREAD

**Issue by rainwoodman** [tensorflow/tensorflow#57641]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10

### Custom Code

No

### Current Behaviour?

```shell
This is an issue to document a known issue with TensorFlow 2.10.

When the system is equipped with 2 or more GPUs, the following code snippet fails with TensorFlow 2.10:


gpus = tf.config.list_physical_devices('GPU')

# Error triggered if logical device configuration is only set 
# for gpus[0], not gpus[1].
tf.config.set_logical_device_configuration(gpus[0], [
    tf.config.LogicalDeviceConfiguration(memory_limit=100),
    tf.config.LogicalDeviceConfiguration(memory_limit=100)
    ])

# Fails
tf.config.list_logical_devices('GPU')

# Raises Error: tensorflow.python.framework.errors_impl.InvalidArgumentError: 
# Device ordinals must be set for all virtual devices or none. But the device_ordinal is specified for 1 while previous devices didn't have any set.
```

2 known workarounds:

- The user can hide the other physical GPUs from TensorFlow with `tf.config.set_visible_devices()`.
- The user can set Logical device configuration to all physical GPUs.

A fix will be included in the next release of TensorFlow.

Reference:
The bug was discovered during TensorFlow Addons 2.10 release. [Discussion Thread](
https://github.com/tensorflow/tensorflow/commit/6c6fe3d2f55d90ef59447c378ff7970559a5d3a6#r83220055)
```


### Standalone code to reproduce the issue

```shell
Refer to above.
```

### Relevant log output

_No response_</details>

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
