### ISSUE TITLE
Periodic-boundary padding for tensors

### ISSUE THREAD

**Issue by Jverduzc** [tensorflow/tensorflow#57672]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.10

### Custom Code

No

### Python version

3.9

### Current Behaviour?

```shell
This issue is to request a feature for padding with "wrap", narrowing down suggestions from Issue #956 (https://github.com/tensorflow/tensorflow/issues/956).

This mode of padding is included as an option in numpy.pad()
https://docs.scipy.org/doc/numpy/reference/generated/numpy.pad.html

It would be very beneficial for applications that require periodic boundary conditions, in particular for physics-based calculations.
```

### Standalone code to reproduce the issue

```shell
# From the original issue:

import numpy
matrix = numpy.arange(25).reshape(5,5)
paddings = [[1,1],[1,1]]
# periodic boundary conditions
padded_matrix = numpy.pad(matrix, pad_width=paddings, mode='wrap')
```

### Relevant log output

_No response_</details>

**Comment by cantonios** [comment]
Just to confirm, we're talking specifically about `tf.pad`?

**Comment by cantonios** [comment]
Those are two separate things.  Adding an option to `tf.pad` is relatively straightforward.  Adding to all convolutions is a whole other beast which requires changing our APIs - our current convolution API doesn't have separate `padding` and `padding_mode` options, it assumes we always pad with zeros and only controls the size.

**Comment by Jverduzc** [comment]
I figured. This issue was implementing it with tf.pad() to do the padding operation separately from the convolution.

**Comment by Jverduzc** [comment]
Following up on this issue of adding tf.pad() option for 'wrap' as available in np.pad()

**Comment by cantonios** [comment]
Sounds fine to me if you'd like to add it as a new feature.

**Comment by madt2709** [comment]
Hey, I'd like to pick this up if no one is working on this.

**Comment by Jverduzc** [comment]
That would be awesome!

**Comment by mattbahr** [comment]
I'd like to try picking up on this where @madt2709 left off if that's alright.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
