### ISSUE TITLE
Include "name" parameter in tf.keras.models.clone_model() function to give a new name to the clone.

### ISSUE THREAD

**Issue by sky-2002** [tensorflow/tensorflow#57678]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.8.2

### Custom Code

No

### Current Behaviour?

```shell
When using the `tf.keras.models.clone_model(previous_model)` function, it assigns the same name as "previous_model" to the created clone. I want to assign a new name to the created clone. This can probably be done by passing a name parameter to the `clone_model()` function.
```

### Standalone code to reproduce the issue

```shell
`pre_m1 = tf.keras.Sequential([
    sentence_encoder_layer,
    layers.Dense(64,activation="relu"),
    layers.Dense(1,activation="sigmoid")
],name="pre_trained_m1")

pre_m2 = tf.keras.models.clone_model(pre_m1)

# In the summary, the name of pre_m2 is printed as "pre_trained_m1" i.e. same as pre_m1.
print(pre_m2.summary())
`
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@sky-2002 
This issue seems to be Keras issue.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!

**Comment by sky-2002** [comment]
@sushreebarsa , ok, I will post it on keras repo. Thank you !

**Comment by sushreebarsa** [comment]
@sky-2002 Thank you for the update!
Could you please move this issue to closed status if you have reported the same issue in keras-team/keras repo?
Thank you!

**Comment by sky-2002** [comment]
Ok, I have put it on keras repo. I will close this one. Thank you !
