### ISSUE TITLE
XLA makes copies of tensors instead of referencing them

### ISSUE THREAD

**Issue by mstebelev** [tensorflow/tensorflow#57681]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

binary

### Tensorflow Version

2.8

### Custom Code

No

### Current Behaviour?

```shell
Wrapping just one tf.reshape operation into compiled @tf.function(jit_compile=True) works much more slower than without XLA compilation. It turns out that generated code contains copying of incoming tensor rather than referencing it with different shape.
Module after compilation looks like 

HloModule a_inference_foo_xla_9__XlaMustCompile_true_config_proto_6001324581131673121_executor_type_11160318154034397263_.8, alias_passthrough_params=true

ENTRY %a_inference_foo_xla_9__XlaMustCompile_true_config_proto_6001324581131673121_executor_type_11160318154034397263_.8 (arg0.1: f32[100,200,300]) -> f32[2,3000000] {
  %arg0.1 = f32[100,200,300]{2,1,0} parameter(0), parameter_replication={false}, metadata={op_name="XLA_Args"}
  %bitcast = f32[2,3000000]{1,0} bitcast(f32[100,200,300]{2,1,0} %arg0.1), metadata={op_type="Reshape" op_name="Reshape" source_file="<ipython-input-3-906cbb49fe55>" source_line=6}
  ROOT %copy = f32[2,3000000]{1,0} copy(f32[2,3000000]{1,0} %bitcast)
}
``` and includes copy operation, while reshape can be done without any copies
```

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1Y3Sv-Ji8zf-0dpTuvSIYc-zyQBkC4HrL
```

### Relevant log output

```shell
[5] %timeit foo_xla(rnd)
34.5 ms ± 4.25 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
[6] %timeit foo_tf(rnd)
371 µs ± 60 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```
</details>

**Comment by sushreebarsa** [comment]
@mstebelev I tried to replicate the issue on colab using latest TF v2.10, please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/28351df84b47f1e383b225229a04dc03/xla_reshape.ipynb#scrollTo=y4F4h6syYQBT) and confirm the same?
Thank you!

**Comment by mstebelev** [comment]
Yes, I see that in 2.10 something is better, but the problem with copy in generated XLA code is the same and you can see it in new version https://colab.research.google.com/drive/1ESGaYLMQttOqqc5GbJZxeC0NDOfipGF7 where we have a lot of reshapes of the same tensor in one operation

**Comment by cheshire** [comment]
In general XLA does not know whether it can alias input and output. I guess this could be fixed at the bridge level, but what we have seen so far, most large aliasing updates are done with resource variables, where aliasing does work.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
