### ISSUE TITLE
Datasets created by `from_generator` do not properly release objects

### ISSUE THREAD

**Issue by iwiwi** [tensorflow/tensorflow#57690]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.10.4

### Current Behaviour?

When we create a dataset by using `tf.data.Dataset.from_generator`, it seems that Python objects captured in the generator are not properly released.

This causes crucial memory leak when conducting experiments that creates datasets with large memory footprint for multiple times (e.g., cross validation).

### Standalone code to reproduce the issue

We expect `__del__ called!` to be printed for three times, but it is never printed.

```python
from typing import Generator

import tensorflow as tf


class SomeObj:
    def __init__(self, x):
        self.x = x

    def __del__(self):
        print("__del__ called!")


def build_dataset(
    obj: SomeObj,
) -> tf.data.Dataset:
    def _generator() -> Generator[tf.Tensor, None, None]:
        while True:
            yield tf.convert_to_tensor(obj.x, dtype=tf.float32)

    return tf.data.Dataset.from_generator(
        _generator,
        output_signature=tf.TensorSpec(shape=(), dtype=tf.float32),
    )


def train_for_a_fold(fold):
    dataset = build_dataset(SomeObj(fold))
    for x in dataset.take(3):
        print(x)


def main():
    train_for_a_fold(0)
    train_for_a_fold(1)
    train_for_a_fold(2)


if __name__ == "__main__":
    main()
```
#### Output

```
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(0.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(1.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
tf.Tensor(2.0, shape=(), dtype=float32)
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@gadagashwini  I was able to replicate the issue on colab, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/4eb38608943d2c1124efbda44bd0f23c/57690.ipynb#scrollTo=xgiRF8AvQW0w) here. Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
