### ISSUE TITLE
Does op ADD support int8/int16 dtype? 

### ISSUE THREAD

**Issue by HensonMa** [tensorflow/tensorflow#57737]
Hi, I just got a issue about the op ADDV2. My model has the following part that I need to cast the float32 input to int8/int16/int32, then cast it back. When I cast the input to int8/int16, the final addition op changed from ADD to ADDV2 as I checked the graph. Hence, how can I avoid op ADDV2 and use op ADD for dtype int8/int16 (if possible), thanks!

```python
  def reshape_add(self, r, yy, method, name):
      """Match the dimension for residuals and add to activations."""
      if r is None:
          return yy
      r = tf.cast(r, tf.int16)
      out_features = yy.shape[3]
      in_features = r.shape[3]
      if in_features > out_features:
          r = r[:, :, :, :out_features]
      elif in_features < out_features:
          # assert method in ['tile', 'zeropad']
          if method == 'tile':
              ch_mult = out_features // in_features
              r = tf.tile(r, (1, 1, 1, ch_mult))
          elif method == 'zeropad':
              pad_size = out_features - in_features
              pad_width = ((0, 0), (0, 0), (0, 0), (0, pad_size))
              r = tf.pad(r, pad_width, mode = "CONSTANT")

      if yy.shape[1] != r.shape[1]:
          # r = tf.keras.layers.AveragePooling2D(pool_size=(3, 3), strides=(2, 2), padding='same')(r)
          r = r[:, :yy.shape[1], :yy.shape[1], :]

      yy_int = tf.cast(yy, tf.int16)
      sum_two = tf.add(yy_int, r)
      return tf.cast(sum_two, tf.float32)
```

### Environment

TensorFlow version: 2.9.1
python version:  3.8.13

**Comment by Shravankb301** [comment]
The model has Addv2 which accepts type int64. Tensorflow lite doesn't support Addv2 with int64 input/output.
Since you used SELECT_TF_OPS that means all non-supported ops will be exported as TF ops and run in TF.
To run the generated tflite file, you need to use Interpreter which supports SELECT.
Please follow the guide on creating an interpreter
https://www.tensorflow.org/lite/guide/ops_select

Another way is to update your model to use int32 instead of int64, convert without SELECT_TF_OPS and use a regular interpreter.
