### ISSUE TITLE
LRN operator outputs wrong results with `jit_compile=True`

### ISSUE THREAD

**Issue by Co1lin** [tensorflow/tensorflow#57746]
<details><summary>Click to expand!</summary> 
 
### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.8.2

### Custom Code

No

### Current Behaviour?

The operator LRN outputs a valid real number like 0.35355338 although according to its definition it should give nan because the input have nan. This issue will not happen w/o XLA, so XLA should have consistent behavior.

### Standalone code to reproduce the issue

CoLab here: https://colab.research.google.com/drive/16QQ5ZUDLCoc7we7TDXvVPrb7OW_fiMNM?usp=sharing

```python
import tensorflow as tf
print(tf.__version__)
from keras import layers


class MyModule(tf.Module):
    def __init__(self):
        super().__init__()

    @tf.function(jit_compile=True)
    def __call__(self, x):
        x = tf.sqrt(x)
        x = tf.raw_ops.LRN(
            input=x,
            depth_radius=1,
            bias=1,
            alpha=1,
            beta=1,
        ) # input / (bias + alpha * sqr_sum) ** beta
        return x


m = MyModule()
x = tf.constant(
    [[[[-0.5,  0.5,  0.5]]]], dtype=tf.float32,
)
with tf.device('/CPU:0'):
    tf.config.run_functions_eagerly(True)
    out = m(x)
    print(out) # tf.Tensor([[[[nan nan nan]]]], shape=(1, 1, 1, 3), dtype=float32)
    tf.config.run_functions_eagerly(False)

with tf.device('/CPU:0'):
    out = m(x)
    print(out) # NOTE: WRONG! tf.Tensor([[[[       nan        nan 0.35355338]]]], shape=(1, 1, 1, 3), dtype=float32)
```

### Relevant log output

```python
2.8.2
tf.Tensor([[[[nan nan nan]]]], shape=(1, 1, 1, 3), dtype=float32)
tf.Tensor([[[[       nan        nan 0.35355338]]]], shape=(1, 1, 1, 3), dtype=float32)
```

</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.9 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b3202bd55007bb04da367dcac7920227/57746.ipynb).

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
