### ISSUE TITLE
TFLite's max operator has wrong broadcasting behavior

### ISSUE THREAD

**Issue by Co1lin** [tensorflow/tensorflow#57759]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 20.04.4 LTS
- TensorFlow installation (pip package or built from source): pip package
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.11.0.dev20220914

### 2. Code

Provide code to help us reproduce your issues using one of the following options:

#### Option A: Reference colab notebooks

https://colab.research.google.com/drive/1SWl6-cWwk2zRkiNYifUXtzojSz_uUCxg?usp=sharing

### 3. Failure after conversion

After converting to TFLite, the model produces tensor with wrong shape. This is inconsistent with normal TF runtime, and numpy behavior.

**Comment by mohantym** [comment]
Hi @Co1lin !
It is replicating in nightly but It was throwing converter error in 2.9 and [2.10.](https://colab.sandbox.google.com/gist/mohantym/6c431570c7da6ef672f4b5ae75970225/tflite_max_broadcasting.ipynb#scrollTo=0txzVtMiUA8G) As the documentation on[ tf.maximum](https://www.tensorflow.org/api_docs/python/tf/math/maximum) suggests you should use same shapes for both input and output.

Thank you!

**Comment by Co1lin** [comment]
Hi, thank you for the reply! Since the documentation of maximum also notes that "Note that maximum supports [broadcast semantics](http://docs.scipy.org/doc/numpy/user/basics.broadcasting.html) for x and y" which means numpy style broadcasting is supported, it's better if TFLite can produce the same results as numpy and TF.

**Comment by mohantym** [comment]
Ok @Co1lin !
Thanks for the clarification. It is a valid bug then.

@sachinprasadhs !
Could you look at this issue. Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/7f2909103fa5a13302e3200b82ee4c51/tflite_max_broadcasting.ipynb#scrollTo=Di0nTeNJjHpc), [2.10](https://colab.sandbox.google.com/gist/mohantym/6c431570c7da6ef672f4b5ae75970225/tflite_max_broadcasting.ipynb#scrollTo=Di0nTeNJjHpc) and [nightly](https://colab.sandbox.google.com/gist/mohantym/d3363177e706d3b2c669c3ff3f8a799f/tflite_max_broadcasting.ipynb#scrollTo=Di0nTeNJjHpc) for reference.

Thank you!

**Comment by ganler** [comment]
@mohantym @sachinprasadhs  It seems this bug only occurs when one of the arguments in max is `tf.zeros`. When setting it to `tf.ones`, the inferred shape will be correct.

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
