### ISSUE TITLE
`tf.experimental.numpy.isposinf` has wrong output when input is integer.

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#57863]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

When integer tensor with +/- inf values, is passed to `tf.experimental.numpy.isposinf`, it has different results on cpu/cuda, and is different from numpy outputs. 

In the example, the input is [-inf,0,inf] for `int32` data type. On cpu, `tf.experimental.numpy.isposinf` wrongly output `True` for `-inf`.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
with tf.device('cpu'):
    x = tf.constant([-2147483648,0,2147483647], dtype=tf.int32)
    result = tf.experimental.numpy.isposinf(x)
    print("cpu:", result)

    
with tf.device('gpu'):
    x = tf.constant([-2147483648,0,2147483647], dtype=tf.int32)
    result = tf.experimental.numpy.isposinf(x)
    print("cuda:", result)

import numpy as np

x = np.array([-2147483648,0,2147483647], dtype=np.int32)
print("numpy:", np.isposinf(x))
```

### Relevant log output

```shell
cpu: tf.Tensor([ True False False], shape=(3,), dtype=bool)
cuda: tf.Tensor([False False  True], shape=(3,), dtype=bool)
numpy: [False False False]
```
</details>

**Comment by tiruk007** [comment]
@gadagashwini 
I was able to reproduce the issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/dc5fef4f7d83733906db6576299c812e/untitled13.ipynb) for reference.
Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
