### ISSUE TITLE
XLA tests fail with compute-sanitizer due to CAS operation on small dtype

### ISSUE THREAD

**Issue by nouiz** [tensorflow/tensorflow#57862]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Source

source

### Tensorflow Version

master branch

### Custom Code

No

### OS Platform and Distribution

Linux

### Python version

not relevant

### Bazel version

5.1.1

### GCC/Compiler version

9.4.0

### GPU model and memory

V100-16G

### Current Behaviour?

```shell
Some XLA tests fail with compute-sanitizer. There is one example in the repro section bellow.

There is one issue in the function EmitAtomicOperationUsingCAS that can trigger this. Mostly, it always read 4 bytes, even if only 1 was allocated.
One simple solution would be to always allocate at least 4 bytes. This won't changes anything as internally, the memory is allocated by block of more then 4 bytes.
```

### Standalone code to reproduce the issue

```shell
bazel test --verbose_failures -c opt --cxxopt=-D_GLIBCXX_USE_CXX11_ABI=1 --java_runtime_version=remotejdk_11 --run_under=compute-sanitizer //tensorflow/compiler/xla/tests:scatter_test_gpu
```

### Relevant log output

```shell
========= Invalid __global__ read of size 4 bytes
=========     at 0x200 in fusion_1
=========     by thread (0,0,0) in block (0,0,0)
=========     Address 0x7f79a5c00800 is out of bounds
=========     and is inside the nearest allocation at 0x7f79a5c00800 of size 1 bytes
=========     Saved host backtrace up to driver entry point at kernel launch time
...
```
</details>

**Comment by tilakrayal** [comment]
@nouiz,
Could you please provide the complete error log. It helps to debug the issue. Thank you!

**Comment by nouiz** [comment]
[test.log](https://github.com/tensorflow/tensorflow/files/9666116/test.log)
Here it is.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
