### ISSUE TITLE
Tensorflow lite Vulkan delegate

### ISSUE THREAD

**Issue by csn1800** [tensorflow/tensorflow#57861]
I have built TF lite GPU delegate to work with Open GL using the following target: `tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so`

How exactly am I supposed to enable Vulkan support? I have seen some references to Vulkan under `tensorflow/lite/delegates/gpu/gl` such as compiler options. Please suggest the steps to follow in enabling Vulkan support.

Also, is this comparison still valid: https://blog.tensorflow.org/2020/08/faster-mobile-gpu-inference-with-opencl.html which says:
`OpenCL-based mobile GPU inference engine for Android, which offers up to ~2x speedup over our existing OpenGL backend`

Are similar optimizations available for Vulkan/OpenGL or using them will compromise the speed in comparison with OpenCL?

**Comment by mohantym** [comment]
Hi @csn1800 !
I am not sure on building specifically to Vulgan delgate and Open GL support.
For building and integrating a delegate w.r.to a specific hardware ,  Standard procedure is to build it using bazel command and call it interpreter using below command.

 

```

//-c opt for C++ implementation , anrdoid_arm64 for android architecture.

bazel  build -c opt --config android_arm64 //tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_gl.so
```

```
# import the delegate in interpreter options , Java code
import tensorflow as tf

try:
  delegate = tf.lite.experimental.load_delegate('delegate.so')
except ValueError:
  // Fallback to CPU

if delegate:
  interpreter = tf.lite.Interpreter(
      model_path='model.tflite',
      experimental_delegates=[delegate])
else:
  interpreter = tf.lite.Interpreter(model_path='model.tflite')
```
For C implmentation , Please refer details [here.](https://www.tensorflow.org/lite/android/delegates/gpu#cc_api_for_android:~:text=When%20calling%20Interpreter,ModifyGraphWithDelegate()%20was%20called.)


[Reference](https://www.tensorflow.org/lite/android/delegates/gpu#cc_api_for_android) .

Thank you!

**Comment by csn1800** [comment]
Thanks for the response @mohantym . So, you mean to say there is no specific build target available for Vulkan and that Tensorflow is not optimized for Vulkan?

I assume you missed out my other question - Could you please clarify if OpenCL is giving optimum performance for TF lite in comparison with other delegates (OpenGL/Vulkan) as suggested by https://blog.tensorflow.org/2020/08/faster-mobile-gpu-inference-with-opencl.html ?
I could observe quite some differences in OpenGL delegate support such as minimal options available with TfLiteGpuDelegateOptions (no inference priorities and experimental flags for OpenGL)

**Comment by mohantym** [comment]
@csn1800 !
Thanks for the update. 

@sachinprasadhs !
Could you look at this query.
Thank you!

**Comment by csn1800** [comment]
@impjdi Could you please look at the query and respond?

**Comment by impjdi** [comment]
You can't use the OpenGL delegate to run it on Vulkan.  We do have a Vulkan implementation internally, but we haven't open sourced it yet due to binary size reason.  The Vulkan impl would have to be shipped with shaderc which is another tens of megabytes; we're waiting for Android to ship shaderc as part of the OS so that devs don't have to eat the app size cost, but it's seeing very little progress on that end.  So ... no Vulkan impl in the short term.

**Comment by eulercat** [comment]
@impjdi  Hello, would you let me know if there is any update for supporting vulkan delegate?

**Comment by impjdi** [comment]
The code has been sitting there ready for more than a couple years now. The only blocker is the availability of shaderc in Android. Without it, our Vk delegate wouldn't work, and if you try to ship the binary with it, you'll see a 10~20MB binary size increase of your app for no real benefit compared to OpenCL or OpenGL.  We've been trying hard to convince the Android team to ship shaderc as part of GMS core, but that hasn't gone anywhere.  However, there's new development in this direction.  While we can't commit to a timeline, there'll be Vk inference in one way or the other in an interesting form.

**Comment by eulercat** [comment]
@impjdi Thanks for the response. But I'm still curious about VK progress in android because in the android-dev site, there is a mention that android ndk already contains a a runtime library for compiling GLSL into SPIR-V. I'm not sure but it means that it might be a way to link VK delegate to that runtime for android?
* android dev site: [https://developer.android.com/ndk/guides/graphics/shader-compilers](https://developer.android.com/ndk/guides/graphics/shader-compilers)

**Comment by CaptainDario** [comment]
@impjdi Does the Vulkan backend have the same limitations as the OpenCL backend? By that I mean

* (Very) limited operator support
* Works only on Android / Linux

Or would the Vulkan backend work on all platforms (Windows/Mac/Linux/iOS/Android)?

**Comment by impjdi** [comment]
@eulercat That's a surprise; I was told that the libshaderc is not available and that's why we never launched out the Vk backend.  We will have to try it out.

@CaptainDario Yeah, the op set is going to be the same.  Believe it or not, even inside Google, there's been no new ops added to the op requests (maybe only a handful of highly customized ops not related to general neural network).  We don't aim to support server-side models or implement all 3000 TF ops, but only performance critical production models.

Even TFLite GPU (OpenGL / Metal / OpenCL) work on desktop (Linux & Mac) when configured correctly.  It's that we don't support the use case officially as we don't have the capacity to do so.  The Vulkan backend (to be released) will be primarily for Android, but nothing should prevent you from doing additional tweaks and making it runnable on desktop (we've seen people do that).

**Comment by CaptainDario** [comment]
@impjdi That are actually really interesting news! Do you have some pointers for me to get Metal on Mac working? Until now I always failed to get OpenCL working on Ubuntu 22.04 maybe you have some pointers there too?

**Comment by CaptainDario** [comment]
@impjdi I tried again compiling the benchmark tool with GPU delegate.
In CMake this fails like this #62941 

The bazel build finishes, but at runtime I get this error on Mac (on ubuntu it says basically the same just without GPUDelegate instead of MetalDelegate)

```
INFO: Created TensorFlow Lite delegate for Metal.
INFO: GPU delegate created.
ERROR: Following operations are not supported by GPU delegate:
DEQUANTIZE:
GATHER: Only support 1D indices

507 operations will run on the GPU, and the remaining 81 operations will run on the CPU.
ERROR: TfLiteMetalDelegate Prepare: newLibraryWithSource: program_source:23:119: error: expected expression
  {half4 second_value = src_tensor_1_buffer[((((0) * U.cmp_int4_1.x + 0) * U.cmp_int4_1.y + (0)) * U.cmp_int4_0.w + (()))];
                                                                                                                      ^

ERROR: Node number 588 (TfLiteMetalDelegate) failed to prepare.
ERROR: Restored original execution plan after delegate application failure.
ERROR: Failed to apply GPU delegate.
ERROR: Benchmarking failed.
```

And I wanted to ask you if there is any chance to support gather with more than one dimension.

**Comment by jeandsp** [comment]
Hello,

Any news about the Vulkan backend for TFlite ?
Is it still planned to be released ?

**Comment by tomeuv** [comment]
@impjdi Is there any chance of releasing the sources for the Vulkan delegate as an unsupported code drop? The people could base their external delegates on top of it and in time move to the in-repo delegate once Google merges it.

**Comment by impjdi** [comment]
Plans for 2025 aren't scoped out, but I don't think anyone is prioritizing the binary size concerns for the Vulkan inference.  We're looking into ways how we can achieve Vulkan inference via other ways, e.g. through WebGPU https://www.khronos.org/assets/uploads/developers/presentations/WebGPU_Meetup_-_WebGPU_on_Android.pdf but it's in early exploration stage.

**Comment by misterBart** [comment]
On https://developer.android.com/ndk/guides/graphics/shader-compilers I read

> The [NDK Release 12 and later](https://github.com/android-ndk/ndk/wiki) includes a runtime library for compiling GLSL into SPIR-V. The runtime library is the same as the one in the [Shaderc](https://github.com/google/shaderc) open source project, and uses the same [Glslang GLSL](https://github.com/KhronosGroup/glslang) reference compiler as its back end. By default, the Shaderc version of the compiler assumes you are compiling for Vulkan. After checking whether your code is valid for Vulkan, the compiler automatically enables the KHR_vulkan_glsl extension. The Shaderc version of the compiler also generates Vulkan-compliant SPIR-V code.

**Comment by tomeuv** [comment]
> Plans for 2025 aren't scoped out, but I don't think anyone is prioritizing the binary size concerns for the Vulkan inference. We're looking into ways how we can achieve Vulkan inference via other ways, e.g. through WebGPU https://www.khronos.org/assets/uploads/developers/presentations/WebGPU_Meetup_-_WebGPU_on_Android.pdf but it's in early exploration stage.

I understand that you don't have currently a plan for releasing a Vulkan delegate. What I was asking is for Google to do an unsupported code drop of what you already have internally.
