### ISSUE TITLE
`Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error` at fork

### ISSUE THREAD

**Issue by ganler** [tensorflow/tensorflow#57877]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

'2.11.0-dev20220927' (nightly)

### Custom Code

No

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.8

### GPU model and memory

A6000

### Current Behaviour?

```shell
When running `tf.function` in a forked process, the program crashed as "Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error". The forked subprocess will crash with an exit code `-6`.
```

### Standalone code to reproduce the issue

```shell
import multiprocessing as mp
import tensorflow as tf


@tf.function
def div(x):
    return (x + x) / (x + x)


with tf.device("/GPU:0"):
    div(tf.ones((100, 100)))


def run():
    with tf.device("/GPU:0"):
        print(div(tf.ones((100, 100))))


process = mp.Process(target=run)
process.start()
process.join()
print(f"Sub-process exited with {process.exitcode}")
```

### Relevant log output

```shell
"""
...
2022-09-27 13:45:15.709933: F tensorflow/compiler/xla/stream_executor/cuda/cuda_driver.cc:148] Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error
"""
```
</details>

**Comment by ganler** [comment]
Another reproducible is:

```python
import multiprocessing as mp
import tensorflow as tf

tf.config.list_physical_devices("GPU") # remove this line resolve the issue.

@tf.function(jit_compile=True)
def div(x):
    return x / x


def run():
    with tf.device("/GPU:0"):
        div(tf.ones((1, 1)))


process = mp.Process(target=run)
process.start()
process.join()
```

which says "could not retrieve CUDA device count: CUDA_ERROR_NOT_INITIALIZED: initialization error"

So it seems there are some bugs when calling logical devices after calling `list_physical_devices` in the parent process?

**Comment by sachinprasadhs** [comment]
I was able to get the output with exit code 0 using tf-nightly version in colab.
Could you please refer the gist [here](https://colab.sandbox.google.com/gist/sachinprasadhs/efb7171eb04f86c844382a9b20218184/57877.ipynb) for the same. Thanks!

**Comment by ganler** [comment]
Hi @sachinprasadhs , could you try this script? Sorry, the script I posted is not right.
 https://colab.research.google.com/drive/1CD9Soetr79d6UT_WEmkxzXcV2PC25FHD?usp=sharing

```python
import multiprocessing as mp
import tensorflow as tf


@tf.function
def div(x):
    return (x + x) / (x + x)


with tf.device("/GPU:0"):
    div(tf.ones((100, 100)))


def run():
    with tf.device("/GPU:0"):
        print(div(tf.ones((100, 100))))


process = mp.Process(target=run)
process.start()
process.join()
print(f"Sub-process exited with {process.exitcode}")
```

**Comment by ganler** [comment]
@sachinprasadhs @tilakrayal Any followup? Thanks!

**Comment by jthemphill** [comment]
Here's [a related StackOverflow question,](https://stackoverflow.com/questions/22950047/cuda-initialization-error-after-fork), and here's [a support forum with an Nvidia engineer's response](https://forums.developer.nvidia.com/t/cuda8-0-bug-child-process-forked-after-cuinit-get-cuda-error-not-initialized-on-cuinit/45764).

This sounds like a classic fork-safety issue. It's possible that `import tensorflow` initializes a global CUDA context variable by calling `cuInit()`, and forking a child process causes the children to reuse this global context instead of initializing their own contexts.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.

**Comment by kolcs** [comment]
> Another reproducible is:
> 
> import multiprocessing as mp
> import tensorflow as tf
> 
> @tf.function
> def div(x):
>     return x / x
> 
> with tf.device("/GPU:0"):    # rm this line can wrok
>     div(tf.ones((1, 1)))      # rm this line can wrok
> 
> def run():
>     with tf.device("/GPU:0"):
>         print(div(tf.ones((1, 1)))) # No print as the program exited with -6.
> 
> 
> process = mp.Process(target=run)
> process.start()
> process.join()
> print(f"Sub-process exited with {process.exitcode}")
> 
> which says "Failed setting context: CUDA_ERROR_NOT_INITIALIZED: initialization error"

I would like to highlight, that the issue is still open. 
I tried with different tensorflow[and-cuda] versions: 2.16, 2.17, 2.18, but none of them seems to work...
