### ISSUE TITLE
Function to disable tf.data debug mode

### ISSUE THREAD

**Issue by metinsuloglu** [tensorflow/tensorflow#57910]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

2.10

### Custom Code

No

### Current Behaviour?

```shell
Currently you can enable tf.data debug mode using: `tf.data.experimental.enable_debug_mode`.

However there is no option to disable it after it has been set.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

dataset = tf.data.Dataset.from_tensors([2.])

tf.data.experimental.enable_debug_mode()
# All datasets defined after this point will be in debug mode.
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
Thanks for the feature request, as the `enable_debug_mode` would redefine the tf.data pipeline and the subsequent tf.data operations runs under debug mode. 
It would not be a feasible way to disable the `debug_mode` dynamically.

**Comment by metinsuloglu** [comment]
It looks as though you already have a function to [toggle debug mode](https://github.com/tensorflow/tensorflow/blob/e34b9ffb5a4483e9ba570cd566999512e8508a18/tensorflow/python/data/ops/dataset_ops.py#L6541), wouldn't it be as simple as setting it to False?

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
