### ISSUE TITLE
Template code does not work

### ISSUE THREAD

**Issue by jntdst** [tensorflow/tensorflow#57921]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.8

### Custom Code

No

### OS Platform and Distribution

colab

### Mobile device

colab

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/keras/landingpage_example.ipynb

https://www.tensorflow.org/ranking
```

### Standalone code to reproduce the issue

```shell
A bug happened!
https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/keras/landingpage_example.ipynb

https://www.tensorflow.org/ranking
```

### Relevant log output

```shell
Input 0 of layer "batch_normalization" is incompatible with the layer: expected axis 2 of input shape to have value 1, but received input with shape (None, None, 136)
    
    Call arguments received by layer "model" "                 f"(type Functional):
      • inputs={'_mask': 'tf.Tensor(shape=(None, None), dtype=bool)', 'float_features': 'tf.Tensor(shape=(None, None, 136), dtype=float64)'}
      • training=True
      • mask=None
```
</details>

**Comment by tiruk007** [comment]
@jntdst 
This issue is closed when the [PR](https://github.com/tensorflow/ranking/pull/333) is merged.

Thank you!

**Comment by tilakrayal** [comment]
@jntdst,
Apologies for the delay. This issue is related to tensorflow/ranking code which we are not supporting. I request to please check in the respective repo for the quick resolutions. 

Also I tried to execute the mentioned code with the alternative approach and it was executed without any issue/error. Kindly find the alternative work-around gist [here](https://colab.research.google.com/gist/tilakrayal/404bf56119bc9857f74dcc5229f3e2ec/landingpage_example.ipynb).  Hope this helps the query. Thank you!
