### ISSUE TITLE
XLA compile enable an option to not fail fast

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#57923]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

2.10

### Custom Code

No

### Current Behaviour?

When a `tf.function` is jit compiled with XLA the graph validation is failing fast so we don't have the full overview of the invalid/uncovered node.

### Standalone code to reproduce the issue

https://github.com/tensorflow/tensorflow/blob/02d5a7dcd0d7ad12b040c465f96d7a91e6b162f1/tensorflow/compiler/tf2xla/xla_compiler.cc#L1277-L1297

### Relevant log output

_No response_</details>

/cc @paynecl

**Comment by bhack** [comment]
It would be also nice if we could validate the compilability for a target device without relying on the hw availability (e.g. like in cross compilation) especially for CI.

**Comment by bhack** [comment]
@paynecl This is also going eventually to pair with the new proposed compiler/runtime interface  and eventually to fully track the high level origin of a failure. See https://github.com/openxla/community/pull/33#issuecomment-1402852253

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
