### ISSUE TITLE
tf.io.gfile.glob is extremely slow

### ISSUE THREAD

**Issue by wookayin** [tensorflow/tensorflow#57939]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9 and 2.10

### Custom Code

No

### OS Platform and Distribution

macOS 12

### Mobile device

-

### Python version

3.9

### Bazel version

-

### GCC/Compiler version

-

### CUDA/cuDNN version

-

</details>

### Current Behaviour?

In my environments, `tf.io.gfile` APIs are extremely slow.

### Standalone code to reproduce the issue

For instance:

```
>>> import tensorflow.io.gfile as gfile  # type: ignore
>>> gfile.glob('gs://tfds-data/*.jsonl')
2022-10-01 22:59:07.324892: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "NOT_FOUND: Could not locate the credentials file.". Retrieving token from GCE failed with "FAILED_PRECONDITION: Error executing an HTTP request: libcurl code 6 meaning 'Couldn't resolve host name', error details: Could not resolve host: metadata".
['gs://tfds-data/community-datasets-list.jsonl']
```

The above takes around 70 seconds to query. Note that `gs://tfds-data/` bucket has only ~7 files on the root directory. Would `glob` walk the entire subtree recursively?

In contrast, `gsutil` commands are quite fast.
```
❯❯❯ time noglob gsutil ls gs://tfds-data/*.jsonl
gs://tfds-data/community-datasets-list.jsonl
noglob gsutil ls gs://tfds-data/*.jsonl  0.62s user 0.16s system 78% cpu 0.997 total
```

**Comment by tiruk007** [comment]
@gadagashwini 
I was able to reproduce the issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/3bc6b99cbc6c6236089a42363ef8b549/57939.ipynb) for reference.
Thank you!

**Comment by gowthamkpr** [comment]
This is still replicating in tf-nightly. Here's the [gist](https://colab.sandbox.google.com/gist/gowthamkpr/4f76a313b9614c573bfd3e4420072322/untitled443.ipynb)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
