### ISSUE TITLE
Issue with saving a network

### ISSUE THREAD

**Issue by MayStepanyan** [tensorflow/tensorflow#57967]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu

### Python version

3․8․10

### Current Behaviour?

When I try to save EfficietNetB0 from tf.keras.applications.efficientnet locally, I receive a TypeError. I got the same error with B1 too, so I assume there's an issue with the whole Efnet Family (and maybe some other models too)

I had no issues with saving ResNet models from tf.keras.applications. 

UPD: There's no such problem in tf 2.9.1 

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
efnet = tf.keras.applications.efficientnet.EfficientNetB0(include_top=False, input_shape=(540,540,3), pooling="avg")
efnet.save("tmp/efnet")
```

### Relevant log output

```shell
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:Found untraced functions such as _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op, _jit_compiled_convolution_op while saving (showing 5 of 115). These functions will not be directly callable after loading.
INFO:tensorflow:Assets written to: tmp/efnet/assets
INFO:tensorflow:Assets written to: tmp/efnet/assets
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mayis/.virtualenvs/tf/lib/python3.8/site-packages/keras/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
TypeError: Unable to serialize [2.0896919 2.1128857 2.1081853] to JSON. Unrecognized type <class 'tensorflow.python.framework.ops.EagerTensor'>.
```
</details>

**Comment by sushreebarsa** [comment]
@gadagashwini I was able to replicate the issue, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/b5728542d0d70a7b1b1c142ee14a7071/57967.ipynb#scrollTo=rl76oVc2-3WM) here. Thank you!

**Comment by gadagashwini** [comment]
Hi @MayStepanyan, You can save the model in H5 format without any issue.
Please take a look at below code.

```
import tensorflow as tf
efnet = tf.keras.applications.efficientnet.EfficientNetB0(include_top=False, input_shape=(540,540,3), pooling="avg")
#efnet.save("tmp/efnet")
efnet.save('my_model.h5')
```

**Output**
```
Downloading data from https://storage.googleapis.com/keras-applications/efficientnetb0_notop.h5
16711680/16705208 [==============================] - 0s 0us/step
16719872/16705208 [==============================] - 0s 0us/step
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
```

**Comment by MayStepanyan** [comment]
@gadagashwini of course I can, but It doesn't solve the problem of not being able to save in tf format

**Comment by SuryanarayanaY** [comment]
Hi @MayStepanyan,

Thanks for highlighting the issue.I have replicated the issue in both TF2.10 and tf-nightly versions.Please refer the [gist](https://colab.research.google.com/gist/SuryanarayanaY/2e8bb76e5fdb2bfb5fd00ddab8fbcb1c/57967-r1.ipynb).

Strange thing is that for this application`tf.keras.applications.efficientnet.EfficientNetB0()` , `model.save('file_path')` is throwing out error where as for Other general model its working fine without error.
One more thing is that the model can be reloaded using `tf.saved_model.load('tmp/efnet') `without any error, where as `tf.keras.models.load_model('tmp/efnet')` throwing error .All the details attached in the gist above.

It seems the issue is related to Keras API.Please post this issue on [keras-team/keras repo](https://github.com/keras-team/keras/issues) with necessary details so that it can be tracked from there

To know more please see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999 .

Thank you!
