### ISSUE TITLE
ValueError: Tensor data is null. Run allocate_tensors() first

### ISSUE THREAD

**Issue by margilt** [tensorflow/tensorflow#57971]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04.5 LTS

### Python version

3.8

### Current Behaviour?

Getting all the weights of a TFLite model as numpy arrays raises `ValueError: Tensor data is null. Run allocate_tensors() first` after getting some of them, even though `allocate_tensors()` is indeed called first.

I expect to get all weights without an error.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

print("TF version:", tf.__version__)

model = tf.keras.models.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1]),
    tf.keras.layers.Dense(units=16, activation='relu'),
    tf.keras.layers.Dense(units=1)
])

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

interpreter = tf.lite.Interpreter(model_content=tflite_model)
interpreter.allocate_tensors()

tensor_details = interpreter.get_tensor_details()
print("Found", len(tensor_details), "tensors:")
for tensor in tensor_details:
    print(f"Tensor {tensor['index']}: {tensor['name']}")
    numpy_tensor = interpreter.get_tensor(tensor["index"])
    print("numpy shape:", numpy_tensor.shape)
```

### Relevant log output

```shell
# python test_tflite_bug.py 
2022-09-30 18:48:49.190440: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
TF version: 2.10.0
2022-09-30 18:48:50.700174: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-09-30 18:48:51.386990: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:362] Ignored output_format.
2022-09-30 18:48:51.387051: W tensorflow/compiler/mlir/lite/python/tf_tfl_flatbuffer_helpers.cc:365] Ignored drop_control_dependency.
2022-09-30 18:48:51.387815: I tensorflow/cc/saved_model/reader.cc:45] Reading SavedModel from: /tmp/tmp9zntcxg8
2022-09-30 18:48:51.388897: I tensorflow/cc/saved_model/reader.cc:89] Reading meta graph with tags { serve }
2022-09-30 18:48:51.388941: I tensorflow/cc/saved_model/reader.cc:130] Reading SavedModel debug info (if present) from: /tmp/tmp9zntcxg8
2022-09-30 18:48:51.391959: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:354] MLIR V1 optimization pass is not enabled
2022-09-30 18:48:51.393032: I tensorflow/cc/saved_model/loader.cc:229] Restoring SavedModel bundle.
2022-09-30 18:48:51.409210: I tensorflow/cc/saved_model/loader.cc:213] Running initialization op on SavedModel bundle at path: /tmp/tmp9zntcxg8
2022-09-30 18:48:51.415109: I tensorflow/cc/saved_model/loader.cc:305] SavedModel load for tags { serve }; Status: success: OK. Took 27301 microseconds.
2022-09-30 18:48:51.428541: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:268] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Found 7 tensors:
Tensor 0: serving_default_dense_input:0
numpy shape: (1, 1)
Tensor 1: sequential/dense/MatMul1
numpy shape: (1, 1)
Tensor 2: sequential/dense_1/MatMul
numpy shape: (16, 1)
Tensor 3: sequential/dense_2/MatMul
numpy shape: (1, 16)
Tensor 4: sequential/dense/MatMul2
Traceback (most recent call last):
  File "test_tflite_bug.py", line 23, in <module>
    numpy_tensor = interpreter.get_tensor(tensor["index"])
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/lite/python/interpreter.py", line 852, in get_tensor
    return self._interpreter.GetTensor(tensor_index, subgraph_index)
ValueError: Tensor data is null. Run allocate_tensors() first
```
</details>

**Comment by mohantym** [comment]
Hi @margilt !
To get inference from a TFlite model, We normally pass a Tensor at input[index] and get the output values at output[index] after invoking the interpreter. 

I think you were trying to output values for each of 7 layers in the lite model but you forgot to input a data and invoke. 

Attached resolved[ gist](https://colab.sandbox.google.com/gist/mohantym/e97f3ad00de31bd413b80526bca14468/git_57971.ipynb) for reference.

Thank you!

**Comment by margilt** [comment]
Hi @mohantym ! I really appreciate you taking the time to answer.

Actually what I'm trying to accomplish with the posted code is not to run inference, but to gather or log all the weights of some particular TFLite model (ideally as numpy arrays). I have actually been using a similar code with TF 2.4.3 using several more complex TFLite models and it works.

I recently tested my example code with TF 2.4.3, 2.5.3, 2.6.5, and 2.7.4: they all worked. It is from TF 2.8 that it stops working for me.

For reference, this is what I get with TF 2.7.4:

```
Found 7 tensors:
Tensor 0: serving_default_dense_input:0
numpy shape: (1, 1)
Tensor 1: sequential/dense/MatMul
numpy shape: (1, 1)
Tensor 2: sequential/dense_1/MatMul
numpy shape: (16, 1)
Tensor 3: sequential/dense_2/MatMul
numpy shape: (1, 16)
Tensor 4: sequential/dense/MatMul1
numpy shape: (1, 1)
Tensor 5: sequential/dense/BiasAdd;sequential/dense_1/MatMul;sequential/dense_1/Relu;sequential/dense_1/BiasAdd
numpy shape: (1, 16)
Tensor 6: StatefulPartitionedCall:0
numpy shape: (1, 1)
```

Thank you!

**Comment by mohantym** [comment]
@margilt !
Yeah! it did not replicate till 2.7 and started replicating 2.8 onwards as you pointed out.

**Comment by RostakaGmfun** [comment]
Hi, are there any updates on this issue?

**Comment by iantimmis** [comment]
Please fix this

**Comment by pkgoogle** [comment]
I am able to replicate in [nightly](https://colab.sandbox.google.com/gist/pkgoogle/e6b15c93436480c2ede61e68f2f72c81/git_57971.ipynb) and [2.14](https://colab.sandbox.google.com/gist/pkgoogle/4a0dda3b0bf663714f088e190355a099/git_57971.ipynb)

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

**Comment by pedrofrodenas** [comment]
You should load the tensorflow.lite model using:
`interpreter = tf.lite.Interpreter(model_path=tflite_model_path, experimental_preserve_all_tensors=True)`

In order to load all layers weights, there is some layers like ZeroPadding that are not initialized if this flag is not provided.

According to tensorflow.lite documentation: 

experimental_preserve_all_tensors : If true, then intermediate tensors used during computation are preserved for inspection, and if the passed op resolver type is AUTO or BUILTIN, the type will be changed to BUILTIN_WITHOUT_DEFAULT_DELEGATES so that no Tensorflow Lite default delegates are applied. If false, getting intermediate tensors could result in undefined values or None, especially when the graph is successfully modified by the Tensorflow Lite default delegate. 

https://www.tensorflow.org/api_docs/python/tf/lite/Interpreter
