### ISSUE TITLE
Update the Android NDK to r25b LTS

### ISSUE THREAD

**Issue by EwoutH** [tensorflow/tensorflow#57970]
Currently the Android build of TensorFlow and TensorFlow Lite use an older NDK, either 19 or 21. The latest LTS release of the [Android NDK](https://developer.android.com/ndk) is r25b (the exact version is currently `25.1.8937393`), and [supports](https://github.com/android/ndk/wiki/Changelog-r25) the latest features and compilers (LLVM 14). 

See earlier NDK updates:

- https://github.com/tensorflow/tensorflow/commit/63e7c149d7817edb63adc085c9650e1659f3b699 Update TFLite to use Android NDK r18b
- https://github.com/tensorflow/tensorflow/commit/60bbb7c240580e79ad157e41c7c8058147e5085d Update the TFLite Android Dockerfile to use NDK r19c
- https://github.com/tensorflow/tensorflow/commit/1a0b21e16b08ab0bb1c15f9b5ec040bfbdee2685 Update NDK version to r19c
- https://github.com/tensorflow/tensorflow/commit/f4a65d74eb49eace09483df48b4ce2d94b6b354d [tf.lite] Update stale doc reference to recommended NDK version
- https://github.com/tensorflow/tensorflow/pull/34419

**Comment by mohantym** [comment]
@EwoutH !
Could you share your pointers on the concerned PR #59422 .
Thank you!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
