### ISSUE TITLE
Problems Spotted in Curl.BUILD

### ISSUE THREAD

**Issue by cpsauer** [tensorflow/tensorflow#58018]
Hello, wonderful TensorFlow team!

I happened to be looking at your [BUILD file for CURL](https://github.com/tensorflow/tensorflow/blame/master/third_party/curl.BUILD), since I was looking to build curl with bazel myself. (I'm not currently a TensorFlow user.) Along the way, I noticed some issues that might cause problems. I figured you all might want a heads up, so that's what this is.

The first thing that jumped out is that it hardcodes the SIZEOF defines to 8 for various sizes, which is gonna break on 32-bit systems. (Older Android, iOS, etc.) See `#  define SIZEOF_SIZE_T 8`. The defines for long, size_t, and time_t seem to be depended on fairly heavily from the code, so I'd be worried about memory errors.

More minorly, it looks like frameworks are missing from iOS (and there are maybe some easier and more compact ways of expressing that code). And there are just more generally some ways I think the code could probably be simplified. Like you could skip the genrule and get bash-free Windows compatibility and just use local_defines. Or I'm finding that globs work just fine for getting source and headers, rather than maintaining a constantly changing list. Finally, some things are potentially problematic, but unused in libcurl, like HAVE_FORK on iOS. I'm sure there are more things I missed, but that's a quick list of what I saw.

Thanks for reading!
Chris
(ex-Googler)

P.S. I'm writing a less problematic BUILD file to replace it. LMK if you'd be interested in collaborating!

**Comment by mohantym** [comment]
Hi @cpsauer !
Thanks for sharing those observations. Feel free to raise a PR from your end

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by mihaimaruseac** [comment]
Hello,

I would be happy to review PRs here, can you please tag me?

**Comment by cpsauer** [comment]
Hey! I ended up just spinning up a new set of BUILD rules for curl over at https://github.com/hedronvision/bazel-make-cc-https-easy. The goal was to have a place where we can all collaborate on rules for making HTTPS requests from C++, since the status quo is that people just keep copy pasting this problematic file.

It also provides a libcurl wrapper called CPR that provides a delightful C++ interface. You can still use libcurl directly, but libcpr might also be quite useful to you guys!

Anyway, you're welcome to use it! Currently works on Android, iOS, macOS (and the other Apple OSs). And I honestly bet that adding Windows/Linux support to it would be easier than incrementally updating this to the latest curl--if you'd be open to contribute or joining forces.

Cheers!
Chris

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
