### ISSUE TITLE
Tensorflow CUDA A100 compatibility issue

### ISSUE THREAD

**Issue by Debby123** [tensorflow/tensorflow#58026]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

binary

### Tensorflow Version

tensorflow-gpu==1.12.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 16.04

### Python version

3.7

### GPU model and memory

Nvidia A100

### Current Behaviour?

```shell
The compatibility table given in the tensorflow site does not contain specific minor versions for cuda and cuDNN. However, if the specific versions are not met, there is an compatibility error when I try to use tensorflow. For example for, tensorflow-gpu==1.12.0 and cuda==9.0, the compatible cuDNN version is 7.1.4 and if I have A100, tensorflow is not compatible. I can use them on a V100 GPU but not on A100 GPU.
```

### Standalone code to reproduce the issue

```shell
pip install --upgrade pip
pip install tensorflow-gpu==1.12.0
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @Debby123 !
1.x versions are not supported anymore. 
Could you test latest instructions from latest [build/install document](https://www.tensorflow.org/install/pip) (It suggests Installing necessary Cuda toolkits according to hardware according to conda channels now  instead of setting path manually).

Please check the tested the configs if you want to build from source.

Thank you!

**Comment by Debby123** [comment]
Hi @mohantym, 
I was trying to reproduce some research code that uses tf 1.x version. Although I tried using the latest build, there were code incompatibilities.  Anyway, I reckon I will have to rewrite the code as per the latest builds. 
Thank you for looking into this!
