### ISSUE TITLE
CosineSimilarity outputs result smaller than -1

### ISSUE THREAD

**Issue by maybeLee** [tensorflow/tensorflow#58031]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.11.0-dev20221009

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 20.04

### Python version

3.7.14

### Bazel version

N/A

### GCC/Compiler version

N/A

### CUDA/cuDNN version

N/A

### GPU model and memory

N/A

### Current Behaviour?

```shell
Following the documentation: https://www.tensorflow.org/api_docs/python/tf/keras/losses/CosineSimilarity, the output of `tf.keras.losses.CosineSimilarity` should be within the range: [-1, 1]. However, when I calculate the cosine similarity loss between two arrays: `[[0,2,3]]` and `[[0,2,3]]`, it outputs `-1.0000001`.

I notice that this issue appeals when the array contains `0.`. I guess it is caused by the computation underflow, but I still don't know why a value smaller than -1 would be outputted. Maybe you can try to do clamping after the computation of cosine similarity?
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
y_true = [[0.,2.,3.]]
y_pred = [[0.,2.,3.]]
cosine_loss = tf.keras.losses.CosineSimilarity()
res = cosine_loss(y_true, y_pred).numpy()
print("tensorflow: ", res)
```

### Relevant log output

```shell
tensorflow:  -1.0000001
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.8, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7a5785c485c46591ad7e6c600a6844e8/untitled657.ipynb).

**Comment by sachinprasadhs** [comment]
This has to be the edge case scenario. It could be due to the underflow or due to the delta value to avoid the NaN outcome. 
But if the array contains zero anything apart from first position, the outcome is limited between [-1,1].
This small difference of 1e-7 can be ignored. 
If you still feel this issue needs to be addressed, could you please open the issue in  https://github.com/keras-team/keras/issues
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999
Thank you!

**Comment by maybeLee** [comment]
Thanks @sachinprasadhs 
I have created an issue in Keras repository: https://github.com/keras-team/keras/issues/17138. I have closed this thread.
