### ISSUE TITLE
PyLint incorrectly identifies `tf.concat` function signature

### ISSUE THREAD

**Issue by dverheijden** [tensorflow/tensorflow#58038]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

No

### Python version

3.9

### Current Behaviour?

When running [`pylint -E check.py`](https://pylint.pycqa.org/en/latest/index.html) on the code snippet below, the following errors are raised:
```shell
check.py:18:10: E1123: Unexpected keyword argument 'axis' in function call (unexpected-keyword-arg)
check.py:18:10: E1120: No value for argument 'values' in function call (no-value-for-parameter)
```
which is unexpected, since the usage is correct as per [the documentation](https://www.tensorflow.org/api_docs/python/tf/concat). The version of PyLint that I'm currently using is the latest: `2.16.0`.

I've raised [a similar issue](https://github.com/tensorflow/tensorflow/issues/43038) in the past, which has been successfully resolved. Indeed, when running `pylint` on the snippet (as also indicated), doesn't raise this issue anymore.
```


### Standalone code to reproduce the issue

```shell
import tensorflow as tf


def previously_not_working():
    """This failed before, but it works now, see also https://github.com/tensorflow/tensorflow/issues/43038"""
    tensor = tf.random.uniform((2, 4), minval=0, maxval=256)
    tf.split(tensor, num_or_size_splits=2, axis=-1)


def failing():
    tensor = tf.random.uniform((2, 4), minval=0, maxval=256)
    print(tf.concat([tensor, tensor], axis=1).shape)
```

### Relevant log output

```shell
check.py:18:10: E1123: Unexpected keyword argument 'axis' in function call (unexpected-keyword-arg)
check.py:18:10: E1120: No value for argument 'values' in function call (no-value-for-parameter)
```
</details>

**Comment by dverheijden** [comment]
I did some additional digging: When using the same pylint version as is used in the TensorFlow CI: [`2.7.4`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/ci_build/install/install_pip_packages.sh#L82), the snippet that is now working (the one listed in the related issue), actually fails again. I'm not sure when this broke again.

**Comment by mohantym** [comment]
Hi @sachinprasadhs !
Could you look at this issue. Attached [gist](https://colab.sandbox.google.com/gist/mohantym/7aa111633b530c25748852f7dd73cb55/git_58038.ipynb#scrollTo=k7bMWXXXtka0) for reference.
Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
