### ISSUE TITLE
I encountered a problem in upgrading the code from 1. X to 2.0.

### ISSUE THREAD

**Issue by Zero1366166516** [tensorflow/tensorflow#58100]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

2.1.0

### Custom Code

No

### OS Platform and Distribution

windows RS 12

### Python version

version 3.8

### Current Behaviour?

```shell
A bug happened!
I'm upgrading the code
reg=tf.contrib.layers.apply_regulation（tf.contlib.layers.l2_regularizer（scale），tf.trainable_variables（））
tf.contrib.layers.l2_regularizer(scale)，Rewrite as tf.keras.regularizers.l2(scale)

tf.contrib.layers.apply_regulation，Don't know how to rewrite。
```

### Standalone code to reproduce the issue

```shell
reg=tf.contrib.layers.apply_regulation（tf.contlib.layers.l2_regularizer（scale），tf.trainable_variables（））
I rewrote it as
reg = tf.keras.layers(tf.keras.regularizers.l2(scale),tf.trainable_variables())
```

### Relevant log output

```shell
Traceback (most recent call last):
  File "C:/Users/Administrator/PycharmProjects/pythonProject1/stock/LSTM.py", line 240, in <module>
    two_up("2019012","zhong")
  File "C:/Users/Administrator/PycharmProjects/pythonProject1/stock/LSTM.py", line 180, in two_up
    reg = tf.keras(tf.keras.regularizers.l2(scale),tf.trainable_variables())
TypeError: 'LazyLoader' object is not callable
```
</details>

**Comment by tilakrayal** [comment]
@Zero1366166516,
In Tensorflow 2.x, keras training loops help us to apply regularization, activation losses automatically, no need to call explicit apply_regularization methods. Kindly please take a look at official [Tensorflow doc](https://www.tensorflow.org/guide/migrate#use_keras_training_loops) for the reference and please try to use **tf.keras.regularizers.L1L2** in TF v2.x. 

Also We recommend trying to use the latest tensorflow stable version where there is a high possibility that this was fixed with later TF versions. Thank you!
