### ISSUE TITLE
Check Fail in AvgPool3DGrad

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58106]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.11.0-dev20221013

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A check-fail can be triggered in AvgPool3DGrad, which leads to a crash.
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        with tf.device("GPU:0"):
            ksize_0 = 1
            ksize_1 = 1
            ksize_2 = 32
            ksize_3 = 32
            ksize_4 = 128
            ksize = [ksize_0, ksize_1, ksize_2, ksize_3, ksize_4, ]
            strides_0 = 1
            strides_1 = 1
            strides_2 = 128
            strides_3 = 128
            strides_4 = 128
            strides = [strides_0, strides_1, strides_2, strides_3, strides_4, ]
            padding = "VALID"
            data_format = "NCDHW"
            orig_input_shape_0 = 111
            orig_input_shape_1 = 24
            orig_input_shape_2 = 43
            orig_input_shape_3 = 77
            orig_input_shape_4 = 89
            orig_input_shape = [orig_input_shape_0, orig_input_shape_1, orig_input_shape_2, orig_input_shape_3, orig_input_shape_4, ]
            grad = tf.random.uniform([0, 4, 1, 1, 1], dtype=tf.float32)
            res = tf.raw_ops.AvgPool3DGrad(
                ksize=ksize,
                strides=strides,
                padding=padding,
                data_format=data_format,
                orig_input_shape=orig_input_shape,
                grad=grad,
            )
    except:
        pass
```

### Relevant log output

```shell
Check failed: cudnnSetTensorNdDescriptor(handle_.get(), elem_type, nd, dims.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)batch_descriptor: {count: 111 feature_map_count: 24 spatial: 1 1 0  value_min: 0.000000 value_max: 0.000000 layout: BatchDepthYX}
Aborted (core dumped)
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/020c31012d08472342e250c4aeb44c91/untitled19.ipynb) for reference.
Thank you!

**Comment by sachinprasadhs** [comment]
tf.raw_ops are basically designed to be consumed by downstream library users, not end users.
Usually, these APIs are less strict in terms of validation etc., which is fine since mainly library writers are supposed to use these symbols.
If available, please prefer high level API for general use case scenarios.
Refer this [RFC](https://github.com/tensorflow/community/blob/master/rfcs/20181225-tf-raw-ops.md#design-proposal) for more details. Thanks!

**Comment by mihaimaruseac** [comment]
While these are internal APIs, the check failure could lead to denial of service. In the past this used to be considered a vulnerability, but since the impact is bounded and preventable, now the policy is for these to be files as issues and resolved whenever someone from community wants to pick them up (they're very good first issues). Please don't auto-close these!

**Comment by maxcopeland** [comment]
Hi @mihaimaruseac -- ok, if I work on this?

**Comment by mihaimaruseac** [comment]
Sure, feel free. It's labeled as `good first issue`, anyone can pick it up and work on it

**Comment by maxcopeland** [comment]
Attaching for reference: https://github.com/tensorflow/tensorflow/security/advisories/GHSA-wxjj-cgcx-r3vq

**Comment by maxcopeland** [comment]
Appears that the commit referenced in the sec advisory avoids the check fail in their listed test case, but not for the one on this issue.

**Comment by yongtang** [comment]
@shijy16 Can you try the latest nightly again? I believe this issue has been fixed recently.
