### ISSUE TITLE
Troubles with set of imports

### ISSUE THREAD

**Issue by RinnetenseiQ** [tensorflow/tensorflow#58111]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.2

### Custom Code

No

### OS Platform and Distribution

Collab

### Python version

3.7.14

### Current Behaviour?

```shell
Some of the functionality is incompatible when using followed imports style:
- from tensorflow.keras... import ...
- from tensorflow.python.keras... import ...

When I want to import without "python" suffix some optimizer classes there is Value error while model compilation
```

### Standalone code to reproduce the issue

```shell
from tensorflow.keras.optimizers import Adam
from tensorflow.python.keras.optimizers import Adam

###########################
model.compile(optimizer=Adam(learning_rate=0.001), loss="mean_squared_error")
```

### Relevant log output

```shell
ImportError: cannot import name 'Adam' from 'tensorflow.python.keras.optimizers' (/usr/local/lib/python3.7/dist-packages/tensorflow/python/keras/optimizers.py)

#######################################

ValueError: Could not interpret optimizer identifier: <keras.optimizers.optimizer_v2.adam.Adam object at 0x7f97d3696c90>
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using  Tf v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/c28ace9557c79c9879f73ea59389cdd0/58111.ipynb) for reference.
Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @RinnetenseiQ ,
Sorry for delayed response.Please find the release note from [here](https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0-rc2) regarding the tensorflow.python.keras.optimizers path.

`tensorflow/python/keras code is a legacy copy of Keras since 2.7 release, and will be deleted in 2.12 release. Please remove any import of tensorflow.python.keras and use public API with from tensorflow import keras or import tensorflow as tf; tf.keras.
`

Thankyou !

**Comment by RinnetenseiQ** [comment]
> Hi @RinnetenseiQ , Sorry for delayed response.Please find the release note from [here](https://github.com/tensorflow/tensorflow/releases/tag/v2.11.0-rc2) regarding the tensorflow.python.keras.optimizers path.
> 
> `tensorflow/python/keras code is a legacy copy of Keras since 2.7 release, and will be deleted in 2.12 release. Please remove any import of tensorflow.python.keras and use public API with from tensorflow import keras or import tensorflow as tf; tf.keras. `
> 
> Thankyou !

I am using 2.10 version. Is your answer true for this version?
If yes, can you change it in oficial docs? https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam

**Comment by SuryanarayanaY** [comment]
Hi @RinnetenseiQ ,

Iam trying to say please use the import statement like  `from tensorflow.keras import xxxx` 
instead of `tensorflow.python.keras import xxxx`.
The https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/Adam also uses tf.keras.optimizers.Adam and 
no `python name space` here in import statement.

Thankyou !
