### ISSUE TITLE
Tensorflow does not build with incompatible_disallow_empty_glob

### ISSUE THREAD

**Issue by limdor** [tensorflow/tensorflow#58155]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

master

### Custom Code

No

### Bazel version

master + --incompatible_disallow_empty_glob

### Current Behaviour?

```shell
Tensorflow does not build with incompatible_disallow_empty_glob

https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1301#0183e377-b3bf-4648-8470-e7a0d37f4a04
```

### Standalone code to reproduce the issue

```shell
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1301#0183e377-b3bf-4648-8470-e7a0d37f4a04
```

### Relevant log output

```shell
https://buildkite.com/bazel/bazelisk-plus-incompatible-flags/builds/1301#0183e377-b3bf-4648-8470-e7a0d37f4a04
```
</details>

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
