### ISSUE TITLE
IOU3d and IOU3d pairwise

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#58166]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

master

### Custom Code

Yes

### Current Behaviour?

We are going to introduce c++ custom ops for pairwise IOU3D in Keras-cv with:

https://github.com/keras-team/keras-cv/pull/890

Analyzing also what we have in [TF 3d](https://github.com/google-research/google-research/blob/master/tf3d/object_detection/box_utils/box_ops.py#L26-L69) we are still relying on [numpy helper routines](https://github.com/google-research/google-research/blob/master/tf3d/object_detection/box_utils/np_box_ops.py)

Same thing for Pytorch 3d that has [c++/CUDA cusotm op](https://github.com/facebookresearch/pytorch3d/blob/main/docs/notes/iou3d.md)

I want to try to understand what kind of routines we could contribute here to support these new ops and to analyze if there is any limit, down to the stack, in the case we need to implement an HLO kernel to cover the XLA jit compilation.

### Standalone code to reproduce the issue

```shell
It is a FR.
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The related PR's which were raised have been merged. Please take a look at the referenced PR's.
https://github.com/keras-team/keras-cv/pull/890
https://github.com/keras-team/keras-cv/pull/1292

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
