### ISSUE TITLE
Crash due to check-fail in DenseBincount

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58178]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A check-fail can be triggered in DenseBincount, which leads to a crash
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        with tf.device("GPU:0"):
            binary_output = False
            input = tf.saturate_cast(tf.random.uniform([0, 5], minval=0, maxval=64, dtype=tf.int64), dtype=tf.int64)
            size = 340
            weights = tf.random.uniform([13, 0], dtype=tf.float32)
            res = tf.raw_ops.DenseBincount(
                binary_output=binary_output,
                input=input,
                size=size,
                weights=weights,
            )
    except:
        pass
```

### Relevant log output

```shell
F ./tensorflow/core/util/gpu_launch_config.h:129] Check failed: work_element_count > 0 (0 vs. 0)
Aborted (core dumped)
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa
I was able to reproduce the issue on Colab using TF v2.10 in GPU and it works on CPU. Please find the gist [CPU](https://colab.research.google.com/gist/tiruk007/81c95c1cb68a641dad5a84c7c370e21e/58178.ipynb) and [GPU](https://colab.research.google.com/gist/tiruk007/1afd2a728b0e1c4765084995cb431a84/58178gpu.ipynb) for reference.
Thank you!

**Comment by sachinprasadhs** [comment]
tf.raw_ops are basically designed to be consumed by downstream library users, not end users.
Usually, these APIs are less strict in terms of validation etc., which is fine since mainly library writers are supposed to use these symbols.
If available, please prefer high level API for general use case scenarios.
Refer this [RFC](https://github.com/tensorflow/community/blob/master/rfcs/20181225-tf-raw-ops.md#design-proposal) for more details. Thanks!

**Comment by mihaimaruseac** [comment]
While these are internal APIs, the check failure could lead to denial of service. In the past this used to be considered a vulnerability, but since the impact is bounded and preventable, now the policy is for these to be files as issues and resolved whenever someone from community wants to pick them up (they're very good first issues). Please don't auto-close these!

**Comment by Tejas-Sands** [comment]
The crashed session is running on TPU , does this mean that there is some problem with colab?

**Comment by dgeorgi** [comment]
I would like to give this issue a shot, what file can i find the buggy code in?

**Comment by madt2709** [comment]
The issue no longer arises when using tf-nightly. It's probably safe to close this issue as well
