### ISSUE TITLE
Check Fail Can Be Triggered in BlockLSTM

### ISSUE THREAD

**Issue by shijy16** [tensorflow/tensorflow#58175]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

tf 2.9 and 2.12.0-dev20221018

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.8

### CUDA/cuDNN version

CUDA 11.5

### Current Behaviour?

```shell
A check-fail can be triggered.
```

### Standalone code to reproduce the issue

```shell
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
import numpy as np
print(tf.__version__)
for _ in range(20):
    try:
        with tf.device("GPU:0"):
            forget_bias = -121.22699269620765
            cell_clip = -106.82307555235684
            use_peephole = False
            seq_len_max = tf.saturate_cast(tf.random.uniform([13, 11, 0], minval=0, maxval=64, dtype=tf.int64), dtype=tf.int64)
            x = tf.random.uniform([1, 3, 15], dtype=tf.float32)
            cs_prev = tf.random.uniform([3, 0], dtype=tf.float32)
            h_prev = tf.random.uniform([3, 0], dtype=tf.float32)
            w = tf.random.uniform([15, 0], dtype=tf.float32)
            wci = tf.random.uniform([0], dtype=tf.float32)
            wcf = tf.random.uniform([0], dtype=tf.float32)
            wco = tf.random.uniform([0], dtype=tf.float32)
            b = tf.random.uniform([0], dtype=tf.float32)
            res = tf.raw_ops.BlockLSTM(
                forget_bias=forget_bias,
                cell_clip=cell_clip,
                use_peephole=use_peephole,
                seq_len_max=seq_len_max,
                x=x,
                cs_prev=cs_prev,
                h_prev=h_prev,
                w=w,
                wci=wci,
                wcf=wcf,
                wco=wco,
                b=b,
            )
    except:
        pass
```

### Relevant log output

```shell
2022-10-20 10:45:56.646548: F tensorflow/core/framework/tensor.cc:733] Check failed: 1 == NumElements() (1 vs. 0)Must have a one element tensor
Aborted (core dumped)
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.10 in CPU and GPU. Please find the gist [CPU](https://colab.research.google.com/gist/tiruk007/e392955bc60e1e515dcac0b63cd2bd0d/58175cpu.ipynb) and [GPU](https://colab.research.google.com/gist/tiruk007/975a17c498bc0f834698f3d27df2716c/58175gpu.ipynb) for reference.
Thank you!

**Comment by sachinprasadhs** [comment]
tf.raw_ops are basically designed to be consumed by downstream library users, not end users.
Usually, these APIs are less strict in terms of validation etc., which is fine since mainly library writers are supposed to use these symbols.
If available, please prefer high level API for general use case scenarios.
Refer this [RFC](https://github.com/tensorflow/community/blob/master/rfcs/20181225-tf-raw-ops.md#design-proposal) for more details. Thanks!

**Comment by mihaimaruseac** [comment]
While these are internal APIs, the check failure could lead to denial of service. In the past this used to be considered a vulnerability, but since the impact is bounded and preventable, now the policy is for these to be files as issues and resolved whenever someone from community wants to pick them up (they're very good first issues). Please don't auto-close these!

**Comment by yongtang** [comment]
Created a PR #59202.
