### ISSUE TITLE
TensorRT converted models are 2-3 times slower in TF 2.10.0 in comparison to TF 2.9.2 

### ISSUE THREAD

**Issue by apivovarov** [tensorflow/tensorflow#58248]
### Issue Type

Performance

### Source

binary pypi

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 18.04

### Python version

3.7

### CUDA/cuDNN version

11.2.2 / 8.3.2.44

### TensorRT version

7.2.3

### GPU model and memory

Nvidia Tesla T4 16GB (aws g4dn.2xlarge)

### Current Behaviour?

Model: imagenet_mobilenet_v2_100_224_classification from tfhub.
I converted and run the model using TF-TRT 2.9.2 and 2.10.0. 

TF-TRT 2.10.0 is 2-3x times slower than TF-TRT 2.9.2. 

Results for imagenet_mobilenet_v2 are below

```
# imagenet_mobilenet_v2

# TF-TRT 2.9.2
P50 (ms): 0.87

# TF-TRT 2.10.0
P50 (ms): 1.87  (2.15x times slower)
```

Similar performance issue exist for other models such as inception_v3 and resnet_50 - 2-3x times slower in TF-TRT 2.10.0

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
from tensorflow.python.compiler.tensorrt import trt_convert as trt
import time
import numpy as np

m=tf.keras.applications.MobileNetV2()
tf.saved_model.save(m, "saved_model")

precision_mode=trt.TrtPrecisionMode.FP32
conversion_params = trt.TrtConversionParams(precision_mode=precision_mode)
converter = trt.TrtGraphConverterV2(
    input_saved_model_dir="saved_model",
    conversion_params=conversion_params)
converter.convert()
converter.save("saved_model_trt_32")

m=tf.saved_model.load("saved_model_trt_32")
f=m.signatures['serving_default']
x=tf.random.uniform(shape=(1,224,224,3), dtype="float32")

# Warmup
N = 10
for i in range(N):
  y = f(x)

N = 100
TTT=[]
for i in range(N):
  t1 = time.time()
  y = f(x)
  t2 = time.time()
  TTT.append(t2-t1)

p50_time = np.percentile(TTT, 50) * 1000
print("P50 (ms):", p50_time)
```

**Comment by apivovarov** [comment]
@bixia1 , @sushreebarsa - just want to check if you were able to reproduce the issue

**Comment by apivovarov** [comment]
I found that significant performance degradation in TF-TRT was caused by commit [612a531c9bc729329470e778dfc014d2d978e587](https://github.com/tensorflow/tensorflow/commit/612a531c9bc729329470e778dfc014d2d978e587) - **Excises VirtualPlacer from layout optimizer transposer.** 
@jkr26 , @Kh4L , @tfeher , @christopherbate , @drivanov , @DEKHTIARJonathan , @kaixih , @jblespiau

**Comment by sushreebarsa** [comment]
@apivovarov I tried to replicate the issue on colab using tf-nightly, and faced `RuntimeError: Tensorflow has not been built with TensorRT support`. Please find the gist [here](https://colab.research.google.com/gist/sushreebarsa/c6be14b1375c204f48de99e30c521d04/58248.ipynb) and confirm the same?
Thank you!

**Comment by apivovarov** [comment]
Hi @sushreebarsa,
Below are Colab notebooks to run TF-TRT:
- [TF2.9.3-TRT7.2.3.ipynb](https://colab.research.google.com/drive/12RGLy6Pr1yP8EGf0OpvXGAWNGThZlVxv#scrollTo=aS06n_0ye9T6)
- [TF2.11.0-TRT7.2.3.ipynb.ipynb](https://colab.research.google.com/drive/1yEwzlwaHlevknBL_PCB1v7NQKXu8IXuh#scrollTo=BK1R0z-WgM2y)
- [TF-nightly1.12-TRT8.5.ipynb](https://colab.research.google.com/drive/1OTvj0E2qYMZLvrn_Wkos-CWpXjYN4V0Z)

**Comment by jkr26** [comment]
I'll give the context I can recall, though I definitely do not remember all of it distinctly.

I believe the possibility of such a regression was discussed in the original change. The issue as I recall it being: the default placement behavior was, in some sense, "accidentally better" for certain purposes, though I do not recall in what circumstances this was expected to be true. It was, however, quite poor in some others--the benchmark from [TensorFlow-Federated](https://github.com/tensorflow/tensorflow-federated) which yielded the investigation that resulted in this change saw something like a 10X-20X speedup, since the default behavior resulted in data being copied between multiple GPUs while executing, not just a single training loop (so, copying once-per-batch), but while even executing a single forward-backwards pass (so copying multiple times per batch). This benchmark uses internal Google infrastructure, so only runs inside Google and unfortunately I cannot point to it.

The general feeling talking to TF core folks was that the behavior of this virtual placer should not / cannot be relied on downstream, and it did not make particularly strong guarantees about what, precisely, it would do. Further, the code seemed mostly unowned--so there was preference for deleting it.

The regressions we saw in internal Google benchmarks could all be fixed by explicitly annotating the model, which was considered to be 'more correct' than relying on poorly understood behavior of virtual placer, so this was the path that was chosen. I believe there was some feeling that if better placer behavior was needed, it would most properly be implemented in / migrated to 'real placer'. That said, I am no expert on op placement in TF.

Hope this context is useful.

**Comment by sushreebarsa** [comment]
@apivovarov Please refer to the comment above and let us know if that helps?
Thank you!

**Comment by apivovarov** [comment]
@sushreebarsa I do not think the comment gives exact solution to return fast TF-TRT inference back.

It seems that the only working solution which we have now is to revert commit 612a531

**Comment by sushreebarsa** [comment]
@apivovarov Could you please confirm if this issue has been resolved?
Thank you!

**Comment by apivovarov** [comment]
One of the solution is to reverts commit https://github.com/tensorflow/tensorflow/commit/612a531c9bc729329470e778dfc014d2d978e587
I opened PR to revert it https://github.com/tensorflow/tensorflow/pull/59044 one moth ago.
PR is still open. 

The issue still exist in TF 2.10, 2.11 and upcoming 2.12.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The PR which was raised for the revert of the mentioned commit was closed. Please find the PR for the reference.
https://github.com/tensorflow/tensorflow/pull/59044

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
