### ISSUE TITLE
WARNING:tensorflow:Using a while_loop

### ISSUE THREAD

**Issue by Ajay-user** [tensorflow/tensorflow#58296]
tf.__version__ = 2.9.2  

`preprocessing_model = tf.keras.Sequential([
    tf.keras.layers.Rescaling(scale=1.0/255),
    tf.keras.layers.RandomRotation(40),
])`

preprocessing_model(  #pass a single image#  ) -- no warning

preprocessing_model( #image_batch#  ) -- WARNING

`
WARNING:tensorflow:Using a while_loop for converting RngReadAndSkip
WARNING:tensorflow:Using a while_loop for converting Bitcast
WARNING:tensorflow:Using a while_loop for converting Bitcast
WARNING:tensorflow:Using a while_loop for converting StatelessRandomUniformV2
WARNING:tensorflow:Using a while_loop for converting RngReadAndSkip
WARNING:tensorflow:Using a while_loop for converting Bitcast
WARNING:tensorflow:Using a while_loop for converting Bitcast
WARNING:tensorflow:Using a while_loop for converting StatelessRandomUniformV2
WARNING:tensorflow:Using a while_loop for converting ImageProjectiveTransformV3
`
Please see the full code here:
[view the code](https://colab.research.google.com/gist/Ajay-user/cf87fc63d66331ee5e338262be83ca71/warning-tensorflow-using-a-while_loop.ipynb#scrollTo=-6N95-QBLbIz)

I tried the same code in tensorflow version 2.8.3 and there was no warning

**Comment by bhack** [comment]
It is mainly related to:

https://github.com/keras-team/keras-cv/issues/291

https://github.com/tensorflow/tensorflow/issues/55639

Some warnings were suppressed https://github.com/tensorflow/tensorflow/commit/88a263ee53fdfa172c37090ef245ac0668b6200c but it just reduces messages as it was not  going to solve the performance issues.

**Comment by tiruk007** [comment]
@Ajay-user 
I was able to reproduce the issue on Colab using TF v2.10. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/85c8a4cb9942167d149dcb61b3a8139e/58296.ipynb) for reference.
This issue seems to be Keras issue. Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) All issues and PRs related to keras will be addressed in that repo.
To know more see;
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999.

Thank you!

**Comment by bhack** [comment]
@tiruk007 it is not related only to the Keras repo but if you see my mentioned tickets we are already tracking this it in both repos so we could it.

@Ajay-user please comment/subscribe to the mentioned tickets and close this one.

Thanks.

**Comment by Ajay-user** [comment]
@bhack  Thankyou 
@tiruk007  [link](https://github.com/keras-team/keras-cv/issues/291)
