### ISSUE TITLE
Tensorflow on C++ Builder 11.2

### ISSUE THREAD

**Issue by delphianaus** [tensorflow/tensorflow#58298]
Is there any support to use C++ builder 11.2 with tensorflow , when i try to include the lib file it complains no symbols are included.

the command i use to add the library is #pragma comment(lib,"lib\\tensorflow.lib") , or i add to the project it gets greyed out right away , the only include i have is #include "include\tensorflow\c\c_api.h" & just a simple call as a test ->
 { 
    TF_Status *status = NULL;
    status = TF_NewStatus();
}

Running 11.2 Version 28.0.46141.0937 ( Latest version) , project is X64

error when doing full build is (Path before lib removed.) -> [ilink64 Error] Fatal: Archive file 'LIB\TENSORFLOW.LIB' lists no symbols in its dictionary.

**Comment by tiruk007** [comment]
@delphianaus 
Could you please fill the issue [template]( https://github.com/tensorflow/tensorflow/issues/new/choose).
Thank you!

**Comment by delphianaus** [comment]
Is the windows build broken ? i want to build cuda debug and see if i can import the dll into C++ builder.

Bazel - 5.3.1
VC 2022
Branch 2.10 from git hub,
using latest copy of anaconda3 ( Python 3.10)

**Comment by mohantym** [comment]
Hi @delphianaus !
Sorry for the late response. 
Just wanted to let you know  earlier that from 2.11 onwards Windows users has to use Cuda Compute capability either through WSL2/Tensorflow-Direct ML plugin.  

[Ref](https://www.tensorflow.org/install/pip#windows-native).

Thank you!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

TensorFlow with GPU access is supported for WSL2 on Windows 10 19044 or higher. This corresponds to Windows 10 version 21H2, the November 2021 update. You can get the latest update from here: [Download Windows 10](https://www.microsoft.com/software-download/windows10). For instructions, see [Install WSL2](https://docs.microsoft.com/windows/wsl/install) and [NVIDIA’s setup docs](https://docs.nvidia.com/cuda/wsl-user-guide/index.html) for CUDA in WSL.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
