### ISSUE TITLE
https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryFocalCrossentropy contains some information of https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryCrossentropy

### ISSUE THREAD

**Issue by 21564669** [tensorflow/tensorflow#58397]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Source

binary

### Tensorflow Version

2.10

### Custom Code

No

### Current Behaviour?

```shell
A bug happened!

in the link below:
https://www.tensorflow.org/api_docs/python/tf/keras/losses/BinaryFocalCrossentropy
it should have introduced some info about the BinaryFocalCrossentropy, but it put some info of BinaryCrossentropy as below:


Binary cross-entropy loss is often used for binary (0 or 1) classification tasks. The loss function requires the following inputs:

y_true (true label): This is either 0 or 1.
y_pred (predicted value): This is the model's prediction, i.e, a single floating-point value which either represents a logit, (i.e, value in [-inf, inf] when from_logits=True) or a probability (i.e, value in [0., 1.] when from_logits=False).
```

### Standalone code to reproduce the issue

```shell
click on the link above
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@21564669,
Thanks for opening this issue. Development of keras moved to another [repository](https://github.com/keras-team/keras/issues). 
 
 
Could you please post this issue on keras-team/keras [repo](https://github.com/keras-team/keras/issues).
To know more please refer:
https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

Please feel free to close this issue, so that we can track on Keras repo.
Thank you!
