### ISSUE TITLE
How to catch XlaRuntimeError in python

### ISSUE THREAD

**Issue by vinayburugu** [tensorflow/tensorflow#58407]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf2.10

### Custom Code

No

### OS Platform and Distribution

Ubuntu

### Python version

3.9

### Current Behaviour?

```shell
Trying to catch XlaRuntimeError in Python. But the error is not visible and the module that defined this exception is also not visible. We are unable to import the exception.
The presumed module that defined XlaRuntimeError is tensorflow.compiler.xla.xla_client.
```

### Standalone code to reproduce the issue

```shell
import tensorflow.compiler.xla.python.xla_client
```

### Relevant log output

```shell
>>>ModuleNotFoundError: No module named 'tensorflow.compiler.xla.python'
```
</details>

**Comment by bhack** [comment]
I don't think it is exposed currently.
What is your use case?

Jax it is handling it internally:
https://github.com/google/jax/blob/main/jax/_src/stages.py#L191-L204

**Comment by vinayburugu** [comment]
@bhack  Since XLA is common to both Tensorflow and Pytorch, accessing XlaRuntimeError and able to throw / catch will enable me to rethrow relevant message that the exception root cause is within XLA and not the framework.
@mohantym I don't think [1](https://www.tensorflow.org/api_docs/python/tf/xla/experimental/jit_scope) and [2](https://www.tensorflow.org/xla/custom_call#signalling_an_error) would solve my use case.

**Comment by mohantym** [comment]
Ok @vinayburugu !
Thanks for the update. 

@sushreebarsa !
Could you look at this issue.

Thank you!

**Comment by bhack** [comment]
>  Since XLA is common to both Tensorflow and Pytorch, accessing XlaRuntimeError and able to throw / catch will enable me to rethrow relevant message that the exception root cause is within XLA and not the framework.

I think it was exposed in Jax with https://github.com/google/jax/pull/10676.

Is this really a TF related request? If not XLA has a new standalone repository at https://github.com/openxla/xla.

**Comment by Lokiiiiii** [comment]
@bhack Though the exception is defined in xla, it seems to be up to every front-end framework to expose the exceptions as you pointed out. The request here is specific to TensorFlow's front-end. 

@vinayburugu You should file an issue with XLA to make this contract between compiler and front-end simpler. If XLA standardizes its exception definitions under one easy to import module, front-ends can expose those with something like

```python
from xla.exceptions import *
```

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Have you got the chance to have a look at the jax.errors.JaxRuntimeError which is alias of XlaRuntimeError
https://jax.readthedocs.io/en/latest/errors.html#jax.errors.JaxRuntimeError

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
