### ISSUE TITLE
Feature Request - Tensorflow Docker Extension

### ISSUE THREAD

**Issue by amyb12345** [tensorflow/tensorflow#58421]
### Describe the problem
Feature request: Hi, I am the product manager for Docker Extensions. We've been getting some requests from Docker users to see a Tensorflow Docker Extension. The most common reason for this request is that the user does not want to install Tensorflow locally. I am opening this feature request so that the larger Tensorflow community can determine how helpful this would be and decide if it should be built. 

### Source code / logs
If it is decided that this Docker Extension should be built, documentation is available [here](https://docs.docker.com/desktop/extensions-sdk/) on how to build a Docker Extension.  If assistance or support is needed, please reach out as we are happy to help!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
