### ISSUE TITLE
Implementing SVD rank threshold?

### ISSUE THREAD

**Issue by AidanGG** [tensorflow/tensorflow#5842]
It might be useful to use Eigen SVD's `Eigen::BDCSVD::setThreshold` function in order to cull the effectively zero singular values, perhaps by introducing a new parameter to TensorFlow's SVD so that `tf.svd(tensor, compute_uv=True, full_matrices=False, thresholded=True, name=None)` uses
- the default Eigen threshold for `thresholded=True`
- the full P = min(M, N) singular values for `thresholded=False`
- whatever threshold is specified with a float, such as `thresholded=1e-7`

I can get started on a PR if this is something that might be useful.

**Comment by aselle** [comment]
@rmlarsen, do you think this would be good. It doesn't look like NumPy has anything equivalent. I think if you are willing to accept this, we should invite @AidanGG to contribute it.

**Comment by rmlarsen** [comment]
@AidanGG The setThreshold method in Eigen does not affect the main SVD computation itself. Rather, it is mostly a convenient way to post-filter the SVD when using it to determine numerical rank or using it for applying a pseudo-inverse via the solve() method.

https://bitbucket.org/eigen/eigen/src/41ef39502e7e9aab985bb5b51894d1f87106b67e/Eigen/src/SVD/SVDBase.h?at=default&fileviewer=file-view-default#SVDBase.h-143

As such, I would prefer that such filtering be implemented in TensorFlow, rather than relying on this feature in the underlying Eigen C++ library. 

Another concern is that such thresholding is not widely supported by other high performance SVD libraries. Should we decide to replace the Eigen "backend" for this op, it would preferable to have the thresholding logic in Tensorflow itself.

It would be awesome if you would be interested in contributing functions that, e.g., apply the pseudo-inverse or filter the SVD based on a threshold.

**Comment by AidanGG** [comment]
Hi @rmlarsen, I have been using
```
rank = tf.shape(tf.where(tf.greater_equal(s, np.finfo(dtype.real_dtype.as_numpy_dtype).eps * s[0] * tf.cast(tf.size(s), dtype.real_dtype))))[0]
```
and slicing `U`, `s` and  `V` by this `rank`. This works well enough for my purpose.
