### ISSUE TITLE
`tf.random.stateless_categorical` produces inconsistent results on CPU/GPU

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#58445]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.2

### Custom Code

No

### OS Platform and Distribution

Colab

### Python version

3.7.15

### CUDA/cuDNN version

11.2.152, 8.1.1

### Current Behaviour?

```shell
`tf.random.stateless_categorical`, the stateless version of `tf.random.categorical`, promises to produce the same result on CPU/GPU according to the docs:

> This is a stateless version of tf.categorical: if run twice with the same seeds and shapes, it will produce the same pseudorandom numbers. The output is consistent across multiple runs on the same hardware (and between CPU and GPU), but may change between versions of TensorFlow or on non-CPU/GPU hardware.

But even the doc example does not satisfy this.
```

### Standalone code to reproduce the issue

```shell
with tf.device("/cpu:0"):
  cpuResult = tf.random.stateless_categorical(tf.math.log([[0.5, 0.5]]), 5, [7, 17])
  print(cpuResult)

with tf.device("/gpu:0"):
  gpuResult = tf.random.stateless_categorical(tf.math.log([[0.5, 0.5]]), 5, [7, 17])
  print(gpuResult)
```

### Relevant log output

```shell
tf.Tensor([[1 0 1 0 0]], shape=(1, 5), dtype=int64)
tf.Tensor([[0 0 0 1 0]], shape=(1, 5), dtype=int64)
```
</details>

**Comment by bhack** [comment]
@cantonios I can reproduce this in eager mode on TF-nightly but it seems that they are aligned in graph mode. 
See https://colab.research.google.com/gist/bhack/a0a1dfe818ace0160dfccd0436811e6a/untitled182.ipynb

**Comment by cantonios** [comment]
Interesting.  I wasn't aware we had the same guarantee _between_ devices (CPU and GPU).  /cc @wangpengmit are we sure this is something we can guarantee?  I guess if they both always use the same philox generator with the same seed.

**Comment by creakseek** [comment]
@cantonios CPU and GPU are actually generating same random numbers even with some stateful APIs like `tf.random.normal()` as long as they have the same seed, though not guaranteed. 
```python
with tf.device("/cpu:0"):
  tf.random.set_seed(335)
  print(tf.random.normal([3, 3]))

with tf.device("/gpu:0"):
  tf.random.set_seed(335)
  print(tf.random.normal([3, 3]))
```
You get:
```
tf.Tensor(
[[ 0.8353135  -0.90217495 -0.49177   ]
 [-0.27702156  0.58681077  1.6345242 ]
 [ 0.15613364 -0.7619551  -0.96528214]], shape=(3, 3), dtype=float32)
tf.Tensor(
[[ 0.8353136  -0.90217495 -0.49177   ]
 [-0.27702156  0.58681077  1.6345242 ]
 [ 0.15613362 -0.7619551  -0.9652822 ]], shape=(3, 3), dtype=float32)
```
Which are very close.

**Comment by cantonios** [comment]
@creakseek it will never be _exact_.  Different platforms/compilers have different guarantees for accuracy of things like `std::exp`, which isn't prescribed by the standard to have any specific error bound.  Eigen/XLA also take some liberties here, allowing some small accuracy tradeoffs in order to boost performance.

Most of TF's RNGs are "stateless" (even the stateful random ops) with counter-based RNGs.  If the same counter-based RNG is used, I'd expect the results to be _almost_ the same (with the caveat mentioned above).

**Comment by wangpengmit** [comment]
We don't guarantee it for `tf.random.stateless_categorical` because it doesn't have an `alg` argument, in which case the algorithm is interpreted to be "auto-select" (which can be device-dependent). There is a sentence in https://www.tensorflow.org/guide/random_numbers: `The RNG algorithm used by stateless RNGs is device-dependent, meaning the same op running on a different device may produce different outputs.`

In cases where you can set the `alg` argument (e.g. `tf.random.Generator` and `tf.random.stateless_normal`), we do guarantee cross-device consistency when `alg` is set to a concrete algorithm.  There is a sentence in https://www.tensorflow.org/guide/random_numbers: `Different devices will generate the same integer numbers, if using the same algorithm and starting from the same state. They will also generate "almost the same" float-point numbers, though there may be small numerical discrepancies caused by the different ways the devices carry out the float-point computation (e.g. reduction order).` (We fulfilled this guarantee pretty well between (non-XLA) CPU and (non-XLA) GPU, but less so between non-XLA and XLA kernels.)

So this issue is actually a feature request: add `alg` argument to `tf.random.stateless_categorical`, and guarantee cross-device consistency when `alg` is set to a concrete algorithm.

**Comment by wangpengmit** [comment]
BTW I suspect the reason it's not reproduced in graph mode is because soft placement placed both ops on CPU.

**Comment by bhack** [comment]
> BTW I suspect the reason it's not reproduced in graph mode is because soft placement placed both ops on CPU.

In my shared colab I had:
`tf.config.set_soft_device_placement(False)`

**Comment by bhack** [comment]
Also if it is a FR for introducing the algo control, don't we need in the meantime to modify the mentioned claim?

https://github.com/tensorflow/tensorflow/blob/359c3cdfc5fabac82b3c70b3b6de2b0a8c16874f/tensorflow/python/ops/stateless_random_ops.py#L834:L838

**Comment by bhack** [comment]
Also if it is a FR for introducing the algo control, don't we need in the meantime to modify the mentioned claim?

https://github.com/tensorflow/tensorflow/blob/b2b201fd709a0a256a39751e7aa248d24f349b7a/tensorflow/python/ops/stateless_random_ops.py#L888;L892

**Comment by cantonios** [comment]
Yes, we should remove the `(and between CPU and GPU)` claim.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The RNG algorithm used by stateless RNGs is device-dependent, meaning the same op running on a different device may produce different outputs
https://www.tensorflow.org/guide/random_numbers

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
