### ISSUE TITLE
`tf.raw_ops.FakeQuantWithMinMaxArgs` loses extra precision with certain inputs

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#58447]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.9.2

### Custom Code

No

### OS Platform and Distribution

Colab

### Python version

3.7.15

### CUDA/cuDNN version

11.2.152, 8.1.1

### Current Behaviour?

```shell
With same settings as docs (min=-6, max=6, num_bits=8, narrow_range=False, name=None), applying `tf.raw_ops.FakeQuantWithMinMaxArgs` to the number 2 will produce 1.9764706 on GPU but 2.0235295 on CPU. Both GPU and CPU get -1.9764706 for -2. It looks like CPU is losing precision especially for positive 2.
```

### Standalone code to reproduce the issue

```shell
with tf.device("/cpu:0"):
  input = np.array([-6., -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6])
  output = tf.raw_ops.FakeQuantWithMinMaxArgs(inputs=input, min=-6, max=6, num_bits=8, narrow_range=False, name=None)
  print(output)

with tf.device("/gpu:0"):
  input = np.array([-6., -5, -4, -3, -2, -1, 0, 1, 2, 3, 4, 5, 6])
  output = tf.raw_ops.FakeQuantWithMinMaxArgs(inputs=input, min=-6, max=6, num_bits=8, narrow_range=False, name=None)
  print(output)
```

### Relevant log output

```shell
tf.Tensor(
[-5.9764705 -4.9882355 -4.        -3.0117648 -1.9764706 -0.9882353
  0.         0.9882353  2.0235295  3.0117648  4.         4.9882355
  5.9764705], shape=(13,), dtype=float32)
tf.Tensor(
[-5.9764705 -4.9882355 -4.        -3.0117648 -1.9764706 -0.9882353
  0.         0.9882353  1.9764706  3.0117648  4.         4.9882355
  5.9764705], shape=(13,), dtype=float32)
```
</details>

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.9, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/16b37a4c45f3315727d755c807e3adae/58447.ipynb).

**Comment by cantonios** [comment]
After some deep digging, you're getting different answers because of the use of compiler-generated fused-multiply-adds (FMA).  It's a compiler optimization that actually makes the GPU kernel _slightly_ more accurate. 

The GPU kernel is built with FMA enabled by default (generally, not specific to TF):
- `--fmad=true for nvcc` [docs](https://docs.nvidia.com/cuda/cuda-compiler-driver-nvcc/index.html#options-for-steering-cuda-compilation)
- `-ffp-contract=fast` for clang [docs](https://llvm.org/docs/CompileCudaWithLLVM.html#flags-that-control-numerical-code)

The CPU kernel is not built with FMA by default, though you can enable it by specifically enabling fma via compile flag `-mfma`.

If you explicitly enable FMA in both cases you get the same values (the GPU values you report - mostly - except potentially for some tail-end values, depending on how the compiler decides to fuse some operations).  If you explicitly _disable_ FMA in both cases, you get the same values again (but this time the CPU values you report).

Welcome to the wonderful world of floating-point arithmetic and compiler optimizations.
