### ISSUE TITLE
`tf.exp` on GPU behaves differently from CPU and numpy when a complex input overflows

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#58489]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

Colab

### Python version

3.7.15

### CUDA/cuDNN version

11.2.152, 8.1.1

### Current Behaviour?

When an input of `tf.complex64` is too big (say `100.+0.j`) and thus causes `np.exp` to overflow, it returns `inf+nanj` on GPU, while `np.exp` and `tf.exp` on CPU return `inf+0.j`. This may affect further computation on the result. 

Since `100+0.j` has zero image part, the overflow should only affect its real part.

### Standalone code to reproduce the issue

```shell
print("numpy")
input = np.array([100], dtype=np.complex64)
exp = np.exp(input)
abs = np.abs(exp)
print(input, exp, abs)

with tf.device("/cpu:0"):
  print("CPU")
  input = tf.convert_to_tensor([100], tf.complex64)
  exp = tf.exp(input)
  abs = tf.abs(exp)
  print(input, exp, abs)

with tf.device("/gpu:0"):
  print("GPU")
  input = tf.convert_to_tensor([100], tf.complex64)
  exp = tf.exp(input)
  abs = tf.abs(exp)
  print(input, exp, abs)
```

### Relevant log output

```shell
numpy
[100.+0.j] [inf+0.j] [inf]
CPU
tf.Tensor([100.+0.j], shape=(1,), dtype=complex64) tf.Tensor([inf+0.j], shape=(1,), dtype=complex64) tf.Tensor([inf], shape=(1,), dtype=float32)
GPU
tf.Tensor([100.+0.j], shape=(1,), dtype=complex64) tf.Tensor([inf+nanj], shape=(1,), dtype=complex64) tf.Tensor([nan], shape=(1,), dtype=float32)
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: RuntimeWarning: overflow encountered in exp
  This is separate from the ipykernel package so we can avoid doing imports until
```
</details>

**Comment by creakseek** [comment]
@tilakrayal This is also reproduced on tf nightly.

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow-gpu v2.9, v2.10 and nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/b35c0398ce6c842017603bc6de8c3b23/gpu.ipynb).

**Comment by bhack** [comment]
@tilakrayal Your nightly gist is on CPU only

**Comment by cantonios** [comment]
The C++ standard doesn't seem to specify what happens on complex overflow: [`std::exp(std::complex)`](https://en.cppreference.com/w/cpp/numeric/complex/exp).  For real inputs, it does [explicitly specify](https://en.cppreference.com/w/cpp/numeric/math/exp#Return_value) that the output should be `inf`.

On CPU, we simply call `std::exp`, which returns `inf+0j`.  On GPU, we're calling the MLIR implementation, which is returning `inf+NaNj`.  If I disable MLIR kernels, I get the same result as CPU (because we then revert back to calling `std::exp`).

As for which one is "correct", given the definition that `exp(x + j * y) = exp(x) * cos(y) + j * exp(x) * sin(y)`, I would actually have expected to get an imaginary component of `inf * 0 = NaN`.  So IMO, MLIR is correct, and `std::exp` is technically in the wrong.  Though `std::exp` is probably trying to conform to the specification for real inputs as much as possible.

I'll forward this to the MLIR team, but as a warning: since the behavior is unspecified for such an input, there's no guarantee we can make implementations conform.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
