### ISSUE TITLE
/usr/local/computecpp not found when install tensorflow.

### ISSUE THREAD

**Issue by michaeldengchangshun** [tensorflow/tensorflow#5848]
when run tensorflow configure, it shows /usr/local/computecpp not found when install tensorflow.
I followed the instrcution, But i can not find how to install computecpp. plz help.

**Comment by lukeiwanski** [comment]
Hi @michaeldengchangshun 
unfortunietly, computecpp is not part of TensorFlow package / codebase. You need to install it manually https://www.codeplay.com/products/computesuite/computecpp. Then, during configuration step point tensorflow to the installation directory. 
Hope that helps

**Comment by prb12** [comment]
@michaeldengchangshun If you don't have a good reason to build from source then we would recommend using one of the binary install packages. 
Closing this issue since isn't really a bug.

**Comment by aurelion314** [comment]
Building tensorflow only requires computecpp if you said yes to using OpenCL. For a simple installation, select no to all the additional options.

**Comment by pligor** [comment]
@prb12 We would use the binary install packages but these instructions: http://www.nvidia.com/object/gpu-accelerated-applications-tensorflow-installation.html suggest otherwise
(these instructions also suggest to build an older version of tensorflow, they are not flexible enough)
Are there better instruction somewhere else?

**Comment by tngn** [comment]
No support for Computecpp on Mac OS currently, so spare yourself the trouble of creating an account to download from it website. Just say N to OpenCL.
