### ISSUE TITLE
Feature request: tflite with GPU and Hexagon delegate support on Linux ARM64 platform

### ISSUE THREAD

**Issue by tensorbuffer** [tensorflow/tensorflow#58498]
From this link: https://www.tensorflow.org/lite/guide/build_arm , GPU delegate is "only available for Android" if I use bazel, so I have to use cmake in order to get GPU delegate.
However from this link: https://www.tensorflow.org/lite/guide/build_cmake , there's only TFLITE_ENABLE_GPU, no TFLITE_ENABLE_HEXAGON. I tried to use it in cmake and it's not recognized.
Wondering if tensorflow can either add GPU delegate to bazel build, or add hexagon to cmake? Which one is more appropriate, if I also want to use our own toolchain?

**Comment by mohantym** [comment]
Hi @tensorbuffer !

Thanks for the feature request. It is correct that Hexagon delegate are currently supported for Android if bazel build are used. 

But I think once you [cross-compiled](https://www.tensorflow.org/lite/guide/build_cmake_arm#build_for_aarch64_arm64) with Linux Arm64 tool chain and build a TFlite run time with TFLITE_ENABLE_GPU=ON flag, It might be possible to compile the C++ program (with g++)  with [Hexagon delegate ](https://www.tensorflow.org/lite/android/delegates/hexagon)documentation against hexagon delegate header  and lite gpu delegate header files as included library files

Could you let us know whether you can use hexagon delegate support on linux Arm64 by using above methond.

Thank you!

**Comment by tensorbuffer** [comment]
Just to confirm, even if I use bazel build, I can't compile hexagon delegate for Linux ARM (like this: bazel build -c opt --config elinux_aarch64 ...) ?

**Comment by mohantym** [comment]
@tensorbuffer !

I just confirmed above [statement](https://github.com/tensorflow/tensorflow/issues/58498#issuecomment-1311022712) in this [thread](https://github.com/tensorflow/tensorflow/issues/58497#issuecomment-1310360891). But, yes  It would be good a feature to support gpu delegate for aarch64 through bazel build .

@sachinprasadhs !
Could you look at this feature request.

Thank you!

**Comment by tensorbuffer** [comment]
@sachinprasadhs any progress with adding GPU aarch64 support to bazil build?

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
