### ISSUE TITLE
Failed installation on Mac OS X El Capitan

### ISSUE THREAD

**Issue by bogonetic** [tensorflow/tensorflow#585]
When I run the suggested command: 

pip install https://storage.googleapis.com/tensorflow/mac/tensorflow-0.5.0-py2-none-any.whl

I get the following error:

tensorflow-0.5.0-py2-none-any.whl is not a supported wheel on this platform.

Please advise.
- Tom

**Comment by mrry** [comment]
Can you try again with the latest release?

```bash
$ pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.6.0-py2-none-any.whl
```

If that doesn't work, can you also please share information about your Python version?

**Comment by prasen9** [comment]
Python 3.5.1.  I am having the same issue.

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/get_started/os_setup.md#pip-installation-pip_install -- did you use pip3 ?  Full command line and error message would be helpful.

**Comment by prasen9** [comment]
No, I did not.  But, it seems the problem was that I was using pip and the older version of the wheel.  If I change the wheel to use py3, then it works.  I do not seem to have pip3 installed.  It may be that pip is referring to Python 2 that was installed with my machine and then I installed anaconda and python 3 on my own.  So, maybe my path does not have pip3.  Anyway, I did this with pip and it worked.

pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.6.0-py3-none-any.whl

I do not know if that will cause other problems in the future though.

**Comment by bogonetic** [comment]
Right, this worked for me. Sorry, I guess I got confused and used the python 2 link instead of python 3. Using the following command line worked (as outlined in Install documentation): 
sudo pip3 install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.6.0-py3-none-any.whl
