### ISSUE TITLE
Removal of Experimental_IO Device in DTensor Causing Issues With Horovod Based Models

### ISSUE THREAD

**Issue by rsanthanam-amd** [tensorflow/tensorflow#58516]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.12

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.03

### Python version

3.9

### Bazel version

5.3.0

### Current Behaviour?

```shell
When I run a Horovod based model, GPU devices should not be prematurely added.  They should only be added as each Horovod based process is spawned
```

### Standalone code to reproduce the issue

```shell
I don't have standalone code but here is an analysis of what happens:

The follow commit is relevant:

https://github.com/ROCmSoftwarePlatform/tensorflow-upstream/commit/16ea0f8995a9b087ff7e50bbf5a03e58e3c5002e

In tensorflow/python/training/saving/saveable_object_util.py, the following change is causing the issue:

+  if context.is_custom_device(device_string):
+    return device_string

The reason is that inside the call to is_custom_device, there is another call to self.ensure_initialized() which causes all the GPUs in the system to be added as a result of the call to pywrap_tfe.TFE_NewContext(opts).

This causes issues with the Horovod based model that I am working with because the model subsequently makes additional calls pywrap_tfe.TFE_NewContext(opts) for 1 device per process.  However, this causes an error with adding the GPU devices because they have already been added as a result of the call to is_custom_device.
```

### Relevant log output

```shell
Here is the error (which is repeated):

2022-11-10 06:24:19.634825: E tensorflow/core/common_runtime/session.cc:91] Failed to create session: INVALID_ARGUMENT: 'visible_device_list' listed an invalid Device id '6' but visible device count is 2
2022-11-10 06:24:19.634941: E tensorflow/c/c_api.cc:2209] INVALID_ARGUMENT: 'visible_device_list' listed an invalid Device id '6' but visible device count is 2
```
</details>

**Comment by samatbryan** [comment]
Are you saving a model before a context is initialized?

**Comment by rsanthanam-amd** [comment]
It's an older model that uses sessions which is where the devices are being added.

Here is the call chain in tensorflow/python/training/saver.py:

build -> _build_internal -> _AddShardedSaveOps -> _AddShardedSaveOpsForV2 -> set_cpu0

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/saver.py#L294

Here is where the devices are added:

https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/direct_session.cc#L195

It doesn't seem to create any contexts at all.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
