### ISSUE TITLE
`tf.linalg.pinv` produces all-zero matrix instead of all-`nan` matrix when given `nan` input on GPU

### ISSUE THREAD

**Issue by creakseek** [tensorflow/tensorflow#58523]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10.0, and nightly

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.7.15

### CUDA/cuDNN version

11.3, 8.2.4

### Current Behaviour?

If any element in a matrix is `nan`, its pseudo inverse cannot be computed so an all-`nan` matrix should be returned, which is what `tf.linalg.pinv` does on CPU. But on GPU, when a tensor containing more than one matrices is given, it returns an all-zero tensor for a `nan` tensor instead. It is strange that GPU works well when there is only one matrix, even if it has `nan`.

### Standalone code to reproduce the issue

```shell
allnan = tf.convert_to_tensor([[[np.nan, np.nan], [np.nan, np.nan]]])
partialnan = tf.convert_to_tensor([[[1., 2.], [5., 7.]], [[np.nan, np.nan], [np.nan, np.nan]]])

with tf.device("/cpu:0"):
    print("CPU allnan", tf.linalg.pinv(allnan))
    print("CPU partialnan", tf.linalg.pinv(partialnan))
with tf.device("/gpu:0"):
    print("GPU allnan", tf.linalg.pinv(allnan))
    print("GPU partialnan", tf.linalg.pinv(partialnan))
```

### Relevant log output

```shell
CPU allnan tf.Tensor(
[[[nan nan]
  [nan nan]]], shape=(1, 2, 2), dtype=float32)
CPU partialnan tf.Tensor(
[[[-2.3333328   0.6666665 ]
  [ 1.6666664  -0.33333325]]

 [[        nan         nan]
  [        nan         nan]]], shape=(2, 2, 2), dtype=float32)
GPU allnan tf.Tensor(
[[[nan nan]
  [nan nan]]], shape=(1, 2, 2), dtype=float32)
GPU partialnan tf.Tensor(
[[[-2.333333    0.66666603]
  [ 1.6666664  -0.33333293]]

 [[ 0.          0.        ]
  [ 0.          0.        ]]], shape=(2, 2, 2), dtype=float32)
```
</details>

**Comment by bhack** [comment]
When debugging these composite Ops it help to check intermediate ops result. Locally it is simpler but I've just copied the python implementation of the op.

https://colab.research.google.com/gist/bhack/7f94c652d70fa6ee0edf7b153b79c655/untitled198.ipynb#scrollTo=uuSUdaujgME9 

As you can see the problem for your 2nd case it is already in the U/V values returned by `tf.linalg.svd` op.

/cc @reedwm

**Comment by bhack** [comment]
Summarized

```python
import tensorflow as tf 
tf.config.set_soft_device_placement(False)

partialnan = tf.convert_to_tensor([[[1., 2.], [5., 7.]], [[np.nan, np.nan], [np.nan, np.nan]]])

with tf.device("/cpu:0"):
    print("CPU partialnan", tf.linalg.svd(partialnan,full_matrices=False, compute_uv=True))
with tf.device("/gpu:0"):
    print("GPU partialnan", tf.linalg.svd(partialnan,full_matrices=False, compute_uv=True))
```

**Comment by cantonios** [comment]
Looks like the CUDA solver does actually raise an internal error.  Not sure why it's not surfacing in colab.

@reedwm internally I get an `InvalidArgumentError`, notifying that the solver received a bad info status here: https://github.com/tensorflow/tensorflow/blob/0ba21962fe3e1f78063812ae9cc475ab928163bf/tensorflow/core/util/cuda_solvers.cc#L239

There's been an effort to return `NaN`s instead of crashing on these linalg failures.  So maybe there's a general solution that can be implemented.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
