### ISSUE TITLE
Add support for None values in tf.distribute.ReplicaContext.all_reduce()

### ISSUE THREAD

**Issue by yoeldr** [tensorflow/tensorflow#58552]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

source

### Tensorflow Version

tf 2.10.0

### Custom Code

No

### Current Behaviour?

```shell
`tf.distribute.ReplicaContext.all_reduce()` does not accept `None` for its `value` argument. This results with very long and repative code for removing `None` values, calling `all_reduce()` then adding the `None` values back to the result. This happens often when dealing with gradient calculations, see e.g., https://github.com/keras-team/keras/blob/v2.10.0/keras/optimizers/optimizer_v2/utils.py#L23
(Note that this code sample is private and cannot be used by external users.)

Returning `None` when value is `None` should be very simple to do inside `all_reduce()` and will greatly simplify the calling code.
```

### Standalone code to reproduce the issue

```shell
resolver = tf.distribute.cluster_resolver.TPUClusterResolver.connect("")
strategy = tf.distribute.TPUStrategy(resolver)

@tf.function
def step_fn():
  ctx = tf.distribute.get_replica_context()
  values = [tf.constant(1.), None]
  return ctx.all_reduce(tf.distribute.ReduceOp.SUM, values)

strategy.experimental_local_results(strategy.run(step_fn))
```

### Relevant log output

```shell
ValueError: None values not supported.
```
</details>

**Comment by SuryanarayanaY** [comment]
Iam able to replicate the issue.Please refer the attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/4f335ec9804258aedf70ad58fe8bc94e/58552.ipynb).
Thankyou!

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
