### ISSUE TITLE
TensorFlow Dataset.from_generator leaks memory for randomly generated samples (correlated with 'cuda_malloc_async')

### ISSUE THREAD

**Issue by Szustarol** [tensorflow/tensorflow#58606]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

2.10, 2.9 tested as well

### Custom Code

No

### OS Platform and Distribution

Ubuntu Linux 22.04 and Google Colab tested

### Python version

3.9

### CUDA/cuDNN version

11.8

### Current Behaviour?

```shell
When dataset is generated via `Dataset.from_generator`, samples that have already been used are not removed from GPU memory (or at least this is what I presume), leading to an increased use of VRAM and finally an OOM error as the training proceeds.

This is an important bug, since very often (as in this case) someone might use `from_generator` to perform augmentation etc, and It can be easily seen by examining the `GPU_mem_usage`, that the memory usage indeed grows. For some reason, Colab allocates memory straight away to ~8 GB, so the growth is only noticeable after around 300-500 epochs. The problem is way worse when training on real, larger datasets.

For a simple summary, just view the graphs on the end of the notebook.


Notice (in the notebook), that even though total memory taken on the GPU grows, TensorFlow "thinks" it is consuming basically constant amount of memory, which points into the direction of a memory leak.


Also, it takes around 900 epochs to fill almost the whole memory (16 GB in case of Colab). Epochs consist of 1024 images of shape (64, 64, 3), float32 dtype, giving 1024*3*64*64*900*4 bytes allocated in total, which is around 45 GB, so I presume not all memory is leaked, OR leaking data is not the cause of the problem.

Notice, however, that MobileNetV3 (which I have used in this example) is roughly 18MB in size, and 18MB*900 epochs is basically the aforementioned 16 GB. This could possibly mean that the model's state is leaked somehow, but I have yet to test this hypothesis (for example by using a larger model and checking when the leak happens, i.e. if `num_epochs_until_crash*model_size==gpu_vram_capacity`).


Also, I have tested multiple scenarios locally, and this seems NOT to happen without the `os.environ['TF_GPU_ALLOCATOR'] = 'cuda_malloc_async'` set, however I have no relevant logs to prove it, since when the flag is absent, whole GPU memory is allocated, and I have no means of monitoring it relevantly, since it doesn't change. I have, however, performed 4 tests and none resulted in OOM error after 1500 epochs, while locally they would usually throw OOM after 400 epochs (RTX 3060Ti).
```

### Standalone code to reproduce the issue

```shell
I have provided a minimal example on google colab, can be viewed here:
https://colab.research.google.com/drive/1-ANVp8KF9irKvqdR390QNlop-pPhGMrU?usp=sharing
I think the example is self-explanatory.
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
I could able to replicate the issue in google colab but colab stopped at epoch 858 due to longer training time taken.But still the Expected behaviour captured in logs.Please find attached gist [here](https://colab.research.google.com/gist/SuryanarayanaY/f69d51ac0fd2c3b7a53833ac8b06a736/58606.ipynb#scrollTo=LWN099X70JnO).

**Comment by SuryanarayanaY** [comment]
Hi @Szustarol ,

By default, TensorFlow maps nearly all of the GPU memory of all GPUs (subject to [CUDA_VISIBLE_DEVICES](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#env-vars)) visible to the process.Hence i tried to create logical device to check actual memory used by the TF.

From the documentation of `get_memory_info` [API](https://www.tensorflow.org/api_docs/python/tf/config/experimental/get_memory_info)  the dict specifies only the current and peak memory that TensorFlow is actually using, not the memory that TensorFlow has allocated on the GPU. 

Hence i used `tf.config.experimental.get_memory_info('GPU:0')['current']` to track current Memory being used by TF process where as the nvidia memory you derived for variable `smi_ret` might be the cumulative Memory being used to store the Model configs,checkpoints,logs etc which will keep growing with no of epochs.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/721a9909505d33494741fb19be7f7c99/58606-r1.ipynb#scrollTo=P1wqtKQehp8C) for my case. In your case since you have not limited Memory growth and also used `'peak' `memory to track hence TF allocates all the Memory on GPU and  `smi_ret` memory value also started increasing only after 856 epochs.I hope this make some sense even though it is not an elegant solution.

Please also refer to some comments from other developers for similar issues [comment1](https://github.com/tensorflow/tensorflow/issues/36465#issuecomment-1072994037), [comment2](https://github.com/tensorflow/tensorflow/issues/36465#issuecomment-1073040685) , [comment3](https://github.com/tensorflow/tensorflow/issues/36465#issuecomment-1283513863) which might be useful for understanding this case.

**Comment by Szustarol** [comment]
Hello @SuryanarayanaY,
 I did measure the amount of "current" memory used but I am not sure if this is really the problem here, so I chose to monitor the peak value which should better indicate, that TensorFlow really thinks it ever allocated *less* memory than it actually did. What I find wrong is the fact that as the training proceeds, the cumulative memory allocated on the GPU grows by over 8 GB and finally causes an OOM error after about 800 epochs, which shouldn't happen, and does not happen when the `cuda_malloc_async` flag is not set (as far as my tests show).

I might be wrong but this, for me, is a memory leak when the platform in some circumstances (setting a flag) causes OOM.
What I am trying to say is:
- either the memory is not cleared when it should be cleared automatically (like previous samples from dataset generator are not released),
- or for some reason cuda_malloc_async allocates extra data on the GPU memory which causes the VRAM usage to grow as the training progresses.


To further illustrate the problem I provide yet another colab notebook: 
https://colab.research.google.com/drive/1R1w3HVb3JIqNftF_FsnBT6OwvWsYwNmW?usp=sharing
The *only* difference between this notebook and the previous one, is that the `cuda_malloc_async` flag is NOT set. And now you can see, that the GPU memory taken never exceeds ~8.5 GB, even though training continues for 1500 epochs, while you have been able to confirm, that around 900 epochs is enough to crash the malloc_async version.

**Comment by SuryanarayanaY** [comment]
@sachinprasadhs could you please look into the issue?

**Comment by Szustarol** [comment]
Any updates on this issue?

**Comment by aaudiber** [comment]
If the issue doesn't happen when `cuda_malloc_async` is not set, that makes it seem like the error is related to `cuda_malloc_async`, rather than `Dataset.from_generator`. Someone familiar with GPU memory allocation needs to look into this.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

From the documentation of get_memory_info [API](https://www.tensorflow.org/api_docs/python/tf/config/experimental/get_memory_info) the dict specifies only the current and peak memory that TensorFlow is actually using, not the memory that TensorFlow has allocated on the GPU.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
