### ISSUE TITLE
ComputeH2D is more priority than FeaturesH2D

### ISSUE THREAD

**Issue by zhaozheng09** [tensorflow/tensorflow#58616]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.8

### Custom Code

Yes

### OS Platform and Distribution

Linux

### Mobile device

no

### Python version

2.7

### Bazel version

master

### GCC/Compiler version

10.2.0

### CUDA/cuDNN version

CUDA Version: 11.4

### GPU model and memory

yes

### Current Behaviour?

**BackGround 1**: CUDA only support once H2D in the same time .
**BackGround 2**: 
  1. **FeaturesAsyncH2D**: TrainingData H2D by `dataset.prefetch_to_device`
  2. **ComputeOpH2D**: Some small H2D in Op. for example: DynamicPartitionOpGPU:  compute output size on CPU, and then transfer size to GPU.

**BackGround 3**: **ComputeOpH2D** maybe block current compute, and **FeaturesAsyncH2D** is needed to next few steps, so **ComputeOpH2D** is more important than **FeaturesAsyncH2D**.

When lots of features need AsyncH2D, they maybe block ComputeOpH2D, because TF don't distinguish the priority of ComputeOpH2D and FeaturesAsyncH2D. 
we use nsys to recurrent this bug:
<img width="1560" alt="image" src="https://user-images.githubusercontent.com/33950866/202851210-cb72e589-9dec-4a85-a35b-365b63ace052.png">

</details>

**Comment by mohantym** [comment]
Hi @zhaozheng09 !

Thanks for sharing your observations and the PR #58617 , But I see Python 2.7 in above Template. ( Ignoring Cuda 11.4 and GCC 10.2 which are not included in Test config ( 9.3 , Cuda 11.2 and cudnn 8.1))

Just curious to see the difference in performance  with Python 3.7 with above PR.
Would it be possible to get a toy code snippet to replicate above issue.

Thank you!

**Comment by mohantym** [comment]
@zhaozheng09 !
Could you resolve the conflict in above PR #58617 .
Thank you!

**Comment by zhaozheng09** [comment]
> @zhaozheng09 ! Could you resolve the conflict in above PR #58617 . Thank you!

Done

**Comment by zhaozheng09** [comment]
> 

This problem seems to have nothing to do with the python version.

**Comment by zhaozheng09** [comment]
> Hi @zhaozheng09 !
> 
> Thanks for sharing your observations and the PR #58617 .
> 
> But I see Python 2.7 in above Template. ( Ignoring Cuda 11.4 and GCC 10.2 which are not included in Test config ( 9.3 , Cuda 11.2 and cudnn 8.1))
> 
> Just curious to see the difference in performance with Python 3.7 with above PR. Would it be possible to get a toy code snippet to replicate above issue.
> 
> Thank you!

This problem seems to have nothing to do with the python version.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
