### ISSUE TITLE
Tensorflow Lite C API works much slower than C++ API

### ISSUE THREAD

**Issue by kkuatov** [tensorflow/tensorflow#58613]
### Issue Type

Performance

### Source

source

### Tensorflow Version

tflite v2.4.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 18.04.6 LTS

### Bazel version

CMake was used

### GCC/Compiler version

gcc 7.5.0

### Current Behaviour?

```shell
I built TFLite v2.4.0 static library and used in our project using C++ API 

(we are using it cross-platform Ubuntu/Android/iOS). It shows inference time 5-10 ms on Ubuntu 18. 

We decided to switch to C API (iOS xcframework is available on C). But I see that on 

C API inference time becomes 45-50 ms. I tried to test using TFLite v2.10.0 C API 

and it shows 180-200 ms. The model tested in Ubuntu is a small OCR model 

with size smaller than 200 KB.
```

### Standalone code to reproduce the issue

```shell
I can't upload the whole files, so here is snippets:

class TextRecognizer {
    ...
    virtual TfLiteModel* getModel() = 0;
    TfLiteInterpreterOptions* options;
    TfLiteInterpreter* interpreter;
};
```

Cpp file:
```
vdoc::TextLinePrediction vdoc::TextRecognizer::predict(const cv::Mat &srcImage) {
    ...
    options = TfLiteInterpreterOptionsCreate();
    interpreter = TfLiteInterpreterCreate(getModel(), options);
    TfLiteInterpreterAllocateTensors(interpreter);
    ...
    TfLiteTensor *input_tensor = TfLiteInterpreterGetInputTensor(interpreter, 0);
    TfLiteTensorCopyFromBuffer(input_tensor, convertedImage.data,
                                   convertedImage.total() * convertedImage.elemSize());
    TfLiteInterpreterInvoke(interpreter);
    const TfLiteTensor *output_tensor = TfLiteInterpreterGetOutputTensor(interpreter, 0);
    float *output = output_tensor->data.f;
    ...
}
```

### Relevant log output

```shell
Output is measured time of each TFLite method call:
Time taken to init interpreter: 0.00191s
Time taken to allocate tensors: 0.00060s
Time taken to copy buffer data: 0.00031s
Time taken to Invoke inference: 0.05476s

As I mentioned before on C++ API inference time is about 10 times faster 0.005s.
```

**Comment by mohantym** [comment]
@kkuatov !
Thanks for sharing your results on C and C++ inference with respect to your OCR model.

@sachinprasadhs !
Could you look at this issue.

Thank you!

**Comment by pjpratik** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.

**Comment by kkuatov** [comment]
I made some workaround and achieved what I needed. I used C++ on Android/Ubuntu and C on iOS. I hope it is fixed in new releases, but can't test it now. So I think we can close it, since it feels like no one is facing the same issue. @pjpratik
