### ISSUE TITLE
Tensorflow lite dynamic input

### ISSUE THREAD

**Issue by sonfire186** [tensorflow/tensorflow#58622]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Windows 11
- TensorFlow installation (pip package or built from source):
pip 2.10

### 2. Code
inputs = tf.keras.layers.Input(shape=(None, None, 3), name='input_image')
model = tf.keras.Model(inputs, inputs)

input_image - [(None, None, None,  3)]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

input_image - [1 1 1 3]

**Comment by tiruk007** [comment]
@sonfire186 
Could you please elaborate on the issue reported here and provide a complete code snippet to reproduce the issue.

Thank you!

**Comment by sonfire186** [comment]
@tiruk007 
```
inputs = tf.keras.layers.Input(shape=(None, None, 3), name='input_image')
model = tf.keras.Model(inputs, inputs, name='light_level_detection')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
    f.write(tflite_model)

interpreter = tf.lite.Interpreter(model_path='model.tflite')
interpreter.allocate_tensors()

# Print input shape and type
inputs = interpreter.get_input_details()
print('{} input(s):'.format(len(inputs)))
for i in range(0, len(inputs)):
    print('{} {}'.format(inputs[i]['shape'], inputs[i]['dtype']))

# Print output shape and type
outputs = interpreter.get_output_details()
print('\n{} output(s):'.format(len(outputs)))
for i in range(0, len(outputs)):
    print('{} {}'.format(outputs[i]['shape'], outputs[i]['dtype']))
```



```
1 input(s):
[1 1 1 3] <class 'numpy.float32'>

1 output(s):
[1 1 1 3] <class 'numpy.int32'>
```

**Comment by mohantym** [comment]
Hi @sonfire186 !
Thanks for bringing  the feature request on Dynamic input. We have already informed the concerned team about this earlier.

Current workaround is give static shape using [model binding](https://www.tensorflow.org/lite/inference_with_metadata/codegen#mlbinding) before deploying in android.

@sachinprasadhs !
Could you look at this feature request.

Thank you!

**Comment by sonfire186** [comment]
@mohantym 

java.lang.OutOfMemoryError: Failed to allocate a 144384016 byte allocation with 25165824 free bytes and 68MB until OOM, target footprint 356191760, growth limit 402653184

**Comment by pjpratik** [comment]
Hi @sonfire186 

If you want to run a model with dynamic input shape, resize the input shape before running inference. Otherwise, the None shape in Tensorflow models will be replaced by a placeholder of 1 in TFLite models.

There are 2 parts, shape and shape_signature. You must be seeing something like `'shape_signature': array([ 1, -1, -1,  3]`

shape: if you just decided to load the model and run, this is the shape of the tensor.

shape_signature: Is similar to shape but instead might have some dimensions labeled with -1, these dimensions are the dimensions that are dynamic and can be resized.

That means that the model you are converting has shape [1, None, None, 3]  and you can resize the 'None' dimensions at runtime.

Thanks.
