### ISSUE TITLE
TFlite IOS will not build when imported as part of a package. 100+ Undefined Symbols reported at link phase

### ISSUE THREAD

**Issue by arctop-sk** [tensorflow/tensorflow#58663]
### Issue Type
Build/Install

### System information

Mac OS 12.6.1
XCode 14.1
TFLite 2.9.1

### Describe the problem

I am trying to add TFLite to a swift package that we have. Essentially our code runs its own tflite models, so it has a dependency on TFLite Swift, which depends on TFLiteC. Since this is a swift package, it is not an option to use pods.

Using information from [this thread](https://github.com/tensorflow/tensorflow/issues/44609), I was able to add the TFLite dependencies, and successfully build my swift package as a standalone package.

However, once I add my package into an actual project, the linking phase completely breaks, with over 100 undefined symbols.

<img width="1920" alt="Screen Shot 2022-11-23 at 20 48 50 PM  1" src="https://user-images.githubusercontent.com/37613957/203625490-dcbf46ee-2238-4dfb-91ec-84a380155bb7.png">

This also happens when using the examples at the end of the above thread.

For clarity, adding the package here, under Frameworks, Libraries, and Embeded content causes the linking failure. 
<img width="1920" alt="Screen Shot 2022-11-23 at 20 55 02 PM  1" src="https://user-images.githubusercontent.com/37613957/203626093-07f9f1e8-cd1f-4059-b3b9-c31bc383ec7d.png">

### Source code / logs

Here is a link to the test project that reproduces this error. (50mb so I cannot directly upload it here)

https://drive.google.com/file/d/1xV-qSxF7z94SqFSrf1QWBkwHesIug0wt/view?usp=sharing

**Comment by DwayneDuane** [comment]
@arctop-sk you appear to not have included the standard C++ library in your project. You can try to add `libc++.tdb` to your "Frameworks, Libraries, and Embedded Content" section:
![index](https://user-images.githubusercontent.com/67419721/203641350-9cd57fdc-e037-4948-8aee-5108476c8265.png)
Also, IIRC, this is only an issue if you build TFLite as static framework. Consider building them as dynamic frameworks if possible.
Your project appears to be in Swift. Swift cannot directly talk to C++, so you may need to deal with the complexity of writing some wrappers in Objective-C around the TFLite API. I would either make an Objective-C project instead of Swift, or consider getting TFLite into your project using Cocoa Pods: https://www.tensorflow.org/lite/guide/ios

**Comment by arctop-sk** [comment]
@DwayneDuane 

Thanks. In fact adding libc++ does solve the linking issue. This was a test, where ultimately i will be using TFLite swift as the API, it just depends on getting this part correctly compiling.

As stated, i need to have this work as a swift package until the team releases a working swift package as mentioned in the referenced thread. For now, this should work.
