### ISSUE TITLE
installing tensor flow on m2

### ISSUE THREAD

**Issue by derrickny** [tensorflow/tensorflow#58689]
ERROR: Could not find a version that satisfies the requirement tensorflow (from versions: none)
ERROR: No matching distribution found for tensorflow

getting this error when I try installing tensor flow on apple m2 MacBook Air

**Comment by tilakrayal** [comment]
@derrickny,
In order to expedite the trouble-shooting process, could you please provide the following information
OS Platform and Distribution (e.g., Linux Ubuntu 16.04):
Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue happens on mobile device:
TensorFlow installed from (source or binary):
TensorFlow version:
Python version:
Installed using virtualenv? pip? conda?:
Bazel version (if compiling from source):
GCC/Compiler version (if compiling from source):
CUDA/cuDNN version:
GPU model and memory:
 
and the exact sequence of commands / steps that you executed before running into the problem. Thank you!

**Comment by derrickny** [comment]
hello I was able to fix the issue I used Conda to download tensor flow.Thank you

**Comment by tilakrayal** [comment]
@derrickny,
Glad the issue is resolved for you, Could you please feel free to move this to closed status. Thank you!
