### ISSUE TITLE
Incompatible Bazel version with the docs

### ISSUE THREAD

**Issue by sniafas** [tensorflow/tensorflow#58694]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

2.11

### Custom Code

No

### OS Platform and Distribution

Debian 11

### Python version

3.8

### Bazel version

5.1.1

### GCC/Compiler version

9.3.0

### CUDA/cuDNN version

11.2,8.1

### GPU model and memory

RTX 3060/12G

### Current Behaviour?

```shell
As it has been discussed https://github.com/tensorflow/tensorflow/issues/58461#issuecomment-1325666595 Bazel version used from the project is not aligned with the one in docs. Since .bazelversion file pinpoints 5.3.0, there is version incompatibility and build from source fails to start.

Happy to do a PR refactoring .bazelversion
```

### Standalone code to reproduce the issue

```shell
Install bazel 5.1.1 and try to compile TF r2.10/2.11.
```

### Relevant log output

```shell
Use other bazel version
```
</details>

**Comment by mohantym** [comment]
Hi @sniafas !
Feel free to raise a PR.
Thank you!

**Comment by mohantym** [comment]
Hi @sniafas !
I could replicate this issue for 2.11 with Bazel 5.1.1 for Cuda support. It asks Bazel 5.3.1 for GPU builds as you mentioned earlier and working as expected for 2.10.

Attached [gist](https://colab.sandbox.google.com/gist/mohantym/d7479993bd95a7ad4f2bb028ca5d8d0d/tensorflow-ranking.ipynb#scrollTo=A3IQrnSBaqXx) for reference.

Updated the documentation through PR[#2158 ](https://github.com/tensorflow/docs/pull/2158) instead of refactoring Bazel rc version.

Thank you!

**Comment by sniafas** [comment]
Hi @mohantym,

seems like a good idea! (Ah i missed the opportunity of a small PR)

**Comment by 8bitmp3** [comment]
This hopefully should have been fixed https://github.com/tensorflow/docs/commit/67e8be9afda4baffadc821a0c99ca423e3e5e415 Thanks @sniafas @mohantym Feel free to reopen if any updates are needed.
