### ISSUE TITLE
Expecting the same names when converting to tflite model

### ISSUE THREAD

**Issue by pfk-beta** [tensorflow/tensorflow#58732]
Hello,

I have created very simple model, and I want to export it to tflite model, to benchmark it on android device, and run simple inferences. This is code to create model:
```python
import tensorflow as tf
import numpy as np
from tensorflow import keras
from tensorflow.keras import layers

input0 = keras.Input(shape=(64,), name="input0") 
input1 = keras.Input(shape=(16,), name="input1")
input2 = keras.Input(shape=(16,), name="input2")

layer0 = layers.Dense(3, activation="relu", name="layer0")(input0)
layer1 = layers.Dense(5, activation="relu", name="layer1")(input1)
layer2 = layers.Dense(7, activation="relu", name="layer2")(input2)

x0 = layers.concatenate([layer0, layer1, layer2])
x1 = layers.concatenate([layer0, layer1, layer2])

output0 = layers.Dense(3, name="output0")(x0)
output1 = layers.Dense(7, name="output1")(x1)

model = keras.Model(
    inputs=[input0, input1, input2],
    outputs=[output0, output1],
)
model.compile(optimizer='sgd', loss='mean_squared_error')

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
tflite_model = converter.convert()

with open('model.tflite', 'wb') as f:
    f.write(tflite_model)
```
environment: google colab

I expect, that tflite model would have `input0`, `input1`, `input2` input names, and `output0` , `output1` output names. But...
Real names are: `serving_default_input0:0`, `serving_default_input1:0`, `serving_default_input2:0`, `StatefulPartitionedCall:0`, `StatefulPartitionedCall:1`

**Comment by mohantym** [comment]
Hi @pfk-beta !
Thanks for feature requesting on setting same name given in model. Original name becomes a metadata for the final names of input and output after conversion and is being decided by conversion process itself.

@sachinprasadhs !
Could you look at this feature request.

Thank you!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.

Thanks.
