### ISSUE TITLE
No speed improvements after TF-TRT optimizing on a tensorflow BERT model

### ISSUE THREAD

**Issue by SohaKhazaeli** [tensorflow/tensorflow#58755]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [ Y] I am using the latest TensorFlow Model Garden release and TensorFlow 2.
- [ Y] I am reporting the issue to the correct repository. (Model Garden official or research directory)
- [ Y] I checked to make sure that this issue has not been filed already.

## 1. The entire URL of the file you are using

https://github.com/tensorflow/models/blob/master/official/nlp/modeling/models/bert_classifier.py

## 2. Describe the bug

After optimizing the model with either FP32 or FP16 I don't get any speed improvements. for int8 I get error in optimization.

## 3. Steps to reproduce

1-optimize with tensorRT
2- test the new mode (no change in inference time

## 4. Expected behavior

The inference time should be decreased after the optimization

## 5. Additional context

![image](https://user-images.githubusercontent.com/38143776/201936813-462dca3f-03a0-450e-aa0b-9ee388845704.png)
## 6. System information
- on docker image: tensorflow/tensorflow:2.10.0-gpu
- 
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Amazon linux
- Mobile device name if the issue happens on a mobile device:
- TensorFlow installed from (source or binary): binary
- TensorFlow version (use command below): 2.10
- Python version: 3.X
- Bazel version (if compiling from source):
- GCC/Compiler version (if compiling from source):
- CUDA/cuDNN version: 11.2.1/8.1.0.77-1
- GPU model and memory: T4

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

TensorRT support is disabled in CUDA builds for code health improvement and Hermetic CUDA support is added.
https://github.com/tensorflow/tensorflow/releases

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
