### ISSUE TITLE
tfds plant_leaves downloads failing

### ISSUE THREAD

**Issue by jamesbraza** [tensorflow/tensorflow#58777]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

No

### OS Platform and Distribution

macOS Monterey version 12.6

### Mobile device

n/a

### Python version

3.10

### CUDA/cuDNN version

n/a

### GPU model and memory

n/a

### Current Behaviour?

I am getting timeouts when trying to download the [`plant_leaves`](https://www.tensorflow.org/datasets/catalog/plant_leaves) dataset on December 4th, 2022.

### Standalone code to reproduce the issue

```python
import tensorflow_datasets as tfds

dataset = tfds.load(name="plant_leaves", split="train", as_supervised=True)
```

### Relevant log output

```None
File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/download/downloader.py", line 306, in _assert_status
    raise DownloadError('Failed to get url {}. HTTP code: {}.'.format(
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://data.mendeley.com/v1/datasets/hb74ynkjcn/1/files/7f977a2c-aa75-4610-a6f6-84c8738d8c79/0001_0001.JPG. HTTP code: 404.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/logging/__init__.py", line 250, in decorator
    return function(*args, **kwargs)
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/load.py", line 575, in load
    dbuilder.download_and_prepare(**download_and_prepare_kwargs)
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py", line 523, in download_and_prepare
    self._download_and_prepare(
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/core/dataset_builder.py", line 1244, in _download_and_prepare
    split_generators = self._split_generators(  # pylint: disable=unexpected-keyword-arg
  File "/path/to/lib/python3.10/site-packages/tensorflow_datasets/image_classification/plant_leaves.py", line 123, in _split_generators
    raise DownloadRetryLimitReachedError(
tensorflow_datasets.image_classification.plant_leaves.DownloadRetryLimitReachedError: Retry limit reached. Try downloading the dataset again.
```
</details>

**Comment by jamesbraza** [comment]
I just realized that perhaps I should have opened this issue in [tensorflow/datasets](https://github.com/tensorflow/datasets).

Let me know if you would like me to close and re-open there.

**Comment by jamesbraza** [comment]
For what it's worth, looks like [`plantae_k`](https://www.tensorflow.org/datasets/catalog/plantae_k) dataset is also not download-able right now.  Very similar stack trace:

```none
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://data.mendeley.com/v1/datasets/t6j2h22jpx/1/files/b48040b2-a92e-4a08-b427-edb148782f5d/apple_d001.JPG. HTTP code: 404.
```

![image](https://user-images.githubusercontent.com/8990777/205563256-dec9194b-7ff1-48bf-9872-ebab5200ada4.png)

Additionally Mendeley has newer versions:
- `plant_leaves`: version 5
- `plantae_k`: version 2

**Comment by gaikwadrahul8** [comment]
Hi, @jamesbraza 

Apologize for the delay and I was able to replicate the issue on Google Colab and on `MacOS` also but I'm also getting the same error message ```
DownloadError(
tensorflow_datasets.core.download.downloader.DownloadError: Failed to get url https://data.mendeley.com/v1/datasets/hb74ynkjcn/1/files/7f977a2c-aa75-4610-a6f6-84c8738d8c79/0001_0001.JPG. HTTP code: 404.
```  It seems like some images url or url iteself for images are not found because we are getting `HTTP code: 404`. so for your reference I have added [gist-file ](https://colab.research.google.com/gist/gaikwadrahul8/cbc47fd8970295c5e028dd017001ab2c/-58777.ipynb)and also `MacOS` screenshot below 

I have also tried with `tfds.core.DatasetBuilder() `approach to download as mentioned below in the code snippet but still getting the same error but I'm able to see it's creating some images folders with tfrecord files

It seems like this issue with `plant_leaves` dataset because I have tried with `mnist` dataset and it's working fine, for your reference here is [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/7ce2468ea3a3f0410d34ccdd4231ca9e/dataset-test.ipynb) so could you please post this issue in this [repo](https://github.com/tensorflow/datasets/issues) for faster resolution. Thank you!

```
plant_leaves_builder = tfds.builder("plant_leaves", data_dir='./')
plant_leaves_builder.download_and_prepare()
datasets = plant_leaves_builder.as_dataset()

train_dataset, test_dataset = datasets["train"], datasets["test"]
assert isinstance(train_dataset, tf.data.Dataset)

# And then the rest of your input pipeline
train_dataset = train_dataset.repeat().shuffle(1024).batch(128)
train_dataset = train_dataset.prefetch(2)
features = tf.compat.v1.data.make_one_shot_iterator(train_dataset).get_next()
image, label = features['image'], features['label']

```
<img width="1512" alt="Screenshot 2023-02-17 at 4 26 16 PM" src="https://user-images.githubusercontent.com/115997457/219628374-bbfd8b9e-86a1-48c6-bc97-83cf88b8d1ec.png">

**Comment by jamesbraza** [comment]
@gaikwadrahul8 thank you for confirming!

I have made a duplicate issue here: https://github.com/tensorflow/datasets/issues/4744.

**Comment by gaikwadrahul8** [comment]
Hi, @jamesbraza 

Thank you for posting this issue in this [repo](https://github.com/tensorflow/datasets/issues) and this issue will be taken care by that team so I'm closing the issue since it is being tracked in `tensorflow/datasets` repo and if you need any further help please post your comments or re-open this issue. Thank you!
