### ISSUE TITLE
Memory leak in decode_jpeg()

### ISSUE THREAD

**Issue by resetpointer** [tensorflow/tensorflow#58826]
Hi, I am using cppflow wrapper to interface directly with tensorflow-2.8 via the native TF C-API. Basically, I have two different ways of creating a tensor. The first method is by using cppflow::decode_jpeg() to create a tensor on GPU memory; the second method is by creating a tensor manually on system memory. The first method causes memory leak, where as the second method does not. The code is as follow:

```cpp
#define USE_TENSORFLOW_GPU_API
#ifdef USE_TENSORFLOW_GPU_API
    input = cppflow::decode_jpeg(req->image().content());
    input = cppflow::expand_dims(input, 0);
#else
    std::vector<uint8_t> data;
    for(int i=0; i < h; i++){
        for(int j=0; j < w; j++){
            QColor color = image.pixelColor(j,i);
            int red, green, blue;
            green = color.green();
            blue = color.blue();
            red = color.red();
            data.push_back(red);
            data.push_back(green);
            data.push_back(blue);
        }
    }

    input = cppflow::tensor(data, {1, h, w, 3});
#endif
```

I am not sure what causes the memory leak, would someone comment on this issue?

I read from this [thread](https://groups.google.com/a/tensorflow.org/g/discuss/c/3czXdek8rEg?pli=1) that GPU memory (of CUDA toolkit) does not get de-allocated until a process is terminated. Please advise if you know anything about this.

Thank you,

**Comment by mohantym** [comment]
Hi @resetpointer !
Thanks for sharing your observations w.r.to memory leak in C++ runtime.

@SuryanarayanaY !
Could you look at this issue.

Thank you!

**Comment by resetpointer** [comment]
Please let me know what to do to help; I can provide a small sample test case if needed.


Thanks,

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
