### ISSUE TITLE
 How to release memory when I want to change model with tf.saved_model.load already?

### ISSUE THREAD

**Issue by gaohuacq** [tensorflow/tensorflow#58852]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

Yes

### Current Behaviour?

```shell
I use tf.saved_model.load to load a trained model. I want to change another model when it done. But the memory is still high, How to release the memory? I have test tf.keras.backend.clear_session() and gc.collect(), all of these didn't work.
```

### Standalone code to reproduce the issue

```shell
model = tf.saved_model.load(model_dir)

tf.keras.backend.clear_session()
gc.collect()
```

### Relevant log output

_No response_</details>

**Comment by pjpratik** [comment]
@gaohuacq Can you please refer through [this](https://github.com/keras-team/keras/issues/12625#issuecomment-668814501) comment and let us know if that helps. Thank you.

**Comment by gaohuacq** [comment]
> @gaohuacq Can you please refer through [this](https://github.com/keras-team/keras/issues/12625#issuecomment-668814501) comment and let us know if that helps. Thank you.

I have tested this, but it doesn't work.

**Comment by SuryanarayanaY** [comment]
Hi @gaohuacq ,
While saving the model using `model.save()` API you can pass kwarg `overwrite=True ` like  below: `model.save(overwrite=True)` 
This will overwrite previous configuration with new configuration during each `model.save`.

If you are not overriding the same model then after each `model.save('some_dir_path')` you need to delete the `model` variable.Since the generated variables in a process won't release memory until deletion or end of process.

Parallely you can use tf.keras.backend.clear_session() and gc.collect() for efficient use.
