### ISSUE TITLE
Crash with dynamic tf.reshape "Check failed: dtype() == expected_dtype (9 vs. 3)"

### ISSUE THREAD

**Issue by bodokaiser** [tensorflow/tensorflow#5886]
```py
import tensorflow as tf

queue = tf.train.string_input_producer(['data.tfrecord'])

reader = tf.TFRecordReader()
_, example = reader.read(queue)

features = tf.parse_single_example(example,features={
    'mr_image': tf.FixedLenFeature([], tf.string),
    'us_image': tf.FixedLenFeature([], tf.string),
    'mr_shape': tf.FixedLenFeature([2], tf.int64),
    'us_shape': tf.FixedLenFeature([2], tf.int64),
})

mr_image = tf.decode_raw(features['mr_image'], tf.int16)
us_image = tf.decode_raw(features['us_image'], tf.uint8)

mr_shape = tf.cast(features['mr_shape'], tf.int64)
us_shape = tf.cast(features['us_shape'], tf.int64)

with tf.Session() as sess:
    coord = tf.train.Coordinator()
    threads = tf.train.start_queue_runners(sess=sess, coord=coord)
    
    #mr = tf.reshape(mr_image, mr_shape)
    #us = tf.reshape(us_image, us_shape)

    print(len(sess.run(mr_image)),len(sess.run(us_image)))
    print(sess.run([mr_shape, us_shape]))
    #print(sess.run(tf.reshape(mr_image, mr_shape)))
    
    coord.request_stop()
    coord.join(threads)
```

Will print:
```
183604 118218
[array([466, 394]), array([366, 323])]
```

However `print(sess.run(tf.reshape(mr_image, mr_shape)))` will cause a crash with:
```sh
F tensorflow/core/framework/tensor.cc:441] Check failed: dtype() == expected_dtype (9 vs. 3)
```

Also `print(sess.run(tf.reshape(mr_image, [466, 394])))` works as expected.

- macOS 10.12.1
- Python 3.5.2
- tensorflow 0.11

**Comment by prb12** [comment]
Thanks for reporting the issue. It looks from your report that this is a runtime failure, rather than a Python exception.

The docs for `tf.reshape` state that the new shape is allowed to be int32 or int64:
https://www.tensorflow.org/versions/r0.11/api_docs/python/array_ops.html#reshape
and the op is correctly registered:
https://github.com/tensorflow/tensorflow/blob/r0.11/tensorflow/core/ops/array_ops.cc#L1155

However, unless I'm missing something it looks like the implementation of the OpKernel assumes that the `sizes` are `int32`:
https://github.com/tensorflow/tensorflow/blob/r0.11/tensorflow/core/kernels/reshape_op.h#L48

This seems to have been the case for a *long* time!  

As a workaround, you could simple use int32 shapes, but either the documentation or implementation should probably be fixed.

**Comment by bodokaiser** [comment]
@prb12 Yes, correct if I change to:

```py
mr_shape = tf.cast(features['mr_shape'], tf.int64)
us_shape = tf.cast(features['us_shape'], tf.int64)
```

it works!

If it makes sense I could add a type check to `tf.reshape` would just require some details where to place it best.

**Comment by vrv** [comment]
The best thing to do is add a TypeConstraint<int32>("Tshape") to all of the kernel regisgtrations here: https://github.com/tensorflow/tensorflow/blob/r0.11/tensorflow/core/kernels/reshape_op.cc#L21

since right now the implementation assumes int32 for the Tshape input.  Do you want to make that change?

**Comment by bodokaiser** [comment]
This seems to be already the case in [later releases](https://github.com/tensorflow/tensorflow/blob/c8a45a8e236776bed1d14fd71f3b6755bd63cc58/tensorflow/core/kernels/reshape_op.cc). Should I still add this change to the `r0.11` branch?

Are there any tests for this?

**Comment by vrv** [comment]
Oh hm, I *thought* I fixed that weeks ago too, glad to hear I didn't miss this one.  We don't have a lot of 'not implemented' tests, which is what would be needed to test this case -- one could register the kernels for Tshape<int64> if desired, we just haven't gotten around to adding them + tests.

We haven't backported a lot of changes into 0.x releases, but I suspect we'll do so once we hit 1.0.

**Comment by zh794390558** [comment]
@prb12 Thanks.

**Comment by stefan-falk** [comment]
Potentially related issue: https://github.com/tensorflow/tensorflow/issues/9836
