### ISSUE TITLE
No OpKernel was registered to support Op 'CudnnRNN' used by {{node CudnnRNN}} with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", seed2=0, is_training=true] Registered devices: [CPU, GPU] Registered kernels:   <no registered kernels>  	 [[CudnnRNN]] 	 [[sequential_2/lstm/PartitionedCall]] [Op:__inference_train_function_66459]

### ISSUE THREAD

**Issue by Rishi-11-2** [tensorflow/tensorflow#58866]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Performance

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.10.6

### Current Behaviour?

```shell
A bug happened!
I am running it on AMD GPU using tensorflow-directml
when I tried to run the following code , it threw an error
```

### Standalone code to reproduce the issue

```shell
inception_v3=tf.keras.applications.InceptionV3(
    include_top=False,
    weights="imagenet",
    input_tensor=None,
    input_shape=(IMAGE_HEIGHT, IMAGE_WIDTH, 3),
)

lrcnn_model.add(TimeDistributed(inception_v3, input_shape = (SEQUENCE_LENGTH,IMAGE_HEIGHT, IMAGE_WIDTH, 3)))

lrcnn_model.add(TimeDistributed(Flatten()))
lrcnn_model.add(LSTM(32))
lrcnn_model.add(Dense(len(CLASSES_LIST), activation = 'softmax'))


# Create an Instance of Early Stopping Callback.
early_stopping_callback = EarlyStopping(monitor = 'val_loss', patience = 5, mode = 'min', restore_best_weights = True)
 
# Compile the model and specify loss function, optimizer and metrics to the model.
lrcnn_model.compile(loss = 'categorical_crossentropy', optimizer = 'Adam', metrics = ["accuracy"])

# Start training the model.
LRCN_model_training_history = lrcnn_model.fit(x = features_train, y = labels_train, epochs = 7, batch_size = 4 , shuffle = True, validation_split = 0.2, callbacks = [early_stopping_callback])
```

### Relevant log output

```shell
InvalidArgumentError                      Traceback (most recent call last)
Cell In [67], line 8
      5 lrcnn_model.compile(loss = 'categorical_crossentropy', optimizer = 'Adam', metrics = ["accuracy"])
      7 # Start training the model.
----> 8 LRCN_model_training_history = lrcnn_model.fit(x = features_train, y = labels_train, epochs = 7, batch_size = 4 , shuffle = True, validation_split = 0.2, callbacks = [early_stopping_callback])

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\tensorflow\python\eager\execute.py:54, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52 try:
     53   ctx.ensure_initialized()
---> 54   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                       inputs, attrs, num_outputs)
     56 except core._NotOkStatusException as e:
     57   if name is not None:

InvalidArgumentError: Graph execution error:

No OpKernel was registered to support Op 'CudnnRNN' used by {{node CudnnRNN}} with these attrs: [seed=0, dropout=0, T=DT_FLOAT, input_mode="linear_input", direction="unidirectional", rnn_mode="lstm", seed2=0, is_training=true]
Registered devices: [CPU, GPU]
Registered kernels:
  <no registered kernels>

	 [[CudnnRNN]]
	 [[sequential_2/lstm/PartitionedCall]] [Op:__inference_train_function_66459]
```
</details>

**Comment by krrishdholakia** [comment]
The error message indicates that there is no registered kernel to support the Op 'CudnnRNN' which is used by the node CudnnRNN. This suggests that there is an issue with Tensorflow's version compatibility with the GPU or the optimizer being used. Trying a different version of Tensorflow, an NVIDIA GPU, or a different optimizer such as SGD or AdamW may help resolve the issue.

If feasible, you can try using an NVIDIA GPU instead of an AMD GPU. Additionally, you can try using a different optimizer such as SGD or AdamW - You may need to try a different optimizer such as SGD or AdamW, as the current optimizer may not be compatible with the version of TensorFlow or the GPU being used.

**Comment by Rishi-11-2** [comment]
Its still showing the same error even I tried using a different optimiser. Also I used different tensorflow version but still showing the same error

**Comment by krrishdholakia** [comment]
You can try to reinstall your GPU driver or reinstall the CUDA Toolkit to make sure that the proper OpKernel is registered. You can also check the device_name and op_name in the stacktrace to make sure that the GPU is being used for the operation.

**Comment by Rishi-11-2** [comment]
I have AMD GPU so CUDA Toolkit wont  be compatible with it. My question is why LSTM using cuda operations?

**Comment by krrishdholakia** [comment]
Ah, for a 'why' question on this, I think code owners are probably your best bet. 

cc: @tilakrayal

**Comment by sushreebarsa** [comment]
@Rishi-11-2 
In order to expedite the trouble-shooting process, please provide the complete code snippet to reproduce the issue reported here. Thank you!

**Comment by bakikocabasa** [comment]
it is really annoying, there is no such source to find a solution for this error. I keep having it. What I guess is that it might be library conflict problem that causes this one.

**Comment by Rishi-11-2** [comment]
The problem is that I used a direct-ml plugin so tensorflow can utilise the AMD GPU . But I don't know why , cuda LSTM is being executed which is not supported by AMD GPU and therefore this error is being thrown

**Comment by Rishi-11-2** [comment]
With tensorflow-directml plugin , I was able to make tensorflow utilise AMD GPU . However when I tried to run LSTM , it gave an error

**Comment by bakikocabasa** [comment]
what is the error that you get?

**Comment by gaikwadrahul8** [comment]
Hi, @Rishi-11-2 

Apologize for the delay and It seems like somewhere in your code, you're using `CudnnRNN` and as you know `AMD GPU `is not compatible with `cuda-toolkit `and if you're not using `CudnnRNN` anywhere in your code so Could you please try to run the same code on Google Colab with GPU and check whether is it running as expected or not ? If not, In order to expedite the trouble-shooting process, could you please provide a code snippet or Google Colab with all imports to reproduce the issue reported here ? Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @Rishi-11-2 

I'm unable to replicate the exact same issue from my end because I'm not sure what values you're passing to `SEQUENCE_LENGTH,` I`MAGE_HEIGHT`, `IMAGE_WIDTH`, `CLASSES_LIST`so to replicate the same behaviour from my end, could you please help me with same code snippet which you're using with all imports and if possible please help me with Google Colab with exact same code which you are using so it will help me to debug your issue ?

May I know have you tried to execute the same code with CPU only if yes is it working fine with CPU ? If not please try it to run on either with CPU only or on Google Colab and check whether is it working as expected or not ? Thank you!

**Comment by bakikocabasa** [comment]
Hi, @gaikwadrahul8,

Since I follow this issue, I tried to overcome the problem by myself. However, I struggle to setup the right libraries and Cuda environment. If you do not mind, would you share a requirement.txt for your GPU environment where you can activate GPU and also mention about Cuda toolkit and CUDA version besides of this information? I am looking for a stable environment for my research. 

Thank you,
best regards

**Comment by gaikwadrahul8** [comment]
Hi, @bakikocabasa 

May I know on which OS you're trying to install Tensorflow GPU please ? and at the moment our stable and latest Tensorflow version is `2.11` and you'll have to install `cudatoolkit=11.2` and `cudnn=8.1.0` so I would suggest you to please follow our [official documentation](https://www.tensorflow.org/install/pip), Please let us know if you face any issue with error log. Thank you!

**Comment by bakikocabasa** [comment]
Hi,

I am using winOS. I will try these two. Have your ever tried to uninstall CUDA? I have Cudatoolkit 12.0... This does not work for me. Rather than only uninstalling it from add & remove the program, I think I need to modify system variable paths as well.

Thank you !

**Comment by bakikocabasa** [comment]
Issue is solved by using mentioned cuda version and toolkit and also having the latest nvidia drivers installed. Thank you for helping. I attached the libraries used for activating the GPU, If it might help...
 !`absl-py==1.4.0
asttokens @ file:///home/conda/feedstock_root/build_artifacts/asttokens_1670263926556/work
astunparse==1.6.3
backcall @ file:///home/conda/feedstock_root/build_artifacts/backcall_1592338393461/work
backports.functools-lru-cache @ file:///home/conda/feedstock_root/build_artifacts/backports.functools_lru_cache_1618230623929/work
cachetools==5.3.0
certifi==2022.12.7
charset-normalizer==3.0.1
colorama @ file:///home/conda/feedstock_root/build_artifacts/colorama_1666700638685/work
contourpy==1.0.7
cycler==0.11.0
debugpy @ file:///C:/ci/debugpy_1637073815078/work
decorator @ file:///home/conda/feedstock_root/build_artifacts/decorator_1641555617451/work
efficientnet==1.0.0
exceptiongroup==1.0.0
executing @ file:///home/conda/feedstock_root/build_artifacts/executing_1667317341051/work
flatbuffers==23.1.21
fonttools==4.38.0
gast==0.4.0
google-auth==2.16.1
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.51.1
h5py==3.8.0
idna==3.4
image-classifiers==1.0.0
imagecodecs==2023.1.23
importlib-metadata @ file:///home/conda/feedstock_root/build_artifacts/importlib-metadata_1672612343532/work
importlib-resources==5.12.0
iniconfig==1.1.1
ipykernel @ file:///D:/bld/ipykernel_1655369313836/work
ipython @ file:///D:/bld/ipython_1676047671725/work
jedi @ file:///home/conda/feedstock_root/build_artifacts/jedi_1669134318875/work
joblib==1.2.0
jupyter_client @ file:///home/conda/feedstock_root/build_artifacts/jupyter_client_1676579893731/work
jupyter_core @ file:///D:/bld/jupyter_core_1675110077853/work
keras==2.10.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.4
libclang==15.0.6.1
Markdown==3.4.1
MarkupSafe==2.1.2
matplotlib==3.7.0
matplotlib-inline @ file:///home/conda/feedstock_root/build_artifacts/matplotlib-inline_1660814786464/work
missingno==0.5.1
nest-asyncio @ file:///home/conda/feedstock_root/build_artifacts/nest-asyncio_1664684991461/work
numpy==1.21.0
oauthlib==3.2.2
opt-einsum==3.3.0
packaging @ file:///home/conda/feedstock_root/build_artifacts/packaging_1673482170163/work
pandas==1.5.3
parso @ file:///home/conda/feedstock_root/build_artifacts/parso_1638334955874/work
pickleshare @ file:///home/conda/feedstock_root/build_artifacts/pickleshare_1602536217715/work
Pillow==9.4.0
platformdirs @ file:///home/conda/feedstock_root/build_artifacts/platformdirs_1675735718929/work
pluggy==1.0.0
ply==3.11
prompt-toolkit @ file:///home/conda/feedstock_root/build_artifacts/prompt-toolkit_1670414775770/work
protobuf==3.19.6
psutil @ file:///C:/Windows/Temp/abs_b2c2fd7f-9fd5-4756-95ea-8aed74d0039flsd9qufz/croots/recipe/psutil_1656431277748/work
pure-eval @ file:///home/conda/feedstock_root/build_artifacts/pure_eval_1642875951954/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
Pygments @ file:///home/conda/feedstock_root/build_artifacts/pygments_1672682006896/work
pyparsing==3.0.9
pytest==7.2.0
python-dateutil @ file:///home/conda/feedstock_root/build_artifacts/python-dateutil_1626286286081/work
pytz==2022.7.1
pywin32==227
PyYAML==6.0
pyzmq @ file:///C:/ci/pyzmq_1657616005830/work
requests==2.28.2
requests-oauthlib==1.3.1
rsa==4.9
scikit-learn==1.2.1
scipy==1.4.1
seaborn==0.12.2
segmentation-models==1.0.1
six @ file:///home/conda/feedstock_root/build_artifacts/six_1620240208055/work
smop==0.41b0
stack-data @ file:///home/conda/feedstock_root/build_artifacts/stack_data_1669632077133/work
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow-estimator==2.10.0
tensorflow-gpu==2.10.0
tensorflow-io-gcs-filesystem==0.30.0
termcolor==2.2.0
threadpoolctl==3.1.0
tomli==2.0.1
tornado @ file:///D:/bld/tornado_1656937958156/work
traitlets @ file:///home/conda/feedstock_root/build_artifacts/traitlets_1675110562325/work
typing_extensions==4.5.0
urllib3==1.26.14
wcwidth @ file:///home/conda/feedstock_root/build_artifacts/wcwidth_1673864653149/work
Werkzeug==2.2.3
wincertstore==0.2
wrapt==1.14.1
zipp @ file:///home/conda/feedstock_root/build_artifacts/zipp_1676708471276/work
`

**Comment by Rishi-11-2** [comment]
You did not understand the setup.. I wasn't using cuda setup . Instead I was using tensorflow -directml plugin+ AMD GPU so as to enable Tensorflow to utilise the AMD GPU that came inbuilt with it . I did not had any CUDA SETUP installed also my laptop does not have any NVIDIA Drivers therefore I was using tensorflow -directml plugin for AMD GPU

**Comment by gaikwadrahul8** [comment]
Hi, @bakikocabasa, Good to hear that your issue got resolved

@Rishi-11-2, I completely understood your issue here,  it shouldn't give the error which is related with CUDA or CudnnRNN because you're using AMD GPU with Tensorflow -DirectML plugin so to confirm whether this issue is related with Tensorflow -DirectML Plugin or anything else I requested you to please run your code on Google Colab with GPU and share that notebook or gist file with me. Now could you please do it ? Thank you!

**Comment by shamer33** [comment]
I had the same issue with it incorrectly wanting to use CUDA for an LSTM model, when for all my previous models it's been fine - I have AMD GPU / DirectML / Windows11 on TF v2.12, and fixed it by changing: 
from keras.layers import LSTM
to:
from tensorflow.compat.v1.keras.layers import LSTM

**Comment by cminnoy** [comment]
HAving the same issue on AMD GPU using direct-ml. Seems LSTM doesn't work on AMD cards.

**Comment by Carter2565** [comment]
> I had the same issue with it incorrectly wanting to use CUDA for an LSTM model, when for all my previous models it's been fine - I have AMD GPU / DirectML / Windows11 on TF v2.12, and fixed it by changing: from keras.layers import LSTM to: from tensorflow.compat.v1.keras.layers import LSTM

Thanks so much! This is the problem I was having too. I plan to see if there is an issue on this repo with this and direct-ml-Plugin repo i plan to open one on both if i dont find one. I needed to use `tf.compat.v1.keras.layers.GRU(128, return_sequences=True)` rather than `keras.layers.GRU(128, return_sequences=True)` when defining my model:
```python
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=32, output_dim=64, input_length=32),
    tf.keras.layers.Bidirectional(tf.compat.v1.keras.layers.GRU(128, return_sequences=True)),
    tf.keras.layers.Dense(32, activation='softmax')
])
```

**Comment by mkchong0710** [comment]
> I had the same issue with it incorrectly wanting to use CUDA for an LSTM model, when for all my previous models it's been fine - I have AMD GPU / DirectML / Windows11 on TF v2.12, and fixed it by changing: from keras.layers import LSTM to: from tensorflow.compat.v1.keras.layers import LSTM

Thanks again!! was worried that couldn't run the RNN coding on TensorFlow with AMD GPU!
