### ISSUE TITLE
tensorflow 2.2 cnn training issue

### ISSUE THREAD

**Issue by akarshsoman** [tensorflow/tensorflow#58860]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

source

### Tensorflow Version

tf 2.2

### Custom Code

Yes

### OS Platform and Distribution

windows 10

### Python version

3.6

### CUDA/cuDNN version

10.1/7.6

### GPU model and memory

rtx 3070 and 8 gb memory

### Current Behaviour?

```shell
tensorflow training and validation accuracy remains at 0.5 in tensorflow-gpu 2.2 version, while in tensorflow 2.5 version it gives good training and validation accuracy. the training was done on cifar10 dataset. could you please explain why its performance decreases on tf 2.2 version
```

### Standalone code to reproduce the issue

```shell
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.datasets import cifar10

physical_devices = tf.config.list_physical_devices("GPU")
tf.config.experimental.set_memory_growth(physical_devices[0], True)

(x_train, y_train), (x_test, y_test) = cifar10.load_data()
x_train = x_train.astype("float32") / 255.0
x_test = x_test.astype("float32") / 255.0

model = keras.Sequential(
    [
        keras.Input(shape=(32, 32, 3)),
        layers.Conv2D(32, 3, padding="valid", activation="relu"),
        layers.MaxPooling2D(),
        layers.Conv2D(64, 3, activation="relu"),
        layers.MaxPooling2D(),
        layers.Conv2D(128, 3, activation="relu"),
        layers.Flatten(),
        layers.Dense(64, activation="relu"),
        layers.Dense(10),
    ]
)


def my_model():
    inputs = keras.Input(shape=(32, 32, 3))
    x = layers.Conv2D(32, 3)(inputs)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)
    x = layers.Conv2D(64, 3)(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.MaxPooling2D()(x)
    x = layers.Conv2D(128, 3)(x)
    x = layers.BatchNormalization()(x)
    x = keras.activations.relu(x)
    x = layers.Flatten()(x)
    x = layers.Dense(64, activation="relu")(x)
    outputs = layers.Dense(10)(x)
    model = keras.Model(inputs=inputs, outputs=outputs)
    return model


model = my_model()
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer=keras.optimizers.Adam(lr=3e-4),
    metrics=["accuracy"],
)

model.fit(x_train, y_train, batch_size=64, epochs=10, verbose=1)
```

### Relevant log output

```shell
fewfewfewf
```
</details>

**Comment by tiruk007** [comment]
@akarshsoman 
There might be a chance of having the bug in the TF v2.2 version, It's unlikely for the TF v2.2 version to receive any bug fixes except when we have security patches. it got fixed in the later version which is the TF2.5 version.Perhaps you can use the latest tf versions for your case. I was able to get expected output in TF v2.5 and TF v2.11. Please find the gist of it [here](https://colab.research.google.com/gist/tiruk007/7e4accb6202d63d154e39126c8ccf0ee/58860.ipynb) for reference.
Thank you!

**Comment by akarshsoman** [comment]
@tiruk007 the results look similar in google colab , my doubt is whether there is problem with tf 2.2 and rtx 30 series ?

**Comment by sushreebarsa** [comment]
@akarshsoman Could you please refer to [this](https://github.com/tensorflow/tensorflow/issues/59015#issuecomment-1365275972) comment and use the latest TF version for getting better results. 
TF 2.2 does not really contain all the changes to prevent code using invalid shapes from crashing the interpreter via CHECK-failures.  TF 2.2 is no longer supported. It's unlikely for TF 2.2 version to receive any bug fixes except when we have security patches. Please let us know if it is still an issue in the latest TF versions?

This issue seems to be Keras issue.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
