### ISSUE TITLE
Variables across different runners in TFLite and SavedModel

### ISSUE THREAD

**Issue by paulfd** [tensorflow/tensorflow#58886]
### System information

-   **Have I written custom code (as opposed to using a stock example script
    provided in TensorFlow)**: Yes
-   **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux CentOS 7
-   **Mobile device (e.g. iPhone 8, Pixel 2, Samsung Galaxy) if the issue
    happens on a mobile device**: No
-   **TensorFlow installed from (source or binary)**: Binary
-   **TensorFlow version (use command below)**: v2.11.0-rc2-17-gd5b57ca93e5
-   **Python version**: 3.9
-   **Bazel version (if compiling from source)**:
-   **GCC/Compiler version (if compiling from source)**:
-   **CUDA/cuDNN version**: Not used
-   **GPU model and memory**: Not used
-   **Exact command to reproduce**:

You can collect some of this information using our environment capture script:

https://github.com/tensorflow/tensorflow/tree/master/tools/tf_env_collect.sh

You can obtain the TensorFlow version with:

```bash
python -c "import tensorflow as tf; print(tf.version.GIT_VERSION, tf.version.VERSION)"
```

### Describe the problem
I am unsure if this is a bug or an expected behavior. I am trying to share `tf.Variable`s between signature runners in TFLite but it does not seem to work. Executing eagerly or with a SavedModel, things work as expected, but the TFLite export somehow flattens/prunes the graph and does not share the variables globally between the signature runners.

### Source code / logs

I prepared a minimal example here:

https://colab.research.google.com/drive/1DTau1na7YfzCWtRk8RC5KHVzZaNp7Tsx?usp=sharing

With TFLite my target is more C++ but the problem appears in Python too, and it was easier to share and test with Python.

**Comment by sushreebarsa** [comment]
@pjpratik I was able to replicate the issue, please find the [gist](https://colab.research.google.com/gist/sushreebarsa/8e6f30e7c3212141f87529169ef28cb1/tflite_variables_and_runners.ipynb#scrollTo=T3FzmJeSCKf2) here.
Thank you!

**Comment by pkgoogle** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The TFLite team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the TFLite space.
