### ISSUE TITLE
CollectiveOpV3Kernel did not support group assignments

### ISSUE THREAD

**Issue by MoFHeka** [tensorflow/tensorflow#58906]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Source

binary

### Tensorflow Version

tf 2.10

### Custom Code

No

### Current Behaviour?

```shell
CollectiveOpV3Kernel did not support group assignments, I need a all2all OP which could dispatch tensors with different shape like Horovod.
```

### Standalone code to reproduce the issue

```shell
import os

import tensorflow as tf
from tensorflow.python.ops import collective_ops

tf.config.experimental.set_memory_growth=True

group_size = 2
group_key = 104
device = 'GPU'
communication = 'auto'

dev0 = '/device:%s:0' % device
dev1 = '/device:%s:1' % device

@tf.function
def run_all_to_all_2devices():
  collectives = []
  in0 = tf.convert_to_tensor([1,1,1,1,3,3])
  in1 = tf.convert_to_tensor([2,2,2,4])
  with tf.device(dev0):
    group_handle0 = collective_ops.initialize_communicator(
        group_key=group_key,
        rank=0,
        group_size=group_size,
        communication_hint=communication)
    collectives.append(
        collective_ops.all_to_all_v3(group_handle0, in0, [0,4]))
  with tf.device(dev1):
    group_handle1 = collective_ops.initialize_communicator(
        group_key=group_key,
        rank=1,
        group_size=group_size,
        communication_hint=communication)
    collectives.append(
        collective_ops.all_to_all_v3(group_handle1, in1, [0,3]))
  return collectives

result = run_all_to_all_2devices()
print(result[0])
print(result[1])
```

### Relevant log output

```shell
UnimplementedError                        Traceback (most recent call last)
Cell In[6], line 32
     28     collectives.append(
     29         collective_ops.all_to_all_v3(group_handle1, in1, [0,3]))
     30   return collectives
---> 32 result = run_all_to_all_2devices()
     33 print(result[0])
     34 print(result[1])

File ~/.conda/envs/hj/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py:153, in filter_traceback.<locals>.error_handler(*args, **kwargs)
    151 except Exception as e:
    152   filtered_tb = _process_traceback_frames(e.__traceback__)
--> 153   raise e.with_traceback(filtered_tb) from None
    154 finally:
    155   del filtered_tb

File ~/.conda/envs/hj/lib/python3.8/site-packages/tensorflow/python/eager/execute.py:54, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     52 try:
     53   ctx.ensure_initialized()
---> 54   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     55                                       inputs, attrs, num_outputs)
     56 except core._NotOkStatusException as e:
     57   if name is not None:
...
	 [[CollectiveAllToAllV3_1/_11]]
  (1) UNIMPLEMENTED:  Group assignments are not supported yet.
	 [[{{node CollectiveAllToAllV3_1}}]]
0 successful operations.
0 derived errors ignored. [Op:__inference_run_all_to_all_2devices_39]
```
</details>

**Comment by mohantym** [comment]
Hi @MoFHeka !
Thanks for sharing your observations on CollectiveOps.

@SuryanarayanaY !
Could you look at this issue. Attached gist in [2.9](https://colab.research.google.com/gist/mohantym/a142bfe169c3c56570f6247f50882b21/git_58906.ipynb?authuser=1#scrollTo=wo-Y79ECUKuY), [2.10](https://colab.research.google.com/gist/mohantym/a138b10b3bc153223ff0a0a2c6b7f9f1/git_58906.ipynb?authuser=1#scrollTo=wo-Y79ECUKuY), [2.11 ](https://colab.research.google.com/gist/mohantym/9ec6672adf5308a5a7688a3258c0c67e/git_58906.ipynb?authuser=1#scrollTo=wo-Y79ECUKuY)and [nightly ](https://colab.research.google.com/gist/mohantym/ab49f3194aaab5169da327f310ae50b3/git_58906.ipynb?authuser=1#scrollTo=wo-Y79ECUKuY)for reference.

Thank you!

**Comment by MoFHeka** [comment]
When will the implementation of all2all OP be like the one in Horovod where the first dimension can be non-fixed?

**Comment by rainwoodman** [comment]
Hi @MoFHeka,

Thanks for the interest in the V3 Collectives. V3 Collectives was an experimental project, and remains unused inside TensorFlow (neither by tf.distribute nor by tf.experimental.dtensor), due to the additional Resource argument complicating the adoption. There is no plan from the TF side to enhance the V3 Collectives at this moment. 

In general TensorFlow's collectives do not work well with non-uniform shapes. The current call signature not taking displacement and size argument like MPI_Alltoallv of course doesn't help. Plumbing non-uniform shapes through all different backends (NCCL, and XLA) can get tricky. Could you elaborate your use case a bit more? Maybe we can come up with an acceptable workaround.

As for the group_assignment attribute: Even if it is implemented, it will not help much regarding the non-uniform shapes. The intention of the attribute was to allow sub-groups inside the current collective group. The semantics of group_assignment can be found in https://www.tensorflow.org/xla/operation_semantics#alltoall under the replica_groups attribute.

**Comment by MoFHeka** [comment]
All2All OP for Large-scale sparse parameter CTR model in multi-GPU distributed training is necessary....

**Comment by MoFHeka** [comment]
reopen this issue

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
