### ISSUE TITLE
Wrong layer name in exception message

### ISSUE THREAD

**Issue by MatthieuHernandez** [tensorflow/tensorflow#58926]
### Issue Type

Bug

### Tensorflow Version

tf 2.11.0

### Custom Code

Yes

### OS Platform and Distribution

Windows 11

### Python version

3.10.9

### Current Behaviour?

```shell
I have an error message that said:
`tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute Conv2D as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:Conv2D]`

But the error is on a keras.layers.Conv1D not on Conv2D.
I know how to solve this exception, but the message displayed is not correct.
```

### Standalone code to reproduce the issue

```py
import tensorflow as tf
import keras

model = tf.keras.models.Sequential([
    keras.layers.Input((5, 2)),
    keras.layers.Conv1D(filters=2, kernel_size=3)
])

model.layers[0].call(tf.ones(shape=(1, 3, 2), dtype=tf.int32))
```

**Comment by tiruk007** [comment]
@MatthieuHernandez 
I was able to reproduce the issue on colab using TF v2.11. Please find the gist [here](https://colab.research.google.com/gist/tiruk007/2b763013cedc7ac656bd6851670f0b35/untitled46.ipynb) for reference.
This issue seems to be keras issue.Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).
Thank you!
