### ISSUE TITLE
AutoCast variable inside tf.function does not cast correctly when saving a model

### ISSUE THREAD

**Issue by JustASquid** [tensorflow/tensorflow#58937]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

2.9.3

### Custom Code

Yes

### OS Platform and Distribution

Windows 10

### Python version

3.9

### Current Behaviour?

```shell
Error when calling model.save()

You can work around the error by commenting out `tf.function` over `call()`.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import keras
import keras.layers

class CosineSimilarityLayer(keras.layers.Layer):
    def __init__(
        self, num_classes: int, name: str = None
    ):
        super().__init__(name=name)
        self.num_classes = num_classes
        self._weights = None

    def build(self, input_shape):
        self._weights = self.add_weight(
            name="W",
            shape=(
                input_shape[-1],
                self.num_classes,
            ),
            initializer="glorot_normal",
            trainable=True,
            dtype=self.dtype
        )
        super().build(input_shape)

    def compute_output_shape(self):
        return None, self.num_classes

    # If you comment out tf.function here, it works.
    @tf.function
    def call(self, inputs: tf.Tensor):
        embedding = inputs
        # normalize feature
        embedding_normalized = tf.nn.l2_normalize(embedding, axis=1)
        # get centroids
        weights_normalized = tf.nn.l2_normalize(self._weights, axis=1, )

        logits = embedding_normalized @ weights_normalized

        return logits

    def get_config(self):
        config = super().get_config().copy()
        config.update(
            {
                "num_classes": self.num_classes,
            }
        )
        return config

def main():
    tf.keras.mixed_precision.set_global_policy("mixed_float16")

    layer = CosineSimilarityLayer(num_classes=100)

    input = tf.zeros(shape=(10, 100), dtype=tf.float16)

    model = keras.models.Sequential([
        layer
    ])

    model(input)

    model.save("autocast_issue")

if __name__ == "__main__":
    main()
```

### Relevant log output

```shell
File "*\autocast_issue.py", line 37, in call  *
        logits = embedding_normalized @ weights_normalized

    TypeError: Input 'b' of 'MatMul' Op has type float32 that does not match type float16 of argument 'a'.
```
</details>

**Comment by mohantym** [comment]
Hi @JustASquid !
I could replicate this issue in 2.9, 2.10 and  2.11.

@SuryanarayanaY !
Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/65e06da996e56e8e0a8e4f7780b36a7c/git_58937.ipynb#scrollTo=4EooDPFRb2qV), [2.10](https://colab.sandbox.google.com/gist/mohantym/c249816b76524de4872223130930e353/git_58937.ipynb#scrollTo=4EooDPFRb2qV) and [2.11](https://colab.sandbox.google.com/gist/mohantym/5b5c2291df32fa8e96cdc78502be35f5/git_58937.ipynb#scrollTo=zz978UmCj-p_) for reference.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @JustASquid ,

There is a limitation for this Policy as below as per [documentation](https://www.tensorflow.org/api_docs/python/tf/keras/mixed_precision/Policy#how_a_layer_uses_its_policys_compute_dtype).

> Currently, only tensors in the first argument to the layer's call method are casted (although this will likely be changed in a future minor release)

Since you passed first argument `input` as `float16` and second argument `weights_normalized` as `float32` the policy converted only first argument and second argument remains as it is and hence causing the Type Error. Hence I changed the second argument also suitable to argument mentioned in Policy `(float16)` and there is no Error. I even tried changing first argument from `float16` to `float32` and the Policy is able to convert it into `float16` and code executed without any error.Please refer to attached [gist-nightly-2.12V](https://colab.sandbox.google.com/gist/SuryanarayanaY/09963dbbb563c3089e3ac617336d73de/58937_r1-nightly.ipynb).

I hope this clarifies your query.Thank you!

**Comment by JustASquid** [comment]
@SuryanarayanaY I don't quite understand. The layer call function only has one argument. So the limitation specified in the documentation should not apply here.

**Comment by SuryanarayanaY** [comment]
@JustASquid ,
Yes the Policy applies to only First Argument to the layer call which converts first argument to `float16` but the the variable `weights_normalized` is of `float32` which is default dtype of TF and hence raising the `TypeError: Input 'b' of 'MatMul' Op has type float32 that does not match type float16 of argument 'a'`  in the operation `embedding_normalized @ weights_normalized`.
The error is not raised by the Policy.The Policy converted first argument dtype as intended.But the operation `embedding_normalized @ weights_normalized` not supports different dtypes for multiplication.Both the arguments should be of same type. Please also refer the [tensordot](embedding_normalized @ weights_normalized) API of Tensorflow regarding the same.

Hence you need to keep same dtypes for dot product which is the reason for the error but not Policy `tf.keras.mixed_precision.set_global_policy`.

Thankyou!

**Comment by JustASquid** [comment]
@SuryanarayanaY I think there is some confusion here. Under the mixed precision policy, the weights variable is created as type AutoCastVariable, which should automatically cast to float16 when it is multiplied with the float16 input tensor. See the implementation of the Dense layer for example, it relies on this in the same way when it multiplies the kernel.

**Comment by SuryanarayanaY** [comment]
@JustASquid ,

Thanks for pointing that. I dig more about Policy and Yes you are correct here.The weights variable should be autocasted to `Policy dtype` and it seems that it also happening during model.call(). I did inserted some print statements for debugging. I observed that when `call()` method wrapped with `@tf.function` during `model.save()` in last call during `model.save()` somehow returning `float32` result for `self.dtype` which might be causing the problem. Whereas without `@tf.function` wrapper all calls returning `float16` as result for `self.dtype`.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/474633d6ea8e15323060cc8a0a8615c9/58937_2-11.ipynb).

There seems some serialization problem here with `tf.function` as wrapper. We need to have a look here and I request you also try to locate the source of problem if possible.

Thank you!

**Comment by k-w-w** [comment]
@reedwm 

Reed, looks like there is a bit of an issue with tf.functions and AutocastVariable. When a function is traced under Keras (I'm guessing `enable_auto_cast_variables` is used somehwere), the variable is correctly converted to the expected dtype. But when a function is traced under core TF, there is no context, so the regular float32 value is used.

Is there a bug for this already?

**Comment by reedwm** [comment]
`enable_auto_cast_variables` [is called in `Layer.__call__`](https://github.com/keras-team/keras/blob/04a23bcf32f4a4957cf7db191619f1979c65fe5c/keras/engine/base_layer.py#L1142) so that AutoCastVariables are casted inside `Layer.call`.

When the error occurs during the `model.save()` call, I see the function being [re-traced here](https://github.com/tensorflow/tensorflow/blob/485d930a2a20decd9d8c77028f7e5c0ba54275dd/tensorflow/python/eager/polymorphic_function/polymorphic_function.py#L1168) in the stack trace. It is being re-traced outside `Layer.__call__` so the `enable_auto_cast_variables` scope is not in effect, causing the error. @k-w-w, do you know why it's being re-traced outside `Layer.__call__`? I'm not very familiar the `tf.function` part of the TF codebase.

Unfortunately we cannot always resolve AutocastVariables to the compute side inside tf.functions, because only layers have a compute type, not variables. It's intentional that variables are only casted when used inside `Layer.call`.

**Comment by k-w-w** [comment]
@reedwm It's being retraced because the function is labelled "tf.function". When the SavedModel code sees a tf.function, it will re-trace it in a blank context (for example, in case it was traced inside a distribution strategy. We don't want to save the distributed function). I'm not entirely sure what part of the cache key is changing in this case.

**Comment by tilakrayal** [comment]
@JustASquid,
I tried to execute the mentioned code on tensorflow v2.17 which contains Keras3.0 by default, and observed the code was executed without any issue/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0e4e839060929b5054392dd4622a4710/untitled2234.ipynb). Thank you!
