### ISSUE TITLE
Clog Copy-Paste Error

### ISSUE THREAD

**Issue by alexbeattie42** [tensorflow/tensorflow#58943]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

master

### Custom Code

No

### OS Platform and Distribution

Any

### Current Behaviour?

In [workspace2.bzl](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace2.bzl#L162) on line 162 clog was copy and pasted from cpu-info (below it) so both import the same archive and clog is not included.

```bash
    tf_http_archive(
        name = "clog",
        strip_prefix = "cpuinfo-5e63739504f0f8e18e941bd63b2d6d42536c7d90",
        sha256 = "18eca9bc8d9c4ce5496d0d2be9f456d55cbbb5f0639a551ce9c8bac2e84d85fe",
        urls = tf_mirror_urls("https://github.com/pytorch/cpuinfo/archive/5e63739504f0f8e18e941bd63b2d6d42536c7d90.tar.gz"),
    )

    tf_http_archive(
        name = "cpuinfo",
        strip_prefix = "cpuinfo-5e63739504f0f8e18e941bd63b2d6d42536c7d90",
        sha256 = "18eca9bc8d9c4ce5496d0d2be9f456d55cbbb5f0639a551ce9c8bac2e84d85fe",
        urls = tf_mirror_urls("https://github.com/pytorch/cpuinfo/archive/5e63739504f0f8e18e941bd63b2d6d42536c7d90.tar.gz"),
    )
```

### Standalone code to reproduce the issue

```shell
View master branch
```

### Relevant log output

_No response_</details>

**Comment by sachinprasadhs** [comment]
Hi, I think the issue has been taken care with the fix https://github.com/tensorflow/tensorflow/commit/d90b6bc733db5a78ae28b815495391e6715d4ac2 which removed clog section and kept only `cpuinfo` as below.
https://github.com/tensorflow/tensorflow/blob/d90b6bc733db5a78ae28b815495391e6715d4ac2/tensorflow/workspace2.bzl#L162-L167.
Could you please close this issue, if you think your issue is addressed. Thanks!
