### ISSUE TITLE
NOT_FOUND: could not find registered platform with id

### ISSUE THREAD

**Issue by vandit2209** [tensorflow/tensorflow#58988]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

source

### Tensorflow Version

tf 2.11.0

### Custom Code

Yes

### OS Platform and Distribution

MacOS Ventura

### Python version

3.10

### GCC/Compiler version

12.2.0

### CUDA/cuDNN version

NA

### GPU model and memory

M1 Mac, 8 GB

### Current Behaviour?

```shell
2022-12-23 01:31:15.756543: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:114] Plugin optimizer for device_type GPU is enabled.
2022-12-23 01:31:17.330784: W tensorflow/core/framework/op_kernel.cc:1830] OP_REQUIRES failed at xla_ops.cc:418 : NOT_FOUND: could not find registered platform with id: 0x12ff97980


Error:
                             Traceback (most recent call last)
Cell In[42], line 1
----> 1 hist = model.fit(train, epochs=20, validation_data=val, callbacks=[tensorboard_callback])

File /opt/homebrew/lib/python3.10/site-packages/keras/utils/traceback_utils.py:70, in filter_traceback.<locals>.error_handler(*args, **kwargs)
     67     filtered_tb = _process_traceback_frames(e.__traceback__)
     68     # To get the full stack trace, call:
     69     # `tf.debugging.disable_traceback_filtering()`
---> 70     raise e.with_traceback(filtered_tb) from None
     71 finally:
     72     del filtered_tb

File /opt/homebrew/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:52, in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     50 try:
     51   ctx.ensure_initialized()
---> 52   tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
     53                                       inputs, attrs, num_outputs)
     54 except core._NotOkStatusException as e:
     55   if name is not None:

NotFoundError: Graph execution error:
```

### Standalone code to reproduce the issue

```shell
[Link to pdf](https://github.com/nicknochnack/ImageClassification/blob/main/Getting%20Started.ipynb)

The code and files needed are same required here
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @vandit2209 !
Could you share the notebook as Colab gist. I am not able to access the dataset and getting error here.

`data_iterator = data.as_numpy_iterator()
`

Thank you!

**Comment by vandit2209** [comment]
Hi @mohantym,
The data folder is in the [repo](https://github.com/nicknochnack/ImageClassification). Kindly find the data folder attached there.

**Comment by mohantym** [comment]
Hi @vandit2209 !
I could replicate this issue with 2.11 tensorflow-macos and metal plug in instruction. 

@SuryanarayanaY !
Could you look at this issue .

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @vandit2209 ,

TF2.11 V officially supports X_code version of 10.14 as per tested [configurations](https://www.tensorflow.org/install/source#cpu_2).There are couple of issues related to your issues Ref - [58453](https://github.com/tensorflow/tensorflow/issues/58453),  [58368](https://github.com/tensorflow/tensorflow/issues/58368).
Already Developer Team looking to update TF to work with latest X_code versions in above issues.
But till then we can test on tested configurations only.

Could you please try and confirm if it works with tested configuration of X_code (10.14).

Thankyou!

**Comment by vandit2209** [comment]
Hi @SuryanarayanaY ,
I have X_code version of 14.2, and I have symlinked brew installed GCC in my OS.
```
gcc --version
gcc (Homebrew GCC 12.2.0) 12.2.0
```
does this impact my issue in a different manner?

**Comment by SuryanarayanaY** [comment]
Hi @vandit2209 ,

Could you confirm whether you configured the build for GPU support ? SInce you mentioned GPU model i have to ask it as there is no GPU support for MacOS. Also can you please confirm the Bazel version you used ?
Have you gone through the issues mentioned in above [comment](https://github.com/tensorflow/tensorflow/issues/58988#issuecomment-1365254444) ?

Thankyou!

**Comment by ewtang** [comment]
Please check this: https://developer.apple.com/forums/thread/722389

**Comment by dickreuter** [comment]
the issue is definitely not yet fixed. Only way to run tensorflow on a mac is:
python -m pip install tensorflow-macos==2.9 
python -m pip install tensorflow-metal==0.5.0

**Comment by pkstys** [comment]
Thanks for this, you are absolutely correct, the only way I could get TF2 to run on my new M1 MacStudio is by installing the versions you mention. But my enthusiasm quickly waned when I benchmarked a fairly simple neural network using Keras:
Exec time on an old Intel core i5 iMac (cpu only): 13 min
Exec time on a brand new tricked out M1 MacStudio (activity monitor confirmed that GPU was running at close to 100% the whole time): 106 min
So either I'm doing something very wrong (exact same python script) or these libraries, tho functional, are seriously faulty.

**Comment by beyarkay** [comment]
@SuryanarayanaY Could you please re-open this issue, as the problem is not fixed. I'm having the same issue on a fresh install of tensorflow in a virtual environment

**Comment by SuryanarayanaY** [comment]
@beyarkay ,

Could you please confirm whether you are using `tensorflow` or `tensorflow-macos` with metal plugin ??  

Please make a note that `tensorflow-macos` currently maintained by Apple itself and you can refer [comment-1415995774](https://github.com/tensorflow/tensorflow/issues/58988#issuecomment-1415995774) for discussion on same in Apple forum.

One of the reason might be using new optimizers which seems not yet supported in `tensorflow-macos`. Probable solution might be using [legacy](https://www.tensorflow.org/api_docs/python/tf/keras/optimizers/legacy) optimizers or downgrading to versions <=2.9 for now until it gets fixed.

Please try these steps and come back if this is still causing the error

**Comment by beyarkay** [comment]
Hi there, yes I am using the Apple supported tf-metal and  tf-macos, and I did manage to fix the issue by downgrading, although I'd like to be on the most up-to-date TF if possible. Am I right in understanding that this is an issue on Apple's side, rather than with TF?

**Comment by SuryanarayanaY** [comment]
@beyarkay ,

I personally tested the following code with latest tensorflow-macos and encountered the reported error.

```
import tensorflow as tf

cifar = tf.keras.datasets.cifar100
(x_train, y_train), (x_test, y_test) = cifar.load_data()
model = tf.keras.applications.ResNet50(
    include_top=True,
    weights=None,
    input_shape=(32, 32, 3),
    classes=100,)

loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
model.compile(optimizer="adam", loss=loss_fn, metrics=["accuracy"])
model.fit(x_train, y_train, epochs=5, batch_size=64)
```
I have changed the optimizer to legacy version by changing the model.compile() like below and its working with latest version also.

`model.compile(optimizer=tf.keras.optimizers.legacy.Adam(), loss=loss_fn, metrics=["accuracy"])`

Please refer to attached log below.

[# Testing tensorflow-macos(2.11v).txt](https://github.com/tensorflow/tensorflow/files/11077747/Testing.tensorflow-macos.2.11v.txt)

Yes, tensorflow-macos is maintained by Apple and this issue might be fixed by them. But I believe this issue already under their attention and efforts are also in place from our side to fix the issue at earliest.Till then the above recommendation shall work fine.

**Comment by pkstys** [comment]
I cannot even install tensorflow-macos

python3.10 -m pip install tensorflow-macos
ERROR: Could not find a version that satisfies the requirement tensorflow-macos (from versions: none)
ERROR: No matching distribution found for tensorflow-macos

And when I just install tensorflow merely importing it crashes the kernel.

p

**Comment by w-i-l** [comment]
Had the same issue on a `M2 PRO` using the tensorflow. 

I have tried so many things, but from what I have tested I found that in order to make it work you will need to:
- create a new conda environment with `python 3.9` (I have tried other versions too, but it seems that only this specific one works)
- install the dependicies `pip install tensorflow-macos==2.9; pip install tensorflow-metal==0.5.0` - also those only versions seem to work
- don't use directly strings for optimizers or loss, instead use them from `tf.keras.optimizers`, `tf.keras.losses`, respectively
- (this one is optional, and can trigger other error) - for classes use `int`s instead of `string`s
- **!!!! VERY IMPORTANT !!!!** - the `2.9 version` needs a specific order for execution, which translates to having the `build` after `compile` method and before `summary`, `fit` commands.

The last point will look something like this:

```python

model = generate_model(classes)

model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
            loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
            metrics=['accuracy'])
    
model.build(input_shape=(None, IMAGE_SIZE, IMAGE_SIZE, 1))
model.summary()

try:
    model.fit(train_dataset, epochs=10, validation_data=validation_dataset)
except KeyboardInterrupt:
    print("Training interrupted")
```

**Comment by w-i-l** [comment]
If the above doesn't work from the first try

Install the latest versions, and then downgrade them, this way should 100% do the job
