### ISSUE TITLE
Windows C API package is missing files

### ISSUE THREAD

**Issue by AlexSnail124** [tensorflow/tensorflow#58985]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Source

binary

### Tensorflow Version

libtensorflow-cpu-windows-x86_64-2.11.0.zip

### Custom Code

No

### OS Platform and Distribution

MS Windows 10

### Current Behaviour?

```shell
The Windows C API install package for CPU only (libtensorflow-cpu-windows-x86_64-2.11.0.zip) is missing some files.
I saw issue #31567 so tried copying the missing files from the equivalent Linux package and it seems to work as
I am able to build and run my application.

The missing files are:
include/tensorflow/tf_buffer.h
include/tsl (whole folder is missing)
```

### Standalone code to reproduce the issue

```shell
To test the set-up I am using this project:
https://github.com/serizba/cppflow/tree/master/examples/tensor
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @AlexSnail124 !

Thanks for work on  windows c wheel. 
Could your raise a PR for the review.

Thank you!

**Comment by AlexSnail124** [comment]
Hi Manas

I think you're suggesting I submit a change for review to fix this issue. I
had originally thought I was just submitting a ticket for someone else to
fix (maybe you).

I'm happy to give it a go at fixing it though. I am a professional
software engineer but am new to github and open source contribution.

Can you point me to the right area that controls how the build packages are
put together? The more specific the better. And I'll work out the rest.

Thanks
Alex

**Comment by sachinprasadhs** [comment]
Hi, Do you think this could be due to the changes made here https://github.com/tensorflow/tensorflow/commit/843cede83294063f88bf17097c2a446db70d9617, changes mainly reflecting on the header file `tf_buffer.h`.
I can also see buffer file which is created at the location [tensorflow/c/tf_buffer.h](https://github.com/tensorflow/tensorflow/commit/843cede83294063f88bf17097c2a446db70d9617#diff-c8c2391971d266b98470913ff25be76ef4777202e637ba79a92bed4e96635ba9).

Let me know if you have any further question s on the dependency to work with. Thanks!
