### ISSUE TITLE
Crash when running tensorflow.python.ops.collective_ops.all_gather

### ISSUE THREAD

**Issue by cse19922021** [tensorflow/tensorflow#59004]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Source

binary

### Tensorflow Version

v2.4.0

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.4

### Python version

3.8

### CUDA/cuDNN version

release 11.0, V11.0.194 Build cuda_11.0_bu.TC445_37.28540450_0

### Current Behaviour?

```shell
If tensorflow.python.ops.collective_ops.all_gather is given input t with rank other than 1, it results in crash.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
from tensorflow.python.ops import collective_ops
try:
  arg_0_tensor = tf.random.uniform([], dtype=tf.float32)
  arg_0 = tf.identity(arg_0_tensor)
  arg_1 = 1
  arg_2 = 100
  arg_3 = 100
  communication_hint = "RING"
collective_ops.all_gather(arg_0,arg_1,arg_2,arg_3,communication_hint=communication_hint,)
except Exception as e:
  print("Error:"+str(e))
```

### Relevant log output

```shell
Aborted (core dumped)
```
</details>

**Comment by tiruk007** [comment]
I was able to execute the given code without a session crash or Aborted(core dumped) on Colab using TF v2.11. Could you please try with the latest version which is TF v2.11 and also v2.4 is pretty old, There is a high possibility that this was fixed with later TF versions.
Please find the gist [here](https://colab.research.google.com/gist/tiruk007/eef574578cdd3c714f92cde8c2f0a8c3/untitled52.ipynb) for reference and let us know if it helps.
Thank you!

**Comment by mihaimaruseac** [comment]
This seems invalid. Affected version is old, out of support.
