### ISSUE TITLE
[help wanted] tf.strings.operations raises TypeError: Value passed to parameter 'input' has DataType string not in list of allowed

### ISSUE THREAD

**Issue by maifeeulasad** [tensorflow/tensorflow#59035]
I'm just trying to create a superficial layer to pre-process data inside models. Here is an my Layer:
```
class StringLayer(tf.keras.layers.Layer):
  def __init__(self):
    super(StringLayer, self).__init__()

  def call(self, inputs):
    return tf.strings.join([some_python_function(word) for word in tf.strings.split(tf.strings.as_string(inputs), sep=" " )], separator=" ")
    
  

#model = tf.keras.models.Sequential()
#model.add(tf.keras.Input(shape=(1,), dtype=tf.string))
#model.add(StringLayer())
```

But it keeps giving me: **`TypeError: Value passed to parameter 'input' has DataType string not in list of allowed values: float32, float64, int32, uint8, int16, int8, int64, bfloat16, uint16, float16, uint32, uint64, complex64, complex128, bool, variant`**

*I know I can do this thing out of the model, but my main goal is to somehow do this inside the model; this way, I'll be able to maximize the GPU utilization.*

**Comment by tiruk007** [comment]
@maifeeulasad 
Could you please fill the issue [template](https://github.com/tensorflow/tensorflow/issues/new/choose) and provide complete code to replicate the issue reported here.
Thank you!

**Comment by maifeeulasad** [comment]
@tiruk007 this is not an issue; this is more like a 'coding help needed' thread.

Any help is highly appreciated for version ` > tf-2.6`

**Comment by SuryanarayanaY** [comment]
Hi @maifeeulasad ,
Iam not sure your exact requirement.Providing more context may be helpful for us to understand your requirement.

AFAIK The error might be due to that `tf.keras.Input()` won't accept `string` dtypes. Could you please refer this alternative [Tutorial](https://www.tensorflow.org/tutorials/load_data/text) related to text and let us know if it helps.

Thankyou !

**Comment by maifeeulasad** [comment]
Sometimes we have models trained with special kinds of data, let say for example:
 - cased
 - uncased

And it's well known that cased models don't go well with an uncased dataset and vice versa. Now we can certainly pre-process.

But I want to achieve this inside `tf.keras.Model`, as I may use different models parallelly. Changing the case is one thing, but I was looking forward to something more generic. Then we will be able to unlock the next level.

This is why I'm looking for some approach where I can iterate `tf.string` and modify it.

**Comment by SuryanarayanaY** [comment]
Hi @maifeeulasad ,
The requested feature may not be possible inside the Model.However your intention is to use GPU you can use the context of tf.device('GPU') like below where the code within this context runs under GPU.

```
with tf.device('GPU'):
    model = tf.keras.models.Sequential()
    model.add(tf.keras.Input(shape=(1,), dtype=tf.string))
    model.add(StringLayer())
```

**Comment by maifeeulasad** [comment]
Surely it's do able, as much as I can think.

Here is my most updated code:
```
@tf.function
def mapp(string):
    return tf.strings.lower(string)

class StringLayer(tf.keras.layers.Layer):

    def __init__(self, seperator = " "):
        super(StringLayer, self).__init__()
        self.seperator = seperator

    def call(self, inputs):
        splits = tf.strings.split(inputs, sep=self.seperator)
        mapped = tf.map_fn(mapp,splits)
        joined = tf.strings.reduce_join(mapped, axis=2, separator=self.seperator)
        return joined
```

Let me explain what it does:
 - `tf.strings.split(inputs, sep=self.seperator)` simply splits the Tensor
 - Then we can map over it, like `tf.map_fn(mapp,splits)` (**This is where I needed help**)
 - `tf.strings.reduce_join(mapped, axis=2, separator=self.seperator)`, we join back the RaggedTensor into one for further


Now I can lower case, or upper case, or some predefined function. But I was trying to make it pure generic, so that we could do anything. Like:
 - stemming
 - lemmatization
Just think about the possibilities.

Currently reading: https://github.com/tensorflow/tensorflow/blob/b2755d85dbf99a6d3cf6ffd92e358377e3c46652/tensorflow/python/ops/string_ops.py

There is a layer called `Rescaling`, which is used quite a lot nowadays in CV problems. No one wants to preprocess and feed it to model; maybe the preprocessing function will have slight variation, and it will/may impact the outcome. So why don't we add it to the model? I'm also trying to move forward with this vision. *Not sure if it is the best approach or not.*

Pinging @SuryanarayanaY

**Comment by SuryanarayanaY** [comment]
@maifeeulasad ,
It seems some of the strings Ops not working inside models.For example `tf.strings.split()` not working with model whereas `tf.strings.lower()` working fine which might be due to difference in implementation for reasons unknown to me.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/676ecfe3ff180fd7422899b9c3347614/59035.ipynb).

Thank you!

**Comment by maifeeulasad** [comment]
@SuryanarayanaY nice observation. 💯 

And I don't think that this issue should be marked as stalled and closed later on. This is a great feature to work on. 🤓

**Comment by SuryanarayanaY** [comment]
@maifeeulasad ,The issue escalated to concern developer as a potential feature request.Thanks!

**Comment by maifeeulasad** [comment]
@SuryanarayanaY okay. 🍺

I'm available to participate in any brain storming session. And if you think I can implement, or contribute with team. Just let me know.

Regards.

**Comment by Rexblk81** [comment]
I like to bring you to my project wrist watch neural interface..

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
