### ISSUE TITLE
TensorListScatterV2 fail to support gradient computation

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#59099]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf2.11, tf2.12.0-dev20230104

### Custom Code

Yes

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.9

### Current Behaviour?

```shell
Computing gradient for `tf.raw_ops.TensorListScatterV2` fails with error `Cannot convert 1 to EagerTensor of dtype variant`. According to [tf.raw_ops](https://www.tensorflow.org/api_docs/python/tf/raw_ops) documentation, the operator `TensorListScatterV2` has gradient.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
input_tensor = tf.constant([[1.0, 2.0], [3.0, 4.0]])
indices = [[0], [1]]
element_shape = [2]
num_elements = 2
output_tensor = tf.raw_ops.TensorListScatterV2(tensor=input_tensor, indices=indices, element_shape=element_shape, num_elements=num_elements)
print(output_tensor) # OK

with tf.GradientTape() as tape:
    tape.watch(input_tensor)
    output_tensor = tf.raw_ops.TensorListScatterV2(tensor=input_tensor, indices=indices, element_shape=element_shape, num_elements=num_elements)
print(tape.gradient(output_tensor, input_tensor)) # Cannot convert 1 to EagerTensor of dtype variant
```

### Relevant log output

```shell
tf.Tensor(<TensorList>, shape=(), dtype=variant)
TypeError: Cannot convert 1 to EagerTensor of dtype variant
```
</details>

**Comment by mohantym** [comment]
Hi @trickiwoo !
Thanks for sharing your observations on TensorListScatterV2.

@SuryanarayanaY !
Could you look at this issue. Attached gist in [2.9](https://colab.sandbox.google.com/gist/mohantym/085e0e959fa1926b761c8731a9f4150c/git_59099.ipynb), [2.10](https://colab.sandbox.google.com/gist/mohantym/601490206d0121c02b9d9ac20fa4eb15/git_59099.ipynb) and[ 2.11](https://colab.sandbox.google.com/gist/mohantym/c5855189f17005c0af0f7e58bb2054fb/git_59099.ipynb#scrollTo=bigVLxRlX8Qb).

Thank you!

**Comment by Gopi-Uppari** [comment]
Hi @trickiwoo,

I tried to execute the mentioned code with tf.2.17.1 version and observed that facing the same error. I suspect the error occurs, because `tf.raw_ops.TensorListScatterV2` outputs a tensor of type `variant`, which is not compatible with TensorFlow's automatic differentiation system. 

To resolve this issue, can you try to use the `tf.tensor_scatter_nd_update()` instead. This operation allows you to update specific parts of a tensor based on given indices and  it is fully compatible with gradient computations.

Could you please refer to this [gist](https://colab.research.google.com/gist/Gopi-Uppari/f526dbe0f835a29706e5d5e8fe51a3f5/tf_issue_59099.ipynb)

Thank you.
