### ISSUE TITLE
tf.Print does not work on embedding gradients

### ISSUE THREAD

**Issue by wchan** [tensorflow/tensorflow#591]
Is this expected? because an embedding gradient is an IndexedSlices rather than a Tensor.

**Comment by ebrevdo** [comment]
You can pass the indices and values to print separately.

**Comment by girving** [comment]
Seems like a reasonable feature to have.

**Comment by Mistobaan** [comment]
What would be a minimal code example, and what would be the desired outcome ?

**Comment by girving** [comment]
@Mistobaan: Not sure what you mean by a minimal code example.  The desired behavior would be that `tf.Print(input, data)` works even if `data` contains a mix of `IndexedSlices` objects and things that can be converted to tensors, and the desired outcome would be output that looks something like

    # tf.Print(_, [xs, IndexedSlices(ys, zs)])
    ... [x...] IndexedSlices([y...], [z...])

Since it would be nice if the new functionality allowed `Tensor` and `IndexedSlices` to be mixed in the same call to `Print`, the best way to implement it might be to add an optional list of extra strings to `Print`, perhaps as a "extras: list(string) = []" attr.  The above would then be implemented in Python as something like

    gen_logging_ops._print(_, [xs, ys, zs], prefixes=["", "IndexedSlices(", ", ", ")"])

inside the Python wrapper version in `tf.Print`.

**Comment by sesse** [comment]
Hi,

I tried this today; I didn't have any problems printing out an IndexedSlices object, or even a tensor and an IndexedSlices together (the IndexedSlices is converted to a tensor before printing). So I would suppose this is fixed in the meantime; feel free to reopen with more information if it still doesn't work for you.
