### ISSUE TITLE
Unexpected behaviour for save load dataset

### ISSUE THREAD

**Issue by tiamilani** [tensorflow/tensorflow#59186]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12.0-dev20230109

### Custom Code

Yes

### Current Behaviour?

```shell
Unexpected behaviour of the save and load function for datasets.
After saving for the first time a dataset I can load it from the disk without problems, modify the dataset as I please and then expect to be able to overwrite the previous dataset on the disk.
Currently, I'm able to save the second time the modified dataset but when I retrieve it from memory the object retrieved contains only the variation that happened before.
This is not what I expect from a 'save' and 'load' function, I should be able to retrieve from the disk an exact copy of what I'm saving.
```

### Standalone code to reproduce the issue

```shell
Colab link: https://colab.research.google.com/drive/1Mw2w6hmHgmORoTipboGCvBMkOv5JCMAu?usp=sharing

In short:
import tensorflow as tf
path="test-save"
tmp_dst_1 = tf.data.Dataset.from_tensor_slices(tf.ones([4, 10, 3, 1]))
tmp_dst_0 = tf.data.Dataset.from_tensor_slices(tf.zeros([4, 20, 3, 1]))
print([elem.shape for elem in tmp_dst_1])
print([elem.shape for elem in tmp_dst_0])
>>> [TensorShape([10, 3, 1]), TensorShape([10, 3, 1]), TensorShape([10, 3, 1]), TensorShape([10, 3, 1])]
>>> [TensorShape([20, 3, 1]), TensorShape([20, 3, 1]), TensorShape([20, 3, 1]), TensorShape([20, 3, 1])]

tmp_dst_1.save(path+"/dst_folder")
from_disk_dst_1 = tf.data.Dataset.load(path+"/dst_folder")
print([elem.shape for elem in from_disk_dst_1])
>>> [TensorShape([10, 3, 1]), TensorShape([10, 3, 1]), TensorShape([10, 3, 1]), TensorShape([10, 3, 1])]

from_disk_dst_1 = from_disk_dst_1.concatenate(tmp_dst_0)
print([elem.shape for elem in from_disk_dst_1])
>>> [TensorShape([10, 3, 1]), TensorShape([10, 3, 1]), TensorShape([10, 3, 1]), TensorShape([10, 3, 1]), TensorShape([20, 3, 1]), TensorShape([20, 3, 1]), TensorShape([20, 3, 1]), TensorShape([20, 3, 1])]
from_disk_dst_1.save(path+"/dst_folder")

from_disk_new_dst = tf.data.Dataset.load(path+"/dst_folder")
print([elem.shape for elem in from_disk_new_dst])
>>> [TensorShape([20, 3, 1]), TensorShape([20, 3, 1]), TensorShape([20, 3, 1]), TensorShape([20, 3, 1])]
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@sushreebarsa 
I was able to reproduce the issue on Colab using TF v2.11 and Tf-nightly-2.12.0.dev20230110. Please find the gist of [TF_v2.11](https://colab.research.google.com/gist/tiruk007/a6e3395023bac8d856362a9c794f1d96/59186.ipynb) and [Tf-nightly-2.12.0.dev20230110](https://colab.research.google.com/gist/tiruk007/ee69d160e8c2deab373b484bb9482c8e/59186_tf-nightly.ipynb) for reference.
Thank you!

**Comment by tiamilani** [comment]
Thanks @tiruk007 for the feedback.
On the google colab link that I shared, there is a possible workaround to the problem. Make a copy of the dataset with a generator before saving it.
I'm not a TensorFlow expert, but, could it be that the cause of this issue is that the save operation only saves the graph operations applied to the dataset? and doing this misses the initial state of the dataset that has been loaded from the disk?

Thanks

**Comment by Rishikesh2338** [comment]
Can you please assign me this work.

**Comment by gaikwadrahul8** [comment]
Hi, @tiamilani 

Apologize for the delay and I was able to replicate the issue without any unexpected behaviour for save and load dataset and it's working fine as expected, for your reference I have added [gist file ](https://colab.research.google.com/gist/gaikwadrahul8/038514e9d1f5508d09e5b2e6b0ae2a43/-59186.ipynb) so please give it try from your end and let us know whether is it resolving your issue or not ?

If issue still persists please let us know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by tiamilani** [comment]
There is an error in your gist_file.
On the last block, you should try to print what you have loaded from the memory, not the variable that you saved in memory.
Should be `print([elem.shape for elem in from_disk_result])` not `print([elem.shape for elem in result_concat])`
Also, I saved the result after the concatenation in my code.

As I was saying before, could it be that save and load only takes into consideration the graph operation applied to the dataset? and for this reason, misses the initial state of the dataset that has been loaded.
Could you please confirm or better explain my doubt?

Thanks for taking charge of this issue.

**Comment by gaikwadrahul8** [comment]
Hi, @tiamilani 

Apologize for the delayed response and I was able to replicate the same issue and It seems like working fine as expected, for your reference I have added [gist-file](https://colab.research.google.com/gist/gaikwadrahul8/14b4e5f6617861d43a715c29eb54dba5/-59186-testing.ipynb) and let me try to explain you the issue, after concatenation by using this line `from_disk_dst_1 = from_disk_dst_1.concatenate(tmp_dst_0)` and we have saved the result in `from_disk_dst_1` with this line `from_disk_dst_1.save(path+"/dst_folder")` after concatenation dataset is available in `from_disk_dst_1` so we should load and iterate over `from_disk_dst_1` not from `from_disk_new_dst` It's correct way to do it.

I would like to inform you that [tf.data](https://www.tensorflow.org/api_docs/python/tf/data) builds a [tf.Graph](https://www.tensorflow.org/api_docs/python/tf/Graph) internally, A TensorFlow computation, represented as a dataflow graph and it seems like due to which initial state of the dataset missing because we're not performing any graph operation.

If I have missed something here, please let me know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by tiamilani** [comment]
Hi gaikwadrahul8,Thanks for your kind replay and explanation.But I think that we are not on the same line.The whole point of the issue that I opened is that when I save a dataset on the disk I expect that loading it from the disk I obtain the exactly same dataset.If you print the same object on which you applied the save operation you are not proving that “what you load is what you have saved” you are simply showing again the same object.On the opposite, if you want to prove that “what you load is equal to what you save” you should try to print what you have loaded so ‘ from_disk_new_dst‘.The output of the concatenate operation is stored in ‘from_disk_dst_1’, once you save this dataset and load it in ‘from_disk_new_dst‘ then I expect that ‘from_disk_dst_1 ==  from_disk_new_dst‘ should be True. Which is not the case.Please let me know if now it’s clear why you shluld check the output of ‘from_disk_new_dst‘ and not ‘from_disk_dst_1‘ otherwise I’ll provide you a different example.Il giorno 3 mar 2023, alle ore 15:11, gaikwadrahul8 ***@***.***> ha scritto:﻿
Hi, @tiamilani
Apologize for the delayed response and I was able to replicate the same issue and It seems like working fine as expected, for your reference I have added gist-file and let me try to explain you the issue, after concatenation by using this line from_disk_dst_1 = from_disk_dst_1.concatenate(tmp_dst_0) and we have saved the result in from_disk_dst_1 with this line from_disk_dst_1.save(path+"/dst_folder") after concatenation dataset is available in from_disk_dst_1 so we should load and iterate over from_disk_dst_1 not from from_disk_new_dst It's correct way to do it.
I would like to inform you that tf.data builds a tf.Graph internally, A TensorFlow computation, represented as a dataflow graph and it seems like due to which initial state of the dataset missing because we're not performing any graph operation.
If I have missed something here, please let me know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by tiamilani** [comment]
Hi @gaikwadrahul8,

Sorry for the delay in my replay.
So, just to check if I understood correctly the process, what happens is the following:
- At the first `save()` operation a `shard` is created, _shard1_, with the dataset 
- Then the `load()` operation loads in memory this `shard` (_shard1_) and the dataset loaded is the same as the one saved
- The `concatenate()` operation modifies the dataset that has been loaded in memory from _shard1_
- Applying the `save()` operation then saves a second `shard`, _shard2_, that contains only the last part
- Using again the `load()` operation loads only the latest `shard` that is _shard2_

Does this make sense?

looking into the documentation, is possible to pass a method as `reader_func` should I write here a method that merges all the shards to obtain the desired output?

Best regards,
tiamilani
