### ISSUE TITLE
Check failure when running tensorflow.python.ops.gen_nn_ops.max_pool

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59197]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
Check failure.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_nn_ops
try:
  arg_0_tensor = tf.random.uniform([1, 10, 14, 1], dtype=tf.float32)
  arg_0 = tf.identity(arg_0_tensor)
  ksize_0 = 1
  ksize_1 = 0
  ksize_2 = 3
  ksize_3 = 1
  ksize = [ksize_0,ksize_1,ksize_2,ksize_3,]
  strides_0 = 1
  strides_1 = 2
  strides_2 = 2
  strides_3 = 1
  strides = [strides_0,strides_1,strides_2,strides_3,]
  padding = "VALID"
  explicit_paddings = []
  data_format = "NHWC"
  out = gen_nn_ops.max_pool(arg_0,ksize=ksize,strides=strides,padding=padding,explicit_paddings=explicit_paddings,data_format=data_format,)
except Exception as e:
  print("Error:"+str(e))
```

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_nn_ops
try:
  arg_0_tensor = tf.random.uniform([1, 6, 8, 1], dtype=tf.float32)
  arg_0 = tf.identity(arg_0_tensor)
  ksize_0 = 1
  ksize_1 = -52.0
  ksize_2 = 2
  ksize_3 = 1
  ksize = [ksize_0,ksize_1,ksize_2,ksize_3,]
  strides_0 = 1
  strides_1 = 1
  strides_2 = 1
  strides_3 = 1
  strides = [strides_0,strides_1,strides_2,strides_3,]
  padding = "VALID"
  explicit_paddings = []
  data_format = "NHWC"
  out = gen_nn_ops.max_pool(arg_0,ksize=ksize,strides=strides,padding=padding,explicit_paddings=explicit_paddings,data_format=data_format,)
except Exception as e:
  print("Error:"+str(e))
```

### Relevant log output

```shell
2023-01-09 15:14:48.597471: F tensorflow/stream_executor/cuda/cuda_dnn.cc:886] Check failed: cudnnSetPoolingNdDescriptor( handle_.get(), (pooling_descriptor.mode() == dnn::PoolingMode::kMaximum ? cudnn_max_pooling_mode : CUDNN_POOLING_AVERAGE_COUNT_EXCLUDE_PADDING), propagate_nans ? CUDNN_PROPAGATE_NAN : CUDNN_NOT_PROPAGATE_NAN, nd, shape.data(), padding.data(), strides.data()) == CUDNN_STATUS_SUCCESS (3 vs. 0)
Aborted

```
```
</details>

**Comment by tilakrayal** [comment]
@nimashiri,
While trying to execute the mentioned code on tensorflow v2.10 and 2.11, I was able to reproduce the issue whereas on 
**tf-nightly**, I was facing a different error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/565e977cb9d325139f5d0715e81a73ec/untitled862_gpu.ipynb). Thank you!

**Comment by sachinprasadhs** [comment]
Thanks for reporting the issue, we will investigate further on check failure and crash.

Meanwhile, when you provide explicit_paddiing as input, you need to change the padding ='EXPLICIT' instead of padding = 'VALID'.
After above mentioned changes, the expected error can be seen.

```
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.ops import gen_nn_ops
try:
  arg_0_tensor = tf.random.uniform([1, 10, 14, 1], dtype=tf.float32)
  arg_0 = tf.identity(arg_0_tensor)
  ksize_0 = 1
  ksize_1 = 0
  ksize_2 = 3
  ksize_3 = 1
  ksize = [ksize_0,ksize_1,ksize_2,ksize_3,]
  strides_0 = 1
  strides_1 = 2
  strides_2 = 2
  strides_3 = 1
  strides = [strides_0,strides_1,strides_2,strides_3,]
  padding = "EXPLICIT"
  explicit_paddings = []
  data_format = "NHWC"
  out = gen_nn_ops.max_pool(arg_0,ksize=ksize,strides=strides,padding=padding,explicit_paddings=explicit_paddings,data_format=data_format,)
except Exception as e:
  print("Error:"+str(e))
```

**Error:explicit_paddings attribute must contain 8 values, but got: 0 [Op:MaxPool]**

**Comment by mihaimaruseac** [comment]
@learning-to-play

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
