### ISSUE TITLE
Segfault when running tensorflow.python.ops.gen_linalg_ops.matrix_solve_ls

### ISSUE THREAD

**Issue by nimashiri** [tensorflow/tensorflow#59196]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
segfault
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np
from tensorflow.python.ops import gen_linalg_ops
try:
  try:
    with tf.device('/CPU'):
      arg_0_tensor = tf.complex(tf.random.uniform([16, 8, 127, 127], dtype=tf.float64),tf.random.uniform([16, 8, 127, 127], dtype=tf.float64))
      arg_0 = tf.identity(arg_0_tensor)
      arg_1_tensor = tf.complex(tf.random.uniform([16, 8, 127, 1], dtype=tf.float64),tf.random.uniform([16, 8, 127, 1], dtype=tf.float64))
      arg_1 = tf.identity(arg_1_tensor)
      arg_2 = -42.0
      fast = False
      out = gen_linalg_ops.matrix_solve_ls(arg_0,arg_1,arg_2,fast=fast,)
  except Exception as e:
    print("Error:"+str(e))
  try:
    with tf.device('/GPU:0'):
      arg_0 = tf.identity(arg_0_tensor)
      arg_0 = tf.cast(arg_0, tf.complex128)
      arg_1 = tf.identity(arg_1_tensor)
      arg_1 = tf.cast(arg_1, tf.complex128)
      gen_linalg_ops.matrix_solve_ls(arg_0,arg_1,arg_2,fast=fast,)
  except Exception as e:
    print("Error:"+str(e))
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
Error:Value for attr 'T' of uint8 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixSolveLs}}; Op<name=MatrixSolveLs; signature=matrix:T, rhs:T, l2_regularizer:double -> output:T; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]; attr=fast:bool,default=true> [Op:MatrixSolveLs]
Error:Value for attr 'T' of uint8 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixSolveLs}}; Op<name=MatrixSolveLs; signature=matrix:T, rhs:T, l2_regularizer:double -> output:T; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]; attr=fast:bool,default=true> [Op:MatrixSolveLs]
Error:Value for attr 'T' of uint8 is not in the list of allowed values: double, float, half, complex64, complex128
	; NodeDef: {{node MatrixSolveLs}}; Op<name=MatrixSolveLs; signature=matrix:T, rhs:T, l2_regularizer:double -> output:T; attr=T:type,allowed=[DT_DOUBLE, DT_FLOAT, DT_HALF, DT_COMPLEX64, DT_COMPLEX128]; attr=fast:bool,default=true> [Op:MatrixSolveLs]
Error:{{function_node __wrapped__MatrixSolveLs_device_/job:localhost/replica:0/task:0/device:CPU:0}} l2_regularizer must be >= 0. [Op:MatrixSolveLs]
malloc(): unaligned tcache chunk detected
Segmentation fault

```
```
</details>

**Comment by mohantym** [comment]
Hi @nimashiri !
I am able to get this error for gen_linalg_ops.matrix_solve_ls without segmentation fault.
`Error:{{function_node __wrapped__MatrixSolveLs_device_/job:localhost/replica:0/task:0/device:CPU:0}} l2_regularizer must be >= 0. [Op:MatrixSolveLs]`

and 
`Error:matrix_solve_ls is currently disabled for complex128 and l2_regularizer != 0 due to poor accuracy.
`

for  `tf.compat.v1.matrix_solve_ls(arg_0,arg_1,arg_2,fast=fast,)`

Attached gist in [2.10](https://colab.sandbox.google.com/gist/mohantym/36821feb3d436f17606df4105126c15a/git_59196.ipynb#scrollTo=uu4AV8R54GKi), [2.11 ](https://colab.sandbox.google.com/gist/mohantym/69470681cc120084dd7aa02397f59e46/git_59196.ipynb#scrollTo=qGejX0Im4-ci)and [nightly ](https://colab.sandbox.google.com/gist/mohantym/42bd80b624d1ff998e6b08ad3f3e4d66/git_59196.ipynb#scrollTo=qGejX0Im4-ci)for reference.

Same in Ubuntu 22 with Ubuntu 20 GPU driver and Cuda 11.2 tool kit (P100 Telsa GPU)
[Ref](https://user-images.githubusercontent.com/86464649/211756653-7af29a6d-135f-4319-bbcc-49c1ba28217d.png)


Could you let us you know your procedure/commands on setting up Tensorflow in Ubuntu22.

Thank you!
