### ISSUE TITLE
[macos-arm64] //tensorflow/compiler/xla/service:hlo_execution_profile_test fails in macOS Arm64

### ISSUE THREAD

**Issue by nitins17** [tensorflow/tensorflow#59204]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf-nightly

### Custom Code

Yes

### OS Platform and Distribution

macOS Monterey 12.4, Arm64

### Python version

3.9.9

### Bazel version

5.3.0

### GCC/Compiler version

Clang from Xcode 13.4

### Current Behaviour?

```shell
INFO: From Testing //tensorflow/compiler/xla/service:hlo_execution_profile_test:
==================== Test output for //tensorflow/compiler/xla/service:hlo_execution_profile_test:
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from HloExecutionProfileTest
[ RUN      ] HloExecutionProfileTest.Basic
2022-12-28 06:42:38.460138: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
2022-12-28 06:42:38.462696: F ./tensorflow/compiler/xla/service/human_readable_profile_builder.h:40] Check failed: clock_rate_ghz >= 1e-9 (1e-09 vs. -1e-09)
```
```


### Standalone code to reproduce the issue

```shell
Run `bazel --bazelrc="macos.bazelrc" test //tensorflow/compiler/xla/service:hlo_execution_profile_test` from the TensorFlow root directory. 

Bazel configs I used are in https://gist.github.com/nitins17/73e0818b3a6bec240775c2619540a979

`//tensorflow/compiler/xla/tests:xla_hlo_profile_test_cpu` fails with a similar error.
```

### Relevant log output

_No response_</details>

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
