### ISSUE TITLE
[macos-arm64] //tensorflow/compiler/xla/service/cpu:vectorized_reduce_with_no_vector_registers_test fails in macOS Arm64

### ISSUE THREAD

**Issue by nitins17** [tensorflow/tensorflow#59205]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf nightly

### Custom Code

Yes

### OS Platform and Distribution

macOS Monterey 12.4, Arm64

### Python version

3.9.9

### Bazel version

5.3.0

### GCC/Compiler version

Clang from Xcode 13.4

### Current Behaviour?

```shell
==================== Test output for //tensorflow/compiler/xla/service/cpu:vectorized_reduce_with_no_vector_registers_test:
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from CodegenReduceOnArchWithNoVectorRegisters
[ RUN      ] CodegenReduceOnArchWithNoVectorRegisters.Test
2022-12-28 07:13:32.077216: W tensorflow/tsl/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz
tensorflow/compiler/xla/service/cpu/vectorized_reduce_with_no_vector_registers_test.cc:86: Failure
Value of: _status_or_value13.status().ok()
  Actual: false
Expected: true
INTERNAL: TargetRegistry::lookupTarget failed: No available targets are compatible with triple "i686-none-android"
[  FAILED  ] CodegenReduceOnArchWithNoVectorRegisters.Test (16 ms)
[----------] 1 test from CodegenReduceOnArchWithNoVectorRegisters (16 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test suite ran. (16 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CodegenReduceOnArchWithNoVectorRegisters.Test

 1 FAILED TEST
```
```


### Standalone code to reproduce the issue

```shell
Run `bazel --bazelrc="macos.bazelrc" test //tensorflow/compiler/xla/service/cpu:vectorized_reduce_with_no_vector_registers_test` from the TensorFlow root directory. 

Other tests that fail similarly:
1. //tensorflow/compiler/xla/service/cpu/tests:cpu_eigen_dot_operation_test
2. //tensorflow/core/platform:__tensorflow_tsl_platform_profile_utils_cpu_utils_test
3. //tensorflow/compiler/xla/tests:execution_profile_test_with_xla_hlo_profile_cpu


Bazel configs I used are in https://gist.github.com/nitins17/73e0818b3a6bec240775c2619540a979
```

### Relevant log output

_No response_</details>

**Comment by kulinseth** [comment]
This issue seems to be same as #59204

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
