### ISSUE TITLE
Is there way to remove BDBA critical Vulnerability 

### ISSUE THREAD

**Issue by rameezdev** [tensorflow/tensorflow#59225]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Others

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.11

### Custom Code

Yes

### OS Platform and Distribution

windows

### Current Behaviour?

```shell
No Critical vulnerabilities in BDBA for TensorFlow.
```

### Standalone code to reproduce the issue

```shell
BDBA report Critical Vulnerabilities CVE-2022-46908 (Sqlite3 3.39.4 component) and CVE-2022-43551, CVE-2022-35260, CVE-2022-32221, CVE-2022-42915 and CVE-2022-42916
(curl 7.85.0 component)
https://nvd.nist.gov/vuln/search
```

### Relevant log output

_No response_</details>

**Comment by yongtang** [comment]
Added a PR #59249 for the fix.

**Comment by rameezdev** [comment]
Both TensorFlow-2.11.0-cp38-cp38-win_amd64.zip and TensorFlow-2.12.0rc0-cp38-cp38-win_amd64.zip alone doesn't have vulnerability 
The individual libraries which are having vulnerabilities are tensorflow_io_gcs_filesystem-0.31.0-cp38-cp38-win_amd64.zip and tensorflow_intel-2.11.0-cp38-cp38-win_amd64.whl

**Comment by rameezdev** [comment]
> Added a PR #59249 for the fix.

Both TensorFlow-2.11.0-cp38-cp38-win_amd64.zip and TensorFlow-2.12.0rc0-cp38-cp38-win_amd64.zip alone don't have a vulnerability
The individual libraries which are having vulnerabilities are tensorflow_io_gcs_filesystem-0.31.0-cp38-cp38-win_amd64.zip and tensorflow_intel-2.11.0-cp38-cp38-win_amd64.whl

**Comment by adarshbilimagga** [comment]
Adding to the above comment. 
Tensorflow used is 2.12.0.  This library tensorflow_io_gcs_filesystem-0.31.0-cp38-cp38-win_amd64.whl still has vulnerability.

**Comment by adarshbilimagga** [comment]
Tensorflow used is 2.17.0. This library tensorflow_io_gcs_filesystem-0.31.0-cp38-cp38-win_amd64.whl still has vulnerability and 0.31.0 version where I could see the latest version available for windows.

**Comment by LavanyaKV1234** [comment]
Hi, 

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
