### ISSUE TITLE
Rust binding for Tensorflow Lite

### ISSUE THREAD

**Issue by Neirth** [tensorflow/tensorflow#59271]
Is there any kind of plan to create Tensorflow Lite bindings for Rust? It would be convenient for projects that only need the model execution layer, without having to import the rest of the project.

**Comment by DURGESH716** [comment]
Here's What I have got from the documentation of tflite, TensorFlow Lite bindings for the Rust programming language have not been officially released by the TensorFlow team yet. However, there are some third-party libraries that provide TensorFlow Lite bindings for Rust.

But here are some of the third party stuff, if you want to try:
1. the Tensorflow Rust crate is a set of Rust language bindings for TensorFlow. It provides a high-level API for loading and running TensorFlow models, as well as a lower-level API for building custom TensorFlow ops using Rust code.

2. Another example is tflite-rust is a rust wrapper for TensorFlow Lite C API, which is developed by the community.

**Comment by Neirth** [comment]
Hi @DURGESH716!

About the status of the third party libraries, I have to mention that they are not following a development speed to be used in production. Being some of these libraries abandoned in time.

Regarding the issue of using some constructions with TensorFlow Custom Ops, yes, it could be considered, but would it be a serious and competitive solution against Tensorflow Lite? It would be necessary to get some comparative metrics for it.

The reason for opening this issue is more to follow up this feature on the TensorFlow Lite library and to show the interest of the community to develop it.

**Comment by synandi** [comment]
@mohantym 
could you please look at this issue?

**Comment by pkgoogle** [comment]
Hi @Neirth,

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/LiteRT/issues/135).

Let us know if you have any questions. Thanks.
