### ISSUE TITLE
No new version on Zenodo

### ISSUE THREAD

**Issue by Fremih** [tensorflow/tensorflow#59308]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### Current Behaviour?

On [Zenodo](https://zenodo.org/record/6574269) only versions up to 2.9.1 are stored. The last update came from May 23, 2022. I was told in [#51071](https://github.com/tensorflow/tensorflow/issues/51071) that new versions should have been added automatically, but they were not. Furthermore, I would be happy if they would come in chronological order and not several versions at the same day. Thanks in advance for the help :)

### Standalone code to reproduce the issue

Look at https://zenodo.org/record/6574269 and issue [#51071](https://github.com/tensorflow/tensorflow/issues/51071)

### Relevant log output

_No response_</details>

**Comment by mihaimaruseac** [comment]
CC @angerson

**Comment by angerson** [comment]
> On [Zenodo](https://zenodo.org/record/6574269) only versions up to 2.9.1 are stored. The last update came from May 23, 2022. I was told in https://github.com/tensorflow/tensorflow/issues/51071 that new versions should have been added automatically, but they were not.

Thanks for your report. This was indeed some kind of silent bug with our integration with Zenodo and GitHub. I think I have fixed it, and the upcoming TensorFlow 2.12 release should be uploaded automatically.

Since the automation does not apply retroactively, I have uploaded those versions that were not published.

> Furthermore, I would be happy if they would come in chronological order and not several versions at the same day.

Sorry, this is not possible. Zenodo does not give us control over display order, and so each TensorFlow version appears in the same order it was uploaded to Zenodo.
