### ISSUE TITLE
Divide in Dataset.map lambda function fails with inf

### ISSUE THREAD

**Issue by dwojcik92** [tensorflow/tensorflow#59324]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

macOS

### Python version

3.8.15

### Current Behaviour?

The presented Standalone code will produce inf or nan.
If I will change:
```
x_train = x_train.map(lambda x : tf.divide(x,255.0))
```
to:
```
x_train = x_train.map(lambda x : tf.divide(x,tf.Variable(255.0, dtype=tf.float16)))
```
It works as it should.

### Standalone code to reproduce the issue

```shell
(x_train, _), (_, _) = tensorflow.keras.datasets.cifar10.load_data()

x_train = tf.convert_to_tensor(x_train, dtype=tf.float16)
x_train = tf.data.Dataset.from_tensor_slices(x_train)
x_train = x_train.map(lambda x : tf.divide(x,255.0))
list(x_train.take(1))
```

### Relevant log output

```shell
[<tf.Tensor: shape=(32, 32, 3), dtype=float16, numpy=
 array([[[inf, inf, inf],
         [inf, inf, inf],
         [inf, inf, inf],
         ...,
         [inf, inf, inf],
         [inf, inf, inf],
         [inf, inf, inf]],
 
        [[inf, inf, inf],
         [inf, inf, inf],
         [inf, inf, inf],
         ...,
         [inf, inf, inf],
         [inf, inf, inf],
         [inf, inf, inf]],
 
        [[inf, inf, inf],
         [inf, inf, inf],
         [inf, inf, inf],
         ...,
         [inf, inf, inf],
         [inf, inf, inf],
         [inf, inf, inf]],
 
...
         [inf, inf, inf],
         ...,
         [inf, inf, inf],
         [inf, inf, inf],
         [inf, inf, inf]]], dtype=float16)>]
```
</details>

**Comment by gaikwadrahul8** [comment]
Hi, @dwojcik92 

I was able to replicate the issue without any `inf `or `nan `values in the output and it's working as expected, for your reference I have added gist file [here](https://colab.research.google.com/gist/gaikwadrahul8/08a5d73bc1e5dd59bf7fef9fbe13ca7c/-59324.ipynb) so could please  check and try from your end ? please let us know whether is it working as expected or not ?

Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!
