### ISSUE TITLE
Checkpointing simple from_generator dataset iterator gives "PyFunc is stateful" error.

### ISSUE THREAD

**Issue by hamzamerzic** [tensorflow/tensorflow#59398]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

binary

### Tensorflow Version

2.12.0

### Custom Code

Yes

### Current Behaviour?

```shell
Trying to build a simple checkpointable dataset. As a first step trying to mimic the behavior of `tf.data.Dataset.range` so that it can be made more complex. Building the iteration logic via a generator results in `PyFunc is stateful` error.
```

### Standalone code to reproduce the issue

```shell
def count():
  i = 0
  while i < 10:
    yield i
    i += 1


ds = tf.data.Dataset.from_generator(
    count, output_signature=tf.TensorSpec(shape=(), dtype=np.int32))

ckpt = tf.train.Checkpoint(iterator=it)
manager = tf.train.CheckpointManager(ckpt, '~/tf-ckpt', max_to_keep=2)
manager.save()
```

### Relevant log output

```shell
_NotOkStatusException: FailedPreconditionError: {{function_node __wrapped__SerializeIterator_device_/job:localhost/replica:0/task:0/device:CPU:0}} PyFunc is stateful. [Op:SerializeIterator]
```
</details>

**Comment by pjpratik** [comment]
I was able to reproduce the issue in TF 2.11 and TF Nightly 2.12.0-dev20230123. Please find the gist [here](https://colab.research.google.com/gist/pjpratik/85dcc93a40b87eb424865344de80489f/59398.ipynb). Thank you.

**Comment by aaudiber** [comment]
`from_generator` datasets are not checkpointable due to their dependency on a Python runtime. That being said, it would be good to improve the error message to something clearer.

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
