### ISSUE TITLE
Crash when running tf.math.unsorted_segment_prod

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#59444]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.10.0

### Custom Code

Yes

### OS Platform and Distribution

Ubuntu 22.04

### Python version

3.9

### Current Behaviour?

```shell
A bug happened!
```

### Standalone code to reproduce the issue

```shell
https://drive.google.com/drive/folders/14XteRiq7ULRMTHFuwDKMLmyf_tx2rHZz?usp=share_link
```

### Relevant log output

_No response_</details>

**Comment by gaikwadrahul8** [comment]
Hi, @SuryanarayanaY 

Could you please look into this issue? Thank you!

**Comment by SuryanarayanaY** [comment]
Hi  @nimashiri ,
I replicated the issue with TF2.10 and tf-nightly versions and observed the crash is due to Higher Input size which exceeds the available RAM and the crash is from OS not Tensorflow.Please observe the snapshot which shows malloc fails to get required memory.
<img width="1486" alt="Screenshot 2023-01-27 at 2 48 12 PM" src="https://user-images.githubusercontent.com/116063290/215051322-5e377d6a-34f8-4273-bda1-bd16dcd4a958.png">

I tried it on a VM with Ubuntu 22.04 OS with 2 GPUs(NVIDIA A100-SXM4-40GB) and the ran the code multiple times which executed without any error even in multiple runs.I have added  the code `print('Code execution completed')` at end of program to ensure success.


<img width="1508" alt="Screenshot 2023-01-27 at 4 15 36 PM" src="https://user-images.githubusercontent.com/116063290/215068289-8cd4ecb5-07f9-4c69-9295-8bca18595e12.png">

This clearly indicates the problem is due to Memory issue and may be with your own environment that caused segmentation fault, but not the problem with Tensorflow.Also please refer to the developer [comment](https://github.com/tensorflow/tensorflow/issues/59168#issuecomment-1405633596) related to malloc with High input size which will eventually lead to OS crash.

**Comment by mihaimaruseac** [comment]
Closing as not a vuln

@dmc1778 please stop posting vulns on GitHub. Please consult SECURITY.md for how to properly and ethically disclose them.
