### ISSUE TITLE
tf equivalent of numpy.view()

### ISSUE THREAD

**Issue by anna-charlotte** [tensorflow/tensorflow#59473]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

MacOS Ventura 13.0

### Python version

3.10.8

### Current Behaviour?

```shell
Is there an equivalent to numpy's `.view()` function in tensorflow?

https://numpy.org/doc/stable/reference/generated/numpy.ndarray.view.html
```

### Standalone code to reproduce the issue

```shell
-
```

### Relevant log output

_No response_</details>

**Comment by mohantym** [comment]
Hi @anna-charlotte !
Thanks for the feature request . 

 @SuryanarayanaY 
Could you look at this feature request.  Attached gist in [2.10,](https://colab.sandbox.google.com/gist/mohantym/44dc83162574a9c423e7d29a14a9eb27/git_59473.ipynb#scrollTo=_u1onZ94h-OT), [2.11](https://colab.sandbox.google.com/gist/mohantym/be7f8a516f41345039f64d9abb826d10/git_59473.ipynb#scrollTo=_u1onZ94h-OT) and [nightly](https://colab.sandbox.google.com/gist/mohantym/bda80a458f26f9cfc6f7863501a0dd95/git_59473.ipynb#scrollTo=bJPev6KBhIDm) (2.12 dev build not stable yet) for reference.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @anna-charlotte ,

I am afraid we can't update a Tensor in a direct way as mentioned above in Tensorflow. Can you please refer this thread #36559 for similar discussion. If you still believe the expected functionality is possible I would escalate to next level Feature request. Thanks!

**Comment by jonas-eschle** [comment]
I would suggest: rethink the way you code. Don't use states, assignments are a kind of state. Think functional.

What should be what? You can use the `update` functions to create a new tensor with values replaced.

**Comment by SuryanarayanaY** [comment]
@anna-charlotte ,

Update: There is already some internal work is going on to make Tensor update methods into a more friendly and familiar syntax. For performance and compatibility reasons, tensors will remain immutable, only allowing modified copies to be returned. I can't say exact timeline though. Thanks!

**Comment by SuryanarayanaY** [comment]
@anna-charlotte ,

Please also refer to the attached [source](https://github.com/tensorflow/tensorflow/issues/33131#issuecomment-1332425382) regarding the WIP. Also keeping the issue open till implementation.

Thanks!

**Comment by cantonios** [comment]
Item assignment is only one part of the puzzle here.  We will make it easier to syntactically "replace" a value in a tensor - in reality, a completely new copy of the tensor will be returned.

The other part of the question is about one tensor referring directly into a portion of another tensor - the "view" part.  We do not support this.  We can use slicing or other indexing ops to make a copy of part of another tensor, but we do not have a way to explicitly refer directly to part of another tensor.  Since tensors are immutable, under-the-hood we can (and do) actually make such optimizations, but we will not support the case presented here where updating `b` will result in a change in `a`.  It is against our current programming model.
