### ISSUE TITLE
module 'numpy' has no attribute 'typeDict'

### ISSUE THREAD

**Issue by hulagerushikesh** [tensorflow/tensorflow#59513]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.9.1

### Custom Code

No

### OS Platform and Distribution

Windows 11

### Python version

3.10.5

### Current Behaviour?

```shell
While importing the tensorflow
```

### Standalone code to reproduce the issue

```shell
The issue is occured when i was trying to import the tensorflow module
```

### Relevant log output

_No response_</details>

**Comment by markandey1414** [comment]
it has been added in tensorflow 2.11.0

**Comment by gaikwadrahul8** [comment]
Hi, @hulagerushikesh 

Apologize for the delay and as per the [NumPy 1.21.0 Release Notes](https://github.com/numpy/numpy/releases/tag/v1.21.0#:~:text=np.typeDict%20has%20been%20formally%20deprecated) `np.typeDict` has been formally deprecated so This means you are using a NumPy version that removed the deprecated `np.typeDict` ( you can use `np.sctypeDict` instead of `np.typeDict`).  I checked while using the `np.typeDict ` you're getting proper warning as below :

```
"<ipython-input-5-f1e601fc314f>:1: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  'float16' in numpy.typeDict and 'float128' in numpy.typeDict and 'complex256' in numpy.typeDict "
```

For your reference I have added [gist file](https://colab.research.google.com/gist/gaikwadrahul8/07a22f3ac14c9269fd1bc2d3ed38f09f/-59513.ipynb) with some sample code and I have tried with latest version of `Tensorflow==2.11` so I would suggest you to either go with latest `Tensorfow version 2.11` or Use an older version of `numpy` (one before it started to issue the deprecation warning)

If Issue still persists please let us know? or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by ilfrich** [comment]
Having the latest version of tensorflow didn't solve the issue for me. I had to manually update `h5py` to 3.8.0 (latest as of writing this) and that solved the issue.
