### ISSUE TITLE
How to create `tf.keras.layers.Input` without batch_size dimension?

### ISSUE THREAD

**Issue by baoachun** [tensorflow/tensorflow#59512]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Support

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

2.9.1

### Custom Code

No

### OS Platform and Distribution

centos7

### Python version

3.8.14

### Bazel version

5.0

### GCC/Compiler version

10.2

### CUDA/cuDNN version

11.4

### GPU model and memory

A30

### Current Behaviour?

One input of my model has nothing to do with batch_size, for example, its shape is [1,2,3], how to avoid automatically adding 1 dimension when creating  `tf.keras.layers.Input` ? If I manually slice it, the slice operator will be introduced, resulting in a decrease in inference performance.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

x = tf.keras.layers.Input(shape=(32,64))
# x.shape: (None, 32, 64)
x = x[0, :, :]
# x.shape: (32, 64)

```

**Comment by tiruk007** [comment]
@baoachun 
This issue seems to be keras issue.Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues)
To know more see;
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999).

Thank you!
