### ISSUE TITLE
Tensorflow Ops for RecordRandomReader

### ISSUE THREAD

**Issue by mhorlacher** [tensorflow/tensorflow#59559]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Feature Request

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### Current Behaviour?

Currently, there is no option for random access reading TFRecord files. This could be extremely useful when dealing with huge (long) datasets that do not fit into memory, e.g. one could create an index of proto byte offsets and then read protos from their offsets. This would enable full shuffling of large datasets. 

I've discovered a RecordRandomReader class in the Git (although there's no documentation of it on the TF web page) which seems to do just that - except it's not a tf ops, so it can not be added to a tf.data pipeline without wrapping it into py_function first, severely limiting its performance. 

So, could we have a RecordRandomReader-like tf ops? Thanks!

**Comment by saurabhmj11** [comment]
The RecordRandomReader operation is part of the TensorFlow IO library, which provides support for reading data from various file formats and data sources.

If you're encountering issues with the RecordRandomReader operation, here are a few steps you can try to resolve the issue:

Ensure that the data source specified in the RecordRandomReader operation is correct and accessible.

Check that the format of the data source is compatible with the RecordRandomReader operation. The RecordRandomReader operation is designed to read records from a data source, so it's important to make sure that the data source is formatted as records.

If you're encountering issues with the TensorFlow IO library, you may want to check the TensorFlow IO GitHub repository for any known issues and potential solutions.

If you're encountering an error message or unexpected behavior, try to provide a minimal, reproducible example that demonstrates the issue. This will help others to understand and diagnose the issue more effectively.

Note: These steps are general and may not resolve the issue for all cases. If the issue persists, I recommend reaching out to TensorFlow support or the TensorFlow user community for further assistance.

**Comment by mhorlacher** [comment]
Hi @saurabhmj11 - thanks for looking into this. I was refering to `tensorflow.python.lib.io._pywrap_record_io.RandomRecordReader`. Using this reader as part of a graph yields the following exception, which leads me to believe that it does only work in eager mode (or wrapped as py_function). 

![image](https://user-images.githubusercontent.com/37439882/217034586-bddc7521-66e6-4600-826a-43b619e1c03e.png)

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
