### ISSUE TITLE
tf.math.digamma outputs NaN when receiving 0

### ISSUE THREAD

**Issue by mazeltovlee** [tensorflow/tensorflow#59627]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### Python version

3.8

### Current Behaviour?

```shell
tf.math.digamma outputs nan when receiving zero. In contrast, spicy, Matlab, and pytorch output -inf. Following the blue curve in this graph (https://ww2.mathworks.cn/help/matlab/ref/psi.html#mw_8a9c6576-f489-4530-bd3f-f6c8d596c644), I guess digamma outputs -inf for zero is more accurate.
```

### Standalone code to reproduce the issue

```shell
tf.math.digamma(0.)  # outputs <tf.Tensor: shape=(), dtype=float32, numpy=nan>
scipy.special.digamma(0.)  # outputs -inf
torch.digamma(0.) # outputs -inf
```

### Relevant log output

_No response_</details>

**Comment by synandi** [comment]
I was able to replicate the issue on Google Colab with latest stable version of Tensorflow 2.11 and also tried with tf-nightly-2.13.0-dev20230209 it's returning nan. Kindly refer to the gist [here](https://colab.sandbox.google.com/gist/synandi/4b432401f0c6c46b7c87c2c6be95faef/59627.ipynb). It seems like we have to dig more into this issue, we will update soon here. Thank you!

**Comment by synandi** [comment]
@mazeltovlee, 

Apologies for the delay. The reason for the discrepancy in the output of the digamma function between TensorFlow and other libraries such as SciPy, MATLAB, and PyTorch is a matter of convention. TensorFlow follows the C99 standard for special functions, that defines the digamma function to be NaN (Not a Number) at x = 0, while the other libraries follow a convention that defines the digamma function to be -inf (negative infinity) at x = 0.

This difference in behavior is due to the underlying mathematical definition of the digamma function and the conventions used by different libraries. Thank you!

**Comment by mazeltovlee** [comment]
Hi, @synandi 

Thanks for your detailed explanation. I will close this issue as it is the expected behavior of TensorFlow.
