### ISSUE TITLE
tf.data.Dataset.map() of tf.data.Dataset feat. tf.RaggedTensor causes broken for-loop

### ISSUE THREAD

**Issue by Tens0rFlaw** [tensorflow/tensorflow#59641]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.9.2

### Custom Code

Yes

### OS Platform and Distribution

Windows 10, WSL2 Ubuntu 20.04

### Python version

3.8.10

### CUDA/cuDNN version

11.2

### Current Behaviour?

```shell
When using a tf.data.Dataset for tf.RaggedTensors, the .map() functionality seems to break the ability to iterate over the datapoints via for-loop, causing an internal TypeError on the for-loop itself.
The expected behaviour would be for the program not to throw a TypeError as the same function works if used via a simple for-loop over the data instead of the .map() functionality.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
ragged_data=tf.ragged.constant([[[[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]]], [[[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]], [[1,2],[3,4],[5,6]]]])
ds=tf.data.Dataset.from_tensor_slices(ragged_data)
def test_fn(ragged_data):
    for x in ragged_data:
        continue
    return ragged_data
ds.map(test_fn)
```

### Relevant log output

```shell
TypeError: Input 'y' of 'Less' Op has type int64 that does not match type int32 of argument 'x'.
```
</details>

**Comment by tiruk007** [comment]
@sushreebarsa 

I was able to reproduce the issue on Colab using TF v2.11 . Please find the gist [here](https://colab.research.google.com/gist/tiruk007/01cd0b1c8b49584bf08617e8fe098086/untitled121.ipynb) for reference.

Thank you!

**Comment by gaikwadrahul8** [comment]
Hi, @Tens0rFlaw 

Apologize for the delay and I was able to replicate the issue on Google Colab with `Tensorflow==2.11` and it's working as expected, for your reference I have added [gist-file ](https://colab.research.google.com/gist/gaikwadrahul8/db0420fcfef1d506079d0d33dfbc0481/-59641.ipynb) and it seems like you're using python `map()` instead of `tf.map_fn()` and for your reference I have added [official documentation](https://www.tensorflow.org/api_docs/python/tf/map_fn) for `tf.map_fn()` which may help you. If issue still persists please let us know or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by Tens0rFlaw** [comment]
Hi @gaikwadrahul8 
that indeed resolves the issue. 
Thank you for you answer!
