### ISSUE TITLE
How to map '\n' to id in a metadata.tsv when visualizing embedding

### ISSUE THREAD

**Issue by leido** [tensorflow/tensorflow#5966]
I'm quite excited about the new embedding visualization feature in TF 0.12.0-RC0. But when I walk through the [new documentation page](https://www.tensorflow.org/versions/master/how_tos/embedding_viz/index.html#tensorboard-embedding-visualization) in the metadata part, it says that the metadata has the exact format with first line as header and others as fields.

What if I have to map char '\n' to id? In this way, the specific format of tsv file will broken. This is often the case in most NLP tasks. 

Hope the developer will explain this. thanks.

**Comment by dsmilkov** [comment]
Hi @leido,

You would have to represent the newline character as "\n" (a 2 characters string). We chose the TSV format since it is well know, human-readable, and allows for white space in labels. If we get a big push on this, we will reconsider switching to another format.

Thanks for reporting this!
