### ISSUE TITLE
zsh: illegal hardware instruction Run on MAC M2

### ISSUE THREAD

**Issue by aim2002** [tensorflow/tensorflow#59663]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11.0

### Custom Code

Yes

### OS Platform and Distribution

13.1 (22C65)

### Python version

Python 3.9.12

### Current Behaviour?

```shell
A bug happened! Help me pleaseee
tensorboard                  2.11.2
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.11.0
tensorflow-estimator         2.11.0
tensorflow-io-gcs-filesystem 0.29.0
```

### Standalone code to reproduce the issue

```shell
zsh: illegal hardware instruction
```

### Relevant log output

_No response_</details>

**Comment by gaikwadrahul8** [comment]
Hi, @aim2002 

I'm not sure which instructions are you following but I'm able to install Tensorflow on Apple M1 Pro and it should work on `Mac M2` also so you can install Tensorlflow by using one of the `Conda`, `Miniconda` or `Miniforge` approach so I followed [Get started with tensorflow-metal](https://developer.apple.com/metal/tensorflow-plugin/) with `Miniconda3` instructions so could you please try with `arm64 : Apple silicon`

While following the instructions and after clicking on [Download Conda environment ](https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-arm64.sh) Miniconda3-latest-MacOSX-arm64.sh file will be downloaded and replace that .sh file as shown below in first step Set up and please follow all steps from `2. Install base TensorFlow` as it is :

```
bash ~/Miniconda3-latest-MacOSX-arm64.sh -b -p $HOME/miniconda
source ~/miniconda/bin/activate
conda install -c apple tensorflow-deps
```
You'll have to use this command `source ~/miniconda/bin/activate` whenever you want to use/activate `Miniconda` environment 

If you're looking to go with `Miniforge` approach then please refer this [Article](https://caffeinedev.medium.com/how-to-install-tensorflow-on-m1-mac-8e9b91d93706) and for [Miniconda-Article](https://medium.com/mlearning-ai/install-tensorflow-on-mac-m1-m2-with-gpu-support-c404c6cfb580) and also please refer [Releases-Table](https://developer.apple.com/metal/tensorflow-plugin/#:~:text=Releases-,tensorflow%2Dmacos,Distributed%20training,-Troubleshooting)

I have added screenshot for your reference below, 

![image](https://user-images.githubusercontent.com/115997457/218498891-4990a9fb-c2a0-4a8d-a46c-3f2bdf84cbd5.png)

If issue still persists, please let us know? or Could you please confirm if this issue is resolved for you ? Please feel free to close the issue if it is resolved ? Thank you!

**Comment by andriiicat** [comment]
Mac mini M2. Used pip install tensorflow. 
As soon as I import tensorflow in my python scrip I am getting:
`zsh: illegal hardware instruction`
