### ISSUE TITLE
split_v generates tensors of unspecified size for all dimensions, when one dimension is missing at the original one

### ISSUE THREAD

**Issue by moliusimon** [tensorflow/tensorflow#5977]
The new split_v function introduced in 0.12rc0 does not correctly predict the shapes of the resulting tensors when the original tensor has an unknown dimension, resulting on the split dimension being of unknown size. For instance:

```
tensor = tf.placeholder(tf.float32, [None, 12])
parts = tf.split_v(tensor, [6, 4, 2], split_dim=1)
```

This results in three tensors, all with shapes [?, ?], instead of the expected [?, 6], [?, 4] and [?, 2]. While at runtime the resulting tensors are of the right size, this makes it more difficult to debug the code during graph definition.

EDIT: This also creates problems when combined with scan. Because scan expects fn to return tensors of the same shape as the initializers, it forces the use of a reshape just to clear the 'unknown' dimension.

**Comment by ekelsen** [comment]
Shape inference is done in C++, not python, and at that point everything is a tensor and it is not possible to inspect the contents of tensors during shape inference.  So, in general, it is not possible to provide any better shape information beyond the rank.

That said, we can hack the python interface to check if the size list is a list of integers and not a tensor and then reshape the outputs correctly.  Is that your use case?  Or do you generate the size list dynamically?  Because if it is dynamically generated, there is no way to do the shape inference that you want.

**Comment by moliusimon** [comment]
Hello ekelsen, yes that is my case. The list provided to split_v is a list of integers, so the size for this dimension is provided.

**Comment by ekelsen** [comment]
This feature should be added before the next release.  Note that this shape inference behavior will be optional as it will add a reshape operation to every output tensor which could be a performance penalty, especially when there are many output tensors (1000+) and the tensors are small.

**Comment by moliusimon** [comment]
Thank you in advance. Nevetheless, I'm a little bit confused as to why a reshape for each output tensor is required. I'm not familiar with how tensorflow works internally, but even if the tensor operation itself has no information on the tensor shape other than the rank, shouldn't it be possible to set the output tensors dimension to the provided values (if these are given as integers) without having to add a reshape operator? After all, under these circumstances the output is guaranteed to have this shape for the split dimension, a reshape seems unnecessary to enforce this.

**Comment by ekelsen** [comment]
Sorry, yes you're correct that all that's needed here is to set the shape.
