### ISSUE TITLE
TensorFlow on Windows logs an error when using GPUs: "Could not identify NUMA node"

### ISSUE THREAD

**Issue by nobsu** [tensorflow/tensorflow#5986]
I use one GPU card now,  tensorflow(0.12) reports follow error, but the process run correctly.   How to suport  if we use multi-gpu on windows ?

E c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:586] Could not identify NUMA node of /job:localhost/replica:0/task:0/gpu:0, defaulting to 0.  Your kernel may not have been built with NUMA support.

**Comment by mrry** [comment]
This error should be a warning. Multiple GPUs work today on Windows, and they should work with a NUMA setup (although we haven't tested this). However, the stream executor code will not take advantage of NUMA topology if it is available.

**Comment by mrry** [comment]
@poxvoculi I think you know most about the more complex bus topologies we use. What are we missing if we don't have GPU-to-NUMA-node mapping information in stream executor?

**Comment by poxvoculi** [comment]
The code and comments in gpu_device.cc clarify what's going on.  We use the StreamExecutor interface to get NUMA affinity for a GPU, then use that to set a (PCI) bus identifier for the GPU.  In the generic open-source version of TensorFlow, the bus id is of no consequence because there are no adaptations for multi-bus architectures.    It would be possible to utilize this feature to customize TF for higher performance in some kinds of multi-bus architecture.

**Comment by mrry** [comment]
Should we remove this log statement from `tensorflow/stream_executor` then? Or should we even remove the code for querying the NUMA affinity, since the bus ID is never used?

**Comment by poxvoculi** [comment]
That should probably be a LOG(INFO), not an error.
