### ISSUE TITLE
Resource exhausted error during training

### ISSUE THREAD

**Issue by DNJ-JINI** [tensorflow/tensorflow#59906]
Resource exhausted error during training
I would like to train the deep learning task semantic segmentation.
Specifications: model with 31 million  parameters
image size ( minimum 1024x1024), batch size 256 framework -tensorflow keras 2.7
Total image samples 30,000,
Label Mask samples 30,000
Does colab pro plus allow the training for this specification with out OOM error?

Issue currently facing  is even with 2000 number of images and 512x512 size for batch size 32 results in out of memory error in colab pro subscription.

**Comment by tilakrayal** [comment]
@DNJ-JINI,
This is not the issue from the Tensorflow side. In order to be able to offer computational resources at scale, Colab needs to maintain flexibility to adjust usage dynamically. Colab Pro subscribers have greater limits than the free version of Colab. You can read more at the FAQ: https://research.google.com/colaboratory/faq.html#resource-limits. 

Please try to raise the issue on [Colab repo](https://github.com/googlecolab/colabtools) for better assistance. If you encounter this repeatedly, we'll need more information for the bug report. Please submit feedback within Colab at Help > Send feedback. Thank you!
