### ISSUE TITLE
How to enable the support of cuda compute capability 3.0 GPU in windows

### ISSUE THREAD

**Issue by Strideradu** [tensorflow/tensorflow#6001]
I just setup gpu supported tensorflow on my windows 10 PC following https://developers.googleblog.com/2016/11/tensorflow-0-12-adds-support-for-windows.html

But right now I found I cannot use my GPU as it is a GeForece GTX760 and only has 3.0 CUDA compute capability

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

There are several discussion for linux and MAC tensorflow, as they can build from source so they can just change the list of the computer capability. right now I cannot build from source so I am wondering if there are any other way to change the setup?

### Environment info
Operating System:
Windows 10 64bit

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
CUDA 8.0
cuDNN 5.1

**Comment by LucasSloan** [comment]
Also running into this issue on Windows 10 with a Quadro K1000M.

**Comment by mrry** [comment]
For binary size reasons, we don't provide pre-built binaries that include code for CC 3.0 devices, so you'll need to build from source. You can follow the steps for the [CMake build](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake) with modifications to `CMakeLists.txt` on [this line](https://github.com/tensorflow/tensorflow/blob/a7b4f636d50b6fcb9cd1f7f138cc50b720fc86dd/tensorflow/contrib/cmake/CMakeLists.txt#L156) and [this line](https://github.com/tensorflow/tensorflow/blob/a7b4f636d50b6fcb9cd1f7f138cc50b720fc86dd/tensorflow/contrib/cmake/CMakeLists.txt#L166) to set a compute capability of `3.0` (instead of `3.5` and `5.2`).

**Comment by sunnybear** [comment]
very funny. No config support, no pre-built support. WTF?
