### ISSUE TITLE
Include tf.IsInf on Tensorflow Lite Operators

### ISSUE THREAD

**Issue by JuanuMusic** [tensorflow/tensorflow#60011]
**System information**
- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux
- TensorFlow installed from (source or binary): binary
- TensorFlow version (or github SHA if from source): 2.11

**Provide the text output from tflite_convert**

```
<unknown>:0: error: failed while converting: 'main': 
Some ops in the model are custom ops, See instructions to implement custom ops: https://www.tensorflow.org/lite/guide/ops_custom 
Custom ops: IsInf
Details:
	tf.IsInf(tensor<?x21x?xf64>) -> (tensor<?x21x?xi1>) : {device = ""}
	tf.IsInf(tensor<?x33x?xf64>) -> (tensor<?x33x?xi1>) : {device = ""}
```

**Standalone code to reproduce the issue** 
Provide a reproducible test case that is the bare minimum necessary to generate
the problem. If possible, please share a link to Colab/Jupyter/any notebook.

Also, please include a link to a GraphDef or the model if possible.

**Any other info / logs**

Include any logs or source code that would be helpful to diagnose the problem.
If including tracebacks, please include the full traceback. Large logs and files
should be attached.

**Comment by synandi** [comment]
Hi @JuanuMusic,
As mentioned in the error, as a workaround you can create your own custom implementation of an unsupported TensorFlow operator in TensorFlow Lite, known as a custom operator by following the instructions mentioned [here](https://www.tensorflow.org/lite/guide/ops_custom). Thank you!

**Comment by JuanuMusic** [comment]
Hi! Yes, I know, but its also suggested to open an Issue to request to add. I think it's an important operator since there are some pre-procesdsing strategies that indeed require it.

**Comment by pkgoogle** [comment]
HI @JuanuMusic,

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/LiteRT/issues/140).

Let us know if you have any questions. Thanks.
