### ISSUE TITLE
Build failure: enumeration value ‘kFP8’ not handled in switch [-Werror=switch]

### ISSUE THREAD

**Issue by VermiIIi0n** [tensorflow/tensorflow#60031]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

Latest master branch (3.17), tf-nightly 2.13

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 22.04

### Python version

3.10.9

### Bazel version

5.3.0

### GCC/Compiler version

11

### CUDA/cuDNN version

CUDA12.1 cuDNN8.8.1 TensorRT8.6.0

### GPU model and memory

RTX 3070 8G

### Current Behaviour?

```shell
Cannot build with bazel

ERROR: /tmp/tensorflow/tensorflow/compiler/tf2tensorrt/BUILD:188:11: Compiling tensorflow/compiler/tf2tensorrt/common/utils.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/tf2tensorrt/_objs/common_utils/utils.pic.d ... (remaining 176 arguments skipped)
tensorflow/compiler/tf2tensorrt/common/utils.cc: In function ‘std::ostream& nvinfer1::operator<<(std::ostream&, const nvinfer1::DataType&)’:
tensorflow/compiler/tf2tensorrt/common/utils.cc:209:10: error: enumeration value ‘kFP8’ not handled in switch [-Werror=switch]
  209 |   switch (v) {
      |          ^
cc1plus: some warnings being treated as errors
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```

### Standalone code to reproduce the issue

```shell
bazel build --config=cuda --cxxopt="-march=native" --cxxopt="-O3" //tensorflow/tools/pip_package:build_pip_package
```

### Relevant log output

```shell
/tmp/tensorflow/tensorflow/compiler/tf2tensorrt/BUILD:188:11: Compiling tensorflow/compiler/tf2tensorrt/common/utils.cc failed: (Exit 1): crosstool_wrapper_driver_is_not_gcc failed: error executing command external/local_config_cuda/crosstool/clang/bin/crosstool_wrapper_driver_is_not_gcc -MD -MF bazel-out/k8-opt/bin/tensorflow/compiler/tf2tensorrt/_objs/common_utils/utils.pic.d ... (remaining 176 arguments skipped)
tensorflow/compiler/tf2tensorrt/common/utils.cc: In function ‘std::ostream& nvinfer1::operator<<(std::ostream&, const nvinfer1::DataType&)’:
tensorflow/compiler/tf2tensorrt/common/utils.cc:209:10: error: enumeration value ‘kFP8’ not handled in switch [-Werror=switch]
  209 |   switch (v) {
      |          ^
cc1plus: some warnings being treated as errors
Target //tensorflow/tools/pip_package:build_pip_package failed to build
```
</details>

**Comment by linuxmetel** [comment]
I got the same problem while compiling [v2.12.0-rc1](https://github.com/tensorflow/tensorflow/tree/v2.12.0-rc1).

I find new DataType `kFP8` added between 8.5.3 and 8.6.0 of TensorRT. (API Reference: [8.5.3](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-853/api/c_api/namespacenvinfer1.html#a83aed11a1c160f30dcd13809678bdd29), [8.6.0](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-860-ea/api/c_api/namespacenvinfer1.html#a83aed11a1c160f30dcd13809678bdd29)) And, in the `case` block, enumeration value ‘kFP8’ hasn't handled in switch yet.

https://github.com/tensorflow/tensorflow/blob/v2.12.0-rc1/tensorflow/compiler/tf2tensorrt/convert/weights.cc#L61-L76

I think this problem will be fixed by adding a case for `kFP8` with `IS_TRT_VERSION_GE` macro. According to [API Reference](https://docs.nvidia.com/deeplearning/tensorrt/api/c_api/namespacenvinfer1.html#abdc74c40fe7a0c3d05d2caeccfbc29c1a7397615c6bee5b62289fc7cceb82fbf7), `kFP8` is not supported yet and maybe some codes to generate assert error should be inserted.

**Comment by SuryanarayanaY** [comment]
@linuxmetel ,

Thanks for the PR. Our Team will review and get back to you if any more details needed. Thanks!
