### ISSUE TITLE
TensorArray throws AttributeError in gradient computation 

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60048]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### Current Behaviour?

```shell
The [documentation](https://www.tensorflow.org/api_docs/python/tf/TensorArray) claims that TensorArray "supports gradient back-propagation via special "flow" control flow dependencies". However, it seems that `TensorArray` is an [unsupported type](https://github.com/tensorflow/tensorflow/blob/d5b57ca93e506df258271ea00fc29cf98383a374/tensorflow/python/ops/gradient_checker_v2.py#L261) for gradient computation at the moment. It would be great if there is clarification, in documentation or better error message.
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

elems = tf.ones(shape=[2])

def init_tensor_array(elems):

    ta = tf.TensorArray(dtype=tf.float32, size=4, dynamic_size=True)
    ta = ta.write(0, elems)
    return ta

ta = init_tensor_array(elems)
with tf.GradientTape() as tape:
    tape.watch(elems)
    t = init_tensor_array(elems)

gradient = tape.jacobian(t, elems)
```

### Relevant log output

```shell
AttributeError: 'TensorArray' object has no attribute 'shape'
```
</details>

**Comment by SuryanarayanaY** [comment]
Hi @trickiwoo,

As TensorArray is a wrapper class for dynamic sized,, per-time-step, Tensor arrays. Also from documentation this class is meant to be used with dynamic iteration primitives such as `while_loop` and `map_fn`. 

It supports gradient `back-propagation` via special "flow" control flow dependencies. Please also refer to [tf.raw_ops](https://www.tensorflow.org/api_docs/python/tf/raw_ops) which confirms it supports gradient.

For your case mentioned since they are not using any dynamic iteration primitives, you can use `tf.stack()` to collect all elements at once and then apply gradients or use `tf.read()` iteratively to collect elements one by one and apply gradients.
However the correct way to use TensorArray is by using with dynamic iteration primitives such as `while_loop` and `map_fn`.

I just added a simple gist here for your reference. Please let us know if it helps.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @trickiwoo ,

Could I know what error message you want to display?(I assuming you want to display the error regarding the usage of TensorArray w.r.t Gradients). Due to performance reasons all the checks are not getting validated. If you want to propose some changes to documentation or want to accommodate user error or want to add some more example codes please feel free to propose a PR and Team may happily review it. 

Thanks!
