### ISSUE TITLE
tf.py_function throws KeyError when computing Jacobian matrix

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60084]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### Current Behaviour?

```shell
tf.py_function throws KeyError when computing Jacobian matrix. It works well when it is computing gradient.
```

### Standalone code to reproduce the issue

```shell
import os
import tensorflow as tf
import numpy as np

a = tf.Variable([1.0, 2.0])

def square(a):
    return tf.py_function(lambda a: a ** 2, [a], a.dtype)

with tf.GradientTape(persistent=True) as tape:
    tape.watch(a)
    y = square(a)
# gradient = tape.gradient(y, a) # pass
jacobian = tape.jacobian(y, a)
print(jacobian)
```

### Relevant log output

```shell
Node: 'gradient_tape/EagerPyFunc'
KeyError: b'pyfunc_0'


         [[{{node gradient_tape/EagerPyFunc}}]] [Op:__inference_f_173]
```
</details>

**Comment by synandi** [comment]
Hi @trickiwoo, Apologies for the delay. We were able to replicate the issue in Colab using TF v2.11. Please find the gist [here](https://colab.sandbox.google.com/gist/synandi/40e7a6bb108d9a9b97bcbe76ab0c67da/60084.ipynb). It seems like we have to dig deep into the issue, we'll update here soon. Thank you!

**Comment by Venkat6871** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
