### ISSUE TITLE
tf.raw_ops.Round doesn't have a gradient

### ISSUE THREAD

**Issue by trickiwoo** [tensorflow/tensorflow#60093]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.11

### Custom Code

Yes

### Current Behaviour?

```shell
The function tf.raw_ops.Round does not have a gradient, however, it is mentioned in the documentation (https://www.tensorflow.org/api_docs/python/tf/raw_ops) that it does. Despite this inconsistency, the code operates correctly as intended.
```

### Standalone code to reproduce the issue

```shell
import os
import tensorflow as tf
import numpy as np

x = tf.Variable([1.5, -1.5], dtype=tf.dtypes.float64)

def rounding(x):

    round_op = tf.raw_ops.Round(x=x)
    return round_op

t1 = rounding(x)
with tf.GradientTape() as tape:
    tape.watch(x)
    t = rounding(x)

gradient = tape.gradient(t, x)
print(gradient)
```

### Relevant log output

```shell
None
```
</details>

**Comment by mayankagarwals** [comment]
Hey @trickiwoo , 

Yes, rounding functions have a finite range and hence gradient zero. Although there are approximations available (refer [here](https://stackoverflow.com/questions/46596636/differentiable-round-function-in-tensorflow)), I don't think that's what documentation would be referring to. Can you point me to the exact line in documentation referring to this so I can raise a PR fixing it

**Comment by mayankagarwals** [comment]
@sushreebarsa the problem is we are registering gradient for round function in registry https://github.com/tensorflow/tensorflow/blob/f46ff5e9cfff71a4de98a8aac79d44df27df48f4/tensorflow/python/ops/math_grad.py#L1812 
And the logic to add documentation is whether a op is present in registry or not
https://github.com/tensorflow/tensorflow/blob/f46ff5e9cfff71a4de98a8aac79d44df27df48f4/tensorflow/tools/docs/generate2.py#L143

**Comment by sushreebarsa** [comment]
@trickiwoo Thank you for raising an issue!
Could you please refer to the comments above and let us know if you want these changes in the documentation?
@mayankagarwals Thank you for your response here. 

As per my understanding, some tf.Operations are registered as being non-differentiable and will return None. Others have no gradient registered.

The tf.raw_ops page shows which low-level ops have gradients registered.

If you attempt to take a gradient through a float op that has no gradient registered the tape will throw an error instead of silently returning None. This way you know something has gone wrong.

For example, the tf.image.adjust_contrast function wraps raw_ops.AdjustContrastv2, which could have a gradient but the gradient is not implemented.

Thank you!

**Comment by trickiwoo** [comment]
@sushreebarsa @mayankagarwals  Thank you for the comments! I didn't know that "has gradient" means "has gradient registered" but it can still be non-differentiable. I think it would be helpful to make it clear in the document, or even better, only mark the differentiable ops as "has gradient" (not sure if that can be done easily though).

Further, I wonder why register a `None` gradient (say for `round`) instead of don't register at all? In my understanding, it is better to throw an error for the non-differentiable operator, instead of silently returning None for the whole computation.

**Comment by sachinprasadhs** [comment]
Hi registering gradient to return None for `Round` to silently return None instead of throwing error when doing gradient computation.
```
@ops.RegisterGradient("Round") 
def _RoundGrad(_, unused_grad): 
    return [None]
```
