### ISSUE TITLE
Editing Tensorboard graphs

### ISSUE THREAD

**Issue by vedhas** [tensorflow/tensorflow#6012]
Thanks for the powerful package, equipped with an awesome tensorboard like visualization environment.

There is just one issue. Graphs generated under Tensorboard occupy too much space than necessary, which makes it difficult to understand what is going on, thanks to consequent relative reduction in font size for all the blocks. It would be really helpful if user could move the nodes around, such that rearranged view is printer friendly, and also user friendly. Please implement the feature soonest you can, as it will help newbies like me (and anyone in general, since this package too is quite new relatively) to ramp up quickly, and also for debugging the code. Thank you.

Vedhas

**Comment by danmane** [comment]
This would be a really involved change, since we passively rely on dagre for layout of the graph. If we took a naive approach to adding draggable nodes, it would reset every time the user collapsed or expanded a node. 

It may be there are simpler approaches for solving your problem, e.g. filtering out certain subsections of the graph so that it is easier to display and understand. In any case, I am going to mark this issue "Contributions Welcome" in case someone else wants to take it on, but adding manual graph layout is not on our roadmap.

**Comment by vedhas** [comment]
I notice that there is option to download the graph as a png image. How about making another downloadable format available? Perhaps SVG, which people can edit easily on inkscape/gimp like tools for own documentation...

**Comment by chihuahua** [comment]
I closed this issue (because TensorBoard is moving into its own repo outside of tensorflow/tensorflow), and started another issue to track @vedhas's proposal of having the graph explorer provide SVGs: tensorflow/tensorboard#66
