### ISSUE TITLE
[Feature Request] MatrixSquareRoot for tflite

### ISSUE THREAD

**Issue by petered** [tensorflow/tensorflow#60154]
Tensorflow lite currently will not compile graphs containing `tf.linalg.sqrtm`.  If you try, you get 

```
Some ops in the model are custom ops, See instructions to implement custom ops: https://www.tensorflow.org/lite/guide/ops_custom 
Custom ops: MatrixSquareRoot
Details:
	tf.MatrixSquareRoot(tensor<3x3xf32>) -> (tensor<3x3xf32>) : {T = f32, device = ""}
```

As a work around, I am using an approximate solution:

```
def tf_denmann_beavers_sqrtm(matrix: TensorInvCovMat, n_iter=10):
    """
    Approximate the matrix-square-root by Denmann Beavers iteration
        https://en.wikipedia.org/wiki/Square_root_of_a_matrix#By_Denman%E2%80%93Beavers_iteration
    Convergence is not guaranteed.  Use at your own risk!
    """
    ym = matrix
    zm = tf.eye(tf.shape(matrix[0])[0], dtype=matrix.dtype)
    for i in range(n_iter):
        ym_ = 0.5 * (ym + tf.linalg.inv(zm))
        zm = 0.5 * (zm + tf.linalg.inv(ym))
        ym = ym_
    return ym
```

But it is not ideal.  

Can we please get `tf.linalg.sqrtm` included as a standard tflite op?

**Comment by sachinprasadhs** [comment]
Hi, Thanks for the feature request. 
Right now, we don't have all the tensorflow ops under TFLite builtin ops. 
We will update in the document when it is available. 
Till then you can use the SELECT_TF_OPS to enable Tensorflow ops as below.

```
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
```

**Comment by petered** [comment]
I'd say it's worth keeping open, data whitening is pretty common operation
and this is a part of it

**Comment by pkgoogle** [comment]
Hi @vamsimanchala, can you please take a look? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @petered 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/178

Let us know if you have any questions. Thanks.
