### ISSUE TITLE
pip install tensorflow==2.11.1 not working on AWS arm64 

### ISSUE THREAD

**Issue by rhuddleston** [tensorflow/tensorflow#60204]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

2.11.1

### Custom Code

No

### OS Platform and Distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current Behaviour?

```shell
When I run `pip install tensorflow==2.11.1` on an aws m6g.large instance (arm64 graviton) it throws the following error:

ERROR: Could not find a version that satisfies the requirement tensorflow-cpu-aws==2.11.1; platform_system == "Linux" and (platform_machine == "arm64" or platform_machine == "aarch64") (from tensorflow) (from versions: 2.9.1, 2.10.0rc0, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0rc1, 2.12.0)
ERROR: No matching distribution found for tensorflow-cpu-aws==2.11.1; platform_system == "Linux" and (platform_machine == "arm64" or platform_machine == "aarch64")

I can see this is the case by navigating here: https://pypi.org/project/tensorflow-cpu-aws/2.11.1/#files

for some reason it was only built for python 3.7 and is lacking binaries for all other python versions. tensorflow 2.11.0 and 2.12.0 both work but we wanted to use 2.11.1 in this case, perhaps an error during that particular build?

For example compare to this: https://pypi.org/project/tensorflow-cpu-aws/2.11.0/#files or the 2.12.0
```

### Standalone code to reproduce the issue

```shell
`pip install tensorflow==2.11.1` on python 3.10 on an aws m6g instance
```

### Relevant log output

_No response_</details>

**Comment by tiruk007** [comment]
@rhuddleston 
Sorry for the late reply, Could you please try with `pip install tensorflow==2.11.*` to install  TF 2.11. I was able to install the TF2.11 without any error on the linux virtual machine with python 3.10. Please find the screenshots below:
[Screenshot 1(https://user-images.githubusercontent.com/111861663/229890752-269caf0a-6bc3-4d24-b233-58d4858facd8.png)
[Screenshot 2(https://user-images.githubusercontent.com/111861663/229890807-259d86a8-94ea-4a53-be43-7679f0638e43.png)


Thank you !

**Comment by carlthome** [comment]
Also been having issues on a macOS M1 with pipenv.

Recently, Dependabot wanted to bump `tensorflow` to 2.11.1 but that caused a version mismatch between `tensorflow-cpu-aws` so now `python -c "import tensorflow"` fails to find the import and `pipenv graph` has this:

```sh
tensorflow==2.11.1
  - tensorflow-cpu-aws [required: ==2.11.1, installed: ?]
```

**Comment by tilakrayal** [comment]
@rhuddleston,
The package tensorflow-cpu-aws is meant for **Arm/AArch64** processors and it can't be downloaded in `X86_64` architectures through pip. 

Pip will try to resolve the wheels suitable for the particular host platform and if it is not found then it raises the error like no matching distribution found.

The pre-built pip wheels for X86_64 built and maintained by tensorflow itself which you can install through pip install tensorflow-cpu and this can be installed on x86_64 machines only.

Could you please refer the documentation [source](https://www.tensorflow.org/install/pip#linux:~:text=Nightly-,Note%3A%20Starting%20with%20TensorFlow%202.10%2C%20Linux%20CPU%2Dbuilds%20for%20Aarch64,package.%20See%20this%20blog%20post%20for%20more%20information%20about%20this%20collaboration.,-conda%20install%20%2D) for more details.

This does not look like a problem that is specific to TensorFlow. I think your problem is all about creating a docker container for a foreign architecture from your x86 machine. In order to do that you need to add qemu to the mix so that there is an environment that allows the docker container to execute.
See https://www.docker.com/blog/multi-platform-docker-builds/

Thank you!
