### ISSUE TITLE
Bazel build issue

### ISSUE THREAD

**Issue by yama-can** [tensorflow/tensorflow#60217]
ERROR: Config value 'opt' is not defined in any .rc file
comes out.

**Comment by tilakrayal** [comment]
@yama-can,
In order to expedite the trouble-shooting process, could you please provide the following information OS Platform, TensorFlow version, Installed using virtualenv? pip? conda?, Bazel version, GCC/Compiler version, CUDA/cuDNN version.

Also there is a similar issue already assigned to the developer which is still in progress and requesting to follow the same for the updates.
https://github.com/tensorflow/tensorflow/issues/58453
 Thank you!

**Comment by mraunak** [comment]
@yama-can, since you have used --config=opt, I think you are running it on CPU/windows. you need to run configure.py (located at https://github.com/tensorflow/tensorflow/blob/master/configure.py) before you can the build command(bazel build --config=opt //tensorflow/tools/pip_package:build_pip_package)

![image](https://user-images.githubusercontent.com/83710963/231277832-27499835-ad99-4980-8f50-f8e3fbead3c4.png)

**Comment by yama-can** [comment]
Thank you!!
I have successfully built tensorflow.

**Comment by SuryanarayanaY** [comment]
@yama-can ,

@mraunak given the right answer.

Whenever we choose `--config=opt`option in bazel build command, we must run `./configure.py` and this is mandatory for this option. During `./configure.py` there will be default option for this based on the platform we are using. Please refer the below line from `/configure.py` where default is chosen already based on the platform. 

**For windows:**
`Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is /arch:AVX]:`

**For Linux:**
`Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -Wno-sign-compare]:`

If you would have run the `./configure.py` then it might be resolved already for you. Please feel free to close the issue if resolved already. Thanks!
