### ISSUE TITLE
Problem on installation document, wrong $LD_LIBRARY_PATH

### ISSUE THREAD

**Issue by KiWeng** [tensorflow/tensorflow#60229]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

No

### Source

binary

### Tensorflow Version

tf v2.12

### Custom Code

No

### Current Behaviour?

```shell
bug:
mkdir -p $CONDA_PREFIX/etc/conda/activate.d
CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh

symptom:
error on creating $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh, causing the $LD_LIBRARY_PATH cannot be set properly, using single quotes instead of double quotes

solution:
CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))
echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:${CUDNN_PATH}/lib" > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
```

### Standalone code to reproduce the issue

```shell
mkdir -p $CONDA_PREFIX/etc/conda/activate.d
CUDNN_PATH=$(dirname $(python -c "import nvidia.cudnn;print(nvidia.cudnn.__file__)"))
echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/:$CUDNN_PATH/lib' > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh
```

### Relevant log output

_No response_</details>

**Comment by sushreebarsa** [comment]
@KiWeng  Could you have a look at this [PR](https://github.com/tensorflow/docs/pull/2217) which might resolve this issue?
Thank you!

**Comment by maurerle** [comment]
@KiWeng - just to mention that the proposed solution here does not solve this issue properly as using double quotes would also resolve the left hand side of the phrase, while `$LD_LIBRARY_PATH` should stay unresolved.

So one would have to use `echo 'export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:'"$CONDA_PREFIX/lib/:$CUDNN_PATH/lib" > $CONDA_PREFIX/etc/conda/activate.d/env_vars.sh` - note use of single quotes for the first part and double quotes (which resolve the variable) for the second part.

But it is now fixed in the PR I submitted - which will hopefully go online soon.

**Comment by KiWeng** [comment]
@sushreebarsa @maurerle Thanks, I think the problem is now solved
