### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute '__version__'

### ISSUE THREAD

**Issue by stonecropa** [tensorflow/tensorflow#60333]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12

### Custom Code

Yes

### OS Platform and Distribution

win10

### Python version

Python3.8.16

### CUDA/cuDNN version

11.7

### Current Behaviour?

A bug happened!

### Standalone code to reproduce the issue

```shell
code is too long
```

### Relevant log output

```shell
(reflow1) PS E:\Googledownload\RectifiedFlow-main\ImageGeneration> python ./main.py --config ./configs/rectified_flow/cifar10_rf_gaussian_ddpmpp.py --eval_folder eval --mode eval --workdir ./logs/1_rectified_flow --config.eval.enable_sampling  --config.eval.batch_size 250 --config.eval.num_samples 3000 --config.eval.begin_ckpt 8
Traceback (most recent call last):
  File "./main.py", line 18, in <module>
    import run_lib
  File "E:\Googledownload\RectifiedFlow-main\ImageGeneration\run_lib.py", line 26, in <module>
    import tensorflow_gan as tfgan
  File "D:\conda\envs\reflow1\lib\site-packages\tensorflow_gan\__init__.py", line 108, in <module>
    _ensure_tf_install()
  File "D:\conda\envs\reflow1\lib\site-packages\tensorflow_gan\__init__.py", line 60, in _ensure_tf_install
    if (distutils.version.LooseVersion(tf.__version__) <
AttributeError: module 'tensorflow' has no attribute '__version__'
```
</details>

**Comment by Himanshuch1708** [comment]
The error message "AttributeError: module 'tensorflow' has no attribute 'version'" suggests that TensorFlow is not properly installed or loaded in your Python environment.

Here are some suggestions that you can try to resolve the issue:

- Check the TensorFlow installation: Make sure that TensorFlow is properly installed in your Python environment. You can check the TensorFlow installation by running the following command in your Python environment:

```sh
import tensorflow as tf
print(tf.__version__)
```
If this returns an error, you may need to reinstall TensorFlow.

- Check for naming conflicts: It's possible that there is a naming conflict with another module or package that is causing the issue. Try renaming any variables or modules that have the same name as TensorFlow.

- Check the Python environment: Make sure that you are running your code in the correct Python environment. You can verify the Python environment by checking the output of the which python command in your terminal or command prompt.

- Upgrade TensorFlow: Try upgrading TensorFlow to the latest version using pip install --upgrade tensorflow.
- Make sure TensorFlow is properly installed and up-to-date. You can check the installation and version by running
 ```pip list | grep tensorflow``` in your command prompt or terminal.

- Try importing TensorFlow in a separate Python shell to check if it's properly installed and the version is correct.

If none of these suggestions work, please provide more details such as the full error message and any other relevant information about your system or code.

**Comment by saurabhmj11** [comment]
The error message "AttributeError: module 'tensorflow' has no attribute 'version'" is indicating that the version of TensorFlow you are using does not have the "version" attribute, which is usually present in TensorFlow versions. This could be due to a number of reasons, including an incorrect installation or an issue with the Python environment.

Here are some steps that you can follow to resolve the issue:

Make sure that TensorFlow is installed correctly. You can do this by running the following command:

perl
Copy code
pip list | grep tensorflow
If TensorFlow is installed, you should see it listed in the output. If it is not installed, you can install it using the following command:

Copy code
pip install tensorflow
Check the version of TensorFlow that you are using. You can do this by running the following command:

scss
Copy code
python -c "import tensorflow as tf; print(tf.__version__)"
If you see an error message or an incorrect version number, it is possible that you have multiple versions of TensorFlow installed, or that your Python environment is not set up correctly.

Make sure that you are using the correct version of TensorFlow in your Python environment. If you have multiple versions of TensorFlow installed, you can specify which version to use by adding the following line of code at the beginning of your script:

python
Copy code
import tensorflow as tf
tf.compat.v1.disable_eager_execution() # disabling eager execution
This will ensure that your script is using the correct version of TensorFlow.

If none of the above steps work, try creating a new Python environment and installing TensorFlow in it. This will ensure that there are no conflicts with other packages or dependencies.

Hopefully, one of these steps will resolve the issue you are facing

**Comment by tilakrayal** [comment]
@stonecropa,
The error message which was mentioned "AttributeError: module 'tensorflow' has no attribute '__version__'" suggested that the TensorFlow is not properly installed or loaded.

Please check the above comments provided by the community and adding to the above comments, here you might have tried to uninstall and install tensorflow. There might be the  chances of the environment using two kinds of tensorflows. Could you please try creating a new environment and start fresh it would work. And never place with the tensorflow versions again. [Reference](https://stackoverflow.com/questions/61554548/attributeerror-module-tensorflow-has-no-attribute-version) 
https://github.com/matterport/Mask_RCNN/issues/795
Thank you!

**Comment by sachinprasadhs** [comment]
Hi, 

Could you please try installing Tensorflow 2.13 using WSL2 for Windows and let us know if that solves your problem.

Refer this link for more details: https://www.tensorflow.org/install/pip

**Comment by jeus1609** [comment]
verifica que tus archivos no se llamen tensorflow.py
