### ISSUE TITLE
error: undefined reference to 'TfLiteGpuDelegateBindGlBufferToTensor'

### ISSUE THREAD

**Issue by picard314** [tensorflow/tensorflow#60403]
Hi @impjdi the amazing porygon~,

I've checkout-ed the branch "v2.10.0" for deploying tflite on Android. In order to avoiding cpu-gpu memory copy, I used the function 'TfLiteGpuDelegateBindGlBufferToTensor' but got logs saying as the issue title during project configuration.

BTW, 
I had #include "tensorflow/lite/delegates/gpu/cl/gpu_api_delegate.h"
I had compiled "libtensorflowlite.so", "libtensorflowlite_gpu_delegate.so", and all those .h included by my project

Please can you shed me some light?

Thanks~

**Comment by picard314** [comment]
> 

Hi @tilakrayal，

Sorry, I should have noticed that you are the Assignee right now. Please can you shed me some light on this issue?

Thanks~

**Comment by pjpratik** [comment]
Hi @picard314 

The `TfLiteGpuDelegateBindGlBufferToTensor` should be able to refer by inclusion of gpu_api_delegate.h

https://github.com/tensorflow/tensorflow/blob/41c3f9ed867b91b8922c6f5828ecce63c85188dd/tensorflow/lite/delegates/gpu/cl/gpu_api_delegate.h#L91

Could you please provide more details or a sample code snippet to reproduce the error?

Thanks

**Comment by picard314** [comment]
Hi, @sachinprasadhs @impjdi 

May I lit up this issue again~ Thanks for your attention!

Now I guess my "libtensorflowlite_gpu_delegate.so" (attached) may be insufficient. It was got by running

bazel build -c opt --config android_arm64 --copt -DCL_DELEGATE_NO_GL --copt -DTFLITE_GPU_BINARY_RELEASE --linkopt -s tensorflow/lite/delegates/gpu:libtensorflowlite_gpu_delegate.so

, with logs looking correct. What do you say please~

I am looking forward to your replies. Thanks again!

Best,
picard314

**Comment by gaikwadrahul8** [comment]
Hi, @picard314 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/176

Let us know if you have any questions. Thanks.
