### ISSUE TITLE
tf.raw_ops.GatherV2 api doc page does not properly describe the argument 'batch_dims' 

### ISSUE THREAD

**Issue by meghendra** [tensorflow/tensorflow#60419]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Documentation Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

tf 2.12.0

### Custom Code

Yes

### Current Behaviour?

The doc page for `tf.raw_ops.GatherV2` [here](https://www.tensorflow.org/api_docs/python/tf/raw_ops/GatherV2) does not describe how `batch_dims` is used in the operator. I found one stack overflow comment [here ](https://stackoverflow.com/questions/58194682/how-to-set-the-parameter-batch-dims-in-tf-gather-nd-tensorflow) that says:

``batch_dims=N informs TF that the first N dimensions of the tensor are batch dimensions...``

If this is indeed correct, it should be included in the doc page. Otherwise the behavior of `batch_dims` parameter is difficult to understand.

### Standalone code to reproduce the issue

```shell
Its a missing detail in the documentation for `tf.raw_ops.GatherV2.
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @meghendra ,

Thanks for your time in bringing this. Basically `tf.raw_ops` not meant for end users but for library writers and hence documentation is not much exhaustive. There is equivalent high level API for this which is [tf.gather](https://www.tensorflow.org/api_docs/python/tf/gather). 

However your pointed information is related to Argument description I agree to that it should have some explanation on argument. Hence I can add the same description that is there in `tf.gather` API for the argument `batch_dims` which is mentioned below.I would like to append this line to existing description.

`The number of batch dimensions. Must be less than or equal to rank(indices)`

Thanks!

**Comment by kiransair** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
