### ISSUE TITLE
How to download outdated versions of Tensorflow in Google Colab?

### ISSUE THREAD

**Issue by luishbastos** [tensorflow/tensorflow#60453]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf 2.5

### Custom Code

Yes

### OS Platform and Distribution

Colab

### Python version

3.11

### Bazel version

3.7.2

### Current Behaviour?

I have a project using Mask RCNN, and the project only works with Tensorflow 2.5, but this version is outdated and the pip doesn't support this version anymore, when I'm trying to build on colab using the "Build from Source" documentation, 

When I try to use bazel I get an error while trying to build it

````
!bazel build --config=cuda //tensorflow/tools/pip_package:build_pip_package
````

Also when I try to use pip

````
!pip install git+https://github.com/tensorflow/tensorflow.git@r2.5
````

I get the following error
````
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/tensorflow/tensorflow.git@r2.5
  Cloning https://github.com/tensorflow/tensorflow.git (to revision r2.5) to /tmp/pip-req-build-f6mzej4m
  Running command git clone --filter=blob:none --quiet https://github.com/tensorflow/tensorflow.git /tmp/pip-req-build-f6mzej4m
  Running command git checkout -b r2.5 --track origin/r2.5
  Switched to a new branch 'r2.5'
  Branch 'r2.5' set up to track remote branch 'r2.5' from 'origin'.
  Resolved https://github.com/tensorflow/tensorflow.git to commit 959e9b2a0c06df945f9fb66bd367af8832ca0d28
ERROR: git+https://github.com/tensorflow/tensorflow.git@r2.5 does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
````

### Standalone code to reproduce the issue

```shell
You can reproduce it by using this colab

https://colab.research.google.com/github/Huxwell/caffe-tf-torch-darknet-onnx/blob/main/tensorflow_from_source.ipynb
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @luishbastos ,

Colab recently stopped support for Tensorflow Versions older than 2.8v. You can't download older versions directly with `pip install tensorflow==x` . The command `!pip install git+https://github.com/tensorflow/tensorflow.git@r2.12` not even working with TF 2.12 versions which might be due to the way TF repo constructed,since `setup.py` not located at the root of tensorflow project directory but under sub directories at path [here](https://github.com/tensorflow/tensorflow/blob/r2.5/tensorflow/tools/pip_package/setup.py).

Tensorflow team not actively supporting older TF versions and this might be the reason why Colab dropped support for TF<2.8 versions. Nevertheless you may ask the reason for same at `googlecolab` repo also if required.

However for your case you may use Anaconda environment/jupyter notebook and install TF 2.5 version by `pip install tensorflow==2.5`.However we are not supporting older versions now and we recommend to use latest versions and we can be helpful in case of any problems with latest versions.

Thanks!
