### ISSUE TITLE
Issue when importing pix2pix in Google Colab

### ISSUE THREAD

**Issue by matheovlk** [tensorflow/tensorflow#60546]
Hello, I wanted to use pix2pix in Google Colab and here is the command I used to import it:

!pip install git+https://github.com/tensorflow/examples.git

I also tried !pip install -q git+https://github.com/tensorflow/examples.git

But for both request, I get this error:

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/tensorflow/examples.git
  Cloning https://github.com/tensorflow/examples.git to /tmp/pip-req-build-z5dheb37
  Running command git clone --filter=blob:none --quiet https://github.com/tensorflow/examples.git /tmp/pip-req-build-z5dheb37
  Resolved https://github.com/tensorflow/examples.git to commit 1ca61321294cd2e97efc021ff1b3700b42befd0b
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Preparing metadata (setup.py) ... error
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

Could you please repair it?
Best regards

P.S.: If there is any way for me to use pix2pix in an alternative way, could you please indicate me on how to do it because I did not found an alternative.

**Comment by tilakrayal** [comment]
@matheovlk,
Could you please try to clone the TensorFlow example repository from GitHub. Use from `examples.tensorflow_examples.models.pix2pix import pix2pix` instead of from `tensorflow_examples.models.pix2pix `import pix2pix, Now you can use 'pix2pix' package. Kindly find the gist [here](https://colab.research.google.com/gist/tiruk007/180bc730fb886639f987ba4c993c50ec/segmentation.ipynb#scrollTo=YQX7R4bhZy5h) for reference.

Also please have a look at this [comment](https://github.com/tensorflow/tensorflow/issues/60213#issuecomment-1495942281) from the community. Thank you!

**Comment by matheovlk** [comment]
It is working now, thank you!
