### ISSUE TITLE
accuracy.eval on MNIST, extremely slow on Win7, P3.5 CPU only

### ISSUE THREAD

**Issue by Roboball** [tensorflow/tensorflow#6056]
Hi I tested the MNIST tutorial on Win7, Python3.5, CPU only. Icore5.
Tested with Geany+CMD console, and Idle+Python shell.

I found that everything runs fine, but the accuracy.eval routine takes more than 20min to run on the MNIST test data. Normally that is done within less than a minute (Ubuntu).  As soon as the evaluation starts, I am not able to use any other programs. Looks like the CPU is completely blocked by calculations from the eval routine. Any idea how to optimize??

print("test accuracy %g"%accuracy.eval(feed_dict={
    x: mnist.test.images, y_: mnist.test.labels, keep_prob: 1.0}))

**Comment by poxvoculi** [comment]
The ubuntu OS evaluation you're comparing for speed, is that on the same processor?  (I.e. is it a dual-boot system?)  Otherwise it's not clear from what you've posted that the Win7/ICore5 system you're comparing it to is as capable.  MNIST is a simple model, most of the eval runtime is floating point matrix multiply.  Is it possible that somehow you're running out of memory and swapping?  That could cause a huge slowdown and also prevent you from being able to access another process.

**Comment by Roboball** [comment]
Ok, it is basically the same out of memory issue what people with GPUs 2-4GB VRAM encounter.  The I5-Win Machine  has only 6GB of RAM and about 8GB are needed to test MNIST quickly all at once. Ubuntu was an I7 16GB RAM, so no problem.

Solution to the problem: feed in batches. Recommendation: (I5,6GB ) batchsize=5000, and (QuadroK620,2GBVram) batchsize=1000. After that use numpy.mean to get the overall accuracy.
Ok, it is basically the same out of memory issue what GPU people with 2-4GB VRAM encounter.  The I5-Win Machine  has only 6GB of RAM and about 8GB are needed to test MNIST quickly all at once. Ubuntu was an I7 16GB RAM, so no problem.

Solution to the problem: feed in batches. Recommendation: (I5,6GB ) batchsize=5000, and (QuadroK620,2GBVram) batchsize=1000. After that use numpy.mean to get the overall accuracy.
