### ISSUE TITLE
TensorFlow not running

### ISSUE THREAD

**Issue by moses-mbaga** [tensorflow/tensorflow#60630]
Hello,

I am trying to create a BERT token using the tensorflow_hub library for python but whenever I run the code, it just gets stuck doesn't show any response.

Here's a screenshot to help:

![Screen Shot 2023-05-18 at 18 39 53](https://github.com/tensorflow/tensorflow/assets/55658291/9c7cdcb4-f1ee-4cd8-adf5-eae34a802fbe)

**Comment by SuryanarayanaY** [comment]
Hi @moses-mbaga ,

From the error log it seems the error is related to conda environment. If you are using conda environment while installing it will prompt to ask some thing like `Do you wish the installer to initialize Miniconda3 by running conda init? [yes|no]:` and you need to type `yes` there. Once it was done then run `source ~/.bashrc` to enable conda command and then run `conda activate <your_env_name>` to activate it.You can find conda environment creation steps [here](https://www.tensorflow.org/install/pip#step-by-step_instructions) for reference.

If followed above steps and still facing the problem then you can try `conda init <SHELL_NAME>` (eg: `conda init bash`) ,the `SHELL_NAME` can be `bash` or any others listed in the log. Please also refer to the conda websource here for more details.

After following above steps if still having problem please let us know. Also please fill the issue at tensorflow-hub repo [here](https://github.com/tensorflow/hub/issues) if the issue is only specific to tensorflow-hub.Also request you to follow the issue template for reporting the issue which can be found here for [tensorflow](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=&projects=&template=tensorflow_issue_template.yaml) and [tf-hub](https://github.com/tensorflow/hub/issues/new?assignees=&labels=type%3Abug%2Ctriage&projects=&template=BUG.yml&title=Bug%3A+) .

Thanks!

**Comment by moses-mbaga** [comment]
Noted,

Let me try the above then I will get back to you.

Thanks!

**Comment by SuryanarayanaY** [comment]
@moses-mbaga ,

Could you please confirm if the problem resolved for you. Thanks!
