### ISSUE TITLE
Problem importint load_img from tensorflow.keras.utils

### ISSUE THREAD

**Issue by franknganmo** [tensorflow/tensorflow#60746]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Build/Install

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12.0

### Custom Code

Yes

### OS Platform and Distribution

Windows

### Python version

3.10.11

### Current Behaviour?

Using load_img to import an image into my program's function

### Standalone code to reproduce the issue

```shell
ImportError: cannot import name 'load_img' from 'keras.preprocessing.image'
```

### Relevant log output

_No response_</details>

**Comment by SuryanarayanaY** [comment]
Hi @franknganmo ,

Could you please confirm the code snippet you are using ?

Please note that if you are using [tf.keras.preprocessing.image.load_img](https://www.tensorflow.org/api_docs/python/tf/keras/utils/load_img) API then it is deprecated and may not work.

Please use [tf.keras.utils.load_img](https://www.tensorflow.org/api_docs/python/tf/keras/utils/load_img) for the image loading purposes. For more details please refer to attached documentation sources.

I have also tested the imports in colab and found that `keras.preprocessing.image.load_img` not working as reported but `keras.utils.load_img ` is working.Please refer to attached [gist](https://colab.research.google.com/gist/SuryanarayanaY/75c5981c8802070f1e4b5c37f14f68c1/60746.ipynb).

Hope this will resolve your issue.

Thanks!

**Comment by franknganmo** [comment]
I use from tensorflow.keras.utils import load_img

**Comment by SuryanarayanaY** [comment]
Hi @franknganmo ,

I think you are using the API wrong. You have to call the API like `tf.keras.utils.load_img()`  .

From your code you calling it as image.load_img(img_path) which makes me think that you are calling the API on image which is not correct.Since if you have imported `load_img` already using  `tensorflow.keras.utils import load_img` then you can directly use it in code.

May be replacing` img=image.load_img(img_path)` with `img=load_img(img_path)` might works for you.

I have attached a sample colab gist on how to use this API . Please refer this and change code accordingly and let us know if it helps.

Thanks!

**Comment by franknganmo** [comment]
good
