### ISSUE TITLE
Docker image issue

### ISSUE THREAD

**Issue by nVietUK** [tensorflow/tensorflow#60777]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

tf v2.13.0-rc0-26-g57633696be6 2.13.0-rc1

### Custom Code

Yes

### OS Platform and Distribution

docker tf 2.13.0rc1-gpu-jupyter

### Python version

3.8.10

### CUDA/cuDNN version

Build cuda_11.8.r11.8/compiler.31833905_0

### GPU model and memory

RTX 2060 6GB

### Current Behaviour?

Could not load library libcublasLt.so.12. Error: libcublasLt.so.12: cannot open shared object file: No such file or directory

### Standalone code to reproduce the issue

```shell
https://github.com/projjal1/English-French-Translator-RNN/blob/master/English_French_Translator.ipynb
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@nVietUK,
`nvidia-docker v2` uses --runtime=nvidia instead of --gpus all. nvidia-docker v1 uses the nvidia-docker alias, rather than the **--runtime=nvidia or --gpus** all command line flags.

Download and run a GPU-enabled TensorFlow image:
`docker run --gpus all -it --rm tensorflow/tensorflow:latest-gpu \`

Use the latest TensorFlow GPU image to start a bash shell session in the container:
`docker run --gpus all -it tensorflow/tensorflow:latest-gpu bash`

https://www.tensorflow.org/install/docker
Thank you!
