### ISSUE TITLE
TF_Input and TF_Output

### ISSUE THREAD

**Issue by IvanUkhov** [tensorflow/tensorflow#6080]
`TF_Input` and `TF_Output` were introduced in 0.12, and the graph and session APIs were updated accordingly. There are the following five functions right now:

```c
extern void TF_AddInput(TF_OperationDescription* desc, TF_Output input);

extern void TF_AddInputList(TF_OperationDescription* desc,
                            const TF_Output* inputs, int num_inputs);

extern void TF_SessionRun(TF_Session* session,
                          // RunOptions
                          const TF_Buffer* run_options,
                          // Input tensors
                          const TF_Output* inputs,
                          TF_Tensor* const* input_values, int ninputs,
                          // Output tensors
                          const TF_Output* outputs, TF_Tensor** output_values,
                          int noutputs,
                          // Target operations
                          const TF_Operation* const* target_opers, int ntargets,
                          // RunMetadata
                          TF_Buffer* run_metadata,
                          // Output status
                          TF_Status*);

extern void TF_SessionPRunSetup(TF_Session*,
                                // Input names
                                const TF_Output* inputs, int ninputs,
                                // Output names
                                const TF_Output* outputs, int noutputs,
                                // Target operations
                                const TF_Operation* const* target_opers,
                                int ntargets,
                                // Output handle
                                const char** handle,
                                // Output status
                                TF_Status*);

extern void TF_SessionPRun(TF_Session*, const char* handle,
                           // Input tensors
                           const TF_Output* inputs,
                           TF_Tensor* const* input_values, int ninputs,
                           // Output tensors
                           const TF_Output* outputs, TF_Tensor** output_values,
                           int noutputs,
                           // Target operations
                           const TF_Operation* const* target_opers,
                           int ntargets,
                           // Output status
                           TF_Status*);
```

Assuming that there are no typos here, I am trying to understand how one should think about the `input` and `inputs` arguments of these functions as their corresponding types involve `TF_Output`, not `TF_Input`. Take `TF_SessionRun`, for instance. It is a bit confusing that both `inputs` and `outputs` are `TF_Output`. It would be great if somebody could explain the reasoning behind this. Thank you.

Regards,
Ivan

**Comment by asimshankar** [comment]
FYI @josh11b @jhseu 

- `TF_Operation` refers to an operation in the graph, which can have multiple inputs and multiple outputs.
- `TF_Output` identifies the one of possibly many outputs of an operation.
- `TF_Input` identifies the one of possibly many inputs of an operation.

For example, the [QuantizedMatMul](https://github.com/tensorflow/tensorflow/blob/d0aac2b/tensorflow/core/ops/math_ops.cc#L2233) operation has 6 inputs and 3 outputs.  `TF_Input{op, 0}` refers to the input `a`, `TF_Input{op, 2}` refers to the input `min_a` etc. while `TF_Output{op, 0}` refers to output`out`, `TF_Output{op, 1}` refers to the output `min_out` etc.

`TF_SessionRun` takes as feeds the outputs of some operations and returns as fetches the outputs of others. Thus `TF_Output` is used to identify both.

Hope that clarifies things. That said, any suggestions to improve the naming here are appreciated. Perhaps naming the arguments to `TF_SessionRun` etc. as `feeds` and `fetches` instead of `inputs` and `outputs` would help a bit?

**Comment by jhseu** [comment]
Yeah, perhaps we should rename the arguments to those functions. The main confusion (it was initially confusing to me too) is that outputs of nodes are inputs to other nodes, and the type refers to its role as the output and the variable name refers to its usage as input.

We're open to suggestions, but I can't think of anything that improves on the current naming. `feeds` and `fetches` only resolves the issue for the various `Run` functions.

**Comment by nikhilk** [comment]
I was confused myself... and happened to come across this old issue searching about TF_SessionRun.

It seems TF_Output could have been called TF_OperationValue to choose a neutral name for the type, and then input/outputs are terms relative to TF_SessionRun.

Just thought I'd share, even though this has been long closed.

**Comment by gil-cohen** [comment]
If its any incentive to find a solution, I was also confused by this.
