### ISSUE TITLE
Ragged String Input not working with GPU  - > non-DMA-copy attempted of tensor type: string

### ISSUE THREAD

**Issue by citizenkeynes** [tensorflow/tensorflow#60812]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

Yes

### Source

source

### Tensorflow Version

2.12

### Custom Code

No

### OS Platform and Distribution

linux

### Python version

3.9

### Current Behaviour?

consider this trivial tf.keras Model:

```
def some_model():
     x = tf.keras.layers.Input(shape=(None, 1), name="string_input",dtype="string",ragged=True)
     some_function = tf.keras.layers.Lambda(lambda x: x)
     model = tf.keras.models.Model([x],some_function(x))
     return model
```
 
```
with tf.distribute.OneDeviceStrategy("gpu:0").scope():
  m  = some_model()
```
passing a ragged tensor will fail :

```
x = tf.ragged.constant([[["somestring"],["somestring"]],[["somestring"],["somestring"],["somestring"]]])
m.predict(x)
```
with "non-DMA-copy attempted of tensor type: string"

whereas this works just fine

```
x = tf.constant([[["somestring"],["somestring"]],[["somestring"],["somestring"]]])
m.predict(x)
```

I am aware that there are many related issue open / i hope the small self-contained example above is useful

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1cf669jKVUlIjC0JGU42VNyZTWEywAgT0?usp=sharing
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@citizenkeynes,
Basically, RaggedTensorVariant objects should never be copied to GPU, because we can't do anything useful with them there. But Placer isn't currently smart enough to figure that out (it just sees a Variant tensor, and doesn't know what kind of value it contains). 
https://github.com/keras-team/keras/issues/14984
https://github.com/keras-team/keras/issues/16354
Thank you!
