### ISSUE TITLE
Could not interpret loss function "NDCG Lambda Weight V2"

### ISSUE THREAD

**Issue by mega-TWZ** [tensorflow/tensorflow#60834]
A erro happened!
Could not interpret loss function NDCG Lambda Weight V2

-------------------------------------------------------------------
model.compile (

optimizer=optimizer,   

loss=tfr.keras.losses.NDCGLambdaWeightV2(topn=60),
                           
metrics=[tfr.keras.metrics.NDCGMetric(topn=60), tfr.keras.metrics.OPAMetric()]

 )

model.fit(train_dataset, epochs=20)
-------------------------------------------------------------
some error happened in " mode.fit()"
ValueError: Could not interpret loss function identifier: <tensorflow_ranking.python.keras.losses.NDCGLambdaWeightV2 object at 0x7fa0e84ee6e0>

**Comment by mega-TWZ** [comment]
may should  be this one
loss = tfr.keras.losses.ApproxNDCGLoss(lambda_weight=tfr.keras.losses.NDCGLambdaWeightV2(topn=60))

**Comment by sushreebarsa** [comment]
@mega-TWZ Thank you for reporting an issue. Could you provide more details on this issue for which you are requesting the feature. Please share the complete standalone code to replicate the issue.
Thank you!

**Comment by mega-TWZ** [comment]
tfr-->keras-->losses

The intention here is a bit vague, we should better distinguish between 'lambda_weight' and 'losses', rather than placing them in the same directory

截图](https://github.com/tensorflow/tensorflow/assets/77107277/5548c89b-9bb9-4a14-ba93-0964a03730c6)

**Comment by mega-TWZ** [comment]
> @mega-TWZ感谢您报告问题。您能否提供有关您请求该功能的这个问题的更多详细信息。请共享完整的独立代码以重现问题题。 谢谢你！

tfr --> keras --> losses

The intention here is a bit vague, we should better distinguish between 'lambda_weight' and 'losses', rather than placing them in the same directory

a picture of tfr.keras.losses (https://github.com/tensorflow/tensorflow/assets/77107277/bc2b6ba7-5868-49cf-899c-d4bc92a610e0)

**Comment by mega-TWZ** [comment]
> @mega-TWZ Thank you for reporting an issue. Could you provide more details on this issue for which you are requesting the feature. Please share the complete standalone code to replicate the issue. Thank you!

you can see my first comment, I have re-edit it

**Comment by sushreebarsa** [comment]
@mega-TWZ Thank you for your response!
This issue seems to be Keras feature.  Please post this issue on [keras-team/keras repo.](https://github.com/keras-team/keras/issues) as Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras). All issues and PRs related to keras will be addressed in that repo.
To know more see this TF forum discussion ; 
[https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999](https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999)
Thank you!
