### ISSUE TITLE
Mistype (mixed_bloat16) in the keras.mixed_precision.Policy class

### ISSUE THREAD

**Issue by antnsi** [tensorflow/tensorflow#60878]
<details><summary>Click to expand!</summary> 
 
 ### Issue Type

Bug

### Have you reproduced the bug with TF nightly?

No

### Source

source

### Tensorflow Version

master

### Custom Code

No

### Current Behaviour?

There is a [mistype](https://github.com/tensorflow/tensorflow/blob/e0f655d121da781e69052f07c2e5635c4544f2fe/tensorflow/python/keras/mixed_precision/policy.py#L195) in the mixed_precision policy check. It should be `bfloat16`, not `bloat16`
```
    if name in ('mixed_float16', 'mixed_bloat16'):
      device_compatibility_check.log_device_compatibility_check(name)
```

There is no practical issue with it because `log_device_compatibility_check` doesn't support it anyway.

### Standalone code to reproduce the issue

```shell
Not required, it's clear from the code
```

### Relevant log output

_No response_</details>

**Comment by tilakrayal** [comment]
@antnsi,
I have raised the PR in Keras repo for the issue https://github.com/keras-team/keras/pull/18233 and the PR has been assigned for reviewing and once it is merged this issue will move to closed status. Thank you!

**Comment by antnsi** [comment]
Thank you 👍🏻

**Comment by tilakrayal** [comment]
@antnsi,
The PR which was raised for the typo error on the `policy.py` file was merged and the typo was also replaced with **bfloat16**
https://github.com/keras-team/keras/pull/18233
https://github.com/keras-team/keras/blob/master/keras/mixed_precision/policy.py

Could you please take a look and confirm whether the issue was resolved. Thank you!

**Comment by antnsi** [comment]
@tilakrayal I assume changes in the Keras codebase should be somehow reflected in the TF repository? Apparently, it's not automatically updated and the mistype [is there](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/mixed_precision/policy.py#L195). Sorry, I'm not very familiar with TF release processed. Either way, the issue can be close as the Keras code was fixed.

**Comment by tilakrayal** [comment]
@antnsi,
Any new Keras PR or issue should be open in [github.com/keras-team/keras](http://github.com/keras-team/keras), instead of [github.com/tensorflow/tensorflow](http://github.com/tensorflow/tensorflow). Keras development is fully moving to [github.com/keras-team/keras](http://github.com/keras-team/keras).

https://discuss.tensorflow.org/t/keras-project-moved-to-new-repository-in-https-github-com-keras-team-keras/1999

Thank you!

**Comment by sachinprasadhs** [comment]
Hi, The code fix in the Keras repo is the one you should be referring to, the tensorflow/keras code is deprecated and will be deleted in future, once all the dependency is taken care of.

> @tilakrayal Should changes in the Keras codebase be somehow reflected in the TF repository? Apparently, it's not automatically propagated, and the mistype [is in master branch](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/keras/mixed_precision/policy.py#L195). Sorry, I'm not very familiar with the TF release process. Either way, the issue can be closed as the Keras code was fixed.
