### ISSUE TITLE
`Bias` fails to broadcast in the context of `matmul` in tf lite model

### ISSUE THREAD

**Issue by YaoJiayi** [tensorflow/tensorflow#60929]
### 1. System information

- OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Linux Ubuntu 20.04
- TensorFlow installation (pip package or built from source): pip
- TensorFlow library (version, if pip package or github SHA, if built from source): 2.14.0-dev20230602

### 2. Code
This is the minimized code to reproduce the issue:
```python
import tensorflow as tf
import numpy as np

x1 = tf.constant([1., 2.], shape=[1, 2])

class Model(tf.keras.Model):
  def __init__(self):
    super(Model, self).__init__()
    self.w = tf.Variable([[3., 4.], [5., 6.]])
    self.b = tf.Variable([3.])
  @tf.function(input_signature=[tf.TensorSpec(x1.shape, x1.dtype)])
  def call(self, x):
    return tf.matmul(x, self.w) + self.b


m = Model()
print('Keras mode output: ', m(x1).numpy())

converter = tf.lite.TFLiteConverter.from_keras_model(m)
tflite_model = converter.convert()
def _evaluateTFLiteModel(tflite_model, input_data):
    interpreter = tf.lite.Interpreter(model_content=tflite_model)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()
    output_details = interpreter.get_output_details()

    for i in range(len(input_data)):
        interpreter.set_tensor(input_details[i]['index'], input_data[i])

    interpreter.invoke()

    output_data = [interpreter.get_tensor(output_details[i]['index'])
                   for i in range(len(output_details))]
    return output_data

print('Lite mode output: ', _evaluateTFLiteModel(tflite_model,[x1])[0])

```
### 3. Failure after conversion
Output:
```
Keras mode output: [[16. 19.]]
Lite mode output:  RuntimeError: tensorflow/lite/kernels/fully_connected.cc:360 NumElements(bias) != SizeOfDimension(filter, 0) (1 != 2)Node number 0 (FULLY_CONNECTED) failed to prepare.Failed to apply the default TensorFlow Lite delegate indexed at 0.
```
Conversion Failure:
- During conversion, the model fails due to the following check at `tensorflow/lite/kernels/fully_connected.cc:360`
```cpp
if (bias) {
    TF_LITE_ENSURE_EQ(context, NumElements(bias), SizeOfDimension(filter, 0));
  }
```

**Comment by pjpratik** [comment]
I was able reproduce this issue. Please find the [gist](https://colab.research.google.com/gist/pjpratik/98e2a454aafb91de2aa202bd1b7d9b2f/60929.ipynb).

@pkgoogle Could you please check if it is intended behaviour.

Thanks.

**Comment by pkgoogle** [comment]
Hello,

broadcasting is working for some simpler cases: [gist](https://colab.sandbox.google.com/gist/pkgoogle/35a12ccd0f2fca2ae8892b50db4260cd/60929.ipynb)

So this appears to be a legitimate bug.

@miaout17, can you please take a look? Thanks.

**Comment by trevordmeyer** [comment]
Any update on this?

**Comment by LakshmiKalaKadali** [comment]
Hi @YaoJiayi,

The runtime error message you provided is due to a mismatch between the bias and filter dimensions during TensorFlow Lite conversion. I have tried the code with `tf_nightly-2.18.0.dev20240611` and changed the shape of the bias vector to match the output size  ` self.b = tf.Variable([3., 4.]) ` in the code. The keras model is converted to tflite model without any errors. Please refer to the [gist](https://colab.sandbox.google.com/gist/LakshmiKalaKadali/2e006d30884a7c6e31805cfa146d262c/-tflite_60299.ipynb#scrollTo=LoMYXGyEkiTG). 

Thank You

**Comment by pkgoogle** [comment]
Hey all, the current state is the same as before, apologies for the issue.

**Comment by gaikwadrahul8** [comment]
Hi, @YaoJiayi 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/166

Let us know if you have any questions. Thanks.
