### ISSUE TITLE
Error: Input 0 of layer 'batch_normalization' is incompatible with the layer: expected ndim=2, found ndim=4.

### ISSUE THREAD

**Issue by ApprikatAI** [tensorflow/tensorflow#60938]
Estoy intentando entrenar un modelo GAN utilizando Keras en TensorFlow, pero estoy encontrando el siguiente error:

```
Input 0 of layer 'batch_normalization' is incompatible with the layer: expected ndim=2, found ndim=4. Full shape received: (None, None, None, 32768)
```

El error ocurre cuando intento entrenar el modelo con el siguiente código:

```python
history = model.fit(train_generator, epochs=100, callbacks=[checkpoint, tensorboard])
```

¿Alguien podría ayudarme a entender qué está causando este error y cómo puedo solucionarlo? Gracias.

**Comment by LuiseSchwenke** [comment]
Hola, yo no hablo espanhol mas:
it seems your model asks for 2 dimensions but your input tensor has a shape of 4 dimensions.  Maybe you could try to change the Input layers? It could be done by  adding a flattening layer as the first layer like this: 
model.add(keras.layers.Flatten(input_shape=(height,width,depth))) 
Otherwise it can help if you could share the code for your model. You can also use model.summary() to debug, it will show you the current shapes.

**Comment by tilakrayal** [comment]
@ApprikatAI,
Could you please provide the complete standalone code to reproduce the issue which helps us to analyse the issue in an effective way. Thank you!
