### ISSUE TITLE
[TensorBoard] Charts in TensorBoard in Safari don't display correctly

### ISSUE THREAD

**Issue by html5cat** [tensorflow/tensorflow#6108]
macOS Sierra, latest Safari (Version 10.0.1). Works good in Chrome.

Steps to repro:
1. Run https://github.com/openai/universe-starter-agent

2. Observe the following graphs:
<img width="423" alt="screen shot 2016-12-05 at 6 32 12 pm" src="https://cloud.githubusercontent.com/assets/823890/20910888/30ec783a-bb19-11e6-8514-5c1027ca068a.png">

3. Console contains these errors:
<img width="505" alt="screen shot 2016-12-05 at 6 32 58 pm" src="https://cloud.githubusercontent.com/assets/823890/20910904/4936486c-bb19-11e6-8032-417677a78d2e.png">

**Comment by xuancong84** [comment]
Have you tried Firefox or Chrome in Mac? We first need to nail down whether it is the browser's problem or Tensorboard's web-script problem?

MacOS is known to cause problems because Apple developers are typically very ignorant of the conventional standards in HTML/CSS/Javascript/PHP/TCPIP and etc.. Last time, I hosted some web service to do online text translation, it turns out that only for MacOS, if your URL query ends with a unicode character, then MacOS or Safari will append a NULL character, then that extraneous NULL character causes my program to function incorrectly. It is a shame that for such a big company, their engineers have actually made such a silly mistake! -:(

**Comment by html5cat** [comment]
@xuancong84 yeah, as per note above, works good in Chrome.

**Comment by xuancong84** [comment]
@html5cat Then how about Firefox? Firefox is the best explorer in the current state-of-the-art.

**Comment by html5cat** [comment]
Don't have it, sorry. Safari has big enough audience - mobile and default on all Macs.

**Comment by dandelionmane** [comment]
We're currently committed to keeping it working on Chrome and Firefox. Open source contributors are welcome to fix it for safari.

**Comment by wchargin** [comment]
I'm going to close this for now. If you have a fix, please feel free to submit it to our new repository at https://github.com/tensorflow/tensorboard/pulls.
