### ISSUE TITLE
AttributeError: module 'tensorflow_datasets' has no attribute 'load'

### ISSUE THREAD

**Issue by MH0386** [tensorflow/tensorflow#61247]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.10.0

### OS platform and distribution

Windows 11

### Python version

3.10.12

### Current behavior?

I cannot access [UCF101](https://www.tensorflow.org/datasets/catalog/ucf101) and download.

TensorFlow 2.10
Python 3.11.12
tensorflow_datasets 4.9.2

### Standalone code to reproduce the issue

```shell
import tensorflow_datasets
ucf101 = tensorflow_datasets.video.ucf101.Ucf101()
```

### Relevant log output

```shell
AttributeError: module 'tensorflow_datasets' has no attribute 'load'
```

**Comment by tilakrayal** [comment]
@MH0386,
As you mentioned,  the above code that was failing on tensorflow v2.10, but whereas on the latest tensorflow v2.12 it was executed without any issues/error. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/0ad49bffc9c2679a4d32c5a196e92cef/untitled1239.ipynb). Thank you!

**Comment by SankeethYadav** [comment]
1. Check TensorFlow Datasets version: Verify that you are using the latest version of TensorFlow Datasets. You can upgrade TFDS using the following command:
```
pip install --upgrade tensorflow-datasets
```

2. Import correct method: Make sure you are importing the correct method from TensorFlow Datasets. Instead of using `load`, you might need to use other methods like `load_dataset` or `load_from_tfds`. For example:
``
import tensorflow_datasets as tfds

dataset = tfds.load_dataset('dataset_name')
```
By following these steps, you should be able to resolve the issue and successfully load datasets using TensorFlow Datasets.

**Comment by MH0386** [comment]
> 1. Check TensorFlow Datasets version: Verify that you are using the latest version of TensorFlow Datasets. You can upgrade TFDS using the following command:
> 
> ```
> pip install --upgrade tensorflow-datasets
> ```
> 
> 2. Import correct method: Make sure you are importing the correct method from TensorFlow Datasets. Instead of using `load`, you might need to use other methods like `load_dataset` or `load_from_tfds`. For example:
>    ``
>    import tensorflow_datasets as tfds
> 
> dataset = tfds.load_dataset('dataset_name')
> 
> ```
> By following these steps, you should be able to resolve the issue and successfully load datasets using TensorFlow Datasets.
> ```

`AttributeError: module 'tensorflow_datasets' has no attribute 'load_dataset'` with tensorflow 2.13 and tensorflow_datasets 4.9.2

**Comment by SankeethYadav** [comment]
The correct method to load datasets in TensorFlow Datasets is 'load', not 'load_dataset'. Here's an example of how to load a dataset using TensorFlow Datasets:

Try using load() instead of load_dataset
import tensorflow_datasets as tfds
# Load the dataset
dataset, info = tfds.load('dataset_name', split='train', as_supervised=True)

**Comment by MH0386** [comment]
Thanks for all; it works now.

**Comment by Shatakkshi** [comment]
for me its still not working

**Comment by steveepreston** [comment]
Problem still exists:
tensorflow= 4.53.0
tensorflow-datasets= 4.9.9

Code:
```python
import tensorflow_datasets as tfds
tfds.load()
```
Error:
`AttributeError: module 'tensorflow_datasets' has no attribute 'load'`
