### ISSUE TITLE
[Windows] Compute 3.0 

### ISSUE THREAD

**Issue by pragmascript** [tensorflow/tensorflow#6125]
I'm trying to run tensorflow 0.12.0rc0 on Windows 10 with a Compute 3.0 Device (gtx 660 Ti) but I get the following message:
```
I c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\core\common_runtime\gpu\gpu_device.cc:948] Ignoring visible gpu device (device: 0, name: GeForce GTX 660 Ti, pci bus id: 0000:01:00.0) with Cuda c
ompute capability 3.0. The minimum required Cuda capability is 3.5.
```
The installation manual seems to suggest that it should work with 3.0. (And it works just fine on Linux)
```
TensorFlow GPU support requires having a GPU card with NVidia Compute Capability (>= 3.0). Supported cards include but are not limited to:

NVidia Titan
NVidia Titan X
NVidia K20
NVidia K40
```

**Comment by mrry** [comment]
We didn't build the binary package for the 0.12rc0 release with support for Compute Capability 3.0 devices.

Since we merged #6092 and #6099, the next release candidate and [nightly builds](http://ci.tensorflow.org/view/Nightly/job/nightly-win/DEVICE=gpu,OS=windows/) for Windows will have this support.
