### ISSUE TITLE
make `tensorflow.python.tools` importable (freeze_graph, and others)

### ISSUE THREAD

**Issue by silky** [tensorflow/tensorflow#6134]
for mysterious reasons, these functions aren't importable

can we add an `__init__.py` to this directory so that we can import them? thoughts?

**Comment by yaroslavvb** [comment]
Most directories don't have `__init__.py` because they are pulled up to be importable as `tf.<name>`. IE, you can see the list here  https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/__init__.py

But also, things in python/tools directory are meant to be run as stand-alone scripts, not clear that it makes sense to have something like `tf.freeze_graph`

**Comment by silky** [comment]
fair enough re the first point

re the second, i actually don't require this function anymore, so i don't really mind. closing.
