### ISSUE TITLE
hitting 2GB limit when importing large frozen graphs onto multiple gpus

### ISSUE THREAD

**Issue by windancer055** [tensorflow/tensorflow#6144]
When I tried to import a big graph onto multiple gpus (multiple times), the graph def usually goes beyond 2GB. Is there a solution to this in tf?

**Comment by yaroslavvb** [comment]
6 months ago there was no plan on the horizon to get rid of the 2GB limit (it would require deep changes to protobuf library) .... but perhaps you can make your graph smaller? IE, you can use distributed tensorflow locally where each worker holds only part of graph relevant to it. Alternatively, you can use `function.Defun` to factor out large repeating chunks of your computation.

**Comment by windancer055** [comment]
Trying to import a pre-trained vgg model, little of the graph that i can control ...

**Comment by yaroslavvb** [comment]
I just tried importing vgg example from [Toronto site](https://www.cs.toronto.edu/~frossard/post/vgg16/) and GraphDef is 85k, so most of your graphdef is coming from somewhere else. You may get better community support in refactoring your graph creation on stack overflow.

2GB may seem like an arbitrary limit, but it's actually quite large and hitting it usually means user error, like node creation "leak". For instance VGG example is 85k graphdef and it has 266 nodes. So it's an average of 320 bytes per node. So to exceed 2GB with similar kind of network, you'd need 6.2 million nodes. There's a 5usec delay on schedule a GPU op, so you will be spending 31 seconds on op schedule overhead per run call.

Another way to hit the limit is having large graph-inlined constants (`tf.constant`). Storing large data inlined in Graph is inefficient because of locks, so you would be better off moving them into variables anyway.

**Comment by windancer055** [comment]
If the graphdef only contains the nodes, 85k makes more sense to me actually ... I was referring to something like this: https://github.com/pavelgonchar/vgg-face-tensorflow/blob/master/vggface16.tfmodel, which is way larger. I think this might be a frozen model in which all variables are converted into constants (and so it falls into the "graph-inlined constants" problem that you mentioned?

**Comment by yaroslavvb** [comment]
Ah, yes, it seems that [tf_run.py](https://github.com/pavelgonchar/face-transfer-tensorflow/blob/master/tf_run.py) in that example is loading 500MB graphdef, so weights are inlined, maybe using script like [freeze_graph.py](https://github.com/tensorflow/tensorflow/blob/5a5a25ea3ebef623e07fb9a46419a9df377a37a5/tensorflow/python/tools/freeze_graph.py). In such case I'm not aware of any solution -- I think the issue should be called "hitting 2GB limit when dealing with large frozen graphs"

**Comment by michaelisard** [comment]
@petewarden can you comment on whether there's a best practice around this for freeze_graph?

**Comment by petewarden** [comment]
It's a bit of a hail mary, but you could try using the memory-mapping approach to get around the 2GB limit, as described here:
https://petewarden.com/2016/09/27/tensorflow-for-mobile-poets/

I've no idea if that will actually work in this case though.

**Comment by tfboyd** [comment]
Automatically closing due to lack of recent activity. We hope that you were able to resolve it on your own. However, since this is a support issue rather than a bug or feature request, you will probably get more information by posting it on StackOverflow.
