### ISSUE TITLE
Fast Layer Normalization GPU kernel

### ISSUE THREAD

**Issue by MycChiu** [tensorflow/tensorflow#6146]
Hi, I wrote a [custom CUDA op for layer normalization](https://github.com/MycChiu/fast-LayerNorm-TF), which is about 5-10x faster than the current `tf.contrib.layers.layer_norm`.

After I posted the link on reddit, some people suggested that I should try to merge this kernel into the trunk, but I have never done this before, so I need some guidance on how this custom kernel could be integrated into TensorFlow's current code.

With my current understanding on how TensorFlow's code is organized, here are some of the problems I think should be solved before the custom op can be integrated into the trunk:
1. It doesn't have CPU kernels.
2. Since the kernel uses shuffle instructions, it only supports cards newer than Kepler.
3. Current implementation has a restriction on the size of last dimension (cannot be larger than 5102)

Without solving these problems, the fastest way to merge this op into the trunk is probably by putting it under the `tf.contrib` folder as it is right now. I will fill out the CLA and make a pull request if you guys think this custom kernel is ready to be merged into the `tf.contrib` folder.

**Comment by michaelisard** [comment]
@martinwicke can you comment?

**Comment by martinwicke** [comment]
In principle, there's no problem in registering a kernel only for GPU. Kepler (CC 3.0, I think) is the minimum for TF anyway, so no problem there either. We may even be able to dispatch to the kernel from contrib.layers.layer_norm, but that may be a bit of a hack. More probably, it'll be a separate op that you can call instead of the layer.

I think you should try merging this into contrib, please send a PR!

**Comment by martinwicke** [comment]
I changed the tags, please reference this issue from your PR.

**Comment by MycChiu** [comment]
Thank you @martinwicke! As requested, #6205 .
