### ISSUE TITLE
Segmentation fault when running tensorflow.python.framework.importer._GatherReturnElements

### ISSUE THREAD

**Issue by dmc1778** [tensorflow/tensorflow#61545]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.11.0

### Custom code

Yes

### OS platform and distribution

22.04

### Python version

3.9

### CUDA/cuDNN version

nvidia-cudnn-cu11==8.6.0.163, cudatoolkit=11.8.0

### Current behavior?

Due to feeding None value

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import os
import numpy as np
from tensorflow.python.framework import importer
try:
  arg_0_0 = "A"
  arg_0 = [arg_0_0,]
  arg_1 = None
  arg_2 = None
  out = importer._GatherReturnElements(arg_0,arg_1,arg_2,)
except Exception as e:
  print("Error:"+str(e))
```
```


### Relevant log output

```shell
023-08-13 02:10:14.149106: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Segmentation fault

```
```

**Comment by sushreebarsa** [comment]
@dmc1778 I was able to reproduce the issue on colab using TF v2.11, 2.13, tf-nightly. Please find the attached [gist](https://colab.research.google.com/gist/sushreebarsa/e6b3d4ed44288db60f61f0572f616591/61545.ipynb). 
Since Segmentation faults can be considered as potential security vulnerabilities please read [SECURITY.md](https://github.com/tensorflow/tensorflow/blob/master/SECURITY.md) and report them through proper channel as mentioned in SECURITY.md.
Thank you!
