### ISSUE TITLE
Error in PredictCost() for the op: op: "CropAndResize" attr

### ISSUE THREAD

**Issue by kvnsng** [tensorflow/tensorflow#61659]
### Issue type

Others

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf 2.13.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.10

### Current behavior?

We have a model that used to run on python 3.7 + tensorflow 2.4.1. When upgrading to tensorflow 2.13.0, we're seeing this error message, which seems to correlate with the degradation of our model performance. Any idea what might be leading to this error and what could be changed? 

It does seem like when I remove `tf.function` decorator, this error message goes away. So, I'm assuming it has something to do with tracing, but not entirely sure why it's erroring out in tf 2.13 and not in 2.4.1...

```
Error in PredictCost() for the op: op: "CropAndResize" attr { key: "T" value { type: DT_FLOAT } } attr { key: "extrapolation_value" value { f: 0 } } attr { key: "method" value { s: "bilinear" } } inputs { dtype: DT_FLOAT shape { dim { size: -569 } dim { size: 128 } dim { size: 224 } dim { size: 2 } } } inputs { dtype: DT_FLOAT shape { dim { size: -16 } dim { size: 4 } } } inputs { dtype: DT_INT32 shape { dim { size: -16 } } } inputs { dtype: DT_INT32 shape { dim { size: 2 } } value { dtype: DT_INT32 tensor_shape { dim { size: 2 } } tensor_content: "\030\000\000\000\020\000\000\000" } } device { type: "GPU" vendor: "NVIDIA" model: "Tesla V100-SXM2-16GB" frequency: 1530 num_cores: 80 environment { key: "architecture" value: "7.0" } environment { key: "cuda" value: "11080" } environment { key: "cudnn" value: "8600" } num_registers: 65536 l1_cache_size: 24576 l2_cache_size: 6291456 shared_memory_size_per_multiprocessor: 98304 memory_size: 11614814208 bandwidth: 898048000 } outputs { dtype: DT_FLOAT shape { dim { size: -16 } dim { size: 24 } dim { size: 16 } dim { size: 2 } } }
```

### Standalone code to reproduce the issue

```shell
I don't have a standalone code to reproduce the issue, but would just like some feedback on what might be causing the above issue...
```

**Comment by sushreebarsa** [comment]
@kvnsng Could you please confirm the python version you are using?
Please make sure to use the [compatible](https://www.tensorflow.org/install/source#ubuntu) versions when you are upgrading TF version. 
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by kvnsng** [comment]
@sushreebarsa `tensorflow==2.4.1` was used with `python 3.8` and `tensorflow==2.13.0` was with `python 3.10`. I used a docker image from tensorflow dockerhub, so I imagine it all had the correct TF versions.

I'll try to prep a small code snippet that could reproduce the issue. Thanks!

**Comment by sushreebarsa** [comment]
@kvnsng Is there any update on this issue?
Thank you!

**Comment by kvnsng** [comment]
@sushreebarsa apologies for the delay but work has been crazy. I'll work on getting a code snippet together by the end of this week. Thanks!

**Comment by sachinprasadhs** [comment]
Hi @kvnsng ,

The version difference is huge from 2.4 to 2.14, many things have changed since then, it is difficult to point to the specific change without any reproducible code.

If you are not able to provide the reproducible code, I would suggest you to go through our release notes https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md which could help you to identify the changes made.

If you have managed to identify the source file of the module you are using, you can check the commit history to identify the changes made.
