### ISSUE TITLE
Android NDK Prefabs for Tensorflow Lite

### ISSUE THREAD

**Issue by mrousavy** [tensorflow/tensorflow#61667]
Hey all! I'm trying to use Tensorflow Lite in an Android NDK/C++ environment.

My `build.gradle` looks something like this:

```groovy
...
android {
  ...
  buildFeatures {
    prefab true
  }
}

dependencies {
  ...
  implementation "org.tensorflow:tensorflow-lite:2.13.0"
}
```

And in my `CMakeLists.txt` I try to find `tensorflow-lite` as a prefab:

```cmake
...
find_package(tensorflow-lite REQUIRED CONFIG)
...

target_link_libraries(
  ${PACKAGE_NAME}
  ...
  tensorflow-lite::tensorflow-lite
)
```

However, CMake is not able to find the package:

```
CMake Error at CMakeLists.txt:10 (find_package):
  Could not find a package configuration file provided by "tensorflow-lite"
  with any of the following names:

    tensorflow-liteConfig.cmake
    tensorflow-lite-config.cmake

  Add the installation prefix of "tensorflow-lite" to CMAKE_PREFIX_PATH or
  set "tensorflow-lite_DIR" to a directory containing one of the above files.
  If "tensorflow-lite" provides a separate development package or SDK, be
  sure it has been installed.
```

Does TensorFlow Lite not provide a prefab publish? This would make it a lot easier to integrate in such environments. Now I have to manually extract the .aar/zip and incldue the headers.

**Comment by pjpratik** [comment]
Hi @mrousavy 

As per the [documentation](https://www.tensorflow.org/lite/android/development#tflite_c_api_2), 

Currently, there is no straightforward way to extract all header files needed, we need include all header files manually.

@pkgoogle Could you please look at this request?

Thanks.

**Comment by pkgoogle** [comment]
Hi @mrousavy, I can't find any documentation that we have a prefab available, should we take this as a feature request?

**Comment by pkgoogle** [comment]
Hi @arfaian, can you please take a look? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @mrousavy 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/154

Let us know if you have any questions. Thanks.
