### ISSUE TITLE
Cast from int32 to float32 changes the value.

### ISSUE THREAD

**Issue by samriddha1904** [tensorflow/tensorflow#61876]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.13.0

### Custom code

Yes

### Current behavior?

 Here what I see is that the bug actually happens b/c as we are doing the conversion from int32 to float32 the value changes, as there is a rounding error that occurs when casting an integer to a floating-point type as float32 is not the high precision floating point type like float64, and the bug will also remain the same if we change them even to int64 from int32.

### Standalone code to reproduce the issue

```shell
> The code is below 
>> tf.cast(tf.constant(52479845, tf.int64), tf.float32)
<tf.Tensor: shape=(), dtype=float32, numpy=52479844.0>
>> tf.cast(tf.constant(52479843, tf.int64), tf.float32)
<tf.Tensor: shape=(), dtype=float32, numpy=52479843.0>
```

### Relevant log output

```shell
### Relevant log output

_No response_
```

**Comment by HarishGuragol** [comment]
Hi @SuryanarayanaY can I contribute to this issue

**Comment by sachinprasadhs** [comment]
This is the standard limitation of floating point precision.

In IEEE 754 single precision (float), there are 23 bits allocated for the mantissa, allowing for approximately 7 decimal digits of precision.

Due to this finite precision, not all real numbers can be represented exactly in the floating-point format. This limitation leads to rounding errors or inaccuracies in calculations, especially when dealing with numbers that require more precision than what can be represented within the given number of bits.

For more detail, visit https://en.wikipedia.org/wiki/IEEE_754
