### ISSUE TITLE
implementation 'org.tensorflow:tensorflow-lite-support:0.1.0'

### ISSUE THREAD

**Issue by B-JackMao** [tensorflow/tensorflow#61918]
implementation 'org.tensorflow:tensorflow-lite-support:0.1.0'
Why do I run this instruction to generate two dependent libraries, TensorFlow Lite and TensorFlow Lite Support?

How can I generate only tensorflow site support as a dependency library?

**Comment by pkgoogle** [comment]
Hi @B-JackMao, can you please fill out the issues template: https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=comp%3Alite-in-play-services&projects=&template=tflite-in-play-services.md This will give us more context so that we may help you faster (You can remove the google-play specific information).
