### ISSUE TITLE
tensorflow android camera demo: replacing inception5h with incetoption-resnetV2

### ISSUE THREAD

**Issue by codeloverr** [tensorflow/tensorflow#6192]
I am trying to replace the provided inception5h with latest inception-resnetV2. I have downloaded the inception-resnet-V2 by entring 
 `wget http://download.tensorflow.org/models/inception_resnet_v2_2016_08_30.tar.gz -O /tmp/inception_resnet_v2_2016_08_30.tar.gz`

And unzip it in 

`unzip /tmp/inception_resnet_v2_2016_08_30.tar.gz -d tensorflow/examples/android/assets/`

After unzip I only found **inception_resnet_v2_2016_08_30.ckpt** but for Android demo requires a `MODEL_FILE` with .pb extension and a `LABEL_FILE`. How I can get these files for inception-resnetV2.

**Comment by andrewharp** [comment]
I can't speak to that specific model, but in the general case you have to have the actual GraphDef which defines the model topology (this may be created by a python script somewhere?). Then you can run [freeze_graph.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph.py) on it to combine it with the checkpoint file, which embeds all the trained weights inside it as constant ops so that it can easily be loaded on mobile.

Additionally, you can then run [optimize_for_inference](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/optimize_for_inference.py) to strip out unused ops that may not be supported on Android.

**Comment by codeloverr** [comment]
@andrewharp  Can you provide some python script that would do that? I am learning tensorflow, still at beginner level.

**Comment by andrewharp** [comment]
The linked scripts are both Python scripts that contain example invocations in the comments;  you just have to provide a GraphDef in addition to the checkpoint you already have. I'm not sure where the corresponding GraphDef for your checkpoint is found, perhaps wherever you found the download link has associated code for generating it?

**Comment by andrewharp** [comment]
Closing; please reopen if you have specific issues with the scripts.
