### ISSUE TITLE
About int16

### ISSUE THREAD

**Issue by panhu** [tensorflow/tensorflow#61985]
### 1. System information

- Linux Ubuntu 16.04
- TensorFlow lite
### 2. Issue

I would like to inquire if my input and output data can only be int16. Can I write "converter. reference_input_type=tf. int16" when converting tflite？ or is there any other good method recommended?

Thanks!

**Comment by sushreebarsa** [comment]
@panhu For converting your Tf lite model please follow the instruction [here](https://www.tensorflow.org/lite/models/convert) and check [this](https://www.tensorflow.org/lite/performance/post_training_integer_quant_16x8) document for tflite Post-training integer quantization with int16 activations.
In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by panhu** [comment]
Hi:
I have another question that I would like to ask if I can only install version 2.5.0 of "tflite runtime" on Windows? as I am using pip to install other versions of "tflite runtime" on Windows, but I am unable to find them.

Thanks!

**Comment by sushreebarsa** [comment]
@panhu 
You can use the latest tflite runtime version. The tflite-runtime Python wheels are pre-built and provided for these platforms as follows;

*Linux armv7l (e.g. Raspberry Pi 2, 3, 4 and Zero 2 running Raspberry Pi OS 32-bit)
*Linux aarch64 (e.g. Raspberry Pi 3, 4 running Debian ARM64)
*Linux x86_64
If you want to run TensorFlow Lite models on other platforms, you should either use the [full TensorFlow package ](https://www.tensorflow.org/install/), or [build the tflite-runtime package from source ](https://www.tensorflow.org/lite/guide/build_cmake_pip). Thank you!
