### ISSUE TITLE
AuditWheel Failures on Build for TensorFlow 2.14

### ISSUE THREAD

**Issue by ohadkatz** [tensorflow/tensorflow#62103]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

TF2.14

### Custom code

No

### OS platform and distribution

Ubuntu 20.04

### Python version

Python3.10

### CUDA/cuDNN version

11.8

### Current behavior?

When trying to build TensorFlow 2.14 on the ci/official `wheel.sh` script, we are seeing manylinux failures during the auditwheel check stating that the "presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain."

Are there any recommendations to fix this issue for TF2.14 builds?

### Standalone code to reproduce the issue

```shell
Env Vars local:
TF_PYTHON_VERSION=3.10
TFCI_INDEX_HTML_ENABLE=0
TFCI_NIGHTLY_UPDATE_VERSION_ENABLE=0
TFCI_DOCKER_ENABLE=1
PWD=/home/ubuntu/TF/tensorflow/build/logs
LANG=C.UTF-8
TFCI_CAPTURE_LOGS_ENABLE=1
TFCI_UPLOAD_LIB_ENABLE=0
TFCI_DOCKER_IMAGE=tensorflow/build:2.14-python3.10
TFCI_NVIDIA_SMI_ENABLE=0
TFCI_GIT_DIR=<TF_HOME>
TFCI_DOCKER_PULL_ENABLE=0
TFCI_COPYBARA_ENABLE=0

Run:
./ci/official/wheel.sh
```

### Relevant log output

```shell
/root/.cache/bazel/_bazel_root/80314ce22acbaa076a5371cd57252cbd/external/python_x86_64-unknown-linux-gnu/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Thu Oct 12 22:03:56 UTC 2023 : === Output wheel file is in: /home/ubuntu/TF/tensorflow/build
+ tfrun ./ci/official/utilities/rename_and_verify_wheels.sh build
+ docker exec tf ./ci/official/utilities/rename_and_verify_wheels.sh build
+ DIR=build
+ for wheel in $DIR/*.whl
+ echo 'Checking and renaming build/tensorflow-2.14.0-cp310-cp310-linux_x86_64.whl...'
Checking and renaming build/tensorflow-2.14.0-cp310-cp310-linux_x86_64.whl...
+ python3 -m auditwheel repair --plat manylinux2014_x86_64 build/tensorflow-2.14.0-cp310-cp310-linux_x86_64.whl --wheel-dir build
+ tee check.txt
INFO:auditwheel.main_repair:Repairing tensorflow-2.14.0-cp310-cp310-linux_x86_64.whl
usage: __main__.py [-h] [-V] [-v] command ...
__main__.py: error: cannot repair "build/tensorflow-2.14.0-cp310-cp310-linux_x86_64.whl" to "manylinux2014_x86_64" ABI because of the presence of too-recent versioned symbols. You'll need to compile the wheel on an older toolchain.

real    0m26.251s
user    0m23.852s
sys     0m2.388s
```

**Comment by angerson** [comment]
Thanks for checking out the newer scripts. Sorry that it's not super clear, but they're still under development. They were not the scripts used to build TF 2.14 -- we're aiming to use them for TF 2.16. So they're not guaranteed to work yet.

I'm guessing this is not working because your build is not using the correct bazelrc settings to select the toolchain present in the container, since the correct toolchain settings have been moving around while these scripts are under development. I think for 2.14 you'd need to make sure that the build is using one of the bazelrcs from the container, e.g. "--bazelrc=/tf/cpu.bazelrc", I think.

**Comment by ohadkatz** [comment]
HI @angerson I attempted to update the build to using the bazelrc's contained within the container, and am still seeing the same auditwheel failure on TF2.14 sigbuild with image being tensorflow/build:2.14-python3.10 .

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
