### ISSUE TITLE
Deterministic behavior gets extremely slow with CNNs in TF > 2.13

### ISSUE THREAD

**Issue by erickrf** [tensorflow/tensorflow#62100]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### GPU model and memory

Tesla T4 15 GB

### Current behavior?

When setting up deterministic behavior with `tf.config.experimental.enable_op_determinism()`, a small model with convolution layers gets prohibitively slow.

The same code runs in about 80 seconds without the flag, but over 10 minutes with it. This behavior was not observed in TF 2.8.

The model code is as follows:

```
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Input, Dense, Embedding, GlobalMaxPooling1D, Conv1D, BatchNormalization, Activation, concatenate, Dropout
from tensorflow.keras.optimizers import Adam
from tensorflow.keras.initializers import Constant
import numpy as np

vocab_size = 200_000
vocab_dim = 100
length1 = 50
length2 = 100
length = 100
num_samples = 100_000
conv_dim = 128
window_sizes = [2, 3, 4, 5]
num_classes = 2000

input_features = [Input(shape=(length1,), dtype="int32"), Input(shape=(length2,), dtype="int32")]
hidden_tensors = []
    
for feature in input_features:
    embeddings = Embedding(vocab_size, vocab_dim)(feature)

    for window_size in window_sizes:
        convoluted = Conv1D(conv_dim, window_size)(embeddings)
        normed = BatchNormalization()(convoluted)
        activated = Activation("relu")(normed)
        pooled = GlobalMaxPooling1D()(activated)
        hidden_tensors.append(pooled)
    
hidden = Dropout(0.5)(concatenate(hidden_tensors))
outputs = Dense(num_classes, activation='softmax')(hidden)

model = Model(inputs=input_features, outputs=outputs)
model.compile(loss="sparse_categorical_crossentropy", optimizer=Adam(learning_rate=0.001), metrics=['accuracy'])

features1 = np.random.randint(0, vocab_size, size=(num_samples, length1), dtype=np.int32)
features2 = np.random.randint(0, vocab_size, size=(num_samples, length2), dtype=np.int32)
labels = np.random.randint(0, num_classes, size=num_samples)

model.fit([features1, features2], labels, epochs=1, batch_size=256)
```

And I triggered determinism with:
```
tf.keras.utils.set_random_seed(1234)
tf.config.experimental.enable_op_determinism()
```

### Standalone code to reproduce the issue

[Colab notebook](https://colab.research.google.com/drive/16B1zAX24EYLkty6j3FmbecBx-t9jNoFe?usp=sharing)

**Comment by SuryanarayanaY** [comment]
Hi @erickrf ,

I have replicated the reported problem and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/f627915b4bb167190faa73aa179736cd/62100.ipynb) here. With Tf2.9v I can see execution time around 63 sec whereas with TF2.14v estimated time Going to 5 Hours. With tf-nightly its taken 724 seconds.

Without `tf.config.experimental.enable_op_determinism()` it seems fine with around 70 sec in all versions.

This needs to be checked. Thanks for reporting.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
