### ISSUE TITLE
Problemas com instalacao do tensorflow no docker

### ISSUE THREAD

**Issue by yurymiguel** [tensorflow/tensorflow#62101]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

Atual

### Custom code

Yes

### OS platform and distribution

Torizon-Linux arm64

### Mobile device

Linux arm64

### Python version

3.10.9

### Current behavior?

Estou tentando construir um docker, mas somente a lib do tensorflow não funciona. Coisa que não acontecia antes, há pouco tempo atrás, eu não tinha nenhum problema. Já tentei diversas coisas como especificar versão do tensorflow, e do tensorflow-cpu-aws no requirements, atualizo o setuptools, construo a wheel, construo o build.

### Standalone code to reproduce the issue

```shell
Antes usando mesma imagem eu não tinha nenhum problema com instalação das libs, agora eu tenho problema somente com a lib do tensorflow.
```

### Relevant log output

```shell
FROM python:3.10

RUN apt-get update && apt-get install -y libgl1-mesa-glx

RUN pip install --upgrade pip

RUN pip install --upgrade setuptools

RUN pip install -r requirements.txt



Meu arquivo requirements.txt:
pytorch
keras
pytesseract
joblib
facenet-pytorch
flask-cors
flask
pandas
plotly
opencv-python
folium
socketio
regex
paramiko
joblib
numpy
psycopg2
tensorflow



ERRO:
ERROR: Could not find a version that satisfies the requirement tensorflow-cpu-aws==2.11.1; platform_system == "Linux" and (platform_machine == "arm64" or platform_machine == "aarch64") (from tensorflow) (from versions: 2.9.1, 2.10.0rc0, 2.10.0rc2, 2.10.0rc3, 2.10.0, 2.10.1, 2.11.0rc0, 2.11.0rc1, 2.11.0rc2, 2.11.0, 2.12.0rc1, 2.12.0, 2.12.1, 2.13.0rc0, 2.13.0, 2.13.1, 2.14.0rc0, 2.14.0rc1, 2.14.0)
ERROR: No matching distribution found for tensorflow-cpu-aws==2.11.1; platform_system == "Linux" and (platform_machine == "arm64" or platform_machine == "aarch64")
```

**Comment by tilakrayal** [comment]
@yurymiguel,
@rhuddleston,
The package tensorflow-cpu-aws is meant for **Arm/AArch64** processors and it can't be downloaded in `X86_64` architectures through pip. 

Pip will try to resolve the wheels suitable for the particular host platform and if it is not found then it raises the error like no matching distribution found.

The pre-built pip wheels for X86_64 built and maintained by tensorflow itself which you can install through pip install tensorflow-cpu and this can be installed on x86_64 machines only.

Could you please refer the documentation [source](https://www.tensorflow.org/install/pip#linux:~:text=Nightly-,Note%3A%20Starting%20with%20TensorFlow%202.10%2C%20Linux%20CPU%2Dbuilds%20for%20Aarch64,package.%20See%20this%20blog%20post%20for%20more%20information%20about%20this%20collaboration.,-conda%20install%20%2D) for more details.

This does not look like a problem that is specific to TensorFlow. I think your problem is all about creating a docker container for a foreign architecture from your x86 machine. In order to do that you need to add qemu to the mix so that there is an environment that allows the docker container to execute.
See https://www.docker.com/blog/multi-platform-docker-builds/

Thank you!
