### ISSUE TITLE
Internal Error for truncatediv when denominator is an integer zero.

### ISSUE THREAD

**Issue by drewshark** [tensorflow/tensorflow#62114]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.14.0

### Custom code

Yes

### Current behavior?

tf.truncatediv raises internal error when denominator is an integer zero. If the denominator is a float zero, this function works normally.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
x = tf.constant(33, dtype="int32")
y = tf.constant(0, dtype="int32")
print(x, y)
print(tf.truncatediv(x,y))
```

**Comment by SWITCHin2** [comment]
Can I try my hands on it?

**Comment by sushreebarsa** [comment]
@drewshark Thank you for raising this issue!
Truncation designates that negative numbers will round fractional quantities toward zero. It performs integer division. When the denominator is zero, there is no integer quotient that can be defined, so the function raises an error.
Could you use a floating-point denominator instead of an integer denominator. Please let us know if it helps?
Thank you!
