### ISSUE TITLE
Different behaviors of raw_ops.Sigmoid can be observed when jitcompiled=true.

### ISSUE THREAD

**Issue by zoux1a** [tensorflow/tensorflow#62212]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.3 LTS (x86_64)

### CUDA/cuDNN version

11.8

### GPU model and memory

GPU 0: NVIDIA GeForce RTX 2070 GPU 1: NVIDIA GeForce RTX 2070 GPU 2: NVIDIA GeForce RTX 2070 GPU 3: NVIDIA GeForce RTX 2070

### Current behavior?

In TensorFlow, enabling jitcompiled results in inconsistent behavior of raw_ops.Sigmoid.

### Standalone code to reproduce the issue

```shell
I can reproduce this issue on colab: https://colab.research.google.com/drive/16gZRKnhRtqUBJiUQEobXCrjt3B4-w8hS?usp=sharing
```

### Relevant log output

```shell
InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''
b'x and y not equal to tolerance rtol = tf.Tensor(0.001, shape=(), dtype=float32), atol = tf.Tensor(0.001, shape=(), dtype=float32)'
b'x (shape=(10, 9) dtype=complex64) = '
(nan+nanj), (1+0j), (nan+nanj), ...
b'y (shape=(10, 9) dtype=complex64) = '
(1+0j), (-0-0j), (1+0j), ...
```

**Comment by Venkat6871** [comment]
Hi **@zoux1a** ,

I have replicated the reported behaviour with colab using TF v2.14, 2.15, and TF-nightly. Please find the [gist](https://colab.research.google.com/gist/Venkat6871/b35628ec856171b2cede047c4df29001/62212_gpu_2-14-2-15-nightly.ipynb) here for reference.

Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @zoux1a ,

The assertion is failing because here the inputs are complex dtypes and Sigmoid Op is converting this to `Nans` or `0` & `1` s which is inconsistent.

If we convert input from complex to float32 then the results are same. I have taken a simple input and attached my observations in the [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/75d132e91953834bc9157daefaa1cbdc/62212_gpu_r2.ipynb#scrollTo=7scnMay_kunM).

IMO, there is some inconsistency in Sigmoid Op with complex dtypes causing this behaviour. Escalating the issue to SME for their comments.

**Comment by cantonios** [comment]
Fix is now in Eigen: https://gitlab.com/libeigen/eigen/-/merge_requests/1431

Will take a few weeks to propagate to TF.

**Comment by tilakrayal** [comment]
@zoux1a ,
The above PR which was raised in the eigen repo was merged and also tried to execute the code on tf-nightly and it was executed without any issue/error/fail. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/8e1306cba13a29a823f72c61c3e7a50c/untitled1954.ipynb). Thank you!
