### ISSUE TITLE
TFLITE does not compile with CMake in Visual Studio 2019

### ISSUE THREAD

**Issue by MVoloshin** [tensorflow/tensorflow#62228]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf-master

### Custom code

Yes

### OS platform and distribution

Windows 7 SP1 x64

### Python version

3.11

### GPU model and memory

NVIDIA GeForce 1660 SUPER 6 GB

### Current behavior?

Cannot find #include <sys/mman.h> in "tensorflow/lite/kernels/internal/optimized/fully_connected_4bit.h"
Expected successful build.

P.S. There's TFLITE_MMAP_DISABLED condition in this file, but I didn't find it in CMakeLists.txt or anywhere else (except Bazel config files that are not used while building with CMake).

### Standalone code to reproduce the issue

```shell
1. Open latest VS 2019 on 64-bit Windows 7 (maybe newer versions too).
2. Download tensorflow-master as zip, unpack.
3. Open tensoflow/lite as CMake project.
4. Right click on root CMakeLists.txt and choose "Build".
```

### Relevant log output

```shell
Cannot find #include <sys/mman.h> in "tensorflow/lite/kernels/internal/optimized/fully_connected_4bit.h"
```

**Comment by jevansio** [comment]
Just hit same issue.

You can try injecting the pre-processor defn straight through by putting it in the cxx flags default value...

cmake -E env CXXFLAGS="/DTFLITE_MMAP_DISABLED" cmake ..

**Comment by MVoloshin** [comment]
> Just hit same issue.
> 
> You can try injecting the pre-processor defn straight through by putting it in the cxx flags default value...
> 
> cmake -E env CXXFLAGS="/DTFLITE_MMAP_DISABLED" cmake ..

Hello! Thank you very much, but I hope this case will be handled automatically once the bug is fixed)

**Comment by gaikwadrahul8** [comment]
Hi, @MVoloshin 

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/101

Let us know if you have any questions. Thanks.
