### ISSUE TITLE
Different Behavior of tf.raw_ops.DivNoNan with jit_compile=True 

### ISSUE THREAD

**Issue by zoux1a** [tensorflow/tensorflow#62255]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.14.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 22.04.3 LTS (x86_64)

### CUDA/cuDNN version

11.8

### GPU model and memory

GPU 0: NVIDIA GeForce RTX 2070 GPU 1: NVIDIA GeForce RTX 2070 GPU 2: NVIDIA GeForce RTX 2070 GPU 3: NVIDIA GeForce RTX 2070

### Current behavior?

When the **tf.raw_ops.DivNoNan** operation is invoked within a tf.function with JIT compilation enabled (**jit_compile=True**), it produces different results compared to the same operation called without JIT compilation. This inconsistency is observed when the code is executed on a GPU device.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import traceback

class Network(tf.Module):
    def __init__(self):
        super().__init__()

    @tf.function(jit_compile=True)
    def __call__(self, x):
      tensor = tf.random.normal([6, 10, 1, 1], dtype=tf.bfloat16)
      x = tf.raw_ops.DivNoNan(x=x, y=tensor)        
      return x

m = Network()
inp = {
    "x": tf.random.normal([1, 1], dtype=tf.bfloat16),
}

with tf.device('/GPU:0'):
    tf.config.run_functions_eagerly(True)
    no_op_res = m(**inp)
    tf.config.run_functions_eagerly(False)
    with tf.device('/GPU:0'):
        op_res = m(**inp)

    tf.debugging.assert_near(tf.cast(no_op_res, tf.float64), tf.cast(op_res, tf.float64), atol=0.001, rtol=0.001)
```

### Relevant log output

```shell
File "/home/guihuan/LLM/results/tf-2/2023-10-22-20-21/test.py", line 26, in <module>
    tf.debugging.assert_near(tf.cast(no_op_res, tf.float64), tf.cast(op_res, tf.float64), atol=0.001, rtol=0.001)
  File "/home/guihuan/.conda/envs/night/lib/python3.9/site-packages/tensorflow/python/util/traceback_utils.py", line 153, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/guihuan/.conda/envs/night/lib/python3.9/site-packages/tensorflow/python/ops/control_flow_assert.py", line 102, in Assert
    raise errors.InvalidArgumentError(
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected 'tf.Tensor(False, shape=(), dtype=bool)' to be true. Summarized data: b''
b'x and y not equal to tolerance rtol = tf.Tensor(0.001, shape=(), dtype=float64), atol = tf.Tensor(0.001, shape=(), dtype=float64)'
b'x (shape=(6, 10, 1, 1) dtype=float64) = '
-80.0, 1.078125, 1.765625, ...
b'y (shape=(6, 10, 1, 1) dtype=float64) = '
-2.171875, 1.5703125, 3.578125, ...
```

**Comment by sushreebarsa** [comment]
Hi, @zoux1a ! I was able to replicate the issue reported here. Please find the attached gist [here](https://colab.research.google.com/gist/sushreebarsa/9ccdaaefb684b9520a371e68a5efad42/62255.ipynb). Thank you!

**Comment by SuryanarayanaY** [comment]
Hi @zoux1a ,

I noticed an issue here.

Inside the call function you are generating the value for images, which in each calls generates different random values because XLA currently ignores TF seeds to random operations which makes the output different for obvious reason. Please refer [known](https://www.tensorflow.org/xla/known_issues#random_number_generation_ignores_tf_seed) issues from XLA section.

I have done the changes to shift images to outside the call function to ensure same inputs. I ran 10 experiments with different inputs of `x` & `tensor` and printed the difference or `reduce_sum` results of `no_op_res` and `op_res` which outputs `0` for each case.

Please refer attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/6f935bce59bde12810afe2ed1127c9c1/62255_final.ipynb) for the experiments.
