### ISSUE TITLE
Build Microfrontend -Wsigned-compare and -Wdouble-promotion

### ISSUE THREAD

**Issue by ericheim** [tensorflow/tensorflow#62290]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

master

### Custom code

No

### GCC/compiler version

Apple Clang 14 and GNU Arm Embedded Toolchain 10.3-2021.07

### Current behavior?

Building the tensorflow/lite/microfrontend sources with -Werror -Wsigned-compare -Wdouble-promotion results in compiler errors when warnings as errors are enabled.

### Standalone code to reproduce the issue

```shell
Compile tensorflow with the flags: -Werror -Wsigned-compare -Wdouble-promotion
```

**Comment by ericheim** [comment]
Attached a PR #62291

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
