### ISSUE TITLE
Status of ragged tensors in tf nightly 

### ISSUE THREAD

**Issue by 0x0L** [tensorflow/tensorflow#62332]
Hello,

It seems keras 3 (used in tf nightly) has dropped support for ragged tensors.

What are the plans for the future of ragged tensors in keras tf?

Thanks

**Comment by mihaimaruseac** [comment]
Meanwhile, you can still use `tf.keras` or directly the ragged tensors API from within TF though

**Comment by SuryanarayanaY** [comment]
@0x0L ,

If you are particularly looking to train a model with ragged input by using tf.keras, AFAIK, you can do it unitil TF2.14 version(Not sure about 2.15V yet). From Keras3(current tf-nightly keras package) onwards the Inputlayer(Input) don't accept `ragged` argument. I tested with a demo and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/4a1cc09b7a92d99679017f5c74ffa3e9/62332.ipynb#scrollTo=-iX3dRvBjgW8) here.

**Comment by 0x0L** [comment]
@mihaimaruseac Actually no, it does not work in tf-nightly: `tf.keras.Input` does not support the `ragged` kwarg anymore as noted by @SuryanarayanaY  (tf keras 2.15rc still has ragged support)

As mentioned in https://github.com/keras-team/keras/issues/18467 they (keras) "may add it back later"... which does not sound too encouraging

**Comment by mihaimaruseac** [comment]
Try https://pypi.org/project/tf-keras-nightly/ instead of `keras-nightly`

**Comment by 0x0L** [comment]
@mihaimaruseac  Thank you so much !!

So I can expect ragged tensors to stay in tf.keras, is that right ?

**Comment by SuryanarayanaY** [comment]
Hi @0x0L ,

AFAIK, `tf_keras` will work for replacement of `tf.keras`  . To use `tf_keras` with latest `tf-nightly` versions, we need to import `tf_keras` as `keras` and use `keras` instead of `tf.keras` since `tf.keras` still imports `keras-nightly`(i.e. `Keras3`) code instead of `tf_keras` code. 

I tried the same demo above and it works importing `tf_keras` as `keras` and replace `tf.keras` with `keras` and attached [gist](https://colab.sandbox.google.com/gist/SuryanarayanaY/4edc38fa6d904988817589d734cefbd3/62332-tf-keras-nightly.ipynb) here for reference.

Thanks to @mihaimaruseac for the inputs.
