### ISSUE TITLE
Incomplete metadata in other than x86_64 distribution

### ISSUE THREAD

**Issue by jelinkovaz** [tensorflow/tensorflow#62346]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.13.0

### Custom code

No

### OS platform and distribution

MacOS , Ventura 13.1

### Python version

3.9

### Current behavior?

Hello! 
When I try to install `tensorflow==2.13` using `pants` on my M2 mac I run into `No interpreter compatible with the requested constraints was found` issue.

According to the conversation with `pants` guys it's caused by incomplete dependencies metadata for other than `x86_64` distribution, as showed in the https://github.com/pantsbuild/pants/issues/20134
Same issue was someone having with `pytorch` https://github.com/pantsbuild/pants/issues/18936 

Would it be please possible to add the dependencies metadata for all of the distributions ? 
Thank you very much in advance! 

### Standalone code to reproduce the issue

```shell
N/A
```

**Comment by jsirois** [comment]
To clarify a bit, I disagree with @jelinkovaz and there is no single dist with complete metadata. The manylinux x86_64 wheel needs to also have:
```
Requires-Dist: tensorflow-macos (==2.13.0) ; platform_system == "Darwin" and platform_machine == "arm64"
```

To form a complete set of metadata.

To explain the issue here a bit more:
---
Although PyPI / PyPA have no strictures against the various distributions for a given project release having different metadata; it is not tooling-friendly in the case of attempting to build multi-platform lock files in particular.

Although PEP-691 is rolling out at PyPI, its not complete and that only covers PyPI; not other indexes or any find links repos at all. As such, to build a multi-platform lock completely correctly every applicable artifact for a given version must be downloaded and its metadata inspected. This is obviously a perf concern in the normal case and pretty much a non-starter in the ML (huge) wheel case.  For example, for tensorflow 2.13.0, which is the case that brought this to my attention, that would be 25 files to download and inspect metadata in at ~2.2GB total. This issue was even discussed in the failed attempt to get a Python lock file standard going in PEP-665 (some of the discussion of this can be found by starting here in item 6: https://discuss.python.org/t/pep-665-specifying-installation-requirements-for-python-projects/9911/130)

Pex thus makes the decision to just use the metadata from one of the distributions and not pull down the rest. I'm sure there are more out there, but the two outliers I know of personally are just pytorch (for a while), and now tensorflow. This is after >2 years of production use of Pex multi-platform locking by Pants users in the wild.

This may not be a use-case of interest to the tensorflow maintainers, but, afaict, the end result would be compatible with what is released today. I suspect the primary issues making this not attractive might be time & effort to switch + possibly tooling getting in the way. I'm definitely ignorant of tensorflow project details.

**Comment by sushreebarsa** [comment]
@jsirois Thank you for your response here!

@jelinkovaz Could you please try to regenerate the metadata and make sure that the meta file is not corrupted or empty?

Yes, it would be possible to add the dependencies metadata for all of the distributions. However, it would be a significant amount of work. 

The error "No interpreter compatible with the requested constraints was found" can occur when you try to install TensorFlow==2.13 using Pants on your M2 Mac.  This is because TensorFlow 2.13 requires a Python interpreter that is compatible with the Apple Silicon architecture. You may try with the different TF.

Thank you!

**Comment by jelinkovaz** [comment]
@sushreebarsa Thank you for reply!

I'm sorry I'm a junior and don't know how it works under the hood exactly. Can you please tell me how you mean to regenerate the metadata ?  All the dependencies are being downloaded by pants.
And what do you mean by trying to use different TF ? The 2.13 is the earliest to support arm64, right? I've tried with 2.14 with the same result. 

My colleague has just suggested a solution that actually solved the problem for me. 
I've added environment markers to the tensorflow in the pants dependency file like this: 
```
tensorflow>=2.10.0; platform_machine == "x86_64"
tensorflow-macos>=2.10.0; platform_machine == "arm64"
```
and pants downloaded and installed the latest TensorFlow==2.14, tensorflow_macos-2.14.0-cp39-cp39-macosx_12_0_arm64.whl without issue. @jsirois FYI

We are now just wondering, shouldn't tensorflow automatically infer the platform and the architecture? We expected it to do that, that's why we didn't try this before. 

Thank you so much!

**Comment by sushreebarsa** [comment]
@jelinkovaz  Glad that your issue has been fixed using the following workaround;
```
tensorflow>=2.10.0; platform_machine == "x86_64"
tensorflow-macos>=2.10.0; platform_machine == "arm64"
```

Yes, TensorFlow should automatically infer the platform and architecture, but if some software packages would be running on your system it would conflict with TF.

Please move this ticket to closed status if the issue has been resolved?
Thank you!

**Comment by MajerMartin** [comment]
Hi @sushreebarsa, can you please provide more details on _"but if some other software packages would be running on your system it would conflict with TF"_? Regardless whether I am installing `tensorflow-macos` manually or as a part of TF installation, there can be potential conflicts and such conflict should be solved by isolation of runtime environment (virtual envs, containers, etc.). Or am I missing something?

**Comment by sushreebarsa** [comment]
@jelinkovaz Yes, generally these kinds of conflicts can be avoided using virtual environments or containers.
The workaround would help as you have mentioned above. For details info on mac build from source installation please have a look at [this](https://www.tensorflow.org/install/source#macos) doc. 
Thank you!
