### ISSUE TITLE
How to get c++ code coverage when running Python tests?

### ISSUE THREAD

**Issue by BiophiliaSWDA** [tensorflow/tensorflow#62403]
It seems connect with these two issues([51091](https://github.com/tensorflow/tensorflow/issues/51091), [46477](https://github.com/tensorflow/tensorflow/issues/46477)), but they were all closed by robot.
I try 
```
bazel coverage -s --instrument_test_targets --coverage_report_generator=@bazel_tools//tools/test:coverage_report_generator --coverage_support=@bazel_tools//tools/test:coverage_support --collect_code_coverage --jobs 5 //tensorflow
``` 
and 
```
sudo bazel coverage -s --instrument_test_targets --experimental_cc_coverage --coverage_report_generator=@bazel_tools//tools/test/CoverageOutputGenerator/java/com/google/devtools/coverageoutputgenerator:Main --combined_report=lcov --jobs 4 //tensorflow/core:all
```
The `.dat` files generated are all 0 Bytes. 

I want to use `bazel coverage` to calculate the `c++ code coverage`, when a python program runs. I don't know if this is possible. If not, can you provide a suitable way for me to obtain the `c++ code coverage`?

My envs:
```
Ubuntu20.04
Tensorflow2.12.0 (Building from Source)
bazel5.3.0 (using bazelisk)
Python3.9
CUDA11.7
cuDnn8.5.0
GCC9.4.0
```

**Comment by Zhangc2024** [comment]
Hello, I'm also struggling with this issue. I'm wondering if you've found a solution?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
