### ISSUE TITLE
How can a tensor remain in gpu when the kernel is launched but does not finish yet?

### ISSUE THREAD

**Issue by cuiguoxin** [tensorflow/tensorflow#6247]
It confuse me a lot. I'm reading the stream executor part of tensorflow's source code. I find that once a graph is executed on a gpu device, each kernel of the graph's nodes just allocates the output memory and launches the cuda kernel on gpu on a stream by passing the input and output device memory. So the op kernel is done but the real execution of the kernel (e.g. cuda) may not be done on the gpu yet. Here is the question: how can tensorflow assure the input memory allocated on the gpu devices still live when the execution really happens on the gpu? I checked the executor.cc file and found that once a kernel is launched, the input tensor is destroyed. Can anyone show me what I miss? Thanks!

**Comment by cuiguoxin** [comment]
In the gpu_device.cc file, the BaseGPUDevice::RequiresRecordingAccessedTensors() function return false since streams_.size() returns 1. So tensors allocated in a kernel's compute() method aren't recorded. No TensorReference will be created.

**Comment by michaelisard** [comment]
When there is a single stream, all kernel launches on the GPU are serialized. So you can think of the GPU memory allocator in TensorFlow as "simulating" the memory usage of the actual kernels. It determines what memory is needed for kernel 1, then enqueues kernel 1 for launch, then "frees" the memory needed by kernel 1. When simulating what memory is needed for kernel 2, it can re-use any temporary memory used by kernel 1, before enqueueing kernel 2, because there is a single stream. This means that kernel 2 is guaranteed not to execute until after kernel 1 completes. As you observe, the memory allocator does not indicate what memory is actually in use on the stream, but it does indicate what memory is available to use for the next kernel to be enqueued, and that is the information that is needed when running the next Op.

Does that make sense?

**Comment by cuiguoxin** [comment]
hi, @michaelisard . I know that all kernels launched on a stream are serialized. For a typical op's kernel's Compute method, the mode is as follows I think: first it gets the input tensor of the kernel, then allocates the out tensor memory on gpu and at last launches the kernel (e.g. cuda) and after all the above things done, the Compute() method returns. So the next Op's kernel's Compute method may be called at once. Tensor's TensorBuffer stores the pointer to the location of the real tensor bytes and it can be remained in gpu if there is an tensor object or an TensorReference object remains in the program. However once a op's kernel is done, it's input will be cleaned and I haven't see any Tensor or TensorReference object alive in the program since the device's RequiresRecordingAccessedTensors() method returns false. So how can this tensor's byte remains in gpu? In detail, does allocating memory on gpu is queued on the stream that executes the kernel?

**Comment by zffchen78** [comment]
TF runtime does not allocate gpu memory per op. Instead, it has it's own
allocator, which grabs a big chunk (the pool) from cuda and never returns
to cuda. All tensor objects are allocated within the pool.

Combined w/ single compute stream configuration, one can prove the memory
safety in a similar way as people prove multi-threaded program's memory
safety properties, albeit much simpler for a single gpu cuda w/ only one
copy-in stream and one copy-out stream.

Consider the following 3 operations in sequence:
   x = add(a, b)
   y = add(x, c)
   z = add(y, d)
assuming, a, b, c, d, x, y, and z are of the same shape, and x and y are
not used before the 3rd operation.

If we, TF runtime, know that they are run on the same gpu device and hence
one single gpu stream, the following are relevant events on cpu and gpu
respectively:
cpu:
  allocate x
  dispatch kernel for x = add(a, b)
  allocate y
  dispatch kernel for y = add(x, c)
  deallocate x
  allocate z
  dispatch kernel for z = add(y, d)
  deallocate y

gpu:
  execute kernel for x = add(a, b)
  execute kernel for y = add(x, b)
  execute kernel for z = add(y, b)

The TF data flow graph guarantees that the events on cpu above happens one
after another. The single cuda stream semantics guarantees events on gpu
above happens one after another. dispatch kernel and execute kernel has the
strict happen-after relation. If you draw the happen-after edges of these
events, you can see their correctness.

More importantly, this allows us the TF runtime to reuse the memory release
by "deallocate x" immediately to "allocate z".


"""
I know that all kernels launched on a stream are serialized. For a typical
op's kernel's Compute method, the mode is as follows I think: first it gets
the input tensor of the kernel, then allocates the out tensor memory on gpu
and at last launches the kernel (e.g. cuda) and after all the above things
done, the Compute() method returns. So the next Op's kernel's Compute
method may be called at once. Tensor's TensorBuffer stores the pointer to
the location of the real tensor bytes and
"""
Up to this point, your understanding matches what TF runtime does.

"""it can be remained in gpu if there is an tensor object or an
TensorReference object remains in the program.
However once a op's kernel is done, it's input will be cleaned and I
haven't see any Tensor or TensorReference object alive in the program since
the device's RequiresRecordingAccessedTensors() method returns false. So
how can this tensor's byte remains in gpu? In detail, does allocating
memory on gpu is queued on the stream that executes the kernel?"""

This section of your description doesn't chime well with TF runtime
implementation. Maybe the point that TF runtime has its own memory pool can
help you understanding, I hope. Without such a pool, yes, you need to queue
the cuda allocation and deallocation calls on the appropriate stream and/or
adds proper waiting events, which we think is a rather complex scheme to
engineer when differently cuda libraries are used concurrently.

**Comment by cuiguoxin** [comment]
hi, @zffchen78 ,I checked your answer and the problem still got solved for me. In gpu_device.cc file, I find that EigenCudaStreamDevice class has an deallocate() method which is  async and gets executed when the stream has done all the previous events. However I didn't find the use of the deallocated method. How does the Allocator like GPUBFCAllocator has this async action?

**Comment by cuiguoxin** [comment]
I see. Thanks!!! @michaelisard @zffchen78
