### ISSUE TITLE
Keras namespace stubs are gone after upgrading to 2.15

### ISSUE THREAD

**Issue by tbhaxor** [tensorflow/tensorflow#62491]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

v2.15.0-rc1-8-g6887368d6d4

### Custom code

Yes

### OS platform and distribution

Arch Linux x64

### Python version

3.11

### Current behavior?

I upgraded it from 2.14 to 2.15 and the keras intellisense stub in the vscode is missing.

![image](https://github.com/tensorflow/tensorflow/assets/28386721/8b9f63eb-3012-4758-b5de-a325ac9bfc83)

I restarted the LSP, still it doesn't show `keras` namespace. However, on checking in the REPL it shows the completion

![image](https://github.com/tensorflow/tensorflow/assets/28386721/a11bf08d-0c0c-466a-b647-d216be5a5b2e)

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
```

**Comment by AnthonyMichaelTDM** [comment]
i'm having the same issue

**Comment by tilakrayal** [comment]
@tbhaxor,
Hi,

Thanks for reporting the issue.

Since the migration, there were many changes made, the error you are getting is due to one such change here https://github.com/keras-team/tf-keras/commit/cff6ac903e2b8a0dde2a469d949f0f0ce3b5f282.

To get rid of the error, you need to install tf-keras-nightly as well as tf-nightly.

Note that, tf-keras-nightly is legacy Keras code, to use the Keras 3 with multi-backend support, use keras-nightly and import Keras directly.

Also the fix will be available once both Tensorflow and tf-keras do the next stable release, until then continue using as suggested. Thank you!

**Comment by sachinprasadhs** [comment]
Hi, 

Keras is migrated to Keras 3 with multi backend support.

Could you please install Keras separately using `pip install keras==3.0.0` and `import keras` directly and let us know the outcome with `keras.layers` etc

**Comment by tbhaxor** [comment]
Yes, we have already migrated to Keras 3 and it's working fine. Thanks for your response.
