### ISSUE TITLE
Unexpected NaN when invoking apis combination of tf.GradientTape().jacobian and tf.multiply and tf.math.reciprocal

### ISSUE THREAD

**Issue by beanduan22** [tensorflow/tensorflow#62558]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.13

### Custom code

Yes

### Current behavior?

```python
import tensorflow as tf
import numpy as np

with tf.device("/cpu:0"):
  def test(a,b):
    with tf.GradientTape() as tape_1:
      tape_1.watch(a)
      tape_1.watch(b)
      w = a * tf.math.reciprocal(b)
      print(w)
    grad_1 = tape_1.jacobian(w, a)
    return grad_1


  a = tf.constant([3], dtype=tf.float32)
  b = tf.constant([0, 2, 3], dtype=tf.float32)

  cpu_output_1 = test(a,b)

with tf.device("/gpu:0"):
  def test(a, b):
    with tf.GradientTape() as tape_1:
      tape_1.watch(a)
      tape_1.watch(b)

      w = a * tf.math.reciprocal(b)
    grad_1 = tape_1.jacobian(w, a)
    return grad_1


  a = tf.constant([3], dtype=tf.float32)
  b = tf.constant([0, 2, 3], dtype=tf.float32)

  gpu_output_1 = test(a, b)

print(cpu_output_1)
print(gpu_output_1)


### Standalone code to reproduce the issue

```shell
when i fuzzing on tensorflow, found unexpected NaN when invoking apis combination of tf.GradientTape().jacobian and tf.multiply and tf.math.reciprocal
```

### Relevant log output

```shell
2023-12-04 11:42:40.628266: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: SSE SSE2 SSE3 SSE4.1 SSE4.2 AVX AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
tf.Tensor([inf 1.5 1. ], shape=(3,), dtype=float32)
tf.Tensor(
[[inf]
 [nan]
 [nan]], shape=(3, 1), dtype=float32)
tf.Tensor(
[[inf]
 [nan]
 [nan]], shape=(3, 1), dtype=float32)
```

**Comment by tilakrayal** [comment]
@sachinprasadhs,
I was able to reproduce the issue on tensorflow v2.14, v2.15 and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3a14ff730af805b46e67d991f49604c7/untitled1610.ipynb).

**Comment by Gopi-Uppari** [comment]
Hi @beanduan22,

I reproduced the issue. Please refer to the [gist file](https://colab.research.google.com/gist/Gopi-Uppari/02ff4a4819295f0dd221e98d3741a8e0/tf_issue_62558.ipynb), where The issue arises because of a division by zero in the calculation of tf.math.reciprocal(b) when b contains zero. The reciprocal of zero is undefined (1/0 = inf), which propagates through the computation and results in NaN during gradient calculations.

To avoid it, One of the possible solution should be to replace b = 0 with a small value (1e-7) to avoid division by zero.

Thank you.
