### ISSUE TITLE
Add PR Template

### ISSUE THREAD

**Issue by Yuheshpandian** [tensorflow/tensorflow#62561]
Hi @tensorflow I'm @Yuheshpandian. I personally love your project. I love to use it in python but still i'm learning many intermediate stuff in python.

I saw many contributions to your repository. So it would be better if you add a PR_Template(Pull Request Template) to your Project.

Thank You

**Comment by SuryanarayanaY** [comment]
Hi @Yuheshpandian ,

We have [CONTRIBUTING.md](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md) for users to guide about how to contribute to the source code and the process flow.

I think adding PR template is not required here.Could you need to add more info or example templates to review?

**Comment by Yuheshpandian** [comment]
I really thought adding PR_TEMPLATE is very essential and that is why it is there in the community standards section in insights but I understood it is not so required.

Thank you

**Comment by SuryanarayanaY** [comment]
Hi @Yuheshpandian ,

Yes, PR template is not much required ask, since most of the details as mentioned in issue template are irrelevant to PR and while raising PR user is asked for Title and the description which is enough. In some cases if test cases are required Dev team will ask for it anyways on case to case basis.We do add suitable labels for the PR once it is created.

Please feel free to close the issue if satisfied with the responses.Thanks!

**Comment by Yuheshpandian** [comment]
Ok thank you for the response
