### ISSUE TITLE
Advisory GHSA-9jjw-hf72-3mxw contains invalid semver

### ISSUE THREAD

**Issue by crfrolik** [tensorflow/tensorflow#62590]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

N/A

### Custom code

No

### OS platform and distribution

N/A

### Mobile device

N/A

### Python version

N/A

### Current behavior?

https://github.com/advisories/GHSA-9jjw-hf72-3mxw
https://github.com/tensorflow/tensorflow/security/advisories/GHSA-9jjw-hf72-3mxw

The semver string is `2.4.0rc0` but it should be `2.4.0-rc.0`. This causes problems for tools and scripts that parse the advisory database.

### Standalone code to reproduce the issue

```shell
N/A
```

**Comment by sachinprasadhs** [comment]
Hi,

Thanks for reporting the issue.

`2.4.0-rc0` is the naming convention we used during the release which you can refer the same here https://github.com/tensorflow/tensorflow/releases/tag/v2.4.0-rc0.

Did you mean it should be `2.4.0-rc0` not` 2.4.0-rc.0`

**Comment by mihaimaruseac** [comment]
It should be `2.4.0-rc0`, with a dash in front of `rc`. While `pip install` supports the case where the dash is missing, this is not standards compliant and tooling that is more strict will be broken.

**Comment by sachinprasadhs** [comment]
@mihaimaruseac , The package table seems to be generated though other file, could you please help me with the source file to make the necessary changes. Thanks

**Comment by mihaimaruseac** [comment]
It's not on files on the repository. It's on the vulnerabilities (example https://github.com/advisories/GHSA-9jjw-hf72-3mxw).

**Comment by mihaimaruseac** [comment]
I updated https://github.com/tensorflow/tensorflow/security/advisories/GHSA-9jjw-hf72-3mxw so maybe this will result in a fix

**Comment by mihaimaruseac** [comment]
There is no change on the https://github.com/advisories/GHSA-9jjw-hf72-3mxw link, probably this should be handled via GitHub support instead.

Alternatively, may I recommend switching to data provided by osv.dev?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
