### ISSUE TITLE
CI build gives a command not found error on /install/install_pip_packages.sh

### ISSUE THREAD

**Issue by giuliocn** [tensorflow/tensorflow#62645]
Steps to error:

1. I forked Tensorflow `master` branch 
2. WITH a Github workspace I created a new branch for editing.
3. I tried to run CI tests from the `/workspaces/tensorflow/` directory with command:
```
tensorflow/tools/ci_build/ci_build.sh CPU bazel test //tensorflow/...
```
4. This led me to the following error:
<details>
```
/...
WORKSPACE: /workspaces/tensorflow
CI_DOCKER_BUILD_EXTRA_PARAMS: 
CI_DOCKER_EXTRA_PARAMS: 
COMMAND: bazel test //tensorflow/...
CI_COMMAND_PREFIX: ./tensorflow/tools/ci_build/builds/with_the_same_user ./tensorflow/tools/ci_build/builds/configured cpu
CONTAINER_TYPE: cpu
BUILD_TAG: tf_ci
  (docker container name will be tf_ci.cpu)

Building container (tf_ci.cpu)...
[+] Building 1.7s (11/17)                                                                                     docker:default
 => [internal] load .dockerignore                                                                                       0.1s
 => => transferring context: 2B                                                                                         0.0s
 => [internal] load build definition from Dockerfile.cpu                                                                0.1s
 => => transferring dockerfile: 654B                                                                                    0.0s
 => [internal] load metadata for docker.io/library/ubuntu:16.04                                                         0.8s
 => [auth] library/ubuntu:pull token for registry-1.docker.io                                                           0.0s
 => [ 1/12] FROM docker.io/library/ubuntu:16.04@sha256:1f1a2d56de1d604801a9671f301190704c25d604a416f59e03c04f5c6ffee0d  0.0s
 => [internal] load build context                                                                                       0.1s
 => => transferring context: 1.73kB                                                                                     0.0s
 => CACHED [ 2/12] COPY install/*.sh /install/                                                                          0.0s
 => CACHED [ 3/12] RUN /install/install_bootstrap_deb_packages.sh                                                       0.0s
 => CACHED [ 4/12] RUN add-apt-repository -y ppa:openjdk-r/ppa &&     add-apt-repository -y ppa:george-edison55/cmake-  0.0s
 => CACHED [ 5/12] RUN /install/install_deb_packages.sh                                                                 0.0s
 => ERROR [ 6/12] RUN /install/install_pip_packages.sh                                                                  0.6s
------                                                                                                                       
 > [ 6/12] RUN /install/install_pip_packages.sh:                                                                             
0.359 --2023-12-15 16:46:42--  https://bootstrap.pypa.io/get-pip.py
0.359 Resolving bootstrap.pypa.io (bootstrap.pypa.io)... 151.101.36.175, 2a04:4e42:9::175
0.383 Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|151.101.36.175|:443... connected.
0.393 HTTP request sent, awaiting response... 200 OK
0.399 Length: 2632263 (2.5M) [text/x-python]
0.399 Saving to: 'get-pip.py'
0.399 
0.399      0K .......... .......... .......... .......... ..........  1% 35.2M 0s
[...]
0.430   2500K .......... .......... .......... .......... .......... 99%  120M 0s
0.430   2550K .......... ..........                                 100%  130M=0.03s
0.430 
0.430 2023-12-15 16:46:42 (81.1 MB/s) - 'get-pip.py' saved [2632263/2632263]
0.430 
0.432 /install/install_pip_packages.sh: line 21: python3.6: command not found
------
Dockerfile.cpu:11
--------------------
   9 |         add-apt-repository -y ppa:george-edison55/cmake-3.x
  10 |     RUN /install/install_deb_packages.sh
  11 | >>> RUN /install/install_pip_packages.sh
  12 |     RUN /install/install_bazel.sh
  13 |     RUN /install/install_proto3.sh
--------------------
ERROR: failed to solve: process "/bin/sh -c /install/install_pip_packages.sh" did not complete successfully: exit code: 127
ERROR: docker build failed. Dockerfile is at /workspaces/tensorflow/tensorflow/tools/ci_build/Dockerfile.cpu
```
</details>

**Comment by AbhisekOmkar** [comment]
The error message indicates that the Docker build process is failing at the step where it is trying to run the `/install/install_pip_packages.sh` script inside the container. The specific error is:

```
/install/install_pip_packages.sh: line 21: python3.6: command not found
```

This suggests that the Python 3.6 executable is not available in the Docker image at the time this script is being executed.

To resolve this issue, you can try the following steps:

1. **Check Python Version:**
   Confirm the available Python version in your Docker image. It seems that Python 3.6 is not installed or is not in the system's PATH.

2. **Update Install Script:**
   Update the `/install/install_pip_packages.sh` script to use the correct Python version available in your Docker image. You might need to replace `python3.6` with the appropriate Python executable name.

   For example, if the available Python executable is `python3`, you can update the script as follows:

   ```bash
   # Replace this line in install_pip_packages.sh
   python3.6 -m ensurepip

   # With this line
   python3 -m ensurepip
   ```

3. **Modify Dockerfile:**
   Ensure that the Dockerfile (`Dockerfile.cpu`) specifies the correct version of Python. You may need to install Python 3.6 explicitly if it's not included in the base image.

   Add the following lines to your Dockerfile before the problematic script:

   ```Dockerfile
   # Install Python 3.6
   RUN apt-get update && apt-get install -y python3.6
   ```

4. **Verify Dockerfile Context:**
   Ensure that all the necessary files and dependencies are available in the Docker build context. It's possible that some required files or scripts are missing.

5. **Review Dependencies:**
   Double-check other dependencies and scripts that may affect the Python installation. Sometimes, issues in earlier steps can cascade into problems in later steps.

After making these adjustments, try rebuilding the Docker image and see if the issue is resolved. If you encounter further issues, review the relevant parts of the Dockerfile and installation scripts to identify any missing dependencies or incorrect configurations. @SuryanarayanaY @giuliocn

**Comment by SuryanarayanaY** [comment]
Hi @giuliocn ,

For nightly you need to have Python version in the range of 3.9-3.11. You need to install Python in this range.

For me it seems even though you are updating the python the python path not set to updated version. Could you try to set the path to newly installed python version. For example for me this [instructions](https://stackoverflow.com/questions/63168301/how-to-change-the-python-version-from-default-3-5-to-3-8-of-google-colab) worked for updating python version in Google colab.

**Comment by SuryanarayanaY** [comment]
CC: @angerson , Could you have any pointers here!

**Comment by tilakrayal** [comment]
@giuliocn,
Could you please confirm whether the issue is resolved in the latest TensorFlow version and for the PR raised which is draft stage would be cleared and then it will assign the reviewer for the review.

https://github.com/tensorflow/tensorflow/pull/62720

https://github.com/tensorflow/tensorflow/pull/62898


Thank you!

**Comment by giuliocn** [comment]
> @giuliocn, Could you please confirm whether the issue is resolved in the latest TensorFlow version and for the PR raised which is draft stage would be cleared and then it will assign the reviewer for the review.
> 
> #62720
> 
> #62898
> 
> Thank you!

With Tensorflow v2.16.1 (latest) the issue is still present. @tilakrayal Let me know how I can assist you.

**Comment by tilakrayal** [comment]
CC: @angerson

**Comment by nicolaspi** [comment]
@giuliocn the build fails on the current master branch, even after applying your changes.

**Comment by giuliocn** [comment]
> @giuliocn the build fails on the current master branch, even after applying your changes.

Pip dependencies were updated without preventing conflicts on future updates. Now, I noticed the presence of a `requirements_lock` file inside the WORKSPACE  build. Shall We use this file to build a conflict free environment with `Dockerfile.cpu`?

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

Also try the required file inside the WORKSPACE build.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
