### ISSUE TITLE
model detects hand as a face. I cant retrieve confidence score from  tfjs-models/face-detection

### ISSUE THREAD

**Issue by DiannaShonia** [tensorflow/tensorflow#62683]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

last version

### Custom code

Yes

### Current behavior?

In mediapipe model documentation (see: https://drive.google.com/file/d/1d4-xJP9PVzOvMBDgIjz6NhvpnlG9_i0S/preview) it says that alongside with bounding box coordinates and keypoints, confidence score should be also returned. 

But there is no info about that in face-detection github repo and in the code. 

In face-detection Demo, you can see for yourself that fists are displayed as faces. I need confidence score to prevent this action.
https://storage.googleapis.com/tfjs-models/demos/face-detection/index.html?model=mediapipe_face_detector

### Standalone code to reproduce the issue

```shell
https://storage.googleapis.com/tfjs-models/demos/face-detection/index.html?model=mediapipe_face_detector

Try to show different hand movements, its being detected as face (mostly fist)
```

**Comment by sushreebarsa** [comment]
@DiannaShonia Please ensure that you're using a model version that provides confidence scores. Some older versions might not provide the same. Also try to raise the minimum confidence score required for a detection to be considered a face. This can filter out less confident detections, potentially reducing false positives.

This issue is related to tfjs so for any further questions , could you please post this issue in [tfjs](https://github.com/tensorflow/tfjs/issues) repository?
 
Thank you!
