### ISSUE TITLE
How to get tf.data autotune metrics?

### ISSUE THREAD

**Issue by frank-lsf** [tensorflow/tensorflow#62690]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

latest

### Custom code

No

### Current behavior?

I want to better understand the internals of the `tf.data` autotuning algorithm. I found that a lot of metrics are logged in https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/metrics.h and https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/model.cc, but I cannot find in my program runs where these metrics are logged or how I can get programatic access to them.

For example, I want to see how tensorflow models the output latency of my operators, according to Section 3.3.2 of the tf.data paper (https://arxiv.org/abs/2101.12127). Can I somehow get this information from either the Python API or the logs?

cc @tlongeri if you are still working on Tensorflow metrics

### Standalone code to reproduce the issue

```shell
Any tf.data pipeline. I'm using the code from https://www.tensorflow.org/guide/data_performance#reproducing_the_figures
```

**Comment by mahrukhS** [comment]
Based on the tensorflow documentation, it seems there are different autotune algorithms. 
https://www.tensorflow.org/api_docs/python/tf/data/experimental/AutotuneAlgorithm

Open the **symbols panel** to see the structure in the options.py file below
https://github.com/tensorflow/tensorflow/blob/v2.14.0/tensorflow/python/data/ops/options.py#L540

**Comment by tilakrayal** [comment]
@franklsf95,
**tf.data** builds a performance model of the input pipeline and runs an optimization algorithm to find a good allocation of its CPU budget across all parameters specified as **AUTOTUNE**. While the input pipeline is running, `tf.data` tracks the time spent in each operation, so that these times can be fed into the optimization algorithm.

The [OptimizationOptions](https://www.tensorflow.org/api_docs/python/tf/data/experimental/OptimizationOptions?version=stable) object gives some control over how autotune will behave. Thank you!

**Comment by franklsf95** [comment]
@tilakrayal I understand the autotune algorithm, but want to see how it works in action. Specifically, for example, the code logs the stopping condition for the autotune algorithm (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/model.cc#L2695), which would help me understand how the algorithm works. My question is where can I find these metrics? They must be logged somewhere.

**Comment by tilakrayal** [comment]
Hi,

Thank you for opening this issue. Since this issue has been open for a long time, the code/debug information for this issue may not be relevant with the current state of the code base.

The Tensorflow team is constantly improving the framework by fixing bugs and adding new features. We suggest you try the latest TensorFlow [version](https://pypi.org/project/tensorflow/) with the latest compatible hardware configuration which could potentially resolve the issue. If you are still facing the issue, please create a new GitHub issue with your latest findings, with all the debugging information which could help us investigate.

Please follow the [release notes](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md) to stay up to date with the latest developments which are happening in the Tensorflow space.
