### ISSUE TITLE
Once Model Trained Does Not Empty The GPU Space, it uses  so much of much GPU Space. Using M1 Pro. Installed the tensorflow using the  TensorFlow Plugin Metal Developers

### ISSUE THREAD

**Issue by NiharJani2002** [tensorflow/tensorflow#62773]
### Issue type

Performance

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.15.0

### Custom code

Yes

### OS platform and distribution

Mac OS Sononoma 14.2 and M1 Pro 

### Python version

3.9.18

### Current behavior?

Utilises The Entire Gpu and does not empty when the model is completely trained. If I again train the model, it just add up the space in my gpu.

### Standalone code to reproduce the issue

```shell
Training Dataset of Brain Tumour segmentation .nii files, convert it into numpy and train unet on it. Size of Unet 4 encoder and 4 decoder.
```

### Relevant log output

```shell
Suggestion Given By The Mac to close the code, occupies most of the spaces In RAM. 
RAM - 16gb
```

**Comment by sushreebarsa** [comment]
@NiharJani2002 Could you use tf.memory.total_allocated_memory() to check the total amount of GPU memory allocated by your TensorFlow session. Please ensure you're using the latest versions of TensorFlow and tensorflow-metal plugin as they might have included memory optimization updates. Kindly check for known issues and workarounds related to memory usage on the Apple Developer Forum (https://developer.apple.com/metal/tensorflow-plugin/).
In order to expedite the trouble-shooting process, please provide a complete code snippet to reproduce the issue reported here.
Thank you!

**Comment by NiharJani2002** [comment]
The issue has been solved. I have seen blogs to solve it

**Comment by sushreebarsa** [comment]
@NiharJani2002 Thank you for the confirmation!
Could you please move this issue to closed status if it is resolved?
Thank you!
