### ISSUE TITLE
Info/warnings when importing Tensorflow

### ISSUE THREAD

**Issue by bergentruckung** [tensorflow/tensorflow#62781]
### Issue type

Build/Install

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

2.13.1

### Custom code

No

### OS platform and distribution

RHEL 8.9

### Python version

3.11.4

### Bazel version

5.4

### GCC/compiler version

10.4

### CUDA/cuDNN version

8.9.5

### GPU model and memory

A100 PCIe

### Current behavior?

Importing tensorflow prints the following:

```
In [1]: import tensorflow as tf                                                                                                                                                                               
2024-01-11 05:40:05.061907: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.                    
To enable the following instructions: AVX512F, in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                                                   
Using TensorFlow backend.                                                                                                                                                                                     
```
It was built with support for GPUs and I can assert that from `tf.test.is_built_with_gpu_support()`. Are the above messages problematic? If they're not, what's the way to silence them while importing tensorflow?

### Standalone code to reproduce the issue

```shell
import tensorflow
```
```


### Relevant log output

```shell
In [1]: import tensorflow as tf                                                                                                                                                                               
2024-01-11 05:40:05.061907: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.                    
To enable the following instructions: AVX512F, in other operations, rebuild TensorFlow with the appropriate compiler flags.                                                                                   
Using TensorFlow backend.
```

**Comment by henrykironde** [comment]
@bergentruckung what flags did you used when building?

**Comment by bergentruckung** [comment]
Yup, here are the flags that I used:
```
-msse4.2 -mavx2 -mfma -march=sandybridge -mtune=broadwell
```
I believe this is because TF sees that I have better instructions to use, but my build doesn't support it? If that's the case, then I'm good and would there be a way to silence this message?

Also, I see this sometimes:
```
In [1]: import tensorflow                                                                                                                                                                                                                                                                                          
2024-01-15 01:19:37.725211: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
```
Is that also a problem? I'm using cuDNN 8.9.5. Should I use the env variable to turn it off, or should I use it? What are the implications? In case I'm supposed to turn it off, is there a better way to turn it off, rather than using the env variable (maybe by using a config file)?

**Comment by henrykironde** [comment]
- `oneDNN custom operations are on` this means that  TensorFlow has enabled custom operations from the oneDNN library.

- `You may see slightly different numerical results due to floating-point round-off errors from different computation orders` this tells you that oneDNN might introduce slight numerical differences in results due to floating-point round-off errors, especially when dealing with different computation orders.
-  `To turn them off, set the environment variable TF_ENABLE_ONEDNN_OPTS=0.` in order to disable the oneDNN custom operations and get consistent numerical results across different computation orders, you can set the TF_ENABLE_ONEDNN_OPTS environment variable to 0 or use do the same in the `Python` interface. 

```python
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
# import tensorflow with disabled ONEDNN
import tensorflow
```

**Comment by Venkat6871** [comment]
Hi **@bergentruckung** ,
Sorry for the delay, "Using TensorFlow backend," indicates that TensorFlow is using its default backend for computations.
If you want to silence these messages or suppress the TensorFlow informational logs, you can adjust the TensorFlow logging level. TensorFlow uses the tf.logging module for logging. For this you need to use
```
import tensorflow as tf
tf.logging.set_verbosity(tf.logging.ERROR)
```
This will suppress INFO and WARNING level messages. Place this code at the beginning of your script or notebook to control the logging level when TensorFlow is imported.

TensorFlow is using oneDNN (formerly known as Intel MKL-DNN) for custom operations, which may lead to slightly different numerical results due to floating-point round-off errors from different computation orders. oneDNN is a highly optimized deep learning library, and TensorFlow uses it for certain operations to enhance performance.

If you're not facing any issues with numerical stability or differences in results, you can leave it enabled. However, if you want to turn it off, you can set the environment variable as like this.
```
import os
os.environ['TF_ENABLE_ONEDNN_OPTS'] = '0'
import tensorflow as tf
```
this will disable oneDNN custom operations.

Thank you!
