### ISSUE TITLE
NonMatchingChecksumError while downloading Caltech Birds 2011 dataset

### ISSUE THREAD

**Issue by aditya02shah** [tensorflow/tensorflow#62805]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

Yes

### OS platform and distribution

Google Colab

### Python version

3.10

### Current behavior?

I am encountering a `Non-Matching Checksum error` while attempting to download the `caltech_birds2011` dataset.
The error persists even when using the `tfds-nightly` package.

### Standalone code to reproduce the issue

```shell
Code to reproduce the error:
import tensorflow_datasets as tfds
dataset = tfds.load('caltech_birds2011', split='train')

Colab:https://colab.research.google.com/drive/1jrI02VQ7ETw0oEL5RRk4vD-AQH07ZtIw?usp=sharing
```

### Relevant log output

```shell
Downloading and preparing dataset 1.11 GiB (download: 1.11 GiB, generated: 1.11 GiB, total: 2.22 GiB) to /root/tensorflow_datasets/caltech_birds2011/0.1.1...
Dl Completed...: 100%
1/1 [00:00<00:00, 1.21 url/s]
Dl Size...:
0/0 [00:00<?, ? MiB/s]
---------------------------------------------------------------------------
NonMatchingChecksumError                  Traceback (most recent call last)
<ipython-input-2-b0dbf98bec1b> in <cell line: 3>()
      1 import tensorflow_datasets as tfds
      2 print("Version",tfds.__version__)
----> 3 dataset = tfds.load('caltech_birds2011', split='train')

19 frames
/usr/local/lib/python3.10/dist-packages/tensorflow_datasets/core/download/download_manager.py in _validate_checksums(url, path, computed_url_info, expected_url_info, force_checksums_validation)
    807         'https://www.tensorflow.org/datasets/overview#fixing_nonmatchingchecksumerror'
    808     )
--> 809     raise NonMatchingChecksumError(msg)
    810 
    811 

NonMatchingChecksumError: Artifact https://drive.google.com/uc?export=download&id=1hbzc_P1FuxMkcabkgn9ZKinBwW683j45, downloaded to /root/tensorflow_datasets/downloads/ucexport_download_id_1hbzc_P1FuxMkcabkgn9ZKinBw1sbZS_7v82APqMiPk0wej8WzZ5MmtVy61NUy-F6708.tmp.2f1a547e76e047aa9c2c734021a5bd45/download, has wrong checksum:
* Expected: UrlInfo(size=1.07 GiB, checksum='0c685df5597a8b24909f6a7c9db6d11e008733779a671760afef78feb49bf081', filename='CUB_200_2011.tgz')
* Got: UrlInfo(size=2.37 KiB, checksum='90974fd9547262b60bca7e22993f85c62ea79200cfee1bf4bef26e0334a0a7fc', filename='download')
```

**Comment by tilakrayal** [comment]
@aditya02shah,
I was able to reproduce the issue on tensorflow v2.15. Could you please allow the developer team to deep dive into the issue and resolve the error. Thank you!

**Comment by aditya02shah** [comment]
@tilakrayal Thank your for confirming and looking into the issue! Let me know if you need more details.

**Comment by tilakrayal** [comment]
@aditya02shah,
Apologies for the delay. As per the documentation, **NonMatchingChecksumError** is raised due to the reasons below.
The website may be down, original datasets files may have been updated or Drive sometimes rejects downloads when too many people access the same URL.

As the workaround you can try to download from the [link](https://drive.usercontent.google.com/corp/download?id=1hbzc_P1FuxMkcabkgn9ZKinBwW683j45&export=download&authuser=0) and also request to check in [datasets](https://github.com/tensorflow/datasets/issues) repository for the quick resolution.

https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/image_classification/caltech_birds.py#L227

https://github.com/tensorflow/datasets/issues/1482

Thank you!

**Comment by aditya02shah** [comment]
@tilakrayal Thanks for the assistance!
