### ISSUE TITLE
How to change color of specific body  point in Pose estimation?    eg. If I want to change color of Hip, Knee & Ankle then is it possible?

### ISSUE THREAD

**Issue by vnanaware111** [tensorflow/tensorflow#62892]
### Issue type

Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

'TensorFlowLiteSwift', '~> 0.0.1-nightly', :subspecs => ['CoreML', 'Metal']

### Custom code

Yes

### Current behavior?

Unable to change specific body point color.

### Standalone code to reproduce the issue

```shell
eg. I want to change color of Hip, Knee & Ankle then is it possible?
```

**Comment by sushreebarsa** [comment]
@vnanaware111  Changing the color of specific body points like Hip, Knee, and Ankle in Pose estimation with TensorFlow Lite (TFLite) is achievable, but it might require some post-processing steps since TFLite itself primarily focuses on model inference. Here is an approach you can consider:
`Inference with TFLite:` Please run your TFLite Pose estimation model to get the predicted keypoints for each body part.
`Post-processing script:`
Then access the keypoints for the desired body parts (Hip, Knee, Ankle) based on their indices or names in the output tensor. Please load the original image you used for inference and iterate through the keypoints and draw circles or shapes on the image at their respective locations using an image editing library like OpenCV or Pillow. You can assign specific colors to Hip, Knee, and Ankle while drawing. Finally save or display the modified image with the highlighted body points.

Thank you!
