### ISSUE TITLE
What was the reason of using the Tensorflow 2.8.0 in the custom object detction 

### ISSUE THREAD

**Issue by rohitkumar9989** [tensorflow/tensorflow#62953]
In the tensorflow custom object detection using the tensorflow lite, we have implemented the usage of the tensorflow 2.8.0 version.

`
sudo apt -y install libportaudio2
pip install -q --use-deprecated=legacy-resolver tflite-model-maker
pip install -q pycocotools
pip install -q opencv-python-headless==4.1.2.30
pip uninstall -y tensorflow && pip install -q tensorflow==2.8.0
`

The reason for the implementation was not defined in the docs.

 Many people say that the issue was due to the compatibility version of the Colab.

If its due to the compatibility version of the colab, and If I tried to run the model on my local PC which has rtx 4060, will the model work normally without any issues (Im running the tensorflow==2.15.0 version)

**Comment by tilakrayal** [comment]
@rohitkumar9989,
There is an issue with the `tf-lite-modelmaker`. This issue is unlikely to be resolved soon. Below are the couple of options to use **tflite-model-maker**:

1. Just use [mediapipe model maker](https://developers.google.com/mediapipe/solutions/model_maker) in colab (You can use a GPU/TPU here as well though there are potential limitations) https://research.google.com/colaboratory/faq.html

2. Attempt to fix your current setup, can you try pip install scann?

3. Build Tensorflow from source w/o AVX support and with Cuda(Nvidia GPUs)/RocM(AMD GPUs) support https://www.tensorflow.org/install/source (For WSL you would follow linux instructions), then try to simultaneously install all your required packages with the built package so that they have the best chance to play nicely together

4. Use a lower level API and skip tflite-model-maker/mediapipe-model-maker and use [keras](https://keras.io/)/[TF](https://www.tensorflow.org/tutorials) directly

https://github.com/tensorflow/tensorflow/issues/62942#issuecomment-1938193409
https://github.com/tensorflow/tensorflow/issues/60431

Thank you!
