### ISSUE TITLE
Cannot copy from a TensorFlowLite tensor (StatefulPartitionedCall:1) with shape [1, 10] to a Java object with shape [1, 10, 4].

### ISSUE THREAD

**Issue by khizii** [tensorflow/tensorflow#62979]
hey there i am a new in the field of android development i tried to run the project of custeom object detection on android app. the app works fines in pretrained model but when i tried to put my own custom model on it then it crashes and it crash report it shows this:

E  :53: GetCmdlineFileContents: Failed to open /proc/650/cmdline (No such file or directory)
Cannot copy from a TensorFlowLite tensor (StatefulPartitionedCall:1) with shape [1, 10] to a Java object with shape [1, 10, 4].

 if anyone solves this error please help me i will be thankful to you:
Below is the part of my code:
![Screenshot 2024-02-16 203916](https://github.com/tensorflow/tensorflow/assets/137616658/9014609e-63b1-4392-9cd7-95526532f79b)
if you want to see the full code please refer to this github:
 https://github.com/pramod722445/Custom_Object_Detection_App

**Comment by Rahulraj0308** [comment]
@khizii I think there is a mismatch between the output shape of your TFLite model. The model produces 10 values, while you're expecting 40 (10 x 4).

**Comment by tilakrayal** [comment]
@khizii,
Could you please take a  look at the output_details, specifically the shape of each output tensor, you will see that the order of outputs is actually [classes, boxes, num_detections, scores] or [scores, boxes, num_detections, classes] (because the shape of output at index 3 is same as shape of output 0, so one of them is scores and other is classes). 

Its likely that your Java code assumes [boxes, classes, scores, num_detections] - which is why the error says that you are trying to copy a wrong-shaped tensor into another one.
https://github.com/tensorflow/tensorflow/issues/46692
https://github.com/tensorflow/tensorflow/issues/55341

Thank you!

**Comment by furkancelikbm** [comment]
anyone fix this ? i couldnt fix for days
