### ISSUE TITLE
Given Shapes are not Broadcastable, tf to tf-lite conversion error

### ISSUE THREAD

**Issue by FabianSchuetze** [tensorflow/tensorflow#63069]
### 1. System information

Google colab as of 2024-02-27
tf version: 2.15.0

### Problem
I receive the following error when converting a tf module from tf to tfl-lite:
```
RuntimeError: Given shapes, [1,436,1024,3] and [1,218,512,3], are not broadcastable.Node number 1 (SUB) failed to prepare.
```
Below is the relevant class:
```
class Inpainting(Model):
    def __init__(self, downsample_factor, **kwargs):
        super(Inpainting, self).__init__(**kwargs)
        self.downsample_factor = downsample_factor
        self.downsize = Resizing(218, 512)

    @tf.function(input_signature=[
        tf.TensorSpec(shape=(1, 218, 512, 3)),
        tf.TensorSpec(shape=(1, 218, 512, 1)),
        tf.TensorSpec(shape=(1, 436, 1024, 3)),
        tf.TensorSpec(shape=(1, 436, 1024, 1)),
        ])
    def call(self, img_t_lr, depth_t_lr, img_t_w, depth_t_w):

        img_t_wlr = self.downsize(img_t_w)
        depth_t_wlr = self.downsize(depth_t_w)
        assert img_t_wlr.shape[1:] == img_t_lr.shape[1:], "must be same shape"
        diff_color = tf.math.subtract(img_t_lr, img_t_wlr)
        assert depth_t_lr.shape[1:] == depth_t_wlr.shape[1:], "must be same shape"
        diff_depth = tf.math.subtract(depth_t_lr, depth_t_wlr)
        diff = tf.concat([diff_color, diff_depth], axis=3)
        return diff
```
Please see here for the full [gist](https://colab.research.google.com/drive/18Q2-NvHFre1-1Dk2HYjTjX1MnUveERle?usp=sharing). 

I am a bit surprised that this happens. Could this be a bug?

**Comment by pkgoogle** [comment]
I think the bug is more that Resizing is converted to a broadcasting operation. If we remove it and make the shapes equivalent, I am able to convert: [gist](https://colab.sandbox.google.com/gist/pkgoogle/d3c0c4c6459343a0a5f7de1d0305db0f/conversionfails.ipynb)

Hi @arfaian, can you please take a look? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @FabianSchuetze 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/77

Let us know if you have any questions. Thanks.

**Comment by FabianSchuetze** [comment]
Thanks a lot. I'll close the issue then. I was aware of LiteRT but not that the transition happens so swiftly.
