### ISSUE TITLE
Adding a GPU model to the compatibility database in tflite

### ISSUE THREAD

**Issue by hooneecho** [tensorflow/tensorflow#63108]
### Issue type

Support

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.15

### Custom code

Yes

### Current behavior?

I have a question in the "acceleration/compatibility" part in tflite.
As far as I know, Samsung mobile model "samsung_xclipse_920" (S22) information was recently added to the compatibility database to check and support the GPU delegation.
https://github.com/tensorflow/tensorflow/commit/1f3d148aba6a364fb1a271410de4e2f74e32e136

I would like to add "samsung_xclipse_940", a S24 model that was recently released officially on the market,
Are there any ways to do it? Is there anything already in progress? Or, can I upload some PRs (gpu_compatibility.bin ...) related to this manually?

### Standalone code to reproduce the issue

```shell
flatc -t --raw-binary --strict-json database.fbs -- gpu_compatibility.bin
flatc -b database.fbs gpu_compatibility.json
```

**Comment by pkgoogle** [comment]
Hi @rubber815, there is probably a way ... @impjdi, can you please take a look? Thanks.

**Comment by ElonGreco** [comment]
Hi @impjdi , 
I would like to know how to submit GPU model information to the compatibility database in tflite? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @hooneecho 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/76

Let us know if you have any questions. Thanks.
