### ISSUE TITLE
tf.raw_ops.SparseConcat: Overflow bug 

### ISSUE THREAD

**Issue by vraebfdsb** [tensorflow/tensorflow#63377]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Python version

3.9

### Current behavior?

Under specific input, `tf.raw_ops.SparseConcat` encounters overflow bug.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

# Generate input data
indices1 = tf.constant([[0, 0], [1, 2]], dtype=tf.int64)
values1 = tf.constant([1, 2], dtype=tf.float32)
shape1 = tf.constant([3, 4], dtype=tf.int64)

indices2 = tf.constant([[0, 1], [2, 3]], dtype=tf.int64)
values2 = tf.constant([3, 4], dtype=tf.float32)
shape2 = tf.constant([-1, 4], dtype=tf.int64)  # Mutated shape with the negative bit set

# Invoke tf.raw_ops.SparseConcat
concatenated_sparse = tf.raw_ops.SparseConcat(
    indices=[indices1, indices2],
    values=[values1, values2],
    shapes=[shape1, shape2],
    concat_dim=0
)

print(concatenated_sparse)
```

### Relevant log output

```shell
tensorflow.python.framework.errors_impl.InternalError: {{function_node __wrapped__SparseConcat_N_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Encountered overflow from large input shape. [Op:SparseConcat] name:
```

**Comment by Venkat6871** [comment]
Hi **@nonenone12135** ,

The error message indicates an overflow from a large input shape. The issue lies in the shape2 variable. You have set the second dimension of shape2 to -1, which is a negative value. This negative value is interpreted as a mutable dimension, meaning that the size of that dimension can change. However, the SparseConcat operation requires all input shapes to be fully defined and non-mutable.

To fix this issue, you need to set the second dimension of shape2 to a positive value. In this case, since the second dimension represents the number of columns in the sparse matrix, you can set it to the same value as shape1, which is 4.
```
shape2 = tf.constant([3, 4], dtype=tf.int64)  # Fixed shape
```

I am providing [gist](https://colab.sandbox.google.com/gist/Venkat6871/8a92282d3a8ebcf24aec3d418b22d908/63377_2-15-nightly-v.ipynb) here for your reference.

Thank you!

**Comment by nonenone12135** [comment]
Thank you for your response. So, is this error message expected behavior rather than a bug?

**Comment by Venkat6871** [comment]
Hi **@vraebfdsb** ,
- Looks like it is working as intended, Meanwhile i will check with developer team on the same issue and will update the same.

Thank you!
