### ISSUE TITLE
0.12.0rc1 windows package for Python 3.5 (x64) does not include lib or include files

### ISSUE THREAD

**Issue by tkerwin** [tensorflow/tensorflow#6343]
I installed the 0.12.0rc1 tensorflow package for Python 3.5 (64 bit) on Windows 10.  

I started to try to add running trained models into an existing C++ software package, but the include and lib files specified by the documentation and found with `tensorflow.sysconfig.get_include()` and `.get_lib()` don't exist They return values:

```
In [5]: tensorflow.sysconfig.get_include()
Out[5]: 'e:\\python35\\lib\\site-packages\\tensorflow\\include'

In [6]: tensorflow.sysconfig.get_lib()
Out[6]: 'e:\\python35\\lib\\site-packages\\tensorflow\\core'
```

But these directories do not exist. I do not know if there is a problem with the package or the documentation.

**Comment by andydavis1** [comment]
@mrry may have seen this one before?

**Comment by mrry** [comment]
Yes, it's true that we don't include those files with the Windows build, because the DLL we generate isn't useful for building C++ applications (it doesn't export the necessary symbols).

Right now, for building C++ applications, your best bet is to follow the [CMake rules](https://github.com/tensorflow/tensorflow/blob/2477b50bf49d2cd6b8eac23071424c31dd05a05e/tensorflow/contrib/cmake/tf_tutorials.cmake) for building [`example_trainer.cc`](https://github.com/tensorflow/tensorflow/blob/2477b50bf49d2cd6b8eac23071424c31dd05a05e/tensorflow/cc/tutorials/example_trainer.cc); or using Bazel on Windows to build your application.

In the future, I expect we will distribute a separate `TensorFlow.dll` that exposes the [C API](https://github.com/tensorflow/tensorflow/blob/2477b50bf49d2cd6b8eac23071424c31dd05a05e/tensorflow/c/c_api.h), because it is relatively small and easy to link against from various different languages.
