### ISSUE TITLE
Support of gradient for TF.MOD

### ISSUE THREAD

**Issue by philipperemy** [tensorflow/tensorflow#6365]
Hello there,

When I include `tf.mod` in my Graph, I have this error:

`LookupError: No gradient defined for operation 'RNN/while/LSTM/Mod' (op type: Mod)`

Will it be handled in the future?

Thanks!

References: https://www.tensorflow.org/api_docs/python/math_ops/arithmetic_operators#mod
Tensorflow version: `0.12.0-rc1`

**Comment by philipperemy** [comment]
# Here we need to register the gradient for the mod operation
@ops.RegisterGradient("Mod")
def _mod_grad(op, grad):
    x, y = op.inputs
    gz = grad
    x_grad = gz
    y_grad = tf.reduce_mean(-(x // y) * gz, reduction_indices=[0], keep_dims=True)
    return x_grad, y_grad

**Comment by kleinma** [comment]
I would like to use `tf.mod` in my graph, as well, in order to define a loss function that minimizes the error in a variable that wraps (e.g. an angle with a range of [-pi,pi)). For example, if
`a1 = pi - eps` and `a2 = -pi + eps`,
then I would like
`a1 - a2 = -2 * eps`,
as opposed to
`a1 - a2 = -2 * eps + 2 * pi`.

In order to test the above solution, must I rebuild Tensorflow from source? I'm currently using 0.12.0rc1.
Thanks!

**Comment by yaroslavvb** [comment]
@kleinma For Python-only changes such as above, you need not rebuild TensorFlow from source

**Comment by aselle** [comment]
I'm not sure if mod in models is well-defined enough to know what the gradient should be in all cases. The angle case makes sense, but lots of uses of mod (binning, etc) are inherently discontinuous, certainly with integers. @girving, do you think we should provide a default mod gradient, or just let people override them appropriately for their application when they see this error?

**Comment by girving** [comment]
The gradient of mod is zero a.e., so it's TensorFlow gradient is zero everywhere.  We should definitely define a zero gradient (returning None).

**Comment by girving** [comment]
@aselle Unassigning myself since I'm on leave.

**Comment by michaelisard** [comment]
@sherrym would you take a look since @girving is out? It sounds as if the gradient should be 0 for mod as defined, but there would be some customers for an angular_mod with a different gradient.

**Comment by philipperemy** [comment]
Any news guys? @girving

**Comment by harpone** [comment]
Wait a sec guys! The gradient of tf.mod(x, y) w.r.t x is 1, except for x / y = integer where it is not defined... but since these points are a set of measure zero, the gradient should always be one (?). Gradient of int division (//) or floor is of course zero...

One plot says it all:
```
xvals = np.linspace(0, 10, 100)
yvals = xvals % 3.14
plt.plot(xvals, yvals)
```

Anyway, looking forward for the gradients!

**Comment by girving** [comment]
Ah, thought we were talking about integer mod, which has no gradient.  Yes, float mod has gradient 1 w.r.t. x a.e., and also an a.e. defined gradient w.r.t. y.

**Comment by harpone** [comment]
OK actually I just assumed tf.mod = % but didn't think about it further...

**Comment by philipperemy** [comment]
@harpone check this out: http://math.stackexchange.com/questions/1849280/derivative-of-remainder-function-wrt-denominator

**Comment by girving** [comment]
@yuefengz Can you take a look?

**Comment by yuefengz** [comment]
That stackexchange link is very helpful. I will implement the gradient function.

**Comment by philipperemy** [comment]
@yuefengz thanks!

**Comment by philipperemy** [comment]
@yuefengz any updates on your part?

**Comment by yuefengz** [comment]
@yuntatsai is working on a change, we will check it soon. Thanks for your patience.
