### ISSUE TITLE
Make VLOG minimum level can be updated via environment

### ISSUE THREAD

**Issue by leftnoteasy** [tensorflow/tensorflow#6366]
I found inside c++ core implementation there're lots of verbose messages like:
```
    VLOG(1) << "Direct session inter op parallelism threads: " << num_threads;
```
They will be very helpful for developer to understand what happens internally and troubleshoot problems.

However I found in implementation, it doesn't look like works without changing the code. (Credit to @yaroslavvb for the solution, see discussion thread: https://groups.google.com/a/tensorflow.org/forum/#!topic/discuss/D0_3jG5_XRQ)
```
    // TODO(jeff): Define a proper implementation of VLOG_IS_ON
    #define VLOG_IS_ON(lvl) ((lvl) <= 0)

    #define VLOG(lvl)      \
        if (VLOG_IS_ON(lvl)) \
          ::tensorflow::internal::LogMessage(__FILE__, __LINE__, tensorflow::INFO)
```

It will be very helpful if we can update the minimum lvl via passing environment.

**Comment by leftnoteasy** [comment]
And I'm interested to contribute to the feature, if folks think it is a valid feature requirement, I can start working on it.

Thanks!

**Comment by yaroslavvb** [comment]
vlog is kind of useful for debugging out of memory situations, right now the only way to get Tensor allocation/deallocation information is though vlog "__LOG_MEMORY__" messages on stdout

**Comment by aselle** [comment]
The probably reason that VLOG is disabled in code is that it would cause a significant runtime penalty. It might be placed in tight loops where comparing against a variable number would cause performance degradation. As it is now, VLOG blocks will basically be eliminated from compiled code and have no performance penalty. Replacing VLOG_IS_ON(lvl) definition with a call to getenv() would not be ok, because getenv() is relatively expensive. One would probably need to make some static data that is initialized by the environment variable once on translation unit initialization.

Perhaps @vrv or @andydavis1 has more insight?

**Comment by vrv** [comment]
https://github.com/tensorflow/tensorflow/pull/6375 is a reasonable solution that is being worked on: it checks the env var once statically on first use and just checks against the member variable on every call, which shouldn't be that expensive.

**Comment by leftnoteasy** [comment]
Thanks for reviews from @cwhipkey, @vrv, @aselle, very helpful!

For performance concerns from @aselle, I think @vrv's comment should solve the problem:
https://github.com/tensorflow/tensorflow/pull/6375#discussion-diff-93282773R130

I'm going to update the patch according to your feedbacks.

**Comment by aselle** [comment]
Sounds good.... marking as contributions welcome since it is being worked on.

**Comment by leftnoteasy** [comment]
#6375 is merged, closing this one, thanks everyone for your feedbacks!
