### ISSUE TITLE
AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_frozen_graph'?

### ISSUE THREAD

**Issue by selvakarna** [tensorflow/tensorflow#63704]
#### Questions: 
I am try convert Frozen Graph.pb tensorflow model into TFLite light weigth model, I am getting following error?

#### Error
AttributeError: type object 'TFLiteConverterV2' has no attribute 'from_frozen_graph'

#### My Code:
import tensorflow as tf

frozen_graph_path="\model\md\saved_model.pb"
pbtxt_path="\model\md\saved_model.pbtxt"

input_shape=(1,224,224,3)
with tf.io.gfile.GFile(frozen_graph_path,"rb") as f:
    graph_def=tf.compat.v1.GraphDef()
    graph_def.ParseFromString(f.read())
    print("The model graph loaded............")
converter=tf.lite.TFLiteConverter.from_frozen_graph(graph_def,input_arrays= ['image_tensor'],output_arrays=['Preprocessor/map/while/Identity'])

**Comment by sushreebarsa** [comment]
@selvakarna `AttributeError: type object 'TFLiteConverterV2' has no attribute` '`from_frozen_graph`' error because the from_frozen_graph method is not available in TensorFlow 2.x's TFLiteConverterV2 class.
If your model is a frozen graph saved as a .pb file, you'll need to use the TensorFlow 1.x compatibility layer (tf.compat.v1) to access the `from_frozen_graph` method.
Could you please let us know which TF version you have used?
Thank you!

**Comment by selvakarna** [comment]
Thank you @sushreebarsa https://github.com/sushreebarsa

**Comment by sushreebarsa** [comment]
@selvakarna Could you use tf.saved_model.load to load the frozen graph as a SavedModel and then convert it to TFLite?
Please let us know the outcome?
Thank you!
