### ISSUE TITLE
Error: numpy.core._exceptions._ArrayMemoryError: Unable to allocate 115. TiB for an array with shape (3983360, 3983360) and data type float64

### ISSUE THREAD

**Issue by NOORLEICESTER** [tensorflow/tensorflow#63761]
I am encountering an error: 'numpy.core._exceptions._ArrayMemoryError: Unable to allocate 115 TiB for an array with shape (3983360, 3983360) and data type float64' when I use HPC. However, I do not encounter any error when I use my personal laptop for the same code.

**Comment by sushreebarsa** [comment]
@NOORLEICESTER `numpy.core._exceptions._ArrayMemoryError` on the HPC system but not on your laptop indicates a limitation in the available memory on the HPC cluster compared to your laptop. HPC environments often prioritize memory efficiency, switching the data type from float64 to float32 can significantly reduce memory usage.

In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!

**Comment by sushreebarsa** [comment]
@NOORLEICESTER In order to expedite the trouble-shooting process, please provide a code snippet to reproduce the issue reported here. Thank you!
