### ISSUE TITLE
TensorFlow 2.16 / Keras 3 have undocumented breaking API changes

### ISSUE THREAD

**Issue by pandrey-fr** [tensorflow/tensorflow#63792]
### Issue type

Documentation Feature Request

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.16.1

### Custom code

No

### Current behavior?

With the (documented) switch to Keras 3, TensorFlow 2.16 has introduced undocumented API-breaking changes that derogate to SemVer and results in unexpected code maintenance costs for depending projects.

While I understand the interest of switching to Keras 3 (and acknowledge the possibility to keep using Keras 2 as backend, albeit non-trivial to impose on end-users of a third-party solution that uses TensorFlow as dependency), I would have expected some kind of effort on documenting parts of the API that changed due to the switch. [This Keras issue](https://github.com/keras-team/keras/issues/18467) and [this guide](https://keras.io/guides/migrating_to_keras_3/#tensorflow-variables-tracking) are presented as listing breaking changes, but seem not to be covering everything that changed, especially when calling keras from TensorFlow rather than as a primary endpoint for setting up models (agnostic to the computation backend).

As I put effort in updating custom code that calls TensorFlow / Keras code, I notably noticed that:
- `tf.keras.Model.weights` (and its variants) as well as `tf.keras.optimizers.Optimizer.variables` no longer return a list of `tf.Variable` instances, but instead return a list of `tf.keras.Variable` that themselves wrap `tf.Variable` instances.
- Some losses were dropped / renamed, _e.g._ `tf.keras.losses.deserialize("mse")` no longer works, but was to the best of my knowledge never reported to be deprecated in previous versions.
- `tf.keras.optimizers.Optimizer.variables()` has been removed in favor of `tf.keras.optimizers.Optimizer.variables`.

These changes can be adjusted for, but require a lot of `if hasattr(tf.keras, "version") and tf.keras.version().startswith("3"):` branching to keep supporting not-so-old versions while adding support for newer TF versions, and, most importantly, require some tedious experiments to find out what has changed and how. As such, I categorize his issue as "Documentation Feature Request" as I obviously do not expect changes to be rolled back, but believe that it would be a sensible gesture towards the community to publish a clearer and more exhaustive guide as to what has changed with the introduction of Keras 3, and how to accommodate third-party code that does not want to impose on end-users the choice of a single TF version.

### Standalone code to reproduce the issue

As a single example of what I am talking about:

This works with TensorFlow 2.15:

```python
import tensorflow as tf

optim = tf.keras.Adagrad()
grads = [tf.zeros((32, 1)), tf.zeros((1,))]
optim.build([tf.Variable(tf.zeros_like(g), name=f"{i}") for i, g in enumerate(grads)])
state = {v.name: v.value() for v in optim.variables()}
assert len(state) == 2
```

But it fails for numerous reasons in TensorFlow 2.16.1 (with Keras 3 backend):
- `state = {v.name: v.value() for v in optim.variables()}` should be replaced with `state = {v.path: v.value.value() for v in optim.variables}`...
- ... and in fact this will not work because the names have not been propagated and all accumulator variables have the shame name/path, hence to put them in a dict I have to deterministically set names, _e.g._ based on indices, which drops some information.

**Comment by Tanishq-JM** [comment]
It looks like you're encountering issues related to changes in the TensorFlow/Keras API, particularly with the switch to Keras 3 in TensorFlow 2.16. The changes you've highlighted, such as the return types of `tf.keras.Model.weights` and `tf.keras.optimizers.Optimizer.variables`, as well as the removal of `tf.keras.optimizers.Optimizer.variables()`, can indeed require adjustments to existing code.

Here are some suggestions to address these changes:

1. **Handling return types:** Since `tf.keras.Variable` wraps `tf.Variable`, you may need to modify your code to work with this change. For example, instead of directly accessing attributes of `tf.Variable`, you may need to use the corresponding methods or properties of `tf.keras.Variable`.

2. **Renamed losses:** For losses that have been dropped or renamed, you'll need to update your code to use the new names or alternatives. Check the TensorFlow documentation or release notes for information on the new names or replacements for the dropped losses.

3. **Updated optimizer variables:** With the removal of `tf.keras.optimizers.Optimizer.variables()`, you'll need to find an alternative way to access the optimizer's variables. One approach could be to maintain a separate list or dictionary of the optimizer's variables in your code.

4. **Documentation and guidance:** It's important to consult the TensorFlow documentation and release notes for guidance on how to update your code for these API changes. Additionally, forums and community discussions can be helpful in understanding the changes and finding solutions.

5. **Conditional branching:** As you mentioned, you may need to use conditional branching (`if` statements) to handle different versions of TensorFlow/Keras in your code. This can help you maintain compatibility with older versions while adding support for newer versions.

It's unfortunate that these changes have resulted in unexpected maintenance costs for your project. Providing feedback to the TensorFlow/Keras development team about the documentation gaps and difficulties in adapting to the changes could help improve the situation for the community.

**Comment by pandrey-fr** [comment]
Sorry, but this is as unhelpful an answer as it gets. Points 1, 2, 4 and 5 are merely repetitions of my issue description, and your conclusion literally prompts me to do what I just did by opening this issue.

As for point 3, the all point of my opening this issue is to point out that there is a lack of documentation regarding these changes, which means everyone has to spend time figuring out what is broken or not, and how to adjust to API changes. I managed to do it in my specific case with a few hours' effort, but the parts I use in my software only cover a small part of the entire TensorFlow/Keras API, hence I expect others will not only encounter the same issues as me, but probably more undocumented issues.

Hence my call for a broader migration guide, that would help developers adjust their code to the recent changes with limited effort.

**Comment by mihaimaruseac** [comment]
(it's an answer generated by an LLM, just spam)

**Comment by mihaimaruseac** [comment]
The LLM generated spam comment has been removed silently.

But for TF 2.16, see https://github.com/tensorflow/tensorflow/issues/69586 for a history of how things got so back

**Comment by pandrey-fr** [comment]
@mihaimaruseac Thank you for your reply. The discussion you linked is mostly about a distinct (albeit relevant) issue, but the details about the RC process having been rushed is (sadly) interesting.

I am struck by your comment stating that
> Everyone that cared about full support of TF is no longer in the team.

Does it mean that we should expect TensorFlow to be progressively dropped, and/or to become a backend project for Keras? If so, this is sad to learn. TensorFlow has come a long way since the version 2 beta, and although there have been caveats and some changes along that path, as far as I can tell it has mostly been stable, notably after version 2.5.

Is there any documentation, or do you have any shareable insight, as to the planned future of TensorFlow and/or its articulation with other libraries in the ecosystem (notably Keras, Jax and Flax)?

**Comment by mihaimaruseac** [comment]
I cannot say much, but Jax is the ecosystem of choice now. With Keras 3 you can easily switch between Jax and PyTorch as backend.

**Comment by pandrey-fr** [comment]
OK, thank you for the insight.
