### ISSUE TITLE
Discussion Online Expanding the Number of Distributed Training Workers 

### ISSUE THREAD

**Issue by guoying1030** [tensorflow/tensorflow#6381]
Tensorflow distributed training adds a new feature:
When we use the distributed tensorflow training task, if the number of workers is too small to start, but not very good convergence. . Especially when used in conjunction with k8s, then tensorflow should support the online expansion of the current number of workers training tasks.

My idea is: Use python interface, notify the ps server, the new worker task_index and worker addr. such as:

We pre-start the cluster as follows:
# On ps0.example.com:
$ Python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
     --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222 \
     --job_name = ps --task_index = 0
# On ps1.example.com:
$ Python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
     --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222 \
     --job_name = ps --task_index = 1
# On worker0.example.com:
$ Python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
     --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222 \
     --job_name = worker --task_index = 0
# On worker1.example.com:
$ Python trainer.py \
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222 \
     --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222 \
     --job_name = worker --task_index = 1

We started the original two ps server ,,, two workers. .
Now let's add a third worker

Import tensorflow as tf
Def main (_):
    With tf.Session ('grpc: //ps0.example.com:2222') as sess:
        Sess.add_onlineworker (2, 'worker2.example.com: 2222')

    With tf.Session ('grpc: //ps1.example.com:2222') as sess:
        Sess.add_onlineworker (2, 'worker2.example.com: 2222')

If name == "main":
    Tf.app.run ()

Just run this python script, and then start worker2.
Worker2 startup script:
$ Python trainer.py
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222
    --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222,
     --worker2.example.com:2222 --job_name = worker --task_index = 2

At this point you should be able to see the worker2 has started training.

If ps0 or ps1 restart, it should be added worker2:
$ Python trainer.py
     --ps_hosts = ps0.example.com: 2222, ps1.example.com: 2222
    --worker_hosts = worker0.example.com: 2222, worker1.example.com: 2222,
     --worker2.example.com:2222 --job_name = ps --task_index = 0

The design idea is as follows:
1. Increase the number of workers online, only need to notify all of the ps server can be.
2. Through the use of the python session interface, you can connect a different ps server, and then send an increase in worker instructions can be given to them.

I've done this at https://github.com/ipdcode/tensorflow.

Welcome to the official google and we discuss to see if there is a need to increase this feature.

**Comment by aselle** [comment]
@mrry, could you comment on this proposal and see if we want to accept the PR.

**Comment by dancing80s** [comment]
I was interested in your idea.
I tried to build  source code of "ipdcode/tensorflow", but I could not build it.
`
Virtual Status AddOnlineWorker(CallOptions* call_options,...
`
It does not seem to be possible to build because there is no implementation of this function.
I wonder if any corrections are not enough...

**Comment by mrry** [comment]
We've discussed this problem within the team, and think we've come up with a design that meets our internal requirements. The basic idea is that we'd move `tf.train.ClusterSpec` from being an argument of `tf.train.Server` to being a configuration option when you create a `tf.Session`. This would let you build clusters on an ad hoc basis, and would remove limitations like requiring all PS tasks to know the identities of all workers at startup time.

@saeta is going to be working on this, so I've assigned the issue to him. He is currently figuring out the details, and should have more to share soon.

**Comment by dancing80s** [comment]
Thank you for sharing information.
I would like to be able to efficiently allocate online streaming data to Tensorflow machine nodes.
I would like to dynamically perform real-time processing in response to changes in streaming for models that want to predict and learn simultaneously, such as LSTM or DQN.
I understand that the current Tensorflow needs to pre-allocate machines in advance.
I expect to implement such online distributed processing.

**Comment by saeta** [comment]
Hi @dancing80s . Currently TensorFlow assumes a cluster is a fixed size and shape. I'm working on a change that does the following:

 1. Worker nodes can boot up without needing to know the whole cluster shape.
 2. A cluster shape (i.e. list of nodes) is tied to a session (instead of being process-wide).
 3. A client can specify the cluster shape at session creation time.

So what this would look like is a tensorflow worker binary can be launched on all nodes in the cluster (e.g. [grpc_tensorflow_server.cc](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_tensorflow_server.cc), just with no required command-line arguments). Then, a client (e.g. python script) can come along and decide to use a subset of the nodes, and create a session referencing that subset, run its computation on it, and simultaneously, another client can be running its own computation on a separate subset in a different session.

One thing to note: my work will not make it possible to change the cluster shape within a session. You'll have to manage that client side by creating new sessions under the hood, and copying data (e.g. training parameters) across.

Hope that helps!

**Comment by saeta** [comment]
Oh, if you need online inference (i.e. predict), I highly recommend you check out [TensorFlow Serving](https://github.com/tensorflow/serving). The team that's put this together has solved a number of non-intuitive challenges you might encounter when running inference in an online environment. Their systems absolutely support updating the models while serving requests, and have tooling to do so.

**Comment by girving** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
