### ISSUE TITLE
Tensorflow fault tolerance

### ISSUE THREAD

**Issue by chaitanya2692** [tensorflow/tensorflow#6416]
Hello,

I have been using the following simple code to learn about the behavior of distributed tensorflow (which claims to be fault tolerant):-

  ```
import tensorflow as tf
cluster = tf.train.ClusterSpec({"local": ["localhost:2222", "localhost:2223","localhost:2224", "localhost:2225"]})
x = tf.constant(2)
with tf.device("/job:local/task:1"):
    y1 = x + 300
 with tf.device("/job:local/task:2"):
    y2 = x**2
with tf.device("/job:local/task:3"):
    y3 = 5*x
with tf.device("/job:local/task:0"):
    y0 = x - 66
    y = y0 + y1 + y2 + y3

model = tf.initialize_all_variables()

with tf.Session("grpc://localhost:2222") as sess:
    sess.run(model)
    print(sess.run(y0))
    print('\n')
    print(sess.run(y1))
    print('\n')
    print(sess.run(y2))
    print('\n')
    print(sess.run(y3))
    print('\n')
    result = sess.run(y)
    print(result)
```

I create workers by running a separate program as given below:-

```
#get task number from command line
import sys
task_number = int(sys.argv[1])

import tensorflow as tf

cluster = tf.train.ClusterSpec({"local": ["localhost:2222", "localhost:2223", "localhost:2224", "localhost:2225"]})
server = tf.train.Server(cluster, job_name="local", task_index=task_number)

print("Starting server #{}".format(task_number))

server.start()
server.join()

```
But when I stop one of the servers(machines), the whole program stops functioning instead of assigning the job to another machine. Is tensorflow fault tolerant when a machine goes down?

**Comment by yaroslavvb** [comment]
No, TensorFlow doesn't reschedule job when machine goes down, that's job of cluster manager.

You could specify your cluster using hostnames rather than IP numbers like this
`cluster = tf.train.ClusterSpec({"local": ["machine1:2222", "machine2:2223"]})
`
Then when one machine1 goes down, it's job of cluster manager to spin up another instance, and update DNS records so that `machine1` points to that machine.

With current distributed implementation, resetting a connection will terminate your `session.run` call (like in https://github.com/tensorflow/tensorflow/issues/6319 which was due to AWS resetting idle connections), so you'll need to add extra logic to restart your `session.run`

**Comment by mrry** [comment]
+1 to what @yaroslavvb said above. The [`tf.train.MonitoredSession`](https://www.tensorflow.org/api_docs/python/train/distributed_execution#MonitoredSession) class contains utilities that help with recovery after a failure.

In the current implementation, after a `tf.Session.run()` call fails due to a worker failure, the `tf.Session` object is no longer usable. The `tf.train.MonitoredSession` takes care of re-creating a new session and running code to restore from a checkpoint, if necessary.

**Comment by yaroslavvb** [comment]
@mrry what if `.run` calls due to connection getting reset in the middle of `run` call like in https://github.com/tensorflow/tensorflow/issues/6319, can I still use the same Session object?

**Comment by mrry** [comment]
The session may be in an undefined state at that point, so YMMV if you try to keep using it. The various wrapper libraries will re-create the session in those cases.

**Comment by chaitanya2692** [comment]
I have written a very simple program but couldn't get the desired output. I have also [posted an issue](https://github.com/tensorflow/tensorflow/issues/6593) on github.

Could you please let me know if I am going the right way or atleast redirect me towards a tutorial to better understand the usage of monitored session?

**Comment by peihe** [comment]
Using DNS isn't ideal, given ports might be taken after a reboot or after failed workers are assigned to new machines. Plus, DNS introduced another dependency.

I am wondering has anyone tried to use grpc name resolvers with services such as zookeeper?
