### ISSUE TITLE
TensorflowLite for Windows on Arm

### ISSUE THREAD

**Issue by everton1984** [tensorflow/tensorflow#64282]
I have been working on making Tensorflow Lite available for the Windows on Arm platform. My current patch can be found here https://github.com/everton1984/tensorflow.git on the branch `woa_enablement2`. I have written a wiki on how to compile that can be accessed here https://linaro.atlassian.net/wiki/spaces/WOAR/pages/29206609925/Tensorflow+Lite. All that is left is getting the XNNPACK patch into mainstream and I am currently discussing it with the maintaners. 

I am wondering if there is the possibility and interest in supporting a new platform, like Windows on Arm and if so if that patch is enough or if there is something else that needs to be tackled.

**Comment by pkgoogle** [comment]
Hi @terryheo, I believe you would know this best, can you please take a look?

**Comment by everton1984** [comment]
Hi @terryheo, sorry to bother but just wanted to check if you had an opinion on this.

**Comment by gaikwadrahul8** [comment]
Hi, @everton1984 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/72

Let us know if you have any questions. Thanks.

**Comment by CaptainDario** [comment]
@everton1984, this is a great effort from you!
I tried compiling tf lite for Windows on ARM the last few days without success.

Would you mind sharing your binary?
