### ISSUE TITLE
XNNPACK is not supported in Linux armv7-a when compile source code

### ISSUE THREAD

**Issue by candcv** [tensorflow/tensorflow#64358]
Hi, I followed the instructions in the website:https://tensorflow.google.cn/lite/guide/build_cmake_arm to cross compile and find a question XNNPACK is not supported in Linux armv7-a when compile source code. 

```
curl -LO https://storage.googleapis.com/mirror.tensorflow.org/developer.arm.com/media/Files/downloads/gnu-a/8.3-2019.03/binrel/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz
mkdir -p ${HOME}/toolchains
tar xvf gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf.tar.xz -C ${HOME}/toolchains
```

```
ARMCC_FLAGS="-march=armv7-a -mfpu=neon-vfpv4 -funsafe-math-optimizations -mfp16-format=ieee"
ARMCC_PREFIX=${HOME}/toolchains/gcc-arm-8.3-2019.03-x86_64-arm-linux-gnueabihf/bin/arm-linux-gnueabihf-
cmake -DCMAKE_C_COMPILER=${ARMCC_PREFIX}gcc \
  -DCMAKE_CXX_COMPILER=${ARMCC_PREFIX}g++ \
  -DCMAKE_C_FLAGS="${ARMCC_FLAGS}" \
  -DCMAKE_CXX_FLAGS="${ARMCC_FLAGS}" \
  -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
  -DTFLITE_ENABLE_XNNPACK=ON  \
  -DCMAKE_SYSTEM_NAME=Linux \
  -DCMAKE_SYSTEM_PROCESSOR=armv7 \
  ../tensorflow/lite/
make -j8
```
**part error log:**
`/tensorflow/build_arm/xnnpack/src/qs8-qc8w-igemm/gen/qs8-qc8w-igemm-2x2c4-minmax-fp32-armsimd32.c:80:15: error: unknown type name ‘int16x2_t’
         const int16x2_t va1c02 = __sxtb16(va1);
`

**Comment by sushreebarsa** [comment]
@candcv You're right that XNNPACK is not officially supported for Linux armv7-a architecture when compiling the source code. This is because armv7-a processors generally lack hardware acceleration features that XNNPACK leverages for performance optimization. You can refer to the XNNPACK documentation [here](https://github.com/google/XNNPACK) for pre-built wheels if available.
Thank you!

**Comment by candcv** [comment]
@sushreebarsa Thank you for your help.
The old Version XNNPACK from https://github.com/google/XNNPACK/tree/test_282285243 can support ARMv7 (with NEON) on Android and **Linux**,but the new version only provide script ARMv7 (with NEON) on Android,not Linux. I think the problem is related to this.

**Comment by sushreebarsa** [comment]
@candcv You are right! It is currently not supported. You can download the specific commit (`test_282285243`) from XNNPACK's GitHub repository. This version should work with ARMv7 NEON on Linux. Please use this with caution because it is not the stable version. It might have unexpected behavior.
Thank you!
