### ISSUE TITLE
Change draw_bounding_box() label input to allow different number of inter-batch boxes.

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#6474]
This is a question or feature request regarding the following function
`tf.image.draw_bounding_boxes(images, boxes, name=None)`
### Current
The required bounding-box format is as follows:
`[batch, num_bounding_boxes, 4]`, in which the labels are in `[y_min, x_min, y_max, x_max]` format.
If i understand correctly, this assumes that every image has the same number of bounding boxes.
### Suggestion
Doesn't it make a lot more sense to change the input format to the following:
`[num_labels, 5]` in the following format `[id, y_min, x_min, y_max, x_max]` where id corresponds to the image in the batch.

**Comment by aselle** [comment]
@danmane, please consider this feature request.

**Comment by bhack** [comment]
Can we add also color and text to the interface?

**Comment by dandelionmane** [comment]
I don't own the tf.image module and don't intend to work on this. Going to mark it contributions welcome.

**Comment by aselle** [comment]
@TimZaman, I believe it is this way so that ops can be created to produce tensors in a deterministic way. If a bounding box is unused it can be given dummy values. Most ops in TensorFlow work better with direct indexable dense formats rather than the id-based sparse format you suggest. So I am closing for now.
