### ISSUE TITLE
JUCE LNK2001 - LNK2019: UNRESOLVED EXTERNAL SYMBOL

### ISSUE THREAD

**Issue by Ikerlandarech** [tensorflow/tensorflow#64818]
Hey there and thank you for reading this.

I've been trying to work on a VST for my final thesis project which consists on timbre transfer voice to instruments, I've been using JUCE and all source files are loaded from the Projuicer, the problem I'm facing is those Linker Errors that I think have to do with reading/accessing the Tensorflow files. I have no idea on how to solve it since I tried changing all the "includes" so that filepath were accessible and also tried importing all TF into the Projuicer but then it crashes.
If anyone can help with this I would really appreciate some help, thank u so very much in advance and have a beautiful day whoever is reading this :)

![image](https://github.com/tensorflow/tensorflow/assets/91797318/aeb1ab03-e867-4e20-9210-aaf554f4d1cb)

**Comment by LakshmiKalaKadali** [comment]
Hi @Ikerlandarech,

Upon inspecting the screenshot, these errors indicate that the code is referencing functions or variables that are not defined or available in the linked libraries.  Check library versions for compatibility, make sure necessary headers are included.  In order to reproduce the issue, please fill the [template](https://github.com/tensorflow/tensorflow/issues/new?assignees=&labels=&projects=&template=tensorflow_issue_template.yaml) and elaborate more the issue and the environment which you are working. 

Thank You
