### ISSUE TITLE
TensorFlow build error under windows

### ISSUE THREAD

**Issue by jimwang118** [tensorflow/tensorflow#64969]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.10.0

### Custom code

Yes

### OS platform and distribution

windows 10

### Python version

3.11

### Bazel version

bazel 5.2.0

### CUDA/cuDNN version

NO

### Current behavior?

When I compile xxx under Windows, the following error appears.
[675 / 976] Compiling snappy.cc; 0s local ... (5 actions, 4 running)
ERROR: F:/vcpkg/buildtrees/tensorflow/.bzl/3tyt3lpr/external/llvm-project/mlir/BUILD.bazel:6592:10: Linking external/llvm-project/mlir/mlir-tblgen.exe failed: (Exit 1201): link.exe failed: error executing command 

### Standalone code to reproduce the issue

```shell
Reproduction steps：
git clone https://github.com/microsoft/vcpkg.git
cd vcpkg
open powershell
.\bootstrap-vcpkg.bat
./vcpkg install tensorflow
```

### Relevant log output
[build-x64-windows-dbg-err.log](https://github.com/tensorflow/tensorflow/files/14847808/build-x64-windows-dbg-err.log)

_No response_

**Comment by NeoZhangJianyu** [comment]
@jimwang118 
Hi,
  This issue is about old Tensorflow: 2.10.0.
  Could you confirm the version?

  Have you install LLVM? please refer to: https://www.tensorflow.org/install/source_windows#install_llvm
  I suggest to follow all steps in guide: https://www.tensorflow.org/install/source_windows

  If you really work with 2.10.0, I suggest to try same case with latest Tensorflow.
  Because old TF (2.10.0) is hard to maintain, so all bugs will be fixed in latest version, instead of based on 2.10.0.

  Thank you!

**Comment by jimwang118** [comment]
Compile the latest version and use the following command, but the same problem occurs.
`'F:/vcpkg/installed/x64-windows/tools/bazel' --output_user_root='F:/vcpkg/buildtrees/tensorflow/.bzl' --max_idle_secs=1 build --verbose_failures --jobs=9    --python_path='F:/vcpkg/downloads/tools/msys2/70baefe917a26e68/mingw64/bin/python3.exe' --define=no_tensorflow_py_deps=true ///tensorflow:tensorflow.dll ///tensorflow:install_headers`

Is llvm necessary to compile tensorflow?

**Comment by jimwang118** [comment]
@NeoZhangJianyu I installed llvm17.0.2 locally, but the following problem still occurred during compilation.
`ERROR: F:/vcpkg/buildtrees/tensorflow/.bzl/3tyt3lpr/external/llvm-project/llvm/BUILD.bazel:622:10: Linking external/llvm-project/llvm/llvm-min-tblgen.exe [for tool] failed: (Exit 1201): link.exe failed: error executing command (from target @llvm-project//llvm:llvm-min-tblgen) `
[build-x64-windows-dbg-err.log](https://github.com/tensorflow/tensorflow/files/14900156/build-x64-windows-dbg-err.log)

**Comment by NeoZhangJianyu** [comment]
2.10 is last version to support native windows.
newer versions are only supported in WSL2.

If you try latest version, please build it in WSL2 in window, instead of native.
If you want to use 2.10, I suggest to install the binary directly.

If you still try with 2.10, please follow the steps in guide: https://www.tensorflow.org/install/source_windows.
In the log, looks like the build cmd is not same as the guide.

**Comment by Venkat6871** [comment]
Hi **@jimwang118** ,
- Sorry for the delay, Ensure that all necessary dependencies for tensorFlow are installed and properly configured on your system. This includes libraries like CUDA, cuDNN, Bazel, and others.
- Make sure your environment variables are correctly set, especially those related to compiler paths, library paths, and Bazel configuration.
- Could you please go through this [documentation](https://www.tensorflow.org/install/source_windows) once. 
- Note: Starting in TF 2.11, CUDA build is not supported for Windows. For using TensorFlow GPU on Windows, you will need to build/install TensorFlow in WSL2 or use tensorflow-cpu with TensorFlow-DirectML-Plugin.

Thank you!
