### ISSUE TITLE
`floating point exception` in `tf.nn.max_pool3d` when value of `ksize` is too large.

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65120]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`floating point exception`  in `tf.nn.max_pool3d` when value of `ksize` is too large, which will cause a crash. This crash occurs in the CPU execution environment.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/1S9D9zdhknu9ReoPahd0_kw2OEuRxLAvB?usp=sharing
```

### Relevant log output

```shell
Floating point exception (core dumped)
```

**Comment by tilakrayal** [comment]
@xl1043237213,
It's not being killed because of TF. You are literally allocating so much memory that the OS is killing the process. It seems like you're giving large negative value for multiple arguments to the function. so due to Integer overflow to buffer overflow or due to insufficient memory (RAM), code is crashing or the process getting killed and I was able to replicate the issue on Google colab. Could you please specify the usecase where you are trying with the large ksize.

input:	A 5-D Tensor of the format specified by data_format.
ksize:	An int or list of ints that has length 1, 3 or 5. The size of the window for each dimension of the input tensor.

Thank you!

**Comment by xl1043237213** [comment]
Thanks for your response. : )
I found the problem with a self-designed fuzzy testing tool, and have not yet found a relevant application scenario that requires setting ksize to such a large value. However, when the value of ksize is accessible to the user, packed in the model, it can cause the program to hang or even crash.

**Comment by tilakrayal** [comment]
I was able to reproduce the issue on tensorflow [v2.15](https://colab.research.google.com/gist/tilakrayal/37b09ac521f769a066af3508d89fe44d/untitled1857.ipynb) and v2.16. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/7b52e2e87495521a3ac7b0a5b30919f9/untitled1858.ipynb).

**Comment by sonali-kumari1** [comment]
Hi @xl1043237213,

Thanks for reporting this issue.
You can use keras.ops.max_pool [API](https://keras.io/api/ops/nn/#maxpool-function) instead of tf.nn.max_pool3d.
And you are giving ksize as a single integer but it should be a list or tuple of 5 elements corresponding to 3D input tensor. Attaching [gist](https://colab.sandbox.google.com/gist/sonali-kumari1/add994a377ce24450a3a7e4b5a11a22f/floating-point-exception-in-tf-nn-max_pool3d-when-value-of-ksize-is-too-large.ipynb) for your reference.
