### ISSUE TITLE
Model.add_loss is not documented

### ISSUE THREAD

**Issue by piyushsrv** [tensorflow/tensorflow#65160]
### Issue type

Documentation Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

2.16.1

### Custom code

Yes

### Current behavior?

In the documentation of `tf.keras.Model` as available at https://www.tensorflow.org/api_docs/python/tf/keras/Model, the method `Model.add_loss` has been used in the example code for the method `compute_loss`. However, the method `Model.add_loss` itself has not been documented on this page.

 The `keras` documentation provides some documentation for `Layer.add_loss`, but I couldn't find any documentation even there for `Model.add_loss`.

### Standalone code to reproduce the issue

```shell
This is a missing documentation issue, so there is no code.
```

**Comment by sushreebarsa** [comment]
@piyushsrv The Model page doesn't explicitly mention add_loss, you can still use it on a Model object because it inherits from Layer. Model inherits from Layer in Keras. This means it gets all the methods and properties of the Layer by default. You can refer to the Layer.add_loss documentation for details on how it works: https://www.tensorflow.org/api_docs/python/tf/keras/losses.
Thank you!
