### ISSUE TITLE
tf.sequence_mask with int64 does not work

### ISSUE THREAD

**Issue by albertz** [tensorflow/tensorflow#6518]
Given some tensor `x` with shape (batch,time) and `seq_lens` of shape (batch,) of dtype `int64`, I wanted to use this code:
```
    mask = tf.sequence_mask(seq_lens, maxlen=tf.shape(x)[1])
```

This fails with `TypeError: Input 'y' of 'Less' Op has type int64 that does not match type int32 of argument 'x'.` in `gen_math_ops._range(0, maxlen, 1) < expand_dims(lengths, 1)`.

If I add `seq_lens = tf.cast(seq_lens, "int32")` before, then it works.

Casting `tf.shape(x)[1]` to `int64` does not work (because of `gen_math_ops._range(0, maxlen, 1)` which treats `0` and `1` as `int32` and then raises `TypeError: Input 'limit' of 'Range' Op has type int64 that does not match type int32 of argument 'start'`).

**Comment by aselle** [comment]
This is an unfortunate known limitation, and we would welcome a patch that fixes it.

**Comment by DjangoPeng** [comment]
@aselle I'm working on it.

**Comment by DjangoPeng** [comment]
@albertz Could you give me a test input and right output sample?

**Comment by jungle-cat** [comment]
@aselle Could we just convert seq_lens to int32 if its dtype is int64 in tf.sequence_mask implementation?

However since the error occurs due to `less` operation in `gen_math_ops._range(0, maxlen, 1) < expand_dims(lengths, 1)` where the left operand is int32 and the right operand is int64. Maybe we could add `type promotion` mechanisms in these operations.

If it's ok by converting seq_lens to int32 in tf.sequence_mask, I can add it as a patch. Wellcome your advice -:)

**Comment by gunan** [comment]
@DjangoPeng are you still working on this?
@aselle has this been fixed yet?

**Comment by yongtang** [comment]
I think this issue has been fixed in the latest version.

**Comment by DjangoPeng** [comment]
@gunan Sorry for this. I'm leaving for some company things. Now, I would return to community work.
