### ISSUE TITLE
Upgrading TFLite package (from TF 2.8 to Play Services)

### ISSUE THREAD

**Issue by tgpsantos** [tensorflow/tensorflow#65232]
**System information**
- TensorFlow Lite in Play Services SDK version (found in `build.gradle`):
```
        implementation 'com.google.android.gms:play-services-tflite-java:16.1.0'
        implementation 'com.google.android.gms:play-services-tflite-gpu:16.1.0'
```

Hi guys,

I'm currently upgrading our tensorflow-lite package from 2.8 to the new Play Services bundle. However, I've come across into a significantly different API compared to what we have right now and some of the documentation.

Here are my doubts
- is version from Play services actually the most up-to-date? last update to tflite-java 16.1.0 seems to be from [may 2023](https://maven.google.com/web/index.html?q=tflite#com.google.android.gms:play-services-tflite-java:16.1.0)
- what's the reason for `[com.google.android](com.google.android.gms:play-services-tflite-java)` library and distribution to be different from `org.tensorflow:tensorflow-lite` ?
- if play services is the most up to date, there seems to be some inconsistencies in the documentation? For instance, I can't find the [Interpreter](https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/Interpreter) anymore now. It seems to have been replaced by InterpreterApi, but it's unclear why we still see both in documentation
- If `Interpreter` was actually replaced by `InterpreterApi`, what's the new way to get the `getSignatureKeys` from this Play Services library?
- I was using Interpreter before so it seems natural to update everything for InterpreterApi, but is it advised against in any way?
- Is `[CompatList](https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/gpu/CompatibilityList)` deprecated / no need to call `getBestOptionsForThisDevice` anymore?
- `compatList.isDelegateSupportedOnThisDevice` replaced by `TfLiteGpu.isGpuDelegateAvailable` ?

Thanks for the help!

**Comment by pkgoogle** [comment]
Hi @tgpsantos, I don't have all the answers but here are some of my thoughts:

> If Interpreter was actually replaced by InterpreterApi, what's the new way to get the getSignatureKeys from this Play Services library?

I don't believe there is a new way... is there something you can't do with the new InterpreterApi, that you needed that method previously that you can't do now?

> I was using Interpreter before so it seems natural to update everything for InterpreterApi, but is it advised against in any way?

I would update everything and that is expected. Let us know if anything goes wrong.

Hi @arfaian, can you please take a look. Thanks.

**Comment by fergushenderson** [comment]
Hi,

> is version from Play services actually the most up-to-date? last update to tflite-java 16.1.0 seems to be from [may 2023](https://maven.google.com/web/index.html?q=tflite#com.google.android.gms:play-services-tflite-java:16.1.0)

The most recent release for Play services is a Beta release from 12/18/2023:

https://maven.google.com/web/index.html?q=tflite#com.google.android.gms:play-services-tflite-java:16.2.0-beta02

That release is Beta release because it includes new functionality, specifically the C API in addition to the Java API; the new functionality is still in Beta. If you're only using the Java API, don't worry about "beta" in the name -- only the C API part is Beta. (The "-java" naming is a little unfortunate, now, but it was easier to distribute the C API and Java API in the same package, and it didn't seem worth changing the name just for that, since changing the name is itself a breaking API change.)

> what's the reason for [com.google.android](com.google.android.gms:play-services-tflite-java) library and distribution to be different from org.tensorflow:tensorflow-lite ?

The former is a "thin client" library that uses a TF Lite runtime with a stable ABI, distributed via Play services. Because this requires a stable ABI, it does not support experimental features.

The latter is a "thick client" library that links the TF Lite runtime into the application. That one does support experimental features.

In general, we recommend using `com.google.android.gms:play-services-tflite-java` rather than `org.tensorflow:tensorflow-lite`, and sticking to only using the stable API methods rather than the experimental API methods.  However, if your app is relying on the experimental API methods, then it may be easier to stick with `org.tensorflow:tensorflow-lite`.

> if play services is the most up to date, there seems to be some inconsistencies in the documentation? For instance, I can't find the [Interpreter](https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/Interpreter) anymore now. It seems to have been replaced by InterpreterApi, but it's unclear why we still see both in documentation

The `Interpreter` API is experimental, and includes experimental methods. So it is available only from the `org.tensorflow:tensorflow-lite` runtime, not from the Play services runtime. It inherits from `InterpreterApi` which defines the stable API, but also adds additional experimental methods.

> If Interpreter was actually replaced by InterpreterApi, what's the new way to get the getSignatureKeys from this Play Services library?

We don't yet have a stable API method for that in the Java API.  We do have stable API methods for that in the C++ and C APIs, though: `tflite::Interpreter::signature_keys()` in the C++ API and `TfLiteInterpreterGetSignatureCount` / `TfLiteInterpreterGetSignatureKey `in the C API.  So I think the lack of a stable API for that in the Java API is just an oversight -- I think we can safely promote the `getSignatureKeys` method from experimental to stable now.  

> I was using Interpreter before so it seems natural to update everything for InterpreterApi, but is it advised against in any way?

As long as your application does not require use of the experimental methods added in `Interpreter`, we advise you depend only on `InterpreterApi`.

> Is [CompatList](https://www.tensorflow.org/lite/api_docs/java/org/tensorflow/lite/gpu/CompatibilityList)
> deprecated

No.

> / no need to call getBestOptionsForThisDevice anymore?

There has never been any _need_ to call that. That method is fairly aspirational; it exists only "For forward compatibility, when the compatibilityList contains more information."  Right now it always returns the empty set of options.  
In theory in future it might return better options that could give better performance on some devices.
Though personally I am skeptical that it will ever return anything other than the empty set of options.  

> compatList.isDelegateSupportedOnThisDevice replaced by TfLiteGpu.isGpuDelegateAvailable ?

If you are using `com.google.android.gms:play-services-tflite-java`, then yes, `TfLiteGpu.isGpuDelegateAvailable` is preferable.  If you are using `org.tensorflow:tensorflow-lite`, then stick with `compatList.isDelegateSupportedOnThisDevice`.

**Comment by fergushenderson** [comment]
We have promoted the signature-related Java API methods from experimental to stable,
and moved them from the `Interpreter` class to the interface that it implements, `InterpreterApi`:
https://github.com/tensorflow/tensorflow/commit/cfe49f4165aff69905c7eb32917a55e4c9be47f2

We have also made a new release of the SDK for Play Services:
https://maven.google.com/web/index.html?q=tflite#com.google.android.gms:play-services-tflite-java:16.3.0
https://maven.google.com/web/index.html?q=tflite#com.google.android.gms:play-services-tflite-gpu:16.3.0

P. S. Thanks for reporting this!
