### ISSUE TITLE
`Check failed` in `tf.raw_ops.TensorScatterAdd` and `tf.tensor_scatter_nd_add` when the rank of `indices` > 2. 

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65671]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

Yes

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Check failed` in `tf.raw_ops.TensorScatterAdd` and `tf.tensor_scatter_nd_add` when the rank of `indices` > 2, which causes the program to crash. See the colab link below for details.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/18JWN3lSTdwvwuG2yka6Uek7CHmwH9ffi?usp=sharing
```

### Relevant log output

```shell
Check failed: d < dims() (1 vs. 1)
```

**Comment by Venkat6871** [comment]
Hi **@xl1043237213** ,

I tried to run your code on colab using TF v2.15, 2.16.1, nightly and faced the same issue. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/6500f73bbd6aa7e4549e1a46bc82d58b/65671_2-15-2-16-nightly-v.ipynb) here for reference.

Thank you!

**Comment by dhantule** [comment]
Hi @xl1043237213, 
You can implement your code using `keras.ops.scatter_update` API however the indices tensor seems to have an extra dimension `([[[0, 0]]])`, which is likely causing issues because `keras.ops.scatter_update` typically requires a 2D indices tensor, where each row represents an index location as mentioned in this [documentation](https://keras.io/api/ops/core/#scatterupdate-function). Attaching [gist](https://colab.sandbox.google.com/gist/dhantule/18208d83303a847c7ff26ce8a32d107f/copy-of-6_tf_raw_ops_tensorscatteradd.ipynb).
