### ISSUE TITLE
ModuleNotFoundError: No module named 'tensorflow.compat'

### ISSUE THREAD

**Issue by deniseepflo** [tensorflow/tensorflow#65772]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.15

### Custom code

Yes

### Python version

3.10.9

### Current behavior?

I have tensorflow 2.15 and python 3.10.9 with this error. 
    import tensorflow.compat.v1 as tf
ModuleNotFoundError: No module named 'tensorflow.compat'

### Standalone code to reproduce the issue

```shell
n
```

**Comment by sushreebarsa** [comment]
@deniseepflo TensorFlow 2.x encourages a different approach. Instead of tensorflow.compat.v1, directly import TensorFlow:
```
import tensorflow as tf
```
 It should work with tensorflow 2.15 and python 3.10.9. 
Please refer to this TensorFlow migration [guide](https://www.tensorflow.org/guide/migrate) for more information.
Thank you!
