### ISSUE TITLE
tf.rank not working. Increments each call

### ISSUE THREAD

**Issue by cgel** [tensorflow/tensorflow#6578]
When running this line:
```tf.rank(tf.placeholder(tf.int32))```
the output increments each time:
```<tf.Tensor 'Rank:0' shape=() dtype=int32>```
```<tf.Tensor 'Rank_1:0' shape=() dtype=int32>```
```<tf.Tensor 'Rank_2:0' shape=() dtype=int32>```

Ubuntu 14.04
Latest install from pip
Both gpu and cpu
0.12.0

**Comment by mrry** [comment]
Each call to `tf.rank()` is creating a new `tf.Tensor` object, and the number you see incrementing is a suffix added to operation names to make them unique.

(This kind of query is better handled on Stack Overflow, since it's neither a bug nor a feature request. Feel free to post a question there to continue the discussion.)

**Comment by cgel** [comment]
Oh! So dumb! Sorry.

**Comment by subratksahoo** [comment]
import tensorflow as tf
x = tf.placeholder(tf.int32,[1,2,5])
rank = tf.rank(x)
with tf.Session() as sess:
    rank_out = sess.run(rank)
    print(rank_out)
