### ISSUE TITLE
Bazel：command not found

### ISSUE THREAD

**Issue by louisway** [tensorflow/tensorflow#6581]
I have install the bazel v0.3.2 per the instruction and it works well on the terminal.but when I was running ./configure, it comes with a result of "Bazel :command not found"

**Comment by zafartahirov** [comment]
COuld you post more information about what is the operating system, how was bazel installed, also run these commands from your terminal and post the outputs:

```
python -c "import tensorflow; print(tensorflow.__version__)"
git rev-parse HEAD
bazel version
```

If you are using Linux or Mac OS, also post this:

```
echo  ${PATH}
./configure
```

I am not sure what is the equivalent for `PATH` in Windows

**Comment by gunan** [comment]
This looks like a problem with your installation of bazel.
Not really a TensorFlow issue.

Please make sure in the same terminal you are running `./configure`, you can run `bazel version`.
You might need to add the location of bazel binary to your path.

Since this is a bazel installation issue, I am closing it. Please make sure to follow bazel installation documentation to make sure it is installed properly.
