### ISSUE TITLE
`Overflow` in `tf.raw_ops.SparseReduceSumSparse` when there are too large values in `input_shape`. 

### ISSUE THREAD

**Issue by xl1043237213** [tensorflow/tensorflow#65871]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

binary

### TensorFlow version

tf 2.15

### Custom code

No

### OS platform and distribution

Linux Ubuntu 20.04

### Python version

3.10

### Current behavior?

`Overflow` in `tf.raw_ops.SparseReduceSumSparse` when there are too large values in `input_shape`.  See the colab link below for details.

### Standalone code to reproduce the issue

```shell
https://colab.research.google.com/drive/17mqn3t23p9sb4e3stOsPvZBTHENqJYku?usp=sharing
```

### Relevant log output

```shell
Non-OK-status: InitDims(dim_sizes) status: INVALID_ARGUMENT: Encountered overflow when multiplying 1700000000000 with 6000000, result: -8246744073709551616
```

**Comment by tilakrayal** [comment]
@xl1043237213,
Thank you for reporting the issue. I was able to reproduce the issue on tensorflow v2.15, v2.16 and tf-nightly. Kindly find the gist of it [here](https://colab.sandbox.google.com/gist/tilakrayal/608a78c05825ddeba08516a1893a5095/untitled1865.ipynb).

**Comment by Gopi-Uppari** [comment]
Hi @xl1043237213,

I was reproduced the issue or error with latest Tensorflow version (TF 2.18.0). Please refer to this [gist file](https://colab.research.google.com/gist/Gopi-Uppari/0d2d0b19120cff83521946e6e0ece549/tf_issue_65871.ipynb).

The issue occured because TensorFlow is attempting to calculate a very large product (1700000000000 * 6000000) as part of the 
sparse tensor operations, leading to integer overflow. The result exceeds the maximum value of a 64-bit integer, causing the calculation 
to fail.

To resolve this error, could you please reduce the scale of the input_shape values if possible.

Thank you.
