### ISSUE TITLE
no such package '@jpeg_archive//': Error downloading from ijg.org

### ISSUE THREAD

**Issue by markusdr** [tensorflow/tensorflow#67]
I'm getting the following error when trying to build from source:

    $ bazel build -c opt --config=cuda //tensorflow/cc:tutorials_example_trainer
    ERROR: /home/name/tmp/tensorflow/tensorflow/core/platform/default/build_config/BUILD:36:1: no such package '@jpeg_archive//': Error downloading from http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/name/.cache/bazel/_bazel_mddreyer/44409223966f9cb8e480014c7f376bcc/external/jpeg_archive: Error downloading http://www.ijg.org/files/jpegsrc.v9a.tar.gz to /home/name/.cache/bazel/_bazel_mddreyer/44409223966f9cb8e480014c7f376bcc/external/jpeg_archive/jpegsrc.v9a.tar.gz: Server returned HTTP response code: 403 for URL: http://www.ijg.org/files/jpegsrc.v9a.tar.gz and referenced by '//tensorflow/core/platform/default/build_config:platformlib'.
    ERROR: Loading failed; build aborted.

**Comment by mrry** [comment]
Is it possible that this was a transient issue when fetching http://www.ijg.org/files/jpegsrc.v9a.tar.gz? I was able to fetch it using wget on my laptop.

If you fetch that URL using wget, do you also get a 403 error?

**Comment by koki0702** [comment]
I have the same problem.
So I fetch the jpegsrc.v9a.tar.gz manually and move the file to the specified directory.
But I have the error below.

```
no such package '@gemmlowp//': https://github.com/google/gemmlowp.git: cannot open git-upload-pack and referenced by '//tensorflow/core:kernels'.
```

Any ideas?

**Comment by jendap** [comment]
It sounds like network connectivity issues in both cases. Try to run it again and check your internet connection that it is not flaky.

@koki0702 the gemmlowp is yet another dependency. it is essentially doing `git clone https://github.com/google/gemmlowp.git` in the same ~/.cache/bazel/.../.../external directory. But do not download them manually one by one. There is too many. Just fix the internet connection.

**Comment by markusdr** [comment]
I tried it multiple times but it didn't work. My coworker had the same problem. But downloading jpegsrc.v9a.tar.gz using wget and copying it to /home/name/.cache/bazel/_bazel_... was OK as a workaround.

**Comment by vrv** [comment]
This seems more like a bazel issue -- closing for now.  Please re-open if you think we need to fix this differently in our BUILD files!

**Comment by davidzchen** [comment]
Feel free to report any Bazel-related issues at https://github.com/bazelbuild/bazel/issues, and we will take a look. Thanks!

**Comment by mattisback** [comment]
I get the error 

> Your request has reached a system that is acting as a gateway or proxy to fulfill the request made by you.
> This system is currently experiencing a temporary error reaching the web site you are requesting.
> Your website (if you host with us) is safe and sound. Our engineers are already aware of this issue and should have it fixed in a couple of minutes. Thanks for your patience in the meantime!

It's a bit frustrating that building tensorflow is reliant on an external source which is unreliable.  Perhaps a backup url should be implemented in case the original url is not accessable?

**Comment by vrv** [comment]
@damienmg, @lberki what do you think about being able to list multiple sources for an external source, instead of just one in bazel?

For example, one thing we could do is host a lot of the source code ourselves on say, Google storage.  Unfortunately, that doesn't work for our clients in China, which is why we don't do that today.  However, if we had multiple sources to choose from, bazel could iterate through them until it finds a successful source.  Worthy of a feature request?

(@jart what do you think?)

**Comment by damienmg** [comment]
Sounds like a reasonable feature request yes.

**Comment by jart** [comment]
@vrv @damienmg Does [repository_ctx.download](https://www.bazel.io/versions/master/docs/skylark/lib/repository_ctx.html#download) throw an exception when a download fails? Because then we could write our own custom repository rule that has failover.

But to be honest, I would rather just mirror the files to a server that works everywhere in the world, including China. I think I figured out how to do this with Google's production environment. So I'm going to be looking into that.

**Comment by Goddard** [comment]
Am I missing something, but I am being sent to http://zlib.net/zlib-1.2.8.tar.gz, but this is 404.

**Comment by jart** [comment]
@Goddard I believe I fixed our workspace.bzl file to update those URLs a couple weeks ago. Chances are you're tracking an old branch. Please pull the latest code.
