### ISSUE TITLE
tensorflow conv2d unexpected convolution result

### ISSUE THREAD

**Issue by HRLTY** [tensorflow/tensorflow#6722]
I try to migrate a `Caffe` network and model(weights) to `tensorflow`. The original first layer is a stride one convolution on 1x128x128 gray image with kernel size 5x5, output channel 96, Caffe two padding, tf 'SAME' padding.
I checked the input image and kernel weights are the same for both versions.
However, the two's upper left corner of conv1's first feature map are **different**.
Only the leftmost column is consistent. I manually calculated and checked the results, the first and the second value of Caffe's (-0.71238005 -0.74042225) are correct according to the definition of convolution, the second value in tensorflow's (-0.71238005 -0.31195271) is **incorrect**. Taking into account the padding, the first value is from the 3x3 block of the image, the second should be the 3x4 block.
Is there any subtle difference in computation model between the two version's implementation of convolution? 
I am not sure whether it is a bug of `tf` or an usage omission. So I posted the detailed version of the problem on [StackOverflow](http://stackoverflow.com/q/41529997/3863647).

**Comment by Valentin4869** [comment]
Sorry, I know you closed this, but I've ran into this problem myself today and have been trying to understand what's wrong for 13 hours with no answer. I wonder if you managed to figure out what was wrong? It seems to me that it's a bug with TF.

I imported some weights from a Caffe network into TF, and for verification I used MATLAB. I also have two OpenCL implementations using FFT convolution and standard convolution. All results excluding TF are consistent, and no matter how much I play around with the padding in TF, it just won't produce the correct results. Plotting the outputs show significant differences, especially in the second layer.  In my case, these errors accumulate and grow through the second convolutional layer and reduces the network's accuracy from 97% to 60%. Of course, it's possible to train the network again in TF to get weights that work, but I don't understand why this bug is not fixed considering how bad it is.
