### ISSUE TITLE
Fit function to work with adaptive step size

### ISSUE THREAD

**Issue by Danojungo** [tensorflow/tensorflow#67252]
Hi,
Is there a way to make the generic fit function work but have different steps in each epoch?
I'm using tf.dataset.sample_from_datasets and I don't get the same amount of steps each epoch, I don't want to use repeat and I do want to run over all my positive samples without setting the steps_per_epoch.

**Comment by Venkat6871** [comment]
Hi **@Danojungo** ,
- Could you use a custom training loop instead of the generic fit function. This approach provides more flexibility, allowing you to adjust the number of steps dynamically for each epoch.
- The generic fit function in tensorflow does not support varying the number of steps per epoch directly.

Thank you!
