### ISSUE TITLE
[TensorFlowLite] Add new data types in the TFLite format schema

### ISSUE THREAD

**Issue by mciprian13** [tensorflow/tensorflow#67821]
Add new data types in the TFLite format schema that could be leveraged by custom accelerators, such as:
- Custom floating point format, having configurable number of bits for exponent and mantissa (something like **TensorType_FLOAT8** using custom format options)

This is relevant only for the TFLite format (schema) used for model representation and not necessary for the TFLite tools or runtime.
This is relevant when industry has proprietary tools that rely on the TFLite format but not on the TFLite tools or runtime (interpreter),

**Comment by pkgoogle** [comment]
Seems like a reasonable request, @miaout17, can you please take a look? Thanks.

**Comment by gaikwadrahul8** [comment]
Hi, @mciprian13 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/63

Let us know if you have any questions. Thanks.
