### ISSUE TITLE
TensorBoard: Improve handling of tall images

### ISSUE THREAD

**Issue by carlthome** [tensorflow/tensorflow#6789]
**[Example of how it looks today](https://cloud.githubusercontent.com/assets/1595907/21849403/e4a3a9e4-d805-11e6-9210-705cff983b4a.png), and [an example of how it would look without stretching](https://cloud.githubusercontent.com/assets/1595907/21849399/da03e30a-d805-11e6-80f4-02f2a44417b9.png).**

TensorBoard's CSS for image summaries stretches the image to 100% which makes it hard to interpret images, especially with pooling operations like in [VGG-like neural networks](https://www.cs.toronto.edu/~frossard/post/vgg16/).

Also, considering datasets as [CIFAR](https://www.cs.toronto.edu/~kriz/cifar.html) have images of 32x32, the large amount of stretching leads to very blurry images. Could we either have control of the number of columns in a pane, or disable image stretching altogether?

**Comment by jart** [comment]
What browser are you using? What happens if you tune the interpolation algorithm in the CSS? Those screenshots look like nearest neighbor, and it does kind of feel like it's losing something when resized.

Disabling image stretching is probably not something we would consider. Perhaps instead we should provide a choice of image interpolation algorithms.

cc: @dandelionmane

**Comment by dandelionmane** [comment]
The latest version of TensorBoard has a button attached to every image that lets you view it as true pixel size. Will that solve the need for you?

Also, +1 for Justine's question about which browser you're using. On chrome by default it doesn't interpolate, just increases size, so it will become blocky rather than blurry. Maybe we don't have the right CSS setting for your browser, though.

**Comment by carlthome** [comment]
Yes, screenshots are from Chrome.

The button to show the actual size is nice, but IMO it would be better if the stretching didn't occur, or at least was controlled with `max-height: 50vh` or something because `width: 100%` really goes bonkers with `height: auto`. For example, [this slice of a spectrogram](https://cloud.githubusercontent.com/assets/1595907/21936553/d1f1eb00-d9b1-11e6-8709-6fc4b807e209.png) stretches from 62x672 to 340x3685 pixels on my 1080p display in Chrome.

Could we at least control the number of columns or something with a slider?

**Comment by jart** [comment]
I retract my previous comment about stretching algorithm. I failed to notice the two screenshots were at different steps, which explains why they looked so different.

It's been really difficult for us to find a way to make the images dashboard fit all use cases. For example, the mnist tutorial has really tiny images, so we'd naturally want to stretch those.

Your suggestion of vh is actually a really interesting idea that we hadn't considered. Especially if we can make the number of card columns increase when `max-height: 100vh` kicks in. However this could potentially make the card title less useful in your case, since it's overflow hidden.

**Comment by chihuahua** [comment]
3f6404f2069a1baf795cc618e700dd43dcbeeb15 limits the default max height of images to 800px. One can always view true pixel size (the full image) if they desire, so I am closing this issue.
