### ISSUE TITLE
Building on OSX with custom swig location

### ISSUE THREAD

**Issue by tomwardio** [tensorflow/tensorflow#681]
Tried to compile Tensorflow on OSX where I'd installed swig (through homebrew) to a location not usually in PATH (~/homebrew/bin) and found that it failed to run swig due to an issue with the swig.sh that's checked in. 

Changing the path in the swig.sh to the absolute path (rather than rely on it being globally accessible) fixed the issue, but I'm unsure how to fix properly through bazel.

Happy to submit a pull req. if someone could advise how best to fix the issue!

**Comment by martinwicke** [comment]
so ~/homebrew/bin is in your PATH? I think this is a question for the bazel folk. Bazel passes on the PATH environment variable to shell scripts it runs, but I don't know off the top of my head how to set it explicitly.

Closing this here -- feel free to reopen if it turns out we should have written swig.sh differently.

**Comment by tomwardio** [comment]
Yes, ~/homebrew/bin is in my path, but for some reason it's not picked up by the BUILD system. Will check to see what PATH is used when building through bazel and see if there's a way to fix. Thanks!
