### ISSUE TITLE
python documentation for tensorflow.abs out of sync

### ISSUE THREAD

**Issue by drewm1980** [tensorflow/tensorflow#6812]
I checked out the master branch tonight:
d4b5c606fc9fbd1a20b5b113b4bc831f31d889a3

I installed the code with pip into a conda environment

It seems the tensorflow.complex_abs() function has been merged into the overloaded tensorflow.abs() function.

The docstring, along with the rest of the python documentation don't seem to reflect this change:

> In [53]: tf.abs?
> Signature: tf.abs(x, name=None)
> Docstring:
> Computes the absolute value of a tensor.
> 
> Given a tensor of real numbers `x`, this operation returns a tensor
> containing the absolute value of each element in `x`. For example, if x is
> an input element and y is an output element, this operation computes
> \\(y = |x|\\).
> 
> Args:
>   x: A `Tensor` or `SparseTensor` of type `float32`, `float64`, `int32`, or
>     `int64`.
>   name: A name for the operation (optional).
> 
> Returns:
>   A `Tensor` or `SparseTensor` the same size and type as `x` with absolute
>     values.
> File:      ~/src/anaconda3/lib/python3.5/site-packages/tensorflow/python/ops/math_ops.py
> Type:      function
>

**Comment by jart** [comment]
This change is being documented as part of the 1.0 release process. Please see https://github.com/tensorflow/tensorflow/releases/tag/v1.0.0-alpha

Are you suggesting that we change the docstring above to say something like "Given a tensor of real or complex numbers x, this operation returns a tensor [...]"? If so, maybe this would be an easy opportunity for you to make a contribution to the codebase. We'd be grateful for a pull request. Otherwise maybe @xmbrst could take a look.

**Comment by aselle** [comment]
Closing due to lack of recent activity. if you provide additional information, we can reopen this. Thanks!
