### ISSUE TITLE
tf.strided_slice outputs tensor of incorrect shape

### ISSUE THREAD

**Issue by strin** [tensorflow/tensorflow#6834]
so for tensor x of shape (?, 41, 41, 32), using

```
tf.strided_slice(x, [0, 1, 1, 0], [-1, -1, -1, -1], [1, 2, 2, 1])
```

will produce tensor <tf.Tensor 'StridedSlice_9:0' shape=(?, 20, 20, 31) dtype=float32>. This result is unexpected, since for last dimension, begin = 0, last = -1, and stride = 1. It should extract the entire dimension.

**Comment by yaroslavvb** [comment]
note that a[:-1] doesn't extract whole of `a`, it stops one element short, and  `strided_slice` copies numpy semantics

If you want to go all the way, you could do a[:] in Python subscript notation (which is syntactic sugar for `strided_slice`) or use `end_mask` argument to ignore the endpoint

`y=tf.strided_slice(x, [0, 0, 0, 0], [-1, -1, -1, -1], [1, 2, 2, 1], end_mask=8)`

**Comment by jart** [comment]
@strin does @yaroslavvb's response address your issue?

**Comment by yaroslavvb** [comment]
As discussed with @strin IRL, the confusion was that in `tf.slice(a, b)`, `b` specifies `size` and `-1` means "take all elements", whereas in `tf.striced_slice(a, b)`, `b` specifies `end` and `-1` means "take elements up to the last one, not including the last one". I'll close this issue for now since new users are likely to not use `slice` directly, so this should become less of an issue

**Comment by strin** [comment]
As @yaroslavvb explained, the second argument `b` has different semantic meaning in `tf.slice` and `tf.strided_slice`. this was confusing to me, because i thought `tf.strided_slice` is an extension of `tf.slice` except for the stride.

**Comment by tlbtlbtlb** [comment]
This just bit me too. It'd be better if the [documentation](https://www.tensorflow.org/api_docs/python/tf/strided_slice) suggested to use Python's array notation instead.
