### ISSUE TITLE
tf.contrib.losses.sparse_softmax_cross_entropy not normal

### ISSUE THREAD

**Issue by benwu232** [tensorflow/tensorflow#6846]
When I tried to use tf.contrib.losses.sparse_softmax_cross_entropy with weights for losses, I got the error:

ValueError: weight.get_shape().ndims cannot be None

Later, I used tf.contrib.losses.softmax_cross_entropy and onehot labels,  everything was ok.  Is there anything wrong with tf.contrib.losses.sparse_softmax_cross_entropy?

Thanks a lot!

**Comment by foxik** [comment]
I have encountered the issue before.

The problem is that if `weights` has unknown shape (for example if it is `[None]`), the following line (referenced current head):
https://github.com/tensorflow/tensorflow/blob/333dc32ff79af21484695157f3d141dc776f7c02/tensorflow/contrib/losses/python/losses/loss_ops.py#L424
causes the resulting shape to be `None` (because the number of dimensions after the `squeeze` is unknown at construction time). Then the code in `compute_weighted_loss` throws an error.

The solution is to remove the referenced line (you can see that it is not in `softmax_cross_entropy` call), because it interferes with the code for dealing with different shapes of `weights` present in `compute_weighted_loss`.

**Comment by jart** [comment]
Thank you for helping our friend @foxik.

**Comment by foxik** [comment]
BTW, are you planning to fix the issue, i.e., remove the offending line from tensorflow/contrib/losses/python/losses/loss_ops.py? I could not find any corresponding pull request (I suppose it would be referenced here automatically if it was created).

**Comment by jart** [comment]
Re-opening for triage again.

**Comment by benwu232** [comment]
@foxik , thanks for your detailed explanation!

**Comment by drpngx** [comment]
@foxik it looks like you have a good handle on this, would you mind sending a PR to fix this?

**Comment by foxik** [comment]
Working on it.
