### ISSUE TITLE
Problems with generate_batch() in word2vec_basic.py

### ISSUE THREAD

**Issue by soloice** [tensorflow/tensorflow#6860]
Does the generate_batch() function miss some possible (word, context) pairs? The sliding window always skips the end of a batch.

For example, if I change the demonstration codes followed by this function into
```
batch, labels = generate_batch(batch_size=4, num_skips=2, skip_window=1)
for i in range(4):
  print(batch[i], reverse_dictionary[batch[i]],
        '->', labels[i, 0], reverse_dictionary[labels[i, 0]])

print('-'*40)
batch, labels = generate_batch(batch_size=4, num_skips=2, skip_window=1)
for i in range(4):
  print(batch[i], reverse_dictionary[batch[i]],
        '->', labels[i, 0], reverse_dictionary[labels[i, 0]])
```
, the sampled pairs would be:
```
3083 originated -> 5242 anarchism
3083 originated -> 12 as
12 as -> 3083 originated
12 as -> 6 a
----------------------------------------
3134 abuse -> 2 of
3134 abuse -> 46 first
46 first -> 3134 abuse
46 first -> 59 used
```

Note that the sampled sentence is:
`Sample data [5242, 3083, 12, 6, 195, 2, 3134, 46, 59, 156] ['anarchism', 'originated', 'as', 'a', 'term', 'of', 'abuse', 'first', 'used', 'against']`
, pairs such like `a -> term`, `term -> of`, `of -> abuse` are skipped.

**Comment by jart** [comment]
Thanks for reaching out @soloice. I'm triaging bugs this week. I'm not deeply familiar with this tutorial, but I'm reluctant to triage this as a bug in TensorFlow since it's modified example code and skipping pairs when training appears to be an intended behavior of the skip-gram model. Maybe the following resources will help?

- https://www.quora.com/How-does-word2vec-work
- http://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/
- http://mccormickml.com/2016/04/27/word2vec-resources/
- https://arxiv.org/pdf/1301.3781.pdf

**Comment by soloice** [comment]
Thanks for your reply.

Though, you might have some misunderstanding about word2vec.  I'm familiar with this model, and have published a paper on it.  I think this is a minor bug, not a desired behavior.  For example, this will cause failure of some theoretical analysis, i.e.: [neural-word-embedding-as-implicit-matrix-factorization](https://papers.nips.cc/paper/5477-neural-word-embedding-as-implicit-matrix-factorization.pdf).

But it's not too serious, because the effect is to subsampling the corpus.  In practice, it still works well for word embedding learning.

A simple fix is to let the pointer `data_index` to backtrack a little bit at the end of generate_batch(), see the next-to-last line below:
```
# Step 3: Function to generate a training batch for the skip-gram model.
def generate_batch(batch_size, num_skips, skip_window):
  global data_index
  assert batch_size % num_skips == 0
  assert num_skips <= 2 * skip_window
  batch = np.ndarray(shape=(batch_size), dtype=np.int32)
  labels = np.ndarray(shape=(batch_size, 1), dtype=np.int32)
  span = 2 * skip_window + 1  # [ skip_window target skip_window ]
  buffer = collections.deque(maxlen=span)
  for _ in range(span):
    buffer.append(data[data_index])
    data_index = (data_index + 1) % len(data)
  for i in range(batch_size // num_skips):
    target = skip_window  # target label at the center of the buffer
    targets_to_avoid = [skip_window]
    for j in range(num_skips):
      while target in targets_to_avoid:
        target = random.randint(0, span - 1)
      targets_to_avoid.append(target)
      batch[i * num_skips + j] = buffer[skip_window]
      labels[i * num_skips + j, 0] = buffer[target]
    buffer.append(data[data_index])
    data_index = (data_index + 1) % len(data)
  data_index = (data_index + len(data) - span) % len(data)
  return batch, labels
```

FYI.

**Comment by jart** [comment]
In that case I will re-open and put you in touch with someone who can help.

@gouwsmeister Our friend @soloice believes he's found a minor bug in the word2vec_basic.py tutorial.  Since you've done work on this tutorial in the past, I'm hoping you can take a look into the information he's presented us.

**Comment by gouwsmeister** [comment]
Good catch. Yes, this seems to be a (very subtle) off-by-one error. Since it only seems to affect the end of every batch, it's effect should almost be negligible (especially for larger batches). 

@soloice, could you please post the output on the same example sentence with your fix, and if it solves the problem we can accept a pull request to fix it?

**Comment by soloice** [comment]
@gouwsmeister Sure. With my fix, the output on the same example will be:
```
Sample data [5234, 3081, 12, 6, 195, 2, 3135, 46, 59, 156] ['anarchism', 'originated', 'as', 'a', 'term', 'of', 'abuse', 'first', 'used', 'against']
3081 originated -> 5234 anarchism
3081 originated -> 12 as
12 as -> 6 a
12 as -> 3081 originated
----------------------------------------
6 a -> 195 term
6 a -> 12 as
195 term -> 2 of
195 term -> 6 a
```
Now all possible pairs are recalled, and words at the end of a batch (`term`, for instance) will appear in the next batch.

**Comment by soloice** [comment]
@gouwsmeister  I've made a pull request about this issue. 
This is the first time that I made a pull request on Github. Not sure if I'm getting it correctly.
Thanks for your tracking.
