### ISSUE TITLE
Dead link to Graph.control_dependencies()

### ISSUE THREAD

**Issue by GothaB** [tensorflow/tensorflow#6884]
"tf.control_dependencies(control_inputs) {#control_dependencies}

Wrapper for Graph.control_dependencies() using the default graph.
See **Graph.control_dependencies()** for more details."

The link to **Graph.control_dependencies()** is dead, but I could really need the details. : 3

(Hope this is the right place the post this. X: )

**Comment by asimshankar** [comment]
@GothaB : I'm guessing you were looking at some markdown files in github. Those may not have correct links, but the API docs on the TensorFlow website (www.tensorflow.org/api_docs/) are probably a better place to browse documentation anyway. 

See [`tf.control_dependencies`](https://www.tensorflow.org/api_docs/python/framework/utility_functions#control_dependencies) linked there and the link to [`Graph.control_dependencies`](https://www.tensorflow.org/api_docs/python/framework/core_graph_data_structures#Graph.control_dependencies) from it.

Closing this issue out since I believe it has been resolved. Feel free to reopen/create a new one if I misunderstood.
