### ISSUE TITLE
tf.select missing in v1.0?

### ISSUE THREAD

**Issue by chenghuige** [tensorflow/tensorflow#6899]
Seems no tf.select in v1.0 and it exists in v0.12(also not marked as depreciated).
If no tf.select do we have corresponding ops to achieve select ?

**Comment by asimshankar** [comment]
Use `tf.where` instead of `tf.select`.
(See [RELEASE.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md))

Apologies for the breaking changes, which should reduce considerably once 1.0 stable is released.

Also, FYI, there is a tool to help with these upgrades: https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/compatibility

Closing this out, feel free to reopen or file a new issue if your issue hasn't been addressed

**Comment by mckeesh** [comment]
@asimshankar is there a reason this isn't in the docs? Putting the notice of deprecation somewhere in v0.12 or v1.0 docs might save people some time :)

**Comment by asimshankar** [comment]
@mckeesh : As pointed out above, it is in the release notes file ([RELEASE.md](https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md)). I'll look into making those notes even more accessible from www.tensorflow.org
