### ISSUE TITLE
Missing legal value check for groups parameter of tf.keras.layers.Conv1D

### ISSUE THREAD

**Issue by PhyllisJi** [tensorflow/tensorflow#69101]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

tf 2.14.0

### Custom code

Yes

### OS platform and distribution

Ubuntu 20.04

### Current behavior?

tf.keras.layers.Conv1D still works fine when groups is set to 0.
With the same parameter settings, pytorch throws the following exception:
```
ValueError: groups must be a positive integer
```

### Standalone code to reproduce the issue

```shell
import tensorflow as tf

conv_layer = tf.keras.layers.Conv1D(
    filters=64,
    kernel_size=1,
    strides=1,
    padding="valid",
    data_format="channels_last",
    dilation_rate=1,
    groups=0, 
    use_bias=True,
    name="conv2"
)

input_tensor = tf.keras.Input(shape=(32, 3))

output_tensor = conv_layer(input_tensor)

print(output_tensor.shape)
```

**Comment by tilakrayal** [comment]
@PhyllisJi,
AFAIK the argument Groups should A positive int specifying the number of groups in which the  input is split along the channel axis. Each group is convolved separately with `filters // groups` filters. The output is the concatenation of all the `groups` results along the channel axis.

Also the Input channels and `filters`  provided must both be divisible by `groups`. Here you are trying with the groups=0 which is not divisible. And also it was fixed in the Tensorflow 2.16. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/93ebecc9d54fd953439d4feddabbfcc0/untitled1933.ipynb).

https://keras.io/api/layers/convolution_layers/convolution1d/

Thank you!
