### ISSUE TITLE
Getting sparse tensors from graph by name

### ISSUE THREAD

**Issue by stepelu** [tensorflow/tensorflow#6922]
Standard (dense) tensors can be easily retrieved by name from a graph using:

`graph.get_tensor_by_name("tensor_name:tensor_index")`

Comparable functionality is provided for operations, but it's not clear to me how to retrieve a sparse tensor in a similar way.
Is such functionality provided at the moment? Having to pass the object around makes the code more involved than it should be.

**Comment by yaroslavvb** [comment]
Yes, it's possible, you just have to figure out the names of tensors that are storing the sparse tensor data. There are some details here

https://www.google.com/url?hl=en&q=https://groups.google.com/a/tensorflow.org/d/msgid/discuss/CADtzJKPqcpYLP2LEgXEUqTpXLbD7YW5coALcR-RZrUirhovydg%2540mail.gmail.com?utm_medium%3Demail%26utm_source%3Dfooter&source=gmail&ust=1484809569744000&usg=AFQjCNFKi8wGndSsYXdUx6Qb5X_WwrPu6w

I think this question is much better suited for stackoverflow since this list is for bugs/feature requests to tensorflow itself
