### ISSUE TITLE
DXGI format does not support cross-API sharing

### ISSUE THREAD

**Issue by VivekEedeeCreations** [tensorflow/tensorflow#69430]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

4.17

### Custom code

Yes

### OS platform and distribution

Windows 10

### Current behavior?

I'm using tensor flow's pose-detection model and a canvas is drawing in a webcam feed with p5.js but in my system i'm not able to see the green lines drawn on my p5 and getting my console filled with these 
514:1 DXGI format does not support cross-API sharing.
    at ValidateVideoTextureCanBeShared (..\..\third_party\dawn\src\dawn\native\d3d12\TextureD3D12.cpp:183)

[Invalid Texture] is invalid.
 - While calling [Invalid Texture].CreateView([TextureViewDescriptor]).

### Standalone code to reproduce the issue

```shell
514:1 DXGI format does not support cross-API sharing.
    at ValidateVideoTextureCanBeShared (..\..\third_party\dawn\src\dawn\native\d3d12\TextureD3D12.cpp:183)

[Invalid Texture] is invalid.
 - While calling [Invalid Texture].CreateView([TextureViewDescriptor]).
This is console filled with when starting the video feed with tensor flow pose detection
```

### Relevant log output

```shell
514:1 DXGI format does not support cross-API sharing.
    at ValidateVideoTextureCanBeShared (..\..\third_party\dawn\src\dawn\native\d3d12\TextureD3D12.cpp:183)

[Invalid Texture] is invalid.
 - While calling [Invalid Texture].CreateView([TextureViewDescriptor]).
```

**Comment by tilakrayal** [comment]
@VivekEedeeCreations,
Looks like this issue is not related to tensorflow. AFAIK the reason might be that Some surface formats are not compatible with Direct2D operations regardless of how they are used. This message indicates that the application should choose another surface format.

https://learn.microsoft.com/en-us/windows/win32/direct2d/d1128
https://github.com/mpv-player/mpv/issues/11206

Thank you!
