### ISSUE TITLE
Better way to transfer data from memory to tensor in C++ API

### ISSUE THREAD

**Issue by ppries** [tensorflow/tensorflow#6955]
This is more of a general feature request for a better way to load data into a tensor in the C++ API, but I'll take our specific case as a reference.

We currently train a model in Python, freeze it, and load it in a C++ production pipeline. This works fine, but it seems the only way of loading data into a tensor is by looping through every single element in the data and copying it to a tensor. In our case, we're dealing with a 1920x1080 ~30 fps video input signal (each frame coming as an OpenCV matrix) making it infeasible to do if we want to process a video within a reasonable amount of time.

It seems there is a way of creating a tensor from a pointer in the C API (see http://stackoverflow.com/questions/39379747/import-opencv-mat-into-c-tensorflow-without-copying), which we will test next, but it would be nice to also have this functionality in the C++ API.

For reference, it takes approximately 900 ms to copy from an 1920x1080x3 OpenCV matrix to a tensor while it takes 315 ms to do session.run (which I assume includes transferring between CPU and GPU memory). 

An issue related to this is that we will probably already have the data on the GPU from some earlier preprocessing, so we would also be very interested in not having to transfer between CPU and GPU unnecessarily.

So I guess it boils down to:

1. Are there any plans for making it easier to load data already in memory to a tensor?
2. How can we contribute?

**Comment by asimshankar** [comment]
Perhaps I'm misunderstanding, but could you use `std::copy_n` on `Tensor::flat`? For example, see [`FillValues` in `tensor_testutil.h`](https://github.com/tensorflow/tensorflow/blob/dcc414587f50673271a31ab767909ec89c956324/tensorflow/core/framework/tensor_testutil.h#L57).

**Comment by allannk** [comment]
Yes, the idea is to avoid copying at all, since we're dealing with approximately 360 mb/s that are already in CPU memory. Avoiding a 1:1 copy (memcpy or otherwise) would be ideal. 

I've been looking into creating a custom allocator for tens or creation, to point to existing data instead - would this be possible? Or are we blind to the obvious solution here?

**Comment by yaroslavvb** [comment]
BTW, memcpy does around like 5GB/sec on a single core, so 360 MB/s seems on the low side

**Comment by ppries** [comment]
Preliminary tests with memcpy confirms that it does indeed run *much* faster; however, having a way of pointing to data instead of copying would still be very nice – especially if we could point to data already on the GPU in some way.

**Comment by yaroslavvb** [comment]
There's a discussion of sharing GPU memory in https://github.com/tensorflow/tensorflow/issues/2210#event-706768999 and it seems hard. 

For sharing main memory, possibly related issue to get rid of copy [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/tensor_coding.cc#L199) . I suspect that Allocator interface would need to be modified to allow keeping pointers to memory that it doesn't own

**Comment by sjperkins** [comment]
> however, having a way of pointing to data instead of copying would still be very nice – especially if we could point to data already on the GPU in some way.

As @yaroslavvb notes here: https://github.com/tensorflow/tensorflow/issues/2919#issuecomment-226660045 there's also a [memcpy ](https://github.com/tensorflow/tensorflow/blob/1084748efa3234c7daa824718aeb7df7b9252def/tensorflow/python/client/tf_session_helper.cc#L460-L470) for copying numpy array contents into python `Session.run()`. I'm mentioning this because I think there are similar issues across languages.

A similar python solution may involve creating a Tensor that wraps the numpy array but does not own the data.

Another possible solution involves explicitly allowing the user to pass array data by move or reference (C++ style). Move would assign ownership for the data to tensorflow, while by ref would leave ownership to the calling python/C++ code.

```python
with tf.Session() as S:
  S.run([ops], feed_dict={x: ...}, move_feed_dict={y:...}, ref_feed_dict={z: ...}
```

It would be nice for this to be consistent across languages.

**Comment by drpngx** [comment]
CC @mrry, @hawkinsp  as FYI.

I can sort of see how that would work on CPU only, but with GPU devices, and also XLA I can see that we would need to think carefully. A shallow tensor sounds like a great idea!

**Comment by sjperkins** [comment]
Thoughts:

I'm not sure that Eigen has the same concept of a [numpy strided indexing](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html#internal-memory-layout-of-an-ndarray) for a Tensor, but similar concepts are expressed in [TensorStriding](https://eigen.tuxfamily.org/dox-devel/unsupported/TensorStriding_8h_source.html) and [TensorPadding](https://eigen.tuxfamily.org/dox-devel/unsupported/TensorPadding_8h_source.html). It would be useful to map the numpy stride concept onto a Tensor, to avoid copies.

Otherwise, a call to [np.ascontiguousarray](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ascontiguousarray.html) will copy a non-contiguous array into a contiguous array, otherwise it will return a view of the original (contiguous) array.

**Comment by suiyuan2009** [comment]
maybe the most straightforward way is modifying the source code of class `Buffer`, then rebuild tensorflow. I didn't find the private API to cast `TF_Tensor*` to `tensorflow::Tensor` that @mrry mentioned in [this stackoverflow post](http://stackoverflow.com/questions/39379747/import-opencv-mat-into-c-tensorflow-without-copying), create a `TensorBuffer` using C api then pass it to the constructor of the class `tensorflow::Tensor`?

**Comment by byronyi** [comment]
@yaroslavvb Thanks for the reference you pointed to! Really helpful to what I am looking for. 

But to this issue per se, I guess parsing in a multi-node context is not exactly what the owner of this issue referred to. 

So currently there is no way to construct a tensor by moving an existing pointer? How about construct a tensor with empty underlying storage and take that storage for your own use, and give it back to TF? 

`Allocator` is such a monolithic runtime so I guess it has to take control over the details of memory allocation, for example, alignment, similar to what `malloc`/`free` does. As it is simply not a good idea to glibc `free` a chunk of memory returned by another memory allocation library, say `jemalloc`.

**Comment by yaroslavvb** [comment]
cc @michaelisard 

@byronyi I'm not away of any way of doing that.

Having TensorFlow allocate the memory buffer and provide the pointer seems safer because TensorFlow could make sure memory is aligned.

This would be useful because one could initialize numpy array based on pre-allocated memory as described [here](http://blog.enthought.com/python/numpy/simplified-creation-of-numpy-arrays-from-pre-allocated-memory/#.WMwNwRIrJE4) and this would reduce memory transfers. (ie PyTorch reuses memory between Tensor and numpy array objects)

**Comment by suiyuan2009** [comment]
@byronyi there is a class [TF_ManagedBuffer](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.cc#L119) derived from `TensorBuffer`, the `data_` field is public, you can directly construct a `TF_ManagedBuffer`, then use [TensorCApi::MakeTensor](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.cc#L475) to construct a Tensor. `TF_ManagedBuffer` need a deallocator function pointer for destruction use. There are also two functions [allocate_tensor](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.cc#L143) and [deallocate_buffer](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/c/c_api.cc#L154) which can give you a memory buffer from tensorflow's cpu allocator.

**Comment by byronyi** [comment]
@suiyuan2009 That piece of information is very helpful. Thank you!

**Comment by wujingyue** [comment]
TensorCApi::MakeTensor doesn't seem visible from client code today. However, you can probably avoid copying pre-allocated buffers to tensors with a customized Alocator. 
```
class FakeAllocator {
 public:
  FakeAllocator(void* buffer): buffer_(buffer) {}
  void* AllocateRaw(size_t alignment, size_t num_bytes) override { return buffer_; }
  void DeallocateRaw(void*) override {}

 private:
  void* buffer_ = nullptr;
};
```

**Comment by suiyuan2009** [comment]
I notice that `TF_ManagedBuffer` is only visible within `c_api.cc` file, using a `FakeAllocator` to construct a `TensorBuffer` is a good approach.

**Comment by wujingyue** [comment]
Caveat: AllocateRaw should check the alignment; otherwise, internal TensorFlow code may crash if the allocated memory is misaligned.

**Comment by bnurbekov** [comment]
@wujingyue Do you know how one should check for the alignment in Eigen::Tensor?

**Comment by wujingyue** [comment]
@bnurbekov https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/framework/allocator.h#L70

Eigen::Tensor has a larger alignment (maybe 512), but it doesn't matter as long as TF allocator is happy with the alignment of your buffer.

**Comment by harshini-gadige** [comment]
@ppries  Have you found a better way or a workaround for this ? If so, I can close this issue.

**Comment by ppries** [comment]
@harshini-gadige 

we are using memcpy for now, but might look into alternative ways of doing this – at some point we will have a need for pointing at data already on the gpu, but other problems are prioritized for now.

**Comment by harshini-gadige** [comment]
Ok. Closing this issue for now. Feel free to reopen if there any new suggestions.

**Comment by duduscript** [comment]
Hi @ppries , I have the same needs that pointing to data already on the gpu, do you have a solution?

**Comment by lsabc** [comment]
> Hi @ppries , I have the same needs that pointing to data already on the gpu, do you have a solution?

I have the same needs as well. Is there any solution? Thanks!

**Comment by duduscript** [comment]
Hi all, I solved this problem in my team, I am sorry that I can not post my code here now, but I can provide some information that may help you guys.

As T4 GPU only have about 15G device memory, in my team, each model is about 500M, we can only load 12-15 models per GPU for serving . To solve this, we want to make model hold in host memory , only when requests come, the model copy from host to deivce for serving. 

To get there, I change the constant op which holds GPU memory in graph_def to a custom op (MutableOp) to replace ConstantOp before loading the model .  And I create a global singleton object to get gpu address for each memory tensor before session run . MutableOp get tensor device address from this global singleton object in construct function .

**Comment by dirktheeng** [comment]
@duduscript I think everybody here would love to see the code for the "set tensor data address" pseudo line. please post a snippet of code.

**Comment by duduscript** [comment]
> @duduscript I think everybody here would love to see the code for the "set tensor data address" pseudo line. please post a snippet of code.

Hi @dirktheeng , I make this custom op(MutableOp) a friend of Tensor, so I just set tensor data membet in MutableOp::Compute

**Comment by dirktheeng** [comment]
@duduscript Thanks much.  I will give this a try.

**Comment by golden0080** [comment]
By looking at the code here in TF repo: https://github.com/tensorflow/tensorflow/blob/72d8f7ba27c1593e17a5fdc03dbe171bca23a88b/tensorflow/compiler/jit/xla_launch_util.h#L190

Looks like I could also implement a subclass of `TensorBuffer`, which only holds the piece of memory you want to pass to TF.
