### ISSUE TITLE
RNN weights aren't being restored on saver.restore calls

### ISSUE THREAD

**Issue by IoDmitri** [tensorflow/tensorflow#6970]
### Environment info
##Operating System:##
Ubuntu 16.04
##Installed version of CUDA and cuDNN: ##
Cuda 8.0,  CuDNN 5.1 
##tensorflow version##
0.12

### What other attempted solutions have you tried?
Not create the graph before using the model. 

### Logs or other output that would be helpful
[SO question](http://stackoverflow.com/questions/41737918/word-embeddings-change-between-sessions-even-if-saved)

**Comment by asimshankar** [comment]
Please avoid crossposting from stackoverflow. We try to keep the github issues list focused on bugs and feature requests and all other questions are better left on stackoverflow.

Taking a cursory look though, it's hard to determine whether this is a bug or not since it depends on what is happening in `self._maybe_initialize()` etc., which might be reinitializing the embeddings on each run. If you do really suspect a bug, please do file an issue with all the information asked for in the "New Issue" template, including a way to reproduce the error, ideally with as little code beyond what is necessary to reproduce it.

Apologies if I'm coming across as a bit terse, that's not the intention. If you do suspect a bug, please do feel free to recreate an issue with instructions to reproduce it. Thanks!
