### ISSUE TITLE
Tensorboard: Please improve log-scale plots

### ISSUE THREAD

**Issue by untom** [tensorflow/tensorflow#7060]
Hi!

Tensorboard currently (version 0.12.1) has an option to plot graphs with a logarithmic log scale, but this functionality doesn't work well whenever plotting very small values (e.g. the ones that converge to zero, like loss values). For example, compare this plot in Tensorboard:

![tensorboard_logplot](https://cloud.githubusercontent.com/assets/3627551/22293860/8abcdc40-e311-11e6-9e70-0796a503afac.png)

With the exact same data plotted using matplotlib/pandas using `logy=True`:

    runs = sorted(os.listdir('tensorboard/logs/'))[:2]
    d = [pd.read_csv('http://127.0.0.1:6033/data/scalars?run=%s&tag=loss&format=csv' % r)['Value'] for r in runs]
    res = pd.DataFrame(d, index=runs).T
    res.plot(ax=ax, logy=True)

![matplotlib_logplot](https://cloud.githubusercontent.com/assets/3627551/22293890/9af8e568-e311-11e6-95ff-a803a39f5d27.png)

Clearly, the Tensorboard plot is much less informative (the "logarithmic plot" option doesn't do anything to improve the plot). It would be nice if Tensorboard could produce logarithmic plots similar to the ones in matplotlib.

**Comment by drpngx** [comment]
@dandelionmane a request for logy plot. Is that something that we would like that Tensorboard doesn't have?

**Comment by dandelionmane** [comment]
We currently use a "ModifiedLogScale" scale from Plottable.js. It's designed to revert to being a linear scale for values close to 0, so that it can be defined at y=0.

I can see that it's not working that well in this case. I also do want the plot to continue to be defined over the whole range of numbers, so that charts don't break if you toggle ito non values that intersect 0.

However, we could move the linearity convergence to be arbitrarily small... e.g. it reverts to linearity in the range 10^-8 to 0. going to mark it contributions welcome for now.

**Comment by wchargin** [comment]
> However, we could move the linearity convergence to be arbitrarily small... e.g. it reverts to linearity in the range 10^-8 to 0. going to mark it contributions welcome for now.

We could also see if we can only use this modified scale when in fact there are negative* values. If we could manage that, then I'd be quite happy regardless of what the behavior is when there are negative values. That is, if you asked for a log plot when you have negative values, that's kind of your fault, but other people shouldn't be affected.

(Sending zero to neginf is fine with me. Our plots already handle infinities well.)

In any case, I've migrated this to our new repository at https://github.com/tensorflow/tensorboard/issues/57. Please feel free to keep discussing or submit a PR there! :-)
