### ISSUE TITLE
Feature Request - support distributed Tensorflow on Sun Grid Engine job scheduler

### ISSUE THREAD

**Issue by stevendavis** [tensorflow/tensorflow#7068]
Sun Grid Engine is commonly used to schedule jobs on scientific computing clusters / supercomputers.  Please consider adding support for distributed Tensorflow on SGE.

**Comment by drpngx** [comment]
Thanks @stevendavis ! @jhseu FYI.

**Comment by martinwicke** [comment]
Sorry, I don't think we'll be able to support this. If you end up with a solution, we'd be happy to link to it from tensorflow.org.

**Comment by shoeffner** [comment]
@stevendavis We managed to run some models on the SGE, but it's tricky because you always run into walltimes and have to somehow handle them properly. Additionally the creation of the ClusterSpecs is not really trivial, as you submit to queues and not to hosts. But by making some tweaks you can actually do it.

I didn't have too much time to make some proper write up, but you can skim [https://github.com/shoeffner/ann3depth](https://github.com/shoeffner/ann3depth) for how we made it. Since it was a project for a university seminar, there's also a small [project report](https://github.com/shoeffner/ann3depth/tree/master/docs/documentation.md) which explains some of the code we used in [tools/grid](https://github.com/shoeffner/ann3depth/tree/master/tools/grid). Most of it is not really well designed, some scripts take input via stdin, others via arguments etc., but it should give you some ideas.

In short these are the important ideas:

- Open ports in your grid system. We had 5001 - 5007 available, you potentially just need one. Ask your admins about it.
- One "keepalive" job which first checks what machines are available and distributes the workload to submit to hosts (This can be heavily improved but was enough for our proof of concept). The keepalive job is submitted by you, it will submit all jobs for worker and ps nodes.
- The keepalive job checks if the jobs are still running and if not, resubmits the whole lot (this turned out to be easier than submitting individual jobs). It also restarts the whole things before it hits its own walltime.
- With the `-notify` flag you can let the SGE send USR1/USR2 signals to your jobs before they get killed. This gives you a window to store a checkpoint right before the walltime is reached. Unfortunately, as in our setup, the SGE can be configured to not send those signals. Then your best bet is to use ALRM signals which erupt before the walltimes are hit. We used a hook ([src/tfhelper.py#L160-L189](https://github.com/shoeffner/ann3depth/blob/1789366bbc7cd97bd70839bc5cff2db1e13e2a5d/src/tfhelper.py#L160-L189)) to handle this.
- Save checkpoints every now and then, your jobs can fail to various reasons (sometimes shells were not found, sometimes some higher priority jobs can kill your job, even people running processes locally on machines without using the SGE resource manage can occur quite often and are troublesome).

What you have to keep in mind is that the SGE is there to distribute computation time on specialized systems among several users for a fair sharing of resources. TensorFlow is not really designed for this use case, it suits designs using containerization where you can assume (almost) infinite computation power and resources. This makes things very tricky.

**Comment by albertz** [comment]
@shoeffner Your scripts assume that there are enough available nodes in the SGE cluster, right? So if there are not enough, I guess it would break? Have you thought about queuing it all together, so that when it gets scheduled, you will get all the requested amount of nodes and resources? I'm currently looking into this. I think this probably can be done via the SGE parallel environment mechanism (see manpage sge_pe). I have seen OpenMPI setups using this `-pe` option.

**Comment by shoeffner** [comment]
My scripts even rely on the exact hosts being available, so the situation gets worse.
I though about job/task arrays, but it is fairly difficult to have distinguishable tasks in a way that the keepalive, as I was using it, can figure that out.
An alternative approach, which I did not implement, might be better suited for that: submit to random machines, let them register to a (known) chief machine and build the cluster from there.

I am looking forward to seeing your solutions.

NB: Don't use the pe option like that. It is there to access single machines with multiple CPUs, which might be useful for tensorflow, but is not necessarily needed. But that's why mp projects use it, they rely on multiple CPU cores. Instead, have a look at job arrays.

**Comment by roblalonde** [comment]
Here is a blog post that was recently done by Univa that outlines an example approach to integrating distributed TensorFlow to a Grid Engine Parallel Environment.  Hope this helps. Feedback and questions very welcome.

https://blogs.univa.com/2018/04/integrating-distributed-tensorflow-with-grid-engine/
