### ISSUE TITLE
Mistakes in docs of tf.range

### ISSUE THREAD

**Issue by alquraishi** [tensorflow/tensorflow#707]
The `limit` argument doesn't have a default value of `None`, and the `start` argument does have a default value of `0`. As specified, the header part of the doc reads: `tf.range(start, limit=None, delta=1, name='range')`, which is misleading and incorrect for something like `tf.range(5)`.

**Comment by vrv** [comment]
Do you want to send us a fix to the docs?

**Comment by alquraishi** [comment]
Sure, although I'm not currently set up so it'll probably take a little bit of time.

**Comment by martinwicke** [comment]
This is an odd one -- we're mimicking python's range behavior, which is hard to properly encode in python because overloading doesn't exist. The docs for python's range say:

range(stop)
range(start, stop[, step])

and the docs for tf.range are pretty clear what it does. The fact that the signature itself is misleading is unfortunate, but somewhat out of our control.

**Comment by alquraishi** [comment]
i see your point. This is pretty confusing though. Are the signatures autogenerated? If not one possibility is to write it out to mirror the semantics, even though it won't be correct python code. I.e. `tf.range(start=0, limit, delta=1, name='range')`, and then just spell it out in the docs that that is the behavior that's effectively achieved, even though it's actually implemented differently in python.

Alternatively maybe say something explicitly in the docs about this caveat? My confusion arose from scanning the signature of the function and thinking it made no sense. Obviously when I read the text the semantics became clearer, but a note explaining the caveat with the signature would be helpful.

**Comment by martinwicke** [comment]
The signatures in the docs are taken directly from the code by the doc
generator.

**Comment by jowagner** [comment]
While not everybody reads all the way to the "Args" section that explains it, most users will read the first paragraphs up to the example. It should therefore be sufficient to more precisely state the behaviour in the sentence starting "Like the Python builtin": Instead of wrongly saying that start defaults to 0, say what really happens, similarly to what you say in the "Args" section for "limit".

I am sorry I have to express my suggestion carefully to not include any phrase that could be part of a solution. This is because I cannot sign Google's contributor licence agreement at this time and from my past experience providing concrete solutions without the CLA is counterproductive. Presumably, developers with CLA fear that any solution they come up with might be too similar to my solutions and therefore decide do not fix the respective issues at all.
