### ISSUE TITLE
CPU performance issue, desynchronized cores

### ISSUE THREAD

**Issue by BogdanRuzh** [tensorflow/tensorflow#7098]
From time to time I have 600% CPU utilization and great performance while feeding batches into my model. But after few minutes, or even hours, CPU stuck on near 100% and everything becomes too slow. 
While it's 600% utilization, CPU History shows great synchronization between all my cores. After it degraded, it seems like desynchronization.

I use CPU only for input pipeline, reading data from SSD.
Ubuntu 16.04, CPU intel, Nvidia GTX cards, and a lot of free RAM memory.

While 600% utilization:
![x89pjcplace](https://cloud.githubusercontent.com/assets/20704139/22349682/624501c6-e419-11e6-97c4-e425a35d975e.jpg)

While 100% :
![image](https://cloud.githubusercontent.com/assets/20704139/22349731/a898b14a-e419-11e6-9c55-5c34fb226efd.png)

/proc/sys/vm/drop_caches doesn't solve my problem

**Comment by yaroslavvb** [comment]
Have you tried using tcmalloc, or jemalloc (jemalloc comes in the nightly version of TF)

If tcmalloc doesn't help, it sounds like you have a bottleneck in your computation. Your "desynchronization" is probably due to some stage being slow, so now the CPU intensive stage now only gets enough work to occupy one CPU

For some examples of debugging inefficient pipelines: https://github.com/tensorflow/tensorflow/issues/6845
https://github.com/tensorflow/tensorflow/issues/3009

**Comment by drpngx** [comment]
Could you try what @yaroslavvb suggests? It's a bit hard to tell without more information.

**Comment by BogdanRuzh** [comment]
Thanks for a help. I need some time to investigate my pipeline and testing tcmalloc/jemalloc.

**Comment by BogdanRuzh** [comment]
I found my bottleneck and it was summary.histogram on weights of a heavy dense layer. So I would just increase step for summary saving.
Thanks for a fast support.

**Comment by drpngx** [comment]
Great to hear!

@dandelionmane FYI
