### ISSUE TITLE
[Java] [Feature] Load from SavedModel

### ISSUE THREAD

**Issue by EronWright** [tensorflow/tensorflow#7134]
Make it possible for the Java library to load exported TF models in SavedModel format.   

Outline of the proposed design:
1. Define a new class `SavedModelBundle` to represent the loaded saved model.  Properties include the graph, session, and metagraphdef.
2. Define a static method on `SavedModelBundle` to load from disk, given an export path and some tags.

```
class SavedModelBundle implements AutoCloseable { 
  public Graph graph() { ... }
  public Session session() { ... }
  public byte[] metaGraphDef() { ... }
  public void close() { /* close the session and graph */ }
  public static SavedModelBundle loadSavedModel(String exportDir, Set<String> tags) { ... }
}
```

3. Write a JNI method to support loading, based on `TF_LoadSessionFromSavedModel` from the C API.

**Comment by EronWright** [comment]
Here's a WIP - do tell if there's any objections to the approach, otherwise I'll write some tests and submit.
https://github.com/cookieai/tensorflow/commit/64360fc51bd5ce48b06f52901e032313b68dfacd

**Comment by asimshankar** [comment]
@jhseu : Weren't you looking into this? Is @EronWright 's plan above in sync with yours?

**Comment by jhseu** [comment]
Ah, yeah, I was going to do it last week but illness prevented me. Seems like it saved me some time :)

@EronWright happy to review the pull request when you think it's ready.

**Comment by jhseu** [comment]
@EronWright some feedback on the code: I was imagining we'd use a static factory method on the Session class. Is there a reason to make a new SavedModelBundle class instead (note that the C++ equivalent isn't ideal and may change)?

Something like:
`public static Session loadSavedModel(String/Path path)` with a variant that also retrieves the metagraphdef.

**Comment by EronWright** [comment]
@jhseu I thought that too but it didn't work in practice.   `TF_LoadSessionFromSavedModel` produces both a session and a graph that the caller takes ownership of.   The session never takes ownership of the graph.   Meanwhile, the JNI method may produce only a single return value.   All together, a `SavedModelBundle`  was the obvious solution.

Regarding the `metagraphdef`, a saved model is not very useful without it because it contains the `signaturedef`s.

**Comment by Enet4** [comment]
That looks like a good approach to the issue. Is there any part of the implementation still missing in https://github.com/cookieai/tensorflow/commit/64360fc51bd5ce48b06f52901e032313b68dfacd, or just the tests? :)

**Comment by EronWright** [comment]
@Enet4 thanks, and feel free to try the updated patch posted above.

**Comment by nirajpatel** [comment]
@EronWright @Enet4 as the documentation is a bit lacking...

I am trying to use `SavedModel` like so:

`SavedModelBundle.load("/path/to/directory");`

but am getting an `UnsatisfiedLinkError`. My directory contains the following files which were saved using the `saver.save` python API: https://puu.sh/uC4fq/ad18591acb.png.

Am I using `SavedModel` incorrectly? I will add some documentation after I figure out what the issue is here! Thanks in advance.

**Comment by Enet4** [comment]
@nirajpatel My hunch would be that the JVM is failing to link with the native library. What is the message carried by that exception?

But there is one more thing you need to fix, though. You should use the [saved_model](https://www.tensorflow.org/api_docs/python/tf/saved_model) API for the saved model functionality, not `tf.train.Saver`. Although the formats for checkpoints and saved models share several similarities, I don't believe they're interchangeable.

**Comment by nirajpatel** [comment]
@Enet4 thank you for replying!

The exception I am seeing is:
```
java.lang.UnsatisfiedLinkError: org.tensorflow.SavedModelBundle.load(Ljava/lang/String;[Ljava/lang/String;[B)Lorg/tensorflow/SavedModelBundle;
	at org.tensorflow.SavedModelBundle.load(Native Method)
	at org.tensorflow.SavedModelBundle.load(SavedModelBundle.java:37)
```

I was originally seeing this because I didn't link to the native library but I am running with the JNI I believe:

(VM Options)[https://puu.sh/uCGut/c04c641b11.png]
(Project Structure)[https://puu.sh/uCGwE/ba35337d9c.png]

> But there is one more thing you need to fix, though. You should use the saved_model API for the saved model functionality, not tf.train.Saver

Ah! That would explain it. Is the `saved_model` API newer or preferred to `tf.train.Saver`?

**Comment by Enet4** [comment]
> Ah! That would explain it. Is the saved_model API newer or preferred to tf.train.Saver?

The `saved_model` API is more recent, but to my understanding, it does not invalidate the other one. If you want to save the graph and all its variables for use in other programs and tools, for a variety of purposes (serving, fine-tuning, etc.), `saved_model` is more indicated. To keep checkpoints of the training process, using `tf.train.Saver` is more appropriate since it also allows you to specify a global step and the maximum number of checkpoints to keep.

As for the message, I cannot tell for sure why that happens. It might be that you are still using the jni dynamic library from a previous version of TensorFlow.

**Comment by nirajpatel** [comment]
Good point @Enet4! I am using the **PREVIEW1** JNI but I compiled from source in order to get the latest changes (including this one). Is there currently a way to build the JNI from source? The only option I see in the readme is https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java#quickstart step number 2.

> The saved_model API is more recent, but to my understanding, it does not invalidate the other one.

This makes sense! I will start using `saved_model`.

**Comment by nirajpatel** [comment]
Nevermind, the JNI is in my build directory! I will use that. I really appeciate the help @Enet4. Thank you. I will send a PR to update the readme soon.
