### ISSUE TITLE
AttributeError: 'module' object has no attribute 'constant'

### ISSUE THREAD

**Issue by calvin-is-seksy** [tensorflow/tensorflow#7157]
I've just installed tensorflow (without the gpu) on my mac, through my virtual environment. I initially had tensorflow downloaded in my ~/ directory, but then found that I could not import it at all in python3.4. I found that I fixed this by making a copy of the tensorflow directory in my working directory fixed that. But now the problem is that once I import tensorflow with $ import tensorflow as tf, I get the message: 

`>>> a = tf.constant('Hello')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'constant'`

**Comment by chestnut3108** [comment]
Maybe there is a script named Tensorflow left on your system which is getting referenced instead of the Tensorflow package...so check it and rename it

**Comment by vrv** [comment]
Indeed, try a clean install and make sure you have activated the proper virtualenv, and there are no other installs of tensorflow or directories anywhere else.  

This is a question more suited for StackOverflow, so please consider posting it there and tagging 'tensorflow'

**Comment by betelgeuseMsi** [comment]
I installed tensorflow from Source had the same problem. I noticed that while executing the command "sudo pip install /tmp/tensorflow_pkg/tensorflow-1.5.0-py2-none-any.whl", I was executing it by copying and pasting it directly which was wrong because the term "tensorflow-1.5.0-py2-none-any.whl" need to be replaced with the right name of the .whl file. First time running it gave some error but when I ran it again, it worked like a charm. You can find it in location /tmp/tensorflow_pkg. Just putting it here hoping it would save someone else's load of time.
