### ISSUE TITLE
Tensorflow restore doesn't work on AWS

### ISSUE THREAD

**Issue by yonatanaol** [tensorflow/tensorflow#7159]
I am running a script that perfectly works on ubuntu 14.04, docker over ubuntu 14.04, docker over MAC OS - but doesn't work on ubuntu 16 on AWS.
the script is:

```
import tensorflow as tf
import os

def load_model_to_session(session, model_dir, meta_file, ckpt_file):
    model_dir_exp = os.path.expanduser(model_dir)
    saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file))
    saver.restore(session, os.path.join(model_dir_exp, ckpt_file))

session = tf.Session()
print ('loading models')
model_dir = '/data/model'
meta_file, ckpt_file = 'a.meta', 'a.ckpt'
print ('ckpt file ' + ckpt_file)
load_model_to_session(session, model_dir, meta_file, ckpt_file)
print ('finish loading the model')
session.close()

`````

the errors i get:

> W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file /data/model/a.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
> W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /data/model/a.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
> W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /data/model/a.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
> W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file /data/model/a.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
> W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /data/model/a.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
> W tensorflow/core/framework/op_kernel.cc:975] Data loss: Unable to open table file /data/model/a.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
> Traceback (most recent call last):
>   File "/tmp/runner.py", line 35, in <module>
>     load_model_to_session(session, model_dir, meta_file, ckpt_file)
>   File "/tmp/runner.py", line 7, in load_model_to_session
>     saver.restore(session, os.path.join(model_dir_exp, ckpt_file))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1388, in restore
>     {self.saver_def.filename_tensor_name: save_path})
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
>     run_metadata_ptr)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
>     feed_dict_string, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
>     target_list, options, run_metadata)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
>     raise type(e)(node_def, op, message)
> tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /data/model/a.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
>          [[Node: save/restore_slice_318 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_318/tensor_name, save/restore_slice_318/shape_and_slice)]]
> 
> Caused by op u'save/restore_slice_318', defined at:
>   File "/tmp/runner.py", line 35, in <module>
>     load_model_to_session(session, model_dir, meta_file, ckpt_file)
>   File "/tmp/runner.py", line 6, in load_model_to_session
>     saver = tf.train.import_meta_graph(os.path.join(model_dir_exp, meta_file))
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1526, in import_meta_graph
>     **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/meta_graph.py", line 502, in import_scoped_meta_graph
>     producer_op_list=producer_op_list)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/importer.py", line 285, in import_graph_def
>     op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
>     original_op=self._default_original_op, op_def=op_def)
>   File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
>     self._traceback = _extract_stack()
> 
> DataLossError (see above for traceback): Unable to open table file /data/model/a.ckpt: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
>          [[Node: save/restore_slice_318 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice_318/tensor_name, save/restore_slice_318/shape_and_slice)]]
> 

in order to reproduce this, you can use the pre-trained open source model here:
https://drive.google.com/file/d/0B5MzpY9kBtDVSTgxX25ZQzNTMGc/view

I'm using tensorflow (python) 0.12.1 .

I suspect that it has something to do with the virtualization (AWS).

BTW, the code works on the pretrained model http://download.tensorflow.org/models/inception_v1_2016_08_28.tar.gz

**Comment by yonatanaol** [comment]
related (unanswered yet) stackoverflow question - http://stackoverflow.com/questions/41958096/cannot-load-checkpoint-file

**Comment by yonatanaol** [comment]
seems like a currepted file

**Comment by hakimka** [comment]
I have the similar issue on AWS

### simple code to create/save a model
import tensorflow as tf
import sys
import numpy as np


w1 =  tf.Variable(tf.random_normal((2,2)), name="w1")
w2 =  tf.Variable(tf.random_normal((2,2)), name="w2")
b1 =  tf.Variable(tf.random_uniform([2],0,100, dtype = tf.int32, seed = 10), name="b1")
b2 =  tf.Variable(tf.random_uniform([2],0,100, dtype = tf.int32, seed = 1), name="b2")

saver = tf.train.Saver()
sess = tf.Session()
sess.run(tf.initialize_all_variables())

print sess.run(w1)
print sess.run(w2)
print sess.run(b1)
print sess.run(b2)

saver.save(sess, 'modW1W2')
sess.close()

### a simple script to restore
import tensorflow as tf
import sys
import numpy as np

w1 =  tf.Variable(tf.zeros((2,2)), name="w1")
w2 =  tf.Variable(tf.zeros((2,2)), name="w2")
b1 =  tf.Variable(tf.zeros(2), name="b1")
b2 =  tf.Variable(tf.zeros(2), name="b2")

model_saver = tf.train.Saver()
with tf.Session() as session:
    model_saver.restore(session, 'modW1W2.meta')
    print("Model restored.") 
    print('Initialized')


=======================================

### The error I am getting

DataLossErrorTraceback (most recent call last)
<ipython-input-1-e2eb1ef816ae> in <module>()
     12 model_saver = tf.train.Saver()
     13 with tf.Session() as session:
---> 14     model_saver.restore(session, 'modW1W2.meta')
     15     print("Model restored.")
     16     print('Initialized')

/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in restore(self, sess, save_path)
   1343 
   1344     sess.run(self.saver_def.restore_op_name,
-> 1345              {self.saver_def.filename_tensor_name: save_path})
   1346 
   1347   @staticmethod

/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    715     try:
    716       result = self._run(None, fetches, feed_dict, options_ptr,
--> 717                          run_metadata_ptr)
    718       if run_metadata:
    719         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    913     if final_fetches or final_targets:
    914       results = self._do_run(handle, final_targets, final_fetches,
--> 915                              feed_dict_string, options, run_metadata)
    916     else:
    917       results = []

/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
    963     if handle is None:
    964       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
--> 965                            target_list, options, run_metadata)
    966     else:
    967       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
    983         except KeyError:
    984           pass
--> 985       raise type(e)(node_def, op, message)
    986 
    987   def _extend_graph(self):

DataLossError: Unable to open table file modW1W2.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice/tensor_name, save/restore_slice/shape_and_slice)]]
	 [[Node: save/restore_slice_2/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_21_save/restore_slice_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/restore_slice', defined at:
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/ubuntu/tensorflow/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2821, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-e2eb1ef816ae>", line 12, in <module>
    model_saver = tf.train.Saver()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 986, in __init__
    self.build()
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1015, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 620, in build
    restore_sequentially, reshape)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 357, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 270, in restore_op
    preferred_shard=preferred_shard))
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/io_ops.py", line 204, in _restore_slice
    preferred_shard, name=name)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/ubuntu/tensorflow/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()

DataLossError (see above for traceback): Unable to open table file modW1W2.meta: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[Node: save/restore_slice = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/restore_slice/tensor_name, save/restore_slice/shape_and_slice)]]
	 [[Node: save/restore_slice_2/_7 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_21_save/restore_slice_2", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

**Comment by yaroslavvb** [comment]
Are you using version 12.1 by chance? That version provided new format for saving checkpoints, but didn't provide a way to read them. The solution is to save in old format:

`saver = tf.train.Saver(write_version = saver_pb2.SaverDef.V1)`

see: http://stackoverflow.com/questions/41048819/how-to-restore-a-model-by-filename-in-tensorflow-r12

**Comment by hakimka** [comment]
Hello Yaroslav,


I just check the version, it says


print tf.__version__

0.11.0rc2


I am using the tensorflow in iPython notebook setup.



By the way, I found this example

http://stackoverflow.com/questions/33759623/tensorflow-how-to-restore-a-previously-saved-model-python
I believe you answered that question at some point.



These lines run ok


w1 = tf.Variable(tf.truncated_normal(shape=[10]), name='w1')
w2 = tf.Variable(tf.truncated_normal(shape=[20]), name='w2')
tf.add_to_collection('vars', w1)
tf.add_to_collection('vars', w2)
saver = tf.train.Saver()
sess = tf.Session()
#sess.run(tf.global_variables_initializer()) <--- I had to comment this out
sess.run(tf.initialize_all_variables())
saver.save(sess, 'my-model')


But my simple, as primitive as I could get on it, would give me trouble. I am still learning the TF and I am not sure I am doing something obviously wrong.


Thank you,

Спасибо



Hakim



________________________________

**Comment by marcunzueta** [comment]
Hello @hakimka 

I had a very similar problem while trying to restore a trained DNN, which was trained in an AWS instance. I found that the tensorflow version that was installed in the AMI I was launching, was 0.12.1, while the version I have installed in my local computer, where I was trying to restore the trained DNN was 1.5.0.

I update the tensorflow to 1.5.0 in the AWS instance AMI, re-trained, saved again, and then I was able to restore the trained DNN successfully. Check that the NN you are trying to restore was saved in the same version as your computer. It worked for me.
