### ISSUE TITLE
TFlite: GPU delegate: ability to limit amount of GPU memory used by TFlite?

### ISSUE THREAD

**Issue by andy-tai** [tensorflow/tensorflow#71838]
Tensorflow can impose a limit on the amount of memory used by Tensorflow on a GPU:

tf.config.LogicalDeviceConfiguration(memory_limit=1024)]

Is it possible to have similar functionality for TFlite on GPU? 

Thanks

**Comment by pkgoogle** [comment]
Hi @andy-tai,

Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress [here](https://github.com/google-ai-edge/LiteRT/issues/271).

Let us know if you have any questions. Thanks.
