### ISSUE TITLE
Why I can't install tensorflow-text2.13.0

### ISSUE THREAD

**Issue by libofei2004** [tensorflow/tensorflow#72259]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

source

### TensorFlow version

tf2.8

### Custom code

No

### OS platform and distribution

windows11

### Python version

3.9.13

### Current behavior?

When I intall tensorflow-text by pip install tensorflow-text==2.13.0, it's failed:
ERROR: Could not find a version that satisfies the requirement tensorflow-text==2.13.0 (from versions: 2.5.0, 2.6.0rc0, 2.6.0, 2.7.0rc0, 2.7.0rc1, 2.7.3, 2.8.0rc0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0, 2.10.0b2, 2.10.0rc0, 2.10.0)
ERROR: No matching distribution found for tensorflow-text==2.13.0
But In page https://pypi.org/project/tensorflow-text/2.13.0/, 2.13.0 is indeed exits, why I can't install it?

### Standalone code to reproduce the issue

```shell
pip install tensorflow-text==2.13.0
```

**Comment by tilakrayal** [comment]
@libofei2004,
After version 2.10, we will only be providing pip packages for Linux x86_64 and Intel-based Macs. For other systems like Windows, Aarch64, and Apple Macs, TensorFlow relies on [build collaborators](https://blog.tensorflow.org/2022/09/announcing-tensorflow-official-build-collaborators.html), and so we will not be providing packages for them. However, we will continue to accept PRs to make building for these OSs easy for users, and will try to point to community efforts related to them.

https://github.com/tensorflow/text/blob/master/README.md#a-note-about-different-operating-system-packages

https://github.com/tensorflow/tensorflow/issues/67465

Also this issue is related to tensorflow-text, so could you please raise the concern on the respected [repo](https://github.com/tensorflow/text/issues/) or the contribute with the PR for the quick resolution. 

Please try to install using WSL/WSL2. Thank you!

**Comment by libofei2004** [comment]
@tilakrayal I find I can't install  mediapipe_model_maker version >0.1.0.1 in windows. I think the reason is some lib like tensorflow-text，tf-models-official do not have a greater windows version. Am I right? Can mediapipe_model_maker be installed with a version greater than 0.1.0.1 on Windows？

**Comment by libofei2004** [comment]
@mihaimaruseac my Python  version is 3.9.13. My operating system is windows 10. I can't install mediapipe_model_maker 0.2.1.4 in windows , I think the reason is some libs like  tensorflow-text，tf-models-official do not have a greater windows version.

**Comment by mihaimaruseac** [comment]
Yes, there is no support for Windows on TF-text. So you'd have to downgrade to an earlier version, or try to use WSL (on Windows) or a cloud/Colab host (Linux).
