### ISSUE TITLE
Feature Request : Latent Dirichlet Allocation impementation using tensorflow(skflow)

### ISSUE THREAD

**Issue by mahatosourav91** [tensorflow/tensorflow#7281]
I am trying to Topic Modelling (LDA) using tensorflow. But I could find any existing LDA implementation in TF learn (skflow) package. 

Is there any other way to implement Topic Modelling using tensorflow?

It would be helpful if LDA support is given in TF Learn (skflow) similar to the scikit-learn Latent Dirichlet Implementation.

**Comment by girving** [comment]
LDA is probably not in scope for `tf.learn`, but I'll wait for @ilblackdragon to comment.

**Comment by mahatosourav91** [comment]
Even if there is any suitable example / implementation of LDA using tensorflow , it would be very helpful

**Comment by gusdoe** [comment]
Since Keras model can be constructed in Tensorflow, you can refer Matthew Honnibal's keras model in below gihub repository:
https://github.com/explosion/spaCy

**Comment by ilblackdragon** [comment]
@gusdoe if you are talking about [https://github.com/explosion/spaCy/blob/a5538d93d0cf00cdaa4ca0f61dd08cc817af8e0e/examples/deep_learning_keras.py](this keras model) - it's not LDA, but LSTM model for sentiment analysis [which we have examples in TF/TF.Learn].

@mahatosourav91 Probably the answer is late, I haven't seen implementation for TF.
Here is implementation in Python that one can convert into TF: https://github.com/hannawallach/python-lda/blob/master/src/lda.py

One of the main issues is that TF likes to operate in batches, but LDA is mostly done on the whole corpus at the same time. If you corpus-level optimization, you can just implement the code from above in TF apis. Otherwise one need to play around to get it to work with batches.

@girving We would still accept a PR if somebody implemented a good version of LDA for TF.Learn and contributed it, wouldn't we?

**Comment by girving** [comment]
@ilblackdragon I think it might be a better fit for a separate repository or models.  As you say: if it's unbatched, it has a different API.  If it's batched, it's new research that we don't want to support in core yet.
