### ISSUE TITLE
Any reason to not publish wheels for Mac OS < 10.11.x on PyPI?

### ISSUE THREAD

**Issue by dwyatte** [tensorflow/tensorflow#7294]
The tensorflow wheels for Mac OS on PyPI are tagged with a platform of 10.11 and thus aren't picked up by pip on Mac OS 10.10.x or earlier. Google hosts wheels that work on any version of Mac OS (e.g., https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-0.12.1-py2-none-any.whl).

Can these be uploaded to PyPI or can a wheel be published there that supports older versions of Mac OS?

**Comment by yaroslavvb** [comment]
The infra team would need to setup older MacOS machines and test wheels in that environment, and fix/document "older MacOS/tensorflow" snags, before publishing an official wheel....how much impact would such releases have?

**Comment by gunan** [comment]
The pip package you linked is simply renamed to `none-any` to avoid any issues that may be caused by older pip versions. That is not actually built for older versions.
As @yaroslavvb pointed out, we wont be able to test the pip packages for older versions, and have as good support for it. This combined with Apple's policy of quickly sending updates to all devices as soon as possible, we decided to keep our official support close to the latest version of MacOS.

@dwyatte Does the above answer your question?

**Comment by dwyatte** [comment]
Helpful context -- thanks guys. Even if this is a "won't fix", it's useful to have it here in GitHub for others who experience the same issue.

Anyway, to answer @yaroslavvb's question about impact: I think this is pretty low impact. Most people using tensorflow seriously will be using it on Linux with a GPU. Of the small subset of Mac users, only a few will be on old versions of the OS.

As the project continues to mature, it might worth noting these OS requirements in the documentation, but the discussion here is a sufficient answer for me.
