### ISSUE TITLE
Feature Request: Official Docker base image with python 3.5 (and not only 3.4)

### ISSUE THREAD

**Issue by brando90** [tensorflow/tensorflow#7368]
I was building my Dockerfile for my docker image and when I ran containers, I noticed that python 3.4 was the one that was used. I installed python 3.5 successfully on the image but I was still unable to use tensorflow. Is it possible to request a base image that is always with the latest version of TensorFlow and also uses other version of pyhton 3? Like 3.5.

I am aware I can just pip install it directly, but that doesn't keep it up to date with the latest. A base image with python 3.5 seems the most appropriate answer.

### What related GitHub issues or StackOverflow threads have you found by searching the web for 
Related Stack Over Flow: http://stackoverflow.com/questions/42122826/can-one-use-python-3-5-in-a-docker-container-based-out-of-the-tensorflow-docker

### Environment info
Ubuntu/Linux and Mac OS X. 

### What other attempted solutions have you tried?
You can install python 3.5 here:

http://askubuntu.com/questions/682869/how-do-i-install-newer-python-versions-using-apt-get

and then fix pip and numpy with:

http://stackoverflow.com/questions/42122639/how-does-one-install-fix-a-failed-numpy-installation-that-works-on-python-3-4-bu/42124828?noredirect=1#comment71418540_42124828

and then one can directly install python 3.5 with pip:

export TF_BINARY_URL=https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.12.1-cp35-cp35m-linux_x86_64.whl
python3.5 -m pip install TF_BINARY_URL

(note pip3 will **not** work if all this is done in the docker container).

This should work but doesn't start from an official base image using python 3.5 and doesn't get the latest version of TensorFlow automatically.

**Comment by girving** [comment]
@caisq Is there a reason to not upgrade the docker?  3.5 would be backwards compatible with 3.4, right?

**Comment by gunan** [comment]
The primary reason for this is our docker images build on top of ubuntu 14.04. We are still at this version, because our base nvidia docker images (`cuda8 cudnn5`) are based off of ubuntu 14.04. So we kept all our docker images at the same ubuntu version to keep consistency. Unfortunately, ubuntu 14.04 only supports up to python 3.4.

We can install python as you described, but we decided to stay with officially supported version to avoid any unprecedented issues non-offical packages may cause. 

We will soon be exploring upgrading all our dockerfiles to latest ubuntu LTS version, which will allow us to upgrade python. Sorry for the inconvenience this delay may have caused.

**Comment by caisq** [comment]
As @jhseu recently pointed out, cuda 8 is now based on ubuntu:16.04. So this old roadblock doesn't exist anymore. We'll confirm that everything else is okay and if so, go ahead with the Python version update in the py3 docker images.

**Comment by brando90** [comment]
cool, so when will this be solved? Just curious.

**Comment by caisq** [comment]
This is resolved. nightly py3 images pushed onto Docker Hub (https://hub.docker.com/r/tensorflow/tensorflow/tags/) are already based on ubuntu 16.04 and Python 3.5.
