### ISSUE TITLE
App Storage Size Increases with CoreML or Metal Usage on iOS

### ISSUE THREAD

**Issue by leoull** [tensorflow/tensorflow#73800]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

0.0.1-nightly

### Custom code

No

### OS platform and distribution

iPhone 17.5.1

### Mobile device

iPhone 13 mini

### Current behavior?

I'm encountering an issue where the app's storage size increases each time an AI model is loaded, and the storage doesn't decrease afterward. Specifically, I'm using the [PoseNet TensorFlow Lite model on iPhone](https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/ios) to demonstrate the problem.

for more detail checkout  [this StackOverflow Post](https://stackoverflow.com/questions/78872138/app-storage-size-increases-with-coreml-or-metal-usage-on-ios)

### Standalone code to reproduce the issue

```md
Run the [TensorFlow Lite Pose Estimation iOS Demo](https://github.com/tensorflow/examples/tree/master/lite/examples/pose_estimation/ios#tensorflow-lite-pose-estimation-ios-demo) using `Metal` or `CoreML`, and you'll notice the app's storage size increasing each time the pose detection model is executed.
```

**Comment by pkgoogle** [comment]
Need a real device to test this. @yishuangP can you please take a look? Thanks.

**Comment by leoull** [comment]
I got reply on Apple's Developer Forum: [CoreML - doUnloadModel:options:qos:error](https://developer.apple.com/forums/thread/768367?login=true)

looks like the issue is with tflite's coreML delegate implementation. I don't know much about this stuff, but the issue is probably here: [coreml_executor.mm](https://github.com/tensorflow/tensorflow/blob/8a3c6ad49d51857cc7ebda10ee93332f16f719ff/tensorflow/lite/delegates/coreml/coreml_executor.mm)

**Comment by gaikwadrahul8** [comment]
Hi, @leoull 
Thanks for raising this issue. Are you aware of the migration to [LiteRT](https://developers.googleblog.com/en/tensorflow-lite-is-now-litert/)? This transition is aimed at enhancing our project's capabilities and providing improved support and focus for our users. As we believe this issue is still relevant to LiteRT we are moving your issue there. Please follow progress here: https://github.com/google-ai-edge/LiteRT/issues/40

Let us know if you have any questions. Thanks.
