### ISSUE TITLE
Add Continuous Integration + Review Requirements to CONTRIBUTING.md

### ISSUE THREAD

**Issue by ahundt** [tensorflow/tensorflow#7443]
Could some basic instructions and suggestions be added to [CONTRIBUTING.md](
https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md)?

Example notes to add:
 - correctly installing and configuring a compliant python/C++ linter
 - links and explanation of other guidelines that must be followed
 - how to run tests on your own machine

**Comment by yaroslavvb** [comment]
I agree that it would be useful to community. I think perhaps someone who has recently gone through the process might be motivated to put the important things together into a nice guide.

Some snippets from my development notes:

making a PR: https://gist.github.com/yaroslavvb/bdb0a92f2a516ebbe2d386c48f5e2c45

pylint:

```
wget -O /tmp/pylintrc https://raw.githubusercontent.com/tensorflow/tensorflow/master/tensorflow/tools/ci_build/pylintrc
pylint tensorflow/get_string_ops.py --rcfile=/tmp/pylintrc
```

Running tests:

You can see requirements in tensorflow/tools/ci_build/install/install_pip_packages.sh

Most recently this meant doing this

```
pip install -I --upgrade setuptools
pip install portpicker
pip install mock
pip install pep8
pip install pylint
pip install py-cpuinfo
pip install pandas==0.18.1
pip install wheel
pip install --upgrade six==1.10.0
pip install --upgrade werkzeug==0.11.10
pip install --upgrade protobuf==3.0.0

```

Then on Ubuntu:
```
export LD_LIBRARY_PATH="/usr/local/cuda/lib64:/usr/local/cuda/extras/CUPTI/lib64:$LD_LIBRARY_PATH"

export flags="--config=opt --config=cuda -k"
bazel test $flags //tensorflow/python/...
```

On MacOS: (bazel needs to be explicitly told to pass env vars for some reason)
```
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH=/usr/local/cuda/lib:/usr/local/cuda/extras/CUPTI/lib
export LD_LIBRARY_PATH=$DYLD_LIBRARY_PATH
export PATH=$DYLD_LIBRARY_PATH:$PATH

export flags="--config=cuda --config=opt -k --action_env PATH --action_env DYLD_LIBRARY_PATH --action_env LD_LIBRARY_PATH -k"
bazel test $flags //tensorflow/python/...
```

For changes to core framework
`bazel test $flags //tensorflow/...
`

Keeping flags in $flags is important because if you you forget a flag, and do `bazel run` or `bazel test` with a new setting, it'll start building everything from scratch, aka 20+ mins of machine being semi-unresponsive.

For long running tests, tmux is useful for provide robustness against disconnection/closing terminal:
```
tmux new -s bazel -n 0
bazel test //tensorflow/...

```
Also, this to keep bazel from wiping its state overnight 

`echo "startup --max_idle_secs=100000000"  > ~/.bazelrc
`

Also, some notes on general philosophy of contributions -- when you contribute something to TensorFlow, the maintenance burden is transferred to the Google TensorFlow team. This means that benefit of contribution must be compared against the cost of maintaining that feature until the heat death of universe.

Hence there are cases when you want to extend functionality of TensorFlow, while remaining the owner/maintainer of this extension. This can be done by keeping extra functionality in a separate repo and using TensorFlow API to bring it in during runtime. For instance, new kernels/ops can be added to TensorFlow using TensorFlow plugin mechanism (load_library)

**Comment by ahundt** [comment]
Awesome info! Since you mentioned tmux there is also http://byobu.co/ which is built on top of tmux and improves usability.

**Comment by aselle** [comment]
@ahundt, would you be willing to contribute a document to this effect? @gunan, do you have any other suggestions?

**Comment by gunan** [comment]
One quick way to contribute would be to use our devel dockerfiles.
But what is already mentioned sounds good to me.

**Comment by ahundt** [comment]
@aselle I don't know all the policies at the moment that's why I asked, heh

**Comment by yaroslavvb** [comment]
I've added a couple of things (buildifier, clang-format) to original reply. I'll keep merging in extra things I come across in there until there's a better place

**Comment by ahundt** [comment]
@yaroslavvb Could you just create a pull request directly adding the text to [CONTRIBUTING.md](CONTRIBUTING.md)?

Regarding the folder of docker files, some of those scripts do look fairly straightforward and could be referenced:
https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker

**Comment by caisq** [comment]
FYI, we are working on the suggested improvements to CONTRIBUTING.md and possibly the docker files as well.

**Comment by ahundt** [comment]
@vrv @caisq Thanks that guide looks super helpful!
