### ISSUE TITLE
error while building on windows with cuda 7.5

### ISSUE THREAD

**Issue by dremaker52** [tensorflow/tensorflow#7453]
I have spent days to build tensorflow on windows with cuda 7.5 but met a lot of error. I first followed https://github.com/tensorflow/tensorflow/tree/master/tensorflow/contrib/cmake/readme.md. I modified CmakeList.txt from cuda 8 to cuda 7.5. But nvcc version 7.5 do not support visual studio 2015. When I change to visual studio 2013. It failed with constexpr because visual studio 2013 do not support it. When I remove constexpr it got a lot of error of noexcept, uint16 and so on. So is it possible to build tensorflow with cuda 7.5? In a lot of cases, it's not possible to use cuda 8 . So can it be seen as a feature request to support cuda 7.5 on windows? Thanks.

**Comment by gunan** [comment]
Ill let @mrry @guschmue comment.
I think there is an incompatibility (due to the versions of visual studio they are compiled with) between cuda versions anything lower than 8 and python.

**Comment by guschmue** [comment]
With vs2015 only supporting the cuda toolkit 8.0 you'd need to use vs2013.
The c99 support in vs2013 was incomplete and tensorflow makes lots of use of c99. When we started porting tensorflow we used vs2015.update1 and even that was a royal pain to get things compile - lots of little things that required code changes. With vs2015.update3 all of this went away.
Maybe not impossible to get this to work but it would be very painful. The code changes itself would be somewhat hard to push back into the master because there would be lots of ifdef.
If you need 7.5 on the box and can't install the cuda 8.0 you could try to copy the cuda 8.0 dlls into a directory and make sure tensorflow finds that directory in the path before it finds 7.5 dlls. As long you have the latest nvidia driver I think this should work.

**Comment by dremaker52** [comment]
Thank you for your response, I will try copying dlls and update drivers.

**Comment by gunan** [comment]
I will close this issue with the explanation @guschmue provided (cannot use cuda 7.5 due to no c99 support in appropriate VS version).
