### ISSUE TITLE
Add support for custom queue runners

### ISSUE THREAD

**Issue by jimfleming** [tensorflow/tensorflow#7477]
I have a custom implementation of `QueueRunner` but right now TF complains when serializing:

> WARNING - tensorflow - Error encountered when serializing queue_runners.
> Type is unsupported, or the types of the items don't match field type in CollectionDef.
> unbound method to_proto() must be called with QueueRunner instance as first argument (got IteratorRunner instance instead)

The use case for the implementation is to take advantage of automatic thread starting from `Experiment`, `Supervisor`, `managed_session`, etc.

I could inherit from `QueueRunner` but a `QueueRunnerBase` would be ideal as much of the existing implementation assumes the use of `enqueue_ops`.

As an example, I have [`GeneratorRunner`](https://gist.github.com/jimfleming/d1118cc630f5c883223a4b4645cc2e7b) which runs a generator in a thread and enqueues the outputs. This is more flexible than the existing `QueueRunner` since it  supports placeholders with feed dictionaries.

**Comment by yaroslavvb** [comment]
@jimfleming do you have a solution in mind? (ie, is it an issue of an internal check being unnecessarily strict?)

**Comment by jimfleming** [comment]
That may be one issue and possibly a feature request for a `QueueRunnerBase` or for a more general thread runner. I haven't yet looked at what is involved with serialization so the check may be valid, in the case of my custom runner, particularly as it has not been tested in a distributed setting.

I'm open to suggestions for how to proceed and if a pull request is warranted I can put one together.

**Comment by yaroslavvb** [comment]
An alternative to "queuerunnerbase" is to implement it as new object and use duck typing to make it work with tensorflow serialization. The amount of stuff in QueueRunner is quite small, I'm not sure if it's worth using inheritance as opposed to "copy paste the needed bits"

**Comment by jimfleming** [comment]
I agree that it's quite small. It looks like [`add_queue_runner`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/queue_runner_impl.py#L365) and [`start_queue_runners`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/training/queue_runner_impl.py#L383) wouldn't be affected. [`QueueRunnerDef`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/protobuf/queue_runner.proto#L17) appears to expect a list of `enqueue_op_name` which breaks from my current use case as the generator performs the enqueue directly.

**Comment by yaroslavvb** [comment]
btw, things seem to be moving in the direction of single threaded stuff using "Hooks" ... not sure if there's a future for queue runners ... IE, instead of having multiple threads issuing run calls in parallel (and causing unreproducible memory errors when the scheduling gets unlucky), do everything in a sequence, see https://github.com/tensorflow/tensorflow/blob/4c192f060cf9ff897911d240c140299d6db257b6/tensorflow/python/training/basic_session_run_hooks.py

BTW, here's current existing code-base handles passing feed_dict to existing queue runners

https://github.com/tensorflow/tensorflow/blob/799e31f3840c21322e380e1ec6e5bacb95d016fa/tensorflow/contrib/learn/python/learn/learn_io/data_feeder_test.py

**Comment by yaroslavvb** [comment]
In particular, it seems "StreamingDataFeeder" is similar to your use case

https://github.com/tensorflow/tensorflow/blob/799e31f3840c21322e380e1ec6e5bacb95d016fa/tensorflow/contrib/learn/python/learn/learn_io/data_feeder.py#L549

**Comment by jimfleming** [comment]
Interesting. I agree that queue runners have their issues, especially wrt reproducibility. I'll look at using run hooks to replicate this without threads.

Something like `StreamingDataFeeder` seems to fit. It's not clear from the tests how it would be used with something like `Estimator`/`Experiment` which does not accept a `feed_dict`, but rather an `input_fn` which returns tensors fed by a queue. I guess I could combine with something like `FeedFnHook` but this feels hacky.

Since it sounds like queue runners are going away the original issue is no longer accurate. If this is moving towards a usage question of existing functionality I can file on SO.

**Comment by aselle** [comment]
@mrry, could you comment on this issue. I think we can close and move to SO based on discussion, but you should take a look. Thank you!

**Comment by mrry** [comment]
I'm not sure what's a possible action is here... or what the utility of a new class hierarchy would be. There's already a way to register serialization and deserialization functions for custom graph-collection objects using [`register_proto_function()`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/framework/ops.py#L4219), so perhaps you could use that? I don't think there's any additional magic we can bring for your `GeneratorRunner` since we don't have (AFAIK) a standard way to serialize a Python generator.

(As an aside, we're trying to find ways to reduce the need for queue runners, but they're in the API for 1.0, so they'll be around for a while but I doubt we'll invest much effort in improving them.)

**Comment by yaroslavvb** [comment]
It seems this kind of modification is easier to do as a library on top of TensorFlow rather than part of TensorFlow itself (Conway's Law). A change to core needs to have some benefit that's not easily achievable when outside of core. Now that TF 1.0 is out, I'm hoping 3rd party libraries will emerge which will collect things like that into toolboxes that are add-ons to TensorFlow. I think this generator pattern is useful, here's a recent user than wanted to know how to use a generator as TensorFlow input -- http://stackoverflow.com/questions/42322176/tensorflow-custom-data-reader-using-py-func
