### ISSUE TITLE
Feature request: enable modification of data in tfrecord files

### ISSUE THREAD

**Issue by tompfeil** [tensorflow/tensorflow#7482]
It would be nice to be able to append or remove samples to or from an existing set of samples saved in a tfrecords file. Otherwise the file has to be duplicated, which is unpractical for datasets >> 1TB.
Formulated in a more generalized way, this can also be seen as splitting and concatenating tfrecord files.

**Comment by aselle** [comment]
I suspect that this is a feature that is not practical to implement since TFRecords are a simple serial file format. Additionally, compressed gzip is not seekable, so the compression would  have to be chunked into some seekable block size. Probably, the best solution is to shard your data into multiple record files. @concretevitamin, could you comment?

**Comment by aselle** [comment]
@jhseu, i know you are giving a talk at the dev summit, but since you are talking about TFRecord in it, I thought you might have additional insight.

**Comment by jhseu** [comment]
Removing records is pretty infeasible without rewriting. I'm not sure we'd want to design the format with that feature, because we're typically optimizing for sequential reads and writes.

Additionally, certain filesystems (e.g., GCS, HDFS) don't allow in-place modifications, so it wouldn't be generally useful.

**Comment by normanheckscher** [comment]
Any chance that append will be implemented?
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/lib/io/tf_record.py#L91
@josh11b

**Comment by josh11b** [comment]
For uncompressed files, you can concatenate them since there is no per-file header. Beyond that, I don't think we have immediate plans to implement append.  That comment you link to was written before we supported compression, which complicates the implementation of the feature.

**Comment by evolu8** [comment]
> For uncompressed files, you can concatenate them

How should we do this? Simply make another file and concat the files to one? How do we prevent compression?

**Comment by kongsgaard** [comment]
@evolu8 you should be able concatenate with bash or windows cmd
https://ss64.com/bash/cat.html
https://ss64.com/nt/type.html

**Comment by RunningLeon** [comment]
Any update on this issue?
Thanks.

**Comment by AnaRhisT94** [comment]
Any updates? Can I append an existing TFRecord?

**Comment by NikoKVCS** [comment]
Any updates? Can I append an existing TFRecord?

**Comment by pietroorlandi** [comment]
Any update about this issue?

**Comment by SuhanovO** [comment]
Any update?
