### ISSUE TITLE
tf.keras.layers.UpSampling2D outputs different output type for input unsigned integer tensors

### ISSUE THREAD

**Issue by rkazants** [tensorflow/tensorflow#74929]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

Yes

### Source

source

### TensorFlow version

2.17.0

### Custom code

Yes

### Current behavior?

Previously, output tensor has float-point type for unsigned input integer tensors.
Now it is changed to the same unsigned integer type as input.
There were backward incompatible changes.

### Standalone code to reproduce the issue

```shell
import tensorflow as tf
import numpy as np

rng = np.random.default_rng()
data = rng.integers(-8, 8, [2, 4, 8, 2]).astype(np.uint16)

tf.keras.backend.clear_session()
x = tf.keras.Input(shape=[4, 8, 2], name='x', dtype=np.uint16)
y = tf.keras.layers.UpSampling2D(size=(2, 3), data_format='channels_last',
                                 interpolation='bilinear')(x)
model = tf.keras.Model(inputs=[x], outputs=[y])
res = model(data)
list(res)[0].dtype
```

**Comment by tilakrayal** [comment]
@rkazants,
Thank you for reporting the issue. I was able to reproduce the issue on tensorflow v2.17 and tf-nightly. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/a844794068095b9578e13cc2f5616761/untitled2089.ipynb).

As this issue is more related to Keras, could you please try to raise the issue on Keras-team/keras [repo](https://github.com/keras-team/keras/issues) for the quick resolution. Thank you!
