### ISSUE TITLE
Illegal instruction (core dumped) on AMD SEV-SNP enabled machine with TensorFlow 2.17.0

### ISSUE THREAD

**Issue by sb-fuji** [tensorflow/tensorflow#75175]
### Issue type

Build/Install

### Description:
I am using an AWS instance with an AMD SEV-SNP enabled machine (AMD EPYC 7R13 Processor) running Ubuntu 22.04.4 LTS. I attempted to install TensorFlow using both `pip install` and a pre-built wheel from the TensorFlow website (`tensorflow_cpu-2.17.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl`). While TensorFlow installed successfully, any attempt to import TensorFlow using `import tensorflow as tf` results in an 'Illegal instruction (core dumped)' error.

The issue persists across different installation methods, but I was able to resolve it by building TensorFlow from source. I believe there is an incompatibility with the AMD SEV-SNP architecture and the pre-built TensorFlow binaries.

### System Information:
- TensorFlow version: 2.17.0
- Installed via: `pip install` and TensorFlow pre-built wheel from [link to the wheel]
- OS: Ubuntu 22.04.4 LTS
- Hardware: AMD EPYC 7R13 Processor (SEV-SNP enabled)
- Python version: 3.11

### Expected Behavior:
TensorFlow should import without any errors.

### Current Behavior:
Importing TensorFlow results in an 'Illegal instruction (core dumped)' error.

### Additional Details:
Building TensorFlow from source resolved the issue, but the pre-built binaries seem to be incompatible with my architecture.

### Standalone code to reproduce the issue

```shell
1. Install TensorFlow via pip: `pip install tensorflow`
2. Try to import TensorFlow using `import tensorflow as tf`
```

**Comment by tilakrayal** [comment]
@sb-fuji,
Generally the "Illegal instruction (core dumped)" error caused by a CPU that does not support AVX instructions.
The Intel(R) Celeron(R) N4505 processor does not support AVX instructions, so you will not be able to use TensorFlow on this CPU without compiling it from the source. The earlier version doesn't require the AVX instructions but the newer version does.

The issue might be related to your environment.You can find the suitable Nvidia driver for your GPU from [here](https://www.nvidia.com/Download/index.aspx).

Thank you!
