### ISSUE TITLE
AVX512 support is not functional (does not compile etc)

### ISSUE THREAD

**Issue by fenrus75** [tensorflow/tensorflow#7530]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?

there is an existing issue but it's very vague and at the same time too specific

### Environment info
Operating System:

Linux 

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):
no cuda

Current AVX512 support does not function, for example with
 bazel build -c opt  --copt=-mavx2 --copt=-mavx512f --copt=-O3 --copt=-march=skylake --copt=-mfma --copt=-g1  //tensorflow/tools/pip_package:build_pip_package

there are various compile errors. I'm filing this ticket more as a grab bag than it being about a specific compile error; as work is done we can add specific failures to this bug.

If nobody else is working on this I can try to assign someone at work to this, but if there's already code floating around to fix this then I'm more than happy to defer to that.

**Comment by aselle** [comment]
Could you link to the original issue? If you could contribute helping fix this from your organization that would be most welcome. I'm not aware of anybody working on this right now. @petewarden, do you know of any other efforts?

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!

**Comment by David-Levinthal** [comment]
for a bazel build like:
bazel build  --copt="-mavx512f" --copt="-mavx512dq" --copt="-mavx512vl" --copt="-Ofast" -s -c opt //tensorflow/tools/pip_package:build_pip_package 
There are errors in PacketMathAVX512 and PacketMathAVX2
avx2 seems to need something like:

typedef struct Packet16q16i {
  __m256i val;
  operator __m256i() const { return val; }
  Packet16q16i();
  Packet16q16i(__m256i val) : val(val) {}
} Packet16q16i;

in avx512
#ifdef EIGEN_VECTORIZE_AVX512DQ
// AVX512F does not define _mm512_extractf32x8_ps to extract _m256 from _m512
#define EIGEN_EXTRACT_8f_FROM_16f(INPUT, OUTPUT)                           \
  __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0) __m256 OUTPUT##_1 = \
      _mm512_extractf32x8_ps(INPUT, 1)
#else
#define EIGEN_EXTRACT_8f_FROM_16f(INPUT, OUTPUT)                \
  __m256 OUTPUT##_0 = _mm256_insertf128_ps(                     \
      _mm256_castps128_ps256(_mm512_extractf32x4_ps(INPUT, 0)), \
      _mm512_extractf32x4_ps(INPUT, 1), 1);                     \
  __m256 OUTPUT##_1 = _mm256_insertf128_ps(                     \
      _mm256_castps128_ps256(_mm512_extractf32x4_ps(INPUT, 2)), \
      _mm512_extractf32x4_ps(INPUT, 3), 1);
#endif

And
template<> EIGEN_STRONG_INLINE Packet16f preduxp<Packet16f>(const Packet16f*
vecs)
{
should be something like:
// AVX512F does not define _mm512_extractf32x8_ps to extract _m256 from _m512
#define EIGEN_EXTRACT_8f_FROM_16f(INPUT, OUTPUT)                           \
  __m256 OUTPUT##_0 = _mm512_extractf32x8_ps(INPUT, 0);        \
__m256 OUTPUT##_1 =  _mm512_extractf32x8_ps(INPUT, 1);

And maybe missing “ “
template<> EIGEN_STRONG_INLINE Packet16f preduxp<Packet16f>(const Packet16f* vecs)
{

this does not finish the problems..see attachment  is this stuff fixed in r1.1?
[avx512_error_after_PacketMath_fixes.txt](https://github.com/tensorflow/tensorflow/files/964910/avx512_error_after_PacketMath_fixes.txt)

**Comment by David-Levinthal** [comment]
even updating to r1.1 and updating the compiler to gcc6.2 brings no joy...the problems shown above go away..but there seems to be some wierd issue with code generation and illegal usage of an instruction

bazel build  --copt="-mavx512f" --copt="-mavx512dq" --copt="-mavx512vl" --copt="-Ofast" -s -c opt //tensorflow/tools/pip_package:build_pip_package
ERROR: /home/levinth/tensorflow_1_1/tensorflow/tensorflow/core/kernels/BUILD:1337:1: C++ compilation of rule '//tensorflow/core/kernels:dynamic_stitch_op' failed: gcc failed: error executing command /usr/bin/gcc -U_FORTIFY_SOURCE -fstack-protector -Wall -B/usr/bin -B/usr/bin -Wunused-but-set-parameter -Wno-free-nonheap-object -fno-omit-frame-pointer -g0 -O2 '-D_FORTIFY_SOURCE=1' -DNDEBUG ... (remaining 111 argument(s) skipped): com.google.devtools.build.lib.shell.BadExitStatusException: Process exited with status 1.
/tmp/ccT8Q8Xu.s: Assembler messages:
/tmp/ccT8Q8Xu.s:23313: Error: invalid register operand for `vmovdqu'
