### ISSUE TITLE
What can replace tf.RegisterShape in tensorflow 1.0.0?

### ISSUE THREAD

**Issue by primetang** [tensorflow/tensorflow#7570]
```
Traceback (most recent call last):
  File "tools/train_net.py", line 18, in <module>
    from networks.factory import get_network
  File "./ImageToolkit0/face_detection/lib/networks/__init__.py", line 8, in <module>
    from .VGGnet_train import VGGnet_train
  File "./ImageToolkit0/face_detection/lib/networks/VGGnet_train.py", line 2, in <module>
    from networks.network import Network
  File "./ImageToolkit0/face_detection/lib/networks/network.py", line 4, in <module>
    import roi_pooling_layer.roi_pooling_op_grad
  File "./ImageToolkit0/face_detection/lib/roi_pooling_layer/roi_pooling_op_grad.py", line 7, in <module>
    @tf.RegisterShape("RoiPool")
AttributeError: 'module' object has no attribute 'RegisterShape'
```

So what can replace `tf.RegisterShape` in tensorflow 1.0.0?

**Comment by yaroslavvb** [comment]
@aselle

**Comment by aselle** [comment]
You need to write shape inference routines in C++. This is part of moving more functionality into core c++ so other language bindings are more useful.  You can search the code for `.SetShapeFn` to see a bunch of examples. It is done through named constructor  argument idiom by providing a C++11 lambda function. Post back if you need more help.

**Comment by vrv** [comment]
https://www.tensorflow.org/extend/adding_an_op#shape_functions_in_c should help too.

**Comment by primetang** [comment]
Here is a temporary solution:

previous version：
```
import tensorflow as tf
tf.RegisterShape
```

version 1.0.0:
```
from tensorflow.python.framework import ops
ops.RegisterShape
```

**Comment by vrv** [comment]
Please don't do that -- if https://github.com/smallcorgi/Faster-RCNN_TF/blob/master/lib/roi_pooling_layer/roi_pooling_op_grad.py#L7 is the shape function, it's very easy to implement in C++.

**Comment by primetang** [comment]
Thank you very much, I will implement it in C++.

**Comment by vrv** [comment]
Here is what the function could look like (edited in github, so no idea if it works).

```
::tensorflow::ShapeHandle dims;
TF_RETURN_IF_ERROR(c->WithRank(c->input(0), 4, &dims));
::tensorflow::DimensionHandle channels;
TF_RETURN_IF_ERROR(c->Dim(dims, 3, &channels))

::tensorflow::ShapeHandle dims_rois;
// Not sure what the rank of this input should be
TF_RETURN_IF_ERROR(c->WithRankAtLeast(c->input(1), 1, &dims_rois));
::tensorflow::DimensionHandle num_rois;
TF_RETURN_IF_ERROR(c->Dim(dims_rois, 0, &channels))

int64 pooled_height;
int64 pooled_width;
TF_RETURN_IF_ERROR(c->GetAttr("pooled_height", &pooled_height));
TF_RETURN_IF_ERROR(c->GetAttr("pooled_width", &pooled_width));

::tensorflow::DimensionHandle output = c->MakeShape({num_rois, pooled_height, pooled_width, channels));
c->set_output(0, output);
c->set_output(1, output);
return ::tensorflow::Status::OK();
```

**Comment by harpone** [comment]
I don't get it... why shouldn't I use @ops.RegisterShape? I know practically no C++ at all, so no custom tf ops for me?

**Comment by vrv** [comment]
If you write your function as a composition of existing operations, you don't need to touch C++.   If you are writing a custom op in C++, then you obviously are already touching C++ :)

**Comment by yaroslavvb** [comment]
@harpone This is a side-effect of moving shape inference into C++ which I guess was needed to enable XLA and non-Python users of TensorFlow. But I wonder if you could just avoid specifying shape inference functions.

I have a trick for speeding up large graphs which makes graph construction 3x faster with no adverse side-effects, change the line in [ops.py](https://github.com/tensorflow/tensorflow/blob/f821ce046df71f5784ed4ce7fb6b87f77d96b031/tensorflow/python/framework/ops.py#L1707) to read this

```
def set_shapes_for_outputs(op):
  """Uses the registered shape functions to set the shapes for op's outputs."""
  return
```

**Comment by yaroslavvb** [comment]
@harpone -- PS there's opveclib (http://opveclib.readthedocs.io/en/master/) which supposedly has magic to turn Python into CUDA code, compile it, and then dynamically load it into TensorFlow as custom op

**Comment by harpone** [comment]
@vrv OK thanks :)

> PS: as Vijay pointed out, you'll need C++ anyway to define the body of custom op, even without shape inference function

Oh yeah... I was using the [py_func](https://gist.github.com/harpone/3453185b41d8d985356cbe5e57d67342) trick earlier, but I guess that's not a very elegant solution...

opveclib sounds really cool, thanks!

**Comment by eragonruan** [comment]
try replace tf with ops

**Comment by aselle** [comment]
Seems like the issue was answered, so closing for now. Thanks!

**Comment by CharlesShang** [comment]
@vrv Thank you for your code.
I've made some modification and tested it. 
Write it down in case someone may need it. 
```
SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
      ::tensorflow::shape_inference::ShapeHandle dims;
      TF_RETURN_IF_ERROR(c->WithRank(c->input(0), 4, &dims));
      ::tensorflow::shape_inference::DimensionHandle channels;
      channels = c->Dim(dims, 3);

      ::tensorflow::shape_inference::ShapeHandle dims_rois;
      TF_RETURN_IF_ERROR(c->WithRankAtLeast(c->input(1), 1, &dims_rois));
      ::tensorflow::shape_inference::DimensionHandle num_rois;
      num_rois = c->Dim(dims_rois, 0);

      int64 pooled_height;
      int64 pooled_width;
      TF_RETURN_IF_ERROR(c->GetAttr("pooled_height", &pooled_height));
      TF_RETURN_IF_ERROR(c->GetAttr("pooled_width", &pooled_width));
      ::tensorflow::shape_inference::ShapeHandle output_shape =\
         c->MakeShape({num_rois, pooled_height, pooled_width, channels});
      c->set_output(0, output_shape);
      c->set_output(1, output_shape);
      return ::tensorflow::Status::OK();
    });
```

**Comment by fansariadeh** [comment]
> @vrv Thank you for your code. I've made some modification and tested it. Write it down in case someone may need it.
> 
> ```
> SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
>       ::tensorflow::shape_inference::ShapeHandle dims;
>       TF_RETURN_IF_ERROR(c->WithRank(c->input(0), 4, &dims));
>       ::tensorflow::shape_inference::DimensionHandle channels;
>       channels = c->Dim(dims, 3);
> 
>       ::tensorflow::shape_inference::ShapeHandle dims_rois;
>       TF_RETURN_IF_ERROR(c->WithRankAtLeast(c->input(1), 1, &dims_rois));
>       ::tensorflow::shape_inference::DimensionHandle num_rois;
>       num_rois = c->Dim(dims_rois, 0);
> 
>       int64 pooled_height;
>       int64 pooled_width;
>       TF_RETURN_IF_ERROR(c->GetAttr("pooled_height", &pooled_height));
>       TF_RETURN_IF_ERROR(c->GetAttr("pooled_width", &pooled_width));
>       ::tensorflow::shape_inference::ShapeHandle output_shape =\
>          c->MakeShape({num_rois, pooled_height, pooled_width, channels});
>       c->set_output(0, output_shape);
>       c->set_output(1, output_shape);
>       return ::tensorflow::Status::OK();
>     });
> ```

Can you please explain how I can save it in the appropriate directory to use it while working with tensorflow?
I have zero knowledge of C++

**Comment by ZHUANG-JLU** [comment]
I wrote custom op by c++ and use tf.load_op_library to load the op in python.And get the Segmentation fault (core dumped).Could someone can help me ?  Ｂelow is the error and code.

######################################################################################################
This is the error.
######################################################################################################
WARNING:tensorflow:From /home/zhj/Py/frustum-pointnets-master/models/tf_util.py:384: The name tf.nn.max_pool is deprecated. Please use tf.nn.max_pool2d instead.

WARNING:tensorflow:From /home/zhj/Py/frustum-pointnets-master/models/tf_util.py:613: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
WARNING:tensorflow:From /home/zhj/Py/frustum-pointnets-master/models/model_util.py:235: to_float (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.cast` instead.
WARNING:tensorflow:From /home/zhj/Py/frustum-pointnets-master/models/model_util.py:236: calling reduce_sum_v1 (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
mask.shape---------------------------- (1, 1024)
Segmentation fault (core dumped)
######################################################################################################


######################################################################################################
This is the custom op 
######################################################################################################
#include "tensorflow/core/framework/common_shape_fns.h"
#include "tensorflow/core/framework/op.h"
#include "tensorflow/core/framework/op_kernel.h"
#include "tensorflow/core/framework/shape_inference.h"

namespace tensorflow {

using shape_inference::DimensionHandle;
using shape_inference::InferenceContext;
using shape_inference::ShapeHandle;
using shape_inference::UnchangedShape;

REGISTER_OP("Zhj")
    .Input("input: float")
    .Output("output: int32")
    .SetShapeFn([](::tensorflow::shape_inference::InferenceContext* c) {
        DimensionHandle batch = c->Dim(c->input(0), 0);
        ShapeHandle output_shape = c->MakeShape({batch,c->MakeDim(512),c->MakeDim(2)});
        c->set_output(0, output_shape);
        return Status::OK();
    });

class PyFuncZhj : public tensorflow::OpKernel {
 public:
  explicit PyFuncZhj(OpKernelConstruction* context) : OpKernel(context) {}

  void Compute(OpKernelContext* context) override {
    // Grab the input tensor
    const Tensor& tensor_in = context->input(0);
    const TensorShape& input_shape = tensor_in.shape();
    auto inputEigen = tensor_in.shaped<float, 2>({input_shape.dim_size(0), input_shape.dim_size(1)});
    // Create an output tensor
    Tensor* output_tensor;
    OP_REQUIRES_OK(context, context->allocate_output(
                                0, TensorShape({input_shape.dim_size(0), 512,2}),
                                &output_tensor));
    auto outputEigen = output_tensor->shaped<int32, 3>({input_shape.dim_size(0), 512, 2});

    std::vector<std::vector<int>> indicesVec;
    for (int i = 0; i < input_shape.dim_size(0); i++)
    {
      std::vector<int> tmpIndices;
      for (int j = 0; j < input_shape.dim_size(1); j++)//output_shape.dim_size(1)
      {
        if(inputEigen(i,j) > 0.1)
        {
          tmpIndices.push_back(j);
        }
      }
      int lengthIndices = tmpIndices.size();
      if(lengthIndices > 0)
      {
        while(tmpIndices.size() < 512)
        {
          int rand_num = rand() % lengthIndices;
          tmpIndices.push_back(tmpIndices[rand_num]);
        }
        while (tmpIndices.size() > 512)
        {
          int rand_num = rand() % tmpIndices.size();
          tmpIndices.erase(tmpIndices.begin() + rand_num);
        }
      }
      indicesVec.push_back(tmpIndices);
    }
    for(int i = 0; i < indicesVec.size(); i++)
    {
      if(0 == indicesVec[i].size())
      {
        for(int j = 0; j < 512; j++)
        {
          outputEigen(i, j, 0) = i;  // batchsize
          outputEigen(i, j, 1) = 0;
        }
      }
      else
      {
        for(int j = 0; j < indicesVec[i].size(); j++)
        {
          outputEigen(i, j, 0) = i;  // batchsize
          outputEigen(i, j, 1) = indicesVec[i][j];
        }
      }
    }
  }
};
REGISTER_KERNEL_BUILDER(Name("Zhj").Device(DEVICE_CPU), PyFuncZhj);
}  // namespace tensorflow
######################################################################################################



######################################################################################################
This is the python code
######################################################################################################
Zhj = tf.load_op_library("/home/zhj/Py/frustum-pointnets-master/train/log_v1/zhj.so")
def tf_gather_object_pc(point_cloud, mask, npoints=512):
    ''' Gather object point clouds according to predicted masks.
    Input:
        point_cloud: TF tensor in shape (B,N,C)
        mask: TF tensor in shape (B,N) of 0 (not pick) or 1 (pick)
        npoints: int scalar, maximum number of points to keep (default: 512)
    Output:
        object_pc: TF tensor in shape (B,npoint,C)
        indices: TF int tensor in shape (B,npoint,2)
    '''
    def mask_to_indices(mask):
        indices = np.zeros((mask.shape[0], npoints, 2), dtype=np.int32)
        for i in range(mask.shape[0]):
            pos_indices = np.where(mask[i,:]>0.5)[0]
            # skip cases when pos_indices is empty
            if len(pos_indices) > 0: 
                if len(pos_indices) > npoints:
                    choice = np.random.choice(len(pos_indices),
                        npoints, replace=False)
                else:
                    choice = np.random.choice(len(pos_indices),
                        npoints-len(pos_indices), replace=True)
                    choice = np.concatenate((np.arange(len(pos_indices)), choice))
                np.random.shuffle(choice)
                indices[i,:,1] = pos_indices[choice]
            indices[i,:,0] = i
        return indices

    print("mask.shape----------------------------", mask.shape)  # mask.shape: (1,1024)
    # indices = tf.py_func(mask_to_indices, [mask], tf.int32)
    indices = Zhj.zhj([mask])
    object_pc = tf.gather_nd(point_cloud, indices)
    return object_pc, indices
