### ISSUE TITLE
# text_classification_with_hub code does not run. give error for `model.add(hub_layer)`

### ISSUE THREAD

**Issue by mn-48** [tensorflow/tensorflow#76042]
https://www.tensorflow.org/tutorials/keras/text_classification_with_hub

code url: https://github.com/tensorflow/docs/blob/master/site/en/tutorials/keras/text_classification_with_hub.ipynb
```
model = tf.keras.Sequential()
model.add(hub_layer)
model.add(tf.keras.layers.Dense(16, activation='relu'))
model.add(tf.keras.layers.Dense(1))

model.summary()
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
[<ipython-input-9-b0a8e638d9e1>](https://localhost:8080/#) in <cell line: 2>()
      1 model = tf.keras.Sequential()
----> 2 model.add(hub_layer)
      3 model.add(tf.keras.layers.Dense(16, activation='relu'))
      4 model.add(tf.keras.layers.Dense(1))
      5 

[/usr/local/lib/python3.10/dist-packages/keras/src/models/sequential.py](https://localhost:8080/#) in add(self, layer, rebuild)
     93                 layer = origin_layer
     94         if not isinstance(layer, Layer):
---> 95             raise ValueError(
     96                 "Only instances of `keras.Layer` can be "
     97                 f"added to a Sequential model. Received: {layer} "

ValueError: Only instances of `keras.Layer` can be added to a Sequential model. Received: <tensorflow_hub.keras_layer.KerasLayer object at 0x7d1a15ed5600> (of type <class 'tensorflow_hub.keras_layer.KerasLayer'>)

**Comment by emadellaloggia** [comment]
This might help:This file might fix it
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic
I put the necessary dlls in the archive

**Comment by mn-48** [comment]
@emadellaloggia your provided file is blocked and shows danger.

**Comment by tilakrayal** [comment]
@mn-48,
Hi, By default the colab notebook is using tensorflow v2.17 which contains keras3.0 which was causing the error. Could you please try to import keras2.0 with the below commands.

```python
!pip install tf_keras

import tf-keras as keras
```

Also I have changed some steps like  modifying **tf_keras/keras.Sequential** instead of **tf.keras.Sequential** and the code was executed without error/fail. Kindly find the gist of it [here](https://colab.research.google.com/gist/tilakrayal/3f0497dc9892f933fdfd706adc39dded/text_classification_with_hub.ipynb).

Thank you!

**Comment by mn-48** [comment]
Yes
