### ISSUE TITLE
the use of MultiRNNCell?

### ISSUE THREAD

**Issue by liuyichaosoftware** [tensorflow/tensorflow#7604]
doc is in https://www.tensorflow.org/tutorials/recurrent

I found the line
stacked_lstm = tf.contrib.rnn.MultiRNNCell([lstm] * number_of_layers,

I need to use MultiRNNCell

but,I write those lines

a = [tf.nn.rnn_cell.BasicLSTMCell(10)]*3

print id(a[0]), id(a[1])

Its output is 4648063696 4648063696

can MultiRNNCell use the same object BasicLSTMCell as a list for parameter?

**Comment by carlthome** [comment]
> can MultiRNNCell use the same object BasicLSTMCell as a list for parameter?

Yes, you'll get separate trainable weights by repeating the list like you're doing. It's a bit confusing to be honest. You should have asked this [here](https://groups.google.com/forum/#!forum/tensorflow) though.

**Comment by aselle** [comment]
@ebrevdo, do you think we should change the docs in some way to make it clearer?

**Comment by ebrevdo** [comment]
This is indeed confusing and hopefully next week we'll have a push (over a
month in the making) that disallows this behavior.  It's a bit out of scope
of this bug to describe why this behavior is the way it is, but it's been
the TF standard for a long time.  But after this change, you'll have to
write:

MultiRNNCell([BasicLSTMCell(10) for _ in range(3)])

otherwise you will get an error when calling dynamic_rnn.

With this version of the code, you end up creating 3 separate BasicLSTMCell
instances, each of which expects to maintain its own parameters.

**Comment by liuyichaosoftware** [comment]
thank you very much ~

**Comment by carlthome** [comment]
Don't forget to close your issue @liuyichaosoftware. 👍

**Comment by tifoit** [comment]
The API has been changed to learn.MetricSpec(...) in tf 1.0.0,

0.9 to 1.0.1 is a big jump. A lot changed. 
Details: https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md 

In tf 1.0.0, the API has been changed such as:

tf.nn.seq2seq.sequence_loss_by_example
to
tf.contrib.legacy_seq2seq.sequence_loss_by_example

tf.nn.rnn_cell.
to
tf.contrib.rnn.

tf.nn.rnn_cell.MultiRNNCell(
to
tf.contrib.rnn.MultiRNNCell(

...

**Comment by lonway** [comment]
How to find the API map between the old and new version @tifoit
