### ISSUE TITLE
tf.pad does not support SparseTensor in r1.0

### ISSUE THREAD

**Issue by sromano** [tensorflow/tensorflow#7622]
This works 
```
import tensorflow as tf
session = tf.InteractiveSession()
pad = tf.pad([[1,2]], [[0,0],[0,150]], mode='CONSTANT')
pad.eval()
```

But this doesn't work

```
import tensorflow as tf
session = tf.InteractiveSession()
tensor = tf.SparseTensor(indices=[[0, 0], [0, 1]], values=[1, 2], dense_shape=[1, 2])
pad = tf.pad(tensor, [[0,0],[0,150]], mode='CONSTANT')
pad.eval()
```

The following error is thrown
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sromano/Dropbox/uba/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 1646, in pad
    return gen_array_ops._pad(tensor, paddings, name=name)
  File "/Users/sromano/Dropbox/uba/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 2083, in _pad
    name=name)
  File "/Users/sromano/Dropbox/uba/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 494, in apply_op
    raise err
TypeError: Expected binary or unicode string, got <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x116288450>
```

My use case is that I'm reading a csv file where each row has a different amount of elements and I want to turn it into a matrix of a fixed length. I use string split in each row and I get a SparseTensor, so then I need a different padding in each row to complete the expected width.

I'm using Python 2.7 and Tensorflow r1.0

**Comment by aselle** [comment]
Did this work for you  previously?

**Comment by sromano** [comment]
No. I updated from r0.10 to r1.0 to see if it will get solved. But it did not work in any of the two versions

**Comment by aselle** [comment]
Yes, unfortunately, it is difficult to support every operation for sparse tensors, and currently it is only supported by a few special ops. With the current sparse form this is unlikely to be a super efficient operation, since to produce paded values, you'd need random access to access values for a gather based approach to producing padded values. It's definitely possible, but we haven't found a need for it yet. What is your use case. Would you be willing to work on a PR to add support?
Thanks for posting this issue!

**Comment by aselle** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
