### ISSUE TITLE
Feature: Tensorboard Starts with all Runs Toggled Off Initially

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#7654]
Currently the initial load /  full page refresh of tensorboard starts on the scalars tab with all runs toggled on for rendering. If there are a lot of runs in the logdir, the browser hangs for a noticeable period of time while all of the charts for the runs are rendered. I suggest making the initial load have runs off and letting the user opt in / turn on the desired set of runs.

**Comment by aselle** [comment]
@dandelionmane, please consider this feature request.

**Comment by carlthome** [comment]
Or maybe default to showing the latest run or something ?

**Comment by cancan101** [comment]
The concept of "latest" run seems somewhat loosely defined to me (ie most recent updated, started? run in parallel?).

**Comment by dandelionmane** [comment]
Having it always start with all runs disabled would be confusing to first-time TensorBoard users who haven't yet learned what the run selector is.

However, we could make it start with all runs toggled off if you have, say, >20 runs. That should solve this performance issue.

What do you think?

**Comment by cancan101** [comment]
Anyway the 20 could be a CLI option? It could be defaulted to 20, but it could also be set to 0, etc by users.

**Comment by carlthome** [comment]
@dandelionmane that's a good fix IMHO.

@cancan101, or just keep view related options controllable in the GUI instead, no? On a similar note it would be nice if GUI controls were kept after browser tab refreshing but that might be a tall order (setting the GET object or fragment identifier like Gmail). At my work we have issues with different users having different preferences, but we look and discuss the same runs.

**Comment by cancan101** [comment]
How are the values in:
![image](https://cloud.githubusercontent.com/assets/51059/23240002/afa75df4-f938-11e6-9879-0751b4a7a173.png)
persisted? Perhaps that can be used.

and re saving changes, it would be _amazing_ if a refresh did not cause by selected runs to be lost.

**Comment by cancan101** [comment]
Related issue, it seems that as new runs are started, they are added to the list toggled _on_.

**Comment by dandelionmane** [comment]
There's something broken in the opensource version of TensorBoard that's causing state not to get persisted in the url bar. Internally, we get really long URLs like:

http://localhost:6006/#scalars&runsDisabled=eyI1L2xyXzFFLTA1LGNvbnY9MixmYz0yIjp0cnVlLCI1L2xyXzFFLTA0LGNvbnY9MSxmYz0yIjp0cnVlLCI1L2xyXzFFLTA0LGNvbnY9MixmYz0yIjp0cnVlfQ%3D%3D

which include the list of selected runs. So a refresh does not lose that info. 

I don't want to add new command line flags for GUI settings. that will be a mess to maintain. 

The values in settings are persisted via localStorage, so we could put more stuff there. It doesn't work super well for Googlers, since the TensorBoard moves around different machines and the local storage cache would be lost since it is (afaik) url specific. But for open-source use cases it should be fine.

**Comment by cancan101** [comment]
Okay, yes, would be great to have setting for min number of runs to auto select or just a flag whether to auto select.

**Comment by dandelionmane** [comment]
I have a CL right now that hardcodes the number to auto-enable at 15.
How important is it to you that you be able to change that value?

**Comment by cancan101** [comment]
As a user, seems odd to me to have the selection behavior determined based on the number of files in the directory. Even having the > 15 is a big improvement from what I have now.

**Comment by dandelionmane** [comment]
I changed it to 10. CL will likely land in GitHub shortly (although it will be longer before it is packaged in a TensorBoard)

Why does it seem odd to have the selection behavior default to showing just the first ten runs?

**Comment by cancan101** [comment]
The idea have having any runs selected initially might be great for discoverability for new users. After that fact, it's just this annoying change point where I have to click an extra untoggle depending on whether I have < 10 or >= 10 runs in a directory.

**Comment by dandelionmane** [comment]
I see. How about I make it so that the first toggle click will go to all-runs-off, regardless of the number of runs present?

**Comment by cancan101** [comment]
What do you mean "first toggle click" ?

**Comment by dandelionmane** [comment]
There is a "toggle all runs" button.
I'll make it so that regardless of how many runs your TensorBoard has, when you click "toggle all runs" for the first time, it will turn all runs off. So if that's the clean state you want, you can always get it in one click, rather than depending on how many runs there were.

**Comment by cancan101** [comment]
ok

**Comment by dandelionmane** [comment]
I just merged a change internally that will change the default again:

If there are more than 40 runs, everything is toggled off by default
If there are 40 or fewer, then everything is toggled on by default.

This way we avoid overloading the browser when there are lots of runs, but for simple cases (and new users) there is no added complexity. I got feedback that turning on only the first 10 was more confusing for everyone, since people mght not realize they are in an intermediate state.

@cancan101  I'm open to changing the constant from 40 to something lower if that would be better for you.

**Comment by cancan101** [comment]
Yes I agree intermediate state is odd. 40 seems like a lot. Just think of seeing 40 lines all on one graph. Perhaps something like 10 or 15?

**Comment by cancan101** [comment]
@dandelionmane After testing the 1.1rc1, I agree that having just the "first" 10 selected if very weird.  Even the definition of first is somewhat arbitrary (arguably you would want the most recent 10 and not the oldest 10). I would personally love see some way to select all or nothing, presumably based on some threshold like 10 or 15 files in the directory (ideally this threshold is configurable on CLI, but I understand this may not be practical).

**Comment by carlthome** [comment]
> This way we avoid overloading the browser when there are lots of runs, but for simple cases (and new users) there is no added complexity. I got feedback that turning on only the first 10 was more confusing for everyone, since people mght not realize they are in an intermediate state.

Makes sense.

> @cancan101 I'm open to changing the constant from 40 to something lower if that would be better for you

How many different colors are there for the scalar plots? The default should not exceed that IMO.
