### ISSUE TITLE
Package not Reslove.

### ISSUE THREAD

**Issue by kinDSa** [tensorflow/tensorflow#7683]
Hello,

I am using TensorFlow Android Camera Demo. In TensorFlowInferenceInterface class there are some package not reslove like:

import org.tensorflow.DataType;
import org.tensorflow.Graph;
import org.tensorflow.Session;
import org.tensorflow.Tensor;
import org.tensorflow.TensorFlow;

Can any one help to find out where some thing is missing.

**Comment by andrewharp** [comment]
Hi, how are you trying to build the demo? Are you getting this while following the instructions in the examples/android/README.md?

**Comment by patoalejor** [comment]
@andrewharp Do you know how to resolve the issue, I have the same problem. I had followed the steps in the README.md

**Comment by andrewharp** [comment]
@kinDSa @patoalejor Can you please explain the exact steps you're using to reproduce this? It sounds like it's not finding the java API classes under tensorflow/java for some reason.

**Comment by kinDSa** [comment]
@andrewharp
I followed step given in  README.md file of TensorFlow Android Camera Demo.First I clone Tensorflow demo, Then Import android project at path tensorflow/tensorflow/examples/android  in android studio. After importing I face above error. There is two class TensorFlowInferenceInterface and RunStats under tensorflow/java.

**Comment by shuangwu** [comment]
I have the same problem, I followed the README.md, and compiled andoird demo with bazel. When trying to use Android Studio, the compilation filed with the same error.

**Comment by htyspghtz** [comment]
Is there anyway we could get an Android Studio release for the Image Classifier? For us folks that aren't able to get a Bazel build going? I've tried for about a week now trying to get this build to work (and I really mean for a week, full days and nights of research and hackjobs). I've had terrible luck with Bazel, and finding a work around to Bazel. This might be due to me being relatively unacknowledged of app development (as my only use, as of now, is to get an app deployed for a web project that I'm working on). I've found one resource, of something somewhat similar (https://github.com/miyosuda/TensorFlowAndroidDemo), but it appears to be outdated, as the changes in files: TensorflowClassifier.java, and TensorflowImageListener.java (which to my understanding has been renamed to ClassifierActivity). I think maybe releasing a depository for Android Studio, that we're able to drop in libtensorflow_demo.so, .jar (from nightly), and our model (of course with input values changed in ClassifierActivity.java (2/23/2017)) might be helpful. Kindest regards, @andrewharp, as you appear to be the only person with updated pertinent documentation.

This comment here, is probably the most useful thing I've read, but I'm not sure what to do with it:


> We definitely could use some centralized documentation about what lib is what. Essentially the libs are consecutive supersets of each other in the following order:
> 
> libandroid_tensorflow_lib.lo:
> core TensorFlow runtime + ops for linking into other libraries (you would still need all the TF headers to really use it, but perhaps it can be useful in some situations)
> 
> libtensorflow_inference.so:
> core TF runtime+ops with added JNI bindings that allow you to use TF for inference from Java. This + the associated jarfile are all you should need to integrate TF into your own Android app, unless you want custom ops or training.
> 
> libtensorflow_demo.so:
> contains everything in libtensorflow_inference.so + demo-specific native code; if you want to run the official demo without building anything native this can be dropped into the APK
> 
> edit: note that the libs currently found at nightly-android (build #11) have been unfortunately built without NEON support, but the next set to be uploaded should be fixed.
>

**Comment by andrewharp** [comment]
@shuangwu @kinDSa @patoalejor 
It's not finding the Java files under [tensorflow/java](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/java). Looks like this was missed on the recent conversion of TensorFlowInferenceInterface to use the Java API. If you add `"../../java/src/main"` to java.srcDirs in [build.gradle](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/android/build.gradle#L41) that should do the trick. I'll send a PR to fix this.

@htyspghtz We're working on full Gradle/cmake/makefile support that will let Android Studio build on Windows. Should be out in the next week or two :)

**Comment by andrewharp** [comment]
@htyspghtz Note that the comment you pasted is a little outdated: currently you need both libtensorflow_inference.so and libtensorflow_demo.so. This is because the TF library and inference bindings have been removed from libtensorflow_demo.so (it only contains object tracking+YUV->RGB conversion code now).

**Comment by shuangwu** [comment]
@andrewharp thanks for the help, it's now complaining about package java.nio.file, another missing entry in java.srcDirs?

**Comment by andrewharp** [comment]
@shuangwu java.nio.file was added in Java 7 -- it sounds like your JDK might be too old or you're forcing compatibility with older APIs.

**Comment by shuangwu** [comment]
@andrewharp I have java 1.8.0_121 installed, so definitely not old, somehow it's not find it?

**Comment by andrewharp** [comment]
@shuangwu Ok, I'm seeing this too now actually. It's coming from the LabelImage.java example, which is not part of the Java API itself.

If you replace java.srcDirs with this I think it will work:
```
            java {
                srcDir '../../java/src/main/java'
                exclude '**/examples/**'
            }
            java {
                srcDir '../../contrib/android/java'
            }
            java {
                srcDir 'src'
            }
```

**Comment by shuangwu** [comment]
@andrewharp it is working, thanks.
