### ISSUE TITLE
embedding variable in ptb_word_lm.py

### ISSUE THREAD

**Issue by sharod** [tensorflow/tensorflow#7684]
In ptb_word_lm.py I see that for word2vec vectors we are doing:

embedding = tf.get_variable(
          "embedding", [vocab_size, size], dtype=data_type())
      inputs = tf.nn.embedding_lookup(embedding, input_.input_data)

but where is the variable embedding created? Is it random or is it pretrained?

**Comment by krayush07** [comment]
Hi @sharod 

tf.get_variable() [creates](https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py#L124) the 'embedding' variable and [initializes it](https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py#L335) using a random initializer during training time as [var scope for training](https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py#L335) is set to 'None'. 

So, during training the word embedding is initialized and further trained since ['trainable' parameter](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/ops/variable_scope.py#L203) is set to True. While during, validation or testing, the trained embeddings are retrieved as [variable reuse](https://github.com/tensorflow/models/blob/master/tutorials/rnn/ptb/ptb_word_lm.py#L342) is set to True.

Also, please use Stackoverflow for these kind of questions.
