### ISSUE TITLE
Image problems in Tensorflow documentation at tensorflow.org, Error 404

### ISSUE THREAD

**Issue by qinglintian** [tensorflow/tensorflow#7685]
I'm not sure I should put the issue here. But when I clicked "Issue tracker" on tensorflow.org, it redirects me here.

I realized that the directory structure for TF documentation has changed a lot for TF 1.0 on http://www.tensorflow.org. Now there are problems for web pages with images, like https://www.tensorflow.org/api_docs/python/tf/segment_max?hl=bn. A 404 error is reported while loading the images.

**Comment by hustlrr** [comment]
that happens to me, too. have you solved the problem?

**Comment by qinglintian** [comment]
@hustlrr I can't solve it. Hope the maintainers fix this issue soon.

**Comment by dr4b** [comment]
it's an issue with how we now have python docs in api_docs/python/tf/whatever but they all refer to "../../images/" -- the proper directory is tensorflow.org/images rather than tensorflow.org/api_docs/images.  Not sure whether to fix in docstring or site generation scripts but we'll get it done one way or the other.
