### ISSUE TITLE
Feature request: Allow import of incomplete graphs

### ISSUE THREAD

**Issue by malmaud** [tensorflow/tensorflow#7726]
It seems like there is no reason in principle not to allow this:

```python
import tensorflow as tf

g=tf.Graph()
with g.as_default():
    x = tf.constant(1.0, name="x")
    y = tf.exp(x)
g_def=tf.GraphDef()
g_def.node.extend([y.op.node_def])

g2 = tf.Graph()
with g2.as_default():
    x = tf.constant(2.0, name="x")
    tf.import_graph_def(g_def)

```

as, after `y` is imported, the `x:0` input it refers to is valid. 

As it stands however, this throws `ValueError: graph_def is invalid at node u'Exp': Input tensor 'x:0' not found in graph_def..`.

**Comment by mrry** [comment]
I don't think this feature should be added to `tf.import_graph_def()`, because it is designed to deal explicitly with correctly typed and valid graphs. The `input_map` argument is available for remapping inputs explicitly, and the following program works:

```python
g2 = tf.Graph()
with g2.as_default():
    x = tf.constant(2.0, name="x")
    tf.import_graph_def(g_def, input_map={"x:0": x})
```

Notice how you had to drop to manipulating the `tf.GraphDef` directly at the protobuf level in order to *create* an incomplete graph. You could easily achieve the behavior you desire by merging the protobufs `g1.as_graph_def()` and `g2.as_graph_def()`, and then use `tf.import_graph_def()` to check the validity of the merged graph.

There might be room somewhere in the API for lower-level graph editing (`tf.contrib.graph_editor` for example?), but `tf.import_graph_def()` already packs a lot of functionality into a single function, and adding more implicit behavior would not—in my opinion—improve it.

**Comment by skye** [comment]
It looks like there's nothing to do here so closing this issue. Please reopen if I'm mistaken.
