### ISSUE TITLE
The function 'layers/convolutional.py` does not follow `tf.GraphKeys` convention

### ISSUE THREAD

**Issue by MarvinTeichmann** [tensorflow/tensorflow#7741]
In [convolutional.py](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/layers/convolutional.py) bias and weight variables are created and named `kernel` and `bias`. However according to the conventions defined in [tf.GraphKeys.md](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard8/tf.GraphKeys.md) those variables should be named  `weights` and `biases` and assigned the corresponding collections. There is some (third party) functionality which utilizes this convention, including `tf.contrib.layers.summarize_weights`. 

In addition, the names to be used are also stored in the constants `tf.GraphKeys.WEIGHTS` and `tf.GraphKeys.BIASES`. So instead of writing the strings hard in the code, I would suggest utilizing those constants. Do you agree with that? I am happy to submit a pull request solving this issue, if desired.

**Comment by poxvoculi** [comment]
@fchollet: Is a PR welcome?

**Comment by fchollet** [comment]
No, the proper convention is `kernel` and `bias`, which is used throughout core layers. This has been extensively discussed internally.

**Comment by MarvinTeichmann** [comment]
ok, you are right. From what I understand by now the [https://github.com/tensorflow/tensorflow/blob/master/tensorflow/g3doc/api_docs/python/functions_and_classes/shard8/tf.GraphKeys.md](tf.GraphKeys.md) conventions are not about the names of Variabels but collections those Variabels should be added. 

So  the following lines should be in there:

````
    tf.add_to_collection(tf.GraphKeys.WEIGHTS, self.kernel)
    tf.add_to_collection(tf.GraphKeys.BIASES,  self.bias)
````

I am happy to put this into a pull request.

**Comment by MarkDaoust** [comment]
These keys are almost never used.
The only `layer` that uses them is:  "contrib.layers.legacy_fully_connected".

(Then a few things in contrib.layers book-keeping ops read them, they're mentioned in the contrib/layers/README.md)

There is no way to automatically set these, like with trainable variables.

For it to actually work as `tf.contrib.layers.apply_regularization` wants it to, it would need to be set *everywhere*, not just in convolutional.

So I don't think fixing `convolutional.py` is the right choice. 

Currently the core `tf.layers` is not using them so that may be a clue that they are not part of the future.
