### ISSUE TITLE
Ho to deal with this Message : TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s): Flex ops: FlexTensorListReserve, FlexTensorListSetItem, FlexTensorListStack

### ISSUE THREAD

**Issue by nassimus26** [tensorflow/tensorflow#77704]
### 1. System information

- Linux Ubuntu 16.04
- TensorFlow installation 2.17

I want to convert this model and check if it could run on a Coral Edge TPU

### 2. Code
```
num_classes = 2
base_model = tf.keras.applications.MobileNetV2(
    include_top=False, weights='imagenet', input_tensor=None,
    input_shape=input_shape,
    pooling=None, 
)
for layer in base_model.layers:
    layer.trainable = False
base_model.summary()
cnn = models.Sequential()
cnn.add(base_model)
cnn.add(layers.GlobalAveragePooling2D())
cnn.add(layers.Dropout(0.2))
base_model.trainable = False
model = models.Sequential()
print(full_input_shape)
model.add(layers.TimeDistributed(cnn, input_shape=full_input_shape))
model.add(layers.LSTM(nbr_frame, return_sequences=True))
model.add(layers.TimeDistributed(layers.Dense(nbr_frame, activation='relu')))
model.add(layers.Flatten())
model.add(layers.Dense(164, activation='relu', name="filter1"))
model.add(layers.Dropout(0.2))
model.add(layers.Dense(24, activation='sigmoid', name="filter2"))
model.add(layers.Dropout(0.1))
model.add(layers.Dense(num_classes, activation="sigmoid", name="last"))
rms = optimizers.RMSprop()
metrics = [tf.keras.metrics.CategoricalAccuracy('accuracy', dtype=tf.float32)]
loss = tf.keras.losses.CategoricalCrossentropy()
model.compile(
    loss=loss,
    optimizer= rms,
    metrics=metrics
)
#####.....training the model ... ######
converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.target_spec.supported_ops = [
  tf.lite.OpsSet.TFLITE_BUILTINS, # enable TensorFlow Lite ops.
  tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.
]
converter.experimental_new_converter = True
tflite_model = converter.convert()
open("fights.tflite", "wb").write(tflite_model)
```

I am getting this message (I have no idea how to deal with this, I didn't find any relevant documentation about this message):

```
W0000 00:00:1728657905.522324    4234 tf_tfl_flatbuffer_helpers.cc:392] Ignored output_format.
W0000 00:00:1728657905.522345    4234 tf_tfl_flatbuffer_helpers.cc:395] Ignored drop_control_dependency.
2024-10-11 16:45:05.522588: I tensorflow/cc/saved_model/reader.cc:83] Reading SavedModel from: /tmp/tmpwe7b0rla
2024-10-11 16:45:05.543656: I tensorflow/cc/saved_model/reader.cc:52] Reading meta graph with tags { serve }
2024-10-11 16:45:05.543697: I tensorflow/cc/saved_model/reader.cc:147] Reading SavedModel debug info (if present) from: /tmp/tmpwe7b0rla
2024-10-11 16:45:05.843740: I tensorflow/cc/saved_model/loader.cc:236] Restoring SavedModel bundle.
2024-10-11 16:45:06.979508: I tensorflow/cc/saved_model/loader.cc:220] Running initialization op on SavedModel bundle at path: /tmp/tmpwe7b0rla
2024-10-11 16:45:07.522614: I tensorflow/cc/saved_model/loader.cc:462] SavedModel load for tags { serve }; Status: success: OK. Took 2000031 microseconds.
2024-10-11 16:45:10.755926: W tensorflow/compiler/mlir/lite/flatbuffer_export.cc:3463] TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):
Flex ops: FlexTensorListReserve, FlexTensorListSetItem, FlexTensorListStack
Details:
	tf.TensorListReserve(tensor<2xi32>, tensor<i32>) -> (tensor<!tf_type.variant<tensor<?x10xf32>>>) : {device = ""}
	tf.TensorListSetItem(tensor<!tf_type.variant<tensor<?x10xf32>>>, tensor<i32>, tensor<?x10xf32>) -> (tensor<!tf_type.variant<tensor<?x10xf32>>>) : {device = "", resize_if_index_out_of_bounds = false}
	tf.TensorListStack(tensor<!tf_type.variant<tensor<?x10xf32>>>, tensor<2xi32>) -> (tensor<10x?x10xf32>) : {device = "", num_elements = 10 : i64}
See instructions: https://www.tensorflow.org/lite/guide/ops_select
```

**Comment by gaikwadrahul8** [comment]
Hi, @nassimus26 

I apologize for the delayed response, if possible could you please help us with Google colab to reproduce the same bahavior from our end to investigate this issue further from our end ? 

Thank you for your cooperation and patience.

**Comment by fergushenderson** [comment]
>   tf.lite.OpsSet.SELECT_TF_OPS # enable TensorFlow ops.

Try removing that line?

In general that is needed for running on CPU, if your model contains TF ops that can't be converted into TF Lite ops.
But I don't think such ops will run on EdgeTPU.  If you remove that line, either it will now just work, or if not you should get some information from the converter about which ops can't be converted.

**Comment by gaikwadrahul8** [comment]
Hi, @nassimus26

As far I know that  message indicates that your model contains TensorFlow operations that are not natively supported in TFLite and requires the Flex delegate. Try using a simpler architecture that is known to work with Edge TPU. Use the Edge TPU compatibility checker tool and quantize your model to **INT8**, you'll have to replace `TimeDistributed` and `LSTM` with supported operations mentioned [here](https://coral.ai/docs/edgetpu/models-intro/#supported-operations)

You can use Flex Delegate to avoid this message `TFLite interpreter needs to link Flex delegate in order to run the model since it contains the following Select TFop(s):Flex ops: FlexTensorListReserve, FlexTensorListSetItem, FlexTensorListStack` but as you mentioned in the issue temple after converting the model to TFLite you want to run on Coral Edge TPU so which is not recommended for Edge TPU because the Edge TPU does not currently support the Flex Delegate

Please refer this [supported operations on the Edge TPU](https://coral.ai/docs/edgetpu/models-intro/#supported-operations) in that `TimeDistributed` is not supported operations and unidirectional `LSTM` only supported

If I have missed something here please let me know. 

Thank you for your cooperation and patience.
