### ISSUE TITLE
Getting the following the error while importing

### ISSUE THREAD

**Issue by sahil210695** [tensorflow/tensorflow#7809]
python bin/run_analysis.py
Traceback (most recent call last):
  File "bin/run_analysis.py", line 7, in <module>
    from src.run_analysis import analyze, render_results_as_images
  File "/DeepOSM/src/run_analysis.py", line 6, in <module>
    import label_chunks_cnn_cifar
  File "/DeepOSM/src/label_chunks_cnn_cifar.py", line 11, in <module>
    import tflearn
  File "/usr/local/lib/python2.7/dist-packages/tflearn/__init__.py", line 21, in <module>
    from .layers import normalization
  File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/__init__.py", line 10, in <module>
    from .recurrent import lstm, gru, simple_rnn, bidirectional_rnn, \
  File "/usr/local/lib/python2.7/dist-packages/tflearn/layers/recurrent.py", line 8, in <module>
    from tensorflow.contrib.rnn.python.ops.core_rnn import static_rnn as _rnn, \
ImportError: No module named core_rnn

while running the github project [https://github.com/zilongzhong/DeepOSM](url)
In this one I am able to create training data successfully but not able to run_analysis.py and while runnin I'm getting this error and

**Comment by aselle** [comment]
This appears to be an issue with DeepOSM. Please file a bug on their issue tracker.

**Comment by sahil210695** [comment]
Already raised an issue but I think this one is with tensorflow. can you help me in this ?

**Comment by aselle** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks! My feeling is that DeepOSM has not updated for TensorFlow 1.0 yet and you are using TensorFlow 1.0, but that is speculation, since you didn't mention which versions.

**Comment by sahil210695** [comment]
Apple Macbook Pro
Processor: 2.2 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
Using with Docker
Docker Version: 1.12.6 (14937)
Tensorflow Version: 0.8.0

also tried with tensorflow version 1.0.0 got the same error and tried the middle versions also
like tensorflow 0.10, 0.11, 0.12 .

**Comment by clrogers2** [comment]
I had the same issue, but with a clean install of python 3.5, Tensorflow 0.12 and TFlearn 0.3 in a conda environment. After checking to confirm that this module was missing in my site-packages folder, I checked the Github repository for Tensorflow and discovered that 0.12 did not have the core_rnn module (possibly due to a rollback), but 1.0 did. The fix for me was to update to Tensorflow 1.0. 

I've done some limited tests to verify that TFLearn is working with Tensorflow 1.0, and so far so good.

**Comment by jtsheng** [comment]
Is there a way to use core_rnn without upgrading to 1.0?

**Comment by aselle** [comment]
@ebrevdo, I believe the answer is no, can you confirm?

**Comment by ebrevdo** [comment]
That's right; you must update to TF 1.0 since that is what TFLearn seems to
be targeting.

**Comment by av8ramit** [comment]
Please try the upgrade suggestions and reopen if there is still an issue.
