### ISSUE TITLE
How to disable peer to peer gpu memory accessing?

### ISSUE THREAD

**Issue by AlvinChen13** [tensorflow/tensorflow#7810]
Our system with 2GPUs always reboot if run training with 2GPUs, but 1 GPU is OK. And the cuda testing case of 'simpleP2P' also make the system reboot.

How could I disable the peer to peer feature?

**Comment by yaroslavvb** [comment]
So you want to disable DMA because it's buggy even though NVidia driver reports that DMA is available? Not sure there's this level of fine-grained configuration at TF level, cc @poxvoculi just in case

**Comment by poxvoculi** [comment]
Do you want to disable all direct memory transfers between the two GPUs, or just make it so that only one GPU is visible to TF?  The second can be done with the CUDA_VISIBLE_DEVICES env variable.

I believe that TF should never dereference a foreign GPU pointer and thus trigger automatic DMA.  If you're using 2 GPUs they should appear as separate devices and all memory transfers will be done via DeviceToDeviceCopy which ultimately turns into a cudaMemcpy call which uses DMA to do a transfer over the PCI bus.   If TF can only see and use one GPU, you'll never trigger a DMA operation involving the other GPU.  If you want to use both GPUs, but stage all transfers via CPU RAM and never direct DMA between the GPUs, that's harder: I don't think there's a setting to accomplish that.  One technique might be always to explicitly copy to a CPU resident tensor before forwarding a value to the other GPU.

**Comment by AlvinChen13** [comment]
@poxvoculi We have another system&1 2 GPUs are connected by SOC legend, so the HW is not support peer to peer memory accessing (I mean GPUDirect), this system has no issue, and I believe it should do DeviceToDeviceCopy also. But our current system&2, the 2 GPUs are connected by PXI which is supported GPPUDirect, and it will cause the system reboot. CUDA has a testing program 'simpleP2P' can test the peer to peer memory accessing. For system &1, 'simpleP2P' will not run since the GPU connection doesn't support it, but for system&2, 'simpleP2P' will make the system reboot. It must be HW or driver issue. To workaround it, I want to disable the GPUDirect feature. For Tensorflow, I find the following code: (./tensorflow/stream_executor/cuda/cuda_gpu_executor.cc)
bool CUDAExecutor::CanEnablePeerAccessTo(StreamExecutorInterface *other) {
  CUDAExecutor *cuda_other = static_cast<CUDAExecutor *>(other);
  return CUDADriver::CanEnablePeerAccess(context_, cuda_other->context_);
}
I'd like to hack the code to make 'CUDAExecutor::CanEnablePeerAccessTo' always return 'false'.

**Comment by bobpoekert** [comment]
@AlvinChen13 did you ever manage to resolve this? I'm having the same issue.

**Comment by dujiangsu** [comment]
Hi AlvinChen13, 

I have the same requirement to disable TF's P2P feature and you provide me with a feasible method. Could you please tell me the result about changing the code you claimed?
