### ISSUE TITLE
ResNet model has wrong output shape

### ISSUE THREAD

**Issue by Lorsu** [tensorflow/tensorflow#78111]
###  Issue

I applied the [tutorial](https://ai.google.dev/edge/litert/models/post_training_integer_quant) for post-training integer quantization to a ResNet model, but the conversion leads to a model with a wrong output shape of [   1    7    7 2048], instead of a 1000-element vector

### 1. System information

Google Colab, with the default tensorlow 2.17

### 2. Code

the image_array is a numpy array of shape (n, 224, 224, 3) and dtype float32

```
model = tf.keras.applications.ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))

def representative_data_gen():
  for input_value in tf.data.Dataset.from_tensor_slices(image_array).batch(1).take(100):
    yield [input_value]

converter = tf.lite.TFLiteConverter.from_keras_model(model)
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
# Ensure that if any ops can't be quantized, the converter throws an error
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
# Set the input and output tensors to uint8 (APIs added in r2.3)
converter.inference_input_type = tf.uint8
converter.inference_output_type = tf.uint8

tflite_model_quant = converter.convert()

output_details = interpreter.get_output_details()[0]
for key in output_details.keys():
  print(key, output_details[key])
```

**Comment by gaikwadrahul8** [comment]
Hi, @Lorsu 

I apologize for the delayed response, thank you for bringing this issue to our attention if possible could you please help us with exact Google colab notebook which you created **ResNet** model to replicate the same behavior from our end ? 

Thank you for your cooperation and patience.

**Comment by gaikwadrahul8** [comment]
Hi, @Lorsu 

It seems like the issue you're facing is because you're using `include_top=False` in the `ResNet50` model which removes the final classification layers. To get the **1000** element output vector we need to include the top layers by setting `include_top=True` so model includes the final classification layers with output 1000 element vector corresponding to the **1000** ImageNet classes.This is useful when you want to use the model for ImageNet classification tasks.
Please refer this [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/b871f283d9f579b03b6d959ca721b7f7/tflite-issue-78111.ipynb) 

If I have missed something here please let me know.

Thank you for your cooperation and patience.

**Comment by Lorsu** [comment]
> Hi, @Lorsu
> 
> It seems like the issue you're facing is because you're using `include_top=False` in the `ResNet50` model which removes the final classification layers. To get the **1000** element output vector we need to include the top layers by setting `include_top=True` so model includes the final classification layers with output 1000 element vector corresponding to the **1000** ImageNet classes.This is useful when you want to use the model for ImageNet classification tasks. Please refer this [gist-file](https://colab.sandbox.google.com/gist/gaikwadrahul8/b871f283d9f579b03b6d959ca721b7f7/tflite-issue-78111.ipynb)
> 
> If I have missed something here please let me know.
> 
> Thank you for your cooperation and patience.

yes, the issue is in the include_top parameter, thank you really much
