### ISSUE TITLE
Primary install page returning 404 https://www.tensorflow.org/get_started/os_setup 

### ISSUE THREAD

**Issue by apiszcz** [tensorflow/tensorflow#7824]
https://www.tensorflow.org/get_started/os_setup 

404. That's an error.

The requested URL was not found on this server.
That's all we know.

**Comment by dr4b** [comment]
Hey, I'm assuming you got to that page through a Google search, or a link from elsewhere, not through navigation on the Tensorflow site itself, right?

We've been redoing a lot of the site structure for tensorflow.org and haven't propagated all of it out to github quite yet, but the entire installing section of getting started -- covered in the os_setup doc -- is now here: 

https://www.tensorflow.org/install/

I'll put in a redirect for that particular file though, since we didn't catch it before, so it should go to the proper place instead of a 404 for you.

**Comment by apiszcz** [comment]
Correct, the page was a google search result. Thank you.
