### ISSUE TITLE
word2vec at tensorflow 1.0

### ISSUE THREAD

**Issue by yuquanle** [tensorflow/tensorflow#7844]
hello everyone
I have a error “
Traceback (most recent call last):
  File "D:/software install/Pycharm/pycharm workplace/Word2vecTest/word2vec.py", line 45, in <module>
    word2vec = tf.load_op_library(os.path.join(os.path.dirname(os.path.realpath(__file__)), 'word2vec_ops.so'))
  File "C:\Users\yuquanle\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py", line 63, in load_op_library
    raise errors_impl._make_specific_exception(None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: D:\software install\Pycharm\pycharm workplace\Word2vecTest\word2vec_ops.so not found”

But that file(word2vec_ops.so) I have used ubuntu to generate the document.

**Comment by poxvoculi** [comment]
Please ensure you are running the most recent version, and include all the information requested in the issues template.

**Comment by icyJoseph** [comment]
Hi,

I can follow up on what this issue is. 

When running tensorflow_models/tutorials/embedding/word2vec.py in Windows 10, it fails. Because we do not have the word2vec_ops.so file. 

### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
http://stackoverflow.com/questions/42106032/tensorflow-word2vec-error

### Environment info
Operating System: Windows 10

### If possible, provide a minimal reproducible example (We usually don't have time to read hundreds of lines of your code)
Run tensorflow_models/tutorials/embedding/word2vec.py on windows. 

Hope this clarifies further. Perhaps we could have some kind of source files to make or gcc through cygwin?

/J

**Comment by icyJoseph** [comment]
I tried to fix this issue, by updating my Tensorflow and then running:

`gcc -std=c++11 -shared word2vec_ops.cc word2vec_kernels.cc -o word2vec_ops.so -fPIC -I C:/Python35/lib/site-packages/tensorflow/include -O2 -D_GLIBCXX_USE_CXX11_ABI=0
`

which outputs:

```
word2vec_ops.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* Copyright 2015 The TensorFlow Authors. All Rights Reserved.
 ^
word2vec_ops.cc:13:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
 #include "tensorflow/core/framework/op.h"
                                          ^
compilation terminated.
word2vec_kernels.cc:1:0: warning: -fPIC ignored for target (all code is position independent)
 /* Copyright 2015 The TensorFlow Authors. All Rights Reserved.
 ^
word2vec_kernels.cc:13:42: fatal error: tensorflow/core/framework/op.h: No such file or directory
 #include "tensorflow/core/framework/op.h"
                                          ^
compilation terminated.
```
Naturally I traveled to tensorflow/core/framework and there was no op.h 

I will continue to explore a solution. Or am I missing something obvious?

/J

**Comment by yuquanle** [comment]
@poxvoculi
@icyJoseph
the environment is tensorflow 1.0，but in windows10 is fail，the file word2vec_ops.so i use ubuntu generate and copy to windows10 . 
In the windows10 ，the error is：

 File "C:\Users\yuquanle\Anaconda3\lib\site-packages\tensorflow\python\framework\load_library.py", line 63, in load_op_library
    raise errors_impl._make_specific_exception(None, None, error_msg, error_code)
tensorflow.python.framework.errors_impl.NotFoundError: D:\software install\Pycharm\pycharm workplace\Word2vecTest\word2vec_ops.so not found

but the word2vec_ops.so already exists.

but in ubuntu ，it can run successfully. I want to know the code is only support in linux？

**Comment by icyJoseph** [comment]
@yuquanle 
Hi,
The problem is that .so extensions do not work on windows. So what you'd need to do is build Tensorflow on Windows as it is shown here:

https://github.com/tensorflow/tensorflow/tree/r0.12/tensorflow/contrib/cmake

I will execute that step list in the upcoming days and report back to you. In the mean time, enjoy TF :)!

**Comment by prb12** [comment]
@keveman @mmry I'm guessing that dynamically loaded user ops on Windows10 may be difficult?

**Comment by wdma** [comment]
I am seeing the same errors as mentioned in this thread.  Specifically:

tensorflow/core/framework/op.h: No such file or directory

and

./word2vec_ops.so: cannot open shared object file: No such file or directory

my code is cloned from https://github.com/tensorflow/tensorflow

Regarding the first error, as far as I can tell, op.h is present in the GitHub repository, so I do not know why it cannot be found.

word2vec_ops.so indeed does not exist in my local directory nor in the GitHub repository.  

Is there a solution here?
