### ISSUE TITLE
Dockerfile version error

### ISSUE THREAD

**Issue by sveesible** [tensorflow/tensorflow#7885]
Version of TensorFlow was incorrectly updated in the Dockerfile
tensorflow/blob/master/tensorflow/tools/docker/Dockerfile 

` http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-0.0.0-cp27-none-linux_x86_64.whl`

It should probably be the 1.0.0 release not the 0.0.0 release
` http://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp27-none-linux_x86_64.whl`

**Comment by caisq** [comment]
Please note that this invalid version string (0.0.0) is intentional. The Dockerfiles in tools/docker are not meant to be used for direct `docker build` calls. Instead, they are meant to be called from the script [tools/docker/parameterized_docker_build.sh](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/tools/docker/parameterized_docker_build.sh). The doc string of the script contains use instructions.

**Comment by sveesible** [comment]
The Readme.md file says to use this command:

$ docker build --pull -t $USER/tensorflow-suffix -f Dockerfile.suffix .

**Comment by caisq** [comment]
@sveesible Good point. I'll make a note to update the README.md file. Re-opening this issue.

**Comment by girving** [comment]
@caisq What's the status here?

**Comment by caisq** [comment]
Working on a PR. Sorry for the delay.
