### ISSUE TITLE
TensorBoard Image download fails if I expand some node before download

### ISSUE THREAD

**Issue by SMH17** [tensorflow/tensorflow#7911]
TensorBoard seems unable to download flow diagram picture if before download picture I expand some node. In the save picture window the name of picture isn't generated, appears a generic "download" filename, and if I click "save", download starts but fails instantly. 
![sample_pic](https://cloud.githubusercontent.com/assets/8108287/23348702/ee3061fc-fcac-11e6-9c79-73df698cca0f.JPG)

Tensorflow v 1.0.0
Windows 10 x64

**Comment by tatatodd** [comment]
@dandelionmane @jart might have some ideas here.

**Comment by chihuahua** [comment]
I am going to tentatively close this issue because I cannot reproduce it. Feel free to re-open as an issue within the new repository for TensorBoard: https://github.com/tensorflow/tensorboard/issues

tensorflow/tensorflow will no longer accept TensorBoard-related issues. I am sorry for not having responded.

I did though file a different but related issue: tensorflow/tensorboard#88
