### ISSUE TITLE
XLA standalone

### ISSUE THREAD

**Issue by bhack** [tensorflow/tensorflow#7941]
I don't know all the internals but what do you think to standalone XLA? I think that targetting HLO IR could be of general use also for other opensource projects. Expecially if the streamexecutor CUDA and OpenCL component it is mainlined in LLVM parallel-lib repository.

**Comment by tatatodd** [comment]
It's certainly possible to target TensorFlow's XLA HLO IR from other projects, though our team doesn't have the bandwidth to support efforts like this in depth right now.

I'm closing this issue for now since it isn't a bug or feature request that we'll be addressing in the near term. However, if you **are** planning a major initiative to target XLA from another project, please do let us know sooner rather than later.  XLA is under extremely active development, so staying in touch with us along the way will help you avoid a certain amount of frustration.

Thanks very much!
