### ISSUE TITLE
"data_format == FORMAT_NHWC" error discrepancy

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#7967]
`tf.nn.conv2d()`'s behaviour on throwing the "data_format == FORMAT_NHWC" assertion seems odd. I cooked up a minimal example:

```py
input_np = np.zeros([1,1,4,4], dtype=np.float32)
x = tf.constant(input_np, dtype=tf.float32)
filter = tf.ones([1,1,1,1], dtype=tf.float32)
out = tf.nn.conv2d(x, filter, [1,1,1,1], padding='SAME', data_format='NCHW')
sess= tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(out)
```
Throws:
```
F tensorflow/core/kernels/conv_ops.cc:62] Check failed: data_format == FORMAT_NHWC
Generic conv implementation only supports NHWC tensor format for now.
Aborted (core dumped)
```

While this works fine, and it uses exactly the same variables, but now I am feeding a placeholder.
```py
input_np = np.zeros([1,1,4,4], dtype=np.float32)
x = tf.placeholder("float", [None, 1,4,4])
filter = tf.ones([1,1,1,1], dtype=tf.float32)
out = tf.nn.conv2d(x, filter, [1,1,1,1], padding='SAME', data_format='NCHW')
sess= tf.Session()
sess.run(tf.global_variables_initializer())
sess.run(out, feed_dict={x:input_np})
```

Using 0.12.1, error is consistent across: OS-X as Ubuntu 14.04, regardless of CPU or GPU device placement.

**Comment by hawkinsp** [comment]
I think what's happening here is:
* the GPU implementation of Convolution support NCHW format, but the CPU implementation does not
* the CPU implementation crashes with a CHECK() failure if passed an NCHW format input rather than failing gracefully.
* in your first example, the convolution is a constant (does not depend on any variables or placeholders), and the constant-folder attempts to use the CPU implementation to evaluate the convolution. This causes a crash.

The fix is probably just to make the CPU convolution fail more gracefully for NCHW inputs (via an OP_REQUIRES).

**Comment by tatatodd** [comment]
@TimZaman Perhaps you can try this on TensorFlow 1.0 to see if this is fixed?

**Comment by prb12** [comment]
#8151 is a duplicate and has more information.
Closing this one.

**Comment by Akila92** [comment]
I have encountered the same error. Im using a CPU not GPU. So I changed the data format of the tensors to overcome in the code.Above Suggested solutions will not work for CPU.
More can be found in tensorflow documentation. Refer to data formats
https://www.tensorflow.org/guide/performance/overview
