### ISSUE TITLE
Bottom-right precedence of padding?

### ISSUE THREAD

**Issue by TimZaman** [tensorflow/tensorflow#7969]
Why has Tensorflow chosen to prefer padding on the bottom right?
With 'SAME' padding, to me it would feel logical to start the kernel's center anchor at the first real pixel. Due to the use of asymmetric padding, this results in a discrepancy with some other frameworks. I do understand that asymmetric padding in principle is good because otherwise one would be left with an unused padding row/column.

![image](https://cloud.githubusercontent.com/assets/7721540/23457266/e6b57d8e-fe7f-11e6-9b88-dc793ce10c73.png)

**Comment by tatatodd** [comment]
@TimZaman Thanks for the comment.  I assume you've seen the following documentation, since you understand how SAME padding works:
https://www.tensorflow.org/api_guides/python/nn#Convolution

But this question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by TimZaman** [comment]
Because Tensorflow does this differently than other frameworks, it breaks weight compatibility with other frameworks. If the padding precedence was given to the left and top rows, it would align with other frameworks (and cudnn). Therefore I asked the question here, and ask the developers directly why this was chosen in this way.
