### ISSUE TITLE
A small problem about tf.case function and Tensor's shape

### ISSUE THREAD

**Issue by fuhuamosi** [tensorflow/tensorflow#8003]
I write the following code on jupyter notebook:
a = tf.placeholder(shape=(5, ),  dtype=tf.float32)
b = tf.placeholder(shape=(5, ),  dtype=tf.float32)
x = tf.constant(0)
y = tf.constant(0)
f1 = lambda: a
f2 = lambda: b
res_tensor = tf.case([ (tf.not_equal(x, y), f1) ], default=f2)

But I found that the res_tensor's shape is unknown rather than (5, ).

**Comment by MicaelCarvalho** [comment]
I came here to report the exact same behavior, and saw your issue on the first page.

The same goes for vectors:

`import tensorflow as tf

value_1 = [tf.placeholder(tf.float32, shape=(2, 3, 4)), tf.placeholder(tf.float32, shape=(5, 6, 7)), tf.placeholder(tf.float32, shape=(8, 9, 10))]
value_2 = [tf.placeholder(tf.float32, shape=(2, 3, 4)), tf.placeholder(tf.float32, shape=(5, 6, 7)), tf.placeholder(tf.float32, shape=(8, 9, 10))]
switcher = tf.placeholder(tf.bool)

def get_value_1():
	return value_1

def get_value_2():
	return value_2

batch_sample = tf.case([(switcher, get_value_1)], default=get_value_2, exclusive=True)

print(get_value_1())
print(get_value_2())
print(batch_sample)`

A simple explanation is that tf.case can handle different output shapes for different cases. For example, if we change value_2 to have different shapes than value_1 (e.g. 2,3,3 instead of 2,3,4) the case will still work.

However, I do believe it would be of best interest to have a defined output shape if all cases have the same shape. It would save us from forcing the shape with something like:

`for k in range(len(batch_sample)): batch_sample[k].set_shape(get_value_1()[k].shape)`

However, this isn't critical, as there is a rather clean workaround.

**Comment by tatatodd** [comment]
Thanks for reporting the issue @fuhuamosi !

@MicaelCarvalho is exactly right.  In general, it's impossible for `tf.case` to know the output shape in all scenarios.

It's true that in the original example, it looks "easy" to infer the output shape.  But the trade-off is the additional code complexity to implement this behavior, that only works for a handful of scenarios.  In typical real usage of `tf.case`, we either won't be able to infer the output shape, or the output shape isn't actually necessary statically.

Closing this out since we won't be implementing this.  If you feel I've made a mistake, feel free to comment on this issue, and I'll re-open it.  Thanks!

**Comment by vanpersie32** [comment]
@MicaelCarvalho  hey, what if the output of tf.case is sent to conv2d which don't support for input with rank none. Does manually forcing the shape of output of tf.case work?

**Comment by MicaelCarvalho** [comment]
@vanpersie32 calling `your_tensor.set_shape(...)` should do it, assuming you know the expected shape of the tensor. That's exactly what the last line of code in my previous message does. :-)

**Comment by buc030** [comment]
I feel this should be implemented. Or at least an informative warning message. Or remove this API...

As the justification on the first place for such high level methods (tf.case, instead of nested tf.cond) is usability, to my opinion, it doesnt make sense to expect the programmer to browse through github issues. This is making TF as some kind of "magic", where replacing equivalent statements makes a difference :)
