### ISSUE TITLE
tf.contrib.rnn module object is not callable. 

### ISSUE THREAD

**Issue by dorienh** [tensorflow/tensorflow#8005]
I am trying to run a tutorial (http://r2rt.com/recurrent-neural-networks-in-tensorflow-ii.html) and have some issue with modules that have moved. 

I researched a bit and found that some classes have moved and fixed: 
tf.nn.rnn_cell.BasicRNNCell(state_size)
to 
tf.contrib.rnn.BasicRNNCell(state_size)

This works now.

However, I have this function I can't seem to fix: 

rnn_outputs, final_state = tf.nn.rnn(cell, rnn_inputs, initial_state=init_state)
--> as expected, says: module 'tensorflow.python.ops.nn' has no attribute 'rnn'

So I tried: 
rnn_outputs, final_state = tf.contrib.rnn(cell, rnn_inputs, initial_state=init_state)

But that says: 'module' object is not callable

I am using python3 (tried 2 as well), with a fresh installed TensorFlow 1.0.0 through pip3. 

I tried looking at the API, but it's not making much sense to me, as I am still going through the tutorial to try to understand what is happening. I would think maybe the arguments have changed, or maybe this is in a sub-function now? https://www.tensorflow.org/api_docs/python/tf/contrib/rnn

**Comment by tatatodd** [comment]
@dorienh Yes, the rnn logic moved from `tf.contrib.rnn` to `tf.nn` for TensorFlow 1.0

I suggest you contact the authors of the tutorial, for them to make the appropriate updates.

I know renaming and code-moving is painful, but note that now that we're on TensorFlow 1.0, we have API compatibility guarantees:
https://www.tensorflow.org/programmers_guide/version_semantics

If you're looking for tutorials, here's one for RNNs, with other links on the left as well:
https://www.tensorflow.org/tutorials/recurrent

Note that this question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
