### ISSUE TITLE
tensorflow-gpu fail for windows 7 T_T

### ISSUE THREAD

**Issue by jumemae** [tensorflow/tensorflow#8006]
My computer installed tensorflow-gpu for windows 7 (FX 2800M)

but GPU not understanding my counter...T_T

always tensorflow cpu understandig...

CUDA  v8.0 and v6.5 Cudnn v5.1 and v 2.1

Fail log is 
F c:\tf_jenkins\home\workspace\release-win\device\gpu\os\windows\tensorflow\stream_executor\cuda\cuda_driver.cc:94] Check failed: s.ok() could not find cuDevice

plz.. help me!!

**Comment by microtony** [comment]
According to this [page](https://developer.nvidia.com/cuda-legacy-gpus), Quadro FX 2800M only has CUDA Compute Capability 1.1 and therefore is not supported. 3.0 is the minimum requirement.

**Comment by tatatodd** [comment]
Thanks for filing the issue @jumemae , and thanks for the reply @microtony !

For future reference, this type of question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
