### ISSUE TITLE
AttributeError: module 'tensorflow' has no attribute 'streaming_accuracy'

### ISSUE THREAD

**Issue by jdvala** [tensorflow/tensorflow#8017]
```
#Accuracy calculation
accuracy = tf.streaming_accuracy(y_p, mnist.train.lables, weights=None,
                       metrics_collections=None, updates_collections=None,
                       name="Accuracy")
acc = sess.run(accuracy)
print (acc)
```
while calculating Accuracy in my model I encountered this error!
Don't have any clue why?

**Comment by tatatodd** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there.

Also, I suggest on your StackOverflow question that you include the version of TensorFlow you're using.

Thanks!
