### ISSUE TITLE
TensorBoard not finding files to display, suggested solution?

### ISSUE THREAD

**Issue by dartdog** [tensorflow/tensorflow#8030]
It seems that the default location for the log files, for most tutorials is in the system root tmp directory.. eg /tmp. This directory cannot normally be found by starting the tensorboard program according to instructions, nor do the debug instructions on the readme page for Tensorboard help at all.. Since they: Grep/ starting in debug Mode etc.. also depend on seeing directories within the user space.

I'd suggest simply modifying the tutorials to add the ./tmp so that the files end up in user space and also that the tensorBoard start up default directory be configured to match, only requiring configuration when needed for larger and more complex installs.

### Environment info
Operating System:
Ubuntu 16.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by tatatodd** [comment]
@jart might have some suggestions here

**Comment by wchargin** [comment]
I don't really understand what you're asking. TensorBoard works just fine with logs stored in `/tmp/`; that's where I put essentially everything. It also works fine with `~/tmp`, but I don't see any reason to change the existing tutorials to use this instead. Indeed, I'd argue that `/tmp/` is better because it's cleared when you restart the machine.

If you're still having issues, try running `tensorboard --logdir /tmp/mnist_tutorial` or whatever your directory is. If that doesn't work, please feel free to report it to us by creating an issue in our new repository at https://github.com/tensorflow/tensorboard/issues. Thanks!
