### ISSUE TITLE
Is it able to set `allow_growth=True` to environment variables?

### ISSUE THREAD

**Issue by ckcz123** [tensorflow/tensorflow#8040]
Hi all, we a device with 3 gpus, and there are several people who are learning deep-learning.
However, while using tensorflow, all gpus will be used, which causes others not able to calculate.

We know setting `config.gpu_options.allow_growth = True` in python code can avoid this, but there are always some people who forget to do this.

So I wonder if we can set `config.gpu_options.allow_growth = True` to default (such as environment variables)? Thanks!

**Comment by yaroslavvb** [comment]
A PR to add this might take some work, but maybe there's a work-around using sitecustomize. IE, you can use sitecustomize to force Python to always run some code, and this code could be used to load tensorflow, and then monkey session init to use custom config. 

IE something like this:
oldinit = tf.Session.__init__
def myinit(session_object, target='', graph=None, config=None):
    print("Intercepted!")
    config = tf.ConfigProto()
    config.gpu_options.allow_growth = True
tf.Session.__init__ = myinit

This is more flexible than env-var on the TensorFlow side because you can do arbitrary configuration. For instance, you could run some code that automatically selects least-used GPU and restricts TensorFlow to use it through `CUDA_VISIBLE_DEVICES` as I'm doing in [notebook_util](https://github.com/yaroslavvb/stuff/blob/master/notebook_util.py#L46)

**Comment by tatatodd** [comment]
Thanks for the suggestion @yaroslavvb !

@ckcz123 There isn't such a mechanism to set session config defaults based on an environment variable.  Although it would be convenient in the scenario you're describing, such a mechanism would also make it harder to reason about what a particular snippet of code is expected to do.  In general we'd like to keep the configuration codepath reasonably straightforward, so I don't think we'll be adding such a mechanism.

Hope that makes sense.  I'm closing this out, but if you feel I'm mistaken, just respond to this issue and I'll re-open it.  Thanks!

**Comment by lucasb-eyer** [comment]
I think this specific option (allow growth) should exist as an env-var flag. Consider the following common scenario:

I only own one machine, which has only one GPU. I sometimes want to run some random person's training code I got on github without it eating all my GPU memory. Because a little later, I want to start a notebook while the training is still running and still be able to do some tensorflow prototyping in it. While your monkey-patching trick is pretty neat, I'd like not to have to paste it into every code that I download.

My point being that whether to consume all GPU memory or not is much more a run-site setting than a code-site setting IMO.

**Comment by yaroslavvb** [comment]
I guess this is a bit of a mismatch between google use-case and open-source use-case -- Google runs single TensorFlow process per GPU.

To avoid having to copy paste this into every snippet, you could do something like this:

`alias python="python -m myconfig`
and then put the snippet into `myconfig`

The general issue about global modifications like environment variables or monkey-patching is that it makes bug reporting harder. You have to make sure users provide copy of code, and also all values of environment variables they used. Then people forget about their environment variables, etc
