### ISSUE TITLE
Make tf.Tensor's magic functions (e.g., `__add__()`) play nice with unknown types

### ISSUE THREAD

**Issue by ageron** [tensorflow/tensorflow#8051]
`tf.Tensor`'s magic functions should return `NotImplemented` rather than raising an exception when they are given an object of an unsupported type (i.e., an object that TensorFlow cannot `convert_to_tensor()`). This would give that object a chance to perform the operation with its reverse magic function (e.g., `__radd__()`). See the code example below. Note that this is what NumPy arrays do.

### Environment info
Operating System: **Ubuntu 16.10**
Installed version of CUDA and cuDNN:  **N/A**
Installed pip package:
https://storage.googleapis.com/tensorflow/linux/cpu/tensorflow-1.0.0-cp35-cp35m-linux_x86_64.whl
TensorFlow version: **1.0.0**

### Reproducible example

```
>>> class AmazingMatrix(object):
...   def __add__(self, b):
...     print("I know how to handle TensorFlow Tensors!")
...   def __radd__(self, a):
...     print("I know how to handle TensorFlow Tensors!")
... 
>>> am = AmazingMatrix()
>>> t = tf.constant([[0.]])
>>> am + t
I know how to handle TensorFlow Tensors!
>>> t + am
Traceback (most recent call last):
[...]/python/ops/math_ops.py", line 799, in binary_op_wrapper
    y = ops.convert_to_tensor(y, dtype=x.dtype.base_dtype, name="y")
[...]
TypeError: Expected float32, got <__main__.AmazingMatrix object at 0x7f5999a73518> of type 'AmazingMatrix' instead.
```

### Related GitHub issues or StackOverflow threads
http://stackoverflow.com/questions/38599637/overloading-tensorflow-tensor-magic-method-priority-similar-to-numpys-array

### What other attempted solutions have you tried?
None. I guess one could create Tensor wrappers, with the appropriate behavior, but it would be quite cumbersome to use.

### Logs or other output that would be helpful
None

**Comment by yaroslavvb** [comment]
Seems like a reasonable.

Can we ensure this doesn't increase probability of bugs such as one fixed by https://github.com/tensorflow/tensorflow/commit/a8c3de3bddf01b4b80c986b3bb81d2a1658be3c8 ?


In that case, "numpy_array+tensorflow_variable" delegated addition to numpy, which used the fact that "variable" supports `__getitem__` to generate a expressions of the form

```
numpy_array[0]+tensorflow_variable[0] 
numpy_array[1]+tensorflow_variable[1]
...
```

This added a bunch of `Slice` ops to the default graph

**Comment by ageron** [comment]
@yaroslavvb That's a great question. I propose the following alternative solution, to avoid any risk.

When a tensor's LHS magic function is called, then before doing anything we check the following conditions (for example for the addition magic functions):
* `type(RHS)` has `__radd__`
* `RHS.__tensor_priority__` is defined and greater than `LHS.__tensor_priority__` (which defaults to 0).

If both conditions apply, then delegate to the RHS (by returning `NotImplemented`). Or else, proceed as usual, and if an error occurs when calling `convert_to_tensor()` and if condition 1 applies, then display a friendly error message explaining the `__tensor_priority__` logic.

The advantages are:
* This gives full control to developers who want to build libraries on top of TensorFlow. If they set `__tensor_priority__`, they can have full control even when tensors are on the LHS.
* This won't break any existing code since nothing changes unless `__tensor_priority__` is defined by the RHS.
* It's consistent with NumPy's approach.
* We don't use `__array_priority__` which may lead to conflicts.
* Compared to the first approach I proposed, this only requires the developer to define `__tensor_priority__` and the error message will explain what to do.

Wdyt?

**Comment by tatatodd** [comment]
Seems reasonable to me too, but I'm not a python expert.  @aselle might have some thoughts on this

**Comment by ageron** [comment]
FYI, I submitted a Pull Request for the proposed `__tensor_priority__` implementation, please comment.

**Comment by shoyer** [comment]
Let me try to provide some context around `__array_priority__` as a NumPy developer. (There has actually been extensive discussion about [removing it entirely](https://github.com/numpy/numpy/issues/5844) going forward, but that's a whole different matter that you probably don't want to get into.)

It exists because NumPy has two different ways of interacting with objects of an unknown type. For example, suppose `array = np.array([1, 2, 3])` and `other = SomeType()`. What should `array + other` give?

1. If `__array_priority__` is unset or less than 1: treat the unknown type as a scalar, and apply the operation in an element-wise fashion over each element of the array, e.g., `array + other` -> `np.array([1 + other, 2 + other, 3 + other])`.
2. If `__array_priority__` is greater than 1: treat the unknown type as an array, and let it try to handle the entire NumPy array, e.g., `array + other` -> `other.__radd__(array)`.

I don't think TensorFlow *ever* wants behavior (1). Hence we don't need `__tensor_priority__`. TensorFlow should stick to Python's default system for overriding arithmetic operations.

Something like one of these solutions seems like a good place to start:

"Try converting everything to a tensor"
```python
# This is possibly not flexible enough, because you might, for example,
# want to define a type (e.g., a tensor with physical units) that is convertible
# to a tensor but preferentially overrides arithmetic.
def __add__(self, other):
  try:
    other = ops.convert_to_tensor(other)
  except TypeError:
    return NotImplemented
  return add_impl(self, other)
```

Or "Let the other type try to override the operation, otherwise convert to tensor" (I like this one better)
```python
KNOWN_TYPES = (tf.Tensor, tf.Variable, ...)

def __add__(self, other):
  # We need exclude known types (including type(self)) to avoid an
  # infinite loop due to similar code in the implementation of Tensor.__radd__
  if not isinstance(other, KNOWN_TYPES):
    # defer to the other type, if it provides an implementation
    result = other.__radd__(self)
    if result is not NotImplemented:
      return result
  # other is known or does not provide an implementation
  other = ops.convert_to_tensor(other)
  return add_impl(self, other)
```

**Comment by ageron** [comment]
Thanks Stephan, awesome insights.  I initially proposed the first solution you suggest. The only problem I see is that the user cannot easily get control in the case where `other` is a subtype of a supported type (the only option would be to somehow force `convert_to_tensor(other)` to raise a `TypeError`, not sure how.  The same is true for the second option you suggest.

Perhaps it's not such a big deal.
Also, I'm wondering, what is the point of trying `convert_to_tensor(other)` if `other` is not a known type? Perhaps we should just return `NotImplemented` systematically in that case?

**Comment by prb12** [comment]
Since there's a pull request in progress, I'm goign to label it as 'contributions welcome' so that this issue doesn't keep needing re-triaging every time somebody comments!

**Comment by shoyer** [comment]
> Also, I'm wondering, what is the point of trying convert_to_tensor(other) if other is not a known type? Perhaps we should just return NotImplemented systematically in that case

Here I was trying to handle other types that can be converted into Tensors but don't know anything about TensorFlow, like built-in Python number and NumPy arrays.

Maybe explicitly listing types to convert is a better idea, e.g.,
```
TYPES_TO_CONVERT = (tf.Variable, number.Number, numpy.ndarray)

def __add__(self, other):
  if isinstance(other, TYPES_TO_CONVERT):
    other = ops.convert_to_tensor(other)
  elif type(other) is not type(self):
    return NotImplemented
  return add_impl(self, other)
```

**Comment by ageron** [comment]
Apparently there's already a `_tensor_conversion_func_registry` containing various base types and their corresponding conversion functions to Tensors, located in `tensorflow.python.framework`.
New conversion functions can be registered using `register_tensor_conversion_function()`, which is part of the [public API](https://www.tensorflow.org/api_docs/python/tf/register_tensor_conversion_function).
So I guess there's already quite a lot of flexibility. The only thing missing is a way to delegate binary ops to the RHS. Perhaps the first option would be sufficient after all: just return `NotImplemented` if a `TypeError` is raised. I'll make the change in the Pull Request.
