### ISSUE TITLE
Missing images in docs

### ISSUE THREAD

**Issue by christopherhesse** [tensorflow/tensorflow#8064]
The page https://www.tensorflow.org/api_docs/python/tf/gather has a broken link to an image: https://www.tensorflow.org/api_docs/images/Gather.png

https://www.tensorflow.org/api_docs/python/tf/scatter_add also has a broken link https://www.tensorflow.org/api_docs/images/ScatterAdd.png

In addition, the images seem to be missing from the tensorflow repo.  Could those be put in there? It is hard to build the docs locally for offline use without the images.

**Comment by ClarkZinzow** [comment]
It looks like those images were deleted from [this folder](https://github.com/tensorflow/tensorflow/tree/9c3043ff3bf31a6a81810b4ce9e87ef936f1f529/tensorflow/g3doc/api_docs/images) in [this commit](https://github.com/tensorflow/tensorflow/commit/854f49bd43588c062b046384f239f64a3d819702).  It looks like those images should be restored to a new tensorflow/docs_src/api_guides/images folder, and the links in the source code documentation need to be changed (e.g., for the ScatterAdd.png image, the image source in [this line](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/ops/state_ops.cc#L289) would need to be changed to the correct link.)

**Comment by tatatodd** [comment]
Thanks for filing the issue @christopherhesse 

Assigning to @dr4b

**Comment by tfboyd** [comment]
The images will likely never get uploaded to GitHub.  The best solution, which does not have a timeline, would be to replace the image links in the GitHub mark down to point to tensorflow.org.  It might be more work than you want to do, but you could try to script it yourself.  Putting the images in GitHub bloats the repo, or so I am told.   Image links should never break over a line due to internal style guides, so a simple find replace might cover a large percent of the situation.  Our publishing process is a big convoluted due to a desire to accept community contributions.

**Comment by wolffg** [comment]
We should restore the images in our internal image repo and fix those links to point to /images.  We need to fix this internally, so I will take this.
