### ISSUE TITLE
relu_layer doesn't appear in tensorflow.org/versions/master/api_docs

### ISSUE THREAD

**Issue by cesarsalgado** [tensorflow/tensorflow#811]
relu_layer has a docstring in the code, but it doesn’t appear in the tensorflow online documentation for some reason.

In case it is not public yet, it should be removed from the cifar example.

**Comment by josh11b** [comment]
I'm not sure whether it is supposed to be public or not.

**Comment by martinwicke** [comment]
It is not supposed to be public, and it will likely be deprecated (and
removed) in favor of layers.fully_connected_relu once that's matured.

I agree using unstable functions in the tutorials is suboptimal, and since
relu_layer is so simple, a simplified version of it should probably be
inlined in cifar.

**Comment by cesarsalgado** [comment]
What about xw_plus_b?

I can make a PR replacing relu_layer and xw_plus_b with public ops in the tutorials. Is someone already working on it?

Is there any other ops that should be replaced in the tutorials?

**Comment by martinwicke** [comment]
Nobody is working on it, if you wrote a pull request, we'd be grateful for it.

**Comment by vrv** [comment]
Looks like it was fixed in #828
