### ISSUE TITLE
gradient_override_map should raise an error if passed invalid gradient names.

### ISSUE THREAD

**Issue by Cogitans** [tensorflow/tensorflow#8138]
Currently, gradient_override_map does not complain if passed in nonsensical information (apart from the simple check to make sure the map is a map from strings to strings).

For instance, the following lines of code run without issue:

` with graph.gradient_override_map({"nonsense": "more_nonsense"}):
      input = tf.sign(input)`

A more subtle point (that happened with me), when attempting to override sign's gradient, the following typo ran without problem:

` with graph.gradient_override_map({"sign": "Identity"}):
      input = tf.sign(input)`
("sign" should be "Sign").

Seems like a fairly simple issue, but I am not quite versed enough in the Tensorflow backend to suggest a fix to this problem.

**Comment by prb12** [comment]
@mrry It looks from the code that this would be difficult to do since `tf.gradient_override_map` is a Python construct and (presumably) doesn't have an easy way to validate the args against all registered op names? 

FWIW, the documentation [here](https://www.tensorflow.org/versions/master/api_docs/python/framework/core_graph_data_structures), does show a clear example where the name of the op whose gradient is being overridden is capitalized whilst the python op wrapper uses the PEP11 naming convention.

It's also still labelled as EXPERIMENTAL in the docs ... Is this still the case, or is it part of the TF1.0 API?

**Comment by mrry** [comment]
Unfortunately it's now part of the 1.0 API so we can't easily change it. It might be possible to validate the names of ops against the `OpDef` registry, which should catch some errors. Over time, however, I think we'll want to standardize on TF functions (which I guess are not yet part of the stable `tf.*` API) as the way to specify overridden gradients for subgraphs and individual ops.

**Comment by Cogitans** [comment]
Agreed that in general the names should match the python functions. I haven't delved into the code as much as I should have, but wouldn't it be possible just to keep a list around in python of everything that got "tf.RegisterGradient(...)"-d and check `gradient_override_map` against it?

**Comment by mrry** [comment]
I don't think the set of names for which `tf.RegisterGradient()` has been called is sufficient for validating the override map keys... for example a common use is to register a temporary gradient for an op that doesn't in general have one.
