### ISSUE TITLE
Get initialized value of variable without resetting

### ISSUE THREAD

**Issue by danijar** [tensorflow/tensorflow#8172]
As far as I know, there is currently no way to get the current value of a variable while ensuring that it has been initialized once. tf.Variable.initialized_value() has a dependency on the initializer that causes the variable to be reset to its initial value every time it is accessed. Using `return tf.cond(tf.is_variable_initialized(variable), lambda: variable.value(), lambda: variable.initialized_value())` does not work since the true-branch of the conditional requires the variable to be initialized, even though the false-branch becomes active.

**Comment by yaroslavvb** [comment]
There's a number of use-cases of dependent variables that can't be handled with `initialized_value`, see https://github.com/tensorflow/tensorflow/issues/4920 for discussion.

I used [smart_initialize](https://gist.github.com/yaroslavvb/d592394c0cedd32513f8fbb87ca05938) that rewrote the graph to automatically initialize the variable on first read, but with VariableV2 change, things changed so that now adding a control dependency in var/read on initializer causes infinite loop. 

I think perhaps the way to fix it is to have add a piece of code that monkey-patches `tf.Variable` class with a version that exposes to the user a Tensor which triggers initialization on first read

**Comment by prb12** [comment]
Yes, this is a bit of a mess with dynamic control flow.  Here's a workaround due to @vrv.   Note the use of `var.read_value()` rather than `var.value()`

```
def initialized_var(t):
  var = tf.Variable(t)
  is_var_init = tf.is_variable_initialized(var)
  return var, tf.cond(is_var_init, lambda: var.read_value(),
                      lambda: var._initializer_op.outputs[0])
```

Please let me know if this works for you.

**Comment by asimshankar** [comment]
Automatically closing due to lack of recent activity. Please update the issue when new information becomes available, and we will reopen the issue. Thanks!
