### ISSUE TITLE
Dirichlet noise returns Nan under jit_compile

### ISSUE THREAD

**Issue by cmarlin** [tensorflow/tensorflow#82461]
### Issue type

Bug

### Have you reproduced the bug with TensorFlow Nightly?

No

### Source

binary

### TensorFlow version

v2.18.0-rc2-4-g6550e4bd802 2.18.0

### Custom code

No

### OS platform and distribution

WSL2

### Python version

3.10.12

### Current behavior?

Function return some Nan values if jit_compile=True

### Standalone code to reproduce the issue

```shell
import tensorflow as tf  # tf.__version__ '2.14.1'
import tensorflow_probability as tfp  # tfp.__version__ '0.22.1'


# @tf.function(jit_compile=True)  # uncomment to trigger bug
def test_exploration_noise(
    prnd: tf.Tensor,
    legal_actions: tf.Tensor,
):
    action_space_size = 9
    batch_size = 2048
    root_dirichlet_alpha = 0.35

    dir_alpha = tf.fill(
            [batch_size, action_space_size], root_dirichlet_alpha
        )
    distribution = tfp.distributions.Dirichlet(dir_alpha * legal_actions)
    noise = distribution.sample(seed=prnd)
    return noise

if __name__ == "__main__":
    seed = tf.constant([ 348206018, 1455008836], dtype=tf.int32)
    new_legal_actions = tf.ones([2048, 9]).numpy()
    new_legal_actions[1212] = [1, 0, 0, 0, 0, 0, 1, 1, 0]  # using line 288 won't trigger bug
    new_legal_actions = tf.convert_to_tensor(new_legal_actions)
    noise = test_exploration_noise(
            # root_dirichlet_alpha=config.root_dirichlet_alpha,
            prnd=seed,
            legal_actions=new_legal_actions,
    )
    print(noise[1212].numpy())
    tf.debugging.assert_all_finite(noise, "invalid noise")
```

### Relevant log output

```shell
without jit:
[0.00337291 0.         0.         0.         0.         0. 0.94923943 0.04738774 0.        ]

with jit:
[nan nan nan nan nan nan nan nan nan]
```

**Comment by cmarlin** [comment]
I couldn't run with nightly

**Comment by Venkat6871** [comment]
Hi **@cmarlin** ,
Apologies for the delay, and thank you for raising your concern. The issue arises because you are multiplying `dir_alpha` by the `legal_action` tensor. If `legal_action` has a value of 0 for a specific action, the corresponding concentration parameter in the Dirichlet distribution becomes 0. This is invalid because the Dirichlet distribution requires all concentration parameters to be strictly positive. Additionally, this issue may occur when using JIT compilation, as XLA might handle zeros differently.
To resolve this, I added a small epsilon value to avoid zeros, and it worked fine for me. Please find the [gist](https://colab.sandbox.google.com/gist/Venkat6871/3b920adf58bf3e078bb7b95fb5fe7857/82461_tf_2-18-0-nightly-v.ipynb) here for reference.

Thank you!
