### ISSUE TITLE
"The TensorFlow library wasn't compiled to use SSE3/SSE4.1/... instructions", "creating context when one is currently active", "Peer access not supported between device ordinals 0 and 1" when running "Hello TensorFlow"

### ISSUE THREAD

**Issue by jw447** [tensorflow/tensorflow#8266]
### What related GitHub issues or StackOverflow threads have you found by searching the web for your problem?
I am running google TensorFlow on google compute engine instance. I started with Hello Tensorflow program and I am reading some warnings.

1. The TensorFlow library wasn't compiled to use SSE3/SSE4.1/SSE4.2/AVX/AVX2/FMA instructions, but these are available on your machine and could speed up CPU computations.
2. successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero.
3. creating context when one is currently active; existing: 0x30fd920
4. Peer access not supported between device ordinals 0 and 1

Can anyone tell me what caused those warnings? First thing I want to know is if my GPUs are actually working on the data are just sent to CPU only?

### Environment info
Operating System: Ubuntu 16.04

### What other attempted solutions have you tried?
I tried run the Hello TensorFlow on both instance with 4 GPUs and instance with 8GPUs.

### Logs or other output that would be helpful
Please see the attachment.

Thank you for your help!

[Terminal Saved Output.txt](https://github.com/tensorflow/tensorflow/files/833162/Terminal.Saved.Output.txt)

**Comment by MicaelCarvalho** [comment]
These are just warnings telling you TF can run faster on CPU if you recompile it by yourself, if you're doing mostly GPU stuff, you don't have to worry about these warnings.

At the end, you're trying to run `tf.run(...)`, and it doesn't exist, so the error seems correct. `job` isn't defined, because you didn't create a session, so it seems correct as well.

By the logs, it seems you are using the GPUs. You can run a script that keeps calculating stuff and run `nvidia-smi` on the terminal to see the GPU usage. Alternatively, you can always manually specify where you want to run something by using `with tf.device('/gpu:0')` for example.

This kind of question would be better addressed on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow), since GitHub is mostly used for bug reporting. ;-)

**Comment by prb12** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

**Comment by paramr** [comment]
Actually it is a good feature request.  SSE4 has been available since 2007 (https://en.wikipedia.org/wiki/SSE4) and https://en.wikipedia.org/wiki/Advanced_Vector_Extensions since 2011.  So seems reasonable to have these enabled by default.

**Comment by yaroslavvb** [comment]
@paramr  There were users who couldn't run official binary because of SSE inclusion -- https://github.com/tensorflow/tensorflow/issues/6809

So the idea is to have slow "lowest common denominator" official release, and then let users build/distribute versions for the gazillion other configurations out there. I post Xeon V3 specialized wheels here -- https://github.com/yaroslavvb/tensorflow-community-wheels

**Comment by mohan-chinnappan-n** [comment]
@yaroslavvb 

Can we add check for this at configure time:
```
 https://github.com/tensorflow/tensorflow/blob/master/configure

```

bash to test this:

```bash

PLATFORM="$(uname -s | tr 'A-Z' 'a-z')"
SSE3_SUPPORTED=false

function is_linux() {
  if [[ "${PLATFORM}" == "linux" ]]; then
    true
  else
    false
  fi
}

function is_macos() {
  if [[ "${PLATFORM}" == "darwin" ]]; then
    true
  else
    false
  fi
}

function sse3_supported_macos() {
    cpuinfo | grep -i 'sse3'  > /dev/null
    if [ $? -eq 0 ];  then
            true     
    else
           false 
    fi
}

function sse3_supported_linux() {
    cat /proc/cpuinfo | grep -i 'sse3'  > /dev/null
    if [ $? -eq 0 ];  then
            true     
    else
           false 
    fi
}




if is_macos; then
    if sse3_supported_macos; then
        SSE3_SUPPORTED=true
        echo "sse3 supported:" $SSE3_SUPPORTED
    fi
fi

if is_linux; then
    if sse3_supported_linux; then
        SSE3_SUPPORTED=true
        echo "sse3 supported:" $SSE3_SUPPORTED
    fi
fi
```

**Comment by trajano** [comment]
Can we have official binaries in central with at least the different presets?  And change the dependencies so that the JNI code is not implicitlly included in `tensorflow` much like how slf4j separates the API and does a lookup for the implementation.
