### ISSUE TITLE
Reduction Functionality for Java API

### ISSUE THREAD

**Issue by nirajpatel** [tensorflow/tensorflow#8280]
Hey! It seems like the reduction functionality available in Python (https://www.tensorflow.org/versions/r0.11/api_docs/python/math_ops/reduction) has not made it to the Java API. Are there plans to port it over yet? There are some useful functions such as `reduce_mean` which I need.

**Comment by prb12** [comment]
@asimshankar Could you please comment?

**Comment by asimshankar** [comment]
This question is probably better suited for [stackoverflow](http://stackoverflow.com/questions/tagged/tensorflow) since the primitives for building such operations are available in the Java API, so there isn't a missing "feature" as such  :)

The Python reduction functions like [`tf.reduce_mean`](https://github.com/tensorflow/tensorflow/blob/169a096/tensorflow/python/ops/math_ops.py#L1329) are simple wrappers over the TensorFlow operations like [`Mean`](https://github.com/tensorflow/tensorflow/blob/169a096a2d9f4c129363d3f56b8b25c9ca4d8aa6/tensorflow/core/ops/math_ops.cc#L1102), where it fills in the `ReductionIndices` argument based on the shape of the input.

For example, to reduce a vector of floats, the following works:
```java
import org.tensorflow.DataType;
import org.tensorflow.Graph;
import org.tensorflow.Output;
import org.tensorflow.Session;
import org.tensorflow.Tensor;

public class ReduceMean {
  public static void main(String[] args) {
    try (Graph g = new Graph();
        Session s = new Session(g)) {
      // Build the graph
      Output placeholder =
          g.opBuilder("Placeholder", "input").setAttr("dtype", DataType.FLOAT).build().output(0);
      Output mean = reduce(g, "Mean", "output", placeholder);

      // Execute it
      try (Tensor in = Tensor.create(new float[]{1,2,3,4,5});
          Tensor out = s.runner().feed("input", in).fetch("output").run().get(0)) {
        System.out.println("Result: " + out.floatValue());
      }
    }
  }

  public static Output reduce(Graph g, String type, String name, Output input) {
    // This is assuming that the input is a vector.
    try (Tensor t = Tensor.create(new int[] {0})) {
      Output reductionIndices =
          g.opBuilder("Const", "ReductionIndices")
              .setAttr("dtype", t.dataType())
              .setAttr("value", t)
              .build()
              .output(0);
      return g.opBuilder(type, name)
          .setAttr("T", DataType.FLOAT)
          .setAttr("Tidx", DataType.INT32)
          .addInput(input)
          .addInput(reductionIndices)
          .build()
          .output(0);
    }
  }
}
```

Admittedly, this is not easy to discover, primarily because we don't yet generate Java code for all the TensorFlow ops (and thus they aren't discoverable via javadoc).  #7149  is about that.

I'll close this issue for now, given that I think it is helped by #7149 and similar questions are probably best suited for stackoverflow at this time.
