### ISSUE TITLE
Pass NHWC Tensors to cuDNN Directly

### ISSUE THREAD

**Issue by cancan101** [tensorflow/tensorflow#8286]
Currently when running `conv2d` on cuDNN with image data in `NHWC` format, TF [converts the input tensor from NHWC to NCHW](https://github.com/tensorflow/tensorflow/blob/0be81439c91e297b078152dd0c266471b24bde7f/tensorflow/core/kernels/conv_ops.cc#L558-L575), runs the conv and then [converts the output tensor back from NHWC to NCHW](https://github.com/tensorflow/tensorflow/blob/0be81439c91e297b078152dd0c266471b24bde7f/tensorflow/core/kernels/conv_ops.cc#L711-L720). However, cuDNN natively supports taking in data in `NHWC` format. 

Assuming this has not been tested and concluded to be optimal, my prior would be to allow Nvidia to handle the optimal execution of a conv2d on `NHWC` data rather trying to transpose within TF.

**Comment by yaroslavvb** [comment]
Does CuDNN `NHWC` run faster than TF transpose + `NCHW`? Is anyone else using CuDNN `NHWC`? I see that PyTorch only supports `NCWH`

cc @zheng-xq

**Comment by cancan101** [comment]
My prior would be that if TF transpose + NCHW + unTranspose were faster, then Nvidia would do that under the surface (which may in fact be what they do). Given that the default layout in TF is `NCHW`, seems reasonable to see if this path can be made faster.

**Comment by zheng-xq** [comment]
Our previous experiments on earlier Cudnn versions show that conversion + NCHW is faster. If there are evidence showing this has changed, we can look into this again.

**Comment by cancan101** [comment]
Looks like cuddn 4 was the first to support NHWC, so perhaps they improved in 5/5.1?

**Comment by yaroslavvb** [comment]
Since people are converging on NHWC, there's no reason for NVidia to improve NCWH, so it could be even slower in the latest version. Will reopen if there's evidence this feature is desirable

**Comment by taion** [comment]
@yaroslavvb Can you clarify what you mean? I thought movement was toward NCHW and away from NHWC, if anything. PyTorch doesn't even support NHWC.

**Comment by albertz** [comment]
@yaroslavvb Was that a typo in your latest post? Otherwise it sounds exactly like the opposite.
Btw., why is that that NCWH is faster than NHWC? ([Related StackOverflow question.](https://stackoverflow.com/questions/44280335/how-much-faster-is-nchw-compared-to-nhwc-in-tensorflow-cudnn)) Is that also the official Nvidia statement, or have people just seen that in benchmarks? Do you have any references for such benchmarks?

**Comment by albertz** [comment]
Is it right that the CPU implementation currently only supports NHWC and fails otherwise? Looked like that in the code, no automatic transposing. But maybe I'm missing something.

**Comment by taion** [comment]
I think @yaroslavvb's post was a typo – NCHW is cuDNN's native format, and is what most other DL libraries use. As such the justification is perhaps that the built-in NHWC operations in cuDNN are slower than transpose-run-transpose.

The CPU implementations in TF largely do only support NHWC, and will fail otherwise.

**Comment by winne42** [comment]
@albertz The official TensorFlow documentation states that NCHW is (typically, not always!) faster on GPUs: https://www.tensorflow.org/performance/performance_guide#use_nchw_imag

**Comment by yaroslavvb** [comment]
ah yes, I got h's and c's backwards, edited

**Comment by melodylail** [comment]
Please Noted, NCHW is also prefer data format from CPU side !!!
"Set to NCHW format to get maximum performance." quote from https://ai.intel.com/tensorflow-optimizations-intel-xeon-scalable-processor/

**Comment by dereklstinson** [comment]
Having built a CNN using multiple go-routines in go. I can see that NCHW is at least easier to stack the outputs of each of the neurons in NCHW.  Since, it naturally wants to work out that way (Even if you do a convolution in NHWC the outputs want to stack into NCHW). That being said. In NHWC the channels of the weights and inputs line up and the cpu doesn't need to skip around in memory when doing the convolution, and NHWC beats NCHW in single threaded performance.  I would say depending on the resources at your disposal it would be best to test both to see which one works better.

**Comment by jackwish** [comment]
> Please Noted, NCHW is also prefer data format from CPU side !!!
> "Set to NCHW format to get maximum performance." quote from https://ai.intel.com/tensorflow-optimizations-intel-xeon-scalable-processor/

Maybe they are benefiting from `NCHW[x]c` layout (check *Blocked layout* section of this [mkl-dnn doc](https://intel.github.io/mkl-dnn/understanding_memory_formats.html) rather than NCHW.
