### ISSUE TITLE
Update macOS GPU installation instructions

### ISSUE THREAD

**Issue by danqing** [tensorflow/tensorflow#8319]
### Environment info

Operating System: macOS 10.12
Tensorflow: 1.0
CUDA/cuDNN: 8.0, 5.1

---

I was setting up Tensorflow with GPU, reading the instructions: https://www.tensorflow.org/install/install_mac. It seems that a few things can be made clearer. I'm not sure where the source for the website lives so I want to file an issue so it can possibly be updated and people searching for related issues can have a pointer.

The issues are with the **Requirements to run TensorFlow with GPU support** section.

1. It mentioned that one should set `LD_LIBRARY_PATH` according to NVIDIA docs, but NVIDIA docs only asks to specify `DYLD_LIBRARY_PATH`, which actually doesn't work. Can we say on the website how exactly it should be set?
2. Same for cuDNN. The linked page actually has no instruction about how to install cuDNN. It may be useful to put on the website that the **include** and **lib** files should be manually copied over to **/usr/local/cuda**.
3. The following should be run to avoid segfault: `sudo ln -sf /usr/local/cuda/lib/libcuda.dylib /usr/local/cuda/lib/libcuda.1.dylib`.

The paths for 1 should be:

```sh
export CUDA_HOME=/usr/local/cuda
export LD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-8.0/lib/
export PATH="/Developer/NVIDIA/CUDA-8.0/bin:${PATH}"
```

**Comment by gunan** [comment]
About 1 and 2: CUDA and cuDNN are software built by NVIDIA. Their installation instructions may change for reasons beyond our control.
Therefore instead of us rewriting NVIDIA's instructions to install their software, we elected to point to NVIDIA for latest instructions for these.

Mac GPU is actually a difficult environment to test, as Apple has not produced a mac with NVIDIA GPUs for three years now. I think there may be two bugs from what you described:
-Setting `DYLD_LIBRARY_PATH` does not work.
-We need to create a symlink to avoid a segfault (when loading cuda libraries)

I will investigate these two.

**Comment by danqing** [comment]
re. 1 and 2, understood. The problem is that they don't really have documentation, unfortunately (esp. for cuDNN).

for `DYLD_LIBRARY_PATH`, I guess it's WAI, since you did mention in the instructions that we should set `LD_LIBRARY_PATH` correctly. it's just nvidia somehow doesn't have that in their docs..

at any rate, hopefully someone having trouble will see this issue and find some help :) Thanks for looking into it!

(someone holding onto an old mbp just for the GPU..)

**Comment by gunan** [comment]
So here is my progress. My macbook pro is gone, due to old age, but these I was able to figure out in its last breath:
The need to create `/usr/local/cuda/lib/libcuda.1.dylib` should now be gone if you use TF from head or TF 1.1 (rc at the moment).

`LD_LIBRARY_PATH` I did not need to set at all to get TF to run.
`DYLD_LIBRARY_PATH`, this was bad. I got everything to work with this aggressive variable:
```
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-8.0:/Developer/NVIDIA/CUDA-8.0/lib:/usr/local/cuda:/usr/local/cuda/lib:$DYLD_LIBRARY_PATH
```
