### ISSUE TITLE
/tutorials/using_gpu doc (possibly other) should use print() since Windows needs Python 3.x

### ISSUE THREAD

**Issue by danbri** [tensorflow/tensorflow#8349]
Should the Python samples in /tutorials/using_gpu and other docs be in 3.5.x form?

* In /install/install_windows we're told "TensorFlow only supports version 3.5.x of Python on Windows"
* In /tutorials/using_gpu there is sample Python code in 2.x style, "print sess.run(c)"
* This code snippet chokes when run on Windows, while print(sess.run(c)) is fine. Trivial to fix but distracts from the task at hand.

There may be more nuance to this (afaik print with parens is ok in 2.7), but it seems like avoidable friction if not.

**Comment by MicaelCarvalho** [comment]
TF is mostly used on linux-based systems, it seems natural to have code written for python 2.7, since TF supports this version of python outside Windows. I do agree with you, however, that at least the `print` functions could be written with parenthesis, just to avoid those simple incompatibility issues. I'm not part of the team, but I believe TF members wouldn't oppose the change, if you send a pull request with those changes.

**Comment by pobingwanghai** [comment]
Not a big deal, haven't find any other error under python3.

**Comment by concretevitamin** [comment]
We currently don't have anybody working on this. It would be great if you could help us by working on this and submitting a PR. Let us know if you need further clarification. Thanks!

**Comment by jerryshao** [comment]
Hi all, I just submitted a PR to fix this issue, please review, thanks a lot 😄

**Comment by concretevitamin** [comment]
Thanks @jerryshao!
