### ISSUE TITLE
fully_connected_preloaded.py on GPU trains slower then on CPU

### ISSUE THREAD

**Issue by taras-sereda** [tensorflow/tensorflow#838]
while running `examples/how_tos/reading_data/fully_connected_preloaded.py` on CPU the speed of training is the following:
```
Step 0: loss = 2.31 (0.586 sec)
Step 100: loss = 2.22 (0.012 sec)
```
But, when I run this code on GPU, it hangs, seems like some blocking occurs:
```
Step 0: loss = 2.30 (3.961 sec)
Step 100: loss = 2.13 (2.797 sec)
```
Timings are meaningless here, since actually I wait more than ~3 sec for next output.

**Comment by yaroslavvb** [comment]
It's common for a non-optimized network to run slower on GPU than on CPU. For instance, CPU has 5x smaller kernel launch overhead, so models with lots of small operations will run faster on GPU. Stack-overflow is a good place for these kinds of questions. In the particular case, it seems that the data is stored at a 600MB blob constant node on CPU, so you have a 600MB CPU->GPU transfer at every step

**Comment by yaroslavvb** [comment]
Actually, this has an easy fix, put "input_images", "input_labels" block into "with tf.device("/cpu:0"):" block. The problem was that constant nodes were placed on GPU, but the slice op is only supported on CPU, hence the data transfers

**Comment by yaroslavvb** [comment]
I have this fix in a pending CL, this issue should get closed when it's pushed

**Comment by yaroslavvb** [comment]
Fixed by  https://github.com/tensorflow/tensorflow/commit/ebe109b76d3a8fbdfadee8fa1e6e642563c88034

**Comment by taras-sereda** [comment]
Hey @yaroslavvb . Thanks for the detailed explanation, I also came up with this fix latter on. 
adding ```with tf.device("/cpu:0")```
leads to the following speed:
```python
Step 0: loss = 2.32 (0.112 sec)
Step 100: loss = 2.20 (0.020 sec)
Step 200: loss = 1.99 (0.018 sec)
Step 300: loss = 1.76 (0.017 sec)
Step 400: loss = 1.42 (0.019 sec)
```
It solves the issue with timing. but using GPU here doesn't helps in performance which contradicts the whole purpose of GPU.
I've added device placement logging
```sess = tf.Session(config=tf.ConfigProto(log_device_placement=True))```

and I see that nodes related to input producing and queues  automatically placed on CPU.  Are there any other ways to get more detailed log to see memory flow CPU->GPU->CPU? 

I'm going to add simple logging, with warnings when the list of available devices contains GPU but looks Looks like it's enough to add logging only in this source:
```https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/simple_placer.cc#L298 ```

Is there any public lists of ops which doesn't have GPU kernels?

**Comment by yaroslavvb** [comment]
After the patch I get 30ms per step on my CPU (HP Z420) and 140ms per step on GPU (K40c). Note that the patch only pins 2 constant ops to the CPU. It looks like there's a "Cast" op which is part of input pipeline that ends up on GPU, so that slows things down a lot. In general I found it best to pin the whole input pipeline to CPU manually.

However, even if you fixed this, this network is too small to benefit much from GPU. Using CPU-only version, the "QueueDeqeueMany" op takes 25ms out of 30ms total, so you have 5 ms spent on "actual computation", so even if you made the computation run 5x faster, it would have negligible effect on step size.

third_party/tensorflow/models/image/mnist/convolutional is much better example for utilizing GPU, I get 8x speed-up when using GPU. Also, cifar10_train example has a better tuned input pipeline

Regarding other questions:
if you turn on verbose logging in bazel, you'll see some messages every time tensors get copied between devices here: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/copy_tensor.cc#L41

One way to find if an op has GPU implementation is to search for "REGISTER_KERNEL_BUILDER" macros, like here https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/cast_op.cc#L217
