### ISSUE TITLE
Please provide a working android example with Android Studio 2.3

### ISSUE THREAD

**Issue by theyonibomber** [tensorflow/tensorflow#8436]
Obsolete gradle version of android example doesn't allow simply importing it as a directory to Android Studio and get the following error:

A problem occurred evaluating root project 'android'.
> java.lang.NullPointerException (no error message)

Still trying to solve this, but reproduction is so trivial (simply try to import the project directory to latest Android Studio and build), I would expect it to be solved faster by the community...

**Comment by andrewharp** [comment]
You're probably running into an uninitialized bazel-tensorflow directory. This is due to a recent change meant to automatically fetch the app assets for you.

If you run:
`bazel build -c opt tensorflow/examples/android:tensorflow_demo`
one time it should create the necessary directories for you. After that you can build from inside Android Studio.

**Comment by theyonibomber** [comment]
Thanks!
I now see this is written in the README, I missed that part. However - maybe it can be emphasized better in README, and error messages could be improved for the next guys who just want to try out the project in AS and encounter this.

**Comment by andrewharp** [comment]
This should be resolved by @ggfan's 360f449d95cf487fd35dbcbc548a6b65fa7ae64f, which removes the bazel dependency on downloading models (meaning it will also work for the makefile build now too).
