### ISSUE TITLE
XLA Feature request: Support Variables for tfcompile

### ISSUE THREAD

**Issue by yaroslavvb** [tensorflow/tensorflow#8441]
Is it feasible to extend tfcompile to support training?

Our reinforcement learning pipelines sometimes spend significant time in Python side of session.run because networks are small, and need lots of session.run calls since each .run leads to an interaction with a simulator (ie, Mujoco, gym or universe)

So you could have have 30k session.run calls where actual computation takes 200 usec, and Python session.run overhead is another 150 usec.

This could be improved if the network was tfcompiled and we didn't have to use session.run, however, this would need tfcompile to be extended to support multiple sets of fetches for the compiled object. IE

1. network initialization, input: weights, output: None
2. network forward op: input: observation, output: action
3. network train op: input: observations, actions output: None
4. network variable read: input: None, output: weights

**Comment by yaroslavvb** [comment]
cc @tatatodd

**Comment by ebrevdo** [comment]
+1 if you're going to go as far as tfcompile; consider just using C++ to interface with your training loop.

alternatively, write a TF C++ op wrapper that communicates with a mujoco session via server/client calls; and then your multiple interactions can be subsumied within a tf.while_loop.

another alternative might be to use session.partial_run to avoid the cost of copying data back and forth between python/C++.

**Comment by yaroslavvb** [comment]
Training is in Python because each step interacts with other Python libraries. Mujoco, [gym](https://gym.openai.com/) and [Universe](https://universe.openai.com/) have  Python bindings. C++ bindings are either not as well tested (people tend to use Mujoco through Python) or missing completely (gym + universe).

Partial run would help if I needed to persist some Tensors between run calls. But here I'm injecting new data each time. I can see how Mujoco C++ op would be more efficient but going down that route seems a bit scary, and would only help with mujoco (and not with gym, universe)

**Comment by ebrevdo** [comment]
tfcompile will create a C++ binary for you; you'd have to swig-wrap it to make it work with python which is IMO more daunting. I've noticed folks are afraid of writing C++ ops but IMO this is the least painful way to design interfaces with other systems thanks to the static type checking (and with Google's address sanitizer you get the additional benefit of ensuring you're not corrupting memory).

you could probably also try the pywrap to make a python op that interacts with mujoco within a tf.while_loop and is more lightweight than many session.run calls.

**Comment by yaroslavvb** [comment]
I was hoping to avoid SWIG and use `ctypes` with tfcompiled object. IE something like

```
import ctypes
network = ctypes.cdll.LoadLibrary("compiled.so")
result = ctypes.c_float()
network.runforward(result)
```

**Comment by ebrevdo** [comment]
if you get that to work, please do report back!

**Comment by asimshankar** [comment]
Fair enough, though you could write C++ code just to execute the graph (equivalent to what the generated `tfcompile` shared library would do) and use it in a way similar you described, no? Just that the library is produced by compiling a `.cc` file that you write instead of being produced by `tfcompile`.

Anyway, just a suggestion, I am in no way suggesting that this feature request isn't a reasonable one. Just pointing out possible equivalents you can pursue today without the feature.

I will stop derailing this thread now :)

**Comment by yaroslavvb** [comment]
@asimshankar Hm, good point. For your proposed alternative I could also use it through ctypes and `compiled.so` would be a C++ binary that I created which uses TF C++ API and implements those 4 modes: variable in, forward, train op, variable out

I was assuming that using XLA AOT for this is more efficient because it gets rid of unneeded TF runtime bits.

Implementing this feature would require changes to `tfcompile` to support Variables and multiple fetch configurations. On other hand it would make XLA AOT compiler more useful/widely applicable.

I'll leave it to XLA maintainers to decide if this feature fits into the XLA vision/design

**Comment by tatatodd** [comment]
Wrt multiple fetch configurations, an alternative is to compile separate functions, one for each configuration.  The only downside that I see of this strategy is that perhaps lots of generated code is duplicated in each function; i.e. the combined size of the *.o files is larger than strictly necessary.  But it doesn't sound like that would be a big issue.

Supporting Variables is trickier.  In theory we could hoist the variables outside of the "pure graph", and add logic to read/write the variables at the edges.  But it's not clear this is worth doing for the AOT codepath; it's quite a bit of work.  You could always do this manually though, so that you end up with a "pure graph" that can be AOT compiled.

**Comment by hawkinsp** [comment]
That said there is some experimental support for compiling code that manipulates variables in the JIT use case:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/compiler/jit/kernels/xla_device_launch_op.cc

(That code only works for ResourceVariables, which will replace Variables at some point in the future.)

Code that reads and writes variables is rewritten into a pure computation that takes the initial values of the variables as inputs and returns updated values as outputs. So most of the code one would need is actually already there.

**Comment by yaroslavvb** [comment]
OK, it seems like some of the performance benefits needed be done with compiled binary that uses C++ TF API, and benchmarking is needed to decide if extra work of adding variables to XLA is justified, will close this for now, will reopen if I come across some concrete numbers.
