### ISSUE TITLE
synchronous posix file mmap

### ISSUE THREAD

**Issue by samwhitlock** [tensorflow/tensorflow#8478]
TensorFlow's [PosixFileSystem::NewReadOnlyMemoryRegionFromFile method](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/posix/posix_file_system.cc#L172) calls `mmap` with [only the `MAP_PRIVATE` flag specified](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/posix/posix_file_system.cc#L183).

Having the ability to specify that flag, at least to specify `MAP_POPULATE` would be very useful for many applications with high disk I/O throughput. For the `MAP_POPULATE` case, I sped up one of my graphs by ~4x by adding that flag because I have a pipeline that:

1. reads in a file of N chunks in size
2. enqueues a pointer to each of those N chunks in an output queue
3. downstream nodes process one chunk at a time

Because of the lack of coordination between the downstream nodes (each being independent), they would take page faults in an uncoordinated manner. When I added `MAP_POPULATE` this went away.

I have a patch to add this feature where I change the [base method](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/platform/file_system.h#L102) to look like this:

    virtual Status NewReadOnlyMemoryRegionFromFile(
      const string& fname, std::unique_ptr<ReadOnlyMemoryRegion>* result, bool synchronous = false) = 0;

and then changed each corresponding subclass method signature. For the Posix subclass, I added `MAP_POPULATE` to the flags if `synchronous == true`.

I can submit a pull request for this, but I find this approach hacky (e.g. that flag might not have the same meaning in non-Posix contexts). If there is a better approach to do this, I'm happy to work on it.

**Comment by concretevitamin** [comment]
My hunch is that changing a well-established interface such as `FileSystem` is not ideal. 

@keveman @vrv do you see any harm in just or'ing `MAP_POPULATE` in the implementation of `PosixFileSystem::NewReadOnlyMemoryRegionFromFile`?

**Comment by vrv** [comment]
Let me find one of the original authors to chime in here...

**Comment by MaxGubin** [comment]
I'm the author of this code. I agree that there are many different use cases.

The cases that I was focused on is on-device (Android) models with big embedding tensors for NLP tasks. For this case, MAP_POPULATE is a really bad idea because usually only a small amount of these tensors are touched during every inference. 

I also don't like the idea with additional low-level flags because tomorrow we'd see another special solutions for Windows, iOS, etc. I'd rather add to the optimizer of a session, similar to constant elimination, a pass to pre-heat small memmaped tensors. Does it look like a cleaner solution that solves your problem?

**Comment by samwhitlock** [comment]
> I'd rather add to the optimizer of a session, similar to constant elimination, a pass to pre-heat small memmaped tensors. Does it look like a cleaner solution that solves your problem?

I'm not quite sure how this works, as I am not knowledgeable about this part of the codebase. By "pre-heat" do you mean a for loop to touch every page (to trigger the page fault)? At least for my use case, I really need to call `mmap` with `MAP_POPULATE` in order to have Linux load all the pages in a single system call. I tried the "for-loop-to-touch-every-page" solution prior to this, but that didn't help so much. I read all the data in every file (either to decompress, or to scan if uncompressed) in my graphs / kernels where I use this file mapping.

**Comment by MaxGubin** [comment]
I've been thinking about it a bit. 
First "pre-heat" I meant to tell the runtime that during a run over the graph all pages must be in memory. I think that "synchronous" is ambiguous because an OS not necessary have to load everything during the call but before the first usage of the tensor. 
A generic implementation can simply touch all pages, but for a specific OS a special flag can be specified that effectively does the same.

Returning to the initial idea, I like the optimization, but I'd like to have some optimization/control and not switch all memmapped tensors to the new mode. Yesterday I thought that a good option is to create a [GraphOptimizer](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/common_runtime/graph_optimizer.h) that sets to ImmutableConst the "pre-heat" attribute based on some optimization parameters (e.g. amount of memory). But it might be an over-kill, a simpler approach would be a flag in the script that adds ImmutableConstants that are specified by a name pattern that they need to be pre-heated. How about this solution?

**Comment by samwhitlock** [comment]
I'm not sure I fully understand this (I haven't looked at the graph optimization part of the code), but I don't think this would work for my use case because I don't mmap tensors. I am not mmaping Tensors directly; instead, my graph works something like this

1. source: a list of filenames
2. read kernel: takes one filename, calls `NewReadOnlyMemoryRegionFromFile` (with the boolean flag hack I currently have), and puts that region into a custom data type that I output as a `resource` type from the read kernel
3. downstream kernels: read in this custom `resource` type that owns the mmaped region, and deletes / recycles it when down (calling the `ReadOnlyMemoryRegion`'s destructor)

This "sidestepping" of tensorflow concepts (e.g. not reading my custom binary format and converting it into a large `string` Tensor) might be hard to accommodate for `MAP_POPULATE` in this case, but I think this could prove useful for other use cases.

**Comment by MaxGubin** [comment]
OK, I understood, you just want to extent the file system interface for your own custom kernel. Because your solution works only on Linux, why you need the portable interface? Just implement everything in the kernel. It's more transparent and doesn't introduce not needed dependencies.

**Comment by samwhitlock** [comment]
Makes sense. I was moving my code out of `core/user_ops` and into `contrib/`, and found this piece for synchronous mapping that I thought could be useful, but I agree it can make things messy in general.

Should I (or someone else) close this issue at this point?

**Comment by vrv** [comment]
Let's close for now -- we can reopen later if it becomes relevant again -- thanks for your efforts on this issue!
