### ISSUE TITLE
LocalCLIDebugWrapperSession hides exception messages

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#8507]
### Environment info
Operating System: osx

Installed version of CUDA and cuDNN: no

If installed from binary pip package, provide:

1. A link to the pip package you installed: nightly, python3, today
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`:1.0.1

```python
import tensorflow as tf
with tf.device('/gpu:0'):
    x = tf.get_variable('W', shape=[10])

sess = tf.Session()
from tensorflow.python import debug as tf_debug
sess = tf_debug.LocalCLIDebugWrapperSession(sess)
sess.run(tf.global_variables_initializer())
```

My machine doesn't have GPU, and the above code throws:
```
OSError: Dump root directory /var/folders/3t/1kq225bs04j3k_2rbdcn2g34g86_w8/T/tfdbg_fw0uylcr does not exist
```
But it should throw the device error, like when debug session is not used:
```
Cannot assign a device to node 'W': Could not satisfy explicit device specification '/device:GPU:0' because no devices matching that specification are registered in this process; available devices: /job:localhost/replica:0/task:0/cpu:0
```

**Comment by caisq** [comment]
@ppwwyyxx thank you very much for reporting this issue. I'll take a look at it soon.

**Comment by caisq** [comment]
Update: the underlying cause of this bug is that `LocalCLIDebugWrapper` attempts to intercept `OpError`s that happen during the underlying `tf.Session.run()` calls. It works if the `OpError` happens in the middle of a graph execution, which will generate the debug dump directory. But in this case, the `OpError` (due to invalid device name) happens before the graph execution even happens, so there is no debug dump directory and `LocalCLIDebugWrapper` generates an error message that masks the original exception. I will push a fix to this issue soon.
