### ISSUE TITLE
tf.case doesn't return a tensor with the given name

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#8594]
With TF 1.0.1.
```python
>> print(tf.case([(tf.constant(True, dtype=tf.bool), lambda: tf.constant(1))], lambda: tf.constant(2), name='aa'))
Tensor("aa/If_1/Merge:0", shape=(), dtype=int32)
```
I expect to see "aa:0".

Similar to #6741

**Comment by skye** [comment]
I'll work on getting a patch in to fix this.

**Comment by girving** [comment]
@skye Did this fall through the cracks?

**Comment by skye** [comment]
Hi, sorry for leaving this hanging for so long. After some internal discussion we decided that to keep the current behavior, where "aa" refers to the enclosing name scope rather than the final output op. This is to be consistent with other functions that produce multiple ops, and since it makes TensorBoard output more useful.

**Comment by ppwwyyxx** [comment]
I think using "aa" for the output op doesn't conflict with using an internal name scope to organize tensorboard graph (e.g. the scope can be named "aa_internal").

Using the name for output op is actually consistent with most other `tf.xxx` functions. At least from the documentation of all `tf.xxx` functions, we cannot tell whether "name" will be used for the op or the scope.
