### ISSUE TITLE
GPU implementations for more ops

### ISSUE THREAD

**Issue by abhishekpatnia** [tensorflow/tensorflow#86]
1. Loads of operations in the embedding example are not supported on GPU. Some documentation   detailing this would be good.
2. I tried to get around the problem by using 'tf.ConfigProto(allow_soft_placement=True)'. However now I get 'Executor failed to create kernel. Invalid argument: AttrValue must not have reference type value of float_ref for attr 'tensor_type'

Thanks
Abhishek

**Comment by bocongl** [comment]
Same issue here. tried both word2vec_basic.py and the word2vec code shipped with source. Can anyone share some insight?

**Comment by abhishekpatnia** [comment]
I did get it working by forcing TensorFlow to use GPU for only matrix multiplication. It was posted here:

http://stackoverflow.com/questions/33624048/fail-to-run-word-embedding-example-in-tensorflow-tutorial-with-gpus

I hoping it will be fixed soon.

**Comment by bocongl** [comment]
@abhishekpatnia Thanks! let me give it a try. Not sure how this will affect performance :(

**Comment by ZhangBanger** [comment]
Is there being work done to support these ops on GPU? Would be happy to chip in if individual efforts are being assigned and tracked somewhere.

**Comment by martinwicke** [comment]
We're working on making more kernels runnable on GPUs. In the code, you can tell which kernels support GPU by going to the core/kernels directory to see which ops have .cu.cc cuda files. If you want to help out, pick a CPU only kernel and write a GPU capable version either by using Eigen (for example, see the argmax or the adjust_contrast kernels), or write a plain cuda kernel (for example, see the check_numerics_op).

In order to avoid duplicating work, I would create an issue called "XX_op does not have a GPU kernel", and then leave a comment that you're starting work on this. Then we won't do that internally without checking in with you first.

Finally, when you have something written, you have to submit a patch through tensorflow.googlesource.com (instructions are [here](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md)).

**Comment by vrv** [comment]
This is too broad of a request, finer grained issues for individual ops are probably better.

**Comment by alexeygrigorev** [comment]
The problem still seems to exist. Has there been any progress on this or related issues? 

I also wonder if there are "finer grained issues"? Just to be able to follow the progress...

**Comment by alexeygrigorev** [comment]
For me, using `GradientDescentOptimizer` instead of ada grad seems to solve the issue - now it runs on gpu (although it doesn't seem faster than cpu)

**Comment by martinwicke** [comment]
Please file finer grained issues. It's clear that we need more GPU ops, but we'd love to understand which ones people are actually running into.

**Comment by anantzoid** [comment]
I'm getting the same error while running `GradientDescentOptimizer ` too for the translation seq2seq exapmle. This is the exact error:

```
E tensorflow/core/framework/op_segment.cc:53] Create kernel failed: Invalid argument: AttrValue must not have reference type value of float_ref
         for attr 'tensor_type'
        ; NodeDef: proj_b/_40291 = _Recv[_start_time=0, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_2226879_proj_b", tensor_type=DT_FLOAT_REF, _device="/job:localhost/replica:0/task:0/cpu:0"](^gradients_2/concat_1, ^GradientDescent_2/update_proj_b/mul/_40293); Op<name=_Recv; signature= -> tensor:tensor_type; attr=tensor_type:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>
```
