### ISSUE TITLE
Problems to visualize Tensorboard 

### ISSUE THREAD

**Issue by Midnight93** [tensorflow/tensorflow#8691]
Hi guys

I have problems to visualize tensorboard on my browser. ( Google chrome )

At the moment I did 3 python files.  ( 2 models and input_data )

Everything works fine, and I don't have any errors with the terminal ( Docker --> IPython ---> Terminal )

I already install pandas, urllib3, sklearn, etc etc

The terminal say me, you can sulf on Tensorboad at 0.0.0.0:6006 ( example )

I try to launch the ip on my browser but I don't see anything.

---- Step by step ---

Step 1
[My file](http://imgur.com/h39C8nd)

Step 2

[Terminal](http://imgur.com/LeT1muD)

Step 3

[Browser](http://imgur.com/6ZQSm2T) 

I tried with different browers, disable the firewall but nothing :(

P.s I'm noob and don't judge me for this question.

Best regards,

**Comment by rgautam98** [comment]
The problem is with the IP address. 

The thing is, 0.0.0.0 is used to bind to the localcomputer. 

With docker running, 0.0.0.0 is no more linked to the container, until you forward the port. 

So you have 2 solutions here. 

Firstly, change the ip address(0.0.0.0) to the ip address of the docker container, which is usually 172.17.0.x, where 0.x usually varies. Check for the ip address using the command  docker inspect <container name> or by using a gui like kitematic. 

The second solution is to forward a port to the local pc. 

You can do it by using the -p command while starting the  container.  The syntax is something like docker run -it -p localport:containerport tensorflow/tensorflow. 

Then access in the browser using the url 
0.0.0.0:localport

Hope it answers your question.

**Comment by drpngx** [comment]
That should do it. Thanks @rgautam98 !

You can also use `--net=host` to use the host networking on docker.
