### ISSUE TITLE
temperature will be higher when I using two different cards in the same machine

### ISSUE THREAD

**Issue by lizhiyuanUSTC** [tensorflow/tensorflow#8741]
Hey, guys, I am trying to train a CNN model. My machine has 2 K40. When I run my model in the second card, the temperature  will be higher than running in the first card, and the training will be slower and slower.

**Comment by jubjamie** [comment]
Is the usage the same in nvidia-smi? Or are you running it on one card exclusively? This might not be a tensorflow issue so I recommend filing a question on stack overflow. In the mean time you could try some primitive troubleshooting by physically removing and swapping cards to clarify if it is a bug caused by device id allocation (doubt it) or mobo or the card itself. 

It may just run hotter and slower because of the cooling for the card or the power consumption. Monitor through nvidia-smi and when you are sure it is a tensorflow issue then I would suggest re-filing as this might get closed! Good luck!

**Comment by lizhiyuanUSTC** [comment]
Thanks a lot. I will have a try.

**Comment by aselle** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
