### ISSUE TITLE
Tensorflow installer

### ISSUE THREAD

**Issue by bellaj** [tensorflow/tensorflow#878]
Hi TensorFlow Team,

I would like to propose a simple bash script to automate the installation of required tools(based on os_setup.md instructions), I think it will help many newbies. It is available under :  https://github.com/bellaj/tensorflow/blob/master/setup_Tensor.sh
This script will help users to install Tensorflow for many Linux distributions .

I have tested it for ubuntu 64, and it works fine.
I am working now on GPU support

any feedback is welcome
thank you

**Comment by martinwicke** [comment]
I like the idea of having a more or less platform independent script. Here are a few concerns I have with this version:

- I'm skeptical that the package names are all the same for yum, apt-get, zypper, yast. 
- I'm not even sure they're consistent across different distributions that use the same package manager.
- I don't know whether all of these take the same arguments (e.g. `install` vs. `-i`)
- variable evaluations should almost always be quoted. Otherwise expressions like `[[ $env -eq 0 ]]` fail with a syntax error if `$env` is empty.
- Why are you using the 0.5.0 wheel for CPU only python 2.7?
- If you get into a "bad choice" branch, the script still continues
- If you install without virtualenv, the script will still output instructions for virtualenv

**Comment by bellaj** [comment]
Thank you @martinwicke. Now It is a simple script as POC, but i will make some deep changes and test it in many distributions. I will take in consideration all your remarques.

**Comment by bellaj** [comment]
Hi, i have updated the script please take a look :)

**Comment by coolshinejonson** [comment]
thank you for the infomation.

**Comment by girving** [comment]
@martinwicke: Looks like this fell through the cracks.

**Comment by martinwicke** [comment]
Ok, I think after we know a little more about the environments out there, I doubt we want to maintain such a script. It's a great idea, felled by the messiness of contemporary information technology.

I'll close this issue.
