### ISSUE TITLE
Large Strides for 1x1 Convolutions

### ISSUE THREAD

**Issue by Natanada** [tensorflow/tensorflow#889]
When a conv2d operator has a stride greater than the kernel size, the following error is thrown:
```ValueError: ('stride must be less than or equal to filter size', 'stride: [2x2] filter: [Dimension(1)xDimension(1)]')```
This makes implementing the 1x1 convolutions used to reduce spatial resolution in several papers (MSRA 2015 among others) awkward. Also, a convolution with stride greater than kernel size may be unusual but is it still well defined. Fixing this may be as simple as removing this assertion.
Thanks to everyone who developed TensorFlow, it's a fascinating tool.

**Comment by vrv** [comment]
I think this has been called 'atrous convolution', at least in the Eigen code.  Does anybody know whether cudnn supports this?  @zheng-xq ?

**Comment by zheng-xq** [comment]
I don't think Cudnn supports convolutions for stride larger than 1. Not
sure the FFT algorithm they were using would still be correct.

**Comment by zheng-xq** [comment]
I stand corrected. The stride larger than 1 should be supported by Cudnn. I was looking at upscalex instead.

**Comment by vrv** [comment]
it's not just stride > 1, it's stride > the input patch.  E.g., skipping regions of the input.

@vincentvanhoucke just corrected me: atrous is introducing holes in the input patch, so the input has 'holes'.  So it's different.

I don't know if our eigen (CPU) implementation supports stride > input_patch.  If it does, and cudnn does too, we can remove this assertion.

**Comment by vrv** [comment]
FYI last week I did try to look at this and cudnn appeared to give different results than I expected (eigen was correct for both CPU and GPU).  Not yet sure whether this is a bug in cudnn or how we were calling it.

**Comment by mackcmillion** [comment]
The same error is thrown when calling `tf.nn.max_pool` or `tf.nn.avg_pool` with stride greater than filter size.

**Comment by ry** [comment]
I hit this bug while trying implement ResNet. I'm working around it by using a 2x2 kernel with all but the top-left zeroed out.
https://github.com/ry/tensorflow-resnet/blob/2775805c4c4af3a3a082100c36a2b2f77791df4d/convert.py#L119-L122

**Comment by cesarsalgado** [comment]
@ry I used resize_nearest_neighbour to circumvent that problem: https://github.com/cesarsalgado/tensorflowed/blob/master/models/residual_nets.py#L46

**Comment by martinwicke** [comment]
I'm marking this a bug since it really should work. Also contributions welcome. See also the recent duplicate #1815.

**Comment by ry** [comment]
@martinwicke I'd like to take a look at fixing it because I'm hitting this still. But I've never hacked on TF before, if you could give a rough outline of what's involved it'd help!

**Comment by vrv** [comment]
@ry: I wish I could still find my code.  I remember Eigen doing something consistent across GPU and CPU and expected and cudnn doing something different (and seemingly wrong), but I might have introduced a bug.

The best thing to start with is via a test: add a simple test to conv_ops_test.py that exercises say, a 1x1 convolution with input depth 1 and output depth 1 for a 1x3x3x1 input with stride 2 (so you get four values: the corners multiplied by a filter).  

If you try to run that, you'll first run into a problem doing conv2d shape inference in python (because it checks for stride < filter) -- remove that and make sure that the shape calculation is correct.

Then you'll probably have to make the same fix in the C++ code (https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/ops_util.cc#L41) to remove that check.

Other than that, I don't think there was anything else I had to do to get the calls to run, but that's when I started seeing different output and didn't have time to debug.  It's possible it has something to do with padding or the shape inference difference between us and cudnn.  Happy to help how I can.
