### ISSUE TITLE
regarding the ValueError: inputs must be a list of at least one Tensor with the same dtype and shape

### ISSUE THREAD

**Issue by wenouyang** [tensorflow/tensorflow#8910]
There is a program that defines the loss function as follows:
```
reg_loss_col = tf.GraphKeys.REGULARIZATION_LOSSES
weight_loss = tf.add_n(tf.get_collection(reg_loss_col),name='reg_loss')

```

Running the program raises the following error message

> File "/home/ decoder/kitti_multiloss.py", line 86, in loss
>     name='reg_loss')
>   File "/devl /tensorflow/tf_0.12/lib/python3.4/site-packages/tensorflow/python/ops/math_ops.py", line 1827, in add_n
>     raise ValueError("inputs must be a list of at least one Tensor with the "
> ValueError: inputs must be a list of at least one Tensor with the same dtype and shape
> 

I am curious how to print out the tensor information of the first parameter `tf.get_collection(reg_loss_col)` in `tf.add_n`, so that I can figure out why this cause the error.

**Comment by aselle** [comment]
This seems to be a program you have written, so this question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

But the error basically means that the collection with key `tf.GraphKeys.REGULARIZATION_LOSSES` has no members. If you cannot find the source of this, be sure to post the full source of the program to stackoverflow as it is impossible to help you with some tiny fragment of the program. Thanks!
