### ISSUE TITLE
Python test failure in TF (KeyError: 'TEST_SRCDIR') on Ubuntu 16.04 

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#8921]
### Environment info: 
Operating System: Ubuntu 16.04 (ppc64le)

###Installed version of CUDA and cuDNN:  CUDA support is disabled 

###Build and test INFO
Built TF (version 1.0.1) successfully on Ubuntu 16.04 and RHEL 7.3. Now I am trying to run the python tests , but 3 tests are failing with the same error :
         [Test name:
                           1) python ./python/saved_model/saved_model_test.py
	                   2) python ./contrib/session_bundle/session_bundle_test.py
	                   3) python ./contrib/session_bundle/bundle_shim_test.py ]
##############################Error log########################################
ERROR: testMaybeSavedModelDir (__main__.SavedModelTest)
           ----------------------------------------------------------------------
          Traceback (most recent call last):
          File "./python/saved_model/saved_model_test.py", line 112, in testMaybeSavedModelDir
          base_path = test.test_src_dir_path("/python/saved_model")
          File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/test.py", line 84, in test_src_dir_path
          return _googletest.test_src_dir_path(relative_path)
          File "/usr/lib/python2.7/site-packages/tensorflow/python/platform/googletest.py", line 112, in test_src_dir_path
          return os.path.join(os.environ['TEST_SRCDIR'],
          File "/usr/lib64/python2.7/UserDict.py", line 23, in __getitem__
          raise KeyError(key)
          KeyError: 'TEST_SRCDIR' 

Any suggestion/solution ?

**Comment by jubjamie** [comment]
TEST_SRCDIR looks like it refers to a directory. Can you please make sure that all required files for your script are in the correct locations?

**Comment by gunan** [comment]
TEST_SRCDIR environment variable is actually created by bazel.
If you are not running with bazel, could you try to set it to the root of your TF source repository before you run your tests? In your case, I think the following should suffice
```
export TEST_SRCDIR=`pwd`
```

**Comment by sandipmgiri** [comment]
I have exported the "TEST_SRCDIR" env var to the root of TF source repository, and now that error is gone , however I am getting some different kind of error

======================================================================
FAIL: testMaybeSavedModelDir (__main__.SavedModelTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./python/saved_model/saved_model_test.py", line 115, in testMaybeSavedModelDir
    self.assertTrue(loader.maybe_saved_model_directory(base_path))
AssertionError: False is not true

----------------------------------------------------------------------
Ran 18 tests in 3.913s

FAILED (failures=1)

**Comment by gunan** [comment]
Most of our tests are written to work with bazel.
I highly recommend against running them outside bazel, and we do not really guarantee tests passing when run outside bazel.
Here is why you are seeing issues:
Saved_model test has a data dependency as defined here:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/BUILD#L106

What bazel does is it arranges all the data dependencies under TEST_SRCDIR.
Then when we run this line after building with bazel, the folder is accessible to us:
https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/saved_model/saved_model_test.py#L113

Because bazel arranges all the dependencies for us, and gives a way for us to access them.

Therefore, It will be tricky to run this test without bazel. And once you get it running, it will be brittle, because it is written using the concepts used by bazel, like the data dependencies.

I will close this issue, as it is not a TF bug.
I would recommend reaching out to stackoverflow if you still would like to run TF unit tests outside bazel.
