### ISSUE TITLE
Feature Request: Erosion2d and Dilation2d implemented on GPU

### ISSUE THREAD

**Issue by vanpact** [tensorflow/tensorflow#8948]
Hi everybody!
Erosion2d and Dilation2d can be used for various reason. e.g. [Ronneberg et al.](https://arxiv.org/abs/1505.04597) compute a weight map using morphological operations for their cost function. This can be done using morphological Erosions and Dilations but those operations are quite slow on CPU. It seems Tensorflow do not use the GPU for those operation. Would it be possible to have those two operations implemented on GPU?

**Comment by asimshankar** [comment]
@vanpact : It seems that TensorFlow does have GPU implementations of these kernels - since the time they were added in 2016 (commit https://github.com/tensorflow/tensorflow/commit/283782a2dc3301f4d9e8dee65654eb97c698d635). See [`dilation_ops.cc`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/kernels/dilation_ops.cc#L471) for the kernel implementation.

Am I missing something?

**Comment by vanpact** [comment]
Ok, I found why I got an error stating "Cannot assign a device to node 'erosion2d': Could not satisfy explicit device specification '/device:GPU:0' because ;no supported kernel for GPU devices is available". The kernel is available for float32 but not for int32. 

Sorry!

Maybe a more explicit error indicating the kernels available for a specific pair of device/function would be nice?

**Comment by asimshankar** [comment]
Will look into that. Closing this out now since the original issue seems to be resolved.
