### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.array_ops' has no attribute 'pack' 

### ISSUE THREAD

**Issue by TB-SeChaJia** [tensorflow/tensorflow#8952]
NOTE: Only file GitHub issues for bugs and feature requests.  All other topics will be closed.

For general support from the community, see [StackOverflow](https://stackoverflow.com/questions/tagged/tensorflow).
To make bugs and feature requests more easy to find and organize, we close issues that are deemed
out of scope for GitHub Issues and point people to StackOverflow.

For bugs or installation issues, please provide the following information.
The more information you provide, the more easily we will be able to offer
help and advice.

### Environment info
Operating System:

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

If installed from binary pip package, provide:

1. A link to the pip package you installed:
2. The output from `python -c "import tensorflow; print(tensorflow.__version__)"`.

If installed from source, provide 

1. The commit hash (`git rev-parse HEAD`)
2. The output of `bazel version`

### Logs or other output that would be helpful
(If logs are large, please upload as attachment or provide link).

**Comment by jubjamie** [comment]
Can you please fill in the issue template. It will help with solving your issue. Most importantly, which version of Tensorflow are you running as I believe that the tf.python group was deprecated in 1.0. Please post a code snippet too so we can understand what you were trying to achieve and what function you were trying to find as the error from your title suggests that you're calling something similar to tf.python.ops.array_ops.pack instead of .pack() perhaps?
