### ISSUE TITLE
Gradients of Gradients throws 'NAN' outputs for LSTM's

### ISSUE THREAD

**Issue by NickShahML** [tensorflow/tensorflow#8959]
### Environment info
Operating System: Ubuntu 14.04

Installed version of CUDA and cuDNN: 
(please attach the output of `ls -l /path/to/cuda/lib/libcud*`):

Cuda 8.0, tensorflow 1.0

If you try to take the gradient of a gradient such as needed in Improved Techniques of Wasserstien GAN's (https://arxiv.org/abs/1704.00028) for LSTMs in the generator, throws a NAN error. If you use convolutions, then there is no error. 

Author's source code for language model:

https://github.com/igul222/improved_wgan_training/blob/master/gan_language.py

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

(Also, if possible, a more focused, smaller snippet that can reproduce the problem without importing a lot of external code will go a long way in being able to help)
