### ISSUE TITLE
Wrap python code into a tf operation

### ISSUE THREAD

**Issue by shinjirei** [tensorflow/tensorflow#9009]
I have described my issue in the keras group [issue 6163](https://github.com/fchollet/keras/issues/6163) but was re-directed here. I am trying to wrap a non-tf function (actually a class) into a tf operation to use in a custom keras layer. When using py_func it always returns  "ValueError: None values not supported." Is it generally possible to wrap an arbitrary piece of python code, which takes a list of numpy arrays as input and delivers a list of numpy arrays , into a tf op?

- *I have written custom code.*
- *TensorFlow installed from binary.*
- *TensorFlow version is 1.0.1*
- *No CUDA/cuDNN used.*
- *Currently no GPU.*

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said, yes it seems [`tf.py_func`](https://www.tensorflow.org/api_docs/python/tf/py_func) is what you want.

**Comment by pinkmanbox** [comment]
Did you find a solution to this?
