### ISSUE TITLE
Windows: tf.gfile methods (tf.gfile.Exists, tf.gfile.IsDirectory) are not Windows friendly

### ISSUE THREAD

**Issue by sshinderman** [tensorflow/tensorflow#9027]
(Windows 10) in saver.py  train.save() takes a sess_path but on windows it returns an empty result.
I had to modify to the following (around line 1354)
    if not gfile.IsDirectory(os.path.dirname(os.path.abspath(save_path))):
similar issue found here:
http://stackoverflow.com/questions/7783308/os-path-dirname-file-returns-empty

this is via pip install --upgrade tensorflow-gpu

**Comment by asimshankar** [comment]
There isn't enough detail in this issue report to help. Could you elaborate on:

- What version of TensorFlow are you using?
- Code that demonstrates the problem

**Comment by sshinderman** [comment]
>>> print(tf.__version__)
1.0.1

i don't have a narrowed down standalone app(i'll try to make some time) that demonstrates it but it looks like the call sequence is just:
saver = tf.train.Saver()
saver.save(sess, 'my-model')

**Comment by asimshankar** [comment]
And what is the problem with that call sequence?

**Comment by sshinderman** [comment]
It throws the ValueError (and prints out ValueError: Parent directory of my-model doesn't exist, can't save.)  -- the example on https://www.tensorflow.org/api_docs/python/tf/train/Saver  shows that style of call.

**Comment by asimshankar** [comment]
Ah, I see. I think the problem reduces to the different behavior of `tf.gfile.IsDirectory` on Windows and other platforms. (I suppose as a workaround you can specify an absolute path to `saver.save()` for now).

```python
import tensorflow as tf
tf.gfile.IsDirectory('')
```

is `True` on Linux and OS X but `False` on Windows, which causes this trouble.
I believe this comes from the implementations of `Exists` and `Stat` in [`windows_file_system.cc`](https://github.com/tensorflow/tensorflow/blob/45d6994f69ac670396671348524a3e88cd0f9656/tensorflow/core/platform/windows/windows_file_system.cc), which is invoked from [`file_system.cc`](https://github.com/tensorflow/tensorflow/blob/45d6994f69ac670396671348524a3e88cd0f9656/tensorflow/core/platform/file_system.cc#L62), which in turn probably comes from the fact that even for Windows, [`TranslateName`](https://github.com/tensorflow/tensorflow/blob/45d6994f69ac670396671348524a3e88cd0f9656/tensorflow/core/platform/file_system.cc#L58) is implemented by [`io::CleanPath`](https://github.com/tensorflow/tensorflow/blob/45d6994f69ac670396671348524a3e88cd0f9656/tensorflow/core/lib/io/path.cc#L189), which seems not-Windows friendly with it's use of `/` and converting an empty path to `.`.

@mrry : What do you suggest? Making `io::CleanPath` OS independent? Or perhaps implementing `WindowsFileSystem::TranslateName`?

@guschmue : Do you have any suggestions?

**Comment by guschmue** [comment]
let me take a look at the code tomorrow. We had some discussions around TranslateName last year but I forgot the details why we did not implement it ... if I see the code I might remember.
In the meantime 
   saver.save(sess, os.path.join(os.path.curdir, 'my-model'))
should workaround it

**Comment by mrry** [comment]
I *think* `io::CleanPath()` should be safe to use on most already-clean filenames, since Windows is tolerant of a mixture of  `'/'` and  `'\'` in paths. However it seems like it might be more useful to switch to using something like [`PathCchCanonicalizeEx()` ](https://msdn.microsoft.com/en-us/library/windows/desktop/hh707084(v=vs.85).aspx) in `WindowsFileSystem::TranslateName()`.

I'm also a bit concerned about the general logic in `saver.py`. In particular, is it guaranteed to be safe to mix `tf.gfile` functions with `os.path.dirname()` and `os.path.basename()` functions? I'm thinking this might cause the code to falsely reject e.g. an HDFS path on Windows. Or the test [on L1457](https://github.com/tensorflow/tensorflow/blob/f8dce81aeaff40dc78d398741854ad8766806f91/tensorflow/python/training/saver.py#L1457) might fail even though two filenames canonicalize to the same name. Maybe we should be delegating all `os.path` use in the Python libraries down to TensorFlow's C++ `Env` and `FileSystem` classes?

One other thing we could do in `saver.py` is to detect whenever a relative path is being supplied (which IIRC wasn't supported on any platform until the latest version) and eagerly convert it to an absolute path.
