### ISSUE TITLE
ValueError: Restore called with invalid save path

### ISSUE THREAD

**Issue by sharod** [tensorflow/tensorflow#9087]
I had saved the model after each epoch using:

savernew = tf.train.Saver(max_to_keep=10000)
sp="/ models/epoch"+str(i+1)+"/"
savernew.save(session, sp,global_step=sv.global_step)

Now I want to restore the epoch 88:

new_saver = tf.train.Saver()
new_saver.restore(sess, "/models/epoch88/")

I am getting the  error:

ValueError: Restore called with invalid save path: '/ models/epoch88/'. File path is: ' /models/epoch88/'

My tensorflow version is 0.11

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  **Make sure you also include the exact command if possible to produce  the output included in your test case.**   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  **Make sure you also include the exact command if possible to produce  the output included in your test case.**   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

**Comment by sharod** [comment]
OS - Ubuntu 16.04 LTS
Architechture - x86_64 
compiled using pip
TF version - 0.11
I had used the above lines in my code which was saved as test.py. So I used python test.py as command.

If there is any more info need pls ask, I will provide.

**Comment by asimshankar** [comment]
Please provide a full reproducible example. For example, I tried the following on both TensorFlow 0.11.0 and 1.0.1 and was unable to see a problem. It would greatly help if you can provide the failure.

```python
import tensorflow as tf

# Create a model and save it
x = tf.Variable(1)
with tf.Session() as sess:
  sess.run(tf.initialize_all_variables()) # tf.global_variables_initializer() in 1.0
  saver = tf.train.Saver()
  saver.save(sess, '/tmp/model')

# Restore in another session
with tf.Session() as sess:
  saver = tf.train.Saver()
  saver.restore(sess, '/tmp/model')
```
