### ISSUE TITLE
'tensorboard' command not found (raspberry pi 3)

### ISSUE THREAD

**Issue by phil123456** [tensorflow/tensorflow#9088]
Bug in installation (tensorflow python code runs fine)

here are the step I used to install TensorFlow :

```
sudo apt-get install python-pip python-dev
wget https://github.com/samjabrahams/tensorflow-on-raspberry-pi/releases/download/v1.0.1/tensorflow-1.0.1-cp27-none-linux_armv7l.whl
pip install --user tensorflow-1.0.1-cp27-none-linux_armv7l.whl
pip uninstall mock
pip install --user mock
sudo pip install --user git+https://github.com/tflearn/tflearn.git
```
the machine is a raspberrry pi v3 (raspbian v 8.0)
tensorflow v 1.0.1

problem :

I try to run tensorboard, I get a command not found

I tried locate, find, whereis, .... nothing, seems like it did not get installed with tensorflow

logs :

dont know if there are any install logs, if yes let me know where to find them

**Comment by asimshankar** [comment]
Those packages (https://github.com/samjabrahams/tensorflow-on-raspberry-pi and https://github.com/tflearn/tflearn.git) are not produced by the maintainers of the TensorFlow repository and are not part of the official release.

Since this isn't something owned or maintained by the TensorFlow maintainers, I'm going to close this out. I'd recommend building from source (perhaps using the instructions from @samjabrahams )

**Comment by phil123456** [comment]
ok, thx
