### ISSUE TITLE
problem with wide_n_deep_tutorial.py on Tensorflow 1.0

### ISSUE THREAD

**Issue by CBrauer** [tensorflow/tensorflow#9092]
Using Python 3.6.0 (Anaconda x64), Tensorflow 1.0, macOS Sierra version 10.12.4, I get the following error:

> 
> >  python wide_deep.py
> Training data is downloaded to /var/folders/h2/727s56vx40s_6n2z9ldl6kx00000gs/T/tmp76m50o3h
> Test data is downloaded to /var/folders/h2/727s56vx40s_6n2z9ldl6kx00000gs/T/tmpwzhof_zb
> model directory = /var/folders/h2/727s56vx40s_6n2z9ldl6kx00000gs/T/tmpclbsc2wm
> Traceback (most recent call last):
>   File "wide_deep.py", line 234, in <module>
>     tf.app.run(main=main, argv=[sys.argv[0]] + unparsed)
>   File "/Users/CBrauer/anaconda/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 44, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "wide_deep.py", line 197, in main
>     FLAGS.train_data, FLAGS.test_data)
>   File "wide_deep.py", line 185, in train_and_eval
>     m = build_estimator(model_dir, model_type)
>   File "wide_deep.py", line 132, in build_estimator
>     fix_global_step_increment_bug=True)
> TypeError: __init__() got an unexpected keyword argument 'fix_global_step_increment_bug'
> > 

Charles

**Comment by asimshankar** [comment]
Thanks for pointing this out. It seems that the tutorial code on the website is linking to the latest version instead of the version compatible with release 1.0.

Could you try with the tutorial version from the 1.0 branch?
https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/examples/learn/wide_n_deep_tutorial.py

I'll try to look into how to make sure that the links in the website point to the appropriate release branch.
