### ISSUE TITLE
Problem with seq2seq models in prediction

### ISSUE THREAD

**Issue by zzw922cn** [tensorflow/tensorflow#9095]
@mrry Hi, I am confused with a prediction problem implemented in TensorFlow seq2seq. I found that in seq2seq inference code, there must be a embedding matrix to step forward. But now, my problem is a continuous prediction problem, such as **price prediction**. **The output must be a sequence of floating numbers. I don't know how to embed these numbers**, so what should I do with TensorFlow seq2seq? Thanks a lot!!

**Comment by jart** [comment]
Thanks for reaching out. We try to keep this issue tracker limited to bugs and feature requests. We recommend posting on [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) for community-driven support. We have this policy so that guys like @mrry will have as much time as possible to make TensorFlow better for everyone. Thank you for your understanding.
