### ISSUE TITLE
Why is there NO input_data in the file?

### ISSUE THREAD

**Issue by Mulf** [tensorflow/tensorflow#9100]
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from (source or binary)?*:
- *TensorFlow version*:
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*:
- *GPU Model and Memory*:
- *Exact command to reproduce*:
My question is irrelevant to these. 

### Describe the problem clearly
I am learning the MNIST based on the tutorial on the [TensorFlow website](https://www.tensorflow.org/get_started/mnist/prosl)
the first line of code is: 
`from tensorflow.examples.tutorials.mnist import input_data`

But when I open the file in [GitHub](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/mnist.py)
I do not see the function Input_data in the file. WHY? 

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by asimshankar** [comment]
This question is better asked on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!

That said, `input_data` is a module and does exist in its own file. See: https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/tutorials/mnist/input_data.py

Closing this out since this doesn't seem to be a bug or feature request.
