### ISSUE TITLE
Tensorflow tests failing on s390x (Farmhash related)

### ISSUE THREAD

**Issue by Nayana-ibm** [tensorflow/tensorflow#9107]
Below tests are failing on big endian s390x platform.
The tests are failing due to farmhash doesn't support s390x platform.
We have already raised an [issue ](https://github.com/google/farmhash/issues/10) with farmhash. Test are passing after applying [patch](https://github.com/google/farmhash/issues/10#issuecomment-272068176) provided there. 

However, we would like to know if the testcases are used  for some complex functionality of TensorFlow?

Tests:
```
 //tensorflow/contrib/layers:sparse_feature_cross_op_test 
 //tensorflow/contrib/learn:tensorflow_dataframe_test 
 //tensorflow/contrib/linear_optimizer:sdca_ops_test 
 //tensorflow/core:platform_fingerprint_test

```

Tensorflow version: v0.10.0

**Comment by asimshankar** [comment]
If the fix is available in farmhash upstream, then it probably make sense to update [`workspace.bzl`](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/workspace.bzl#L186) so that it includes the fixed version. Would you like to send a PR for that?

(Also, if possible, I'd suggest moving to TensorFlow 1.0)

**Comment by Nayana-ibm** [comment]
@asimshankar The fix is not yet available in farmhash upstream. 
Here are the details: https://github.com/google/farmhash/issues/10

So, would like to know if the above mentioned testcases are used to test some complex functionality of TensorFlow? or they can be ignored?

**Comment by asimshankar** [comment]
@Nayana-ibm - Whether or not they can be ignored would depend on what your use case is. Certainly, these failures cannot be ignored if any of the operations in the model use the fingerprinting function (which would be the contrib ops whose test failed, plus some other operations in core that invoke the `Fingerprint64` and `Fingerprint128` functions).

They can be ignored if the codepaths you invoke don't call the `Fingerprint*` functions. Hard to say without more information, though I'd be conservative and suggest that this problem be fixed (and also, that you move to TensorFlow 1.0 instead of 0.10 if possible)

**Comment by Nayana-ibm** [comment]
Tensorflow uses farmhash as an external dependency, it fetches farmhash code through [this ](https://github.com/tensorflow/tensorflow/blob/v0.10.0/tensorflow/workspace.bzl) file.

```
native.new_http_archive(
    name = "farmhash_archive",
    url = "https://github.com/google/farmhash/archive/34c13ddfab0e35422f4c3979f360635a8c050260.zip",
```
    
Now, the required farmhash [patch ](https://github.com/google/farmhash/commit/2bc1fd0d958f6b6b2131ac70484aa81bfaf9b29a)for big endian s390x platform has been merged. 

So, TensorFlow can use [this](https://github.com/google/farmhash/commit/2bc1fd0d958f6b6b2131ac70484aa81bfaf9b29a) commit id for Tensorflow as to add support for big endian?

**Comment by Nayana-ibm** [comment]
When [this](https://github.com/google/farmhash/commit/2bc1fd0d958f6b6b2131ac70484aa81bfaf9b29a) commit id will be used in Tensorflow for farmhash?

**Comment by Nayana-ibm** [comment]
@asimshankar 
The farmhash fix (which is required for mentioned test-cases) is now available in farmhash upstream through [this](https://github.com/google/farmhash/commit/2bc1fd0d958f6b6b2131ac70484aa81bfaf9b29a) commit id.  Now, workspace.bzl can be updated with this commit id for farmhash. 

@gunan  Will it be possible to update workspace.bzl file to use [this ](https://github.com/google/farmhash/commit/2bc1fd0d958f6b6b2131ac70484aa81bfaf9b29a)commit id ?

**Comment by gunan** [comment]
Sorry for missing this issue.
@Nayana-ibm please feel free to send a pull request updating the pinned hash in tensorflow/workspace.bzl
You can assign the pull request to me.

**Comment by Nayana-ibm** [comment]
@gunan Thanks for your reply. 
I was a preparing patch for tensorflow/workspace.bzl file for PR however getting an issue with below link: 
//mirror.bazel.build/github.com/google/farmhash/archive/23eecfbe7e84ebf2e229bd02248f431c36e12f1a.zip"

on wget, it gives an error as: 
`HTTP request sent, awaiting response... 403 Forbidden`

Am I missing something here?

Also the patch requires sha256 for farmhash commit id.  I have calculated sha256 for farmhash commit id `23eecfbe7e84ebf2e229bd02248f431c36e12f1a` as  `55215f8cd3ddbe9781f6fe5cc228731d6dcc8301b6191c6d420034c3fff1cb8d`. 
can you please confirm if it's correct?

**Comment by gunan** [comment]
That is expected to fail. We manuqlly mirror dependencies on GCS once the
links are updated.

On Jul 18, 2017 8:16 AM, "Nayana Thorat" <notifications@github.com> wrote:

@gunan <https://github.com/gunan> Thanks for your reply.
I was a preparing patch for tensorflow/workspace.bzl file for PR however
getting an issue with below link:
//mirror.bazel.build/github.com/google/farmhash/archive/
23eecfbe7e84ebf2e229bd02248f431c36e12f1a.zip"

on wget, it gives an error as:
HTTP request sent, awaiting response... 403 Forbidden

Am I missing something here?

Also the patch requires sha256 for farmhash commit id. I have calculated
sha256 for farmhash commit id 23eecfbe7e84ebf2e229bd02248f431c36e12f1a as
55215f8cd3ddbe9781f6fe5cc228731d6dcc8301b6191c6d420034c3fff1cb8d.
can you please confirm if it's correct?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/tensorflow/issues/9107#issuecomment-315960192>,
or mute the thread

**Comment by Nayana-ibm** [comment]
patch committed to TensorFlow through [PR-11579](https://github.com/tensorflow/tensorflow/pull/11579).
Closing this issue.
