### ISSUE TITLE
Problem with label_image.py

### ISSUE THREAD

**Issue by swammaws** [tensorflow/tensorflow#9116]
NOTE: Issues that are not bugs or feature requests will be closed. Please ask usage questions on StackOverflow.
![capture](https://cloud.githubusercontent.com/assets/20141573/24884907/07d2d32c-1e4c-11e7-9568-fbaae2459860.PNG)

### You must complete this information or else your issue will be closed
- *Have I written custom code (as opposed to using a stock example script provided in TensorFlow)?*:
- *TensorFlow installed from (source or binary)?*:
- *TensorFlow version*:
- *Bazel version (if compiling from source)*:
- *CUDA/cuDNN version*:
- *GPU Model and Memory*:
- *Exact command to reproduce*:

### Source Code / Logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full-traceback. Large logs and files should be attached. Try to reproducible test-case code the bare-minimum necessary to generate the problem

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!
