### ISSUE TITLE
"Cannot allocate memory" error on first Udacity assignment

### ISSUE THREAD

**Issue by mamigot** [tensorflow/tensorflow#912]
![screenshot](http://i.imgur.com/r1PTe4C.png)

Though, as the screenshot shows, I have allocated 5GB of memory to the Docker container running [the course's first Jupyter notebook](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/examples/udacity/1_notmnist.ipynb), I can't seem to get past this cell because of Python's `cannot allocate memory` error. Sometimes it happens with `notMNIST_large/B` and sometimes with `notMNIST_large/C`. I don't see why this error is thrown when the container reaches 1.4GB, since it should be able to go up to 5GB...

I doubt this is a problem with TensorFlow but, since it's part of the course, I figured this issue might be helpful to other students as well.

This is the Docker command I'm running (differs from [the original command](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/examples/udacity#running-the-docker-container-from-the-google-cloud-repository) in that this gets rid of `--rm` and adds `--memory=5gb`):
```shell
docker run --name udacity_deep_learning --memory=5g -p 8888:8888 -it b.gcr.io/tensorflow-udacity/assignments
```

**Comment by vincentvanhoucke** [comment]
If you have more memory than that, can you try raising the ceiling and see if it fails later?
Someone else commented they had needed more.

**Comment by mamigot** [comment]
`--memory=8g` let it go up to `notMNIST_large/D`... then it went back down to `notMNIST_large/C` with 12GB before it crashed with the same `OSError: [Errno 12] Cannot allocate memory`.

Meanwhile the usage stats of the container (`docker stats udacity_deep_learning`) show that it's nowhere near the limit (the most it went up to before crashing was about 1.5GB)

```
CONTAINER               CPU %               MEM USAGE / LIMIT     MEM %               NET I/O               BLOCK I/O
udacity_deep_learning   0.01%               1.402 GB / 12.88 GB   10.88%              256.3 MB / 657.9 kB   733.4 MB / 237.6 kB
```

Thank you for your help!

**Comment by vincentvanhoucke** [comment]
@timothyjlaurent was successful with the Docker container. Any gotcha there? I haven't tried recently. Maybe @craigcitro has some advice too.

**Comment by timothyjlaurent** [comment]
What I did to get it running was to ensure that my docker-machine VM had sufficient memory. Initially the VM only had 4GB, increasing the VM to have 8GB was sufficient to get it working. Also, you don't need to tune the amount of memory in the `docker run`  command -- docker will use whatever is available if you don't specify a constraint.

1 last IMPORTANT hint -- mount the udacity directory in your container like so 

`docker run --rm -v <path to udacity dir>`:/notebooks <image name>`

This will ensure that all the work and FS writes will go on your disk and not be ephemerally lost when your container goes down. 

hope this helps  @mamigot

**Comment by craigcitro** [comment]
ah, this one is interesting: the problem here is that while `docker run` happily allocates more memory to the container, the problem is that the underlying **vm** (owned by `docker-machine`) doesn't have any more memory to give.

i followed the second option in [this SO post](http://stackoverflow.com/questions/32834082/how-to-increase-docker-machine-memory-mac) to bump the underlying vm's memory to 8GB, and things seem to be humming along.

so:
* we probably want to add a note to the course instructions for OSX users about ensuring their machine has enough RAM.
* `docker stats` probably wasn't lying about the total memory *used*, just about total amount *available*. :grin: 
* it's also possible that we could do a bit more cleanup of leftover objects in the python code itself (i think sometimes numpy is bad about cleaning up after itself, but i could be wrong), but that's really a secondary concern (since we definitely need more memory in the base VM regardless).

**Comment by vincentvanhoucke** [comment]
Would someone who understands this well mind adding those tips to the README.md?

**Comment by craigcitro** [comment]
Sending a CL out now.

**Comment by vincentvanhoucke** [comment]
Gracias

**Comment by mamigot** [comment]
Thank you, @vincentvanhoucke, @craigcitro and @timothyjlaurent , that worked perfectly!
Looking forward to the course and using TensorFlow!
