### ISSUE TITLE
no such package '@gmock_archive//': Error downloading in Tensorflow (on ubuntu_X86 14.04) 

### ISSUE THREAD

**Issue by sandipmgiri** [tensorflow/tensorflow#9123]
I'm getting the following error when trying to run the configure command (on ubuntu_X86:14.04):

ERROR: /root/tf/tensorflow/tensorflow/workspace.bzl:221:3: no such package '@gmock_archive//': Error downloading

Please find the attached log for more details.
[logfile.txt](https://github.com/tensorflow/tensorflow/files/912026/logfile.txt)

Note- On ubuntu-ppc64le vm , configure command ran successfully.

Any suggestion/solution ?

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also **include your TensorFlow version**. Also, did you compile from source or install a binary?  **Make sure you also include the exact command** if possible to produce  the output included in your test case.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

Though, looking at the log file you provided and the errors like:

```
ERROR: /root/tf/tensorflow/tensorflow/workspace.bzl:221:3: no such package '@gmock_archive//': Error downloading [http://bazel-mirror.storage.googleapis.com/pkgs.fedoraproject.org/repo/pkgs/gmock/gmock-1.7.0.zip/073b984d8798ea1594f5e44d85b20d66/gmock-1.7.0.zip, http://pkgs.fedoraproject.org/repo/pkgs/gmock/gmock-1.7.0.zip/073b984d8798ea1594f5e44d85b20d66/gmock-1.7.0.zip] to /root/.cache/bazel/_bazel_root/8e11c3f2ede966708196f520db8b1e69/external/gmock_archive/gmock-1.7.0.zip: All mirrors are down: [Checksum was 49a998729226839bc06d6d4b8384af0c83e05e842b979193f43e1c3440e9cd16 but wanted 26fcbb5925b74ad5fc8c26b0495dfc96353f4d553492eb97e85a8a6d2f43095b, Checksum was dc73d26ce544ae4ba7f1ad6d305de0dee72bd953e4bfd9ba7170b2d5326946de but wanted 26fcbb5925b74ad5fc8c26b0495dfc96353f4d553492eb97e85a8a6d2f43095b] and referenced by '//external:gtest'
```

there seems to be some network error on the machine that might be truncating or corrupting the files.
