### ISSUE TITLE
How to reinitialize state prior to inference with RNN

### ISSUE THREAD

**Issue by kevinashaw** [tensorflow/tensorflow#9127]
I have an RNN graph which has been trained in TF with good accuracy, but when it runs in Android (using libtensorflow_inference.so) it runs poorly.  I have a hypothesis that the problem is due to the statefulness of the RNN.  It is my understanding that during training the RNN state is reinitialized to a fresh state with each minibatch.  However, when running in reallife, it is running continuously without the state being refreshed.  Thus causing anomalous results.
Is there a way to force the state to be refreshed when running in an Android environment?  I note that the java interface (tensorflowinferenceinterface.java) has no such method.
I have also documented this inquiry in SO nine days ago, but had no response: [link](http://stackoverflow.com/questions/43159921/tensorflow-initializing-state-for-rnn-between-inferences-in-android).

**Comment by jart** [comment]
Kevin, you did the right thing by originally going to StackOverflow with this question. This issue tracker is not an escalation path.

We have a *bugs and feature requests only policy* on this issue tracker. The reason is because TensorFlow developers respond to issues (usually within a day.) Our goal is to focus on work that benefits everyone in the community, e.g. fixing bugs and writing features. Support only helps individuals. Filing an issue also causes thousands of people receive notifications. We want those people to see individuals communicating the most interesting problems possible.

The reason why I'm explaining the policy is because I'm noticing this isn't the first issue. I believe policy works best when it's transparent.
