### ISSUE TITLE
NotFoundError while restoring inception_v3 model

### ISSUE THREAD

**Issue by VigneshSrinivasan10** [tensorflow/tensorflow#9131]
Hi,

I am trying to make use of `inception_v3` model from `https://github.com/tensorflow/models/tree/master/slim`

After downloading the model as described in the webpage, I wanted to restore the model using 

    saver = tf.train.Saver()
    saver.restore(sess, 'model/inception_v3.ckpt')

And I get this error: 

    NotFoundError (see above for traceback): Tensor name "InceptionV3/Mixed_6d/Branch_1/Conv2d_0c_7x1/biases" not found in checkpoint files model/inception_v3.ckpt

Upon inspection of `tf.trainable_variables()`, i find the variable with name -    

    "InceptionV3/Mixed_6d/Branch_1/Conv2d_0c_7x1/biases:0"

Is the suffix `:0` causing this error ? If not how can i load this model ? 

I raised this issue @tensorflow/models, but unfortunately, I did not get any response. 
Thanks in advance!

**Comment by poornagurram** [comment]
I think while you are trying to download the model you might have downloaded it partially or somewhere else so you got that error.

**Comment by jart** [comment]
@VigneshSrinivasan10 We monitor both tensorflow/tensorflow and tensorflow/models when working on issues, so crossposting is not necessary. https://github.com/tensorflow/models/issues/1315.

**Comment by jart** [comment]
Also take into consideration that opening an issue here causes thousands of people to receive notifications. We want them to see an individual communicating an interesting problem, rather than being redirected to Stack Overflow. The TensorFlow team aims to focus on work that benefits the entire community, e.g. fixing bugs and writing features. Support only helps individuals.
