### ISSUE TITLE
Broken link in Python API documentation on RNN and Cells (contrib)

### ISSUE THREAD

**Issue by AnnikaLindh** [tensorflow/tensorflow#9134]
There's a broken link in the Python API documentation on RNN and Cells (contrib).

The link appears at the very bottom of this page: www.tensorflow.org/api_guides/python/contrib.rnn
Title of link: tf.contrib.rnn.stack_bidirectional_dynamic_rnn
URL of link: https://www.tensorflow.org/api_guides/python/BROKEN_LINK

**Comment by asimshankar** [comment]
Thanks for pointing this out. 

There seems to an issue with the website push that accidentally pushed the guide for version 1.1 instead of for the current stable release 1.0. `tf.contrib.rnn.stack_bidirectional_dynamic_rnn` is not available in 1.0.
(FYI @wolffg )

However, those symbols do (and will) exist in release 1.1. So, in the mean time you're welcome to try out the 1.1 release candidate version (or wait for it's final release) and the documentation can be found inhttps://www.tensorflow.org/versions/r1.1/api_docs/python/tf/contrib/rnn/stack_bidirectional_rnn

Once the 1.1 release is made, this page will be fixed.

Closing it out since I believe the problem has been fixed in code and will update itself on the next website/release push.
