### ISSUE TITLE
YoloDetector example needs java_test() rule

### ISSUE THREAD

**Issue by zgq91** [tensorflow/tensorflow#9135]
Hi:
   when I use android studio to compile TensorflowYoloDetector, the following error occurs:

E/art: No implementation found for long org.tensorflow.contrib.android.RunStats.allocate()

 (tried Java_org_tensorflow_contrib_android_RunStats_allocate and  Java_org_tensorflow_contrib_android_RunStats_allocate__)

TensorFlowInferenceInterface: TensorFlow native methods not found, attempting to load via tensorflow_inference
TensorFlowInferenceInterface: Successfully loaded TensorFlow native methods (RunStats error may be ignored)

TensorFlowInferenceInterface: Failed to load model from 'file:///android_asset/graph-tiny-yolo-voc.pb': java.io.IOException: Not a valid TensorFlow Graph serialization: Invalid GraphDef

tensorflow: TensorFlowYoloDetector: TF init status: 1.

　　 Look forward to your reply.

**Comment by andrewharp** [comment]
`TensorFlowInferenceInterface: Failed to load model from 'file:///android_asset/graph-tiny-yolo-voc.pb': java.io.IOException: Not a valid TensorFlow Graph serialization: Invalid GraphDef`

It doesn't sound like you've put the required model into the assets/ directory. The yolo model isn't provided with TF, so you'll need to create it yourself and add it to the demo. There are instructions on using darkflow to create one in TensorFlowDetectorActivity.java.

**Comment by jart** [comment]
This broke when the RunStats interface was added in 6005d639932dd586733bfb3f50a9925f195c3910. The author must have forgotten to implement `allocate` in the class definition. Root cause IMHO is there not being a `java_test` rule for this example. We have `@junit` defined in workspace.bzl. Shouldn't be too much trouble to add a BUILD file to that directory with a test rule.

**Comment by andrewharp** [comment]
@jart Actually, it just tries to call allocate() to see if the native methods are loaded. The following log messages indicate that they were, so the previous error can be ignored (I'm unaware of any means to suppress it or otherwise test for native method existence).

Regarding testing: even though @jnuit may be available for Java tests I don't believe Bazel supports android_test rules yet (we actually have a few Android tests internally that are not exposed yet due to this).

**Comment by andrewharp** [comment]
@zgq91 
To clarify, this error has nothing at all to do with RunStats, that's just a red herring.

I'd need more info to debug the actual YOLO problem (like what's the output of `unzip -v tensorflow_demo.apk`), but if you're doing anything outside the basic tiny-yolo-voc sample conversion command shown in DetectorActivity then it's outside the scope of TF support.

**Comment by jart** [comment]
@andrewharp It seems I misread the yolo class, for some reason thinking it implemented RunStats. I'll let you take matters from here. I'll also send you an email with some thoughts on how we can improve the Android testing situation.

**Comment by shenyingying** [comment]
@jart hi have you implementation in yolov2.pb or yolov2-tiny.pb not the tiny-yolo-voc.pb ,should i change the label in source code,it seems like ,but there is something wrong in my project?can anyone help me,thanks a lot
