### ISSUE TITLE
Bazel build  error loading package 'tensorflow/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent call last):

### ISSUE THREAD

**Issue by JMBokhorst** [tensorflow/tensorflow#9222]
I'm trying to build a simple script,  however while compiling i get the following error: 

ERROR: C:/users/john/downloads/tensorflow-master/tensorflow/loader/BUILD:1:1: error loading package 'tensorflow/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent call last):
        File "C:/users/john/downloads/tensorflow-master/tensorflow/workspace.bzl", line 88
                _apply_patch(repo_ctx, repo_ctx.attr.patch_file)
        File "C:/users/john/downloads/tensorflow-master/tensorflow/workspace.bzl", line 79, in _apply_patch
                _execute_and_check_ret_code(repo_ctx, ["patch", "-p1", "-d", r...), <2 more arguments>])
        File "C:/users/john/downloads/tensorflow-master/tensorflow/workspace.bzl", line 71, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(256) when executing 'patch -p1 -d C:/tools/msys64/tmp/_bazel_john/mzdlugz6/external/protobuf -i C:/users/john/downloads/tensorflow-master/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: java.io.IOException: CreateProcess(): The system cannot find the file specified.
 and referenced by '//tensorflow/loader:test850.dll'.

protobuf is installed:

$ protoc --version
libprotoc 3.2.0

$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:02:06 2017 (1489669326)
Build timestamp: 1489669326
Build timestamp as int: 1489669326

I have build bazel with chocolatery as described on the bazel site.

Tried solution from issue #5029 (although the error is different). If i run the exact same script with bazel on a mac everything is fine and the build completes (no this is unfortunate not a solution). So i know the problem is with windows bazel and maybe the paths? 

Also tried to compile with CMAKE however with no succes

**Comment by asimshankar** [comment]
Please provide details about what platform you are using  (operating system, architecture). Also include your TensorFlow version. Also, did you compile from source or install a binary?  Make sure you also include the exact command if possible to produce  the output included in your test case.   We ask for this in the issue submission template, because    it is really difficult to help without that information. Thanks!

(In general, please fill out ALL the information asked for in the new issue template)

**Comment by JMBokhorst** [comment]
Sorry my bad: 

------------------------

### System information
OS: windows 10 64 bit
Tensorflow installed with for windows python 3 (without GPU) from binary (pip3 install....)
Tensorflow version: 
>>> import tensorflow as tf; print(tf.__version__)
1.0.1

$ protoc --version
libprotoc 3.2.0

$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:02:06 2017 (1489669326)
Build timestamp: 1489669326
Build timestamp as int: 1489669326

### Describe the problem
While building a script with tensorflow as dependancy, bazel fails on protobuf when bazel is analyzing. 

Last INFO before i get for the error: 
INFO: Downloading http://bazel-mirror.storage.googleapis.com/github.com/google/protobuf/archive/2b7430d96aeff2bb624c8d52182ff5e4b9f7f18a.tar.gz: 40,960 bytes
 
The problem occurs when i try to build a simple script with tensorflow included, or when i just try to build anything with tensorflow as dependancy. 

Problem also only occurs when including deps[//tensorflow/core:tensorflow]. Problem does not occur when building the same files on a mac (also with tensorflow v1.0.1 and bazel 0.4.5).

### Source code / logs
$ bazel build --cpu=x64_windows_msvc :test.dll
WARNING: C:/tools/msys64/tmp/_bazel_john/hawbuxgu/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
.
WARNING: C:/tools/msys64/tmp/_bazel_john/hawbuxgu/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
.
WARNING: C:/tools/msys64/tmp/_bazel_john/hawbuxgu/external/bazel_tools/tools/cpp/cc_configure.bzl:57:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
.
ERROR: C:/_shared/_tensorflow_build_test/tf/tensorflow/tensorflow/_test_tensorflow_files/BUILD:1:1: error loading package 'tensorflow/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent call last):
        File "C:/_shared/_tensorflow_build_test/tf/tensorflow/tensorflow/workspace.bzl", line 98
                _apply_patch(repo_ctx, repo_ctx.attr.patch_file)
        File "C:/_shared/_tensorflow_build_test/tf/tensorflow/tensorflow/workspace.bzl", line 87, in _apply_patch
                _execute_and_check_ret_code(repo_ctx, ["patch", "-p1", "-d", r...), <2 more arguments>])
        File "C:/_shared/_tensorflow_build_test/tf/tensorflow/tensorflow/workspace.bzl", line 79, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(256) when executing 'patch -p1 -d C:/tools/msys64/tmp/_bazel_john/hawbuxgu/external/protobuf -i C:/_shared/_tensorflow_build_test/tf/tensorflow/third_party/protobuf/add_noinlines.patch':
Stdout:
Stderr: java.io.IOException: CreateProcess(): The system cannot find the file specified.
 and referenced by '//tensorflow/_test_tensorflow_files:test.dll'.
ERROR: Analysis of target '//tensorflow/_test_tensorflow_files:test.dll' failed; build aborted.
INFO: Elapsed time: 12.000s

**Comment by asimshankar** [comment]
Ah, I see, the `patch` command is not available and needs to be installed.
See https://github.com/tensorflow/tensorflow/issues/8919#issue-218857845 for inspiration and let us know if that works.

Thanks.

**Comment by JMBokhorst** [comment]
That seemed to be te problem indeed. Thank you very much!

**Comment by BerndSchmitt** [comment]
I have nearly the same problem here. (i think):

System information
OS: windows 7 64 bit
Tensorflow installed with for windows python 3 (with GPU) from binary (pip3 install....)

Tensorflow version:

import tensorflow as tf; tf.__version__
'1.0.1'

I do not have any protoc ...

$ bazel version
WARNING: ignoring http_proxy in environment.
Build label: 0.5.2- (@non-git)
Build target: bazel-out/msys_x64-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Jul 6 10:39:46 2017 (1499337586)
Build timestamp: 1499337586
Build timestamp as int: 1499337586



Describe the problem

The problem occurs when i try to build a simple script with tensorflow included https://www.tensorflow.org/api_guides/cc/guide

in order to understand the problem better i changed names

Source code / logs
the directory .../Sourcen/external/tensorflow-master/tensorflow/cc/example1/ contains 3 files
WORKSPACE
BUILD
example-code.cc

----- WORKSPACE 
----------------------> empty


--- BUILD
cc_binary(
    name = "example-out",
    srcs = ["example-code.cc"],
    deps = [
        "//tensorflow/cc:cc_ops",
        "//tensorflow/cc:client_session",
        "//tensorflow/core:tensorflow",
    ],
)
--------------------------


--- example-code.cc
// tensorflow/cc/example/example.cc
#include "tensorflow/cc/client/client_session.h"
#include "tensorflow/cc/ops/standard_ops.h"
#include "tensorflow/core/framework/tensor.h"

int main() {
  using namespace tensorflow;
  using namespace tensorflow::ops;
  Scope root = Scope::NewRootScope();
  // Matrix A = [3 2; -1 0]
  auto A = Const(root, { {3.f, 2.f}, {-1.f, 0.f}});
  // Vector b = [3 5]
  auto b = Const(root, { {3.f, 5.f}});
  // v = Ab^T
  auto v = MatMul(root.WithOpName("v"), A, b, MatMul::TransposeB(true));
  std::vector<Tensor> outputs;
  ClientSession session(root);
  // Run and fetch v
  TF_CHECK_OK(session.Run({v}, &outputs));
  // Expect outputs[0] == [19; -3]
  LOG(INFO) << outputs[0].matrix<float>();
  return 0;
}
--------------------------


using msys2 to run bazel in .../Sourcen/external/tensorflow-master/


$ bazel run -c opt //tensorflow/cc/example1:example-out
WARNING: ignoring http_proxy in environment.
WARNING: C:/tools/msys64/tmp/_bazel_xxxxxx/6esgz-yl/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: 'BAZEL_VC' is not set, start looking for the latest Visual C++ installed.
.
WARNING: C:/tools/msys64/tmp/_bazel_xxxxxxx/6esgz-yl/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: Looking for VS%VERSION%COMNTOOLS environment variables,eg. VS140COMNTOOLS
.
WARNING: C:/tools/msys64/tmp/_bazel_xxxxxxxx/6esgz-yl/external/bazel_tools/tools/cpp/cc_configure.bzl:67:3:
Auto-Configuration Warning: Visual C++ build tools found at C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\
.
ERROR: xxxxxx...../tensorflow-master/tensorflow/cc/example1/BUILD:1:1: error loading package 'tensorflow/core': Encountered error while reading extension file 'protobuf.bzl': no such package '@protobuf//': Traceback (most recent call last):
        File "xxxxxxxx.../tensorflow-master/tensorflow/workspace.bzl", line 116
                _apply_patch(repo_ctx, repo_ctx.attr.patch_file)
        File "xxxxx..../tensorflow-master/tensorflow/workspace.bzl", line 107, in _apply_patch
                _execute_and_check_ret_code(repo_ctx, cmd)
        File "xxxxx..../tensorflow-master/tensorflow/workspace.bzl", line 91, in _execute_and_check_ret_code
                fail("Non-zero return code({1}) when ..., <2 more arguments>))
Non-zero return code(1) when executing 'c:/tools/msys64/usr/bin/bash.exe -c patch -p1 -d C:/tools/msys64/tmp/_bazel_xxxxx/6esgz-yl/external/protobuf -i xxxxx..../tensorflow-master/third_party/protobuf/add_noinlines.patch':
Stdout: can't find file to patch at input line 4
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff -u -r a/src/google/protobuf/compiler/cpp/cpp_file.cc b/src/google/protobuf/compiler/cpp/cpp_file.cc
|--- a/src/google/protobuf/compiler/cpp/cpp_file.cc     2017-02-10 23:55:34.000000000 +0100
|+++ b/src/google/protobuf/compiler/cpp/cpp_file.cc     2017-03-21 13:41:46.931979154 +0100
--------------------------
File to patch:
Skip this patch? [y]
Skipping patch.
3 out of 3 hunks ignored

Stderr:  and referenced by '//tensorflow/cc/example1:example-out'.
ERROR: Analysis of target '//tensorflow/cc/example1:example-out' failed; build aborted.
INFO: Elapsed time: 9,402s
ERROR: Build failed. Not running target.
