### ISSUE TITLE
why there are not file "decoder_fn.py"

### ISSUE THREAD

**Issue by CTsing** [tensorflow/tensorflow#9251]
why there are not file "decoder_fn.py",which mention in the tensorflow website(https://www.tensorflow.org/api_docs/python/tf/contrib/seq2seq/simple_decoder_fn_inference).

**Comment by asimshankar** [comment]
Apologies, the website generator is incorrectly linking to the master branch when in this case it should be linking to the latest release: https://github.com/tensorflow/tensorflow/blob/r1.0/tensorflow/contrib/seq2seq/python/ops/decoder_fn.py

@wolffg is in the process of fixing the website generator so that it links to code in the appropriate release branch.
