### ISSUE TITLE
[cmake/feature request] provide USE_SYSTEM_xxx flags to skip dependency builds

### ISSUE THREAD

**Issue by CDLuminate** [tensorflow/tensorflow#9298]
Tensorflow's cmake build will download and compile all of its dependency. Julia[1] does something similar to maximize its performance. However Julia provided some optional flags such as `USE_SYSTEM_FFTW` so users can compile Julia against the FFTW library provided by system package manager (e.g. `apt/dpkg`). I wish Tensorflow's cmake build could provide similar options to skip building its dependencies and just use the system provided one.

[1] https://github.com/JuliaLang/julia/blob/master/Makefile#L243

**Comment by mrry** [comment]
This seems like a reasonable request, although it's one we're unlikely to use for releases because linking together one huge static library from the exact versions of the library dependencies is easier to reason about. (Indeed, most of the trouble with the Windows version has been "DLL hell" of one form or another.)

However, I can see why this would be useful for local source development, and would be happy to review contributions to the CMake build that allow this!

**Comment by itsmeolivia** [comment]
Automatically closing due to lack of recent activity. Since this issue is old at this point, please reopen the issue if it still occurs when tried with the latest version of Tensorflow. Thank you.

**Comment by CDLuminate** [comment]
This should be reopened.
