### ISSUE TITLE
grpc error in distributed tensorlfow 

### ISSUE THREAD

**Issue by TomorrowIsAnOtherDay** [tensorflow/tensorflow#9377]
pciBusID 0000:04:00.0
Total memory: 11.17GiB
Free memory: 11.10GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K40m, pci bus id: 0000:04:00.0)
**# E0422 12:13:21.315971987   26528 tcp_server_posix.c:148]     check for SO_REUSEPORT: {"created":"@1492834401.315943300","description":"OS Error","errno":92,"file":"external/grpc/src/core/lib/iomgr/socket_utils_common_posix.c","file_line":181,"os_error":"Protocol not available","syscall":"setsockopt(SO_REUSEPORT)"}**
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:200] Initialize GrpcChannelCache for job ps -> {0 -> localhost:8865}
I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:200] Initialize GrpcChannelCache for job worker -> {0 -> localhost:8866}
I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:221] Started server with target: grpc://localhost:8865

I try distributed tensorflow and start only one server and one worker, the model does not converge as the local version.

**Comment by drpngx** [comment]
Please report OS and version.

**Comment by TomorrowIsAnOtherDay** [comment]
Linux version 2.6.32_1-13-0-0

**Comment by TomorrowIsAnOtherDay** [comment]
(gcc version 4.4.4 20100726 (Red Hat 4.4.4-13) (GCC) )            CentOS release 6.3 (Final)

**Comment by drpngx** [comment]
What distribution?

**Comment by mrry** [comment]
2.6.32 is a very old kernel... I don't think it supports `SO_REUSEPORT`, which as far as I can tell was [merged in 2013](https://lwn.net/Articles/542629/) (to Linux 3.9).

As far as I remember, we don't actually use this feature but gRPC enables it by default on some sockets. We actually try to [disable it on server sockets](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc#L58), because it wreaks havoc with our unit tests.

**Comment by drpngx** [comment]
@TomorrowIsAnOtherDay I am closing since this is not a supported platform. Your options at this points are to either disable that feature in your private copy of tensorflow and rebuild, or upgrade your kernel. The comment on [stackoverflow](http://stackoverflow.com/questions/3261965/so-reuseport-on-linux) indicates that there was a backport for `2.6.32`, so this might be the most viable option.

**Comment by TomorrowIsAnOtherDay** [comment]
I will try to update my kernel, thanks for your reply.
