### ISSUE TITLE
[Java] Distributed mode support

### ISSUE THREAD

**Issue by mdymczyk** [tensorflow/tensorflow#9420]
### Describe the problem

Is there any plan to add distributed mode to the Java API? I checked the code and it seems to be doable (unless I missed something) so I was wondering if anyone is already working on it? I went through the issue tracker and PRs but couldn't find anything related.

**Comment by girving** [comment]
The Java API is focused on inference, where distributed mode is usually not relevant.  Do you have an application?

**Comment by mdymczyk** [comment]
@girving I wanted to create and train the model using the Java API instead of having to train in Python, save the graph file and then load it using the Java API. Would make the whole workflow much easier if I could do it from the same tech stack.

I can have a look at how hard it's to implement and make a PR (if it's doable), but my question is would such a PR have any chance of being accepted or are you set on only inference and keeping the Java API minimal?

**Comment by girving** [comment]
@asimshankar and @mrry: Can you comment?  My naive hunch is that distributed support is fairly straightforward; just a matter of adding another parameter to the `Session` constructor.  Except, of course, that one has to arrange for all the processes to exist and connect.  However, I'm not sure how useful it will be given the Java API's lack of graph construction support.

**Comment by mrry** [comment]
Yes, it looks like the [bindings in `Session.java`](https://github.com/tensorflow/tensorflow/blob/28091dce41045570b7d92eb912eddce0079c0234/tensorflow/java/src/main/java/org/tensorflow/Session.java#L51) are missing the equivalent of a `target` argument. For a pure-Java solution, we'd also want some bindings for the equivalent of Python's `tf.train.Server`, which should be fairly easy to add&mdash;but right now they are part of the "no stability guarantees" C++ API, rather than the stable C API.

**Comment by mdymczyk** [comment]
Cool, thanks @girving and @mrry  - I was mostly worried that some parts of the distributed impl were only done in Python and I missed them. I'll put something together since I need it for myself and PR, then you can decide if you want it or not.

**Comment by girving** [comment]
If you might submit a PR, I'll reopen this and mark it contributions welcome.  It's good to have a place to track feature requests.
