### ISSUE TITLE
Tons of warnings related to GUARDED_BY on Mac

### ISSUE THREAD

**Issue by girving** [tensorflow/tensorflow#955]
I get a bunch of these:

    In file included from tensorflow/core/framework/load_library.cc:20:
    ./tensorflow/core/framework/op_kernel.h:945:63: warning: 'guarded_by' attribute requires arguments whose type is annotated with 'capability' attribute; type here is 'tensorflow::mutex' [-Wthread-safety-attributes]
      gtl::InlinedVector<WrappedAllocator, 4> wrapped_allocators_ GUARDED_BY(mu_);
                                                                  ^
    ./tensorflow/core/platform/default/thread_annotations.h:52:53: note: expanded from macro 'GUARDED_BY'
    #define GUARDED_BY(x) THREAD_ANNOTATION_ATTRIBUTE__(guarded_by(x))
                                                        ^
    ./tensorflow/core/platform/default/thread_annotations.h:42:57: note: expanded from macro 'THREAD_ANNOTATION_ATTRIBUTE__'
    #define THREAD_ANNOTATION_ATTRIBUTE__(x) __attribute__((x))

**Comment by girving** [comment]
We should probably run this by a clang-knowledgeable person, since the answer is presumably very simple given that knowledge.

**Comment by girving** [comment]
@keveman: Do you know the right person to ask?

**Comment by jendap** [comment]
@girving I have tried to fix them a week... https://github.com/jendap/tensorflow/commit/7db4674218f4a8822d2db5d4f63682beb05ba6fd put down the 50+ MB log on mac build of CI down to less than 1MB.

But it does not go away completely. The problem is that std::unique_lock does not have SCOPED_LOCKABLE annotation in /Library/Developer/CommandLineTools/usr/include/c++/v1/mutex. Either we have to create our MutexLock (should not be too hard) or disable the warning.

**Comment by girving** [comment]
@jendap Was this ever fixed?

**Comment by yaroslavvb** [comment]
I see 3-4 GUARDED_BY warnings in today's head --
http://pastebin.com/AbSxRzKJ
That doesn't seem like a "ton" since there are >600 warnings not related to
guarded_by

**Comment by girving** [comment]
Closing since "tons" no longer applies. :)
