### ISSUE TITLE
Documentation pages are unnecessarily large

### ISSUE THREAD

**Issue by ppwwyyxx** [tensorflow/tensorflow#9566]
```
curl https://www.tensorflow.org/api_docs/python/tf/abs | wc -c  # 1841844 (1.8MB)
```
Each page in the documentation now contains a HUGE left navbar contributing over 99% of the size.

1. This would waste a lot of network traffic on loading identical navbar over and over again.
2. It creates a big trouble when I tried to build an offline version of the doc. The whole html documents used to be <100MB, now they are 2.5GB.

**Comment by JamieDawson** [comment]
This topic brings up a lot of good points.
Where would I go into the REPO to find the code for the navbar?

**Comment by aselle** [comment]
@wolffg, please take a look. cc @martinwicke.

**Comment by ppwwyyxx** [comment]
The whole documentation now has become 8GB.

**Comment by wolffg** [comment]
Thanks for reporting this.  If you check out your Network tab on Chrome, you aren't normally downloading 2.3Mb each time, but closer to about 700K.  That's still a lot, but less than you'd think looking at the final result.

Having said that, we're aware that there are just a lot of links on the API reference pages now, and that can make pages feel slow, especially on mobile.  We're discussing how we can keep the pages navigable but reduce the render speed.

Rather than scraping our site, it might be faster to generate the API reference yourself, which you can do with instructions here: 

https://www.tensorflow.org/community/documentation#generating_docs_and_previewing_links

The final leftnav generators generate exclusively for our internal serving architecture, so we haven't made them public, but you can run the core API generator scripts yourself with those instructions and you should get TOC files.

**Comment by ppwwyyxx** [comment]
Thanks for the comment! Indeed, the network traffic isn't huge because pages are downloaded as gzip.

The doc generation works for me, although I still prefer the official nice-looking html. I'll find my own way out for offline docs.
