### ISSUE TITLE
Why the basic function of different rnn cells are different?

### ISSUE THREAD

**Issue by rylanchiu** [tensorflow/tensorflow#9600]
I'd like to tackle two issues. The first one is about the initializer. I can define initializer in `LSTMCell ` but not in `GRU` cell. The second one is `layer_normalization`. There is `LayerNormBasicLSTMCell` available for using layer normalization on LSTM cell. But there is not other kinds of cell used in that way. I wonder why not make this general functions available for all kinds of cells?

**Comment by ebrevdo** [comment]
PRs are welcome.

**Comment by chris-chris** [comment]
If there is no volunteer yet, can I try this issue?
I reviewed source codes of GRUCell, LSTMCell, and LayerNormBasicLSTMCell.
I think I can give it a shot.

**Comment by ebrevdo** [comment]
If making API changes I encourage sooner rather than later. They should be
backwards compatible. I'll move rnncells back to core soon and it will be
harder to make changes after that.

**Comment by chris-chris** [comment]
@ebrevdo Okay, I'll make it quick.

There are two tasks.
1. Add initializer parameter to GRUCell, MultiRNNCell
I've done this issue. I'll make a PR for this one first.

2. Add layer_norm, norm_gain, norm_shift parameters
 to TimeFreqLSTMCell, CoupledInputForgetGateLSTMCell, GridLSTMCell, BidirectionalGridLSTMCell ( all LSTMCells in rnn_cell.py )

```
    Args:
      layer_norm: If `True`, layer normalization will be applied.
      norm_gain: float, The layer normalization gain initial value. If
        `layer_norm` has been set to `False`, this argument will be ignored.
      norm_shift: float, The layer normalization shift initial value. If
        `layer_norm` has been set to `False`, this argument will be ignored.
```

This issue will take some more time to apply because I couldn't find a way to make general wrapper like `LayerNormWrapper`(I named it).

I think I need to add layer_norm parameters to all those LSTMCells, and implement it separately.
If you have any good idea, please tell me.

**Comment by chris-chris** [comment]
https://github.com/chris-chris/tensorflow/commit/a9ddcbddddb3d8a375c1e128d3c21b78e8bef2f6

I applied layer normalization to CoupledInputForgetGateLSTMCell. 
But I'm not sure that this is the right application. So I need some reviews.
I didn't make a PR yet.

Please leave a comment if you have any feedback.

I'm now reading the references for layer normalization now...

[Reference]
https://arxiv.org/abs/1607.06450
"Layer Normalization"
Jimmy Lei Ba, Jamie Ryan Kiros, Geoffrey E. Hinton

**Comment by skye** [comment]
Closing this issue since it looks like the corresponding PR has been merged. Please let me know if I should reopen.
