### ISSUE TITLE
pkg-config file generation

### ISSUE THREAD

**Issue by arrufat** [tensorflow/tensorflow#9703]
Hi! I was wondering if a pkg-config file for the tensorflow library (`libtensorflow.so`) could be added so that depending projects could use it more easily.

For the current stable version (`1.1.0`), if we installed it into `/usr` (which should be configurable), the generated pkg-config file `tensorflow.pc` should look something like:
```
prefix=/usr
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
modules=1

Name: tensorflow
Version: 1.1.0
Description: Library for computation using data flow graphs for scalable machine learning
Requires:
Libs: -L${libdir} -ltensorflow -lstdc++
Cflags: -I${includedir}/tensorflow
```
Thanks in advance :)

**Comment by arrufat** [comment]
I'd like to make a pull request, but I don't know how you would prefer this to be implemented.
I've just written a small shell script that generates this pkconfig file for a given prefix.
It coud be run as `./generate-pc.sh /usr`:
```bash
#!/usr/bin/env bash

TF_VERSION=`grep Release RELEASE.md | head -1 | sed -e 's/# Release //g'`

if [[ $# == 0 ]]
then
	echo "Usage:"
	echo -e "\t$0 install_prefix"
	exit
fi

TF_PREFIX=$1

echo "Generating pkgconfig file for TensorFlow $TF_VERSION in $TF_PREFIX"

cat << EOF > tensorflow.pc
prefix=${TF_PREFIX}
exec_prefix=\${prefix}
libdir=\${exec_prefix}/lib
includedir=\${prefix}/include
modules=1

Name: TensorFlow
Version: ${TF_VERSION}
Description: Library for computation using data flow graphs for scalable machine learning
Requires:
Libs: -L\${libdir} -ltensorflow -lstdc++
Cflags: -I\${includedir}/tensorflow
EOF
```
Yes, I know, the way I get the version is not the best...

**Comment by drpngx** [comment]
@yifeif is that something we'd like to have or should it be in a separate repo?

**Comment by yifeif** [comment]
@asimshankar who knows more about C API distribution :).

**Comment by asimshankar** [comment]
@arrufat : Thanks for the suggestion. This would be useful for building packaged distributions. Feel free to send a pull request adding your script and we can discuss further there. I would suggest explicitly taking the version as an argument instead of using `grep` over `RELEASE.md` and maybe an appropriate location for this script would be `tensorflow/c/generate-pc.sh`.

FYI, on OS X using [homebrew](https://brew.sh/), @kali and @ilovezfs have been kind enough to make installation as simple as `brew install libtensorflow` that [includes the pkg-config](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libtensorflow.rb)

**Comment by arrufat** [comment]
I guess this can be closed now. Thanks everyone!

**Comment by drpngx** [comment]
Great!
