### ISSUE TITLE
Changing default type from tf.int32 to tf.int64

### ISSUE THREAD

**Issue by fesun** [tensorflow/tensorflow#9781]
I am trying to allocate very large variables inside single-box, but the default out_type of some operators are tf.int32, it's too small as most modern data center machines have more than 100G memory.

Here is the operators I found:
`tf.shape(input, name=None, out_type=tf.int32)`
`tf.size(input, name=None, out_type=tf.int32)`
`tf.shape_n(input, out_type=None, name=None), out_type defaults to tf.int32`

For example if I have one [500000000000] tensor, tf.shape fails with the following error message inside Windows:

> OverflowError: Python int too large to convert to C long

Linux has the same issue and chooses overflow instead of raising exceptions.

**Comment by girving** [comment]
Unfortunately we can't change the defaults for backwards compatibility reasons.  Can you set `out_type`?

**Comment by yaroslavvb** [comment]
It's not clear this new default would be a net benefit. People seem to care a lot about training models on GPU fast. This change would double default shape transfer costs, so benchmarking would be needed to make this doesn't introduce a bottleneck that makes some model unexpectedly slow.

Fortunately in Python, there's a general technique you can use to create your own set of custom defaults, called monkey-patching.

You could have a module that rewrites TensorFlow Python public API functions with sane defaults for your applications, and because of TensorFlow API compatibility requirements, this would be easy to maintain.

Here's a fun example of monkey-patching I used to figure out who is adding 'Mul' ops to my graph. 
```
def intersept_op_creation(op_type_name_to_intercept):
  """Drops into PDB when particular op type is added to graph."""
  from tensorflow.python.framework import op_def_library
  old_apply_op = op_def_library.OpDefLibrary.apply_op
  def my_apply_op(obj, op_type_name, name=None, **keywords):
    print(op_type_name+"-"+str(name))
    if op_type_name == op_type_name_to_intercept:
      print("Why dost though add %s to my graph!!" %(op_type_name_to_intercept,))
      import pdb; pdb.set_trace()
    return(old_apply_op(obj, op_type_name, name=name, **keywords))
  op_def_library.OpDefLibrary.apply_op=my_apply_op
intercept_op_creation('Mul')

```

**Comment by fesun** [comment]
I tried to change the default type to int64 and lots of errors, seems quite a lot of dtype inference/computation depends on int32. I think most super-large tensors are used for embedding_lookup, maybe it's possible to change tf.shape out_type to int64 for some operators like gather and gather gradients.

@yaroslavvb changing default function is one possible solution, thanks.

**Comment by girving** [comment]
@fesun We'd be happy to consider localized changes.

**Comment by fesun** [comment]
@girving I changed tf.shape default out_type to int64 inside GatherGrad, everything is fine for me now. No performance impact should happen. Please see pull request #9780
