### ISSUE TITLE
Exporting and loading models with crossed_columns gives errors

### ISSUE THREAD

**Issue by jan-apptornado** [tensorflow/tensorflow#9861]
### System information
- **Have I written custom code (as opposed to using a stock example script provided in TensorFlow)**:
yes, see below
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
ubuntu 16.04
- **TensorFlow installed from (source or binary)**:
binary
- **TensorFlow version (use command below)**:
1.1.0

### Describe the problem
I trained a `LinearClassifier` that includes a `crossed_column`. When I export it and then load and run it again I get an error message: "ValueError: No op named SparseFeatureCross in defined operations".

### Source code / logs
To train and export the model I used the following python script:
```
import tensorflow as tf
from tensorflow.contrib.learn.python.learn.utils import input_fn_utils

def input_fn():
    features = {'a': tf.constant([[1],[2]]),
                'b': tf.constant([[3],[4]]) }
    labels = tf.constant([0, 1])
    return features, labels

feature_a = tf.contrib.layers.sparse_column_with_integerized_feature("a", bucket_size=10)
feature_b = tf.contrib.layers.sparse_column_with_integerized_feature("b", bucket_size=10)
feature_c = tf.contrib.layers.crossed_column([feature_a, feature_b], hash_bucket_size=100)
feature_columns = [feature_a, feature_b, feature_c]
model = tf.contrib.learn.LinearClassifier(feature_columns=feature_columns)
model.fit(input_fn=input_fn, steps=10)

feature_spec = tf.contrib.layers.create_feature_spec_for_parsing(feature_columns)
serving_input_fn = input_fn_utils.build_parsing_serving_input_fn(feature_spec)
model.export_savedmodel('simple-cross/export', serving_input_fn)
```
To load and run the model I used the following python script:
```
import tensorflow as tf

def _int_feature(value):
  return tf.train.Feature(int64_list=tf.train.Int64List(value=[value]))

with tf.Session() as session:
    model = tf.saved_model.loader.load(session, ['serve'], "simple-cross/export/1494601566/")
    probs = tf.get_default_graph().get_tensor_by_name('linear/binary_logistic_head/predictions/probabilities:0')

    feature_dict = {'a': _int_feature(value=0),
                    'b': _int_feature(value=5)}
    example = tf.train.Example(features=tf.train.Features(feature=feature_dict)).SerializeToString()
    feed_dict = { 'input_example_tensor:0' : [example] }
    print(session.run(probs, feed_dict=feed_dict))
```
(BTW: is this the best way to import/run a saved model? It feels like plugging in constants like `linear/binary_logistic_head/predictions/probabilities:0` isn't the way to go.)

This results in the following error:
```
ValueError: No op named SparseFeatureCross in defined operations.
```
### Notes
When I add the import
```
from tensorflow.contrib.learn.python.learn.utils import input_fn_utils
```
to the load/run script, it magically works.

Unfortunately, I like to run the model from Java as well, and in Java there is no analogous workaround AFAIK (input_fn_utils doesn't exist there).

**Comment by girving** [comment]
@ispirmustafa: Looks like a bug.  Can you take a look?

**Comment by ispirmustafa** [comment]
It seems saved model load couldn't find the contrib ops.
@sukritiramesh @davidsoergel do you have idea what's going on?

**Comment by sukritiramesh** [comment]
The usage of the lower level of SavedModel APIs for loading from python/saved_model seems correct. @davidsoergel Could this be stemming from export_savedmodel(...)?

**Comment by asimshankar** [comment]
Ops defined in `contrib` are built as shared libraries which need to be loaded into the address space before they are used. Currently, this load happens when the corresponding Python module is imported. Unfortunately, no other piece of code knows where to find the shared libraries for ops found in the graph.

As a workaround for now, add:

```python
from tensorflow.contrib.layers.python import ops
```

to your program before invoking `tf.saved_model.loader.load` (which triggers a [load library call](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/contrib/layers/python/ops/sparse_feature_cross_op.py#L30)), so something like:

```python
import tensorflow as tf
from tensorflow.contrib.layers.python import ops
with tf.Session() as session:
    model = tf.saved_model.loader.load(session, ['serve'], "simple-cross/export/1494601566/")
```

FWIW, you can see all the custom op libraries installed with the pip package using something like:

```sh
find $(dirname $(python -c "import tensorflow; print tensorflow.__file__")) -name "*.so"
```

Unfortunately, loading custom op libraries from within Java or other language bindings is not working at the moment, primarily because the way custom op libraries are built right now requires the use of `RTLD_GLOBAL` when loading them. We [hack this up in Python right now](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/python/pywrap_tensorflow.py#L31).

A believe a more correct solution would be to have the custom op libraries explicitly depend on the framework shared library and not rely on `RTLD_GLOBAL`, but that is a longer fix (FYI @allenlavoie)

In the mean time, possible workarounds for Java will require some source modification and compilation of `libtensorflow_jni.so`. Options include:

- Changing [`load_library.cc`](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/core/platform/posix/load_library.cc#L27) to use `RTLD_GLOBAL` and then initiating a call to [`TF_LoadLibrary`](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/c/c_api.h#L1116) from Java
- Statically linking the ops needed by [adding explicit dependencies in the BUILD rule](https://github.com/tensorflow/tensorflow/blob/r1.1/tensorflow/java/BUILD#L151)

I'm sincerely sorry that things aren't in better shape at this time. Improving support for custom (contrib) ops in other languages is on our TODO list. A related aside, ops needed for the linear model used in wide-and-deep are slowly moving towards core anyway (e.g. commit 65283e269fac1306089303143daf550b7b1a6658). 

So, if your linear model only uses the bucketize operation and not the various cross-feature ones (which are used in the wide-and-deep tutorial), then you might already be in better shape vis-a-vis being able to import your model in Java.

Hope that helps.

FYI @allenlavoie @jhseu @skye

**Comment by pavanky** [comment]
@asimshankar 

>  Improving support for custom (contrib) ops in other languages is on our TODO list. 

Any idea when this might happen ?

**Comment by allenlavoie** [comment]
@pavanky relatively soon! The code is written and tested, it just needs review and the ironing out of some final details. Mid September if things go according to schedule.

**Comment by ispirmustafa** [comment]
For crossed_column, you can switch to core versions of feature_columns. tf.feature_column.*
such as tf.feature_column.crossed_column. Exporting and loading should work if you use these ones. Also please use core version of estimator too such as tf.estimator.DNNLinearCombinedClassifier.
