### ISSUE TITLE
Wrong hyperlink in web page tutorial

### ISSUE THREAD

**Issue by Craigjw** [tensorflow/tensorflow#9905]
There is a wrong html link in text in the tutorial "Vector Representations of Words" at address https://www.tensorflow.org/tutorials/word2vec

The text is in the first paragraph after the bullet points in the Highlights section at the top of the page.

The link for:

**tensorflow_models/tutorials/embedding/word2vec.py** 
https://www.github.com/tensorflow/tensorflow/blob/r1.1/tensorflow_models/tutorials/embedding/word2vec.py

is wrong, it should point to the following address:

https://github.com/tensorflow/models/blob/master/tutorials/embedding/word2vec.py

I hope that this is helpful.

**Comment by ali01** [comment]
Thank you for the heads up, @Craigjw. We're on it.

**Comment by wolffg** [comment]
This is fixed in 1.2 and master already; this will be fixed at this location when 1.2 is made the current binary version.  We can cherrypick back to 1.1, but I don't think it's worth the trouble.

As a passing note, we should not link from 1.1 narrative docs to master code samples; this has caused confusion in the past, as the master code may not work with 1.1.  It should link to the 1.1 branch (which it's trying to do here, but there was a problem with the link format).

Again, this will be fixed very soon.

**Comment by dr4b** [comment]
This has propagated out to the root of tensorflow.org, so I'm closing.  Thanks.
