### ISSUE TITLE
Feature request: tf.nn.depthwise_conv2d_transpose

### ISSUE THREAD

**Issue by jvlmdr** [tensorflow/tensorflow#9917]
### System information
- **TensorFlow installed from (source or binary)**: source
- **TensorFlow version (use command below)**: ('v1.1.0-0-g1ec6ed5', '1.1.0')
- **Bazel version (if compiling from source)**: 0.4.5- (@non-git)
- **CUDA/cuDNN version**: 7.5/5.1
- **GPU model and memory**: NVIDIA M40, 12GB

### Describe the problem
I would like to apply a `tf.nn.conv2d_transpose` operation to each channel of a feature image independently. There is no `tf.nn.depthwise_conv2d_transpose` operation.

I tried using `tf.nn.depthwise_conv2d_native_backprop_input` however, when I try to optimize a function that involves one of these operations, it results in an error because there is no gradient operation defined:

```
LookupError: No gradient defined for operation 'DepthwiseConv2dNativeBackpropInput_1' (op type: DepthwiseConv2dNativeBackpropInput)
```

This is related to https://github.com/tensorflow/tensorflow/issues/7934

It is possible to achieve this functionality using `conv2d_transpose` by constructing a large filter with many coefficients set to zero. However, it is relatively inefficient, especially for a large number of channels.

**Comment by chzeng** [comment]
thanks  for  your  share

**Comment by RickBoss** [comment]
Why would you like to do a transpose operation to each channel of a feature image independently?

**Comment by rdinse** [comment]
```
import tensorflow as tf
import numpy as np
from tensorflow.python.framework import ops
from tensorflow.python.ops import nn_ops
from tensorflow.python.ops import array_ops

NUM_ITERATIONS = 1000

@ops.RegisterGradient("DepthwiseConv2dNativeBackpropInput")
def _DepthwiseConv2DNativeBackpropInputGrad(op, grad):
  """The derivatives for depth-wise deconvolution.
  Args:
    op: the depth-wise deconvolution op.
    grad: the tensor representing the gradient w.r.t. the output
  Returns:
    the gradients w.r.t. the input and the filter
  """
  return [None,
          nn_ops.depthwise_conv2d_native_backprop_filter(
              grad,
              array_ops.shape(op.inputs[1]),
              op.inputs[2],
              op.get_attr("strides"),
              op.get_attr("padding"),
              data_format=op.get_attr("data_format")),
          nn_ops.depthwise_conv2d_native(
              grad,
              op.inputs[1],
              op.get_attr("strides"),
              op.get_attr("padding"),
              data_format=op.get_attr("data_format"))]

filter1 = tf.Variable(np.ones((3, 3, 2, 1), dtype=np.float32))
deconv1 = tf.nn.depthwise_conv2d_native_backprop_input(
  [2, 30, 30, 2],
  filter1,
  tf.ones([2, 28, 28, 2]),
  [1, 1, 1, 1],
  "VALID")
filter2 = tf.Variable(np.ones((3, 3, 2, 1), dtype=np.float32))
deconv2 = tf.nn.depthwise_conv2d_native_backprop_input(
  [2, 32, 32, 2],
  filter2,
  deconv1,
  [1, 1, 1, 1],
  "VALID")
loss = tf.reduce_mean(tf.square(deconv2 - 1))
train_op = tf.train.AdamOptimizer(1e-4).minimize(loss)

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(filter1))
for i in range(NUM_ITERATIONS):
  print(sess.run([train_op, loss])[1], end="\r")
print(sess.run(filter1))
```

I have attempted to implement the gradient for `tf.nn.depthwise_conv2d_native_backprop_input` in the code above. If someone could tell me what is missing for a pull request (test cases, wrapper functions etc.), then I would gladly contribute.

**Comment by yongtang** [comment]
@rdinse I think you could create the PR as an open PR will likely generate more discussion and attention.

**Comment by rjbruin** [comment]
+1 for this feature request! AFAIK this is much needed for an implementation of the recent [GradNorm paper](GradNorm: Gradient Normalization for Adaptive Loss Balancing in Deep Multitask Networks).

@rdinse [Here are the contributing guidelines](https://github.com/tensorflow/tensorflow/blob/master/CONTRIBUTING.md), does that help? :)

**Comment by feihugis** [comment]
@rdinse Are you still working on this issue?

**Comment by akuz** [comment]
I am also interested in this issue, and I think I have some idea how this can be done. If you read about how the depthwise_conv2d is implemented, you will find find that "_depthwise_conv2d applies a different filter to each input channel (expanding from 1 channel to channel\_multiplier channels for each), then concatenates the results together._" -- therefore, depthwise_conv_2d_transpose could theoretically be implemented via N regular conv_2d_transpose's (where N is the number of input channels to depthwise_conv_2d) applied to the corresponding selection of the channels from the encoding, and using the corresponding selection from the filter for each, and then concatenating the results. You'd just need to know how the original depthwise_conv2d interleaves the output channels (1,1,2,2,3,3 or 1,2,3,1,2,3), so that you know how to select the correct parts of the encoding and filter for the N regular "deconvolutions". I could perhaps attempt to implement this, I will update if I do.

**Comment by akuz** [comment]
Here is an implementation for you. I don't have time to submit pull request with tests etc, but this works for me. Although, it's slower than when I use the regular conv2d and conv2d_transpose with the same number of input and output channels (and larger, full filters). If implemented in C++ (or in some other smarter way), it should be in fact faster. Anyway, at least it works. P.S. I've also tried using `tf.while_loop` when the number of channels is only known at run-time, and it also works, but I don't think this extra complication is necessary, since the number of channels is usually known at "compile time" (for TensorFlow graph).

```
def depthwise_conv2d_transpose(
  value,
  filter,
  strides,
  output_shape,
  data_format='NHWC',
  padding='SAME',
  name='depthwise_conv2d_transpose'):

  if data_format == 'NHWC':
    channel_axis = 3
    channel_output_shape = [
      output_shape[0],
      output_shape[1],
      output_shape[2],
      1]
  elif data_format == 'NCHW':
    channel_axis = 1
    channel_output_shape = [
      output_shape[0],
      1,
      output_shape[1],
      output_shape[2]]
  else:
    raise ValueError("Unsupported data_format: {}".format(data_format))

  filter_shape = filter.get_shape().as_list()
  if len(filter_shape) != 4:
    raise ValueError("Expected filter of dim 4, got filter shape: {}".format(filter_shape))

  conv_in_channels = filter_shape[2]
  if conv_in_channels is None:
    raise ValueError("Number of convolution input channels in filter (dim 2) " +
                     "must be known at compile time, got: {}".format(conv_in_channels))

  channel_multiplier = filter_shape[3]
  if channel_multiplier is None:
    raise ValueError("Channel multiplier in filter (dim 3) " +
                     "must be known at compile time, got: {}".format(channel_multiplier))

  # collect outputs for all input channeld
  c_outputs = []

  # create all operations in scope with name
  with tf.variable_scope(name):

    # regular conv2d_transpose for each input channel
    for c in range(conv_in_channels):

      # grab subset of value
      c_value = tf.gather(value,
        indices=list(range(
          channel_multiplier*c,
          channel_multiplier*c+channel_multiplier)),
        axis=channel_axis)

      # grab subset of filter
      c_filter = tf.gather(filter,
        indices=[c],
        axis=2)

      # run for this input channel
      c_outputs.append(
        tf.nn.conv2d_transpose(
          value=c_value,
          filter=c_filter,
          strides=strides,
          output_shape=channel_output_shape,
          data_format=data_format,
          padding=padding,
          name='channel{}'.format(c)))

    # concatenate outputs within variable scope
    output = tf.concat(c_outputs, axis=channel_axis, name='concat')

  return output
```

**Comment by astropeak** [comment]
Hey, I'd like to work on this. Looks it still hasn't been done. Is that alright?
