### ISSUE TITLE
I'm curious about whether these two graphs are same network

### ISSUE THREAD

**Issue by ailias** [tensorflow/tensorflow#9928]
![cifar](https://cloud.githubusercontent.com/assets/10510469/26090870/2fd017a4-3a3a-11e7-9303-13b912a8b0c1.png)
As we know, the upper graph is the provided example instance of CIFAR10. But when I copied these inference() code to my code, it likes as bellow. So my question is does these two graphs are equal? If yes, why they are looks like so different?
![cifar-my](https://cloud.githubusercontent.com/assets/10510469/26090871/2fe2502c-3a3a-11e7-8608-c5aa91324871.png)

**Comment by jubjamie** [comment]
While this is an interesting question you're better off **asking this on Stack Overflow** tagged as Tensorflow as this will get closed by the devs as it's not a bug. 

From a quick glance it looks like they do share a lot of similar components but the inference code shows the graph built together instead of what looks like the model components in the top picture. Bit i'm not sure. Hopefully those on Stack Overflow can help you more!

**Comment by skye** [comment]
@jubjamie is correct, please repost on  [StackOverflow](http://stackoverflow.com/questions/tagged/tensorflow) since it is not a  bug or feature request. There is also a larger community that reads questions there. Thanks!
